### ISSUE TITLE
Release Schedule / Security Updates

### ISSUE THREAD

**Issue by KoenLav** [nestjs/nest#10002]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I don't know for how long the current version of NestJS will receive security updates.

### Describe the solution you'd like

A release schedule or security updates schedule for NestJS.

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

Security.

**Comment by kamilmysliwiec** [comment]
Nest does not have a fixed release cycle.

- Patch releases (including security, and bug fixes) are released as needed.
- Minor releases always contain new features, with a typical time frame of 3~6 months.
- Major releases are announced ahead of time and go through a alpha/beta pre-release phases.
