### ISSUE TITLE
Suddenly jwt strategy is not recognized

### ISSUE THREAD

**Issue by s-triar** [nestjs/nest#10004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have followed along the nestjs autentication documentation and it works at first. But some reasons, jwt strategy does not work anymore because nestjs does not recognized it.

![image](https://user-images.githubusercontent.com/34316314/180588024-460e82f4-ebeb-49a8-8af0-1e7905bffe84.png)

### Minimum reproduction code

https://github.com/s-triar/usaha

### Steps to reproduce

I am using monorepo NX with nestjs and angular
1. `npm install`
2. Set up the .env file accordingly
3. Run nestjs with `nx run api:serve`
4. Run angular with `npm start`
5. Go to http://localhost:4200
6. Register yourself at `http://localhost:4200/auth/register`
7. Try to login `http://localhost:4200/auth/login`
8. Go to `http://localhost:4200/my-profile` after login or refresh

### Expected behavior

I should be able to access api `/api/user-auth/my-profile` to get my profile.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/jwt; @nestjs/passport; passport-jwt

### NestJS version

9.0.3

### Packages versions

```json
{
  "name": "usaha",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2020 browser module main",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~14.0.5",
    "@angular/cdk": "^14.0.5",
    "@angular/common": "~14.0.5",
    "@angular/compiler": "~14.0.5",
    "@angular/core": "~14.0.5",
    "@angular/flex-layout": "^14.0.0-beta.40",
    "@angular/forms": "~14.0.5",
    "@angular/material": "^14.0.5",
    "@angular/platform-browser": "~14.0.5",
    "@angular/platform-browser-dynamic": "~14.0.5",
    "@angular/router": "~14.0.5",
    "@nestjs/common": "^9.0.3",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.3",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.3",
    "@nestjs/typeorm": "^9.0.0",
    "@nrwl/angular": "14.4.2",
    "bcrypt": "^5.0.1",
    "hashids": "^2.2.10",
    "jwt-decode": "^3.1.2",
    "mysql2": "^2.3.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~7.4.0",
    "tslib": "^2.0.0",
    "typeorm": "^0.3.7",
    "uuid": "^8.3.2",
    "zone.js": "~0.11.6"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.0.5",
    "@angular-eslint/eslint-plugin": "~14.0.0",
    "@angular-eslint/eslint-plugin-template": "~14.0.0",
    "@angular-eslint/template-parser": "~14.0.0",
    "@angular/cli": "~14.0.5",
    "@angular/compiler-cli": "~14.0.5",
    "@angular/language-service": "~14.0.5",
    "@nestjs/schematics": "^9.0.1",
    "@nestjs/testing": "^9.0.3",
    "@nrwl/cli": "14.4.2",
    "@nrwl/cypress": "14.4.2",
    "@nrwl/eslint-plugin-nx": "14.4.2",
    "@nrwl/jest": "14.4.2",
    "@nrwl/linter": "14.4.2",
    "@nrwl/nest": "14.4.2",
    "@nrwl/node": "14.4.2",
    "@nrwl/workspace": "14.4.2",
    "@types/bcrypt": "^5.0.0",
    "@types/jest": "27.4.1",
    "@types/passport-jwt": "^3.0.6",
    "@types/passport-local": "^1.0.34",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "cypress": "^9.1.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "27.5.1",
    "jest-preset-angular": "~11.1.2",
    "nx": "14.4.2",
    "prettier": "^2.6.2",
    "ts-jest": "27.1.4",
    "ts-node": "~10.8.0",
    "typescript": "~4.7.2"
  }
}

```

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Your strategy injects a REQUEST scoped provider (`UserAuthService` injects [`UserService` injects `CURRENT_USER`](https://github.com/s-triar/usaha/blob/main/apps/api/src/app/user/user.service.ts#L21)). [Follow the docs on how to deal with request scoped strategies](https://docs.nestjs.com/security/authentication#request-scoped-strategies).

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
