### ISSUE TITLE
Suddenly jwt strategy is not recognized

### ISSUE THREAD

**Issue by s-triar** [nestjs/nest#10003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have followed along the nestjs autentication documentation and it works. But some reasons, jwt strategy does not work anymore because nestjs does not recognized it.

### Minimum reproduction code

https://github.com/s-triar/usaha

### Steps to reproduce

I am using monorepo NX with nestjs and angular
1. `npm install`
2. Set up the .env file accordingly
3. Run nestjs with `nx run api:serve`
4. Run angular with `npm start`
5. Go to http://localhost:4200
6. Register yourself at `http://localhost:4200/auth/register`
7. Try to login `http://localhost:4200/auth/login`
8. Go to `http://localhost:4200/my-profile` after login or refresh

### Expected behavior

I should be able to access api `/api/user-auth/my-profile` to get my profile.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/jwt; 

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
could you please run `nest info`

**Comment by s-triar** [comment]
> could you please run `nest info`

![image](https://user-images.githubusercontent.com/34316314/180588046-eb332c32-f47a-40b3-9496-85fccb91c0ff.png)

**Comment by micalevisk** [comment]
duplicate #10003

you know you could edit the description right? xD

**Comment by s-triar** [comment]
> 

yeah I know. But I dont know if I have submitted yet. Just `shift+enter` on the form.

**Comment by micalevisk** [comment]
@s-triar https://github.com/nestjs/nest/issues

**Comment by s-triar** [comment]
> @s-triar https://github.com/nestjs/nest/issues

I have searched it and the problem solved with adding JwtStrategy on the providers array. But I have added it on the providers array. but it still does not work. It works before and I do not know why it suddenly does not work

**Comment by s-triar** [comment]
It is on the the problem is in this path `apps\api\src\app\auth`

**Comment by micalevisk** [comment]
then it's not a bug, right?

**Comment by s-triar** [comment]
@micalevisk to be honest I dont know the term

**Comment by micalevisk** [comment]
fw = framework

> it suddenly does not work

btw there's no way to it happened in node. You have either changed the source code or updated the `node_modules` by running `npm install` (that's one of the reasons you should use `npm ci` instead)

**Comment by s-triar** [comment]
I will let you know after `npm ci` finished

**Comment by s-triar** [comment]
@micalevisk It still does not work even after performing `npm ci`

> fw = framework
> 
> > it suddenly does not work
> 
> btw there's no way to it happened in Node. You have either changed the source code or updated the `node_modules` by running `npm install` (that's one of the reasons you should use `npm ci` instead)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
