### ISSUE TITLE
MqttRecordBuilder doesn't publish any additional properties.

### ISSUE THREAD

**Issue by kpostekk** [nestjs/nest#10016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Creating `MqttRecord` using `MqttRecordBuilder` does not send properties (userProperties, responseTopic) to the mqtt and other listners.

> letf side: ClientProxy emitting records
> right side: Controller receiving payload and context.
![image](https://user-images.githubusercontent.com/30326322/180744336-dcdfc518-f1d9-482a-afee-82d48bc9dd26.png)

> code that emits data
```ts
@Injectable()
export class StatusPublisherService
  extends MicroserviceClient
  implements OnModuleDestroy, OnModuleInit
{
  private heartbeat: NodeJS.Timer | null = null
  private readonly replicaName: string

  constructor(@Inject('STATUS_PUBLISHER') client: ClientProxy) {
    super(client)
    this.replicaName = os.hostname()
  }

  onModuleInit() {
    this.heartbeat = setInterval(() => {
      const record = new MqttRecordBuilder('mydata')
        .setProperties({
          userProperties: { not: 'data' },
          responseTopic: 'any/response',
        })
        .build()
      this.client.emit('replica/copy/heartbeat', record)
      console.log(record)
    }, 500)
  }

  onModuleDestroy() {
    if (this.heartbeat) {
      clearInterval(this.heartbeat)
    }
  }
}
```

> code that receives data
```ts
@Controller('hypervisor')
export class HypervisorController {
  @MessagePattern('#')
  passHeartbeats(@Payload() payload: string, @Ctx() context: MqttContext) {
    console.log({ packet: context.getPacket(), payload})
  }
}
```

> data on the mqtt broker
![image](https://user-images.githubusercontent.com/30326322/180745319-04708f76-e23f-453a-91b7-c91b68191e25.png)

### Minimum reproduction code

https://github.com/kpostekk/mqtt-nestjs-bug

### Steps to reproduce

1. yarn
2. yarn start
3. optional, connect to mqtt broker to see transmitted data

### Expected behavior

Everything from https://docs.nestjs.com/microservices/mqtt#record-builders

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.5

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v18.2.0
YARN Version    : 1.22.18 

[Nest CLI]
Nest CLI Version : 9.0.0

[Nest Platform Information]
platform-express version : 9.0.5
microservices version    : 9.0.5
serve-static version     : 3.0.0
schematics version       : 9.0.1
passport version         : 9.0.0
swagger version          : 6.0.4
testing version          : 9.0.5
common version           : 9.0.5
core version             : 9.0.5
cli version              : 9.0.0

### Node.js version

18.2.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Make sure to set the protocol version to 5 in both server and client configuration:

```typescript
app.connectMicroservice<MicroserviceOptions>({
  transport: Transport.MQTT,
  options: {
    url: 'mqtt://0.0.0.0:1883',
    protocolVersion: 5,
  },
});
```

(don't forget about updating the configuration you pass to the `ClientsModule` too).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
