### ISSUE TITLE
Sample code is outdated: graphqlExpress is undefined

### ISSUE THREAD

**Issue by yardz** [nestjs/nest#1001]
## I'm submitting a Documentation issue on GRAPHQL
<pre><code>
[ ] Regression
[ ] Bug report
[ ] Feature request
[ x] Documentation issue or request
</code></pre>

## Current behavior
When starting a new project using graphql the lib "graphqlExpress" returns undefined
<code>import { graphqlExpress } from 'apollo-server-express';</code>

I have identified that this code works with dependency {"apollo-server-express": "^ 2.0.0-beta.7"} but currently when installed it comes as {"apollo-server-express": "^ 2.0.4 "}

## Minimal reproduction of the problem with instructions
-Start a new project using cli.
-Follow graphql's quick start
You can display the value of "graphqlExpress" in the console to verify that it is undefined

## What is the motivation / use case for changing the behavior?
I find it very important that the basic tutorial work correctly. It is very bad when it is necessary to keep breaking your head to make the basic tutorial work.
I also find it important to keep the dependencies always updated

## Environment

<pre><code>
Nest version: ^5.0.0

 
For Tooling issues:
- Node version: v10.6.0
- Platform:  Mac

Others:
Version of the lib that the example works on: apollo-server-express ^2.0.0-beta.7,
Version of lib that is installed when starting a new project (most current):  apollo-server-express ^2.0.4

If you only change the version of apollo-server-express everything works correctly.

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed
