### ISSUE TITLE
INestApplication doesn't resolve close() as a property when running e2e tests

### ISSUE THREAD

**Issue by nakajimayoshi** [nestjs/nest#10014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Running `npm run test:e2e` throws the following error: 

TypeError: Cannot read properties of undefined (reading 'close') 

this prevents the app from closing. Leaving multiple ports open when running tests, and causing subsequent tests to fail when ran on the same port.

speficially, it cannot read the property close() property from the 'INestApplication' interface from @nestjs/testing. This is used to define app.close(); 

```ts
import { Test } from '@nestjs/testing';
import { AppModule } from '../src/app.module';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import { PrismaService } from '../src/prisma/prisma.service';
import * as pactum from 'pactum';
import { AuthDto } from '../src/auth/dto';

describe('App e2e', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
        imports: [AppModule],
    }).compile();
    const app = moduleRef.createNestApplication();
    app.useGlobalPipes(
        new ValidationPipe({
          whitelist: true,
        }),
    );
    const port = 3060;
    await app.init();
    await app.listen(port);
    prisma = app.get(PrismaService)
      await prisma.cleanDb();
    pactum.request.setBaseUrl(`http://localhost:${port}`)
  });

  afterAll(() => {
      app.close();
  });
```
result: 
![image](https://user-images.githubusercontent.com/52870481/180713376-fbcfc733-fe96-43f1-9136-dc96c3c88a2d.png)

### Minimum reproduction code

https://github.com/nakajimayoshi/auth-api

### Steps to reproduce

1. Download the repo and open in an IDE

2. Setup env variables 

3. Run the following command:

# test coverage
$ `npm run test:e2e`

### Expected behavior

Unit test should pass 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
 "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@prisma/client": "^4.1.0",
    "argon2": "^0.28.7",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "dotenv-cli": "^6.0.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "prisma": "^4.1.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
```

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This is most likely from never closing the `PrimsaClient`. You should create an `OnApplicationShutdown` hook that closes the connection to ensure the server can properly shutdown.

**Comment by nakajimayoshi** [comment]
Hey there, thanks for replying. 
The best I could find in the documentation was https://docs.nestjs.com/recipes/prisma#issues-with-enableshutdownhooks

but the enableShutdownHooks property does not exist on the PrismaService type

**Comment by jmcdo29** [comment]
https://docs.nestjs.com/fundamentals/lifecycle-events#lifecycle-events-1

**Comment by nakajimayoshi** [comment]
Hi there, I found this:  

"Due to inherent platform limitations, NestJS has limited support for application shutdown hooks on Windows. You can expect SIGINT to work, as well as SIGBREAK and to some extent SIGHUP - [read more](https://nodejs.org/api/process.html#process_signal_events). However SIGTERM will never work on Windows because killing a process in the task manager is unconditional, "i.e., there's no way for an application to detect or prevent it". Here's some [relevant documentation](https://docs.libuv.org/en/v1.x/signal.html) from libuv to learn more about how SIGINT, SIGBREAK and others are handled on Windows. Also, see Node.js documentation of [Process Signal Events](https://nodejs.org/api/process.html#process_signal_events)"

so does that mean it's impossible to kill test-db instances on windows?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
