### ISSUE TITLE
app.startAllMicroservices does not throw an error in case of bad microservice start

### ISSUE THREAD

**Issue by Turentkm** [nestjs/nest#10029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Continuing the issue from previous report and solution mr:
* https://github.com/nestjs/nest/issues/9749
* https://github.com/nestjs/nest/pull/9751

Atm the service initiated as hybrid app GraphQL & RMQ microservice.
```
async function bootstrap(): Promise<void> {
  const app = await NestFactory.create(MicroserviceModule);
  app.enableCors();
  app.useGlobalPipes(new ValidationPipe());
  app.connectMicroservice(TransportersConfig.MICROSERVICE);
  await app.startAllMicroservices();
  await app.listen(RESOURCES_MS_PORT);
}
bootstrap();
```
The issue occurs when the microservice failed to connect to RMQ and launch it self. Previously it was stuck in infinite loop trying to reconnect, but that was "fixed"(both issue and fix above). BUT! The "fix" created yet another issue, but now with privacy.

The current workflow is - if the connection to microservice failed, log the error to the user and continue regular flow.
Technically, we still getting stuck in infinite loop, but now we log the error to inform of what happened. 
Yet, the error that is being thrown 
```
[Nest] 11196  - 07/27/2022, 2:00:57 PM   ERROR [Server] Connection to transport failed. Trying to reconnect...
[Nest] 11196  - 07/27/2022, 2:00:57 PM   ERROR [Server] Object:
{
  "err": {
    "errno": -3008,
    "code": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": *actual host name*
  },
  "url": {
    "protocol": "amqp",
    "hostname": *actual host name*
    "port": 5672,
    "username": *REAL_USERNAME*,
    "password": *REAL_PASSWORD*
  }
}
```
**This is HUGE security leak, which need to be fixed ASAP.**

Besides the security issue, there is no way to indicate if the microservice should be restarted, based on the current flow. For my current project, it is mandatory to have RMQ microservice running, since the communications between multiple apps is being done via transporters. 
If the ms is not connected to the transporter, the pod needs to drop and restart it self. 
In order to do this, with the current flow, first, the microservice needs to initiate (which it cant do, cause of the retry logic), but even if it did start, the next logic needs to be added to the .module.ts code:
```
imports: [ClientsModule.register([
  { name: 'REDIS_CLIENT', transport: Transport.REDIS },
])],
....

constructor(@Inject('RMQ_CLIENT') private readonly client: ClientProxy) {
}

async onModuleInit() {
  await this.client.connect();
  setInterval(async () => {
    try {
      await this.client.emit('healthcheck', 'healthcheck').toPromise();
    } catch (e) {
      // Sending the message has failed, start recovery
      console.error(e);
      process.exit(1);
    }
  }, 1000);
}
```

This is an awkward way to check if the microservice was connected, instead of handling an error in `.catch` block after - `app.startAllMicroservices()`

### Minimum reproduction code

https://github.com/Turentkm/test-rmq-connection

### Steps to reproduce

1. npm update
2. npm ci
3. add .env with the variables for your RMQ.
4. npm run start:dev

### Expected behavior

1. The logging of the error will be wrappr or altered with info message.
2. Rethrow the error out of startAllMicroservices or return the server object to handle the error in the desired way (stop the app/or throw process error to allow the handling to kubernetes etc.)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.7

### Packages versions

```
[System Information]
OS Version     : Windows 10
NodeJS Version : v14.17.3
NPM Version    : 6.14.13 

[Nest CLI]
Nest CLI Version : 8.2.8

[Nest Platform Information]
platform-express version : 8.4.7
microservices version    : 8.4.7
schematics version       : 8.0.11
mongoose version         : 8.0.1
graphql version          : 9.1.2
testing version          : 8.4.7
common version           : 8.4.7
config version           : 1.2.1
axios version            : 0.0.7
core version             : 8.4.7
cli version              : 8.2.8
```

### Node.js version

14.17.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
If you need such behavior, is there any reason why you use the hybrid application approach? Why not `NestFactory.createMicroservice()` (and no `connectMicroservice `) instead?

**Comment by Turentkm** [comment]
> If you need such behavior, is there any reason why you use the hybrid application approach? Why not `NestFactory.createMicroservice()` (and no `connectMicroservice `) instead?
> 
> I checked the repository you linked and using the `connectMicroservice` in this case makes no sense.

The overall structure of the project consists of multiple applications being hybrid applications. All of them provide api functionality via GraphQL but also handles communications between one another. |
This was required to distribute the load and to separate the different requests for data, besides the fact that each microservice is working with its own db. Also we have multiple http requests being handled by each microservice from kubernetes to handle multiple workflows.

From the documentation provided, I saw such example here -  https://docs.nestjs.com/faq/hybrid-application. This solution was giving us the required functionality.

If there is a better approach, I would gladly look into it.
