### ISSUE TITLE
Nest build cli converts dynamic import to require

### ISSUE THREAD

**Issue by Dabada** [nestjs/nest#10047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use the dynamic import of commonJS, nest build converts it into a require inside a resolved promise.

My code
`const queue = new (await import('p-queue')).default({ concurrency: 2 });`

Code generated by nest buid:
`const queue = new (await Promise.resolve().then(() => require('p-queue'))).default({ concurrency: 2 });`

this conversion leads to the following error at runtime:

`Error [ERR_REQUIRE_ESM]: require() of ES Module .\node_modules\p-queue\dist\index.js from .\dist\mailer\mail\mail.service.js not supported.
Instead change the require of index.js in .\dist\mailer\mail\mail.service.js to a dynamic import() which is available in all CommonJS modules.`

### Minimum reproduction code

https://codesandbox.io/s/nest-cli-build-convert-dynamique-import-into-require-e2o24v?file=/src/app.service.ts

### Expected behavior

Keep the dynamic import as is. It works fine.

I've change the code generated by nest build in dist directory, and replaced 

`const queue = new (await Promise.resolve().then(() => require('p-queue'))).default({ concurrency: 2 });`
BY
`const queue = new (await import('p-queue')).default({ concurrency: 2 });`

no more errors and everything works fine.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

nest-cli 

### NestJS version

9.0.3

### Packages versions

```
nest i

 _   _             _      ___  _____  _____  _     _____ 
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |  
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |  
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_ 
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/ 


[System Information]
OS Version     : Windows 10
NodeJS Version : v16.11.1
YARN Version    : 1.22.5 

[Nest CLI]
Nest CLI Version : 9.0.0   

[Nest Platform Information]
platform-socket.io version : 9.0.3
platform-fastify version   : 9.0.3
microservices version      : 9.0.3
mapped-types version       : 1.1.0
schematics version         : 9.0.1
passport version           : 9.0.0
swagger version            : 6.0.3
typeorm version            : 9.0.0
testing version            : 9.0.3
common version             : 9.0.3
config version             : 2.2.0
core version               : 9.0.3
jwt version                : 9.0.0
cli version                : 9.0.0
 version                   : 1.7.1
```

### Node.js version

v16.11.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This looks like something Typescript (tsc) is doing instead of Nest. If you run `tsc -p tsconfig.build.json` you get the same output, so this is unrelated to the Nest CLI

**Comment by Dabada** [comment]
You're right! My bad :-)

**Comment by LeonManolo** [comment]
how did you fix that?

**Comment by Dabada** [comment]
check here: https://github.com/microsoft/TypeScript/issues/50109
