### ISSUE TITLE
Response mapping. Duplicate nesting level.

### ISSUE THREAD

**Issue by ph55** [nestjs/nest#1004]
Response map from official doc return duplicate nesting level.
https://docs.nestjs.com/interceptors
```ts
import { Injectable, NestInterceptor, ExecutionContext } from '@nestjs/common';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

export interface Response<T> {
  data: T;
}

@Injectable()
export class TransformInterceptor<T>
  implements NestInterceptor<T, Response<T>> {
  intercept(
    context: ExecutionContext,
    call$: Observable<T>,
  ): Observable<Response<T>> {
    return call$.pipe(map(data => ({ data })));
  }
}
```

Response for
```ts
@Get()
async test(): Promise<any> {
  return 'ok';
}
```
is:

```ts
{
  data: {
    data: "ok"
  }
}
```

**Comment by kamilmysliwiec** [comment]
I suppose you have bounded the same interceptor twice. Just tested locally, no issues.

**Comment by ph55** [comment]
So I've tested in controller with `@UseInterceptors(new ResponseInterceptor())` works well.

**But** when used in module with provider I get duplicate nesting, hmm...
```ts
{
  provide: APP_INTERCEPTOR,
  useClass: ResponseInterceptor
}
```

**Comment by ph55** [comment]
Ok, so I can reproduce with 5.0.1 in dummy app.
https://github.com/ph55/nest-int

After updating to 5.1.0 issue gone.

Don't know if it worth to understand what was cause.
I'll update to latest version.
