### ISSUE TITLE
Unable to load playground in newer version of @nestjs dependency set

### ISSUE THREAD

**Issue by mdv27** [nestjs/nest#10051]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current behavior

I didn't find similar issue.
When application started and http://localhost:4000/graphql path accessed, it renders client/index.html.
![image](https://user-images.githubusercontent.com/12114755/182107817-c0e28991-328a-4861-8d32-2d1c1ababe5d.png)

### Minimum reproduction code

https://github.com/mdv27/nestjs-graphql-test-app

### Steps to reproduce

1. npm ci
2. npm run start

### Expected behavior

There should be graphql playground page loaded as mentioned [here](https://docs.nestjs.com/graphql/quick-start#graphql-playground) 
As with below version set it works fine:
```json
{
  "dependencies": {
    "@apollo/gateway": "^0.26.1",
    "@azure/storage-blob": "^12.5.0",
    "@nestjs/common": "^7.5.1",
    "@nestjs/config": "^0.6.3",
    "@nestjs/core": "^7.5.1",
    "@nestjs/graphql": "^7.10.6",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/serve-static": "^2.1.4",
    "apollo-datasource-rest": "^3.4.0",
    "apollo-server": "^2.25.0",
    "applicationinsights": "^2.3.1",
    "axios": "^0.21.1",
    "axios-mock-adapter": "^1.20.0",
    "axios-request-throttle": "^1.0.0",
    "azure-devops-node-api": "^11.1.1",
    "execution-time": "^1.4.1",
    "graphql": "^15.8.0",
    "graphql-parse-resolve-info": "^4.12.0",
    "graphql-request": "^3.4.0",
    "limiter": "^2.1.0",
    "nest-neo4j": "0.1.4",
    "pluralize": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3",
    "tedious": "^11.4.0",
    "win-node-env": "^0.4.0",
    "winston": "^3.7.2",
    "winston-azure-application-insights": "^4.0.0"
  }
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

9.0.1

### Packages versions

```json
{
 "dependencies": {
    "@graphql-tools/utils": "8.8.0",
    "@nestjs/apollo": "10.0.17",
    "@nestjs/common": "9.0.1",
    "@nestjs/core": "9.0.1",
    "@nestjs/graphql": "10.0.18",
    "@nestjs/platform-express": "9.0.1",
    "@nestjs/serve-static": "^3.0.0",
    "apollo-server": "3.9.0",
    "apollo-server-express": "3.9.0",
    "class-transformer": "0.5.1",
    "class-validator": "0.13.2",
    "graphql": "16.5.0",
    "graphql-subscriptions": "2.0.0",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.5.5"
  }
}
```

### Node.js version

14.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I am using `@nestjs/serve-static` for loading my client side code which is in angular.  For demo purpose I just added plain html.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
