### ISSUE TITLE
Req.body is not parsed and available in global middlewares

### ISSUE THREAD

**Issue by Pixelatus** [nestjs/nest#10057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to use req.body inside a global middleware (https://docs.nestjs.com/middleware#global-middleware) i am unable to access the body since body-parser is called after.

Cannot use Functional middleware or Class middleware since the middleware that I am trying to use is exported from a private npm package and it is strictly made using express-type middlewares.

I would appreciate any possible solution, thank you.

### Minimum reproduction code

not needed

### Expected behavior

Req.body to be available in global middlewares

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

7.6.13

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
if you can call `app.use(mid)`, you can use functional/class middleware as well. I didn't follow :thinking:

**Comment by Pixelatus** [comment]
the 'mid' middleware is a simple method with signature 'function mid(req, res, next): void' exported from a private package.
What I do now is:

```
import { NestFactory } from '@nestjs/core';
import { AppModule } from '@src/app.module'
import { mid } from 'private-package';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.use(mid);
  await app.listen(3000);
 }
```
The problem is that this 'mid' middleware meeds req.body, so body-parser needs to be called before app.use(mid). And I suppose adding body-parser middleware by hand before linking 'mid' middleware is not the best solution.

**Comment by micalevisk** [comment]
```ts
export class PrivateMiddleware implements NestMiddleware {
  use = mid();
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

+ this has been discussed +100 times in the past 😅
