### ISSUE TITLE
Error when enabling graphiql in Mercurius

### ISSUE THREAD

**Issue by max0000402** [nestjs/nest#10056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When enabling graphiql in Mercurius, an error occurs:
```
/home/max/errortest/node_modules/fastify/lib/pluginUtils.js:118
    throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
          ^
FastifyError: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.3.0' is installed
```

### Minimum reproduction code

https://github.com/max0000402/nestjs_mercurius_error

### Steps to reproduce

1. `npm install`
2.  `npm run start:dev`

### Expected behavior

The application should start without errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/mercurius

### NestJS version

9.0.7

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^10.0.21",
    "@nestjs/mercurius": "^10.0.21",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-fastify": "^9.0.7",
    "graphql": "^16.5.0",
    "mercurius": "^9.8.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
},
"devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
}
```

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Upgrade mercurius to version 10 or greater. Version 9.8 is compatible with fastify 3 and nest v9 uses fastif y4
