### ISSUE TITLE
[error][]: -> uncaught error, Cannot read properties of undefined (reading 'databaseName'), TypeError: Cannot read properties of undefined (reading 'databaseName')

### ISSUE THREAD

**Issue by 516744942** [nestjs/nest#10058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

    const [list, total] = await
      noticeRepo.createQueryBuilder("notice")
        .where("notice.isRead=:isRead", { isRead: NoticeReaType[getDto.readType] })
        .andWhere("notice.reciverId=:reciverId", { reciverId: user.id })
        .orderBy({"notice.create_date":"DESC"})
        .innerJoinAndSelect(
          "notice.activity",
          "activity",
          "activity.activity_type!=:activity_type",
          { activity_type: ActivityTypeEnum.APPROVE }
        )
        .skip(paging.skip)
        .take(paging.take)
        .getManyAndCount()
        
        
        
       Error reporting using innerJoinAndSelect、orderBy and skip

### Minimum reproduction code

no

### Steps to reproduce

use  innerJoinAndSelect、orderBy and skip

### Expected behavior

get list and total

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

typeorm

### NestJS version

8.0.6

### Packages versions

```json

```

### Node.js version

v16.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
