### ISSUE TITLE
Logger and ConsoleLogger don't work as expected by their types

### ISSUE THREAD

**Issue by Gerrit-K** [nestjs/nest#10069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There are several cases where the logging methods don't behave as one could expect, based on the type signature. Most notably, the optional parameters `context` and `stack` are not handled correctly in those cases, as can be seen in this example:

```ts
// ...
  private logger: Logger = new Logger('topContext');
  private loggerWithoutTopContext: Logger = new Logger();
  private consoleLogger = new ConsoleLogger('topContext');
  private consoleLoggerWithoutTopContext = new ConsoleLogger();
// ...
    this.logger.log('message'); // works as intended
    this.logger.log('message', 'context'); // context doesn't override logger context but is printed as an additional message instead
    this.logger.error('message', 'stack'); // works as intended
    this.logger.error('message', 'stack', 'context'); // context doesn't override logger context and stack is not printed as a stack trace but rather as an additional message

    this.loggerWithoutTopContext.log('message'); // works as intended
    this.loggerWithoutTopContext.log('message', 'context'); // works as intended
    this.loggerWithoutTopContext.error('message', 'stack'); // stack is misinterpreted as context
    this.loggerWithoutTopContext.error('message', 'stack', 'context'); // works as intended

    this.consoleLogger.log('message'); // works as intended
    this.consoleLogger.log('message', 'context'); // works as intended
    this.consoleLogger.error('message', 'stack'); // stack is misinterpreted as context
    this.consoleLogger.error('message', 'stack', 'context'); // works as intended

    this.consoleLoggerWithoutTopContext.log('message'); // works as intended
    this.consoleLoggerWithoutTopContext.log('message', 'context'); // works as intended
    this.consoleLoggerWithoutTopContext.error('message', 'stack'); // stack is misinterpreted as context
    this.consoleLoggerWithoutTopContext.error('message', 'stack', 'context'); // works as intended
```
The output of this is:
```log
[Nest] 70039  - 04/08/2022, 14:38:46     LOG [topContext] message
[Nest] 70039  - 04/08/2022, 14:38:46     LOG [topContext] message
[Nest] 70039  - 04/08/2022, 14:38:46     LOG [topContext] context
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [topContext] message
stack
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [topContext] message
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [topContext] stack
context
[Nest] 70039  - 04/08/2022, 14:38:46     LOG message
[Nest] 70039  - 04/08/2022, 14:38:46     LOG [context] message
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [stack] message
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [context] message
stack
[Nest] 70039  - 04/08/2022, 14:38:46     LOG [topContext] message
[Nest] 70039  - 04/08/2022, 14:38:46     LOG [context] message
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [stack] message
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [context] message
stack
[Nest] 70039  - 04/08/2022, 14:38:46     LOG message
[Nest] 70039  - 04/08/2022, 14:38:46     LOG [context] message
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [stack] message
[Nest] 70039  - 04/08/2022, 14:38:46   ERROR [context] message
stack
```

### Minimum reproduction code

https://github.com/Gerrit-K/nestjs-logger-mre/blob/main/src/app.service.ts

### Steps to reproduce

Just start the app using `npm run start`. The logs will appear in the `onModuleInit` hook.

### Expected behavior

_Ideally_ `context` and `stack` should always be printed correctly. However, since both are of type `string` this might be tricky. If not possible, then it might be worth considering fixing the types in some way that they don't suggest different behavior. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^9.0.0

### Packages versions

```json
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).

If `Logger` has a predefined context (passed as the constructor parameter), other arguments will behave similar to the built-in `console.log` meaning, each argument will be printed in a new line.
