### ISSUE TITLE
"404 Not Found" is misleading and confusing as a default status code.

### ISSUE THREAD

**Issue by hakamdev** [nestjs/nest#10064]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

`nest version 9.0.0`
I noticed that nest returns a `404 Not Found` when you try to send an http method that is not yet implemented for a particular controller, which I find confusing, as 404 means the request resource is not existent but not necessarily the method in not implemented or not allowed.

### Describe the solution you'd like

My proposal is simply replacing the default status code in this case `404 Not Found`, with a more meaningful status code such as 
- `405 Method Not Allowed` , which describes exactly what's happening, that is, the http method is not allowed for this endpoint.
- Or `403 Forbidden`, which indicates that the requested method is forbidden for this particular endpoint.

### Teachability, documentation, adoption, migration strategy

This is a minor change that requires no special documentation.

### What is the motivation / use case for changing the behavior?

To avoid confusion, so when front-end devs would test a particular http method on a nest server, they would realize that such a method is not allowed, and perhaps request the back-end devs to add it. instead of just thinking that there is no data to return.

**Comment by micalevisk** [comment]
I didn't follow. Are you talking about `@nestjs/cli` generated files?

**Comment by hakamdev** [comment]
@micalevisk no, but nest itself, when there a controller with no `Delete` method for example, it returned status code is `404`, so you don't know whether it's the resource you are deleting that doesn't exist, or the Delete method itself that's implemented.
<img width="1032" alt="Screen Shot 2022-08-04 at 02 05 20" src="https://user-images.githubusercontent.com/29928577/182743939-bed029e3-4dc1-460d-a152-866a03838594.png">

**Comment by micalevisk** [comment]
if the route didn't exist replying with something other than 404 just sounds wrong

You can change that behavior in your app tho

**Comment by hakamdev** [comment]
@micalevisk yes, I agree with 404 IF the route doesn't exists, but in this case the route exists, not the it's the http method that doesn't exist.

**Comment by micalevisk** [comment]
> but in this case the route exists, not the it's the http method that doesn't exist.

then the route didn't exists, you know? the route is made by its HTTP verb + path

**Comment by hakamdev** [comment]
<img width="464" alt="Screen Shot 2022-08-04 at 02 39 44" src="https://user-images.githubusercontent.com/29928577/182744635-842366e6-f008-4cb2-b211-3ddbf1602b0e.png">
@micalevisk take for example this controller, all it has is `@Get` if I try Delete method on this route what would I get in this case?

**Comment by micalevisk** [comment]
404 Not found, as there's no `DELETE /items` route

**Comment by hakamdev** [comment]
@micalevisk alright, thank you for the discussion.

**Comment by nick-lironi-irvine** [comment]
FWIW I agree with the reporter on the expected behaviour. 

> then the route didn't exist, you know? A route is made by its HTTP verb + path (conceptually speaking)

This sounds like it might be an implementation choice of Nest, or the underlying router, but that doesn't match my understanding of the HTTP spec! 
I think that conceptually there is a URI for a resource, like /items, and then various methods like GET or DELETE can be applied to it.
https://httpwg.org/specs/rfc9110.html#status.405 says that a 404 is appropriate when the target resource (/items in this example) cannot be resolved, but that 405 applies when the target resource can be resolved but the method is not supported.
