### ISSUE TITLE
use SQL statements

### ISSUE THREAD

**Issue by hijulien** [nestjs/nest#10068]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I think typeorm is an over encapsulated behavior and it is not as flexible as SQL statements. What should I do if I want to use native SQL statements?

### Describe the solution you'd like

I can use mysql2 package to connect to the database and use native SQL statements to manipulate the database

### Teachability, documentation, adoption, migration strategy

none

### What is the motivation / use case for changing the behavior?

1. Learning typeorm has no effect

2. Typeorm is not as flexible as SQL statements

**Comment by micalevisk** [comment]
`@nestjs/typeorm` isn't typeorm

Go to their repo instead: https://github.com/typeorm/typeorm/
