### ISSUE TITLE
CORS error with fastify adapter on 9.0.0

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [nestjs/nest#10067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am getting cors error if use FastifyAdapter however there is no error if i use ExpressAdapter (default)

### Minimum reproduction code

...

### Expected behavior

No cors error for Fastify adapter

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0+

### Packages versions

```json
"@fastify/static": "^6.5.0",
        "@nestjs/common": "^9.0.8",
        "@nestjs/core": "^9.0.8",
        "@nestjs/jwt": "9.0.0",
        "@nestjs/passport": "9.0.0",
        "@nestjs/platform-express": "^9.0.8",
        "@nestjs/platform-fastify": "^9.0.8",
        "@nestjs/swagger": "^6.0.5",

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
