### ISSUE TITLE
@inject @injectmodule not working in Middleware

### ISSUE THREAD

**Issue by sinbargit** [nestjs/nest#10065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

@inject @injectmodule not working in Middleware. I need using Sequelize in middleware, but it not working. 
Here is the code refer to middleware in app module:
```
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(AppMiddleWare)
      .forRoutes('*');
  }
}
```
Here is the code for middleware:
```
import { Injectable, NestMiddleware, Inject } from '@nestjs/common'
import { InjectModel } from '@nestjs/sequelize'
import { Request, Response, NextFunction } from 'express'
import { genUuid } from './utils'
import { ZsSession } from '@/model/zs-session.model'
import {
  ValidateSessionAction,
  ValidateSessionActionParam
} from '@/api/zstack/ValidateSessionAction'

@Injectable()
export class AppMiddleWare implements NestMiddleware {
  @Inject() validateSessionAction: ValidateSessionAction
  @InjectModel(ZsSession) private zsSession: typeof ZsSession

  async use(req: Request, res: Response, next: NextFunction) {
    const sessionId = req.headers['x-session-id'] as string
    const session = this.zsSession.findOne({ where: { sessionUuid: sessionId } })
    if (!session) {
      this.logger.debug(`session invalid ${sessionId} not in db`)
      res.status(401).send()
      return
    }
     ......
    next()
  }
}

```
the `this.zsSession is undefinded`
How to fix it?

### Minimum reproduction code

please see my desc

### Expected behavior

@inject @injectmodule working fine in Middleware. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.0.0

### Packages versions

 "@nestjs/common": "7.0.0",
    "@nestjs/config": "0.4.1",
    "@nestjs/core": "7.0.0",
    "@nestjs/graphql": "7.3.7",
    "@nestjs/platform-express": "7.0.0",
    "@nestjs/schedule": "0.4.0",
    "@nestjs/sequelize": "0.1.0",
    "@nestjs/serve-static": "^2.1.4",

### Node.js version

14.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
1) Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

2) any reason to use property injection vs constructor injection?

**Comment by sinbargit** [comment]
@jmcdo29 
1  here is the respository:https://codesandbox.io/s/bold-wave-05s8gc?file=/src/app.middleware.ts
2 I need to verfiry the auth in a moddleware: in the respository is in app.middleware.ts

**Comment by jmcdo29** [comment]
What am I supposed to do with this reproduction? Half the files are missing, there's no database, and it doesn't compile, let alone start.

If you can provide a minimum reproduction, as described by the link above, I'll re-open the issue and take a look, until then I can only assume you have something misconfigured

**Comment by sinbargit** [comment]
I have fix the respository, not it can be debug now. https://codesandbox.io/s/icy-frog-spv4ol?file=/src/app.service.ts.
Please take a look.

**Comment by sinbargit** [comment]
@jmcdo29  I have make a reproduction as you require, please take a look https://codesandbox.io/s/icy-frog-spv4ol?file=/src/app.middleware.ts

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
