### ISSUE TITLE
Logger should have support for file logging in prod environment.

### ISSUE THREAD

**Issue by dharmendrasha** [nestjs/nest#10070]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We do not want console logging in production it should have build in functionality to file logging.

### Describe the solution you'd like

Where we can specify the full path and file name of the file to be logged in

### Teachability, documentation, adoption, migration strategy

User can esiliy disable enable file logging service based in environment variables

### What is the motivation / use case for changing the behavior?

When we host the service in production inside docker we might lost our all logs until last restart of the container.

**Comment by dharmendrasha** [comment]
wrote a simple file logger on a dali basis hope this help

```import { ConsoleLogger, LogLevel } from '@nestjs/common'
import { yellow } from '@nestjs/common/utils/cli-colors.util'
import * as fs from 'fs'
import * as path from 'path'

class CustomError extends ConsoleLogger {
  private _shouldWriteToTheFile = false
  private _pathToWrite: string = __dirname
  private _fileName = `${new Date().getDate()}-${new Date().getMonth()}-${new Date().getFullYear()}.log`

  set pathToWrite(path: string) {
    this._pathToWrite = path
  }

  set shouldWriteToThePath(should: boolean) {
    this._shouldWriteToTheFile = should
  }

  printMessages(
    messages: unknown[],
    context?: string,
    logLevel?: LogLevel,
    writeStreamType?: 'stdout' | 'stderr',
  ) {
    const resolvePath = path.resolve(this._pathToWrite, this._fileName)
    messages.forEach(message => {
      const pidMessage = this.formatPid(process.pid)
      const contextMessage = context ? yellow(`[${context}] `) : ''
      const timestampDiff = ''
      const formattedLogLevel = logLevel.toUpperCase().padStart(7, ' ')
      const formattedMessage = this.formatMessage(
        logLevel,
        message,
        pidMessage,
        formattedLogLevel,
        contextMessage,
        timestampDiff,
      )

      if (this._shouldWriteToTheFile) {
        fs.appendFile(resolvePath, formattedMessage, err => {
          if (err) throw err
        })
      } else {
        process[writeStreamType ?? 'stdout'].write(formattedMessage)
      }
    })
  }

  constructor(context: string) {
    super(context)
  }
}

const logger = new CustomError('App')
logger.pathToWrite = path.resolve(__dirname, '..', '..', 'logs')
logger.shouldWriteToThePath = false
export { logger }
```

**Comment by dharmendrasha** [comment]
If it helps please assign this issue to me i will create an PR

**Comment by micalevisk** [comment]
another approach we could follow is changing that `ConsoleLogger#printMessages` to allow any type of writable stream like `fs.createWriteStream('./output.txt')`. But I feel that 'console' implies in using either `process.stdout` or `process.stderr` :thinking: 

https://github.com/nestjs/nest/blob/721372f0c6b1e64a2c9a6a3dbc5ef5e90fa5bd40/packages/common/services/console-logger.service.ts#L180-L184

---

I recommend using [Pino](https://getpino.io/) instead of the default logger. There's a lib on that: https://github.com/iamolegga/nestjs-pino

**Comment by jmcdo29** [comment]
The logger is something that is left intentionally able to be swapped out with ease. You can either use another logger, like Pino as mical mentioned or [ogma](https://ogma.jaymcdoniel.dev) which I wrote with Nest in mind, or you could just pipe your output to a file using the `>` operator in your start command (e.g. `node dist/main > server.log` [note: you'll probably want to disable colors for that]). We'd rather not tie in production specific logic to the framework itself and leave that as an option for each dev and use case.
