### ISSUE TITLE
make it more friendly to the beginner

### ISSUE THREAD

**Issue by reply2future** [nestjs/nest#10084]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I run `npm test` after installing the packages, and I got the error message like that:
![image](https://user-images.githubusercontent.com/6359152/183596425-7c646e39-9b60-4fc2-b2ca-186aca5c5795.png)
The reason why would throw this error is that I didn't run `npm build`

### Describe the solution you'd like

add a command `"pretest": "npm run build"` to `package.json`, so it can build automatically when running `npm test`

### Teachability, documentation, adoption, migration strategy

no need

### What is the motivation / use case for changing the behavior?

It's more friendly when I want to contribute the project with there steps and no need to run `npm build`:
1. `npm install`
2. `npm test`
3. coding
4. `npm test`
5. ...

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
