### ISSUE TITLE
Any exception triggers KafkaJS retryable logic

### ISSUE THREAD

**Issue by fjodor-rybakov** [nestjs/nest#10091]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

https://github.com/nestjs/nest/pull/9293

### NestJS version

8.4.7 -> 9.0.7

### Describe the regression

Currently we have a situation when throwing any exception triggers KafkaJS retry logic. Previously all exceptions were swallowed by [this code](https://github.com/nestjs/nest/blob/2084157cf7f1d2a381cc32dfeba6b8387ab2370c/packages/microservices/server/server.ts#L117).

There is no difference to use KafkaRetryableExecption and any other type of exceptions in case when we need retryable logic.

We are using `@EventPattern` decorator. 

### Input code

```ts

```

### Expected behavior

Only KafkaRetryableException should trigger retryable logic

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by fjodor-rybakov** [comment]
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

https://github.com/fjodor-rybakov/kafka-retryable

**Comment by KiriLucas** [comment]
Same happening with me, but instead of any exception triggering retry, it enters an infinite loop and keeps retrying the same message over and over again.
