### ISSUE TITLE
publishing events to kafka via client.emit() fails because producer member variable is set to null in ClientKafka class

### ISSUE THREAD

**Issue by arcoslorn** [nestjs/nest#10095]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8.2.4 -> 9.0.8

### Describe the regression

The  ClientKafka is unable to emit events to Kafka, throwing an error instead -> the 'producer' member variable is set to null in ClientKafka.

### Minimum reproduction code

https://github.com/arcoslorn/kafka_nest_stats/tree/master

### Input code
The line that causes the error is below:
```ts
this.client.emit('stats.floorUpdate', {
          key: address,
          value: floorUpdate,
        }),
```

Kafka client is initialized here
```ts
    ClientsModule.registerAsync([
      {
        name: 'STATS_SERVICE',
        imports: [ConfigModule],
        inject: [ConfigService],
        useFactory: async (configService: ConfigService) => {
          const { brokers, ssl } = parseKafkaHost(
            configService.get('KAFKA_HOST'),
          );
          console.log(brokers, ssl);
          return {
            transport: Transport.KAFKA,
            options: {
              client: {
                clientId: 'stats',
                brokers,
                ...ssl,
              },
              consumer: {
                groupId: 'stats-service',
              },
            },
          };
        },
      },
    ]),
```

```ts
constructor(
    @Inject('STATS_SERVICE')
    private client: ClientKafka){}

        async emitEvent(address, floorUpdate){
this.client.emit('stats.floorUpdate', {
          key: address,
          value: floorUpdate,
        }),
}
```
This line of code now fails because at ClientKafka.dispatchEvent, this.producer.send is not available. 
`this.producer === null`
### Error Message
```
TypeError: Cannot read properties of null (reading 'send')
    at ClientKafka.dispatchEvent (/Users/Documents/projects/kafka_nest_stats/node_modules/@nestjs/microservices/client/client-kafka.js:132:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Nest] 17079  - 08/11/2022, 4:17:13 PM   ERROR [ServerKafka] ERROR [Runner] Error when calling eachMessage {"timestamp":"2022-08-11T23:17:13.967Z","logger":"kafkajs","topic":"orderbook.newFloor","partition":0,"offset":"0","error":{"status":"error","message":"Internal server error"}}
[Nest] 17079  - 08/11/2022, 4:17:14 PM   ERROR [RpcExceptionsHandler] Cannot read properties of null (reading 'send')
```
### Expected behavior

The message should emit to the indicated kafka topic.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by arcoslorn** [comment]
The minimum reproduction repository is here: https://github.com/arcoslorn/kafka_nest_stats/tree/master

It requires a local instance of kafka to run.

The KafkaClient does not connect before the first event is published, thus resulting in the error.

**Comment by arcoslorn** [comment]
further investigation shows that onModuleInit() is completing after kafka messages are being processed. -- this should be incorrect behavior, and was not the case in nest 8.0.*

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/184303792-c0fdde4f-dc31-4fdb-8dbd-f4eebf366cec.png)

Your setup seems to be very custom. 

This repository doesn't really reproduce the original issue you reported. Please, provide a minimum reproduction repository without any custom hacks that let us isolate & and reproduce your issue locally.

**Comment by Yansb** [comment]
@arcoslorn Try to perform a connect on module init 
```js
  onModuleInit() {
     this.client.connect()
  }
```
or in your constructor
```js
    constructor(
    @Inject('STATS_SERVICE')
    private client: ClientKafka
    ){
       this.client.connect()
    }
```

**Comment by YossiArye** [comment]
> @arcoslorn Try to perform a connect on module init
> 
> ```js
>   onModuleInit() {
>      this.client.connect()
>   }
> ```
> 
> or in your constructor
> 
> ```js
>     constructor(
>     @Inject('STATS_SERVICE')
>     private client: ClientKafka
>     ){
>        this.client.connect()
>     }
> ```

I attempted to include it within onModuleInit, but encountered the same error. Is there an updated version that addresses this issue?
