### ISSUE TITLE
Nest.js app with Prisma creates multiple connections on boot

### ISSUE THREAD

**Issue by sebpowell** [nestjs/nest#10092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We have a project that involves two Prisma instances. 

Directory structure looks like this:

```
/modules
   /moduleOne
   /moduleTwo
   /prisma
      prismaOne.service.ts
      prismaTwo.service.ts
```

Both of these are setup exactly like how the example in the docs are setup:

```TS
import { INestApplication, Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '../../../prisma/generated/prisma-one';

@Injectable()
export class PrismaOneService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect();
  }

  async enableShutdownHooks(app: INestApplication) {
    this.$on('beforeExit', async () => {
      await app.close();
    });
  }
}
```

These are then injected into other modules, in the following way:

```TS
import { Module } from '@nestjs/common';
import { PrismaOneService } from '../prisma/prisma-one.service.ts'
import { PrismaTwoService } from '../prisma/prisma-two.service.ts'

@Module({
  imports: [],
  controllers: [Controller],
  providers: [
    PrismaOneService,
    PrismaTwoService
  ],
  exports: [],
})
export class Module {}
```

The issue we're having is that it would *appear* that a new connection is created for every module we load that injects this service. So very quickly, we might end up with upwards of 20 connections when booting the app up locally. This eventually leads to a connection error:

```
 Error: Error in connector: Error querying the database: db error: FATAL: sorry, too many clients already
```

Commenting out some modules in our main app.ts file results in less connections being created.

Does anyone know what might be going wrong? Any help would be greatly appreciated!

P.S: the example repo I included will not boot as I haven't setup Prisma with a test DB – hopefully the structure will be enough to show what's going on, but if not, I can look at setting up a test DB to connect to.

### Minimum reproduction code

https://codesandbox.io/s/peaceful-raman-jrg513

### Expected behavior

I would expect only one connection to be initiated when the app boots up.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
 "dependencies": {
    "@nestjs/axios": "^0.0.7",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/jwt": "github:nestjs/jwt",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/terminus": "^8.0.6",
    "@ntegral/nestjs-sentry": "^3.0.7",
    "@prisma/client": "^4.1.1",
    "@sendgrid/mail": "^7.6.2",
    "@sentry/node": "^7.0.0",
    "@slack/types": "^2.5.0",
    "@slack/web-api": "^6.7.2",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "country-state-city": "^3.0.1",
    "date-fns": "^2.28.0",
    "dotenv": "^16.0.0",
    "express-jwt": "^7.6.2",
    "handlebars": "^4.7.7",
    "joi": "^17.6.0",
    "jwks-rsa": "^2.1.0",
    "lodash": "^4.17.21",
    "mjml": "^4.12.0",
    "nest-router": "^1.0.9",
    "passport": "^0.5.2",
    "passport-jwt": "^4.0.0",
    "postcode-validator": "^3.7.0",
    "pusher": "^5.1.0-beta",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "snakecase-keys": "^5.4.2",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@faker-js/faker": "^7.3.0",
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@types/validator": "^13.7.2",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "prisma": "^4.1.1",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5",
    "webpack": "^5.72.1"
  },
}

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Every time you add a provider to the `providers` array, a new instance of that provider gets created. If you are wanting to keep a single instance of that provider, the provider should live in its own module where it is in the `providers` and the `exports`, then in the modules that contain the service where you want to inject this now singleton shared provider you should import the module rather than re-declaring the provider. 

In other words, do this:
```ts
@Module({
  providers: [PrismaService],
  exports: [PrismaService],
})
export class PrismaModule {}

@Module({
  imports: [PrismaModule],
  providers: [SomeProviderUsingPrismaService],
})
export class SomeModule {}
```

Not this:
```ts
@Module({
  providers: [PrismaService, UsingPrismaService]
})
export class FooModule {}

@Module({
  providers: [PrismaService, BarService],
})
export class BarModule {}
```

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by sebpowell** [comment]
@jmcdo29 – amazing, thanks Jay! Seems obvious in retrospect 😅 I've updated our code, and that seems to have solved it. Thank you!
