### ISSUE TITLE
nestjs/schedule: fixedDelay timers

### ISSUE THREAD

**Issue by fauxbytes** [nestjs/nest#10100]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

`@Interval` allows installing a periodic task. This applies well to tasks that need to run at a fixed rate. Often though, the business logic of tasks require that only a single instance is running at any given time. For such use-cases, `@interval` doesn't quite fit, as it does not guarantee the former, and tasks can overrun the interval and so overlap.

### Describe the solution you'd like

Looking for a feature similar to [Spring's fixedDelay](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/annotation/Scheduled.html#fixedDelay--) mechanism. It differs from `@Interval` in that the specified period is measured from the time the last invocation terminated, rather than when it initiated. As a result, only one such task is active at any given time.

### Teachability, documentation, adoption, migration strategy

@FixedDelay(10000)
doFoo() {
  this.logger.debug('Called 10 seconds after the last invocation of foo terminated');
}

### What is the motivation / use case for changing the behavior?

See above

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
