### ISSUE TITLE
GRPC - RpcExceptions are returned as plain Error to client

### ISSUE THREAD

**Issue by gilre** [nestjs/nest#10101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When calling a GRPC server, 
exceptions are returned as plain Error objects instead of `RpcException`.

This makes it impossible to filter using `RpcExceptionFilter`.
As well as forcing every call to be wrapped in a try catch rather than relying on the filter.

I've been looking for a solution for weeks, tried Discord as well as StackOverflow,
there are multiple entries regarding this but no answers,
same for issues here, 
seems like [this](https://github.com/nestjs/nest/pull/5710) should solve similar cases but it's not relevant to grpc transports.

Please help

### Minimum reproduction code

https://github.com/gilre/nestjs-grpc-exception-reproduce

### Steps to reproduce

1. `npm ci`
2. `nest start`
4. `curl localhost:3001/hero/1`
5. see error printed out `Error: 5 NOT_FOUND: Hero not found`

### Expected behavior

I would expect the Grpc client to throw a typed error (RpcException) as was thrown by the called server
that way it will be possible to use `RpcExceptionFilter` to handle failures etc...

```
RpcException [Error]: Hero not found
    at . . .
  error: { code: 5, message: 'Hero not found' }
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

v16.15.0

### Packages versions

```json

{
 "dependencies": {
    "@grpc/grpc-js": "^1.6.9",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.0.8",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.5"
  },
"devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.4",
    "@types/node": "^18.0.3",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.5",
    "@typescript-eslint/parser": "^5.30.5",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^28.1.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.5",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.7.4"
  }
}
```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
