### ISSUE TITLE
ClientGrpcProxy - serializeError is not called before returning error

### ISSUE THREAD

**Issue by gilre** [nestjs/nest#10104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`serializeError` is not invoked before returning error from `ClientGrpcProxy`, [here](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-grpc.ts#L246)
even if the Grpc client was extended and `serializeError` overloaded

```
class ErrorHandlingProxy extends ClientGrpcProxy {
  serializeError(err) {
    return new RpcException(err);
  }
}

@Module({
  providers: [
    {
      provide: 'HERO_PACKAGE',
      useFactory() {
        return new ErrorHandlingProxy(grpcClientOptions.options);
      },
    },
  ],
  controllers: [HeroController],
})
export class HeroModule {}
```

### Minimum reproduction code

https://github.com/gilre/nestjs-grpc-exception-reproduce

### Steps to reproduce

1. npm ci
2. nest start
3. curl localhost:3001/hero/1
4. see error printed out Error: 5 NOT_FOUND: Hero not found

### Expected behavior

as the client proxy was created with an overloaded `serializeError`,
it's expected to be invoked before returning the error.

expected thrown error after `serializeError`:
```
RpcException [Error]: 5 NOT_FOUND: Hero not found
    at ErrorHandlingProxy.serializeError (nestjs-grpc-exception-reproduce/src/hero/hero.module.ts:8:12)
   .
   .
   {
      code: 5,
      details: 'Hero not found',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
 "dependencies": {
    "@grpc/grpc-js": "^1.6.9",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.0.8",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.5"
  },
"devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.4",
    "@types/node": "^18.0.3",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.5",
    "@typescript-eslint/parser": "^5.30.5",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^28.1.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.5",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.7.4"
  }
}
```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

this is based on [this reply](https://github.com/nestjs/nest/pull/5710#issuecomment-786882740)
and [this discord convo](https://discord.com/channels/520622812742811698/1007179618211606538)

**Comment by gilre** [comment]
I will gladly work on a pr for this if needed.

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome! 🙌

**Comment by gilre** [comment]
Great, 
i'll work on it over the weekend, will probably open a pr tomorrow evening.
