### ISSUE TITLE
Custom RPC exception when using Kafka based microservice is not returning error

### ISSUE THREAD

**Issue by RaiMX** [nestjs/nest#10113]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8.4.6 -> 9.0.9

### Describe the regression

Custom RPC exception when using Kafka based microservice is not returning error.
Error is displayed in console, but not getting to Kafka topic.
Before upgrading to v9 it was working fine.

### Input code

```ts
import { ArgumentsHost, Catch, HttpException, RpcExceptionFilter } from '@nestjs/common';
import { RpcException } from '@nestjs/microservices';
import { Observable, throwError } from 'rxjs';

@Catch()
export class CustomRpcExceptionFilter implements RpcExceptionFilter<RpcException> {
    
    catch(exception: RpcException | HttpException, host: ArgumentsHost): Observable<any> {
    ...
    return throwError(() => JSON.stringify(error)); // before migrating to v9 this line worked fine
    }
}
```

### Expected behavior

Custom RPC exception should return error

### Other

```json
"dependencies": {
        "@nestjs/common": "^9.0.9",
        "@nestjs/config": "^2.2.0",
        "@nestjs/core": "^9.0.9",
        "@nestjs/microservices": "^9.0.9",
        "@nestjs/platform-express": "^9.0.9",
        "@nestjs/swagger": "^6.0.5",
        "@nestjs/typeorm": "^9.0.1",
        "@nestjsx/crud": "^5.0.0-alpha.3",
        "@nestjsx/crud-typeorm": "^5.0.0-alpha.3",
        "bcrypt": "^5.0.1",
        "cache-manager": "^4.1.0",
        "cache-manager-redis-store": "^2.0.0",
        "class-transformer": "^0.5.1",
        "class-validator": "^0.13.2",
        "ioredis": "^5.2.0",
        "kafkajs": "^2.1.0",
        "kafkajs-snappy": "^1.1.0",
        "mongoose": "^6.4.4",
        "nest-winston": "^1.7.0",
        "pg": "^8.7.3",
        "redis": "^4.2.0",
        "reflect-metadata": "^0.1.13",
        "rimraf": "^3.0.2",
        "rxjs": "^7.5.6",
        "typeorm": "^0.3.7",
        "typeorm-naming-strategies": "^4.1.0",
        "winston": "^3.8.1",
        "winston-daily-rotate-file": "^4.7.1"
    },
    "devDependencies": {
        "@nestjs/cli": "^9.0.0",
        "@nestjs/schematics": "^9.0.1",
        "@nestjs/testing": "^9.0.9",
        "@types/cache-manager": "^4.0.1",
        "@types/cache-manager-redis-store": "^2.0.1",
        "@types/express": "^4.17.13",
        "@types/jest": "^28.1.5",
        "@types/node": "^18.0.3",
        "@types/supertest": "^2.0.12",
        "@typescript-eslint/eslint-plugin": "^5.30.6",
        "@typescript-eslint/parser": "^5.30.6",
        "eslint": "^8.19.0",
        "eslint-config-prettier": "^8.5.0",
        "eslint-plugin-prettier": "^4.2.1",
        "jest": "^28.1.2",
        "prettier": "^2.7.1",
        "source-map-support": "^0.5.21",
        "supertest": "^6.2.4",
        "ts-jest": "^28.0.5",
        "ts-loader": "^9.3.1",
        "ts-node": "^10.8.2",
        "tsconfig-paths": "^4.0.0",
        "typescript": "^4.7.4"
    }
```

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by RaiMX** [comment]
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

Here is the repo
https://github.com/RaiMX/nestjs-kafka-exceptions

**Comment by RaiMX** [comment]
any updates?

**Comment by peshkov3** [comment]
any updates?

**Comment by RaiMX** [comment]
Please anybody?

**Comment by RaiMX** [comment]
forcing me to downgrade to version 8...

**Comment by kimvladis** [comment]
Faced same problem week ago, there are bug in ServerKafka. Extend ServerKafka and override method `combineStreamsAndThrowIfRetriable` with:
```
private combineStreamsAndThrowIfRetryable(response$: Observable<any>, replayStream$: ReplaySubject<unknown>) {
    return new Promise<void>((resolve, reject) => {
      let isPromiseResolved = false;
      response$.subscribe({
        next: (val) => {
          replayStream$.next(val);
          if (!isPromiseResolved) {
            isPromiseResolved = true;
            resolve();
          }
        },
        error: (err) => {
          if (err instanceof KafkaRetriableException && !isPromiseResolved) {
            isPromiseResolved = true;
            reject(err);
          }
          replayStream$.error(err);
          if (!isPromiseResolved) {
            isPromiseResolved = true;
            resolve();
          }
        },
        complete: () => replayStream$.complete(),
      });
    });
  }
  ```
  
  Also in new version you need to provide Exception instance instead of message of exception in RpcExceptionFilter:
  ```
  catch(exception: RpcException | HttpException, host: ArgumentsHost): Observable<any> {
    ...
    return throwError(() => exception);
  }
  ```

**Comment by RaiMX** [comment]
> Faced same problem week ago, there are bug in ServerKafka. Extend ServerKafka and override method

Thank you!
I confirm that this solution works!

**Comment by RaiMX** [comment]
> I confirm that this solution works!

@kimvladis Could you submit a pull request?

**Comment by RaiMX** [comment]
> Faced same problem week ago, there are bug in ServerKafka. Extend ServerKafka and override method `combineStreamsAndThrowIfRetriable` with:
> 
> ```
> private combineStreamsAndThrowIfRetriable(response$: Observable<any>, replayStream$: ReplaySubject<unknown>) {
>   return new Promise<void>((resolve, reject) => {
>     response$.subscribe({
>       next: (val) => {
>         replayStream$.next(val);
>         resolve();
>       },
>       error: (err) => {
>         if (err instanceof KafkaRetriableException) {
>           reject(err);
>         }
>         replayStream$.error(err);
>         resolve();
>       },
>       complete: () => replayStream$.complete(),
>     });
>   });
> }
> ```
> 
> Also in new version you need to provide Exception instance instead of message of exception in RpcExceptionFilter:
> 
> ```
> catch(exception: RpcException | HttpException, host: ArgumentsHost): Observable<any> {
>   ...
>   return throwError(() => exception);
> }
> ```

How would you extend ServerKafka? I mean extend whole chain of classes?
