### ISSUE TITLE
Closing Redis Microservice Server Causes Uncaught Error

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#10120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When calling `app.close()` on a redis microservice server, an uncaught error will be thrown.

```
~/node_modules/.pnpm/ioredis@5.2.2/node_modules/ioredis/built/redis/event_handler.js:182
        self.flushQueue(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
                        ^
Error: Connection is closed.
    at close (~/node_modules/.pnpm/ioredis@5.2.2/node_modules/ioredis/built/redis/event_handler.js:182:25)
    at Socket.<anonymous> (~/node_modules/.pnpm/ioredis@5.2.2/node_modules/ioredis/built/redis/event_handler.js:149:20)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:757:14)
```

### Minimum reproduction code

https://github.com/jmcdo29/nestjs-redis-microservices-close-failure

### Steps to reproduce

1) clone this repo
2) `npm i`/`yarn`/`pnpm i`
3) `docker compsoe up -d`
4) `npm run start:dev`/`yarn start:dev`/`pnpm start:dev`
5) observe the error

### Expected behavior

The server closes without any kind of errors on SIGINT or `app.close()`. I found this during integration testing of my ogma library where I programatically open and close servers to verify an interceptor works as expected.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.9

### Packages versions

```
[System Information]
OS Version     : Linux 5.18
NodeJS Version : v18.6.0
PNPM Version    : 7.8.0

[Nest CLI]
Nest CLI Version : 9.0.0

[Nest Platform Information]
platform-express version : 9.0.9
microservices version    : 9.0.9
schematics version       : 9.0.1
testing version          : 9.0.9
common version           : 9.0.9
core version             : 9.0.9
cli version              : 9.0.0
```

### Node.js version

18.7.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I'm happy to work on this as I already have a fix in mind and can have the patch up relatively quickly

**Comment by kamilmysliwiec** [comment]
Great investigation @jmcdo29! I just created a PR that addresses this issue https://github.com/nestjs/nest/pull/10122
