### ISSUE TITLE
Cookie in middleware not working only using fastify.

### ISSUE THREAD

**Issue by armada45-pixel** [nestjs/nest#10121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If using express cookie in middleware can working normal.
But If using fastify all about cookie will undefined.

### Minimum reproduction code

https://github.com/armada45-pixel/nestjs-cookie-middleware-fastify.git

### Using npm

```bash
npm i
npm run start:dev
```

### Using yarn

```bash
yarn install
yarn start:dev
```

### Using pnpm

```bash
pnpm i
pnpm start:dev
```

## You can use VS Code Debugger

> install package using package manager like npm, yarn, pnpm, bun
>
> Go to Run and Debug Page
>
> Run Debugger Profile name " DS "

### Expected behavior

Can use all about cookie in middleware using fastify.
Request.cookies['key']
Response.setCookie('key', 'value')
Response.cookie('key', 'value')

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

fastify-cookie

### NestJS version

9.0.9

### Packages versions

```json
{
  "name": "nestjs-cookie-middleware-fastify",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "update": "yarn-upgrade-all"
  },
  "dependencies": {
    "@fastify/cookie": "^7.4.0",
    "@nestjs/common": "^9.0.9",
    "@nestjs/core": "^9.0.9",
    "@nestjs/platform-express": "^9.0.9",
    "@nestjs/platform-fastify": "^9.0.9",
    "cookie-parser": "^1.4.6",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.6"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.1",
    "@nestjs/testing": "^9.0.9",
    "@types/cookie-parser": "^1.4.3",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.7",
    "@types/node": "^18.7.5",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.33.1",
    "@typescript-eslint/parser": "^5.33.1",
    "eslint": "^8.22.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "fastify": "^4.4.0",
    "jest": "^28.1.3",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.8",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.1.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

18.7.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
