### ISSUE TITLE
No documentation on how to use GqlThrottlerGuard with Subscription

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [nestjs/nest#10130]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am using global throttler guard for my graphql api. But I get an error when I am adding subscriptions
```"Cannot read properties of undefined (reading 'ip')",```
It is thrown bu ```GqlThrottlerGuard```

It would be great to have section in documentation here: https://docs.nestjs.com/security/rate-limiting#graphql how to handle it 

### Describe the solution you'd like

It would be great to have section in documentation here: https://docs.nestjs.com/security/rate-limiting#graphql how to handle it 

### Teachability, documentation, adoption, migration strategy

--

### What is the motivation / use case for changing the behavior?

--

**Comment by kamilmysliwiec** [comment]
Please report this issue here https://github.com/nestjs/throttler
