### ISSUE TITLE
Nest controller is using standard method when using @Res() with fastify

### ISSUE THREAD

**Issue by Aightt44340** [nestjs/nest#10148]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8 -> 9

### Describe the regression

When I add the @Res() decorator to my route, the controller should not automatically send the response and should wait for me to manually send the data with the response object. This works fine with express but not with fastify.

### Input code

main.ts
```ts

import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
  await app.listen(3000);
}
bootstrap();

```

app.controller.ts
```ts

import { Controller, Get, Res } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(@Res() response): string {
    return this.appService.getHello();
  }
}

```

### Expected behavior

With this code, when I call this route, it should loop forever because I am not sending data with the response object.

**Comment by micalevisk** [comment]
use `@Res({ passthrough: true })`

https://docs.nestjs.com/controllers#library-specific-approach

**Comment by micalevisk** [comment]
actually, I guess I missed your point. I'll reopen this if you provide a minimum repository that reproduces your issue.

# [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
