### ISSUE TITLE
Support for custom prisma locations

### ISSUE THREAD

**Issue by kokokenada** [nestjs/nest#10150]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have an issue with monorepo using npm workspaces and prisma. The set up is there are two microservices that both use prisma (say packages/api1, packages/api2). If the same version of prisma is used in each, npm will create https://github.com/prisma in the root node_modules. The generated .prisma files are installed as a sibling to https://github.com/prisma, so api1 and api2 can clobber each other. One can specify where to generate the files (https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#using-a-custom-output-path), however,  nestjs uses @prisma/client to import, so the new location is ignored.

### Describe the solution you'd like

A way to specify where to pick up prisma from .

### Teachability, documentation, adoption, migration strategy

Maybe a nest-cli.json option??

### What is the motivation / use case for changing the behavior?

I want to use workspace features to speed up dependency installation and provide easy ways to share code across packages. This was is a problem encountered along the way.  One workaround is to simply use slightly different versions of prisma (to force local install).  If npm workspaces had a no hoist option (https://github.com/npm/rfcs/issues/287) this would also be a way to solve the problem.

**Comment by jmcdo29** [comment]
> however, nestjs uses @prisma/client to import,

There's nothing that limits you to using just `@prisma/client`, that's just how the simple case works. If you need to follow prisma's docs for multiple import and output locations, there should be nothing stopping you from doing so.

**Comment by kokokenada** [comment]
Thanks for the reply @jmcdo29 .  The issue is that the prisma/nestjs tool uses @prisma/client and provides no way of configuring it: https://github.com/notiz-dev/nestjs-prisma/blob/main/lib/prisma.service.ts

**Comment by jmcdo29** [comment]
`nestjs-prisma` is not maintained by us. Please report this issue to [their repo](https://github.com/notiz-dev/nestjs-prisma).
