### ISSUE TITLE
Transient scoped providers not resolving dependencies when `@Inject(INQUIRER)` is present on constructor (UnitTest)

### ISSUE THREAD

**Issue by TheVoid-0** [nestjs/nest#10159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to mock the transient provider dependencies, the inquirer cannot be resolved, thus resulting (for some reason) on a service with undefined dependencies. Note that this only happens if `@Inject(INQUIRER)` is present on the constructor. So far I have not encountered problems in the actual application, I could only reproduce this behavior using the TestingModule

### Minimum reproduction code

https://github.com/TheVoid-0/transient-provider-undefined-dependencies

### Steps to reproduce

npm run test

### Expected behavior

It would be expected that services with unresolved dependencies (that are not optional) to throw an error instead of being resolved with undefined dependencies. Also It's necessary to have a way to mock the inquirer injection to be able to test transient scoped providers

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

While using the TestBuilder `useMocker()` and logging every token that the function was called, I've noticed that the INQUIRER token was never logged, every dependency from the Service goes through the `useMocker` except for the INQUIRER token, I do not know if this is intentional or not

**Comment by jmcdo29** [comment]
Looks like this is specifically an issue with the `useMocker` functionality. Using this as the test
```ts
describe('TransientService', () => {
  let transientService: TransientService;

  beforeEach(async () => {
    const app: TestingModule = await Test.createTestingModule({
      providers: [
        TransientService,
        {
          provide: SingletonService,
          useValue: {},
        },
        {
          provide: INQUIRER,
          useValue: 'TestingModule',
        },
      ],
    })
      /*.useMocker((token) => {
        console.log('INJECTING', token);
        if (token === SingletonService) {
          return {};
        }
        if (token === INQUIRER) {
          return 'TestingModule';
        }
      }) */
      .compile();

    transientService = await app.resolve(TransientService);
  });

  it('should have dependencies injected', () => {
    expect(transientService['singletonService']).toBeDefined();
  });
});
```
everything works as expected. I'll try to take a look into this soon. Probably something about how TRANSIENT and REQUEST scoped providers are provided in the `TestingModule`

**Comment by TheVoid-0** [comment]
@jmcdo29 Thanks for answering as always. I've could saved a lot of time if I had tested that sooner 😅.  But now I can proceed the work with that aproach.

**Comment by kamilmysliwiec** [comment]
@jmcdo29 A little tip that may be helpful - both REQUEST and INQUIRER providers are pre-defined (they're always pre-defined in the container, no matter if they're being used)

**Comment by kamilmysliwiec** [comment]
Did you have a chance to investigate this issue @jmcdo29? 🙌

**Comment by jmcdo29** [comment]
> Did you have a chance to investigate this issue @jmcdo29? 🙌 

I'll take a look back into it in the morning.. Thanks for bringing it back up :+1:

**Comment by jmcdo29** [comment]
I believe the original error has to do with trying to auto-mock `INQUIRER` or `REQUEST`, due to what Kamil said about them always being defined. I took our current `integration/auto-mock` test and made copies for `FooService` being both `TRANSIENT` and`REQUEST` scoped and they worked exactly as expected with no changes necessary.

If that's the case we should probably make a mention in the docs that `REQUEST` and `TRANSIENT` cannot be auto-mocked _because_ they're already defined in the context, but they can be overwritten with a custom provider or a `overrideProvider`
