### ISSUE TITLE
Nest can't resolve dependencies of the GraphQLModule

### ISSUE THREAD

**Issue by AndriiKifiak** [nestjs/nest#10158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello guys, I have a weird issue, my case is a bit complicated, I have federated graph monorepo(apollo, express), the idea is to launch each subgraph in separate worker thread, during launching gateway:
```typescript
/// main.ts
  await Promise.all([
    {
      path: '../users-application/dist/app.module.js',  
      name: 'users-application'
    },
    {
      path: '../posts-application/dist/app.module.js',
      name: 'posts-application'
    }
  ].map(async (item) => {
    await new Worker("./generatorWorker", { 
      workerData: { path: item.path },
    });
  }))
```
```typescript
/// generatorWorker
const generate = async (pathe: string) => {
  const module = await import(resolve(process.cwd(), pathe));    
      
  try {
      await NestFactory.create(module.AppModule)
      console.log('CREATED');
  } catch (error) {
    console.log(error);
  }
}

generate(workerData.path);
```
The example above has a static array of subgraphs but it may differ depends on runtime.
The problem  appears after I have updated version of `nest/core` and `nest/common` to version ^8 I am receiving dependency error from `NestFactory.create`:
```
Nest can't resolve dependencies of the GraphQLModule (?, GqlModuleOptions, AbstractGraphQLDriver, GraphQLTypesLoader). Please make sure that the argument HttpAdapterHost at index [0] is available in the GraphQLModule context.

Potential solutions:
- If HttpAdapterHost is a provider, is it part of the current GraphQLModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })
```
`HttpAdapterHost` is something which should be injected by default inside of the `GraphQlModule` from `@nest/graphql`
With version `nest/core` lower that 8 it works fine.
I could debug it till the point of [scanner file](https://github.com/nestjs/nest/blob/master/packages/core/injector/injector.ts#L523) 
See the minimum example repo: it is slightly changed from `samples` folder to reproduce my issue.

### Minimum reproduction code

https://github.com/AndriiKifiak/federation-graph-nestjs-problem/tree/version_8

### Steps to reproduce

1. run `npm i` for each folder: `gateway`, `posts-application` and `users-application`
2. run `npm run start` at `./gateway` folder

### Expected behavior

It should just resolve all deps properly.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nest/graphql

### NestJS version

8.2.3

### Packages versions

```json
  "dependencies": {
    "@apollo/gateway": "0.46.0",
    "@nestjs/apollo": "9.2.4",
    "@nestjs/common": "8.2.3",
    "@nestjs/core": "8.2.3",
    "@nestjs/graphql": "10.0.0",
    "@nestjs/platform-express": "8.2.3",
    "apollo-server-express": "3.6.2",
    "graphql": "15.7.2",
    "graphql-tools": "8.0.0",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.4.0",
    "threads": "^1.7.0",
    "ts-morph": "12.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "8.1.5",
    "@nestjs/schematics": "8.0.8",
    "@nestjs/testing": "8.2.3",
    "@types/express": "4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.26",
    "@types/supertest": "2.0.11",
    "@typescript-eslint/eslint-plugin": "4.33.0",
    "@typescript-eslint/parser": "4.33.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-prettier": "4.0.0",
    "jest": "27.5.1",
    "prettier": "2.5.1",
    "supertest": "6.1.6",
    "ts-jest": "27.0.7",
    "ts-loader": "9.2.8",
    "ts-node": "10.4.0",
    "tsconfig-paths": "3.11.0",
    "typescript": "4.3.5"
  },
```

### Node.js version

16.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Most likely this is going to be an issue with multiple `node_modules` locations and each having their own `@nestjs/common` and `@nestjs/core`. If you end up importing across those directory boundaries, some of the internal `instanceof` checks end up failing due to JavaScript's object equality. If possible, I would suggest using a tool like `nx` to create the workspace with a single root `node_modules` directory so that this no longer becomes an issue.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
