### ISSUE TITLE
Sequelize ORM generates multiple unique constraints for the same column 

### ISSUE THREAD

**Issue by chandrashekhar07** [nestjs/nest#10152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- In sequelize orm, with configuration `alter:true` , when server restarts, a new unique constraint is generated for the same column. And older constraints/keys are still valid for the given column.

- screenshot from pgadmin:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/35414590/185788247-bdfb34b7-e772-4610-8360-1d687699310c.png">

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/07-sequelize

### Steps to reproduce

- Provide the database configuration  SequelizeModule.forRoot()
In addition, set ` sync: {  alter: true, }`

- for example:
`  SequelizeModule.forRoot({
      dialect: 'postgres',
      host: 'winhost',
      port: 5432,
      username: 'postgres',
      password: '',
      database: 'dev-db',
      autoLoadModels: true,
      synchronize: true,
      sync: {
        alter: true,
      },
    })
`
    
    
-  Go to user.model.ts, and make one of the columns unique, for that you can use @Unique decorator from "sequelize-typescript"
- Restart the server,  On each restart, a new unique constraint is generated
    
 - Screenshot from pgadmin
    
<img width="357" alt="image" src="https://user-images.githubusercontent.com/35414590/185787724-d1c57010-363e-41d2-bdfe-13ef3f293549.png">

    

### Expected behavior

- There should be only one unique constraints/key for a column

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/sequelize, sequelize-typescript, pg, sequelize

### NestJS version

9.0.1

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "9.0.1",
    "@nestjs/core": "9.0.1",
    "@nestjs/platform-express": "9.0.1",
    "@nestjs/sequelize": "9.0.0",
    "mysql2": "2.3.3",
    "pg": "^8.7.3",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.5.5",
    "sequelize": "6.21.2",
    "sequelize-typescript": "2.1.3",
    "typescript": "4.7.4"
  },
```

### Node.js version

14.19.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

ubuntu in WSL

**Comment by micalevisk** [comment]
Report on Sequelize repo instead: https://github.com/sequelize/sequelize
