### ISSUE TITLE
Export loadPackage util

### ISSUE THREAD

**Issue by sszczep** [nestjs/nest#10163]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As of now, we cannot import `loadPackage` util directly from `@nestjs/common` package.  We need to stick with absolute path (`common/utils/load-package.util.ts`).

### Describe the solution you'd like

`loadPackage` should be exported in barrel-export in `common/utils/index.ts` file.

### Teachability, documentation, adoption, migration strategy

```ts
import { loadPackage } from '@nestjs/common';
loadPackage(packageName, context, loaderFn);
```

### What is the motivation / use case for changing the behavior?

`loadPackage` seems to be a util which could be reused in our custom components. It would be especially useful when creating custom validation pipes with `transformerPackage` and `validatorPackage` options to keep consistency with built-in pipes.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
