### ISSUE TITLE
onModuleInit order with import dependencies

### ISSUE THREAD

**Issue by SpekalsG3-SS** [nestjs/nest#10174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [NestFactory] Starting Nest application...
[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [InstanceLoader] ApplicationModule dependencies initialized +28ms
[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [InstanceLoader] OneModule dependencies initialized +0ms
[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [InstanceLoader] TwoModule dependencies initialized +0ms
third service module init
first service module init
second service module init
[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [NestApplication] Nest application successfully started +7ms

### Minimum reproduction code

https://github.com/jeiea/nest_report

### Steps to reproduce

git clone https://github.com/jeiea/nest_report.git
cd nest_report
pnpm install
pnpm run start

### Expected behavior

[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [NestFactory] Starting Nest application...
[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [InstanceLoader] ApplicationModule dependencies initialized +28ms
[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [InstanceLoader] OneModule dependencies initialized +0ms
[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [InstanceLoader] TwoModule dependencies initialized +0ms
first service module init
second service module init
third service module init
[Nest] 56283  - 10/22/2021, 5:18:38 PM     LOG [NestApplication] Nest application successfully started +7ms

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.7

### Packages versions

```json
    "@nestjs/core": "^8.4.7",
    "@nestjs/common": "^8.4.7",
```

### Node.js version

v16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I'm coping [another issue on this topic](https://github.com/nestjs/nest/issues/8412). I know this is an expected behaviour but what if I want to change it? I want to ensure that all module dependencies' OnModuleInit called before calling parent's OnModuleInit.

**Comment by micalevisk** [comment]
We can discuss this on our [Discord](https://discord.gg/nestjs), as this is not a feature request nor a bug report.
