### ISSUE TITLE
Dynamic data route does not work well

### ISSUE THREAD

**Issue by zomixi** [nestjs/nest#10173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```ts
import { Controller, Get, Param } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  // @Get('/hello/cats/1') i just want path
  @Get('/hello/:path(.+)')
  getHello(@Param('path') path: string): string {
    console.log(path);

    return this.appService.getHello();
  }
}
```
When i fetch `/hello/cats/1`, i get:
```json
{
    "statusCode": 404,
    "message": "Cannot GET /hello/cats/1",
    "error": "Not Found"
}
```

### Minimum reproduction code

https://codesandbox.io/s/determined-haslett-obxl55?file=/src/app.controller.ts

### Expected behavior

```ts
import { Controller, Get, Param } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  // @Get('/hello/cats/1') i just want path
  @Get('/hello/:path(.+)')
  getHello(@Param('path') path: string): string {
    console.log(path);

    return this.appService.getHello();
  }
}
```
When i fetch `/hello/cats/1`, i cat get path is `cats/1`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.11

### Packages versions

```json
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
that doesn't work in plain Express neither.

```ts
const express = require('express') // v4.8.1
const app = express()

app.get('/hello/:path(.+)', (req, res) => res.end('ok'))

app.listen(3000)
```

```bash
curl "localhost:3000/hello/cats/1"
```

**Comment by jmcdo29** [comment]
From express's docs:

> Since the hyphen (-) and the dot (.) are interpreted literally, they can be used along with route parameters for useful purposes.

You probably need a more useful regex like `:path([\\w\d\\/]+)`
