### ISSUE TITLE
multiple handlers @EventPattern() for the same event, with an interceptor and request scoped controller

### ISSUE THREAD

**Issue by yuvall-cyera** [nestjs/nest#10184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When there are multiple handlers, listening to the same event (tested with Kafka), the expected behavior is that both handlers will be called (https://github.com/nestjs/nest/pull/6334).
But when an interceptor is also involved, and the controller is request scoped only one handler is being called.
The second one isn't being called - only its interceptor is being called

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-8vgdfu?file=src%2Fapp.controller.ts,src%2Fmain.ts

### Steps to reproduce

1. npm start
2. send a Kafka message with topic named `topic`

### Expected behavior

Expect that both of the handlers will be called

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.7

### Packages versions

```json

```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10209
