### ISSUE TITLE
DI error getting while using useMocker in testing

### ISSUE THREAD

**Issue by TahaDgn** [nestjs/nest#10191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There are a lot of dependencies injected into my service where I'm trying to improve unit testing. I decided to use `moduleRef.useMocker((token) => { })` to reduce the time consuming with DIs. I supposed that I would only inject the service on testing as a provider or controller while creating the testing module according to the doc. However, when I run the tests, getting DI resolution error. 

There is the code below

```ts
describe('DocumentsService', () => {
  let serviceOnTesting: ServiceOnTesting;

  beforeEach(async () => {

    const moduleRef = await Test.createTestingModule({
      providers: [
        ServiceOnTesting,
      ],
    })
      .useMocker((token) => {
        if (token === InjectedService) {
          return {
            someMockedFunction: jest.fn().mockResolvedValue({ value: 'value' }),
          }
        }
      })
      .compile();

    serviceOnTesting = moduleRef.get(ServiceOnTesting);
  });

  describe('Test suite', () => {
    it('Should work', async () => {

                          // This one just returns the value of mocked function 
      const value = await serviceOnTesting.serviceFunction();

      expect(value).toMatchObject({ value: 'value' });
    });
  });
});
```

Then it does throw

```shell
Nest cant resolve dependencies of the ServiceOnTesting(?)
```

### Minimum reproduction code

https:/github.com

### Expected behavior

It should execute the mocked function without struggle in dependencies.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

jest-mock

### NestJS version

9.0.11

### Packages versions

```json
{
  "scripts": {
    "prebuild": "rimraf dist",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "build": "nest build",
    "start": "ts-node -r tsconfig-paths/register src/start.ts",
    "preinstall": "npx npm-force-resolutions",
    "start:dev": "nodemon -L",
    "start:prod": "node dist/start.js",
  },
  "dependencies": {
    "@apollo/gateway": "0.28.1",
    "@golevelup/ts-jest": "^0.3.3",
    "@nestjs/common": "9.0.11",
    "@nestjs/config": "2.1.0",
    "@nestjs/core": "9.0.11",
    "@nestjs/graphql": "7.10.6",
    "@nestjs/microservices": "7.6.18",
    "@nestjs/passport": "7.1.5",
    "@nestjs/platform-express": "7.5.5",
    "@nestjs/typeorm": "7.1.5",
    "@types/express": "4.16.1",
    "@types/node": "15.0.1",
    "apollo-server-express": "2.19.2",
    "aws-sdk": "^2.1167.0",
    "axios": "^0.27.2",
    "body-parser-graphql": "1.1.0",
    "cache-manager": "3.4.0",
    "class-transformer": "0.4.0",
    "class-validator": "0.13.1",
    "cls-hooked": "^4.2.2",
    "dotenv": "8.2.0",
    "express-basic-auth": "^1.2.0",
    "firebase-admin": "8.12.1",
    "fs": "0.0.1-security",
    "graphql": "14.6.0",
    "graphql-rate-limit": "2.0.1",
    "graphql-tag": "2.10.1",
    "graphql-tools": "7.0.5",
    "graphql-type-json": "0.3.2",
    "graphql-upload": "11.0.0",
    "handlebars": "4.7.7",
    "ipware": "2.0.0",
    "jest-mock": "^29.0.1",
    "jwt-decode": "3.1.2",
    "kafkajs": "1.15.0",
    "moment": "2.29.4",
    "nestjs-typeorm-paginate": "^2.6.2",
    "node-cache": "5.1.0",
    "nodemon": "1.19.0",
    "nonblocking": "1.0.3",
    "passport": "0.6.0",
    "pg": "8.5.1",
    "qs": "6.9.4",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.0",
    "rxjs": "6.5.3",
    "safe-compare": "^1.1.4",
    "sheetjs-style": "0.15.6",
    "ts-node": "8.4.1",
    "tsconfig-paths": "3.9.0",
    "tslib": "1.11.2",
    "type-graphql": "1.1.1",
    "typeorm": "0.2.41",
    "typescript": "4.1.3",
    "winston": "^3.8.1",
    "winston-aws-cloudwatch": "3.0.0"
  },
  "devDependencies": {
    "@commitlint/cli": "12.1.4",
    "@commitlint/config-conventional": "12.1.4",
    "@nestjs/cli": "7.5.4",
    "@nestjs/testing": "9.0.11",
    "@types/bcrypt": "1.0.0",
    "@types/bunyan": "1.8.6",
    "@types/jest": "^27.4.1",
    "@types/jsonwebtoken": "7.2.5",
    "@types/lodash": "4.14.125",
    "@types/node": "15.0.1",
    "@typescript-eslint/eslint-plugin": "^4.27.0",
    "@typescript-eslint/parser": "^4.27.0",
    "dtslint": "0.5.9",
    "eslint": "^7.28.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "husky": "7.0.1",
    "jest": "^27.5.1",
    "mime-types": "2.1.35",
    "node-notifier": "5.4.0",
    "nodemon": "1.19.0",
    "prettier": "^2.3.1",
    "pretty-quick": "^3.1.3",
    "ts-jest": "^27.1.3",
    "ts-loader": "7.0.1",
    "tsconfig-paths": "3.9.0",
    "typescript": "4.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

14:latest

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Maligosus** [comment]
Can you show ServiceOnTesging class ?

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by TahaDgn** [comment]
Well, seems like I misunderstood the purpose of use Mockery. I need to implement all of the providers to produce mockers. It does not make sense to use this besides the old approach(creating testing modules by passing the custom providers with mock values). I expected that if a provider did not implement it into the use Mocker, it would be implemented with a default empty mock/object. Then It would be meant something for the codebase readability and made implementation easier by passing unnecessary implementations.

**Comment by jmcdo29** [comment]
You could pass back a default value of the token isn't a match to any in the factory. The factory is really there for if you want a specific implementation for your services, or a specific mocker
