### ISSUE TITLE
Class 'HttpException' incorrectly extends base class 'Error'

### ISSUE THREAD

**Issue by iuliust** [nestjs/nest#10202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After I've upgraded to nestjs 9, I get the following error when compiling:

![image](https://user-images.githubusercontent.com/5154932/187463394-3b4248e9-bcee-4ada-b730-9210c1355439.png)

The error goes away if I set exactOptionalPropertyTypes to false, in `tsconfig.json`.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-tyjh1w?file=tsconfig.json,src%2Fapp.controller.ts,tsconfig.build.json

### Steps to reproduce

set the following properties in tsconfig.json:

```json
{
  "lib": ["ES2022"],
  "strictNullChecks": true,
  "exactOptionalPropertyTypes": true,
  "skipLibCheck": false
}
```

### Expected behavior

The HttpException class should not collide with ES2022's cause property on Error's prototype.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.11

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^9.0.11",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.11",
    "@nestjs/platform-express": "^9.0.11",
    "@nestjs/platform-socket.io": "^9.0.11",
    "@nestjs/platform-ws": "^9.0.11",
    "@nestjs/swagger": "^6.1.0",
    "@nestjs/websockets": "^9.0.11",
    "axios": "^0.27.2",
    "dotenv": "^16.0.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "~7.5.5",
    "swagger-ui-express": "^4.4.0",
    "tsconfig-paths": "^3.14.1",
    "tslib": "~2.3.1",
    "uuid": "^8.3.2",
    "ws": "~8.2.3"
  },
  "devDependencies": {
    "@microsoft/api-extractor": "^7.25.0",
    "@nestjs/cli": "^9.1.1",
    "@nestjs/schematics": "^9.0.1",
    "@nestjs/testing": "^9.0.11",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.1",
    "@types/lodash": "^4.14.182",
    "@types/node": "^16.11.39",
    "@types/socket.io": "^3.0.2",
    "@types/supertest": "^2.0.12",
    "@types/uuid": "^8.3.4",
    "@types/ws": "~8.2.3",
    "@xmldom/xmldom": "^0.8.2",
    "jest": "^28.1.1",
    "supertest": "^6.2.3",
    "ts-jest": "^28.0.4",
    "ts-loader": "^8.4.0",
    "ts-node": "^10.8.1",
    "typescript": "^4.7.4"
  }
```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

![image](https://user-images.githubusercontent.com/5154932/187463088-c8212a62-348e-4841-aee6-8c7dfbdc5c30.png)

**Comment by micalevisk** [comment]
use `skipLibCheck: true`
