### ISSUE TITLE
Cannot overwrite provider outside of defining module

### ISSUE THREAD

**Issue by florian-besser** [nestjs/nest#10208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We define a module like so:
```
export const ROLES = 'ROLES';
@Module({
  providers: [
    SomeService,
    {
      // Will be overwritten later!
      provide: ROLES,
      useValue: []
    },
  ],
  exports: [ROLES],
})
export class A {}
```

The `SomeService` does inject `ROLES` and always receives `[]`, even if `ROLES` is overwritten later on:
```
const module: TestingModule = await Test.createTestingModule({
        imports: [A],
        providers: [
          {
            provide: ROLES,
            useValue: ['some value...'],
          },
        ],
      })
```

### Minimum reproduction code

https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master

### Steps to reproduce

Create modules like above. Apologies for not providing a URL but I cannot share the codebase I'm working on.

Checking https://docs.nestjs.com/fundamentals/custom-providers does seem to imply that you can overwrite providers, specifically the code:
```
@Module({
  imports: [CatsModule],
  providers: [
    {
      provide: CatsService,
      useValue: mockCatsService,
    },
  ],
})
export class AppModule {}
```

### Expected behavior

The `SomeService` should be injected `ROLES` as overwritten by the `TestingModule`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.8

### Packages versions

```json

```
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.16.0
NPM Version    : 8.11.0 

[Nest CLI]
Nest CLI Version : 9.0.0 

[Nest Platform Information]
platform-express version : 9.0.8
microservices version    : 9.0.8
mapped-types version     : 1.1.0
platform-ws version      : 9.0.9
websockets version       : 9.0.9
schedule version         : 2.1.0
terminus version         : 9.1.0
swagger version          : 6.0.5
testing version          : 9.0.8
common version           : 9.0.8
config version           : 2.2.0
axios version            : 0.1.0
core version             : 9.0.8
jwt version              : 9.0.0
cli version              : 9.0.0

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
