### ISSUE TITLE
@Body + ValidationPipe (transform: true) doesn't respect the dto class

### ISSUE THREAD

**Issue by JamieYnonan** [nestjs/nest#10207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When sending a request, an instance of the DTO class is generated with all the parameters sent in the body.

### Minimum reproduction code

https://codesandbox.io/p/github/JamieYnonan/nestjs/csb-pkiwlt/draft/dreamy-ardinghelli

### Steps to reproduce

**nest new project-name**
Which package manager would you ❤️  to use?
**npm**
move to project
**cd project-name**
Generate new resource (https://docs.nestjs.com/recipes/crud-generator#generating-a-new-resource)
**nest g resource**
? What name would you like to use for this resource (plural, e.g., "users")?
**users**
 What transport layer do you use?
**REST API**
Would you like to generate CRUD entry points? 
**Y**
install
**npm i --save class-validator class-transformer**

POST (creates the object with all the parameters of the body.)
**curl -d '{"id": "uuid", "name": "name value", "total": 10, "other": "other value"}' -H "Content-Type: application/json"** http://localhost:3000/users
**console**: true
**response**: {"id":"uuid","name":"name value","total":10,"other":"other value"}

PATCH (creates the object with all the parameters of the body. OmitType doesn't work)
**curl --request PATCH -d '{"id": "uuid", "name": "name value", "total": 10, "other": "other value"}' -H "Content-Type: application/json" http://localhost:3000/users/uuid**
**console**: true
**response**: {"id":"uuid","name":"name value","total":10,"other":"other value"}

### Expected behavior

POST (creates the object with all the parameters of the body.)
**curl -d '{"id": "uuid", "name": "name value", "total": 10, "other": "other value"}' -H "Content-Type: application/json"** http://localhost:3000/users
**console**: true
**response**: {"id":"uuid","name":"name value","total":10}

PATCH (creates the object with all the parameters of the body. OmitType doesn't work)
**curl --request PATCH -d '{"id": "uuid", "name": "name value", "total": 10, "other": "other value"}' -H "Content-Type: application/json" http://localhost:3000/users/uuid**
**console**: true
**response**: {"name":"name value","total":10}

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "prueba",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^9.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Use `whitelist: true` to strip undocumented properties from the final class. This is how `class-transformer` and `class-validator` work. Please refer to their docs for more info

**Comment by JamieYnonan** [comment]
thanks
