### ISSUE TITLE
route exclusion from the setGlobalPrefix not taken in account when enableVersioning is set

### ISSUE THREAD

**Issue by cperuzzi** [nestjs/nest#10215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi folks,

When you create an API and set the global prefix to something with a configuration containing exclusion like this
`app.setGlobalPrefix('api', {
    exclude: [
      "/my-route",
    ],
  });`

the 'my-route' is not taken in account at all if I enable the API versioning like this :

`app.enableVersioning({
    type: VersioningType.URI,
    defaultVersion: '1',
  });`

### Minimum reproduction code

https://github.com/cperuzzi/nest-routing-issue

### Steps to reproduce

1. npm install
2. npm start
3. use the route http://localhost:3000/api/v1/route => it returns something
4. use the route http://localhost:3000/route => 404

### Expected behavior

when a route is excluded in the global prefix it should be excluded even if the route versioning is enabled

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.x

### Packages versions

```
[Nest CLI]
Nest CLI Version : 9.1.1 

[Nest Platform Information]
platform-express version : 9.0.11
schematics version       : 9.0.2
testing version          : 9.0.11
common version           : 9.0.11
core version             : 9.0.11
cli version              : 9.1.1

```

### Node.js version
16.17.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by quangtran88** [comment]
I think the expected route should be [](http://localhost:3000/v1/route) because `setGlobalPrefix` and `enableVersioning` should behave independently. When set the `exclude` option only for `setGlobalPrefix` but not for `enableVersioning`, then the versioning should be applied normally. I suggest the current behavior should be fixed in this way but I don't know if it'll break any existing apps out there.

**Comment by cperuzzi** [comment]
one question request then it to be able to exclude the same route from the versioning as well

**Comment by gitSambhal** [comment]
Try adding 
```
  @Version(VERSION_NEUTRAL)
```
to the controller method.

**Comment by cperuzzi** [comment]
When I add `VERSION_NEUTRAL` it does have the behavior of putting the excluded route to the http://localhost:3000/v1/route but in this case, I have to add the v1 version in all of my controllers explicitly. 

It would be great just to have the possibility to exclude a specific route (or a list) from all the global route prefixes.

**Comment by gitSambhal** [comment]
@cperuzzi I think you have added the version_neutral at the controller level, you need to add it to the function level only.

**Comment by ricardodantas** [comment]
This is not working for me as well.

**Comment by crice88** [comment]
My excluded routes are completely hosed right now when version is bumped from 9.2.1 to latest. We have a similar setup to OP.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11650
