### ISSUE TITLE
DI: Transitive requirements for imported module providers works incorrectly

### ISSUE THREAD

**Issue by jmarianski** [nestjs/nest#10211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When declaring module A, B and C I expect, that when I import C into B and B into A, if provider C exports provider serviceC1 and providerC2 and provider C1 injects providerC2 (or any other injectable code), then service A is required to import providerC2 or else the application breaks.

More concrete example:
module A is AuthModule
module B is UserModule
module C is TypeOrmModule

in AuthModule I import UserModule, declare UserService as provider and try to use it. In UserModule I inject repository of User. Application breaks since I'm using TypeOrmModule.forFeature inside UserModule instead of declaring it in the AuthModule.

Issue occurs in other types of injections, I've created a fake module, attached an injection here, supplied it there and injection breaks.

### Minimum reproduction code

https://github.com/jmarianski/typeorm-transitive-repository

### Expected behavior

I would expect DI to solve it by supplying the dependencies to the module it needs without the need to redeclare it in uppermost context.

Also would be great if there was a possibility to redeclare dependencies in module declaration.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "nest-typescript-starter",
  "private": true,
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/event-emitter": "^1.3.1",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/typeorm": "^9.0.1",
    "bcrypt": "^5.0.1",
    "mysql2": "^2.3.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.5",
    "typeorm": "^0.3.8"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.4",
    "@types/node": "^18.0.3",
    "@types/passport-local": "^1.0.34",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.5",
    "@typescript-eslint/parser": "^5.30.5",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^28.1.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "sqlite3": "^5.0.11",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.5",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

14.18.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I'm pretty sure it could be solved with global modules by the looks of it. However personally I wouldn't want UsersModule / AuthModule to be singletons inside the application. 

Be mindful, I've experimented in the code with injecting the service from different module into the other, that's why this behavior bugged me, since I was able to decouple UserService from requirements by using a config class that injected it for me with the use of static variables, however it doesn't solve the underlying issue.

**Comment by jmcdo29** [comment]
If you are trying to re-use a provider that was previously created by another module, you shouldn't add that provider to the new module's `providers` array. Instead, you should add the original module to the new module's `imports` to provide access to what the original module has in its `exports` array. 

Any time you add a provider to a `providers` array, Nest knows to make a new instance of that provider in the current module's context, which in your case means that you don't have access to all the same providers (like the typeorm repository) without basically rebuilding the original module in the new module.

For further support, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by jmarianski** [comment]
Ah, now I reminded myself why I wanted to do that. I wanted simply to try injecting an instance into already existing inject as a way to supplement an implementation of an already existing inject in a parent module in order to modify the behavior accordingly. Eg. in app module I would add a line like

{ provide: 'UserServiceInterface', useClass: UsersService2 }

however I did not get it working cause - well - scope of the provision is tied to the module, not it's imported modules. Same goes for the requirements, which are tied to the module that is declaring the provider.

Anyways, thanks for the help, I think I know where to go in order to go further with my ideas.

**Comment by jmcdo29** [comment]
Did you try using `useExisting` instead of `useClass`? That should pull the existing `UsersService2` from the container and expose it under the new `UserServiceInterface` injection token

**Comment by jmarianski** [comment]
I just tried and to no avail, injection replacement still didn't happen. Perhaps I'm doing something wrong. I've pushed my code with the change for useExisting but I think it didn't do the trick.

I guess DI injector is tied to the module scope and that's why such an injection would not work working across the modules.

**Comment by jmcdo29** [comment]
Let's continue any more discussion on Discord and see if we can figure out a solution to what you're trying to do.
