### ISSUE TITLE
ParseArrayPipe doesn't validate when using @Expose with groups on DTO

### ISSUE THREAD

**Issue by SergioArrighi** [nestjs/nest#10218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm attaching a CodeSandbox to reproduce the issue

I'm using ParseArrayPipe to validate an array of objects as body of a post endpoint
`@Post()
  async createAll(
    @Body(new ParseArrayPipe({ items: TestDTO })) testDTO: TestDTO[],
  ) {
    console.log('validated');
 }`

where TestDTO is defined as follows:
`import { Expose, Type } from 'class-transformer';
import { IsInt, IsIP } from 'class-validator';

export enum Role {
  User = 'user',
  Admin = 'admin',
  Robot = 'robot',
}

export class TestDTO {
  constructor(partial?: Partial<TestDTO>) {
    if (partial) Object.assign(this, partial);
  }

  @IsIP()
  @Type(() => String)
  @Expose({ groups: [Role.Admin, Role.Robot] })
  ipAddress: string;

  @IsInt()
  @Type(() => Number)
  @Expose({ groups: [Role.Admin, Role.Robot] })
  relayCount: number;
}
`

Please note the 'groups' property in the Expose decorator. In my true project I have an interceptor that sets the metadata but I tested without it and doesn't make any difference because as you will see check is static in class-transform.

Now when I shoot to this enpoint I end up in parse-array-pipe.js, method transform.
Then line 72
`return this.validationPipe.transform(item, validationMetadata);`
Then I end up debugging TransformOperationExecutor.js method getKeys line 372.
This method return empty array and this is the root cause of the issue.

Specifically it gets the keys right on line 384
`keys = Object.keys(object);`

Then on line 416 already something strange:
`keys = keys.concat(exposedProperties);`
This basically duplicates the keys in the array.

And finally line 444
`keys = keys.filter(key => {
    const exposeMetadata = storage_1.defaultMetadataStorage.findExposeMetadata(target, key);
    return (!exposeMetadata ||
        !exposeMetadata.options ||
        !exposeMetadata.options.groups ||
        !exposeMetadata.options.groups.length);
});`

This of course removes all the keys from array as I have groups defined in the DTO.

Please assist in making sense out of this because to me there is no rational explanation for this.
Thanks and regards

### Minimum reproduction code

https://codesandbox.io/s/nestjs-forked-qbzzvu?file=/src/app.controller.ts

### Steps to reproduce

1. npm install
2. npm run
3. Shoot post request at localhost:3000 with json payload: [{"ipAddress":"127.0.0.1","relayCount":1}]

### Expected behavior

The request is validated by the array validation pipe

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

class-transform, class-validate

### NestJS version

9.0.11

### Packages versions

```
{
"dependencies": {
    "@nestjs/common": "9.0.11",
    "@nestjs/core": "9.0.11",
    "@nestjs/platform-express": "9.0.11",
    "class-transformer": "0.5.1",
    "class-validator": "0.13.2",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.5.6"
  },
  "devDependencies": {
    "@nestjs/cli": "^6.9.1",
    "@nestjs/schematics": "^6.7.0",
    "@nestjs/testing": "^6.8.0",
    "@types/express": "^4.17.1",
    "@types/jest": "^24.0.18",
    "@types/node": "^12.7.8",
    "@types/supertest": "^2.0.8",
    "jest": "^24.9.0",
    "prettier": "^1.18.2",
    "supertest": "^4.0.2",
    "ts-jest": "^24.1.0",
    "ts-loader": "^6.2.0",
    "ts-node": "^8.4.1",
    "tsconfig-paths": "^3.9.0",
    "tslint": "^5.20.0",
    "typescript": "^3.6.3"
  }
}

```

### Node.js version

17.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
if you believe that this is a bug on `class-transformer`, report it to them insted.

```bash
npm docs class-transformer
```

**Comment by SergioArrighi** [comment]
Well actually I would need a second opinion because it could be possible that I'm misusing nest.
I will update title.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
