### ISSUE TITLE
[Common:CacheInterceptor] Error: "undefined" is not a cacheable value

### ISSUE THREAD

**Issue by thesoundfromthesky** [nestjs/nest#10225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When `null` or `undefined` values are saved with `this.cacheManager.set(key, undefined)`,
cache-manager-ioredis will throw error and crush app.

```ts
new Promise((resolve, reject) => {
Error: "undefined" is not a cacheable value
```
When `CacheModule` is used with with `cache-manager-ioredis` package, `this.cacheManager.set()` becomes promise.

`this.cacheManager.set()` is being used in "CacheInterceptor", 
https://github.com/nestjs/nest/blob/master/packages/common/cache/interceptors/cache.interceptor.ts#L58
Line 58 throws unhandled promise error and crushes app

### Minimum reproduction code

https://github.com/thesoundfromthesky/nestjs-cache-interceptor-error-reproduction

### Steps to reproduce

1. `npm install`
2.  set redis url string in `app.module`
3. `npm start:dev`
4.  open browser
5.  go to url `http://localhost:3000`
6. CacheInterceptor is applied to default route( / ) and returns undefined which will throw the error and crushes the app.

### Expected behavior

I expect error to be handled properly so it can prevent app crushing or prevent Nil value going through `cachemanager.set()` with if statement

I was playing around and came up with two solutions.

1. change callback to async and introduce try catch like this
```ts
tap(async () => {
        try {
          await this.cacheManager.set('key', undefined);
        } catch (err) {
          // Error won't get handled by filter exceptions
          console.error(err);
        }
      })
```

2. Nil check
```ts
      tap((value) => {
        // save only if value is not nil
        if (!isNil(value)) {
          this.cacheManager.set('key', value);
        }
      })
```

Thank you

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
 "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "cache-manager": "^4.1.0",
    "cache-manager-ioredis": "^2.1.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/cache-manager": "^4.0.2",
    "@types/cache-manager-ioredis": "^2.0.2",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "~4.7.4"
  },

```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? Adding try..catch block sounds reasonable

**Comment by thesoundfromthesky** [comment]
It's an honor to create a PR for this issue.
After creating this issue, I have been thinking If I could improve the solution. I've got an idea from [https://github.com/nestjs/nest/issues/6427](https://github.com/nestjs/nest/issues/6427) and I would like to discuss about 3rd option with you.

3. Introducing `CacheInterceptor#setCache`

```ts
protected async setCache<T>(
  key: string,
  value: T,
  options?: CachingConfig,
): Promise<void>  {
  try {
    await this.cacheManager.set(key, value, options);
  } catch (err) {
    Logger.error(`key: ${key} value: ${value}`, 'CacheInterceptor');
    console.error(err);
  }
}
```
About above method
Pros
1. This will prevent app crushing due to `unhandled promise rejection`.

Cons
1. This will block `async/sync errors` reaching exception filters. Someone might have been handling `sync errors` with `exception filters`, but this method might disable their logic.

or just introduce wrapper without any additional logic
```ts
protected setCache<T>(
  key: string,
  value: T,
  options?: CachingConfig,
): void  {
    this.cacheManager.set(key, value, options); 
}
```
About above method
Pros
1. This will let all the `errors` flow as is. `sync errors` will reach `exception filters`, `async errors` will crush app. 
2. If a user is having problem with `async errors`, they can extend `CacheInterceptor` and override `#setCache` to implement their own solution.

Cons
1. If somebody is already using `#setCache`  in their extended `CacheInterceptor`, this might break their logic.
 
with above method `CacheInterceptor#intercept` will return following

```ts
  return next.handle().pipe(
        tap(response => {
          const args = isNil(ttl) ? [key, response] : [key, response, { ttl }];
          this.setCache(...args);
         })
```

`setCache()` definition is from [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cache-manager/index.d.ts#L67](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cache-manager/index.d.ts#L67)
  
If introducing a method for this issue is unreasonable, I will move on with first solution.

Thank you

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10243
