### ISSUE TITLE
async static method from ConfigurableModuleBuilder return  DynamicModule Type instedof Promise<DynamicModule>

### ISSUE THREAD

**Issue by femike** [nestjs/nest#10226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When set async function as async typescript sayd me "meoow"  😹

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-kekcbf?file=src/example.module.ts

### Expected behavior

```ts
export class ExampleModule extends ConfigurableModuleClass {
  //          👇️
  static async forRootAsync(options: typeof ASYNC_OPTIONS_TYPE) {
    const { name } = await options.useFactory();

    return {
      ...super.forRootAsync(options),
    };
  }
  ```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.11

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "config": "^3.3.7",
    "express-session": "^1.17.3",
    "passport": "^0.6.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@faker-js/faker": "^7.5.0",
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/swagger": "^6.1.1",
    "@nestjs/testing": "^9.0.0",
    "@types/config": "^3.3.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.4",
    "@types/node": "^18.0.3",
    "@types/passport-local": "^1.0.34",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.5",
    "@typescript-eslint/parser": "^5.30.5",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^28.1.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.5",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.7.4"
  },
```

### Node.js version

v16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Looks like we should make the type `DynamicModule | Promise<DynamicModule>` for both the root and the root async methods, as `imports` can take in a `Promise<Module>`. By default, the root ans root async are sync, but you do have a use case where `static async forRootAsync` seems valid

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10227

**Comment by uiii** [comment]
This is still not fixed?
