### ISSUE TITLE
Cannot @Inject(REQUEST) in Services Class

### ISSUE THREAD

**Issue by nmquaan** [nestjs/nest#10229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The request Object always null when communicating Microservices.
```
{"message":{"stack":"TypeError: Cannot read properties of null (reading 'header')\n    at BaseMicroService.sendAsync
```

### Minimum reproduction code

https://discord.com/channels/520622812742811698/1015926538769805422

### Expected behavior

I can get header value into Request object.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.1

### Packages versions

```json
    "@nestjs/bull": "^0.6.1",
    "@nestjs/common": "^9.0.11",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.11",
    "@nestjs/cqrs": "^9.0.1",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/microservices": "^9.0.11",
    "@nestjs/platform-express": "^9.0.11",
    "@nestjs/swagger": "^6.1.1",
    "@nestjs/terminus": "^9.1.1",
    "@nestjs/typeorm": "^9.0.1",
```

### Node.js version

v16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
