### ISSUE TITLE
How to get module's service by it's property?

### ISSUE THREAD

**Issue by zelid** [nestjs/nest#1022]
There is a module called `widgets.module.ts`
Inside it there are a lot of services like: 
`latest-news-widget.service.ts`
`contacts-widget.service.ts`
etc...

Each widget service class implements:
```
export interface WidgetService {
    readonly ID: number;
    readonly NAME: string;
    getData(inputParams: any): any;
}
```

There is a place inside `pages/pages.service.ts` which takes a list of widgets and in this place I need to get the right `XxxWidgetService` registered in `widgets/widgets.module.ts` by service's  ID or NAME which corresponds to Angular's widget name.

Pseudocode:
```
async getPageData(pageSlug: string)
{
    const page = await this.pageRepository.findOne(pageSlug);

    for (const widget of page.widgets)
    {
        const widgetService = widgetsModule.getServiceByName(widget.NAME);
        widget.data = await widgetService.getData(params);
    }

    return page;
}
```

How do you recommend to get the right service from registered within some module by service's property like ID or NAME (the `const widgetService = widgetsModule.getServiceByName(widget.NAME);` part of pseudocode above)?

**Comment by whtiehack** [comment]
```
widgetsModule.getServiceByName(name){
  return this[name+'WidgetService']
}
```

**Comment by kamilmysliwiec** [comment]
Use `ModuleRef`, see here https://docs.nestjs.com/fundamentals/circular-dependency (Module Reference)
