### ISSUE TITLE
Wrapper code for eliminating authentication boilerplate

### ISSUE THREAD

**Issue by KevinMusgrave** [nestjs/nest#10231]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Most applications don't need custom authentication code. Something standard with reasonable defaults would be fine. There is [documentation](https://docs.nestjs.com/security/authentication) for authentication, but it's a lot of boilerplate, and copying all of this boilerplate is not ideal.

### Describe the solution you'd like

It would be great if nestjs provided a separate package like `@nestjs/auth` that wrapped all of the boilerplate, so that authentication could be taken care of with a few lines of code.

People who want a custom approach could keep all their existing boilerplate, while people who want a "reasonable default" could install `@nestjs/auth` and use the wrapper.

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

-

**Comment by micalevisk** [comment]
the issue is that the authentication can be done by several 3rd-party libs. The docs only shows the usage with `passport`

So the `@nestjs/auth` would be a wrapper for `@nestjs/passport` (which is a wrapper for `passport` lol) or waht?

**Comment by KevinMusgrave** [comment]
It seems like I have to copy-paste: 

- UsersService
- AuthService
- LocalStrategy
- JwtStrategy
- AuthModule

It'd be nice if I could just import AuthModule from `nestjs/auth`, and pass in some basic configuration options.

**Comment by micalevisk** [comment]
I'm not sure if we could have a flexible wrapper around this :thinking:  I believe that the intention of `@nestjs/password` is to avoid boilerplate set up already, we could improve it instead, I guess

**Comment by micalevisk** [comment]
or maybe you could write a builder around that pattern and publish as a community lib.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
