### ISSUE TITLE
Serverless Modules

### ISSUE THREAD

**Issue by Noriller** [nestjs/nest#10230]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Today, you have to learn how to use serverless and there are things like the Serverless Framework that help, but even with that you still need to know a lot.

It's also costly to deploy a full application when you might want just cloud functions that use a bucket or database.

Nest has great DX, but it would be costly to run it as cloud functions and you would still need to know how to deploy each piece.

### Describe the solution you'd like

I want to develop in localhost as normal, but run commands to deploy it to the cloud without even having to mind which resources I need.

Each route would become a cloud function, repositories could become SQL or NoSQL services...

This would mean we could develop something that uses a bucket with part (or all of it) being hosted as cloud services and the rest pointing to the services created.

All I would need to do is to set the env variables, the rest would be taken care of.

### Teachability, documentation, adoption, migration strategy

I believe that Architect [arc.codes](arc.codes) is one thing that comes closest to what I think it should be, but it would have the nest spin to it. Also some fullstack frameworks are doing it, in a way, with the BFF functions being made in a minimal way and being deployed as cloud functions (like next and remix).

You create a serverless module, set the env variables needed, call the appropriate decorators to name the resources in the cloud provider (to create or use existing ones) and develop as if you're deploying a "normal" non cloud based application, it would, then, be all transpiled, trimmed and all the resources needed would be created/updated.

### What is the motivation / use case for changing the behavior?

In the docs: https://docs.nestjs.com/faq/serverless#using-standalone-application-feature

There's no comparison between a simple node script vs a full application and more and more, many companies are migrating to microservices in cloud providers, but this comes with extra costs from DX to having to orchestrate all of the services and endpoints.

Nest has one of the best DX out there and more and more, knowing cloud is becoming akin to knowing git or docker.

It would become easy to work with TS. all tools and the cli while easily deploying everything in cloud functions.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
