### ISSUE TITLE
Only require dependencies in starter project which are used

### ISSUE THREAD

**Issue by mcmxcdev** [nestjs/nest#10244]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am using NX to generate a Nest workspace, and I am wondering about the necessity to have the following dependencies installed out of the box:

```
"reflect-metadata": "^0.1.13",
"rxjs": "^7.0.0"
```

I don't see `rxjs` operators used anywhere in the starter project. 
I am not familiar with `reflect-metadata`, but it sounds to me that it would be required for old environments only.

### Describe the solution you'd like

Only require dependencies which are used in a starter template to keep it simple and the bundle size small.

### Teachability, documentation, adoption, migration strategy

/

### What is the motivation / use case for changing the behavior?

Remove the need to ask yourself what is needed and what's not.

**Comment by kamilmysliwiec** [comment]
Both packages are required, peer dependencies of NestJS core & common.
