### ISSUE TITLE
Interceptor isn't forwarding an Event from a Custom Transport Strategy

### ISSUE THREAD

**Issue by SuttonO-Webeo** [nestjs/nest#10240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have created a custom transport strategy that is meant to be intercepted, something logged, and then the method within the controller should be fired. However, the controller is not being fired after the interceptor.

### Minimum reproduction code

https://github.com/SuttonO-Webeo/custom-transport-test

### Steps to reproduce

1. clone repo
2. `npm install`
3. `npm run start:dev`

You should see logs stating `inside the rpc if statement` (every 5 seconds) but not the follow on logs from the controllers or service stating `inside controller event pattern` and `inside service test pattern`

However, if you hit `http://localhost:3000` you will see `inside the http if statement`, then `inside controller http`, then `inside service get hello`

### Expected behavior

I'd expect the custom strategy to work in the same way as http does. With the interceptor firing and then getting forwarded onto the controller.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "custom-transport-test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.0.11",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
@kamilmysliwiec I'm unsure if this is due to calling `handler` directly, like our docs show, meaning that to trigger the interceptor _properly_ you'd need to use some sort of custom `ClientProxy`, or if there is some sort of error in the way we currently handle custom transports

**Comment by kamilmysliwiec** [comment]
If you bind at least 1 interceptor, handlers are wrapped into RxJS streams. These streams are _lazy_ aka cold (as mentioned in the docs). That means, you have to subscribe to them in order to execute the underlying stream's logic:

```typescript
const streamOrResult = await handler({ key: pattern });
if (isObservable(streamOrResult)) {
  streamOrResult.subscribe();
}
```
This might be a valuable addition to the docs so if you're willing to contribute, PRs are more than welcome @SuttonO-Webeo 🙌
