### ISSUE TITLE
ValidationPipe and WsException filter not working

### ISSUE THREAD

**Issue by sadstorman** [nestjs/nest#10258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Its throws  an BadRequest error in the console but is not working properly. I followed this docs [https://docs.nestjs.com/websockets/exception-filters](https://docs.nestjs.com/websockets/exception-filters)
![image](https://user-images.githubusercontent.com/68755448/189213394-746cfd2a-b9f3-4657-b7b1-dd86fae99422.png)

### Minimum reproduction code

https://codesandbox.io/s/suspicious-hopper-4ic18o?file=/src/driver.gateway.ts

### Expected behavior

Validation pipe: not allow to send a number if DTO says must be a string
Filter: catch the error and not throwing that, like HttpException.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
"dependencies": {
    "@googlemaps/google-maps-services-js": "^3.3.16",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-socket.io": "^9.0.11",
    "@nestjs/serve-static": "^3.0.0",
    "@nestjs/swagger": "^6.0.4",
    "@nestjs/typeorm": "^9.0.0",
    "@nestjs/websockets": "^9.0.11",
    "@types/aws-sdk": "^2.7.0",
    "aws-sdk": "^2.1191.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "firebase-admin": "^11.0.0",
    "joi": "^17.6.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "socket.io": "^4.5.2",
    "swagger-ui-express": "^4.5.0",
    "typeorm": "^0.3.7"
  },
```

### Node.js version

18.6.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
