### ISSUE TITLE
UNIT Test case not working after Jest 27.x upgrade

### ISSUE THREAD

**Issue by suryakanta101** [nestjs/nest#10252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We have an application run with nestjs , angular 12 and jest. 

Recently we upgraded the jest version to jest v27 from v26. 

We are seeing Angular unit test case Testbed is working fine but NestJs testcase are not working,  giving undefined 

const mod: TestingModule = await Test
      .createTestingModule({.....

### Minimum reproduction code

https://stackoverflow.com/questions/71522703/why-jest-not-working-as-expected-after-upgrading-to-the-latest-version-27-5-1

### Expected behavior

It should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.3

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by micalevisk** [comment]
# [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by suryakanta101** [comment]
Basically when we are using Jest v26, then Circular Dependency check was not mandatory. But when we upgrade to Jest v27 , now all test case are failing under nestjs applications.

**Comment by jmcdo29** [comment]
Okay. We still need a minimum reproduction to begin diagnosing if this is in nest, something in jest/ts-jest, or a problem in your code.

**Comment by suryakanta101** [comment]
Our application is based on NestJs and Jest v27 

When we had jest v26, all test cases were working perfectly.  But when we migrate to jest v27, we faced all type of below circular dependency issue with same code base.

Most of my modules have circular reference, in order to create type resolvers and allow data to be queried from both sides of the relation.

I have the current scenario:

person.module.ts

@Module({
  exports: [PersonService],
  providers: [PersonService, PersonResolver],
  imports: [forwardRef(() => AddressModule))]
})
export class PersonModule {}
address.module.ts

@Module({
  exports: [AddressService],
  providers: [AddressService, AddressResolver],
  imports: [forwardRef(() => PersonModule)]
})
export class AddressModule {}
All fine for the application perspective, works like a charm. My problem is with testing. I'm creating mocked modules with @nestjs/testing features and I got caught with a problem because of this circular reference.

export function createAddressModule(): Promise<TestingModule> {
  return Test.createTestingModule({
    imports: [PersonModule], 
    providers: [
      AddressService,
      AddressResolver,
      {
        provide: getRepositoryToken(Address),
        useClass: Repository
      }
    ]
  }).compile()


I'm not able to create a TestingModule instance because the function is not being able to mock this import's providers. Is there a proper way to do that that I'm not seeing here?

I am able to fix this issue by adding
@Inject  ForwardRef while injecting in service file, but number of files are huge... Not possible to do this for whole project.

Thanks y'all for the support

**Comment by jmcdo29** [comment]
> I am able to fix this issue by adding `@Inject(ForwardRef)` while injecting in service file

That should already be there anyways.

As you have yet to provide a reproduction, I can only assume this is an issue with _your_ code and not a bug in the framework. If you provide a reproduction, I'll re-open the issue.
