### ISSUE TITLE
Microservices logic

### ISSUE THREAD

**Issue by Spartaques** [nestjs/nest#10265]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a project i want to migrate to nest from php laravel. Php laravel has awesome https://laravel.com/docs/9.x/artisan cli commands functionality that makes possible to run some cli entrypoints available to your app. This case is very useful because we can have different entrypoints to app. For example, http web/api, cron cli commands, kafka consumers etc. And everything use one codebase. In nest js i only found https://docs.nestjs.com/standalone-applications and nest-commander. But i didnt find a way how to reuse code base normally and have several entrypoints with different processes. 
My requirements:
1. Reusing code
2. Have one repo
3. Have possibility to scale different entrypoints separately. For example, kafka can scale by increasing topic partitions count. I wanna have for example 1 instance of nest to handle api, and 3 instance of best that handle kafka topic “test” with 3 consumers

 P.s. nest js is awesome project. I like it)))

### Describe the solution you'd like

Make possible to have not only http entrypoint, but for example cli entrypoint as well as http of the same repo

### Teachability, documentation, adoption, migration strategy

https://laravel.com/docs/9.x/artisan

### What is the motivation / use case for changing the behavior?

Scalability

**Comment by jmcdo29** [comment]
`nest start --entryFile`?

**Comment by Spartaques** [comment]
I suggest it's better to have clean separation between api and cli. It's nice to have separate entry for cli and possibility to don't use different entryFiles but have one entryfile with different program name. Like nest start-cli consume:test or nest start-cli consume:test2

**Comment by Spartaques** [comment]
Maybe it's wrong approach for nest and node js, but i dont mind its wrong. I suggest it's wrong approach to only have possibility to handle everything in one node process (http as well as kafka consumers) without integrated poccibility to separate this processes using native framework way (without copy pasting files). As solution, i propose to make clean separation between CLI and HTTP entrypoints.

**Comment by jmcdo29** [comment]
> As solution, i propose to make clean separation between CLI and HTTP entrypoints.

Isn't that what `entryFile` would allow? Not sure I'm following the proposal here.

**Comment by micalevisk** [comment]
@Spartaques what would be the difference between `nest start` and `nest start-cli`? :thinking: (I didn't use Laravel before)

**Comment by kamilmysliwiec** [comment]
This sounds like something we already provide with the `entryFile` option. Also, to share code and manage multiple apps in 1 repository, you could turn your repo into a monorepo (https://docs.nestjs.com/cli/monorepo).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
