### ISSUE TITLE
Get decorator handles HEAD method

### ISSUE THREAD

**Issue by tvaliasek** [nestjs/nest#10274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you place @Get decorated route before @Head decorate route binded to the same url all HEAD request got handled by Get route.

``` ts
import { Controller, Get, Head, HttpCode, ForbiddenException } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  // this works
  @HttpCode(204)
  @Head()
  getHead() {
    // do nothing
  }

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  // this ignores exception and HttpCode decorator, request is handled by Get
  @Get('test')
  getHelloTest(): string {
    console.log('hadled by Get');
    return this.appService.getHello();
  }

  @HttpCode(204)
  @Head('test')
  getFailedHead() {
    throw new ForbiddenException('This should end as 403');
  }
}
``` 

### Minimum reproduction code

https://github.com/tvaliasek/nestjs-greedy-get

### Steps to reproduce

# Setup
1. npm ci

# Reproduction
1. npm run start:dev
2. open new terminal
3. curl --head http://localhost:3000/test
4. See the console, message "handled by Get" occurs and HTTP response has status 200 instead of 403

### Expected behavior

Head request should be handled by @Head decorated route regardless of its order in the controller.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.11

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v16.13.0
NPM Version    : 8.14.0 

[Nest CLI]
Nest CLI Version : 9.1.3

[Nest Platform Information]
platform-express version : 9.0.11
schematics version       : 9.0.3
testing version          : 9.0.11
common version           : 9.0.11
core version             : 9.0.11
cli version              : 9.1.3

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
if you declare the method with `@Head('test')` before the `@Get('test')` one, it will work

Not sure if this is a bug or a expected behavior of Express :thinking:

**Comment by tvaliasek** [comment]
Yes, I just tried it with pure express and it behaves exactly the same. I was convinced that 8.x version does not suffer from this.

**Comment by micalevisk** [comment]
so since that's the expected behavior of the underlying HTTP server, we shouldn't change it, right?

I just tested with v8 as well.
