### ISSUE TITLE
NestJs Dev server keeps restarting in a loop on ubuntu

### ISSUE THREAD

**Issue by niteshbalusu11** [nestjs/nest#10277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My nestjs dev server keeps restarting a loop when starting with `nest start --watch` on Ubuntu machines. It works fine on windows and mac.

It keeps giving the following messages before restarting: Is it some typescript issue?
```
[10:09:53 PM] File change detected. Starting incremental compilation...

[10:09:54 PM] Found 0 errors. Watching for file changes.
```

### Minimum reproduction code

https://github.com/niteshbalusu11/lndboss

### Steps to reproduce

1. Clone the repo on ubuntu machine
2.  Install deps using `yarn`
3. `yarn dev` to start the dev server
4. watch it restart in an infinite loop.

### Expected behavior

The Dev server only restarts when it detects changes.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.11

### Packages versions

```json
  "dependencies": {
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@mui/icons-material": "^5.10.3",
    "@mui/material": "^5.10.4",
    "@mui/x-date-pickers": "^5.0.0",
    "@nestjs/common": "^9.0.11",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.11",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.11",
    "@nestjs/platform-socket.io": "^9.0.11",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/websockets": "^9.0.11",
    "antd": "^4.23.0",
    "async": "^3.2.4",
    "axios": "^0.27.2",
    "balanceofsatoshis": "^12.27.0",
    "bcryptjs": "^2.4.3",
    "chart.js": "^3.9.1",
    "class-sanitizer": "^1.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "json-to-pretty-yaml": "^1.2.2",
    "jwt-decode": "^3.1.2",
    "lightning": "^5.21.0",
    "nest-winston": "^1.7.0",
    "next": "^12.2.5",
    "notiflix": "^3.2.5",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "qrcode.react": "^3.1.0",
    "react": "^18.2.0",
    "react-chartjs-2": "^4.3.1",
    "react-copy-to-clipboard": "^5.1.0",
    "react-dom": "^18.2.0",
    "react-js-cron": "^2.1.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.6",
    "socket.io-client": "^4.5.2"
  },
```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
didn't manage to reproduce your issue

![image](https://user-images.githubusercontent.com/13461315/189792828-57cd5d88-c113-470f-a6a1-8049983f64b2.png)

Make sure your code didn't end up changing any TS file under `src/`

**Comment by niteshbalusu11** [comment]
oops. can you create a `.env` file in the root of the project and add this to the file and restart.
`ENCRYPTION_KEY="b4970320a3601d19b876c18ce2eb895d687962d3f0b72e0d4de05ed74be34d9a`

**Comment by micalevisk** [comment]
same error, no loops

**Comment by micalevisk** [comment]
ok, I've run `cp .env.example .env` but got no loops on `yarn dev` 

![image](https://user-images.githubusercontent.com/13461315/189793420-0b1fbc14-12d1-474b-b5e0-2c0d4e6aba3c.png)

**Comment by niteshbalusu11** [comment]
ah yeah, I accidentally typed the wrong key in `.env`. It's called `JWT_SECRET_DEV`.
Ok, you have managed to reproduce then.
What I don't understand is, that it does not happen on a mac or windows.

**Comment by micalevisk** [comment]
looks like that happens due to this `onModuleInit`: https://github.com/niteshbalusu11/lndboss/blob/0103bc4b7c37f97e6da749c3f9af331ae7e84db5/src/server/modules/view/view.service.ts#L14

![image](https://user-images.githubusercontent.com/13461315/189795714-d43950ca-21fd-4f5c-b13f-5cf2bd414e66.png)

**Comment by niteshbalusu11** [comment]
Ok. Will take a look, wonder why it doesn't happen on mac and windows though. 

Thank you.

**Comment by dhia-rizqullah** [comment]
Hey, @niteshbalusu11. Have you perchance found the solution to this problem? 

I have the same setup (nest, next, ubuntu) & encountered the same exact problem.  My coworkers that use Mac also do not encounter this issue.

**Comment by niteshbalusu11** [comment]
> Hey, @niteshbalusu11. Have you perchance found the solution to this problem? 
> 
> 
> 
> I have the same setup (nest, next, ubuntu) & encountered the same exact problem.  My coworkers that use Mac also do not encounter this issue.

Nope, never found the solution. I just use a Mac.
