### ISSUE TITLE
Fastify inside a docker

### ISSUE THREAD

**Issue by dribro** [nestjs/nest#1027]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When changing from express.js to fastify as described in the documentation, if the application is running inside a docker, it will return ERR_EMPTY_RESPONSE.
The issue is that if you're running fastify inside a docker, you need to specify the host, which should be '0.0.0.0', an issue that doesn't happen if you stick with the default express.js configuration.
As nest is so micro-service oriented, I expect this to be a issue that will happen with some frequency.

## Expected behavior
Mention of this abnormal behavior inside https://docs.nestjs.com/techniques/performance 
Maybe even a mention of this tool https://github.com/sindresorhus/is-docker (Something that wasn't useful for my particular scenario, but might be to others)

## Minimal reproduction of the problem with instructions
**FAILS**
```typescript
// main.ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule, new FastifyAdapter());
  await app.listen(3000);
}
bootstrap();
```
**SUCCESS**
```typescript
// main.ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule, new FastifyAdapter());
  await app.listen(3000, '0.0.0.0');
}
bootstrap();
```

## What is the motivation
Took me a while to find the solution 😄 

<pre><code>
- Nest version: 5.2.2
- Platform:  Docker
</code></pre>

Others:
https://github.com/fastify/fastify-cli/issues/57 relevant issue

**Comment by weeco** [comment]
Yep I noticed the same here, took me a while to figure it out since that only happened inside of Docker. 

I was using the alpine-node:10 base image. What docker base image did you use?

**Comment by dribro** [comment]
it was a custom company image.

I now realized I made a issue in the wrong place https://github.com/nestjs/docs.nestjs.com

oops!
