### ISSUE TITLE
IntersectionType from @nestjs/swagger does not run validation with the ValidationPipe

### ISSUE THREAD

**Issue by Chowarmaan** [nestjs/nest#10282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have created different endpoints for the different DTOs.
 POST /code - Uses the CodeDTO definition, and when run with no request body data, is validated and returns errors

 POST /desc - Uses the DescriptionDTO definition, and when run with no request body data, is validated and returns errors

 POST /both - Uses the TwoDTO definition, which uses the @nestjs/swagger IntersectionType to combine the DTOs, but when the empty request body is submitted, the validat
<img width="331" alt="DTOsCombined" src="https://user-images.githubusercontent.com/175738/190220669-38955e7a-ca05-476a-b9d8-7a3e51da6694.png">
ion is not run, there are no errors, and the route returns 201 Created.

### Minimum reproduction code

https://github.com/Chowarmaan/IntersectTypeIssue

### Steps to reproduce

1. npm install
2. npm run start:dev
3. browse to Swagger docs (localhost:30000/api) and look at the Schemas.  The TwoDTO is the proper combination, and does have the indicators of the validation entries.
4. Send a POST to /code without any request body, and the validation errors are returned
5. Send a POST to /desc without any request body, and the validation errors are returned
6. Send a POST to /both without any request body, and the validation errors are not returned, and the route completes with a 201 Created response.

### Expected behavior

The combined errors from the CodeDTO and the DescriptionDTO to have been returned when the POST /both with an empty request body is received.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

9.1.3

### Packages versions

```json
{
  "name": "intersect-type-issue",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/class-transformer": "^0.4.0",
    "@nestjs/class-validator": "^0.13.4",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/swagger": "^6.1.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.5.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

[System Information]
OS Version     : Windows 10
NodeJS Version : v18.5.0
NPM Version    : 8.12.1

[Nest CLI]
Nest CLI Version : 9.1.3

[Nest Platform Information]
class-transformer version : 0.4.0
platform-express version  : 9.0.11
class-validator version   : 0.13.4
schematics version        : 9.0.3
swagger version           : 6.1.2
testing version           : 9.0.11
common version            : 9.0.11
core version              : 9.0.11
cli version               : 9.1.3

**Comment by jmcdo29** [comment]
Change from using `@nestjs/class-validator` and `@nestjs/class-transformer` to the original `class-valdiator` and `class-transformer`. The `mapped-types` package uses `class-validator` and `class-transformer` under the hood, and the `@nestjs/*` variants save the metadata to their own internal metadata storages due to how `c-v`/`c-t` initially work.

**Comment by Chowarmaan** [comment]
Thanks.  That corrects the issue.  Is there any plans for this to be in the NestJS version of the classes?  If not, is there a way to use maintained classed (since NestJS forked these to have maintained code) instead of these older libraries?

**Comment by jmcdo29** [comment]
We actually haven't made many changes to the `@nestjs/class-validator` or `@nestjs/class-transformer` packages since we forked them., really just a few stylistic things and removing the docs. We forked them _in case_ there was a lapse of support by the original maintainers and we needed to start moving the functionality to be more geared towards Nest.

**Comment by Chowarmaan** [comment]
Do you think there might be a future time that the validation would work with the @nestjs variants?  I am looking to evaluate the maintenance of keeping individual DTOs (instead of using IntersectionType and the @nestjs libraries) which would have some replicated data in a few DTO areas, against the potential issue of the validation stopping altogether if future changes were made and the refactoring was extensive.

Right now, I use the IntersectionType so I can have parameters in the URL (pathing to the actual endpoint for a GET or PATCH), with the same rules as the payloads, that are on the main URL.  IE: /user/:userid, so that: `POST /user` with a payload of 

    {
        id: 'user1',
        name: 'John Doe',
        ...
    }

The payload would then have rules on it for the Id for length, patterns, etc.  For some routes, the rules are handy to save expensive data fetches.  

However, for some routes, the simple validation is not needed, as the route can simply return the 404 Not Found for bad data patterns, as the service fetch is not expensive.  This also allows for some routes to not even have the additional validation outside of a ParseIntPipe (or similar) to do the initial validation.

**Comment by jmcdo29** [comment]
Out of the box validation _does_ work. It's the `IntersectionType` and other mapped types that don't because of how class-validator stores the metadata. It uses an internal metadata storage instead of the `Reflect` API, so when `@nestjs/mapped-types` uses `class-validator.getMetadataStorage.getTargetTypeMetadatas(parentClass)` it reads that there's no metadata, because `@nestjs/class-validator#MetadataStorage !== class-validatoe#MetadataStorage`. We might be able to create some sort of hook to tell `@nestjs/mapped-types` _which_ validation library to use, similar to how the `ValidationPipe` works, but as of now it just loads `class-validator`

**Comment by Chowarmaan** [comment]
Sorry, I should have been clearer.  The validation does work well, it is just the use case you pointed me to share DTO properties with the IntersectionType, that has the validation error, on the included DTOs.  Any fields defined in the DTO that is using the IntersectionType are also handled properly in the validation.
