### ISSUE TITLE
ConsoleLogger prints an array of an object as `[object Object]`.

### ISSUE THREAD

**Issue by yukukotani** [nestjs/nest#10280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ConsoleLogger prints an object correctly. But an array of an object is printed as `[object Object]`.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-nglkvt?file=src%2Fapp.controller.ts

### Expected behavior

An array of an object should be printed with `JSON.stringify`.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : Linux 5.0
NodeJS Version : v16.14.2
NPM Version    : 7.17.0 

[Nest CLI]
Nest CLI Version : 9.0.0 

[Nest Platform Information]
platform-express version : 9.0.0
schematics version       : 9.0.0
testing version          : 9.0.0
common version           : 9.0.0
core version             : 9.0.0
cli version              : 9.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Looks like this comes from our [`isPlainObject`](https://github.com/nestjs/nest/blob/7db5638d3f7f683eb4432c9e4be42796f223e0e3/packages/common/utils/shared.utils.ts#L8) check, specifically where we check [`ctor instanceof ctor`](https://github.com/nestjs/nest/blob/7db5638d3f7f683eb4432c9e4be42796f223e0e3/packages/common/utils/shared.utils.ts#L21). With an array, `Array instanceof Array` comes back false it would seem. With this, our `colorize` method tries to `.toString()` the `[{ key: 'obj array' }]` which results in `[object Object]` like you're seeing. We can add an earlier check in the `isPlainObject` method for `Array.isArray(fn)` and return true if so, but I'm not sure what other implications that may have elsewhere in the internals

**Comment by kamilmysliwiec** [comment]
Following what @jmcdo29 wrote above, would you like to create a PR for this change @yukukotani?

**Comment by yukukotani** [comment]
@jmcdo29 @kamilmysliwiec Thanks for the explanation! Of course, I'll work on this.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10291
