### ISSUE TITLE
Memory leaks in ClientTCP

### ISSUE THREAD

**Issue by regevbr** [nestjs/nest#10286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when a tcp client proxy has an outstanding requests, and the connection to the server suddenly closes (due to network issues for example) no one cleans the routing maps, nor calls those callbacks to notify them, thus creating a memory leak and hanging promises/observers that will never be resolved.

### Minimum reproduction code

https://github.com/regevbr/nestjs-leak-reproduction

### Steps to reproduce

see test in reproduciton code

### Expected behavior

Outstanding callback should be called with an error and the routing map should be cleared, whenever the connection is closed

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.0.11",
    "@nestjs/platform-express": "^9.0.0",
```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10287
