### ISSUE TITLE
Error: Cannot find module '@nestjs/common'

### ISSUE THREAD

**Issue by Stryder91** [nestjs/nest#10289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, i have this issue when npm start my project

Of course i have installed @nestjs/common, @nestjs/core etc
(i can find them in node_modules).

I tried also npm i --legacy-peer-deps and npm i --force
And also tried @nestjs version 8.0.0 or 9.0.11 (latest)

Version : 
 "@nestjs/common": "^8.0.0",
 "@nestjs/core": "^8.0.0",

Node js version : v16.17.0

(the Minimum reproduction code repo is not correct, since i cannot show this repo but we must fill one) 

### Minimum reproduction code

https://github.com/Stryder91/auth_service

### Steps to reproduce

npm i
npm run start

### Expected behavior

Expecting to launch nestjs web server

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

```json
 "dependencies": {
        "@nestjs/axios": "^0.0.3",
        "@nestjs/common": "^8.0.0",
        "@nestjs/config": "^1.1.0",
        "@nestjs/core": "^8.0.0",
        "@nestjs/mongoose": "^9.0.1",
        "@nestjs/passport": "^8.0.1",
        "@nestjs/platform-express": "^8.0.0",
        "@nestjs/swagger": "^5.1.5",
        "@uniswap/v2-core": "^1.0.1",
        "class-transformer": "^0.4.0",
        "class-validator": "^0.13.1",
        "dotenv": "^14.3.2",
        "ethers": "^5.5.1",
        "helmet": "^4.6.0",
        "mailgun-js": "^0.22.0",
        "migrate-mongo": "^8.2.3",
        "mongoose": "^6.0.13",
        "passport": "^0.4.1",
        "passport-local": "^1.0.0",
        "reflect-metadata": "^0.1.13",
        "rimraf": "^3.0.2",
        "rxjs": "^7.2.0",
        "swagger-ui-express": "^4.1.6",
        "uuid": "^8.3.2"
    },
    "devDependencies": {
        "@nestjs/cli": "^8.0.0",
        "@nestjs/schedule": "^1.0.2",
        "@nestjs/schematics": "^8.0.0",
        "@nestjs/testing": "^8.0.0",
        "@types/chai": "^4.2.22",
        "@types/express": "^4.17.13",
        "@types/jest": "^27.0.1",
        "@types/mailgun-js": "^0.22.12",
        "@types/mocha": "^9.0.0",
        "@types/node": "^16.0.0",
        "@types/nodemailer": "^6.4.4",
        "@types/passport-local": "^1.0.34",
        "@types/supertest": "^2.0.11",
        "@typescript-eslint/eslint-plugin": "^5.0.0",
        "@typescript-eslint/parser": "^5.0.0",
        "chai": "^4.3.4",
        "eslint": "^8.0.1",
        "eslint-config-prettier": "^8.3.0",
        "eslint-plugin-prettier": "^4.0.0",
        "jest": "^27.2.5",
        "mocha": "^8.4.0",
        "mongodb-memory-server": "^8.0.2",
        "prettier": "^2.3.2",
        "source-map-support": "^0.5.20",
        "supertest": "^6.1.3",
        "ts-jest": "^27.0.3",
        "ts-loader": "^9.2.3",
        "ts-mocha": "^8.0.0",
        "ts-node": "^10.0.0",
        "tsconfig-paths": "^3.10.1",
        "typescript": "^4.7.4"
    },
```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
> (the Minimum reproduction code repo is not correct, since i cannot show this repo but we must fill one)

If the minimum reproduction doesn't show your error, how are we supposed to know what you're doing to get this error?

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment]
@Stryder91 are you using Docker?

**Comment by Stryder91** [comment]
> @Stryder91 are you using Docker?

No i am not :'(

**Comment by micalevisk** [comment]
if you want to use v8, install v8 instead (`npm i @nestjs/common@8` and so on). If that package is located under `node_modules`, I don't see any reason to get that 'module not found' error. Sounds pretty much an issue with your environment.

Try creating a brand new nestjs project again (`npx @nestjs/cli new app-v9`).

As you haven't any repro to share, we couldn't help you with that.

You can go to our [Discord](https://discord.gg/nestjs) to discuss this further.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
