### ISSUE TITLE
Assigning enum as a value from outside nestjs app causes ts error

### ISSUE THREAD

**Issue by jacobdo2** [nestjs/nest#10292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have the following project structure (turborepo):
```
 apps/
  api/ (nestjs app)
  web/ (frontend app)
packages
 types/ (to be shared across api and web in apps)
```

When I import an enum from `types` into the `api` application and try to assign it as a value:
```typescript
import { ExampleEnum } from 'types'

const test = ExampleEnum.ONE;
```

I get the following ts error:
```
api:dev: export * from "./src";
api:dev: ^^^^^^
api:dev: 
api:dev: SyntaxError: Unexpected token 'export'
api:dev:     at Object.compileFunction (node:vm:352:18)
api:dev:     at wrapSafe (node:internal/modules/cjs/loader:1032:15)
api:dev:     at Module._compile (node:internal/modules/cjs/loader:1067:27)
api:dev:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
api:dev:     at Module.load (node:internal/modules/cjs/loader:981:32)
api:dev:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
api:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19)
api:dev:     at require (node:internal/modules/cjs/helpers:102:18)
api:dev:     at Object.<anonymous> (/Users/hello/Projects/types-nestjs-nextjs-turbo/apps/api/src/app.controller.ts:2:1)
```

### Minimum reproduction code

https://github.com/jacobdo2/types-nestjs-nextjs-turbo

### Expected behavior

I should be able to assign an enum value to a variable without an error. 

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^8.0.0

### Packages versions

```json
{
"@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"}
```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please share the steps to reproduce your issue.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
