### ISSUE TITLE
@fastify/compress not working

### ISSUE THREAD

**Issue by nhanpiti** [nestjs/nest#10305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![1](https://user-images.githubusercontent.com/3874737/191405816-9b30186f-65fd-427b-9f5b-63187a0e536b.png)

No "Content-Encoding" in Header

Code sample
![2](https://user-images.githubusercontent.com/3874737/191405925-abb97f2b-c300-46b6-bd09-e9cdf3a5ea74.png)

### Minimum reproduction code

[Sample Code](https://github.com/nhanpiti/fastify-compress-nestjs)

### Steps to reproduce

Follow tutorial https://docs.nestjs.com/techniques/compression

### Expected behavior

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding

Content-Encoding: gzip or Content-Encoding: deflate appear in header.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "dependencies": {
    "@fastify/compress": "^6.1.1",
    "@fastify/multipart": "^7.1.1",
    "@fastify/static": "^6.5.0",
    "@mikro-orm/cli": "^5.4.0",
    "@mikro-orm/core": "^5.4.0",
    "@mikro-orm/mariadb": "^5.4.0",
    "@mikro-orm/migrations": "^5.4.0",
    "@mikro-orm/nestjs": "^5.1.1",
    "@mikro-orm/reflection": "^5.4.0",
    "@nestjs/axios": "^0.1.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-fastify": "^9.0.11",
    "@nestjs/swagger": "^6.1.1",
    "cache-manager": "^4.1.0",
    "cache-manager-redis-store": "^2.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "cls-hooked": "^4.2.2",
    "fastify": "^4.6.0",
    "fastify-swagger": "^5.2.0",
    "redis": "3.1.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/cache-manager": "^4.0.2",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "run-script-webpack-plugin": "^0.1.1",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5",
    "webpack": "^5.74.0",
    "webpack-node-externals": "^3.0.0"
  }
}
```

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please share a minimum reproduction project.

**Comment by nhanpiti** [comment]
> Please share a minimum reproduction project.

There is sample code: https://github.com/nhanpiti/fastify-compress-nestjs

http://localhost:3000/swagger-api#/default/AppController_getHello

![3](https://user-images.githubusercontent.com/3874737/191410581-f6892e9e-f83e-4b08-a4af-25afae6f3be8.png)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
