### ISSUE TITLE
Nestjs Microserver RabbitMQ Request Response Jest Testing

### ISSUE THREAD

**Issue by tushar1998** [nestjs/nest#10306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Running multiple test for MessagePattern e2e, results in channel close from Rabbitmq

### Minimum reproduction code

git@github.com:tushar1998/issueReproduce.git

### Steps to reproduce

Clone Repository
`git clone https://github.com/tushar1998/issueReproduce.git`

Checkout Branch 
`git checkout nestjs-rabbitmq-channel`

Install Node Modules
`npm i`

Run e2e test
`npm run test:e2e`

### Expected behavior

Should pass test properly without Throw

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9

### Packages versions

```json
"dependencies": {
    "@nestjs/axios": "0.1.0",
    "@nestjs/common": "9.0.11",
    "@nestjs/config": "2.2.0",
    "@nestjs/core": "9.0.11",
    "@nestjs/event-emitter": "1.3.1",
    "@nestjs/mapped-types": "1.1.0",
    "@nestjs/microservices": "9.0.11",
    "@nestjs/mongoose": "9.2.0",
    "@nestjs/platform-express": "9.0.11",
    "@nestjs/swagger": "6.1.2",
    "@nestjs/terminus": "9.1.1",
    "@types/amqplib": "^0.8.2",
    "amqp-connection-manager": "^4.1.6",
    "amqplib": "^0.10.3",
    "auth0": "2.39.0",
    "aws-sdk": "2.1072.0",
    "axios": "^0.27.2",
    "class-transformer": "0.4.0",
    "class-validator": "0.13.2",
    "cloudinary": "1.29.0",
    "cookies": "0.8.0",
    "cors": "2.8.5",
    "express-jwt": "6.1.1",
    "form-data": "4.0.0",
    "handlebars": "4.7.7",
    "jwks-rsa": "2.0.5",
    "lodash": "4.17.21",
    "migrate-mongo": "8.2.3",
    "mjml": "4.13.0",
    "mock-jwks": "1.0.3",
    "mongodb-memory-server": "8.2.0",
    "mongoose": "6.6.0",
    "nestjs-i18n": "8.2.2",
    "nodemailer": "6.7.8",
    "on-headers": "1.0.2",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.4.0",
    "stripe": "10.2.0",
    "swagger-ui-express": "4.3.0",
    "ts-morph": "13.0.2",
    "ua-parser-js": "1.0.2",
    "url": "0.11.0",
    "uuid": "8.3.2",
    "when": "3.7.8"
  },
  "devDependencies": {
    "@aws-sdk/types": "3.55.0",
    "@nestjs/cli": "9.1.3",
    "@nestjs/schematics": "9.0.3",
    "@nestjs/testing": "9.0.11",
    "@types/auth0": "2.34.13",
    "@types/cookies": "0.7.7",
    "@types/cors": "2.8.12",
    "@types/express": "4.17.13",
    "@types/jest": "27.0.3",
    "@types/jsonwebtoken": "8.5.8",
    "@types/lodash": "4.14.177",
    "@types/node": "16.11.10",
    "@types/nodemailer": "6.4.5",
    "@types/supertest": "2.0.11",
    "@types/uuid": "8.3.3",
    "@typescript-eslint/eslint-plugin": "5.4.0",
    "@typescript-eslint/parser": "5.4.0",
    "eslint": "8.3.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-prettier": "4.0.0",
    "fs-extra": "10.0.0",
    "husky": "7.0.4",
    "istanbul-api": "3.0.0",
    "jest": "27.3.1",
    "jest-html-reporters": "3.0.8",
    "jsonwebtoken": "8.5.1",
    "lint-staged": "12.1.2",
    "prettier": "2.5.0",
    "supertest": "6.2.4",
    "ts-jest": "27.0.7",
    "ts-loader": "9.2.6",
    "ts-node": "10.4.0",
    "tsc-watch": "4.5.0",
    "tsconfig-paths": "3.12.0",
    "tslint": "6.1.3",
    "typescript": "4.5.2"
  },
```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/22202489/191468324-66e3e194-945c-41fc-b9ec-e3d75ad02077.png">

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
