### ISSUE TITLE
ValidationPipe is not a constructor

### ISSUE THREAD

**Issue by PatrickAngrezani** [nestjs/nest#10308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to use class validator, it appears an error in main.ts, follow my code:

`import {ValidationPipe} from '@nestjs/common';
import {NestFactory} from '@nestjs/core';
import {DocumentBuilder, SwaggerModule} from '@nestjs/swagger';
import {AppModule} from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const config = new DocumentBuilder()
  .setTitle('Lama-test API')
  .setDescription('Making an APIREST for Lama')
  .setVersion('1.0')
  .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('swagger', app, document);
  app.useGlobalPipes(new ValidationPipe())

  await app.listen(3000);
}
bootstrap();
`

when I run my api, the following trouble appears::
app.useGlobalPipes(new ValidationPipe())
                     ^
TypeError: common_1.ValidationPipe is not a constructor
    at bootstrap (C:\Users\clemi\Desktop\lama-test\src\main.ts:15:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Minimum reproduction code

https://github.com/PatrickAngrezani/lama-test

### Expected behavior

I hope somebody who already had this trouble help me 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v18.4.0
NPM Version    : 8.12.1 

[Nest CLI]
Nest CLI Version : 9.0.0

[Nest Platform Information]
platform-express version : 9.0.11
mapped-types version     : 1.1.0
schematics version       : 9.0.1
passport version         : 9.0.0
swagger version          : 6.0.5
typeorm version          : 9.0.1
testing version          : 9.0.11
common version           : 9.0.11
config version           : 2.2.0
core version             : 9.0.11
jwt version              : 9.0.0
cli version              : 9.0.0

### Node.js version

8.12.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Your reproduction (once you add in the `app.useGlobalPipes(new ValidationPipe())` works fine.

**Comment by PatrickAngrezani** [comment]
i already made that. Already installed again with default settings, already put @injectable in validation.pipe in @nest/common. But anything works. You can helpme? @jmcdo29

**Comment by jmcdo29** [comment]
The code in your reproduction is, at newest, four days old. It does not reproduce the problem you're reporting, so there's nothing we can do. If you can provide a reproduction that _does_ reproduce the error, I'll reopen the issue

**Comment by PatrickAngrezani** [comment]
@jmcdo29   I'm new in this world, so I dont understand so much. What I can say you is that when I run "npm run start(or :dev)" appears this error 

""app.useGlobalPipes(new ValidationPipe())
^
TypeError: common_1.ValidationPipe is not a constructor
at bootstrap (C:\Users\clemi\Desktop\lama-test\src\main.ts:15:22)
at processTicksAndRejections (node:internal/process/task_queues:95:5)""

If I can pass you more informations I dont know what are then. Can you help me please?

**Comment by jmcdo29** [comment]
@PatrickAngrezani For the **third** time: With the code you've provided **I cannot reproduce that error**. Because of this, I don't know how to help. Please provide code that _does_ reproduce this error

**Comment by PatrickAngrezani** [comment]
my code is that, in main.ts:

import {ValidationPipe} from '@nestjs/common';
import {NestFactory} from '@nestjs/core';
import {DocumentBuilder, SwaggerModule} from '@nestjs/swagger';
import {AppModule} from './app.module';

```
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const config = new DocumentBuilder()
  .setTitle('Lama-test API')
  .setDescription('Making an APIREST for Lama')
  .setVersion('1.0')
  .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('swagger', app, document);

  await app.listen(3000);
}
bootstrap();
```

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
