### ISSUE TITLE
Dependency Injection Issue (Possibly related to #1277)

### ISSUE THREAD

**Issue by vdiaz1130** [nestjs/nest#10304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a Socket.Io Gateway

```
  import { OnModuleInit } from '@nestjs/common';
  import { OnGatewayConnection, OnGatewayDisconnect, WebSocketGateway, WebSocketServer } from '@nestjs/websockets';
  import { Server, Socket } from 'socket.io';
  import { ClientService } from '../client/client.service';


  @WebSocketGateway({ cors: { origin: ['http://localhost:3000', 'http://localhost:4200'] } })
  export class WSGateway implements OnGatewayConnection, OnGatewayDisconnect, OnModuleInit {
    @WebSocketServer()
    server: Server;
    
    constructor(private clientService: ClientService) {
      console.log('1. WSGateway Constructor', this.clientService) // <- Does not execute if I inject into ClientService constructor.
    }
    
    async handleConnection(socket: Socket) {
      console.log('2. WSGateway handleConnection', this.clientService); // <- undefined if I inject into ClientService constructor.
    }

    handleDisconnect(client: any) {
      console.log('3. handleDisconnect');
    }

    onModuleInit() {
      this.server.on('connection', (socket) => {
        console.log(socket.id);
        console.log('connected');
      });
    }
  }

```

Note that I am injecting a service into the constructor `constructor(private clientService: ClientService)`

```
  import { Inject, Injectable } from "@nestjs/common";
  import { REQUEST } from "@nestjs/core";
  import { Request } from 'express';

  @Injectable()
  export class ClientService {
    constructor(@Inject(REQUEST) protected readonly request: Request) {
    // constructor() {
      console.log('ClientService Constructor');
    }
  }
```

Note here that I am injecting REQUEST into the constructor `constructor(@Inject(REQUEST) protected readonly request: Request)`

For some reason, when I inject into this constructor, the constructor in both ` ClientService` and `WSGateway` fail to execute. If I remove the injection both constructors execute.

### Minimum reproduction code

https://github.com/vdiaz1130/nestjs_issue

### Steps to reproduce

1. Clone repo
2. pnpm i
3. pnpm serve
4. Note ClientService constructor does NOT get executed
5. Note WSGateway constructor does NOT get executed
6. Uncomment constructor in ClientService and comment the constructor with DI
7. pnpm serve
8. Note ClientService constructor DOES get executed
5. Note constructor in WSGateway DOES get executed

### Expected behavior

1. Constructors in both ClientService and WSGateway should be executed when service is injected in ClientService constructor.
2. Injected service (ClientService) in WSGateway should not be undefined when `handleConnection` is executed

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

Socket.io

### NestJS version

9.0.11

### Packages versions

```json
"@nestjs/axios": "^0.0.6",
"@nestjs/common": "9.0.11",
"@nestjs/config": "^1.2.0",
"@nestjs/core": "9.0.11",
"@nestjs/jwt": "^8.0.0",
"@nestjs/passport": "^8.2.1",
"@nestjs/platform-express": "9.0.11",
"@nestjs/platform-socket.io": "^9.0.11",
"@nestjs/swagger": "6.0.5",
"@nestjs/websockets": "^9.0.11",
"@nestjs/schematics": "9.0.1",
"@nestjs/testing": "9.0.11",

"socket.io": "^4.5.2",
```

### Node.js version

16.9.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

npm -v 7.21.1
pn -v 7.11.0
node -v v16.9.1

**Comment by jmcdo29** [comment]
Note that our docs explicitly state you can't have a request scoped gateway. By injecting the request into the service that the gateway injects, you make the gateway request scoped.
