### ISSUE TITLE
Nest can't resolve dependencies of the ShopService (ShopRepository, ?). Please make sure that the argument CACHE_MANAGER at index [1] is available in the ShopModule context.

### ISSUE THREAD

**Issue by austinp0wers** [nestjs/nest#10314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`import { CacheModule, Global, Module, CACHE_MANAGER } from '@nestjs/common';
import * as redisStore from 'cache-manager-redis-store';

export const cacheModule = CacheModule.registerAsync({
  useFactory: async () => ({
    store: redisStore,
    host: 'localhost',
    port: process.env.REDISPORT,
    ttl: 0,
    auth_pass: process.env.REDISAUTHPASS,
  }),
});

@Global()
@Module({
  imports: [cacheModule],
})
export class CacheDBModule {}
`

this is my cacheModule 
and this is my app.module

`import { CacheDBModule } from './redisCache.module';
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { AuthModule } from './modules/auth/auth.module';
import { typeORMconfig } from './database/mysql/mysql.typeorm';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigurationModule } from './database/db.module';
import { UserModule } from './modules/user/user.module';
import { ShopModule } from './modules/shop/shop.module';
import { ConfigModule } from '@nestjs/config';
import { ReservationModule } from './modules/reservation/reservation.module';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: '.env',
    }),
    CacheDBModule,
    TypeOrmModule.forRoot(typeORMconfig),
    AuthModule,
    ConfigurationModule,
    UserModule,
    ShopModule,
    ReservationModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
`

i'm curious to find out why it's spitting out the can't resolve dependencies error. 
I've followed the guide from the document below
https://docs.nestjs.com/techniques/caching

the service logic is down below.
this is how i injected the CACHE_MANAGER
`
import { CACHE_MANAGER, Inject, Injectable } from '@nestjs/common';
import { Cache } from 'cache-manager';

export class ShopService {
  constructor(
    private readonly shopRepository: ShopRepository,
    @Inject(CACHE_MANAGER) private cacheManager: Cache,
  ) {}
`
and this is where i was going to use it
`
    async getShopList(shopReqQuery: reqShopList) {
    const shops = await this.cacheManager.get('shops');
`

### Minimum reproduction code

https://github.com/austinp0wers/nestRedisProblem/blob/main/README.md

### Expected behavior

expected to not have errors and successfully get the key from redis Cache.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
    "@nestjs/common": "^8.4.7",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^8.4.7",
    "@nestjs/jwt": "^8.0.1",
    "@nestjs/passport": "^8.2.2",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/swagger": "^5.2.1",
    "@nestjs/typeorm": "^8.0.1",
    "@types/dotenv": "^8.2.0",
    "@types/passport-local": "^1.0.34",
    "@types/zen-observable": "^0.8.3",
    "bcrypt": "^3.0.6",
    "cache-manager": "^4.1.0",
    "cache-manager-redis-store": "^2.0.0",
    "class-validator": "^0.13.2",
    "dotenv": "^16.0.1",
    "error": "^10.4.0",
    "express-basic-auth": "^1.2.1",
    "jsonwebtoken": "^8.5.1",
    "mysql2": "^2.3.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.4.0",
    "typeorm": "^0.3.7"
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Add `exports: [CacheModule]` to your `CacheDBModule`. Your `CacheDBModule` is global, but has no exports and only (currently) internally uses the `CacheModule`, which is not what you intend.

For further support please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by austinp0wers** [comment]
@jmcdo29 Thank you so much for the detailed insights!
