### ISSUE TITLE
Bull jobs silently failed if there is no named processor

### ISSUE THREAD

**Issue by PetrShchukin** [nestjs/nest#10313]
I created a new bug, because it obscures the queue flow. 
If I add a named job "my_job" into the queue "my_queue" and I have the second service watching this queue, if there's no handler for "my_job" it will silently(!) fail the job. Usually when it's done within the same service you get the "Missing process handler for job type" error. I understand that the behavior of failing the job (instead of let's say keeping it in active stage) comes from Bull, but at least it should throw an error.

### Steps to reproduce

1. Add a named job "my_job" into a named queue "my_queue"
2. In the second service create a processor that looks at "my_queue", but does no have the named "my_job" process
3. Execute the code

### Expected behavior

1. Job should remain in the active stage OR an error appear

### Package
"@nestjs/bull": "0.5.5",

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
