### ISSUE TITLE
Dynamically resolved providers can't access REQUEST

### ISSUE THREAD

**Issue by joaquinwojcik** [nestjs/nest#10327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

# Intro and context
We're building a multi-tenant service using Nest.js and we faced some strange behavior (at least to us) with how `moduleRef.resolve` works.

We want to dynamically instantiate a useCase depending on which tenant is making the request.
We identify the tenant with a header (`x-tenant`) on the request.

![image](https://user-images.githubusercontent.com/3205737/192826409-0ba364f6-d483-400c-a0c2-7e0e8c38ec32.png)
_Our tests in app.spec.ts_

------
# How we use moduleRef
Here is our app module, where we are using `moduleRef` to resolve the use case based on the `x-tenant` header.

```
const tenants = {
  '9b7c5221-481d-4c8b-9705-aa9577c04fda': {
    name: 'FakeBBVA',
  },
  'ab92f370-7a75-43da-96e4-0cb8aee4050c': {
    name: 'FakeSantander',
  },
};

@Module({
  imports: [],
  controllers: [AppController],
  providers: [
    SantanderConnector,
    BBVAConnector,
    FakeBBVACreateAccountUseCase,
    FakeSantanderCreateAccountUseCase,
    {
      provide: CreateAccountUseCase,
      useFactory: function (request: Request, moduleRef: ModuleRef) {
        const tenantGuid = request.header('x-tenant');
        const tenant = tenants[tenantGuid].name;
        const tenantUseCase = `${tenant}CreateAccountUseCase`; // E.g FakeSantanderCreateAccountUseCase
        try {
          return moduleRef.resolve(tenantUseCase);
        } catch (e) {
          throw Error('Cant load tenant use case');
        }
      },
      inject: [REQUEST, ModuleRef],
    },
  ],
})
export class AppModule {}
```

------

# Let's do a request and follow it step by step.
For this example we're going to use Santander tenant (`id: ab92f370-7a75-43da-96e4-0cb8aee4050c`)

## Controller
Here everything work as expected. `createAccountUseCase` is resolved correctly and injects `FakeSantanderCreateAccountUseCase`.
```
@Controller()
export class AppController {
  constructor(private readonly createAccountUseCase: CreateAccountUseCase) {}

  @Post('/api/accounts')
  async createAccount(
    @Req() req: Request,
    @Res() res: Response,
  ): Promise<Response> {
    const { name } = req.body;
    const response = await this.createAccountUseCase.execute(name);
    return res.status(201).json(response);
  }
}
```

## FakeSantanderCreateAccountUseCase
Here everything work as expected.

```
@Injectable({ scope: Scope.REQUEST })
export class FakeSantanderCreateAccountUseCase extends CreateAccountUseCase {
  constructor(private connector: SantanderConnector) {
    super();
  }

  async execute(personName: string): Promise<string> {
    return this.connector.createAccount(personName);
  }
}

```

## SantanderConnector
And finally, here is the strange behavior...
```
@Injectable({ scope: Scope.REQUEST })
export class SantanderConnector {
  constructor(@Inject(REQUEST) private req: Request) {}

  createAccount(personName: string): Promise<string> {
    const traceId = this.req.header('x-amzn-trace-id');
    return new Promise((resolve, reject) => {
      if (!traceId) {
        return reject('No trace id');
      }

      // Fake HTTP call here sending trace id...

      return resolve(`Fake santander account created for ${personName}`);
    });
  }
}
```

When we call `this.req.header`  we receive the following error:
```
TypeError: Cannot read property 'header' of undefined
    at SantanderConnector.createAccount (/Volumes/Work/open-source/di-problems-repo/src/connectors/SantanderConnector.ts:10:30)
    at FakeSantanderCreateAccountUseCase.execute (/Volumes/Work/open-source/di-problems-repo/src/use-cases/FakeSantanderCreateAccountUseCase.ts:12:27)
    at AppController.createAccount (/Volumes/Work/open-source/di-problems-repo/src/app.controller.ts:15:54)
    at /Volumes/Work/open-source/di-problems-repo/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /Volumes/Work/open-source/di-problems-repo/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /Volumes/Work/open-source/di-problems-repo/node_modules/@nestjs/core/router/router-proxy.js:9:17
    at /Volumes/Work/open-source/di-problems-repo/node_modules/@nestjs/core/router/router-explorer.js:149:17
```

## Workaround?
If we modify our module definition to always provide `FakeSantanderCreateAccountUseCase` when someone asks for `CreateAccountUseCase` it works just fine.

```
@Module({
  imports: [],
  controllers: [AppController],
  providers: [
    SantanderConnector,
    BBVAConnector,
    FakeBBVACreateAccountUseCase,
    FakeSantanderCreateAccountUseCase,
    {
      provide: CreateAccountUseCase,
      useClass: FakeSantanderCreateAccountUseCase,
    },
  ],
})
export class AppModule {}
```

# Analysis and outro
We think that the issue is inside `moduleRef.resolve`. It can correctly resolve the provider, but if this provider has a "request scoped dependency" then we receive this error.

This is very strange as well, because the dependency couldn't be resolved but the class is instantiated.

### Minimum reproduction code

https://github.com/joaquinwojcik/nest-di-problems

### Steps to reproduce

1. Clone the repo.
```
git clone https://github.com/joaquinwojcik/nest-di-problems.git
```

2. Run yarn
```
yarn
```

3. Run tests.
```
yarn test
```

4. See error `TypeError: Cannot read property 'header' of undefined` in **test santander**

5. Replace `app module providers` with this: (only changes provider for `CreateAccountUseCase`)
```
providers: [
    SantanderConnector,
    BBVAConnector,
    FakeBBVACreateAccountUseCase,
    FakeSantanderCreateAccountUseCase,
    {
      provide: CreateAccountUseCase,
      useClass: FakeSantanderCreateAccountUseCase,
    },
 ],
```

6. Run tests again.
```
yarn test
```

7. **test santander** passes. **test bbva** will fail because we're always injecting santander use case.

### Expected behavior

We expect to be able to resolve providers dynamically.
We expect to receive `REQUEST` in our dynamically resolved providers.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/3205737/192839635-5634f12f-4c68-4adf-9885-b0b5b85305e3.png">

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.6.15

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^7.6.15",
    "@nestjs/core": "^7.6.15",
    "@nestjs/platform-express": "^7.6.15",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.6"
  },
"devDependencies": {
    "@nestjs/cli": "^7.6.0",
    "@nestjs/schematics": "^7.3.0",
    "@nestjs/testing": "^7.6.15",
    "@types/express": "^4.17.11",
    "@types/jest": "^26.0.22",
    "@types/node": "^14.14.36",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "jest": "^26.6.3",
    "prettier": "^2.2.1",
    "supertest": "^6.1.3",
    "ts-jest": "^26.5.4",
    "ts-loader": "^8.0.18",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.2.3"
  },
```

### Node.js version

14.18.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
You need to make sure to provide the [`contextId` aka the Sub-Tree Id](https://docs.nestjs.com/fundamentals/module-ref#getting-current-sub-tree) so you get the current instance. Otherwise, `resolve` will only find the provider itself and not the one for the current request (i.e. the one where `request` is not-null). See the diff below

```diff
diff --git a/src/app.module.ts b/src/app.module.ts
index b967d10..053b827 100644
--- a/src/app.module.ts
+++ b/src/app.module.ts
@@ -2,7 +2,7 @@ import { Module } from '@nestjs/common';
 import { AppController } from './app.controller';
 import { CreateAccountUseCase } from './use-cases/CreateAccountUseCase';
 import { Request } from 'express';
-import { ModuleRef, REQUEST } from '@nestjs/core';
+import { ContextIdFactory, ModuleRef, REQUEST } from '@nestjs/core';
 import { FakeBBVACreateAccountUseCase } from './use-cases/FakeBBVA.CreateAccountUseCase';
 import { FakeSantanderCreateAccountUseCase } from './use-cases/FakeSantanderCreateAccountUseCase';
 import { SantanderConnector } from './connectors/SantanderConnector';
@@ -35,8 +35,9 @@ const tenants = {
         const tenantGuid = request.header('x-tenant');
         const tenant = tenants[tenantGuid].name;
         const tenantUseCase = `${tenant}CreateAccountUseCase`;
+        const subTreeId = ContextIdFactory.getByRequest(request);
         try {
-          return moduleRef.resolve(tenantUseCase);
+          return moduleRef.resolve(tenantUseCase, subTreeId);
         } catch (e) {
           throw Error('Cant load tenant use case');
         }
```

**Comment by joaquinwojcik** [comment]
It worked! Thanks @jmcdo29
