### ISSUE TITLE
Add support for JSON format in LoggerService

### ISSUE THREAD

**Issue by MiniMarker** [nestjs/nest#10342]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not related to a problem

### Describe the solution you'd like

When instantiating a new LoggerService, a new option property for format can be added. Based on the setting either an ConsoleLogger or possibly a new JsonConsoleLogger will be used. 

the resulting log message would be splitted up into an object looking like this:

```
{
  "pid": 1,
  "timestamp": "XXX",
  "level": "info",
  "message": "hello",
  ...otherProps
}
```

### Teachability, documentation, adoption, migration strategy

No migration neccesary, since regular text logger should be default

### What is the motivation / use case for changing the behavior?

External log collection tools (like elasticsearch) have the ability to parse objects and split them into separate data rows for better filtration and querying.

**Comment by MiniMarker** [comment]
I can contribute with an implementation if feature request is ok 😸

**Comment by kamilmysliwiec** [comment]
> I can contribute with an implementation if feature request is ok 😸

That would be great! PRs are more than welcome

**Comment by MiniMarker** [comment]
For future questions, which channel in discord is most suitable for questions related to core nest features?

**Comment by Tony133** [comment]
> For future questions, which channel in discord is most suitable for questions related to core nest features?

Hi @MiniMarker  use nestjs forum (see screenshot) that what regarding NestJS framework topics such as core, cli, express, fastify, etc.

<img width="224" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/193543512-49f94d6e-1168-43b1-954d-8edd8142d3e0.png">

**Comment by MiniMarker** [comment]
Hi @armujahid great job!

One small detail is the naming of the keys which can be shortened a bit?

```
pidMessage -> pid
contextMessage -> context
output -> message
```

Also what do you do with optional context objects provided as the second parameter in the log functions?

**Comment by armujahid** [comment]
@MiniMarker yes I will use short keys in final implementation.
> Also what do you do with optional context objects provided as the second parameter in the log functions?

I didn't changed context behavior so it will propagate as it is via 2nd string argument or via global setting of context via constructor.
```
logger.error('Hello world', "2nd string argument");

{"pid":"16973","timestamp":"10/06/2022, 10:56:03 AM","logLevel":"error","context":"\u001b[38;5;3m[2nd string argument] \u001b[39m","message":"Hello world","timestampDiff":""}
```

**Comment by kamilmysliwiec** [comment]
Thanks for sharing @armujahid!

**Comment by MiniMarker** [comment]
@armujahid have you finished the final implementation? I can't find the pull request for the json logger
