### ISSUE TITLE
MQTT microservice published QOS 2 tagged messages as QOS 0

### ISSUE THREAD

**Issue by ChristiaanWillemsen** [nestjs/nest#10341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Creating a record with QOS 2 sending it out and via emit leads to actually sending a QOS 0 message:

```typescript 
const record = new MqttRecordBuilder(event).setQoS(2).build();
this.mqttClient.emit(config.mqttTopic, record);
```

### Minimum reproduction code

http://foo.bar

### Steps to reproduce

1. define a MQTT client in your @Module via  ClientsModule.register
2. inject the client as a ClientProxy in your service
3. call some code to send a message:

```typescript 
const event = {"foo":"bar"}
const record = new MqttRecordBuilder(event).setQoS(2).build();
this.mqttClient.emit(config.mqttTopic, record);
```
Possibly there is one additional thing, I use a serializer to get rid of the default data structure:

```typescript 
{
   serializer: new MQTTDataSerializer()
}
```
```typescript 
export class MQTTDataSerializer implements Serializer {
  serialize(value: any): OutgoingResponse {
    return value.data.data;
  }
}
```

### Expected behavior

I would expect the message to be sent as QOS 2, but it's not.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.11

### Packages versions

```json
    "@nestjs/axios": "^0.1.0",
    "@nestjs/common": "^9.0.11",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.11",
    "@nestjs/microservices": "^9.0.11",
    "@nestjs/platform-express": "^9.0.11",
    "@nestjs/schedule": "^2.1.0",
```

### Node.js version

v16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
What version of mqtt do you use?

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by ChristiaanWillemsen** [comment]
MQTT version 3.1.1
