### ISSUE TITLE
Add @Roles to @nestjs/common

### ISSUE THREAD

**Issue by JAZZ-FROM-HELL** [nestjs/nest#10363]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No

### Describe the solution you'd like

In the [Guards](https://docs.nestjs.com/guards) documentation, a `@Roles()` decorator is suggested as a specific implementation of `@SetMetadata()`

```
import { SetMetadata } from '@nestjs/common';
export const Roles = (...roles: string[]) => SetMetadata('roles', roles);
```

Imo since it is completely generic and probably widely used, it could be added to the `@nestjs/common` core decorators.

### Teachability, documentation, adoption, migration strategy

If added, update the Guards documentation to simply use `@Roles(..)` instead of `@SetMetadata(..)` and remove the implementation.

### What is the motivation / use case for changing the behavior?

Simplified use and documentation.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
