### ISSUE TITLE
Overriding guard doesn't work when testing

### ISSUE THREAD

**Issue by juliengbt** [nestjs/nest#10366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

Overriding a guard with the method below doesn't actually override the guard.

```
testingModule
      .overrideGuard(MyGuard)
      .useValue({ canActivate: () => true })
      .compile();
``` 

### Minimum reproduction code

https://github.com/juliengbt/nestjs-guard-override

### Steps to reproduce

1. npm install
2. npm run test:e2e

### Expected behavior

test should not fail because the guard should be overridden

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-fastify": "^9.1.3",
    "passport": "^0.6.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  }
```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
