### ISSUE TITLE
Use nestjs to handle incoming email on a server

### ISSUE THREAD

**Issue by xegulon** [nestjs/nest#10397]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'd like to use nest for my node application that listens on port 25 and has to handle incoming emails. For now, I use NodeMailer SMTP server like this:

```js
const server = new SMTPServer({
  secure: false,
  authOptional: true,
  onData(stream, _session, callback) {
    simpleParser(stream).then(handleIncomingEmail);

    stream.on('end', () => {
      callback(null, 'Message queued.');
    })
  },
});

server.on("error", err => {
  console.log(`Server error ${err.message}`);
});

server.listen(25);
```
But I'd like to convert it to an idiomatic nest js application (for now it's not even based on nest)

### Describe the solution you'd like

Adding a new `@EmailHandler` and `@EmailData` decorators somewhere  in the application structure.

### Teachability, documentation, adoption, migration strategy

User will be able to use nest as an email receiving application.

### What is the motivation / use case for changing the behavior?

There is not change of behaviour, it is a new functionality.

**Comment by Tony133** [comment]
Hi @xegulon, this topic had been discussed past see here: https://github.com/nestjs/nest/issues/5388
