### ISSUE TITLE
Exception in a Promise crashes the application

### ISSUE THREAD

**Issue by klodoma** [nestjs/nest#10398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

An exception in a Promise crashes the application. 

I just put this in a controller:
```js
    new Promise(() => {
      throw new Error('error');
    }).then(() => {
      console.log('OK');
    });
```
I get in the console the exception, but the application is dead(not responding) anymore. 

![image](https://user-images.githubusercontent.com/944350/195045652-0cf301e5-b1cd-41dd-b88d-b3877138e73d.png)

### Minimum reproduction code

https://github.com/klodoma/nest-bug/blob/master/src/app.controller.ts
https://github.com/klodoma/nest-bug

### Steps to reproduce

1. `yarn install`
2. `yarn start:dev`
3. Open http://localhost:3000/
4. Page Opens
5. Reload the page (application is dead)

### Expected behavior

1. an exception should not kill the app.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Node.js version

v16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by micalevisk** [comment]
that's expected as we have a floating promise.

![image](https://user-images.githubusercontent.com/13461315/195055279-98599d8f-7827-4538-a913-2138aea86a62.png)

do this instead:

```ts
  getHello(): string {
    return new Promise(() => {
      throw new Error('error');
    }).then(() => {
      console.log('OK');
    });
    return this.appService.getHello();
  }
```

**Comment by klodoma** [comment]
Thank you
