### ISSUE TITLE
Nest can't resolve dependencies of the DiscoveryService (?). Please make sure that the argument ModulesContainer at index [0]

### ISSUE THREAD

**Issue by cjayashantha** [nestjs/nest#10396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I was trying to create a reusable npm package from a custom module that will be used in several projects of mine. In that module, one of the service use DiscoveryService (in @nestjs/core). npm package builds successfully and no errors are given.

When I try to use that, I am getting the below error while trying to start the application.

[Nest] 36004  - 10/11/2022, 9:40:19 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the DiscoveryService (?). Please make sure that the argument ModulesContainer at index [0] is available in the DiscoveryModule context.

Potential solutions:
- If ModulesContainer is a provider, is it part of the current DiscoveryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within DiscoveryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })

Error: Nest can't resolve dependencies of the DiscoveryService (?). Please make sure that the argument ModulesContainer at index [0] is available in the DiscoveryModule context.

Potential solutions:
- If ModulesContainer is a provider, is it part of the current DiscoveryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within DiscoveryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })

note : 

In my app.module.ts

I am importing my module (npm package).

I tried below way also, 

providers: [ 
    {
      provide: 'DISCOVERY_SERVICE',
      useFactory: () => {
        return new DiscoveryService(new ModulesContainer());
      },
    },
  ],

### Minimum reproduction code

can-not-share-repo

### Steps to reproduce

create module that use DiscoverySerice in one of the services,

separate it out to another npm package,

add that npm package to package json and import the module in app.module.ts

### Expected behavior

should be loading DiscoveryService

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json

```

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)

**Comment by iamjaredwalters** [comment]
@cjayashantha were you able to solve this? Im in a very similar situation.
