### ISSUE TITLE
ws:// works but wss://localhost:port/ got ‘WebSocket connection to 'wss://localhost:10086/' failed: ‘

### ISSUE THREAD

**Issue by Eddy0Hoang** [nestjs/nest#10401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i can use ws://localhost:port to connect to the nestjs app, but when i try to use wss://, i got the error '_wss://localhost:10086/ failed:_'
i have tested the cert and the key in a express app, both ws:// and wss:// work fine in that,
```
async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    httpsOptions: {
      key: readFileSync('pri.key').toString(),
      cert: readFileSync('pri.crt').toString()
    }
  });
  app.enableCors()
  app.useWebSocketAdapter(new WsAdapter())
  await app.listen(10001);
}
```
is there any configuration else is required to use wss:// in a nestjs app?

### Minimum reproduction code

nothing

### Expected behavior

success to connect to the nestjs app via wss:// protocol

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.4

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-fastify": "^9.1.4",
    "@nestjs/platform-ws": "^9.1.4",
    "@nestjs/websockets": "^9.1.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "webpack": "5"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
```

### Node.js version

14.17.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)

---

Also, if you believe that this is a bug, you should supply some minimum reproduction of it 

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
