### ISSUE TITLE
Incorrect string to objectId cast for graphql scalars in conjunction with validation pipe.

### ISSUE THREAD

**Issue by NikitaChaykin** [nestjs/nest#10402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When adding the transform: true option to the validation pipe, it constantly generates a new objectId after casting from string to objectId via graphql scalar

### Minimum reproduction code

https://github.com/NikitaChaykin/graphql-mongoose-object-id-scalar-issue

### Steps to reproduce

1. yarn --frozen-lockfile in each apps.
2. run graphql queries for 5.13.14 and 6.6.5 versions of mongoose.

### Expected behavior

The expected behavior is equivalent to what was in the mongus version 5.13.14 package.
Expected behavior: we are run graphql query like this
```
query {
      appQuery (input:{ idForCastingToScalar: "5d6ede6a0ba62570afcedd3a" }) {
      id
    }
  }
```
after casting string ("5d6ede6a0ba62570afcedd3a") to objectId via graph scalar we get (new Types.ObjectId("5d6ede6a0ba62570afcedd3a")) no matter what and how many parameters were passed to the validation pipe

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

mongoose

### NestJS version

9.0.0

### Packages versions

```json
    "@nestjs/cli": "^9.0.0",
```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by PetrifiedEye** [comment]
Same:(

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
