### ISSUE TITLE
Fastify Denial of Service (DoS) GHSA-455w-c45v-86rg

### ISSUE THREAD

**Issue by goriunov** [nestjs/nest#10403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Fastify has vulnerabilities and requires an update:

https://security.snyk.io/vuln/SNYK-JS-FASTIFY-3042394

https://github.com/fastify/fastify/security/advisories/GHSA-455w-c45v-86rg

### Minimum reproduction code

Not required

### Expected behavior

Not to have vulnerability :) 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

any

### Packages versions

```json
latest
```

### Node.js version

any

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest/pull/10394

We'll get this merged in as soon as we can.
