### ISSUE TITLE
Dark mode for docs website

### ISSUE THREAD

**Issue by killerdroid99** [nestjs/nest#10413]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Using a chrome extension to view nestjs docs but slow loading is encountered, would be nice if dark mode is built in

### Describe the solution you'd like

system-wide theme which respects user's preferred color-scheme but can be changed with a theme toggle button, 
something like this??
![Screenshot (2)](https://user-images.githubusercontent.com/75910246/196434449-c9b8bab9-58c1-4580-82ed-9cfb9788af11.png)

### Teachability, documentation, adoption, migration strategy

I am pretty sure everyone will like this feature

### What is the motivation / use case for changing the behavior?

Documentation websites these days are implementing dark mode, why not include this in nest as it has a pretty large community and I also read the docs all the time, but its light theme puts so much pressure on eyes

**Comment by micalevisk** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/1138
