### ISSUE TITLE
Exception-Filter ignores exception thown in mongoose-sequence callback

### ISSUE THREAD

**Issue by uragun91** [nestjs/nest#10419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi.

I am using `nestjs` with `mongoose` and `mongoose-sequence` plugin. `mongoose-sequence` allows to increment model fields. Typically it does it automatically when saving model, but it also provides `<model>.setNext()` method to do it manually. This method receives a callback function which have a single argument `error`. Depending on whether it is defined or not we can understand was the operation successfull or not. Here is my usecase:

```ts
(claim as Claim & SequenceDocument).setNext(
  environment.mongooseAutoIncrementCounterName,
  (err: unknown) => {
    if (err) {
      throw new InternalServerErrorException({
        status: 'error',
        message: 'Unable to auto-increment referenceStoreId',
      }, message);
    }
  },
);
```
In case if `err` is defined I am throwing an ordinary `InternalServerErrorException`. By calling `setNext` `mongoose-sequence` performs `save()` under the hood. In my case this method was called on the model which had some required fields, which were missing in its mongodb document. For this reason `save()` method failed with validation errors and this piece of code thrown my `InteralServerErrorException`. 
But the problem is that my exception just crashed the application instead of send it by http. I was thinking that this is a problem with my exception handler, but for testing purposes I just moved exception throwing out of the callback and it worked fine, like expected.

Sorry, I cannot provide reproduction code, in my case it requires mongodb instance.
I suppose that this issue is not related to mongodb or mongoose or even mongoose-sequence plugin, but may be the way nestjs handles errors. 

### Minimum reproduction code

https://example.com/sorry-no-repro-need-mongodb-instance-without-which-it-will-not-work

### Steps to reproduce

1. Setup empty nestjs project.
2. Setup mongoose module with mongoose-sequence plugin (Claim is my model that I operate with):
```ts
import { Module } from '@nestjs/common';
import { getConnectionToken, MongooseModule } from '@nestjs/mongoose';
import { Connection } from 'mongoose';
import AutoIncrementFactory from 'mongoose-sequence';

import { environment } from '../../environments/environment';
import { Claim, CLAIM_SCHEMA } from './claim.entity';

@Module({
  imports: [
    MongooseModule.forFeatureAsync([
      {
        name: Claim.name,
        useFactory: (connection: Connection): unknown => {
          const schema = CLAIM_SCHEMA;

          // eslint-disable-next-line
          // @ts-ignore
          const autoIncrement = AutoIncrementFactory(connection);
          const referenceStoreIdField: keyof Pick<Claim, 'referenceStoreId'> = 'referenceStoreId';

          // @ts-ignore
          schema.plugin(autoIncrement, {
            id: environment.mongooseAutoIncrementCounterName,
            inc_field: referenceStoreIdField,
            start_seq: 13000,
          });

          return schema;
        },
        inject: [getConnectionToken()],
      },
    ]),
    ...
  ],
  controllers: [...],
  providers: [...],
})

class ClaimModule {}
```
3. Somewhere n the service layer call model's `setNext` with the setup I described earlier:
```ts
(claim as Claim & SequenceDocument).setNext(
  environment.mongooseAutoIncrementCounterName,
  (err: unknown) => {
    if (err) {
      throw new InternalServerErrorException({
        status: 'error',
        message: 'Unable to auto-increment referenceStoreId',
      }, message);
    }
  },
);
```

### Expected behavior

Exception information should be transferred through http to client, as always.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

"mongoose": "^6.3.2",    "mongoose-sequence": "^5.3.1"

### NestJS version

^8.0.0

### Packages versions

```json
{
  "name": "aplus",
  "version": "0.0.0",
  "license": "MIT",
  "engines": {
    "node": ">=14 <16"
  },
  "scripts": {
    ...
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "@ant-design/icons-angular": "^13.1.0",
    "@nestjs/axios": "^0.0.7",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mongoose": "^9.0.3",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/terminus": "^8.0.6",
    "@nrwl/angular": "14.0.5",
    "@ui-team/keycloak": "1.1.3",
    "@unlimint/nestjs-app-configurator": "^1.0.1",
    "@unlimint/nestjs-vault-adapter": "^1.0.1",
    "class-transformer": "^0.5.1",
    "keycloak-js": "^10.0.2",
    "mongoose": "^6.3.2",
    "mongoose-paginate-v2": "^1.6.3",
    "mongoose-sequence": "^5.3.1",
    "nest-winston": "^1.6.2",
    "ng-zorro-antd": "^13.2.1",
    "passport": "^0.5.2",
    "passport-jwt": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~7.4.0",
    "tslib": "^2.0.0",
    "uuid": "^8.3.2",
    "winston": "^3.7.2",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.0",
    "@angular-eslint/eslint-plugin": "~13.1.0",
    "@angular-eslint/eslint-plugin-template": "~13.1.0",
    "@angular-eslint/template-parser": "~13.1.0",
    "@angular/cli": "~13.3.0",
    "@angular/compiler-cli": "~13.3.0",
    "@angular/language-service": "~13.3.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@nrwl/cli": "14.0.5",
    "@nrwl/eslint-plugin-nx": "14.0.5",
    "@nrwl/jest": "14.0.5",
    "@nrwl/linter": "14.0.5",
    "@nrwl/nest": "14.0.5",
    "@nrwl/node": "14.0.5",
    "@nrwl/workspace": "14.0.5",
    "@types/jest": "27.4.1",
    "@types/mongoose-sequence": "^3.0.7",
    "@types/node": "16.11.7",
    "@types/passport-jwt": "^3.0.6",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "~5.18.0",
    "@typescript-eslint/parser": "~5.18.0",
    "class-validator": "^0.13.2",
    "eslint": "~8.12.0",
    "eslint-config-prettier": "8.1.0",
    "istanbul-combine": "^0.3.0",
    "jest": "27.5.1",
    "jest-junit": "^13.2.0",
    "jest-preset-angular": "11.1.1",
    "migrate": "^1.8.0",
    "nx": "14.0.5",
    "prettier": "^2.5.1",
    "ts-jest": "27.1.4",
    "ts-node": "^9.1.1",
    "typescript": "~4.6.2",
    "webpack-bundle-analyzer": "4.5.0"
  }
}

```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
> [example.com/sorry-no-repro-need-mongodb-instance-without-which-it-will-not-work](https://example.com/sorry-no-repro-need-mongodb-instance-without-which-it-will-not-work)

Then add a `docker-compose` with mongoose set up :) 

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

More than likely, the callback is being mishandled and the response or "end of request" lifecycle is happening before that error is thrown so it's out of Nest's hands at that point

**Comment by uragun91** [comment]
@jmcdo29 sure. Need time to craft it. Will provided it tomorrow. Thanks for the reply.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
