### ISSUE TITLE
 Nest can't resolve dependencies when two packages reference @nestjs/core 

### ISSUE THREAD

**Issue by ak99372** [nestjs/nest#10414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Creating nest application (via NestFactory) in shared local package (e.g. customBootstrap), while also referencing another @nestjs/core module (e.g RouterModule) from application project results in injector not recognizing dependencies.
Example:
- shared-lib project references NestFactory (e.g customBootstrap)
- app references RouterModule

```
Nest can't resolve dependencies of the RouterModule (?, Symbol(ROUTES)). Please make sure that the argument ModulesContainer at index [0] is available in the RouterModule context.
```

### Minimum reproduction code

https://github.com/ak99372/nestjs-core-issue.git

### Steps to reproduce

1. cd shared
2. npm i
3. npm run build
4. cd ../app
5. npm i
6. npm start

### Expected behavior

Referencing @nestjs/core modules and classes from different packages shouldn't cause injector problems.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{ "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "shared-lib": "file:../shared"
}
```

### Node.js version

16.18.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
you need to move the `@nestjs/core` on the shared lib to the peer deps list instead, due to how nodejs module resolution & javascript works.

In the end, you shouldn't have more than one occurrence non-deduped of `@nestjs/core` when running `npm ls @nestjs/core`

**Comment by ak99372** [comment]
thanks for quick response @micalevisk 
- make sense and I updated the example project to use peer dependency (but it didn't fix the issue)

@jmcdo29 
- as you mentioned this does work in nestjs monorepo (which is where our code originated) but as our project grew we had to separate child applications and shared libraries (and can't hoist nodemodules for other reasons)

**Comment by jmcdo29** [comment]
If you want to discuss this further, we can [continue on Discord](https://discord.gg/nestjs), but as this is not a bug, issues are not the place to keep the discussion going.

**Comment by laurencefass** [comment]
I am only seeing this behaviour in my e2e tests, and my app works fine. Im using the @nest/config module and service to demonstrate that context isn't shared between  e2e test environments and the services that it injects.

My nest monorepo structure:

```
mono-root
  - libs
    - mylib
      - src
        - module and service files
  - apps
    - myapp
    - src
      - main.ts
        - e2e-spec.ts
         - mylib
          - identical module and service files
```

module and service code:

in mylib/src

the module:

```
// config-module.ts
import { Module } from "@nestjs/common";
import { MyConfigService } from "./config-service";
import { ConfigModule } from "@nestjs/config";

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
  ],
  providers: [MyConfigService],
  exports: [MyConfigService],
})
export class MyConfigModule {}

```

and the service

```
//config-service.ts
import { Injectable } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";

@Injectable()
export class MyConfigService {
  constructor(private configService: ConfigService) {
    console.log("MyConfigService", this.configService.get<string>("abcd"));
  }
}

```

my e2e test sits in the same location as my nest app. The console log in MyConfigService outputs undefined importing my module and service from libs but outputs the expected value when i import from the nested folder (relative to the e2e test file). 

```
 config.e2e-spec.ts
import { Test } from "@nestjs/testing";
import { MyConfigModule, MyConfigService } from "@spotlightsportsgroup/nest";
// import { MyConfigModule, MyConfigService } from "./config-test/index";
import { ConfigService, ConfigModule } from "@nestjs/config";

describe("SharedLib", () => {
  let myConfigService: MyConfigService;
  let configService: ConfigService;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [MyConfigModule, ConfigModule.forRoot()],
      providers: [MyConfigService],
    })
      .overrideProvider(ConfigService)
      .useValue({
        get: jest.fn((value) => {
          return "mocked:" + value;
        }),
      })
      .compile();

    myConfigService = moduleRef.get<MyConfigService>(MyConfigService);
    configService = moduleRef.get<ConfigService>(ConfigService);
  });
```
