### ISSUE TITLE
SEARCH HTTP method

### ISSUE THREAD

**Issue by Nisgrak** [nestjs/nest#10420]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to use the SEARCH HTTP method with NestJS but it doesn't have the @Search() decorator as @Get(), @Post(), etc

### Describe the solution you'd like

Create a @Search() decorator for use in the controllers.

### Teachability, documentation, adoption, migration strategy

Same use as the actual HTTP methods decorators.

Express and Fastify already supports it
http://expressjs.com/en/4x/api.html#routing-methods
https://www.fastify.io/docs/latest/Reference/Routes/#routes-options

A PR was sended a long time ago but it doesn't get merged #9465, it doesn't include SEARCH (it is an old WebDav method) but can be as a base to include all the WebDav methods.

### What is the motivation / use case for changing the behavior?

Allow to use the SEARCH HTTP method as the other ones, is a "GET with body" without break any standard.

**Comment by Gustrb** [comment]
I'd be really interested in working on this issue, but I'm quite new to open sourcing and to this project codebase, could someone help me get through it? 😄

**Comment by micalevisk** [comment]
@Gustrb

- https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [Step-by-step guide to contributing on GitHub](https://www.dataschool.io/how-to-contribute-on-github/)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10533
