### ISSUE TITLE
LazyModuleLoader not available in lazily loaded module

### ISSUE THREAD

**Issue by advancingu** [nestjs/nest#10421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Have a lazily loaded module `LazyModule` and a service `LazyService` inside it that itself wants to use `LazyModuleLoader` to load further modules.

Running an application like this fails with an error:
```
Error: Nest can't resolve dependencies of the LazyService (?). Please make sure that the argument LazyModuleLoader at index [0] is available in the LazyModule context.
```

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-1eknf8?file=src/app.module.ts

### Steps to reproduce

1. Run the reproduction code.
2. See error message in console.

### Expected behavior

`LazyModuleLoader` should be usable in services of modules that were lazy loaded.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^9.0.0

### Packages versions

```json
{
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.4.0"
}
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Potentially the same issue as in https://github.com/nestjs/nest/issues/9622.

**Comment by micalevisk** [comment]
you should not have that `LazyService` in a `providers` array of a 'eager' loaded module (`AppModule`) otherwise it won't be lazy-loaded anymore.

**Comment by micalevisk** [comment]
Looks like we can't inject `LazyModuleLoader` in lazy-loaded providers. Not sure if this is the intended behavior tho.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/9622
