### ISSUE TITLE
`nest build` doesn't behave as expected

### ISSUE THREAD

**Issue by sclausen** [nestjs/nest#10425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

1. A newly created project doesn't emit typescript definitions
2. changing `outDir` in `tsconfig.lib.json` from `../../dist/libs/bar` to `./dist` doesn't seem to have any effect

### Minimum reproduction code

https://github.com/sclausen/nestjs-monorepo-bug

### Steps to reproduce

1. Clone the project
2. execute `nest build bar`
3. notice that no `*.d.ts` have been emitted and the `index.js` is not in the configured `outDir` `<projectDir>/libs/bar/dist/index.js`, but still `<projectDir>/dist/libs/bar/index.js`

### Expected behavior

The configured `outDir` in `tsconfig.lib.ts` and the compilerOption `"declaration": true` is respected.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.4

### Packages versions

```
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v18.3.0
NPM Version    : 8.11.0 

[Nest CLI]
Nest CLI Version : 9.1.4 

[Nest Platform Information]
platform-express version : 9.1.4
schematics version       : 9.0.3
testing version          : 9.1.4
common version           : 9.1.4
core version             : 9.1.4
cli version              : 9.1.4
```

### Node.js version

v18.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
