### ISSUE TITLE
Nest graphql not respecting nullable flag

### ISSUE THREAD

**Issue by assertnotnull** [nestjs/nest#10427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My ObjectType User, the phone field is required even though I've set it to be nullable and it gets nullable if I rename the key

[See the video](https://www.loom.com/share/6de4d85951424d01a188bfb8127252c5)

### Minimum reproduction code

none

### Expected behavior

It should respect the nullable flag value

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

nest/graphq

### NestJS version

8.0.0

### Packages versions

```json
"@nestjs/bull": "^0.5.4",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^10.1.3",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mercurius": "^10.1.3",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-fastify": "^8.4.4",
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by assertnotnull** [comment]
My bad, I've noticed I need to pull nullable in the @ ResolveField too
