### ISSUE TITLE
[Docs] Issue with caching documentation

### ISSUE THREAD

**Issue by pavliy** [nestjs/nest#10436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've been playing with CacheInterceptor. Documentation states that TTL should be specified in seconds.
In my case - I'm using default 'memory' store and TTL there is specified in milliseconds.

node-cache also talks about ms: https://github.com/node-cache-manager/node-cache-manager

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/20-cache

### Expected behavior

Documentation should reflect real picture

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.4

### Packages versions

```json
"@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/typeorm": "^9.0.1",
```

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
`cache-manager` v4, what the docs were written for, use a TTL in seconds, and thus is what our documentation reflects. `cache-manager` v5 uses a TTL in milliseconds, and a different store format, and thus is not guaranteed to work the same. There's an open PR (#10370) to allow both versions to work using a TTL in seconds.
