### ISSUE TITLE
Nest build error when upgrading typescript to 4.8.X

### ISSUE THREAD

**Issue by leonard-henriquez** [nestjs/nest#10430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have an error with the `nest build` command when I upgrade typescript from 4.7.4 to 4.8.4 (or any 4.8.X).
Sorry I didn't include a minimum reproduction code. I don't know I to build it because I have no details on where the error comes from.

<img width="601" alt="Capture d’écran 2022-10-21 à 13 47 57" src="https://user-images.githubusercontent.com/30215564/197189036-731dd343-6f8f-4151-bada-9ad919a225b4.png">

<img width="604" alt="Capture d’écran 2022-10-21 à 13 48 33" src="https://user-images.githubusercontent.com/30215564/197189078-363a8925-de35-40bc-826c-c549cce10cba.png">

I noticed the build works again if my remove all my CLI plugins (`@nestjs/swagger/plugin` and `@nestjs/graphql/plugin`).
It looks similar to https://github.com/nestjs/nest-cli/issues/1752 but all my Nest dependencies are at the last available versions.

### Minimum reproduction code

none

### Expected behavior

I would expect `nest build` to succeed

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

typescript

### NestJS version

9.1.4

### Packages versions

```
 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.17.0
NPM Version    : 8.15.0

[Nest CLI]
Nest CLI Version : 9.1.4

[Nest Platform Information]
platform-express version : 9.1.4
schematics version       : 9.0.3
passport version         : 9.0.0
graphql version          : 10.1.3
swagger version          : 6.1.2
testing version          : 9.1.4
apollo version           : 10.1.3
common version           : 9.1.4
config version           : 2.2.0
core version             : 9.1.4
jwt version              : 9.0.0
cli version              : 9.1.4
```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
let's track this here: https://github.com/nestjs/nest-cli/issues/1812
