### ISSUE TITLE
Different router result from context.getHandler()

### ISSUE THREAD

**Issue by joaogl** [nestjs/nest#10446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We have the following:

```
<<< Controller
@Controller('entity')

  @Get('/')
  findAll() {
    return this.service.findAll();
  }

  @Get('/:id')
  findById(@Param('id') id: number) {
    return this.service.findById(id);
  }


<<< AuthorizationGuard

  public async canActivate(context: ExecutionContext): Promise<boolean> {
    console.log(context.getHandler());
  }
```

If I curl the endpoint `localhost/entity/`:
 - I get a list of entities 🆗 
 - Console log says  `[Function: findAll]`🆗 
 
If I curl the endpoint `localhost/entity/2`:
 - I get a single entity 🆗 
 - Console log says  `[Function: findById]`🆗 
 
If I curl the endpoint `localhost/entity/%3f`:
 - I get a list of entities (I guess it's 🆗 ) 
 - Console log says  `[Function: findById]` (If I'm getting a list entities it means it didn't go to findById) 

### Minimum reproduction code

none

### Expected behavior

If I curl the endpoint `localhost/entity/`:
 - I get a list of entities 
 - Console log says  `[Function: findAll]`
 
If I curl the endpoint `localhost/entity/2`:
 - I get a single entity 
 - Console log says  `[Function: findById]`
 
If I curl the endpoint `localhost/entity/%3f`:
 - I get a list of entities 
 - Console log says  `[Function: findAll]` 

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.4

### Packages versions

```json
    "@nestjs/axios": "^0.1.0",
    "@nestjs/common": "^9.0.4",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.4",
    "@nestjs/platform-express": "^9.0.4",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/typeorm": "^9.0.0",
```

### Node.js version

v16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by karthik2265** [comment]
@joaogl I've created a mock of the above here: https://github.com/karthik2265/nestjs-features , checkout the cats-controller findAll and findOne method, the code works as expected, maybe you are missing something , try comparing your code with mine.

**Comment by Marcjazz** [comment]
> 

The issue you're having is route resolver issue.  `%3f` is resolved as a value for  `:id` reason why the context handler log says `[Function: findById]`. 
If you are trying to implement some query option behavior use `?` instead of `/` e.g. `localhost/entity?q=3f`  and retrieve the value with the `@Query(key?:string)` decorator :

```
  @Get('/')
  findAll(@Query() query: string | string[]) {
    console.log(query) // { q: '3f' }
    return this.service.findAll();
  }
```
