### ISSUE TITLE
Nest.js doesn't provide the reason of 'disconnect' in the 'handleDisconnect()'.

### ISSUE THREAD

**Issue by manyfun99** [nestjs/nest#10447]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The native socket.io provides the way to know the reasons of 'disconnect' event by following API.

- https://socket.io/docs/v4/server-socket-instance/#disconnect

```
io.on("connection", (socket) => {
  socket.on("disconnect", (reason) => {
    // ...
  });
});
```
The reason is specifically provided to know whether it was normal disconnection or not such as 'ping timeout'.
* server namespace disconnect
* client namespace disconnect
* server shutting down
* ping timeout
* transport close
* transport error
* parse error
* forced close
* forced server close

But I couldn't find any realted things in the nest.js document and source code.

I need that feature to know wheter the 'disconnect' event was expected or not such as 'shutting down' or 'time out'.

Is there any way to know the reason of 'disconnect' event?

### Describe the solution you'd like

Supporting the 'reason' from the nest.js 'handleDisconnect'.

### Teachability, documentation, adoption, migration strategy

```
  @SubscribeMessage('disconnecting')
  public async handleDisconnect(
    @ConnectedSocket() client: Socket,
    @MessageBody()
    data: {
      reason: string;    // supporting the reason in the data object.
    },
  ) {
```

### What is the motivation / use case for changing the behavior?

I need that feature to know wheter the 'disconnect' event was expected or not such as 'shutting down' or 'time out'.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
