### ISSUE TITLE
lazy loading 3rd party module fails

### ISSUE THREAD

**Issue by timm-stelzer-e-farm** [nestjs/nest#10458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

NestJS fails to lazily inject third-party dependencies. I've tested with both `nest-mongodb` and `@golevelup/nestjs-rabbitmq`, a repro is linked with the former.

Running `start:lazy` fails with:

```
UnknownDependenciesException [Error]: Nest can't resolve dependencies of the DatabaseService (?). Please make sure that the argument fooDb at index [0] is available in the DatabaseModule context.

Potential solutions:
- If fooDb is a provider, is it part of the current DatabaseModule?
- If fooDb is exported from a separate @Module, is that module imported within DatabaseModule?
  @Module({
    imports: [ /* the Module containing fooDb */ ]
  })

    at Injector.lookupComponentInParentModules (/<path>/node_modules/@nestjs/core/injector/injector.js:241:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Minimum reproduction code

https://github.com/timm-stelzer-e-farm/nestjs-dependency-injections-issue

### Steps to reproduce

Given the reproduction repository is cloned somewhere (see above):

```
yarn
docker compose up -d
yarn start:eager
yarn start:lazy
```

### Expected behavior

Eagerly and lazily injecting 3rd party dependencies work.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### NestJS version

9.1.2

### Packages versions

```json
    "devDependencies": {
        "ts-node": "^10.9.1",
        "typescript": "^4.8.4"
    },
    "dependencies": {
        "@nestjs/common": "9.1.2",
        "@nestjs/core": "9.1.2",
        "mongodb": "^4.10.0",
        "nest-mongodb": "^6.4.0",
        "reflect-metadata": "^0.1.13",
        "rxjs": "^7.5.7"
    }

```

### Node.js version

v18.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
