### ISSUE TITLE
request.body is undefined in middleware using fastify

### ISSUE THREAD

**Issue by RezaRahmati** [nestjs/nest#10466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Value of `request.body` in undefined in middleware when using fastify

### Minimum reproduction code

https://github.com/RezaRahmati/nest-fastify-body-issue

### Steps to reproduce

1. npm i
2. npm run start:dev
3. 
```
curl --location --request POST 'http://localhost:3000?p=6' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 5
}'
```
5. expect the console
```
body undefined
query Empty <[Object: null prototype] {}> { p: '6' }
headers {
  'content-type': 'application/json',
  'user-agent': 'PostmanRuntime/7.29.2',
  accept: '*/*',
  'cache-control': 'no-cache',
  'postman-token': 'c5a13389-10b7-40ea-a523-c35d667631a4',
  host: 'localhost:3000',
  'accept-encoding': 'gzip, deflate, br',
  connection: 'keep-alive',
  'content-length': '15'
}
url /?p=6
dto { id: 5 }
```

### Expected behavior

body should have value

This is expected log
```
body  { id: 5 }
query Empty <[Object: null prototype] {}> { p: '6' }
headers {
  'content-type': 'application/json',
  'user-agent': 'PostmanRuntime/7.29.2',
  accept: '*/*',
  'cache-control': 'no-cache',
  'postman-token': 'c5a13389-10b7-40ea-a523-c35d667631a4',
  host: 'localhost:3000',
  'accept-encoding': 'gzip, deflate, br',
  connection: 'keep-alive',
  'content-length': '15'
}
url /?p=6
dto { id: 5 }
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.6 (same in 9.0.5)

### Packages versions

```json
 "dependencies": {
    "@nestjs/common": "^9.1.6",
    "@nestjs/core": "^9.1.6",
    "@nestjs/platform-express": "^9.1.6",
    "@nestjs/platform-fastify": "^9.1.6",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.7"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.1.4",
    "@nestjs/schematics": "^9.0.3",
    "@nestjs/testing": "^9.1.6",
    "@types/express": "^4.17.14",
    "@types/jest": "29.2.0",
    "@types/node": "^18.11.7",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.41.0",
    "@typescript-eslint/parser": "^5.41.0",
    "eslint": "^8.26.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "29.2.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.1",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.4.1",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.8.4"
  },

```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Also as a side would you please guide what should be the types of Request, Response and Next (I read in another thread that Camilo mentioned Request in the middleware is request.raw, but not sure what should be the typing, in the middleware documentation only express types are mentioned)

**Comment by jmcdo29** [comment]
This is due to how `fastify` uses `middie` to create express compatible middleware. Please review closed issues and Fastify's documentation on middleware.

**Comment by RezaRahmati** [comment]
@jmcdo29 would you please link me to a thread about it and how to solve it please

**Comment by jmcdo29** [comment]
> Also as a side would you please guide what should be the types of Request, Response and Next (I read in another thread that Camilo mentioned Request in the middleware is request.raw, but not sure what should be the typing, in the middleware documentation only express types are mentioned)

req: `IncomingMessage`
res: `ServerResponse`
next: `(err?: Error) => void`

**Comment by jmcdo29** [comment]
> how to solve it 

There's nothing to solve, you just don't use a middleware for what you're trying to achieve.

For further support, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by jmcdo29** [comment]
[ref 1](https://github.com/nestjs/nest/issues/9927)
[ref 2](https://github.com/nestjs/nest/issues/9865)
[ref 3](https://github.com/nestjs/nest/issues/9469)
