### ISSUE TITLE
[Documentation] Extract DataSource into a separate file to use `typeorm` migrations

### ISSUE THREAD

**Issue by proohit** [nestjs/nest#10465]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, the documentation just refers to the typeorm cli to use migrations. However, some nestjs specific preparations have to be done in order to use the cli, i.e. extract the `DataSource` into a file where an instance is exported by default.

### Describe the solution you'd like

Something like the following:

```typescript
//dataSource.ts
import { DataSource } from 'typeorm';
import ormconfig from '../ormconfig.json';

const dataSource = new DataSource({
    ...ormconfig,
});

export default dataSource;
```

```typescript
TypeOrmModule.forRootAsync({
  dataSourceFactory: async () => {
    const { default: dataSource } = await import('./dataSource');
    await dataSource.initialize();
    return dataSource;
  },
}),
```
And use the cli with `typeorm-ts-node-commonjs -d dataSource.ts --`

### Teachability, documentation, adoption, migration strategy

see above

### What is the motivation / use case for changing the behavior?

More help and guidance on how to use the typeorm cli in a nestjs project.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
