### ISSUE TITLE
rawBody:true does not work whilst also increasing the request size limit

### ISSUE THREAD

**Issue by louisjrdev** [nestjs/nest#10471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

With an app boostrapped like so:
```typescript
async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    rawBody: true,
  });
  app.use(json({limit: '50mb'}));
  app.use(urlencoded({limit: '50mb'}));
  app.setGlobalPrefix('api');
  await app.listen(3000);
}
bootstrap();
```
and a controller like so:
```typescript
Controller('customerwebhook')
export class CustomerWebhookController {
  constructor(private readonly configService: ConfigService, private readonly customerWebhookService: CustomerWebhookService) {}

  @Post()
  async customerWebhook(
    @Body() payload: XeroWebhookPayload,
    @Req() request: RawBodyRequest<any>,
    @Headers('x-xero-signature') signature: string,
    @Res({ passthrough: true }) response: any,
  ): Promise<void> {
    //handle verification
}
```

I get the issue that the `request` is not actually a raw request, therefore I cannot verify the webhook correctly. This is solved if I remove the two `app.use()` calls in the bootstrap but I require this as my webhook requests can be in excession of 10kb (the default)

Is there a workaround / am I using this wrong, I believe these two things should be able to work in conjunction.

### Minimum reproduction code

https://codesandbox.io/s/cocky-violet-bfj8pw?file=/src/customer-webhook.controller.ts

### Expected behavior

The request should still be a raw request and also the request size limit respected.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "hidden",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/throttler": "^3.1.0",
    "@prisma/client": "^4.5.0",
    "object-sha": "^2.0.7",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "xero-node": "^4.28.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.18.2",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "prisma": "^4.5.0",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.8.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


```

### Node.js version

16.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
cc @tolgap 🤔 I think this might actually be the expected behavior since `rawBody` configures internal express middleware so if someone provides their own implementation, `rawBody` is ignored. Perhaps we should log a warning in this case?

**Comment by tolgap** [comment]
@kamilmysliwiec This is a tricky one 😞 .

The adapter has no idea that the `rawBody` option was passed once we're past the creation of the `NestApplication`.

I can think of multiple solutions.

1. Change the `NestApplicationOptions.bodyParser: boolean` option to `bodyParser: boolean | BodyParserOptions` and introduce a type that can enable/disable `rawBody` and include other body parser options as well
2. Add new functions to the adapters (e.g. `enableRawBody(contentType: string, bodyParserOptions: object)` that we can call via `app.enableRawBody(...)`
3. Both solution 1 and 2 :)

**Comment by kamilmysliwiec** [comment]
Both would be amazing @tolgap 🙌

**Comment by Gustrb** [comment]
I'm really interested in tackling this issue, but I'm new to open sourcing, could somebody give some guideance on how to solve it?

**Comment by louisjrdev** [comment]
So I have actually managed to work around this like so:
```typescript
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { json, urlencoded } from "express";
import { getBodyParserOptions } from "@nestjs/platform-express/adapters/utils/get-body-parser-options.util";

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {bodyParser: false});

  app.use(json(getBodyParserOptions(true, { limit: '50mb'})));
  app.use(urlencoded(getBodyParserOptions(true, { limit: '50mb'})));
  app.setGlobalPrefix('api');
  await app.listen(3000);
}
bootstrap();

```

**Comment by adamwdennis** [comment]
I'm experiencing the same issue, using the [@golevelup/nestjs-stripe](https://github.com/golevelup/nestjs/tree/master/packages/stripe) package, and following their [instructions on raw request body handling](https://github.com/golevelup/nestjs/tree/master/packages/stripe#%EF%B8%8F-configure-raw-request-body-handling).

In local dev, everything works without having to follow the workaround in this thread -- I only get this problem in production.

**It's almost as though setting `bodyParser: false` is ignored in production.**

```log
2022-11-17T01:25:16.420745776Z [Nest] 1  - 11/17/2022, 1:25:16 AM   ERROR [ExceptionsHandler] No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
2022-11-17T01:25:16.420990732Z Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
2022-11-17T01:25:16.421014713Z     at validateComputedSignature (/app/node_modules/stripe/lib/Webhooks.js:208:11)
2022-11-17T01:25:16.421019885Z     at Object.verifyHeader (/app/node_modules/stripe/lib/Webhooks.js:103:5)
2022-11-17T01:25:16.421023748Z     at Object.constructEvent (/app/node_modules/stripe/lib/Webhooks.js:10:20)
2022-11-17T01:25:16.421027513Z     at StripePayloadService.tryHydratePayload (/app/node_modules/@golevelup/nestjs-stripe/lib/stripe.payload.service.js:28:43)
2022-11-17T01:25:16.421031307Z     at StripeWebhookController.handleWebhook (/app/node_modules/@golevelup/nestjs-stripe/lib/stripe.webhook.controller.js:34:49)
2022-11-17T01:25:16.421035074Z     at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
2022-11-17T01:25:16.421038583Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-11-17T01:25:16.421042223Z     at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
2022-11-17T01:25:16.421045910Z     at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by Karman40** [comment]
@kamilmysliwiec I updated my app to the latest version, but the error still persists. Could you help me why?

**Comment by tolgap** [comment]
@Karman40 what does your application bootstrap (`main.ts`) look like? We have tests in place that check against this functionality.

**Comment by Karman40** [comment]
@tolgap 
```
async function bootstrap() {
  const httpsOptions = process.env?.HTTPS === 'true' ? {
    key: readFileSync(join(process.cwd(), 'ssl.key')),
    cert: readFileSync(join(process.cwd(), 'ssl.crt')),
  } : undefined;

  const app = await NestFactory.create(AppModule, { httpsOptions, rawBody: true });
  const configService = app.get(ConfigService);

  app.setGlobalPrefix(configService.get<string>('globalPrefix'));
  app.enableCors(configService.get('CORS'));

  app.useGlobalPipes(new ValidationPipe({ transform: true, forbidUnknownValues: false }));
  useContainer(app.select(AppModule), { fallbackOnErrors: true });
  app.useWebSocketAdapter(new SocketIoAdapter(app));

  // RAW BODY alaways undefined, but limit works good
  app.use(json({ limit: configService.get<string>('LIMIT') }));
  app.use(urlencoded({ limit: configService.get<string>('LIMIT'), extended: true }))

  await app.listen(configService.get<number>('PORT') || 3000, configService.get<string>('HOSTNAME') || '0.0.0.0');

  if (module.hot) {
    module.hot.accept();
    module.hot.dispose(() => app.close());
  }
}
```

If I use the following code instead of `app.use(json({ limit: configService.get<string>('LIMIT') }));`, the problem is solved (also for old versions):
```
  app.use((req, res, next) => {
    if (req.path.indexOf('/api/stripe/webhook') === 0) next();
    else json({ limit: configService.get<string>('LIMIT') })(req, res, next);
  });
```

**Comment by tolgap** [comment]
@Karman40 you're not using the newly added functions that fixes this issue.

```ts
const app = await NestFactory.create<NestExpressApplication>(AppModule, { httpsOptions, rawBody: true });
const configService = app.get(ConfigService);

// ...

const parserLimit = configService.get<string>('LIMIT');
app.useBodyParser('json', { limit: parserLimit });
app.useBodyParser('urlencoded', { limit: parserLimit, extended: true })

// ... reset of code like `await app.listen()`.
```

**Comment by Karman40** [comment]
@tolgap thanks for your help, it works.
I misinterpreted something, I thought the previous code would also work after the ew release.

**Comment by marcalj** [comment]
I'm using NestJS v9.3.9 and I'm getting errors about using this new function:

```bash
$ npm run build

> otps-backend@0.0.1 prebuild
> rimraf dist


> otps-backend@0.0.1 build
> nest build

src/main.ts:34:7 - error TS2339: Property 'useBodyParser' does not exist on type 'INestApplication'.

34   app.useBodyParser('json', { limit: '50mb' });
         ~~~~~~~~~~~~~
src/main.ts:35:7 - error TS2339: Property 'useBodyParser' does not exist on type 'INestApplication'.

35   app.useBodyParser('urlencoded', { limit: '50mb', extended: true });
         ~~~~~~~~~~~~~

Found 2 error(s).
```

```
[System Information]
OS Version     : Linux 5.15
NodeJS Version : v18.14.1
NPM Version    : 9.5.0

[Nest CLI]
Nest CLI Version : 9.2.0

[Nest Platform Information]
platform-express version : 9.3.9
mapped-types version     : 1.2.2
platform-ws version      : 9.3.9
websockets version       : 9.3.9
schematics version       : 9.0.4
throttler version        : 3.1.0
passport version         : 9.0.3
schedule version         : 2.2.0
terminus version         : 9.2.1
testing version          : 9.3.9
common version           : 9.3.9
axios version            : 1.0.1
core version             : 9.3.9
jwt version              : 10.0.2
cli version              : 9.2.0
 version                 : 1.8.1
```

In which NestJS version is available? Thanks!

**Comment by marcalj** [comment]
Had to cast object to compile:

`app.useBodyParser('urlencoded', { limit: '50mb', extended: true } as OptionsUrlencoded);`

**Comment by tolgap** [comment]
No need to cast. The function is generic.

```ts
app.useBodyParser<OptionsUrlencoded>('urlencoded', { limit: '50mb', extended: true })
```

I will update the example above to show this.

**Comment by marcalj** [comment]
Thanks Tolga! ❤️

**Comment by shawncao** [comment]
it doesn't seem there is a method `useBodyParser` in the latest version `9.3.9`, am I missing anything?

**Comment by shawncao** [comment]
> it doesn't seem there is a method `useBodyParser` in the latest version `9.3.9`, am I missing anything?

Oh, have to use `NestExpressApplication`

**Comment by telecare-zeno** [comment]
I also met this issue if I re-define the body size limitation,  
I use nest old version, so just use blow code to do it, then rawBody not work
```
app.use(express.json({ limit: '10mb' }));
``` 

so I upgrade `@nestjs/platform-express` to `9.4.3` for using `useBodyParser`
but rawBody still not work
```javascript
const app = await NestFactory.create<NestExpressApplication>(AppModule, {
  rawBody: true,
  logger: WinstonModule.createLogger({
    instance,
  }),
});
app.useBodyParser('json', { limit: '10mb' });
app.useBodyParser('urlencoded', { limit: '10mb' });
```
if I just remove `app.useBodyParser('json', { limit: '10mb' });`, rawbody work as expect
Does anyone has idea on it?

**Comment by sonickseven** [comment]
> So I have actually managed to work around this like so:
> 
> ```ts
> import { NestFactory } from '@nestjs/core';
> import { AppModule } from './app.module';
> import { json, urlencoded } from "express";
> import { getBodyParserOptions } from "@nestjs/platform-express/adapters/utils/get-body-parser-options.util";
> 
> async function bootstrap() {
>   const app = await NestFactory.create(AppModule, {bodyParser: false});
> 
>   app.use(json(getBodyParserOptions(true, { limit: '50mb'})));
>   app.use(urlencoded(getBodyParserOptions(true, { limit: '50mb'})));
>   app.setGlobalPrefix('api');
>   await app.listen(3000);
> }
> bootstrap();
> ```

It works fine for me, congratulations!!

**Comment by jaunusa** [comment]
Thank you @tolgap, your solution works.

Does anybody know how to get the rawBody when using `form-data`?

**Comment by b4rtaz** [comment]
I found a flexible solution:

```ts
import { RawBodyRequest } from '@nestjs/common';
import { Request, Response } from 'express';
import * as express from 'express';

export interface RawBodyMiddlewareOptions {
  limit: string;
  rawBodyUrls: string[];
}

export function rawBodyMiddleware(options: RawBodyMiddlewareOptions): unknown {
  const rawBodyUrls = new Set(options.rawBodyUrls);

  return express.json({
    ...options,
    verify: (request: RawBodyRequest<Request>, _: Response, buffer: Buffer) => {
      if (rawBodyUrls.has(request.url) && Buffer.isBuffer(buffer)) {
        request.rawBody = Buffer.from(buffer);
      }
      return true;
    }
  });
}
```

Then:

```ts
app.use(
  rawBodyMiddleware({
    limit: '20mb',
    rawBodyUrls: ['/some-url']
  })
);
```

By this the controller that binds `/some-url` has available the `rawBody` property with the buffer.

```ts
@Controller()
export class SomeController {
  @Post('/some-url')
  public async post(@Req() req: RawBodyRequest<Request>, @Res() res: Response) {
```

**Comment by scr4bble** [comment]
Guys, I have just found this thread, wonderful work. Thank you for that.
One last thing: could you please update also https://docs.nestjs.com/faq/raw-body and mention this in the page? It would help immensely as people like me wouldn't be forced to find this github issue and read the whole thread in order to find out how to fix this issue.

**Comment by tolgap** [comment]
@scr4bble What do you think is missing on the docs page?

**Comment by scr4bble** [comment]
The docs should mention that one has to use `app.useBodyParser()` in order to make the rawBody option work in Nest App in case other parsers are used (or if they have some custom options). Basically that you need to use `app.useBodyParser()` instead of `app.use()`.

**Comment by tolgap** [comment]
@scr4bble its right there in the docs you linked yourself? Or are we talking about about specific phrasing here? If you think better words are needed for custom parser settings, feel free to open a PR in nestjs/docs.nestjs.com 👍 .

**Comment by scr4bble** [comment]
You are right. Discard my comments please. I probably misunderstood those sections when reading it first time and I didn't notice those methods are different from what we use. Sorry for not paying better attention.

**Comment by clintonferraz** [comment]
I think @scr4bble has a point here. Although it is mentioned in the docs, there is room for improvement. The section discussing app.useBodyParser() seems to be located below the section on rawBody. Someone (myself included) might overlook it or assume that the sections below are discussing unrelated topics. It would be helpful if there were at least a warning in the same section about the need to replace use with useBodyParser.

**Comment by jimfilippou** [comment]
If you take a look here https://github.com/nestjs/nest/blob/d132bd2cedeb8aa10c560369892fdc85706e40ae/packages/platform-express/interfaces/nest-express-application.interface.ts#L95-L111 you can see that it's possible without importing from `express` when I was using 

```
app.use(json(getBodyParserOptions(true, { limit: '50mb'})));
app.use(urlencoded(getBodyParserOptions(true, { limit: '50mb'})));
```

So what I did is this and it was resolved.
```
app.useBodyParser('json', { limit: '50mb' });
app.useBodyParser('urlencoded', { extended: true, limit: '50mb' });
```
