### ISSUE TITLE
Nest swagger CLI not generating types for response bodies

### ISSUE THREAD

**Issue by MartinSchere** [nestjs/nest#10478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The [CLI plugin](https://docs.nestjs.com/openapi/cli-plugin) for swagger does not generate response bodies, even though the types are known.

Happens with express as well as fastify.

### Minimum reproduction code

https://github.com/MartinSchere/nest-sample

### Steps to reproduce

1. Clone the repository and install following the steps specified in the `README.md`
2. Navigate to `localhost:3000/api`
3. See that there is no response type for the `/` endpoint:

<img width="1596" alt="Screen Shot 2022-10-29 at 11 20 49" src="https://user-images.githubusercontent.com/61954243/198836576-2ef114db-d9a4-4979-8e6d-25e7b2e0143b.png">

### Expected behavior

According to the [documentation](https://docs.nestjs.com/openapi/cli-plugin):

> add a response decorator to every endpoint with a proper status and type (response model)

The plugin should generate the `type` for the response. In the example provided above, it should have:

```ts
{ message: string; someProp: number }
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

9.0.0

### Packages versions

```
[System Information]
OS Version: macOS Monterey
NodeJS Version : v16.14.2
YARN Version    : 1.22.19

[Nest CLI]
Nest CLI Version : 9.1.5

[Nest Platform Information]
platform-express version : 9.1.6
schematics version       : 9.0.3
swagger version          : 6.1.3
testing version          : 9.1.6
common version           : 9.1.6
core version             : 9.1.6
cli version              : 9.1.5
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by GalloaFranco** [comment]
Hi Martin! 👋🏻 . I think that this is not a issue.
Maybe this corresponds to be a question on StackOverflow with nestjs tag. Anyway, I took the time to review your problem and I could see that following the documentation I was able to generate both the schema response and the example without any problem.
Remember that we must create a class that will serve as a model for our response (according to the [documentation](https://docs.nestjs.com/openapi/cli-plugin#:~:text=Please%2C%20note%20that%20your%20filenames%20must%20have%20one%20of%20the%20following%20suffixes%3A%20%5B%27.dto.ts%27%2C%20%27.entity.ts%27%5D%20(e.g.%2C%20create%2Duser.dto.ts)%20in%20order%20to%20be%20analysed%20by%20the%20plugin.)). The plugin will then do the magic for us ✨.

Following your sample repo: 
- I create a `response.dto.ts`(t**he suffix is important**!) file.
```ts
export class ResponseDTO {
  message: string;
  someProp: number;
}
```

- I use that dto in the service.
```ts
import { Injectable } from '@nestjs/common';
import { ResponseDTO } from './response.dto';

@Injectable()
export class AppService {
  makeSample(): Promise<ResponseDTO> {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({
          message: 'Hello World',
          someProp: 123,
        } as ResponseDTO);
      }, 2000);
    });
  }
}
```

And thats it! You can see something like [this](https://i.postimg.cc/63XS4zGZ/Screenshot-2022-10-30-at-23-25-21.png) in swagger UI.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
