### ISSUE TITLE
Keep REPL history after reload

### ISSUE THREAD

**Issue by jellelicht** [nestjs/nest#10476]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The Nest REPL  has support for all the expected REPL navigation facilities: up-arrow, down-arrow, control+R for bck-i-search. 
I reload (=restart) the REPL when any of the underlying files change.
After a reload, the REPL loses all input history, so I can no longer navigate using the previously mentioned up-arrow, down-arrow, control+R, at least until I manually insert the same inputs again.

### Describe the solution you'd like

After reloading a REPL, (optionally) keep track of any previous inputs so these can be navigated to using the up-arrow, down-arrow and control+R.

A configurable persistence location like .bash_history would be a usable solution for my situation.

### Teachability, documentation, adoption, migration strategy

Extension to `@nestjs/core`'s `repl`:
```
export declare function repl(module: Type, opts?: { historyPersistenceFile: string }): Promise<import("repl").REPLServer>;
```

### What is the motivation / use case for changing the behavior?

Principle of least surprise: most other REPL-like systems have (optional) support for having a durable input history.

Self-centered use-case: I like re-running the same 2-to-5 commands on my REPL while prototyping a new feature.

**Comment by micalevisk** [comment]
as the return of `repl` is an instance of [nodejs repl](https://nodejs.org/api/repl.html) this is already feasible:

```js
const replServer = await repl(AppModule)
replServer.setupHistory('.nestjs_repl_history', () => {})
```

I'm not sure if we should bring that to the core :thinking:

**Comment by jellelicht** [comment]
@micalevisk thank you, this is perfect! This can be closed as far as I am concerned.
For anyone else hitting this later, I went with:
```typescript
const replServer = await repl(AppModule)    
replServer.setupHistory('.nestjs_repl_history', (err, _repl) => {
  if (err !== null) {
    console.error(err);
  }
});
```

**Comment by uiii** [comment]
I think you can definitely add this to the documentation, it is quite necessary when run with `--watch` flag

**Comment by micalevisk** [comment]
@uiii that docs mention that `repl()` returns a REPL instance, thus one could figure that out if they know a bit on nodejs 'advanced' stuff.

But feel free to add that to the docs site: https://github.com/nestjs/docs.nestjs.com

---

Also, we won't have this feature in the core: https://github.com/nestjs/nest/pull/10618#issuecomment-1336939220

**Comment by uiii** [comment]
Ah I got it now it is Node.js thing. I thought first you built it up specifically for NestJs.
