### ISSUE TITLE
[@nestjs/typeorm] `UseRepositories` helper function to make typeorm feature imports more explicit

### ISSUE THREAD

**Issue by proohit** [nestjs/nest#10477]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not a problem, but a suggested improvement of the developer experience for the typeorm integration. It is for one cumbersome how to use and not very clear what `TypeOrmModule.forFeature` does.

### Describe the solution you'd like

```ts
//use-repositories.ts

import { TypeOrmModule } from '@nestjs/typeorm';
import { EntityClassOrSchema } from '@nestjs/typeorm/dist/interfaces/entity-class-or-schema.type';

const UseRepositories = (entities?: EntityClassOrSchema[]) =>
  TypeOrmModule.forFeature(entities);

export default UseRepositories;
```

### Teachability, documentation, adoption, migration strategy

Possibly export this in `@nestjs/typeorm` and use it for `imports` in a `@Module`:
```ts
// some-entity.module.ts

@Module({
  imports: [UseRepositories([SomeEntity, SomeOtherEntity])],
  controllers: [SomeEntityController],
  providers: [SomeEntityService],
})
export class SomeEntityModule {}
```

Now repositories for `SomeEntity` and `SomeOtherEntity` can be injected:

```ts
// some-entity.service.ts

@Injectable()
export class SomeEntityService {
  constructor(
    @InjectRepository(SomeEntity)
    private readonly someEntityRepository: Repository<SomeEntity>,
    @InjectRepository(SomeOtherEntity)
    private readonly someOtherEntityRepository: Repository<SomeOtherEntity>,
  ) {}
}
```

### What is the motivation / use case for changing the behavior?

I think the most common use case of `TypeOrmModule.forFeature` is to be able to inject repositories, so I would suggest a helper function to make these imports more explicit.

**Comment by micalevisk** [comment]
you can make the helper function in your side. I don't see any reason to move that to `@nestjs/typeorm`

We could instead improve the doc around `TypeOrmModule.forFeature` to clarify what it does.

**Comment by proohit** [comment]
@micalevisk thanks for your blazingly fast answer :D .

I did it on my side and use it actively, yet still couldn't help but think that this a very common use case, so why not make it a 'standard'. I agree however that this would be an additional point for potential breaking changes, which makes maintainability a little harder.

**Comment by micalevisk** [comment]
> a very common use case

I'm not sure on that. I'm pretty familiar with `.forFeature`. If I have a helper like that I wouldn't know what it does. And `.forFeature` follow a [well-documented convention](https://docs.nestjs.com/fundamentals/dynamic-modules#community-guidelines), so, to me, it's easier to understand it instead of `UseRepositories` (even tho this one has a good name)

Anyway, if you don't want to wait for Kamil's response, go ahead and open a PR at https://github.com/nestjs/typeorm :cat:

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
