### ISSUE TITLE
If Microservices are created with Redis as transporter and services is horizontally scaled (having pods greater than 1) then each instance of service is receiving the message and there is no load balancing

### ISSUE THREAD

**Issue by rajatKumarr** [nestjs/nest#10483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently if my microservice has multiple instance and is created with Redis as Transporter then when client is publishing a message, all instances are receiving the message. So assume if the action is createUser and all instance will listen to the message, they will try to create same user which is not desired at all. So Redis should act as a queue here and not as a publisher and subscriber. Maybe it can be based on bull.js instead of using ioredis directly. 

### Minimum reproduction code

https://github.com/rajatKumarr/nest-example

### Steps to reproduce

1. use `yarn` to install dependencies.
2. use `yarn start:service` in different terminals to start multiple instance of iam service. (run 2-3 instance of service)
3.  use `yarn start:dev` to start gateway
4. hit `localhost:3000/api` to hit the endpoint. 
5. You will see message being received to every instance in the logs and not to the one. 

### Expected behavior

Only one instance should receive the message. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [x] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json

```

### Node.js version

16.16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
