### ISSUE TITLE
Course payment issue - too many redirects

### ISSUE THREAD

**Issue by ungurnicoleta** [nestjs/nest#10485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After I've paid for the course, I've been redirected to a page that wasn't working. The payment was successful and I received the confirmation email, but first I was redirected to this page.

I've uploaded the screenshot below.
<img width="1738" alt="Screenshot 2022-11-01 at 01 11 51" src="https://user-images.githubusercontent.com/32622785/199127148-efeba2e0-57e1-40db-9ef2-d6801d007681.png">

### Minimum reproduction code

https://learn.nestjs.com/after_login?code=Zg9xa3xZuYv2TMsD2ZvxxmciJwFBN3ayRuHRh_Z34pEh7eCObDH4D_bf9ZMeiO_RHhx0ZsoAhiOIn9lqha-ysQ&wizard_id=9r6Jtcg6IelaV3QlemWwr2vhZbhnbaT8tljv4Uv0Vy6e4Esu4NrxpmDD8FzszwbYj3v_gJwJM4QQkF5YsCtDoQ

### Expected behavior

A working redirect page :)

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json

```

### Node.js version

18.8.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Btw I love the product and cats!

**Comment by kamilmysliwiec** [comment]
Please, reach out to us via support@nestjs.com
