### ISSUE TITLE
Nest can't resolve dependencies of the RoleManagementService (?, XmwRoleRepository, XmwPermissionRepository). Please make sure that the argument Sequelize at index [0] is available in the RoleManagementModule context

### ISSUE THREAD

**Issue by Cyan-Xmw** [nestjs/nest#10495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

 I want to use sequelize  transaction,then I do:
![image](https://user-images.githubusercontent.com/40554571/199208515-9cca3d03-b98d-441d-be96-a65d5884907e.png)
![image](https://user-images.githubusercontent.com/40554571/199208572-7b64d375-7659-4149-94b5-e8116337e156.png)
but I dont know how to do in modules :
![image](https://user-images.githubusercontent.com/40554571/199208664-87458083-e513-4834-b2b6-c0ca75ed0dd3.png)
got An error:
![image](https://user-images.githubusercontent.com/40554571/199208779-beca827d-1a6c-4e3d-bb6d-dcc5d5480e0a.png)

What should I do  Thanks

### Minimum reproduction code

https://github.com/Cyan-Xmw/react-umi-xmw/blob/Cyan/Xmw_server/src/modules/system/role-management/role-management.service.ts

### Expected behavior

No Error

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "xmw_sequelize",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/sequelize": "^9.0.0",
    "@nestjs/swagger": "^6.1.2",
    "chalk": "4.1.2",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "lodash": "^4.17.21",
    "log4js": "^6.7.0",
    "moment": "^2.29.4",
    "mysql2": "^2.3.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "sequelize": "^6.25.3",
    "sequelize-typescript": "^2.1.5",
    "stacktrace-js": "^2.0.2",
    "swagger-ui-express": "^4.5.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.0.0",
    "@types/sequelize": "^4.28.14",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


```

### Node.js version

16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)

**Comment by micalevisk** [comment]
btw, read the docs https://docs.nestjs.com/techniques/database#sequelize-integration

![image](https://user-images.githubusercontent.com/13461315/199223518-91b2fb2f-8849-40eb-bf05-42904846b6ce.png)
