### ISSUE TITLE
[nestjs/graphql] Resolver Inheritance 

### ISSUE THREAD

**Issue by michaelwittwer** [nestjs/nest#10498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Executing the following graphQL query fails:
```graphql
query{
  findWarriors{
    id
    level
    resolveFieldOnWarrior
    resolveFieldOnCharacter
  }
}
```

with error message `Cannot return null for non-nullable field Warrior.resolveFieldOnCharacter.` since the field resolver [CharacterResolver.resolveFieldOnCharacter](https://github.com/shiftcode/nestjs-issue-investigation/blob/main/src/graphql/character.resolver.ts#L9) never gets executed and thus value is `null` which is not supported by our definition.

### Minimum reproduction code

https://github.com/shiftcode/nestjs-issue-investigation

### Steps to reproduce

1. `yarn install`
2. `yarn start`

### Expected behavior

Executing the failing graphQL query from above should success. When debugging I see that the code in [CharacterResolver.resolveFieldOnCharacter](https://github.com/shiftcode/nestjs-issue-investigation/blob/main/src/graphql/character.resolver.ts#L9) is never executed and thus the field value is `null` which is not supported by the definition. What I think is strange is that the schema contains the field `resolveFieldOnCharacter` for type `Warrior` but during runtime it fails to execute the field resolver.
What I tried: Let the [WarriorResolver](https://github.com/shiftcode/nestjs-issue-investigation/blob/main/src/graphql/warrior.resolver.ts) extend the [CharacterResolver](https://github.com/shiftcode/nestjs-issue-investigation/blob/main/src/graphql/character.resolver.ts), this solved the issue and is probably how it should be done, but seems confusing to me because of the schema reason.
From the documentation about [inheritance of Resolvers](https://docs.nestjs.com/graphql/resolvers#class-inheritance) it is not clear that I MUST use inheritance to implement the sample use-case, but rather showing how to use inheritance and generics.

If inheritance on the field resolver side is what I should do, the generation of the schema should work the same and not show the field `resolveFieldOnCharacter` for `Warrior` IMO.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

9.1.6

### Packages versions

```json
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.17.0
YARN Version    : 1.22.19 

[Nest CLI]
Nest CLI Version : 9.1.5 

[Nest Platform Information]
platform-express version : 9.1.6
schematics version       : 9.0.3
graphql version          : 10.1.5
testing version          : 9.1.6
common version           : 9.1.6
apollo version           : 10.1.4
core version             : 9.1.6
cli version              : 9.1.5
```

see [package.json](https://github.com/shiftcode/nestjs-issue-investigation/blob/main/package.json) and [yarn.lock](https://github.com/shiftcode/nestjs-issue-investigation/blob/main/yarn.lock) for more version details.

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
