### ISSUE TITLE
csurf has deprecated

### ISSUE THREAD

**Issue by YuanXingH** [nestjs/nest#10496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[scurf](https://github.com/expressjs/csurf#csurf
) has deprecated, if it has alternative CSRF protection package?

### Minimum reproduction code

app.use(csurf());

### Expected behavior

There is a simple and useful library like python flask_wtf.csrf?

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"devDependencies": {
    "@nestjs/cli": "^9.0.0",
}
```

### Node.js version

14.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
