### ISSUE TITLE
How can I use execution context in a custom validator Pipe ?

### ISSUE THREAD

**Issue by NishaUttawani** [nestjs/nest#10503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a custom Validator, where I want to use the execution context. Can you suggest if is it possible to get that ?

### Minimum reproduction code

https://github.com/nestjs

### Expected behavior

Should be able to access the execution context.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by NishaUttawani** [comment]
@kamilmysliwiec Need your help here.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
