### ISSUE TITLE
Use @nestjs/swagger/plugin with babel

### ISSUE THREAD

**Issue by clayrisser** [nestjs/nest#10516]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

How can I use `@nestjs/swagger/plugin` with babel?

### Describe the solution you'd like

I would like a babel plugin that does the same thing as `@nestjs/swagger/plugin`.

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

My setup uses babel instead of tsc or ts-loader.

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
