### ISSUE TITLE
Apply to middleware the same decorator set as Controller endpoints

### ISSUE THREAD

**Issue by JAZZ-FROM-HELL** [nestjs/nest#10517]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

At this point, middleware and in particular guards require low-level boilerplate code to access ExecutionContext, request or handler method metadata.

For example, `RolesGuard` in the [NestJS documentation](https://docs.nestjs.com/guards) currently requires reflector to access handler method roles list and to parse the request in order to obtain the user:

```
  canActivate(context: ExecutionContext): boolean {
    const roles = this.reflector.get<string[]>('roles', context.getHandler());
    if (!roles) {
      return true;
    }
    const request = context.switchToHttp().getRequest();
    const user = request.user;
    return matchRoles(roles, user.roles);
  }
```

### Describe the solution you'd like

I'd like middleware and guards to accept any controller handler decorator set - e.g. `@Request()`, `@Body()`, `@Param()` `@Query()`, different pipes, other guards, custom decorators etc.

For instance in the example above, the guard may accept a decorated `@Request()` parameter just like a Controller method, as well as a `@Handler(..)` reflected param, so that these parameters will be immediately available without needing to do the actual parsing, reflection and so on inside it. Something like this:

````
canActivate(@Request() req, @Handler('roles') roles): boolean {
   return matchRoles(roles, req.user.roles);
}
````

Another example could be in `NestMiddleware.use()` which can be used for instance in an HttpLogger like this, in addition to or instead of a raw request and response:
````
  // @User() is a custom pipe
  use(@User() user, @Handler() handler, next: function) {
     this.logger.log('User ' + user.id + ' accessed ' + handler.name);
      ...
   }
````

This can even allow chaining of middleware. For example conditional authorization may be implemented by adding a guard decorator to any guard that relies on it. For example, a `@RolesGuard()` may be decorated with an `@AuthGuard()`, so that `@AuthGuard()` is always called before it and also it won't require handler methods to call it themselves (and the guarding order will be clearer too, and in some cases might even save some redundant database calls):

````
@Injectable()
@AuthGuard()
export class RolesGuard implements CanActivate {
...
}
````

### Teachability, documentation, adoption, migration strategy

See solution description. It would clearly require some documentation update.

### What is the motivation / use case for changing the behavior?

Ease of use - parsing the `ExecutionContext` or different request components can be a pain and we already have that in the controller, so why not reuse it in the middleware scope?

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
