### ISSUE TITLE
ModuleRef is not found when using Nest.js with a PNPM Mono Repo

### ISSUE THREAD

**Issue by zgriesinger** [nestjs/nest#10519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

# Issue
I have a mono repo where APIs are using a custom healthcheck library re-exported from the HealthCheck examples in the docs here: https://docs.nestjs.com/recipes/terminus

We are consuming this module in various apps. And use `pnpm` with `auto-install-peers=true` set in our `.npmrc`.

We're having a confusing issue where `ModuleRef` is undefined. Since this is a base provider I have no idea how this is happening.

I think it may be due to `pnpm` and how it resolves dependencies but I think in this case it may be functioning correctly and there's a bug in Nest.js.

Is there any known way around it?

I have some more info here in the Readme of the reproduction repo:
https://github.com/zgriesinger/pnpm-nest-mono

### Minimum reproduction code

https://github.com/zgriesinger/pnpm-nest-mono

### Steps to reproduce

```
gh repo clone zgriesinger/pnpm-nest-mono
cd pnpm-nest-mono
pnpm i
pnpm -r build
pnpm -F api start
```

### Expected behavior

The `pnpm run -F api start` command works and the API starts up.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/terminus

### NestJS version

9

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@zg/healthcheck": "workspace:^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },

```

### Node.js version

v16.18.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

<img width="1696" alt="image" src="https://user-images.githubusercontent.com/15172516/200082135-38884d74-5147-4900-b9f3-ad8137183eda.png">

_No response_

**Comment by micalevisk** [comment]
> Since this is a base provider I have no idea how this is happening.

https://docs.nestjs.com/faq/common-errors

![image](https://user-images.githubusercontent.com/13461315/200082954-9a55bc2a-4127-4cb3-8bac-3bcaf3068f0a.png)

**Comment by jmcdo29** [comment]
To get around this, you can install the `@nestjs/*` packages to your workspace root instead of each package and pnpm will use the root `node_modules` when you request those
