### ISSUE TITLE
@Query decorator not validating correctly

### ISSUE THREAD

**Issue by Alvaro948P4Q** [nestjs/nest#10518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

After hours of debugging (and months using NestJS), I have runned out of ideas, and if necesary, I can try to replicate the error, but it would take too much time depending on if I have not missunderstood the error:

Currently I got a controller that list users (a simplified version):

```ts
@Get()
@UseInterceptors(ClassSerializerInterceptor)
async list(
    @Query() filter: UserFilterRequest
): Promise<UserPaginatedResponse> {
    const users: UserEntity[] = await this.service.list();
    return this.userPageResponseCreator.create(users, new UserPaginatedResponse());
}
```

Everything worked fine until I added a `@Query` param with type `UserFilterRequest`:

```ts
export class UserFilterRequest {
    @ApiProperty({ description: 'The user fullname', type: String })
    @IsOptional()
    @IsString()
    public fullname: string = null;
}
```

Other parts of the application have similiar things, but none of them have given any error before. Now, after adding that `@Query` param, the tests (only the tests infact) are throwing `BadRequestException` for every **single endpoint** of the application using `class-validator`, with a bunch validation errors that do not belong to the class of the parameter:

```
BadRequestException: Bad Request Exception
        at ValidationPipe.exceptionFactory (/usr/src/app/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
        at ValidationPipe.transform (/usr/src/app/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at resolveParamValue (/usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:147:23)
        at async Promise.all (index 0)
        at pipesFn (/usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:150:13)
        at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:37:30 {
      response: {
        statusCode: 400,
        message: [
          'id should not be empty',
          'data must be an array',
          'data should not be empty',
          'reader should not be empty',
          'app should not be empty',
          'strip should not be empty',
          'code should not be empty',
          'unit should not be empty',
          'inserting should not be empty',
          'sampling should not be empty',
          'mode should not be empty',
          'mode must be a valid enum value',
          'channel should not be empty',
          'description should not be empty',
          'type should not be empty',
          'manufacturingBatch should not be empty',
          'token should not be empty'
        ],
        error: 'Bad Request'
      },
      status: 400
    } {
      host: ExecutionContextHost {
        args: [ [IncomingMessage], [ServerResponse], [Function: next] ],
        constructorRef: null,
        handler: null,
        contextType: 'http',
        getRequest: [Function: getRequest],
        getResponse: [Function: getResponse],
        getNext: [Function: getNext]
      }
    }
```

Those messages are in fact reporting attributes of other classes (even from other modules) and are using similar `class-validator` decorators injected using `@Query` or `@Body`. Things that I have tested so far:

Removing the `class-validator` decorators from `UserFilterRequest`, solves the issue:

```ts
export class UserFilterRequest {
    @ApiProperty({ description: 'The user fullname', type: String })
    // @IsOptional()
    // @IsString()
    public fullname: string = null;
}
```

Removing the `UserFilterRequest` from the `@Query` param, solves the issue: (however, I assume this would make the param not be serialized)

```ts
@Get()
@UseInterceptors(ClassSerializerInterceptor)
async list(
    @Query() filter //: UserFilterRequest
): Promise<UserPaginatedResponse> {
    const users: UserEntity[] = await this.service.list();

    return this.userPageResponseCreator.create(users, new UserPaginatedResponse());
}
```

So, I have reached the point where I am thinking if this can be caused because of having _too much_ classes on the project and maybe NestJS or `class-validator` is somehow not handling all the classes individually.

Any ideas on how to proceed with the debuging? Thanks!

### Minimum reproduction code

TODO

### Expected behavior

Adding more `@Query` attributes should not make the app to throw `ValidationException` everywhere

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.6

### Packages versions

```
[System Information]
OS Version     : Linux 5.15
NodeJS Version : v16.14.2
NPM Version    : 8.15.1 

[Nest CLI]
Nest CLI Version : 9.1.5 

[Nest Platform Information]
platform-socket.io version : 9.1.6
platform-express version   : 9.1.6
websockets version         : 9.1.6
schematics version         : 9.0.3
throttler version          : 3.1.0
passport version           : 9.0.0
schedule version           : 2.1.0
terminus version           : 9.1.2
swagger version            : 6.1.3
typeorm version            : 9.0.1
testing version            : 9.1.6
common version             : 9.1.6
config version             : 2.2.0
axios version              : 0.1.0
core version               : 9.1.6
jwt version                : 9.0.0
cli version                : 9.1.5
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Also, validation pipes are enabled:

```ts
app.useGlobalPipes(new ValidationPipe({ transform: true }));
```

**Comment by micalevisk** [comment]
How's the request you're sending? can you show us the client-side code on that.

Is it with the `content-type: application/json` header?

**Comment by Alvaro948P4Q** [comment]
Hi @micalevisk, yes it is `content-type: application/json`

![image](https://user-images.githubusercontent.com/97282850/199983900-71f83ede-2b94-498f-b0dd-4b56ebb14cd6.png)

An this would be a minimal version of the test:

```ts

const moduleFixture: TestingModule = await Test.createTestingModule({
    imports: [AppModule]
}).compile();

await moduleFixture.init();
const app: INestApplication = moduleFixture.createNestApplication();
const http = agent(app.getHttpServer());
        
describe('List users', () => {
    it('Should list users', async () => {
        const response = await http.get(`/users`).expect(HttpStatus.OK);
    });
});
```

**Comment by micalevisk** [comment]
what's the result of the test?

Also, can you show the response body for that request?

**Comment by Alvaro948P4Q** [comment]
Hi @micalevisk,

The test, and any other test that points to an endpoint that tries to map query params, or body (json) into a class (that have `class-validator`) is not returing HTTP 400 due to the BadRequestException of the `ValidationPipe`.

Note that all the endpoints have started to fail after adding this `UserFilterRequest` class, if I remove it, everything works perfectly (even if I only remove the `@Is*` decorators from this class in particular).

**Comment by micalevisk** [comment]
what if you remove the `@UseInterceptors(ClassSerializerInterceptor)`

**Comment by Alvaro948P4Q** [comment]
Hi @micalevisk ,

Sorry for the late answer and BTW thanks for your assistance. I have remove the `@UseInterceptors(ClassSerializerInterceptor)`, but the test keeps failing.

**Comment by micalevisk** [comment]
So I guess we couldn't help much without any code that reproduces your issue.

Maybe some another thing is being running before reaching the controller.

I'll close this until you share some repro.

You can use our [Discord](https://discord.gg/nestjs)

**Comment by micalevisk** [comment]
@Alvaro948P4Q you could also add me as a outside collaborator to your private repo btw 🙂
