### ISSUE TITLE
Apollo Server 4 - fastify 4 support

### ISSUE THREAD

**Issue by jani888** [nestjs/nest#10514]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have an issue when I try to use fastify 4 with apollo server, it does not work, because the apollo server v3 only supports fastify 3

### Describe the solution you'd like

Apollo Server 4 changed how integrations with web servers work, and there is a [fastify integration](https://www.npmjs.com/package/@as-integrations/fastify) which supports fastify v4.

Is it possible to make this work with nestjs?

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

-

**Comment by kamilmysliwiec** [comment]
Duplicate https://github.com/nestjs/graphql/issues/2445
