### ISSUE TITLE
Change status code dynamically in a platform-agnostic way

### ISSUE THREAD

**Issue by Thore1954** [nestjs/nest#10525]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently the only way to dynamically change the status code in route handlers is to use a library-specific response with the `passthrough` option which makes it hard to switch between Express and Fastify.

### Describe the solution you'd like

Instead you can allow us to return an object from the route handler method with the shape (similarly to redirection):
```ts
{
  "data": any,
  "statusCode": number
}
```
Of course this would be a massive breaking change, instead you can introduce a wrapper class (similarly to `StreamableFile`) which we can return from the route handler method.

### Teachability, documentation, adoption, migration strategy

TBD

### What is the motivation / use case for changing the behavior?

Cross-platform support.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
