### ISSUE TITLE
Get list of implemented routes and their versions

### ISSUE THREAD

**Issue by milosdakic** [nestjs/nest#10529]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a need to throw specific errors for routes that don't have a version implemented. eg. request for v2 route but v1 only exists, return specific error rather than generic route not found.

It seems that the internal `RouteResolver` already does most of this via `registerRouters` — https://github.com/nestjs/nest/blob/master/packages/core/router/routes-resolver.ts#L81-L137

Would need a way to expose this structure (rather than just logging it out) via the request.

### Describe the solution you'd like

A way to get a list of implemented routes on a running application. Similar to https://www.npmjs.com/package/express-list-routes but along with decorator data such as versions.

### Teachability, documentation, adoption, migration strategy

We can expand the Request object or similar to document functionality that may be built around this.

### What is the motivation / use case for changing the behavior?

I'm working on a project that requires pretty strict version control/management. Without handling reference maps for this, we would be able to do this via code as all routes are already decorated with versions.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/5141
