### ISSUE TITLE
Add utility method to get the websocket pattern

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#10520]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Right now, the only way to get the current pattern being triggered for a websocket request is to do so via reflection and reading the metadata set by the `@SubscribeMessage()` decorator, which is okay for an interceptor, but unusable in a filter as there is no `ExecutionContext#getClass()` or `ExecutionContext#getHandler()` in filters.

### Describe the solution you'd like

Just like the RPC contexts have specific helper methods added to their `ArgumentsHost#switchToHrpc().getClient()` result to get the current pattern (e.g. MQTT -> `getTopic()`, NATS -> `getSubject()`, etc) it would be helpful for the `ArgumentsHost#switchToWs().getClient()` had a utility method to get the current message pattern. Maybe specifically `getPattern()`?

### Teachability, documentation, adoption, migration strategy

We can mention it in the docs on either the `exception filters`, `guards`, or `interceptors` page, or create a new page about the `WsExecutionContext` so that it's better documented. Adoption would be by those who are building something like I am. No migration strat needed, it should theoretically be a non-breaking change.

### What is the motivation / use case for changing the behavior?

I'm working on improving functionality for [ogma](https://github.com/jmcdo29/ogma) so that it can log exceptions from the filter that aren't previously logged via its interceptor. HTTP, GQL, and RPC, this is all doable with minor modifications I'm just stuck on the implementation for WS because of the lack of ability to get this value. It would be possible with custom ws and socket.io adapters that bind middleware, but it would be much nicer to not have to have devs use anything other than what my package provides.

**Comment by kamilmysliwiec** [comment]
Sounds like a useful enhancement. Would you like to work on this feature @jmcdo29?

**Comment by jmcdo29** [comment]
I'll need some insight in where the contract gets created on request, but one I have that I think I should be okay

**Comment by jmcdo29** [comment]
I think I got something working. @kamilmysliwiec we don't bind an exception filter for invalid events like we do the 404 handler in HTTP, right?

**Comment by kamilmysliwiec** [comment]
> @kamilmysliwiec we don't bind an exception filter for invalid events like we do the 404 handler in HTTP, right?

Could you clarify what you mean by _invalid events_? 🤔 Emitting events for which there are no corresponding handlers?

**Comment by my-random-username** [comment]
nestjs discord channel is dead. it seems its full of fake online accounts

**Comment by jmcdo29** [comment]
> > @kamilmysliwiec we don't bind an exception filter for invalid events like we do the 404 handler in HTTP, right?
> 
> Emitting events for which there are no corresponding handlers? If so, yes, we do not

Correct, events for which there are no `@SubscribeMessage()` handlers

**Comment by kamilmysliwiec** [comment]
Let's track this issue here https://github.com/nestjs/nest/pull/10545 🙌
