### ISSUE TITLE
Tests timeouts on 9.20

### ISSUE THREAD

**Issue by Tirke** [nestjs/nest#10547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When bumping everything to the latest release, some simple tests we have started timing out.

@nestjs/common@9.1.6-->9.2.0
@nestjs/core@9.1.6-->9.2.0
@nestjs/mongoose@9.2.0-->9.2.1
@nestjs/platform-fastify@9.1.6-->9.2.0

I've isolated the issue to just bumping @nestjs/core@9.1.6-->9.2.0 if I bump the other packages tests will still pass.

### Minimum reproduction code

https://github.com/Tirke/nest-core-bug

### Steps to reproduce

In the repro repo run the test, it will hang for more than 5sec so Jest will kill it.
Downgrade `@nestjs/core`  to `9.1.6` and run the test again, it will finish.

### Expected behavior

Tests can finish.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```json
 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS Monterey
NodeJS Version : v18.10.0
PNPM Version    : 7.9.5

[Nest CLI]
Nest CLI Version : 9.1.5

[Nest Platform Information]
platform-fastify version : 9.2.0
schematics version       : 9.0.3
testing version          : 9.2.0
common version           : 9.2.0
core version             : 9.2.0
cli version              : 9.1.5
```

### Node.js version

v18.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Your `AppController#submitCode` injects `@Res()` but never calls `res.send()` so the response never makes it to the test and the test timesout waiting. Either  add `{ passthrough:  true }` to `@Res()` to tell nest to send the response, or send the response yourself.
