### ISSUE TITLE
Un-Awaited Promises - Exceptions Not Caught

### ISSUE THREAD

**Issue by JordanTreDaniel** [nestjs/nest#10542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- If I am serving a request through a controller and I call service,
- that service calls an async function which throws an error, not using the key word await
- if the called async function fails, the entire app will fail. Despite having built an exception handling by nest, and also implementing a custom exception filter.

### Minimum reproduction code

https://codesandbox.io/s/hardcore-cray-1jypy7?file=/src/app.controller.ts

### Steps to reproduce

Simply hit the default endpoint. This will call a controller > service > private `problematicFunction` and the app will crash.

### Expected behavior

I would expect that the exception handling would kick in and at least process the request. When I have a custom filter implemented, it will still crash the app. 

I understand that this may actually be a feature, and if so, could someone explain exactly why the behavior happens the way it does?

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

It's a nest thing, (+javascript async/threading behavior)

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Exception Filters are for catching exceptions that happen during the request lifecycle. If you call a promise but don't await it, the request moves on and can be responded to before the promise throws, meaning you have an unhandled promise. This is the intention of the framework and not a bug. 

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
