### ISSUE TITLE
App.get() for unknown token instead of throwing an error shuts down application with process.exit(1)

### ISSUE THREAD

**Issue by goriunov** [nestjs/nest#10541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we call `app.get("SOME_STUFF")` it prints an error and immediately exists an application instead of just throwing an error that can be caught by the user and handled appropriately.

### Minimum reproduction code

Check steps to reproduce for the code

### Steps to reproduce

```ts
import { Module } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";
import { FastifyAdapter } from "@nestjs/platform-fastify";

@Module({})
class Container {}

const bootstrap = async () => {
    const app = await NestFactory.create(Container, new FastifyAdapter());

    try {
        app.get("SOMETHING");
    } catch (err) {
        // Expect error to be caught, instead application exits with process.exit(1);
        console.log("Error in here", err);
    }

    app.listen(3000);
};

bootstrap();
```

### Expected behavior

Just throw an error that can be handled by the application in a relevant way without exiting the application

```
dmitriigoriunov@Dmitriis-MacBook-Pro at_realtime_common % npx ts-node ./test/test.ts
[Nest] 82387  - 08/11/2022, 22:21:33     LOG [NestFactory] Starting Nest application...
[Nest] 82387  - 08/11/2022, 22:21:33     LOG [InstanceLoader] Container dependencies initialized +18ms
[Nest] 82387  - 08/11/2022, 22:21:33   ERROR [ExceptionHandler] Nest could not find SOMETHING element (this provider does not exist in the current context)
Error: Nest could not find SOMETHING element (this provider does not exist in the current context)
    at InstanceLinksHost.get (_/node_modules/@nestjs/core/injector/instance-links-host.js:15:19)
    at NestApplication.find (_/node_modules/@nestjs/core/injector/abstract-instance-resolver.js:8:60)
    at NestApplication.get (_/node_modules/@nestjs/core/nest-application-context.js:64:20)
    at _/node_modules/@nestjs/core/nest-factory.js:133:40
    at Function.run (_/node_modules/@nestjs/core/errors/exceptions-zone.js:10:13)
    at Proxy.<anonymous> (_/node_modules/@nestjs/core/nest-factory.js:132:46)
    at Proxy.<anonymous> (_/node_modules/@nestjs/core/nest-factory.js:181:54)
    at bootstrap (_/test/test.ts:12:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Exited at this point
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```json
    "@nestjs/common": "^9.2.0",
    "@nestjs/core": "^9.2.0",
    "@nestjs/platform-fastify": "^9.2.0",
```

### Node.js version

18

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
