### ISSUE TITLE
nestjs website is out of reach

### ISSUE THREAD

**Issue by my-random-username** [nestjs/nest#10546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

the website is down

### Minimum reproduction code

2

### Expected behavior

Both the documentation and GitHub settings for reporting bugs in nestjs are the worst of their kind

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

master

### Packages versions

I can't access the nestjs website since yesterday. I wonder if the service is unavailable or if my connection to the website is limited.

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
