### ISSUE TITLE
hmr not working [HMR] Update failed: SyntaxError:.hot-update.json: Unexpected end of JSON input

### ISSUE THREAD

**Issue by sakura-he** [nestjs/nest#10559]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When editing my code frequently, the hot update throws an error, and the hot update after that does not include the latest code changes, but WEBPACK does tell me that the compilation is done

### Minimum reproduction code

https://github.com/sakura-he/nestjs

### Steps to reproduce

- npm start:dev
- open localhost:3002 or api
- Frequently modify the code in /src/app.controller.ts getHello mehods Make webpack trigger hot update
- If you try enough times (20+), you will definitely trigger an error like the following
```
 Info  Webpack is building your sources...

[HMR] Update failed: SyntaxError: C:\Users\aw\Desktop\nest-test\nest-test\dist\main.473066e693d2284ab7c5.hot-update.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1173:22)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at C:\Users\aw\Desktop\nest-test\nest-test\dist\main.js:1310:21
Entrypoint main 49 KiB = main.js 46.6 KiB 0.473066e693d2284ab7c5.hot-update.js 2.46 KiB
webpack 5.74.0 compiled successfully in 223 ms
```
- After that, if you modify the code again, webpack will tell you that the hot update compilation is done, but the latest changes you made to the code will not actually be compiled

### Expected behavior

Please let the hot update work
Thank you very much for your team

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [x] Other (see below)

### Other package

@nestjs/cli？webpak？

### NestJS version

latest

### Packages versions

```json
{
	"name": "nest-fir",
	"version": "0.0.1",
	"description": "",
	"author": "",
	"private": true,
	"license": "UNLICENSED",
	"scripts": {
		"prebuild": "rimraf dist",
		"build": "nest build",
		"format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
		"start": "ts-node src/index.ts",
		"start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js --watch",
		"start:debug": "nest start --debug --watch",
		"start:prod": "node dist/main",
		"lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
		"test": "jest",
		"test:watch": "jest --watch",
		"test:cov": "jest --coverage",
		"test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
		"test:e2e": "jest --config ./test/jest-e2e.json",
		"typeorm": "typeorm-ts-node-commonjs",
		"migration:generate": "npm run typeorm migration:generate -- -d ./ormconfig.ts ./migrations/Migration",
		"migration:run": "npm run typeorm migration:run -- -d ./ormconfig.ts "
	},
	"dependencies": {
		"@nestjs/common": "^9.0.0",
		"@nestjs/config": "^2.2.0",
		"@nestjs/core": "^9.0.0",
		"@nestjs/jwt": "^9.0.0",
		"@nestjs/mapped-types": "*",
		"@nestjs/passport": "^9.0.0",
		"@nestjs/platform-express": "^9.0.0",
		"@nestjs/typeorm": "^9.0.1",
		"@prisma/client": "^4.3.1",
		"@types/multer": "^1.4.7",
		"argon2": "^0.29.1",
		"class-transformer": "^0.5.1",
		"class-validator": "^0.13.2",
		"dotenv": "^16.0.3",
		"ejs": "^3.1.8",
		"express": "^4.18.2",
		"g": "^2.0.1",
		"jsonwebtoken": "^8.5.1",
		"mariadb": "^3.0.1",
		"mock": "^0.1.1",
		"mockjs": "^1.1.0",
		"mysql2": "^2.3.3",
		"passport": "^0.6.0",
		"passport-jwt": "^4.0.0",
		"passport-local": "^1.0.0",
		"reflect-metadata": "^0.1.13",
		"rimraf": "^3.0.2",
		"rxjs": "^7.2.0",
		"typeorm": "0.3.10"
	},
	"devDependencies": {
		"@nestjs/cli": "^9.0.0",
		"@nestjs/schematics": "^9.0.0",
		"@nestjs/testing": "^9.0.0",
		"@types/express": "^4.17.13",
		"@types/jest": "28.1.8",
		"@types/mockjs": "^1.0.7",
		"@types/node": "^16.11.10",
		"@types/supertest": "^2.0.11",
		"@typescript-eslint/eslint-plugin": "^5.0.0",
		"@typescript-eslint/parser": "^5.0.0",
		"eslint": "^8.0.1",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-prettier": "^4.0.0",
		"jest": "28.1.3",
		"prettier": "^2.3.2",
		"prisma": "^4.3.1",
		"run-script-webpack-plugin": "^0.1.1",
		"source-map-support": "^0.5.20",
		"supertest": "^6.1.3",
		"ts-jest": "28.0.8",
		"ts-loader": "^9.2.3",
		"ts-node": "10.7.0",
		"tsconfig-paths": "4.1.0",
		"typescript": "4.5.2",
		"webpack": "^5",
		"webpack-node-externals": "^3.0.0"
	},
	"jest": {
		"moduleFileExtensions": [
			"js",
			"json",
			"ts"
		],
		"rootDir": "src",
		"testRegex": ".*\\.spec\\.ts$",
		"transform": {
			"^.+\\.(t|j)s$": "ts-jest"
		},
		"collectCoverageFrom": [
			"**/*.(t|j)s"
		],
		"coverageDirectory": "../coverage",
		"testEnvironment": "node"
	}
}
```

### Node.js version

v16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

 Info  Webpack is building your sources...

[HMR] Update failed: SyntaxError: C:\Users\aw\Desktop\nest-fir\dist\main.b8158cbeffd28731ed96.hot-update.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1173:22)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at C:\Users\aw\Desktop\nest-fir\dist\main.js:3125:21
Entrypoint main 121 KiB = main.js 119 KiB 0.b8158cbeffd28731ed96.hot-update.js 1.58 KiB
webpack 5.74.0 compiled successfully in 2204 ms

 Info  Webpack is building your sources...

webpack 5.74.0 compiled successfully in 908 ms

 Info  Webpack is building your sources...

Entrypoint main 121 KiB = main.js 119 KiB 0.f881fae31027cc1c9dad.hot-update.js 1.58 KiB
webpack 5.74.0 compiled successfully in 4067 ms

 Info  Webpack is building your sources...

webpack 5.74.0 compiled successfully in 1284 ms

 Info  Webpack is building your sources...

Entrypoint main 121 KiB = main.js 119 KiB 0.09beb5a439fcf46acc39.hot-update.js 1.58 KiB
webpack 5.74.0 compiled successfully in 864 ms

 Info  Webpack is building your sources...

webpack 5.74.0 compiled successfully in 734 ms

 Info  Webpack is building your sources...

Entrypoint main 121 KiB = main.js 119 KiB 0.7878d5ef0759fd3288a1.hot-update.js 1.77 KiB
webpack 5.74.0 compiled successfully in 1444 ms

 Info  Webpack is building your sources...

**Comment by micalevisk** [comment]
> why not discuss it on a programming-related website like github?

There are several issues asking something similar. 

If this is in fact a bug on the fw side, we can discuss it here.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
