### ISSUE TITLE
Feature: Any plan to provide a @RefreshScope  to re-init module.

### ISSUE THREAD

**Issue by Nawbc** [nestjs/nest#10550]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Relate to #7961

Due to the nest's module cannot re-init at runtime, the node process needs to restart to apply the remote dynamic configs.

### Describe the solution you'd like

It is helpful for remote config service that we cloud reload the app without restarting the process.  Just like spring cloud's @RefeshScope annotation. 

### Teachability, documentation, adoption, migration strategy

https://docs.erda.cloud/en/2.0/manual/msp/guides/nc/spring.html#use-refreshscope-annotation-of-spring-cloud-config

**Comment by Nawbc** [comment]
> so we would have some decorator to mark those providers/controllers/enhancers that should be reinitialized when something happens?

yep

> I didn't follow what would triggers that in terms of nodejs capabilities, could you please elaborate? I didn't use Spring before
> 
> I guess that feature could play well with the REPL one

This feature should have nothing to do with nodejs.

> I didn't use Spring before

Me too. 😂


The Situation:
when we use the tools like consul nacos or any other configuration management system, KV store. We can fetch the configs from it, and updating the remote configs will trigger the subscription, but configs are immutable in memory after initialization, so we need to reload the nest module to modify the configs in memory and apply them to the app.

e.g. 
```ts
TypeOrmModule.forRootAsync({
  imports: [NacosConfigModule],
  inject: [NacosConfigService],
  async useFactory(nacosConfigService: NacosConfigService) {
    const configs = await nacosConfigService.getConfig('service-auth.json'); 
  
    return {
      ...configs.orm,
      autoLoadEntities: true,
    };
  },
},

```
``` ts
@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor(readonly nacosConfigService: NacosConfigService) {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      ignoreExpiration: false,
      async secretOrKeyProvider(_request, _jwtToken, done) {
        const c = await nacosConfigService.getConfig('service-auth.json');

        done(null, c.jwt.secret);
      },
    });
  }

  async validate(payload: JwtPayload) {
    return payload;
  }
}

```
Not limited to the database, jwt configs. 

---

This is the `@RefreshScope` description.
https://www.javadoc.io/doc/org.springframework.cloud/spring-cloud-commons-parent/1.1.4.RELEASE/org/springframework/cloud/context/scope/refresh/RefreshScope.html

Result  https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/multi/multi__spring_cloud_config_2.html#_refreshing_the_configuration_at_runtime

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
