### ISSUE TITLE
[Future Request] Add metadata to exceptionFactory for built-in parse pipes

### ISSUE THREAD

**Issue by KiritaniAyaka** [nestjs/nest#10555]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to get more information when built-in parse pipes throw an error. Such as the name of the arguments.

### Describe the solution you'd like

Add metadata to the `exceptionFactory` of every built-in parse pipes

### Teachability, documentation, adoption, migration strategy

Passing an `exceptionFactory` with a function has two parameters like this:

```ts
new ParseIntPipe({
	exceptionFactory: (error: string, metadata: ArgumentMetadata) => {
		/* ... */
	}
});
```

### What is the motivation / use case for changing the behavior?

We can know which parameter has parse failed. It is possible to throw an error with a more friendly message.

---

I could open a pull request for this issue if you would like.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
