### ISSUE TITLE
The request variable randomly disappears in models

### ISSUE THREAD

**Issue by torsakch** [nestjs/nest#10561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My application needs to support multi-tenancy. I'm trying to implement the models that automatically add "where tenent_id = xxx" clause to every query. The attached code is the way I implement that. Everything seems to work fine except sometime the request variable just have no value (null) in some requests randomly. Note that I get the tenant_id from the header of requests. I think there are some strange behaviors in this. In the code, I gets the error "No tenentId" randomly (line 26 and 59).  Please check the setup and guide to the solution. Thanks!!!!

### Minimum reproduction code

https://gist.github.com/torsakch/d70cca2970e2c79f4a525a3d9082aeea

### Steps to reproduce

The issues occurs randomly. So, I cannot show the exact steps to reproduce. It might be some memory, or cache problem that make this issue occurs.  

### Expected behavior

In every requests, the request objects should not be disappears. The model should get the tenant_id from the request object everytime.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.11

### Packages versions

```json
docker image: node:16.16.0-alpine3.16
"@nestjs/core": "^9.0.11",
"@nestjs/common": "^9.0.11",
"@nestjs/platform-express": "9.0.11",
"@nestjs/sequelize": "^8.0.0",
"sequelize": "^6.6.5",
"sequelize-cli": "^6.2.0",
"sequelize-typescript": "^2.1.0",
```

### Node.js version

6.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
please share minimum reproduction repository.

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
