### ISSUE TITLE
Precision on working nest on windows

### ISSUE THREAD

**Issue by FloUz-ai** [nestjs/nest#10567]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Yesterday I tried to use the nest CLI to generate a nest project. 

When I did run the command, the project was generated correctly but when I tried to launch `npm run start:dev` or any other to start the project I encountered the error : 

`Cannot find module 'source-map-support/register'`

I tried to install but nothing soleved my problem. 

I ended up creating my project on wsl and it worked fine. 

On conclusion it seems there is a probleme using nest on windows.

### Describe the solution you'd like

In the FAQ or in the general documentation, you should write that this error is on windows side only and nest CLI should be used on linux only

### Teachability, documentation, adoption, migration strategy

Same as above 

### What is the motivation / use case for changing the behavior?

Same as the first question

**Comment by micalevisk** [comment]
Can you please share some screenshot of that error? Showing your terminal and the message itself

I have a machine with Windows 10 (that I don't use for programming) I could try to reproduce that issue

**Comment by FloUz-ai** [comment]
Hi guys, Here a screen of the error raised when I launch the project generated 

![image](https://user-images.githubusercontent.com/83022872/202169393-4bec6e82-4af7-4eb9-be2d-305cbcf4f77f.png)

**Comment by jmcdo29** [comment]
Nest doesn't call to the `source-map-support` package at all in its code. You can search the code base for it and only find references in the `package-lock.json` files. This is something with your setup, not the framework
