### ISSUE TITLE
Version-aware Middleware doesn't play well with global prefix

### ISSUE THREAD

**Issue by mareksuscak** [nestjs/nest#10566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Given the following implementation:

```
// main.ts
app.setGlobalPrefix('api');
app.enableVersioning({
    type: VersioningType.URI,
    prefix: 'v',
    defaultVersion: '1',
  });

// user.module.ts
export class UserModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(RetrieveUserByIdMiddleware)
      .forRoutes({ path: 'users/:userId', method: RequestMethod.GET, version: '1' });
  }
}
```

The middleware doesn't work as expected because it's currently generating the following URL:

```
/v1/api/users/:userId
```

instead of:

```
/api/v1/users/:userId
```

In other words, version numbers are being prepended before the global prefix where it should be prepend before the path but appended after the global prefix.

### Minimum reproduction code

https://codesandbox.io/s/nestjs-version-aware-middleware-repro-ecg7ge

### Expected behavior

Global prefix should precede the version number and the version number should precede the path.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

9.2.0

### Node.js version

18.x.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by thaoula** [comment]
Hi All,

I just tried applying a route version using @Version and it does not seem to working correctly.

I see the version prefix being applied before the Global Prefix as described in the issue above.

I see -
` /v1/api/task`

 rather than 
`/api/v1/task `

as suggested in the documentation.

Regards,
Tarek

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10390

**Comment by RizkySix** [comment]
Thank you mate it helps me a lot ❤️
