### ISSUE TITLE
Bug: no connection to RabbitMQ

### ISSUE THREAD

**Issue by MikeKoval** [nestjs/nest#10562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have this test scenario:
1. Stop rabbit mq server or just close connection from rabbit mq manager
2. Push a message to queue using emit() from ClientProxy
3. Start rabbit mq server
4. Push another message in queue like 2.

Expected:
2 messages in queue

Actual:
No messages in queue

I noticed nest.js microservices using https://www.npmjs.com/package/amqp-connection-manager stating 
>If messages are sent while the broker is unavailable, queues messages in memory until we reconnect.

Also wondering how do you suggest to troubleshoot microservices communication?
I mean i used to logs of what was pushed to queue, retry, reconnect, offline actions etc... that could help to troubleshoot such issues better, but maybe its related to amqp-connection-manager directly, not to nest.js microservices.

### Minimum reproduction code

https://github.com/MikeKoval/nest-rabbit-mq-test

### Steps to reproduce

https://user-images.githubusercontent.com/19329415/201859955-dd810b64-bc7c-44bb-bb43-c04f5c94788a.mp4

### Expected behavior

2 messages in queue

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

https://github.com/MikeKoval/nest-rabbit-mq-test/blob/main/package.json

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by yieldinov** [comment]
Face same issue

**Comment by MikeKoval** [comment]
As there is no reaction i had to get rid of nest micro services in favor of amqp-connection-manager, i dont have such issue anymore

**Comment by corentingosselin** [comment]
I found something interesting in nestjs microservice source code inside client-rmq.ts
```
  public connect(): Promise<any> {
    if (this.client) {
      return this.connection;
    }
    this.client = this.createClient();
    this.handleDisconnectError(this.client);
    const connect$ = this.connect$(this.client);
    this.connection = lastValueFrom(
      this.mergeDisconnectEvent(this.client, connect$).pipe(
        switchMap(() => this.createChannel()),
        share(),
      ),
    ).catch(err => {
      if (err instanceof EmptyError) {
        return;
      }
      throw err;
    });
    return this.connection;
  }
```
The connection observable is not recreated after connection closed (when you stop the rmq server)
When you send a message while rmq server is off, the connection observable keep in memory the error connection refused.

And then when you resend a message with rabbitmq server started, it keeps the old error message and does not go to the next line: this.client = this.createClient();

To fix this, I would change the behaviour of this observable. don't really know how to do that but going to figure it out

**Comment by corentingosselin** [comment]
> I found something interesting in nestjs microservice source code inside client-rmq.ts
> 
> ```
>   public connect(): Promise<any> {
>     if (this.client) {
>       return this.connection;
>     }
>     this.client = this.createClient();
>     this.handleDisconnectError(this.client);
>     const connect$ = this.connect$(this.client);
>     this.connection = lastValueFrom(
>       this.mergeDisconnectEvent(this.client, connect$).pipe(
>         switchMap(() => this.createChannel()),
>         share(),
>       ),
>     ).catch(err => {
>       if (err instanceof EmptyError) {
>         return;
>       }
>       throw err;
>     });
>     return this.connection;
>   }
> ```
> 
> The connection observable is not recreated after connection closed (when you stop the rmq server) When you send a message while rmq server is off, the connection observable keep in memory the error connection refused.
> 
> And then when you resend a message with rabbitmq server started, it keeps the old error message and does not go to the next line: this.client = this.createClient();
> 
> To fix this, I would change the behaviour of this observable. don't really know how to do that but going to figure it out

So I found a fix, maybe not the best but it's working now.

 ```
  public mergeDisconnectEvent<T = any>(
    instance: any,
    source$: Observable<T>,
  ): Observable<T> {
    const eventToError = (eventType: string) =>
      fromEvent(instance, eventType).pipe(
        map((err: any) => {
          throw err;
        }),
      );
    const disconnect$ = eventToError(DISCONNECT_EVENT);

    const urls = this.getOptionsProp(this.options, 'urls', []);
    const connectFailed$ = eventToError(CONNECT_FAILED_EVENT).pipe(
      retryWhen(e =>
        e.pipe(
          scan((errorCount, error: any) => {
            this.close();
            if (urls.indexOf(error.url) >= urls.length - 1) {
              throw error;
            }
            return errorCount + 1;
          }, 0),
        ),
      ),
    );    
    return merge(source$, disconnect$, connectFailed$).pipe(first());
  }
 ```

I added  this.close(); to reset the client.
So the client is set to null when we try to send message to rabbitmq
when we try to send message if rabbitmq is connected it will recreate the client

**Comment by afilp** [comment]
Hi! 

Related to this: "As there is no reaction..."

Do you have the feeling that there is no active/heavy development on nestjs? I am just asking because we are evaluating it for our backend.

The vast majority of the commits are from the dependabot. I hope I am totally wrong here.

**Comment by corentingosselin** [comment]
> Hi!
> 
> Related to this: "As there is no reaction..."
> 
> Do you have the feeling that there is no active/heavy development on nestjs? I am just asking because we are evaluating it for our backend.
> 
> The vast majority of the commits are from the dependabot. I hope I am totally wrong here, @kamilmysliwiec and his team has done a great work and created a great platform. I am just asking for the future enhancements/fixes/support.
> 
> Thanks.

Hello, nestjs is a great tool, but yes it feels a bit inactive right now. Maybe the team is working on other project or support premium customers. 
This issue is critical, because without a fix we can't use microservice with rabbitmq, still waiting...

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11019
