### ISSUE TITLE
validate(payload: any) in Implementing Passport JWT doc it's not correct

### ISSUE THREAD

**Issue by enricodevita** [nestjs/nest#10568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

in doc when you explain the validate method in [Implementing Passport JWT](https://docs.nestjs.com/security/authentication#implementing-passport-jwt) you wrote that pass payload and then use it's properties payload.sub and payload.username but in validate the parameter it's all Request Object so you have to extract token from parameter, decode it, then you have payload and you can use it.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/19-auth-jwt

### Expected behavior

I expect that payload in validate method it's the payload object and not entire Request

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/passport

### Packages versions

"@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/swagger": "^6.1.3",
    "@nestjs/typeorm": "^9.0.1",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "mysql2": "^2.3.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.10"

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
let's track this here: fullReqLogger
