### ISSUE TITLE
@nestjs/axios not working

### ISSUE THREAD

**Issue by ungurnicoleta** [nestjs/nest#10578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am aware of this issue that `axios` had last month -> [https://github.com/axios/axios/issues/5038](https://github.com/axios/axios/issues/5038), but it seems like it's affecting this package as well.

Every time I try to use HttpModule, I'm getting this error. 

```
TypeError: this.http.get is not a function
```

### Minimum reproduction code

It's a private repo

### Expected behavior

That should be a valid method.
<img width="545" alt="Screenshot 2022-11-21 at 01 05 08" src="https://user-images.githubusercontent.com/32622785/202931477-34464f09-1a38-4d29-aded-1b7409dfe662.png">

<img width="608" alt="Screenshot 2022-11-21 at 01 05 00" src="https://user-images.githubusercontent.com/32622785/202931475-f9a0d672-256c-4fc5-8dc7-806e90193419.png">

<img width="666" alt="Screenshot 2022-11-21 at 01 05 51" src="https://user-images.githubusercontent.com/32622785/202931478-50255851-fccd-400d-968f-080abc8901b7.png">

### Package

 - [X] @nestjs/axios

### NestJS version

9.2.0

### Packages versions

```
{
  "name": "project",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/axios": "1.0.0",
    "@nestjs/common": "9.2.0",
    "@nestjs/config": "2.2.0",
    "@nestjs/core": "9.2.0",
    "@nestjs/jwt": "9.0.0",
    "@nestjs/passport": "9.0.0",
    "@nestjs/platform-express": "9.2.0",
    "@nestjs/schedule": "2.1.0",
    "@nestjs/typeorm": "9.0.1",
    "@types/bcrypt": "^5.0.0",
    "@types/passport-jwt": "^3.0.6",
    "aws-sdk": "^2.1159.0",
    "axios": "1.1.3",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "cookie-parser": "^1.4.6",
    "date-fns": "^2.28.0",
    "passport": "^0.5.2",
    "passport-jwt": "^4.0.0",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "stripe": "^9.10.0",
    "typeorm": "0.3.10",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@nestjs/cli": "9.1.5",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "9.2.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "9.4.1",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v18

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
we don't know what is that `this.http` but looks like it's not what you think it is.

If you believe that this a bug on the framework, please share a minimum reproduction of it. Otherwise you can use our [Discord](https://discord.gg/nestjs) for further support.

---

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment]
btw, `@nestjs/axios` has its own repository (that's why it's not listed in the _packages_ section of the form).

Run `npm docs @nestjs/axios` to find that out.
