### ISSUE TITLE
Module scoped providers

### ISSUE THREAD

**Issue by CrisDgrnu** [nestjs/nest#10572]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

My team is building an app based on 2 big modules, the first one is a GraphQL API and the second one is a MQTT service, we are defining the `AuthGuard` in the GraphQL module like this on the providers section

`
{
            provide: APP_GUARD,
            useClass: JwtAuthGuard
}
`

The problem is (this is the expected behavior we know), that it's applied globally, we know that we can use the `@useGuard` decorator in each resolver that we want, but is there any way to define providers that are "module scoped"? I haven't find anything like this, so I think that this can be a big improvement!

### Describe the solution you'd like

If we want providers to be global, we can provide them on app.module, else If we want them to be module-scoped, then they should be provided in the module, to work in the module and submodules. 

### Teachability, documentation, adoption, migration strategy

 .

### What is the motivation / use case for changing the behavior?

 .

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
