### ISSUE TITLE
Can't use raw body when built-in body parser is disabled/overwritten

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#10574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

if we disable the built-in body parser, we cannot use the [raw body](https://docs.nestjs.com/faq/raw-body) feature. Since there's no mention on `body-parser` in that page, I believe that the current behavior is a bug rather than a limitation (I could be wrong tho).

```ts
import { NestFactory } from '@nestjs/core'
import { AppModule } from './app.module'

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    bodyParser: false, // <<<
    rawBody: true,
  })
  await app.listen(3000)
}
```

Also, I notice that adding `app.use( json(...) )` (in order to define our own configuration to replace the built-in json body parser middleware) it will disable the raw body feature.

### Minimum reproduction code

not needed. See below

### Steps to reproduce

you can see that the method `registerParserMiddleware` won't be called if `bodyParser` is `false`

https://github.com/nestjs/nest/blob/8e3af065bb9abbecc91b4e6068c8e205ef79d165/packages/core/nest-application.ts#L169-L171

https://github.com/nestjs/nest/blob/8e3af065bb9abbecc91b4e6068c8e205ef79d165/packages/core/nest-application.ts#L184-L188

and below we can see that `httpAdapter.registerParserMiddleware` (for Express) is responsible for setting up the raw body feature:

https://github.com/nestjs/nest/blob/8e3af065bb9abbecc91b4e6068c8e205ef79d165/packages/platform-express/adapters/express-adapter.ts#L222-L236

### Expected behavior

I'd like to use my own body parser middleware instead of the built-in one while still be able to use on the raw body feature. Or, for instance, just disable the body parser but not the raw body:

```ts
// main.ts
import { NestFactory } from '@nestjs/core'
import { AppModule } from './app.module'
async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    bodyParser: false, // <<<
    rawBody: true,
  })
  await app.listen(3000)
}
bootstrap();

// controller.ts
import { Controller, Post, Req } from '@nestjs/common';

@Controller()
export class AppController {
    @Post()
    getBody(@Req() req: any) {
      return {
        rawBody: req.rawBody ?? null,
        body: req.body ?? null,
      }
    }
}
```

should return this:

```
$ curl -s -X POST -H "content-type: application/json" -d '{"foo": 123}' localhost:3000 | jq
{
  "rawBody": {
    "type": "Buffer",
    "data": [
      123,
      34,
      102,
      111,
      111,
      34,
      58,
      32,
      49,
      50,
      51,
      125
    ]
  },
  "body": null
}
```

instead of:

```
$ curl -s -X POST -H "content-type: application/json" -d '{"foo": 123}' localhost:3000 | jq
{
  "rawBody": null,
  "body": null
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```
[System Information]
OS Version     : Linux 5.15
NodeJS Version : v16.15.1
NPM Version    : 8.18.0 

[Nest CLI]
Nest CLI Version : 9.1.5 

[Nest Platform Information]
platform-express version : 9.2.0
schematics version       : 9.0.3
testing version          : 9.2.0
common version           : 9.2.0
core version             : 9.2.0
cli version              : 9.1.5
```

**Comment by micalevisk** [comment]
I think that the raw body feature depends entirely on `body-parser` (looking at the express adapter only). If so, I doubt that we could use it without the built-in body parser feature :disappointed: In this case, we need to mention this in the docs site.

**Comment by kamilmysliwiec** [comment]
> I think that the raw body feature depends entirely on body-parser (looking at the express adapter only).

Correct

> In this case, we need to mention this in the docs site.

Would you like to create a PR for this @micalevisk?

**Comment by micalevisk** [comment]
sure: https://github.com/nestjs/docs.nestjs.com/pull/2541
