### ISSUE TITLE
Mapped-types DTOs can't be imported by CRA (React)

### ISSUE THREAD

**Issue by bjornhauge** [nestjs/nest#10577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The DTO creation helpers from `@nestjs/mapped-types` cannot be imported by the `create-react-app` build process. There are several import errors, the first of them being these:
![image](https://user-images.githubusercontent.com/59002156/202916271-6b2833bf-cfe4-4f21-a88f-2215e6dc010c.png)
This is relevant when working in a monorepo and sharing DTO classes between front- and back-end. Trying to efficiently derive POST/PUT/GET DTOs from entity classes using the `OmitType`.

What is the recommended way to share these classes between front- and back-end?

### Minimum reproduction code

see two-line mod to CRA boilerplate in steps below

### Steps to reproduce

1. `npx create-react-app react-nestjs --template typescript`
2. `cd react-nestjs`
3. `npm i @nestjs/mapped-types`
4. Add the following code to `App.tsx`:
    ```ts
    import { OmitType } from "@nestjs/mapped-types";
    console.log(OmitType) // make sure CRA actually tries to import it
    ```
5. `npm start`

### Expected behavior

The `@nestjs/mapped-types` should be able to be imported and used by the CRA build process.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/mapped-types

### Packages versions

```json
  "dependencies": {
    "@nestjs/mapped-types": "^1.2.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.3",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.9",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.3",
    "web-vitals": "^2.1.4"
  },
```

### Node.js version

16.18.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

Also doesn't work with vite/esbuild.

**Comment by micalevisk** [comment]
https://github.com/nestjs/mapped-types/issues/907#issuecomment-1299824987

**Comment by bjornhauge** [comment]
This seems like an important use case for mapped types -- as far as I can imagine, probably the *main* use case. Might it be worth making it possible to use without webpack shims that most devs are unlikely to feel comfortable with?
