### ISSUE TITLE
using the `CacheInterceptor` for `StreamableFiles` and caching HTTP headers

### ISSUE THREAD

**Issue by StefanWin** [nestjs/nest#10575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Caching does not seem to work for routes which return `StreamableFile`. I don't know if its intended to work (or if it even makes sense to cache files via redis<sup>1</sup>) but the current behaviour seems buggy since HTTP headers aren't cached. 

<sup>1</sup> : I'm not that familiar with redis but IIRC the max value is something like 512mb per key and our files have a 8mb limit. We wanted to cache it since the file sits in a `minio` instance. We didn't use the presigned url stuff since we wanted URL's which don't expire.

Since the route can return any mime-type in our (closed-source) project, the `Content-Type` header needs to be set manually.

Setting a fixed `Content-Type` header with `@Header()` also does not work (which also wouldn't be good for our use-case since the `Content-Type` isn't fixed.

The reproduction repo uses `redis` as a cache store since the in-memory store throws node warnings:
```
(node:50553) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Readable]. Use emitter.setMaxListeners() to increase limit
```

The test file I used is a ~50kb jpg.

## Behaviour

**Samples will differ from reproduction repo for brevity**

When using the following setup:

```ts
@UseInterceptors(CacheInterceptor)
@CacheTTL(5)
@Header('Content-Type', 'image/jpeg')
@Header('Content-Disposition', 'inline; corgi.jpg')
// ...
```
and opening the route in a browser, the initial page-load will show the image but any subsequent page-loads which are within the TTL don't load correctly (white small square in Chrome).

Using:
```ts
@UseInterceptors(CacheInterceptor)
@CacheTTL(5)
@Get('/with-cache-decorator/image.jpg')
async defaultCache(
  @Res({ passthrough: true }) response: Response,
): Promise<StreamableFile> {
  const {buffer, contentType, fileName} = await loadFile();
  response.set({
    'Content-Disposition': `inline; ${fileName}`,
    'Content-Type': contentType,
  });
  return new StreamableFile(file);
}
```
and opening the route in the browser, the first page-load is fine as well but any subsequent page-loads within TTL will ignore the `Content-Type` header and return the content as `application/json`, i.e. `JSON.stringify(StreamableFile)`. Once the TTL expires the image will load normally.

I know that `CacheInterceptor` and injecting `Response` is not supported but it seems to partially work at least.

## Notes
I haven't tried a custom `FileCacheInterceptor` but it might possible with the `CacheManager` and caching something like:
```ts
const data = {
  headers: response.headers,
  data: response.body
}
```

In retrospect, this is more about documentation than a bug since I'm using unsupported behaviour.

Semi-related: the `StreamableFile` file constructor optionally takes an `options` object but there's nothing about that in the Documentation (website or `JSDoc`) so I'm assuming its for internal use.

### Minimum reproduction code

https://github.com/StefanWin/nestjs-cache-streamable-file-repro

### Steps to reproduce

1. `npm ci`
2. `docker compose up -d`
3. `npm run start:dev`
4. go to [`http://localhost:3000/with-cache-decorator/image.jpg`](http://localhost:3000/with-cache-decorator/image.jpg)
5. go to [`http://localhost:3000/without-headers/image.jpg`](http://localhost:3000/without-headers/image.jpg)
6. go to [`http://localhost:3000/fixed-headers/image.jpg`](http://localhost:3000/fixed-headers/image.jpg)
7. go to [`http://localhost:3000/without-cache-decorator/image.jpg`](http://localhost:3000/without-cache-decorator/image.jpg)

### Expected behavior

If it should work: `Content-Type` (and other headers) should be cached.
If it shouldn't: No caching at all, a warning/error or just a hint in the `Caching` or `Streaming Files` documentation.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```json
"@nestjs/common": "^9.0.0",
"@nestjs/core": "^9.0.0",
"@nestjs/platform-express": "^9.0.0",
"cache-manager": "4.1.0",
"cache-manager-ioredis": "2.1.0",
"reflect-metadata": "^0.1.13",
"rimraf": "^3.0.2",
"rxjs": "^7.2.0"
```

### Node.js version

18.4.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
