### ISSUE TITLE
RawBody with Binary

### ISSUE THREAD

**Issue by UncleFirefox** [nestjs/nest#10587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, I'm trying to use the rawBody feature with binary in Postman but it does not work.

![image](https://user-images.githubusercontent.com/3224718/203412911-482f037b-4467-481f-9ff8-ca2919d079bb.png)

I thought passing binary would have the buffer value field on req.rawBody but it does not, is this intended to work with binary?
NOTE: I configured the feature correctly and if I pass a raw json I see a buffer there so I guess rawBody works but not for this case?

Some people created this gist but I find it rather ugly: https://gist.github.com/jonilsonds9/efc228e34a298fa461d378f48ef67836

### Minimum reproduction code

-

### Expected behavior

req.rawBody has the buffer of the attached file

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"@nestjs/common": "^9.0.8",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.8",
    "@nestjs/platform-express": "^9.0.8",
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by jmcdo29** [comment]
Nest does not add `req.rawBody` based on the raw income, rather it modifies the body-parser signature for `application/json` and `application/x-www-form-urlencoded` to take the original raw body and set it to `req.rawBody`. This means that if you send a data type that does not match, then `req.rawBody` will not be set.

**Comment by micalevisk** [comment]
@UncleFirefox feel free to update the docs on raw body to mention the behavior described above.

**Comment by micalevisk** [comment]
@UncleFirefox 

- express: https://github.com/nestjs/nest/blob/220b098e220b1e3471493d036425d525a951e566/packages/platform-express/adapters/express-adapter.ts#L222
- fastify: https://github.com/nestjs/nest/blob/220b098e220b1e3471493d036425d525a951e566/packages/platform-fastify/adapters/fastify-adapter.ts#L455

**Comment by clintonb** [comment]
@micalevisk can you say more, please? It's a year later, and I'm encountering this issue but there are zero docs. You've provided two links, but it's unclear what someone needs to do to receive other content types.

**Comment by micalevisk** [comment]
@clintonb please use our discord for support

I don't recall neither

**Comment by clintonb** [comment]
I adapted https://stackoverflow.com/a/61416426/592820. This requires installing [raw-body](https://www.npmjs.com/package/raw-body). I have `rawBody: true` on the `NestFactory.create()` call, but have no clue if it's required to get the raw body to the controller. I need it to handle AWS signature verification for the S3 proxy I'm building.

I created a decorator to apply to a controller route's arguments.
```ts
import {
  BadRequestException,
  ExecutionContext,
  createParamDecorator,
} from '@nestjs/common';
import getRawBody from 'raw-body';

export const RawBody = createParamDecorator(
  async (_, context: ExecutionContext) => {
    const req = context.switchToHttp().getRequest<import('express').Request>();
    if (!req.readable) {
      throw new BadRequestException('Invalid body');
    }

    return getRawBody(req);
  }
);
```

Here it is in action:
```ts
// controller.ts

@Put('*')
@Header('Content-Type', 'application/xml')
async put(@Req() request, @Param() params, @RawBody() body) {
  const name = request.params[0];
  return this.s3ProxyService.putObject({
    bucketName: BUCKET,
    name,
    content: body,
  });
}
```
