### ISSUE TITLE
@nestjs/microservices peer dependencies not installing. 

### ISSUE THREAD

**Issue by jeremyjfleming** [nestjs/nest#10582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying to run application, but I found some of the packages listed in microservices are not installing. Specifically the ones that use "*" for versioning and are listed as optional in the peerDependenciesMeta

`ERROR in ../node_modules/@nestjs/microservices/client/client-grpc.js 25:104-128
Module not found: Error: Can't resolve '@grpc/grpc-js' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/client'
 @ ../node_modules/@nestjs/microservices/client/index.js 5:21-45
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/client/client-grpc.js 27:14-43
Module not found: Error: Can't resolve '@grpc/proto-loader' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/client'
 @ ../node_modules/@nestjs/microservices/client/index.js 5:21-45
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/client/client-kafka.js 38:95-113
Module not found: Error: Can't resolve 'kafkajs' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/client'
 @ ../node_modules/@nestjs/microservices/client/index.js 6:21-46
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/client/client-mqtt.js 19:90-105
Module not found: Error: Can't resolve 'mqtt' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/client'
 @ ../node_modules/@nestjs/microservices/client/index.js 7:21-45
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/client/client-nats.js 19:90-105
Module not found: Error: Can't resolve 'nats' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/client'
 @ ../node_modules/@nestjs/microservices/client/index.js 8:21-45
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/client/client-redis.js 16:95-113
Module not found: Error: Can't resolve 'ioredis' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/client'
 @ ../node_modules/@nestjs/microservices/client/index.js 12:21-46
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/client/client-rmq.js 35:78-96
Module not found: Error: Can't resolve 'amqplib' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/client'
 @ ../node_modules/@nestjs/microservices/client/index.js 13:21-44
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/client/client-rmq.js 36:107-141
Module not found: Error: Can't resolve 'amqp-connection-manager' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/client'
 @ ../node_modules/@nestjs/microservices/client/index.js 13:21-44
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/deserializers/nats-request-json.deserializer.js 10:107-122
Module not found: Error: Can't resolve 'nats' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/deserializers'
 @ ../node_modules/@nestjs/microservices/server/server-nats.js 8:41-99
 @ ../node_modules/@nestjs/microservices/server/index.js 8:21-45
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/deserializers/nats-response-json.deserializer.js 11:140-155
Module not found: Error: Can't resolve 'nats' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/deserializers'
 @ ../node_modules/@nestjs/microservices/client/client-nats.js 9:42-101
 @ ../node_modules/@nestjs/microservices/client/index.js 8:21-45
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/helpers/kafka-reply-partition-assigner.js 13:111-129
Module not found: Error: Can't resolve 'kafkajs' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/helpers'
 @ ../node_modules/@nestjs/microservices/helpers/index.js 7:21-64
 @ ../node_modules/@nestjs/microservices/index.js 16:21-41
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/serializers/nats-record.serializer.js 10:100-115
Module not found: Error: Can't resolve 'nats' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/serializers'
 @ ../node_modules/@nestjs/microservices/client/client-nats.js 11:33-81
 @ ../node_modules/@nestjs/microservices/client/index.js 8:21-45
 @ ../node_modules/@nestjs/microservices/microservices-module.js 12:17-36
 @ ../node_modules/@nestjs/core/nest-application.js 20:124-177
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/server/server-grpc.js 22:79-103
Module not found: Error: Can't resolve '@grpc/grpc-js' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/server'
 @ ../node_modules/@nestjs/microservices/server/index.js 5:21-45
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/server/server-grpc.js 24:14-43
Module not found: Error: Can't resolve '@grpc/proto-loader' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/server'
 @ ../node_modules/@nestjs/microservices/server/index.js 5:21-45
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/server/server-kafka.js 36:75-93
Module not found: Error: Can't resolve 'kafkajs' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/server'
 @ ../node_modules/@nestjs/microservices/server/index.js 6:21-46
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/server/server-mqtt.js 17:70-85
Module not found: Error: Can't resolve 'mqtt' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/server'
 @ ../node_modules/@nestjs/microservices/server/index.js 7:21-45
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/server/server-nats.js 18:70-85
Module not found: Error: Can't resolve 'nats' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/server'
 @ ../node_modules/@nestjs/microservices/server/index.js 8:21-45
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/server/server-redis.js 16:75-93
Module not found: Error: Can't resolve 'ioredis' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/server'
 @ ../node_modules/@nestjs/microservices/server/index.js 9:21-46
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/server/server-rmq.js 34:58-76
Module not found: Error: Can't resolve 'amqplib' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/server'
 @ ../node_modules/@nestjs/microservices/server/index.js 10:21-44
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38

ERROR in ../node_modules/@nestjs/microservices/server/server-rmq.js 35:87-121
Module not found: Error: Can't resolve 'amqp-connection-manager' in '/mnt/c/Users/jerem/projects/eafab/node_modules/@nestjs/microservices/server'
 @ ../node_modules/@nestjs/microservices/server/index.js 10:21-44
 @ ../node_modules/@nestjs/microservices/index.js 21:21-40
 @ ../node_modules/@nestjs/core/nest-application.js 121:120-152
 @ ../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 4:15-38`

### Minimum reproduction code

https://github.com

### Expected behavior

Should run correctly with the necessary dependencies installed. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/

[System Information]
OS Version     : Linux 4.4
NodeJS Version : v18.12.1
NPM Version    : 8.19.2 

[Nest CLI]
Nest CLI Version : 9.1.5

[Nest Platform Information]
platform-socket.io version : 9.2.0
platform-express version   : 9.2.0
microservices version      : 9.2.0
mapped-types version       : 1.2.0
websockets version         : 9.2.0
schematics version         : 9.0.3
testing version            : 9.2.0
common version             : 9.2.0
core version               : 9.2.0
cli version                : 9.1.5

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by micalevisk** [comment]
how can we reproduce this?

**Comment by jeremyjfleming** [comment]
this is a standard nest application as an npm sub-project. I am using additional nest packages as listed above. This isn't necessarily a project-specific problem, I don't understand why npm isn't installing some of the peer dependencies.

**Comment by micalevisk** [comment]
npm install won't install peer deps, that's not how peer deps works.

Resources:

- https://nodejs.org/es/blog/npm/peer-dependencies
- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies

---

I'll close this until you provide us some guidance on how to reproduce your issue. Thanks.

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by jeremyjfleming** [comment]
Rather than an issue with nest, is this an issue with my project itself? I am not using any of the services listed as optional in the meta, why would this be happening? Is there a setting I'm missing? I am not able to provide a working reproduction at this time. I am asking if you would know why this might be happening from a general view of the framework.

**Comment by jeremyjfleming** [comment]
Alright. Thanks
