### ISSUE TITLE
inject function

### ISSUE THREAD

**Issue by nitedani** [nestjs/nest#10586]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Idea: 

In angular14 they added [inject()](https://angular.io/api/core/inject), that can be used to inject dependencies in new ways. Is there plan for something similar?

### Describe the solution you'd like

Something similar to the angular inject()

### Teachability, documentation, adoption, migration strategy

```ts
@Injectable()
export class UserService {
  configService = inject(ConfigService)
...
```
```ts
@Module({
  providers: [{
    provide: "SomeService",
    useFactory() {
        const configService = inject(ConfigService)
        ...
    },
  }],
})
export class AppModule {}
```

### What is the motivation / use case for changing the behavior?

Less boilerplate

**Comment by micalevisk** [comment]
> Less boilerplate

can you show an example on the current way of achieving what you intended for?

**Comment by nitedani** [comment]
right now
```ts
@Injectable()
export class UserService {
  someProp: string;
  constructor(private configService: ConfigService) {
    this.someProp = configService.SOME_PROP;
  }
```
vs
```ts
@Injectable()
export class UserService {
  configService = inject(ConfigService)
  someProp = this.configService.SOME_PROP;
```

**Comment by micalevisk** [comment]
thanks, I didn't used Angular before.

IMHO the difference seems to be too minimal. So we end up having two ways of doing the same thing, which will increases the learning curve, while has no real gain in terms of verbosity.

But if Kamil aggrees on having that in the core, I'd be happy to maintain it anyway.

**Comment by nitedani** [comment]
```ts
const someFunction = (someParam) => {
  const serviceA = inject(ServiceA)
  const serviceB = inject(ServiceB)
  return serviceA.doSomething() + serviceB.doSomethingElse() + someParam
}

@Injectable()
export class UserService {
  something = someFunction("hello")
}
@Injectable()
export class NotesService {
  somethingElse = someFunction("bye")
}
```

**Comment by micalevisk** [comment]
so its seems now that `inject` would behave pretty much like `app.get()`

I'm not sure if that's even feasible tbh :thinking:

**Comment by KostyaTretyak** [comment]
@nitedani, I haven't tried `inject()` in an Angular context yet, but it seems that even in Angular it is not possible to make the `someFunction()` you described using `inject()` outside the class or `useFactory()`. So your services will not be able to call this function as easily as you wrote in the code.

Is it still possible to do this in practice in Angular?

**Comment by KostyaTretyak** [comment]
The problem with `inject()` is that its use will not allow DI recursive scanning of dependencies in the process of imports/exports of modules with providers.

For example:

```ts
import { Injectable, Module, inject } from '@nestjs/common';

// ********** In Module1 **********
@Injectable()
export class Service1 {}

@Injectable()
export class Service2 {
  constructor(private service1: Service1) {}
}

@Module({
  providers: [Service1, Service2],
  exports: [Service2],
})
export class Module1 {}


// ********** In Module2 **********
@Module({
  imports: [Module1]
})
export class Module2 {}

@Injectable()
export class Service3 {
  service2 = inject(Service2);
}
```

The call `inject(Service2)` will not work in Module2 because DI will not import Service1.

**Comment by micalevisk** [comment]
@KostyaTretyak with [`ModuleRef`](https://docs.nestjs.com/fundamentals/module-ref#module-reference) we can retrieve the a provider from the global context by supplying the option `strict: false`  to `ModuleRef#get`.

But I don't see any way to implement the `inject` function here.

**Comment by KostyaTretyak** [comment]
> we can retrieve the a provider from the global context by supplying the option `strict: false` to `ModuleRef#get`.

But will `ModuleRef` be able to export `Service1` even if it is not exported from `Module1`?

If we look at this code:

```ts
@Injectable()
export class Service2 {
  service1 = inject(Service1);
}
```

I assume that there is no way to see that `Service2` depends on `Service1`.

**Comment by micalevisk** [comment]
yep, as long as the provider is visible to the root module (that should be the same for both `Service1` and `Service2`). By _visible_ I mean: some module has been registered the provider.

<details>
<summary>talk is cheap</summary>

```ts
import { Module, Injectable } from '@nestjs/common';
import { ModuleRef } from '@nestjs/core';

@Module({
  providers: [{ provide: 'Service1', useValue: 456 }], // note: there's no exports
})
export class Module1 {}


@Injectable()
export class Service2 {
  // constructor(@Inject('Service1') private bar: number) {} // won't work, as expected
  constructor(private readonly moduleRef: ModuleRef) {}

  onModuleInit() {
    const service1 = this.moduleRef.get('Service1', { strict: false })
    console.log(service1) // 456
  }
}

@Module({
  providers: [Service2],
})
export class Module2 {}


@Module({
  imports: [Module1, Module2],
})
export class AppModule {} // root module
```

</details>

**Comment by KostyaTretyak** [comment]
> as long as the provider is visible to the root module

But if not visible to the root module? For example, if `Service1` and `Service2` has request scope?

**Comment by kamilmysliwiec** [comment]
Introducing the `inject()` function would be against the fundamental design decisions of this framework. Angular added this function to address edge-cases we don't have to worry about ourselves.
