### ISSUE TITLE
[Discussion] Share material / presentations about Nest

### ISSUE THREAD

**Issue by cyril-lakech** [nestjs/nest#1058]
I see a lot of presentations about Nest those days on Twitter 😍

We are preparing a talk for an event in Paris next month.
We can find a few videos online but not so many slides are available.

Could you share here  materials and slides about Nest to help crafting great deck to present it everywhere in the world more easily?

We are building our slide from scratch and maybe we could found some help with some material online. I am sure every other speakers are doing the same.

We will share our presentation soon, still draft now but will be live before end of october.

**Comment by kamilmysliwiec** [comment]
My latest presentation: https://speakerdeck.com/kamilmysliwiec/rethinking-enterprise-architectures-with-node-dot-js

**Comment by cyril-lakech** [comment]
thanks @kamilmysliwiec nice slides

**Comment by bovandersteene** [comment]
These are my slides from 6 months ago, https://slides.com/bovandersteene/nestjs. They are still based on nest 4.

**Comment by cyril-lakech** [comment]
Thanks and our slides: https://axaguildev.github.io/nestjs-talk

**Comment by kamilmysliwiec** [comment]
My latest presentation from ngAtlanta https://speakerdeck.com/kamilmysliwiec/dependency-injection-in-nest-and-angular-intersection-and-mismatch

**Comment by kamilmysliwiec** [comment]
And "Taming reactive node.js: Stream-oriented architecture with Nest" presented at JsKongress 🇩🇪 https://speakerdeck.com/kamilmysliwiec/taming-reactive-node-dot-js-stream-oriented-architecture-with-nest

**Comment by wenderpmachado** [comment]
Thanks for the previous presentations, it helped me a lot. 
Here is my presentation from yesterday at OpenLabsConf 🇧🇷: https://www.slideshare.net/WenderMachado1/nest-js-o-framework-progressivo

**Comment by vesheff** [comment]
Hello everyone 

@kamilmysliwiec 
Thanks for the great framework! Keep up the good work!

The presentations you've all shared helped me a lot to structure my talk from yesterday for DEV.BG. 
[Here](https://github.com/vesheff/talks/tree/master/2019/dev.bg%20-%20nest/server) is the repo with the demo I've made: 

[Presentation](https://github.com/nestjs/nest/files/3207010/Nestjs.-.dev.bg.pptx)

**Comment by vanessametonini** [comment]
Hi! Here the slides of my presentation about Nest in BrazilJS on the road Manaus. It is in Brazilian Portuguese 🇧🇷
https://pt.slideshare.net/vanessametonini/arquitetura-node-com-nestjs
