### ISSUE TITLE
When adding fastify graphql getting deprecation warning

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [nestjs/nest#10580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

 npm i @nestjs/graphql @nestjs/apollo graphql apollo-server-fastify

getting this

```
 apollo-server-fastify@3.11.1: The `apollo-server-fastify` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
```

### Minimum reproduction code

test

### Expected behavior

Need proper instructions how to act further

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/graphql

### Packages versions

```json
"@nestjs/apollo": "^10.1.6",
        "@nestjs/graphql": "^10.1.6",
        "@nestjs/common": "^9.2.0",
        "@nestjs/config": "^2.2.0",
        "@nestjs/core": "^9.2.0",
        "@nestjs/mapped-types": "*",
        "@nestjs/terminus": "^9.1.3",
        "@nestjs/throttler": "^3.1.0",
        "@nestjs/websockets": "^9.2.0",
        "apollo-server-express": "^3.11.1",
        "apollo-server-fastify": "^3.11.1",
```

### Node.js version

16.5.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
See comment [here](https://github.com/nestjs/graphql/issues/2307#issuecomment-1190003338)
