### ISSUE TITLE
Cache Module doesn't accept store object and uses memory caching instead

### ISSUE THREAD

**Issue by Leichtwind** [nestjs/nest#10590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you pass store object to CacheModule, store is ignored and in-memory cache is used instead.

### Minimum reproduction code

https://github.com/Leichtwind/nestjs-typescript-starter-9kbyw9

### Steps to reproduce

1. `npm ci`
2. `npm start`
3. `curl localhost:3000`
4. Response is `Hello World!` instead of `Cached value`
5. There are no messages `Trying to get cache` or `Trying to set cache` in console

### Expected behavior

CacheModule uses passed store object

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```
[Nest Platform Information]
platform-express version : 9.2.0
schematics version       : 9.0.3
testing version          : 9.2.0
common version           : 9.2.0
core version             : 9.2.0
cli version              : 9.1.5
```

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10591
