### ISSUE TITLE
Expose REFLECTOR constant inside cache.interceptor.ts

### ISSUE THREAD

**Issue by latuconsinafr** [nestjs/nest#10592]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When I want to unit test my custom cache interceptor that extends the `CacheInterceptor` class, I want to stimulate what the `reflector.get()` method returned to test different kinds of behaviour based on the `CACHE_KEY_METADATA` (for example somewhere in my `trackBy` code as the same as the original CacheInterceptor `trackBy`): 

```js 
const cacheMetaData = this.reflector.get(CACHE_KEY_METADATA, context.getHandler()); 
```

Then I have to provide a mock reflector inside my unit test providers array. The first try was something like this:

```js
beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({
      providers: [
        HttpCacheInterceptor, // my custom class
        { provide: CACHE_MANAGER, useValue: mockedCacheManager },
        { provide: Reflector, useValue: mockedReflector },
      ],
    }).compile();

    httpCacheInterceptor =
      moduleRef.get<HttpCacheInterceptor>(HttpCacheInterceptor);
    cacheManager = moduleRef.get(CACHE_MANAGER);
    reflector = moduleRef.get<Reflector>(Reflector); // then i realized it always an empty object
  });
```
I realized it when I looked at the `cache.interceptor.ts` code and I saw that the reflector using `@Inject(REFLECTOR)` which is REFLECTOR is a constant value representing `'Reflector'`.

It was solved by changing the providers array into something like this:

```js
beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({
      providers: [
        HttpCacheInterceptor, // my custom class
        { provide: CACHE_MANAGER, useValue: mockedCacheManager },
        { provide: 'Reflector', useValue: mockedReflector },
      ],
    }).compile();

    httpCacheInterceptor =
      moduleRef.get<HttpCacheInterceptor>(HttpCacheInterceptor);
    cacheManager = moduleRef.get(CACHE_MANAGER);
    reflector = moduleRef.get('Reflector');
  });
```

### Describe the solution you'd like

Will it be possible for the REFLECTOR constant to be exposed as well as the CACHE_MANAGER? So, it will prevent some kind of hard code in the unit test (in case of the REFLECTOR constant name changes sometime in the future). 

### Teachability, documentation, adoption, migration strategy

Depiction of the unit test after this request will always refer to the constants (both the `CACHE_MANAGER` and `REFLECTOR`) would be as follows:

```js
beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({
      providers: [
        CustomCacheInterceptor, // custom cache interceptor
        { provide: CACHE_MANAGER, useValue: mockedCacheManager },
        { provide: REFLECTOR, useValue: mockedReflector },
      ],
    }).compile();

    httpCacheInterceptor =
      moduleRef.get<CustomCacheInterceptor>(CustomCacheInterceptor);
    cacheManager = moduleRef.get(CACHE_MANAGER);
    reflector = moduleRef.get(REFLECTOR);
  });
```

### What is the motivation / use case for changing the behavior?

The motivation for this feature request is to allow developers to make a consistent unit test regarding any class that extends the CacheInterceptor class.

**Comment by micalevisk** [comment]
@Gustrb PRs are more than welcome :)

**Comment by kamilmysliwiec** [comment]
AFAIR `'Reflector'` provider is registered with the `useExisting: Reflector` so overriding/mocking the `Reflector` provider should be OK (no need to directly reference 'Reflector').

**Comment by micalevisk** [comment]
Exposing that internal constant is just a way to ensure that our consumer code won't break in case on any change to that token. But yeah, this sounds odd. We should find a better way to circumvent this issue.

**Comment by jmcdo29** [comment]
In my opinion, this is one of the packages that we should pull out of common and make it its own integration, along with a few others, so that `common` and `core` are really the base necessities for using Nest and everything else can be added without worry of what else is in there. I've got a couple in mind that we could do for v10 if you're up for it, @kamilmysliwiec

**Comment by zanminkian** [comment]
> Will it be possible for the REFLECTOR constant to be exposed as well as the CACHE_MANAGER? So, it will prevent some kind of hard code in the unit test (in case of the REFLECTOR constant name changes sometime in the future).

The REFLECTOR constant's value is 'reflector'. It is widely used in `@nestjs/common` and other third-party package. Instead of `cache.interceptor.ts`, `@nestjs/core` should expose it.

I can't agree more about the opinion from @jmcdo29. Classes about cache in `@nestjs/common` should not update any more. Just release a new package `@nestjs/cache` and deprecate the CacheModule in `@nestjs/common`, because it's complex and harder and harder to use.

**Comment by jmcdo29** [comment]
> The REFLECTOR constant's value is 'reflector'. It is widely used in @nestjs/common and other third-party package. Instead of cache.interceptor.ts, @nestjs/core should expose it.

The use of the string `'REFLECTOR'` is a hack to get around the circular nature between `@nestjs/common` and `@nestjs/core` that would no longer be needed if we made `@nestjs/cache`, so there's really no need to expose it. Other libraries should be relying on the _class_ `Reflector` for injection, not the string token.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/11427
