### ISSUE TITLE
How to use @Options() prelighted http options method in controller to support other HTTP methods (Ex: DELETE, PATCH, PUT,POST))

### ISSUE THREAD

**Issue by indrasenakatam** [nestjs/nest#10598]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Nest js server enabled with express cors(). But how we can customise @Options() method as a preflighted req for any of the non simple req methods.
app.enableCors({ credentials: true, origin: true });

Example: https://github.com/expressjs/cors#enabling-cors-pre-flight
app.options('/products/:id', cors()) // enable pre-flight request for DELETE request
app.del('/products/:id', cors(), function (req, res, next) {
  res.json({msg: 'This is CORS-enabled for all origins!'})
})

How Nest js support to provide to customise the preflighted request.

And how we can expose these @Options preflighted method in NestSwagger.

And can you please share document how exactly @Options method works in Nest.

### Describe the solution you'd like

@Options() method can customise in controller to handle preflighted request and response at endpoint level along with CORS.

Nest js swagger can expose this method as preflighted method

### Teachability, documentation, adoption, migration strategy

Few API gateway's are allowed only what are the methods are available in swagger json file for that endpoint.
So for client browser raised preflighted OPTIONS http method not explicitly available in swagger.
so here we should have to find other alternatives.

### What is the motivation / use case for changing the behavior?

All kind of API definition gateways (based swagger YAML files) to easily import  and support without customization.

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)

**Comment by indrasenakatam** [comment]
Could you please provide some insights on @Opitons()
how to use and enhance in Nest. I have not found any reference or documentation in our Nest documentation.

It would be great if you share any of the reference form nest js how to use @Optios() in controller.

**Comment by micalevisk** [comment]
> how to use `@Options()` in controller.

It works just like any other router decorator, but you cannot use those decorators in the same controller's method.

In the worst case, you could retrieve the underlying http adapter from the `bootstrap` function and use it directly like `app.options('/', (req, res) => {})` and so on.
