### ISSUE TITLE
Durable provider scope wins over non durable.

### ISSUE THREAD

**Issue by vizio360** [nestjs/nest#10594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using durable providers, if a service has 2 dependencies, one durable and the other  still REQUEST scope but NON durable, the service inherits the REQUEST DURABLE scope. 

### Minimum reproduction code

https://github.com/vizio360/nestJSDurableProvidersIssue

### Steps to reproduce

See reproduction code

### Expected behavior

If there is at least one dependency with just REQUEST scope (non durable) the service should be REQUEST scope non durable as well.

REQUEST Scope non durable should win over REQUEST scope durable.

and I would expect the overall priority for scopes to be (high to low):
```
REQUEST non durable
REQUEST durable
DEFAULT
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.13.2
NPM Version    : 8.1.2 

[Nest CLI]
Nest CLI Version : 9.1.5 

[Nest Platform Information]
platform-express version : 9.2.0
schematics version       : 9.0.3
graphql version          : 10.1.6
testing version          : 9.2.0
apollo version           : 10.1.6
common version           : 9.2.0
core version             : 9.2.0
cli version              : 9.1.5
```

### Node.js version

16.13.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by vizio360** [comment]
I've removed the TRANSIENT scope from the expected overall scope priority as it is a special case as explained in the docs: https://docs.nestjs.com/fundamentals/injection-scopes#scope-hierarchy

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10698
