### ISSUE TITLE
An aggregator for kafka

### ISSUE THREAD

**Issue by mostafa8026** [nestjs/nest#10607]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm trying to implement a reply response pattern in which I publish a message to a topic listened to by several consumer groups. That means that they will all get the message as well as submit the response in the reply topic.
The problem is because they all respond to the same message, only the first received message in the reply topic shall be answered. The others will be discarded. Given that I know how many responses I should be getting on the reply topic(call that number-n), how can I make `ClientKafka` wait for n responses and then resolve the answer?

### Describe the solution you'd like

I would like to pipe the `reply` topic until all of them available, but It got only one.

```
async getAllResponses() {
    const result = await this._internalClientKafka.send(SharedPatterns.TEST_MULTI_TOPIC, {})
      .pipe(
        tap(data => {
          console.log(data)
        }),
        take(n),
      ).toPromise();

    return result;
  }
```

### Teachability, documentation, adoption, migration strategy

It's so easy to adopt this scenario, because it uses `rxjs` behind.

### What is the motivation / use case for changing the behavior?

As I mentioned above it is so useful to get all results from all the consumers.

**NOTE:** spring-kafka had this ability as mentioned in this issue: https://github.com/spring-projects/spring-kafka/issues/998#issuecomment-484966034

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
