### ISSUE TITLE
Fastify adapter not supporting new signature .listen([options][, callback]) - and thus nestjs can't work with iisnode (port is a string defining a named pipe)

### ISSUE THREAD

**Issue by e-dot** [nestjs/nest#10602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to use **NestJS** on an IIS server - with **iisnode** module, and with the **fastify** framework.

When run in iis, the nestjs application fails with error:
**r [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.**

I managed to run nestjs with iisnode and the express framework - passing and object to the listen() function:
```ts
const app = await NestFactory.create(AppModule);
await app.listen(process.env.PORT || 3000)
```

IISNode sets environment variable to a string containing a named pipe used to communicate between IIS and Node.

This should be working with fastify too - but it doesn't.

Looking at the source code (fastify-adapter.js line 96+), it seems than the adapter doesn't support the latest signature of listen() and forces port to be and integer :
```js
    listen(port, ...args) {
        const isFirstArgTypeofFunction = typeof args[0] === 'function';
        const callback = isFirstArgTypeofFunction ? args[0] : args[1];
        const options = {
            port: +port,
        };
        if (!isFirstArgTypeofFunction) {
            options.host = args[0];
        }
        return this.instance.listen(options, callback);
    }
```

Is there a way to set **full fastify listen options** from nest application ? i.e. like this:
```ts
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter()
  );
  await app.listen({ path: process.env.PORT });
```

Regards,

E.

### Minimum reproduction code

unavailable

### Expected behavior

Application should start and listen to port (either a TCP port like 3000 or a named pipe connected to IIS).

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

iisnode

### NestJS version

9.2.0

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v16.18.1
NPM Version    : 8.19.2

[Nest CLI]
Nest CLI Version : 9.1.5

[Nest Platform Information]
platform-express version : 9.2.0
schematics version       : 9.0.3
testing version          : 9.2.0
common version           : 9.2.0
core version             : 9.2.0
cli version              : 9.1.5

### Node.js version

16.18.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by e-dot** [comment]
Sorry I can't reproduce this issue outside of Windows/IIS/IISNode.

I **can provide a pull request though** - adapting the adapter is easy. 

Regards,

E.

**Comment by micalevisk** [comment]
PRs are more than welcomed 😄

**Comment by e-dot** [comment]
I'm working on a PR for this issue (adapt the fastify-adapter to support listenOptions parameter), but the issue is closed. 

Why is this issue closed?

Regards,

E.
