### ISSUE TITLE
Fresh CLI install missing webpack dependency

### ISSUE THREAD

**Issue by SWBennett06** [nestjs/nest#10609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Running through the First Steps guide, it looks like the generated package.json is missing an explicit Webpack dependency, throwing `Error: Cannot find module 'webpack'`. 

I referred to [this StackOverflow post](https://stackoverflow.com/a/72557939/4098761) and explicitly installed the dependency, after which `npm start` succeeded.

### Minimum reproduction code

NA

### Steps to reproduce

```sh
npm i -g @nestjs/cli
nest new nest-test
cd nest-test
npm start
```

### Expected behavior

The CLI should generate a functional application.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/cli

### NestJS version

9.0.0

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },
```

### Node.js version

14.19.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
the _first steps_ guide has no mention on webpack, so I didn't get why you expected that :thinking:

**Comment by micalevisk** [comment]
anyway

as you can see below, the fresh new app generated by the CLI depends on `ts-loader`, which depends on `webpack`. I didn't manage to reproduce your issue. 

![image](https://user-images.githubusercontent.com/13461315/204366713-08eb0187-2488-4b7b-a6d0-108b735447ce.png)
