### ISSUE TITLE
I also get the type error using override, but not using app.register

### ISSUE THREAD

**Issue by ufec** [nestjs/nest#10604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I also get the type error using override, but not using app.register

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-yffp2u?file=src%2Fmain.ts

### Steps to reproduce

```shell
npm i -g @nestjs/cli
nest new test_helmet
cd test_helmet
npm uninstall @nestjs/platform-express && npm install --save @nestjs/platform-fastify fastify @fastify/helmet
```

In my last issue, adapter.register(fastifyHelmet) app.register(fastifyHelmet) will get type error, but now only at this time adapter.register(fastifyHelmet) occurs type error

```ts
async function bootstrap() {
  const adapter = new FastifyAdapter();
  await adapter.register(fastifyHelmet); // error
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    adapter,
  );
  await app.register(fastifyHelmet); // success
  await app.listen(3000);
}
bootstrap();
```

### Expected behavior

`adapter.register(fastifyHelmet)` and `app.register(fastifyHelmet)` is ok

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```json
{
  "name": "nest-typescript-starter",
  "private": true,
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-fastify": "^9.2.0",
    "fastify": "^4.10.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.4",
    "@types/node": "^18.0.3",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.5",
    "@typescript-eslint/parser": "^5.30.5",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^28.1.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.5",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  },
  "overrides": {
    "@nestjs/platform-fastify": {
      "fastify": "$fastify"
    }
  }
}

```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
![image](https://user-images.githubusercontent.com/13461315/204096356-ba1d85ca-a41f-41ff-bc90-d806d0df6083.png)

please update your reproduction. It doesn't work.

I know that I could install the dependencies myself but:

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by ufec** [comment]
> ![image](https://user-images.githubusercontent.com/13461315/204096356-ba1d85ca-a41f-41ff-bc90-d806d0df6083.png)
> 
> please update your reproduction. It doesn't work.
> 
> I know that I could install the dependencies myself but:
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

I tried to install it, but it doesn't work

**Comment by micalevisk** [comment]
yeah, I know. I just open the reproduction you shared and it doesn't work, like I said
