### ISSUE TITLE
The Optional Depencies Injections so that it can be more compatiable with test

### ISSUE THREAD

**Issue by kusime** [nestjs/nest#10603]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently I am using prisma with Nest , and use jest to test around with them , but I Encounter an new problem when build a service , in the jest test file , 

  beforeEach(() => {
    // https://www.prisma.io/docs/guides/testing/unit-testing#dependency-injection
    // prepare the prisma context
    service = new UsersService(prismaMock);
  });

and the prismaMock type is DeepMockProxy<PrismaClient> , [ref](https://www.prisma.io/docs/guides/testing/unit-testing#singleton)

and in UsersService file , in the constructor 

  constructor(
    private readonly prisma: PrismaService, 
  ) {}

when normally , the injection can work correctly , since the PrismaService is what the service need ,
but , if I just claim the PrismaService in UsersService , the `service = new UsersService(prismaMock);`
will fail , and the test will direcltly fail since the type check is failed 

 error TS2345: Argument of type 'DeepMockProxy<PrismaClient<PrismaClientOptions, never, RejectOnNotFound | RejectPerOperation | undefined>>' is not assignable to parameter of type 'PrismaService'.

so , I am trying to claim the test type , in UsersService file , in the constructor 

  constructor(
    private readonly prisma: PrismaService | DeepMockProxy<PrismaClient>,
  ) {}

and this can work with test , however , in the normal case , the injector will be confused so it throw 

ERROR [ExceptionHandler] Nest can't resolve dependencies of the TodosService (?). Please make sure that the argument Object at index [0] is available in the PrismaModule context.

Potential solutions:
- If Object is a provider, is it part of the current PrismaModule?
- If Object is exported from a separate @Module, is that module imported within PrismaModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

So I wonder if there is a good solution in this case , so that we don't have to modify the constructor again and again when testing

### Describe the solution you'd like

Is there possiable to use some thing to determine where this Injection is test enviroment or the production enviroment , so that both test and the production will not fail 

Maybe use the parameter decorator to describe the dependencies ? 

### Teachability, documentation, adoption, migration strategy

if this can be achieve , the user will not manually change the constructor again and again between test the development 

### What is the motivation / use case for changing the behavior?

Increase the smart with the enviroment detection

**Comment by micalevisk** [comment]
```ts
Test.createTestingModule({
  providers: [
    UserService,
    { provide: PrismaService, useValue: prismaMock }
  ]
})
```

isn't this what you're trying to achieve?

---

- https://github.com/jmcdo29/testing-nestjs: A repository to show off to the community methods of testing NestJS including Unit Tests, Integration Tests, E2E Tests, pipes, filters, interceptors, GraphQL, Mongo, TypeORM, and more!
- [Advanced Testing Strategies with Mocks in NestJS](https://trilon.io/blog/advanced-testing-strategies-with-mocks-in-nestjs)

**Comment by kusime** [comment]
> 

OMG ! that's work , Thanks !! previously , I tried with 

Test.createTestingModule({
  providers: [
    UserService,
    { provide: 'PrismaService", useValue: prismaMock }
  ]
})

but the above not work , so i give up to think about build the custom provider ...

**Comment by micalevisk** [comment]
```ts
providers: [ FooService ]
// The above is the same as doing
providers: [ { provide: FooService, useClass: FooService } ]
```

so you have a provider with the token `FooService` (which is the class reference), not `"FooService"`. That's why.
