### ISSUE TITLE
Cannot inject fastifyInstance if fastify version is different from @nestjs/platform-fastify

### ISSUE THREAD

**Issue by WhiteKiwi** [nestjs/nest#10611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

@nestjs/platform-fastfiy has a strong fastify 4.9.2 dependence. If the installed fastify version is different from @nestjs/platform-fastfiy, there will be a type error.
I think this should go into peer dependencies. I would like to ask if there is a history that has not been added as a peer.

![image](https://user-images.githubusercontent.com/32415680/204456701-9fb02ecb-21a3-4150-8b41-3864fe7ea055.png)

### Minimum reproduction code

https://github.com/WhiteKiwi/nestjs-fastify-peer-issue

### Steps to reproduce

1. pnpm install
2. open src/main.ts

### Expected behavior

no typeerror

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.0

### Packages versions

```json
{
	"dependencies": {
	  "@nestjs/common": "^9",
	  "@nestjs/config": "^2",
	  "@nestjs/core": "^9",
	  "@nestjs/mongoose": "^9.1.0",
	  "@nestjs/platform-fastify": "^9",
	  "@nestjs/swagger": "^6",
	  "fastify": "^4"
	}
  }
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
