### ISSUE TITLE
Failed retries do not work in EventPattern handlers with Kafka transport

### ISSUE THREAD

**Issue by tooleks** [nestjs/nest#10617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The issue is related to https://github.com/nestjs/nest/issues/4241, https://github.com/nestjs/nest/pull/9293, and https://github.com/nestjs/nest/pull/9586.

`KafkaRetriableException` introduced in https://github.com/nestjs/nest/pull/9586 works well with `MessagePattern`, but doesn't work as expected with `EventPattern` handlers: the errors are ignored and the retries are not initiated.

Upon further investigation, we have located the issue in the following lines. https://github.com/nestjs/nest/blob/eb5c2d2a6746cd3b7b4d538bf4dd25f925b50194/packages/microservices/listeners-controller.ts#L100

Looks like the `eventHandler` wrapper above doesn't wait for the execution of the next handler in the chain, so the promise in `handleEvent` below is resolved before all of the event handlers in the chain complete the execution. 

https://github.com/nestjs/nest/blob/eb5c2d2a6746cd3b7b4d538bf4dd25f925b50194/packages/microservices/server/server-kafka.ts#L302

We have tried to patch the existing code like this which seems to resolve the issue.

```TypeScript
const eventHandler: MessageHandler = async (...args: unknown[]) => {
  const originalArgs = args;
  const [dataOrContextHost] = originalArgs;
  if (dataOrContextHost instanceof RequestContextHost) {
    args = args.slice(1, args.length);
  }
  const originalReturnValue = proxy(...args);
  const returnedValueWrapper = eventHandler.next?.(
    ...(originalArgs as Parameters<MessageHandler>),
  );
  returnedValueWrapper?.then((returnedValue) =>
    this.connectIfStream(returnedValue as Observable<unknown>),
  );

  const originalValue = await originalReturnValue;
  if (returnedValueWrapper) {
    const returnedValue = await returnedValueWrapper;
    if (isObservable(originalValue) && isObservable(returnedValue)) {
      return merge(originalValue, returnedValue);
    } else if (isObservable(returnedValue)) {
      return returnedValue;
    }
  }

  return originalReturnValue;
};
```

Can somebody take a look at this and review the proposed solution (I'm no `rxjs` expert)? I can help with a PR once receive some feedback or the green light on the implementation.

### Minimum reproduction code

https://github.com/tooleks/nestjs-kafka-retries

### Expected behavior

Errors thrown during `eachMessage` execution should be passed to `kafkajs`.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```json
{
  "name": "nestjs-kafka-retries",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.2.1",
    "@nestjs/platform-express": "^9.0.0",
    "kafkajs": "^2.2.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

16.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in this PR https://github.com/nestjs/nest/pull/11020

**Comment by tooleks** [comment]
Awesome! Thanks a lot, @kamilmysliwiec.
