### ISSUE TITLE
Request: Add next page button in the documentation

### ISSUE THREAD

**Issue by dennyX7** [nestjs/nest#10624]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I think, this helps many developers to navigate to next page with the less cursor movement. But, that way, the users can stay more time in the documentation pages. 

### Describe the solution you'd like

Add the next & previous page buttons in the documentation, it helps for quick movement over the docs.

### Teachability, documentation, adoption, migration strategy

This issue is related to documentation.  I think this helps in better documenation.

### What is the motivation / use case for changing the behavior?

For better user mobility.

**Comment by dennyX7** [comment]
<img width="1512" alt="Screenshot 2022-12-01 at 4 09 47 PM" src="https://user-images.githubusercontent.com/79908607/205032487-41e8215c-dd93-4710-8bad-b2efa04ece13.png">

Adding the sample screenshot for some reference.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/issues/192
