### ISSUE TITLE
How to test nest locally to contribute ?

### ISSUE THREAD

**Issue by cyril-lakech** [nestjs/nest#1062]
Hi,

I did some code on Nest to contribute.

I would like to test my local nest version to check if it working well.

How to use the cats sample with my local nest code ?

Which commands to use lerna/npm etc ?

I don't want to run test, I want to run a sample app with the local nest code modifier by myself. I modifier common/core modules only.

**Comment by cyril-lakech** [comment]
thanks @shekohex

**Comment by kamilmysliwiec** [comment]
Just to confirm,`npm run build` will build your local codebase and automatically replace the old bundle inside all examples/integration tests with the latest build.
