### ISSUE TITLE
Out-of-the-box support for `Explorer` pattern

### ISSUE THREAD

**Issue by tolgap** [nestjs/nest#10629]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I seem to be repeating myself regularly when doing an `Explorer` pattern. Here are some of the scenarios:

- `WorkerExplorer` to register my own queue/worker pattern (does not use `@nestjs/bull`
- `WebhookHandlerExplorer` to automatically resolve webhooks to a certain provider

Especially the Webhook logic has been rewritten often.

### Describe the solution you'd like

I would like it if NestJS could abstract this `Explorer` pattern to a common abstract class.

Something like:

```ts
const MY_WEBHOOKS_KEY = 'MY_WEBHOOKS_KEY'

// `@Explorer` provided by NestJS
@Explorer(MY_WEBHOOKS_KEY)
export class WebhookHandlerExplorer implements NestExplorer {}

// `createExplorerDecorator` provided by NestJS
const WebhookHandler = createExplorerDecorator(MY_WEBHOOKS_KEY);

@WebhookHandler('customer_create')
export class MyHandler {}

@Module({
  providers: [MyHandler],
})
export class MyHandlersWebhook {}
```

Where Nest would register these `@Explorer` providers automatically, and use them during module initialisation to look for other providers that have been marked with `MY_WEBHOOKS_KEY` metadata.

### Teachability, documentation, adoption, migration strategy

See above. This is an extremely rough idea. I thought I'd propose it to see if anyone has thought of something similar, and maybe even has a better API design in mind.

### What is the motivation / use case for changing the behavior?

High repetition. Even within `@nestjs` packages themselves, like `@nestjs/graphql` and `@nestjs/bull`.

**Comment by karthik2265** [comment]
hey @tolgap could you please explain a bit about explorer pattern or point me towards a resource to understand it.

**Comment by tolgap** [comment]
@karthik2265 here's an example of an Explorer that searches through all providers and filters them based on metadata: https://github.com/nestjs-shopify/nestjs-shopify/blob/a12bdfb9b10412f2dcba395fbf126d5a9626c64b/packages/webhooks/src/webhooks.explorer.ts

Or the one from `@nestjs/bullmq` to register queues/workers: https://github.com/nestjs/bull/blob/0ca489b93f36a330131b40d176c2c030d976518e/packages/bullmq/lib/bull.explorer.ts

**Comment by Flusinerd** [comment]
This sounds like a great community library. 
But I think, that this is too specific for the main nestjs repository.
Are there any other frameworks out there that provide this implementation out of the box?

**Comment by kamilmysliwiec** [comment]
That's what I came up with thus far:

```typescript
const WebhookHandler = DiscoveryService.createDecorator<{ name: string }>();

@WebhookHandler({ name: 'my-webhook' })
export class MyWebhook {}
```

and then in the explorer class:

```typescript
const webhooks = discoveryService.getProviders({
  metadataKey: WebhookHandler.KEY,
});
webhooks.forEach(wrapper => {
  // type-safe
  const { name } = discoveryService.getMetadataByDecorator(
    WebhookHandler,
    wrapper,
  );
  console.log(name);
});
```

cc @tolgap

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12107

**Comment by tolgap** [comment]
@kamilmysliwiec didn't want to add an unnecessary comment on the PR itself, but I went through the proposed solution and this is exactly what I was looking for 🔥.
