### ISSUE TITLE
Dependency Injection for a Config Token.

### ISSUE THREAD

**Issue by bokzor** [nestjs/nest#10634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a really simple use case that should work (in my opinion) but that doesn't.

I have a Dynamic Module that declares a "Config Token"

And a Service that depends on that token. 

It seems the service is not able to resolve that dependency.

```
@Global()
@Module({})
export class QuoteCommonBrokerModule {
    static register(options: QuoteBrokerModuleOptions) {
        return {
            module: QuoteCommonBrokerModule,
            providers: [
             { provide: KAFKA_CONFIG_TOKEN, useValue: options.kafkaConfig },
               KafkaHealthCheck
            ],
            exports: [KafkaHealthCheck],
        };
    }
}
```

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-ha7qrt?file=src/app.module.ts

### Steps to reproduce

npm i
npm start

### Expected behavior

Dependency should be accessible in the dependency tree

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : Linux 5.0
NodeJS Version : v16.14.2
NPM Version    : 7.17.0 

[Nest CLI]
Nest CLI Version : 9.0.0 

[Nest Platform Information]
platform-express version : 9.0.0
schematics version       : 9.0.0
testing version          : 9.0.0
common version           : 9.0.0
core version             : 9.0.0
cli version              : 9.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

As workaround, I created a small service containing the config.

```
         {
                    provide: KafkaConfigService,
                    useFactory: () => {
                        return new KafkaConfigService(options.kafkaConfig);
                    },
                },
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
