### ISSUE TITLE
Add ways to access mercurius instance to create hooks ? 

### ISSUE THREAD

**Issue by julestruong** [nestjs/nest#10631]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm having this issue described here . https://github.com/Eomm/mercurius-logging/issues/7

I can't use a plugin , i have this error 

```
backend   | AssertionError [ERR_ASSERTION]: The dependency 'mercurius' of plugin 'mercurius-logging' is not registered
backend   |     at /usr/src/app/node_modules/fastify/lib/pluginUtils.js:64:5
backend   |     at Array.forEach (<anonymous>)
backend   |     at Object.checkDependencies (/usr/src/app/node_modules/fastify/lib/pluginUtils.js:63:16)
backend   |     at Object.registerPlugin (/usr/src/app/node_modules/fastify/lib/pluginUtils.js:135:21)
backend   |     at Boot.override (/usr/src/app/node_modules/fastify/lib/pluginOverride.js:28:57)
backend   |     at Plugin.exec (/usr/src/app/node_modules/avvio/plugin.js:79:33)
backend   |     at Boot.loadPlugin (/usr/src/app/node_modules/avvio/plugin.js:272:10)
backend   |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

If i understand correctly, i should register mercurius, but its already done under the hood by nestjs so i'm quite confused

### Describe the solution you'd like

I would like to be able to add hooks for mercurius https://github.com/mercurius-js/mercurius/blob/master/docs/hooks.md

Something like this =>https://github.com/Davide-Gheri/nestjs-mercurius#hooks

Just a simple decorator 
```
import { GraphQLHook } from 'nestjs-mercurius';

@Injectable()
export class HookService {
  @GraphQLHook('preValidation')
  async onPreValidation(schema: GraphQLSchema, source: DocumentNode, context: any) {
   //...
  }
}
``` 

### Teachability, documentation, adoption, migration strategy

Well  i would reuse this 

## Hooks

Register mercurius hooks as service methods, using the `@GraphQLHook()` decorator

```typescript
import { GraphQLHook } from 'nestjs-mercurius';
@Injectable()
export class HookService {
  @GraphQLHook('preValidation')
  async onPreValidation(schema: GraphQLSchema, source: DocumentNode, context: any) {
   //...
  }
}
```

### What is the motivation / use case for changing the behavior?

I'm just adding a behavior, to be able to create or use plugins like theses 

https://github.com/mercurius-js/mercurius/blob/master/docs/plugins.md

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
