### ISSUE TITLE
Dynamic Module cannot resolve dependencies, Please make sure that the argument dependency at index [0] is available in the *Module context.

### ISSUE THREAD

**Issue by conspireagency** [nestjs/nest#10677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I followed the course / documentation regarding dynamic modules, but I feel like something may be missing.  In the service of the dynamic module it's complaining that it cannot resolve the options dependency injected as part of the dynamic module ie.

`@Inject(MODULE_OPTIONS_TOKEN) private options: AuthModuleOptions`

Where AuthModuleOptions is the interface (in the docs "ConfigModuleOptions").

![Screen Shot 2022-12-07 at 4 03 53 PM](https://user-images.githubusercontent.com/29992361/206323667-fc6302f7-f04f-4f4b-a485-09aac18bf95f.png)

Perhaps besides the point, but as some background I'm trying to create a reusable module hosted on npm (AuthModule).

### Minimum reproduction code

https://github.com/conspireagency/nestm-shopify

### Steps to reproduce

1. New nest instance
2. Import dynamic module from npm and add it to the AppModule, something like this

`
AuthModule.registerAsync({

      imports: [ConfigModule],

      useFactory: (configService: ConfigService) => ({

        cookie: configService.get('TOP_LEVEL_OAUTH_COOKIE'),

        secret: configService.get('SHOPIFY_SECRET'),

        scopes: configService.get('SCOPES'),

      }),

      inject: [ConfigService],

    }),`
    
I've verified that without the @Inject of the module options that the other dependencies (Mikro Orm related) throw no errors / works fine.  It's only when I try to inject the options passed in that it throws an error.

Wondering if perhaps these options still need to be in providers in the dynamic module like the screenshot below from the documentation?  In the examples that show extending ConfigurableModuleClass however, this does not seem to be the case.

![Screen Shot 2022-12-07 at 4 08 05 PM](https://user-images.githubusercontent.com/29992361/206324272-0d25c3c3-f39e-4a10-9467-452c8ec050c2.png)

### Expected behavior

Should be able to access options injected / passed in without throwing an error unable to resolve the dependency (options).

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json

```

### Node.js version

17.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
you got a circular dependency at import level. Read the FAQ page.

**Comment by conspireagency** [comment]
@micalevisk got it, thanks.  Yeah having AppModule imported into the dynamic module was just me messing around because noting seemed to work.
