### ISSUE TITLE
App crashes if StreamableFile stream has error mid-stream

### ISSUE THREAD

**Issue by garrettjstevens** [nestjs/nest#10681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using a `StreamableFile`, if the stream has an error after the stream has already started piping to the response, the app crashes. Here is the error that is displayed before the crash:

```
_http_outgoing.js:561
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (/home/garrett/Playground/stream-crash-repro/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/home/garrett/Playground/stream-crash-repro/node_modules/express/lib/response.js:174:12)
    at StreamableFile.handleError (/home/garrett/Playground/stream-crash-repro/node_modules/@nestjs/common/file-stream/streamable-file.js:15:21)
    at Transform.<anonymous> (/home/garrett/Playground/stream-crash-repro/node_modules/@nestjs/platform-express/adapters/express-adapter.js:44:22)
    at Object.onceWrapper (events.js:520:26)
    at Transform.emit (events.js:412:35)
    at Transform.afterTransform (internal/streams/transform.js:94:17)
    at Transform.transform [as _transform] (/home/garrett/Playground/stream-crash-repro/dist/app.service.js:29:17) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

I ran into this because I am using an `Transform` to transform a stream of database results into a text document that is then sent to the user with `StreamableFile`. If there is an error processing the first "chunk" of the stream, the app handles it as expected. If the error happens on subsequent chunks, though, the app crashes. It looks like `StreamableFile`'s error handler is trying to set something on the response after the response has already started.

### Minimum reproduction code

https://github.com/garrettjstevens/nest-stream-crash-repro

### Steps to reproduce

```bash
$ npm install
$ npm run start
$ curl http://localhost:3000
```

See that the app has crashed.

### Expected behavior

I expected the app to not crash, and probably log an error.

I understand that since the success status and headers have already been sent (since the stream has already started) when this error happens, there's not really an easy way for NestJS to signal to the client that there was a problem with the stream, so I don't expect anything like that. I'll handle checking for prematurely terminated streams in my client app.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```
[Nest Platform Information]
platform-express version : 9.2.1
schematics version       : 9.0.3
testing version          : 9.2.1
common version           : 9.2.1
core version             : 9.2.1
cli version              : 9.1.5
```

### Node.js version

14.20.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
![image](https://user-images.githubusercontent.com/13461315/206355165-e7a4fde2-f616-4630-9147-f89a837713d0.png)

did you missed the `return` or `else` clause in there? After adding, the error I got was 'Error: synthetic error'

**Comment by garrettjstevens** [comment]
Oops, yes, I forget the `return`, thanks for checking. I've added it to the reproduction repo. I'm still seeing the app crash even with the `return` added, though.

**Comment by micalevisk** [comment]
cc @jmcdo29 :eyes: 

I'm not confident on using `isHeadersSent` on the default handler because it's property defined by Express. So if we had any other HTTP adapter other than express/fastify, it won't work.

I tested that with the fastify adatper and the app didn't crash because it handles that scenario properly.

**Comment by garrettjstevens** [comment]
For anyone else who needs a workaround for now, I'm using the express adapter and was able to use @micalevisk's suggestion and make my own error handler like this that seems to work:

```js
return new StreamableFile(stream).setErrorHandler((err, res) => {
  if (res.destroyed) {
    return
  }
  if (res.headersSent) {
    res.end()
    return
  }
  res.statusCode = 400
  res.send(err.message)
})
```

**Comment by kamilmysliwiec** [comment]
cc @jmcdo29 🤔

**Comment by jmcdo29** [comment]
Man! I've missed this in the chaos of the new year and events that happened in December for me! So sorry about that! I think adding in the `headersSent` check works well, thanks @micalevisk. This entire handler is only currently used on the express path, because as long as a buffer or stream is returned, fastify handles that internally so we just use `StreamableFile` for the headers there and return the stream without the error handler. 

I should update the docs to make that part clearer. So yeah, if we want to make use of the `headersSent` to manage this lets do it.

**Comment by micalevisk** [comment]
I'm a bit concerd on how that would work for 3rd-party HTTP adapters :thinking:

**Comment by jmcdo29** [comment]
> I'm a bit concerned on how that would work for 3rd-party HTTP adapters thinking

That depends on if they even implement a handler for the `StreamableFile` in the first place. [Node's `ServerResponse` object has the `headersSent` property already anyways, so long as they extend from that and expose it in some way it should be fine](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#responseheaderssent)

**Comment by Tony133** [comment]
I discussed this on Discord with Jay and brought it to his attention, but if we did it like this:
```
  protected handleError: (
    err: Error,
    response: StreamableHandlerResponse,
  ) => void = (err: Error, res) => {
    if (!res.destroyed) {
      res.statusCode = 400;
      return err.message;
    }
  };
```
Would it be wrong?

**Comment by jmcdo29** [comment]
@Tony133 If we just `return error.message` then the callback won't ever be hit here
https://github.com/nestjs/nest/blob/0e0e24b522ac99d7cca650a953dbcccd63092cbe/packages/platform-express/adapters/express-adapter.ts#L85-L95

`body.errorHandler` is what ends up sending off the response. in some cases. If we just `return err.message` then no response will be sent
https://github.com/nestjs/nest/blob/0e0e24b522ac99d7cca650a953dbcccd63092cbe/packages/common/file-stream/streamable-file.ts#L15-L23

We're just adding in more checks to make sure that we don't send a response if the response is already sent.

**Comment by Tony133** [comment]
Okay, I must have missed this 😄. Anyway ok thanks for the response.
