### ISSUE TITLE
Refering to issue 10675

### ISSUE THREAD

**Issue by zetti-caletti** [nestjs/nest#10688]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Refering to issue #10675 but can't answer anymore -.-
@kamilmysliwiec What I want to have is not an extra feature or something. You just have to implement to allow other HTTP-Methods for the SSE-Handler. So instead of only being able to map it to GET I also want to be able to map it against POST or DELETE or the others, like I can do on every Controller-Method with the Get, Post, etc.-Decorators. This has nothing todo with a logic change. Actually I have more Use-Cases for using Server-Sent-Events with POST-Method instead of GET-Method.

Such features like the SSe-Decorator or others I wouldn't map it generally to a specific HTTP-Method. The one who decides which HTTP-Method is used should be only the user of the framework.

So I map for example: @Sse('setup, 'post'), so NestJs maps this SSE-Handler to POST-Method. 
And then I can inject the post payload with @Body-Decorator and the rest is exactly the same like now.
Would be great to have this :+1: 

### Describe the solution you'd like

-

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

-

**Comment by micalevisk** [comment]
Sorry but I still didn't get what do you want us to do here since you said that this is not a feature. 🤔

**Comment by zetti-caletti** [comment]
I want to be able to use Server-Sent-Events for POST and DELETE Requests. Am I missing something or maybe you can tell me how I can achieve this? NestJs uses GET-Method for SSE for default and how can I change this?

**Comment by zetti-caletti** [comment]
Server-Sents-Events define a "protocal" on how a server can send events to a client. It's independent from the HTTP-Method you call this endpoint. So that's why I don't understand it why I can't change the HTTP-Request-Method. Or at least I don't know how to do it.

**Comment by zetti-caletti** [comment]
Actually I don't know whats that hard to understand my "feature"/question. Are you all kidding me? thinking

**Comment by zetti-caletti** [comment]
Look: SSe-Decorator uses GET-Request-Method as the default. To change it to POST-Method, I tried to use the POST-Decorator additionally. But it doesn't work:
![Screenshot_20221212_115942](https://user-images.githubusercontent.com/75048883/207029270-98c584cd-975c-445b-9adf-48165d885943.png)

![Screenshot_20221212_120044](https://user-images.githubusercontent.com/75048883/207029290-e94f78fe-0f46-4b69-830d-0f0afaf178e7.png)

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
