### ISSUE TITLE
Add explicit ts-node cache directory

### ISSUE THREAD

**Issue by agung-wete** [nestjs/nest#1070]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When start in dev mode, is not easy to find transpiled file 

## Expected behavior

Explicit directory. Maybe save to `tmp/tscache` directory.

## Minimal reproduction of the problem with instructions

> nodemon.json: 
> `"exec": "ts-node -r tsconfig-paths/register --cacheDirectory tmp/tscache src/main.ts",`

## What is the motivation / use case for changing the behavior?

For performance reason, debugging, research, etc.

**Comment by kamilmysliwiec** [comment]
I believe that we shouldn't force a user to use not-default configuration options by default. Let's leave the choice to the programmer
