### ISSUE TITLE
Conditionally register paths inside a controller

### ISSUE THREAD

**Issue by Gxmadix** [nestjs/nest#10700]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We can't hide new paths and feature, that are still in development.
```
export class FeatureController {
  constructor(protected readonly service: FeatureService) {}
  // ...

  @Post('not-released-yet')
  async notReleasedYet() {
    return this.service.notReleasedYet();
  }

  @Get('not-released-yet')
  async notReleasedYet() {
    return this.service.notReleasedYet();
  }
}
```

### Describe the solution you'd like

We can add a second optional argument to Post, Get etc...

```
export class FeatureController {
  constructor(protected readonly service: FeatureService) {}
  // ...

  @Post('not-released-yet', process.env !== 'production')
  async notReleasedYet() {
    return this.service.notReleasedYet();
  }

  @Get('not-released-yet', someConfition())
  async notReleasedYet() {
    return this.service.notReleasedYet();
  }
}
```

### Teachability, documentation, adoption, migration strategy

I am not sure of my self, since there could be hidden effects I am not aware of.
We can add a second optional parameter to the [RequestMethods](https://github.com/nestjs/nest/blob/master/packages/common/decorators/http/request-mapping.decorator.ts), default to true.
And not do the mapping inside `createMappingDecorator`  when this condition is falsy.

```
const createMappingDecorator =
  (method: RequestMethod) =>
  (path?: string | string[], active: boolean): MethodDecorator => {
    if (!active) return;
    return RequestMapping({
      [PATH_METADATA]: path,
      [METHOD_METADATA]: method,
    });
  };
```

### What is the motivation / use case for changing the behavior?

Dynamically register paths easily and manage multi environments, release versions...

**Comment by micalevisk** [comment]
the route is registered but is just 'hidden' from the client side That's the only fault I could see on that approach. Which might actually be good as you problably don't want to have multiple handler for the same routes while developing 

But yeah, your use case is easily handled by that guard as well

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
