### ISSUE TITLE
Wrong nullable QueryFail

### ISSUE THREAD

**Issue by PatrykKuniczak** [nestjs/nest#10715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I create Entity and i create a record from Data Grip and when i start nestjs app i have error

### Minimum reproduction code

https://github.com/PatrykKuniczak/memesChat/tree/liveChat

### Steps to reproduce

npm i
npm run start:dev

### Expected behavior

Script start, when data in DB is right, compatibile with entity

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/typeorm

### NestJS version

9.0.0

### Packages versions

```json
[System Information]
OS Version     : Windows 10
NodeJS Version : v16.16.0
NPM Version    : 8.1.4 

[Nest CLI]
Nest CLI Version : 9.1.5

[Nest Platform Information]
platform-socket.io version : 9.2.1
platform-express version   : 9.2.1
mapped-types version       : 1.2.0
websockets version         : 9.2.1
schematics version         : 9.0.3
testing version            : 9.2.1
typeorm version            : 9.0.1
common version             : 9.2.1
config version             : 2.2.0
core version               : 9.2.1
cli version                : 9.1.5
```

### Node.js version

16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

https://github.com/PatrykKuniczak/Machine-Shop-Manager/tree/main/backend

```ts
import {Column, Entity, PrimaryGeneratedColumn} from "typeorm";


@Entity('PersonalDatum')
export class PersonalDatum {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({length: 50})
    name: string;

    @Column({length: 50})
    surname: string;

    @Column({length: 50})
    birthCity: string;

    @Column("timestamp with time zone")
    birthDate: Date;
}
```

![image](https://user-images.githubusercontent.com/64608510/205310460-6c1df72d-1c22-46b4-9a7d-6ae9c6c13012.png)

![image](https://user-images.githubusercontent.com/64608510/205310695-f6a55c19-3f31-494d-80dc-73df6e002dfd.png)

"QueryFailedError: column "birthDate" of relation "PersonalDatum" contains null values"

I using Postgresql

I have the same issue in my next project 

![image](https://user-images.githubusercontent.com/64608510/206906978-518a2557-93e4-420c-80eb-0e69b9f7135c.png)

```ts
@Entity("User")
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ length: 20 })
  clientId: string;

  @Column({ length: 60 , default: ""})
  name: string;
}
```
"QueryFailedError: column "clientId" of relation "User" contains null values"

Whole Error: 
```
QueryFailedError: column "clientId" of relation "User" contains null values
    at PostgresQueryRunner.query (F:\Projects\memesChat\backend\src\driver\postgres\PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PostgresQueryRunner.executeQueries (F:\Projects\memesChat\backend\src\query-runner\BaseQueryRunner.ts:651:13)
    at PostgresQueryRunner.addColumn (F:\Projects\memesChat\backend\src\driver\postgres\PostgresQueryRunner.ts:1115:9)
    at PostgresQueryRunner.addColumns (F:\Projects\memesChat\backend\src\driver\postgres\PostgresQueryRunner.ts:1129:13)
    at RdbmsSchemaBuilder.addNewColumns (F:\Projects\memesChat\backend\src\schema-builder\RdbmsSchemaBuilder.ts:823:13)
    at RdbmsSchemaBuilder.executeSchemaSyncOperationsInProperOrder (F:\Projects\memesChat\backend\src\schema-builder\RdbmsSchemaBuilder.ts:226:9)
    at RdbmsSchemaBuilder.build (F:\Projects\memesChat\backend\src\schema-builder\RdbmsSchemaBuilder.ts:95:13)
    at DataSource.synchronize (F:\Projects\memesChat\backend\src\data-source\DataSource.ts:318:9)
    at DataSource.initialize (F:\Projects\memesChat\backend\src\data-source\DataSource.ts:256:43)

^C  at DataSource.synchronize (F:\Projects\memesChat\backend\src\data-source\DataSource.ts:318:9)
```

I'd try do it but still didn't work:
```ts
  @Column({ length: 60 , nullable: true})
  name?: string;
```

That's intresting 
```
create table "User"
(
    id         serial
        constraint "PK_9862f679340fb2388436a5ab3e4"
            primary key,
    name       varchar(60) not null,
    "clientId" varchar(20) not null
);

alter table "User"
    owner to postgres;
```

"nullable" work wrong, intresting, that's something wrong after last update

I set "nullable" to 'false' run, and for 'true' and DDL looks fine 
```
name       varchar(60)
```

but error appear when i start script 
```
column "clientId" of relation "User" contains null values         
```
![image](https://user-images.githubusercontent.com/64608510/206909770-987aebb6-7568-4bc0-875d-b82356e4cc7b.png)

I create issue in Typeorm repository, but my bad is I didn't test it without Nest, yesterday i do it, and it's work with pure Typeorm, that's intresting, that's must be something wrong with 9 version of @nestjs/typeorm.
Because earlier i didn't have error like that

That's the issue what I've told:
https://github.com/typeorm/typeorm/issues/9587

I copy and paste, everything but maybe it's also helpful.

On reproduction code, i send a github with my second project, because it's less code and relations, easier to test :)
But my first project is on the first line

I open to send more details :)

**Comment by micalevisk** [comment]
please share the steps to reproduce this issue, your project is too big. What's the line that triggers that error?

I don't think this is related with nestjs at all, tho.

**Comment by PatrykKuniczak** [comment]
I send minimum reproduction:

https://github.com/PatrykKuniczak/memesChat/tree/liveChat

Look at this again, this is soo much smaller

I think it's related with nest, because on pure typeorm, this error didn't occur in the same Entity

**Comment by micalevisk** [comment]
which operation triggers that error?

**Comment by PatrykKuniczak** [comment]
I create this data with DataGrip, u have screen shots, u have also Entity, Can see "default" property, then for test script. 

```
Steps to reproduce:

Go src/database/config/typeorm.config.ts 
and paste ur "DB_URL"

and src/main.ts 
and paste "PORT"

Don't need to use configService, just paste :)

npm i
npm run start:dev
CTRL + C interrupt
```

Later create data inside User table

![image](https://user-images.githubusercontent.com/64608510/206906978-518a2557-93e4-420c-80eb-0e69b9f7135c.png)

Something like this, left "name" empty for default ""
And "npm run start:dev" then u can see this error 

Or u can use Postman or Something for run socket.io event:

![image](https://user-images.githubusercontent.com/64608510/207388227-581bc458-bbef-4a73-a145-3d1019b85436.png)

![image](https://user-images.githubusercontent.com/64608510/207385893-05abdc7d-b00b-463e-add3-724152a125bf.png)

and only connect, 1 time or 2, every connect create user

Then "npm run start:dev" and u can see error

Yeah, u right, my steps from earlier it's too little for run this app.

**Comment by PatrykKuniczak** [comment]
@micalevisk let's clone now, i done something wrong in code, clone again now :)

**Comment by micalevisk** [comment]
you could create a new post on discord to discuss that

If it's something on executeQueries, than I don't see how it could be related with nest :thinking: 

but I didn't investigate that yet.

**Comment by PatrykKuniczak** [comment]
@micalevisk Ok, i will do it now

**Comment by PatrykKuniczak** [comment]
The problem, is "solved" i generate new nestJs app, and copy my src, error didn't occure anymore.

That's crazy issue, IDN what's wrong, computers is a big mistery :)

Thanks @micalevisk for support :)
