### ISSUE TITLE
Remove stack trace (noise) from NestJS errors output

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#10722]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm pretty sure that the most common user-facing error message from Nest is the _'Nest can't resolve dependencies of ...'_

Let's look at some real example of such error:

![image](https://user-images.githubusercontent.com/13461315/207738131-b3b6184e-2322-466c-9100-f34bc5f7cd95.png)

Look at that, newcomers might not understand why a stacktrace is being printed out since all it has is nestjs internal details that clearly won't help them to solve the error.

The text message highlighted red is enough. All the rest seems to be just noise.

If we have disabled coloring (`NO_COLOR=true`), we'll got this:

![image](https://user-images.githubusercontent.com/13461315/207738524-fb71064a-c533-4311-933c-8b09f405ec5c.png)

again, to much text for such a simple & commom issue.

I believe that most of the time one will have to scroll up the terminal window a bit so him/she could fully grasp what's the error.

---

I didn't manage to work around that on our side since the `UnknownDependenciesException` is caught by the exception zone. Even after changing `abortOnError` is changed to `false`, but I'm unsure if this is expected or not :thinking: 

https://github.com/nestjs/nest/blob/eebb976b2240ac389dd61c3f81478553abfdeac5/packages/core/nest-factory.ts#L175-L180

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/13461315/207738746-1d98c37e-ec51-4183-82ce-798fe323d473.png)

the highlighted text above should not be displayed by default.

At same time, those details might be useful when debugging nestjs internals. So they should be displayed when the debug mode is enabled (`NEST_DEBUG=true`).

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

Errors handled by NestJS are leaking useless stack traces, which could be annoying for people that are facing them often.

**Comment by kamilmysliwiec** [comment]
This is just a regular `console.error`. Do you think we should hide this by default? AFAIR other frameworks/libraries like React/Angular etc print that information too

**Comment by micalevisk** [comment]
I found that this is due to the following line:

https://github.com/nestjs/nest/blob/eebb976b2240ac389dd61c3f81478553abfdeac5/packages/core/errors/exception-handler.ts#L12

If we omit the `stack` arg, we'll have this output:

https://github.com/nestjs/nest/blob/eebb976b2240ac389dd61c3f81478553abfdeac5/packages/common/services/console-logger.service.ts#L79

since `NEST_DEBUG` is beign used only in `@nestjs/core`, can I open a PR chaging that to introduce the proposed feature only for `UnknownDependenciesException` (for now)?

**Comment by kamilmysliwiec** [comment]
Let me repeat my question 😄 Do you think we should hide this by default? AFAIR other frameworks/libraries like React/Angular etc print that information too. To me, it looks somewhat odd that an application crashes without printing a stack trace.

**Comment by micalevisk** [comment]
Fair enough

**Comment by micalevisk** [comment]
And this is feasiable already by having using the following logger instead:

```ts
import { ConsoleLogger } from '@nestjs/common';

export class MyLogger extends ConsoleLogger {
  error(message: any, stack?: string, context?: string) {
    if (context === 'ExceptionHandler' && message.includes("can't resolve dependencies")) {
      super.error(message, context);
    } else {
      super.error(message, stack, context);
    }
  }
}

// ...

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    logger: new MyLogger,
  })
}
```
