### ISSUE TITLE
Support for multiple request type decorators on a single controller method

### ISSUE THREAD

**Issue by MarcoLeko** [nestjs/nest#10730]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Whenever we want to handle `@Get() @Head()` requests method types per controller method, it does not work to set both annotations on the same method. Meaning whenever we have such a use case:

```ts
    @Head()
    @Get()
    @Render('irgendwas')
    root(): {
        return irgendwas;
    }
```

The @Get() will not be work. The solution for this is to create dedicated class methods per request type annotation:

```ts
    @Head()
    @Render('irgendwas')
    head(): {
        return irgendwas;
    }


    @Get()
    @Render('irgendwas')
    get(): {
        return irgendwas;
    }
```

Trying out nestjs utility function `applyDecorators` like this:

```ts
export function GetOrHead(path?: string | string[]) {
  return applyDecorators(Head(path), Get(path));
}


  // controller
  @GetOrHead()
  getHello(@Req() req): string {
    return this.appService.getHello();
  }

```

Does also not seem to work...Would it be possible to provide multiple desired request method decorators on one single method? 
For completeness, I provided a reproducible environment to play around: https://stackblitz.com/edit/github-a6k6yn-pzzug6?file=src/app.controller.ts

If you would like to do `HEAD` requests open up the console from the output page and do this:

```js
const options = {method: 'GET'};
let res = await fetch('https://githuba6k6yn3vxnnp-cdud--3001.local-credentialless.webcontainer.io/foo', options);
``` 
Tests have been added to check if head & get request method type are handled as expected.

### Describe the solution you'd like

To set multiple request method type decorators on a single method. This is especially useful for get/head request types.

### Teachability, documentation, adoption, migration strategy

No input on this, but would highly appreciate your opinion.

### What is the motivation / use case for changing the behavior?

The motivation is to keep the declarative approach by decorators and not to declare multiple class methods for a get/head request handling.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
