### ISSUE TITLE
Get request returns old data directly

### ISSUE THREAD

**Issue by bdlover3** [nestjs/nest#10733]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

9.1.2

### Describe the regression

Get request returns old data directly  after a POST UPDATE

### Input code

```ts
`import { Body, Controller, Get, Param, Post, Req } from "@nestjs/common"
import { NoAuth } from "src/common/decorater/customize"
import { IndexService } from "./index.service"

@Controller("index")
export class IndexController {
  constructor(private indexService: IndexService) {}
  

  @NoAuth()
  @Post("getLocationList")
  async getLocationList() {
    const result = await this.indexService.getLocationList()
    console.log(result[0])
    return result
  }
  @Post("addLocation")
  async addLocation(@Body() bd) {
    return await this.indexService.addLocation(bd)
  }
  @Post("saveLocation")
  async saveLocation(@Body() bd) {
    const result = await this.indexService.saveLocation(bd)
    return result
  }
  @Post("delLocation")
  async deLocation(@Body() id){
    return await this.indexService.delLocation(id)
  }
}
`
```

### Expected behavior

there is my code ：

nestjs returns  the old data directly when the  "GET" "getLocationList" request 
"saveLocation"  goes well
when i trace it 
getLocationList() does not execute and nestsjs return statuscode 200 with old data 

last 2-3 second 

POST method is ok

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

If you believe this is a bug please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
