### ISSUE TITLE
function app.useCors() not handling preflight requests properly

### ISSUE THREAD

**Issue by pMattheew** [nestjs/nest#10735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When it is used the preflight requests are sent to the application by a client browser and being returned with a response of 404, what makes the browser to block the original request to be done in the application. 

It only happens using `app.useCors()` function. My function was like this: 

```
   app.enableCors({
      origin: "*",
      credentials: true,
      allowedHeaders: "*",
      optionsSuccessStatus: 200,
   })
```
[main.ts](https://github.com/pMattheew/forfaitbank-api/commit/4521c9c85030204222040795114656ed549b99b9)

After days having troubles with this I tried to change, I moved this options to the `app.create()` function and it worked, like this:

```
	const app = await NestFactory.create(AppModule, {
		cors: {
			origin: "*",
			credentials: true,
			allowedHeaders: "*",
			optionsSuccessStatus: 200,
		},
	});
```
[main.ts](https://github.com/pMattheew/forfaitbank-api/commit/5e8a31031b9cef73cb9f5d136fa07fa2bde8d7c8)

I have my NestJS API hosted on Vercel, so initially I thought that it was a problem with Vercel, but when I changed it it started working.

And how my controller isn't configured to handle OPTIONS requests this error is thrown, here is a log output from Vercel when I try to do a request to it:

![image](https://user-images.githubusercontent.com/99044724/208095091-a328d281-b320-4d45-bec2-9192eb20aab7.png)

I made a Stackblitz showing the error with a simple Angular app, where I took two URLs, one with the buggy code and another after I solved it, and I've put two buttons to make requests to them.

### Minimum reproduction code

https://stackblitz.com/edit/angular-ivy-pzz3pc?devToolsHeight=33&file=src/app/app.component.ts

### Expected behavior

It is expected that using the function `app.useCors()` has the same effect of using cors options in `app.create(..., { cors: true } )` function: to it handle the preflight request correctly returning a 200 status code to process the original client request.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.5

### Packages versions

```

{
  "name": "forfaitbank-api",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prisma:dev:deploy": "prisma migrate deploy",
    "db:dev:up": "docker compose --project-directory=./prisma/ up dev-shadow-db -d",
    "db:dev:rm": "docker compose --project-directory=./prisma/ rm dev-shadow-db -s -f -v",
    "db:dev:restart": "npm run db:dev:rm && npm run db:dev:up && sleep 1 && npm run prisma:dev:deploy",
    "prisma:test:deploy": "npx env-cmd -f ./test/.env.test prisma migrate deploy",
    "db:test:up": "docker compose --project-directory=./test/ up test-db -d",
    "db:test:rm": "docker compose --project-directory=./test/ rm test-db -s -f -v",
    "db:test:restart": "npm run db:test:rm && npm run db:test:up && sleep 3 && npm run prisma:test:deploy",
    "db:test:studio": "npx env-cmd -f ./test/.env.test -- prisma studio",
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "pretest:e2e": "npm run db:test:up && sleep 3 && npm run prisma:test:deploy && sleep 1",
    "test:e2e": "npx env-cmd -f ./test/.env.test -- jest --watch --no-cache --config ./test/jest-e2e.json",
    "posttest:e2e": "npm run db:test:rm",
    "pretest:db:e2e": "npm run db:test:up",
    "test:db:e2e": "npx env-cmd -f ./test/.env.test -- jest database.e2e-spec.ts --watch --no-cache --config ./test/jest-e2e.json",
    "posttest:db:e2e": "npm run db:test:rm",
    "ci:e2e": "npm run pretest:e2e && npx env-cmd -f ./test/.env.test -- jest app.e2e-spec.ts --no-cache --config ./test/jest-e2e.json",
    "postci:e2e": "npm run db:test:rm",
    "preci:db:e2e": "npm run db:test:up",
    "ci:db:e2e": "npx env-cmd -f ./test/.env.test -- jest database.e2e-spec.ts --no-cache --config ./test/jest-e2e.json",
    "postci:db:e2e": "npm run db:test:rm"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@prisma/client": "^4.7.1",
    "argon2": "^0.30.2",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "env-cmd": "^10.1.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.0.0",
    "@types/passport-jwt": "^3.0.7",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "pactum": "^3.3.1",
    "prettier": "^2.3.2",
    "prisma": "^4.7.1",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
