### ISSUE TITLE
[Fastify] Compression does not work in exception filter

### ISSUE THREAD

**Issue by sgrigorev** [nestjs/nest#10736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Client receives nothing if a response is quite big and if it is sent from exception filter. Also there is error in logs
```
"err":{"type":"Error","message":"premature close","stack":"Error: premature close\n    at onclosenexttick (/Users/sgrigorev/Projects/nestjs-compress-issue/node_modules/end-of-stream/index.js:54:86)\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"},"msg":"premature close"}
```

### Minimum reproduction code

https://github.com/sgrigorev/nestjs-compress-issue

### Steps to reproduce

See readme in reproduction code

### Expected behavior

Client must not receive empty response if compression is enabled

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```json
    "@fastify/compress": "^6.2.0",
    "@nestjs/common": "^9.2.1",
    "@nestjs/core": "^9.2.1",
    "@nestjs/platform-fastify": "^9.2.1",
    "fastify": "^4.10.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

1. Compression works if you run fastify without nestjs
2. It works if you decrease response payload.
3. It works if response is sent from controller

There was a similar [issue](https://github.com/fastify/fastify-compress/issues/215) with "Premature close" error in the @fastify/compress library. It might be related.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
