### ISSUE TITLE
Cache interceptor wrong ttl argument

### ISSUE THREAD

**Issue by riccardotornesello** [nestjs/nest#10755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the cache interceptor, the arguments passed to `cacheManager.set` are `[key, response, { ttl }]` while, according to NestJS and cache-manager documentation it should be `[key, response, ttl]` (ttl as third argument instead of an object containing options).

This is the line https://github.com/nestjs/nest/blob/ada4921b51bab2eb2ecc2de797aba91679296133/packages/common/cache/interceptors/cache.interceptor.ts#L58

### Minimum reproduction code

NO

### Expected behavior

From cache-manager's Store type: `set<T>(key: string, data: T, ttl?: Ttl): Promise<void>;`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
