### ISSUE TITLE
Circular dependency displays generic message that doesn't help.

### ISSUE THREAD

**Issue by dav1app** [nestjs/nest#10758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
console.error
    Error: A circular dependency has been detected. Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()".
```

I'm considering a bug since it is expected from the log to help. The current state of the log doesn't give meaning to the log itselft.

### Minimum reproduction code

https://docs.nestjs.com/fundamentals/circular-dependency

### Steps to reproduce

- Literally any circular dependency error.

node_modules/@nestjs/core/injector/container.js:102:19

### Expected behavior

 Use `moduleRef._metatype.name` and its current `provider.name` to give some hint on where the circular dependency is coming from. 
 
 console.error
    Error: A circular dependency has been detected on modules  TrainingModule  <-> UpdateTrainingService. They reference each other. Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()".

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"@nestjs/core": "^7.6.15",
```

### Node.js version

latest

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
you're using nestjs v7. We won't add any feature to versions other than v9.

Have you tried to reproduce this in v8? I could tried that out if you share a minimum repro of it.

btw [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by dav1app** [comment]
Hi @micalevisk. I will work on that later on. ETA 2d. Is that ok to keep this issue open? 

Feel free to drop it for any pointy-haired metrics.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
