### ISSUE TITLE
Way to intercept static files

### ISSUE THREAD

**Issue by tamtakoe** [nestjs/nest#10759]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Example:
I use NestJS app with `ServeStatic` module or `useStaticAssets` (Express loader) in my SPA.
I want to intercept index.html and change it or use other file, but there is no way how to do it by NestJS

Middleware, interceptor or controller show me response without file name or content (eg: https://github.com/tamtakoe/nestjs-demo).

### Describe the solution you'd like

My solution is to add file info inside response or at least use file handler inside ServeStatic module or some other way

### Teachability, documentation, adoption, migration strategy

```
// inside interceptor/middleware/controller
if (res.filename === 'index.html') {
  // do smth
}
```
or
```
// inside controller
@Get('file:index.html')
```
or
```
// inside module
ServeStaticModule.forRoot({
    rootPath: join(__dirname, '../src/static'),
    intercept: (res) => {
      if (res.filename === 'index.html') {
        // do smth
      }
   }
})
```

### What is the motivation / use case for changing the behavior?

E.g. If you need to show special file for each user or include config etc. into index.html

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
