### ISSUE TITLE
Global interceptor not catch errors

### ISSUE THREAD

**Issue by Karman40** [nestjs/nest#10751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I created an interceptor to save the LOGs. I created the app module and set the provider, but I find that when there are errors (4xx/5xx), these errors are not caught by catchError.

```
providers: [
  {provide: APP_INTERCEPTOR, useClass: LoggingInterceptor},
]
```

```
return next
  .handle()
  .pipe(
    catchError(err => {
      console.error(err);
      return throwError(() => err);
    }),
    tap(async (res) => {
      console.log(res);
    })
 );
```

### Minimum reproduction code

https://codesandbox.io/s/cranky-aj-j3phdh?file=/src/app.module.ts

### Expected behavior

catch errors

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```
[System Information]
OS Version     : Windows 10
NodeJS Version : v16.18.1
NPM Version    : 9.1.2 

[Nest CLI]
Nest CLI Version : 9.1.5

[Nest Platform Information]
platform-socket.io version : 9.2.1
platform-express version   : 9.2.1
websockets version         : 9.2.1
schematics version         : 9.0.3
throttler version          : 3.1.0
mongoose version           : 9.2.1
schedule version           : 2.1.0
testing version            : 9.2.1
common version             : 9.2.1
config version             : 2.2.0
axios version              : 1.0.0
bull version               : 0.6.2
core version               : 9.2.1
cli version                : 9.1.5
```

### Node.js version

16.18.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Where's the error being thrown in your reproduction?

**Comment by Karman40** [comment]
@jmcdo29 I do not understand the question.
A non-existent URL is also sufficient, the 404 error, but no log.

https://j3phdh.sse.codesandbox.io/error

**Comment by jmcdo29** [comment]
Interceptors bind to route handlers that *exist*. The creation of the 404 is not a part of the route handlers that you create, so the `APP_INTERCEPTOR` that is bound to your server never gets triggered. If you want to handle those errors you can use the [Exception Filter](https://docs.nestjs.com/exception-filters)

**Comment by Karman40** [comment]
Oh, I see, thank you.

If the route exists, do I have to use "Exception filters" in that case as well? So there is an existing route and let's say authentication fails.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
