### ISSUE TITLE
Please share Nestjs Release/support schedule details.

### ISSUE THREAD

**Issue by thangaraja** [nestjs/nest#10754]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It would be nice to have a page where we can see roadmap along with end up life for Nestjs releases. 

Examples:
https://github.com/nodejs/release#release-schedule
https://angular.io/guide/releases#actively-supported-versions
https://angular.io/guide/releases#release-schedule

This will give an idea of how long a version can be used in production and plan for next version upgrade

### Describe the solution you'd like

THere is a site https://endoflife.date/ where we can see end-of-life details for the software. This also provides details as API. 

https://endoflife.date/angular
https://endoflife.date/api/angular.json

### Teachability, documentation, adoption, migration strategy

THere is a site https://endoflife.date/ where we can see end-of-life details for the software. This also provides details as API. 

https://endoflife.date/angular

### What is the motivation / use case for changing the behavior?

Help the user to plan the software upgrade.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/2670#issuecomment-516280615
