### ISSUE TITLE
Live reload: EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by ArnaudDenoyelle** [nestjs/nest#10752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In a NX context, just after creating a new project, trying to save a file results in a EADDRINUSE error instead of live-reload

Seems to happen only if the project is created with Nx. I can't reproduce it in a pure Nest repo

### Minimum reproduction code

https://github.com/ArnaudDenoyelle/nest-EADDRINUSE

### Steps to reproduce

Create a project `npx create-nx-workspace@latest acme --preset=nest --appName=api --nxCloud=false`
Go to the project directory `cd acme`
Start the server with `nx serve api`
Modify a like in `app.service.ts` and save

### Expected behavior

The server should live reload and changes should be applied

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

create-nx-workspace

### NestJS version

9.2.1

### Packages versions

```
npx nest info

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : Linux 5.15
NodeJS Version : v14.20.0
NPM Version    : 6.14.17 

[Nest CLI]
Nest CLI Version : 9.1.5 

[Nest Platform Information]
platform-express version : 9.2.1
schematics version       : 9.0.3
testing version          : 9.2.1
common version           : 9.2.1
core version             : 9.2.1

```

### Node.js version

14.20.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

code/acme [ nx serve api

> nx run api:serve

chunk (runtime: main) main.js (main) 2.78 KiB [entry] [rendered]
webpack compiled successfully (c16c5b6c32515b78)
Debugger listening on ws://localhost:9229/9c46216f-3036-424a-8df9-c153cb93a633
For help, see: https://nodejs.org/en/docs/inspector
Type-checking in progress...
[Nest] 23693  - 12/25/2022, 3:03:41 PM     LOG [NestFactory] Starting Nest application...
[Nest] 23693  - 12/25/2022, 3:03:41 PM     LOG [InstanceLoader] AppModule dependencies initialized +20ms
[Nest] 23693  - 12/25/2022, 3:03:41 PM     LOG [RoutesResolver] AppController {/api}: +4ms
[Nest] 23693  - 12/25/2022, 3:03:41 PM     LOG [RouterExplorer] Mapped {/api, GET} route +2ms
[Nest] 23693  - 12/25/2022, 3:03:41 PM     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 23693  - 12/25/2022, 3:03:41 PM     LOG 🚀 Application is running on: http://localhost:3333/api
No errors found.
chunk (runtime: main) main.js (main) 2.78 KiB [entry] [rendered]
webpack compiled successfully (008a4af9381bfd9b)
Starting inspector on localhost:9229 failed: address already in use
No errors found.
[Nest] 23799  - 12/25/2022, 3:04:08 PM     LOG [NestFactory] Starting Nest application...
[Nest] 23799  - 12/25/2022, 3:04:08 PM     LOG [InstanceLoader] AppModule dependencies initialized +23ms
[Nest] 23799  - 12/25/2022, 3:04:08 PM     LOG [RoutesResolver] AppController {/api}: +4ms
[Nest] 23799  - 12/25/2022, 3:04:08 PM     LOG [RouterExplorer] Mapped {/api, GET} route +2ms
[Nest] 23799  - 12/25/2022, 3:04:08 PM     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 23799  - 12/25/2022, 3:04:08 PM   ERROR [NestApplication] Error: listen EADDRINUSE: address already in use :::3333 +2ms
(node:23799) UnhandledPromiseRejectionWarning: Error: listen EADDRINUSE: address already in use :::3333
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at ExpressAdapter.listen (/home/arnaud/code/acme/node_modules/@nestjs/platform-express/adapters/express-adapter.js:78:32)
    at /home/arnaud/code/acme/node_modules/@nestjs/core/nest-application.js:167:46
    at new Promise (<anonymous>)
    at NestApplication.listen (/home/arnaud/code/acme/node_modules/@nestjs/core/nest-application.js:156:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23799) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23799) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ArnaudDenoyelle** [comment]
Seems to be an NX problem only. I can fix it by downgrading @nrwl related dependencies to 15.3.3

Opened a new issue at NX here : https://github.com/nrwl/nx/issues/14017

**Comment by gyenabubakar** [comment]
In 2025 and I'm facing this issue! Live reload crashes because the port is already taken.

**Comment by micalevisk** [comment]
@gyenabubakar please share a reproduction that does not uses Nx

**Comment by gyenabubakar** [comment]
@micalevisk 

For some reason I couldn't reproduce it. Live reload is working normal now.

**Comment by petertoth-dev** [comment]
Exactly the same issue here @gyenabubakar and it just started from the blue. There's definitely an issue with live reloading and killing the previous instance

Some logs:

```
[STARTUP]


[6:40:08 PM] Starting compilation in watch mode...

[6:40:14 PM] Found 0 errors. Watching for file changes.

[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [NestFactory] Starting Nest application...
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +6ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] UserIdentityVerificationModule dependencies initialized +26ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] StorageModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] IdentityModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] LocationsModule dependencies initialized +0ms


DB QUERIES....


[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +47ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] UsersModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] FilesModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [InstanceLoader] VisitsModule dependencies initialized +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RoutesResolver] AppController {/}: +4ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RoutesResolver] AuthController {/auth}: +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/auth/register, POST} route +1ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/auth/login, POST} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/auth/logout, POST} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RoutesResolver] UsersController {/users}: +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/users/:userId, GET} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RoutesResolver] IdentityController {/verifications/identity}: +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/verifications/identity/request/:userId, POST} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/verifications/identity/response, POST} route +1ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RoutesResolver] LocationsController {/locations}: +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/locations/search, GET} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/locations/:id, GET} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RoutesResolver] VisitsController {/visits}: +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/visits, POST} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/visits/:userId, GET} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/visits/:id, DELETE} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/visits/:id, PUT} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RoutesResolver] FilesController {/files}: +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [RouterExplorer] Mapped {/files, POST} route +0ms
[Nest] 390286  - 09/04/2025, 6:40:15 PM     LOG [NestApplication] Nest application successfully started +2ms



[RELOAD]

[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +47ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] UsersModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] FilesModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [InstanceLoader] VisitsModule dependencies initialized +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RoutesResolver] AppController {/}: +4ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RoutesResolver] AuthController {/auth}: +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/auth/register, POST} route +1ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/auth/login, POST} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/auth/logout, POST} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RoutesResolver] UsersController {/users}: +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/users/:userId, GET} route +1ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RoutesResolver] IdentityController {/verifications/identity}: +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/verifications/identity/request/:userId, POST} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/verifications/identity/response, POST} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RoutesResolver] LocationsController {/locations}: +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/locations/search, GET} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/locations/:id, GET} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RoutesResolver] VisitsController {/visits}: +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/visits, POST} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/visits/:userId, GET} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/visits/:id, DELETE} route +1ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/visits/:id, PUT} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RoutesResolver] FilesController {/files}: +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [RouterExplorer] Mapped {/files, POST} route +0ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 390455  - 09/04/2025, 6:42:06 PM   ERROR [NestApplication] Error: listen EADDRINUSE: address already in use 0.0.0.0:3000 +0ms
```

UPDATE:

This will a race-condition issue somewhere. Sometimes randomly works sometimes throws the error between reloads. Usually always the second try works strenghtening my theoiry this is a race condition issue.

**Comment by eightHundreds** [comment]
Don't let `cursor` start your service

**Comment by Sweet-KK** [comment]
I think this isn't just an issue with Nx; I encountered it after using pnpm workspaces as well, but it doesn't occur in a standalone Next.js project.
