### ISSUE TITLE
Allow KafkaJS MSK IAM integration

### ISSUE THREAD

**Issue by florian-besser** [nestjs/nest#10777]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As of KafkaJs `2.2.0` they support a new way to connect:
https://www.npmjs.com/package/@jm18457/kafkajs-msk-iam-authentication-mechanism

Specifically, they can specify `sasl` like so:
```
sasl: {
    mechanism: Type,
    authenticationProvider: awsIamAuthenticator(process.env.REGION, process.env.TTL)
  }
```

Since we use NestJS (which wraps KafkaJs) as well as AWS Kafka I wanted to make use of this feature. I wrote the following code:
```
import {
  awsIamAuthenticator,
  Type,
} from '@jm18457/kafkajs-msk-iam-authentication-mechanism';
```
and
```
let sasl: SASLOptions = {
        mechanism: Type,
        authenticationProvider: awsIamAuthenticator(
          process.env.AWS_REGION,
          '900',
        ),
      };
```

This threw me the following error:
`TS2322: Type '"AWS_MSK_IAM"' is not assignable to type '"plain" | "scram-sha-256" | "scram-sha-512" | "aws" | "oauthbearer"'.`
As it turns out the NestJS `SASLOptions` does not yet accept this new mechanism, and TS type safety is letting me know.

### Describe the solution you'd like

I have solved the problem like so:
```
let sasl: SASLOptions  = {
        mechanism: Type,
        authenticationProvider: awsIamAuthenticator(
          process.env.AWS_REGION,
          '900',
        ),
        // This ugly cast is done as NestJS does not seem to support KafkaJS new mechanism yet, should be fixed in the future.
      } as unknown as SASLOptions
```
As you can see from the cast and comment I'm not terribly happy **but this does work successfully**

My preferred solution would be an update to the TS types of NestJS/microservices to avoid me having to use `as` for workarounds.

### Teachability, documentation, adoption, migration strategy

NestJS AFAIK does not yet have specific documentation for integrating with AWS MSK through IAM. I can provide my code snippets as documentation but I'm unsure whether NestJS would really be interested in that - I figure such detailed documentation would be better placed unter the KafkaJS library, where it already exists anyway, e.g. at https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism/tree/main/example

### What is the motivation / use case for changing the behavior?

Type-safety is good, but needs to be up-to-date. If KafkaJS allows a new type then NestJS should also allow that.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this? Updating types should be sufficient to fix this one

**Comment by florian-besser** [comment]
I am happy to do so; right now I'm still trying to get things working properly.
I've raised https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism/issues/20 as we're seeing disconnects after some time. Still trying to figure out if that is an issue with config, on the AWS MSK auth or on KafkaJs.

**Comment by abhishekmatta999** [comment]
> If anyone is facing the issue.
> 
> I am able to use it by
> 
> ```
> sasl: createMechanism({
>     region: process.env.AWS_REGION,
> }) as unknown as SASLOptions,
> ```
> 
> It seems weird for casting it to SASLOptions instead of Mechanism. But for me it works.

Could you please share the screenshot of the whole configuration you set?
