### ISSUE TITLE
Use async functions in nest generate resource CLI

### ISSUE THREAD

**Issue by ericsj** [nestjs/nest#10780]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

**First feature:**
When using `nest g resource` command, the functions in the controllers and services are synchronous, but normally we invoke async functions in the services. So, instead of:

```
  @Post()
  create(@Body() createServiceCategoryDto: CreateServiceCategoryDto) {
    return this.serviceCategoryService.create(createServiceCategoryDto);
  }
```
It would make more sense:
```
  @Post()
  async create(@Body() createServiceCategoryDto: CreateServiceCategoryDto) {
    return await this.serviceCategoryService.create(createServiceCategoryDto);
  } 
```
The same applies to the generated service
**Second feature:**
It would be interesting an option to not generate the entity file, since Prisma ORM uses a different approach

### Describe the solution you'd like

**First feature**
Controller example:
```
  @Post()
  async create(@Body() createServiceCategoryDto: CreateServiceCategoryDto) {
    return await this.serviceCategoryService.create(createServiceCategoryDto);
  } 
```
Service example:
```
  async create(createServiceCategoryDto: CreateServiceCategoryDto) {
    return 'This action adds a new serviceCategory';
  }
```
**Second feature**
`nest g resource --no-entity`

### Teachability, documentation, adoption, migration strategy

either changing the default command `nest g resource` or adding an option `nest g resource --async-methods`

### What is the motivation / use case for changing the behavior?

Every time I use the command I need to manually add the async keyword

**Comment by micalevisk** [comment]
there's no reason to use `return await` since there's no `catch` clause.

This was taken by PR https://github.com/nestjs/schematics/pull/1163 but Kamil complains about having `async` with no `await`.
