### ISSUE TITLE
NestJs Server going into loops of incremental compilation.

### ISSUE THREAD

**Issue by dikshantbansal-covetrus** [nestjs/nest#10785]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

"@nestjs/apollo": "^10.1.7" , "@nestjs/graphql": "^10.1.7"

### Describe the regression

The NestJs server is depicting continuous file changes in this version and going into loops of incremental compilation. This issue is coming after updating the NestJs versions.

NestJs and GraphQL Versions used -
"@graphql-tools/mock": "^8.7.14",
    "@nestjs/apollo": "^10.1.7",
    "@nestjs/axios": "^1.0.0",
    "@nestjs/common": "^9.2.1",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.2.1",
    "@nestjs/graphql": "^10.1.7",
    "@nestjs/platform-express": "^9.2.1",
    "@nestjs/swagger": "^6.1.4",
    "@nestjs/terminus": "^9.1.4",

### Input code

```ts

```

### Expected behavior

Server should not go into loops of incremental compilation.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
