### ISSUE TITLE
validate field with enum strings in nestjs

### ISSUE THREAD

**Issue by praveentoby** [nestjs/nest#10784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

my enum is as follows
export enum Timezones  {
    'Europe/Andorra',
    'Asia/Dubai',
    'Asia/Kabul',
    'America/Antigua'
}
and my dto file i have 
 @IsEnum(Timezones, { each: true })
  timezone: Timezones[];
  
  but when i make a request like 
  {
"timezone" : "xyz"
}
its not validating

### Minimum reproduction code

https://gitlab-v2.ams-sbx.blv.cloud/backstage-ads/believe

### Expected behavior

it should throw error saying xyz is not accepted

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

{
  "name": "backstage-ads",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"apps/**/*.ts\" \"libs/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{core,shared,apps,libs,test}/**/*.ts\" --fix",
    "test:service-campaigns:unit": "jest --config ./apps/service-campaigns/test/jest-unit.json",
    "test:service-campaigns:integration": "jest --config ./apps/service-campaigns/test/jest-integration.json",
    "test:service-stats:unit": "echo 'no unit test for service-stats'",
    "test:service-stats:integration": "jest --config ./apps/service-stats/test/jest.json",
    "test:service-push-google-ads:unit": "echo 'no unit test for service-push-google-ads'",
    "test:service-push-google-ads:integration": "jest --config ./apps/service-push-google-ads/test/jest.json",
    "console:export-campaigns": "ts-node -r tsconfig-paths/register apps/service-stats/src/console.ts export campaigns"
  },
  "dependencies": {
    "@elastic/elasticsearch": "^7.15.0",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/typeorm": "^9.0.0",
    "cache-manager": "^4.1.0",
    "cache-manager-redis-store": "^2.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "facebook-nodejs-business-sdk": "^14.0.0",
    "google-ads-api": "^11.0.0",
    "mysql2": "^2.3.3",
    "nestjs-console": "^7.0.1",
    "papaparse": "^5.3.2",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.7"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/elasticsearch": "^5.0.40",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/papaparse": "^5.3.4",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": ".",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node",
    "roots": [
      "<rootDir>/apps/"
    ]
  }
}

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
