### ISSUE TITLE
Disable nats pingTimer by flag

### ISSUE THREAD

**Issue by andreyddk** [nestjs/nest#10783]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The debug message of nats server is annoying and its cant be disabled.
`DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".`

### Describe the solution you'd like

My propose it is extends the implementation existed flag `debug` of `MicroserviceOptions` for disable `pingTimer` message.

### Teachability, documentation, adoption, migration strategy

Example of usage.

```
const app = await NestFactory.createMicroservice<MicroserviceOptions>(
    AppModule,
    {
      transport: Transport.NATS,
      options: {
        servers: nats.servers,
        queue: TENANT_SERVICE_QUEUE,
        debug: false // its disable pingTimer message too.
      }
    }
  );
```

### What is the motivation / use case for changing the behavior?

Unnecessary logs in terminal result the problem with collect logs and understand it.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by andreyddk** [comment]
> Would you like to create a PR for this?

Yea, sure. I will make it soon.

**Comment by andreyddk** [comment]
I guess I don't have permissions for make pull request.

`remote: Permission to nestjs/nest.git denied to andreyddk.
`

```
ERROR: Permission to nestjs/nest.git denied to andreyddk.
fatal: Could not read from remote repository.
```

**Comment by jmcdo29** [comment]
You should make a fork and push your code to it. Then make a PR from your fork to this repo. Pretty standard through most Open Source projects

**Comment by andreyddk** [comment]
> You should make a fork and push your code to it. Then make a PR from your fork to this repo. Pretty standard through most Open Source projects

Thank you, its done.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10798
