### ISSUE TITLE
Express is bout found when installing with pnpm

### ISSUE THREAD

**Issue by morbargig** [nestjs/nest#10808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My packages 
![DF87E1B3-FAA9-4D6B-8AE4-A8D4B0CB6CA2](https://user-images.githubusercontent.com/51287453/210864422-f21aa4a8-982e-4a4b-ab63-a641cb6e8b2b.jpeg)

When I run
pnpm i
nest start 

I get this error
![6D6601C9-6FB9-432D-AA3D-29B51FD20691](https://user-images.githubusercontent.com/51287453/210865938-a04a97a8-f197-4e9b-90cc-c530518a4ff2.jpeg)

When I run
npm i 
best start it working fine

### Minimum reproduction code

null

### Steps to reproduce

1. pnpm I
2. nest start

### Expected behavior

Just to get ride of the error in the current behavior 
Or just like running with npm i

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

~9.0.0

### Packages versions

```json
      
```

### Node.js version

~19.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by morbargig** [comment]
![6D6601C9-6FB9-432D-AA3D-29B51FD20691](https://user-images.githubusercontent.com/51287453/210865938-a04a97a8-f197-4e9b-90cc-c530518a4ff2.jpeg)

**Comment by micalevisk** [comment]
Have you tried to run it with tsc instead of webpack? 🤔 

Kind hard to understand what is the issue here since you didn't provide any useful info nor a repro. I know people that are using PNPM on their express app just fine.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
