### ISSUE TITLE
nest start --watch not reloading after changes (nest start --watch not working)

### ISSUE THREAD

**Issue by likesandy** [nestjs/nest#10802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

system: windows11 22H2
Node version: v18.12.1
@nestjs/cli: 9.1.8

use cli create project through `npm run start:dev` change file watch There is no effective(nest start --watch not working)

### Minimum reproduction code

none

### Expected behavior

none

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction). 

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by likesandy** [comment]
At first I thought it was a windows 11 problem, and had the idea of going from 11->10, but finally I found out **it was a node version problem**, I went from v18.x->v16.x and the problem no longer existed, overwatch was working fine.

**Comment by irakli2206** [comment]
I have the same issue. I don't think downgrading Node is a good solution for this.

**Comment by irakli2206** [comment]
> Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction).
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

I am using a completely untouched Nest project created using 'nest new' command.

**Comment by likesandy** [comment]
@micalevisk 
当我降低node版本的时候,程序正常运行,但当我使用nvm切换node18.x版本的时候,程序也可以正常运行了,这让我有点捉摸不透了

**Comment by likesandy** [comment]
@irakli2206 
When I lower the node version, the program runs normally, but when I use nvm to switch the node18.x version, the program can also run normally, which makes me a bit puzzled

**Comment by micalevisk** [comment]
I've been using node16 with NVM and the latest version of nestjs just fine on Linux.

There were some optimizations on tsc so there are scenarios on which the restart won't be made because nothing was changed.
