### ISSUE TITLE
Fresh Nest project has no live reload

### ISSUE THREAD

**Issue by irakli2206** [nestjs/nest#10828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I create a new Nest project with nest new command, I start up the app using npm run start:dev, and it starts successfully, but whenever I change something in the code, the app doesn't show the updates. The console just shows "Found 0 errors. Watching for file changes" and nothing happens.

### Minimum reproduction code

Default Nest project

### Steps to reproduce

1. npm run start:dev
2. Change something in the code

### Expected behavior

Live reload should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0 but also 8.0.0

### Packages versions

```json

```

### Node.js version

16 and 18

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
