### ISSUE TITLE
Suggestion: add this repository to some issue bounty program

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#10824]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

On [Discord](https://discord.gg/nestjs) (at `#contributing-to-nest` channel) a discussion regarding the life of the framework and its 'official' packages was arised.

It's 2023 and NestJS is growing :tada: But I notice few problems on its long-term health:

- @nestjs org has a lot of repositories (36), and
- there aren't enough people that could help on addressing issues on all of them (there are [359](https://github.com/issues?q=is%3Aissue+is%3Aopen+org%3Anestjs) open by now), and so
- old issues (and WIP PRs) are still open due to the lack of any direct investment on them

As popular its gets, more and more issues will be open ~ _I guess_.

Speaking for myself, as a happy maintainer, I've been using [this](https://github.com/users/micalevisk/projects/1/views/4) GitHub project to save Issues that I'm intersted to solve. _But_ since I'm doing that for free as a hobby, I don't find much time to dive into more complex ones. My priority are those that could fix an issue on apps that I'm working with.

### Describe the solution you'd like

To start, we could add only this repository into some kind of "issue bounty" program (for free) like https://issuehunt.io so anyone could fund open issues to encourage GitHub community to address them. Those kind of issues would have a dedicated label to help on identifying them (added by the bot of that program).

<details>
<summary>In case of IssueHunt, the issue would look like this:</summary>

![image](https://user-images.githubusercontent.com/13461315/211164788-2a6754e9-d8bf-4452-a187-9b809e82c23d.png)
![image](https://user-images.githubusercontent.com/13461315/211164795-d3d0751c-8e95-4e19-9b6d-e8869aa2ab5e.png)

</details>

<details>
<summary>and the repo on IssueHunt app would look like this:</summary>

![image](https://user-images.githubusercontent.com/13461315/211165565-30bd50d2-1861-47ef-8b05-5d95ddd83fe1.png)

</details>

I know that we could start supporting nestjs already via Open Collective but **I think** that that system doesn't encourage people from outside of @nestjs org to work on some issue.

### Teachability, documentation, adoption, migration strategy

Taking IssueHunt as an example, the owner of this repo just need to log-in on it with its GitHub account and then add this repo to their system. Then any user of IssueHunt could start fund open issues as they whish :cat: 

The only downside I can think of is that more PRs will be open if the community starts to adhere to this ideia. And since, as of now, only one person (I guess) have permissions to merge them, that could be stressful.

### What is the motivation / use case for changing the behavior?

The goal is to start yet another initiative that could help on improving the maintainability of NestJS in general so it could grow even more in 2023. I mean, if someone will paid for a given problem to be solved, then contributors could invest their time on that. As there are companies that are using Nest in production, I don't think that this is too unrealistic.

---

I just want to hear some thought about this. Thanks! :)

**Comment by kamilmysliwiec** [comment]
There are currently no plans to integrate Nest with any external bounty programs. If anyone is interested to contribute, PRs are more than welcome - that's OSS. If there's any issue/PR that needs to be urgently reviewed, please, let me know. If there are some outstanding, crucial PRs/issues - please let me know too. Otherwise, I don't think that we're lacking updates/running into any maintenance issues - issues that are not _bugs_ (or just random questions) but rather feature requests don't have to be immediately implemented.
