### ISSUE TITLE
There is no matching event handler defined in the remote service

### ISSUE THREAD

**Issue by ddimitrioglo** [nestjs/nest#10830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Emitting an event (via RabbitMQ transport) fails every second time with the error: `There is no matching event handler defined in the remote service. Event pattern: test_msg`

### Minimum reproduction code

https://github.com/ddimitrioglo/nestjs-reproduction-example

### Steps to reproduce

1. Install dependencies in both (`first` & `second` microservices): `npm install`
2. Start both microservices: `npm run start:dev`
3. Trigger event emission: http://localhost:3001/trigger

### Expected behavior

Receive **every** event

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```
[System Information]
OS Version     : macOS
NodeJS Version : v14.17.5
NPM Version    : 6.14.14 

[Nest CLI]
Nest CLI Version : 9.1.8 

[Nest Platform Information]
platform-express version : 9.2.1
microservices version    : 9.2.1
schematics version       : 9.0.4
testing version          : 9.2.1
common version           : 9.2.1
core version             : 9.2.1
cli version              : 9.1.8
```

### Node.js version

14.17.5

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
