### ISSUE TITLE
body-parser 'strict' option configuration

### ISSUE THREAD

**Issue by l-derossis** [nestjs/nest#10838]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a requirement from a customer who needs to send raw strings, number, or JSON objects on our API. But by default, NestJS doesn't seem to accept anything else than objects.

From what I understand, it's because of the default configuration of `body-parser` that is applied. It is configured with the `strict` option to `true` (actually it's not set, but it's true by default). The [body-parser doc](https://www.npmjs.com/package/body-parser#bodyparserjsonoptions) states about this option: 
> When set to true, will only accept arrays and objects; when false will accept anything JSON.parse accepts. Defaults to true.

But I can't find any way to configure it. I found this workaround, but it's not really satisfying: 

```
    const app = await NestFactory.create<NestExpressApplication>(AppModule, {
        bodyParser: false,
    });

    app.use(bodyParser.json({ strict: false }));
```

I disable it and use it with the configuration I want in an additional middleware. I'm not a huge fan of this solution because I have to read NestJS source code to understand what values are set by default, since I want to use the same configuration as previously. 

### Describe the solution you'd like

Addind a parameter to configure `body-parser` like that would be very helpful: 

```
const app = await NestFactory.create<NestExpressApplication>(AppModule, {
        bodyParser: false,
        bodyParserStrict: true
    });
```

### Teachability, documentation, adoption, migration strategy

Users will be able to read raw strings / numbers / booleans from the request body with the `@Body()` decorator. I've found many issue related to this behavior, all of them with a different workaround.

### What is the motivation / use case for changing the behavior?

I'm stuck with a customer requirement.

**Comment by micalevisk** [comment]
that solution won't scale.

A better one would be allowing the consumer to supply their own body parser options instead. See PR #10633
