### ISSUE TITLE
Exception thrown by NestApplication.useStaticAssets() with single options arg

### ISSUE THREAD

**Issue by michaelbromley** [nestjs/nest#1083]
## I'm submitting a...
[x] Bug report

## Current behavior
I believe there may be an error in the implementation of `NestApplication.useStaticAssets()`, such that it throws an exception when used with a single options object argument.

https://github.com/nestjs/nest/blob/ce498e86150f7de4a260f0c393d47ec4cc920ea1/packages/core/nest-application.ts#L355-L364

The first signature above suggests that you can pass a single `options` object to the method. This is then passed to the `ExpressAdapter.useStaticAssets()` method (if you are using Express as I am), with the first argument being the options object, and the second argument being undefined.

https://github.com/nestjs/nest/blob/ce498e86150f7de4a260f0c393d47ec4cc920ea1/packages/core/adapters/express-adapter.ts#L122-L127

Since now the `options` argument is undefined, execution will move to line 126 and will pass our original options object to the `express.static()` method. This will result in an exception being thown:

```
TypeError: root path must be a string
    at Function.serveStatic [as static] (<snip>\node_modules\serve-static\index.js:44:11)
    at ExpressAdapter.useStaticAssets (<snip>\node_modules\@nestjs\core\adapters\express-adapter.js:86:39)
    at NestApplication.useStaticAssets (<snip>\node_modules\@nestjs\core\nest-application.js:248:30)
```

## Expected behavior
It should work with a single options argument, as in the docs: https://docs.nestjs.com/techniques/mvc

## Environment

<pre><code>
Nest version: 5.3.2
</code></pre>

**Comment by michaelbromley** [comment]
hmm... perhaps I am really missing something here, but if you look at line 126 above, at runtime the value of `path` is the config object when you only use a single object argument, which leads to the exception.

I would have expected something more like this:
```ts
class ExpressAdapter {
    // ....

    useStaticAssets(pathOrOptions: string, options: ServeStaticOptions) { 
        if (typeof pathOrOptions === 'string') {
            return this.use(express.static(pathOrOptions, options));        
        } else if (pathOrOptions && pathOrOptions.prefix) { 
            return this.use(pathOrOptions.prefix, express.static(pathOrOptions.prefix, pathOrOptions)); 
        }
    }
} 
```

**Comment by kamilmysliwiec** [comment]
> hmm... perhaps I am really missing something here, but if you look at line 126 above, at runtime the value of path is the config object when you only use a single object argument, which leads to the exception.

Sure, but if you use a single object argument, it has to provide `prefix` property. If there is no `prefix` prop, the exception is thrown.

**Comment by kamilmysliwiec** [comment]
Please, note that the API for `FastifyAdapter` and `ExpressAdapter` is different.

**Comment by NickDubelman** [comment]
Ahhh i thought that could be a potential cause but was confused because of your above comment didn't point out that distinction.

> Notice that there are 2 examples (1 with options object that contains prefix prop and another one with a single string)

However you did say

>  Pass 2 arguments
    Pass 1 argument with options object that has prefix property

and 

> Sure, but if you use a single object argument, it has to provide prefix property. If there is no prefix prop, the exception is thrown.

but that seems to apply to the FastifyAdapter only. OP specified ExpressAdapter, hence both of our confusion.

Thanks for the great framework!

**Comment by kamilmysliwiec** [comment]
Yes, just figured out that my explanation was totally wrong 😅
