### ISSUE TITLE
`--disallow-code-generation-from-strings` breaks nest's named ESM exports

### ISSUE THREAD

**Issue by ephys** [nestjs/nest#10846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you run node with the `--disallow-code-generation-from-strings` option & use native ESM imports, some named ESM imports break.

### Minimum reproduction code

https://github.com/ephys/nest-esm-issue

### Steps to reproduce

1. `npm ci`
2. `node index.mjs` # should run without issues
3. `node --disallow-code-generation-from-strings index.mjs` # should break: named import not found

### Expected behavior

For named exports to be available even when `--disallow-code-generation-from-strings` is used

### Package

I've only tested the first 4 packages of this list, only `@nestjs/core` succeeded (but it's possible one of the imports is failing. This issue is likely relevant to all packages):

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```json
"@nestjs/core": "^9.2.1",
"@nestjs/common": "^9.2.1",
"@nestjs/microservices": "^9.2.1",
"@nestjs/platform-express": "^9.2.1",
```

### Node.js version

18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

I think this can be fixed by including an ESM export map file, like I've done in other projects here: https://github.com/sequelize/sequelize/blob/main/src/decorators/legacy/index.mjs (+ [test](https://github.com/sequelize/sequelize/blob/main/test/unit/esm-named-exports.test.js) to ensure it stays up to date)

**Comment by jmcdo29** [comment]
We haven't set up ESM support yet, so anything that _is_ working is not by design and anything that _isn't_ working is not a bug. When we make Nest compatible with ESM this will be resolved. In the meantime, I followed the errors from the output and wrote the `import { Logger } ...` as 
```
import pkg from '@nestjs/common'
const { Logger } = pkg
```
and your code worked. Annoying, sure, but it works

**Comment by jccpro** [comment]
Wouldn't it be useful to keep it so it can be added as tests later when Nest will support ESM modules?
