### ISSUE TITLE
Support to async iterable on grpc methods

### ISSUE THREAD

**Issue by Farenheith** [nestjs/nest#10845]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It's not a problem, actually, but as AsyncIterables have been more and more improved in the core language, supporting it to represent a server-side stream for a gRPC method would be elegant.

### Describe the solution you'd like

Internally, the method result could be checked to see if it is an async Iterable, for example:
```ts
  ...
  let result = await controllerMethod();
  if (result.hasOwnProperty(Symbol.asyncIterator)) {
    result = rxjs.from(result);
  }
```

### Teachability, documentation, adoption, migration strategy

For instance, with the current version, I still can achieve something like that, with a code like this:
```ts
        @GrpcMethod()
	serverSideMethod(myData: MyData, metadata: Metadata) {
		return rxjs.from(
			this.asyncGeneratorMethod(
				myData, metadata,
			),
		);
	}
```

But with async iterables, something like this could be supported:

```ts
        @GrpcMethod()
	async *serverSideMethodAsyncGenerator(myData: MyData, metadata: Metadata) {
		... some code here ...
                yield resut1;
		... some code here ...
                yield resut2;
		... some code here ...
                yield resut3;
	}
```

### What is the motivation / use case for changing the behavior?

Async iterables are native, powerful, and elegant for a stream solution.
Also, even the internal stream API implements the async iterable interface. This feature could be used not only to declare a server-side stream of results with an async generator method, but also with Streams, Readables, and anything derived from it, letting the conversion to an rxjs Observable under the hood.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
