### ISSUE TITLE
Joi is undefined

### ISSUE THREAD

**Issue by edlynvillegas** [nestjs/nest#10879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm getting this error message below when trying to use joi

> TypeError: Cannot read properties of undefined (reading 'object')

### Minimum reproduction code

https://codesandbox.io/s/eager-spence-1697r7?file=/src/users/dto/create-user.dto.ts

### Expected behavior

joi package should not be undefined

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

joi

### NestJS version

9.0.0

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v18.7.0
NPM Version    : 8.15.0 

[Nest CLI]
Nest CLI Version : 9.1.8 

[Nest Platform Information]
platform-express version : 9.2.1
mapped-types version     : 1.2.0
schematics version       : 9.0.4
swagger version          : 6.1.4
testing version          : 9.2.1
common version           : 9.2.1
core version             : 9.2.1
cli version              : 9.1.8

### Node.js version

18.7.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by edlynvillegas** [comment]
I'm getting this error message using `import * as Joi from 'joi';`

> Cannot apply rules to empty ruleset or the last rule added does not support rule properties

**Comment by micalevisk** [comment]
@edlynvillegas the import went fine. The error now is due to how Joi works and your usage. Read their docs: https://joi.dev
