### ISSUE TITLE
Update nestjs caching docs for CacheModule and set ttl unit to ms

### ISSUE THREAD

**Issue by divyeshsachan** [nestjs/nest#10876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The latest version of cache-manage (v5) accepts ttl value in milliseconds. Whereas in docs https://docs.nestjs.com/techniques/caching#customize-caching it is written as seconds.

### Minimum reproduction code

NA

### Expected behavior

Kindly update docs https://docs.nestjs.com/techniques/caching#customize-caching and set ttl as milliseconds to avoid confusion.

This is a breaking change by cache-manager in v5, old packages using ttl in seconds will not work as expected as latest version of cache-manager changed its ttl unit to milliseconds.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

cache-manager v5

### NestJS version

9.2.1

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [x] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
