### ISSUE TITLE
Possible incorrect verbose log level priority

### ISSUE THREAD

**Issue by andkom** [nestjs/nest#10878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently Nest JS has the following log level priorities:

https://github.com/nestjs/nest/blob/master/packages/common/services/utils/is-log-level-enabled.util.ts#L3
```typescript
const LOG_LEVEL_VALUES: Record<LogLevel, number> = {
  debug: 0,
  verbose: 1,
  log: 2,
  warn: 3,
  error: 4,
};
```

and `verbose` log level is higher than `debug`, but in most systems and loggers `verbose` is usually lower than `debug`.

Was it done on purpose?

See also nestjs-pino issue: https://github.com/iamolegga/nestjs-pino/issues/1268

### Minimum reproduction code

https://github.com/nestjs/nest/

### Expected behavior

`verbose` log level is lower than `debug`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

nestjs-pino

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Tony133** [comment]
Could it be that `verbose` loglevel "groups" some loglevels as `info` or `trace`? (a curiosity of mine 😄), I was talking about it on Discord a few minutes ago.

**Comment by kamilmysliwiec** [comment]
Thanks for bringing this up! This was actually reported in the past as well. While log-level priorities vary between different systems/frameworks/libraries, I agree it's more common to see that the `verbose` log level is lower than `debug` in the hierarchy. However, changing this now would introduce quite an important breaking change and so the question is whether we should even do this at this point. Possibly - but definitely not sooner than in the next major release :)

**Comment by iamolegga** [comment]
@kamilmysliwiec hi 👋 I agree that this is a breaking change and it could be fixed only in major release, maybe we should keep this issue open until then? At the moment even order of levels in the docs hints that verbose might be lower than debug

**Comment by kamilmysliwiec** [comment]
Let's do this!

**Comment by kamilmysliwiec** [comment]
Let me lock this then just to avoid off-topic

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11036
