### ISSUE TITLE
app.service.ts IMPORT keyword builded as CIMPORT

### ISSUE THREAD

**Issue by pedrogatinhos** [nestjs/nest#10871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When initializing a new project `$ npm i -g @nestjs/cli
$ nest new project-name` the `import` statement inside app.service.ts is being builded as `cimport` causing a syntax error
error: `cimport { Injectable } from '@nestjs/common';`
fixed: `import { Injectable } from '@nestjs/common';`

### Minimum reproduction code

https://gist.github.com/pedrogatinhos/4e93d2961decc6e3a62c572f3c8479ea

### Steps to reproduce

$ npm i -g @nestjs/cli
$ nest new project-name

### Expected behavior

No synax errors when building the scratch template

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1

### Packages versions

```json
"@nestjs/cli": "^9.0.0",
"@nestjs/schematics": "^9.0.0",
"@nestjs/testing": "^9.0.0",
"@types/express": "^4.17.13",
"@types/jest": "29.2.4",
```

### Node.js version

14.17

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
On Unix it works correctly( see screenshot ), try reinstalling the CLI of NestJS

<img width="798" alt="Screenshot 2023-01-12 alle 10 56 24" src="https://user-images.githubusercontent.com/11542387/212035873-805d9e48-f90a-451d-86f9-727eb317e2ae.png">

Try posting this problem in the [Discord](https://discord.com/invite/G7Qnnhy) support channel.

**Comment by micalevisk** [comment]
try it with `npx @nestjs/cli@latest new` instead

**Comment by pedrogatinhos** [comment]
yes it worked thanks 🤝
