### ISSUE TITLE
Module not found: Error: Can't resolve modules -webpack5 breaking changes

### ISSUE THREAD

**Issue by sapirel** [nestjs/nest#10884]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

9.2.1

### Describe the regression

I upgraded next js version  and it changed webpack to version 5
Since that I got the following errors:

Module not found: Error: Can't resolve 'cache-manager' in '/Users/sapirelisha/Documents/falcon-lab-automation/node_modules/@nestjs/common/cache'

Module not found: Error: Can't resolve '@nestjs/microservices/microservices-module' in '/Users/sapirelisha/Documents/falcon-lab-automation/node_modules/@nestjs/core'

Module not found: Error: Can't resolve '@nestjs/microservices' in '/Users/sapirelisha/Documents/falcon-lab-automation/node_modules/@nestjs/core'
I got more error on another nest modules : cache-manager, class-transformer, cache-manager etc...

I  know that its breaking changes in webpack 5 so I tried edit webpack.config.js, but it didn't resolve all the errors.
and if  I put in fallbak  all the errors module in  false like: fallback:{fs:false} , the application didn't rendered in the browser
Why I got these errors?
How can I fix that?
Any help will be highly appreciated.

### Input code

const WebpackNotifierPlugin = require('webpack-notifier'); 
const nrwlConfig = require("@nrwl/react/plugins/webpack.js"); // require the main @nrwl/react/plugins/webpack configuration function.
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')
var IgnorePlugin = require('webpack').IgnorePlugin;
module.exports = (config, context) => {
  nrwlConfig(config); // first call it so that it @nrwl/react plugin adds its configs, 
 
// then override your config.
  return {
    ...config,
    target: "web", 
    plugins:[
    ...config.plugins,
    new IgnorePlugin({
      checkResource(resource) {
        const lazyImports = [
          '@nestjs/microservices',
          '@nestjs/platform-express',
          'cache-manager',
          'class-validator',
          'class-transformer',
          '@nestjs/microservices/microservices-module',
          'cache-manager'
        ];
        if (!lazyImports.includes(resource)) {
          return false;
        }
        try {
          require.resolve(resource);
        } catch (err) {
          return true;
        }
        return false;
      },
    })],
    resolve : {
      ...config.resolve,
      fallback: {
        ...config.resolve.fallback,
        // Use can only include required modules. Also install the package.
        // for example: npm install --save-dev assert
        // url: require.resolve('url'),
         fs: false,
         tls: false,
         net: false,
         async_hooks:false,
        //   ['cache-manager']:false,
        //   ['@nestjs/microservices/microservices-module']: false,
        //   ['class-transformer/storage']: false,
        // ['@nestjs/microservices']: false,
          repl: false
        // assert: require.resolve('assert'),
        // crypto: require.resolve('crypto-browserify'),
        // http: require.resolve('stream-http'),
        // https: require.resolve('https-browserify'),
        // os: require.resolve('os-browserify/browser'),
        // buffer: require.resolve('buffer'),
        // stream: require.resolve('stream-browserify'),
    }
      },
      plugins: [
       ...config.plugins,
      //  new WebpackNotifierPlugin({title: 'Frontend Project build completed'}),
       new NodePolyfillPlugin()
      ],
      externals: {
        bufferutil: "bufferutil",
        "utf-8-validate": "utf-8-validate",
      }

  };
};```ts

```


### Expected behavior

The errors will be disappear, because they stop us from deploy the app.and the application will successfully run on the browser like it does in webpack 4

### Other

_No response_

**Comment by Tony133** [comment]
Hi @sapirel,

have you taken a look at this: https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5 ? 

All the way use the support channel [discord](https://discord.com/invite/G7Qnnhy) for this kind of questions.

The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by sapirel** [comment]
@Tony133  thanks for your answer. I tried but it didn' work
I will write my question in the supported channel

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
