### ISSUE TITLE
When using nest g resource, npm is used by default

### ISSUE THREAD

**Issue by Chen-913** [nestjs/nest#10890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using `nest g resource`, `npm` is used by default
But I use the project created by `pnpm` !

### Minimum reproduction code

no

## Simple steps
nest new my-nest-app
-> choose `pnpm`
cd my-nest-app
nest g resoure test1 --no-spec
![image](https://user-images.githubusercontent.com/72293244/212843237-91e46c86-6ce2-440d-8397-48e490069fb5.png)

### Expected behavior

It should use `pnpm` to install the new dependency

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v14.19.3
NPM Version    : 6.14.17

[Nest CLI]
Nest CLI Version : 9.1.8

[Nest Platform Information]
platform-express version : 9.2.1
mapped-types version     : 1.2.0
schematics version       : 9.0.4
testing version          : 9.2.1
common version           : 9.2.1
core version             : 9.2.1
cli version              : 9.1.8

my `package.json` :
```json
"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
```

### Node.js version

14.19.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Duplicated, See [here](https://github.com/nestjs/nest-cli/issues/1115), this also happens with Yarn.
