### ISSUE TITLE
Getting 404 error with @nestjs/websockets

### ISSUE THREAD

**Issue by sapirel** [nestjs/nest#10891]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

^9.2.1

### Describe the regression

I upgraded nest + nest websocket to 9.2.1 version, and created websocket  in server side (nodejs) by the following code:

in file labFlow.getways.js:

import { WebSocketGateway, WebSocketServer } from '@nestjs/websockets';
import { Server } from 'socket.io';
import { SocketsDefinition } from '@lab/api';
import { Logger } from '@lab/common-backend';

@WebSocketGateway({ path: SocketsDefinition.labFlowSocket })
export class LabFlowGetway {
  constructor(private readonly logger: Logger) {}
  @WebSocketServer()
  private readonly server: Server;

  onModuleInit = () => {
    this.server.on('connection', socket => {
      console.log('Hello!!!', socket.id);
    });
  };
  broadcast = (eventName: string, message: string): void => {
    this.logger.log(`LabFlow message: ${message}`);
    this.server.emit(eventName, message);
  };
}

I added it to app.module:
 providers: [
    LabFlowGetway,
    LabFlowService,
    {
      provide: APP_FILTER,
      useClass: AllExceptionsFilter,
    },
  ],

and in the client (react +ts)  I got the error:
main.24afcea753750dc1.js:2          GET http://localhost:4200/lab-flow-table/entities/?EIO=4&transport=polling&t=OM_x1M1 404 (Not Found)

The code in the client:
const socket: Socket = io('', { path: SocketsDefinition.labFlowSocket });
 socket.on(SocketEventType.newLabFlowInsertedEvent, handleEvent);

Any help will be highly appreciated!

### Input code

Macos

"@nestjs/axios": "^1.0.1",
    "@nestjs/common": "^9.2.1",
    "@nestjs/core": "^9.2.1",
    "@nestjs/elasticsearch": "^9.0.0",
    "@nestjs/mongoose": "^9.2.1",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.2.1",
    "@nestjs/platform-socket.io": "^9.2.1",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/serve-static": "^3.0.0",
    "@nestjs/swagger": "^6.1.4",
    "@nestjs/websockets": "^9.2.1",
"socket.io": "^4.5.0",
    "socket.io-client": "^4.5.0",

### Expected behavior

Expect websocket will success to connect
and stop getting 404 error

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
