### ISSUE TITLE
Return views in exception filter is not working with fastify

### ISSUE THREAD

**Issue by whl2606555** [nestjs/nest#10897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I using fastify, the code below does not return anything in response actually:
```typescript
async catch(exception: unknown, host: ArgumentsHost):Promise<void>{
        const response = host.switchToHttp().getResponse() as FastifyReply
        response.view('error')
        return Promise.resolve()
    }
```

### Minimum reproduction code

https://codesandbox.io/s/blazing-breeze-ysmn2l

### Steps to reproduce

1. `nest start`
2. open `http://127.0.0.1:3000/exception`

### Expected behavior

It should return a view.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

ejs

### Packages versions

```json
"dependencies": {
    "@fastify/static": "^6.6.1",
    "@fastify/view": "^7.4.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-fastify": "^9.2.1",
    "ejs": "^3.1.8",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  }
```

### Node.js version

19.4.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
