### ISSUE TITLE
Cache-manager V5 (5.1.4) is breaking automatic caching via CacheInterceptor 

### ISSUE THREAD

**Issue by MateZubcic** [nestjs/nest#10899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The automatic caching using CacheInterceptor as described in the documentation is not working when using cache-manager v5.1.4 which is installed after using the documentation recommended command to install the required packages:

`npm install cache-manager`

At the moment of time this installs:

`"cache-manager": "^5.1.4"`

With this version the caching does not work at all. 

### Minimum reproduction code

https://github.com/MateZubcic/nest/tree/master/sample/20-cache/src

### Steps to reproduce

The reproduction code is a fork of the nest repo, the example for caching was using cache-manager v4, my repo only has it updated to v5 using the command from docs.
1. run the api
2. try the test endpoint
3. Make multiple api calls inside 5 seconds which is the default TTL of a cached response
4. notice that the api is always run and never cached, I have demonstrated this by a console.warn line which always gets called

### Expected behavior

Expected behavior would be for the automatic caching to work using the recommended command from documentation.

If that is not currently possible then the docs should specify that v4.1 should be used only.
for example the recommended command should maybe be:

`npm install cache-manager@4.1.0`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v16.17.0
NPM Version    : 8.19.1 

[Nest CLI]
Nest CLI Version : 9.0.0

[Nest Platform Information]
platform-express version : 9.0.1
schematics version       : 9.0.1
testing version          : 9.0.1
common version           : 9.0.1
core version             : 9.0.1
cli version              : 9.0.0

### Node.js version

NodeJS Version : v16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
The documentation needs to be updated, in fact there is already a PR ready, see [here](https://github.com/nestjs/docs.nestjs.com/pull/2576)

**Comment by MateZubcic** [comment]
Thanks I will be closing the issue as it is being addressed.
