### ISSUE TITLE
nestjs will not be installed with nestj cli.

### ISSUE THREAD

**Issue by neko113** [nestjs/nest#10892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="455" alt="image" src="https://user-images.githubusercontent.com/75781414/212939547-79168202-62ac-49aa-a929-4bfcb6c126ae.png">
my computer is m1 air and nestjs is not installed.

### Minimum reproduction code

no

### Expected behavior

no

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

latest

### Packages versions

```json
nestjs latest cli

```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Hi @neko113, for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel

The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by micalevisk** [comment]
Try it out with  
`npx @nestjs/cli@latest new`

**Comment by neko113** [comment]
> Try it out with `npx @nestjs/cli@latest new`

that isnt work too
