### ISSUE TITLE
Module '"@nestjs/common"' has no exported member 'ParseFilePipeBuilder'

### ISSUE THREAD

**Issue by nitinmagdumvista** [nestjs/nest#10900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Module '"@nestjs/common"' has no exported member 'ParseFilePipeBuilder'

"@nestjs/axios": "^0.0.6",
    "@nestjs/class-transformer": "^0.4.0",
    "@nestjs/class-validator": "^0.13.4",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mongoose": "^9.2.0",

### Minimum reproduction code

https://github.com/nestjs/

### Expected behavior

how to use file validation in nestjs/common 8.0.0

@UploadedFile(
  new ParseFilePipeBuilder()
    .addFileTypeValidator({
      fileType: 'jpeg',
    })
    .addMaxSizeValidator({
      maxSize: 1000
    })
    .build({
      errorHttpStatusCode: HttpStatus.UNPROCESSABLE_ENTITY
    }),
)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

"@nestjs/axios": "^0.0.6",
    "@nestjs/class-transformer": "^0.4.0",
    "@nestjs/class-validator": "^0.13.4",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mongoose": "^9.2.0",

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

"@nestjs/axios": "^0.0.6",
    "@nestjs/class-transformer": "^0.4.0",
    "@nestjs/class-validator": "^0.13.4",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mongoose": "^9.2.0",

**Comment by micalevisk** [comment]
`ParseFilePipeBuilder` was introduce in nestjs v9.

**Comment by nitinmagdumvista** [comment]
Thanks @micalevisk How to validate fileType and fileIsRequired in v8

**Comment by micalevisk** [comment]
@nitinmagdumvista 
you can do that in various way. You could start with a simply one using just nodejs+express stuff. Or you can see how `ParseFilePipeBuilder` here in this repository and copy that logic.

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead

**Comment by edeebee** [comment]
it is possible to inject parameters from config into validator decorator? e.g :
@UploadedFile(
      new ParseFilePipe({
        validators: [
          new MaxFileSizeValidator({
            maxSize: this.configService.get('MAX_CSV_UPLOAD_SIZE_BYTES'),
          }),
        ],
      }),
