### ISSUE TITLE
How to return a pdf file in response ? 

### ISSUE THREAD

**Issue by maroodb** [nestjs/nest#1090]
we suppose that I have a Buffer object , How to return it in a response object?

```
@Get(':fileHash')
getFile(@Param('fileHash') fileHash) {
        console.log(fileHash);
        this.sharingService.get(fileHash).then ( buffer => {
         
         // what to do ?
       }
    }
```

**Comment by maroodb** [comment]
this is sharingService code:

```
@Injectable()
```
export class SharingService {
   private ipfs: any;
  constructor (){
    this.ipfs =  ipfsAPI('localhost', '5001', {protocol: 'http'})
  }
  public add (file) {
    this.ipfs.add(file, (err, res) => {
      console.log(err);
      console.log(res);
    })
  }

  public get (fileHash) {
    return new Promise(((resolve, reject) => {
      this.ipfs.get(fileHash, (err, res) => {
        if (err) {
          reject(err)
        } else {
          resolve(res)
        }
      })
    }));

  }
}
```
```

**Comment by marcus-sa** [comment]
```ts
@Injectable()
export class SharingService {
	private ipfs: any;
	
	constructor (){
		this.ipfs = ipfsAPI('localhost', '5001', { protocol: 'http' });
	}
	
	// You need to get the content as a readable stream ...
	public async get (fileHash: string) {
		return await this.ipfs.files.catReadableStream(fileHash);
	}
}
```

```ts
// And then pipe it through the request response and set the content-type header
// dunno if this works but the below will
@Get(':fileHash')
@Header('Content-Type', 'application/pdf')
async getFile(@Param('fileHash') fileHash: string) {
   return await this.sharingService.get(fileHash);
}

// this will definitely work
@Get(':fileHash')
@Header('Content-Type', 'application/pdf')
async getFile(@Res() res: Response, @Param('fileHash') fileHash: string) {
   res.pipe(await this.sharingService.get(fileHash));
}
```

**Comment by maroodb** [comment]
> @Get(':fileHash') @Header('Content-Type', 'application/pdf') async getFile(@Param('fileHash') fileHash: string) { return await this.sharingService.get(fileHash); }

I got this error when using pipe "error TS2339: Property 'pipe' does not exist on type 'Response'."

**Comment by maroodb** [comment]
the two alternatives doesn't answer the question.

**Comment by marcus-sa** [comment]
I think you need to formulate your question different as I got no clue what you actually want

**Comment by nightmarelie** [comment]
That's how I implemented it on my project

**Controller:**
```javascript
import { Post, Body, Res } from '@nestjs/common';
import { Response } from 'express';
// import PrintDto | printSchema | JoiValidationPipe

@Post('pdf')
async print(
  @Body(new JoiValidationPipe(printSchema)) body: PrintDto,
  @Res() res: Response,
) {
  const buffer = await this.printService.printPdf(body);
  const stream = this.printService.getReadableStream(buffer);

  res.set({
    'Content-Type': 'application/pdf',
    'Content-Length': buffer.length,
  });

  stream.pipe(res);
}
```
**PrintService:**
```javascript
import { Readable } from 'stream';
// import PrintDto

async printPdf(body: PrintDto): Promise<Buffer> {
  // ...
  return buffer;
}

getReadableStream(buffer: Buffer): Readable {
  const stream = new Readable();

  stream.push(buffer);
  stream.push(null);

  return stream;
}
```
> [useful link to stream-handbook](https://github.com/substack/stream-handbook)  This document covers the basics of how to write node.js programs with streams.
