### ISSUE TITLE
A named Get path doesn't work after the empty one

### ISSUE THREAD

**Issue by behzadam** [nestjs/nest#10903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I add a @Get('named') new router in the Controller if another empty Get() is exists it should be the last one and seems the order is important.

### Minimum reproduction code

https://github.com/behzadam/leitner/pull/83/files

### Expected behavior

Adding new methods ( routers ) to a controller should work regardless of order.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```json

```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/2590
