### ISSUE TITLE
API change proposal: use Symbols for lifecycle hooks methods instead of strings

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#10901]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Although the API of [lifecycle hook methods](https://docs.nestjs.com/fundamentals/lifecycle-events#lifecycle-events-1) is fine due to the role of NestJS, I want to discuss an alternative API that addresses issues on the current one.

Using strings for hooks methods leads to the following issues: 

1. They pollute our domain classes

  <details>
  <summary>for example</summary>

![image](https://user-images.githubusercontent.com/13461315/213842266-c78c4e4d-053c-4dd0-a883-15f5c22ff135.png)

they appear in the autocompletion even tho we rarely want to call them from outside. To circumvent that we can use the `private` modifier, but now we can't use `implments OnX` due to how TS works. Another way would be by implementing the Facade Pattern.

  </details>

2. We have to recall on 5 (maybe more in the future?) reserved methods that our providers and modules shouldn't have
3. We're leaking abstractions to consumer side. We can no longer have class-based providers with such methods due to name clashes
   1. if, for whatever reason, we have some 3rd-party package that ends up invoking some of those methods for non-nestjs related stuff, our app won't work as we expected. So I guess we can say that those 5 methods are reserved for transitive dependencies as well
4. Since using the `implements` construction is not mandatory, people there aren't familiar with NestJS could found confusing having such 'special' methods in few classes that aren't explicitly implementing those interfaces, which may looks unrelated with the fw.

Angular has those kind of methods [too](https://angular.io/guide/lifecycle-hooks#lifecycle-event-sequence) but they have a brand on their names (the prefix `ng` which stands for _Angular_). I don't like that aproach, tho.

[Ts.ED](https://tsed.io/docs/hooks.html#introduction) has hooks just like Angular. The prefix is `$`.

React has them too like Nest but they are moving away from JS classes now.

### Describe the solution you'd like

Use _Symbol properties_ construction.

<details>
<summary>For example, JS has the built-in <code>Symbol.replace</code> symbol (and a bunch of others) to allow us changing the behavior of some native operation with ease
</summary>

[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/replace)

![image](https://user-images.githubusercontent.com/13461315/213841842-77abaffd-3872-41aa-8b09-42609c5fb6ce.png)

</details>

<details>
<summary>Nodejs's core use them to create private internal fields</summary>

![image](https://user-images.githubusercontent.com/13461315/213841301-171fd8b3-71f0-4046-a1ba-4a5d45e4dba4.png)

</details>

In NestJS, we would go

<details>
<summary>from this</summary>

```ts
import {
  BeforeApplicationShutdown,
  Injectable,
  OnApplicationBootstrap,
  OnApplicationShutdown,
  OnModuleDestroy,
  OnModuleInit,
} from '@nestjs/common';

@Injectable()
export class AppService
  implements
    OnModuleInit,
    OnModuleDestroy,
    OnApplicationBootstrap,
    OnApplicationShutdown,
    BeforeApplicationShutdown
{
  getHello(): string {
    return 'Hello World!';
  }

  onModuleInit(): void {
    console.log('[AppService] onModuleInit');
  }

  onApplicationBootstrap(): void {
    console.log('[AppModule] onApplicationBootstrap');
  }

  onModuleDestroy() {
    console.log('[AppService] onModuleDestroy');
  }

  beforeApplicationShutdown(signal?: string) {
    console.log('[AppService] beforeApplicationShutdown');
  }

  onApplicationShutdown(signal?: string) {
    console.log('[AppService] onApplicationShutdown');
  }
}
```

</details>

to this:

<details open><summary><b>Proposal 1</b>: avoid importing 2 things by using the same name for both the interface and the symbol</summary>

```ts
import {
  Injectable,
  BeforeApplicationShutdown,
  OnModuleInit,
} from '@nestjs/common';

@Injectable()
export class AppService
  implements
    OnModuleInit,
    BeforeApplicationShutdown
{
  getHello(): string {
    return 'Hello World!';
  }

  [OnModuleInit](): void {
    console.log('[AppService] onModuleInit');
  }

  [BeforeApplicationShutdown](signal?: string) {
    console.log('[AppService] beforeApplicationShutdown');
  }
}
```

</details>

<details><summary><b>Proposal 2</b>: importing 2 things (the interface and the symbol)</summary>

```ts
import {
  Injectable,
  BeforeApplicationShutdown,
  beforeApplicationShutdown,
  OnModuleInit,
  onModuleInit,
} from '@nestjs/common';

@Injectable()
export class AppService
  implements
    OnModuleInit,
    BeforeApplicationShutdown
{
  getHello(): string {
    return 'Hello World!';
  }

  [onModuleInit](): void {
    console.log('[AppService] onModuleInit');
  }

  [beforeApplicationShutdown](signal?: string) {
    console.log('[AppService] beforeApplicationShutdown');
  }
}
```

</details>

---

![image](https://user-images.githubusercontent.com/13461315/213842933-8c4ed59a-f7d4-45e6-86aa-b71fbed6fee5.png)

#### cons

1. Using computed properties for classes isn't that common (and may looks odd to newcomers) as a public API for nodejs frameworks out there. But I want to make sure that this API has been discussed
3. 3rd-party libs that only uses lifecycle hooks and no other breaking change introduced in v11, would have to implement both versions (string and symbol-based) in order to support both v10 and v11

### Teachability, documentation, adoption, migration strategy

- add those new symbol methods in v9, as an alternative to string-based ones
- deprecated string-based ones in v10. At runtime a warning message will make that clear for each component that implement some lifecycle hook method
- remove string-based ones in v11

### What is the motivation / use case for changing the behavior?

- Address the earlier mentioned problems
- More reasons here: [Do we really need symbols? Aren't strings enough?](https://exploringjs.com/es6/ch_symbols.html#_do-we-really-need-symbols-arent-strings-enough)
- We can now introduce more methods, without worrying on impacting old nestjs applications

**Comment by kamilmysliwiec** [comment]
While I agree that this proposal generally makes sense and appreciate that you took your time to write it down, we should make sure to only introduce breaking changes when it's absolutely necessary - and I don't think this change is required given what impact it would have on existing codebases (with rather minimal benefit)
