### ISSUE TITLE
GraphQL. Cannot create enum with values in "code first approach" 

### ISSUE THREAD

**Issue by gapon2401** [nestjs/nest#10902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Autogenerated GraphQL schema file `schema.gql` doesn't have enum values, only keys. 

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-graphql-schema-enum-issue?file=src/schema.gql

### Expected behavior

Autogenerated `schema.gql` with enum values. According to the reproduction [link](https://stackblitz.com/edit/nestjs-graphql-schema-enum-issue?file=src/schema.gql) I expect:

```
enum Size {
  SMALL = 'sm',
  MEDIUM = 'med',
  LARGE = 'lg',
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
    "@nestjs/apollo": "^10.1.7",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^10.1.7",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I'm using "code first approach" for creating schema for GraphQL. I've tried to use `resolvers` for graphql module from the [docs](https://docs.nestjs.com/graphql/unions-and-enums). Nothing changes. I cannot make module to generate enum with values.

**Comment by Tony133** [comment]
Hi @gapon2401, for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel

The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by micalevisk** [comment]
this is expected, see https://docs.nestjs.com/graphql/unions-and-enums#code-first-1
