### ISSUE TITLE
@nestjs/swagger / class-validator - applyDecorators does not work in conjunction with whitelist and forbidNonWhitelisted: true

### ISSUE THREAD

**Issue by chtpl** [nestjs/nest#10910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My API rejects the field which I wanted to make optional using the helper decorator I created below because it seems to ignore the IsOptional decorator.
However, the ApiPropertyOptional seems to be applied, because when I change that to "ApiProperty" in the applyDecorators call below, the Swagger web UI shows a red asterisk next to the field name in the schema tab which wasn't there with ApiPropertyOptional

```
app.useGlobalPipes(new ValidationPipe({whitelist:true, forbidNonWhitelisted: true}));

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { Allow, IsOptional, IsString } from 'class-validator';

export function ApiOptionalString(options: { example: string; description: string }) {
  return applyDecorators(
    ApiPropertyOptional({
      example: options.example,
      description: options.description,
    }),
    Allow,
    IsOptional,
    IsString,
  );
}

export class MyDto {

  @ApiOptionalString({
    example: 'Hello',
    description: 'Greeting',
  })
    greeting: string;
}
```

### Minimum reproduction code

Will provide one when asked

### Expected behavior

All decorators should be applied

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
    "@nestjs/swagger": "^6.1.4",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
