### ISSUE TITLE
@Header Decorator affect all next methods

### ISSUE THREAD

**Issue by maroodb** [nestjs/nest#1093]
I have this controller 
```
 @Get(':fileHash')
   @Header('Content-Type', 'application/pdf')
   async getFile(@Param('fileHash') fileHash: string) {
     return await this.sharingService.get(fileHash);
   }

  @Get('encrypt')
  testEncrypt (@Res() res) {

    this.cryptoUtils.encryptAsync(Buffer.from("Hello maro")).then(console.log).catch(console.log)
  }
```

In this order  @Header('Content-Type', 'application/pdf') affects also the second method (testEncrypt),

when I reverse the order everything gone right. 

why ?

**Comment by kamilmysliwiec** [comment]
I can't reproduce this issue. Also, your code is invalid, `testEncrypt` will never respond to the user (injected `res` object)
