### ISSUE TITLE
Issue setting up SequelizeModule with proxy for Snowflake DB

### ISSUE THREAD

**Issue by TASimpson** [nestjs/nest#10949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Everything has been working great! However, I have been tasked to have the Snowflake DB connection go through a proxy. I have not been able to find a solution and I have tried a few with no success. Please help me determine how I need to set this up so that our application can go to Production without a total rewrite! The below is my set up in my `app.module.ts`. What do I need to add to make this work?? 

```
    SequelizeModule.forRoot({
      dialect: 'snowflake',
      host: 'localhost',
      dialectOptions: {
        account: 'snowflake_account_here',
        application: 'SNOWFLAKE',
        role: 'snowflake_role_here',
        warehouse: 'snowflake_warehouse_here',
        schema: 'snowflake_schema_here'
      },
      username: 'snowflake_username_here',
      password: 'snowflake_password_here',
      database: 'snowflake_database_here',
      define : {
        freezeTableName: true
      },
      models: ([...list of models here]),
      quoteIdentifiers: false
    })
```

I have tried the following with NO success: 

1. Added the following under `dialectOptions`
  ```
 host: 'url to proxy'
 port: 'port to proxy'
```
AND 
```
stream : {
   host: 'url to proxy'
   port: 'port to proxy'
}
```
AND 
```
proxyHost: 'url to proxy'
proxyPort: 'port to proxy'
```

  

### Minimum reproduction code

N/A

### Steps to reproduce

1. Set up the SequelizeModule as described here for snowflake db connection: https://docs.nestjs.com/recipes/sql-sequelize
2. Now where to add proxy?? 

### Expected behavior

Just need the ability to add a proxy to the snowflake db connection!

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^9.0.0

### Packages versions

 "dependencies": {
    "@angular/animations": "~14.2.0",
    "@angular/cdk": "^14.2.2",
    "@angular/cli": "~14.2.0",
    "@angular/common": "~14.2.0",
    "@angular/compiler": "~14.2.0",
    "@angular/compiler-cli": "~14.2.0",
    "@angular/core": "~14.2.0",
    "@angular/forms": "~14.2.0",
    "@angular/material": "^14.2.2",
    "@angular/platform-browser": "~14.2.0",
    "@angular/platform-browser-dynamic": "~14.2.0",
    "@angular/router": "~14.2.0",
    "@material/card": "^14.0.0",
    "@nestjs/axios": "^0.1.1",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/sequelize": "^9.0.0",
    "@nestjs/swagger": "^6.1.2",
    "@nestjs/terminus": "^9.1.4",
    "@nestjs/typeorm": "^9.0.1",
    "@ng-bootstrap/ng-bootstrap": "^13.1.1",
    "@ng-select/ng-select": "^10.0.3",
    "@nrwl/angular": "^14.7.5",
    "@types/snowflake-sdk": "^1.6.8",
    "angular-auth-oidc-client": "^14.1.4",
    "angular-svg-icon": "^14.0.0",
    "angular2-uuid": "^1.1.1",
    "bootstrap": "^5.2.1",
    "cache-manager": "^4.1.0",
    "express-session": "^1.17.3",
    "fontawesome": "^5.6.3",
    "husky": "^8.0.1",
    "jwt-decode": "^3.1.2",
    "mysql2": "^2.3.3",
    "newrelic": "9.0.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-okta-oauth20": "^1.1.0",
    "passport-openidconnect": "^0.1.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~7.5.0",
    "sequelize": "^6.24.0",
    "sequelize-typescript": "^2.1.3",
    "snowflake-sdk": "^1.6.13",
    "tslib": "^2.3.0",
    "typeorm": "^0.3.11",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.2.0",
    "@angular-eslint/eslint-plugin": "~14.0.4",
    "@angular-eslint/eslint-plugin-template": "~14.0.4",
    "@angular-eslint/template-parser": "~14.0.4",
    "@angular/language-service": "~14.2.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@nrwl/cli": "14.7.5",
    "@nrwl/cypress": "14.7.5",
    "@nrwl/eslint-plugin-nx": "14.7.5",
    "@nrwl/jest": "14.7.5",
    "@nrwl/linter": "14.7.5",
    "@nrwl/nest": "^14.7.5",
    "@nrwl/node": "14.7.5",
    "@nrwl/workspace": "14.7.5",
    "@types/jest": "28.1.1",
    "@types/node": "16.11.7",
    "@types/sequelize": "^4.28.14",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "cypress": "^10.7.0",
    "cypress-multi-reporters": "^1.6.1",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "jest-preset-angular": "~12.2.2",
    "mocha": "^10.1.0",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "^4.2.1",
    "mochawesome-report-generator": "^6.2.0",
    "nx": "14.7.5",
    "prettier": "^2.6.2",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.8.2"
  }

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead

**Comment by TASimpson** [comment]
Ok will do! thanks!
