### ISSUE TITLE
Can't disable RouterExplorer and RouterMapper logs

### ISSUE THREAD

**Issue by asantos00** [nestjs/nest#10955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently a good part of my production logs are initializations of the application due to the number of logs that RouterMapper, RoutesResolver and RouterExplorer. I can't find a way to disable it

```
[12:34:17.909] INFO (27292):
    context: "RouterExplorer"
    message: "Mapped {/negotiations/:negotiationId/offers, POST} (version: 1) route"
[12:34:17.909] INFO (27292):
    context: "RoutesResolver"
    message: "OffersController {/offers} (version: 1):"
[12:34:17.909] INFO (27292):
    context: "RouterExplorer"
    message: "Mapped {/offers/:offerId, GET} (version: 1) route"
[12:34:17.909] INFO (27292):
    context: "RouterExplorer"
    message: "Mapped {/offers/:offerId/state, PATCH} (version: 1) route"
[12:34:17.909] INFO (27292):
    context: "RoutesResolver"
    message: "NegotiationsAdminController {/admin/negotiations} (version: 1):"
```

### Minimum reproduction code

Any nestjs app

### Expected behavior

Is there a way to disable these types of logs, or at least to intercept them?

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```json
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.13.1
NPM Version    : 8.1.2

[Nest CLI]
Nest CLI Version : 9.1.5

[Nest Platform Information]
platform-express version : 9.2.1
event-emitter version    : 1.3.1
mapped-types version     : 1.2.0
schematics version       : 9.0.3
passport version         : 9.0.0
terminus version         : 9.1.4
swagger version          : 6.1.4
typeorm version          : 9.0.1
testing version          : 9.2.1
common version           : 9.2.1
config version           : 2.2.0
axios version            : 1.0.0
core version             : 9.2.1
jwt version              : 9.0.0
cli version              : 9.1.5
```

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead

**Comment by micalevisk** [comment]
btw if you use another logger lib like the production-ready [Pino](getpino.io/) (with [`nestjs-pino`](https://github.com/iamolegga/nestjs-pino)) you will be able to suppress such entries easily using Pino features. The native one was designed to be as simple as possible and extensible

**Comment by micalevisk** [comment]
[how to disable initialization logging](https://dev.to/micalevisk/nestjs-tip-how-to-disable-initialization-logging-1b38)
