### ISSUE TITLE
Controllers Lifecycle

### ISSUE THREAD

**Issue by acostaf** [nestjs/nest#1095]
We have Lifecycle like OnModuleInit, OnModuleDestroy for services and OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect for gateways but I cannot find anything for Controller

Any idea ?

**Comment by acostaf** [comment]
OnModuleInit works on Controller but just when  app.listenAsync.. is on but wont fire when the project it is a microservice  @kamilmysliwiec can you help ?

**Comment by kamilmysliwiec** [comment]
`OnModuleInit` and `OnModuleDestroy` work for controllers as well.
Please, provide reproduction repository (and use issue template if possible)

**Comment by acostaf** [comment]
Hi @kamilmysliwiec 

I found the problem, when you have a nest project as that just listen to NATS messages (Microservice), like the below without  await app.listenAsync ... or app.listen the OnModuleInit and OnModuleDestroy don't get call so what I am doing is to call app.init() after await app.startAllMicroservicesAsync();

Can you ad some comments in the documentation? or some code to prevent this from happening ?

```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { Transport } from '@nestjs/microservices';
import { ConfigService } from 'stw-server-common';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const config = new ConfigService();

  await app.connectMicroservice({ transport: Transport.NATS, options: { url: config.NATSServer } });

  await app.startAllMicroservicesAsync();
}
bootstrap();
```

**Comment by acostaf** [comment]
I see, then call await app.listenAsync();?

that worked thanks.

BTW great work, we are using the app in a investment bank as a pilot for the core tech team that may be rolled to several other teams.

**Comment by kamilmysliwiec** [comment]
Yes :) Great to hear!
