### ISSUE TITLE
Middleware to serve Git repos

### ISSUE THREAD

**Issue by pkyriakis** [nestjs/nest#10957]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Nest cannot handle requests send by the git client without manually manipulating the req/res objects. 

### Describe the solution you'd like

The solution would be a middleware or a module that handles git requests, performs the needed actions on the repository and responds to the client. [This](https://www.npmjs.com/package/git-http-backend) npm package is a node wrapper for the git-http-backend that could be ported over to Nest. Ideally, there could be some interaction with nodegit, i.e., the affected repo could be injected into the controller for further processing. 

### Teachability, documentation, adoption, migration strategy

Developers should be able to use the proposed feature as any other Nest module.

### What is the motivation / use case for changing the behavior?

While I do not foresee a widespread use of such module, as most developers rely on established providers to host their repos, there are definitely some use-cases, i.e., teams that are self-hosting their repos and want to serve it over http, or developers who want to build a repo hosting service.

**Comment by micalevisk** [comment]
it's just a middleware right? why not writting your own and publish it as a community-made package?

**Comment by micalevisk** [comment]
To be fair this seems to be something that your app should support as a feature, not the framework

So I don't see any reason to bring that to @nestjs scope. The ecosystem has such role :)

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
