### ISSUE TITLE
TypeScript frameworks should be type safe

### ISSUE THREAD

**Issue by chriskuech** [nestjs/nest#10960]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

TypeScript is not a type safe language, it does not provide guarantees. If the deserializer does not accurately parse the value into its reported type, then TypeScript's overhead turns from a benefit to a burden.

The de facto deserializers for NestJS are `class-transformer` and `typeorm` at their respective ends of the stack. These frameworks are both not type safe as they rely on classes which can have unset properties. `class-transformer`'s converters and `typeorm`'s repository methods are also loosely typed defeating the purpose of using TypeScript.  Using these libraries frequently causes the type system to break with inaccurate types.

### Describe the solution you'd like

Support using a non-`class`-based library for defining/deserializing DTOs, such as `zod`. This library should be fully featured for defining any typescript type, including union types.

### Teachability, documentation, adoption, migration strategy

More info on why classes are bad for type definitions: https://javascript.plainenglish.io/why-you-should-generally-prefer-typescript-interfaces-and-custom-types-over-classes-d145814218ce

### What is the motivation / use case for changing the behavior?

* `class-transformer` is incapable of representing more complex object shapes because it is `class`-based and decorator based instead of explicit (such as `zod`).
* `class-transformer` easily leads to inaccurate types because it is `class`-based, unlike libraries supporting shapes (such as `zod`).
* when combined with the ORM featured in the NestJS docs (TypeORM), the experience becomes unbearable due to them silently mapping invalid types to eachother.
* NestJS architecture is amazing and it should not be brought down to `class-transformer` (and `typeorm`'s) level.

**Comment by micalevisk** [comment]
I'm pretty sure that this is being handled by the community already.

I don't like `class-x` packages that much but I don't think we would just drop them in the future, so starting support yet another lib for the same role just introduces maintenance burden here (to me).

**Comment by kamilmysliwiec** [comment]
You don't have to use `class-x` packages if you don't want to, and you can easily swap them with others (like zod). They're not required for Nest to work.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
