### ISSUE TITLE
Websocket Gateways Do Not Load when in Separate Modules

### ISSUE THREAD

**Issue by nawilson** [nestjs/nest#1097]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behaviour
When using websockets, gateways that are in separate modules are not added. For example, in the below code, only the namespace "gateway3" is available. Namespaces gateway1, and gateway2 are not available.

## Expected behaviour
I would expect that, since the gateways are part of the providers of their respective module, they would all load have have their namespaces available.

## Minimal reproduction of the problem with instructions
```
//Module 1
import { Gateway1 } from './services/gateway1.service';

@Module({
    imports: [ ],
    providers: [
        Gateway1 // namespace: gateway1
    ],
    controllers: [ ],
    exports: [ 
       Gateway1 // including or excluding this has no effect on whether it loads
    ],
})
export class Module1 {
}

//Module 2
import { Gateway2 } from './services/gateway2.service';

@Module({
    imports: [ ],
    providers: [
        Gateway2 // namespace: gateway2
    ],
    controllers: [ ],
    exports: [ 
       Gateway2 // including or excluding this has no effect on whether it loads
    ],

})
export class Module2 {
}

//Main WebSocket Module (is imported into app.module)
import { Module1 } from './modules/module1/module1.module';
import { Module2 } from './modules/module2/module2.module';
import { Gateway3 } from './services/gateway3.service';

@Module({
    imports: [
        Module1,
        Module2
    ],
    providers: [
       Gateway3 // namespace: gateway3
    ],
    controllers: [ ],
    exports: [ ],
})
export class MainWebSocketModule {
}
```

## What is the motivation / use case for changing the behaviour?
Code modularization and separation of concerns in websockets.

## Environment

<pre><code>
Nest version: 5.3.7

 
For Tooling issues:
- Node version: 8.11.4
- Platform:  Mac and Windows

</code></pre>

**Comment by kamilmysliwiec** [comment]
Just tested with `02-gateways`, everything works well. Please, provide a repository which reproduces your issue.

**Comment by ningacoding** [comment]
02-gateways, not working for me:

-  socket.io-redis package missing

![image](https://user-images.githubusercontent.com/17342546/53302592-a41fbe80-3825-11e9-8874-e5e7e77c61c9.png)

- WebSocket not listening

![image](https://user-images.githubusercontent.com/17342546/53302594-4a1ef900-3825-11e9-82f9-e0c47b78ec50.png)
