### ISSUE TITLE
Interceptor can not resolve dependency injection that use Scope.REQUEST

### ISSUE THREAD

**Issue by galapagosit** [nestjs/nest#10979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### TestAService

I have TestAService.
This is Scope.REQUEST scope;
```
@Injectable({ scope: Scope.REQUEST })
export class TestAService {}
```

### InterceptorA

Then InterceptorA inject TestAService.
When this is called,
logging **this.testAService**.

```
import { TestAService } from 'src/test-a/test-a.service';

@Injectable()
export class InterceptorA implements NestInterceptor {
  constructor(private readonly testAService: TestAService) {}

  intercept(_context: ExecutionContext, next: CallHandler): Observable<any> {
    console.log('InterceptorA called');
    console.log('this.testAService', this.testAService);
    return next.handle();
  }
}
```

### AppModule

InterceptorA is used globally
```
@Module({
  imports: [TestAModule],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_INTERCEPTOR,
      useClass: InterceptorA,
    },
  ],
})
export class AppModule {}
```

## Problem

When controller is callled. logged message is 

```
InterceptorA called
this.testAService undefined
```
this.testAService is not injected...

However, if InterceptorA is set to 
@Injectable({ scope: Scope.REQUEST })
it will be injected normally.

This document says that the scope is automatically bubbled, but that does not seem to be the case.
https://docs.nestjs.com/fundamentals/injection-scopes#scope-hierarchy

### Minimum reproduction code

https://github.com/galapagosit/nest-di-test

### Steps to reproduce

1. npm install
2. npm run start:dev 
3. access http://localhost:3000/

### Expected behavior

InterceptorA automatically set Scope.REQUEST and DI is resolved.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

[System Information]
OS Version     : macOS
NodeJS Version : v18.13.0
YARN Version    : 1.22.19 

[Nest CLI]
Nest CLI Version : 9.1.9 

[Nest Platform Information]
platform-express version : 9.2.1
schematics version       : 9.0.4
testing version          : 9.2.1
common version           : 9.2.1
core version             : 9.2.1
cli version              : 9.1.9

### Node.js version

v18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
That's actually a slightly different issue than https://github.com/nestjs/graphql/issues/325 - scope should properly bubble up for non-GraphQL apps. I'll get to the bottom of this asap

**Comment by kamilmysliwiec** [comment]
Have you tried using:

```
{
  provide: APP_INTERCEPTOR,
  useClass: InterceptorA,
  scope: Scope.REQUEST // <--- this is new
},
```
instead?

**Comment by galapagosit** [comment]
It was also successfully injected that way!

**Comment by kamilmysliwiec** [comment]
We should document this somewhere (update the docs) as that's not the first time this issue pops up 🤔  I'll see where we can add this note

**Comment by Fardenz** [comment]
> We should document this somewhere (update the docs) as that's not the first time this issue pops up 🤔 I'll see where we can add this note

I agree that this should be documented somewhere, as I also stumbled upon the documentation and assumed that [the scope hierarchy would also bubble up](https://docs.nestjs.com/fundamentals/injection-scopes#scope-hierarchy) and apply to interceptors
