### ISSUE TITLE
How to use nodemon when run nest project ?

### ISSUE THREAD

**Issue by jamespakorn** [nestjs/nest#1100]
How to use nodemon when run nest project ?

 ** i want to reload server-side when edit code in nest project without npm run start again.

**Comment by gado704555** [comment]
`npm run start:dev`

**Comment by mariomuja** [comment]
i also had this issue; it now works for me

one problem was that I did not correctly refer to files:  

// wrong: import { ExcelController } from 'src/routes/ExcelController';
// seemingly correct: import { ExcelController } from '../routes/ExcelController';

my start:dev in package.json looks as follows:
tsc-watch -p tsconfig.build.json --onSuccess \"node dist/main.js\"

another thing: please delete your "dist" folder and recreate it with
npm run build
there may be disturbing stuff in your dist...

keen to read what helped in your case
have fun,
mario
