### ISSUE TITLE
Issue Initializing @nestjs/microservice version 9.3.1

### ISSUE THREAD

**Issue by Alvannwanorim** [nestjs/nest#11009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```node 
C:\Users\bglag\Documents\Code\RabbitMq Microservice\ordering-app\node_modules\@nestjs\microservices\nest-microservice.js:104
        this.assertNotInPreviewMode('listen');
             ^
TypeError: this.assertNotInPreviewMode is not a function
    at NestMicroservice.listen (C:\Users\bglag\Documents\Code\RabbitMq Microservice\ordering-app\node_modules\@nestjs\microservices\nest-microservice.js:104:14)
    at C:\Users\bglag\Documents\Code\RabbitMq Microservice\ordering-app\node_modules\@nestjs\core\nest-application.js:140:63
    at Array.map (<anonymous>)
    at NestApplication.startAllMicroservices (C:\Users\bglag\Documents\Code\RabbitMq Microservice\ordering-app\node_modules\@nestjs\core\nest-application.js:140:46)
    at C:\Users\bglag\Documents\Code\RabbitMq Microservice\ordering-app\node_modules\@nestjs\core\nest-factory.js:133:40
    at Function.run (C:\Users\bglag\Documents\Code\RabbitMq Microservice\ordering-app\node_modules\@nestjs\core\errors\exceptions-zone.j
```

### Minimum reproduction code

https://github.com/Alvannwanorim/Orders_And_Billing_Microservice/tree/bug

### Steps to reproduce

git clone https://github.com/Alvannwanorim/Orders_And_Billing_Microservice/tree/bug

```sh
npm i 
npm run start:dev billing 
```

### Expected behavior

Should start the microservice without crashing 

Works finish when I switched to version 9.2.0

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.3.1",
    "@nestjs/mongoose": "^9.2.1",
    "@nestjs/platform-express": "^9.0.0",
    "amqp-connection-manager": "^4.1.10",
    "amqplib": "^0.10.3",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "joi": "^17.7.0",
    "mongoose": "^6.9.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I believe that you need to upgrade `@nestjs/core` to 9.3

try that out.

**Comment by micalevisk** [comment]
also please, next time share us the output of `npx nest info` so we don't have to check out your repository just to see which version exactly you're using for each package :)

**Comment by Alvannwanorim** [comment]
Okay Thanks. Will do that

**Comment by kamilmysliwiec** [comment]
You should make sure that `@nestjs/microservices` `@nestjs/core` `@nestjs/testing` and `@nestjs/common` are all on the same version (so for example, 9.3.0)
