### ISSUE TITLE
nest cannot handle src/main.mts

### ISSUE THREAD

**Issue by beckend** [nestjs/nest#11021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```bash
> nest start

Error: Cannot find module '/home/admin/Coding/codegenerator/dist/main'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

works fine when using `main.ts`.

### Minimum reproduction code

https://github.com/beckend/bug-nestjs-main.mts

### Steps to reproduce

```bash
mkdir /tmp/work && cd /tmp/work
npm i -g @nestjs/cli
npx nest new project-name
cd project-name
mv src/main.ts src/main.mts
npm run start

nest start

Error: Cannot find module '/tmp/work/project-name/dist/main'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

### Expected behavior

```bash
> project-name@0.0.1 start
> nest start

[Nest] 58877  - 02/02/2023, 11:45:40 PM     LOG [NestFactory] Starting Nest application...
[Nest] 58877  - 02/02/2023, 11:45:40 PM     LOG [InstanceLoader] AppModule dependencies initialized +5ms
[Nest] 58877  - 02/02/2023, 11:45:40 PM     LOG [RoutesResolver] AppController {/}: +2ms
[Nest] 58877  - 02/02/2023, 11:45:40 PM     LOG [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 58877  - 02/02/2023, 11:45:40 PM     LOG [NestApplication] Nest application successfully started +0ms
```

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.1

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^9.3.1",
    "@nestjs/core": "^9.3.1",
    "@nestjs/platform-express": "^9.3.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.1.9",
    "@nestjs/schematics": "^9.0.4",
    "@nestjs/testing": "^9.3.1",
    "@types/express": "^4.17.16",
    "@types/jest": "29.4.0",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.50.0",
    "@typescript-eslint/parser": "^5.50.0",
    "eslint": "^8.33.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "29.4.1",
    "prettier": "^2.8.3",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "29.0.5",
    "ts-loader": "^9.4.2",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.1.2",
    "typescript": "^4.9.5"
  },
```

### Node.js version

18.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
![image](https://user-images.githubusercontent.com/13461315/216469804-98e56957-27f6-4b00-9ca6-94714f74a7df.png)

you didn't build your project.

**Comment by beckend** [comment]
why would I build it?

**Comment by micalevisk** [comment]
yeeah, using `nest start` you don't have to build it yourself. I thought you were using `npm run start:prod` my bad

**Comment by micalevisk** [comment]
you can circumvent that by use the `entryFile` option in your `nest-cli.json` with the value `"main.mjs"` so it will run `node dist/src/main.mjs` instead

But it still won't start due to the lack of support of ESM (see #8736)

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/8736
