### ISSUE TITLE
Watch mode loops endlessly

### ISSUE THREAD

**Issue by Hareloo** [nestjs/nest#11038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello! 
I am experiencing a very weird bug:
In my personal home computer, I can create a NestJS project using the CLI and running with npm run start:dev with no problem.
In my laptop however, the exact same thing doesn't work - again, I am creating a default project with the NestJS cli but when I start it with npm run start:dev it loops endless with:
```
10:40:27 AM - File change detected. Starting incremental compilation...
10:40:27 AM - Found 0 errors. Watching for file changes.
```

I also tried to use tsc --watch and that does work on my laptop as well...
I don't even know where to begin debugging something like this, I'm talking about the default project and I'm using the same node, npm and typescript versions on both computers...
Would appreciate some help if possible

### Minimum reproduction code

Default project

### Expected behavior

Watch for file changes and only re-compile when those are detected.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```
{
  "name": "test-proj",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/*/.ts\" \"test/*/.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/*/.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "*/.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction). You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by Hareloo** [comment]
> Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction). You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

Well that's part of the problem - you probably wouldn't be able to reproduce this.
It only happens on some of my work laptops...
I just want to know if other people encountered this and how I could possibly find the issue...

**Comment by jmcdo29** [comment]
If I _had_ to guess, this would be a windows specific thing with typescript 4.9 due to how watched files are computed. I've got no clue otherwise though. Especially cause you said `tsc --watch` ([that's all we end up calling](https://github.com/nestjs/nest-cli/blob/master/lib/compiler/watch-compiler.ts#L121)) doesn't endlessly run

**Comment by Hareloo** [comment]
> If I _had_ to guess, this would be a windows specific thing with typescript 4.9 due to how watched files are computed. I've got no clue otherwise though. Especially cause you said `tsc --watch` ([that's all we end up calling](https://github.com/nestjs/nest-cli/blob/master/lib/compiler/watch-compiler.ts#L121)) doesn't endlessly run

Well there's more to it than tsc --watch because tsc --watch doesn't actually start the project for me, just compiles the files..

**Comment by jmcdo29** [comment]
> Well there's got to be more to it than tsc --watch because tsc --watch doesn't actually start the project for me, just compiles the files..

You're right, we call `node dist/main` after compilation completes. `tsc --watch` is what would be an issue here though because you are staying in the compilation loop. Unless you've modified the base `nest new` project to create some file that `tsc` is aware of on startup which would cause this, the start up of the server shouldn't be causing tsc to retrigger

**Comment by Hareloo** [comment]
> > Well there's got to be more to it than tsc --watch because tsc --watch doesn't actually start the project for me, just compiles the files..
> 
> You're right, we call `node dist/main` after compilation completes. `tsc --watch` is what would be an issue here though because you are staying in the compilation loop. Unless you've modified the base `nest new` project to create some file that `tsc` is aware of on startup which would cause this, the start up of the server shouldn't be causing tsc to retrigger

Is there a way (or maybe this already happens) to make `nest start --watch` print the detected file that changed to the console or a log file or something? Maybe then I would have some clue as to why this is happenning...

**Comment by jmcdo29** [comment]
> Is there a way (or maybe this already happens) to make nest start --watch print the detected file that changed to the console or a log file or something? Maybe then I would have some clue as to why this is happenning...

Again, it's typescript that sees the changed file. Nest just starts up the `tsc --watch` action programmatically. We don't watch for the file ourselves

**Comment by Hareloo** [comment]
> > Is there a way (or maybe this already happens) to make nest start --watch print the detected file that changed to the console or a log file or something? Maybe then I would have some clue as to why this is happenning...
> 
> Again, it's typescript that sees the changed file. Nest just starts up the `tsc --watch` action programmatically. We don't watch for the file ourselves
I understand...
Do you have any suggestions how I could possibly debug this problem?

**Comment by micalevisk** [comment]
@Hareloo read this: https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#file-watching-changes

**Comment by Hareloo** [comment]
> @Hareloo read this: https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#file-watching-now-uses-file-system-events

Mm interesting... But if it's a version thing how is it possible that it works on one machine but not on the other one even though they are using the same version?

**Comment by micalevisk** [comment]
yes, SO works like that, you know

**Comment by micalevisk** [comment]
I suggest you to play with `watchOptions`: https://www.typescriptlang.org/docs/handbook/configuring-watch.html

**Comment by Hareloo** [comment]
> I suggest you to play with `watchOptions`: https://www.typescriptlang.org/docs/handbook/configuring-watch.html

Thank you so much, this solved my problem, I was looking for a solution for weeks now.
All I needed to do is change watchFile under watchOptions to use polling instead of fsEvents and it works like a charm.

**Comment by micalevisk** [comment]
@Hareloo could you please add a new section at https://docs.nestjs.com/faq/common-errors to guide windows users that are using `typescript@^4.9` towards that solution?

That's not the first time I saw people complaining with `@nestjs/cli` right after upgrading TS to 4.9 on windows

**Comment by duoduoObama** [comment]
hi @Hareloo ,May I ask what configuration did you modify to solve this problem? I have been troubled for a long time, but I have read your docs and found no solution steps.

**Comment by igortas** [comment]
This is not working in nx with incremental set to true  on linux/wsl2
