### ISSUE TITLE
Definition of @ApiOperation outside a controller does not respect summary

### ISSUE THREAD

**Issue by Motii1** [nestjs/nest#11037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I wanted to have a wrapper on `@ApiOperation`, it's definition explains itself
```typescript
export const MockedApiOperation = (opts: ApiOperationOptions) =>
  applyDecorators(
    ApiTags('fake'),
    ApiOperation({ ...opts, summary: `[MOCK] ${opts.summary}` }),
  );
```
Unfortunately when I am using it on a method in a controller, e.g.
```typescript
export class ProfileController {
  @MockedApiOperation({ summary: 'Get profile details as a logged user' })
  @ApiBearerAuth()
  @UserJwt()
  @Get('/me')
  async getProfile(@LoggedUser() caller: User): Promise<ProfileDto> {
    return ProfileDto.from({
      id: caller.id,
      firstName: 'Mariusz',
      lastName: 'Pudzianowski',
      gender: Gender.Male,
      phoneNumber: '+48123456789',
      dateOfBirth: new Date('07-02-1977'),
      email: 'marian@gmail.com',
      nationalIdentificationNumber: null,
      imageUrl: null,
    });
  }
}
```
swagger displayed in the browser does not display `summary`

### Minimum reproduction code

https://pastebin.com/XkZFVLn3

### Expected behavior

The summary should be displayed in the swagger in the browser.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

9.1.1

### Packages versions

```json
"dependencies": {
    "@aws-sdk/client-sesv2": "^3.254.0",
    "@aws-sdk/client-sns": "^3.245.0",
    "@aws-sdk/node-http-handler": "^3.226.0",
    "@aws-sdk/types": "^3.226.0",
    "@nestjs/common": "^9.1.1",
    "@nestjs/core": "^9.1.1",
    "@nestjs/jwt": "^10.0.1",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.1.1",
    "@nestjs/swagger": "^6.1.2",
    "@nestjs/typeorm": "^9.0.1",
    "@sentry/cli": "^2.5.2",
    "@sentry/node": "^7.13.0",
    "@sentry/tracing": "^7.13.0",
    "@sentry/types": "^7.13.0",
    "@types/lodash": "^4.14.180",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.1",
    "dayjs": "^1.11.7",
    "dotenv": "^16.0.3",
    "jest-junit": "^14.0.1",
    "lodash": "^4.17.21",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "pg": "^8.8.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "superagent": "^8.0.0",
    "swagger-ui-express": "^4.1.6",
    "typeorm": "^0.3.11",
    "typeorm-naming-strategies": "^4.1.0",
    "uuid": "^9.0.0",
    "winston": "^3.3.3",
    "winston-loggly-bulk": "^3.2.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.1.3",
    "@nestjs/schematics": "^9.0.3",
    "@nestjs/testing": "^9.1.1",
    "@types/bcrypt": "^5.0.0",
    "@types/dotenv": "^8.2.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^29.0.3",
    "@types/node": "^18.7.18",
    "@types/passport-jwt": "^3.0.8",
    "@types/supertest": "^2.0.11",
    "@types/uuid": "^9.0.0",
    "@types/winston-loggly-bulk": "^3.0.1",
    "@typescript-eslint/eslint-plugin": "^5.38.0",
    "@typescript-eslint/parser": "^5.38.0",
    "eslint": "^8.23.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.0.3",
    "pre-commit": "^1.2.2",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^29.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^4.1.0",
    "typescript": "^4.3.5"
  },
```

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

swagger config
```typescript
const document = SwaggerModule.createDocument(
    app,
    new DocumentBuilder()
      .setTitle('example')
      .setVersion('1.0.0')
      .build(),
  );

  SwaggerModule.setup('/api', app, document);
```

**Comment by micalevisk** [comment]
I just tested with `@nestjs/swagger@6.1.4` and it worked as expected

![image](https://user-images.githubusercontent.com/13461315/216649574-74739ab2-7218-450c-9a9b-c3378f308029.png)


![image](https://user-images.githubusercontent.com/13461315/216648942-cd4a72b2-d047-4232-9fdb-ececa8d1d5d6.png)

---

Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction). You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
