### ISSUE TITLE
use multiple ws adapters in app, ws & socket.io

### ISSUE THREAD

**Issue by Nishchit14** [nestjs/nest#11047]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In my case, I need to implement **native/raw WebSocket** with **SocketIo** gateways.

in the `maiin.ts`, I have tried this but it's not working
```
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  app.useWebSocketAdapter(new WsAdapter(app));
  app.useWebSocketAdapter(new IoAdapter(app));
  await app.listen(3000);
```
When I use both gateways together then it's not working, If I use single at a time (by commenting another one) then It's working.

### Describe the solution you'd like

There would be a solution where It can be configured to use two ws protocols together. One gateway for WS and another gateway for SocketIo.

### Teachability, documentation, adoption, migration strategy

It should be documented here, https://docs.nestjs.com/websockets/adapter

### What is the motivation / use case for changing the behavior?

My application is serving the web on SocketIO and serves the old version with raw WebSocket to support backward compatibility.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
