### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module (Graphql-Upload)

### ISSUE THREAD

**Issue by ryskin** [nestjs/nest#11046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

"Nest.js should fix Nest.js bugs or else users will have to abandon it as it will no longer be fit for purpose as many important npm packages are being published in standard ESM format."

<img width="797" alt="image" src="https://user-images.githubusercontent.com/3756722/216805890-1c5d151b-f2a4-4393-acf8-5e4f7ad14306.png">

### Minimum reproduction code

https://github.com/jaydenseric/graphql-upload/issues/332

### Expected behavior

Should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

{
  "name": "rent-bike-api",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@admin-bro/nestjs": "^1.1.0",
    "@adminjs/express": "^5.1.0",
    "@adminjs/nestjs": "^5.1.0",
    "@adminjs/typeorm": "^4.0.0",
    "@nestjs/apollo": "^10.1.7",
    "@nestjs/common": "^9.2.1",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.2.1",
    "@nestjs/graphql": "^10.1.7",
    "@nestjs/jwt": "^10.0.1",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.2.1",
    "@nestjs/typeorm": "^9.0.1",
    "@types/passport-jwt": "^3.0.8",
    "adminjs": "^6.8.2",
    "apollo-server-express": "^3.11.1",
    "class-validator": "^0.14.0",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "graphql": "^16.6.0",
    "graphql-tools": "^8.3.16",
    "graphql-upload": "16",
    "npm": "^9.4.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "pg": "^8.8.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^4.1.2",
    "rxjs": "^7.8.0",
    "typeorm": "^0.3.11"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.1.9",
    "@nestjs/schematics": "^9.0.4",
    "@nestjs/testing": "^9.2.1",
    "@types/express": "^4.17.16",
    "@types/jest": "29.4.0",
    "@types/node": "^18.11.18",
    "@types/passport-local": "^1.0.35",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.49.0",
    "@typescript-eslint/parser": "^5.49.0",
    "eslint": "^8.32.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "29.4.1",
    "prettier": "^2.8.3",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "29.0.5",
    "ts-loader": "^9.4.2",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.1.2",
    "typeorm-uml": "^1.6.5",
    "typescript": "^4.9.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Until we support ESM modules, you can use dynamic imports and the `compilerOption.moduleResolution: Node16` option in your `tsconfig` so that you can `const gqlUpload = await import('graphql-upload')`
