### ISSUE TITLE
Injected REQUEST object is always "undefined"

### ISSUE THREAD

**Issue by ww917352** [nestjs/nest#11055]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

9.2.1->9.3.1

### Describe the regression

We inject `REQUEST` (from `@nestjs/core`) to request scoped method ({scope: Scope.REQUEST}). It worked fine until the upgrade of NestJS core to 9.3.x. Now it always contains `undefined`.

### Input code

```ts

```

### Expected behavior

The REQUEST object should contain the `express/Request` object.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/11002

Fixed in 9.3.3
