### ISSUE TITLE
Nestjs 9 fails silently during production initialisation

### ISSUE THREAD

**Issue by philosofonusus** [nestjs/nest#11057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Doesn't fully start server on initialisation step, can't trace it. Need your help

Im using planetscale mysql as a database and prisma orm

Using meilisearch for full-text search system

Redis for key-value demo, using dragonfly in reality. but the same behaviour

Seems like doesn't connect successfully database or meilisearch

```
node dist/main
api          | 
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [NestFactory] Starting Nest application...
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] AppModule dependencies initialized +72ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] PrismaModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] MailerModule dependencies initialized +1ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] JwtModule dependencies initialized +1ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] FileModule dependencies initialized +12ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] ThrottlerModule dependencies initialized +6ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] MailerCoreModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] CacheModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] MeiliSearchModule dependencies initialized +1ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] UsersModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] MailModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] RedisCacheModule dependencies initialized +1ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] GraphQLModule dependencies initialized +1ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] ProductsModule dependencies initialized +0ms
api          | [Nest] 19  - 02/06/2023, 4:38:16 PM     LOG [InstanceLoader] AuthModule dependencies initialized +1ms
```

### Minimum reproduction code

https://github.com/TETSUKAI/tetsukai_backend

### Steps to reproduce

docker compose up --build

### Expected behavior

Project successfully initialised and returns not empty status

### Package

- [ ] I don't know. Or some 3rd-party package
- [] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

prisma, meilisearch, redis, nestjs-meilisearch, meilisearch

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "tetsukai_backend",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@fastify/cookie": "^8.3.0",
    "@fastify/csrf": "^6.1.0",
    "@fastify/helmet": "^10.1.0",
    "@nestjs-modules/mailer": "^1.8.1",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^10.1.7",
    "@nestjs/jwt": "^10.0.1",
    "@nestjs/mercurius": "^10.1.7",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-fastify": "^9.2.1",
    "@nestjs/throttler": "^3.1.0",
    "@prisma/client": "^4.8.1",
    "argon2": "^0.30.3",
    "aws-sdk": "^2.1295.0",
    "cache-manager": "^5.1.4",
    "cache-manager-redis-store": "^3.0.1",
    "deep-email-validator": "^0.1.21",
    "graphql-upload-minimal": "^1.5.4",
    "meilisearch": "^0.30.0",
    "mercurius-upload": "^6.0.0",
    "nestjs-meilisearch": "^2.1.2",
    "nestjs-throttler-storage-redis": "^0.2.2",
    "passport-jwt": "^4.0.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "tinify": "^1.7.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
can please you try it out with nestjs v9.0.0 (not the latest, which is v9.3.3)

Also, share us the output of `npx nest info`

**Comment by Tony133** [comment]
@philosofonusus  have you tried commenting out this line

```
  await app.register(fastifyCsrf);
```

in `main.ts`  ?

**Comment by Tony133** [comment]
A solution by seeing your repository may be the following: 

use this `@fastify/csrf-protection` package instead of `@fastify/csrf` , see documentation nestjs [here](https://docs.nestjs.com/security/csrf#csrf-protection)

and edit the `main.ts` file like this:

```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from './prisma/prisma.service';
// import tinify from 'tinify';
import { fastifyCookie } from '@fastify/cookie';
import { fastifyHelmet } from '@fastify/helmet';
import fastifyCsrf from '@fastify/csrf-protection';

const MercuriusGQLUpload = require('mercurius-upload');
const OS = require('os');

process.env.UV_THREADPOOL_SIZE = OS.cpus().length;

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter({ pluginTimeout: 0, logger: true }),
  );
  const config = app.get(ConfigService);
  await app.register(fastifyCookie, {
    secret: config.get('COOKIE_SECRET'),
  });
  await app.register(fastifyHelmet);
  await app.register(fastifyCsrf);

  await app.enableCors({
    credentials: true,
    origin: [config.get('DOMAIN')],
  });
  await app.register(MercuriusGQLUpload);
  // tinify.key = config.get('tinifyKey');
  const prismaService = app.get(PrismaService);
  await prismaService.enableShutdownHooks(app);
  await app.listen(config.get('PORT'), '0.0.0.0', () =>
    console.log('Listening port' + config.get('PORT')),
  );
}
bootstrap();
```


however if you are having difficulties and need support use the support channel [discord](https://discord.com/invite/G7Qnnhy)

I hope I was helpful

**Comment by dansousa09** [comment]
I have the same problem and I just solved it when I downgraded the version of @nestjs/websockets to v9.2.1.

`(node:1) UnhandledPromiseRejectionWarning: TypeError: this.metadataScanner.getAllMethodNames is not a function
    at GatewayMetadataExplorer.explore (/usr/src/app/node_modules/@nestjs/websockets/gateway-metadata-explorer.js:13:14)
    at WebSocketsController.subscribeToServerEvents (/usr/src/app/node_modules/@nestjs/websockets/web-sockets-controller.js:33:61)
    at WebSocketsController.connectGatewayToServer (/usr/src/app/node_modules/@nestjs/websockets/web-sockets-controller.js:30:14)
    at SocketModule.connectGatewayToServer (/usr/src/app/node_modules/@nestjs/websockets/socket-module.js:47:35)
    at /usr/src/app/node_modules/@nestjs/websockets/socket-module.js:36:38
    at IteratorWithOperators.forEach (/usr/src/app/node_modules/iterare/lib/iterate.js:157:13)
    at SocketModule.connectAllGateways (/usr/src/app/node_modules/@nestjs/websockets/socket-module.js:36:14)
    at /usr/src/app/node_modules/@nestjs/websockets/socket-module.js:31:61
    at Map.forEach (<anonymous>)
    at SocketModule.register (/usr/src/app/node_modules/@nestjs/websockets/socket-module.js:31:17)
    at NestApplication.registerWsModule (/usr/src/app/node_modules/@nestjs/core/nest-application.js:83:27)
    at NestApplication.registerModules (/usr/src/app/node_modules/@nestjs/core/nest-application.js:72:14)
    at NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:91:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NestApplication.listen (/usr/src/app/node_modules/@nestjs/core/nest-application.js:147:33)
    at async bootstrap (/usr/src/app/dist/main.js:23:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by philosofonusus** [comment]
> A solution by seeing your repository may be the following:
> 
> use this `@fastify/csrf-protection` package instead of `@fastify/csrf` , see documentation nestjs [here](https://docs.nestjs.com/security/csrf#use-with-fastify)
> 
> and edit the `main.ts` file like this:
> 
> ```ts
> import { NestFactory } from '@nestjs/core';
> import {
>   FastifyAdapter,
>   NestFastifyApplication,
> } from '@nestjs/platform-fastify';
> import { AppModule } from './app.module';
> import { ConfigService } from '@nestjs/config';
> import { PrismaService } from './prisma/prisma.service';
> // import tinify from 'tinify';
> import { fastifyCookie } from '@fastify/cookie';
> import { fastifyHelmet } from '@fastify/helmet';
> import fastifyCsrf from '@fastify/csrf-protection';
> 
> const MercuriusGQLUpload = require('mercurius-upload');
> const OS = require('os');
> 
> process.env.UV_THREADPOOL_SIZE = OS.cpus().length;
> 
> async function bootstrap() {
>   const app = await NestFactory.create<NestFastifyApplication>(
>     AppModule,
>     new FastifyAdapter({ pluginTimeout: 0, logger: true }),
>   );
>   const config = app.get(ConfigService);
>   await app.register(fastifyCookie, {
>     secret: config.get('COOKIE_SECRET'),
>   });
>   await app.register(fastifyHelmet);
>   await app.register(fastifyCsrf);
> 
>   await app.enableCors({
>     credentials: true,
>     origin: [config.get('DOMAIN')],
>   });
>   await app.register(MercuriusGQLUpload);
>   // tinify.key = config.get('tinifyKey');
>   const prismaService = app.get(PrismaService);
>   await prismaService.enableShutdownHooks(app);
>   await app.listen(config.get('PORT'), '0.0.0.0', () =>
>     console.log('Listening port' + config.get('PORT')),
>   );
> }
> bootstrap();
> ```
> 
> however if you are having difficulties and need support use the support channel [discord](https://discord.com/invite/G7Qnnhy)
> 
> I hope I was helpful

Thank you very much, this helped me
