### ISSUE TITLE
Add ability to disable initialization logging

### ISSUE THREAD

**Issue by mainfraame** [nestjs/nest#11056]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Integrating nestjs into aws lambdas has been a god send for many developers. Unfortunately during the many cold starts, the initialization logs (routercontext, etc.) clutter the logs. This makes using the logs to debug often cumbersome. 

This same issue occurs for running api tests. You can disable it by setting it to silent, but this isn’t ideal for all cases. 

### Describe the solution you'd like

Add a flag to NestFactory.create to disable the initialization logs:
```
disableInitLogging: true
```

### Teachability, documentation, adoption, migration strategy

This can be associated with any docs on serverless or testing. 

### What is the motivation / use case for changing the behavior?

As mentioned, for testing and in lambda environments, these initialization logs are just unnecessary noise you have to sift through.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
