### ISSUE TITLE
@nestjs/websockets 9.3.3 failure

### ISSUE THREAD

**Issue by MarcP9** [nestjs/nest#11065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In this new version when trying to work whit a Gateway, it crash saying

 TypeError: this.metadataScanner.getAllMethodNames is not a function at GatewayMetadataExplorer.explore (/app/node_modules/@nestjs/websockets/gateway-metadata-explorer.js:13:14)

Imposible to make work the documentation examples, think that not happends when i use the library version 9.2.*

### Minimum reproduction code

https://github.com/nestjs/nest

### Expected behavior

thats, my chatGateway test:

import { SubscribeMessage, WebSocketGateway, WebSocketServer } from '@nestjs/websockets';
import { Socket, Server } from 'socket.io';

@WebSocketGateway({ cors: true })
export class ChatGateway
{

  @WebSocketServer()
  server: Server;

  @SubscribeMessage('sendMessage')
  async handleSendMessage(client: Socket, payload: string): Promise<string> {
      return 'hello world!!!!';
  }
}

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
what's the output of `npx nest info`?

**Comment by kamilmysliwiec** [comment]
Make sure your `@nestjs/websockets` package version matches the version of `@nestjs/core`
