### ISSUE TITLE
"perf(core): change sha1 to xxhash" commit broke runtime of Nest.js application on Ubuntu 20.04

### ISSUE THREAD

**Issue by fiki574** [nestjs/nest#11071]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

7f43821d4810e6b2eff87f159eac2a8177f2736a

### NestJS version

9.3.2 -> 9.3.5

### Describe the regression

So, I've upgraded @nestjs/common and @nestjs/core dependencies from 9.3.2. to 9.3.5. Decided to run them on my PC with Windows 10, runs perfectly, all good. Pushed to my Github and let the Actions complete the build and deployment processes, and this is "docker logs" output of the container that runs my Nest.js application.

```
Error: Cannot find module '@node-rs/xxhash-linux-x64-gnu'
Require stack:
- /app/node_modules/@node-rs/xxhash/index.js
- /app/node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js
- /app/node_modules/@nestjs/core/inspector/uuid-factory.js
- /app/node_modules/@nestjs/core/injector/instance-wrapper.js
- /app/node_modules/@nestjs/core/injector/injector.js
- /app/node_modules/@nestjs/core/injector/module-ref.js
- /app/node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js
- /app/node_modules/@nestjs/core/inspector/serialized-graph.js
- /app/node_modules/@nestjs/core/injector/container.js
- /app/node_modules/@nestjs/core/injector/index.js
- /app/node_modules/@nestjs/core/index.js
- /app/dist/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/app/node_modules/@node-rs/xxhash/index.js:172:31)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@node-rs/xxhash/index.js',
    '/app/node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js',
    '/app/node_modules/@nestjs/core/inspector/uuid-factory.js',
    '/app/node_modules/@nestjs/core/injector/instance-wrapper.js',
    '/app/node_modules/@nestjs/core/injector/injector.js',
    '/app/node_modules/@nestjs/core/injector/module-ref.js',
    '/app/node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js',
    '/app/node_modules/@nestjs/core/inspector/serialized-graph.js',
    '/app/node_modules/@nestjs/core/injector/container.js',
    '/app/node_modules/@nestjs/core/injector/index.js',
    '/app/node_modules/@nestjs/core/index.js',
    '/app/dist/main.js'
  ]
}
```

### Input code

```ts

```

### Expected behavior

Application should run normally on Ubuntu 20.04, just like it does on Windows 10.

### Other

Runs on Github hosted Ubuntu runners, this is Actions response for a simple unit test stage:
![image](https://user-images.githubusercontent.com/10419719/217326719-5000f31c-1af4-430a-bb64-e17071c2bf65.png)

Produces pretty much the same error:

```
Require stack:
      node_modules/@node-rs/xxhash/index.js
      node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js
      node_modules/@nestjs/core/inspector/uuid-factory.js
      node_modules/@nestjs/core/injector/instance-wrapper.js
      node_modules/@nestjs/core/injector/injector.js
      node_modules/@nestjs/core/injector/module-ref.js
      node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js
      node_modules/@nestjs/core/inspector/serialized-graph.js
      node_modules/@nestjs/core/injector/container.js
      node_modules/@nestjs/testing/testing-module.builder.js
      node_modules/@nestjs/testing/test.js
      node_modules/@nestjs/testing/index.js
      src/tests/auth.controller.spec.ts

    > 1 | import { Test, TestingModule } from "@nestjs/testing";
        | ^
      2 | import { I18nContext } from "nestjs-i18n";
      3 | import { getMockReq, getMockRes } from "@jest-mock/express";
      4 | import { UserService } from "@user/services";

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (node_modules/@node-rs/xxhash/index.js:[17](https://github.com/Pinehood/ph-s2u-backend/actions/runs/4116536300/jobs/7106703742#step:7:18)2:31)
      at Object.<anonymous> (node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js:4:[18](https://github.com/Pinehood/ph-s2u-backend/actions/runs/4116536300/jobs/7106703742#step:7:19))
      at Object.<anonymous> (node_modules/@nestjs/core/inspector/uuid-factory.js:5:39)
      at Object.<anonymous> (node_modules/@nestjs/core/injector/instance-wrapper.js:11:24)
      at Object.<anonymous> (node_modules/@nestjs/core/injector/injector.js:14:28)
      at Object.<anonymous> (node_modules/@nestjs/core/injector/module-ref.js:8:[20](https://github.com/Pinehood/ph-s2u-backend/actions/runs/4116536300/jobs/7106703742#step:7:21))
      at Object.<anonymous> (node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js:5:22)
      at Object.<anonymous> (node_modules/@nestjs/core/inspector/serialized-graph.js:8:30)
      at Object.<anonymous> (node_modules/@nestjs/core/injector/container.js:6:28)
      at Object.<anonymous> (node_modules/@nestjs/testing/testing-module.builder.js:6:[21](https://github.com/Pinehood/ph-s2u-backend/actions/runs/4116536300/jobs/7106703742#step:7:22))
      at Object.<anonymous> (node_modules/@nestjs/testing/test.js:5:34)
      at Object.<anonymous> (node_modules/@nestjs/testing/index.js:11:[22](https://github.com/Pinehood/ph-s2u-backend/actions/runs/4116536300/jobs/7106703742#step:7:23))
      at Object.<anonymous> (src/tests/auth.controller.spec.ts:1:1)
```

**Comment by micalevisk** [comment]
it works on my Ubuntu 20.04 and on my CI pipeline on GH which uses Ubuntu.

Could you share your workflow file?

**Comment by jmcdo29** [comment]
I would hazard a guess that `@node-rs/xxhash` generates different code on Windows 10 and Linux-x64 and the `npm ci` is just getting the `Windows 10` variant due to respecting the lockfile while the runtime is trying to access the `linux-x64` specific files. If you could generate a lockfile for ubuntu/linux-x64 that would fix this up. 

I'll look into the package and see what they suggest as well. I know we just switched to it for performance purposes

**Comment by fiki574** [comment]
Right, but this is very problematic for Windows developers, and is a very breaking change to introduce for a patch version upgrade, to be fair.

Here's my Dockerfile that might help in reproducing the error:
```
FROM node:lts-bullseye-slim

WORKDIR /app
COPY . /app

RUN npm ci
RUN npm run build

EXPOSE 3000
CMD ["node", "dist/main"]
```

For now, I downgraded the problematic dependencies to 9.3.2 from 9.3.5 so all services and pipes I have work now, but would be nice to have an official fix and support of future version normally, without these additional generations and manual steps I need to take for the interop.

Nevertheless, thanks for your work and response time, it's amazing!

**Comment by H4ad** [comment]
From what I have look, `napi-rs/xxhash` uses the same strategy of `esbuild` to distribute the packages, [xxhash](https://www.npmjs.com/package/@node-rs/xxhash?activeTab=explore) and [esbuild](https://github.com/evanw/esbuild/blob/main/npm/esbuild/package.json#L17).

From what I understand, `npm` resolves to the correct package depending on the machine that is running the install, if it is Linux 64bits, then `linux-x64` will be chosen.

Things can get worse when you mix the architecture of the CI systems, like building in Linux 64 and then deploying in another architecture.

But as fiki said, I think this could be marked as a breaking change because of the way it breaks the deployment process. So I don't know if worth it to recommend fixing the CI or just reverting the package for now and using `crypto.createHash('sha1')` instead, and then in nestjs 10 we introduce this package.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this @H4ad? If you still have benchmarks comparing sha1 vs xxhash & could link them in the PR that would be ideal (I think you've already shared them with me earlier).

**Comment by H4ad** [comment]
Yes, I can!

About the benchmarks, I will put in the PR but just to give you a idea:

```
uuid v4 x 14,449,798 ops/sec ±2.08% (75 runs sampled)
uuid v5 x 182,749 ops/sec ±1.26% (80 runs sampled)
sha1 x 396,744 ops/sec ±3.76% (72 runs sampled)
napi-rs/blake x 395,341 ops/sec ±4.28% (65 runs sampled)
nanoid x 2,735,417 ops/sec ±1.01% (78 runs sampled)
uid x 39,619,464 ops/sec ±2.39% (76 runs sampled)
luuked x 3,931,161 ops/sec ±3.93% (73 runs sampled)
napi-rs/uuid x 4,509,946 ops/sec ±1.83% (76 runs sampled)
node-rs/xxHash xxh32 x 3,104,990 ops/sec ±1.90% (76 runs sampled)
node-rs/xxHash xxh64 x 2,985,482 ops/sec ±1.74% (79 runs sampled)
Fastest is uid
```

`sha1` is slower than `xxHash` but faster than using `uuid-v5`.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11073
