### ISSUE TITLE
Throwing 404 when accessing controllers containing similar prefix within path

### ISSUE THREAD

**Issue by md-shah** [nestjs/nest#11086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We have these 4 APIs in three controllers. One of them is having a path parameter and other two of them are sharing a common "store" prefix in the route.

> 1. /:accountType/profile // ProfileController
> 2. /:accountType/profile/tags // ProfileController
> 3. /store/profile // StoreProfileController
> 4. /store/management // StoreManagementController

When we try to access the `"/store/profile/tags"`, it will throw 404 saying that the route is not found. 

```
{
    "statusCode": 404,
    "message": "Cannot GET /store/profile/tags",
    "error": "Not Found"
}
```

### Minimum reproduction code

https://github.com/md-shah/nest-js-issue-report

### Steps to reproduce

1. npm install
2. go to localhost:3000/store/profile/tags
3. This will throw error 404

### Expected behavior

Since there are no duplicated routes `"/store/profile/tags"`, it should go to ProfileController instead of throwing 404.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.6.15

### Packages versions

```json
    "@nestjs/common": "^7.6.15",
    "@nestjs/core": "^7.6.15",
    "@nestjs/platform-express": "^7.6.15",
    "@nestjs/platform-fastify": "^7.6.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.6"
```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
actually, that's not a bug. It's even how v8 and v9, works. See the hint at https://docs.nestjs.com/controllers#route-parameters
