### ISSUE TITLE
Handle connection failures gracefully

### ISSUE THREAD

**Issue by Hareloo** [nestjs/nest#11084]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I cannot handle cases where Redis or TypeORM connections fail, the app throws an exceptions and just exits

### Describe the solution you'd like

I would like to have a way to handle situations like this even in ways that will prevent the app from crashing even when it can't form a connection.

### Teachability, documentation, adoption, migration strategy

I don't know

### What is the motivation / use case for changing the behavior?

 Cases in which one may need to handle situations as described and not crash the app

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
