### ISSUE TITLE
feat: detect input file type from buffer

### ISSUE THREAD

**Issue by mohamadrezamomeni** [nestjs/nest#11082]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have to detect file type from buffer in my project after exploring nestjs documentation, I didn't find any feature about. I resolve this issue with another library

### Describe the solution you'd like

I'm going to develop this feature in nestjs. I'm going to develop this feature then send pull request. I can develop this feature in two way . I can use popular library or I can develop this feature natively in nestjs. @kamilmysliwiec  can you give me some suggestions?

### Teachability, documentation, adoption, migration strategy

users can use built-in pipeline nestjs for detecting file type

### What is the motivation / use case for changing the behavior?

I think this feature is good idea for controlling input file type

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
