### ISSUE TITLE
ModuleRef.create not initializing Scope.TRANSIENT dependencies correctly

### ISSUE THREAD

**Issue by smasry-thiqah** [nestjs/nest#11085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have these two services
```typescript
@Injectable()
export class DogService implements IDog {
  constructor(private logger: Logger) {
    this.logger.log('dog service loaded');
  }

  whoAmI() {
    return 'the real dog';
  }
}
```
and

```typescript
import { Injectable, Logger } from '@nestjs/common';
import { IDog } from './dog.interface';

@Injectable()
export class DogMockService implements IDog {
  constructor(private logger: Logger) {
    this.logger.log('dog mock service loaded');
  }

  whoAmI() {
    return 'the mocked dog';
  }
}
```
both of them are with the default Scope but both are injecting the  logger which is marked as transient in the module
here's my module configuration:
```typescript
@Module({
  imports: [ConfigModule.forRoot()],
  controllers: [AppController],
  providers: [
    AppService,
    CatService,
    {
      provide: Logger,
      useFactory: (inquirer: object) => {
        return new Logger(inquirer.constructor.name);
      },
      inject: [INQUIRER],
      scope: Scope.TRANSIENT,
    },
    {
      provide: DOG,
      useFactory: (config: ConfigService, moduleRef: ModuleRef) => {
        if (config.get('USE_MOCK') === 'true') {
          return moduleRef.create(DogMockService);
        } else {
          return moduleRef.create(DogService);
        }
      },
      inject: [ConfigService, ModuleRef],
    },
  ],
})
export class AppModule {}
```
I use the module ref to create the desired class "either real or mocked" based on some environment variable.
but currently it doesn't inject the logger which is of scope transient

### Minimum reproduction code

https://codesandbox.io/p/sandbox/determined-hoover-4yjsp2

### Expected behavior

Moduleref.create() to resolve the needed transient dependencies

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.*

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "2.3.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.5"
  }
}
```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Oh yeah, we should probably clarify this in the docs. You should (almost) never use the `ModuleRef` inside a factory provider - module isn't yet initialized at this point and you might be getting odd results (like this one).

For your use case, I'd just register both `DogMockService` and `DogService` as providers, inject them into the `DOG` factory, and then conditionally select the one that I want to use.

**Comment by micalevisk** [comment]
@smasry-thiqah feel free to suggest any improvement to the docs repo to clarify this limitation of injecting ModuleRef into factory providers.
