### ISSUE TITLE
Invalid definition for directive "@tag"

### ISSUE THREAD

**Issue by pablom58** [nestjs/nest#11095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am getting this error:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/53399357/218079573-5936ab24-7f6c-4cfa-9f8e-53eb8441871d.png">

This is my AppModule

<img width="659" alt="image" src="https://user-images.githubusercontent.com/53399357/218080103-91c62d97-7d47-4b9b-adda-82ba31de4e1b.png">

I am configuring a monorepo with NX, node version 16.13.0

The error is that when nestjs generates the graphql schema is adding an extra valio to directive @tag definition

The expected value is: 
directive @tag(name: String!) repeatable on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

But it is adding a SCHEMA field that is what causes the error:
directive @tag(name: String!) repeatable on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | SCHEMA | UNION

### Minimum reproduction code

https://github.com/pablom58/graphql-issue

### Steps to reproduce

yarn
npx nx run users:serve

### Expected behavior

<img width="783" alt="image" src="https://user-images.githubusercontent.com/53399357/218081334-69341837-2a45-432d-9e73-19fc40d16681.png">

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

graphql

### NestJS version

9.0.0

### Packages versions

```json
{
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "dependencies": {
    "@apollo/federation": "^0.38.1",
    "@apollo/subgraph": "^2.2.1",
    "@nestjs-query/core": "^0.30.0",
    "@nestjs-query/query-graphql": "^0.30.0",
    "@nestjs-query/query-typeorm": "^0.30.0",
    "@nestjs/apollo": "^10.1.6",
    "@nestjs/common": "^9.2.1",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^10.1.7",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/typeorm": "^9.0.1",
    "apollo-server-express": "^3.11.1",
    "axios": "^1.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "dataloader": "^2.2.1",
    "graphql": "^16.6.0",
    "graphql-query-complexity": "^0.12.0",
    "graphql-subscriptions": "^2.0.0",
    "pg": "^8.9.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.0.0",
    "tslib": "^2.3.0",
    "typeorm": "^0.3.12"
  },
  "devDependencies": {
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@nrwl/eslint-plugin-nx": "15.6.3",
    "@nrwl/jest": "15.6.3",
    "@nrwl/linter": "15.6.3",
    "@nrwl/nest": "15.6.3",
    "@nrwl/node": "15.6.3",
    "@nrwl/webpack": "15.6.3",
    "@nrwl/workspace": "15.6.3",
    "@types/jest": "28.1.1",
    "@types/node": "18.7.1",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "nx": "15.6.3",
    "prettier": "^2.6.2",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.8.2"
  }
}

```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
