### ISSUE TITLE
AuthGaurd not working in Microservice Gateway

### ISSUE THREAD

**Issue by nqhd3v** [nestjs/nest#11099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Today, I am converting a monolithic app to a microservice app. Everythings are OK to send and receive request or response between services. But, when I am trying to apply UseGaurds for my routes in the API gateway, It shows the error when I start the app:

`ERROR [ExceptionHandler] Cannot read properties of undefined (reading '__guards__')`

I don't know why, but in NestJS app docs, they said should use RpcException instead HttpException, and nothing more. I tried it but failed too.

Thanks for your help!

### Minimum reproduction code

https://github.com/nqhd3v/cyberlogitec-kafak/tree/main/api-gateway

### Steps to reproduce

1. yarn
2. yarn start:dev

### Expected behavior

App started with log "Running with port XXXXX"

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.7

### Packages versions

```json
{
  "name": "terminal-apis",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.3.0",
    "@nestjs/core": "^9.3.7",
    "@nestjs/jwt": "^10.0.1",
    "@nestjs/microservices": "^9.3.7",
    "@nestjs/passport": "^9.0.1",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/serve-static": "^3.0.0",
    "@nestjs/typeorm": "^9.0.1",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cookie-parser": "^1.4.6",
    "joi": "^17.7.0",
    "kafkajs": "^2.2.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "pg": "^8.9.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.11"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/cookie-parser": "^1.4.3",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/multer": "^1.4.7",
    "@types/node": "^16.0.0",
    "@types/passport-jwt": "^3.0.8",
    "@types/passport-local": "^1.0.35",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

16.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
hi! thanks for reporting :smiley_cat: 

your minimum repro is quite big, and the _steps to reproduce_ section is supposed to have all the steps to reproduce the issue, which isn't the case.

**Comment by nqhd3v** [comment]
oh no, actually you just need to start the api-gateway app, because it's having the same problem as above

**Comment by jmcdo29** [comment]
Make sure `@nestjs/common`, `@nestjs/core`, and `@nestjs/microservices` are all on the same major.minor.patch version

**Comment by nqhd3v** [comment]
Amazing :) It runs! Thank you so much! Absolutely, sorry so much, but I know this is not the case, but when I clone this project from a monolithic nestjs app, It doesn't run as I expected!

**Comment by zanminkian** [comment]
> Make sure `@nestjs/common`, `@nestjs/core`, and `@nestjs/microservices` are all on the same major.minor.patch version

@jmcdo29  I have saw so many issues caused by this reason. Do we have a good way to reduce these problems?

**Comment by micalevisk** [comment]
@zanminkian what about this: https://github.com/nestjs/nest-cli/issues/1929

**Comment by zanminkian** [comment]
@micalevisk It's the shortcoming of `nestjs/nest` monorepo. I think, it should lock peerDependencies in specific version. It should upgrade the specific peerDependencies when upgrading the sub package version.
