### ISSUE TITLE
Circular dependency between two factory providers (add error message & throw)

### ISSUE THREAD

**Issue by lybrus** [nestjs/nest#11093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```typescript
export const dynamicProvider1 = {
  provide: 'PROVIDER1',
  useFactory: (provider2: any) => {
    setTimeout(() => {
      console.log('from provider 1', provider2);
    }, 1);
    return {
      name: 'provider 1',
    };
  },
  inject: ['PROVIDER2'],
};

export const dynamicProvider2 = {
  provide: 'PROVIDER2',
  useFactory: (provider1: any) => {
    setTimeout(() => {
      console.log('from provider 2', provider1);
    }, 1);
    return {
      name: 'provider 2',
    };
  },
  inject: ['PROVIDER1'],
};
```

No errors, nothing output.

### Minimum reproduction code

https://github.com/lybrus/dynamic-providers-circular-dependency

### Steps to reproduce

1. npm i
2. npm run start:dev
3. The application hangs on `LOG [NestFactory] Starting Nest application...`

### Expected behavior

Error

or

Output in some sequence, but I have no idea how to use forwardRef in this case.

`
from provider 2 { name: "provider 1" }
from provider 1 { name: "provider 2" }
`

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

It would be better to have an error message.

**Comment by kamilmysliwiec** [comment]
Using forward refs (and generally circular imports) between factory providers wouldn't make any sense since the factory function is called once (and only once). We should improve the DX though by either ignoring this provider & printing an error message, or just terminating/crashing the application on init.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11126
