### ISSUE TITLE
ConfigurableModuleClass registerAsync wrongly generates empty imports

### ISSUE THREAD

**Issue by tbglazer** [nestjs/nest#11097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ConfigurableModuleClass  super.registerAsync() generates empty imports:[] overriding any imports existing before. 

### Minimum reproduction code

no reproduction code

### Expected behavior

Should not generate empty imports.
As a workaround call ...super.registerAsync() before adding any imports (unlike the documentation)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.6

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I didn't manage to reproduce this.

Please provide a minimum reproduction repository. You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
