### ISSUE TITLE
Expand API versioning to file generating

### ISSUE THREAD

**Issue by mertsafter** [nestjs/nest#11101]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It's not a problem I am facing but I think it would be a nice feature. As I understood, the API versioning does not affect any file generating like "nest generate controller". Wouldn't it be nice to also include the version in newly generated files?

### Describe the solution you'd like

As a nestjs developer I want to have my newly generated files to also include versioning within the name, if I provide the needed information as a parameter.
For example:
nest generate controller app --version 2
result:
app.v2.controller.ts

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

To have a well-documented and strictly file-separated structure of my API versioning while also defining a naming convention of controller/services for API versioning

**Comment by micalevisk** [comment]
hi!

how the content how that generated file would look like?

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
