### ISSUE TITLE
DB Seeder

### ISSUE THREAD

**Issue by miladezzat** [nestjs/nest#11100]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to make seeding databases

### Describe the solution you'd like

I have npm package for adding seeder
https://www.npmjs.com/package/nestjs-db-seederan 

### Teachability, documentation, adoption, migration strategy

it's just a suggestion for the npm for seeder

### What is the motivation / use case for changing the behavior?

if you add dummy data, or if you seed some real data

**Comment by miladezzat** [comment]
@kamilmysliwiec

**Comment by jmcdo29** [comment]
There are no plans to bring this package or functionality into the `@nestjs/` scope. There's too many sub-databases to/ORMs to manage _on top of_ the already existing mongo, sequelize, and typeorm wrappers. If you feel this can be provided as a community package, we'd be happy to mention it on the [awesome NestJS repo](https://github.com/nestjs/awesome-nestjs).

**Comment by miladezzat** [comment]
@jmcdo29 this package works with any orm at least with `mongoose`, `prisma`,  `sequelize` and `typeORM`

**Comment by jmcdo29** [comment]
Great! I stand by what I said
