### ISSUE TITLE
DRPC

### ISSUE THREAD

**Issue by dedychaidir** [nestjs/nest#11116]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Is DRPC compatible with NestJS? Any idea how to use it with DRPC? I don't find any tutorials for it

### Describe the solution you'd like

Any answer, if DRPC is able to be accomodate

### Teachability, documentation, adoption, migration strategy

Any tutorials or documentation

### What is the motivation / use case for changing the behavior?

I've read on some websites that DRPC is more effective rather than GRPC

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
