### ISSUE TITLE
Upgrade @apollo/subgraph above 2.3.0 cause errors

### ISSUE THREAD

**Issue by geekmini** [nestjs/nest#11138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've upgrade form @apollo/subgraph from 2.2.3 to 2.3.1 but found this errors on tags.

```txt
"@tag" should have locations field_definition, object, interface, union, argument_definition, scalar, enum, 
enum_value, input_object, input_field_definition, but found (non-subset) field_definition, 
object, interface, union, argument_definition, scalar, enum, enum_value, input_object, 
input_field_definition, schema
```

### Minimum reproduction code

https://github.com/geekmini/nestjs-federation-build-error

### Steps to reproduce

- `npm ci`
- `npm run start`

Then you will get the @tags directive error

### Expected behavior

the nest application should be bootstrapped successfully

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@apollo/subgraph

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "post-service",
  "version": "0.0.1",
  "description": "The post service",
  "author": "james@sapia.ai",
  "private": true,
  "license": "MIT",
  "scripts": {
    "start": "nest start --watch",
    "schema:emit": "ts-node src/graphql/schema.emitter.ts",
    "schema:publish": "npm run schema:emit && env-cmd -f .env.local rover subgraph publish {fill_the_graph_name_here} --name posts --schema ./schema.gql --routing-url http://localhost:6002/graphql"
  },
  "dependencies": {
    "@apollo/federation": "^0.38.1",
    "@apollo/subgraph": "^2.3.1",
    "@nestjs/apollo": "^10.1.7",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^10.1.7",
    "@nestjs/platform-express": "^9.0.0",
    "apollo-server-express": "^3.11.1",
    "graphql": "^16.6.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@apollo/rover": "^0.12.1",
    "@graphql-hive/cli": "^0.19.12",
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "env-cmd": "^10.1.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

16.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

use npm

**Comment by Tony133** [comment]
It is not related to NestJS but to the `@apollo/subgraph` package see here https://github.com/apollographql/federation/issues/2375 and you can find some solutions here: https://github.com/nestjs/graphql/issues/2646.

**Comment by Tony133** [comment]
It is not related to NestJS but to the `@apollo/subgraph` package see here https://github.com/apollographql/federation/issues/2375 and you can find some solutions here: https://github.com/nestjs/graphql/issues/2646.
