### ISSUE TITLE
Order of execution of middleware is out of order of module imports

### ISSUE THREAD

**Issue by igrek8** [nestjs/nest#11132]
### Is there an existing issue for this?

- [X] https://github.com/nestjs/docs.nestjs.com/pull/1333

### Current behavior

Hello community,

I have got some trouble with how nest.js runs middleware when there are multiple modules implementing them. Nest.js DI imports modules in the right order but attaches module middleware out of the order. 

## Setup

- App
  - Feature A
    - Feature B
      - **Feature C**
        - **Middleware C**
  - **Feature D**
    - **Middleware D**

## Expected

When application is initialised one receives the correct order of module imports and module configurations:

1. feature-a/constructor
2. feature-b/constructor
3. feature-c/constructor
4. feature-d/constructor
5. **feature-c/configure** 
6. **feature-d/configure**

Then one makes a request and expects the following resolution:

1. feature-c/middleware (since feature-c was configured first)
2. feature-d/middleware (since feature-d was configured after feature-c)

## Received

But for some reason one receives the following order of execution of middleware:

1. ⚠️ feature-d/middleware
2. ⚠️ **feature-c/middleware**

For some reason, middleware of `feature-d` is executed before middleware of `feature-c`. Thus, order of middleware is perhaps incorrect.

## Search for answers

I have read the issue https://github.com/nestjs/docs.nestjs.com/pull/1333. The author and community commented with the following:

> In the case of middleware bound across different modules, the middleware bound to the root module will run first, and then middleware will run **in the order that the modules are added to the imports array.**

### Minimum reproduction code

https://github.com/igrek8/nestjs-middleware-out-of-order

### Steps to reproduce

1. `yarn`
2. `yarn start`
3. see console output

### Expected behavior

It is expected that Nest respects order of execution of middleware in regards to module imports array such as if initialisation is performed with the following:

1. feature-a/constructor
2. feature-b/constructor
3. feature-c/constructor
4. feature-d/constructor
5. **feature-c/configure** 
6. **feature-d/configure**

Order of middleware execution should be performed with the following

1. **feature-c/middleware**
2. **feature-d/middleware**

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9

### Packages versions

```json
{
  "name": "middleware-order",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by igrek8** [comment]
The order change is caused by the following sorting

https://github.com/nestjs/nest/blob/master/packages/core/middleware/middleware-module.ts#L148-L155

**Comment by igrek8** [comment]
Does it make sense to avoid sorting based on distance so registration of middleware will be governed by the DI and not by the module distance?

**Comment by igrek8** [comment]
#11133

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11133

**Comment by janis91** [comment]
Hi @kamilmysliwiec I am a bit confused. The issue has been closed, the related PR has been closed - not merged. And the docs have not been adapted. So in my eyes, if I am not getting anything wrong, either documentation or the code must be wrong. In the docs it still states `In the case of middleware bound across different modules, the middleware bound to the root module will run first, and then middleware will run in the order that the modules are added to the imports array.`
And in the PR you are saying `This is the expected behavior given that module C is closer to the root module than module B`

So what is the expected behavior? If the PR was done with the correct intention however, I think this is a breaking change, since maybe someone based their setup on the resolution based on the distance. Although we are currently facing the problem, that it doesn't make sense to restructure the modules just because a middleware should be executed in a different order. Maybe it would also makes sense to consider a different way, like an @Order decorator or something like that?

Could you please elaborate or explain to me, what is the actual intended behavior such that we can decide how to change our implementation?

**Comment by dannybster** [comment]
> Let's track this here #11133

Looking at this issue and the closed PR, would you suggest the documentation needs to be corrected?

I'd also respectfully argue that sorting by distance is much more complicated and further removed from expected order than sorting by import order, i.e. middleware in Express is sorted in the order it is added.

A simple change or addition of a module as a dependency of another module can completely and unexpectedly change the order in which middleware runs.
