### ISSUE TITLE
Nestjs and pino logger not working correctly with GraphQL requests

### ISSUE THREAD

**Issue by mh377** [nestjs/nest#11149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am able to append a custom header: `x-request-id` to each log message for REST requests but not for GraphQL requests.

### Minimum reproduction code

https://github.com/mh377/nestjs-graphql-sample

### Steps to reproduce

Please see my github repo for instructions on how to reproduce the issue

### Expected behavior

I should be able to append a custom header `x-request-id` to each log message for both REST and GraphQL requests.

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

nestjs-pino

### NestJS version

9.3.5

### Packages versions

```json
{
  "name": "graphql-sample",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/apollo": "^10.2.0",
    "@nestjs/common": "^9.3.5",
    "@nestjs/config": "^2.3.1",
    "@nestjs/core": "^9.3.5",
    "@nestjs/graphql": "^10.2.0",
    "@nestjs/platform-express": "^9.3.3",
    "apollo-server-express": "^3.11.1",
    "graphql": "^16.6.0",
    "nestjs-pino": "^3.1.2",
    "pino-http": "^8.3.3",
    "pino-pretty": "^9.2.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4",
    "uuidv4": "^6.2.13"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v16.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Hi @mh377, for these kinds of issues related to using third-party packages like `nestjs-pino`, try using the support channel [discord](https://discord.com/invite/G7Qnnhy)
