### ISSUE TITLE
Nest generate does nothing in new project

### ISSUE THREAD

**Issue by soroushmadani** [nestjs/nest#11141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is the bug I reported. #11140

@nestjs/cli and @nestjs/schematics are updated to the latest version. it is still behaving the same way

```
yarn list v1.22.19
├─ @nestjs/cli@9.2.0
├─ @nestjs/common@9.3.9
├─ @nestjs/core@9.3.9
├─ @nestjs/platform-express@9.3.9
├─ @nestjs/schematics@9.0.4
├─ @nestjs/testing@9.3.9
```

would you solve my problem before closing the issue?

### Minimum reproduction code

https://github.com/soroushmadani/nest-bugreport

### Expected behavior

to work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
hi! you didn't tell us if you had upgraded the global installed one, which seems to be the cause of this. If we use the local `@nestjs/cli`, it works fine, I just tested it.

![image](https://user-images.githubusercontent.com/13461315/220091442-9fa2c918-d7ca-4d9e-bbe8-819a7589189e.png)

btw I don't recommend using `@nestjs/cli` globally otherwise you might face those issues if you didn't fully understand how nodejs module resolution works. Instead, use `npx @nestjs@cli new` to create a new project and `npx nest g ...` to use the `@nestjs/cli` that was installed for it.

**Comment by soroushmadani** [comment]
I guess I found the problem.
in yarn.lock i changed the @nestjs/cli part and it works now.

the new one that does not work:
```
"@nestjs/cli@^9.0.0":
  version "9.2.0"
  resolved "https://registry.yarnpkg.com/@nestjs/cli/-/cli-9.2.0.tgz#d174f54d7aaa6695b8e413093e3d18367bc8bec7"
  integrity sha512-6B1IjDcJbrOu55oMF67L1x5lDUOZ3Zs9l7bKCBH9D78965m8wq/2rlEWl/gJto5TABLQWy3hVvV/s8VzUlRMxw==
  dependencies:
    "@angular-devkit/core" "15.1.4"
    "@angular-devkit/schematics" "15.1.4"
    "@angular-devkit/schematics-cli" "15.1.4"
    "@nestjs/schematics" "^9.0.0"
    chalk "3.0.0"
    chokidar "3.5.3"
    cli-table3 "0.6.3"
    commander "4.1.1"
    fork-ts-checker-webpack-plugin "7.3.0"
    inquirer "7.3.3"
    node-emoji "1.11.0"
    ora "5.4.1"
    os-name "4.0.1"
    rimraf "4.1.2"
    shelljs "0.8.5"
    source-map-support "0.5.21"
    tree-kill "1.2.2"
    tsconfig-paths "4.1.2"
    tsconfig-paths-webpack-plugin "4.0.0"
    typescript "4.9.5"
    webpack "5.75.0"
    webpack-node-externals "3.0.0"
```

the older one that works:
```
"@nestjs/cli@^9.0.0":
  version "9.0.0"
  resolved "https://registry.yarnpkg.com/@nestjs/cli/-/cli-9.0.0.tgz#f9ab4c33cfbc9ee54d792fe29e0f582e0bf04b06"
  integrity sha512-xT5uOoIEcaB/Fn6UeF7atfKqKiEEsTeRKPiM55p+e5H9WVw8FC2r4ceZgaINJbsw0QWskVj/ZQadMo6dA6hXxw==
  dependencies:
    "@angular-devkit/core" "14.0.5"
    "@angular-devkit/schematics" "14.0.5"
    "@angular-devkit/schematics-cli" "14.0.5"
    "@nestjs/schematics" "^9.0.0"
    chalk "3.0.0"
    chokidar "3.5.3"
    cli-table3 "0.6.2"
    commander "4.1.1"
    fork-ts-checker-webpack-plugin "7.2.11"
    inquirer "7.3.3"
    node-emoji "1.11.0"
    ora "5.4.1"
    os-name "4.0.1"
    rimraf "3.0.2"
    shelljs "0.8.5"
    source-map-support "0.5.21"
    tree-kill "1.2.2"
    tsconfig-paths "3.14.1"
    tsconfig-paths-webpack-plugin "3.5.2"
    typescript "4.7.4"
    webpack "5.73.0"
    webpack-node-externals "3.0.0"
```
