### ISSUE TITLE
Support for Vite 

### ISSUE THREAD

**Issue by appinteractive** [nestjs/nest#11156]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

To speed up dev and startup times, vite could be used. There were already several issues opened on this topic, but due to the lack of decorator support in ESBuild and Vite they have gone nowhere. 

### Describe the solution you'd like

By researching I found this package that uses babel for the missing functionality. Maybe someone wants to check that out. https://www.npmjs.com/package/vite-plugin-babel

Speeding up the server would be nice, currently it does feel a bit like 2018 😅

@kamilmysliwiec what do you think?

### Teachability, documentation, adoption, migration strategy

Should be optional I guess?

### What is the motivation / use case for changing the behavior?

Speed, time is money, also tests on CI might benefit and cost less due to quicker tournaround times.

**Comment by micalevisk** [comment]
Hi!

Is this for nestjs CLI or what, exactly? 🤔

**Comment by appinteractive** [comment]
@Tony133 yeah the answer is already a year old and a lot in the ecosystem has changed. 

So your standpoint is still against vite, correct? 

Neither then less it would be a good alternative to the webpack dev Server you already documented.

**Comment by micalevisk** [comment]
I wonder if we could make the compiler more extensible so everyone could start writing their own integrations for nestjs cli. Not sure how feasible this is tho.

**Comment by Tony133** [comment]
@appinteractive, as you read, the answer was given by one of the core team members, I didn't write it, so I think it is still valid as an answer. Anyway I am not against new features, I have tried Vite with both Vue and NestJS , besides Vite there would be turbopack which is an interesting project but I haven't tried it yet, as you see there are others. If you want you can use Vite with NestJS in your projects, but keep in mind that there will be incompatibilities due for example also to the change with ES Module, many technologies need time to be as compatible as possible, sometimes it takes many years, one year is not enough.

However, the question is, does it make sense to overload the core team to add these new compilers? I can add maybe an alternative to webpack, yes, that wouldn't be bad, but then in the future, let's say more are coming, should they add them all? The question is not only about Vite, but also about adding a new adapter, etc., should they be added by the Core Team? The Core Team has laid out a path, then the other things can be supported by the community. 

This is my personal opinion, then everyone is free to think differently as they should, on the contrary, it is nice to talk about it and discuss it. 😉👍

**Comment by kamilmysliwiec** [comment]
> yeah the answer is already a year old and a lot in the ecosystem has changed.

Unfortunately, not much has changed for us ever since. `esbuild` still doesn't support TS decorator's metadata so it's unsuitable for Nest. 

On the bright side, if you want to speed up your build script (by 10-100x), you can achieve so with SWC.

1. Install SWC and a few others

```
$ npm i -D @swc/cli @swc/core concurrently nodemon
```

2. Create the .swcrc file in the root directory:

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "baseUrl": "./"
  },
  "minify": false
}
```

3. Add the following script to your package.json

```
"start:swc": "concurrently \"swc --out-dir dist -w src\" \"nodemon dist/main\"",
```

4. Run `npm run start:swc`

Example: for a medium-sized application, I was able to speed up my build by 100x (from 11 seconds to 0,1s).

**Comment by appinteractive** [comment]
Thank you for your answers 👍

Why I wanted to try vite was the broad support, ecosystem and speed. 

Will try swc with that config. Maybe something like that would be something for the documentation for "experiments"?

Thanks and I appreciate your work 🍀

**Comment by kamilmysliwiec** [comment]
Since the example with "concurrently" might be causing some nodemon loops during the first build (since nodemon is watching the entire directory), you can also just run 2 scripts in separate terminal windows:

```
npx swc --out-dir dist -w src
```

and:

```
nodemon dist/main
```

 :)

> Maybe something like that would be something for the documentation for "experiments"?

I'll add this to the docs shortly!

**Comment by appinteractive** [comment]
Dziękuję Kamil 👍

**Comment by dennemark** [comment]
Is it worth taking a look at this again? https://github.com/evanw/esbuild/releases/tag/v0.21.3 "Implement the decorator metadata proposal"

**Comment by dzcpy** [comment]
Please add Vite support. Webpack is the new IE for Node.js backend developers

**Comment by kamilmysliwiec** [comment]
https://github.com/TrilonIO/nest-vitest
