### ISSUE TITLE
@InjectNull() to inject a null value

### ISSUE THREAD

**Issue by ArcherGu** [nestjs/nest#11154]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm designing a library that integrates electron and nest.js: [@doubleshot/nest-electron](https://github.com/Doubleshotjs/doubleshot/tree/main/packages/nest-electron). I want it to be compatible with both electron and node environments, so some @Inject may not work in different environments, but I don't want nest.js throw errors.

For example, I have a `@Window()` decorator that inject window object provided by `ElectronModule` into `Controller` or `Service`.
```ts
/**
 * Window decorator, help to inject window
 */
export const Window = (name: string): ReturnType<typeof Inject> => Inject(name)
```
In the electron environment, I add `ElectronModule` to `imports`, but in node environment I just remove it:
```ts
const imports = isElectron? [ 
  ElectronModule.registerAsync({
    // init electron window
  })
] : []

@Module({
  imports,
  controllers: [AppController],
})
export class AppModule { }
```
so, I want a `@InjectNull()` to help me inject just a null value: 
```ts
export const Window = (name: string): ReturnType<typeof Inject | typeof InjectNull> => isElectron? Inject(name) : InjectNull()
```

### Describe the solution you'd like

I want a `@InjectNull()` to help me inject just a null value: 
```ts
export const Window = (name: string): ReturnType<typeof Inject | typeof InjectNull> => isElectron? Inject(name) : InjectNull()
```
Or add this feature to `@Inject()`, mybe: `@Inject(NULL_VALUE_TOKEN)`

### Teachability, documentation, adoption, migration strategy

see `Is your feature request related to a problem? Please describe it`

### What is the motivation / use case for changing the behavior?

see `Is your feature request related to a problem? Please describe it`

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
