### ISSUE TITLE
Include module aliasing with Nest CLI code generation

### ISSUE THREAD

**Issue by nolawnchairs** [nestjs/nest#11169]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not a problem or bug, just a small annoyance.

When using the Nest CLI to generate new modules, controllers, etc, it uses the standard style for adding the imports:

```ts
import { FooModule } from './foo-module/foo.module.ts';
```

However, I have module aliasing defined in my `tsconfig.json` file:

```json
"paths": {
  "@lib/*": ["./*"]
}
```

### Describe the solution you'd like

Ideally, the Nest CLI could introspect the `tsconfig.json` file and add its imports with the aliasing:

```ts
import { FooModule } from '@lib/modules/foo-module/foo.module.ts';
```

### Teachability, documentation, adoption, migration strategy

N/A. It would not affect DX in any real way, but could improve it for those who use aliasing.

### What is the motivation / use case for changing the behavior?

Just simply a time saver. If I generate new files, I delete the generated imports and re-import them using VSCode's auto import feature.

But most times, I just manually create the modules/services/controllers that I need.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
