### ISSUE TITLE
Disable http server for use only sockets

### ISSUE THREAD

**Issue by Dolzhansky** [nestjs/nest#11162]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a problem, my team use Microservices architecture and socket app it different process and she accept http requests, we search how disable http server but not found this

### Describe the solution you'd like

Disable http server for example app.disableHttp()

### Teachability, documentation, adoption, migration strategy

No

### What is the motivation / use case for changing the behavior?

Idk maybe this feature use lower memory without http

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
