### ISSUE TITLE
Types of property 'sockets' are incompatible when using Socket.io 

### ISSUE THREAD

**Issue by oceanwap** [nestjs/nest#11174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Use case: 

I am using a package which uses socket.io to listen for some events, and I am using this package inside nest app.

Problem:
I am getting error "Types of property 'sockets' are incompatible" for some time now.  @nestjs/platform-socket.io locks the socket.io version, while the package which I am using  doesn't lock it to a specific version and it allows patch version upgrades. Because of this typescript throws type mismatch error, for socket.io objects.

@nestjs/platform-socket.io uses socket.io version 4.6.0, while my package uses ^4.6.0 but I don't want to lock it because even if I lock it, and then if @nestjs/platform-socket.io upgrades to 4.6.1 or 4.6.2 in future I always need to change my package and release it again so nest application works, and it's quite uncomfortable since we can't get bug fixes or patches from socket.io without a nested upgrade of all underlying packages.

### Minimum reproduction code

I don't think it's needed

### Expected behavior

It shouldn't lock the version of socket.io or any package to patch level.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [X] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
