### ISSUE TITLE
`useFactory` and `useValue` behave different.

### ISSUE THREAD

**Issue by zanminkian** [nestjs/nest#11176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Running code below (eg: `ts-node main.ts`), it will print `AModule value` twice. But what I expect is print `AModule value` and `BModule value`.
If I replace `useFactory: () => value` with `useValue: value`, it will print `AModule value` and `BModule value` as expected.
```ts
import 'reflect-metadata'
import { NestFactory } from '@nestjs/core';
import { Inject, Module } from '@nestjs/common';

@Module({})
export class BaseModule {
  static forFeature(value: string, name: string = 'default') {
    const providers = [{
      provide: name,
      // If I replace `useFactory: () => value` with `useValue: value`, this bug will disappear
      // useValue: value
      useFactory: () => value
    }]
    return {
      module: BaseModule,
      providers,
      exports: providers
    }
  }
}

export class AService {
  constructor(@Inject('default') private readonly value: string){
    console.log(value)
  }
  print() {
    console.log(this.value)
  }
}

@Module({
  imports: [BaseModule.forFeature('AModule value')],
  providers: [AService],
  exports: [AService]
})
export class AModule {}

export class BService {
  constructor(@Inject('default') private readonly value: string){
    console.log(value)
  }
  print() {
    console.log(this.value)
  }
}

@Module({
  imports: [BaseModule.forFeature('BModule value')],
  providers: [BService],
  exports: [BService]
})
export class BModule {}


@Module({
  imports: [AModule, BModule]
})
export class AppModule{
}

(async ()=>{
  const app = await NestFactory.create(AppModule)
  app.listen(9090)
})()

```

### Minimum reproduction code

https://github.com/zanminkian/nestjs-use-factory-bug

### Steps to reproduce

See the repository README.

### Expected behavior

See the repository README.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.9

### Packages versions

```json


{
  "dependencies": {
    "@nestjs/common": "^9.3.9",
    "@nestjs/core": "^9.3.9",
    "@nestjs/platform-express": "^9.3.9"
  },
  "devDependencies": {
    "@types/node": "^18.14.2"
  }
}
```

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
You can declare an additional UUID provider that generates a random unique ID per module to ensure they produce different hashes.

If you search through some of our old issues on this (this has been discussed several times in the past), you'll see a bit more information on why this is even needed

**Comment by KostyaTretyak** [comment]
> You can declare an additional UUID provider that generates a random unique ID per module to ensure they produce different hashes.

@kamilmysliwiec, what do you mean? I can't find anything related to this (I searched for information on the terms `UUID provider`).

**Comment by kamilmysliwiec** [comment]
> Wow! That is, NestJS creates instances of providers even when they are not injected? Is it logical? Where in the documentation can we read this?

It is perfectly reasonable given that certain providers act as entry providers (job processors, queue providers, crons, GQL resolvers, and tons of others) 

> @kamilmysliwiec, what do you mean? I can't find anything related to this (I searched for information on the terms UUID provider).

```
{ 
  provide: 'MODULE_ID',
  useValue: randomUUID(),
}
```

Search through old issues to get more context & information.
