### ISSUE TITLE
axios request Timeout , Cause program crash

### ISSUE THREAD

**Issue by luojiong** [nestjs/nest#11178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I used the @ nestjs/axios and axios libraries to write an example according to the official document, but when I sent a request with an exception or an exception, my program crashed directly. I don't understand why request is a separate method that causes the program to crash

 

### Minimum reproduction code

https://codesandbox.io/p/sandbox/amazing-stonebraker-d55ly7?file=%2Fsrc%2Fapp.service.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A12%7D%5D

### Steps to reproduce

 1、 npm i --save @nestjs/axios axios
 2、 import httpModule 
3、 controller use httpService 
4、 this.httpService.axiosRef.get('https://google.com');

### Expected behavior

I hope that when my request is unexpected, it will not cause my entire program to crash, but let me handle this exception

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

axios @nests/axios

### NestJS version

9.0.0

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v18.14.1
YARN Version    : 1.22.19

[Nest CLI]
Nest CLI Version : 9.1.3

[Nest Platform Information]
platform-express version : 9.1.2
microservices version    : 9.2.0
mapped-types version     : 1.1.0
schematics version       : 9.0.3
mongoose version         : 9.2.0
passport version         : 9.0.0
swagger version          : 6.1.2
typeorm version          : 9.0.1
testing version          : 9.1.2
common version           : 9.1.2
config version           : 2.2.0
axios version            : 2.0.0
core version             : 9.1.2
jwt version              : 9.0.0
cli version              : 9.1.3

### Node.js version

18.14.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

D:\project\robot-devops\node_modules\axios\lib\core\AxiosError.js:89
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
Error: connect ECONNREFUSED ::1:80
    at Function.AxiosError.from (D:\project\robot-devops\node_modules\axios\lib\core\AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (D:\project\robot-devops\node_modules\axios\lib\adapters\http.js:577:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (D:\project\robot-devops\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by micalevisk** [comment]
that's expected. As you've missed the `await` in that promise, no one is listen to the rejection that it could araise.

**Comment by luojiong** [comment]
@micalevisk  thanks  I get
