### ISSUE TITLE
MQTT microservices will not start

### ISSUE THREAD

**Issue by SolunaSoftware** [nestjs/nest#11175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When await app.startAllMicroservices() is called this error happens: 

ERROR [Server] Error: connect ECONNREFUSED 127.0.0.1:1883

![NbvMvqE](https://user-images.githubusercontent.com/27294701/222152259-68d67d60-f157-4585-b143-2b5d459abb9c.png)

### Minimum reproduction code

https://github.com/SolunaSoftware/nestjs-mqtt-test.git

### Steps to reproduce

1. npm i
2. npm run start:dev

### Expected behavior

That the server and connected microservice starts with no errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

mqtt, reflect-metadata and rxjs

### NestJS version

9.0.0

### Packages versions

```[System Information]
OS Version     : Windows 10
NodeJS Version : v16.17.0
NPM Version    : 8.19.2 

[Nest CLI]
Nest CLI Version : 9.2.0

[Nest Platform Information]
platform-express version : 9.3.9
microservices version    : 9.3.9
schematics version       : 9.0.4
testing version          : 9.3.9
common version           : 9.3.9
core version             : 9.3.9
cli version              : 9.2.0
```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I have also tried to reach out for help/input on discord: https://discord.com/channels/520622812742811698/1080453342897127474

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
