### ISSUE TITLE
Support to log Set and Map

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest#11189]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When I use the nest built-in logger to log an object, the Set and Map properties are empty in the console. 

### Describe the solution you'd like

print out the type and the values
```
{
  mySet: [Set] [val1, val2]
  myMap: [Map] {
    key1: val1,
    key2: val2
  }
}
```

### Teachability, documentation, adoption, migration strategy

use the built-in logger as usual 

### What is the motivation / use case for changing the behavior?

to avoid creating a custom logger

**Comment by r37r0m0d3l** [comment]
Can you please provide acceptance criteria for this feature? I'm an author of https://consono.js.org/ and am currently in the same boat as you. I want to implement something in between a lightweight logger and full support of the new types of variables.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11258
