### ISSUE TITLE
CQRS Testing In Documentation

### ISSUE THREAD

**Issue by josephaw1022** [nestjs/nest#11185]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I noticed that there is a past pr that asked for help on a testing strategy with the cqrs package https://github.com/nestjs/nest/issues/274. While the responses in the thread does help solve a lot of the problems for getting momentum while working the cqrs and wanting to do basic unit tests, I think just responding to the question and closing out the pr did miss the documentation part of the pr.

### Describe the solution you'd like

There are two solutions that I think would be super helpful. This can be iterated on, so the second point isn't required, but does build on the first point. 

1) Testing Strategy in the cqrs page. This section would basically just have a brief explanation/example  of testing 
  - a controller/service that calls the command/event bus
  - a command handler 
  - a event handler
  - a query handler

2) The examples of the tests implemented in the example cqrs repo

### Teachability, documentation, adoption, migration strategy

Doesn't really apply since this is a documentation request

### What is the motivation / use case for changing the behavior?

It's clear that the cqrs package has a lot to offer and I really enjoy using it, but I think the package's documentation needs to be iterated on and needs to have documentation that goes in a bit more depth.

**Comment by Tony133** [comment]
There are already open issues for this in the documentation repository see here: https://github.com/nestjs/docs.nestjs.com/issues/1240, https://github.com/nestjs/docs.nestjs.com/issues/1239 

However, if you might be interested there is an example here: https://github.com/jmcdo29/testing-nestjs/tree/main/apps/cqrs-sample
