### ISSUE TITLE
can't access service in exception filter

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest#11190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when throw error from AuthenticationMiddleware, the app crashed
```
/src/app.filter.ts:29
            ReqAuxData: this.reqService.getAuxData()
                                        ^

TypeError: Cannot read properties of undefined (reading 'getAuxData')
    at AppFilter1.catch (/src/app.filter.ts:29:41)
    at ExceptionsHandler.invokeCustomFilters (/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/exceptions/exceptions-handler.js:33:26)
    at ExceptionsHandler.next (/home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/exceptions/exceptions-handler.js:13:18)
    at /home/ian/templates/vite-nest/node_modules/.pnpm/@nestjs+core@9.3.9_jrq2rdgfp2sx67wmylmrqliwxe/node_modules/@nestjs/core/router/router-proxy.js:13:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Minimum reproduction code

https://github.com/ianzone/vite-nest-fastify/tree/filter-error

### Steps to reproduce

1. pnpm i
2. pnpm run dev
3. GET http://localhost:3000/error

### Expected behavior

app doesn't crash, request info is logged in the exception filter.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : Linux 5.15
NodeJS Version : v18.12.0
PNPM Version    : 7.28.0

[Nest CLI]
Nest CLI Version : 9.2.0

[Nest Platform Information]
platform-fastify version : 9.3.9
swagger version          : 6.2.1
testing version          : 9.3.9
common version           : 9.3.9
config version           : 2.3.1
core version             : 9.3.9

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

probably still https://github.com/nestjs/nest/issues/10781

**Comment by Maligosus** [comment]
Inject `ModuleRef` and try resolve provider
```ts
import { ArgumentsHost, Catch, HttpException, Injectable, Logger } from '@nestjs/common';
import { BaseExceptionFilter,ContextId,ModuleRef } from '@nestjs/core';
import { FastifyReply, FastifyRequest } from 'fastify';
import { RequestService } from './services';

// https://docs.nestjs.com/exception-filters#exception-filters
@Injectable()
@Catch()
export class AppFilter extends BaseExceptionFilter {
  private readonly logger = new Logger(AppFilter.name);
  constructor(
   private readonly moduleRef: ModuleRef
  ) {
    super();
  }
 async catch(exception: Error, host: ArgumentsHost) {
    const req = host.switchToHttp().getRequest<FastifyRequest>();
    const res = host.switchToHttp().getResponse<FastifyReply>();
   const contextId = ContextIdFactory.getByRequest(req);
   const module = await moduleRef.resolve(RequestService ,contextid);
    const ctx = {
      Method: req.method,
      Path: req.url,
      Params: req.params,
      Query: req.query,
      Headers: req.headers,
      Body: req.body,
      ReqAuxData: this.reqService.getAuxData(),
    };

    let statusCode = 500;
    let message = '';
    if (exception instanceof HttpException) {
      this.logger.warn(ctx, exception.stack);
      statusCode = exception.getStatus();
      message = exception.message;
    } else {
      // unexpected errors that need to trigger alerts
      this.logger.error(ctx, exception.stack);
      message = exception.message;
    }

    res.status(statusCode).send({ ...this.reqService.getLogTrace(), message });
  }
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
