### ISSUE TITLE
`@Query()` params with square brackets are `undefined`

### ISSUE THREAD

**Issue by c-kirkeby** [nestjs/nest#11240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

A query parameter that looks like the following will get turned into `undefined`:

```ts
findAll(@Query('filter[ownerId]') ownerId?: string) {
  console.debug(ownerId);
  return this.catService(ownerId)
}
```

When used like this (example using [httpie](https://httpie.io/cli)):
```sh
$ http get :3000/cats filter\[breedId\]=123
```

The console statement will print:

```sh
undefined
```

However if we remove the square brackets like this:

```ts
findAll(@Query('ownerId') ownerId?: string) {
  console.debug(ownerId);
  return this.catService(ownerId)
}
```

Then it gets printed as:

```sh
f16c54b1-6f3a-4a0d-8478-03f205efcc15
```

### Minimum reproduction code

https://github.com/c-kirkeby/nest-square-brackets-reproduction

### Steps to reproduce

1. `git clone git@github.com:c-kirkeby/nest-square-brackets-reproduction.git`
2. `pnpm run start:dev`
3. `http get :3000/cats filter\[breedId\]=123` (using httpie with zsh)`, alternatively I wrote an e2e test: `pnpm run test:e2e`.

### Expected behavior

The URL param should come through as the value that is passed. Ideally there'd be a way for them to be bundled up into a `filter` object but I couldn't find a way to define this in the Nest docs.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^9.0.0",
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
  },
```

### Node.js version

v18.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
