### ISSUE TITLE
Report more information when `npm run start:prod` return **module_not_found** error.

### ISSUE THREAD

**Issue by toknT** [nestjs/nest#11241]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The app `npm run start`,`npm run start:dev`,`npm run build`  runed successly, but if run `npm run start:prod` after build **it always return module_not_found error without any other more information**.So I want more information to solveit.

### Describe the solution you'd like

No ideal.

### Teachability, documentation, adoption, migration strategy

More happy developer life.

### What is the motivation / use case for changing the behavior?

More happy developer life.

**Comment by micalevisk** [comment]
That's because of how nodejs works. And we usually don't want to perform any task before starting the app using that npm-script. Also, the CLI might not be available when running `start:prod` (which is fine).

I don't think we should change this. You can play with it in your side just fine 😺
