### ISSUE TITLE
CASL documentation using deprecated CASL code

### ISSUE THREAD

**Issue by muametgrooby** [nestjs/nest#11242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Nestjs documentation uses deprecated functions from CASL, copy-pasting it brings up deprecation errors
https://docs.nestjs.com/security/authorization#advanced-implementing-a-policiesguard

### Minimum reproduction code

https://docs.nestjs.com/security/authorization#advanced-implementing-a-policiesguard

### Steps to reproduce

Look at the documentation for implementing CASL

### Expected behavior

there should be no deprecation warnings when I follow the guide in documentation

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@casl/ability

### NestJS version

NA

### Packages versions

```json
{
    "@casl/ability": "^6.3.3"
}
```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
this should be fixed by PR https://github.com/nestjs/docs.nestjs.com/pull/2597

thanks for reporting!
