### ISSUE TITLE
Distributed Tracing feature  

### ISSUE THREAD

**Issue by rizesky** [nestjs/nest#11255]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

- I have issue tracing a request that span multiple services, as each service has its own id of 1 request.
Currently, I have to manually add interceptor on each service and add request id in header and append it in log, which is kind of hard to manage, and tiring, especially if service support multiple communication protocol.
- I want to have 1 id that have the same value on all participating service.  

### Describe the solution you'd like

- Distributed Tracing Feature.  A feature that can trace a request that span over multiple service, with any kind of protocol (http, gprc, tcp). In **Java** world, there is [Spring Boot Sleuth](https://github.com/spring-cloud/spring-cloud-sleuth/tree/3.1.x). 

### Teachability, documentation, adoption, migration strategy

- I don't really know what the best approach to this is. 

### What is the motivation / use case for changing the behavior?

- Easiness in tracing a request that span multiple services.

**Comment by rizesky** [comment]
https://github.com/MetinSeylan/Nestjs-OpenTelemetry 
I actually found this library, but I'm not sure if it is reliable or not.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
