### ISSUE TITLE
Create grpc server without import ".proto" file

### ISSUE THREAD

**Issue by minh1611** [nestjs/nest#11254]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to create a grpc server by nestjs, and I have a proto file name "tenant_service.proto" I use buf.build with plugin stephenh-ts-proto to generate ts file from the ".proto"  file. Now I want create grpc server with source from ".ts" file which I already created before instead of ".proto" file like this example: https://docs.nestjs.com/microservices/grpc. Does someone have any solution. 

### Describe the solution you'd like

The solution I want is create grpc server by ".ts" file generated by ".proto" file, instead of import directly ".proto" file.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
