### ISSUE TITLE
support to set default exclude and include routes on MiddlewareConsumer

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest#11259]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

for routes that are always included or excluded, I have to repetitively append them when applying each middleware
```
configure(consumer: MiddlewareConsumer) {
  const swagger = ['/api', '/api/(.*)', '/api-json']
  consumer.apply(Middleware1).exclude(...swagger).forRoutes('(.*)');
  consumer.apply(Middleware2).exclude(...swagger).forRoutes('(.*)');
  consumer.apply(Middleware3).exclude(...swagger).forRoutes('(.*)');
  ...
}
```

### Describe the solution you'd like

should be able to set included and excluded routes at once
```
configure(consumer: MiddlewareConsumer) {
  consumer.exclude('/api', '/api/(.*)', '/api-json')
  consumer.forRoutes('(.*)')
  consumer.apply(Middleware1)
  consumer.apply(Middleware2)
  consumer.apply(Middleware3)
  consumer.apply(SwaggerMiddleware).forRoutes('/api', '/api/(.*)', '/api-json')  // this should trump the default settings
  ...
}
```

### Teachability, documentation, adoption, migration strategy

as the description above

### What is the motivation / use case for changing the behavior?

to reduce repetitive code

**Comment by kamilmysliwiec** [comment]
`apply()` takes a rest argument as an input parameter so you can pass in multiple middleware functions/classes [apply](https://github.com/nestjs/nest/blob/a61bcd30991d78aa9b0cbe440f1d98c362afd5ad/packages/common/interfaces/middleware/middleware-consumer.interface.ts#L18)

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
