### ISSUE TITLE
upgrade from v7 to LTS

### ISSUE THREAD

**Issue by sambhav2612** [nestjs/nest#11256]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

7.6.13 => LTS

### Describe the regression

Hi,

We need to upgrade our NestJS backend from v7.6.13 (core) to LTS. We failed to incrementally upgrade it when v8 was released and its causing performance issues now.

These are the external dependencies we have:
- GraphQL
- Bull Queue
- Socket IO

Please suggest the best way to upgrade to v9.

### Input code

```ts

```

### Expected behavior

Backend upgraded to LTS

### Other

Node: v14.20.1
OS: macOS 13.2.1

**Comment by sambhav2612** [comment]
@kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
