### ISSUE TITLE
Support for specifying the `provide` value of CacheManager

### ISSUE THREAD

**Issue by shincurry** [nestjs/nest#11262]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In my actual usage, I need two `Cache`:
* One is a regular Redis based data cache to store some simple data.
* The other is a file cache, which is used to cache binary data uploaded by users.

The two `Cache` use different `cache-manager-store` independently, not simultaneously via `multiCaching`.

But the current implementation that `createCacheManager` hardcodes the value of provide (`CACHE_MANAGER`) so that when I import multiple `CacheModule` in `AppModule`, I can only access the last one through `@Inject(CACHE_MANAGER) cache!: Cache;`, even though multiple `Cache` are actually instantiated.

### Describe the solution you'd like

Add an extra optional option named `key` to `CacheModule.register` as a way to distinguish between different cache modules and use this name value to inject cache instance.

```ts
export function createCacheManager(key?: string): Provider {
  return {
    provide: key || CACHE_MANAGER,
    // ...
```

### Teachability, documentation, adoption, migration strategy

app.module.ts
```ts
export const CACHE_MANAGER_FILE_KEY = "CACHE_MANAGER_FILE"
export const CACHE_MANAGER_REDIS_KEY = "CACHE_MANAGER_REDIS"

@Module({
  imports: [
    CacheModule.register({
      isGlobal: true,
      key: CACHE_MANAGER_FILE_KEY,
      store: fileStore,
    }),
    CacheModule.register({
      isGlobal: true,
      key: CACHE_MANAGER_REDIS_KEY,
      store: redisStore,
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

app.service.ts
```ts
import { CACHE_MANAGER_FILE_KEY, CACHE_MANAGER_REDIS_KEY } from './App.module';

@Injectable()
export class AppService {

  @Inject(CACHE_MANAGER_FILE_KEY) fileCache!: Cache;
  @Inject(CACHE_MANAGER_REDIS_KEY) redisCache!: Cache;

}

```

### What is the motivation / use case for changing the behavior?

Mentioned before.

By the way, I think other packages may also have this feature need, such as `ConfigModule` (project has multiple configuration files, but doesn't want to merge them together to use).

**Comment by kamilmysliwiec** [comment]
You can declare two additional modules: DataCacheModule and FileCacheModule and re-export `Cache` under a different token (so there are no conflicts).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
