### ISSUE TITLE
Regsiter fastify plugin doesn't work

### ISSUE THREAD

**Issue by deleau-victor** [nestjs/nest#11265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi i am trying to register the fastify plugins but there are errors and i don't know why because in my previous code i was doing the same thinks and was working.

```ts
import { NestFactory } from '@nestjs/core'
import { AppModule } from './app.module'
import fastifyCookie, { FastifyCookie } from '@fastify/cookie'
import fastifyCors from '@fastify/cors'
import fastifyCsrfProtection from '@fastify/csrf-protection'
import fastifyHelmet from '@fastify/helmet'
import { ConfigService } from '@nestjs/config'
import {
	FastifyAdapter,
	NestFastifyApplication,
} from '@nestjs/platform-fastify'
import * as fs from 'fs'
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger'
import { ValidationPipe } from '@nestjs/common'
const httpsOptions = {
	key: fs.readFileSync('./secrets/cert.key'),
	cert: fs.readFileSync('./secrets/cert.crt'),
}

async function bootstrap() {
	const app = await NestFactory.create<NestFastifyApplication>(
		AppModule,
		new FastifyAdapter({ https: httpsOptions })
	)
	const configService = app.get(ConfigService)
	app.register(fastifyCookie, {
		secret: configService.get<string>('COOKIE_SECRET'),
	})
	app.register(fastifyHelmet)
	app.register(fastifyCsrfProtection, { cookieOpts: { signed: true } })
	app.register(fastifyCors, {
		credentials: true,
		origin: `https://${configService.get<string>('domain')}`,
	})
	app.useGlobalPipes(new ValidationPipe())
	await app.listen(3000)
	console.log(`Application is running on: ${await app.getUrl()}`)
}
bootstrap()
```

Like on this code, all registered plugins return error like :

'Argument of type 'FastifyCookie' is not assignable to parameter of type 'FastifyPluginCallback<FastifyCookieOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>'

### Minimum reproduction code

https://github.com/deleau-victor/docchus-back

### Steps to reproduce

Try to register any fastify plugin

### Expected behavior

Nest JS must correctly register the fastify plugins

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"@fastify/cookie": "^8.3.0",
		"@fastify/cors": "^8.2.0",
		"@fastify/csrf-protection": "^6.1.0",
		"@fastify/helmet": "^10.1.0",
		"@fastify/static": "^6.6.1",
		"@nestjs/common": "^9.2.1",
		"@nestjs/config": "^2.2.0",
		"@nestjs/core": "^9.2.1",
		"@nestjs/mapped-types": "*",
		"@nestjs/platform-fastify": "^9.2.1",
		"@nestjs/swagger": "^6.1.4",
		"@nestjs/throttler": "^4.0.0",
		"bcrypt": "^5.1.0",
		"cache-manager": "^5.1.4",
		"cache-manager-ioredis-yet": "^1.1.0",
		"class-transformer": "^0.5.1",
		"class-validator": "^0.14.0",
		"dayjs": "^1.11.7",
		"fastify": "^4.12.0",
		"handlebars": "^4.7.7",
		"ioredis": "^5.2.5",
		"joi": "^17.7.0",
		"jsonwebtoken": "^9.0.0",
		"moment": "^2.29.4",
		"neo4j-driver": "^5.6.0",
		"nest-neo4j": "^0.2.0",
		"nodemailer": "^6.9.0",
		"reflect-metadata": "^0.1.13",
		"rxjs": "^7.8.0",
		"slugify": "^1.6.5",
		"uuid": "^9.0.0"
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Hi!

Looks like your repository is private.

**Comment by quinguyenzx** [comment]
Won't happen if you install `fastify@4.13.0`.
I tested on my local machine, and this issue will happen on fastify versions:
- `4.12.0`
- `4.14.0`
- `4.14.1` (latest)

The issue seems like mismatch interface:
`Argument of type 'FastifyHelmet' is not assignable to parameter of type 'FastifyPluginCallback<FastifyHelmetOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>'.`
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/119300941/224602646-d75689cf-4091-417e-a4b7-24fb460d73fe.png">

**Comment by AsyncLegs** [comment]
"In my case, reverting the TypeScript version to 4.9 resolved the issue."

**Comment by joelywz** [comment]
Ensure that the Fastify version in the project matches the one specified in [@nestjs/platform-fastify](https://github.com/nestjs/nest/blob/master/packages/platform-fastify/package.json)

**Comment by matheusdearaujo** [comment]
I have this problem in recent versions.

**Comment by Alexhaec1310** [comment]
> I have this problem in recent versions.

Have you found any solution?

**Comment by Der-Alex** [comment]
I am facing the same type incompatibility issue with the latest versions and pnpm: 
```
@nestjs/core@10.3.3
@nestjs/platform-fastify@10.3.3 >> package.json says: fastify@4.26.1
fastify@4.26.1
@fastify/cookie@9.3.1
```
![grafik](https://github.com/nestjs/nest/assets/14862425/ffe6c1c4-9a35-4257-9b34-dbded91b9981)

Any advice?

**Comment by Alexhaec1310** [comment]
> UPDATE:
> 
> I found out that the app.register function from the NestFastifyApplication is based on fastify@4.26.0 whereas @nestjs/platform-fastify seems to want to have fastify@4.26.1. They are not compatible. When I install fastify@4.26.0 I can register my plugins.
> 
> @deleau-victor Maybe someone from your nestjs team can check this up?
> 
> I am facing the same type incompatibility issue with the latest versions and pnpm:
> 
> ```
> @nestjs/core@10.3.3
> @nestjs/platform-fastify@10.3.3 >> package.json says: fastify@4.26.1
> fastify@4.26.1
> @fastify/cookie@9.3.1
> ```
> 
> ![grafik](https://private-user-images.githubusercontent.com/14862425/305360283-ffe6c1c4-9a35-4257-9b34-dbded91b9981.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNzgyOTksIm5iZiI6MTcwODA3Nzk5OSwicGF0aCI6Ii8xNDg2MjQyNS8zMDUzNjAyODMtZmZlNmMxYzQtOWEzNS00MjU3LTliMzQtZGJkZWQ5MWI5OTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDEwMDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOGY2MDUxNzBiN2NlZjdiNTYzNTkyMmMxNDk2MDIwMmE3ZTVmMTBjZWRkNTJjNmEwMTkwNjVjYzc3OTY3MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXhOmEB4dOd2GnA_0x6htHaR1A6VDKa38pLcW170EJQ)
> 
> Any advice?

For now this is the solution I have found, I have the same versions as you do.

Main.ts
```
await app.register(require('@fastify/cookie'))
await app.register(require('@fastify/csrf-protection'), {
	cookieKey: 'XSRF-TOKEN',
	cookieOpts: { signed: true },
})

await app.register(require('@fastify/helmet'))
```

and I had to disable this to stop slint from displaying that error, at the start of Main.ts

/* eslint-disable @typescript-eslint/no-var-requires */

**Comment by jmcdo29** [comment]
This is generally a typescript error due to the fact that `fastify` is most likely directly installed **and** installed via `@nestjs/platform-fastify`. If you install the same version that `@nestjs/platform-fastify` does, the error will go away

**Comment by richardanewman** [comment]
> This is generally a typescript error due to the fact that `fastify` is most likely directly installed **and** installed via `@nestjs/platform-fastify`. If you install the same version that `@nestjs/platform-fastify` does, the error will go away

This worked for me. Changed package.json to `"fastify": "4.26.0",` to match the same version in `@nestjs/platform-fastify` and ran `npm i -force` and the error went away. Thanks! @jmcdo29

**Comment by alvinlys** [comment]
anyone tried the latest but failed too?  
<img width="303" alt="image" src="https://github.com/nestjs/nest/assets/32334860/d8e5e6ba-2e5a-4ab5-b508-f5b736203211">

**Comment by viniciuskloppel** [comment]
Just adding `"fastify": "4.26.1"` to the `devDependencies` not necessarily will fix the problem. It actually depends on the version of `fastify` that your version of `@nestjs/platform-fastify` is using. Here's what I recommend:
- Locate the package.json of the `@nestjs/platform-fastify` in the node_modules folder, i.e., `node_modules/@nestjs/platform-fastify/package.json`
- Look what's the version of `fastify` being used in that file. Let's say it's `"fastify": "4.17.0"`
- Go back to the package.json of your project (where the issue is happening)
- Add the version of fastify you found above (e.g. `"fastify": "4.17.0"`) to the devDependencies

**Comment by XIYO** [comment]
I used a translator.

The solution I found was to ignore the type checking or make the versions match.

sol. 1
```javascript
// @ts-ignore
await app.register(fastifyCookie);
```

sol. 2
**match version**
![image](https://github.com/user-attachments/assets/49b2bd7a-74b3-4161-b0fd-a9bc84662dc5)

problem. 1
**unmatch version**
![image](https://github.com/user-attachments/assets/e37b8269-53a0-4188-adf9-542c0b5e8c86)

---

However, I have a question.

Types like FastifyReply and FastifyRequest obviously exist in the Fastify package, so it makes sense to add these dependencies additionally. Due to this, compatibility issues with versions can arise, forcing me to tediously update Fastify with every release.

While I gained type safety, I encountered compatibility issues. 😂

Is there a better way to alleviate this fatigue?

**Comment by puzzle9** [comment]
Is there any elegant way now

**Comment by suyash-purwar** [comment]
> Ensure that the Fastify version in the project matches the one specified in [@nestjs/platform-fastify](https://github.com/nestjs/nest/blob/master/packages/platform-fastify/package.json)

Thanks @joelywz. This fixed the issue for me. Adding this comment for visibility.

**Comment by bantamroasted** [comment]
> This is generally a typescript error due to the fact that `fastify` is most likely directly installed **and** installed via `@nestjs/platform-fastify`. If you install the same version that `@nestjs/platform-fastify` does, the error will go away





https://typescripts.space/questions/guide-to-crafting-a-reply-using-nestjs-exception-filters-with-nestfastify
