### ISSUE TITLE
Is there a way to do a constructor injection of a Response object?

### ISSUE THREAD

**Issue by ytetsuro** [nestjs/nest#11278]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This is not a problem.
However, I would like to keep the display process separate from the display process.
I don't want to fatten up the Controller with additional display responsibilities.

So, we want to prepare a Presenter class and DI the Response object to the Presenter class.

```typescript
@injectable({ scope: Scope.REQUEST })
class Presenter {
  constructor(@Response private readonly response: Response) {}

  output(glue: GlueObject) {
     this.response.send({foo: glue.bar});
  }
}
```

This can be accomplished by adding the following settings to Modules.

```typescript
@Module({
  imports: [],
  controllers: [FooController],
  providers: [
    Presenter,
    {
      provide: 'RESPONSE',
      useFactory: (request: Request) => request.res,
      inject: [REQUEST],
    },
  ],
})
```

However, this method does not use the Response decorator in the Controller, so multiple status sets will result in an error.

```
Error: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n
```

This error disappears when the Response decorator is used in the method receiving the request.

### Describe the solution you'd like

Is it possible to not automatically set the status in Nest.js without using the Response decorator?

### Teachability, documentation, adoption, migration strategy

Example.

```typescript
@Controller('/', {responsePassthrough: false})
class FooController {}
```

### What is the motivation / use case for changing the behavior?

I don't want to handle the display process in the Controller.
By handling this, it becomes easier to reuse the display process.
It also makes it possible to test the display logic only with the display logic.

https://blog.georgovassilis.com/2019/04/14/the-model-view-presenter-controller-pattern/

**Comment by Maligosus** [comment]
Hello. I tried to implement something similar, created a PR. I hope they approve.

**Comment by kamilmysliwiec** [comment]
You should be able to accomplish what you need by implementing a custom HTTP adapter that inherits from the one you currently use (ExpressAdapter/FastifyAdapter). Add an additional if condition in the "send"/or any other method you need, checking if it wasn't already processed in the controller.

Otherwise, there are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
