### ISSUE TITLE
ExternalContextCreator getContextModuleKey is searching only in providers

### ISSUE THREAD

**Issue by bintoll** [nestjs/nest#11272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Not sure if it is bug or expected behavior, please correct me if I am wrong.
I am using the @golevelup/nestjs-rabbitmq which uses ExternalContextCreator under the hood to create rmq context. I am trying to use same controller for both rest and rabbitmq. Generally it works fine, but when I tried to add exception filter, exceptions from rabbitmq handlers are not filtered. After some investigation I find out that createConcreteContext for filters returns empty array of filter functions (https://github.com/nestjs/nest/blob/e63f5c0ff58c08ab8cdfed8fd81cf5abfbc427e2/packages/core/exceptions/base-exception-filter-context.ts#L18), it returns empty array because getInstanceByMetatype returns undefined (https://github.com/nestjs/nest/blob/e63f5c0ff58c08ab8cdfed8fd81cf5abfbc427e2/packages/core/exceptions/base-exception-filter-context.ts#L59), because moduleContext is empty string. moduleContext is set here (https://github.com/nestjs/nest/blob/e63f5c0ff58c08ab8cdfed8fd81cf5abfbc427e2/packages/core/helpers/external-context-creator.ts#L109). Finally I found out that problem is on this line (https://github.com/nestjs/nest/blob/e63f5c0ff58c08ab8cdfed8fd81cf5abfbc427e2/packages/core/helpers/external-context-creator.ts#L248) it is trying to find moduleCtor only in providers of moduleRef. I can not understand why it is designed to look only inside providers, because it is common to have context in controllers and there is a possibility to extends contexts (ws, rpc). I know that ws and rpc are registered in another way using createMicroservice, but anyway, is there a reason why ExternalContextCreator tries to find moduleCtor only in providers? 
After changing that if clause to ```moduleRef.hasProvider(moduleCtor) || moduleRef.controllers.has(moduleCtor)``` everything starts working as expected - in controller if rabbitmq or rest api handler throws exception it is filtered by exception filter in both cases. 

### Minimum reproduction code

It should be clear from detailed description. But in case if it still not, please let me know and I will create the project

### Expected behavior

ExternalContextCreator getContextModuleKey should search for moduleCtor in controllers as well as in providers

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@golevelup/nestjs-rabbitmq

### NestJS version

9.0.0

### Packages versions

```json

```

### Node.js version

16.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> is there a reason why ExternalContextCreator tries to find moduleCtor only in providers?

Because `ExternalContextCreator` was designed to be used only for providers.

> because it is common to have context in controllers and there is a possibility to extends contexts (ws, rpc)

There are different APIs for extending framework built-ins (adapters, transport strategies, etc.)
