### ISSUE TITLE
Incorrect Type for NestExpressAdapter

### ISSUE THREAD

**Issue by bmeverett** [nestjs/nest#11279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Type error on `server.keepAliveTimeout`. This was previously working on older versions and seems to have broken when the interface was typed in https://github.com/nestjs/nest/commit/d6a89fa613725f558562f998f8018f26003a75cf

### Minimum reproduction code

https://github.com/bmeverett/nest-keep-alive

### Steps to reproduce

Create a new NestJS application. 
In `main.ts` assign the `app.listen` call to a variable

When updating to NestJS 9.2.x and above the `keepAliveTimeout` is no longer able to be used on the response of `app.listen()`

```
 const app = await NestFactory.create<NestExpressApplication>(AppModule);
  const server = await app.listen(3000);
  server.keepAliveTimeout = 30_000
```

### Expected behavior

I believe the type should be `http.Server` (it inherits from the generic `Server`)

[Express](https://expressjs.com/en/api.html#app.listen)
[Http Server ](https://nodejs.org/api/http.html#http_server_listen)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3

### Packages versions

```json
platform-express version : 9.3.9
schematics version       : 9.0.4
testing version          : 9.3.9
common version           : 9.3.9
core version             : 9.3.9
cli version              : 9.2.0
```

### Node.js version

18.7

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
thanks for reporting! Let's track this here: #11280

I don't recall exactly why I pick `net` instead of `http` in there.
