### ISSUE TITLE
BaseExceptionFilter does not forward exception object to logger

### ISSUE THREAD

**Issue by ChrisiPK** [nestjs/nest#11285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When an error is thrown in the application, this error is handled by `BaseExceptionFilter`. In the code, the class checks whether it is an instance of `Error`. If it is, then it just logs the message and the stack trace.

https://github.com/nestjs/nest/blob/ffe96511099e503022eb4c0cb841c8e0be6a5aeb/packages/core/exceptions/base-exception-filter.ts#L71-L76

This is a problem for loggers that expect to receive the actual exception object. An example of this is the Sentry transport for Winston.

https://github.com/aandrewww/winston-transport-sentry-node/blob/5b466b42b3b7ea9c1983fd7ce5e463311ac9c072/src/transport.ts#L100-L102

### Minimum reproduction code

https://github.com/nestjs/nest

### Expected behavior

The logger should be supplied with the actual exception object and the stack, not just the message and the stack. This will enable transports to process the exception themselves.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

master

### Packages versions

NestJS v9
winston-transport-sentry-node v2.7.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
There are no plans to change the current behavior. However, you should be able to align with your needs by implementing a custom global exception filter.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
