### ISSUE TITLE
Request object when using ContextIdStrategy with Graphql doesnt contain the right information

### ISSUE THREAD

**Issue by maniator** [nestjs/nest#11292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a request is made to a regular API the request.headers object has data

When I make a GQL request however, it does not...

Here is what I used, directly copied from the docs with a name change...

```typescript
export class AuthBearerStrategy implements ContextIdStrategy {
  attach(contextId: ContextId, request: Request) {
    // request.headers is null, so the request errors out
    const tenantId = request.headers['authorization'] as string;
    let tenantSubTreeId: ContextId;

    if (tenants.has(tenantId)) {
      tenantSubTreeId = tenants.get(tenantId);
    } else {
      tenantSubTreeId = ContextIdFactory.create();
      tenants.set(tenantId, tenantSubTreeId);
    }

    console.log('TENANT', tenantId);

    // If tree is not durable, return the original "contextId" object
    return (info: HostComponentInfo) =>
      info.isTreeDurable ? tenantSubTreeId : contextId;
  }
}
```

### Minimum reproduction code

I put the code in the example... copied direct from the docs.

### Expected behavior

Should have access to the headers object on a gql request

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### Packages versions

```json
  "dependencies": {
    "@aws-sdk/client-secrets-manager": "^3.271.0",
    "@grpc/grpc-js": "^1.8.7",
    "@grpc/proto-loader": "^0.7.4",
    "@nestjs/apollo": "^10.2.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.3.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^10.2.0",
    "@nestjs/jwt": "^10.0.1",
    "@nestjs/microservices": "^9.3.5",
    "@nestjs/passport": "^9.0.1",
    "@nestjs/platform-express": "^9.3.9",
    "@nestjs/serve-static": "^3.0.1",
    "@nestjs/typeorm": "^9.0.1",
    "@vendia/serverless-express": "^4.10.1",
    "apollo-server-express": "^3.11.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "express": "^4.18.2",
    "graphql": "^16.6.0",
    "graphql-type-json": "^0.3.2",
    "helmet": "^6.0.1",
    "luxon": "^3.2.1",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-ldapauth": "^3.0.1",
    "pg": "^8.9.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "type-graphql": "^1.1.1",
    "typeorm": "^0.3.12"
  },

```

### Node.js version

18.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by maniator** [comment]
The weird part is that I see the headers themselves if I log the request object.... but it is locked behind a symbol key that I have no access to 

```
    [Symbol(kHeaders)]: {
      host: 'localhost:3000',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0',
      accept: '*/*',
      'accept-language': 'en-US,en;q=0.5',
      'accept-encoding': 'gzip, deflate, br',
      'content-type': 'application/json',
      authorization: 'Bearer ZHmlHMJVLNtOQdNp1XVqKCeSFaFPMnQGWn0gTTdH3Lg',
      'content-length': '1298',
      origin: 'http://localhost:3000',
      connection: 'keep-alive',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-origin'
    },

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
