### ISSUE TITLE
HMR not working in docker because of typescript: `^4.9.5`

### ISSUE THREAD

**Issue by sanzhardanybayev** [nestjs/nest#11299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

# NestJS HMR not working when using with Docker 

## Description
When running `docker-compose up` with the current `command` in the `docker-compose` file including `npm i --verbose`, Docker seems to exit after installing the packages. However, after removing `npm i --verbose` from the `command` in the `docker-compose` file and running `docker-compose up` again, Docker runs without any issues.

Furthermore, editing any source file does not trigger rebuilding as expected. The issue is not with the mounting of files, as changes made directly from the container do not solve the issue either. The only solution to trigger Docker rebuild is to force downgrade to `4.6.5`.

## Actual Behavior
Changes made to any source file do not trigger rebuilding.

## Possible Solution
The current version of Docker seems to be incompatible with the current `command` in the `docker-compose` file. Downgrading to `4.6.5` could be a temporary solution until a more permanent fix is found.

### Minimum reproduction code

https://github.com/sanzhardanybayev/nestjs-ts-hmr

### Steps to reproduce

1. Run `docker-compose up`
2. If Docker exits after installing packages, remove `npm i --verbose` from `command` in the `docker-compose` file and run `docker-compose up` again.
3. Edit any source file and observe that changes made to the file do not trigger rebuilding.

### Expected behavior

Editing any source file should trigger rebuilding, as Docker should recognize changes made to the files and rebuild accordingly.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

typescript

### NestJS version

^4.9.5

### Packages versions

```json
{
  "name": "test-hmlr",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "typescript": "^4.5.5",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I guess this is related with this: https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#file-watching-now-uses-file-system-events

Please play with [`watchOptions`](https://www.typescriptlang.org/docs/handbook/configuring-watch.html)

**Comment by sanzhardanybayev** [comment]
The only solution to trigger **HMR** is to downgrade to `4.6.5` 

But it's not it's very convenient to downgrade TS. A fix would be very appreciated.

**Comment by sanzhardanybayev** [comment]
@micalevisk thanks for the reference! 

Unfortunately `watchOptions` didn't help. I could have configured it in the wrong way. But from what I did I wasn't able to fix the issue.

**Comment by micalevisk** [comment]
I didn't manage to run your repro by following the steps to reproduce:

![image](https://user-images.githubusercontent.com/13461315/226221819-ce472ad5-1309-4e26-a1a4-8ef039f37d8f.png)

**Comment by sanzhardanybayev** [comment]
@micalevisk thanks for letting know! 

Just fixed the repo. Please pull latest changes and run `docker-compose up` again

**Comment by micalevisk** [comment]
looks like it went fine here on Ubuntu 22.04.2

[demo.webm](https://user-images.githubusercontent.com/13461315/226227636-a22b4d5e-7cea-4379-af1e-360f760e480b.webm)

**Comment by sanzhardanybayev** [comment]
@micalevisk  🤔  Looks very promising. 

Have you made any changes?  

I'm on Windows. Probably gotta switch to WSL now. 

Btw, have you made any changes?

**Comment by micalevisk** [comment]
> I'm on Windows

so why did you checked the Linux checkbox? :thinking: 

I just cloned your repro and ran `docker compose up`

**Comment by sanzhardanybayev** [comment]
@micalevisk my bad! I thought the question was where the code was tested. In this case, it's alpine, which is the distro of Linux.

**Comment by micalevisk** [comment]
try this out: https://docs.nestjs.com/faq/common-errors#file-change-detected-loops-endlessly

**Comment by sanzhardanybayev** [comment]
@micalevisk thanks! That solved the issue!

**Comment by Mathis-Levieux** [comment]
> try this out: https://docs.nestjs.com/faq/common-errors#file-change-detected-loops-endlessly
> 
> btw there's no _HRM_ here but `tsc` watch mode

Thank you so much men you saved me after a lot of troubles
