### ISSUE TITLE
Injecting a `Model` doesn't work in the constructor using `ModuleRef.get()`

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#11291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Getting a `Model` with `ModuleRef.get()` in the constructor of a service results in `null`:

```
constructor(
    @Inject(MY_MODULE_OPTIONS_TOKEN) private options: MyModuleOptions,
    private moduleRef: ModuleRef,
  ) {
    this.catModel = this.moduleRef.get(
      getModelToken(this.options.collectionName), { strict: false },
     );

    console.log(this.catModel); // null
  }
```

Thanks to @jmcdo29 he figured out that it works within the `onModuleInit()` hook.

### Minimum reproduction code

https://github.com/MickL/nestjs-model-injection-bug

Specific code with comments / different usecases are here:
https://github.com/MickL/nestjs-model-injection-bug/blob/main/src/my-library/my-service.service.ts

### Steps to reproduce

1. `npm install`
2. `npm start`
3. Check `my-library.service.ts`, I added comments / docs there

### Expected behavior

Should return the Model, same behavior as using `@Inject()` decorator.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.10

### Packages versions

```
[Nest Platform Information]
platform-express version : 9.3.10
schematics version       : 9.0.4
mongoose version         : 9.2.1
testing version          : 9.3.10
common version           : 9.3.10
core version             : 9.3.10
cli version              : 9.2.0
```

### Node.js version

19.1.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
You should never use `ModuleRef` in the constructor since the module (and its dependencies) are not yet initialized, hence the `onModuleInit` hook.
