### ISSUE TITLE
Request scoped providers are injected incorrectly when only one uses `forwardRef`

### ISSUE THREAD

**Issue by migueloller** [nestjs/nest#11294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The issue manifests itself when there's a provider that depends on another provider via `forwardRef` and that provider is request-scoped. Injected instances aren't present at request time (i.e., are `undefined`).

### Minimum reproduction code

https://github.com/migueloller/nest-forward-ref-repro

### Steps to reproduce

1. `pnpm i`
2. `pnpm start:dev`
3. `curl localhost:3000`

### Expected behavior

The expectation is that when the`AppController` method `getHello` calls the `AService` method `hello`, `this.bService` is not `undefined`, resulting in the following error: `TypeError: Cannot read properties of undefined (reading 'hello')`.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.10

### Packages versions

```json
{
  "@nestjs/common": "^9.0.0",
  "@nestjs/core": "^9.0.0",
  "@nestjs/platform-express": "^9.0.0",
  "reflect-metadata": "^0.1.13",
  "rxjs": "^7.2.0"
}
```

### Node.js version

v18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest/issues/5778#issuecomment-733547016

https://github.com/nestjs/nest/issues/7278

**Comment by migueloller** [comment]
@jmcdo29, thanks so much for the prompt response! This seems to be exactly the issue I'm running into. I understand the non-determinism and how things depend on which constructor is called first.

What I'm trying to understand is, irrelevant of the order, why can't NestJS instantiate all classes before calling the controller method? It seems this should be possible since the providers are injected in the constructor.

**Comment by migueloller** [comment]
Something else that I'll add is that the problem is fixed if a `forwardRef` is added in the other direction.

**Comment by micalevisk** [comment]
Here's the thread about this issue on our Discord: https://discord.com/channels/520622812742811698/1086374106087301202
