### ISSUE TITLE
Building monorepo app with lib outputs to wrong output directory using tsc

### ISSUE THREAD

**Issue by izacsc** [nestjs/nest#11295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When Building monorepo app with lib it outputs to dist/apps/withlib/apps/withlib using tsc.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-juxzd6?file=dist/apps/withlib/apps/withlib/src/main.js

### Steps to reproduce

npm build withlib

### Expected behavior

Output folder should be dist/apps/withlib.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

Maybe nestcli or tsc

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "nest-typescript-starter",
  "private": true,
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"apps/**/*.ts\" \"libs/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./apps/nest-typescript-starter/test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.4",
    "@types/node": "^18.0.3",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.5",
    "@typescript-eslint/parser": "^5.30.5",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^28.1.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.5",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": ".",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node",
    "roots": [
      "<rootDir>/apps/",
      "<rootDir>/libs/"
    ],
    "moduleNameMapper": {
      "^@app/mylib(|/.*)$": "<rootDir>/libs/mylib/src/$1"
    }
  }
}
```

### Node.js version

v16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by micalevisk** [comment]
that's because you have `"../../dist/apps/withlib"` at `apps/withlib/tsconfig.app.json`

It should be `"../../dist"`:

![image](https://user-images.githubusercontent.com/13461315/226192014-63839087-ab6e-4ae5-81e1-87eda705e4e5.png)

**Comment by kamilmysliwiec** [comment]
Using the monorepo mode with tsc makes no sense. If you don't want to use webpack, then you should consider setting up a custom configuration with TS project references & composite mode
