### ISSUE TITLE
Logging lifecycle hooks

### ISSUE THREAD

**Issue by Maligosus** [nestjs/nest#11301]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Many developers use third-party nestjs modules. But there are times when some third-party modules run onModuleInit or onApplicationBootstrap hooks. Among these cases, it happens that the functions stop the execution of the application from launching completely and nothing else happens. And in fairly large applications, it is very difficult to track

### Describe the solution you'd like

Log every execution of application lifecycle hooks

### Teachability, documentation, adoption, migration strategy

Documentation does not need to be updated

### What is the motivation / use case for changing the behavior?

Users will be able to understand which modules did not load

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
