### ISSUE TITLE
Update the Docs to provide Codesandbox examples

### ISSUE THREAD

**Issue by tomkuehl** [nestjs/nest#1130]
## I'm submitting a...
<pre><code>
[x] Documentation issue or request
</code></pre>

Hi,
as soon as this PR is merged it's possible to use Nest templates within Codesandbox: https://github.com/CompuIves/codesandbox-client/pull/1121
How about rewriting the examples in the documentation to provide embedded Codesandboxes? So the user can test stuff while exploring the docs. :smile: (https://codesandbox.io/docs/embedding)

**Comment by kamilmysliwiec** [comment]
We'll certainly do it! Looking forward to the Nest template 🙂 Thanks @tomkuehl

**Comment by kamilmysliwiec** [comment]
(and here is the documentation repo https://github.com/nestjs/docs.nestjs.com/issues btw :D but no worries, I'll take care of it, issue on the github is not required)
