### ISSUE TITLE
Multi-Provider doesn't work for user-defined tokens but why for internals?

### ISSUE THREAD

**Issue by zetti-caletti** [nestjs/nest#11314]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As stated here #770 [#4786](https://github.com/nestjs/nest/issues/4786), there is no support for multi providers.
However, why does it work for internal defined token? So to me it appears, that Nest supports the concept of multi-providers, but just doesn't allow it to use for users?! The solution with manually injection the providers and return an array is ugly. Angular shows the way how it works.

![Screenshot_20230322_013556](https://user-images.githubusercontent.com/75048883/226773148-faaf3883-2f09-471f-8797-fc3b1ee5ee52.png)

Both Interceptor are registered and run.
However with my search provider, only the last provider gets injected. If its not supported, this code should throw at least an error.

### Describe the solution you'd like

Should support multi-provider not only for predefined tokens from the framework, but also for user defined tokens.
Angular, Symfony, etc. supports this.

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

-

**Comment by micalevisk** [comment]
Here's a user-made implementation of such feature (kinda): https://dev.to/micalevisk/nestjs-tip-multi-value-providers-almost-like-multi-from-angular-1c63

**Comment by zetti-caletti** [comment]
> Here's a user-made implementation of such feature (kinda): https://dev.to/micalevisk/nestjs-tip-multi-value-providers-almost-like-multi-from-angular-1c63

Thanks :) Haven't finished reading it, but it states that the token has to be unique. But why it then works e. g. with APP_INTERCEPTOR. Is there a special logic in NestJs like "if (token == 'APP_INTERCEPTOR') // then accept multi"?

**Comment by zetti-caletti** [comment]
> Here's a user-made implementation of such feature (kinda): https://dev.to/micalevisk/nestjs-tip-multi-value-providers-almost-like-multi-from-angular-1c63

Thanks, I will try out your solution :+1:

**Comment by zetti-caletti** [comment]
> > this is inconsistent
> 
> yeah it looks inconsistent but it was a design decision.
> 
> Those built-in `APP_*` are 'special' providers. They are applied **globally**:
> 
> https://github.com/nestjs/nest/blob/5999d6b9e2377029777f3ee1daba4d1114624fdb/packages/core/scanner.ts#L583-L607
> 
> So it would still look inconsistent if we have that multi-provider. I don't think that this was the main reason on why we won't bring this feature to the core for now.

Ah ok I understand. Your solution works well. Thanks :) 
Maybe then at least your solution (provide function) should become part of nestjs, so that everybody can participate from that.
And then I would mention it in the docs, that there is this "workaround" solution.

**Comment by zetti-caletti** [comment]
"So it would still look inconsistent if we have that multi-provider."
Well if there would be multi providers I would have then to add multi: true for APP_INTERCEPTOR, thats it.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
