### ISSUE TITLE
NATS subscription isn't listening to messages

### ISSUE THREAD

**Issue by tupe12334** [nestjs/nest#11319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The`EventPattern` and the `MessagePattern` decorators aren't listening to specified patterns.

### Minimum reproduction code

https://github.com/tupe12334/nestjs-nats-error

### Steps to reproduce

1. npm I in both services
2. docker-compose up
3. start both of the services

The producer will start printing that it sending messages (and you can see them in the natscli)
<img width="682" alt="Screen Shot 2023-03-22 at 13 50 04" src="https://user-images.githubusercontent.com/61761153/226901056-dca79588-7d7a-4844-b3ce-a75b451dd6a2.png">

The consumer will not print anything 

### Expected behavior

The`EventPattern` and the `MessagePattern` decorators need to listen for the specified topic pattern.

### Package

- [X] <code>@nestjs/microservices</code>

### NestJS version

9

### Packages versions

**specified in the package.json**

### Node.js version

16.19.0

### In which operating systems have you tested?

- [X] macOS

**Comment by kamilmysliwiec** [comment]
Consumer application isn't a hybrid one meaning it doesn't really subscribe to messages:

![image](https://user-images.githubusercontent.com/23244943/227139432-184220a9-29af-4f3b-a1b8-56c298b9aec6.png)

Also, you can't use the following decorators (@MessagePattern and @EventPattern) on methods of a regular Injectable class:

![image](https://user-images.githubusercontent.com/23244943/227139537-a0fb521e-9d2a-4a66-88bc-bd44fefcdf6c.png)

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
