### ISSUE TITLE
Bug when combine NestJS + Docker + PinoJS

### ISSUE THREAD

**Issue by serhbs** [nestjs/nest#11326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After almost each reload I see an error:
![image](https://user-images.githubusercontent.com/33103361/227207190-46a9837a-9591-4464-84a3-61acf59d17f6.png)
After PinoJS has been added
Could you please help to resolve it?

### Minimum reproduction code

https://github.com/serhbs/nestemplate

### Steps to reproduce

save the file (reload env)

### Expected behavior

no issue

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

nestjs-pino

### NestJS version

9.0.0

### Packages versions

```json

```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by serhbs** [comment]
> looks like your repository is private

thx, you are right, opened it

**Comment by micalevisk** [comment]
I didn't ran your repro yet but I think that it is related with this bug: https://github.com/nestjs/nest-cli/issues/1614 

Are you 100% sure that this error doesn't appears when you import the `LoggerModule.forRoot` into `AppModule`?

**Comment by serhbs** [comment]
> I didn't run your repro yet but I think that it is related with this bug: [nestjs/nest-cli#1614](https://github.com/nestjs/nest-cli/issues/1614)
> 
> Are you 100% sure that this error doesn't appears when you don't import the `LoggerModule.forRoot` into `AppModule`?
> 
> I'm using `nestjs-pino` just fine by now

About you link, I see that problem is similar but it is not the same.
And I see no saluting there for my case (or maybe I am wrong? please correct me)

I guess that something with PinoJS.
And if you could help me - it will be super!

**Comment by serhbs** [comment]
JFYI: I see no error in case delete PinoJS, but I see no error in case if I run just clean NestJS + PinoJS + Docker.
I will check more and back with more detailed info in minutes

**Comment by serhbs** [comment]
> can you test this outside of Docker container?
> 
> I've been using `nestjs-pino` v3.1.2 and `pino` v8.7.0 with no worries on Linux.

I just did super simple APP.
https://github.com/serhbs/test-nest-pinojs-prisma

What I found - when I add PinoJS as well as Prisma - I see an error
In case I add just Prisma or PinoJS  (another module just comment) - no errort

could you help to find where the problem is?

**Comment by serhbs** [comment]
> I believe the issue is with Prisma and it's probably due to that issue I linked here before
> 
> Remove Prisma stuff from your repro (so nestjs + pino + docker) so we could confirm that.

As I wrote before, when I delete Prisma - I see no error here
