### ISSUE TITLE
Auth.js alternative for authentication

### ISSUE THREAD

**Issue by noiissyboy** [nestjs/nest#11331]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

passport js is not updated for a while. it would be great to add support for alternativ authentication such as Auth.js

### Describe the solution you'd like

passport js is not updated for a while. it would be great to add support for alternativ authentication such as Auth.js

### Teachability, documentation, adoption, migration strategy

passport js is not updated for a while. it would be great to add support for alternativ authentication such as Auth.js

### What is the motivation / use case for changing the behavior?

passport js is not updated for a while. it would be great to add support for alternativ authentication such as Auth.js

**Comment by kamilmysliwiec** [comment]
You don't need passport.js for authentication when using Nest.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
