### ISSUE TITLE
use ConfigModule but get the value in process.env is undefined

### ISSUE THREAD

**Issue by HandsomeTea** [nestjs/nest#11398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

it just a nestjs project for study, successful operation requires configuring mongodb and redis, it is run successfully denpends on config process.env.REDIS_URL, problem is:
1, I confirm that I first loaded the `ConfigModule` module before use it，you can view my code，and run `npm run struct` to view my business module dependencies
2，`process.env.REDIS_URL` is `undefined` when I start project：
![image](https://user-images.githubusercontent.com/20680635/227838750-dfdffcb1-0c62-412a-a68e-e82751b2bba8.png)

but it is very strange when I give a direct redis url (this allows the program to start normally):
![image](https://user-images.githubusercontent.com/20680635/227840122-c8bd905a-8ba6-4b9a-b0d8-e9499007af92.png)

Just a short time(10ms) later, `process.env.REDIS_URL`has a value, and use `process.env.DB_URL` to connect mongodb is successful but I didn't give `process.env.DB_URL` a direct value

### Minimum reproduction code

https://github.com/HandsomeTea/nestjs-server

### Expected behavior

I hope that after using `ConfigModule`, I can use `process.env.any` to obtain the configured value immediately

or my project can start successful use this code(mabe my code has some error)
![image](https://user-images.githubusercontent.com/20680635/227841178-c9a8712a-203c-4b26-8e72-03f55b09ca1c.png)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/config

### NestJS version

"@nestjs/core": "^9.0.0"

### Packages versions

```json
"dependencies": {
        "@nestjs/apollo": "^11.0.4",
        "@nestjs/common": "^9.0.0",
        "@nestjs/config": "^2.3.1",
        "@nestjs/core": "^9.0.0",
        "@nestjs/graphql": "^11.0.4",
        "@nestjs/mapped-types": "*",
        "@nestjs/mongoose": "^9.2.1",
        "@nestjs/platform-express": "^9.0.0",
        "@nestjs/sequelize": "^9.0.0",
        "@nestjs/terminus": "^9.2.1",
        "class-transformer": "^0.5.1",
        "class-validator": "^0.14.0",
        "compression": "^1.7.4",
        "csurf": "^1.11.0",
        "express-http-context": "^1.2.4",
        "graphql": "^16.6.0",
        "graphql-query-complexity": "^0.12.0",
        "graphql-subscriptions": "^2.0.0",
        "jsonwebtoken": "^9.0.0",
        "log4js": "^6.8.0",
        "nestjs-ioredis": "^0.1.8",
        "pg": "^8.10.0",
        "reflect-metadata": "^0.1.13",
        "rxjs": "^7.2.0",
        "sequelize-typescript": "^2.1.5"
    },
    "devDependencies": {
        "@compodoc/compodoc": "^1.1.19",
        "@nestjs/cli": "^9.0.0",
        "@nestjs/schematics": "^9.0.0",
        "@nestjs/testing": "^9.0.0",
        "@types/express": "^4.17.13",
        "@types/ioredis": "^5.0.0",
        "@types/jest": "29.2.4",
        "@types/node": "18.11.18",
        "@types/supertest": "^2.0.11",
        "@typescript-eslint/eslint-plugin": "^5.0.0",
        "@typescript-eslint/parser": "^5.0.0",
        "eslint": "^8.0.1",
        "eslint-config-prettier": "^8.3.0",
        "eslint-plugin-prettier": "^4.0.0",
        "jest": "29.3.1",
        "prettier": "^2.3.2",
        "source-map-support": "^0.5.20",
        "supertest": "^6.1.3",
        "ts-jest": "29.0.3",
        "ts-loader": "^9.2.3",
        "ts-node": "^10.0.0",
        "tsconfig-paths": "4.1.1",
        "typescript": "^4.7.4"
    },
```

### Node.js version

v18.15.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by HandsomeTea** [comment]
The code path for the screenshot is `src/dal/cache/cache.module.ts`

**Comment by jmcdo29** [comment]
This is due to how the `ConfigModule` and decorators in general work. Not a bug. For further assistance, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by HandsomeTea** [comment]
Do you mean that using the ConfigModule to set the value for process.env cannot be used in the imports parameter of the module during initial project startup?
I think this scenario is very common, some parameters configured through process.env must be used during initial startup, such as process.env.REDIS_URL in my project
ConfigModule should provide a solution at least, otherwise using ConfigModule is not as useful as writing a function myself to configure the value for process.env

this is a suggestion

**Comment by jmcdo29** [comment]
> I think this scenario is very common, some parameters configured through process.env must be used during initial startup, such as process.env.REDIS_URL in my project

That's what the use of `forRootAsync`/`registerAsync` and using `useFactory` with `inject:[ConfigService]` is for, to ensure that the `process.env` has been populated. If you don't like that approach, use `dotenv` directly and run the `config` method in your `main.ts` **before** all other imports
