### ISSUE TITLE
The PartialType function will lost metadata of it's first param when using webpack.config.js

### ISSUE THREAD

**Issue by shangchen0531** [nestjs/nest#11421]
### Is there an existing issue for this?

- [] I have searched the existing issues

### Current behavior

I am trying to define an update-dto by the `PartialType` imported from `@nestjs/mapped-types`, 
```js
import { PartialType } from '@nestjs/mapped-types';
import { CreateRoomDto } from './create-room.dto';

export class UpdateRoomDto extends PartialType(CreateRoomDto) {}
```
and when I update it's data, 
```js
{
    "monsters": [
        {
            "id": "99",
            "name": "ERROR LIST DATA",
            "num": 15
        }
    ]
}
```
the array field of nested schema has not been validated correctly. The metadata of UpdateRoomDto is missing. And the data type have been converted from Object to Array.
```js
monsters: [ [ id: '99', name: 'ERROR LIST DATA', num: 15 ] ]
```

And the response from api is,
```js
{
  ...
  "monsters": [
    {}
  ],
  ...
}
```

But in the second dto, when I manully define all members of update-dto,
```js
// import { PartialType } from '@nestjs/mapped-types';
import { Type } from 'class-transformer';
import {
    IsInt,
    IsArray,
    IsOptional,
    ValidateNested,
    IsString,
    IsBoolean,
} from 'class-validator';
import { BossItemDto } from './create-floor.dto';

export class UpdateFloorDto {

    @IsInt()
    @IsOptional()
    bindZ?: number;

    @IsArray()
    @IsOptional()
    @ValidateNested({
        each: true,
    })
    @Type(() => BossItemDto)
    boss?: BossItemDto[];

    @IsString()
    @IsOptional()
    name?: string;

    @IsOptional()
    @IsString()
    nextFloorId?: string;

    @IsBoolean()
    @IsOptional()
    open?: boolean;
}
```

and update it's data,
```js
{
    "boss": [
        {
            "id": "8",
            "name": "PASS DATA",
            "num": 68
        }
    ]
}
```
it has been validated right.

The right response:
```js
{
  "boss": [
    {
      "id": "69",
      "name": "boss",
      "num": 10
    }
  ],
}
```

### Minimum reproduction code

https://github.com/shangchen0531/NestJSPartialTypeBug

### Expected behavior

Update-dto with array field of the nested schema should be validated rightly when using `PartialType`.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/mapped-types

### NestJS version

9.0.0

### Packages versions

```json
"@nestjs/common": "^9.0.0",
"@nestjs/config": "^2.3.1",
"@nestjs/core": "^9.0.0",
"@nestjs/mapped-types": "^1.2.2",
"@nestjs/mongoose": "^9.2.2",
"@nestjs/platform-express": "^9.0.0",
"@nestjs/cli": "^9.0.0",
"@nestjs/schematics": "^9.0.0",
"@nestjs/testing": "^9.0.0",
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
