### ISSUE TITLE
Allow returning (and registering) a FactoryProvider or an array of FactoryProvider from useFactory to allow more flexibility in dynamic module

### ISSUE THREAD

**Issue by SteadEXE** [nestjs/nest#11425]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

At the moment I have a dynamic module registered like this:

```typescript
MyModule.forRootAsync({
  useFactory: (config: ConfigService) => {
	return {
	  version: config.get<number>('compatibility_version')
	}
  },
  inject: [ ConfigService ]
})
```

This is the code of my module:
```typescript
@Module({
  imports: [
    CqrsModule
  ]
})
export class MyModule {
  static forRootAsync (options: MyModuleAsyncOptions): DynamicModule {
    return {
      module: MyModule,
      imports: [
        CqrsModule
      ],
      providers: [
        ...this.createAsyncProviders(options),
        {
          provide: 'HANDLERS',
          useFactory: (options: MyModuleOptions) => {
            if (options.version === 1) {
              return [ {
                provide: CQRSHandlersV1,
                useClass: CQRSHandlersV1
              } ];
            }

            return [ {
              provide: CQRSHandlersV2,
              useClass: CQRSHandlersV2
            } ];
          },
          inject: [ MY_MODULE_OPTIONS ]
        }
      ],
      exports: [
        CqrsModule
      ]
    }
  }

  private static createAsyncProviders (
    options: MyModuleAsyncOptions
  ): Provider[] {
    if (options.useExisting || options.useFactory) {
      return [ this.createAsyncOptionsProvider(options) ];
    }

    return [
      this.createAsyncOptionsProvider(options),
      {
        provide: options.useClass,
        useClass: options.useClass
      }
    ];
  }

  private static createAsyncOptionsProvider (
    options: MyModuleAsyncOptions
  ): Provider {
    if (options.useFactory) {
      return {
        provide: MY_MODULE_OPTIONS,
        useFactory: options.useFactory,
        inject: options.inject || []
      };
    }

    return {
      provide: MY_MODULE_OPTIONS,
      useClass: options.useClass,
      useExisting: options.useExisting
    }
  }
}
```

At the moment the array of FactoryProvider returned by the useFactory inside forRootAsync is not registered.
The only way I found was to use forRoot instead of forRootAsync and hardcode the version when I register my module.

MY_MODULE_OPTIONS is not yet available in forRootAsync, so I can't construct on array of providers with it. 

### Describe the solution you'd like

Maybe one solution would be to add an another type of provider. (More complicated I think but no breaking changes)

One solution would be, if useFactory returns an ExistingProvider, FactoryProvider, ValueProvider or ClassProvider, register it.
A kind of recursive registration.

### Teachability, documentation, adoption, migration strategy

I think we could use the existing doc, especially the one teaching useFactory, and say that if useFactory returns an array of provider, it would be registered aswell.

### What is the motivation / use case for changing the behavior?

I don't think there is a way to change the list of providers when using an async registration method if the list depends on another provider (like MY_MODULE_OPTIONS in my case).

Maybe I am totally wrong and I am trying to go in a wrong direction.

Have a nice day everyone.

**Comment by kamilmysliwiec** [comment]
This has been discussed several times in the past (search through old issues).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
