### ISSUE TITLE
Optimize dependencies in monorepo

### ISSUE THREAD

**Issue by dthib** [nestjs/nest#11431]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hi,
I would like to use the monorepo cli but each app can have its own dependencies and I don't want to make the docker image heavier if the specific dependencies are not needed.
Is there any solution for this issue (or maybe i am missing something and webpack is doing the job?) ? Have you thought of using lerna for this purpose ?
Thanks

### Describe the solution you'd like

Maybe be able to use lerna (i have never used it) ?

### Teachability, documentation, adoption, migration strategy

Maybe have a lerna mode when creating the monorepo ?

### What is the motivation / use case for changing the behavior?

Optimize docker image for each microservice. Embed only needed dependencies.

**Comment by kamilmysliwiec** [comment]
You can dynamically generate a package.json file using, for example, this plugin https://www.npmjs.com/package/generate-package-json-webpack-plugin

Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
