### ISSUE TITLE
Dependency injection with new Logger(MyService.name);

### ISSUE THREAD

**Issue by geogeim** [nestjs/nest#11432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to create a custom `LoggerService` that uses `@Inject(REQUEST)` to get request parameters
```js
@Injectable({ scope: Scope.TRANSIENT })
export class LogService extends ConsoleLogger {
  @Inject(REQUEST) private request;
....
```

When i use it in a service with dependency injection like this:
```js
export class MyService {
  constructor(private readonly logger: LogService) {
    logger.setContext(MyService.name);
}
```
Everything works fine
But when i use it like usual:

```js
import { Logger } from '@nestjs/common';
....
export class MyService {
  private logger = new Logger(MyService.name);
....
}
```
The injection doesn't take place (i.e. request variable is undefined)

### Minimum reproduction code

http://github.com

### Expected behavior

injection should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
    "@nestjs/apollo": "^10.0.16",
    "@nestjs/axios": "^0.0.8",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^10.0.16",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/swagger": "^5.2.1",
    "@nestjs/terminus": "^9.2.1",
    "@nestjs/typeorm": "^9.0.0",
```

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
This is the expected behavior. For support, please use our [Discord](https://discord.gg/nestjs) . We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by josephaw1022** [comment]
I would look here https://docs.nestjs.com/fundamentals/injection-scopes#request-provider

This seems like an issue with your scope

**Comment by micalevisk** [comment]
You're calling `new LogService` by yourself so there is no chance to let nestjs intercept that call. That's why.
