### ISSUE TITLE
Nested Files handling to upload files

### ISSUE THREAD

**Issue by Pro-File** [nestjs/nest#11436]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am a developer and I am making a nest JS API which can handle normal file uploads and nested file uploads.

The architecture of my DTO is like:

export class CreateNewFulltimeEmployeeDto {

  @ApiProperty({ type: 'string', format: 'binary' })
  profileImage: any;

  @ApiProperty({ type: 'string', format: 'binary' })
  contractFilePath: any;

  @ValidateNested({ each: true })
  @ApiProperty({
    type: [QualificationInfoDto],
    additionalProperties: true,
  })
  @Type(() => QualificationInfoDto)
  @Transform(({ value }) => JSON.parse(value), { toClassOnly: true })
  @IsArray()
  qualificationInfo: QualificationInfoDto[];
}

where as in QualificationInfoDto:

export class QualificationInfoDto {
  @IsOptional()
  @ApiProperty({ type: 'string', format: 'binary' })
  qualificationInfoDoc: any;
}

I want to parse qualificationInfoDoc File through any of the FileInterceptor decorator but there is no way I can reach my destination. 
NOTE: The qualificationInfoDoc property belongs to an object of an array named QualificationInfo which is a property of a CreateNewFullTimeEmployeeDto. 

Please, assist me and I will be very thankful to you!

### Describe the solution you'd like

I am looking for a solution.

### Teachability, documentation, adoption, migration strategy

It is not a new useCase but I didn't find any findings.

### What is the motivation / use case for changing the behavior?

So that any one can handle this useCase.

**Comment by Tony133** [comment]
Hi @Pro-File, for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel

The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.
