### ISSUE TITLE
Proposal: Monorepo add frontend framework support, React , Vue and etcd

### ISSUE THREAD

**Issue by jphunt** [nestjs/nest#11455]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

wanna add frontend app inside nestjs monorepo

### Describe the solution you'd like

no idea

### Teachability, documentation, adoption, migration strategy

have to configure mannaully

### What is the motivation / use case for changing the behavior?

a lot project including both frontend and backend, also wanna utilize monorepo

**Comment by Tony133** [comment]
Hi @jphunt,
 
For this there is already a workspace that does this called Nx: https://nx.dev/getting-started/intro, here: https://nx.dev/packages you can find the available frameworks that you can integrate into a mono repository and personally it is my favorite. 
So I do not think it is necessary for the NestJS Core Team to add frontend support.

With Nx you can integrate NestJS with Angular or React or Vue. 

I hope I was helpful.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
