### ISSUE TITLE
Proposal: package some core components into packages, again within the same monorepo for the next major version of NestJS v10

### ISSUE THREAD

**Issue by Tony133** [nestjs/nest#11454]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

N/A

### Describe the solution you'd like

Currently the RouterModule class is exported from the `@nestjs/core` package it would be nice if it was imported for example as follows:

`import { RouterModule } from '@nestjs/router';`

For example, to start creating microservices, we need to install the package `@nestjs/microservices` and we need to do the same when we need to build WebSockets based applications install the package `@nestjs/websockets` a way to separate into packages some parts the core of NestJS.

The same could be done with REPL, it could be installed with `@nestjs/repl`, and imported for example:

`import { repl } from '@nestjs/repl';`

again within the same monorepo.

These are the two parts of the core that I noticed where it is feasible as a thing.

Let me know what you think 

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

N/A

**Comment by kamilmysliwiec** [comment]
Core & router packages depend on each other so if we decided to split them up we'd introduce yet another annoying circular relationship 😄 

As for REPL, I was initially thinking of publishing it as a separate package but eventually decided to keep it close to the core. Luckily, we don't really need to worry about the size of packages that much
