### ISSUE TITLE
WebSocket server causing application failure

### ISSUE THREAD

**Issue by Lucky38i** [nestjs/nest#11456]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8.3.1 -> 9.3.10

### Describe the regression

Migration has been successful except for when the WebSocket server is handling received messages which throws a node exception causing the application to fail. 
![](https://media.discordapp.net/attachments/838062729398976522/1095414860461899827/71879cbe4c8886d18d5952dc48561908.png)
I’ve added the code snippet where the gateway is [Full code](https://github.com/flybywiresim/simbridge/blob/main/apps/server/src/interfaces/mcdu.gateway.ts)

Just to confirm I’m using WS and not no socket.io
```ts
// Gateway Adapter
    app.useWebSocketAdapter(new WsAdapter(app));
```

### Input code

```ts

export class McduGateway implements OnGatewayInit, OnGatewayConnection {
    constructor(
        @Inject(serverConfig.KEY) private serverConf: ConfigType<typeof serverConfig>,
        private printerService: PrinterService,
        private networkService: NetworkService,
    ) {}

    private readonly logger = new Logger(McduGateway.name);

    @WebSocketServer() server: Server

    async afterInit(server: Server) {
        this.server = server;
        this.logger.log('Remote MCDU websocket initialised');
        this.logger.log(`Initialised on http://${await this.networkService.getLocalIp(true)}:${this.serverConf.port}${server.path}`);
    }

    handleConnection(client: WebSocket) {
        this.logger.log('Client connected');
        client.on('message', (message: String) => {
            if (message === 'mcduConnected') {
                this.logger.log('Simulator connected');
            }
            this.server.clients.forEach((client) => {
                if (client.readyState === WebSocket.OPEN) {
                    client.send(message);
                }
            });
            if (message.startsWith('print:')) {
                const { lines } = JSON.parse(message.substring(6));
                this.printerService.print(lines);
            }
        });
    }
}

```

### Expected behavior

The gateway should handle receiving messages as expected with throwing an exception like before the migration.

**Comment by Lucky38i** [comment]
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
> 
> 
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

That's not really feasible as you'd need to setup a websocket client to push a message to the server to trigger the runtime error.

**Comment by kamilmysliwiec** [comment]
@Lucky38i you could add an index.html file that auto-pushes a message that triggers the error
