### ISSUE TITLE
cant connect to redis v7

### ISSUE THREAD

**Issue by hatemragab** [nestjs/nest#11492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i cant connect to redis v 7

### Minimum reproduction code

 hb

### Steps to reproduce

i cant connect to redis v 7

### Expected behavior

i cant connect to redis v 7

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [X] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.0

### Packages versions

```json

```

### Node.js version

17.9.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
this is a general **nodejs** question not related with Nest.

---

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
