### ISSUE TITLE
Support Additional RESTful methods: COPY, LINK, UNLINK

### ISSUE THREAD

**Issue by j1i-ian** [nestjs/nest#11491]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello, 
We have construct app with Nest.js 
and need additional RESTful methods to use [RFC 2068](https://www.rfc-editor.org/rfc/rfc2068) especially COPY, LINK, UNLINK.

Http method represents action about resource, but there is no implemented feature/function like decorator for COPY, LINK, UNLINK in Nest.js. 
RESTful API is designed for optimization network-based activations including cache, proxy etc. So, Divide concern of action (SoC) means us to allow we can control traffic caching, proxy buffering by method, to support more plentiful ways what makes happy users with elegant way  like HATEOAS. 

So I hope Nest.js teams to support this features.

### Describe the solution you'd like

I would like to use this function for communication with frontend about resource control like item duplication, linking between items or unlink them.
Also it allows to separate COPY from POST.

and then, We will plan cache strategy more correctly.

### Teachability, documentation, adoption, migration strategy

It this feature is added, I wish I can add about COPY, LINK, UNLINK to [controller-resource part](https://docs.nestjs.com/controllers#resources)

### What is the motivation / use case for changing the behavior?

I love so much `Standardization`. And supporting standard means we inherit legacy from all Pioneers of Web including their hyper concept, sensitive  controlling of web. e.g. you must consider caching is often used on fetching data but not write. But if we should make more efficient about writing work, writing also can be separated with pure creating and COPYING already exist one. Then the latter can be cached. This example is just one variants of why RESTful action follows separating by http method including LINK, UNLINK, other unsupported methods.

The First RESTful framework in Java, Jersey Framework, is maded by Sun microsystems, would make more easy and fast expandible services (Even also it supported making custom method by user).

on nowadays central of open source is moved to typescript by Google-Oracle legal war, but it is not means stopping to implementation of standard is good. I wish Nest.js can be organisation that implement standardization for making IT more beautiful world like as Sun microsystem tried making happy IT development environment

**Comment by ProductOfAmerica** [comment]
NestJS uses either Express or Fastify as the underlying web framework depending on the chosen adapter. Since both Express and Fastify do not support the LINK and UNLINK HTTP methods, it's not possible to use those methods in NestJS directly.

[https://www.fastify.io/docs/latest/Reference/Routes/#routes-options](fastify)
