### ISSUE TITLE
NestJS : Not able to use Apollo Studio Explorer

### ISSUE THREAD

**Issue by skatkar** [nestjs/nest#11537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to use Apollo Studio Explorer with NestJS graphql (express server). I'm adding ApolloServerPluginLandingPageLocalDefault in the plugins array of GraphQLModule. Additional details are posted on Stackoverflow here : https://stackoverflow.com/questions/76058998/nestjs-not-able-to-use-apollo-studio-explorer

It fails with this exception:

```
error TS2322: Type 'ApolloServerPlugin<BaseContext>' is not assignable to type 'ApolloServerPlugin<any>'.
  Types of property 'serverWillStart' are incompatible.
    Type '(service: GraphQLServiceContext) => Promise<void | GraphQLServerListener>' is not assignable to type '(service: GraphQLServerContext) => Promise<void | GraphQLServerListener>'.
      Types of parameters 'service' and 'service' are incompatible.
        Type 'GraphQLServerContext' is missing the following properties from type 'GraphQLServiceContext': schemaHash, serverlessFramework

43       plugins: [ApolloServerPluginLandingPageLocalDefault()],
```

### Minimum reproduction code

I don't have a Git repository

### Expected behavior

Able to integrate Studio explorer.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/apollo

### NestJS version

9.4.0

### Packages versions

```json
[Nest Platform Information]
devtools-integration version : 0.1.4
platform-express version     : 9.4.0
schematics version           : 9.1.0
graphql version              : 11.0.5
typeorm version              : 9.0.1
testing version              : 9.4.0
apollo version               : 11.0.5
common version               : 9.4.0
config version               : 2.3.1
core version                 : 9.4.0
cli version                  : 9.4.0
```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
