### ISSUE TITLE
Redis v7 not able to connect to microservices

### ISSUE THREAD

**Issue by hatemragab** [nestjs/nest#11530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when i try to connect microservices by  Transport.REDIS
but with REDIS version 7 it says 
Error: Connection is closed
but when use version 6 it works good
i think there are some break changes
see Minimum reproduction code
for full example

### Minimum reproduction code

https://github.com/hatemragab/micro-redis-bug

### Steps to reproduce

npm start:dev

### Expected behavior

i just call this code 
```
//this database will delete after this issue close
const digitalOceanOptions = {
  host: 'db-redis-nyc1-93996-do-user-6764627-0.b.db.ondigitalocean.com',
  username: 'default',
  password: 'AVNS_-m_Sz9Q_i4SMljmnQXp',
  port: 25061,
};

 app.connectMicroservice<MicroserviceOptions>({
    transport: Transport.REDIS,
    /// this testing v7 redis hosted on digitalocean self database management
    /// this db will delete after close this issue
    options: digitalOceanOptions,
  });
```
when i try to connect to this redis by the normal redis package it connected  
```
const client = createClient(digitalOceanOptions);
// Listen for the 'connect' event
client.on('connect', () => {
  console.log('Connected to Redis from redis not front nest microservice!!');
});

// Listen for the 'error' event
client.on('error', (err) => {
  console.error('Failed to connect to Redis', err);
});
client.connect();
```
so the problem now come from nestjs **microservice**

see Minimum reproduction code
for full example

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

    "ioredis": "^5.3.2",     "redis": "^4.6.5",

### NestJS version

9.4.0

### Packages versions

```json
{
  "name": "micro-redis-bug",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.4.0",
    "@nestjs/core": "^9.4.0",
    "@nestjs/microservices": "^9.4.0",
    "@nestjs/platform-express": "^9.4.0",
    "ioredis": "^5.3.2",
    "redis": "^4.6.5",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.4.0",
    "@nestjs/schematics": "^9.1.0",
    "@nestjs/testing": "^9.4.0",
    "@types/express": "^4.17.17",
    "@types/jest": "29.5.0",
    "@types/node": "18.15.11",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.58.0",
    "@typescript-eslint/parser": "^5.58.0",
    "eslint": "^8.38.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "29.5.0",
    "prettier": "^2.8.7",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "29.1.0",
    "ts-loader": "^9.4.2",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.2.0",
    "typescript": "^5.0.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other
my nodejs version is v17.9.1
[Nest] 62187  - 04/19/2023, 1:07:18 PM   ERROR [Server] Retry time exhausted

/Users/hatemragap/Downloads/micro-redis-bug/node_modules/ioredis/built/Redis.js:207
                    reject(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
                           ^
Error: Connection is closed.
    at EventEmitter.connectionCloseHandler (/Users/hatemragap/Downloads/micro-redis-bug/node_modules/ioredis/built/Redis.js:207:28)
    at Object.onceWrapper (node:events:642:26)
    at EventEmitter.emit (node:events:527:28)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by kamilmysliwiec** [comment]
Can you reproduce this issue with a locally installed Redis v7 db?

**Comment by hatemragab** [comment]
ok i will do

**Comment by ragingprodigy** [comment]
@hatemragab @kamilmysliwiec  I'm able to connect to a local instance of Redis v7 db. @hatemragab I'd suggest looking into establishing a connection to that remote redis instance (outside of the NestJS setup) using a tool like `redis-client` or `telnet`

**Comment by hatemragab** [comment]
> @hatemragab @kamilmysliwiec  I'm able to connect to a local instance of Redis v7 db. @hatemragab I'd suggest looking into establishing a connection to that remote redis instance (outside of the NestJS setup) using a tool like `redis-client` or `telnet`

yes me too i can connect to v7 from nestRedis 
but not from nestMicroservice only

**Comment by ragingprodigy** [comment]
@hatemragab So, you mean the code block below results in an error if your `localOptions` points to a Redis v7 instance running locally?

```typescript
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.connectMicroservice<MicroserviceOptions>({
    transport: Transport.REDIS,
    options: localOptions, // this works for me when I point it to a local Redis v7 instance
  });
  await app.startAllMicroservices();
  await app.listen(3000);
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
