### ISSUE TITLE
Nest Pipe - Update Decorator for pipes from @Injectable to @Pipe, to be consist with Angular

### ISSUE THREAD

**Issue by dinbtechit** [nestjs/nest#11545]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As of Angular 15, angular now has a dedicated decorator for pipes. It would be nice if that same consistency is carried over to Nest as well.

Test Pipe:

**nest app**
```ts
@Injectable()
export class TestPipe implements PipeTransform {
  transform(value: any, metadata: ArgumentMetadata) {
    return value;
  }
}

```

**Angular app**
```ts
@Pipe({
  name: 'test'
})
export class TestPipe implements PipeTransform {
  transform(value: unknown, ...args: unknown[]): unknown {
    return value;
  }
}

```

### Describe the solution you'd like

use `@Pipe` decorator for pipes.

### Teachability, documentation, adoption, migration strategy

nest g pipe <pipename>

### What is the motivation / use case for changing the behavior?

To keep it consistent with Angular.

**Comment by micalevisk** [comment]
> To keep it consistent with Angular.

can you please elaborate on why is this? :thinking:

**Comment by dinbtechit** [comment]
That's fair. The only reason is to keep the decorator name consistent with Angular. I don't have anything else to elaborate. 

I understand those 2 frameworks have different roles but the concept of pipe in nestjs is the same as angular, no?

Anywho, I see where you coming probably for nestjs it makes more sense to have that as `@Injectable()` as it will always be used through constructor injection.

Closing this for now.
