### ISSUE TITLE
Wildcard must be the last character in the route

### ISSUE THREAD

**Issue by pedroluiznogueira** [nestjs/nest#11543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

``While following the documentation on section [Controllers - Route Wildcards](https://docs.nestjs.com/controllers#route-wildcards).

The provided example does not work as expected:

```typescript
@Get('ab*cd')
findAll() {
  return 'This route uses a wildcard';
}
```

When running the application I get:
```shell
throw new Error('Wildcard must be the last character in the route')
              ^
Error: Wildcard must be the last character in the route
```

A wildcard at the end works just fine

```typescript
@Get('abcd*')
findAll() {
  return 'This route uses a wildcard';
}
```

### Minimum reproduction code

https://gist.github.com/pedroluiznogueira/f2efbe53045cd67ef13e3bcc0ac29125

### Steps to reproduce

1. open https://docs.nestjs.com/controllers#route-wildcards
2. create a nest example using nest cli
3. create a controller with the wildcards route provided in the example
4. run `npm install`
5. run `npm start`

### Expected behavior

If there's anything else to be done when using wildcards like `ab*cd` it would be nice to have that in the docs. And if not supported at all, make that explicit.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
  "name": "nest-api-docs",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^10.0.3",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-fastify": "^9.4.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.0",
    "@types/node": "18.15.11",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.5.0",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "roots": [
      "src",
      "test"
    ],
    "testRegex": ".*\\.(spec|e2e-spec)\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

16.19.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I would be happy to contribute if that's indeed a bug, and any change is needed! :smile:

**Comment by jmcdo29** [comment]
I cannot reproduce this using Nest and express. 
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by pedroluiznogueira** [comment]
will share in just a bit @jmcdo29

**Comment by jmcdo29** [comment]
It looks like this is a [limitation of fastify](https://www.fastify.io/docs/latest/Reference/Routes/) and their underlying library [find-my-way](https://github.com/delvedor/find-my-way#match-order). We should mention in the docs that a wildcard in the middle of the route is only supported by express

**Comment by pedroluiznogueira** [comment]
yeah, just realized that now as well, when using the defaults for generating the `INestApplication` the error goes away.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
