### ISSUE TITLE
Allowed override path for swagger

### ISSUE THREAD

**Issue by wenerme** [nestjs/nest#11548]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

e.g. I have a route like

```ts
@Get('enc/:format/*')
@ApiOperation({ summary: 'Encode data to QR code' })
```

The generated doc can not change the `*` part, for generated doc I want to use `enc/:format/:data`

### Describe the solution you'd like

Maybe add a `path` to `@ApiOperation` ?

### Teachability, documentation, adoption, migration strategy

Will not break anything.

### What is the motivation / use case for changing the behavior?

Fastify only support syntax like `abc/*` format for wildcard.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
