### ISSUE TITLE
HttpExceptions and their children are not logged

### ISSUE THREAD

**Issue by doojin** [nestjs/nest#11579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a service method:

```typescript
@Injectable()
export class AppService {
  getHello(): string {
    throw new InternalServerErrorException('test error');
  }
}
```

When controller calls the service and a `HttpException` (or any it's child like `InternalServerErrorException`) is thrown, I receive a proper HTTP response but logger does not log anything.

On the other hand, if I throw a custom error, like: 
```typescript
throw new Error('test');
```

I can see proper logging as expected:
```
[Nest] 71531  - 04/29/2023, 1:41:04 AM   ERROR [ExceptionsHandler] test
Error: test
<stacktrace here>
```

I believe this is happening because of this check:
https://github.com/nestjs/nest/blob/85966703ac57a5b263ab5807033f6ac78548c0ef/packages/core/exceptions/base-exception-filter.ts#L30

But this does not make any sense, I want to see HTTP errors in my logs same way I see any other errors. I dived into docs but wasn't able to find the way to enable these logs by default. The only solution I can think of is implementing custom exception handler and using it globally.

### Minimum reproduction code

https://github.com/doojin/NestLogHttpException

### Steps to reproduce

1. `npm install`
2. `npm start`
3. Access http://localhost:3000/

### Expected behavior

I'm expecting to see any errors happening for the users of my web application in the logs, including `HttpException` errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
```

### Node.js version

20.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by doojin** [comment]
In the meanwhile my workaround is creating a logger instance in the service and explicitly do the logs myself:
```typescript
try {
  // my logic
} catch (e) {
  const error = 'some error details';
  this.logger.error(error, e);
  throw new InternalServerErrorException(error, { cause: e });
}
```

This way error appears properly in the HTTP response and logs. Have to not forget to do this manually everywhere tho.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
