### ISSUE TITLE
GraphQL CLI Plugin option typeFileNameSuffix only takes in consideration extensions

### ISSUE THREAD

**Issue by olivierpascal** [nestjs/nest#11581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am not using the regular `user.model.ts` naming convention, but rather `UserModel.ts`.

GraphQL CLI Plugin option typeFileNameSuffix works with ".model.ts" suffix, but does not work with "Model.ts" suffix.

The following `nest-cli.json` config:

```
"compilerOptions": {
  ...
  "plugins": [
    {
      "name": "@nestjs/graphql",
      "options": {
        "typeFileNameSuffix": [".model.ts", "Model.ts"],
        "introspectComments": true
      }
    }
  ]
},
```

Successful parse `User.model.ts` but fail to parse `UserModel.ts` file.

### Minimum reproduction code

https://github.com/olivierpascal/issue-nestjs-graphqlcli-suffix

### Steps to reproduce

```
$ git clone https://github.com/olivierpascal/issue-nestjs-graphqlcli-suffix
$ cd issue-nestjs-graphqlcli-suffix
$ npm run start:dev
```

### Expected behavior

In the `src/schema.gql` file, both `User1` (generated from `user1.model.ts`) and `User2` (generated from `User2Model.ts`) model should contains the `name` field.

But only `User1` is correct.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

9.0.0

### Packages versions

```json
{
  "dependencies": {
    "@apollo/server": "^4.7.0",
    "@nestjs/apollo": "^11.0.5",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^11.0.5",
    "@nestjs/platform-express": "^9.0.0",
    "graphql": "^16.6.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.0",
    "@types/node": "18.15.11",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.5.0",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^4.7.4"
  }
}
```

### Node.js version

16.9.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
isn't this the desired outcome?

![image](https://user-images.githubusercontent.com/13461315/235378413-c72245d2-3275-4287-a6ee-f54f1671750c.png)

**Comment by olivierpascal** [comment]
Damn, my bad! I was so sure I did not double checked that. You are correct, the example works like expected. I have yet to find the minimum reproduction code for my issue. Sorry for bothering.
