### ISSUE TITLE
Module distance calculation bug

### ISSUE THREAD

**Issue by matt1097** [nestjs/nest#11586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have created a minimum reproduction project that has a fairly simple module tree.

AppModule -> Module2
AppModule -> Module1
Module2 -> Module1

Each module has only a constructor and OnModuleInit in a single provider.
I put a console.log in each constructor and each OnModuleInit to guage execution order.

Module1 has an `isInited` flag that I can also print to see if its OnModule Init has completed.

What ends up happening is Module2's OnModuleInit ends up running before its dependency is ready.

### Minimum reproduction code

https://github.com/matt1097/nest-distance-bug

### Steps to reproduce

1. npm ci
2. npm run start
3. Observe console.log prints and print that M1Service initialized is false
4.  Make the proposed fix to scanner.js
5. Re run program and see that M1Service initialized is now true

### Expected behavior

M1Service should always be initialized before M2Service.

I traced the bug back to this line: https://github.com/nestjs/nest/blob/master/packages/core/scanner.ts#L368 which is where the distance of a module is assigned.
In my output below, you can see that in the 'failure' case one of the module's distance goes from 0 -> 2 -> 1.
So NestJS goes with the shorter path when it should have kept with the longer one.

My proposed fix for that line is to wrap it with an if statement to keep the larger value.
```js
if (distance > importedModuleRef.distance) {
    importedModuleRef.distance = distance;
}
```
With this fix in place, the module keeps its correct 'most distant' path and the initialize order is corrected.

This issue also manifests itself as something I have seen reported a few times: That it appears the order something is listed in the imports matters.
In my min reproduction repo, you can also make the problem seemingly go away by changing the order of the modules in App.module.ts to: `imports: [Module1Module, Module2Module],`.

With the propose fix, order truly doesn't matter.

I have seen this issue and tested the fix on both NestJS core v8.x and 9.x

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.0

### Packages versions

```ini
[System Information]
OS Version     : Windows 10
NodeJS Version : v18.9.0
NPM Version    : 8.19.1 

[Nest CLI]
Nest CLI Version : 9.4.2

[Nest Platform Information]
platform-express version : 9.4.0
schematics version       : 9.1.0
testing version          : 9.4.0
common version           : 9.4.0
core version             : 9.4.0
cli version              : 9.4.2
```

### Node.js version

18.9.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

Program output when broken
```
> npm run start

> distance-bug@0.0.1 start
> nest start

[Nest] 44276  - 05/01/2023, 9:47:36 PM     LOG [NestFactory] Starting Nest application...
$$imported module distance before 0
$$imported module distance after 1
$$imported module distance before 0
$$imported module distance after 2
$$imported module distance before 2
$$imported module distance after 1
M1Service constructor called
[Nest] 44276  - 05/01/2023, 9:47:36 PM     LOG [InstanceLoader] AppModule dependencies initialized +10ms
[Nest] 44276  - 05/01/2023, 9:47:36 PM     LOG [InstanceLoader] Module1Module dependencies initialized +0ms
M2Service constructor called
[Nest] 44276  - 05/01/2023, 9:47:36 PM     LOG [InstanceLoader] Module2Module dependencies initialized +0ms
M2Service onModuleInit called
Is M1Service already inited:  false
M1Service onModuleInit called
[Nest] 44276  - 05/01/2023, 9:47:36 PM     LOG [NestApplication] Nest application successfully started +17ms
```

Program output with proposed fix:
```
> npm run start

> distance-bug@0.0.1 start
> nest start

[Nest] 2652  - 05/01/2023, 9:48:40 PM     LOG [NestFactory] Starting Nest application...
$$imported module distance before 0
$$imported module distance after 1
$$imported module distance before 0
$$imported module distance after 2
$$imported module distance before 2
$$imported module distance after 2
M1Service constructor called
[Nest] 2652  - 05/01/2023, 9:48:40 PM     LOG [InstanceLoader] AppModule dependencies initialized +10ms
[Nest] 2652  - 05/01/2023, 9:48:40 PM     LOG [InstanceLoader] Module1Module dependencies initialized +0ms
M2Service constructor called
[Nest] 2652  - 05/01/2023, 9:48:40 PM     LOG [InstanceLoader] Module2Module dependencies initialized +0ms
M1Service onModuleInit called
M2Service onModuleInit called
Is M1Service already inited:  true
[Nest] 2652  - 05/01/2023, 9:48:40 PM     LOG [NestApplication] Nest application successfully started +16ms
```

**Comment by jmcdo29** [comment]
Your repository is private

**Comment by matt1097** [comment]
I apologize, it should be public now.

**Comment by ProductOfAmerica** [comment]
Change `imports: [Module2Module, Module1Module],` to `imports: [Module1Module, Module2Module],`. `Is M1Service already inited:  true`.

**Comment by matt1097** [comment]
@ProductOfAmerica I am aware of that _work around_. I mention it in my writeup above.
The order does not need to matter, and the developers have mentioned before that order should not matter, like here: https://github.com/nestjs/nest/issues/380#issuecomment-362916550
