### ISSUE TITLE
Customize the way the ws adapter looks for message handler

### ISSUE THREAD

**Issue by CodyTseng** [nestjs/nest#11584]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Recently, I wrote a nostr relay based on the [nostr protocol](https://github.com/nostr-protocol/nips), which is a WebSocket service (https://github.com/CodyTseng/nostr-relay-nestjs). The message format of the nostr protocol is `["type", ...]`, while the ws-adaptor can only handle message in the format of `{ "event": "type", ... }`. Therefore, I inherited the ws-adaptor and modified its method of finding for message handler. However, this means that the entire project's WebSocket requests must comply with the nostr protocol. Therefore, I would like to have a way to allow the adaptor to use a different method of finding for message handler for different gateways.

### Describe the solution you'd like

I think it could be possible to allow developers to customize the method for finding for message handler on the Gateway. Developer can add a method

```
findMessageHandler(message: any, handlers: MessageMappingProperties[]): MessageMappingProperties
```

to the Gateway. Then, in the ws-adaptor, we can prioritize using this method to finding for message handler.

### Teachability, documentation, adoption, migration strategy

We can customize the method for finding for message handler like this:

```
@WebSocketGateway()
export class ServerGateway implements FindMessageHandler {
  findMessageHandler(message: any, handlers: MessageMappingProperties[]) {
    // custom routing method
    return handlers.find(handler => handler.message === message[0]);
  }

  @SubscribeMessage('push')
  onPush(client, data) {
    return {
      event: 'pop',
      data,
    };
  }
}
```

### What is the motivation / use case for changing the behavior?

To handle different formats of WebSocket message in the same project.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
