### ISSUE TITLE
Nest can't resolve dependencies of the MongooseCoreModule (MongooseConnectionName, ?)

### ISSUE THREAD

**Issue by ursnj** [nestjs/nest#11595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Throwing error woth mongoose

[Nest] 10469  - 05/04/2023, 2:05:32 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the MongooseCoreModule (MongooseConnectionName, ?). Please make sure that the argument ModuleRef at index [1] is available in the MongooseCoreModule context.
Potential solutions:
- Is MongooseCoreModule a valid NestJS module?
- If ModuleRef is a provider, is it part of the current MongooseCoreModule?
- If ModuleRef is exported from a separate @Module, is that module imported within MongooseCoreModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })

Error: Nest can't resolve dependencies of the MongooseCoreModule (MongooseConnectionName, ?). Please make sure that the argument ModuleRef at index [1] is available in the MongooseCoreModule context.
Potential solutions:
- Is MongooseCoreModule a valid NestJS module?
- If ModuleRef is a provider, is it part of the current MongooseCoreModule?
- If ModuleRef is exported from a separate @Module, is that module imported within MongooseCoreModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })
    at Injector.lookupComponentInParentModules (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:247:19)
    at Injector.resolveComponentInstance (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:200:33)
    at resolveParam (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:120:38)
    at async Promise.all (index 1)
    at Injector.resolveConstructorParams (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:135:27)
    at Injector.loadInstance (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:61:13)
    at Injector.loadProvider (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:88:9)
    at /Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 0)
    at InstanceLoader.createInstancesOfProviders (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/instance-loader.js:55:9)

### Minimum reproduction code

NA

### Expected behavior

Server should start smothly

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/mongoose

### NestJS version

9.0.0

### Packages versions

```json
"@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^10.0.1",
    "@nestjs/mongoose": "^9.2.1",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-socket.io": "^7.6.18",
    "@nestjs/websockets": "^7.6.18",
    "bcrypt": "^5.1.0",
    "class-validator": "^0.14.0",
    "lodash": "^4.17.21",
    "json-stringify-safe": "^5.0.1",
    "mongoose": "^6.8.0",
    "mqtt": "^4.3.7",
    "nest-mqtt": "^0.2.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "uuid": "^8.3.2"
```

### Node.js version

16.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

When you do move this to Discord, please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by ricardo-code-yes** [comment]
wha is the solution for this?

**Comment by SergioSuarezDev** [comment]
+1

**Comment by LagSlug** [comment]
The way I resolved this was to just pass the dependency to the dynamic module. I tried resolving it with peer dependencies, but for reasons beyond my understanding that did not work.

**Comment by SergioSuarezDev** [comment]
I think this is a problem with loading dynamic modules... only installing with rpm locally... because if I upload to npm and install it does work...

in my package.json
example:   "@npm/nest-components": "file:../nest-components"

**Comment by titandino** [comment]
@SergioSuarezDev I observed this exact same issue today. Spent hours pulling hair out trying to figure out why the modules wouldn't resolve. When I copy paste the module directly into the service that I am using, it works just fine, but if I use `npm link` to include my library locally, it fails to resolve ModuleRef. When I publish my library to our NPM registry and include it from there, it works just fine.

**Comment by lalithasj** [comment]
Hi,
I have the same problem.
Appreciate any suggestions.

**Comment by mayonfrancis** [comment]
If anyone is running into a similar issue, here's a scenario to check:

- The host app uses @nestjs/* libraries and @nestjs/mongoose.
- Package A also depends on @nestjs/* and @nestjs/mongoose.
- The host app depends on Package A.

Run:
```bash
npm list @nestjs/core
```
…or check any of the `@nestjs/*` packages in the host app.

If you see multiple versions of NestJS packages (i.e., they're not deduplicated), this can cause issues due to how NestJS uses reflection and metadata.

Try making @nestjs/* packages peerDependencies in your internal/shared package and ensure the host app and the package are using compatible versions. Or try matching nestjs versions.

YMMV, but using same version of nestjs has helped in my case.
