### ISSUE TITLE
Possible memory leak when using server side events

### ISSUE THREAD

**Issue by ggagosh** [nestjs/nest#11601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use Server-Sent Events for one of my routes and then push db changes for subscribed users. The functionality works fine, but as soon as the event count is 10k for example, the error appears: 

`(node:43243) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 drain listeners added to [SseStream]. Use emitter.setMaxListeners() to increase limit
`

### Minimum reproduction code

https://gist.github.com/ggagosh/0850fd0100f17e2bc040095a917c0342

### Expected behavior

I suppose should work without any warning

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^9.0.0

### Packages versions

```json
"@nestjs/common": "^9.0.0",
"@nestjs/config": "2.3.1",
"@nestjs/core": "^9.0.0",
"@nestjs/event-emitter": "^1.4.1",
"@nestjs/graphql": "^11.0.5",
"@nestjs/jwt": "10.0.3",
"@nestjs/mongoose": "^9.2.2",
"@nestjs/passport": "9.0.3",
"@nestjs/platform-express": "^9.0.0",
"@nestjs/swagger": "6.3.0",
"@nestjs/terminus": "^9.2.2",
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
What if you remove that `setTimeout` call?

**Comment by ggagosh** [comment]
> What if you remove that `setTimeout` call?

It's do nothing actually, just for show purposes. When subscribing to the route, start pushing values after 1 sec, nothing more.

**Comment by micalevisk** [comment]
then I don't think that that code is enough to reproduce your issue, right? Please share the full code along with the steps to reproduce.

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by ggagosh** [comment]
> then I don't think that that code is enough to reproduce your issue, right? Please share the full code along with the steps to reproduce.
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

[example nest application](https://github.com/ggagosh/sse) you can use to reproduce this behavior. after running the application, use Postman or any other similar application and enter `localhost:3000/sse`, then check the console where the warning appears.

**Comment by jmcdo29** [comment]
Seems like some sort of issue with usd adding `this.once('drain')` [here](https://github.com/nestjs/nest/blob/master/packages/core/router/sse-stream.ts#L119). Interestingly it doesn't happen when using rxjs directly via `interval`

<details>
<summary>Stack Trace</summary>

```
(node:1588817) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [SseStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at SseStream.addListener (node:events:605:10)
    at SseStream.Readable.on (node:internal/streams/readable:875:35)
    at SseStream.once (node:events:649:8)
    at SseStream.writeMessage (/home/jay/Documents/code/help/sse/node_modules/.pnpm/@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0/node_modules/@nestjs/core/router/sse-stream.js:70:18)
    at /home/jay/Documents/code/help/sse/node_modules/.pnpm/@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0/node_modules/@nestjs/core/router/router-response-controller.js:65:80
    at new Promise (<anonymous>)
    at /home/jay/Documents/code/help/sse/node_modules/.pnpm/@nestjs+core@9.0.0_@nestjs+common@9.0.0_@nestjs+platform-express@9.0.0_reflect-metadata@0.1.13_rxjs@7.2.0/node_modules/@nestjs/core/router/router-response-controller.js:65:50
    at /home/jay/Documents/code/help/sse/node_modules/.pnpm/rxjs@7.2.0/node_modules/rxjs/src/internal/operators/debounce.ts:101:21
```

</details>

**Comment by ggagosh** [comment]
Yeah, so strange, it does not happen when returning the Rx operator directly and not using `Subject.next()` 🤔 and also it's not related to the amount of returning data. 

As I debug, for my local machine, after 377 iterations, `this.once('drain', cb);` run, and it happens every iteration after, which I think is the cause of the warning. 

For example, for the nest application I provide, just fill the array with 377 elements and run it.

**Comment by ggagosh** [comment]
As I continue debugging, find out [this comment](https://github.com/nodejs/help/issues/2426#issuecomment-579516522) and think it's related to this. 

I don't know why it does not appear when you use `interval` directly, maybe because of [debounse?](https://github.com/nestjs/nest/blob/85966703ac57a5b263ab5807033f6ac78548c0ef/packages/core/router/router-response-controller.ts#L127)

**Comment by kamilmysliwiec** [comment]
cc @soyuka 🤔

**Comment by azhaochen** [comment]
I have the same issue:
`(node:167175) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [SseStream]. Use emitter.setMaxListeners() to increase limit`

**Comment by Furmanov19** [comment]
@ggagosh could you please provide an example with `interval`?

**Comment by ggagosh** [comment]
> @ggagosh could you please provide an example with `interval`?

Hey, this is the example [branch](https://github.com/ggagosh/sse/tree/with-interval)
  
I take the interval example from NestJS documentation, I just change the interval time to 0, because first I think the warning was caused by the amount of data I try to return.

**Comment by MatheusWoeffel** [comment]
> I have the same issue: `(node:167175) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [SseStream]. Use emitter.setMaxListeners() to increase limit`

I have the same issue, has anyone found some workaround/solution to this problem? In my case, I can reproduce the issue by sending HTTP requests and immediately cancelling them, after a couple of cancelled requests the warning pops up.

**Comment by dgastudio** [comment]
same here

**Comment by lxmfly123** [comment]
> > I have the same issue: `(node:167175) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [SseStream]. Use emitter.setMaxListeners() to increase limit`
> 
> I have the same issue, has anyone found some workaround/solution to this problem? In my case, I can reproduce the issue by sending HTTP requests and immediately cancelling them, after a couple of cancelled requests the warning pops up.

I figured out a solution: Add a listener for disconnect event, which stops the streaming. 

``` typescript
@Sse('stream`)
sse(@Req() req: Request) {
    const stream = /* start your stream */
    req.on('close', ()=>{ stream.destroy() })
}
```

or something like that.

**Comment by lponciolo** [comment]
I've submitted a PR requesting some changes to solve this issue. If you could validate it, I would appreciate it. https://github.com/nestjs/nest/pull/12188

**Comment by soyuka** [comment]
Hi, sorry didn't see that, but it doesn't surprise me that there's a leak as by definition we may never end the stream... You should consider using mercure.rocks for something more bullet proof. I'll take a look at the proposed patch :).

**Comment by lponciolo** [comment]
@soyuka In my case, the problem occurs when, having several gateways that use @SubscribeMessage, a client connects to the websocket, that bindMessageHandlers function also runs several times generating listeners for the same disconnect event, then the warning appears.

The issue at hand appears to be somewhat different from my own situation; I apologize for any confusion. You might find this issue to be more relevant:  https://github.com/nestjs/nest/issues/7249

**Comment by chriskuech** [comment]
@lxmfly123 I (like in the repro) use `Subject` from `rxjs`, which doesn't seem to have anything resembling a `.destroy()` message. Any idea how to update it for the `rxjs` case?

**Comment by Totalus** [comment]
> @lxmfly123 I (like in the repro) use `Subject` from `rxjs`, which doesn't seem to have anything resembling a `.destroy()` message. Any idea how to update it for the `rxjs` case?

I call `subject.complete()`

**Comment by codemile** [comment]
In my case, I can reproduce this by aborting the client connection. Basically, start a SSE stream on the browser and then hit F5 to reload the webpage. This makes the browser disconnect and then the server will show this error.

**Comment by codemile** [comment]
I was able to fix my issue by completing the observable when the request socket is closed.

```
import {Request} from 'express';


@Sse()
see(@Req() req: Request): Observable<any> {
   return new Observable((subscriber) => {
      req.socket.on('close', () => {
          subscriber.complete();
      });
     // do your stream work here
   });
}
```
   
> FYI: `req.on('close')` didn't work for me. Had to use `req.socket.on('close')` instead.

**Comment by soyuka** [comment]
To solve this issue we should just document that developers should end the stream on client socket close. Can someone contribute that at https://github.com/nestjs/docs.nestjs.com/blob/bf400a0c615185a72fd58998526fdfaec19ac5d1/content/techniques/server-sent-events.md?plain=1#L3 ? Thanks!

**Comment by benyaminl** [comment]
@soyuka I quite confused with these warnings (because it also throws to nestjs queue), and quite misleading. The problem is happening when the redis service not on and not working. Will there any notes for this or at least it doesn't cause confusion with the developer with throwing error that redis connection is broken.

**Comment by soyuka** [comment]
Note sure how this related to redis

**Comment by benyaminl** [comment]
> Note sure how this related to redis

With redis it thow same error message and warning when the connection isn't initiated and when using the consumers 
https://docs.nestjs.com/techniques/queues#consumers

I think it's OOT with this, but it produce the same warnings when the redis server is dead, case to missleading, it should throw error instead.

**Comment by joaopcm** [comment]
I'm still having this issue with Redis-based queues

**Comment by zhengjitf** [comment]
> I'm still having this issue with Redis-based queues

@joaopcm  Can you share a minimum reproduction? I'd like to investigate it.
