### ISSUE TITLE
Implement @InjectTreeRepositry for @nestjs/type

### ISSUE THREAD

**Issue by zinzinday** [nestjs/nest#11606]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Typeorm was supported @Tree Entity with TreeRespository for it.
Why we not implement dectorator @InjectTreeReposity

### Describe the solution you'd like

```ts
dataSource.manager.getTreeRepository(Entity)
```

### Teachability, documentation, adoption, migration strategy

https://typeorm.io/tree-entities

### What is the motivation / use case for changing the behavior?

No change

**Comment by micalevisk** [comment]
You didn't elaborate on why we should have in first place, as nestjs itself was not built for typeorm. What are you missing, exactly?

**Comment by micalevisk** [comment]
btw `@InjectRepository()` supports tree entities since `@nestjs/typeorm@9.0.1`

see: https://github.com/nestjs/typeorm/issues/1367
