### ISSUE TITLE
MulterOptions types not complete

### ISSUE THREAD

**Issue by baumerdev** [nestjs/nest#11607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The current MulterOptions interface in [multer-options.interface.ts](https://github.com/nestjs/nest/blob/master/packages/platform-express/multer/interfaces/multer-options.interface.ts) allows only a string for dest

```
export interface MulterOptions {
  dest?: string;
  // ...
}
```

But Multer's disk storage engine in [disk.js](https://github.com/expressjs/multer/blob/master/storage/disk.js#L20) allows either a string or a function with params for request, file and a callback.

```
  if (typeof opts.destination === 'string') {
    mkdirp.sync(opts.destination)
    this.getDestination = function ($0, $1, cb) { cb(null, opts.destination) }
  } else {
    this.getDestination = (opts.destination || getDestination)
  }
```

### Minimum reproduction code

No reproduction, just types

### Expected behavior

The type definition for MulterOptions should be something like

```
import { Request } from "express";
export interface MulterOptions {
  dest?: string| ((req: Request, file: Express.Multer.File, cb: (error: Error | null, destination: string) => void) => void);
  // ...
}
```

With this change you can use both variants without any type errors

```
@UseInterceptors(
  AnyFilesInterceptor({
    dest: "some_path"
  })
)
```

```
@UseInterceptors(
  AnyFilesInterceptor({
    dest: (request, file, cb) => {
      cb(null, "some_path")
    }
  })
)
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

multer

### NestJS version

9.3.9

### Packages versions

```json
{
  "@nestjs/core": "^9.3.9",
  "@nestjs/platform-express": "^9.3.9"
}
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by baumerdev** [comment]
rubiins change should work with a small adjustment, I commented on his pull request. So if he's able to re-submit it, I will defer it to him :)

**Comment by baumerdev** [comment]
@kamilmysliwiec Before it's getting to quiet on this, I opened a PR #11708 that just successfully completed all the checks (that don't need any approval)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11708
