### ISSUE TITLE
`--strict` flag does not work as expected

### ISSUE THREAD

**Issue by minhtaile2712** [nestjs/nest#11603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use this command to scaffold a new project `nest new strict-project --strict`, only 5 options below are toggled on (which is different to the case without `--strict` flag):

```json
{
    "strictNullChecks": true,
    "noImplicitAny": true,
    "strictBindCallApply": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true
}
```

### Minimum reproduction code

https://docs.nestjs.com/first-steps#setup

### Steps to reproduce

1. `nest new project-name`
2. `nest new project-name-strict --strict`
3. Compare `tsconfig.json` in two project and see the differences.

### Expected behavior

 I expected `tsconfig.json` to have option `compilerOptions.strict` set to `true`.

```json
{
    "compilerOptions": {
        "strict": true
    }
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

Nest CLI (`@nestjs/cli`) 9.4.2 

### Node.js version

v18.16.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [x] Linux

**Comment by minhtaile2712** [comment]
I will move this issue to `nest-cli`

**Comment by micalevisk** [comment]
Few free to update the docs to clarify that behavior of `--strict` flag
