### ISSUE TITLE
Hot reloading on file changes in docker not working with nest-cli.json generate library - Window

### ISSUE THREAD

**Issue by codegdo** [nestjs/nest#11615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hot reloading on file changes in docker not working with nest-cli.json - Window

### Minimum reproduction code

n/a

### Steps to reproduce

Create new project with nest-cli

**Create Dockerfile**
--
```
FROM node:alpine as development
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY . .
EXPOSE 5000
```

**Create docker-compose.yaml**
--
```
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev main
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
```

**Edit tsconfig.json**
---
https://stackoverflow.com/questions/75318862/nestjs-doesnt-hot-reload-work-in-inside-docker
```
"watchOptions": {
    "watchFile": "dynamicPriorityPolling",
    "watchDirectory": "dynamicPriorityPolling",
    "excludeDirectories": [
      "**/node_modules",
      "dist"
    ]
  }
```

Start run docker-compose up --build

Update files app.service.ts, Docker will reload in the console

Stop docker running

Run nest g library common

Start run docker-compose up --build again

Update files app.service.ts, Docker STOP reloading in the console

Visual Studio Code Version: 1.78.2
Docker version 23.0.5, build bc4487a
Nest version 9.4.0
Node version v18.12.1
Npm version 8.5.5

### Expected behavior

App should hot reload when updating the files.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.0

### Packages versions

```json
{
  "name": "main",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\" \"libs/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.0",
    "@types/node": "18.15.11",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.5.0",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": ".",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node",
    "roots": [
      "<rootDir>/src/",
      "<rootDir>/libs/"
    ],
    "moduleNameMapper": {
      "^@app/common(|/.*)$": "<rootDir>/libs/common/src/$1"
    }
  }
}
```

### Node.js version

v18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Can you try typescript v4.7

I guess you're using v4.9?

**Comment by codegdo** [comment]
hi micalvisk,

I am using "typescript": "^4.7.4" as nest-cli create new project. 

Have been searching and try all suggestions. not working. The hot reload is stop working when the nest-cli.json added to project.

Windows 10 Pro

Thanks,

**Comment by micalevisk** [comment]
I would like to know the exact version you're using. That range means nothing without some lock file. Please share the version with us. Also, which versions of typescript you've tried?

Run `npm ls typescript`

**Comment by codegdo** [comment]
hi micalevisk,

details:
├─┬ @nestjs/cli@9.4.2
│ ├─┬ fork-ts-checker-webpack-plugin@8.0.0
│ │ └── typescript@4.9.5 deduped
│ └── typescript@4.9.5 deduped
├─┬ @nestjs/schematics@9.1.0
│ └── typescript@4.9.5 deduped
├─┬ @typescript-eslint/eslint-plugin@5.59.5
│ └─┬ tsutils@3.21.0
│   └── typescript@4.9.5 deduped
├─┬ ts-jest@29.0.5
│ └── typescript@4.9.5 deduped
├─┬ ts-loader@9.4.2
│ └── typescript@4.9.5 deduped
├─┬ ts-node@10.9.1
│ └── typescript@4.9.5 deduped
└── typescript@4.9.5

Thanks,

**Comment by codegdo** [comment]
hi micalevisk,

I re-install typescript@^4.7.4 and test again it work as expected.

Thanks.

**Comment by micalevisk** [comment]
thanks

have you tried `typescript@4.7`? I want to see if this is related with the new behavior introduced in `typescript@4.9`

**Comment by codegdo** [comment]
Edit:
After I run install typescript@4.7.4

├─┬ @nestjs/cli@9.4.2
│ ├─┬ fork-ts-checker-webpack-plugin@8.0.0
│ │ └── typescript@4.7.4 deduped
│ └── typescript@4.9.5
├─┬ @nestjs/schematics@9.1.0
│ └── typescript@4.7.4 deduped
├─┬ @typescript-eslint/eslint-plugin@5.59.5
│ └─┬ tsutils@3.21.0
│ └── typescript@4.7.4 deduped
├─┬ ts-jest@29.0.5
│ └── typescript@4.7.4 deduped
├─┬ ts-loader@9.4.2
│ └── typescript@4.7.4 deduped
├─┬ ts-node@10.9.1
│ └── typescript@4.7.4 deduped
└── typescript@4.7.4

re-run docker-compose up --build with nest-cli.json added - the reload **NOT WORKING**

if I remove nest-cli.json - typescript@4.9.5 or 4.7.4 - the reload **WORKING JUST FINE**

Thanks,

**Comment by micalevisk** [comment]
then, for now, you can use 4.9 and with this config in your tsconfig: https://docs.nestjs.com/faq/common-errors#file-change-detected-loops-endlessly

I'm not even sure if this is a bug or a limitation on how 4.9 default config works in Windows 10

**Comment by codegdo** [comment]
hi micalevisk,

Thank you for you help.

Edit: re-install typescript@5.0.4
├─┬ @nestjs/cli@9.4.2
│ ├─┬ fork-ts-checker-webpack-plugin@8.0.0
│ │ └── typescript@5.0.4 deduped
│ └── typescript@4.9.5
├─┬ @nestjs/schematics@9.1.0
│ └── typescript@5.0.4 deduped
├─┬ @typescript-eslint/eslint-plugin@5.59.5
│ └─┬ tsutils@3.21.0
│   └── typescript@5.0.4 deduped
├─┬ ts-jest@29.1.0
│ └── typescript@5.0.4 deduped
├─┬ ts-loader@9.4.2
│ └── typescript@5.0.4 deduped
├─┬ ts-node@10.9.1
│ └── typescript@5.0.4 deduped
└── typescript@5.0.4

Tested Window with added tsconfig.json
```
"watchOptions": {
    "watchFile": "fixedPollingInterval"
  }
```

The reload WORK **without nest-cli.json added**.

The reload has no Issue with MAC OS - with nest-cli.json added.


Thanks,

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
