### ISSUE TITLE
readme_zh one img 404 not found

### ISSUE THREAD

**Issue by zhu-hongwei** [nestjs/nest#11618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[https://github.com/nestjs/nest/blob/master/readme_zh.md](https://github.com/nestjs/nest/blob/master/readme_zh.md)

<img width="1440" alt="image" src="https://github.com/nestjs/nest/assets/61079864/0402fb3a-82de-4ada-8685-523ccbb1153d">

### Minimum reproduction code

none

### Expected behavior

the img show not error

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
let's track this here: #11619
