### ISSUE TITLE
Some circular dependencies are not detected and prevent the server from starting without throwing an error

### ISSUE THREAD

**Issue by yjaaidi** [nestjs/nest#11630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Given the circular dependency below, `await NestFactory.create(AppModule)` never resolves nor rejects with a `CircularDependencyException` or similar.

```ts
class B {}

@Injectable()
class A {
  constructor(b: B) {}
}

@Injectable()
class BImpl {
  constructor(a: A) {}
}

@Controller()
class AppController {
  constructor(a: A) {}
}

await NestFactory.create(AppModule);
```

Right now, the `CircularDependencyException` is only triggered if the circular dependency is an ECMAScript circular dependency where a provider ends up being `undefined` but it doesn't detect when the problem happens during injection.

cc. @seb-mynotary

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-circular-dependency-repro?file=src%2Fmain.ts&terminal=start

### Expected behavior

Circular dependencies should be detected and throw a `CircularDependencyException` error.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.0

### Packages versions

```json
{
  "@nestjs/common": "9.4.0",
  "@nestjs/core": "9.4.0",
  "@nestjs/platform-express": "9.4.0"
}
```

### Node.js version

20.1.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I tested your repro with `@nestjs/core` v9.0.11, v9.2.1 and v9.3.0 as well and I got the same behavior on all of them. Thanks for reporting this. I'll investigate this further ASAP.

![image](https://github.com/nestjs/nest/assets/13461315/55eb66a5-e6d3-4845-bb06-9124977af1cb)

**Comment by yjaaidi** [comment]
Cool! Thanks @micalevisk!
Let me know if I can help by any way.

IMO, the container must somehow track an injectable's state and flag it as "pending" so we can detect the circular dependency.

**Comment by micalevisk** [comment]
https://github.com/nestjs/nest/blob/d352e6f138bc70ff33cccf830053946d17272b82/packages/core/injector/instance-loader.ts#L69-L78

the promise on L72 didn´t resolved/rejected for the second call of `createInstancesOfProviders` (ie, when `moduleRef` is `AppModule`). I'm still trying to understand why is this

**Comment by CodyTseng** [comment]
If each provider is placed in a different file, a `CircularDependencyException` error will be throwed. I guess NestJS discovers circular dependencies through NodeJS module loader.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12020
