### ISSUE TITLE
[microservices][Kafka] Empty postfixId not working for ClientKafka

### ISSUE THREAD

**Issue by quaos** [nestjs/nest#11647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Referring to #9677

on the Client side of `microservices` module, providing `postfixId` options as  empty string still results in `-client` postfix after the client ID and consumer group ID.

I found this related line:
https://github.com/nestjs/nest/commit/d88b920dba0b2b82188c242b666f361015c9c9da#diff-dfaf9025d840c609351b76ce88dbb871cd6b9aca0d552185db8a0cccd28324beR100

### Minimum reproduction code

https://codesandbox.io/p/sandbox/test-nest-microservices-client-postfixid-ssmgcw?welcome=true

### Expected behavior

Should be able to provide the `ClientKafka` without default postfix of `-client` in `clientId` and `groupId`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.1

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^9.4.1",
    "@nestjs/config": "^2.3.2",
    "@nestjs/core": "^9.4.1",
    "@nestjs/microservices": "9.4.1",
    "@nestjs/platform-express": "^9.4.1",
    "kafkajs": "^2.2.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "run-script-webpack-plugin": "0.0.11",
    "rxjs": "^7.4.0",
    "webpack": "5.70.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.1.3",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^29.0.0",
    "@types/node": "^16.11.1",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.29.2",
    "@typescript-eslint/parser": "^4.29.2",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.1",
    "jest": "^29.0.0",
    "prettier": "^2.4.1",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.6",
    "ts-jest": "^29.0.0",
    "ts-loader": "^9.2.6",
    "ts-node": "^10.3.0",
    "tsconfig-paths": "^3.11.0",
    "typescript": "^4.4.4"
  }
}
```

### Node.js version

v16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
This is going to change in v10 https://github.com/nestjs/nest/pull/10549
