### ISSUE TITLE
Adding Transactional Annotation to NestJS 

### ISSUE THREAD

**Issue by luc-boussantr-lp** [nestjs/nest#11658]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, managing transactions involving multiple services in NestJS can be a complex and time-consuming task. The process of creating and passing around the entityManager can add clutter to the codebase and make it harder to maintain. 

### Describe the solution you'd like

It would be highly beneficial to have a transaction annotation that allows developers to create SQL transactions easily and automatically rollback the transaction if an error is thrown within the annotated code block. Something that could resemble what Spring Boot does with the Transactional annotation : https://www.baeldung.com/transaction-configuration-with-jpa-and-spring#the-transactional-annotation.

### Teachability, documentation, adoption, migration strategy

The proposed transaction annotation should provide a convenient way to define a transactional context in NestJS, ensuring that any database operations performed within the annotated code block are executed within a transaction. If an error occurs during the execution, the transaction should be automatically rolled back, preserving data consistency.

```typescript
@Controller('example')
export class ExampleController {
  @Post('/back-fill')
  @Transaction()
  async performTransactionalOperation(): Promise<void> {
    // Database operations within this method will be executed within a transaction.
    // If any error occurs, the transaction will be automatically rolled back.
   const answer = await this.firstService.performTransactionalOperation();
   await this.externalApi.callApi(answer);
   await this.otherService.performOtherTransactionalOperation();
  }
}
```

### What is the motivation / use case for changing the behavior?

Currently, I have an API endpoint that creates multiple entities (User, Companies,...) and calls multiple external APIs. However, it happens that an unknown error occurs while this endpoint is called and I would want to rollback all of my changes to my database. 
Since there are multiple services involved, I don't want to use the entityManager because it would have to be passed around everywhere.

**Comment by micalevisk** [comment]
`@Transaction()` is too broader to me

I mean, we can build any kind of nodejs app with Nest, each one would have their own meaning for the word "transaction"

also, if we take typeorm as an ORM, they even remove their decorator abstraction because _"These decorators do the things out of the TypeORM scope"_

I'm not sure if this fits well in Nest scope neither :thinking:

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
