### ISSUE TITLE
Nestjs environment variables 

### ISSUE THREAD

**Issue by OlojaMuyiwa** [nestjs/nest#11659]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

i’m trying to deploy nestjs on a linux server with nginx as a reverse proxy. and i want nestjs to read the port environment variables from the system environment variables. how do i do that. 

### Describe the solution you'd like

nil 

### Teachability, documentation, adoption, migration strategy

nil 

### What is the motivation / use case for changing the behavior?

nil

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by OlojaMuyiwa** [comment]
i’ve done that no response @jmcdo29

**Comment by jmcdo29** [comment]
![image](https://github.com/nestjs/nest/assets/28268680/f5159b58-cfa5-4062-a752-640d54265517)

Mhmm, no response huh?

**Comment by OlojaMuyiwa** [comment]
oh sorry💀
