### ISSUE TITLE
throw built-in exceptions from HttpService

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest#11652]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

when HttpService returns a 4xx error without catching and rethrow, it would be treated as a 500 error.

### Describe the solution you'd like

throw built-in exceptions with corresponding status code

### Teachability, documentation, adoption, migration strategy

none

### What is the motivation / use case for changing the behavior?

avoid writing exception wrappers.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
