### ISSUE TITLE
perf: inject and make ngModule optional

### ISSUE THREAD

**Issue by jon9090** [nestjs/nest#11651]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

latest

Angular makes ngModule optional because they understand it is not necessary. Also, make the inject function an alternative to inject in ctor. 

Because nestjs is inspired by angular, can nestjs have those same ideas? to keep up with angular changes?

**Comment by micalevisk** [comment]
> inject function an alternative to inject in ctor.

see https://github.com/nestjs/nest/issues/10586#issuecomment-1324707932

**Comment by micalevisk** [comment]
I'm not familiar with Angular

What do you mean by _ngModule optional_ part? and how this relates with nestjs apps? an example on what do you want to achieve would be great.

**Comment by kamilmysliwiec** [comment]
Angular != NestJS
