### ISSUE TITLE
ability to retry on HttpService

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest#11653]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

none

### Describe the solution you'd like

integrate with [axios-retry](https://github.com/softonic/axios-retry)? idk.
and config via HttpModule.register

### Teachability, documentation, adoption, migration strategy

none

### What is the motivation / use case for changing the behavior?

avoid hacking solutions

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
