### ISSUE TITLE
 Cannot find module 'wrap-ansi'

### ISSUE THREAD

**Issue by dyonathakramer** [nestjs/nest#11660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i start the app with nest start:

![image](https://github.com/nestjs/nest/assets/113115617/1ef05698-0f8a-4cb6-999a-8f65241e3f59)

Already tried to change to nest/cli 9.5.0 and node 18, but the same...

### Minimum reproduction code

https://github.com/private/code-company

### Expected behavior

Well, would be nice to see it starting.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.5

### Packages versions

```json
{
  "name": "cron-jobs",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\"",
    "lint:fix": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:changed": "jest -o",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/axios": "2.0.0",
    "@nestjs/bull": "0.6.3",
    "@nestjs/common": "9.1.6",
    "@nestjs/config": "2.2.0",
    "@nestjs/core": "9.1.6",
    "@nestjs/jwt": "9.0.0",
    "@nestjs/mapped-types": "1.2.2",
    "@nestjs/microservices": "9.2.0",
    "@nestjs/mongoose": "9.2.2",
    "@nestjs/passport": "9.0.0",
    "@nestjs/platform-express": "9.1.4",
    "@nestjs/schedule": "2.2.2",
    "@nestjs/swagger": "6.1.2",
    "@nestjs/typeorm": "9.0.1",
    "aws-sdk": "2.1230.0",
    "axios": "1.4.0",
    "bottleneck": "2.19.5",
    "bull": "4.10.0",
    "cache-manager": "4.1.0",
    "cache-manager-ioredis": "2.1.0",
    "class-transformer": "0.5.1",
    "class-validator": "0.14.0",
    "date-fns": "2.29.3",
    "dayjs": "1.11.7",
    "discord-ts-webhook": "1.2.1",
    "express-basic-auth": "1.2.1",
    "kafkajs": "2.2.4",
    "form-data": "4.0.0",
    "lodash": "4.17.21",
    "mongoose": "7.2.0",
    "multer": "2.0.0-rc.4",
    "nestjs-i18n": "~10.2.6",
    "passport": "0.6.0",
    "passport-jwt": "4.0.1",
    "pdfkit": "0.13.0",
    "pg": "8.11.0",
    "redis": "4.3.1",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.5.7",
    "shallow-equal-object": "1.1.1",
    "typeorm": "0.3.16"
  },
  "devDependencies": {
    "@nestjs/cli": "9.1.5",
    "@nestjs/schematics": "9.0.3",
    "@nestjs/testing": "9.1.6",
    "@types/cron": "2.0.1",
    "@types/express": "4.17.17",
    "@types/jest": "29.5.1",
    "@types/cache-manager": "4.0.2",
    "@types/lodash": "4.14.194",
    "@types/multer": "1.4.7",
    "@types/node": "18.15.11",
    "@types/passport-jwt": "3.0.8",
    "@types/pdfkit": "0.12.9",
    "@types/supertest": "2.0.12",
    "@types/uuid": "9.0.1",
    "@typescript-eslint/eslint-plugin": "5.59.1",
    "@typescript-eslint/parser": "5.59.1",
    "eslint": "8.39.0",
    "eslint-config-prettier": "8.8.0",
    "eslint-plugin-prettier": "4.2.1",
    "jest": "29.5.0",
    "prettier": "2.8.8",
    "source-map-support": "0.5.21",
    "supertest": "6.3.3",
    "ts-jest": "29.1.0",
    "ts-loader": "9.4.2",
    "ts-node": "10.9.1",
    "tsconfig-paths": "4.2.0",
    "typescript": "5.0.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node",
    "moduleNameMapper": {
      "^src/(.*)$": "<rootDir>/$1"
    }
  }
}

```

### Node.js version

20.0.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
hard to tell without some repro, I guess? I've using the latest version just fine on Linux (node 18)

can you need to tell us at least when did this error start happening?

**Comment by dmitriybo** [comment]
The thing is that if there is a dependency in the project that uses the glob package, then a conflict may arise. It requires the jackspeak package, which in turn uses the @isaacs/cliui package, which recently upgraded to 8.0.2 and started using wrap-ansi@8.1.0. The glob package is a dependency of many other packages, such as graphql-ws (which @nest/graphql needs).
Therefore, it is required to update the inquirer package to the latest version. This is part of issue #1313.
As a temporary solution, you can write in package.json:
```
"resolutions": {
  "wrap-ansi": "7.0.0",
  "string-width": "4.1.0"
}

**Comment by jmcdo29** [comment]
See. All that above, **that's why** we all for reproductions.

**Comment by dmitriybo** [comment]
Pretty strange behavior of yarn (using the latest version 1.22.19):

`npm i -g @nestjs/cli`
`nest new project-name` (select yarn)

Next, I install packages that have wrap-ansi in the dependency tree, while installing them individually:
`yarn add rimraf`
`yarn add glob`
An error occurs.
```
const wrapAnsi = require('wrap-ansi');
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\user\WebstormProjects\untitled\node_modules\wrap-ansi\index.js from C:\Users\user\project\node_modules\inquirer\lib\utils\screen-manager.js not supported. 
Instead change the require of index.js in C:\Users\user\project\node_modules\inquirer\lib\utils\screen-manager.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\user\project\node_modules\inquirer\lib\utils\screen-manager.js:4:18)
```
But if you delete the node_modules folder and reinstall the packages, then everything is fine.

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be related specifically to NestJS.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
