### ISSUE TITLE
Durable providers are unable to recover from errors being thrown

### ISSUE THREAD

**Issue by KamalAman** [nestjs/nest#11664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using  Durable Providers https://docs.nestjs.com/fundamentals/injection-scopes#durable-providers. When a Service is marked as durable but throws an error for whatever reason for a given context ID, the error sticks **forever** until service restarts. 

Is there any way to delete the context / not cache the context if an error is thrown? 

### Minimum reproduction code

https://github.com/nestjs/nest/blob/master/integration/scopes/src/durable/durable.service.ts

### Steps to reproduce

Follow the integration steps for a durable provider, and have the provider throw an error on the initial request for a context id. All subsequent requests will still throw the same error **forever**

### Expected behavior

Durable providers should not be cached if they throw an error

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.2

### Packages versions

```json
```

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KamalAman** [comment]
@micalevisk here is the reproduction https://github.com/KamalAman/nestjs-issue-11664

The issue is if the construction of the class durable service throws, this is especially an issue with factories.

**Comment by micalevisk** [comment]
would you like to create a PR to address that?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11666

**Comment by dberardo-com** [comment]
is this still an issue ?
