### ISSUE TITLE
onModuleInit() not called in correct order

### ISSUE THREAD

**Issue by amadeusjposchmann** [nestjs/nest#11672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

A module may be initialized before its dependencies are initialized.

Suspected culprit is the skip condition at https://github.com/nestjs/nest/blob/5bba7e9d264319490f142ca5e8099c559fa7e7e3/packages/core/scanner.ts#L360

IMHO, the `|| modulesStack.includes(moduleRef)` has to be removed. A moduleRef may not be skipped if it has been visited before, because it may have entered the recursive function with a different(higher) value for `distance` than during its last evaluation.

### Minimum reproduction code

https://github.com/amadeusjposchmann/nestDistanceExample

### Steps to reproduce

1. `npm ci`
2. `npm run start`

### Expected behavior

YSerivce's onModuleInit() should be called before XService's onModuleInit() is called.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.2

### Packages versions

```json
9.4.2
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

Consider a module A, depending on X, depending on Y.

Your root/application module depends on modules X and A, giving you these chains:

1) R->X->Y
2) R->A->X->Y

Evaluating the first chain, the scanner assigns distances X:1, Y:2 .
Evalutaing the second chain, the scanner updates to A:1, X:2, Y:2 .
X and Y end up with the same distances, despite X depending on Y, because the scanner skips the second X->Y reference. They may even end up in reverse order, if there would be another module inbetween ( i.e. A->B->C->X->Y )

For testing purposes, we've removed the suspect culprit condition in a testing setup and it's working as expected in our project where the issue surfaced. Will create a PR as proposal.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11674

**Comment by amadeusjposchmann** [comment]
Could someone please re-open this ticket? As discussed in the PR, the proposed fix is not feasible, but the problem persists and the minimal example still holds.
