### ISSUE TITLE
Multiple microservice clients responses to single request with Redis transport.

### ISSUE THREAD

**Issue by SeungsuKim** [nestjs/nest#11687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using `@nestjs/microservices`, an application sends a request by `send()` method of `ClientProxy` instance, which is using Redis as a transport. There are two microservices which is a client of the request.

I expect only one of the clients get the request and responses.

### Minimum reproduction code

It needs multiple microservices to reproduce.

### Expected behavior

Both clients get the request and handle it.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```
microservices version    : 9.2.1
common version           : 9.3.10
core version             : 9.3.10
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
