### ISSUE TITLE
NestReplyPartitionAssigner does not reassign partitions when a group member leaves

### ISSUE THREAD

**Issue by OleksandrZaturskyi** [nestjs/nest#11688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If a topic has only one partition and two consumers in group (this situation can appear during deployment in kubernetes), when the consumer who owns the reply partitions dies, the partitions are not reassigned to the second consumer

### Minimum reproduction code

https://github.com/OleksandrZaturskyi/kafka-reply-partition-assign/commit/ed712ecd324e121a31d13504c2d47fd5e570339a

### Steps to reproduce

1. setup kafka with broker available on `localhost:9092`
2. `npm run build`
3. start first consumer `PORT=3000 npm run start`
4. wait until first consumer joins group 
![image](https://github.com/nestjs/nest/assets/41697979/a2444a97-0550-4f5e-8642-030ce8f04e25)
5. start second consumer `PORT=3001 npm run start`
6. wait until second consumer joins group 
![image](https://github.com/nestjs/nest/assets/41697979/2e57edfb-5c76-4093-8ffd-62b120809eb5)
7. kill first consumer(`ctrl + c`)
8. note that the second consumer cannot join a group and stops with `Crash: Error: value should be an instance of Encoder` after several attempts
![image](https://github.com/nestjs/nest/assets/41697979/8e3600bb-38b0-45df-9e63-fa34170c6f38)
![image](https://github.com/nestjs/nest/assets/41697979/4f1c5eec-6ca6-441e-82fc-a54145e498cc)
![image](https://github.com/nestjs/nest/assets/41697979/814a87f3-a869-4b81-bb6d-39919bf36070)

### Expected behavior

partitions connected to the second consumer, how the Sticky Assignor should behave https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/StickyAssignor.html

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.2

### Packages versions

```
[System Information]
OS Version     : macOS Unknown
NodeJS Version : v16.17.0
NPM Version    : 9.5.1 

[Nest CLI]
Nest CLI Version : 9.5.0 

[Nest Platform Information]
platform-express version : 9.4.2
microservices version    : 9.4.2
schematics version       : 9.2.0
testing version          : 9.4.2
common version           : 9.4.2
core version             : 9.4.2
cli version              : 9.5.0

```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

assumed fix: https://github.com/OleksandrZaturskyi/kafka-reply-partition-assign/commit/e1f4e94fb012e9438750d1ef540a3beb38960869

**Comment by kamilmysliwiec** [comment]
Thanks for reporting this issue! Let's track it here https://github.com/nestjs/nest/pull/11692
