### ISSUE TITLE
Failed to connect to websocket using wss

### ISSUE THREAD

**Issue by Tyh2001** [nestjs/nest#11682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/nestjs/nest/issues/11681

<img width="679" alt="2939de67c12cc1c0583e3435f90c51c" src="https://github.com/nestjs/nest/assets/73180970/d8c7e457-d08e-4970-a80a-d5cb7cbdb89b">

Oh, that won't solve the problem at all. This is too bad. I don't have a say, it's too slow to solve the problem like this.

No one is speaking or asking questions inside, right? The most recent one was active a year ago and did not have the authority to speak.

<img width="580" alt="21293b5fe9a70b0dd1321aff56f5e2a" src="https://github.com/nestjs/nest/assets/73180970/4c50f2a1-c9cf-49ec-84fb-4c9ca142794b">

@kamilmysliwiec

### Minimum reproduction code

-

### Steps to reproduce

-

### Expected behavior

-

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.0

### Packages versions

```json
-
```

### Node.js version

18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
This isn't a bug but rather an issue in your code/setup. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
