### ISSUE TITLE
Unable to resolve signature of parameter decorator when called as an expression.

### ISSUE THREAD

**Issue by s97712** [nestjs/nest#11683]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8.5.1

### Describe the regression

TypeScript 5.0 makes type-checking more accurate for decorators under --experimentalDecorators. One place where this becomes apparent is when using a decorator on a constructor parameter.

```ts
@Controller('app')
export class AppController {
  constructor(
    @Inject(REQUEST) private request: Request
  ) {}
}
```
This will get error:
```
Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.
```

This call will fail because key expects a string | symbol, but constructor parameters receive a key of undefined. Change the signature of 'inject' can resolve the error。

```diff
- export declare function Inject<T = any>(token?: T): (target: object, key: string | symbol, index?: number) => void;
+ export declare function Inject<T = any>(token?: T): (target: object, key?: string | symbol, index?: number) => void;
```

### Input code

```ts

```

### Expected behavior

Not errors.

**Comment by kamilmysliwiec** [comment]
This has been already fixed https://github.com/nestjs/nest/blob/d92a64e7e23a10920ef7d6b5e0916359463fdd3b/packages/common/decorators/core/inject.decorator.ts#L37-L38
