### ISSUE TITLE
Example of storing images with Mongoose and Nest.js

### ISSUE THREAD

**Issue by ArneTesch** [nestjs/nest#1169]
Can I find somewhere an example of storing images with Mongoose and Nest.js, using the File Upload interceptor?

Thanks!

**Comment by quen2404** [comment]
Hello @ArneTesch ! You should use stackoverflow for that kind of question. I already do this with Nest, you have to use [MulterModule](https://docs.nestjs.com/techniques/file-upload) & [MongooseModule](https://docs.nestjs.com/techniques/mongodb). 

You can inject the Mongoose Connection using the `@InjectConnection()` decorator.
This is not documented currently, i already made a [pull request](https://github.com/nestjs/docs.nestjs.com/pull/173) about this .

Then you can use any gridfs library, i made this one: [mongo-gridfs](https://www.npmjs.com/package/mongo-gridfs), and use it in a service :
```typescript
@Injectable()
export class FilesService {
  private fileModel: MongoGridFS;

  constructor(@InjectConnection() private readonly connection: Connection) {
    this.fileModel = new MongoGridFS(this.connection.db, 'images');
  }

  async readStream(id: string): Promise<GridFSBucketReadStream> {
    return this.fileModel.readFileStream(id);
  }

  async writeStream(stream, options?: IGridFSWriteOption): Promise<FileInfo> {
    return await this.fileModel
      .writeFileStream(stream, options)
      .then(FilesService.convertToFileInfo);
  }

  async findInfo(id: Types.ObjectId): Promise<FileInfo> {
    return await this.fileModel
      .findById(id.toHexString())
      .then(FilesService.convertToFileInfo);
  }

  public async writeFile(
    file: DiskFile,
    metadata?: Metadata,
  ): Promise<FileInfo> {
    return await this.fileModel
      .uploadFile(
        file.path,
        {
          filename: file.originalname,
          contentType: file.mimetype,
          metadata,
        },
        true,
      )
      .then(FilesService.convertToFileInfo);
  }


 // ...
}
```

And in your controller :

```typescript
  @Post()
  @UseInterceptors(FileInterceptor('file'))
  async uploadFile(
    @UploadedFile() file: DiskFile,
  ): Promise<Image> {
    const createdFile = await this.filesService.writeFile(file, metadata);

  }

```

**Comment by ArneTesch** [comment]
Hello @quen2404,

Thanks for the help! Really appreciate this.

How can I use the @InjectConnection decorator?
I guess this not standard included in Nest.js?

Thanks!

**Comment by quen2404** [comment]
This decorator is provided by the [MongooseModule](https://docs.nestjs.com/techniques/mongodb) like `@InjectModel()` . So you only have to add it to depencencies: 
```bash
npm install --save @nestjs/mongoose mongoose
```

**Comment by ArneTesch** [comment]
Can you show me an example of your DiskFile interface?

When testing with Postman, how should the form-data looks like?

**Comment by quen2404** [comment]
DiskFile is an interface which match this : https://github.com/expressjs/multer#api
Here is a postman example: 
![image](https://user-images.githubusercontent.com/5547492/46614220-8e7b5800-cb15-11e8-8bc0-0f88d48c7cbe.png)
Don't forget to declare & configure your MulterModule in your AppModule

**Comment by ArneTesch** [comment]
Hi,

The error is caused because the file.path value is undefined.
I am very new with Mongo and Node.js, so I haven't experience with Multer and the configuration of it. I guess I am missing something in the configuration.

I just configured it like this:
    MulterModule.registerAsync({
        useFactory: () => ({
        dest: '/upload',
    }),
And this is the error:
![image](https://user-images.githubusercontent.com/7737520/46672618-35282d00-cbd8-11e8-9f37-1941553c7d8b.png)

**Comment by quen2404** [comment]
File not found is an exception raised by `mongo-grifs` if there is no file at the given path. 
Verify the value of your `file.path` variable. and check on your disk if the file exists.
I don't use Async mode to configure MulterModule, just this:
```typescript
MulterModule.register({
  dest: '/tmp/upload',
})
```

**Comment by kamilmysliwiec** [comment]
Please, use StackOverflow for such questions.
