### ISSUE TITLE
Durable provider

### ISSUE THREAD

**Issue by jayzernguyenstarack** [nestjs/nest#11699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently I'm testing on the Durable Provider to get tenantId from request scope in order to avoid open to many connection to database in each request. This is the code from NestJS docs:

```
import {
  HostComponentInfo,
  ContextId,
  ContextIdFactory,
  ContextIdStrategy,
} from '@nestjs/core';
import { Request } from 'express';

const tenants = new Map<string, ContextId>();

export class AggregateByTenantContextIdStrategy implements ContextIdStrategy {
  attach(contextId: ContextId, request: Request) {
    const tenantId = request.headers['x-tenant-id'] as string;
    console.log(request);

    let tenantSubTreeId: ContextId;

    if (tenants.has(tenantId)) {
      tenantSubTreeId = tenants.get(tenantId);
    } else {
      tenantSubTreeId = ContextIdFactory.create();
      tenants.set(tenantId, tenantSubTreeId);
    }

    return {
      resolve: (info: HostComponentInfo) =>
        info.isTreeDurable ? tenantSubTreeId : contextId,
      payload: { tenantId },
    };
  }
}
```

This will take the `x-tenant-id` from request header. However, I want to retrieve the `tenantId` from the data inside the context between microservices as well. I tried to use `ExecutionContext` and `Inject(CONTEXT)` but none of them worked. How can we achieve this within microservices system?

### Minimum reproduction code

Not available

### Expected behavior

I expect it will be able to retrieve `tenantId` from microservices as well instead of request only

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json

```

### Node.js version

16.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
