### ISSUE TITLE
ESLint warnings only in projects generated with pnpm and not other package managers

### ISSUE THREAD

**Issue by slyofzero** [nestjs/nest#11707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When initializing a project using the nest-cli and choosing pnpm as the package manager, I get ESLint warnings because of the `no-unused-vars` rule in all of the app module, controller, and service files generated. This warning should only appeared for unused variables, functions, or classes that were defined but never called back again in the file and should not appear on exported items but in this case they are appearing for decorators and exported items.

### pnpm
![image](https://github.com/nestjs/nest/assets/71858966/59a1984a-873e-4bed-9d39-deb9a7d87388)

### Minimum reproduction code

https://github.com/slyofzero/nestjs-pnpm-issue

### Steps to reproduce

1. git clone https://github.com/slyofzero/nestjs-pnpm-issue
2. pnpm install
3. Open the project using VSCode
4. Open any of the default module, controller, or service files

### Expected behavior

This is something that isn't happening when the project is generated using`yarn` as the package manager in the cli.
### yarn
![image](https://github.com/nestjs/nest/assets/71858966/4343e694-2f84-4c55-abf3-41d1eea84984)

I have checked both `package.json` and `.eslintrc.js` for both the projects and they are identical, same ESLint rules apply on both and same versions of ESLint. Interestingly if we remove `node_modules` from the yarn project and do `pnpm install` to get all the packages the issue in the pnpm project doesn't happen.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

eslint

### NestJS version

9

### Packages versions

```json
{
  "name": "backend-pnpm",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.1",
    "@types/node": "18.16.12",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.5.0",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.1.0",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^5.0.0"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
everything went fine here

also, that does seems to be related with nestjs. Instead of relying on your editor, run `pnpm lint`
