### ISSUE TITLE
Dev tool integration bug snapshot is not taking

### ISSUE THREAD

**Issue by armaansharma786** [nestjs/nest#11701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We are trying to integrate dev tools with our project,
 as in the documentation it is written that in the main.ts file

NestFactory.create() Here we need to pass an object with a key snapshot: true, 

when I am doing this my code is not get compiled, it is giving error snapshot property does not exist 

    "@nestjs/core": "^9.4.2",
    
    this is the package version
    
        const app = await NestFactory.create(AppModule, {
      snapshot: true,
    });

this is what i am doing

please see why it is not taking snapshot 

### Minimum reproduction code

dont know its a public issue

### Expected behavior

as per documentation, it should take snapshot key while creating app in main.ts file

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9

### Packages versions

```json

```
  "@nestjs-modules/json-service": "^0.2.2",
    "@nestjs-modules/nestjs-dyn-logger": "^1.6.3",
    "@nestjs/axios": "^1.0.0",
    "@nestjs/bull": "^0.6.2",
    "@nestjs/common": "^9.2.1",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.4.2",
    "@nestjs/devtools-integration": "^0.1.4",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.2.1",
    "@nestjs/swagger": "^6.1.3",

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

nope

**Comment by micalevisk** [comment]
What is the output of `npx nest info`?

**Comment by armaansharma786** [comment]
src/main.ts:59:7 - error TS2769: No overload matches this call.
inst-backend_1  |   Overload 1 of 2, '(module: any, options?: NestApplicationOptions): Promise<INestApplication>', gave the following error.
inst-backend_1  |     Argument of type '{ snapshot: boolean; }' is not assignable to parameter of type 'NestApplicationOptions'.
inst-backend_1  |       Object literal may only specify known properties, and 'snapshot' does not exist in type 'NestApplicationOptions'.
inst-backend_1  |   Overload 2 of 2, '(module: any, httpAdapter: AbstractHttpAdapter<any, any, any>, options?: NestApplicationOptions): Promise<INestApplication>', gave the following error.
inst-backend_1  |     Argument of type '{ snapshot: boolean; }' is not assignable to parameter of type 'AbstractHttpAdapter<any, any, any>'.
inst-backend_1  |       Object literal may only specify known properties, and 'snapshot' does not exist in type 'AbstractHttpAdapter<any, any, any>'.
inst-backend_1  | 
inst-backend_1  | 59       snapshot: true,
inst-backend_1  |          ~~~~~~~~~~~~~~

**Comment by micalevisk** [comment]
looks like your `@nestjs/core` is not v9.4.2 as you're thinking

that's not a bug but a setup issue. Share some repro or the output of `nest info` next time, please.

**Comment by armaansharma786** [comment]
![Screenshot from 2023-06-09 11-39-15](https://github.com/nestjs/nest/assets/47622136/b8f448ee-2a41-4afa-9683-6104fe59d01f)
Please help here, core is already upto date

**Comment by armaansharma786** [comment]
@micalevisk

**Comment by kamilmysliwiec** [comment]
Make sure to update `@nestjs/common` as well
