### ISSUE TITLE
How to use async function with nestKafka to partitioning partition.

### ISSUE THREAD

**Issue by ArahnakaArm** [nestjs/nest#11700]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I need a soulution that ClientsModule.registerAsync can use kafka createPartitioner with async function

### Describe the solution you'd like

I would like to ClientsModule.registerAsync to createPartitioner with async function .
<img width="621" alt="Screenshot 2566-06-06 at 14 11 53" src="https://github.com/nestjs/nest/assets/38695975/be4798d6-c431-4ae1-868c-f47476064623">

<img width="658" alt="Screenshot 2566-06-06 at 14 10 57" src="https://github.com/nestjs/nest/assets/38695975/5fd89aad-f669-446d-8f10-145107b2337e">

### Teachability, documentation, adoption, migration strategy

Here's is a document 
https://docs.nestjs.com/microservices/kafka

### What is the motivation / use case for changing the behavior?

I need redis to manage partition per message.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
