### ISSUE TITLE
Add ability to configure error thrown by built-in exception handler on unrecognized exceptions

### ISSUE THREAD

**Issue by bozorgmehr96** [nestjs/nest#11766]
### Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to implement [JSend specification](https://github.com/omniti-labs/jsend/blob/master/README.md) and everything works except uncaught exceptions.

### Describe the solution you'd like

Add a `unrecognizedExceptionFactory` to the app.\
When the built-in exception handler can't recognize the exception it throws the error returned by the factory.

### Teachability, documentation, adoption, migration strategy

```typescript
const app = await NestFactory.create(AppModule);
app.unrecognizedExceptionFactory = () => {
    return new CustomException()
}
```

### What is the motivation / use case for changing the behavior?

To be able to control unrecognized exceptions response.

**Comment by micalevisk** [comment]
> exception handler can't recognize the exception

not sure what do you mean by that. Isn't this something that we can do already via the [catch-all exeception filter](https://docs.nestjs.com/exception-filters#catch-everything)?

**Comment by bozorgmehr96** [comment]
Yes, but what if there are other exception filters?

For example we have a filter for database related errors.

In that case the catch-all exception will catch those errors too.

**Comment by micalevisk** [comment]
I still don't see how your proposed solution differs from the catch-all aproach as that function is bound to the `app` anyway just like a global catch-all exception filter :thinking: 

if you have dedicated filter for database related errors, the catch-all won't catch those.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
