### ISSUE TITLE
@RequestMapping is undocumented

### ISSUE THREAD

**Issue by fahrradflucht** [nestjs/nest#1178]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
I get the following error message:
```
Error: Request mapping properties not defined in the @RequestMapping() annotation!
```

This would maybe be a helpful error message if I had ever heard of this annotation, but neither do I use it in my code nor is it documented.

## Expected behaviour
Mention / explain `@RequestMapping` somewhere in the docs.

## Environment
<pre><code>
Nest version: 5.3.11
</code></pre>

**Comment by barretojs** [comment]
i think it's not supposed to be documented, since it's a intern decorator for the routes(if i understood correctly).
are you using the decorators correctly? passing the route in the @Controller and stuff

**Comment by kamilmysliwiec** [comment]
It's a deprecated decorator. Read the latest docs https://docs.nestjs.com/controllers

**Comment by connorlanigan** [comment]
This error occurred to me as well, using Nest v5.6.2 .
Just as @fahrradflucht , I hadn't used the `@RequestMapping()` annotation anywhere.

In my case, the cause for this was the controller class missing the `@Controller()` attribute. As soon as I added it, the error was gone.

**Comment by mdao032** [comment]
Thank you @connorlanigan ! 
You saved my day
