### ISSUE TITLE
Nestjs multer

### ISSUE THREAD

**Issue by OlojaMuyiwa** [nestjs/nest#11791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### but the issue is that i applied to fileters to the multer configuration to only accept image files. which works. but i have two major problem 

**1. when i check if the file is an image and throw an error, it throws and error which is okay,but it doesn’t return the error to the user**

**2. when i rename the file extension which changes the mine type it doesn’t throw any error**

### Minimum reproduction code

https://github.com/OlojaMuyiwa/congenial-giggle

### Expected behavior

**1. when i check if the file is an image and throw an error, it throws and error which is okay,but it doesn’t return the error to the user**

**2. when i rename the file extension which changes the mine type it doesn’t throw any error**

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

{
  "name": "jobster",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs-modules/mailer": "^1.8.1",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.3.2",
    "@nestjs/core": "^9.0.0",
    "@nestjs/event-emitter": "^1.4.1",
    "@nestjs/jwt": "^10.0.3",
    "@nestjs/platform-express": "^9.0.0",
    "@prisma/client": "^4.15.0",
    "@types/nodemailer": "^6.4.8",
    "argon2": "^0.30.3",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "dotenv": "^16.1.4",
    "hbs": "^4.2.0",
    "nodemailer": "^6.9.3",
    "prisma": "^4.15.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.0",
    "@types/node": "18.15.11",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.5.0",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

20.3.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by OlojaMuyiwa** [comment]
@jmcdo29 
[github repo](https://github.com/OlojaMuyiwa/congenial-giggle.git)

you can clone the repo

**Comment by jmcdo29** [comment]
> you can clone the repo

Yes, I _can_ clone the repo. However, the `master` branch doesn't have use of `@UseInterceptor(FileInterceptor('file'))` or similar, and you've provided no instructions on how to reproduce whatever error you think you're running into.

This most likely is not a bug with Nest, and is rather a request for support, which should be made [on our Discord server](https://discord.gg/nestjs)

**Comment by jmcdo29** [comment]
You should still create a **minimum** reproduction, no database, no prisma, no external services, just the bare bones of what's necessary to reproduce the error. Do that, and I'll take a look.

**Comment by jmcdo29** [comment]
Use `BadRequestException`, or create your own `Exception Filter`. `Error`s are considered "unknown" by Nest and result in a 500. Any error that extends `HttpException` is considerd "known" by the base exception filter and Nest will forward on the message

**Comment by OlojaMuyiwa** [comment]
@jmcdo29 wow i didn't know error are unknown. that was the cause to my issue.

i've fixed it now and i've learnt a new thing, thanks to you.

you are doing a great job for the community thank you.
