### ISSUE TITLE
Sample 32 - graphql-federation-code-first is broken

### ISSUE THREAD

**Issue by Esteday** [nestjs/nest#11799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While starting following error occurs.

`./nest-master-3/sample/31-graphql-federation-code-first/users-application/node_modules/@apollo/federation-internals/src/error.ts:66
    super(
    ^
GraphQLError: The schema is not a valid GraphQL schema.. Caused by:
Invalid definition for directive "@tag": "@tag" should have locations FIELD_DEFINITION, OBJECT, INTERFACE, UNION, ARGUMENT_DEFINITION, SCALAR, ENUM, ENUM_VALUE, INPUT_OBJECT, INPUT_FIELD_DEFINITION, but found (non-subset) FIELD_DEFINITION, OBJECT, INTERFACE, UNION, ARGUMENT_DEFINITION, SCALAR, ENUM, ENUM_VALUE, INPUT_OBJECT, INPUT_FIELD_DEFINITION, SCHEMA
`

updating to federation 2 resolves issue but on query gives:

`"error": {
    "errors": [
      {
        "message": "Cannot read properties of undefined (reading 'kind')",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",`

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first

### Expected behavior

Sample working. Schema first approaches works without issues

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

nestje/graphql

### NestJS version

9.4.3

### Packages versions

```json

```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
I am also writing this here by downgrading to version 2.2.3 of the following:

"@apollo/gateway": "2.2.3",
"@apollo/subgraph": "2.2.3"
 

The example works perfectly.

so it is not a problem related to the `@nestjs/graphql` package but rather to the @apollo/subgraph package.

there is an open issue in the `apollograhql` federation repository regarding this problem, see here: apollographql/federation#2375

I opened a PR here: #11880, to solve the problem, at least for the time being.
