### ISSUE TITLE
@swc/jest - TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by gabrielgasp** [nestjs/nest#11804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm following the[ Nest documentation regarding SWC (Jest + SWC to be exact)](https://docs.nestjs.com/recipes/swc#jest--swc), but when I change the jest transformer from ts-node to @swc/jest, the tests start throwing `TypeError: Cannot read properties of undefined (reading 'getHello')`.

In the second commit in the _minimum reproduction code_ is the changes I made after creating a new Nest project.

This is not specific to v10, my actual project is running on Nest 9 but I created a Nest 10 project as _minimum reproduction code_ and the behavior is the same.

### Minimum reproduction code

https://github.com/GabrielGasp/nest-jest-swc-debug

### Steps to reproduce

1. `npm install`
2. `npm test` or `npm run test:e2e`

### Expected behavior

Tests to run successfully.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@swc/core @swc/jest

### NestJS version

9.0.0 and 10.0.0

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@swc/core": "^1.3.64",
    "@swc/jest": "^0.2.26",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  }
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

![Screenshot 2023-06-15 at 13 45 18](https://github.com/nestjs/nest/assets/83838669/ebd1bcd3-007f-4f9a-a790-ec29196c2df7)

**Comment by jmcdo29** [comment]
Where is the `.swcrc` to tell swc to work with decorators and the legacy decorators from Typescript that nest needs to make use of?

**Comment by GabrielGasp** [comment]
> Where is the `.swcrc` to tell swc to work with decorators and the legacy decorators from Typescript that nest needs to make use of?

I tried with the .swcrc metioned [here](https://docs.nestjs.com/recipes/swc#swc-configuration) but it didn't appear to change anything.

Since the documentation says "SWC builder is pre-configured to match the requirements of NestJS applications." and the SWC + Jest section doesn't mention anything regarding the .swcrc, I opted to leave the file out of the _minimum reproduction code_.

That said, I can add the the .swcrc file if it helps.

**Comment by GabrielGasp** [comment]
I also tried adding the following snippet to .swcrc jsc options without success.
```json
"transform": {
  "legacyDecorator": true,
  "decoratorMetadata": true
},
```

**Comment by GabrielGasp** [comment]
@jmcdo29 Ok, after doing tinkering with `.swcrc` that should have completely break the transformer, I noticed that `@swc/jest` was ignoring the file.

After some searching, I stumbled on this [issue](https://github.com/swc-project/jest/issues/52) and, apparently, you have place `@swc/jest` inside an array for it to read `.swcrc` and work as intended. Also, the additional snippet above is necessary.

Might be a good idea to update the documentation [here](https://docs.nestjs.com/recipes/swc#jest--swc) with `@swc/jest` inside an array.

I'll leave the configurations I used below for future reference.

```json
// package.json

"jest": {
  "moduleFileExtensions": [
    "js",
    "json",
    "ts"
  ],
  "rootDir": "src",
  "testRegex": ".*\\.spec\\.ts$",
  "transform": {
    "^.+\\.(t|j)s$": ["@swc/jest"]
  },
  "collectCoverageFrom": [
    "**/*.(t|j)s"
  ],
  "coverageDirectory": "../coverage",
  "testEnvironment": "node"
}
```

```json
// .swcrc

{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "baseUrl": "./"
  },
  "minify": false
}
```

**Comment by GabrielGasp** [comment]
@jmcdo29 Ok, after doing tinkering with `.swcrc` that should have completely break the transformer, I noticed that `@swc/jest` was ignoring the file.

After some searching, I stumbled on this [issue](https://github.com/swc-project/jest/issues/52) and, apparently, you have place `@swc/jest` inside an array for it to read `.swcrc` and work as intended. Also, the additional snippet above is necessary.

Might be a good idea to update the documentation [here](https://docs.nestjs.com/recipes/swc#jest--swc) with `@swc/jest` inside an array.

I'll leave the configurations I used below for future reference.

```json
// package.json

"jest": {
  "moduleFileExtensions": [
    "js",
    "json",
    "ts"
  ],
  "rootDir": "src",
  "testRegex": ".*\\.spec\\.ts$",
  "transform": {
    "^.+\\.(t|j)s$": ["@swc/jest"]
  },
  "collectCoverageFrom": [
    "**/*.(t|j)s"
  ],
  "coverageDirectory": "../coverage",
  "testEnvironment": "node"
}
```

```json
// .swcrc

{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "baseUrl": "./"
  },
  "minify": false
}
```
