### ISSUE TITLE
integration tests are not running

### ISSUE THREAD

**Issue by regevbr** [nestjs/nest#11820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running integration tests, only 2 suites are running, This is cause because there are 2 `.only` instances in the test files

### Minimum reproduction code

none

### Expected behavior

All integration tests shoulod run 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

all packages

### NestJS version

10.0.0

### Packages versions

```json

```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Fixed, thanks for reporting!
