### ISSUE TITLE
Middleware is not triggered when pass controller to consumer's forRoutes()

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest#11833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

this won't trigger the AuthMiddleware
```
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(AuthMiddleware).forRoutes(UsersController);
  }
}
```

this will trigger the AuthMiddleware
```
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(AuthMiddleware).forRoutes('users');
  }
}
```

### Minimum reproduction code

https://github.com/ianzone/nest-issue

### Steps to reproduce

1. pnpm i
2. pnpm run dev
3. go to localhost:3000/users

### Expected behavior

AuthMiddleware get triggered and console logs out 'AuthMiddleware invoked...'

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : Linux 5.15
NodeJS Version : v18.16.0
PNPM Version    : 8.6.2

[Nest CLI]
Nest CLI Version : 10.0.2

[Nest Platform Information]
platform-fastify version : 10.0.1
mapped-types version     : 0.0.1
schematics version       : 10.0.1
testing version          : 10.0.1
common version           : 10.0.1
core version             : 10.0.1
cli version              : 10.0.2

### Node.js version

v18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
that seems to be a regression introduce by PR #9809

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11837
