### ISSUE TITLE
How can I get the native node req object directly.Nestjs can't support JSON5

### ISSUE THREAD

**Issue by lovelyJason** [nestjs/nest#11830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The way it is：
I provide an api for others to call which Content-Type being application/json.But this guy is determined not to pass a legal JSON string.Instead of a key without double quotes json.Later I learned that this is the specification of JOSN5.In JSON5, there is no need to put double quotes on the key

So I can only take another way to parse this JSON5 in Nest.js.What I think is that after I finish processing, I will hand it over to nest.js for processing

I tried interceptor, pipe， 'req' decorator, 'request'decorator.

### pipe
```typescript
import { Injectable, PipeTransform, ArgumentMetadata  } from "@nestjs/common";

@Injectable()
export class ParseJson5Pipe implements PipeTransform  {
  transform(value: any, metadata: ArgumentMetadata) {
    console.log('---------------')
    console.log(value, metadata)
    return value;
  }
}
```

```typescript
import { Controller, Get, Post, Put, Delete, Body, Param } from '@nestjs/common';
import { ParseJson5Pipe } from 'src/pipes/parseJson5';

interface ReceiveResponse<T = unknown> {
  code: number;
  data?: T;
  message: string;
}

  @Post()
  @UsePipes(ParseJson5Pipe)
  async addOne(@Body() body: any): Promise<ReceiveResponse> {
    console.log(req.body)
    try {
      await this.receiveService.addOne(body)
      return {
        code: 0,
        data: null,
        message: 'success'
      }
      
    } catch (error) {
      console.log(error.message)
    }
  }

```

### interceptor

```typescript
import { Injectable, NestInterceptor, ExecutionContext, CallHandler } from "@nestjs/common";

@Injectable()
export class PraseJson5Interceptor implements NestInterceptor {
  public intercept(_context: ExecutionContext, next: CallHandler) {

    // changing request
   let request = _context.switchToHttp().getRequest();
   console.log(request.body)
   // ...
  }
}
```

```typescript
import { Controller, Get, Post, Put, Delete, Body, Param } from '@nestjs/common';
import { PraseJson5Interceptor } from 'src/interceptors/parseJson5';

interface ReceiveResponse<T = unknown> {
  code: number;
  data?: T;
  message: string;
}

  @UseInterceptors(PraseJson5Interceptor)
  @Post()
  async addOne(@Body() body: any): Promise<ReceiveResponse> {
    console.log(req.body)
    try {
      await this.receiveService.addOne(body)
      return {
        code: 0,
        data: null,
        message: 'success'
      }
      
    } catch (error) {
      console.log(error.message)
    }
  }
```

### req or request

```typescript
import { Controller, Get, Post, Put, Delete, Body, Param, Request, Req } from '@nestjs/common';

interface ReceiveResponse<T = unknown> {
  code: number;
  data?: T;
  message: string;
}

  @Post()
  async addOne(@Req() req, @request() request, @Body() body: any): Promise<ReceiveResponse> {
    console.log(req.body)
      // @Request()获取express原生请求体，监听data方法拿到req数据
      req.on('data', reqs => {
        console.log(reqs);
      })
      return '';
  }
```

All of these have no effect.They have a common result.When I post this api， For example, if I pass a non-standard JSON format，like `{a: 1}`, key without double quotes。

![image](https://github.com/nestjs/nest/assets/50656459/0bb8212e-81df-4055-bb26-4490a6d38d56)

The program reported an error directly, and did not enter my custom logic

I know that nestjs' parsing of request parameters depends on a package 'body-parser'.Including express, eggjs, all depend on this library.So no web framework in the Nodejs world supports json5 transmission.This is so tragic.Unlike in java, we can use fastjson, gson, jackson

The only way I can think of is to step into the 'body-parser' and modify the source code
```javascript
import JSON5 from 'json5'  // import this package

  function parse (body) {
    if (body.length === 0) {
      // special-case empty json body, as it's a common client-side mistake
      // TODO: maybe make this configurable or part of "strict" option
      return {}
    }

    if (strict) {
      var first = firstchar(body)

      if (first !== '{' && first !== '[') {
        debug('strict violation')
        throw createStrictSyntaxError(body, first)
      }
    }

    try {
      debug('parse json')
      return JSON.parse(body, reviver)  // return JSON5.parse(body, reviver)
    } catch (e) {
      throw normalizeJsonSyntaxError(e, {
        message: e.message,
        stack: e.stack
      })
    }
  }
```

Is it reasonable for body-parse to use 'JSON.parse' violently?

Say something off topic.Nestjs depends on express, and express only supports three request methods:

application/json
application/x-www-form-urlencoded
multipart/form-data

When We want to request application/xml, I can only be dumbfounded.We have to do this

```javascript
@Post('xml')
getXml(@request() req) {
 req.on('data', reqs =>{ console.log(reqs })
}
```

But this is not valid for json5.Illegal JSON will be directly intercepted

### Minimum reproduction code

none

### Expected behavior

- Able to support custom parsing of the body
- Or can there be a way to handle this situation instead of changing 'body-parse' source code

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "nest-project",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/mongoose": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/typeorm": "^10.0.0",
    "mongoose": "^7.3.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.12.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
nestjs supports anything that, for instance, Express supports. It just a matter of configuration.

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
