### ISSUE TITLE
Nestjs build not working as expected when NODE_ENV is set to production

### ISSUE THREAD

**Issue by nikhil-ponduri** [nestjs/nest#11848]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

Error: Property 'objectId' does not exist on type '{}'

Steps to reproduce:
1. Set the NODE_ENV environment variable to 'production'.
2. Build the NestJS application.
3. Trigger the code snippet mentioned below.

Code Snippet:

```
const mapObject = new Map()

const employee = mapObject.get("keyName");

if (!employee) {
  throw new ServerException({
  });
}
const objectId = employee.objectId;
```

Expected behavior:
The build process should complete successfully without any errors, even when the NODE_ENV environment variable is set to 'production'.

Actual behavior:
When the NODE_ENV environment variable is set to 'production', the build throws the following error: "Property 'objectId' does not exist on type '{}'."

Additional information:
- This issue does not occur in the development environment.
- The error occurs when trying to access the 'objectId' property of the 'employee' object retrieved from the 'mapObject' map.

### Minimum reproduction code

https://codesandbox.io/s/angry-wood-k5l85z?file=/src/index.js

### Expected behavior

Nestjs Build should happen with out any issues.

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

"@nestjs/common": "^9.0.0",
"@nestjs/config": "^2.2.0",
"@nestjs/core": "^9.0.0",
"@nestjs/cli": "^9.0.0",

### Node.js version

18.16.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
