### ISSUE TITLE
onApplicationShutdown not being called when onModuleDestroy is present

### ISSUE THREAD

**Issue by simplenotezy** [nestjs/nest#11866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you add both `onApplicationShutdown` and `onModuleDestroy`, the `onApplicationShutdown` is never called.

### Minimum reproduction code

https://codesandbox.io/p/sandbox/romantic-worker-285ks4?file=%2Fsrc%2Fapp.service.ts%3A8%2C4

### Steps to reproduce

1. Start the server
2. Stop it using CTRL+C

### Expected behavior

You should see:

```
Application is shutting down! Signal: SIGINT
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.9

### Packages versions

```
[System Information]
OS Version     : macOS Unknown
NodeJS Version : v16.14.2
NPM Version    : 9.6.4

[Nest CLI]
Nest CLI Version : 9.2.0

[Nest Platform Information]
platform-fastify version : 9.3.9
schematics version       : 9.0.4
schedule version         : 2.2.0
terminus version         : 9.2.1
graphql version          : 11.0.4
typeorm version          : 9.0.1
testing version          : 9.3.9
apollo version           : 11.0.4
bullmq version           : 1.1.0
common version           : 9.3.9
config version           : 2.3.1
core version             : 9.3.9
cqrs version             : 9.0.3
jwt version              : 10.0.2
cli version              : 9.2.0
 version                 : 1.8.1

### Node.js version

v16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

_No response_

**Comment by micalevisk** [comment]
you didn't call `app.enableShutdownHooks();` see https://docs.nestjs.com/fundamentals/lifecycle-events#application-shutdown

![image](https://github.com/nestjs/nest/assets/13461315/8c3bd515-ab9d-4af1-b1c6-acc4df89fc91)

**Comment by simplenotezy** [comment]
Hey @micalevisk - I actually do call that method,  but I see that I forgot to do that in the provided sandbox example. I'll update that.

**Comment by micalevisk** [comment]
![image](https://github.com/nestjs/nest/assets/13461315/4813b1cb-4ed8-4455-9534-692704e015bf)

everything went fine here tho.
