### ISSUE TITLE
Enhance ParseEnumPipe and other pipes to support optional validation

### ISSUE THREAD

**Issue by AbdlrahmanSaberAbdo** [nestjs/nest#11865]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Typically, I utilize pipes at the controller level to transform and validate the values received through the `@Query(...)` decorator. These query parameters are often used for filtering data, making them optional (it's nice if they are provided, but it's also fine if they are not).
However, when using a pipe like `@Query('priceType', ParseEnumPipe) priceType: ParseEnumPipe`, it incorrectly indicates that the value is required.

### Describe the solution you'd like

I propose the addition of an extra property, `isOptional`, to the `ParseEnumPipeOptions` interface. This would provide the flexibility to specify that a value is optional. It would be highly beneficial, as it would eliminate the need to create a custom pipe for such cases. I am happy to contribute.

### Teachability, documentation, adoption, migration strategy

Introduce the `isOptional` property to the `ParseEnumPipeOptions` interface and make necessary adjustments to the `parseEnumPipe` implementation.

### What is the motivation / use case for changing the behavior?

My motivation is to provide the ability to specify, "If a query parameter is provided, then validate and transform it; if not, bypass the pipe altogether." Query parameters are inherently optional, but if they are included, I want to ensure their validation.

I know that I can create a custom validator for this purpose, but why create a custom one and the framework already provides such functionality? Custom validators are typically designed for scenarios where the framework lacks appropriate support for specific validation requirements.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by AbdlrahmanSaberAbdo** [comment]
> Would you like to create a PR for this issue?

Sure, I wanted to make sure first that nestJs team agree on this change

**Comment by AbdlrahmanSaberAbdo** [comment]
> Would you like to create a PR for this issue?

In this PR (https://github.com/nestjs/nest/pull/11879), I introduced a new property. (isOptional) for `ParseEnumPipe`. I'm uncertain if you would like to extend this capability to other pipes as well. If you agree, please let me know, and I can create another PR to update other pipes accordingly.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11879

**Comment by cafe-jun** [comment]
Hi, I’d like to work on this issue.
I’m planning to add an `optional` option to ParseEnumPipe
to allow undefined or null values, along with unit tests.
Please let me know if this approach works.
