### ISSUE TITLE
Nest.js 10 broken on Node.js 14

### ISSUE THREAD

**Issue by ckotzbauer-nerdware** [nestjs/nest#11876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Nest.js 10 has switched to ES2021, as stated in the migration guide. The compiled code now uses logical-assignments (??=). This feature is not available in Node.js 14 (only behind a flag). However, only Node.js 12 support has ended by Nest.js 10, Node.js 14 can still be used. There's an error reported by the lambdas:
```js
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected token '??='",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token '??='",
        "    at _loadUserApp (/var/runtime/UserFunction.js:222:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:1114:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)",
        "    at Module.load (internal/modules/cjs/loader.js:979:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:819:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

### Minimum reproduction code

private code

### Expected behavior

As the release is out, please add a notice to the migration guide and maybe drop Node.js 14 support officially for Nest.js 10.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
"@nestjs/common": "10.0.0",
"@nestjs/core": "10.0.0",
"@nestjs/platform-fastify": "10.0.0",
```

### Node.js version

14.x.x (latest on AWS)

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I did not provide a code-sample, as the project is private. However, if you need one, I will try to create a repro, but I think the case should be clear.

**Comment by micalevisk** [comment]
that's expected

![image](https://github.com/nestjs/nest/assets/13461315/d034d281-2658-4fdc-8a6c-2d1b815fa422)

https://docs.nestjs.com/migration-guide

**Comment by ckotzbauer-nerdware** [comment]
Ah sorry, I did not read this sentence correctly. Thanks for the reply. But maybe change the headline to "Dropping support for Node.js 14" then. 😉
