### ISSUE TITLE
2 concurrent Prisma queries from 2 concurrent requests causes Nest to hang

### ISSUE THREAD

**Issue by bryceAebi** [nestjs/nest#11878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

*Context:* I'm running a NestJS (latest) server (node:20.2-alpine) with a postgres (postgres:15-alpine) database. Both are dockerized and connected to each other via Docker Compose. I have not tweaked any of prisma's default connection pooling parameters. Prisma is configured with NestJS per NestJS's integration guide.

*Issue:* Periodically, my web client will send 2 simultaneous requests to my server. Each request involves a simple data query (one is a SELECT and one is an UPDATE). Without fail, if I leave my setup running locally, then AFTER about 5 minutes of letting my Nestjs server run idle, when my browser makes that double request _neither_ of the Prisma calls succeed and there are no errors or warnings in my console from either nest or prisma despite having DEBUG on for both. Subsequent queries also fail until I restart the NestJS server.

Rarely, postgres will print an `unexpected eof on client connection with an open transaction` when this happens.

Note that with prisma debug on, I get the same log lines from each of the two failed queries as I do when they succeed
* `2023-06-18T19:00:16.676Z prisma:client  Prisma Client call: ... etc`
* ` 2023-06-18T19:00:16.677Z prisma:client  Generated request: ... etc`

However, when I have postgres query logging on, there are NO logs for these queries in the case where the server is hanging.

### Some Debugging I've Done
* I've tried executing the double query manually by clicking a button that fires off the 2 http requests at once. I can click the button as many times as I want without running into this issue. The issue only happens if the server has been idle for about 5 minutes
* I've tried letting the server idle for 5+ minutes and then execute ONLY ONE of the two queries, and the issue does not occur. The issue only happens when the two queries are run together triggered by their respective http requests.
* I don't believe the server is hanging because of an uncaught exception in a promise. I have the following snippet in my `main.ts` (which I've tested works) and it is not printing any issues:
```
  // Crash Node if there is an unhandled promise rejection
  process.on('unhandledRejection', (up) => {
    console.log('unhandledRejection', up)
    throw up
  })
  ```

### How to reproduce

- Spin up server and postgres via docker-compose
- Don't make any requests to the web app for about 5 minutes
- execute the double request from the web app
- see both requests fail in the web app network tab. checking server logs shows that both prisma queries never returned

Thank you very much for reviewing this issue.
### Prisma information

```prisma

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id                                   String                  @id @unique @default(uuid())
  lastActiveAt                         DateTime?               @map("last_active_at")
  lastRecordedTimezone                 String?                 @map("last_recorded_timezone")

  @@map("users")
}

model RoutineTracker {
  id              String             @id @default(uuid())
  user            User               @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId          String             @map("user_id")
  routineCode     RoutineCode        @map("routine_code")
  type            RoutineTrackerType @default(Progression) @map("type")

  @@map("routine_trackers")
}
```

```ts

/**
  * REQUEST 1 BUSINESS LOGIC
  */
  async findAll(options?: {
    userId?: string
    isActive?: boolean
    type?: RoutineTrackerType
  }): Promise<RoutineTrackerResponse[]> {

    const queryWhere = {}

    if (options.userId) {
      queryWhere['userId'] = options.userId
    }

    if (options.isActive === true) {
      queryWhere['routineCode'] = {
        in: ['routine1', 'routine2'],
      }
    }

    if (options.type) {
      queryWhere['type'] = options.type
    }

    console.log('>> before routineTrackerQuery', queryWhere)
    const routineTrackers = await this.prisma.routineTracker.findMany({
      where: queryWhere,
    })
    
    // THIS SECOND CONSOLE.LOG IS NEVER REACHED
    console.log('>> after routineTrackerQuery')

    const routineTrackerResponses: RoutineTrackerResponse[] = []
    for (const routineTracker of routineTrackers) {
      routineTrackerResponses.push(this.buildResponse(routineTracker))
    }
    return routineTrackerResponses
  }

  /**
  * REQUEST 2 BUSINESS LOGIC
  */
async updateTimezoneAndLastActiveAt(
    userId: string,
    timezone: string,
  ): Promise<UserResponse> {

    if (!moment.tz.zone(timezone)) {
      throw new BadRequestException('Invalid timezone')
    }

    console.log('BEFORE QUERY')

    const user = await this.prisma.user.update({
      where: {
        id: userId,
      },
      data: { lastRecordedTimezone: timezone, lastActiveAt: new Date() },
    })

  // THIS SECOND CONSOLE.LOG IS NEVER REACHED
   console.log('AFTER QUERY')

    return this.buildResponse(user)
  }
```

### Minimum reproduction code

it's not easy for me to make a small reproduce-able version of this, but i will work on one and add a link here

### Expected behavior

Both queries should succeed, and NestJS should not hang.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [x] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

prisma@4.15.0, @prisma/client@4.15.0

### NestJS version

10.0.1

### Packages versions

```json
{
    "@nestjs/common": "^10.0.1",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.1",
    "@nestjs/jwt": "^10.1.0",
    "@nestjs/mapped-types": "^2.0.0",
    "@nestjs/passport": "^10.0.0",
    "@nestjs/platform-express": "^10.0.1",
    "@nestjs/serve-static": "^4.0.0",
    "@nestjs/swagger": "^7.0.1",
    "@nestjs/websockets": "^10.0.1"
}
```

### Node.js version

20.2.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
I don't think this is related to Nest. Still, if you want us to help, we need a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by bryceAebi** [comment]
@kamilmysliwiec thank you for the response. I have opened a ticket with Prisma and will see if they have any advice. If that doesn't work out in the next few days, I'll put together a sample repo and respond here

**Comment by Jaikant** [comment]
@bryceAebi I am seeing exactly the same issue with nestjs and prisma, where the app goes unresponsive after a period of inactivity. I  have not yet been able to reproduce the issue, so cannot say if it is because of two concurrent requests, but it very well be prisma causing it. Do you have an issue number you are tracking in the prisma repo?

**Comment by Jaikant** [comment]
@kamilmysliwiec In my case while the symptoms and stacks are exactly like @bryceAebi, I can say that when the server goes unresponsive, it is nestjs which is unresponsive. Maybe prisma is taking nestjs done or there is something else happening here.

Even controllers which do not interact with the database are stuck. The server is able to receive requests, because I have a NestMiddleware which logs the incoming request as below:

@Injectable()
export class RequestLoggerMiddleware implements NestMiddleware {
  private logger = new Logger('RequestLoggerMiddleware');

  use(req: Request, res: Response, next: NextFunction) {
    this.logger.log(`Incoming request: ${req.method} ${req.originalUrl || req.url}`);
    next();
  }
}


But this request goes missing after that, doesn't reach the controller. The app remains unresponsive till it is restarted.

**Comment by Jaikant** [comment]
In the bootstrap funtion in main.ts I added, 
```
  process.on('uncaughtException', (error) => {
    console.error('Uncaught Exception at:', error);
  }); 

```

And one of the reasons could be the below error, not sure why it came and if it is the reason
```
Uncaught Exception at: Error: read ETIMEDOUT
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'read'
}

```

**Comment by kamilmysliwiec** [comment]
This issue has nothing to do with NestJS
