### ISSUE TITLE
Module initialization is blocked indefinitely without error message when a module injects one of its own providers into another of its own providers

### ISSUE THREAD

**Issue by RochMoreau** [nestjs/nest#11889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

# Symptoms
The build hangs indefinitely at the module dependencies initialization, without warning or error message. On little codebases (here the minimum reproduction code) the process finishes with code 0, without any info.

# Cause
The issue happens when a module tries to inject one of its own providers into another of its own providers, which is a programming error but can be hard to spot when the module has many providers.

# Problem
On large codebases with many modules, it is hard to identify which module prevents app loading because no message is displayed in the console. The app fails silently.

### Minimum reproduction code

https://github.com/RochMoreau/nestjs-silent-build-fail-reproduction

### Steps to reproduce

```
npm i
npm run start
```

Bug output:
```
> nestjs-silent-build-fail-reproduction@0.0.1 start
> nest start

[Nest] 99143  - 06/23/2023, 10:05:23 PM     LOG [NestFactory] Starting Nest application...

Process finished with exit code 0
```

### Expected behavior

Expected (non-bug) output:
A message saying "ActionsRunnerModule dependencies cannot be initialized" when a self-injection is detected. This could help locate the exact module provoking the issue.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
    "@nestjs/core": "^10.0.0"
}
```

I can confirm it is also present in version 8

### Node.js version

18.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I found the culprit Module by changing the NestJS core "instance-loader" function "createInstance" with the following implementation.
It prevents the hang by using a `Promise.race` with a timeout. If a module is not loaded before the timeout, it throws an error.
The function logs the list of module that haven't been loaded, the culprit is among them.

This may be a bit hacky, and the issue could probably be detected earlier like circular dependency detection.

```js
    async createInstances(modules) {
        const notLoadedModules = {}
        try {
        const promises = [...modules.values()].map(async (moduleRef) => {
            notLoadedModules[moduleRef.metatype.name] = true
            await this.createInstancesOfProviders(moduleRef);
            await this.createInstancesOfInjectables(moduleRef);
            await this.createInstancesOfControllers(moduleRef);
            const { name } = moduleRef.metatype;
            this.isModuleWhitelisted(name) &&
                this.logger.log((0, messages_1.MODULE_INIT_MESSAGE) `${name}`);
            delete notLoadedModules[moduleRef.metatype.name]
        })
            for (const promise of promises) {
                const timeoutPromise = new Promise((resolve, reject) => {
                    setTimeout(() => {
                        reject(new Error('Timeout occurred'));
                    }, 300);
                });
                await Promise.race([promise,timeoutPromise]);
            }
        } catch(e){
            console.log(notLoadedModules)
            throw e
        }
    }
```

**Comment by micalevisk** [comment]
could you please see if this is related with Issue #11630

**Comment by jmcdo29** [comment]
It probably is. Nest's current check for if circular deps exist is if the dep is undefined. As this has the dep defined there's another issue in the resolution. I'm working on tracing it right now

**Comment by RochMoreau** [comment]
It looks like it is the same underlying issue, an "internal" circular dependency in a module

**Comment by jmcdo29** [comment]
I've tracked the call down to this `donePromise` call(line 115). https://github.com/nestjs/nest/blob/a460bc6d361b62c7d8cdfbba110c2658443f2034/packages/core/injector/injector.ts#L102-L120

However, I'm having a bit of trouble determining what the actual method here is, so it's hard to continue debugging the promise chain

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/11630
