### ISSUE TITLE
Cannot find module '*' (SWC Compilation Error)

### ISSUE THREAD

**Issue by siamahnaf** [nestjs/nest#11891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to update my existing project to nestjs 10 for using 20x fast compiler. I set my swc in `nest-cli.json`-

```
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "builder": "swc"
  }
}
```

And am I am getting a error like

```
ReferenceError: Cannot access 'User' before initialization
```
![image](https://github.com/nestjs/nest/assets/78312010/187c3d1c-f00b-4c0d-8ac9-800200b08a8a)

### Minimum reproduction code

https://github.com/siamahnaf/test-project

### Expected behavior

I don't know what is the problem!

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```
{
  "name": "server",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@apollo/server": "^4.7.4",
    "@nestjs/apollo": "^12.0.3",
    "@nestjs/axios": "^3.0.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.0.3",
    "@nestjs/jwt": "^10.1.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/schedule": "^3.0.1",
    "@nestjs/typeorm": "^10.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/speakeasy": "^2.0.7",
    "axios": "^1.4.0",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cookie-parser": "^1.4.6",
    "geoip-lite": "^1.4.7",
    "graphql": "^16.7.1",
    "graphql-pg-subscriptions": "^2.0.5",
    "nestjs-typeorm-paginate": "^4.0.4",
    "next-useragent": "^2.8.0",
    "pg": "^8.11.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "speakeasy": "^2.0.0",
    "typeorm": "^0.3.17"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.66",
    "@types/cookie-parser": "^1.4.3",
    "@types/cron": "^2.0.1",
    "@types/express": "^4.17.17",
    "@types/geoip-lite": "^1.4.1",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Looks like your repository is private

**Comment by siamahnaf** [comment]
I can solve existing problem. But I am facing another issue. I already plaace a question on discussion into swc. Can you please see the question if you can please.

https://github.com/swc-project/swc/discussions/7577

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/recipes/swc#common-pitfalls

**Comment by siamahnaf** [comment]
Yes, I can solve it now. But I am seeing import issue. Could you please help on that?

**Comment by siamahnaf** [comment]
I already ask a question on swc GitHub discussion. Here is link-https://github.com/swc-project/swc/discussions/7577

**Comment by micalevisk** [comment]
@siamahnaf for that one, see #11863

**Comment by siamahnaf** [comment]
I already see this issues. But I can't figure out?

**Comment by siamahnaf** [comment]
my folder structure is-
![image](https://github.com/swc-project/swc/assets/78312010/61183bdc-6a66-44f9-9011-4b6d7eb728c1)

in src folder I have structure like-

`src > student > model > student.entity`
`src > user > model > user.entity`

I import user.entity into student.entity like -


`import { User } from "@/user/model/user.entity";`

I am getting an error like-

![image](https://github.com/swc-project/swc/assets/78312010/1dae2355-4ef2-41b9-b5c5-3b254ac9a350)


I create a `.swcrc` file like-

```
{
    "$schema": "https://json.schemastore.org/swcrc",
    "jsc": {
        "baseUrl": "./"
    }
}
```

and my `tsconfig.json`-

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
  }
}
```

Where I am wrong?

**Comment by kamilmysliwiec** [comment]
In `@nestjs/cli@10.0.3` SWC paths & baseUrl had to be specified manually in the .swcrc file.

In `@nestjs/cli@10.0.4` paths & baseUrl will be auto-populated from the `tsconfig.json`

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by siamahnaf** [comment]
I already provide my git repository in my last comment!

**Comment by kamilmysliwiec** [comment]
I can't reproduce your issue on my machine 

<img width="999" alt="image" src="https://github.com/nestjs/nest/assets/23244943/47468e8a-2149-45f4-b3a1-38a4bbe0c937">

**Comment by siamahnaf** [comment]
But in my environment I am still seeing the error.

I am trying from a windows pc

Your environment?

**Comment by jmcdo29** [comment]
[This is](https://github.com/swc-project/swc/issues/5165) [most likely](https://github.com/swc-project/swc/issues/4730) an [swc issue](https://github.com/swc-project/swc/issues/2725) and not related to NestJS directly. 

@kamilmysliwiec correect meif I'm wrong here, but Nest doesn't do anything special to the config or resolution when using SWC, we just pass it directly to swc for transpilation, unlike with tsc how we hook into tsconfig-paths, correct?

**Comment by llong2195** [comment]
i try it but not work
https://stackblitz.com/edit/nestjs-typescript-starter-xdrtdr

**Comment by kamilmysliwiec** [comment]
SWC won't work on web containers (stackblitz/codesandbox), just FYI.

> @kamilmysliwiec correect meif I'm wrong here, but Nest doesn't do anything special to the config or resolution when using SWC, we just pass it directly to swc for transpilation, unlike with tsc how we hook into tsconfig-paths, correct?

In the latest version of `@nestjs/cli`, we copy the `paths` and `baseUrl` configuration values from `tsconfig.json` to `.swcrc`, but other then that yeah, no changes/hooks

**Comment by siamahnaf** [comment]
> [This is](https://github.com/swc-project/swc/issues/5165) [most likely](https://github.com/swc-project/swc/issues/4730) an [swc issue](https://github.com/swc-project/swc/issues/2725) and not related to NestJS directly.
> 
Your highlighted issues all are closed as solve. But there is no proper solution. SWC said that they buy a windows pc and try to reproduce the issue. They don't find any issue, that's why they close the issue. But with nestjs we facing the same issue.

**Comment by jmcdo29** [comment]
It's a problem with swc _on Windows_. In unix environments or works as expected. If I had a Windows name I would try to figure out what swc configuration to change to get it to work

**Comment by siamahnaf** [comment]
Okay, thank you. Should I create a issue on SWC?

**Comment by kamilmysliwiec** [comment]
I just double-checked and it seems to be working as expected (windows)

@siamahnaf can you try to reproduce this issue with swc cli directly?

**Comment by llong2195** [comment]
@kamilmysliwiec 
when i override path in .swcrc, build not work
![image](https://github.com/nestjs/nest/assets/68091468/29e4180a-cbe4-4fb4-b470-6251183cd612)
![image](https://github.com/nestjs/nest/assets/68091468/b1d75850-514f-4eb9-abee-520febf533ed)

**Comment by kamilmysliwiec** [comment]
@onselakin can you please provide a minimum reproduction repository?

**Comment by siamahnaf** [comment]
Exactly same issue I am facing in my project. But it is working as expected in @kamilmysliwiec environment! I am now totally puzzled what's going on! Someone says this is the issue from swc(From Discord).

@kamilmysliwiec, Should I create a new issue in `swc`.

**Comment by siamahnaf** [comment]
@kamilmysliwiec , I have a question!

I open a file from dist folder, that was already build.

![image](https://github.com/nestjs/nest/assets/78312010/5c6c5bd8-cddc-4080-9fc5-0cf0b2ad994c)

In the picture I can I see that-

`const _studententity = require("G:/Codestation21/e-campus/server/src/student/model/student.entity");`

SWC compile path like above. Why swc compile in this way where default typescript compiler compile like-

`const _studententity = require("../student/model/student.entity");`

Why swc give the full path of the file when compilation?

**Comment by rubiin** [comment]
In my case , the file in dist still has an alias `const _entities = require("@entities");`

With tsc it works fine, 

```
	"compilerOptions": {
		"baseUrl": "src",
		"outDir": "dist",
		"paths": {
			"@lib/*": ["./lib/*"],
			"@common/*": ["./common/*"],
			"@modules/*": ["./modules/*"],
			"@entities": ["./entities/index"],
			"@mocks": ["./_mocks_/index"],
			"@generated": ["./generated/index"]
		},
	},

```

**Comment by andrucz** [comment]
@siamahnaf I just ran into the same issue trying to build my project on Windows. It works on my Mac.

**Comment by toimc** [comment]
same here

**Comment by linhtv-salefronts** [comment]
I'm running it on Mac and got the same error, it's a problem on an .entity file too, I'm using MikroORM.

**Comment by linkthai** [comment]
I'm running it on Mac and got the same error, it's a problem on an .entity file too, I'm using MikroORM.

**Comment by duyphamsalto** [comment]
I got the same issue

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the SWC repository https://github.com/swc-project/swc
