### ISSUE TITLE
whitelist:true will trim array of objects of dto

### ISSUE THREAD

**Issue by chunf** [nestjs/nest#11892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

At main.ts, if i set whitelist to be true,
```
//main.ts
 app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
    }),
  );
```
And if my dto looks like this
```
//post.dto.ts
class child {
@IsString()
name
}

class PostDto {
@ValidateNested({each:true})
@Type(()=>child)
child: child
}
```

if i post this json
```json
{
child:[
{"name": "test"}
]}
```

### Minimum reproduction code

https://codesandbox.io/p/sandbox/compassionate-bird-fscrxs?file=%2Fsrc%2Fmain.ts%3A9%2C1

### Steps to reproduce

1. npm run start
2. POST {Child:{"name":"test"}}
3. See error "Child.0.property name should not exist".

### Expected behavior

expect the validation will pass and the child[0].name value is still available.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "nest-typescript-starter",
  "private": true,
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.1",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.0.0",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.64",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
please share exactly the query that we should make

this:

![image](https://github.com/nestjs/nest/assets/13461315/3ebc5fe8-3364-44fe-9854-8cbae78796c3)

isn't the same as this one:

![image](https://github.com/nestjs/nest/assets/13461315/68b31902-3904-49fa-83a8-e2593457d235)


Also, I didn't manage to reproduce your issue here:

![image](https://github.com/nestjs/nest/assets/13461315/7c9c0cf2-8a71-4f34-b542-c2f44b1a08b8)

**Comment by chunf** [comment]
Sorry, I found out that the issue is related to creating dto as a module. Will create a new issue for this.
