### ISSUE TITLE
Devtools Graph - Injection Scope

### ISSUE THREAD

**Issue by kosiakMD** [nestjs/nest#11912]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

DevTools should show Module/Service/etc **Injection Scope** on dependency Graph

### Describe the solution you'd like

Users should see in a fast way Injection Scope of dependencies in Graph, annotations, etc.
Could be toggled in the Graph for highlighting
Devtools could show issues/exceptions

### Teachability, documentation, adoption, migration strategy

1) In the Devtools Graph user could select a Module/Service/etc - and see an annotation about its scope
2) In the Devtools Graph user could select a checkbox to highlight (background/stroke) with different colors for each Injection Scope type, with a legend to an example which is it
3) Devtools analyzer will show exceptions, e.g. scope 'request' used in module with scope 'default' (singleton)

### What is the motivation / use case for changing the behavior?

I wanted to analyze logic, structure, theoretical performance issues or bottlenecks
I want to see all of those in 1 place

**Comment by kamilmysliwiec** [comment]
> DevTools should show Module/Service/etc Injection Scope on dependency Graph

![image](https://github.com/nestjs/nest/assets/23244943/8afc4274-a57e-4254-b55c-8752bb7843a1)

Use-case #2: Scope bubbling https://youtu.be/bW8V-ssfnvM?t=42

This option isn't available for the modules view since modules themselves can't be scoped (and their providers' scope doesn't determine its scope).
