### ISSUE TITLE
Information when core version mismatches package version - or something like nest install for installing packages in proper version based on core

### ISSUE THREAD

**Issue by PiotrSzlagura** [nestjs/nest#11919]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I started developing my app when current version was 9.x. Yesterday I tried adding websockets and did 

```
yarn add @nestjs/websockets @nestjs/platform-socket.io
```

They were installed in their most current version, which is now 10.x.

When I started my app websocket just would not work, but app builds and runs fine without any information about a problem. 

You can see my test repo for this issue here: https://github.com/PiotrSzlagura/nestjs-ws-problem-repro. You can start an app and have it working just fine without websockets working and no information about it.

I finally figured out that upgrading core to 10.x solves the problem

### Describe the solution you'd like

It would be really nice if app would throw some warning when it detects mismatching versions of packages. Another possible solution would be to include something like `nest install <package>` in nest-cli, to make sure package is installed with proper version. (similar to `expo install <package>`)

### Teachability, documentation, adoption, migration strategy

I don't think this applies here

### What is the motivation / use case for changing the behavior?

Motivation here is that less experienced developers might easily overlook this version mismatch, and because there is no information about it during build, it's not that easy to debug.

**Comment by micalevisk** [comment]
See https://github.com/nestjs/nest-cli/issues/1929

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/issues/1929
Otherwise, your package manager (pnpm, npm, yarn) should already warn you about the dependencies version mismatch (peer deps)
