### ISSUE TITLE
The microservice doesn't retry message after it throw a RpcException

### ISSUE THREAD

**Issue by dancespiele** [nestjs/nest#11936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I set a microservice with `retryAttempts` 5 and `retryDelay` 3000 however it doesn't retry the message after it throws a `RpcExeption` 

### Minimum reproduction code

https://github.com/dancespiele/minimal-retry-attempts-bug

### Steps to reproduce

You can find the steps to reproduce [here](https://github.com/dancespiele/minimal-retry-attempts-bug#minimal-example-about-a-bug-retryattempts-in-tcp-transporter)

### Expected behavior

When message fail the consumer should retry the message again with the times set in `retryAttempts` 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.3

### Packages versions

```json
{
  "name": "nest-typescript-starter",
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint '{src,apps,libs,test}/**/*.ts' --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "echo 'No e2e tests implemented yet.'"
  },
  "dependencies": {
    "@nestjs/common": "10.0.3",
    "@nestjs/core": "10.0.3",
    "@nestjs/microservices": "10.0.3",
    "@nestjs/platform-express": "10.0.3",
    "class-transformer": "0.5.1",
    "class-validator": "0.14.0",
    "reflect-metadata": "0.1.13",
    "rimraf": "5.0.1",
    "rxjs": "7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "10.0.5",
    "@nestjs/schematics": "10.0.1",
    "@nestjs/testing": "10.0.3",
    "@types/amqplib": "0.10.1",
    "@types/express": "4.17.17",
    "@types/node": "20.3.1",
    "@types/supertest": "2.0.12",
    "jest": "29.5.0",
    "prettier": "2.8.8",
    "supertest": "6.3.3",
    "ts-jest": "29.1.0",
    "ts-loader": "9.4.3",
    "ts-node": "10.9.1",
    "tsconfig-paths": "4.2.0",
    "@typescript-eslint/eslint-plugin": "5.60.0",
    "@typescript-eslint/parser": "5.60.0",
    "eslint": "8.42.0",
    "eslint-config-prettier": "8.8.0",
    "eslint-plugin-import": "2.27.5",
    "typescript": "5.1.3"
  }
}
```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
