### ISSUE TITLE
Enabling validation whitelist removes child array parameter and displays validation message when DTO is wrapped as a module

### ISSUE THREAD

**Issue by chunf** [nestjs/nest#11944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a project where I like to share the same DTO between frontend and Nest.js backend. It works like a charm until I have a DTO that accepts array of object. I notice that all parameters of the object will be trimmed and removed when I enabled whitelist within validation. The issue doesn't arrise if the DTO is defined within the same backend project/module.

I created a minimum reproduction code below.

### Minimum reproduction code

https://codesandbox.io/p/sandbox/quizzical-gould-s7tk7k?file=%2Fdto%2Fsrc%2Findex.ts%3A15%2C1

### Steps to reproduce

1. cd dto
2. npm run build
3. cd ../nest-project
4.  npm run build
5. npm run start
6. curl -X POST http://localhost:3000/ -H 'Content-Type: application/json' -d '{"Child":[{"name":"abc"}]}'

### Expected behavior

Expect console log of {"Child":[{"name":"abc"}]} but instead you will get 

{"message":["Child.0.property name should not exist"],"error":"Bad Request","statusCode":400} 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10

### Packages versions

[System Information]
OS Version     : Linux 5.15
NodeJS Version : v16.17.0
NPM Version    : 8.15.0 

[Nest CLI]
Nest CLI Version : 10.0.1 

[Nest Platform Information]
platform-express version : 10.0.0
schematics version       : 10.0.1
testing version          : 10.0.0
common version           : 10.0.0
core version             : 10.0.0
cli version              : 10.0.1

### Node.js version

16.17

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

The same happened at node 18.16 version as well

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
