### ISSUE TITLE
Sample 31: GraphQL Federation code-first does not work

### ISSUE THREAD

**Issue by NilsMoller** [nestjs/nest#11942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The users application throws a `GraphQLError: The schema is not a valid GraphQL schema` error when starting.
The posts application throws a `The "@apollo/subgraph" package is missing.` error when starting.

### Minimum reproduction code

N/A

### Steps to reproduce

1. Clone this repository
2. Open sample 31: GraphQL Federation code-first
3. Run `npm install` in all three projects (users, posts, gateway)
4. Run the commands listed in the README
5. See errors in console.

### Expected behavior

The projects start correctly.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.3

### Packages versions

# Users
```json
"dependencies": {
  "@apollo/gateway": "2.4.8",
  "@apollo/server": "4.7.5",
  "@apollo/subgraph": "2.4.8",
  "@nestjs/apollo": "12.0.3",
  "@nestjs/common": "10.0.3",
  "@nestjs/core": "10.0.3",
  "@nestjs/graphql": "12.0.3",
  "@nestjs/platform-express": "10.0.3",
  "graphql": "16.6.0",
  "graphql-tools": "9.0.0",
  "reflect-metadata": "0.1.13",
  "rimraf": "5.0.1",
  "rxjs": "7.8.1",
  "ts-morph": "19.0.0"
},
"devDependencies": {
  "@nestjs/cli": "10.0.5",
  "@nestjs/schematics": "10.0.1",
  "@nestjs/testing": "10.0.3",
  "@types/express": "4.17.17",
  "@types/jest": "29.5.2",
  "@types/node": "20.3.2",
  "@types/supertest": "2.0.12",
  "@typescript-eslint/eslint-plugin": "5.60.0",
  "@typescript-eslint/parser": "5.60.0",
  "eslint": "8.43.0",
  "eslint-config-prettier": "8.8.0",
  "eslint-plugin-prettier": "4.2.1",
  "jest": "29.5.0",
  "prettier": "2.8.8",
  "supertest": "6.3.3",
  "ts-jest": "29.1.0",
  "ts-loader": "9.4.3",
  "ts-node": "10.9.1",
  "tsconfig-paths": "4.2.0",
  "typescript": "5.1.3",
  "webpack": "5.88.0"
}
```
# Posts
```json
"dependencies": {
  "@apollo/federation": "0.38.1",
  "@apollo/gateway": "2.4.8",
  "@apollo/server": "4.7.5",
  "@nestjs/apollo": "12.0.3",
  "@nestjs/common": "10.0.3",
  "@nestjs/core": "10.0.3",
  "@nestjs/graphql": "12.0.3",
  "@nestjs/platform-express": "10.0.3",
  "graphql": "16.6.0",
  "graphql-tools": "9.0.0",
  "reflect-metadata": "0.1.13",
  "rimraf": "5.0.1",
  "rxjs": "7.8.1",
  "ts-morph": "19.0.0"
},
"devDependencies": {
  "@nestjs/cli": "10.0.5",
  "@nestjs/schematics": "10.0.1",
  "@nestjs/testing": "10.0.3",
  "@types/express": "4.17.17",
  "@types/jest": "29.5.2",
  "@types/node": "20.3.2",
  "@types/supertest": "2.0.12",
  "@typescript-eslint/eslint-plugin": "5.60.0",
  "@typescript-eslint/parser": "5.60.0",
  "eslint": "8.43.0",
  "eslint-config-prettier": "8.8.0",
  "eslint-plugin-prettier": "4.2.1",
  "jest": "29.5.0",
  "prettier": "2.8.8",
  "supertest": "6.3.3",
  "ts-jest": "29.1.0",
  "ts-loader": "9.4.3",
  "ts-node": "10.9.1",
  "tsconfig-paths": "4.2.0",
  "typescript": "5.1.3"
},
```
# Gateway
```json
"dependencies": {
  "@apollo/gateway": "2.4.8",
  "@apollo/server": "4.7.5",
  "@nestjs/apollo": "12.0.3",
  "@nestjs/common": "10.0.3",
  "@nestjs/core": "10.0.3",
  "@nestjs/graphql": "12.0.3",
  "@nestjs/platform-express": "10.0.3",
  "graphql": "16.6.0",
  "graphql-tools": "9.0.0",
  "reflect-metadata": "0.1.13",
  "rimraf": "5.0.1",
  "rxjs": "7.8.1",
  "ts-morph": "19.0.0"
},
"devDependencies": {
  "@nestjs/cli": "10.0.5",
  "@nestjs/schematics": "10.0.1",
  "@nestjs/testing": "10.0.3",
  "@types/express": "4.17.17",
  "@types/jest": "29.5.2",
  "@types/node": "20.3.2",
  "@types/supertest": "2.0.12",
  "@typescript-eslint/eslint-plugin": "5.60.0",
  "@typescript-eslint/parser": "5.60.0",
  "eslint": "8.43.0",
  "eslint-config-prettier": "8.8.0",
  "eslint-plugin-prettier": "4.2.1",
  "jest": "29.5.0",
  "prettier": "2.8.8",
  "supertest": "6.3.3",
  "ts-jest": "29.1.0",
  "ts-loader": "9.4.3",
  "ts-node": "10.9.1",
  "tsconfig-paths": "4.2.0",
  "typescript": "5.1.3",
  "webpack": "5.88.0"
},
```

### Node.js version

20.2.0 (latest version i could install with nvm. `@types/node` package is specified as v20.3.2)

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I did not change anything in the repository. Its just a clone of what is on github.

**Comment by kamilmysliwiec** [comment]
@Tony133 I believe you recently created a PR to fix this example 🤔 (?)

**Comment by Tony133** [comment]
Yes, I had done this PR: https://github.com/nestjs/nest/pull/11880, from what I noticed, dependabot/renovate did automatically upgrade dependencies again. (see screenshot)
<img width="1776" alt="screen-renovate" src="https://github.com/nestjs/nest/assets/11542387/0695cbfe-e1cc-446b-a824-3b0d7d3eab65">

**Comment by Tony133** [comment]
This and the PR of renovate that re-updated the dependencies: https://github.com/nestjs/nest/pull/11811

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this again? @Tony133 I'll see if we can block renovate & dependabot on this sample 😞

**Comment by Tony133** [comment]
Yes, in the afternoon I will prepare the PR 🚀

**Comment by Tony133** [comment]
PR done! link: https://github.com/nestjs/nest/pull/11950 🔥 🚀

**Comment by kamilmysliwiec** [comment]
Thank you @Tony133! Let's track this here https://github.com/nestjs/nest/pull/11950
