### ISSUE TITLE
New 'fatal' log level for critical unrecoverable application errors (as opposed to standard user 'error' level)

### ISSUE THREAD

**Issue by Frank-D** [nestjs/nest#11945]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I find it not super convenient having to combine both critical application errors (e.g. application code bug, or application logic bug) AND user interaction errors (e.g. user trying to do something not supported by the application, or perhaps bad user inputs even though those could be mapped to less critical log levels such as verbose, debug, info or warn..).

### Describe the solution you'd like

A new 'fatal' (or 'critical') log level introduced and leveraged in the default ootb nestjs logger classes (Logger, ConsoleLogger, LoggerService, etc), which would now allow to easily differentiate/isolate application 'fatal' from 'error' problems.

### Teachability, documentation, adoption, migration strategy

Very simple doc update to introduce a new method signature in the LoggerService code snippet [listed here](https://docs.nestjs.com/techniques/logger#custom-implementation).

No migration strategy needed, since this remains backward compatible, e.g. no breaking change introduced. Users can simply start leveraging the new 'fatal/critical' log level, if they want/need to. All their existing code relying on all other existing and kept log levels will still work.

### What is the motivation / use case for changing the behavior?

In the end, if ALL application errors end up being identified all the same, e.g. under ERROR log level, then it makes it hard for us apps developers to quickly identify which of all these potential errors are actual critical unrecoverable application errors that require our immediate attention and will require actual application code or configuration fix or else they'll continue to generate errors to users trying the same functionality.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Mexidense** [comment]
Hey, folks 👋🏽

Apache Log4j uses this [standard](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/Level.html) and as @Frank-D said, the Fatal level error is used to prevent the application from continuing `and allow to easily differentiate/isolate application 'fatal' from 'error' problems`.

Could we add this fatal level error? I have never contributed to NestJS and I would like to, can I?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12161
