### ISSUE TITLE
"PRECONDITION_FAILED - reply consumer cannot acknowledge" since v10

### ISSUE THREAD

**Issue by r-arias** [nestjs/nest#11966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hey,

we seem to be running into the issue supposedly fixed by this PR: https://github.com/nestjs/nest/pull/11862

The PR was closed and the last comment suggests that this is just a configuration issue, however, it only happens after moving to v10.

When creating a Microservice like this:

```ts
@Module({
  imports: [/* ... */],
  exports: [/* ... */, 'my_jobs'],
  providers: [
    /* ... */,
    {
      provide: 'my_jobs',
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => {
        const factoryOptions: RmqOptions = {
          transport: Transport.RMQ,
          options: {
            urls: [configService.createRabbitMqConnectionString()],
            queue: configService.get('QUEUE_NAME'),
            noAck: false,
            prefetchCount: 1,
            queueOptions: {
              durable: true,
              messageTtl: parseInt(configService.get('JOB_TIMEOUT'), 10),
            },
          },
        };

        Logger.debug('CreatingProxyFactory for RMQ', factoryOptions);

        return ClientProxyFactory.create(factoryOptions);
      },
    },
  ],
})
```

we receive the following error:

```
[0] [Nest] 74747  - 03.07.2023, 14:15:35   ERROR [ClientProxy] Disconnected from RMQ. Trying to reconnect.
[0] [Nest] 74747  - 03.07.2023, 14:15:35   ERROR [ClientProxy] Object:
[0] {
[0]   "err": {
[0]     "code": 406,
[0]     "classId": 60,
[0]     "methodId": 20
[0]   }
[0] }
[0]
[0] /Users/.../node_modules/amqplib/lib/channel.js:133
[0]       var closeFrameError = new Error(e);
[0]                             ^
[0]
[0] Error: Operation failed: BasicConsume; 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - reply consumer cannot acknowledge"
[0]     at reply (/Users/.../node_modules/amqplib/lib/channel.js:133:29)
[0]     at C.accept (/Users/.../node_modules/amqplib/lib/channel.js:416:7)
[0]     at Connection.mainAccept (/Users/.../node_modules/amqplib/lib/connection.js:63:33)
[0]     at Socket.go (/Users/.../node_modules/amqplib/lib/connection.js:486:48)
[0]     at Socket.emit (node:events:513:28)
[0]     at emitReadable_ (node:internal/streams/readable:590:12)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
[0] Emitted 'error' event on ChannelWrapper instance at:
[0]     at ChannelWrapper._onConnect (/Users/.../node_modules/amqp-connection-manager/dist/cjs/ChannelWrapper.js:313:18)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[0]   code: 406,
[0]   classId: 60,
[0]   methodId: 20
[0] }
```

I am not further adding reproduction steps, as the existing PR seems to suggest you already know what's wrong. I'll happily try to provide more info if that turns out to be wrong!

### Minimum reproduction code

...

### Expected behavior

The exact same code used to work with nestjs v9. We did not upgrade `amqplib` or `amqp-connection-manager`. These were already the latest version.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.5

### Packages versions

```json
{
    "@nestjs/axios": "3.0.0",
    "@nestjs/cache-manager": "2.0.1",
    "@nestjs/common": "10.0.5",
    "@nestjs/core": "10.0.5",
    "@nestjs/jwt": "10.1.0",
    "@nestjs/microservices": "10.0.5",
    "@nestjs/passport": "10.0.0",
    "@nestjs/platform-express": "10.0.5",
    "@nestjs/schedule": "3.0.1",
    "@nestjs/typeorm": "10.0.0"
}
```

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> The PR was closed and the last comment suggests that this is just a configuration issue, however, it only happens after moving to v10.

In v9 there was a bug causing `noAck: false` to always be ignored & set to `true` (since we used `||` instead of `??`). If you want your app to keep working as it was in v9, set `noAck` to `true` (or just remove this option whatsoever as true is the default).

**Comment by r-arias** [comment]
Thanks for the answer!

Interesting, we were using `noAck: false` since before v9. If the behaviour really changed with v9, we (luckily 😅 ) never noticed. How do we get the behaviour that `noAck: false` is supposed to give us, then?

**Comment by kamilmysliwiec** [comment]
> How do we get the behaviour that noAck: false is supposed to give us, then?

I'm assuming you just want to make sure all outgoing messages are properly received & processed, is that correct? If so, you can set `noAck: true` on the consumer side (`main.ts` file of your rmq microservice) and `noAck: false` on the producer side (client configuration - your `factoryOptions` object).

**Comment by r-arias** [comment]
Great, thanks for your answer! I'll try that.

**Comment by r-arias** [comment]
Seems to work and I think I finally understood why :joy:

Thanks, I am closing this.

**Comment by csgergo123** [comment]
How can I make it so that I can manually ack incoming events?
If there is an event that can take up to minutes to run (such as a pdf generation of thousands of pages), I don't want the client to receive new events from Rabbitmq during that time. Only after the entire controller function has run.

```
@EventPattern('createPdf')
async createPdf(
  @Payload() createPdfPayload: CreatePdfPayload,
  @Ctx() context: RmqContext,
) {
  const channel = context.getChannelRef();
  const originalMsg = context.getMessage();

  try {
    await this.pdfService.create(createPdfPayload);
  } catch (error) {
    this.logger.error('Failed to create PDF', error.stack);
  }
  
  channel.ack(originalMsg);
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
