### ISSUE TITLE
`overrideModule` does not override Dynamic Modules

### ISSUE THREAD

**Issue by fmrsabino** [nestjs/nest#11967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Given the following module definitions:

```typescript
@Module({})
export class ExampleModule {
  static register(value: string): DynamicModule {
    return {
      module: ExampleModule,
      providers: [{ provide: 'TEST_TOKEN', useValue: value }],
    };
  }
}

@Module({
  imports: [ExampleModule.register('production')],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

In a testing scenario if we try to override the `ExampleModule` with `.overrideModule(ExampleModule).useModule(ExampleModule.register('test'))` the module is not overridden and the default instance is used instead. This means that `TEST_TOKEN` value is `production` even after overriding the module which provides it with `test`.

### Minimum reproduction code

https://github.com/fmrsabino/nestjs-dynamic-module-override

### Steps to reproduce

1. npm install
2. npm test

### Expected behavior

`TEST_TOKEN` should be `test` and not `production` when executing the tests under `src/app.controller.spec.ts`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.5

### Packages versions

[System Information]
OS Version     : macOS Unknown
NodeJS Version : v18.16.0
NPM Version    : 9.5.1

[Nest CLI]
Nest CLI Version : 10.1.1

[Nest Platform Information]
platform-express version : 10.0.5
schematics version       : 10.0.1
testing version          : 10.0.5
common version           : 10.0.5
core version             : 10.0.5
cli version              : 10.1.1

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
with `.useModule(ExampleModule.register('test'))` you're creating another instance of that dynamic module, that's why the "original" one didn't get overwritten

you need to use the same object returned by `ExampleModule.register('production')` at `src/app.module.ts`

**Comment by fmrsabino** [comment]
> with `.useModule(ExampleModule.register('test'))` you're creating another instance of that dynamic module, that's why the "original" one didn't get overwritten
> 
> you need to use the same object returned by `ExampleModule.register('production')` at `src/app.module.ts`. Try it out

In this case do you mean to override the provider itself (so `TEST_TOKEN`)?

**Comment by micalevisk** [comment]
I've read it too quickly, sorry

I meant, you're using `ExampleModule`, which is the static version, not the dynamic one. You'd have to do this instead:

![image](https://github.com/nestjs/nest/assets/13461315/474bdd26-c94e-4b97-89e8-4edf3adc4611)

**Comment by ajfranzoia** [comment]
I had the same problem and finally resolved it by finding this issue (AI was no help). It would be nice to have this detailed in the testing docs.

**Comment by caeus** [comment]
I had to find this thread, instead of actually finding this information in NestJs docs.
