### ISSUE TITLE
How to use multiple diskStorage destinations in same controller with nestjs

### ISSUE THREAD

**Issue by cakctus** [nestjs/nest#11977]
### Minimum reproduction code

https://github.com/cakctus/car-nestjs-backend/blob/master/src/apps/ads/create-ad/create-ad.controller.ts

### Expected behavior

Can't use multiple multer diskStorage in same controller Its works for first controller in my class, but for second controller does not work, 505 Error

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by cakctus** [comment]
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

Done

**Comment by jmcdo29** [comment]
Your reproduction is not _minimum_ 
![image](https://github.com/nestjs/nest/assets/28268680/fa1b42a1-3788-4281-b8e5-9e2745a106ac)

Please provide only the necessary code to reproduce the error.

Also, why did you remove the issue description?

**Comment by cakctus** [comment]
> Also, why did you remove the issue description?

I`am trying to use multer in same class in multiple methods, for first methods in my class i can use, but for seconds i cant, logic is the same, but i have 500 error for second controller

**Comment by micalevisk** [comment]
@cakctus we would like to see the steps to reproduce your issue as well.

**Comment by cakctus** [comment]
> @cakctus we would like to see the steps to reproduce your issue as well.

<img width="526" alt="Screenshot_1" src="https://github.com/nestjs/nest/assets/39764706/bd89c5ed-e05e-47b5-b651-7720a9c178e1">

For this works.

<img width="470" alt="Screenshot_2" src="https://github.com/nestjs/nest/assets/39764706/c41c51bd-b0d0-40b4-87d6-a3a7df8cf6f2">

But for this not

**Comment by jmcdo29** [comment]
We get what you're saying. All we're asking is for a repository that sets this up with the minimal code necessary. One controller, no database, no extra middleware, no monorepo, etc. Just a very simple setup to reproduce this bug [as this link explains](https://minimum-reproduction.wtf)

**Comment by cakctus** [comment]
Thanks everyone for helping. Issues was in incorrect folder path.
