### ISSUE TITLE
Injected Service isn't being 

### ISSUE THREAD

**Issue by israelboudoux** [nestjs/nest#11976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The methods in service `myAService` aren't being recognized when methods on the controller get called. The application initializes well, but something is happening that when methods on the service are called, raising _"TypeError: this.myAService.method is not a function"_.

### Minimum reproduction code

https://github.com/israelboudoux/nestjs-bug

### Steps to reproduce

Run the following...

```
npm i
npm run build:api
npm run start:api
curl --location 'http://127.0.0.1:9080/v1' \
--header 'Content-Type: application/json' \
--data '{}'
```

See the logs and one will see something similar to ...
```
{
  "msg": "Sorry, an unexpected error happened. Please, try again later!",
  "exception": {},
  "stack": "TypeError: this.myAService.create is not a function\n    at MyController.create (/home/israel/work/nestjs-bug/packages/api/dist/controllers/my.controller.js:30:67)\n    at /home/israel/work/nestjs-bug/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /home/israel/work/nestjs-bug/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /home/israel/work/nestjs-bug/node_modules/@nestjs/core/router/router-proxy.js:9:17\n    at async Object.<anonymous> (/home/israel/work/nestjs-bug/node_modules/@nestjs/core/router/router-explorer.js:166:17)"
}
```

### Expected behavior

The methods on `myAService` should be called with no error.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.1

### Packages versions

```json
{
  "name": "api",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "rm -rf dist && tsc -p tsconfig.json",
    "start": "node -r dotenv/config dist/index.js"
  },
  "dependencies": {
    "@fastify/cookie": "^8.3.0",
    "@fastify/cors": "^8.2.1",
    "@nestjs/common": "^9.4.1",
    "@nestjs/config": "^2.3.2",
    "@nestjs/core": "^9.4.1",
    "@nestjs/jwt": "^10.0.3",
    "@nestjs/platform-fastify": "^9.4.1",
    "@nestjs/typeorm": "^9.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "dotenv": "^16.0.3",
    "fastify": "^4.15.0",
    "nestjs-pino": "^3.2.0",
    "pino-http": "^8.3.3",
    "reflect-metadata": "^0.1.13",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/jest": "^29.5.0",
    "@types/mjml": "^4.7.1",
    "@types/node": "^18.15.11",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "ts-jest": "^29.1.0",
    "typescript": "^5.0.3"
  }
}

```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

No

**Comment by QM-Repo** [comment]
Hello @israelboudoux , 

Yes I confirm what @micalevisk  says (after testing), if you change your arrow functions, in "normal" function you will have the expected behavior!  🙂

`
 findAll = async () => {
    return undefined;
  };
`
**to**
` 
async findAll() {
    return undefined;
  }
`

Have a nice day!

**Comment by israelboudoux** [comment]
Amazing guys, thank you so much for the support!

**Comment by pawelgrzybek** [comment]
It is not a bug, it is a feature.

Spec:
https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-function-definitions

Arrow functions MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

- replace arrow functions with function declarations
- rebind method (if you really need to keep arrow functions for some reason)

```js
class {
  // from
  create = async (param) => {
    // your stuff
  },

  // to
  async create() {
    // your stuff
  }
}
```

```js
class {
  constructor() {
    this.create = this.create.bind(this)
  }

  create = async (param) => {
    // your stuff
  }
}
```

**Comment by micalevisk** [comment]
I also notice that this only happens when your `LocalStorageMapService` is using the `REQUEST` scope

**Comment by israelboudoux** [comment]
Hey @kamilmysliwiec, why you closed the issue https://github.com/nestjs/nest/issues/12083 and blocked it to receive additional comments, that is not cool man, there are edge-cases the framework doesn't handle and you're just hiding things under the carpet, congratulations for your attitude, it is helping a lot!

Cheers!
