### ISSUE TITLE
[Error] version 10 tsconfig#paths

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [nestjs/nest#11978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

compile fail

```bash
invalid type: map, expected a sequence at line 1 column 468
invalid type: map, expected a sequence at line 1 column 471
invalid type: map, expected a sequence at line 1 column 480
invalid type: map, expected a sequence at line 1 column 495
invalid type: map, expected a sequence at line 1 column 450
Failed to compile 5 files with swc.

 Error  Failed to compile:
src/app.controller.spec.ts
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/main.ts
```

### Minimum reproduction code

https://github.com/carvalhoviniciusluiz/project-test-2

### Steps to reproduce

to simulate the error just configure *paths* in the tsconfig.json file

```js
{
   "compilerOptions": {
     ...
     "paths": {
       "~/*": [
         "*"
       ]
     }
   }
}
```

then execute the command `pnpm start`

i left a gif file showing how to run the error in the readme.md of the repository that I am forwarding the link

### Expected behavior

it is expected that the project can understand the files routed with the aliases in tsconfig paths;

following a configuration:
```json
{
  "compilerOptions": {
    ...
    "outDir": "./dist",
    "baseUrl": "./src",
    "paths": {
      "~/*": [
        "*"
      ]
    }
  }
}
```
we have the final result:
```js
import { Test, TestingModule } from '@nestjs/testing';
import { AppController } from '~/app.controller';
import { AppService } from '~/app.service';
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10

### Packages versions

```json
{
  "name": "project-test-2",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "build:swc": "find src/ -type f ! -name '*.spec.ts' -exec swc --out-dir dist/ {} +",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "test:clear": "jest --clearCache",
    "up:packs": "yarn ncu -u"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.5",
    "@nestjs/core": "^10.0.5",
    "@nestjs/platform-express": "^10.0.5",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.1.7",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.0.5",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.68",
    "@swc/jest": "^0.2.26",
    "@types/express": "^4.17.17",
    "@types/jest": "29.5.2",
    "@types/node": "20.3.3",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.61.0",
    "@typescript-eslint/parser": "^5.61.0",
    "eslint": "^8.44.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "29.6.0",
    "npm-check-updates": "^16.10.13",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "29.1.1",
    "ts-loader": "^9.4.4",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.2.0",
    "typescript": "^5.1.6"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.ts?$": [
        "@swc/jest"
      ]
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

19.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
please tell us the commands we need to run to reproduce your issue (AKA _steps to reproduce_) just to know that we are in the same page

**Comment by micalevisk** [comment]
I notice that `@nestjs/cli` ends up adding `"swcrc"` as `true` [here](https://github.com/nestjs/nest-cli/blob/77915d8dbbf579c7ce651b332fe81af12d338a4d/lib/compiler/defaults/swc-defaults.ts#L34) when merging with your `.swcrc` config, which leads to such error at SWC side. 

You can reproduce the same behavior with plain swc

**Comment by micalevisk** [comment]
might be related with https://github.com/nestjs/nest-cli/issues/2160

**Comment by micalevisk** [comment]
yeah, PR https://github.com/nestjs/nest-cli/pull/2161 seems to fixes this

![image](https://github.com/nestjs/nest/assets/13461315/f53fd8ba-33fb-4f9f-a01d-2e200f2776fd)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/2161
