### ISSUE TITLE
Ignored webpack.config.js when using SWC with monorepo

### ISSUE THREAD

**Issue by masurceac** [nestjs/nest#11971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to use NestJS app in monorepo mode in combination with SWC - the webpack.config.js file is ignored.
This happens when importing SWC config: 
```js
/* webpack.config.js */
const swcDefaultConfig =
  require('@nestjs/cli/lib/compiler/defaults/swc-defaults').swcDefaultsFactory()
    .swcOptions
    
 /* ... */
 
```
Without this require statement the config file is loaded.

### Minimum reproduction code

https://github.com/masurceac/nest-monorepo-swc

### Steps to reproduce

1. `npm install`
2. `npm run start:dev`

### Expected behavior

App should load `webpack.config.js` and compile using SWC.
However, the config file is being ignored (`process.exit` is not being called).

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.5

### Packages versions

```json
{
 "dependencies": {
    "@nestjs/common": "^10.0.5",
    "@nestjs/core": "^10.0.5",
    "@nestjs/platform-express": "^10.0.5",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.1.1",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.0.5",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.67",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.3",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.60.1",
    "@typescript-eslint/parser": "^5.60.1",
    "eslint": "^8.44.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "swc-loader": "^0.2.3",
    "ts-jest": "^29.1.1",
    "ts-loader": "^9.4.4",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.6"
  }
}
```

### Node.js version

18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I noticed that when having @nest/* libraries in version 10.0.0 everything works fine.

**Comment by kamilmysliwiec** [comment]
Fixed in `@nestjs/cli@10.1.3`, thanks for reporting!
