### ISSUE TITLE
Please remove dotenv-expand from @nestjs/config package

### ISSUE THREAD

**Issue by mrm-ot** [nestjs/nest#11985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

@nest/config uses a poorly written `dotenv-expand` package without evaluating or documenting properly it's behavior. 

By reading this [Expandable variables](https://docs.nestjs.com/techniques/configuration#expandable-variables) section from Configuration, Someone might assume that only `${VAR}` syntax from `.env` file will be expanded. But this is not the case. As you can see from below, how `dotenv-expand` behave. It doesn't have any proper syntax.

.env file 

```
ENV_1='test$gone'
ENV_2='test${gone'
ENV_3='test$gone}'
ENV_4=test$gone
```

output

```
before {
  parsed: {
    ENV_1: 'test$gone',
    ENV_2: 'test${gone',
    ENV_3: 'test$gone}',
    ENV_4: 'test$gone'
  }
}
after {
  parsed: { ENV_1: 'test', ENV_2: 'test', ENV_3: 'test', ENV_4: 'test' }
}
```

### Minimum reproduction code

https://stackblitz.com/edit/stackblitz-starters-qyksmd?file=.env

### Steps to reproduce

1. view the contents of .env
2. run `node index`
2. there will be output in console

### Expected behavior

properly document the behavior of .env file expansion or remove `dotenv-expand` package  completely.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/config

### Packages versions

```json
"@nestjs/config": "^3.0.0",
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
are you proposing a drop of such feature from `@nestjs/config` or do you have an alternative package for `dotenv-expand` in mind?

**Comment by mrm-ot** [comment]
just realized dotenv-expand is used by 9 million github repo and it is written by same author as dotenv. It will make no differences by removing it from here. It makes sense to keep it as is.

**Comment by jmcdo29** [comment]
Also, I want to mention, this is documented: [documentation here](https://docs.nestjs.com/techniques/configuration#expandable-variables)
