### ISSUE TITLE
nest build swc "Bindings not found."

### ISSUE THREAD

**Issue by LastKing** [nestjs/nest#11986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Bindings not found.

### Minimum reproduction code

https://github.com/toonew-issue/nestjs-swc-graphql-comments

### Steps to reproduce

1. docker build .
2. err: `Bindings not found.` 

### Expected behavior

docker build , success build 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.5

### Packages versions

```json
{
  "name": "nestjs-study",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build -b swc --type-check",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start -b swc",
    "start:dev": "nest start -b swc --watch",
    "start:debug": "nest start -b swc --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@apollo/server": "^4.7.5",
    "@nestjs/apollo": "^12.0.7",
    "@nestjs/common": "^10.0.5",
    "@nestjs/core": "^10.0.5",
    "@nestjs/graphql": "^12.0.7",
    "@nestjs/platform-express": "^10.0.5",
    "@nestjs/swagger": "^7.1.1",
    "graphql": "^16.7.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.1.7",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.0.5",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.68",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.4.0",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.61.0",
    "@typescript-eslint/parser": "^5.61.0",
    "eslint": "^8.44.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.6.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.1",
    "ts-loader": "^9.4.4",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.6"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

windows run docker build.

I windows pc run `nest build` don't any error , but docker run `pnpm run build` wrong.

**Comment by CHFR-wide** [comment]
Hello, did you copy everything including node_modules in your Dockerfile?
I had the same problem until I realized @swc was likely very os-dependant (had a similar problem with stuff like bcrypt). It works if I `npm i @swc/core` from within the container.

It is generally good practice to **not** copy node_modules in your Dockerfile, and run `npm i` instead, but in  development environments I tend to not really care and only reinstall the troublesome packages.

**Comment by kamilmysliwiec** [comment]
> It is generally good practice to not copy node_modules in your Dockerfile, and run npm i instead, but in development environments I tend to not really care and only reinstall the troublesome packages.

This ☝️
