### ISSUE TITLE
Nest.js + Apollo GraphQL Federation + subscription

### ISSUE THREAD

**Issue by adamatti** [nestjs/nest#11987]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not exactly a problem, but today graphql subscription is not supported using federation.

There is a explicit `throw` in the code about it [here](https://github.com/nestjs/graphql/blob/910c994a9b83be3edc87e0bdeadce7d26a2f86a7/packages/apollo/lib/drivers/apollo-federation.driver.ts#L45)

```typescript
    // class ApolloFederationDriver
    if (options.installSubscriptionHandlers || options.subscriptions) {
      // TL;DR <https://github.com/apollographql/apollo-server/issues/2776>
      throw new Error(
        'No support for subscriptions yet when using Apollo Federation',
      );
    }
```

### Describe the solution you'd like

Graphql clients will be able to use subscription calling the federated service/gateway

### Teachability, documentation, adoption, migration strategy

Not 100% sure how it would be implemented.
IMHO, no migration is needed

### What is the motivation / use case for changing the behavior?

We have a microservices infrastructure and would like to have different services exposing subscriptions, so the client (ui / front) would be able to subscribe only knowing the federation gateway endpoint

**Comment by timonmasberg** [comment]
This is probably an issue for the [nestjs/graphql](https://github.com/nestjs/graphql) package. Nevertheless, the error is thrown in the apollo driver, and apollo does currently not support federated subscriptions from the `@apollo/server` package [(it does for its enterprise solutions)](https://www.apollographql.com/blog/announcement/backend/federated-subscriptions-in-graphos-real-time-data-at-scale/). You could create your own solution with schema stitching etc.. which is more of a workaround, something like [this](https://www.apollographql.com/blog/backend/federation/using-subscriptions-with-your-federated-data-graph/). This, IMHO, is nothing for the nestjs/graphql package to support natively.

**Comment by kamilmysliwiec** [comment]
Duplicate https://github.com/nestjs/graphql/issues/2879
