### ISSUE TITLE
Buffer is object when upload file

### ISSUE THREAD

**Issue by aring1998** [nestjs/nest#11983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/nestjs/nest/assets/73280042/ea7726c4-2f15-4030-92fc-61ea1475d9b4)

### Minimum reproduction code

none

### Expected behavior

The upload file should be type of byte[]

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
> The upload file should be type of byte[]

[Why?](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/multer/index.d.ts#L46)

**Comment by aring1998** [comment]
> > The upload file should be type of byte[]
> 
> [Why?](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/multer/index.d.ts#L46)
![image](https://github.com/nestjs/nest/assets/73280042/35f3e0a7-a11d-45a0-abb2-5e02b408351e)

Last year, I wrote a method for uploading files by Nestjs, as shown in the figure. The returned file is a byte [] buffer which is what I want. I don't know why the new project has the problem of buffer becoming an object.

**Comment by jmcdo29** [comment]
Can you provide a minimum reproduction?

**Comment by aring1998** [comment]
> Can you provide a minimum reproduction?

I'm sorry, when I tried to intercept a portion of the source code for you, I found out that I had defined a global pipe to filter empty data. This pipe converted the buffer into an object and now the problem has been resolved. Thank you.
