### ISSUE TITLE
nest g resource imports PartialType from "@nestjs/swagger"

### ISSUE THREAD

**Issue by yxyx-github** [nestjs/nest#12010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After installation of swagger as noted in steps to reproduce, whenever one generates a module the import of PartialType in updateDtd is imported from `@nestjs/swagger` by mistake. This cause the validation of PATCH-Requests to fail if not all required fields are provided.

### Minimum reproduction code

https://github.com/yxyx-github/partial-type-import-reproduction

### Steps to reproduce

1. create new Nest app with `nest new <your-app-name>`
2. generate a resource with `nest g resource first`
3. see the correct import of `PartialType` in `update-first.dto.ts`: `import { PartialType } from '@nestjs/mapped-types';`
4. install swagger: `npm install --save @nestjs/swagger` as described in the docs
5. generate another resource with `nest g resource second`
6. see the wrong import of `PartialType` in `update-second.dto.ts`: `import { PartialType } from '@nestjs/swagger';`

### Expected behavior

After installation of swagger as noted in steps to reproduce, the import for PartialType of every updateDtd for every generated resource should still be imported from `@nestjs/mapped-types`.

### Package

- [x] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

Output of npx nest info (don't know why it says "Windows 10", I'm actually using Windows 11):
```
[System Information]
OS Version     : Windows 10
NodeJS Version : v20.3.1
NPM Version    : 9.6.7 

[Nest CLI]
Nest CLI Version : 10.1.8

[Nest Platform Information]
platform-express version : 10.0.5
mapped-types version     : 2.0.2
schematics version       : 10.0.1
swagger version          : 7.1.1
testing version          : 10.0.5
common version           : 10.0.5
core version             : 10.0.5
cli version              : 10.1.8
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
