### ISSUE TITLE
Add Native support for in-memory testing

### ISSUE THREAD

**Issue by afaq1182** [nestjs/nest#12011]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am writing to request a new feature for NestJS that would enhance the testing capabilities of the framework. Specifically, I would like to propose the addition of native support for in-memory testing.

Currently, NestJS provides excellent support for mocking dependencies using libraries like Jest or ts-mockito, which is invaluable for unit testing. However, having native in-memory testing support within the framework itself would greatly simplify and streamline the testing process, especially for integration and end-to-end testing scenarios.

Here are a few reasons why native in-memory testing support would be beneficial:

Simplified Setup: Native support for in-memory testing would eliminate the need for developers to set up and configure external databases solely for testing purposes. This would reduce the setup time and complexity associated with configuring separate testing environments.

Improved Performance: In-memory testing eliminates the overhead of connecting to a real database, leading to faster test execution. Tests can be performed more rapidly and with increased efficiency, allowing developers to iterate and receive feedback quickly.

Database-Agnostic Testing: With in-memory testing support, developers would have the flexibility to write tests that are not tied to a specific database or ORM. This agnostic approach allows developers to focus solely on testing the logic of their application without being concerned about the underlying persistence mechanism.

Enhanced Test Coverage: In-memory testing would enable developers to test database-related functionalities more comprehensively. It would facilitate the testing of complex queries, transactional operations, and other database interactions that are challenging to mock effectively.

I believe that adding native in-memory testing support to NestJS would make the framework even more powerful and developer-friendly, aligning it with other modern frameworks that provide such capabilities out of the box.

Thank you for considering this feature request. I truly appreciate the hard work and dedication of the NestJS team in creating a fantastic framework. I am confident that the addition of native in-memory testing support would further strengthen the testing ecosystem of NestJS.

Looking forward to seeing NestJS continue to evolve and empower developers in their testing efforts.

### Describe the solution you'd like

checkout testing mechanism for Adonisjs, and implement it.

### Teachability, documentation, adoption, migration strategy

mocking doesn't help with real-time data. what if we can't test if the data is being inserted properly or not in the database.

### What is the motivation / use case for changing the behavior?

in-memory testing would ensure real-time data testing.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

However, I'm not sure how this issue is related to NestJS. With Nest, you can use any ORM/query builder/driver of your choice, be it TypeORM, Mongoose, Prisma, Knex, MikroORM, etc., and so creating a library agnostic abstraction layer that would support such a broad API surface is simply impossible & pointless.

Not to mention that performing e2e tests against a mocked, in-memory database is considered a bad practice

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
