### ISSUE TITLE
`RouterModule` causes incorrect `req.params` in middleware

### ISSUE THREAD

**Issue by Cyberuben** [nestjs/nest#12024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the `RouterModule` together with middleware, the `req.params` values seem to be wrong. 

This might have to do with the path mapping happening internally, but it results in `req.params.myParam` to contain another part of the route, instead of the parameter. 

In this case, the route `/devices/:deviceId/test/:justTesting` is registered by a `Get(':deviceId/test/:justTesting')` and a module registered with `path: 'devices'`. 

Inside the middleware, `req.params.deviceId` results in `devices`, while in the `Get()` handler, it resolves to the actual route param.

### Minimum reproduction code

https://codesandbox.io/p/sandbox/white-wood-7zm5wq

### Expected behavior

I expect the `req.params` values to reflect the actual params based on what is entered in the route.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^10.0.0

### Packages versions

```
[Nest Platform Information]
platform-express version : 10.0.5
schematics version       : 10.0.1
testing version          : 10.0.5
common version           : 10.0.5
core version             : 10.0.5
cli version              : 10.1.8
```

### Node.js version

18.16.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

<img width="806" alt="image" src="https://github.com/nestjs/nest/assets/1823121/f8f2e327-3691-4593-b5a2-372c092af693">

**Comment by micalevisk** [comment]
FYI I just tested with Nest v8.0 and v9.0 and got the same behavior as in v10
