### ISSUE TITLE
Bug  method in class metadata scanner not found getAllMethodNames

### ISSUE THREAD

**Issue by Mateusrreis** [nestjs/nest#12028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi Guys, 
I try executing project with nestjs, but is falling when running.

My project is consume queue pubsub (GCP) and also rest api.

Error in console: `this.metadataScanner.getAllMethodNames is not a function`

Happen this error when add this add layer connect pubsub, line code in main.ts.
![image (6)](https://github.com/nestjs/nest/assets/29742392/d5884afa-a970-4527-8962-3523eb9184ac)

Warning: Error happen after version @nestjs/microsservice 9.2.1, before running with sucess

I think after merged `[PR#11022](https://github.com/nestjs/nest/pull/11022)` 
Exactly this line packages/microservices/listener-metadata-explorer.ts line number 40

Help this solution, I looked and didn't find on issues.

### Minimum reproduction code

![image](https://github.com/nestjs/nest/assets/29742392/f81d4343-547e-4810-be68-c68c430415cb)

### Expected behavior

I hope started application with sucess.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^9.0.0

### Packages versions

```json
"@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/event-emitter": "^2.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/microservices": "^9.2.1",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/swagger": "^6.1.3"
```

### Node.js version

16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by micalevisk** [comment]
can you share us the output of `npx nest info`?

looks like you need to upgrade something

**Comment by kamilmysliwiec** [comment]
> Warning: Error happen after version @nestjs/microsservice 9.2.1, before running with success

Make sure your `@nestjs/common`, `@nestjs/core` and `@nestjs/microservices` are all on the same version.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
