### ISSUE TITLE
hello, document description error。

### ISSUE THREAD

**Issue by LeoKun1231** [nestjs/nest#12029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This error is described and the httpAdapterHost object should not be deconstructed

![image](https://github.com/nestjs/nest/assets/88810970/b2a3b11b-d374-4d01-945a-3b719f8a14d8)

### Minimum reproduction code

11

### Steps to reproduce

no steps

### Expected behavior

11

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

11

### NestJS version

11

### Packages versions

```json

```

### Node.js version

11111111

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

11

**Comment by micalevisk** [comment]
```
const { foo } = bar
```

is not equal to

```
const foo = bar
```

**Comment by LeoKun1231** [comment]
> ```
> const { foo } = bar
> ```
> 
> is not equal to
> 
> ```
> const foo = bar
> ```
> 
> The docs is using the first one, which is a JS feature called _destructuring_.

no,no.You misunderstood me.
The two types do not match.This variable httpAdapter should no longer be deconstructed.
Here's the link to the document. Look at the context.
https://docs.nestjs.com/exception-filters#catch-everything

![image](https://github.com/nestjs/nest/assets/88810970/e4755cfc-caaf-4093-992b-6594ef333101)

**Comment by jmcdo29** [comment]
These are different filters. The docs are correct
