### ISSUE TITLE
@CacheTTL doesn't override module default ttl

### ISSUE THREAD

**Issue by Pho3niX90** [nestjs/nest#12027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

@CacheTTL has no effect, cache still uses default TTL set on module.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-mjjolw?file=src%2Fapp.controller.ts

### Expected behavior

@CacheTTL should override module TTL for the given controller.  

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
  "dependencies": {
    "@nestjs/cache-manager": "2.0.1",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "cache-manager": "5.2.3",
    "cache-manager-redis-yet": "4.1.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
```

### Node.js version

16.20

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

The same behaviour happens for latest node and nestjs versions

**Comment by quangtran88** [comment]
Hi @Pho3niX90, according to the document, it appears that the impact is limited to methods. However, for further enhancement, I believe it would be beneficial to extend the support to the controller level as well.

![image](https://github.com/nestjs/nest/assets/107824159/c67ef0ab-6c11-4dc4-9e27-bba66173f77f)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/cache-manager/pull/112
