### ISSUE TITLE
Create Drizzle ORM recipe

### ISSUE THREAD

**Issue by LouisLecouturier** [nestjs/nest#12036]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As a beginner, I have no idea on how yo integrate drizzle ORM in a NestJs app…

### Describe the solution you'd like

As Drizzle is getting more and more adopted and trendy, I think having a recipe in the documentation (as it already exists for Prisma) would be very useful for a lot of people !

### Teachability, documentation, adoption, migration strategy

Having a recipe in the documentation 

### What is the motivation / use case for changing the behavior?

Drizzle is a new but very popular solution and its getting bigger and bigger in the ecosystem.
It could be beneficial for the NestJS ecosystem

**Comment by micalevisk** [comment]
There is an article about that, at least: https://javascript.plainenglish.io/setup-drizzle-orm-with-nest-js-ff55a7ab213f

**Comment by smith558** [comment]
> There is an article about that, at least: https://javascript.plainenglish.io/setup-drizzle-orm-with-nest-js-ff55a7ab213f

This is paywalled though.

**Comment by ItsTarik** [comment]
I don't understand why this issue is closed perhaps there is no resolution to the main need ?

**Comment by jabedzaman** [comment]
> I don't understand why this issue is closed perhaps there is no resolution to the main need ?

did u got some solution??

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/drizzle
