### ISSUE TITLE
nest.js  https+websocket

### ISSUE THREAD

**Issue by wujianyong1994** [nestjs/nest#1205]
##    websocket:

<pre><code>
import { SubscribeMessage, WebSocketGateway, WsResponse, WebSocketServer } from '@nestjs/websockets';
import { Observable, of } from 'rxjs';
import { map } from 'rxjs/operators';
@WebSocketGateway({path : '/room'})
export class EventsGateway {
  @WebSocketServer() server;
@SubscribeMessage('chat')
  chat(client: any, data: any) {
    this.server.emit('chat', data);
  }

}
</code></pre>
## web
<pre><code>
import io from 'socket.io-client';
const socket = io(websocketUrl, {path : '/room'});
socket.emit('chat', {msg});
</code></pre>

## description
i used http+websocket ,it can work.  But when i used https+websocket,it can't work.
when i request the  nest.js server with socket+https ,the browser get error:
Failed to load https://t*********.club:3001/room/?EIO=3&transport=polling&t=MQ6GnWx: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

response:{"statusCode":404,"error":"Not Found","message":"Cannot GET /room"}

How to solve ， thx！！

**Comment by karimsqualli** [comment]
When creating the websocketGateway you need to specify the `origin` parameter,

By default the value of `origin` is `*`, it mean that it allow requeest from any host, in https, you need to restrist that to only the adress of your client. for example if you are working locally : `localhost:3000`

@WebSocketGateway({path : '/room', origin: 'localhost:3000'})


More information here: https://socket.io/docs/server-api/

**Comment by wujianyong1994** [comment]
> When creating the websocketGateway you need to specify the `origin` parameter,
> 
> By default the value of `origin` is `*`, it mean that it allow requeest from any host, in https, you need to restrist that to only the adress of your client. for example if you are working locally : `localhost:3000`
> 
> @WebSocketGateway({path : '/room', origin: 'localhost:3000'})
> 
> More information here: https://socket.io/docs/server-api/
thank you very much！！！
i  set the option of WebSocketGateway : @WebSocketGateway({path : '/room', origin: 'localhost:3000'});
But the same problem happened. Maybe i  just use  http+websocket

**Comment by Root-Control** [comment]
how is configured your app.module file?

**Comment by wujianyong1994** [comment]
> how is configured your app.module file?

import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { EventsGateway } from './app.gateway'

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService, EventsGateway]
})
export class AppModule {}

**Comment by Root-Control** [comment]
Please show me main.ts code

**Comment by wujianyong1994** [comment]
> Please show me main.ts code
==========main.ts=====
async function bootstrap() {
  console.log('start nestjs');
  await Db.dbInit(config.db);
  if (process.env.NODE_ENV === 'production'){
    init.initHttps();
  } else {
    await init.init();
  }
}
bootstrap();
=========init.initHttps()======
export async function initHttps(){
    const httpsOptions = {
        key: fs.readFileSync('../Nginx/2_thebestguy.club.key'),
        cert: fs.readFileSync('../Nginx/1_thebestguy.club_bundle.crt')
    };
    const server = express();
    const app = await NestFactory.create(AppModule, server);
    app.enableCors();
    await app.init();
    https.createServer(httpsOptions, server).listen(3001);
}

**Comment by Root-Control** [comment]
In my nestjs config i had 
app.useWebSocketAdapter(new WsAdapter(app.getHttpServer()))

I deleted the code and had no more problems, I think the problem is no longer your connection to the socket, the problem lies in the configuration of mainjs or maybe the express server, verify the configuration and make the tests

**Comment by kamilmysliwiec** [comment]
Please, use StackOverflow for such questions

**Comment by jamesliauw** [comment]
@karimsqualli 
Why not review the official website documents without providing corresponding help? I believe that most people tend to publish authority rather than quality assurance.
