### ISSUE TITLE
interceptor with timeout dosen't work when handler uses synchronous blocking operation

### ISSUE THREAD

**Issue by kongku** [nestjs/nest#12087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Interceptor dosen't work when the blocking operation takes longer than tiemout specified.
I know that this problem arises from rxjs, but this is an official example given to solve the timeout.
But I wonder why this happens.

interceptor :
```typescript
@Injectable()
export class TimeoutInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    return next.handle().pipe(
      timeout(3000),
      catchError((err) => {
        if (err instanceof TimeoutError) {
          return throwError(() => new RequestTimeoutException());
        }
        return throwError(() => err);
      }),
    );
  }
}
```

controller:
```typescript
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  @Get('timeout1')
  async timeout1() {
    const result = await new Promise((resolve) => {
      const fibo = function (n) {
        if (n < 2) {
          return n;
        }
        return fibo(n - 1) + fibo(n - 2);
      };
      setTimeout(() => {
        let time = fibo(44);
        resolve('timeout1:' + time);
      }, 100);
    });
    return result;
  }

  @Get('timeout2')
  timeout2() {
    const time = fibo(45);
    resolve('timeout2:' + time);
    return result;
  }

  @Get('timeout3')
  async timeout3() {
    const result = await new Promise((resolve) => {
      const fibo = function (n) {
        if (n < 2) {
          return n;
        }
        return fibo(n - 1) + fibo(n - 2);
      };
      setTimeout(() => {
        let time = fibo(44);
        resolve('timeout1:' + time);
      }, 5000);
    });
    return result;
  }
}
```

```
$ curl -X GET -w "\nTime total: %{time_total}s\n" "localhost:3000/timeout1"
701408733
Time total: 6.964490s

$ curl -X GET -w "\nTime total: %{time_total}s\n" "localhost:3000/timeout2"
701408733
Time total: 6.845120s

$ curl -X GET -w "\nTime total: %{time_total}s\n" "localhost:3000/timeout3"
{"message":"Request Timeout","statusCode":408}
Time total: 3.039372s
```

### Minimum reproduction code

no

### Expected behavior

Blocking operations can also trigger timeouts.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
    "@nestjs/common": "^10.0.5",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.5",
    "rxjs": "^7.8.1",
}
```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
That's the nature of Node.js. Since it's "single-threaded", synchronous operations are always blocking and won't be interrupted by any asynchronous signals.
