### ISSUE TITLE
TypeError: Cannot read properties of undefined (on injected service)

### ISSUE THREAD

**Issue by israelboudoux** [nestjs/nest#12083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The following error is arising when one tries to invoke methods on an injected service. The problem is that for some methods the calls are successful, but for others don't.

```
TypeError: Cannot read properties of undefined (reading 'find')
    at OrganisationService.findAll (/home/xxx/work/nestjs-bug/packages/api/dist/services/organisation.service.js:30:71)
    at OrganisationsController.findAll (/home/xxx/work/nestjs-bug/packages/api/dist/controllers/organisations.controller.js:24:76)
    at /home/xxx/work/nestjs-bug/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/xxx/work/nestjs-bug/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /home/xxx/work/nestjs-bug/node_modules/@nestjs/core/router/router-proxy.js:9:17
    at async Object.<anonymous> (/home/xxx/work/nestjs-bug/node_modules/@nestjs/core/router/router-explorer.js:166:17)
```

### Minimum reproduction code

https://github.com/israelboudoux/nestjs-bug/tree/service_methods_failing

### Steps to reproduce

1. `npm ci`
2. `npm run db:start` (this will start a _postgres_ docker container)
3. `npm run build:api`
4. `npm run start:api`

The following command calls an endpoint on the `OrganisationController` that **fails** when calling the method `organisationService.findAll`:
```
curl --location 'http://127.0.0.1:9080/v1/organisations' \
--header 'Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5pbyIsIm5hbWUiOiJhZG1pbiIsIm9yZ2FuaXNhdGlvbklkIjoxLCJvcmdhbmlzYXRpb25Sb2xlIjowLCJpc1Bhc3N3b3JkRXhwaXJlZCI6ZmFsc2V9LCJpYXQiOjE2ODk3MjUxMTV9.Q1R7TKT7WjiuCbLQXbqVwuJqoOxeQQWpOK-K36x5u1U'
```

The following command calls an endpoint on the `OrganisationController` that **passes** when calling the method `organisationService.findById`:
```
curl --location 'http://127.0.0.1:9080/v1/organisations/1' \
--header 'Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5pbyIsIm5hbWUiOiJhZG1pbiIsIm9yZ2FuaXNhdGlvbklkIjoxLCJvcmdhbmlzYXRpb25Sb2xlIjowLCJpc1Bhc3N3b3JkRXhwaXJlZCI6ZmFsc2V9LCJpYXQiOjE2ODk3MjUxMTV9.Q1R7TKT7WjiuCbLQXbqVwuJqoOxeQQWpOK-K36x5u1U'
```

### Expected behavior

Both the calls explained in the 'Steps to reproduce' should pass.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.1

### Packages versions

```json
{
  "name": "api",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "rm -rf dist && tsc -p tsconfig.json",
    "start": "node -r dotenv/config dist/index.js",
    "dev": "tsc -p tsconfig.json --watch & node --watch dist/index.js",
    "test": "jest",
    "lint": "prettier --check ./src/**/* ./test/**/* && eslint ."
  },
  "dependencies": {
    "@fastify/cookie": "^8.3.0",
    "@fastify/cors": "^8.2.1",
    "@nestjs/common": "^9.4.1",
    "@nestjs/config": "^2.3.2",
    "@nestjs/core": "^9.4.1",
    "@nestjs/jwt": "^10.0.3",
    "@nestjs/platform-fastify": "^9.4.1",
    "@nestjs/typeorm": "^9.0.1",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "dotenv": "^16.0.3",
    "fastify": "^4.15.0",
    "jsonwebtoken": "^9.0.0",
    "mjml": "^4.14.1",
    "nestjs-pino": "^3.2.0",
    "pg": "^8.10.0",
    "pino-http": "^8.3.3",
    "postmark": "^3.0.18",
    "reflect-metadata": "^0.1.13",
    "supertest": "^6.3.3",
    "typeorm": "^0.3.16",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/jest": "^29.5.0",
    "@types/jsonwebtoken": "^9.0.2",
    "@types/mjml": "^4.7.1",
    "@types/node": "^18.15.11",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "ts-jest": "^29.1.0",
    "typescript": "^5.0.3"
  }
}

```

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
that's the issue that we found at #11976 right? Seems to be a bug, to me

**Comment by israelboudoux** [comment]
Yes @micalevisk, but the other time was about arrow methods, that in this case there isn't arrow methods anymore.

**Comment by jmcdo29** [comment]
I _think_ this has to do with the implementation of the `LocalStorageMapService`, as when it gets removed your `OrganisationService` works correctly. Seems like something in the `this` context gets messed up, but I'm not sure what yet. This does seem less of a bug within the Nest framework, and more a bug in the implementation, though it is strange that this works on some methods but not others

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be related to the Nest framework but rather to the implementation itself (`LocalStorageMapService` creates a new instance of `AsyncLocalStorage` per every incoming request so I'd suspect it already leads to some tricky to debug/find memory leaks and edge-cases).
