### ISSUE TITLE
[8.0.9] - Sharing same @EventPattern across 2 handlers is broken if 2nd handler uses an interceptor and the controller is request scoped

### ISSUE THREAD

**Issue by Dovakeidy** [nestjs/nest#12091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

[issue](https://github.com/nestjs/nest/issues/7913).

### Current behavior

Given two controller route handlers that subscribe to the same @EventPattern, both handlers are executed as expected. However, if an interceptor is used on the 2nd handler **and** the controller is request scoped, the interceptor is executed but the handler itself is never executed

Related to this [issue](https://github.com/nestjs/nest/issues/7913).

I forked the repository of this issue and upgraded Nestjs to version 8.0.9 which is supposed to have fixed this problem, but it persists if the controller is in scope request.

### Minimum reproduction code

https://github.com/Dovakeidy/nestjs-redis-troubleshoot/tree/issue-7913

### Steps to reproduce

1. yarn
2. yarn start:dev
3. Goto localhost:3000/ping

### Expected behavior

I expected both handlers to be triggered even if I use an interceptor on the 2nd handler and the controller is request scoped.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.9

### Packages versions

```json
{
  "name": "nestjs-redis-test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main"
  },
  "dependencies": {
    "@nestjs/common": "8.0.9",
    "@nestjs/core": "8.0.9",
    "@nestjs/microservices": "8.0.9",
    "@nestjs/platform-express": "8.0.9",
    "cache-manager": "3.4.4",
    "cache-manager-redis-store": "2.0.0",
    "redis": "3.1.2",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "8.1.1",
    "@nestjs/schematics": "8.0.2",
    "@types/cache-manager": "3.4.1",
    "@types/express": "4.17.12",
    "@types/node": "14.17.4",
    "prettier": "2.3.2",
    "supertest": "6.1.3",
    "ts-loader": "8.3.0",
    "ts-node": "9.1.1",
    "tsconfig-paths": "3.10.1",
    "typescript": "4.3.5"
  }
}
```

### Node.js version

14.18.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Dovakeidy** [comment]
#7913

**Comment by kamilmysliwiec** [comment]
You're using a 2y old version of Nest. Please, update to the latest version.
