### ISSUE TITLE
Controllers and Providers Auto Import

### ISSUE THREAD

**Issue by petrusdemelo** [nestjs/nest#12099]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, we need to import and export controllers and providers across system modules manually. However, sometimes we want to have an option where every component is able to receive an injection of any other else. To achieve that, it's necessary to import all controllers and injectables on this "global.module.ts" and declare them inside @Module decorator. It can become a big file as long as the size of the application grows. 

### Describe the solution you'd like

Create an "auto import" feature, where classes decorated with @Controller or @Injectable would be available immediately as controllers and providers if otherwise not done. 

The requirement is to export controllers from controller/index.ts and import from './controllers' in the main.ts file ensuring the parser will read all files.

This way, the module becomes cleaner instead of importing every single file. It fits with the use-case approach, where each use case becomes a different controller/service class and a simple application could have a hundred of imports. 

### Teachability, documentation, adoption, migration strategy

|  src
|  controllers
| -- foo.controller.ts
| -- index.ts
| global.module.ts
| main.ts

controllers/foo.controller.ts
```typescript
@Controller()
export class FooController {
  constructor(private readonly service: FooService) {}

  @Get('/foo')
  public async execute(): Promise<FooResponseDTO> {
    return this.service.execute();
  }
}
```

controllers/index.ts
```typescript
export * from './foo.controller.ts'
```

global.module.ts
```typescript
@Module({
  imports: [],
  controllers: Controllers.getControllers(), // or other approch
  providers: Providers.getProviders(), // or other approch
})
export class GlobalModule {}
```
Another possibility is if controller and provider are undefined, use every controller and provider declared:

global.module.ts
```typescript
@Module({
  imports: []
})
export class GlobalModule {}
```
In this case, could have a function like `declareProvider({ provide: foo, useClass: bar})` to populate provider array automatically.

main.ts
```typescript
import from './controllers';

//Everything else
```

### What is the motivation / use case for changing the behavior?

Cleanness of modules file.

**Comment by petrusdemelo** [comment]
I'd like to let you know, I can do this contribution. I've done that in a personal project, I just wanted to create an issue to see if there would have community support and adoption of the idea.

**Comment by jmcdo29** [comment]
This breaks the entire idea of Nest's use of modules for encapsulation. If you'd like to implement this is a third party package be our guest, but this is not aligned with the opinions of the framework.

**Comment by petrusdemelo** [comment]
@jmcdo29 this would be a second option, available to be chosen or not. The idea is not to deprecate the use of modules because I believe they are important in a lot of cases.

**Comment by micalevisk** [comment]
what I like the most on nestjs is that there isn't much 'magic' stuff happening, which, to me, helps on understanding what's going on and debug issues in my nestjs apps.

AFIAK there isn't much _convention over configuration_ (strictly speaking, there is none) besides the ones we enforce with NestJS native schematics (which can be replaced with your own schematics collection)

**Comment by jmcdo29** [comment]
@petrusdemelo I still don't see a need for this within the framework. There's never a time you need to import a controller _outside_ of its original module, and the same generally goes for `providers` as they should be shared via the `exports` of their originating modules, to keep their singleton status

**Comment by petrusdemelo** [comment]
Ok, thank you
