### ISSUE TITLE
Angular-like `inject` function

### ISSUE THREAD

**Issue by avchugaev** [nestjs/nest#12108]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Need a simpler and better way to inject dependencies in base (abstract) classes.

### Describe the solution you'd like

Angular introduced an `inject` function that solves the problems perfectly.
It also provides a better way of injection dependencies within factory functions.
It adds another option to inject dependencies and preserves the classic (constructor) approach, so it doesn't require breaking changes. 

### Teachability, documentation, adoption, migration strategy

You can find docs and example at Angular docs https://angular.io/api/core/inject

### What is the motivation / use case for changing the behavior?

It would be nice to have simple way to inject dependencies in base class without need to pass injected services by constructors chain.

Example:

```ts
abstract class ServiceBase {
  private dependency1 = inject(Dependency);
  private dependency2 = inject(TOKEN);
  private dependency3 = inject(TOKEN, {optional: true});
}

class ConcreteService extends ServiceBase {
  constructor(private dependency4: Dependency4) {
    super(); // no need to inject and pass dependencies of super class here
  }
}
```

**Comment by micalevisk** [comment]
duplicate https://github.com/nestjs/nest/issues/10586#issuecomment-1324707932
