### ISSUE TITLE
v10 testing package is incompatible with yarn PnP due to cross-package relative import

### ISSUE THREAD

**Issue by alexanderbartl** [nestjs/nest#12106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When upgrading the `@nestjs/*` packages to version 10, everything works fine in projects using classic yarn. However, with yarn berry and [plug'n'play](https://yarnpkg.com/features/pnp), there no longer is a `node_modules` folder and we get the following typescript compiler error:

    .yarn/__virtual__/@nestjs-testing-virtual-dc800f43e0/0/cache/@nestjs-testing-npm-10.0.0-3db06d0890-2309204562.zip/node_modules/@nestjs/testing/interfaces/override-module.interface.d.ts:1:34 - error TS2307: Cannot find module '../../core/interfaces/module-definition.interface' or its corresponding type declarations.
    .yarn/__virtual__/@nestjs-testing-virtual-dc800f43e0/0/cache/@nestjs-testing-npm-10.0.0-3db06d0890-2309204562.zip/node_modules/@nestjs/testing/testing-module.builder.d.ts:4:34 - error TS2307: Cannot find module '../core/interfaces/module-definition.interface' or its corresponding type declarations.

Both files import from the `@nestjs/core` package via a relative path (`import { ModuleDefinition } from '../../core/interfaces/module-definition.interface';`) rather than via the package name, which only works with a `node_modules` folder.

### Minimum reproduction code

https://github.com/alexanderbartl/nestjs-import-error-minimal

### Steps to reproduce

1. `yarn set version berry`
2. Enable PnP
3. Install v10 of nestjs
4. Run tsc

### Expected behavior

`tsc` compiles successfully.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.1.0

### Packages versions

```json
"@nestjs/testing": "10.1.0",
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [x] Linux

### Other

Note: I haven't checked if there are any other parts of the codebase using relative cross-package imports, but the ones in the testing package are the only ones reported in my projects.

**Comment by kamilmysliwiec** [comment]
Fixed in v10.1.1

**Comment by alexanderbartl** [comment]
That was fast, thanks! Unfortunately, I need to bother you again as the fix was only made in one of the two files mentioned above, `testing-module.builder.d.ts` is unchanged and continues to cause the problem.

**Comment by kamilmysliwiec** [comment]
`testing-module.builder.d.ts` is an automatically generated file. Remove `node_modules` and reinstall your packages and you should be good to go.
