### ISSUE TITLE
[typescript][intellisense] TypeScript intellisense suddenly misbehaving

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nestjs/nest#12152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

You can read more about the issue here: https://github.com/microsoft/vscode/issues/189015

### Minimum reproduction code

None

### Steps to reproduce

You can read more about the steps to reproduce here: https://github.com/microsoft/vscode/issues/189015

### Expected behavior

You can read more about expected behavior here: https://github.com/microsoft/vscode/issues/189015

### Final Words

It started happening randomly today, after so long making NestJS projects flawlessly.

I reported it to vscode repository thinking it was an intellisense issue, but apparently it's a NestJS issue.

I delete all the files in a fresh NestJS project, and the issue goes away.

Some package is doing this I'm pretty sure.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.1.2

### Packages versions

```json
{
  "name": "typeorm-test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\"",
    "start": "nest start",
    "start:dev": "pnpm format && nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "clean": "rimraf node_modules dist pnpm-lock.yaml",
    "typeorm": "ts-node ./node_modules/typeorm/cli",
    "typeorm:generate-migration": "npm run typeorm -- -d ./typeOrm.config.ts migration:generate ./migrations/%npm_config_name%",
    "typeorm:create-migration": "npm run typeorm -- migration:create ./migrations/%npm_config_name%",
    "typeorm:run-migrations": "npm run typeorm migration:run -- -d ./typeOrm.config.ts"
  },
  "dependencies": {
    "@nestjs/common": "^10.1.2",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.1.2",
    "@nestjs/platform-express": "^10.1.2",
    "@nestjs/swagger": "^7.1.2",
    "@nestjs/typeorm": "^10.0.0",
    "@nestjs/websockets": "^10.1.2",
    "@prisma/client": "^5.0.0",
    "bcrypt": "5.1.0",
    "mongodb": "^5.7.0",
    "mysql2": "^3.5.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.17"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.1.10",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.1.2",
    "@types/bcrypt": "^5.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.3",
    "@types/node": "^20.4.5",
    "@types/supertest": "^2.0.12",
    "jest": "^29.6.1",
    "prettier": "^2.8.8",
    "rimraf": "^5.0.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.1",
    "ts-loader": "^9.4.4",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.6"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

18.16.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

OS: Windows 11 Home 10.0.22621 Build 22621
VSCode: 1.80.1

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment]
btw did you have [`strictNullChecks`](https://www.typescriptlang.org/tsconfig/strictNullChecks.html) enable?

**Comment by angelhdzmultimedia** [comment]
> btw did you have [`strictNullChecks`](https://www.typescriptlang.org/tsconfig/strictNullChecks.html) enable?

Thank you for your time. No, it's `false`. I haven't touched the `tsconfig.json`.

And I consider I provided a lot of context and information so found no need to add a reproduction link. Sorry if that bothered you. In the original issue I opened in vscode repository, you can see I'm using fresh NestJS projects to test and that I also tried in another Windows user profile with a freshly installation of VSCode.

`tsconfig.json`
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

**Comment by angelhdzmultimedia** [comment]
`"strictNullChecks": true` solved it.
 
 What changed!?

![image](https://github.com/nestjs/nest/assets/10191085/5df85a23-4b56-4322-908a-d6414b15162e)

**Comment by micalevisk** [comment]
that's how that flag works. Read typescript docs. It's not related with nestjs.

**Comment by angelhdzmultimedia** [comment]
Oh by the way, in the vscode issue, I mentioned that in a Nuxt 3 TypeScript project it was working great.

So thanks to you that mentioned the `strictNullChecks`, it gave me an idea, to check the tsconfig.json that Nuxt 3 uses, and they are omitting the `strictNullChecks`.

> Read the typescript docs

LOL, condescending and arrogant much? 👎 didn't like your attitude.

It has been working like a charm since I started working with NestJS. 

The issue started today. I never touch the tsconfig.json because NestJS has been working so good with TypeScript.

Something definitely changed in NestJS templates, and you are blaming me as if I was a newbie and not knowing anything TypeScript or about the TypeScript configuration. 🙄

Thanks God there are many kind people and maintainers around.
