### ISSUE TITLE
[regression in 10.1.0] error in dependency injection

### ISSUE THREAD

**Issue by TrejGun** [nestjs/nest#12153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

after update from 10.0.5 to 10.1.0 application throws error

```
~/node_modules/@nestjs/core/injector/injector.js:43
                throw new exceptions_1.CircularDependencyException(`"${wrapper.name}"`);
                      ^

CircularDependencyException [Error]: A circular dependency has been detected inside "WaitListListService". Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()". Note that circular relationships between custom providers (e.g., factories) are not supported since functions cannot be called more than once.
    at Injector.loadInstance (~/nestjs-injection-bug/node_modules/@nestjs/core/injector/injector.js:43:23)
    at Injector.loadProvider (~/nestjs-injection-bug/node_modules/@nestjs/core/injector/injector.js:97:20)
    at ~/node_modules/@nestjs/core/injector/injector.js:228:58
```

initial discussion in discord 
https://discord.com/channels/520622812742811698/1132753430956490805

### Minimum reproduction code

https://github.com/TrejGun/nestjs-injection-bug

### Steps to reproduce

npm i
npm start
see error

### Expected behavior

no error is thrown

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.1.0

### Packages versions

```json

```

### Node.js version

20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

WebStorm

**Comment by micalevisk** [comment]
here's the dependency graph:

![graph](https://github.com/nestjs/nest/assets/13461315/938f4291-09ba-40bf-9e8e-9643af44b055)

**Comment by lvisb** [comment]
I'm also having this problem.

**Comment by micalevisk** [comment]
@lvisb is your use case too different from the https://github.com/TrejGun/nestjs-injection-bug above? if yes, could you share us your code?

**Comment by lvisb** [comment]
@micalevisk It's practically the same as your code, except that in my case, the services are in different modules. It was working on `@nestjs/core` and `@nestjs/common` version `9.3.9`.

I hadn't worked on the project for a few months, so I upgraded to `10.1.2` and had this problem.

**Comment by micalevisk** [comment]
@lvisb it's a regression introduced in v10.1.0 by #12020

you can use the semver range `~10.0.0` until we fix that. Feel free to investigate this bug :)

**Comment by jmcdo29** [comment]
<details>

<summary>It looks like the dependency properly gets found, but Nest then keeps trying to resolve it causing the error</summary>

```
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [NestFactory] Starting Nest application...
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Resolving dependency Reflector in the Reflector provider (alias)
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Looking for Reflector in InternalCoreModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Found Reflector in InternalCoreModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Resolving dependency WaitListItemService in the WaitListListService provider
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Looking for WaitListItemService in WaitListListModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Looking for WaitListItemService in WaitListItemModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Found WaitListItemService in WaitListItemModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Resolving dependency WaitListListService in the WaitListItemService provider
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Looking for WaitListListService in WaitListItemModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Looking for WaitListListService in WaitListListModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Found WaitListListService in WaitListListModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InjectorLogger] Looking for WaitListListService in InternalCoreModule
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InstanceLoader] AppModule dependencies initialized +2ms
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InstanceLoader] BlockchainModule dependencies initialized +0ms
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InstanceLoader] MechanicsModule dependencies initialized +1ms
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InstanceLoader] WaitListModule dependencies initialized +0ms
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InstanceLoader] WaitListItemModule dependencies initialized +0ms
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [InstanceLoader] WaitListListModule dependencies initialized +0ms
[Nest] 3819869  - 07/28/2023, 11:31:31 AM     LOG [NestApplication] Nest application successfully started +16ms
```

</details>

**Comment by jmcdo29** [comment]
It's strange though that we have a passing test case [for this exact scenario](https://github.com/nestjs/nest/blob/master/integration/injector/e2e/circular-modules.spec.ts)

**Comment by lvisb** [comment]
I tried creating a project from scratch using version 10.0.0 of NestJS, and I had no issues with CommonJS. However, when I switched the same project to ESM, I encountered a cyclic dependency error:

ReferenceError: Cannot access 'ModuleAService' before initialization
at file:///xxxx/src/module-b/module-b.service.ts:8:38
at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

https://github.com/lvisb/nestjs-circular-dependency-error

**Comment by micalevisk** [comment]
@lvisb that's expected. Not related to the original issue. See: #8736

**Comment by micalevisk** [comment]
for some reason a cycle is detected by the following call when checking for `WaitListItemService`

https://github.com/nestjs/nest/blob/2b1b63a74f76d9816a84ad4638d213663eee2dbe/packages/core/injector/settlement-signal.ts#L53-L55

**Comment by jmcdo29** [comment]
Thank you @micalevisk this gave me what I needed to hack up a workaround

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12163

**Comment by benkroeger** [comment]
I have resolved this by wrapping the parameter type definition of constructor injected parameter with `Readonly`


```ts
@Injectable()
class ModuleAService {
  constructor(
    @Inject(forwardRef(() => ModuleBService))
    private readonly bService: Readonly<ModuleBService>,
  ){}
}
```

the root-cause is the generated code when target is ESM. Although we're using `forwardRef` for the actual dependency injection within nestjs, Nodejs executes the top-level `__decorate` function in ModuleAService directly when loading the module... and when not wrapping the `ModuleBService` in a generic, the metadata decoration sees it as a the class (which it actually is). Wrapping it in a generic uses `Object` class instead in the metadata decorator.



```ts
// compiled output with ModuleBService class reference
ModuleAService = __decorate([
    Injectable(),
    __param(0, Inject(forwardRef(() => ModuleBService))),
    __metadata("design:paramtypes", [ModuleBService]) // <-- this is where the error is thrown
], ModuleAService);
export { ModuleAService };
```

```ts
// compiled output with Readonly<ModuleBService> reference
ModuleAService = __decorate([
    Injectable(),
    __param(0, Inject(forwardRef(() => ModuleBService))),
    __metadata("design:paramtypes", [Object])
], ModuleAService);
export { ModuleAService };
```
