### ISSUE TITLE
Error: Cannot find module '@nestjs/common/utils/select-exception-filter-metadata.util'

### ISSUE THREAD

**Issue by wls0** [nestjs/nest#12151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Server start after get error

Error: Cannot find module '@nestjs/common/utils/select-exception-filter-metadata.util'
Require stack:
- /Users/test/Desktop/project/my-api/node_modules/@nestjs/microservices/exceptions/rpc-exceptions-handler.js
- /Users/test/Desktop/project/my-api/node_modules/@nestjs/microservices/context/exception-filters-context.js
- /Users/test/Desktop/project/my-api/node_modules/@nestjs/microservices/microservices-module.js
- /Users/test/Desktop/project/my-api/node_modules/@nestjs/microservices/nest-microservice.js
- /Users/test/Desktop/project/my-api/node_modules/@nestjs/microservices/index.js
- /Users/test/Desktop/project/my-api/dist/app.module.js
- /Users/test/Desktop/project/my-api/dist/main.js

### Minimum reproduction code

yarn run start

### Steps to reproduce

1. yarn add @nestjs/microservices
2. yarn run start
3. get error

### Expected behavior

i try 
delete node_modules
delete dist folder

but get a error message

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

'@nestjs/common/utils/select-exception-filter-metadata.util'

### NestJS version

9.0.0

### Packages versions

[System Information]
OS Version     : macOS Unknown
NodeJS Version : v18.16.0
YARN Version    : 1.22.19 

[Nest CLI]
Nest CLI Version : 9.4.2 

[Nest Platform Information]
platform-express version : 9.4.0
microservices version    : 10.1.2
schematics version       : 9.1.0
mongoose version         : 10.0.0
passport version         : 10.0.0
swagger version          : 7.0.4
testing version          : 9.4.0
common version           : 9.4.0
config version           : 3.0.0
core version             : 9.4.0
jwt version              : 10.1.0
cli version              : 9.4.2

### Node.js version

v18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Align your `@nestjs/*` versions. Upgrade all to v10

You're using v9 and v10 at same time. Might be that

**Comment by micalevisk** [comment]
oh, yeah, should be that

you're using `@nestjs/comoon` v9 while your `@nestjs/microservices` is under v10
