### ISSUE TITLE
Measure time cost between after request incoming and before response sending

### ISSUE THREAD

**Issue by thorseraq** [nestjs/nest#12159]
### Is there an existing issue that is already proposing this?
- [x] have searched the existing issues

### Is your feature request related to a problem? Please describe it
Currently I'm investigating server timing measurement for nest server: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing, and record the cost in the response header

I investigated middleware, the following code can calculate the time cost, but only when response is finished, this make adding cost in response header impossible.

```typescript
app.use((req: Request, res: Response, next: NextFunction) => {
  const requestId = req.headers[REQUEST_ID] || 'unknown';
  const now = process.hrtime();
  req.res = res; // used in logger-plugin.ts
  res.on('finish', () => {
    const delta = process.hrtime(now);
    const cost = delta[0] + delta[1] / 1e9;
    // ...
  });
  next();
});
```

Interceptor has similar problem, when `next.handle()` is invoked, the response has already been sent
```typescript
@Injectable()
export class TimingInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    const now = Date.now();
    return next.handle().pipe(
      tap(() => {
        const response = context.switchToHttp().getResponse();
        const processingTime = Date.now() - now;
        response.set('X-Processing-Time', processingTime.toString());
      })
    );
  }
}
```

So wondering Is there any way to observe and record the time cost of a request tour (before response was sent)

**Comment by thorseraq** [comment]
Currently I found a solution with [on-headers](https://github.com/jshttp/on-headers), implementation refers: https://github.com/toeverything/AFFiNE/pull/3370/files#diff-a0ab03198deee5faadb7caa3fa31f3cb0f8408d6b8db2a266fc3105f9e76b7ed:~:text=onHeaders(res%2C%20()%20%3D%3E%20%7B

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
