### ISSUE TITLE
ApplicationConfig got undefined, global enhancers doesnt work when using `NestFactory.createApplicationContext`

### ISSUE THREAD

**Issue by SocketSomeone** [nestjs/nest#12165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I using libs which using `ExternalContextCreator` for apps - global enhancers doesnt work for some reason.
(For example [nest-commander](https://nest-commander.jaymcdoniel.dev/en/features/commander/), [necord](https://necord.org/))

### Minimum reproduction code

https://github.com/SocketSomeone/nestjs-standalone-apps-issue

### Steps to reproduce

1. `yarn install`
2. `yarn start:dev`

### Expected behavior

After bootstrap application allow to create  fns via `ExternalContextCreator` with global enhancers. For that we need to pass ApplicationConfig to container

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.1.0

### Packages versions

```json
[System Information]
OS Version     : Windows 10
NodeJS Version : v18.12.1
YARN Version    : 1.22.19 

[Nest CLI]
Nest CLI Version : 10.1.8

[Nest Platform Information]
common version : 10.1.0
core version   : 10.1.0
```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12166
