### ISSUE TITLE
"mapChildrenToValidationErrors" method returns incorrect error message when validating an object which is in an array

### ISSUE THREAD

**Issue by anhpt97** [nestjs/nest#12164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I just discovered something that I think could be a bug here:
https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L266

When I validate a complex DTO:
```
import { Type } from 'class-transformer';
import { IsArray, IsNotEmpty, IsString, ValidateNested } from 'class-validator';

export class LoginDto3 {
  @IsString()
  @IsNotEmpty()
  username: string;

  @IsString()
  @IsNotEmpty()
  password: string;
}

export class LoginDto2 {
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => LoginDto3)
  username: LoginDto3[];

  @IsString()
  @IsNotEmpty()
  password: string;
}

export class LoginDto {
  @ValidateNested()
  @Type(() => LoginDto2)
  username: LoginDto2;

  @IsString()
  @IsNotEmpty()
  password: string;
}
```

Result:
![Screenshot from 2023-07-30 19-39-47](https://github.com/nestjs/nest/assets/54684536/72af06ed-d418-4f5b-ad34-179a127a791e)

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-jtqamz

### Expected behavior

I think the code should be fixed to like this:
![Screenshot from 2023-07-30 20-37-07](https://github.com/nestjs/nest/assets/54684536/459ce0a1-b48a-4582-b402-70e3d45f8250)

Note: "isNumberString" function is imported from the "class-validator" package.

Result:
![Screenshot from 2023-07-30 19-26-10](https://github.com/nestjs/nest/assets/54684536/275d9445-ccb7-4c6c-b064-bc0fe82167b0)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by anhpt97** [comment]
P.S. I'm temporarily using a regular expression to fix this issue:
```message = message.replace(/()(\.)(\d[^.]*)()/g, '$1[$3]$4');```

**Comment by micalevisk** [comment]
I believe that we can't use `isNumberString` from class-validator because `ValidationPipe` doesn't requires class-validator (see `loadValidator` method)

**Comment by anhpt97** [comment]
> I believe that we can't use `isNumberString` from class-validator because `ValidationPipe` doesn't requires class-validator (see `loadValidator` method)

Yeah, I understand, so I just edited the content of this issue. I used this regular expression:
```/^\d/.test(error.property)``` (check if "error.property" must start with a numeric character)

**Comment by micalevisk** [comment]
What about negative numbers?

**Comment by anhpt97** [comment]
> What about negative numbers?

Hmmm, so the regular expression would look like this:
```/^\-?\d/```
It seems that I have not been able to cover all possible scenarios.

**Comment by anhpt97** [comment]
After a few hours of searching, I think this is probably the best regular expression:
```/[^\p{L}]/gu```

![Screenshot from 2023-07-31 00-08-49](https://github.com/nestjs/nest/assets/54684536/76e87894-ab4c-432b-a954-dedb74effbfc)

In case if the value of "error.property" is all letters, part of the error message will have dot notation style (a.b), otherwise it will have bracket notation style (a['b']). Although I would like it to have dot notation style if error.property = "abc123", for example.

Sorry if my wording is a bit confusing.

**Comment by micalevisk** [comment]
Ok can you clarify _why_ exactly do you think that the current behavior is a bug? Just to align the expectations here

**Comment by anhpt97** [comment]
@micalevisk I set logging in multiple places in 3 functions ("flattenValidationErrors", "mapChildrenToValidationErrors" and "prependConstraintsWithParentProp") and found out the value of "error.property" is having issues. As you can see from the example above, "username.username.0.username" doesn't seem to be correct but should be "username.username[0].username".
(Sorry if my answer doesn't really answer your question.)

**Comment by micalevisk** [comment]
I don't know why we have that dot notation (which is invalid for JS) but there is am unit test asserting such usage, see:

https://github.com/nestjs/nest/blob/2b1b63a74f76d9816a84ad4638d213663eee2dbe/packages/common/test/pipes/validation.pipe.spec.ts#L179-L183

so, to me, the current behavior seems to be correct as it is aligned with the test suite :thinking:

**Comment by anhpt97** [comment]
Hmmm, I haven't read through the "validation.pipe.spec.ts" file so I didn't think it was a correct behavior. If that's the author's expectation then I'll probably solve the problem myself, although I don't think "test.0.prop1" is correct 😀.

**Comment by kamilmysliwiec** [comment]
This is just an error message - it's not supposed to be parsed and executed as JS instruction, that's why we decide that `.0.` notation is good enough

**Comment by anhpt97** [comment]
Dziękuję za wyjaśnienie, panie Myśliwiec! :)
