### ISSUE TITLE
✨ FR: Make LogLevels extendable by turning it into an interface 

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nestjs/nest#12177]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The LogLevel type is not extendable. So you cannot provide a list of LogLevels that is not a subset of LogLevels.

https://github.com/nestjs/nest/blob/657b24cbd37b56f8d26c722e0aebb1c90098c6e5/packages/common/services/logger.service.ts#L9

### Describe the solution you'd like

Suggestion of @Rafaeltab via Discord is something like the following

```ts
interface LogLevelList {
  log?: 'log';
  error?: 'error';
  warn?: 'warn';
  debug?: 'debug';
  verbose?: 'verbose';
}

type LogLevel = keyof LogLevelList
```

### Teachability, documentation, adoption, migration strategy

for most of the users there should be no change since they might already only use the given log levels.

### What is the motivation / use case for changing the behavior?

Customizing a logger with custom log levels is not possible with the restriction to a specific set of log levels and having the correct typescript typing.

**Comment by KostyaTretyak** [comment]
But your new `LogLevel` will also be not extendable. In fact, it is important for you to have the `LogLevelList` interface. Only it can be extendable.

**Comment by KostyaTretyak** [comment]
@rafaeltab, your example only works if it's in a single file, or the `LogLevelList` will be declared globally. Neither the first nor the second is probably a good practice.

**Comment by rafaeltab** [comment]
> @rafaeltab, your example only works if it's in a single file, or the `LogLevelList` will be declared globally. Neither the first nor the second is probably a good practice.

You're right, it only works if it is declared globally or in the same file. I would like to add that the main point of the issue is only to allow the extension of the type in some way so we can define custom log levels. There is no requirement for it to be implemented in this way. If anyone finds a better way to implement this It is only natural that you should use that method.

The proposed method does not require any existing developers to change their code and is therefore very unintrusive. If an alternate solution is found, I hope it maintains this aspect.

**Comment by sschneider-ihre-pvs** [comment]
> I find that relying on declaration merging a bit odd from consumer PoV
> 
> Instead, I'd suggest a type arg for `LoggerService`. But I'm unsure if it will looks that better

I guess this is also difficult because the LogLevels live in the options object, so you would end up with some kind of generic for a property of an object that doesn't even have to exist. Also, you have to make it backward compatible.

**Comment by sschneider-ihre-pvs** [comment]
As @rafaeltab mentioned, this is only a suggestion to be able to make the loglevels extendable to be able to use and extend the logger correctly. Currently, you are able to add methods for other log levels, but you will be unable to set those loglevels with setLogLevels because it is restricted to a subset of the default ones.

**Comment by KostyaTretyak** [comment]
I know that the following example is not ideal, but it gives an opportunity to extend the Logger:

```ts
import { LoggerService, LogLevel, Logger } from '@nestjs/common';

type MyLogLevel = 'log' | 'error' | 'warn' | 'debug' | 'verbose' | 'customLevel';

interface MyLoggerService extends LoggerService {
  setLogLevels?(levels: MyLogLevel[]): any;
}

class MyLogger extends Logger {
  static override isLevelEnabled(level: MyLogLevel): boolean {
    return super.isLevelEnabled(level as LogLevel);
  }

  static override overrideLogger(logger: MyLoggerService | MyLogLevel[] | boolean): any {
    return super.overrideLogger(logger as LoggerService | LogLevel[] | boolean);
  }
}
```

Is this option not suitable for you?

**Comment by kamilmysliwiec** [comment]
What log levels that are not provided by the framework would you like to use though?

**Comment by sschneider-ihre-pvs** [comment]
> 

winston has a log level silly for example. npm has also some others like timing, notice, http, silent ...

**Comment by sschneider-ihre-pvs** [comment]
for me personally I was trying to add `info` and `silly`

**Comment by kamilmysliwiec** [comment]
BTW 

> The LogLevel type is not extendable. So you cannot provide a list of LogLevels that is not a subset of LogLevels.

Unions are _extendable_:

```ts
export type MyLogLevels = LogLevels | 'silly';
```

**Comment by rafaeltab** [comment]
> BTW
> 
> > The LogLevel type is not extendable. So you cannot provide a list of LogLevels that is not a subset of LogLevels.
> 
> Unions are _extendable_:
> 
> ```ts
> export type MyLogLevels = LogLevels | 'silly';
> ```

The goal is too extend the original union, not create a new one with the same values. Your code does not change [this](https://github.com/nestjs/nest/blob/657b24cbd37b56f8d26c722e0aebb1c90098c6e5/packages/common/services/logger.service.ts#L44C3-L44C3) union for example:

**Comment by rafaeltab** [comment]
> If you want to create a logger that provides non-framework-supported methods, why would you even use `setLogLevels`? Since you need to instantiate the logger class yourself, you could just pass what levels should be used through the constructor, or provide an alternative method for configuring them.

I just gave that as an example, I am not personally encountering this issue, I helped PO find a solution, and am trying to help find answers to his question here. From [this](https://github.com/nestjs/nest/issues/12177#issuecomment-1660486754) comment I take that he does need `setLogLevels`, and that the restrictions on it are preventing him from using it properly. I do not know the exact use case, perhaps @sschneider-ihre-pvs could give some more insight into whether the solution you proposed could solve his issue.

**Comment by sschneider-ihre-pvs** [comment]
> If you want to create a logger that provides non-framework-supported methods, why would you even use `setLogLevels`? Since you need to instantiate the logger class yourself, you could just pass what levels should be used through the constructor, or provide an alternative method for configuring them.

The constructor has the same constraints to `LogLevels`

**Comment by kamilmysliwiec** [comment]
Not sure if I'm following. 

I believe there might be a slight misunderstanding about my intended point. Let me try to rephrase what I said. 

If you want to create a logger that provides non-framework-supported methods (and so it won't be compatible with Nest logger and possibly others that implement the `LoggerService` interface either way), why do you want to follow `ConsoleLogger` API? If you have a custom class, you can provide your own constructor, and your own options object, you can establish your own API, and implement log-level checking logic. There's no limitation on the framework side to do so.

**Comment by HariAcharya80** [comment]
I don't think this change is needed since framework don't have any obligation on custom logging. We can do this in many ways.

**Comment by sschneider-ihre-pvs** [comment]
The intent was to just add additional loglevels by leaving the rest as it is. I was not inclined to just reimplement consolelogger just with two extra log levels. it is also possible to just skip type safety and just add the functions for the loglevels and call them manually. Since there are no restrictions on class augmentation, only on type augmentation.
If it is not possible or not wanted, this FR can be closed.
