### ISSUE TITLE
The application crashes when an RpcException is thrown from the gRPC controller.

### ISSUE THREAD

**Issue by albert-mirzoyan** [nestjs/nest#12187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Nest application crashes (unhanded exception) when an exception is thrown in the gRPC controller with a stream input.

### Minimum reproduction code

https://github.com/albert-mirzoyan/reproducible-grpc-exception

### Steps to reproduce

Install and start an application
```shell
npm ci
nest start
```

Run a test in separate terminal
```shell
npm run test:e2e 
```
Test should fail, nest will fail to call lastValueFrom on a EMPTY Observable and crash
https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-grpc.ts#L285

### Expected behavior

The thrown RpcException should be "sent" to the client, just like it is when a non-streaming controller throws an exception.
Both test cases in the provided example should pass, and the application should not crash

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json

```

### Node.js version

v16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by quangtran88** [comment]
I think we can add `defaultIfEmpty(undefined)` after `catchError` throws `EMPTY` sinnce we have validated `if (!isUndefined(response))` as below:
 
```typescript
      } else {
        const response = await lastValueFrom(
          res.pipe(
            takeUntil(fromEvent(call as any, CANCEL_EVENT)),
            catchError(err => {
              callback(err, null);
              return EMPTY;
            }),
            defaultIfEmpty(undefined), // <= Add default as undefined
          ),
        );

        if (!isUndefined(response)) {
          callback(null, response);
        }
      }
```
I created a PR for this https://github.com/nestjs/nest/pull/12282

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12282

**Comment by alvincrisuy** [comment]
Is the fix working already? when i throw an exception even for non grpcexception the server crash
