### ISSUE TITLE
Guards on GraphQL subscriptions?

### ISSUE THREAD

**Issue by murbanowicz** [nestjs/nest#1219]
Hello,

I was trying to find something about it in docs but didn't find this topic.

I was looking for some docs or/and example how I can protect subscriptions.
For example when user trying to subscribe for updates on some tenant data if he has active membership with that tenant. 

I would appreciate any help to understand this topic.

**Comment by marcus-sa** [comment]
I agree on this, there seriously needs some more documentation on how to do guards on GraphQL resolvers.
Authentication with JWT and so many more topics.

**Comment by jukkahell** [comment]
I did something like this to get my subscription protected:
First in your app module import GraphQLModule:
`GraphQLModule.forRootAsync({
   inject: [UserService, ConfigService],
   imports: [UserModule, ConfigModule],
   useFactory: graphQLModuleFactory, // <-- graphQLModule factory is below
})`

GraphQLModuleFactory shouild return GqlModuleOptions. Here's only the subscription option that is relevant:
`export const graphQLModuleFactory = async (config: ConfigService) => ({
  subscriptions: {
    onConnect: async (connParams, websocket) => {
      const tokenHeader = "jwtToken";
      const token = connParams["jwtToken"];
      if (token) {
        jwt.verify(token, config.jwtSecret) as JwtPayload;
      } else {
        throw new UnauthorizedException("Unauthorized", "User not authorized to connect.");
      }
    },
  },
... // rest of the options`

jwt is imported from jsonwebtoken library.

Hope this helps.

**Comment by jukkahell** [comment]
The above works when you want to subscribe in any of the subscriptions you have. But I don't know the answer if you want to guard only specific @Subscription. And that's why I'm here. I tried to get the request from context:
```
@Subscription("receiveMessage")
receiveMessage() {
  return {
    subscribe: (rootValue, args, context, info) => {
      console.log(context);
    }
  }
}
```
But there was only `{ req: undefined }` in there.

Would appreciate if someone had any ideas how to do it.

**Comment by zjovan** [comment]
@jukkahell any progress?

**Comment by jukkahell** [comment]
@zjovan unfortunately no. I've been trying for two nights to find a solution but I believe we have no other option but to get it fixed inside Nest somehow.

**Comment by kamilmysliwiec** [comment]
I'll take care of it soon. Could you please create an issue in the corresponding repository? https://github.com/nestjs/graphql

**Comment by jukkahell** [comment]
Thanks for the reply Kamil. I created this: https://github.com/nestjs/graphql/issues/84

**Comment by kamilmysliwiec** [comment]
Thanks @jukkahell. Let's track this issue there! :)
