### ISSUE TITLE
Feature request: improve the cache feature

### ISSUE THREAD

**Issue by giosueDelgado** [nestjs/nest#12196]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The current caching system in NestJS, while functional, lacks some of the ease of use and flexibility found in other libraries such as [type-cacheable](https://github.com/joshuaslate/type-cacheable). Managing caches and especially cleaning groups of keys could be made more user-friendly and efficient.

### Describe the solution you'd like

I want to manage cache more effectively in my project, and I find that the current caching techniques available in NestJS are not as intuitive or complete as the ones in the type-cacheable library. This is particularly true when dealing with complex scenarios that require managing or cleaning groups of keys.
A clear and concise integration of features similar to those found in the type-cacheable library into NestJS would be highly beneficial. This would include more simplistic usage and a more comprehensive level of control for cleaning specific groups of keys. Considered drawbacks might include the complexity of implementing these changes and ensuring compatibility with existing NestJS applications.

### Teachability, documentation, adoption, migration strategy

Implementing this feature would require clear documentation, including examples of how to leverage the new caching capabilities. A migration guide for users who are currently using the existing caching system might also be beneficial. Perhaps a step-by-step tutorial or even a comparison table between the current approach and the new approach could help users adopt this feature quickly.

### What is the motivation / use case for changing the behavior?

The motivation behind this request is to simplify and enhance the caching capabilities in NestJS. This change would align the NestJS caching system more closely with other modern solutions, making it easier for developers to manage and optimize cache in various use cases. By offering a more powerful and intuitive caching system, we can make NestJS even more appealing to developers, aligning it with current standards and expectations in the field.

**Comment by kamilmysliwiec** [comment]
What prevents you from using `type-cacheable` with Nest?

**Comment by giosueDelgado** [comment]
Hi @kamilmysliwiec we start using it.
My request is to integrate this feature directly in the nestjs framework. At the moment there is a cache manager, I think can be more good for nestjs framework to integrate this better level of cache.

What do you think about it?

**Comment by kamilmysliwiec** [comment]
> My request is to integrate this feature directly in the nestjs framework.

Nest framework doesn't provide cache feature ootb

>  At the moment there is a cache manager

`@nestjs/cache-manager` is just a tiny wrapper around `cache-manager` that lets you use this package with Nest. Using `type-cacheable` instead is perfectly fine though. We don't need official wrappers for all existing libraries in the ecosystem
