### ISSUE TITLE
Cannot manage to get the Dev-tool  working

### ISSUE THREAD

**Issue by dberardo-com** [nestjs/nest#12193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i have setup the devtool following the nestjs guide.

NOTE: my project was bootstrapped using "nx" so i have no npm start:dev command, i run just npm start making sure NODE_DEV=development

the application starts up regularly, but the localhost:8000 page shows this messsage: 

"GET is not allowed for the request."

### Minimum reproduction code

https://docs.nestjs.com/devtools/overview

### Expected behavior

i should be able to see the devtool gui on port 8000

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/devtools-integration

### NestJS version

9.1.1

### Packages versions

```json
"@nestjs/apollo": "^11.0.5",
    "@nestjs/axios": "^2.0.0",
    "@nestjs/bull": "^10.0.1",
    "@nestjs/cache-manager": "^1.0.0",
    "@nestjs/common": "^9.1.1",
    "@nestjs/config": "^2.3.2",
    "@nestjs/core": "^9.1.1",
    "@nestjs/event-emitter": "^2.0.0",
    "@nestjs/graphql": "^11.0.5",
    "@nestjs/microservices": "^9.4.2",
    "@nestjs/platform-express": "^9.1.1",
    "@nestjs/sequelize": "^9.0.2",
    "@nestjs/typeorm": "^10.0.0",
```

### Node.js version

14.21.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Hi @dberardo-com,  try updating the dependencies `@nestjs/core` and `@nestjs/common` to version 9.3.x, devtools has been integrated since version 9.3.x of NestJS.

**Comment by micalevisk** [comment]
you can try to use this tiny package: https://www.npmjs.com/package/nestjs-devtools-loader to reduce the boilerplate code

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead

**Comment by dberardo-com** [comment]
> Hi @dberardo-com, try updating the dependencies `@nestjs/core` and `@nestjs/common` to version 9.3.x, devtools has been integrated since version 9.3.x of NestJS.

i have upgraded to v10.x but same error: 

![image](https://github.com/nestjs/nest/assets/65530457/d7791b9f-9652-424b-98cf-fb5ef22bb76a)

**Comment by dberardo-com** [comment]
> you can try to use this tiny package: https://www.npmjs.com/package/nestjs-devtools-loader to reduce the boilerplate code

same error here as well ... no useful log in console ...

i am using "node" to start the environment, not "nest", is that a problem ?

how can i use nest in a "@nx" project ?

**Comment by Tony133** [comment]
> > Hi @dberardo-com, try updating the dependencies `@nestjs/core` and `@nestjs/common` to version 9.3.x, devtools has been integrated since version 9.3.x of NestJS.
> 
> i have upgraded to v10.x but same error:
> 
> ![image](https://user-images.githubusercontent.com/65530457/258891425-d7791b9f-9652-424b-98cf-fb5ef22bb76a.png)

I confirm that Devtools also works with Nx monorepo, however seeing the "localhost:8000" screenshot, what is it referring to? to the Devtools endpoint or your app? because Devtools works through the platform you don't have to connect via browsers to the enpoint, but you need to login with a github, gitlab or bitbucket account first ( see screenshot ) and then once you start app with nx, on devtools platform you will find an endpoint that doesn't refer to your app, but it is an enpoint where devtools uses to collect the graph,etc of your app. 

<img width="1002" alt="devtools-endpoint" src="https://github.com/nestjs/nest/assets/11542387/63401b4a-34f2-406a-aef0-e396ec76afb8">

**Comment by dberardo-com** [comment]
this makes it more clear ... i thought devtool was an offline tool ... somehow the documentation is not explicit about this point ...

is the devtool free? can i create an account and use it for test purposes without any credit card upload and stuff like that ?

thanks for mentioning this ...

**Comment by charlesbodman** [comment]
This should be made more clear in the documentation. It seems like an offline tool.
