### ISSUE TITLE
Cache interceptor prioritization

### ISSUE THREAD

**Issue by ehenon** [nestjs/nest#12194]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Let's take a NestJS application using a cache system, and having a controller implemented like this:

```
import { Controller, Get, UseInterceptors } from "@nestjs/common";
import { CacheInterceptor } from "@nestjs/cache-manager";
import { CustomCacheInterceptor } from "@common/interceptors/custom-cache.interceptor";
import { TestService } from "./test.service";

@Controller("")
@UseInterceptors(CacheInterceptor)
export class TestController {
    constructor(private readonly testService: TestService) {}

    @Get("/a")
    async getA(...): Promise<string> {
        return this.testService.getA(...);
    }
  
    @Get("/b")
    @UseInterceptors(CustomCacheInterceptor)
    async getB(...): Promise<string> {
        return this.testService.getB(...);
    }

    // other routes
    // ...
}
```

As we can see, all routes in the controller will benefit from the use of Nest's `CacheInterceptor` default cache interceptor. But one route in particular (`GET /b`) benefits from a custom cache interceptor that has been coded specifically for certain app routes (most likely a different cache key management).

With this code, when calling the `GET /b` route, the custom cache interceptor will not override the default cache interceptor. Both will be executed and the route will be cached twice, which is certainly not what's intended.

If we want to use the default cache interceptor for all the controller's routes except for the `GET /b` route, one solution might be to remove the `@UseInterceptors(CacheInterceptor)` annotation from the controller and put it on each of the file's routes, except for route `GET /b`. But if we have many different routes in our application, and many controllers, this can quickly become redundant.

### Describe the solution you'd like

In the context of using cache interceptors (the default NestJS cache interceptor, but also any other custom interceptor extending it), it may be relevant to set up a prioritization system so that only the "lowest-level" interceptor is used.

### Teachability, documentation, adoption, migration strategy

```
import { Controller, Get, UseInterceptors } from "@nestjs/common";
import { CacheInterceptor } from "@nestjs/cache-manager";
import { CustomCacheInterceptor } from "@common/interceptors/custom-cache.interceptor";
import { TestService } from "./test.service";

@Controller("")
@UseInterceptors(CacheInterceptor)
export class TestController {
    constructor(private readonly testService: TestService) {}

    @Get("/a")
    async getA(...): Promise<string> {
        return this.testService.getA(...);
    }
  
    @Get("/b")
    @UseInterceptors(CustomCacheInterceptor)
    async getB(...): Promise<string> {
        return this.testService.getB(...);
    }

    // other routes
    // ...
}
```

With this code, a call to the `GET /b` route would use the `CustomCacheInterceptor` but not Nest's default `CacheInterceptor` (the custom interceptor being the lowest-level annotated cache interceptor).

On the other hand, a call to the `GET /a` route would use Nest's default `CacheInterceptor` (as there is no low-level method annotation, but a global annotation at controller level).

### What is the motivation / use case for changing the behavior?

Avoid having to add the same `@UseInterceptors(CacheInterceptor)` annotation to all routes not using a custom cache interceptor.

**Comment by jmcdo29** [comment]
This isn't how Interceptors, or enhancers in general, work. You'd have to extends the standard caching interceptor to read for metadata to know to skip caching for specific route handlers.

**Comment by ehenon** [comment]
Hello @jmcdo29, thanks for your answer

I know that's not how interceptors work in general. However I thought it might be relevant that there is logic like this only at the level of cache interceptors (those extending `CacheInterceptor`), as I didn't see a real use case where multiple cache interceptors might want to be used by someone for a single route.

Could you share a code snippet using your technique pls?
