### ISSUE TITLE
platform-fastify error in type utils after upgrade nestjs version

### ISSUE THREAD

**Issue by brunokunace** [nestjs/nest#12207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

yarn && yarn start:dev
Starting compilation in watch mode...

node_modules/@nestjs/platform-fastify/node_modules/fastify/types/utils.d.ts:53:76 - error TS1005: '?' expected.

53 type StringAsNumber<T extends string> = T extends `${infer N extends number}` ? N : never;
                                                                              ~

node_modules/@nestjs/platform-fastify/node_modules/fastify/types/utils.d.ts:66:47 - error TS1005: '?' expected.

66     Key extends `${infer X extends CodeClasses}xx` ?
                                                 ~

node_modules/@nestjs/platform-fastify/node_modules/fastify/types/utils.d.ts:69:108 - error TS1005: '?' expected.

### Minimum reproduction code

not have any way to do this

### Steps to reproduce

scripts: {
    "start:dev": "nest start --watch",
}

yarn
yarn start:dev

### Expected behavior

Run the awesome app =)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.1

### Packages versions

```json
"dependencies": {
    "@amplitude/node": "^1.9.1",
    "@aws-sdk/client-chime": "^3.335.0",
    "@aws-sdk/client-chime-sdk-meetings": "^3.310.0",
    "@aws-sdk/client-dynamodb": "^3.342.0",
    "@aws-sdk/lib-dynamodb": "^3.342.0",
    "@fastify/secure-session": "^6.2.0",
    "@logdna/logger": "^2.3.0",
    "@nestjs/axios": "^3.0.0",
    "@nestjs/common": "^10.1.3",
    "@nestjs/core": "^10.1.3",
    "@nestjs/jwt": "^10.1.0",
    "@nestjs/passport": "^10.0.0",
    "@nestjs/platform-express": "^10.1.3",
    "@nestjs/platform-fastify": "^10.1.3",
    "@nestjs/schedule": "^3.0.2",
    "@nestjs/swagger": "^7.1.7",
    "@nestjs/typeorm": "^10.0.0",
    "@ngneat/falso": "^6.4.0",
    "@slack/webhook": "^6.0.0",
    "@types/cache-manager": "^4.0.1",
    "@types/cron": "^1.7.3",
    "@types/stripe": "^8.0.417",
    "ably": "^1.2.30",
    "activecampaign": "^1.2.5",
    "async-sema": "^3.1.1",
    "aws-sdk": "^2.952.0",
    "aws4": "^1.11.0",
    "bcryptjs": "^2.4.3",
    "cache-manager": "^4.1.0",
    "class-transformer": "0.4.0",
    "class-validator": "^0.13.1",
    "crypto": "^1.0.1",
    "dotenv": "^10.0.0",
    "escape-html": "^1.0.3",
    "fastify": "3.29.4",
    "fastify-raw-body": "^3.1.0",
    "fastify-swagger": "^4.4.2",
    "module-alias": "^2.2.2",
    "moment-range": "^4.0.2",
    "mysql2": "^2.2.5",
    "nestjs-stripe": "^1.0.0",
    "node-ses": "^3.0.3",
    "openai": "^3.2.1",
    "passport": "^0.4.1",
    "passport-headerapikey": "^1.2.2",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.6",
    "sqlite3": "^5.0.2",
    "stripe": "^12.1.1",
    "typeorm": "^0.2.31",
    "typeorm-seeding": "^1.6.1",
    "url-metadata": "^2.5.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.6",
    "@nestjs/schematics": "^7.2.7",
    "@nestjs/testing": "^7.6.14",
    "@types/aws-sdk": "^2.7.0",
    "@types/bcrypt": "^3.0.0",
    "@types/express": "^4.17.11",
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.31",
    "@types/passport-jwt": "^3.0.5",
    "@types/passport-local": "^1.0.33",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.15.2",
    "@typescript-eslint/parser": "^4.15.2",
    "eslint": "^7.20.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-config-standard-with-typescript": "^20.0.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-promise": "^4.3.1",
    "eslint-plugin-standard": "^5.0.0",
    "git-commit-msg-linter": "^3.0.4",
    "husky": "^4.3.8",
    "jest": "^26.6.3",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "supertest": "^6.1.3",
    "ts-jest": "^26.5.2",
    "ts-loader": "^8.0.17",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "4.4.4"
  },

```

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

After update the nestjs version from 7 to 10, we receive this errors and can't start my app.

**Comment by micalevisk** [comment]
nvm

upgrade your `typescript` package to v5.
