### ISSUE TITLE
关于架子不能启动

### ISSUE THREAD

**Issue by sundalingg** [nestjs/nest#12200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

作者你好，我在使用你的架子时，有些node包安装不了，请问node需要什么版本，node镜像地址是什么。我有尝试14版本的node和淘宝镜像的地址，但是还有些node包下不了，

### Minimum reproduction code

主项目

### Expected behavior

作者你好，我在使用你的架子时，有些node包安装不了，请问node需要什么版本，node镜像地址是什么。我有尝试14版本的node和淘宝镜像的地址，但是还有些node包下不了，还有些包说是windows用不了。

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```
packjosn我没有改动

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
