### ISSUE TITLE
Kafka hybrid application incorrectly initializes consumers when producerOnlyMode set to true

### ISSUE THREAD

**Issue by bylethviva** [nestjs/nest#12206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When starting the hybrid application, the startup logs show that a consumer has been started and that it has joined the consumer group with id `nestjs-group-server`.

### Minimum reproduction code

https://github.com/bylethviva/nestjs-hybrid-kafka-issues

### Steps to reproduce

I used the cp-all-in-one project to run Kafka for me.

1. Download & start confluent all-in-one.
 ```
git clone https://github.com/confluentinc/cp-all-in-one.git
cd cp-all-in-one/cp-all-in-one
docker compose up --build -d
```
1. Dowload the repo I provided
1. Run npm run start:dev

At this point you'll be able to see the messages about the consumer group being joined.

![Screen Shot 2023-08-08 at 3 38 45 PM](https://github.com/nestjs/nest/assets/69170267/f1b17a62-8aed-4414-a9d0-68616217f3ff)

### Expected behavior

In a hybrid application, when using `app.connectMicroservice` with Kafka and I pass `producerOnlyMode: true`, I expect that option to be respected. If I change my `app.module.ts` to:

```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ClientsModule, Transport } from '@nestjs/microservices';

@Module({
  imports: [
    ClientsModule.register([
      {
        name: 'kafka-client-test',
        transport: Transport.KAFKA,
        options: {
          client: {
            brokers: ['localhost:9092', 'kafka:29092'],
          },
          producer: {
            allowAutoTopicCreation: true,
          },
          producerOnlyMode: true,
        },
      },
    ]),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

and my `main.ts` to:

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();
```

I get the expected behavior and a consumer group isn't started in the logs. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : macOS Monterey
NodeJS Version : v18.13.0
NPM Version    : 8.19.3

[Nest CLI]
Nest CLI Version : 10.1.11

[Nest Platform Information]
platform-express version : 10.1.3
microservices version    : 10.1.3
schematics version       : 10.0.2
testing version          : 10.1.3
common version           : 10.1.3
core version             : 10.1.3
cli version              : 10.1.11

### Node.js version

18.13

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

In the [ClientKafka](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-kafka.ts#L120), there's logic around the `producerOnlyMode` when connecting to Kafka. But if you look in [ServerKafka](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-kafka.ts#L99), there's no logic here in `start` that refers to the `producerOnlyMode` property, even though it's a valid configuration option.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by bylethviva** [comment]
@kamilmysliwiec I submitted PR #12219 for this. I'll keep an eye out for any feedback.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12219
