### ISSUE TITLE
add NodeJS 20 to CI matrix

### ISSUE THREAD

**Issue by rbnayax** [nestjs/nest#12215]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Node 20 is still not LTS (will be in 2 months) but we want to start testing our servers with it, and we would be much more confident in the testing if your tests will run on it as well

### Describe the solution you'd like

Add node 20 to the CI matrix so we can be sure it works on it

### Teachability, documentation, adoption, migration strategy

just add node 20 to circle ci matrix

### What is the motivation / use case for changing the behavior?

Be prepared for node 20 LTS

**Comment by jmcdo29** [comment]
If it helps with confidence, I personally use node 20 on my personal project

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? :)

**Comment by rbnayax** [comment]
> Would you like to create a PR for this issue? :)

sure

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12218
