### ISSUE TITLE
New high-level API to integrate `SetMetadata`+`Reflector` service in a type-safe way

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#12224]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We have two abstractions (`Reflector` and `SetMetadata`) that are too low level to work together in a type-safe manner. Also, we've seen that the two are widely used together.

Here I'll focus only in one use case for `SetMetadata` which is having a user-made decorator factory like this:

![image](https://github.com/nestjs/nest/assets/13461315/3828a783-ae5c-4fc2-b498-37a9066ed047)

Although we can use `SetMetadata` multiple times for the same decorator factory, I didn't find a good (nor even feasible) API for such use case. Also, I don't think this should be common. Instead, we should leverage on `applyDecorators` helper in favor of the Single Responsibility Principle.

### Describe the solution you'd like

The solution I'm about to propose must meet the following requirements:

1. pretty easy to migrate from the weak-typed way
2. less boilerplate for both consumer and producer sides 
	- The `Reflector` API should infer the metadata key
4. increased coupling at type level
    - The `Reflector` API should infer the type (TS) of the metadata value, while also including `undefined` to it prevent runtime errors 
5. supports only one call for `SetMetadata` to enforce SRP
6. still support [decorator composition](https://docs.nestjs.com/custom-decorators#decorator-composition)
4. backwards-compatible. We can keep using the low level APIs along with this new one

A new utility function as a static method of `Reflector` helper class from `@nestjs/core` called `createDecorator` (or anything like that) that works almost like the #12107

And `Reflector#get` (and others) will now accept the decorator factory returned by that new method. So now `reflector.get` knows what is the metadata key and the metadata value type

```ts
export const Roles = Reflector.createDecorator<string[]>()
// `Roles.KEY` is a random unique ID for this metadata

@Roles(['admin'])
class Foo {
  @Roles(['owner'])
  // downside: since the type is string[], I don't think we can allow rest params/args anymore
  bar() {}
}

// ...
reflector.get(Roles, target) // string[] | undefined
```

We could even supply our own metadata key, to help on migrating "legacy" code:

```ts
export const Roles = Reflector.createDecorator<string[]>({ metadataKey: 'roles' })
```

### Teachability, documentation, adoption, migration strategy

maybe adding a new section at https://docs.nestjs.com/fundamentals/execution-context about this new way to create a class/method decorator factory for those that want to use `Reflector` to retrieve the metadata 

### What is the motivation / use case for changing the behavior?

what was described in the issue #12101 but narrowed down to the problem of how to properly type safe the metadata data while also avoiding duplicated references to metadata's key

---

## Disclaimer

I'm not 100% sure if the proposed solution is feasible but I'd like to give it a try only if it is accepted

**Comment by kamilmysliwiec** [comment]
It's feasible although we won't be able to fully replace `@SetMetadata` (which gives more flexibility). As discussed in some other issue, I'd love to see a PR for this! Should be pretty simple to create based on https://github.com/nestjs/nest/pull/12107 I can work on this too if needed

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/12237
