### ISSUE TITLE
Wrong file destination for prod script

### ISSUE THREAD

**Issue by batur** [nestjs/nest#12222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, I am trying to create an app with Nest.js. I used CLI to create a project. But when trying to deploy in Heroku faced an issue with `start:prod` script. It looks `dist/main`, but in dist folder doesn't have any main file. The main file inside of src folder(`dist/src/main`) I saw so many issues in StackOverflow or identical platforms. I think it can be fixed easily 

### Minimum reproduction code

https://github.com/batur/another-todo-api

### Expected behavior

`start:prod` script should be equal `dist/src/main`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

nest-cli

### NestJS version

10.1.11

### Packages versions

```json
    "@apollo/server": "^4.9.1",
    "@nestjs/apollo": "^12.0.7",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.0.8",
    "@nestjs/platform-express": "^10.0.0",
```

### Node.js version

16.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please search through existing closed issues.. We've explained this several times.
