### ISSUE TITLE
FAQ page isn't structured as a standard FAQ

### ISSUE THREAD

**Issue by moroccandeveloperlivingabroad** [nestjs/nest#12221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

As a new comer when I click on FAQ, I expect to see questions and their respective answers. 

The way FAQ is structured breed confusion and doesn't help gaining a quick overall understanding about the framework.

I'm reporting this as a bug and not as a feature because it is a mismatch between what the title means and what the content provides. 

Thank you in advance.

### Minimum reproduction code

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

N/A

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Do have any practical ideia on how to translate the current version to a question-based approach?

I may be wrong but I don't think that the traditional FAQ would fit that well for nestjs...

**Comment by kamilmysliwiec** [comment]
> I may be wrong but I don't think that the traditional FAQ would fit that well for nestjs...

I don't think so either

PRs are more than welcome though so if you have any ideas @moroccandeveloperlivingabroad, please go ahead and create one
