### ISSUE TITLE
emit debug logs (NEST_DEBUG mode) for invoked exception filters

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#12220]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

On big apps with a lot of exception filters, it could be hard to tell which filter has been evaluated for a given exception caught by Nest

### Describe the solution you'd like

like those logs that we have when using the env. var. `NEST_DEBUG=true`, I'd like to see some log that shows exception filter's name when some exception filter is invoked

Something that displays the exception filter class's name and, if feasiable, the host module.

Not sure if this use case doesn't fits the intention of `NEST_DEBUG`

### Teachability, documentation, adoption, migration strategy

we could mention somwhere in the docs site what the `NEST_DEBUG` mode does

---

we just need to update the following parts:

https://github.com/search?q=repo%3Anestjs/nest%20selectExceptionFilterMetadata&type=code

### What is the motivation / use case for changing the behavior?

from time to time people found weird behavior regarding exception filters. They usually don't know that one of their filters is being evaluated and thus changing the final response's payload. This could be even harder to grasp when it is a 3rd-party filter (a filter from some 3rd-party nestjs lib)

**Comment by kamilmysliwiec** [comment]
`NEST_DEBUG=true` isn't intended to log "post-initialization" runtime messages.

> They usually don't know that one of their filters is being evaluated and thus changing the final response's payload. 

I think it's fairly simple to achieve with inheritance (pseudo-code):

```
export class MyFilter extends ExistingFilter {
  catch(...) {
     this.logger.debug();
     return super.catch(...);
  }
}
```

Not sure if we need framework to log this ootb
