### ISSUE TITLE
Problem with PickType and PartialType decorators not working as expected

### ISSUE THREAD

**Issue by Nandeep2750** [nestjs/nest#12232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the PickType and PartialType decorators to create an input type, I'm encountering an error stating that the input type must define one or more fields. However, when manually defining the input type, the error does not occur, and the GraphQL schema is generated without issues.

### Minimum reproduction code

https://github.com/nestjs/mapped-types

### Steps to reproduce

**### 1. Using PickType and PartialType (Error):**

```
import { Field, HideField, ID, ObjectType } from '@nestjs/graphql';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import * as bcrypt from 'bcryptjs';
import { InternalServerErrorException } from '@nestjs/common';
import { ADMIN_CONFIG } from 'src/config/constants';

export type AdminDocument = HydratedDocument<Admin>;

@ObjectType()
@Schema({ timestamps: true })
export class Admin {
  @Field(() => ID)
  _id: string;

  @Field()
  @Prop({ required: true, type: String })
  firstName: string;

  @Field()
  @Prop({ required: true, type: String })
  lastName: string;

  @Field()
  @Prop({ required: true, type: String, unique: true })
  email: string;

  @HideField()
  @Prop({ required: true, type: String })
  password: string;

  @HideField()
  @Prop({ required: false, type: String })
  refreshToken: string;

  @HideField()
  @Prop({ required: false, type: Date })
  refreshTokenCreatedAt: Date;

  @HideField()
  @Prop({ type: Boolean, default: false })
  isDeleted: boolean;
}
```
```
import { InputType, Field, PartialType, PickType } from '@nestjs/graphql';
import { Admin } from '../entities/admin.entity';
@InputType()
export class UpdateAdminProfileInput extends PartialType(
  PickType(Admin, ['firstName', 'lastName', 'email', 'refreshToken'] as const),
) {}
```

**### 2. Manually Defining the Input Type (No Error):**
```
import { InputType, Field, PartialType, PickType } from '@nestjs/graphql';
@InputType()
export class UpdateAdminProfileInput {
  @Field(() => String, { nullable: true })
  firstName?: string;

  @Field(() => String, { nullable: true })
  lastName?: string;

  @Field(() => String, { nullable: true })
  email?: string;

  @Field(() => String, { nullable: true })
  refreshToken?: string;
}
```

### Expected behavior

I expected that both approaches, using PickType and PartialType decorators and manually defining the input types, would produce the same GraphQL input type structure.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### Packages versions

```json
"dependencies": {
    "@apollo/server": "^4.9.1",
    "@nestjs/apollo": "^12.0.7",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.0.8",
    "@nestjs/jwt": "^10.1.0",
    "@nestjs/mongoose": "^10.0.1",
    "@nestjs/passport": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "bcryptjs": "^2.4.3",
    "graphql": "^16.7.1",
    "joi": "^17.9.2",
    "passport-jwt": "^4.0.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "ts-morph": "^19.0.0",
    "uuid": "^9.0.0"
},
"devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
},
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> The PartialType() function takes an optional second argument that is a reference to a decorator factory. This argument can be used to change the decorator function applied to the resulting (child) class. If not specified, the child class effectively uses the same decorator as the parent class (the class referenced in the first argument). In the example above, we are extending CreateUserInput which is annotated with the @InputType() decorator. Since we want UpdateUserInput to also be treated as if it were decorated with @InputType(), we didn't need to pass InputType as the second argument. If the parent and child types are different, (e.g., the parent is decorated with @ObjectType), we would pass InputType as the second argument. For example:

https://docs.nestjs.com/graphql/mapped-types#partial

BTW not only `PartialType` takes this second argument but all of the existing mapped type functions
