### ISSUE TITLE
Incorrect type for return value of getAllAndMerge

### ISSUE THREAD

**Issue by ReneZeidler** [nestjs/nest#12231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Reflector method [`getAllAndMerge`](https://github.com/nestjs/nest/blob/85cc3869ee2a38f57075d59ac642eddf259ab016/packages/core/services/reflector.service.ts#L45-L76) returns type `TResult extends any[]`, implying that the return value will always be an array. However, it can also return objects (intended behavior) and primitive types (maybe unintended behavior).

```ts
getAllAndMerge<TResult extends any[] = any[], TKey = any>(metadataKey: TKey, targets: (Type<any> | Function)[]): TResult;
```

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-getallandmerge-bug?file=src%2Ftest-metadata.interceptor.ts

### Steps to reproduce

1. Open StackBlitz example
2. Click through examples 1 through 6 and obvserve the expected and actual output as well as the type of the output

### Expected behavior

1. Examples 1 and 2 return objects, which is what I would expect and which is explicitly handled in the code. The return type of `getAllAndMerge` should either be `TResult extends any` to match the current, actual behavior or `TResult extends any[] | object` if the bug from example 3 is also fixed.  
The default value of TResult can either remain `any[]` to match the most common use case and not break existing code, or be changed to the new wider type, which can cause type errors in existing code with no explicit type annotation for `TResult`.
2. Example 3: A single metadata value is always returned as is. Because two primitive values get merged into an array (example 6), I'd intuitively expect a single primitive to be wrapped in a one-element array, also supported by the current typing of the method. However, a single object should not be wrapped in an array (example 2).

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.1.0

### Packages versions

```ini
[System Information]
OS Version     : Linux 5.10
NodeJS Version : v18.12.1
NPM Version    : 9.6.6 

[Nest CLI]
Nest CLI Version : 10.1.10 

[Nest Platform Information]
platform-express version : 10.1.0
schematics version       : 10.0.1
swagger version          : 7.1.2
typeorm version          : 10.0.0
testing version          : 10.1.0
common version           : 10.1.0
config version           : 3.0.0
axios version            : 3.0.0
core version             : 10.1.0
cli version              : 10.1.10
 version                 : 1.9.1
```

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

These are technically two separate bugs (1. type doesn't match current behavior / 2. possibly incorrect return value for primitive metadata values). Since the resolutions of both issues affect each other, I decided to file them in just one issue.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for both issues?

**Comment by ReneZeidler** [comment]
Sure, I will take a look and try to get a dev env setup to create a PR.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12235
