### ISSUE TITLE
Using pnpm to install dependencies cannot start the project, using yarn is ok

### ISSUE THREAD

**Issue by TinsFox** [nestjs/nest#12246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

project failed to start

<img width="701" alt="image" src="https://github.com/nestjs/nest/assets/33956589/8aa144b9-bc2e-4389-bf02-4e3264437072">

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/27-scheduling

### Steps to reproduce

1. pnpm i
2. pnpm start

### Expected behavior

I hope he can work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "nest-typescript-starter",
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint '{src,apps,libs,test}/**/*.ts' --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "echo 'No e2e tests implemented yet.'"
  },
  "dependencies": {
    "@nestjs/common": "10.0.3",
    "@nestjs/core": "10.0.3",
    "@nestjs/platform-express": "10.0.3",
    "@nestjs/schedule": "3.0.1",
    "dotenv": "16.3.1",
    "reflect-metadata": "0.1.13",
    "rimraf": "5.0.1",
    "rxjs": "7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "10.0.5",
    "@nestjs/schematics": "10.0.1",
    "@nestjs/testing": "10.0.3",
    "@types/bull": "3.15.9",
    "@types/dotenv": "8.2.0",
    "@types/express": "4.17.17",
    "@types/jest": "29.5.3",
    "@types/node": "20.3.3",
    "@types/supertest": "2.0.12",
    "jest": "29.6.1",
    "prettier": "2.8.8",
    "supertest": "6.3.3",
    "ts-jest": "29.1.1",
    "ts-loader": "9.4.4",
    "ts-node": "10.9.1",
    "tsconfig-paths": "4.2.0",
    "@typescript-eslint/eslint-plugin": "5.60.1",
    "@typescript-eslint/parser": "5.60.1",
    "eslint": "8.42.0",
    "eslint-config-prettier": "8.8.0",
    "eslint-plugin-import": "2.27.5",
    "typescript": "5.1.6"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

pnpm@8.1.0

**Comment by Tony133** [comment]
I use pnpm v8.6.12 the latest released version is working perfectly ( see screenshot ), have you tried to update the version of pnpm ?
<img width="1969" alt="pnpm-install" src="https://github.com/nestjs/nest/assets/11542387/9565520a-3893-4274-b2f3-4e58fd722daf">

**Comment by TinsFox** [comment]
Hi @Tony133 , thank you for your reply.

It is indeed possible to use pnpm@8.6.12

**Comment by TinsFox** [comment]
Hey @Tony133 

I tried to create a new nestjs project, followed the steps in the documentation to add task scheduling and failed when the project started

👇 Here is the minimal repo:
https://github.com/TinsFox/task-scheduling-pnpm

```bash
git clone git@github.com:TinsFox/task-scheduling-pnpm.git
cd task-scheduling-pnpm
pnpm install
pnpm start
```

The error shown in the figure below appears

<img width="883" alt="image" src="https://github.com/nestjs/nest/assets/33956589/0b9cc18d-24c2-4a67-8b4f-7765064ca00c">

**Comment by TinsFox** [comment]
I also found a problem. In the example, there is no @types/cron dependency, but it needs to be installed in the document. which is correct

<img width="944" alt="image" src="https://github.com/nestjs/nest/assets/33956589/475e1134-94e7-4287-8af7-f1fce4bce223">

<img width="906" alt="image" src="https://github.com/nestjs/nest/assets/33956589/ab812510-8fd7-4f76-b4e2-1ea1281702b3">

**Comment by TinsFox** [comment]
> Hi @Tony133 , thank you for your reply.
> 
> It is indeed possible to use pnpm@8.6.12

This is only valid for https://github.com/nestjs/nest/tree/master/sample/27-scheduling

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Tony133** [comment]
> I also found a problem. In the example, there is no `@types/cron` dependency, but it needs to be installed in the document. which is correct
> 
> <img alt="image" width="944" src="https://user-images.githubusercontent.com/33956589/261903394-475e1134-94e7-4287-8af7-f1fce4bce223.png"> <img alt="image" width="906" src="https://user-images.githubusercontent.com/33956589/261903416-ab812510-8fd7-4f76-b4e2-1ea1281702b3.png">

@TinsFox verifying actually there would be no need for this `@types/cron` dependency anymore because it's deprecated (see here:https://www.npmjs.com/package/@types/cron) so the documentation should be updated.

In fact it should also be removed from the `@nestjs/schedule` package, there is a PR here: nestjs/schedule#1374 , only that it has conflicts and cannot be merged.

As for the error, maybe there's something inside the `@nestjs/schedule` package that's not working, but I still need to check.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/schedule/pull/1374
