### ISSUE TITLE
nestjs backend crash while sending large amount of websocket connection request using jmeter - need throttle for websocket connection request.

### ISSUE THREAD

**Issue by icetrust0212** [nestjs/nest#12240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Nestjs backend crash when I was doing performance test.
I am sending large amount of websocket connection request and it crashes backend.

### Minimum reproduction code

https://github.com/balance_capital/binary-options-backend

### Expected behavior

I should be able to implement throttle guard for websocket connection request in websocket gateway.
I know there is built-in websocket throttler in nestjs.
When I use it for @SubscribeEvent('message'), it worked well.
But I noticed it doesn't work for websocket connection request.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [X] <code>@nestjs/platform-socket.io</code>
- [X] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
     "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-socket.io": "^9.2.0",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/swagger": "^6.1.4",
    "@nestjs/throttler": "^4.2.1",
    "@nestjs/typeorm": "^9.0.1",
    "@nestjs/websockets": "^9.2.1",
```

### Node.js version

16.19.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
looks like you repository is private

**Comment by HariAcharya80** [comment]
@icetrust0212 repo is not publicly accessible.

**Comment by kamilmysliwiec** [comment]
Are you sure this is related to NestJS, not socket.io?

**Comment by mowatermelon** [comment]
Socket can be configured with maxConnections. Is the number of connections configured relatively low?

**Comment by kamilmysliwiec** [comment]
We rely on socket.io defaults
