### ISSUE TITLE
Consider adding Github Apps 

### ISSUE THREAD

**Issue by marcus-sa** [nestjs/nest#1226]
https://probot.github.io offers some great tools to improve the workflow.
For example https://probot.github.io/apps/move/

Instead of having to comment on an issue, telling them to recreate it in the correct repository, then close it and comment on it again, you could simply just move it.

**Comment by kamilmysliwiec** [comment]
"Transfer this issue" feature is now available in Github out-of-the-box (currently in "Beta"). Anyway, thanks for sharing this URL, I'll definitely make use of some of these apps :)
