### ISSUE TITLE
LazyModuleLoader - Cannot read properties of undefined (reading 'scanForModules')

### ISSUE THREAD

**Issue by andyslack** [nestjs/nest#12300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In my live project I noticed since upgrading to Nest v10 we are getting the following error when using the LazyModuleLoader

```
TypeError: Cannot read properties of undefined (reading 'scanForModules')
          at LazyModuleLoader.load ({project_root}/node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js:17:64)
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I created a new project for the minimum reproduction code here: https://codesandbox.io/p/sandbox/nestjs-lazyloader-issue-forked-wym2ln

### Minimum reproduction code

https://codesandbox.io/p/sandbox/nestjs-lazyloader-issue-forked-wym2ln

### Steps to reproduce

1. `npm install`
2. `npm run start`
3. See error when navigating to `/`

this should all happen automatically with `codesandbox.io`

### Expected behavior

Should return a random dog result from a 3rd party API when the issue is fixed.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

latest

### Packages versions

```json
 "dependencies": {
    "@nestjs/cli": "latest",
    "@nestjs/common": "latest",
    "@nestjs/core": "latest",
    "@nestjs/platform-express": "latest",
    "axios": "latest",
    "class-transformer": "latest",
    "class-validator": "latest",
    "module-alias": "latest",
    "reflect-metadata": "latest",
    "rxjs": "latest",
    "typescript": "latest"
  },
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
remove the `LazyModuleLoader` from your `providers` array. It's a built-in provider. You shouldn't be registering it by yourself.

![image](https://github.com/nestjs/nest/assets/13461315/8cad78b7-8b0b-4318-bc9d-ce0a6509728b)

**Comment by andyslack** [comment]
@micalevisk that was it, works now!! Thank you so much!
