### ISSUE TITLE
Link don't work

### ISSUE THREAD

**Issue by PatrykKuniczak** [nestjs/nest#12307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://docs.nestjs.com/microservices/redis#options

This link for 'ioredis' don't work:
https://luin.github.io/ioredis/index.html#RedisOptions

404 Not Found :)

### Minimum reproduction code

https://docs.nestjs.com/microservices/redis#options

### Expected behavior

Work properly

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by thanosngplus** [comment]
Hello!

I'm not a member of the Nest.js team, however I think that documentation issues should be opened at https://github.com/nestjs/docs.nestjs.com/issues.

I also assume that the correct link would be https://redis.github.io/ioredis/index.html#RedisOptions.

**Comment by kamilmysliwiec** [comment]
Fixed
