### ISSUE TITLE
Argument type Type<NestInterceptor> is not assignable to parameter type NestInterceptor | Function

### ISSUE THREAD

**Issue by iXingo** [nestjs/nest#12304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

nest-common Argument type [FileInterceptor](https://github.com/nestjs/nest/blob/923bd6afd150fa87b38e5730c3bfba63638b4e6d/packages/platform-express/multer/interceptors/file.interceptor.ts#L28)  **Type\<NestInterceptor\>** is not to  [UseInterceptors](https://github.com/nestjs/nest/blob/923bd6afd150fa87b38e5730c3bfba63638b4e6d/packages/common/decorators/core/use-interceptors.decorator.ts#L29C21-L29C37) parameter type **NestInterceptor | Function** 

![image](https://github.com/nestjs/nest/assets/3634305/b1369078-1ad6-467b-8df5-9bfd336f38d5)
![image](https://github.com/nestjs/nest/assets/3634305/68d7a54d-720a-454d-9453-25c56accf04d)

![image](https://github.com/nestjs/nest/assets/3634305/7bf9cda2-0164-4c0d-a35b-f80efc0b79cf)

### Minimum reproduction code

https://gist.github.com/iXingo/76b4f24c5b3f4f5e880b1c2ec9db0e36

### Steps to reproduce

   Use the following package
```json
 "@nestjs/common": "^10.2.2",
    "@nestjs/platform-express": "^10.2.2",
```

```javascript
  @Post('upload')
  @UseInterceptors(FileInterceptor('file'))
  uploadFile(@UploadedFile() file: Express.Multer.File) {
    console.log(file);
    if (!file) {
      throw new BadRequestException('No file uploaded');
    }

    console.log(file.originalname);
    console.log(file.filename);
    console.log(file.path);

    return file.filename;
  ```

### Expected behavior

convert **Type\<NestInterceptor\>** to parameter type **NestInterceptor | Function**

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

none

### NestJS version

10.2.2

### Packages versions

```json
    "@nestjs/common": "^10.2.2",
    "@nestjs/platform-express": "^10.2.2",
```

### Node.js version

18.16.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

none

**Comment by micalevisk** [comment]
I didn't manage to reproduce this. 

![image](https://github.com/nestjs/nest/assets/13461315/d06b7bb7-5ff5-4fa6-8a26-491db05406f9)


How your tsconfig file looks like?

**Comment by iXingo** [comment]
thanks for your quick response, I updated the typescript version, and the issue was gone.

**Comment by andkom** [comment]
what typescript version? i have 5.2.2 and have the same issue

**Comment by iXingo** [comment]
> what typescript version? i have 5.2.2 and have the same issue

In fact. it is not resolved. I switched to VScode now. it still shows a warning on Webstorm.
