### ISSUE TITLE
NestJS jwt-passport Authentication

### ISSUE THREAD

**Issue by CountZero1981** [nestjs/nest#1232]
Hello,
I'm trying to implement a distributable JWT authentication library to use it in my projects. Did everything like in the docs, but getting an error `Error: Unknown authentication strategy "jwt"`.

The code:

jwt.auth.module.ts:
```
import {Module, DynamicModule} from '@nestjs/common';
import {JwtModule} from '@nestjs/jwt';
import {JwtStrategy} from './jwt.strategy';
import {PassportModule} from '@nestjs/passport';
import {ConfigService} from "./config.service";
import {JwtOptions} from "./interfaces/jwt.options";

@Module({
})

export class JwtAuthModule {
  static forRoot(jwtOptions): DynamicModule {
    return {
      module: JwtAuthModule,
      imports: [
        JwtModule.register(jwtOptions),
        PassportModule.register({defaultStrategy: 'jwt'}),
      ],
      providers: [
        JwtStrategy,
        {
          provide: ConfigService,
          useValue: new ConfigService(jwtOptions),
        }
      ],
      exports: [ConfigService, JwtStrategy]
    };
  }
}
```

jwt.strategy.ts:
```
import {ExtractJwt, Strategy} from 'passport-jwt';
import {PassportStrategy} from '@nestjs/passport';
import {Injectable} from '@nestjs/common';
import {JwtPayload, User} from './interfaces';
import {ConfigService} from "./config.service";
import {Inject} from "@nestjs/common";
const passport = require("passport");

@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy, 'jwt') {
  constructor(private readonly configService: ConfigService) {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      secretOrKey: configService.get('secretOrPrivateKey'),
    });
    // to check that a strategy is really instantiated - yes, I see this in the output
    console.log('JwtStrategy constructor called');
    // and I even tried to explicitly register my strategy in a passport
    passport.use('jwt', this);
  }

  async validate(payload: JwtPayload): Promise<User> {
     return {
      uuid: payload.uuid,
      email: payload.email,
    }
  }
}
```

used it in a project in app.module.ts:
```
import { Module, NestModule, HttpModule } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { environment } from './environments';
import { AuthModule } from './auth/auth.module';
import { PermissionModule } from './permission/permission.module';
import {JwtAuthModule} from '@pe/nest-kit';
import {JwtModule} from '@nestjs/jwt';
import {PassportModule} from '@nestjs/passport';

@Module({
  imports: [
    JwtModule.register(environment.jwtOptions),
    PassportModule.register({defaultStrategy: 'jwt'}),
    JwtAuthModule.forRoot(environment.jwtOptions),
    HttpModule,
    AuthModule,
    PermissionModule,
    MongooseModule.forRoot(environment.mongodb),
  ],
})
export class ApplicationModule implements NestModule {
  configure() {
  }
}
```

the output:

> [nodemon] starting `ts-node src/main.ts`
> [Nest] 30794   - 25.10.2018, 12:02:14   [NestFactory] Starting Nest application...
> JwtStrategy constructor called
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] ApplicationModule dependencies initialized +42ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] PassportModule dependencies initialized +0ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] MongooseModule dependencies initialized +0ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] JwtModule dependencies initialized +0ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] JwtAuthModule dependencies initialized +1ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] HttpModule dependencies initialized +0ms
> (node:30794) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] MongooseCoreModule dependencies initialized +14ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] MongooseModule dependencies initialized +7ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] MongooseModule dependencies initialized +1ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] MongooseModule dependencies initialized +0ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] UserModule dependencies initialized +0ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] PermissionModule dependencies initialized +1ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [InstanceLoader] AuthModule dependencies initialized +0ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [NestMicroservice] Nest microservice successfully started +18ms
> init() method
> bindEvents() method
> [Nest] 30794   - 25.10.2018, 12:02:14   [RoutesResolver] AuthController {/api/auth}: +17ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [RouterExplorer] Mapped {/login, POST} route +2ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [RoutesResolver] PermissionController {/api/check}: +0ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [RouterExplorer] Mapped {/:businessUuid/:entity/:action, GET} route +1ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [RoutesResolver] PermissionEventController {/api/permission-event}: +1ms
> [Nest] 30794   - 25.10.2018, 12:02:14   [NestApplication] Nest application successfully started +2ms
> app started at port 3020
> client is ready
> [Nest] 30794   - 25.10.2018, 12:02:21   [ExceptionsHandler] Unknown authentication strategy "jwt" +7611ms
> Error: Unknown authentication strategy "jwt"
>     at attempt (/home/countzero/workspace/permissions/node_modules/passport/lib/middleware/authenticate.js:186:37)
>     at authenticate (/home/countzero/workspace/permissions/node_modules/passport/lib/middleware/authenticate.js:362:7)
>     at Promise (/home/countzero/workspace/permissions/node_modules/@nestjs/passport/dist/auth.guard.js:83:3)
>     at new Promise (<anonymous>)
>     at /home/countzero/workspace/permissions/node_modules/@nestjs/passport/dist/auth.guard.js:75:83
>     at MixinAuthGuard.<anonymous> (/home/countzero/workspace/permissions/node_modules/@nestjs/passport/dist/auth.guard.js:47:36)
>     at Generator.next (<anonymous>)
>     at /home/countzero/workspace/permissions/node_modules/@nestjs/passport/dist/auth.guard.js:19:71
>     at new Promise (<anonymous>)
>     at __awaiter (/home/countzero/workspace/permissions/node_modules/@nestjs/passport/dist/auth.guard.js:15:12)
>     at MixinAuthGuard.canActivate (/home/countzero/workspace/permissions/node_modules/@nestjs/passport/dist/auth.guard.js:40:20)
>     at GuardsConsumer.tryActivate (/home/countzero/workspace/permissions/node_modules/@nestjs/core/guards/guards-consumer.js:13:34)
>     at canActivateFn (/home/countzero/workspace/permissions/node_modules/@nestjs/core/router/router-execution-context.js:97:59)
>     at /home/countzero/workspace/permissions/node_modules/@nestjs/core/router/router-execution-context.js:47:37
>     at /home/countzero/workspace/permissions/node_modules/@nestjs/core/router/router-proxy.js:8:23
>     at Layer.handle [as handle_request] (/home/countzero/workspace/permissions/node_modules/express/lib/router/layer.js:95:5)
>

**Comment by barretojs** [comment]
very strange... i did a very similar code here and it's working fine. this @pe/nest-kit repository, is it exporting the JwtAuth correctly? have you tried using the JwtAuth in the same code base? this is my only guess without looking in the rest of the code, because your code looks correct.
also you don't need to register the Passport and JwtModule twice.

**Comment by CountZero1981** [comment]
solved.
in PHP, we have one dependency tree for whole project. in npm each package has its own dependency subtree, e. g.:
--passport
--@pe/nest-kit
----passport 
nest-kit uses objects from ----passport, but the root project uses objects of the type with the same name, but actually this is another type for the nodejs compiler. the solution is to re-export AuthGuard from passport through @pe/nest-kit, and it works.
