### ISSUE TITLE
Add Search to the documentation

### ISSUE THREAD

**Issue by ahmedmagdy11** [nestjs/nest#12329]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Why there is no search in the main documentation itself? have you seen Laravel documentation 
- easy to understand
- A lot of examples 
- Can actually search for what you want

Please fix the documentation to make our life easier thanks

### Describe the solution you'd like

- Add search bar
- Add more example 
- Go into details

### Teachability, documentation, adoption, migration strategy

the latest version

### What is the motivation / use case for changing the behavior?

Being +3 years backend and i find the documentation very hard it's not beginner friendly at all

**Comment by kamilmysliwiec** [comment]
![image](https://github.com/nestjs/nest/assets/23244943/b5e057d4-efe3-49db-85fa-be067fddbb21)

?

**Comment by ahmedmagdy11** [comment]
@kamilmysliwiec  this is not appearing in my browser i am using Firefox via Ubuntu 22
![image](https://github.com/nestjs/nest/assets/53973228/97076eb4-49d6-404b-8c88-440dacc42186)
