### ISSUE TITLE
Nest can't resolve dependencies of the MessageResolver (?, PubSub).

### ISSUE THREAD

**Issue by AmirAliEidivandi** [nestjs/nest#12323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I wrote a chat application and it is integrated with Nest and GraphQL. Now I want to add the resolvers of the message module, but it gives this error:

![image](https://github.com/nestjs/nest/assets/86082526/58c8b866-b80f-44d6-898d-d4f4a27c3436)

### message.module.ts:
```
import { Module, forwardRef } from '@nestjs/common';
import { MessageResolver } from './message.resolver';
import { MessageService } from './message.service';
import { MongooseModule } from '@nestjs/mongoose';
import { Message, MessageSchema } from './models/message.model';
import { UserModule } from 'src/user/user.module';
import { GroupModule } from 'src/group/group.module';
import { PubSub } from 'graphql-subscriptions';

@Module({
  imports: [
    MongooseModule.forFeature([{ name: Message.name, schema: MessageSchema }]),
    forwardRef(() => UserModule),
    GroupModule,
  ],
  providers: [MessageResolver, MessageService, PubSub],
  exports: [MessageService],
})
export class MessageModule {}
```

### message.resolver.ts:
```
import { PubSub } from 'graphql-subscriptions';
import { MessageService } from './message.service';
import { Inject } from '@nestjs/common';
import { Resolver, Query, Mutation, Args } from '@nestjs/graphql';
import { Message } from './models/message.model';
import { CreateMessageInput } from './dto/message.input';

@Resolver((of) => Message)
export class MessageResolver {
  constructor(
    @Inject('MessageService')
    private readonly service: MessageService,
    @Inject('PubSub') private readonly pubSub: PubSub,
  ) {}

  @Query((returns) => [Message])
  async getMessagesByUserId(
    @Args('userId', { type: () => String }) userId: string,
  ): Promise<Message[]> {
    return this.service.getMessagesByUserId(userId);
  }

  @Mutation((returns) => Message)
  async createMessage(
    @Args('createMessageInput') createMessageInput: CreateMessageInput,
  ): Promise<Message> {
    const newMessage = this.service.create(createMessageInput);
    this.pubSub.publish('messageAdded', { messageAdded: newMessage });

    return newMessage;
  }
}
```

### Minimum reproduction code

https://github.com/nestjs/nest/issues/2601

### Steps to reproduce

1. npm run start:dev
2. [Nest] 25476  - 08/31/2023, 11:03:55 AM     LOG [NestFactory] Starting Nest application...
[Nest] 25476  - 08/31/2023, 11:03:55 AM     LOG [InstanceLoader] AppModule dependencies initialized +29ms
[Nest] 25476  - 08/31/2023, 11:03:55 AM     LOG [InstanceLoader] MongooseModule dependencies initialized +0ms
[Nest] 25476  - 08/31/2023, 11:03:55 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the MessageResolver (?, PubSub). Please make sure that the argument MessageService at index [0] is available in the MessageModule context.

Potential solutions:
- Is MessageModule a valid NestJS module?
- If MessageService is a provider, is it part of the current MessageModule?
- If MessageService is exported from a separate @Module, is that module imported within MessageModule?
  @Module({
    imports: [ /* the Module containing MessageService */ ]
  })

### Expected behavior

I want to test queries and mutations in http://localhost:8000/graphql
but not working and have an error

I read nest document but it didn't help: https://docs.nestjs.com/faq/common-errors

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^9.0.0

### Packages versions

```json
"dependencies": {
    "@apollo/server": "^4.9.2",
    "@nestjs/apollo": "^12.0.7",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^12.0.8",
    "@nestjs/mongoose": "^10.0.1",
    "@nestjs/platform-express": "^9.0.0",
    "bcrypt": "^5.1.1",
    "dotenv": "^16.3.1",
    "graphql": "^16.8.0",
    "graphql-subscriptions": "^2.0.0",
    "jsonwebtoken": "^9.0.1",
    "mongoose": "^7.5.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/mongoose": "^5.11.97",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  }
```

### Node.js version

18.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
