### ISSUE TITLE
Error: Cannot find module 'src/app.module'

### ISSUE THREAD

**Issue by itbaduc** [nestjs/nest#12322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

in NestJs v10.2.2 when start with SWC it show error **"Cannot find module 'src/app.module'"** but when run without SWC it run normal

### Minimum reproduction code

/

### Expected behavior

Start Nest Application

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^10.2.2",
    "@nestjs/core": "^10.2.2",
    "@nestjs/platform-express": "^10.2.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
```

### Node.js version

18.16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest-cli/pull/2271
