### ISSUE TITLE
Router module does't distinguish dynamic modules

### ISSUE THREAD

**Issue by Thore1954** [nestjs/nest#12326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Consider a dynamic module that registers some controllers. I want to define a dynamic prefix for the controllers:
```ts
@Module({
  controllers: [HealthController, MetricsController],
})
export class MonitoringModule {
  static register({ path, contextKey }): DynamicModule {
    return {
      module: MonitoringModule,
      imports: [
        RouterModule.register([
          {
            path,
            module: MonitoringModule,
          },
        ]),
      ],
      providers: [
        {
          provide: 'CONTEXT_KEY',
          useValue: contextKey,
        },
      ],
    };
  }
}
```
However, when I import it into my feature modules, all prefixes are overwritten by the final module:
```ts
@Module({
  imports: [
    MonitoringModule.register({
      path: 'a',
      contextKey: 'feature a',
    }),
  ],
})
export class FeatureAModule {}
```
```ts
@Module({
  imports: [
    MonitoringModule.register({
      path: 'b',
      contextKey: 'feature b',
    }),
  ],
})
export class FeatureBModule {}
```
```
[Nest] 52  - 08/31/2023, 12:40:38 PM     LOG [RoutesResolver] HealthController {/b/health}: +2ms
[Nest] 52  - 08/31/2023, 12:40:38 PM     LOG [RoutesResolver] MetricsController {/b/metrics}: +1ms
[Nest] 52  - 08/31/2023, 12:40:38 PM     LOG [RoutesResolver] HealthController {/b/health}: +1ms
[Nest] 52  - 08/31/2023, 12:40:38 PM     LOG [RoutesResolver] MetricsController {/b/metrics}: +0ms
```

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-tw6dzj

### Expected behavior

The router module should distinguish dynamic modules instead of overwriting:
```
[Nest] 52  - 08/31/2023, 12:40:38 PM     LOG [RoutesResolver] HealthController {/a/health}: +2ms
[Nest] 52  - 08/31/2023, 12:40:38 PM     LOG [RoutesResolver] MetricsController {/a/metrics}: +1ms
[Nest] 52  - 08/31/2023, 12:40:38 PM     LOG [RoutesResolver] HealthController {/b/health}: +1ms
[Nest] 52  - 08/31/2023, 12:40:38 PM     LOG [RoutesResolver] MetricsController {/b/metrics}: +0ms
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
  "@nestjs/common": "^10.0.0",
  "@nestjs/core": "^10.0.0",
  "@nestjs/platform-express": "^10.0.0",
  "reflect-metadata": "^0.1.13",
  "rxjs": "^7.8.1"
}
```

### Node.js version

16.20.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
