### ISSUE TITLE
infer nestjs application type from adapter being used (for native ones) on `NestFactory.create`

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#12338]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

If we want a type safe Nest app when using `NestFactory.create` we must supply the type arg

For `@nestjs/platform-express`, it is `NestExpressApplication`  
For `@nestjs/platform-fastify`, it is `NestFastifyApplication`  

our code looks like this:

```ts
const app = await NestFactory.create<NestExpressApplication>(AppModule)
// or
const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter())
```

### Describe the solution you'd like

I'd like to avoid the redundancy on types for that static method.

if I use this:

```ts
const app = await NestFactory.create(AppModule)
// or
const app = await NestFactory.create(AppModule, opts)
```

the type arg `T` here:

https://github.com/nestjs/nest/blob/2d13d081d8f0bf7fe592a7d2762baf568403803c/packages/core/nest-factory.ts#L64

should be `NestExpressApplication`.

If I use this:

```ts
const app = await NestFactory.create(AppModule, new FastifyAdapter())
// or
const app = await NestFactory.create(AppModule, new FastifyAdapter(), opts)
```

the type arg `T` should be `NestFastifyApplication`

If the adapter is not one of those from `@nestjs/*`, `T` should remain as `INestApplication`. 

---

I'm not sure if this is feasible yet but I'll give it a try if this FR is accepted

### Teachability, documentation, adoption, migration strategy

we can can omit the type arg from the docs

I guess this might introduce a breaking change for those that are wrongly invoking some method that is not avaiable for the adapter they're using

### What is the motivation / use case for changing the behavior?

It's a minor DX improvement. Less boilerplate. One doesn't need to know that `NestFactory.create` has a type arg.

I believe that version will be easier to reason about for TS newcomers. Sometimes people ask why do we need to supply that "twice" just because they don't know that types are erased at runtime.

**Comment by kamilmysliwiec** [comment]
This is how it originally worked and was overhauled to reduce the static circular relationships between Nest packages.
