### ISSUE TITLE
@ApiBearerAuth() can't throw 403 forbidden

### ISSUE THREAD

**Issue by onlyhasbi** [nestjs/nest#12337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am creating role based authentication and when adding @ApiBearerAuth() on one of the function handler classes and testing it with wrong role token but then instead of throwing a forbidden error, it results in a successful response. is this a bug ? 
  

![2](https://github.com/nestjs/nest/assets/11315625/6cf72608-ddbd-4b80-83c6-d5d590d39c2b)

![1](https://github.com/nestjs/nest/assets/11315625/74ca243f-1587-4147-9c56-28adc3a6e992)

  

### Minimum reproduction code

https://pastebin.com/Akw2vikV

### Expected behavior

it should return forbidden error

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/swagger

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/jwt": "^10.1.0",
    "@nestjs/passport": "^10.0.1",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/swagger": "^7.1.8",
    "@nestjs/typeorm": "^10.0.0",
    "@types/passport-jwt": "^3.0.9",
    "argon2": "^0.31.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "dayjs": "^1.11.9",
    "jwt-decode": "^3.1.2",
    "nest-csv-parser": "^2.0.4",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.17"
  },
  "devDependencies": {
    "@compodoc/compodoc": "^1.1.21",
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.82",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.5.7",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "cross-env": "^7.0.3",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "pg": "^8.11.3",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by riadhriadh** [comment]
the token format that you have already inserted is incorrect, you must delete the {

**Comment by micalevisk** [comment]
it's not a bug; `@ApiBearerAuth()` and others `@ApiX` decorators changes nothing on how your app behaves. They are for documentation sake only. You should implement the functionality yourself.

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
