### ISSUE TITLE
NestJS - Fastify - Cookies : Type 'FastifyCookie' is not assignable to type 'FastifyPluginCallback<FastifyCookieOptions>'.

### ISSUE THREAD

**Issue by befabry** [nestjs/nest#12339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

First, thanks for the great tools.

TS complains when I try to follow these directives : [Cookies - Use with Fastify](https://docs.nestjs.com/techniques/cookies#use-with-fastify)

I followed [this](https://github.com/fastify/fastify-cookie#typescript-example) as well to initiate the cookies and removed the await.

In my `main.ts` I have with something like this :

    import { fastifyCookie } from '@fastify/cookie';
    import { NestFactory } from '@nestjs/core';
    import {
      FastifyAdapter,
      NestFastifyApplication,
    } from '@nestjs/platform-fastify';
    import { ValidationPipe } from '@nestjs/common';
    import { AppModule } from './app.module';

    async function bootstrap() {
      const app = await NestFactory.create<NestFastifyApplication>(
        AppModule,
        new FastifyAdapter(),
      );

      //eslint-disable-next-line @typescript-eslint/ban-ts-comment
      //@ts-ignore
      app.register(fastifyCookie);
      app.useGlobalPipes(new ValidationPipe({ whitelist: true }));

      await app.listen(3001, '0.0.0.0');
    }
    bootstrap();

I have to use `@ts-ignore` else it gives me a `Type 'FastifyCookie' is not assignable to type 'FastifyPluginCallback<FastifyCookieOptions>'.` but it's working

The error :

    Argument of type 'FastifyCookie' is not assignable to parameter of type 'FastifyPluginCallback<FastifyCookieOptions> | FastifyPluginAsync<FastifyCookieOptions> | Promise<...> | Promise<...>'.
      Type 'FastifyCookie' is not assignable to type 'FastifyPluginCallback<FastifyCookieOptions>'.
        Types of parameters 'instance' and 'instance' are incompatible.
          Type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>' is missing the following properties from type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>': serializeCookie, parseCookie, signCookie, unsignCookie

### Minimum reproduction code

https://github.com/La-Fabryck/caddie-backend-nest

### Steps to reproduce

1. docker compose run --rm backend npm i
1. cp .env.sample .env
1. cp .env.sample .env.development
1. docker compose run --rm backend npx prisma db seed
1. docker compose up

### Expected behavior

I shouldn't have to use `@ts-ignore`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

fastify

### NestJS version

10.2.4

### Packages versions

```json
{
  "name": "caddie-backend-nest",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@fastify/cookie": "^9.0.4",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.1",
    "@nestjs/core": "^10.0.0",
    "@nestjs/jwt": "^10.1.1",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-fastify": "^10.0.0",
    "@prisma/client": "^5.2.0",
    "bcrypt": "^5.1.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "fastify": "^4.22.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@babel/plugin-proposal-throw-expressions": "^7.22.5",
    "@faker-js/faker": "^8.0.2",
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.78",
    "@types/bcrypt": "^5.0.0",
    "@types/jest": "28.1.8",
    "@types/node": "^18.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-import-resolver-typescript": "^3.6.0",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "prisma": "^5.2.0",
    "source-map-support": "^0.5.20",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  },
  "prisma": {
    "seed": "ts-node prisma/seed/index.ts"
  }
}

```

### Node.js version

18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
This is almost always a side effect of two versions of fastify installed. The one from `fastify`, and the one from `@nestjs/platform-fastify`

**Comment by befabry** [comment]
> npm ls fastify
    ├─┬ @nestjs/platform-fastify@10.2.4
    │ └── fastify@4.22.0
    └── fastify@4.22.2
