### ISSUE TITLE
A particular arrangement of injectable dependencies causes one of them to have instance methods called before constructor

### ISSUE THREAD

**Issue by SimpleCreations** [nestjs/nest#12332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I inject dependencies in a certain way, one of the dependency's constructor is not called before its instance methods, resulting in instance fields becoming uninitialized. 

### Minimum reproduction code

https://github.com/SimpleCreations/nestjs-dependency-injection-issue-repro

### Steps to reproduce

1. Clone the reproduction repo
2. Run `yarn`
3. Run `yarn start:dev`

You will see an error thrown by [this line](https://github.com/SimpleCreations/nestjs-dependency-injection-issue-repro/blob/main/src/product/services/category.service.ts#L22), which [shouldn't happen if the service's constructor has been called](https://github.com/SimpleCreations/nestjs-dependency-injection-issue-repro/blob/main/src/product/services/category.service.ts#L15).

4. Uncomment [this line](https://github.com/SimpleCreations/nestjs-dependency-injection-issue-repro/blob/main/src/product/resolvers/category.resolver.ts#L11) (and don't forget to add an import statement for `MyService1`)

You will see that this seemingly unrelated change caused the error to disappear.

### Expected behavior

The service's constructor shouldn't be called (or not called) based on which unrelated dependencies are injected. (Or perhaps instance methods shouldn't be called at all before the constructor is called.)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.3

### Packages versions

```json
    "@apollo/server": "4.9.3",
    "@as-integrations/fastify": "2.1.0",
    "@nestjs/apollo": "12.0.7",
    "@nestjs/common": "10.2.3",
    "@nestjs/core": "10.2.3",
    "@nestjs/graphql": "12.0.8",
    "@nestjs/platform-fastify": "10.2.3",
```

### Node.js version

20.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
There's a circular relationship between your request-scoped providers - this is considered a bad practice and advised against in the documentation. The instantiation order is not guaranteed in this case (which makes sense because there's no way to determine which one should be instantiated first + all services have to be instantiated dynamically - on async signal) so this may happen.

Please search through some of our old issues on this (this has been discussed several times in the past).
