### ISSUE TITLE
The reflect-metadata version is very old. Is there any replacement packages?

### ISSUE THREAD

**Issue by dorseysen** [nestjs/nest#12345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The reflect-metadata version is very old. Is there any replacement packages?

### Minimum reproduction code

https://github.com/nestjs/nest/blob/master/package.json

### Steps to reproduce

"@nestjs/core": "^10.0.0",

### Expected behavior

Is there a replacement mode?

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"@nestjs/core": "^10.0.0",
```

### Node.js version

18.14.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
old but well tested, I'd say:

![image](https://github.com/nestjs/nest/assets/13461315/f920153c-f6e1-4fa4-8368-d0b2cb31059d)
![image](https://github.com/nestjs/nest/assets/13461315/1cfd1015-9b65-4664-aca1-47a336ab1727)

**Comment by dorseysen** [comment]
I see, However, some companies may have restrictions on the use of open source software. For example, open source third-party software is updated too frequently or has not been updated for a long time (more than three years).
@micalevisk @jmcdo29

**Comment by dorseysen** [comment]
![image](https://github.com/nestjs/nest/assets/33741833/429f64fd-23c3-4a5c-be6e-9abe868a7423)

Or another way, whether it can be used as an indirect dependency, the “peerDependencies” version is installed by the user overwrite.

**Comment by kamilmysliwiec** [comment]
As wine ages, its taste usually gets better. Old doesn't mean worse
