### ISSUE TITLE
Nest build doesn't respect exclude with swc

### ISSUE THREAD

**Issue by iamchathu** [nestjs/nest#12340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When nest build run with enabling swc in it generates `spec.js` files.

### Minimum reproduction code

New project

### Expected behavior

I tested without swc and seems It works without issues

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/cli

### NestJS version

10.2.4"

### Packages versions

```json

```

### Node.js version

18

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by powerfulyang** [comment]
https://swc.rs/docs/configuration/compilation#exclude

**Comment by powerfulyang** [comment]
add `"exclude": [".*\\.spec\\.ts$"],` to `.swcrc`
