### ISSUE TITLE
[CLI] Provide bun as a package manager in the startup menu when we create a new nest project

### ISSUE THREAD

**Issue by amm834** [nestjs/nest#12359]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

```
nest new foo
Choose Package Manager
> npm
> yarn 
> pnpm 
> bun ✅
```

### Describe the solution you'd like

`bun` is faster than `pnpm` that is I am using in my daily work.

### Teachability, documentation, adoption, migration strategy

https://bun.sh/

```
cd foo
bun install
```

### What is the motivation / use case for changing the behavior?

It's faster and reduce installation time.

**Comment by jmcdo29** [comment]
1) use the [cli repo](https://github.com/nestjs/nest-cli)
2) [Bun doesn't current have `emitDecoratorMetadata` support](https://github.com/oven-sh/bun/issues/1641#issuecomment-1712700944) which Nest _heavily_ relies on, so we can't really add a runtime/package-manager that doesn't really work with Nest

**Comment by amm834** [comment]
Yes,I know bun did not support emit decorator. But what I would like to see is installing packages and I am not intended to run  nest application with bun.
I am apologize for opening issue on wrong repo. I first think nest uses mono repo and packages cli in it. Sorry for that.

**Comment by brayden-wong** [comment]
if you use `bunx  create nest <app name>` it will install all requirements to create a nestjs application using npm, which you can easily transfer to use either yarn or pnpm
