### ISSUE TITLE
Zod schema.parse method return Partial object (every field is nullable) in nestjs app

### ISSUE THREAD

**Issue by topperspal** [nestjs/nest#12356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Suppose a user schema as follows
```js
import { z } from "zod";

const UserSchema = z.object({
  name: z.string(),
});

type User = z.infer<typeof UserSchema>;
```

Here type **User** is equivalent to

```js
type User = {
    name?: string;
}
```

instead of 
```js
type User = {
    name: string;
}
```

What is wrong with zod here, I want name field to be non nullable but it is not here? It works pretty much fine on both simple **nodejs app** and **deno**, but it does not work in **nestjs** app.

### Minimum reproduction code

https://github.com/nestjs/nest/files/12546251/nest-app.zip

### Steps to reproduce

1. Create a new nest app
```terminal
nest nest testzod
```

2. create a schema file with user schema
```js 
import { z } from "zod";

const UserSchema = z.object({
  name: z.string(),
});

type User = z.infer<typeof UserSchema>;
```

### Expected behavior

```js
type User = {
    name: string;
}

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

zod, kysely

### NestJS version

_No response_

### Packages versions

```json
{
  "name": "nest-app",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@prisma/client": "^5.2.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "kysely": "^0.26.3",
    "nanoid": "^3.3.6",
    "pg": "^8.11.3",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "zod": "^3.22.2"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/pg": "^8.10.2",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "prisma": "^5.2.0",
    "prisma-kysely": "^1.7.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

Kysely type intellisence is also not working properly.

Check it-
[nest-app.zip](https://github.com/nestjs/nest/files/12546251/nest-app.zip)

**Comment by JonLopezGarcia** [comment]
@topperspal You must enable `strictNullChecks` in your `tsconfig.json`

<img width="342" alt="image" src="https://github.com/nestjs/nest/assets/22107965/890d039a-8bed-4e77-bb8b-63f28fedbd9e">

**Comment by G-Shock-74** [comment]
Hi ***@***.***,<br><br>
		You are receiving this email because you requested access to review and/or receive the data that Unity collects when you are playing . To access this information, request your data report or exercise your privacy rights, please click follow this link: https://u16634401.ct.sendgrid.net/ls/click?upn=SJOJK4-2BEKZguH1osxnZkEuIO9INCZbUc1yCzwRnWWhGGyhEGMZ3A-2F1Z0HNXKwlVQauPRuHcEOCbnReT-2FlqFw2LjWgANAot5EX55sNkCpTER6nmIVxgxHjiWGTPxtoikXBxZO_U31jt5HgHBh7k3Grc5s4l-2BeWkSuRWO9jYH7meIZR2pkkMyk5DmhPjHL-2BbyUSMv-2FOXceN7U1w4xh1rnIWwtV-2FEArSKqDSo5N7ypV642fgsDMQR0q56LhlpL3KNu-2FK8FKVjxWkbYDtH3jj3cQ6EyFR-2F5nD3AnkvIbnQ8FV9canuinp7kGPzMhGUOvhCmmG4xb4gNiT5w9B5iii8G24l6bvNi2DLLH6mpiTvTEmGOLGdGQPmCPFJQg5Q1l9Y3tbURCi2yhlj4myBRylaRnN9NP-2B7g-3D-3D <br><br>
		Please note that for security purposes this link will expire in 48 hours. If your link expires, make a new request and we will send you a new link.<br><br>
		At Unity, we care deeply about your privacy rights and the safety of your personal data. If you have any questions or concerns about data collection and Unity, please email us at <a ***@***.******@***.***</a>.<br><br>
		Thank you,<br>
		Unity Technologies

**Comment by micalevisk** [comment]
That's not related with Nest.
