### ISSUE TITLE
Upgrading socket.io NestJS packages from v8 to v9 breaks socket integration

### ISSUE THREAD

**Issue by rauldeheer** [nestjs/nest#12353]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

v8 -> v9

### Describe the regression

Hi!

I've upgraded our whole application from NestJS v8 to NestJS v10 recently. Everything was working fine after the migration and I read the migration guides for v8 -> v9 and v9 -> v10. 

Upon further inspection of my application I found out that the socket integration was completely broken. The socket connection was disconnected before even connecting. After searching the whole internet, I wasn't really able to find anything. I also inspected the migration guides a second time but nothing in there states anything about web sockets.

After downgrading only `@nestjs/platform-socket.io` and `@nestjs/websockets` to `8.4.7`, everything started working again. I also tried v9 first, but this also didn't work. So I suppose this means that migrating from v8 -> v9 breaks the socket functionality in some cases.

So I would like to know why this breaks so I can fix it locally and update the migration guide through a PR.

### Input code

```ts

```

### Expected behavior

I expect the application to work after upgrading the NestJS socket packages to v9/v10. Additional changes that one has to make to make it work should be documented in the migration guide.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by rauldeheer** [comment]
Any news?

**Comment by micalevisk** [comment]
@rauldeheer 

Please provide a minimum reproduction repository

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
