### ISSUE TITLE
Add a new provider `TokenProvider<T>` to register tokens dynamically

### ISSUE THREAD

**Issue by redsuperbat** [nestjs/nest#12354]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Sometimes it's necessary to register an implementation of an interface in the providers array dynamically. If this registration depends on another dependency such as a `ConfigService` it becomes tedious since you have to use the `FactoryProvider<T>` and pass all of the arguments into the constructor of the implementation.

### Describe the solution you'd like

Currently you would have to write code like this with a `FactoryProvider`:
```ts
{
  provide: FixerService,
  useFactory: (
    config: ConfigService,
    httpClient: HttpClient,
    options: FixerModuleForFeatureOptions,
    grpcClient: GrpcClient
  ) => {
   const fixerServiceType = config.getOrThrow<"http" | "grpc">("fixer.serviceType", "http");
    if(fixerServiceType === "http") {
      return new HttpFixerService(options, httpClient);
    }
    if(fixerServiceType === "grpc") {
      return new GrpcFixerService(options, grpcClient);
    }
  },
  inject: [ConfigService, HttpClient, FIXER_OPTIONS, GrpcClient],
}
```
As you could imagine this code would grow larger and larger depending on how the `HttpFixerService` and `GrpcFixerService` changes over time.

The solution would introduce a `TokenProvider` and you could return a token and then Nest would hande the dependency resolution internally:
```ts
{
  provide: FixerService,
  useClassFactory: (config: ConfigService) => {
   const fixerServiceType = config.getOrThrow<"http" | "grpc">("fixer.serviceType", "http");
    if(fixerServiceType === "http") {
      return HttpFixerService
    }
    if(fixerServiceType === "grpc") {
      return GrpcFixerService
    }
  },
  inject: [ConfigService],
}
```
Then the provider would only need to depend on the services which control the logic of which implementation would be used. Not which dependencies goes where.

### Teachability, documentation, adoption, migration strategy

I added a code example in the previous box ☝️.

No breaking changes, this is a non-braking feature.

### What is the motivation / use case for changing the behavior?

This would further embrace Nest.js DI system by making it easier and more maintainable to use polymorphic patterns in your code, which can be very useful to prevent side-effects from happening in different environments like staging, demo etc.

--- 

***edit: changed the name of the factory function***

**Comment by micalevisk** [comment]
what about `useClassFactory` instead? since that seems to be all about having a factory to `useClass`

**Comment by KostyaTretyak** [comment]
Have you tried using ModuleRef? Try this:

```ts
{
  provide: FixerService,
  useFactory: (config: ConfigService, moduleRef: ModuleRef) => {
    const fixerServiceType = config.getOrThrow<'http' | 'grpc'>('fixer.serviceType', 'http',);
    if (fixerServiceType === 'http') {
      return moduleRef.get(HttpFixerService);
    }
    if (fixerServiceType === 'grpc') {
      return moduleRef.get(GrpcFixerService);
    }
  },
  inject: [ConfigService, ModuleRef],
},
```

Of course, this `module.get()` can only be used if your services are running in the default scope.

**Comment by micalevisk** [comment]
you could use `moduleRef.resolve` as well if you don't want to initialize all the providers.

**Comment by redsuperbat** [comment]
> what about `useClassFactory` instead? since that seems to be all about having a factory for `useClass`

I don't mind the name. useClassFactory makes more sense to me too.

**Comment by redsuperbat** [comment]
> Have you tried using ModuleRef? Try this:
> 
> ```ts
> {
>   provide: FixerService,
>   useFactory: (config: ConfigService, moduleRef: ModuleRef) => {
>     const fixerServiceType = config.getOrThrow<'http' | 'grpc'>('fixer.serviceType', 'http',);
>     if (fixerServiceType === 'http') {
>       return moduleRef.get(HttpFixerService);
>     }
>     if (fixerServiceType === 'grpc') {
>       return moduleRef.get(GrpcFixerService);
>     }
>   },
>   inject: [ConfigService, ModuleRef],
> },
> ```
> 
> Of course, this `moduleRef.get()` can only be used if your services are running in the default scope.

Didn't think of that, this should solve this. However it's a common pattern for me, would it make sense to add this kind of provider too? 🤔

**Comment by kamilmysliwiec** [comment]
Instead of using `get()` you could use `create()` - in this case you won't have to separately register both HttpFixerService and GrpcFixerService providers
