### ISSUE TITLE
Easy auth with providers

### ISSUE THREAD

**Issue by scorpio-demon** [nestjs/nest#12358]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Having an easy lib to auth

### Describe the solution you'd like

I wrote a lib to have an easy auth in nest
[https://github.com/scorpio-demon/Nest-auther](https://github.com/scorpio-demon/Nest-auther)

### Teachability, documentation, adoption, migration strategy

[https://github.com/scorpio-demon/Nest-auther/blob/main/README.md](https://github.com/scorpio-demon/Nest-auther/blob/main/README.md)

### What is the motivation / use case for changing the behavior?

Speed up developing. Save time of developers

**Comment by jmcdo29** [comment]
So what's the issue? If you have a library for the community you can make a PR on the [awesome repo](https://github.com/nestjs/awesome-nestjs). Just know it won't be merged until it meets the requirements.

If you're looking for feedback, I'd suggest either the [nestjs subreddit](https://nestjs.reddit.com) or [our Discord server](https://discord.gg/nestjs).
