### ISSUE TITLE
Support parameter metadata in SetMetadata and Reflector

### ISSUE THREAD

**Issue by ZBAGI** [nestjs/nest#12368]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

[SetMetadata](https://github.com/nestjs/nest/blob/master/packages/common/decorators/core/set-metadata.decorator.ts) utility provides a straightforward way to annotate classes and methods with metadata. However, it falls short when it comes to adding metadata to method parameters. This limitation forces developers to build their custom implementations for handling parameter metadata.

### Describe the solution you'd like

I propose [extending `SetMetadata`](https://github.com/nestjs/nest/pull/12369/files#diff-79dc9f830860495c05ce4d895aa8ba995746dc2e8d84f7f2c888e3bcc284f7e0) to support parameter metadata and introducing a corresponding method in[ `Reflector` named `getParam`](https://github.com/nestjs/nest/pull/12369/files#diff-34fa43c7f9337c2a7063d8f10052248722b982237cea3c8324fc14686c12e2df). This `getParam` method would return an array of metadata values, where each index represents the corresponding parameter index in the function signature.
PR: #12369

### Teachability, documentation, adoption, migration strategy

The proposed solution is backward-compatible and would require no migration from existing projects. One thing to note is the `param:` prefix on the metadata key. This prefix is essential for disambiguation because both method-level and parameter-level metadata are attached to the method itself. Without a distinct key prefix, metadata for methods would override metadata for parameters when using the same key.

### What is the motivation / use case for changing the behavior?

Expanding `SetMetadata` and `Reflector` in this manner will make them more versatile for all types of metadata annotations, including parameter-level annotations. For example, this feature would be beneficial for guards that rely on custom metadata annotations on method parameters.

In my specific use case, I wish to annotate a controller, methods, and parameters with CheckAccessRightsTo metadata. This metadata would enable a custom guard to dynamically determine the required access rights. The guard would base its decision on whether a specific parameter value exists if the metadata is attached to the parameters. Alternatively, it would always check the access rights if the metadata is attached to a method or class.

Here's a code example to illustrate:
```ts
@Controller([
  "accounts",
  "roles/:roleId/accounts"
])
@CheckAccessRightsTo(Account)
export default class AccountController {
  @Get(":accountId")
  public async getAccount(
    @FromPath("accountId") accountId: number,
    @CheckAccessRightsTo(Role) @FromPath("roleId") roleId?: number,
  ): Promise<boolean> {
    return true; // Just an example
  }
}
```

While `createParamDecorator` could potentially be used to achieve similar functionality, it comes with its set of limitations:
1. It would require creating a separate decorator for what is essentially the same functionality, leading to redundant and fragmented code.
2. My custom guard aggregates all missing access rights and returns them in a single error message. Using createParamDecorator would force me to check/throw errors individually for each missing right, which would be less user-friendly.

On top of that, I'm sure there are many more use cases for properties metadata. It's a common requirement, and it would be great if `SetMetadata` in conjunction with `Reflector` could cover all types of metadata, not just those for classes and methods.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/12369#issuecomment-1715060267
