### ISSUE TITLE
Question about Websockets

### ISSUE THREAD

**Issue by JeetChaudhari** [nestjs/nest#1237]
Hi all, I have a question about websockets.

Is there any way we can extend Gateway so that we can create base gateway which would implement all CRUD methods and we can use those events with namespace of extending gateway? This would allow to implement API based on websockets only instead of http. If yes, then how to do it? I tried but Base Gateway never intitialized.

**Comment by kamilmysliwiec** [comment]
Hey @JeetChaudhari 
There is no such feature in Nest so far. If you are looking for help in creating this, I'd suggest using StackOverflow.
