### ISSUE TITLE
Build error after nestjs version  upgrade 

### ISSUE THREAD

**Issue by shaiambar** [nestjs/nest#12388]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

9.2.1 -> 10.2.4

### Describe the regression

I was updating my nestjs version to 10.x (using `ncu -u -f /^@nestjs/` command and made `npm I `after) and when I tried to build my project (`nest build` ) I got the following error: 
### node_modules/engine.io/node_modules/engine.io-parser/build/esm/index.d.ts:6:54 - error TS2304: Cannot find name 'TransformStream'.

I found [this](https://stackoverflow.com/questions/76837796/error-ts2304-cannot-find-name-transformstream) on stackoverflow, but the solutions there seem like a workaround and not a real fix. 

### Input code

Those are the lines that can't find the TransformStream
```ts
export declare function createPacketEncoderStream(): TransformStream<Packet, any>;
export declare function createPacketDecoderStream(maxPayload: number, binaryType: BinaryType): TransformStream<Uint8Array, any>;
```

### Expected behavior

that the build will work successfully 

### Other

**Those are all of the packages that were upgraded:**
![Screenshot 2023-09-13 at 17 55 43](https://github.com/nestjs/nest/assets/104723671/679661e9-15ea-4952-b02d-9f70346c29db)

**and I am adding the error:**
![Screenshot 2023-09-13 at 17 59 44](https://github.com/nestjs/nest/assets/104723671/411dd51d-e259-41ff-a01f-bf807bdcc90a)

**Comment by micalevisk** [comment]
nodejs version?

**Comment by shaiambar** [comment]
v18.12.0

**Comment by micalevisk** [comment]
I didn't manage to reproduce this.

Please provide a minimum reproduction repository. You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by shaiambar** [comment]
Hi here is [minimal project repository](https://github.com/shaiambar/nestUpgrade) just need to nest build and the error reproduce
thanks

**Comment by shaiambar** [comment]
thank you so much.
