### ISSUE TITLE
@nestjs/platform-fastify deprecation warning

### ISSUE THREAD

**Issue by HarunKilic** [nestjs/nest#12387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using latest version of @fastify/helmet I get this warning: 
```(node:44976) [FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.``` 

Which should be fixed in fastify v.4.7x

But seems like nestjs is using fastify v.4.22.2

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-ksxfqq?file=package.json,src%2Fmain.ts

### Expected behavior

Warning being removed

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "dependencies": {
    "@fastify/helmet": "^11.1.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-fastify": "^10.2.5",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
}
```

### Node.js version

18.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
With Fastify `v4.23.1` it should be fixed, there is a PR of renovate, here https://github.com/nestjs/nest/pull/12389

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12389
