### ISSUE TITLE
[ConfigurableModuleBuilder] Using `registerAsync` on dynamic module errors about module's argument dependency (at index[0])

### ISSUE THREAD

**Issue by sprijk** [nestjs/nest#12399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Following the docs on [Dynamic Modules](https://docs.nestjs.com/fundamentals/dynamic-modules), I receive:
```
ERROR [ExceptionHandler] Nest can't resolve dependencies of the CONFIGURABLE_MODULE_OPTIONS[4951e117b0e2e867ba029] (?). Please make sure that the argument dependency at index [0] is available in the ApiModule context.
```
Apologies, after looking on issues, and other examples, I can't find the what I have overlooked.

Many thanks in advance.

### Minimum reproduction code

https://github.com/sprijk/configurable-dynamic-module-issue

### Steps to reproduce

1. `npm ci`
2. `npm run start:dev`
3. See error...

### Expected behavior

I was expecting I followed the docs to the letter, but I may have overlooked something... 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.x.x

### Packages versions

```
[System Information]
OS Version     : Linux 5.15
NodeJS Version : v18.17.1
NPM Version    : 9.6.7 

[Nest CLI]
Nest CLI Version : 10.1.17 

[Nest Platform Information]
platform-express version : 10.2.5
schematics version       : 10.0.2
testing version          : 10.2.5
common version           : 10.2.5
config version           : 3.1.1
core version             : 10.2.5
cli version              : 10.1.17
```

### Node.js version

18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Why are you passing an array to the `ApiModule.forRootAsync()`? It should take in a single options object.

```diff
diff --git a/src/app.module.ts b/src/app.module.ts
index 899df4c..808ccb6 100644
--- a/src/app.module.ts
+++ b/src/app.module.ts
@@ -11,18 +11,15 @@ const config = ConfigModule.forRoot({
   load: [serverConfig],
 });
 
-const api = ApiModule.registerAsync([
-  {
-    name: 'API_SERVICE',
-    inject: [ConfigService],
-    useFactory: async (config: ConfigService) => {
-      return {
-        url: config.get<string>('server.host'),
-        port: config.get<string>('server.port'),
-      };
-    },
+const api = ApiModule.registerAsync({
+  inject: [ConfigService],
+  useFactory: async (config: ConfigService) => {
+    return {
+      url: config.get<string>('server.host'),
+      port: +config.get<string>('server.port'),
+    };
   },
-]);
+});
 
 @Module({
   imports: [config, api],
```

**Comment by micalevisk** [comment]
yeah, that should fix.

@sprijkz we use GitHub Issues to track bug reports, feature requests and regressions

next time try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead

**Comment by hktime9** [comment]
@sprijk were you able to solve this by sending in the object instead of sending in an array? I'm facing a similar issue but I'm using the register() method from my dynamic module.

**Comment by sprijk** [comment]
@hktime9 yep!
