### ISSUE TITLE
FastifyError [Error]: fastify-plugin: @fastify/static - expected '^4.23.0' fastify version, '4.22.2' is installed

### ISSUE THREAD

**Issue by vitaliy-grusha** [nestjs/nest#12396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

With this "@nestjs/platform-fastify": "^10.2.5" when `useStaticAssets` is used

```typescript 
app.useStaticAssets({
  root: join(__dirname, './utilities/graphiql'),
  prefix: '/graphiql',
  index: ['index.html'],
});
```

Nest app can't start due to an error `FastifyError [Error]: fastify-plugin: @fastify/static - expected '^4.23.0' fastify version, '4.22.2' is installed`. This is because latest @fastify/static requires fastify^4.23.0 ([source](https://github.com/fastify/fastify-static/blob/2471a4c2413f7958b0045073e70d81b1bd85b57d/index.js#L555)).

### Minimum reproduction code

none

### Steps to reproduce

1. pnpm up
2. pnpm run start:dev
3. get an error

### Expected behavior

It should work :).

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.5

### Packages versions

```json
    "@nestjs/common": "^10.2.5",
    "@nestjs/core": "^10.2.5",
    "@nestjs/graphql": "^12.0.9",
    "@nestjs/jwt": "^10.1.1",
    "@nestjs/mapped-types": "^2.0.2",
    "@nestjs/mercurius": "^12.0.9",
    "@nestjs/microservices": "^10.2.5",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-fastify": "^10.2.5",
    "@nestjs/platform-socket.io": "^10.2.5",
    "@nestjs/throttler": "^4.2.1",
    "@nestjs/websockets": "^10.2.5",
```

### Node.js version

v20.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
There is a PR here for the upgrade to fastify` v4.23.2` for the "@nestjs/platform-fastify" package: https://github.com/nestjs/nest/pull/12395

while for the @nestjs/serve-static package there is a PR here: https://github.com/nestjs/serve-static/pull/1274, again for the upgrade to fastify `v4.23.2`

**Comment by vitaliy-grusha** [comment]
Oh, thanks!

**Comment by shAbhijit** [comment]
> There is a PR here for the upgrade to fastify` v4.23.2` for the "@nestjs/platform-fastify" package: #12395
> 
> while for the @nestjs/serve-static package there is a PR here: [nestjs/serve-static#1274](https://github.com/nestjs/serve-static/pull/1274), again for the upgrade to fastify `v4.23.2`
Hi,
I am facing a similar issue. Is there any workaround until the PR is merged, or when will the PR be merged?
