### ISSUE TITLE
Add a timeout to loading modules

### ISSUE THREAD

**Issue by pcurrivan** [nestjs/nest#12397]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am having an issue where a Type ORM module is hanging during initialization of my app because it can't connect to a postgres database.   As a result, NestJS hangs without any error message, and it took a long time for me to track down the problem.

### Describe the solution you'd like

NestJS should protect itself by having its own timeout for loading modules.  

### Teachability, documentation, adoption, migration strategy

Timeout should be configurable, and maybe optional.

### What is the motivation / use case for changing the behavior?

When the timeout expires NestJS can print an error message describing what module hung during initialization instead of the current behavior where NestJS just silently hangs without any error messages.

**Comment by micalevisk** [comment]
Any suggestions on how the API for that could look like?

**Comment by OMartinez-NeT** [comment]
Perhaps [ModuleMetadata](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/modules/module-metadata.interface.ts) could accept a timeout property. And upon loading all the [modules](https://github.com/nestjs/nest/blob/67951ff2e9b7f4803856ab8169e23350e49d7dfc/packages/core/injector/instance-loader.ts#L48-L60), the timeout property can be evaluated, and if necessary, the module execution could be wrapped in a `Promise.race` 

The API definition should look like this:

```
@Module({
  timeout: 4000,
  imports: [],
})
export class AppModule {}
```

**Comment by jmcdo29** [comment]
> I am having an issue where a Type ORM module is hanging during initialization of my app because it can't connect to a postgres database.

The TypeORM module has a built in retry and reporting for problems with connecting the the database and stops after 10 retries, reports the full error, and throws an exception that stops the initialization process. Are you seeing something different here?

**Comment by pcurrivan** [comment]
@jmcdo29 I was not providing a value for connectTimeoutMS  in my TypeOrmModuleOptions, and the default timeout ended up as 0 (disabled).  (I observed a value of 0 for _connectionTimeoutMillis in pg/lib/client.js). I just now tried setting connectTimeoutMS to 5000 and now I am getting an error message.  This is with @nestjs/typeorm 10.0.0, typeorm 0.3.17, and pg 8.11.1.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
