### ISSUE TITLE
Interceptor in main project breaks endpoints in npm installed Nest lib

### ISSUE THREAD

**Issue by alwinzwets** [nestjs/nest#12406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Adding an interceptor to the project causes a print out of the Observable structure instead of the Observable result on endpoints exposed by a Nest NPM library.

Without the interceptor the behaviour is as expected and the endpoint returns the result of the Observable, i.e.:
```json
{
  "msg": "Hello World - From lib!"
}
```

When any (even an empty) interceptor is added to the main Nest instance, the endpoint in the lib starts returning the print out of the Observable structure, i.e.:
```json
{
  "source": {}
}
```

This only occurs on endpoints exposed by libs that are added to the project via NPM. Removing the interceptor fixes the problem.

See attached git repo for a minimum reproduction.

### Minimum reproduction code

https://github.com/alwinzwets/nestjs-interceptor-reproduction

### Steps to reproduce

See README.md in repo.

### Expected behavior

I would expect to keep receiving the Observable results on lib endpoints after adding the Interceptor in the main project.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.5

### Packages versions

```
[System Information]
OS Version     : Windows 11
NodeJS Version : v20.4.0
NPM Version    : 9.7.2 

[Nest CLI]
Nest CLI Version : 10.1.17

[Nest Platform Information]
platform-express version : 10.2.5
schematics version       : 10.0.2
testing version          : 10.2.5
common version           : 10.2.5
core version             : 10.2.5
cli version              : 10.1.17
```

### Node.js version

20.4.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
If you want to use `npm link`, you should also make sure to link peer dependencies (rxjs and all `@nestjs/{..}` packages) - otherwise lib and app will use different copies which may lead to unexpected behavior.

**Comment by alwinzwets** [comment]
Thanks for this! `npm link rxjs` already solves the problem indeed. Interesting behaviour since RxJS versions in app and lib are exactly the same, but not a nest issue luckily.
