### ISSUE TITLE
express-adapter: content-type may be null

### ISSUE THREAD

**Issue by mfulton26** [nestjs/nest#12412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`response.getHeader("Content-Type")` can return `null` instead of `undefined`

### Minimum reproduction code

https://github.com/mfulton26/deno-nest

### Expected behavior

code should gracefully handle `undefined` and `null`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.5

### Packages versions

```json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true
  },
  "imports": {
    "@graphql-yoga/nestjs": "npm:@graphql-yoga/nestjs@^2.1.0",
    "@nestjs/common": "npm:@nestjs/common@^10.0.0",
    "@nestjs/core": "npm:@nestjs/core@^10.0.0",
    "@nestjs/graphql": "npm:@nestjs/graphql@^12.0.0",
    "@nestjs/platform-express": "npm:@nestjs/platform-express@^10.0.0",
    "@nestjs/testing": "npm:@nestjs/testing@^10.0.0",
    "graphql": "npm:graphql@^16.8.1",
    "reflect-metadata": "npm:reflect-metadata@^0.1.13",
    "rxjs": "npm:rxjs@^7.8.1"
  }
}

```

### Deno version

deno 1.37.0 (release, aarch64-apple-darwin)
v8 11.8.172.3
typescript 5.2.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I am experimenting with getting NestJS to run on Deno (I want to run NestJS on Deno Deploy).

So far it has gone well but this is one issue I did run into. Maybe this is a Deno Node compat issue (and Deno should be returning `undefined` instead of `null`) but I also figure the change is so easy here in NestJS and only makes the code more resilient so why not change it here is my thinking.

current:
https://github.com/nestjs/nest/blob/97e9652290c777cd39992dcacf20d5642807c15e/packages/platform-express/adapters/express-adapter.ts#L105-L106

proposed:
```ts
      !response.getHeader('Content-Type')?.startsWith('application/json') &&
```

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12413
