### ISSUE TITLE
Watcher doesn't restart process on unhandled errors-rejections

### ISSUE THREAD

**Issue by Shahor** [nestjs/nest#12411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In dev mode, when an unhandled error/rejection happens the process exits but the watcher doesn't do anything about it.

The error is displayed and process exits, and the process won't be reloaded unless there's a new save on a file **with changes** (just saving doesn't trigger the watcher). 

This makes the developer experience a bit cumbersome as it's not super obvious from the logs that the process exited, and how to restart it.

### Minimum reproduction code

https://github.com/Shahor/nestjs-exit

### Steps to reproduce

1. clone
2. install
3. `yarn start:dev`

### Expected behavior

# Ideal

- The log could still show the error but also explicitely state that the process was killed.
- Explain how to restart it or when it'll restart (after saves on a changed file).
- The watcher automatically restarts the process so we can resume working without disruption

# Possibly

- The watcher effectivelly gives up restarting the process after seeing the same error X times (to avoid infinite loops, even though devs could abort the process in that case)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10

### Packages versions

```json
 "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
```

### Node.js version

20.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I think that's expected due to the `abortOnError` being `true` by default

You can disable it like this:

```ts
NestFactory.create(AppModule, { abortOnError: false })
```

**Comment by kamilmysliwiec** [comment]
That's the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
