### ISSUE TITLE
@nestjs/graphql: GraphQLDriver#generateSchema() returns `null` unless `autoSchemaFile` is defined

### ISSUE THREAD

**Issue by mfulton26** [nestjs/nest#12420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`graphQlAdapter.generateSchema()` resolves to `null` in a standalone application context unless `autoSchemaFile` is defined.

### Minimum reproduction code

https://dash.deno.com/playground/noisy-alligator-71

### Steps to reproduce

1. copy and paste the minimum reproduction code into a local file named `main.ts`
2. run `deno run -A main.ts`
3. open http://localhost:8000/graphql
4. in Graph_i_QL, try to inspect the schema explorer or run a query (e.g. `query { jobs { id } }`)

the schema isn't loaded and the GraphQL endpoint doesn't work

logs show `ERR Error: Expected null to be a GraphQL schema.`

### Expected behavior

the schema is loaded and the GraphQL query works as expected

here's a working example of the code (just uncomment the line containing `autoSchemaFile` to reproduce the reported issue):

```ts
import { NestFactory } from "npm:@nestjs/core@^10.0.0";
import {
  Controller,
  Get,
  Injectable,
  Module,
} from "npm:@nestjs/common@^10.0.0";
import {
  Field,
  GraphQLModule,
  ID,
  ObjectType,
  Query,
  Resolver,
} from "npm:@nestjs/graphql@^12.0.0";
import { YogaDriver, YogaDriverConfig } from "npm:@graphql-yoga/nestjs@^2.1.0";
import { createYoga } from "npm:graphql-yoga@^4.0.4";

@ObjectType()
export class Job {
  @Field((type) => ID)
  id: string;
}

@Resolver((of) => Job)
export class JobsResolver {
  constructor() {}

  @Query((returns) => [Job])
  async jobs(): Promise<Job[]> {
    return [{ id: "1" }, { id: "2" }];
  }
}

@Module({
  imports: [],
  providers: [JobsResolver],
})
export class JobsModule {}

@Injectable()
export class AppService {
  getHello(): string {
    return "Hello World!";
  }
}

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}

@Module({
  imports: [
    JobsModule,
    GraphQLModule.forRoot<YogaDriverConfig>({
      driver: YogaDriver,
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

const appContext = await NestFactory.createApplicationContext(AppModule);

const { graphQlAdapter } = appContext.get(GraphQLModule);
const schema = await graphQlAdapter.generateSchema({
  autoSchemaFile: "schema.gql",
})!;

const yoga = createYoga({
  schema,
  landingPage: false,
  graphiql: {
    title: "Field Server GraphiQL",
    defaultQuery: undefined,
  },
});

Deno.serve(yoga);
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

10.2.5

### Packages versions

```json
{
  "imports": {
    "@graphql-yoga/nestjs": "npm:@graphql-yoga/nestjs@^2.1.0",
    "@nestjs/common": "npm:@nestjs/common@^10.0.0",
    "@nestjs/core": "npm:@nestjs/core@^10.0.0",
    "@nestjs/graphql": "npm:@nestjs/graphql@^12.0.0",
    "@nestjs/testing": "npm:@nestjs/testing@^10.0.0",
    "graphql-yoga": "npm:graphql-yoga@^4.0.4",
    "graphql": "npm:graphql@^16.8.1"
  }
}

```

### Deno version

deno 1.37.0 (release, aarch64-apple-darwin)
v8 11.8.172.3
typescript 5.2.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I'm learning ways to use NestJS with Deno! 😄

**Comment by kamilmysliwiec** [comment]
`createApplicationContext` shouldn't be used in combination with `GraphQLModule`.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
