### ISSUE TITLE
inject() function similar to the Angular one for new way of dependency injection

### ISSUE THREAD

**Issue by auricleau** [nestjs/nest#12440]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The introduction of inject() function in Angular 14 provide a new way of how developer can handle DI.

Since Nest.js and Angular share a similar way on DI, I think the feature can also benefit user of Nest.js

### Describe the solution you'd like

Please refer to [Angular - inject](https://angular.io/api/core/inject) for details on the implementation of Angular.

### Teachability, documentation, adoption, migration strategy

Instead of providing every dependency in the constructor, as shown in the official documentation:
```typescript
  constructor(private catsService: CatsService) {}
```
Developer can inject the dependency as:
```typescript
  private catsService = inject(CatsService);
```

For optional dependency, we can change from:
```typescript
  constructor(@Optional() @Inject('HTTP_OPTIONS') private httpClient: T) {}
```
to:
```typescript
  private httpClient = inject<T>('HTTP_OPTIONS', { optional: true });
```

The injection can also be done inside of method:
```typescript
  @Post()
  async create(@Body() createCatDto: CreateCatDto) {
    const catsService = inject(CatsService);
    catsService.create(createCatDto);
  }
```
or even as a parameter used for static method and inject the dependency when calling the static method when needed
```typescript
  async static create(props: createProps, repository = inject<IDataBaseRepository>('DATABASE_REPOSITORY')) {
    await repository.insert(props);
  }
```

The inject() function also eliminate the need of calling super() when we extends class.
Instead of:
```typescript
export class BaseClass {
  constructor(baseService: BaseService) {}
}

export class ExtendClass extends BaseClass {
  constructor(baseService: BaseService, extendService: ExtendService) {
    super(baseService);
  }
}
```
We can:
```typescript
export class BaseClass {
  baseService = inject(BaseService);
}

export class ExtendClass extends BaseClass {
  extendService = inject(ExtendService);
}
```

### What is the motivation / use case for changing the behavior?

As described above, user can handle DI in a more flexible and potentially eliminate the need of writing a bunch of boilerplate codes. While the original DI utilise the native Typescript way, it is not going anywhere. But the introduction of the new way of DI can help provide new tools to improve the performance of developers

**Comment by jmcdo29** [comment]
[I see that you checked the "I have searched previous issues" box](https://github.com/nestjs/nest/issues/10586#issuecomment-1324707932), but [it's not like this hasn't been discussed before](https://github.com/nestjs/nest/issues/12108)
