### ISSUE TITLE
NestJS not handling error from thrown from service

### ISSUE THREAD

**Issue by hooliy** [nestjs/nest#12469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/nestjs/nest/assets/3368691/551900a3-f105-4458-9205-0285f13f9d23)
![image](https://github.com/nestjs/nest/assets/3368691/f78793dd-3ae8-436a-b6da-8fe4119c1ad4)

### Minimum reproduction code

https://github.com/hooliy/min-nestjs.git

### Expected behavior

In the project, mikro-orm was used. I unintentionally wrote a piece of faulty code and found that the global exception interceptor cannot intercept this exception, which directly causes the application to terminate. I am certain that the global interceptor is correctly configured and I have tested that it can successfully intercept other exception information in the service. Currently, I have only found this one exception that cannot be intercepted and causes the application to terminate.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0

### Packages versions

```json
"dependencies": {
    "@mikro-orm/core": "^5.8.2",
    "@mikro-orm/mysql": "^5.8.2",
    "@mikro-orm/nestjs": "^5.2.1",
    "@mikro-orm/sql-highlighter": "^1.0.1",
    "@nestjs/cache-manager": "^2.1.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/jwt": "^10.1.1",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/swagger": "^7.1.12",
    "bcryptjs": "^2.4.3",
    "cache-manager": "^5.2.3",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "moment": "^2.29.4",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  }
```

### In which operating systems have you tested?

- [x] macOS
- [x] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
that's due to how `.forEach` works. not related with nesjs.

I'd suggest you to read this: [JavaScript async and await in loops](https://zellwk.com/blog/async-await-in-loops/)
