### ISSUE TITLE
Suggestion: minimal dockerfile example

### ISSUE THREAD

**Issue by isaacbatst** [nestjs/nest#12479]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Today there's no instruction about a dockerized nest app, like this example from [nextjs docs](https://nextjs.org/docs/app/building-your-application/deploying#docker-image)

### Describe the solution you'd like

It would be nice to have a recipe maybe, just suggesting a minimal dockerfile example, with suggested good practices. I'll write here an example based in what I have used and I request your improvements suggestions

### Teachability, documentation, adoption, migration strategy

Something like this:

NestJS applications can be builded using docker images. 

Here we have a [multi-stage build](https://docs.docker.com/build/building/multi-stage/) example. This will allow you to build an image for development or production.

```Dockerfile
# Install dependencies if needed
FROM node:18-alpine as dev
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile
COPY . .
ENTRYPOINT ["yarn"]
CMD ["start:dev"]
EXPOSE 3000

# Build production dist
FROM node:18-alpine as builder
WORKDIR /app
ENV NODE_ENV production
COPY --from=dev /app/node_modules ./node_modules
COPY . . 
RUN yarn build
RUN rm -rf node_modules
RUN yarn --frozen-lockfile --production

# Run production version only with necessary files
FROM node:18-alpine as production
WORKDIR /app
ENV NODE_ENV production
RUN addgroup --system --gid 1001 nest
RUN adduser --system --uid 1001 nest
COPY --from=builder --chown=nest:nest /app/dist ./dist
COPY --from=builder --chown=nest:nest /app/node_modules ./node_modules
COPY --from=builder --chown=nest:nest /app/package.json ./package.json
USER nest
CMD ["yarn", "start:prod"]
```

To build an image, create a file named `Dockerfile` inside your project root folder and execute the following command:

```sh
# builds a development image
docker build --target dev -t my-nest-app-dev .
# builds a production image
docker build -t my-nest-app-prod .
```

### What is the motivation / use case for changing the behavior?

I have needed to deploy an application with docker images, so that I had to look for articles and the docker docs itseft to create it from scratch. I would be great to have a recipe with recommended practices inside nest docs.

**Comment by micalevisk** [comment]
there are few examples here: https://github.com/nestjs/awesome-nestjs

I have another example here: https://gist.github.com/micalevisk/9ee47135b22f284dd73de6ea6d5aa864

Jay has one here: https://github.com/jmcdo29/nest-docker-template

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
