### ISSUE TITLE
Updating `@nestjs/*` to v10 breaks prisma client with Yarn PnP

### ISSUE THREAD

**Issue by wataruian** [nestjs/nest#12481]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When updating `@nestjs/*` to `v10`, prisma client can't be resolved anymore. Everything works fine when on `v9`.

```
2023-10-01 17:23:10.323 [ERROR]: uncaughtException: @prisma/client tried to access .prisma, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: .prisma (via ".prisma/client/index")
Required by: @prisma/client@virtual:157310d72b686b3237bd38407cf1bd2fd4e9c9299fb1302b25b44e45e175b9f265650deb342202e79002585ac68e431f75b040f5708c46f4bc29b919dd1ec7e9#npm:5.3.1 (via /Users/wataruian/projects/api/.yarn/unplugged/@prisma-client-virtual-9f5efad218/node_modules/@prisma/client/)
```

Prisma client version: `^4.13.0`

### Minimum reproduction code

Will see if I can make repro code but the behavior is easily reproduced using v10 of nestjs together with prisma client.

### Expected behavior

NestJS app should start after updating to v10 with prisma client and Yarn PnP

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@prisma/client

### NestJS version

10.2.6

### Packages versions

```json
{
    "@nestjs/common": "^10.2.6",
    "@nestjs/core": "^10.2.6",
    "@nestjs/platform-express": "^10.2.6"
}
```

### Node.js version

v18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Architecture: Apple M2 Pro (arm64)
OS version: 13.5.2 (22G91)

**Comment by Tony133** [comment]
Hi @wataruian, for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel

The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by micalevisk** [comment]
> is easily reproduced

than share a repro

Tbh I'm pretty sure that this is not related with nestjs at all. Prisma doesn't depends on nestjs. You might be missing something
