### ISSUE TITLE
moduleRef.get for request scoped services

### ISSUE THREAD

**Issue by ZBAGI** [nestjs/nest#12480]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm facing an issue where I'm unable to fetch durable services into other durable services dynamically using the `moduleRef.get()` method.

Here's a simplified example to illustrate:

*In module A:*
```ts
@Injectable({ scope: Scope.REQUEST, durable: true })
class ExampleService {
	public example: boolean = true;
}

providers: [
  ExampleService,
  {
    provide: "exampleToken",
    useExisting: ExampleService
  }
]
```
*In module B*
```ts
@Injectable({ scope: Scope.REQUEST, durable: true })
class OtherService {
	public example(): void {
		const allServices = this.moduleRef.get("exampleToken", { strict: false, each: true });
	}
}
```
The `allServices` is receiving `null` for all registered services. 
After quick search i found [Issue #2861](https://github.com/nestjs/nest/issues/2861). It's mentioned:

> It's not an issue. You can't use get() to retrieve request-scoped instances + you can't inject request-scoped instances to singleton, statically scoped services.

While I understand that it is impossible to fetch __request-scoped__ services into __singletons__, why isn't it possible to fetch __request-scoped__ instances into other __request-scoped__ instances? More importantly, why can't __durable__ services be fetched into other __durable__ services? I tend to view __durable__ services not as __request-scoped__ but rather as 'singletons that are grouped by certain rules' defined in `ContextIdStrategy`.

Is this a design limitation, or was there an intentional decision behind this behavior?

### Describe the solution you'd like

I propose extending the functionality to enable the fetching of request-scoped services within other request-scoped services, provided they share the same durable value. This would create a more intuitive dependency tree, aligning with the user expectation that services with the same durability should be accessible within the same scope.

### Teachability, documentation, adoption, migration strategy

This would be a new feature that should be backward-compatible, thus requiring no migration or adoption strategy for existing users.

### What is the motivation / use case for changing the behavior?

It feels natural to be able to fetch request-scoped services within the same request scope, especially if both services are durable.

**Comment by jmcdo29** [comment]
[There's already ways to get request scoped instances using `moduleRef.resolve`](https://docs.nestjs.com/fundamentals/module-ref#resolving-scoped-providers)

**Comment by ZBAGI** [comment]
Thanks, @jmcdo29 . You are right; this is actually the method I've been looking for. But, it requires a `contextId`, and I can't create a new one since I want to fetch a `durable` service that holds a reference to the tenant database. Could you clarify how I can get the `contextId` of the service from which i try to fetch the other service (ie. _module B_)

**Comment by jmcdo29** [comment]
I could be wrong here, but I _believe_ that if you use `ContextIdFactory.getByRequest(currentRequest)` Nest will realize it relates to a durable context and retrieve that contextId. I'd need @kamilmysliwiec to confirm or deny that though.

**Comment by ZBAGI** [comment]
Thanks again, @jmcdo29 , for the very fast answer. However, it seems there might be a bug. (Should I create a new issue for it?) 

Namely, when the service we request via `this.moduleRef.resolve` (let's call it X) hasn't been initialized yet, Nest correctly tries to create new instance, but all of X's dependencies appear to lose the REQUEST context (i.e., it is set to undefined).

Here is the snippet to demonstrate the issue:
```ts
import { Controller, Get, Inject, Injectable, Module, Scope } from "@nestjs/common";
import {
	ContextId, ContextIdFactory, ContextIdResolver, ContextIdResolverFn, ContextIdStrategy,
	HostComponentInfo, ModuleRef, NestFactory, REQUEST
} from "@nestjs/core";
import { NestExpressApplication } from "@nestjs/platform-express";

// Context strategy
const tenants = new Map<string, ContextId>();
export class TenantContextIdStrategy implements ContextIdStrategy {
	public attach(contextId: ContextId, request: Request): ContextIdResolverFn | ContextIdResolver | undefined {
		// request is string in the durable services
		const tenantId = typeof request == "string" ? request : "example" + i;

		let tenantSubTreeId: ContextId;
		if (tenants.has(tenantId)) {
			tenantSubTreeId = tenants.get(tenantId) as ContextId;
		} else {
			tenantSubTreeId = ContextIdFactory.create();
			tenants.set(tenantId, tenantSubTreeId);
		}

		return {
			resolve: (info: HostComponentInfo): ContextId =>
				info.isTreeDurable ? tenantSubTreeId : contextId,
			payload: tenantId,
		};
	}
}
ContextIdFactory.apply(new TenantContextIdStrategy());

class DatabaseService { }

@Injectable({ scope: Scope.REQUEST, durable: true })
class ExampleService {
	constructor(
		protected db: DatabaseService
	) { }
}

@Injectable({ scope: Scope.REQUEST, durable: true })
export class TransformationService {
	public constructor(
		protected moduleRef: ModuleRef,
		@Inject(REQUEST) public request: any
	) { }

	public async test(): Promise<void> {
		const allProviders = await this.moduleRef.resolve("exampleToken", ContextIdFactory.getByRequest(this.request), { each: true });
		allProviders.forEach((p: any) => {
			// console.log(p);
		});
	}
}

@Module({
	providers: [TransformationService],
	imports: [],
	controllers: [],
	exports: [TransformationService]
})
class TransformationModule {
}

// STARTUP
@Controller("example")
class ExampleController {
	public constructor(
		public transformationService: TransformationService,
		// protected service: ExampleService <- if uncommented it forces initialization of ExampleService with correct REQUEST context ie. everything works fine.
	) {}
	
	@Get()
	public getAccessPoints(): string {
		this.transformationService.test();

		return "example";
	}
}
@Module({
	providers: [
		ExampleService,
		TransformationService,
		{
			provide: "exampleToken",
			useExisting: ExampleService
		},
		{
			provide: DatabaseService,
			scope: Scope.REQUEST,
			durable: true,
			inject: [REQUEST],
			useFactory: (tenantId: string): Promise<DatabaseService> => {
				// request here is `undefined` when initialized via this.moduleRef.resolve
				if(typeof tenantId != "string") // REQUEST is string for durable services and request obj otherwise
					throw new Error("Database can only be requested by services marked as durable");
				console.log("INITIALIZED DATABASE FOR " + tenantId);

				return <any>{};
			}
		}
	],
	controllers: [ExampleController],
	imports: [TransformationModule]
})
class ApiModule {}

(async(): Promise<void> => {
	const app = await NestFactory.create<NestExpressApplication>(ApiModule);
	app
		.disable("x-powered-by")
		.set("trust proxy", "loopback, linklocal, uniquelocal");
		
	app.enableCors();

	await app.listen(80);
})();
```

**Comment by ZBAGI** [comment]
After a little tinkering, I found that re-registering the request by context ID fixes the issue:
```ts
public constructor(
	protected moduleRef: ModuleRef,
	@Inject(REQUEST) public request: any
) {}

public async test(): Promise<void> {
	const context = ContextIdFactory.getByRequest(this.request);
	this.moduleRef.registerRequestByContextId(this.request, context); // This fixes the issue, but nonetheless, it feels strange that I need to re-register the request context here.
	const allProviders = await this.moduleRef.resolve("exampleToken", context, { each: true });
}
```
Since this issue is completely unrelated to the original question, I marking this issue as closed. 
Thanks again @jmcdo29 for help!

**Comment by severous** [comment]
已经导入了持久服务ContextService，为何无法通过moduleRef.get获取
<img width="1782" height="940" alt="Image" src="https://github.com/user-attachments/assets/c2865f8a-a654-47f8-94f7-280fe26b3b4c" />
