### ISSUE TITLE
@Catch()  decorator support string argument

### ISSUE THREAD

**Issue by Jurajzovinec** [nestjs/nest#12482]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We are using [rush stack](https://rushstack.io/) for running our nestjs microlithic architecture and to follow the DRY principle most of our bootstrap-related code is shared using an internal npm package (let's call it `internal-bootstrap`). This package also offers several implementations of ExceptionFilters. 
The current design of the exception filter requires class instances of filtered error. This puts us in a situation where the filtered error must be in a namespace of the specific library.
Example: we want to define SqlQueryExceptionFilter that will catch (and handle) TypeORM generated errors like `QueryFailedError` in `internal-bootstrap`
 Solutions on our side would be to:
 1. Extend implementation of AllExceptionsFilter (which has no argument in @Catch() decorator) in order to handle and filter QueryFailedError error inside of it which would result in moving filtering logic from framework to implementation of AllExceptionsFilter
 2. Install the TypeORM library in `internal-bootstrap` package in order to define SQL queries dedicated ExceptionFilter which would result expensive extension of `internal-bootstrap` package
 3. Define TypeORM as peer-dependency which will result in newly introduced constraint, when each new microservice will expect to have TypeORM library installed

### Describe the solution you'd like

Extend the functionality of @Catch decorator by "string" agnostic filtering
```ts
@Catch('QueryFailedError')
export SqlQueryExceptionHandler extends BaseExceptionFilter {
   ...
}
```

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

-

**Comment by KostyaTretyak** [comment]
> Define TypeORM as peer-dependency which will result in newly introduces constraint

What exactly is wrong with this solution? What kind of **constraint** are you talking about? Don't want to import exception tokens?

**Comment by micalevisk** [comment]
you can use [this pattern](https://dev.to/micalevisk/nestjs-tip-fine-grained-exception-filtering-for-the-same-exception-class-5ha5) if you want to perform something other than just `obj instanceof ClassRef`

**Comment by Jurajzovinec** [comment]
> What kind of **constraint** are you talking about? Don't want to

The **constraint** I talk about is more related to the design of newly introduced microservices. Newly introduced microservice using `internal-bootstrap` package will expect to have TypeORM installed (which may not be required)

**Comment by Jurajzovinec** [comment]
@micalevisk thanks for sharing this pattern. Most likely we will use this idea :) @KostyaTretyak feel free to close this feature request

**Comment by KostyaTretyak** [comment]
> @KostyaTretyak feel free to close this feature request

@Jurajzovinec, I'm not a NestJS maintainer, I just follow the wishes of NestJS users and if they suggest something useful, I implement it in my [Ditsmod](https://ditsmod.github.io/en/) framework.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/12482#issuecomment-1742188297
