### ISSUE TITLE
RouterModule: Multiple Exports from Routes File Break Prefixes

### ISSUE THREAD

**Issue by DrunkenToast** [nestjs/nest#12497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

TestModule does not get prefixed with `/test` when multiple items are exported (in this case a route param that is used in the TestController) from the route-tree.ts file. Instead it is exposed as `/:testMessage` instead of `/test/:testMessage`.

As a sidenote, this likely isn't limited to the RouterModule: During development I noticed that I couldn't properly use the exported parameter in a guard either, it would immediately crash when the guard was used.

### Minimum reproduction code

https://github.com/DrunkenToast/reproducable-nestjs-router-module-exports

### Steps to reproduce

1. Create a TestModule with TestController that uses a testParameter
2. Register RouterModule in AppModule
3. Create a RouteTree object from a seperate file which defines a path for the TestModule/TestController
4. Export something else from this RouteTree file (this example we export a testParameter that we use in the TestController)
5. When this exported parameter gets used the TestModule does not get prefixed with the defined path

### Expected behavior

You may define as much as your heart desires from any file without it causing unexpected behaviour.

You can use the workaround by going in src/test.controller.ts and uncommenting the workaround import and commenting the import from the route-tree.ts file.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

/

### NestJS version

^10.0.0

### Packages versions

```json
{
  "name": "reproducable-nestjs-router-module",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

v18.17.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Current behaviour:
```
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [NestFactory] Starting Nest application...
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [InstanceLoader] RouterModule dependencies initialized +7ms
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [InstanceLoader] TestModule dependencies initialized +0ms
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [RoutesResolver] AppController {/}: +8ms
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [RoutesResolver] TestController {/}: +0ms
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [RouterExplorer] Mapped {/:testMessage, GET} route +0ms
[Nest] 8471  - 10/04/2023, 9:29:01 AM     LOG [NestApplication] Nest application successfully started +1ms
```

Expected behaviour/using workaround:
```
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [NestFactory] Starting Nest application...
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [InstanceLoader] RouterModule dependencies initialized +7ms
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [InstanceLoader] TestModule dependencies initialized +0ms
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [RoutesResolver] AppController {/}: +8ms
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [RoutesResolver] TestController {/test}: +0ms
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [RouterExplorer] Mapped {/test/:testMessage, GET} route +0ms
[Nest] 8519  - 10/04/2023, 9:29:51 AM     LOG [NestApplication] Nest application successfully started +1ms
```

**Comment by SirReiva** [comment]
You are creating a circular dependency with testParam const exported in route-tree.ts, if you log TestModule in this file you will see that is undefined.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/12497#issuecomment-1747749596

This is a common issue in JS and there's not much we can do on our side to fix this up.
