### ISSUE TITLE
feature: Add asynchronous context tracking module

### ISSUE THREAD

**Issue by joebowbeer** [nestjs/nest#12508]
Asynchronous context tracking is stable according to the official documentation

https://nodejs.org/api/async_context.html#asynchronous-context-tracking

      async_hooks are still experimental but if anyone wants to use this feature now,
      check out this library https://github.com/Papooch/nestjs-cls

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/1407#issuecomment-1748160008_

**Comment by kamilmysliwiec** [comment]
That PR was using this API https://nodejs.org/api/async_hooks.html

![image](https://github.com/nestjs/nest/assets/23244943/c46d310c-d3ed-4e35-a2aa-6f0d45c81b49)

I'm not sure what nestjs-cls uses but if it was moved to stage 2 that's cool
