### ISSUE TITLE
Inject a provider in another provider, same module

### ISSUE THREAD

**Issue by ale958** [nestjs/nest#1250]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
</code></pre>

I have a service/provider, let's say it's call ServiceA1, in a module A marked as @Injectable().
In the **same module**  i have another service/provider, let's say it's call ServiceA2, marked as @Injectable().
I want to inject ServiceA1 in ServiceA2 I try with: 

```
@Injectable()
export class serviceA2 {
  constructor( @Inject('ServiceA1') private readonly serviceA1: ServiceA1){
  }
  
myFunction(integer A):  {
    const something = this.serviceA1.functionInServiceA1();
  }

}
```
This code throw an error: serviceA1 undefined.

My module.ts 
```
@Module({
  imports: [],
  controllers: [],
  providers: [ServiceA1, ServiceA2]
})
```
I have to make another module to use serviceA2 in serviceA1?

**Comment by marcus-sa** [comment]
If both providers depend upon each other, you create a so called "circular dependency"
For this you'll have to use `forwardRef`

**OBS:** Also you shouldn't provide a string in the `Inject` decorator, but the actual class instead.

> `import { forwardRef } from '@nestjs/common';`

```ts
@Module({
  providers: [
    forwardRef(() => ServiceA1),
    forwardRef(() => ServiceA2),
  ],
})
```
```ts
@Injectable()
export class ServiceA1 {
  constructor(
    @Inject(forwardRef(() => ServiceA2)) 
    private readonly serviceA2: ServiceA2,
  ){}
  
  myFunction():  {
    const something = this.serviceA2.func();
  }

}
```
```ts
@Injectable()
export class ServiceA2 {
  constructor(
    @Inject(forwardRef(() => ServiceA1)) 
    private readonly serviceA1: ServiceA1,
  ){}
  
  myFunction():  {
    const something = this.serviceA1.func();
  }

}
```

**Comment by ale958** [comment]
Providers do not depend on each other, only serviceA2 depends(needs) on ServiceA1, so I think there are other solutions to using that _forwardRef_

**Comment by kamilmysliwiec** [comment]
> I have to make another module to use serviceA2 in serviceA1?

You don't. I would suggest creating appropriate issue on the StackOverflow with somewhat more details about your problem.

**Comment by adrien2p** [comment]
done :)

**Comment by trumbitta** [comment]
@ale958 @adrien2p did you find a solution? I'm having the same problem.

**Comment by trumbitta** [comment]
@marcus-sa 

```
Type 'ForwardReference<any>' is not assignable to type 'Provider'.
  Type 'ForwardReference<any>' is missing the following properties from type 'FactoryProvider': provide, useFactory
```

**Comment by ale958** [comment]
My problem was related to DialogFlowModule lib which I was using, maybe the stackoverflow discussion [https://stackoverflow.com/questions/53088444/inject-a-provider-in-another-provider-same-module-1250](url) will give you some help

**Comment by adrien2p** [comment]
@trumbitta could you share a bit of code please ?

**Comment by trumbitta** [comment]
@adrien2p I ended up splitting the module into two global modules. That effectively worked around the issue.
