### ISSUE TITLE
NestJS starter on Stackblitz has wrong logo

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nestjs/nest#12543]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Problem with logo in Stackblitz NestJS Starter

### Describe the solution you'd like

Can this issue be solved from NestJS end, or is a bug in Stackblitz?
https://github.com/stackblitz/starters/issues/7

Thank you! 🔥🎉🤝😊

### Teachability, documentation, adoption, migration strategy

None

### What is the motivation / use case for changing the behavior?

None

**Comment by jmcdo29** [comment]
This is an issue with their site. Nothing to do with the Nest repo itself. Someone probably used an `x` instead of an `s`.

**Comment by angelhdzmultimedia** [comment]
> This is an issue with their site. Nothing to do with the Nest repo itself. Someone probably used an `x` instead of an `s`.

Thank you very much for your time and your kindness.
