### ISSUE TITLE
`Nest start/build` Error: Cannot find module '/home/.../dist/main'

### ISSUE THREAD

**Issue by sequencerr** [nestjs/nest#12557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

see https://github.com/nestjs/nest/issues/9298

### Minimum reproduction code

https://github.com/lohevol/nestjs-issue/tree/master/src

### Steps to reproduce

```
a@debian:~/$ rm -r dist
a@debian:~/$ nest start --builder tsc
Error: Cannot find module '/home/a/dist/main'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
a@debian:~/a/back/backend$ nest start --builder webpack
ERROR in main
Module not found: Error: Can't resolve 'ts-loader' in '/home/a/back/backend'
resolve 'ts-loader' in '/home/a/packages/back/backend'
...

webpack 5.88.2 compiled with 1 error in 11000 ms
a@debian:~/a$ 
```

### Expected behavior

to be able compile `nest start` or `nest build`, after `rm -r dist`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version
```
[System Information]
OS Version     : Linux 6.1
NodeJS Version : v20.8.0
NPM Version    : 10.1.0 

[Nest CLI]
Nest CLI Version : 10.1.18 

[Nest Platform Information]
platform-socket.io version : 10.2.7
websockets version         : 10.2.2
passport version           : 10.0.0
testing version            : 10.2.2
jwt version                : 10.1.0
```

### Packages versions

```json
package.json
  "dependencies": {
    "@nestjs/jwt": "10.1.0",
    "@nestjs/passport": "10.0.0",
    "@nestjs/platform-socket.io": "^10.1.3",
    "@nestjs/testing": "10.2.2",
    "@nestjs/websockets": "10.2.2",
...
  },
  "types": "dist/main.d.ts",
  "main": "dist/main.js",
...
```
```json
nest-cli.json
{

  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "manualRestart": true,
    "tsConfigPath": "./tsconfig.json"
  }
}

```
```json
tsconfig.json
{
  "extends": "../../name/tsconfig.json",
  "compilerOptions": {
    "outDir": "./dist",
    "baseUrl": "./src",
    "module": "CommonJS",
    "emitDeclarationOnly": false,
    "tsBuildInfoFile": ".tsbuildinfo",
    "rootDir": "src"
  },
  "include": ["src"]
}
```
```
sys:
a@debian:~/$ nvm current
v20.8.0
a@debian:~/$ npm -v
10.1.0
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

```
System:
  Host: debian Kernel: 6.1.0-12-amd64 arch: x86_64 bits: 64 Console: pty pts/1 Distro: Debian
    GNU/Linux 12 (bookworm)
Machine:
  Type: Vmware System: VMware product: VMware Virtual Platform v: N/A serial: VMware-56 4d
    40 b2 aa 1c 86-43 d9 b6 ea 8f e3 b0 45
  Mobo: Intel model: 440BX Desktop Reference Platform serial: N/A BIOS: Phoenix v: 6.00
    date: 11/12/2020
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         45 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    CPU family:          6
    Model:               158
    Thread(s) per core:  1
    Core(s) per socket:  1
    Socket(s):           4
    Stepping:            9
    BogoMIPS:            7823.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse
                         36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant
                         _tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_k
                         nown_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movb
                         e popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf
                         _lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbas
                         e tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt x
                         saveopt xsavec xgetbv1 xsaves arat flush_l1d arch_capabilities
Virtualization features: 
  Hypervisor vendor:     VMware
  Virtualization type:   full
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    1 MiB (4 instances)
  L3:                    12 MiB (4 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
  ```

**Comment by sequencerr** [comment]
_missing nest version, installed globally_
```
[System Information]
OS Version     : Linux 6.1
NodeJS Version : v20.8.0
NPM Version    : 10.1.0 

[Nest CLI]
Nest CLI Version : 10.1.18 

[Nest Platform Information]
platform-socket.io version : 10.2.7
websockets version         : 10.2.2
passport version           : 10.0.0
testing version            : 10.2.2
jwt version                : 10.1.0
```

**Comment by jmcdo29** [comment]
Your minimum reproduction is incomplete. It won't compile as there's missing, I'm guessing, libraries?

From the look of the dist, your "`src`" is actually normally at `server/src` and you have a `config` library as well. When typescript compiles this, it tries to keep the directory structure of your project the same in the `dist`, so you end up with `dist/server/src/main.js` As you never tell Nest that the main is to be found at `server/src/main`, it still tries to run `node dist/main` and gets this error. This is something that is common and well "reported" even though it isn't an issue with the CLI itself. Please use our [Discord](https://discord.gg/nestjs) for further support on this issue

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by sequencerr** [comment]
I'm going to. It's a bug report, isn't it?)

**Comment by jmcdo29** [comment]
_You_ think it's a bug report. _I_ think it's a misconfiguration. Without an actual reproduction and knowing what your code is doing, it's impossible to say, and as `nest start` is working for every other user, most likely it's not an issue with the framework

**Comment by sequencerr** [comment]
@micalevisk I hope so

**Comment by sequencerr** [comment]
Hello. @jmcdo29, I've correctly filled my bug report now. Can you check it out please?

**Comment by jmcdo29** [comment]
@sequencerr your reproduction **does not** reproduce the error you're describing. I'm able to run `yarn nest start --builder tsc` and `pnpm nest start --builder tsc` without any issue.

**Comment by sequencerr** [comment]
@jmcdo29 It does not work on my machine))
do you believe me?

**Comment by jmcdo29** [comment]
Hard to say why. I'll be happy to keep this discussion going **[on discord](https://discord.gg/nestjs)** like I've said several times now. But this is not a bug in the framework.

**Comment by jmcdo29** [comment]
After discussing on Discord, it was determined that I missed one of the reproduction steps (the `rm -rf dist`) which was crucial to causing the issue. The error comes from using `tsc` in incremental mode, deleting the `dist` and **not** deleting the `.tsbuildinfo` file, which Typescript would use to se the old project graph, find that no changes had been made, and not re-compile the project as the (now non-existent) dist __should__ be correct. The solution is to simply delete the `.tsbuildinfo` file and do a full re-compile
