### ISSUE TITLE
NestExpressApplication is strict to Content-Type json / raw / text / urlencoded

### ISSUE THREAD

**Issue by RoyLeibo** [nestjs/nest#12556]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am working on support SCIM protocol.
The requirements of the protocol specify that the Content-Type header should be sent with application/scim+json.
Express is removing the body from the request since the default body parser is application/json, and I can't find a way to add this SCIM format to the supported types.

### Describe the solution you'd like

I would like to be able to add application/scim+json as a supported body type to my application.
It will be great if it could be limited to a specific path prefix.

### Teachability, documentation, adoption, migration strategy

just allow different Content-Type in the bootstrap of the application

### What is the motivation / use case for changing the behavior?

Supporting different Content-Type

**Comment by micalevisk** [comment]
since new built-in body parsers won't be added - because there's no reason to as you can add it in your side - let's continue this thread here: https://stackoverflow.com/questions/77273241
