### ISSUE TITLE
Introducing @Logger(): A Property Decorator for Enhanced Logging Context in NestJS

### ISSUE THREAD

**Issue by virgenherrera** [nestjs/nest#12565]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No, is just a verbosity decrement.

### Describe the solution you'd like

Implement the @Logger() property decorator to empower NestJS applications with an enriched logging context, enhancing diagnostic capabilities and streamlining debugging procedures. This decorator, when applied to a class property, will automatically assign a logging context to it, ensuring that logs generated within the scope of the class are contextualized with relevant information. This facilitates more precise tracing of application flow and errors, especially in a microservices architecture where tracing transactions across service boundaries can be challenging. The @Logger() decorator abstracts the complexities involved in managing logging contexts, providing developers with a straightforward and intuitive way to incorporate detailed, context-specific logs into their applications. This not only aids in swiftly identifying and resolving issues but also significantly improves the overall observability of the system. Thus, the implementation of @Logger() represents a pivotal enhancement in application maintainability and operational excellence.

### Basic Usage

Implementing `@Logger()` in your class is straightforward. Simply decorate the property where you wish to assign the logging context.

```typescript
import { Logger } from '@nestjs/common';

class SampleService {
  @Logger()
  private readonly logger;

  someMethod(): void {
    this.logger.log('This is a log message with enriched context');
  }
}


### What is the motivation / use case for changing the behavior?

Simplify instantiation of logger

**Comment by jmcdo29** [comment]
So, essentially now you have 
```ts
@Logger()
private readonly logger: Logger;
```
instead of 
```ts
private readonly logger = new Logger(SampleService.name);
```

And if anyone has [`strictPropertyInitialization`](https://www.typescriptlang.org/tsconfig#strictPropertyInitialization) set to true they now have to tell Typescript that this property is fine, correct?

**Comment by micalevisk** [comment]
Perhaps that can leave as a 3rd-party lib. We have a lot of decorators already and I don't any see good reasons to add yet another one for non-functional changes

**Comment by micalevisk** [comment]
I think that this approach feels more idiomatic for Nest (and with less boilerplate code!):

```ts
@Injectable()
class AService {
  constructor(private readonly logger: Logger) {}

  onModuleInit(): void {
    this.logger.log('A')
  }
}

@Injectable()
class BService {
  constructor(private readonly logger: Logger) {}

  onModuleInit(): void {
    this.logger.log('B')
  }
}


@Module({
  providers: [
    AService,
    BService,

    {
      scope: Scope.TRANSIENT,
      provide: Logger,
      inject: [INQUIRER],
      useFactory: (instance) => new Logger(instance.constructor.name)
    }
  ]
})
export class AppModule {}
```

![image](https://github.com/nestjs/nest/assets/13461315/d242a6a1-efbf-47ae-8ea8-06805e318855)

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
