### ISSUE TITLE
in resolvers register the mutation/query based on env

### ISSUE THREAD

**Issue by Jazeb** [nestjs/nest#12563]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No it's not related to a problem.

### Describe the solution you'd like

In mutation / query decorator we have options, in that options tab we there should be a boolean option whether to register the mutation / query and create the GraphQL schema.
I want to only register and create schema of mutation if the environment is staging or development.

### Teachability, documentation, adoption, migration strategy

` @Mutation(() => Patient, { shouldRun: process.env.NODE_ENV !== 'production' })`
key name can be changed

### What is the motivation / use case for changing the behavior?

We can have a feature that mutation / query can be registered and created in schema based on environment.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
