### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by imcm7** [nestjs/nest#12578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

What primitive (or in that form) value is need to pass to validator to not satisfy that condition 
https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/packages/common/pipes/validation.pipe.ts#L113

to run next lines of code of that method, if it check if is primitive here too https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/packages/common/pipes/validation.pipe.ts#L122

and metatype can't be empty because it is used here
```
entity.constructor = metatype; 
and
entity = { constructor: metatype };


### Minimum reproduction code

---

### Steps to reproduce

_No response_

### Expected behavior

To transform and validate primitive values?

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

_No response_

### NestJS version

_No response_

### Packages versions

```json
--
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
If there's no metatype (e.g. `@Body() body`), or the metatype is a primitive, or there is a custom decorator being used and the option to enable the custom decorator validation is not enabled

For further questions, please use our discord server

**Comment by imcm7** [comment]
@jmcdo29 if the metatype is a primitive it stop at `if (!metatype || !this.toValidate(metadata)) { retrun }` and not go down to validation `const errors = await this.validate(entity, this.validatorOptions);`

**Comment by jmcdo29** [comment]
Apologies, to **not** satisfy the condition it needs to be essentially any custom class type, generally speaking, a DTO

**Comment by imcm7** [comment]
I know, but if it need to be DTO why the nex lines check for primitive https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/packages/common/pipes/validation.pipe.ts#L122

**Comment by jmcdo29** [comment]
Technically, the first primitive check in the `toValidate` checks if the type is `String`/`Boolean`/`Number` etc..the _class_ itself not the direct primitive. So it is possible the promise still passes down to further lines

**Comment by imcm7** [comment]
@jmcdo29 can you give me an example of a value to call ValidationPipe with it for that,
``
 } else if (isCtorNotEqual) {
      // when "entity" is a primitive value, we have to temporarily
      // replace the entity to perform the validation against the original
      // metatype defined inside the handler
      entity = { constructor: metatype };
    }
``
 I not understand, because the `if (isCtorNotEqual && !isPrimitive` is DTO but first?

**Comment by imcm7** [comment]
@jmcdo29 you mean that it is a promise that will resolve to primitive?

**Comment by imcm7** [comment]
Result to validate a primitive is need to pass a promise that resolve to primitive

**Comment by imcm7** [comment]
@jmcdo29 but if I pass number or Promise<Number> it always retrun NaN

**Comment by jmcdo29** [comment]
Apologies for any confusion, my phone auto corrected "primitive" to "promise". Now please, for further questions, use our Discord

**Comment by imcm7** [comment]
I simply asked for such primitive that will `still passes down to further lines`

**Comment by jmcdo29** [comment]
And I simply asked that you move this conversation to our discord, as that is where we generally provide support and discussion. As this is not a bug, it doesn't belong in the issues
