### ISSUE TITLE
The method stripProtoKeys do `delete value.__proto__;` but for that exists option

### ISSUE THREAD

**Issue by imcm7** [nestjs/nest#12579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The method stripProtoKeys do `delete value.__proto__;` but exists option

```
ValidationPipeOptions = {
     transformOptions: {
           excludePrefixes: ['__', '___'] ,
     },
};
```

https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/packages/common/pipes/validation.pipe.ts#L229

Or is not the same?

### Minimum reproduction code

--

### Expected behavior

--

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

--

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
We hard coded this in to handle a security conference in class-transformer
