### ISSUE TITLE
Introducing dependencies in import type will result in unresolved dependencies

### ISSUE THREAD

**Issue by hengshanMWC** [nestjs/nest#12604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Modify to import type
<img width="549" alt="image" src="https://github.com/nestjs/nest/assets/45714422/2108ebe0-8ae0-4574-9ea2-f13a4b2e63b1">

```bash
npm start
[Nest] 11555  - 2023/10/18 23:53:37   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AppController (?). Please make sure that the argument Function at index [0] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If Function is a provider, is it part of the current AppModule?
- If Function is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Function */ ]
  })

Error: Nest can't resolve dependencies of the AppController (?). Please make sure that the argument Function at index [0] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If Function is a provider, is it part of the current AppModule?
- If Function is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Function */ ]
  })

    at Injector.lookupComponentInParentModules
```

### Minimum reproduction code

https://github.com/hengshanMWC/nest-app-issues

### Steps to reproduce

```bash
nest new
cd nest-app
vim src/app.controller.ts
import { AppService } from './app.service'; -> import type { AppService } from './app.service';
pnpm start
```

### Expected behavior

`pnpm start`
<img width="769" alt="image" src="https://github.com/nestjs/nest/assets/45714422/3a4fbf68-b8c8-4a20-99f8-aa7e56159b08">

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
"@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
```

### Node.js version

20.8.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

```
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 100.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - /opt/homebrew/bin/node
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.5.1 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.70
    Safari: 17.0
```

**Comment by jmcdo29** [comment]
This is the expected behavior. When using a `type` import, Typescript will not set the emitted metadata to have the correct class reference, Ava as such nest won't be able to resolve the dependency based on the incorrect metadata
