### ISSUE TITLE
Error in ClassSerializerInterceptor

### ISSUE THREAD

**Issue by metinjakupi** [nestjs/nest#12619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="1343" alt="Screenshot 2023-10-20 at 16 58 17" src="https://github.com/nestjs/nest/assets/32740979/5f9432be-3d84-423e-ac3c-ed0c04ff96f4">

### Minimum reproduction code

#

### Steps to reproduce

I encountered this issue when attempting to register a new user via the API. Strangely, it only started happening today.

### Expected behavior

<!--->

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.7

### Packages versions

```json
"@nestjs-modules/mailer": "^1.9.1",
    "@nestjs/axios": "^3.0.0",
    "@nestjs/common": "^10.2.7",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.7",
    "@nestjs/jwt": "^10.1.1",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "^10.2.7",
    "@nestjs/swagger": "^7.1.13",
    "@nestjs/typeorm": "^10.0.0",
       "@nestjs/cli": "^10.1.18",
    "@nestjs/schematics": "^10.0.2",
    "@nestjs/testing": "^10.2.7",
```

### Node.js version

v18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
> it only started happening today

have you upgraded some package or what?


## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment]
what's the output of `app.get(Reflector)`? make sure it's an instance of `Reflector`

Also, instad of `app.useGlobalInterceptors`, try it out with [`APP_INTERCEPTOR`](https://docs.nestjs.com/interceptors#binding-interceptors)

**Comment by metinjakupi** [comment]
output of the app.get(Reflector)
Reflector {}

i used in app.module.ts with APP_INTERCEPTOR im having the same issue

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
