### ISSUE TITLE
Hi @kamilmysliwiec I'm trying to inject `CONTEXT` just as  @appsolutegeek did, but I get this error:

### ISSUE THREAD

**Issue by appasaheb4** [nestjs/nest#12625]
Hi @kamilmysliwiec I'm trying to inject `CONTEXT` just as  @appsolutegeek did, but I get this error:

`"TypeError: Cannot read property 'getInstanceByContextId' of undefined",
            "    at Injector.loadInstance (/Users/babajide/workspace/andela/myandela-server/node_modules/@nestjs/core/injector/injector.js:59:38)",
            "    at Injector.loadPerContext (/Users/babajide/workspace/andela/myandela-server/node_modules/@nestjs/core/injector/injector.js:279:20)",
            "    at ResolversExplorerService.<anonymous> (/Users/babajide/workspace/andela/myandela-server/node_modules/@nestjs/graphql/dist/services/resolvers-explorer.service.js:110:61)",
            "    at Generator.next (<anonymous>)",
            "    at /Users/babajide/workspace/andela/myandela-server/node_modules/@nestjs/graphql/dist/services/resolvers-explorer.service.js:19:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/Users/babajide/workspace/andela/myandela-server/node_modules/@nestjs/graphql/dist/services/resolvers-explorer.service.js:15:12)",
            "    at resolverCallback (/Users/babajide/workspace/andela/myandela-server/node_modules/@nestjs/graphql/dist/services/resolvers-explorer.service.js:94:51)",
            "    at field.resolve (/Users/babajide/workspace/andela/myandela-server/node_modules/graphql-extensions/dist/index.js:140:26)",
            "    at resolveFieldValueOrError (/Users/babajide/workspace/andela/myandela-server/node_modules/graphql/execution/execute.js:486:18)"`

Is there anything I'm doing wrong?

_Originally posted by @jidesakin in https://github.com/nestjs/nest/issues/1905#issuecomment-502724344_

**Comment by appasaheb4** [comment]
facing same issue

**Comment by appasaheb4** [comment]
Hi team,
Issue fixed please check below code 
```
@Inject(forwardRef(() => CONTEXT)) private context
```

**Comment by Tony133** [comment]
If the problem has been solved, I would say that this issue can be closed, right?

**Comment by appasaheb4** [comment]
Till facing issue:
[Nest] 7728  - 10/29/2023, 11:49:16 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'aggregate')
TypeError: Cannot read properties of undefined (reading 'aggregate')
