### ISSUE TITLE
SWC builder error

### ISSUE THREAD

**Issue by peiyanlu** [nestjs/nest#12623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Problem with routing mapping when using SWC as a builder

### Minimum reproduction code

https://github.com/peiyanlu/nest-swc-test

### Expected behavior

SWC builder can work normally

### Package

- [x] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.7

### Packages versions

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/

[System Information]
OS Version     : Windows 10
NodeJS Version : v18.16.0
PNPM Version    : 8.6.6 

[Nest CLI]
Nest CLI Version : 10.1.18

[Nest Platform Information]
platform-express version : 10.2.7
schematics version       : 10.0.2
testing version          : 10.2.7
common version           : 10.2.7
core version             : 10.2.7
cli version              : 10.1.18

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

[nest-swc.zip](https://github.com/nestjs/nest/files/13059895/nest-swc.zip)

**Comment by micalevisk** [comment]
both `npm start` and `npm build` went fine here on Linux; nodejs 18

```
git clone git@github.com:peiyanlu/nest-swc-test.git
cd nest-swc-test
npm i
npm start
```

**Comment by peiyanlu** [comment]
> both `npm start` and `npm run build` went fine here on Linux; nodejs 18
> 
> ```
> git clone git@github.com:peiyanlu/nest-swc-test.git
> cd nest-swc-test
> npm i
> npm start
> ```


Thank you, but I'm sorry, I don't have a Linux environment. In a Windows environment, there are some issues with `pnpm start: dev` and updates. If you run the real-time generated dist directory file, it is also normal, but the results brought by `pnpm start: dev` are incorrect. I provided a video at the end of the issues that briefly recorded this behavior

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the swc repository
