### ISSUE TITLE
Cannot access 'Logger' before initialization

### ISSUE THREAD

**Issue by imcm7** [nestjs/nest#12626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/packages/common/utils/load-package.util.ts#L6

### Minimum reproduction code

-

### Steps to reproduce

```
const logger = new Logger('PackageLoader');  // in more strict mode compiller say it can't access it before initialization

export function loadPackage(
  packageName: string,
  context: string,
  loaderFn?: Function,
) {
  try {
    return loaderFn ? loaderFn() : require(packageName);
  } catch (e) {
    logger.error(MISSING_REQUIRED_DEPENDENCY(packageName, context));
    Logger.flush();
    process.exit(1);
  }
}
```

### Expected behavior

That work well

```
export function loadPackage(
  packageName: string,
  context: string,
  loaderFn?: Function,
) {
  try {
    return loaderFn ? loaderFn() : require(packageName);
  } catch (e) {
    const logger = new Logger('PackageLoader'); // here
    logger.error(MISSING_REQUIRED_DEPENDENCY(packageName, context));
    Logger.flush();
    process.exit(1);
  }
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

last

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by imcm7** [comment]
I put in ts config strict mode and try to correct all errors from nest js

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by jmcdo29** [comment]
I couldn't reproduce this locally

**Comment by imcm7** [comment]
@jmcdo29 also https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/packages/core/injector/module.ts#L42

it is not used anywhere.

**Comment by micalevisk** [comment]
@imcm7 that unused import has been removed in PR #12561

---

> I put in ts config strict mode and try to correct all errors from nest js

please share the exact steps to reproduce that. Which files do we need to change? Which command do we need to run to see the errrors?

**Comment by imcm7** [comment]
I ue such tsconfig.json

```
// Generated by nuxi
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "jsxImportSource": "vue",
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Node",
    "skipLibCheck": true,
    "isolatedModules": false,
    "useDefineForClassFields": true,
    "strict": true,
    "noImplicitThis": true,
    "esModuleInterop": true,
    "allowJs": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "paths": {
      "~": [
        ".."
      ],
      "~/*": [
        "../*"
      ],
      "@": [
        ".."
      ],
      "@/*": [
        "../*"
      ]
    },
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

**Comment by imcm7** [comment]
And I something touched in code and services not injecting in controller, and I can't find what I broke.

>TypeError: undefined is not an object (evaluating 'this.appService.getHello')
    at getHello (/home/Project/server/src/app.controller.ts)
    at <anonymous> (/home/Project/server/libraries/core/router/router-execution-context.ts)

**Comment by kamilmysliwiec** [comment]
Please, let's provide a minimum reproduction repository next time you create an issue in this repository.
