### ISSUE TITLE
Logger injection issue

### ISSUE THREAD

**Issue by sodamnfoolish** [nestjs/nest#12632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Custom logger make an error some times
```
/app/node_modules/@nestjs/common/services/console-logger.service.js:48

if (!this.isLevelEnabled('error')) {

^

TypeError: Cannot read properties of undefined (reading 'isLevelEnabled')

at error (/app/node_modules/@nestjs/common/services/console-logger.service.js:48:19)

at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Logger injection:
```
await NestFactory.createApplicationContext(AppModule, {
    logger: new TelegramLogger(
      env.TELEGRAM_TOKEN,
      env.TELEGRAM_CHAT_ID,
      `${env.token}`
    ),
  });
```

Logger implementation:
```
import { Injectable, ConsoleLogger } from '@nestjs/common';
import { Telegram } from 'telegraf';

export class TelegramLoggerOptions {
  verbose?: boolean;
  log?: boolean;
  warn?: boolean;
  error?: boolean;
}

@Injectable()
export class TelegramLogger extends ConsoleLogger {
  private readonly telegram: Telegram;
  private readonly logLevels: TelegramLoggerOptions;

  constructor(
    token: string,
    private readonly chatId: string,
    context: string,
    logLevels?: TelegramLoggerOptions
  ) {
    super(context);
    this.telegram = new Telegram(token);
    this.logLevels = {
      verbose: logLevels?.verbose ?? true,
      log: logLevels?.log ?? true,
      warn: logLevels?.warn ?? true,
      error: logLevels?.error ?? true,
    };
  }

  private sendMessage(message: string) {
    this.telegram.sendMessage(this.chatId, message).catch(super.error);
  }

  public verbose(message: any) {
    if (this.logLevels.verbose)
      this.sendMessage(`🟦 ${this.context}\n${message}`);
    super.verbose(message);
  }

  public log(message: any) {
    if (this.logLevels.log) this.sendMessage(`🟩 ${this.context}\n${message}`);
    super.log(message);
  }

  public warn(message: any) {
    if (this.logLevels.warn) this.sendMessage(`🟧 ${this.context}\n${message}`);
    super.warn(message);
  }

  public error(message: any) {
    if (this.logLevels.error) this.sendMessage(`🟥 ${this.context}\n${message}`);
    super.error(message);
  }
}

```

### Minimum reproduction code

https://github.com/

### Expected behavior

Throw the real error

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^10.0.2

### Packages versions

```json
"@nestjs/common": "^10.0.2",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.2",
    "@nestjs/platform-express": "^10.0.2",
    "@nestjs/schedule": "^3.0.1",
    "@nestjs/swagger": "^7.1.1",
    "@nestjs/typeorm": "^10.0.0",
"@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.0.2",
```

### Node.js version

18.16.1

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment]
you're using `createApplicationContext`
maybe you need to call `await app.init()` as well?

**Comment by micalevisk** [comment]
I can't tell if is the case but if you have something like:

```js
const foo = logger.log
foo("bar")
```

you'll see that error due to how JS works.

**Comment by sodamnfoolish** [comment]
@jmcdo29 @kamilmysliwiec reproduction repo: https://github.com/sodamnfoolish/nest-telegram-logger
it looks like the problem is rate limit on Telegram Bot API, but I'm not sure

**Comment by jmcdo29** [comment]
This is not an issue with the logger, but rather how you call `super.error` in the `.catch` of your `sendMessage` method. You need to `.catch(super.catch.bind(this))` or `.catch(err => super.catch(err))`. Standard `this` reference stuff with JS and not related to Nest at all
