### ISSUE TITLE
"nest stop" for CLI

### ISSUE THREAD

**Issue by tonebonekone** [nestjs/nest#12659]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The CLI does not provide an explicit way to stop processes spawned from `nest start` and  `nest start --watch`. In order to stop these processes, developer has to rely on shell commands, which is a leaky abstraction.  

### Describe the solution you'd like

If `nest start` is the on switch, need something like `nest stop` as the off switch.  

This is especially applicable for `nest start --watch`. The CLI should track the spawned process ids and gracefully stop them when something like `nest stop` is invoked. Currently the developer must stop them at a lower level (`"kill $(lsof -t -i :5050)` or in the case of `--watch`, `killall node` (not recommended!) , etc.).  

### Teachability, documentation, adoption, migration strategy

Ctrl+C is fine in a manual context, but one of the benefits of the CLI is that its commands can be invoked through npm scripts for automated E2E development workflows. By having the CLI be responsible for managing the lifecycle of its own abstracted NodeJS processes, the developer can write composable workflows that manage the lifecycles of a nest instance, its test and the DB (including migrations and teardowns).

For example, our implementation consists of a Typescript Nest server that connects to multiple DBs with migrations. A given npm script would include sub-routines like:

```
rm -rf ./db                // delete a bunch of DB artifacts 
&& nest start (--watch).   // starts nest, provisions fresh DB, runs migrations, etc.
&& node myscript.js        // provisions additional data to DB to get it to a given state
&& nest stop               // stops nest and attendant processes
&& (jest, k6)              // run tests against a re-provisioned DB with a given state
```

### What is the motivation / use case for changing the behavior?

So the CLI can be part of composable, automated E2E developer workflows

**Comment by micalevisk** [comment]
we would have to supply some PID to `nest stop`, right? as we could have multiple `nest start` running at same time

**Comment by jmcdo29** [comment]
I'm not sure I see the benefit here. Correct me if I'm mistaken, but if your `nest start` spins up a server, then the `node myscript.ts` and further commands won't run anyway, right? Because the `nest start` (which is essentially `tsc -p tsconfig.build.json && node dist/main`) will not exit, and with no exit code the terminal won't continue the chain of commands. So even if we did create a `nest stop` command, in this case it wouldn't change anything, as the `nest start (--watch)` is a command chain blocker

**Comment by tonebonekone** [comment]
@jmcdo29 it is possible to invoke commands to stop the nestJS server in a separate execution context to continue the overall workflow. apologies for horrific example, but it can be accomplished via something like this npm script:

```
// delete existing DB
rm -rf ./data/db/local
// start server, which provisions a new DB and runs migrations
&& NODE_ENV=local concurrently -r \"yarn format\" \"nest start --watch\" 
// give it some time, then stop the server
& sleep 4 && kill $(lsof -t -i :5050) 

// test against the DB
&& jest app --silent=false

// restart the server and run load tests against it a third-party service.
yarn start:nest & sleep 15 && k6 run ./scripts/utils/load.js 

// stop server upon third-party service returning control back to execution context
&& kill $(lsof -t -i :5050) 
```

this process can work with --watch as well, but you can end up with dangling task runners. or `killall node`, which can shut off unrelated processes to node

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement this in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
