### ISSUE TITLE
Can't inject with property-based injection.

### ISSUE THREAD

**Issue by ph55** [nestjs/nest#1265]
I have one class extend another one.
In order not to drag dependency through constructor and `super` I try to inject via property injection.

From docs:

> Property-based injection
In some very specific cases, a property-based injection might be useful. For instance, if your top-level class depends on either one or multiple providers, passing them all the way up by calling super() in sub-classes from the constructor can be very annonying. Thus, in order to avoid it, you can use @Inject() decorator on a property level.

```ts
import { Injectable, Inject } from '@nestjs/common';

@Injectable()
export class HttpService<T> {
  @Inject('HTTP_OPTIONS')
  private readonly httpClient: T;
}
```

I'm trying to replace this:
```ts
  public constructor(
    private configService: ConfigService
  ) {
    super();
  }
```

with this:

```ts
@Inject(ConfigService) private readonly configService: ConfigService;
// or this
@Inject('CONFIG_SERVICE_PROVIDER') private readonly configService: ConfigService;
```

But there is ts error:
`TS1240: Unable to resolve signature of property decorator when called as an expression.`

And `configService` undefined.

![image](https://user-images.githubusercontent.com/1386622/48086753-4596ec00-e206-11e8-8573-791e447f9594.png)

**Comment by ph55** [comment]
Maybe it's worth to expose static `get` like in angular. So you can do something like:

```ts
  private configService: ConfigService;

  constructor() {
    this.configService = Injector.get(ConfigService);
  }
```

**Comment by marcus-sa** [comment]
https://github.com/nestjs/nest/issues/1014

**Comment by marcus-sa** [comment]
@ph55 

this should work

```ts
import { Injector } from '@nestjs/core'; 

@Injectable()
abstract class BaseService {
  protected readonly core: CoreService;

  constructor(injector: Injector) {
    this.core = injector.get<CoreService>(CoreService);
  }
}

@Injectable()
export class FirstService extends BaseService {
  // this.core should be an instance of CoreService
}
```

**Comment by kamilmysliwiec** [comment]
Above solution won't work because there is no `Injector`, instead, we have `ModuleRef` class. However, @ph55 it looks that you haven't updated your packages yet. Please, upgrade to 5.4.0 and issues will disappear.

**Comment by ph55** [comment]
Oh, I see. It only introduced in latest 5.4

So I guess origin of confusion is that documentation not versioned.
Thanks.
