### ISSUE TITLE
"Module Not Found" error, 

### ISSUE THREAD

**Issue by HARISHIMSS** [nestjs/nest#12665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="473" alt="image" src="https://github.com/nestjs/nest/assets/108579608/9a9d55f3-8a1f-471f-a9c2-569d0cdf4193">

### Minimum reproduction code

Simply create a new project and run the project

### Steps to reproduce

1. Just create a new nest project
2. Try to run the project

### Expected behavior

Just it should start the project without any errors

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.0

### Packages versions

```json
"@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"

"@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
```

### Node.js version

20.9.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I didn't manage to reproduce this on linux. Seems to be a nodejs windows-only issue. Try to rename your directory.

![image](https://github.com/nestjs/nest/assets/13461315/5896d710-49f1-4600-9dac-c94275ce108e)


## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by HARISHIMSS** [comment]
> I didn't manage to reproduce this on linux. Seems to be a nodejs windows-only issue. Try to rename your directory.
> 
> ![image](https://user-images.githubusercontent.com/13461315/278205935-5896d710-49f1-4600-9dac-c94275ce108e.png)
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

@micalevisk I tried with changing the name and couple of alternate suggestions also. But, its not working in windows

**Comment by micalevisk** [comment]
@HARISHIMSS I'd suggest you to find which version was working before, incluing switching nodejs version, if you think that this was the reason

```bash
npm ini nest
# after creating the project play with the version of `@nestjs/cli`
```

**Comment by HARISHIMSS** [comment]
Thank you @micalevisk
