### ISSUE TITLE
Controller handler parameters rejected pipes resolution priority

### ISSUE THREAD

**Issue by GeLoLabs** [nestjs/nest#12668]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello,

I dig into an issue related to controller handler parameters rejected pipes resolution priority.

Let's use a concrete example to demonstrate the issue, given the following simple controller handler:

```
async create(
  @Body(ValidationPipe) cmd: UserPermissionCreate,
  @Param('id', UserPipe) user: User,
): Promise<UserPermission> {
  return await this.manager.create(user, cmd);
}
```

According to the [documentation](https://docs.nestjs.com/faq/request-lifecycle#pipes), the `RouterExecutionContext` will go through pipes trigerring first my `UserPipe` and then go through the `ValidationPipe`. I debug it, and all is fine, the `UserPipe` is first trigerred and then, the `ValidationPipe` is trigerred.

The issue comes when dealing with exceptions thrown in pipes. My `UserPipe` is an heavy pipe, it does database connection and so, by design, it is slow whereas the `ValidationPipe` runs fast.

Since the `RouterExecutionContext` resolves all pipes for all parameters and then, it resoles there values concurrently using `Promise.all`, the first promise which rejects is the one which will be used. 

In my example, the `ValidationPipe` runs more fastly than my `UserPipe` and so, throw first and the resulting exception is returned to the end user (400 - Bad Request).

As you start understand, it is not the expected behavior for me, I would like to get the exception from my `UserPipe` first if it has thrown or if not, go to the next controller param, check if it has thrown and so on. The final result would be to get a 404 - Not Found, instead of a 400 - Bad Request.

So far, for now, I was not able to find a workaround to this issue. Am I missing something ?

### Describe the solution you'd like

IMHO, we should be able to control the priority of the controller parameters rejected pipes instead of relying "randomly" on the first one which reject.

Breaking the current behavior is not an option, so what about introducing a new decorator, something like `PipeStrategy('default' | 'strict')` in order to control this behavior.

Then in the `RouterExecutionContext.createPipesFn` we can use `Promise.allSettled` or `Promise.all` according to the pipe strategy and reject accordingly:

Default strategy (current behavior):

```
await Promise.all(paramsOptions.map(resolveParamValue))
```

Strict Strategy (new behavior):

```
await Promise.allSettled(paramsOptions.map(resolveParamValue)).then((results) => {
  results.forEach((result) => {
    if (result.status === 'rejected') {
      throw result.reason;
    }
   })
});
```

### Teachability, documentation, adoption, migration strategy

Then, end user would use the feature this way:

```
@PipeStrategy('strict')
async create(
  @Body(ValidationPipe) cmd: UserPermissionCreate,
  @Param('id', UserPipe) user: User,
): Promise<UserPermission> {
  return await this.manager.create(user, cmd);
}
```

### What is the motivation / use case for changing the behavior?

The motivation is to be able to control the priority of the controller parameters rejected pipes.

**Comment by GeLoLabs** [comment]
An other solution / proposition would be to use a decorator like `PipeStrategy('concurrent' | 'sequential')` and then, update the `RouterExecutionContext.createPipesFn` with:

Concurrent strategy (current behavior):

```
await Promise.all(paramsOptions.map(resolveParamValue))
```

Sequential Strategy (new behavior):

```
for (const param of paramsOptions) {
  await resolveParamValue(param);
}
```

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
