### ISSUE TITLE
Property 'pipes' does not exist on type 'RouteParamMetadata'

### ISSUE THREAD

**Issue by imcm7** [nestjs/nest#12674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

> Property 'pipes' does not exist on type 'RouteParamMetadata'

https://github.com/nestjs/nest/blob/044012283a079ffd96365f37e0f6571b69ac67e6/packages/core/router/router-execution-context.ts#L294

Here you use metadata.pipes

```
const { index, data, pipes: pipesCollection } = metadata[key];
```

Metadata is of type RouteParamMetadata, but RouteParamMetadata don't have field pipes https://github.com/nestjs/nest/blob/044012283a079ffd96365f37e0f6571b69ac67e6/packages/common/decorators/http/route-params.decorator.ts#L25

### Minimum reproduction code

https://github.com/nestjs/nest/blob/master/packages/common/decorators/http/route-params.decorator.ts#L25

### Expected behavior

No type errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

-

### Packages versions

-

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I didn't understand what do you want, exactly :thinking:

**Comment by imcm7** [comment]
@micalevisk and here https://github.com/nestjs/nest/blob/044012283a079ffd96365f37e0f6571b69ac67e6/packages/websockets/context/ws-context-creator.ts#L210

metadata is `metadata: TMetadata` but in 

https://github.com/nestjs/nest/blob/044012283a079ffd96365f37e0f6571b69ac67e6/packages/core/router/router-execution-context.ts#L285

is  Record<number, RouteParamMetadata>

And now I have 

```
Type '({ index: number; extractValue: (...args: unknown[]) => unknown; type: string; data: ParamData | undefined; pipes: any[]; } | undefined)[]' is not assignable to type 'ParamProperties[]'.
  Type '{ index: number; extractValue: (...args: unknown[]) => unknown; type: string; data: ParamData | undefined; pipes: any[]; } | undefined' is not assignable to type 'ParamProperties'.ts
  ``

**Comment by imcm7** [comment]
stupid code

**Comment by imcm7** [comment]
and `return [] as T;` 
```
Conversion of type 'never[]' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  'never[]' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'any[]'.
  ```
