### ISSUE TITLE
Emit Not Broadcasting to All Clients with WSAdapter in NestJS

### ISSUE THREAD

**Issue by mwaeckerlin** [nestjs/nest#12679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using NestJS with the WSAdapter (ws WebSockets instead of socket.io), I expected that calling `this.server.emit('test', 'hello event')` would broadcast to all connected clients and return `true` upon a successful connection. However, in reality, invoking `this.server.emit('test', 'hello event')`  returns `false` and no messages are sent to the clients.

### Minimum reproduction code

https://github.com/nestjs/nest/blob/master/sample/16-gateways-ws

### Steps to reproduce

1. Clone the NestJS sample for WebSockets from [here](https://github.com/nestjs/nest/blob/master/sample/16-gateways-ws/src/events/events.gateway.ts).
2. Add `this.server.emit('test', 'hello event')` to the `onEvent` method.
3. Observe that the `emit` function does not broadcast to the clients and returns `false`.

### Expected behavior

Same behavior of `this.server.emit` as with `socket.io`: It broadcasts to all connected clients:

On
```
@WebSocketServer() server: Server
…
this.server.emit('test', 'hello event')`
```
the function returns true and all clients receive: `{"event":"test","data":"hello event"}` in `data`.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [X] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.6

### Packages versions

```json
{
  "name": "nest-typescript-starter",
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint '{src,apps,libs,test}/**/*.ts' --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "echo 'No e2e tests implemented yet.'"
  },
  "dependencies": {
    "@nestjs/common": "10.2.6",
    "@nestjs/core": "10.2.6",
    "@nestjs/platform-express": "10.2.6",
    "@nestjs/platform-ws": "10.2.6",
    "@nestjs/websockets": "10.2.6",
    "class-transformer": "0.5.1",
    "class-validator": "0.14.0",
    "rimraf": "5.0.5",
    "reflect-metadata": "0.1.13",
    "rxjs": "7.8.1",
    "ws": "8.13.0"
  },
  "devDependencies": {
    "@types/ws": "8.5.5",
    "@nestjs/cli": "10.1.18",
    "@nestjs/schematics": "10.0.2",
    "@nestjs/testing": "10.2.6",
    "@types/express": "4.17.18",
    "@types/node": "20.8.7",
    "@types/supertest": "2.0.15",
    "jest": "29.7.0",
    "prettier": "3.0.3",
    "supertest": "6.3.3",
    "ts-jest": "29.1.1",
    "ts-loader": "9.4.4",
    "ts-node": "10.9.1",
    "tsconfig-paths": "4.2.0",
    "@typescript-eslint/eslint-plugin": "5.62.0",
    "@typescript-eslint/parser": "5.62.0",
    "eslint": "8.42.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-plugin-import": "2.29.0",
    "typescript": "5.2.2"
  }
}
```

### Node.js version

20.5.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Possible Workaround:

```
import {OnGatewayConnection, OnGatewayDisconnect, SubscribeMessage, WebSocketGateway, WebSocketServer, WsResponse} from '@nestjs/websockets'
import {from, Observable} from 'rxjs'
import {map} from 'rxjs/operators'
import {Server} from 'ws'

@WebSocketGateway(8080)
export class EventsGateway implements OnGatewayConnection, OnGatewayDisconnect {
  @WebSocketServer()
  server: Server

  handleConnection(socket: WebSocket) {
    this.server.on('event', (event, data) => socket.send(JSON.stringify({event, data})))
  }

  handleDisconnect(socket: WebSocket) {}

  @SubscribeMessage('events')
  onEvent(client: any, data: any): Observable<WsResponse<number>> {
    console.log('received:', data)
    console.log('emitted:', this.server.emit('event', 'test', 'hello event'))
    return from([1, 2, 3]).pipe(map(item => ({event: 'events', data: item})))
  }

  @SubscribeMessage('message')
  onMessage(client: any, data: any) {
    console.log('received:', data)
    this.server.emit('test', 'hello message')
    return {event: 'message', data: 'got some data'}
  }
}
```

- Would probably also require a deregister on `handleDisconnect`
- connect/disconnect should be hidden in the framework
- parameter `'event'` in `this.server.emit` should be hidden in the framework

**Comment by mwaeckerlin** [comment]
**I got a solution** by adapting the existing `WsAdapter` class in `packages/platform-ws/adapters/ws-adapter.ts`:
- add registration and deregistration of clients to `bindClientConnect` and `bindClientDisconnect`
- change the `emit` function of the server in `create`

→ please add my patch to `WsAdapter`: 
[wsadapter.ts.diff.txt](https://github.com/nestjs/nest/files/13226178/wsadapter.ts.diff.txt)

My changes:

Add / Replace:
```typescript
  private clientData = new Map<WebSocket, { server: any, listener: (...args: any[]) => void }>();

  public bindClientConnect(server: any, callback: Function) {
    server.on(CONNECTION_EVENT, (client: any) => {
      const listener = (event, data) => client.send(JSON.stringify({event, data}));
      server.on('event', listener);
      this.clientData.set(client, { server, listener });      
      callback(client);
    });
  }
  
  public bindClientDisconnect(client: any, callback: Function) {
    client.on(CLOSE_EVENT, () => {
      const data = this.clientData.get(client);
      if (data) {
        data.server.removeListener('event', data.listener);
        this.clientData.delete(client);
      }
      callback();
    });
  }
```

In `create`, for all places where a server is created / returned, add before returning or registration:
```typescript
      const origEmit = wsServer.emit.bind(wsServer);
      wsServer.emit = (event: string, data: any) => origEmit('event', event, data);
```

Which ends up in:
```
  public create(
    port: number,
    options?: Record<string, any> & {
      namespace?: string;
      server?: any;
      path?: string;
    },
  ) {
    const { server, path, ...wsOptions } = options;
    if (wsOptions?.namespace) {
      const error = new Error(
        '"WsAdapter" does not support namespaces. If you need namespaces in your project, consider using the "@nestjs/platform-socket.io" package instead.',
      );
      this.logger.error(error);
      throw error;
    }

    if (port === UNDERLYING_HTTP_SERVER_PORT && this.httpServer) {
      this.ensureHttpServerExists(port, this.httpServer);
      const wsServer = this.bindErrorHandler(
        new wsPackage.Server({
          noServer: true,
          ...wsOptions,
        }),
      );
    
      const origEmit = wsServer.emit.bind(wsServer);
      wsServer.emit = (event: string, data: any) => origEmit('event', event, data);

      this.addWsServerToRegistry(wsServer, port, path);
      return wsServer;
    }

    if (server) {
        const origEmit = server.emit.bind(server);
        server.emit = (event: string, data: any) => origEmit('event', event, data);
        return server;
    }
    if (path && port !== UNDERLYING_HTTP_SERVER_PORT) {
      // Multiple servers with different paths
      // sharing a single HTTP/S server running on different port
      // than a regular HTTP application
      const httpServer = this.ensureHttpServerExists(port);
      httpServer?.listen(port);

      const wsServer = this.bindErrorHandler(
        new wsPackage.Server({
          noServer: true,
          ...wsOptions,
        }),
      );
      const origEmit = wsServer.emit.bind(wsServer);
      wsServer.emit = (event: string, data: any) => origEmit('event', event, data);
      this.addWsServerToRegistry(wsServer, port, path);
      return wsServer;
    }
    const wsServer = this.bindErrorHandler(
      new wsPackage.Server({
        port,
        path,
        ...wsOptions,
      }),
    );
    const origEmit = wsServer.emit.bind(wsServer);
    wsServer.emit = (event: string, data: any) => origEmit('event', event, data);
    return wsServer;
  }
```

**Comment by micalevisk** [comment]
If you believe you've got a bug fix, please open a pull request

**Comment by mwaeckerlin** [comment]
@micalevisk, I'd prefer to discuss the solution first; and I'm still testing.

I found one issue in my approach: If `server.emit` is explicitly called with 3 arguments, then the original function should be called unchainged:

```
  private replaceEmit(server) {
    const origEmit = server.emit.bind(server)
    server.emit = (event: string, data: any, param3?: any) =>
      param3 !== undefined
        ? origEmit(event, data, param3)
        : origEmit('event', event, data)
  }
```

Otherwise we miss `wsServer.emit('connection', ws, request)` in http-server-upgrade.

**Comment by mwaeckerlin** [comment]
My changes are [here](https://github.com/Scrypt-Swiss/nest-fork/tree/mrw-fix-ws-adapter-emit-%2312679), ready for pull request, but `sh scripts/run-integration.sh` fails: 
```
  1) WebSocketGateway (WsAdapter)
       "after each" hook for "should handle message (2nd port)":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/marc/git/nest/integration/websockets/e2e/ws-gateway.spec.ts)
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7)
```

Looks like `await app.close();` does not terminate within 2s, even though the test case was succesfull.

@micalevisk, do you have any idea, what could be the problem? What could prevent `app` from closing?

[This is my actual change](https://github.com/Scrypt-Swiss/nest-fork/commit/cd16af1d63e5c9d4c6420f4e223aa640963bf5d2) (you can ignore the sample, just one file `ws-adapter.ts`)

**Comment by kamilmysliwiec** [comment]
Thanks for sharing the solution to this issue with others, but I don't think we should be altering the default ws behavior at the framework level.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.

**Comment by mwaeckerlin** [comment]
Would it be "altering the default ws behavior"? IMHO it would rather be fixing the ws behavior so that it works and behaves the same way as in the socket.io implementation.

It is not even documented, that `emit` does not work with ws! At least documentation should be updated!

But why not simply make it work?

So I don't agree with closing this ticket, @kamilmysliwiec.

My guess is more, that ws is seldom used, so no one complained before?

**Comment by micalevisk** [comment]
> At least documentation should be updated!

We know that there are lacks in the docs for that subject. PRs are more than welcome to improve it

Also, I'd suggest you to read this: https://gist.github.com/g1eny0ung/9e7d4d0f72547a8d156452e76fa8f7a3
