### ISSUE TITLE
Issue when utilizing an enum during initialization

### ISSUE THREAD

**Issue by ctsstc** [nestjs/nest#12671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Scenario 1

During tests I get an error like:

```
TypeError: Cannot read properties of undefined (reading 'chosenType')
```

### `some-service.ts`
```ts
@Inectable()
export class SomeService {
  private readonly someType = SomeEnum.chosenType
}
```

### `some.module.ts`
```ts
@Module({
  providers: [SomeService],
  exports: [SomeService]
})
```

### `some-service.spec.ts`
```ts
describe(SomeService, () => {
  let service: SomeService

  beforeEach(async () => {
    const module = await Test.createTestingModule({
      providers: [SomeService],
    }).compile()
    service = module.get(SomeService)
  })
})
```

## Scenario 2

In my mocks I'll get an error like this while testing:

```
TypeError: Cannot read properties of undefined (reading 'chosenType')
```

### `some.mocks.ts`
```ts
export const mockThingIAmUsing = {
  hello: 'world',
}

export const mockSomething = {
  type: SomeEnum.chosenType,
}
```

### `some-service.spec.ts`
```ts
import { mockThingIAmUsing } from './some.mocks.ts'

console.log("The Thing:", mockThingIAmUsing)

describe(SomeService, () => {
  let service: SomeService

  beforeEach(async () => {
    const module = await Test.createTestingModule({
      providers: [SomeService],
    }).compile()
    service = module.get(SomeService)
  })
})
```

## A Get Around

I've found if I mock out the library and provide the actual implementation the issue goes away.

```ts
jest.mock('@org/library-name', () => {
  const actual = jest.requireActual('@org/library-name')

  return {
    ...actual,
    SomeEnum: {
      ...actual.SomeEnum,
    },
  }
})
```

### Minimum reproduction code

Soon™

### Steps to reproduce

I am struggling to determine if this is a NestJS issue, dependency injection issue, node, transpilation, tree shaking, swc issue or a mix of them¿?!

These seem to be related:
- https://github.com/nestjs/nest/issues/2315
- https://stackoverflow.com/questions/71384390/nestjs-cannot-resolve-enum-jest
	- Marked as duplicate but the duplicate doesn't seem relevant; the question doesn't really get resolved.
- https://stackoverflow.com/a/51158269/349659
	- This is a pattern we use in our shared libraries, I seem to be having this with a library we've created so I wonder if this is the issue?

I had a similar issue when I initially switched from `ts-jest` to `@swc/jest` as the jest transpiler/transformer, but it semed to be related to a possible circular dependency or due to putting an enum definition in a module; once it was separated into its own file the issue went away.

### Expected behavior

The enum should be defined and resolve without issue.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.1.11

### Packages versions

```
[System Information]
OS Version     : macOS
NodeJS Version : v18.16.0
NPM Version    : 9.5.1 

[Nest CLI]
Nest CLI Version : 10.1.11 

[Nest Platform Information]
platform-express version : 10.1.3
schematics version       : 10.0.1
schedule version         : 3.0.1
graphql version          : 12.0.8
testing version          : 10.1.3
apollo version           : 12.0.9
common version           : 10.1.3
config version           : 3.0.0
axios version            : 3.0.0
core version             : 10.1.3
cli version              : 10.1.11
```

### Node.js version

v18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
