### ISSUE TITLE
Add a basic file(s) interceptor/decorator for Fastify

### ISSUE THREAD

**Issue by xegulon** [nestjs/nest#12695]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have an issue while trying to use nestjs with Express and Fastify interchangeably, because nestjs/platform-fastify does not implement a decorator/interceptor for multipart form data files.

### Describe the solution you'd like

The counterpart of FileInterceptor, UploadedFiles for nestjs+fastify

### Teachability, documentation, adoption, migration strategy

Adapting the docs for https://docs.nestjs.com/techniques/file-upload

### What is the motivation / use case for changing the behavior?

It's an addition, not a modification of something already existing

**Comment by jmcdo29** [comment]
[There's an open PR to integrate `fastify-mutler` that's been open for a while](https://github.com/nestjs/nest/pull/6935). There's also [`@nest-lab/fastify-multer`](https://github.com/jmcdo29/nest-lab/tree/main/packages/fastify-multer) to bring a `FileInterceptor`  for fastify, and soon to be a `@nest-lab/multer` that integrates _any_ multer so long as the user provides the multer instance. I need to create that last one though

**Comment by xegulon** [comment]
Ok, thanks for your answer

When is this feature supposed to land?
