### ISSUE TITLE
Angular-style pipes

### ISSUE THREAD

**Issue by its-dibo** [nestjs/nest#12693]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

since Nestjs follows the architecture of Angular, it is better to also follow the same architecture for the pipes.

Nest-style pipes
```
@Get(':id')
async findOne(@Param('id', ParseIntPipe) id: number) {
  return this.catsService.findOne(id);
}
```

Angular-style pipes
```
@Get(':id')
async findOne(@Param('id | int | min:10') id: number) {
  return this.catsService.findOne(id);
}
```

**Comment by micalevisk** [comment]
> since Nestjs follows the architecture of Angular,

I don't think that's true. The fw was **inspired** by Angular

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
