### ISSUE TITLE
Console logger service receives wrong parameters on printMessages()

### ISSUE THREAD

**Issue by tobias-jueschke** [nestjs/nest#12697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I implemented a custom console logger overwriting the printMessages() method. This worked fine in previouse version 8.0.0 of nestjs. After upgrading to version 10.2.8 the printMessage function receives wrong parameters for logging an error. For all other log levels it works as expected.

This can be seen in the code sandbox https://codesandbox.io/p/sandbox/awesome-tereshkova-wy9kcw

Just run "npm run test". The test can be found under src/console-logger.spec.ts

### Minimum reproduction code

https://codesandbox.io/p/sandbox/awesome-tereshkova-wy9kcw

### Expected behavior

Parameters of method printMessages works same for all log levels.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "nest-typescript-starter",
  "private": true,
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/jest/bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.1",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.0.0",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.64",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I've ran your tests with nestjs v8 and one didn't pass:

![image](https://github.com/nestjs/nest/assets/13461315/ce4285c5-ecbd-46ac-b816-a41a0188a5b2)

is this expected? I was expecting a test suite that worked in v8 but not in v9 and v10

**Comment by tobias-jueschke** [comment]
I had a mistake in the expected message. I fixed it and now it is the case the it runs for version 8 and fails for version 10.

**Comment by jmcdo29** [comment]
[Version 8](https://github.com/nestjs/nest/blob/v8.4.7/packages/common/services/console-logger.service.ts#L270) and [version 10](https://github.com/nestjs/nest/blob/master/packages/common/services/console-logger.service.ts#L310) have different code to try and handle the optional passing of the stack and context variables, so what you're seeing is likely a breaking change between them. 

I think specifically it comes from [this line](https://github.com/nestjs/nest/blob/master/packages/common/services/console-logger.service.ts#L331) with the `!isUndefined` check

**Comment by micalevisk** [comment]
I guess we missed that on our v9 migration guide, right

**Comment by tobias-jueschke** [comment]
When I debugged the code it ran into line https://github.com/nestjs/nest/blob/master/packages/common/services/console-logger.service.ts#L319. Not clear to me is why should the log level "error" behaves different to other log levels for the printMessages function?

**Comment by jmcdo29** [comment]
Because the error can take the `stack` of the error as the second argument. The logic around determining stack or context is a bit complex and can cause some differences like this

**Comment by tobias-jueschke** [comment]
But in this line https://github.com/nestjs/nest/blob/master/packages/common/services/console-logger.service.ts#L319 it is already clear that there is no stack given. Changing that return value to something like:

`if (args.length === 2) {
      return this.isStackFormat(args[1])
        ? {
            messages: [args[0]],
            stack: args[1] as string,
            context: this.context,
          }
        : {
+         messages: args,
+         context: this.context,
          };
    }`

But maybe causes other problems?

**Comment by kamilmysliwiec** [comment]
If there are 2 elements and the second one is not of stack format then we assume it's context (= we can't simply fallback to `this.context`)

**Comment by tobias-jueschke** [comment]
Okay, I understand the problem, but it feels not correct to me to have same concept methods signatures with different results in the printMessages() function. 

If I call one of the following methods with this signature I expect that the printMessages() function is called with the same given parameters.

```
error(message: any, ...optionalParams: [...any, string?, string?]): void;
warn(message: any, ...optionalParams: [...any, string?]): void;
debug(message: any, ...optionalParams: [...any, string?]): void;
```
if I call the following function signature

```
error(message: any, stack?: string, context?: string): void;
```
 it could be different. But that would be fine.

In my case this means I have not all information in the printMessages() function to create a consistent log message for error, info, warn, ... it is always different for "error" and there I have to create a work around to use the additionlProps which are not in the "messages" instead in the "context". I am not sure if this is expected, because it worked in previouse versions. 

But if this is intended then my question would be, how can I create a consitent console log message for error, info, ... with additionl paramters?

**Comment by kamilmysliwiec** [comment]
Just to better understand what you need and what doesn't work correctly for you now, could you create a PR showcasing what changes to the logger would make things easier for you? Contributions are generally more than welcome so if there's any way we could improve the API without introducing breaking changes then we'd love to approve it

**Comment by tobias-jueschke** [comment]
Thanks for the invitation. I would try my best ;)

**Comment by tobias-jueschke** [comment]
So I digged now a bit deeper into it and found out, that when I add "optionalParams" to the log function it will result into two log messages e.g.:

```
logger.error('some message', {
      some: 'optional params',
      another: 'optionl params',
    });
```

```
[Nest] 78927  - 01.01.1970, 01:00:01   ERROR some message
[Nest] 78927  - 01.01.1970, 01:00:01   ERROR Object:
{
  "some": "optional params",
  "another": "optionl params"
}
```

If this is the desired behavior, this issue can be closed. And I need to rethink my implementation of the "printMessages()".

**Comment by tobias-jueschke** [comment]
So I digged now a bit deeper into it and found out, that when I add "optionalParams" to the log function it will result into two log messages e.g.:

```
logger.error('some message', {
   some: 'optional params',
   another: 'optionl params',
});
```

```
[Nest] 78927  - 01.01.1970, 01:00:01   ERROR some message
[Nest] 78927  - 01.01.1970, 01:00:01   ERROR Object:
{
  "some": "optional params",
  "another": "optionl params"
}
```

If this is the desired behavior, this issue can be closed. And I need to rethink my implementation of the "printMessages()".
