### ISSUE TITLE
npm run start:prod command gives me node:internal/modules/cjs/loader:1051 throw err Error: Cannot find module '.../dist/main' error

### ISSUE THREAD

**Issue by fikrikaradereli** [nestjs/nest#12694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've run `npm run build` command, and then run `npm run start:prod`, here comes the error :

`% npm run start:prod

> project-name@0.0.1 start:prod
> node dist/main

node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/Users/fikri/projects/project-name/dist/main'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.5.1`

### Minimum reproduction code

github.com

### Expected behavior

No error complaint, and run in production mode

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

[System Information]
OS Version     : macOS Unknown
NodeJS Version : v20.5.1
NPM Version    : 10.0.0 

[Nest CLI]
Nest CLI Version : 10.2.1 

[Nest Platform Information]
platform-express version : 10.2.8
serve-static version     : 4.0.0
schematics version       : 10.0.3
passport version         : 10.0.2
swagger version          : 7.1.14
testing version          : 10.2.8
common version           : 10.2.8
config version           : 3.1.1
core version             : 10.2.8
jwt version              : 10.1.1
cli version              : 10.2.1

### Node.js version

v20.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead

**Comment by micalevisk** [comment]
this is probably because the compiled `main.ts` file isn't located at `dist/src/main.js`

and so it's related with typescript, not nestjs itself. You can change the `start:prod` npm-script to fulfill your project needs.

**Comment by fikrikaradereli** [comment]
No, the compiled `main.ts` file is located at `dist/src/main.js`

<img width="856" alt="image" src="https://github.com/nestjs/nest/assets/21260508/78f44e2f-2b99-4e00-9bc1-bbd536e19ca7">

**Comment by jmcdo29** [comment]
That's how Typescript does things when there's a TS file outside of the src. This is not a bug

**Comment by fikrikaradereli** [comment]
I set up the project using Nest CLI and didn't change any config. When I want to run in production mode, it gives me an error. And you say it is all about typescript config. Right? Do you have any solution for me?

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
