### ISSUE TITLE
Catch microservice connection error from API gateway

### ISSUE THREAD

**Issue by ericzon** [nestjs/nest#127]
Hello everyone,

I'm testing NestJs (very nice job!), specially microservice section and I've found that every time the client sends a message to failing / disconnected microservice, this throws an error that it seems not catcheable on the client (at least, I've tried surrounding with try / catch the method this.client.send(...) from the docs (https://docs.nestjs.com/real-time/microservices/basics.html)

The output:
`
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9001
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
`

How can we handle this?

I'm currently using:

common: "version": "3.0.0"
core: "version": "3.0.1"
microservices: "version": "3.0.1"
testing: "version": "3.0.0"
websockets: "version": "3.0.0"

Thank you

**Comment by kamilmysliwiec** [comment]
Hi @ericzon,
Let me know if u still have issues after upgrading the framework into v4.
Thanks

**Comment by kuncevic** [comment]
what is the new url for https://docs.nestjs.com/real-time/microservices/basics.html ?

**Comment by kamilmysliwiec** [comment]
HI @kuncevic,
https://docs.nestjs.com/microservices/basics
