### ISSUE TITLE
wrong build output, the build output formats are not unified

### ISSUE THREAD

**Issue by its-dibo** [nestjs/nest#12701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use nest with swagger to build an esm server app.
I investigated the `dist` output and I see all files are copiled as esm (which is the desired behavior), except the dto files are commonjs

### Minimum reproduction code

.

### Steps to reproduce

1- create a nestjs app with @nestjs/cli
2- add `type: module` to packagejs, and adjust your tsconfig.json to outbut ESNEXT modules
3- add @nestjs/swagger as a plugin into nest-cli.json
4- generate a resource `nest g resource users`
5- build
6- check dist/main.js, you'll find it an esm module, wherease dist/users/dto/create-users.dto.js is a commonjs

### Expected behavior

all files are esm

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

10.0.0

### Packages versions

```json
 "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/platform-fastify": "^10.2.8",
    "@nestjs/swagger": "^7.1.14",
    "@nestjs/typeorm": "^10.0.0",
    "pg": "^8.11.3",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.17"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/supertest": "^2.0.12",
    "nodemon": "^3.0.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  }

```

### Node.js version

20.9.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
