### ISSUE TITLE
DIC can not find dependancy when imported from '.'

### ISSUE THREAD

**Issue by CSenshi** [nestjs/nest#12706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to import from current working directory nest is not able to inject provider.

```typescript
import { Controller, Get } from '@nestjs/common';
import { Service } from '.'; // <- does not work
// import { Service } from './service'; // <- works

@Controller()
export class HttpController {
  constructor(private readonly a: Service) {}

  @Get()
  getHello(): string {
    return 'Hello World';
  }
}

```

`Error: Nest can't resolve dependencies of the HttpController (?). Please make sure that the argument dependency at index [0] is available in the AppModule context.`

### Minimum reproduction code

https://github.com/CSenshi/nest-dic-bug-demo

### Steps to reproduce

1. npm i
2. nest start

### Expected behavior

It should just resolve dependancy. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^10.0.0

### Packages versions

```json
[System Information]
OS Version     : macOS Unknown
NodeJS Version : v20.9.0
NPM Version    : 10.1.0 

[Nest CLI]
Nest CLI Version : 10.2.1 

[Nest Platform Information]
platform-express version : 10.2.8
schematics version       : 10.0.3
testing version          : 10.2.8
common version           : 10.2.8
core version             : 10.2.8
cli version              : 10.2.1
```

### Node.js version

20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
that's due to circular imports with barrel files

Just don't import from `'.'`. There's no good reason to

More on this here: [Circular Dependencies in NestJS and how to Avoid Them.](https://trilon.io/blog/avoiding-circular-dependencies-in-nestjs)

**Comment by CSenshi** [comment]
1. The workaround is to use Injection Token (e.g. `@Inject('SOME_TOKEN')`. So why is nest unable to solve it? Maybe use custom injection token when DIC finds circular import?
2. forwardRef is the solution, but it is mainly for two services including each other. Here we have circular imports but only first is using second. So maybe it is possible to use forwardRef internally when circular import is found. (circular file import and not inject)

**Comment by micalevisk** [comment]
>  So why is nest unable to solve it?

because nestjs doesn't have enough metadata to do so like you did.

You can understand it better if you understand nodejs and typescript. That's not really related to nestjs itself.

Also, I'd suggest you to read this: https://github.com/nestjs/docs.nestjs.com/pull/2481/files to understand how `@Injectable()` works. Might be helpful

**Comment by CSenshi** [comment]
Okay I found out about something. You can actually do this. You just need to include file that uses circular DI last.

Before:
```
export * from './controller';
export * from './service';
```

After:
```typescript
export * from './service';
export * from './controller';
```

As far as controller uses service and not vice versa this works
