### ISSUE TITLE
Avoid serializing buffers when creating module's opaque token

### ISSUE THREAD

**Issue by nonamich** [nestjs/nest#12719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Nest takes a very long time to start, the problem is in [ModuleTokenFactory.getStringifiedOpaqueToken](https://github.com/nestjs/nest/blob/02595296e438dab8f6461672970dfdaec552e466/packages/core/injector/module-token-factory.ts#L45), @nestjs/microservices(gRPC) and large .proto files.

The metadata of the [ClientsModule](https://github.com/nestjs/nest/blob/02595296e438dab8f6461672970dfdaec552e466/packages/microservices/module/clients.module.ts#L17) module stores the .proto file data for gRPC in the form of [Buffer](https://nodejs.org/api/buffer.html#buffer)([fileDescriptorProtos](https://github.com/grpc/grpc-node/blob/779e970099b155f92b54a594c1b40fcef4378031/packages/grpc-js/src/make-client.ts#L64)), which is why the [getStringifiedOpaqueToken](https://github.com/nestjs/nest/blob/02595296e438dab8f6461672970dfdaec552e466/packages/core/injector/module-token-factory.ts#L45) method takes so long to process because the Buffer serialization is completely in json. 

Here is an example: https://i.imgur.com/JMBdzu2.png
Here's another example of how much it slows down the launch: https://i.imgur.com/zt91JuK.png

Can this be avoided somehow, maybe we need to add a check for Buffer to the [ModuleTokenFactory.replacer](https://github.com/nestjs/nest/blob/02595296e438dab8f6461672970dfdaec552e466/packages/core/injector/module-token-factory.ts#L70) method?

### Minimum reproduction code

https://stackblitz.com/~/github.com/nonamich/test-buffer

### Expected behavior

The Buffer should not be serialized to JSON to create a module token because the Buffer can be very large. It is worth adding a custom [replacer](https://github.com/nestjs/nest/blob/02595296e438dab8f6461672970dfdaec552e466/packages/core/injector/module-token-factory.ts#L70C14-L70C14).
As a workaround I use this code: 
```js
// Hard fix
import * as util from 'node:util';

Buffer.prototype.toJSON = function () {
  return util.inspect(this); // '<Buffer 00 00 00 00 00 00 ... 5 more bytes>' as string
};
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [x] Other (see below)

### Other package

@grpc/grpc-js

### NestJS version

10.2.8

### Packages versions

```json
{
  "dependencies": {
    "@grpc/grpc-js": "^1.9.9",
    "@grpc/proto-loader": "^0.7.10",
    "@nestjs/common": "^10.2.8",
    "@nestjs/core": "^10.2.8",
    "@nestjs/microservices": "^10.2.8",
    "@nestjs/platform-express": "^10.2.8",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.2.1",
    "@nestjs/schematics": "^10.0.3",
    "@nestjs/testing": "^10.2.8",
    "@types/express": "^4.17.21",
    "@types/jest": "^29.5.8",
    "@types/node": "^20.9.0",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
}
```

### Node.js version

20.9.0

### In which operating systems have you tested?

- [ ] Windows
- [x] Linux
- [ ] macOS

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by H4ad** [comment]
If this feature lands, I think we should create a documentation page to describe what can cause two modules to be serialized in the same hash.

**Comment by nonamich** [comment]
@kamilmysliwiec  
> Would you like to create a PR for this issue?

I wanted to, but it's more complicated than I thought. Data of type Buffer does not get into the [ModuleTokenFactory.replacer](https://github.com/nestjs/nest/blob/02595296e438dab8f6461672970dfdaec552e466/packages/core/injector/module-token-factory.ts#L45) method because it has a [Buffer.toJSON](https://nodejs.org/api/buffer.html#buftojson) method. That is, the Buffer is immediately serialized to JSON without being passed to the [replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify?retiredLocale=uk#replacer)

**Comment by nonamich** [comment]
@H4ad 
> If this feature lands, I think we should create a documentation page to describe what can cause two modules to be serialized in the same hash.

I think not if encrypt the Buffer in [sha256](https://github.com/nestjs/nest/blob/02595296e438dab8f6461672970dfdaec552e466/packages/core/injector/module-token-factory.ts#L67C4-L67C4) beforehand

**Comment by H4ad** [comment]
@nonamich This PR #12753 will fix your issue without changing the `ModuleTokenFactory`.

Instead of changing the `ModuleTokenFactory` replacer logic, I think is better to introduce some kind of feature to allow the developer to have more control over how this `ModuleTokenFactory` works and possibly skip the whole serialization.

I already talked about this in the past: https://github.com/nestjs/nest/issues/10844#issuecomment-1399282773

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12753

> Instead of changing the ModuleTokenFactory replacer logic, I think is better to introduce some kind of feature to allow the developer to have more control over how this ModuleTokenFactory works and possibly skip the whole serialization.

https://github.com/nestjs/nest/pull/12753#issuecomment-1816278717
