### ISSUE TITLE
Any plans to bring back support for Redis as cache-manager?

### ISSUE THREAD

**Issue by itinance** [nestjs/nest#12720]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

With the latest/current versions of NestJS, it seems impossible anymore to use `cache-manager-redis-store` as cache-manager, nor is any other out-of-the-box-solution existing according to my current knowledge.

Errors vary between:

> error TS2345: Argument of type '{ store: CacheManagerRedisStore.RedisStoreConstructor; host: string; port: number; }' is not assignable to parameter of type 'CacheModuleOptions<RedisClientOptions<RedisModules, RedisFunctions, RedisScripts>>'.

and

> Type '(config: RedisClientOptions<RedisModules, RedisFunctions, RedisScripts> & Config) => Promise<RedisStore>' cannot be assigned to type '(string | CacheStoreFactory | CacheStore)

More details can be found on StackOverflow, e.x. [here](https://stackoverflow.com/questions/74621340/i-get-a-types-error-when-registering-redis-with-nestjs-using-cachemodule-registe). 

https://stackoverflow.com/questions/74621340/i-get-a-types-error-when-registering-redis-with-nestjs-using-cachemodule-registe

Also, the repository `cache-manager-redis-store` seems to be unmaintained with the latest commit happening at October 2022. Issue-responses won't get recognized, and PRs won't get merged since then.

Can someone provide some hints on this topic? Will NestJS provide its own implementation for **redis**-support or is someone else already working on that?

### Describe the solution you'd like

Redis can be used as a cache-manager:

Something like this code (taken  from the official [Docs](https://docs.nestjs.com/techniques/caching))

    CacheModule.register<RedisClientOptions>({
      store: redisStore,

      // Store-specific configuration:
      host: 'localhost',
      port: 6379,
    }),

### Teachability, documentation, adoption, migration strategy

See https://docs.nestjs.com/techniques/caching

### What is the motivation / use case for changing the behavior?

To bring back an important feature.

**Comment by jmcdo29** [comment]
It's not nest that removed the support. It's that package not updating for mode-cache-manager. You can use `cache-manager-redis-yet` for Redis support in cache-manager. Just as their docs show

**Comment by itinance** [comment]
Wow, thanks. Can someone please help me to configure this properly? The docs from https://docs.nestjs.com/techniques/caching are not helping here.
