### ISSUE TITLE
Transformer ("class-transformer") metadata cannot be inherited for "CreateUserDto" class.

### ISSUE THREAD

**Issue by sugar258596** [nestjs/nest#12731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/nestjs/nest/assets/84883966/b08c77e9-8eba-4d6e-ae92-b16985a35a50)

### Minimum reproduction code

https://github.com/sugar258596/NestJs.git

### Expected behavior

在DTO中使用PartialType方法进行创建一个新的类出现这个问题

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/swagger": "^7.1.14",
    "@nestjs/typeorm": "^10.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "express": "^4.18.2",
    "express-session": "^1.17.3",
    "mysql2": "^3.6.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "svg-captcha": "^1.4.0",
    "typeorm": "^0.3.17"
  },
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
