### ISSUE TITLE
NestJs dependency issue

### ISSUE THREAD

**Issue by majva-g** [nestjs/nest#12749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

 Nest can't resolve dependencies of the AuthService (?, JwtService, ConfigService, +, EventEmitter, +, MailerService, MessageService). Please make sure that the argument dependency at index [0] is available in the AuthModule context.

### Minimum reproduction code

github.com

### Expected behavior

The app should run and the AuthService dependencies can be injected.

app.module.ts
```
@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: [`.env.stage.${process.env.STAGE}`],
      validationSchema: envValidationSchema,
    }),
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => ({
        type: 'postgres',
        autoLoadEntities: true,
        entities: [__dirname + '/**/*.entity{.ts,.js}'],
        synchronize: true,
        host: configService.get('DB_HOST'),
        port: configService.get('DB_PORT'),
        username: configService.get('DB_USERNAME'),
        password: configService.get('DB_PASSWORD'),
        database: configService.get('DB_DATABASE'),
      }),
    }),
    AuthModule,
    MessageModule,
    EventEmitterModule.forRoot(),
  ],
  providers: [
    {
      provide: APP_GUARD,
      useClass: ATGuard,
    },
    {
      provide: APP_GUARD,
      useClass: ActiveUserGuard,
    },
  ],
})
export class AppModule {}
```

auth.module.ts
```
@Module({
  imports: [
    ConfigModule,
    TypeOrmModule.forFeature([User, Device, VerificationCode]),
    JwtModule.register({}),
    forwardRef(() => MessageModule),
  ],
  controllers: [AuthController, UsersController, DevicesController],
  providers: [
    AuthService,
    UserRepository,
    UsersService,
    ATStrategy,
    RTStrategy,
    DevicesService,
    VerificationCodesService,
  ],
  exports: [UsersService, AuthService, UserRepository],
})
export class AuthModule {}
```

users.service.ts:
`@Injectable()
export class UsersService {
  constructor(
    private repo: UserRepository,
    private readonly config: ConfigService,
  ) {}
}
```

auth.service.ts:
```
export class AuthService {
  constructor(
    private usersService: UsersService,
    private jwtService: JwtService,
    private config: ConfigService,
    private deviceService: DevicesService,
    private eventEmitter: EventEmitter2,
    private verificationCodesService: VerificationCodesService,
    private mailerService: MailerService,
    @Inject(forwardRef(() => MessageService))
    private messageService: MessageService,
  ) {}
}
```


### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

_No response_

### NestJS version

10.1.9

### Packages versions

```json
    "@nestjs-modules/mailer": "^1.7.1",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/event-emitter": "^2.0.3",
    "@nestjs/jwt": "^10.1.0",
    "@nestjs/passport": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/swagger": "^7.1.13",
    "@nestjs/typeorm": "^10.0.0",
```

### Node.js version

20.8.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

As you can see nest can't inject UsersService to AuthService, Also the DevicesService and VerificationCodeService are shown as + in the error message. Both of them are inside the Auth module.

Any idea?

**Comment by micalevisk** [comment]
Seems to be a circular dependency thing

Hard to tell more without seen the whole code.

You can use `forwardRef` to confirm that.

**Comment by majva-g** [comment]
@micalevisk 
Nope, UsersService is inside the auth module, as same as AuthService.
The circular dependency is about the Message module that I used circular dependency

**Comment by micalevisk** [comment]
Yeah but have you tried `forwardRef` for the others as well or not? I didn't follow

As you didn't share the full code, we can't help more

**Comment by majva-g** [comment]
Yes. 
message.module.ts
`
@Module({
  imports: [MessageConfigModule.register(), forwardRef(() => AuthModule)],
  providers: [
    MessageService,
    InternalMessageService,
    MessageRepository,
    UserRepository,
    UsersService,
    ConfigService,
  ],
  exports: [MessageService],
  controllers: [MessageController],
})
export class MessageModule {}
`
I also commented all the codes related to the message service and the problem still remains.

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
