### ISSUE TITLE
Add support for ClientKafka Batch Emit 

### ISSUE THREAD

**Issue by elsakoh** [nestjs/nest#12748]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

i'd like to be able to send multiple messages using emit function when using kafka, im not sure if its because other clients disallows such behaviour thats why the interface only has one function

### Describe the solution you'd like

reference code at [client-kafka](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-kafka.ts)
off the top of my head something like 
```ts
protected async dispatchEventBatch(packets: OutgoingEvent[]): Promise < any > {
    if(!packets.length) return;
    const pattern = this.normalizePattern(packets[0].pattern);
    const outgoingEvents = await Promise.all(
        packets.map((packet) =>  { 
            return this.serializer.serialize(packet.data, { pattern }
         });
    );

    const message = Object.assign(
      {
        topic: pattern,
        messages: outgoingEvents,
      },
      this.options.send || {},
    );

    return this.producer.send(message);
}
  ```
  
 OR expose the producer for `ClientKafka` class

#### teachability / documentation 
should be something simple like 
ClientProxy.emit(Message | Message[])

#### migration 
no migration needed 

### What is the motivation / use case for changing the behavior?

just thought the underlying kafkajs allows for this behaviour, not exposing it makes me have to send message by message in nestjs application code

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by gunb0s** [comment]
is there any progress?

**Comment by kamilmysliwiec** [comment]
@gunb0s would you like to create a PR for this issue?

**Comment by gunb0s** [comment]
> @gunb0s would you like to create a PR for this issue?

yes, it would be appreciate if you review this
https://github.com/nestjs/nest/pull/12954

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12954
