### ISSUE TITLE
Consumer Tag is missing while configuring Rmq microservice  

### ISSUE THREAD

**Issue by rawalrajen** [nestjs/nest#12759]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently I can not able to specify consumerTag while consuming message from rmq queue. However it is quite possible to specify using amqplib as below 

`await channel.consume(queue, (message) => {
      if (message) console.log(" [x] '%s'", message.content.toString());
      else console.warn(' [x] Consumer cancelled');
    }, { noAck: true, consumerTag: 'my-microservice' });`

### Describe the solution you'd like

Rmq options should accept extra parameter for consumerTag and should pass the param to amqplib 

`interface RmqOptions {
    transport?: Transport.RMQ;
    options?: {
        urls?: string[] | RmqUrl[];
        queue?: string;
        prefetchCount?: number;
        isGlobalPrefetchCount?: boolean;
        queueOptions?: any;
        socketOptions?: any;
        noAck?: boolean;
        consumerTag?: string;
       ...rest
    };
}`

### Teachability, documentation, adoption, migration strategy

ConsumerTag param should be optional just like as noAck parameter. If users provide the consumerTag then it should pass to amqplib otherwise it should be as it is. 

### What is the motivation / use case for changing the behavior?

I think its quite important to have readable consumerTag name for debugging and analytics purpose. If we don't provide consumerTag explicitly amqplib generates some random tag which is quite difficult to remember. Rmq admin dashboard itself provides the consumerTag on their ui as well which speaks volume of its importance.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12760
