### ISSUE TITLE
Socket.io engine.io packet 

### ISSUE THREAD

**Issue by chongma** [nestjs/nest#12762]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In socket.io if I want to trigger a callback when there are packets sent between the server and client I can use this code:
```typescript
io.on("connection", (socket) => {
  socket.conn.on("packet", ({ type, data }) => {
    // called for each packet received
  });
  socket.conn.on("packetCreate", ({ type, data }) => {
    // called for each packet sent
  });
});
```

### Describe the solution you'd like

What is the equivalent code in `WebSocketGateway`?  Is it to place this code in the `handleConnection` function?

### Teachability, documentation, adoption, migration strategy

It might be nice to add this use case in the docs and possibly examples

### What is the motivation / use case for changing the behavior?

It might not be a change of behaviour if it works the way expected.  It just needs clarity

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
