### ISSUE TITLE
Applying type option to ClassSerializerInterceptor can cause other options to be ignored

### ISSUE THREAD

**Issue by kmw14641** [nestjs/nest#12763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using ClassSerializerInterceptor and adding @SerializeOptions with 'type' option which applies decorators in that type such as @Transform, some other options such as exposeDefaultValues are ignored. Applying only plainToClass or classToPlain with same option works well, and using ClassSerializerInterceptor without 'type' option also creates expected behavior.

### Minimum reproduction code

https://github.com/kmw14641/nestjs-class-serializer-interceptor-example

### Steps to reproduce

1. `npm ci`
2. `npm start`
3. Send get request to http://localhost:3000/
4. Check response

### Expected behavior

With exposeDefaultValues option, because there is a default value at nickName property in GetUserDto, returning an object without nickName property should create nickName field with default value, but response has no nickName field.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.6

### Packages versions

platform-express version : 10.2.6
schematics version       : 10.0.2
testing version          : 10.2.6
common version           : 10.2.6
core version             : 10.2.6
cli version              : 10.1.18

### Node.js version

20.9.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
![image](https://github.com/nestjs/nest/assets/13461315/46238b07-3909-4fae-961d-0f59416287f5)

**Comment by kmw14641** [comment]
Sorry, I set that private. Now accessible.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12764
