### ISSUE TITLE
Cors not working when enabled as per documentation

### ISSUE THREAD

**Issue by kiriti999** [nestjs/nest#12770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

  This line `const app = await NestFactory.create(AppModule, { cors: options });` should allow origins passed but I keep getting error:
  
  The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. 

### Minimum reproduction code

https://blog.whatsnxt.in/

### Steps to reproduce

Using the code below giving me error:

```
 const whiteList = [
      'https://blog.whatsnxt.in',
      'https://www.whatsnxt.in',
      'https://api.whatsnxt.in',
      'https://blogapi.whatsnxt.in',
    ];
    
    const options = {
      origin: process.env.NODE_ENV == 'prod' ? whiteList : true,
      methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
      credentials: true,
      preflightContinue: false,
      optionsSuccessStatus: 200,
      allowedHeaders: 'Content-Type,Accept,Authorization,email,x-request-id,request-type,X-Service-Identifier',
      exposedHeaders: 'X-Service-Identifier'
    };
    
    const app = await NestFactory.create(AppModule, { cors: options });
    app.use((req, res, next) => {
      res.header('credentials', 'true');
      res.header('Access-Control-Allow-Origin', '*');
      res.header('Access-Control-Allow-Methods', 'GET,HEAD,PUT,PATCH,POST,DELETE');
      res.header('Access-Control-Allow-Headers', 'Content-Type,Accept,Authorization,email,x-request-id,request-type,X-Service-Identifier');
      next();
    });

Error:

     Access to XMLHttpRequest at 'https://blogapi.whatsnxt.in/api/blog/popular' from origin 'https://blog.whatsnxt.in' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: 

    The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. 

    The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute


```

I tried all the options but still I get cors issue

### Expected behavior

Should allow origins whitelisted

```
const whiteList = [
  'https://blog.whatsnxt.in',
  'https://www.whatsnxt.in',
  'https://api.whatsnxt.in',
  'https://blogapi.whatsnxt.in',
];
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

NA

### NestJS version

10.2.9

### Packages versions

```
 "dependencies": {
    "@elastic/elasticsearch": "7.4.0",
    "@google-analytics/data": "^4.0.1",
    "@nestjs/cache-manager": "^2.1.1",
    "@nestjs/common": "^10.2.9",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.9",
    "@nestjs/elasticsearch": "^10.0.1",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "^10.2.9",
    "@nestjs/throttler": "^5.0.1",
    "@types/cache-manager": "^4.0.2",
    "bcryptjs": "^2.4.3",
    "cache-manager": "^3.6.0",
    "cache-manager-redis-store": "^2.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cloudinary": "^1.36.4",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    "csurf": "^1.11.0",
    "dotenv": "^16.3.1",
    "express-rate-limit": "^6.11.0",
    "helmet": "^7.0.0",
    "joi": "^17.8.4",
    "migrate-mongo": "^11.0.0",
    "mongodb": "^5.1.0",
    "nodemailer": "^6.9.7",
    "npm-check-updates": "^16.14.6",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "pm2": "^5.3.0",
    "reflect-metadata": "^0.1.13",
    "uuid": "^9.0.1"
  },
```

### Node.js version

v18.18.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

![image](https://github.com/nestjs/nest/assets/13074074/7724bb3b-f987-4429-ac08-95207b9b05f2)

Posted question here as well: 
[https://stackoverflow.com/questions/77505630/nestjs-cors-options-is-not-enabled](https://stackoverflow.com/questions/77505630/nestjs-cors-options-is-not-enabled)

**Comment by jmcdo29** [comment]
This is noisy likely a misconfiguration, not a bug. Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by kiriti999** [comment]
This is related to this issue: https://github.com/nestjs/nest/issues/1071

I am having the same issue

**Comment by jmcdo29** [comment]
That would be related to the underlying cors library. Nest doesn't provide an explicit cors library, we just pass the configuration down to the underlying engine's library

**Comment by micalevisk** [comment]
@kiriti999 unless you have a properly reproduction to share so we could see if this is related with Nest, I'd suggest you to report this to https://github.com/expressjs/cors

as you can see below, `cors: options` is a just a proxy to `app.use(cors(options))`. Nothing fancy

https://github.com/nestjs/nest/blob/d4bda940fc10238eb18f14ebf66d66b7ef8bff41/packages/platform-express/adapters/express-adapter.ts#L212-L214
