### ISSUE TITLE
Swagger documentation excludes any properties that uses the Matches class validator

### ISSUE THREAD

**Issue by abdelrahmansafwat** [nestjs/nest#12786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If there is a type that has a property validated with Match class-validator, that property is ignored by Swagger altogether.

### Minimum reproduction code

https://github.com/abdelrahmansafwat/matches-bug-repro

### Steps to reproduce

1. yarn install
2. yarn start
3. Navigate to http://localhost:3000/docs
4. Check CreateDemoDto in Schemas

### Expected behavior

The schema should be:
```
{
  name: string;
  age?: number;
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

10.0.0

### Packages versions

```
"@nestjs/common": "^10.0.0",
"@nestjs/core": "^10.0.0",
"@nestjs/platform-express": "^10.0.0",
"@nestjs/swagger": "^7.1.16",
"class-transformer": "^0.5.1",
"class-validator": "^0.14.0",
"reflect-metadata": "^0.1.13",
"rxjs": "^7.8.1"
```

### Node.js version

18.18.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

![image](https://github.com/nestjs/nest/assets/33398534/22dc9e81-a7cd-4994-9f19-f3818d9100d9)
![image](https://github.com/nestjs/nest/assets/33398534/20f03035-5a6b-4271-9da6-4732f2338101)

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by abdelrahmansafwat** [comment]
> Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

https://github.com/abdelrahmansafwat/matches-bug-repro

**Comment by micalevisk** [comment]
thanks. I manage to reproduce it here

Somehow if you use a variable for the regex, it works:

![image](https://github.com/nestjs/nest/assets/13461315/058f0424-551f-46db-bd76-da12043f4022)

![image](https://github.com/nestjs/nest/assets/13461315/97d1370e-7410-4d6c-800d-7db4f7b15498)

seems to be a limitation of the `@nestjs/swagger` plugin

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/issues/2723
