### ISSUE TITLE
How to use Hot Reload?

### ISSUE THREAD

**Issue by Modeest** [nestjs/nest#1278]
When I use `npm run start` by default, the Application was running, But When I use `npm run webpack` and `npm run start`, then the Application gave me  a error, like this
![图](http://i2.bvimg.com/654110/22477658a8c7b2c9s.png)

webpack.config.js is Official default configuration

**Comment by marcus-sa** [comment]
Please use StackOverflow for questions like this.
As you can CLEARLY read its a permissions problem.
