### ISSUE TITLE
How to disable program startup logs and enable custom logs

### ISSUE THREAD

**Issue by xxwangkaimin** [nestjs/nest#12785]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When developing and deploying projects, the program will print some built-in startup logs during startup:
![image](https://github.com/nestjs/nest/assets/33536543/7852b484-f739-450d-86da-49dce1945b6c)
![image](https://github.com/nestjs/nest/assets/33536543/94ea323b-353c-4fa9-80a0-9676c49c6a48)
I don't want to display this type of log, only display my own customized output logs:
![image](https://github.com/nestjs/nest/assets/33536543/3e2de04a-364a-4c4f-ae75-91f04de35dcd)
```ts
import { NestFactory } from '@nestjs/core'
import { AppModule } from './app.module'
import { ConfigService } from '@nestjs/config'
import { GetConfigType } from './config'
import { Logger, RequestMethod, ValidationPipe } from '@nestjs/common'
import { setupSwagger } from './setup-swagger'
import { EnvEnum, EnvType } from './common/enums/env.enum'

function createSwaggerServerUrl(domain: string, env: EnvType, port: number) {
  let serverUrl = domain
  if (env === EnvEnum.development) {
    serverUrl += ':' + port + '/api'
  } else {
    serverUrl += '/api'
  }
  return serverUrl
}

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    // logger: false
  })
  const configService = app.get(ConfigService<GetConfigType>)
  const port = configService.get<number>('port')
  const domain = configService.get<string>('domain')
  const env = configService.get<EnvType>('environment_variable')
  /* 设置 HTTP 标头来帮助保护应用免受一些众所周知的 Web 漏洞的影响 */
  app.setGlobalPrefix('api', {
    exclude: [
      { path: '/', method: RequestMethod.GET }
    ]
  })
  app.useGlobalPipes(new ValidationPipe())
  const swaggerServerUrl = createSwaggerServerUrl(domain, env, port)
  setupSwagger(app)
  await app.listen(port, () => {
    Logger.log(
      `NestJS项目已经启动，接口文档请访问：${swaggerServerUrl}/swagger-ui`
    )
  })
}
bootstrap()
```

### Describe the solution you'd like

Display only user-defined logs, do not display program startup logs

### Teachability, documentation, adoption, migration strategy

![image](https://github.com/nestjs/nest/assets/33536543/7588975b-9795-410c-ad5a-e87d561a85ea)
Do not output the logs in the red box, output the logs in the yellow box. These logs are my customized logs.
Can I implement it through a custom logging module?

### What is the motivation / use case for changing the behavior?

Refine log output.

**Comment by jmcdo29** [comment]
Use `logger: false` in the `NestFactory` and afterwards use `app.useLogger(new Logger())` afterwards to re-set the `Logger` instance

**Comment by xxwangkaimin** [comment]
@jmcdo29 I set it according to your method, but it still has corresponding log output.
![image](https://github.com/nestjs/nest/assets/33536543/85a13205-c689-4917-8074-36a587b00ef5)

**Comment by jmcdo29** [comment]
For that, you can either extend the logger and exclude that context, or just instantiate they let directly wherever you need it

**Comment by xxwangkaimin** [comment]
@jmcdo29 Do you mean I need to implement a custom logging module?

**Comment by jmcdo29** [comment]
Yes. I believe that we don't plan to add any more major changes to the Logger class. Kamil can correct me on this if I am wrong

**Comment by kamilmysliwiec** [comment]
> Do you mean I need to implement a custom logging module?

In your `Logger` class check if `context === "RoutesExplorer"` (or Resolver) and if so, skip printing out the message

**Comment by micalevisk** [comment]
[how to disable initialization logging](https://dev.to/micalevisk/nestjs-tip-how-to-disable-initialization-logging-1b38)
