### ISSUE TITLE
NestJs parse user if authenticated

### ISSUE THREAD

**Issue by karimsqualli** [nestjs/nest#1280]
i want to know if there is a decorator that make req.user object available in a controller method, if the user is logged in (Authaurization header sent), if not then just let the req.user be null.

The AuthGuard decorator will return 401 if the user is not logged, so it's not suitable for my case.

**Comment by marcus-sa** [comment]
Use `createParamDecorator`

```ts
import { createParamDecorator } from '@nestjs/common';

export const User = createParamDecorator((, req) => req.user);
```

**Comment by karimsqualli** [comment]
@marcus-sa i think that not the problem, the problem i have with the `user` is that if the route don't have a `AuthGuard` decorator, the user is not parsed from the `jwt` token, so `req.user` is always null.

i have a special requirement for an api endpoint, if the user is logged, then there is a special code for this case. but if not, then the method should be working without returning `401` error ( Authorization required). 

And i can't do that with the `AuthGuard` decorator

**Comment by nartc** [comment]
AuthGuard throw UnauthorizedException when there’s no User. You can always create a custom AuthGuard and instead of throwing exception, you can just return null :)
