### ISSUE TITLE
ValidationPipe sets "undefined" for Boolean parameter if not provided

### ISSUE THREAD

**Issue by myfunc** [nestjs/nest#12818]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

PR #10953

### NestJS version

9.4.3 -> 10.2.10

### Describe the regression

I encountered a breaking change while migrating to the new major version of Nest.js.

In version 9.4.3, the ParseBoolPipe from "@nestjs/common" used to set a parameter's value to "false" if it was not provided. Starting from version 10.0.0, the ValidationPipe::transformPrimitive() now sets a Boolean parameter to "undefined."

Unfortunately, this change is not mentioned in the Nest.js migration guide https://docs.nestjs.com/migration-guide and is not highlighted in the release notes.

### Input code

```ts
import {
  Controller,
  Get,
  ParseBoolPipe,
  Query,
} from '@nestjs/common';

@Controller('users')
export class LeaderboardUserController {

  @Get()
  async getAll(
    @Query('hideUsernames', ParseBoolPipe) hideUsernames: boolean,
  ) {
    return "data";
  }
}

```

### Expected behavior

Endpoints returns "data".

**Comment by micalevisk** [comment]
that's expected and it was a breaking change, as I described in that PR. That's why it was introduced in v10, not in v9

**Comment by micalevisk** [comment]
btw that has nothing to do with `ValidationPipe`

it just for `ParseBoolPipe`

**Comment by myfunc** [comment]
I wonder how many unexpected runtime issues like this I will face in v10.

**Comment by myfunc** [comment]
Actually thank you, now I see the full list of such possible changes. Thank you for a quick response.

**Comment by micalevisk** [comment]
@myfunc 

actually, in your case, you should see a validation error (400 bad request), not `undefined`, right?

can you provide a minimum repro?

**Comment by myfunc** [comment]
Yes, I see validation error. 
I think there is no need to make a minimal repo for that listed change. That's completely clear now.

**Comment by myfunc** [comment]
That's risky breaking change, cause it reveals only in runtime.
