### ISSUE TITLE
CorsOptionsCallback type - Error should be nullable when TS strict=true

### ISSUE THREAD

**Issue by leepowellnbs** [nestjs/nest#12816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently if you use the `CorsOptionsDelegate` in the NextFactory creation, it is impossible to correctly type as the callbacks first option is an `Error` and not nullable (typescript option strict=true)

```
export interface CorsOptionsCallback {
    (error: Error, options: CorsOptions): void;
}
```

This means an error MUST be passed and therefore means we can't set the cors options.

<img width="481" alt="Screenshot 2023-11-23 at 12 23 57" src="https://github.com/nestjs/nest/assets/97112180/59a78377-f35f-48d2-8725-02a76ee72ed7">

This is the problem line: https://github.com/nestjs/nest/blob/e48be85c164744b098ae8573cc64d7837e5a30cb/packages/common/interfaces/external/cors-options.interface.ts#L58

### Minimum reproduction code

https://codesandbox.io/p/devbox/elated-germain-l9g3tn?file=%2Fsrc%2Fmain.ts%3A14%2C6

### Steps to reproduce

Use this in the bootstrap function:
```
const app = await NestFactory.create(AppModule, {
    cors: (request: Request, callback: CorsOptionsCallback) => {
      callback(null, {
        origin: request.headers.origin,
        credentials: true,
      });
    },
    bodyParser: true,
  });
  ```

### Expected behavior

Should be able to pass `null` or `Error` to allow usage of delegated cors options.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.10

### Packages versions

```json

```

### Node.js version

20.8.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/12817
