### ISSUE TITLE
Don't deploy firebase function with nest

### ISSUE THREAD

**Issue by jundat95** [nestjs/nest#1281]
## Problem

I run command: `firebase deploy` -> don't deploy code to firebase

## Environment
*nest version*
![screenshot_3](https://user-images.githubusercontent.com/11944757/48336440-dc462b80-e692-11e8-86cd-50e9a48a5e85.png)

*main.ts*
![screenshot_2](https://user-images.githubusercontent.com/11944757/48336480-f253ec00-e692-11e8-8f15-b68141ae1c87.png)

*Error*
![screenshot_4](https://user-images.githubusercontent.com/11944757/48336531-1a434f80-e693-11e8-9bfc-b81e37de51f8.png)

**Comment by Shyam-Chen** [comment]
https://howtofirebase.com/cloud-functions-migrating-to-node-8-9640731a8acc

**Comment by jundat95** [comment]
thank you !!

**Comment by danieldanielecki** [comment]
Hi @jundat95,

Trying to get working Angular Universal with Nest using Firebase Cloud Functions, but can't get it working.
Might you share you solution for this? It looks like you have it working. In my case I got working Nest + Angular Universal on localhost, but can't deploy it to make it working with Cloud Functions.

**Comment by danieldanielecki** [comment]
Got it working, if someone would like to sharing the code:

```
import * as express from 'express';
import * as functions from 'firebase-functions';
import { AppModule } from './app.module';
import { Express } from 'express';
import { ExpressAdapter } from '@nestjs/platform-express';
import { NestFactory } from '@nestjs/core';

const server: Express = express();

// Create and init Nest server based on Express instance.
const createNestServer = async (expressInstance: Express) => {
  const app = await NestFactory.create(
    AppModule,
    new ExpressAdapter(expressInstance)
  );
  app.listen(4048);
};

createNestServer(server);
exports.angularUniversalFunction = functions.https.onRequest(server); // Export Firebase Cloud Functions to work on
```
