### ISSUE TITLE
Tackle #11493 with docs or framework improvements

### ISSUE THREAD

**Issue by veimox** [nestjs/nest#12849]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We have the same issue described in https://github.com/nestjs/nest/issues/11493 and after a chat in Discord with @micalevisk  we concluded that we can open an issue for a feature request to either tackle it at a framework level or at least update the Guards documentation to avoid confusion.

### Describe the solution you'd like

Ideally the framework level solution, but the docs might be the most cost effective for now

### Teachability, documentation, adoption, migration strategy

One disclaimer paragraph might be enough

### What is the motivation / use case for changing the behavior?

Avoid spending one day with a weird behaviour that is solved in an anti intuitive way

**Comment by kamilmysliwiec** [comment]
PRs to the documentation are more than welcome!
