### ISSUE TITLE
Versions are inconsistent

### ISSUE THREAD

**Issue by lsxqer** [nestjs/nest#12858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```js
@fastify/middie Package dependency "path-to-regexp": "^6.1.0",

@nestjs/platform-fastify Package dependency  "path-to-regexp": "^3.0.2",

@fastify/middie 
const { pathToRegexp } = require('path-to-regexp')

@nestjs/platform-fastify
const pathToRegexp = require('path-to-regexp')

```
The problems caused
If the two dependencies are packaged differently, there will be a package that cannot find the 'pathToRegexp' function
All you need to do is update the dependencies of the platform-fast package, e.g. to ^6.1.0

### Minimum reproduction code

none

### Expected behavior

I'm using docker to pack, but after packaging, there will be no function found, undefined function

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Packages versions

```json
{
    "@fastify/multipart": "^8.0.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.0.0",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mapped-types": "^2.0.3",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/platform-fastify": "^10.2.8",
    "@nestjs/serve-static": "^4.0.0",
    "@nestjs/typeorm": "^10.0.0"
}

```

### Node.js version

v20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
