### ISSUE TITLE
Wrong FilesInterceptor type from @nestjs/platform-express when using in @UseInterceptors(FilesInterceptor())

### ISSUE THREAD

**Issue by sailingIt** [nestjs/nest#12850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

FilesInterceptor in @nestjs/platform-express in version 9 was Type<NestInterceptor<any, any>> and  Type<NestInterceptor> in version 10+ causes an type error when using it inside @UseInterceptors(FilesInterceptor(''));

### Minimum reproduction code

https://github.com/nestjs/nest/blob/v10.2.10/packages/platform-express/multer/interceptors/files.interceptor.ts

### Steps to reproduce

type error when using FilesInterceptor inside @UseInterceptors(FilesInterceptor('')) in version 10+

### Expected behavior

FilesInterceptor form @nestjs/platform-express should be correct type to be used inside @UseInterceptors() decorator

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.10

### Packages versions

```json
"@nestjs/common": "^10.2.10",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.10",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "10.2.10",
    "@nestjs/serve-static": "^4.0.0",
    "@nestjs/typeorm": "^10.0.1",
```

### Node.js version

18.18.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
> type error when using FilesInterceptor inside @UseInterceptors(FilesInterceptor('')) in version 10+

I didn't manage to reproduce this here

![image](https://github.com/nestjs/nest/assets/13461315/b64c010f-76be-4805-89ab-d7c22873dd15)
![image](https://github.com/nestjs/nest/assets/13461315/410b2958-90a5-4b6c-ae79-df83cdbfc76b)

---

Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
