### ISSUE TITLE
cannot find module dist/src/main.js

### ISSUE THREAD

**Issue by joshua-williams** [nestjs/nest#12857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In order for Typescript to compile into the same directory as the source files I removed the `outDir` property from my `tsconfig.json`. 
After running `nest build` I end up with `src/main.js` as expected

I then updated the `entryFile` property in `nest-cli.json` 
```
...
"sourceRoot": "src",
 "entryFile": "src/main.js",
...
```
When running `nest start` I get the following error:
`Error: Cannot find module '/Users/joshua/git/acreofnature-api/app/dist/main.js'`

### Minimum reproduction code

https://github.com/joshua-williams/nestbug.git

### Steps to reproduce

1. `git clone https://github.com/joshua-williams/nestbug.git`
2. `cd nestbug`
3. `npm run build`
4. `npm start`

### Expected behavior

It should start the server but instead it throws an error
`Error: Cannot find module '/Users/joshua/git/acreofnature-api/app/dist/main.js'`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.1

### Packages versions

```json

```

### Node.js version

20.8.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Your repo is an empty one. Nothing in the `nestbug` folder

**Comment by joshua-williams** [comment]
Thanks @jmcdo29 I pushed the code.

**Comment by jmcdo29** [comment]
_Technically_ the `entryFile` is relative to `dist` as that's 99.9% of the time where the nest cli builds to and our opinion of where it should be. **If** you really don't want that, set the `entryFile` to `../src/main`

**Comment by joshua-williams** [comment]
That's what I ended up having to do and it works fine for me 👍.  I just wasn't sure if that was the expected behavior.

**Comment by micalevisk** [comment]
that's why I recommend having the [`rootDir`](https://www.typescriptlang.org/tsconfig#rootDir) defined in the tsconfig file.
