### ISSUE TITLE
Optional query param / param with default value isn't taken into consideration when using ValidationPipe with transform: true

### ISSUE THREAD

**Issue by Hareloo** [nestjs/nest#12864]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

I am using a ValidationPipe enabled globally with `transform: true.`.
The problem is that I have query params which are optional, or that should have a default value if not explicitly set, like so:
```
  async getPatients(
    @Query('limit') limit: number = PAGINATION_DEFAULT_LIMIT,
    @Query('offset') offset: number = 0,
```

The issue is that both `limit` and `offset` get converted to NaN when no value is passed, instead of to the default value I set.
If I try to change the code so that these params will be optional like so:
```
  async getPatients(
    @Query('limit') limit?: number,
    @Query('offset') offset?: number,
```
The same issue persists...

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-mgxaub?file=src%2Fapp.controller.ts,src%2Fmain.ts

### Expected behavior

1. Create a new project
2. Install class-validators and class-transform packages
3. Add global validation pipe with transform
4. Add an optional query param with number type, call it test
5. Make a request without test query param and the param will be NaN

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^10.0.0

### Packages versions

```
[Nest Platform Information]
platform-socket.io version : 10.2.10
platform-express version   : 10.2.10
cache-manager version      : 2.1.1
websockets version         : 10.2.10
schematics version         : 10.0.3
passport version           : 10.0.2
schedule version           : 4.0.0
swagger version            : 7.1.16
typeorm version            : 10.0.1
testing version            : 10.2.10
common version             : 10.2.10
config version             : 3.1.1
axios version              : 3.0.1
core version               : 10.2.10
cli version                : 10.2.1
```

### Node.js version

20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
how your http request looks like?

**Comment by Hareloo** [comment]
> how your http request looks like?
For example:
https://localhost:4001/api/v2/patients
Just not specifying the param

**Comment by kamilmysliwiec** [comment]
Perhaps similarly to boolean parameters, we should skip the primitives transformation when value === undefined?

**Comment by Hareloo** [comment]
> Perhaps similarly to boolean parameters, we should skip the primitives transformation when value === undefined?

I believe something like that would solve this.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Hareloo** [comment]
Created a PR for this here: https://github.com/nestjs/nest/pull/12893

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12893

**Comment by luzhenqian** [comment]
This problem is still not solved yet, my solution is:

1. Create pipe file:

```ts
// pipes/int-default-value-pipe.ts
import { PipeTransform, Injectable, ArgumentMetadata } from '@nestjs/common';

@Injectable()
export class IntDefaultValuePipe implements PipeTransform {
  constructor(private readonly defaultValue: any) {}

  transform(value: string, metadata: ArgumentMetadata): any {
    const val = parseInt(value, 10);
    return isNaN(val) ? this.defaultValue : val;
  }
}
```

2. Modify code.

Then put the original code:

```ts
@Query('page') page = 0
```

Change it to this:

```ts
@Query('page', new IntDefaultValuePipe(0)) page
```

It working.
