### ISSUE TITLE
Implementation of custom ORM's, Typegoose | Knex

### ISSUE THREAD

**Issue by MohitNishad** [nestjs/nest#12871]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am trying to use typegoose instead of mongoose because it provides more typesafty, since nest is production framework i don't want any compromises

### Describe the solution you'd like

Creating a class which can talk methods and by providing it to module we can use those ORMs which are not supported or something like that

### Teachability, documentation, adoption, migration strategy

I don't have any docs yet it was the issues which i was facing from 4 months first it was with drizzle and now with typegoose. If the solution will be helpfull then i am looking forward to contribute in the docs

### What is the motivation / use case for changing the behavior?

It will reduce overhead for creating a custome nestjs package for orms when they arrive. By creating some kind of api which let deveopers to intract with it according to their need of orm will help them

**Comment by micalevisk** [comment]
I believe this is somethign that should be handled by the nestjs community since it can be done in several ways. And then could be listed at https://github.com/nestjs/awesome-nestjs

**Comment by MohitNishad** [comment]
thank you for your support you can now close this issues 😊
