### ISSUE TITLE
Lazy loaded module cannot access global module

### ISSUE THREAD

**Issue by 5d-jh** [nestjs/nest#12879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[This issue](https://github.com/nestjs/nest/issues/9622) doesn't seem to been resolved on nestjs@9.

```
UnknownDependenciesException [Error]: Nest can't resolve dependencies of the ImportedService (?). Please make sure that the argument GLOBAL at index [0] is available in the ImportedModule context.

Potential solutions:
- Is ImportedModule a valid NestJS module?
- If GLOBAL is a provider, is it part of the current ImportedModule?
- If GLOBAL is exported from a separate @Module, is that module imported within ImportedModule?
  @Module({
    imports: [ /* the Module containing GLOBAL */ ]
  })

```

### Minimum reproduction code

https://github.com/5d-jh/nest-lazy

### Steps to reproduce

```
ts-node -T main.ts
```

### Expected behavior

Nest should inject value `hi` to `ImportedService`, resulting to print `hi` on console.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.3

### Packages versions

```json
{
  "name": "lazy",
  "version": "1.0.0",
  "dependencies": {
    "@nestjs/common": "9",
    "@nestjs/core": "9",
    "@nestjs/platform-express": "^10.2.10"
  },
  "devDependencies": {
    "ts-node": "^10.9.1",
    "typescript": "^5.3.2"
  }
}

```

### Node.js version

18.18.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12880
