### ISSUE TITLE
the ability to exclude a controller from prefixing

### ISSUE THREAD

**Issue by its-dibo** [nestjs/nest#12892]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

we can exclude some routes from prefixing as addressed [here](https://docs.nestjs.com/faq/global-prefix) as per [this feature request](https://github.com/nestjs/nest/issues/963) like this:

```
app.setGlobalPrefix('v1', { exclude: ['cats'] });
```

 

### Describe the solution you'd like

we can exclude a controller with all of its routes

```
app.setGlobalPrefix('v1', { 
 exclude: [ CatsController ] 
});
```

### Teachability, documentation, adoption, migration strategy

https://docs.nestjs.com/faq/global-prefix
https://github.com/nestjs/nest/issues/963

### What is the motivation / use case for changing the behavior?

.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
