### ISSUE TITLE
Add Feature Flagging

### ISSUE THREAD

**Issue by lukas-reining** [nestjs/nest#12903]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Feature Flagging is becoming pretty popular in organizations and larger projects.
For Nest.js there is no idiomatic way of including feature flagging into an application. 
I would propose to have a module that helps using feature flags in these apps.
Feature flagging could become a new technique in the docs.

### Describe the solution you'd like

As the [OpenFeature](https://openfeature.dev/) Team, we think of building an OpenFeature module for Nest.js as we had the request from the community for this and the large adoption of Nest.js in the industry. 
We have an open issue here: https://github.com/open-feature/js-sdk/issues/705
This would make it easy to integrate any feature flagging api or something like in-memory or environment variable providers to a Nest.js app, either by using an existing provider implementation or writing a small provider.

If it is interesting to the Nest.js project we could collaborate on getting this into the project.

### Teachability, documentation, adoption, migration strategy

It would be great to have feature flagging being documented as a technique in the Nest.js docs.

### What is the motivation / use case for changing the behavior?

We want to build a module OpenFeature Module for Nest.js which would best be served in the Nest.js repos.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
