### ISSUE TITLE
MongoDB ParseObjectIdPipe or ObjectIdPipe validation for NestJS

### ISSUE THREAD

**Issue by emileyski** [nestjs/nest#12919]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In NestJS for relational databases, we can validate IDs using ParseUUIDPipe or ParseIntPipe (depending on the ID type) in the controller, but there is no built-in pipe for validating and converting IDs of type ObjectID from Mongoose.

### Describe the solution you'd like

It would be ideal to have a ParseObjectIdPipe similar to ParseUUIDPipe. It can be implemented from PipeTransform<string, ObjectID>:

```ts
import { Injectable, PipeTransform } from '@nestjs/common';
import { Types } from 'mongoose';

@Injectable()
export class ParseObjectIdPipe implements PipeTransform<string, Types.ObjectId>
{
  transform(value: string): Types.ObjectId {
    // validation and transformation
  }
}
```

### Teachability, documentation, adoption, migration strategy

When using Mongoose package:

```ts
import { Types } from 'mongoose';

// Controller
@Get(':id')
  findOne(@Param('id', ParseObjectIdPipe) id: Types.ObjectId) {
  // ...
}
```

When using MongoDB package:

```ts
import { ObjectID } from 'mongodb';

// Controller
@Get(':id')
  findOne(@Param('id', ParseObjectIdPipe) id: ObjectID) {
  // ...
}
```

### What is the motivation / use case for changing the behavior?

I just want to validate and transform incoming ID params in my Controller or even ID properties in DTOs of type ObjectID from MongoDB.

**Comment by micalevisk** [comment]
thanks for you suggestion!

I believe that this is too specific to live under `@nestjs/common`. To me, the nestjs community should maintain such pipes instead.

**Comment by vlbras** [comment]
Thanks for sharing your solution! NestJS is platform agnostic, which means this pipe will not be added to core packages just to work with MongoDB.

I created and published a package that will help you to not only transform and validate not only incoming ID params in Controller but also ID properties in DTOs:

## Installation

```
npm install nestjs-object-id
```

## Usage

### @IsObjectId()
@IsObjectId() is a decorator for validating MongoDB Object IDs in DTOs.
<br>Here is an example along with commonly used `IsString` and `IsNotEmpty` from [class-validator](https://github.com/typestack/class-validator) package.

```ts
import { IsObjectId } from 'nestjs-object-id';
import { IsString, IsNotEmpty } from 'class-validator';

class UpdatePostDTO {
    @IsObjectId()
    authorId: string;

    @IsString()  
    @IsNotEmpty()
    title: string;
}
```

### IsObjectIdPipe
IsObjectIdPipe is a pipe for validating MongoDB Object IDs in route parameters. 
```ts
import { IsObjectIdPipe } from 'nestjs-object-id';

@Controller('posts')
export class PostsController {
  constructor(private readonly postsService: PostsService) {}

  @Get(':id')
  findOne(@Param('id', IsObjectIdPipe) id: string) {
    return this.postsService.findOne(id);
  }
}
```

### ParseObjectIdPipe
ParseObjectIdPipe extends the functionality of IsObjectIdPipe by converting string parameters into Types.ObjectId instances. 
```ts
import { ParseObjectIdPipe } from 'nestjs-object-id';
import { Types } from 'mongoose';

@Controller('posts')
export class PostsController {
  constructor(private readonly postsService: PostsService) {}

  @Get(':id')
  findOne(@Param('id', ParseObjectIdPipe) id: Types.ObjectId) {
    return this.postsService.findOne(id);
  }
}
```

**Comment by emileyski** [comment]
> Thanks for sharing your solution! NestJS is platform agnostic, which means this pipe will not be added to core packages just to work with MongoDB.
> 
> I created and published a package that will help you to transform and validate not only incoming ID params in Controller but also ID properties in DTOs:
> 
> ## Installation
> ```
> npm install nestjs-object-id
> ```
> 
> ## Usage
> ### IsObjectIdPipe
> IsObjectIdPipe is a pipe for validating MongoDB Object IDs in route parameters.
> 
> ```ts
> import { IsObjectIdPipe } from 'nestjs-object-id';
> 
> @Controller('posts')
> export class PostsController {
>   constructor(private readonly postsService: PostsService) {}
> 
>   @Get(':id')
>   findOne(@Param('id', IsObjectIdPipe) id: string) {
>     return this.postsService.findOne(id);
>   }
> }
> ```
> 
> ### ParseObjectIdPipe
> ParseObjectIdPipe extends the functionality of IsObjectIdPipe by converting string parameters into Types.ObjectId instances.
> 
> ```ts
> import { ParseObjectIdPipe } from 'nestjs-object-id';
> import { Types } from 'mongoose';
> 
> @Controller('posts')
> export class PostsController {
>   constructor(private readonly postsService: PostsService) {}
> 
>   @Get(':id')
>   findOne(@Param('id', ParseObjectIdPipe) id: Types.ObjectId) {
>     return this.postsService.findOne(id);
>   }
> }
> ```
> 
> ### @IsObjectId()
> @IsObjectId() is a decorator for validating MongoDB Object IDs in DTOs. Here is an example along with commonly used `IsString` and `IsNotEmpty` from [class-validator](https://github.com/typestack/class-validator) package.
> 
> ```ts
> import { IsObjectId } from 'nestjs-object-id';
> import { IsString, IsNotEmpty } from 'class-validator';
> 
> class UpdatePostDTO {
>     @IsObjectId()
>     authorId: string;
> 
>     @IsString()  
>     @IsNotEmpty()
>     title: string;
> }
> ```

Thank you, your solution helped

**Comment by kamilmysliwiec** [comment]
Thanks @vlbras!
