### ISSUE TITLE
NestJS Graceful shutdown

### ISSUE THREAD

**Issue by JuTiger-Lee** [nestjs/nest#12913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I tried graceful shutdown but I failed
I first used @nestjs/typeorm package, but This package db connection close before the work is finished

I tried process like this
1. Database record lock in workbench
2. lock wating in nestjs application
3. excute command pm2 restart different terminal
4. lock clear(excute command is "ROLLBAKC") in workbench
5. excute query in nestjs application
6. excute error message "[TypeORMError: Connection is not established with mysql database" in nestjs application

and I  next used typeorm package, This package is ignore and server exist

When Nestjs try graceful shutdown, Nestjs should confirm event loop stack and thread pool
The current method is unsafe

### Minimum reproduction code

notthing

### Steps to reproduce

1. Database record lock in workbench
2. lock wating in nestjs application
3. excute command pm2 restart different terminal
4. lock clear(excute command is "ROLLBAKC") in workbench
5. excute query in nestjs application
6. excute error message "[TypeORMError: Connection is not established with mysql database" in nestjs application

### Expected behavior

I think When Nestjs try graceful shutdown, Nestjs should confirm event loop stack and thread pool

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/tyeprom

### NestJS version

9.0.0

### Packages versions

```json
{
 "dependencies": {
   "@nestjs/tyeprom": "^9.0.0",
   "@nestjs/common": "^9.0.0",
   "@nestjs/core": "^9.0.0",
   "@nestjs/microservices": "^9.2.1",
   "typerom": "^0.3.7",
   ....
}
}
```

### Node.js version

v18.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
