### ISSUE TITLE
Dynamic Module can't use ConfigurableModuleBuilder MODULE_OPTIONS_TOKEN

### ISSUE THREAD

**Issue by ZimGil** [nestjs/nest#12910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Nest can't resolve dependencies of the Symbol() (?). Please make sure that the argument "CONFIGURABLE_MODULE_OPTIONS[4dfb49aef07f49aba685f]" at index [0] is available in the SomeModule context

### Minimum reproduction code

https://github.com/ZimGil/nest-dynamic-module-issue

### Steps to reproduce

1. `npm i`
2. `npm start`
3. See error

### Expected behavior

`MODULE_OPTIONS_TOKEN` should be available for the imports part of a dynamic module

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^9.0.0 || ^10.0.0 

### Packages versions

[System Information]
OS Version     : macOS Unknown
NodeJS Version : v16.17.1
NPM Version    : 8.15.0

[Nest CLI]
Nest CLI Version : 10.2.1

[Nest Platform Information]
platform-express version : 10.2.10
schematics version       : 10.0.3
testing version          : 10.2.10
common version           : 10.2.10
core version             : 10.2.10
cli version              : 10.2.1

### Node.js version

20.8.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Remove this import https://github.com/ZimGil/nest-dynamic-module-issue/blob/main/src/app.module.ts#L8

Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
