### ISSUE TITLE
Wrong `Object` prototype in repl context

### ISSUE THREAD

**Issue by othierry** [nestjs/nest#12916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello Nestjs team! 👋 

`Object` prototype in nestjs repl context seems to diverge from the `Object` prototype from main context. **See the code sandbox below to see an example.**

This causes runtime issues in repl especially for libraries (ex: typeorm 0.2.45) which checks for `instanceof Object` at runtime. 

```ts
// typeorm ex.
$(UserDAO).update({ id: 42 }, { firstName: 'oli' }) // will throw in repl and work in node
```

As described [here](https://github.com/nodejs/node/issues/27859) the issue was confirmed in node.js repl module.

When using `useGlobal: true` in the repl `start()` options, it works as expected (solution given [here](https://github.com/nodejs/node/issues/27859#issuecomment-495761434)).

### Minimum reproduction code

https://codesandbox.io/p/devbox/jolly-kapitsa-ynrtcq

### Steps to reproduce

From code sandbox

```bash
yarn start
> x = {}
{}
> x instanceof Object
true
> $(AppService).isInstanceOfObject(x)
false
> $(AppService).isSpreadCopyInstanceOfObject(x)
true
```

### Expected behavior

As described [here](https://github.com/nodejs/node/issues/27859) the issue was confirmed in node'js repl module.

When using `useGlobal: true` in the repl `start()` options it works as expected (solution given [here](https://github.com/nodejs/node/issues/27859#issuecomment-495761434)).

Potential solution: Allowing `node`'s repl `start` options has a second parameter of `nestjs`'s `repl` function would allow users to specify specific options such as `useGlobal` if needed.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/cli": "^10.0.1",
    "@nestjs/schematics": "^10.0.1",
    "@nestjs/testing": "^10.0.0",
```

### Node.js version

20.9.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [x] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by othierry** [comment]
> Would you like to create a PR for this issue?

Sure 👍

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12924
