### ISSUE TITLE
Consider supporting reflect-metadata@^0.2.1

### ISSUE THREAD

**Issue by notaphplover** [nestjs/nest#12926]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

NestJs libraries have a peer dependency of `reflect-metadata@^0.1.12`, so `0.2.X` versions are not supported (consider [docs](https://github.com/npm/node-semver?tab=readme-ov-file#caret-ranges-123-025-004)) as reference.

### Describe the solution you'd like

Since `reflect-metadata@0.2.X` are not introducing any breaking changes, it would be great if they could be accepted in the range of the peer dependencies.

### Teachability, documentation, adoption, migration strategy

The migration strategy would consist in updating package peer dependencies to also allow `reflect-metadata@0.2.X`

### What is the motivation / use case for changing the behavior?

Updating `reflect-metadata` dependencies of my packages that are implemented on top of the NestJS framework.

**Comment by schiller-manuel** [comment]
Should nestjs then use the newly introducted `reflect-metadata/lite` export?
see https://github.com/rbuckton/reflect-metadata/pull/144

**Comment by KostyaTretyak** [comment]
> Should nestjs then use the newly introduced `reflect-metadata/lite` export? see [rbuckton/reflect-metadata#144](https://github.com/rbuckton/reflect-metadata/pull/144)

From the linked PR:
> The polyfill-free `/lite` and `/no-conflict` exports require a runtime or bundler that supports [package.json subpath exports](https://nodejs.org/dist/latest-v20.x/docs/api/packages.html#subpath-exports).

So, as far as I understand, `reflect-metadata/lite' will be used in NestJS only after migration to ECMAScript modules.

**Comment by schiller-manuel** [comment]
Is the migration to ESM on the horizon?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/12943

**Comment by notaphplover** [comment]
@kamilmysliwiec there seem to be trouble in the CI to merge #12943, would it be ok if we submit a PR to properly update the constraints? Once its merged it will allow renovatebot to properly update example packages.
