### ISSUE TITLE
NestJS CLI MODULE_NOT_FOUND with Docker

### ISSUE THREAD

**Issue by mohsenamjadi** [nestjs/nest#12946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm implementing a **NestJS** microservices project in a monorepo structure. Suppose that I have two microservices that have the same **Dockerfiles**, and I am running the project using a **docker-compose** file. the docker-compose file is as follows:

    services:
      firstMicroservice:
        build:
          context: .
          dockerfile: ./apps/firstMicroservice/Dockerfile
          target: development
        command: pnpm run start:dev firstMicroservice
        env_file:
          - ./apps/firstMicroservice/.env
        ports:
          - '3000:3000'
        volumes:
          - .:/usr/src/app
      auth:
        build:
          context: .
          dockerfile: ./apps/auth/Dockerfile
          target: development
        command: pnpm run start:dev auth
        env_file:
          - ./apps/auth/.env
        ports:
          - '3001:3001'
        volumes:
          - .:/usr/src/app    
      mongo:
        image: mongo

Then here is my Dockerfile (as an example of my Dockerfiles):

    FROM node:alpine As development

    WORKDIR /usr/src/app

    COPY package.json ./
    COPY pnpm-lock.yaml ./

    RUN npm install -g pnpm
    RUN npm install -g @nestjs/cli
    RUN pnpm install

    COPY . .

    RUN pnpm run build

    FROM node:alpine as production

    ARG NODE_ENV=production
    ENV NODE_ENV=${NODE_ENV}

    WORKDIR /usr/src/app

    COPY package.json ./
    COPY pnpm-lock.yaml ./

    RUN npm install -g pnpm
    RUN npm install -g @nestjs/cli
    RUN pnpm install --prod 

    COPY --from=development /usr/src/app/dist ./dist

    CMD ["node", "dist/apps/auth/main"]

The problem is that when I run docker-compose up I get this error:

    auth-1   | > nest start --watch "auth"
    auth-1   |
    auth-1   | node:internal/modules/cjs/loader:1147
    auth-1   |   throw err;
    auth-1   |   ^
    auth-1   |
    auth-1   | Error: Cannot find module '/usr/src/app/node_modules/@nestjs/cli/bin/nest.js'
    auth-1   |     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    auth-1   |     at Module._load (node:internal/modules/cjs/loader:985:27)
    auth-1   |     at Function.executeUserEntryPoint [as runMain] 
    (node:internal/modules/run_main:135:12)
    auth-1   |     at node:internal/main/run_main_module:28:49 {
    auth-1   |   code: 'MODULE_NOT_FOUND',
    auth-1   |   requireStack: []
    auth-1   | }
    auth-1   |
    auth-1   | Node.js v21.4.0
    auth-1   |  ELIFECYCLE  Command failed with exit code 1.

The interesting thing is that when I change the **WORKDIR** in the Dockerfile to **/app** instead of **usr/src/app** the error is not showing anymore and the application works. but in this case, if I change the **volumes** address in the **docker-compose** to **/app** too, the error shows up again.

As much as I know these two addresses should be the same but when they are the same I get the error about **not finding** the **nestjs cli module**. also when I change the address to /app, I don't have **hot reloading** anymore and I think something is wrong with this solution. 

**I would appreciate it if anyone could help or if you give me any idea about this**. also, I want to know other than hot reloading that I miss, **what problem it might cause** if these **two addresses are not the same**.

### Minimum reproduction code

https://github.com/

### Expected behavior

The docker-compose runs microservices successfully with no errors about NestJS-Cli, as I am installing it globally in the container.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/cli

### NestJS version

10.2.10

### Packages versions

```json
{
  "name": "projectname",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"apps/**/*.ts\" \"libs/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/apps/bolibz/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./apps/bolibz/test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.10",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/microservices": "^10.2.10",
    "@nestjs/mongoose": "^10.0.2",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.0.0",
    "@types/bcryptjs": "^2.4.6",
    "bcryptjs": "^2.4.3",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cookie-parser": "^1.4.6",
    "express": "^4.18.2",
    "joi": "^17.11.0",
    "mongoose": "^8.0.3",
    "nestjs-pino": "^3.5.0",
    "passport": "^0.7.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "pino-http": "^8.6.0",
    "pino-pretty": "^10.3.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/cookie-parser": "^1.4.6",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/passport-jwt": "^3.0.13",
    "@types/passport-local": "^1.0.38",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": ".",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node",
    "roots": [
      "<rootDir>/libs/",
      "<rootDir>/apps/"
    ],
    "moduleNameMapper": {
      "^@app/common(|/.*)$": "<rootDir>/libs/common/src/$1"
    }
  }
}
```

### Node.js version

18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I've been using [this](https://gist.github.com/micalevisk/9ee47135b22f284dd73de6ea6d5aa864) dockerfile just fine

**Comment by mohsenamjadi** [comment]
> I've been using [this](https://gist.github.com/micalevisk/9ee47135b22f284dd73de6ea6d5aa864) dockerfile just fine

You are also using /app as WORKDIR in your Dockerfile, as I said when I use /app it works fine but what about the volumes section in my docker-compose? because when these two addresses are same, the project gives the error. is this issue something related to the WORKDIR address?? or access issues related to usr/src/app?  I also gave it 777 permission and it is not working!

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
