### ISSUE TITLE
MQTT payload parser crop data

### ISSUE THREAD

**Issue by muei** [nestjs/nest#12952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[System Information]
OS Version     : Linux 5.15
NodeJS Version : v20.10.0

[Nest CLI]
Nest CLI Version : 10.2.1 

[Nest Platform Information]
platform-express version : 10.2.10
microservices version    : 10.2.10
schematics version       : 10.0.3
testing version          : 10.2.10
common version           : 10.2.10
config version           : 3.1.1
core version             : 10.2.10
cli version              : 10.2.1

### Minimum reproduction code

none

### Expected behavior

```js
// # AppController

  @MessagePattern("/testtopic")
  handleRequest(@Payload() payload: string, @Ctx() context: MqttContext) {
    const message = JSON.stringify(payload)

    console.log(`Topic: ${context.getTopic()} Data:\n${message} `)
  }
```
```
// # main.ts
const app = await NestFactory.createMicroservice<MicroserviceOptions>(AppModule, {
  transport: Transport.MQTT,
  options: {
    url: 'mqtt://localhost:1883',
  },
});
```

Then send the test data:
```
{

  "data": {
    "tag":"1"
  },
  "id": "409584236",
  "method": "GET",
  "path": "/groups"
}
```

the controller can receive part of data of data node:
```
{
    "tag":"1"
 }
```

if the test data has no `data` property, will receive the whole struct.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

none

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.0.0",
    "@nestjs/microservices": "^10.2.10",
    "@nestjs/platform-express": "^10.0.0",
    "dotenv": "^16.3.1",
    "joi": "^17.11.0",
    "js-yaml": "^4.1.0",
    "mqtt": "^5.3.3",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },

```

### Node.js version

v20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

...

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.

**Comment by tthdvd** [comment]
Hi!

I have the same issue (macOS), I don't get why this has been closed.

I also looked after it in Discord but I couldn't find any resolution there. (Only messages that said "I was redirected to here from the GitHub issue").

In my opinion, the issue should be closed if it has been resolved somehow, not by redirecting users to Discord channels or it should be reopened. 
 
@muei  please let me know if you have any resolution for this issue, it would be very helpful!

**Comment by muei** [comment]
@tthdvd Hi brother, I've already looked into it on Discord, and many people are having the same issue, which has been around for a year or even longer. I've also mentioned it to the official team, but they haven't made any response or improvements. I'm very disappointed with NestJS, so for new projects, I no longer consider using NestJS.

**Comment by kamilmysliwiec** [comment]
MQTT strategy always passes on **only the** `data` attribute as the message payload (by design) so just move your other properties there as well when sending messages to a broker from outside Nest application context.
