### ISSUE TITLE
Issue with reflect-metadata v.0.2.1 when using @nestjs/axios

### ISSUE THREAD

**Issue by thepphithakP** [nestjs/nest#12951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

> nest build

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @nestjs/axios@3.0.1
npm ERR! Found: reflect-metadata@0.2.1
npm ERR! node_modules/reflect-metadata
npm ERR!   reflect-metadata@"^0.2.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer reflect-metadata@"^0.1.12" from @nestjs/axios@3.0.1
npm ERR! node_modules/@nestjs/axios
npm ERR!   @nestjs/axios@"^3.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: reflect-metadata@0.1.14
npm ERR! node_modules/reflect-metadata
npm ERR!   peer reflect-metadata@"^0.1.12" from @nestjs/axios@3.0.1
npm ERR!   node_modules/@nestjs/axios

### Minimum reproduction code

https://github.com/

### Steps to reproduce

I'm encountering an issue when trying to use reflect-metadata version "^0.2.1" in combination with the "@nestjs/axios" package. The error occurs when running the npm run build or nest build command.

### Expected behavior

I expect the build process to complete successfully without any dependency resolution issues.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Packages versions

"dependencies": {
    "@fastify/static": "^6.12.0",
    "@fastify/view": "^8.2.0",
    "@nestjs/axios": "^3.0.1",
    "@nestjs/common": "^10.3.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.3.0",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mapped-types": "^2.0.4",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.3.0",
    "@nestjs/platform-fastify": "^10.3.0",
    "@nestjs/schedule": "^4.0.0",
    "@nestjs/swagger": "^7.1.17",
    "@nestjs/typeorm": "^10.0.1",
    "axios": "^1.6.2",
    "bcrypt": "^5.1.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "handlebars": "^4.7.8",
    "hbs": "^4.2.0",
    "jsonwebtoken": "^9.0.1",
    "moment": "^2.29.4",
    "nest-winston": "^1.9.3",
    "passport": "0.7.0",
    "passport-jwt": "^4.0.1",
    "pg": "^8.11.2",
    "reflect-metadata": "0.1.14",
    "rxjs": "^7.2.0",
    "sqlite3": "^5.1.6",
    "typeorm": "^0.3.17",
    "winston": "^3.11.0",
    "winston-daily-rotate-file": "^4.7.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.2.1",
    "@nestjs/schematics": "^10.0.3",
    "@nestjs/testing": "^10.3.0",
    "@types/bcrypt": "^5.0.2",
    "@types/express": "^4.17.21",
    "@types/hbs": "^4.0.4",
    "@types/jest": "29.5.11",
    "@types/node": "20.10.5",
    "@types/passport-jwt": "^3.0.13",
    "@types/supertest": "^2.0.16",
    "@typescript-eslint/eslint-plugin": "^6.15.0",
    "@typescript-eslint/parser": "^6.15.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.0.1",
    "jest": "^29.7.0",
    "prettier": "^3.1.1",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.1.1",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "4.2.0",
    "typescript": "^5.3.3"
  },

### Node.js version

20.0.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
