### ISSUE TITLE
Problem with Websockets receiving data from 3rd party service

### ISSUE THREAD

**Issue by dmitriy-uvin** [nestjs/nest#12956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Problem with ngrok websockets.
When I go to the ngrok link I have a simple HTML page where I am able to connect to websockets.
On the backend, I have a simple method that allows you to fetch some messages to the frontend and it works.

But, I need to receive and establish a connection with Twilio.
![photo_2023-12-21_20-21-26](https://github.com/twilio/twilio-node/assets/51481296/e89ad714-6960-4d81-80b2-25c5744883ec)
The first screenshot (where is no code response) it's when Twilio tries to establish websocket connection.

![photo_2023-12-21_20-22-16](https://github.com/twilio/twilio-node/assets/51481296/765e5dc4-a119-41ae-a093-357770334737)
The second one (with response code) it's when I connect from index.html, and that works.

![photo_2023-12-21_20-23-06](https://github.com/twilio/twilio-node/assets/51481296/ce06cd73-de5c-440b-9d32-04182729ff88)
The third one is the error in Twilio logs.

How it can be solved?

### Minimum reproduction code

https://github.com/dmitriy-uvin/cold-caller

### Steps to reproduce

1. register in Twilio
2. Get Twilio keys
3. Purchase number
4. input your number to receive a call
5. See in empty terminal (no message from websockets)

### Expected behavior

I can see data received from other server via Websockets.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

{
  "name": "ai-agent",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/platform-socket.io": "^10.3.0",
    "@nestjs/serve-static": "^4.0.0",
    "@nestjs/websockets": "^10.3.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "socket.io": "^4.7.2",
    "twilio": "^4.20.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

### Node.js version

20.9.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
We'd need a __minimal__ way to reproduce this. Nothing that requires us to purchase anything or complex setup steps.
