### ISSUE TITLE
functional hooks for context injection

### ISSUE THREAD

**Issue by nkitku** [nestjs/nest#12965]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Description

I am currently working on an NX workspace that involves an Angular and NestJS project combination. In experimenting to directly import NestJS controllers as functions into Angular.

Here's a simplified example of what I'm trying to achieve:

#### NestJS Controller (app.controller.ts)

```ts
import { Body, Controller, Get, Post, Query } from '@nestjs/common';
import { LoginUser } from './decorators/auth.decorator';
import { ActiveUser } from './models/active-user.model';

@Controller()
export class AppController {
  @Get('getHello')
  async getHello(@Query() query: { name: string }) {
    // ... method implementation
  }

  @Auth()
  @Post('sayHello')
  async sayHello(@Body() body: { name: string }, @LoginUser() user: ActiveUser) {
    // ... method implementation
  }
}
```

#### Angular Component (app.component.ts)

```ts
import { HttpClient } from '@angular/common/http';
import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import type { AppController } from '@package/api/app/app.controller';
import { firstValueFrom } from 'rxjs';

const proxyMaker = (controllerName = '') => {
  const httpClient = inject(HttpClient);
  const destroyRef = inject(DestroyRef);
  const proxy = new Proxy(
    {},
    {
      get: (target, prop: string) => {
        if (target[prop]) return target[prop];
        const httpMethod = prop.startsWith('get') ? 'get' : 'post';
        const url = simplifyPath(`/api/${controllerName}/${prop}`);
        const toPromise = (obs: any) => firstValueFrom(obs.pipe(takeUntilDestroyed(destroyRef)));
        if (httpMethod === 'get') target[prop] = (query: any) => toPromise(httpClient.get(url, { params: query }));
        else {
          target[prop] = (query: any, body: any) => {
            if (body === undefined) [query, body] = [{}, query];
            return toPromise(httpClient.post(url, body ?? {}, { params: query }));
          };
        }
        return target[prop];
      },
    },
  );
  return proxy as any;
};

@Component({ selector: 'app' })
export class AppComponent implements OnInit, OnDestroy {
  readonly #appController: AppController = proxyMaker();

  ngOnInit(): void {
    {
      const hello = await this.#appController.getHello({ name: 'test' });
      console.log(hello);
    }
    {
      // Type error occurs here
      const hello = await this.#appController.sayHello({ name: 'test' });
      console.log(hello);
    }
  }
}
```

### Issue

The problem arises when attempting to call the `sayHello` function from the NestJS controller proxy. The `sayHello` function requires a second parameter, `user`, which is resolved by a custom decorator `@LoginUser()`.

### Describe the solution you'd like

I am looking for a way to achieve the desired behavior without relying on a parameter decorator. Instead, I am exploring the possibility of using a hook-like mechanism similar to Angular's `inject` for dependency injection.

Here's a hypothetical example of the desired NestJS controller modification:

```ts
@Auth()
@Post('sayHello')
async sayHello(@Body() body: { name: string }) {
  const user: ActiveUser = inject(LoginUser);
  // ... method implementation
}
```

This modification would allow seamless integration with the NestJS controller proxy in Angular, addressing the current type error issue.

I appreciate your consideration and look forward to any insights or suggestions on achieving this functionality. Thank you!

### Teachability, documentation, adoption, migration strategy

mentioned above

### What is the motivation / use case for changing the behavior?

Enabling TypeScript to derive richer contextual information directly from the imported API functions would undoubtedly boost productivity and code maintainability.

**Comment by micalevisk** [comment]
see https://github.com/nestjs/nest/issues/10586#issuecomment-1324707932

**Comment by nkitku** [comment]
I'd like to reopen this issue because my situation is different from what issue you mentioned. It seems like there might be some confusion around the `inject` function (which was just an example I used). Instead, I'm thinking we could use `useCtx()` like this:

```typescript
@Auth()
@Post('sayHello')
async sayHello(@Body() body: { name: string }) {
  const ctx: ExecutionContext = useCtx();
  // ... method implementation
}
```

> cool but why? nestjs is a nodejs fw, not a angularjs fw

I'm not integrating NestJS with Angular; rather, I'm using NestJS types in the frontend. This way, I avoid having to define types in both the frontend and backend, plus there's no need to write endpoints in the frontend. I've given it a shot, and it works like a charm!

**Comment by nkitku** [comment]
@micalevisk, Alternatively, if there's already a workaround to obtain context without relying on parameters and a request-scoped controller

**Comment by nkitku** [comment]
thanks to reopen this issue, I found a hacky way to do this, but need a better way to do this to support more features.

```typescript
export interface CustomHookCtx {
  req: any;
  res: any;
}

let customCtx: CustomHookCtx;

export function useCtx(): CustomHookCtx;
export function useCtx<T>(fn: (ctx: CustomHookCtx) => T): T;
export function useCtx<T>(fn?: (ctx: CustomHookCtx) => T) {
  return fn ? fn(customCtx) : customCtx;
}

// modify handler function in the RouterExecutionContext#create method
RouterExecutionContext.prototype.create = function (instance: Controller, callback: (...args: any[]) => unknown, methodName: string, moduleKey: string, requestMethod: RequestMethod, contextId = STATIC_CONTEXT, inquirerId?: string) {
  /// ....

  const handler =
    <TRequest, TResponse>(args: any[], req: TRequest, res: TResponse, next: Function) =>
    async () => {
      fnApplyPipes && (await fnApplyPipes(args, req, res, next));
      // ------------------------------
      customCtx = { req, res } as any;
      const output = callback.apply(instance, args);
      customCtx = undefined;
      // ------------------------------
      return output;
    };

  /// ....
};
```

### Usage

```typescript
export const LoginUserCtx = (ctx: CustomHookCtx) => (ctx.req as any).user?.() as ActiveUser;

@Controller()
export class AppController {
  @Auth()
  @Post()
  async create(@Body() body) {
    const user = useCtx(LoginUserCtx);
  }
}
```

**Comment by micalevisk** [comment]
I believe that these "functional approaches" doesn't fits well into nestjs. At least not in its core. Let's see what Kamil thinks.

**Comment by nkitku** [comment]
I understand your consideration, I believe incorporating such approaches can bring significant benefits effortlessly, especially in the context of monorepos. Not only for NestJS + Angular but also for React, Vue, Solid, and even in plain js based client.

For instance:
- Full type support: Enables us to comprehend types without explicitly defining them, through type inference.
- VS Code "Go to Definition" support: Facilitates easy discovery of controllers and methods, and "Find All References" helps identify places where the API is called.
- Any modifications in the API automatically trigger errors in the frontend code, providing an early heads-up.

and it will bring a lot of ease without any major change or impact on the existing NestJS framework.

In my use case, this simple `useCtx()` function serves the purpose, but need your thoughts on this, and i think it should be named as `useHttpCtx()` instead of `useCtx()`.

**Comment by nkitku** [comment]
also created a decorator to auto set path and http method

```ts
export const HttpAPI = () => {
  return (
    target: object,
    key: string,
    descriptor: TypedPropertyDescriptor<any>
  ) => {
    // set function name as path
    Reflect.defineMetadata(PATH_METADATA, key, descriptor.value);
    // set http method to get if function name starts with get else post
    Reflect.defineMetadata(
      METHOD_METADATA,
      key.startsWith("get") ? RequestMethod.GET : RequestMethod.POST,
      descriptor.value
    );
    return descriptor;
  };
};
```

usage example

```ts
@Controller("app")
export class AppController {
  @Auth()
  @HttpAPI() // this will set path (store) and http method (Post)
  async store(@Body() body: { name: string }) {
    const user = useHttpCtx(LoginUserCtx);
    return { same: user.name === body.name };
  }
}
```

in angular

```ts
import type { AppController } from "@package/api/app.controller";

@Component({ selector: "app" })
export class AppComponent implements OnInit {
  readonly #appController = useController<AppController>("app");

  ngOnInit(): void {
    const { same } = await this.#appController.store({ name: "test" });
    console.log(same);
  }
}
```

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
