### ISSUE TITLE
Support Javascript in Resource schematic

### ISSUE THREAD

**Issue by AlvesJorge** [nestjs/nest#12978]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Was following the "Build a REST API With NestJS and Prism" tutorial and I came across 
`Failed to execute command: node @nestjs/schematics:resource --no-dry-run --no-skip-import --language="js" --source-root="src" --spec --no-flat --spec-file-suffix="spec"`

I can't find anywhere in the documentation saying that this is a TS only feature.

TS Will one day die and Javascript will remain, I don't get why TS is getting priority treatment that JS isn't, I mean it's in the name, Nest**JS**.

With the complains out of the way, 
Thank you for building open source software :) 

### Describe the solution you'd like

- Build the feature for Javascript

### Teachability, documentation, adoption, migration strategy

No Comment.

### What is the motivation / use case for changing the behavior?

Use Javascript instead of Typescript

**Comment by micalevisk** [comment]
> TS Will one day die

But then Nest will die as well, as it is written in TS, right?

tbh I don't think that JS could survive without TS. Even new JS runtimes are supporting TS by default

Anyways. We need to fix the support for plain JS, I guess

**Comment by micalevisk** [comment]
nvm, I just ran `npx nest generate resource` in a app using the [JS starter](https://github.com/nestjs/javascript-starter/) and got the following error

![image](https://github.com/nestjs/nest/assets/13461315/44e87875-118f-414b-94c7-3e6976982780)

> The "resource" schematic does not support JavaScript language (only TypeScript is supported)

**Comment by AlvesJorge** [comment]
> But then Nest will die as well, as it is written in TS, right?

Only if you're being pessimistic 😅 

> tbh I don't think that JS could survive without TS.
Why not? 
Not only there's other less intrusive type annotations (JSDoc), there's a [proposal ](https://github.com/tc39/proposal-type-annotations)for optional typing (a la python) integrated directly into JS.
Besides, there's nothing wrong with a dynamic language, I'm just tired of pretending like typescript is solving more issues than it is causing. Also, Microsoft.

Also the web runs on **Javascript**, it's not going away.

**Comment by derrickmehaffy** [comment]
Welp I was going to test out Nest for a project within our company but if this is the way Nest is going I'm out as well, I'll go look at other frameworks that don't force Typescript on users.

**Comment by AlvesJorge** [comment]
@derrickmehaffy please reply if you found any MVC JS Frameworks that aren't either really old, or force you to use Typescript.
