### ISSUE TITLE
If I was developing in pure js how would I use a function decorator and now I use a function decorator that starts with an error like @UploadedFile()

### ISSUE THREAD

**Issue by 1214368261** [nestjs/nest#12976]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

If I was developing in pure js how would I use a function decorator and now I use a function decorator that starts with an error like @UploadedFile()

### Describe the solution you'd like

If I was developing in pure js how would I use a function decorator and now I use a function decorator that starts with an error like @UploadedFile()

### Teachability, documentation, adoption, migration strategy

If I was developing in pure js how would I use a function decorator and now I use a function decorator that starts with an error like @UploadedFile()

### What is the motivation / use case for changing the behavior?

If I was developing in pure js how would I use a function decorator and now I use a function decorator that starts with an error like @UploadedFile()

**Comment by 1214368261** [comment]
![c8980ad602ba077d613b0419cf61436](https://github.com/nestjs/nest/assets/58449160/c34f1be8-7c84-4739-9e85-a258a3fd6a04)
![bdf0afbb539e2f52f326edf83b6e532](https://github.com/nestjs/nest/assets/58449160/5985998c-70bf-43ca-978b-5f8fa99ae5db)

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
