### ISSUE TITLE
How to receive Long or int64 type parameters

### ISSUE THREAD

**Issue by wang1223440313** [nestjs/nest#12971]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

How to receive Long or int64 type parameters

### Describe the solution you'd like

support Long or int64 type param

### Teachability, documentation, adoption, migration strategy

direct use param or custom transform 

### What is the motivation / use case for changing the behavior?

no support java Long type param; Param loss accuracy in body

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
