### ISSUE TITLE
Issue of durable provider with worker

### ISSUE THREAD

**Issue by huuduynvc** [nestjs/nest#12997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use durable provider to multiple mongoose connection with nestjs. The problem is that I cannot use request scope for workers.

### Minimum reproduction code

github.com/huuduynvc

### Expected behavior

 I want workers to reuse the functions of services.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
