### ISSUE TITLE
Limiting the number of requests based on the client IP.

### ISSUE THREAD

**Issue by ManucherKM** [nestjs/nest#13002]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hi all. In my project, to limit the number of requests to avoid DDOS attack, I am using throttler package. But it returns error code 429 if the number of requests exceeds the allowed threshold for a certain time to all clients that are not involved in DDOS attack. Let's say I have set that there should be no more than 10 requests per 1 second for a certain root. If there is a DDOS attack on this root, the API will throw error 429 to absolutely everyone, including users in the browser who are not participating in the DDOS attack. As a result, the root will simply be blocked until the DDOS attack is over or until the server for the API goes down. The IP example is 1 of the possible solutions to the problem. Perhaps for Nest.js there are already variants of solving this problem, I would be glad to have your suggestions.

### Describe the solution you'd like

I apologize for the formatting. I can't get it right on GitHub.
`ThrottlerModule.forRoot([
			{
				ttl: 1000,
				limit: 10,
				ip: true
			},
		])`

### Teachability, documentation, adoption, migration strategy

I don't think it's a big topic to do separate documentation for this question. In my opinion it would be more correct to add it to https://docs.nestjs.com/security/rate-limiting section with code examples.

### What is the motivation / use case for changing the behavior?

Motivation according to the problem described earlier.

**Comment by jmcdo29** [comment]
`@nestjs/throttler` already uses the IP as a part of request tracking. More than likely, you're behind a reverse proxy and all requests that come into your server are being seen as the reverse-proxy's IP address instead of the client's IP address. And if that's the case, you need to configure the underlying HTTP adapter to trust the proxy so that `req.ip` ends up getting the correct client IP instead of the reverse-proxy's IP.
