### ISSUE TITLE
Failed to received the event/message on Microservice with RMQ 

### ISSUE THREAD

**Issue by PacoPacoPakitor** [nestjs/nest#13006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The receiver can't handle the message in micro-service with RabbitMQ RMQ.
I tried to used `send & subscribe` & `emit`  and `EventPattern` & `MessagePattern` but it's always got same error 

`[Nest]   WARN [Server] An unsupported event was received. It has been acknowledged, so it will not be re-delivered. Pattern: notifications`

### Minimum reproduction code

https://github.com/PacoPacoPakitor/microservice-rmq

### Steps to reproduce
1.  nest start --watch
2. nest start billing --watch
3. use postman to send this request: 
    http://localhost:3000/orders?name=hha&price=123213&phoneNumber=123213
4. you will be able to see the log from orders service :
     Calling createOrder request: { name: 'hhhhhaaaa', price: 213, phoneNumber: 213 }
5. but no log from billing service

### Expected behavior

I followed the steps in the tutorial
https://docs.nestjs.com/microservices/rabbitmq  &  https://www.youtube.com/watch?v=yuVVKB0EaOQ&ab_channel=MichaelGuay 
to implement @EventPattern and @MessagePattern, it's should be log and receive messages from the Receiver.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
"dependencies": {
    "@apollo/gateway": "^2.5.5",
    "@nestjs/apollo": "^12.0.9",
    "@nestjs/axios": "^3.0.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.0.10",
    "@nestjs/mapped-types": "*",
    "@nestjs/microservices": "^10.3.0",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/throttler": "^5.1.1",
    "@prisma/client": "^5.5.2",
    "amqp-connection-manager": "^4.1.14",
    "amqplib": "^0.10.3",
   .... rest dependencies
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "prisma": "^5.4.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
```

### Node.js version

20.3.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
