### ISSUE TITLE
Allow passing a function to the @Header decorator for dynamic values

### ISSUE THREAD

**Issue by mrVito** [nestjs/nest#13012]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm trying to attach a 'Last-Modified' header on my API response and was initially trying to use this code:
```ts
@Header('Last-Modified', new Date().toUTCString())
```
Unfortunatelly this doesn't work as expected, as the value for the header is only evaluated once _at startup_ and thus it is the same value on every request.

### Describe the solution you'd like

Would be great if we could pass a function to the value argument of the `@Header` decorator that is evaluated on every request to the given endpoint so we can have _dynamic_ values for the header.

### Teachability, documentation, adoption, migration strategy

Use a function for the _value_ argument on the `@Header` decorator to evaluate an expression on every request:
```ts
@Header('Last-Modified', () => new Date().toUTCString())
```

### What is the motivation / use case for changing the behavior?

I have currently moved on to using an injected response object (using `@Res` decorator) and setting the header directly on it which is all fine, but it is not really nice to have additional native response handling code when only a simple header is needed and thus the _nest.js way_ would be much more elegant.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

Simply about this method to check if value is function and if so, execute it:

https://github.com/nestjs/nest/blob/22b7946a645255718f50fe67ae330fb1ac6be2f6/packages/core/router/router-response-controller.ts#L82-L89

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13027
