### ISSUE TITLE
Nestjs will re-initial sometimes while running in the pod

### ISSUE THREAD

**Issue by zzswang** [nestjs/nest#13011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While looking into the log from k8s pod, we found that the NestJs re-initial the application several times, but the pod never restarted. The log is full of the starting messages. like

```txt
LOG [NestFactory] Starting Nest application...
module initialized bla bla
....
LOG [NestFactory] Starting Nest application...
module initialized bla bla
....
LOG [NestFactory] Starting Nest application...
module initialized bla bla
```

I'm not quite sure whether it is a bug. But the real problem is it will register all events (through onEvent) multiple times. Lead to wrong business logic. Like create duplicated records.

The weird starting behavior will not unregister the events before re-initializing.

By the way,  another question may have something todo with it.

Will it lead to re-initialize? The pod never restart.

- the microservice is over the pressure, load too high

We use mqtt microservice, but can not find any way to rate limit it.

Thanks.

### Minimum reproduction code

I'm sorry I can't provide the code, because it can not reproduced in development environment.

### Expected behavior

Should not reinitialize, if the load is too high, some heath break, it should lead to restart process. means pod should restart, then everything should be working fine.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/mqtt

### Packages versions

```json
    "@36node/xlsx-toolkits": "^0.1.4",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/event-emitter": "^1.3.1",
    "@nestjs/mapped-types": "*",
    "@nestjs/microservices": "9.0.7",
    "@nestjs/mongoose": "^9.2.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/schedule": "^2.2.1",
    "@nestjs/swagger": "6.1.2",
    "@types/cache-manager-memcached-store": "^3.0.1",
    "cache-manager": "^4.0.0",
    "cache-manager-memcached-store": "^3.0.0",
    "cache-manager-redis-store": "^3.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "debug": "^4.3.4",
    "dotenv": "^16.0.3",
    "gcoord": "^0.3.2",
    "ioredis": "^5.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "mongodb": "^4.12.1",
    "mongoose": "^6.6.5",
    "mongoose-hidden": "^1.9.1",
    "mqtt": "^4.3.7",
    "multer": "1.4.5-lts.1",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "redis": "^4.3.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I believe that we can do nothing without some reproduction.

**Comment by zzswang** [comment]
Does anyone run into same issue?
I've tried to run some minimal code on my laptop, but failed to reproduce.

Or any hint，what will trigger the re-initial process?

**Comment by micalevisk** [comment]
> Does anyone run into same issue?

I don't think so

> what will trigger the re-initial process?

To me, only the watch mode of the Nest CLI. But you shouldn't be using the CLI in prod.

**Comment by zzswang** [comment]
Yes, we use production build in the pod.

**Comment by zzswang** [comment]
Currently, at least one thing should be concern:

for `OnEvent` function, we should check if there is any existing binding for same function instance before we register the event.

**Comment by zzswang** [comment]
Now for save, the work around we start to work for the online service:

remove all event mechanism, and directly call the other module's service instead.

**Comment by kamilmysliwiec** [comment]
I have never seen a similar error myself nor has anyone ever reported this. Sounds like an issue with your project - we can't say much without the reproduction repository.

If you manage to reproduce this locally, please create a new issue and provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
