### ISSUE TITLE
Support Hono Web Framework

### ISSUE THREAD

**Issue by pritish-thub** [nestjs/nest#13013]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hono is a web framework with support out of the box for Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, Lagon, AWS Lambda, Lambda@Edge, and Node.js

### Describe the solution you'd like

Just switching the webframework to Hono, just like we can switch from Express to Fastify

### Teachability, documentation, adoption, migration strategy

The NestJS code remains the same only the backend framework should change

### What is the motivation / use case for changing the behavior?

Honi is extremely lightweight, fast and smaller in size as compared to Express and Fastify.

**Comment by jmcdo29** [comment]
Feel free to create and publish a `HonoAdapter` that can plug into the `NestFactory`. So long as it adheres to the `AbstractHttpAdapter`, it should be usable

**Comment by reslear** [comment]
any news?

**Comment by EdamAme-x** [comment]
> any news?

We are trying to work on this.

**Comment by shaaridev** [comment]
@reslear  @EdamAme-x @reslear 

You should probably check out this repo
 [deno-oak-nest](https://github.com/jiawei397/deno-oak-nest)
 Nestjs for Deno, support hono and oak

Personally I didn't have the time to test it , let me if it works.

**Comment by kiyasov** [comment]
3 days of painstaking work. It's done. 

P.s It remains to make file upload support for Graphql


https://github.com/kiyasov/platform-hono

**Comment by maxime-aubry** [comment]
> 3 days of painstaking work. It's done.
> 
> https://github.com/kiyasov/platform-hono

I beleive you use nodejs in this library.
Si it's not compatible with Bun, right ?
Thanks.

**Comment by kiyasov** [comment]
> I beleive you use nodejs in this library.
> Si it's not compatible with Bun, right ?
> Thanks.

It works with both nodejs and bun

**Comment by kamilmysliwiec** [comment]
There's really no compelling reason to choose Hono over Express or Fastify. The differences are minimal, and end-users won’t notice any difference in real-world applications (APIs with 1 "Hello world" route don't count).

Still, if someone wants to use Hono, creating an adapter should be straightforward. The one @kiyasov shared and linked above looks great
