### ISSUE TITLE
Add APP_LOGGER enhancer

### ISSUE THREAD

**Issue by nikrabaev** [nestjs/nest#13015]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a custom nestjs logger which I set as default like this:
```
const app = await NestFactory.create(AppModule, {
  bufferLogs: true,
});

const logger = app.select(LoggerModule).get(LoggerService);

app.useLogger(logger);
```
Unfortunately the app initialization errors are logged by the built-in logger because they are thrown at the `NestFactory.create(...)` call which goes before the `app.useLogger(...)` call.
I know it's possible to pass the custom logger's `LoggerService` instance as a `logger` option to the app factory call, but this way I can't benefit of the Nest's dependency injection within that custom `LoggerService`. 
Setting `abortOnError` to `false` doesn't make it any better. 

### Describe the solution you'd like

In the documentation I found that it's possible to register a global exception filter by registering a provider with key `APP_FILTER` within any module. `APP_FILTER` is one of the [multiple enhancers](https://github.com/nestjs/nest/blob/3f3199ccb4e9e5f8c313afd417adf54d0346d312/packages/core/constants.ts#L13-L28) supported by nest's core.

I propose to add a new `APP_LOGGER` enhancer which would allow developers to override the built-in logger during the app initialization while leveraging all the dependency injection capabilities.

### Teachability, documentation, adoption, migration strategy

Instead of using `app.setLogger(...)` it would be possible to apply the custom logger globally by registering the following provider within the custom logger module:
```
@Module({
  providers: [
    {
      provide: APP_LOGGER,
      useFactory: (configService: ConfigService) => ...,
      inject: [ConfigService],
    }
  ]
})
export MyLoggerModule {}
```

I understand that the module init logs are written before the module initialization begins, so by the time the `APP_LOGGER` provider is registered some logs might be already written. To handle this, the `bufferLogs: true` behaviour can be adjusted to stop the buffering as soon as the first `APP_LOGGER` provider is registered by some module.

### What is the motivation / use case for changing the behavior?

It should be possible to log the app initialization errors using the custom logger.
In my case it's important because I need these errors to be written to Sentry and also written to stdout as json along with the init logs which had been written before the error.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
