### ISSUE TITLE
Using Custom Transport Strategy to use camunda

### ISSUE THREAD

**Issue by malekAdeo** [nestjs/nest#13026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a project nestjs that using version 8.2.3 and nodejs 16 and I did upgrade to this version and now I have nestjs 10.3.0 and nodejs 20.10.0 so when I did this upgrade my configuration to connect to camunda doesn't work.
I'm using CustomTransportStrategy to subscripe to message of camunda 
My configuration:
`import {
    Server,
    CustomTransportStrategy,
    MessageHandler,
} from '@nestjs/microservices';
import {
    Inject,
    Injectable,
    Logger
} from '@nestjs/common';
import { Client } from 'camunda-external-task-client-js';

@Injectable()
export class ExternalTaskConnector extends Server
    implements CustomTransportStrategy {
    constructor(@Inject('CONNECTION_PROVIDER') private readonly client: Client) {
        super();
    }

    public listen(callback: () => void) {
        this.init();
        callback();
    }

    public close() {
        this.client.stop();
        Logger.log('External Task Client stopped', 'ExternalTaskConnector')
    }

    protected init(): void {
        this.client.start();

        Logger.log('External Task Client started', 'ExternalTaskConnector')

        const handlers = this.getHandlers();
        handlers.forEach((messageHandler: MessageHandler, key: string) => {
            let jsonKey = JSON.parse(key);
            this.client.subscribe(
                jsonKey.topic,
                jsonKey.options,
                ({ task, taskService }) => {
                    messageHandler(task, taskService);
                },
            );
        });
    }
}`

`@Global()
@Module({
  providers: [
    {
      provide: CONNECTION_PROVIDER,
      useFactory: async () => {
        return new Client({
          baseUrl: process.env.CAMUNDA_BASE_URL!,
          maxTasks: process.env.CAMUNDA_MAX_TASKS ? parseInt(process.env.CAMUNDA_MAX_TASKS) : 1,
          interval: process.env.CAMUNDA_INTERVAL ? parseInt(process.env.CAMUNDA_INTERVAL) : 300,

        });
      },
    },
    ...Object.values(providers),
  ],
  exports: Object.values(providers),
})
export class CamundaModule { }`

`  app.connectMicroservice<MicroserviceOptions>(
    {
      strategy: app.get(ExternalTaskConnector)
    }
  )`

When I tried to start the project the app crush and I had app.exit(1) but when I use @nestjs/microservices version 8.2.5 it works correctly 

### Expected behavior

the project must be start like when I use the version of nestjs 8.2.5

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Packages versions
    "@nestjs/axios": "^3.0.1",
    "@nestjs/common": "^10.3.0",
    "@nestjs/core": "^10.3.0",
    "@nestjs/microservices": "^10.3.0",
    "@nestjs/platform-express": "^10.3.0",
    "@nestjs/swagger": "^7.1.17",
    "@nestjs/terminus": "^10.2.0",
    "@receivit/common--clients": "^7.0.0",
    "@receivit/common--dtos": "^7.0.0",
    "@tsconfig/node20": "^20.1.2",

### Node.js version

20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
