### ISSUE TITLE
When I got the `@Inject (RQQUEST)` parameter from the injection`Service` in `Middleware`, but what I got was `undefined`.

### ISSUE THREAD

**Issue by SuperCodeCandy** [nestjs/nest#13043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, assuming I have `ServicesA` and `ServicesB`, they were originally interdependent. I used `forwardRef` to handle their dependency relationship, but due to subsequent iterations, `ServicesB` no longer depends on `ServicesA`. Therefore, `@Inject(forwardRef(() => ServicesA))` in `ServicesB` was removed, but the injection in `ServicesA` has not been removed yet, When I call the method in `ServicesA` in Middleware to get the request injected using `Inject(REQUEST)`, I get `undefined`,

My problem has been resolved now. After removing the dependency injected in `ServicesA`, it can work normally. I have a little question about the performance of this part.
I get `undefined` is this expected?
Is it because I mistakenly used 'forwardRef' that caused it?

### Minimum reproduction code

https://codesandbox.io/p/devbox/distracted-sun-t8ffm4?file=%2Fsrc%2Fmodule%2Ftest2%2Ftest2.services.ts%3A12%2C30

### Steps to reproduce

1. npm run start
2. Accessing localhost: 3000
    - On the console, output `===>undefined`
3. Canceling the comments in 'test2.services.ts', repeat the service, and accessing it again will result in the correct output.

### Expected behavior

I expect it to receive the `request` normally

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  }
```

### Node.js version

v18.18.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
You should never use `forwardRef` in combination with request-scoped providers. Check out some old issues to learn more on why is that
