### ISSUE TITLE
CPU intensive controller prevents AMQP connection from receiving heartbeat, hence connections gets closed.

### ISSUE THREAD

**Issue by ticmaidev** [nestjs/nest#13040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I'm using **RMQ** as transport and `@MessagePattern`: if controller method has a high CPU usage then AMQP closes connection and reports it as an empty error object:

![image](https://github.com/nestjs/nest/assets/128381407/5ce8fd3d-107f-42d0-85ba-1bdb65a7f5ec)
![image](https://github.com/nestjs/nest/assets/128381407/5ba70670-6f23-41b1-9bfb-83726b19d1da)

The whole microservice keeps working (including the heavy task). But somehow it will block hearbeats from being sent to AMQP connection.

### Minimum reproduction code

https://github.com/ticmaidev/amqplib-nest-heartbeat-issue

### Steps to reproduce

- set env variables according to .example.env
- run `yarn start:dev`
- connect to the microservice ('data_exporting')
- send the payload to the consumer ('createExporting');
- wait heartbeat timeout (5 seconds);
- error shows up (empty);

_note: setting socket option **heartbeatIntervalInSeconds** to a greater value will prevent the channel from closing, but it won't execute more than 1 task at a time (**prefetchCount: 5**)._

### Expected behavior

I'm expecting to run all **_prefetchCount_** message corresponding tasks in parallel. Those are heavy tasks so I'm expecting them to run in paralell. Also: if I lose connection, I should be able to easily check that on `{ err: {} }`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

amqplib (0.10.3)

### NestJS version

10.0.0

### Packages versions

```json
{
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/microservices": "^10.3.0",
    "@nestjs/platform-express": "^10.0.0",
    "amqp-connection-manager": "^4.1.14",
    "amqplib": "^0.10.3",
  }
```

### Node.js version

v18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the [amqplib](https://github.com/amqp-node/amqplib) repository
