### ISSUE TITLE
ModuleRef injection to injectable constructor fails during unit testing

### ISSUE THREAD

**Issue by tempoc** [nestjs/nest#13041]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

9.2.1 -> 9.3.10

### Describe the regression

A unit test written for n injectable that requires `ModuleRef` injected into the constructor fails at the injection stage with v9.3.10

### Input code

```ts
@Injectable()
export class AuditedCollectionServiceFactory {
  constructor(private readonly moduleRef: ModuleRef) {}
}

describe('injection', () => {
  it('should work', () => {

  const module = await Test.createTestingModule({
            providers: [
                AuditedCollectionServiceFactory,
            ],
        }).compile();

// Next statement fails
        factory = module.get<AuditedCollectionServiceFactory>(
            AuditedCollectionServiceFactory,
        );
    });
});
```

### Expected behavior

The Test module should be able to create an instance of the `AuditedCollectionServiceFactory` without any additional configuration if the only constructor parameter is a `ModuleRef`.

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment]
I just tested myself. Everything went fine so far:

![image](https://github.com/nestjs/nest/assets/13461315/c42691c1-fcfd-4e84-906a-21245dcd4980)

```ts
import { Test, TestingModule } from '@nestjs/testing';
import { ModuleRef } from '@nestjs/core';
import { INestApplication, Injectable } from '@nestjs/common';

@Injectable()
export class AuditedCollectionServiceFactory {
  constructor(private readonly moduleRef: ModuleRef) {}
}

describe('test', () => {
  let moduleFixture: TestingModule ;

  beforeEach(async () => {
     moduleFixture = await Test.createTestingModule({
      providers: [AuditedCollectionServiceFactory],
    }).compile();
  });

  it('should pass', async () => {
    const provider = moduleFixture.get(AuditedCollectionServiceFactory)
    expect(provider).toBeInstanceOf(AuditedCollectionServiceFactory)
  });
});
```

**Comment by tempoc** [comment]
Found more info. A transitive dependency was lingering at 9.2.1 for @nestjs/core in the project that was consuming my library. So the service imported 9.2.1 and the library was written on 9.3.10. This means that on some level there's a breaking change between the two, unless the direct injection was introduced as a feature on version 9.3.0.

Everything works fine when the consuming service updates its version of @nestjs/core to >=9.3.10
