### ISSUE TITLE
Using multiple CacheModules resolve to same cache manager in v10.3.0

### ISSUE THREAD

**Issue by drdreo** [nestjs/nest#13058]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

10.2.10 --> 10.3.0

### Describe the regression

The cache manager is shared between multiple cache modules since the upgrade on @nestjs/common@10.3.0 and @nestjs/core@10.3.0.
I have singled out these 2 dependencies, as latest @nestjs/cache-manager changes seem to be not causing this.

To verify caching aint working as expected run `npx nx test`

The cache modules can be found at `src/app/caches`. I created a cat-cache and a user-cache. They should be configured differently (ttl, max,..) and not share the same manager since cat and user IDs can overlap.

[In the provided repo](https://github.com/drdreo/nest-cache-bug/tree/master), there is also a [working branch](https://github.com/drdreo/nest-cache-bug/tree/working-branch).

### Minimum reproduction code

https://github.com/drdreo/nest-cache-bug

### Input code

Registering a feature cache module will share same cache manager, like:
```ts
@Module({
    imports: [CacheModule.register({ ttl: 60 * 10 * 1000, max: 1000 })],
    providers: [CatCacheService],
    exports: [CatCacheService]
})
export class CatCacheModule {}
```

### Expected behavior

Different cache modules can be configured differently. I would expect that the cache manager is not shared between the two modules and one cache does not include keys and values from others.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/cache-manager/issues/203
