### ISSUE TITLE
NestJS doesn't error when provider's dependencies haven't been resolved

### ISSUE THREAD

**Issue by snigdha920** [nestjs/nest#13059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We have the case where:

1. We create a service without an @Injectable decorator on the service class, let's call this `BookService`
2. We include the service in the providers array of a module `BookModule`
3. We use the service in a controller `BookController`

The `BookService` injects another service `AuthorService`, but `bookService.authorService` is undefined and nest does not error out - no errors on the `BookService` or `BookController` (which is using the service)

In a unit test, importing the `BookModule` and then doing 

```typescript
service = module.get<BookService>(BookService)
```

`service` is `defined`. but `bookService.authorService` is `undefined`, because it was not injected correctly.

### Minimum reproduction code

https://github.com/snigdha920/nestjs-di

## Steps to reproduce

1. Install dependencies with `pnpm i`
2. Run `pnpm start:dev` in the root
3. No errors in the console, but we see the message from the `BookService` constructor: `BookService.authorService is undefined`
4. In the test `book.service.spec.ts`, we successfully get the `BookService` from the module context, but `bookService.authorService` is `undefined`. Run the test by `pnpm test`

### Expected behavior

This behaviour is weird, what I expect is:

Since `BookService` is included in the providers array, nest should throw an error can't resolve dependancies of `BookService` 

OR

Since `BookService` is being used by the `BookController`, the `BookController` should throw an error that it couldn't resolve the `BookService` dependency since the dependencies of `BookService` itself hasn't been resolved

OR

The unit test to should error saying it could not find the provider `BookService` in the module context since `BookService` hasn't been initialised properly because it's dependencies weren't resolved

I basically want some error at compile time that we're using a service in a controller whose dependencies have not been resolved. This service is also included in the `providers` array, so there should be some error at compile time. 

Is there a unit test I can write that catches this? Instead of having to manually check for every dependency of a service in a unit test (which I cannot do if `BookService.authorService` was a private field)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "10.3.0",
    "@nestjs/core": "10.3.0",
    "@nestjs/platform-express": "10.3.0"
  },
```

### Node.js version

20.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
> is undefined and nest does not error out

I believe that this is a limitation of typescript, and could be fixed using a linter rule

We can add classes without `@Injectable()` to the `providers` array, as long as they won't inject anything or if you're using the `@Inject()` instead

There is no way to nestjs to know if you missed the `@Injectable()` or not

**Comment by jmcdo29** [comment]
The `@Injectable()` decorator is a way to force Typescript to emit the constructor metadata for what parameters are there. If the class doesn't have parameters, you _technically_ don't need the decorator, so adding the class without the decorator to the providers is perfectly valid. Regardless if the class is decorated, it does still need to be added to the providers array so nest can be aware of the existence of the class and add it to the provider tokens map

**Comment by snigdha920** [comment]
Okay, also read https://github.com/nestjs/docs.nestjs.com/pull/2481/files. So nest can't possibly resolve dependencies of a class (with a non-empty constructor) in the providers array without at least a @Inject / @Injectable decorator because there won't be enough metadata to do so. Is that correct?

**Comment by micalevisk** [comment]
@snigdha920 exactly

and nestjs can't tell if a class has a non-empty constructor if the class has no decorators. That's why I believe this is a limitation we can't fix on nestjs side

**Comment by KostyaTretyak** [comment]
Note that the `AuthorService` is re-exported from the `AuthorModule` and additionally declared in the `BookModule`. Which is excessive. If you comment out the `BookService` declaration in the `BookModule` class, NestJS will throw the expected error:

```ts
import { Module } from '@nestjs/common';
import { BookService } from './book.service';
import { BookController } from './book.controller';
import { AuthorModule } from '../author/author.module';

@Module({
  imports: [AuthorModule],
  controllers: [BookController],
  // providers: [BookService],
})
export class BookModule {}
```

But if you comment out the `AuthorService` re-export from the `AuthorModule` module, NestJS will not throw the expected error:

```ts
import { Module } from '@nestjs/common';
import { BookService } from './book.service';
import { BookController } from './book.controller';
import { AuthorModule } from '../author/author.module';

@Module({
  // imports: [AuthorModule],
  controllers: [BookController],
  providers: [BookService],
})
export class BookModule {}
```
It seems that NestJS only does the validation related to parameter resolution when exporting providers. This can probably be called inconsistent behavior on the part of NestJS.
