### ISSUE TITLE
The terser plug-in was configured using webpack and then failed to build

### ISSUE THREAD

**Issue by lamorttu** [nestjs/nest#13054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

build error
![image](https://github.com/nestjs/nest/assets/21117602/327b8cc5-d169-4843-93a6-7cd0880a77ca)

### Minimum reproduction code

null

### Steps to reproduce

![image](https://github.com/nestjs/nest/assets/21117602/96e97927-bd75-4928-b06b-38a2d724e2b0)
![image](https://github.com/nestjs/nest/assets/21117602/92aa7671-851f-4d36-abe7-69e2c664a1bf)
![image](https://github.com/nestjs/nest/assets/21117602/1f92e8ae-99eb-460a-8a25-775900aa1a8f)

yarn build:genomics-backend

### Expected behavior

Run the nest build successfully

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/elasticsearch": "^10.0.1",
    "@nestjs/jwt": "^10.1.1",
    "@nestjs/microservices": "^10.2.2",
    "@nestjs/mongoose": "^10.0.1",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/schedule": "^4.0.0",
    "@nestjs/swagger": "^7.1.4",
    "@nestjs/typeorm": "^10.0.0",
```

### Node.js version

18.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
