### ISSUE TITLE
Refer to the official website to configure terser-webpack-plugin. It does not seem to take effect

### ISSUE THREAD

**Issue by lamorttu** [nestjs/nest#13055]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

![image](https://github.com/nestjs/nest/assets/21117602/bf885eec-fec3-45b3-bdd9-151f0e247c41)
 install the terser-webpack-plugin package and override its configuration
yarn build:genomics-backend
![image](https://github.com/nestjs/nest/assets/21117602/f5ab8e50-6e29-48ea-ae19-096c910c4d1d)

### Describe the solution you'd like

![image](https://github.com/nestjs/nest/assets/21117602/b847b658-cead-4f6d-99d5-88efa07d2069)
TerserPlugin is not effective and does not have the mangle and compress effect

### Teachability, documentation, adoption, migration strategy

nothing

### What is the motivation / use case for changing the behavior?

![image](https://github.com/nestjs/nest/assets/21117602/1e691550-a286-41ca-996a-28b1e11d0baa)
The webpack configuration takes effect in monorepo

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
