### ISSUE TITLE
Cannot deprecate GraphQL field in auto generated schema (code first)

### ISSUE THREAD

**Issue by Oleshkooo** [nestjs/nest#13060]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

`deprecationReason` property in InputType decodarot does not deprecate field in GraphQL schema

### Minimum reproduction code

https://github.com/Oleshkooo/nestjs-field-deprecation-issue

### Steps to reproduce

Create new nest project
```console
nest new .
```

Install packages
```console
npm i @nestjs/graphql @nestjs/apollo @apollo/server graphql
```

Edit app.module.ts
```ts
import { ApolloServerPluginLandingPageLocalDefault } from '@apollo/server/plugin/landingPage/default';
import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo';
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { join } from 'path';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ExampleModule } from './example/example.module';

@Module({
  imports: [
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      path: '/graphql',
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
      sortSchema: true,
      playground: false,
      plugins: [ApolloServerPluginLandingPageLocalDefault()],
    }),
    ExampleModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

Generate new module
```console
nest g res
example
GraphQL (code first)
y
```

Edit src/example/dto/create-example.input.ts
```ts
import { InputType, Int, Field } from '@nestjs/graphql';

@InputType()
export class CreateExampleInput {
  @Field(() => Int, {
    description: 'Example field (placeholder)',
    deprecationReason: 'This field is deprecated',
  })
  exampleField: number;
}
```

Run app
```console
npm run start:dev
```

Check src/schema.gql file (no deprecated directive)
```gql
input CreateExampleInput {
  """Example field (placeholder)"""
  exampleField: Int!
}
```

### Expected behavior

`exampleField` is deprecated in GraphQL schema

```gql
input CreateExampleInput {
  """Example field (placeholder)"""
  exampleField: Int! @deprecated(reason: "This field is deprecated")
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

10.1.18 (nest -v)

### Packages versions

```json
{
  "name": "nest-issue",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@apollo/server": "^4.10.0",
    "@nestjs/apollo": "^12.0.11",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.0.11",
    "@nestjs/platform-express": "^10.0.0",
    "graphql": "^16.8.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

20.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

From the docs:

WARNING
Directives applied through the @Directive() decorator will not be reflected in the generated schema definition file.

So I didn't use @Directive()

OS: MacOS
Version: Sonoma 14.1.1
Node.js version: 20.11.0
npm version: 10.2.4
NestJS version: 10.1.18 (`nest -v`)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Oleshkooo** [comment]
Not sure

**Comment by Deniks** [comment]
According to this, you cannot deprecate Input fields - https://github.com/graphql/graphql-spec/issues/197

**Comment by PlayAnyData** [comment]
@kamilmysliwiec @Deniks Could you state for my understanding why this has been closed? As far as I understand the linked thread, this PR has been merged: https://github.com/graphql/graphql-spec/pull/525 Therefore, deprecation of input types should be possible. Otherwise, I am getting something totally wrong.

I have checked today against the latest version in conjunction with this fix: https://github.com/nestjs/graphql/pull/3157 (Adding deprecation to Args). However, the code-first approach (using InputType as shown above as well), still does not support this.
