### ISSUE TITLE
ConfigurableModuleBuilder "alwaysTransient: false" (@default) doesn't work

### ISSUE THREAD

**Issue by StiliyanKushev** [nestjs/nest#13076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The console log is printed only once, unless alwaysTransient is set to true.

```ts
// my-custom-module.ts

import { Inject, Module } from '@nestjs/common';

import { ConfigurableModuleBuilder } from '@nestjs/common';

export const {
  ConfigurableModuleClass,
  MODULE_OPTIONS_TOKEN: MY_CUSTOM_MODULE_OPTIONS,
} = new ConfigurableModuleBuilder<{
  baseUrl?: string;
}>().build();

@Module({})
export class MyCustomModule extends ConfigurableModuleClass {
  constructor(
    @Inject(MY_CUSTOM_MODULE_OPTIONS)
    private readonly options,
  ) {
    console.log(options);
    super();
  }
}

// app.module.ts
@Module({
  imports: [
    MyCustomModule.register({ baseUrl: 'https://google.com' }),
    MyCustomModule.register({ baseUrl: 'https://google1.com' }),
    MyCustomModule.register({ baseUrl: 'https://google2.com' }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

```

### Expected behavior

Expecting the console log to run 3 times because the options are different in the providers array (as stated in the official nestjs advanced concepts course).

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Packages versions

```bash
[System Information]
OS Version     : Linux 6.1.69-1-MANJARO
NodeJS Version : v20.8.0
NPM Version    : 10.1.0 

[Nest CLI]
Nest CLI Version : 10.3.0 

[Nest Platform Information]
platform-express version : 10.3.0
mapped-types version     : 2.0.4
schematics version       : 10.1.0
testing version          : 10.3.0
common version           : 10.3.0
core version             : 10.3.0
cli version              : 10.3.0

[Warnings]
The following packages are not in the same minor version
This could lead to runtime errors
* Under version 10.3
- @nestjs/platform-express 10.3.0
- @nestjs/common 10.3.0
- @nestjs/core 10.3.0
* Under version 10.1
- @nestjs/schematics 10.1.0
```

### Node.js version

v20.8.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
isn't this pretty much what the docs of `alwaysTransient` says here:

https://github.com/nestjs/nest/blob/3141a1e707e7913149dea8a1675ce92c29e1db6c/packages/common/module-utils/configurable-module.builder.ts#L35-L42

**Comment by StiliyanKushev** [comment]
Well, here's the thing though, the expected behavior I described is not really documented, but is clearly mentioned in one of the official nestjs courses. What I'm saying is that, `alwaysTransient` set to `true` actually works as expected, but when set to `false` (by default), it supposedly (as shown in the course) should still act as if `alwaysTransient` is set to `true` for providers that are the same but have different options passed (such as in my example), due to their "internal hash" being different.

**Comment by StiliyanKushev** [comment]
The version used in the course seems to be `v7.1.2`

**Comment by micalevisk** [comment]
@StiliyanKushev yeah, got you

please feel free to improve the docs at https://github.com/nestjs/docs.nestjs.com

**Comment by micalevisk** [comment]
> Just to recap, the course suggests that the above logs should execute 3 times 

are you sure?

at 8:25
![image](https://github.com/nestjs/nest/assets/13461315/918b5d93-f4d5-4b7f-99b6-422fbe8ff3ac)

![image](https://github.com/nestjs/nest/assets/13461315/c31e0ada-58b3-42b3-a036-a7e4f2adeb68)

**Comment by StiliyanKushev** [comment]
That's the correct video you're referencing, but it's the wrong timestamp.
I can provide the screenshots in a sec.

**Comment by StiliyanKushev** [comment]
at 9:08
![image](https://github.com/nestjs/nest/assets/24881376/5eec155e-b79b-4b14-a935-b11c0374854a)
![image](https://github.com/nestjs/nest/assets/24881376/18523cc3-7798-4398-a3a5-83e1470b2a65)

**Comment by StiliyanKushev** [comment]
Okay, I'll make a repo in a minute. I can also test with different nest versions and will report up until what version it works as expected.

**Comment by micalevisk** [comment]
check out the https://github.com/nestjs/nest/releases 

I don't think that that behavior have changed but I can be wrong

**Comment by StiliyanKushev** [comment]
Yeah, already searched in the releases, wasn't mentioned. (Another reason I suspect this to be a bug).

**Comment by StiliyanKushev** [comment]
[Here](https://github.com/StiliyanKushev/nestjs-bug-report-reproduction/tree/master) you go, hope that's enough :)

**Comment by StiliyanKushev** [comment]
Notice that it works as expected if I downgrade to version 9 for example.

![image](https://github.com/nestjs/nest/assets/24881376/daa8eaf2-017d-454d-b5bd-49b84fac4695)

**Comment by micalevisk** [comment]
seems to be a regression introduced on `@nestjs/common@10.3.0`

**Comment by StiliyanKushev** [comment]
Actually, seems to be a semi-recent bug in the latest version of `@nestjs/common@10.3.0`.

![image](https://github.com/nestjs/nest/assets/24881376/1cb41865-487a-4560-8cbe-24d8042cdce9)

**Comment by H4ad** [comment]
@micalevisk Yeah, this is a bug introduced by my PR, `alwaysTransient` works because of: https://github.com/nestjs/nest/pull/12753/files#diff-22f1ab07f43abbd45f270de55b6cd35da90c02fe92cee99f67d51a37b85002c8R209-R220 which makes the module unique.

That piece of code worked before because we used those objects to differentiate each module, if he use the async version, then it will have the same issue.

We can basically revert the change for that module only, the easiest/quickest fix, the other changes we don't need to revert.

We can also go back to the conversation started at https://github.com/nestjs/nest/pull/12898, this issue could be fixed using that feature.

**Comment by StiliyanKushev** [comment]
Great! Additionally I'd say this can be better documented for future reference as to me it seems to be a somewhat crucial feature in certain scenarios.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/13083
