### ISSUE TITLE
Add RabbitMQ connection options

### ISSUE THREAD

**Issue by tetofonta** [nestjs/nest#13071]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The RabbitMQ microservice client allows only the property relative to socket options to the underlying ampqlib as per line [client/client-rmq.ts:136](https://github.com/nestjs/nest/blob/d6a6f30165eb021797f6162e5bf7f4567b0189fa/packages/microservices/client/client-rmq.ts#L136). There is no way to pass additional connection options like ssl certificates and client certificates or to specify a different authentication method like EXTERNAL. 

### Describe the solution you'd like

Add a key to RmqOptions or substitue RmqOptions#socketOptions with the full options object

### Teachability, documentation, adoption, migration strategy

External Authentication method: [Here](https://www.rabbitmq.com/authentication.html)
amqplib ssl example passing certificates to the connect handler: [Here](https://github.com/amqp-node/amqplib/blob/bbe579e467866a40ff1c0ae2428c416111340364/examples/ssl.js#L37)
amqplib ssl EXTERNAL auth example: [Here](https://github.com/amqp-node/amqplib/blob/bbe579e467866a40ff1c0ae2428c416111340364/examples/ssl.js#L55)
ampqlib EXTERNAL auth method issue: [Here](https://github.com/amqp-node/amqplib/issues/105)

### What is the motivation / use case for changing the behavior?

Impossibility of integrating RabbitMQ inside an existing microservice architecture because RabbitMQ is configured with mTLS authentication.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Deniks** [comment]
Hey, i have created PR for this issue.

**Comment by kamilmysliwiec** [comment]
let's track this here https://github.com/nestjs/nest/pull/13105
