### ISSUE TITLE
Dependency Injection does not work for .tsx files

### ISSUE THREAD

**Issue by PurpleTape** [nestjs/nest#13074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you try to run a project with `tsx` files that contains some Dependency Injection, an error will occur:
```
[Nest] 60380  - 01/21/2024, 7:36:17 PM     LOG [InjectorLogger] Nest encountered an undefined dependency. This may be due to a circular import or a missing dependency declaration.
[Nest] 60380  - 01/21/2024, 7:36:17 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AppServiceWithDep (?). Please make sure that the argument dependency at index [0] is available in the AppModule context.
```

However, if the `tsx` file has no dependencies, then the project will run successfully

When building a project, the following behavior is observed:

The class in the `ts` file will be compiled in something like this:

```js
class AppController {
    getHello() {
        return this.appService.getHello();
    }
    constructor(appService){
        _define_property(this, "appService", void 0);
        this.appService = appService;
    }
}
```

When will the code for the `tsx` be like this:
```js
class AppServiceWithDep {
    log() {
        console.log(vueExports.createVNode("b", null, [
            this.appService.getHello()
        ]));
    }
    constructor(appService){
        // <-- There is no dependency injection
        this.appService = appService;
    }
}
```

### Minimum reproduction code

https://github.com/PurpleTape/nestjs-di-issue

### Steps to reproduce

1. Clone project
2. Start with `npm run dev` - no errors
3. Go to `./src/app.module.ts` and add `AppServiceWithDep` provider
4. Start with `npm run dev` - error

Building - `npm run build`

### Expected behavior

Dependency injection works correctly for `tsx` files

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Packages versions

```json

```

### Node.js version

v20.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by PurpleTape** [comment]
I figured it out, it was necessary to use plugin `@babel/plugin-proposal-decorators`, not `@babel/plugin-syntax-decorators`

**Comment by PurpleTape** [comment]
Still, the problem is relevant. In the updated version of the repository, the project is now running, but the injected dependency has `undefined`

Can you please tell me what this might be related to?

I am grateful in advance!

**Comment by micalevisk** [comment]
please fix the repo so we can run `npm install` with no errors

![image](https://github.com/nestjs/nest/assets/13461315/db82fb39-2466-4f03-8123-2cafe2527d29)

**Comment by PurpleTape** [comment]
In the final, the problem is solved with https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata
