### ISSUE TITLE
HttpsOptions doesn't have SecureOptions

### ISSUE THREAD

**Issue by tilak-puli** [nestjs/nest#13070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

NestJs create app doesn't have SecureOptions(which is present in HttpsOptions)

### Minimum reproduction code

https://www.reddit.com/r/node/comments/n7s3km/nestjs_how_to_restrict_tls_cipher_suite/

### Steps to reproduce

Nil

### Expected behavior

I am trying to disable tlsv1.0 and v1.1 but I don't see SecureOptions in HttpsOptions. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.3

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13075
