### ISSUE TITLE
KafkaJS typing mismatch

### ISSUE THREAD

**Issue by edeesis** [nestjs/nest#13077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/nestjs/nest/assets/1738038/2427dbea-5b41-4526-bc95-0477a25c7cdc)

### Minimum reproduction code

https://github.com/edeesis/kafkajs-nest

### Steps to reproduce

Attempt to re-use the KafkaJS KafkaConfig typing in the Nest MicroserviceOptions. You'll get a typescript error as screenshotted above.

```typescript
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { KafkaConfig } from 'kafkajs';
import { MicroserviceOptions, Transport } from '@nestjs/microservices';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const config: KafkaConfig = {
    clientId: 'client-id',
    brokers: process.env.KAFKA_BROKERS.split(','),
  };
  await app.connectMicroservice<MicroserviceOptions>({
    transport: Transport.KAFKA,
    options: {
      client: config,
    },
  });
  await app.listen(3000);
}

```

### Expected behavior

Typings should match.

I'm also curious why there's a need for separate typings, rather than using the typings exported from kafkajs.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.x

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^10.3.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.3.0",,
    "@nestjs/microservices": "^10.3.0",
    "kafkajs": "^2.2.4",
  }
}
```
Change was done in [kafkajs 2.2.1](https://github.com/tulios/kafkajs/releases/tag/v2.2.1)

### Node.js version

20.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
> I'm also curious why there's a need for separate typings, rather than using the typings exported from kafkajs.

peer dependency & strictLibCheck = true -> TS errors 

Would you like to create a PR with updated types?

**Comment by edeesis** [comment]
@kamilmysliwiec Done, thanks!

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/13084
