### ISSUE TITLE
Could not resolve dependency for reflect-metadata

### ISSUE THREAD

**Issue by mateuszzastawny** [nestjs/nest#13082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
npm ERR! Could not resolve dependency:
npm ERR! peer reflect-metadata@"^0.1.12" from @nestjs/common@10.3.0
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"10.3.0" from the root project
npm ERR!   peer @nestjs/common@"^9.0.0 || ^10.0.0" from @nestjs/swagger@7.2.0
npm ERR!   node_modules/@nestjs/swagger
npm ERR!     @nestjs/swagger@"7.2.0" from the root project
```

Could not properly resolve dependencies for new reflect-metadata.

### Minimum reproduction code

https://github.com/mateuszzastawny/nestjs-common-issue

### Steps to reproduce

1. `npm install reflect-metadata@0.2.1`
2. `npm install @nestjs/common@10.3.0`

### Expected behavior

Installing dependencies without errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/bull": "10.0.1",
    "@nestjs/cache-manager": "2.2.0",
    "@nestjs/common": "10.3.0",
    "@nestjs/core": "10.3.0",
    "@nestjs/microservices": "10.3.0",
    "@nestjs/mongoose": "10.0.2",
    "@nestjs/platform-express": "10.3.0",
    "@nestjs/swagger": "7.2.0",
    "reflect-metadata": "0.2.1"
  }
}
```

### Node.js version

20.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
as the error says, you should use `reflect-metadata` 0.1.x, not 0.2.x

not sure when we can start supporting the latest version of `reflect-metadata`
