### ISSUE TITLE
Milvus Support

### ISSUE THREAD

**Issue by arrrrny** [nestjs/nest#13081]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am experimenting using Milvus vector database for similarity search on my product database.

### Describe the solution you'd like

It would be nice to have native NestJS Milvus connector.

### Teachability, documentation, adoption, migration strategy

Users can connect to Milvus database running locally or on cloud.

### What is the motivation / use case for changing the behavior?

Graph databases are getting popular and responding to demands of vector represantation of data specificifically on AI related projects.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
