### ISSUE TITLE
Middleware doesn't get called if more than one version is specified in `version`

### ISSUE THREAD

**Issue by 1valdis** [nestjs/nest#13093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I create a middleware for all routes in my application, as such:
```ts
export class AppModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(VersioningMiddleware).forRoutes({
      path: '*',
      version: ['1', '2'],
      method: RequestMethod.ALL,
    });
  }
}
```
As soon as there is more than one item in `version` array, the middleware does not get called.

### Minimum reproduction code

Please see "Steps to reproduce" for full minimum reproduction code

### Steps to reproduce

```ts
// main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module.js';
import { VersioningType } from '@nestjs/common';
import { NestExpressApplication } from '@nestjs/platform-express';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);

  app.enableVersioning({
    defaultVersion: ['3'],
    type: VersioningType.URI,
  });
  await app.listen(3000);
}
bootstrap();


// app.module.ts
import { VersioningMiddleware } from './versioning.js';
import { AppController } from './app.controller.js';

@Module({
  imports: [],
  controllers: [AppController],
})
export class AppModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(VersioningMiddleware).forRoutes({
      path: '*',
      version: ['1'],
      method: RequestMethod.ALL,
    });
  }
}


// app.controller.ts
@Controller()
export class AppController {
  @Get('hello')
  async hello() {
    return { hello: 'world' };
  }
}


// versioning.ts
export class VersioningMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: (error?: any) => void) {
    res.status(452).end();
  }
}
```

Run the project and call a route `/v1/hello`. You should get the http 452 empty response, produced by the middleware.

Now, change the version array in `forRoutes` from `version: ['1']` to `version: ['1', '2']`. Calling the same route now results in default NestJS Not Found error. Middleware does not get called.

### Expected behavior

The middleware should be called for `/v1/hello`, as well as for `/v2/hello`, resulting in status 452 empty response. `/v3/hello` should return the `{ "hello": "world" }` from the controller.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.1

### Packages versions

```
common version           : 10.3.1
core version             : 10.3.1
```

### Node.js version

20.9.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by 1valdis** [comment]
Workaround:
```ts
export class AppModule {
  configure(consumer: MiddlewareConsumer) {
    ['1', '2'].forEach(version => consumer.apply(VersioningMiddleware).forRoutes({
      path: '*',
      version,
      method: RequestMethod.ALL,
    }));
  }
}
```
But I'd rather not 🥲

**Comment by micalevisk** [comment]
from what I tested, this is the behavior since v9.0.0 of `@nestjs/core`. But looks buggy to me

I notice that, in your example, the following line is resulting in the `[ "/v2,1/*" ]`:

https://github.com/nestjs/nest/blob/8cfa85407218d20022e7d421b8de8dd08d656c63/packages/core/middleware/route-info-path-extractor.ts#L43

because of this `.toString()`:

https://github.com/nestjs/nest/blob/8cfa85407218d20022e7d421b8de8dd08d656c63/packages/core/middleware/route-info-path-extractor.ts#L85

Might be related with that, somehow :thinking:

**Comment by kamilmysliwiec** [comment]
🤔 @micalevisk would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13193
