### ISSUE TITLE
 WebSocket response not received when returning a json object

### ISSUE THREAD

**Issue by achrafelkhnissi** [nestjs/nest#13099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

I am currently working on a project where I need to implement a chat feature. I observed that when I send a JSON object back to the client, the client does not receive it; instead, the client only receives the data as a string from the server.

I attempted the same approach using the socket.io package, and it works as expected. However, this behavior only occurs in NestJS.

Here is a simple socket.io server where the server sends data to the client, and the client successfully receives it:

```javascript
const httpServer = require("http").createServer();
const io = require("socket.io")(httpServer, {
  cors: true,
});

io.on("connection", (socket) => {
  socket.on("string", (data, callback) => {
    callback("string sent");
  });

  socket.on("json", (data, callback) => {
    callback({ message: "json sent" });
  });
});

httpServer.listen(3002);
```

And here is a simplified gateway in NestJS where the client only receives data when returned as a string but not in JSON format:
```typescript
import {
  SubscribeMessage,
  WebSocketGateway,
  WsResponse,
} from '@nestjs/websockets';

@WebSocketGateway({
  cors: true,
})
export class ChatGateway {
  @SubscribeMessage('string')
  handleMessage(): string {
    return 'string sent';
  }

  @SubscribeMessage('json')
  handleObject(): WsResponse<string> {
    return {
      event: 'json',
      data: 'json sent',
    };
  }
}
```

Lastly, a simple client for testing:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Socket.io Client</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.3.1/socket.io.js"></script>
  </head>
  <body>
    <h1>Socket.io Client</h1>

    <script>
      // Connect to the socket.io server
      const socket = io("http://localhost:3002");

      // 1. Receive a string from the server
      socket.emit("string", "Hello, server!", (data) => {
        console.log("Server response:", data);
      });

      // 2. Receive an object from the server
      socket.emit("json", "Hello, server!", (data) => {
        console.log("Server response:", data);
      });
    </script>
  </body>
</html>
```

### Minimum reproduction code

https://github.com/achrafelkhnissi/nestjs-socket-issue

### Expected behavior

it should print both
- `string sent`
- `json sent`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Node.js version

20.6.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
