### ISSUE TITLE
Nested routes in NestJS are confused with parameters

### ISSUE THREAD

**Issue by Niko-R-Esla** [nestjs/nest#13094]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am trying to implement a NestJS API with the recommended REST API structure, where I am facing a problem with nested routes. Let's say we have school and class modules. But each of these modules have also corresponding type modules. School types can be elementary, high school etc. Class types can be seminar, lecture, lab course etc. Therefore, I have 4 modules (school, class, school types and class types). According to [this](https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/), I should use nested routes for more clarity on related resources. Therefore I want to have the following routes:

### Describe the solution you'd like

> /school(/:id) // to get all schools or school by id
> /school/:id/type // to get the type of school by id
> /school/type // to get all school types
> /school/type(/:id) // to get school types or school type by id
> /class(/:id) // to get all classes or class by id
> /class/:id/type // to get the type of class by id
> /class/type // to get all class types
> /class/type(/:id) // to get class types or class type by id

### Teachability, documentation, adoption, migration strategy

To keep my code tidy, I have subfolders for school-type and class-type modules to keep things tidy. As docs suggest, I am using [router-module](https://docs.nestjs.com/recipes/router-module):

```
imports: [... SchoolModule, RouterModule.register([{
    path: 'school', 
    module: SchoolModule, 
    children: [
      {
        path: 'type',
        module: SchoolTypeModule
      }
    ]
  },
  {
    path: 'class', 
    module: ClassModule, 
    children: [
      {
        path: 'type',
        module: ClassTypeModule
      }
    ]
  }]), 

```
When running NestJS, logs suggest that the desired routing is in place. Shown for school only:

> LOG [RouterExplorer] Mapped {/api/school/:id, GET} route +0ms
> LOG [RouterExplorer] Mapped {/api/school, GET} route +1ms
> LOG [RoutesResolver] SchoolTypeController {/api/school/type}: +0ms
> LOG [RouterExplorer] Mapped {/api/school/type/:id, GET} route +1ms
> LOG [RouterExplorer] Mapped {/api/school/type, GET} route +1ms
> LOG [NestApplication] Nest application successfully started +6ms

The problem is that when I try to access all school types, api/school/type routes to api/school/:id I wonder, what I am missing. I know that static routes need to come before the dynamic ones but school/type is whole different submodule in it's own controller.

### What is the motivation / use case for changing the behavior?

My motivation for this feature request is to organize my API, so that I can use endpoints related to their parent endpoints. As mentioned above, this is a recommended design. I had this issue discussed on discord. Instead of having `school-type` and `class-type`, it is much more elegant to have `school/type` and `class/type`. I was not able to find any related documentation regarding this issue, except for #255, but I am not sure if this is answering this problem. If this is related to a missing documentation, I would be happy to contribute.

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
