### ISSUE TITLE
@Body transform issue: The `metatype` property of the 2nd Arg to ValidationPipe.transform(v, metadata) is `undefined` during jest e2e `supertest` run.

### ISSUE THREAD

**Issue by m-fire** [nestjs/nest#13108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## 1. Typical app runs or standalone E2E `supertest` situations:
![image](https://github.com/nestjs/nest/assets/58259968/6759a2b7-d1d1-4093-84d4-e47f0929a5c8)

## 2-1. Nested request API scenario testing situations:
![image](https://github.com/nestjs/nest/assets/58259968/faa081fd-715a-4dc5-ab40-6ecec11c4e50)

## 2-2. ValidationPipe.transform Status:
![image](https://github.com/nestjs/nest/assets/58259968/7b4ebe85-2d3a-4d61-bd4f-014762cb2bf1)

### Minimum reproduction code

1. [CodeSandbox](https://codesandbox.io/p/github/m-fire/not-transform-dto-in-validation-pipe/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clryclct80006356ljat1zxn7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clryclct70002356lr0kd5d9e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clryclct70004356lcg3qt8ka%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clryclct70005356lrw9aoydq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clryclct70002356lr0kd5d9e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clryclct70001356la95n6ygy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.eslintrc.js%2522%257D%255D%252C%2522id%2522%253A%2522clryclct70002356lr0kd5d9e%2522%252C%2522activeTabId%2522%253A%2522clryclct70001356la95n6ygy%2522%257D%252C%2522clryclct70005356lrw9aoydq%2522%253A%257B%2522id%2522%253A%2522clryclct70005356lrw9aoydq%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clryclct70004356lcg3qt8ka%2522%253A%257B%2522id%2522%253A%2522clryclct70004356lcg3qt8ka%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clryclct70003356lqivy14qh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clryct3mc006ee8iygl3lebi4%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clrycn5q1006p356l7zsyeiht%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clryclct70003356lqivy14qh%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)
2. [GitHub repository](https://github.com/m-fire/not-transform-dto-in-validation-pipe.git)

### Steps to reproduce

1. Run `npm run test:e2e`, check the result: success2, failure3
2. DTO transform success tests. path: `test/module/auth/feature`
   - /sign-in-user.api.test.ts
   - /sign-up-user.api.test.ts
3. Failed tests. path: `test/module/board/feature`
   - /register-board.api.test.ts
   - /register-comment.api.test.ts
   - /get-comment-list.api.test.ts
4. debug the `request` method in `src/module/auth/feature/sign-in-user.api.ts` for each test
5. the `undefined` check in the title should be checked in the `ValidationPipe.transform()` method.

### Expected behavior

ValidationPipe should have no problem converting DTOs through `@Body`. It's too unreliable.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [x] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.1

### Packages versions

```

### Node.js version

20.11.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

[System Information]
OS Version     : Windows 10.0.22631
NodeJS Version : v20.11.0
NPM Version    : 9.6.7 

[Nest CLI]
Nest CLI Version : 10.3.0

[Nest Platform Information]
platform-express version : 10.3.1
mapped-types version     : 2.0.4
serve-static version     : 4.0.0
schematics version       : 10.1.0
passport version         : 10.0.3
typeorm version          : 10.0.1
testing version          : 10.3.1
common version           : 10.3.1
config version           : 3.1.1
core version             : 10.3.1
jwt version              : 10.2.0
cli version              : 10.3.0

[Warnings]
The following packages are not in the same minor version
This could lead to runtime errors
* Under version 10.3
- @nestjs/platform-express 10.3.1
- @nestjs/common 10.3.1
- @nestjs/core 10.3.1
* Under version 10.1
- @nestjs/schematics 10.1.0

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by m-fire** [comment]
@micalevisk May I request a review? I've updated the minimal reproduction comments and reproduction procedure above, and I've posted sample code as you suggested - it's a minimal scenario test, so there's a lot of source code.

**Comment by m-fire** [comment]
@micalevisk I think this issue is related to the import/export behavior of Typescript. What do you think? I think it's right, it suddenly started working again 😑.

**Comment by micalevisk** [comment]
I've no ideia :thinking:

**Comment by m-fire** [comment]
This is the second time this has happened to me.

### before
: The `Request` was placed inside the `auth` module outside the Api class.
`import { AuthToken, SignInUserRequest } from '@src-module/auth/feature'`

### after
: Located in the same folder as the API class
`import { SignInUserRequest } from './sign-in-user.request'`

**Comment by m-fire** [comment]
We'll commit the rest of the code to the repository to reflect this, so take a look when you need to.

**Comment by m-fire** [comment]
I'll just reopen it for now.
because it's impossible to reproduce what happened😑. I don't know how it was fixed.

**Comment by kamilmysliwiec** [comment]
I'm sure it's just an import/export issue, possibly caused by barrel files (index.ts) introducing a cyclic import in your code, leading to TS metadata being undefined in a specific context
