### ISSUE TITLE
Options property inboxPrefix not implemented in ClientNats

### ISSUE THREAD

**Issue by leandrogenas** [nestjs/nest#13150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The message is not being published with the set inbox prefix

### Minimum reproduction code

https://github.com/n-a

### Steps to reproduce

1.  Publish any message to a Nats server with `inboxPrefix` option defined

_No response_

### Expected behavior

The message being written with the correct prefix 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v20.9.0
YARN Version    : 1.22.19 

[Nest CLI]
Nest CLI Version : 8.2.8

[Nest Platform Information]
platform-express version : 9.4.3
platform-fastify version : 9.4.3
microservices version    : 9.4.3
serve-static version     : 3.0.1
schematics version       : 9.2.0
passport version         : 9.0.3
typeorm version          : 9.0.1
testing version          : 9.4.3
common version           : 9.4.3
core version             : 9.4.3
jwt version              : 10.2.0
cli version              : 8.2.8

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13151
