### ISSUE TITLE
ValidationPipe does not support index.ts file importing

### ISSUE THREAD

**Issue by CamiloPenagos99** [nestjs/nest#13153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ValidationPipe does not support index.ts file importing. Pipe does not validate when DTO was imported with index.ts

### Minimum reproduction code

https://codesandbox.io/p/devbox/xenodochial-elgamal-dckyvh?file=%2Fsrc%2Fapp.controller.ts%3A11%2C21

### Steps to reproduce

1. Create a simple module with nestjs (controller, service and dto)
2. Define `index.ts` file to export the module files: explanation [index.ts](https://medium.com/@bobjunior542/maximize-typescript-productivity-use-the-index-file-now-cac2f4f4d1ed)
3. Configure ValidationPipe by using either `app.useGlobalPipes(new ValidationPipe());` or `@UsePipes(new ValidationPipe({}))`
4. Create your DTO to validate the incoming data against it:
```
export class CreateUserDto {
  @IsEmail()
  email: string;

  @IsNotEmpty()
  password: string;
}
```
5. if you import the DTO by using the index.ts like this `import { CreateUserDto } from '.'`; any incoming request will hit/reach the controller, no matter its data types (pipe wont work). 
6. You must import the DTO by providing de **full path** like this `import { CreateUserDto } from './xxx/CreateUserDto'` the validationPipe will work as expected depends on your configuration/rules.

### Expected behavior

It should support importing like that to make the process easier and improve code readability

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

"class-validator": "^0.14.0"

### NestJS version

^9.0.0

### Packages versions

```"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/swagger": "^7.1.17",
    "axios": "^1.6.5",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
I guarantee this is due to a circular file import. You _can_ use barrel imports, but you have to make sure you don't end up creating circular file chains where a imports b imports c imports a because it will mess up the type metadata that Nest tries to read to know what type to use in the ValidationPipe and is a restriction at the Typescript level, not something the framework can handle.

**Comment by micalevisk** [comment]
@CamiloPenagos99 here's a good article on that subject: [Circular Dependencies in NestJS and how to Avoid Them](https://trilon.io/blog/avoiding-circular-dependencies-in-nestjs)
