### ISSUE TITLE
applyDecorators doesn't update the openapi.json file when using Matches decorator

### ISSUE THREAD

**Issue by KaydenMiller** [nestjs/nest#13165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When applying decorators using the `applyDecorators` function (specifically the `Matches` decorator) the `openapi.json` spec will not be updated with requisite `pattern` field. 

For example I created a custom decorator for `Matches` and `ApiProperty` where I wanted to provide some validation for the format of an object id, but I also wanted to provide the description api information at the same time. So I used an `applyDecorators` to merge them together. 

Example snippet of what I wrote
```ts
export const IsUniqueIdentifier = () =>
  applyDecorators(
    Matches('^[a-f\\d]{24}$'),
    ApiProperty({
      type: String,
      description:
        'Stringified Mongo ObjectId\nSee [Object Id](https://www.mongodb.com/docs/manual/reference/method/ObjectId/)',
      format: 'ObjectId',
    })
  )
```

`openapi.json` spec actual output:
```json
{
  "type_name_here": {
    "type": "string",
    "description": "Stringified Mongo ObjectId\nSee [Object Id](https://www.mongodb.com/docs/manual/reference/method/ObjectId/)",
    "format": "ObjectId"
  }
}
```

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-92nr6d?file=src%2Fmain.ts

### Steps to reproduce

1. configure basic api using nestjs
2. configure typescript
3. add the `@nestjs/swagger` library
4. create an endpoint and controller
5. create a string property or aliased string property (for example `export type UniqueId = string`
6. create a class to represent the api request
7. create an `applyDecorators` based decorator merging `Matches` with `ApiProperty`
8. apply the new decorator to your previously created string property
9. attempt to make a request where the pattern is not matched
10. it will work even though the pattern is not matched, and the `openapi.json` spec will not have a pattern field

### Expected behavior

expected `openapi.json` output:
```json
{
  "type_name_here": {
    "type": "string",
    "description": "Stringified Mongo ObjectId\nSee [Object Id](https://www.mongodb.com/docs/manual/reference/method/ObjectId/)",
    "format": "ObjectId",
    "pattern": "^[a-f\\d]{24}$"
  }
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/swagger": "^7.2.0",
    "@nestjs/throttler": "^5.1.1",
```

### Node.js version

18.16.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I think that that will be fixed by this PR: https://github.com/nestjs/swagger/pull/2747

**Comment by kamilmysliwiec** [comment]
NestJS Swagger CLI plugin uses static analysis (traverses AST) to detect validation annotations and convert them to corresponding OpenAPI rules. If you use `applyDecorators` which is a runtime construct (plugin doesn't analyze decorators applied through `applyDecorators`) then any validation you put there won't be introspected and reflected in the doc

**Comment by KaydenMiller** [comment]
@kamilmysliwiec that explains the open api spec portion of the issue but shouldn't validation itself still occur? With this validation of the matches also doesn't occur (I probably could have done a better job of including that part of the problem in the description, that my bad).

**Comment by KaydenMiller** [comment]
NVM, I figured out the later issue as well it was that I wasn't providing the `app.useGlobalPipes(new ValidationPipe())` which is required for the validation.
