### ISSUE TITLE
ClassSerializerInterceptor misses groups when using options.type

### ISSUE THREAD

**Issue by jobcespedes** [nestjs/nest#13160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using ClassSerializerInterceptor and options.type: some class, groups  rules are not applied

### Minimum reproduction code

https://github.com/nestjs/nest/blob/180bdf67786f9b8e917e9d2f5e9d9598f7f40867/packages/common/serializer/class-serializer.interceptor.ts#L97

### Expected behavior

Using ClassSerializerInterceptor and options.type: some class, groups are applied

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.10

### Packages versions

```
[System Information]
OS Version     : Linux 6.6
NodeJS Version : v18.14.2
NPM Version    : 9.5.0 

[Nest CLI]
Nest CLI Version : 10.2.1 

[Nest Platform Information]
platform-express version : 10.2.10
microservices version    : 10.2.10
mapped-types version     : 2.0.4
schematics version       : 10.0.3
passport version         : 10.0.3
terminus version         : 10.2.0
swagger version          : 7.1.16
typeorm version          : 10.0.1
testing version          : 10.2.10
common version           : 10.2.10
config version           : 3.1.1
core version             : 10.2.10
cli version              : 10.2.1
 version                 : 2.0.0

```

### Node.js version

v18.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
duplicate #12763
