### ISSUE TITLE
AppController query, req, res variables are undefined when typegoose's setLoglevel executed in main.ts

### ISSUE THREAD

**Issue by lucas-yang-sphr** [nestjs/nest#13163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

http://localhost:3000/?testQuery=you

the query value testQuery is always undefined

### Minimum reproduction code

https://stackblitz.com/~/edit/nestjs-typescript-starter-zumzau?initialPath=/?testQuery=testhaha

### Steps to reproduce

npm install
npm run start:dev

### Expected behavior

http://localhost:3000/?testQuery=you

'you' query value showed as response

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@typegoose/typegoose, mongoose

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "nestjs-sandbox2",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@typegoose/typegoose": "^12.1.0",
    "mongoose": "^8.1.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v18.19.0

### In which operating systems have you tested?

- [x] macOS
- [x] Windows
- [x] Linux

### Other

In the main.ts,

if you remove line 8 which is "setLogLevel('error')",
the web behave correctly.

only it has problem with "setLogLevel('error')" line

source code archive is attached

[nestjs-sandbox2.tar.gz](https://github.com/nestjs/nest/files/14162625/nestjs-sandbox2.tar.gz)

**Comment by micalevisk** [comment]
I just tested. Pretty weird

bu if that error only happens when using `setLogLevel` from `@typegoose/typegoose`, I guess this should be reported to `@typegoose/typegoose`, right? :thinking:

**Comment by micalevisk** [comment]
nvm. That's due to `refelect-metadata`. Same as #13107

![image](https://github.com/nestjs/nest/assets/13461315/98b39014-726c-4c58-a6b4-012aa925d7c3)
