### ISSUE TITLE
GRPC Stream Error

### ISSUE THREAD

**Issue by NAlexandrov** [nestjs/nest#13187]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

PR #12673

### NestJS version

10.2.8 -> 10.2.9 and latest

### Describe the regression

After PR #12673 the stream closes with the status OK and the client does not see the error.

### Minimum reproduction code

https://github.com/NAlexandrov/nest-stream-error

### Input code

```ts
  @GrpcMethod('HelloworldService', 'SayHelloStream')
  sayHelloStream() {
    throw new Error('Method not implemented');
  }
```

### Expected behavior

This code is above must throw an error and client must see it:
![Nest 10.2.8](https://github.com/NAlexandrov/nest-stream-error/raw/main/images/SayHelloStream_10.2.8.png)

But in NestJS >= 10.2.9 client see OK response:

![latest nest](https://github.com/NAlexandrov/nest-stream-error/raw/main/images/SayHelloStream_10.3.2.png)

**Comment by NAlexandrov** [comment]
I have got an expected behavior, if I add `client.emit(error);` before unsubscribe at [line](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-grpc.ts#L313) and `client.emit(err);` before unsubscribe at [line](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-grpc.ts#L337).

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by NAlexandrov** [comment]
> Would you like to create a PR for this issue?

#13195

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13195
