### ISSUE TITLE
Middleware `forRoutes` not working with wildcard which is already working for `exclude` of another middleware

### ISSUE THREAD

**Issue by sidharthbhumio** [nestjs/nest#13194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is my middleware consumer, I have to work with 2 seperate auth flows. So `(.*)/public(.*)` was excluded for `AuthMiddleware` and included for `PublicUserAuthMiddleware`. 
```
configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(AuthMiddleware)
      .exclude(
        'swagger',
        'users/login',
        '(.*)/public(.*)',
      )
      .forRoutes('*')
      .apply(PublicUserAuthMiddleware)
      .forRoutes('(.*)/public(.*)')
      .apply(LoggerMiddleware)
      .forRoutes('*');
```

A route `xxx/:uuid/public` is not being consumed by neither `AuthMiddleware` nor `PublicUserAuthMiddleware`.

### Minimum reproduction code

https://codesandbox.io/p/devbox/nestjs-min-reproducible-dnvsgd?file=%2Fsrc%2Fauth.middleware.ts

### Steps to reproduce

1. Visit `/normal`
2. You'll see `Auth` in the logs as it is consumed by `AuthMiddlware`
3. Visit `/normal/public`
4. Expected to see `Public` in logs, but not seen. Neither is `Auth`.

### Expected behavior

Route `xxx/:uuid/public` should be consumed by `PublicUserAuthMiddleware`. The same pattern used to exclude is not working for `forRoutes`.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Packages versions

```json
{
  "@nestjs/platform-socket.io": "10.3.0",
  "@nestjs/platform-express": "10.3.0",
  "@nestjs/websockets": "10.3.0",
  "@nestjs/common": "10.3.0",
  "@nestjs/core": "10.3.0",
  "@nestjs/schematics": "10.1.0"
}
```

### Node.js version

v18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
`forRoutes` passes routes directly to the underlying HTTP driver which in your case is express, which in turn expects just `*` not `(.*)`. 

`exclude` is a slightly different, cross-platform mechanism that expects a newer syntax.

Not the most straightforward & convenient indeed, but there's much we can do to fix this
