### ISSUE TITLE
`ValidationPipe` and possibly others throw `HttpException` when used on WS gateways

### ISSUE THREAD

**Issue by StiliyanKushev** [nestjs/nest#13190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the following example if the `ValidationPipe` was to ever throw, it would cause an internal error rather then `WsException`.

```ts
@UsePipes(
  new ValidationPipe({
    transform: true,
    forbidUnknownValues: true,
    forbidNonWhitelisted: true,
    whitelist: true,
  }),
)
@WebSocketGateway({ namespace: 'something' })
export class SomethingGateway {}
```

To workaround this at the moment one possible solution is to patch it with an exception filter like so:

```ts
@Catch()
export class WsExceptionsFilter extends BaseWsExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost) {
    if (exception instanceof HttpException) {
      super.catch(new WsException(exception.getResponse()), host);
    } else {
      super.catch(exception, host);
    }
  }
}

@UseFilters(WsExceptionsFilter)
@UsePipes(
  new ValidationPipe({
    transform: true,
    forbidUnknownValues: true,
    forbidNonWhitelisted: true,
    whitelist: true,
  }),
)
@WebSocketGateway({ namespace: 'something' })
export class SomethingGateway {}
```

That's because [by the looks of it](https://github.com/nestjs/nest/blob/8cfa85407218d20022e7d421b8de8dd08d656c63/packages/common/pipes/validation.pipe.ts#L170) `ValidationPipe` always throws an `HttpException` regardless of the protocol of the current execution context.

### Minimum reproduction code

https://github.com/StiliyanKushev/ws-exception-validation-pipe-reproduction-repo

### Steps to reproduce

```shell
npm ci
npm run test:e2e
```

### Expected behavior

I expected `ValidationPipe` to throw a `WsException` when used inside of a WS gateway.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.0

### Packages versions

```shell
[System Information]
OS Version     : Linux 6.6.8-zen1-1-zen
NodeJS Version : v20.8.0
NPM Version    : 10.1.0 

[Nest CLI]
Nest CLI Version : 10.3.2 

[Nest Platform Information]
platform-socket.io version : 10.3.2
platform-express version   : 10.3.2
websockets version         : 10.3.2
schematics version         : 10.1.1
testing version            : 10.3.2
common version             : 10.3.2
core version               : 10.3.2
cli version                : 10.3.2
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Alternatively, if we're meant not to be using `ValidationPipe` on WS gateways, then the docs should be updated.

As of now, the docs clearly showcase the possible use of `ValidationPipe` inside WS gateways as seen here:
![image](https://github.com/nestjs/nest/assets/24881376/29d0109c-0b7e-470a-8720-29528829ce2b)

**Comment by getlarge** [comment]
The `ValidationPipe` constructor can also receive an `exceptionFactory` to create your exceptions. Then, you could have the options for the `WebSocketGateway` validators as a shared constant. I have been doing this for errors thrown in the RPC `ExecutionContext` type.

**Comment by kamilmysliwiec** [comment]
i wonder if we should just update examples in the docs to mention that (what @getlarge said above)

**Comment by kamilmysliwiec** [comment]
![image](https://github.com/user-attachments/assets/d7e083da-30ce-48c8-b372-810273ce92ed)

Docs have been updated
