### ISSUE TITLE
support for nats jetstream in microservice

### ISSUE THREAD

**Issue by sudoStatus200** [nestjs/nest#13198]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I nats message queue setup with nestjs and I can send recieve message efficiently. 
Now I want to setup nats jetstream for sending and receiving data. I can do it by subscribing to subject and capturing data but for this i have to do this manually. 

I wanted to use something like ` @MessagePattern` for jetstream also , so that my implementation becomes simple.

I checked the docs and discord but I could not find any thing specific for jetstream.

I would like work on this feature in nest microservice.

### Describe the solution you'd like

I want to make using nats jetstream easy to implement in nest projects by providing modules to send or recieve data from stream.  

I basically want build something like `nats.send and @MessagePattern` for nats jetstream

### Teachability, documentation, adoption, migration strategy

Based on my reseach this feature not exists, so it will be completely new.

### What is the motivation / use case for changing the behavior?

This will make using nats jetstream much easy for developers and also easy to understand client code.

If this feature already exists please let me know

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
