### ISSUE TITLE
Type issue with supertest and `app.getHttpServer()`

### ISSUE THREAD

**Issue by coler-j** [nestjs/nest#13191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Bumped my dependencies from:

```
@nestjs/cli: "10.2.1" -> 10.3.2
@nestjs/common: "10.3.0" -> 10.3.2
@nestjs/config: "3.1.1" -> 3.2.0
@nestjs/core: "10.3.0" -> 10.3.2
@nestjs/platform-express: "10.3.0" -> 10.3.2
@types/supertest": "2.0.16" -> "6.0.2"
```

Have `"@typescript-eslint/no-unsafe-argument": "error"` in eslint config.

When using supertest with nest application and error will be raised:

```
let app: INestApplication;

...

return request(app.getHttpServer())
      .get('/')
      .expect(200)
      .expect('Hello World!');
```

Error

```
 error  Unsafe argument of type `any` assigned to a parameter of type `App`  @typescript-eslint/no-unsafe-argument
```

MRC provided below.

### Minimum reproduction code

https://codesandbox.io/p/devbox/black-smoke-oly5151mxy?file=%2Fpackage.json%3A37%2C32&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clserz9ty00073b6hkjtgde8z%2522%252C%2522sizes%2522%253A%255B75.59218559218557%252C24.407814407814428%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clserz9ty00023b6hlau8816e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clserz9ty00043b6h8ewzvquw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clserz9ty00063b6hlrjfgq1r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clserz9ty00023b6hlau8816e%2522%253A%257B%2522id%2522%253A%2522clserz9ty00023b6hlau8816e%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clserz9ty00063b6hlrjfgq1r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clserz9ty00053b6haykq24y5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clserz9ty00063b6hlrjfgq1r%2522%252C%2522activeTabId%2522%253A%2522clserz9ty00053b6haykq24y5%2522%257D%252C%2522clserz9ty00043b6h8ewzvquw%2522%253A%257B%2522id%2522%253A%2522clserz9ty00043b6h8ewzvquw%2522%252C%2522activeTabId%2522%253A%2522clses2r4x00cs3b6h7vd5nvdj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clserz9ty00033b6huu3g2g48%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%252C%2522id%2522%253A%2522clses2r4x00cs3b6h7vd5nvdj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

`INestApplication<>

### Expected behavior

`INestAppliction` and `INestApplication<NestExpressApplication>` are typed to match `supertest` `App` expectations

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@types/supertest

### NestJS version

10.3.2

### Packages versions

```json
 "@nestjs/apollo": "12.1.0",
    "@nestjs/cli": "10.3.2",
    "@nestjs/common": "10.3.2",
    "@nestjs/config": "3.2.0",
    "@nestjs/core": "10.3.2",
    "@nestjs/graphql": "12.1.0",
    "@nestjs/mapped-types": "2.0.5",
    "@nestjs/passport": "10.0.3",
    "@nestjs/platform-express": "10.3.2",
    "@nestjs/terminus": "10.2.2",
    "@nestjs/typeorm": "10.0.2",
```

### Node.js version

18.18.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by coler-j** [comment]
Can get around this by doing `NestExpressApplication` instead of `INestAppliction` or `INestApplication<NestExpressApplication>`

**Comment by micalevisk** [comment]
so the "issue" is because `app.getHttpServer()` has `any` as the return type, right?

that's because of the following change: https://github.com/nestjs/nest/commit/cf4097cf24b2c3d64ae1b884e63b3945bcd8fc4b

now `INestApplication` has a type arg, which defaults to `any`

https://github.com/nestjs/nest/blob/8cfa85407218d20022e7d421b8de8dd08d656c63/packages/common/interfaces/nest-application.interface.ts#L24

I'am not sure if we can improve that or if you just need to type that `INestApplication` better

**Comment by coler-j** [comment]
Well, how would I type the `INestApplication` better than doing `INestApplication<NestExpressApplication>`? I don't think there is anything else that would make sense in the context that it is being used.

**Comment by micalevisk** [comment]
I guess it should be: `INestApplication<Server>` where `Server` is from `net` (nodejs module)

**Comment by kamilmysliwiec** [comment]
Just pass `<Server>` as a type argument, as @micalevisk suggested above

When it comes to your ESLint rule, this isn't a bug (more explanation here https://github.com/nestjs/schematics/pull/1700#issuecomment-1938177634)

One thing we could improve is to mention this in the docs (_if you have X rule enabled, then make sure to pass Server as a type argument_).
