### ISSUE TITLE
Add built-in HTTP exception `TooManyRequests` to `nestjs/common` package

### ISSUE THREAD

**Issue by LauraBeatris** [nestjs/nest#13197]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It's a blocker per se, as it's possible to use `HttpException` with `429` status code, so it's more like an abstraction to be added as for other statuses code. 

### Describe the solution you'd like

Introduce an exception class for `429` status code. 

### Teachability, documentation, adoption, migration strategy

Would need to update this doc section to include the new built-in exception: https://docs.nestjs.com/exception-filters#built-in-http-exceptions

### What is the motivation / use case for changing the behavior?

The majority of the codebase that I'm working relies on built-in exception classes, and I couldn't find one for the 429 status code.

**Comment by jmcdo29** [comment]
There's one that exists already in `@nestjs/throttler`, and making your own extension of `HttpException` is relatively straightforward

**Comment by LauraBeatris** [comment]
> There's one that exists already in `@nestjs/throttler`, and making your own extension of `HttpException` is relatively straightforward

@jmcdo29 I understand that it's a simple abstraction, not a blocker per se. I guess the argument would be, if there are other HTTP statuses in the package, why not cover all of them?

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).

**Comment by kamilmysliwiec** [comment]
Just a few examples (for the reference)

https://github.com/nestjs/nest/issues/6657#issuecomment-799214959
https://github.com/nestjs/nest/pull/11560
https://github.com/nestjs/nest/pull/9446
https://github.com/nestjs/nest/pull/8358
https://github.com/nestjs/nest/pull/8352
https://github.com/nestjs/nest/pull/9778
