### ISSUE TITLE
Jest fails to import files

### ISSUE THREAD

**Issue by 1alexvash-work** [nestjs/nest#13205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The error:
![image](https://github.com/nestjs/nest/assets/150182520/76b4cbc9-9f93-4139-a3b9-f44816f176a7)

Walkthrough the error:
https://www.loom.com/share/c27d87ff55884bf0a4f8b3dca2969e52

### Minimum reproduction code

https://github.com/1alexvash-work/nestjs-jest-error

### Expected behavior

Jest test environment works the same way as NestJS dev environment

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "project-name",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "prisma:generate": "yarn prisma generate"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@prisma/client": "^5.8.1",
    "axios": "^1.6.7",
    "jsonwebtoken": "^9.0.2",
    "mongodb": "^6.3.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "prisma": "^5.8.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This is how Jest has always worked by default with Nest. If you want to use absolute (`src/`) imports, you have to configure Jest via the [`moduleNameMapper`](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring) option. Otherwise, you should use relative imports.

**Comment by 1alexvash-work** [comment]
@jmcdo29 

At 2:07 it can be seen that I've used this option already

**Comment by jmcdo29** [comment]
Then it should be in the reproduction repository. [I don't see it in the jest configuration in your package.json](https://github.com/1alexvash-work/nestjs-jest-error/blob/dev-step-two/package.json#L58)

**Comment by 1alexvash-work** [comment]
True

This piece of code just did not seem to make any difference. The error was the same; hence I did not commit it, commited it now

**Comment by mlp-dw** [comment]
[1alexvash-work](https://github.com/1alexvash-work) I exatly have the same issue, my import doesn't work, do you found any solution ?

**Comment by 1alexvash-work** [comment]
@mlp-dw 

I had to configure it inside the `package.json`

![image](https://github.com/nestjs/nest/assets/150182520/3a05480a-6afd-41e2-ac17-23f3848ea6c3)

**Comment by 1alexvash-work** [comment]
@jmcdo29 

Let's include this config as a default one for NestJS boilerplate, so in the future people don't encounter this problem
