### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by buqiyuan** [nestjs/nest#13210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="805" alt="image" src="https://github.com/nestjs/nest/assets/39730999/4b6e900f-68d5-4e14-96a0-b1fd781b3209">
<img width="792" alt="image" src="https://github.com/nestjs/nest/assets/39730999/6d95fd87-08ed-4ab2-82f9-f4c200514a49">
<img width="565" alt="image" src="https://github.com/nestjs/nest/assets/39730999/64ec8716-c33c-4792-8d0f-13dd66933196">

### Minimum reproduction code

none

### Expected behavior

Maybe we need writing a depth limiter manually (see [microsoft/TypeScript#45711](https://github.com/microsoft/TypeScript/pull/45711)).

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/config

### Packages versions

```json
    "@nestjs/common": "^10.3.2",
    "@nestjs/config": "^3.2.0",
    "@nestjs/core": "^10.3.2",
```

### Node.js version

18

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Which version of typescript are you using?

**Comment by buqiyuan** [comment]
> 您使用的是哪个版本的打字稿？

"typescript": "^5.3.3"

**Comment by buqiyuan** [comment]
Sorry, this is my problem, I used `DataSourceOptions` as `ConfigType` incorrectly, sorry for wasting your precious time.

```diff
import { registerAs } from '@nestjs/config'

import { DataSource, DataSourceOptions } from 'typeorm'
+ import { MysqlConnectionCredentialsOptions } from 'typeorm/driver/mysql/MysqlConnectionCredentialsOptions'
import { env, envBoolean, envNumber } from '~/global/env'
// eslint-disable-next-line import/order
import dotenv from 'dotenv'

dotenv.config({ path: `.env.${process.env.NODE_ENV}` })

const dataSourceOptions: DataSourceOptions = {
  type: 'mysql',
  host: env('DB_HOST', '127.0.0.1'),
  port: envNumber('DB_PORT', 3306),
  username: env('DB_USERNAME'),
  password: env('DB_PASSWORD'),
  database: env('DB_DATABASE'),
  synchronize: envBoolean('DB_SYNCHRONIZE', false),
  entities: ['dist/modules/**/*.entity{.ts,.js}'],
  migrations: ['dist/migrations/*{.ts,.js}'],
  subscribers: ['dist/modules/**/*.subscriber{.ts,.js}'],
}
export const dbRegToken = 'database'

export const DatabaseConfig = registerAs(
  dbRegToken,
  (): DataSourceOptions => dataSourceOptions,
)

- export type IDatabaseConfig = ConfigType<typeof DatabaseConfig>
+ export type IDatabaseConfig = Pick<MysqlConnectionCredentialsOptions, 'host' | 'port' | 'username' | 'password' | 'database'>

const dataSource = new DataSource(dataSourceOptions)

export default dataSource
```
