### ISSUE TITLE
Add `@RawBody()` decorator to avoid having to always resort to `@Req()` with specific types and parameters

### ISSUE THREAD

**Issue by tolgap** [nestjs/nest#13224]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Right now when you want to access the raw body of a request, you always have to inject the entire `@Req()` with a specific wrapper type:

```ts
@Controller()
class MyController {
  @Get('/')
  myRoute(@Req() req: RawBodyRequest<unknown>) {
    const { rawBody } = req
    // ...
  }
}
```

This feels a bit cumbersome.

### Describe the solution you'd like

I would like to introduce a `@RawBody()` param decorator to reduce the type overhead, and avoid having to use specific typings:

```ts
@Controller()
class MyController {
  @Get('/')
  myRoute(@RawBody() rawBody: Buffer) {
    // ...
  }
}
```

### Teachability, documentation, adoption, migration strategy

This can be added to the documention site on the following pages:

- https://docs.nestjs.com/faq/raw-body
- https://docs.nestjs.com/controllers#request-object

### What is the motivation / use case for changing the behavior?

I'm writing specific logic that _should_ be HTTP adapter agnostic, but I'm having to use `@Req req: RawBodyRequest<FastifyRequest | Request>` as typings. Would be nice if I could avoid that.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13225
