### ISSUE TITLE
Kafka microservice throw Error when first connect to server

### ISSUE THREAD

**Issue by sollidy** [nestjs/nest#13220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I start kafka in docker, with `bitnami/kafka:3.3.2`, it create clean kafka server. Than i start nestjs microservice, which throw Error `This server does not host this topic-partition`. Even though I've written in config `allowAutoTopicCreation: true`.
I need to restart nest to make the connection happen.

![Screenshot from 2024-02-16 11-21-05](https://github.com/nestjs/nest/assets/70297692/36901132-92f1-431b-b807-181c58673187)

### Minimum reproduction code

https://github.com/sollidy/nest-monorepo-example

### Steps to reproduce

1. docker-compose up -d
2. yarn install
3. yarn start:dev-piscina-compute

Before new try, you need firstry down containers `docker-compose down`

### Expected behavior

Creating new topics in Kafka without throwing Error

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.2

### Packages versions

```
[System Information]
OS Version     : Linux 6.7.4-100.fc38.x86_64
NodeJS Version : v18.19.0
YARN Version    : 4.1.0 

[Nest CLI]
Nest CLI Version : 10.3.2 

[Nest Platform Information]
platform-express version : 10.3.2
microservices version    : 10.3.2
schematics version       : 10.1.1
testing version          : 10.3.2
common version           : 10.3.2
core version             : 10.3.2
cli version              : 10.3.2
```

### Node.js version

18.19.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
