### ISSUE TITLE
Request sample code for mqttjs in nestjs

### ISSUE THREAD

**Issue by zhuqiyun** [nestjs/nest#1323]
Can someone provide a sample code for the mqtt client? Just like ngx-mqtt, or how to use mqttjs in nest, the specific code example. We are the manufacturer of the Internet of Things, want to use nestjs in the background, use mqtt to subscribe to the information of various devices. I created an issue last time, but I still don't understand that answer. Thank you

**Comment by kamilmysliwiec** [comment]
Closed due to the lack of activity & capacity of contributors is not infinite. Hopefully, I'll be able to provide an example some day in the future

**Comment by dreamerblade** [comment]
I didn't want to make a new issue after finding this one but I certainly agree with this. Spent about 2 hours scouring the internet for even the briefest mention of NestJS working with MQTT to no avail.
