### ISSUE TITLE
Bad typings for Fastify server `enableCors` method, `delegator` property is missing

### ISSUE THREAD

**Issue by mdorda** [nestjs/nest#13234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When passing `delegator` property to `enableCors` method (according to `@fastify/cors` [documentation](https://github.com/fastify/fastify-cors)), it issues:
```
Object literal may only specify known properties, and 'delegator' does not exist in type 'CorsOptions | CorsOptionsDelegate<any>'
```

It is needed to access the whole request object. Using `cors` property or pass function (`CorsOptionsDelegate<T>`) allows to access only `origin` string property and whole `fastify` object, but not the request itself.

### Minimum reproduction code

https://github.com

### Steps to reproduce

```typescript
const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter({}),
);

app.enableCors({
    // this issues an TS error, but works in runtime as expected
    delegator: (request: FastifyRequest, callback: CorsOptionsCallback): void => {
        //
    },
});
```

### Expected behavior

Code provided in "Steps to reproduce" should not issues an TS error.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.1

### Packages versions

```
"@fastify/compress": "~6.5.0",
"@fastify/static": "~6.12.0",
"@nestjs/cli": "~10.3.0",
"@nestjs/common": "~10.3.1",
"@nestjs/core": "~10.3.1",
"@nestjs/passport": "~10.0.3",
"@nestjs/platform-fastify": "~10.3.1",
"@nestjs/schedule": "^4.0.0",
"@nestjs/swagger": "~7.2.0",
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by mdorda** [comment]
If it is desirable to fix the issue, I will be happy to do so.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13247
