### ISSUE TITLE
Improve experience when initialisation error occurs

### ISSUE THREAD

**Issue by gingermusketeer** [nestjs/nest#13246]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Similar to https://github.com/nestjs/nest/issues/5162 I have run into the usage of `process.abort()` hiding the underlying error.

In  my case it was due to SWC compiling a sub dependency incorrectly such that an exception was thrown when it was used. 

The current implementation results in a core dump which in CI looked like:
```
          app │ ----- Native stack trace -----
          app │
          app │  1: 0xc8610c node::Abort() [node]
          app │  2: 0xcfb29c  [node]
          app │  3: 0xeefaf8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [node]
          app │  4: 0xef02b8  [node]
          app │  5: 0xef06d0 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
          app │  6: 0x186d964  [node]
          app │
          app │ ----- JavaScript stack trace -----
          app │
          app │ 1: handleInitializationError (/workspace/node_modules/@nestjs/core/nest-factory.js:118:21)
          app │ 2: initialize (/workspace/node_modules/@nestjs/core/nest-factory.js:113:18)
          app │ 3: processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The "JavaScript stack trace" is only available from node >18 so to debug it required node to be upgraded.

### Describe the solution you'd like

The above core dump is not useful that useful but the JS stack trace is. Ideally the original error would not be swallowed and would be thrown or logged. Also using `process.exit` instead of `process.abort` would remove the unhelpful core dump log.

### Teachability, documentation, adoption, migration strategy

Hopefully doesn't require teaching users as they will see their errors.

### What is the motivation / use case for changing the behavior?

Better developer experience.

**Comment by kamilmysliwiec** [comment]
This sounds like an edge case - the compiler incorrectly processed your files, and this shouldn't happen often (or ever really). 

To cover this, use `abortOnError: false` as suggested here https://github.com/nestjs/nest/pull/5327

There's a few reasons we can't just migrate to process.exit - more can be found in old issues.
