### ISSUE TITLE
When I use Nestjs in my own build monorepo project, there seems to be some bugs with "@nestjs/core postinstall".

### ISSUE THREAD

**Issue by XiangLinDotFu3** [nestjs/nest#13245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to integrate the front-end project of React and the back-end project of NestJS into a monorepo project, so I created a monorepo project with the NestJS backend project as one of the packages, and then pnpm install the relevant dependencies in the root directory of the monorepo, and an error occurred.

![error](https://github.com/nestjs/nest/assets/144814364/0fb6c5d8-7249-4a25-afa7-0f27a8a30346)

Hope the master provides a solution to this problem, thank you.

### Minimum reproduction code

https://github.com/XiangLinDotFu3/monorepo-nest-todo.git

### Steps to reproduce

1. git clone https://github.com/XiangLinDotFu3/monorepo-nest-todo.git
2. cd monorepo-nest-todo-master
3. pnpm install

### Expected behavior

All packages can be installed in the root directory of the monorepo project

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.1

### Packages versions

```json

```

### Node.js version

16.20.2

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/12383
