### ISSUE TITLE
When I introduce a configuration file from outside the project, an error occurs: Cannot find module

### ISSUE THREAD

**Issue by FerretAngel** [nestjs/nest#13251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```code
PS C:\Users\12194\Desktop\test\test> nest start
Error: Cannot find module 'C:\Users\12194\Desktop\test\test\dist\main'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

### Minimum reproduction code

https://github.com/FerretAngel/nestImportOutsideError/tree/main

### Steps to reproduce

This is my project path,(this project is using nestcli creted:nest new test)
![image](https://github.com/nestjs/nest/assets/58507654/85f0d16c-baef-4022-b4fa-7b1374fdfe60)
Import external files in src/main.ts.
![image](https://github.com/nestjs/nest/assets/58507654/8e155cc2-9186-416d-9f02-6ff3fbcd042f)
This is the content of config.ts.
![image](https://github.com/nestjs/nest/assets/58507654/2e69eade-c544-4a21-b394-494d28cda9d5)

### Expected behavior

![image](https://github.com/nestjs/nest/assets/58507654/b50c008c-20e5-410a-b601-89162d3db3ba)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v18.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by FerretAngel** [comment]
Why am I importing an external file? Because I'm learning how to manage microservices in a monorepo, so I need to use a global constant that all microservices can access.

**Comment by micalevisk** [comment]
I believe you should either need to change the entry file (`entryFile`) or the source dir (`sourceRoot` in your `nest-cli.json` due to how your tsconfig and your project file structure.

Or just define the right [`rootDir`](https://www.typescriptlang.org/tsconfig#rootDir) in your `tsconfig.json` instead of letting TSC infer it, I guess.

**Comment by FerretAngel** [comment]
I separately edited the entryFile of nest-cli.json for each project and now it runs successfully. Thank you very much for your help!
