### ISSUE TITLE
How can I override nest's default logger using the fastify adapter's built-in logger?

### ISSUE THREAD

**Issue by Tony133** [nestjs/nest#13286]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

You can override the default NestJS logger with the logger embedded in the Fastify adaptor (that would be the Pino logger),  is it possible ?

```ts
 const fastifyAdapter = new FastifyAdapter({
    logger: true, // enable logger integrated into fastify adapter
  });

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    fastifyAdapter,
    {
      bufferLogs: true,
    },
  );

  const logger = app.get(.............);  // ---> what passes here ??? 
  app.useLogger(logger);
```

### Describe the solution you'd like

Ability to use the logger built into the fastify adapter by overriding the default logger of Nest.

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

Since the Fastify adapter has a built-in logger, it would be nice if it were possible to use it by default in the Nest application by overriding the default Nest logger. Looking at the Fastify adapter file a `FastifyBaseLogger` is used (imported here https://github.com/nestjs/nest/blob/master/packages/platform-fastify/adapters/fastify-adapter.ts#L20 ) so I guess it is possible to use it instead of the default one, no?

**Comment by kamilmysliwiec** [comment]
You can use nestjs-pino https://github.com/iamolegga/nestjs-pino

**Comment by lamngockhuong** [comment]
Hi @Tony133

Here’s how I did it. I hope it’s helpful for you.

```
// Create PinoLoggerService class

import { LoggerService } from '@nestjs/common';
import { FastifyBaseLogger } from 'fastify';

export class PinoLoggerService implements LoggerService {
  constructor(private readonly logger: FastifyBaseLogger) {}

  log(message: any, context?: string) {
    this.logger.info({ context }, message);
  }

  error(message: any, trace?: string, context?: string) {
    this.logger.error({ context, trace }, message);
  }

  warn(message: any, context?: string) {
    this.logger.warn({ context }, message);
  }

  debug?(message: any, context?: string) {
    this.logger.debug({ context }, message);
  }

  verbose?(message: any, context?: string) {
    this.logger.trace({ context }, message);
  }
}
```

```
// at main.ts
  const fastifyAdapter = new FastifyAdapter({
    logger: true
  });

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    fastifyAdapter,
    {
      bufferLogs: true, // required
    },
  );

  app.useLogger(new PinoLoggerService(fastifyAdapter.getInstance().log));
```

<img width="1234" alt="image" src="https://github.com/user-attachments/assets/c9242837-e7f9-4319-8832-9b901c6939d9">

**Comment by mdhthahmd** [comment]
Hi, does the platform-fastify package expose the `FastifyBaseLogger` type?

**Comment by micalevisk** [comment]
@mdhthahmd no. You can find this out by searching for `FastifyBaseLogger` in this repository.

You can import that type from `fastify`

**Comment by mdhthahmd** [comment]
Thanks @micalevisk for the quick response, i ended up doing
```ts
import { LoggerService } from '@nestjs/common';
import { FastifyAdapter } from '@nestjs/platform-fastify';
import pino, { LoggerOptions } from 'pino';

export const options: LoggerOptions = {
  level: process.env.NODE_ENV !== 'production' ? 'debug' : 'fatal',
  base: {
    application: 'nestjs',
    environment: process.env.NODE_ENV || 'development',
  },
};

export const logger = pino(options);

export class PinoLogger implements LoggerService {
  constructor(log: FastifyAdapter['instance']['log']) {}

  log(message: any, context?: string) {
    this.log.info({ context }, message);
  }

  error(message: any, trace?: string, context?: string) {
    this.log.error({ context, trace }, message);
  }

  warn(message: any, context?: string) {
    this.log.warn({ context }, message);
  }

  debug?(message: any, context?: string) {
    this.log.debug({ context }, message);
  }

  verbose?(message: any, context?: string) {
    this.log.trace({ context }, message);
  }
}
```
