### ISSUE TITLE
examples: Consider upgrading GraphQL example to demonstrate field resolvers

### ISSUE THREAD

**Issue by llllvvuu** [nestjs/nest#13295]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Right now, all of the GraphQL examples in the `sample/` folder only have one entity.

### Describe the solution you'd like

It would be great for some of the examples to demonstrate the proper pattern for working with two or more entities and adding a resolver for queries like
```graphql
recipes {
  foo
  bar
  ingredients {
    baz
  }
}
 ```

### Teachability, documentation, adoption, migration strategy

This is the documentation.

### What is the motivation / use case for changing the behavior?

No change in behavior.

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome if you'd be interested in creating one :)
