### ISSUE TITLE
Security Vulnerability on NestJS

### ISSUE THREAD

**Issue by aydinnyunus** [nestjs/nest#13311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I reported it through the email from **aydinnyunus@gmail.com** user but I did not get any response.

### Minimum reproduction code

-

### Expected behavior

-

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

latest

### Packages versions

```json
latest
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
is it a vulnerability on any `@nestjs/*` packages or some of their dependencies?

**Comment by aydinnyunus** [comment]
> is it a vulnerability on any `@nestjs/*` packages or some of their dependencies?

Hello, indeed, it's under `@nestjs/*`. I've already provided the specifics via email to support@nestjs.com.

**Comment by micalevisk** [comment]
ok. thanks.

just to let you know, I don't have access to that e-mail. Kamil should give it a shot

**Comment by aydinnyunus** [comment]
okay thank you

**Comment by kamilmysliwiec** [comment]
`FileTypeValidator` only verifies the mime type (as stated in the comment https://github.dev/nestjs/nest/blob/e331fb0d996b4fea11bd3ef8e76ef46e8b53b4d1/packages/common/pipes/file/file-type.validator.ts#L19)

**Comment by Woodz** [comment]
For anyone coming to this issue from the security vulnerability database links, the actual discussion and fix are in https://github.com/nestjs/nest/issues/14876
