### ISSUE TITLE
Add a ParseNullPipe to the common library

### ISSUE THREAD

**Issue by keenjoe007** [nestjs/nest#13310]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, NestJS does not provide a ParseNullPipe in the common library.

### Describe the solution you'd like

Implementing a ParseNullPipe. I am open to opening a PR with the changes!

### Teachability, documentation, adoption, migration strategy

Including the new pipe in https://docs.nestjs.com/pipes#built-in-pipes.

### What is the motivation / use case for changing the behavior?

I think it is common enough to want to parse null from get request, so including it in the common library can save some time:)

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
