### ISSUE TITLE
Is a good idea to make auto import when generate files using cli?

### ISSUE THREAD

**Issue by tarfao** [nestjs/nest#13325]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Actually is not a problem, is just to improve or time because always I have to create controller, service and provider I have to import a service into controller and provider into a service.

### Describe the solution you'd like

I would like to generate controllers, services and providers, using CLI, and the controller have already imported service, and service have already imported provider.
Like happens with module when we generate new files, it'll import into module file.

### Teachability, documentation, adoption, migration strategy

Always when we have to build a new context, it's more common create at least two files, controller and service, or service and provider or even all of them, controller, service and provider.

I suggest that when we run:

`nest generate service`

We already have imported a provider, even if we won't use that. See the image below

![image](https://github.com/nestjs/nest/assets/29742240/3ceb7e0c-39b1-4487-9970-a2f2b0123dd9)

the same have to happens when we generate a controller, but importing the service instead of provider.

### What is the motivation / use case for changing the behavior?

Always when I have to create controller, service and provider I have to import a service into controller and provider into a service.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
