### ISSUE TITLE
@Req still undefinied with reflect-metadata@^0.2

### ISSUE THREAD

**Issue by gayamedj** [nestjs/nest#13322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Last week, I had a problem with the @req object being undefined. I discovered that the issue was related to **the reflect-metadata** version not matching the one used by the **typeorm** package. To address this, I downgraded typeorm to version **0.3.19**, which resolved the issue.

However, today, I encountered the same problem again, and unfortunately, the previous solution didn't work. After seeking help on the support channel, I learned of another solution that seemed to work for others: upgrading the **reflect-metadata** version to **^0.2.1**. *Despite trying this, my @req#3382 body remains undefined.*

```json
  "dependencies": {
    "@hapi/joi": "^17.1.1",
    "@nestjs/common": "^10.3.3",
    "@nestjs/config": "^3.2.0",
    "@nestjs/core": "^10.3.3",
    "@nestjs/mapped-types": "^2.0.5",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/platform-fastify": "^10.3.3",
    "@nestjs/typeorm": "^10.0.2",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "mysql2": "^3.9.2",
    "reflect-metadata": "^0.2.1",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.20"
  },
```

### Minimum reproduction code

https://github.com/gayamedj/nestjs-reflect-metadata-version-issue

### Steps to reproduce

1. yarn start
2. Send a POST request to the  "/admins" route with JSON Body

### Expected behavior

The route should return the body you sent.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

{
    "@hapi/joi": "^17.1.1",
    "@nestjs/common": "^10.3.3",
    "@nestjs/config": "^3.2.0",
    "@nestjs/core": "^10.3.3",
    "@nestjs/mapped-types": "^2.0.5",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/platform-fastify": "^10.3.3",
    "@nestjs/typeorm": "^10.0.2",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "mysql2": "^3.9.2",
    "reflect-metadata": "^0.2.1",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.20"
  }

### Node.js version

v20.11.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I didn't manage to reproduce it with this minimum repro https://gitlab.com/micalevisk/reflecting

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/typeorm/typeorm/issues/10671

**Comment by OSA413** [comment]
Can not reproduce, `package-lock` file shows `"reflect-metadata": "^0.2.1"`
