### ISSUE TITLE
gRPC Streaming endpoints that throw errors crash the main process

### ISSUE THREAD

**Issue by ssilve1989** [nestjs/nest#13360]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

#13328

### NestJS version

10.2.9 -> 10.3.5

### Describe the regression

gRPC server streaming endpoints that throw errors now have nothing catching those errors resulting in an unhandledRejection crashing the application. This is the offending PR https://github.com/nestjs/nest/pull/13328 

I will plan to work with @benlesh to get a PR up to resolve these as well as some other concerns ben has around the `call.emit` changes, and add test cases that prevent this issue in the future

### Minimum reproduction code

https://github.com/ssilve1989/nest-grpc-streaming-regression

### Input code

A simple rpc that throws an error crashes the entire application now 

```ts
  @GrpcMethod('EchoService', 'StreamEcho')
  streamEcho(request: StreamEchoRequest): Observable<StreamEchoResponse> {
    throw new Error('oopsies');
  }
```

### Expected behavior

The server responding to requests with gRPC Errors should not itself crash. 

### Other

papertrail of PRs that led to this issue

https://github.com/nestjs/nest/pull/12673
https://github.com/nestjs/nest/pull/13195
https://github.com/nestjs/nest/pull/13328

**Comment by kamilmysliwiec** [comment]
Thank you @ssilve1989! For now I just reverted the #13328 PR https://github.com/nestjs/nest/pull/13367
