### ISSUE TITLE
Extra options are set only to default values when using `registerAsync` 

### ISSUE THREAD

**Issue by snigdha920** [nestjs/nest#13372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

For a dynamic module built using the configurable module builder:

- When configured using `registerAsync`, [extra-options](https://docs.nestjs.com/fundamentals/dynamic-modules#extra-options) are set to the default value, not the value being provided
  
- When configured using `register`, the extra options are set to the value being provided

### Minimum reproduction code

https://github.com/snigdha920/nestjs-extra-options-bug

## Steps to reproduce

1. Install dependencies with `pnpm i`
2. Run `pnpm start:dev` in the root
3. We see that the `AuthorModule` is not initialised, even though we pass `authorEnabled` to `true` in the `BookModule.registerAsync` configuration:

<img width="1548" alt="image" src="https://github.com/snigdha920/nestjs-extra-options-bug/assets/62167899/70282f5d-ef43-40ab-a373-b2de9d46a7f1">

4. Comment out the `registerAsync` configuration, and uncomment the `register` configuration in `app.module.ts`, then we see that the `AuthorModule` is initialised:

<img width="1540" alt="image" src="https://github.com/snigdha920/nestjs-extra-options-bug/assets/62167899/b7e1ddfc-13aa-4782-8fdc-a6be000e834d">

### Expected behavior

The `AuthorModule` should be initialised when we pass `authorEnabled` to `true` in the `BookModule.registerAsync` configuration

What I'm trying to do is import modules depending on config passed in. So in practice I use a ConfigService to pass the right config to the module:

```typescript
 JobsModule.registerAsync({
  inject: [ConfigService],
  useFactory: (configService: ConfigService) => {
    const billingEnabled = configService.getOrThrow<boolean>('billingEnabled');
    return {
      billingEnabled,
    };
  },
}),
```

But the extra options are not being set correctly when using registerAsync, and I can only use registerAsync because I want to use my ConfigService.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.7

### Packages versions

```json
{
  "name": "nestjs-di",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "10.3.7",
    "@nestjs/core": "10.3.7",
    "@nestjs/platform-express": "10.3.7"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


```

### Node.js version

20.11.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
`authorEnabled` is not an option of the `BookModule`, but rather an extra of it. It lives at the same level as `useFactory` or `useClass` when using `registerAsync`, but _looks_ like it lives at the same level as the options when using regular `register`. This is not a bug, but the way the system is designed. 
![image](https://github.com/nestjs/nest/assets/28268680/6d092a40-72bc-44ad-819f-20f9ba61667f)

**Comment by snigdha920** [comment]
> `authorEnabled` is not an option of the `BookModule`, but rather an extra of it. It lives at the same level as `useFactory` or `useClass` when using `registerAsync`, but _looks_ like it lives at the same level as the options when using regular `register`. This is not a bug, but the way the system is designed. ![image](https://private-user-images.githubusercontent.com/28268680/317833162-6d092a40-72bc-44ad-819f-20f9ba61667f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjA1MzcsIm5iZiI6MTcxMjA2MDIzNywicGF0aCI6Ii8yODI2ODY4MC8zMTc4MzMxNjItNmQwOTJhNDAtNzJiYy00NGFkLTgxOWYtMjBmOWJhNjE2NjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDEyMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZjI2NzE1ZjI0MDEwZDI1NGVlNmI2ZTk1Nzk5MmQwOTI5NzRjOTA4M2JhYzNhNDE2MTA4MmViNGZjZjQ4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IsPNjSGeM-HI9z6GP8t5pByBAAiZY_vepnpNEVBYPKE)

Clear, thx! I think we should add an example in the documentation, or a note, because from the documentation it looks like it's an option we can pass from `registerAsync` too. If you agree, I can open a PR.
