### ISSUE TITLE
Connection Error in Service during Startup

### ISSUE THREAD

**Issue by chahatjaink** [nestjs/nest#13377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Problem Description:
During the initialization of the NestJS application, the WebService encounters a connection error when attempting to communicate with the proxy service. The error message indicates "Error: connect ECONNREFUSED 172.23.0.2:8544".

Probable Cause:
The connection error likely occurs because the proxy service may not be fully initialized or ready to accept connections when the Web3Service attempts to establish a connection during the startup of the NestJS application.

### Minimum reproduction code

https://www.reddit.com/r/nestjs/comments/1bs491l/connection_error_in_webservice_during_startup/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

### Expected behavior

Proxy service should start on startup and should be utilised in onModuleInit()

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json

```

### Node.js version

10.9.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Tony133** [comment]
Hi @chahatjaink, for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel

The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
