### ISSUE TITLE
Can we have a template resource for graphql + rest together?

### ISSUE THREAD

**Issue by LeOndaz** [nestjs/nest#13376]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Nope, no problems

### Describe the solution you'd like

When asked
```
What transport layer do you use?
```

Can we have a point that says

```
GraphQL + Restful
```

That gives a resul of 

```
feature/rest/<as_if_we_chose_rest>
feature/graphql/<as_if_we_choose_graphql_code_or_schema>
```

### Teachability, documentation, adoption, migration strategy

I'll be able to do the PR in both Nest.js and the docs

### What is the motivation / use case for changing the behavior?

I have an API that exposes both because it's a business-to-business API, and our business cases show that some businesses will prefer to go for GraphQL while others will go for Rest, but since we are not targetting consumers, we will incorporate both. I'm currently doing the structuring manually, if it seems like a nice feature, I'll happily give it a shot in your codebase.

**Comment by Tony133** [comment]
Hi @LeOndaz ,

This repository is dedicated to the NestJS framework not Next.js framework

For questions or support for the NestJS framework try using the support channel [discord](https://discord.com/invite/G7Qnnhy)

The NestJS Core team uses GitHub to keep track of bug reports, feature requests, and regressions.

I hope I'm being helpful

**Comment by LeOndaz** [comment]
> Hi @LeOndaz ,
> 
> 
> 
> This repository is dedicated to the NestJS framework not Next.js framework
> 
> 
> 
> For questions or support for the NestJS framework try using the support channel [discord](https://discord.com/invite/G7Qnnhy)
> 
> 
> 
> The NestJS Core team uses GitHub to keep track of bug reports, feature requests, and regressions.
> 
> 
> 
> I hope I'm being helpful

Hello, that's a typo, I meant nest

**Comment by LeOndaz** [comment]
@micalevisk in case its okay for you, I will PR this (add GraphQL + Rest in one option, in the TUI)

**Comment by micalevisk** [comment]
I found that too too specific to live under the `@nestjs/schematics` collection. As you can plug your own collection to that `generate` command, I prefer to not add such resource template.

But the final decision is up to Kamil.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
