### ISSUE TITLE
Middleware consumer have a text error

### ISSUE THREAD

**Issue by qd-xiaowang** [nestjs/nest#13371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

overview→Middleware→Middleware consumer→code

import { CatsController } from './cats/cats.controller.ts';

".ts" is error

![nest](https://github.com/nestjs/nest/assets/64092346/86097c39-239a-4a79-839f-1083d7f45e75)

### Minimum reproduction code

https://github.com/nestjs/

### Expected behavior

import { CatsController } from './cats/cats.controller';

Also, how can I become a contributor to Nest?

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

now

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
[Docs are open source, feel free to make a PR](https://github.com/nestjs/docs.nestjs.com)

**Comment by qd-xiaowang** [comment]
> [Docs are open source, feel free to make a PR](https://github.com/nestjs/docs.nestjs.com)

thanks！

**Comment by qd-xiaowang** [comment]
> [Docs are open source, feel free to make a PR](https://github.com/nestjs/docs.nestjs.com)

I submitted a PR in the document, please check! #3083
