### ISSUE TITLE
There is no change in the treatment between string and object response of HttpException

### ISSUE THREAD

**Issue by IsraelZablianov** [nestjs/nest#1339]
https://github.com/nestjs/nest/blob/d5dca175d753a0931bd4cc7853f18895c0eb3db3/packages/common/exceptions/http.exception.ts#L11

When response is a string or object the same behavior is applied, in contrast to what is written in the comment.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting!

**Comment by kamilmysliwiec** [comment]
Fixed in 5.5.0 :)
