### ISSUE TITLE
Improve documentation on @Injectable()

### ISSUE THREAD

**Issue by bacebu4** [nestjs/nest#13398]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Documentation on why `@Injectable()` decorator is not clear enough in docs as well as in source code comment. For more information we can refer to this [article](https://medium.com/@maciejsikorski/why-do-we-use-the-injectable-decorator-with-nestjs-60b4ca7d955c#:~:text=The%20%40Injectable()%20decorator%20attaches,by%20the%20Nest%20IoC%20container.)

### Describe the solution you'd like

I'd like to suggest adding more information about why `@Injectable()` is really needed to eliminate the confusion. What do you think about that? I can draft PR with suggestions

### Teachability, documentation, adoption, migration strategy

Provided explanation in the link can be a good foundation for improving documentation

### What is the motivation / use case for changing the behavior?

To eliminate the confusion on why `@Injectable()` decorator is needed

**Comment by micalevisk** [comment]
what about this: https://github.com/nestjs/docs.nestjs.com/pull/2481/files#diff-88ed06aab2377fc1bd6e94f641c0d518a1c45be5246dec0d2ad851eb256dcf43

**Comment by bacebu4** [comment]
Yeah, this is exactly that, haven't checked PRs before opening

Closing the issue, let's track progress in #2481 and hope it will land in the master branch :)
