### ISSUE TITLE
The use of SetMetadata custom decorators does not take effect

### ISSUE THREAD

**Issue by jackQian666** [nestjs/nest#13402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I defined a decorator using SetMetadata
As shown below
![image](https://github.com/nestjs/nest/assets/86473027/4c5cc32e-2b96-405f-9b6d-ee5bf9e6fb96)

Then I defined an AuthGuard and added the logic of using @Public() to skip the guard.
As shown below

![image](https://github.com/nestjs/nest/assets/86473027/92ab2f60-757b-49d3-8551-0e8b6924afdc)

And used the @Public() decorator in the method to generate the verification code
![image](https://github.com/nestjs/nest/assets/86473027/1e072278-04b4-4ebe-8cca-1e0d198a03de)

I found that @Public() did not take effect，Then I debugged the code，
It was found that the value of IS_PUBLIC_KEY defined in the @Public() decorator was not obtained through Reflector.
As shown below，You can see that the printed value is undefined ，According to the official documentation, this problem has occurred before
![image](https://github.com/nestjs/nest/assets/86473027/c8c4696f-0282-4358-8dc5-102645ce2581)

### Minimum reproduction code

https://github.com/jackQian666/demo

### Expected behavior

I hope that using @Public() can skip token verification

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.7

### Packages versions

{
  "name": "quan-view-server",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@fastify/static": "^7.0.2",
    "@nestjs-modules/ioredis": "^2.0.2",
    "@nestjs/cache-manager": "^2.2.2",
    "@nestjs/common": "^10.3.7",
    "@nestjs/core": "^10.0.0",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/platform-fastify": "^10.3.7",
    "@nestjs/platform-socket.io": "^10.3.7",
    "@nestjs/swagger": "^7.3.1",
    "@nestjs/typeorm": "^10.0.2",
    "@nestjs/websockets": "^10.3.7",
    "@types/lodash": "^4.17.0",
    "cache-manager": "^5.4.0",
    "cache-manager-redis-store": "^3.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "crypto-js": "^4.2.0",
    "ioredis": "^5.3.2",
    "lodash": "^4.17.21",
    "mysql2": "^3.9.3",
    "nanoid": "^3.3.7",
    "passport": "^0.7.0",
    "passport-local": "^1.0.0",
    "redis": "^3.1.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "svg-captcha": "^1.4.0",
    "typeorm": "^0.3.20"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

### Node.js version

18.19.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kangkangovo2333** [comment]
使用 this.reflector.get(
            IS_PUBLIC_KEY,
            context.getHandler()
        )

**Comment by jackQian666** [comment]
试过了，不行的
![image](https://github.com/nestjs/nest/assets/86473027/2a901b42-3c06-4b86-9408-b51c49939a45)

**Comment by jackQian666** [comment]
> 使用 this.reflector.get( IS_PUBLIC_KEY, context.getHandler() )
试过了，不行的
![image](https://github.com/nestjs/nest/assets/86473027/caafcacb-2e22-4c39-ae3c-9283f57748a8)

**Comment by jackQian666** [comment]
> 使用 this.reflector.get( IS_PUBLIC_KEY, context.getHandler() )

不知道为啥没人提，this.reflector 下面的方法我都试过了，都不行，使用 @SetMetadata() 装饰器也不行，都没法把元素数注入

**Comment by kangkangovo2333** [comment]
> > 使用 this.reflector.get( IS_PUBLIC_KEY, context.getHandler() )
> 
> 不知道为啥没人提，this.reflector 下面的方法我都试过了，都不行，使用 @SetMetadata() 装饰器也不行，都没法把元素数注入

你的context.getHandler()没调用

**Comment by jackQian666** [comment]
> > > 使用 this.reflector.get( IS_PUBLIC_KEY, context.getHandler() )
> > 
> > 
> > 不知道为啥没人提，this.reflector 下面的方法我都试过了，都不行，使用 @SetMetadata() 装饰器也不行，都没法把元素数注入
> 
> 你的context.getHandler()没调用
nen能得到类，没得到方法
![image](https://github.com/nestjs/nest/assets/86473027/a611575e-cfff-47a3-8c3e-1a822e7105f4)

**Comment by kangkangovo2333** [comment]
> > > > 使用 this.reflector.get( IS_PUBLIC_KEY, context.getHandler() )
> > > 
> > > 
> > > 不知道为啥没人提，this.reflector 下面的方法我都试过了，都不行，使用 @SetMetadata() 装饰器也不行，都没法把元素数注入
> > 
> > 
> > 你的context.getHandler()没调用
> > nen能得到类，没得到方法
> > ![image](https://private-user-images.githubusercontent.com/86473027/320184752-a611575e-cfff-47a3-8c3e-1a822e7105f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODI1MzMsIm5iZiI6MTcxMjM4MjIzMywicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODQ3NTItYTYxMTU3NWUtY2ZmZi00N2EzLThjM2UtMWE4MjJlNzEwNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OTBhMDczMzM4MDA1YmE0Mjc3ZjVjMWM0NmI1M2MzYTRmNDk0MWU0ZDUzNjQ3NmU4MjQxYmFkYzc3OTA5YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yscdVT3pzKJUhb1PHBjemjfEiD7V4UdVm9t_K0Cplo4)

![image](https://github.com/nestjs/nest/assets/102359572/cfd60d8f-5d73-4454-aecd-e65dad327469)
你这里的方法要调用

**Comment by jackQian666** [comment]
> "reflect-metadata": "^0.1.13",

调用了的，我把装饰器加到了captcha 方法上面，调用的也是captcha方法
![image](https://github.com/nestjs/nest/assets/86473027/bc48590d-59b8-4ae9-b5d0-78d755c7e71c)

**Comment by kangkangovo2333** [comment]
> > "reflect-metadata": "^0.1.13",
> 
> 调用了的，我把装饰器加到了captcha 方法上面，调用的也是captcha方法，守卫里面打印的依旧是上面的内容 ![image](https://private-user-images.githubusercontent.com/86473027/320185508-bc48590d-59b8-4ae9-b5d0-78d755c7e71c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODM0MjIsIm5iZiI6MTcxMjM4MzEyMiwicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODU1MDgtYmM0ODU5MGQtNTliOC00YWU5LWI1ZDAtNzhkNzU1YzdlNzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZTY3ZDk3MzY3OTYxYTg4ZGNmNzliYWZmZmQ1ODBlMjI3ZjUyNmQ5NDAxZWNjNjgyZWU5YjlmNDA3NzMxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxGU60gduD50iFHUDCAKRqgRKU3U8xHEg_tLsye5Ae4)

我说的是你在guard内的context.getHandler没有调用 你仔细看看

**Comment by jackQian666** [comment]
> > > "reflect-metadata": "^0.1.13",
> > 
> > 
> > 调用了的，我把装饰器加到了captcha 方法上面，调用的也是captcha方法，守卫里面打印的依旧是上面的内容 ![image](https://private-user-images.githubusercontent.com/86473027/320185508-bc48590d-59b8-4ae9-b5d0-78d755c7e71c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODM0MjIsIm5iZiI6MTcxMjM4MzEyMiwicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODU1MDgtYmM0ODU5MGQtNTliOC00YWU5LWI1ZDAtNzhkNzU1YzdlNzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZTY3ZDk3MzY3OTYxYTg4ZGNmNzliYWZmZmQ1ODBlMjI3ZjUyNmQ5NDAxZWNjNjgyZWU5YjlmNDA3NzMxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxGU60gduD50iFHUDCAKRqgRKU3U8xHEg_tLsye5Ae4)
> 
> 我说的是你在guard内的context.getHandler没有调用 你仔细看看

怎么调用呢？ 不是很理解你的意思，我的理解是把通过 context.getHandler 获取到目标方法 或者目标类，传给reflector，拿到对应的注入元数据

**Comment by kangkangovo2333** [comment]
> > > > "reflect-metadata": "^0.1.13",
> > > 
> > > 
> > > 调用了的，我把装饰器加到了captcha 方法上面，调用的也是captcha方法，守卫里面打印的依旧是上面的内容 ![image](https://private-user-images.githubusercontent.com/86473027/320185508-bc48590d-59b8-4ae9-b5d0-78d755c7e71c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODM0MjIsIm5iZiI6MTcxMjM4MzEyMiwicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODU1MDgtYmM0ODU5MGQtNTliOC00YWU5LWI1ZDAtNzhkNzU1YzdlNzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZTY3ZDk3MzY3OTYxYTg4ZGNmNzliYWZmZmQ1ODBlMjI3ZjUyNmQ5NDAxZWNjNjgyZWU5YjlmNDA3NzMxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxGU60gduD50iFHUDCAKRqgRKU3U8xHEg_tLsye5Ae4)
> > 
> > 
> > 我说的是你在guard内的context.getHandler没有调用 你仔细看看
> 
> 怎么调用呢？ 不是很理解你的意思，我的理解是把通过 context.getHandler 获取到目标方法 或者目标类，传给reflector，拿到对应的注入元数据

你看你装饰器的代码 确认在this.reflector.get()中 context.getHandler()是调用的

**Comment by jackQian666** [comment]
> > > > > "reflect-metadata": "^0.1.13",
> > > > 
> > > > 
> > > > 调用了的，我把装饰器加到了captcha 方法上面，调用的也是captcha方法，守卫里面打印的依旧是上面的内容 ![image](https://private-user-images.githubusercontent.com/86473027/320185508-bc48590d-59b8-4ae9-b5d0-78d755c7e71c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODM0MjIsIm5iZiI6MTcxMjM4MzEyMiwicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODU1MDgtYmM0ODU5MGQtNTliOC00YWU5LWI1ZDAtNzhkNzU1YzdlNzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZTY3ZDk3MzY3OTYxYTg4ZGNmNzliYWZmZmQ1ODBlMjI3ZjUyNmQ5NDAxZWNjNjgyZWU5YjlmNDA3NzMxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxGU60gduD50iFHUDCAKRqgRKU3U8xHEg_tLsye5Ae4)
> > > 
> > > 
> > > 我说的是你在guard内的context.getHandler没有调用 你仔细看看
> > 
> > 
> > 怎么调用呢？ 不是很理解你的意思，我的理解是把通过 context.getHandler 获取到目标方法 或者目标类，传给reflector，拿到对应的注入元数据
> 
> 你看你装饰器的代码 确认在this.reflector.get()中 context.getHandler()是调用的

![image](https://github.com/nestjs/nest/assets/86473027/86694315-ae50-4e67-8750-fea0a581a8c9)
这个是装饰器代码，都试过了，还是不行

**Comment by kangkangovo2333** [comment]
> > > > > > "reflect-metadata": "^0.1.13",
> > > > > 
> > > > > 
> > > > > 调用了的，我把装饰器加到了captcha 方法上面，调用的也是captcha方法，守卫里面打印的依旧是上面的内容 ![image](https://private-user-images.githubusercontent.com/86473027/320185508-bc48590d-59b8-4ae9-b5d0-78d755c7e71c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODM0MjIsIm5iZiI6MTcxMjM4MzEyMiwicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODU1MDgtYmM0ODU5MGQtNTliOC00YWU5LWI1ZDAtNzhkNzU1YzdlNzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZTY3ZDk3MzY3OTYxYTg4ZGNmNzliYWZmZmQ1ODBlMjI3ZjUyNmQ5NDAxZWNjNjgyZWU5YjlmNDA3NzMxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxGU60gduD50iFHUDCAKRqgRKU3U8xHEg_tLsye5Ae4)
> > > > 
> > > > 
> > > > 我说的是你在guard内的context.getHandler没有调用 你仔细看看
> > > 
> > > 
> > > 怎么调用呢？ 不是很理解你的意思，我的理解是把通过 context.getHandler 获取到目标方法 或者目标类，传给reflector，拿到对应的注入元数据
> > 
> > 
> > 你看你装饰器的代码 确认在this.reflector.get()中 context.getHandler()是调用的
> 
> ![image](https://private-user-images.githubusercontent.com/86473027/320186998-86694315-ae50-4e67-8750-fea0a581a8c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODUwMTEsIm5iZiI6MTcxMjM4NDcxMSwicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODY5OTgtODY2OTQzMTUtYWU1MC00ZTY3LTg3NTAtZmVhMGE1ODFhOGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA2MjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMTIzM2Y0Mzc2M2JhOWM4YmUyMTgyMTE2MDBiNzU5OGQ1ZmNhZGQyOGM1Y2Y4NWQzZGE0YTUzNjY2ZDg0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gvL3IbDDtj-SEViDF-ihUiMVHAqWkyIAxEMFMCp7PBE) 这个是装饰器代码，都试过了，还是不行

说错了是守卫里

**Comment by jackQian666** [comment]
> > > > > > > "reflect-metadata": "^0.1.13",
> > > > > > 
> > > > > > 
> > > > > > 调用了的，我把装饰器加到了captcha 方法上面，调用的也是captcha方法，守卫里面打印的依旧是上面的内容 ![image](https://private-user-images.githubusercontent.com/86473027/320185508-bc48590d-59b8-4ae9-b5d0-78d755c7e71c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODM0MjIsIm5iZiI6MTcxMjM4MzEyMiwicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODU1MDgtYmM0ODU5MGQtNTliOC00YWU5LWI1ZDAtNzhkNzU1YzdlNzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZTY3ZDk3MzY3OTYxYTg4ZGNmNzliYWZmZmQ1ODBlMjI3ZjUyNmQ5NDAxZWNjNjgyZWU5YjlmNDA3NzMxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxGU60gduD50iFHUDCAKRqgRKU3U8xHEg_tLsye5Ae4)
> > > > > 
> > > > > 
> > > > > 我说的是你在guard内的context.getHandler没有调用 你仔细看看
> > > > 
> > > > 
> > > > 怎么调用呢？ 不是很理解你的意思，我的理解是把通过 context.getHandler 获取到目标方法 或者目标类，传给reflector，拿到对应的注入元数据
> > > 
> > > 
> > > 你看你装饰器的代码 确认在this.reflector.get()中 context.getHandler()是调用的
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/86473027/320186998-86694315-ae50-4e67-8750-fea0a581a8c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODUwMTEsIm5iZiI6MTcxMjM4NDcxMSwicGF0aCI6Ii84NjQ3MzAyNy8zMjAxODY5OTgtODY2OTQzMTUtYWU1MC00ZTY3LTg3NTAtZmVhMGE1ODFhOGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA2MjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMTIzM2Y0Mzc2M2JhOWM4YmUyMTgyMTE2MDBiNzU5OGQ1ZmNhZGQyOGM1Y2Y4NWQzZGE0YTUzNjY2ZDg0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gvL3IbDDtj-SEViDF-ihUiMVHAqWkyIAxEMFMCp7PBE) 这个是装饰器代码，都试过了，还是不行
> 
> 说错了是守卫里

大意了，应该是这种，jias加上括号才行，感谢感谢
![image](https://github.com/nestjs/nest/assets/86473027/9042166c-5209-486b-8e3c-6001154bb907)
