### ISSUE TITLE
NestJS HttpException class returns success status when status is undefined

### ISSUE THREAD

**Issue by Duarte007** [nestjs/nest#13404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In this example, when the HttpException class is instantiated in this way (with an undefined status parameter), an exception is thrown with an undefined status and when going up the application layers, instead of an error status being returned, the default status of the http method is returned in the endpoint response (status 200 in this case exemplified in the reproduction code)

```
@Injectable()
export class TestService {

 async test() {
    try {
      throw new BadRequestException('Test Error');
    } catch (error) {
      throw new HttpException(error, undefined);
    }
  }

}
```

### Minimum reproduction code

https://github.com/Duarte007/nestjs-exception-handler-test

### Steps to reproduce

1. yarn
2. yarn start:dev
3. access swagger in http://localhost:3000/api
4. execute the GET

### Expected behavior

In my opinion, it is extremely dangerous for an exception to be returned with a success status. By default, perhaps wouldn't it be better to return status 500 when it is not defined in the HttpException parameter?

I was trying to throw an exception and was surprised that an error could be returned as a success.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/swagger": "^7.3.1",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  }
```

### Node.js version

v18.19.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
that's expected as you're ignoring the type definition of `HttpException`'s constructor:

https://github.com/nestjs/nest/blob/8b4dbb30909be86290d01da54205ab4bf081ab46/packages/common/exceptions/http.exception.ts#L60-L63

note that `status` is expected to be `number`, isn't optional. But since you've disabled the `strictNullChecks` option, you aren't getting any error at compiler time.

**Comment by Duarte007** [comment]
Thanks for the answer @micalevisk
I understood your comment, but I updated the reproduction code repository so that the `typescript` would not give an error and this behavior would still happen.

Once is it possible to construct the code in such a way that there is the possibility of an `undefined` being passed as a parameter, such as using an `any` variable, something that, although contraindicated, is quite common in typescript projects, I think it does It makes sense to have a safety lock for this scenario.

I understand that the class constructor explicitly asks for a number in the status, but since it is possible to enter this flow, I believe it would be safer, either to put a default error status, like 500, or to protect the class with some validation in the constructor that does not accept the undefined status parameter.

The scenario of an exception, due to some carelessness, being ignored, can be worrying. And I still think that additional validation would give nestjs more robustness and resilience

**Comment by micalevisk** [comment]
but we'd have to starting adding runtime validations everywhere in the codebase just because you are not following the API contract. In this case, the contract is well-defined with typescript types.

But feel free to open a new issue as a _feature request_.

**Comment by micalevisk** [comment]
as an example (maybe not the best) that aligns with my expectation:

```ts
const express = require('express')
const app = express()
const port = 3000

app.get(123, (req, res) => {
  res.send('Hello World!')
})
```

![image](https://github.com/nestjs/nest/assets/13461315/984d8a44-3ae7-44e7-9da4-53614d1dafea)

note that the docs shows the API contract and we're ignoring it. When running that app, you'll see no errors.
