### ISSUE TITLE
[chore] drop dev. dependencies that are leading to errors on running `npm install` in this repo

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#13432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

we can't use `npm install` after cloning https://github.com/nestjs/nest repo due to this error:

![image](https://github.com/nestjs/nest/assets/13461315/c9ba6e57-09b6-41e8-9067-6899fbf792ef)

which is related with legacy packages:
- `commitlint-circle` -- the last update was 6 years ago
- `merge-graphql-schemas` -- this [has been deprecated](https://www.npmjs.com/package/merge-graphql-schemas)

After removing them from our deps list and after resolving the PR https://github.com/nestjs/graphql/pull/3181 (to support the latest `ts-morph` on `@nestjs/graphql`), `npm install` will work as expected.

I didn't fully understand why those dependencies are needed. So if they are, ignore this issue.

```bash
git clone git@github.com:nestjs/nest.git
cd nest
npm i
## see the error
```

### Expected behavior

Install the deps without the need to use the flag `--legacy-peer-deps`

https://github.com/nestjs/nest/blob/6f119a7fdd46718327d3e1f4cb0bdc5d0ac7531b/.circleci/config.yml#L32

**Comment by Tony133** [comment]
I get these errors:
<img width="1062" alt="error-npm-install" src="https://github.com/nestjs/nest/assets/11542387/e35e8cd2-7c46-45f9-b97e-76e95b9be81e">

**Comment by Tony133** [comment]
Wouldn't it be better to move graphql integration tests to the repository dedicated to the `@nestjs/graphql` module?

**Comment by kamilmysliwiec** [comment]
> Wouldn't it be better to move graphql integration tests to the repository dedicated to the @nestjs/graphql module?

Having them here is necessary to ensure that we don't break this package (and it is essential for the ecosystem) while making changes to the core.

So what do we need to do in this repository in order to fix this issue (apart from merging PRs in the graphql repo)?

**Comment by Tony133** [comment]
> > Wouldn't it be better to move graphql integration tests to the repository dedicated to the @nestjs/graphql module?
> 
> Having them here is necessary to ensure that we don't break this package (and it is essential for the ecosystem) while making changes to the core.

Ok 👍, thank you for your reply 

> 
> So what do we need to do in this repository in order to fix this issue (apart from merging PRs in the graphql repo)?

Can no longer run `npm install`, gives error concerning dependencies  😄 ( see screenshot ) at least i see these errors in the terminal 🙂, maybe it is reflect-metadata that is at version `0.2.2` (see here: [https://github.com/nestjs/nest/blob/master/package.json#L73)](https://github.com/nestjs/nest/blob/master/package.json#L73), and in the other packages is at `0.2.1`? 


<img width="1312" alt="error-npm-install" src="https://github.com/nestjs/nest/assets/11542387/ccedf379-4403-4913-8045-3b8420dcfda2">

**Comment by micalevisk** [comment]
what works without merging that PR:

```bash
vim package.json # to remove commitlint-circle merge-graphql-schemas and change ts-morph version to 21.x
rm package-lock.json
npm i
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR removing both packages @micalevisk?
