### ISSUE TITLE
Support for Multiple HTTP Methods on the function

### ISSUE THREAD

**Issue by reselvakumar** [nestjs/nest#13433]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Now we have to define one HTTP method per function. so i have to do something like this 

```
 @Post('filter')
  async filterData(@User() user: any, @Query() params: any, @Body() filter?: any) {
    return 'Filtered data';
  }

  @Get()
  async getAllData(@User() user: any, @Query() params: any) {
    return this.filterData(user, params);
  }
```

### Describe the solution you'd like

if we have something like this

```
@Post('filter')
@Get()
  async filterData(@User() user: any, @Query() params: any, @Body() filter?: any) {
    return 'Filtered data';
  }
```

Or something like this

```
 @Multi({ path: '', method: RequestMethod.GET },
        { path: 'filter', method: RequestMethod.POST })
  async filterData(@User() user: any, @Query() params: any, @Body() filter?: any) {
    return 'Filtered data';
  }
```

**Comment by micalevisk** [comment]
I like the ideia of supporting

```ts
@Post('filter')
@Get()
  async filterData(@User() user: any, @Query() params: any, @Body() filter?: any) {
    return 'Filtered data';
  }
```

because it's the intuitive way. But overusing it would be very odd to follow.

**Comment by KostyaTretyak** [comment]
Apparently, it will be problematic, for example, for building OpenAPI documentation. How would you do this for this code?

```ts
@Post('filter')
@Get()
  async filterData(@User() user: any, @Query() params: any, @Body() filter?: any) {
    return 'Filtered data';
  }
```

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future. You should just move the shared logic to another class (service) and call the corresponding method from the controller's route.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
