### ISSUE TITLE
 Nest can't resolve dependencies of the DiscoveryService (?). Please make sure that the argument ModulesContainer at index [0]

### ISSUE THREAD

**Issue by r-devops-github** [nestjs/nest#13441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi guys,

We are attempting to create an internal NestJS sdk for our applications. The trouble we are facing is when we are attempting to develop the sdk locally, and installing the new sdk build into our local applications. The error that occurs is 

```
[Nest] 9552  - 15/04/2024, 2:14:32 pm   ERROR [ExceptionHandler] Nest can't resolve dependencies of the DiscoveryService (?). Please make sure that the argument ModulesContainer at index [0] is available 
in the DiscoveryModule context.

Potential solutions:
- Is DiscoveryModule a valid NestJS module?
- If ModulesContainer is a provider, is it part of the current DiscoveryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within DiscoveryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })

Error: Nest can't resolve dependencies of the DiscoveryService (?). Please make sure that the argument ModulesContainer at index [0] is available in the DiscoveryModule context.

Potential solutions:
- Is DiscoveryModule a valid NestJS module?
- If ModulesContainer is a provider, is it part of the current DiscoveryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within DiscoveryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })
```

We have checked the versions of the shared sdk, and the applications. And, they all have the exact @nestjs/core version 10.0.0. The module that is experiencing the issue is designed as such:

```javascript
/**
 * @publicApi
 */
@Module({
 imports: [DiscoveryModule],
})
export class SharedModule implements OnModuleInit, NestModule {
  constructor(private readonly discoveryService: DiscoveryService) { }
}
``` 

Any advice on how we can move forward would be hugely appreciated.

### Minimum reproduction code

(Please refer to the above code)

### Steps to reproduce

1. Build shared NestJS sdk `npm run build`
2. Update the NestJS application package.json "@shared/nestjs": "file:/../shared-nestjs/dist", then install `npm i`
3. Run the application `npm run start:dev`

These steps will produce the following.

```
[Nest] 9552  - 15/04/2024, 2:14:32 pm   ERROR [ExceptionHandler] Nest can't resolve dependencies of the DiscoveryService (?). Please make sure that the argument ModulesContainer at index [0] is available 
in the DiscoveryModule context.

Potential solutions:
- Is DiscoveryModule a valid NestJS module?
- If ModulesContainer is a provider, is it part of the current DiscoveryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within DiscoveryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })

Error: Nest can't resolve dependencies of the DiscoveryService (?). Please make sure that the argument ModulesContainer at index [0] is available in the DiscoveryModule context.

Potential solutions:
- Is DiscoveryModule a valid NestJS module?
- If ModulesContainer is a provider, is it part of the current DiscoveryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within DiscoveryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })
```

### Expected behavior

Application should run as expected

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
"@nestjs/common": "10.0.0",
"@nestjs/config": "3.2.0",
"@nestjs/core": "10.0.0",
```

### Node.js version

18.19.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by r-devops-github** [comment]
We've set the following in our shared library (package.json)

  "peerDependencies": {
    "@nestjs/axios": "3.0.0",
    "@nestjs/common": "10.0.0",
    "@nestjs/config": "3.1.1",
    "@nestjs/core": "10.0.0"
  },
  
  But the issue still persists. We have cleared out everything (node_modules, cache) just in case

**Comment by kamilmysliwiec** [comment]
> Update the NestJS application package.json "@shared/nestjs": "file:/../shared-nestjs/dist", then install npm i

If you're referencing your libs like this ☝️, then the `shared-nestjs` must not have the `@nestjs/core` installed in the local `node_modules` directory.

**Comment by KostyaTretyak** [comment]
@r-devops-github, maybe you just forgot to add the `@Injectable()` decorator before the `DiscoveryService`.

**Comment by aanosh** [comment]
@KostyaTretyak @kamilmysliwiec I have a similar problem with building sdk for nestjs app
`export class AuthModule {
  static register(clientSettings?: ClientSettings): DynamicModule {
    const providers: Provider[] = []

    if (clientSettings) {
      const clientProvider = {
        provide: AuthService,
        useFactory: () => new AuthService(clientSettings),
      }
      providers.push(clientProvider)
    }

    return {
      module: AuthModule,
      providers,
      exports: providers,
      global: true,
    }
  }
}`
and I want to inject to custom guard:
`@Injectable()
export class PartialAccessGuard implements CanActivate {
  constructor (reflector: Reflector, private readonly authClient: AuthService) {
    super(reflector)
  }

  public async canActivate (context: ExecutionContext): Promise<boolean> {}
  }
  `
  
 this code works fine when it a part of app sources. But if I move it to external package, AuthService is not resolved for PartialAccessGuard (added `@inject(AuthService)` no effect) 
 
 also added to sdk package.json
 `  "peerDependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0"
  },`

**Comment by KostyaTretyak** [comment]
@aanosh, your example is missing the `@Module()` decorator before the `AuthModule`. Maybe you forgot to add it in your application as well?

**Comment by aanosh** [comment]
@KostyaTretyak sorry I haven't copied it:
```
@Module({
  imports: [PassportModule],
})
```

Let me note that the problem occurs only when I add this sdk as a separate package and load it with npm.

**Comment by micalevisk** [comment]
I believe that it will be really hard to us to understand the issue without a proper reproduction code.

Because even if you're using the peer deps correctly, depending on how you're developing the SDK, you'll see errors like that due to JS realms. That's why tools like [Yalc](https://github.com/wclr/yalc) exists


## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by r-devops-github** [comment]
Hey guys,

For a potential code reproduction, we followed the steps detailed here https://dev.to/nestjs/publishing-nestjs-packages-with-npm-21fm

The only changes we had to make to the code base detailed, was updating the nestjs packages. We first built the sdk dependency to not use the DiscoveryModule anywhere in the code base. Installed the package into an application and all went well. No errors thrown. The next step was we created a Test2Module which does the exact same steps as our shared library by importing the DiscoveryModule. We installed into our application, imported the Test2Module, and we have the issue detailed in the ticket. Please see screenshot.
![Capture](https://github.com/nestjs/nest/assets/117138148/d6d10ef7-5c1b-4266-a615-ae2d1b0767df)

Any advice would be hugely appreciated

**Comment by micalevisk** [comment]
I can see that you're using `file` to link the lib. Which can lead to such errors, depending on how you're using the lib

Please run `npm ls @nestjs/core` from your app side and share the output with us

**Comment by kamilmysliwiec** [comment]
I have already explained how to fix this issue above.

> Update the NestJS application package.json "@shared/nestjs": "file:/../shared-nestjs/dist", then install npm i

If you're referencing your libs like this ☝️, then the shared-nestjs must not have the @nestjs/core installed in the local node_modules directory (= otherwise you have 2 copies of the package)

Alternatively, you can use `file:/../shared-nestjs/node_modules/@nestjs/core` to also temporarily mount the local version of `@nestjs/core` so both the host application and your library use the same copy.

This has been discussed several times in the past. From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
