### ISSUE TITLE
I have a question about dependency injection and module import

### ISSUE THREAD

**Issue by sugar258596** [nestjs/nest#13442]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There are four modules: a,b,c,d;
Module b is injected into module a, and module c is introduced (a uses the method in c), module d imports module a.
Why do I have to import b and c in module d?? , can not run without importing,
(The English translation may not be accurate, please understand)

### Describe the solution you'd like

*

### Teachability, documentation, adoption, migration strategy

*

### What is the motivation / use case for changing the behavior?

*

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
