### ISSUE TITLE
Cannot read properties of undefined (reading 'constructor') 

### ISSUE THREAD

**Issue by joao-moonward** [nestjs/nest#13440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I encountered an error in my KnexJS query builder return at the end of the user's request.
```
Cannot read properties of undefined (reading 'constructor)
```

My object is like this:
```
{
   data: [{}, {},...],
   pagination: {}
}
```

During debugging, I discovered that the error might be caused by the `transform` function mapping the `data` array.

```ts
            if (!targetType && value.constructor !== Object /* && TransformationType === TransformationType.CLASS_TO_PLAIN*/)
                if (!Array.isArray(value) && value.constructor === Array) {
                    // Somebody attempts to convert special Array like object to Array, eg:
                    // const evilObject = { '100000000': '100000000', __proto__: [] };
                    // This could be used to cause Denial-of-service attack so we don't allow it.
                    // See prevent-array-bomb.spec.ts for more details.
                }
                else {
                    // We are good we can use the built-in constructor
                    targetType = value.constructor;
                }
```
After executing `targetType = value.constructor;`, the value of it is `{}`, which is not a constructor. Then, inside the `getAncestors` function, it has this code:

```ts
            for (let baseClass = Object.getPrototypeOf(target.prototype.constructor); typeof baseClass.prototype !== 'undefined'; baseClass = Object.getPrototypeOf(baseClass.prototype.constructor)) {
                ancestors.push(baseClass);
            }
```

`target.prototype.constructor`  is an undefined access.

### Minimum reproduction code

https://github.com/joaovitorteixeira/nestjs-knex-error

### Expected behavior

I'm not sure if I set something up incorrectly, but I expect the response from my service to go to the client without any exceptions.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

knexjs knex-paginate

### NestJS version

10.3.7

### Packages versions

```json
    "@nestjs/common": "^10.3.7",
    "@nestjs/config": "^3.2.2",
    "@nestjs/core": "^10.3.7",
```

### Node.js version

v18.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I'll provide a repository once I get home.

**Comment by micalevisk** [comment]
looks like your repository is private

![image](https://github.com/nestjs/nest/assets/13461315/2f6055ce-6828-4740-ba8f-1978d5f43fdf)

**Comment by joao-moonward** [comment]
@micalevisk Sorry, mate. I'll make it public as soon as possible and let you know.
