### ISSUE TITLE
TCP.onStreamRead (node:internal/stream_base_commons:217:20)

### ISSUE THREAD

**Issue by cuikaipeng** [nestjs/nest#13452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
 ELIFECYCLE  Command failed with exit code 1.
<img width="598" alt="iShot_2024-04-16_13 47 43" src="https://github.com/nestjs/nest/assets/78460423/3a2d8137-c2b2-43b4-bec7-710f575a622b">

### Minimum reproduction code

x

### Expected behavior

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
 ELIFECYCLE  Command failed with exit code 1.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.7

### Packages versions

```json

```

### Node.js version

20.12.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.

**Comment by lenran659** [comment]
I have the same problem.
