### ISSUE TITLE
Supply time to TypeOrmLogger.logQuery()

### ISSUE THREAD

**Issue by sscots** [nestjs/nest#13451]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This is to help analyze and optimize the aggregation of query time.

### Describe the solution you'd like

I'd like to supply the time to the TypeOrmLogger.logQuery() function just like it is done for the TypeOrmLogger.logSlowQuery()

### Teachability, documentation, adoption, migration strategy

Used just like the TypeOrmLogger.logSlowQuery()

### What is the motivation / use case for changing the behavior?

I'd like to be able to see the time of all my queries so I can see and improve queries that could use some improvement but may not show up in the slow query log. For example, say I am running a query that is .5 seconds. That's not too slow but what if I'm running 10 queries at that rate. That's 5 seconds of querying. If I can get it down to .25 seconds I've only got 2.5 seconds of querying. I want to be able to see this across all my queries so I can know which ones to work on.

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
