### ISSUE TITLE
grpc microservice stops listening to requests after version 10.3.3 (needs peer dependency)

### ISSUE THREAD

**Issue by bfelds** [nestjs/nest#13466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Between v10.3.3 and v10.3.4 our grpc microservice stopped responding to messages. This was likely because https://github.com/nestjs/nest/pull/13283 was introduced, which depends on grpc/grpc-js:^1.10.0 (https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.10.0). A minimum peer dependency should be added for clarity

### Minimum reproduction code

canpostifneeded

### Steps to reproduce

Create microservice with grpc/grpc-js:^1.9.7 and nestjs/microservices:10.3.4 . 

### Expected behavior

Expect that npm/pnpm mention the unmet peer dependency introduced in 10.3.4. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

grpc/grpc-js

### Packages versions

```json
"dependencies": {
    "@grpc/grpc-js": "^1.9.7",
    "@grpc/proto-loader": "^0.7.10",
    "@nestjs/common": "^10.3.7",
    "@nestjs/config": "^3.2.2",
    "@nestjs/core": "^10.3.7",
    "@nestjs/microservices": "10.3.4",
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in 10.3.8
