### ISSUE TITLE
Feature Request: Support for Bun.js

### ISSUE THREAD

**Issue by 1096396089** [nestjs/nest#13476]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Will Bunjs be supported in the future?

### Describe the solution you'd like

I would like to propose that NestJS adds support for Bun.js as an alternative to Node.js. Bun.js has been gaining popularity due to its high performance and built-in package manager, which could benefit NestJS users looking for more efficient server-side solutions.

### Teachability, documentation, adoption, migration strategy

I would like to propose that NestJS adds support for Bun.js as an alternative to Node.js. Bun.js has been gaining popularity due to its high performance and built-in package manager, which could benefit NestJS users looking for more efficient server-side solutions.

### What is the motivation / use case for changing the behavior?

I would like to propose that NestJS adds support for Bun.js as an alternative to Node.js. Bun.js has been gaining popularity due to its high performance and built-in package manager, which could benefit NestJS users looking for more efficient server-side solutions.

**Comment by micalevisk** [comment]
There's a whole thread on our discord about this: https://discord.com/channels/520622812742811698/1150960341107351562

It's not a matter of nestjs supporting bun. It's the opposite. And it works already (sometimes). See https://github.com/oven-sh/bun/issues/1641#issuecomment-1821912213

**Comment by elovin** [comment]
@micalevisk 
> It's not a matter of nestjs supporting bun. It's the opposite.

I thought bun was aiming for a 100% compatibility with Node.js eventually ? 
If that is the case it should work with nestjs applications even if nestjs does not officially support it.

>  And it works already (sometimes). See https://github.com/oven-sh/bun/issues/1641#issuecomment-1821912213

It only works when decorators, one of the most important nestjs features, is not used. 
There are just too many issues with bun and typescripts `emitDecoratorMetadata` for any larger / serous nestjs application to work.

**Comment by elovin** [comment]
@micalevisk sorry, I somehow thought I'm writing this on the bun page ....
