### ISSUE TITLE
Multi-tenant app fail on first non durable tree request

### ISSUE THREAD

**Issue by DylanVeldra** [nestjs/nest#13477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

For the context, the app is a multi-tenants, with a configDb service being instantiate for each tenant when needed.

The issue manifest when the first request on a tenant isn't on a `isTreeDurable === true`

I found how to patch it and I also found a work around.

The patch:
`packages/core/router/router-explorer.ts` line 421 replace 

`const requestProviderValue = isTreeDurable ? contextId.payload : request;`

by 

`const requestProviderValue = isTreeDurable ? contextId.payload : Object.assign(request, contextId.payload);`

same for `packages/core/middleware/middleware-module.ts` line 349

The workaround is commented in the reproduction repo.
I would like to know if the use of the work around is safe or the patch should be applied ? 

### Minimum reproduction code

https://github.com/DylanVeldra/nest-multitenant

### Steps to reproduce

This will work:
`npm i
`
`npm start
`
```
curl --location 'localhost:8080/foo' \
--header 'x-tenant-id: BAR'
```

```
curl --location 'localhost:8080/kaz' \
--header 'x-tenant-id: BAR'
```

This wont work if you change the order of curl request like this:

`npm i
`
`npm start
`

```
curl --location 'localhost:8080/kaz' \
--header 'x-tenant-id: BAR'
```

```
curl --location 'localhost:8080/foo' \
--header 'x-tenant-id: BAR'
```

### Expected behavior

Both orders should work, no matter if the first request is a `isTreeDurable` or not

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.8

### Packages versions

```json

{
  "name": "nest-multitenant",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "nest build",
    "dev": "npm run build && nest start --watch",
    "start": "npm run build && nest start --watch"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nestjs/common": "^10.3.8",
    "@nestjs/core": "^10.3.8",
    "@nestjs/platform-express": "^10.3.8",
    "express": "^4.19.2"
  },
  "devDependencies": {
    "@types/express": "^4.17.21"
  }
}

```

### Node.js version

21.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Please let me know if you need more informations,

Have good day 👋

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13485
