### ISSUE TITLE
LoggerService transforms the instance of Error when controller throws an Error

### ISSUE THREAD

**Issue by eliasjnior** [nestjs/nest#13482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you create a `CustomLogger` that implements the `LoggerService` to be used as a global logger, is expected that the instances of the objects don't change when logging.

But if you throw an error in a controller, it will be logged by this `CustomLogger`, but the problem is that we lose the instance.

Example:
```ts
// app.controller.ts
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new Error('custom error');
  }
}
```

And the logger:
```ts
// custom-logger.ts
import { LogLevel, LoggerService } from '@nestjs/common';

export class CustomLogger implements LoggerService {
  log(message: any, ...optionalParams: any[]) {
    console.log('CustomLogger.log', message, ...optionalParams);
  }

  error(message: any, ...optionalParams: any[]) {
    console.dir(message);
    console.dir(optionalParams);
    console.log('CustomLogger.error', message, ...optionalParams);
    console.log('message', message instanceof Error);
    console.log('optionalParams', optionalParams instanceof Error);
    console.log('optionalParams[0]', optionalParams[0] instanceof Error);
  }

  warn(message: any, ...optionalParams: any[]) {
    console.log('CustomLogger.warn', message, ...optionalParams);
  }

  debug?(message: any, ...optionalParams: any[]) {
    console.log('CustomLogger.debug', message, ...optionalParams);
  }

  verbose?(message: any, ...optionalParams: any[]) {
    console.log('CustomLogger.verbose', message, ...optionalParams);
  }

  fatal?(message: any, ...optionalParams: any[]) {
    console.log('CustomLogger.fatal', message, ...optionalParams);
  }

  setLogLevels?(levels: LogLevel[]) {
    console.log('CustomLogger.setLogLevels', levels);
  }
}
```

And the main:
```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { CustomLogger } from './custom-logger';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    bufferLogs: true,
    logger: new CustomLogger(),
  });

  await app.listen(3000);
}
bootstrap();
```

### Minimum reproduction code

https://codesandbox.io/p/devbox/vigorous-bassi-c7jgjh

### Steps to reproduce

Open the default port to receive an error and look at the console logs

### Expected behavior

Expected to `optionalParams[0]` to be instance of `Error`, but it's not

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "nest",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

20.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by sinapirani** [comment]
See packages/core/exceptions/base-exception-filter.ts in the NestJS source code:

  public handleUnknownError(
    exception: T,
    host: ArgumentsHost,
    applicationRef: AbstractHttpAdapter | HttpServer,
  ) {
    const body = this.isHttpError(exception)
      ? {
          statusCode: exception.statusCode,
          message: exception.message,
        }
      : {
          statusCode: HttpStatus.INTERNAL_SERVER_ERROR,
          message: MESSAGES.UNKNOWN_EXCEPTION_MESSAGE,
        };

    const response = host.getArgByIndex(1);
    if (!applicationRef.isHeadersSent(response)) {
      applicationRef.reply(response, body, body.statusCode);
    } else {
      applicationRef.end(response);
    }

    if (this.isExceptionObject(exception)) {
      return BaseExceptionFilter.logger.error(
        exception.message,
        exception.stack,
      );
    }
    return BaseExceptionFilter.logger.error(exception);
  }

  public isExceptionObject(err: any): err is Error {
    return isObject(err) && !!(err as Error).message;
  }


If your error is an instance of Error, then the error logs a concatenation of the error message and stack, not the Error object itself.

**Comment by eliasjnior** [comment]
@sinapirani that means we need to have our own filter if we want to get the Error object 🤔

Should we really rely on that? For me, many people want to use their custom logger (like Winston, Pino, etc) and they have their way to parse the error logs. That means if they want to catch this logs, they need to implements `LoggerService` + `NestInterceptor` or an exception filter?

My current solution was to build something like this:

```ts
@Injectable()
export class ErrorInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
    return next.handle().pipe(
      catchError((error) => {
        logger.error(error);

        return throwError(() => {
          if (error instanceof HttpException) {
            return error;
          }

          return new HttpException(
            {
              statusCode: 500,
              message: 'Internal server error',
            },
            500,
            { cause: error },
          );
        });
      }),
    );
  }
}
```

**Comment by kamilmysliwiec** [comment]
That's the expected behavior.

From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
