### ISSUE TITLE
Not sure if it is bug or feature request, nest middleware in jest runs before any other express middleware

### ISSUE THREAD

**Issue by jacobbogers** [nestjs/nest#13484]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello, nest middleware runs before any middleware [issue 3148][10]

But since we use `Test.createTestingModule`  and `createNestApplication`  how do we implement the workaround mentioned in [issue 3148][10]

```typescript
async function createTestModule(loggerMock: ILoggerService) {
    const moduleRef: TestingModule = await Test.createTestingModule({
        imports: [
            ConfigModule.forRoot({
                load: [mockConfig],
            }),
            BusinessOrderModule,
        ],
    })
        .overrideProvider(ILOGGER_SERVICE)
        .useValue(loggerMock)
        .compile();
   
    const app = moduleRef.createNestApplication();
    const loggerMiddleware = new LoggerMiddleware();
    
    // NOTE:
    // this will make the loggerMiddleware run before any other middleware in express (like body parser)
    app.use(loggerMiddleware.use.bind(loggerMiddleware));
    return { app };
}
```

[10]: https://github.com/nestjs/nest/issues/3148

### Describe the solution you'd like

For `createNestApplication` to have implement `"NestModule.configure"` contract, so we can use nestjs middleware properly

### Teachability, documentation, adoption, migration strategy

so integration test can have fool fidelity with production code

### What is the motivation / use case for changing the behavior?

so integration test can have fool fidelity with production code

**Comment by micalevisk** [comment]
I guess you just need to write a module to register that middleware and put it in that `imports` array of your testing module

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
