### ISSUE TITLE
Devtools with microservices: Error: listen EADDRINUSE: address already in use :::8000

### ISSUE THREAD

**Issue by sjacq** [nestjs/nest#13486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When an app is set to serve as a microservice as well, Devtools tries to allocate / use the port twice, preventing the app from starting. 

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-gzpmcr?file=src%2Fmain.ts

### Steps to reproduce

Display the browser console and start the StackBlitz demo. 

If you replace the return 8000 by a random integer (eg between 8000 and 8999) you'll see the 2 ports allocated. 

### Expected behavior

Devtools should start only once for the NestJS App.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [x] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [x] Other (see below)

### Other package

NestJS Devtools

### NestJS version

10.3.8

### Packages versions

```
"@nestjs/common": "^10.3.8",
"@nestjs/config": "^3.2.2",
"@nestjs/core": "^10.3.8",
"@nestjs/devtools-integration": "^0.1.6",
"@nestjs/microservices": "^10.3.8",
"@nestjs/platform-express": "^10.3.8",
```

### Node.js version

21.7.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I guess that's up to you to change the default port, as you did already here

![image](https://github.com/nestjs/nest/assets/13461315/bd89db10-2bdc-4c20-9e3b-f727a028ceaf)

**Comment by sjacq** [comment]
> I guess that's up to you to change the default port (8000), as you did already here
> 
> ![image](https://private-user-images.githubusercontent.com/13461315/324982487-bd89db10-2bdc-4c20-9e3b-f727a028ceaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDM3NjcsIm5iZiI6MTcxMzkwMzQ2NywicGF0aCI6Ii8xMzQ2MTMxNS8zMjQ5ODI0ODctYmQ4OWRiMTAtMmJkYy00YzIwLTllM2ItZjcyN2EwMjhjZWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDIwMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZDVhYjY4MDljYjU0OGVkZTgwMjAzOWY3YmVlY2MzZmM3NzY0Mjc1OWNkNzFhZjhlM2UwNDVlZmI3ZDQ2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5jULZCgIvsJLNQL3XS6FDKmlX9XoBSfNDi3qsfKEal0)

Even if you change the port, it will still try to allocate it twice. 

- If you remove the microservice, that works
- If you keep the microservice and instead of returning 8000, you return ```randomInt(8000, 8999)```, you'll see in the console that 2 ports are allocated.

Obvisouly, we'd like only one port, so we know which one and can use it in the devtools portal.

**Comment by micalevisk** [comment]
got it

not sure what is the desired nor the best behavior but I see that that happens because you're using the same root module (`AppModule`) twice, and so the dev tools module

![image](https://github.com/nestjs/nest/assets/13461315/27245231-9ee3-4904-bc1d-08efcee0d182)

**Comment by sjacq** [comment]
My bad ! Stupid mistake.

Trying to set up a hybrid application, so microservice should have been defined using ```app.connectMicroservice({})``` and not ``` createMicroservice```, which as you pointed out injects twice the app.module.ts

Sorry about that. Case closed.

Thanks for the reactivity.
