### ISSUE TITLE
Easy way to compose ORed validators

### ISSUE THREAD

**Issue by JensRantil** [nestjs/nest#13483]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am validating that a string is either a MongoId or a UUID. I had to implement my own validator for this:
```typescript
import {
  ValidatorConstraint,
  ValidatorConstraintInterface,
  ValidationOptions,
  registerDecorator,
  isUUID,
  isMongoId,
} from 'class-validator';

@ValidatorConstraint()
export class IsUUIDOrMongoIdConstraint implements ValidatorConstraintInterface {
  validate(text: string): boolean {
    return isUUID(text) || isMongoId(text);
  }

  defaultMessage(): string {
    return 'Text ($value) must be a UUID or a MongoId';
  }
}

export function IsUUIDOrMongoId(validationOptions?: ValidationOptions) {
  return function (object: Object, propertyName: string) {
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [],
      validator: IsUUIDOrMongoIdConstraint,
    });
  };
}
```

A workaround is obviously also a somewhat complex RegExp, but that doesn't work in all cases where you want to compose different validators.

### Describe the solution you'd like

Dream scenario would be to to be able to compose different validators, similar to [how `applyDecorators(...)` works](https://docs.nestjs.com/custom-decorators#decorator-composition). I am thinking of something like this:
```typescript
import ...

export class MyOwnDto {
  @ValidateOr(
    IsUUID(),
    IsMongoId(),
  )
  readonly myProperty: string;
}
```
Or something like this:
```typescript
import { applyValidators } from '@nestjs/common';

export function IsUUIDOrMongoId() {
  return applyValidators(
    IsUUID(),
    IsMongoId(),
  );
}
```

### Teachability, documentation, adoption, migration strategy

See the described proposed solution(s) above.

### What is the motivation / use case for changing the behavior?

To make it easier to use composition when describing different cases that should be composed using OR (`||`) to a new validator.

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the class-validator library
