### ISSUE TITLE
Problem with File upload in Swagger

### ISSUE THREAD

**Issue by chertik77** [nestjs/nest#13508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm not able to see input for file choosing in swagger. Look at the images below, maybe something slipped off my mind.

![image](https://github.com/nestjs/nest/assets/129002577/e1b3e8bb-078d-49c0-915a-3d3f7d2864b9)

![image](https://github.com/nestjs/nest/assets/129002577/6e489bc0-7047-4b96-b0eb-d73c1a3cb75e)

### Expected behavior

Be able to upload images through swagger

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

10.0.0

### Packages versions

```json
platform-express version : 10.3.3
schematics version       : 10.1.1
passport version         : 10.0.3
mongoose version         : 10.0.4
swagger version          : 7.3.0
testing version          : 10.3.3
common version           : 10.3.3
config version           : 3.2.0
core version             : 10.3.3
jwt version              : 10.2.0
cli version              : 10.3.2
 version                 : 1.11.2
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/issues/2933
