### ISSUE TITLE
collection.count is deprecated

### ISSUE THREAD

**Issue by eric2877** [nestjs/nest#1353]
when nest works with mongo 4, if using findAndCount method  console out put this : 
 DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

is that means I have to overried this method myself ?  the  my  repository  extends  the native  Repository<T>

**Comment by kamilmysliwiec** [comment]
I'd suggest reporting this issue in the `typeorm` directory.
