### ISSUE TITLE
Base exception filter ignores exception cause

### ISSUE THREAD

**Issue by jeengbe** [nestjs/nest#13550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The base exception filter (https://github.com/nestjs/nest/blob/master/packages/core/exceptions/base-exception-filter.ts#L72-L75) simply drops any properties on errors other than message and stack, especially [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause). This is very unfortunate as cause is when provided often crucial to understanding an error.

### Minimum reproduction code

n/a

### Expected behavior

Additional properties, especially `cause` should not simply be ignored, but forwarded to the logger.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

n/a

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by jeengbe** [comment]
I have little understanding of what's happening with the error and why message and stack are logged explicitly. I guess the change would require more refactoring than just my simple patch, sorry.

**Comment by ZigBalthazar** [comment]
Hi @micalevisk, @kamilmysliwiec 
I'm interested in working on this issue and improving the `base-exception-filter`

**Comment by jochongs** [comment]
I've created a PR #13681 

Could you take a look? :)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13870
