### ISSUE TITLE
Exclude version prefix for specific routes

### ISSUE THREAD

**Issue by bin-umar** [nestjs/nest#13562]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Yes, our project has several routes categorized as 'internal' which we do not want to automatically version like other routes in our application. NestJS offers the VERSION_NEUTRAL option to handle such cases, but it requires marking each controller or route individually, which is verbose and cumbersome, especially as the number of routes grows.

### Describe the solution you'd like

We propose an enhancement to the versioning feature in NestJS to allow for route exclusions directly in the versioning configuration. Here’s a proposed API modification:
```ts
app.enableVersioning({
    defaultVersion: '1',
    type: VersioningType.URI,
    exclude: ['health'],
});
```
This configuration would enable developers to specify routes that should not have versioning applied, offering greater flexibility without the verbosity of using VERSION_NEUTRAL on each controller.

### Teachability, documentation, adoption, migration strategy

This feature can be seamlessly integrated into existing applications. Developers would only need to add the `exclude` parameter to their versioning setup. Documentation should explain the use of the exclude option, with examples for common use cases such as excluding internal or administrative routes. This approach simplifies the application structure by reducing the need for separate controllers or extensive use of `VERSION_NEUTRAL`.

### What is the motivation / use case for changing the behavior?

The primary motivation is to streamline the configuration process for internal routes that do not require versioning. Our current approach using `VERSION_NEUTRAL` is too verbose and not scalable as we add more internal services and health checks that need to remain version-neutral for simplicity and internal compliance.

**Comment by micalevisk** [comment]
I think that this can be addressed with the [custom versioning type](https://docs.nestjs.com/techniques/versioning#custom-versioning-type), although not simple as you're suggesting

Can you please try it out?

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
