### ISSUE TITLE
If HttpAdapterHost is a provider, is it part of the current ClsModule?

### ISSUE THREAD

**Issue by Nijinsha** [nestjs/nest#13581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
 ERROR [ExceptionHandler] Nest can't resolve dependencies of the ClsModule (?, ModuleRef). Please make sure that the argument HttpAdapterHost at index [0] is available in the ClsModule context.

Potential solutions:
- Is ClsModule a valid NestJS module?
- If HttpAdapterHost is a provider, is it part of the current ClsModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within ClsModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

```

### Minimum reproduction code

https://github.com/nestjs/nest/i

### Expected behavior

ClsModule should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

nestjs-cls

### NestJS version

10.0.0

### Packages versions

```json
    "@nestjs/common": "~10.0.0",
    "@nestjs/core": "^10.0.0",
    "nestjs-cls": "~4.2.1",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "typeorm": "~0.3.20",
    "@nestjs/config": "~3.2.2",
    "@nestjs/typeorm": "~10.0.2",
    "@nestjs/event-emitter": "~2.0.4",
    "@nestjs/swagger": "~7.3.1",
    "pg": "~8.11.3"
```

### Node.js version

20.12.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
please read the https://docs.nestjs.com/faq/common-errors page

If you think that this is a bug, share us a minimum reproduction repository.
