### ISSUE TITLE
move away from reflect-metadata

### ISSUE THREAD

**Issue by cayter** [nestjs/nest#13600]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

<img width="914" alt="Screenshot 2024-05-19 at 3 42 18 PM" src="https://github.com/nestjs/nest/assets/242017/84528051-463c-4255-a494-3927c0484c50">

As mentioned in the [above](https://github.com/rbuckton/reflect-metadata?tab=readme-ov-file#metadata-reflection-api), tc39 has finalised the decorator metadata spec which leads to `reflect-metadata` implementation being outdated.

esbuild has recently released [decorator metadata support](https://github.com/evanw/esbuild/releases/tag/v0.21.3) that follows tc39 stage 3 spec which makes it super easy for us to run nestjs app via `node --import=tsx app.ts` (assuming tsx is gonna upgrade its esbuild dependency to v0.21.3 soon).

### Describe the solution you'd like

N/A

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

- Much simpler setup.
- Better parity between dev/prd.

**Comment by micalevisk** [comment]
Duplicated #11414
