### ISSUE TITLE
Payment integration using phonepay documentation 

### ISSUE THREAD

**Issue by rahulclevdoc** [nestjs/nest#13609]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

unable to integrate phone pay using nest js 

### Describe the solution you'd like

phone pay integration like we have stripe , phone pay is also an good option to use  ,
using same way how we can integrate 

### Teachability, documentation, adoption, migration strategy

phone pay integration like we have stripe , phone pay is also an good option to use 

### What is the motivation / use case for changing the behavior?

phone pay integration like we have stripe , phone pay is also an good option to use

**Comment by micalevisk** [comment]
This is not specific to nestjs but nodejs

Please use our Discord instead.
