### ISSUE TITLE
configurable threshold for The module ... is taking ...ms to serialize

### ISSUE THREAD

**Issue by sovcharenko** [nestjs/nest#13627]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We're consistently getting 

`The module "InternalCoreModule" is taking 35.35ms to serialize` during start up when app runs on not super fast CPU or when CPU throttling kicks in.

There is no way to configure threshold as it's hardcoded to 10ms 

https://github.com/nestjs/nest/blob/aa7538ffbe8608c41ece2a035b872e5032f57763/packages/core/injector/module-token-factory.ts#L37C4-L42C6

### Describe the solution you'd like

Add configuration option to increase warning threshold or disable this check altogether.

### Teachability, documentation, adoption, migration strategy

N/A i think

### What is the motivation / use case for changing the behavior?

Reduce warnings noise

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/13336

**Comment by sovcharenko** [comment]
@kamilmysliwiec i might be missing something but i don't think this is completed.

The PR you linked is the initial implementation that has 10ms hardcoded.
