### ISSUE TITLE
Feat: Add support for turbopack

### ISSUE THREAD

**Issue by rajat-dlt** [nestjs/nest#13623]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently there’s an option to use webpack, along with this could we also introduce support for turbopack, recently integrated with nextJS. 

### Describe the solution you'd like

A new configuration to build the code using turbopacl, would be very beneficial. 

### Teachability, documentation, adoption, migration strategy

This could be a straightforward change maybe alongside the previously existing methods. 

### What is the motivation / use case for changing the behavior?

It would make the build process really fast.

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
