### ISSUE TITLE
Query filter

### ISSUE THREAD

**Issue by Sansossio** [nestjs/nest#1363]
How would you use a query filter for a GET request in nest?
This is what I want but written for loopback4:
```typescript
@get('/entities', {
    responses: {
      '200': {
        description: 'Array of Entities model instances',
        content: {
          'application/json': {
            schema: {type: 'array', items: {'x-ts-type': Entities}},
          },
        },
      },
    },
  })
  async find(
    @param.query.object('filter', getFilterSchemaFor(Entities)) filter?: Filter,
  ): Promise<Entities[]> {
    return await this.entitiesRepository.find(filter);
  }
```

**Comment by kamilmysliwiec** [comment]
Could you describe an expected behavior of such decorator? I have never built anything with loopback.

**Comment by CesarHuelamo** [comment]
That works as a bridge between the query parameters and the query to the database. Kind of a small graphql on top of the REST api.

**Comment by kamilmysliwiec** [comment]
It looks that Pipe should solve similar problems.
