### ISSUE TITLE
zod validation with @Param error

### ISSUE THREAD

**Issue by yusuf-saydullayev** [nestjs/nest#13647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using zod validation with @Param decorator

### Minimum reproduction code

https://github.com/yusuf-saydullayev/zod-param-conflict

### Steps to reproduce

1. clone repository, install dependencies and start
2. Use API platform to hint api (like postman)
3. hit Post or Put to: http://localhost:3000/2 with json body : { "title": "this is title"}
4. See erro : {
    "message": "Validation failed",
    "error": "Bad Request",
    "statusCode": 400
}

### Expected behavior

Without  validation error, because all data has to pass validation

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

zod

### NestJS version

10.3.9

### Packages versions

```json
platform-express version : 10.3.9
schematics version       : 10.1.1
testing version          : 10.3.9
common version           : 10.3.9
core version             : 10.3.9
cli version              : 10.3.2
```

### Node.js version

20.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

If I do something wrong let me know

**Comment by micalevisk** [comment]
![image](https://github.com/nestjs/nest/assets/13461315/90026fea-6814-4c17-9c92-1a7246a47c6d)

there's no way to nestjs to know how to validate the `id` parameter using that `ZodValidationPipe` pipe. 

if you add `if (metadata.type !== 'body') return value`, it will not try to validate parameters and so will work as expected
