### ISSUE TITLE
This framework does not feel great at all.

### ISSUE THREAD

**Issue by fcastrocs** [nestjs/nest#13658]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

"NestJS - A progressive Node.js framework"
'We do not support ESM"

These two quotes cannot both be true.

### Describe the solution you'd like

yes

### Teachability, documentation, adoption, migration strategy

..

### What is the motivation / use case for changing the behavior?

..

**Comment by micalevisk** [comment]
here's a list of others frameworks: https://gist.github.com/micalevisk/5d8b076fbbb81c7e8a362f8db7a494d7

**Comment by KostyaTretyak** [comment]
@fcastrocs, you can try also [Ditsmod](https://ditsmod.github.io/en/). The code of this framework is written in ESM format.
