### ISSUE TITLE
NestJs middlewares don't run when fastify is the HTTP adapter

### ISSUE THREAD

**Issue by caolanb10** [nestjs/nest#13657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

NestJs middlewares don't run when fastify is the HTTP adapter

When implementing fastify middleware from the docs: https://docs.nestjs.com/techniques/performance#middleware
It doesn't run

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-fvyxvn

### Steps to reproduce

1. npm ci
2. npm start
3. Observe the middleware in `main.ts` runs but the LoggerMiddleware applied in the app.module.ts doesn't work.

### Expected behavior

The logger middleware should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.2

### Packages versions

```json
    "@nestjs/common": "^10.3.2",
    "@nestjs/core": "^10.3.2",
    "@nestjs/platform-fastify": "10.3.9",
    "reflect-metadata": "^0.2.1",
    "rxjs": "^7.8.1"
```

### Node.js version

v18.20.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by caolanb10** [comment]
Solution is
```ts
    consumer.apply(LoggerMiddleware).forRoutes('(.*)');
```

Default behaviour is different between express and fastify, this doesn't work for fastify: 
```ts
    consumer.apply(LoggerMiddleware);
```

**Comment by kamilmysliwiec** [comment]
Not sure if I'm following. The provided code snippet:

```ts
consumer.apply(LoggerMiddleware);
```

is incorrect for both adapters.
