### ISSUE TITLE
Just started with the boilerplate and test does not run

### ISSUE THREAD

**Issue by kopax** [nestjs/nest#13659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, I  have been reading for the first time nestjs documentation and started with https://docs.nestjs.com/first-steps

e2e commands are by default not working

### Minimum reproduction code

https://github.com/kopax/project-name

### Steps to reproduce

```
$ npm i -g @nestjs/cli
$ nest new project-name
$ yarn 
$ yarn test:e2e
```

I have the following error: 
```

on ⛵ teleport.ehp.passculture.team in (staging) project-name on  master [?] via  v20.10.0 on ☁️  gcpadmin.dimitri.kopriwa@passculture.app(passculture-metier-prod) 
❯ yarn test:e2e
yarn run v1.22.15
$ jest --config ./test/jest-e2e.json
 FAIL  test/app.e2e-spec.ts (6.363 s)
  AppController (e2e)
    ✕ / (GET) (5071 ms)

  ● AppController (e2e) › / (GET)

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      16 |   });
      17 |
    > 18 |   it('/ (GET)', () => {
         |   ^
      19 |     return request(app.getHttpServer())
      20 |       .get('/')
      21 |       .expect(200)

      at app.e2e-spec.ts:18:3
      at Object.<anonymous> (app.e2e-spec.ts:6:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.393 s, estimated 7 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
````

### Expected behavior

I expect a working example 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  }
}
```

### Node.js version

v20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

NA

**Comment by micalevisk** [comment]
are you sure you're using the latest version of `@nestjs/cli`? I just ran the following steps and everything went fine here on my linux

Please try this out:

```bash
npm i -g @nestjs/cli@latest
nest new project-name ## and select yarn
cd project-name
yarn
yarn test:e2e
```

![image](https://github.com/nestjs/nest/assets/13461315/571c1e7b-7efa-4b9a-ad82-40dd733d99c7)

**Comment by kopax** [comment]
Hello, you are right, that was a network problem with my host. Thanks you :) Sorry for disturbing !
