### ISSUE TITLE
Typescript Error for using the version 10.3.9  of @nestjs/platform-fastify.

### ISSUE THREAD

**Issue by gordonlau** [nestjs/nest#13684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am using the version `10.3.9` of `@nestjs/platform-fastfiy`, `@nestjs/common` and `@nestjs/core`.  There is a typescript error for the `FastifyAdapter` if I use the sample code.

```typescript
async function bootstrap() {
    const app = await NestFactory.create<NestFastifyApplication>(
        AppModule, 
        new FastifyAdapter() 
    );
    await app.listen(8080);
}
```

The typescript error is the following.

```typescript
Property 'instance' is protected but type 'FastifyAdapter<TServer, TRawRequest, TRawResponse, TRequest, TReply, TInstance>' is not a class derived from 'AbstractHttpAdapter<TServer, TRequest, TResponse>'
```

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/10-fastify

### Steps to reproduce

1. Use the sample provided
2. Upgrade the version `10.3.9`.
3. Run `npm install`
4. The typescript error should appears

### Expected behavior

It should works without typescript error.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.9

### Packages versions

```json
   "dependencies": {
        "@fastify/static": "^7.0.4",
        "@nestjs/common": "^10.3.9",
        "@nestjs/core": "^10.3.9",
        "@nestjs/platform-fastify": "^10.3.9",
        "@nestjs/swagger": "^7.3.1"
   }
```

### Node.js version

20.13.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
![image](https://github.com/nestjs/nest/assets/13461315/c5238a7b-a18b-482f-b126-c147faed1621)

no errors here

Try deleting the lock file and install everything again

**Comment by gordonlau** [comment]
I think I have found the issue of my code. By just installing `@nestjs/platform-fastify`, running `nest` command is good, but it is going to give you typescript error. I need to install `fastify` package separately just to get the type definition right.
Thank you for your help @micalevisk.
