### ISSUE TITLE
response.getHeaders() function always returns empty object in NestJS with Fastify.

### ISSUE THREAD

**Issue by matheuspleal** [nestjs/nest#13685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I created an interceptor to log information about requests and responses. However, I noticed that the getHeaders() method of the response context only works when NestJS uses Express (default), but when Fastify is set in the settings, getHeaders() always returns an empty object

### Minimum reproduction code

https://github.com/matheuspleal/nestjs-fastify

### Steps to reproduce

1.   `npm install`
2.  `npm start:dev`

In the `src/main.ts` file, simply uncomment the // Default with Express code snippet and comment the // Custom with Fastify snippet to use Express instead of Fastify and check if the headers are returned correctly by the getHeaders( function ) when Express is in use.

### Expected behavior

Regardless of the tool (Express or Fastify), the NestJS API should handle the return of headers when the getHeaders() function is invoked.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "nestjs-fastify",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.2.2",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/platform-fastify": "^10.3.9",
    "pino": "^9.2.0",
    "pino-pretty": "^11.2.1",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
when using Express adpater:

![image](https://github.com/nestjs/nest/assets/13461315/59427956-fa7b-46b6-9706-603967e0665f)

when using Fastify adapter:

![image](https://github.com/nestjs/nest/assets/13461315/3831bdb8-0480-4582-ae2e-a620b04fefb9)

and after adding a `response.headers()` call, I see this:

![image](https://github.com/nestjs/nest/assets/13461315/fca1fbc3-9a9d-4f9a-9f58-c519ce1c2ef4)

I didn't find any mention on the `x-powered-by` header being defined automatically by Fastify so I'd say that it doesn't. Thus, there's nothing wrong with the present behavior.

**Comment by matheuspleal** [comment]
You are sure! Express defines a default `x-powered-by` header and Fastify does not. I tested it by adding a custom header `response.header('x-foo', 'bar')` and it worked! Thank you for your help!
