### ISSUE TITLE
with queue's enabled not all EventPattern's get triggered

### ISSUE THREAD

**Issue by tholum** [nestjs/nest#13686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using NATS, if queue's are enabled, not all patterns get triggered on an event, I am fairly sure this is because when in a queue NATS only sends an event to one of the subscribers in the queue, and it would appear as if Nest in the backend groups subscribers ( which is why the 2 with core.test trigger together ), 

Possible Solutions:
* Find the most permissive pattern, and write code to send to the paterns, so in my example, see core.* contains core.test
* Allow setting queue in the EventPattern parameters

The example if I publish an event to 'core.test' and in three controllers I have, with the following example, I will randomly eather get it on A and B, Or I will get it on C

Controller A:
```ts
@EventPattern(`core.test`)
    async test(data: any, @Ctx() context: NatsContext) {
        console.log( "From A",  context.getSubject() );
        // console.log('Ticket created All :', data);
    }
```

Controller B:
```ts
@EventPattern(`core.test`)
    async test(data: any, @Ctx() context: NatsContext) {
        console.log( "From B",  context.getSubject() );
        // console.log('Ticket created All :', data);
    }
```

Controller C:
```ts
@EventPattern(`core.*`)
    async test(data: any, @Ctx() context: NatsContext) {
        console.log( "From C",  context.getSubject() );
        // console.log('Ticket created All :', data);
    }
```

relavent code from my main.ts
```ts 

app.connectMicroservice({
      transport: Transport.NATS,
      options: {
        queue: process.env.NATS_QUEUE,
        servers: process.env.NATS_URL.split(';'),
        token: process.env.NATS_TOKEN
      }    
    });

```

### Minimum reproduction code

https://github.com/tholum/nestjs-natsbug1

### Expected behavior

All 3 get triggered

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "nats-bug",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/microservices": "^10.3.9",
    "@nestjs/platform-express": "^10.0.0",
    "dotenv": "^16.4.5",
    "nats": "^2.26.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord since that is the expected behavior of this feature. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
