### ISSUE TITLE
returning an object from file upload controller returns undefined response

### ISSUE THREAD

**Issue by Toxicable** [nestjs/nest#1370]
## I'm submitting a...
<pre><code>[x] Bug report
</code></pre>

## Current behavior
If we have a file upload endpoint like the example below and return an object then nothing is in the response body. You must use `res.send({path: file.path});` to send something back
```
  @Post('upload')
  @UseInterceptors(FileInterceptor('file', {dest: '/tmp/files', }))
  upload(@UploadedFile() file: {path: string}, @Res() res: Response) {
    return {path: file.path};
  }
```
This example will send it back
```
  @Post('upload')
  @UseInterceptors(FileInterceptor('file', {dest: '/tmp/files', }))
  upload(@UploadedFile() file: {path: string}, @Res() res: Response) {
    res.send({path: file.path});
  }
```

## Expected behavior
returning from this method should return something on the response

## Minimal reproduction of the problem with instructions
the snippets above

## What is the motivation / use case for changing the behavior?
a nice api for dealing with files

## Environment

<pre><code>Nest version: 5.1.0

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/49873669-bdb38b80-fe1c-11e8-9ea6-098aa287c1bb.png)
https://docs.nestjs.com/controllers 
Chapter: **Routing**
