### ISSUE TITLE
Typegoose Support

### ISSUE THREAD

**Issue by olawalejuwonm** [nestjs/nest#13704]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have issue when trying to reference other model with mongoose. I prefer using the class instead of just String as anything might go wrong

### Describe the solution you'd like

Let typegoose be natively supported by nestjs. It was built natively with typescript support for mongoose which is also the aim of NestJS. Please 

### Teachability, documentation, adoption, migration strategy

Please see this: [here](https://github.com/typegoose/typegoose/discussions/933#discussioncomment-9281764)

### What is the motivation / use case for changing the behavior?

It will make NestJs more typescript inclined and hence powerful. I have enjoyed using it on solo express project and when I found out about NestJs I assumed it will be the default

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
