### ISSUE TITLE
2 high severity vulnerabilities in `@nestjs/platform-ws`

### ISSUE THREAD

**Issue by robertIsaac** [nestjs/nest#13713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`@nestjs/platform-ws` has hard dependency on `"ws": "8.17.0"` which has the vulnerabilities  https://github.com/advisories/GHSA-3h5v-q93c-6h6q
we need to update it to `8.17.1`

### Minimum reproduction code

any project with @nestjs/platform-ws

### Steps to reproduce

`npm i @nestjs/platform-ws`

### Expected behavior

to depend on `"ws": "8.17.1"` or even better `"ws": "~8.17.1"`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [x] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"@nestjs/platform-ws": "^10.2.6",
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in v10.3.10
