### ISSUE TITLE
Once `fastify-passport` becomes stable, we'll add support for it in the `@nestjs/passport` package.

### ISSUE THREAD

**Issue by olawalejuwonm** [nestjs/nest#13711]
When do we know when this has been done?
              Once `fastify-passport` becomes stable, we'll add support for it in the `@nestjs/passport` package.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/5702#issuecomment-727792674_

**Comment by micalevisk** [comment]
so I guess now `@fastify/passport` right

duplicate https://github.com/nestjs/passport/issues/1655

**Comment by olawalejuwonm** [comment]
> so I guess now we can start supporting fastify via `@fastify/passport` 
> 
> duplicate https://github.com/nestjs/passport/issues/1655

When will this be done please?
