### ISSUE TITLE
App not loading

### ISSUE THREAD

**Issue by ganeshbala2008** [nestjs/nest#13725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

App not loading stuck at instance loader. Unable to find the exact issue. No circular dependecy detected

![image](https://github.com/nestjs/nest/assets/19310900/8a2eea2f-ed02-41bc-b99d-c69ba964a4bd)

### Minimum reproduction code

NA

### Steps to reproduce

1. npm run start:debug

### Expected behavior

Should start the app

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0..0

### Packages versions

```json
"dependencies": {
		"@nestjs/axios": "^3.0.2",
		"@nestjs/azure-database": "^3.0.0",
		"@nestjs/common": "^10.0.0",
		"@nestjs/core": "^10.0.0",
		"@nestjs/platform-express": "^10.0.0",
		"@nestjs/swagger": "^7.3.1",
}
```

### Node.js version

18.19.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Sorry but there's no way we could help you without the whole code so I'll close this until you provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
