### ISSUE TITLE
ModuleRef failed to get/resolve external service which have been imported into local module

### ISSUE THREAD

**Issue by mannok** [nestjs/nest#13726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Given this module setup:

```
@Module({
  providers: [AuthService],
  exports: [AuthService],
})
export class AuthModule {}

@Module({
  imports: [AuthModule],
  providers: [AuthController],
})
export class ApiModule {}
```

The following is not working
```
Controller({ scope: Scope.REQUEST, path: 'auth' })
export class AuthController {
  constructor(private moduleRef: ModuleRef) {}

  @Get('profile')
  async profile(@Req() req: Request) {
    const contextId = ContextIdFactory.getByRequest(req);
    const authService = await this.moduleRef
      .resolve(AuthService, contextId); // error thrown
  }
}
```

### Minimum reproduction code

https://github.com/nestjs/nest

### Expected behavior

`await this.moduleRef.resolve(AuthService, contextId); ` should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.2.2",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "joi": "^17.13.3",
    "node-telegram-bot-api": "^0.65.1",
    "p-retry": "^6.2.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  }
}
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
`moduleRef` is referencing `AppModule`, not `AuthModule`. Move `AuthController` to `AuthModule` and it will work as you wish

Use our discord community next time.
