### ISSUE TITLE
Add In Built Support for absolute path import

### ISSUE THREAD

**Issue by jashezan** [nestjs/nest#13722]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Absolute Path Import is quite handy as a developer. It enhance developer experience drastically. Many popular projects are adopting this. Like `Next.js` has adopted this.

### Describe the solution you'd like

Currently the code looks like
```typescript
import { UserModule } from "./user/user.module";
```

After adopting absolute path import:
```typescript
import { UserModule } from "@/user/user.module";
```

### Teachability, documentation, adoption, migration strategy

People are using the `module-alias` package [A Third Party npm package] to achieve this. Also, there is some nasty configuration. This should be simplified as in **`Next.js`**.

### What is the motivation / use case for changing the behavior?

The absolute path import will make the code readable, more maintainable, and less hectic.

**Comment by jmcdo29** [comment]
So long as you have the paths correctly set up in your `tsconfig`, this should be supported out of the box. You may need to update your testing config though. On `nest build`, Nest will transpile using Typescript, and call into a `before` hook to use `tsconfig-paths` to replace the absolute path with the related relative path.

**Comment by micalevisk** [comment]
[working.webm](https://github.com/nestjs/nest/assets/13461315/6bf98490-3ced-4265-90b7-0cf68d0fe118)
