### ISSUE TITLE
Route parameter override another controller

### ISSUE THREAD

**Issue by IgorRSGraziano** [nestjs/nest#13723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating a resource, such as **User**, which contains a route like `:id`, and within that resource create another resource, let's call it **Auth**, and the **Auth** has a root route `'/'`, this root route instead of hitting in auth, it is falling on the **User** route

In example code, i create manually user (inside src/user), and generated by `nest ge res resource-user` (inside src/resource-user)

### Minimum reproduction code

https://github.com/IgorRSGraziano/nest-route-override

### Steps to reproduce

1 - npm i
2 - npm run start:dev
3 - try access http://localhost:3000/user/auth

### Expected behavior

Expected result from example code is 'Session' response (from controller src/user/user.controller.ts)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
```

### Node.js version

21.2.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
sorry but I didn't understand what's wrong. In your reproduction repository, `GET http://localhost:3000/user/auth` is returning the response from `src/user/user.controller.ts`, as you said it's the expected behavior

Are you saying that it should be returning `"Session"` from `src/user/auth/auth.controller.ts` instead?

**Comment by IgorRSGraziano** [comment]
> sorry but I didn't understand what's wrong. In your reproduction repository, `GET http://localhost:3000/user/auth` is returning the response from `src/user/user.controller.ts`, as you said it's the expected behavior
> 
> Are you saying that it should be returning `"Session"` from `src/user/auth/auth.controller.ts` instead?

Sorry if the explanation was confusing, when accessing `GET http://localhost:3000/user/auth`, you should hit the controller `src/user/auth/auth.controller.ts` and not `src/user/user.controller`

**Comment by micalevisk** [comment]
can you share the initial version of the project? could be in another branch of your repository

**Comment by micalevisk** [comment]
but the `src/user/auth/auth.controller.ts` controller doesn't have a `user` prefix. Why are you expecting `GET /user/auth` to hit that controller? :thinking: 

![image](https://github.com/nestjs/nest/assets/13461315/b56167ce-26cc-4b63-b6f0-188cee9d82ad)

**Comment by IgorRSGraziano** [comment]
> but the `src/user/auth/auth.controller.ts` controller doesn't have a `user` prefix. Why are you expecting `GET /user/auth` to hit that controller? 🤔
> 
> ![image](https://private-user-images.githubusercontent.com/13461315/342888186-b56167ce-26cc-4b63-b6f0-188cee9d82ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDI2NzksIm5iZiI6MTcxOTM0MjM3OSwicGF0aCI6Ii8xMzQ2MTMxNS8zNDI4ODgxODYtYjU2MTY3Y2UtMjZjYy00YjYzLWI2ZjAtMTg4Y2VlOWQ4MmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE5MDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNDY1ODFlYzM5YzJmYTNlZTViOTU5YTZiYTY0YTgzY2YwN2ViN2YwYjE0MzliNjJmMzk3YWNjNWJiOWJiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2qkxWWHAq9dsqDZdR1bfQeah1tGwvJ-7NK8SHYC6k_Q)

Oh god, sorry, I really forgot about that. But when trying to add `user/auth` I had the same error on `GET http://localhost:3000/user/auth`

**Comment by micalevisk** [comment]
AFIAK this is expected. The controllers listed at `AppModule` are taking precedence over the ones discovered for each module at `AppModule`'s `imports`.

If you create another module (eg: `UserModule`) to register the `UserController` controller and then if your `AppModule` imports both:  `[AuthModule, UserModule]`, it will behave as you're expecting due to the registration order.

**Comment by IgorRSGraziano** [comment]
It worked correctly, thank you very much!
