### ISSUE TITLE
[Fastify] Crash when registering a middleware that also registers middie

### ISSUE THREAD

**Issue by ancyrweb** [nestjs/nest#13729]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm trying to integrate @fastify/vite with NestJS, but both @fastify/vite & @nestjs/platform-fastify register `middie`.
Which leads to a crash.

So far the solution I've found is to implement the following.

```ts
async function bootstrapNestJs() {
  const adapter = new FastifyAdapter({ logger: true });
  await adapter.register(FastifyVite as any, {
    ...
  });

  (adapter as any).isMiddieRegistered = true;

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    adapter,
  );

  const server = app.getHttpAdapter().getInstance() as any;
  await server.vite.ready();
  await app.listen(3000);
}
```

### Describe the solution you'd like

The simple patch would be to add an other flag to the `FastifyAdapter` constructor to mark `middie` as already registered.
I can propose a PR if wanted.

### Teachability, documentation, adoption, migration strategy

It's just an optional flag.

### What is the motivation / use case for changing the behavior?

Required to setup Vite with NestJS.

### Repro

Here's a sample project that illustrates the problem : https://github.com/ancyrweb/nestjs-react-vite-ssr
Remove the line `(adapter as any).isMiddieRegistered = true;` in the `src/main.ts` file.

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by ancyrweb** [comment]
@micalevisk updated

**Comment by kamilmysliwiec** [comment]
Feel free to create a PR that allows passing the `skipMiddie` attribute to the `FastifyAdapter` constructor (as part of the options object)
