### ISSUE TITLE
Do not lock closed issues on GitHub

### ISSUE THREAD

**Issue by vtgn** [nestjs/nest#13728]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When we have problems, we searches inside the issues if someone already notified it.
But when it is the case, most of the time the issues are old (ok), closed (ok), and locked (doh!!!), which prevents us from being able to ask for additional information, or to complete the issue by possible workarounds, particularly when no workaround is given or not enough clearly.

### Describe the solution you'd like

Do not lock closed issues.

### Teachability, documentation, adoption, migration strategy

None.

### What is the motivation / use case for changing the behavior?

It would be more practical to let the possibility to add new comments on the closed issues, even several years later, just to complete the discussion, ask for additional information, and propose new workarounds for the next readers having the same problem. It happens often to me, and it's very frustrating to see the issues closed without concrete workaround given. And when I find one, I would like to share it to give a solution to the next readers like me. Plus, it avoids the creation of new issues about the same problem, just because the previous one has given no solution.

**Comment by vtgn** [comment]
For example, I have a workaround to give for this problem, but it is locked: https://github.com/nestjs/nest/issues/8076

**Comment by micalevisk** [comment]
I understand your frustration.

Additionally, I strongly recommend you to [read this](https://gist.github.com/g1eny0ung/9e7d4d0f72547a8d156452e76fa8f7a3) if you want to rely on OSS.

**Comment by micalevisk** [comment]
and about that issue, I'd like to see your workaround for it in this issue: https://github.com/nestjs/docs.nestjs.com/issues/2823

**Comment by vtgn** [comment]
@micalevisk I agree that I doubt GitHub is the best place to share workarounds or technical discussions, because it must be dedicated for bugs reporting and features improvement only, to avoid to overload the NestJs team.
But I find also frustrating that we can do it on generic platforms only, like stackoverflow. It would be great to have a dedicated place somewhere, linked with the official NestJs tool and team, to share our good practices, workarounds and solutions.

**Comment by micalevisk** [comment]
@vtgn we use Discord for that. It is pretty big now. In the past others platforms were tried but none succeeded.

**Comment by vtgn** [comment]
@micalevisk Oh ok, I'll try to see it, I have no account yet. Thanks.
I'm preparing the answer for the workaround, I need to do some additional tests.

**Comment by kamilmysliwiec** [comment]
We used to not lock issues in the past and it only led to more spam, making them even harder to follow. If you have a workaround that you'd like to share with others, you can always create a new issue and immediately close it.
