### ISSUE TITLE
Preconfigured CLI for NestJS

### ISSUE THREAD

**Issue by EivydasV** [nestjs/nest#13732]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

NestJS currently lacks built-in CLI support. Coming from a Symfony background, I have appreciated the robust CLI tooling that Symfony provides out of the box.  There is a `nest-commander` package that offers CLI tooling, but NestJS does not have a standard way to use it. This makes it harder and more time-consuming for developers to integrate and configure the CLI in their projects.

### Describe the solution you'd like

I would like to see NestJS include a preconfigured CLI tool out of the box, similar to what Symfony provides. This CLI should offer a standardized approach for creating commands.

### Teachability, documentation, adoption, migration strategy

In the root directory of a NestJS project, a `bin/commander` file could be created. This file would look like:
```
#!/usr/bin/env node

import { CommandFactory } from 'nest-commander';
import { AppModule } from '../src/app.module';

async function bootstrap() {
	await CommandFactory.run(AppModule, ['warn', 'error']);
}

bootstrap();
```
This file doesn't have an extension since it is marked with a shebang (#!) at the top, indicating it should be executed with Node.js.

However, because it doesn't have a .ts extension, it won't be compiled to JavaScript by TypeScript. I haven't yet figured out how to address this issue, but this example demonstrates the concept. After creating this file, we could run `dist/bin/commander` in the terminal to execute the commands.

### What is the motivation / use case for changing the behavior?

Integrating a preconfigured CLI into NestJS would significantly enhance the framework's capabilities and simplify the process of creating commands. Additionally, third-party packages could leverage this CLI to provide their own commands. For example, when a third-party package is registered in a module, it could automatically include commands created by the package author.

For instance, NestJS packages like `@nestjs/elasticsearch` could provide built-in commands for managing Elasticsearch. Once registered, developers could easily run commands such as `dist/bin/commander drop:indexes` directly from the terminal.

Overall, comprehensive CLI tooling would be a powerful addition to NestJS, offering a more streamlined and efficient development experience. I believe this aspect has been overlooked but holds great potential.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
