### ISSUE TITLE
Dynamic module promises in the `exports` array is broken

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#13733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Since the commit https://github.com/nestjs/nest/commit/be6d90ace2b0b2496fc4cd51619d8216e2f4a808#diff-10d05a74883d097e0c5b94c8564bd68b26cfcc9c57b32e3e0c0024c9e91c3e88 (nestjs v6), the following is supposed to work but it doesn't:

```ts
const whenDynamicModule: Promise<DynamicModule> = Promise.resolve({
  module: class MyModule {},
})

@Module({
  imports: [whenDynamicModule],
  exports: [whenDynamicModule],
})
export class AppModule {}
```

it crashes with the following error:

```
Error: Nest cannot export a provider/module that is not a part of the currently processed module (Bar). Please verify whether the exported [object Promise] is available in this particular context.

Possible Solutions:
- Is [object Promise] part of the relevant providers/imports within Bar?
```

we can easily see that this is either a missing feature or a regression.

### Minimum reproduction code

https://gitlab.com/micalevisk/nestjs-issue-13733

### Steps to reproduce

```
git clone https://gitlab.com/micalevisk/nestjs-issue-13733
cd nestjs-issue-13733
npm ci
npm start
## se the error
```

### Expected behavior

I tested it with nestjs v6, v7 (with a different error), v8, v9, v10 so I'm pretty sure that this was never supported besides what the type definition says.

I found that after testing the `ConditionalModule` feature with dynamic modules returning promises. I never saw anyone reporting this error before so I'd say that this is not common pattern at all.

I tried to fix this but due to the async nature I didn't managed to fix it easily.

So instead of starting supporting it now in v10, I'd rather prefer to drop the `Promise<DynamicModule>` type from `exports` in NestJS v11. Or just drop it now in v10 because it doesn't seem to be used anyway.

If anyone starting asking for such fix in <=v10, we could suggest them to use  
`exports: [YourDynamicModule]` instead and tell them that this is not a feature but a wrong type definition.

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.9

### Packages versions

N/A

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Kelvin-ui-hub** [comment]
Hey, let me try and work on it

**Comment by micalevisk** [comment]
@Kelvin-ui-hub go ahead. PRs are more than welcomed

**Comment by kelvin-go-get** [comment]
Okay thanks

**Comment by micalevisk** [comment]
@kamilmysliwiec can we just drop this feature in the next major release as it never worked anyway?

**Comment by kamilmysliwiec** [comment]
Sounds good @micalevisk. Would you like to create a PR for this?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/14114
