### ISSUE TITLE
swc compilation with type-checking should not compile when there are type errors

### ISSUE THREAD

**Issue by aberonni** [nestjs/nest#13760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using SWC with NestJS, there is a handy [type checking functionality](https://docs.nestjs.com/recipes/swc#type-checking). When there is a type error, you see a log in the console, but the project still compiles successfully.

<details>
  <summary>Expand me to see an example of the logs with a TS error and a reload</summary>

```console
➜ docker logs -f 121-service

> prestart:dev
> npm install --no-fund --no-audit --no-save


up to date in 1s

> start:dev:nest
> nest start -r tsconfig-paths/register -d 0.0.0.0:9229 --type-check -w -p tsconfig.json

 Info  "typeCheck" will not have any effect when "builder" is not "swc".
>  SWC  Running...

⠋  TSC  Initializing type checker...Successfully compiled: 563 files with swc (320.51ms)
Debugger listening on ws://0.0.0.0:9229/c36fd4e5-7c97-44ec-ab4e-0d4152bb15f8
For help, see: https://nodejs.org/en/docs/inspector
src/app.module.ts:70:5 - error TS2322: Type 'string' is not assignable to type 'void'.

70     return '';
       ~~~~~~

>  TSC  Found 1 error. Watching for file changes.
✔  TSC  Initializing type checker...
>  TSC  Found 0 issues.
Watching for file changes.
[Nest] 123  - 07/05/2024, 8:58:24 AM     LOG [NestFactory] Starting Nest application...
{"name":"AzureAD: Bearer Strategy","hostname":"d0b35d6e1d57","pid":123,"level":40,"msg":"Production environments should always validate the issuer.","time":"2024-07-05T08:58:24.443Z","v":0}
[Nest] 123  - 07/05/2024, 8:58:24 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +33ms
...
...
... # lots of logs omitted here
...
...
[Nest] 159  - 07/05/2024, 8:59:07 AM     LOG [NestApplication] Nest application successfully started +29ms
```
</details>

### Minimum reproduction code

n/a - happy to provide it but only if it is necessary

### Expected behavior

When the type check flag is used and there is a type error, the SWC compiler does not compile the project nor show the "Application successfully started" message.

(AFAIK this would be the same behaviour as the compiler without SWC) 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.9

### Packages versions

```console
➜ npx nest info

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS 23.4.0
NodeJS Version : v18.20.0
NPM Version    : 10.5.0 

[Nest CLI]
Nest CLI Version : 10.3.2 

[Nest Platform Information]
platform-express version : 10.3.9
throttler version        : 4.2.1
passport version         : 10.0.3
schedule version         : 4.0.2
terminus version         : 10.2.3
swagger version          : 7.3.1
testing version          : 10.3.9
typeorm version          : 10.0.2
common version           : 10.3.9
axios version            : 3.0.2
bull version             : 10.1.1
core version             : 10.3.9
cli version              : 10.3.2

```

### Node.js version

18.20.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

This could be potentially an additional flag ie. `--type-check-fail-on-error` but IMHO this would be the expected behaviour of the existing flag.

**Comment by micalevisk** [comment]
> ... the SWC compiler does not compile the project

We can prevent the compilation because the type checking is performed in parallel for performance reasons (I guess). But the 'Found 0 issues' seems to be a bug to me

![image](https://github.com/nestjs/nest/assets/13461315/054a64d0-1c13-4d08-a789-18c995c98a12)

**Comment by kamilmysliwiec** [comment]
This is the expected behavior - type checking is supposed to run in parallel and be non-blocking for the compilation itself.
