### ISSUE TITLE
Global module service not injected when running test

### ISSUE THREAD

**Issue by mutongwu** [nestjs/nest#13775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Cound not inject global module service when running test cases.
Here is the dependence chain: 
```
app.module ---> a.module --->share.module (Global)

app.controller --> app.service ---> a.service ---> share.service (exported in share.module)
```
**### When I run the app, every thing goes fine.  But when I run the e2e testing, it failed.**

### Minimum reproduction code

https://codesandbox.io/p/devbox/thirsty-thompson-myz2t5?file=%2Ftest%2Fapp.e2e-spec.ts%3A10%2C27

### Steps to reproduce

1. npm the e2e script :  `npm run test:e2e`
2. failed with error:
```

> nest@0.0.1 test:e2e /project/workspace
> jest --config ./test/jest-e2e.json

 FAIL  test/app.e2e-spec.ts
  ● Test suite failed to run

    Cannot find module 'src/common/share.service' from '../src/a/a.service.ts'

    Require stack:
      /project/workspace/src/a/a.service.ts
      /project/workspace/src/app.service.ts
      /project/workspace/src/app.controller.ts
      /project/workspace/src/app.module.ts
      app.e2e-spec.ts

      1 | import { Injectable } from '@nestjs/common';
    > 2 | import { ShareService } from 'src/common/share.service';
        | ^
      3 |
      4 | @Injectable()
      5 | export class AService {

      at Resolver._throwModNotFoundError (../node_modules/.pnpm/jest-resolve@29.7.0/node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (../src/a/a.service.ts:2:1)
      at Object.<anonymous> (../src/app.service.ts:2:1)
      at Object.<anonymous> (../src/app.controller.ts:2:1)
      at Object.<anonymous> (../src/app.module.ts:2:1)
      at Object.<anonymous> (app.e2e-spec.ts:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.709 s
Ran all test suites.
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

ShareService should be injected correctly into a.service.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

"^10.0.0"

### Packages versions

```json
{
  "name": "nest",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
1. your sandbox link is not working
2. this seems to be a Jest limitation on using absolute imports. So read this: https://til.hashrocket.com/posts/lmnsdtce3y-import-absolute-paths-in-typescript-jest-tests

**Comment by mutongwu** [comment]
> 1. your sandbox link is not working
> 2. this seems to be a Jest limitation on using absolute imports. So read this: https://til.hashrocket.com/posts/lmnsdtce3y-import-absolute-paths-in-typescript-jest-tests

Thanks for your reply.  sandbox link is updated.

https://codesandbox.io/p/devbox/thirsty-thompson-myz2t5?file=%2Ftest%2Fapp.e2e-spec.ts

**Comment by micalevisk** [comment]
adding the follow to your jest config file will fix that:

```
  "moduleNameMapper": {
    "src/(.*)": "<rootDir>/../src/$1"
  }
```

(not saying that this is the best approach as you'd have to coordinate with typescript path aliases as well)

---

Please use our [discord server](https://discord.gg/nestjs) next time. That was a pretty clear Jest error, not related with NestJS at all.
