### ISSUE TITLE
proposal: drop nest monorepo mode

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#13781]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Nest's Monorepo mode was useful when there weren't amazing or well defined monorepo tools in the ecosystem, especially as Lerna was being deprecated around the same time that it came out. However, since the creation, we've had tools like Nx, Turbo, and Rush arise and provide much smoother monorepo management experiences. These tools show how Nest's monorepo mode is like a monorepo lite, as it doesn't provide a strong build system, and is really only good for Nest only monorepos, which while they exist, aren't as plentiful as full stack or multi-package monorepos. 

### Describe the solution you'd like

Drop the support of a monorepo mode from Nest, and instead provide recipes or similar guidance to show how to work with Nest in a monorepo. These could even be blog articles from the community if we don't want them in the documentation itself.

### Teachability, documentation, adoption, migration strategy

This would be a breaking change, as there will be people using monorepo mode that would need to migrate, so we might want to choose one or two to say "These are our suggested monorepo tools", my vote is for Nx and Turbo, and especially Nx as they've made the process streamlined, but don't want people to feel locked into a decision on our behalf.

### What is the motivation / use case for changing the behavior?

As I said, Nest's monorepo mode isn't as powerful as other monorepo management tools, and it can end up causing churn as the responsibilities of a project grows to start including a front end or non-Nest servers. By removing Nest's monorepo mode, not only do we set ourselves up for success by dealing with less issues and maintenance, but we also set up the community for a stronger success by using tools that have whole teams dedicated to their creation and maintenance. This will allow us to focus more on the framework and less on the CLI, which should allow for better support from us as time goes on.

**Comment by micalevisk** [comment]
I'd say that we could deprecated it in v11 and then drop it in v13

**Comment by kamilmysliwiec** [comment]
If someone wants to use Nx, Lerna, or Turborepo, then that's great - go for it, but there's no reason to deprecate and remove something that already serves its purpose well (NestJS-only monorepos) and force everyone to migrate just because _there are other tools around_, not to mention all articles, videos, and everything that would become outdated as a result of this change.
