### ISSUE TITLE
.setGlobalPrefix() could expose a formatting callback function 

### ISSUE THREAD

**Issue by nhomble** [nestjs/nest#13795]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am unable to describe common prefixes for groups of routes.

Instead of grouping all of my routes under a static prefix (and excluding the rest), I have groups of endpoints that I'd like to ensure have common prefixes for example:

1. public apis vs internal apis
2. health check endpoints
3. static endpoints

---

With the current implementation, there's at best 2 groups: static prefixed group and everything else.

### Describe the solution you'd like

I think the `.setGlobalPrefix` endpoint could consider overloading its argument to take in `string | () => string`. In terms of arguments, I'm curious what the maintainers think but beyond the existing metadata extracted in `RoutesResolver`, I'd like access to the `Reflector` to look up my own decorators.

### Teachability, documentation, adoption, migration strategy

The current overloading is backwards compatible with the static implementation today so I don't see any migration concerns. 

Documentation/teachability can be done with additional information in the [existing FAQ](https://docs.nestjs.com/faq/global-prefix)

### What is the motivation / use case for changing the behavior?

I have http applications that have different sets of apis that differentiate between infrastructural apis, developer experience apis, operational apis, and public/private apis. To help build consistency across services and build straightforward [path-prefix rules](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) having more control beyond a static prefix is desirable as a common function rather than depending on end-users to consistently annotate their controllers a certain way.

You could imagine that based off of custom decorators, we could influence the path prefix.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
