### ISSUE TITLE
ConfigService cache

### ISSUE THREAD

**Issue by its-dibo** [nestjs/nest#13805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

configService always gets an obsolated values

### Minimum reproduction code

.

### Expected behavior

configService should revalidate the cache when the .env file used by it modified.
as a suggestion we can check for modifying time

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/config

### Packages versions

.

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
