### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by zandko** [nestjs/nest#13802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This problem will occur when I upgrade nest-cli to the latest version.

### Minimum reproduction code

Brand-new template

### Steps to reproduce

1. `pnpm add @nestjs/cli@latest` 2. `pnpm run start:dev`

### Expected behavior

It can start normally when I develop locally.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/cli

### NestJS version

10.3.10

### Packages versions

```json

```

### Node.js version

18.18.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

![IMG-2024-07-19-09 00 06@2x](https://github.com/user-attachments/assets/e75a526e-c923-4ecd-9af2-59f6c4a37d53)

**Comment by micalevisk** [comment]
everything went fine in my linux. Perhaps this is a bug on mac OS only?

closing this until we have a minimum repro of that with the right steps to reproduce it.
