### ISSUE TITLE
Injecting ClientProxy (microservice) to allow easy overriding (mocking) via testing?

### ISSUE THREAD

**Issue by appsolutegeek** [nestjs/nest#1380]
Hi

I am trying to find a way of injecting the ClientProxy into the constructor of a service. Is this possible, I would like to do this to allow easier testing (unit testing) and replacing it with a mock.

I checked the docs and it appears you can create it inside the constructor or use a decorator on a public field.

Does anyone have any experience with working with the clientProxy and injecting it into a constructor for easier testing ?

Thanks in advance

**Comment by kamilmysliwiec** [comment]
Hi @appsolutegeek, 
I would suggest looking here https://docs.nestjs.com/microservices/basics **Client** chapter. It seems that `ClientProxyFactory` should solve your issues (basically, simply create a custom provider that registers `ClientProxyFactory.create()` result as a container value).

**Comment by appsolutegeek** [comment]
thanks @kamilmysliwiec , I will look into this.
