### ISSUE TITLE
Documentation - allow copy code snippets 

### ISSUE THREAD

**Issue by Tamir198** [nestjs/nest#13819]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

no

### Describe the solution you'd like

Would be nice to have a copy button for the code snippets in the docs : 

![image](https://github.com/user-attachments/assets/15a198df-d9d2-4adf-8a3a-5ca71955c8a1)

### Teachability, documentation, adoption, migration strategy

the users will be able to copy the code snippet

### What is the motivation / use case for changing the behavior?

Motivation - it will be a bit more comfortable

**Comment by micalevisk** [comment]
duplicate https://github.com/nestjs/docs.nestjs.com/issues/2332
