### ISSUE TITLE
gRPC client stream not working when interceptor is registered in NestJS 

### ISSUE THREAD

**Issue by hersentino** [nestjs/nest#13818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

With a NestJS gRPC server that uses a interceptor, client stream calls are not working. If no interceptor is used, client streams work flawlessly. The same behavior occurs for bidirectional streams, but there are no bugs for server streams

### Minimum reproduction code

https://github.com/hersentino/nestjs-grpc-interceptor

### Steps to reproduce

1. `npm i`
2. `npm start` => run gRPC server
3. `npm run client` => run gRPC client that makes a client stream to the server => call not working
4. Comment out the gRPC interceptor on line 28 inside `src/main.ts`
5. Re-run steps 2 and 3 => call working fine

### Expected behavior

To have the gRPC client stream working when an interceptor is registered

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```[Nest CLI]
Nest CLI Version : 10.4.2 

[Nest Platform Information]
platform-express version : 10.3.10
microservices version    : 10.3.10
schematics version       : 10.1.2
testing version          : 10.3.10
common version           : 10.3.10
core version             : 10.3.10
cli version              : 10.4.2
```

### Node.js version

v20.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Sassyprogrammer1** [comment]
Can I look into this issue ?

**Comment by Kelvin-ui-hub** [comment]
Hi, can i work on this issue?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/14163
