### ISSUE TITLE
Nestjs controller vs forwardRef issue

### ISSUE THREAD

**Issue by khanhx** [nestjs/nest#13826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This issue will happen with the bellow condition
 - The controller inject service A
 - Service A has using forwardRef for inject service B
 - Service A constructor call the async function for modified the service A property
 => From the controller, we can't access the latest value of that property. The value has been cached.

### Minimum reproduction code

https://github.com/khanhx/nestjs-controller-forwardref-bug

### Steps to reproduce

1. `npm ci`
2. `npm run start`

<img width="881" alt="image" src="https://github.com/user-attachments/assets/c8e0ce86-55ad-4cc5-b53d-7599b1e0139a">

### Expected behavior

The value from controller should match with value in the service A since we only have one instance of service A

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
  "@nestjs/common": "^10.3.2",
    "@nestjs/core": "^10.3.2",
    "@nestjs/platform-express": "^10.3.2",
    "reflect-metadata": "^0.2.1",
    "rxjs": "^7.8.1"
```

### Node.js version

v18.18.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
