### ISSUE TITLE
Use `ExecutionContext` Instead of `ArgumentHost` in Custom Exception Filters

### ISSUE THREAD

**Issue by toshmukhamedov** [nestjs/nest#13822]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The current implementation of the `catch(exception: any, host: ArgumentHost)` method in custom exception handlers uses `ArgumentHost`, which doesn’t provide detailed information about the context of the exception. This limitation makes it difficult to determine the source and context of the error, such as the method or class where the exception occurred. For more advanced exception handling scenarios, such as logging, analytics, or custom error responses, having access to `ExecutionContext` would be more beneficial. `ExecutionContext` extends `ArgumentHost` and provides additional methods to access the class and handler.

### Describe the solution you'd like

I propose extending the catch method to use `ExecutionContext` instead of `ArgumentHost`. This change would allow developers to access richer context data when handling exceptions, facilitating more detailed logging, error handling, and debugging. Specifically, `ExecutionContext` should provide methods to access information such as the handler method, and the class where the exception occurred.

### Teachability, documentation, adoption, migration strategy

- Teachability: The change should be straightforward for developers already familiar with NestJS’s existing context handling mechanisms. Documentation should include examples demonstrating how to access and use the additional information provided by `ExecutionContext`.
- Documentation: Update the official documentation to reflect the new `catch(exception: any, host: ExecutionContext)` signature and provide examples of how to use the new methods and properties available in `ExecutionContext`.
- Adoption: Developers can gradually adopt the new feature as needed. Since `ExecutionContext` extends `ArgumentHost`, existing code that relies on `ArgumentHost` methods will continue to work without modification.
- Migration Strategy: To ease the transition, provide a clear guide on how to update existing custom exception handlers to use `ExecutionContext`. Emphasize that the new approach is optional but offers additional benefits.

### What is the motivation / use case for changing the behavior?

The primary motivation for this change is to provide developers with more detailed contextual information when handling exceptions. By using `ExecutionContext` instead of `ArgumentHost`, developers can access the method and the class where the exception originated.

**Comment by jmcdo29** [comment]
It cannot be guaranteed that the rich context found in the `ExecutionContext` will exist inside the filter. In the case of 404s that Nest generally catches for you, there is no class or handler so you can't actually call those methods. Because of the uncertainty, we have to go with the safe option of the `ArgumentHost`. If you'd like to add context of where the error happened, you can do that with where you throw the error, or possibly in an interceptor before the error makes its way to the filter.

**Comment by toshmukhamedov** [comment]
Thanks for the clarification
