### ISSUE TITLE
A convenient `deprecated` tool for endpoints, following best practices 🥷

### ISSUE THREAD

**Issue by Avivbens** [nestjs/nest#13823]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Background 

Recently, I needed to deprecate a few endpoints and was considering the best way to measure and inform users of these changes. 
Apart from some monitoring tools that might assist with the migration, I find it challenging to communicate directly with my clients about changes and deprecations.

## The Idea

After exploring what the Nest.js ecosystem currently has to offer, I'm convinced that integrating these capabilities could greatly enhance the framework.

Based on extensive research, here are the best practices for HTTP communication in this context:

- Include a `Deprecation` header with the value set to `true`.
- Add a `Sunset` header specifying the scheduled sunset date.
- Provide a `Link` header with the URL of the new endpoint.
- Include a `Message` header with a friendly developer-to-developer message.

### Example

```typescript
@Controller()
export class MyController {

    @Deprecated({
        sunset: '2022-01-01' || new Date('2022-01-01') || 1640995200000,
        message: 'This endpoint is deprecated. See the migration guide for more information - https://example.com/migration-guide',
        link: '/some-new-endpoint',
    })
    @Get('some-endpoint')
    async someEndpoint(): Endpoint1Res {}

    @Get('some-new-endpoint')
    async someNewEndpoint(): Endpoint2Res {}
}

```

While I believe the `Link` and `Message` headers should be optional, that's a discussion for another time.

What are your thoughts on this approach? Could it be useful?

### NOTE

I came across issue #1266, which has remained inactive for a while. 
Given the advancements in Nest.js since 2018, I think it's time to revisit this topic.

### I would be more than happy to open a PR if that's a feature we want to implement 🙏

<br>
<hr>

### Teachability, documentation, adoption, migration strategy

There's no need for migration. 
It's simply a nice new feature.

### What is the motivation / use case for changing the behavior?

Described above

**Comment by micalevisk** [comment]
I guess you can have this already using the [decorator composition](https://docs.nestjs.com/custom-decorators#decorator-composition), right?

**Comment by Avivbens** [comment]
> I guess you can have this already using the [decorator composition](https://docs.nestjs.com/custom-decorators#decorator-composition) feature, right?

That's a cool one, yeah 
![thank-you](https://github.com/user-attachments/assets/4d434b55-056b-44cd-94e5-699d830d6169)


I still believe we should have a dedicated decorator for this. It seems like something we want to share among developers so it can be properly monitored. 
Nest.js should encourage the development community to follow best practices

**Comment by micalevisk** [comment]
> It seems like something we want to share 

I don't think we can be sure on this.

I think that before starting adding new APIs to the core, the community could create their own package to see an standard emerging.

**Comment by Avivbens** [comment]
> > It seems like something we want to share
> 
> I don't think we can be sure on this.
> 
> I think that before starting adding new APIs to the core (and so increasing the learning curve, usually), the community could create their own packages to see an standard emerging. This happened with few `@nestjs/*` packages

Agreed. 
It might be connected to the `@nestjs/common` package, where other HTTP-related decorators, like `Post`, are also located.

**Comment by Avivbens** [comment]
> > It seems like something we want to share
> 
> I don't think we can be sure on this.
> 
> I think that before starting adding new APIs to the core (and so increasing the learning curve, usually), the community could create their own packages to see an standard emerging. This happened with few `@nestjs/*` packages

You're right; I don't think the `@nestjs/core` package should include this change. 

However, what about the `@nestjs/common` package? 
It contains all the related decorators for HTTP, such as `Post`.

**Comment by micalevisk** [comment]
about _core_ I meant `@nestjs/*` packages

**Comment by Avivbens** [comment]
> about _core_ I meant `@nestjs/*` packages

Ohh, I see
If so, I think differently, as this is a fundamental component that almost every application needs. 

As mentioned, I think we need a standard here 🤞

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
