### ISSUE TITLE
Geospatial Query in GraphQL

### ISSUE THREAD

**Issue by hxdef2517** [nestjs/nest#1383]
Is there a way to make a geospatial query like 
```
SELECT id, name, ST_Distance_Sphere(table.location, point('$data[long]', '$data[lat]')) / 1000 AS distance, 
FROM table WHERE distance <= {$distance}   
```
in NestJS with GraphQL module? If yes could you please advice an approach of how to achieve that ?

**Comment by dhritzkiv** [comment]
What you're likely looking for is the [typeorm](https://github.com/nestjs/typeorm) module to use with postgresql in order to run your geospatial queries.

You'll have to implement GraphQL queries (geospatial or otherwise) on top of that.

**Comment by hxdef2517** [comment]
@dhritzkiv is there any way to do that using sequelize ? Like to build models as usual just maybe run a raw query for this specific part?

**Comment by dhritzkiv** [comment]
There should be a way to do it in sequelize, as it supports geospatial data types. However, I don't use sequelize, so I can't be of much help there. Make sure to check out [this documentation](https://docs.nestjs.com/recipes/sql-sequelize) on how to get started with sequelize and nestjs. And also be sure to read about `sequelize.fn`

Anyway, I think your original question is out of the scope of this framework.

**Comment by hxdef2517** [comment]
@dhritzkiv I've used sequelize with nest before, that's why asked. Alright anyway thanks. Will research more on that.

**Comment by kamilmysliwiec** [comment]
> @dhritzkiv I've used sequelize with nest before, that's why asked. Alright anyway thanks. Will research more on that.

I believe that this issue might be closed then.
