### ISSUE TITLE
Redirect from POST call triggers a POST call instead of a GET call only if StatusCode is passed

### ISSUE THREAD

**Issue by bertyhell** [nestjs/nest#13842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have this example code.
The expected flow is:
* browser does a GET /login
* nestjs redirect to login page of the identifity provider
* user enters credentials
* identity provider does a POST to /login-callback
* nestjs checks login credentials
* nestjs redirects to client application (http://localhost:3000)

expected behavior: Redirect are always GET calls
current behavior: Redirect is a POST call in certain cases

```typescript
import {
  Body,
  Controller,
  Get,
  Post,
  Redirect,
  HttpStatus,
  Res,
} from '@nestjs/common';
import { AppService } from './app.service';
import { Response } from 'express';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('login-1')
  @Redirect()
  async login1(@Body() body: any): Promise<any> {
    console.log('check login by checking tokens inside body', body);
    return {
      url: 'http://idp-url.com?redirectTo=http://my-server.com/login-callback-failing1',
      statusCode: HttpStatus.TEMPORARY_REDIRECT,
    };
  }

  @Post('login-callback-failing1')
  @Redirect()
  async loginCallbackFailing1(@Body() body: any): Promise<any> {
    console.log('check login by checking tokens inside body', body);
    return {
      url: 'http://localhost:3000',
      statusCode: HttpStatus.TEMPORARY_REDIRECT,
    };
  }

  @Get('login-2')
  @Redirect()
  async login2(@Body() body: any): Promise<any> {
    console.log('check login by checking tokens inside body', body);

    /**
     * Does an unexpected POST call to localhost:3000
     */
    return {
      url: 'http://idp-url.com?redirectTo=http://my-server.com/login-callback-failing2',
      statusCode: HttpStatus.TEMPORARY_REDIRECT,
    };
  }

  @Post('login-callback-failing2')
  async loginCallbackFailing2(
    @Body() body: any,
    @Res() res: Response,
  ): Promise<any> {
    console.log('check login by checking tokens inside body', body);
    res.redirect('http://localhost:3000');
  }

  @Get('login-3')
  @Redirect()
  async login3(@Body() body: any): Promise<any> {
    console.log('check login by checking tokens inside body', body);

    /**
     * Does an unexpected POST call to localhost:3000
     */
    return {
      url: 'http://idp-url.com?redirectTo=http://my-server.com/login-callback-works',
      statusCode: HttpStatus.TEMPORARY_REDIRECT,
    };
  }

  @Post('login-callback-works')
  async loginCallbackWorks(
    @Body() body: any,
    @Res() res: Response,
  ): Promise<any> {
    console.log('check login by checking tokens inside body', body);

    /**
     * Does the expected GET call to localhost:3000
     */
    res.redirect('http://localhost:3000');
  }
}

```

### Minimum reproduction code

https://codesandbox.io/p/devbox/nestjs-repl-forked-qrlhkl?workspaceId=7e7408d0-5f95-4c0a-9d7c-5ead17d801f2&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz880g4z0007356k8bcryw6n%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz880g4z0002356kg9oq5evl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz880g4z0004356kkrcfca0m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz880g4z0006356kufro5mgb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz880g4z0002356kg9oq5evl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz880g4y0001356k4yc86vsk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clz8818d70002356kaiaxuwcz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp.controller.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz880g4z0002356kg9oq5evl%2522%252C%2522activeTabId%2522%253A%2522clz8818d70002356kaiaxuwcz%2522%257D%252C%2522clz880g4z0006356kufro5mgb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz880g4z0005356ki37wzpsg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clz880g4z0006356kufro5mgb%2522%252C%2522activeTabId%2522%253A%2522clz880g4z0005356ki37wzpsg%2522%257D%252C%2522clz880g4z0004356kkrcfca0m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz880g4z0003356klcyh75r0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clz880g4z0004356kkrcfca0m%2522%252C%2522activeTabId%2522%253A%2522clz880g4z0003356klcyh75r0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Because of the identity provider i cannot provide a complete example. Only the code that is in the nestjs service with mock urls.

The browser should do a GET call to http://localhost:3000 at the end of the login flow
But now it does a POST call in certain cases:
which NEXTjs doesn't like so it throws a `Method not allowed | 405`
![image](https://github.com/user-attachments/assets/e76c24a3-029c-4c42-840f-98ff2c87f160)
![image](https://github.com/user-attachments/assets/6857815b-45d6-4a8c-87e6-e1a30e08d7c2)

### Expected behavior

The browser should do a GET call to http://localhost:3000 at the end of the login flow

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.4.3

### Packages versions

```json
{
    "@nestjs/common": "9.4.3",
    "@nestjs/config": "3.0.0",
    "@nestjs/core": "9.4.3",
    "@nestjs/platform-express": "9.4.3",
    "@nestjs/schedule": "3.0.1",
    "@nestjs/swagger": "7.1.1",
}
```

### Node.js version

22.1.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by c032** [comment]
Possibly relevant:

* https://expressjs.com/en/api.html#res.redirect
* https://docs.nestjs.com/controllers#redirection

Both sources state that a redirection defaults to using `HTTP 302 Found`. If you want your redirection to use a GET instead, then you might want to explicitly use [`HTTP 303 See Other`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303).

Even the MDN article for [HTTP 302 Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) says this:

> In the cases where you want the method used to be changed to GET, use 303 See Other instead.
