### ISSUE TITLE
Separate libs from apps in nest-cli.json file.

### ISSUE THREAD

**Issue by leandroluk** [nestjs/nest#13856]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Today when I create a new library like `nest g lib example` the CLI will change the nest-cli.json file adding a new reference into "projects" object. The problem is i can have a lib and a project with same name like "auth" (one for persist guards and other stuffs and other as the centered authentication app (when using multiple apps).

### Describe the solution you'd like

May separate apps from libs in two fields in `nest-cli.json` like this:

```
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "applications": { 
    "root": "apps/auth",
    "projects": {
      "auth": {
        "root": "apps/auth",
        "entryFile": "main",
        "sourceRoot": "apps/auth/src",
        "compilerOptions": {
          "tsConfigPath": "apps/auth/tsconfig.app.json"
        }
      },
    }
  },
  "libraries": {
    "auth": {
      "root": "libs/auth",
      "entryFile": "index",
      "sourceRoot": "libs/auth/src",
      "compilerOptions": {
        "tsConfigPath": "libs/auth/tsconfig.lib.json"
      }
    },
  }
}
``` 

### Teachability, documentation, adoption, migration strategy

just as there is an option for experimental features in nextjs, this could be defined in nest-cli.json and if the community that uses nest adheres, be implemented by default

### What is the motivation / use case for changing the behavior?

improve the readability of the `nest-cli.json` file and allow libraries and projects with the same name to exist since one project is not dependent on another so it does not need to be declared in the "module name mappers" or in the tsconfig.json files

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
