### ISSUE TITLE
need Esm support 

### ISSUE THREAD

**Issue by Ajayghoshm** [nestjs/nest#13851]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We need esm support for using adminjs going forward, as in case of python we have django admin as the best soultion, this is a proper requirement we we start using the nest js for actual products

### Describe the solution you'd like

Support ESM

### Teachability, documentation, adoption, migration strategy

Can use the thread for discusion

### What is the motivation / use case for changing the behavior?

  support for adminjs

**Comment by micalevisk** [comment]
> Can use the thread for discusion

we use discord for that, see https://discord.com/channels/520622812742811698/1116062757041733753
