### ISSUE TITLE
add a decorator for disabling the request body parser

### ISSUE THREAD

**Issue by eladchen-lusha** [nestjs/nest#13872]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to disable the default body parser for a specific method in a controller

### Describe the solution you'd like

Add a decorator that will allow me to read the request as a stream and parse the body by myself.

### Teachability, documentation, adoption, migration strategy

A decorator placed on method:

`@DisableBodyParser`

### What is the motivation / use case for changing the behavior?

When handling file uploads / webhooks /  large payloads its next to impossible.

I just need to be able to read the readable stream without loading everything into memory...

**Comment by micalevisk** [comment]
I don't like the ideia of introducing yet another decorator

We need to find a better way to handle that. Maybe with the [raw-body](https://docs.nestjs.com/faq/raw-body) feature in mind.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
