### ISSUE TITLE
[CLI] Revisit Bun support when creating new NestJS project

### ISSUE THREAD

**Issue by ccaspanello** [nestjs/nest#13881]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Previously there was an issue created for this:
[Provide bun as a package manager in the startup menu when we create a new nest project](https://github.com/nestjs/nest/issues/12359)

At the time this was not possible because Bun did not support the decorators.  However, this has been worked on (see https://bun.sh/blog/bun-v1.0.3?ref=nooptoday.com#emitdecoratormetadata-used-by-nest-js-typeorm-and-more) and some people are having success running it with Bun.
https://nooptoday.com/how-to-run-nestjs-with-bun/

I would really like to see bun as a first class citizen in the CLI tools, I've been favoring it over npm and yarn

### Describe the solution you'd like

Add Bun as an option when running `nest new my-project`

### Teachability, documentation, adoption, migration strategy

Links have been provided above.

### What is the motivation / use case for changing the behavior?

Bun is widely used and gaining popularity.  It seems reasonable to support it.

**Comment by micalevisk** [comment]
https://github.com/nestjs/nest-cli/pull/2223
