### ISSUE TITLE
microservices: multiple NATS clients created blocking application shutdown

### ISSUE THREAD

**Issue by borisovg** [nestjs/nest#13880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If several NATS messages are sent in succession several clients are created under the hood. When `client.close()` is called only one of these clients is closed and the rest continue blocking the event loop.

I suspect this might be due to the `await` here https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-nats.ts#L39

### Minimum reproduction code

https://github.com/borisovg/nest-nats-client-bug

### Steps to reproduce

1. Run `pnpm install`
2. Run `pnpm start`
3. Observe that `CONNECT` is logged twice.
4. Observe that application keeps running after 'SHOULD EXIT' log and there is a `heartbeats.ts` timer blocking the event loop.
5. Change `length: 2` to `length: 1` on L11 in `src/app.service.ts`
6. Run `pnpm start`
7. Observe that the application exits successfully.

### Expected behavior

Calling `client.close()` should close allow application to exit.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
"dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/microservices": "^10.4.0",
    "@nestjs/platform-express": "^10.0.0",
    "nats": "^2.28.2",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1",
    "wtfnode": "^0.9.3"
  }
}
```

### Node.js version

20.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in 10.4.1
