### ISSUE TITLE
Missing `@Injectable()` or `@Inject()` decorators silently injects `undefined`

### ISSUE THREAD

**Issue by glebbash** [nestjs/nest#13899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Missing `@Injectable()` or `@Inject()` decorators silently injects `undefined`.

This is a **major** issue as it does not prevent Nest.js application from starting and it's very easy to miss this in tests when mocking methods that use these broken injectables.

Notice the log output in the following [repro](https://github.com/glebbash/nest-injectable-repro/blob/a87b6cb92ad1671f0feb728cf6ac6205e032ea7c/src/app.service.ts#L9):

<table>
<tr>
<th>Broken</th>
<th>Working</th>
</tr>
<tr>
<td>

## Case 1
![image](https://github.com/user-attachments/assets/7d2596c1-9530-4279-acb9-9a4863acddf3)

</td>
<td>

## Case 2
![image](https://github.com/user-attachments/assets/42bf753f-3a51-407c-8b8d-e73fd04f32a2)

## Case 3
![image](https://github.com/user-attachments/assets/268ba3e5-4fc5-4b64-802f-7988c553fb7e)

</td>
</tr>
</table>

`Case 1` is unexpected and should not happen / everyone needs to be aware of this problem.

### Minimum reproduction code

https://github.com/glebbash/nest-injectable-repro

### Steps to reproduce

1. `npm ci`
2. `npm start`
3. Check logs

### Expected behavior

There should be an error thrown, stopping the application from initializing or this issue must be documented.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^10.3.1

### Packages versions

```
[System Information]
OS Version     : Linux 6.1.91-060191-generic
NodeJS Version : v20.15.1
NPM Version    : 10.7.0 

[Nest CLI]
Nest CLI Version : 10.3.0 

[Nest Platform Information]
platform-express version : 10.4.1
schematics version       : 10.1.0
terminus version         : 10.2.2
swagger version          : 7.2.0
testing version          : 10.3.1
common version           : 10.3.1
axios version            : 3.0.1
core version             : 10.3.1
cli version              : 10.3.0

[Warnings]
The following packages are not in the same minor version
This could lead to runtime errors
* Under version 10.4
- @nestjs/platform-express 10.4.1
* Under version 10.3
- @nestjs/common 10.3.1
- @nestjs/core 10.3.1
* Under version 10.1
- @nestjs/schematics 10.1.0
```

### Node.js version

20

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
this is expected due to TypeScript introspection limitations. I believe that you can use ESLint with plugins like https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/ to detect such cases.

Neither `@Inject()` nor `@Injectable()` are mandatory if you won't inject anything on that, which is why nestjs itself couldn't prevent it.

**Comment by glebbash** [comment]
But this lint plugin is not mentioned in the docs and does not come with default Nest.js installation.

@micalevisk I don't think it's very user friendly to not document known issues and just give link once to some third party solution in case someone stumbles upon it.

**Comment by micalevisk** [comment]
Got you. Few free to open a PR on the docs github repo to document that.

**Comment by jmcdo29** [comment]
For what it's worth, [there is a PR that I want to have merged that talked about what the `@Injectable()` decorator does and why it's important](https://github.com/nestjs/docs.nestjs.com/pull/2481)
