### ISSUE TITLE
Load Balancing for NestJS

### ISSUE THREAD

**Issue by hxdef2517** [nestjs/nest#1389]
As far as I know node instance while running using only one processor core, correct me if I'm wrong. Is there a way to setup load balancer while running 4 instances for each core of my project? I haven't found any thread on that.

Is there a way to build something like this: 
https://thecodebarbarian.com/building-your-own-load-balancer-with-express-js

**Comment by marcus-sa** [comment]
Use Nginx.

**Comment by hxdef2517** [comment]
@marcus-sa how does nginx helps in this case? Any example?

**Comment by brucecodezone** [comment]
i use pm2

**Comment by hxdef2517** [comment]
@brucecodezone thanks! I didn't know pm2 can do that :)
