### ISSUE TITLE
Nestjs code generator from OpenAPI yaml or json file 

### ISSUE THREAD

**Issue by mercale** [nestjs/nest#13891]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Nestjs OpenAPI integration is great but I still prefer to write the OpenApi in an swagger editor or Stoplight as I need business people to review the specification first before coding it.  I prefer Nestjs but I find it tasking (wates of time really) to rewrite the entire dto and entities over again.  I thought wouldnt it be great if Nestjs has a code generator that reads from a pre-created  OpenAPI yaml or json file. How awesome that would be being able to save a lot of time and able to focus on business logic. 

### Describe the solution you'd like

For a Nestjs code generator from an OpenAPI yaml or json.
Something like 
nest new {project} --oas [filename]
I expect the generator to bootstrap the required swagger libraries and update the main.ts, and create the resources (dto, entities, specs, controllers, module and services) that is the ideal ask, but I would settle with just creating the dto and entities. 

### Teachability, documentation, adoption, migration strategy

For teachability and documentation , would it be acceptable to use the **Hint** section to instruct people on how  to create a new project from an existing OpenAPI yaml or json file. I think a good place to put this would be on the  Overview/First-step page. 

Subsequently for adoption, or migration - there could be a **nest g resource [resource-name] --oas [filename] --path [path-name]** support as well.

### What is the motivation / use case for changing the behavior?

It would encourage more people who are following OpenAPI first approach to use Nestjs. I definitely would.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
