### ISSUE TITLE
NestFactory.createApplicationContext - error Cannot read properties of undefined (reading 'getOrThrow') in module service

### ISSUE THREAD

**Issue by LBeckX** [nestjs/nest#13905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to build a console helper with NestJS that works with a Mongoose database.
To build the Mongoose URI, I have created my own module which creates the URI for me.
When I start the application normally, everything works as it should and the DatabaseService is injected and in this service I can access the ConfigService inside of my database.service.ts.

main.ts:
const app = await NestFactory.create(AppModule);

But, when I call the CLI tool and start the app with
const app = await NestFactory.createApplicationContext(AppModule);
I get the following error:

```error
[Nest] 18400  - 22.08.2024, 16:53:40   ERROR [ExceptionHandler] Cannot read properties of undefined (reading 'getOrThrow')
TypeError: Cannot read properties of undefined (reading 'getOrThrow')
    at DatabaseService.getDatabaseUrl ([PATH]\src\module\database\database.service.ts:14:37)
    at InstanceWrapper.useFactory ([PATH]\src\app.module.ts:19:30)
    at Injector.instantiateClass ([PATH]\node_modules\@nestjs\core\injector\injector.js:368:55)
    at callback ([PATH]\node_modules\@nestjs\core\injector\injector.js:65:45)
    at async Injector.resolveConstructorParams ([PATH]\node_modules\@nestjs\core\injector\injector.js:144:24)
    at async Injector.loadInstance ([PATH]\node_modules\@nestjs\core\injector\injector.js:70:13)
    at async Injector.loadProvider ([PATH]\node_modules\@nestjs\core\injector\injector.js:97:9)
    at async [PATH]\node_modules\@nestjs\core\injector\instance-loader.js:56:13
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders ([PATH]\node_modules\@nestjs\core\injector\instance-loader.js:55:9)
```

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-error-in-cli

### Steps to reproduce

1. Create a console application file like: `my-cli-tool.ts`
2. Add the following code:

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);
  app.close()
}
bootstrap();
```

3. Create a database.module.ts and database.service.ts 

```ts
import { Module } from '@nestjs/common';
import { DatabaseService } from './database.service';
import { ConfigModule } from '@nestjs/config';

@Module({
  imports: [
    ConfigModule,
  ],
  providers: [
    DatabaseService,
  ],
  exports: [
    DatabaseService,
  ],
})
export class DatabaseModule {
}
```

```ts
import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class DatabaseService {
  private readonly _logger = new Logger(DatabaseService.name);

  constructor(
    private configService: ConfigService,
  ) {
  }

  getDatabaseUrl(): string {
    const user = this.configService.getOrThrow('MONGO_USER');
    const password = this.configService.getOrThrow('MONGO_PASSWORD');
    const host = this.configService.getOrThrow('MONGO_HOST');
    const port = this.configService.getOrThrow('MONGO_PORT');
    const database = this.configService.getOrThrow('MONGO_DATABASE');
    const uriSecure = `mongodb://${user}:*****@${host}:${port}/${database}`;

    this._logger.log(`Build database uri: ${uriSecure}`);

    return `mongodb://${user}:${password}@${host}:${port}/${database}`;
  }
}
```

4. put it all together in the app.module.ts

```ts
...imports

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),

    DatabaseModule,

    MongooseModule.forRootAsync({
      imports: [DatabaseModule],
      inject: [DatabaseService],
      useFactory: (databaseService: DatabaseService) => ({
        uri: databaseService.getDatabaseUrl(),
      }),
    }),
  ],
  controllers: [],
})
export class AppModule {
}

```

5. start the console application

```bash
npx tsx ./src/bin/my-cli-tool.ts
```

### Expected behavior

Just like when I start the application normally.
There is no error and the console programme runs normally.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/mongoose, @nestjs/cli, @nestjs/schematics, @nestjs/testing

### NestJS version

10.4.1

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.2.3",
    "@nestjs/core": "^10.0.0",
    "@nestjs/mongoose": "^10.0.10",
    "@nestjs/platform-express": "^10.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "date-fns": "^3.6.0",
    "mongoose": "^8.5.3",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1",
    "tsx": "^4.17.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^7.0.0",
    "@typescript-eslint/parser": "^7.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^7.0.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
```

### Node.js version

20.15.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
AFAIR `tsx` does not emit decorator metadata (meaning, the framework can't determine what to _inject_). I would suggest just using Nest CLI to run your CLI (or pre-compile your project first)

---

Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
