### ISSUE TITLE
GraphQL Directives Not Being Added to the IntrospectionQuery/Validation Pipeline

### ISSUE THREAD

**Issue by MDrooker** [nestjs/nest#13900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using this example-
https://stackblitz.com/edit/nestjs-typescript-starter-ysyvra?file=src%2Fshape%2Fshape.resolver.ts

Neither the ```@oneOf``` or the ```@deprecated``` directives are added to the Introspection Query.

For the ```@deprecated``` on, I would expect that its showing in any playground.

For the ```@oneOf``` the validation phase of the mutation should kick out a payload that looks like -
```mutation{
  createShape(profileConfigurn:"asd",input:{
    circle:{
      radius:12
      height:12
    }
    rectangle:{
      height:10
      width:10
    }
  })
}
```
It does not fail, and is allowed to succeed.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-ysyvra?file=src%2Fshape%2Fshape.resolver.ts

### Steps to reproduce

Submit 
```
mutation{
  createShape(profileConfigurn:"asd",input:{
    circle:{
      radius:12
      height:12
    }
    rectangle:{
      height:10
      width:10
    }
  })
}
````

### Expected behavior

Should fail validation

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

10.3

### Packages versions

```json
"dependencies": {
    "@graphql-yoga/nestjs": "^3.7.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.2.0",
    "@nestjs/platform-express": "^10.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "graphql": "^16.9.0",
    "reflect-metadata": "^0.2.0",
    "graphql-yoga": "^5.7.0",
    "rxjs": "^7.8.1"
  },
```

### Node.js version

18.20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past). https://github.com/nestjs/graphql
