### ISSUE TITLE
JSON format for logs

### ISSUE THREAD

**Issue by balaji-atoa** [nestjs/nest#13908]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

the main problem devs face is will be with maintaining the application logs. The current format, is just a text and not structured which will not motivate devs to use NestLogger for production. it would be better if there might be an option to parse logs to json by default. btw thanks for the amazing framework! :)

### Describe the solution you'd like

Add an option like `jsonLayout`(string) which will be passed dynamically by the user to the module, if it is json, logs will be printed as JSON format, else by default it will follow our default logs format. This will provide better flexibility and makes it scalable for the future.

### Teachability, documentation, adoption, migration strategy

.

### What is the motivation / use case for changing the behavior?

dev experience

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/13561
