### ISSUE TITLE
Add a way to pass loader options to custom grpc-loader

### ISSUE THREAD

**Issue by eladhaim** [nestjs/nest#13930]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We heavily rely on protobuf and use [ts-proto](https://github.com/stephenh/ts-proto) to generate our package definitions. To handle the generated code, we've had to create our own gRPC loader. However, while we have the option to pass a custom gRPC loader, we currently cannot pass custom gRPC options. Ideally, we'd like the loader object within GrpcOptions to be of type any or a generic type that we can override to customize the options as needed.

### Describe the solution you'd like

Our problem is just a type issue, converting the loader object to any/generic with default will do the job.

### Teachability, documentation, adoption, migration strategy

Today:
```
     ClientsModule.register([
      {
        name: 'GRPC_CLIENT_NAME',
        transport: Transport.GRPC,
        options: {
          package: 'testPackage',
          protoPath: 'proto_path',
          protoLoader: 'our custom loader',
          url: 'localhost:4001',
          loader: {
             // @ts-ignore
             newOption: 'new option'
          },
        },
      }
    ]),
```    
   After the change:
   ``` 
      ClientsModule.register([
      {
        name: 'GRPC_CLIENT_NAME',
        transport: Transport.GRPC,
        options: {
          package: 'testPackage',
          protoPath: 'proto_path',
          protoLoader: 'our custom loader',
          url: 'localhost:4001',
          loader: {
             newOption: 'new option'
          },
        },
      }
    ])
```
### What is the motivation / use case for changing the behavior?

Adding more flexibility to the server/client of grpc

**Comment by wrspada02** [comment]
Do you think would be nice pass some kind of generic type to the loader object instead apply type any? Just to keep the type safe. Also, I'll figure it out and try to implement this.

**Comment by eladhaim** [comment]
yes sure i think generic type will be great, i can submit a pr if needed.

**Comment by wrspada02** [comment]
May I try to implement this? It'd be my first contribuition on the open-source world.

**Comment by eladhaim** [comment]
go ahead, i think it is a good issue to start with

**Comment by wrspada02** [comment]
Thank you. Any updates I'll let you know.

**Comment by wrspada02** [comment]
Well, I think I did what you meant. I ain't able to push a PR on this repository, however, I just did a fork and pushed it there. Could you check it out and confirm if makes sense?

![image](https://github.com/user-attachments/assets/21828c48-e4d4-496d-8483-76bfd787b671)

https://github.com/wrspada02/nest/commit/dc3d1af687adb91bc3b96b59b0b1b6d09c4a8f21

**Comment by eladhaim** [comment]
👍

**Comment by wrspada02** [comment]
Hello @nestjs, May we create a PR for this type feature addition? I ain't able to open a PR for this repository.

**Comment by CaioF** [comment]
@eladhaim quick question, is your custom loader able to serialize/deserialize google.protobuf types when generating with ts-proto? Because I have an issue where nestJS seems to ignore the wrappers from ts-proto and therefore I cannot use any of the well known types. https://github.com/stephenh/ts-proto/issues/1106#issuecomment-2336522124

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/13941
