### ISSUE TITLE
path-to-regexp npm audit high vulnerable

### ISSUE THREAD

**Issue by danielehrhardt** [nestjs/nest#13955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In express, @nestjs/core, @nestjs/platform-express there is a package used "path-to-regexp" what causes a npm high security vulnerable. For Version 0.1.7 there is a path 0.1.10 but for 3.2.0 there is no patch currently available. 
This should be updated. 

### Minimum reproduction code

https://github.com/pillarjs/path-to-regexp/commit/29b96b4a1de52824e1ca0f49a701183cc4ed476f

### Steps to reproduce

npm install
npm audit

### Expected behavior

no high security vulnerable

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.3.10

### Packages versions

latest

### Node.js version

20

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by danielehrhardt** [comment]
https://github.com/pillarjs/path-to-regexp/security/advisories/GHSA-9wv6-86v2-598j

**Comment by autorejecttop** [comment]
`@nestjs/platform-fastify` is also affected by this

**Comment by autorejecttop** [comment]
I tried reproducing this by:

1. `nest new project-name`
2. `npm install @nestjs/microservices @nestjs/platform-fastify @nestjs/platform-socket.io @nestjs/platform-ws @nestjs/testing @nestjs/websockets`
3. `npm audit`

and got this output:

```
# npm audit report

path-to-regexp  <=0.1.9 || 0.2.0 - 7.2.0
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
fix available via `npm audit fix --force`
Will install @nestjs/platform-express@7.0.0, which is a breaking change
node_modules/@fastify/middie/node_modules/path-to-regexp
node_modules/express/node_modules/path-to-regexp
node_modules/path-to-regexp
  @fastify/middie  *
  Depends on vulnerable versions of path-to-regexp
  node_modules/@fastify/middie
    @nestjs/platform-fastify  *
    Depends on vulnerable versions of @fastify/middie
    Depends on vulnerable versions of @nestjs/core
    Depends on vulnerable versions of path-to-regexp
    node_modules/@nestjs/platform-fastify
  @nestjs/core  <=2.0.2 || 5.2.0-next - 5.7.4 || >=6.11.0-next.1
  Depends on vulnerable versions of @nestjs/microservices
  Depends on vulnerable versions of @nestjs/platform-express
  Depends on vulnerable versions of @nestjs/websockets
  Depends on vulnerable versions of path-to-regexp
  node_modules/@nestjs/core
    @nestjs/microservices  >=7.0.1
    Depends on vulnerable versions of @nestjs/core
    Depends on vulnerable versions of @nestjs/websockets
    node_modules/@nestjs/microservices
    @nestjs/platform-express  *
    Depends on vulnerable versions of @nestjs/core
    Depends on vulnerable versions of express
    node_modules/@nestjs/platform-express
      @nestjs/testing  >=7.0.1
      Depends on vulnerable versions of @nestjs/core
      Depends on vulnerable versions of @nestjs/microservices
      Depends on vulnerable versions of @nestjs/platform-express
      node_modules/@nestjs/testing
    @nestjs/websockets  >=7.0.1
    Depends on vulnerable versions of @nestjs/core
    Depends on vulnerable versions of @nestjs/platform-socket.io
    node_modules/@nestjs/websockets
      @nestjs/platform-socket.io  >=8.0.0-alpha.1
      Depends on vulnerable versions of @nestjs/websockets
      node_modules/@nestjs/platform-socket.io
      @nestjs/platform-ws  >=8.0.0-alpha.1
      Depends on vulnerable versions of @nestjs/websockets
      node_modules/@nestjs/platform-ws
  express  4.0.0-rc1 - 4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
  Depends on vulnerable versions of path-to-regexp
  node_modules/express

11 high severity vulnerabilities

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.
```

**Comment by paskaran** [comment]
The problem is audit pipelines failing :D downgrading to 6.10.14 is not an option for us. Hopefully the fix arrives soon :). Thanks

**Comment by danielehrhardt** [comment]
https://github.com/nestjs/nest/pull/13957

**Comment by micalevisk** [comment]
I don't think that upgrading `path-to-regexp` from v3 to v8 is a good short-term solution because we might bring breaking changes (see [v6](https://github.com/pillarjs/path-to-regexp/releases/tag/v6.0.0), [v7](https://github.com/pillarjs/path-to-regexp/releases/tag/v7.0.0), and others). I guess we need to find a way to let the dev upgrade it on their side instead

**Comment by micalevisk** [comment]
looks like that the `path-to-regexp`'s team won't backport that fix tho: https://github.com/pillarjs/path-to-regexp/issues/318

**Comment by micalevisk** [comment]
thanks

so for those that really don't use `path-to-regexp` (ie., no regex paths), you can use this patch for `@nestjs/core` (and `express@4`, in my case) for now:

- [`express+4.19.2.patch`](https://pastebin.com/raw/xNS2CwAL)
- [`@nestjs+core+10.4.1.patch`](https://pastebin.com/raw/DP6MLg4J)

**Comment by danielehrhardt** [comment]
https://github.com/pillarjs/path-to-regexp/issues/317#issuecomment-2342092483
3.3.0 published
