### ISSUE TITLE
sse close event not trigger

### ISSUE THREAD

**Issue by wenghongtian** [nestjs/nest#13956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

sse close event not trigger

### Minimum reproduction code

https://github.com/wenghongtian/nest-sse

### Steps to reproduce

1. pnpm i
2. pnpm start
3. call 'http://localhost:3004/api/workflow/sse/application/run' with sse and post method
4. close the connect
5. `req.on('close', () => {
      console.log('request closed');
    });` not trigger

### Expected behavior

When the socket is closed, 'close' event can trigger

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

[System Information]
OS Version     : macOS 23.1.0
NodeJS Version : v20.12.2
PNPM Version    : 8.14.3 

[Nest CLI]
Nest CLI Version : 10.4.2 

[Nest Platform Information]
platform-express version : 10.3.10
microservices version    : 10.3.10
platform-ws version      : 10.3.10
websockets version       : 10.3.10
schematics version       : 10.1.2
throttler version        : 5.2.0
passport version         : 10.0.3
swagger version          : 7.4.0
testing version          : 10.3.10
common version           : 10.3.10
config version           : 3.2.3
axios version            : 3.0.2
core version             : 10.3.10
jwt version              : 10.2.0
cli version              : 10.4.2

### Node.js version

20.12.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
maybe related with this issue: #10389

**Comment by kamilmysliwiec** [comment]
Duplicate https://github.com/nestjs/nest/issues/10389
