### ISSUE TITLE
Proposal to Replace Outdated Terminology with Inclusive Alternatives

### ISSUE THREAD

**Issue by muhabdulkadir** [nestjs/nest#13950]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Yes, the current terminology in the NestJS framework (e.g., whitelist, forbidNonWhitelisted) is considered non-inclusive. As modern development practices increasingly emphasize inclusive and neutral language, this terminology may be seen as outdated and potentially exclusionary.

### Describe the solution you'd like

I propose replacing the terms whitelist and forbidNonWhitelisted with more inclusive alternatives such as allowList and forbidNonAllowListed. This change would align with current best practices in inclusive language and improve the framework's alignment with modern standards.

### Teachability, documentation, adoption, migration strategy

Update the official NestJS documentation to use the new terminology and provide deprecation warnings for the old terms, with a clear timeline for their removal.

### What is the motivation / use case for changing the behavior?

The motivation is to enhance inclusivity in programming language and terminology, reflecting contemporary standards and practices. Adopting inclusive language can help create a more welcoming and respectful environment for all developers.

**Comment by RobertMurfin** [comment]
No. As a white man I would feel less included if these terms were to change. Thank you for thinking about my feelings though, fortunately I'm mentally sane.

**Comment by kamilmysliwiec** [comment]
These are coming from the `class-validator` package, not NestJS. Feel free to report this issue in their repository
