### ISSUE TITLE
Vulnerability in Express < 4.20.0

### ISSUE THREAD

**Issue by bu-michael** [nestjs/nest#13960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Express is used by @nestjs/platform-express in version 4.19.2: https://github.com/nestjs/nest/blob/master/packages/platform-express/package.json#L23

### Minimum reproduction code

https://github.com/expressjs/express/security/advisories/GHSA-qw6h-vgh9-j6wx

### Steps to reproduce

See https://github.com/expressjs/express/security/advisories/GHSA-qw6h-vgh9-j6wx

### Expected behavior

Update to Express 4.20.0, which has been released on September 10 2024: https://github.com/expressjs/express/releases/tag/4.20.0

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.1

### Packages versions

[System Information]
OS Version : Linux 5.15.153.1-microsoft-standard-WSL2
NodeJS Version : v20.17.0
NPM Version : 10.8.3

[Nest CLI]
Nest CLI Version : 10.4.5

[Nest Platform Information]
platform-express version : 10.4.1
cache-manager version : 2.2.2
schematics version : 10.1.4
throttler version : 6.2.1
mongoose version : 10.0.10
terminus version : 10.2.3
swagger version : 7.4.0
testing version : 10.4.1
common version : 10.4.1
config version : 3.2.3
axios version : 3.0.3
core version : 10.4.1
jwt version : 10.2.0
cli version : 10.4.5

### Node.js version

20.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by wtrzy** [comment]
Same here. `npm audit` returns security issue inside @nestjs/platform-express -> express -> serve-static -> send:
```
git pr
Already up to date.
bash-4.4# npm audit 
# npm audit report

body-parser  <1.20.3
Severity: high
body-parser vulnerable to denial of service when url encoding is enabled - https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
fix available via `npm audit fix --force`
Will install @nestjs/core@6.10.14, which is a breaking change
node_modules/body-parser
  @nestjs/platform-express  *
  Depends on vulnerable versions of @nestjs/core
  Depends on vulnerable versions of body-parser
  Depends on vulnerable versions of express
  node_modules/@nestjs/platform-express
    @nestjs/core  5.2.0-next - 5.7.4 || >=6.11.0-next.1
    Depends on vulnerable versions of @nestjs/platform-express
    Depends on vulnerable versions of path-to-regexp
    node_modules/@nestjs/core
      @nestjs/testing  >=7.0.1
      Depends on vulnerable versions of @nestjs/core
      Depends on vulnerable versions of @nestjs/platform-express
      node_modules/@nestjs/testing
  express  <=4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
  Depends on vulnerable versions of body-parser
  Depends on vulnerable versions of path-to-regexp
  Depends on vulnerable versions of send
  Depends on vulnerable versions of serve-static
  node_modules/express


path-to-regexp  <=0.1.9 || 0.2.0 - 7.2.0
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
fix available via `npm audit fix --force`
Will install @nestjs/core@6.10.14, which is a breaking change
node_modules/express/node_modules/path-to-regexp
node_modules/path-to-regexp

send  <0.19.0
Severity: moderate
send vulnerable to template injection that can lead to XSS - https://github.com/advisories/GHSA-m6fv-jmcg-4jfg
fix available via `npm audit fix`
node_modules/send
  serve-static  <=1.16.0
  Depends on vulnerable versions of send
  node_modules/serve-static


8 vulnerabilities (2 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by mikheyrojo** [comment]
It would be great if path-to-regexp is updated in `core` and `platform-express` to the version without HIGH vulnerability

**Comment by MeiravShimelman** [comment]
Any update on it? when the new version will come ?
