### ISSUE TITLE
ERROR [ExceptionsHandler] (0 , rxjs_1.lastValueFrom) is not a function

### ISSUE THREAD

**Issue by CodeSenior** [nestjs/nest#13975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello everyone,
I have this problem when I launch the default query in /GET of Hello, my Nest application crashes and I have this in log.

- Node: v21.6.2
- Pnpm: 8.15.4
- Nest: 7.6.0

`[Nest] 51772  - 16/09/2024 18:32:43   ERROR [ExceptionsHandler] (0 , rxjs_1.lastValueFrom) is not a function
TypeError: (0 , rxjs_1.lastValueFrom) is not a function
    at RouterResponseController.transformToResult (/Users/amar/Projects/TEMPLATES/base-nestjs/node_modules/.pnpm/@nestjs+core@10.4.2_@nestjs+common@10.4.2_@nestjs+platform-express@10.4.2_reflect-metadata@0.1.14_rxjs@6.6.7/node_modules/@nestjs/core/router/router-response-controller.js:33:45)
    at /Users/amar/Projects/TEMPLATES/base-nestjs/node_modules/.pnpm/@nestjs+core@10.4.2_@nestjs+common@10.4.2_@nestjs+platform-express@10.4.2_reflect-metadata@0.1.14_rxjs@6.6.7/node_modules/@nestjs/core/router/router-execution-context.js:174:52
    at /Users/amar/Projects/TEMPLATES/base-nestjs/node_modules/.pnpm/@nestjs+core@10.4.2_@nestjs+common@10.4.2_@nestjs+platform-express@10.4.2_reflect-metadata@0.1.14_rxjs@6.6.7/node_modules/@nestjs/core/router/router-execution-context.js:47:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/amar/Projects/TEMPLATES/base-nestjs/node_modules/.pnpm/@nestjs+core@10.4.2_@nestjs+common@10.4.2_@nestjs+platform-express@10.4.2_reflect-metadata@0.1.14_rxjs@6.6.7/node_modules/@nestjs/core/router/router-proxy.js:9:17`

* **app.controller.ts**
`import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('hello')
  getHello(): string {
    return this.appService.getHello();
  }
}`

***app.module**
`import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: ['.env.local', '.env'],
      isGlobal: true,
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}`

***app.service.ts**
`import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  getHello(): string {
    return 'Hello World!';
  }
}`

*env
#NEST
PORT=3001
NODE_ENV=localhost

### Minimum reproduction code

https://github.com/

### Expected behavior

the application must return the Hello at /GET/hello

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

`    "@nestjs/common": "^10.4.2",
    "@nestjs/config": "^3.2.3",
    "@nestjs/core": "^10.4.2",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.4.2",
`

### Node.js version

21.6.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by kamilmysliwiec** [comment]
Just make sure to have the latest version of RxJS installed in your project and you'll be fine.
