### ISSUE TITLE
Interceptors seemingly behave differently than other components in Nest.JS when it comes to DI

### ISSUE THREAD

**Issue by jpage-godaddy** [nestjs/nest#13972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In a dynamic module, providing an interceptor with `useValue` does not cause that instance to be made available when using the interceptor. Instead, the DI system tries to instantiate a new interceptor. See this [StackOverflow question](https://stackoverflow.com/questions/78983451/registered-nest-js-interceptor-not-being-used-for-dependency-injection/78983579#78983579) for more details and how I was able to work around this counter-intuitive behavior.

### Minimum reproduction code

See this [code sandbox](https://codesandbox.io/p/devbox/tender-dewdney-dx3s5h?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm115h5sa00072a6de83rda4i%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm115h5sa00022a6d0tx5c2zl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm115h5sa00042a6dsi4wvop0%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm115h5sa00062a6d0xuzl0ou%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm115h5sa00022a6d0tx5c2zl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm115h5sa00012a6dml6713de%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm116mic400022a6cji4qnknu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fanother.module.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm115h5sa00022a6d0tx5c2zl%2522%252C%2522activeTabId%2522%253A%2522cm116mic400022a6cji4qnknu%2522%257D%252C%2522cm115h5sa00062a6d0xuzl0ou%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm115h5sa00052a6d6pza96z0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%257D%255D%252C%2522id%2522%253A%2522cm115h5sa00062a6d0xuzl0ou%2522%252C%2522activeTabId%2522%253A%2522cm115h5sa00052a6d6pza96z0%2522%257D%252C%2522cm115h5sa00042a6dsi4wvop0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm115h5sa00032a6degw8u6m4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522cm115h5sa00042a6dsi4wvop0%2522%252C%2522activeTabId%2522%253A%2522cm115h5sa00032a6degw8u6m4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Start the app

### Expected behavior

The app should start up without errors. To me, the behavior should untuitively be that because I instantiated `SomeInterceptor` and provided it in its owning module, that instance should be what `@UseInterceptors(SomeInterceptor)` resolves. Instead, it invoke the constructor and tries to resolve its parameters.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```
[System Information]
OS Version     : Linux 5.15.153.1-microsoft-standard-WSL2
NodeJS Version : v20.15.1
NPM Version    : 10.7.0 

[Nest CLI]
Nest CLI Version : 10.4.5 

[Nest Platform Information]
platform-express version : 10.4.1
schematics version       : 10.1.1
terminus version         : 10.2.3
swagger version          : 7.4.0
testing version          : 10.4.1
common version           : 10.3.10
axios version            : 3.0.2
core version             : 10.4.1
cli version              : 10.4.5
```

### Node.js version

20

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
this is the expected behavior, not a bug

Would you like to create a _feature request_ instead?

**Comment by jpage-godaddy** [comment]
Yeah, kind of fuzzy... I would say the fact that the behavior is counter-intuitive _could_ be called a bug, but yeah implementing the expected behavior would be a new feature.

**Comment by micalevisk** [comment]
as you've used a _bug report_, this won't help us to address the issue. That's why we have different issues templates

**Comment by KostyaTretyak** [comment]
These issues arise because [interceptors in NestJS are not considered providers](https://dev.to/kostyatretyak/nestjs-vs-ditsmod-di-features-for-interceptors-guards-pipes-and-filters-5bcm). Plus, interceptors are actually a group of providers that must register under one common token. But NestJS explicitly does not have multiproviders, so you cannot do as follows:

```ts
// ...
providers: [
  { provide: HTTP_INTERCEPTORS, useExisting: SomeInterceptor, multi: true },
  { provide: SomeInterceptor, useValue: instanceOfSomeInterceptor }
]
```
