### ISSUE TITLE
Nestjs Module Drizzle

### ISSUE THREAD

**Issue by luas10c** [nestjs/nest#13983]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

What do you think about an official drizzle module for nestjs?

example, @nestjs/drizzle

### Describe the solution you'd like

I am willing to help remove the module to facilitate the connection using drizzle with nestjs

### Teachability, documentation, adoption, migration strategy

It wouldn't be too difficult to also contribute to the documentation on how to use it.

### What is the motivation / use case for changing the behavior?

We are seeing increasing use of drizzle as a direct competitor to prism and typeorm.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/drizzle
