### ISSUE TITLE
Hi, is there a way that I can save the stacktrace or log to .log file？

### ISSUE THREAD

**Issue by RaymondLuker** [nestjs/nest#1400]
![image](https://user-images.githubusercontent.com/44513350/50438015-26276000-0927-11e9-8f04-47f54ae25b1d.png)
I want to save the information in the console window to a local file such as .log file. Is there a method? I do use simple-node-logger but still I want to save those messeges

**Comment by BrunnerLivio** [comment]
In Linux you can simply pipe the stdout to a file:
`npm run start > app.log`

in Powershell you can use [Out-File](
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-6)

So logger libs also support direct file output handling within your app code.

**Comment by RaymondLuker** [comment]
> In Linux you can simply pipe the stdout to a file:
> `npm run start > app.log`
> 
> in Powershell you can use [Out-File](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-6)
> probably like this (not a powershell expert though)
> `npm run start | Out-File -filepath app.log`
> 
> So logger libs also support direct file output handling within your app code.

Thank you so much, I will give it a try and see if it works
