### ISSUE TITLE
platform-fastify returning 404 on HEAD requests

### ISSUE THREAD

**Issue by tuxmachine** [nestjs/nest#14016]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

#13493

### NestJS version

10.3.9

### Describe the regression

Previously a HEAD request used to respond with status `200`. Now it responds with a `404`.

### Minimum reproduction code

[repoduction repo](https://github.com/tuxmachine/nest-fastify-head/blob/master/package.json#L21)

### Input code

```ts
curl -I http://localhost:3000
```

### Expected behavior

Status 200 if the endpoint exists

### Other

The new Fastify `route(...)` supports an array of HTTP methods. The simplest solution might be to just inject routes with `method: [method, 'HEAD']`

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/14017
