### ISSUE TITLE
Dont delete logs when app starts

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#14033]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When the NestJS app starts previous logs are removed. I would like to have an option to keep them.

I tried using `--preserveWatchOutput` but this only preserves logs when file changes are detected in watch mode.

### Describe the solution you'd like

Add a new flag to `nest start` that does preserve previous logs

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

This is unfortunate because I am running a monorepo that does steps before the NestJS app starts (e.g. compile a library and run Drizzle Studio). I dont want to lose this logs, e.g. Drizzle Studio shows a link to their web ui.

**Comment by micalevisk** [comment]
I'm not sure about adding flags for this

Any suggestion on the name of the flag that you're expecting?

**Comment by MickL** [comment]
I would prefer config option in nest-cli.json but I think there is no config option for preserveWatchOutput, too.

Is there any reason to clear the logs on startup? Personally I would remove that for all cases. 

If you add a flag, you could name it —preserveLogs

**Comment by micalevisk** [comment]
to be honest, I guess what you're looking for can be addressed with [`preserveWatchOutput`](https://www.typescriptlang.org/tsconfig/#preserveWatchOutput) in your tsconfig file under `compilerOptions`. Have you tried this out?

**Comment by MickL** [comment]
This is what the Nest flag does, it keeps logs after file change. But this issue is about the initial clearing of the logs when a Nest app starts.

**Comment by micalevisk** [comment]
> the initial clearing of the logs when a Nest app starts.

I didn't get what do you mean because here is working just fine:

![image](https://github.com/user-attachments/assets/2b87c9a5-3572-4244-b8d6-bfcc2bc74816)

**Comment by MickL** [comment]
I think it happens only when starting multiple processes at once e.g. with Turbo Repo

**Comment by micalevisk** [comment]
so I'm not sure if we can address this in `@nestjs/cli` :thinking:
