### ISSUE TITLE
Body with files and textfields

### ISSUE THREAD

**Issue by mak7an** [nestjs/nest#14032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
  // @UseInterceptors(FileInterceptor('file'))
  @Post('file')
  uploadFile(
    @Body() body: SampleDto,
    // @UploadedFile() file: Express.Multer.File,
  ) {
    return {
      body,
      // file: file, // .buffer.toString(),
    };
  }
```

With `FileInterceptor` response is `{"body":{"data":"test.mp3","test":"true"}}`. Test property if string but it is boolean.

Without `FileInterceptor` response is ``{"body":{"data":"test.mp3","test":true}}`.  Test is boolean.

If I use that body to update data `this.userRepository.assign(user, data)` I get errors from mikro-orm (bacause id is string and boolean values are string type) validation and nest validation pipe.

> ValidationError: Trying to set User.test of type 'boolean' to 'true' of type 'string'.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/29-file-upload

### Expected behavior

Boolean to be boolean and integer integer.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

Just run sample

### Node.js version

21.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Multer (the underlying form body parser) makes everything that is not a file a string. You'll need to add an explicit `@Transform()` if you want the `ValidationPipe` to handle that

**Comment by mak7an** [comment]
@jmcdo29 thank you, I didn't think about that
