### ISSUE TITLE
Support pipes on `@Headers()` decorator

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#14047]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

> [!NOTE]
> This is a duplicate of a really old issue: #279 (and few others)
> I just want to give this a conclusion on whether this was by design or just because of maintenance burden, so I can improve the docs to prevent more issues about it.

We cannot supply pipes to the `@Headers()` from `@nestjs/common`

![image](https://github.com/user-attachments/assets/a5130777-b5a3-49e3-9761-09121b93861f)

<details>
<summary>So when we want to do some kind of transformation and/or validation over request headers, we can use the <code>createParamDecorator</code> utility along with the <code>validateCustomDecorators:true</code> option from the built-in <code>ValidationPipe</code> like this:
</summary>

```ts
import { Controller, createParamDecorator, ExecutionContext, Get, ValidationPipe } from '@nestjs/common';
import { IsNotEmpty } from 'class-validator';

const ReqHeaders = createParamDecorator((_: never, ctx: ExecutionContext) => {
  const req = ctx.switchToHttp().getRequest();
  return req.headers;
});

class DTO {
  @IsNotEmpty()
  'x-foo': string;
}

@Controller()
export class AppController {
  @Get()
  hello(
    @ReqHeaders(new ValidationPipe({ validateCustomDecorators: true })) reqHeaders: DTO,
  ) {
    return {
      reqHeaders,
    }
  }
}
```

</details>

To me, this solution looks hacky as we can use pipes over query and path parameters already:
1. it is tight coupled with the underlying http framework because of the `.getRequest()`'s return
2. one should know that if they want to use the `ValidationPipe`, they'd have to supply that `validateCustomDecorators` flag.
3. it is not clear why `@Headers()` doesn't works the same as the others decorators that act over the request object. And so it seems counterintuitive, which leads to confusion: #11404 #4798 #356

### Describe the solution you'd like

Make the `@Headers()` decorator work just like `@Query()` and `@Param()` ones.

So I expect the following patterns to work:

```ts
@Headers(ValidationPipe) headers: MyDto
@Headers(ValidationPipe, AnotherPipe) headers: MyDto

@Headers('x-foo', ValidationPipe) headers: MyDto,
@Headers('x-foo', ValidationPipe, AnotherPipe) headers: MyDto

// when ValidationPipe is bind globally or per route
@Headers() headers: MyDto
```

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

All of the aforementioned details about the solution to use pipes over request headers doesn't looks quite good from a DX PoV

**Comment by kamilmysliwiec** [comment]
If we enable pipes for headers, the global validation pipe would run for all arguments annotated with @Headers(), which would:

- introduce a breaking change
- result in a performance drop

That said, most headers typically don't need complex validation, as they are usually just strings and rarely require data transformations or type conversions.
