### ISSUE TITLE
Compatibility issue with @fastify/cookie and Fastify version 5.x in @nestjs/platform-fastify.

### ISSUE THREAD

**Issue by Prakash-Banjade** [nestjs/nest#14045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

There is a compatibility issue between `@nestjs/platform-fastify` and `@fastify/cookie`. The `@nestjs/platform-fastify` package depends on Fastify version `4.28.1`, while the latest version of `@fastify/cookie` requires Fastify `^5.0.0`. This results in the following TypeScript error when trying to use `@fastify/cookie` with a NestJS application:

Argument of type 'FastifyCookie' is not assignable to parameter of type 'FastifyPluginCallback<FastifyCookieOptions> | FastifyPluginAsync<FastifyCookieOptions> | Promise<...> | Promise<...>'.

### Minimum reproduction code

https://github.com/Prakash-Banjade/learn-fastify/tree/master/fastify-nestjs

### Steps to Reproduce

1. Create a new NestJS application using the Fastify adapter.
2. Install `@fastify/cookie` and try to register it in the application.
3. Observe the TypeScript error due to the version mismatch.

### Expected Behavior
I expected to be able to register the `@fastify/cookie` plugin in a NestJS application using the Fastify adapter without encountering any TypeScript errors. Specifically, the `@fastify/cookie` plugin should work seamlessly with the version of Fastify (`4.28.1`) that `@nestjs/platform-fastify` depends on, or `@nestjs/platform-fastify` should be updated to support Fastify `^5.0.0`.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.4

### Packages versions

[System Information]
OS Version     : Windows 10.0.22631
NodeJS Version : v20.13.1
NPM Version    : 10.8.2 

[Nest CLI]
Nest CLI Version : 10.4.5 

[Nest Platform Information]
platform-fastify version : 10.4.3
mapped-types version     : 2.0.5
schematics version       : 10.1.4
throttler version        : 6.2.1
swagger version          : 7.4.2
typeorm version          : 10.0.2
testing version          : 10.4.3
common version           : 10.4.3
config version           : 3.2.3
core version             : 10.4.4
jwt version              : 10.2.0
cli version              : 10.4.5
 version                 : 2.0.2

### Node.js version

20.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
please see https://github.com/nestjs/nest/issues/14029#issuecomment-2370338697 and https://github.com/nestjs/nest/pull/13990#issuecomment-2360122504
