### ISSUE TITLE
Missing JWT token on my request halts totally the API execution 

### ISSUE THREAD

**Issue by sergio-vega-over** [nestjs/nest#14041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I target the endpoint that requires the JWT token, bu I dont incldue this JWT token, the API halts and stops processing other requests. I guess this should not be the correct behaviour?

I get the unauthorized response on the postman, but stilll the API halts. I am expecting to receive the unaith reposne, but still process other requests. 

i get this error:                
```

throw err || new common_1.UnauthorizedException();
                             ^
UnauthorizedException: Unauthorized
```

this happens on this piece of code inside the package passport:

        handleRequest(err, user, info, context, status) {
            if (err || !user) {
                throw err || new common_1.UnauthorizedException();
            }
            return user;
        }

seems to throw a exception that is not handle properly, so it halts the api. 
### Minimum reproduction code

.

### Steps to reproduce

I am just executing with, no custom stuff on the guard. I applied this guar to my endpoint. 

export class JwtAuthPermissionsGuard extends AuthGuard('jwt')

same for the strategyclass . I am using the default one:

@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor() {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      ignoreExpiration: false,
      secretOrKey: JWT_SECRET,
    });
  }

  validate(payload: any) {
    console.log(payload);
    if (!payload) throw new UnauthorizedException('Invalid token');
    return payload;
  }

**Nothing custom**

### Expected behavior

I expect the execution of the api to conitnue and allow other request, not halting it. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/passport

### NestJS version

^9.0.0

### Packages versions

```json
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/passport": "^10.0.3",
  "passport": "^0.7.0",
    "passport-jwt": "^4.0.1",
```

### Node.js version

18.11

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

c

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
