### ISSUE TITLE
Add "graphql" to ContextType

### ISSUE THREAD

**Issue by azuziii** [nestjs/nest#14046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using Graphql and http, so in some interceptors and guards I have to check if the conext is of graphql type, but when I do
`ctxType == 'graphql'` I get `This comparison appears to be unintentional because the types 'ContextType' and '"graphql"' have no overlap`.

Can you add `'graphql'` to `ContextType` in `@nestjs\common\interfaces\features\arguments-host.interface.d.ts`

`export type ContextType = 'http' | 'ws' | 'rpc';`

### Minimum reproduction code

https://github.com/azuziii/issue-graphql-nest/blob/main/guard.ts

### Steps to reproduce

Make a guard, interceptor or anything that has context of type `ExecutionContext`, and try to check the type of context doing something like: 

```
    const type = context.getType();

    let request;

    if (type == 'graphql') { // < -- Error here
      const ctx = GqlExecutionContext.create(context);
      request = ctx.getContext().req;
    } else {
    // ...
    }
```

### Expected behavior

`context.getType()` should accepte all these `'http' | 'rpc' | 'ws' | 'graphql'`
My current fix is `const type: 'http' | 'rpc' | 'ws' | 'graphql' = context.getType();`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.5

### Packages versions

```
{
  "name": "app",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@apollo/server": "^4.11.0",
    "@nestjs/apollo": "^12.2.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.2.3",
    "@nestjs/core": "^10.0.0",
    "@nestjs/graphql": "^12.2.0",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/typeorm": "^10.0.2",
    "@nestjs/websockets": "^10.4.4",
    "@types/bcrypt": "^5.0.2",
    "@types/cookie-parser": "^1.4.7",
    "bcrypt": "^5.1.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "cookie-parser": "^1.4.6",
    "graphql": "^16.9.0",
    "nestjs-cls": "^4.4.1",
    "passport": "^0.7.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "pg": "^8.13.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.20"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^8.0.0",
    "@typescript-eslint/parser": "^8.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^7.0.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

20.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
this is expected because you must call `GqlExecutionContext.create(executionContext)` before and then call `.getType()` on the return of this new context obj

**Comment by micalevisk** [comment]
You can check over 'http' instead. Then, if it is not http, call `GqlExecutionContext.create(executionContext)` to see if it is graphql

I'll keep this open so Kamil can clarify if `ContextType` isn't supposed to have the value `"graphql"`

**Comment by jmcdo29** [comment]
You can also do `getContext<ContextType | 'graphql'>()` if you're sure the type can be there
