### ISSUE TITLE
Add metadata into ValidationPipe.exceptionFactory method

### ISSUE THREAD

**Issue by akaNightmare** [nestjs/nest#14050]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Sometime need to create a custom error information in global ValidationPipe based on `ArgumentMetadata`.
```js
createExceptionFactory() {
        return (validationErrors = []) => {
            if (this.isDetailedOutputDisabled) {
                return new http_error_by_code_util_1.HttpErrorByCode[this.errorHttpStatusCode]();
            }
            const errors = this.flattenValidationErrors(validationErrors);
            return new http_error_by_code_util_1.HttpErrorByCode[this.errorHttpStatusCode]({
               message: `${metadata.type} validation failed`, // <---- HERE metada is absent
               errors,
            });
        };
    }
```

### Describe the solution you'd like

Pass the second argument to 
```js
return (validationErrors = [], metadata: ArgumentMetadata) => {
            if (this.isDetailedOutputDisabled) {
                return new http_error_by_code_util_1.HttpErrorByCode[this.errorHttpStatusCode]();
            }
            const errors = this.flattenValidationErrors(validationErrors);
            return new http_error_by_code_util_1.HttpErrorByCode[this.errorHttpStatusCode](errors);
        };
```

calling the method
```js
if (errors.length > 0) {
  throw await this.exceptionFactory(errors, metadata);
}
```

and update TS related options
```ts
export interface ValidationPipeOptions extends ValidatorOptions {
  // ...
  exceptionFactory?: (errors: ValidationError[], metadata: ArgumentMetadata) => any;
  // ...
}
```

### Teachability, documentation, adoption, migration strategy

no explaination

### What is the motivation / use case for changing the behavior?

no explaination

**Comment by micalevisk** [comment]
I'm afraid that we might be making that factory function too complex and specific(?). I believe that in this case you should write your own pipe instead with `extends ValidationPipe`

**Comment by akaNightmare** [comment]
@micalevisk copy/extend own validationpipe which is 99% the same, I think it's overhead

**Comment by kamilmysliwiec** [comment]
1. Create a new class (pipe)
2. Make it extend `ValidationPipe`
3. Override `transform` and catch exception factory specific error
4. Add more info/metadata and rethrow
