### ISSUE TITLE
Separate apps from libs when use monorepos

### ISSUE THREAD

**Issue by leandroluk** [nestjs/nest#14054]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Today every new lib or app created in project will be added in "projects" property in `nest-cli.json` file like this

```json
{
  "projects": {
    "main": {
      "type": "application",
      "root": "apps/main",
      "entryFile": "main",
      "sourceRoot": "apps/main/src",
      "compilerOptions": {
        "tsConfigPath": "apps/main/tsconfig.app.json"
      }
    },
    "tenant": {
      "type": "application",
      "root": "apps/tenant",
      "entryFile": "main",
      "sourceRoot": "apps/tenant/src",
      "compilerOptions": {
        "tsConfigPath": "apps/tenant/tsconfig.app.json"
      }
    },
  }
}
```

But if I add any library with same name of any application I need to force another name...

### Describe the solution you'd like

When project uses an monoreposaves the project in two new properties like "apps" and "libs" like this

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "monorepo": true,
  "apps": {
  
  },
  "libs": {
  
  }
}
```

### Teachability, documentation, adoption, migration strategy

This change would be more technical and organizational and most users would not be directly impacted.

### What is the motivation / use case for changing the behavior?

This change will improve organization and legibility when working with workspaces

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
