### ISSUE TITLE
Nest.js POST Endpoint is Dropping the Message Body from an SNS Notification

### ISSUE THREAD

**Issue by ddrummond-allio** [nestjs/nest#14053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The following POST endpoint in my Nest.JS API can receive notifications from SNS, but the message body is always `{}` including the SubscriptionConfirmation message first sent when subscribing to the SNS Topic.

### Minimum reproduction code

https://github.com/hop-along-polly/nest-js-sns-bug

### Steps to reproduce

Instructions are also in the README but here they are again.

1. Run `pnpm start` to start the Nest.js App
2. Follow the [Ngrok Quickstart](https://ngrok.com/docs/getting-started/) guide to setup an HTTPS proxy to the locally running Nest.js App. When starting the Ngrok proxy use `ngrok http http://localhost:3000`

**NOTE: The free trial is enough to reproduce the error.**

3. Run `./scripts/init-aws.sh` to create the SNS Topic and Subscribe the Ngrok HTTPS endpoint as an HTTPS Subscriber to that Topic.

4. Observe an event is received at the `/sns` endpoint but the message body logged is `{}`

### Expected behavior

A SubscriptionConfirmation notification similar to the one below should be received.

```json
{
    "Type": "SubscriptionConfirmation",
    "MessageId": "8e5fc642-62da-4ea5-b33a-245e4a2fe5c3",
    "Token": "2336412f37fb687f5d51e6e2425ba1f30ada00b51d3b6f457a7d6f494a2d9784f8ed42a92d409de41347da3103f629c7917496199e93884f67994285a82140f4691f09ef1319f3bc1cb0a8243cfee64957bd2ef9e5f79440f301f9bc4ad2afd76252e7f65bfb2d3d9f53fb8e47a972b3",
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:derek-test",
    "Message": "You have chosen to subscribe to the topic arn:aws:sns:us-east-1:000000000000:derek-test.\nTo confirm the subscription, visit the SubscribeURL included in this message.",
    "SubscribeURL": "https://sns.us-east-1.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-east-1:000000000000:derek-test&Token=2336412f37fb687f5d51e6e2425ba1f30ada00b51d3b6f457a7d6f494a2d9784f8ed42a92d409de41347da3103f629c7917496199e93884f67994285a82140f4691f09ef1319f3bc1cb0a8243cfee64957bd2ef9e5f79440f301f9bc4ad2afd76252e7f65bfb2d3d9f53fb8e47a972b3",
    "Timestamp": "2024-10-01T21:22:02.189Z",
    "SignatureVersion": "1",
    "Signature": "rOAdId9vryAuHLWpwd7AZh48K4XcUfHKxePsMKEIk5gUEz58ZogLmmz4xDB5Be16NHOeN4Te6RFS5d80xWTAFu2QlEWYM38o5KPlT4KSd26z3ivPtVfBcOOdFlRC3ueW3/tajUwvfSf7u/rrAQo0A6CZ5vmSX9qz2soZJxMHjRNteFQXSWwPL4A8uaVcd0EYBbohsrdZVGQI6hBpUPmN7ufIBi3cd4flbAD/OLXN80LxEtwjkZIEST95EhkKyOwIcjJmNIAVUXiSo3F8AhfFmTiXUFBJpH9xyCqkgeu7IXggD+WhBkdpLF9AoEhZyUL+EUaFptaWX9MhS8rf71O57g==",
    "SigningCertURL": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-60eadc530605d63b8e62a523676ef735.pem"
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
    "@nestjs/axios": "^3.0.3",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "axios": "^1.7.7",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Your repository is empty

**Comment by ddrummond-allio** [comment]
My apologies. I didn't notice there was an error when first pushing the code. It's there now.

**Comment by micalevisk** [comment]
The app looks pretty standard so far I'd say that client is not behaving like you want to. Make sure that it sending the `Content-type: application/json` otherwise `req.body` will be empty

We won't reproduce the issue if we need to setup an AWS account, sorry. And looks like you don't even need to use SNS if the issue is on the server side otherwise it is not related to nestjs
