### ISSUE TITLE
Fastify V5 Upgrade

### ISSUE THREAD

**Issue by PattyTrish** [nestjs/nest#14068]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Nest.js currently utilizes Fastify v4, which will [exit LTS on June 30, 2025](https://fastify.dev/docs/latest/Reference/LTS/#schedule). This will happen after [Node.js ends Maintenance LTS support for v18 on April 30, 2025](https://github.com/nodejs/Release). At some point, Nest.js needs to support the future Fastify platform to ensure Nest.js clients are up to date, decreasing vulnerability rate.

### Describe the solution you'd like

A new major version of Nest.js that supports Fastify V5. This version will initially include enough fixes to breaking changes to support existing users, utilizing the [Fastify migration guide](https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/). If there are any breaking changes to the end-user, they will be documented.

Since old Node versions are not going to be compatible, this is a breaking change.

There is a new feature detailed, but that will not be considered for this initial issue.

If it makes sense, this major version could also include the next major version of Express that someone else has proposed: #14042. Note that Express 5 supports Node 18 while Fastify V5 does not. This will also need to not be an issue.

### Teachability, documentation, adoption, migration strategy

Migration documentation will be used to appraise Nest.js users on how to upgrade, accounting for any breaking changes, if the upgrade does not fit in patch notes. This will be a major version update and may involve beta version testing if that is supported by the community.

### What is the motivation / use case for changing the behavior?

To keep Nest.js modern, it needs to support the newest versions of its platforms. Users will move away from Nest.js if it prone to being outdated and/or a security risk due to being outdated.

As a happy Nest.js user, I'd love for the opportunity to contribute back! This is an interesting possibility, and I would like to know if there is any other work ongoing for this, or if I can help kick off this upgrade.

**Comment by micalevisk** [comment]
#13990

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/14177
