### ISSUE TITLE
socket.io not up-to-date

### ISSUE THREAD

**Issue by tibo-mllr** [nestjs/nest#14084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi!
I'm updating the packages to fix the `cookie` vulnerability, but even though I put `@nestjs/platform-socket.io` up-to-date with `yarn add @nestjs/platform-socket.io`, the yarn.lock don't change the dependencies versions. It worked for `@nestjs/platform-express`...

See screenshot of the `yarn.lock` diff: https://drive.google.com/file/d/1vXflQaBdXl_XiF6Z_O0cesVdBpCOTmyd/view?usp=sharing

Seems more like a `yarn` issue, but would you know why this happens? And how to fix on my side ?

### Minimum reproduction code

https://github.com/tibo-mllr/website/tree/Updates (see last commit https://github.com/tibo-mllr/website/commit/978eadc51ac81bc6790f9d03776e172c45a63aec)

### Expected behavior

It should upate the `socket.io` version, as in https://github.com/nestjs/nest/commit/4d3d39158aa6ff032f64914a2725ca1f51644aac

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [X] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.4

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^10.4.4",
    "@nestjs/config": "^3.2.3",
    "@nestjs/core": "^10.4.4",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mongoose": "^10.0.10",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^10.4.5",
    "@nestjs/platform-socket.io": "^10.4.5",
    "@nestjs/swagger": "^7.4.2",
    "@nestjs/websockets": "^10.4.4",
    "bcrypt": "^5.1.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "mongoose": "^8.6.3",
    "passport": "^0.7.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.2.2"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.4.5",
    "@nestjs/schematics": "^10.1.4",
    "@types/bcrypt": "^5.0.2",
    "@types/node": "^22.5.5",
    "@types/passport-jwt": "^4.0.1",
    "@types/passport-local": "^1.0.38",
    "@typescript-eslint/eslint-plugin": "^8.6.0",
    "@typescript-eslint/parser": "^8.6.0",
    "@website/shared-types": "1.0.0",
    "eslint": "^8.57.1",
    "typescript": "^5.6.2"
  }
}

```

### Node.js version

20.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
the latest version of `socket.io` is `4.8.1` but it seems that `4.8.0` doesn't have such vulnerability anymore and it's the current version being used by `@nestjs/platform-socket.io`. So I don't think that we can do anything on nestjs side.

![image](https://github.com/user-attachments/assets/6da238d2-3c5c-4ada-8596-91633bf5fd87)

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead

**Comment by lluiscab** [comment]
Why is socket.io pinned to `4.8.0` and still not updated to `4.8.1` after a month?

**Comment by micalevisk** [comment]
@kamilmysliwiec 
![image](https://github.com/user-attachments/assets/d998750b-7b59-4110-93b3-c241b96c9375)

looks like we missed this one
