### ISSUE TITLE
Specific queue for NATS microservice

### ISSUE THREAD

**Issue by frct1** [nestjs/nest#14083]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Problem is when developer need to specify queue he should specify it at `connectMicroservice` options key.

### Describe the solution you'd like

Since `@MessagePattern` as well as `@EventPattern` decorator accepts `extras` argument it could be used like
```ts
@EventPattern('event_1', SPECIFIC_CLIENT, { queue: 'group-1'})
async handle1(){}

@EventPattern('event_1', SPECIFIC_CLIENT, { queue: 'group-1'})
async handle2(){}
```

### Teachability, documentation, adoption, migration strategy

No migration strategy required

### What is the motivation / use case for changing the behavior?

Motivation is to reduce count of required connections to NATS since a lot of subjects and queues could process within single connection.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/14200

**Comment by frct1** [comment]
> #14200

Wooooah Pog!
Thank you
