### ISSUE TITLE
ParseIntPipe transform not working

### ISSUE THREAD

**Issue by Lliuxs** [nestjs/nest#14095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

in docs  a simle ParseIntPipe like this 
if value is a float value 1.1 i got 1 but i got a error.
import { PipeTransform, Injectable, ArgumentMetadata, BadRequestException } from '@nestjs/common';

@Injectable()
export class ParseIntPipe implements PipeTransform<string, number> {
  transform(value: string, metadata: ArgumentMetadata): number {
    const val = parseInt(value, 10);
    if (isNaN(val)) {
      throw new BadRequestException('Validation failed');
    }
    return val;
  }
}

souceCode like this fisrt valitae but /^-?\d+$/.test(1.1) return false throw a error
should parseInt first？

if (!this.isNumeric(value)) {
      throw this.exceptionFactory(
        'Validation failed (numeric string is expected)',
      );
    }
    return parseInt(value, 10);

### Minimum reproduction code

https://codesandbox.io/p/devbox/affectionate-christian-j9v3lq?file=%2Fsrc%2Fapp.controller.ts%3A13%2C1

### Steps to reproduce

npm run start:dev

<img width="861" alt="image" src="https://github.com/user-attachments/assets/6e68446e-b67b-45f5-b691-132e07072021">

### Expected behavior

got 1 not error

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
