### ISSUE TITLE
Dynamic Module providers: useFactory not working when using same token

### ISSUE THREAD

**Issue by Fksg** [nestjs/nest#14099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using a dynamic module with _useFactory_ to provide a simple value, I observe unexpected behavior when injecting tokens in multiple modules. Specifically, when creating two modules with different values for the token, both instances end up with the same value, instead of retaining their respective values.

**Reproduction**

1. Define a dynamic module as follows:

```javascript
@Module({})
class DynamicModule {
    static register(value: string) {
        return {
            module: DynamicModule,
            providers: [{ provide: "TOKEN", useFactory: () => value }],
            exports: ["TOKEN"]
        }
    }
}
```

2. Create two modules that import _DynamicModule_ with different values:

```javascript
@Module({ imports: [DynamicModule.register("Module1")] })
class Module1 {
    constructor(@Inject("TOKEN") token: string) {
        console.log(`Should display Module1: ${token}`)
    }
}

@Module({ imports: [DynamicModule.register("Module2")] })
class Module2 {
    constructor(@Inject("TOKEN") token: string) {
        console.log(`Should display Module2: ${token}`)
    }
}

@Module({ imports: [Module1, Module2] })
class AppModule {
}

NestFactory.create(AppModule).then(app => app.listen(3000))
```

3. When running the above code, the output shows the same token for both modules:

```
Should display Module2: Module1
Should display Module1: Module1
```

4. However, if I replace _useFactory_ with _useValue_, the tokens are displayed correctly:

```
Should display Module1: Module1
Should display Module2: Module2
```

### Minimum reproduction code

https://github.com/Fksg/dynamic-module/blob/main/src/main.ts

### Expected behavior

Each module should display its respective token as defined by its register call.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.6

### Packages versions

"@nestjs/common": "10.4.6"
"@nestjs/core": "10.4.6"

### Node.js version

20.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I believe that this is expected.

![image](https://github.com/user-attachments/assets/6fd9b425-12ba-450b-96da-79d2a0861389)

To circumvent that, you can:

1. replace `useFactory` with `useValue`, or
2. add a 'no-op' custom value provider to that dynamic module so that it will receive an unique ID every time you call the dynamic module (or an unique ID based on its parameters, for example; you could use the [`object-hash`](https://www.npmjs.com/package/object-hash) lib). See how `@nestjs/typeorm` does that here: https://github.com/nestjs/typeorm/blob/92f193cc0e19fda68a83ea58c79494c816524efd/lib/typeorm-core.module.ts#L113-L116

**Comment by Fksg** [comment]
> 2\. no-op

I need to use useFactory and the same token ID.

**Comment by kamilmysliwiec** [comment]
This will be fixed in the next major release https://github.com/nestjs/nest/pull/13336
