### ISSUE TITLE
@SubscribeMessage callback funciton parameter

### ISSUE THREAD

**Issue by elkon028** [nestjs/nest#14104]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

- socket.io server API
```js
import { Server } from 'socket.io'
io.on("connection", (socket) => {
  socket.on("news", (data) => {
    console.log(data);
  });
  // with several arguments
  socket.on("news", (arg1, arg2, arg3) => {
    // ...
  });
  // or with acknowledgement
  socket.on("news", (data, callback) => {
    callback(0);
  });
});

```
- nestjs @SubscribeMessage('news') 
- How to implement callback function
- Similar to the following socket.io server API
```js
@SubscribeMessage('news')
onNews(@WsCallback??? callback){
  callback(0)
}
socket.on("news", (data, callback) => {
    callback(0);
  });
```
- Is this the only way?
```js
handleConnection(@ConnectedSocket() client: Socket) {
    console.log(`Client connected with id: ${client.id}`)
    client.on('news', async (data: any, callback) => {
      console.log('news', client.id, data)
      callback('....')
    })
  }
```

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
