### ISSUE TITLE
Missing Federation Directives in Subgraph Schema when Using Code-First Approach with Federation 2

### ISSUE THREAD

**Issue by yahavf6** [nestjs/nest#14105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, I'm encountering an issue with @nestjs/graphql when using Apollo Federation with Federation version 2. Specifically, some Federation directives (such as @key) are not appearing in the generated subgraph schema when I use the code-first approach.

I've set up my NestJS application to use Federation 2, and I’ve configured the GraphQLModule with the ApolloFederationDriver. However, even though I've annotated my entities with the appropriate Federation directives in the code, these directives are missing in the schema that gets generated.

### Minimum reproduction code

https://github.com/nestjs/graphql

### Steps to reproduce

Install `@nestjs/graphq`l and `@apollo/subgraph`.

Configure the GraphQLModule with ApolloFederationDriver and set federation: { version: 2 }

Define an entity with Federation directives using the code-first approach, for example:

```
@ObjectType()
@Directive('@key(fields: "id")')
export class User {
  @Field(() => ID)
  id: string;

  @Field()
  name: string;
}
```
Start the application and inspect the generated schema.

### Expected behavior

The generated subgraph schema should include the specified Federation directives (e.g., `@key(fields: "id")`), as these are essential for the Apollo Gateway to correctly stitch together the subgraphs.

Actual Behavior

The generated schema does not include the directives, which breaks compatibility with any tools that based on `supergraph.graphql` schema and prevents proper federation functionality.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

12.0.10

### Packages versions

```json
    "@apollo/server": "^4.9.5",
    "@apollo/subgraph": "^2.5.6",
    "@azure/msal-node": "^2.1.0",
    "@azure/storage-blob": "^12.18.0",
    "@clerk/clerk-sdk-node": "^5.0.11",
    "@google-cloud/storage": "^4.7.2",
    "@hubspot/api-client": "^9.0.0",
    "@intail/model-lib": "*",
    "@intail/shared-lib": "*",
    "@intail/utility-lib": "*",
    "@langchain/core": "^0.1.63",
    "@langchain/openai": "^0.0.31",
    "@logtail/node": "^0.4.16",
    "@logtail/winston": "^0.4.16",
    "@microsoft/microsoft-graph-client": "^3.0.7",
    "@nestjs/apollo": "^12.0.10",
    "@nestjs/axios": "^3.0.1",
    "@nestjs/bull": "^10.0.1",
    "@nestjs/cache-manager": "^2.1.1",
    "@nestjs/common": "^10.2.8",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.8",
    "@nestjs/event-emitter": "^2.0.3",
    "@nestjs/graphql": "^12.0.10",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/microservices": "^10.2.8",
    "@nestjs/mongoose": "^9.0.3",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "^10.2.8",
    "@nestjs/schedule": "^4.0.0",
    "@nestjs/terminus": "^10.1.1",
    "@nestjs/throttler": "^5.0.1",
    "@nestjs/websockets": "^10.4.1",
    "@sendgrid/mail": "^8.1.3",
    "@sendgrid/client": "^8.1.3",
    "@slack/oauth": "^3.0.0",
    "@slack/web-api": "^7.0.1",
    "amqp-connection-manager": "^4.1.14",
    "amqplib": "^0.10.3",
    "analytics-node": "^6.2.0",
    "apollo-server-core": "^3.13.0",
    "apollo-server-express": "^3.13.0",
    "axios": "^1.6.1",
    "bcryptjs": "^2.4.3",
    "bull": "^4.11.5",
    "cache-manager-ioredis-yet": "^1.2.2",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cookie-parser": "^1.4.6",
    "countries-list": "^3.1.0",
    "crypto": "^1.0.1",
    "dataloader": "^2.2.2",
    "dotenv": "^16.3.1",
    "googleapis": "^108.0.0",
    "graphql": "^16.8.1",
    "graphql-redis-subscriptions": "^2.6.0",
    "graphql-subscriptions": "^2.0.0",
    "graphql-type-json": "^0.3.2",
    "helmet": "^7.1.0",
    "i18n-iso-countries": "^7.6.0",
    "ioredis": "^5.2.4",
    "jsforce": "^1.11.0",
    "jwks-rsa": "^3.1.0",
    "jwt-decode": "^4.0.0",
    "lodash": "^4.17.21",
    "module-alias": "^2.2.3",
    "moment": "^2.30.1",
    "mongoose": "^6.8.3",
    "nanoid": "^3.3.7",
    "nest-winston": "^1.9.4",
    "object-hash": "^3.0.0",
    "papaparse": "^5.3.2",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "passport-strategy": "^1.0.0",
    "psl": "^1.9.0",
    "randomatic": "^3.1.1",
    "reflect-metadata": "^0.1.13",
    "remove-accents": "^0.4.4",
    "rimraf": "^5.0.5",
    "rxjs": "^7.8.1",
    "sqlstring": "^2.3.3",
    "svix": "^1.13.0",
    "tldts": "^5.7.104",
    "winston": "^3.11.0",
    "csv-parser": "^3.0.0"
```

### Node.js version

20.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by yahavf6** [comment]
Everyone has this issue, I've spent almost 3 days a solution for this!
And found it after long research:
https://github.com/nestjs/graphql/pull/2059

Can close
