### ISSUE TITLE
Pass metadata from grpc client to gprc server

### ISSUE THREAD

**Issue by mariocasila** [nestjs/nest#14101]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am looking for a way to authorize an rpc via NestJS grpc microservices. Basically I want to attach a token in the grpc client, which has to be validated by the grpc server.

### Describe the solution you'd like

we can add it like what postman does for grpc.

### Teachability, documentation, adoption, migration strategy

![image](https://github.com/user-attachments/assets/017d6b3b-c968-4da0-b7be-a68ff13f9888)

### What is the motivation / use case for changing the behavior?

if we add this functionality, we can easily pass token or something in meta from microservice to microservice which requires authentication/authorization

**Comment by kamilmysliwiec** [comment]
https://stackoverflow.com/questions/37526077/how-to-add-metadata-to-nodejs-grpc-call

Just pass metadata as the second argument of your method
