### ISSUE TITLE
ParseFilePipe doesnt accept Validators implementing PipeTransform

### ISSUE THREAD

**Issue by gyanendrasng** [nestjs/nest#14106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

As mention [here](https://docs.nestjs.com/techniques/file-upload#file-validation) that the pipe ParseFilePipe will accept validators which implement PipeTransform but in reality it required that the validators are of the type FileValidator(abstract class).

If it is the intended behaviour then I believe there should be an example to show how the file Validator class mentioned [here](https://docs.nestjs.com/techniques/file-upload#file-validation) should be used.  

### Minimum reproduction code

Not required

### Expected behavior

Currently the app throws an compile time error 
`Type 'FileValidationPipe' is missing the following properties from type 'FileValidator<Record<string, any>, IFile>': validationOptions, isValid, buildErrorMessagets(2739)`
 on the code snippet being like this - 

```
 @Post()
  @UseInterceptors(FileInterceptor('resume'))
  async create(
    @Body() createDTO: CreateDTO,
    @UploadedFile(
      new ParseFilePipe({
        validators: [
          new FileValidationPipe({ fileType: 'pdf', required: true }),
        ],
      }),
    )
    resume: Express.Multer.File,
  ) {
    console.log(resume);
    return await this.candidateService.create(createDTO);
  }
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "backend",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.2.3",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@prisma/client": "^5.21.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "file-type": "^19.6.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1",
    "tsimportlib": "^0.0.5"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^5.0.0",
    "@types/jest": "^29.5.2",
    "@types/multer": "^1.4.12",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^8.0.0",
    "@typescript-eslint/parser": "^8.0.0",
    "eslint": "^9.0.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^7.0.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

20.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by gyanendrasng** [comment]
Yes, it was really confusing to me as it was not clear to me, lemme know if I should open a PR for it?

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome!
