### ISSUE TITLE
Update Deprecated Variadic Argument Usage in .listen() Method for Fastify Sample

### ISSUE THREAD

**Issue by dushmanta05** [nestjs/nest#14102]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

While migrating from Express to Fastify, I encountered a deprecation warning when using the `app.listen(3000)` method with Fastify. The warning message indicated that the variadic `.listen()` method, which accepts a port and an optional callback, is now deprecated.

![screenshot 01](https://github.com/user-attachments/assets/c3ed5bc8-d527-4105-a6b5-4292d4dcb055)

Deprecation Message:

```
The signature '(port: string | number, callback?: (err: Error, address: string) => void): Promise<RawServerDefault>' of 'app.listen' is deprecated.ts(6387)
nest-fastify-application.interface.d.ts(69, 8): The declaration was marked as deprecated here.
(method) NestFastifyApplication<RawServerDefault>.listen(port: number | string, callback?: (err: Error | null, address: string) => void): Promise<RawServerDefault> (+5 overloads)
Starts the application.

@deprecated — Variadic listen method is deprecated. Please use .listen(optionsObject, callback) instead. The variadic signature will be removed in fastify@5

@see — https://github.com/fastify/fastify/pull/3712
```

Upon reviewing the [Fastify Pull Request](https://github.com/fastify/fastify/pull/3712) mentioned in the warning, I learned that the recommended approach is to use an options object with the `.listen()` method rather than passing the port number.

### Describe the solution you'd like

To resolve the deprecation warning, you can use the new object format to pass the port to the `.listen()` method, like this:

```js
async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  app.useGlobalPipes(new ValidationPipe());
  await app.listen({ port: 3000 });
  console.log(`Application is running on: ${await app.getUrl()}`);
}
bootstrap();
```

### Teachability, documentation, adoption, migration strategy

With this updated sample, we can use the latest Fastify changes and ensure compatibility with future updates.

Here’s the complete code for the `main.ts` file:

```js
import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  app.useGlobalPipes(new ValidationPipe());
  await app.listen({ port: 3000 });
  console.log(`Application is running on: ${await app.getUrl()}`);
}
bootstrap();
```

### What is the motivation / use case for changing the behavior?

Since Fastify has changed the `.listen()` method and the older practice of passing the port number directly is deprecated, using the updated method can be more beneficial and keep us up to date with Fastify's latest changes, as well as compatible with future versions.

**Comment by dushmanta05** [comment]
@micalevisk I was following the sample so pointed out, could you please what changes you're referring to? Thank you.

**Comment by micalevisk** [comment]
the implementation:

https://github.com/nestjs/nest/blob/7843db3984af97e98b5486ad142fd5bcf438a3f2/packages/platform-fastify/adapters/fastify-adapter.ts#L264

the interface:

https://github.com/nestjs/nest/blob/7843db3984af97e98b5486ad142fd5bcf438a3f2/packages/platform-fastify/interfaces/nest-fastify-application.interface.ts#L128

But I guess that deprecated method was expected to be there and will be removed in the next major release of Nestjs

I wonder why we can't just 'undeprecate' and support it under the hood instead tho. `app.listen` having different interfaces depending on the adapter is a bit odd to me but Kamil knows better about this.

**Comment by kamilmysliwiec** [comment]
Undeprecated here https://github.com/nestjs/nest/pull/14108 we can handle this on the NestJS adapter's side
