### ISSUE TITLE
Compatibility issue between NestJS Swagger, SWC type-checking, and class-validator DTOs

### ISSUE THREAD

**Issue by myatminag** [nestjs/nest#14109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm encountering an issue where NestJS Swagger and SWC type-checking do not work correctly with class-validator DTOs. It seems there's a compatibility problem when using these tools together.

1. First, generate metadata.ts by running `npx ts-node src/metadata.ts`.
2. Then, start the NestJS application in watch mode with type-checking enabled at nest-cli.json: `npm run start:dev`.

With this setup, the request body appears in Swagger, and it connects to the .dto.ts files under the dto folder. However, if I delete a `.dto.ts` file, the `metadata.ts` file throws an error: Error: Cannot find module `'./app/tenant/dto/test.dto'.` This issue requires a server restart each time a `.dto.ts` file is removed.

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "builder": "swc",
    "typeCheck": true,
    "watchAssets": true,
    "plugins": ["@nestjs/swagger"]
  }
}
```

### Minimum reproduction code

https://codesandbox.io/p/devbox/frosty-pasteur-gfvz5w

### Steps to reproduce

1. Set up a NestJS project with SWC, Swagger, and class-validator.
2. Create a DTO class with validation decorators from class-validator in a file under the dto folder (e.g., test.dto.ts).
3. Generate metadata by running: `npx ts-node src/generate-metadata.ts`.
4. Start the NestJS server in watch mode with SWC and type-checking enabled: `nest start -b swc -w --type-check`.
5. Open the Swagger documentation and confirm that the request body schema for the DTO appears as expected.
6. Delete the test.dto.ts file from the dto folder.
7. Observe that the server logs an error similar to: `Error: Cannot find module './app/tenant/dto/test.dto'`.
8. Notice that restarting the server is required for the application to run without errors after deleting a .dto.ts file.

### Expected behavior

When using SWC, Swagger, and class-validator DTOs together:

1. After generating `metadata.ts` and starting the server in watch mode, Swagger should display the request body schema based on the `DTO` files in the `dto` folder.
2. If a .`dto.ts` file is deleted, the server should handle the change gracefully without requiring a restart.
3. The `metadata.ts` file should not throw a "Cannot find module" error when a `DTO` file is removed, allowing the server to continue running in watch mode without interruption.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/swagger, class-validator,  @swc/cli, @swc/core

### NestJS version

10.4.4

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^10.3.2",
    "@nestjs/core": "^10.4.4",
    "@nestjs/platform-express": "^10.4.4",
    "@nestjs/swagger": "^8.0.2",
    "class-validator": "^0.14.1",
    "reflect-metadata": "^0.2.1",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.4.5",
    "@nestjs/schematics": "^10.1.0",
    "@nestjs/testing": "^10.3.2",
    "@swc/cli": "^0.3.9",
    "@swc/core": "^1.4.0",
    "@types/express": "^4.17.21",
    "@types/jest": "^29.5.12",
    "@types/node": "^20.11.16",
    "@types/supertest": "^6.0.2",
    "@typescript-eslint/eslint-plugin": "^6.21.0",
    "@typescript-eslint/parser": "^6.21.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "jest": "^29.7.0",
    "prettier": "^3.2.5",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.4",
    "ts-jest": "^29.1.2",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.3.3"
  },
```

### Node.js version

20.9.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Generating metadata and compiling your projects are separate processes (two different scripts running in parallel), so avoiding file deletion conflicts is not possible. However, even when you run both concurrently, the process will flow as follows:

1. Your DTO file is removed.
2. SWC incremental compilation, which is faster than metadata generation, will initially cause a type-check failure.
3. The metadata generator then catches up and regenerates the metadata file, triggering another SWC recompilation and type-check.
4. At this point, type-checking should pass without issues.

From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again.
