### ISSUE TITLE
OnModuleDestroy call order bug

### ISSUE THREAD

**Issue by wenlong-chen** [nestjs/nest#14118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

A depends on B, B's onModuleDestroy is called before A's onModuleDestroy.

### Minimum reproduction code

https://github.com/wenlong-chen/nest-on-module-destory-bug

### Steps to reproduce

The following code will throw an Error: file closed during shutdown.

```typescript
import { Global, Injectable, Module, OnModuleDestroy, OnModuleInit } from "@nestjs/common";
import { FileHandle, open } from 'fs/promises';

@Injectable()
export class BService implements OnModuleInit, OnModuleDestroy {
  private fh: FileHandle

  async log(message: string) {
    await this.fh.write(message);
  }

  async onModuleInit() {
    this.fh = await open('test.txt', 'w');
  }

  async onModuleDestroy() {
    await this.fh.close();
  }
}

@Module({
  providers: [BService],
  exports: [BService],
})
export class BModule {}

@Injectable()
export class AService implements OnModuleInit, OnModuleDestroy {
  constructor(private bService: BService) {}

  async onModuleInit() {
    await this.bService.log('AService.onModuleInit\n');
  }

  async onModuleDestroy() {
    await this.bService.log('AService.onModuleDestroy\n');
  }
}

@Module({
  imports: [BModule],
  providers: [AService],
  exports: [AService]
})
export class AModule {}

@Module({
  imports: [AModule, BModule],
})
export class AppModule {}


```

### Expected behavior

A depends on B, B's onModuleDestroy is called after A's onModuleDestroy.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "nest-on-module-destroy-bug",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^8.0.0",
    "@typescript-eslint/parser": "^8.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^7.0.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

20.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this in 1 place https://github.com/nestjs/nest/pull/14111

**Comment by flovouin** [comment]
Shouldn't this be extended to all "termination hooks", i.e. `beforeApplicationShutdown` and `onApplicationShutdown`? #14111 only addresses `onModuleDestroy` and I don't see any other changes in [11.0.0 branch](https://github.com/nestjs/nest/blob/11.0.0/packages/core/nest-application-context.ts).

I currently have a bug where a database module is being shutdown before a module that uses it. The database client complains that there are still open connections. I carefully implemented `onApplicationShutdown`, but if those are called in ascending `distance` order, that would actually make the bug more likely to occur.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this @flovouin?

**Comment by flovouin** [comment]
Here it is: https://github.com/nestjs/nest/pull/14267
