### ISSUE TITLE
Execution time decorator

### ISSUE THREAD

**Issue by 40oleg** [nestjs/nest#14119]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Trying to determine bottleneck of app.

### Describe the solution you'd like

It would be great to add some decorators that could handle the execution time of some endpoint and log logs if something runs longer than some threshold.
@MaxExecutionTime(N), where N is the waiting time in milliseconds

If the endpoint execution time is less than N, then nothing happens, but otherwise the message "the SOME_METHOD method performed much more than expected" appears.

### Teachability, documentation, adoption, migration strategy

It does not need any migration. It just a decorator that have some logging execution time logic

### What is the motivation / use case for changing the behavior?

I'm building a distributed system on nest, and one of the connected systems is returning responses too slowly. I could have handled this situation by just looking at the logs, but I needed to check the client settings and the code.

**Comment by micalevisk** [comment]
you can use an interceptor for that and then:

```js
const MaxExecutionTime = (n) => UseInterceptors(TimeoutInterceptor(n))
```

So I'd say that this is too specific to leave under `@nestjs/*` scope.
