### ISSUE TITLE
New File Interceptor

### ISSUE THREAD

**Issue by gyanendrasng** [nestjs/nest#14124]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Assume that we have 2 files which we want to send from frontend to nestjs, now both files have different keys in formdata, currently there is no way to accept 2 files separately and validate them both using an file interceptor, we can use FilesInterceptor but then we have to send both files in a single key and one in a specific order.
Same case goes for AnyFilesInterceptor and moreover we can use a custom validator to validate both properly.

### Describe the solution you'd like

Maybe (am not sure if its possible with multer) we allow the developer to use a new file interceptor which he can use inside UseInterceptors to get the files. 
something like this - 
The suggested interceptor is named as NewFileInterceptor

`@UseInterceptors(NewFileInterceptor('file1'),NewFileInterceptor('file2'))`

and then we can use UplodaedFile to get the file inside the controller function. 

### Teachability, documentation, adoption, migration strategy

some thing like this - 

```typescript
@Post('file')
@UseInterceptors(NewFileInterceptor('file1'),NewFileInterceptor('file2'))
uploadFileAndValidate(@UploadedFile(
  new FileSizeValidationPipe(),
) file1: Express.Multer.File,@UploadedFile(
  new FileSizeValidationPipe(),
) file2: Express.Multer.File ) {
  return file1||file2;
}
```

### What is the motivation / use case for changing the behavior?

mentioned above

**Comment by SngGyanendra** [comment]
@micalevisk ?

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

At the moment, there are no plans to introduce a new file interceptor pipe.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
