### ISSUE TITLE
Can I create files with line breaks of LF when I use Windows?

### ISSUE THREAD

**Issue by anqisoft** [nestjs/nest#14128]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I usually use Windows 10, so the default line break is CRLF. But I want all files to use LF as line break.
Whether I create an application by "nest new -p pnpm nest-blog" or a module by "nest g mo modules/article && nest g s modules/article && nest g co modules/article", I get files with CRLF line breaks.
But I want to get files with LR line breaks, and I don't like to format files again and again using "pnpm format".

Can you help me?
![image](https://github.com/user-attachments/assets/b2ac7a02-9e6b-4b10-a7b3-588d8361c6a1)

### Describe the solution you'd like

![1731296141513](https://github.com/user-attachments/assets/3935e09d-c436-4331-8a1b-d5ff11107fb1)

### Teachability, documentation, adoption, migration strategy

Please see the above pictures.

### What is the motivation / use case for changing the behavior?

Please see the above pictures.

**Comment by anqisoft** [comment]
According to https://github.com/nestjs/nest-cli/issues/2056, I added the following configuration information to tsconfig.json:
"newLine": "lf",
Then when I used "nest g ...", I got files using LF as line breaks.

I don't know whether it is necessary to suggest "nest new" to add a parameter "-n, --newline" with optional values ​​"crlf" and "lf", and the default value is "lf".

**Comment by kamilmysliwiec** [comment]
We track this here https://github.com/nestjs/nest-cli/issues/316
