### ISSUE TITLE
@nestjs/platform-fastify^10.4.7 doesn't use the latest fastify version, thus many plugins throws mismatch versions error.

### ISSUE THREAD

**Issue by KR1470R** [nestjs/nest#14145]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

^10.0.0

### Describe the regression

When using `@nestjs/platform-fastify^10.4.7`(the latest version at the moment)  and the `@fastify/cookie^11.0.1`, `@fastify/multipart^9.0.1` (both up to date too) \
the following errors occured:
 `FastifyError [Error]: fastify-plugin: @fastify/cookie - expected '5.x' fastify version, '4.28.1' is installed`
`FastifyError [Error]: fastify-plugin: @fastify/multipart - expected '5.x' fastify version, '4.28.1' is installed`

### Input code

```ts

```

### Expected behavior

The `@nestjs/platform-fastify^10.4.7` should use `fastify^5.1.0` version and fastify plugins shouldn't mismatch versions error.

**Comment by micalevisk** [comment]
nestjs v10 doesn't supports the latest version of `fastify`

**Comment by KR1470R** [comment]
got ya, thanks
awaiting for the nest 11 version then.
