### ISSUE TITLE
Make life esay for devs just delete this project 

### ISSUE THREAD

**Issue by chann44** [nestjs/nest#14148]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

yes 
i have issue with how the nest is dog shit it is just  bad way of writting software i think just use functional way of doing stuff or just use minimal classs overhead because it does not make scnece to have all this when i am writing sam elogic in three places 

### Describe the solution you'd like

fucing delte it 

### Teachability, documentation, adoption, migration strategy

just a problem in the ass

### What is the motivation / use case for changing the behavior?

i don't like it

**Comment by jmcdo29** [comment]
Hello, it seems that you have very strong opinions about a Free Open Source project that you are not forced to use (unless a decision was made by upper management at your workplace, in which case talk with them). As using nest is not the only way to write a server using Typescript and NodeJS, you are certainly more than welcome to use any other approach: fastify, express, koa, hapi, loopback, node's http module, or any other approach you find palatable. 

Meanwhile, we will continue to develop and use this framework as we find it useful.
