### ISSUE TITLE
Align the logic of `isOptionalFactoryDependency` internal utility

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#14154]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

at `@nestjs/common` we have a `x is OptionalFactoryDependency` with the following logic:

https://github.com/nestjs/nest/blob/7d62aad5fc81e839bcdb9b357e5d8fc2f513f1fc/packages/common/module-utils/utils/get-injection-providers.util.ts#L14-L18

but at `@nestjs/core` we have a `x is OptionalFactoryDependency` with a bit different logic:

https://github.com/nestjs/nest/blob/7d62aad5fc81e839bcdb9b357e5d8fc2f513f1fc/packages/core/injector/injector.ts#L346-L350

I can't tell if this was intentional or not. Thus, I can't tell which function has the correct logic.

### Describe the solution you'd like

Ensure that both `isOptionalFactoryDependency` and `isOptionalFactoryDep` have the same logic, as we don't want to expose that internal utility from outside of `@nestjs/*` packages.

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

I believe that `OptionalFactoryDependency` should be just one thing.

Also, 3rd-party packages might want to reuse that logic (like `nestjs-spelunker` here: https://github.com/jmcdo29/nestjs-spelunker/blob/3cf07cbaef306e885eb031ad46f979cc7497dfd1/src/exploration.module.ts#L149-L153).

**Comment by kamilmysliwiec** [comment]
Sounds good to me. Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
let's track this here https://github.com/nestjs/nest/pull/14175
