### ISSUE TITLE
Multer options asynchronously provided per request

### ISSUE THREAD

**Issue by Azbesciak** [nestjs/nest#14152]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Let us imagine the situation we need to upload a bunch of files, but constrains differs per endpoint, user privilage, server mode, region - whatever, it changes by time and context.

Currently I see we may have set static endpoint config when setting `@UseInterceptors` above the controller, or globally when setting up the `MulterModule`, which even has a method `registerAsync` that gives some hope of sharing the possibility requested above (even when asking Github copilot it says the same :) ), but unfortunatelly the method is called only at the beggining, when the app is setting up.

### Describe the solution you'd like

Ideally would be to have another `registerAsyncPerRequest` (or just `registerPerRequest` because it is then async in most cases probably, or even if not it is simpler to assume that) which provides the same as the current `MulterModule.registerAsync` but takes the current request (and `ExecutionContext`) as an argument and provides options.

### Teachability, documentation, adoption, migration strategy

https://docs.nestjs.com/techniques/file-upload#async-configuration - would need to be updated

### What is the motivation / use case for changing the behavior?

As in the description, we fetch file upload constraints per user/company/app type from the database, dynamically.
It is also configurable by the app admin, even on the file type constraint to the scope I wonder if it is not easier to make that whole validation on our side in the controller instead of using the multer middleware.

**Comment by KostyaTretyak** [comment]
@Azbesciak, try [@ts-stack/multer](https://github.com/ts-stack/multer).

**Comment by Azbesciak** [comment]
@KostyaTretyak Thank you, to clarify since you posted the official repository, you mean to implement the middleware by my own then?

**Comment by KostyaTretyak** [comment]
> As in the description, we fetch file upload constraints per user/company/app type from the database, **dynamically**.
It is also configurable by the app admin, even on the file type constraint to the scope I wonder if it is not easier to make that whole validation on our side in the controller **instead of using the multer middleware**.

I assumed from this quote of yours that you don't need to build middleware. `@ts-stack/multer` is intended for dynamic parsing, exactly as you described in this issue. Did I not understand you correctly?

**Comment by Azbesciak** [comment]
@KostyaTretyak 
Maybe it is rather my invalid understaning of the middleware's purpose.
My goal is to reuse as much existing framework as possible.
I just want to validate per each request, whether files meet conditions or not.
The only problem is these conditions are not fixed and depend on the user's context, for instance.
I have the whole information already in the request, since it is provided by preceeding middlewares.

**Comment by KostyaTretyak** [comment]
Something like this is what you want to achieve, right?

```ts
import { createWriteStream } from 'node:fs';
import { Multer } from '@ts-stack/multer';
import { Controller, Scope, Post, Request, Req } from '@nestjs/common';
import { MyFileConfig } from './my-file-config';

@Controller({ scope: Scope.REQUEST })
export class AppController {
  constructor(private config: MyFileConfig) {}

  @Post()
  async getHello(@Req() request: Request) {
    // Here `photos` - is the name of the field in the HTML form.
    const multer = new Multer(this.config);
    const parsePhotos = multer.array('photos', 12);
    const parsedForm = await parsePhotos(request, request.headers);

    const promises: Promise<void>[] = [];
    parsedForm.files.forEach((file) => {
      const promise = new Promise<void>((resolve, reject) => {
        const path = `uploaded-files/${file.originalName}`;
        const writableStream = createWriteStream(path);
        writableStream.on('error', reject);
        writableStream.on('finish', resolve);
        file.stream.pipe(writableStream);
      });
      promises.push(promise);
    });

    return 'ok';
  }
}
```

**Comment by Azbesciak** [comment]
Yes, but I would rather keep the controller instance as a singleton, and provide the Multer's config per request. 
But at the end it all goes to the same thing - I cannot use the current Multer configuration options as these are static and global, and I need to find some workaround - or make things in my own way, without the framework help :)

**Comment by Azbesciak** [comment]
Actually the possible solution is to use `MulterOptions.registerAsync` with `useClass` as the one declared with `@Injectable({ scope: Scope.REQUEST })`.
I was a bit sceptic if that may work, but it did. Thank you for the hint!
So, maybe to consider if that can be more explicitly expressed - there is some cognitive and knowledge bias after all?
Or just my lack of experience :)

**Comment by Azbesciak** [comment]
Unfortunatelly - I have failed with that.
Maybe it could be possible to make multer options calculated lazyly, or not in the constructor at least...
Or instead of injecting options, to inject their provider.
https://github.com/nestjs/nest/blob/master/packages/platform-express/multer/interceptors/files.interceptor.ts#L12
That solution is very limiting. Of course - I can create my own interceptor, what I will do, but...

**Comment by KostyaTretyak** [comment]
But you can skip the config from the constructor, hardcode it directly in the service or controller method if you really need it:

```ts
import { createWriteStream } from 'node:fs';
import { Multer, MulterOptions } from '@ts-stack/multer';
import { Controller, Scope, Post, Request, Req } from '@nestjs/common';

@Controller({ scope: Scope.REQUEST })
export class AppController {
  @Post()
  async parseFiles(@Req() request: Request) {
    const multerOptions: MulterOptions = { limits: { files: 20 } };
    const multer = new Multer(multerOptions);
    // Here `photos` - is the name of the field in the HTML form.
    const parsePhotos = multer.array('photos', 12);
    const parsedForm = await parsePhotos(request, request.headers);

    const promises: Promise<void>[] = [];
    parsedForm.files.forEach((file) => {
      const promise = new Promise<void>((resolve, reject) => {
        const path = `uploaded-files/${file.originalName}`;
        const writableStream = createWriteStream(path);
        writableStream.on('error', reject);
        writableStream.on('finish', resolve);
        file.stream.pipe(writableStream);
      });
      promises.push(promise);
    });

    await Promise.all(promises);

    return 'ok';
  }
}
```

**Comment by kamilmysliwiec** [comment]
> which even has a method registerAsync that gives some hope of sharing the possibility requested above (even when asking Github copilot it says the same :) ), but unfortunatelly the method is called only at the beggining, when the app is setting up.

`registerAsync` lets you asynchronously retrieve the configuration for multer (e.g., pull it from an external source, config service, etc). However, it doesn't make the interceptor itself request-scoped

> Yes, but I would rather keep the controller instance as a singleton, and provide the Multer's config per request.

In this case, you need to create your own request-scoped interceptor. Follow the steps below:

1. Create a request-scoped interceptor that mimics the built-in file interceptor https://github.dev/nestjs/nest/blob/71e8acec3936a6b3f2d000de6b51c4253d6d5a9a/packages/platform-express/multer/interceptors/file.interceptor.ts#L25 
2. Instead of creating the multer instance in the constructor, create it in the intercept method (using request-specific configuration)
3. Consider using durable providers to not recreate the interceptor every time (on every request) https://docs.nestjs.com/fundamentals/injection-scopes#durable-providers

From the looks of this issue, it could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
