### ISSUE TITLE
Nest swagger issue on Api Responses

### ISSUE THREAD

**Issue by dmitrirussu** [nestjs/nest#1419]
Hi, I observed the next issue under the Nest Swagger Api doc, If I have two models of same name, but they export diff group of fields... Nest do expose only for first model imported... which is wrong...
Both models are used totally in diff modules 
```
Use Case 1: 
Tag {
  @ApiModelProperty({ required: true })
   uuid: string:
  @ApiModelProperty({ required: true })
  name: string
} 

Use case 2:
Tag {
  @ApiModelProperty({ required: true })
  name: string
} 
```

**Comment by nartc** [comment]
Why would you do that?

**Comment by kamilmysliwiec** [comment]
It doesn't make sense to keep 2 models that share the same name - how swagger would differentiate them?
