### ISSUE TITLE
[ValidationPipe] query params becomes object in runtime when declared with string typescript type

### ISSUE THREAD

**Issue by soumitdas** [nestjs/nest#14234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Consider the case when `ValidationPipe({ transform: true })` is used & query is defined with just typescript type like `@Query("foo") foo: string`.

Now if nested query parameter is passed the value become object in runtime.

### Example
GET /users?foo[bar]=value

```
getSomething(@Query("foo") foo: string) {
  foo = {
    bar: "value"
  }
}
```

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-wfb5dc?file=src%2Fapp.controller.ts

### Steps to reproduce

1. GET /users?userId[$ne]=NA
2. Check console for `userId type object and value {"$ne":"NA"}`
3. If the value of "userId" was passed to a DB query without further validation, it will result into query injection

### Expected behavior

Since the value was defined as "string" in typescipt & validation pipe has the context like `metatype === String` the query value should become string in runtime like `[object Object]`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.4

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^10.3.2",
    "@nestjs/core": "^10.4.4",
    "@nestjs/platform-express": "^10.4.4",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "reflect-metadata": "^0.2.1",
    "rxjs": "^7.8.1"
  }

```

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by soumitdas** [comment]
Potential change can be:

```typescript
protected transformPrimitive(value: any, metadata: ArgumentMetadata) {
    if (!metadata.data) {
      // leave top-level query/param objects unmodified
      return value;
    }
    const { type, metatype } = metadata;
    if (type !== 'param' && type !== 'query') {
      return value;
    }
    if (metatype === Boolean) {
      if (isUndefined(value)) {
        // This is an workaround to deal with optional boolean values since
        // optional booleans shouldn't be parsed to a valid boolean when
        // they were not defined
        return undefined;
      }
      // Any fasly value but `undefined` will be parsed to `false`
      return value === true || value === 'true';
    }
    if (metatype === Number) {
      return +value;
    }
    // ---------------- Proposed change ---------------
    if (metatype === String && !isUndefined(value)) {
      return String(value)
    }
    return value;
  }
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by soumitdas** [comment]
> Would you like to create a PR for this issue?

I could have, but looks like @LhonRafaat had already raised.

**Comment by LhonRafaat** [comment]
> > Would you like to create a PR for this issue?
> 
> I could have, but looks like @LhonRafaat had already raised.
> 
> He had omitted the undefined check, but I think it's required since type definition can be optional. `String(undefined) == "undefined"` Not empty string :)
> 
> For `@Query("foo") foo?: string` we might not want value of `foo` to be `undefined` as string

True, I guess I should have read the comments... 
I can do this  for sake of consistency with the Boolean check
 ```typescript
  if (metatype === String) {
      if (isUndefined(value)) {
        return undefined;
      }
      return String(value);
    }
   ```

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/14241/
