### ISSUE TITLE
Static Page created using Nest does not link another html file

### ISSUE THREAD

**Issue by BraveEvidence** [nestjs/nest#14244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I added the `@nestjs/serve-static` in my `nest.js` app, I created an `index.html` file in client folder and in that I added this code

`<li><a href="/link">Link 1</a></li>`

Now I created link.html file as well but when I click on the anchor tag in index.html, it does not navigate to link.html file
 

### Minimum reproduction code

https://github.com/BraveEvidence/NestStaticSample

### Steps to reproduce

1. Create a Nest.js project
2. npm install --save @nestjs/serve-static
3. Create a client folder in root of the project
4. Create index.html and link.html in client folder
5. In index.html add following code
`<li><a href="/link">Link 1</a></li>`

### Expected behavior

Clicking on `<li><a href="/link">Link 1</a></li>` in index.html should navigate to link.html file

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

nestjs/serve-static

### NestJS version

10.0.0

### Packages versions

```json
[System Information]
OS Version     : macOS 23.6.0
NodeJS Version : v20.17.0
NPM Version    : 10.8.2 

[Nest CLI]
Nest CLI Version : 10.4.8 

[Nest Platform Information]
platform-express version : 10.4.11
serve-static version     : 4.0.2
schematics version       : 10.2.3
testing version          : 10.4.11
common version           : 10.4.11
core version             : 10.4.11
cli version              : 10.4.8
```

### Node.js version

v20.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
