### ISSUE TITLE
@Res() response in controller hangs if not used.

### ISSUE THREAD

**Issue by Jaikant** [nestjs/nest#14276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If a controller has an unused @Res() decorator, it doesn't return a response. Even if there is a return statement.
E.g the below controller:
```
  @Get('/repro')
  async issueRepro(
    @Res() response,
  ) {
      const returncode = null;
      return returncode;
  }
```

If we add the `passthrough: true` it works ok, like below:
```
  @Get('/repro')
  async issueRepro(
    @Res({ passthrough: true }) response: Response,
  ) {
      const returncode = null;
      return returncode;
  }

```

I am raising this as a bug, since it is counter intuitive that the method does a return and nothing returns. 
This happened to me during a code refactor, when I mistakenly forgot to remove the Res() decorator from the parameter list.
If the moderators think, this is a non issue, please proceed to mark it invalid.

### Minimum reproduction code

This has probably been discussed in this issue: https://github.com/nestjs/nest/issues/6933

### Steps to reproduce

We just need to make a fetch call from the client to the endpoint of the controller. The request would be recieved but no response would be returned.

### Expected behavior

A response should be returned.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```json
    "@nestjs/cache-manager": "^2.2.2",
    "@nestjs/common": "^9.2.1",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.2.1",
    "@nestjs/event-emitter": "^1.3.1",
    "@nestjs/jwt": "^10.0.3",
    "@nestjs/microservices": "^9.2.1",
    "@nestjs/passport": "^9.0.3",
    "@nestjs/platform-express": "^9.4.1",
    "@nestjs/schedule": "^4.1.1",
    "@nestjs/swagger": "^7.4.0",


```

### Node.js version

v18.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
You're right, [this has already been discussed and documented](https://github.com/nestjs/nest/issues/6933#issuecomment-822848137)
