### ISSUE TITLE
Binding IP for a nest application is verbose

### ISSUE THREAD

**Issue by TobyColeman** [nestjs/nest#143]
Hullo 👋 

Currently if you want to bind your express instance to a specific IP you end up with something like this: 

```typescript
@Module({})
class ApplicationModule {}x

function createApp (
  server: express.Application,
  port: number,
  address: string
): Promise<INestApplication> {
  const app = NestFactory.create(ApplicationModule, server)
  app.init()

  return eventToPromise(server.listen(port, address), 'listening').then(
    () => app
  )
}
```
It would seem more ideal if [NestApplication.listen()](https://github.com/kamilmysliwiec/nest/blob/master/src/core/nest-application.ts#L75) better reflected the options that [ExpressAppliation.listen()](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-serve-static-core/index.d.ts#L1081) takes? The above isn't so ideal given that it doesn't check if the nest application has already been initialised.

**Comment by kamilmysliwiec** [comment]
Hi @TobyColeman,
Definitely needed, marked as a todo.

**Comment by xeoneux** [comment]
@TobyColeman environment variables?

**Comment by adrien2p** [comment]
Hey ! You can use dotenv easily for that

**Comment by TobyColeman** [comment]
Ah nice, I wasn't aware of an approach like this - https://stackoverflow.com/a/10714707 should have look at the express docs a bit further. Cheers for noting that down @kamilmysliwiec!

**Comment by cojack** [comment]
@adrien2p could you show how?

**Comment by chriszrc** [comment]
I noticed this project at least presents a way to configure express directly:

https://github.com/d3viant0ne/nestjs-mongoose

**Comment by kamilmysliwiec** [comment]
Hi @TobyColeman,
Since @nestjs/core 4.0.4 the `listen()` method accepts `hostname` as a second argument :slightly_smiling_face:
