### ISSUE TITLE
The type of WebSocketGateway's options does not work

### ISSUE THREAD

**Issue by sapenlei** [nestjs/nest#14303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![CleanShot 2024-12-10 at 11 38 39@2x](https://github.com/user-attachments/assets/928e6271-61c2-41b4-994b-549044778fc7)

cors has no type hints, cors2 does not show errors.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/02-gateways

### Expected behavior

cors has type hints, cors2 does show errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.15

### Packages versions

```json

[System Information]
OS Version     : macOS 24.1.0
NodeJS Version : v22.12.0
PNPM Version    : 9.0.2 

[Nest CLI]
Nest CLI Version : 10.4.8 

[Nest Platform Information]
platform-socket.io version : 10.4.15
platform-express version   : 10.4.13
mapped-types version       : 2.0.6
websockets version         : 10.4.15
schematics version         : 10.2.3
testing version            : 10.4.13
common version             : 10.4.13
core version               : 10.4.13
jwt version                : 10.2.0
cli version                : 10.4.8

```

### Node.js version

22.12

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/14305
