### ISSUE TITLE
fastify version upgrade

### ISSUE THREAD

**Issue by 0x0bit** [nestjs/nest#14304]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

With `@nestjs/platform-fastify`, if you are using the relevant fastify hooks directly, you must specify the version number because version conflicts will result in errors
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/5a07f240-3fc5-4058-a14f-2cb75372d9ca">

### Describe the solution you'd like

`@nestjs/platform-fastify` fastify package version upgrade

### Teachability, documentation, adoption, migration strategy

。

### What is the motivation / use case for changing the behavior?

。

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/14177
