### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'url') - Prisma Client

### ISSUE THREAD

**Issue by dev-mariana** [nestjs/nest#14316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I don't know why but nest is not recognizing the prisma client instance.

Prisma Service: 

import { INestApplication, Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  constructor() {
    super({
      log: ['query', 'info', 'warn', 'error'],
    });
  }
  async onModuleInit() {
    await this.$connect();
  }

  async enableShutdownHooks(app: INestApplication) {
    process.on('beforeExit', async () => {
      await this.$disconnect();
      await app.close();
    });
  }
}

db module:

import { Module } from '@nestjs/common';
import { PrismaService } from './prisma/prisma.service';
import { UrlsRepository } from './prisma/repositories/urls.repository';

@Module({
  providers: [PrismaService, UrlsRepository],
  exports: [PrismaService, UrlsRepository],
})
export class DatabaseModule {}

service:

import { PrismaClient } from '@prisma/client';
import { Url } from 'src/domain/entities/url';
import { IUrlsRepository } from 'src/domain/repositories/urls.repository';
import { PrismaService } from '../prisma.service';

export class UrlsRepository implements IUrlsRepository {
  constructor(private prismaService: PrismaService) {}

  async find(): Promise<Url[]> {
    try {
      <------- it works. ----->
      const prisma = new PrismaClient(); 
    const test = await prisma.url.findMany();

  <---- not working (undefined) --->
   const result = await this.prismaService.url.findMany();

    console.log('test -> ', test);
    console.log('test 2 -> ', result);
    } catch (error) {
      console.log(error);
    }
  }
}

### Minimum reproduction code

https://github.com/dev-mariana/desafio-nexmuv

### Steps to reproduce

1. Run docker compose up -d
2. npm i
3. npm run start:dev

### Expected behavior

Expected to return:

test2 ->  []

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```
{
  "name": "desafio-nexmuv",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.3.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "@prisma/client": "^6.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "nanoid": "^5.0.9",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^5.0.0",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^8.0.0",
    "@typescript-eslint/parser": "^8.0.0",
    "eslint": "^8.0.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "prisma": "^6.0.1",
    "source-map-support": "^0.5.21",
    "supertest": "^7.0.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

22.12.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

TypeError: Cannot read properties of undefined (reading 'url')
    at UrlsRepository.save (/Users/mariana_bastos/dev/technical-tests/desafio-nexmuv/src/infra/database/prisma/repositories/urls.repository.ts:24:40)

**Comment by micalevisk** [comment]
I just checked your repository but it does not has the full code.

---

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
