### ISSUE TITLE
Cannot create new nest project

### ISSUE THREAD

**Issue by maarre** [nestjs/nest#14346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In a directory structure already under git control.
```
>nest new nestserver
⚡  We will scaffold your app in a few seconds..

? Which package manager would you ❤️  to use? pnpm
Error: A merge conflicted on path "/nestserver/README.md".

Failed to execute command: node @nestjs/schematics:application --name=nestserver --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager="pnpm" --collection="@nestjs/schematics" --language="ts"

>Error: A merge conflicted on path "/nestserver/README.md".
```

### Minimum reproduction code

not applicable

### Expected behavior

Successful configuration of my new project.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.9

### Packages versions

```json

```

### Node.js version

v18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
looks like that's because you're using it in a directory that already has the `README.md` file. 

I guess in this case the CLI must not to write another `README.md` file but I'm not sure.

**Comment by micalevisk** [comment]
actually, when you run `nest new foo`, the CLI will create another directory called 'foo'. And so there is no way to having such file conflict.

But you must have run the same `new` command twice, which leads to that error when using PNPM as a package manager:

![image](https://github.com/user-attachments/assets/0cdc8eb6-64a2-4e3e-9777-37d8d4abcb31)

![image](https://github.com/user-attachments/assets/966a5ba1-feb0-4691-860e-68cef5cf3265)

**Comment by maarre** [comment]
If I remember correctly I got the error when executing the code in a git repo.
