### ISSUE TITLE
BaseExceptionFilter applicationRef.isHeadersSent is undefined

### ISSUE THREAD

**Issue by Makkalay** [nestjs/nest#14348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In `handleUnknownError`  is `applicationRef` but in catch is `const applicationRef = this.applicationRef ||
            (this.httpAdapterHost && this.httpAdapterHost.httpAdapter);`.

And I get `applicationRef.isHeadersSent` is undefined in modified express adapter but it is in `applicationRef._httpAdapter.isHeadersSent`

```
class BaseExceptionFilter {
    constructor(applicationRef) {
        this.applicationRef = applicationRef;
    }
    catch(exception, host) {
        const applicationRef = this.applicationRef ||
            (this.httpAdapterHost && this.httpAdapterHost.httpAdapter);
        if (!(exception instanceof common_1.HttpException)) {
            return this.handleUnknownError(exception, host, applicationRef);
        }
        const res = exception.getResponse();
        const message = (0, shared_utils_1.isObject)(res)
            ? res
            : {
                statusCode: exception.getStatus(),
                message: res,
            };
        const response = host.getArgByIndex(1);
        if (!applicationRef.isHeadersSent(response)) {
            applicationRef.reply(response, message, exception.getStatus());
        }
        else {
            applicationRef.end(response);
        }
    }
    handleUnknownError(exception, host, applicationRef) {
        console.log(applicationRef)


        const body = this.isHttpError(exception)
            ? {
                statusCode: exception.statusCode,
                message: exception.message,
            }
            : {
                statusCode: common_1.HttpStatus.INTERNAL_SERVER_ERROR,
                message: constants_1.MESSAGES.UNKNOWN_EXCEPTION_MESSAGE,
            };
        const response = host.getArgByIndex(1);
        if (!applicationRef.isHeadersSent(response)) {
            applicationRef.reply(response, body, body.statusCode);
        }
        else {
            applicationRef.end(response);
        }
        if (this.isExceptionObject(exception)) {
            return BaseExceptionFilter.logger.error(exception.message, exception.stack);
        }
        return BaseExceptionFilter.logger.error(exception);
    }
    isExceptionObject(err) {
        return (0, shared_utils_1.isObject)(err) && !!err.message;
    }
    /**
     * Checks if the thrown error comes from the "http-errors" library.
     * @param err error object
     */
    isHttpError(err) {
        return err?.statusCode && err?.message;
    }
}
```

### Minimum reproduction code

https://github.com/nestjs

### Expected behavior

-

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10

### Packages versions

--

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment]
also, run `npx nest info`

that usually happens when you're using the wrong version among `@nestjs/*` packages

**Comment by Makkalay** [comment]
but is normal to use this.applicationRef  in catch and not use it in handleUnknownError?

**Comment by micalevisk** [comment]
I'd have to see the source code to understand better what you're trying. But usuall

**Comment by Makkalay** [comment]
@micalevisk Also nest use req.send and res.type('text/html')  which not exists in my case.
I can use req.end() and something like `req.headers['Content-type'] = 'text/html';`
It will be better to use in that change some methods from adapter, to be universally.

**Comment by Makkalay** [comment]
@micalevisk  I am not at that point in that I can do that, by I will try to understand how all work and will try :)

**Comment by Makkalay** [comment]
I  do `app.useGlobalFilters(new AllExceptionsFilter(app.get(HttpAdapterHost)))` but need to pass `httpAdapter` like `app.useGlobalFilters(new AllExceptionsFilter(app.get(HttpAdapterHost).httpAdapter))`.

With no argument `app.useGlobalFilters(new AllExceptionsFilter())` and ` app.useGlobalFilters(AllExceptionsFilter)` not work too.

https://docs.nestjs.com/exception-filters#inheritance

It can do some check here to throw or something like `const applicationRef = this.applicationRef.hasOwnProperty(httpAdapter) ?? this.applicationRef.httpAdapter;`.


For what is when that code if httpAdapterHost is empty?

```
 @Optional()
  @Inject()
  protected readonly httpAdapterHost?: HttpAdapterHost;

```
