### ISSUE TITLE
LazyModuleLoader reusing same provider implementation for two modules with strict false

### ISSUE THREAD

**Issue by mathulbrich** [nestjs/nest#14341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

I've been encountering issues with `LazyModuleLoader` when resolving providers dynamically. Specifically, if I have two modules where each declares a provider with the same name (in the `provide` field), using `LazyModuleLoader` to load both modules and their providers results in only one of the providers being available.

This issue occurs only when I set the `strict` flag to false. However, this behavior seems counterintuitive since durable providers are disabled in this context.

Could this be a bug, or is it an intentional behavior when resolving providers with the `strict` flag set to false?

### Minimum reproduction code

https://github.com/mathulbrich/nestjs-lazy-loader-bug-report

### Steps to reproduce

1. Run `yarn`
2. Run `yarn build`
3. Run `yarn start`
4. Request `GET` to `http://localhost:3001/app` 

### Expected behavior

Each field having their own provider value. Should return like:

```json
{"moduleAValue":"FIRST <anything>","moduleBValue":"SECOND <anything>","moduleAValue2":"FIRST <anything>"}
```

But instead is returning:

```json
{"moduleAValue":"SECOND <anything>","moduleBValue":"SECOND <anything>","moduleAValue2":"SECOND <anything>"}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.15

### Packages versions

```json
{
  "name": "nestjs-lazy-loader-bug-report",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "nest start --entryFile app",
    "build": "nest build"
  },
  "dependencies": {
    "@nestjs/common": "^10.4.15",
    "@nestjs/config": "^3.3.0",
    "@nestjs/core": "^10.4.15",
    "@nestjs/platform-express": "^10.4.15",
    "express": "^4.21.2",
    "reflect-metadata": "^0.2.2",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.4.9",
    "@nestjs/schematics": "^10.2.3",
    "@types/express": "^5.0.0",
    "@types/node": "20.14.9",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.7.2"
  }
}

```

### Node.js version

20.14.9

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
> or is it an intentional behavior when resolving providers with the strict flag set to false?

When `strict` is set to `false`, `moduleRef` searches through all modules, regardless of context. To select a provider from a specific module, you must first choose that module using the `select` method.

Alternatively, you can set `each` to `true` (`get(..., { each: true })`), retrieve an array of providers, and then perform the filtering on your own (depending on what you need)

**Comment by mathulbrich** [comment]
@kamilmysliwiec Thanks for the answer, there's an example of how to use select method inside a provider (without using by `app.select(...)`)? I need to select this `DynamicModule` inside a logic that I have, which is inside a provider.

**Comment by kamilmysliwiec** [comment]
Assign the result of `Module#yourStaticMethod` to a variable (constant) and then import this constant instead of calling that method inline (in the imports array). You can then pass that constant to the `select(HERE)` method call
