### ISSUE TITLE
Using keyPrefix for the socket gateway with the Redis adapter

### ISSUE THREAD

**Issue by phidinhthao** [nestjs/nest#14353]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8.0.0 -> 10.0.0

### Describe the regression

When I upgraded NestJS to the latest version (@nestjs/core: ^10.0.0, redis: ^4.7.0) from old version (@nestjs/core: ^8.0.0, redis: ^3.1.2), there was an issue with using keyPrefix for the socket gateway with the Redis adapter. It seems that the keyPrefix option has been removed from the createClient function. So how can I add the keyPrefix configuration for the Redis adapter?

### Input code

```ts
const pubClient = createClient({
            url: `redis://:${process.env.REDIS_PASSWORD}@${process.env.REDIS_HOST}:${process.env.REDIS_PORT}/0`,
        });
```

### Expected behavior

old code:
```ts
const pubClient = createClient({
            host: process.env.REDIS_HOST,
            port: process.env.REDIS_PORT,
            password: process.env.REDIS_PASSWORD,
            keyPrefix: process.env.REDIS_PREFIX || ''

        });
```

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
