### ISSUE TITLE
How to use Guard with Reflector in specific routes?

### ISSUE THREAD

**Issue by ahmadarif** [nestjs/nest#1439]
I have created guard and guard reflector, but this guard is not working if not registered in module providers using APP_GUARD.

In my case, I want to execute the guard only when the routes is called. It that possible?

**Comment by kamilmysliwiec** [comment]
Please, use StackOverflow for such questions.

**Comment by ahmadarif** [comment]
Sorry, thank you for notifying me @kamilmysliwiec :)

**Comment by ahmadarif** [comment]
This is my [My Question](https://stackoverflow.com/questions/54173203/how-to-use-guard-with-reflector-in-specific-routes)
