### ISSUE TITLE
Support try…catch around next() in middleware

### ISSUE THREAD

**Issue by bradleyayers** [nestjs/nest#145]
I'd love to be able to use standard try…catch around `next()` in middleware in the way that [Koa](https://github.com/koajs/koa) does it. In my opinion this is more elegant than Nest's current middleware + exception filter combination.

I'm currently writing some middleware that wraps controllers in a database transaction. I attach the database client to the Request object, but exception handlers only have access to the Response object, so unfortunately this makes it a bit awkward.

I love the DI and encouraged type safety of Nest, but really miss the first-class async/await paradigm of koa.

**Comment by kamilmysliwiec** [comment]
Hey @bradleyayers,
The interceptors available since v4 release should fit your requirements http://www.docs.nestjs.com/interceptors
You have an access to the `request` here and also to the thrown exception.
Let me know if it's fine :)
Best,
Kamil
