### ISSUE TITLE
Cache routes/controller data automatically after application has being started

### ISSUE THREAD

**Issue by kuncevic** [nestjs/nest#1450]
## I'm submitting a...

[x ] Feature request

## Current behavior
I have a controller decorated with `CacheInterceptor` so each request is gets cached for 24 hours when client call the route. There is no data cached until client requested the route. 

## Expected behavior
I want to to be able to cache routes that has 24 hours ttl cache automatically once application got started. 

## What is the motivation / use case for changing the behavior?
In my use case the requests taking a bit of time to execute as the data is coming from different sources. I wont to provide the best experience for the client. In that particular case the data is quite static and getting changed only once in 24 hours so I just want to cache the data on application start.

**Comment by kamilmysliwiec** [comment]
It rather looks like a custom functionality that you can implement easily using existing framework's abilities. We cannot cover every scenario within the framework itself.

**Comment by kuncevic** [comment]
@kamilmysliwiec Yeah I did try to implement that myself. But I didn't find how to approach that. 
I thought I cold call my Controller methods that needs to be precached once application starts.
So found https://docs.nestjs.com/faq/lifecycle-events tried to implement `OnModuleInit` on my `Controller` but it din't work as seems like you can not call Controllers own methods on `onModuleInit`

What do you think is the best way of approaching my use case? Would you mind to point me out to the right direction?

**Comment by kamilmysliwiec** [comment]
I would do it in a different layer, for example, in services directly.

**Comment by agborkowski** [comment]
@kuncevic i think @km mean good approach is cache service cause its data access layer and its easily to cache

**Comment by kuncevic** [comment]
@agborkowski that means I shall not rely on `CacheInterceptor` as I am currently do, but just build my own custom cache mechanism on service layer? please correct me if I am wrong.

**Comment by agborkowski** [comment]
but yes yous should do maping on service lvl... why cause in order to methedology C(ontroller)-thin M(odel / Service)- fat
