### ISSUE TITLE
Can I use nest By function folder!

### ISSUE THREAD

**Issue by akai007** [nestjs/nest#1453]
![image](https://user-images.githubusercontent.com/10443550/51299167-5bc0f400-1a62-11e9-959a-113bd9b1a7f8.png)

**Comment by kamilmysliwiec** [comment]
It's all up to you. I don't know any advantage of this approach though, especially, if you held different module-scoped services/entities/controllers in the same directory.

**Comment by akai007** [comment]
> It's all up to you. I don't know any advantage of this approach though, especially, if you held different module-scoped services/entities/controllers in the same directory.
Thanks, I know nestjs design principle. And separating by layer could be better I think. sometime I can easy to rewrite on another platform. like java\koa ...

**Comment by akai007** [comment]
> It's all up to you. I don't know any advantage of this approach though, especially, if you held different module-scoped services/entities/controllers in the same directory.

Thanks, I know nestjs design principle. And separating by layer could be better I think. sometime I can easy to rewrite on another platform. like java\koa ...
