### ISSUE TITLE
Validations for forms

### ISSUE THREAD

**Issue by Grafikart** [nestjs/nest#1454]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Validation for forms use case

The documentation for the validation explains things correctly for an API application (that speaks JSON) but doesn't show how it would work for a form based application. It would be interesting to show a proposal on how to handle validation for an app that renders views instead of JSON. 
It would be a nice way to show a use case for **Exception filters**.

**Comment by cojack** [comment]
@Grafikart this works exactly the same way, u're making a `POST /somwhere` a logic make a validation on the model, it may throw exception with error messages, catch it, pass it to the view, display it.

Just it.

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions.

**Comment by cojack** [comment]
@Grafikart even better, make a PR with an explanation how to do it with examples.
