### ISSUE TITLE
[PROBLEM] Reflector - Guard doesn't run with reflector decorator

### ISSUE THREAD

**Issue by aronraja** [nestjs/nest#1478]
## I'm submitting a...

<pre><code>
[ x ] Support request
</code></pre>

## Current behavior
I have a problem with using a reflector and a guard. The problem is that the guard doesn't run on my reflector and immediately skips the guard. I am using it on @nestjs/graphql

## Expected behavior

It should log the value that was passed in.

## Minimal reproduction
**resolver.ts**
```
    @Query('test')
    @RateLimit('value', 'sometext')
    public async test(
    ){
        return await this.userService.test()
    }
```

**decorator.ts**
`export const RateLimit = (...value: string[]) => ReflectMetadata('value', value);
`

**guard.ts**
```
@Injectable()
export class RateLimitGuard implements CanActivate {
  constructor(private readonly reflector: Reflector) {}

  canActivate(context: ExecutionContext): boolean {
    const ctx = GqlExecutionContext.create(context);
    const value= this.reflector.get<string[]>('value', context.getHandler())
    // const request: Request = ctx.getContext().req

    console.log(value)

    return false 
// It still returned true/ didn't run at all...
  }
}
```

## Environment

<pre><code>
Nest version: 5.4.0

 
For Tooling issues:
- Node version: v8.11.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Could you please provide a minimal repository which reproduces your issue?

**Comment by IntellectProductions** [comment]
@kamilmysliwiec I'm having this same issue :( I just tried to basically do what was setup in the NestJS documentation and it doesn't even trigger my guard. I'm on the latest NestJS version too (5.7.3).

**Comment by picheli20** [comment]
@kamilmysliwiec same here, even if you run the example on the repo (https://github.com/nestjs/nest/tree/master/sample/01-cats-app), the `user` is always `undefined` on this guard :(

```typescript
    const request = context.switchToHttp().getRequest();
    const user = request.user;
```

**Comment by SloCompTech** [comment]
Same, here, is there a solution for this ?

**Comment by Vandell63** [comment]
Hey @SloCompTech 
I propose a solution on -> https://github.com/nestjs/nest/issues/2027#issuecomment-527863600
It could maybe help  you
