### ISSUE TITLE
NestJS: Best Practice of exception handling (Exception filters vs Interceptors.catchError)

### ISSUE THREAD

**Issue by oshevchukLviv** [nestjs/nest#1480]
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack 
[X ] question

What are pros and cons using [Exception filters](https://docs.nestjs.com/exception-filters) over [Interceptors.catchError ](https://docs.nestjs.com/interceptors)(Exception mapping) ?

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track issues/bugs/features.
