### ISSUE TITLE
Nest website issues

### ISSUE THREAD

**Issue by acronamy** [nestjs/nest#1485]
The nest website is displaying a cloudflare error page. Just a heads up. Of course this could just be my phone. 

"See how your application may potentially look like without leaving
your personal browser."

-----
Error 1101 Ray ID: 4a15dbef08e935ba • 2019-01-30 18:04:06 UTC
Rendering error
What happened?
You've requested a page on a website (codesandbox.io) that is on the Cloudflare network. An unknown error occurred while rendering the page.

Sorry it's not an issue. Just a bit of an unfortunate demo of capabilities.

**Comment by joeyslack** [comment]
More of an issue with the codesandbox embed, IMO.

**Comment by kamilmysliwiec** [comment]
I would suggest reporting this issue here https://github.com/CompuIves/codesandbox-client
