### ISSUE TITLE
CLI application interface

### ISSUE THREAD

**Issue by mhf-ir** [nestjs/nest#1487]
Any guide for create cli application. If we have any standard like other stuff like MVC, REST, Graphql, will be awesome.
Some useful stuff:
https://github.com/tj/commander.js/
http://yargs.js.org/

Use cases somthing like:
* RESET super admin user password from cli
* some bash cron or other application call my nest application for any clean cache or etc.
* run massive data process or special case processing by using services like database
* backup and gc stuff

Key feature:
* Standard CLI options and stuff
* Autocompletion stuff and etc

for php developers many users use https://symfony.com/doc/current/components/console.html

**Comment by joeyslack** [comment]
Someone has already made one: https://github.com/nestjs/nest/issues/1117

**Comment by kamilmysliwiec** [comment]
Duplicate of #1117
