### ISSUE TITLE
Cannot run latest test examples from master (cat-app)

### ISSUE THREAD

**Issue by rychkog** [nestjs/nest#151]
Steps
1) git clone ...
2) cd /nest/examples/01-cats-app
3) npm i
4) npm start
5) Observe bunch of compilations errors

Versions
OS: Linux Mint 18.2
npm - 5.3.0
node - 8.4.0

**Comment by kamilmysliwiec** [comment]
Hi @rychkog,
Thanks for reporting. I updated `package.json`. Can you verify now? :slightly_smiling_face: 
Kamil

**Comment by cojack** [comment]
@kamilmysliwiec @rychkog it works now, thanks :+1:

**Comment by kamilmysliwiec** [comment]
Cool :tada: @rychkog please confirm

**Comment by rychkog** [comment]
@kamilmysliwiec It works! Dziekuje bardzo :)

**Comment by kamilmysliwiec** [comment]
Haha. Thanks @rychkog :wine_glass:
