### ISSUE TITLE
Set multiple view directories with express

### ISSUE THREAD

**Issue by kiwikern** [nestjs/nest#1513]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
With `app.setBaseViewsDir(join(__dirname, '..', 'views');` you can set one base directory for the views by providing a string path.

## Expected behavior
Express allows for a string path or an **array of paths**, see [docs](http://expressjs.com/en/4x/api.html#app.set).

> A directory or an array of directories for the application's views. If an array, the views are looked up in the order they occur in the array.

Nest should allow for an array of strings as well, see 
https://github.com/nestjs/nest/blob/85d7384b5e2b486af42d13c7940ee2e3fa63256d/packages/core/adapters/express-adapter.ts#L129

## What is the motivation / use case for changing the behavior?
https://stackoverflow.com/q/54098773/4694994

## Environment
<pre><code>
Nest version: 5.4.0

**Comment by cojack** [comment]
So I suggest to create kind of type for `@Controller`, maybe provide an `RestController`, `WebController` or something similar by `@Controller` type argument. And during controller initialization, it might by default setup for you a view for current controller, like:


```
├── package.json
├── package-lock.json
├── public
├── src
│   ├── app.controller.ts
│   ├── app.module.ts
│   ├── main.ts
│   └── user
│       ├── user.controller.ts
│       ├── user.module.ts
│       └── views
│           ├── create.twig
│           ├── delete.twig
│           ├── edit.twig
│           └── index.twig
```

Then when it comes to return a rendered string, it will automatically know that it should take a look in the `user/views` directory to take the specific view.
