### ISSUE TITLE
Memory footprint of NestJs

### ISSUE THREAD

**Issue by cschroeter** [nestjs/nest#1519]
I just realised running the NestJs microservice example consumes around 170-180 MiB. Imho its way to heavy considering the provided functionality. Any thoughts?

**Comment by kamilmysliwiec** [comment]
It depends on transport strategy that is being used. Could you provide more details/sample, minimal repo?

**Comment by cschroeter** [comment]
Ok after doing a few more tests here are my results:

A NestJs app with an hello world controller consumes  **27.41 MiB**.
A NestJs microservice  app with a Redis client consumes **33.18 MiB**.
 
The  ~**170 MiB** I mentioned earlier included non transpiled code. So I guess th difference is mostly ts-node..

I will do a few more tests with e.g GraphQL and put the results in here.

Here is the Dockerfile for the tests.
```Dockerfile
# Stage 1 - Build
FROM node:11.8.0-alpine as builder
WORKDIR /usr/src/app

# Install all deps including devDependencies
COPY . .
RUN yarn install --frozen-lockfile && yarn build

# Stage 2 - Package
FROM node:11.8.0-alpine as app
WORKDIR /usr/src/app

# Install deps for production only
ENV NODE_ENV=production
COPY package.json yarn.lock ./
RUN yarn install --production

# Copy builded source from the upper builder stage
COPY --from=builder /usr/src/app/dist .

CMD ["node", "dist/main.js"]
```

**Comment by kamilmysliwiec** [comment]
It doesn't seem to be an issue with Nest then. Should we close this issue?

**Comment by cschroeter** [comment]
Yeah, sure. Don't think we can reduce the memory footprint any further. At least people now have a little clue what's the memory footprint of nestjs 😁
