### ISSUE TITLE
intercept method of NestIInterceptor changed and documentation example is no longer correct 

### ISSUE THREAD

**Issue by kunokdev** [nestjs/nest#1529]
[X] Regression
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request

## Current behavior
TS compile error due to type incompatibility

## Expected behavior
Behave the way it behaved in version 5.6.2

## Minimal reproduction of the problem with instructions

Method `intercept` now accepts different arguments
```
import { Injectable, NestInterceptor, ExecutionContext } from "@nestjs/common";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

export interface Response<T> {
  success: boolean;
  message: string;
  payload: T | {};
}

@Injectable()
export default class ResponseInterceptor<T> implements NestInterceptor<T, Response<T>> {
  intercept(context: ExecutionContext, call$: Observable<T>): Observable<Response<T>> {
    return call$.pipe(
      map(data => ({
        success: true,
        message: typeof data === "string" ? data : "Successfully interacted with resource",
        payload: typeof data !== "string" ? data : {}
      }))
    );
  }
}

```
## What is the motivation / use case for changing the behavior?
Be able to write code the same way it is represented in documentation. I had to upgrade to due to #1402 . Sorry for opening issue for alpha, but can you provide minimal example?

## Environment

Nest version: 6.0.0-alpha.3

**Comment by kamilmysliwiec** [comment]
> Nest version: 6.0.0-alpha.3

You have installed `6.0.0` alpha version which is not an official release yet. Please, install `5.7.0` (`@latest` tag)
