### ISSUE TITLE
Graphql typegeneration c

### ISSUE THREAD

**Issue by aalpgiray** [nestjs/nest#1550]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behaviour
When in dev  "npm run start:dev" mode, GraphQL generates type definitions which are caught by the builder and source gets rebuild. "Infinite loop" This renders dev mode completely unusable.

## Expected behaviour
A usable watch mode compiler.

**Comment by kamilmysliwiec** [comment]
See https://github.com/nestjs/graphql/issues/87
