### ISSUE TITLE
Capture request before it makes it to jwt strategy and authguard

### ISSUE THREAD

**Issue by blubberbo** [nestjs/nest#1555]
Hi, I have the following Jwt Strategy:

```
@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor(
    private readonly authService: AuthService,
    private readonly config: ConfigService,
  ) {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      secretOrKey: config.jwtSecret,
    });
  }

  async validate(req: Request, payload: JwtPayload, done) {
    // tslint:disable-next-line
    const incomingPayload: JwtPayload = { id: req['id'], email: req['email'] };
    const user = await this.authService.validateUser(incomingPayload);
    if (!user) {
      return new UnauthorizedException();
    }
    return user;
  }
}
```

and a controller implementing it with:
```
@Get()
@UseGuards(AuthGuard('jwt'))
async getThings(@Query() query): Promise<any> {
```

and I would like to accomplish 2 things:

1. I would like to not have to pass a token in dev
2. I would like to, when in a live environment, not require a token coming from certain domains

It seems to me that the best way to do this would be to catch the request coming in and then check if a) it is not production - in which case just say the request is valid w/o a token and b) if it is production, then check if it is from a whitelisted domain, so allow the request even w/o a token

What I cannot seem to do is find a way to access the request before it validates the jwt in the header. I assume the solution has something to do with me writing a class that inherits something from passport, but I am not sure what.

Any guidance would help and I am happy to show whatever code is necessary

**Comment by kamilmysliwiec** [comment]
Simply extend `AuthGuard('jwt')` and check env variables/request before passing it to the `super.canActivate()` method. See here https://docs.nestjs.com/techniques/authentication **Inheritance** section.

Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions next time.
