### ISSUE TITLE
analytics on traffic (universal-analytics throwing error)

### ISSUE THREAD

**Issue by blubberbo** [nestjs/nest#1556]
the documentation didn't have anything on tracking (or analytics) on the traffic to the server.

I am building an api and would like a way to log or get analytics on traffic - is there a recommended standardized way?

I started to implement [universal-analytics](https://github.com/peaksandpies/universal-analytics) but ran into `universal_analytics_1.default is not a function` error and can't find much about it

**Comment by kamilmysliwiec** [comment]
There is no recommended way so far. We are doing our best to provide as many examples as possible. However, it's very tough to cover every possible use-case. Also, please, next time use this https://github.com/nestjs/docs.nestjs.com/issues repo.
