### ISSUE TITLE
document missing single quotes

### ISSUE THREAD

**Issue by yingjun** [nestjs/nest#1558]
https://docs.nestjs.com/techniques/mvc

import { NestFactory, FastifyAdapter } from '@nestjs/core';
import { ApplicationModule } from './app.module';
import { join } from 'path';

async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule, new FastifyAdapter());
  app.useStaticAssets({
    root: join(__dirname, '..', public'), //**-> missing left single quotes**
    prefix: '/public/',
  });
  app.setViewEngine({
    engine: {
      handlebars: require('handlebars'),
    },
    templates: join(__dirname, '..', 'views'),
  });
  await app.listen(3000);
}
bootstrap();

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed, I'll publish an update soon.
