### ISSUE TITLE
@nest/cli

### ISSUE THREAD

**Issue by felipemouradev** [nestjs/nest#156]
why not?

**Comment by ThomRick** [comment]
Hey @felipemouradev 
What the issue is about ?

**Comment by felipemouradev** [comment]
The possibility of implementing a CLI for the nest, I gave a good study in the framework, but felt a need for a CLI tool to generate code scafolds, to make development more agile.

**Comment by felipemouradev** [comment]
Just as the Angular

**Comment by felipemouradev** [comment]
Sorry I still had not seen the https://github.com/nestjs/nest-cli was part of the same repo of the official nest, I found some problems in it, but that's another issue.

**Comment by ThomRick** [comment]
Ok no problem !

**Comment by ShinDarth** [comment]
@kamilmysliwiec is the cli stable already? the documentation still points to the starter project `nest-typescript-starter` to setup a new project instead of using the cli. Is there a reason for that?

**Comment by kamilmysliwiec** [comment]
@ThomRick we need Thom to update CLI to the latest Nest version :slightly_smiling_face:

**Comment by ThomRick** [comment]
Hey guys !
I'll update Nest-CLI project templates soon !

**Comment by ShinDarth** [comment]
ok thanks for your answers and keep up the good work!

**Comment by ThomRick** [comment]
Hey @ShinDarth 
The typescript template is up to date with the last Nest version.
Let's try to create a new project.

If you want you can beta test the nest-cli update command on your already created project.
I have no feedbacks about it :-)

**Comment by kamilmysliwiec** [comment]
Thanks @ThomRick :heart:

**Comment by ShinDarth** [comment]
@ThomRick sorry for the late response, however I have no already created projects with nestjs. I'm just approaching to this framework and I was wondering what's the best way to actually create a new project
