### ISSUE TITLE
How to useGlobalPipes('rest') with serve angular static files ?

### ISSUE THREAD

**Issue by yantrab** [nestjs/nest#1564]
I wont to use 'rest' for all non client files, so i adding:
`app.setGlobalPrefix('rest');` 

But then FrontendMiddleware not  working:

```
export class AppModule {
  configure(consumer: MiddlewareConsumer): void {
    consumer.apply(FrontendMiddleware).forRoutes(
      {
        path: '/**', // For all routes
        method: RequestMethod.ALL, // For all methods
      },
    );
  }
}
```

so what is the solution?

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions.

**Comment by yantrab** [comment]
Ok, someone can help me with [that](https://stackoverflow.com/questions/54739873/how-to-use-global-pipes-rest-with-serve-angular-static-files)?
