### ISSUE TITLE
problem with socket.io-redis adapter

### ISSUE THREAD

**Issue by Mangdar** [nestjs/nest#1575]
main.ts
---------------------------------------------------------------------
import { RedisIoAdapter } from 'dist/src/modules/socket-adapters/redis-io.adapter';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, { cors: true });
  await app.useWebSocketAdapter(new RedisIoAdapter(app));
  await app.listen(3000);
}
bootstrap();

redis-io.adapter.ts
---------------------------------------------------------------------
import { IoAdapter } from '@nestjs/websockets';
import * as redisIoAdapter from 'socket.io-redis';

const redisAdapter = redisIoAdapter({ host: 'localhost', port: 6379 });

export class RedisIoAdapter extends IoAdapter {
  createIOServer(port: number, options?: any): any {
    const server = super.createIOServer(port, options);
    server.adapter(redisAdapter);
    return server;
  }
}

---------------------------------------------------------------------
i got error
---------------------------------------------------------------------
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

**Comment by kamilmysliwiec** [comment]
Hey @Mangdar,
You have to set up your local `redis` instance https://redis.io/ (it may run in the docker container) :)
