### ISSUE TITLE
Update Peer Dependency

### ISSUE THREAD

**Issue by johannesschobel** [nestjs/nest#1577]
Dear @kamilmysliwiec ,

should those `peerDependency` be updated to the latest versions?
https://github.com/nestjs/nest/blob/6cea5928dee266494eb43f7273140410a234b20c/packages/testing/package.json#L15-L18

Actually, if i run
```
yarn install
``` 
I get the following warning:
```
warning " > @nestjs/testing@5.7.2" has unmet peer dependency "@nestjs/common@5.*".
warning " > @nestjs/testing@5.7.2" has unmet peer dependency "@nestjs/core@^5.0.0".
```

All the best and thank you very much for your clarification

**Comment by kamilmysliwiec** [comment]
@5.7.2 should match both versions https://semver.npmjs.com/ (and previous ones should work well too).

**Comment by johannesschobel** [comment]
yeah, according to the semver page this should work.. However, if i run `yarn install` i get this warning and i cannot resolve why?!
