### ISSUE TITLE
Bug in doc about pipes?

### ISSUE THREAD

**Issue by cojack** [nestjs/nest#158]
Below: "Now it's time to finish the ValidationPipe class.", in function `async transform` in file `validation.pipe.ts` there is `return value;` it should't be `return object;`?

**Comment by kamilmysliwiec** [comment]
Hey @cojack,
Not exactly. The `ValidationPipe` responsibility is to validate the parameter, not transform it. If you'd return the `object` instead of `value`, you'll override the original property.
