### ISSUE TITLE
02-gateways not working

### ISSUE THREAD

**Issue by ningacoding** [nestjs/nest#1584]
Cloned example project, so details of issue reproduction are skipped.

02-gateways, not working:

-  socket.io-redis package missing

![image](https://user-images.githubusercontent.com/17342546/53302592-a41fbe80-3825-11e9-8874-e5e7e77c61c9.png)

- WebSocket not listening

Nest Startup Logs:
> nest-typescript-starter@1.0.0 start (etc)/nest-master/sample/02-gateways
> ts-node src/main.ts

> [Nest] 14177   - 24/2/2019 11:16:48   [NestFactory] Starting Nest application...
> [Nest] 14177   - 24/2/2019 11:16:48   [InstanceLoader] ApplicationModule dependencies initialized +8ms
> [Nest] 14177   - 24/2/2019 11:16:48   [InstanceLoader] EventsModule dependencies initialized +0ms
> [Nest] 14177   - 24/2/2019 11:16:48   [NestApplication] Nest application successfully started +25ms

Client: 
![image](https://user-images.githubusercontent.com/17342546/53302594-4a1ef900-3825-11e9-82f9-e0c47b78ec50.png)

## Details:

Even adding the missing package, WebSocket does not works, i'm ussing:

Plattform: Linux - Ubuntu 18.04.2LTS
Node: v8.10.0
NPM: 3.5.2

**Comment by ningacoding** [comment]
Client Code:

    this.socket = io("//localhost:3000", {
      reconnectionDelay: 1000, // we need this
      reconnection: true,// we need this
      reconnectionAttempts: 10,// we need this
      transports: ["websocket"],// we need this
      agent: false, // [2] Please don't set this to true
      upgrade: false, // we need this
      rejectUnauthorized: false // we need this
    });

    this.socket.on("error", (err) => {
      console.log("SOCKET ERROR", err);
    });

    this.socket.on("disconnect", (err) => {
      console.log("SOCKET DISCONNECT", err);
    });

    this.socket.on("connect_error", (err) => {
      console.log("SOCKET CONNECT ERROR", err);
    });

    this.socket.on("reconnect", () => {
      console.log("SOCKET RECONNECT");
    });

    this.socket.on("reconnect_attempt", () => {
      console.log("SOCKET RECONNECT ATTEMPT");
    });

    this.socket.on("reconnecting", () => {
      console.log("SOCKET RECONNECTING");
    });

    this.socket.on("reconnect_failed", (err) => {
      console.log("SOCKET RECONNECT FAILED", err);
    });

    this.socket.on("reconnect_error", (err) => {
      console.log("SOCKET RECONNECT ERROR", err);
    });

    this.socket.on("connect_timeout", (err) => {
      console.log("SOCKET CONNECT TIMEOUT", err);
    });

    this.socket.on("connect", () => {
      console.log("SOCKET IO CONNECTED", this.socket.id);
      this.socket.send("message", { test: "test" });
    });

**Comment by kamilmysliwiec** [comment]
> socket.io-redis package missing

It's just an example adapter - not necessarily required by this example. 

Please, provide a minimal repository which reproduces your issue.

**Comment by ningacoding** [comment]
This is the minimal repository which reproduces the issue:

https://github.com/nestjs/nest/tree/master/sample/02-gateways
