### ISSUE TITLE
Is there any way to create a custom cli command

### ISSUE THREAD

**Issue by xujif** [nestjs/nest#160]

**Comment by cojack** [comment]
what do you mean @xujif?

**Comment by xujif** [comment]
How can I create a DI enviroment with out create app.  like   typedi

**Comment by cojack** [comment]
I do not understand you at all, sorry, you have to explain it better.

**Comment by ThomRick** [comment]
Hey @xujif !
Your issue is about Nest or Nest-CLI ?
I looked around typedi and that's awesome !
I didn't play with Nest without creating application yet ! 
Let's try this but it seems that you need to create application in order to create Nest entity instances in the container.

**Comment by xujif** [comment]
@cojack  I want to create some cli command with the  Module and components injected.
```typescript
export class SomeCommand {
     protected userResp: Repository<User>
     constructor( @Inject('db') private db: Connection) {
        this.userResp = db.getRepository(User)
    }
    handle(){  
     // do some thing
    }
}
const cmd = NestFactory.createInstance(SomeCommand) // like typedi
cmd.handle()
// or 
NestFactory.registerCommand('some',SomeCommand)
// in bash
node cli.js some --arg some-arg
```

**Comment by kamilmysliwiec** [comment]
Hi @xujif,
It's not possible and probably won't be possible in the future.

**Comment by JulianBiermann** [comment]
@xujif If you want to create custom generated components take a look at `yeoman-generator`s.

**Comment by xujif** [comment]
@JulianBiermann @kamilmysliwiec I'm not mean to create custom command .
I mean to create an DI enviroment to inject dependency, ignore the last line of code 
```javascript
export class SomeCommand {
     protected userResp: Repository<User>
                   // will inject db
     constructor( @Inject('db') private db: Connection) {
        this.userResp = db.getRepository(User)
    }
    handle(){  
     // do some thing
    }
}
const cmd = NestFactory.createInstance(SomeCommand) // create a DI enviroment 
// like  typeDi     Container.get(SomeCommand)  to get an instance with dependencies injected.
cmd.handle()
```

**Comment by geecu** [comment]
@kamilmysliwiec care to explain a little why this isn’t even considered? Is there an easy way to create custom commands that have access to the DI? Coming from a PHP/Symfony background, I’m certainly expecting this from a framework... ( https://symfony.com/doc/current/console.html ). Is there a chance this issue was closed without understanding the requirement and it’ll be considered in the future?

**Comment by kamilmysliwiec** [comment]
In the nearest update, there's a possibility to create a Nest context. It'll create an application instance without running HTTP server in the background, and you'll be able to select any component that is a part of the DI container.
