### ISSUE TITLE
Typings abstract class

### ISSUE THREAD

**Issue by myeveryheart** [nestjs/nest#1607]
## GraphQLModule 

[ ] Bug report

The doc shows
```
export class Author {
  id: number;
  firstName?: string;
  lastName?: string;
  posts?: Post[];
}

export class Post {
  id: number;
  title?: string;
  votes?: number;
}

export abstract class IQuery {
  abstract author(id: number): Author | Promise<Author>;
}
```
Author and Post are not abstract class。

But when I run start, I get
```
export abstract class Author {
  id: number;
  firstName?: string;
  lastName?: string;
  posts?: Post[];
}
```

## Expected behavior
I do not want abstract class。

"@nestjs/common": "^5.7.3",
"@nestjs/core": "^5.7.3",
"@nestjs/graphql": "^5.5.5",
 
For Tooling issues:
- Node version: v10.15.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Fixed in `@nestjs/graphql@5.5.7`. :)
