### ISSUE TITLE
Define routes in an external config

### ISSUE THREAD

**Issue by govorov** [nestjs/nest#161]
Hi!
The way of defining routes via decorators in controllers directly is fine, but sometimes it's quite useful to have an external config with routes. It has a variety of advantages and config could look something like:
```
export const AppRoutes = [
    {
        path: 'prefix',
        children: [
            {
                method     : 'GET',
                path       : 'feature1', // "/prefix/feature1"
                controller : Feature1Controller,
            },
        ],
    },

    // or even allow actions be in a separate class
    // and map to action directly
    {   
        method : 'POST',
        path   : 'prefix2',
        action : SomeAction,
    },

    // or provide rails-like conventions about method names
    {
        path: 'rest-api',
        restController: ApiController,
    }
];
```

And then attach routes to a module:
```
@Module({
    routes: [
        AppRoutes,
    ],
})
export class ApplicationModule {}
```

It there a way to use this kind of routing with the current Nest API?

**Comment by kamilmysliwiec** [comment]
Hey @govorov,
The idea behind Nest is to create routes in the declarative-way, without any external config. I'm sorry, but it won't be possible in the future :slightly_frowning_face:

**Comment by JulianBiermann** [comment]
@govorov 

Maybe a Workaround is to declare your routes in a class with static fields and use them in the decorators:

```typescript
@Controler(MyStaticRouteConfig.Controllers.Cat)
export class MyController {

    @Get(MyStaticRouteConfig.Methods.Cat.Get)
    public async loveCats(): Promise<Cat> {
    }

}
```

I didn't test it but maybe it works.

**Comment by kamilmysliwiec** [comment]
@JulianBiermann constant values should work fine
