### ISSUE TITLE
Nest can't resolve dependencies of the CACHE_MANAGER (?). Please make sure that the argument at index [0] is available in the CacheModule context

### ISSUE THREAD

**Issue by feleventh** [nestjs/nest#1625]
## Hi, When I wanted to use the cache , I got the error

<pre><code>
import { Injectable, Inject, HttpException, CACHE_MANAGER, HttpService } from '@nestjs/common';
import { WeixinParams } from './interfaces/weixinparams.interface';
import * as crypto from 'crypto';

@Injectable()
export class WeixinService {
  constructor(
    @Inject(CACHE_MANAGER) protected readonly cacheManager: any,
    @Inject(HttpService) private readonly httpService: HttpService,
  ) {}

  /**
   * 验证服务器
   * @param {WeixinParams} weixinParams
   * @param {string} token
   */
  validateServer(weixinParams: WeixinParams, token: string): string{
    const {signature, nonce, timestamp, echostr} = weixinParams;
    const str = [token, timestamp, nonce].sort().join('');
    const shasum = crypto.createHash('sha1');
    shasum.update(str);
    const result = shasum.digest('hex');
    if (result === signature){
      return echostr;
    } else {
      return 'wrong';
    }
  }
  /**
   * get access_token
   */
  async getAccessToken(appId: string, appSecret: string): Promise<string> {
    console.log(CACHE_MANAGER);
    console.table(this.cacheManager);
    const accessToken = await this.cacheManager.get(appId);
    if (accessToken) {
      return accessToken;
    } else {
      const url = `https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${appId}&secret=${appSecret}`;
      const { data } = await this.httpService.get(url).toPromise();
      if (data.errcode) {
        throw new HttpException(data.errmsg, data.errcode);
      }
      await this.cacheManager.set(appId, data.data.access_token);
      return data.data.access_token;
    }
  }
}

</code></pre>

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
