### ISSUE TITLE
Importing CACHE_MANAGER from CacheModule / 

### ISSUE THREAD

**Issue by dantman** [nestjs/nest#1633]
## Summary
I want to import `CACHE_MANAGER` from CacheModule to use in a userland cache in addition to the built-in controller cache. I'm using a cache server so I'd much prefer to reuse the cache manager instead of instancing multiple connections to the cache from the same application used for the same purpose.

However it is not working and I am rubbing up against limits to the dependency injection system that may either be an issue with the system, an issue with CacheModule, or a limitation in the dependency injection system that should be documented.

#1625 may be related, but I've provided a repository to reproduce the issue and more specific details.

## Minimal reproduction of the problem with instructions
Here's a snippet with the general idea. (3 files condensed into one for an overview)

And a full repo you can run `npm run test` in: https://github.com/dantman/nestjs-user-cache-test/commit/f80e4754eb8583d88699a5e725933f03903261cc

```ts
@Module({
  imports: [CacheModule],
  providers: [UserCacheService],
  exports: [UserCacheService],
})
export class UserCacheModule {}

@Injectable()
export class UserCacheService {
  constructor(@Inject(CACHE_MANAGER) private readonly cache: Cache) {}

  get(key: string) { return this.cache.get(key); }
}

const module: TestingModule = await Test.createTestingModule({
  imports: [CacheModule.register({}), UserCacheModule],
}).compile();
```

This seems correct according to the documentation provided about the dependency injection system and the source code. CacheModules exports CACHE_MANAGER. I explicitly import CacheModule. And the "root" module (a testing one in this case to experiment) registers a CacheModule with config and imports the UserCacheModule.

I've also tried this and every permutation I can think of the following:

- Modifying CacheModule so provider and exports are part of `register`/`registerAsync` instead of the `@Module({})`
- Using `imports: [forwardRef(() => CacheModule)],` in case there is a race condition
- Using `@Inject(forwardRef(() => CACHE_MANAGER))` in case there is a race condition

## Current behaviour

Every thing I try with that general approach ends up with one of these two errors:
- `Nest can't resolve dependencies of the UserCacheService (?). Please make sure that the argument at index [0] is available in the UserCacheModule context.`
- `Nest can't resolve dependencies of the CACHE_MANAGER (?). Please make sure that the argument at index [0] is available in the CacheModule context.`

The only thing that works is to make UserCacheModule a dynamic module where the `imports: [CacheModule.register(options)],` is done inside of the `UserCacheModule.register` and then `exports: [CacheModule, UserCacheService]`.

However that feels questionable. Instead of just importing the CacheModule that the application has defined config for at the root; CacheModule's config options are integrated into the UserCacheManager's implementation details. And this only works if there is one module that needs to do this; if there are more, then config and possibly CacheModule instances will be duplicated.

**Comment by kamilmysliwiec** [comment]
It's not an issue. `CacheModule` isn't global, which means that you have to register it everywhere when you use it. If you want to share cache configuration among multiple providers, simply create your cache/core module which imports `CacheModule`, calls `.register()` and re-exports configured `CacheModule` + you can make your module `@Global()` if you don't want to import it everywhere.
