### ISSUE TITLE
Attach user details to request object

### ISSUE THREAD

**Issue by MR-Karimii** [nestjs/nest#1634]
## I will set global middleware for attach user details to request object...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[x] Support request 
</code></pre>

## Current behavior
I set globaly middleware and it work in http...

```
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer): void {
    consumer.apply(AuthMiddleware).forRoutes('*');
  }
```

## Expected behavior
But is not work in gateway...

## Environment

<pre><code>
Nest version: 5.2.2

**Comment by kamilmysliwiec** [comment]
Middleware don't apply to the websockets - it's not an issue. Use interceptors instead.
