### ISSUE TITLE
TypeOrm Recipe fails when running after tsc transpilation (start:prod)

### ISSUE THREAD

**Issue by chriszrc** [nestjs/nest#164]
So when running from the /dist folder, using the default instructions/code I got this error:

```
No repository for "Region" was found. Looks like this entity is not registered in current "default" connection?
```

Region is my entity, and it worked fine running with nodemon. Looking through the TypeOrm docs, I noticed this alternate configuration for createConnection:

```
entities: [__dirname + "/modules/**/entity/{*.ts,*.js}"],
```
ref: https://typeorm.github.io/connection.html

Updating the example with the matching of both ts and js files enabled the app to work when running with node. I assume this works because there are no ts files to be found after transpilation, and typeorm needs to be configured to look for the js files when running under node, but I am also brand new to TypeOrm.

```
//this worked
entities: [
   __dirname + '/../**/**.entity{.ts,.js}'
],
```

Is this a bug or did I miss something else?

**Comment by chriszrc** [comment]
Ok, I confirmed with typeorm that if you're not using ts-node (which is only used by default in the dev mode for nestjs), that you would need the above modifications - 

https://github.com/typeorm/typeorm/issues/682#issuecomment-331187289

**Comment by kamilmysliwiec** [comment]
Hi @chriszrc,
Thanks! Will fix the issue in the docs asap :slightly_smiling_face:

**Comment by kamilmysliwiec** [comment]
Hello again,
Fixed now. Thanks!
