### ISSUE TITLE
CORS Demo?

### ISSUE THREAD

**Issue by Feng-JY** [nestjs/nest#165]

**Comment by Feng-JY** [comment]
Not active. use v4
Middleware -> 
![image](https://user-images.githubusercontent.com/13466494/30768869-5e29558a-a041-11e7-8b4a-fbed43255c2f.png)

ApplicationModule ->
![image](https://user-images.githubusercontent.com/13466494/30768873-6f80c322-a041-11e7-87cd-0a12a0197f7e.png)

**Comment by kamilmysliwiec** [comment]
Hey @Feng-JY,
As far as I know, everything is working correctly (the middlewares are applied). By the way, you can use https://github.com/expressjs/cors (cors package) and then just call `app.use(cors())`.

**Comment by matthewharwood** [comment]
@kamilmysliwiec 100% works I'm using it in my project
https://github.com/illuminism/platform/blob/master/server/src/index.ts#L35

However, I think @Feng-JY wants to make it a middleware so he can scope a certain module and associated route(r/s) of the application. The way I did it, cors are open to all routes of the entire application, which isn't very robust.

**Comment by cojack** [comment]
How about something more complex, like this:

```typescript
import { Middleware, NestMiddleware, ExpressMiddleware } from '@nestjs/common';
import * as cors from 'cors'

@Middleware()
export class CorsMiddleware implements NestMiddleware {
  resolve(...args: any[]): ExpressMiddleware {
    return (req, res, next) => {
      cors({}, req, res, next);
    };
 }
}```

**Comment by kamilmysliwiec** [comment]
Furthermore, I think functional middleware fits better here.

**Comment by kamilmysliwiec** [comment]
Hi @Feng-JY,
Are you still having some troubles with this middleware?

**Comment by Caballerog** [comment]
Hi!

I just to use the @matthewharwood link to use cors() and it works!.

Although, would be interesting a little reference in the documentation to "https://github.com/expressjs/cors" ;-)

Thanks.

**Comment by cschroeter** [comment]
You could also just in main.ts 

```typescript
import { NestFactory } from '@nestjs/core';
import { ApplicationModule } from './app.module';
import * as cors from 'cors';

async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule);
  app.use(cors());
  await app.listen(5000);
}
bootstrap();

**Comment by mwanago** [comment]
@cojack although it seems very nice and clean, it does not work for me. Function cors is never called. Try this:
```import { Middleware, NestMiddleware, ExpressMiddleware } from '@nestjs/common';
import * as cors from 'cors';

@Middleware()
export class CorsMiddleware implements NestMiddleware {
    resolve(...args: any[]): ExpressMiddleware {
        return cors();
    }
}
```
You can pass options as a first argument of cors().

**Comment by chriszrc** [comment]
This lib makes this a breeze - https://github.com/wbhob/nest-middlewares
