### ISSUE TITLE
[DOCS] Recipes pages redirect to home page

### ISSUE THREAD

**Issue by g0d0** [nestjs/nest#167]
The URLs bellow are used onto left-bottom-menu on https://docs.nestjs.com, but your click redirect to home page.

https://docs.nestjs.com/recipes/passport
https://docs.nestjs.com/recipes/cqrs
https://docs.nestjs.com/recipes/mongodb
https://docs.nestjs.com/recipes/graphql
https://docs.nestjs.com/recipes/swagger

**Comment by kamilmysliwiec** [comment]
Hi @g0d0,
That's true. The reason is that they're not finished yet. I'm gonna create these pages as soon as possible, just need to find some free time :slightly_smiling_face:
