### ISSUE TITLE
Are there any examples for global guards usage?

### ISSUE THREAD

**Issue by BruceHem** [nestjs/nest#169]
I'm trying to create a global guard but it doesn't seem to work.

**Comment by kamilmysliwiec** [comment]
Hi @BruceHem,
Can you paste your code?
Kamil

**Comment by BruceHem** [comment]
Here's part of my server.ts setup.
![screen shot 2017-09-27 at 2 04 14 pm](https://user-images.githubusercontent.com/15667259/30900105-d61aec9a-a38c-11e7-86bd-ff5a49eaea43.png)

And the following is my guard.
![screen shot 2017-09-27 at 2 04 28 pm](https://user-images.githubusercontent.com/15667259/30900131-ecf535b0-a38c-11e7-9cd3-86c6b511ae9d.png)

I'm just logging in the logic. But when I request the api endpoint I don't see any logs.

I miss something?

**Comment by BruceHem** [comment]
It logs if I use @UseGuards(AuthGuard) directly on the controller.

**Comment by kamilmysliwiec** [comment]
Hi @BruceHem,
Please update your version of @nestjs/core to 4.0.4 and please, let me know if you still have any issues :slightly_smiling_face:

**Comment by obedm503** [comment]
I'm still experiencing this with @nest/core 4.5.10. the only difference in my case is that i'm using graphql. so if I use `@UseGuards` on the resolver class it works (except on `@Mutation`s), but doesn't work at all when using it globally. 
let me know if I should open a different issue instead
