### ISSUE TITLE
Use bodyParser by default

### ISSUE THREAD

**Issue by brunokrebs** [nestjs/nest#170]
The framework already serializes responses as JSON objects (even instances of classes). Wouldn't it make sense to use `app.use(bodyParser.json());` by default?

**Comment by kamilmysliwiec** [comment]
Hi @brunokrebs,
It'd be great, but I'm afraid that a lot of people who are already using the framework would have to change the existing code = it's a breaking change. I'll think about it, but no earlier than with the next major release. 
Thanks :slightly_smiling_face:
