### ISSUE TITLE
Microservices sample

### ISSUE THREAD

**Issue by thangs2** [nestjs/nest#172]
Hi,

Thanks for your NestJS, it is really nice and clean.
So, Do we have any example for Microservices with EventSourcing?

Thanks.

**Comment by kamilmysliwiec** [comment]
Hi @thangs2,
Nope. There's only an example with CQRS here https://github.com/kamilmysliwiec/nest-cqrs-example. It should be pretty easy to add events storing. Unfortunately, there's no full example available yet.

**Comment by malixsys** [comment]
@kamilmysliwiec How well do these microservices scale?
