### ISSUE TITLE
Change ArgumentsHost to WsArgumentsHost

### ISSUE THREAD

**Issue by lossless1** [nestjs/nest#1725]
https://github.com/nestjs/nest/blob/55646f5ae2356b269ce83f3da3d2fdf34db8c630/packages/common/interfaces/exceptions/ws-exception-filter.interface.ts#L4

https://github.com/nestjs/nest/blob/55646f5ae2356b269ce83f3da3d2fdf34db8c630/packages/websockets/exceptions/base-ws-exception-filter.ts#L7

**Comment by kamilmysliwiec** [comment]
Each filter takes `ArgumentsHost` as an input parameter for the sake of consistency between filters, interceptors, and guards. You can switch to `WsArgumentsHost` by calling `.switchToWs()`.
