### ISSUE TITLE
websockets: Acknowledgment functions are not being called

### ISSUE THREAD

**Issue by thesayyn** [nestjs/nest#1727]
## I'm submitting a...
[ x ] Bug report

## Current behavior
Acknowledgment functions are not being called if the event does not have any arguments rather than ack function.

## Expected behavior
Acknowledgment functions should be called 

## Minimal reproduction of the problem with instructions
`
socket.emit('test', 'dsadsa', console.log) is called but 
socket.emit('test',  console.log) is not.

`

## Environment
MacOS Mojave
@nestjs/*@^5.7.3

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
