### ISSUE TITLE
Interceptor response mapping

### ISSUE THREAD

**Issue by ajvorobiev** [nestjs/nest#174]
Hi,

I'm using version 4.0.1 and am having trouble writing a response transformation interceptor. The interceptor is hit in debug but the response body is the same as without it.

controller (I'm using global interceptors):
```
@Get()
async getVersionInformation(@Response() res) {
        const info = await this.infoService.getInfo();
        res.status(HttpStatus.OK).json(info);
 }
```

interceptor:
```
  intercept(dataOrRequest, context: ExecutionContext, stream$: Observable<any>): Observable<any> {
    return stream$.map((data) => (
        {data}
    ));
  }
```

The general set up is as in the example. What am I doing wrong?

Thanks.

P.S. The logging interceptor sample works fine.

**Comment by kamilmysliwiec** [comment]
Hi @ajvorobiev,
The response mapping doesn't work with the express response strategy (using `@Res()` object directly is not possible). I've added the *note* about it in the docs. https://docs.nestjs.com/interceptors :slightly_smiling_face: 
Thanks,
Kamil
