### ISSUE TITLE
TypeError for newly typed providers

### ISSUE THREAD

**Issue by kiwikern** [nestjs/nest#1747]
## I'm submitting a...

<pre><code>
[x] Regression 
</code></pre>

## Current behavior

In my test, I'm mocking typeorm's EntityManager:
```
{ provide: getEntityManagerToken(), useFactory: entityManagerMockFactory },
```
Since v6, this is now throwing a type error: `Type 'string | Function' is not assignable to type 'string | symbol | Type<any>'.`

## Expected behavior

The typing that was introduced in commit https://github.com/nestjs/nest/commit/758257291b1067bc4828fd51e37cb9d8031ccca4 should allow for `Function` as a provider token. (Or alternatively, the types for `getEntityManagerToken` etc. in nestjs/typeorm should be changed.)

https://github.com/nestjs/nest/blob/81d8dae7cd8212c6efd43cc47c3a093a3f046d44/packages/common/interfaces/modules/provider.interface.ts#L22

## Minimal reproduction of the problem with instructions
Add the following line to a test case in your TestingModule's declaration:
```
{ provide: getEntityManagerToken(), useValue: {} },
```

## Environment

<pre><code>
Nest version: 6.0.1

**Comment by kamilmysliwiec** [comment]
Fixed in 6.0.2 :)
