### ISSUE TITLE
Nest TypegraphQL AuthGuards

### ISSUE THREAD

**Issue by hxdef2517** [nestjs/nest#1767]
Basically Is there a way to get a context and read auth headers using guard with typegraphQL package ?

**Comment by kamilmysliwiec** [comment]
Sure. See https://docs.nestjs.com/graphql/tooling#execution-context + you have to assign `request` to the `context` - https://docs.nestjs.com/techniques/authentication

**Comment by hxdef2517** [comment]
@kamilmysliwiec thank you so much ! it works 👍
