### ISSUE TITLE
WebSocketGateway Subscription

### ISSUE THREAD

**Issue by kwtsangaf** [nestjs/nest#177]
Hi,
WebSocketGateway has port config. Does WebSocketGateway has server ip config? I want to subscribe another server emitter but I don't know how to do it. Thanks for the help.

**Comment by cojack** [comment]
@kwtsangaf there're a second param as "hostname", maybe try to pass here the ip, you wan't to bind?

**Comment by kamilmysliwiec** [comment]
Hi @kwtsangaf,
The @cojack's solution should work for you. Let us know if you still have any issues 🙂
