### ISSUE TITLE
关于技术文档的建议

### ISSUE THREAD

**Issue by lishizhi** [nestjs/nest#1770]
作者你好，我非常喜欢nestjs，感谢你的付出。有很多像我一样没有后端经验的人想学nestjs，但是目前的技术文档看着很吃力，如果能详细一些就更好了，谢谢。

**Comment by dzzzzzy** [comment]
You can join this Chinese developer's QQ group: 489719517, there are many Chinese developers using nestjs, and they can help you to learn nestjs. :heart: :muscle:

**Comment by kamilmysliwiec** [comment]
I would love to know Chinese to chat with you 😢 @lishizhi  I recommend looking here then (QQ group) 489719517
