### ISSUE TITLE
[Passport] Custom callback in Passport Middleware for error handler

### ISSUE THREAD

**Issue by cdiaz** [nestjs/nest#178]
Some errors types as invalid signature, jwt expired, no auth token, invalid token, invalid algorithm... are not being handled on [passport-jwt](https://github.com/themikenicholson/passport-jwt)

The default response send only 'unauthorized' message and http status 401

 [In this Issue](https://github.com/themikenicholson/passport-jwt/issues/84) the author recommend using [custom callbacks](http://passportjs.org/docs#custom-callback) according to official passport docs

I've tried to try the following code, but I can not get it to work fine

```javascript
export class AuthModule implements NestModule {
  public configure(consumer: MiddlewaresConsumer) {
    consumer
      .apply(passport.authenticate('jwt', { session: false }, (err, user, info) => {
        console.log(info.message)
      }))
      .forRoutes({ path: '/auth/authorized', method: RequestMethod.ALL });
  }
}
```
`console.log(info.message) ` Is printed but does not can exit function, and within it  next() function is not available, so response stays in the waiting forever

Any idea?

**Comment by kamilmysliwiec** [comment]
Hi @cdiaz,
Just use *class middleware*, not the functional one.

**Comment by cdiaz** [comment]
Hi @kamilmysliwiec, i'm using class middleware, but I can not access to the next() function inside passport   
This is my [Example](https://github.com/cdiaz/nest-passport/blob/master/src/modules/auth/auth.middleware.ts#L11)

**Comment by kamilmysliwiec** [comment]
Hi @cdiaz ,
Change:
```
 (err, user, info, next) =>
```
into:
```
 (err, user, info) =>
```

You're overriding `next` variable.

**Comment by adrien2p** [comment]
Hey !

If you try to wrap you return in a arrow function like that ?

return async (req: Request, res: Response, next: NextFunction) => {

**Comment by cdiaz** [comment]
```javascript
@Middleware()
export class JwtMiddleware implements NestMiddleware {
  public resolve(): (req, res, next) => void {
    return async (req: Request, res: Response, next: NextFunction) => {
      await passport.authenticate('jwt', { session: false }, (err, user, info) => {
        if(err){
          throw new HttpException(info.message, 401)
        }
        else{
          next()
        }
      })
    }
  }
}
```

**Comment by adrien2p** [comment]
Hi @cdiaz yes something like that, did you try ?

**Comment by cdiaz** [comment]
@adrien2p  Yes, I tried but Next() does not work within the passport context

**Comment by adrien2p** [comment]
Hey, could you try insteadof the third parameter something like 
Passeport.authenticate('jwt', {session: false})(req, res, next)
Then ensure you than the header contains 'Authorization JWT Jwt_token and let me noticed :)

See you

**Comment by cdiaz** [comment]
thanks @adrien2p , but I have already tried all this and I have not been able to solve it, @kamilmysliwiec  reopen the issue until there is a solution, please

**Comment by adrien2p** [comment]
```javascript
@Middleware()
export class JwtMiddleware implements NestMiddleware {
  public resolve(): (req, res, next) => void {
    return  passport.authenticate('jwt', { session: false })
  }
}
```

Could you execute that and send back the exception handled ?

**Comment by darioxtx** [comment]
hi,

you can access `next` like this.

```typescript
@Middleware()
export class LocalStrategyMiddleware implements NestMiddleware {
    resolve() {
        return async (req, res, next) => {
            return await passport.authenticate('local', {session: true}, (err, user, info) => {
                if (err) {
                    next(new HttpException(err, 401));
                }
                else {
                    next();
                }
            })(req, res, next)
        }
    }
}
```

**Comment by adrien2p** [comment]
Hey ! I've already propose this solution which apparently doesnt work ...

**Comment by darioxtx** [comment]
each example is missing some parts that's why its does not work.

**Comment by adrien2p** [comment]
Yes you right i didn't write the callback ;)

**Comment by kamilmysliwiec** [comment]
Hi @cdiaz,
Is the @darioxtx's example works for you :)?

**Comment by kamilmysliwiec** [comment]
Hi @cdiaz,
Let us know if you still have any issues 🙂

**Comment by cdiaz** [comment]
Yes,  thanks @kamilmysliwiec, @darioxtx this solution worked for me.
the [Middleware](https://github.com/cdiaz/nest-passport/blob/master/src/modules/auth/auth.middleware.ts) has been updated

**Comment by BorntraegerMarc** [comment]
@cdiaz Your example doesn't seem to work if I change this line: https://github.com/cdiaz/nest-passport/blob/master/src/auth/middlewares/login.middleware.ts#L8

from `{session: false}` to `{session: true}`

Am I missing something?

**Comment by mohamedHassanKa** [comment]
guys i am having the same probleme it says 
TypeError: next is not a function
 can you help me solve it
