### ISSUE TITLE
PLEASE ADD REACTJS SUPPORT - ANGULAR IS NOT JAVASCRIPT DEVELOPERS FAVOR

### ISSUE THREAD

**Issue by clRcoDE** [nestjs/nest#1792]
# I'm submitting a support request for ReactJS and VueJS

## Current behavior
no documentary for integrate nestjs with ReactJS and VueJS

## Expected behavior

to be front-end library "Independent"

## What is the motivation / use case for changing the behavior?

angular is losing its popularity 
many react developers , coding in typescript now!
and nestjs need to follow with the flow of javascript community

@kamilmysliwiec

**Comment by appsolutegeek** [comment]
I disagree.. It is an independent library, it doesn't require angular - but uses the practice and patterns of angular.

You integrate it with vuejs and reactjs - just like you would any other framework ... using Rest calls and returning static content.

**Comment by clRcoDE** [comment]
there is no clear documents about working nestjs with react or vue on the internet
none of react/express developers likes this type of supporting
@kamilmysliwiec is resisting about react ( probably because of their angular-community sponsors ) 
he removes any likeness in code between react and nestjs in every update
in the time that many frameworks from a lot of languages following react patterns
nestjs is on the opposite side of this flow
working with react-nestjs is like react-laravel these days

**Comment by marcus-sa** [comment]
So you want him to change the entire coding style based off your opinion on how it should be done?
There's a specific reason why it follows Angular patterns, because it is the right thing to do.
If you don't like the framework then simply don't use it?

**Comment by BrunnerLivio** [comment]
You can use NestJs alongside with React or Vue. In fact as far as I know a lot of startups / projects actually use a non-Angular but NestJs stack.

> in the time that many frameworks from a lot of languages following react patterns

We have many different inspirations of how we build our framework. Though I can’t think how we should inspire ourselves from React. It does not provide any services, strict architecture or whatsoever. It is more a library which is built solely for frontend development.

Can you give me a more particular concept what you are talking about?

**Comment by clRcoDE** [comment]
> So you want him to change the entire coding style based off your opinion on how it should be done?

this isnt my personal opinion ;)
world is moving towards react

> There's a specific reason why it follows Angular patterns, because it is the right thing to do.

can you explain why angular is the right thing to do but react is not? 

> If you don't like the framework then simply don't use it?

ok this will waste nestjs awesome potential to rise

>
> Angular isn't losing it's popularity, it's yet the most advanced front-end framework.

and most overwhelming
please look at charts and wake up  ;)


@kamilmysliwiec

**Comment by clRcoDE** [comment]
> You can use NestJs alongside with React or Vue. In fact as far as I know a lot of startups / projects actually use a non-Angular but NestJs stack.
> Can you give me a more particular concept what you are talking about?


1 - if we can use react and nestjs together why there isnt any article , support or documentary about using these technologies together ?

2 - okey nestjs archtecture is inspired by angular but why you inspired syntax by angular?
if nestjs syntax look like to react syntax more , react developers will migrate easily to nestjs


is now clear?

**Comment by juanjoseluisgarcia** [comment]
@clRcoDE you do not understand anything. It is a backend framework. If you want to access to it with ReactJS or Vue you will need to make an ajax call with libraries like fetch or axios like you would with node, Java, Ruby or any other backend framework. Your request simply does not make sense and exposes some deep lack of understanding of how basic things work. If you want plain vanilla ES6 just use node.

**Comment by nelsonBlack** [comment]
> > You can use NestJs alongside with React or Vue. In fact as far as I know a lot of startups / projects actually use a non-Angular but NestJs stack.
> > Can you give me a more particular concept what you are talking about?
> 
> 1 - if we can use react and nestjs together why there isnt any article , support or documentary about using these technologies together ?
> 
> 2 - okey nestjs archtecture is inspired by angular but why you inspired syntax by angular?
> if nestjs syntax look like to react syntax more , react developers will migrate easily to nestjs
> 
> is it clear now?
> @kamilmysliwiec
> @BrunnerLivio



> > You can use NestJs alongside with React or Vue. In fact as far as I know a lot of startups / projects actually use a non-Angular but NestJs stack.
> > Can you give me a more particular concept what you are talking about?
> 
> 1 - if we can use react and nestjs together why there isnt any article , support or documentary about using these technologies together ?
> 
> 2 - okey nestjs archtecture is inspired by angular but why you inspired syntax by angular?
> if nestjs syntax look like to react syntax more , react developers will migrate easily to nestjs
> 
> is it clear now?
> @kamilmysliwiec
> @BrunnerLivio

In a client- server(API) application, the programming pattern of the client not having to know how the server is implemented or not having to depend on server architecture is actually a good plus.
I have a nestjs GRAPHQL server back-end working with a flutter android app and angular client too .... The only thing the client needs to know is what data is required /endpoints - thus one can use the same backend for any other client side application vuejs/react /bootstrap/ etc

**Comment by appsolutegeek** [comment]
I suggest somebody closes this, its been asked and answered @kamilmysliwiec

I think there are other pressing feature requests/doc requests and real questions :-)

**Comment by clRcoDE** [comment]
6 month after this ridiculous issue and doing some couples of projects i think i was completely wrong here

@kamilmysliwiec deleting this issue would be a good idea :)

thanks
