### ISSUE TITLE
Custom messages from guards

### ISSUE THREAD

**Issue by nmabhinandan** [nestjs/nest#180]
I've a guard which returns false if the request doesn't have correct jwt token or has expired jwt token. But I'm not being able to send the message back to notify why the request is 403 forbidden. 

here's my code
``` typescript
@Guard()
export class AuthGuard implements CanActivate {

    canActivate(req: Request, context: ExecutionContext): Promise<boolean> {
        return new Promise<boolean>((resolve, reject) => {
            if (req.headers.authorization && req.headers.authorization.toString().split(' ')[0] === 'Bearer') {
                const token: string = req.headers.authorization.toString().split(' ')[1];
                Database.Connection.then((connection: Connection) => {
                    const decoded = jwt.verify(token, 'secret');

                    connection.getRepository(User).findOneById(decoded.data).then((user: User) => {
                        (req as any).user = user;
                        resolve(true);
                    });
                }).catch((err) => {
                    resolve(false);
                });
            } else {
                resolve(false);
            }
        });
    }
}
```

**Comment by adrien2p** [comment]
You could take a look at my repo's this is exactly the same problem and a use a middleware and a custom exception to handle and send back to the client

**Comment by kamilmysliwiec** [comment]
Hi @nmabhinandan,
It's easy. Instead of returning `false`, just throw a `HttpException`.

**Comment by kamilmysliwiec** [comment]
Also, it'd be easier to use async / await instead of `resolve()`

**Comment by nmabhinandan** [comment]
@kamilmysliwiec can canActivate be async?

**Comment by kamilmysliwiec** [comment]
@nmabhinandan of course! I see there's no example in the docs. Good point, maybe I should create one :slightly_smiling_face:
