### ISSUE TITLE
type-graphql generating error even without to use it

### ISSUE THREAD

**Issue by apiel** [nestjs/nest#1812]
I am planning to start to use type-graphql. So the first thing I did was `yarn add type-graphql` but as soon as I had the library my existing resolvers failed, even if I don't use type-graphql at all. The only thing I did was to add the library in the node_modules.

![image](https://user-images.githubusercontent.com/5873198/54817660-c2979f00-4c97-11e9-8c1f-3ad8568ccf18.png)

**Comment by kamilmysliwiec** [comment]
So basically the thing is that you cannot use both approaches at the same time. They are different from technical perspective and they produce different metadata. Once Nest detects that you have installed `type-graphql` in your project, it consequently "means" that you want to switch to the code-first way, and therefore Nest will automatically try to grab the metadata attached through the `type-graphql` decorators. Those decorators have some requirements though (like explicit type in your example) and lack of them lead to errors.
