### ISSUE TITLE
bug(storeRelatedModule): forwardRef can be undefined 

### ISSUE THREAD

**Issue by d3viant0ne** [nestjs/nest#183]
![screen shot 2017-10-09 at 11 42 03 pm](https://user-images.githubusercontent.com/8420490/31369647-7dd1b960-ad4b-11e7-89da-9876fc74e5e6.png)

> This is more an error handling issue than anything else. This should obviously create an error condition, imo it should just be handled a bit better.

In https://github.com/nestjs/nest/blob/master/src/core/scanner.ts#L115 `related` can be undefined which in turn throws. I ran into this issue originally when tinkering with server side HMR & HTTP2 push but there is a much less complex way to create this condition, simply typo a module import in `app.module.ts`

```
import { AppBootstrap } from './app.bootstrap';
import { AppComponent } from './app.component';
import { AppConfiguration } from './app.config';

import { SomeUndefModule } from './some/undefined.module';

import { } from ''
@Module({
  modules: [
    SharedModule,
    SomeUndefinedModule,
  ],
  controllers: [],
  components: [AppComponent, AppBootstrap, AppConfiguration],
  exports: [AppComponent, AppBootstrap, AppConfiguration],
})
```

**Comment by cojack** [comment]
@d3viant0ne title is misleading, it's not about `forwardRef` is undefined, but `related` is undefined. So if you can update it. Btw, how do you are able to transpile ts with typo?

**Comment by d3viant0ne** [comment]
@cojack Read the section on scope - https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by cojack** [comment]
@d3viant0ne but still, you're introducing the wrong variable, it's not about `forwardRef` but `related` is undefined, this is your words:

> In https://github.com/nestjs/nest/blob/master/src/core/scanner.ts#L115 related can be undefined which in 

And your topic: 

> forwardRef can be undefined

Does they're the same? </eot>
