### ISSUE TITLE
@nestjs/platform-express"' has no exported member 'UploadedFiles'

### ISSUE THREAD

**Issue by kunokdev** [nestjs/nest#1830]
[X] Regression 

## Current behavior
`UploadedFiles` are not exported from the package

> node_modules/@nestjs/platform-express"' has no exported member 'UploadedFiles'

## Expected behavior

Documentation says: 
> Both `FilesInterceptor()` and `@UploadedFiles()` decorator are exposed from `@nestjs/platform-express` package.

## Minimal reproduction of the problem with instructions

```
import { UploadedFiles, FilesInterceptor } from "@nestjs/platform-express";
```

## What is the motivation / use case for changing the behavior?
Behavior stopped working, documentation not in match

## Environment

Nest version: 6.0.2

**Comment by kamilmysliwiec** [comment]
Just updated the docs. Thanks for reporting!
