### ISSUE TITLE
bug?(core): Missing callModuleInitHook for NestMicroservice app

### ISSUE THREAD

**Issue by cojack** [nestjs/nest#187]
Hi,

When you create a microservice app, there is nothing like hooks for init where in nestapp their are.

It's for some purpose, the difference?

**Comment by kamilmysliwiec** [comment]
Hi @cojack,
Thanks, you're right. It will be fixed with the incoming update.

**Comment by kamilmysliwiec** [comment]
Hi, fixed in v4.1.7, thanks again 🙂
