### ISSUE TITLE
Refactor non nestjs/nest related integration/* tests to their repository

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#1874]
## I'm submitting a...

<pre><code>
[x] Refactor
</code></pre>

## Current behavior
At the moment some integration tests are present in the nestjs/nest repository which should get refactored in the repository the functionality it is coming from (e.g. typeorm, mongoose, typegraphql)

## Expected behavior
The tests should be executed if possible in a pipeline similar like [@nestjs/terminus](https://github.com/nestjs/terminus/blob/master/.travis.yml) runs the e2e tests 

## What is the motivation / use case for changing the behavior?
If a contributor sends a PR to the mentioned repositories, we do not know if it breaks unless the integration tests of nestjs/nest get executed manually. In my opinion, nestjs/nest does not need to check whether it integrates with other libraries. That responsibility belongs to the integration repositories themselves.

**Comment by kamilmysliwiec** [comment]
Yes and no. Ideally, we should also have integration tests in other repositories. However, we shouldn't remove those existing ones - they provide a quick way to check if the change doesn't break the whole ecosystem. Additionally, they check some other functionalities, like async providers, global modules etc.

**Comment by BrunnerLivio** [comment]
> way to check if the change doesn't break the whole ecosystem

Yes that is definitely convenient, but I think not an optimal solution. If the integrations would only use the public API of Nest, then I think we would only have to test against the public API of the nestjs/nest packages. But as of now some nestjs/* integrations use internal functionality, so therefore these tests make sense.

Or do I miss a point?

> async providers, global modules etc.

 I did not meant to refer to these kinds of tests, which test the integration of the nestjs/nest packages. These are absolutely fine :)

**Comment by kamilmysliwiec** [comment]
Just think about those tests as sample applications that make use of some libraries which in turn take advantage of Nest features (including async providers, global modules, etc. which are being used by typeorm, mongoose and so on). They are not being used to test those libraries specifically.

**Comment by kamilmysliwiec** [comment]
Let's track this in other repositories where those tests are actually missing (and will be added - hopefully - shortly)
