### ISSUE TITLE
Problem with Authentication chapter and the 19-auth sample

### ISSUE THREAD

**Issue by franken133** [nestjs/nest#1888]
I download the 19-auth sample and add some console.log debug code to it, then found some problems.
1. the code in JwtAuthGuard is never executed, below '2222222' was not print in the console.
canActivate(context: ExecutionContext) {
    console.log('22222222222');
    // add your custom authentication logic here
    // for example, call super.logIn(request) to establish a session.
    return super.canActivate(context);
  }

2.then I change the guard to JwtAuthGuard in the AuthController like below:
@Get('data')
  @UseGuards(JwtAuthGuard)
  findAll(@Req() req) {
    return req.user;
    // this route is restricted by AuthGuard
    // JWT strategy
  }

the code in JwtAuthGuard was invoked, but in the canActivate function, I can't get the user info from request. and the canActivate function was called before the JwtStrategy?

Can you explain the proceed sequence for the auth module? and how to get the user info in the JwtAuthGuard?

Thanks

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions.

**Comment by Bnaya** [comment]
I'm having a similar issue, and i have a feeling that this is might be a bug.
I've placed breakpoints and seems that the guard `canActivate` is called before the JWT authentication strategy (jwt passport in my case)

These are preliminary findings for me, i'm trying to understand more.

**Comment by Bnaya** [comment]
@kamilmysliwiec i've found that calling `super.canActivate(context);` before running the custom logic, populates req.user
And on the example, the comment is really confusing
https://github.com/nestjs/nest/blob/master/sample/19-auth/src/auth/guards/jwt-auth.guard.ts#L10-L14

is it a bug/by design?
I can make a pr to change the example if its an acceptable solution

**Comment by kamilmysliwiec** [comment]
> I've placed breakpoints and seems that the guard canActivate is called before the JWT authentication strategy (jwt passport in my case)

This is how it's supposed to work.

**Comment by Bnaya** [comment]
So the example is confusing, and the api as well.
I need to call `super.canActivate(context);` **for the side effect** and then run my own logic.
If there were any this.prepare(), that would have make more sense.
