### ISSUE TITLE
It can be nice to have access of the NestContainer instance of the application on the modules

### ISSUE THREAD

**Issue by erickponce** [nestjs/nest#189]
With application container access, you can build modules that have annotations...

I am building a NestJS module that works with Kue, so in the application controllers I can have something like this to define a Task:

```typescript
@Task({ name: 'justOneTest' })
justOneTest(done, task) {
    console.log('Received task:', task);
    setTimeout(done, 5000);
}
```

Then create a new job with:

```typescript
kueService.create(this.justOneTest);
```

**Comment by kamilmysliwiec** [comment]
Hi @erickponce,
What the `@Task` decorator is supposed to do?

**Comment by erickponce** [comment]
Hi @kamilmysliwiec thank you for your response,

The @Task decorator is the way to define one task code.

So rigth now I have the module contructor using a metadata explorer to search for tasks in the controllers, then I register that task in Kue (https://github.com/Automattic/kue):

```typescript
for (const { task, metadata } of this.metadataExplorer.explore(instance)) {
    KueService.registerTask(task, metadata, instance);
}
```
I'm just using the **container** to get the application modules (don't know if there is a better way to do this)

```typescript
const modules = container.getModules();
modules.forEach(({ routes, components }) => {
    this.bindTasks(routes);
    this.bindTasks(components);
});
``` 

To demonstrate better,

```typescript
@Task({
        name: 'justOneTest',
        concurrency: 3,
        queue: 'test',
        attempts: 3,
        ttl: 3000,
        backoff: { delay: 5 * 1000, type: 'fixed' }
})
async justOneTest(job: Job, done: DoneCallback) {
    done(null, 'Task completed!');
}
``` 

To fire that task you can do:

```typescript
@Get('task')
createJob(@Res() res) {
    const job = this.kueService.createJob(this.justOneTest, { a: 'b' }).save();
    job.on('complete', (result) => res.send(result));
    job.on('failed', (err) => res.status(HttpStatus.INTERNAL_SERVER_ERROR).send(err));
}
``` 

Obervation about Kue: It is a priority job queue backed by redis, built for node.js.

**Comment by kamilmysliwiec** [comment]
So just to summarize, the only thing which you wanna achieve is to create tasks in more declarative-way - using decorators with "task metadata", right?

**Comment by erickponce** [comment]
Yes that's correct.

**Comment by kamilmysliwiec** [comment]
I'm thinking about the right solution now. The most plausible scenario is that I'll provide a function to grab a `NestContainer` from the instance for the more advanced users.

**Comment by erickponce** [comment]
Yes, I like the approach of provide a function to grab the `NestContainer`.

**Comment by mkzaker** [comment]
+1

**Comment by kamilmysliwiec** [comment]
Soo I was thinking about this change and I realized that it's needless in fact. Since we have an access to the `ModuleRef`, it's possible to do the exact same thing as with the `NestContainer`. Take a look how this has been achieved inside *CQRS* module - https://github.com/nestjs/cqrs 🙂

**Comment by erickponce** [comment]
I changed the implementation to use `ModuleRef` accordingly to CQRS and it works perfectly.

Thank you @kamilmysliwiec :slightly_smiling_face:

**Comment by kamilmysliwiec** [comment]
Awesome 🙂

**Comment by shekohex** [comment]
That will be awesome when you can make tasks to run later on your application like send emails , delete old users , clearing cache .. etc

**Comment by cdiaz** [comment]
Hi @erickponce,  you can release an example of your code? it would be very useful.

**Comment by erickponce** [comment]
I have shared the code on https://github.com/erickponce/nestjs-kue feel free to use it.

Note that this is not tested on production environments, and there are improvments to be made =)

**Comment by whtiehack** [comment]
@erickponce  thx for share.

**Comment by Diluka** [comment]
How can I access container here?
```ts
export function f(){
    // How to access container here?
}
```
