### ISSUE TITLE
Route :params not working in @Controller() and .setGlobalPrefix()

### ISSUE THREAD

**Issue by plunntic** [nestjs/nest#190]
Sadly, this is not working:

```ts
@Controller('some/:id')
export class CategoriesController {

    @Post()
    create(@Param('id') id: string)
    {
        console.log(id); // gives undefined
    }

}
```

It seems like the issue comes from express itself (params from prefixes are not populated in `request.params` either). The same story with `.setGlobalPrefix('some/:id')`.

That's quite a big problem for me - i'm writing a multi-tenant api and just wanted to include tenand id as part of the resource location - but this way i'd have to copy the prefix into all `@Get()`, `@Post()` and so on decorators through the whole project.

As this looks like express-dependent and probably is a wont-fix maybe there is some workaround i'm not aware of?

Using typescript & @nestjs/common-4.1.1 @nestjs/core-4.1.3

**Comment by adrien2p** [comment]
I'm not sure that a global prefix like that on your controller is necessary, you should may be try @Controller('some') and then @Post(':id') instead.

**Comment by kamilmysliwiec** [comment]
Hi @plunntic,
The nest is using the express **router** concept, that's why all of the prefixes are not working. Each controller is, in fact, an express router instance. Unfortunately, I don't know any workaround 🙁

**Comment by joshua-fogg** [comment]
This feature would be super helpful. I am working with large data sets upto 40mb in json size and need to break these down into smaller segments and categories. Currently I'm having to repeat an ID parameter for every child of my controller as below:

`
@Controller('ui-config')
export class UiConfigController {
 10-20x @Get(':id/someExtension')
}
`

**Comment by kamilmysliwiec** [comment]
@joshua-fogg actually, it should work fine already 🙂
