### ISSUE TITLE
Changing from Express to the Fastify does not allow to create the instance of the NestApplication

### ISSUE THREAD

**Issue by nbaua** [nestjs/nest#1906]
## Current behavior
When changing from Express to the Fastify, the bootstrapping method does not allow to create the instance of the NestApplication.

## Expected behavior
As per the documentation the following version of the **create** method should work seamlessly.

	`const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());`

## Minimal reproduction of the problem with instructions
I am using the 
    "@nestjs/platform-fastify": "^6.0.5",

With following code in the main.ts file.

`
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
	const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
	await app.listen(3000);
}
bootstrap();
`
Straight from the NestJS documentation.
However It does not compile with or without the create method flavors

create<NestFastifyApplication>(.....) does not work
create(...) gives the Error: Cannot find module '@nestjs/core/adapters/http-adapter'

## Environment

Nest version: 6.0.5

 
For Tooling issues:
- Node version:  v10.15.0
- Platform:   Windows

Others:

Please check the  screen-shot

![err](https://user-images.githubusercontent.com/17998763/55326231-e2537200-54a4-11e9-9a74-e4fcbb62cf3c.png)

**Comment by kamilmysliwiec** [comment]
It seems that your `@nestjs/core` package is outdated. Please, update to 6.0.5
