### ISSUE TITLE
Docs: add custom provider to samples

### ISSUE THREAD

**Issue by mchelen** [nestjs/nest#1907]
## I'm submitting a...

<pre><code>

[ X] Documentation issue or request
</code></pre>

## Current behavior

There are some nice examples for using custom providers at https://docs.nestjs.com/fundamentals/custom-providers

However, those examples don't seem to be covered too much in https://github.com/nestjs/nest/tree/master/sample

It's harder to understand the docs without full sample code (what does `OptionsProvider` look like?)

## Expected behavior

It would be nice to have full working samples of the code described in https://docs.nestjs.com/fundamentals/custom-providers - maybe as a sample app using a config class?

**Comment by ejhayes** [comment]
FWIW this looked like a good blog article showing how this worked (using NestJS v5, but looks like it is still relevant): https://www.codementor.io/foysalit/rest-api-with-mongodb-and-nest-js-hto6x5120

**Comment by kamilmysliwiec** [comment]
Sample https://github.com/nestjs/nest/tree/master/sample/25-dynamic-modules
