### ISSUE TITLE
How can you mock external dependencies?

### ISSUE THREAD

**Issue by mslourens** [nestjs/nest#191]
I am trying to test a logger-service, which uses imports from the node_modules `winston` and `fs`, and I would like to mock these imports, but I don't know how. With nest it's really easy to mock the injected dependencies, but these dependencies are imported, not injected. For normal Node.js modules I use [proxyquire](https://github.com/thlorenz/proxyquire) to proxy my required node_modules, but that's not possible with Nest, because the dependencies are imported, not required, and they are imported very early in the process (before the constructor of the service is called). 

Here is my logger-service:
```typescript
import {Component} from '@nestjs/common';
import {Logger, transports} from 'winston';
import * as path from 'path';
import * as fs from 'fs';

import { ConfigService } from '../config/config.service';

require('winston-daily-rotate-file');

@Component()
export class LoggerService {
    logger:any;
    logFolders:any;

    constructor(private config:ConfigService) {
        this.logFolders = {base: path.join(__dirname, '..', '..', '..', 'logs')};
        this.logFolders.debug = path.join(this.logFolders.base, 'debug');
        this.logFolders.exception = path.join(this.logFolders.base, 'debug');

        this._createLogFolders();

        this.logger = new Logger({
            transports: [
                new transports.Console({
                    json: false,
                    timestamp: true,
                    level: config.get('debug') ? 'debug' : 'info'
                }),
                new transports.DailyRotateFile({
                    filename: path.join(this.logFolders.debug, 'debug.log'),
                    json: false,
                    level: 'error',
                    datePattern: 'yyyy-MM-dd-',
                    prepend: true
                })
            ],
            exceptionHandlers: [
                new transports.Console({
                    json: false,
                    timestamp: true,
                    level: config.get('debug') ? 'debug' : 'info'
                }),
                new transports.DailyRotateFile({
                    filename: path.join(this.logFolders.exception, 'execeptions.log'),
                    json: false,
                    level: 'error',
                    datePattern: 'yyyy-MM-dd-',
                    prepend: true
                })
            ],
            exitOnError: false
        });
    }

    private _createLogFolders() {
        const createDir = dir => {
            if (!fs.existsSync(dir)) {
                fs.mkdirSync(dir);
            }
        };

        createDir(this.logFolders.base);
        createDir(this.logFolders.debug);
        createDir(this.logFolders.exception);
    }

    debug(message:string) {
        this.logger.debug(message);
    }

    info(message:string) {
        this.logger.info(message);
    }

    warn(message:string) {
        this.logger.warn(message);
    }

    error(message:string) {
        this.logger.error(message);
    }
}
```

And this is my test:
```typescript
import {Test} from '@nestjs/testing';
import {TestingModule} from '@nestjs/testing/testing-module';
import {LoggerService, ConfigService} from '../';
import {expect} from 'chai';
import * as sinon from 'sinon';

describe ('LoggerService', () => {
    let module: TestingModule;
    let service: LoggerService;
    let sandbox;
    let logStub;

    beforeEach(async () => {
        sandbox = sinon.sandbox.create();

        module = await Test.createTestingModule({
            components: [
                LoggerService,
                ConfigService
            ]
        }).compile();

        service = module.get(LoggerService);
    });

    it('should exist', () => {
        expect(service).to.exist;
    });

    it('should log a debug message', () => {
         logStub = sandbox.stub(service.logger, 'debug');
         service.debug('someMessage');
         expect(logStub).to.have.been.calledWith('someMessage');
    });

    it('should log a info message', () => {
        logStub = sandbox.stub(service.logger, 'info');
        service.info('someMessage');
        expect(logStub).to.have.been.calledWith('someMessage');
    });

    it('should log a debug message', () => {
        logStub = sandbox.stub(service.logger, 'warn');
        service.warn('someMessage');
        expect(logStub).to.have.been.calledWith('someMessage');
    });

    it('should log a debug message', () => {
        logStub = sandbox.stub(service.logger, 'error');
        service.error('someMessage');
        expect(logStub).to.have.been.calledWith('someMessage');
    });

});
```

I am not able to mock winston or fs, so I cannot test the constructor or prevent the creation of the logFolders.

Can anyone help me to mock imports?

**Comment by adrien2p** [comment]
Hey !
You could maybe use `https://github.com/boblauer/mock-require/blob/master/README.md`
Which work like this `mock = require('mock-require')`
And then `mcok('pathDependency', { mockMethod: expectedBehavior });`

**Comment by mslourens** [comment]
I already tried mock-require, as well as [rewiremock](https://www.npmjs.com/package/rewiremock), but the file is loaded at the very beginning of the test, probably because I export all providers in a index.ts, and when a test imports on of those exports, all exports of the index.ts are loaded, including my logger-service, and the mock won't work anymore.

**Comment by unlight** [comment]
You are not following IoC
You must create injectable component  from logger package and inject to constructor.
```
{
  provide: 'Logger',
  useFactory: () => require('winston')
};
```
constructor(
    private config:ConfigService,
   @Inject('Logger) private logger,
) {}
```

**Comment by adrien2p** [comment]
@unlight yes tou right, sorry i didn't check the details of the code my bad ^^

**Comment by mslourens** [comment]
@unlight thanx! That's exactly what I needed.

**Comment by kamilmysliwiec** [comment]
Cool :) @unlight great answer!

**Comment by BrunnerLivio** [comment]
Currently facing the same problem and came up with the solution like @unlight. 
Now the problem I have is, the third-party dependencies do not have any type definitions when using inside  of a service, controller, etc. 

I tried:
```TypeScript
import * as Fs from 'fs';

export class AppController {
  constructor(
   // TSError: Cannot use namespace 'Fs' as a type.
    @Inject('Fs')
    private Fs: Fs
  )
}
```

Anyone found a solution for this?

**Comment by mslourens** [comment]
I think fs is part of the @types/node package. For other packages without
type definitions you can just create your own.

On May 17, 2018 at 1:02 PM, <Livio Brunner <notifications@github.com>>
wrote:

Currently facing the same problem and came up with the solution like
@unlight <https://github.com/unlight>.
Now the problem I have is, the third-party dependencies do not have any
type definitions when using inside of a service, controller, etc.

I tried:

import * as Fs from 'fs';
export class AppController {
  constructor(
   // TSError: Cannot use namespace 'Fs' as a type.    @Inject('Fs')
    private Fs: Fs
  )
}

Anyone found a solution for this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nestjs/nest/issues/191#issuecomment-389828780>, or mute
the thread

**Comment by BrunnerLivio** [comment]
Thanks for the quick anwser @mslourens.
I am aware of that. But how do you actually explain TypeScript to use the Fs-Typings of `@types/node` for my variable? 

You cant just use `import { fs } from '@types/node'` and then add the type to the variable off course. 

I hope you understand what I mean.

**Comment by mslourens** [comment]
Ah, I see what you mean. You can still type FS, but probably not the whole module at once. Say if you just want to use the fstat function of the fs module, you have to inject it separately and then type it as fstat, like this:
```js
import { fstat } from 'fs';

export class AppController {
  constructor(
   // TSError: Cannot use namespace 'Fs' as a type.
    @Inject('stat')
    private stat: fstat
  )
}
```
Your AppModule will look like this:
```js
@Module({
  components: [
    { provide: 'stat', useFactory: () => require('fs').fstat },
  ]
})
export class AppModule {
}
````
The downside of this way of injecting is that you have a lot of dependencies to inject in your controller. That's why I choose to just forget the type.

**Comment by BrunnerLivio** [comment]
Thanks for the anwser. That solution would fix my issue, but as you mentioned this is not really convenient. I prefer having no types, rather than creating a wrapper for every function and injecting it, like you do.

Guess there is no better solution at the moment.

**Comment by unlight** [comment]
Sorry, [This answer](https://github.com/nestjs/nest/issues/191#issuecomment-390176721) was for @BrunnerLivio

**Comment by BrunnerLivio** [comment]
@unlight
Oh thats awesome, did not know that!
Thanks alot!
