### ISSUE TITLE
express ErrorRequestHandler not fired

### ISSUE THREAD

**Issue by arkraft** [nestjs/nest#192]
Adding a error handler on the express instance itself has no effect, it never gets fired. I belive this is due to the ExceptionFilters which capture all the errors. Not captured errors are handled within the [ExceptionsHandler](https://github.com/nestjs/nest/blob/master/src/core/exceptions/exceptions-handler.ts#L12) class and never leave it. 

This is a problem for me right now because i wanted to integrate [Sentry](https://docs.sentry.io/clients/node/integrations/express/) which would need me to append an ErrorRequestHandler to the express instance. A ExceptionFilter doew not work here as it has no `request` but just the `response`. 

A NestMiddleware would also not work as there is no error object given.

**Comment by kamilmysliwiec** [comment]
Hi @arkraft,
Interceptors have an access to the `request` object and using `.catch` operator, they can handle any thrown exceptions. Maybe you can try with them?

**Comment by arkraft** [comment]
Thank you for the answer, i will try that.

**Comment by arkraft** [comment]
It did not work with catch. But i found out that the `request` is added to the `response`object. So i can use filters. And inside the filter i can use the exceptionaHandler from `raven`. Thank you for your help.

**Comment by colinmorelli** [comment]
Out of curiosity - is there any reason to not provide thee request on the exception handlers? The workaround to access `response.req` works but feels like a hack at best (it's also not typed on the interface so it's either ugly or requires additional typings)`.

I have a case in which I'd like to adjust the response body depending on whether the request was a XHR vs a browser request (as determined by a header).
