### ISSUE TITLE
Can't resolve 'cache-manager'

### ISSUE THREAD

**Issue by NikolaiGarkusha** [nestjs/nest#1927]
## I'm submitting a...

<pre><code>
[x] Bug report
</code></pre>

## Current behavior

I develop an app with angular and nest in one repo. 

## Expected behavior

LocalStorageService on client side should check is current platform is browser, and add/set/remove items in browser LocalStorage

## Minimal reproduction of the problem with instructions

When I created on client side LocalStorageService and  <code>@Inject(PLATFORM_ID) private readonly platformId: Object</code>, I had an error 
<pre><code>
ERROR in ./node_modules/@nestjs/common/cache/cache.providers.js
Module not found: Error: Can't resolve 'cache-manager' in '/project/node_modules/@nestjs/common/cache'
</code></pre>

After that I installed `cache-manager` and import it in nest AppModule.
But now I have a warning
`WARNING in ./node_modules/@nestjs/common/utils/load-package.util.js 8:39-59
Critical dependency: the request of a dependency is an expression` 

## Environment

<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: 11.13.0
- Platform:  Ubuntu 18.04.2 LTS

Others:

- Angular version: 7.2.0
- nestjs/ng-universal: 0.4.2
</code></pre>
,Thanks

**Comment by kamilmysliwiec** [comment]
Take a look here https://github.com/nestjs/nest/issues/1706
