### ISSUE TITLE
ModulesContainer, InstanceWrapper Documentation 

### ISSUE THREAD

**Issue by 5up3rD4n1** [nestjs/nest#1965]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I'm working in a really modularized project, in which, we need configuration to be dynamic and scoped for some modules. So there is a library that is going to be use by multple nest applications. We are using the power of the custom providers with `forRoot` method to factory the configuration for an entire app, but in the same application we want the hability fetch the configuration and scoped as need for each module in the application.

I tried to create my own decorator and wrapping the `@Inject` funtionallity to mix it with mine, and then hack the ModulesContainer like [nest/cqrs](https://github.com/nestjs/cqrs) library does, getting the instance and overriding the configuration instance with a new instance using the custom decoration meta that I injected to scope it.

## Expected behavior

I'm not sure about the expected behavior, but I was thinking something like:

- Let `@Inject` provide parameters to the instance that is going to be injected. (I know this can break some design paterns, since someone will have the hability to inject complex objects into the `Injectable`'s constructor params.
- When using `forRoot` dynamic provider, let the `useFactory` receive parameters so it can be considered when returning the instance. In this case `useFactory` can also receive custom params for each instance that is going to generate. (Maybe this is not the way it works so correct me if I'm totally wrong).

## Minimal reproduction of the problem with instructions

**Library code**
```js
// decorator
export function Configurable(scope: string) {
  return (target: object, key: string | symbol, index?: number) => {
    const meta = Reflect.getMetadata(CONFIGURABLE_METADATA, target) || {};
    let dependencies = meta.dependencies || [];

    dependencies = [...dependencies, { scope, key }];

    Reflect.defineMetadata(
      CONFIGURABLE_METADATA,
      { dependencies },
      target,
    );

    Inject(CONFIGURATION_PROVIDER_TOKEN)(target, key, index);
  };
}
```

```js
// explorer service
@Injectable()
export class ExplorerService {
  constructor(private readonly modulesContainer: ModulesContainer) {}

  injectScopes(): void {
    const providers = [...this.modulesContainer.values()]
      .map((module: NestModule) => {
        return [...module.providers.values()];
      }).reduce((a, b) => a.concat(b), []);

    providers.forEach(provider => {
      const { instance } = provider;

      if (!instance && !instance.constructor) {
        return;
      }

      // custom metadata
      const meta = Reflect.getMetadata(CONFIGURABLE_METADATA, instance.constructor);

      if (meta) {
        meta.dependencies.forEach(dep => {
          const { index, scope } = dep;
          const wrapper = provider[INSTANCE_METADATA_SYMBOL].dependencies[index];
          const { instance: depInstance } = wrapper;
          Object.defineProperty(depInstance, 'scope', { value: scope });
        });
      }
    });
  }
}
```
**Application code (using the library)**
```js
// usage in the application
@Module({
  imports: [ConfigurationModule.forRoot(factoryOptions)],
  providers: [UserConfigProvider],
  exports: [ConfigurationModule]
})
export class AppModule {}
```

```js
// user config provider
@Injectable()
export class AssessmentConfiguration {
  constructor(
    @Configurable('common')
    private readonly commonConfig: ConfigurationService,
    @Configurable('users')
    private readonly usersConfig: ConfigurationService,
  ) {}
}
```

## What is the motivation / use case for changing the behavior?

Allow dynamic modules to generate custom instances or to create instances with injected customized params.

There is no documentation on how to use the `ContainersModule` or the `InstanceWrapper`. I was trying to follow the code but its hard for me to get the flow and how to hack it to inject the dependencies before the instance is created. I was thinking that maybe I can redefine the `InstanceWrapper` dependencies and then from the desired wrapper I can trigger the method that generate the instances again with the new dependencies. But that is advanced stuff I guess.

Also I can't provide scopes into providers because I can't hard code provider tokens into the library code and it can be as many scopes a I want to, so I think there is no way to do it dynamically, with the current tools nest is providing.

## Environment
<pre><code>
Nest version: 6.0.5

For Tooling issues:
- Node version: v10.14.2  
- Platform: Linux  
</code></pre>

**Comment by kamilmysliwiec** [comment]
> There is no documentation on how to use the ContainersModule or the InstanceWrapper. I was trying to follow the code but its hard for me to get the flow and how to hack it to inject the dependencies before the instance is created. I was thinking that maybe I can redefine the InstanceWrapper dependencies and then from the desired wrapper I can trigger the method that generate the instances again with the new dependencies. But that is advanced stuff I guess.

Well, I don't think that you really need this internal API stuff.

```typescript
@Configurable('common')
```

What about:

```typescript
export const Configurable = (key: string) => Inject(`${key.toUpperCase()}_CONFIG`);
```

then just register a custom provider within a module:

```typescript
{
   provide: 'COMMON_CONFIG',
   useX(factory/value/class whatever you need)
}
```

For this, you can create the `ConfigurationModule.forFeature()` static method. And this is how you can have "scoped configuration" per module.

**Comment by 5up3rD4n1** [comment]
I didn't know about the `forFeature` method, sounds like an option. So, there is no way to do it without defining a provider in each module? I'm concerned that we might need many possible scopes. Hence, module definitions can get really extensive defining all scoped configurations, the idea was to have something more dynamic and with just an annotation on the fly provide a new different "scoped configuration".

Let me know if there is something else I can do to achieve it.

Thanks @kamilmysliwiec for your answer!

**Comment by kamilmysliwiec** [comment]
> module definitions can get really extensive defining all scoped configurations

Module has to define a scoped configuration which will be available for its providers. If you want to share those configurations among modules, you can create another module.

> the idea was to have something more dynamic and with just an annotation on the fly provide a new different "scoped configuration".

It still is dynamic but moves the responsibility to a parent module instead of a class itself (which should be considered as a best practice in Nest).

**Comment by 5up3rD4n1** [comment]
I was looking a way where there is no need to explicitly define the scoped providers in a module or a parent module, but I get and respect that Nest does things different. 

This conversation gave me some new ideas on how to implement it.

Thanks again!
