### ISSUE TITLE
Suggestion: rename to @nest/*

### ISSUE THREAD

**Issue by wbhob** [nestjs/nest#197]
The NPM org @nest has 0 things inside, so you can likely petition NPM to give you the name. That would be a good change for v5.

**Comment by kamilmysliwiec** [comment]
Hi @wbhob,
I don't think it's necessary. The GitHub organization, page & docs domain is also known as *nestjs*.

**Comment by wbhob** [comment]
Good point, but just to follow the Angular style, everything is imported from @angular/*, and it makes syntax clearer and shorter.

**Comment by kamilmysliwiec** [comment]
Hi @wbhob,
The angular's using `@angular` prefix only because they wanted to emphasize the difference between old AngularJS and the new one (Angular without JS suffix). We don't have a similar problem - nest = nestjs. 🙂

**Comment by wbhob** [comment]
Hmm... I suppose it is a matter of preference.

**Comment by MonsieurMan** [comment]
Yes, this is definitely not critical. Maybe to keep in mind for a major
milestone. 😉

Le dim. 29 oct. 2017 à 3:00 PM, Wilson Hobbs <notifications@github.com> a
écrit :
