### ISSUE TITLE
Unable to connect to microcervice

### ISSUE THREAD

**Issue by darioxtx** [nestjs/nest#203]
Hi @kamilmysliwiec , 

As a test I used your microservice example, and it worked (everything is same app). Then i tried to use `ClientProxy` on my nest app, and call that running microservice, but I don't any get results the request just stuck.

What I'm going wrong?

**Comment by kamilmysliwiec** [comment]
Hi @darioxtx,

Could you share your code/repo? 🙂 I need more context here.

**Comment by darioxtx** [comment]
I did small example and all connections started to work. seems like I did mistake in ports configuration. 
Also I notice that using `Transport.REDIS` does not throw any exception to client if microservice is down.

**Comment by kamilmysliwiec** [comment]
Awesome. About Redis, that's how it works. Since microservices are based on rxjs, you can use a `timeout()` operator. 🙂

**Comment by Oskang09** [comment]
@kamilmysliwiec how u fixed it? sorry for disturbing. i'm new to redis , i build microservice via redis too but if the microservice not up , and call to the microservice won't throw any expcetion and stuck there even timeout has been applied.

Code : https://pastebin.com/L31NkGi7

**Comment by Oskang09** [comment]
I don't know isit a good way or not. but it work rather then pipe(timeout()).
```
import { Injectable, NestInterceptor, ExecutionContext } from '@nestjs/common';
import { Observable } from 'rxjs';

@Injectable()
export class TimeoutInterceptor implements NestInterceptor
{
    TimeoutAction: (req: any, res: any) => any;
    TimeoutSecond: number;

    constructor(timeoutAction: (req: any, res: any) => any, timeoutSecond: number) {
        this.TimeoutAction = timeoutAction;
        this.TimeoutSecond = timeoutSecond;
    }

    intercept(
        context: ExecutionContext,
        call$: Observable<any>,
    ): Observable<any>
    {
        setTimeout(() => {
            this.TimeoutAction(context.getArgByIndex(0), context.getArgByIndex(1));
        }, this.TimeoutSecond);

        return call$.pipe();
    }
}
```

**Comment by Riley19280** [comment]
I am using the native timeout method from rxjs to forward timeout errors to my global error handler.
`import { Injectable, NestInterceptor, ExecutionContext, HttpException, HttpStatus, Logger } from '@nestjs/common';
import { Observable, TimeoutError, throwError } from 'rxjs';
import { timeout, catchError} from 'rxjs/operators';

@Injectable()
export class TimeoutInterceptor implements NestInterceptor {
  intercept(
      context: ExecutionContext,
      call$: Observable<any>,
  ): Observable<any> {
    return call$.pipe(
        timeout(2500),
        catchError(error => {
          if (error instanceof TimeoutError) {
            return throwError(new HttpException('Request timed out.', HttpStatus.SERVICE_UNAVAILABLE));
          } else {
            Logger.log('Unknown error:' + JSON.stringify(error), 'TimeoutInterceptor');
            return throwError(new HttpException('Internal Server Error', HttpStatus.INTERNAL_SERVER_ERROR));
          }
        }),
    );
  }
}`
