### ISSUE TITLE
How to integrate the context into a pipe?

### ISSUE THREAD

**Issue by yostools** [nestjs/nest#2032]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The context cannot be integrated into a pipe.

## Expected behavior
The context should be integrated into the pipe via @Inject.

## Minimal reproduction of the problem with instructions
I want to use a pipe to change the transferred data according to the current user. How do I integrate the context into a pipe?

To create the basic structure, I followed the instructions in the [documentation](https://docs.nestjs.com/pipes):
```typescript
import { ArgumentMetadata, Injectable, PipeTransform } from '@nestjs/common';

@Injectable()
export class CheckPipe implements PipeTransform<any> {

  /**
   * Check input
   */
  async transform(value: any, { metatype }: ArgumentMetadata) {

    // Return value if it is only a basic type (without decorator)
    if (!metatype || this.isBasicType(metatype)) {
      return value;
    }

    // Get context
    const context = ???;

    // Restrict value for current user
    if (!context.currentUser.roles.includes('admin')) {
      delete value.id
    }

    // Return value
    return value;
  }

  /**
   * Checks if it is a basic type
   */
  private isBasicType(metatype: any): boolean {
    const types = [String, Boolean, Number, Array, Object];
    return types.includes(metatype);
  }
}
```

I've tried to integrate context via Injection:
```typescript
@Injectable({ scope: Scope.REQUEST })
export class CheckPipe implements PipeTransform<any> {

  /**
   * Constructor to inject context
   */
  constructor(@Inject(CONTEXT) private readonly context) {}

  ...
}
```
And integrated the pipe into the module:
```typescript
@Module({
  providers: [
    {
      provide: APP_PIPE,
      useClass: CheckPipe,
    },
  ],
})
```
But `this.context` in the `transform` method is undefined.

I am using the pipe in a GraphQL resolver:

```typescript
@Resolver(of => User)
export class UserResolver {
 
  ...

  /**
   * Create new user
   */
  @Mutation(returns => User, { description: 'Create a new user' })
  async createUser(@Args('input') input: UserCreateInput): Promise<User> {
    return await this.usersService.create(input);
  }

  ...
}
```

## What is the motivation/use case for changing the behavior?
I want to use a pipe to change the input data according to the current user. 

## Environment

<pre><code>
Nest version: 6.1.1
 
For Tooling issues:
- Node version: 11.11.0
- Platform:  Mac
</code></pre>

**Comment by nartc** [comment]
Can you provide a repo to reproduce?

**Comment by yostools** [comment]
@nartc under the following link I have provided a repository in which the problem occurs: [https://github.com/yostools/nest-example](https://github.com/yostools/nest-example)

If you run `npm run test:e2e` you can see that during the tests a console.log was executed with the context in the pipe (`src/common/pipes/check.pipe.ts:24`), which is unfortunately undefined:

```
console.log src/common/pipes/check.pipe.ts:24
    Current context undefined
```

**Comment by zinzinday** [comment]
I have some issues.
I think, NestJS not supported @Inject and scopes on provide APP_PIPE.
i have test @Inject with other provede token and custom provide token.
 But all return `undefined`

**Comment by yostools** [comment]
Does anyone have a clue for me as to whether this is possible or will soon be possible?

**Comment by kamilmysliwiec** [comment]
It seems that it's the same issue as here https://github.com/nestjs/nest/issues/1916
let's track this in a one place
