### ISSUE TITLE
it would be nice to set moduleRef.find and findInstanceByPrototypeOrToken be public methods

### ISSUE THREAD

**Issue by minzojian** [nestjs/nest#2036]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
i have some components but with same name, which has been placed under different folders
```
---app.module  
---moduleA  
     ---test.service.js  
---moduleB  
     ---test.service.js  
```
in this case, call ``this.moduleRef.get("moduleB")`` in moduleA will get nothing, cause moduleRef is looking for componets in current module(moduleA) context. and will get nothing if i didn't import moduleB into moduleA

then i found ``moduleRef.find`` method,which can look for component from a ``flatContainer`` however, if i have components with same name but in different folder, i will not able get the correct component only by ``moduleRef.find``   
then i found another method ``findInstanceByPrototypeOrToken``,which can achieve my purpose,
so finally,i write down  a custome provide like this
```
import {Module} from '@nestjs/common';
import {UnknownModuleException} from '@nestjs/core/errors/exceptions/unknown-module.exception'
import {AppController} from './app.controller';
import {AppService} from './app.service';

const findComponent = {
  provide: "findComponent",
  useValue: function (componentMetatypeOrToken, moduleMetaTypeOrToken) {
    const moduleName = typeof moduleMetaTypeOrToken == "function"
      ? moduleMetaTypeOrToken.name
      : moduleMetaTypeOrToken;
    var module = [...this.moduleRef.container.getModules().values()].find((m) => {
      return m.metatype.name == moduleName
    })
    if (module) {
      return this.moduleRef["findInstanceByPrototypeOrToken"](componentMetatypeOrToken, module);
    }
    throw new UnknownModuleException();
  }
}

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService, findComponent],
})
export class AppModule {}

```
and use this function in child service of moduleA like this
```
import {Injectable, Inject} from '@nestjs/common';
import {ModuleRef} from '@nestjs/core';

@Injectable()
export class TestService {
    findComponent;
    constructor(
        private readonly moduleRef: ModuleRef,
    ) {
        this.findComponent = this.moduleRef["find"]("findComponent");
    }
    test() {
        let testService2 = this.findComponent("TestService", "ModuleB")
        return  testService2.test();
    }
}
```

## Expected behavior

you can notice that  i call ``find`` and ``findInstanceByPrototypeOrToken`` by ``moduleRef["find"]``, cause this 2 methods are protected methods. maybe modify the ``createModuleRefMetatype`` funtion in ``module.js``, and move ``find`` and ``findInstanceByPrototypeOrToken`` method out would be nice

## Environment

<pre><code>
Nest version: latest

For Tooling issues:
- Node version: 10.14.2
- Platform:  Windows 

</code></pre>

**Comment by kamilmysliwiec** [comment]
> in this case, call this.moduleRef.get("moduleB") in moduleA will get nothing, cause moduleRef is looking for componets in current module(moduleA) context. and will get nothing if i didn't import moduleB into moduleA

Use `moduleRef.get('moduleB', { strict: false })` instead.
