### ISSUE TITLE
Question: How can I overwrite the default 404 response when route doesn't exist

### ISSUE THREAD

**Issue by jpinkster** [nestjs/nest#204]
How do we go about overwriting the default express response for when there is no route defined? Before I was able to define all my routes and then have a catch all statement like this:

```
app.all('/api/*', (req: express.Request, res: express.Response, next: Function): void => {
        ErrorHandler.run(new APINotFoundError(), req, res, next);
});
```

**Comment by kamilmysliwiec** [comment]
Hi @jpinkster,
The nest provides `@All` decorator (inside `@nestjs/common` package), also you can easily use wildcards, for example `@All('api/*')` 🙂
