### ISSUE TITLE
TypeORM migrations

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#205]
Hi,
Is there a way to run migrations with defining the connection as described in the docs?
```
export const databaseProviders = [
  {
    provide: DB_CON_TOKEN,
    useFactory: async () => await createConnection({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      username: 'root',
      password: 'root',
      database: 'test',
      entities: [
        __dirname + '/../**/*.entity{.ts,.js}',
      ],
      migrations: [
        __dirname + '/migrations/*.migration{.ts,.js}'
      ]
    }),
  },
]; 
```

The only option I see is to configure 2 dbConnections, one for nest (for the repository/entity) and one for TypeORM for the migrations.

**Comment by d3viant0ne** [comment]
Doesn't really have anything to do with Nest. What exists in the docs is just a simple example of how you could add TypeORM to a Nest server, it's far from the only way to do so.

There is a slightly more robust example here - https://github.com/zachgrayio/nest-typeorm-example

Note the database module used in conjunction with feature module specific TypeORM configs.

**Comment by vlio20** [comment]
awesome! thanks for providing the example

**Comment by d3viant0ne** [comment]
I'm using TypeORM / Nest in prod @ work. You can find me in gitter under the same name if you continue to have trouble with it.

**Comment by vlio20** [comment]
thanks @d3viant0ne ... I will :)

**Comment by welkie** [comment]
Example repo https://github.com/zachgrayio/nest-typeorm-example is 404ing right now.

**Comment by jgordor** [comment]
@welkie https://github.com/kamilmysliwiec/nest-typeorm-example
