### ISSUE TITLE
Update expressJS dependency to 4.16.x

### ISSUE THREAD

**Issue by jhanschoo** [nestjs/nest#206]
ExpressJS 4.16.x (finally!) has `body-parser` as built-in middleware. It should be updated, and the `body-parser` dependency removed (including in the examples).

**Comment by kamilmysliwiec** [comment]
Hi @jhanschoo,
Definitely! Thanks, the package will be updated with the next release 🎉

**Comment by kamilmysliwiec** [comment]
Done v4.1.17 😃

**Comment by malixsys** [comment]
@kamilmysliwiec should this issue really be closed? 🤔

https://github.com/nestjs/nest/blob/master/lib/core/package.json#L8 

c.f. https://nodesecurity.io/advisories/534
