### ISSUE TITLE
Move from socket.io to sockjs

### ISSUE THREAD

**Issue by keenondrums** [nestjs/nest#208]
Hi! Have you thought about moving from socket.io to sockjs? The thing is that socket.io is known for not guaranteeing message order in certain cases. There's a informative [comparison](http://xsnippet.org/359042/). I know I can use my own ws adapter, but shouldn't the best possible tools for the job be propagated as default solutions?

**Comment by kamilmysliwiec** [comment]
Hi @keenondrums,
We're using the socket.io because it's well-known for a lot of people and seems to be the most popular ws library at the moment. As you suggested, if you wanna use another one, you can always create an adapter 🙂

**Comment by victordidenko** [comment]
Does somebody know, is there publicly available SockJS adapter for NestJS?
SockJS beats socket.io on supported clients, it can be used even with old browsers, emulating connection with different techniques, like xhr-streaming, xhr-polling and others.
Even Spring Framework – most popular framework for Java – have chosen to implement SockJS client and server.
