### ISSUE TITLE
Transactions support in Mongoose for Nest

### ISSUE THREAD

**Issue by davidvella82** [nestjs/nest#2086]
Hi,

I am currently experimenting with Nest and considering to use it for a new project. One of the requirements is support for atomic transaction. While it seems to be supported in Node/Mongoose I cannot find any examples of how transactions can be implemented using Nest/TypeScript. Gone through Nest documentation and couldn't find any examples either. Does anyone have any experience in implementing transactions using Nest?

**Comment by kamilmysliwiec** [comment]
I don't think that this is something that should be solved particularly by Nest. See mongoose docs https://mongoosejs.com/docs/transactions.html

**Comment by silvelo** [comment]
I am using transactions in my project and look like this.
```
 async createOrUpdateAdministrator(newAdmin: CreateUserDto) {
        const session = await this.userModel.db.startSession();
        try {
            const adminHash = await this.hashPassword(newAdmin, Role.ADMIN);
            const createdAdmin = await this.userModel.findOneAndUpdate(
                { type: Role.ADMIN }, adminHash, { upsert: true })
                .select('-password')
                .exec();
            const accessToken = await this.generateToken(createdAdmin);
            session.commitTransaction();
            return accessToken;
        } catch (error) {
            session.abortTransaction();
            this.logger.error(`Administrator '${newAdmin.email}' couldn\'t create or update`);
            this.logger.error(error);
        }
    }
```

**Comment by faridhajnal** [comment]
do you know a way of using Promise.all in conjunction with transactions @silvelo ? Thanks for your solution!

**Comment by silvelo** [comment]
> do you know a way of using Promise.all in conjunction with transactions @silvelo ? Thanks for your solution!

No, sorry  :( .
