### ISSUE TITLE
setGlobalPrefix not specified in docs

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#210]
it would be great if it would be possible to add a prefix to all routes, like in this lib example:
https://github.com/pleerock/routing-controllers#prefix-all-controllers-routes

This is how it can be done in express:
https://stackoverflow.com/a/29993694/1691423

**Comment by vlio20** [comment]
Found `setGlobalPrefix`, full example:

```
async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule);
  app.setGlobalPrefix(''); // <----
  await app.listen(3000);
}
bootstrap();
```

Couldn't find it in the docs though...

**Comment by wbhob** [comment]
There are a lot of things that are currently undocumented that should be. The current docs are more of a guide, rather than an API reference. I'm trying to communicate with @kamilmysliwiec to join the core team so I can start to improve documentation, but I haven't heard back yet.

**Comment by kamilmysliwiec** [comment]
Hi @vlio20,
It's in the documentation - https://docs.nestjs.com/faq/global-prefix (**FAQ** section) 🙂
