### ISSUE TITLE
what is the nest-cli.json usefor and where to find doc about it?

### ISSUE THREAD

**Issue by yeongjet** [nestjs/nest#2109]
nest-cli.json exists in the root dictory by using nest-cli to generate new project.
{
  "language": "ts",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src"
}
what is these configurations usefor?
I haven't find out any information about it

**Comment by jmcdo29** [comment]
I used it for when I changed the source root due to using a mono-repo setup. Otherwise, I think you can use it to change to using pure JavaScript instead of Typescript.

**Comment by kamilmysliwiec** [comment]
@jmcdo29 exactly!
