### ISSUE TITLE
[Question] How to mock a Component while creating a Test Module

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#211]
Hi,
I am trying to write a unit test to one of my controllers:  
```
    beforeEach(async () => {
      const module = await Test.createTestingModule({
        controllers: [UsersController],
        components: [
          UserService, // <--- want to mock this
          UtilsService
        ],
      }).compile();
``` 

My question is how can I mock  `UserService` which is injected in `UserController`. `UserSerivce` has a lot of other dependencies that I do not want to add in the test module?

My current solution is just to create a class within the test which has the same class name:
```
class UserService {}
```

**Comment by wbhob** [comment]
You can use provider syntax, which is best defined in the Angular docs (but has the *exact* same functionality) https://angular.io/guide/dependency-injection

Hope this helps!
Wilson

**Comment by stonelasley** [comment]
@vlio20 Here is a quick example of a couple options. ServiceTwo and Three are using the provider syntax wbhob mentioned. 

```typescript
import { Test } from '@nestjs/testing';
import { TestingModule } from '@nestjs/testing/testing-module';
jest.mock('../services/service-one.service');
import { ServiceOne, ServiceTwo, ServiceThree } from '../services';
import { MyController } from './my-report.controller';

describe('MyController', () => {
    let module: TestingModule;
    let controller: MyController;
    let service: ServiceOne;
	let mockTwo: any = {
		funcOne: () => true
	}

    beforeEach(async () => {
        module = await Test.createTestingModule({
            controllers: [MyController],
            components: [
				ServiceOne, //auto-mocked via jest
				{provide: ServiceTwo, useValue: mockTwo}, //uses object above
				{provide: ServiceThree: useFactory: () => {return {funcOne: () => true}} //creates object
			],
        }).compile();

        controller = module.get(MyController);
        service = module.get(ServiceOne);
    });
});

**Comment by vlio20** [comment]
@wbhob, @stonelasley just found `overrideComponent` this one as well:

const module = await Test.createTestingModule({
            modules: [CatsModule],
          })
          .overrideComponent(CatsService).useValue(catsService) // <----
          .compile();

not sure when the overriding taking place, before or after the initialisation...
