### ISSUE TITLE
Request (context) provider in Microservices for request-scoped providers

### ISSUE THREAD

**Issue by ivibe** [nestjs/nest#2111]
## I'm submitting a...
<pre><code>[x] Feature request</code></pre>

## Current behavior
In the HTTP application it's possible to inject an original request reference into request-scoped providers. However, there's no such functionality for microservices.

## Expected behavior
It would be great to have something similar to Request provider but in Microservices. For example, Context provider.

In case of Microservices, context might be an object that contains pattern and transmitted data, at least for TCP Microservice.
```
CONTEXT {
  pattern,
  data
}
```

## What is the motivation / use case for changing the behavior?
Having access to Request (context) provider permit to instantiate services per request based on the context.
For example:
```typescript
import { Module, Scope } from '@nestjs/common';
import { CONTEXT } from '@nestjs/microservices';
import { CatsController } from './cats.controller';
import { CatsService } from './cats.service';
import { ExternalCatsService } from './external-cats.service';
import { LocalCatsService } from './local-cats.service';

@Module({
  controllers: [CatsController],
  providers: [
    {
      provide: CatsService,
      scope: Scope.REQUEST,
      useFactory: ctx =>
        ctx.data.isLocal ? new LocalCatsService() : new ExternalCatsService(),
      inject: [CONTEXT],
    },
  ],
})
export class CatsModule { }
```

## Environment

<pre><code>
Nest version: 6.1.1

 
For Tooling issues:
- Node version: 11.10.0
- Platform:  Windows 10

Others:

</code></pre>

What do you think?

**Comment by kamilmysliwiec** [comment]
Added in 6.30. We need to update the docs accordingly (let's track this here https://github.com/nestjs/docs.nestjs.com/issues/461)

```typescript
import { CONTEXT } from '@nestjs/microservices';
```
`CONTEXT` implements `RequestContext<T>`:

```typescript
pattern: string | Record<string, any>;
data: T;
```

**Comment by ivibe** [comment]
Awesome!
Unfortunately, didn't have time at all to participate in making a PR.
Thank you!

**Comment by rhlsthrm** [comment]
Can you please provide a simple example of how to print out the request context? I am trying to print the `subject` of the received message in my MessagePattern controller.

For example if I subscribe to `@MessagePattern("user.id.>")` I want to be able to get the subject of the request so I can split the string get get the send ID, for example if subject is `user.id.abcdef` I need the `abcdef` part.
