### ISSUE TITLE
controller don't return result without replay.send with fastify platform

### ISSUE THREAD

**Issue by yantrab** [nestjs/nest#2128]
when using @res decorator, it is cause problem to return result.
this is work:
```
    @Post('login')
    async login(@Body() user: LoginRequest): Promise<User> {
        return undefined;
    } 
```
and this is working also:
```
    async login(@Body() user: LoginRequest, @Res() reply): Promise<User> {
          reply.send(foundUser);
    }
```

but this,  does not work:
```
    async login(@Body() user: LoginRequest, @Res() reply): Promise<User> {
        return undefined;
   }
```

[this](https://github.com/yantrab/nest-angular/blob/update-nest/server/src/auth/auth.controller.ts) is the source

**Comment by kiwikern** [comment]
Question was posted on [Stackoverflow](https://stackoverflow.com/q/55945069/4694994)
