### ISSUE TITLE
how to inject the service in the nested module?

### ISSUE THREAD

**Issue by farzer** [nestjs/nest#2144]
```js
// Aservice
@Injectable
export class Aservice {}
```

```js
// Acontroller
@Controller()
export class AController {
  constructor(private readonly aservice: AService) {} // can not inject
}
```

```js
// module A
@Module({
  controllers: [Acontroller],
  providers: [Aservice],
})
export class Amodule {}
```

```js
// moduleB
@Module({
  imports: [Amodule],
})
export class Bmodule {}
```

```js
// Appmodule
@Module({
  imports: [Bmodule],
})
export class Appmodule {}
```

make error

`Nest can't resolve dependencies of the AService (?). Please make sure that the argument at index [0] is available in the AModule context`

- nestjs: 6.0.0

**Comment by AntoineMaitre** [comment]
You have to export the `AService ` within your `Amodule`, otherwise `AService` won't be available in the Bmodule. `Amodule` should look something like this:

```typescript
// module A
@Module({
  controllers: [Acontroller],
  providers: [AService],
  exports: [AService],
})
export class Amodule {}
```

Also pay attention to the typo of the `@Injectable()` decorator within **AService**:

```typescript
// AService
@Injectable()
export class AService {}
```

let me know if it helps

**Comment by farzer** [comment]
Thanks for your reply, but the problem has not been resolved. I reproduced my problem in [this repository](https://github.com/farzer/nest-test).

**Comment by farzer** [comment]
solved [here](https://github.com/dzzzzzy/Nestjs-Learning/issues/23)
