### ISSUE TITLE
[Request] Implementation of "useExisting" provider

### ISSUE THREAD

**Issue by jbjhjm** [nestjs/nest#2145]
## Feature Request

I need to provide a service both directly and via a provider token.
Both need to inject the same instance.
For this use case, angular implements a [ExistingProvider](https://angular.io/api/core/ExistingProvider).

Currently this is only possible by implementing a manual singleton pattern through a factory function.

It would be awesome to see the ExistingProvider in nestjs too and would further reduce differences to angular. 

Thanks.

**Comment by kamilmysliwiec** [comment]
Published as 6.3.0

**Comment by jbjhjm** [comment]
Works perfectly fine. Thank you Kamil!!
