### ISSUE TITLE
Complex controller paths

### ISSUE THREAD

**Issue by javascrewpt** [nestjs/nest#215]
let's say that I'd like to do something like `cats/5/doctor-visits/2` where `5` is `catId` and `2` is `doctorVisitsId`? Would that even be possible? would I need a new controller for this or could I just somehow nest controllers?

Currently I have a controller for `@Controller('cats/:id/doctor-visits/:docId')`

**Comment by javascrewpt** [comment]
OK I managed to get it to work. The documentation is really bad regarding these routes.

````TypeScript
	@Controller('cats')
	export class CatsController {

		@Get()
		findAll() {
			return ['cat', 'cat2'];
		}

		@Get(':id')
		findById( @Param('id') id) {
			console.log(id);
			return ['cat', 'cat2', id];
		}

		@Get(':id/doctor-visits/:docId')
		findByDoctor( @Param('id') id, @Param('docId') docId) {
			console.log(id);
			return ['cat', 'cat2', id, docId];
		}
	}
````

**Comment by wbhob** [comment]
This is the current way this behavior is handled.

**Comment by wbhob** [comment]
You should be able to do this:
```ts
@Controller('cats/:id')
	export class CatsController {
		@Get()
		findById( @Param('id') id) {
			console.log(id);
			return ['cat', 'cat2', id];
		}

		@Get('doctor-visits/:docId')
		findByDoctor( @Param('id') id, @Param('docId') docId) {
			console.log(id);
			return ['cat', 'cat2', id, docId];
		}
	}
```

**Comment by kamilmysliwiec** [comment]
Hey @javascrewpt,
Each `@Controller()` is, in fact, a **express* Router instance - that's why it's not possible to pass any custom parameters at this level. To avoid repeating yourself every time inside every route handler, you can create a function and call it inside the decorator. 🙂  I'm sorry about the troubles with documentation 🙁

**Comment by javascrewpt** [comment]
kamilmysliwiec thank you for taking the time to explain these things. However, since I am relatively new to nest.js, I can't quite imagine the approach you suggested (create a function and call it inside the decorator), can you please provide a basic example?
