### ISSUE TITLE
NestJS CacheManager and redis

### ISSUE THREAD

**Issue by hxdef2517** [nestjs/nest#2154]
Unfortunately haven't found any article or sample on how to use redis with nest.
Basically I've setup redis in app module as was described in docs:

```
CacheModule.register({
      store: redisStore,
      host: 'localhost',
      port: 6379,
    }),
``` 

Then in app module I can get access to instance:

```
export class AppModule {
  constructor(@Inject(CACHE_MANAGER) cacheManager: any,
    private readonly connection: Connection) {

    const client = cacheManager.store.getClient();

    client.on('error', (error: any) => {
      console.info(error);
    });
  }
}
```

and same way access client in controller. But how to have this instance of client among all my modules ? I need to have an access for hSet, set, get methods in certain parts of my application and different modules

**Comment by kamilmysliwiec** [comment]
Create `CoreModule` which imports:
```typescript
CacheModule.register({
   store: redisStore,
   host: 'localhost',
   port: 6379,
}),
```
and exports `CacheModule`. Afterward, import `CoreModule` in every module in which you need an access to the cache manager.
