### ISSUE TITLE
[Question] How to create a ArgumentMetadata for testing pipes 

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#216]
Hi,
Is it possible to create Metadata object which implements argument Metadata interface? I need it in order to test pipes. Sure I can create a simple object wich is implementing this interface, but I am curious if there is a different way.

**Comment by wbhob** [comment]
I'm having trouble understanding what you need. If you're asking to create an object based on an interface, you just type the object as the interface:

```
let myObj: Argument Metadata = {
    ....
}
```

**Comment by vlio20** [comment]
Forget about it, misunderstood that it just can be run during the test.

**Comment by wbhob** [comment]
Nice post-mortem! Good luck!
