### ISSUE TITLE
Please Add `optional: boolean` to @Query route param decorator

### ISSUE THREAD

**Issue by justinmchase** [nestjs/nest#2169]
## I'm submitting a...
[x] Feature request

## Current behavior
Using `@Query('foo')` will always make a query parameter required.

## Expected behavior
The Query decorator should have an `optional: boolean` property available, similar to how the Args decorator for gql resolvers has nullable and other options.

e.g.
`@Query({ name: 'foo', optional: true })`

I'm ok with it always being a string and then using pipes to validate / transform the value downstream but at least `nullable` or `optional`, whatever, would be nice.

## Minimal reproduction of the problem with instructions
> NA

## What is the motivation / use case for changing the behavior?
I'm creating a controller and would like to have optional parameters with sensible defaults.

## Environment
> NA

## Extra
I believe this is the correct location in code:
https://github.com/nestjs/nest/blob/master/packages/common/decorators/http/route-params.decorator.ts#L95

**Comment by kamilmysliwiec** [comment]
> Using @Query('foo') will always make a query parameter required.

I'm not sure what do you mean by this. Query parameters are always optional.

**Comment by justinmchase** [comment]
Hmm, I was interpretting it as required because swagger was doing so.

![Screen Shot 2019-05-10 at 8 37 16 AM](https://user-images.githubusercontent.com/10974/57531397-fd649d80-72fe-11e9-916b-2b372a0ee5c1.png)

If you're saying that its always optional then maybe there is a different way to describe it for swagger?

**Comment by Destreyf** [comment]
@justinmchase I had something similar happen when i used swagger, i had to create Dto objects with the `@ApiModelProperty` decorator, and then i used `({ required: false })` as the param for it. 

This is done for a post, but i believe you should be able to do something similar, if there's a better way to do it i'd love to see it.

It appears the Swagger UI when it add's parameters they're defaulted as required and (as far as i can tell) the only way to change that is to use the `ApiModelProperty` decorator.

This is an example of my `CreateUserDto`

```ts
export class CreateUserDto {
  @ApiModelProperty()
  name: string;

  @ApiModelProperty()
  email: string;

  @ApiModelProperty({ required: false })
  password?: string;

  @ApiModelProperty({ required: false })
  confirmPassword?: string;
}
```

**Comment by hwalyonglance** [comment]
@justinmchase 
```
@ApiImplicitQuery({
	name: 'foo',
	required: false,
	type: String
})
myMethod(@Query('foo') foo: string){

}
```

**Comment by kamilmysliwiec** [comment]
Both solutions are fine :)

**Comment by notHaiLuu** [comment]
For me, I still keep the rule of DTO, but I use @ApiImplicitQuery to control @Query is optional or required in swagger params, and it worked. Thanks you guys.

`export class CreateCmsDTO {
  @ApiModelProperty({ example: 'cms_code' })
  @IsNotEmpty()
  code: string;

  @ApiModelProperty({ example: {'content': '<h3>This is content</h3>'} })
  @IsNotEmpty()
  value: string;
}`

`@Get()
  @ApiOperation({ title: `Get all cms` })
  @ApiImplicitQuery({
    name: 'code',
    description: 'The cms\'s code',
    required: false,
    type: String
  })
  @ApiOkResponse({ type: CmsDTO, isArray: true, description: `Returns all cms` })
  async getAll(@Query('code') code?: string): Promise<CmsDTO[]> {
    const entities = await this.cmsService.getAll(code);
    const dtos = this.cmsConverter.toDTOs(entities);

    return dtos;
  }`
