### ISSUE TITLE
process.env.NODE_ENV undefined

### ISSUE THREAD

**Issue by Githamza** [nestjs/nest#2174]
I would configure enivrement variables in nestjs as mentioned in documentation[ here](https://docs.nestjs.com/techniques/configuration):

in my service constructor  I get env file path

```
import * as dotenv from 'dotenv';
import * as fs from 'fs';

export class ConfigService {
  private readonly envConfig: { [key: string]: string };

  constructor(filePath: string) {
    this.envConfig = dotenv.parse(fs.readFileSync(filePath))
    console.log(this.envConfig)
  }

  get(key: string): string {
    return this.envConfig[key];
  }
}
``` 
 Then in config module I set the config service
```
  providers: [
    {
      provide: ConfigService,
      useValue: new ConfigService(`${process.env.NODE_ENV}.env`),
    },
  ],
  exports: [ConfigService],
})
```
## Current behavior
Actually I get   process.env.NODE_ENV value` undefined`

## Expected behavior
get env variable path in process.env.NODE_ENV

Nest version: 6.0.0
 
For Tooling issues:
- Node version: 10
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
See https://stackoverflow.com/questions/9198310/how-to-set-node-env-to-production-development-in-os-x

**Comment by darwinguz** [comment]
I have the same error but my `NODE_ENV=development` and when I run its value is `undefined` and the result:
`ENOENT: no such file or directory, open ''`

**Comment by Tornik73** [comment]
I use this one:
`start:dev": "SET NODE_ENV=DEVELOPMENT && 
concurrently --handle-input \"wait-on dist/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\"",`

**Comment by devfreddy** [comment]
I ran into a similar issue, the first resolution was utilizing `cross-env` to set it and the second appears to be when running multiple commands, declaring it front of each/or the proper one. 

My best guess without finding confirmation of this is that although `&&` runs commands sequentially, waiting for the previous one to finish, it must start with fresh env variables for each command.

Doesn't work:

```bash
"start:dev": "cross-env NODE_ENV=development rimraf dist && concurrently --handle-input \"wait-on dist/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\" ",
```

```bash
"start:dev": "cross-env NODE_ENV=development && rimraf dist && concurrently --handle-input \"wait-on dist/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\" ",
```

```bash
"start:dev": "cross-env NODE_ENV=development rimraf dist && concurrently --handle-input \"wait-on dist/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\" ",
```

Works:

```bash
"start:dev": "rimraf dist && cross-env NODE_ENV=development concurrently --handle-input \"wait-on dist/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\" ",
```

```bash
# rimraf likely doesn't care about NODE_ENV /shrug
"start:dev": "cross-env NODE_ENV=development rimraf dist && cross-env NODE_ENV=development concurrently --handle-input \"wait-on dist/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\" ",
```

**Comment by ripley** [comment]
I had a same issue and added one log in config service's constructor.

  constructor(filePath: string) {
    console.log(filePath);
    this.envConfig = dotenv.parse(fs.readFileSync(filePath))
    console.log(this.envConfig)
  }

No matter I set NODE_ENV to development explicitly as a envvar or via cross-env the console.log always dumped the path TWICE, the first time it's 'development.env', and the second time it's 'undefined.env'.

Struggling to figure out what's going on here ...

**Comment by mfechner** [comment]
Have you checked `process.env` after you have executed `dotenv.parse...`?

**Comment by tobiassen** [comment]
I'm facing the same issue as well.
Followed the documentation on how to implement configuration (https://docs.nestjs.com/techniques/configuration): 
```config.module.ts```:
```typescript
import { Module } from '@nestjs/common';
import { ConfigService } from './config.service';

@Module({
  providers: [
    {
      provide: ConfigService,
      useValue: new ConfigService(`${process.env.NODE_ENV || 'development'}.env`),
    },
  ],
  exports: [ConfigService],
})
export class ConfigModule {}
```

```config.service.ts```:
```typescript
import * as dotenv from 'dotenv';
import * as fs from 'fs';

export class ConfigService {
  private readonly envConfig: { [key: string]: string };

  constructor(filePath: string) {
    console.log(`filePath: ${filePath}`)
    this.envConfig = dotenv.parse(fs.readFileSync(filePath))
    console.log(`envConfig: ${JSON.stringify(this.envConfig)}`)
    console.log(`NODE_ENV: ${process.env.NODE_ENV}`)
  }

  get(key: string): string {
    return this.envConfig[key];
  }
}
```
Output:
```log
8:52:49 PM - Found 0 errors. Watching for file changes.
filePath: development.env
envConfig: {"KEY1":"value1","KEY2":"value2"}
NODE_ENV: development
[Nest] 8347   - 09/22/2019, 8:52:51 PM   [NestFactory] Starting Nest application...
filePath: undefined
[Nest] 8347   - 09/22/2019, 8:52:51 PM   [ExceptionHandler] The "path" argument must be one of type string, Buffer, or URL. Received type undefined +119ms
```

**Comment by baptisteArnaud** [comment]
> I'm facing the same issue as well.
> Followed the documentation on how to implement configuration (https://docs.nestjs.com/techniques/configuration):
> `config.module.ts`:
> 
> ```ts
> import { Module } from '@nestjs/common';
> import { ConfigService } from './config.service';
> 
> @Module({
>   providers: [
>     {
>       provide: ConfigService,
>       useValue: new ConfigService(`${process.env.NODE_ENV || 'development'}.env`),
>     },
>   ],
>   exports: [ConfigService],
> })
> export class ConfigModule {}
> ```
> 
> `config.service.ts`:
> 
> ```ts
> import * as dotenv from 'dotenv';
> import * as fs from 'fs';
> 
> export class ConfigService {
>   private readonly envConfig: { [key: string]: string };
> 
>   constructor(filePath: string) {
>     console.log(`filePath: ${filePath}`)
>     this.envConfig = dotenv.parse(fs.readFileSync(filePath))
>     console.log(`envConfig: ${JSON.stringify(this.envConfig)}`)
>     console.log(`NODE_ENV: ${process.env.NODE_ENV}`)
>   }
> 
>   get(key: string): string {
>     return this.envConfig[key];
>   }
> }
> ```
> 
> Output:
> 
> ```
> 8:52:49 PM - Found 0 errors. Watching for file changes.
> filePath: development.env
> envConfig: {"KEY1":"value1","KEY2":"value2"}
> NODE_ENV: development
> [Nest] 8347   - 09/22/2019, 8:52:51 PM   [NestFactory] Starting Nest application...
> filePath: undefined
> [Nest] 8347   - 09/22/2019, 8:52:51 PM   [ExceptionHandler] The "path" argument must be one of type string, Buffer, or URL. Received type undefined +119ms
> ```

I have the exact same problem, even when I hardcode 'development.env'. So the problem doesn't come from undefined env variable

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
