### ISSUE TITLE
 module structure and autoload

### ISSUE THREAD

**Issue by GlauberF** [nestjs/nest#2175]
there is now some way to autoloader a new module, with its folder and its files and its module annotation.

Because I am creating a structure that will receive new applications / modules on demand and it would be much easier and less laborious, to have a way of after including the folder with the new module it is already registered and available for the entire application.

**Comment by kamilmysliwiec** [comment]
This is not how the framework itself is supposed to work. If you want to automatically include a new module in `imports` array of nearest module, I'd suggest creating your own schematic.
