### ISSUE TITLE
[Question | Bug] - getting sub injectable from TestingModule

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#218]
Hi,
When trying to get a sub injectable (for example `Component`) it returns null.
For example:  

```
// DatabaseModule
@Module({
  modules: [],
  components: [
    SubService
  ]
})
export class AppModule {
}

// App Module
@Module({
  modules: [
    DatabaseModule
  ]
})
export class AppModule {
}
```
And then when trying to user `createTestingModule`:
```
const module = await Test.createTestingModule({
      modules: [AppModule]
}).compile();

const subService = appModule.get<SubService>(SubService);
concole.log(subModule) // null
```

I found this workaround:
```
const dbModule = appModule.select(DatabaseModule);
const subService = dbModule.get<SubService>(SubService);

concole.log(subService) // instance of SubService
```

So should the `get` method return also nested components of other dependent modules? If so, this is a bug.

**Comment by kamilmysliwiec** [comment]
Hey @vlio20!
Nope. That's exactly why the `select()` method exists. There's a note about it [here](https://docs.nestjs.com/advanced/e2e-testing) 🙂

**Comment by vlio20** [comment]
the `including imported ones` is a bit misleading (maybe only for me)

**Comment by kamilmysliwiec** [comment]
True, right. Thanks @vlio20, will change this 🙂

**Comment by kamilmysliwiec** [comment]
Fixed, will be available in the next update. Thanks again @vlio20
