### ISSUE TITLE
Catch ValidationError

### ISSUE THREAD

**Issue by AlexeyAlexeyAlexeyAlexey** [nestjs/nest#2197]
I use next package versions:
    @nestjs/common: 6.2.0,
    @nestjs/core: 6.2.0,
    @nestjs/jwt: 6.1.0,
    @nestjs/mongoose: 6.1.2,
    @nestjs/passport: 6.1.0,
    @nestjs/platform-express: 6.2.0,
    @nestjs/swagger: 3.0.2,   
    mongoose: 5.5.8, 
    rxjs: 6.5.2,
    typescript: 3.4.5

While processing database (Mongo) request I've got ValidationError (field in database is longer than it's maxlength in Schema):
![111](https://user-images.githubusercontent.com/50629385/57708393-ea8cf880-7671-11e9-9325-e8eb40443d98.png)

I wanted to catch such errors using @Catch() interseptor. But I cannot do it because something wrong with ValidationError. It used to be in mongoose package, now it's in nestjs/common:
![222](https://user-images.githubusercontent.com/50629385/57708539-30e25780-7672-11e9-9d01-72b03229d729.png)

How do I globally catch ValidationError?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.
