### ISSUE TITLE
jwt authentication

### ISSUE THREAD

**Issue by GlauberF** [nestjs/nest#2219]
I'm having trouble getting into a solution for jwt authentication.

my application connects to mongoDB and this DB already has data, which is managed by another application too laravel (PHP).

As I would just to authenticate, that is the user when calling a route I made in nestjs, it will send a token created based on its user, but made that token in laravel.

I only need to make the page authenticate and validate if this token is in fact valid, because I have access to the database.

Anyone would have any idea how I would do this, since I can not generate another token, just validate the token that was sent to me, based on the data in the database.

**Comment by Destreyf** [comment]
@GlauberF 

Normally i think this kind of question would belong on StackOverflow but I will give it a quick shot to explain how you should be able to make this work.

As long as you configure the JWT module with the same secret/expiration as the Laravel app, you should be able to validate JWT tokens made by the Laravel system.

If you go to the documentation for JWT auth: https://docs.nestjs.com/techniques/authentication#jwt-strategy and take a look specifically at the `JwtStrategy` class and the `AuthModule`.

You will need to import this AuthModule into your main AppModule in order for it to take affect, you also need to implement Guards to validate the JWT, on that same page you should look for the `JwtAuthGuard` code.

The `validate` function found in the `JwtStrategy` needs to call some service/function that can look up a user by some property of the Jwt that was included in the request.  In the example code this is based off the `email` property, but if you have a `id` for your user in your Jwt you could accomplish the same thing.

You will have to make sure your front end app sends it as an `Authorization` header in the `Bearer TOKEN_HERE` format in order for it to be processed correctly.

**Comment by kamilmysliwiec** [comment]
Thanks @Destreyf for the detailed answer! Next time @GlauberF, please use either StackOverflow or our Discord channel

**Comment by evilive3000** [comment]
@GlauberF 
> The `validate` function found in the `JwtStrategy` needs to call some service/function that can look up a user by some property of the JWT that was included in the request. In the example code this is based off the `email` property, but if you have a `id` for your user in your JWT you could accomplish the same thing.

Is this a good practice to call something like `UserService.findById(payload.id)` each request? Don't we reinvent sessions in such way, doing DB call each request and fetching user by session/token.
We have all data that we need in payload (id, email, etc.) and we trust it because it's signed, so why do we need this DB calls?
