### ISSUE TITLE
6.2.1 breaks overrideProvider for custom providers

### ISSUE THREAD

**Issue by kiwikern** [nestjs/nest#2229]
## I'm submitting a...

<pre><code>
[x] Regression
</code></pre>

## Current behavior

The update to @nestjs/core@6.2.1[ broke my integration tests](https://travis-ci.org/kiwikern/shassi-nest/jobs/534429171) with: `TypeError: Class constructor TelegrafMock cannot be invoked without 'new'`

This is because I'm overriding a custom provider in my unit test with `useClass(TelegrafMock)`.

##### AppModule
```
providers: [
  {
    provide: AppService,
    useFactory: () => new AppService(),
  },
],
```

##### e2e test
```
const moduleFixture = await Test.createTestingModule({
  imports: [AppModule],
})
  .overrideProvider(AppService)
  .useClass(AppService)
  .compile();
```

I think the regression was introduced in #2070. 
Before the change, `inject` was null:
https://github.com/nestjs/nest/blob/11a85cd25457fa1dd61fde0240031023cfbb6013/packages/core/injector/injector.ts#L590

## Minimal reproduction of the problem with instructions

I have created a simple [codesandbox ](https://codesandbox.io/s/nesttypescriptstarter-lnbch?fontsize=14&module=%2Ftest%2Fapp.e2e-spec.ts) that shows the failing test. Just run the e2e tests.

## Environment

<pre><code>
Nest version: 6.2.1
</code></pre>

**Comment by kamilmysliwiec** [comment]
Just published hotfix (6.2.2). It should be fixed now :) Thanks for reporting
