### ISSUE TITLE
Request injection across modules appears borked

### ISSUE THREAD

**Issue by eropple** [nestjs/nest#2259]
## Current behavior
I'm trying to build a module to inject request-scoped Bunyan loggers into my application. I write a lot of different apps, so I'm working on this as an external module. Currently, using `@Inject(REQUEST)` in an `@Injectable` or `inject: [REQUEST]` in a `FactoryProvider` injects `undefined`.

## Input Code
```ts
import { DynamicModule, Scope, RequestMethod, forwardRef } from '@nestjs/common';
import { FactoryProvider, NestModule, MiddlewareConsumer } from '@nestjs/common/interfaces';
import { REQUEST } from "@nestjs/core";
import * as Bunyan from "bunyan";
import { IncomingMessage } from 'http';
import { merge, flatten } from "lodash";

import { LoggingOptions, DEFAULT_LOGGING_OPTIONS } from './options';
import { ROOT_LOGGER, LOGGER, LOGGING_OPTIONS } from './injector-keys';

export class LoggingModule implements NestModule {
  static forRoot(options: Partial<LoggingOptions>): DynamicModule {
    const realOptions = merge(DEFAULT_LOGGING_OPTIONS, options);
    const moduleLogger = realOptions.rootLogger.child({ component: LoggingModule.name });
    moduleLogger.info("Building module for injector.");

    // obviously this should be a ValueProvider, but I wanted to explicitly log inside it.
    const loggingOptions: FactoryProvider = {
      provide: LOGGING_OPTIONS,
      useFactory: () => {
        console.log("LOGGING_OPTIONS provider")
        return realOptions;
      }
    };

    const rootLogger: FactoryProvider = {
      provide: ROOT_LOGGER,
      scope: Scope.DEFAULT,
      inject: [LOGGING_OPTIONS],
      useFactory: (options: LoggingOptions) => {
        console.log("ROOT_LOGGER provider, typeof(options): ", typeof(options)) // prints out "object"
        return options.rootLogger;
      }
    };

    const requestLogger: FactoryProvider = {
      provide: LOGGER,
      scope: Scope.REQUEST,
      inject: [ROOT_LOGGER, REQUEST],
      useFactory: (rootLogger: Bunyan, request: IncomingMessage) => {
        console.log("LOGGER provider, typeof(rootLogger, request): ", typeof(rootLogger), typeof(request)); // prints "object", "undefined"
        // dies on this line, as request is undefined
        const correlationId = flatten(request.headers["x-correlation-id"]) || "NO_X_CORRELATION_ID_FOUND";

        const requestLogger = rootLogger.child({ correlationId });
        return requestLogger;
      }
    }

    return {
      module: LoggingModule,
      imports: [],
      providers: [
        loggingOptions,
        rootLogger,
        requestLogger
      ],
      exports: [
        ROOT_LOGGER,
        LOGGER
      ]
    };
  }
}
```

Output (and this is using [@eropple/nestjs-bunyan-logger](https://github.com/eropple/nestjs-bunyan-logger) to prettify my server logs, you can clearly see where the `console.log` statements are getting dropped):
```
[2019-05-23T04:16:51.422Z]  INFO: podshow/LoggingModule/31155 on bigboss: Building module for injector.
[2019-05-23T04:16:51.514Z]  INFO: podshow/Nest/31155 on bigboss: Starting Nest application... (context=NestFactory)
LOGGING_OPTIONS provider
ROOT_LOGGER provider, typeof(options):  object
[2019-05-23T04:16:51.557Z]  INFO: podshow/Nest/31155 on bigboss: ConfigModule dependencies initialized (context=InstanceLoader)
... [more startup stuff]
[2019-05-23T04:16:51.728Z]  INFO: podshow/Nest/31155 on bigboss: Nest application successfully started (context=NestApplication)
... [and now I issue a request that tries to `@Inject(LOGGER)` from the main application...
LOGGER provider, typeof(rootLogger, request):  object undefined
... [and now the request crashes in the request-scoped logger factory]
```

I've also tried it with a `forwardRef`, which didn't change anything.

## Expected behavior
I expect the request object to end up injected into the `requestLogger` factory provider.

## Environment

<pre><code>
Nest version: 6.2.4
 
For Tooling issues:
- Node version: 11.14.0
- Platform:  Fedora 29, though I doubt it's related

Others:
n/a
</code></pre>

**Comment by eropple** [comment]
Also, to short-circuit a couple other things:

- Controllers in my hosted application properly receive injected `@Inject(REQUEST)`ed requests.
- When I add my own request-scoped export to my module, my host application can receive it.

It appears to be directly related to `REQUEST`.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue, it would help us a lot

**Comment by eropple** [comment]
Unfortunately I've since worked around the issue I was hitting, so I don't have a repro off-hand. However, it appears to not be a third-party module issue at all, but rather a lifecycle issue. My providers were being engaged to inject a request-scoped logger into a middleware. At the point in the request lifecycle where middlewares are being created, it seems like the value provided by `REQUEST` is undefined. I would think that this should throw an error, but it seems like the pre-validation done by the DI container doesn't catch this.

This may now be a duplicate of another bug.

**Comment by kamilmysliwiec** [comment]
Could you provide a repo that reproduces this issue? We can't help without it :(
