### ISSUE TITLE
Use strings rather than symbols as DI tokens

### ISSUE THREAD

**Issue by eropple** [nestjs/nest#2260]
## Describe the solution you'd like
It's a little difficult to develop a module with `npm link` because `@nestjs/core` defines `REQUEST` (and a few others) as a `Symbol`. When using `npm link`, your dependent module has a different instance of that `Symbol` and the DI injector doesn't understand what you're asking for.

There may be another good solution to this, FWIW; the symbol equality issue is just throwing me at the moment.

Request-scoped request injection across modules appears broken at the moment for other reasons (see #2259), but this is orthogonal to that.

## Teachability, Documentation, Adoption, Migration Strategy
Not applicable; internal feature iteration.

## What is the motivation / use case for changing the behavior?
The solution largely describes it. I want to develop my external modules in parallel with a working application and `npm link` is the "canonical" way to do so (`tsc --watch` the submodule, restart the nodemon'd app when it's rebuilt).

Currently I'm working around it with a `file:` dependency in `package.json` and manually removing the `node_modules` folder that gets copied in, and that really isn't great.

**Comment by kamilmysliwiec** [comment]
Honestly, I don't understand. All `@nestjs/...` packages should be set as peer dependencies (and shared between libs)

**Comment by eropple** [comment]
So I might be missing something, but here's my understanding. For sake of argument, call our third-party dev package `nestjs-addon`.

- When you're developing `nestjs-addon`, if you have `@nestjs/...` as peer dependencies, you then need them as dev dependencies (so that you have types, etc. for `tsc` to actually build against).
- When you then `npm link` into a NestJS application (so as to test your third-party library against a real app), the current state of your `nestjs-addon` directory is symlinked into your app's `node_modules` directory. This includes _its_ `node_modules`.
- When you import from `nestjs-addon`, it _appears_ to be sourcing stuff like `@nestjs/core` from _its_ `node_modules` directory, not _the NestJS application's_ `node_modules` directory.
- Because of this, `nestjs-addon`'s `Symbol(REQUEST)` is _not the same object_ as the app's `Symbol(REQUEST)`, and so the dependency injector cannot satisfy that token.

Please correct me if I'm misunderstanding, but this seems to hang together.

**Comment by felixhayashi** [comment]
Same situation, here. It took me some time to get to the root of this problem and then found this issue.

If one is linking nestjs projects via e.g. lerna and each nestjs project has it's own set of `node_modules` including a copy of `@nestjs/core` then the `REQUEST` symbol used in the imported **module A** won't match the `REQUEST` used in the main **module B** that is importing the other **module A**. 

So if **module A** is using a service provided by **module B** that is "request-scoped" (via `@Inject(REQUEST)`) then the DI-mechanism will fail with an `UNKNOWN_DEPENDENCIES_MESSAGE`.

If the `REQUEST` provider token were a string, this problem would be solved.

 the error message created via `UNKNOWN_DEPENDENCIES_MESSAGE` also fails to convert a Symbol value to a string in vs code: `TypeError: Cannot convert a Symbol value to a string`.

**Comment by kamilmysliwiec** [comment]
Changed in 7.0.0

**Comment by felixhayashi** [comment]
Hi @kamilmysliwiec,

thanks for this new release :+1: 

However, I don't think the PR addresses the problem described in the OP, it only fixed the resulting error message. After all `REQUEST` ('@nestjs/core') is still a symbol and as such it causes the problems described above.

Please consider reopening this ticket, thanks.

**Comment by kamilmysliwiec** [comment]
This has been fixed in this PR https://github.com/nestjs/nest/pull/4201
