### ISSUE TITLE
req.url is always '/' in Middleware

### ISSUE THREAD

**Issue by IceMimosa** [nestjs/nest#2261]
## Current behavior

In Middleware, the req.url is always `/` Instead of the actual URL path. But in Controller, the req.url is correct.

> Tips: I use nextjs to handle the URL like this `nextServer.getRequestHandler()(req, res)`, and it uses req.url by default.

## Input Code

```ts
// Middleware
@Injectable()
export class LoggerMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: Function) {
    console.log(`Request middleware... ${req.url}`); // always /
    next();
  }
}

// Controller
@Controller('/cats')
export class AppController {
  constructor(private readonly appService: AppService) {}
  @Get('/all')
  getHello(@Req() req: Request): string {
    console.log(`Request... ${req.url}`); // correct
    return this.appService.getHello();
  }
}
```

## Possible Solution

I can use `req.originalUrl` to resolve this.

```ts
this.nextServer.getRequestHandler()
  .bind(this.nextServer)(req, res, url.parse(req.originalUrl));
```

## Environment

<pre><code>
Nest version: 6.2.4

 
For Tooling issues:
- Node version: v10.13.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by zinzinday** [comment]
This not a bug. Remove slash / on decorator Controller.
```ts
    @Controller('cats')
```

**Comment by IceMimosa** [comment]
@zinzinday It doesn't seem to work.

**Comment by underfin** [comment]
The behavior depending on the `express`.

**Comment by kamilmysliwiec** [comment]
It's not related to Nest
