### ISSUE TITLE
Cannot hide opencollective message in CI

### ISSUE THREAD

**Issue by reegnz** [nestjs/nest#2264]
## Current behavior
I tried setting all the options described in https://github.com/nuxt/opencollective#disable-message
Nothing hides the message.

## Expected behavior
In a CI environment I want to disable such messages like the opencollective one.

## Possible Solution
Upgrade the opencollective lib to 0.2.2
https://github.com/nuxt/opencollective/blob/master/CHANGELOG.md

## Environment
Platform:  Mac
Nest version: 6.2.4

 ```bash
➜ npm --version
6.9.0
➜ node --version
v10.15.3
```

**Comment by kamilmysliwiec** [comment]
Would you be interested in creating a PR for this?

**Comment by reegnz** [comment]
Sure, I can try that.

**Comment by reegnz** [comment]
@kamilmysliwiec PR is open.
