### ISSUE TITLE
[PackageLoader] The "class-transformer" error reopen issue for nest 6.2.2

### ISSUE THREAD

**Issue by NikitaIT** [nestjs/nest#2268]
https://github.com/nestjs/nest/issues/1386

**Comment by kamilmysliwiec** [comment]
It's not an issue. `class-transformer` is and will always be required if you use `ValidationPipe`

**Comment by NikitaIT** [comment]
@kamilmysliwiec I think should specify this clearly here https://docs.nestjs.com/techniques/validation

**Comment by guizoxxv** [comment]
I'm using NestJs 6.0.0 and importing ValidationPipe on `main.ts` as
`import { ValidationPipe } from '@nestjs/common';`

I receive the following error:
`The "class-transformer" package is missing. Please, make sure to install this library ($ npm install class-transformer) to take advantage of ValidationPipe.`

On the [documentation page](https://docs.nestjs.com/techniques/validation) there is only mention that the [class-validator package](https://github.com/typestack/class-validator) is used so I believe that this package is installed by default with NestJS.

The [class-transformer package](https://github.com/typestack/class-transformer) is an extension mentioned by class-validator GitHub page and after installing it `npm install class-transformer` the error was fixed.

I believe that the class-transformer package should be a dependency of NestJs or mentioned on the validation documentation page.
