### ISSUE TITLE
Hacking Nest DI container?

### ISSUE THREAD

**Issue by ngonzalezromero** [nestjs/nest#2282]
Hi all!!
In our company, we have many microservices build it on Nest. 
Also, we have a utility class, that provide us Db connections, logging, etc. This library has a nest as a dependency
some months ago, we didn't  have problems with this library, but now, we  would like the share it with other node projects (lambda, express, etc), but the Nest dependency it does not allow us
is for that, that we need to inject, dynamically every class of this library to DI Nest.
We could instantiate each class, but we love the DI 
Thank for the help
cc @cguzmancamus

**Comment by BrunnerLivio** [comment]
> but the Nest dependency it does not allow us

Can you be a bit more specific with that? What does Nest not allow?

Have you checked out [Application Context](https://docs.nestjs.com/application-context)in the docs?

**Comment by ngonzalezromero** [comment]
> > but the Nest dependency it does not allow us
> 
> Can you be a bit more specific with that? What does Nest not allow?
> 
Sure.
When we  want to deploy a lambda on aws, the Nest dependency ( "@nestjs/common": "4.6.6","@nestjs/core": "4.6.6")  crashes the execution ( too many memory usage )

> Have you checked out [Application Context](https://docs.nestjs.com/application-context) in the docs?

We want inject our class on DI injector ,
We don’t get instances from that

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.
