### ISSUE TITLE
Webpack report error : "Module not found"

### ISSUE THREAD

**Issue by wowtim** [nestjs/nest#2285]
## Current behavior

Webpack report error ：Module not found for "@nestjs/microservices","cache-manager", "class-transformer"

## Input Code

Here is my "webpack.config.js", I removed HMR configuration from sample.
```
const webpack = require('webpack');
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: ['./src/main.ts'],
  target: 'node',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  mode: 'development',
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'server.js',
  },
};
```

When I run "webpack --config webpack.config.js",  it reports 

Error: 
Can't resolve '@nestjs/microservices' in “[my path]/node_modules/@nestjs/core"
Can't resolve '@nestjs/cache-manager' in "[my path]/node_modules/@nestjs/common/cache"
Can't resolve '@nestjs/class-transformer' in "[my path]/node_modules/@nestjs/common/pipes"
...

## Expected behavior

Webpack finished without errors
## Environment
Win 10

**Comment by kamilmysliwiec** [comment]
You also removed `nodeExternals`. See this issue for more info https://github.com/nestjs/nest/issues/1706
