### ISSUE TITLE
Is it possible to reuse DTO parameters?

### ISSUE THREAD

**Issue by Pietrox** [nestjs/nest#2286]
Hello,

I was wondering if it's possible to use single parameter in DTO that is taken from a class to a class along with all decorators.

For example:

Model A
```Typescript
export class CatsDtoA {
    @ApiModelProperty()
    @IsNotEmpty()
    @Type(() => String)
    SessionID: string;
}
````
Model B
```Typescript
export class CatsDtoB {
    @ApiModelProperty()
    @IsNotEmpty()
    @Type(() => Number)
    UserID: number;
}
````

And the final model would take these 2 classes all together with the decorators and form Model C.
Is it even doable? It's like extending 2 classes into one - or maybe there is some other way?

**Comment by kamilmysliwiec** [comment]
Multiple inheritance is unavailable in JavaScript
