### ISSUE TITLE
Middleware for all routes not working with pathless controller and methods

### ISSUE THREAD

**Issue by Can-Sahin** [nestjs/nest#2291]
## Current behavior
A Middleware configured with `forRoutes('*')` is not called with a controller without path, such like `@Controller()`, and also a method without any path, like `@Get()`.  It works with a path in either of them however. The reason behind a pathless controller is I already have a `app.setGlobalPrefix('api/...')` in my app and I am putting up a controller for that path of global prefix, so no need for a path.

## Input Code

```ts
//Basically like
NestFactory.create(UserAPIModule, adapter)
  .then(app => {
    app.setGlobalPrefix('api/user');
    app.enableCors();
    return app.init();
  })

// Then...

@Module({
  imports: [UserModule],
})
export class UserAPIModule {
  public configure(consumer: MiddlewareConsumer) {
    consumer.apply(MyMiddleware).forRoutes('*');
  }
}

@Injectable()
export class MyMiddleware implements NestMiddleware {
  public use(req: Request, res: Response, next: Function) {
    console.log('THIS IS NOT CALLED');
    next();
  }
}

@Module({
  imports: []
  controllers: [UserController],
})
export class UserModule {}


@Controller()
export class UserController {
  constructor() {}

  @Get()
  public async getUser() {
    console.log('this is called without middlware');
    return 'Users object';
  }
}
```

## Expected behavior
Middlewares should also be called on pathless controllers due to the meaning of the `wildcard` 

## Environment

<pre><code>
Nest version: 6.2.4

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Could you please provide a minimal repository which reproduces your issue?

**Comment by Can-Sahin** [comment]
https://github.com/Can-Sahin/nestjs-issue-sample

I put the descriptions into readme file. 

Thanks.

**Comment by soumyart** [comment]
I'm also facing the same issue.

**Comment by soumyart** [comment]
By replacing `@Controller()` with `@Controller('')`, middlewares are invoked for both the route (with/without trailing slash).

**Comment by Can-Sahin** [comment]
I was trying this and don't think this works (with '')
`@Controller({ path: '', scope: Scope.REQUEST })`

**Comment by soumyart** [comment]
Sorry, my bad. Hadn't tested properly. It's not working.

**Comment by zonorion** [comment]
Hi, i have an issue. 
`"message": "Cannot POST /v1/hotel/"`
But when i remove the trailing slash like: /v1/hotel. It's work well. So i want nestjs accept both.
Can you tell me what i have to do? Thanks so much :)

**Comment by kamilmysliwiec** [comment]
This has been clarified in the documentation (as part of the v7 release) https://docs.nestjs.com/middleware#route-wildcards

![image](https://user-images.githubusercontent.com/23244943/78987438-526feb80-7b2e-11ea-8a7e-91a7eefe4a01.png)
