### ISSUE TITLE
Express set

### ISSUE THREAD

**Issue by underfisk** [nestjs/nest#2293]
## Current behavior

set is not being exposed in order to add custom config to express such as trust proxy
## Input Code

```ts
const your = (code) => here;
```

## Expected behavior

Being able to set express config such as trust proxy, views etc
## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
See this https://docs.nestjs.com/first-steps#platform
```
const app = await NestFactory.create<NestExpressApplication>(ApplicationModule);
```

**Comment by underfisk** [comment]
Hi what i mean is this:
https://expressjs.com/en/4x/api.html#app.set

**Comment by ricardosaracino** [comment]
This seems to work.. not sure if this is recommended 
```
 const server = express();

    server.set('trust proxy', 1);

    const app = await NestFactory.create(AppModule, new ExpressAdapter(server), {
        logger,
        httpsOptions: environment.httpsOptions,
    });
```

**Comment by underfisk** [comment]
That's strange because the old nestjs version had set, now it's not exposed and it's very useful for this like trust proxy

**Comment by ricardosaracino** [comment]
Nest should not be dependent on express.. It makes total sense

**Comment by underfisk** [comment]
Yes but since nest uses mainly it and set is one of the most used things, there's no problem on exposing it that's what i mean

**Comment by ricardosaracino** [comment]
Gonna have to agree to disagree on this one 😉

**Comment by kamilmysliwiec** [comment]
There is a `set` method, but you have to use `NestExpressApplication` interface. See here https://docs.nestjs.com/first-steps#platform

```typescript
const app = await NestFactory.create<NestExpressApplication>(ApplicationModule);
```

**Comment by ricardosaracino** [comment]
this is much better than what im doing
