### ISSUE TITLE
UnhandledPromiseRejectionWarning on invalid RMQ microservice pattern

### ISSUE THREAD

**Issue by atte-backman** [nestjs/nest#2299]
## Current behavior

When sending invalid JSON microservice pattern via RMQ, e.g. `{ac`, `UnhandledPromiseRejectionWarning` is being thrown:

    (node:21109) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at ServerRMQ.handleMessage (.../node_modules/@nestjs/microservices/server/server-rmq.js:61:29)
        at channel.consume (.../node_modules/@nestjs/microservices/server/server-rmq.js:54:51)

## Expected behavior
This situation (exception) should be gracefully handled. For instance, when sending unknown event pattern the following is being produced:

    [Nest] 21398   - 05/29/2019, 1:17 PM   There is no matching event handler defined in the remote service. +352291ms

## Environment

<pre><code>
Nest version: 6.2.4

 
For Tooling issues:
- Node version: 10.15.3
- Platform:  Ubuntu 16.04.6 LTS

**Comment by kamilmysliwiec** [comment]
Fixed in the latest release
