### ISSUE TITLE
How to inject component into interceptor?

### ISSUE THREAD

**Issue by ArtworkAD** [nestjs/nest#230]
Say we created a logger component:

```
@Component()
export class LoggerService {

    logger: any;

    constructor() {
        this.logger = new Logger({
            transports: [
                new transports.Console({
                    json: false,
                    timestamp: true,
                    level: 'info'
                })
            ]
        });
    }
    //...
}
```

To use this logger I simply add it to components list of the app module:

```
@Module({
    modules: [...],
    components: [LoggerService]
})
```

I want to know if it is correct to use the logger in an interceptor as follows:

```
@Interceptor()
export class LoggingInterceptor implements NestInterceptor {

    constructor(private readonly logger: LoggerService) {}

    intercept(dataOrRequest, context: ExecutionContext, stream$: Observable<any>): Observable<any> {
        this.logger.info('Request to ' + context.parent.name + '.' + context.handler.name);
        return stream$;
    }
}
```

and in server.ts

`app.useGlobalInterceptors(new LoggingInterceptor(new LoggerService()));`

I noticed that component injection does not work in the interceptor. So is it safe to pass a new instance of LoggerService to LoggingInterceptor?

**Comment by adrien2p** [comment]
Hey @ArtworkAD 
You should use the IoC pattern, that mean's you need create a provider like this : 
```
{
    provide: 'LoggerService',
    userValue: LoggerService
}
```

And then inject it with `@Inject('LoggerService') private readonly loggerService`

**Comment by ArtworkAD** [comment]
@adrien2p thank you, how do I use this?

```
{
    provide: 'LoggerService',
    userValue: LoggerService
}
```

Do I have to replace it in `components: [LoggerService]`?

**Comment by adrien2p** [comment]
Yep you can inject it as a component in components

**Comment by ArtworkAD** [comment]
@adrien2p thanks but

`app.useGlobalInterceptors(new LoggingInterceptor())`

wants me to provide the logging service as argument. How do I pass it when using injection?

**Comment by ArtworkAD** [comment]
@adrien2p yes I did inject it like this

    constructor(@Inject('LoggerService') private readonly loggerService) {}

but this 

    app.useGlobalInterceptors(new LoggingInterceptor())

is giving me error that `1 argument is expected`. It wants me to provide a logger service instance. So I am wondering should I just do

    app.useGlobalInterceptors(new LoggingInterceptor(new LoggerService()))

or is that bad practice?

**Comment by adrien2p** [comment]
Yes i think in a global interveptor you can’t inject like this my bad, so you need to pass a classic argument

**Comment by ArtworkAD** [comment]
@adrien2p thanks for your help :1st_place_medal:
