### ISSUE TITLE
How to unit test service

### ISSUE THREAD

**Issue by BrucePauker** [nestjs/nest#2308]
Hello !

First thank you so much for such a beautiful framework !

I juste have question regarding unit testing services with mongoDB. In the documentation about unit testing mongoDB there is : 

> When it comes to unit test our application, we usually want to avoid any database connection, making our test suits independent and their execution process quick as possible. But our classes might depend on models that are pulled from the connection instance. What's then? The solution is to create fake models. In order to achieve that, we should set up custom providers . In fact, each registered model is represented by NameModel token, where Name is a model's name.

service.spec.ts
`import { Test, TestingModule } from '@nestjs/testing';
import { ReservationService } from './reservation.service';
import {
    CreateReservationDto,
    LanguageModule,
    LanguageService,
    LoggerService,
    ReservationType,
    RestaurantServiceInterface,
} from '@pielectronique/shared/dist';
import { getModelToken } from '@nestjs/mongoose';
import { HttpModule } from '@nestjs/common';
import { ConfigService } from '../../config/config.service';
import { Request } from 'express';
import * as moment from 'moment';
import { ReservationSchema } from '../models/reservation.schema';
import * as mongoose from 'mongoose';
import { Model } from 'mongoose';

const ReservationModel = mongoose.model('Reservation', ReservationSchema);

describe('ReservationService', () => {
    let reservationService: ReservationService;
    const newPreReservation: CreateReservationDto = {
        pax: 2,
        lastName: 'Doe',
        phoneNumber: '0632165082',
        dateTime: moment.utc().toISOString(),
        type: ReservationType.PRE_RESERVATION,
    };

    const mockRequest: any = {
        t: Function,
    };

    beforeEach(async () => {

        const module: TestingModule = await Test.createTestingModule({
            providers: [
                ReservationService,
                LoggerService,
                ConfigService,
                {
                    provide: getModelToken('Reservation'),
                    useValue: ReservationModel,
                },
            ],
            imports: [
                HttpModule,
                LanguageModule,
            ],
        }).compile();

        reservationService = module.get<ReservationService>(ReservationService);
        const languageService: LanguageService = module.get(LanguageService);
        mockRequest.t = languageService.i18next.t;
    });

    it('should be defined', () => {
        expect(reservationService).toBeDefined();
    });

    describe('create reservation', () => {
        it('should create reservation', async () => {
            const service = Promise.resolve([
                {
                    id: '5ceac5d51f42182ae03b9c8a',
                    restaurantID: '5cd3220cf32b4a1ad822b7bc',
                    startDateTime: '2019-06-22T10:00:00.000Z',
                    endDateTime: '2019-06-22T11:00:00.000Z',
                } as RestaurantServiceInterface,
            ]);

            jest.spyOn(
                reservationService,
                'findServiceForReservation',
            ).mockImplementationOnce(() => service);

            const reservation = await reservationService.createReservation(
                '5cd3220cf32b4a1ad822b7bc',
                newPreReservation,
                mockRequest as Request,
            );

            expect(
                reservationService.findServiceForReservation,
            ).toHaveBeenCalledTimes(1);
            expect(reservation).toBeDefined();
            expect(reservation).toContain(newPreReservation);
        });
    });
});
`

service.ts
`import {
    Injectable,
    HttpService,
    ConflictException,
    HttpException,
    HttpStatus,
} from '@nestjs/common';
import {
    CreateReservationDto,
    HttpBodyInterface,
    LoggerService,
    ReservationInterface,
    ReservationStatus,
    RestaurantServiceInterface,
} from '@pielectronique/shared/dist';
import { InjectModel } from '@nestjs/mongoose';
import * as mongoose from 'mongoose';
import { Model } from 'mongoose';
import { Request } from 'express';
import { Moment } from 'moment';
import { AxiosResponse } from 'axios';
import { Observable } from 'rxjs';
import { ConfigService } from '../../config/config.service';
import * as moment from 'moment';

@Injectable()
export class ReservationService {
    constructor(
        private readonly loggerService: LoggerService,
        @InjectModel('Reservation')
        private reservationModel: Model<
            ReservationInterface & mongoose.Document
        >,
        private readonly httpService: HttpService,
        private readonly configService: ConfigService,
    ) {}

    /**
     * Create a new reservation and return it
     *
     * @param {string} restaurantID
     * @param {CreateReservationDto} reservation
     * @param {Request} req
     */
    async createReservation(
        restaurantID: string,
        reservation: CreateReservationDto,
        req: Request,
    ): Promise<ReservationInterface & mongoose.Document> {
        const newReservation = new this.reservationModel(reservation);
        newReservation.status = ReservationStatus.WAITING;
        newReservation.restaurantID = restaurantID;
        let service: RestaurantServiceInterface[];

        service = await this.findServiceForReservation(
            restaurantID,
            moment.utc(newReservation.dateTime),
            req,
        );

        if (service.length > 0) {
            try {
                return await newReservation.save();
            } catch (e) {
                this.loggerService.error(e, 'ReservationService');
                throw new HttpException(
                    req.t('error:GENERAL_ERROR'),
                    HttpStatus.BAD_REQUEST,
                );
            }
        } else
            throw new ConflictException(req.t('reservation:ERROR.NO_SERVICE'));
    }

    /**
     * Return the service for a given dateTime
     * Calls the service Service with http method
     *
     * @param {string} restaurantID
     * @param {Moment} dateTime
     * @param req
     * @return {ReservationInterface[]}
     */
    async findServiceForReservation(
        restaurantID: string,
        dateTime: Moment,
        req: Request,
    ): Promise<RestaurantServiceInterface[]> {
        try {
            const axiosResponse: AxiosResponse<
                HttpBodyInterface<RestaurantServiceInterface[]>
            > = await this.httpService
                .get(
                    this.configService.serviceUri +
                        `/by/date/${restaurantID}?startDateTime=${dateTime.toISOString()}&endDateTime=${dateTime.toISOString()}`,
                )
                .toPromise();

            return axiosResponse.data.data;
        } catch (e) {
            this.loggerService.error(e, 'ReservationService');
            throw new HttpException(
                req.t('error:GENERAL_ERROR'),
                HttpStatus.BAD_REQUEST,
            );
        }
    }
}
`

However, I really don't understang how to implement the catModel without having a connection. Moreover, even when I'm trying to have a connection, the async method does not work and the test stays open. Could you please help me on this issue ?

I'm sorry, but I'm just starting with unit test so I still need to learn and understand a lot.

Thank you very much

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.
