### ISSUE TITLE
Unknown authentication strategy "bearer" when using servise with scope: Scope.REQUEST

### ISSUE THREAD

**Issue by ondrej-janosik** [nestjs/nest#2310]
## Current behavior
When I change my AuthService with method getUserByToken to scoped I am getting an error:
 [Nest] 713   - 05/30/2019, 3:38 PM   Unknown authentication strategy "bearer" +4390ms
If I change it back to singleton everzthing works as excepted

## Input Code
```ts
import { Injectable, Scope } from '@nestjs/common';

import { UserEntity } from 'src/entity/UserEntity';
import { Repository } from 'typeorm';

import { InjectRepository } from '@nestjs/typeorm';

@Injectable({
  // scope: Scope.REQUEST, // THIS IS THE LINE THAT CHANGE THE BEHAVIOUR
})
export class AuthService {
  constructor(
    @InjectRepository(UserEntity)
    private readonly userRepository: Repository<UserEntity>,
  ) {}

  public async getUserByToken(token: string): Promise<UserEntity> {
    const user = await this.userRepository.findOne({
      where: {
        token,
      },
      relations: ['role'],
    });

    return user;
  }
}
```

## Expected behavior
It should work with different scoping

## Environment

<pre><code>
Nest version: 6.2.4
 
For Tooling issues:
- Node version: 10.15.0
- Platform:  Windows

**Comment by ondrej-janosik** [comment]
I have just noticed a very similar issue (https://github.com/nestjs/nest/issues/1870) and it looks like this behavior is by design. Is there any documentation/example of how to implement authorization in a multitenant application?

**Comment by kamilmysliwiec** [comment]
As you noticed, it's impossible to use passport for that. I'd rather recommend wiring up your own tailored auth mechanism (which should be fairly simple though). I'm not aware of any article at the moment unfortunately :(
