### ISSUE TITLE
Enums and decorators within modules are undefined outside of the module in which they are defined

### ISSUE THREAD

**Issue by tristan957** [nestjs/nest#2315]
## Bug Report

I have an AuthModule with a Role enum being exported in auth/index.ts. I also have an Authorized decorator saying which roles are allowed being exported in auth/auth.decorator.ts.

## Current behavior

When I try to use the enum or the decorator to protect routes in the UserController in the UserModule, I get undefined compilation errors such Role has no property ADMIN.

## Expected behavior
Ability to use the decorator and enum outside of the auth module.

## Environment

<pre><code>
Nest version: 6.2.4

**Comment by tristan957** [comment]
I can't find this behavior mentioned in the docs at all.

**Comment by shekohex** [comment]
Don't use `export * from './somefile.whatever.ts'` and also the relative import will not work there, you need the full path, at least where the file is located.

I didn't know if that's a must, but when i face that issue and the DI goes crazy, i just use the full path, and it works

I think it's a bug in Typescript it self? IDK to be honest.

By the way, if it's a bug in Typescript, i think the docs should have a note about that.

**Comment by tristan957** [comment]
Is there a bug in the TS repository I can refer to? Otherwise I will open one

**Comment by shekohex** [comment]
> Is there a bug in the TS repository ...

As i said I'm not sure of that 😅, I'm just guessing 😳

**Comment by tristan957** [comment]
Alright. I am gonna open one then and see what happens. Thanks for your help. Your advice fixed my problem.

**Comment by kowsheek** [comment]
This could be related to a common issue in NodeJS where it caches module references as they get loaded.

**Comment by tristan957** [comment]
@kowsheek is there a bug in the nodejs or v8 repos that I could refer to?

**Comment by kowsheek** [comment]
If I understand the issue correctly, it's not a bug in NodeJS, but rather a [documented "feature"](https://nodejs.org/api/modules.html#modules_cycles). There's an open [issue on TS](https://github.com/Microsoft/TypeScript/issues/13245) about it.
