### ISSUE TITLE
express-adapter - Error: listen EACCES 0.0.0.0:3000 

### ISSUE THREAD

**Issue by GregorBiswanger** [nestjs/nest#2316]
## Current behavior
Hello community, my project can not be done anymore. I always get the following exception: "Error: listen EACCES 0.0.0.0:3000" - I tried different ports (see bottom). It always comes the same error message. I only use one gateway so far and had NestExpressApplication included and a static folder to choose. That had worked well. Only now can not do this anymore.

## Input Code
```ts
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { AppModule } from './app.module';
import { join } from 'path';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  app.useStaticAssets(join(__dirname, '..', 'public'));
  app.setGlobalPrefix('/v1/api');
  await app.listen(3000);
}
bootstrap();
```

## Exception on start
> npm start

> server@0.0.1 start C:\Users\Gregor\Documents\Web-Projects\HandsUp\server
> ts-node -r tsconfig-paths/register src/main.ts

[Nest] 16072   - 2019-05-30 21:34   [NestFactory] Starting Nest application...
[Nest] 16072   - 2019-05-30 21:34   [InstanceLoader] AppModule dependencies initialized +20ms
[Nest] 16072   - 2019-05-30 21:34   [RoutesResolver] AppController {/v1/api/}: +136ms
[Nest] 16072   - 2019-05-30 21:34   [RouterExplorer] Mapped {/, GET} route +5ms
[Nest] 16072   - 2019-05-30 21:34   [NestApplication] Nest application successfully started +5ms
Error: listen EACCES 0.0.0.0:3030
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at ExpressAdapter.listen (C:\Users\Gregor\Documents\Web-Projects\HandsUp\server\node_modules\@nestjs\platform-express\adapters\express-adapter.js:41:32)
    at NestApplication.listen (C:\Users\Gregor\Documents\Web-Projects\HandsUp\server\node_modules\@nestjs\core\nest-application.js:133:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at Object.<anonymous> (C:\Users\Gregor\Documents\Web-Projects\HandsUp\server\node_modules\ts-node\src\bin.ts:154:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.0.1 start: `ts-node -r tsconfig-paths/register src/main.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gregor\AppData\Roaming\npm-cache\_logs\2019-05-30T19_34_28_102Z-debug.log

## Environment

<pre><code>
Nest version: 6.0.0
 
For Tooling issues:
- Node version: 10.14.1
- Platform:  Windows

**Comment by GregorBiswanger** [comment]
Port 80 works - But I want to use port 3000 - nothing but local port 3000 ?! Have also tried 3030 or 3001 - Nothing works. Really crazy.

**Comment by underfin** [comment]
You can  take a look for https://stackoverflow.com/questions/35068712/error-listen-eacces-0-0-0-080-osx-node-js or https://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports

**Comment by kamilmysliwiec** [comment]
It's not directly related to NestJS. Please, take a look at the above links
