### ISSUE TITLE
PRECONDITION-FAILED / UnhandledPromiseRejectionWarning after RMQ reconnect

### ISSUE THREAD

**Issue by atte-backman** [nestjs/nest#2323]
## Current behavior

When starting microservice with RMQ transport layer everything is ok. There is exactly one consumer for the queue as there should be:

![toook](https://user-images.githubusercontent.com/7066805/58694713-5a062600-839c-11e9-9ff0-8237d5376da9.png)

There happens some weird behavior when shutting RMQ manually down via

    $ sudo service rabbitmq-server stop

At first glance, everything seems normal and expected. The console is correctly flooded with

    [Nest] 6536   - 05/31/2019, 11:52 AM   Disconnected from RMQ. Trying to reconnect. +101323ms

However, after starting RMQ again with

    $ sudo service rabbitmq-server start

there occurs `UnhandledPromiseRejectionWarning`:

     (node:6536) UnhandledPromiseRejectionWarning: Error: Operation failed: BasicConsume; 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - reply consumer already set"
         at reply (.../node_modules/amqplib/lib/channel.js:128:29)
         at ConfirmChannel.C.accept (.../node_modules/amqplib/lib/channel.js:411:7)
         at Connection.mainAccept [as accept] (.../node_modules/amqplib/lib/connection.js:64:33)
         at Socket.go (.../node_modules/amqplib/lib/connection.js:478:48)
         at Socket.emit (events.js:189:13)
         at emitReadable_ (_stream_readable.js:535:12)
         at process._tickCallback (internal/process/next_tick.js:63:19)

Also, it seems the old consumer is not removed (or reused), as after the reconnect there is now 2 consumers for the queue from the same microservice (process):

![toomuch](https://user-images.githubusercontent.com/7066805/58694604-0dbae600-839c-11e9-875d-f49071961a38.png)

## Expected behavior

Nest shouldn't create new consumer on successful reconnect.

## Environment

<pre><code>
Nest version: 6.2.4
 
For Tooling issues:
- Node version: 10.15.3
- Platform:  Ubuntu 16.04.6 LTS
- RabbitMQ 3.6.2, Erlang 18.3

**Comment by kamilmysliwiec** [comment]
Could you please provide a minimal repository which reproduces your issue?

**Comment by kamilmysliwiec** [comment]
Fixed in 6.10.9
