### ISSUE TITLE
[Suggestion] Adding Middleware Pipeline

### ISSUE THREAD

**Issue by shekohex** [nestjs/nest#233]
### What is a Middleware Pipeline ?
 For now all Middleware run in sequence 
```
Client => Middleware1 => Middleware2 => Middleware3 => Server (Controller)
```
What's Middleware Pipeline is to create a pipeline that will make Middleware run in parallel , **WHAT** ?

```
                | => (Pipeline) [Middleware1 => Middleware2]
Client =>
                | => (Pipeline) [Middleware3]
```

Why Pipelines ?
> 80% of the middleware are not dependent upon each other, so executing them in sequence is overkill
Making them parallel will be huge performance boost.
What I have in mind is.. Piplelines + Middleware
Each pipeline will be executed in sequence and it can have multiple middleware, they will be executed in parallel
So If u want 2 middleware to be executed in sequence, you can put them in 2 pipelines
So middleware like Shield + Flash + AuthInitwill be in a single pipeline
And Cors will be in a different pipeline, since it has the ability to end the request of it’s own.
> @thetutlage "the Author of AdonisJS"

You can read more at this [Discussion](https://github.com/adonisjs/discussion/issues/13#event-1318519280) in AdonisJS Framework

**Comment by adrien2p** [comment]
:+1

**Comment by MonsieurMan** [comment]
@adrien2p Please use reactions instead, these comments really pollutes issues so is this one I'm writing.

**Comment by shekohex** [comment]
I will try to see it anyway
