### ISSUE TITLE
Type 'classDTO' has no properties in common with type 'DeepPartial<Class>'.ts(2559)

### ISSUE THREAD

**Issue by Riffero** [nestjs/nest#2344]
## Bug Report
I need to save a DTO using a method of my service, which comes from the client going through the controller
## Current behavior
Type 'PersonaDTO' has no properties in common with type 'DeepPartial<Persona>'.ts(2559)

## Input Code

persona.service.ts
```ts
@Injectable()
export class PersonaService {
    constructor(
        @InjectRepository(Persona)
        private readonly personaRepository: Repository<Persona>){}

    //METODOS ABM CONTRA LA BASE DE DATOS
    async nuevoPersona(nuevaPersonaDTO: PersonaDTO): Promise<Persona>{
        const persona = await this.personaRepository.save(nuevaPersonaDTO);
        return persona;
    }
}
```
persona.dto.ts
```ts
 export class PersonaDTO {
    readonly nombre: string;
    readonly edad: number;
    readonly telefono: string;
    readonly esCasado: boolean;
 }
```
persona.ts
```ts
@Entity()
export class Persona {

    @ObjectIdColumn()
    private id:ObjectID
    
    @Column()
    private nombre:string;

    @Column()
    private edad:number;

    @Column()
    private telefono:string;

    @Column()
    private esCasado:boolean;
    //getters and setters
}
```
## Expected behavior
the method _.save(nuevaPersonaDTO)_ saves the data correctly

## Possible Solution
In a previous project, 2 or 3 months ago, the method I'm trying to implement now worked.
I do not know if it will be a problem of some update

## Environment

<pre><code>
Nest version: 6.3.0

 
For Tooling issues:
- Node version: v10.15.3  
- Platform: Windows 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
You should rather report this issue here https://github.com/typeorm/typeorm
