### ISSUE TITLE
Angular 8 and nest g controller

### ISSUE THREAD

**Issue by FuelKubitox** [nestjs/nest#2345]
## Bug Report

I created an Angular 8 Project and used Angular CLI to add NestJS. Works fine, but if i add Controllers with NestJS CLI i have some Problems in app-routing.module.ts .

First i have to say, that it sucks, when i use CLI that he rewrites the app-routing.module.ts and my ordered File becomes a little bit messy as i not want. Do describe my Problem i added a Picture of my Error in Visual Studio Code. This is what i get when i use the CLI.

[https://ibb.co/QjnkKfs](url)

```ts
const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'aboutme', component: AboutmeComponent },
  { path: 'projects', component: ProjectsComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'blog', component: BlogComponent },
  { path: 'admin', component: AdminComponent, canActivate: [AuthGuardLogin] },
  { path: 'login', component: LoginComponent },
  { path: 'logout', component: LogoutComponent },
  { path: 'notfound', component: NotFoundComponent },
  { path: '**', redirectTo: '/notfound' },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
  controllers: [UserController, BlogController, ProjectsController]
})
export class AppRoutingModule { }
```

**Comment by kamilmysliwiec** [comment]
This isn't how Nest and Angular integration is supposed to work.  
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.

**Comment by FuelKubitox** [comment]
It wasnt just a Question. The Nest CLI creates this Code...

**Comment by kamilmysliwiec** [comment]
You shouldn't run Nest CLI commands inside the Angular repo because it cannot easily distinguish Nest/Angular modules. In your command line, navigate to the directory that contains Nest application.

**Comment by FuelKubitox** [comment]
Thanks
