### ISSUE TITLE
Impossible to load npm package (require is working not import)

### ISSUE THREAD

**Issue by qlaffont** [nestjs/nest#2346]
## Current behavior
When I try to load [nconf](https://github.com/indexzero/nconf) with require syntax it's working but with import syntax is not working. Do you know why ?

## Input Code

```ts
import { Injectable } from '@nestjs/common';
// import nconf from 'nconf';
const nconf = require('nconf');

@Injectable()
export class NconfService {
  public config() {
    console.log(nconf);
    console.log('/');
    nconf
      .argv()
      .env()
      .file({ file: 'path/to/config.json' });

    return nconf;
  }
}

```

## Expected behavior
console.log need to return an object not undefined.

## Environment

<pre><code>
Nest version: "@nestjs/core": "^6.0.0"

 
For Tooling issues:
- Node version: v11.11.0
- Platform:  Mac

Others:
- Use VSCode
</code></pre>

**Comment by kamilmysliwiec** [comment]
Instead of:
```
import nconf from 'nconf';
```
Use:
```
import * as nconf from 'nconf';
```
or enable synthetic default imports

**Comment by qlaffont** [comment]
Thanks !
