### ISSUE TITLE
How to inject static MyPipe instance to microservice controller.

### ISSUE THREAD

**Issue by vsDizzy** [nestjs/nest#2347]
I need to use this pipe instance across all the RbMQ controllers:
```ts
const pipe = new ValidationPipe({ transform: true });
```

What is the a proper way to set it up?
Currently I'm using a workaround:

app.controller.ts
```ts
@Controller()
@UsePipes(MyPipe)
export class AppController {}
```

my-pipe.ts
```ts
export class MyPipe {
  constructor(@Inject('pipe') base) {
    return base;
  }
}
```

app.ts
```ts
  const mod = await Test.createTestingModule({
    controllers: [AppController],
    providers: [{ provide: 'pipe', useValue: pipe }],
  }).compile();
```

We're using `MyPipe` here as a wrapper. Is it OK?

**Comment by kamilmysliwiec** [comment]
Why not just `@UsePipes(pipe)`? You don't have to necessarily pass type between parenthesis, the instance is fine as well

**Comment by vsDizzy** [comment]
Yes this should work too. Thanks.

**Comment by vsDizzy** [comment]
Actually I can't use instance because my pipe uses `Logger` and transforming services from `DI`

**Comment by kamilmysliwiec** [comment]
I don't understand. So why can't you just use DI?

**Comment by vsDizzy** [comment]
What I'm thinking about is kind of `@UsePipes('token')` And then it resolve token using `DI`.

Backing to my case:
If `pipe` is global to our controller where i can instantiate it so it could use services from `DI`.
Maybe in `OnModuleInit`?

**Comment by kamilmysliwiec** [comment]
> If pipe is global to our controller where i can instantiate it so it could use services from DI.
Maybe in OnModuleInit?

Your code is valid

```
@UsePipes(MyPipe)
export class AppController {}
```

This allows `MyPipe` to inject dependencies

**Comment by vsDizzy** [comment]
It is intertwined a little. But thank you Kamil you saved my day.
