### ISSUE TITLE
WebSocket Gateway - doesn't work with ExpressAdapter

### ISSUE THREAD

**Issue by adrianpiesiak** [nestjs/nest#2355]
## Current behavior
WebSocket Gateway is not working properly when Nest application is created by using ExpressAdapter.

It seems that the gateway is not linked properly to the http service - client gets 404 upon connection, gateway itself seems to be initiated (OnGatewayInit is executed with meaningful result).

## Input Code
I've created minimal code to reproduce.
In the main.ts there are two bootstrap method implementations - one works, second one doesn't.

There is client.js file to simulate the client. Simply run it with node client.js - it should produce console logs in both server (when socket is properly connected) and in client (upon connection error).

https://github.com/adrianpiesiak/NestJs-socket-bug

## Expected behavior
The WebSocketGateway should work in both bootstrapping methods

## Environment
Node: 10.15.2
@nestjs/core@6.3.1
@nestjs/common@6.3.1
@nestjs/platform-socket.io@6.3.1
@nestjs/platform-express@6.3.1

**Comment by kfsjostrand** [comment]
Try to 
```javascript
const httpServer = await https.createServer(httpsOptions, server).listen(port);
app.useWebSocketAdapter(new IoAdapter(httpServer));
await app.init();
```

**Comment by kamilmysliwiec** [comment]
If you replace this line:
```typescript
http.createServer(server).listen(3000);
```

with this line
```typescript
await app.listen(3000);
```
it's gonna work fine. Why are you trying to spin up `http` server manually? You can access this one created by Nest easily:

```typescript
const httpServer = app.getHttpServer();
```

Also, you don't have to use `ExpressAdapter` to have full control over `express` instance - you can simply call this instead:

```typescript
const express = app.getHttpAdapter().getInstance();
```

**Comment by adrianpiesiak** [comment]
Thanks @kamilmysliwiec - I will verify that shortly.
The example wasn't showing the intention - which is, instantiate the app, so that you can get a config service instance injected into the main.ts file, so that you can read e.g. http / https / certificates / etc and apply them to the service, without breaking the socket gateway ;)

Thanks for quick answer.
