### ISSUE TITLE
Nestjs e2e testing with mocking mongoose model example unclear

### ISSUE THREAD

**Issue by Manju-CA** [nestjs/nest#2356]
I am writing end to end test for my nestjs+mongoose application with supertest. I am able to mock mongoose apis such as find(), delete() etc. But with mongoose save api, for code this.CatModel(CatObject), mocking is not working. I dont have mongodb for test system , so i need to mock it. In nestjs documentation i could not find any explaination for it.

cat.e2e-spec.ts

    describe('cat apis', () => {
let app: INestApplication;

    beforeAll(async () => {
    const module = await Test.createTestingModule({
            imports: [CatModule]
        })
            .overrideProvider(getModelToken('Cat'))
            .useValue(mockCatModel)
            .compile();

    app = module.createNestApplication();
    server = app.getHttpServer();
    await app.init();
});

    it(`POST /cat `, async () => {
    return await request(server)
        .post('/cat')
        .send(newcatPayload)
        .set('Accept', 'application/json')
        .expect(201)
        .expect(({ body }) => {
            expect(body).toEqual(expectedResponse);
        });
});
cat.service.ts

    public async createCat(catObject: CreateCatDto, user): Promise<ICat> {
    const oCat = this.catModel(catObject);
    oCat.user = user;
    return await oCat.save();
}
catModel.ts

    export const mockCatModel = {

  find: (obj) => {
    return [catMock];
  },

    save : (cat) => {
    return cat;
   }
  };
this.catModel.find() works fine but, this.catModel() throws Error: 'this.catModel is not a function'.

I tried in catModel.ts, adding below function,

    function : (a) => {return a;}
but did not work. Please help if with correct way of mocking this.catModel(catObject).

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We're using GitHub to track feature requests, bugs, and improvements.
