### ISSUE TITLE
Proxying via @Controller doesn't work but via app.all (from express) does ?

### ISSUE THREAD

**Issue by appsolutegeek** [nestjs/nest#2357]
## Current behavior
This is going to be a difficult one to understand and explain but here goes.

I am trying to proxy all requests through a @Controller, first of all this is confirmed as working

```
   const server = express()

    server.all("*", function(req, res) {
      proxy.web(req, res, {
        changeOrigin: true,
        target: "https://kibana.test.com:443"
      })
```

The above proxies all my request to Kibana and it works without an issue, I placed it in main.ts which is where I do the following

```
    const server = express()
    const app = await NestFactory.create(AppModule, new ExpressAdapter(server))
    await app.init()
```

I will explain the controller setup now, which is exactly the same but it starts to proxy but it fails on some things with specifically this issue. The controller uses the same "app" above to bootstrap. no difference there.

```
https://localhost:3009/api/saved_objects/_bulk_get 504 (Gateway Time-out)
```

I really don't understand why, it works as above.. Here is my @Controller, is doing the "exact" same thing.

```
import { All, Controller, Get, Inject, Req, Res } from "@nestjs/common"
import { Request, Response } from "express"
import Server from "http-proxy"

@Controller()
export class ProxyController {
  private server: Server
  constructor() {
    this.server = Server.createProxyServer()
  }

  @All()
  proxyAll(@Req() request: Request, @Res() response: Response): void {
    this.server.web(request, response, { changeOrigin: true, target: "https://kibana.test.com:443" })
  }
}
```

I can't provide a repo, I mean, its KIBANA that seems to cause an issue but my question is, what difference is it between the PURE express route above and a controller route ?

Is there some hidden middleware or life cycle I am not aware of ?

I am using the package http-proxy

## Environment

<pre><code>
Nest version: 6.1

 
For Tooling issues:
- Node version: 11
- Platform:  MAC

Others:
</code></pre>

**Comment by kamilmysliwiec** [comment]
`@All()` is actually using `server.use()` underneath. Could you check this code:

```typescript
const server = express()

// previously server.all
server.use("*", function(req, res) {
    proxy.web(req, res, {
        changeOrigin: true,
        target: "https://kibana.test.com:443"
})
```
to confirm if that causes the problem

**Comment by appsolutegeek** [comment]
sure, i am on it. Thanks for not closing this :-) I was at a loss.

i will come back as soon as i have done a test, probably be tomorrow now.

Thanks.

**Comment by appsolutegeek** [comment]
Ok I tested it, this doesn't even proxy at all... Doesn't even load anything.. Strange right ??

To confirm I did exactly this.

```
server.use("*", function(req, res) {
      proxy.web(req, res, {
        changeOrigin: true,
        target: "https://kibana.test.com:443"
      })
    })
```

if I now comment it out and return it to

```
server.all("*", function(req, res) {
      proxy.web(req, res, {
        changeOrigin: true,
        target: "https://kibana.test.com:443"
      })
```

it works again.

Can i provide more info ?

**Comment by appsolutegeek** [comment]
I suppose I could just use the code above but i want to take advantage of dependency injection etc as I have some logic for proxying - basicallly I am checking some security headers and if its there then i proxy otherwise I don't.

If I create a service (rather than a controller) and use the "server.all" where server is the express instance - maybe that will work ? Doesn't seem clean right ?

Also, the other thing is how do I get a hold of the express instance inside a service, i don't think its possible right ?

**Comment by kamilmysliwiec** [comment]
> Also, the other thing is how do I get a hold of the express instance inside a service, i don't think its possible right ?

Actually, it's possible, see here https://docs.nestjs.com/faq/http-adapter#in-context-strategy

You can inject `HttpAdapterHost` which wraps `HttpAdapter` inside. Afterward, call `httpAdapter.getInstance()`.

**Comment by appsolutegeek** [comment]
Nice! I am going to keep this handy. So to summarise. I have a fix already :-)

The issue is still present and I don't fully understand why it worked with pure express vs controller.

But I was proxying kibana which was behind its own proxy server (it was adding security headers and them sorts of things). I have now replaced the URL with the direct kibana address and now my proxy is working inside Controllers!

So - its strange that this was happening (and still is), but it is fixed for me.

For sure, it was something the kibana proxy was adding that was causing problems but the annoying thing was with a test on pure express it worked - which is why I reached out.

I am going to close this now.

I suppose its kind of an edge case anyway :-)

Thanks

**Comment by appsolutegeek** [comment]
@kamilmysliwiec Sorry, I thought it. was fixed. Its not :-( so the problem remains, even going directly to kibana.

I suppose I can use the above that you mentioned httpAdaptor.getInstance inside a service ??

This would be satisfactory i suppose

Unless you have anything else I could try ? :-)

**Comment by appsolutegeek** [comment]
I suppose it wouldn't make sense in doing the getInstance inside a controller - right ? The controller is there to provide http methods and considering I have an issue - then a service is probably the right call here ?

I will try it

**Comment by kamilmysliwiec** [comment]
> I suppose I can use the above that you mentioned httpAdaptor.getInstance inside a service ??

Exactly. You can create a sort of `ProxyHttpService` that uses `getInstance()` directly (and call `.all()` in there)

**Comment by appsolutegeek** [comment]
Yep - confirmed as working - I will close it.

```
@Injectable()
export class AppService {
  constructor(private readonly loggerFactoryService: LoggerFactoryService, private readonly httpAdapterHost: HttpAdapterHost) {
    const proxy = Server.createProxyServer()

    const expressInstance = this.httpAdapterHost.httpAdapter.getInstance()

    expressInstance.all("*", function(req, res) {
      proxy.web(req, res, {
        changeOrigin: true,
        target: "https://kibana.test.com:443"
      })
    })
  }
}
```

Thanks.

I suppose there isn't  much more we can do here, so feel free to close this now - I have my workaround that works well.

**Comment by Aaltuj** [comment]
I know the issue is closed, but i came across the same scenario. Only this time with the syncing of CouchDb. The workaround by having the `expressInstance.all('sync')` in the service unfortunately doesn't allow me the set the `@AuthGard('jwt')`. 

So i could add a express middleware that does this manually or i'll take a look what is using the JWT AuthGard and try to call that in the Express middleware.

A different approach would be a extra param in the @All('sync', {useAll:true}).  That the `expressInstance.all` is used instead of `expressInstance.use`. But i don't know what the impact of that would be through out the framework.

Any advice would be appreciated

**Comment by Aaltuj** [comment]
Oke i've got the authentication working. Appently the passport framework is a global sharing the options that your provided with nestjs/passport.
This next snippet allows you to authenticate the proxy endpoint that relies on the `expressinstance.all()`.

``` typescript
import {Injectable}      from '@nestjs/common';
import {HttpAdapterHost} from '@nestjs/core';
import {Express}         from 'express';
import * as httpProxy    from 'http-proxy';
import * as passport     from 'passport';


@Injectable()
export class AppService {
    private server: Express;


    PROXY_TARGET = 'http://localhost:5984/';
    proxy        = httpProxy.createProxyServer({});


    constructor(private readonly adapterHost: HttpAdapterHost) {
        this.server = adapterHost.httpAdapter.getInstance();
        this.startCouchDbProxyServer(this.PROXY_TARGET, '/sync');

    }

    private startCouchDbProxyServer(proxy_target: string, url: string) {

        this.server.all(`${url}/*`, passport.authenticate('jwt', {session: false}), (request, response) => {
            console.log('Original url: ', request.url);
            console.log('Path to replace: ', request.route.path);
            // Get the path of the proxy handle and replace the astrix
            const path  = request.route.path.replace('*', '');
            // Rewrite url to remove the path from the original path
            request.url = request.url.replace(new RegExp(path), '');
            console.log('Target url', proxy_target + request.url);


            this.proxy.web(request, response, {
                target: proxy_target
            });

        });
    }

}
```

**Comment by anees042** [comment]
> Yep - confirmed as working - I will close it.
> 
> ```
> @Injectable()
> export class AppService {
>   constructor(private readonly loggerFactoryService: LoggerFactoryService, private readonly httpAdapterHost: HttpAdapterHost) {
>     const proxy = Server.createProxyServer()
> 
>     const expressInstance = this.httpAdapterHost.httpAdapter.getInstance()
> 
>     expressInstance.all("*", function(req, res) {
>       proxy.web(req, res, {
>         changeOrigin: true,
>         target: "https://kibana.test.com:443"
>       })
>     })
>   }
> }
> ```
> 
> Thanks.
> 
> I suppose there isn't much more we can do here, so feel free to close this now - I have my workaround that works well.

How you injected HttpAdapterHost?

Nest can't resolve dependencies of the AppService (?). Please make sure that the argument at index [0] is available in the AppModule context
