### ISSUE TITLE
response.redirect does not work when using Fastify adapter

### ISSUE THREAD

**Issue by albertsgrc** [nestjs/nest#2360]
## Describe the regression

```typescript
@Get()
redirect(@Res() res) {
  res.redirect("/target");
}
```

Hitting such a handler does not trigger a redirect to `/target` when using the Fastify adapter, instead, it replies with an empty 200 OK response.

## Input Code

Add this handler

```typescript
  @Get('redirect')
  redirect(@Res() res) {
      res.redirect('/');
  }
```

to the `src/cats/cats.controller.ts` controller inside the `sample/10-fastify` sample. Start the server and hit the browser with the url `http://localhost:3000/cats/redirect`.

## Expected behavior/code

Hitting `http://localhost:3000/cats/redirect` should change the url to `http://localhost:3000/`.

## Environment
<pre><code>
Nest version: 5.7.4 -> 6.3.1

For Tooling issues:
- Node version: 11.6.0
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
Could you look at this issue https://github.com/nestjs/nest/issues/1978?

**Comment by albertsgrc** [comment]
I guess I didn't search thoroughly enough, thank you Kamil
