### ISSUE TITLE
Ts error on prod build with graphql

### ISSUE THREAD

**Issue by prakashchokalingam** [nestjs/nest#2375]
## Bug Report
I am getting the following errors while performing `npm run start:prod`

```
node_modules/apollo-server-express/dist/ApolloServer.d.ts:1:8 - error TS1192: Module '"myproject/node_modules/@types/express/index"' has no default export.

1 import express from 'express';
         ~~~~~~~

node_modules/apollo-server-express/dist/ApolloServer.d.ts:2:8 - error TS1192: Module '"myproject/node_modules/@types/cors/index"' has no default export.

2 import corsMiddleware from 'cors';
```

## Expected behavior
build succeeds

## Environment

<pre><code>
[System Information]
OS Version     : macOS Mojave
NodeJS Version : v10.15.3
NPM Version    : 6.4.1

[Nest Information]
platform-express version : 6.0.0
mongoose version         : 6.1.2
graphql version          : 6.2.4
common version           : 6.0.0
core version             : 6.0.0

Others:
"apollo-server-express": "^2.6.2"
</code></pre>

**Comment by kamilmysliwiec** [comment]
Set `allowSyntheticDefaultImports` to `true` in your `tsconfig.json` https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by prakashchokalingam** [comment]
Thanks @kamilmysliwiec
