### ISSUE TITLE
TypeORM Entity fails silently

### ISSUE THREAD

**Issue by mschuttt** [nestjs/nest#2377]
## Current behavior
NestJS just fails silently using TypeORM

## Input Code
**app.module.ts**
```
@Module({
  controllers: [AppController],
  providers: [AppService],
  imports: [TypeOrmModule.forRoot({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      username: 'user',
      password: 'secret',
      database: 'db',
      synchronize: true,
      entities: [__dirname + '/**/*.entity{.ts,.js}']
    }),
    TodoModule
  ],
})
export class AppModule {}
```

**todo.module.ts**
```
@Module({
  imports: [TypeOrmModule.forFeature([Todo])],
  providers: [TodoService],
  controllers: [TodoController]
export class TodoModule {}
})
```

## Expected behavior
There should be some sort of error (timeout etc.)
When I shutdown my DB instance the process just times out without any message
When I startup my DB again the connection works, but when I insert the todo entity it fails again without any message (process starts and immediately stops without any message at all!)

## Environment
<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: v10.15.0
- Platform:  Linux Ubuntu
</code></pre>

**Comment by ttrevorr** [comment]
Why was this closed? What was the resolution?

**Comment by sunnylqm** [comment]
might because you used custom logger and disabled built in logger
