### ISSUE TITLE
Wrong grpc options are passed to client constructor which causes it to fail.

### ISSUE THREAD

**Issue by matthewlilley** [nestjs/nest#2381]
Version of nest: latest
Third party libraries grpc.

If credentials (combined in my case), are included GrpcClientOptions, they're automatically passed along as the third "options" argument of the grpc client constructor, which causes it to blow up with the message "TypeError: Channel options must be an object with string keys and integer or string values".

I temporarily fixed this for myself by firstly saving the computed credentials to a const, and then deleting credentials from the GrpcClientOptions as can be seen here:

https://github.com/matthewlilley/nest/commit/ae449bbb08a993fdea3d1c3c54524afcbbfbede0

As the credentials themselves are passed as a 2nd option to the grpc client constructor, which can be seen below, there's no reason for them to be in the options object. The options object should only contain string keys and string/integer values, but now is polluted with an object, and this is the reason that error is thrown.

https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.d.ts#L1059

**Comment by matthewlilley** [comment]
Updated with more information.

**Comment by kamilmysliwiec** [comment]
Fixed in 6.3.2 :) Thanks for reporting!

**Comment by matthewlilley** [comment]
@kamilmysliwiec You're more than welcome, and great work getting that out so quickly. It was my first time playing around with Nest, and aside from that little hiccup, solid.
