### ISSUE TITLE
Empty reply from the server

### ISSUE THREAD

**Issue by focux** [nestjs/nest#2383]
## Current behavior
When I start the server, everything work as expected. The problem comes after doing several concurrent requests (~80 requests in a short period of time) to the server. It stops working and the only answer you receive from all the endpoints is (after waiting around 1 minute) `Empty reply from the server`.

I didn't receive any error in the console. I was trying to track down the issue and it seems that the controllers are catching the requests, it gets stuck in every TypeORM query. Also, I enabled the TypeORM's debug mode, and I don't see any query being logged when the server isn't responding. It's SO weird, I don't know what else to do, I've trying to solve it with no luck for two days.

When you restart the server, it starts working again until he receives several concurrent requests.

## Input Code

Hard to replicate, I'd have to set up a DB.

## Expected behavior
Do not receive an `Empty reply from the server` when doing an HTTP request to an endpoint or at least, receive an error.

## Environment

<pre><code>
Nest environment:
    "@nestjs/common": "^6.3.1",
    "@nestjs/core": "^6.3.1",
    "@nestjs/passport": "^6.1.0",
    "@nestjs/platform-express": "^6.3.1",
    "@nestjs/platform-socket.io": "^6.3.1",
    "@nestjs/swagger": "^3.0.2",
    "@nestjs/typeorm": "^6.1.2",
    "@nestjs/websockets": "^6.3.1",

 
For Tooling issues:
- Node version: v10.15.1
- Platform:  Linux

**Comment by kamilmysliwiec** [comment]
It sounds rather like a typeorm issue(?). We can't help without the repo that reproduces the issue.

**Comment by focux** [comment]
I tracked the bug and It was related to @AfterLoad() TypeORM listener, I already opened an issue there. Thank you.
