### ISSUE TITLE
Nest microservices request-response not working as documented

### ISSUE THREAD

**Issue by rhlsthrm** [nestjs/nest#2384]
## Current behavior
I am following the documented instructions to create a NATS microservice. I am trying to get a simple request-response example built, but I am running into an issue where the app gets into an infinite loop by responding to its own requests forever.

## Input Code
Repo created to show issue: https://github.com/rhlsthrm/nest-nats-req-reply-issue

## Expected behavior
Request from test-script should receive response from Nest. Nest should properly read and log message data.

## Environment

<pre><code>
Nest version: 6.3.1

 
For Tooling issues:
- Node version: v10.16.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
> where the app gets into an infinite loop by responding to its own requests forever

You have an infinite loop in your code (dispatching the same message over and over). See `sample` directory (in this repo) for basic examples.

**Comment by rhlsthrm** [comment]
The infinite loop is coming from the client sending the message defined in the message pattern, as per the documentation states (here)[https://docs.nestjs.com/microservices/basics]: 
> The send() method takes two arguments, pattern and payload. The pattern has to be equal to this one defined in the @MessagePattern() decorator while payload is a message that we want to transmit to another microservice.

If the pattern is equal to the one defined in the @MessagePattern() decorator, how could it not infinite loop? Do you know of an end to end example of NATS working with the request-response pattern?

**Comment by johnbiundo** [comment]
@rhlsthrm There's a complete end to end example here: https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-1-p3
