### ISSUE TITLE
Problem with hotreload and typeorm - Unexpected token

### ISSUE THREAD

**Issue by adrianDY** [nestjs/nest#2389]
## Current behavior
I cloned the typescript repo tutorial and followed it completely. I also created a few of my own entities and it works without errors.
I then proceeded to introduce hotreloading with webpack based on the tutorial on the NestJs site.
When running `npm run webpack` it completes successfully.
When running `npm run start` I am presented with the following error

```
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
``` 

## Input Code
ormconfig.json
```json
{
  "type": "mysql",
  "host": "127.0.0.1",
  "port": 3306,
  "username": "root",
  "password": "root",
  "database": "test",
  "entities": ["src/**/*.entity{.ts,.js}"],
  "synchronize": false,
  "logging": true,
  "cache": true
}

pacakge.json (scripts)
```
{
    "build": "tsc -p tsconfig.build.json",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "startOld": "ts-node -r tsconfig-paths/register src/main.ts",
    "start": "node dist/server",
    "webpack": "webpack --config webpack.config.js",
    "start:dev": "concurrently --handle-input \"wait-on dist/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\" ",
    "start:debug": "nodemon --config nodemon-debug.json",
    "prestart:prod": "rimraf dist && npm run build",
    "start:prod": "node dist/main.js",
    "lint": "tslint -p tsconfig.json -c tslint.json",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  }

## Expected behavior
Running `npm run webpack` and then `npm run start` should not result in errors

## Possible Solution
I searched the internet and could not find anyone with the same issue, but I did find something similar. Someone suggested to change the `ormconfig.json` file and replace 
`  "entities": ["src/**/*.entity{.ts,.js}"]`
with
`  "entities": ["dist/**/*.entity{.ts,.js}"]`
but then I was . presented with a new error stating that typeorm could not find the entities

## Environment
Nest version: 5

 
For Tooling issues:
- Node version: 12
- Platform:  Mac

**Comment by victorbrun** [comment]
I get the same compilation error when the main.js from the ./dist folder is started

**Comment by adrianDY** [comment]
@victorbrun Thanks for the tip.
Unfortunately any direct reference to the entity files result in a new (better?) error

```
[Nest] 37152   - 2019-06-14 21:33   [ExceptionHandler] No repository for "User" was found. Looks like this entity is not registered in current "default" connection? +1ms
RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
```

**Comment by kamilmysliwiec** [comment]
```
SyntaxError: Unexpected token {
```
This error usually means that your compiled app is trying to load original `.ts` files (before transpilation). Put entities directly into `entities: []` array or fix your entities path (so it loads only `.js` files)

**Comment by appliaison** [comment]
Changing 

`"entities": ["./src/**/*.entity.ts", "./dist/**/*.entity.js"]`

to

`"entities": ["dist/**/*.entity{.ts,.js}"]`

fixes this issue.

**Comment by hassankn** [comment]
> Changing
> 
> `"entities": ["./src/**/*.entity.ts", "./dist/**/*.entity.js"]`
> 
> to
> 
> `"entities": ["dist/**/*.entity{.ts,.js}"]`
> 
> fixes this issue.

Thanks! That fixes the issue

**Comment by gintsgints** [comment]
Only way, wich works all cases (compiled, debug, typescript, typescript debug, tests) was import entities manually, one by one and put as array in config.

**Comment by kamilmysliwiec** [comment]
That's what I would suggest too. We updated the docs with manually imported entities.

**Comment by d337** [comment]
> Changing
> 
> `"entities": ["./src/**/*.entity.ts", "./dist/**/*.entity.js"]`
> 
> to
> 
> `"entities": ["dist/**/*.entity{.ts,.js}"]`
> 
> fixes this issue.

The above solution is really great but there is still one problem. When you are in development you generally don't use ```dist``` because it's for production.
Now, when you remove ```dist``` you won't have access to ```dist/entities/..``` so, for that in place better option is to use ```env``` like below:

**Comment by d337** [comment]
> Changing
> 
> `"entities": ["./src/**/*.entity.ts", "./dist/**/*.entity.js"]`
> 
> to
> 
> `"entities": ["dist/**/*.entity{.ts,.js}"]`
> 
> fixes this issue.

The above solution is really great but there is still one problem. When you are in development you generally don't use ```dist``` because it's for production.
Now, when you remove ```dist``` you won't have access to ```dist/entities/..``` or at least when you're using ```ts-node``` you probably don't use ```dist``` for development purpose. For that in place better option is to use ```env``` like below:


Step-1: Create two different ```env``` files

**1. .env.production**
```
# TypeORM
ENTITY_PATH=dist/entities/*.entity{.ts,.js}
MIGRATION_PATH=dist/migrations/*.{.ts,.js}
```
**2. .env.development**
```
# TypeORM
ENTITY_PATH=src/entities/*.entity{.ts,.js}
MIGRATION_PATH=src/migrations/*.{.ts,.js}
```

Step-2: Configure TypeORM options:
```
...
      entities: [this.get('ENTITY_PATH')],
      migrations: [this.get('MIGRATION_PATH')], 
...

```

Step-3: Add ```NODE_ENV``` in your scripts like,
```
...
"start:dev": "NODE_ENV=development ts-node main.ts",
"start:prod": "NODE_ENV=production node main.js",
...
```

P.S.: For using ```env``` configurations follow this [doc](https://github.com/nestjs/docs.nestjs.com/blob/master/content/techniques/configuration.md)

**Comment by thozh** [comment]
> Changing
> 
> `"entities": ["./src/**/*.entity.ts", "./dist/**/*.entity.js"]`
> 
> to
> 
> `"entities": ["dist/**/*.entity{.ts,.js}"]`
> 
> fixes this issue.

Thank you so much ! It worked for me.
