### ISSUE TITLE
How to override global ValidationPipe in controller?

### ISSUE THREAD

**Issue by sandeepsuvit** [nestjs/nest#2390]
I have a code in which i have applied a global validation pipe in ```main.ts``` file like so:
```typessctipt
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  // Enable global validation pipe
  app.useGlobalPipes(new ValidationPipe({
    whitelist: true
  }));
}
```

Now in one of my controller i wanted to skip some properties of a DTO in a patch request

```typescript
    @Patch(':id')
    // Override the pipe
    @UsePipes(new ValidationPipe({ skipMissingProperties: true}))
    updateProject(@Body() dataToUpdate: UpdateProjectDTO) {
        return dataToUpdate;
    }
```

This is my DTO:

```typescript
export class UpdateProjectDTO {
    @IsNotEmpty()
    projectType: string;

    @IsNotEmpty()
    projectDescription: string;
}
````

I wanted to ignore ```projectDescription``` if its not submitted as part of the request. But in this case my global pipe is taking precedence which doesn't have ```skipMissingProperties``` defined as part of its property. Is there a solution to override the global pipe?

**Comment by indiejoseph** [comment]
+1

**Comment by underfin** [comment]
```
export class UpdateProjectDTO {
    @IsNotEmpty()
    projectType: string;

    @IsOptional()
    projectDescription: string;
}
```

**Comment by sandeepsuvit** [comment]
> ```
> export class UpdateProjectDTO {
>     @IsNotEmpty()
>     projectType: string;
> 
>     @IsOptional()
>     projectDescription: string;
> }
> ```
> 
> it`s work for you.

Hi @underfin thanks for your reply. But in my project the issue is both ```projectType``` and  ```projectDescription``` are mandatory in case of the schema design. I was looking for an option of partially updating the data once its created. If i don't include the global pipe in the ```main.ts``` file my usecase works. But i was wondering if there is an option of overriding the global pipe at the controller function level.

**Comment by underfin** [comment]
```
public createContext<T extends any[], R extends any[]>(
    instance: Controller,
    callback: (...args: any[]) => any,
    metadataKey: string,
    contextId = STATIC_CONTEXT,
    inquirerId?: string,
  ): R {
    const globalMetadata =
      this.getGlobalMetadata && this.getGlobalMetadata<T>();
    const classMetadata = this.reflectClassMetadata<T>(instance, metadataKey);
    const methodMetadata = this.reflectMethodMetadata<T>(callback, metadataKey);
    return [
      ...this.createConcreteContext<T, R>(
        globalMetadata || ([] as T),
        contextId,
        inquirerId,
      ),
      ...this.createConcreteContext<T, R>(classMetadata, contextId, inquirerId),
      ...this.createConcreteContext<T, R>(
        methodMetadata,
        contextId,
        inquirerId,
      ),
    ] as R;
  }
```
It`s not support for override global pipe on now.
It maybe can be a feature for this.

**Comment by sandeepsuvit** [comment]
> methodMetadata

Oh i see. Thanks for the clarification @underfin 
I guess in that case i'll have to manually have a repetitive validation pipe on all my controller methods.

**Comment by kamilmysliwiec** [comment]
You can create a new pipe that inherits from `ValidationPipe`. This pipe would read the handler metadata using `Reflector` (see example https://docs.nestjs.com/guards#reflection) and based on this metadata, would use `skipMissingProperties`.

**Comment by sandeepsuvit** [comment]
> You can create a new pipe that inherits from `ValidationPipe`. This pipe would read the handler metadata using `Reflector` (see example https://docs.nestjs.com/guards#reflection) and based on this metadata, would use `skipMissingProperties`.

Hi @kamilmysliwiec,
Thanks a lot for your reply, but sorry i didn't actually follow what you were trying to explain based on the reflection url that you provided above. Were you asking me to do something like passing additional properties to the validate method after implementing the PipeTransform like so:

```typescript
import { ArgumentMetadata, BadRequestException, PipeTransform } from '@nestjs/common';
import { plainToClass } from 'class-transformer';
import { validate } from 'class-validator';

export class CustomValidation implements PipeTransform<any> {
    async transform(value: any, { metatype }: ArgumentMetadata) {
        if (!metatype || !this.toValidate(metatype)) {
            return value;
        }
        const object = plainToClass(metatype, value);
        // Pass `skipMissingProperties` as part of the custom validation
        const errors = await validate(object, { skipMissingProperties: true });
        if (errors.length > 0) {
            throw new BadRequestException('Validation failed');
        }
        return value;
    }

    private toValidate(metatype: Function): boolean {
        const types: Function[] = [String, Boolean, Number, Array, Object];
        return !types.includes(metatype);
    }
}

.....

    @Patch(':id')
    @UsePipes(new CustomValidation())
    updateProject(@Body() dataToUpdate: UpdateProjectDTO) {
        return dataToUpdate;
    }

```
If this is what i have to do then the global validation pipe still take precedence. Could you please point out on what i am doing wrong here.

**Comment by jeffwcx** [comment]
I override ValidationOptions By this way. @sandeepsuvit 

```ts
// extends global pipe
import { ValidationPipe, ArgumentMetadata, Injectable } from '@nestjs/common';
import { REWRITE_VALIDATION_OPTIONS } from '../decorators/constants';

@Injectable()
export class MyValidationPipe extends ValidationPipe {
  async transform(value: any, metadata: ArgumentMetadata) {
    const options = Reflect.getMetadata(REWRITE_VALIDATION_OPTIONS, metadata.metatype);
    let originOptions;
    if (options) {
      originOptions = Object.assign({}, this.validatorOptions);
      this.validatorOptions = Object.assign(this.validatorOptions, options);
    }
    try {
      const result = super.transform(value, metadata);
      if (originOptions) {
        this.validatorOptions = originOptions;
      }
      return result;
    } catch (error) {
      throw error;
    }
  }
}
```
I have to change the  `this.validatorOptions`, cause
https://github.com/nestjs/nest/blob/65f44cf0193326ad7c25f6375e2e312b877182b9/packages/common/pipes/validation.pipe.ts#L76

If add a options param in transform would be better
https://github.com/nestjs/nest/blob/65f44cf0193326ad7c25f6375e2e312b877182b9/packages/common/pipes/validation.pipe.ts#L63

```ts
public async transform(value: any, metadata: ArgumentMetadata, options?: ValidatorOptions = {}) {
// ...
const errors = await classValidator.validate(entity, Object.assign({}, this.validatorOptions, options));
// ...
}
```

And in Dto
```ts
@RewriteValidationOptions({ skipMissingProperties: true })
export class UpdateTemplateDto {
    @IsString()
    value: string;
}
```
Decorator is simple
```ts
import { REWRITE_VALIDATION_OPTIONS } from './constants';
import { ValidatorOptions } from '@nestjs/common/interfaces/external/validator-options.interface';
import { SetMetadata } from '@nestjs/common';

export function RewriteValidationOptions(options: ValidatorOptions) {
  return SetMetadata(REWRITE_VALIDATION_OPTIONS, options);
}
```
