### ISSUE TITLE
No way to control route order across controllers

### ISSUE THREAD

**Issue by itslenny** [nestjs/nest#2394]
I have two controllers that have overlapping routes. `item-inventory` is a sub-concern of store so the route is `store/item-inventory`, but I also have a get store route `store/:storeId`. 

They are conflicting and `store/item-inventory` is hitting `store/:storeId` with a store id of `item-inventory`. 

If these routes were both defined in the same controller file / class I could control the order, but I want to have them in separate files to keep things organized. However, there doesn't seem to be any way to control the order that controllers load.

in my module I have:

```
  controllers: [
    StoreItemInventoryController,
    StoreController,
  ],
```

I've tried re-arranging the controllers, but it makes no difference.

This is the basic setup of the two controllers for reference:

```
@Controller('store')
export class StoreController {
  @Get(':storeId')
  getStores(@Param('storeId') storeId: string) {
    // ... /store/item-inventory hits this route
  }
}
```

```
@Controller('store/item-inventory')
export class StoreItemInventoryController {

  @Get()
  getInventoryItems() {
    // ... this route is impossible to hit because of the store controller
  }
}
```

**Comment by kamilmysliwiec** [comment]
Well, the order of controllers should matter. Could you provide a small repo which reproduces your issue?
