### ISSUE TITLE
Middleware gets stuck

### ISSUE THREAD

**Issue by uvero** [nestjs/nest#2405]
## Current behavior
Any path that fits a middleware doesn't get a response, and doesn't even "hit" the middleware `use` function

## Input Code

After doing a bit of toying-around, I found that paths that don't fit the middleware path don't cause a problem, but those who do get stuck without a response and the `use` function doesn't even get called. I started with a more complicated middleware (trying to serve built angular app as static frontend and `/api/**` paths as API), but to break it down I tried to changed to simplest example, the one found on the middleware documentation. My code now looks like this:

`application.module.ts`:
```ts
import { Module, RequestMethod, MiddlewareConsumer, NestModule } from '@nestjs/common';
import { AppController } from './app.controller';
import { LoggerMiddleware } from './logger.middleware';

@Module({
    imports: [],
    controllers: [AppController],
    providers: [LoggerMiddleware],
})
export class AppModule implements NestModule {
    constructor(private readonly connection: Connection) {

    }

    configure(consumer: MiddlewareConsumer): void {
        consumer.apply(LoggerMiddleware).forRoutes(
            {
                method: RequestMethod.ALL,
                path: '/log/**'
            }
        );
                console.log('configured');
    }
}
```

`logger.middleware.ts`:
```ts
import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response } from 'express';

@Injectable()
export class LoggerMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: Function) {
    console.log('Request...');
    next();
  }
}
```

As mentioned, when a path doesn't fit the `/log/**` pattern, the app works as expected, but when it does, there is no response (and hte browser's request gets timed out), and nothing is even logged (which means the `use` function doesn't get used).

## Environment
```

[System Information]
OS Version     : Linux 4.15
NodeJS Version : v10.15.3
YARN Version    : 1.16.0
[Nest Information]
platform-express version : 6.3.1
typeorm version          : 6.1.2
common version           : 6.3.1
core version             : 6.3.1
cli version              : 6.5.0
```
I'm using [GitPod](http://gitpod.io) for developing & running.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue. Also, adding `LoggerMiddleware` as a provider is not required
