### ISSUE TITLE
NATS request-response not working

### ISSUE THREAD

**Issue by rhlsthrm** [nestjs/nest#2408]
## Current behavior
Previously reported similar issue here: https://github.com/nestjs/nest/issues/2384, but I am re-reporting with a stripped-down example that I believe should be working.

Steps to reproduce (following docs: https://docs.nestjs.com/microservices/basics):
- Run local NATS server
- Run simple Nest app to respond to requests following message pattern by returning a value
- Send request from another client to server with message pattern
- See that response never shows up on the client, and NATS server logs show that the message was never published

The following code and instructions available in this test repo: https://github.com/rhlsthrm/nest-nats-req-reply-issue

## Input Code
https://github.com/rhlsthrm/nest-nats-req-reply-issue

Relevant controller snippet:
```
@Controller()
export class AppController {
  constructor(
    private readonly appService: AppService,
  ) {}

  @MessagePattern({ cmd: 'hello' })
  getHello(data: any) {
    // this logs correct data input
    console.log('data: ', data);
    return this.appService.getHello();
  }
}
```

## Expected behavior
I expect to be able to receive a response on my client that is sending the request.

## Possible Solution
I can see in my NATS server logs that the Nest app correctly sets up the subscription, but the response never gets published. This is a working example of a response to a request-response pattern: https://github.com/rhlsthrm/nest-nats-req-reply-issue/blob/master/test-nats-reply.ts.

My inkling is that the replyTo isn't being parsed out of the message properly, so it isn't publishing responses. It's unclear from looking at the Nest code where this is being set up.

I'm happy to provide more information and test things out. This is currently blocking my production release of a Nest app, so I really need some support (also willing to donate/tip anyone who is willing to help support me on this).

## Environment
Nest version: 6.3.1

**Comment by rhlsthrm** [comment]
OK so thanks to someone on StackOverflow I found that it's required to add the `id` to the message in order for Nest to reply properly. I believe this should be better documented but that is a separate issue:

```ts
const reply = await nc.request("hello", 500, JSON.stringify({ data: "Hello", id: "myid" }));
console.log({ reply });
```

StackOverflow: https://stackoverflow.com/questions/56549704/nestjs-nats-request-response/56599032?noredirect=1#comment99946255_56599032

**Comment by johnbiundo** [comment]
This topic is discussed extensively here.  https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-1-p3

Hopefully it helps!
