### ISSUE TITLE
Provide `ApplicationConfig` as core injectable

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#2410]
## Is your feature request related to a problem? Please describe.
With `@nestjs/terminus` I would like to get the global prefix of the `@nestjs/core/application-config` class. Unfortunately, as far as I know there is no way to get that information inside an application context.

## Describe the solution you'd like
Possible solutions I could imagine:

- Expose `ApplicationConfig` as core injectable
- Create a new core provider with token `GLOBAL_PREFIX`

## What is the motivation / use case for changing the behavior?
See nestjs/terminus#228

**Comment by kamilmysliwiec** [comment]
Let's do this:
```
Expose ApplicationConfig as core injectable
```

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec PR is already up ;) #2412
