### ISSUE TITLE
Production build doesn't contain all files necessary

### ISSUE THREAD

**Issue by PeterDavidCarter** [nestjs/nest#2411]
## Current behavior

When running a build of my nx project, the nest api file created (main.js) is missing at least one dependency (tslib). The build works if I manually copy in the package.json file onto the productions server and npm install from there, but this shouldn't be happening, as all the required files should be there. The angular project in the same nx repo works without issue.

## Expected behavior

I expect the dist folder to contain everything I need for a production build.
## Environment
<pre><code>
Nest version: X.Y.Z

 6.2.4
For Tooling issues:
- Node version: XX  
10.16.0
- Platform:  
Ubuntu 18.04 (also observed on 19.04).
Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the nx repo https://github.com/nrwl/nx
