### ISSUE TITLE
[Miroservice] EventPattern using RabbitMQ transport

### ISSUE THREAD

**Issue by NatriumTrioksida** [nestjs/nest#2413]
Does ```EventPattern``` using RabbitMQ transport support pubsub/one-to-many communication? 

While RabbitMQ and the underlying library (amqplib) support this (by using exchange and bind queue), it seems the current implementation is simply a request-response (RPC) both for ```MessagePattern``` and ```EventPattern```. What I expect for ```EventPattern``` was something like pubsub, client emit an event and _all_ connecting servers/subscribers receive the event. Current behavior for ```EventPattern``` when there are multiple servers is that the emitted events are load balanced to the servers.

**Comment by kamilmysliwiec** [comment]
It's slightly hard to align the transport strategy to the requirements of every system. For your use-case, you could basically create a custom transport strategy that inherits from the existing `Rmq` one. We're working on the docs for this feature here https://github.com/nestjs/docs.nestjs.com/issues/113
