### ISSUE TITLE
Nestjs microservices with php laravel

### ISSUE THREAD

**Issue by hxdef2517** [nestjs/nest#2414]
Is there any way to send commands to laravel redis using nest microservices as well as receive commands from laravel in nest? 

```
this.client.send({ cmd: 'channel_name' }, { foo: 'bar' }).subscribe({
            next: php_response => {
                res.status(HttpStatus.OK).json(php_response);
            },
            error: error => {
                res.status(HttpStatus.INTERNAL_SERVER_ERROR).json(error);
            }
        });
```

How can I specify channel ?

**Comment by kamilmysliwiec** [comment]
We're working on the docs here https://github.com/nestjs/docs.nestjs.com/issues/406

**Comment by kamilmysliwiec** [comment]
https://trilon.io/blog/using-nestjs-microservices-with-laravel
