### ISSUE TITLE
isNil Type Guard

### ISSUE THREAD

**Issue by CanKattwinkel** [nestjs/nest#2418]
Is there any particular reason for `isNil` not having a type guard? `isUndefined` on the other side has one.

I've stumbled across it repeatedly because my IDE prefers importing `nest` over `lodash`. Lodash, on the other hand, has a guard. In a project with `strict: true` it is a little annoying. 

https://github.com/nestjs/nest/blob/master/packages/common/utils/shared.utils.ts

**Current:**
```
export const isNil = (obj: any): boolean => isUndefined(obj) || obj === null;
```

**Wanted:**
```
export const isNil = (obj: any):  obj is null | undefined => isUndefined(obj) || obj === null;
```

**Comment by kamilmysliwiec** [comment]
Added in 6.3.2 :) Thanks for reporting!
