### ISSUE TITLE
Unknown authentication strategy "bearer"

### ISSUE THREAD

**Issue by huangdalin-web** [nestjs/nest#2419]
## Current behavior
Unknown authentication strategy "bearer"

## Input Code

```ts
@Controller('cats',)
export class CatsController {
  constructor(){}
  @Get()
  @UseGuards(AuthGuard("bearer"))
  findAll(): string {
    return 'This action returns all cats';
  }
}
```

**Comment by Aciderr** [comment]
I had this problem because I didn't add HttpStrategy to providers in my module

**Comment by Destreyf** [comment]
@huangdalin-web If your Authentication is setup by a module, you may need to make sure you have your strategy as a Provider in the module decorator:

```ts
@Module({
  imports: [
    JwtModule.register(),
    PassportModule.register({ defaultStrategy: 'jwt', session: true }),
  ],
  controllers: [AuthController],
  exports: [PassportModule, AuthService],
  providers: [AuthService, JwtStrategy]
})
export class AuthModule {
}
```

I had to add my JwtStrategy to the `providers`, you will have to reference whatever strategy you've defined/used.
