### ISSUE TITLE
NATS Connect Options : User attribute missing

### ISSUE THREAD

**Issue by walterspieler** [nestjs/nest#2426]
## Current behavior
The option available on https://github.com/nats-io/nats.js#connect-options isn't available in @Client options.

## Input Code

```ts
@Client({
    transport: Transport.NATS,
    options: {
      url: env.nats,
      user: env.usernats,
      pass: env.passnats,
    },
  })
```

## Expected behavior

Typescript shouldn't yell since user is a nats valid option.

## Possible Solution

Add `user: string;` in NatsOptions  interface `@nestjs/microservices/interfaces/microservice-configuration.interface.d.ts`

```ts
export interface NatsOptions {
    transport?: Transport.NATS;
    options?: {
        url?: string;
        name?: string;
        user?: string;
        pass?: string;
        maxReconnectAttempts?: number;
        reconnectTimeWait?: number;
        servers?: string[];
        reconnect?: boolean;
        pedantic?: boolean;
        tls?: any;
        queue?: string;
    };
}
```
## Environment

<pre><code>
Nest version: 6.5.0

 
For Tooling issues:
- Node version: 12.0.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 6.3.2 :) Thanks for reporting!
