### ISSUE TITLE
How support cluster with `microservices`

### ISSUE THREAD

**Issue by underfin** [nestjs/nest#2436]
When there's a lot of traffic on the site,How to do with `nest` `microservices`.As a background,  the cluster with `microservices` will be useful(The `dubbo` and `springClound` is mature `microservices` solution on java.),I hope get some suggestions 
with this.If we dont support this, maybe its a very important feature.

**Comment by kamilmysliwiec** [comment]
You can use Kubernetes for that (instead of Spring Cloud). Also, more sophisticated messaging platforms give you load-balancing, clustering, etc (e.g. NATS, RabbitMQ). For HTTP micro-services, you can simply use either nginx or ingress (k8s).
