### ISSUE TITLE
Proposal: AWS Specific Microservices (Lambda/Kinesis)

### ISSUE THREAD

**Issue by duro** [nestjs/nest#2442]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
The ability to create microservices and clients which use some of the AWS native services such as Kinesis and Lambda (possibly SNS and SQS in the future).

## Teachability, Documentation, Adoption, Migration Strategy
I'm seeing this as a Transports which can be setup to mount to the handler of a Lambda, and are aware of the event structure of either incoming Kinesis events, or directly invoked Lambdas, as well as Clients that can be setup to communicate via the AWS SDK with these two different services.

## What is the motivation / use case for changing the behavior?
We run Nest in a serverless architecture. This has been working well for us when exposing the service via API Gateway. I have so far been using a custom built Kinesis "transport" for sending  events to Kinesis, but the more I have read into Nest microservices, the more I feel this could be built into the nest microservices module.

Also, when doing Lambda <-> Lambda communication, this should happen not via API Gateway, but via direct invokes of the function using the AWS SDK. This seem like it would be a great for for an additional transport/client in Nest.

## Build Out
I am very interested in taking on the build out of this, and submitting it as a PR. That said, I am new to developing on the internals of Nest, so any others willing to co-sponsor or assist me in navigating this contribution, please chime in. I'm going to need some help to keep this moving.

## Feedback?
I'd love to hear feedback from the community on whether this seems like something others would use or is a good idea. If it seems like something that doesn't make sense for the framework itself, I'd love to hear how building this out as an add-on integration would work. I haven't seen many examples of people extending the microservice layer as a third-part module. All feedback and suggestion welcome.

**Comment by kamilmysliwiec** [comment]
Hi @duro,

We're willing to provide even more and more micro-service transport strategies over time. Both Lambda/Kinesis integrations would be very welcome. If you want to contribute, you can simply follow this guide https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md. Unfortunately, we cannot give you anyone that would assist you in building this functionality - everyone is incredibly busy lately. PRs are welcome though, so feel free to try at least!

**Comment by Can-Sahin** [comment]
I would like to achieve similar things as I said on my comment. I'm currently not needing it but when I do and if it still hasn't been implemented I will make sure I help with pull request. But at the moment again as I said in the comment microservices are something I couldnt understand deeply enough to contribute. 

See -> https://github.com/nestjs/docs.nestjs.com/issues/98#issuecomment-478486168

**Comment by TreeMan360** [comment]
@kamilmysliwiec have PRs been closed as this in progress or would you still be looking for contributions?

**Comment by kamilmysliwiec** [comment]
PRs are welcome @TreeMan360!

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/3960
