### ISSUE TITLE
not inject correct instance when use useClass

### ISSUE THREAD

**Issue by metauro** [nestjs/nest#2445]
## Current behavior
I want to use multiple jwt strategy, and inject config to JwtService, but in this case the admin-session module always get the user-session config instance

## Input Code
https://codesandbox.io/s/nest-typescript-starter-lgpb1?fontsize=14

## Environment

<pre><code>
Nest version: 6.0.4
 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Fixed in 6.4.0

**Comment by metauro** [comment]
@kamilmysliwiec it works 👍 , thanks a lot, could you tell me what reason causes this problem？I tried to read the source code, but my level is limited, thanks again.
