### ISSUE TITLE
SSR with ReactDOMServer.renderToString

### ISSUE THREAD

**Issue by badpenguin** [nestjs/nest#2454]
Can i generate SSR react's page using ReactDOMServer.renderToString from a controller?
I wish to replace a custom SSR project using express with NestJS.
I tried a little but i got an HTTP 503 message with the error
```
{"path":"/test2/","name":null,"message":"Cannot read property 'createElement' of undefined"}
```
when rendering a simple HelloWorld component

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
