### ISSUE TITLE
Transform event shape

### ISSUE THREAD

**Issue by goodoldneon** [nestjs/nest#2455]
## Feature Request

Add ability to transform MQ events to conform to Nest's event shape requirement.

For example, Nest expects the event data to be in the `data` property. However, in our platform event data is in the `payload` property.

Here's a repo demonstrating my issue:

https://github.com/goodoldneon/nestjs-rmq-shape

## Is your feature request related to a problem? Please describe.
When I send a RabbitMQ message with a `payload` property, that property is lost and the message data is `undefined`.

In method `handleEvent()` in `packages/microservices/server/server.ts`, `packet.data` passed.

## Describe the solution you'd like
A way to inject a transformer to change event shape right when an event is received. For my specific problem, I want to rename property `payload` to `data`.

## Teachability, Documentation, Adoption, Migration Strategy
Not sure.

## What is the motivation / use case for changing the behavior?
Our entire platform uses an event shape that isn't compatible with Nest. We want to gradually migrate our services to Nest, but the Nest services won't have compatible messages with our legacy services.

Nest is awesome and we want to migrate to it ❤️! This is our only hurdle so far.

**Comment by kamilmysliwiec** [comment]
It sounds like a useful feature, a way to use a custom serializer (which implements both `serialize` and `deserialize` methods)

**Comment by goodoldneon** [comment]
@kamilmysliwiec, how do you envision its usage? Would `serialize` and `deserialize` property be added to `MicroserviceOptions`? So maybe it'd look something like this:

```ts
function serialize(event) {
  return {
    pattern: event.type,
    data: event.payload,
  }
}

function deserialize(event) {
  return {
    type: event.pattern,
    payload: event.data,
  }
}

app.connectMicroservice({
  transport: Transport.RMQ,
  options: {
    urls: ['amqp://hip:hop@localhost:5672'],
    queue: 'test',
  },
  serialize,
  deserialize,
});
```

**Comment by kamilmysliwiec** [comment]
This feature has been added in Nest 6.6.0. Let's track the documentation update here https://github.com/nestjs/docs.nestjs.com/issues/626
