### ISSUE TITLE
no error message within provider-constructors

### ISSUE THREAD

**Issue by renehauck** [nestjs/nest#2456]
## Bug Report
If an error in a service within the constructor is thrown when starting a NestJs application, you don't get an error message, the application simply terminates without feedback.
The same happens when I try to load a provider into the constructor, which I did not export or import into the respective module.
## Current behavior
Any error in a provider will not be displayed while the application starts (within the method NestFactory.create). You only get the error message "error Command failed with exit code 1" but no additional information.
## Input Code

```ts
// only "error Command failed with exit code 1."
@Injectable()
export class MyService {
    constructor() {
        throw new Error("ups");
    }

// only "error Command failed with exit code 1."
@Injectable()
export class MyService {
    constructor(private readonly notExportedService: NotExportedService) {

    }
```

## Expected behavior

a more detailed error message :blush: 
## Environment

<pre><code>
Nest version: 6.3.2

 
For Tooling issues:
- Node version: v10.15.1
- Platform:  Linux

Others:

</code></pre>
Thank you

**Comment by kamilmysliwiec** [comment]
Could you please provide a minimal repository which reproduces your issue?

**Comment by renehauck** [comment]
I generated an app with "nest g app" and tried to reproduce the error, but as a "pure" nest application I get an error message.
Then I added the module "@nestjs/platform-express" and bang, the error is swallowed again. :smiley: 

the repository: https://github.com/renehauck/nest-con-error

without @nestjs/platform-express
```typescript
async function bootstrap() {
  const ExpressApp = express();
   const app = await NestFactory.create(AppModule);
  // const app: NestExpressApplication = await NestFactory.create(AppModule, new ExpressAdapter(ExpressApp), {
  //   logger: false
  // });
  await app.listen(3000);
}
bootstrap();
```
![Bildschirmfoto vom 2019-06-27 09-14-18](https://user-images.githubusercontent.com/3898144/60245135-38755d00-98bc-11e9-8cd8-e281ee94d10a.png)

with @nestjs/platform-express
```typescript
async function bootstrap() {
  const ExpressApp = express();
  // const app = await NestFactory.create(AppModule);
  const app: NestExpressApplication = await NestFactory.create(AppModule, new ExpressAdapter(ExpressApp), {
    logger: false
  });
  await app.listen(3000);
}
bootstrap();

```
![Bildschirmfoto vom 2019-06-27 09-17-43](https://user-images.githubusercontent.com/3898144/60245225-6fe40980-98bc-11e9-9fbd-5dc2bf9d6296.png)

Thank you

**Comment by kamilmysliwiec** [comment]
@renehauck because you disabled logger:
```typescript
const app: NestExpressApplication = await NestFactory.create(AppModule, new ExpressAdapter(ExpressApp), {
  logger: false
});
```
remove `{ logger: false }` configuration and it will work fine

**Comment by renehauck** [comment]
Sorry for the stupid question. :man_facepalming:
