### ISSUE TITLE
Generate common REST API endpoint

### ISSUE THREAD

**Issue by hrandika** [nestjs/nest#2458]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Rather than manually create all the endpoint for a given entity we can generate common endpoints like GET,POST,DELETE etc to reduce boilerplate code.

## Teachability, Documentation, Adoption, Migration Strategy
Ex : @Contoller to @RestController that will create all endpoints.

## What is the motivation / use case for changing the behavior?
Highly inspired by Spring data rest. https://spring.io/projects/spring-data-rest#overview
I have a demonstrated video so you get an idea.
https://www.youtube.com/watch?v=NdorOTjXZhw
Happy to contribute if someone can point directions.

**Comment by BrunnerLivio** [comment]
Thank you for submitting this issue.

There are no plans to add this as core functionality, but there is a well-written library out there called [nestjsx/crud](https://github.com/nestjsx/crud). 
You can also check out [this](https://youtu.be/jo-1EUxMmxc?t=2451) talk from Kamil, the creator of this framework. It solves the problem you are describing using mixings.
