### ISSUE TITLE
Allow overriding of template engine specific options

### ISSUE THREAD

**Issue by woutrbe** [nestjs/nest#2461]
## Is your feature request related to a problem? Please describe.
While working with Pug templates, I was trying to using their extend layout feature. You can either extend a layout by it's relative path `extends index`, or use absolute paths `extends /index`.
If you prefer to keep your views structured in a certain way, using relative paths quickly becomes very messy. I.e. `extends ../../index`. So using absolute paths is a preferred way.

## Describe the solution you'd like
Pug (https://pugjs.org/api/reference.html) has a `basedir` option, that allows you to set the root of all inclusions. 

## Teachability, Documentation, Adoption, Migration Strategy
While we already have a `.setViewEngine(engine: string)` and `.setBaseViewsDir(path: string)`. I would either want to see a new method, or allow options to be passed to `.setViewEngine(engine: string)`, so it becomes `.setViewEngine(engine: string, options: any)`.

## What is the motivation / use case for changing the behavior?
Allow users to specify template engine options.

**Comment by kamilmysliwiec** [comment]
Have you looked at this issue? https://stackoverflow.com/questions/16525362/how-do-you-set-jade-basedir-option-in-an-express-app-the-basedir-option-is-r

You can access the underlying express instance using `getHttpAdapter().getInstance()`: https://docs.nestjs.com/faq/http-adapter

**Comment by woutrbe** [comment]
@kamilmysliwiec I did know how to do it in Express, just couldn't figure out how to integrate it with Nest.

Accessing the express instance did the trick. This might have to be clarified in the documentation under MVC - https://docs.nestjs.com/techniques/mvc
```
const express = server.getHttpAdapter().getInstance();
express.locals.basedir = join(__dirname, 'templates');
```

**Comment by kamilmysliwiec** [comment]
We're constantly working on the documentation improvements. Thanks for reporting! :)
