### ISSUE TITLE
REPL for NestJS

### ISSUE THREAD

**Issue by kowsheek** [nestjs/nest#2466]
## Feature Request
Hey friends, I've been working on a large NestJS project for the financial technology space over the last few months. In the process, I felt I had the need for a REPL environment (so I could stop going back and forth between database and application views).

## Describe the solution you'd like

NestJS was missing this REPL interface, so I created one called [inestjs](https://github.com/kowsheek/inestjs). Of course, it's really simple, but I have some ideas on adding some features similar to the Ruby on Rails and Moleculer REPL.

Here's a little snippet of my using the REPL:

![image](https://user-images.githubusercontent.com/164881/60303189-c6c10180-9903-11e9-8e82-d5caee075c42.png)

## Teachability, Documentation, Adoption, Migration Strategy
I'd love to hear if something like this is in the works from @kamilmysliwiec and the team (I was only able to find one issue vaguely related to it).

Furthermore, additional feature ideas and thoughts are welcome. Feel free to add to the discussion here or [in this issue on the project repository](https://github.com/kowsheek/inestjs/issues/1).

**Comment by kamilmysliwiec** [comment]
Hey @kowsheek,
We don't plan to provide such a feature under the official organization (not enough bandwidth in relation to usefulness). I'd love to see the community packages space growing though so if you're interested, you can consider joining either nestjx or nestjs-community. cc @zMotivat0r @bashleigh

**Comment by jmcdo29** [comment]
Those who fine this issue can track its progress here: https://github.com/nestjs/nest/pull/9684
