### ISSUE TITLE
How to set default value for datetime in nest ORM column for mysql

### ISSUE THREAD

**Issue by mymmoonoa** [nestjs/nest#2473]
Does anyone know how to set default datetime value for nest ORM mysql

I tried 1. `@Column({ type: 'datetime', default: () =>  new Date()}) `.
which give me error `QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Sat Jun 29 2019 18:21:11 GMT+0800 (CST)' at line 1`

2. `@Column({ type: 'datetime', default: () => '2019-06-29'}) `
3. `@Column({ type: 'datetime', default: 'CURRENT_TIMESTAMP'})`

All failed. 
I will be very appreciated for any help.

**Comment by Insidexa** [comment]
[TypeORM issues](https://github.com/typeorm/typeorm/issues)
