### ISSUE TITLE
NestJS Cloud Deployement

### ISSUE THREAD

**Issue by halimpuckjava** [nestjs/nest#2474]
hi

i finish to devlope a simple server with nestjs & mysql, but when try to deploy in cloud i not found any tutorial or doc to help me.

**Comment by owl1n** [comment]
Hi, @halimpuckjava 

You just need build && start your application on your server via `npm run build` and `npm run start:prod` commands. Your application will be available on `:3000` port.

There are some more cases that are more suitable:

1) Run command `npm run start:prod` via pm2 package ([link here](http://pm2.keymetrics.io/)). Install nginx on your server - `sudo apt install nginx`, create or edit nginx configuration in `/etc/nginx/conf.d/default.conf`. Paste the code below into this file.

```
server {
    listen               80 default_server;
    server_name          localhost;

    location / {
        proxy_pass       http://localhost:3000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
}
```

Restart nginx service and enjoy it via `http://<your server ip here>`

2) Second case - docker. In GitHub repositories you can find few projects with nestjs and docker implementation. User `docker nestjs starter` query in github search form
