### ISSUE TITLE
MaxListenersExceededWarning when add custom log to interceptor

### ISSUE THREAD

**Issue by nvuhung** [nestjs/nest#2477]
## Bug Report
Add custom log service to interceptor and see the error: MaxListenersExceededWarning
## Current behavior
After declared the AppLogService (I use winston to log) into LoggingInterceptor, the error message display: 
`(node:51317) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit`
And the interceptor not working

## Input Code

```ts
@Injectable()
export class LoggingInterceptor implements NestInterceptor {
  private readonly logger: AppLogService = new AppLogService(
    LoggingInterceptor.name,
  );

  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    this.logger.log('Before...');

    const now = Date.now();
    return next
      .handle()
      .pipe(
        tap(() => this.logger.log(`After... ${Date.now() - now}ms`)),
      );
  }
}
```

## Expected behavior

Can use AppLogService in LoggingInterceptor

## Environment

<pre><code>
Nest version: 6.2.4

 
For Tooling issues:
- Node version: v10.16.0
- Platform: Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by nvuhung** [comment]
Thanks for your response. I have known the root cause. That is the problem of winston library. I remove it and the code work well. I will close this issue
