### ISSUE TITLE
What about Clustering?

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#248]
Sorry if i missed it in the documentation: Is clustering/multi-threading supported? Is it possible to cluster only certain modules? And if yes, can the child processes easily communicate with each other/the master process(e.g. by use of Redis)?

Despite optimizing performance for heavy algorithms this is very important for the use of Socket.io: Having a lot of users connected to the same namespace will require to cluster them on the cpu cores. If doing so, it requires:

1. Handle [sticky sessions](https://github.com/wzrdtales/socket-io-sticky-session) - It is important that all connections always go to the same child process since Socket.io will always use http on start and may keep a http long polling connection on older browsers.
2. [Redis Adapter](https://github.com/socketio/socket.io-redis)(or [MongoDB](https://github.com/losandes/socket.io-mongodb)) - By use of an socket.io adapter a child process can emit to a whole namespace without worries. Even when the clients are connected to different child processes, just call emit as you would do normally.

Clustering across multiple machines(servers) requires a load balancer with sticky sessions for websockets. But the machines should have the ability to communicate with each other, e.g. by use of Redis. Is this what you mean by microservices? (I don't get this part of the documentation)

**Comment by kamilmysliwiec** [comment]
Hi @MickL!
It's possible to cluster nest application in the same way as an express app. There's no feature to cluster only certain modules (you would have to run different app instances). About socket.io - that's true,  you can use `WsAdapter` https://docs.nestjs.com/websockets/adapter
