### ISSUE TITLE
Silent error when injecatble requires itself

### ISSUE THREAD

**Issue by lkostrowski** [nestjs/nest#2481]
## Current behavior

Nest allows injecting service to the same service (recursion happens?).

No errors are printed

Calling any endpoint returns `Error: Couldn't connect to server`

## Input Code
1. Start new nest app with default settings
2. Open AppService
3. Add `constructor(private service: AppService) {}` to AppService

## Expected behavior
Nest console should throw error

## Possible Solution
Nest console should throw error

## Environment

<pre><code>
Nest version: X.Y.Z
` "@nestjs/core": "^6.3.2",`
 
For Tooling issues:
- Node version: XX  `v10.15.3`
- Platform:  Mac

Others:
</pre>
</code>

Is injecting service to itself valid operation?

**Comment by kamilmysliwiec** [comment]
> Is injecting service to itself valid operation?

It's not, there is actually no reason to support this feature. What would you like to accomplish?

**Comment by lkostrowski** [comment]
Nothing. I did this by mistake and was quite surprised how outcome looks like. When I figured out, I thought error should be thrown.
I asked question by-the-way, I propose to just disallow this operation (bug/request)

**Comment by kamilmysliwiec** [comment]
Got it. Thanks for reporting! :) Fixed in 6.4.0

**Comment by lkostrowski** [comment]
Cool, thanks!
