### ISSUE TITLE
@UseGuards doesn't work with type-graphql decorator 

### ISSUE THREAD

**Issue by Davis10733** [nestjs/nest#2484]
## Current behavior

I've added @UseGuards in graphql resolver but graphql guard never trigger
## Input Code

```ts
// resolver
import { UseGuards } from '@nestjs/common'
import { Ctx, Query, Resolver } from 'type-graphql'
import { MyContext } from '../../types/myContext'
import { User } from '../entities'
import { GqlAuthGuard } from '../auth/gql.authGuard'

@Resolver()
export class MeResolver {
  @Query(returns => User)
  @UseGuards(new GqlAuthGuard())
  me(@Ctx() ctx: MyContext) {
    return ctx.user
  }
}
```

```ts
// GqlAuthGuard
import {
  ExecutionContext,
  Injectable,
  UnauthorizedException,
} from '@nestjs/common'
import { ExecutionContextHost } from '@nestjs/core/helpers/execution-context-host'
import { GqlExecutionContext } from '@nestjs/graphql'
import { AuthGuard } from '@nestjs/passport'

@Injectable()
export class GqlAuthGuard extends AuthGuard('cognito') {
  canActivate(context: ExecutionContext) {
    // this method never trigger
    const ctx = GqlExecutionContext.create(context)
    const { req } = ctx.getContext()
    return super.canActivate(new ExecutionContextHost([req]))
  }

  handleRequest(err: any, user: any) {
     ....
  }
}
```

## Expected behavior
`canActive` method should be triggered.

## Environment

<pre><code>
Nest version: 6.3.2

 
For Tooling issues:
- Node version: v10.15  
- Platform:  Mac

Others:
Type-Graphql version: 0.17.3

</code></pre>

**Comment by kamilmysliwiec** [comment]
> import { Ctx, Query, Resolver } from 'type-graphql'

You should use decorators exported from `@nestjs/graphql` (`@Query()`, `@Resolver()` etc)

**Comment by Davis10733** [comment]
Cool, That works. Thanks a lot. 
But I'm wondering why ? I thought `type-graphql` is compatible with `nestjs`. It still can generate schema and work well in original way (except guard).

**Comment by kamilmysliwiec** [comment]
> But I'm wondering why ? I thought type-graphql is compatible with nestjs. It still can generate schema and work well in original way (except guard).

It won't inject your dependencies (hence, won't work well). We surely need to add an error message to improve developers experience.

**Comment by Davis10733** [comment]
Got it. Thank you for your nice answer.

**Comment by jelling** [comment]
@kamilmysliwiec just to clarify, are you saying that classes that extend AuthGuard will not be run if the resolver is using the type-graphql resolvers? 

If so, I tried switching to the @nestjs/graphql decorators but they are not a 1:1 replacement. For example, it's @args instead of @arg. Also in my case the schema no longer built.

**Comment by marcus-sa** [comment]
@kamilmysliwiec the errors messages could be a part of https://github.com/nestjs/nest-cli/issues/349

**Comment by marcus-sa** [comment]
@jelling you should be using Nest resolvers regardless. They're not supposed to be compatible.

**Comment by jelling** [comment]
@marcus-sa I trust you're right and I'm willing to do that but want to confirm my understanding of the issue as reworking the graphql schema was not plug-and-play. I.e. nest works with type-graphql up until this point. 

What's the underlying need for all the nest wrapper classes, hooking things into the Nest DI process?
