### ISSUE TITLE
Websocket acknowledgement

### ISSUE THREAD

**Issue by danapier** [nestjs/nest#249]
Does onMessage support the acknowledgement callback?

Example 1:
@SubscribeMessage('events')
onEvent(client, data): WsResponse<any> {
  const event = 'events';
  return { event, data };
}

Example 2:
socket.on('news', (data, callback) => {
  callback(0);
});

**Comment by kamilmysliwiec** [comment]
Hi @danapier,
By default - no, but you can do this easily using `WsAdapter` https://docs.nestjs.com/websockets/adapter

**Comment by anton-g** [comment]
@danapier did you get this working somehow? I've been [trying to implement the same thing myself](https://stackoverflow.com/questions/49612658/socket-io-acknowledgement-in-nest-js/) but can't get it working.

**Comment by AndyGura** [comment]
I wrote this module over nestjs, which do it under the hood so you don't need to call ack callback explicitly, you only need to return value or throw error: https://www.npmjs.com/package/nestjs-socket-handlers-with-ack . Hope it helps
