### ISSUE TITLE
Nest doesn't log failed dependency resolution exception when using custom logger

### ISSUE THREAD

**Issue by caiorcferreira** [nestjs/nest#2497]
## Current behavior
When some dependency can't be resolved by Nest it fails on startup and logs an exception pointing which dependency it could not resolve. However, when a customer logger is set trough `app.useLogger(customLogger)`, and a dependency resolution fails, the app simply crashs and don't log any message.

## Input Code
One can reproduce this behaviour using [this sandbox](https://codesandbox.io/s/custom-logger-bug-3zofy). Change the `useLogger` variable at `main.ts` to see each behaviour.

## Expected behavior
Nest should log the exception and other messages even using the custom logger.

## Possible Solution
It's not clear for me yet what is causing this behaviour.

## Environment

<pre><code>
Nest version: 6.4.0
 
For Tooling issues:
- Node version: locally, Node 10.16.0
- Platform: Mac and Linux

</code></pre>

**Comment by kamilmysliwiec** [comment]
This is how it's supposed to work. If you set a custom logger, it's your responsibility to provide the `error` method and print that error.

**Comment by caiorcferreira** [comment]
The custom logger implements the `LoggerService` interface from `@nestjs/common`, which imposes the implementation of the `error` method. There were some errors in the provided sandbox, although the problem remained the same: the `error` method from the custom logger was never called.

The main issue is not the fact that the error isn't printed using the custom logger, since the dependecy resolution exception probably occurs before the logger is provided. Is that the problem is not logged at all.

Shouldn't Nest log this level of information with any logger instance it has available? It would saved me from hours of debbuging a dependency issue that was never printed even with the custom logger providing an `error` method.

**Comment by kamilmysliwiec** [comment]
> There were some errors in the provided sandbox, although the problem remained the same: the error method from the custom logger was never called.

The error appears in the provided sandbox

**Comment by kamilmysliwiec** [comment]
> Shouldn't Nest log this level of information with any logger instance it has available? It would saved me from hours of debbuging a dependency issue that was never printed even with the custom logger providing an error method.

You explicitly set `logger: false` = no logs. You can just enable/disable it conditionally depending on the environment.

**Comment by caiorcferreira** [comment]
Excellent, removing `{ logger: false }` works. 

But, it only works if I don't pass an options object or an empty object. If I pass `{ logger: true }`, it still doesn't log the exception.  It creates an counter intuitive API. IMHO the options should understand `{ logger: true }` as same as not passing the option. If it can be done and you think it would be useful, I would be glad to help and open an PR.

Besides that, I think it would be a nice addition to the docs show the example with environment resolution, like:
```ts
const options = process.env.NODE_ENV === 'production' ? { logger: false } : {};

const app = await NestFactory.create(ApplicationModule, options);
app.useLogger(app.get(MyLogger));
await app.listen(3000);
```
