### ISSUE TITLE
@types/express and @types/cors have no default export

### ISSUE THREAD

**Issue by MarkNjunge** [nestjs/nest#2502]
## Bug Report
Projects using GraphQL cant be built using `yarn build`

The error seems like it's from apollo-server-express but when I created a minimal project using Typescript and apollo-server-express, the issue doesn't arise.  

The dependencies are the same, as far as I can tell: 
Plain apollo-server-express
```
+-- apollo-server-express@2.7.0-alpha.3
| | `-- @types/express@4.17.0 deduped
| +-- @types/express@4.17.0
| | +-- @types/express-serve-static-core@4.16.7
| |   +-- @types/express-serve-static-core@4.16.7 deduped
+-- express@4.17.1
```
Nest
```
+-- @nestjs/platform-express@6.4.0
| +-- express@4.17.1
| `-- @types/express@4.17.0 deduped
+-- @types/express@4.17.0
| +-- @types/express-serve-static-core@4.16.7
|   +-- @types/express-serve-static-core@4.16.7 deduped
+-- apollo-server-express@2.7.0-alpha.3
| +-- @types/express@4.17.0 deduped
| | |   | +-- spdx-expression-parse@3.0.0 deduped
| | |   `-- spdx-expression-parse@3.0.0
```

## Current behavior
```
λ yarn build
yarn run v1.15.2
warning package.json: No license field
$ tsc -p tsconfig.build.json
node_modules/apollo-server-express/dist/ApolloServer.d.ts:1:8 - error TS1192: Module '"/project/node_modules/@types/express/index"' has no default export.

1 import express from 'express';
         ~~~~~~~

node_modules/apollo-server-express/dist/ApolloServer.d.ts:2:8 - error TS1192: Module '"/project/node_modules/@types/cors/index"' has no default export.

2 import corsMiddleware from 'cors';
         ~~~~~~~~~~~~~~


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Input Code
A new project with GraphQL configured. Up to and including [this section](https://docs.nestjs.com/graphql/quick-start#getting-started) of the documentation.

## Expected behavior
The project builds

## Environment

<pre><code>
Nest-cli version: 6.5.0
@nestjs/common: ^6.4.0
@nestjs/core: ^6.4.0
@nestjs/graphql: ^6.2.4
@nestjs/platform-express: ^6.4.0
 
For Tooling issues:
- Node version: 10.5.3
- Platform:  Windows

</code></pre>

**Comment by kamilmysliwiec** [comment]
It looks like `apollo-server-express` issue. Add `allowSyntheticDefaultImports: true` to your tsconfig.json to fix this issue (compiler options)
