### ISSUE TITLE
Handle stream in controller response

### ISSUE THREAD

**Issue by BenjD90** [nestjs/nest#2504]
## Is your feature request related to a problem? Please describe.
When I want to return a stream to an http client, I have to pipe the stream to the response.

## Describe the solution you'd like
Handle pipe return type for functions in controllers.

## Teachability, Documentation, Adoption, Migration Strategy
Here is an implementation in an other project close to NestJS :
https://github.com/typestack/routing-controllers/blob/4a56d176db77bc081dfcd3d8550e8433b5bc476e/src/driver/express/ExpressDriver.ts#L331

## What is the motivation / use case for changing the behavior?
This could very usefull, and make code easier to read.

Thanks a lot for your support to this good framework :smile:

**Comment by kamilmysliwiec** [comment]
Could you elaborate more on your idea? I'm guessing that you want Nest to handle this:
```
return someFunction;
```
automatically by calling `res.pipe(someFunction)` underneath? If so, keep in mind that Nest aims to stay platform-agnostic which means that we cannot use features that are exclusively available in express (and not available in other libraries, like fastify).

What about just injecting `res` using `@Res()` decorator?
