### ISSUE TITLE
Cant inject dependecy in PipeTransform

### ISSUE THREAD

**Issue by menme95** [nestjs/nest#2513]
## Current behavior
I am trying to inject dependency in a PipeTransform that is used with @UsePipes to validate.
I've been debugging my code and the decorator @UsePipes run when the dependecy (no async) is still undefined. The original dependecy (assert) is resolved later and can be used in the controller.

## Input Code
```ts
@Injectable()
export class JoiValidationPipe implements PipeTransform {
  constructor(private readonly schema: object, private readonly assert) {
  }
```
```ts
constructor(@Inject("Assert") private readonly assert){}
@Post()
  @UsePipes(new JoiValidationPipe(FileSchema, this.assert))
  @UseInterceptors(FileInterceptor("file"))
```

## Expected behavior
I hope this.assert wouldn't be undefined in JoiPipe.

## Environment

<pre><code>
Nest version: 6.5.0

 
For Tooling issues:
- Node version: 8.15.0
- Platform:  Linux

</code></pre>

**Comment by kamilmysliwiec** [comment]
```
constructor(@Inject("Assert") private readonly assert){}
@Post()
  @UsePipes(new JoiValidationPipe(FileSchema, this.assert))
```

You cannot use `this` in this context - this isn't how JavaScript works.

**Comment by menme95** [comment]
But I can't inject the provider directly to the pipe because the constructor expect 2 arguments them... That is why I used 'this.assert' there

**Comment by kamilmysliwiec** [comment]
You can't inject dependencies if you are manually creating an instance of the class (new Class)

**Comment by menme95** [comment]
So ... Aren't there anyway to inject something to the pipe?

**Comment by kamilmysliwiec** [comment]
You have to pass a type into `@UsePipes()` instead of creating an instance on your own (e.g. `@UsePipes(JoiValidationPipe)`. If you want to pass extra params to the `JoiValidationPipe`, you can use mixins.

**Comment by ph55** [comment]
@kamilmysliwiec but there is examples in docs that use new pipe instances:
https://docs.nestjs.com/pipes

```ts
@Post()
@UsePipes(new JoiValidationPipe(createCatSchema))
async create(@Body() createCatDto: CreateCatDto) {
  this.catsService.create(createCatDto);
}

@Injectable()
export class JoiValidationPipe implements PipeTransform {
  constructor(private readonly schema: Object) {}

  transform(value: any, metadata: ArgumentMetadata) {
    const { error } = Joi.validate(value, this.schema);
    if (error) {
      throw new BadRequestException('Validation failed');
    }
    return value;
  }
}
```

**Comment by posei** [comment]
@ph55 you're able to use a newly defined instance the way they have because they aren't injecting any dependencies, it's all defined instances - Like @kamilmysliwiec has said if you'd like to pass in extra params you can go the mixin route and still have DI

**Comment by bhaidar** [comment]
@posei Can you please refer me to an example on using a mixin? Thanks
