### ISSUE TITLE
[BUG] ValidationPipe not working with cat-app example

### ISSUE THREAD

**Issue by workfel** [nestjs/nest#252]
Hi, 

I just start to learn `nestjs` and i have downloaded the example for testing it.
I just want to create an cat with `POST` method `/cats/` and i have a `error 500`.
On the body i put this:
```
{
	"name": "odo",
	"age":"ss",
	"breed": "dd"
}
```
But when i debug the `ValidationPipe` on the `tranform()` method `value` is `undefined`.

Do you know where is the mistake ?

Thanks

**Comment by workfel** [comment]
I found, i missing `app.use(bodyParser.json());` on `server.ts`  !
I seen, you have an commit who remove all `bodyParser`, why do you remove it ? 

Thanks

**Comment by kamilmysliwiec** [comment]
Hi @workfel,
With the latest update (4.3.0) everything should work fine 🙂 Thanks for reporting
