### ISSUE TITLE
NestJS development: clarify names of NPM build tasks

### ISSUE THREAD

**Issue by eropple** [nestjs/nest#2520]
## Is your feature request related to a problem? Please describe.
When trying to get started as a NestJS contributor, the build system is surprising. It's pretty customary to just go `npm run build` when you're trying to build a project, but NestJS's build breaks in unexpected ways (claiming missing symbols, etc.). @BrunnerLivio graciously helped me out by pointing me towards `npm run build:dev`, but even he seemed a little unclear by describing `npm run build` as a "production build". It isn't, though, as it actually relies on `npm run prerelease` to set up the environment for `npm run build` to work.

## Describe the solution you'd like
It seems to me that renaming `build:dev` to `build` would be less surprising (and less discouraging to new contributors). The existing `build` isn't actually sufficient to build the app, so perhaps it'd be better named something like `build:internal` to discourage its use outside of the `publish` build pipeline.

## What is the motivation / use case for changing the behavior?
Well, I've been trying to get a working build environment for about an hour so I could start a branch to contribute a fix to a problem, and if I was a little less focused on getting a solution out there I probably would've given up. Making the on-ramp for new contributors a little easier is always good, yeah? :)

**Comment by kamilmysliwiec** [comment]
I'm fine with any changes that would make the on-ramp easier for everyone. Do you want to create a PR with a proposal that includes what would be the easiest from your standpoint?

Btw, in the future, you should just follow steps listed here:
https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md#development

it should be pretty easy to spin up everything.

**Comment by kamilmysliwiec** [comment]
Just pushed a small update. `npm run build` should be now sufficient to set up a local environment :)
