### ISSUE TITLE
[Question]: What's the status on fastify's FileInterceptor?

### ISSUE THREAD

**Issue by mschuttt** [nestjs/nest#2522]
## Is your feature request related to a problem? Please describe.
What is the status on porting the FileInterceptor and File Upload to fastify? 

## Describe the solution you'd like
File upload as described in the documentation should work with fastify as well

## What is the motivation / use case for changing the behavior?
Fastify Support

**Comment by kamilmysliwiec** [comment]
> File upload as described in the documentation should work with fastify as well

![image](https://user-images.githubusercontent.com/23244943/60828879-e1bd2c80-a1b3-11e9-8cc1-8962418f2491.png)

> What is the status on porting the FileInterceptor and File Upload to fastify?

https://github.com/nestjs/nest/pull/2088
