### ISSUE TITLE
Switching to request-scoped for controllers?

### ISSUE THREAD

**Issue by hardcodet** [nestjs/nest#2524]
## Is your feature request related to a problem? Please describe.

Singleton controllers and services seem do not feel like a good fit for many scenarios. I wonder whether defaulting to requests scope really would be such a bad idea (but I lack the experience to make an educated guess).

## Describe the solution you'd like

I'm only just getting started with Nest (love it, it's great work!), but I already stumbled over various use cases related to singletons. I can't help but wonder whether request-scoped controllers might not be a better default. In the end, I'll always need the user context, I'll always need logging with a lot of context (and I'd also want those loggers in my services), and I wouldn't want to manually inject the request into every controller method and then manually pass everything down the chain.

The docs explicitly discourage from non-singleton controllers, but I wonder whether this really is a problem. Wouldn't the creation of request-scoped controllers and services be a cheap operation (granted they don't do expensive constructor work)?

**Comment by kamilmysliwiec** [comment]
> Singleton controllers and services seem do not feel like a good fit for many scenarios. I wonder whether defaulting to requests scope really would be such a bad idea (but I lack the experience to make an educated guess).

Singletons should cover pretty much 99% scenarios. Request-scoped providers are useful only for some very specific cases, to be honest (and can be simply combined/mixed with static providers when necessary). Actually, request-scoped providers are quite new in Nest, and even though it's a great addition to the core - they weren't even very much demanded by the community (I suppose that still not too many people make use of them). We added them to simplify some more sophisticated scenarios (give an abstraction layer that will simplify testing for instance), but almost nobody needed them so far. For other stuff - we can easily move forward with shared instances. It's very important to keep in mind that Node.js has a different execution model than Java/C# and thus, we don't really have to worry about their problems (thread per request/connection). 

> Wouldn't the creation of request-scoped controllers and services be a cheap operation (granted they don't do expensive constructor work)?

Controllers have a lot of metadata associated with them (like all enhancers, respectively guards, interceptors, pipes, and filters that can also be request-scoped). We do cache lots of things, but it will still have an impact on the overall performance.

>  In the end, I'll always need the user context, I'll always need logging with a lot of context (and I'd also want those loggers in my services), and I wouldn't want to manually inject the request into every controller method and then manually pass everything down the chain.

This is a common practice in Node.js community to attach things to the request object (and it will be also much faster btw). If you prefer request-scoped providers, use them - they also fit great here :) However, there is no plan to move over request-scoped providers as a default scope - this will always be opt-in.

**Comment by hardcodet** [comment]
Thanks for all the context and the super-fast reply! I really appreciate it :)
