### ISSUE TITLE
Webpack only outputting decleration files

### ISSUE THREAD

**Issue by Dilanwizzy** [nestjs/nest#2529]
I am trying to create a server side rendering application through nest but I am facing some issues with the webpack example. 

When I run the webpack example it outputs only decleration files ``app.controller.d.ts``. Now this causes a problem with TypeOrm and I get the error of **No repository for "UserEntity" was found. Looks like this entity is not registered in current "default" connection?**

This is my app.module.ts

```

import { AppController } from './app.controller';
import { AppService } from './app.service';
import { UserModule } from './resolvers/user/user.module';
import { AuthModule } from './auth/auth.module';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Connection } from 'typeorm';
import ormconfig from './ormconfig';
import { join } from 'path';

@Module({
  imports: [
    AuthModule,
    UserModule,
    GraphQLModule.forRoot({
      autoSchemaFile: 'schema.gql',
    }),
    TypeOrmModule.forRoot({
      "type": "mysql",
      "host": "localhost",
      "port": 3306,
      "username": "root",
      "password": "password",
      "database": "db",
      "entities": [join(__dirname, '**/**.entity{.ts,.js}')],
      "synchronize": true
    })
  ],

  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {
  public constructor(private readonly connection: Connection) {}
}
```
If I just run ``npm run start:prod`` this outputs js files aswell along side declaration files. 

I would like to know how would output js or ts files on webpack.

**Comment by kamilmysliwiec** [comment]
If you are using webpack, instead of passing a path here:
```typescript
"entities": [join(__dirname, '**/**.entity{.ts,.js}')],
```
I'd suggest adding entities directly (as references to classes). For instance:
```typescript
entities: [Post, User]
```

**Comment by Dilanwizzy** [comment]
I have tried that and I get cannot find module
