### ISSUE TITLE
passport.use(this) doesn't seem to work in Passport example?

### ISSUE THREAD

**Issue by Zeldaze** [nestjs/nest#253]
I am trying to follow Passport integration example, and using Postman, I am getting unauthorized regardless of JWT token present or not. In fact, since our validation returns true all the time, we should not even see unauthorised at all. 

When I try and console log from within the validateUser function, it appears not even called at all?
e.g. 
  async validateUser(signedUser): Promise<boolean> {
    // put some validation logic here
    // for example query user by id / email / username
    console.log('Validation logic');
    return true;
  }

Can you test with example for passport and let me know if something changed?

**Comment by jpaveggio** [comment]
Hi @Zeldaze. The same thing is happening to me, what was the solution you found? Thank you in advance!
