### ISSUE TITLE
forbidNonWhitelisted does not allow optional properties

### ISSUE THREAD

**Issue by bennyn** [nestjs/nest#2535]
## Bug Report

In my NestJS application I enabled [forbidNonWhitelisted](https://docs.nestjs.com/techniques/validation#stripping-properties). When I now try to do a POST with a DTO that contains an optional property, then my application will complain that the property should not exist.

## Current behavior

My `CreateAccountBody` DTO has an optional property called `passphrase` which is marked with `@ApiModelPropertyOptional()`. When I do a POST request (which contains the "passphrase" property) on my account resource , then my application will return a "HTTP 404 Bad Request" error because "whitelistValidation" fails.

## Input Code

**main.ts**

```ts
app.useGlobalPipes(
  new ValidationPipe({
    forbidNonWhitelisted: true,
    transform: true,
    whitelist: true,
  })
);
```

**CreateAccountBody.ts**

```ts
import {ApiModelProperty, ApiModelPropertyOptional} from '@nestjs/swagger';
import {IsNotEmpty} from 'class-validator';

export class CreateAccountBody {
  @ApiModelProperty()
  @IsNotEmpty()
  apiKey!: string;

  @ApiModelProperty()
  @IsNotEmpty()
  apiSecret!: string;

  @ApiModelProperty()
  @IsNotEmpty()
  label!: string;

  @ApiModelPropertyOptional()
  passphrase?: string;
}
```

**AccountController.ts**

```ts
import {Body, Controller, Post} from '@nestjs/common';
import {ApiResponse} from '@nestjs/swagger';
import {AccountEntity} from './AccountEntity';
import {AccountService} from './AccountService';
import {CreateAccountBody} from './CreateAccountBody';

@Controller('api/v1/account')
export class AccountController {
  constructor(private readonly accountService: AccountService) {}

  @Post()
  @ApiResponse({status: 201, type: AccountEntity})
   post(@Body() body: CreateAccountBody): Promise<AccountEntity> {
    return this.accountService.createAccount(body);
  }
}
```

## Expected behavior
Requests which have optional properties defined should not get rejected.

## Possible Solution

Only requests with properties which are not defined at all in the DTO should be rejected.

## Environment

<pre><code>
Nest version: 6.4.1
</code></pre>

**Comment by jmcdo29** [comment]
I think this is related to the other issue I just commented on #2536, the optional decorator you are currently using is related to the `SwaggerModule`, not `class-validator`, and so you need to use the `@IsOptional()` decorator to show `class-validator` and the `ValidationPipe` that the values are not necessary.

**Comment by bennyn** [comment]
> so you need to use the `@IsOptional()` decorator to show `class-validator` and the `ValidationPipe` that the values are not necessary

You're right! 🎉 I missed that information. It's a game changer! Thanks for your detailed answer and assistance. 😃
