### ISSUE TITLE
The "whitelist" property removes "Query" parameters

### ISSUE THREAD

**Issue by bennyn** [nestjs/nest#2536]
## Bug Report

When I enable the [whitelist](https://docs.nestjs.com/techniques/validation#stripping-properties) option in my app, then all properties of `@Query` parameters get removed.

## Current behavior

When I send a request to `/account?label=something`, then my `query` log statement prints an empty object.

## Input Code

**main.ts**

```ts
app.useGlobalPipes(
  new ValidationPipe({
    transform: true,
    whitelist: true,
  })
);
```

**AccountController.ts**

```ts
import {Controller, Get, Query} from '@nestjs/common';
import {ApiResponse, ApiUseTags} from '@nestjs/swagger';
import {AccountEntity} from './AccountEntity';
import {AccountService} from './AccountService';
import {CreateAccountResponse} from './dto/CreateAccountResponse';
import {FindAccountQuery} from './dto/FindAccountQuery';

@ApiUseTags('account')
@Controller('api/v1/account')
export class AccountController {
  constructor(private readonly accountService: AccountService) {
  }

  @Get()
  @ApiResponse({status: 200, type: CreateAccountResponse, isArray: true})
  get(@Query() query: FindAccountQuery): Promise<CreateAccountResponse[]> {
    console.log('query', query);
    return this.accountService.getAccounts(query);
  }
}
```

**FindAccountQuery.ts**

```ts
import {ApiModelPropertyOptional} from '@nestjs/swagger';

export class FindAccountQuery {
  @ApiModelPropertyOptional()
  label?: string;

  @ApiModelPropertyOptional()
  name?: string;
}
```

## Expected behavior

When I send a request to `/account?label=something`, then my `query` log statement should print an object with a `label` property that is set to `something`.

## Environment

<pre><code>
Nest version: 6.4.1
</code></pre>

**Comment by jmcdo29** [comment]
This looks like the Validation pipe is working as expected, as you do not have you `FindAccountQuery` fields decorated with anything from `class-validator` and therefore the pipe will strip them from the request. If you want them to be optional instead you can use the `@Optional()` decorator and that will keep them from being stripped. The decorator you're currently using is only for Swagger.

**Comment by kamilmysliwiec** [comment]
Thanks @jmcdo29 :)
