### ISSUE TITLE
NATS request/reply with external API not working

### ISSUE THREAD

**Issue by kbrustol** [nestjs/nest#2540]
## Current behavior

Can't have a response when sending a request to an external API (infinite loop).

## Input Code

Request:
```ts
@Controller('startupapp')
export class StartupappController {
    constructor(@Inject('NATS_SERVER') private readonly client: ClientProxy) {}

    @Get('test')
    async test() {
        return this.client.send('test', 'test');
    }
}
```
Reply (C# with nats.net library - https://github.com/nats-io/nats.net):
```cs
EventHandler<MsgHandlerEventArgs> h = (sender, args) =>
{
    if (args.Message.Reply != null)
    {
        c.Publish(args.Message.Reply, Encoding.UTF8.GetBytes("{\"data\":\"test\"}"));
    }
};
```

## Expected behavior

Get response from external API

## Possible Solution

I supposed the payload from C# must have a specific structure to be understandable by NestJS, but can't find which one 

## Environment
<pre><code>
Nest version: 6.5.0

 
For Tooling issues:
- Node version: 10.15.0  
- Platform:  Windows 10
</code></pre>

**Comment by kbrustol** [comment]
It seems that id generate by client-nats is needed into the response: 

https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-nats.ts
```ts
public async handleMessage(
    channel: string,
    message: ReadPacket & Partial<PacketId>,
    client: Client,
    replyTo: string,
  ) {
    if (isUndefined(message.id)) {
      return this.handleEvent(channel, message);
    }
    const publish = this.getPublisher(client, replyTo, message.id);
    const handler = this.getHandlerByPattern(channel);
    if (!handler) {
      const status = 'error';
      return publish({ id: message.id, status, err: NO_MESSAGE_HANDLER });
    }
    const response$ = this.transformToObservable(
      await handler(message.data),
    ) as Observable<any>;
    response$ && this.send(response$, publish);
  }
```

When message.id is undefined, handleMessage() returns 'this.handleEvent':

https://github.com/nestjs/nest/blob/master/packages/microservices/server/server.ts
```ts
  public async handleEvent(pattern: string, packet: ReadPacket): Promise<any> {
    const handler = this.getHandlerByPattern(pattern);
    if (!handler) {
      return this.logger.error(NO_EVENT_HANDLER);
    }
    const resultOrStream = await handler(packet.data);
    if (this.isObservable(resultOrStream)) {
      (resultOrStream.pipe(publish()) as ConnectableObservable<any>).connect();
    }
  }
```

In this case, 'this.isObservable(resultOrStream)' return false, so nothing happen.

Maybe I'm wrong, I test and make a return later.

**Comment by kbrustol** [comment]
I monitor logs output on NATS server to see what happen.

The first one is req/rep using NATS inside NestJS. The second one is when reply comes from an external API. It seems that something is missing around observable.

```
->> [PUB foo _INBOX.8I5VJ2LAQ3UPAJ6MDPJG3A.8I5VJ2LAQ3UPAJ6MDPJGKS 75]
->> MSG_PAYLOAD: [{"pattern":"foo","data":"test","id":"84779d3a-5ed5-4806-8a8a-e55274fbc6c6"}]
<<- [MSG foo 2 _INBOX.8I5VJ2LAQ3UPAJ6MDPJG3A.8I5VJ2LAQ3UPAJ6MDPJGKS 75]
->> [PUB _INBOX.8I5VJ2LAQ3UPAJ6MDPJG3A.8I5VJ2LAQ3UPAJ6MDPJGKS 76]
->> MSG_PAYLOAD: [{"err":null,"response":["test"],"id":"84779d3a-5ed5-4806-8a8a-e55274fbc6c6"}]
<<- [MSG _INBOX.8I5VJ2LAQ3UPAJ6MDPJG3A.8I5VJ2LAQ3UPAJ6MDPJGKS 2 76]
```

```
->> [PUB games.findAll _INBOX.D7WKCZLMMGCI0YS7FCP58T.D7WKCZLMMGCI0YS7FCP5YK 85]
->> MSG_PAYLOAD: [{"pattern":"games.findAll","data":"test","id":"a8e26fce-b23a-4d1c-9bf1-c244cbe1399b"}]
<<- [MSG games.findAll 2 _INBOX.D7WKCZLMMGCI0YS7FCP58T.D7WKCZLMMGCI0YS7FCP5YK 85]
->> [PUB _INBOX.D7WKCZLMMGCI0YS7FCP58T.D7WKCZLMMGCI0YS7FCP5YK 76]
->> MSG_PAYLOAD: [{"err":null,"response":["test"],"id":"a8e26fce-b23a-4d1c-9bf1-c244cbe1399b"}]
<<- [MSG _INBOX.D7WKCZLMMGCI0YS7FCP58T.D7WKCZLMMGCI0YS7FCP5YK 2 76]
->> [PUB _INBOX.D7WKCZLMMGCI0YS7FCP58T.D7WKCZLMMGCI0YS7FCP5YK 63]
->> MSG_PAYLOAD: [{"isDisposed":true,"id":"a8e26fce-b23a-4d1c-9bf1-c244cbe1399b"}]
<<- [MSG _INBOX.D7WKCZLMMGCI0YS7FCP58T.D7WKCZLMMGCI0YS7FCP5YK 2 63]
```

Sending another publish with 'isDisposed' to true and the request id do the trick.

**Comment by izio38** [comment]
#2905

**Comment by kamilmysliwiec** [comment]
I recommend reading this article https://trilon.io/blog/using-nestjs-microservices-with-laravel

It shows what structure Nest uses for messages + how to interact with Nest microservices from external services written in different languages.

**Comment by johnbiundo** [comment]
Extensive discussion here that should help: https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-1-p3
