### ISSUE TITLE
Allow injectable middleware to be used on static asset paths when a global prefix is present

### ISSUE THREAD

**Issue by tristan957** [nestjs/nest#2549]
## Current behavior
When using a global prefix, static assets do not sit behind the global prefix. When applying injectable middlewares in the AppModule.configure function, the middlewares only apply to routes behind the global prefix.

## Expected behavior
Be able to use injectable middleware to protect static asset paths when a global prefix is in use.

Use case: Protecting static content

**Comment by tristan957** [comment]
Right now I have to workaround using a functional middleware and calling app.use in index.ts

**Comment by kamilmysliwiec** [comment]
Could you please show your current implementation?

**Comment by tristan957** [comment]
@kamilmysliwiec I will leave a partial implementation here. I am currently too busy to leave an entire example.

```ts
// index.ts

bootstrap() {
  const app = new NestApplication<ExpressAdapter>();
  app.useGlobalPrefix("/api/v1");
  app.useStaticAssets("./assets", { path: "/assets");
  app.run(8080);
}
```
```ts
export default class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(MyMiddleware).forRoutes({ path: "assets" });
}
```

In this configuration, requests going to the static assets will never be interrupted my the middleware. Instead the middleware will only apply to "/api/v1/assets" instead of "/assets"
