### ISSUE TITLE
What about nested routers?

### ISSUE THREAD

**Issue by gelito** [nestjs/nest#256]
Hi all, 

I'm starting with NextJS (it looks awesome, great job!) but I have a doubt.

I see twice the documentation, but I don't see anything about nested routers. How can I do it??

Something like (/cats/:shomecat/dogs/).

I see that I can do it if in the dogsController:
@Controller('cats/:hash/dogs')

But, what about the possibility to nested routers?? Import the dogsModule inside the catsModule and avoid the 'cats/:hash/dogs'.

A reference/example on pure Javascript + Express:
http://katieleonard.ca/blog/2016/nested-routes-with-expressjs/

**Comment by shekohex** [comment]
I think we already discussing this in #255 
check this out.

**Comment by gelito** [comment]
Thanks @shekohex it's the same! Sorry, I close this! ;-)
