### ISSUE TITLE
How to throw/handle errors in middleware?

### ISSUE THREAD

**Issue by Swatinem** [nestjs/nest#2563]
## Feature Request

In standard express, any middleware can call `next` with an optional error, as per the normal node-js callback conventions.

However, at least the `NestMiddleware` types do not mention this possibility, nor do the *middleware* docs.

https://github.com/nestjs/nest/blob/525e642286a8e8ca2d3c550a95bdf2efdf97c039/packages/common/interfaces/middleware/nest-middleware.interface.ts#L2

## Is your feature request related to a problem? Please describe.

When using `throw` inside of a `NestMiddleware`, the error is not handled **at all**. The error is not logged or returned, it is swallowed and the request does not terminate.

Also, when using `next(new Error('foobar'))`, the error is propagated correctly to my `APP_FILTER`, so I can log it, but the request is still not terminated and runs into a timeout.

## Describe the solution you'd like

* Make it possible to pass an error to `next` for a callback-style api
* Optionally, catch errors in case `use` is an async function that returns a promise. This just makes it nicer so that apps don’t need to wrap everything in try/catch themselves.

## Teachability, Documentation, Adoption, Migration Strategy

The current *Middleware* docs do not mention error handling / throwing at all. They should.

## What is the motivation / use case for changing the behavior?

A middleware, just like any other part of your code can throw unexpected (async) script errors…
There should *always* be a way to at least log those errors and make sure that requests terminate properly.

**Comment by kamilmysliwiec** [comment]
> When using throw inside of a NestMiddleware, the error is not handled at all. The error is not logged or returned, it is swallowed and the request does not terminate.

Please, provide a minimal repository which reproduces your issue.

**Comment by Swatinem** [comment]
> Please, provide a minimal repository which reproduces your issue.

Hm, I could not exactly reproduce this, but here you go:
https://github.com/Swatinem/nest-error-repro/commit/22a82faa705f84622ba56943526a28cd4a50ed66

Now that I implemented this case from scratch, I noticed that I `return` the error from the Exception Filter, as suggested here: https://docs.nestjs.com/graphql/tooling#exception-filters

Since our whole app is based on `@nestjs/graphql`, and doing a `return new GraphQLError(message)` in the Exception Filter, I thought this was the way to go. Seems like this does not work correctly when throwing inside of Middleware (which we use together with a Guard for authentication…).

**Comment by Swatinem** [comment]
So maybe this is just a misunderstanding or misleading documentation about the difference in Error Handling when the error originates inside a graphql resolver vs when the error originates outside the graphql layer?

**Comment by kamilmysliwiec** [comment]
Returning an error is enough if the Filter is for GraphQL resolver. However, in your case, exception comes from the middleware which is either express or fastify mechanism (that runs outside of Apollo GraphQL scope). In this case, you have to send a response manually (as in the normal express/fastify app).

**Comment by Swatinem** [comment]
That definitely makes sense.
Is there an example of how I can get this distinction out of the `ArgumentsHost`?

**Comment by kamilmysliwiec** [comment]
So far, you can only compare types of arguments (request != root), but we're working on the feature that will make it easier https://github.com/nestjs/nest/pull/2493
