### ISSUE TITLE
AnyFilesInterceptor missing from index.ts

### ISSUE THREAD

**Issue by gabriellupu** [nestjs/nest#2565]
## Current behavior
Multer interceptors index file doesn't export `AnyFilesInterceptor`

## Input Code
[packages/platform-express/multer/interceptors/index.ts](https://github.com/Samox/nest/blob/b25754da3f0eef344bdff6e4f7c793b11aa2fd13/packages/platform-express/multer/interceptors/index.ts)
```ts
export * from './file-fields.interceptor';
export * from './file.interceptor';
export * from './files.interceptor';
```

## Expected behavior
multer interceptors index should export `AnyFilesInterceptor`

## Possible Solution
```ts
export * from './file-fields.interceptor';
export * from './file.interceptor';
export * from './files.interceptor';
export * from './any-files.interceptor';
```

## Environment

<pre><code>
Nest version: 6.5.0

**Comment by kamilmysliwiec** [comment]
Fixed in 6.5.3 :)
