### ISSUE TITLE
Capture error GRPC 14 UNAVAILABLE service unavaible

### ISSUE THREAD

**Issue by david23539** [nestjs/nest#2570]
Hello My name is David:
I am developing una app web con Nest and microservice by grpc.
In first moment, i don´t have a server grpc, only client and get error 14 UNAVAILBLE. Ok, I want to control this error.
I don´t want send the error 500 Internal Server.
How could I do it, with my own exception?
Thanks and sorry for my English

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by david23539** [comment]
ok, sorry
