### ISSUE TITLE
Support for KOA 2

### ISSUE THREAD

**Issue by nhhockeyplayer** [nestjs/nest#2572]
## Feature Request
Support for KOA 2

## Is your feature request related to a problem? Please describe.

NO

## Describe the solution you'd like

Support for KOA 2

## What is the motivation / use case for changing the behavior?

KOA 2 has been under recognized and leaves express in the dust with its core context object
and its minimal code footprint

KOA 2 should be of the highest priority for server support

Please make this a priority

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/54

**Comment by nhhockeyplayer** [comment]
ok awesome 
I had not known it was abstracted as such to that extent

thats good news
