### ISSUE TITLE
Crashed when using global module

### ISSUE THREAD

**Issue by Diluka** [nestjs/nest#2582]
## Current behavior

crashed when starting

## Input Code

https://github.com/Diluka/nest-issue-2341

## Environment

<pre><code>
Nest version: `>=6.3.1`

 
For Tooling issues:
- Node version: `v10`
- Platform:  `Any`

Others:

</code></pre>

relate to #2341 @maksimkurb

**Comment by kamilmysliwiec** [comment]
Add `exports: [CacheModule]` to `VendorModule`

**Comment by Diluka** [comment]
What? @kamilmysliwiec 

https://github.com/nestjs/nest/blob/fc99ccdb30010c686f9955b05ba3432d30f2d949/packages/common/decorators/modules/global.decorator.ts#L1-L11

> Once imported will be available for all existing modules. 

I imported `CacheModule` in `VendorModule` which has `@Global()`, so the `CacheModule` should be available in other modules like `CoreModule`

This feature was broken since `6.3.1`. And @maksimkurb says this is a bug and tell me to open a new issue. https://github.com/nestjs/nest/issues/2341#issuecomment-511108019

**Comment by KBPatel-Fintech** [comment]
@kamilmysliwiec  ,  please look this issue is after 6.3.0 if we updated to new version my app throws nest can't resolve dependencies error ..we use a same as @Diluka  use in their project global module concept using @Global() decorator  'Once imported will be available for all existing modules.'  it not working anymore after this version update. we use nestjs in very big project we need to solve this issue as soon as possible.

**Comment by kamilmysliwiec** [comment]
> Once imported will be available for all existing modules.

But still, you have to explicitly export providers. Global modules are implicitly available everywhere, but your providers have to be exported. It's not a bug.

> If you have to import the same set of modules everywhere, it can get tedious. Unlike in Nest, Angularproviders are registered in the global scope. Once defined, they're available everywhere. Nest, however, encapsulates providers inside the module scope. You aren't able to use a module's providers elsewhere without first importing the encapsulating module.

https://docs.nestjs.com/modules#global-modules
