### ISSUE TITLE
Retry for microservices rabbitMq

### ISSUE THREAD

**Issue by ZinkevychSergii** [nestjs/nest#2586]
## Feature Request
Custom behavior on exception
## Is your feature request related to a problem? Please describe.
When handler of @EventPattern and @MessagePattern throw an error, i would like to re-queue those message, do ack only on success. 
## Describe the solution you'd like
@nestjs-plus/rabbit already has such feature
`  @RabbitRPC({
    exchange,
    routingKey,
    errorBehavior: MessageHandlerErrorBehavior.REQUEUE,
    queue,
  })`

## What is the motivation / use case for changing the behavior?
At my @EventPattern handler i use quite unstable provider, so sometimes it's return 502 timeout. On this error i do rollback to db and would like to try again

**Comment by kamilmysliwiec** [comment]
You can simply write an interceptor that will retry multiple times :)
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
