### ISSUE TITLE
Authentication PassportModule.register no longer works as explained in documentation

### ISSUE THREAD

**Issue by alfonsocj** [nestjs/nest#2589]
## Bug Report
Defining any property like `defaultStrategy` or `property` on PassportModule (imported in AuthModule) as explained in the documentation https://docs.nestjs.com/techniques/authentication no longer works since version 6.3.1. This is due to the scope fix introduced in 6.3.1 when importing modules.
A workaround is to import `PassportModule.register({defaultStrategy: 'DEFAULT'})` on every module that uses the `AuthGuard`, but that kind of defeats the purpose of having a default strategy.

You can reproduce it using the sample code provided https://github.com/nestjs/nest/tree/master/sample/19-auth-jwt and modifying AuthModule to use `PassportModule.register({property: 'default'}`.

You can see that it still adds the property `user` to the request instead of `default`, unless we import `PassportModule.register({property: 'default'}` directly on AppModule.

<pre><code>
Nest version: 6.3.1

</code></pre>

**Comment by DimosthenisK** [comment]
I thought that this was intended behaviour, as I ran into it about a week ago and everything I found pointed to the fact that I have to include the passport module in every module I wanted to use the guard on.

**Comment by kamilmysliwiec** [comment]
> I thought that this was intended behaviour, as I ran into it about a week ago and everything I found pointed to the fact that I have to include the passport module in every module I wanted to use the guard on.

It's intended behavior. Modules encapsulate providers. If you want to use them, re-export the module from `AuthModule`:

```
exports: [PassporModule]
```
