### ISSUE TITLE
[Question] Additional decorators used with controller parameters

### ISSUE THREAD

**Issue by szkumorowski** [nestjs/nest#259]
Hello,

Is it possible to set custom properties into additional decorated parameters in controller ?
Example:

@Get()
async findAll(@Principal() principal:Principal) { }

Where principal will be built with factory based on current request context ?

I tried to use pipes, but without result. Looks interceptors/middlewares are not proper to go with it.

**Comment by zMotivat0r** [comment]
@szkumorowski I've created PR https://github.com/nestjs/nest/pull/240, waiting for @kamilmysliwiec approve.

**Comment by gelito** [comment]
Kudos to @zMotivat0r

**Comment by mkzaker** [comment]
I need this feature,too.
@kamilmysliwiec approve please.

**Comment by kamilmysliwiec** [comment]
Fantastic job @zMotivat0r. I'm gonna merge this pull request today 🙂
