### ISSUE TITLE
Consider using PostGraphile

### ISSUE THREAD

**Issue by wisekaa03** [nestjs/nest#2591]
## Feature Request
Consider using PostGraphile

## Teachability, Documentation, Adoption, Migration Strategy
See this:
https://www.graphile.org/postgraphile/usage-library/
https://www.graphile.org/postgraphile/postgresql-schema-design/
https://github.com/graphile/examples/tree/master/db

## What is the motivation / use case for changing the behavior?
Postgraphile is much faster than Prisma

**Comment by kamilmysliwiec** [comment]
You can use both with Nest.
