### ISSUE TITLE
Dynamically setting database connection, based on the customer or tenant

### ISSUE THREAD

**Issue by juicycleff** [nestjs/nest#2594]
Is it possible to dynamically set up a type orm connection based on the scope and use it throughout the request for a specific user. With that being said, and if possible, will it scale?

**Comment by kamilmysliwiec** [comment]
It is possible, but you would have to wrap `typeorm` on your own as shown here https://docs.nestjs.com/recipes/sql-typeorm (so without `@nestjs/typeorm`). 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
