### ISSUE TITLE
can not create entity/repository/migration by cli?

### ISSUE THREAD

**Issue by lichnow** [nestjs/nest#2597]
Basically, all frameworks that support ORM can create Entity, Repository and migration (just based on php symfony and doctrine) directly through the built-in CLI, but nest.js can not, which surprised me. Is there any plan? Or can you just write the entity, migration or create it by typeorm's cli?

**Comment by kamilmysliwiec** [comment]
Nest isn't tied to any particular ORM so you can use whatever you need/want to use. For TypeORM, you can simply use their CLI.
