### ISSUE TITLE
please allow ClassSerializerInterceptor to accept transformOptions property

### ISSUE THREAD

**Issue by jasperblues** [nestjs/nest#2608]
## Feature Request

I need to be able to set the `class-transformer` `transformOptions` globally for outgoing requests. 

Specifically I need to omit null values from the response (https://github.com/typestack/class-transformer/pull/284) 

## Describe the solution you'd like

This will entail three changes. 

The constructor for ```ClassSerializerInterceptor``` will accept class transform options as an argument: 

```typescript
@Injectable()
export class ClassSerializerInterceptor implements NestInterceptor {
    constructor(@Inject(REFLECTOR) protected readonly reflector: any,
                readonly serializerOptions: ClassTransformOptions) {
        classTransformer = loadPackage(
          'class-transformer',
          'ClassSerializerInterceptor',
          () => require('class-transformer')
        );
        require('class-transformer');
    }
```

The method to obtain options will use this as the default: 
```typescript
  private getContextOptions(
      context: ExecutionContext,
    ): ClassTransformOptions | undefined {
        return (
          this.reflectSerializeMetadata(context.getHandler()) ||
          this.reflectSerializeMetadata(context.getClass()) ||
          this.serializerOptions
        );
    }
```

`ClassTransformOptions` will have an added `includePolicy` field. 

```typescript
    /**
     * Sets the global policy for which fields will be included. The default is any defined field.
     */
    includePolicy?: Include;
```

## Teachability, Documentation, Adoption, Migration Strategy

Default transform options can be turned on globally as so: 

```typescript
 app.useGlobalInterceptors(
      new ClassSerializerInterceptor(app.get(Reflector), {
          includePolicy: Include.NON_NULL
      }),
      new LogMetricsInterceptor(app.get(LocalStorage)),
      app.get(RequestPersistingInterceptor),
      app.get(ResponseHeadersInterceptor)
    );```

## What is the motivation / use case for changing the behavior?

This change to NestJS will address a specific business need and expand the utility for the community.

**Comment by underfin** [comment]
Why not use `ClassTransformOptions` with `class-transformer`.

**Comment by jasperblues** [comment]
@underfin This is exactly what I am proposing. Currently only incoming requests accept `ClassTransformOptions`. Note that NestJS mirrors the interface.

**Comment by Carlovan** [comment]
I need this as well. Is someone working on it?

**Comment by jasperblues** [comment]
@Carlovan I planned to wait until https://github.com/typestack/class-transformer/pull/284 is approved so that I can add the corresponding property to NestJS' mirrored `ClassTransformOptions'.

**Comment by Carlovan** [comment]
So we should expect a long waiting.. the last activity on class-transformer is on 20th of May :disappointed:

**Comment by jasperblues** [comment]
They can be done separately if it is blocking you. Would you like to prepare the PR, as described above, without the class transformer options? 

Otherwise I'll get to it asap.

**Comment by Carlovan** [comment]
Hi, sorry for the waiting. Thank you but don't worry, I wrote a simple workaround for this. Wait and do things the better way.

**Comment by jasperblues** [comment]
> Hi, sorry for the waiting. Thank you but don't worry, I wrote a simple workaround for this. Wait and do things the better way.

Any chance of reviewing the related pull req @pleerock ?

**Comment by tlan16** [comment]
Hmm, this doesn't look like proceeding. For anyone facing the same issue. With the fix/proposal from @jasperblues , assuming you're using nest.js, you can do this to change pass the `CLASS_SERIALIZER_OPTIONS` to serializer:
```typescript
import { CLASS_SERIALIZER_OPTIONS } from '@nestjs/common/serializer/class-serializer.constants';
import { Include } from 'class-transformer/Include';

@Reflect.metadata(CLASS_SERIALIZER_OPTIONS, { includePolicy: Include.NON_NULL })
@Controller('api/users')
export class UserController {
    public constructor(public readonly userService: UserService) {}

    @Get()
    public async search(@Query() request: UserSearchRequestDto): Promise<UserSearchResposeDto[]> {
        const users = await this.userService.search(request);
        return users.map(user => UserSearchResposeDto.fromModel(user));
    }
}
```
The key part is `@Reflect.metadata`, which will be picked up by `this.reflectSerializeMetadata(context.getClass())`.
