### ISSUE TITLE
When uploading files using FileInterceptor, report 500

### ISSUE THREAD

**Issue by Surile** [nestjs/nest#2614]
## Current behavior

When uploading a file using FileInterceptor, it exceeds 1m and reports 500. However, according to the document modification, the fieldSize of the limits is configured, but the Filed value too long is reported.

## Input Code

```ts
  @Post('upload')
  @UseInterceptors(
    FileInterceptor('file', {
      limits: {
        fieldSize: 2 * 1024 * 1024,
      },
    }),
  )
  async searchImage(@UploadedFile() file, @Body() params) {
    const data = file.buffer.toString('base64');
    return await this.imageService.imageClassfiy(params.token, data);
  }
```

## Expected behavior

Is it possible to limit file size changes?

## Environment

![image](https://user-images.githubusercontent.com/28652894/61506492-dc15e100-aa14-11e9-9afc-59af9157ed4f.png)

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by Surile** [comment]
[image](https://wx1.sinaimg.cn/large/006a7eb0ly1g558aiwh87j318g0rttg0.jpg)
Take this picture as an example, the upload will be 500 errors. I have deployed it on the server and [api](http://119.3.108.116/api/image/upload)  `post` is the api request address.

Below are the field names and parameters：
> token :25.6078e7764ffff7f45947178cc31b717c.315360000.1878885269.282335-16783522
file: image

Open source code is [here](https://github.com/Surile/samle/blob/master/src/server/image/image.controller.ts)

**Comment by SeWaS** [comment]
Hi @Surile 
Maybe the `body-parser` middleware (https://www.npmjs.com/package/body-parser) for express will help you? Seems like we can define a body size limit here:
```javascript
const server = express();
// ...
server.use(bodyParser.json({ limit: '2mb' }));
```

**Comment by Surile** [comment]
@SeWaS  Thank you 。I'll try

**Comment by Surile** [comment]
![image](https://user-images.githubusercontent.com/28652894/61992755-dd8a7d80-b094-11e9-97c2-64bdc40d5f45.png)

@SeWaS I'm sorry. This method is still unsolved.
