### ISSUE TITLE
JSON errors don't trigger global ExceptionFilters

### ISSUE THREAD

**Issue by jasperblues** [nestjs/nest#2615]
## Current behavior
When NestJS is unable to parse incoming JSON payload the resulting error is not routed through the global exception filter. 

## Input Code
1. Create a simple application, with a controller that accepts a post request. 
2. Register a global exception filter. 
3. Post invalid JSON to the controller

## Expected behavior
The error is routed through exception filter. 

## Actual behavior
Nest default error is returned. 

## Possible Solution
I have not investigated the cause. 

## Environment
NestJS 6.5.2

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
