### ISSUE TITLE
Import service dynamically

### ISSUE THREAD

**Issue by frct1** [nestjs/nest#2618]
## Current behavior
When we trying to run module dynamically there is error
`Nest cannot find given element (it does not exist in current context)`

## Input Code

```ts
const mod = await import('../provisioning/*module*/*module*.service').then(m=> m[module+"Service").catch(err=>{
      console.log(err)
      return null;
    });
    const res = this.moduleRef.get(mod, { strict: true}).create();
    return res;
```

## Expected behavior

I've expected that we can import services dynamically by variable and call their methods independently. This solution is more reliable than injecting every module service in every constructor...

## Environment

<pre><code>
Nest version: 6..5.0

 
For Tooling issues:
- Node version: 12.5.0  
- Platform: Windows 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
> This solution is more reliable than injecting every module service in every constructor...

This solution doesn't make sense. Why do you actually want to do something like this?

**Comment by frct1** [comment]
Hello @kamilmysliwiec 
Now i'm moving from monolith system (php) where modules connected through 
```
require($module'.php')
$response = module_Create();
```
In previous system we have handler which call module functions when user open page, for example.
But due to the php troubles we moving to NestJS and that type of module connecting in nest really required

**Comment by kamilmysliwiec** [comment]
> However statically injecting service into certain service isn't good solution cause type of event can be any

What do you mean by `type of event`?

> In previous system we have handler which call module functions when user open page, for example.

Why are you trying to load them (modules) dynamically on demand?

**Comment by frct1** [comment]
So we have user actions like `add, delete, edit` on page. 
When user doing this actions then backend working with related to that module. 
Module name is getting from user database record kinda `user.project = anymodule` then we need to do actions in certain with that `anymodule`.

**Comment by marcus-sa** [comment]
Sounds to me like you should be using a microservice architecture instead.

**Comment by frct1** [comment]
> Sounds to me like you should be using microservices architecture instead.

Uhm, yes. If my solution has no chances i will switch to creating microservice to modules

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
