### ISSUE TITLE
Getting an error while configuring Web socket using Angular(socket.io-client and ngx-socket.io).

### ISSUE THREAD

**Issue by SinghRajKr** [nestjs/nest#2619]
## Bug Report
Getting an error while configuring Web socket using Angular.
## Current behavior
**Error from the Browser console:** 
GET http://localhost:9999/socket.io/?EIO=3&transport=polling&t=MmEdWhZ 429 (Too Many Requests)
**AND**
Access to XMLHttpRequest at 'http://localhost:9999/socket.io/?EIO=3&transport=polling&t=MmEdgXi' from origin 'http://localhost:4200' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials

**Logs from Nestjs Console**
[Nest] 7968   - 7/20/2019, 3:00:34 PM   [ExceptionFilter] GET /socket.io/?EIO=3&transport=polling&t=MmEj_jv  +5349ms
{"statusCode":404,"path":"/socket.io/?EIO=3&transport=polling&t=MmEj_jv","method":"GET","message":{"statusCode":404,"error":"Not Found","message":"Cannot GET /socket.io/?EIO=3&transport=polling&t=MmEj_jv"},"timestamp":"7/20/2019, 3:00:34 PM"}

## Input Code
```ts
import {SubscribeMessage, WebSocketGateway, WebSocketServer, WsResponse,
     OnGatewayConnection, OnGatewayInit, OnGatewayDisconnect} from '@nestjs/websockets';
import { Logger } from '@nestjs/common';
import { Server, Socket } from 'socket.io';

@WebSocketGateway()
export class PostsGateway implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect {
    @WebSocketServer()
    webSocketServer: Server;

    private logger: Logger = new Logger('Socket Server');

    afterInit(server: Server) {
        this.logger.log('Web Socket Initialized');
    }

    handleConnection(client: Socket, ...args: any[]) {
        this.logger.log(`New Client Connected ${client.id}`);
        // client.emit('connection', 'Successfully Connected to Socket Server.');
    }

    @SubscribeMessage('messageToServer')
    handleWelcome(client: Socket, msg: string): WsResponse<string>  {
        // this.webSocketServer.emit('messageToClient', msg);
        return {event: 'messageToClient', data: msg };
    }

    handleDisconnect(client: Socket) {
        this.logger.log(`Client disconnected ${client.id}`);
    }

}
```

## Expected behavior

Others:
I have enabled cors in main.ts
app.enableCors();
</code></pre>

**Comment by SinghRajKr** [comment]
**Following code is working from main.ts**
import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { Logger } from '@nestjs/common';
import * as Socket from 'socket.io';

`async function bootstrap() {
  const logger = new Logger('MY APPLICATION LOGGER');
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  const server = await app.listen(process.env.PORT, process.env.HOST);
  const io = Socket(server);
  logger.log(`Server is listening at ${process.env.HOST}:${process.env.PORT}`);
  io.on('connection', (socket) => {
    logger.log(`SOCKET CONNECTION ESTABLISHED`);
    socket.on('disconnect', () => {
      logger.log('User Disconnected');
    });
    socket.on('messageToServer', msg => {
      logger.log(`Message To Server ${msg}`);
      io.emit('messageToClient', msg);
    });
  });
}`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
