### ISSUE TITLE
Injection not working in tests with Injection Scopes

### ISSUE THREAD

**Issue by xxluke** [nestjs/nest#2639]
## Current behavior
After setting a service to the scope "Request", tests which use this service will fail with a message like `TypeError: Cannot read property 'getHello' of undefined`.

## Input Code
Example repo: https://github.com/xxluke/nestjs-typescript-starter

I changed the code of the service to this:
```ts
@Injectable({scope: Scope.REQUEST})
export class AppService {
  @Inject(REQUEST)
  private readonly request: Request;

  getHello(): string {
    return 'Hello World!';
  }
}
```

## Expected behavior
No errors.

## Environment

<pre><code>Nest version: 6.5.3
 
For Tooling issues:
- Node version: 10
</code></pre>

**Comment by kamilmysliwiec** [comment]
Working on this https://github.com/nestjs/nest/pull/2387

**Comment by immanuel192** [comment]
Remove `package-lock.json`, install packages and I can see it works

**Comment by xxluke** [comment]
This is still not working in NestJS 6.6.4 even though all linked issues/pull requests are closed/merged.

**Comment by kamilmysliwiec** [comment]
@xxluke you should use `await app.resolve()` instead of `app.get()`
