### ISSUE TITLE
NestJS Microservices integration with Laravel

### ISSUE THREAD

**Issue by bcba25** [nestjs/nest#2642]
Is there any way to send commands to laravel redis using nest microservices as well as receive commands from laravel in nest? 

```
this.client.send({ cmd: 'channel_name' }, { foo: 'bar' }).subscribe({
            next: php_response => {
                res.status(HttpStatus.OK).json(php_response);
            },
            error: error => {
                res.status(HttpStatus.INTERNAL_SERVER_ERROR).json(error);
            }
        });
```

How can I specify channel ?

Previously  I've created this thread, but it was closed and till now no response regarding this implementation. @kamilmysliwiec hope you can assist on this, I want to split some functionality to Nest and slowly start moving from laravel to nest. Thanks

**Comment by zuohuadong** [comment]
you means publish/subscribe ?

**Comment by BrunnerLivio** [comment]
Please, use our [Discord]( https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by bcba25** [comment]
@zuohuadong have you done it with nest ? Currently both projects are working separately, but when I do send command to laravel sub - nothing happens.

**Comment by zuohuadong** [comment]
php artisan list  ？
