### ISSUE TITLE
94814:19-45 Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by savantKing** [nestjs/nest#2643]
## Current behavior
I updated Angular 6 to Angular 8. And everything  seems to work. But I only get a annoying warning saying:

> 94814:19-45
> Critical dependency: the request of a dependency is an expression

## Expected behavior
That the warning will not be thrown anymore.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:
So the complete message is this:

> WARNING in ./node_modules/typescript/lib/typescript.js 94814:19-45
> Critical dependency: the request of a dependency is an expression
> i ｢wdm｣: Compiled with warnings.
> 

</code>

</pre>

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the `ng-universal` package + provide a minimal repo that reproduces your issue
