### ISSUE TITLE
repository.findOrFail() should return a 404 error instead of 500 if no entity

### ISSUE THREAD

**Issue by brunobuddy** [nestjs/nest#2647]
## Current behavior
When using `findOrFail()` or `findOneOrFail()`, a 500 error is thrown if there is no entity (EntityNotFoundError).

## Input Code
```ts
  async show(id: number): Promise<Sample> {
    return await this.sampleRepository.findOneOrFail({ id })
  }
```

## Expected behavior
In Laravel framework (PHP), a similar implementation exists for long time and returns a 404 error in that case by default: https://laravel.com/docs/5.8/eloquent#retrieving-single-models. This behavior is more intuitive and result in less code in services.

## Possible Solution
Return 404 instead of 500

## Environment

<pre><code>
Nest version: 5.1.0

**Comment by kamilmysliwiec** [comment]
Please, read this https://docs.nestjs.com/exception-filters
