### ISSUE TITLE
[discussion]: Allow registering interceptors across modules

### ISSUE THREAD

**Issue by OJezu** [nestjs/nest#2649]
## Is your feature request related to a problem? Please describe.
Allow modifying/enriching responses from a controller's method, while the module containing the controller knows nothing about the modifying code.

## Describe the solution you'd like
I would like to register an interceptor in `ActionModule` on controller in `DataModule`, while the `DataModule` is not coupled to `ActionModule`. The interceptor must be injectable.

## Teachability, Documentation, Adoption, Migration Strategy
First a decision needs to be made, how the interceptor should be implemented, some posibilites are:

- special syntax in module definition, or new provider type
- moving things around, so `UseInterceptors` can be successfully used manually during initialization of later modules
- changing the way `UseInterceptors` work, so that it can be used at any time.
- supporting forwardRef in UseInterceptors

## What is the motivation / use case for changing the behavior?
My application has two modules, `DataModule` keeping some data structure, and `ActionModule` that does actions based on the entities kept in `DataModule`. `ActionModule` imports `DataModule`. Users of the app API would greatly appreciate if some information on last actions would be included in requests about the data structure, that are served by controllers in `DataModule`

Currently, a global interceptor can be registered, in which scenario what controller and method is called has to be checked in that interceptor, which will be called for all served requests.

## Example of what does not work now:
```typescript
@Controller('/')
class KittensController {
  @Get('/')
  @UseInterceptors(MeowInterceptor) // this does not work, MeowInterceptor is not found
  @UseInterceptors(forwardRef(() => MeowInterceptor)) // this does not work, as UseInterceptors does not work with forwardRef
  // also this two methods require coupling the KittensModule to MeowModule at least in annotations
  public getKittens() {
    return {kittens: [{name: 'Fluffers'}, {name: 'Mrs Cute'}, {name: 'Old Meowy'}]};
  }
}

@Module({
  controllers: [
    KittensController,
  ],
})
class KittensModule {}

//////// MEOW MODULE

@Injectable
export class MeowService {
  public getLastMeowForCat(kitten: {name: string}): string|null {
    const catTable = { // let's pretend this is not trivial
      'Fluffers': 'meow',
      'Mrs Cute': 'MEEEEOW',
      'Old Meowy': 'Mrrrrrrrr',
    };
    
    return kitten.name in catTable ? catTable[kitten.name]: null;
  }
}

@Injectable
export class MeowInterceptor  implements NestInterceptor {
  public constructor(private readonly meowService: MeowService) {}

  public intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    return next.handle().pipe(
      tap((result: {kittens: {name: string, lastMeow?: string|null}[]}): void => {
        result.kittens.forEach((kitten) => {
          kitten.lastMeow = this.meowService.getLastMeowForCat(kitten);
        });
      }),
    );
  }
}

// this does not work, as MeowService for MeowInterceptor cannot be found in DI yet
UseInterceptors(MeowInterceptor)(
  KittensController.prototype,
  'MethodA',
  Object.getOwnPropertyDescriptor(ControllerA.prototype, 'methodA'),
);

@Module({
  imports: [
    KittensModule,
  ],
  providers: [
    MeowService,
    {
      provide: '',
      useFactory: () => {
        // And this comes too late, the interceptor registration returns no error, but the interceptor is not fired for requests
        UseInterceptors(MeowInterceptor)(
          KittensController.prototype,
          'MethodA',
          Object.getOwnPropertyDescriptor(ControllerA.prototype, 'methodA'),
        );
      },
    },
  ],
})
class MeowModule{}
```

**Comment by OJezu** [comment]
Also up for discussion: are there other places that would benefit from cross-module declaration? Should there be another method to accomplish extension of module behaviour, like [DI tags](https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services)?

**Comment by kamilmysliwiec** [comment]
``
 @UseInterceptors(MeowInterceptor) // this does not work, MeowInterceptor is not found
```

It works. You can just export `MeowService` from `MeowModule` and import `MeowModule` from `KittensModule`. That will create a circular dependency, but it will work fine.

```
@UseInterceptors(forwardRef(() => MeowInterceptor)) // this does not work, as UseInterceptors does not work with forwardRef
```
`forwardRef` doesn't make any sense in combination with `@UseInterceptors()` (it's even impossible to create a circular dependency between controller and interceptor).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by OJezu** [comment]
I did use Discord, and no solution with no circular dependencies was proposed.

The point is to have no circular dependency, so the modules are not coupled to each other.

**Comment by kamilmysliwiec** [comment]
That's one of the most important ideas of Nest modules - isolation. If you want to impose behavior of one module from another module without a clear relationship between them, it's against the framework rules. Perhaps, middleware could help you here - they're bounded to a route path instead.

**Comment by OJezu** [comment]
I understand that, on the other hand, there is no way of easily extending modules behaviour without modifying them, so no open/closed principle for controllers here(?).

Moreover, I can do what I want with a _global_ interceptor, which arguably is even worse.
