### ISSUE TITLE
Use cold observable for request-response and hot for events

### ISSUE THREAD

**Issue by ps2goat** [nestjs/nest#2651]
## Is your feature request related to a problem? Please describe.

We started using TCP microservices, and were looking to use the `emit` method similar to what's in the documentation. 

This is more likely a documentation issue, as the receiving service did not respond until the calling service subscribed to the `emit` result.

For example, this is the sample code in the documentation:

```
async publish() {
  this.client.emit<number>('user_created', new UserCreatedEvent());
}
```

We actually had to do at least this for the message to be sent/received:

```
async publish() {
  this.client.emit<number>('user_created', new UserCreatedEvent()).subscribe();
}
```
## Describe the solution you'd like

At the very least, the documentation should be updated to include that the subscribe call is required.

As a personal preference, it would be easier to work with a Promise using async/await to return an ack in this case vs. having to deal with observables, at least in the publish-and-forget situation. There'd be no subscription to make and no clean-up of the subscription.  It makes sense to use Observables in other cases where there's a lot of back-and-forth chatter besides a basic acknowledgement.

## Teachability, Documentation, Adoption, Migration Strategy

The code on the client calling the service would look like this:

```
async publish() {
  // optional await, if you don't care about the response.
  await this.client.emit<number>('user_created', new UserCreatedEvent());
}
```
## What is the motivation / use case for changing the behavior?

observables don't make sense for a fire-and-forget strategy, at least on the publishing side.

**Comment by kamilmysliwiec** [comment]
I think that we should remain consistent (keep betting on Observables), but a cold observable should be changed into a hot one (that emits an event asynchronously even without `subscribe()`). What do you think?

**Comment by ps2goat** [comment]
I would be ok with that.

**Comment by kamilmysliwiec** [comment]
Added in 6.6.0 :)
