### ISSUE TITLE
Add ability for versioning in controllers and requests.

### ISSUE THREAD

**Issue by alfredoperez** [nestjs/nest#2654]
## Feature Request
Add ability for versioning in controllers and requests.

## Is your feature request related to a problem? Please describe.
Using a prefix for versioning does not solve the problem of having an API that works for multiple versions.

### Versioning a Controller

This is to enable  a controller to have multiple versions or work for a specific version

1. Add Metadata about the controller versions as an of strings. This can be done by adding an option to the `@Controller` or add a `@Version` decorator.

2. Modify the `RouteResolver` `registerRoutes` to add a prefix for each version in the controller's metadata

Eg. 
```typescript
@Controller({path: '/helloworld', versions: ['v1', 'v2]})
export class HelloWorldController {
	@Get()
	getGreeting(): string {
		return 'Hello';
	}
}
```

The previous example enables the following endpoints:

```console
 GET  api/v1/helloworld
 GET  api/v2/helloworld
```

### Versioning a Request
1. Add metadata to the request with the request decorator 
2. in the `request-mapping.decorator.ts` create the `PATH_METADATA` for each version

Eg.
```typescript
@Controller('versioned-helloworld')
export class VersionedHelloWorldController {

	constructor() { }

	/**
	 * GET /versioned-helloworld/v1/greeting
	 *
	 * Returns 'Hello World from a V1'
	 */
	@AtlasGet({ path: 'greeting', versions: ['v1'] })
	getV3Greeting(): string {
		return 'Hello World from a V1';
	}

	/**
	 * GET /versioned-helloworld/beta/greeting
	 *
	 * Returns 'Hello World from a beta'
	 */
	@Get({ path: 'greeting', versions: ['beta'] })
	getBetaGreeting(): string {
		return 'Hello World from a beta';
	}

	/**
	 * GET /versioned-helloworld/beta/farewell
	 * GET /versioned-helloworld/v2/farewell
	 *
	 * Returns 'Bye World from a beta and V3'
	 */
	@AGet({ path: 'farewell', versions: ['beta', 'v2'] })
	getFarewell(): string {
		return 'Bye World from  beta and V2';
	}
}
```

The previous example enables the following endpoints:

```console
  GET /versioned-helloworld/v1/greeting
  GET /versioned-helloworld/beta/greeting
  GET /versioned-helloworld/beta/farewell
  GET /versioned-helloworld/v2/farewell
```
## Teachability, Documentation, Adoption, Migration Strategy
This will be extra parameters that can be used or omitted.

## What is the motivation / use case for changing the behavior?
To add capabilities for API, Controllers and endpoints versioning. 

Versioning is an essential part of the development of an API process, and must of the time just adding a `prefix` to the API wont allow migration and deprecation.

**Comment by kamilmysliwiec** [comment]
```typescript
@AtlasGet({ path: 'greeting', versions: ['v1'] })
```
Why not just `@Get('v1/greeting')`? Or if you have multiple versions, `@Get(['v1/greeting', 'v2/greeting'])`. 

You can even create your own decorator for this:
```typescript
export const AtlasGet = ({ path, versions }) => Get(
  versions.map((version) => `${version}/${path}`)
);
```

and then use as in your example:

```typescript
@AtlasGet({ path: 'greeting', versions: ['v1'] })
```
