### ISSUE TITLE
Auto Inject provider and not module architecture

### ISSUE THREAD

**Issue by lichnow** [nestjs/nest#2671]
Dependency-injected service providers (or all classes) should be automatically injected unless there are special requirements (such as the need to use `usefactory`). It should be registered and the import or export between each module is very cumbersome and Things that can easily cause confusion in the architecture.
The application architecture should replace the module build in a straightforward way. Modules (or plugins) should be used as extensions for third parties, not directly in the application, which makes no sense and can make the framework very heavyweight.
The symfony4 to 3 improvement is a good demonstration，See [symfony-flex](https://symfony.com/doc/current/setup/flex.html) and [autowrite](https://symfony.com/doc/current/service_container/3.3-di-changes.html)and[bundles](https://symfony.com/doc/current/bundles.html)

**Comment by kamilmysliwiec** [comment]
This is how the framework is designed. We don't plan to change the overall architecture
