### ISSUE TITLE
Implement https://github.com/fanout/express-grip

### ISSUE THREAD

**Issue by ricardovf** [nestjs/nest#2677]
## Feature Request
Is there a reference adapter that i can use, something like a microservice adapter?

## Is your feature request related to a problem? Please describe.
It's to clear to me how to implement this solution using nestjs: https://github.com/fanout/express-grip it's necessary to use this guy: https://pushpin.org

Thanks

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
