### ISSUE TITLE
RepositoryNotFoundError when using HMR with TypeORM

### ISSUE THREAD

**Issue by Ivanca** [nestjs/nest#2695]
## Bug Report
After following the [Hot reload tutorial](https://docs.nestjs.com/techniques/hot-reload), then the [TypeORM tutorial](https://docs.nestjs.com/techniques/database) this error starts happening. I tried creating a new one from scratch to see if I had missed some step but the exact same error happened again. I have googled the error and none of the solutions seem to work, including the solutions talking about changing "entities" in configorm.json; I tried using sqlite and postgres but the same error happens with both.

When I run `npm run build` it creates the build succesfully so I assume it has something to do with HRM or/and webpack.

## Current behavior
Get this error from console:
RepositoryNotFoundError: No repository for "Photo" was found. Looks like this entity is not registered in current "default" connection?

## Input Code
https://github.com/Ivanca/nestjs-error-proof

## Expected behavior
No errors.

## Environment

<pre><code>
Nest version: 6.5.3

 
For Tooling issues:
- Node version: v10.16.0
- Platform: Windows 10

Others:
Package.json contains:
    "start": "ts-node -r tsconfig-paths/register dist/server",
    "webpack": "webpack --config webpack.config.js",

</code></pre>

**Comment by Ivanca** [comment]
There is a buggy work-around that is very flawed, that is using `entities: getMetadataArgsStorage().tables.map(tbl => tbl.target)`

Is very flawed because for deployment reasons I need to use ormconfig.json **NOT** a ts file for configuration.

**Comment by ecSpl01t** [comment]
I've got the same issue, but getMetadataArgsStorage didn't help me.
I tried to debug and found some weird data...
- when the application is started I got this: 
[ [Function: PlaceRatingEntity],
  [Function: PlaceGroupEntity],
  [Function: UserBookingEntity],
  [Function: PlaceEntity],
  [Function: UserFavoriteEntity],
  [Function: UserEntity] ]

My 6 entities.

- But when hmr was started, I got this:
[ [Function: PlaceRatingEntity],
  [Function: PlaceGroupEntity],
  [Function: UserBookingEntity],
  [Function: PlaceEntity],
  [Function: UserFavoriteEntity],
  [Function: UserEntity],
  [Function: PlaceRatingEntity],
  [Function: PlaceGroupEntity],
  [Function: UserBookingEntity],
  [Function: PlaceEntity],
  [Function: UserFavoriteEntity],
  [Function: UserEntity] ]

Maybe it's my problem...

> RepositoryNotFoundError: No repository for "PlaceEntity" was found. Looks like this entity is not registered in current "default" connection?


Someone knows, what happened?

**Comment by kamilmysliwiec** [comment]
See the solution here: https://github.com/nestjs/nest/issues/755

@ecSpl01t it seems that for some reasons your entities are loaded twice. Perhaps, you just have to modify your `entities` path to don't point at both `.js` and `.ts` files.

**Comment by Ivanca** [comment]
@kamilmysliwiec  None of those were solutions, this is a bug of nestjs for not allowing a simple way to still work despite being bundled in a single file.

**Comment by kamilmysliwiec** [comment]
This issue has nothing to do with NestJS. If you use bundler like webpack with typeorm, you have to either pass class references directly (instead of using a wildcard string which - for webpack - is just a string) OR create a plugin for webpack that would replace this particular string with those references at the compilation time.
