### ISSUE TITLE
App won't start with start:dev script, start script works fine

### ISSUE THREAD

**Issue by newtonmunene99** [nestjs/nest#2705]
## Current behavior

When I run `npm start:dev` it fails with the following output/error:
```
[Nest] 5456   - 08/04/2019, 4:26 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +175ms
C:\Users\Munene\Projects\Node\myprojectname\src\cards\cards.entity.ts:1
(function (exports, require, module, __filename, __dirname) { import {
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
## Input Code

```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  Column,
  ManyToOne,
  UpdateDateColumn,
} from 'typeorm';
import { UsersEntity } from '../users/users.entity';

@Entity('cards')
export class CardsEntity {
  @PrimaryGeneratedColumn('uuid') id: string;

  @CreateDateColumn() addedOn: Date;

  @UpdateDateColumn() updatedOn: Date;

  @Column({
    type: 'text',
    unique: true,
  })
  cardNumber: string;

  @Column('text') cardType: string;

  @Column('text') cardHolder: string;

  @Column('text') expiry: string;

  @ManyToOne(type => UsersEntity, owner => owner.cards)
  owner: UsersEntity;
}

```

## Expected behavior

`start:dev` script should start app and watch for changes.

## Environment

<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: 10.15.0  
- Platform:  Windows

Others:

</code></pre>
### Screenshot
![image](https://user-images.githubusercontent.com/29271333/62424366-8741be00-b6d6-11e9-80cc-7e69bd2de843.png)

**Comment by ed-fruty** [comment]
Do you have the correct database connection settings? Are you sure that the database is running ?
Try to change your settings for example to `sqlite` driver and check again.

**Comment by newtonmunene99** [comment]
Yes the database connection is fine. When using `start` script everything works fine I can read and write to the database

**Comment by jolabo** [comment]
For the **start:dev** command did you change your TypeOrm config to look for entities in the _dist_ folder? (note this breaks the start command).

**Comment by julianomqs** [comment]
Hello there,

I had this same problem, and I solved changing this line:

```json
"entities": ["src/**/*.entity{.ts,.js}"]
```

to this:

```json
"entities": ["dist/**/*.entity{.ts,.js}"]
```

(Look for entities from dist folder instead of src folder)

in `ormconfig.json`.

**Comment by newtonmunene99** [comment]
I added both of them like this
```
"entities":["src/**/*.entity{.ts,.js}","dist/**/*.entity{.ts,.js}"]
```
I'll try removing the `src` one

**Comment by kamilmysliwiec** [comment]
See similar issues: https://github.com/nestjs/nest/issues?utf8=%E2%9C%93&q=Unexpected+token+%7B
