### ISSUE TITLE
.send .emit microservice

### ISSUE THREAD

**Issue by scriptsure** [nestjs/nest#2718]
## Bug Report
The only way to get a SEND or EMIT to engage is to perform a RETURN. So for instance this will not work:

```this.client.send....```

you have to do this 

```return this.client.send....```

The actual return type of the function in the MS has no impact on this issue.

If I do this it also works:

```this.client.send<any>(pattern, payload).subscribe()```

The use case here is that I do not want to do a RETURN inside of an express call... I want nestjs to send back default response. I assume that the SUBSCRIBE is the key?

**Comment by kamilmysliwiec** [comment]
`send()` is intended to be a lazy one. However, we do plan to change `emit()` to a hot observable, since we don't expect any response from the external microservice.
