### ISSUE TITLE
[Discussion] Use Bazel as build system

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#2719]
## Feature Request

This issue serves the purpose of an open discussion - looking for Pros/Cons and how the current build system (e.g. Gulp) should be handled once we would migrate to Bazel.  

## Describe the solution you'd like
Use Bazel to build and test the NestJS ecosystem

## What is the motivation / use case for changing the behavior?
Angular and many other projects are using Bazel. I think a discussion is worthwhile whether we should adopt Bazel at NestJS too. 

Related issue #2714

**Comment by BrunnerLivio** [comment]
Some useful tools we could use with Bazel:
- [ts-api-guardian](https://www.npmjs.com/package/ts-api-guardian) protects the public API with Golden Files (`.d.ts`)
-

**Comment by kamilmysliwiec** [comment]
Bazel is a great tool, but I'm not entirely sure if we really need it in our repo currently. Perhaps, it might be useful someday in the future when packages grow even more, so why not starting looking at this integration beforehand. I'm fine with anything that can improve our DX and local workflow. Let's give it a shot and verify if it meets our expectations.

**Comment by marcus-sa** [comment]
I've begun working on it here https://github.com/nestjs/nest/pull/2743 :smiley:
