### ISSUE TITLE
Use CircleCI as replacement of TravisCI

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#2720]
## What is the motivation / use case for changing the behavior?
TravisCI is great for smaller projects and easy to get started with. In my opinion NestJS has grown out of this. 

Some features why choose CircleCI over TravisCI:
- YAML Anchors: Allows to define "mixin" jobs. It allows to reduce redundancy. Useful for e.g. setup the environment and [saving / restoring cache](https://github.com/angular/angular/blob/961d663fbef4d6ea2ebb5a60f38799a273fa71ed/.circleci/config.yml#L100-L105).
- Displays each job on GitHub: 
![Selection_001](https://user-images.githubusercontent.com/9899423/62685584-3c1ff780-b9c3-11e9-8b42-1306b63a7dbc.png)
- Better measuring:
![Selection_002](https://user-images.githubusercontent.com/9899423/62685790-a042bb80-b9c3-11e9-811d-23cf3611283b.png)
- Better workflow integration:
![Selection_003](https://user-images.githubusercontent.com/9899423/62685873-cd8f6980-b9c3-11e9-9ae3-83703a2801d4.png)

## Teachability, Documentation, Adoption, Migration Strategy
Migrate nestjs/nest to CircleCI. Migrate integrations only if needed.

**Comment by marcus-sa** [comment]
Using https://garden.io or similar would also help the integration of sample projects and e2e testing and help getting rid of gulp completely.
(We use it for our entire dashboard app at work)

**Comment by kamilmysliwiec** [comment]
I wanted to migrate over CircleCI for months! :) Let's do it as soon as possible. Feel free to move forward with this migration if you have some spare time.

**Comment by marcus-sa** [comment]
Let me know if you need any help ✊

**Comment by kamilmysliwiec** [comment]
I started the migration towards CircleCI. Feel free to contribute:)

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec looking really nice - exactly how I had imagined it to be (with the mixins / aliases, etc. so awesome) :)

The checks are so useful for a contributor:
![awesomeness](https://user-images.githubusercontent.com/9899423/63702890-2cf4d280-c828-11e9-84c9-4ced3ab9c1db.png)
![awesomeness 2](https://user-images.githubusercontent.com/9899423/63703101-94128700-c828-11e9-9772-1110b0c23c7f.png)

and the config is way cleaner and maintainable.

**Comment by marcus-sa** [comment]
Any reason for why you're not using yarn?

**Comment by BrunnerLivio** [comment]
@marcus-sa we challenged that idea some time ago in #1060, but in the end went for #1176. It would have been a huge change to the existing codebase, so #1176 made more sense at the time. 

Maybe we can re-discuss this topic since we are anyway currently expanding our build system, but this should be handled in a separate issue / PR.

**Comment by kamilmysliwiec** [comment]
Just finished the migration of the main repo. I'll do the same for the rest of them too. If anyone wants to contribute, PRs are welcome!

PS. @BrunnerLivio I think that @marcus-sa asked about NPM vs Yarn, not Yarn workspaces. I'm personally using NPM recently, but I don't have any preference here. Both aren't perfect, neither one convinced me, so I'm just using this one which is more popular now:)
