### ISSUE TITLE
cannot set header

### ISSUE THREAD

**Issue by l2ubin** [nestjs/nest#2722]
## Current behavior

@Header('Content-Type','application/json') doesn't set the response header to application/json
Also there is no Content-Type header on the response by default on the latest version of nest at the time of scaffolding the app
## Expected behavior

Should allow setting content-type header

## Minimal reproduction of the problem with instructions

Add @Header('Content-Type','application/json') to any get route and see the response

**Comment by BrunnerLivio** [comment]
If your Controller method returns an object, NestJS automatically switches to `Content-Type: application/json` - whereas if you return a string ìt will result in `Content-Type: text/html`. 
Therefore you do not need to handle it yourself. However, if you actually need to change it anyway, then your example should work, I just checked.

I have used this controller. Note that the `get()` method returns a string, so Nest would return `text/html` if the `@Header()` is not set...
```ts
@Controller()
class AppController {
  @Get('/')
  @Header('Content-Type', 'application/json')
  get() {
    return 'test';
  }
}
```

... but it returns `application/json`:

```
$ curl --head -i http://localhost:3000
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 4
ETag: W/"4-qUqP5cyxm6YcTAhz05Hph5gvu9M"
Date: Thu, 08 Aug 2019 18:20:44 GMT
Connection: keep-alive
```
