### ISSUE TITLE
Add seconds to default logger service

### ISSUE THREAD

**Issue by ulrichb** [nestjs/nest#2723]
## Is your feature request related to a problem? Please describe.
No seconds in the default logging.

## Describe the solution you'd like

Atm. only hours and minutes are logged in the default [`Logger` implementation](https://github.com/nestjs/nest/blob/202a572ea4470e358f6f0aa6df3c0c71a4d5aa5b/packages/common/services/logger.service.ts#L110).

Please add seconds, or maybe add an option to customize the default logger format.

Note that I don't want to override the whole logger service. It's pretty nice, I just want another timestamp format.

**Comment by l2ubin** [comment]
I have added that to my pull request. Hope it gets accepted soon

**Comment by ulrichb** [comment]
For reference: https://github.com/nestjs/nest/pull/2770. Thx @l2ubin .

**Comment by l2ubin** [comment]
> For reference: #2770. Thx @l2ubin .

let me know if I could help out with any code

**Comment by kamilmysliwiec** [comment]
Fixed in 6.6.0 :)

**Comment by ulrichb** [comment]
Nice, thx
