### ISSUE TITLE
fastify request no body in middleware

### ISSUE THREAD

**Issue by nnsay** [nestjs/nest#2729]
## Current behavior

Can not get the request body in middleware.

## Input Code

```ts
// main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';

async function bootstrap() {
  // const app = await NestFactory.create(AppModule);
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());

  await app.listen(3000);
}
bootstrap();

// app.module.ts
import { Module, MiddlewareConsumer, NestModule } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule implements NestModule {
  constructor(
    private readonly appService: AppService,
  ) { }

  // middleware
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(logger)
      .forRoutes('*');
  }
}

function logger(req, res, next) {
  console.log({
    headers: req.headers,
    originalUrl: req.originalUrl,
    hostname: req.hostname,
    body: req.body, // undefined
    method: req.method,
  });
  next();
}
```

## Expected behavior

the request body should output when send a post request with data. eg: 
```
curl -X POST \
  'http://localhost:3000/webhook?aa=' \
  -H 'Content-Type: application/json' \
  -d '{
	"name": "jimmy"
}'
```
and the result is:
![image](https://user-images.githubusercontent.com/14331919/62819160-2b6aaf80-bb84-11e9-8035-2cd672a9dea5.png)

but the result is ok when i use the default express platform, so i guest it's a compatibility bug.
## Environment

<pre><code>
Nest version: 6.0.0
 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
https://github.com/fastify/fastify/blob/master/docs/Middlewares.md#express-middleware-compatibility 

Fastify gives you Node `req` and `res` instances in middleware (not their wrappers). Hence, you can't access parsed request `body`.

> This is because Fastify wraps the incoming req and res Node instances using the Request and Reply objects internally, but this is done after the middlewares phase. If you need to create a middleware you have to use the Node req and res instances.
