### ISSUE TITLE
Bug of ValueProvider

### ISSUE THREAD

**Issue by GithubCGY** [nestjs/nest#2732]
## Current behavior

When 'useValue' is undefined, you  will get an error 'Nest can't resolve dependencies of the Log4jsService (?)'.
## Input Code

```ts
export function createOptionProvider(options?: Configuration | string): Provider {
    return {
        provide: LOG4JS_OPTION,
        useValue: return options; // undefined
    };
}

@Injectable()
export class Log4jsService implements LoggerService {
    constructor(@Inject(LOG4JS_OPTION) options?: Configuration | string) {}
    ...
}
```

## Environment

<pre><code>
Nest version: 6.5.3

 
For Tooling issues:
- Node version: 10.15.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec I am questioning whether we should or should not support this? We could say "just use null", but `null` does have some annoying side-effects. See [sindresorhus](https://github.com/sindresorhus/meta/issues/7) thread. So it may would make sense to allow `undefined`?

---
To work around this, just use `export function createOptionProvider(options: Configuration | string | null = null)`

**Comment by kamilmysliwiec** [comment]
Well, it sounds weird to define a provider which provides undefined value. In the best-case scenario, you should provide a default value when `options` is not available. I don't see any reason why we should support this.

**Comment by BrunnerLivio** [comment]
No I guess if the user may provide  `undefined` he just reside to `@Optional()`. Let's close this issue.
