### ISSUE TITLE
How to use repostory as a parameters in other function?

### ISSUE THREAD

**Issue by abedalterra** [nestjs/nest#2738]
Hi, I have an issue with the repository in nestjs.

I have a function that has repository as a params, like below
`export function saveToAdditional(data: ObjectMap, systemRepository: 
    MongoRepository<Systems>, systemId: string, functionName: string): boolean {
    systemRepository.find() //or maybe use findOne, findOneAndUpdate, etc
    return 
}
`

I want to write unit test of my file but i don't know how to mock the repository. I had write a unit test for service before and i made a module first :
` module = await Test.createTestingModule({
      providers: [
        ExternalSystemService,
        {
          provide: getRepositoryToken(Systems),
          useFactory: mockSystemsRepositoryFactory,
        },
      ],
    }).compile();`

But i think i dont need createTestingModule for this function test.  Any suggestion

**Comment by BrunnerLivio** [comment]
Please, use our [Discord]( https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
