### ISSUE TITLE
Microservices with redis transport ? lost messages ?

### ISSUE THREAD

**Issue by appsolutegeek** [nestjs/nest#2749]
Hi

I am trying to pick the correct transport for microservices, I already know the Basic TCP transport isn't ideal. I was left with 2 options that I would like to use. Once was nats streaming - but i don't think a transport exists for nats streaming, only for nats.

I do have access to redis, i was wonder what happens if one of the servers go down, when it re-connects does it receives all missed messages ?

Is redis a good recommended transport to use ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
