### ISSUE TITLE
Nest npm run start:dev fails, npm start works.

### ISSUE THREAD

**Issue by mkbrdigital** [nestjs/nest#2757]
## Bug Report

App won't run with npm run start:dev

![Screenshot from 2019-08-15 14-49-30](https://user-images.githubusercontent.com/49996023/63118194-c17f4b00-bf73-11e9-8c86-f28b7b8c08e1.png)

With npm start:
![nest3](https://user-images.githubusercontent.com/49996023/63118208-cc39e000-bf73-11e9-80e0-83deac79211c.png)

## validator.interceptor.ts

```ts
import {
  NestInterceptor,
  Injectable,
  ExecutionContext,
  HttpException,
  HttpStatus,
  CallHandler,
} from '@nestjs/common';
import { Observable } from 'rxjs';
import { Contract } from 'src/backoffice/contracts/contract';
import { ResultModel } from 'src/backoffice/models/result.models';

@Injectable()
export class ValidatorInterceptor implements NestInterceptor {
  constructor(public contract: Contract) {}
  intercept(
    context: ExecutionContext,
    next: CallHandler<any>,
  ): Observable<any> {
    const body = context.switchToHttp().getRequest().body;
    const valid = this.contract.validate(body);
    if (!valid) {
      throw new HttpException(
        new ResultModel(
          'Ops, algo saiu errado',
          false,
          null,
          this.contract.errors,
        ),
        HttpStatus.BAD_REQUEST,
      );
    }
    return next.handle();
  }
}

```

## customer.controller.ts

```ts
import {
  Controller,
  Get,
  Post,
  Put,
  Delete,
  Param,
  Body,
  UseInterceptors,
} from '@nestjs/common';
import { CustomerModel } from '../models/customer.models';
import { ResultModel } from '../models/result.models';
import { ValidatorInterceptor } from 'src/interceptors/validator.interceptor';
import { CreateCustomerContract } from '../contracts/customer.contracts';

@Controller('v1/customers')
export class CustomerController {
  @Get()
  get() {
    return new ResultModel(null, true, [], null);
  }
  @Get(':document')
  getById(@Param('document') documente) {
    return new ResultModel(null, true, {}, null);
  }
  @Post()
  @UseInterceptors(new ValidatorInterceptor(new CreateCustomerContract()))
  post(@Body() body: CustomerModel) {
    return new ResultModel('Cliente criado com sucesso', true, body, null);
  }
  @Put(':document')
  put(@Param('document') document, @Body() body) {
    return new ResultModel('Cliente alterado com sucesso', true, body, null);
  }
  @Delete(':document')
  delete(@Param('document') document) {
    return new ResultModel('Cliente removido com sucesso', true, null, null);
  }
}

```

## Environment
![nest1](https://user-images.githubusercontent.com/49996023/63115090-cd1b4380-bf6c-11e9-8e60-3b95628a0380.png)

<pre><code>
Nest version: 6.6.3

 
For Tooling issues:
- Node version: 12.7.0
- npm version: 6.10.0
- Typescript: 3.5.3
- Platform:  Linux Mint 19 Tessa
</code></pre>

**Comment by jmcdo29** [comment]
`ts-node` works by using ts files directly and holding all compiled js files in memory, it also inherently changes all references from `src` to the `dist` that it holds so that there are no problems with using `src` in your path as a relative path. After using `tsc-watch` (or any other variation of `tsc`) `src` is not auto changed to `dist` and it is not possible for node to resolve the path to `src` from `dist` as they are different directories. You'll need to change any imports using `src` to the absolute path using `..` from where the current file is.
