### ISSUE TITLE
How to return response in UTF-8 with BOM ?

### ISSUE THREAD

**Issue by Youta-Asial** [nestjs/nest#2759]
## Current behavior

Thanks for your contributions!
I have to return csv files in UTF-8 with BOM. (Want it opened with Excel.)
But downloaded file through nestjs response doesn't have BOM. (Is it removed automatically?)

## Input Code

```ts
request.res.contentType('text/csv');
request.res.attachment('sales.csv');
request.res.write(
  Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from('csv,string,here')]);
);
request.res.end();
```

## Expected behavior

Being able to respond csv in UTF-8 with BOM.

## Environment

<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: 12.4.0 
- Platform:  Debian 

</code></pre>

Thanks.

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
