### ISSUE TITLE
deploy under sub-path

### ISSUE THREAD

**Issue by jqs7** [nestjs/nest#277]
I use [apex/up](https://github.com/apex/up) for deployment, it would deploy the application into aws with a url like `https://xxx.amazonaws.com/development/` under up's built-in reverse proxy.

The problem is, when i visit the api of nest application, it would redirect to root path from sub-path with status 301, like `https://xxx.amazonaws.com/development/swagger` -> `https://xxx.amazonaws.com/swagger`.

How to disable this behavior?

**Comment by shekohex** [comment]
could you try to make `development` as Global Prefix.
hmm, give it a try, it may work 
```ts
app.setGlobalPrefix('development');
```

**Comment by jqs7** [comment]
sadly, it doesn't work

**Comment by kamilmysliwiec** [comment]
Hi @jqs7, 
Honestly, I don't think that it's a Nest-related issue. You should prefer to use stackoverflow for that kind of questions 🙂
