### ISSUE TITLE
Load axios lazily in HttpModule

### ISSUE THREAD

**Issue by ruscon** [nestjs/nest#2772]
## Current behavior
I have a question about `axios` dependency in the `@nestjs/common`.
It is used only in `HttpModule`, which is not required for use in a particular project.
In addition, my project can work with an older version of `axios`.
Thus, in my project, 2 versions of the `axios` library are installed.
Additionally, the `HttpService` return the `axios` instance out to my project and accordingly, a version conflict may occur

## Expected behavior

Maybe `axios` should be as a `peerDependency` or `optionalDependency` ?

## Environment

Nest version: 6.5.3

**Comment by DimosthenisK** [comment]
This seems correct. Make nestJS ask for it, just like it does when you try to start a gateway without having socket.io installed.

**Comment by kamilmysliwiec** [comment]
I'm fine with loading this library lazily. We can do it in the next major release (since that should be considered as a breaking change)

**Comment by underfin** [comment]
Other library maybe can load lazily, like microservice library `redis`  and `nats` etc.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/4640#issuecomment-770811700
