### ISSUE TITLE
Microservice listenAsync promise does not reject on error

### ISSUE THREAD

**Issue by michaelbromley** [nestjs/nest#2777]
## Current behavior
When creating a Nest Microservice and then starting it with the `listenAsync()` method, any failure to start the microservice server (e.g. port already in use) will result in the returned promise never settling (neither resolving nor rejecting.

## Input Code
```ts
const microservice = await NestFactory.createMicroservice(WorkerModule, {
    transport: Transport.TCP,
    options: {
         port: 1234 // some port already in use 
    },
});

await microservice.listenAsync(); // <-- program will hang here
```

## Expected behavior
If there is an error in starting the microservice, the promise returned by `listenAsync()` should reject.

## Possible Solution
The following code: 
https://github.com/nestjs/nest/blob/0fb20e1e534c1b904017c0a60cf5b3d4abeaa15b/packages/microservices/nest-microservice.ts#L122-L124

should account for the error case and call the promise's `reject` function.

Since it is calling the Node `net.Server.listen()` method under the hood, and this method does not seem to pass failure or error data to the callback, I guess this could be implemented by adding listeners for the [`error` event](https://nodejs.org/api/net.html#net_event_error) and [`listening` event](https://nodejs.org/api/net.html#net_event_listening), something like this:

```ts
export class NestMicroservice {
  // ...

  public listen(onListening: () => void, onError: (err: any) => void)) {
    !this.isInitialized && this.registerModules();

    this.logger.log(MESSAGES.MICROSERVICE_READY);
    this.server.on('listening', onListening);
    this.server.on('error', onError);
    this.server.listen();
  }

  public async listenAsync(): Promise<any> {
    return new Promise((resolve, reject) => this.listen(resolve, reject));
  }

  // ...
}
```

## Environment

<pre><code>
Nest version: 6.5.2

**Comment by kamilmysliwiec** [comment]
> Since it is calling the Node net.Server.listen() method under the hood, and this method does not seem to pass failure or error data to the callback

This method doesn't always call `net.Server.listen`. Instead, it depends on the currently chosen transport strategy. Hence, we should provide a more generic solution to handle this issue :)

**Comment by michaelbromley** [comment]
Ah right. So how about changing the `CustomTransportStrategy` interface to add an optional error argument to the callback, in the idiomatic node style:

```ts
export interface CustomTransportStrategy {
  listen(callback: (err?: any) => void): any;
  close(): any;
}
```

Then each microservice transport would need to be updated to pass any error into the callback.

e.g. for TCP
```ts
export class ServerTCP extends Server implements CustomTransportStrategy {
  // ..
  public listen(callback: (err?: any) => void) {
    this.server.on('listening', () => callback());
    this.server.on('error', err => callback(err));
    this.server.listen(this.port, this.host);
  }
}
```

or for Redis
```ts
export class ServerRedis extends Server implements CustomTransportStrategy {
  //..
  public listen(callback: (err?: any) => void) {
    this.subClient = this.createRedisClient();
    this.pubClient = this.createRedisClient();

    this.handleError(this.pubClient);
    this.handleError(this.subClient);
    this.start(callback);
  }

  public start(callback?: (err?: any) => void) {
    this.bindEvents(this.subClient, this.pubClient);
    this.subClient.on(CONNECT_EVENT, () => callback());
    this.subClient.on(ERROR_EVENT, err => callback(err));
  }
}
```

and then in nest-microservice.ts:
```ts
export class NestMicroservice extends NestApplicationContext {
  // ..
  public listen(callback: (err?: any) => void) {
    !this.isInitialized && this.registerModules();

    this.logger.log(MESSAGES.MICROSERVICE_READY);
    this.server.listen(callback);
  }

  public async listenAsync(): Promise<any> {
    return new Promise((resolve, reject) => {
      this.listen(err => {
        if (err) {
          reject(err);
        } else {
          resolve();
        }
      });
    })
  }
```

Does that seem like a reasonable solution?

**Comment by dolsem** [comment]
I found out (through the discussion in #3209) that essentially the same thing happens with regular Nest app listen() function (not microservice). The difference seems to be that the error can still be detected with a callback argument (even though the listen() method is async and the TS type of the callback is incorrect).

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/6264
