### ISSUE TITLE
Tests broken with new fastify version

### ISSUE THREAD

**Issue by dolsem** [nestjs/nest#2782]
Please update **fastify** version in **@nestjs/platform-fastify** dependencies. They recently updated response headers type (https://github.com/fastify/fastify/pull/1775), and my tests that make use of `app.inject()` now break with
```
      Types of property 'headers' are incompatible.
        Type 'object' is not assignable to type 'Record<string, string>'.
          Index signature is missing in type '{}'.
```

### Update:
Looks like there's been a commit that updated version to 2.7.1, but the latest npm package is still using 2.6.0.

**Comment by kamilmysliwiec** [comment]
Fixed in 6.6.0 :)
