### ISSUE TITLE
nestjs/cli MaxListenersExceededWarning with node.js 12.9.0 version

### ISSUE THREAD

**Issue by neverhesitate** [nestjs/nest#2783]
## Bug Report
npm i -g @nestjs/cli install command gives the below warning with the latest node.js release;

## Current behavior
(node:15352) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit

## Environment
Nest version: 6.6.4
 
- Node version:  v12.9.0
- Platform:  Windows 10

**Comment by zuohuadong** [comment]
+1

**Comment by BrunnerLivio** [comment]
FYI: I can not reproduce this error on Ubuntu 18.04 with Node v12.9.0:
```
$ nest info

[System Information]
OS Version     : Linux 4.15
NodeJS Version : v12.9.0
NPM Version    : 6.10.2
[Nest Information]
platform-express version : 6.0.0
common version           : 6.0.0
```

Seems like either a Windows-only problem or something else.

**Comment by jayakusumah** [comment]
same issue with mojave , nodejs v10.16.0

**Comment by ddehghan** [comment]
It happens also on docker node:12.10.0-alpine
