### ISSUE TITLE
How about making configService available to RedisIoAdapter?

### ISSUE THREAD

**Issue by VirnectRemote** [nestjs/nest#2784]
## Feature Request
How about making configService available to RedisIoAdapter?

## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

import { IoAdapter } from '@nestjs/platform-socket.io';
import * as redisIoAdapter from 'socket.io-redis';
import { ConfigService } from '../config/config.service';

export class RedisIoAdapter extends IoAdapter {
  **// now i am using like this line. But this is drawbacks because class is created newly.**
  private configService: ConfigService = new ConfigService();

  createIOServer(port: number, options?: any): any {
    const server = super.createIOServer(port, options);
    const redisAdapter = redisIoAdapter({
      host: this.configService.getAsString(`REDIS_HOST`),
      port: this.configService.getAsNumber(`REDIS_PORT`),
    });
    server.adapter(redisAdapter);
    return server;
  }
}

## Teachability, Documentation, Adoption, Migration Strategy

How about inject adapter to modular ???

**Comment by db2crush** [comment]
https://github.com/nestjs/nest/issues/2785#issue-483162053
