### ISSUE TITLE
why Fastify and Express in dependencies 

### ISSUE THREAD

**Issue by nocord** [nestjs/nest#2786]
???

**Comment by BrunnerLivio** [comment]
You are probably referring to [`nestjs/nest/package.json`](https://github.com/nestjs/nest/blob/master/package.json). This won't be used for any of the packages, thus you won't install Express nor Fastify, except if you install `@nestjs/platform-express`  or `@nestjs/platform-fastify`. 

As you can see in [`nestjs/nest/packages/core/package.json`](https://github.com/nestjs/nest/blob/master/packages/core/package.json) and [`nestjs/nest/packages/common/package.json`](https://github.com/nestjs/nest/blob/master/packages/common/package.json) you do not have `fastify` or `express` as dependency.
