### ISSUE TITLE
Nestjs reload problem

### ISSUE THREAD

**Issue by l2ubin** [nestjs/nest#2787]
## Bug Report
Everytime i upload file through post man to my nestjs api, it reloads
## Input Code

```ts
  @Post('upload')
    @UseInterceptors(FileInterceptor('file', {
        dest: './uploads'
    }))
    uploadFile(@UploadedFiles() files) {
        console.log(files);
    }
```

## Possible Solution

tsc-watch may have hands on this one. Although i dont seem to configure it to exclude uploads directory

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by BrunnerLivio** [comment]
> tsc-watch may have hands on this one.

This is not related to NestJS, therefore I am closing this issue. As you have mentioned, this is most likely a problem of `tsc-watch` or your configuration. Are you sure you have correctly configured to exclude your `uploads` directory?

**Comment by l2ubin** [comment]
for those having reload on upload , remove tsc-watch and use nodemon instead
