### ISSUE TITLE
[feature] use fastify preHandler hook for middleware

### ISSUE THREAD

**Issue by ToonvanStrijp** [nestjs/nest#2791]
## Is your feature request related to a problem? Please describe.
Right now when you use middleware in combination with the fastify adapter you don't get the parsed body and response exposed to the middleware. You can see this when looking at [visual lifecyle](https://github.com/fastify/fastify/blob/master/docs/Lifecycle.md) the middleware is run before the fastify parsing etc starts.

This is different to the express middleware. When using the express adapter you can access the parsed body, query etc.

I would be better and easier to have the same possibilities when using the fastify adapter as well.

## Describe the solution you'd like
This would be easily doable by making us of the [preHandler](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#preHandler) hook.

## Teachability, Documentation, Adoption, Migration Strategy
This brings one breaking change since all the middleware that is using with the fastify adapter now gets the raw request instead of the fastify request. When we change this those users need to change a bit of code to get is working again.

## What is the motivation / use case for changing the behavior?
If we implement this the middleware in fastify acts more the same as in express and is easier to use, right now you've to parse the body manually if needed in the middleware. When using the `preHandler` hook this isn't necessary anymore.

**Comment by kamilmysliwiec** [comment]
See PR for more context
