### ISSUE TITLE
Controllers not available when OnApplicationBootstrap fires

### ISSUE THREAD

**Issue by hardcodet** [nestjs/nest#2795]
## Current behavior

The lifecycle docs state that when `OnApplicationBootstrap` happens: `Called once the application has fully started and is bootstrapped`. However, controllers are not accessible at this time.

Context: I'm trying to register a webhook with Nest during that event. The webhook provider immediately sends a test message to the registered endpoint (my Nest application), and fails because the request is not routed. If I introduce an artificial delay, the registration works.

## Expected behavior

The event should probably fire once the app is indeed ready, and requests are being routed, no? Alternatively, maybe second event? Basically one to finalize after bootstrapping, and one to work when the app is actually live?

## Environment

Nest version: 6.5.3

**Comment by kamilmysliwiec** [comment]
At the moment, we do call `onApplicationBootstrap` hook when the entire application is initialized (async providers are instantiated, modules graph resolved), but before `listen()` is triggered. We should probably change this behavior cc @BrunnerLivio

**Comment by hardcodet** [comment]
Glad to hear! I'd suggest the two event version - one before (as a final setup task), one after listen. That wouldn't break existing code, and there's merit in having both, no?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/2983#issuecomment-770809417
