### ISSUE TITLE
GRPC server cannot receive metadata when wrapped by a request-scope interceptor.

### ISSUE THREAD

**Issue by Reasno** [nestjs/nest#2802]
## Current behavior

Whenever a GRPC server handler is wrapped by a request-scoped interceptor, the GRPC metadata will never be passed into the handler.

## Input Code

In GRPC handlers, there are two arguments should be passed into, data and metadata. 

However, when we wrap a request-scoped interceptor around the handler, only data (args[0]) is passed into the proxy chain at [line 121](https://github.com/nestjs/nest/blob/a53abc92c68a47979b21900f5223566756793a76/packages/microservices/listeners-controller.ts#L121), stopping metadata from propagating. 

## Expected behavior
GRPC handler can get metadata regardless of any interceptors.

## Possible Solution

change 
```ts
return proxy(data);
```
to

```ts
return proxy(...args);
```

at this [line](https://github.com/nestjs/nest/blob/a53abc92c68a47979b21900f5223566756793a76/packages/microservices/listeners-controller.ts#L121)
## Environment

<pre><code>
Nest version: 6.5.0

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Would you like to create PR for this issue?

**Comment by Reasno** [comment]
PR submitted.

**Comment by kamilmysliwiec** [comment]
Fixed in 6.6.0 :)
