### ISSUE TITLE
Cancel pending axios request when Graphql client request is cancel

### ISSUE THREAD

**Issue by vagostep** [nestjs/nest#2817]
## Feature Request
When i use Graphql Module, and make a query that fetch over the server using Axios, when i cancel that query in Playground, the request is not cancelled

## Is your feature request related to a problem? Please describe.

```javascript
@Query()
findAll(): Observable<any[]> {
  return of([]);
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
