### ISSUE TITLE
[DISCUSSION] Access To NestContainer

### ISSUE THREAD

**Issue by shekohex** [nestjs/nest#282]
We Should Have access to `NestContainer` from `NestFactory`
### Why ?
 to have the ability to make 3rd party modules, middlewares, ..etc
to be explicit  I need access to the container to get its modules and then I could Refactor or edit them
anyway I could Make a PR , but I need your Opinion

**Comment by kamilmysliwiec** [comment]
Hi @shekohex,
It'll be possible to inject `ModulesContainer` in the nearest release. With the dynamic modules feature, you will be able to create 3rd party modules very easily. 🙂

**Comment by shekohex** [comment]
And what about Editing or Refactoring the existing Modules ?
It will be awesome and Helpful in some situations

**Comment by wbhob** [comment]
@kamilmysliwiec I have third party module for mongo (https://www.github.com/wbhob/nest-mongo). How will the ModulesContainer do for third party modules?

**Comment by kamilmysliwiec** [comment]
I think the `ModuleContainer` along with the dynamic modules feature should cover most of the available use-cases. About the `NestContainer`, I'm not sure if it's a good decision to make this a part of the public API since it's still possible to access this instance in a hacky-way.

**Comment by myflowpl** [comment]
@kamilmysliwiec You just released v4.5.0 and and dynamic modules are in CHANGELOG, 
but is documentation still under development? 
I can't find any way to learn how to use them

**Comment by mkzaker** [comment]
@kamilmysliwiec documentation please

**Comment by shekohex** [comment]
There's a methods called extractMetadata , hmmm that's interesting , I should look at it tomorrow. 
Until Kamil respond , I will try to figure it out.

**Comment by kamilmysliwiec** [comment]
Here's an explanation https://github.com/nestjs/nest/pull/283
Will provide docs as soon as I can
