### ISSUE TITLE
OpenCV4NodeJS working fine, but fails in Unit Testing

### ISSUE THREAD

**Issue by awe-sim** [nestjs/nest#2824]
Hi,

I started a new Nest project and installed `opencv4nodejs` library which comes with its typings. If I use this library anywhere in my project, it works without any issue. However, it gives errors when used in a test suite. My test suite is as follows:

```
	import { imread, Mat } from 'opencv4nodejs';

	describe('HelloWorld', () => {
		it('should return buffer', () => {
			imread('image.png');
			expect(true).toBe(true);
		});
	});
```

This gives the following error:
```
 FAIL  src/test.spec.ts
  ● Test suite failed to run

    Cannot find module 'test/node_modules/opencv4nodejs/build/Release/opencv4nodejs' from 'cv.js'

    However, Jest was able to find:
        './cv.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'ts'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (../node_modules/opencv4nodejs/lib/cv.js:17:8)
```

Is this an issue with the testing configuration? The application works fine with `OpenCV4NodeJS` and the Test Suite works fine if I comment out the lines calling `OpenCV` functions.

Regards,
Asim

**Comment by BrunnerLivio** [comment]
Seems like you are creating unit tests? In general it is seen as best practice to mock any third party system. What you are doing currently is end to end or integration testing FYI.

To fix this error you probably need to modify your Jest config. Maybe click on the link of the error message. Probably that can help you further.

If you need further assistance, please use our [Discord]( https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
