### ISSUE TITLE
Injection with/in WsException filter

### ISSUE THREAD

**Issue by DiFuks** [nestjs/nest#2826]
H! This request is similar on https://github.com/nestjs/nest/issues/302
I have a global filter in which about 10 dependences (logging of different types of errors, generation of the different statuses of answers for rest, etc.). Everything works thanks to a solution above.
I needed to use the similar filter, but for sockets. I did not find a similar solution. How can I make it?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
