### ISSUE TITLE
Run benchmarks in CI

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#2831]
## Is your feature request related to a problem? Please describe.
Currently we do not track benchmarks on any PR. This is a slippery slope sometimes, so we should establish boundaries using the given load tests.

## Describe the solution you'd like

- On each commit benchmarks should be tested and compared to the master branches stats. 
- *(Optional)* Add a way to track the benchmarks over time (e.g. diagram) 

## Teachability, Documentation, Adoption, Migration Strategy

This feature needs to be executed in multiple steps. To easily store the outcome of each benchmark output, we can use [Codechecks](https://github.com/codechecks) and directly integrate it with our pipeline. @krzkaczor, the maintainer of codechecks, is happy to assist us in this feature request.

- **Rewrite the benchmarks script [benchmarks/run_all.sh](https://github.com/nestjs/nest/blob/master/benchmarks/run_all.sh):** @BrunnerLivio
So we can easily make use of the output (`Requests/sec` and `Transfer/sec`) to store it and compare the values later on with incoming commits. It would make sense to rewrite the script to TS and make use of [node-wrk](https://github.com/sidorares/node-wrk) package, which parses the output of `wrk`.

- **Integrate codechecks:** @krzkaczor
Make use of these values and add a check on each commit, part of the CI.
The values which are important:
  - `Requests/sec` and `Transfer/sec` of NestJS-Express
  - `Requests/sec` and `Transfer/sec` of NestJS-Fastify
  - `Requests/sec` and `Transfer/sec` difference from Express to NestJS-Express
  - `Requests/sec` and `Transfer/sec` difference from Fastify to NestJS-Fastify

## Upcoming challenges

The benchmarks may be unreliable, depending on which hardware it is being executed. In a first phase, we set the codecheck to always succeed. Therefore, in case we realize that the benchmarks are unreliable on CircleCI hardware, we won't get blocked by it. For a period of time we are going to evaluate how reliable the output is. Depending on that we are going to execute a second phase, which will try to make these benchmarks reliable. After the second phase has been executed, the codechecks should fail, in case a commit deviates largely over a certain threshold from the last commit.

**Comment by kamilmysliwiec** [comment]
I'm not sure how credible these tests would be, but it's definitely worth giving it a try. PRs are welcome :)

**Comment by krzkaczor** [comment]
Initial implementation is done: https://github.com/nestjs/nest/pull/2903

Ideas to make more it more stable:
- switch to machine executor
- run benchmarks multiple times and take only best results
- run performance tests on a dedicated machine using BuildKite CI

**Side note**: since you already have codechecks setup in your repo. You can use other useful PR automation. For example, you might like [typecov](https://github.com/codechecks/typecov). Full list: https://github.com/codechecks/awesome-codechecks
