### ISSUE TITLE
Error log is not showed when package doesn't exists.

### ISSUE THREAD

**Issue by dantehemerson** [nestjs/nest#2835]
## Current behavior

I have a project that uses **platform-fastify**.
I created a test and I got the following error:
![image](https://user-images.githubusercontent.com/18385321/63877975-3c8e2b80-c98e-11e9-9e93-6b2971886a58.png)

Looking at the NestJs code I noticed that by default it uses platform-express, so I solved it creating my **fastify-adapter**.

However, note that here makes a log when a package does not exist, but that log does not show it to me.

https://github.com/nestjs/nest/blob/f791b3e6b1d0373cffaf046250420dd2bb9e0a8d/packages/common/utils/load-package.util.ts#L16

Is this an error of NesJs or is it necessary to configure something for the log?

## Expected behavior
Should write the error log when a package does not exist.

## Environment

<pre><code>
Nest version: 6.5.3

 
For Tooling issues:
- Node version: v10.15.3  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by dantehemerson** [comment]
Here is the repo: https://github.com/dantecalderon/nestjs-issue-2835
### Steps to reproduce:
* Install
```
yarn
```

* Run view the response error:
```
yarn test:e2e
```

* Should be something like this:
```
gitpod /workspace/nestjs-issue-2835 $ yarn test:e2e
yarn run v1.17.3
$ jest --config ./test/jest-e2e.json
  ●  process.exit called with "1"

      11 |         }).compile();
      12 |
    > 13 |         app = moduleFixture.createNestApplication();
         |                             ^
      14 |         await app.init();
      15 |     });
      16 |

      at Object.loadPackage (../node_modules/@nestjs/common/utils/load-package.util.js:12:17)
      at TestingModule.createHttpAdapter (../node_modules/@nestjs/testing/testing-module.js:24:56)
      at TestingModule.createNestApplication (../node_modules/@nestjs/testing/testing-module.js:12:43)
      at Object.beforeEach (app.e2e-spec.ts:13:29)

 RUNS  test/app.e2e-spec.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
gitpod /workspace/nestjs-issue-2835 $
```

**Comment by undervane** [comment]
@dantehemerson I've found by removing `process.exit(1)` makes the error to be shown, however of course this is not a solution. 😉

![image](https://user-images.githubusercontent.com/21361339/64034946-ea950380-cb4f-11e9-8bdb-deea5532d414.png)


**@nestjs/common/utils/load-package.util.ts**
```ts
import { Logger } from '../services/logger.service';

const MISSING_REQUIRED_DEPENDENCY = (name: string, reason: string) =>
  `The "${name}" package is missing. Please, make sure to install this library ($ npm install ${name}) to take advantage of ${reason}.`;

const logger = new Logger('PackageLoader');

export function loadPackage(
  packageName: string,
  context: string,
  loaderFn?: Function,
) {
  try {
    return loaderFn ? loaderFn() : require(packageName);
  } catch (e) {
    logger.error(MISSING_REQUIRED_DEPENDENCY(packageName, context));
    // Removing line below makes the error to be shown
    // process.exit(1);
  }
}
```

**Comment by dantehemerson** [comment]
> ```js
>     logger.error(MISSING_REQUIRED_DEPENDENCY(packageName, context));
>     // Removing line below makes the error to be shown
>     // process.exit(1);
>   }
> }
> ```

@undervane  @kamilmysliwiec 
I think that could solve the problem. 
I think calling process.exit (1) interrupts the logger finishing his work

**Comment by kamilmysliwiec** [comment]
Calling `process.exit(1)` is required.

It seems that `jest` is gathering console logs to show them using their own reporters after running the test (OR hide if the corresponding configuration option is enabled). In this case, you should change your `jest` configuration (to show logs immediately - I'm not sure if this is still possible).  Otherwise, you won't see logs because the process is forcefully closed before `jest` prints grouped logs. It's not the NestJS issue.
