### ISSUE TITLE
Update code examples to use AppModule instead of ApplicationModule

### ISSUE THREAD

**Issue by johnbiundo** [nestjs/nest#2839]
## Feature Request

Change examples to use AppModule instead of obsolete ApplicationModule.

Compatibility with docs and typescript starter repo.

@kamilmysliwiec, would this break any tests?

**Comment by kamilmysliwiec** [comment]
Sounds great! Would you like to create a PR for that? 

> @kamilmysliwiec, would this break any tests?

Nope :)

**Comment by johnbiundo** [comment]
Yep, on it :)

**Comment by johnbiundo** [comment]
This is covered by #2970
