### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [nestjs/nest#2844]
## Is your feature request related to a problem? Please describe.

There isn't a programmatic way to access an Ethereum address to send funds to for this project

## Describe the solution you'd like

I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, I'm building a project that allows developers to setup one recurring donation that is split between all of their dependencies with an Ethereum address: https://sustainus.io

## Teachability, Documentation, Adoption, Migration Strategy

GitHub Sponsors takes care of some of this with their nice UI. You could point people towards an Ethereum wallet, or give a link to Sustainus

## What is the motivation / use case for changing the behavior?

Enabling Ethereum donations, which have a number of potential benefits

**Comment by kamilmysliwiec** [comment]
We don't plan to accept donations in cryptocurrencies for now.
