### ISSUE TITLE
ValidationPipe transforms before validating

### ISSUE THREAD

**Issue by IGassmann** [nestjs/nest#2856]
# Bug Report

## Current behavior
If a property from a DTO has transformation and validation decorators the transformation decorator will be applied before the validation ones. Since the validators work essentially with the string type, they become useless when those strings are converted to objects in the transformation step.

The following code won't work. `@IsMongoId` will never pass, because the array of strings is transformed into an array of `ObjectID` before it is used.

If we remove the `@IsMongoId` decorator and the request contains an invalid `ObjectID` string, the server will throw a 500 error, because it can't instantiate the object `ObjectID`.

## Input Code

```ts
@IsNotEmpty()
@IsArray()
@IsMongoId({
   each: true
 })
@Transform(strings => strings.map(string => new ObjectID(string)))
readonly categoriesId: ObjectID[];
```

## Expected behavior
The validation step should happen before the transformation step.

## Environment

<pre><code>
Nest version: v10.16.1

**Comment by felixhayashi** [comment]
> The validation step should happen before the transformation step.

disagree here, often serialization needs to happen first because data is sent encoded and first needs to be unwrapped/decoded before any validation should occur.

Say frontend sends a date string and one uses `IsDate` – this validator only works if the transformer first transforms the date-string into a Date instance.

**Comment by kamilmysliwiec** [comment]
That's the whole idea of the existing `ValidationPipe`. If your requirements are different and you need to first validate the input, you can create another pipe by looking at the source code of `ValidationPipe`, it should be pretty simple.
