### ISSUE TITLE
Inject REQUEST into a singleton service somehow

### ISSUE THREAD

**Issue by bengry** [nestjs/nest#2861]
I have a scenario that seems valid to me, but I can't get it working with Nest properly.
I'm using TypeORM (using @nestjs/typeorm), and want to give it a custom logger - which will basically just log the user who performed the query for each one. The user can be gotten via the express.Request object.
This is what I did ([also here](https://codesandbox.io/s/nest-typescript-starter-kru7r), though not runnable without plugging in an SQL connection):
```typescript
// current-user.service.ts
@Injectable({ scope: Scope.REQUEST })
export class CurrentUserService {
  get currentUser(): string | null {
    if (!this.request || !this.request.user) {
      return null;
    }

    return this.request.user.email;
  }

  constructor(@Optional() @Inject(REQUEST) private request: Request) {}
}

// logger.service.ts
@Injectable()
export class LoggerService extends Logger {
  constructor(private readonly moduleRef: ModuleRef) {
    super();
  }

  log(message: any, context?: string) {
    super.log(this.formatMessage(message), context);
  }

  private formatMessage(message: any) {
    const currentUserService = this.moduleRef.get(CurrentUserService, {
      strict: false,
    });
    return `[${currentUserService.currentUser}]: ${message}`;
  }
}

// typeorm-logger.service.ts
@Injectable()
export class TypeormLogger implements Logger {
  // Logger is imported from `typeorm`
  constructor(private logger: LoggerService) {}

  logQuery(query: string) {
    // there are more params, don't matter for the sake of the argument
    this.logger.log(query);
  }
}

// logger.module.ts
@Module({
  providers: [LoggerService, TypeormLogger],
  exports: [LoggerService, TypeormLogger],
})
export class LoggerModule {}

// app.module.ts
@Module({
  imports: [
    TypeOrmModule.ForRootAsync({
      imports: [LoggerModule],
      inject: [TypeormLogger],
      useFactory: (typeormLogger: TypeormLogger) => {
        return {
          type: 'mysql',
          logger: typeormLogger,
        };
      },
    }),
  ],
})
export class AppModule {}
```

I get an error about not being able to do `moduleRef.get()` on a request-scoped service, but when I do `moduleRef.resolve()` instead I both get it as a `Promise` (which I really want to avoid, since this is just logging after all), as well as a new instance of `CurrentUserService` but with a `request === undefined` for some reason.

Please advise - I can't figure out how to inject `REQUEST` for the logging, inside TypeORM.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by bengry** [comment]
@kamilmysliwiec I think this may be an actual bug (in some form), so I posted it as a question since I'm not sure - but maybe the labelling will change if it is indeed an issue with Nest (i.e. the above is not supported).

I also tried asking in Discord (under #support), but so far got no replies.

**Comment by kamilmysliwiec** [comment]
It's not an issue. You can't use `get()` to retrieve request-scoped instances + you can't inject request-scoped instances to singleton, statically scoped services.
