### ISSUE TITLE
Mongoose Connection outside NestJS for Lambda

### ISSUE THREAD

**Issue by WiesBen** [nestjs/nest#2867]
Hi everybody,

we are running nestjs on AWS Lambda similar like that: https://keyholesoftware.com/2019/05/13/aws-lambda-with-nestjs/

Unfortunately the mongoose part of nestjs does not close the database connections, so my mongo cluster is reaching a connection limit even if no one is working on that.

The best practices on mongoose docs says this: https://mongoosejs.com/docs/lambda.html

Does anybody know how to achieve this in combination with the nestjs framework? 

Regards

**Comment by kamilmysliwiec** [comment]
You have to call `app.close()` to close mongoose connection.

**Comment by WiesBen** [comment]
Sorry to say, but at which point do you mean?

**Comment by WiesBen** [comment]
I opened a stackoverflow for that, maybe this is misunderstood here. The link to the topic: https://stackoverflow.com/questions/57782360/mongoose-connection-outside-nestjs-for-lambda
