### ISSUE TITLE
Better HttpException class

### ISSUE THREAD

**Issue by valerio-battaglia** [nestjs/nest#2869]
## Is your feature request related to a problem?
The current problem with the included HttpException is that they are wrapped up to act as an `Error` class, even though they are not implemented as excepted. Moreover, the object containing the Http exception is duplicated under two different keys. This problem arises especially when you throw the Exception which shows a stack trace not clear as below:
```
Error: [object Object],
	at ContactService.getContacts(...)
	...
```

## Describe the solution you'd like
I would like to have an HttpException easy to trace, easy to customize or swap out of the box (same approach as the other NestJS tools). There exists great library for HTTP exceptions such as [@hapi/boom](https://github.com/hapijs/boom), which can do the job and be used under the hood.

## Teachability, Documentation, Adoption, Migration Strategy
This is a change under the hood of the implementation of the base class HTTPException.

## What is the motivation / use case for changing the behavior?
As stated before, hard to track or customize. Let's take this example:
```ts
@Injectable()
export class ContactService {
	public async getContacts(id: string): Promise<Contact[]> {
		// [...] some external calls
		const [res, otherRes] = await Promise.all([req, otherReq]);
		if (res.result.type === 'Failed') {
			// this exception will have a trace to here with [Object object] 
			// which can be understood only by looking at the code
			throw new NotFoundException(`${res.result.message}`);
		}
		// [...] some other logic
	}
}
```

## System info
NestJS: 6.5.3
Node.js: 12.9.0
OS: Windows_NT x64 10.0.17763

**Comment by kamilmysliwiec** [comment]
What version of NestJS and Node do you use?

**Comment by valerio-battaglia** [comment]
I added it to the comment too, here:
NestJS: 6.5.3
Node.js: 12.9.0
OS: Windows_NT x64 10.0.17763

**Comment by kamilmysliwiec** [comment]
Can you share a minimal reproduction repository? Since 6.5.0 we should be able to easily serialize `message`. Just tested locally and it works for me.

>  Moreover, the object containing the Http exception is duplicated under two different keys. 

We plan to change this (we actually have already done that but we had to revert this change because it should be considered as a breaking one = hence, we'll make it as a part of 7.0.0 release).

**Comment by nartc** [comment]
@valerio-battaglia Are you talking about Exception that will be returned to the clients upon error requests? How about using an Exception Filter? 

```typescript
import {
  ArgumentsHost,
  Catch,
  ExceptionFilter,
  HttpException,
  HttpStatus,
} from '@nestjs/common';
import { ApiException } from '../api-exception.model';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(error: any, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const res = ctx.getResponse();
    const req = ctx.getRequest();
    const statusCode = error.getStatus();
    const stacktrace = error.stack;
    const errorName = error.response.name || error.response.error || error.name;
    const errors = error.response.errors || null;
    const path = req ? req.url : null;

    if (statusCode === HttpStatus.UNAUTHORIZED) {
      if (typeof error.response !== 'string') {
        error.response.message =
          error.response.message ||
          'You do not have permission to access this resource';
      }
    }

    const exception = new ApiException(
      error.response.message,
      errorName,
      stacktrace,
      errors,
      path,
      statusCode,
    );
    res.status(statusCode).json(exception);
  }
}
```

I'm using `Swagger` and `ApiException` is a model that will be exposed on SwaggerUI so I use `Exception Filter` to transform all `HttpException` into `ApiException` so my Api error model will be consistent. I don't know if this solves your use-case.

**Comment by valerio-battaglia** [comment]
@nartc I am actually using a similar model, it is a filter that catches all `HttpException` and converts them into `ApolloError` to be nicely formatted in the GraphQL response. The problem that I noticed is that the `Stacktrace` of these thrown errors are not correctly serialized.
Let me investigate what would be our goal in terms of Error traceability and then I will come back and tell you more about what is the actual problem.

**Comment by valerio-battaglia** [comment]
Here you go: https://github.com/valerio-battaglia/nest-error-serialization

If you run `$ npm run test` you will see the following failing output tests:
```
● AppController › root › should return a NOT nicely formatted error

    thrown: [Error: [object Object]]Error: [object Object]

       9 |   getMagic(errorType: number): string {
      10 |     if (errorType === 1) {
    > 11 |       throw new ServiceUnavailableException(
         |             ^
      12 |         'The magic is not available at the moment.',
      13 |       );
      14 |     } else if (errorType === 2) {

      at AppService.getMagic (app.service.ts:11:13)
      at AppController.getMagic (app.controller.ts:15:28)
      at Object.<anonymous> (app.controller.spec.ts:23:28)

  ● AppController › root › should return a nicely formatted error

    The magic is not available at the moment.

      13 |       );
      14 |     } else if (errorType === 2) {
    > 15 |       throw new Error('The magic is not available at the moment.');
         |             ^
      16 |     }
      17 |
      18 |     return 'some magic';

      at AppService.getMagic (app.service.ts:15:13)
      at AppController.getMagic (app.controller.ts:15:28)
      at Object.<anonymous> (app.controller.spec.ts:27:28)
```

As you can see, when you throw the base `Error` class it is serialized nicely everywhere it will be catch and logged: Tests, Logging, ...
But for `HttpException` is not the case, it is serialized to `[Error: [object Object]]...` and it is not really explicative. This happens also for example in the NestJS GraphQL package.

**Comment by kamilmysliwiec** [comment]
@valerio-battaglia thanks, I'll take a look asap

**Comment by valerio-battaglia** [comment]
I've also added the example with GraphQL.
If you open the playground at `/graphql` and use the following queries to replicate the same issue:
```gql
query NOT_NICE {
  magic(error: 1) {
    message
  }
}

query NICE {
  magic(error: 2) {
    message
  }
}
```

You will see that the stacktrace in the response is also affected by the same issue.

**Comment by kamilmysliwiec** [comment]
So it sounds like Jest is trying to use `.message` property directly, instead of serializing the entire `Error` object. We could temporarily work around this issue by adding `toString()` method to `message`. That would lead to something like this:

```
thrown: [Error: {"statusCode":503,"error":"Service Unavailable","message":"The magic is not available at the moment."}]Error: {"statusCode":503,"error":"Service Unavailable","message":"The magic is not available at the moment."}
```

**Comment by valerio-battaglia** [comment]
I think that it would be better to use the `error.message` property as a `string` instead of a custom object, as well as set the `error.name` property to be compliant with the `Error` base class specifications (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Parameters). And use a custom property to wrap all other info that we would need for the `Exception`.

**Comment by kamilmysliwiec** [comment]
Yes, I know, but as I said here https://github.com/nestjs/nest/issues/2869#issuecomment-527367391 - we can't do it yet.

**Comment by valerio-battaglia** [comment]
Yes, I understand it is a breaking change and that it will be added for the next major release (such as 7.0.0). Now that the issue is clear, I still want to point out that using the same approach of wrapping external library under the hood for the `Exception` would be a great.

**Comment by kamilmysliwiec** [comment]
We want to reduce the number of external libraries as much as possible. The plan is to stick with the current solution, just refactor invalid properties together with the next major release.
