### ISSUE TITLE
onModuleDestroy() not called

### ISSUE THREAD

**Issue by amit12cool** [nestjs/nest#2893]
I need to close some db connections as soon as my application is killed.I decided to close the db connections in onModuleDestroy function but it never gets called.I have implemented the interface for onModuleDestroy in my class though.

Anything I'm missing here?
Please let me know will onModuleDestroy () not be called when I kill my application?

**Comment by jmcdo29** [comment]
Did you add `app.enableShutdwonHooks()` in your `main.ts`?

**Comment by amit12cool** [comment]
Nopes I didn't. Also do I need to add listenasync instead listen? Both seems to be same to me.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jmcdo29** [comment]
Apologies, shutdown hooks are not necessarily needed, it should be okay with just OnModuleDestroy which gets called with `app.close()`. Do you have a repo showing the problem?

**Comment by amit12cool** [comment]
I don't want to call app.close() explicitly as I want onModuleDestroy should be called on app killed through let's say console etc.
Do you really need the repo as my use case is straight forward.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amit12cool** [comment]
Apparently, when I call app.close() after app.listen() onModuleDestroy () does get called but my app is also killed which is what don't to kill the app through code rather it when killed abruptly or deliberately by ctrl+ c in terminal onModuleDestroy should be called.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jmcdo29** [comment]
If your use case is for `ctrl + c` then that is a SIGKILL and should be handled with the shutdown hooks instead of the module destroy events. [Here is some more information about application shutdown](https://docs.nestjs.com/fundamentals/lifecycle-events#onapplicationshutdown)

**Comment by amit12cool** [comment]
Another use case is app is running in a container on k8s pod and we bring down the container.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jmcdo29** [comment]
K8s and Heroku are also mentioned as use cases for using application shutdown hooks. It's mentioned in the link I posted

**Comment by amit12cool** [comment]
Ok..Thanks. So that means I need to use app shutdown events rather than onModuleDestroy.

Last question:- what's the use case for onModuleDestroy then?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BrunnerLivio** [comment]
@amit12cool  It often depends on the integrations. For example, if you use nestjs/typeorm, then the DB closes on `onApplicationShutdown` (currently it is still using `onModuleDestroy` but we are going to change it to `onApplicationShutdown`). With the upcoming version of `nestjs/terminus`, all HTTP routes would start to send 503 responses on `beforeApplicationShutdown`. Depending on what you are trying to achieve, you’d need to place it into the correct lifecycle event. For instance, if you’d need to do DB operations, right before the application closes, you’d go for `beforeApplicationShutdown`. Maybe you’ll need to do other operations, while HTTP still is able to respond with 2xx status code, then you’d do it in `onModuleDestroy`. @johnbiundo and I are currently improving the docs :)

**Comment by amit12cool** [comment]
Ok..that makes sense to me. Doubt remains here is, does onModuleDestroy is called as a lifecycle event or its explicitly called when app.close() is called from the code?

**Comment by amit12cool** [comment]
Also since onModuleDestroy and onApplicationShutdown() are not promise based how can i call my promise based functions in onModuleDestroy or onApplicationShutDown functions?

**Comment by BrunnerLivio** [comment]
@amit12cool what do you mean with `not promise based`?  As you can see here we await all the hooks, so your example should work fine.

https://github.com/nestjs/nest/blob/c39d4fc7989646625d1ef494c2acd871b28c4ee2/packages/core/nest-application-context.ts#L169-L172

**Comment by amit12cool** [comment]
This works. Thanks for your replies.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
