### ISSUE TITLE
OnModuleDestroy does not await async methods

### ISSUE THREAD

**Issue by jasperblues** [nestjs/nest#2895]
## Current behavior

On module destroy is invoked, however if it is an async method, it does not appear to be awaited. 

## Input Code

```ts
export class DatabaseModule implements OnModuleDestroy {

    constructor(
      private readonly pool: ConnectionPool) {
    }

    public async onModuleDestroy(): Promise<void> { // <---- THIS METHOD NOT AWAITED
        await this.pool.end();   
    }

}
```

## Expected behavior
`onModuleDestroy` method is awaited. 

## Possible Solution
Detect if it is a promise and await in that case. 

In our specific case we set connection pool IDLE_TIMEOUT to a reasonable value. 

## Environment

<pre><code>
6.5.3

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:
#2893 related?

**Comment by BrunnerLivio** [comment]
`onModuleDestroy` gets invoked if `app.closed()` gets called (which works fine in the latest version).

My guess you want that `onModuleDestroy` gets called when the process gets shutdown by a system signal (e.g. SIGINT)? For that you'd need to call `app.enableShutdownHooks()`. [More on that topic](https://docs.nestjs.com/fundamentals/lifecycle-events#onapplicationshutdown).

**Comment by jasperblues** [comment]
No, I want `onModuleDestroy` to be invoked when `app.close()` is called, as per documentation. When this method is asynchronous, it does not _appear_ to be awaited. (I haven't checked this deeply - reported findings in case they're useful). 

*Steps to Repro:*

```ts
    export class DatabaseModule implements OnModuleDestroy {

    constructor(
      private readonly pool: ConnectionPool) {
    }

    public async onModuleDestroy(): Promise<void> { // <---- THIS METHOD NOT AWAITED
        await this.pool.end();   
        console.log(`Hello`);
    }

}```


*Jest Test* 

```ts    
    beforeAll(async () => {
        app = await TestContext.createTestApp();
        jobRepo = app.get(ScheduledJobRepository);
    });

    afterAll(() => {
        app.close();
    });
```

*Expected:* 

- Hello is printed to console

*Actual:*

Jest warns that the console is unavailable as it has already shut down.

**Comment by BrunnerLivio** [comment]
As I mentioned, I have tested whether `onModuleDestroy` gets awaited. Judging from Jest test, maybe you need to write the following:

```ts
afterAll(async () => {
  await app.close();
});
```
->  You forgot to await the `app.close()`

---

If that still does not work, then I assume the `this.pool.end()` does not correctly resolve. You can try it out by replacing `await this.pool.end()` with `await new Promise(resolve => setTimeout(resolve, 3000))`, to verify whether NestJS correctly awaits the `onModuleDestroy` in your context. If so, the test should last around `~3s` and then you'd know that `await this.pool.end()` is faulty.

Let me know whether you were able to get more insights :)

**Comment by jasperblues** [comment]
@BrunnerLivio Doh! That was surely it! (I didn't test because not near that code right now, however in the unlikely event it was something else I'll post more feedback).
