### ISSUE TITLE
Nest dependency resolution issue with tsconfig paths and same directory imports

### ISSUE THREAD

**Issue by raychz** [nestjs/nest#2897]
## Bug Report
NOTE: This is not a duplicate of #986 as I am already using tsconfig-paths-bootstrap.js.
## Current behavior
I've set a few different paths in tsconfig.json to make importing of controllers, entities, services, etc. easier to deal with.  Relevant portion of tsconfig.json:
```ts
    ...
    "baseUrl": "./src",
    "paths": {
      "@hello/controllers": [
        "./controllers"
      ],
      "@hello/entities": [
        "./entity"
      ],
      "@hello/services": [
        "./services"
      ]
    },
    ...
```

I've also created barrel files (index.ts) within the src/controllers/, src/entity/, and src/services/ directories that re-exports all of the classes that I need from within those directories.

Everything works as expected when importing a service from a file that is within my controllers directory. Example:
```ts
// src/controllers/comment.controller.ts
// This works
import { CommentService } from '@hello/services';

@Controller()
export class CommentController {...}
```

Things do **NOT** work when importing a service from another service file that is within the **same** directory. Example
```ts
// src/services/comment.service.ts
// This does NOT work
import { StoryService, UserService } from '@hello/services';
// StoryService, UserService, and CommentService are in the src/services directory 

@Injectable()
export class CommentService {...}
```
The error that I get when doing the above is:
```
Error: Nest can't resolve dependencies of the CommentService (?, +). Please make sure that the argument at index [0] is available in the AppModule context.
```

## Expected behavior
I expect dependencies to resolve using a path defined in tsconfig.json, even if they're being imported from within the same directory.

## Possible Solution
My current workaround is to import the files using relative paths:
```ts
// src/services/comment.service.ts
// This does work
import { StoryService } from './story.service';
import { UserService } from './user.service';
// I'd prefer to do this:
// import { StoryService, UserService } from '@hello/services';

@Injectable()
export class CommentService {...}
```

## Environment

<pre><code>
@nestjs/common@5.7.4
@nestjs/core@5.7.4
typescript@3.6.2

**Comment by kamilmysliwiec** [comment]
See my responses here:
https://github.com/nestjs/nest/issues/1181#issuecomment-430037003
https://github.com/nestjs/nest/issues/1181#issuecomment-430197191

Barrel files have their own implication which we should be aware of. Although, import statements look nicer with them, it's not always the best idea to use them

**Comment by raychz** [comment]
@kamilmysliwiec I was able to fix this while still using barrel files.

**EXPORT ORDER MATTERS**

In my `index.ts` barrel file, I was exporting the comment service before the user and story services.  However, the comment.service.ts class imports story.service.ts and user.service.ts. Story and user must be exported **BEFORE** comment.

Before:
```ts
// src/services/index.ts
// This does NOT work 
// and throws the "Nest can't resolve dependencies of the CommentService..." error
export * from './comment.service';
export * from './story.service';
export * from './user.service';
```

After with correct ordering:
```ts
// src/services/index.ts
// This works!
export * from './story.service';
export * from './user.service';
export * from './comment.service';
```

Now I can use the import path in my tsconfig.json in the comment service:
```ts
import { StoryService, UserService } from '@hello/services';

@Injectable()
export class CommentService {...}
```

Are there any other known gotchas with using barrel files in this case?  I'm using a single root app module (no feature modules) and so far haven't seen any other weird issues.
