### ISSUE TITLE
WsExceptionFilter only refers to a type.

### ISSUE THREAD

**Issue by binarytracer** [nestjs/nest#2898]
## Bug Report
- either Me or the docs missed something/somewhere?

## Current behavior
following this **[guide](https://docs.nestjs.com/websockets/exception-filters#filters)**
got this error: 
 ```sh
error TS2693: 'WsExceptionFilter' only refers to a type, but is being used as a value here.
```

## Input Code
```typescript 
import { SubscribeMessage, WebSocketGateway, WsResponse, WsException } from '@nestjs/websockets';
import { Socket } from 'socket.io';
import { Observable, from } from 'rxjs';
import { map } from 'rxjs/operators';
import { UseFilters, WsExceptionFilter } from '@nestjs/common';
import { log } from './logger';

@WebSocketGateway()
export class FirstTimerGateway {
  @UseFilters(new WsExceptionFilter())
  @SubscribeMessage('events')
  onEvent(client, data: any): WsResponse<any> {
    const event = 'events';
    return { event, data };
  }
```
## Expected behavior
- I think I should not be getting this error.

## Environment

<pre><code>
[System Information]
OS Version     : Linux 4.15
NodeJS Version : v12.10.0
NPM Version    : 6.11.3
[Nest Information]
platform-socket.io version : 6.6.3
platform-express version   : 6.6.3
websockets version         : 6.6.3
mongoose version           : 6.1.2
passport version           : 6.1.0
swagger version            : 3.1.0
common version             : 6.6.3
core version               : 6.6.3
jwt version                : 6.1.1

</code></pre>

**Comment by kamilmysliwiec** [comment]
In this example, `WsExceptionFilter` is "your" custom filter implementation, same as here https://docs.nestjs.com/websockets/exception-filters#inheritance `AllExceptionsFilter`.

> The custom filters feature is supported as well and works equivalently. Here is an example that makes use of a manually instantiated method-scope filter (class-scoped works too):

**Comment by binarytracer** [comment]
i gonna closed this idiotic question if mine.

**Comment by binarytracer** [comment]
thanks btw.
