### ISSUE TITLE
MiddlewareConsumer.apply type resolution: Dependency Injection resolution seems incorrect

### ISSUE THREAD

**Issue by joshboley** [nestjs/nest#2901]
## Current behavior

When applying middleware using `MiddlewareConsumer.apply(<some_type>)`, and all of the following are true:

1. `<some_type>` is imported from a different module than `AppModule` (let's call it `Module1`) AND,
2. `<some_type>` is an `@Injectable()` class AND,
3. `<some_type>` expects an `injected dependency` and said dependency is encapsulated in `ModuleA`

Then an error is thrown indicating that the `injected dependency` is not able to be resolved in `AppModule`.

However, if instead of calling `MiddlewareConsumer.apply(<some_type>)`, you:
1. Inject `<some_type>` via the `AppModule` constructor AND,
2. Call `MiddlewareConsumer.apply(<some_type_instance_via_AppModule_constructor>.use)`

Then it works as expected because we're using the `apply` override of passing a function instead of a type.

This is difficult to describe in words, but the code snippets below should make the issue clear.

## Input Code

This code breaks:
```ts
@Injectable
class SomeMiddleware {
    constructor(
        @Inject(PROVIDER_A) private readonly providerA: any
    ) {}
}
=====================================================================
providerA = {
    provide: PROVIDER_A,
    useValue: 'waffles'
};
@Module({
    providers: [
        providerA,
        SomeMiddleware
    ],
    exports: [
        SomeMiddleware
    ]
}),
class Module1 {}
======================================================================
@Module({
    imports: [Module1]
}),
class AppModule {
    configure(consumer: MiddlewareConsumer) {
        consumer
            // ** Unable to resolve PROVIDER_A dependency for SomeMiddleware because the dependency is unknown by AppModule
            .apply(SomeMiddleware)
            .forRoutes('*');
    }
}
```

This works, but seems incorrect because now internal module providers are being exported:
```ts

@Injectable
class SomeMiddleware {
    constructor(
        @Inject(PROVIDER_A) private readonly providerA: any
    ) {}
}
=====================================================================
providerA = {
    provide: PROVIDER_A,
    useValue: 'waffles'
};
@Module({
    providers: [
        providerA,
        SomeMiddleware
    ],
    exports: [
        providerA, // ** Add this line
        SomeMiddleware
    ]
}),
class Module1 {}
======================================================================
@Module({
    imports: [Module1]
}),
class AppModule {
    configure(consumer: MiddlewareConsumer) {
        consumer
            // ** Now it works because of the extra export above
            .apply(SomeMiddleware)
            .forRoutes('*');
    }
}

```

This works without exposing encapsulated module providers, but makes me think there's a bug in how the type is resolved inside `apply`:

```ts

@Injectable
class SomeMiddleware {
    constructor(
        @Inject(PROVIDER_A) private readonly providerA: any
    ) {}
}
=====================================================================
providerA = {
    provide: PROVIDER_A,
    useValue: 'waffles'
};
@Module({
    providers: [
        providerA,
        SomeMiddleware
    ],
    exports: [
        SomeMiddleware
    ]
}),
class Module1 {}
======================================================================
@Module({
    imports: [Module1]
}),
class AppModule {
    constructor(
        private readonly middleware: SomeMiddleware,
    ) {}
    configure(consumer: MiddlewareConsumer) {
        consumer
            // ** This works by passing a reference to SomeMiddleware.use
            .apply(this.middleware.use.bind(this.middleware))
            .forRoutes('*');
    }
}

```

## Expected behavior

The first code snippet above should resolve dependencies correctly like so`.apply(SomeMiddleware)` without having to also `export` encapsulated module dependencies.

## Possible Solution

I tried to do some triage and think through possible solutions.  Unfortunately, I'm not fully wrapping my mind around the module and dependency graphing.  It does appear the main issue lies [here](https://github.com/nestjs/nest/blob/master/packages/core/injector/injector.ts#L474).  It appears the `||` was originally added in order to encapsulate providers that aren't exported.  Unfortunately, there doesn't appear to be any logic that to allow use of a provider if the `wrapper` and provider are contained in the same module.  Perhaps there's a way to link the wrapper and provider back to the same module and implement logic in this location to allow the provider to be used even if `exports.has(name)` is false.  If that exists, I wasn't able to figure out the link.  This functionality obviously works when the App Module bootstraps because (as mentioned above) injecting via the constructor works.  I just haven't been able to wrap my mind around exactly _why_ it works in one place but not the other.  I may be missing something simple.

EDIT: After looking into this more, I'm curious if `MiddlewareResolver` always creating a new instance of `Injector` could be the issue...but using the existing `Injector` in the caller doesn't seem to work for me. https://github.com/nestjs/nest/blob/master/packages/core/middleware/resolver.ts#L7

## Environment

<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: 10.16.0  
- Platform: Mac  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
```typescript
providers: [
        providerA,
        SomeMiddleware
],
exports: [
        providerA, // ** Add this line
        SomeMiddleware
]
```

This code is invalid - you should never put middleware in `providers` array. Middleware is not a provider. https://docs.nestjs.com/middleware

```typescript
class AppModule {
    configure(consumer: MiddlewareConsumer) {
        consumer
            // ** Unable to resolve PROVIDER_A dependency for SomeMiddleware because the dependency is unknown by AppModule
            .apply(SomeMiddleware)
            .forRoutes('*');
    }
}
```

In the above example, `SomeMiddleware` becomes a part of the `AppModule` which means that this module has to either **provide** `PROVIDER_A` or import a module which exports `PROVIDER_A`

**Comment by joshboley** [comment]
@kamilmysliwiec I see what you're saying.  I can do it that way.  It may be worth clarifying in the documentation that injecting dependencies into middleware classes works differently than it does in other classes (since you can't modularize and encapsulate middleware along with its dependencies).

On a side note, would you be able to share the architectural reasoning behind why middleware is not considered a provider?

For context, the use case we have is that we have some shared middleware that calculates response times and logs them.  We are sharing this code via an npm package between multiple apps.  My goal was to encapsulate all of the middleware's dependencies into a single module so that the AppModule could simply import the entire module and pass the injection token of the middleware to the `apply` function.
