### ISSUE TITLE
Transport - Nats request/response behavior

### ISSUE THREAD

**Issue by izio38** [nestjs/nest#2905]
When using NATS as the message transporter, I notices some `unexpected behaviour`. In fact, the `nats` library on npm doesn't work the same as work the NestJs Nats transport.

## 1
Request/Response from a non-NestJs application to a NestJs application:
This code is supposed subscribe to the `MyRequest` response and emit a `MyRequest` event. It does work well when the listener an `@EventPattern()`.
**The requester**
```ts
natsClient.requestOne('MyRequest', JSON.stringify(sendParam), {}, 1000, function(response: any) {
    console.log(response);
});
```
**NestJs Listener**
```ts
@EventPattern("MyRequest")
public myRequest(param) {
    return {status: "ok"};
}
```
With this configuration I can't get a message. I did inspect the nats logs with shows us:
```
nats_1           | [1] 2019/09/08 20:54:13.477215 [TRC] 172.20.0.8:49818 - cid:29 - <<- [SUB _INBOX.W6L0JU4O11PM9ZC8R44PTT.* 2]
nats_1           | [1] 2019/09/08 20:54:13.477247 [TRC] 172.20.0.8:49818 - cid:29 - <<- [PUB MyRequest _INBOX.W6L0JU4O11PM9ZC8R44PTT.W6L0JU4O11PM9ZC8R44Q28 25]
nats_1           | [1] 2019/09/08 20:54:13.477255 [TRC] 172.20.0.8:49818 - cid:29 - <<- MSG_PAYLOAD: ["{\"id\":\"TEST\",\"test\":\"OK\"}"]
nats_1           | [1] 2019/09/08 20:54:13.477277 [TRC] 172.20.0.7:60752 - cid:27 - ->> [MSG MyRequest 2 _INBOX.W6L0JU4O11PM9ZC8R44PTT.W6L0JU4O11PM9ZC8R44Q28 25]

```
In fact: `MyRequest 2` is the message sent by the NestJs return.

My first question is: **How to deal with this?** Should I firstly listen to `MyRequest 2` before sending `MyRequest` message, then remove the listener?

Or is there a way to configure this behavior?

## 2
Request/Response NestJs application to a non-NestJs application:

This one is more simple but still annoying. I'm forced to pass an `id` property when send a request to a non-NestJS application (I guess NestJs took the best option it has, but it's difficult to deal with). I'm always thinking: __I am sending to a non-NestJS app or a NestJs app?__ 

**Non-NestJs Sender**
```ts
// Subscribe to a Nats message.
natsClient.subscribe(
  "Api.Mailer.To.Mailer:Send.Mail.Requested",
  { queue: "nats-mailer" },
  (message, replyTo) => {
        // ...
    }).then(() => {
        // .id is required by NestJS in order to know that is a response.
        natsClient.publish(replyTo, { id: message.id, status: "success" });
    }).catch((error) => {
        natsClient.publish(replyTo, { id: message.id, status: "error", error });
    });
  }
);
```

I do not blame anything, just exposing the fact that this usage isn't that simple.
It's possible I misunderstood something in here, please let me know.

If anyone have a simpler solution, please let me know.

Izio.

**Comment by kamilmysliwiec** [comment]
Let's track this issue here https://github.com/nestjs/nest/issues/2540

**Comment by johnbiundo** [comment]
This topic is discussed extensively here.  Hopefully it helps!  https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-1-p3
