### ISSUE TITLE
Query param like tag[location] = 'US', 'India'

### ISSUE THREAD

**Issue by amit12cool** [nestjs/nest#2906]
I could not find any feature support for the following url

http://abcd.com/efgh?tag[location]='US','India'&tag[area]='Florida','Delhi'

Im able to give normal strings in the query params and parse them in Nestjs but not able to figure out the how the aove query param be parsed in the controller nestjs.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
