### ISSUE TITLE
Pass custom values in provider constructor

### ISSUE THREAD

**Issue by amit12cool** [nestjs/nest#2914]
```
@ApiUseTags('Tenants')
@Controller('tenants')
export class TenantsController {
    constructor(private readonly tenantsService: TenantsService) { }

    @Get('devices')
    @ApiOperation({ title: 'Retrieve details for the given device(s) with specific fields' })
    async findDevices(@Query(new QueryParamValidationPipe()) queryFields: QueryParamDto): Promise<string> {
        return this.tenantsService.findDevices(queryFields);
    }
}
```
In above code, how can I pass the query fields as constructor argument to TenantsService?

Note: Already asked above question on Discord, but no reply yet.

**Comment by kamilmysliwiec** [comment]
> Note: Already asked above question on Discord, but no reply yet.

We use [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. GitHub is for tracking bugs, feature requests, and potential improvements.

**Comment by amit12cool** [comment]
@kamilmysliwiec can u help on discord?
