### ISSUE TITLE
Use consistent coding styling between projects 

### ISSUE THREAD

**Issue by IGassmann** [nestjs/nest#2918]
I have noticed that the CLI starter, the documentation, the main project, and officials modules have all different set of TSLint rules applied to them. I propose that we normalize all those rules by enforcing one set of well documented and thought rules, such as the http://airbnb.io/javascript, across all the different official projects.

That would make the reading easier, add constancy to the different projects, and enforce many good practices that have long been discussed.

Prettier could still be used and would work with the linting rules by using the following ESLint extensions:

```
'airbnb-base',
'plugin:import/typescript',
'plugin:@typescript-eslint/recommended',
'prettier',
'prettier/@typescript-eslint',
```

If that makes, I would open the different PRs on the projects to apply the configuration change.

**Comment by kamilmysliwiec** [comment]
We want to migrate to ESlint either way, so bringing more consistency at the same time would be a nice idea. Would you like to create PR for this issue? One thing to note - if some change will require lots of code modifications, please, ask in the PR beforehand :)

**Comment by IGassmann** [comment]
Sure! I will open a PR first in https://github.com/nestjs/typescript-starter to start simple.

**Comment by RDeluxe** [comment]
I started migrating our NestJs repo to ESLint, it seems pretty painless atm (well, except the prettier + eslint 6 + vscode quircks)

**Comment by hboylan** [comment]
My current setup in Nest project:

**.eslintrc**
```json
{
  "extends": ["prettier"],
  "plugins": ["prettier"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "rules": {
    "prettier/prettier": "error"
  }
}
```

**.prettierrc**
```json
{
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all"
}
```

**package.json**
```json
{
  ...
  "@typescript-eslint/eslint-plugin": "^2.3.2",
    "@typescript-eslint/parser": "^2.3.2",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^6.3.0",
    "eslint-plugin-prettier": "^3.1.1",
    "prettier": "^1.18.2",
    "tslint": "^5.20.0",
  ...
}
```

For VS Code:

**.vscode/settings.json**
```json
{
  "eslint.autoFixOnSave": true,
  "eslint.validate": [
    "javascript",
    {
      "language": "typescript",
      "autoFix": true
    }
  ]
}
```

**Comment by kamilmysliwiec** [comment]
We're actively migrating to ESLint now.
