### ISSUE TITLE
Architecture Question: Middleware as decorator

### ISSUE THREAD

**Issue by unlight** [nestjs/nest#293]
I'm studying and researching this framework, and it's architecture generates many questions, for example
**#166 Why pipe is not a component**
I have another one:
Why middlewares are configured in modules?
Why not decorator?
```
@Controller('/cat')
@UseGuards(RolesGuard)
@UseInterceptors(TransformInterceptor)
@UseMiddlewares(Logger)
export class CatController {
...
    @Get('/browse')
    @Middleware(Logger)
    async cats() {
        return this.catService.findAll();
    }
}
```

**Comment by wbhob** [comment]
This does create some unnecessary redundancy, I agree.

**Comment by kamilmysliwiec** [comment]
Hi @unlight,
I have explained it here https://github.com/nestjs/nest/issues/235.
