### ISSUE TITLE
Weird scope behaviour leading to undefined injected services

### ISSUE THREAD

**Issue by DimosthenisK** [nestjs/nest#2938]
## Current behavior
Calling a service A's method "AA" from service B leads to service A's "this" having undefined properties. Calling service A's "AB" that subsequently calls AA from service B leads to correct execution.

I am at a loss of words over this problem because nothing makes sense
As context: Module B is included in Module A and added to imports via forwardRef both in module A and module B. Service B and service A are both injected into each other with forwardRef, too.

## Input Code

```ts
//Service A
constructor(
    @Inject(forwardRef(() => BService))
    private readonly BService: BService,
	@InjectRepository(A)
    private readonly ARepository: Repository<A>
) {}

async AA() {
   let expired = await this.ARepository.find({
       where: {
               deleted: false,
               persistent: false,
               startedOn: LessThan(
                  moment()
                  .subtract('1', 'minute')
                  .toDate()
               ),
       },
   });
   return expired;
}

async AB() {
    let result = await this.AA();
}
```

```ts
//Service B
constructor(
        @Inject(forwardRef(() => AService))
        private readonly AService: AService
    ) {
    }

async BA() {
   let ABResult = await this.AService.AB(); //Works fine
   let AAResult = await this.AService.AA(); //Throws cannot access "find" of undefined. On breakpoint debugging, no services are injected at all.
}
```

all functions from BService are called from BController.

## Expected behavior
I can call AA function from BService and not get an error

## Environment

<pre><code>
Nest version: Latest, just ran yarn upgrade.
 
For Tooling issues:
- Node version: 10.12.0
- Platform:  Windows 10 + docker
</code></pre>

You can follow the issue also on discord in the support channel

**Comment by kdubb** [comment]
@kamilmysliwiec Is there no way to warn about circular references in dependencies?

I'm using request scoped elements and I can see no circular references but when I use `ModuleRef.resolve` I get a service with no injected dependencies.
