### ISSUE TITLE
nestjs/swagger fails with GET and enum combination

### ISSUE THREAD

**Issue by TrejGun** [nestjs/nest#2939]
## Current behavior
Swagger UI fails to render component
<img width="1458" alt="Screen Shot 2019-09-12 at 6 30 50 PM" src="https://user-images.githubusercontent.com/185285/64798443-acee9c80-d58b-11e9-8d18-d02a3271a503.png">

## Input Code

```ts
export enum CatalogStatus {
  Active = "active",
  Inactive = "inactive",
}

export class CatalogSearchSchema extends CommonSearchSchema implements CatalogSearchFields {
  @ApiModelProperty()
  public code: string;

  @ApiModelProperty({
    enum: CatalogStatus
  })
  public status: CatalogStatus;
}

```

## Expected behavior
swagger ui should render component without error

## Possible Solution
pass `Object.values(CatalogStatus)` instead of `CatalogStatus` itself, to the swagger-ui
```js
  @ApiModelProperty({
    enum: [CatalogStatus.Active, CatalogStatus.Inactive],
  })
  public status: CatalogStatus;
```
this code works fine

## Environment

<pre><code>
"@nestjs/core": "6.6.7",
"@nestjs/swagger": "3.1.0",
"swagger-ui-express": "4.1.0",

For Tooling issues:
- Node version:  v12.9.1
- Platform:  Mac

Others:

npm
</code></pre>

<img width="684" alt="Screen Shot 2019-09-12 at 6 36 40 PM" src="https://user-images.githubusercontent.com/185285/64799031-a876b380-d58c-11e9-9dc6-8ad77282ff6c.png">
<img width="437" alt="Screen Shot 2019-09-12 at 6 37 04 PM" src="https://user-images.githubusercontent.com/185285/64799033-a876b380-d58c-11e9-810c-8f9aa2b632be.png">

**Comment by kamilmysliwiec** [comment]
`enum` doesn't exist in vanilla JavaScript. This construction: 

```
  @ApiModelProperty({
    enum: [CatalogStatus.Active, CatalogStatus.Inactive],
  })
  public status: CatalogStatus;
```

is valid.

**Comment by TrejGun** [comment]
@kamilmysliwiec 
There is enum to array converter 
https://github.com/nestjs/swagger/blob/master/lib/explorers/api-parameters.explorer.ts#L173
but it is not used in this branch of code
if you can help me to find a place where it should be called for get params i can make a PR

**Comment by TrejGun** [comment]
@kamilmysliwiec any comment?
