### ISSUE TITLE
why it has express and fastify dependency

### ISSUE THREAD

**Issue by lithic** [nestjs/nest#2952]

**Comment by izio38** [comment]
These dependencies are needed in order to provide platform on which your HTTP instances could run on. You obviously don't need to bring them all into your project if you care about volume spaces

**Comment by BrunnerLivio** [comment]
I guess you've looked into the [root package.json](https://github.com/nestjs/nest/blob/master/package.json) of NestJS? Note those dependencies are only used for internal development. For your production app, you'll use the [@nestjs/core package.json](https://github.com/nestjs/nest/blob/master/packages/core/package.json) (which does not include express nor fastify) and choose the platform you want to run on e.g. [@nestjs/paltform-express](https://github.com/nestjs/nest/blob/master/packages/platform-express/package.json) which includes the Express package.
