### ISSUE TITLE
HMR does not work on macos

### ISSUE THREAD

**Issue by hamdiwanis** [nestjs/nest#2956]
## Bug Report

i set up sample project with HMR as in documentations nothing more and it work as expected on mu windows machine but not on mu macos one. i was wondering what would be the reason. i appreciate your help

## Current behavior

npm run webpack runs fine
npm run start runs fine
change a file
webpack reload as expected
server instance does not update 

## Expected behavior

server instance does update to refect new changes

## Environment

<pre><code>
- Nest version: 6.6.4
- Node version: 11.3.0
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
I'm using Mac as well and it works fluently. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by hamdiwanis** [comment]
thanks
