### ISSUE TITLE
Logger service: Allow context based filtering 

### ISSUE THREAD

**Issue by ulrichb** [nestjs/nest#2959]
## Is your feature request related to a problem? Please describe.
Some modules (e.g. `RouterExplorer`) are too verbose. I want to restrict their logging to e.g. ">= warn".

## Describe the solution you'd like
A configuration option which allows to specify minimum level (or a list of levels) overrides _per logging context_. 

With `NestFactory.create(..., {  logger: ['error', 'warn'], });` it's already possible for all contexts, now I would like to have a context-specific override.

Just like .NET Core's [Serilog](https://github.com/serilog/serilog-settings-configuration#level-overrides) has.

Example:
```ts
NestFactory.create(..., {  

  logger: ['debug', 'info', 'warn', 'error'],

  loggerContextOverride: {
    "RouterExplorer": ['warn', 'error'],
    "SomeOtherAppContext": ['error'],
  },

});
```

**Comment by kamilmysliwiec** [comment]
We don't plan to add more features to the existing logger, but you should be able to easily add this functionality on your own (simply extend the built-in logger and override corresponding methods).

**Comment by ulrichb** [comment]
Okay. Could you then add a simple `this.shouldLog()`-check call to (the private) [`Logger.callFunction()`](https://github.com/nestjs/nest/blob/35c79bd4915786cc9dc94ab4170c031c1a9819d5/packages/common/services/logger.service.ts#L95).

... + add `protected shouldLog(name, message, context) => boolean`. (Here, the current `this.isLogLevelEnabled()` can be moved in).

This would make such modifications much easier by just extending the default `Logger`.

I could also provide a PR for this.
