### ISSUE TITLE
Unexpected error message for ParseUUIDPipe.

### ISSUE THREAD

**Issue by rev-hikari** [nestjs/nest#2960]
## Current behavior

```
"message": "Validation failed (uuid vundefined is expected)"
```

## Input Code

```ts
@Param("id", new ParseUUIDPipe()) // without options.version
```

## Expected behavior

```
"message": "Validation failed (uuid is expected)"
```

## Environment

```
Nest version: 6.6.7
```

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by cjancsar** [comment]
@rev-hikari did you resolve this?

**Comment by cjancsar** [comment]
Seems if you don't explicitly specify a version, then you get this error. See: https://stackoverflow.com/questions/59403893/nestjs-parseuuidpipe-validation-failed-uuid-vundefined-is-expected
