### ISSUE TITLE
p2p websocket

### ISSUE THREAD

**Issue by FilipeMazzon** [nestjs/nest#2963]
## Is your feature request related to a problem? Please describe.
I need to create a blockchain and want to create with nestjs, but I really like to use websocketGateway but with the documentation I don`t have a clue how I can connect with anothers websocket servers.

## Describe the solution you'd like
Improve websocket documentation on nestjs with the example connecting backend to backend

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
