### ISSUE TITLE
Emitting an error event throws an exception

### ISSUE THREAD

**Issue by THPubs** [nestjs/nest#2976]
## Current behaviour
If you emit an `error` event in a web socket gateway:
```
socket.emit('error', 'un-authorized');
```

it throws an unhandled exception like this:
```
UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('un-authorized')
```

The same thing happens even if we throw a `WsException`:
```
throw new WsException('un-authorized');
```

The error doesn't get forwarded to the client. The client is set to listen to this error event, get the message and show it to the user.

## Expected behavior
Forwarding the `error` event to the client which triggers the on error event.

## Environment
Nest version: 6.7.1

 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Mac

**Comment by izio38** [comment]
Which websocket platform are you using?

**Comment by THPubs** [comment]
@izio38 I'm using Web Sockets.

**Comment by izio38** [comment]
Could you share a minimal reproduction of the issue please?
I don't really get what's happening since if you're using the WS plateform, if should be logged and that's it: https://github.com/nestjs/nest/blob/fb72dcc0fe358e3bde7090997474b72f91f8dc13/packages/platform-ws/adapters/ws-adapter.ts#L96

**Comment by THPubs** [comment]
@izio38 Sure you can have a look at this repo: https://github.com/THPubs/nest-ws

**Comment by izio38** [comment]
I have no proof on this, but I looked at the code and it seems the exeption filter catch the error and re-throw it to a `exception` event.
I'll give it a try later :)

**Comment by THPubs** [comment]
@izio38 Thanks I tried to listen to the `exception` event in both client and server. Still nothing. I just need to get the error message to the front end (client) 🙂

**Comment by izio38** [comment]
```js
describe('AppController (e2e)', () => {
  let ws;

  // beforeEach(async () => {
  //   const moduleFixture: TestingModule = await Test.createTestingModule({
  //     imports: [AppModule],
  //   }).compile();

  //   app = moduleFixture.createNestApplication();
  //   await app.init();
  // });

  // it('/ (GET)', () => {
  //   return request(app.getHttpServer())
  //     .get('/')
  //     .expect(200)
  //     .expect('Hello World!');
  // });

  it('should throw an error', async () => {
    ws = io.connect('http://localhost:8080');
    ws.on('connect_error', args => {
      console.log('connect error');
      console.error(args);
    });
    ws.on('error', args => {
      console.log('error');
      console.error(args);
    });
    await new Promise(resolve =>
      ws.on('connect', () => {
        console.log('connect');
        resolve();
      }),
    );
  });
})
```
Error can be found on `connect_error` as specify Socket.Io.

**Comment by THPubs** [comment]
The thing is, it's not being forwarded to the front end (The client-side). But just noticed that if I exit the app, then all the errors will be forwarded to the front end.

**Comment by izio38** [comment]
Yes they are, try the snippet I shared
if you throw an error during the connection, it's bounced to connect_error

Le mer. 18 sept. 2019 à 02:29, Pubudu Kodikara <notifications@github.com> a
écrit :

**Comment by THPubs** [comment]
Yes but even though the tests catch the error. The real client can't catch the error.

**Comment by kamilmysliwiec** [comment]
@THPubs take a look here https://github.com/socketio/socket.io/issues/2285#issuecomment-150708182

`error` is a reserved keyword, you should use a different name.

**Comment by THPubs** [comment]
Ah, thanks. The thing is I'm porting an existing API to nest. In the existing system, we emit an `error` event and the front end catches it. That means we have to change the front end also right?

However, I did try the WS adapter (We won't be able to go for WS now since the front end code already use Sockets.) and in there, it did send the error back to the front and we were able to catch it by listening to the `connect_error` event. But in Socket.io even the `connect_error` event returns nothing.

**Comment by kamilmysliwiec** [comment]
> In the existing system, we emit an error event and the front end catches it. That means we have to change the front end also right?

This means that in the existing system you're doing something different than in this one that you're building right now. Perhaps, there is some workaround that allows emitting `error` event that I'm not aware of. Regardless, you shouldn't do that either way.

> However, I did try the WS adapter (We won't be able to go for WS now since the front end code already use Sockets.) and in there, it did send the error back to the front and we were able to catch it by listening to the connect_error event. But in Socket.io even the connect_error event returns nothing.

WS adapter varies with many things with socket.io, so you would definitely have to change a lot of things in your FE app.

Anyway, this issue is not related to NestJS specicially. You can try using our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions

**Comment by THPubs** [comment]
Ah ok thanks! I'll have a look at it 🙂
