### ISSUE TITLE
Where is @nestjs/websockets repo? I need to create PR to fix bug

### ISSUE THREAD

**Issue by oleksii-shnyra** [nestjs/nest#2977]
Hello, I have an issue with @nestjs/websockets.

I already solved it locally through creating custom io adapter, but I want tot make a PR so that package itself works properly.

But cannot find @nestjs/websockets - where to create PR actually?
Link from npm registry redirects here.

**Comment by marcus-sa** [comment]
Most of the packages provided by `@nestjs/*` remains in this mono repository.
The specific package you're looking for is located in https://github.com/nestjs/nest/tree/master/packages/websockets
