### ISSUE TITLE
[Kafka Microservice] ClientKafka Reply Topic Partitions

### ISSUE THREAD

**Issue by mkaufmaner** [nestjs/nest#2984]
## Current behavior
When new `ClientKafka` instances are launched they join the consumer group and subscribe to their respective topics.  This process triggers a rebalance of topic partitions assigned to consumers of the consumer group.

Normally, topic partitions are assigned using round robin partitioner that assigns topic partitions to a collection of consumers sorted by consumer names which are randomly set on application launch.  However, when a new consumer joins the consumer group, the new consumer be positioned anywhere within the collection of consumers.  This creates a condition where preexisting consumers would be assigned different partitions when the preexisting consumer is positioned after the new consumer.  Subsequently, the consumers that are assigned different partitions will lose response messages of requests sent before the rebalance.

To prevent the `ClientKafka` consumers from losing response messages a custom partitioner is utilized.  This custom partitioner assigns partitions to a collection of consumers sorted by high-resolution timestamps (`process.hrtime()`) that are set on application launch.

Unfortunately, this solution only addresses the problem of `ClientKafka` consumers joining the consumer group.  However, it doesn't address the problem of `ClientKafka` consumers leaving the consumer group.

## Expected behavior

Existing topic partition assignments where the consumer is assigned only one partition of the topic should not be reassigned to other partitions.  Regardless of whether the `ClientKafka` consumer is joining or leaving the group.

## Possible Solution

Implement a partitioner that takes into account existing topic partition assignments.  See https://cwiki.apache.org/confluence/display/KAFKA/KIP-54+-+Sticky+Partition+Assignment+Strategy

## Environment

<pre><code>
Nest version: >=6.7.0

 
For Tooling issues:
- Node version: N/A
- Platform: N/A

Others:

</code></pre>

**Comment by evyros** [comment]
I came here form google, looks like an old issue but super relevant.
Following this, hopefully to see #5654 get merged soon.

**Comment by mkaufmaner** [comment]
> I came here form google, looks like an old issue but super relevant.
> Following this, hopefully to see #5654 get merged soon.

Yep, still working on it.  Just need to finish the tests really and work out another problem I have been encountering with sending the producer messages.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/5654
