### ISSUE TITLE
Validation pipe and TypeScript generics... doesn't work, it's ok?

### ISSUE THREAD

**Issue by gremo** [nestjs/nest#2989]
## Bug Report
Premise: I'm learning TypeScript, so maybe this is just the way things work.

Anyways, I'm trying to do a **generic controller**. Why? To make a reusable module. Here is how it looks like:

```typescript
import { Body, Controller, Get, Post, UsePipes, ValidationPipe } from '@nestjs/common';
import { BankModel } from './bank.model';

@Controller('banks')
export class BankController<E extends BankModel = BankModel> {
  @Post()
  @UsePipes(ValidationPipe)
  public getOne(@Body() bank: E): void { }
}
```

`BankModel` is an abstract class with the proper decorators for some properties.

## Expected behavior
When I `POST /banks`, the validation works.

## Current behavior
Validation doesn't work. I inserted some debug code in `validation.pipe.js` [here](https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L65) and the result is:

`{ metatype: [Function: Object], type: 'body', data: undefined }`

If I change the method to:

```typescript
public getOne(@Body() bank: BankModel): void { }
```

Here is the output:

`{ metatype: [Function: Bank], type: 'body', data: undefined }`

## Environment
<pre><code>
Nest version: 6.6.3

 
For Tooling issues:
- Node version: v10.16.0
- Platform: Windows 10 x64
</code></pre>

**Comment by kamilmysliwiec** [comment]
See this https://github.com/nestjs/nest/issues/965#issuecomment-415149081
