### ISSUE TITLE
Body parser ignores Dto structure.

### ISSUE THREAD

**Issue by wintertime-inc** [nestjs/nest#2995]
## Current behavior
While using POST over controller and passing Body as an DTO object it seems like we can still manipulate whole object, is it expected behaviour? How to change it so only attributes within DTO will be acceptable by the server?

## Input Code

**dto**
```ts
export class CreateInstanceDto {
  name: string;
}
```
**instance.service function**
```ts
  async create(instanceBody: CreateInstanceDto, user: User): Promise<Instance> {
    try {
      const instance = new this.instanceModel(instanceBody);
      instance.createdBy = user.mail;
      await instance.save();
      return instance;
    } catch (e) {
      throw new BadRequestException(e.message.toString());
    }
  }
```
**instance.controller**
```ts
  @UseGuards(AuthGuard('jwt'))
  @Post()
  create(@Body() instanceDto: CreateInstanceDto, @Request() req): Promise<Instance> {
    return this.instanceService.create(instanceDto, req.user);
  }
```
**instance.interface**
```ts
export interface Instance {
  id?: string;
  name: string;
  active: boolean;
  status: any;
  createdAt: Date;
  createdBy: string;
  configuration: any;
}
```
**instance.schema**
```ts
import * as mongoose from 'mongoose';

export const InstanceSchema = new mongoose.Schema({
  name: {required: true, type: String, index: {unique: true}},
  active: {type: Boolean, default: false},
  status: {type: Map, default: {
      database : false,
      environment : false,
      configuration : false,
      language : false,
    }},
  createdAt: {type: Date, default: Date.now},
  createdBy: {type: String},
  configuration: {type: Map, default: {}},
});
```
## Expected behavior
Once I post anything else than `name` it should ignore all other inputs.
Right now if I pass `name`:"xxx" and `active`:true, object xxx is created with active status as true instead of default `false` provided by the schema.

## Environment

<pre><code>
Nest version: 6.6.4
 
For Tooling issues:
- Node version:  v10.15.3
- Platform: Windows

</code></pre>

**Comment by kamilmysliwiec** [comment]
See:
1. https://docs.nestjs.com/techniques/validation#stripping-properties
2. https://docs.nestjs.com/techniques/validation#auto-payload-transforming

**Comment by wintertime-inc** [comment]
Just one comment on that @kamilmysliwiec, is it better practice to leave body parser > DTO open for such a behavior and only update/play with what we expect to have or actually looking at the resolution which you just posted? I would love to know which option is preferable/more efficient.

**Comment by kamilmysliwiec** [comment]
The default behavior will be more performant, while this one that I've posted - more secure out-of-the-box.

**Comment by jselesan** [comment]
Hi @kamilmysliwiec, I have the following code:

`import { Get, Controller, Query, Post, Body, UsePipes, ValidationPipe } from '@nestjs/common';

interface TestDto {
  field1: number;
  field2: boolean;
}

@Controller()
export class AppController {
  constructor() {}

  @Get()
  @UsePipes(new ValidationPipe({ whitelist: true, transform: true}))
  root(@Query() dto: TestDto): TestDto {
    return dto;
  }

}
` 

If I navigate to http://localhost:3000/?field1=15&field2=true&field3=hello, I get

`{
"field1": "15",
"field2": "true",
"field3": "hello"
}
`

But I expect

`{
"field1": 15,
"field2": true
}`

What am I doing wrong?
