### ISSUE TITLE
Type 'NestFastifyApplication' does not satisfy the constraint 'INestApplication'.   Type 'NestFastifyApplication' is missing the following properties from type 'INestApplication': use, enableCors, listen, listenAsync, and 19 more.ts(2344) Peek Problem No quick fixes available

### ISSUE THREAD

**Issue by nitin28061996** [nestjs/nest#3002]
## Input Code

import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';
import { INestApplication } from '@nestjs/common';
async function bootstrap() {
  const app:INestApplication = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  app.enableCors();
  await app.listen(3000);
}
bootstrap();
```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by zieglar** [comment]
I use fastify, but I skip `INestApplication`

**Comment by kamilmysliwiec** [comment]
```
await NestFactory.create<NestFastifyApplication>(...)
```
