### ISSUE TITLE
PostConstruct and PreDestroy Annotations

### ISSUE THREAD

**Issue by BenRacicot** [nestjs/nest#3005]
## Feature Request
I'm new to Nest but thought I'd ask about the Nest way to PostConstruct and PreDestroy. 
Is [onModuleInit()](https://docs.nestjs.com/fundamentals/lifecycle-events) meant to run after an object is instantiated?

I see that a Nest competitor, Inversify, [has implemented @postConstruct](https://github.com/inversify/InversifyJS/issues/587) for this specific case.

If onModuleInit exists for this reason please close. Otherwise, I'd like to propose @PostConstruct / @PreDestroy annotations!

## What is the motivation / use case for changing the behavior?
I could not explain better than this article on [https://www.baeldung.com/spring-postconstruct-predestroy](PostConstruct https://www.baeldung.com/spring-postconstruct-predestroy)

**Comment by marcus-sa** [comment]
`onModuleDestroy` is the equivalent of `PreDestroy` in Nest
Same goes for `onModuleInit` and `PostConstruct`

**Comment by kamilmysliwiec** [comment]
You can use `onModuleInit()` and `onModuleDestroy()` for that.
