### ISSUE TITLE
Route parameter token limitations

### ISSUE THREAD

**Issue by ed-fruty** [nestjs/nest#3007]
For example we have routes like

 - `/cats/:id` (`cats/32`)
 - `/categories/:category` (`/categories/my-favorite-category`)

And we want to more control rules for tokens. 
For example it would be "*cats id's must be only integers*" or "*categories can be only alphabetic*"

Now we can't use all power of regular expressions in routes. 

In Laravel application we made like [this](https://laravel.com/docs/5.8/routing#parameters-regular-expression-constraints)

```php
Route::get('user/{id}', function ($id) {
    //
})->where('id', '[0-9]+');
```

Is it any possibility to do the same with Nest ?

Maybe it can be like this:

```ts
@Controller('/cats')
export class CatsController {

  @Get(':id')
  @RouteParamConstraint('id', '/\d{2,5}/')
  async show(@Param('id') id) {
     //
  }
}
```

Yep, we can detect correct entity id or not inside the controller action, but I think it would be better when wrong id don't handle controller at all (like we have validation of request dto now)

-----
P.S.
Out of scope of this issue, but maybe it will be pretty cool to make possibility to inject something instead of param, like:

```ts
@Controller('/cats')
export class CatsController {

  @Get(':cat')
  @RouteParamConstraint('cat', '/[a-zA-Z0-9]{3, }/')
  @BindRouteParam('cat', CatsRouteResolver) //or @BindRouteParamToEntity('id', Cat)
  async show(cat: Cat) {
     //
  }
}
```

**Comment by kamilmysliwiec** [comment]
> For example it would be "cats id's must be only integers" or "categories can be only alphabetic"

You can use pipes for that easily. https://docs.nestjs.com/pipes
Actually, even the built-in `ValidationPipe` should be enough for your requirements :)

> Out of scope of this issue, but maybe it will be pretty cool to make possibility to inject something instead of param, like:

Use custom decorators then: https://docs.nestjs.com/custom-decorators
In combination with pipes, they should provide what you need

**Comment by ed-fruty** [comment]
Yes, I know that it's possible to do at all, but it would be cool have them out of the box )

**Comment by kamilmysliwiec** [comment]
> Yes, I know that it's possible to do at all, but it would be cool have them out of the box )

It's possible out-of-the-box with the `ValidationPipe`
