### ISSUE TITLE
Not able to read params when content type is "application/json-patch+json" when doing JSON Patch requests

### ISSUE THREAD

**Issue by alfredoperez** [nestjs/nest#3008]
## Current behavior
NestJS is not able to read a parameter when the request header for content-type is 'application/json-patch+json'.

This content type is needed for the JsonPatch https://tools.ietf.org/html/rfc6902 

> 3.  Document Structure
> 
>    A JSON Patch document is a JSON [RFC4627] document that represents an
>    array of objects.  Each object represents a single operation to be
>    applied to the target JSON document.
> 
>    The following is an example JSON Patch document, transferred in an
>    HTTP PATCH request:
> 
>    PATCH /my/data HTTP/1.1
>    Host: example.org
>    Content-Length: 326
>    Content-Type: application/json-patch+json
>    If-Match: "abc123"
> 
>    [
>      { "op": "test", "path": "/a/b/c", "value": "foo" },
>      { "op": "remove", "path": "/a/b/c" },
>      { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
>      { "op": "replace", "path": "/a/b/c", "value": 42 },
>      { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
>      { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
>    ]
> 

## Input Code
Using a Patch request, change the content-type to "application/json-patch+json" and the body won't be read by NestJS. Changing the content-type to json fixes this problem, but it goes against the standard

## Expected behavior
Consumers should be able to do PATCH requests with the content-type of 'Content-Type: application/json-patch+json'

## Possible Solution
Was not able to find why the body/param is not read

## Environment

Nest version: 6.7.1

**Comment by kamilmysliwiec** [comment]
See this issue https://github.com/expressjs/body-parser/issues/96

**Comment by alfredoperez** [comment]
Thanks @kamilmysliwiec 
Just for reference, I used the following to be able to parse the params:

```ts
import { json } from 'body-parser';
...

app.use(json({ type: 'application/json-patch+json' }));
```
