### ISSUE TITLE
Get reliable server url with `NestApplication.url` 

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#3010]
## Is your feature request related to a problem? Please describe.
**As a user** I want to reliably get the server URL.
 
## Describe the solution you'd like
After `app.listen` the application should know all the needed information.
I would expect the following behavior.

```ts
const app = await NestFactory.create(AppModule);
await app.listen(3000);
console.log(app.url) // returns http://[::1]:3000/
```

## What is the motivation / use case for changing the behavior?
To further improve the DX of NestJS I would like to see the server URL logged in the console once I boot up the application. I would suggest the log message should be part of the boilerplate when running `nest new [NAME]`.

```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
  console.log(`Server is listening on ${app.url}`);
}
bootstrap();
```

## Open topics
- How should we determine when the server is running with the `http://` or `https://` protocol?
- [Follow-up] Where should the log message have its place? The options I come up with are:
  - In the `nest new`-schematics (as described above)
  - Underlying in `NestApplication#listen`
  - Let `nest start` handle the printing of the message (maybe the way to go, in case `nest start --watch` should change the port)

**Comment by kamilmysliwiec** [comment]
Sounds useful :) PRs are welcome!

**Comment by jmcdo29** [comment]
I think this is something I can take on. Do you want the log of `listening on` to be a part of the `listen` function, or do you want it to still be up to the dev to add in the log?

**Comment by kamilmysliwiec** [comment]
Getter/method will be enough (without the log)

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec @jmcdo29 
One thing which is unclear for me;
> How should we determine when the server is running with the http:// or https:// protocol?
Should @jmcdo29 just check whether
