### ISSUE TITLE
Missing package 

### ISSUE THREAD

**Issue by rubiin** [nestjs/nest#3013]
## Bug Report
One of the samples in git is missing class-validator package in serializer sample 21
## Current behavior

After npm install and running tha app via, npm run start, `The "class-validator" package is missing. Please, make sure to install this library ($ npm install class-validator) to take advantage of ValidationPipe` is shown on the cli

## Expected behavior
The app should be running after the npm install and the npm start command

## Possible Solution
Add class-validator package on serializer example in [link](https://github.com/nestjs/nest/blob/master/sample/21-serializer/package.json)

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: 10  
- Platform: Linux 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
I think it's tracked here https://github.com/nestjs/nest/pull/2970
