### ISSUE TITLE
Importing DTO from another module

### ISSUE THREAD

**Issue by mranon0007** [nestjs/nest#3028]
I have 2 Modules, a ```person``` module and a `cat` module. If I want to use a cat service, I simply import the `cat` module into `person` and inject the service. What should I do about plain classes, like DTOs? A function in my Cat controller ```getCatOwner()``` returns a person object, so I need to import the DTO class from `cat` module. Is this the standard way to do this?

Thank you

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
