### ISSUE TITLE
Nest can't resolve dependencies of the CallCatsService (?). Please make sure that the argument at index [0] is available in the CallCatsModule context.

### ISSUE THREAD

**Issue by cam-nisimura** [nestjs/nest#3036]
## Current behavior
I add the service to call the service which uses httpModule.

npm start shows errors, following;

> Nest can't resolve dependencies of the CallCatsService (?). Please make sure that the argument at index [0] is available in the CallCatsModule context. +187ms

## Input Code

1. According https://docs.nestjs.com/techniques/http-module, create app and cat module without any configuration using register().

**cats.module.ts**
```
@Module({
  imports: [HttpModule],
  providers: [CatsService],
})
export class CatsModule {}
```
2. create call-cats module and service. 

**call-cats.module.ts**
```
import { Module } from '@nestjs/common';
import { CallCatsService } from './call-cats.service';
import { CatsModule } from '../cats/cats.module';

@Module({
  imports: [CatsModule],
  providers: [CallCatsService]
})
export class CallCatsModule {}
[vagrant@gamebox call-cats]$ more call-cats.module.ts 
import { Module } from '@nestjs/common';
import { CallCatsService } from './call-cats.service';
import { CatsModule } from '../cats/cats.module';

@Module({
  imports: [CatsModule],
  providers: [CallCatsService]
})
export class CallCatsModule {}

```

**call-cats.service.ts**
```
import { Injectable } from '@nestjs/common';
import { CatsService } from '../cats/cats.service';

@Injectable()
export class CallCatsService {
   constructor(private readonly catService: CatsService) { }
 }
```
**app.module.ts**

```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { CatsModule } from './cats/cats.module';
import { CallCatsModule } from './call-cats/call-cats.module';

@Module({
  imports: [CatsModule, CallCatsModule],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

## Expected behavior
npm start  runs without error.

## Environment

<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: v10.16.0
- Platform:  Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
