### ISSUE TITLE
Redis Streams support

### ISSUE THREAD

**Issue by patrickandroid** [nestjs/nest#3061]
## Feature Request
Is there any plans to support Redis Streams? 
I think it would be a great addition. I'm new to the Nest framework.
Would it require much work to implement? I'd like to help.

https://redis.io/topics/streams-intro

## Describe the solution you'd like

"Unlike Pub/Sub messages which are fire and forget, Redis streams preserve messages in perpetuity. Redis streams implement consumer groups, a feature that allows a group of clients to cooperate when consuming elements from a stream "
https://aws.amazon.com/redis/Redis_Streams/

## What is the motivation / use case for changing the behavior?
I'd like to use Redis to implement a queue system with consumer groups, instead of using RabbitMQ.

**Comment by patrickandroid** [comment]
Sorry for reopening the issue. Would creating a "Custom Transport", similar to the [RabbitMq](https://docs.nestjs.com/microservices/custom-transport) implementaion be the best way to implement Redis Streams?

**Comment by kamilmysliwiec** [comment]
@patrickandroid "Custom Transport" is the only way for now.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/3960
