### ISSUE TITLE
Cannot access injected services from @FieldResolver method

### ISSUE THREAD

**Issue by justinmchase** [nestjs/nest#3064]
## Bug Report
Multiple instances of a resolver are being created and I cannot access the constructor injected services from within `@FieldResolver` methods.

## Current behavior
If I create a resolver class with services injected in the constructor I can see the services injected correctly but later when an `@FieldResolver` method is invoked the services are undefined and putting logging in the constructor I can see it is instantiated multiple times and the second time lacks the services it needs.

## Input Code
```ts
let id = 0

@Resolver(of => Example)
export class ExampleResolver {
  private id: number

  constructor(
    private test: TestService
  ) {
    this.id = id++
    console.log({ id: this.id, test }) // { id: 0, test: {...} }, the first time
  }

  @FieldResolver(type => [string], { name: 'tests' })
  public async tests() {
    console.log({ id: this.id, test: this.test }) // { id: 1, test: undefined}
    return [] 
  }
}
```

## Expected behavior
* I expect the resolver to be instantiated exactly once
* I expect the services to always be injected into the constructor

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: v12.8.0
- Platform: ubuntu

**Comment by kamilmysliwiec** [comment]
You should use `@ResolveProperty` instead of `@FieldResolver`. We're working on the improvements to the documentation

**Comment by justinmchase** [comment]
Thanks
