### ISSUE TITLE
MiddlewareConsumer exclude is fail

### ISSUE THREAD

**Issue by Hareis** [nestjs/nest#3066]
I implemented it following the example of the official website demo. logger.middleware
https://docs.nestjs.cn/6/middlewares

![image](https://user-images.githubusercontent.com/11290701/65857838-3c22ef00-e397-11e9-93e3-7b34f32102f9.png)

![image](https://user-images.githubusercontent.com/11290701/65858159-e3a02180-e397-11e9-98e4-810e2a5fcfe9.png)

It has been confirmed that this LoggerMiddleware has been used only in AppModule. 
However, when accessing [status] routes excluded from exclude,
```
http://localhost:3000/account/status
```
Will still go to the LoggerMiddleware and output 'log.' on the console. 
Please tell me if path is misconfigured in my exclude

**Comment by kamilmysliwiec** [comment]
国内开发者交流群
QQ群：277386223 QQ群：336289049 QQ群：489719517

**Comment by Hareis** [comment]
> 国内开发者交流群
> QQ群：277386223 QQ群：336289049 QQ群：489719517

This perfunctory treatment of Chinese developers is really not very good.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue :) I'll take a look asap

**Comment by Hareis** [comment]
> Please, provide a minimal repository which reproduces your issue :) I'll take a look asap

I put him in my warehouse, [https://github.com/Hareis/project-name-nest](url) 
Please check that LoggerMiddleware is being used correctly for me

**Comment by kamilmysliwiec** [comment]
`exclude` feature works slightly different right now. If you look into the original version of the docs (here https://docs.nestjs.com/middleware#middleware-consumer), you'll see this:

> Please note that the exclude() method does not work with functional middleware (middleware defined in a function rather than in a class; see below for more details). In addition, this method doesn't exclude paths from more generic routes (e.g., wildcards). If you need that level of control, you should put your paths-restriction logic directly into the middleware and, for example, access the request's URL to conditionally apply the middleware logic.

The most important part here is this:

> In addition, this method doesn't exclude paths from more generic routes (e.g., wildcards). If you need that level of control, you should put your paths-restriction logic directly into the middleware and, for example, access the request's URL to conditionally apply the middleware logic.

The behavior will be changed in the next major release 7.0.0 due to this PR https://github.com/nestjs/nest/pull/3042

**Comment by Hareis** [comment]
Thank you. Got it.

**Comment by mosh-dev** [comment]
If @Controller decorator has prefix it needs to be included in path. line auth/change-password
