### ISSUE TITLE
[Question] ArgumentsHost.getType implementation

### ISSUE THREAD

**Issue by galkin** [nestjs/nest#3081]
Right now, interface implementation is based on `setType` method, as result we have overcomplication. [Example](https://github.com/nestjs/nest/blob/master/packages/core/guards/guards-consumer.ts#L19
)

@kamilmysliwiec, do we have any tech problems for implementation this feature based on Reflection? Draft:

```
import { PATH_METADATA } from '@nestjs/common/constants';
import { RESOLVER_TYPE_METADATA } from '@nestjs/graphql/dist/graphql.constants';

...
  getType<TContext extends string = ContextType>(): TContext {
    if (Reflect.getMetadata(PATH_METADATA, this.handler)) return 'http';
    if (Reflect.getMetadata(RESOLVER_TYPE_METADATA, this.handler)) return 'graphql';
    ...
    return 'unknown';
  }
```

**Comment by kamilmysliwiec** [comment]
> do we have any tech problems for implementation this feature based on Reflection? 

Yes, it would be slower.

> Right now, interface implementation is based on setType method, as result we have overcomplication.

It's not an overcomplication. `type` depends on the context creator, not the handler itself.

**Comment by galkin** [comment]
Thank you for explanation.
