### ISSUE TITLE
overrideGuard doesn't work in e2e test that include 2 controllers using the same guard

### ISSUE THREAD

**Issue by jogelin** [nestjs/nest#3101]
## Current behavior
I would like to make an e2e test that include 2 controllers/resolvers that are using the same Guard but the `overrideGuard` of the `TestingModule` isn't take in account.

It works if I include only one controller/resolver into the test.

## Input Code
https://github.com/jogelin/issue-override-guard

## Expected behavior
If I specify `overrideGuard` into the `TestingModule` configuration, I should never have the real Guard called

## Environment

<pre><code>
    "@nestjs/common": "^6.7.2",
    "@nestjs/core": "^6.7.2",
    "@nestjs/testing": "^6.7.1",
</code></pre>

Could help for #2515 and #2070

**Comment by kamilmysliwiec** [comment]
Fixed in 6.8.2. Thanks!
