### ISSUE TITLE
Cannot find module '@nestjs/common/interfaces/external/kafka-options.interface'.

### ISSUE THREAD

**Issue by bitbreakr** [nestjs/nest#3103]
## Current behavior

Cannot start the backend due to an error on compilation since installation of 
package **"@nestjs/microservices"**

## Input Code

account_1       | node_modules/@nestjs/microservices/interfaces/microservice- configuration.interface.d.ts(2,79): error TS2307: Cannot find module '@nestjs/common/interfaces/external/kafka-options.interface'.
account_1       | 10:52:11 AM - Found 1 error. Watching for file changes.

## Environment
Docker: v19.03.2
MacOS
Nodejs: v12.2.0
<pre><code>

NESTJS
platform-express version : 6.0.0
microservices version    : 6.8.2
passport version         : 6.1.0
swagger version          : 3.1.0
common version           : 6.0.0
core version             : 6.0.0
jwt version              : 6.1.1

**Comment by kamilmysliwiec** [comment]
Update @nestjs/common and @nestjs/core to the latest versions

**Comment by bitbreakr** [comment]
@kamilmysliwiec Damn, you're so fast answering. Thanks for the answer, have a good day.

**Comment by jaligamap** [comment]
@kamilmysliwiec - do you have any example code on how to use the kafka-options ?
