### ISSUE TITLE
Custom decorator that applies multiple existing decorators

### ISSUE THREAD

**Issue by karlos1337** [nestjs/nest#3104]
## Feature Request
I miss from other TS frameworks a way to create a decorator that applies multiple decorators, for example:
```ts
export function Auth(roles: string | string[]): NestDecorator {
  return applyDecorators(
    SetMetadata('roles', roles),
    UseGuards(AuthGuard)
  );
}
```
to be used as:
```ts
@Controller()
export class MyController {
  @Get('')
  @Auth('admin')
  getAll() {...}
}
```

**Comment by marcus-sa** [comment]
That's possible in every TS project that doesn't use AOT compilers (like Angular)

**Comment by joeyslack** [comment]
@karlos1337 as @marcus-sa said, this should already be possible.

Correct me if I misunderstand, but it seems you are looking for `@SetMetadata('roles', ['admin'])` [https://docs.nestjs.com/guards#reflection](https://docs.nestjs.com/guards#reflection)

**Comment by karlos1337** [comment]
Maybe I missexplain, my intention is kind of sugar-code, for DRY intention, resume both decorators features that are explained in [nest docs guards workaround](https://docs.nestjs.com/guards) in one.

I could use:
```ts
@Controller()
export class MyController {
  @Get('...')
  @SetMetadata('roles', ['admin']);
  @UseGuards(AuthGuard)
  getAll() {...}

  @Get('...')
  @SetMetadata('roles', ['user']);
  @UseGuards(AuthGuard)
  getOne() {...}
}
```
but, could be great if can build custom decorators that combine multiple decorators in one and resume that in:
```ts
@Controller()
export class MyController {
  @Get('...')
  @Auth(['admin'])
  getAll() {...}

  @Get('...')
  @Auth(['user'])
  getOne() {...}
}
```
Like, as I said, could be done in [other ts backend frameworks](https://tsed.io/docs/custom-endpoint-decorators.html#custom-endpoint-decorator) and could be great (and seems easy to implement) add also a similar method in nest.

**Comment by kamilmysliwiec** [comment]
We can provide `applyDecorators` function, but basically, as @marcus-sa mentioned, composing decorators doesn't require any additional helper function - you can do that as well with Nest decorators.

**Comment by karlos1337** [comment]
@kamilmysliwiec yeah, I could add that helper method in my own app code but could be useful also in nest core and IMHO is a so common feature and lib size increase is insignificant.
PR added, apply or let me know if need any modification ;)

**Comment by kamilmysliwiec** [comment]
Added in 6.9.0
