### ISSUE TITLE
Allow to grab REQUEST_CONTEXT_ID

### ISSUE THREAD

**Issue by kdubb** [nestjs/nest#3105]
## Current behavior
`ModuleRef.resolve` doesn't work correctly when resolving `REQUEST` scope dependencies from a controller/service. The call to `resolve` generates a new `contextId` because there is _seemingly no method_ to get the "current" context id that generated the requesting controller.

This has the effect of creating new dependencies for a scope that will be discarded nearly immediately and items in that scope will not wire to the current request's scope. This causes problems when a dependency tries to get the current request (using `@Inject(REQUEST)`) because it doesn't exist in this temporary isolated scope.

## Input Code

```ts
    @Injectable({scope: Scope.REQUEST))
    class Logger {
      constructor(@Inject(REQUEST) request) {}
    }

    @Injectable({scope: Scope.REQUEST))  //Scope implicit due to Logger dependency
    class SomeCommandHandler implements CommandHandler {
      constructor(private readonly logger: Logger) {...}
    }

    @Injectable({scope: Scope.REQUEST))
    class SomeController {
      constructor(private readonly module: ModuleRef) {}

      dispatch(@Request() req: any) {
        const handler = await this.module.resolve<CommandHandler>(getCommandHandlerToken(command.command));  // Maps to `SomeCommandHandler` using a custom provider
    }
```

## Expected behavior
`ModuleRef.resolve` would produce a properly wired `SomeCommandHandler` with a `Logger` that has access to the current request.

## Possible Solution

First when a context id is generated,  if one is not already assigned to the request object...
https://github.com/nestjs/nest/blob/a68ae579d4cf6f096708188a861d8a3b76a3268d/packages/core/router/router-explorer.ts#L260

it **never** gets assigned back to the request.  This seems incorrect because it is now inaccessible anywhere outside this usage.  Also, in `MiddlewhereModule.registerHandler`, the only other place a context is generated, it **is** assigned back to the request.

Second, `REQUEST_CONTEXT_ID` seems like it should be injectable like its sibling `REQUEST` is allowing easy access to it; although if the above is fixed it will be accessible via the request object itself.

Finally, `ModuleRef` should carry the `REQUEST_CONTEXT_ID` that generated it inside itself (if it was injected into a request scoped object) and `resolve` should use that context id if none is passed into the resolve argument. As was laid out above it currently just generates a new context id which causes all the issues. 

## Environment

<pre><code>
Nest version: 6.6.3
 
For Tooling issues:
- Node version: 12.10.8
- Platform:  Mac

Others:
</code></pre>

**Comment by kdubb** [comment]
FYI, I hacked my `RouterExplorer` to assign the generated context id to the request and then I passed that to `ModuleRef.resolve` using the request object.  It then produces the correct object with all dependencies as they should be.

**Comment by hovonako-KMS** [comment]
It's could be better if we have method: ModuleRef.resolveByCurrentContextId(TOKEN)

**Comment by kdubb** [comment]
@kamilmysliwiec You changed this to "enhancement" but the problem is related to resolving dependencies from request scoped beans.  Currently `resolve` is _broken_ so enhancement is the a correct label.

Also, Is there any workaround that doesn't require a core change?

**Comment by kdubb** [comment]
For anybody experiencing the same issue, a workaround is to assign a `REQUEST_CONTEXT_ID` _before_ NestJS begins handling the request.

When using the `FastifyAdapter` it looks like this...
```typescript
fastifyInstance
  .addHook('onRequest',
           (req: FastifyRequest, reply: FastifyReply<any>, done: (err?: Error) => void) => {
             req[REQUEST_CONTEXT_ID] = { id: randomStringGenerator() } as ContextId;
             done();
           });
```

**Comment by kamilmysliwiec** [comment]
@kdubb `resolve()` isn't broken, this is how it is supposed to work. The only thing we should provide is the way to grab current request context id.

**Comment by kdubb** [comment]
@kamilmysliwiec  First, NestJS is awesome and I am grateful for all the hardwork the team has put into it. We've rearchitected a new version of our app using it and couldn't be more pleased with it.

That being said... If I try to use `resolve()` (without workarounds) it crashes the current request due to missing dependencies with no warnings or error explanations. That's only _after_ you work past an error about the undefined context id.

It required hours of debugging (considering I have no previous knowledge of NestJS) followed by a couple hours more to figure out a hack. Finally, another half day of tinkering to discover a workaround that could be shipped. 

Sincerely, with all due respect... it's broken.

**Comment by kamilmysliwiec** [comment]
Can you provide a minimal repository which reproduces your issue?

**Comment by kdubb** [comment]
@kamilmysliwiec I've added an example to my issue example repo @ https://github.com/kdubb/nest-fastify-req-scoped

Specifically, in `RequestScopedController.postResolve1` you'll notice that, in its current state, it fails to inject dependencies into the "resolved" `SomeService`.

You can fix the injection problem by generating a contextId and passing it to the `resolve` method. Although, since it's not the same contextId as the current request is using then `OtherService` fails because one of its dependencies is `@Inject(REQUEST)`, of which there is no current value.

**Comment by kamilmysliwiec** [comment]
Tracking this here https://github.com/nestjs/docs.nestjs.com/pull/953/files

**Comment by jessepinho** [comment]
Wanted to follow up on this. As far as I can tell, @kdubb's issue still doesn't seem to be addressed. 

I've created another [minimal reproduction](https://github.com/jessepinho/nestjs-context-id-repro) of this issue:
- I attached the request context ID to the request object ([code](https://github.com/jessepinho/nestjs-context-id-repro/blob/6f5bf790f907df039597865b0fb2c137234c4769/src/main.ts#L8-L12)).
- I used that context ID inside my `UsersService` to resolve a request-scoped service called `QueryService` ([code](https://github.com/jessepinho/nestjs-context-id-repro/blob/6f5bf790f907df039597865b0fb2c137234c4769/src/users/users.service.ts#L15-L19))
- But then the request-scoped `QueryService` is instantiated with an `undefined` request ([code](https://github.com/jessepinho/nestjs-context-id-repro/blob/6f5bf790f907df039597865b0fb2c137234c4769/src/query/query.service.ts#L8)).

I've added log lines so that you can run it locally and see the same results. Any ideas @kamilmysliwiec?

**Comment by kamilmysliwiec** [comment]
You shouldn't assign `REQUEST_CONTEXT_ID` manually (it's generated automatically by the framework). Please, follow this guide https://docs.nestjs.com/fundamentals/module-ref#getting-current-sub-tree
