### ISSUE TITLE
[Question] How control global and non-global Pipe order?

### ISSUE THREAD

**Issue by galkin** [nestjs/nest#3108]
### Question
How control global and non-global Pipeline order?

At my application I have global ValidationPipe added with **useGlobalPipes** and custom ParseDatePipe added with **Query** decorator. I want run ParseDatePipe before ValidationPipe. How can I achieve that?

### Examples
```typescript
...
  app.useGlobalPipes(new ValidationPipe({ transform: true }));
...
```

```typescript
...
  @Post('/')
  async routerHanderl(
    @Query('date', new ParseDatePipe(false, () => new Date())) date: Date
  ) {
...
```

```typescript
import { ArgumentMetadata, BadRequestException, PipeTransform } from '@nestjs/common';

export class ParseDatePipe implements PipeTransform<string | undefined, Date> {
  constructor(private readonly required: boolean, private readonly defaultValue: () => Date = () => new Date()) {}

  transform(value: string | undefined, metadata: ArgumentMetadata): Date {
    if (value === undefined) {
      if (this.required) throw new BadRequestException(`'${metadata.data}' at '${metadata.type}' is required`);
      return this.defaultValue();
    }
    if (isNaN(Date.parse(value))) {
      throw new BadRequestException(`${value} for '${metadata.data}' at '${metadata.type}' has wrong value`);
    }
    return new Date(value);
  }
}
```

**Comment by kamilmysliwiec** [comment]
Pipes always run in the following order:
- global pipes
- controller-level pipes
- route-level pipes

You can control the order *per* level, but you can't change levels order. You can't run route-level pipe before global pipe. Likewise, you can't run controller-level pipe after route-level one

**Comment by galkin** [comment]
Could we make improvement:
- global pipes
- controller-level pipes
- route-level pipes
- controller-level pipes with `UseEndingPipes`
- global pipes with `useGlobalEndingPipes`

I will happy to open pull request with such improvement?
