### ISSUE TITLE
Passing params to middleware

### ISSUE THREAD

**Issue by rwienrot** [nestjs/nest#3124]
Hi together,

I just want to pass a parameter to my middleware and found this article https://github.com/nestjs/nest/issues/3

While trying to use the with-property on that described way:

```
export class GatewayModule implements NestModule {
    configure(consumer: MiddlewareConsumer) {
      consumer.apply(ProxyMiddleware)
          .with('myParamString')
          .forRoutes('gateway/test');
}
```
I get this error message
`error TS2339: Property 'with' does not exist on type 'MiddlewareConfigProxy'.`

Having a look into the named interfaces I indeed find only the properties "apply", "forRoutes", "exclude" and so on but no "with". So my question: How is the way to pass parameters to middleware and how can I read out these parameters? My Middleware-class is looking so:

```
@Injectable()
export class ProxyMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: Function) {
    console.log(`In ProxyMiddleware with param...`);
    next();
  }
}
```
Thanks for any support.

**Comment by kamilmysliwiec** [comment]
See https://github.com/nestjs/nest/issues/1378
