### ISSUE TITLE
req.body empty in NestMiddleware

### ISSUE THREAD

**Issue by wintertime-inc** [nestjs/nest#3148]
## Current behavior
Currently based on the process of bodyParser and middleware, I must create one which will be body/headers related to handle further request to the database (e.g. based on request select specific DB, not hard coded) everything been working till I figured that the req.body is empty in this context so I used raw-body instead, but while doing it, it happen that body is purged somewhere in process and it is not assigned to next function.

So 2 questions there:

1. How to enable req.body in Middleware? Currently req.body always returns undefined while data is placed. If I get this right Middleware can be used to tuning the request a bit, before it is sent to the controllers and validations etc.
2. How come body is purged in process of using simple Middleware with raw-body?

## Input Code
```ts
My main.ts:

    app.useGlobalFilters(new QueryFailedErrorFilter());
    app.useGlobalPipes(
        new ValidationPipe({
            whitelist: true
        }),
    );
    app.use(new MyMiddleware().use);

My MyMiddleware (regarding question 1.):

import { Injectable, NestMiddleware } from '@nestjs/common';
@Injectable()
export class MyMiddleware implements NestMiddleware {
    use(req, res, next: Function) {
            req.body is always undefined
}

My MyMiddleware (regarding question 2.):

import { Injectable, NestMiddleware } from '@nestjs/common';
@Injectable()
export class MyMiddleware implements NestMiddleware {
    async use(req, res, next: Function) {
            if (req.url === '/login' && req.method === 'POST') {
                const body = await rawbody(req);
                const bodyJSON = JSON.parse(body.toString());
                const bodyJsonMail = bodyJSON.mail;
                ...
            }
           next();
}
```

## Expected behavior
I would like to operate body in Middleware (get one value from it) and then have use of ValidationPipe for further validation of given bodies.

## Environment

<pre><code>
Nest version: 6.8.1
 
For Tooling issues:
- Node version: 10.15.3
- Platform:  Windows

</code></pre>

**Comment by wintertime-inc** [comment]
I don't need to have it working for now, as I took different approach, however I think it would be nice to see req.body in middleware.

**Comment by kamilmysliwiec** [comment]
Your middleware is applied before `bodyParser`. Instead of using `app.use()`, you should rather follow this example: https://docs.nestjs.com/middleware#applying-middleware, so in your case:

```typescript
 consumer
      .apply(MyMiddleware)
      .forRoutes('*');
```
