### ISSUE TITLE
The middleware not apply when use fastify server

### ISSUE THREAD

**Issue by underfin** [nestjs/nest#3149]
## Current behavior

The middleware not apply (no log) when use fastify server.It is work when use express server.
## Input Code

https://codesandbox.io/s/likui-nest-repo-wlbn9?from-embed

## Expected behavior

The middleware should work when use fastify server
## Environment

<pre><code>
Nest version: 6.8.2

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by underfin** [comment]
```
this.instance.use(normalizedPath, (req, res, next) => {
        const queryParamsIndex = req.originalUrl.indexOf('?');
        const pathname =
          queryParamsIndex >= 0
            ? req.originalUrl.slice(0, queryParamsIndex)
            : req.originalUrl;

        if (!re.exec(pathname + '/') && normalizedPath) {
          return next();
        }
        if (
          requestMethod === RequestMethod.ALL ||
          req.method === RequestMethod[requestMethod]
        ) {
          return callback(req, res, next);
        }
        next();
      });
```
The code in packages/platform-fastify/adapters/fastify-adapter.ts. 
I debug this because it into first condition.Maybe change condition order can fix it.
I hope work it if you confim which it is a bug and get reply for this, thanks.

**Comment by kamilmysliwiec** [comment]
Can you provide the github repo to clone?

**Comment by underfin** [comment]
https://github.com/underfin/nest-repo.git

**Comment by kamilmysliwiec** [comment]
For fastify path matching, we use this package https://github.com/pillarjs/path-to-regexp https://github.com/pillarjs/path-to-regexp#usage

**Comment by underfin** [comment]
Yea, I get this of path-to-regexp which use fastify path match in nest.But express also use this package.
Would you repetition behavior with this? I think the behavior of fastify  should be same with express.

**Comment by kamilmysliwiec** [comment]
Feel free to create a PR if you see any way we could improve the consistency.

**Comment by underfin** [comment]
Thanks for your reply.I will have a try for this.

**Comment by jsdevtom** [comment]
Passing the controller to the `forRoots` also doesn't work with fastify. Eg: `.forRoutes(CatsController);` 
Is this the same issue?

**Comment by underfin** [comment]
@jsdevtom. I dont repetition your issues.Can you provider the repo with your code?

**Comment by jsdevtom** [comment]
@underfin Here is the live, working reproduction of the issue: https://codesandbox.io/embed/nest-lq9zp?fontsize=14&initialpath=%2Fchild%2Fblah&module=%2Fsrc%2Fchild%2Fchild.module.ts Please tell me if I am mistaken.

**Comment by underfin** [comment]
@jsdevtom. Look like is a bug in fastify with your issues.
You can look like this repo (https://codesandbox.io/embed/condescending-germain-qh0x7).
Wildcard path dont work.Doc is here https://www.fastify.io/docs/latest/Middleware/

**Comment by jsdevtom** [comment]
@underfin Thanks for replying.

The wildcard path _does_ work. Both your examples that you linked to demonstrate that the wildcard works. (Visit https://qh0x7.sse.codesandbox.io/css/sdf and see the [fastify docs](https://www.fastify.io/docs/latest/Middleware/#restrict-middleware-execution-to-a-certain-path-s-) where it says that wildcards are not supported in **multiple paths**). 

The NestJS docs don't state that the forChild method doesn't work with fastify so I assume this really is a bug. What do you think?

**Comment by underfin** [comment]
@jsdevtom .I think shuold report the problem to fastify.

**Comment by kamilmysliwiec** [comment]
It seems to be a fastify issue
