### ISSUE TITLE
Dynamic basePath feature.

### ISSUE THREAD

**Issue by wintertime-inc** [nestjs/nest#3155]
## Feature Request
Add possibility to support dynamic base path to the services.

## Describe the solution you'd like

Currently you can setup global prefix of the app itself in static way:
https://docs.nestjs.com/faq/global-prefix

It would be nice to have possibility to create dynamic base path.
E.g. {**dynamicBasePath**}/api/something

So then {**dynamicBasePath**} could be inject into Middleware which can be used to customize request and response as per dynamicBasePath.

Use case:

There is the same controller for all basePaths, for example **users**.
There can be only one controller and then argument @BasePath() path, could be inject into the method which could be later used for service call, and then up to the logic it will take repo dynamically.

Every request {**dynamicBasePath**}/api/users will be routed to the /api/users controller with basePath value of dynamicBasePath.

```
controller:

public getById(@BasePath() path, @Param() userId: string) {
        return this.service.find(path, userId);
}


userService.findOne:

//example1:
public find(path, userId){
    if (path === 'v1') {
        useOldRepository.get(userId)
    }
    if (path === 'v2') {
        useNewRepository.get(userId)
    }
  }

//example2:
public find(path, userId){
   getDynamicContainer(path).get(userId)
}
```

But the whole idea behind this is that, we have possibility to specify action in similar way to @Request or @Headers in more and flexible way. Just to have a simple example, but there are several better use cases of having dynamic base path.

**Comment by kamilmysliwiec** [comment]
> Currently you can setup global prefix of the app itself in static way:
https://docs.nestjs.com/faq/global-prefix

Well, you can actually use param for that (`setGlobalPrefix(':version')`) but it won't make sense in the most of the possible scenarios. You can actually define your own controller decorator:

```
export const MyController = (path: string) => Controller(`:version/${path}`)
```
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
