### ISSUE TITLE
@Query() does not transform to DTO

### ISSUE THREAD

**Issue by jselesan** [nestjs/nest#3156]
## Current behavior
I have a controller that needs to recive data from the request query and I want to put that data into a DTO using @Query() but it does not properly transform the DTO to the target interface

## Input Code
```ts
import { Get, Controller, Query, Post, Body, UsePipes, ValidationPipe } from '@nestjs/common';

interface TestDto {
  field1: number;
  field2: boolean;
}

@Controller()
export class AppController {
  constructor() {}

  @Get()
  @UsePipes(new ValidationPipe({ whitelist: false, transform: true}))
  root(@Query() dto: TestDto): TestDto {
    return dto;
  }

}
```

## Expected behavior
If I call **http://localhost:3000/?field1=10&field2=true&field3=test** I get

```ts
{
"field1": "10",
"field2": "true",
"field3": "test"
}
```
But the expected result is:
```ts
{
"field1":  10,
"field2": true
}
```

## Environment

<pre><code>
Nest version: 5.7.4
Node version: 10.9.0
class-transformer: 0.2.3
class-validator: 0.10.1
tsc version: 1.8.10
Platform: Ubuntu 18.10

</code></pre>

**Comment by wintertime-inc** [comment]
whitelist must be setup to true in order to cut additionals

**Comment by kamilmysliwiec** [comment]
You haven't used any validation decorator (which is required)

**Comment by jselesan** [comment]
I'm sorry @kamilmysliwiec, I've added the decorators and changed from interface to class:

```ts
export class TestDto {
  @IsNumber()
  field1: number;
  @IsBoolean()
  field2: boolean;
}
```
But now, I get the following error message:

```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": [
    {
        "target": {
           "field1": "15",
           "field2": "false"
        },
       "value": "15",
       "property": "field1",
       "children": [],
      "constraints": {
      "isNumber": "field1 must be a number"
    }
},
{
    "target": {
       "field1": "15",
       "field2": "false"
    }, 
    "value": "false",
    "property": "field2",
    "children": [],
    "constraints": {
    "isBoolean": "field2 must be a boolean value"
  }
}
]
}
```
If I change @IsNumber to @IsNumberString and @IsBoolean to @IsBooleanString it validates, but I do not get the transformed dto

**Comment by QJvic** [comment]
> I'm sorry @kamilmysliwiec, I've added the decorators and changed from interface to class:
> 
> ```ts
> export class TestDto {
>   @IsNumber()
>   field1: number;
>   @IsBoolean()
>   field2: boolean;
> }
> ```
> 
> But now, I get the following error message:
> 
> ```json
> {
>   "statusCode": 400,
>   "error": "Bad Request",
>   "message": [
>     {
>         "target": {
>            "field1": "15",
>            "field2": "false"
>         },
>        "value": "15",
>        "property": "field1",
>        "children": [],
>       "constraints": {
>       "isNumber": "field1 must be a number"
>     }
> },
> {
>     "target": {
>        "field1": "15",
>        "field2": "false"
>     }, 
>     "value": "false",
>     "property": "field2",
>     "children": [],
>     "constraints": {
>     "isBoolean": "field2 must be a boolean value"
>   }
> }
> ]
> }
> ```
> 
> If I change @IsNumber to @IsNumberString and @IsBoolean to @IsBooleanString it validates, but I do not get the transformed dto

hey frieng,did you fix this problem?I am facing this problem now.

**Comment by Hwan-seok** [comment]
Use `@Type` on your properties.
`@Query` always return string type so we have to cast to desired type.
### Example
```typescript
import { Type} from 'class-transformer';

export class TestDto {
  @IsNumber()
  @Type(()=>Number)
  field1: number;

  @IsBoolean()
  @Type(()=>Boolean)
  field2: boolean;
}
```

**Comment by joanna-liana** [comment]
The solution with `@Type` kinda works, but it'll return `true` for any string passed to the query param.
Another workaround is to use `@Transform`:

```
 @Transform(value => {
   if (value === 'true') return true;
   if (value === 'false') return false;
   return value;
 })
```

**Comment by romerojunior** [comment]
A better approach would be passing `enableImplicitConversion` to your ValidationPipe, as such:

```typescript
app.useGlobalPipes(new ValidationPipe({
    transform: true,
    transformOptions: {
      enableImplicitConversion: true
    },
}));
```

Interface defined here:
https://github.com/nestjs/nest/blob/master/packages/common/interfaces/external/class-transform-options.interface.ts

**Comment by okuxxbos20** [comment]
I'm sorry @romerojunior, I tried your approach but a boolean value is always true.  

So, when I post a boolean value like `isActive`: false, 
```typescript
 ExampleDTO {
  name: 'sample',
  isActive: true,
  age: 32,
  description: 'test description...'
}
```

Unfortunately,  `isActive` values in DB are all true.😢

**Comment by CoderSpinoza** [comment]
@romerojunior @okuxxbos20 

> I'm sorry @romerojunior, I tried your approach but a boolean value is always true.
> 
> So, when I post a boolean value like `isActive`: false,
> 
> ```ts
>  ExampleDTO {
>   name: 'sample',
>   isActive: true,
>   age: 32,
>   description: 'test description...'
> }
> ```
> 
> Unfortunately, `isActive` values in DB are all true.😢

I am experiencing the same issue. Could this be a bug?

**Comment by jmcdo29** [comment]
If you believe it is a bug please provide a [minimum reproduction](http://minimum-reproduction.wtf)

**Comment by goalia** [comment]
Hello 🖖 
We're experiencing the same problem while using boolean in query params @QuanticPotatoes

When we send undefined for a boolean value, I received true as a value 🥇
