### ISSUE TITLE
Code coverage in e2e tests

### ISSUE THREAD

**Issue by matthew-bajorek-fastfin** [nestjs/nest#3169]
## Current behavior
Collecting coverage on e2e test results in no files covered.

## Input Code
By using 
```bash
nest new project-name
```

Then in test/jest-e2e.json add key "collectCoverage": true

```ts
{
  "moduleFileExtensions": ["js", "json", "ts"],
  "rootDir": ".",
  "testEnvironment": "node",
  "testRegex": ".e2e-spec.ts$",
  "transform": {
    "^.+\\.(t|j)s$": "ts-jest"
  },
  "collectCoverage": true
}
```

Then run
```bash
npm run test:e2e
```

## Expected behavior
Code coverage should be shown from app.controller.ts and app.service.ts.

## Possible Solution
It seems as the module fixture is not being imported for tracking by jest.

## Environment

<pre><code>
Nest version: 6.10.1
 
For Tooling issues:
- Node version: v12.10.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by matthew-bajorek-fastfin** [comment]
This was solved by switching over jest to mocha and using yarn instead of npm.

**Comment by velut** [comment]
I solved this as follows:

1. Move `jest-e2e.json` from the `test` directory to the root directory of the project (where `package.json` is located)

2.  Change the contents of `jest-e2e.json` to the following:

```json
{
    "moduleFileExtensions": ["js", "json", "ts"],
    "rootDir": ".",
    "testEnvironment": "node",
    "testMatch": ["<rootDir>/test/**/*.e2e-spec.{ts,js}"],
    "transform": {
        "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "./coverage-e2e"
}
```

3. Change the `test:e2e` script inside `package.json` to:

```json
"test:e2e": "jest --config ./jest-e2e.json"
```

Now running the `test:e2e` script with the `--coverage` flag should generate the required coverage inside the `coverage-e2e` directory.

**Comment by mick352** [comment]
If someone has a problem with a self-defined mock: you can disable that mock e.g. for typeorm with 
 ```
jest.unmock('typeorm')
```

**Comment by Tom-DK** [comment]
> I solved this as follows:
> 
> 1. Move `jest-e2e.json` from the `test` directory to the root directory of the project (where `package.json` is located)
> 2. Change the contents of `jest-e2e.json` to the following:
> 
> ```json
> {
>     "moduleFileExtensions": ["js", "json", "ts"],
>     "rootDir": ".",
>     "testEnvironment": "node",
>     "testMatch": ["<rootDir>/test/**/*.e2e-spec.{ts,js}"],
>     "transform": {
>         "^.+\\.(t|j)s$": "ts-jest"
>     },
>     "coverageDirectory": "./coverage-e2e"
> }
> ```
> 
> 1. Change the `test:e2e` script inside `package.json` to:
> 
> ```json
> "test:e2e": "jest --config ./jest-e2e.json"
> ```
> 
> Now running the `test:e2e` script with the `--coverage` flag should generate the required coverage inside the `coverage-e2e` directory.

Worked for me too, but I just changed the rootDir and the paths relative to it so I could keep my file structure.

**Comment by jeanfortheweb** [comment]
I just realized, that you just have to change the "rootDir" to "..", that's it. Maybe that could be the default?

**Comment by bingtsingw** [comment]
> I just realized, that you just have to change the "rootDir" to "..", that's it. Maybe that could be the default?

Thank you, it works for me.

For anyone who searched this problem from google.
Just change `test/jest-e2e.json` file content to:
```
{
  "moduleFileExtensions": ["js", "json", "ts"],
  "moduleNameMapper": {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@test/(.*)$": "<rootDir>/test/$1"
  },
  "rootDir": "..",
  "testEnvironment": "node",
  "testRegex": ".e2e-spec.ts$",
  "transform": {
    "^.+\\.(t|j)s$": "ts-jest"
  }
}

```

You can also add some scripts in `package.json`
```
"scripts": {
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "test:e2e:watch": "jest --config ./test/jest-e2e.json --watch",
    "test:e2e:cov": "jest --config ./test/jest-e2e.json --coverage",
}
```
