### ISSUE TITLE
How to print errors

### ISSUE THREAD

**Issue by Kamshak** [nestjs/nest#317]
Hey, just a quick support request: 

I have made a mistake now my app throws an error:
```
[Nest] 28   - 2017-12-20 17:13:56   [ExceptionsHandler] [object Object]
```
This log is of course pretty useless (although nicely colored). So i've tried overwriting the logging in my server.ts:
```
app.useGlobalFilters({
    catch: (e: any, res: any) => {
      console.error(e);
      res.status(500).send(e);
    }
  });
```
Unfortunately this does nothing at all. Help would be much appreciated!

**Comment by Kamshak** [comment]
Tried this as well:

```
@Catch(Error)
class Handler {
  catch(e: any, res: any) {
    console.error(e);
    res.status(500).send(e);
  }
}

app.useGlobalFilters(new Handler());
```

**Comment by shekohex** [comment]
could you explain more ?
is this an error from un handled code , or from Nest ?
and you may have a look at #[Nest-Flub](https://github.com/shekohex/nestjs-flub)

**Comment by nicolaslt** [comment]
@Kamshak It looks like you might be using the RPC transport? If so, have very similar issues. #316 #303

**Comment by nicolaslt** [comment]
Actually not using RPC transport on account of `res` usage. Ignore me.

**Comment by kamilmysliwiec** [comment]
Hi @Kamshak,
In `4.5.2` you should be able to catch each exception, including those that not extend `Error`. In order to do that, just left the parentheses empty `@Catch()` https://docs.nestjs.com/exception-filters

**Comment by Kamshak** [comment]
Thanks!

**Comment by claudiuchis** [comment]
As of nest 5.0.0, the 2nd param of the catch method is not a response, but an ArgumentHost, which encapsulates the response. 

```
import { ExceptionFilter, Catch, HttpException, ArgumentsHost } from '@nestjs/common';

@Catch()
export class ErrorFilter implements ExceptionFilter {
  catch(error: Error, host: ArgumentsHost) {
    let res = host.switchToHttp().getResponse();
    let message;
    let status;  
    if (error instanceof HttpException) {
        status = error.getStatus();
        message = error.getResponse();
    } else {
        status = 500;
        message = 'Internal error';
    }
    return res.status(status).json({ message, status });  
  }
}
```
