### ISSUE TITLE
Custom validation pipe called twice, since Nest 6.8.3

### ISSUE THREAD

**Issue by NAlexandrov** [nestjs/nest#3201]
## Current behavior
Custom validation pipe called twice, since Nest 6.8.3

## Input Code
I have simple microservice with next method:

```ts
  @MessagePattern({
    cmd: 'notifications:get',
    topic: 'notificator',
  })
  @UsePipes(selectionSchema)
  async getNotifications(@Query() query: NotificationSelection) {
    ...
  }
```

And I have custom validation pipe based on Ajv
```ts
@Injectable()
export class AjvValidationPipe implements PipeTransform {

  ...

  transform(data: { [key: string]: any }) {
    // this method called twice
    // first with data = undefined
    // second with valid data
  }

  ...

}
```

## Expected behavior
Custom validation pipe called only once as at previous versions of Nest.js

## Possible Solution
Downgrade to 6.8.2 or early

## Environment

<pre><code>
Nest version: 6.8.3

For Tooling issues:
- Node version: 10.6.3
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by NAlexandrov** [comment]
@kamilmysliwiec https://github.com/NAlexandrov/nest-validation-pipe-error

**Comment by kamilmysliwiec** [comment]
Fixed in the latest patch release. Let me know if you face any issues
