### ISSUE TITLE
Nest exits silently if app.listen() is given invalid IP address

### ISSUE THREAD

**Issue by dolsem** [nestjs/nest#3209]
## Current behavior

Currently if Nest is given an IP address that the server cannot listen on with any of the existing network interfaces, the app starts and then silently exits with no error message being thrown. This makes it very difficult to track down the issue.

## Input Code

```ts
async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(fastify({ logger })),
  );
  const config = app.get(ConfigService);
  await app.listen(config.port, config.address);
}
bootstrap();
```

## Expected behavior

An error should be thrown that informs the user that the server cannot bind to this address + port.

## Environment

<pre><code>
Nest version: 6.5.3

 
For Tooling issues:
- Node version: v12.10.0
- Platform:  Linux

</code></pre>

**Comment by jmcdo29** [comment]
@dolsem the problem here is that the underlying Node HTTP server's listen doesn't throw an error, but instead uses callbacks. Maybe an error handler [could be added here](https://github.com/nestjs/nest/blob/master/packages/core/nest-application.ts#L236) for the case of a bad port and hostname. change it to something like
```ts
public listenAsync(port: number | string, hostname?: string): Promise<any> {
    return new Promise(resolve => {
      const server: any = this.listen(port, hostname, (err) => err ? reject(err) : resolve(server));
    });
  }
```
Even Express doesn't throw an error when you provide a bad port according to their code. Could be a good improvement though

**Comment by dolsem** [comment]
@jmcdo29 I looked into your suggestion and found out that Nest's listen() function does accept callback as its third argument. This callback does indeed return an error with code EADDRNOTAVAIL, though its TS type definition is incorrect (function with no arguments).

Personally I find this API counter-intuitive, since this is an async method. I think listen method promise should reject with this error (which can then obviously be caught and handled by the user).

**Comment by jmcdo29** [comment]
I believe the only reason the `listen` method is marked as `async` is to allow for the `await this.init()` function if it needs to be called. Maybe it makes more sense to return a `promise` in the `listen` method and remove `listenAsync` as they both should return the same thing (a promise of the httpServer). And yeah, looks like the callback function's parameters should be updated.

**Comment by kamilmysliwiec** [comment]
Good point @jmcdo29

**Comment by dolsem** [comment]
@kamilmysliwiec sorry for a late response. I'd be happy to create a PR, but I've been very busy lately. Might get to it in the next week or so.

**Comment by Sikora00** [comment]
Is that issue still available to take? I could take that.

**Comment by dolsem** [comment]
@Sikora00 the PR attached above is fixing this issue

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/3360
