### ISSUE TITLE
Dynamic Module that implements NestModule does not invoke `configure`

### ISSUE THREAD

**Issue by jasperblues** [nestjs/nest#3219]
## Bug Report

From what I can see a DynamicModule (eg assembled from a module builder class) does not invoke `configure` from NestModule interface, even if the built module conforms to this protocol. 

## Current behavior

```typescript
    public build(): DrivineModule {
        return Object.assign(new DrivineModule(), {
            module: DrivineModule,
            providers: this.providers,
            exports: this.providers,
            configure(consumer: MiddlewareConsumer): any {
                this.logger.log(`Applying transactional context middleware`);
                consumer.apply(TransactionContextMiddleware).forRoutes('**/**');
            }
        });
    }
```
^-- the `configure` method above is not invoked. 

Sorry if this report contains insufficient details - super busy atm. Please close it, if it is not helpful and I will report back with more information when I'm not busy.

**Comment by kamilmysliwiec** [comment]
```
public build(): DrivineModule {
        return Object.assign(new DrivineModule(), {
            module: DrivineModule,
            providers: this.providers,
            exports: this.providers,
            configure(consumer: MiddlewareConsumer): any {
                this.logger.log(`Applying transactional context middleware`);
                consumer.apply(TransactionContextMiddleware).forRoutes('**/**');
            }
        });
    }
```

The above code is wrong and can't work properly.  
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by jasperblues** [comment]
Thank you - will be reasonably certain (99%) that there's a genuine bug in future. 

Meanwhile, there's a good community on the Discord channel and I received the advice that I needed.
