### ISSUE TITLE
Following GraphQL quick start leads to error

### ISSUE THREAD

**Issue by Akxe** [nestjs/nest#3221]
## Bug Report

Following graphQL quickstart from "Nest TypeScript starter repository" leads to error

## Input Code
https://github.com/Akxe/Rex-server/tree/graphQL (temporary, once fixed I'll make it private once again)

```ts
@Module({
	imports: [
		CarriersModule,
		GraphQLModule.forRoot({
			installSubscriptionHandlers: true,
			autoSchemaFile: 'schema.gql',
		}),
	],
	controllers: [AppController],
	providers: [AppService],
})
export class AppModule {}

@Module({
	providers: [CarriersResolver],
})
export class CarriersModule {}

@Resolver()
export class CarriersResolver {

	@Query(() => String)
	async carriers() {
		return 'carriers';
	}
}
```

## Expected behavior
Compilation error? (Not sure maybe runtime)
`Error: Apollo Server requires either an existing schema, modules or typeDefs`

## Possible Solution
Running code via `ts-node -r tsconfig-paths/register src/main.ts` instead of `npm run start:dev` works... (I saw it in a video tutorial I followed too)

## Environment

<pre><code>
Nest version: 6.8.3 (^6.8.0)
 
For Tooling issues:
- Node version: v12.6.0
- Platform: Windows 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
@johnbiundo can you test on Windows?

**Comment by johnbiundo** [comment]
@kamilmysliwiec the repo from @Akxe compiled and started for me on Windows with the latest release of Nest.

I will try to test sample #23 when I get a chance as well.

**Comment by johnbiundo** [comment]
Sample #23 also compiles and starts on Windows with latest version (re: #3220).

**Comment by Akxe** [comment]
It indeed works without any more fiddling, thus this can be closed. Amazing work :)

PS: Re-making my repo private
