### ISSUE TITLE
i want use worker_threads in my project and ts-node 

### ISSUE THREAD

**Issue by zhaojunlike** [nestjs/nest#3226]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

hello，if i create a workspace ,i use ts-node throw error
Error: Cannot find module '@app/database/database.module'
Require stack:
- F:\workspace\nike.snkrs\node-nike-snkrs\snkrs-app\apps\tasker\src\app.module.ts

i use nest start:dev tasker it's ok
what should i do
anyone help me please
wo want use worker_threads in my project, and i create so many libs , but now ,i have to use the rest ci  to manage my project ,but in my project, i need to use ts-node to run my project。

em.....like this 
workspace
![image](https://user-images.githubusercontent.com/13638996/67169604-d1396680-f3de-11e9-9584-0fe275d5a65e.png)

tasker project
![image](https://user-images.githubusercontent.com/13638996/67169612-d8607480-f3de-11e9-9b1a-8cec31f499ff.png)

i should use `rest ci ` to manager project deps, now if i use nest-cli run my project it's ok,but if i use ts-node it's not work

```
> ts-node apps/tasker/src/main.ts
Error: Cannot find module '@app/database/database.module'
Require stack:
- F:\workspace\nike.snkrs\node-nike-snkrs\snkrs-app\apps\tasker\src\app.module.ts
- F:\workspace\nike.snkrs\node-nike-snkrs\snkrs-app\apps\tasker\src\main.ts

```

```
>nest start:dev tasker
It can work
```

**Comment by zhaojunlike** [comment]
My goal was to use rest my old projects, and Shared library file

**Comment by zhaojunlike** [comment]
I think, if I can use ts-node to run the project, so I can use worker_threads

**Comment by zhaojunlike** [comment]
I think the nest `DI` implementation is very perfect, I now want to use the nest in the part of the module only use di manage my project

**Comment by zhaojunlike** [comment]
I think may be I don't understand the typescript, but I still want to ask about my train of thought is workable

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
