### ISSUE TITLE
In graphql-apolllo example, can't find cat with findOneById method

### ISSUE THREAD

**Issue by dobest27** [nestjs/nest#3237]
## Bug Report
In graphql-apollo example, cat is being made without property named id. So, it can't find cat with findOneById method.

## Current behavior

Currently, cat is being made without property named id. So cats created by requests aren't found by findOneById().

## Input Code

```ts
@Injectable()
export class CatsService {
  private readonly cats: Cat[] = [{ id: 1, name: 'Cat', age: 5 }];

  create(cat: Cat): Cat {
    cat.id = this.cats.length + 1;
    this.cats.push(cat);
    return cat;
  }

  findOneById(id: number): Cat {
    return this.cats.find(cat => cat.id === id);
  }
}
```

## Expected behavior

- Expected create cat having property named id.
- Expected can find cat by findOneById method.

## Possible Solution

Add id property using length of cats array when create cat.
```ts
create(cat: Cat): Cat {
  cat.id = this.cats.length + 1;
  this.cats.push(cat);
  return cat;
}
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fix merged
