### ISSUE TITLE
Using fastify-rate-limit with nestjs

### ISSUE THREAD

**Issue by anwaar931** [nestjs/nest#3242]
Want to add fastify-rate-limit in nestjs. 

Has anybody done that or can help? 

```
import rateLimit from 'fastify-rate-limit'
import * as ms from 'ms'

rateLimit(
/*Here it is expecting FastifyInstance, not sure about this.*/,
	{
	    timeWindow: ms('1 minute'),
	    max: 100, // limit each IP to 100 requests per timeWindow
	},
	null,
	)
```
Someone also posted a question related to this on stackoverflow, no answer yet.
https://stackoverflow.com/questions/58376187/how-to-configure-rate-limit-with-fastify-adapter-in-nest-js

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
