### ISSUE TITLE
TypeOrm listeners not executed during e2e testing

### ISSUE THREAD

**Issue by igern** [nestjs/nest#3243]
## Current behavior

The issue manifests when running e2e test with typeorm and you try to save something to the the database. The corresponsing typeorm listerners are not being executed. These are shown in the code below.
The issue does not manifest when the application is ran normally. 
## Input Code

Individual.entity.ts
```ts
...
  @BeforeInsert()
  @BeforeUpdate()
  private encryptPassword(): void {
    if (this.tmpPassword !== this.password) {
      this.hashPassword();
      this.tmpPassword = this.password;
    }
  }

  @BeforeInsert()
  private hashPassword() {
    this.passwordSalt = bcrypt.genSaltSync();
    this.password = bcrypt.hashSync(this.password, this.passwordSalt);
  }
...
```
e2e.spec.ts
```ts
describe('AppController (e2e)', () => {
  let app: INestApplication;
  let module: TestingModule;
  let connection: Connection

  beforeAll(async () => {
    module = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    connection = module.get(Connection)
    app = module.createNestApplication();
    await app.init();
  })

  afterAll(async () => {
    module.close();
  })

  beforeEach( async () => {
    await connection.synchronize(true)
  })
...
```

## Expected behavior

I expect the behavior in the two listeners in the code to be executed before they are inserted into the database.

## Environment

<pre><code>
Nest version: 6.7.2

 
For Tooling issues:
- Node version: 10.16.3
- Platform: Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by igern** [comment]
This is not a question. I believe there is a bug when it comes to e2e testing with databases using typeorm. The behavior when running my Nest app normally and when it is run using the test framework from @nestjs/testing is different from one another. 
When i run it normally, TypeOrm listeners as described in the issue, are being executed properly causing the password to be hashed before they are saved in the database
When i run it in a test, they are not executed, causing different non hashed passwords to be saved.

I can not find any working examples/tests that documents this odd behavior.

**Comment by jmcdo29** [comment]
Do you have a repository that is mimicking this behavior? It seems strange that it would work in a normal start up and not in the e2e context, as nothing changes there. Could this be an issue with TypeORM directly?

**Comment by igern** [comment]
I have made a repository that tests this behavior: 
https://github.com/igern/Nestjs-Typeorm-e2e-testing
The repository just tests whether the TypeOrm listener is executed before insert.
It also contains a command to simply run the service so you can see the TypeOrm listeners are being executed normally.

**Comment by igern** [comment]
The problem was assumed to be caused by the jest environment not having access to the entity class fully causing it to not have the TypeOrm listeners and therefore not executing them. 
The fix in this case was to change the string used to find our entities in the TypeOrmModuleOptions from 
```
entities: ["dist/**/*.entity.{ts,is}"];
```
to
```
entities: [ __dirname + '/**/*.entity.{ts,js}'];
```

**Comment by mmbmatteo** [comment]
Found the same here.

Thank you @igern for the workaround 😄 👍
