### ISSUE TITLE
Chain multiple exception filters execution

### ISSUE THREAD

**Issue by valerio-battaglia** [nestjs/nest#3252]
## Is your feature request related to a problem? Please describe.
The issue is that I am not able to execute two exception filters as the filter themselves are actually single pointcut for the chain.

## Describe the solution you'd like
The first option would be to have `Filter` with a similar syntax to `Interceptor` such that developers can decide if the `Filter` is a pointcut or not.
A second option would be to apply a `Pipe` or an `Interceptor` at different levels, such as to catch errors from `Guard`.

## What is the motivation/use case for changing the behavior?
A request comes into the following API
```R
req -> TraceMiddleware -> AuthGuard -> LoggingInterceptor -> GQLResolver w/ TransformExceptionFilter(HttpException)
```
Each step can potentially throw an `Exception`, not necessarely an `HttpException`.
The `Exception` transformation is done in a `Filter` in order to be able to catch errors coming from any step.

As a new feature, I would like to have a logger to log every exception that is happening, potentially with the `ExecutionContext` from which is thrown, without having to change my existing filter to comply with SRP and prevent mixing up logging with transformation.
Possible scenarios:
- A `Middleware` would not have the `ExecutionContext`.
- An `ExceptionLoggingInterceptor` would not be called to log if the failure point is `TraceMiddleware` or `AuthGuard`.
- A second `Filter` would not be run together with the `TransformExceptionFilter`.

**Comment by kamilmysliwiec** [comment]
Exception filters were designed to be a pointcut. If you want to log every exception and at the same time, have multiple filters registered, wouldn't it be more predictable to use composition/inheritance instead? In case you want to make it even more dynamic, you could create a `MethodDecorator` that would wrap the actual function.

**Comment by valerio-battaglia** [comment]
Okay, but we can potentially have a chain of inheritance of which is hard to maintain at some later point, so we were wondering if there is a possibility to easy that out.

**Comment by kamilmysliwiec** [comment]
You can use composition in this case.

**Comment by valerio-battaglia** [comment]
Okay, thanks for the feedback. We will look into which solutions could be the best way to achieve it.
