### ISSUE TITLE
Loading and manipulating static files

### ISSUE THREAD

**Issue by rabr2ro** [nestjs/nest#3254]
Hello,

I have an ExpressJS server application and I thought it's a good candidate to migrate to NestJS, so I learn about NestJS framework. I work as a Web developer and I use Angular on daily basis, so I understood how the services and controllers should wok. But I got stuck before I begin.

My current expressJS application load data from json files, located in a 'data' folder on the backend, but I was not able to do this with NestJS and I had no success in finding any help on how could I do it. The idea was to load a json file from disk and, based on the url parameters, I find some items in the loaded json file and return those items as a json array to the frontend. The filtering logic I wanted to implement in a service, but I got stuck to the loading of the files.
I have several such json files, located in a data folder, that I could not even make it to be copied in the dist folder, when nestjs application is build.

For example, to respond to an url like 'customer/1', i wanted to load the customers.json file from disk, and from the customers list obtained after the loading, to return the customer[1] item.

I have another use case, where for an url like 'metamodel/formName', I want to load from the disk the json file with name 'test-formName-detail.json' (formName is the url parameter that tells what json file to load from the disk), to make some alteration to the data loaded from json file and return the new content to the frontend.

I saw nestJS documentation about, authentication, database, mvc, etc... but I'm not in any of these cases. So I decided that nestJS is not the appropriate framework to migrate my expressJS application.

Thank you and good luck,
Radu

**Comment by BrunnerLivio** [comment]
This is do-able with NestJS. Have a look at the [controllers chapter](https://docs.nestjs.com/controllers) where you can see how you can use URL parameters. Then just simply load the JSON file using the normal NodeJS [fs](https://nodejs.org/api/fs.html)-package and filter it by the given URL parameters. 

For the future - please, use our [Discord]( https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by rabr2ro** [comment]
Thank you for your quick reply.
I understood how to use the url parameters, but you still did not give me a solution how to make a 'data' folder (parallel with src) to be copied to the 'dist' folder.
Regarding discord channel, I do not have a discord account and I have no intention to make one. I have no use for it.
Thank you again for your answer, but I decided to keep my expressJS application.
