### ISSUE TITLE
Documents:  How Nestjs works with Node.js packages

### ISSUE THREAD

**Issue by svstartuplab** [nestjs/nest#3261]
## Is your feature request related to a problem? Please describe.
I tried figuring out how to use Nestjs with Cloudinary's Node SDK.  Brunner helped me in the Nestjs_framework Reddit.

## Describe the solution you'd like
Many of us now using Nestjs came from Angular and have no experience with Node and Express. We could use a documents page that helps us understand how to use Node NPM packages with Nestjs.  This seems mostly related to the current page on providers so that page should be referenced.

## Teachability, Documentation, Adoption, Migration Strategy
I have no knowledge of Node or Express so I can help with this.

## What is the motivation / use case for changing the behavior?
Make it easier for those of us new to this stack to understand how to use it to the full potential.

**Comment by kamilmysliwiec** [comment]
I would suggest checking the following articles:
- https://dev.to/nestjs/build-a-nestjs-module-for-knex-js-or-other-resource-based-libraries-in-5-minutes-12an
- https://dev.to/nestjs/advanced-nestjs-how-to-build-completely-dynamic-nestjs-modules-1370
- https://dev.to/nestjs/publishing-nestjs-packages-with-npm-21fm

written by @johnbiundo 💪
