### ISSUE TITLE
ExecutionContext argument in createParamDecorator

### ISSUE THREAD

**Issue by iniel** [nestjs/nest#3266]
## Is your feature request related to a problem? Please describe.

I have an issue with createParamDecorator. I'd like to use `createParamDecorator` to create a route parameter decorator `@Log`. It should return an instance of `Logger` with `CotrollerName_handlerName` context like this:

```
@Controller()
export class AppController {
	@Get()
	foo(@Log() logger: Logger) {
		logger.log('message');
		// [Nest] 70856   - 2019-10-25 12:09:33 PM   [AppController_foo] message
	}

	@Get()
	bar(@Log() logger: Logger) {
		logger.log('message');
		// [Nest] 70856   - 2019-10-25 12:09:33 PM   [AppController_bar] message
	}
}
```

But I have access only to the data and request objects in the `createParamDecorator` factory function. There is no information about execution context in it.

```
import {Logger} from '@nestjs/common';

export const Log = createParamDecorator((data, req) => {
  const context = ?
  return new Logger(context);
});
```

## Describe the solution you'd like

It would help if I could get access to the whole `ExecutionContext` object from the `createParamDecorator` factory function instead of request object.

**Comment by kamilmysliwiec** [comment]
Take a look at this PR https://github.com/nestjs/nest/pull/3070
Perhaps, instead of passing `ArgumentsHost` in 7.0.0, we could pass `ExecutionContext`?

**Comment by iniel** [comment]
Thank you! I think it's gonna work then.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/3070/files
