### ISSUE TITLE
Update ClassTransformOptions

### ISSUE THREAD

**Issue by jbjhjm** [nestjs/nest#3274]
ClassTransformOptions interface is missing the property "excludeExtraneousValues" which 
has been introduced in class-transformer version 0.21.

It might still be rather unknown but pretty useful as it allows to make sure that no unwanted properties can pass the transformation, as described [here](https://github.com/typestack/class-transformer#enforcing-type-safe-instance).

**Comment by SeWaS** [comment]
I opened a PR for this 👍

**Comment by kamilmysliwiec** [comment]
Added in 6.9.0
