### ISSUE TITLE
Plugin architecture

### ISSUE THREAD

**Issue by Disane87** [nestjs/nest#3277]
Hey guys, I already asked this question in your discord, but I think this channel is way better than discussing it in the discord.

For my current application I develop a core sever module with all needed controllers to get the application working (in the standard way). All other features should be added as plugins. In angular I have a way of plugging in modules at runtime, but now I need this for the backend too.

I my use case, I need a new feature, like "reporting". The package contains an angular module (for frontend) and a NestJS module with a subset of controllers (only for this use case).

Is this possible or how I can achieve that? I'm pretty new to NodeJS/NestJS but I'm experienced with angular and developing in general. 

As NodeJS is "only" JavaScript, is it possible to a plugin architecture working with SystemJS?

**Comment by kamilmysliwiec** [comment]
Can you show us an example of what you're trying to accomplish?

**Comment by BrunnerLivio** [comment]
I have to close this issue, since it is not related to NestJS - we use this issue tracker to track bugs & features related to Nest.

---

This questions is pretty open ended, since the different approaches are almost endless.

I'd recommend to you that you make use of NPM itself for its plugin system. This is how most popular libraries do it in Node.js (e.g. babel, nestjs, eslint, gatsbyjs).

**Comment by Disane87** [comment]
Yeah sure. It‘s not a code example but I can explain you the intention to clarify my question. 

My applications ships with a core functionality, like address management, login etc. 

If a customer wants to use an appointment module (with scheduling, crud operations for appointments etc) I want do develop it as a module which he can buy from a store and load the module at runtime into his already running application. I don’t want to bloat the core app with stuff he doesn‘t ever use and to prevent he sees some controllers of features he didn‘t bought. 

In Angular you can achieve this with lazy loaded modules and package them into a library which is loaded lazy into the application with some other stuff like inject running instances of modules into it.

**Comment by kamilmysliwiec** [comment]
You can achieve that with [dynamic modules](https://docs.nestjs.com/fundamentals/dynamic-modules) (dynamically set `imports` array of the dynamic module)

**Comment by Disane87** [comment]
> You can achieve that with [dynamic modules](https://docs.nestjs.com/fundamentals/dynamic-modules) (dynamically set `imports` array of the dynamic module based on the customer preferences [e.g. fetched from the db])

I've read the article about that, thank you @kamilmysliwiec , but I don't have a clue how to load the modules at runtime. 
While these plugins aren't declared while building, I can't load them with `module.register()` 

```ts

import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ConfigModule } from './config/config.module';

@Module({
  imports: [ConfigModule.register({ folder: './config' })],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

Or am I missing something?

**Comment by BrunnerLivio** [comment]
@Disane87 You can compute it inside of your module.

```typescript

@Module({})
export class PluginModule {
  static registerPlugins(): DynamicModule {
   // Get a list of of your dynamically loaded modules 
   // For demonstration purposes, I just use a static array
   const imports = [PluginAModule, PluginBModule];
    return {
      module: PluginModule,
      imports,
    };
  }
}

```

**Comment by Disane87** [comment]
The hint from @kamilmysliwiec was really good but my intention is to plugin pluginA while the application is running

**Comment by BrunnerLivio** [comment]
@Disane87  
> I guess I can load the modules from a given path like this?

Yes, that would work.

>  plugin pluginA while the application is running

This is not possible yet. What function do you use for that in Angular? `Compiler.compileModuleAndAllComponentsSync`?

**Comment by Disane87** [comment]
Oh no, its a mixture of SystemJS (for loading the module) and instantiating components with `viewContainerRef.createComponent`.

There is a good article about that (even with AOT)

https://blog.angularindepth.com/building-extensible-dynamic-pluggable-enterprise-application-with-angular-aed8979faba5
