### ISSUE TITLE
Middleware with Decorators

### ISSUE THREAD

**Issue by IRCraziestTaxi** [nestjs/nest#3285]
## Is your feature request related to a problem? Please describe.
Decorators make building projects easy and intuitive. The current way of configuring middleware is neither of those things.

## Describe the solution you'd like
I previously built APIs using [routing-controllers](https://github.com/typestack/routing-controllers) and one of the things I adored about that lib the most is being able to apply middleware to an entire controller or by controller method via decorators. I was certain Nest would apply middleware the same way and was very surprised to see that is not the case.

## What is the motivation / use case for changing the behavior?
Not only would decorator-based middleware make implementing middleware a lot easier and more intuitive, but as described in [this comment](https://github.com/nestjs/nest/issues/1800#issuecomment-497463254), the current way of configuring middleware can lead to problems with middleware being applied to the correct routes.

Yes, I am aware this feature request has already been shunned in [235](https://github.com/nestjs/nest/issues/235) and [1800](https://github.com/nestjs/nest/issues/1800), but I urge you to reconsider. The value gained by implementing decorator-based middleware would be great.

**Comment by kamilmysliwiec** [comment]
There is no plan to change this behavior. Middleware in Nest are applied to *paths*, not specific methods/classes. However, if you really want to apply them using decorators, you should rather use interceptors (it should be fairly simple to migrate any existing middleware to an interceptor).
