### ISSUE TITLE
【Suggest】Is it possible to change Components to providers？

### ISSUE THREAD

**Issue by jiayisheji** [nestjs/nest#329]
Components inside injection is service
The providers are just receiving services, which are more semantic and easier to accept

**Comment by FriOne** [comment]
@jiayisheji https://github.com/nestjs/nest/issues/254#issuecomment-345834627

**Comment by jiayisheji** [comment]
@FriOne 
I mean：

The current wording：
```ts
import { Module } from '@nestjs/common';
import { CatsController } from './cats.controller';
import { CatsService } from './cats.service';
import { SharedModule} from '../shared.module';
@Module({
    imports: [SharedModule],
    controllers: [CatsController],
    components: [CatsService],
    exports: [CatsService],
})
export class CatsModule {}
```

Improved wording：
```ts
import { Module } from '@nestjs/common';
import { CatsController } from './cats.controller';
import { CatsService } from './cats.service';
import { SharedModule} from '../shared.module';
@Module({
    imports: [SharedModule],
    controllers: [CatsController],
    providers: [CatsService],
    exports: [CatsService],
})
export class CatsModule {}
```
More in line with the semantic

Change `Components` to `providers`

**Comment by FriOne** [comment]
@jiayisheji sorry, i'm not the backer or the owner of the library.
What I meant is that nestjs design is ready. If there is a place for discussion then it is in the issues with tag `discussion`. @kamilmysliwiec, correct me if I'm wrong. Think this question should be in the issue template if so :)

**Comment by wbhob** [comment]
@FriOne it is in the issue template as "feature request".

**Comment by kamilmysliwiec** [comment]
Hi @jiayisheji,
That's not possible. It's explained in several issues already, I'd make the answer as a part of the docs as well.

**Comment by jiayisheji** [comment]
@kamilmysliwiec Ok, Thank you
