### ISSUE TITLE
Using decorator based middleware (workaround)

### ISSUE THREAD

**Issue by IRCraziestTaxi** [nestjs/nest#3296]
I discovered a workaround to the dismissed feature request for this functionality at [235](https://github.com/nestjs/nest/issues/235), [1800](https://github.com/nestjs/nest/issues/1800), and [3285](https://github.com/nestjs/nest/issues/3285).

Sorry to open a new issue (I'll close it after posting), but since those issues were immediately locked so I cannot comment on them, I wanted to make this workaround available for anybody wishing to use it.

Thought process: I have previously used [routing-controllers](https://github.com/typestack/routing-controllers) before trying out Nest and loved the super simple decorator based API structuring, including middleware.

Since routing-controllers is also (by default) based on Express, I figured I'd see if it could plug it in and make using its own middleware possible. It totally is!

Example middleware class:

```ts
import { Request, Response } from "express";
import { ExpressMiddlewareInterface, Middleware } from "routing-controllers";

@Middleware({
    type: "before"
})
export class TestMiddleware implements ExpressMiddlewareInterface {
    public async use(request: Request, response: Response, next: () => void): Promise<void> {
        console.log("Middleware works!");

        next();
    }
}
```

Controller action:

```ts
import { Body, Controller, Get, Post, Res } from "@nestjs/common";
import { Response } from "express";
import { UseBefore } from "routing-controllers";

// ...

@UseBefore(TestMiddleware)
@Get()
public async getAll(
    @Res()
    response: Response
): Promise<Response> {
    console.log("GET requested.");
    // ...
}
```

main.ts:

```ts
import { ValidationPipe } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";
import { useExpressServer } from "routing-controllers";
import { AppModule } from "./app.module";

async function bootstrap(): Promise<void> {
    const app = await NestFactory.create(AppModule);
    app.useGlobalPipes(new ValidationPipe({ transform: true }));

    // Enable routing-controllers to apply middleware to controllers and routes.
    useExpressServer(app);

    await app.listen(3000);
}

bootstrap();
```

That's all there is to it! Hopefully this will be of use to other folks wanting an easier way to apply middleware.

**Comment by kamilmysliwiec** [comment]
I would not recommend combining `routing-controllers` with Nest since it may create side-effects and lead to very tricky issues. This workaround shouldn't be used.
