### ISSUE TITLE
@nestjs/core 6.8.5 have some issues while updating npm

### ISSUE THREAD

**Issue by selvaprogrammer** [nestjs/nest#3298]
## Bug Report
Hi team, i have worked in nestjs last night i update my package it will update v6.0.0 to V6.8.5 
Then i run source it will throw "this.applicationRef.status is not a function" then i downgrade old version it will working fine is there any problem in @nestjs/core v6.8.5
## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, update other packages accordingly `@nestjs/platform-express` etc. (their versions have to match)

**Comment by selvaprogrammer** [comment]
Thanks @kamilmysliwiec noted that i was update common & core not platform-express i have update all package then it works good.Nice job man
