### ISSUE TITLE
Use built in FilesInterceptor will generate upload files twice.

### ISSUE THREAD

**Issue by yandan66** [nestjs/nest#3300]
## Current behavior
I use build in file upload middleware, and if I upload a file or files, while get the same file twice.
## Input Code

```ts
import { Controller, Post, UseInterceptors, UploadedFiles } from '@nestjs/common'
import { FilesInterceptor } from '@nestjs/platform-express'
import { UploadService } from './upload.services'

@Controller()
export class UploadController {
  constructor(private readonly uploadService: UploadService) { }
  @Post('upload')
  @UseInterceptors(FilesInterceptor('files'))
  uploadFile(@UploadedFiles() files) {
    console.log(files);
  }
}

```
The Input and Output there

![input](https://n1image.hjfile.cn/res7/2019/10/31/9ce899f3bd33f8e99a164107b55ae819.png)
![output](https://n1image.hjfile.cn/res7/2019/10/31/06bc7f873a601a8a52edd2952f55a69f.png)

## Environment
```
[System Information]
OS Version     : macOS Mojave
NodeJS Version : v10.15.3
NPM Version    : 6.9.0
[Nest Information]
platform-express version : 6.8.5
passport version         : 6.1.0
typeorm version          : 6.2.0
common version           : 6.8.5
```

 
For Tooling issues:
- Node version: v10.15.3
- Platform:   macOS Mojave

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by yandan66** [comment]
I had made a mistake. sorry.
