### ISSUE TITLE
A failed build using 'nest build' returns '0' instead of '1'

### ISSUE THREAD

**Issue by ClemannD** [nestjs/nest#3301]
## Bug Report
Currently, when doing a `nest build`, the return code is `0` (pass) even if it fails to build. This prevents us from doing build tests before merging PRs.

## Current behavior
To show what is happening, this command should only output 'passed' if nest build succeeds. But you can see it is failing to build but still printing 'passed'.

<img width="737" alt="Screen Shot 2019-10-31 at 9 33 47 AM" src="https://user-images.githubusercontent.com/17599322/67951542-1a996b00-fbc2-11e9-9fc7-a4144f69dab8.png">

## Expected behavior
A failed build should return `1`

## Environment

<pre><code>
Nest version: 6.10.5

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
I believe that we fixed this already. Have you updated to the latest version?

**Comment by ClemannD** [comment]
```
"@nestjs/cli": "^6.9.0",
"@nestjs/schematics": "^6.7.0",
"@nestjs/testing": "^6.7.1"
```

**Comment by ClemannD** [comment]
Solved by updating.

Thank you for the quick response @kamilmysliwiec
