### ISSUE TITLE
Add port to log output

### ISSUE THREAD

**Issue by marikaner** [nestjs/nest#3306]
## Feature Request
As this is just a minor issue and easy to understand, I will quickly describe my idea below:
This is a nice to have, but also a quick win: I just used nest for the very first time and created a project and followed the given instructions to start the app (`npm run start`). Then, I didn't know on which port the app would be running, because there was no information in the log on that and I didn't write the code of the scaffolding.
It's easy to look it up, but it might be more convenient to just have a link like http://localhost:3000 in the logs.

**Comment by BrunnerLivio** [comment]
Thanks to #3010 this could now be done. @kamilmysliwiec how about we add a `console.log` statement which prints the app url to the main.ts of the typescript-starter / cli app?

**Comment by kamilmysliwiec** [comment]
I like it @BrunnerLivio. PRs are more than welcome!

**Comment by Usama-Tahir** [comment]
status on this? I'd love to make a PR if no one has done this yet.

**Comment by kamilmysliwiec** [comment]
@Usama-Tahir PRs are welcome!
