### ISSUE TITLE
HttpException and NotFoundException have different output

### ISSUE THREAD

**Issue by rokerkony** [nestjs/nest#3308]
## Bug Report
There was already a similar bug reported in #1832 but the conversation is closed.

## Current behavior
- When I throw an error as `throw new Error('not in catch');`
    the `err.message` is: `not in catch`
- When I throw an error as `throw new HttpException('my message from HttpException', 404);`
    the `err.message` is: `my message from HttpException`
- When I throw an error as `throw new NotFoundException('my message from NotFoundException');`
    the `err.message` is:
    ```
    {
      statusCode: 404,
      error: 'Not Found',
      message: 'my message from NotFoundException'
    }
    ```

## Input Code
I test it with the following code:
```ts
// app.controller.ts
import {Controller, Get, HttpException, NotFoundException} from '@nestjs/common';

@Controller()
export class AppController {
  @Get()
  getHello(): void {
    const n: number = Math.random();
    if (n > 0.6) {
      throw new HttpException('my message from HttpException', 404);
    }

    if (n > 0.3 && n <= 0.6) {
      throw new Error('not in catch');
    }

    if (n <= 0.3) {
      throw new NotFoundException('my message from NotFoundException');
    }
  }
}

// http.filter.ts
import {Catch, ExceptionFilter} from '@nestjs/common';
import {ArgumentsHost} from '@nestjs/common/interfaces/features/arguments-host.interface';

@Catch()
export class HttpFilter implements ExceptionFilter {
    public catch(err: any, host: ArgumentsHost): any {
        console.log(err.message);

        return host.switchToHttp().getResponse();
    }
}

//main.ts
import {HttpFilter} from './http.filter';
app.useGlobalFilters(new HttpFilter());

```

## Expected behavior
Is it by design that `err.message` has a different output with `HttpException(msg, 404)` and `NotFoundException(msg)`? I would expect the same behavior.

It is problematic when you need to work with an error in the filters.

## Environment
<pre><code>
Nest version: 6.8.5
 
For Tooling issues:
- Node version: 12.12.0
- Platform: tested on mac & linux

**Comment by kamilmysliwiec** [comment]
This will be fixed in the next major release https://github.com/nestjs/nest/pull/3053
