### ISSUE TITLE
How can I get headers from websocket client using ws with guard, not socket.io?

### ISSUE THREAD

**Issue by AsyncLegs** [nestjs/nest#3312]
## Current behavior
Hey everybody.
Im experiencing problems with ws adapter in Guards context: inside Gateway's **handleConnection** I'm able to get client headers, but in the same time I can't get client headers inside the Guard - when I'm getting context from **context.switchToWs().getClient()**  - there are no headers

Is there some workaround for that?

## Input Code
https://github.com/AsyncLegs/ws-guard-issue

## Expected behavior
Client headers should be available in the execution context as they available in the socket.io variant

## Possible Solution
I guess, that the Request object should be passed to execution context somehow.

## Environment

<pre><code>
OS Version     : macOS Catalina
NodeJS Version : v10.16.3
YARN Version    : 1.19.1
[Nest Information]
platform-express version : 6.8.5
platform-ws version      : 6.8.5
websockets version       : 6.8.5
common version           : 6.8.5
core version             : 6.8.5
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by AsyncLegs** [comment]
@kamilmysliwiec  Thanks for the response.
I've investigated a bit deeper and realized that WS library doesn't pass the req object into on('message') event as second parameter, so possible workaround might be:
`  async afterInit(server: Server) {
    server.on('connection', (socket, request) => {
      socket['request'] = request;
    });
  }`
And after that request gets visible inside ExecutionContext.

#https://github.com/websockets/ws/issues/1658
