### ISSUE TITLE
Export createRpcParamDecorator

### ISSUE THREAD

**Issue by Mokto** [nestjs/nest#3318]
## Feature Request
It would be nice to be able to export rpcParamDecorator.

We are able to define our own param decorators for http requests. It would be awesome to be able to do the same for RPC microservices.

## What is the motivation / use case for changing the behavior?

For example, for RabbitMQ, everyone could define a decorator to get the content of every message.

**Comment by kamilmysliwiec** [comment]
You should be able to use `createParamDecorator` https://docs.nestjs.com/custom-decorators

Fixed in 6.9.0

**Comment by Mokto** [comment]
Works perfectly now, thanks !
