### ISSUE TITLE
gRPC: Metadata

### ISSUE THREAD

**Issue by Joshgallagher** [nestjs/nest#3324]
## Is your feature request related to a problem? Please describe.
I have looked through the docs and can't seem to find anything in detail regarding gRPC Metadata. Therefore, I am wondering if this is available and can be added to the docs?

## What is the motivation / use case for changing the behavior?
I want to leverage Metadata for errors, e.g. validation errors.

Currently, I am using `JSON.stringify()` to pass errors back in the `message` field within a `RpcException`.

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/docs.nestjs.com/issues/115
