### ISSUE TITLE
How to determinate if it is REST endpoint or GQL mutation inside AuthGuard

### ISSUE THREAD

**Issue by TrejGun** [nestjs/nest#3325]
Lets say I want to write a hybrid app which uses JWT token for authorization. So I have used passport jwt strategy and implemented custom AuthGuard which is used for both endpoints and mutations. It looks like this:

```js
@Injectable()
export class AuthGuard implements CanActivate {
  constructor(private readonly reflector: Reflector) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const ctx = GqlExecutionContext.create(context);
    const gqlCtx = ctx.getContext();
    if (gqlCtx) {
      // GQL logic
    }

    const req = context.switchToHttp().getRequest();
    // REST logic
  }
}
```

Is there a good way to determinate where this guard is used without creating GQL context each time?

**Comment by Kirzilla** [comment]
Have you thought about splitting REST/GraphQL auth guards?
`AuthGuardAbstract`, `AuthGuardRest`, `AuthGuardGraphql`

**Comment by TrejGun** [comment]
Yeah but I really like the fact I can use UseGuard with any of them

**Comment by jmcdo29** [comment]
One option would be to keep a constant naming convention, then you can tell what is being called via the reflector's `getClass()` method. That may inherently be available by the `ExecutionContext` actually. But this does completely rely on you to keep the naming convention and could be problematic if you change it

**Comment by TrejGun** [comment]
Thanks guys

also I found this
https://github.com/nestjs/nest/issues/1581
