### ISSUE TITLE
Get instance of dynamic modules and child modules

### ISSUE THREAD

**Issue by Disane87** [nestjs/nest#3329]
Hey guys, actually I've been a step further with my dynamic plugins (as described in https://github.com/nestjs/nest/issues/3307#issuecomment-549737331). Now I want to get an instance of my `PluginModule` to get the instances of all loaded plugins, because there are `functions` and `properties` which I need to read after loading, because they contain some metadata and other stuff (like seeding db objects etc.).

But if I want to get the instance of my `PluginModule` there is an exception:
> Error: Nest could not select the given module (it does not exist in current context)

I try to get the instance in the `main.ts` by (like stated in the docs at https://docs.nestjs.com/application-context):

```ts
const pluginModule: PluginModule = app.select(AppModule).select(PluginModule);
```

It's also not working with:
```ts
const pluginModule: PluginModule = app.select(PluginModule);
```

Am I missing something?

The module hierarchy:

- AppModule
-- PluginModule (wich loads the dynamic plugins)
--- PluginAModule
---- PluginBSubmodule
--- PluginBModule

**Comment by Disane87** [comment]
Got a hacky way to get this done. Because I'm in a static class while dynamic loading the module, I have to return all loaded plugins (with name and classes) with an injection token to use it within the application:

```ts
return {
				module: PluginModule,
				imports: [...this.pluginsArray.map(plugin => plugin.module)],
				providers: [
					PluginService,

					// Return an injection token which holds all loaded plugins to get them into the plugin module
					{
						provide: 'LOADED_PLUGINS',
						useValue: this.pluginsArray,
					},
				],
			} as DynamicModule;
```

In the `constructor` i inject the token and iterate them all and create instances of it to obtain the meta data from them:

```ts
constructor(@Inject('LOADED_PLUGINS') plugins: Plugin[], private pluginService: PluginService) {

		plugins.forEach((plugin: Plugin) => {
			const pluginModule = plugin.module as any;
			const module: PluginModuleConfig = new pluginModule();

			console.log(module.metadata);
		});
	}
```

Interfaces:
```ts
export interface PluginModuleConfig {
    metadata: PluginMetaData;
}

export interface PluginMetaData {
    name: string;
    author: string;
    version: string;
    description: string;
    repo: string;
    database?: object;
}

```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Disane87** [comment]
Sorry! I thought for bigger discussions github will be a more structured way of discussing this. With Discord you quickly run the risk of overlooking things or losing the red thread.
