### ISSUE TITLE
Client Mqtt dispatchEvent() returns entire packet instead of packet.data

### ISSUE THREAD

**Issue by sandeshgb** [nestjs/nest#3341]
## Current behavior
My current scenario is just a normal publish-subscribe application, in which I'm publishing a topic and subscribing to it. But the response I'm expecting is the message sent by me, but it also provides me with the topic name.
Expected output: {"a":56}
Actual output: {"pattern":"topic-name", "data":"{\"a\":56}"}

Also due to stringify() the additional escape characters in output.

## Input Code
Link: https://github.com/nestjs/nest/blob/40b486b0588f46ac390ae6739fe7bdd5ebcfb73a/packages/microservices/client/client-mqtt.ts#L156

const response = await this.client.emit(topic, message).toPromise(); // service I'm calling

protected dispatchEvent(packet: ReadPacket): Promise<any> {
    const pattern = this.normalizePattern(packet.pattern);
    const serializedPacket = this.serializer.serialize(packet);

    return new Promise((resolve, reject) =>
      this.mqttClient.publish(pattern, JSON.stringify(serializedPacket), err =>
        err ? reject(err) : resolve(),
      ),
    );
  }

## Expected behavior
Should return message (i.e packet.data) instead of entire packet (pattern + data).
Also if I need to pass an additional parameter to send(), can you assist me in this, because now it takes only two params.

## Possible Solution
dispatchEvent(packet) {
        const pattern = this.normalizePattern(packet.pattern);
        const serializedPacket = this.serializer.serialize(packet.data); // added data
        return new Promise((resolve, reject) => this.mqttClient.publish(pattern, serializedPacket, err => err ? reject(err) : resolve()));  // removed stringify
    }

## Environment
nestjs

<pre><code>
Nest version: 6.10.4

 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Ubuntu 16.04 LTS (64-bit)

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
