### ISSUE TITLE
Real world example for microservice

### ISSUE THREAD

**Issue by ardyfeb** [nestjs/nest#3342]
I very confusing about microservice, i cannot realizing that can be useful on my app.

My question:

- What is microservice used for ?
- Can microservice handle event similiar with event emitter on nodejs ?, when `ProductService` emit event `onProductCreated` then `NotificationService` will handle that event (send notification to user)
- Any example real word usage ?

i currently trying find package for nestjs to implement event based architecture, like on Laravel https://laravel.com/docs/5.7/events

i have e commerce backend, so when user checkout `CheckoutService` will handle that, then when checkout complete i need broadcast to other service like `NotificationService` and send push notification to user. Can microservice resolve my problem ?

**Comment by ardyfeb** [comment]
My real problem is, i use elasticsearch and redis, so when user create product then elasticsearch need index that product and cache with redis. currently i call redis / elasticsearch manually, with event based this step will be simple, product service emit event and other service will listen and do any task

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
