### ISSUE TITLE
How to properly do parameter validation?

### ISSUE THREAD

**Issue by HeavyStorm** [nestjs/nest#335]
What's the best way to validate "body" DTO's? I'm just worried by simple stuff such as making sure if all mandatory fields are defined and types are correct, for instance, if a field I declared to be a string is actually a string, etc.

For instance:

```
import { Get, Controller, Query, Param, Post, Body } from '@nestjs/common';

class MyType {
	name: string;
}

@Controller('example')
export class ExampleController {
	@Post() 
	createOne(@Body() item: MyType) {
		
	}
}
```

Will accept a payload such as: 
```
{
	"name": 123
}
```

...without complaining.

**Comment by pumano** [comment]
check out "class-validator" from cats example:
https://github.com/nestjs/nest/blob/master/examples/01-cats-app/src/cats/dto/create-cat.dto.ts
you just use annotations for your body model, then use ValidationPipe from that example:
https://github.com/nestjs/nest/blob/master/examples/01-cats-app/src/common/pipes/validation.pipe.ts

Then just use Validation pipe in controller (you can also find it in that example). It's amazingly easy and declarative way to do validation.

**Comment by kamilmysliwiec** [comment]
Hi @HeavyStorm,
Great explanation @pumano 🙂 Take a look at the docs to find more details: https://docs.nestjs.com/pipes. Pipes will fit your requirements.

**Comment by panuhorsmalahti** [comment]
How would one verify a body which is an array?

```
app.useGlobalPipes(new ValidationPipe());
```
```
export class CreateMeasurementDto {
    @IsString() readonly time: string;
```
```
    @Post()
    async measurements(@Req() request: Request, @Body() newMeasurements: CreateMeasurementDto[]) {
```

This doesn't seem to work (but works when `CreateMeasurementDto` is not an array.

**Comment by panuhorsmalahti** [comment]
Why? As far as I know JSON array is valid in HTTP POST and body content type `application/json`? Or are you saying it's a limitation of Nest.js validation?

**Comment by chanlito** [comment]
@panuhorsmalahti AFAIK you can create use an object and supply the array inside. Nest.js framework itself doesn't comes with validation, nest uses the validation pipe which is using class-validator library.

Honestly, I've never sent a req.body as an array.

**Comment by panuhorsmalahti** [comment]
I don't want to change my endpoint from `[]` to `{data: []; }`. Nest.js does come with some validation code, namely the ValidationPipe. Well, since it doesn't support validating arrays, I think this is an open feature request.

I could alternatively call class-validator manually in the controller, but I'd like to avoid that solution. I could also implement my own ValidationPipe, but it's better to get it fixed upstream.

**Comment by kamilmysliwiec** [comment]
It isn't Nest limitation, but a TypeScript one. We cannot reflect generic types.

**Comment by beeman** [comment]
The links to these examples have been updated:

> check out "class-validator" from cats example:
> /examples/01-cats-app/src/cats/dto/create-cat.dto.ts@master

https://github.com/nestjs/nest/blob/master/sample/01-cats-app/src/cats/dto/create-cat.dto.ts

> you just use annotations for your body model, then use ValidationPipe from that example:
> /examples/01-cats-app/src/common/pipes/validation.pipe.ts@master

https://github.com/nestjs/nest/blob/master/sample/01-cats-app/src/common/pipes/validation.pipe.ts

**Comment by kodayashi** [comment]
@panuhorsmalahti - What did you end up doing here? I have an endpoint that I'd like to POST an array to (body is array). Trying to validate using class-validator as well :)

**Comment by ekifox** [comment]
How to validate what all items is number in array (number[])

async getRates(@Body('ids') ids: number[]): Promise<any> {
