### ISSUE TITLE
Add `funding` to npm configuration

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#3351]
## Describe the solution you'd like
Add the `funding` option the package.json of the nestjs/* packages. Therefore a developer can run `npm fund` and see where you can donate to.
[Read more in this article](https://blog.opencollective.com/beyond-post-install/)

## Other
How should we handle the post-install message of OpenCollective? Since NPM now "supports" fundings, shall we keep it?

**Comment by kamilmysliwiec** [comment]
`funding` has been added as part of the latest release.
