### ISSUE TITLE
mongoose types

### ISSUE THREAD

**Issue by albes** [nestjs/nest#3352]
does @types/mongoose needs upgrade to be used with this nestjs example?

I get this error:

`interface Device
Interface 'Device' incorrectly extends interface 'Document'.
  Types of property 'model' are incompatible.
    Type 'string' is not assignable to type '<T extends Document>(name: string) => Model<T, {}>'.ts(2430)
Peek Problem
No quick fixes available`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
