### ISSUE TITLE
As I need to send email using nestjs I would like an official framework lib. I don't feel safe using third parties.

### ISSUE THREAD

**Issue by kusther** [nestjs/nest#3364]
## Feature Request
As I need to send email using nestjs I would like an official framework lib. I don't feel safe using third parties.

## Is your feature request related to a problem? Please describe.
I need to send emails in nestjs but the framework does not support this yet.

## Describe the solution you'd like
Create an official module for sending emails in nestjs.

**Comment by frct1** [comment]
Uhmmm
Why not a nodemailer
In case with nestjs module i think it is will be wrapper for one of most popular exist packages

**Comment by kamilmysliwiec** [comment]
You can use any existing Node.js mailer module - all of them will be compatible with NestJS
