### ISSUE TITLE
Very strange behavior Importing modules

### ISSUE THREAD

**Issue by Root-Control** [nestjs/nest#3371]
## Current behavior

I've created a module called Documents, and i imported in the appModule (Main)
This module have its own middlewares (documentByIdMiddleware, documentValidatorMiddleware)

The whole application have 3 middlewares, LoggerMiddleware, TokenMiddleware, TenantMiddleware

All middlewares are being called after the documentMiddleware.

But in this moment the global middleware are not being applied.

The most weird thig is when i change the imports order.

## Input Code

*NO FUNCTIONAL*
```ts
@Module({
    imports: [
        DatabaseModule,
        AuthModule,
        CategoriesModule,
        CompaniesModule,
        DocumentsModule,
        JobsModule,
        MessagesModule,      
        UsersModule,
        PlansModule,
        SubscriptionsModule,
        ArticlesModule,
    ],
    controllers: [
    ],
    providers: [
        AppGateway,
        GlobalVariables
    ]
})```
*FUNCTIONAL*
```ts
@Module({
    imports: [
        DatabaseModule,
        AuthModule,
        CategoriesModule,
        CompaniesModule,
        JobsModule,
        DocumentsModule,
        MessagesModule,      
        UsersModule,
        PlansModule,
        SubscriptionsModule,
        ArticlesModule,
    ],
    controllers: [
    ],
    providers: [
        AppGateway,
        GlobalVariables
    ]
})```

## Expected behavior
<!-- A clear and concise description of what you expected to happen (or code). -->
Middlewares working fine

## Possible Solution
Changing the index in the module declarations

Aditional Note: DocumentsModule is declared in the 5th Position (not working)
if i move to other position (6 or 2) works fine, so i'm pretty sure is not about dependency, because is not connecting with other undeclared modules. 

This is a random error, because was working fine the last 1-2 months, and failed suddenly
## Environment

<pre><code>
Nest version: 6.3.1
<!-- Check whether this is still an issue in the most recent Nest version -->
 
For Tooling issues:
- Node version: 10.16.0 
- Platform:  Windows
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by Root-Control** [comment]
https://github.com/Root-Control/test-modules

Steps:
1.- Rename the .dev.env file to .env
2.- Add the MONGODB_PORT  value to 27017
3.- Run npm install
4.- Npm run start

5.- Test the uris: 
       http://localhost:1337/api/articles (works)
       http://localhost:1337/api/moduleA (works)

6.- Verify the middlewares order (see the message "DO STUFF MIDDLEWARE------" <- This middleware should be executed after all middlewares, but is executing in the beggining for the api (moduleA)
Thank you in advance

clarifying the issue:
1.- All Routes is passing by main middlwares declared in the app.module
(loggerMiddleware, tokenMiddleware, tenantMiddleware), and after this, the routes is using their own middlwares (documentById, doStuffMiddleware), for the current repo, the moduleA is not respecting the order, and is calling the module middleware first instead the main middlewares.

**Comment by Root-Control** [comment]
@kamilmysliwiec the problem was in the middleware orders, i think this problem is because the parent middlewares (app.module) are loaded before the module middlewares (very strange), is solved using await.
```ts
export class ArticlesModule implements NestModule {
    constructor() {
        console.log('Applicants module loaded');
    }
    public async configure(consumer: MiddlewareConsumer) {
        await consumer.apply(ArticleValidatorMiddleware).forRoutes({ path: 'articles', method: RequestMethod.POST });
        await consumer.apply(ArticleByIdMiddleware).forRoutes({ path: 'articles/:articleId', method: RequestMethod.ALL });
        //  users id calling middleware for findById users before run another methods like "delete/update/read"
    }
}
```

**Comment by kamilmysliwiec** [comment]
That's the expected behavior. In the past, the middleware order was random. Now modules closer to the root module (or in the root module, e.g. app.module) should be applied first
