### ISSUE TITLE
Change tsconfig baseUrl 

### ISSUE THREAD

**Issue by SamKhachatryan** [nestjs/nest#3378]
### Hi there.

What if I want to change the `baseUrl ` on **tsconfig.json**

From `./`
To `./src`?

And use as **import/require** file path `*` in place of `src/*`.

It can't find the modules after the I change the `baseUrl` and throw errors.

### Thanks.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
