### ISSUE TITLE
Exporting Repository class in the Module

### ISSUE THREAD

**Issue by theseeker16** [nestjs/nest#3385]
Hi, I was wondering if exporting a Repository file in the module is a good practice, I'm making some unit testing for a module, I would like just to use the service and test indirectly the repository. But when I inject it into testingModule, it asks me about the repository file with following error: 

> Potential solutions:- If UserRepository is a provider, is it part of the current _RootTestModule?- If UserRepository is exported from a separate @Module, is that module imported within _RootTestModule? @Module({ imports: [ /* the Module containing UserRepository */ ] })

**Original user.spec.ts**

```

describe('usersService', () => {
  let usersService: UsersService;

  beforeAll(async () => {
    const module = await Test.createTestingModule({
      imports: [UsersModule],
      providers: [UsersService]
    }).compile();

    usersService = module.get<UsersService>(UsersService);

  });
});
```

I exported it from the module and the error was fixed. But I don't know if it the best way to do that

```
@Module({
  imports: [DatabaseModule],
  providers: [...userProvider, UsersService, UserRepository],
  exports: [UsersService, **UserRepository**],
  controllers: [UsersController],
})
export class UsersModule { }
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
