### ISSUE TITLE
Testing module - how to useGlobalPipes

### ISSUE THREAD

**Issue by bensiu** [nestjs/nest#3396]
## Is your feature request related to a problem? Please describe.
In testing Controller
I would like to add useGlobalPipes(.....) before compile to be able to use build-in Body validation in controller params

  ```
beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [SomeController],
      providers: [{
        provide: SomeService,
        useClass: SomeServiceMock,
      }],
    })
   .somewhereHere(.......)
   .compile();

    controller = module.get<SomeController>(SomeController);
    service = module.get<SomeService>(SomeService);
  });
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by cjancsar** [comment]
Because Discord sucks for having any sort of history of issues: https://stackoverflow.com/questions/59355841/how-to-apply-global-pipes-during-e2e-tests
