### ISSUE TITLE
Documentation about CRUD with MongoDb and MySQL

### ISSUE THREAD

**Issue by GulajavaMinistudio** [nestjs/nest#34]
Are there any clear docs about how to connect and run crud operation with database, i.e mongodb, mysql, or postgree?

**Comment by juandav** [comment]
Hi, @GulajavaMinistudio , you can see on next sample. https://github.com/cdiaz/nestjs-demo

**Comment by Mark-McCracken** [comment]
I have an example I've managed to hook up to MySQL, will try to post tomorrow evening

**Comment by zachgrayio** [comment]
@GulajavaMinistudio,

I've integrated TypeORM with Nest rather successfully which allows me to use pretty much any relational database I want in a Nest application.

Here's a link to the example repository: https://github.com/zachgrayio/nest-typeorm-example

**Comment by cojack** [comment]
@zachgrayio would be awesome if you would like to improve docs (pr) for a guide with TypeORM and Nest , as you have already done this and have knowledge about it.

**Comment by GulajavaMinistudio** [comment]
Any news about it ? and more docs about database integration in Nest ? so we can use and testing it in real project.

**Comment by zachgrayio** [comment]
I know this is a pretty hot topic right now, and I'll try do something more on it as soon as possible. 

I've made a few improvements to database components shown in the example above for use in internal projects, but haven't gotten that back into the example repo yet, and I'm not sure whether it's best to invest time in

a) updating the example
b) trying to work on some docs on a DIY integration
c) stand up a Nest TypeORM module people can get off of npm and start injecting into services.. this would require buy in from the nest guys though obviously

Any opinions?

**Comment by silvelo** [comment]
I am working in two repo with iridium for mongodb and nest, and it worked well.
[repo 1](https://github.com/silvelo/RetroNexus-server)
[repo2](https://github.com/AgoraBinaria/app-base)

**Comment by cdiaz** [comment]
This another example for [Nest/Iridium ](https://github.com/AngelMunoz/nest-iridium) by [@AngelMunoz](https://github.com/AngelMunoz)

**Comment by JulianBiermann** [comment]
In order to ease the use of mongoose in my projects I created a small helper lib for injecting mongoose models.

https://www.npmjs.com/package/nest-mongoose

**Comment by kamilmysliwiec** [comment]
Hi everyone
TypeORM - https://docs.nestjs.com/recipes/sql-typeorm
Mongoose - https://docs.nestjs.com/recipes/mongodb
Sequelize - https://docs.nestjs.com/recipes/sql-sequelize

**Comment by rynop** [comment]
Anyone have a TypeORM with an example of at least the C of CRUD? Currently only R is documented. Full CRUD example would be nice, but I think a Create example would show noobs like myself how to combine a DTO and Entity the CORRECT way in a POST endpoint.

**Comment by cvh23** [comment]
The RD of CRUD is not that hard, but a best practice for CU would be really helpful. It somehow unclear how to use Nest and TypeORM in real world scenarios.
@rynop Have you found something?

**Comment by rynop** [comment]
@cvh23 I have.  Under the gun on timeline right now, will contribute back an example when I get time.

In short I just use a `.dto` and a TyoeORM `entity` and then use `plainToClass` to transform the DTO to the entity class (this does not make sense for EVERY use case, but does for some).  Ex:

```
import { plainToClass } from 'class-transformer';
...
const user = plainToClass(User, createUserDto);
```

I let the DTO do the data validation that is sent to the endpoint (ex: validating the body POSTed to /users).

I know this is super brief and not sure if it is best practice. Really need a sample project to convey.  I will do my best to create one and contribute back when I get time.
