### ISSUE TITLE
Azure event grid trigger support, similar to @nestjs/azure-func-http

### ISSUE THREAD

**Issue by iangregsondev** [nestjs/nest#3421]
## Is your feature request related to a problem? Please describe.
I would love to use the new azure event grid for event sourcing. I have tested the azure-func-http and it works great but it requires that we use a callback via event grid which means the azure function needs to have a public url exposed.

It would be really nice to be able to only have a trigger for the azure event grid, which is supported in azure functions. (tried it via VS Code plugin etc but no way of hooking up nest right now as the azure-func-http needs to pass in a req)

Maybe then we could have a number of private (non-exposed) microservices behind azure functions, listening and being triggered by Azure event grid - events..

Some microservices do not need to expose their url because they only act upon events that they are listening to.

It would also be really nice if 1 microservice (in nest) could support 2 different triggers. I mean multiple triggers are already supported in azure.

But the possibility of a nest service listening for both event grid and also http triggers (already supported via azure-func-http)

That would mean that a service can wake up on a http request but also on a azure event grid trigger - that would be sweet :-)

Can I provide more info ?

**Comment by iangregsondev** [comment]
There is some code for node here https://docs.microsoft.com/en-us/javascript/api/overview/azure/eventgrid?view=azure-node-latest

**Comment by kamilmysliwiec** [comment]
We're working on this already (as a separate package).

**Comment by iangregsondev** [comment]
@kamilmysliwiec great. Is it publically available repo?

**Comment by kamilmysliwiec** [comment]
Not yet
