### ISSUE TITLE
Dynamic importing of modules (Not dynamic modules)

### ISSUE THREAD

**Issue by igortas** [nestjs/nest#3423]
I like to import dynamically one sub-module, from multiple sub-modules I have into root module folder, depending from some .ENV configuration value (similar to useFactory, but for modules).

src\
rootFolder (rootModule, etc..)
   folderA (service, sub-module, etc..)
   folderB (service, sub-module, etc..)

Folder A and B, use same interface. Actually they hold sip providers code logic, but makes interaction with some different 3rd party service.

I don't like to have service wrapper on root level, I only like to import the module from folderA or B, depending some .env value.

BR,

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
