### ISSUE TITLE
Dynamic modules needs a configuration with a identifier per module

### ISSUE THREAD

**Issue by dbatistat** [nestjs/nest#3427]
## Current behavior

We have a HttpModule with many different configurations, but this not working because Nestjs take the first instance with the first configuration. So we saw the implementation of [HttpModule](https://github.com/nestjs/nest/blob/master/packages/common/http/http.module.ts) from Nest, and we couldn't understand why if it worked to the framework and not to us. We saw that they used an HTTP_MODULE_ID, and we used a constant with the same data and everything worked correctly, but trying to change the name or even leave an empty name and still working. 

So, for some reason you need a module identifier with a different name, or a hash or uuid for each module you want to make dynamic. This happens when using useFactory.

We don't understand why you need this, even with an empty name provider. But it doesn't indicate anywhere in the documentation, so either it's a bug or it doesn't explain this in the documentation.

## Input Code

```ts
@Module({})
export class HttpModule {
  static configure(moduleConfig: ModuleConfig): DynamicModule {
    return {
      module: HttpModule,
      imports: [LoggingModule],
      providers: [
        {
          provide: HTTP_CONFIG,
          useFactory: moduleConfig.useFactory,
          inject: moduleConfig.inject || []
        },
        {
          provide: '',
          useValue: moduleConfig.name, // <------- NEED THIS TO WORK, or a uuid() or any random value 
        },
        HttpService
      ],
      exports: [HttpService]
    }
  }
}
```

## Possible Solution
Add to the documentation of Dynamic Modules this configuration

## Environment

<pre><code>
Nest version: 6.6.7

 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
This actually should not be required anymore. Please, provide a minimal repository which reproduces your issue.
