### ISSUE TITLE
When disable built-in logger, ExceptionHandler can't output by overrideed logger

### ISSUE THREAD

**Issue by zieglar** [nestjs/nest#3439]
## Current behavior

I've use thirdparty winston logger, and disable system built-in logger in application create param, but thirdparty logger can't output some error like `[ExceptionHandler] xxxScheduleService is not defined`, I checked [ExceptionHandler](https://github.com/nestjs/nest/blob/master/packages/core/errors/exception-handler.ts)  and [NestFactory](https://github.com/nestjs/nest/blob/master/packages/core/nest-factory.ts#L160-L164) code, found overrideed logger only work after create.

## Input Code

main.ts
```ts
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    fAdapt,
    { logger: false },
  );
  app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));
```

## Expected behavior

I want [NestFactory](https://github.com/nestjs/nest/blob/master/packages/core/nest-factory.ts#L160-L164) throw error can normal output even if built-in logger is disabled.

## Environment

<pre><code>
[NestFactory](https://github.com/nestjs/nest/blob/master/packages/core/nest-factory.ts#L160-L164) 
[Nest Information]
@nestjsx/crud-typeorm version : 4.2.0
platform-socket.io version    : 6.10.1
platform-fastify version      : 6.10.1
platform-express version      : 6.10.1
@nestjsx/crud version         : 4.2.0
serve-static version          : 1.0.1
websockets version            : 6.10.1
passport version              : 6.1.0
mongoose version              : 6.1.2
typeorm version               : 6.2.0
common version                : 6.10.1
core version                  : 6.10.1
jwt version                   : 6.1.1

 
For Tooling issues:
- Node version: 8.16.1
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/69497820-731e0880-0ee1-11ea-91cb-ad906426788f.png)

>  The only downside of this solution is that your first initialization messages won't be handled by your logger instance

https://docs.nestjs.com/techniques/logger
