### ISSUE TITLE
[Question] How to use the global modules which modules decorate with @Global()

### ISSUE THREAD

**Issue by sirius1024** [nestjs/nest#344]
I note that in Module's document we've a new decorator @Global().
If I set a module as Global, How do I use it in another module without import?

Here is the version informations:
```js
"@nestjs/common": "^4.5.6",
"@nestjs/core": "^4.5.7",
```

**Comment by myflowpl** [comment]
As I understand It has to be imported at least once somewhere in the app.

In my case, I have global ConfigModule with exported ConfigService.
I import it at the root AppModule along with all other modules: DbModule, LoggerModule, FormsModule.  Now I can just inject ConfigService in all my modules, without importing the ConfigModule everywere

**Comment by sirius1024** [comment]
@myflowpl Thanks for your sharing. But if I have to import the class(not interface) that I want to use,  why we use DI? why not just new className() and call its method with the instance?

**Comment by BruceHem** [comment]
@sirius1024 it's all about testing.

**Comment by kamilmysliwiec** [comment]
@sirius1024 it's nicely explained here https://angular.io/guide/dependency-injection#di-by-example
