### ISSUE TITLE
Unable to receive QoS 1 messages on mqtt after application restart

### ISSUE THREAD

**Issue by gpanainte** [nestjs/nest#3441]
## Current behavior

I have a micro-service configuration with a `clean` session parameter set to `false`. As such I was expecting to receive QoS 1 messages sent while application is offline, when the application comes online again, but didn't happen.

## Input Code

```ts
app.connectMicroservice({
      transport: Transport.MQTT, options: {
        url: configService.masterBrokerUrl,
        protocol: 'mqtt',
        username: configService.masterBrokerUsername,
        password: configService.masterBrokerPassword,
        clientId: configService.masterBrokerClientId,
        clean: false
      }
    });
```

## Expected behavior
According to the comments in mqtt-options.interface.d.ts when setting client to false, I should receive QoS 1 and 2 messages while offline.

```ts
    /**
     * true, set to false to receive QoS 1 and 2 messages while offline
     */
    clean?: boolean;
```

## Possible Solution
I think the problem has to do with the way nest [subscribes to the topics](https://github.com/nestjs/nest/blob/92cba726ab54820a70fc2e9e7ca8fa0f4c6e0b76/packages/microservices/server/server-mqtt.ts#L57). I have changed server-mqtt.js file in order to set QoS 1 level and everything works as expected. 
 
```ts
 bindEvents(mqttClient) {
        mqttClient.on(constants_1.MESSAGE_EVENT, this.getMessageHandler(mqttClient).bind(this));
        const registeredPatterns = [...this.messageHandlers.keys()];
        registeredPatterns.forEach(pattern => {
            const { isEventHandler } = this.messageHandlers.get(pattern);
            mqttClient.subscribe(isEventHandler ? pattern : this.getAckQueueName(pattern), { qos: 1 });
        });
    }
``` 

I think this also correlates with [MQTT js documentation](https://github.com/mqttjs/MQTT.js#mqttclientsubscribetopictopic-arraytopic-object-options-callback), where they mention 

> qos subscription level, default 0`

A better solution would be to be able to define QoS level when registering a `MessagePattern` or `EventPattern` 
For example 

```ts
@MessagePattern({topic: 'some/topic', qos: 1})
``` 

## Environment

<pre><code>
Nest version: 6.6.4

</code></pre>

**Comment by Nosfistis** [comment]
Better yet, I think that `emit()`  should provide more options on each specific client. MQTT publishes can have the `retain` flag on as well, which is particularly helpful for last known packet persistence.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/3073

**Comment by tiberiu89** [comment]
Is this fixed? I can't see relevant information in the tracked issue. I publish events from node-red with QoS 1, setup mosquitto for persistent sessions. If i stop and start the nestjs container, it doesn't receive any events sent while stopped.

```ts
 app.connectMicroservice<MicroserviceOptions>(
    {
      transport: Transport.MQTT,
      options: {
        clientId: 'workflow',
        url: `mqtt://${config.get('services.mosquitto')}`,
        protocolVersion: 5,
        clean: false
      },
    },
    {
      inheritAppConfig: true,
    },
  );
```

```ts
@EventPattern('/events/domain/test')
  receive(@Payload() payload: any, @Ctx() ctx: MqttContext) {
    const topic = ctx.getTopic();
    const cloudevent = MQTT.toEvent({
      body: payload,
      headers: {
        ...(ctx.getPacket().properties?.userProperties || {}),
        source: topic,
      },
    });

    console.log(`Received message on topic ${topic}: ${cloudevent}`);
  }
```
