### ISSUE TITLE
Documentation: Swagger Response has Extra Attribute: id

### ISSUE THREAD

**Issue by cjancsar** [nestjs/nest#3444]
## Current behavior
In the responses section of https://docs.nestjs.com/recipes/swagger it shows this class:

```
export class Cat {
  @ApiModelProperty()
  name: string;

  @ApiModelProperty()
  age: number;

  @ApiModelProperty()
  breed: string;
}
```

But the response shows:

```
{
    id: number,
    name: string,
    age: number,
    breed: string
}
```

## Expectation

Where does the `id` come from in the response? It is not defined on the model definition implicitly with `ApiModelProperty` decorator.

**Comment by kamilmysliwiec** [comment]
There has to be something wrong with your code. If you're still noticing this issue, please, provide a minimal repository and report this here https://github.com/nestjs/swagger/issues instead

**Comment by cjancsar** [comment]
@kamilmysliwiec this is not from my code, this is from the documentation as written (I am saying it looks wrong or there is something missing). There is a disparity between the `Cat` class definition example, and the swagger Model example on https://docs.nestjs.com/recipes/swagger page

Cat Class Definition:
![image](https://user-images.githubusercontent.com/51799534/69550153-84f6be80-0f68-11ea-8232-9e8172e96c83.png)

Swagger Model example:
![image](https://user-images.githubusercontent.com/51799534/69550034-50830280-0f68-11ea-9fb9-ea5399c73dc8.png)

The swagger model does not extend any base class, nor does it have an `id` field defined on it, but the example swagger model then shows an `id` attribute...
