### ISSUE TITLE
[Modules] Exported request-scoped providers don't propagate

### ISSUE THREAD

**Issue by ulrichb** [nestjs/nest#3446]
## Bug Report

Normally Nest's DI "propagates" the scope: When injecting e.g. a request-scoped service into `MyIntermediateService` then `MyIntermediateService` implicitly becomes request scoped.

**But:** This does not work when the request-scoped service is imported from another module.

## Current behavior

See the following full repro sample. When you GET `http://localhost:4001/My/Op` then `MyRequestService.method()` throws "_Cannot read property 'path' of undefined_" because `this.request` is `undefined` (instead of holding the 'express' request).

Note that:
* When registering `MyRequestService` directly within `ApplicationModule` it works as expected.
* Explicit setting `@Injectable({scope: Scope.REQUEST})` to `MyIntermediateService`  _workarounds_ the issue.

## Input Code

```ts
import express from "express";
import {NestFactory, REQUEST} from "@nestjs/core";
import {Controller, Get, Inject, Injectable, Module, Scope,} from '@nestjs/common';
import {ExpressAdapter} from "@nestjs/platform-express";

@Injectable({scope: Scope.REQUEST})
class MyRequestService {

    constructor(@Inject(REQUEST) private readonly request: express.Request) {
        console.log("MyRequestService c'tor");
    }

    method() {
        // FAILS because `MyIntermediateService` gets a wrong
        // (too early created) instance:
        console.log('within MyRequestService; path: ', this.request.path);
    }
}

// Explicit setting the scope workarounds the issue: @Injectable({scope: Scope.REQUEST})
export class MyIntermediateService {

    constructor(
        @Inject("MyRequestService") readonly myRequestService: MyRequestService,
    ) {
        console.log("MyIntermediateService c'tor");
    }

    method() { this.myRequestService.method(); }
}

@Controller("My")
export class MyController {

    constructor(
        // @Inject(MyRequestService) readonly myRequestScopeService: MyRequestService,
        @Inject(MyIntermediateService) readonly myIntermediateService:
            MyIntermediateService) {

        console.log("MyController c'tor");
    }

    @Get("Op")
    op() {
        // this works: this.myRequestScopeService.method();
        this.myIntermediateService.method();
        return {result: "x"};
    }
}

@Module({
    providers: [MyRequestService],
    exports: [MyRequestService],
})
export class InfraModule {}

@Module({
    imports: [
        InfraModule,
    ],
    providers: [
        // When moving `MyRequestService` here it works,
        MyIntermediateService,
    ],
    controllers: [MyController],
})
export class ApplicationModule {}

//

async function bootstrap() {
    const app = await NestFactory.create(ApplicationModule, new ExpressAdapter());

    const port = 4001;
    await app.listen(port);
    console.log(`listening on port ${port}`);
}

bootstrap();

```

## Expected behavior
No run-time error.

## Possible Solution
Also use the module-imported services in the "scope propagation" alorithm.

## Environment

<pre><code>
Nest version: 6.10.1

 
For Tooling issues:
- Node version: 13.1
- Platform:  Win

**Comment by kamilmysliwiec** [comment]
Can you please provide a minimal repository which reproduces your issue?

**Comment by ulrichb** [comment]
> Can you please provide a minimal repository which reproduces your issue?

=> https://github.com/ulrichb/IssueAttachments/tree/master/nest-repro-3446

**Comment by jmtelljohann** [comment]
I'm running into the same problem. It was introduced when I tried to upgrade from 6.8.5 to 6.9.0. I can't share my repository, but the summary of the issue is: I have a downstream service that is request scoped, if I don't make everything that injects that service request scoped as well, DI fails. Nest used to inherently make everything request scoped if it depended on a service that was request scoped and this seems to no longer be the case.

**Comment by ulrichb** [comment]
Okay, seems as the same issue, but to be sure what exactly do you mean with "DI fails" (what happens exactly)? And do you also use multiple modules like in the issue description?

**Comment by kamilmysliwiec** [comment]
Can you please test `@nestjs/core@6.10.2` :)?

**Comment by jmtelljohann** [comment]
@ulrichb when I try to inject the service that is request scoped into another service that is not explicitly tagged as request scoped, it is null. Each of the services is in its own module as described above.

**Comment by jmtelljohann** [comment]
@kamilmysliwiec the behavior is slightly different in 6.10.2. Now when I try to inject the request into a service, it is null unless that service and everything that depends on that service is request scoped.
@Inject(REQUEST) private readonly request: Request

**Comment by jmtelljohann** [comment]
After upgrading to 6.10.2, only one of my services that depends on something that is request scope has doesn't implicitly become request scope as well.

I can't figure out the pattern of why it's only this one service that I have to add request scope to now

**Comment by kamilmysliwiec** [comment]
Can you share your repo @jmtelljohann?

**Comment by jmtelljohann** [comment]
@kamilmysliwiec Unfortunately it's a private repo that my company will not let me share

**Comment by kamilmysliwiec** [comment]
Would you like to try creating a small repository that reproduces your problem? It should be enough to simply replicate the dependencies tree.

**Comment by jmtelljohann** [comment]
@kamilmysliwiec yeah I'll take a stab at it

**Comment by ulrichb** [comment]
> Can you please test `@nestjs/core@6.10.2` :)?

Works great. Many thanks!

**Comment by cjancsar** [comment]
Just starting using nest and ran into this issue... was tearing my hair out. `@nestjs/core@6.10.2` resolved the issue.
