### ISSUE TITLE
Unknown exceptions when returned do not have an "error" key, unlike all other nest error responses.

### ISSUE THREAD

**Issue by duro** [nestjs/nest#3454]
## Current behavior
When an error is thrown from a core express middleware (like body parser), the error is handled by the BaseExceptionFilter. The error response this sends has a different structure than the rest of the HTTP exception responses

Here is where that is thrown

https://github.com/nestjs/nest/blob/master/packages/core/exceptions/base-exception-filter.ts#L49-L52

## Expected behavior
Since all other errors from nest are thrown where "error" is a common key, and "message" is more of an optional field, it would make sense that these errors would follow that same structure.

## Possible Solution
Make the shape of these Unknown Exceptions also include an "error" key.

**Comment by galesky** [comment]
Hey @duro i've checked this snippet and also the classes involved in HttpError Handling.

You are right that the `error` property exists in all other Http Exceptions but the `UnknownError` one

I will tackle this issue tomorrow or the day after.

I want to take a little more time so to also check if there is a reason why the `body` of the "UnknownError" Exception is not an instance of `HttpException`  directly or through his own class as an extension of `HttpException`;

Perhaps @kamilmysliwiec can clarify

**Comment by saulotoledo** [comment]
Thanks for the redirect @kamilmysliwiec. I standardized the exceptions by using the `message` attribute in #4045, but let me know if you guys want me to also include the `error` attribute and I will update the PR.
