### ISSUE TITLE
CORS does not seem to activate

### ISSUE THREAD

**Issue by thedogcampaign** [nestjs/nest#3458]
## Current behavior

CORS simply does not work regardless of how I enable it.

1. `const app = await NestFactory.create(AppModule, { cors: true });`
2. `const app = await NestFactory.create(AppModule, { cors: {corsOptions} });`
3. `app.enableCors() ;`
4. `app.enableCors({corsOptions})`
5. `app.use(cors());`
6. 
```
app.enableCors({
    origin: "*",
    methods: "GET,HEAD,PUT,PATCH,POST,DELETE",
    allowedHeaders: ['Content-Type', 'Authorization'],
  });
```

HTTP OPTIONS requests just end up with a 404

This is during development and not production.

## Expected behavior
CORS should be enabled.

## Minimal reproduction of the problem with instructions

Create a new project and just attempt to enable CORS with previously mentioned methods above.
## Environment

<pre><code>
Nest version: 6.9.0

 
For Tooling issues:
- Node version: v10.16.3
- Platform:  Windows 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
GraphQL app/REST API?

**Comment by hershko765** [comment]
can you provide with the full main.ts file as is? i think it will be easier with full code
