### ISSUE TITLE
Possible issue with configuration docs

### ISSUE THREAD

**Issue by reggi** [nestjs/nest#3459]
I believe theres a bug in the documentation.

Here is the link to the page:
https://docs.nestjs.com/techniques/configuration

The issue is with this code block:
```ts
import { Injectable } from '@nestjs/common';
import { ConfigService } from './config/config.service';

@Injectable()
export class AppService {
  private isAuthEnabled: boolean;
  constructor(config: ConfigService) {
    // Please take note that this check is case sensitive!
    this.isAuthEnabled = config.get('IS_AUTH_ENABLED') === 'true';
  }
}
```

Shouldn't this be `constructor(@Inject() config: ConfigService)`?

**Comment by kamilmysliwiec** [comment]
> Shouldn't this be constructor(@Inject() config: ConfigService)?

Nope :)

**Comment by reggi** [comment]
Learning! Thx
