### ISSUE TITLE
looking for real examples 

### ISSUE THREAD

**Issue by tx4x** [nestjs/nest#346]
Hi,
Are there real world examples I can look at ? I am not an angular expert and I have a hard time to understand how to actually use that. The example folders and also the guide/docs only show some boilerplating but they don't contain code how to retrieve a module, controller or component or call methods on methods on them. 

Can somebody help ? 
thanks, 
nice work !

**Comment by tx4x** [comment]
ah, found something here: https://github.com/jakub-gawlas/example-app-nest-js

**Comment by tm-3** [comment]
https://github.com/adrien2p/nestjs-graphql

Another example for you...a little more complete in terms of how you'd set up for multiple environments.

**Comment by tx4x** [comment]
@tm-3 : great! thank a lot.

**Comment by tx4x** [comment]
@tm-3  sorry but the docs and source code has various problems when installing. could manage to fix the code but the docs point to files which don't exists. 

any idea how to find more real-world apps/examples ? thanks a million

**Comment by BruceHem** [comment]
@tx4x https://github.com/BruceHem/simple-todos

**Comment by fwoelffel** [comment]
@tx4x https://github.com/fwoelffel/nub-api

**Comment by EndyKaufman** [comment]
@tx4x https://github.com/EndyKaufman/nest-permissions-seed

**Comment by tx4x** [comment]
Thank you all! The 'nest-permission-seed' gave me enough insights how to use nest-js. 

Sorry for getting a little offtopic right now but I am wondering nest-js is still a good fit when it comes to adding a CLI interface to my objects since most of net-js seems rather building on HTTP.

Let's say I wanna use https://github.com/orbital-js/orbital together with 'blessed'  in order to add an additional ui, the CLI. Do you think it's possible to still end up with clean and readable code ? From what I see is that there is massive use of decorators, fulfilling some interface for HTTP, and swagger, and database stuff. I guess I need to add some more decorators for such a CLI interface. The mentioned nest-permission-seed project for instance has sometimes 5+ decorators for an object property/RPC method(POST,GET), exposing also permission attributes or HTTP status codes. That's totally neat but in reality I want to make it less implicit and also separate such interfaces, ie: there is some model and I actually want to add 'interfaces' like HTTP or CLI on demand; think of vlc.exe -add-ui:web, console,....

What do you think, might it be possible to such thing with nest-js without  getting off to much of the design target of nest-js? To me it seems obvious to have the controllers free of any interface implementations/properties in regard of HTTP internals and so forth. Well, I am just guessing here and I hope to get some comments from you :-) Thanks in advance !

**Comment by PierreTurnbull** [comment]
> @tx4x https://github.com/EndyKaufman/nest-permissions-seed

The only example that uses relations in depth. Thank's !

**Comment by kentloog** [comment]
Nest.js API [example](https://github.com/kentloog/nestjs-sequelize-typescript) where are implemented the following:
-   [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript) ORM with [PostgreSQL](https://www.postgresql.org/) (+migrations and seeders)
-   auth with [JWT](https://jwt.io/)
-   tests with [Jest](https://jestjs.io/)
-   docs with [Swagger](https://swagger.io/)

Repo: https://github.com/kentloog/nestjs-sequelize-typescript

**Comment by alonssro** [comment]
Do yo have examples for rabbitmq? please

**Comment by joe307bad** [comment]
[Here is a restful API in NestJS](https://github.com/joe307bad/points/tree/master/API.Points) that I have been working on for awhile with the following features:
* [MongoDB](https://www.mongodb.com/) for storage and [Mongoose](http://mongoosejs.com/) for object mapping
* [AccessControl](https://onury.io/accesscontrol/) for role base permissions and attribute based access control
* [Passport](http://www.passportjs.org/) and [JWT](https://jwt.io/) for token authentication

https://github.com/joe307bad/points/tree/master/API.Points

**Comment by marcus-sa** [comment]
Have a look at https://github.com/xmlking/ngx-starter-kit
