### ISSUE TITLE
The /views and /public folders do not appear in the /build folder usign hbs.

### ISSUE THREAD

**Issue by taksumaki** [nestjs/nest#3461]
I am trying to use .hbs templates in my nestjs project but the **/views** and **/ public** folders do not appear in the **/ build** folder.

Note: I am copying exactly the same code as our Nestjs doc about **MVC**.

**Comment by kamilmysliwiec** [comment]
See here https://docs.nestjs.com/cli/monorepo#assets

**Comment by taksumaki** [comment]
Can I do the same for the "start:dev" mode?
