### ISSUE TITLE
Dynamically Configured Reused Modules

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#3462]
## Potential Commit/PR that introduced the regression**

Looks like it was [this commit](https://github.com/nestjs/nest/commit/ed3da85252fef246c73b5bc120fb218018a5abf9) that introduced the problem. Something about how instead of a name then enitre metatype is now being passed to the hashing function.

## Describe the regression
After updating to 6.10.0 I was greeted with an error about `Error: Unknown object type "promise"` from `~/node_modules/object-hash/index.js:223:17`. After playing around the `module-token-factory` code, and doing some code spelunking, I found that if you pass the options `{ ignoreUnknown: true }` to the `hash` method, the server starts up as expected. This error means that I cannot use [this package](https://github.com/golevelup/nestjs/tree/master/packages/modules)(more about that in a moment)  along with creating a static method for easily configuring dynamic modules. 

## Input Code
[Here is a repository branch](https://github.com/jmcdo29/dynamic-module-test/tree/broken-config) (make sure you use the `broken-config` branch)that recreates the error. This uses a package created by @WonderPanda for reducing boilerplate for dynamic modules, but the functionality of the package is described in the README of the repository. The package also allows for dynamic modules to be configured in one place (like `AppModule`) and reused elsewhere without the need for passing the configuration again.

## Expected behavior/code
I expect the server able to start up without a problem.

## Possible Solution
As I mentioned before, it seems like [at this function](https://github.com/nestjs/nest/blob/master/packages/core/injector/module-token-factory.ts#L20) we can pass the option `{ ignoreUknown: true }` and the server starts up without a problem for me, however, I don't know if this will cause any more regressions.

## Environment
<pre><code>
Nest version: 6.9.0 -> 6.1.0

For Tooling issues:
- Node version: 12.7.0
- Platform: Linux Mint

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Can you please test `@nestjs/core@6.10.2` :)?

**Comment by jmcdo29** [comment]
That did it! No more error! Thank you for the quick turn around
