### ISSUE TITLE
WebSocketGateway returns "server internal error" when validation failed

### ISSUE THREAD

**Issue by Isahara86** [nestjs/nest#3476]
## Current behavior
When DTO validation failed "Internal server error" returned instead validation error.

## Input Code

```ts
  @UsePipes(new ValidationPipe())
  @SubscribeMessage('subscribe-transactions')
  subscribeTransactions(
    @MessageBody() subscription: SubscriptionDTO,
    @ConnectedSocket() client: Socket,
  ): void {
    ...
  }
```
response when validation failed
```json
{status: "error", message: "Internal server error"}
```

## Expected behavior
If validation failed I expect to see validation error as it works for @Controller

## Environment

<pre><code>
Nest version: 6.9.0
NodeJs version: 12.13.0
OS: MacOS Catalina 10.15.1

**Comment by kamilmysliwiec** [comment]
`ValidationPipe` throws `BadRequestException` by default (HTTP exception). You can change this using `exceptionFactory` option:

```typescript
new ValidationPipe({
   exceptionFactory: (errors) => new YourWsError(errors),
})
```

**Comment by Isahara86** [comment]
Maybe you should add this to documentation.
