### ISSUE TITLE
[Question] How to "remove" inherit decorator ?

### ISSUE THREAD

**Issue by miramo** [nestjs/nest#348]
There is an elegant way to "remove" inherit decorator like `@ApiModelProperty` in child class ?

I'm using [class-validator](https://github.com/typestack/class-validator) with [Nest](https://github.com/nestjs/nest) to validate my input data with some DTO class and [Nest's swagger module](https://github.com/nestjs/swagger) for the doc

I need to have a parent class with all fields optional and a child class with some mandatory fields.

So i have a `CreateAccountDto` wich inherit from `AccountDto`

The idea behind is to have different inputs DTO like `CreateAccountDto` and avoid repetition.

Actually i have : 
```typescript
export class AccountDto {
  @IsUUID('4')
  @IsOptional()
  @ApiModelProperty()
  readonly account_id: string;

  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  @IsEmail()
  @IsOptional()
  @ApiModelProperty()
  readonly email: string;

  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  @IsOptional()
  @ApiModelProperty()
  readonly password: string;
}
```
and
```typescript
export class CreateAccountDto extends AccountDto {
  @Equals(undefined)
  @RemoveApiModelProperty()
  readonly account_id: string;

  @RemoveIsOptional()
  readonly email: string;

  @RemoveIsOptional()
  readonly password: string;
}
```

```typescript
const removeApiPropertyDecorator = (metakey: string): PropertyDecorator => {
  return (target: object, propertyKey: string | symbol) => {
    const properties = Reflect.getMetadata(DECORATORS.API_MODEL_PROPERTIES_ARRAY, target) || [];

    Reflect.defineMetadata(DECORATORS.API_MODEL_PROPERTIES_ARRAY, _.without(properties, `:${propertyKey}`), target);
    Reflect.deleteMetadata(metakey, target, propertyKey);
  };
};
export const RemoveApiModelProperty = (): PropertyDecorator => {
  return removeApiPropertyDecorator(DECORATORS.API_MODEL_PROPERTIES);
};
```

My actual solution is to have a custom `@RemoveApiModelProperty` and `@RemoveIsOptional` decorator, but i'm not sure is the best way to accomplish my goal !?

**Comment by kamilmysliwiec** [comment]
Hi @miramo,
There's no way provided out-of-the-box to do that. Your solution seems to be fine.
