### ISSUE TITLE
VSCode Debugger killed after file changes

### ISSUE THREAD

**Issue by saachinsiva** [nestjs/nest#3480]
Hello

We recently migration two of our applications from pure Express framework to NestJS. We are trying to use the similar debug config for NestJS as shown below. Everything is working fine with the debugger like hitting the endpoint etc but as soon as we change any files, the debugger is killed and we need to manually start the debugger again which means it compiles all the files etc. Please advise.

```json
{
      "type": "node",
      "request": "launch",
      "name": "ECS-TS-NODE-DEV",
      "runtimeExecutable": "ts-node-dev",
      "cwd": "${workspaceFolder}/server",
      "args": [
        "--inspect",
        "--nolazy",
        "--no-notify",
        "--no-deps",
        "--debug",
        "--ignore",
        "${workspaceFolder}/server/node_modules",
        "-r",
        "${workspaceFolder}/server/node_modules/tsconfig-paths/register",
        "${workspaceFolder}/server/src/main.ts"
      ],
      "restart": true,
      "protocol": "inspector",
      "internalConsoleOptions": "openOnSessionStart",
      "console": "internalConsole",
      "port": 9229,
      "env": {
        "TS_NODE_FILES": "true"
      }
    }
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
