### ISSUE TITLE
Catch error on async functions

### ISSUE THREAD

**Issue by Mokto** [nestjs/nest#3484]
## Is your feature request related to a problem? Please describe.

Sometimes I want to trigger some async actions without using `await`. For example, in a API Rest route, when as signs up, I want to trigger an analytics event. But I don't want the end-user response time to be impacted by this analytics call. It works fine obviously, but if anything throws an error, it is caught by Nest and it's impossible (as far as I know) to catch it (to send it to Sentry for example).

## Describe the solution you'd like

Have something like `app.onUnhandledException((error: Error) => ...)`

Thanks very much !

**Comment by kamilmysliwiec** [comment]
Nest doesn't catch any error thrown asynchronously. If you want to listen to unhandled rejections, you can use `process.on('unhandledRejection')`

**Comment by Mokto** [comment]
Thanks ! I don't know why I didn't see that from the beginning.

Side note : the event is `uncaughtException`, not `unhandledRejection`.
