### ISSUE TITLE
Not work controllers response

### ISSUE THREAD

**Issue by EndyKaufman** [nestjs/nest#349]
Based on starter template 
https://github.com/EndyKaufman/new-nestjs
https://new-nestjs.herokuapp.com/

My sample todo application
https://github.com/EndyKaufman/nest-permissions-seed
https://nest-permissions-seed.herokuapp.com/

If revert to prev version, it work OK
https://github.com/EndyKaufman/nest-permissions-seed/commit/10b990ff5a8c9bbcda7697c29adea62cc21b502d?diff=unified

**Comment by kamilmysliwiec** [comment]
Hi @EndyKaufman,
Please update your version into `4.5.9`

**Comment by EndyKaufman** [comment]
Everything works, thank you!
