### ISSUE TITLE
How to access service(inject with Request) in Interceptors 

### ISSUE THREAD

**Issue by Zaynex** [nestjs/nest#3496]
Hi, I have a question:
How to access servier(inject with Request) in Interceptors?

My service:
It's ok when I use it in other controller or service.
```
@Injectable()
export class MyLogger implements LoggerService {
  constructor(
    @Inject('winston') private readonly logger: WinstonLog,
    @Inject(REQUEST) private readonly reqeust: Request,
  ) {}

  log(message: string, context?: string) {
    return this.logger.info(message, { context });
  }

  info(message: string, context?: string) {
    return this.logger.info(message, { context });
  }
}
```

But I can't access in interceptors
```
export class LogginInterceptor implements NestInterceptor {
  constructor(
    private readonly logger: MyLogger,
  ) {}

  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    // this.logger will be undefined
    this.logger.info('[LogginInterceptor]: Request Handle Start...');
    //....
}
```

```
this.logger will be undefined
```
Why I can't use it in interceptor ?
It's because I use `Request` in service ?

I don't know how it work internal, anyone can explain this ? And how I can access `this.logger` ?Thanks.

I find some issue like this, but it's hard to solve. https://github.com/nestjs/nest/issues/1916#issuecomment-491481384

**Comment by kamilmysliwiec** [comment]
Can you please provide a minimal repository which reproduces your issue?

**Comment by Zaynex** [comment]
@kamilmysliwiec see the demo https://github.com/Zaynex/nestjs-error-demo  .Thanks.

**Comment by kamilmysliwiec** [comment]
If you use custom providers syntax, you need to define `scope` property:

```typescript
{
      provide: APP_INTERCEPTOR,
      scope: Scope.REQUEST,
      useClass: LoggingInterceptor,
},
```

https://docs.nestjs.com/fundamentals/injection-scopes#usage

**Comment by Zaynex** [comment]
@kamilmysliwiec  thanks. After set scope property. It works.
I read the docs about Performance.
I am sorry I still can't understand that
I don't know whether this way will effect performance or not?
Can you explain it ? I to know in depth.

**Comment by kamilmysliwiec** [comment]
It will slightly affect application performance. Example:

Singleton controller:
- 100 requests = 1 instance (one `new YourControllerClass()`)

Request-scoped controller:
- 100 requests = 100 instances (100x `new YourControllerClass()`)
