### ISSUE TITLE
Nest can't resolve dependencies of the CatsController

### ISSUE THREAD

**Issue by EmiyaYang** [nestjs/nest#3499]
## Bug Report

>Nest can't resolve dependencies of the CatsController (?). Please make sure that the argument CatsService at index [0] is available in the _RootTestModule context.
Potential solutions:
    - If CatsService is a provider, is it part of the current _RootTestModule?
    - If CatsService is exported from a separate @Module, is that module imported within _RootTestModule?
      @Module({
        imports: [ /* the Module containing CatsService */ ]
      })

## Current behavior

```bash
$ npm i -g @nestjs/cli
$ nest new project-name
$ npm install
$ nest g controller cats
$ nest g service cats
$ npm run test
```

## Input Code

```
src
├── cats
├──├──cats.service.ts
├──├──cats.controller.ts
├──├──cats.controller.spec.ts
├── app.module.ts      
└── main.ts  
```

```ts
// app.module.ts
import { Module } from '@nestjs/common';
import { CatsController } from './cats/cats.controller';
import { CatsService } from './cats/cats.service';

@Module({
  imports: [],
  controllers: [CatsController],
  providers: [CatsService],
})
export class AppModule {}
```

```ts
// cats.controller.ts
import { Controller, Get } from '@nestjs/common';
import { CatsService } from './cats.service';

@Controller('cats')
export class CatsController {
  constructor(private readonly service: CatsService) {}

  @Get()
  findAll() {
    return this.service.findAll();
  }
}
```

```ts
// cats.service.ts
import { Injectable } from '@nestjs/common';
import { Cat } from './interfaces/cat.interface';

@Injectable()
export class CatsService {
  private readonly cats: Cat[] = [];

  create(cat: Cat) {
    this.cats.push(cat);
  }

  findAll(): Cat[] {
    return this.cats;
  }
}
```

```ts
// cats.controller.spec.ts
import { Test, TestingModule } from '@nestjs/testing';
import { CatsController } from './cats.controller';

describe('Cats Controller', () => {
  let controller: CatsController;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [CatsController],
    }).compile();

    controller = module.get<CatsController>(CatsController);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });
});

```

## Expected behavior

Pass the test.

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version: v12.13.0
- Platform:  Mac

</code></pre>

**Comment by EmiyaYang** [comment]
Just followed the tutorial and met this error in the test. As a total beginner, I don't know how to fix it with the potential solutions.

**Comment by kamilmysliwiec** [comment]
Add `CatsService` to `providers` in your `cats.controller.spec.ts` file. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
