### ISSUE TITLE
Re: Documentation: Swagger Response has Extra Attribute: id

### ISSUE THREAD

**Issue by cjancsar** [nestjs/nest#3503]
This was closed with out actual understanding of the issue: https://github.com/nestjs/nest/issues/3444

To re-iterate, the current swagger recipe documentation has a potential bug in it. Excerpt from the issue above:

> @kamilmysliwiec this is not from my code, this is from the documentation as written (I am saying it looks wrong or there is something missing). There is a disparity between the `Cat` class definition example, and the swagger Model example on https://docs.nestjs.com/recipes/swagger page

**Cat Class Definition**:
![image](https://user-images.githubusercontent.com/51799534/69550153-84f6be80-0f68-11ea-8232-9e8172e96c83.png)

**Swagger Model example:**
![image](https://user-images.githubusercontent.com/51799534/69550034-50830280-0f68-11ea-9fb9-ea5399c73dc8.png)

The `Cat` class does not extend any base class, nor does it have an `id` field defined on it, but the example rendered swagger model then shows an `id` attribute...

**Comment by kamilmysliwiec** [comment]
This will be fixed in this PR https://github.com/nestjs/docs.nestjs.com/pull/825

Thanks for the clarification
