### ISSUE TITLE
Unexpected error when updating nestjs/core to the latest version

### ISSUE THREAD

**Issue by nartc** [nestjs/nest#3505]
## Describe the regression

I have a library that lists nestjs/core as devDependencies. Upon updating nestjs/core to the latest version, my travis ci build errored out

![340D90FA-7839-4C22-980C-6302C4333340](https://user-images.githubusercontent.com/25516557/69879944-57728380-128e-11ea-94f4-cde4d5b7027e.png)

## Input Code

I believe this is a typing issue.

Here's the issue on my library github: https://github.com/nestjsx/automapper/issues/13

## Environment
<pre><code>
Nest version: 6.10.2 -> 6.10.3

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 6.10.4
