### ISSUE TITLE
The official website can provide API documentation, you can view/search API list

### ISSUE THREAD

**Issue by zhuSass** [nestjs/nest#3507]
## The official website can provide API documentation, you can view/search API list
The existing official documentation is more of a general tutorial, but it is expected to provide an API search function, which I think would be very popular. Please refer to React Native, which provides a tutorial, as well as an API for viewing and searching

**Comment by kamilmysliwiec** [comment]
We are tracking this here https://github.com/nestjs/docs.nestjs.com/pull/413
