### ISSUE TITLE
Websocket - send to single client

### ISSUE THREAD

**Issue by jchapelle** [nestjs/nest#3508]
I can't get the websocket server to send to a single clients. All the example found on the internet emit message to all the connected client. In a chat app, that's not the use case ... In a chat app you only send a message to a set of 2 clients. I can't get it to work properly. Can you help ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
