### ISSUE TITLE
tsconfig.json ignores exclude option when developing

### ISSUE THREAD

**Issue by rokelvisar** [nestjs/nest#3510]
## Current behavior
tsconfig.json has option to exclude watching files/folders, but it does not work because this option is only applied to files being watched by include property.

## Input Code

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "dist"]
}
```

## Expected behavior
All paths under exclude should not trigger app restart.

## Possible Solution
Add "include": ["src"]

## Environment

<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: v10.16.3
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
