### ISSUE TITLE
OnApplicationBootstrap fires prematurely

### ISSUE THREAD

**Issue by whitebyte** [nestjs/nest#3516]
## Current behavior
`OnApplicationBootstrap` fires before the bootstrap actually completed

## Input Code
main-loop.service.ts
```ts
...
@Injectable()
export class MainLoopService {
    public async onApplicationBootstrap(): Promise<void> {
        console.log("This shouldn't happen");
    }
}
```

When I start the app, logs appear in the following order:
```
Starting Nest application..
This shouldn't happen
Nest application successfully started
```

## Expected behavior
`OnApplicationBootstrap`  should be called when the bootstrap actually finished

## Environment
nodejs 10.17.0

<pre><code>
Nest version: 6.10.4
 
For Tooling issues:
- Node version: nodejs 10.16.3
- Platform:  Windows WSL

**Comment by whitebyte** [comment]
FWIW the appllication itself appears to be working correct, so maybe it's just wrong log order?

**Comment by kamilmysliwiec** [comment]
> Nest application successfully started

This log ^ appears once each `onApplicationBootstrap` hook has been evaluated

**Comment by whitebyte** [comment]
I still don't understand.
https://docs.nestjs.com/fundamentals/lifecycle-events

> OnApplicationBootstrap Called once the application has fully started and is bootstrapped

This is not what happens in practice. According to the docs onApplicationBootstrap should start _after_ `Nest application successfully started`

**Comment by kamilmysliwiec** [comment]
This is just a log that indicates that all `onApplicationBootstrap` has been successfully called.
