### ISSUE TITLE
Suggestions on improvement of Chinese docs

### ISSUE THREAD

**Issue by ZhenHe17** [nestjs/nest#3518]
## Is your feature request related to a problem? Please describe.
I'm a Chinese developer and I can hardly understand [nest Chinese docs](https://docs.nestjs.cn/6/firststeps) , because it seems most parts of the docs are translated by computer.

## Describe the solution you'd like
 Improve Chinese docs

## What is the motivation / use case for changing the behavior?

Make Chinese docs better

**Comment by wxs77577** [comment]
@ZhenHe17 for chinese video courses, please check https://www.bilibili.com/video/av73070499

**Comment by kamilmysliwiec** [comment]
Chinese documentation is maintained by the community here https://github.com/nestcn/docs.nestjs.cn

**Comment by ZhenHe17** [comment]
> @ZhenHe17 for chinese video courses, please check https://www.bilibili.com/video/av73070499

谢了，视频有点浅，还是希望官方能完善中文文档
