### ISSUE TITLE
Global Module's provider instantiated twice?

### ISSUE THREAD

**Issue by StevenLangbroek** [nestjs/nest#3519]
## Current behavior

I have a `CommonModule`, which imports a `PostgresConnector` (based on `@databases/pg`. I've marked the module as `@Global()`. The module is used in both a root `APIModule` (which we use for GraphQL) and `KafkaModule`, which is used for consuming Kafka messages. I had expected the `PostgresConnector` to be instantiated once, but I see a console warning me that the database object is created twice.

## Input Code

CommonModule:
```ts
@Global()
@Module({
  providers: [PostgresConnector, {
    provide: ENV,
    useValue: env
  }],
  exports: [PostgresConnector]
})
export class CommonModule {}
```

APIModule:
```ts
@Module({
  imports: [
    GraphQLModule.forRoot({
      autoSchemaFile: 'schema.graphql',
      playground: true
    }),
    ReservationsModule,
    CommonModule
  ],
  providers: [RootResolver, ReservationsResolver]
})
export class APIModule {}
```

KafkaModule:
```ts
@Module({
  imports: [MerchantsModule, CommonModule, ReservationsModule],
  controllers: [],
  providers: []
})
export class KafkaModule {}
```

Warning:
```bash
WARNING: Creating a duplicate database object for the same connection.
    at Function.createConnection [as default] (/Users/stevenlangbroek/Code/portal-bff/node_modules/@databases/pg/lib/index.js:366:24)
    at PostgresConnector.onModuleInit (/Users/stevenlangbroek/Code/portal-bff/dist/common/postgres.connector.js:22:31)
    at MapIterator.iterare_1.default.filter.filter.map [as iteratee] (/Users/stevenlangbroek/Code/portal-bff/node_modules/@nestjs/core/hooks/on-module-init.hook.js:21:43)
    at MapIterator.next (/Users/stevenlangbroek/Code/portal-bff/node_modules/iterare/lib/map.js:13:39)
    at IteratorWithOperators.next (/Users/stevenlangbroek/Code/portal-bff/node_modules/iterare/lib/iterate.js:21:28)
```

## Expected behavior

I had expected it to be instantiated once, but I realize this might be a misunderstanding on my side.

## Environment

N/A

**Comment by kamilmysliwiec** [comment]
> Global modules should be registered only once, generally by the root or core module. In the above example, the CatsService provider will be ubiquitous, and modules that wish to inject the service will not need to import the CatsModule in their imports array.

https://docs.nestjs.com/modules#global-modules

**Comment by StevenLangbroek** [comment]
@kamilmysliwiec my `CommonModule` is global, as you can see in `CommonModule` snippet above...

**Comment by StevenLangbroek** [comment]
If I remove it from my `imports` statements in my root modules, I get this error:

```
Nest can't resolve dependencies of the MerchantsRepository (?). Please make sure that the argument PostgresConnector at index [0] is available in the MerchantsModule context.

Potential solutions:
- If PostgresConnector is a provider, is it part of the current MerchantsModule?
- If PostgresConnector is exported from a separate @Module, is that module imported within MerchantsModule?
  @Module({
    imports: [ /* the Module containing PostgresConnector */ ]
  })
```

**Comment by kamilmysliwiec** [comment]
Global modules should be **registered only once**. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by StevenLangbroek** [comment]
I understand, I just wasn't sure whether this was a bug or a misunderstanding.

**Comment by StevenLangbroek** [comment]
Did you see that I'm creating both a `MicroService` and an `Application` and trying to share this module between the two?

**Comment by StevenLangbroek** [comment]
I honestly cannot get this to work without running into an error, it seems like a bug to me. If I don't import the module into both root modules, the Repository class that uses it (which I need in both applications) fails to resolve it's `PostgresConnector` dependency.

**Comment by StevenLangbroek** [comment]
The error message also doesn't address `@Global()` modules:

```
Potential solutions:
- If PostgresConnector is a provider, is it part of the current ReservationsModule?
- If PostgresConnector is exported from a separate @Module, is that module imported within ReservationsModule?
  @Module({
    imports: [ /* the Module containing PostgresConnector */ ]
  })
```

**Comment by kamilmysliwiec** [comment]
It's impossible to share any module between 2 simultaneously running applications

**Comment by StevenLangbroek** [comment]
Ok, I'll submit a warning to the global module docs. Is there a way to create my connection manually and pass it in as injectable? I'd gladly contribute that back too.

**Comment by StevenLangbroek** [comment]
And can `connectMicroService` help here perhaps?

**Comment by StevenLangbroek** [comment]
I'm curious, should I turn this into a feature request? Is there a pattern for this I can document (sharing a db connection between applications)? Moving this out of Nest's infra makes my application less testable, which I'd like to prevent.

**Comment by StevenLangbroek** [comment]
@kamilmysliwiec would love some guidance wrt what to do with this. Thanks <3

**Comment by cKhoff** [comment]
do you have tried to bootstrap your nest application and nest microservice as hybridapp ?
https://docs.nestjs.com/faq/hybrid-application

**Comment by StevenLangbroek** [comment]
@cKhoff I did, didn't work either.

**Comment by StevenLangbroek** [comment]
You don't think this is a use-case worth addressing as you're adding more environments to run nestjs ini @kamilmysliwiec?
