### ISSUE TITLE
Redis adapter requires close() to avoid Jest from stalling

### ISSUE THREAD

**Issue by DaGaMs** [nestjs/nest#3523]
## Bug Report
I implemented a websocket server following the current documentation. Everything works fine, until I tried to move to the redis adapter as described [here](https://docs.nestjs.com/websockets/adapter). After that, I got the `Jest did not exit one second after the test run has completed` error in my tests, as descibed in #1538 

## Possible Solution
The sample code for the redis adapter in the documentation should be amended with this:

```
  close(server: any): void {
    this.redisAdapter.pubClient.quit();
    this.redisAdapter.subClient.quit();
    super.close(server);
  }
```

I realised that the adapter-internal clients were not being closed, causing the hanging tests. With this modification, Jest is now happy.

**Comment by kamilmysliwiec** [comment]
> I realised that the adapter-internal clients were not being closed

If you use any external resources that should be disposed, you have to call `await app.close()` method in either `after` or `afterEach` depending on your test suite. This will close the redis adapter clients automatically.

**Comment by DaGaMs** [comment]
🤦‍♂️ ok, so the issue was simply that the default test harness does not does not have an `afterEach` clause in which to close the app. Could I suggest to add this? Currently, out of the box, you get:

```typescript
import { Test, TestingModule } from '@nestjs/testing';
import * as request from 'supertest';
import { AppModule } from './../src/app.module';

describe('AppController (e2e)', () => {
  let app;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  it('/ (GET)', () => {
    return request(app.getHttpServer())
      .get('/')
      .expect(200)
      .expect('Hello World!');
  });
});
```

How about instead:

```typescript
import { Test, TestingModule } from '@nestjs/testing';
import * as request from 'supertest';
import { AppModule } from './../src/app.module';

describe('AppController (e2e)', () => {
  let app;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });
  // Simple addition to ensure app is closed correctly after each test, 
  // leaving no dangling connections open
  afterEach(async () => {
    await app.close();
  });
  
  it('/ (GET)', () => {
    return request(app.getHttpServer())
      .get('/')
      .expect(200)
      .expect('Hello World!');
  });
});
```

**Comment by kamilmysliwiec** [comment]
Looks good @DaGaMs! PRs are welcome
