### ISSUE TITLE
can i use WebSockets like express-ws?

### ISSUE THREAD

**Issue by getixin** [nestjs/nest#3524]
i don't use {"event":"xxx", "data": "xxxx"} this format, i just send some string to server, how can i do?
express-ws like this:
`app.ws('/echo', function(ws, req) {
  ws.on('message', function(msg) {
    ws.send(msg);
  });
});`

**Comment by kamilmysliwiec** [comment]
You can either use WebSocket client directly instead of using Gateways (which is totally fine) or write your own Adapter (see docs)

**Comment by lizardruss** [comment]
@getixin @kamilmysliwiec I wrote a [nest adapter for express-ws](https://github.com/lizardruss/platform-express-ws). I haven't put together a readme for it yet, but the [tests](https://github.com/lizardruss/platform-express-ws/blob/master/e2e/express-ws.gateway.spec.ts) should be a good starting point
