### ISSUE TITLE
Problem with sending data to microservice

### ISSUE THREAD

**Issue by VladimirMikhaylov** [nestjs/nest#3527]
```js
accumulate(): Observable<number> {
  const pattern = { cmd: 'sum' };
  const payload = [1, 2, 3];
  return this.client.send<number>(pattern, payload);
}
```
If i want to call function which contain send method without return, it return as fulfilled promise but in microservice we donty have any manipulation with our data (looks like microservice didn's recive anything). If we call function contain return this.client.send.. without return we have the same. How can a call send without return?

**Comment by kamilmysliwiec** [comment]
> he send() method takes two arguments, pattern and payload. The pattern should match the one defined in a @MessagePattern() decorator. The payload is a message that we want to transmit to the remote microservice. This method returns a cold Observable, which means that you have to explicitly subscribe to it before the message will be sent.

Especially this part:

> which means that you have to explicitly subscribe to it before the message will be sent.

You have to either call `.subscribe()` or transform a cold observable to a hot one. 
https://docs.nestjs.com/microservices/basics#sending-messages

If you return, NestJS automatically subscribes to your stream and that's why your message is being delivered.
