### ISSUE TITLE
Migrate tslint to eslint

### ISSUE THREAD

**Issue by quadgod** [nestjs/nest#3534]
## Feature Request

Migrate tslint to eslint

## Describe the solution you'd like

I would suggest to use a next configuration (just example)

```javascript
// .eslintrc
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "rules": {
    "no-unused-expressions": ["error"],
    "@typescript-eslint/member-ordering": ["off"],
    "@typescript-eslint/interface-name-prefix": ["off"],
    "@typescript-eslint/explicit-member-accessibility": ["off"],
    "@typescript-eslint/quotes": ["error", "single", "avoid-escape"]
  },
  "extends": ["plugin:@typescript-eslint/recommended"]
}
```

Good to have it in nest-cli

## What is the motivation / use case for changing the behavior?

![image](https://user-images.githubusercontent.com/3990608/70043901-9b80c380-15c1-11ea-8f36-8b4cb020b637.png)
https://github.com/palantir/tslint

tslint is no longer supported is somebody working on tslint -> eslint migration?

**Comment by kamilmysliwiec** [comment]
Tracking here https://github.com/nestjs/typescript-starter/issues/69
