### ISSUE TITLE
Make it possible to log command in microservice interceptor

### ISSUE THREAD

**Issue by BorntraegerMarc** [nestjs/nest#3535]
## Is your feature request related to a problem? Please describe.

I've seen [some answers](https://stackoverflow.com/questions/55093055/logging-request-response-in-nest-js) where people explain how to setup a global logger in a `NestApplication`. I would like to achieve the same thing in a `NestMicroservice`: To log which message pattern was requested from the microservice.

## Describe the solution you'd like

As an example let's say we have the following controller:

```typescript
@Controller('/auth')
export class AuthController {
    @MessagePattern({ cmd: '/login' })
    async login(auth: AuthDto) {
        return true;
    }
}
```

Following the official way to add an interceptor I ended up with:
```typescript
@Injectable()
export class LoggingInterceptor implements NestInterceptor {
    intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
        console.log('Before...');

        const now: number = Date.now();
        return next.handle().pipe(tap(() => console.log(`After... ${Date.now() - now}ms`)));
    }
}
```

I can see the logs in the console however I would like to log the microservice command as well: `/auth/login`.

**As far as I know there is no way to achieve this.**

Just in case I also opened a stackoverflow question: https://stackoverflow.com/questions/59161158/nestjs-how-to-globally-log-request-patterns-in-microservice-app

## What is the motivation / use case for changing the behavior?

So we can keep an overview in production which microservice API's were used.

**Comment by kamilmysliwiec** [comment]
What about:
```typescript
const pattern = context
      .switchToRpc()
      .getContext<TcpContext>()
      .getPattern();
```
The method name can vary depending on the transport strategy (e.g. for Redis it would be `getChannel()` instead)

**Comment by BorntraegerMarc** [comment]
I can't find the `TcpContext` class. where should it be imported from?

**Comment by BorntraegerMarc** [comment]
@kamilmysliwiec I just get an error message:
```js
komed-emr                | [Nest] 54   - 12/05/2019, 7:26:07 PM   [RpcExceptionsHandler] context.switchToRpc(...).getContext(...).getPattern is not a function +74719ms
komed-emr                | TypeError: context.switchToRpc(...).getContext(...).getPattern is not a function
komed-emr                |     at MicroserviceRequestLoggingInterceptor.intercept (/home/packages/nestjs/src/interceptors/microservice-request-logging.interceptor.ts:18:14)
komed-emr                |     at /home/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:22:36
komed-emr                |     at InterceptorsConsumer.intercept (/home/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:24:24)
komed-emr                |     at /home/app/node_modules/@nestjs/microservices/context/rpc-context-creator.js:50:46
komed-emr                |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
komed-emr                |     at /home/app/node_modules/@nestjs/microservices/context/rpc-proxy.js:10:32
komed-emr                |     at ServerTCP.handleMessage (/home/app/node_modules/@nestjs/microservices/server/server-tcp.js:52:54)
```

Is it maybe a bug? Because inspecting the return value of `getContext` doesn't look like anticipated:
<img width="449" alt="Screenshot 2019-12-05 at 19 31 45" src="https://user-images.githubusercontent.com/7549295/70263098-e18e8080-1795-11ea-8c3c-e49a947688d0.png">

**Comment by kamilmysliwiec** [comment]
Oh it looks fine. Can you update to the latest version?

**Comment by BorntraegerMarc** [comment]
jep, now it's working 🎉 thanks!
