### ISSUE TITLE
Can't declare 2 global modules with the same name

### ISSUE THREAD

**Issue by BorntraegerMarc** [nestjs/nest#3538]
## Bug Report

Not sure if this is an issue or expected behaviour. But I can't declare 2 global modules with the same name.

Before I receive any blame: I simplified the reproduction code and don't actually have a "core" & "shared" module with the same name. So please don't try to suggest I should change our app structure 😃 I verified that our prod code structure makes sense 😃 

## Current behavior

I receive the following error: `Nest can't resolve dependencies of the AppInitStateService (RedisService, ?). Please make sure that the argument EnvVariablesService at index [1] is available in the AppInitializationStateModule context.`

## Input Code

First module `src/shared/shared.module.ts`:
```ts
@Global()
@Module({
    providers: [RedisService],
    exports: [RedisService]
})
export class SharedModule {}
```

2nd module in app `src/core/shared.module.ts`:
```ts
@Global()
@Module({
    providers: [EnvVariablesService],
    exports: [EnvVariablesService]
})
export class SharedModule {}
```

app init service at `src/app-initialization/app-initialization.service.ts`:
```ts
@Injectable()
export class AppInitStateService {
    constructor(
        private readonly redisService: RedisService,
        private readonly envVariablesService: EnvVariablesService
    ) {}
}
```

## Expected behavior

I would have expected that this works.

## Environment

<pre><code>
Nest version: 6.12.2

 
For Tooling issues:
- Node version: v12.13.0  
- Platform: Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
This should be fixed in `6.10.6`. Please, let me know if you're still facing this issue.
