### ISSUE TITLE
GET request with JSON querystring

### ISSUE THREAD

**Issue by Menci** [nestjs/nest#3541]
## Is your feature request related to a problem? Please describe.
I am using DTOs and `class-validator` with a GET request endpoint in my controller. The input numeric ID is treated as a string so it doesn't pass the validation.

## Describe the solution you'd like
Provide a options to use JSON format querystring instead, to ensure the type of input data won't lose.

**Comment by Menci** [comment]
According to https://stackoverflow.com/questions/34820064/defining-an-api-with-swagger-get-call-that-uses-json-in-parameters, it is possiable in Swagger OpenAPI 3.

**Comment by kamilmysliwiec** [comment]
https://stackoverflow.com/a/45690436/6696689

Example:

```typescript
app.use(bodyParser.urlencoded({ extended: true }))
```

**Comment by Menci** [comment]
@kamilmysliwiec But Swagger still provide me a urlencoded interface. How can I tell Swagger I'm using JSON?

**Comment by kamilmysliwiec** [comment]
I would suggest creating this issue here https://github.com/scottie1984/swagger-ui-express @Menci

**Comment by Menci** [comment]
Opened nestjs/swagger#423.
