### ISSUE TITLE
Hot reload and injection issues

### ISSUE THREAD

**Issue by tobieeniafe** [nestjs/nest#3545]
## Current behavior
After installing nest app, over time the cli stops noticing changes in my files and keeps showing data from old code. Even after restarting my pc and server & from postman. So I deleted the ./dist folder and re-ran "nest start --watch" again and now I'm having an error saying "Nest can't resolve dependencies of the ProductsService (?). Please make sure that the argument ProductModel at index [0] is available in the AppModule context." and everything seems imported rightly." The repo is attached below.

## Input Code

https://github.com/tobieeniafe/nest_api

## Expected behavior

Hot reload should match current files at all times

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Windows 10

**Comment by kamilmysliwiec** [comment]
You've got a few issues:

1. Why both `ProductsController` and `ProductsService` are registered by `AppModule`? The error message is correct, `ProductModel` is not available in this context
2. Why `ProductsModule` imports `ProductsModule`? 

Also, sometimes TypeScript compiler's cache in incremental mode (watch mode) is not being properly invalidated. If you set `deleteOutDir` to true in `nest-cli.json`, you'll no longer see such problems

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
