### ISSUE TITLE
Testing Nestjs service with auth method

### ISSUE THREAD

**Issue by javaclassvas** [nestjs/nest#3546]
Hello! maybe somebody can help to figure out how to properly test my service?
code of the service

@Injectable ()
export class DevicesService {
    constructor (
        @InjectRepository ( DevicesEntity ) private devicesRepository: Repository<DevicesEntity> ) {
    }
     
    async authenticate ( data: TDevicesDTO ): Promise<boolean> {
        const { deviceId, password } = data;
        const device: DevicesEntity  = await this.devicesRepository.findOne ( { where: [{ deviceId }] } );
        if ( !device ) {
            console.log ( `[Devices service] Authenticate device ID : ${deviceId}. Access denied. Device was not found in the database` );
            return false;
        }

I need only to test how authenticate method works, and i found this strategy:

export type MockType<T> = {
    [P in keyof T]: jest.Mock<{}>;
};
//@ts-ignore
export const repositoryMockFactory: () => MockType<Repository<DevicesEntity>> = jest.fn ( () => ({
    findOne: jest.fn ( entity => entity ),
}) );

describe ( 'Device controller', () => {
    let service: DevicesService;
    let repositoryMock: MockType<Repository<DevicesEntity>>;
    
    beforeEach ( async () => {
        const module: TestingModule = await Test
        .createTestingModule ( {
            providers: [
                DevicesService,
                { provide: getRepositoryToken ( DevicesEntity ), useFactory: repositoryMockFactory },
            ],
        } ).compile ();
        
        service        = module.get<DevicesService> ( DevicesService );
        repositoryMock = module.get ( getRepositoryToken ( DevicesEntity ) );
    } );
    
    it ( 'should be defined', () => {
        expect ( service ).toBeDefined ();
    } );
    
    it ( 'should find in database', () => {
        const device                 = { deviceId: 'BCU0001', password: 'qwerty123' };
        const { deviceId, password } = device;
        const toFind                 = { where: [{ deviceId }] };
        repositoryMock.findOne ( toFind );
        expect ( repositoryMock.findOne ).toHaveBeenCalledWith ( toFind );
        
    } );
    
    it ( 'should pass Authentication', async () => {
        const device = { deviceId: 'BCU0001', password: 'qwerty123' };
        const auth   = await service.authenticate ( device );
        expect ( auth ).toEqual ( true );
    } );
    
} );

on database i only have one entry with deviceId: 'BCU0001', password: 'qwerty123' 
and the tests passed with success
but if i will make test case with wrong id or password, the tests are success too 
here is test log  

 PASS  src/services/auth.spec.ts
  Device controller
    ✓ should be defined (15ms)
    ✓ should find in database (9ms)
    ✓ should pass Authentication (9ms)

  console.log src/services/devices.service.ts:39
    [Devices service] Authenticate device ID : wrong id . Success

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        4.555s, estimated 5s
Ran all test suites.
(node:3956) UnhandledPromiseRejectionWarning: Error: Illegal arguments: string, undefined
(node:3956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

If anyone have an idea what im doing wrong - will be happy in pushing me to the right direction =))

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
