### ISSUE TITLE
Unobvious circular dependency error

### ISSUE THREAD

**Issue by dilame** [nestjs/nest#3555]
## Current behavior

```
 throw new circular_dependency_exception_1.CircularDependencyException('@InjectRepository()');
        ^

Error: A circular dependency has been detected inside @InjectRepository(). Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()". Also, try to eliminate barrel files because they can lead to an unexpected behavior too.
```

## Input Code

It's better to see the repo. There is no place for circular dependency here. It's too simple. It even doesn't use `@InjectRepository()` 

https://github.com/dilame/nest-circular-example

## Expected behavior

No error

## Possible Solution

Have no idea

## Environment

<pre><code>
Nest version: 6.7.2

 
For Tooling issues:
- Node version: v10.14.2
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
This error means that you've passed `undefined` value into `@InjectRepository()` decorator. We can't really produce anything more descriptive :( Ensure you don't have any circular dependencies between your entity<->service.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by dilame** [comment]
@kamilmysliwiec please, look at my repository. It doesn't use  `@InjectRepository()` at all. And doesn't have any serivces.  However, it doesn't starts.

**Comment by dilame** [comment]
I'm totally sure it's a bug.

**Comment by kamilmysliwiec** [comment]
Oh, yikes. OK, please remove these two files:

- https://github.com/dilame/nest-circular-example/blob/master/src/database/index.ts
- https://github.com/dilame/nest-circular-example/blob/master/src/database/entities/index.ts

More info here https://github.com/nestjs/nest/issues/1181#issuecomment-430197191
