### ISSUE TITLE
 Unknown authentication strategy "local"

### ISSUE THREAD

**Issue by rumsky** [nestjs/nest#3559]
## Current behavior
follow the docs https://docs.nestjs.com/techniques/authentication.  This is a error :"Error: Unknown authentication strategy "local""

## Environment

<pre><code>
Nest version:6.7.2
"passport": "^0.4.0",
 "passport-local": "^1.0.0",
 
For Tooling issues:
- Node version: v12.13.0
- Platform:  Mac

**Comment by unckleg** [comment]
Any news on this one ? Any service dependent on Request scope will break the passport.

**Comment by corradopetrelli** [comment]
I am in the same situation of @rumsky

**Comment by samanshahmohamadi** [comment]
I encountered same issue in a project which I created from scratch. But sample _19-auth-jwt_ in this repository is working just fine. I could not find the difference between this sample and my project.

**Comment by munkk** [comment]
same here
any updates?

**Comment by munkk** [comment]
i repeated all steps in that nest.js guide and somehow it started work :) seems that i forgot to add some module or soo...

**Comment by rumsky** [comment]
Sorry, I encountered this problem because I miss provide 'LocalStrategy' in auth.module.ts.
Please check your **providers** and **imports**
`auth/auth.module.ts

import { Module } from '@nestjs/common';
import { AuthService } from './auth.service';
import { UsersModule } from '../users/users.module';
import { PassportModule } from '@nestjs/passport';
import { LocalStrategy } from './local.strategy';

@Module({
  imports: [UsersModule, PassportModule],
  providers: [AuthService, LocalStrategy],
})
export class AuthModule {}
`

**Comment by PierreTurnbull** [comment]
I'm facing the same problem.
I have given my auth module the imports and providers required but still I get this error: "Error: Unknown authentication strategy "local""...

**Comment by cjancsar** [comment]
This is likely something broken in a recent version of a nest module. This happens all the time with Nest.

**Comment by PierreTurnbull** [comment]
@cjancsar why downvoting my comment though?
