### ISSUE TITLE
[Feature request] Support pipes for headers

### ISSUE THREAD

**Issue by ssbarbeee** [nestjs/nest#356]
Currently the route params decorator for headers has the following signature:
```javascript 
export declare const Headers: (property?: string) => ParameterDecorator;
```

Suggestion do you think it would be possible to support pipes for the headers as well?
Perhaps something like: 

```javascript
export declare function Headers(...pipes: PipeTransform<any>[]): any;
```
```javascript
export declare function Headers(property: string, ...pipes: PipeTransform<any>[]): any;
```

**Comment by kamilmysliwiec** [comment]
Hi @ssbarbeee,
That's not possible, see here https://github.com/nestjs/nest/issues/279
BUT there's a workaround. You can create a custom decorator for your headers https://docs.nestjs.com/custom-decorators, pipes run for them as well. 🙂
