### ISSUE TITLE
Can't start GRPC microservice server & client in docker container

### ISSUE THREAD

**Issue by BorntraegerMarc** [nestjs/nest#3560]
## Current behavior

It seems like [I'm not the first one who has troubles starting a GRPC client/server in nestjs in a docker container](https://stackoverflow.com/questions/55693797/how-to-run-grpc-microservice-with-nestjs-in-a-docker-container).

I'm using docker-compose.

I'm receiving the following error for the GRPC server:
```
The "grpc" package is missing. Please, make sure to install this library ($ npm install grpc) to take advantage of ServerGrpc.
```

And GRPC client:
```
The "grpc" package is missing. Please, make sure to install this library ($ npm install grpc) to take advantage of ClientGrpcProxy
```

I'm 100% sure that the `grpc` package is installed. I'm using yarn as a package manager.

Here's the `yarn.lock` file snippet:
```
grpc@^1.24.2:
  version "1.24.2"
  resolved "https://registry.yarnpkg.com/grpc/-/grpc-1.24.2.tgz#76d047bfa7b05b607cbbe3abb99065dcefe0c099"
  integrity sha512-EG3WH6AWMVvAiV15d+lr+K77HJ/KV/3FvMpjKjulXHbTwgDZkhkcWbwhxFAoTdxTkQvy0WFcO3Nog50QBbHZWw==
  dependencies:
    "@types/bytebuffer" "^5.0.40"
    lodash.camelcase "^4.3.0"
    lodash.clone "^4.5.0"
    nan "^2.13.2"
    node-pre-gyp "^0.14.0"
    protobufjs "^5.0.3"
```

I also tried installing the dependency directly in the docker build step: `RUN yarn add grpc` -> no luck as well

## Input Code

```ts
import { INestMicroservice } from '@nestjs/common';
import { Transport } from '@nestjs/common/enums/transport.enum';
import { NestFactory } from '@nestjs/core';
import { join } from 'path';
import { ApplicationModule } from './app.module';

async function bootstrap(): Promise<any> {
    // Create microservice app. Explanation why host is needed can be found here https://github.com/nestjs/nest/issues/2532
    const microserviceApp2: INestMicroservice = await NestFactory.createMicroservice(ApplicationModule, {
        transport: Transport.GRPC,
        options: {
            url: '0.0.0.0:3001',
            package: 'user',
            protoPath: join(__dirname, 'user.proto')
        }
    });
    await microserviceApp2.listenAsync();
}
// tslint:disable-next-line:no-floating-promises
bootstrap();
```

## Expected behavior

No exception is happening.

## Environment

<pre><code>
Nest version: 6.10.7

 
For Tooling issues:
- Node version: 12  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
This is not related to NestJS. We are currently running multiple gRPC microservices in Docker containers orchestrated by Kubernetes without any issue. I would rather look for `grpc` package related problems.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
