### ISSUE TITLE
e2e testing nest js with prisma

### ISSUE THREAD

**Issue by innoveltec** [nestjs/nest#3565]
Hello,

I created a nest js with prisma graphql api. How can i create and run some e2e testing for my api. It would be ideal if i could run my tests against my staging db. Beneath is a starting point i have. But i am not sure where i need to define my prisma service and how i can use it inside my tests.

beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [
        UserModule,
        GraphQLModule.forRoot({
          autoSchemaFile: 'src/schema.graphql',
        }),
      ],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

Kind regards,

Gerry

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
