### ISSUE TITLE
JSON:API implementation 

### ISSUE THREAD

**Issue by dsvjetl** [nestjs/nest#3566]
## Is your feature request related to a problem? Please describe.
I can't use JSON:API format with Nest.js (Request URLs handling, ex.: /user?include=image&sort=-name).

## Describe the solution you'd like
Implementation, documentation and example how to handle JSON:API format requests with Nest.js.

## What is the motivation / use case for changing the behavior?
JSON:API is highly growing HTTP(AJAX) standard. This is one of the major reasons why Nest.js is not used for some projects. It would be great if Nest.js would have some kind of handler for this, because it is a great framework and it would be a shame not to use it just because it is not supporting JSON:API format requests.

**Comment by kamilmysliwiec** [comment]
> I can't use JSON:API format with Nest.js

There is no reason why you couldn't use JSON:API with Nest. Nest provides an architecture and it's up to you what you'll build on top of that. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by scandinave** [comment]
I think that what it say, is that it would be nice to be able to generate json-api compatible api by just installing a special package. Something like @nestjs-jsonapi that when installed transform the output of the nestjs REST implementation. The same idea behind the proposing of express or fastify implementation 

It would be must easier than take a implementation and integrate it manually with nest.

**Comment by BrunnerLivio** [comment]
@scandinave have you had a look at [nestjsx/crud](https://github.com/nestjsx/crud)?

**Comment by benedikt-buchert** [comment]
I think a first step would be serializing data to JSON:API () https://jsonapi.org/format/

https://www.npmjs.com/package/jsonapi-serializer
https://docs.nestjs.com/techniques/serialization

Allowing requests via includes would be a second step that is optional: https://jsonapi.org/format/#fetching-includes

**Comment by klerick** [comment]
@dsvjetl  we have created a plugin  https://www.npmjs.com/package/json-api-nestjs
