### ISSUE TITLE
Demonstration of Need for Decorator Application for Middleware

### ISSUE THREAD

**Issue by IRCraziestTaxi** [nestjs/nest#3576]
## Is your feature request related to a problem? Please describe.
After giving up on trying to integrate `routing-controllers`' decorator-based middleware application to nest, I gave in and went ahead with the module-based configuration of middleware enforced by nest.

However, after running into some frustrations with the way our middleware is configured, I decided to once again address this issue.

For reference, past issues requesting this feature:

#235
#1800
#3285

## Describe the solution you'd like
The issue and desired solution is demonstrated in the repro referenced below.

## Teachability, Documentation, Adoption, Migration Strategy
The issue and desired solution is demonstrated in the repro referenced below.

## What is the motivation / use case for changing the behavior?
In short, a couple of our controllers have no more than two methods using a simple `AuthorizeValidToken` middleware and the rest of the many actions use an `AuthorizeThing` middleware.

What I found is that, even when configuring middleware in the module to which the controller is scoped, I needed to specify the base route already defined in the controller for the routes to exclude for `AuthorizeThing`.

A repro is linked below, but here are the relevant code snippets:

```ts
import { Injectable, NestMiddleware } from '@nestjs/common';
import { NextFunction, Request, Response } from 'express';

@Injectable()
export class AuthorizeValidToken implements NestMiddleware {
    public async use(request: Request, response: Response, next: NextFunction): Promise<void> {
        try {
            // Get the token from the request and make sure it's valid.
        }
        catch (error) {
            response
                .status(401)
                .json({
                    message: error.message,
                });

            return;
        }

        next();
    }
}

import { Injectable, NestMiddleware } from '@nestjs/common';
import { NextFunction, Request, Response } from 'express';

@Injectable()
export class AuthorizeThing implements NestMiddleware {
    public async use(request: Request, response: Response, next: NextFunction): Promise<void> {
        try {
            // Get the token from the request and make sure it's valid.
            // Then, check the user's ID against the parameter from the request
            // corresponding to the Thing's ID and check the database
            // to ensure the user is authorized for that Thing.
        }
        catch (error) {
            response
                .status(401)
                .json({
                    message: error.message,
                });

            return;
        }

        next();
    }
}

import { Controller, Get, Req, Res, Param } from '@nestjs/common';
import { Request, Response } from 'express';

@Controller('things')
export class ThingController {
  // IDEAL:
  // @UseBefore(AuthorizeThing)
  @Get(':thingId')
  public async getThingChildren(
    @Param('thingId')
    thingId: number,
    @Res()
    response: Response,
  ): Promise<Response> {
    // The AuthorizeThing middleware has already verified that the user is authorized
    // to see this Thing.
    // Therefore, query the database for the Thing matching the ID from the route param
    // and return it.
    return response
      .status(200)
      .json({
        message: 'Here is your thing.',
        value: {},
      });
  }

  // IDEAL:
  // @UseBefore(AuthorizeValidToken)
  @Get()
  public async getThings(
    @Req()
    request: Request,
    @Res()
    response: Response,
  ): Promise<Response> {
    // Get the token from the request and then get the user's ID from the token.
    // Then return Things that the user is authorized to see.
    return response
      .status(200)
      .json({
        message: 'Here are your things.',
        value: [],
      });
  }
}

import { MiddlewareConsumer, Module, NestModule, RequestMethod } from '@nestjs/common';
import { AuthorizeThing } from '../_middleware/authorize-thing.middleware';
import { AuthorizeValidToken } from '../_middleware/authorize-valid-token.middleware';
import { ThingController } from './thing.controller';

@Module({
  controllers: [ThingController],
})
export class ThingModule implements NestModule {
  public configure(consumer: MiddlewareConsumer): void {
    consumer
      .apply(AuthorizeValidToken)
      .forRoutes(ThingController);

    consumer
      .apply(AuthorizeThing)
      .exclude(
        {
          method: RequestMethod.GET,
          // My first thought was, since this is scoped to the ThingModule,
          // path should be as follows:
          // path: '',
          // Rather than the following
          // (although it did make sense once I realized what was going on):
          path: 'things',
          // Note that this string path is redundant with the base path
          // already specified in ThingController.
          // This is a pretty strong argument for decorator-based middleware application.
          // The entire point of typescript and decorators is to reduce redundancy like this,
          // not to mention that decorator-based application is more intuitive anyway.
        },
      )
      .forRoutes(ThingController);
  }
}
```

Per the comments, the entire point of typescript and decorators is to reduce redundancy such as needing to specify the base route of the controller again. What if that base route changes? Sure, I could, should, and probably will create an external constant to ensure that base route is consistent everywhere it is used, but the need to do so coupled with the fact that decorators would make this much more intuitive and eliminate the need to do that made me believe this issue needs to be addressed again.

To be clear, I am _not_ suggesting that the need to specify the base route rather than an empty string should be changed, but I _am_ suggesting that decorators would make this a lot easier and more intuitive.

I know this issue is going to be immediately dismissed, closed, and locked again, but I want the record to show the logic for implementing decorators to apply middleware.

Minimalist repro containing the snippets above:
https://github.com/IRCraziestTaxi/nest-middleware-issue

**Comment by kamilmysliwiec** [comment]
As I've mentioned a few times already in all these issues that you listed (+ several others), we don't plan to introduce another decorator for middleware. Middleware are tied to a path, everything else - to handlers. In fact, if you use all the existing architectural building blocks that are specific to Nest (filters, guards, pipes, and interceptors), you don't even need a middleware anymore.
