### ISSUE TITLE
Suggestion: "Who is using this in production?" thread.

### ISSUE THREAD

**Issue by j** [nestjs/nest#359]
It'd be cool to see how this is performing for any adopters and their experiences with it.

**Comment by amrayoub** [comment]
same question , i'm thinking of starting learning it

**Comment by zMotivat0r** [comment]
I'm using it in production. It's the best thing that ever happened to me in my nodejs backend development process so far. Tons of kudos to @kamilmysliwiec and all contributors. Love ya!

**Comment by tx4x** [comment]
same question here. biggest obstacle to get into this here is the documentation which leaves a lot to desire. ...not sure i have to learn angular first or debug the code

**Comment by BruceHem** [comment]
@tx4x U don't have to learn Angular.

**Comment by tx4x** [comment]
@BruceHem : any other recommendation how to learn this ? Currently I am trying to find a base platform to port [my IDE](https://www.npmjs.com/package/control-freak), authoring apps for automation, IoT & friends). I have lots of constraints like cli-apps, user generated web/electron apps,... I am having a hard time to understand how to get my features done with nest.js. To me it seems that nest.js is rather designed for web-apps only, endorsing mainly http(express), not sure yet. I couldn't get even web-sockets working the way i want because there seems too much abstraction in the way, hiding important things, no idea yet. I will give it another week :-)

**Comment by valorkin** [comment]
We using it in enterprise: cb.com
In several gaominder.org products
And all new apps

**Comment by kamilmysliwiec** [comment]
I have been working with Nest several times, and I know few companies that use it as well, but I'm not neutral here 😅

**Comment by BorntraegerMarc** [comment]
We're using nest to build a highly scalable & secured medical chat application for hospitals. So Nest is literally saving lives 🎉🙂

**Comment by kamilmysliwiec** [comment]
@BorntraegerMarc wow! I love it 😍

**Comment by tx4x** [comment]
Hi there,
I did hope someone could point on a finished project here on github :-)
g

**Comment by BorntraegerMarc** [comment]
Unfortunately our project is not open source :/

**Comment by bradleyayers** [comment]
I'm using it for https://dovetailapp.com and happy with it 👍

**Comment by martinyung** [comment]
@bradleyayers @zMotivat0r @BorntraegerMarc, hi all, i'm trying to deploy nest js to aws elastic beanstalk, is there any documentation on how to configure the app for production? Thanks

**Comment by kamilmysliwiec** [comment]
@martinyung there's no documentation about that so far. About this kind of question, you should rather use stackoverflow 🙂

**Comment by BorntraegerMarc** [comment]
Yeah @kamilmysliwiec Altough I'm feeling that this question comes up quite a lot of times... I know that it has absolutely nothing to do with nestjs but I just wanted to ask: If I would write a step-by-step guide on how to generate a uglyfied & production deployable bundle: would you publish it on the official documentation?

**Comment by kamilmysliwiec** [comment]
@BorntraegerMarc feel free to create a PR directly to the docs, I'd love to see it 🙂 !!

**Comment by cojack** [comment]
Hi guys, I would like to inform you that I will present Nest on [meet.js](https://www.facebook.com/events/329804147528351/) in Gdańsk, so everyone is warm welcome there if you would like to share your knowledge or gather some. Btw we have free beer :beer: :heart_eyes: 

Presentation will have name: "Nest to meet you" :smiley:

**Comment by kamilmysliwiec** [comment]
@cojack love it! let me know if I can help somehow 🍻

**Comment by davidssonarnor** [comment]
@kamilmysliwiec I am evaluating using nest in production. Do you have any stats on companies using nest in production? Thanks, and keep up the good work.

**Comment by valorkin** [comment]
@davidssonarnor what kind of stats are you looking for?

**Comment by davidssonarnor** [comment]
@valorkin Maybe best would be a list of companies or projects using Nest in production. Similar list for React would be https://github.com/facebook/react/wiki/Sites-Using-React . I am trying to evaluate this from the standpoint of a CTO. It is a little bit hard, I have been prototyping a little bit using Nest and it has been good so far.

**Comment by valorkin** [comment]
CareerBuilder, Gapminder, Valor Software, This Dot, Liberty Flight, ...

**Comment by andrewtw** [comment]
It would be great if NestJS could have a page that open to commit the apps that use NestJS in production.

Well, like SailsJS, it presents the logo on official websites to make its project be more persuasive.

**Comment by kamilmysliwiec** [comment]
Reference #1006

**Comment by cconcise** [comment]
I'm with @davidssonarnor. I love Nest.JS, it's a great framework, but it's hard to pitch to people in business. Right now all I can really sell is developer experience. It would be nice to have a list on the official website of companies using it in production. The documentation could use a bit of improvement as well. Super super awesome framework though! I've used it for one app already, and am currently evaluating using it again for another app.

**Comment by cconcise** [comment]
@kamilmysliwiec Nice to hear from you! I'd love to start contributing to Nest as soon as I can free up some time. Hands down way better framework than Express or Hapi (IMO). Thank you a million times over for starting this amazing framework!! For the time this project saved me over using something like Express on my last project, you helped to literally put money in my pocket.

@valorkin that's a very good point. I've been pretty good at selling Nest, aside from selling that it scales. When I sell React I can simply point to Facebook or Airbnb. WIth Nest it's a harder sell in terms of putting numbers into a spreadsheet. Btw I just checked out your company's website, awesome website! Super clean design, and fast!

**Comment by valorkin** [comment]
@cconcise thanks ;)
