### ISSUE TITLE
How to inject service in DTO class?

### ISSUE THREAD

**Issue by sjlee1125** [nestjs/nest#3608]
How to inject service in DTO class?
I have DTO and Service
dto
```typescript
@Injectable()
export class DTO {
  constructor(private readonly testService: TestService) {}

  @Validate(IsValidAddress)
  address: string;

  @Expose()
  get realAddress() {
    return this.testService.isValidAddress(this.address);
  }
}
```
and dto used in addressController
```typescript
@Controller('address')
export class AddressController {
  constructor(private readonly addressService: AddressService) {}

  @Get('balance')
  getBalance(@Param() params: DTO) {
    console.log(params.realAddress);
    return this.addressService.getBalance({ ...params });
  }
}
```
this throw error that testService undefined..
How can i use that service in dto class?

* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/528
