### ISSUE TITLE
Having a way to disconnect Database connection (or any services having a connection) properly when the app close

### ISSUE THREAD

**Issue by vschoener** [nestjs/nest#3610]
## Is your feature request related to a problem? Please describe.
I use a custom MongoDB module that connects (create a connection) in the `forRoot`. But when the app closes, there is no way to instruct and disconnect the database.

I got this situation during my e2e test, jest hangs waiting for a promise to be resolved and it comes from the DB connection having his connection.

## Describe the solution you'd like
During the `app.close()`, I would like my services connection to be closed properly.

I know I could manually disconnect my DB in the after here getting the service by my hand, but maybe the module may need to implement a `close` method to handle such a case.

Or should I use https://docs.nestjs.com/fundamentals/lifecycle-events? 
Let me know what you think.

## Teachability, Documentation, Adoption, Migration Strategy
In the module, having method implementation like `forRoot` (maybe static if we can use DI), to be able to get the connection and close it. 

## What is the motivation / use case for changing the behavior?
Controlling the module that needs to close connection whatever it is

**Comment by kamilmysliwiec** [comment]
Use [lifecycle events](https://docs.nestjs.com/fundamentals/lifecycle-events) for this.

`app.close()` will trigger hooks

**Comment by vschoener** [comment]
Great, thank you 👍
