### ISSUE TITLE
Headers variable problem

### ISSUE THREAD

**Issue by biplabmalakar** [nestjs/nest#362]
Request is=> GET /demo/get HTTP/1.1
Host: localhost:3000
headerData: biplab
Cache-Control: no-cache
Postman-Token: d4a18862-9849-527d-bd34-6490c9ec1f65

and value in the server
{ host: 'localhost:3000',
  connection: 'keep-alive',
  headerdata: 'biplab', // hear variable is converted into lowercase.
  'cache-control': 'no-cache',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36',
  'postman-token': '4e9b956f-91ca-4d9f-206d-1591bca85bfa',
  accept: '*/*',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-US,en;q=0.9' }

Can check this issue?

**Comment by cojack** [comment]
Hi @biplabmalakar,
First of all, there is a CONTRIBUTING guide, also when you press a button "New issue" there was a template for fill to better explanation of problem, why don't you use it?

And at the very end, if Im not blind, your header looks like:

```headerData: biplab```

So what you expect to have at the server side?

```headerdata: 'biplab', // hear variable is converted into lowercase.```

values are identical.

**Comment by kamilmysliwiec** [comment]
Hi @biplabmalakar,
Honestly, I don't understand how we could help you. Where's a difference between what you expected -> what have you received eventually?

**Comment by BruceHem** [comment]
@biplabmalakar all header's properties get converted to lower case.

Example: If you have X-API-Key set in the header, on the server u will receive x-api-key.

**Comment by cojack** [comment]
@BruceHem he was asking abut values, not keys

**Comment by biplabmalakar** [comment]
@kamilmysliwiec Actually I didn't read the HTTP property before creating this issue, so sorry for that. It's working fine.
I have another problem, According to the doc if we pass object to the HttpException ({
    status: HttpStatus.FORBIDDEN,
    error: 'This is a custom message',
  }) then it will rewrite response body but it's not,  it's giving error "expected another argument"

**Comment by kamilmysliwiec** [comment]
@biplabmalakar please create appropriate issue for that 🙂
