### ISSUE TITLE
Injection outside of constructor.

### ISSUE THREAD

**Issue by Ayzrian** [nestjs/nest#3621]
## Is your feature request related to a problem? Please describe.

I have an issue when I was writing a class that encapsulates login of repository and mongoose model. I use injection to provide repository and model to class, but that doesn't work, because I want to be able use its static methods and create class vie new Class(classData); 
## Describe the solution you'd like

Angular provide Injector, that allows you to inject whatever you want whenever you want. I want to be able to inject repository and model inside my static methods out of necessity. 

## Teachability, Documentation, Adoption, Migration Strategy

Here is example how it works with Angular.

https://stackoverflow.com/questions/39101865/angular-2-inject-dependency-outside-constructor

## What is the motivation / use case for changing the behavior?

Nest will be even more flexible framework. Use case was described before.

**Comment by kamilmysliwiec** [comment]
Use `ModuleRef` for this: https://docs.nestjs.com/fundamentals/circular-dependency#module-reference

We are working on a dedicated chapter for this feature
