### ISSUE TITLE
Validation pipe doesn't validate DTOs.

### ISSUE THREAD

**Issue by Ayzrian** [nestjs/nest#3625]
## Current behavior

Validation pipe pass objects with wrong definition. Here is the definition. 

![image](https://user-images.githubusercontent.com/44115170/70636598-7d106d00-1c3e-11ea-8dce-cd78c066c0ca.png)

Here is the route handler.

![image](https://user-images.githubusercontent.com/44115170/70636623-8b5e8900-1c3e-11ea-95e6-99aa1a663f28.png)

Here is the insomnia request. 

![image](https://user-images.githubusercontent.com/44115170/70636730-afba6580-1c3e-11ea-9ebd-711b1b5aeb57.png)

## Input Code

```ts
const your = (code) => here;
```

## Expected behavior

I want validation pipe to behave correctly.

## Possible Solution

I suppose that nest or validation pipe starts to work incorrect if you declare body type using |. So it can't detect correctly what is it suppose to check first type or second.

## Environment

<pre><code>
Nest version: 6.7.2

 
For Tooling issues:
- Node version: 12.12
- Platform:  Windows 

Others:

</code></pre>

**Comment by galesky** [comment]
Hey @ayzrian,

Just to narrow down the problem , 

1. Have you tried using only the simple DTO (not the array kind) ? In that case it worked as expected?

**Comment by Ayzrian** [comment]
> Hey @Ayzrian,
> 
> Just to narrow down the problem ,
> 
> 1. Have you tried using only the simple DTO (not the array kind) ? In that case it worked as expected?

Yes, I have tried. In this case it works as expected.

**Comment by kamilmysliwiec** [comment]
Please, use Github search. These problem is explained in a few issues already. Keywords that may help "validationpipe array"
