### ISSUE TITLE
Microservice running in cluster mode sends message to all forks

### ISSUE THREAD

**Issue by ukaric** [nestjs/nest#3626]
## Bug Report

With Nestjs microservice and Redis transport trying to fork a process for parallel execution and then sending messages results in a message being delivered to all processes and triggering underlying functionality multiple times.  

## Current behavior

By sending a message to nestjs microservice instance that's being forked to multiple CPU cores underlying queue handler gets triggered n times.

> main.js

```ts
import { NestFactory } from '@nestjs/core';

import { AppModule } from './app/app.module';

import * as os from 'os';
import * as cluster from 'cluster';
import { Logger } from '@nestjs/common';
import { Transport } from '@nestjs/microservices';

async function bootstrap() {
  const logger = new Logger('Micrsoervice Queue');
  const clusterSize = os.cpus().length;

  if (clusterSize > 1) {
    if (cluster.isMaster) {
      for (let i = 0; i < clusterSize; i++) {
        cluster.fork();
      }

      cluster.on('exit', function(worker) {
        logger.log(`Worker ${worker.id} has exited.`);
      });
    } else {
      const app = await NestFactory.createMicroservice(AppModule, {
        transport: Transport.REDIS,
        options: {
          url: 'redis://127.0.0.1:6379',
          retryAttempts: 5,
          retryDelay: 500
        }
      });
      await app.listen(() => {
        console.log('Listening');
      });
    }
  }
}

bootstrap();

```

> app.controller

```ts
import { Controller } from '@nestjs/common';
import { Queue } from 'bull';
import { InjectQueue } from 'nest-bull';
import * as _ from 'lodash';
import { MessagePattern } from '@nestjs/microservices';

@Controller()
export class AppController {
  constructor(@InjectQueue('image-processing-queue') private readonly queue: Queue) {}

  // Gets triggered  `os.cpus().length` times
  @MessagePattern({ cmd: '@QUEUE/PROCESS_IMAGE' })
  async uploadToBucket(data) {
    const { file, bucketId } = data;
    const job = await this.queue.add('processImage', { file, bucketId });
    return {
      message: 'Image processing job created',
      data: _.omit(job, ['data'])
    };
  }
}

```

## Expected behavior

Sending a message pattern to a forked instance of nestjs microservice should trigger the underlying handler only once.

## Possible Solution

Maybe some kind of schedule would work. I have tried it with a plain HTTP endpoint and it does not appear to be triggering handlers multiple times.

## Environment

<pre><code>
Nest version: `@nrwl/nest: ^8.5.0`

 
For Tooling issues:
- Node version: `v12.10.0`
- Platform:  `Linux 4.19.85-1-MANJARO`

**Comment by kamilmysliwiec** [comment]
> Redis transporter implements the publish/subscribe messaging paradigm and leverages Pub/Sub feature of Redis. Published messages are categorized in channels, without knowing what subscribers (if any) will eventually receive the message. Each microservice can subscribe to any number of channels. In addition, more than one channel can be subscribed to at a time. Messages exchanged through channels are fire-and-forget, which means that if a message is published and there are no subscribers interested in it, the message is removed and cannot be recovered. Thus, you don't have a guarantee that either messages or events will be handled by at least one service. A single message can be subscribed to (and received) by multiple subscribers.

Most importantly, this part:
 
> A single message can be subscribed to (and received) by multiple subscribers.

Source https://docs.nestjs.com/microservices/redis

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
