### ISSUE TITLE
Nest.js authentication stop working after upgrade node.js to 13.3.0

### ISSUE THREAD

**Issue by leosuncin** [nestjs/nest#3631]
## Bug Report
I have a boilerplate project with Nest.js authentication using passport, and was working perfectly fine until I update my node.js version to 13.3.0 for unknown reason the passport strategies are ignored by Nest router and the request is passed directly to the controller.

The project has unit and e2e tests to fully coverage the edge cases, the only change was the update of node 12.13.0 to 13.3.0.
## Current behavior
I had setup passport with `local` and `jwt` strategies, also enable passport session. The user is validated against the database.

The `Authorization` header is not verified neither the login credentials by the Passport module.
## Input Code

https://github.com/leosuncin/nest-auth-example

## Expected behavior

Authentication working with Passport

## Environment

<pre><code>
@nestjs/common: 6.10.10
@nestjs/core: 6.10.10
@nestjs/jwt: 6.1.1
@nestjs/passport: 6.1.1
@nestjs/platform-express: 6.10.10
@nestjs/typeorm: 6.2.0

 
For Tooling issues:
- Node version: 13.3.0  
- Platform: Manjaro Linux 5.4.2-1  

Others:
passport: 0.4.0
passport-jwt: 4.0.0
passport-local: "1.0.0
typeorm: 0.2.19

</code></pre>

I'm not sure if it is an error with Nest.js core or Passport module

**Comment by corradopetrelli** [comment]
Are you solved it? I am interested

**Comment by leosuncin** [comment]
No, it's not working, I downgraded node.js version

**Comment by leosuncin** [comment]
@corradopetrelli. Do you have the same issue?

**Comment by corradopetrelli** [comment]
@leosuncin Yes I have the same issue.
The differences about my env are:
- Ubuntu 18.04.3
- Node version 12.13.1

**Comment by leosuncin** [comment]
I installed node.js 12.13.1 with NVM and didn't get any error with my repository.

> @leosuncin Yes I have the same issue.
> The differences about my env are:
> 
>     * Ubuntu 18.04.3
> 
>     * Node version 12.13.1

**Comment by leosuncin** [comment]
Travis CI
https://travis-ci.org/leosuncin/nest-auth-example

**Comment by thierri** [comment]
The problem is the signature of validate method, on LocalStrategy class. Make sure it receives exactly username and password.

If you replace username with email or something else it will not overload the original PassportStrategy method, returning always Unauthorized, given no clue of the error.

async validate(username: string, password: string): Promise<any> { // Do any validation here. }

**Comment by leosuncin** [comment]
The strategy was never called. The problem was the `Guard`

**Comment by ama3ing** [comment]
@leosuncin But what was the problem?

**Comment by kluplau** [comment]
Running the sample `19-auth-jwt` and calling `/auth/login` with 
```json
{"username": "john", "password": "changeme'}
```
Resulted in error 401.

It works in node 12.14.0 but stopped working in 12.14.1. I don't know when it started working again, but the latest release 12.16.3 works.

**Comment by jakohole** [comment]
> Running the sample `19-auth-jwt` and calling `/auth/login` with
> 
> ```json
> {"username": "john", "password": "changeme'}
> ```
> 
> Resulted in error 401.
> 
> It works in node 12.14.0 but stopped working in 12.14.1. I don't know when it started working again, but the latest release 12.16.3 works.

Poor me. It doesn't work though.

**Comment by kluplau** [comment]
> Poor me. It doesn't work though.

Have you renamed the username to email by any chance?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
