### ISSUE TITLE
Wrong nested objects validation.

### ISSUE THREAD

**Issue by Ayzrian** [nestjs/nest#3634]
## Current behavior

I want to validate body using ValidatePipe. It doesn't validate my DTO correctly. 

## Input Code

Here is my insomnia request. 

![image](https://user-images.githubusercontent.com/44115170/70797545-66d4ef00-1dad-11ea-8c6c-4956765e0d13.png)

```ts
export class CreateTaskDto {
    @IsString()
    @MinLength(3)
    header: string;

    @IsString()
    @MinLength(3)
    text: string;

    @IsBoolean()
    isShared: boolean;
}


export class CreateTasksDto {
  @ValidateNested({
    each: true,
  })
  tasks: CreateTaskDto[];
}

// Here is the route handler.


  @Post()
  @UsePipes(new ValidationPipe())
  async createTask(
    @Body() tasksDto: CreateTasksDto,
    @Param('userId', new ParseIntPipe()) userId: number,
  ): Promise<boolean> {
    return this.tasksService.createTasks(tasksDto.tasks, userId);
  }

```

## Expected behavior

DTO must not pass validation because field header is number. 

## Environment

<pre><code>
Nest version: 6.9

 
For Tooling issues:
- Node version: 12
- Platform: Windows 

Others:

</code></pre>

**Comment by bmstefanski** [comment]
Have you tried adding `@Type(() => CreateTaskDto)` over tasks field
```ts
@ValidateNested({
    each: true,
  })
@Type(() => CreateTaskDto)
  tasks: CreateTaskDto[];
```


https://github.com/typestack/class-transformer#working-with-nested-objects

**Comment by kamilmysliwiec** [comment]
@bmstefanski solution will fix your issue
