### ISSUE TITLE
Nest can't inject custom provider

### ISSUE THREAD

**Issue by katsanva** [nestjs/nest#3635]
## Bug Report
When trying to add nest to existing application DI is not working for the custom provider. Everything is fine for clean standalone nest app.

## Current behavior
```
[Nest] 48509   - 12/13/2019, 1:30:58 PM   [ExceptionHandler] Nest can't resolve dependencies of the AccountsService (?). Please make sure that the argument foo at index [0] is available in the AccountsService context.

Potential solutions:
- If foo is a provider, is it part of the current AccountsService?
- If foo is exported from a separate @Module, is that module imported within AccountsService?
  @Module({
    imports: [ /* the Module containing foo */ ]
  })
```
## Input Code

accounts.module.ts
```ts
import { Module } from '@nestjs/common';
import { AccountsService } from './accounts.service';

@Module({
  imports: [AccountsService],
  providers: [{ provide: 'foo', useValue: 'foo' }],
  exports: [AccountsService],
})
export class AccountsModule {}
```
accounts.service.ts
```ts
import { Injectable, Inject } from '@nestjs/common';

@Injectable()
export class AccountsService {
  constructor(
    @Inject('foo')
    private readonly foo: any,
  ) {}
}
```

## Expected behavior
Dependencies are injected

## Possible Solution

This resolves with installing @nestjs/*@6.10.9

## Environment

<pre><code>
Nest version: 6.10.10

 
For Tooling issues:
- Node version: v10.17.0
- Platform:  Mac

Others:

tsc 3.5.2
</code></pre>

**Comment by kamilmysliwiec** [comment]
Your code is invalid (`imports: [AccountsService]`). 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
