### ISSUE TITLE
Nest JS Monorepo mode for microservices + docker-compose

### ISSUE THREAD

**Issue by Maxondria** [nestjs/nest#3652]
Hi,

I am developing a @nestjs project, we have decided to switch to a **microservices architecture** embracing the **monorepo** mode for code reusability. We use **docker-compose** to spin up a number of these **microservices**. On switching to monorepo mode, everything worked as read from the docs but we are having trouble building each app as an image from it's own dockerfile, so it becomes a service in docker compose,  because these apps share same dependancies (typescript files mainly - read linter, and config). Because of this, apps can't start because they can't find the right config files because the tsconfig file in each app's folder extends the main file on the root of the project (which nest configures relative to project and library in the monorepo).

**Ideally, each app's image is supposed to be built from it's specific dockerfile however, the tsconfig file in each of the apps created by nest extends the main tsconfig which has settings and paths as defined by the nest-cli for the whole project**

We don't want to transfer everything into one container. Are there any suggestions or help on how to configure docker-files to avoid the issues aforementioned? thanks

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by dulkith** [comment]
@Maxondria  did you solve the problem?
