### ISSUE TITLE
 WebSocketGateway and onModuleInit execution order

### ISSUE THREAD

**Issue by thinkive** [nestjs/nest#3654]
When I use nestjs for a project, because I have asynchronous operations in onModuleInit, WebSocketGateway has successfully connected to the client, but my project has not yet started. I would like to ask if there is a way to wait for the asynchronous operations in onModuleInit to complete WebSocketGateway listening is enabled

**Comment by kamilmysliwiec** [comment]
> f there is a way to wait for the asynchronous operations in onModuleInit to complete WebSocketGateway listening is enabled

It's impossible. `onModuleInit` runs *after* gateway is listening. Instead, you can define an asynchronous provider and inject this provider into the gateway class (hence, you'll have certainty that the gateway will be created ONLY when this specific provider has been created as well).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
