### ISSUE TITLE
module.getProviderByKey(providerKey).instance returns the instance without injecting its dependencies

### ISSUE THREAD

**Issue by enoelboostmi** [nestjs/nest#3660]
## Input Code
I have a class called `PermissionManager` that receives a list of `Voter` interfaces in the constructor.

```lang-ts
    export interface Voter {
        vote(): bool;
    }

    export class PermissionManager {
          constructor(private readonly voters: Voter[]) {
          }
    }

    export class SpecificVoter implements Voter {
          constructor(private readonly anotherDependency: AnotherDependency) {
          }

          public function vote(): bool {
              return true;
          }
    }
```

The idea is that `PermissionManager` shouldn't know what the voters are. So, to do so, I add each of my voters into a global list so that when I instantiate `PermissionManager`, it has the list of all the voters. Basically, I'm doing something similar to [Symfony's service tags][1].

Here's my NestJS provider:

```lang-ts
    const provider = {
      provide: PermissionManager,
      useFactory: (container: ModulesContainer) => {

        const voters = [];

        globalList.forEach(value => {
          container.forEach(module => {
            const provider = module.getProviderByKey(value.constructor.name);

            if (provider !== undefined) {
              voters.push(provider.instance);
            }
          });
        });

        return new PermissionManager(voters);
      },
      inject: [ModulesContainer],
    };
```

The provider can properly find the class `SpecificVoter` but it never instantiates its dependencies.

Therefore, why doesn't `module.getProviderByKey(SpecificVoter).instance`  return `SpecificVoter` with its dependencies?

  [1]: https://symfony.com/doc/current/service_container/tags.html

## Environment

<pre><code>
Nest version: 6.10.11
 
For Tooling issues:
- Node version: 12.8.0
- Platform:  Mac

Others:

</code></pre>

**Comment by enoelboostmi** [comment]
Ok, so @jmcdo29 gave me a good hint on Discord but I want to put it here since I don't know exactly what the best approach is.

If I do:

```
provider.cloneStaticInstance().donePromise.then(value1 => {
// provider.instance here now has the injected dependencies
 })
```

I'm guessing that directly accessing `provider.instance` is wrong and that another method should be used?

I can see that there are two other methods: `getInstanceByContextId` or `getInstanceByInquirerId`and when the `donePromise` is resolved, provider.instance contains the proper instance.

**Comment by kamilmysliwiec** [comment]
Well, you are trying to access the internals that aren't a part of the public API. We don't have any advanced documentation about the underlying structures/methods that can be used to extend the framework. I'd suggest looking at other packages (like graphql or bull instead) to better understand how to leverage them
