### ISSUE TITLE
Integrating a Hystrix-like library 

### ISSUE THREAD

**Issue by samdelagarza** [nestjs/nest#3662]
Our team has really enjoyed using NestJS as distinct http microservices we have also created an Orchestration Layer which plays the part of a microservice aggregator (BFF). Its at this layer that we would like to incorporate a tool similar to Hystrix by Netflix, but we found https://nodeshift.dev/opossum/ which we think would work great. However, my question is how would you recommend that I grab the route definitions (which are hidden/generated by the controllers). 

Is there a pattern you recommend? Or is there prior-art somewhere of another library that is doing the same?

**Comment by kamilmysliwiec** [comment]
Unfortunately, there is no easy way to access this metadata. A quite similar question was asked here https://github.com/nestjs/nest/issues/1769
