### ISSUE TITLE
global Http Service shared across the whole application 

### ISSUE THREAD

**Issue by AlaaMezian** [nestjs/nest#3663]
## Feature Request
i would like a way to provide the same httpService among the whole application 
setting the httpmodule to global isn't doing so and instead a different httpService is given accross services 
## Is your feature request related to a problem? Please describe.

for example in my appmodule i am using onModuleInit and in that logic i am using axios interceptor to modify the request object and add a specific header and them i am using httpService in another service to call an api back-end-to-back-end the header i added is not in the request used in httpService .
## Describe the solution you'd like

a clear and simple way to do so 
## What is the motivation / use case for changing the behavior?
trying to use nest js in a microservices project  and trying to deal with some concerns regarding that

**Comment by galesky** [comment]
There are a few ways to do so, in summary it seems you want the HttpService as [singleton](https://www.geeksforgeeks.org/singleton-class-java/), which nest actually defaults to.

As you mentioned an Interceptor, can you check if any of this issues fits into what you are looking for: 
https://github.com/nestjs/nest/issues/3496, 
https://github.com/nestjs/nest/issues/3250

**Comment by AlaaMezian** [comment]
@galesky  thanks for your feedback but this is not the case 
for httpServices because they are not custom provider they are out of the box provider 

what happening currently is the following in the main app I am using onModuleInit 

```
export class AppModule implements OnModuleInit {
  constructor(private httpService: HttpService) { }
  onModuleInit() {
    this.httpService.axiosRef.interceptors.request.use((req) => {
      req.headers['X-Correlation-Id'] = `GTW-${v4()}`;
      console.log('the request ', req.headers['X-Correlation-Id']);
      return req;
    });
  }
````
but when logging request across the application there is no header added to all request and by that i mean when using axios to call other services and then log the header received in the other service there is no X-Correlation-Id'

**Comment by galesky** [comment]
Oh, i got it now, you are want to add the `header` to the OUTBOUND requests, not the INBOUND ones, sorry i misunderstood before;

I'll take a look later today, i think maybe you can do this with [Interceptors](https://docs.nestjs.com/interceptors) but i'm not sure yet

**Comment by AlaaMezian** [comment]
Yes and I am using an axios interceptors but it's seems that it's not using the the same httpService among all classes

**Comment by jmcdo29** [comment]
I believe if you want all of your httpServices to use the same interceptor, if I'm understadning the use right, when you `register` the `HttpModule` you can pass in configuration options and set the `transformRequest` option to be a function that adds headers to the outbound request. Then, as the `HttpService` is not transient scoped, all uses of the `HttpService` should have that transform method with it

**Comment by kamilmysliwiec** [comment]
Simply register `HttpModule` once and re-export it so you won't have to pass the same set of options every time. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
