### ISSUE TITLE
Axios 0.19.0 that is being used has a bug and no update in sight :-( - can we downgrade ?

### ISSUE THREAD

**Issue by iangregsondev** [nestjs/nest#3665]
## Current behavior

There is a bug in the latest axios 0.19.0 which nest depends on, basically you can't pass in custom properties on the config object - this is really important as I normally pass in my original request and correlationid - so in the interceptors (axios) - i have access to those for logging etc.

I know this is NOT a nest issue but nest does depend on a version of axios with an issue.

The issue is available here https://github.com/axios/axios/issues/1718 . and 
 https://github.com/axios/axios/pull/2006

Everyone has been waiting for 0.19.1 to be released - which fixes it - it seems - see https://github.com/axios/axios/pull/2502

Although right now its a major issue for nest and no release seems imminent.

Can we roll back to the previous version ?

**Comment by kamilmysliwiec** [comment]
Unfortunately, older versions of axios have some minor vulnerabilities. We need to wait until the new release of axios is released.
