### ISSUE TITLE
GRPC Client in Guards

### ISSUE THREAD

**Issue by juicycleff** [nestjs/nest#3666]
## Is your feature request related to a problem? Please describe.
grpc client is always null in a guard

## Describe the solution you'd like
I believe it is beneficial to have GRPC client work inside a Guard especially for microservice architectures, where you need to call another service in a guard.

## Teachability, Documentation, Adoption, Migration Strategy
```Typescript
@Injectable()
export class TenantGuard implements CanActivate, OnModuleInit {
  @Client({
    transport: Transport.GRPC,
    options: {
      package: 'tenant',
      url: `localhost:7200`,
      protoPath: join('proto/tenant.proto'),
    },
  })
  client: ClientGrpc;
  tenantService: ITenantService;

  async canActivate(
    context: ExecutionContext,
  ): Promise<boolean> {

    try {
      const tenant = await this.tenantService.findOneTenant({
        ...code
      }).toPromise();
      return !!tenant;
    } catch (e) {
      Logger.error(e, this.constructor.name);
      throw new AuthenticationError('Invalid tenant credentials');
    }
  }

  onModuleInit(): any {
    this.tenantService = this.client.getService<ITenantService>('TenantService');
  }
}
```

## What is the motivation / use case for changing the behavior?
Communicating with other microservices using GRPC in guards

**Comment by kamilmysliwiec** [comment]
You should never use `@Client()` in enhancers (neither in guards nor interceptors etc). I'd suggest using `ClientsModule` instead https://docs.nestjs.com/microservices/basics#client
