### ISSUE TITLE
npm install @nestjs/graphql ,report:Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by rumsky** [nestjs/nest#3668]
## Current behavior
While install @nestjs/graphql ,report error: npm ERR! Unexpected end of JSON input while parsing near '...script":"3.4.5"},"pee'

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version:  v12.13.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
