### ISSUE TITLE
Execution Context #1581 marked as resolved and closed, but not fixed

### ISSUE THREAD

**Issue by Karabur** [nestjs/nest#3669]
## Bug Report

issue #1581 marked as resolved, but fix not there. 

## Current behavior
it is still 'http' on GraphQL execution context as of @nestjs/graphql@6.5.3 

## Expected behavior
having 'gql' or 'graphql' or whatever fits in GqlExecutionContext.type

**Comment by kamilmysliwiec** [comment]
We are tracking this here https://github.com/nestjs/graphql/issues/473
