### ISSUE TITLE
Bug in example

### ISSUE THREAD

**Issue by thegatheringstorm** [nestjs/nest#367]
https://github.com/nestjs/nest/blob/b6cba3784dcb266ceb18d78d43e5b18821bbed39/examples/10-mockgoose/src/database/database.providers.ts#L2

But in [Nest Docs](https://docs.nestjs.com/recipes/mockgoose)  it's `mockgoose` without `fix`

**Comment by kamilmysliwiec** [comment]
Hi @thegatheringstorm,
Thanks, I merged a pull request to the docs already, will be available soon. In the meantime, please, follow official example instead of docs snippets. 🙂

**Comment by thegatheringstorm** [comment]
@kamilmysliwiec Thanks!
