### ISSUE TITLE
Need help to identify issue 

### ISSUE THREAD

**Issue by mubasshir** [nestjs/nest#3670]
## Bug Report
App not starting.  App.listen doesn't start

## Current behaviour

App failed to start

## Input Code

```main.ts
 try {
    process.on('unhandledRejection', (err) => {
      // tslint:disable-next-line:no-console
      console.error(err); <------- no console
    });
    const app = await NestFactory.create<NestFastifyApplication>(
      AppModule,
      new FastifyAdapter(),
    );
    app.enableCors();
    app.useGlobalFilters(new AllExceptionsFilter());

    await app.listen(3000, () => {
      // tslint:disable-next-line:no-console
      console.log('listen callback'); <------- no console
    }).then(() => {
      // tslint:disable-next-line:no-console
      console.log('started'); <------- no console
    });
  } catch (error) {
    // tslint:disable-next-line:no-console
    console.log('catch', error); <----- only this gets consoled as undefined
  }
```

## Expected behaviour

The app should listen on port 3000. Or `catch` should return an error

## Environment
<pre><code>
[System Information]
OS Version     : macOS Catalina
NodeJS Version : v13.3.0
YARN Version    : 1.21.1
[Nest Information]
@nestjsx/crud-typeorm version : 4.2.0
platform-fastify version      : 6.10.11
microservices version         : 6.10.11
@nestjsx/crud version         : 4.2.0
passport version              : 6.1.0
typeorm version               : 6.2.0
common version                : 6.7.2
config version                : 0.0.7
core version                  : 6.7.2
jwt version                   : 6.1.1
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
