### ISSUE TITLE
It is inconvenient to use the names of "components".

### ISSUE THREAD

**Issue by kaluginserg** [nestjs/nest#368]
In our team, "components" are usually called "web components" (https://en.wikipedia.org/wiki/Web_Components). Or at least Angular components (also consisting of html, css and js).
I very like NestJs, but the naming convention for the "component" causes confusion and (frequently for me) inconvenience to use together with angular and other solutions.

So the idea for renaming:
`components: []` => `providers: []` (in Module declaration)
`@Component` => `@Injectable` (for Service declaration)

What do you think about it?

**Comment by kamilmysliwiec** [comment]
Hi @kaluginserg,
See here https://github.com/nestjs/nest/issues/254#issuecomment-345834627
