### ISSUE TITLE
CQRS not working with SCOPED request 

### ISSUE THREAD

**Issue by juicycleff** [nestjs/nest#3687]
## Current behavior
Calling a CQRS command or query fails when using a scoped service. In fact, if a service is scoped per request, CQRS DI just completely fails. Is this by design, or a bug or something that can be improved? If it's a bug then I can volunteer to fix it, seeing its very important in my project.

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version: v10.16.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
See https://github.com/nestjs/cqrs/issues/60

**Comment by juicycleff** [comment]
Thanks @kamilmysliwiec
