### ISSUE TITLE
Throwing HttpException with status of HttpStatus.PROCESSING causes socket hangup

### ISSUE THREAD

**Issue by cyorobert** [nestjs/nest#3690]
## Current behavior
When a `HttpException` is thrown with a status of `HttpStatus.PROCESSING` supertest/jest respond with `Error: socket hang up`. Full trace:

```
Error: socket hang up

    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Input Code

app.controller.ts
```ts
import { Controller, Get, HttpException, HttpStatus } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    throw new HttpException('processing', HttpStatus.PROCESSING);
  }
}
```

app.controller.spec.ts

```ts
import { HttpStatus } from '@nestjs/common';
import { NestExpressApplication } from '@nestjs/platform-express';
import { Test, TestingModule } from '@nestjs/testing';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import * as supertest from 'supertest';

describe('AppController', () => {
  let appController: AppController;
  let app: NestExpressApplication;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AppController],
      providers: [AppService],
    }).compile();

    app = module.createNestApplication();
    await app.init();
    appController = module.get<AppController>(AppController);
  });

  describe('root', () => {
    it('should respond with status code 102', () => {
        return supertest(app.getHttpServer())
          .get('/')
          .expect(HttpStatus.PROCESSING);
    });
  });
});
```

## Expected behavior
The request should respond with a HTTP status of 102 and not error.

## Environment

<pre><code>
Nest version: 6.10.12
 
For Tooling issues:
- Node version: 10.15.3
- Platform: OSX & Ubuntu via CircleCI

Others:

Changing the status code to anything greater than 200 seems to solve this issue. For the mean time I've resorted to using `HttpStatus.ACCEPTED` instead of `HttpStatus.PROCESSING`. Thank you!

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by cyorobert** [comment]
Hey @kamilmysliwiec thank you for taking a look at my issue. I've provided a minimal reproduction of my issue here https://github.com/cyorobert/nestjs-issue-3690.

## Steps to reproduce

- Clone the repo `git clone git@github.com:cyorobert/nestjs-issue-3690.git`
- `npm install`
- `npm test`

## About the issue

This was reproduced using the command `nest new sample`, replacing the contents of `getHello` in `app.controller.ts` with `throw new HttpException('processing', HttpStatus.PROCESSING)`, and writing an e2e test to assert that the route returns a status code of 102.

I'm not convinced this is a Nest issue. It may be an issue with express or supertest, but the error and stack trace are not specific enough to help me pinpoint why the issue occurs.

**Comment by kamilmysliwiec** [comment]
Unfortunately, this issue is not related to NestJS but rather to the platform used underneath (express/fastify depending on your app)
