### ISSUE TITLE
I use @ nestjs / schedule to run the error according to the case

### ISSUE THREAD

**Issue by JCqiu** [nestjs/nest#3709]
## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

![image](https://user-images.githubusercontent.com/16211027/71455641-ebbe0080-27d0-11ea-92f3-797e8832e3e1.png)
![image](https://user-images.githubusercontent.com/16211027/71455648-f6789580-27d0-11ea-986f-d09a56d41fe3.png)
![image](https://user-images.githubusercontent.com/16211027/71455660-fc6e7680-27d0-11ea-8597-bb47e56ca0f4.png)
![image](https://user-images.githubusercontent.com/16211027/71455668-05f7de80-27d1-11ea-9b03-300bc2aad120.png)
I use @ nestjs / schedule to run the error according to the case

**Comment by willyjchen** [comment]
I have the same issue with sample 027-scheduling.

**Comment by johnbiundo** [comment]
This appears to be an issue with running an earlier version of nest.  The `package.json` for the 027-scheduling sample specifies 6.10.9.  With that version, I get the same circular dependency error.  Upgrading to latest (6.10.12) fixes it.

**Comment by JCqiu** [comment]
@johnbiundo thank you.I got it done.
![image](https://user-images.githubusercontent.com/16211027/71495876-081e7380-288b-11ea-9d3f-71f828db61fe.png)

**Comment by sanzhardanybayev** [comment]
@johnbiundo Thanks, your solution works!
