### ISSUE TITLE
How to get non-Observable response when calling service from gRPC client?

### ISSUE THREAD

**Issue by pxmage** [nestjs/nest#3710]
I wrote a gRPC service and called it from a gRPC client

The client-side code is like: 

```javascript
@Injectable()
export class ClientService {
 
  @Client({
    transport: Transport.GRPC,
    options: {
      url: '0.0.0.0:5000',
      package: 'blahblah',
      protoPath: 'blahblah'
    },
  })
  private client: ClientGrpc
  private userService: IUserService

  onModuleInit() {
    this.userService = this.client.getService<IUserService>('UserService')
  }
  
  async test(params: ClientTestDTO): Promise<IUserMessage> { 
// ↑ I WAS EXPECTING  A PROMISE, BUT I GOT A OBSERVABLE!
    return this.userService.createUser(params)
  }
```

When I called from the client-side,  I was expecting a Promise containing my typed result, However, I got an Observable from it.

I checked the doc, and it says "all service methods return Observable" :
<img width="1239" alt="BB461FCE-D010-4129-9D85-4C5D7F4E80E0" src="https://user-images.githubusercontent.com/52536798/71476021-edfa7c00-281d-11ea-8027-e855e630dc62.png">

I got two questions: 
1. **Do all service methods return and can only return Observable when calling from gRPC client-side?**
2. **If I can get a Promise instead of an Observable, then how?**

**Comment by TrejGun** [comment]
you can try .toPromise method on Observable

**Comment by pxmage** [comment]
> you can try .toPromise method on Observable
@TrejGun  Thanks for your reply!

I tried before I submit this issue, but I hope I could **directly** get a Promise from it. Is there any way to achieve that?

The reason is that I generated `d.ts` file from my **pre-defined proto files** like this:
```javascript
    class UserService extends $protobuf.rpc.Service {
        public createUser(request: microservice.uc.IUserCreateRequest): Promise<microservice.uc.IUserMessage>;
    }
```

According to the DRY, I hope the proto files that I wrote could provide types for gRPC client to use instead of just define that it returns Observable<any>.

**Comment by TrejGun** [comment]
```
async test(params: ClientTestDTO): Promise<IUserMessage> { 
    return this.userService.createUser(params).toPromise()
  }
```

this should match your d.ts. or may be i just dont understand the problem

**Comment by pxmage** [comment]
> ```
> async test(params: ClientTestDTO): Promise<IUserMessage> { 
>     return this.userService.createUser(params).toPromise()
>   }
> ```
> 
> this should match your d.ts. or may be i just dont understand the problem

@TrejGun No because the signature of `createUser` method is
```javascript
 public createUser(request: microservice.uc.IUserCreateRequest): Promise<microservice.uc.IUserMessage>;
```
The signature says this method  returns a `Promise`, and you can't call `toPromise` on a `Promise`.

The signature is generated from `.proto` files using `protobuf.js`, and I found no library could generate a signature that returns `Observable` . (I've checked `protobuf.js` `protoc-gen-ts` etc.)

Currently, I have to rewrite the interface in client-side myself again:
```javascript
interface MyUserService {
     createUser(params: ICreateUserRequest)  Observable<any>
}
```
which violated the DRY rule, cuz I write this duplicate code that has already been declared in proto files.

**Comment by TrejGun** [comment]
i see your problem

you wont like this obviously 
```
  async test(params: ClientTestDTO): Promise<IUserMessage> { 
    const promise = this.userService.createUser(params) as unknown as Promise;
    return promise.toPromise()
  }
```
but this is the only thing i can think of about now

**Comment by pxmage** [comment]
@TrejGun Yeah, I hope I could follow DIY and don't violate the typescript type system.

But anyway thanks for your reply!

Currently, I  wrote  a workaround:
```javascript
export const promisify = <T extends object>(service: T) => {
  return new Proxy(service, {
    get: (service: any, methodName: string) => {
      return async (...params) => {
        return await service[methodName](...params).toPromise()
      }
    }
  })
}
```

and I do
```
 this.userService = promisify(this.client.getService<IUserService>('UserService'))
```
to keep the type system work

**Comment by kamilmysliwiec** [comment]
@pxmage your solution (with `promisify`) is the only supported way so far. Thanks for sharing!

**Comment by pxmage** [comment]
@kamilmysliwiec all right then, I think there might be more people get confused by the doc.

But anyway thank you for your reply.
