### ISSUE TITLE
How can i pack the production dependencies in a single fiel

### ISSUE THREAD

**Issue by SnowFlowers** [nestjs/nest#3722]
## Describe the solution you'd like

My dependencies and devDependencies can't sepreate when run my application. 
When deploy my app, I should copy all the node_modules to my container. It is a waste of my space.

## What is the motivation / use case for changing the behavior?

pro build should build all js in a file. not with node_modules

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
