### ISSUE TITLE
when i use some custom files in controller, if i run 'npm run test', it's not work

### ISSUE THREAD

**Issue by RayZoey** [nestjs/nest#3733]
## Bug Report
when i use some custom files in controller, if i run 'npm run test', it's not work ,have some error like  `Cannot find module '@/common/pipe/pagination-config.pipe' from 'grid.controller.ts'`
## ERROR

`Cannot find module '@/common/pipe/pagination-config.pipe' from 'grid.controller.ts'`
but my controller is can work ,if i want use unit test, will wrong
## CODE
spec.ts
<img width="612" alt="Snipaste_2020-01-02_11-12-53" src="https://user-images.githubusercontent.com/24807484/71650563-b2960b00-2d51-11ea-87a3-d130a842a0f4.png">

controller.ts:
<img width="675" alt="Snipaste_2020-01-02_11-13-14" src="https://user-images.githubusercontent.com/24807484/71650571-c0e42700-2d51-11ea-8632-cda96b57d0a1.png">

## ERROR MASSAGE

<img width="766" alt="123" src="https://user-images.githubusercontent.com/24807484/71650680-9ba3e880-2d52-11ea-9862-170c94d26d82.png">

**Comment by jmcdo29** [comment]
Have you added the [path mapping](https://kulshekhar.github.io/ts-jest/user/config/#paths-mapping) in your jest configuration?

Also, in the future you should ask your questions on [Discord](https://discord.gg/G7Qnnhy
) as the Issues tracker is being used to track bug and feature requests.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by RayZoey** [comment]
> 您是否在玩笑配置中添加了[路径映射](https://kulshekhar.github.io/ts-jest/user/config/#paths-mapping)？
> 
> 另外，将来，由于“问题”跟踪器已用于跟踪错误和功能请求，因此您应该在[Discord上](https://discord.gg/G7Qnnhy)提问。

Thanks. jest  is not configure.
