### ISSUE TITLE
Helmet not activating

### ISSUE THREAD

**Issue by MeStrak** [nestjs/nest#3734]
## Current behavior
I followed instructions in the documentation to use helmet.js, but after implementing it nothing happens and the X-PoweredBy header is still present. I have the following response headers:

Accept-Ranges: bytes
Content-Length: 1703
Content-Type: text/html; charset=UTF-8
Date: Thu, 02 Jan 2020 16:57:38 GMT
ETag: W/"6a7-U6UIN9ZT6oBA9gf6/2WEJFm3ZM4"
**X-Powered-By: Express**

## Input Code

```ts
import { ValidationPipe, Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

import * as helmet from 'helmet';

import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.useGlobalPipes(new ValidationPipe());
  app.use(helmet());
  app.enableCors();
  const PORT = process.env.PORT || 3000;
  Logger.log('Setting port: ' + PORT, 'info');
  Logger.log('Auth0 domain: ' + process.env.AUTH0_DOMAIN, 'Auth0');

  await app.listen(PORT);
}
bootstrap();
```

## Expected behavior
By default activating helmet should remove the X-PoweredBy header, but it is still present.

## Environment

<pre><code>
Nest version: 6.8.3

 
For Tooling issues:
- Node version: 10.16.3
- Platform:  Windows

Others:
IDE: VSCode
Package manager: Yarn
Front end: Vue.js

**Comment by Boshen** [comment]
@MeStrak Do a hard refresh, I think you're seeing a cached response.

**Comment by MeStrak** [comment]
@Boshen I tried that but I have the same result. I've stopped and restarted both Nest + front end, and did a hard refresh, as well as trying in another browser and I still see that header.

My requests are GraphQL rather than REST - could that be anything to do with it?

**Comment by Boshen** [comment]
@MeStrak 
try two things: 
1. dig into your node_modules and check if this line is being called https://github.com/helmetjs/hide-powered-by/blob/master/index.ts#L17
2. try `app.getHttpAdapter().getInstance().disable('x-powered-by')`

By looking at the issues in the helmet repo, there seems to be some problems with express and the order of middleware executions. 

And I can't reproduce this, my example setup works https://github.com/Boshen/nestjs-playground/blob/master/src/main.ts#L45

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by MeStrak** [comment]
Oops, sorry about that @kamilmysliwiec, this is the last message!

@Boshen For info I was being stupid - it is working, the headers are disabled on the backend, it was my front end server that was adding them. When I check the headers directly on the backend everything is fine.
