### ISSUE TITLE
Support Kafka subscribe fromBeginning.

### ISSUE THREAD

**Issue by raymondsze** [nestjs/nest#3739]
## Feature Request
Seems like it is unable to customise the options when the client-kafka.js subscribe a topic.
https://kafka.js.org/docs/consuming#a-name-from-beginning-a-frombeginning

## Is your feature request related to a problem? Please describe.

May be adding options.subscribe?

**Comment by kamilmysliwiec** [comment]
Sounds good! PRs are welcome.

**Comment by SkippyZA** [comment]
I have just come across the need for this too. Will see if I can put together a PR that makes sense

**Comment by theabuitendyk** [comment]
@SkippyZA Do you have a PR for this? This is blocking me too, so I can start putting together a PR if not.

**Comment by kamilmysliwiec** [comment]
Added in 6.11.9

**Comment by StevenLangbroek** [comment]
@kamilmysliwiec I think this was included in the previous Kafka setup, but not in the current ones. I've been trying to find any plans to bring this back, but haven't found any. This is an essential building block for Kappa architectures. Can you help us understand what the plans are, and if you'd be open for a PR or issue discussing potential APIs & implications?
