### ISSUE TITLE
Add tslib as helper

### ISSUE THREAD

**Issue by cojack** [nestjs/nest#3740]
## Is your feature request related to a problem? Please describe.

Maybe it's not related to a problem at all, but it will reduce amount of redundancy code from output.

## Describe the solution you'd like

So just add a tslib as a dependency and put a helper into tsconfig

## Teachability, Documentation, Adoption, Migration Strategy

It's commonly used, so I think everyone know what's about https://www.npmjs.com/package/tslib

## What is the motivation / use case for changing the behavior?

Code will be smaller, cleaner, original.

What do you think guys?

**Comment by kamilmysliwiec** [comment]
Sounds great! Would you like to create a PR(s) for this?

**Comment by cojack** [comment]
As we can see, nest have best collaborators, thanks @Boshen!
