### ISSUE TITLE
Mongoose with env config & docker not working

### ISSUE THREAD

**Issue by stonymahony** [nestjs/nest#3744]
## Bug Report
Hello,
I've come across a strange problem. 

## Current behavior
I use an env file and a ConfigService, as described in the documentation, to configure Mongoose. 
This is my **app.module.ts**.
```
import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { EnvironmentsModule } from './environments.module';
import { EnvironmentsService } from './environments.service';

@Module({
  imports: [
    MongooseModule.forRootAsync({
      imports: [EnvironmentsModule],
      useFactory: async (environmentsService: EnvironmentsService) => ({
        uri: environmentsService.get('DB_URI'),
        // uri: 'mongodb://mongo-env:27017/mongo-env',
        useFindAndModify: false,
        useNewUrlParser: true,
        autoReconnect: true
      }),
      inject: [EnvironmentsService]
    })
  ],
  controllers: [AppController],
  providers: [AppService]
})
export class AppModule {
}
```

Locally this works fine, so that's not where the error can be.

But when I deploy this setup in Docker, the following error occurs

```
Nest] 25 - 01/04/2020, 12:43:05 PM [ExceptionHandler] failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/topologies/server.js:431:11)
    at Pool.emit (events.js:210:5)
    at Pool.EventEmitter.emit (domain.js:476:20)
    at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:559:14
    at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:973:11
    at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:39:11
    at callback (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:261:5)
    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

If I write out the URI statically, the setup works again.

Why does the dynamic configuration via the ConfigService of Mongoose work locally, but not in Docker?

I am grateful for every tip!

## Environment
Minimal repo can be found [here](https://github.com/stonymahony/mongoose-env-minimal).

**Comment by Boshen** [comment]
Try your setup without nest first? And by looking at your Dockerfile / docker-compose, I'm guessing your nest service is not connected to your mongo-env service.

**Comment by stonymahony** [comment]
I can access the mongo container created this way locally, that does not seem to be the problem.

The connection should actually be made via 'depends_on' and 'links' - which sometimes works.

I have tested further, even the static Mongo URI does not always work reliably. Can't really explain this to me...

**Comment by lakshnachadha** [comment]
I can see in your docker-compose you have exported the port 3427
```
mongo-env:
    container_name: mongo-env
    restart: always
    image: mongo
    ports:
      - "3427:27017"
    volumes:
      - mongo-env-data:/data/db
    networks:
      - mongo-env
```

but in your mongo uri, you are trying to connect to port 27017. and i think thats why you are facing this issue

**Comment by stonymahony** [comment]
Since the two containers are in the same network, access can theoretically be made to any port.
Therefore not even one port would have to be published.

But since I had the same idea as you, I tried the other one - with the same result. Unfortunately this is not the solution, but thank you very much!

**Comment by bhushan629** [comment]
EnvironmentsService class, constructor not using the file path

```
export class EnvironmentsService {
  private readonly envConfig: Record<string, string>;

  constructor(filePath: string) {
    this.envConfig = dotenv.parse(
      fs.readFileSync('./config/environments/local.env')
    );
  }

  get(key: string): string {
    return this.envConfig[key];
  }
}
```

constructor should use filePath argument. and NODE_ENV environment variable should be set in docker compose.

**Comment by stonymahony** [comment]
bhushan, you have saved me countless more hours of tedious work! 

Your tip went in the right direction. 
Even when using the constructor (embarrassing bug, by the way) I get an error.
The problem is that setting NODE_ENV in the container does not work - it is `undefined`, I never expected that. Neither `set NODE_ENV`, nor the package `cross-env'` works...strange behaviour.

I will try using docker environment variables instead, as you suggested.

Thanks a lot!
