### ISSUE TITLE
Alternative DRY pattern for crud operations

### ISSUE THREAD

**Issue by Eldar-X** [nestjs/nest#3749]
## Alternative DRY pattern for crud operations
Hi, I'm trying to solve the DRY problem. I know a [crud module](https://github.com/nestjsx/crud) is available, but I'm trying to create an alternative pattern. As you know, we currently need to create at least 3-4 files for a controller in nest.js. 

1- Database definitions - schema
2- Create DTO
3- Update DTO
4- Interface

Synchronizing these files is painful when you have large objects.

Now what I'm working on is:
1- I am trying to declare mongoose schema and dto for both create and update operation with a single file.
2- Just using Nest.js controllers without moving the logic to the crud decorators.

What I was trying to do was mostly simple.
1- I used typegoose module for Mongoose schema definitions.
2- I have created a new decorator to define the operation type and validate dto correctly.

```typescript
// user.entity.ts
import { ApiProperty } from '@nestjs/swagger';
import { Injectable } from '@nestjs/common';
import { prop } from '@typegoose/typegoose';
import { IsString, IsEmail, IsDefined } from 'class-validator';

@Injectable()
export class UserEntity {
  @ApiProperty()
  @IsDefined({ groups: ['create'] })
  @IsString({ always: true })
  @prop()
  name?: string;

  @ApiProperty()
  @IsDefined({ groups: ['create'] })
  @IsString({ always: true })
  @prop()
  surname?: string;

  @ApiProperty()
  @IsString({ always: true })
  @prop()
  optionalParam?: string;
}
```

```typescript
// operation.decorator.ts
import { SetMetadata, applyDecorators, UsePipes, ValidationPipe } from '@nestjs/common';

export const Operation = (options: { type?: string; pagination?: boolean } = {}) => {
  return (target, propertyKey: string, descriptor: PropertyDescriptor) => {
    return applyDecorators(
      SetMetadata('operation', options),
      UsePipes(
        new ValidationPipe({
          transform: true,
          whitelist: true,
          skipMissingProperties: true,
          groups: [options.type || propertyKey],
        }),
      ),
    )(target, propertyKey, descriptor);
  };
};
```

```typescript
// users.module.ts
import { Module } from '@nestjs/common';
import { TypegooseModule } from 'nestjs-typegoose';
import { UsersController } from './users.controller';
import { UsersService } from './users.service';
import { UserEntity } from './entities/user.entity';

@Module({
  imports: [TypegooseModule.forFeature([UserEntity])],
  controllers: [UsersController],
  providers: [UsersService],
})
export class UsersModule {}
```

```typescript
// users.controller.ts
import { Controller, Post, Body, Put } from '@nestjs/common';
import { UserEntity } from './entities/user.entity';
import { Operation } from '../crud';

@Controller('users')
export class UsersController {
  @Post()
  @Operation({
    type: 'create', // Optional if not set method name will be used
  })
  create(@Body() user: UserEntity) {
    return user;
  }

  @Put()
  @Operation()
  update(@Body() user: UserEntity) {
    return user;
  }
}
```

There are a few things I need help:

- [ ] Group/Operation based swagger support. 
- [ ] Support for global validation pipes.

I'm not advanced developer so if you see any pitfalls or you have improvements in my idea please comment.

**Comment by kamilmysliwiec** [comment]
>  I know a crud module is available, but I'm trying to create an alternative pattern. As you know, we currently need to create at least 3-4 files for a controller in nest.js.

`@nestjsx/crud` is a package built by the community (not an official one). For more sophisticated scenarios in which you need more control over what's happening in your system, we don't recommend using libraries that wrap the entire logic behind the abstraction layer.

If you want to propose a different approach to address simple CRUD operations, I would suggest to either create an issue in this repo (nestjsx/crud) or publish another package as an alternative way to tackle this problem.
