### ISSUE TITLE
Component member is no longer supported after updating version

### ISSUE THREAD

**Issue by DavidFaizulaev** [nestjs/nest#3750]
Hello,

I've updated the version of nestjs/common from 5.4.0 to the latest 6.10.14.
Since then, the typescript complication fails with the following error:

`src/common/logger.ts(1,10): error TS2305: Module '"/builds/entities-mapper/node_modules/@nestjs/common/index"' has no exported member 'Component'.`

```
import { Component } from '@nestjs/common';
import * as bunyan from 'bunyan';
import * as _ from 'lodash';
import * as common from './common';

require('bunyan');

@Component()
export class Logger {
    private static readonly logger = bunyan.createLogger({
        name: common.PROXY_NAME,
        level: common.LOG_LEVEL,
        environment: common.ENVIRONMENT || 'test',
        serializers: {err: bunyan.stdSerializers.err}
    });

    static trace(msg: string, obj?:any){
        obj ? this.logger.trace(obj, msg) : this.logger.trace(msg);
    }
}

```

I could not find in the release notes and documentation what replaces 'Component', can you please advise how can resolve this?

Thanks.

**Comment by Boshen** [comment]
`Injectable`?

**Comment by Boshen** [comment]
There is a section on loggers, see https://docs.nestjs.com/techniques/logger

**Comment by kamilmysliwiec** [comment]
`@Component()` decorator was removed in v5. https://docs.nestjs.com/v5/migration-guide

**Comment by Pashozator** [comment]
@kamilmysliwiec update documentation, please.

**Comment by kamilmysliwiec** [comment]
Everything is up to date @Pashozator
