### ISSUE TITLE
in the service, how to use the other service who is in the same model.

### ISSUE THREAD

**Issue by xiaodiao1212** [nestjs/nest#3753]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

**Comment by xiaodiao1212** [comment]
@paolomainardi

**Comment by xiaodiao1212** [comment]
in the angular, use providedIn: 'root' to regist the model scope.

**Comment by xiaodiao1212** [comment]
@beeman @4F2E4A2E @xdamman

**Comment by 4F2E4A2E** [comment]
@xiaodiao1212 thx for creating this issue, please post a code sample for this.
