### ISSUE TITLE
ValidationPipe on Query DTO Appears to be Ignored

### ISSUE THREAD

**Issue by john-rager** [nestjs/nest#3760]
## Current behavior
Following awesome course on Nest.js at https://www.youtube.com/playlist?list=PLPF-H6Hf8xrrzXQvg3jMgotCEZ_TBlOfA.  Lesson 28 discusses validating query parameters passed via a DTO.  No matter what I try, it behaves as though the validations don't exist. I've gone over the instructions several times, and have googled the issue looking for solutions but can't get it to recognize the rules I've set up in the DTO. The controller route that is giving me trouble is getTasks() (see below).

## Input Code
Here's the code for my DTO:

```ts
import { TaskStatus } from '../task.model';
import { IsOptional, IsIn, IsNotEmpty } from 'class-validator';

export class GetTasksFilterDto {
  @IsOptional()
  @IsIn([TaskStatus.OPEN, TaskStatus.IN_PROGRESS, TaskStatus.DONE])
  status: TaskStatus;

  @IsOptional()
  @IsNotEmpty()
  search: string;
}
```

Here's the controller:

```ts
import {
  Controller,
  Get,
  Post,
  Body,
  Param,
  Delete,
  Patch,
  Query,
  UsePipes,
  ValidationPipe,
} from '@nestjs/common';
import { TasksService } from './tasks.service';
import { Task, TaskStatus } from './task.model';
import { CreateTaskDto } from './dto/create-task.dto';
import { GetTasksFilterDto } from './dto/get-tasks-filter.dto';
import { TaskStatusValidationPipe } from './pipes/task-status-validation.pipe';

@Controller('tasks')
export class TasksController {
  constructor(private tasksService: TasksService) { }

  @Get()
  getTasks(@Query(ValidationPipe) filterDto: GetTasksFilterDto): Task[] {
    if (Object.keys(filterDto).length) {
      return this.tasksService.getTasksWithFilters(filterDto);
    } else {
      return this.tasksService.getAllTasks();
    }
  }

  @Get(':id')
  getTaskById(@Param('id') id: string): Task {
    return this.tasksService.getTaskById(id);
  }

  @Post()
  @UsePipes(ValidationPipe)
  createTask(@Body() createTaskDto: CreateTaskDto): Task {
    return this.tasksService.createTask(createTaskDto);
  }

  @Patch(':id/status')
  updateTaskStatus(
    @Param('id') id: string,
    @Body('status', TaskStatusValidationPipe) status: TaskStatus,
  ): Task {
    return this.tasksService.updateTaskStatus(id, status);
  }

  @Delete(':id')
  deleteTask(@Param('id') id: string): Task {
    return this.tasksService.deleteTask(id);
  }
}
```

## Expected behavior
Expected behavior is that if I hit localhost:3000/tasks?status=CLOSED&search=, I should get validation errors because I specified a status that isn't among the accepted ones and specified an empty search string.  But instead I get an empty result array which tells me it's passing the validations and returning nothing.

## Possible Solution
None that I can think of.

## Environment

<pre><code>
Nest version: 6.7.2
class-validator: 0.11.0
 
For Tooling issues:
- Node version: 12.14.0
- Platform:  Linux

Others:
VS Code v1.41.1.
npm v6.13.4
</code></pre>

This is the first issue I've run into that's got me scratching my head.  Your team has developed an amazing framework!! :-)

**Comment by Boshen** [comment]
Take a look at https://docs.nestjs.com/techniques/validation
You need to setup validation pipe in order for it to work
```
  app.useGlobalPipes(new ValidationPipe());
```

**Comment by john-rager** [comment]
Thank you @Boshen.  I had tried adding that, but the result was the same.  I believe that turns on validation pipes for all routes, which doesn't hurt, but note in the Query decoration in my getTasks() route that I turn on validation pipes for the Query decoration specifically.

**Comment by Boshen** [comment]
@john-rager I can't reproduce your case, can you provide a test repo

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by MarluanEspiritusanto** [comment]
You also can only use `app.useGlobalPipes(new ValidationPipe({ transform: true }));` on main.ts. It's work for me 😊

**Comment by hobbydevs** [comment]
Is has not to do with the `ValidationPipe` itself. 
The mentioned issue happens, if you mark a property in the DTO `@IsOptional()`. 
Then the validation is ignored, even when a value is provided.
