### ISSUE TITLE
Running multiple microservices on the TCP transport strategy with dynamic ports

### ISSUE THREAD

**Issue by divanvb** [nestjs/nest#3763]
## Current behavior

Running multiple microservices on the TCP transport strategy with dynamic ports. I have 1 NestExpressApplication with multiple microservices in a mono repo. Running everything on the microservices on the TCP strategy uses port 3000 instead of dynamically assigning.

Using redis I don't have to specify ports / host and can just add microservices to my mono repo and set it up accordingly.

## Input Code

```ts
app.mododule
@Module( {
	imports: [
		LoggerModule,
		InterceptorsModule,
		ClientsModule.register( [
			{
				name: 'MICROSERVICE_CHANNEL',
				transport: Transport.TCP,
			},
		] ),
	],
	controllers: [AppController, ...CONTROLLERS],
	providers: [],
	exports: [],
} )
```

```ts
import { TrafficInterceptorService } from '@app/interceptors';
import { LoggerService } from '@app/logger';
import { HttpException, HttpStatus, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import * as compression from 'compression';
import { config, DotenvConfigOutput } from 'dotenv';
import { NextFunction, Request, Response } from 'express';
import * as helmet from 'helmet';
import { AppModule } from './app.module';

async function bootstrap() {
	const logger: LoggerService = new LoggerService( 'Gateway - Bootstrap' );

	try {
		/**
		 * @description Load environment variables
		 */
		const env: DotenvConfigOutput = config();

		/**
		 * @description Server Creation
		 */
		const server: NestExpressApplication = await NestFactory.create<NestExpressApplication>( AppModule );

		/**
		 * @description Security
		 */
		server.enableCors();
		server.use( helmet() );
		server.use( compression() );

		/**
		 * @description Global
		 */
		server.setGlobalPrefix( process.env.GLOBAL_PREFIX );
		server.useGlobalInterceptors( new TrafficInterceptorService() );
		server.useGlobalPipes( new ValidationPipe( { transform: true, whitelist: true, disableErrorMessages: process.env.ENVIRONMENT === 'dev' ? true : false } ) );

		/**
		 * @description Req & Res timeouts
		 */
		server.use( ( request: Request, response: Response, next: NextFunction ) => {
			request.setTimeout( 10000, () => {
				throw new HttpException( 'Server Timeout', HttpStatus.REQUEST_TIMEOUT );
			} );

			response.setTimeout( 10000 );

			next();
		} );

		/**
		 * @description OpenAPI configuration
		 */
		process.env.ENVIRONMENT === 'dev'
			? SwaggerModule.setup(
				'swagger',
				server,
				SwaggerModule.createDocument(
					server,
					new DocumentBuilder()
						.setTitle( 'Gateway' )
						.setDescription( `Gateway platform for testing & accessing APIs.` )
						.setVersion( '1.0' )
						.build(),
				),
			)
			: logger.log( `Let's hope it doesn't break` );

		/**
		 * @description Startup
		 */
		await server.listen( process.env.PORT, process.env.HOST, () => {
			logger.log( `⛩️  Gateway has started successfully - ${ process.env.HOST }:${ process.env.PORT }` );
		} );
	} catch ( error ) {
		logger.error( 'Error in bootstrap', error );
	}
}
bootstrap();

```

```ts
How I create the microservice (main.ts of microservice)
const microservice: INestMicroservice = await NestFactory.createMicroservice( AppModule, {
	transport: Transport.TCP,
} );
```

## Expected behavior

Trying to run on Express server which talks to all the microservices under on "channel"

## Environment

<pre><code>
 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/

[System Information]
OS Version     : Linux 4.19
NodeJS Version : v13.3.0
NPM Version    : 6.13.1
[Nest Information]
platform-express version : 6.10.14
microservices version    : 6.10.14
swagger version          : 4.1.2
common version           : 6.10.14
core version             : 6.10.14
Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
> Running multiple microservices on the TCP transport strategy with dynamic ports. I have 1 NestExpressApplication with multiple microservices in a mono repo. Running everything on the microservices on the TCP strategy uses port 3000 instead of dynamically assigning.

Port 3000 is being used by default. If you need to run multiple TCP microservices, you have to generate a random port and store it somewhere (to be used by clients). 

> Using redis I don't have to specify ports / host and can just add microservices to my mono repo and set it up accordingly.

Redis-based microservices are based on a completely different philosophy (each microservice connects to the same instance of a database - hence, you don't have to specify different ports)
