### ISSUE TITLE
Update to Axios 0.19.1, it's released & fixes a major bug, custom config (details inside)

### ISSUE THREAD

**Issue by iangregsondev** [nestjs/nest#3766]
## Current behavior
Passing in custom config (so they can be picked up in the interceptor) was broken in axios 0.19.0, its been a long time coming but its finally released! 0.19.1!

I send a previous report asking to be downgraded but it wasn't possible.  https://github.com/nestjs/nest/issues/3665

Now we have an official release.

The major problem about the config was this PR 

https://github.com/axios/axios/pull/2207

This has now been released (with other fixes also) here 

https://github.com/axios/axios/releases

Any chance of upgrading as this is a real blocker as our interceptors can't pick up any custom properties that you send down, they get erased :-(

To reiterate, it was broken in 0.19.0 and 0.19.1 fixes this and other things.

Thanks

**Comment by jmcdo29** [comment]
There is already a PR for this from the renovate bot: #3765. Hopefully there will be a patch with it soon

**Comment by iangregsondev** [comment]
Great - thanks !

**Comment by kamilmysliwiec** [comment]
Fixed in 6.11.0

**Comment by iangregsondev** [comment]
Thanks @kamilmysliwiec I noticed it included the 0.19.2 - which is good news as they introduced a bug with regards to XSS and having the word javascript in urls.

This was fixed in 0.19.2

Thanks!
