### ISSUE TITLE
Batching and Caching Documentation

### ISSUE THREAD

**Issue by Jonatthu** [nestjs/nest#377]
## I'm submitting a...
<pre><code>
[ x] Documentation issue or request
</code></pre>

On the documentation of Graphql there is nothing talking about Batching or Caching
https://www.npmjs.com/package/dataloader
Is there any example integrating this or get a same behavior with nestjs?

**Comment by kamilmysliwiec** [comment]
Hi @Jonatthu,
There's no documentation, yet. Please, use graphql https://github.com/nestjs/graphql repo to report any issues/concerns about graphql package.
