### ISSUE TITLE
How I can infer type of Injection?

### ISSUE THREAD

**Issue by RafaelGSS** [nestjs/nest#3772]
Hello!

I have the following structure:

```ts
// base.ts
export default abstract class Foo {
  constructor(config: ConfigType, @Inject("SOME_KEY") private example: Example) {
    // do something with config
  }
}

// impl.ts
export default class Bar extends Foo {
  constructor(@Inject("ANOTHER_KEY") private readonly service: ExampleService {
    super({ obj }); // sending `config`.
  }
}
```

But, when enable `"strictNullChecks": true` in my tsconfig, I receive the following error:

"[tsserver 2554] [E] Expected 2 arguments, but got 1."

How I can infer the injection?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
