### ISSUE TITLE
Lcov Report not showing metrics

### ISSUE THREAD

**Issue by ymoreiratiti** [nestjs/nest#3778]
## Current behavior
On execute jest coverage, the Lcov-report generated appear without the metrics
![image](https://user-images.githubusercontent.com/5731429/72076930-25186500-32d5-11ea-8b72-3d9754e8ae59.png)

## Expected behavior
Show metrics of the coverage of statements, branches, functions, and lines
![image](https://user-images.githubusercontent.com/9997953/28251462-42e736c2-6a75-11e7-9ac8-4410e511c5c7.png)

## Environment

Nest version: 6.7.2

For Tooling issues:
- Node version: 10.0.0
- Platform:  Windows 10 64 bits

Others:

It happen's on clean project. 
- nest new project
- npm run test:cov

[Coverage Folder](https://github.com/nestjs/nest/files/4040930/coverage.zip)

**Comment by kamilmysliwiec** [comment]
This looks like a Jest bug. Let's track it in their repo https://github.com/facebook/jest/issues/9388
