### ISSUE TITLE
NestFactory, InstanceLoader and NestMicroservice should use the passed Logger

### ISSUE THREAD

**Issue by Mokto** [nestjs/nest#3789]
## Is your feature request related to a problem? Please describe.
I would like the nestjs build logs to be as small as possible.

## Describe the solution you'd like
When I use `NestFactory.create` I can override the Logger so that I don't see too many logs.
It doesn't work for a microservice.

<img width="796" alt="Screenshot 2020-01-10 at 14 58 34" src="https://user-images.githubusercontent.com/5103928/72158104-c0830600-33b9-11ea-8a14-9b90cb8ec9d8.png">

(I run multiple microservices at the same time)

## Files that need to be changed

https://github.com/nestjs/nest/blob/master/packages/core/nest-factory.ts#L30
https://github.com/nestjs/nest/blob/master/packages/core/injector/instance-loader.ts#L12
https://github.com/nestjs/nest/blob/master/packages/microservices/nest-microservice.ts#L29

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by Mokto** [comment]
Creating the minimal repo made me realize this works properly....

It was a stupid mistake ;) 

Sorry about that.
