### ISSUE TITLE
Monorepo init: tsconfig.app.json missing

### ISSUE THREAD

**Issue by Nabellaleen** [nestjs/nest#3792]
## Current behavior
I've tried to init' a monorepo "from scratch" and seems it doesn't work "out of the box", as the `tsconfig.app.json` and `tslint.json` files are not created in the "root" project.

## Input Code
```
$ npx nest new backend
# ...
$ npx nest generate app frontend
# ...
$ npx nest start

 Error  Could not find TypeScript configuration file "apps/backend/tsconfig.app.json". Please, ensure that you are running this command in the appropriate directory (inside Nest workspace).
```

## Expected behavior
`npx nest start` should work out-of-the-box after the init of a monorepo, as mentionned in the doc : https://docs.nestjs.com/cli/monorepo

## Possible Solution
If I copy and edit appropriately the files from the `frontend` directory to the `backend` one, it works.

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version: v10.15.3
- Platform:  Linux Fedora 31
</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! It was a regression. Fixed in the latest version of CLI
