### ISSUE TITLE
Support the whole set of HTTP methods

### ISSUE THREAD

**Issue by GerkinDev** [nestjs/nest#3798]
## Is your feature request related to a problem? Please describe.

I can't define all HTTP methods on my controllers.

## Describe the solution you'd like

I should be able to use a decorator, pretty much like `@Get` or `@Post`, to allow & bind other HTTP verbs on a controller method. Something like `@Search('/my-path')`. Otherwise, a decorator like `@HttpMethod('SEARCH', '/my-path')` would be fine too.

## Teachability, Documentation, Adoption, Migration Strategy

On https://docs.nestjs.com/controllers#resources

> Earlier, we defined an endpoint to fetch the cats resource (GET route). We'll typically also want to provide an endpoint that creates new records. For this, let's create the POST handler:
> ```ts
> import { Controller, Get, Post } from '@nestjs/common';
> 
> @Controller('cats')
> export class CatsController {
>   @Post()
>   create(): string {
>     return 'This action adds a new cat';
>   }
> 
>   @Get()
>   findAll(): string {
>     return 'This action returns all cats';
>   }
> }
> ```
> 
> It's that simple. Nest provides the rest of the standard HTTP request endpoint decorators in the same fashion - `@Put()`, `@Delete()`, `@Patch()`, `@Options()`, `@Head()` and `@All()`. Each represents its respective HTTP request method.
> 
> In addition to those standard HTTP verbs, full support of the methods registered in the [IANA methods registry](https://www.iana.org/assignments/http-methods/http-methods.xhtml) is ensured by their own decorator (`@Search()`, `@Label()`, etc) or the `@HttpMethod('METHOD')` decorator.

## What is the motivation / use case for changing the behavior?

As mentioned in the [RFC 7231 for HTTP/1.1](https://tools.ietf.org/html/rfc7231#section-4):

>    Additional methods, outside the scope of this specification, have
>   been standardized for use in HTTP.  All such methods ought to be
>   registered within the "Hypertext Transfer Protocol (HTTP) Method
>   Registry" maintained by IANA, as defined in Section 8.1.

And here is [the IANA registry](https://www.iana.org/assignments/http-methods/http-methods.xhtml).

This specification is still valid, and is not overriden by any specification in the [RFC 7540 for HTTP/2](https://tools.ietf.org/html/rfc7540).

---

Thank you for your amazing work on this framework. I can try to give a hand for a PR :handshake:

**Comment by jmcdo29** [comment]
Looks like a small problem with implementing all the decorators could be that [fastify only supports a few mehtods](https://github.com/fastify/fastify/blob/master/lib/route.js#L8) whereas [express supports most of them](https://github.com/jshttp/methods/blob/master/index.js#L22). As Nest works with both frameworks, it could be difficult to implement something like `@Search()` that will only work with Express without throwing an error from Fastify. Just something to keep in mind, but I think it may still be doable, just larger scoped than though.

**Comment by GerkinDev** [comment]
Okay then. But is there something I can do, a trick I can use, to use proper semantics for my API ? Would you recommend me to look somewhere in the meanwhile ?

**Comment by kamilmysliwiec** [comment]
As @jmcdo29, we can't do it since these methods are not fully supported by underlying platforms.

**Comment by jmcdo29** [comment]
Thinking out loud here, would it be possible to add in the decorators for the below that Express does support under the /platform-express package and update its adapter to handle them properly? It would, of course, be now code to maintain for the Express side, but it could help some people with the development they're trying to achieve.
