### ISSUE TITLE
GRPC-Server-Side-Streaming: Missing events for error / disconnect

### ISSUE THREAD

**Issue by sjkummer** [nestjs/nest#3799]
## Current behavior
Nestjs does not inform about broken connections when using GRPC server side streaming. As a result, there is no possible way for the server no know if a GRPC streaming client is still connected. The GRPC client also does not get an event after the network connection to server becomes broken. 

Clarification 1: 
Full-Duplex-Streaming (@GrpcStreamCall) provides this events. But in GRPC-web use cases, it is not an option to use Full-Duplex streaming, since GRPC-web supports server side streaming only.

Clarification 2:
On the client-side, developers can implement workarounds like Ping-Pong mechanisms using GRPC-unary-calls. But on the server side, no such workarounds are possible.

## Input Code
This has already been discussed on the following tickets:
- https://github.com/nestjs/nest/issues/2659
- https://github.com/nestjs/nest/issues/3289
- https://github.com/nestjs/nest/issues/1414

An example repo exists at:
https://github.com/sjkummer/nestjs-grpc-stream-helloworld

## Expected behavior
For the RxJS Subject + Observable approach, an 'error' or 'completed' event should be fired as soon as the network connection between client and server becomes broken. 
https://docs.nestjs.com/microservices/grpc

**Comment by sjkummer** [comment]
@kamilmysliwiec Can you confirm the issue? (still in 'needs triage')

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/3289. https://github.com/nestjs/nest/issues/2659 and #1414 are closed already
