### ISSUE TITLE
How can I implement busboy or use custom multer for upload large file (100GB) ?

### ISSUE THREAD

**Issue by vnknowledge2014** [nestjs/nest#3813]
I want to implement busboy or multer for upload 100GB file to server using FileInterceptor, but when I make POST request upload file by Postman, nest server always timeout and not response anything message. Please help me, I need to know solution for that problem!

Many thanks nestjs team.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
