### ISSUE TITLE
Join the OpenJS Foundation

### ISSUE THREAD

**Issue by zuohuadong** [nestjs/nest#3814]
https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_PROGRESSION.md

Nest currently has few feature updates, and Ioc is not as easy to use as angular. I hope to join openjs for better development.

developer: @renovate-bot

![image](https://user-images.githubusercontent.com/11203929/72307061-0854a680-36b4-11ea-9792-1b705e5320d0.png)

**Comment by kamilmysliwiec** [comment]
> Ioc is not as easy to use as angular.

IoC is different 

We don't plan to join the foundation.
