### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by rkristelijn** [nestjs/nest#3815]
## Current behavior
```
~/nest/sample/13-mongo-typeorm(master)$
added 1133 packages from 991 contributors and audited 904245 packages in 83.988s
found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

## Input Code

```
~/nest/sample/13-mongo-typeorm(master)$ npm audit fix
npm WARN nest-typescript-starter@1.0.0 No repository field.

updated 1 package in 6.505s
fixed 4 of 4 vulnerabilities in 904245 scanned packages
```

## Expected behavior

No vulnerabilities

## Possible Solution
`npm audit fix`

## Environment

<pre><code>
Nest version: 6.11.3
 
For Tooling issues:
- Node version: v12.6.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
We are using Renovate which should automatically update handlebars to the latest version shortly.
