### ISSUE TITLE
Basic routing not working

### ISSUE THREAD

**Issue by u84six** [nestjs/nest#3821]
## Bug Report
I'm running through a basic tutorial to build a rest api using nest and can't get routing to work that's not root.

I've setup vscode on macOS catalina, ran through the installation process, and tested the default appcontroller and it works fine (i.e. I get 'Hello World' when I go to http://localhost:3000). Next, I add a new file foo.controller.ts and add the code:

`import { Controller, Get } from '@nestjs/common';

@Controller('foo')
export class FooController {

  @Get()
  getFoo(): string {
    return 'this is foo';
  }
}`

Then I load the new controller into the app module:

`import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { FooController } from './foo.controller'
import { AppService } from './app.service';

@Module({
  imports: [],
  controllers: [AppController, FooController],
  providers: [AppService],
})
export class AppModule {}`

Then when I got to http://localhost:3000/foo I get the error:
{"statusCode":404,"error":"Not Found","message":"Cannot GET /foo"}

## Environment

<pre><code>
Nest version: 6.13.3
 
For Tooling issues:
- Node version: 13.5.0
- Platform:  macOS Catalina

**Comment by Insidexa** [comment]
show output from stdout when NestJS is started
and provide example repository with your code

**Comment by u84six** [comment]
> show output from stdout when NestJS is started
> and provide example repository with your code

Example repository? What do you mean?

**Comment by u84six** [comment]
Here's the terminal output:

10:10:58 AM - File change detected. Starting incremental compilation...


10:10:58 AM - Found 0 errors. Watching for file changes.
Debugger listening on ws://127.0.0.1:9229/6b11f05f-07c0-4c39-b2b5-5a84943c2c1e
For help, see: https://nodejs.org/en/docs/inspector
[Nest] 18617   - 01/14/2020, 10:10:58 AM   [NestFactory] Starting Nest application...
[Nest] 18617   - 01/14/2020, 10:10:58 AM   [InstanceLoader] AppModule dependencies initialized +10ms
[Nest] 18617   - 01/14/2020, 10:10:58 AM   [RoutesResolver] AppController {/}: +4ms
[Nest] 18617   - 01/14/2020, 10:10:58 AM   [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 18617   - 01/14/2020, 10:10:58 AM   [NestApplication] Nest application successfully started +1ms

**Comment by Insidexa** [comment]
try restart your application

**Comment by u84six** [comment]
I killed the process, restarted vscode, started the dev server, still the same problem. Is there anything else I can look at? I'll try deleting the node_modules directory and reinstalling.

**Comment by u84six** [comment]
When in doubt, reboot. There must have been a stuck process because a machine reboot fixed the problem.

**Comment by qubiack** [comment]
@u84six did you identify this process?
