### ISSUE TITLE
@Inject() decorator - why token is optional?

### ISSUE THREAD

**Issue by jmargieh** [nestjs/nest#3824]
Hi,

Why the token parameter is optional?
and in what the use-cases `@Inject()` is used without a token?

I'm asking since, in my application I have an `@Injectable` which was configured as a provider.
but whenever I tried to inject this class as follows: `@Inject() private myClass: Class` I get the following error:

`Error: Nest can't resolve dependencies of the ResolverService (ILoggerFactory, ?). Please make sure that the argument dependency at index [1] is available in the CdmClientModule context.`

Thanks.

**Comment by kamilmysliwiec** [comment]
Because of the property-based injection, see https://docs.nestjs.com/providers#property-based-injection
