### ISSUE TITLE
cache response in controller based on Accept-Language in header

### ISSUE THREAD

**Issue by elgreatly** [nestjs/nest#3825]
I tried to cache the response from the endpoint and it works but I need to add the cache based on the Accept-Language parameter in the header 
ex: 
- if I send in header Accept-Language: en it will cache the response for only requests with Accept-Language: en 
- but if I send the request with Accept-Language: fr it should create another cache for fr language 

this is a sample of my code:

```
    @UseInterceptors(CacheInterceptor)
    @CacheTTL(60*60)
    @Get('test')
    test(language: string): Promise<string> {
        return this.testService.test(language);
    }
```
is there any way to do it like that?

**Comment by kamilmysliwiec** [comment]
See https://docs.nestjs.com/techniques/caching#adjust-tracking

**Comment by elgreatly** [comment]
Thanks @kamilmysliwiec for quick reply i tried that but i don't know how to save and get the result based on language (i mean in any variable), this don't explain in this link, 

could you give me any example for this?

**Comment by zgayjjf** [comment]
@elgreatly 
I have the same question, do you have any information? 
Besides, I'd like to get the result based on request Ip.

**Comment by elgreatly** [comment]
@zgayjjf 

i handled it by override the cache interceptor

```
@Injectable()
export class HttpCacheInterceptor extends CacheInterceptor {
	trackBy(context: ExecutionContext): string | undefined {
		const request = context.getArgByIndex(0);
		const lang = request.headers['accept-language'] || 'en';
		const httpAdapter = this.httpAdapterHost.httpAdapter;
		const isHttpApp = httpAdapter && !!httpAdapter.getRequestMethod;
		const cacheMetadata = this.reflector.get(CACHE_KEY_METADATA, context.getHandler());
		if (!isHttpApp || cacheMetadata) {
			return `${cacheMetadata}_${lang}`;
		}

		if (httpAdapter.getRequestMethod(request) !== 'GET') {
			return undefined;
		}
		return httpAdapter.getRequestUrl(request) + '_' + lang;
	}
}

```

it works fine
