### ISSUE TITLE
How to define a route with colon？

### ISSUE THREAD

**Issue by hehejiuhuizhe** [nestjs/nest#3827]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

Hello,I'm using nestjs.
I want to define some rotes like this in controller: 
/assets/{assetId}/set/device-common:encrypt-mode
/assets/{assetId}/set/device-common:auth-mode
...
Each one has its own dto.
How to deal with the ":"  ?
Thanks.

**Comment by hehejiuhuizhe** [comment]
I've found a solution,define like this:
/assets/{assetId}/set/device-common(:)encrypt-mode
It works.Is this way right?

**Comment by kamilmysliwiec** [comment]
This should be fine.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions in the future. We are using GitHub to track bugs, feature requests, and potential improvements.
