### ISSUE TITLE
ValidationPipe don't work when validate array of objects.

### ISSUE THREAD

**Issue by RayZoey** [nestjs/nest#3832]
## Current behavior

example code:

dto:
```ts
import { ValidateNested } from 'class-validator';
import { CreateGridDto } from '@/grid/dto/create-grid.dto';
import { Type } from 'class-transformer';

export class SaveAllGridDto {
  @Type(() => CreateGridDto)
  @ValidateNested({ each: true })
  public params: CreateGridDto[];
}
```
item dto:
```ts
export class CreateGridDto {
    @Expose({name: 'grid_row'})
    readonly gridRow: boolean;
    @Expose({name: 'grid_area_id'})
    readonly gridAreaId: number;
}
```
controller:
```ts
import {Expose, Transform} from 'class-transformer';
import { IsArray, IsBoolean, IsNumber, IsString } from 'class-validator';
    @Post('saveAll')
    @HttpCode(201)
    async saveAll(@Body() saveAllGridDto: SaveAllGridDto) {
        console.log(saveAllGridDto)
    }
```
requst data
```json
{
"params":[
    {
        "grid_row": 1111123,
        "grid_area_id": 12,
    }
]
}
```
## Result
i try to print  'saveAllGridDto' , it's '{}'

## Expected behavior
i hope it's will throw exception, besuce grid_row is number, not bool

## Remark
i find a issue (https://github.com/nestjs/nest/issues/1192)  like this issue, try to simulate running, result is '{}'
<pre><code>
Nest version: core: 6.10.12

 
For Tooling issues:
- Node version: v10.16.3
- Platform:  Mac OS

Others:

</code></pre>

**Comment by konraddysput** [comment]
Please transform your object. I suggest to use:
`    async saveAll(@Body(new ValidationPipe({ transform: true }) saveAllGridDto: SaveAllGridDto) {`

**Comment by kamilmysliwiec** [comment]
Please, look at these issues https://github.com/nestjs/nest/issues?utf8=%E2%9C%93&q=validationPipe+array
