### ISSUE TITLE
Tspath resolving

### ISSUE THREAD

**Issue by flobiber** [nestjs/nest#3836]
## Current behavior
If i use ts-paths with latest version. I got the following error: 

```
internal/modules/cjs/loader.js:638
    throw err;

Error: Cannot find module
```

## Input Code

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "paths": {
      "@shared": ["./../shared"]
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
