### ISSUE TITLE
Conflict when using Guard with the same class name

### ISSUE THREAD

**Issue by stvnyung** [nestjs/nest#3841]
Hello there 👋

Thanks a lot for Nest.js, I'm really loving the work that you guys are putting out there !

## Current behaviour
If we use two different guards using the same class name but different files, only the first guard met will be recognise and used (cf. repo link below).

## Input Code
Repo: https://github.com/stvnyung/nest-guard-issue
Specific commit implementing the issue: https://github.com/stvnyung/nest-guard-issue/commit/7040292e033574b80ee79aeef3f6b5c21d1611d6

In the repo, you can see `CommentController` uses `src/comment/is-owner.guard.ts` which will always fails as it returns `false`.

But because, in `app.module.ts` we declare our controller in the order `controllers: [ AppController, PostController, CommentController ]`, only the guard `src/post/is-owner.guard.ts` is actually used.

You can see that all the request will be successful on `http://localhost:3000/post` and `http://localhost:3000/comment`.

## Expected behavior
Nest.js should differentiate both guards even if they use the same name.

## Possible Solution
At least I think it should throw an error if we use two different guard with the same class name.

## Environment

<pre><code>
Nest version: 6.10.14

**Comment by kamilmysliwiec** [comment]
Hey @stvnyung!

This happens when you have guards (or any enhancers) with the same name registered in 1 module. We're tracking this issue here https://github.com/nestjs/nest/issues/789

Aside note: having classes with the exact same name in one module should be considered as a bad practice.
