### ISSUE TITLE
Upload file in NestJS not working when Nest is deployed to Google Cloud Functions

### ISSUE THREAD

**Issue by vnenkpet** [nestjs/nest#3845]
This is apparently caused by bug in GCF itself, hoewever you can make it run when you're using a different instance of multer middleware as explained this: https://stackoverflow.com/questions/47242340/how-to-perform-an-http-file-upload-using-express-on-cloud-functions-for-firebase

From what I understand though, this is not possible to achieve in current version of NestJS as it uses multer by default. 

Is there any way to make this work? 

We are experimenting with using NestJS on serverless Google Cloud and so far this seems like a blocker.

**Comment by kamilmysliwiec** [comment]
Simply write this logic on your own instead of using the built-in `FileInterceptor`.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
