### ISSUE TITLE
Set application options after application is created by factory

### ISSUE THREAD

**Issue by chapterjason** [nestjs/nest#3851]
## Describe the solution you'd like
Add a method to set the options for the application after created from the factory.
I imagine something like this:

```typescript
async function bootstrap() {
    const application = await NestFactory.create<NestExpressApplication>(ApplicationModule);
    application.setOptions({
        logger: ["log", "error", "warn"],
    });
}
```

### Drawbacks

1. The options probably won't reach underlying layers that use the `appOptions` in `Application`, cause of some calls in the constructor. (I didn't analyse it that much)
2. If the developer call the method to late, the chance of drawback 1 gets higher.

## Teachability, Documentation, Adoption, Migration Strategy
I think it is really easy to understand. A notice in the documentation could be enough.
It also brings new functionality, cause now you can get a configuration service and then set the options for the whole application from that service.

## What is the motivation / use case for changing the behavior?
The motivation is to decouple the hard coded configuration for the application.
In my application I have a configuration module, this module can serve several configurations loaded from `.json` files. Everything works fine. But for the application I have to create a bit of boilerplate and create instances twice to load it before I call the factory.

**Before:**

```typescript
async function bootstrap() {
    const environment = new ProcessEnvironment();
    const processor = new ConfigurationProcessor(environment);
    const loader = new ConfigurationLoader([path.join(__dirname, "../config")], processor);
    const { env, port } = loader.load("application.json", new ApplicationConfiguration());
    const application = await NestFactory.create<NestExpressApplication>(ApplicationModule, {
        logger: env === "prod" ? ["log", "error", "warn"] : ["log", "error", "warn", "debug", "verbose"],
    });
    await application.listen(port);
}
```

**After:**

```typescript
async function bootstrap() {
    const application = await NestFactory.create<NestExpressApplication>(ApplicationModule);
    const { env, port } = application.select(ApplicationModule).get(ApplicationConfiguration);
    application.setOptions({
        logger: env === "prod" ? ["log", "error", "warn"] : ["log", "error", "warn", "debug", "verbose"],
    });
    await application.listen(port);
}
```

**Comment by kamilmysliwiec** [comment]
```typescript
const { env } = application.get(ApplicationConfiguration);
const logLevels = env === "prod" ? ["log", "error", "warn"] : ["log", "error", "warn", "debug", "verbose"];
Logger.overrideLogger(logLevels);
```
