### ISSUE TITLE
useClass accepting a function

### ISSUE THREAD

**Issue by jacob87o2** [nestjs/nest#3863]
## Is your feature request related to a problem? Please describe.
At the moment we can instantiate a provider with different classes, i.e. depending on environment variables set, like so:
```ts
{
    provide: Provider,
    useClass: process.env.SOME_ENV === 'someValue'
        ? providerOne
        : providerTwo,
}
```
But the problem is when we want to use **ConfigService** or another provider do that. AFAIK (please correct me if I'm wrong), it's not possible with `useClass` at the moment. 

It is possible with `useFactory`, but then we have to pass all the dependencies manually.
```ts
{
    provide: Provider,
    useFactory: (configService: ConfigService, dep1: Dep1, dep2: Dep2, dep3: Dep3, dep4: Dep4) => 
        configService.get<string>('someOption') === 'someValue'
            ? new ProviderOne(dep1, dep2)
            : new ProviderTwo(dep3, dep4),
    inject: [ConfigService, Dep1, Dep2, Dep3, Dep4]
}
```
It gets even worse with provider, which itself uses property based injection.

## Describe the solution you'd like
My idea is to pass function to `useClass` that would take dependencies as arguments (like in `useFactory`), but unlike `useFactory` it would return the class, not it's instance.
```ts
{
    provide: Provider,
    useClass: (configService: ConfigService) => 
        configService.get<string>('someOption') === 'someValue'
            ? ProviderOne
            : ProviderTwo,
    inject: [ConfigService]
}
```
## What is the motivation / use case for changing the behavior?
Configuring Provider instantiation with ConfigService.

I hope this makes sense. Any comments about this idea will be appreciated! 🙂

**Comment by kamilmysliwiec** [comment]
```typescript
{
    provide: Provider,
    useClass: (configService: ConfigService) => 
        configService.get<string>('someOption') === 'someValue'
            ? ProviderOne
            : ProviderTwo,
    inject: [ConfigService]
}
```

Since all dependencies (for both providers) have to be defined either way, you can simply work around this with such a solution:

```typescript
{
    provide: Provider,
    useClass: (configService: ConfigService, providerOne: ProviderOne, providerTwo: ProviderTwo) => 
        configService.get<string>('someOption') === 'someValue'
            ? providerOne
            : providerTwo,
    inject: [ConfigService, ProviderOne, ProviderTwo]
}
```

Then, add both `ProviderOne` and `ProviderTwo` to the `providers` array. If either provider is using lifecycle hooks (assuming that these providers perform some actions on app bootstrap(?)), remove them and trigger it from the inquirer.

**Comment by jacob87o2** [comment]
@kamilmysliwiec I assume you meant `useFactory` in second example.

What about CQRS query and command handlers? They're handling the requests as soon as they're instantiated. In my example, I have single query and two different handlers, that I would like to switch using config service.

**Comment by kamilmysliwiec** [comment]
> What about CQRS query and command handlers? They're handling the requests as soon as they're instantiated. In my example, I have single query and two different handlers, that I would like to switch using config service.

This is something we should discuss separately in the `@nestjs/cqrs` repo.

> I assume you meant useFactory in second example.

Yes, my bad! Sorry
