### ISSUE TITLE
Service injected in Dynamic module can it be injected in static module too?

### ISSUE THREAD

**Issue by amit12cool** [nestjs/nest#3864]
I have been using nestjs-pino looger modules like below:- 

```
import {
  Module,
  HttpModule
} from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { APP_FILTER } from '@nestjs/core';
import { LoggerModule } from 'nestjs-pino';

import { CorrelationIdGeneratorService } from './services/helpers/generators/correlation-id-generator.service';


const correlationIdGeneratorFactory = {
  providers: [
    CorrelationIdGeneratorService,
    UniqueIdGeneratorService
  ],
  inject: [CorrelationIdGeneratorService],
  useFactory: async (correlationIdGeneratorService: CorrelationIdGeneratorService) => {
    return {
      pinoHttp: {
        genReqId: (request) => {
          correlationIdGeneratorService.generateCorrelationId(request);
          return correlationIdGeneratorService.getCorrelationId();
        },
        level: config.get('log.LEVEL'),
        useLevelLabels: true,
        base: null,
        timestamp: () => {
          return `, "time":"${new Date().toISOString()}"`;
        },
      },
    };
  }
}

@Module({
  imports: [
    LoggerModule.forRootAsync(correlationIdGeneratorFactory)
  ],
  providers: [
    CorrelationIdGeneratorService
  ],
  exports: [
    CorrelationIdGeneratorService
  ]
})
export class SharedModule { }
```

It seems when CorrelationIdGeneratorService is injected in other service the instance is totally new i.e. its different from the one injected in the LoggerModule.

Any idea, how can i inject the same instance of CorrelationIdGeneratorService  throughout my code be it dynamic or static module?

I was thinking that the singleton instance of CorrelationIdGeneratorService   will be injected throughout the code.But that is not the case.

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by amit12cool** [comment]
I have raised it here as a question sir.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by amit12cool** [comment]
@kamilmysliwiec I have raised a question here, please help.
https://stackoverflow.com/questions/59825106/nestjs-pinorequestid-to-be-used-throughout-code
