### ISSUE TITLE
HTTPS Example Not Working

### ISSUE THREAD

**Issue by ethanchiu10** [nestjs/nest#3879]
## Current behavior
The HTTPS example as shown here https://docs.nestjs.com/faq/multiple-servers does not work.

## Input Code
```ts
const httpsOptions = {
  key: fs.readFileSync('./secrets/private-key.pem'),
  cert: fs.readFileSync('./secrets/public-certificate.pem'),
};
const app = await NestFactory.create(ApplicationModule, {
  httpsOptions,
});
await app.listen(3000);
```

## Expected behavior
HTTPS should work

## Environment
<pre><code>
Nest version: 6.10.14
 
For Tooling issues:
- Node version: 12.14.0
- Platform: Linux

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by ethanchiu10** [comment]
Nevermind, I see where I got tricked up. Using this method, the https server lives on port 3000 instead of 443. Closing this issue now.
