### ISSUE TITLE
Multiple Servers and GraphQL Subscriptions

### ISSUE THREAD

**Issue by ethanchiu10** [nestjs/nest#3880]
## Current behavior
Using the multiple server way to create a server, the graphql subscription websocket connection will throw an error.

```
WebSocket connection to 'ws://localhost:3000/graphql' failed: Error during WebSocket handshake: Unexpected response code: 404
```

## Input Code
```ts
const server = express();
const app = await NestFactory.create(
  ApplicationModule,
  new ExpressAdapter(server),
);
await app.init();

http.createServer(server).listen(3000);
```

## Expected behavior
GraphQL subscription websocket connection should succesfully connect.

## Environment

<pre><code>
Nest version: 6.10.14
 
For Tooling issues:
- Node version: 12.14.0
- Platform: Linux, Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by ethanchiu10** [comment]
https://github.com/ethanchiu10/nest-issue3880

**Comment by kamilmysliwiec** [comment]
Having multiple servers with Apollo seems to be unsupported. Let's add this to the documentation. https://github.com/nestjs/docs.nestjs.com/issues/958
