### ISSUE TITLE
[Cache] trackBy function is not excecuted when using @CacheTTL() or/and @CacheKey() decorators

### ISSUE THREAD

**Issue by andrewrgbm** [nestjs/nest#3883]
I overrided `trackBy` function in HttpCacheInterceptor based on header language like [adjust-tracking](https://docs.nestjs.com/techniques/caching#adjust-tracking), but it's executed only on the first call but in the other calls after that it returned the cached data without execute `trackBy` function even if i changed the header language then it returns the data with the wrong language.

Here is sample code :

```
export class UserController{
    @UseInterceptors(HttpCacheInterceptor)
    @CacheTTL(6000)
    @Get('user')
    user(): Promise<string> {
        return this.userService.findUser();
    }
}
```

```
export class HttpCacheInterceptor extends CacheInterceptor {
    trackBy(context: ExecutionContext): string | undefined {
        const request = context.getArgByIndex(0);
        const lang = request.headers['accept-language'] || 'en';
        return lang;
    }
}
```
**Expected Behavior :** 

- When I call the endpoint with `Accept-Language=en` it should return the data and cache it then when I call it again with the same  `Accept-Language=en` it will get it from cache.
- When I call the endpoint with `Accept-Language=fr` it should return different data for `fr` and cache it then when I call it again with the same  `Accept-Language=fr` it will get it from cache.

**Actual Behavior**

- When I call the endpoint with `Accept-Language=en` it returns the english data and when I call it again it doesn't execute trackBy function and returns the cached data.
- When I call the endpoint with `Accept-Language=fr` it it returns the english cached data without executing the trackBy function.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
