### ISSUE TITLE
ConfigService Injection Stopped working Suddenly

### ISSUE THREAD

**Issue by darrenangle** [nestjs/nest#3884]
## Bug Report

Running a previously working NestJS app that uses a global ConfigModule to load the config service into various services for external API registration. After (maybe?) an `npm install` the injection of the configService has stopped altogether. 

## Current behavior

Running `npm run start:dev` produces the following error:
```
`TypeError: Cannot read property 'get' of undefined
    at new SomeService (/Users/user/code/app/build/src/some/some.service.js:19:34)
    at Injector.instantiateClass (/Users/user/code/app/node_modules/@nestjs/core/injector/injector.js:288:19)
    at callback (/Users/user/code/app/node_modules/@nestjs/core/injector/injector.js:75:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Injector.resolveConstructorParams (/Users/user/code/app/node_modules/@nestjs/core/injector/injector.js:116:24)
    at async Injector.loadInstance (/Users/user/code/app/node_modules/@nestjs/core/injector/injector.js:79:9)
    at async Injector.loadProvider (/Users/user/code/app/node_modules/@nestjs/core/injector/injector.js:36:9)
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (/Users/user/code/app/node_modules/@nestjs/core/injector/instance-loader.js:41:9)
    at async /Users/user/code/app/node_modules/@nestjs/core/injector/instance-loader.js:27:13`
```

## Input Code

This is the service in question, it's breaking on the configservice.get
```ts
@Injectable()
export class SomeService {
  apiKeyId: string | undefined;

  constructor(
    private readonly configService: ConfigService,
    private readonly http: HttpService
  ) {
    // Set api keys from env
    this.apiKeyId = this.configService.get<string>('API_KEY_ID');
```

Here's how I'm loading the module in app.module:
```ts
@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    SomeModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

And the Service's Module
```ts
@Module({
  imports: [HttpModule],
  providers: [SomeService],
  exports: [SomeService],
  controllers: [SomeController],
})

export class SomeModule {}
```

## Expected behavior

ConfigService should be available to the other services and not undefined. No code related to this flow has changed since previously working, so it feels like some kind of regression.

## Environment

<pre><code>
Nest version: check package.json

 "dependencies": {
    "@nestjs/common": "^6.10.14",
    "@nestjs/config": "0.0.8",
    "@nestjs/core": "^6.10.14",
    "@nestjs/platform-express": "^6.10.14",
    "firebase-admin": "^8.9.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.5.3"
  },
  "devDependencies": {
    "@nestjs/cli": "^6.9.0",
    "@nestjs/schematics": "^6.7.0",
    "@nestjs/testing": "^6.7.1",
    "@types/express": "^4.17.1",
    "@types/jest": "^24.0.18",
    "@types/node": "^12.7.5",
    "@types/supertest": "^2.0.8",
    "jest": "^24.9.0",
    "prettier": "^1.18.2",
    "supertest": "^4.0.2",
    "ts-jest": "^24.1.0",
    "ts-loader": "^6.1.1",
    "ts-node": "^8.4.1",
    "tsconfig-paths": "^3.9.0",
    "tslint": "^5.20.0",
    "typescript": "~3.7.0",
    "gts": "^1.1.2"
  },

 
For Tooling issues:
- Node version: v12.13.1
- Platform: Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by darrenangle** [comment]
I figured this out. I believe upgrading the `gts` package overwrote my `ts-config.json` replacing the output folder and compiling to javascript instead of typescript in the `dist/` folder as usual. Serving from this folder produced this error.
