### ISSUE TITLE
Lazy instantiation of providers

### ISSUE THREAD

**Issue by leandro-manifesto** [nestjs/nest#3886]
I would like to suggest adding lazy instatiation of providers.

From what I could find, #2587 was created asking this exact feature, but it was locked a while later for inactivity.

But the argument of allowing lazy instantiation because of serverless environments still stands. Right now I'm using Google Cloud Run as an orchestration platform for docker containers and startup times are as important as response times, but this also applies to any functions based platform. Also, in these contexts parts of the application could even never be executed.

I don't know much about NestJS's internals, but I have some ideas on how this could be exposed:
- Add a `lazy` field to provider defitinitions in the Module options
- Add a `lazy` field to the Injectable options
- Add a `LAZY_SINGLETON` Scope

**Comment by kamilmysliwiec** [comment]
Instead of lazily loading providers in a single application, we want to provide a way to dynamically create multiple lambda functions from 1 app (using decorators). You can track progress here https://github.com/nestjs/serverless-core

**Comment by leandro-manifesto** [comment]
That will be awesome for function environments.

But Google Cloud Run actually runs several server instances auto-scaled to meet demand.
The startup is the same as a long-running NestJS server, but in this case the servers are short lived.
