### ISSUE TITLE
Unable to connect to Oracle database via TypeORM

### ISSUE THREAD

**Issue by JoshWilliams92** [nestjs/nest#3888]
## Current behavior

Unable to connect to the database
'Error: ORA-12521: TNS:listener does not currently know of instance requested in connect descriptor' 

## Input Code

    TypeOrmModule.forRoot({
      type: 'oracle',
      host: 'ip address/db-name',
      port: 1521,
      username: '***',
      password: '***',
      database: '***',
      entities: [__dirname + '/**/*.entity{.ts,.js}'],
      synchronize: true,
    }),

## Expected behavior

It should be able to establish the connection to the database successfully.
Please note I am able to establish the connection via the main guide
https://oracle.github.io/node-oracledb/doc/api.html#getstarted

## Environment

- Node version: V13.7.0
- NPM version: 6.13.6
- Typescript: 3.7.5
- Nest version: 6.14.0
- Typescript version
- Platform:  Windows 64 bit OS

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the [typeorm](https://github.com/typeorm/typeorm) repository.
