### ISSUE TITLE
Why can't I use a service on a Gateway?

### ISSUE THREAD

**Issue by taksumaki** [nestjs/nest#3892]
I am trying to run a service that is in a Module (User) and I want to use it in a Gateway to execute a method but when I run the application I get an error. He tells me that a method could not be found, the Logger also doesn't work for me on the Gateway, I don't know what will happen.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
