### ISSUE TITLE
Do you have a plan to rewrite the underlying framework to Koa2？

### ISSUE THREAD

**Issue by caiya** [nestjs/nest#390]

**Comment by caiya** [comment]
If you do so, i think nestjs will be better hot.

**Comment by caiya** [comment]
docs.nestjs.com cannot access！！！

**Comment by wbhob** [comment]
No there are no plans to do so. It is built in Express and will not be rewritten. However, I encourage you to DM me on Gitter, I have some ideas that I want to share with someone and collaborate.

**Comment by kamilmysliwiec** [comment]
Hi @caiya,
If there appear any good truly express a compatible alternative, that'd provide a better performance I'd definitely consider to use it. I don't see the point to integrate with koa2 so far.
