### ISSUE TITLE
E2e Testing sometimes works, sometimes not

### ISSUE THREAD

**Issue by jakemonton** [nestjs/nest#3900]
## Current behavior

Running the default e2e script. Sometimes it works and most of the time not. Not sure what causes the issue.

## app.e2e-spec.ts

```ts
import { Test, TestingModule } from '@nestjs/testing';
import * as request from 'supertest';
import { AppModule } from './../src/app.module';
import { INestApplication } from '@nestjs/common';

describe('AppController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    console.log('app: test');
    await app.init();
  });

  it('/ (GET)', async () => {
    return request(app.getHttpServer())
      .get('/')
      .expect(200)
      .expect('Hello World!');
  });

  afterAll(async () => {
    await app.close();
  });
});

```

## Expected behavior

The test should succeed as this is the default e2e test out of the NestJs package.
 
## Tooling issues
- Nest version: 6.11.2
- Node version: 13.2.0
- NPM version: 6.13.1
- Platform: Mac

**Comment by jakemonton** [comment]
This is the error:
![Screen Shot 2020-01-24 at 6 52 14 pm](https://user-images.githubusercontent.com/2330966/73056419-b3e2cf80-3eda-11ea-8b76-e586bc2601ed.png)

**Comment by kamilmysliwiec** [comment]
I can't reproduce your issue with the starter project. 
Please, provide a minimal repository which reproduces your issue.

**Comment by jakemonton** [comment]
Hi @kamilmysliwiec my bad. Actually, it is working. I forgot I added https://github.com/nestjsx/crud to it and might be the cause of the issue. I will take a look more into it.
