### ISSUE TITLE
Undefined @Body with new core/common version 6.11.0

### ISSUE THREAD

**Issue by wjlewis** [nestjs/nest#3907]
## Bug Report

Receiving undefined `@Body` on _some_ routes when updating to `@nestjs/core` and `@nestjs/common`.

We figured this out because our builds **don't include a package-lock.json** and today the application started having issues.

```
@Put('/central/:versionId')
  async updateCentralVersion(
    @Param('versionId', ParseUUIDPipe) versionId: string,
    @Body() update: UpdateFeatureTextVersionDto,
    @UserId() modifiedBy: string,
    @Timestamp() modifiedAt: string
  ): Promise<FeatureText> {
    // HERE
    console.log(update);
    return this.featureTextsService.updateCentralVersion(
      versionId,
      update,
      modifiedBy,
      modifiedAt
    );
  }
```

## Current behavior

`// HERE` prints `undefined`

## Expected behavior

`// HERE` should print the actual body of the request.

## Possible Solution

Locally, we changed our versions of `@nestjs/core` and `@nestjs/common` to `~6.10.0` and it worked and the application works as expected.

When changing to `~6.11.0` the body is `undefined`.

## Environment

Nest version: 6.11.0
For Tooling issues:
- Node version: node:12-alpine (docker)
- Platform: node:12-alpine (docker)

**Comment by kamilmysliwiec** [comment]
Are you using express or fastify? Can you please provide a minimal repository which reproduces your issue?

**Comment by AcidSlide** [comment]
Are you having the "unknownValue" issue? If it is, it took me around 5hours to fix it but the issue is super duper weird.  There is technically no way to recreate the issue.

**Comment by kamilmysliwiec** [comment]
@wjlewis  can you test with 6.11.1?
