### ISSUE TITLE
Better ack handling of RabbitMQ messages

### ISSUE THREAD

**Issue by ssilve1989** [nestjs/nest#3908]
## Feature Request
Have Nest optionally automatically handle acknowledgements of rabbitmq messages.

## Is your feature request related to a problem? Please describe.

Setting the `prefetchCount` on a rabbitmq server setup in Nest is fairly useless without also setting `noAck: false`. Setting the `noAck` however requires us to manually handle acknowledgements on every `MessagePattern`/`EventPattern` handler, likely via an interceptor that needs to get the rabbit context and message.

I think it stands to reason that most users would think setting the `prefetchCount: 1` and using a `MessagePattern` would ensure that the Nest service only receives messages one at a time, however this is not the case due to the default `noAck: true`. 

## Describe the solution you'd like

I would like to see an option on the ServerRMQ options, perhaps called `autoAck` that implies Nest will handle acknowledgements for us based on the message handler type. i.e. EventPattern can ack immediately and MessagePattern can ack when its complete. Setting `autoAck: true`, perhaps even having it as the default, would also imply that `noAck` be set to `false`. 

## Teachability, Documentation, Adoption, Migration Strategy

Users will still be able to get the functionality of the current implementation by setting doing `autoAck: false` and `noAck: false` requiring them to handle ack'ing themselves if they so choose.

## What is the motivation / use case for changing the behavior?

My motiviation is that I believe this is the default behavior the framework should be using when it comes to RabbitMQ. It is extremely unclear that setting the `prefetchCount` does nothing and I really would have expected the framework to handle the acknowledgements for me.

I dont mind attempting to implement this myself as I already have mucked around in the Nest source when originally debugging why `prefetchCount` seemingly had no effect on my handlers.

**Comment by kamilmysliwiec** [comment]
> I would like to see an option on the ServerRMQ options, perhaps called autoAck that implies Nest will handle acknowledgements for us based on the message handler type. i.e. EventPattern can ack immediately and MessagePattern can ack when its complete.

This is the default behavior of the rmq library used underneath. Nest provides an abstraction layer that allows to declaratively define handlers for either "messages" or "events" for various transporters. Everything else remains the same as if you would interact with the library directly. We don't want to start adding more features and functionalities around transport strategies that aren't already provided & implemented by the library creators to avoid confusion. However, if you need such functionality in your application, you can either write an interceptor (as you mentioned above) OR create a custom transport strategy which extends the existing `RmqServer` (unfortunately, the docs aren't the best for this feature yet, we track it here https://github.com/nestjs/docs.nestjs.com/issues/113).

**Comment by ssilve1989** [comment]
@kamilmysliwiec Custom Transport sounds like a good solution. I look forward to updated docs. Thanks for the reply!

**Comment by johnbiundo** [comment]
For those stumbling on this issue, there's a tutorial on building custom transporters here: https://dev.to/nestjs/part-1-introduction-and-setup-1a2l

Will be working on official docs soon as well.
