### ISSUE TITLE
Application Context is not working like expected

### ISSUE THREAD

**Issue by westor21** [nestjs/nest#3910]
I want to use my nestjs application as backend application with database access, but I also want to start the same application a second time in Application Context, to do some cron jobs.
The application runs perfect in normal server mode.
2nd instance I start with parameter. I´m running in dist folder

`node main dosomething`

```
async function bootstrap() {
  if (process.argv[2] === 'dosomething') {
    const app = await NestFactory.createApplicationContext(AppModule);
   ...

```
I notice the following behavior:

- the .env file, wich I placed inside the folder, where main.js resides, is not parsed (I use "@nestjs/config": "0.0.7",)
- the 2nd instance wants to start a listener to a websocket port again, which is already running in the 1st instance (error: port is already in use)
- I get the following error:
(node:18936) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'clear' of undefined
    at AccommodationService.truncateInactiveTable$ (C:\xampp\www\uz\nx-test\dist\apps\api\main.js:152:83)

Line 152 ist this:
`return Object(rxjs__WEBPACK_IMPORTED_MODULE_7__["from"])(this.passiveRepo.clear());`

this.passiveRepo is undefined, but it should already be instantiatet in the constructor of a service in a module, which is a dependency of a module which is not a direct dependency of AppModule. 
Do I need to instantiate all needed services by hand?

Dependencies:
`AppModule -> AdminModule -> ServiceModule -> Service -> instantiate this.passiveRepo`

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by westor21** [comment]
Thank you very much for your quick response.
I tryed to strip down my project into a new repo, and I committed it here:

https://github.com/westor21/demo-nest

But currently I have another problem with that code, and I spent hours but I'm lost in finding a solution - the code looks exact (I think so) as it does in my original project and that one builds with no errors.

When I try to run this new repo, I see the following dependency problem:

[Nest] 2012   - 2020-01-26 18:47:37   [ExceptionHandler] Nest can't resolve dependencies of the TypeOrmModuleOptions (?). Please make sure that the argument ConfigService at index [0] is available in the TypeOrmCoreModule context.

Probably you will quick find where my problem may be. Could it have to do with newer Lib versions? This isn't my original package.json, so there may be other versions in many of the libraries then in my real project.

**Comment by westor21** [comment]
I found the problem, why my app service throws this undefined error (TypeError: Cannot read property 'clear' of undefined): I do some async initialisation inside the service, and that is simple not ready, when I call the service.
I would close the issue for now and validate the other problmes in the next days. And I would open new separat issues for every problem, if it is still there for me.
