### ISSUE TITLE
Dynamic MessagePattern/MessageEvent

### ISSUE THREAD

**Issue by overflowz** [nestjs/nest#3912]
## Is your feature request related to a problem? Please describe.

I want to subscribe to only certain events (which are defined in the environment variables). E.g. I'd like to subscribe only `/things/${thing_id}/event` topic, which is impossible right now.

## Describe the solution you'd like

I want to have some kind of option (lazy decorator or something) so I will be able to get the environment variable and generate a topic name from it.

## What is the motivation / use case for changing the behavior?

If I specify dynamic id for the topic (e.g. `/things/+/event`) then I'll get a lot of events that are not relevant to the current handler.

**Comment by kamilmysliwiec** [comment]
If you want to subscribe to events/messages dynamically, you should use https://docs.nestjs.com/application-context + library (e.g. mqtt) directly.

**Comment by overflowz** [comment]
That makes no sense since `Controller` decorator will be meaningless in that case, am I right?

If I get it correctly, I should subscribe to events (e.g. in mqtt) and pass them to `ApplicationContext` like `app.select(module).get(controller).method` ?

Also why this issue was closed? :)

**Comment by kamilmysliwiec** [comment]
> That makes no sense since Controller decorator will be meaningless in that case, am I right?

Correct.

> If I get it correctly, I should subscribe to events (e.g. in mqtt) and pass them to ApplicationContext like app.select(module).get(controller).method ?

No, you should subscribe to events from providers. You don't need `@nestjs/microservices` to create a microservice with NestJS.

> Also why this issue was closed? :)

We are using GitHub to track bugs, feature requests, and potential improvements. Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.

**Comment by aRusenov** [comment]
I also needed it for dynamic kafka topic names (different per environment). The way I tackled it was leveraging `Reflect.decorate` to dynamically apply a decorator at runtime. For that, we first define our custom decorator to contain the environment variable where we read the actual topic/pattern from:

```ts
export const KAFKA_TOPIC_METADATA = '__kafka-topic-candidate';

export function KafkaTopic(variable: string | keyof AppConfig): any {
  return (
    target: any,
    key: string | symbol,
    descriptor: PropertyDescriptor,
  ) => {
    Reflect.defineMetadata(
      KAFKA_TOPIC_METADATA,
      variable,
      descriptor.value,
    );
    return descriptor;
  };
```
Then apply it to the controller handler: 
```ts
@KafkaTopic('KAFKA_TOPIC_BOOK_UPDATE')
  async processMessage(
    @Payload() { value: payload }: { value: BookUpdateModel },
  ) {
    ...
  }
```

The gist of it defined in service that dynamically sets Nest's `MessagePattern` decorator:
```ts
@Injectable()
export class KafkaDecoratorProcessorService {
  constructor(
    private readonly LOG: Logger,
    private readonly appConfig: AppConfig,
  ) {
  }

  processKafkaDecorators(types: any[]) {
    for (const type of types) {
      const propNames = Object.getOwnPropertyNames(type.prototype);
      for (const prop of propNames) {
        const propValue = Reflect.getMetadata(
          KAFKA_TOPIC_METADATA,
          Reflect.get(type.prototype, prop),
        );

        if (propValue) {
          const topic = this.appConfig[propValue];
          this.LOG.log(`Setting topic ${topic} for ${type.name}#${prop}`);
          Reflect.decorate(
            [MessagePattern(topic)],
            type.prototype,
            prop,
            Reflect.getOwnPropertyDescriptor(type.prototype, prop),
          );
        }
      }
    }
  }
}
```

In my case above it's mapping the custom `KafkaTopic` decorator's value to an environment variable from my own `AppConfig` service.

And finally, in `main.ts` I simply call the decorator processor to dynamically set the `MessagePattern` with the final resolved value.
**Important**: this needs to happen before the kafka microservice is initialized:
```ts
 const app = await NestFactory.create(AppModule);
  app
    .get(KafkaDecoratorProcessorService)
    .processKafkaDecorators([AppController]);

  app.connectMicroservice({
    transport: Transport.KAFKA,
    ...
   })
```

**Comment by zub0r** [comment]
@aRusenov That worked like charm, thanks!
I used that approach to prefix listener patterns with user IDs

**Comment by binhleon** [comment]
@aRusenov hello, may you help me with TCP transport please, look like it need to use different `metadata key: KAFKA_TOPIC_METADATA` but i dont know what use for TCP. Thank you

**Comment by ChristiaanWillemsen** [comment]
When using this equivalent approach for MQTT, it doesn't subscribe to the topics that are configured. If you then manually subscribe the topic to the clientId (using the broker UI), it still delivers messages correctly though.

**Comment by kholbek** [comment]
Thank you @aRusenov, [that](https://github.com/nestjs/nest/issues/3912#issuecomment-591387376) worked for me!
