### ISSUE TITLE
Adding NanoExpress Adapter

### ISSUE THREAD

**Issue by aguerram** [nestjs/nest#3914]
Hello there community I hope you doing well I have a suggestion about adding new Nest adapter,
this new node js framework really attracted me since it's considered as one of the fastest backend frameworks (faster then fastify), moreover it consumes less resources then express or fastify.

## Feature Request
nanoexpress Adapter

## Is your feature request related to a problem? Please describe.
No, just a suggestion for fast performance

## Teachability, Documentation, Adoption, Migration Strategy
Just like other adapters work.

## What is the motivation / use case for changing the behavior?
If you check this repository you will know what I'm talking about 😄.
https://github.com/aguerram/web-frameworks

**Comment by kamilmysliwiec** [comment]
We'll consider creating an adapter in the future. For now, this package is too young

**Comment by dschewchenko** [comment]
@aguerram Also This library does not support HTTP2!

**Comment by aguerram** [comment]
Ohh I see, I was waiting for this addition, but thank you for you respond
and thank you guys from making Nestjs a great framework.
