### ISSUE TITLE
Support AWS SSM Params

### ISSUE THREAD

**Issue by omer-morad-ni** [nestjs/nest#3924]
## Is your feature request related to a problem? Please describe.
We have an issue loading configurations from remote. In this case we would like to load all the application configurations from AWS SSM params.
We have decided in the company to give a chance to NestJS and right now we have not found  any satisfying solution relating to SSM configurations.

## Describe the solution you'd like
SSM params should be loaded before the application bootstraps. For example: in order to establish mongo connection we need to fetch SSM params first, which means the first step in the application bootstrap should be trying to get SSM params, and if it fails - give the option to choose if application launches or not (maybe with fallbacks) 

## What is the motivation / use case for changing the behavior?
As said, all the credentials to Mongo and different API keys are being stored in AWS SSM system.

**Comment by bhushan629** [comment]
Hi,

if u like u can check my aws nestjs module. i have integrated it with AWS SecretsManager service. uou can extend it and support it for AWS SSM service as well

https://github.com/bhushan629/aws

Check the test cases for how to use his module

**Comment by omer-morad-ni** [comment]
> Hi,
> 
> if u like u can check my aws nestjs module. i have integrated it with AWS SecretsManager service. uou can extend it and support it for AWS SSM service as well
> 
> https://github.com/bhushan629/aws
> 
> Check the test cases for how to use his module

Thank you, I will take a look!

**Comment by kamilmysliwiec** [comment]
There are plenty of examples on how to deal with asynchronous providers in the documentation.
