### ISSUE TITLE
[Question] Turning off log messages when an application starts ?

### ISSUE THREAD

**Issue by thohoh** [nestjs/nest#393]
I hope there's some kind of environment variable that does the thing.
Here's the output I'd like to get rid of when doing e2e testing:

```[Nest] 99271   - 2018-2-4 01:41:48   [NestFactory] Starting Nest application...
[Nest] 99271   - 2018-2-4 01:41:48   [InstanceLoader] ApplicationModule dependencies initialized +17ms
[Nest] 99271   - 2018-2-4 01:41:48   [InstanceLoader] SystemModule dependencies initialized +3ms
[Nest] 99271   - 2018-2-4 01:41:48   [InstanceLoader] EnvironmentModule dependencies initialized +1ms
[Nest] 99271   - 2018-2-4 01:41:48   [InstanceLoader] LoggerModule dependencies initialized +3ms
[Nest] 99271   - 2018-2-4 01:41:48   [InstanceLoader] NodeModule dependencies initialized +1ms
[Nest] 99271   - 2018-2-4 01:41:48   [InstanceLoader] BlockchainModule dependencies initialized +3ms
```

Thanks

**Comment by wbhob** [comment]
Can you share code or other details, and follow the issue template so we can help diagnose your issue?

**Comment by thohoh** [comment]
@wbhob I apologise, right after I posted this question I actually edited it and made more informative, but it  backed up to the first state for some reason.

**Comment by wbhob** [comment]
hmmm as far as I know, there's no way to disable logging. There are a number of other issues that have expressed interest in manipulating/disabling the logger. This would be a good question to put on the survey @kamilmysliwiec . Otherwise, I don't think you can do this.

**Comment by kamilmysliwiec** [comment]
Hi @thohoh,
For now you can use a workaround:
```
Logger.setMode(NestEnvironment.TEST);
```

**Comment by chanlito** [comment]
@kamilmysliwiec any progress on this?

**Comment by cojack** [comment]
@chanlito yes, now we have a possibility to create custom Logger, then you're able to handle it by your own.
