### ISSUE TITLE
ValidationPipe coerces null/undefined to empty object

### ISSUE THREAD

**Issue by Ezard** [nestjs/nest#3930]
## Current behaviour
If passed a null/undefined object, ValidationPipe coerces it to `{}` and then attempts to validate it, even if the object is allowed to be null/undefined

## Input Code

```ts
@Query(() => [Item], { name: 'items' })
getItems(@Args({ name: 'input', type: () => ItemsInput, nullable: true }) input?: ItemsInput): Item[] {
  // 'input' is {} here, instead of undefined
}
```

## Expected behaviour
My specific use case is a nullable GraphQL input (for a query with optional parameters)
I'd like for validation to be run on the object if it's provided, and for it to be ignored if not; at the moment, however, ValidationPipe converts the value to an empty object, validates it, then returns it (assuming validation was successful). This means that business code that is expecting the value to be null/undefined does not work as expected.

## Possible Solution
This seems to be caused by the `toEmptyIfNil` function in `ValidationPipe`; I feel like there should be a way to say "skip validation for this object is it is null/undefined", probably via a class-level decorator

I had a bit of a play around trying to get it to work, but I'm not massively familiar with the workings of `reflect-metadata` which is what I was trying to make use of

## Environment

Nest version: 6.11.1

**Comment by Ezard** [comment]
Managed to fix my usage of `reflect-metadata` and get this working

Ended up being pretty simple:

Class-level decorator:
```
export const BypassValidationIfNil = () => SetMetadata('bypass-validation-if-nil', true);
```

Change to `ValidationPipe` (https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L65):
From:
```
if (!metatype || !this.toValidate(metadata)) {
```
To:
```
if (!metatype || !this.toValidate(metadata) || (isNil(value) && Reflect.getMetadata('bypass-validation-if-nil', metatype) === true)) {
```

Happy to open a PR for this if needed

**Comment by kamilmysliwiec** [comment]
This should be fixed in 6.11.2. Let me know if you face any issues

**Comment by Ezard** [comment]
@kamilmysliwiec thanks for the fast turnaround, but it doesn't appear to be fixed; as GitHub has noted above, I've submitted a PR that fixes this and adds tests for it

**Comment by kamilmysliwiec** [comment]
See my response in PR
