### ISSUE TITLE
Add language (i18n) to router

### ISSUE THREAD

**Issue by mhf-ir** [nestjs/nest#394]
i need to have route based languages for nestjs that perpend language and if not present use default language based on router.
if `en` is default language and`de` and `fr` is another languages

```
GET /cats => cats findAll() with `en` request language.
GET /en/cats => cats findAll() with `en` request language.
GET /de/cats => cats findAll() with `de` request language.
GET /fr/cats => cats findAll() with `fr` request language.
```

**Comment by wbhob** [comment]
You will need to make controllers for each language, or you can pass in language as a route parameter, like `/:language/cats`.

**Comment by mhf-ir** [comment]
good but it's bad practice ... i need to have same code in whole route of my application ... think about 30 controller and each 4 actions ... added 120 same text ... can i modify route before going to controller and remove the langauge part and pass to route header or params then call controller ? seems be the better way

**Comment by wbhob** [comment]
You could use a middleware to set a global variable, like req.lang

**Comment by kamilmysliwiec** [comment]
Hi @mhf-ir,
Please, use stackoverflow https://stackoverflow.com/questions/tagged/nestjs instead.
