### ISSUE TITLE
Licensing under a "do not harm" type of license

### ISSUE THREAD

**Issue by EmilCataranciuc** [nestjs/nest#3944]
Many open source software libraries or even software packages end up being used in systems or by organizations which don't have the interest of human well being at heart.

It might be a good idea to license nest under a "do not harm" type of license. So far I am aware of this license: https://firstdonoharm.dev But it doesn't include many specifics regarding distribution and so on (compared to GPL or MIT). Maybe a dual license would fit.

**Comment by kamilmysliwiec** [comment]
I agree with these posts:
https://github.com/symfony/symfony/issues/35490#issuecomment-579120192
https://github.com/symfony/symfony/issues/35490#issuecomment-579127850

We don't plan relicensing

**Comment by EmilCataranciuc** [comment]
Kind of sad but OK.
