### ISSUE TITLE
Multer (File Upload) is not working globally 

### ISSUE THREAD

**Issue by stolotti** [nestjs/nest#3946]
Referring to #2374 
Using .forRoot leads to compilation errors.

I've solved using @Global() and adding MulterModule to exports in app.module.ts 

Please put the instructions to use multer globally in the documentation or a ref. to the bug.
I spent a lot of time figuring out why it works flawlessly but doesn't save the file, giving no errors.
Thanks.

**Comment by kamilmysliwiec** [comment]
What compilation errors?

**Comment by kamilmysliwiec** [comment]
> Using .forRoot leads to compilation errors.

You should use `.register()` instead https://docs.nestjs.com/techniques/file-upload#default-options
