### ISSUE TITLE
Inconsistent behaviour for MessagePattern

### ISSUE THREAD

**Issue by krukru** [nestjs/nest#3954]
I have two microservices which are communicating together via MessagePattern decorator and using Kafka as their transport.
MicroserviceA sends a message (using `client.send`) to microserviceB (which has the MessagePattern decorator) and expects (but does not await) a response.
 
For this example, I am using two different implementations, which should give the same behaviour - but they do not.

Here is a short snippet of their app.controllers
```typescript
    // microservice A, app.controller.ts
    // Listens for an event and sends a message to microservice B, expects response

    @EventPattern("incoming.event.using.promise")
    public async fooUsingPromise(incomingMessage: any): Promise<void> {
        this.client.send("promise.communication", incomingMessage.value).toPromise().then((result) => {
            console.log(result);
        });
    }

    @EventPattern("incoming.event.using.rxjs")
    public async fooUsingRxjs(incomingMessage: any): Promise<void> {
        this.client.send("rxjs.communication", incomingMessage.value).toPromise().then((result) => {
            console.log(result);
        });
    }
```
```typescript
    // microservice B, app.controller.ts
    // Responds to incoming messages, simulates busy work

    @MessagePattern("promise.communication")
    public async respondWithPromise(incomingMessage: any): Promise<any> {
        return new Promise((resolve) => {
            setTimeout(() => resolve("done"), 5000); //busy work
        });
    }

    @MessagePattern("rxjs.communication")
    public respondWithObservable(incomingMessage: any): Observable<void> {
        return of("done").pipe(delay(5000)); //busy work       
    }
```
The test is now to send a burst of 5 events to "incoming.event.using.promise". 
My expected behaviour would be that microserviceA will sends all 5 requests "at the same time", microserviceB will process all 5 requests at the same time, and return all 5 responses at the same time. This does not happen, instead what happens is:

MicroserviceA sends 5 requests to microserviceB, and then waits 5 seconds for every response. (waiting for a total of 25 seconds)

When using the Observable return value, the actual behaviour aligns with my expectations:
microserviceA sends 5 requests and after 5 seconds gets all 5 responses.

My question is, why does this not work the same with promises? Note that I am never calling await.

**Comment by kamilmysliwiec** [comment]
> Note that I am never calling await.

Nest has to await your `async` method internally.

> My question is, why does this not work the same with promises? 

In this example:

```
public async respondWithPromise(incomingMessage: any): Promise<any> {
 return new Promise((resolve) => {
   setTimeout(() => resolve("done"), 5000); //busy work
  });
}
```

Your handler is busy processing the message and the method returns a result after 5 seconds (we are "awaiting" this call).

In this example on the other hand:

```
@MessagePattern("rxjs.communication")
public respondWithObservable(incomingMessage: any): Observable<void> {
    return of("done").pipe(delay(5000)); //busy work       
}
```

Your handler returns a value immediately (hence, "await" used internally resolves immediately).  We already have a stream that we can subscribe to (which happens right after the method returns a value)

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by krukru** [comment]
Hey @kamilmysliwiec, thanks for the explanation :)
Reading from the [docs](https://docs.nestjs.com/microservices/basics) I could not infer that this would be the expected behaviour. 
I am new to both nest and node, so maybe this is on me - but it seems like something really important and worth mentioning in the docs. Something like:
> Returning Promise from MessagePattern will block further requests until the promise resolves, while returning Observable will accept new requests even though the first one has not completed yet.
