### ISSUE TITLE
NATS Streaming (STAN)

### ISSUE THREAD

**Issue by Sacro** [nestjs/nest#3955]
I would like NATS streaming added back to the microservices core. 

It was added in 43da706a61df86a357212500574d2cd018e918bc but then a day later, removed via 852ce08bf320825b0e154b0623520ac596e3e1c9. 

Is there a reason it was removed?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/3960
