### ISSUE TITLE
Unable to broadcast event in websocket

### ISSUE THREAD

**Issue by cieldon32** [nestjs/nest#3958]
I want to broadcast to all clients, I use server.emit , client.emit, client.broadcast.emit, all fail.
my code:
`

    @WebSocketGateway(8080)
    export class EventsGateway implements OnGatewayConnection, OnGatewayDisconnect {
    @WebSocketServer()
    server: Server;
    users: number = 0;

    async handleConnection(client){
        // A client has connected
       this.users++;

       // Notify connected clients of current users
       this.server.emit('message', this.users);  // fail
       // client.send(this.users); // client can get the message, but just current client. I hope broadcast all clients
      // client.emit('message', this.users); // fail
     // client.broadcast.emit('message', this.users); // fail
    }

    @SubscribeMessage('events')
    onEvent(client: any, data: any) {
        console.log(this.users)
        // return client.broadcast.emit('message', {data});
        // this.server.emit('events', {data});
        // this.server.emit('message', this.users);
        // return from([data]).pipe(map((item) => ({ event: 'events', data: item })));
       // client.broadcast.emit('message', {data});
       //client.broadcast.send(this.users);
   
     }
   }

`

I fond the "https://github.com/nestjs/nest/issues/1335", but it's solution is  'client.send', not my hope.
please  tell how to broadcast all clients

**Comment by cieldon32** [comment]
I have a hack solution:
`
    async handleConnection(client: any){
    // A client has connected
    this.users++;
    if(!this.wsClients){
      this.wsClients = [client];
    } else {
      this.wsClients.push(client);
    }
    
  }

....

private broadcast(event, message: any) {
    const broadCastMessage = JSON.stringify(message);
    for (let c of this.wsClients) {
      c.send(JSON.stringify({
        event,
        data: message
      }));
    }
  }

@SubscribeMessage('events')
  onEvent(client: any, data: any) {
    this.broadcast('message', {data: this.users})
  }


`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
