### ISSUE TITLE
Support binary messages over websockets (ws)

### ISSUE THREAD

**Issue by billkidwell** [nestjs/nest#3965]
## Is your feature request related to a problem? Please describe.
The request is not related to a problem.

## Describe the solution you'd like
Use of a decorator to support a message handler for binary messages.  (e.g. @SubscribeBinary)

It may also be worthwhile to allow more control over the format of messages.  In addition to binary messages, I also need to support json messages with a different format.  If there is a way to using the existing adapter and add extensibility, that seems preferable to a custom adapter.  

## Teachability, Documentation, Adoption, Migration Strategy
Dependent on final solution.  Key points: No changes to existing code.  New decorator for binary messages.  Possibly provide a way to override the behavior of message handler binding.

## What is the motivation / use case for changing the behavior?
I require a method to handle binary data for a websocket connection.  Devices are communicating with a server via websockets.  I'd like to replace the existing solution with one based on nestjs.  Some devices communicate JSON, while others use Binary (protocol buffers).  Devices that communicate via JSON use a different format than what is prescribed by the existing ws adapter.

**Comment by kamilmysliwiec** [comment]
You can simply create an adapter for this https://docs.nestjs.com/websockets/adapter

**Comment by billkidwell** [comment]
I agree that I can create a custom adapter.  I have already started to do so.  If anyone has interest in handling binary messages, or JSON messages of a constrained nature, I'll let this be a placeholder for interest.  Looks like it is not a priority at the moment.
