### ISSUE TITLE
Authentication documentation - best practices

### ISSUE THREAD

**Issue by dnmd** [nestjs/nest#397]
## I'm submitting a...
[ ] Regression
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the motivation / use case for changing the behavior?

I see different, closed, issues regarding built-in authentication. Knowing that _authentication is hard to get right_, I started looking for best practices and guidance on the topic with regard to Nestjs. 

In the official [docs](https://docs.nestjs.com/techniques/authentication) on authentication, lines like “for demo purposes”, “hint”, etc. suggests there is not yet _one way_ of doing authentication _right_.

Loving this library, I really hope to get authentication right, together. I’ve seen similar libraries (feathersjs / loopback) having a mechanism in place providing – an optional – consistent authentication API, that does it right.

So, to get to the question(s)
- are there any / such plans for the future?
- would, more extensive documentation on this topic on how to do authentication right, be something that lie ahead of us? 

Resources found:
Passport strategies: https://github.com/Abdallah-khalil/NodeJsWithPassport
Auth0: https://github.com/cdiaz/nestjs-auth0

**Comment by cdiaz** [comment]
Hi @dnmd, I wrote the [nestjs-auth0](https://github.com/cdiaz/nestjs-auth0) example a few months ago following  [this seed project](https://github.com/auth0/node-auth0/tree/eb4c9c8858a32f55d47fa31abf9f7bea8cf52852/examples/nodejs-regular-webapp) from Auth0 and based on nestjs version 2;  But this is now [deprecated](https://github.com/auth0/node-auth0/tree/master/examples/).
(My example does not follow the best practices, however I will try to update it)

You can also review [this new repository](https://github.com/cdiaz/nest-passport/tree/master/src/auth), which approaches the [authentication recipe](https://docs.nestjs.com/techniques/authentication) published in the official nestjs documentation, using passport strategies in combination with middlewares.

I think the [authentication recipe](https://docs.nestjs.com/techniques/authentication) is the best way to do it for now, however this depends on your preferences and needs.

Good luck

**Comment by kamilmysliwiec** [comment]
Hey @dnmd,
I'm working on AuthModule, trying to provide something really extensible. Keep fingers crossed

**Comment by dnmd** [comment]
@kamilmysliwiec , we will! If you want to keep this issue open to track / report the progress or want to close it for now, feel free to do so. Thanks for the feedback so far.

**Comment by John0x** [comment]
@kamilmysliwiec what is the state of this? Need to decide whether or not to implement it on my own or just wait

**Comment by ericzon** [comment]
I'm implementing my own auth mechanism with playing together middleware + guards  but I'm missing the possibility to have a built-in method to exclude routes, as mentioned in https://github.com/nestjs/nest/issues/17

**Comment by kamilmysliwiec** [comment]
I published `@nestjs/passport` which is only a tip of the iceberg. Once I have a bit more time, I'm gonna expand this module with a bunch of useful features that should substantially reduce a boilerplate.
