### ISSUE TITLE
redirect error

### ISSUE THREAD

**Issue by nicetomeetnode** [nestjs/nest#3970]
when i use “redirect” as path in this controller,the handle function ```redirect``` does not exec
```
@Get("redirect") 
    @Redirect('https://www.baidu.com', 302)
    redirect(@Query("flag") flag) {
        console.log(flag, "----");
        if (flag === 'sina') {
            return {
                "url": "http://www.sina.com"
            }
        }
    }
```
but when i change another path ,it is ok
```
@Get("test-redirect") 
    @Redirect('https://www.baidu.com', 302)
    redirect(@Query("flag") flag) {
        console.log(flag, "----");
        if (flag === 'sina') {
            return {
                "url": "http://www.sina.com"
            }
        }
    }
```

**Comment by nicetomeetnode** [comment]
and another error is 
when i use redirect in a controller at the back，and there is nothing or function behind it. 
```
@Controller('cats')
export class CatsController {
 @Get("test-redirect")  
 @Redirect('https://www.baidu.com', 302)
}
```
it will print error like this
```
error TS1146: Declaration expected.

46     @Redirect('https://www.baidu.com', 302)
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by nicetomeetnode** [comment]
sorry ,i am in china,i could not use the Discord channel that you mention above,i can not connect to it.

**Comment by nicetomeetnode** [comment]
> Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
sorry ,i am in china,i could not use the Discord channel that you mention above,i can not connect to it.
