### ISSUE TITLE
Oprhan providers don't honor scope

### ISSUE THREAD

**Issue by marcotisi** [nestjs/nest#3974]
## Current behavior
Sharing an orphan (not included in a module) provider across modules result in provider not honoring its scope. When injecting a dependency class (`DependencyService` in the repository) inside consumers (`FirstConsumer` and `SecondConsumer`), the injected class is instantiated twice, resulting in not honoring the `DEFAULT` (Singleton) provider scope.

## Input Code
https://github.com/marcotisi/nestjs-orphan-providers
Relevant files:
- first-consumer.module.ts
- second-consumer.module.ts

The dependency has a `console.log` inside its constructor, which show you how many times it is instantiated. 
If you run the application as is, you will notice the message `Instance created` twice in console. 
The dependency is imported directly through a provider:
```ts
@Module({
  providers: [DependencyServiceProvider, FirstConsumer]
})
```
If you use a module to encapsulate the provider, you see the message only once.
You could try that by changing module definition (both inside `first-consumer.module.ts` and `second-consumer.module.ts`) to:
```ts
@Module({
  imports: [DependencyServiceModule],
  providers: [FirstConsumer],
})
```

## Expected behavior
The expected behavior would be to instantiate the class only once, and reuse it across consumers.
Otherwise, some documentation explaining why this isn't possible would be desiderable.

## Environment

<pre><code>
Nest version: 6.10.14

 
For Tooling issues:
- Node version: v10.18.0 
- Platform:  Mac & Linux 
</code></pre>

**Comment by kamilmysliwiec** [comment]
It works as expected. Please, read this chapter https://docs.nestjs.com/modules
