### ISSUE TITLE
WsException not throwing

### ISSUE THREAD

**Issue by ardyfeb** [nestjs/nest#3977]
## Current behavior
The ws exception not emit exception event, `@SubcribeMessage('exception')` never called

## Input Code
https://github.com/ardyfeb/ws-issue

## Expected behavior
Emit exception event, so we can handle it and ack the error

## Environment
```
[System Information]
OS Version     : Linux 5.3
NodeJS Version : v10.15.2
YARN Version    : 1.21.1 

[Nest CLI]
Nest CLI Version : 6.14.1 

[Nest Platform Information]
platform-socket.io version : 6.11.4
platform-express version   : 6.10.14
platform-fastify version   : 6.11.4
elasticsearch version      : 7.0.0
websockets version         : 6.11.4
passport version           : 6.1.1
swagger version            : 4.2.3
typeorm version            : 6.2.0
common version             : 6.11.4
core version               : 6.11.4
jwt version                : 6.1.1
```

**Comment by kamilmysliwiec** [comment]
`exception` is a reserved word (name of an event) used to indicate errors/exceptions. You can't use it

**Comment by ardyfeb** [comment]
I not use `exception` as event, can you please check the repository ?. The guard not throw WsException correctly

Ws Guard: https://docs.nestjs.com/websockets/guards
Base ws filter: https://github.com/nestjs/nest/blob/master/packages/websockets/exceptions/base-ws-exception-filter.ts#L32

**Comment by ardyfeb** [comment]
If i throw `WsException` inside guard, the exception is silent not like `HttpException` that return response if some exception throwed inside guard or controller

**Comment by kamilmysliwiec** [comment]
@ardyfeb you should catch exceptions on the client-side, not server-side. `@SubcribeMessage('exception')` won't be triggered by `WsException`, that wouldn't make sense
