### ISSUE TITLE
Support exchanges in RabbitMQ client

### ISSUE THREAD

**Issue by gperdomor** [nestjs/nest#3981]
## Feature Request
It would be great if exchanges were supported out of the box... In a event based system, where services communicate using a event bus in a pub/sub like pattern, RabbitMQ transport can't be used, only Redis and NATS transport, which is fine, the problem is that Redis and NATS works in a fire and forget mode, so, disconnected services will lost messages.

With exchanges, we can publish the message to an exchange and the exchange broadcast that message over some queues (each Microservices listen a different queue), so if one o more services are down, messesges will handled later because it will be retained en the queue

## Describe the solution you'd like

In the server we can have a new optional `exchange` parameter:

```typescript
const app = await NestFactory.createMicroservice(ApplicationModule, {
  transport: Transport.RMQ,
  options: {
    urls: ['amqp://localhost:5672'],
    queue: 'cats_queue',
    exchange: {
        name: 'eventbus', // put the name of the exchange
        type: 'fanout', // the exchange type
        echangeOpts: {
            durable: false
        }
    }
    queueOptions: {
      durable: false
    },
  },
});
```

In a similar way, we should be able to configure a Client to send messages to a exchange:

```typescript
ClientsModule.register([
      {
        name: 'MATH_SERVICE',
        transport: Transport.RMQ,
        options: {
          urls: ['amqp://localhost:5672'],
          exchange: {
            name: 'eventbus'
          }
        },
      },
    ]),
  ]
```
 

## Teachability, Documentation, Adoption, Migration Strategy

https://www.rabbitmq.com/tutorials/tutorial-three-javascript.html

## What is the motivation / use case for changing the behavior?

Motivation: Implement a microservices system using some kind of pub/sub communication using RabbitMQ and without lost messages

**Comment by kamilmysliwiec** [comment]
You can always extend `ServerRmq` class. We're tracking the documentation here https://github.com/nestjs/docs.nestjs.com/issues/113
