### ISSUE TITLE
NestJs mongoose statics - buld-in methods access 

### ISSUE THREAD

**Issue by inzider** [nestjs/nest#3983]
I'm trying to migrate a JS API code to NestJs. 
I can't acces the buld-in methods of mongoose from within the statics methods in my Schema. There seems no way to refer to the Schema in that context. 

Within the Schema, for the Schema.methods, I am able to access properties and mongoose build in methods whit "this".  ie: this.properties or ie: this.findById(); --> build-in methods.

But I just can't access build-in methods for the Schema.statics methods; this.find or any other builds in methods are not available under this. or this.model, this.Schema, LeadSchema. or any other way I could imagine.

Please help me find the proper way to refer to the model and access those build-in methods from Schema.statics without adding again another layer or abstraction as whit typegoose. 

----------------------------
    export const LeadSchema = new mongoose.Schema({   
    name: String,
    });

    LeadSchema.statics.advancedResult = async function() {
    try { 
          lead = await this.find();  -> this wont work but why and how to access Schema buil-in methods?
          return lead;
          } catch (error) { 
             throw new BadRequestException(`Could Find Leads`, `${error}`);
         }
    };

PS: I tried stackoverflow.com but did not found this specific situation.  
ref: https://mongoosejs.com/docs/guide.html#statics
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose#static-methods

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by inzider** [comment]
I felt mongoose is a big part of any NestJS API - those methods should be accessible under this as in typescript. Lets call that a bug... 

    // Static methods
   UserSchema.statics.findWithCompany = function(id) {
   return this.findById(id).populate("company").exec()
   }
Anyhow, thanks for the reference. Nice project.
