### ISSUE TITLE
Acknowledgments without return?

### ISSUE THREAD

**Issue by aleesaan** [nestjs/nest#3988]
Currently we can `return` some data to the acknowledgment function, like so:

Server:
 ```ts
 @SubscribeMessage('someEvent')
 public someEvent(@MessageBody() body) {
   // do stuff, then return any data to the callback function
   return 'halo';
}
```

Client:
```ts
this.socket.emit('someEvent', 'hola', console.log);
// logs 'halo'
```

However, I would like to do more after sending the acknowledgment to the client, and can't figure out if currently there is a way to do something like:

 ```ts
 @SubscribeMessage('someEvent')
 public someEvent(@MessageBody() body, callback) {
  // do some stuff, call the acknowledgment function with any data
  callback('halo');
  // do any additional stuff
}
```

Any advice is appreciated!

**Comment by kamilmysliwiec** [comment]
This is not possible. We don't plan to add this future atm.
