### ISSUE TITLE
Nest Cli service creation Class name problem

### ISSUE THREAD

**Issue by zajcman** [nestjs/nest#3989]
Nest version: 6.6.4

# I'm submitting a ***"Bug Report"***

# Current behavior
 The problem is when i create service file from command line.
When i generate service by using only name that work greate but when i want create service in directory like below  

(I want create cron service file inside service/cron directory)
![image](https://user-images.githubusercontent.com/15013936/73604800-d8a00c80-4596-11ea-86fe-9dd34cdbba17.png)

Service file is created corectry buy the class name has all  path not only class name 

![image](https://user-images.githubusercontent.com/15013936/73604867-8d3a2e00-4597-11ea-9f4c-cdbb1e1b5b7a.png)

and add wrong class name in app.module.ts

![image](https://user-images.githubusercontent.com/15013936/73604893-cb375200-4597-11ea-8aee-e1dccad5a199.png)

# Expected behavior
Insert only class name without path

**Comment by ceoro9** [comment]
@zajcman, Hello. NestJS cli has a separate [repo](https://github.com/nestjs/nest-cli). Please re-create your issue there and close the current one. Thanks.

**Comment by kamilmysliwiec** [comment]
Instead of `nest g service service\cron\cron`, you should call `nest g service service/cron/cron`
