### ISSUE TITLE
API over WebSockets ? 

### ISSUE THREAD

**Issue by tx4x** [nestjs/nest#399]
Hi,
this is rather a simple yes/no question: Do you see any problems to establish an API over websockets? Looking at the example folders it rather seems that Nest is designed for HTTP only and I am a little lost to have expose an API over HTTP but also over websockets. I actually have the same problem to expose my model to a CLI interface. 

thanks in advance. 

g

**Comment by kamilmysliwiec** [comment]
Hi @tx4x,
There're 2 ways:
1. Create a normal web app but don't expose any HTTP endpoints - use Gateways (https://docs.nestjs.com/websockets/gateways) instead. If you want to use something different than socket.io create an adapter (https://docs.nestjs.com/websockets/adapter)
2. Create nest microservice and provide your own custom transport strategy (https://docs.nestjs.com/microservices/custom-transport) with your WS logic (just 1 interface to implement).

**Comment by tx4x** [comment]
hi,
sorry but after days of trying i am back to square one. 
I still have to provide a HTTP API which is easy to do with nest.js. In particular I'm using swagger & swagger-codegen-typescript for the client interface. However, since REST somehow sucks (no progress information,...) I'd like to add now an optional websocket interface in a way where I don't need to write additional controllers/services. 

Would it be possible to call my HTTP services from within a websocket gateway ? From what I saw in the examples and user apps: 

```
    // some service method:
    @Roles('isSuperuser')
    @Permissions('load_user')
    @ApiBearerAuth()
    @HttpCode(HttpStatus.OK)
    @ApiResponse({
        status: HttpStatus.OK, type: OutDevicesDto,
        description: ''
    })
    /*@ApiResponse({ status: HttpStatus.FORBIDDEN, description: 'Forbidden.' })*/
    @ApiImplicitQuery({ name: 'q', required: false, type: String, description: 'Text for search (default: empty)' })
    @ApiImplicitQuery({
        name: 'per_page', required: false, type: Number,
        description: 'Number of results to return per page. (default: 10)'
    })
    @ApiImplicitQuery({
        name: 'cur_page', required: false, type: Number,
        description: 'A page number within the paginated result set. (default: 1)'
    })
    @ApiImplicitQuery({
        name: 'group', required: false, type: Number,
        description: 'Group id for filter data by group. (default: empty)'
    })
    @Get()
    async loadAll(){....}
```
If it's not possible to call this service methods via web-socket gateway manually, do you have suggestion to make it work ? Eventually, I  just need to re-organize a little, ie: move HTTP specific decorators like @Get/@Post,... somewhere else though. Sorry for bothering, I am just trying to get shortcuts in order to provide some REST over WebSockets but also later on provide a CLI interface for those services if possible.

any thoughts? 
thanks in advance

**Comment by tx4x** [comment]
never mind, I think I found a way:

1. write some decorators which can be used to access metadata (reflect) of a controller, eg: @AsyncApi(ws?:SocketOptions)
2. inject the controller for a gateway, eg: private readonly ws: EventsGateway
3. gateway uses controller's metadata to setup and drive an async api, eg: Reflect.getMetadata('path', ControllerClass) // can't access nestjs/common/constants btw.

Not sure this is the way but currently I currently don't see better options; Or how for instance would one notify all clients about entity updates, triggered by someones REST operation in Nest.JS ? I know ways but they turn out all very ugly and add quite some more code.

g

**Comment by lord-of-harem** [comment]
Hello,

I am looking for a framework that realizes exactly the requested functionality, to have exposed the methods via REST and WebSocket.

I would prefer Nest, but I find [Feathers](https://feathersjs.com) that does exactly the functionality. Ideally, Nest offers the same thing.
