### ISSUE TITLE
Apollo upload

### ISSUE THREAD

**Issue by WillSquire** [nestjs/nest#4000]
I'm looking to upload files using Apollo and wondered if there's a best practise way to use this inside of nestjs? Can't see documentation from GrouphQL uploads on the site, but noticed the GraphQL module passes through the upload typings:
```
uploads: {
  maxFileSize: 10000000,
  maxFiles: 5
}
```

There's a few posts around using `graphql-upload` along with the config above to get it working. I tried this and it worked initially, but no longer seems to so I'm not sure if there was a different recommended way?

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by WillSquire** [comment]
This is a feature request. The request is for documentation on using Apollo's Upload feature to be added.
