### ISSUE TITLE
Unable to use rediss protocol with microservices

### ISSUE THREAD

**Issue by d-y-charpen** [nestjs/nest#4001]
## Current behavior
I'm trying to use Redis Transport for my microservice, hosted on Azure, but cannot pass a URL with the correct protocol, receiving this message:
`node_redis: WARNING: You passed "rediss" as protocol instead of the "redis" protocol!`
After which I receive intermittent disconnects due to not using the correct protocol.

## Input Code
```main.ts
const redisURL = `${'rediss://' +
      process.env.TRANSPORT_REDIS_HOST +
      ':' +
      process.env.TRANSPORT_REDIS_PORT +
      '?password=' +
      process.env.TRANSPORT_REDIS_PASSWORD +
      ',ssl=True,abortConnect=False' }`;

const app = await NestFactory.createMicroservice(AppModule, {
    transport: Transport.REDIS,
    options: {
      url: redisURL,
      retryAttempts: 5,
      retryDelay: 3000,
    },
  });

app.listen(() => console.log('Microservice is listening'));
```

## Expected behavior
A stable connection using SSL.

## Possible Solution
It looks like node_redis was [out of date](https://github.com/NodeRedis/node_redis/issues/1458#issue-490761927) as of relatively recently but their README seems to suggest that `rediss` should be usable, so I'm not sure if there's a dependency whose version I should increase?

## Environment

<pre><code>
Nest version: 6.11.5
 
For Tooling issues:
- Node version: 13.7.0 (latest)
- Platform:  Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Actually, we're planning to migrate to `ioredis` soon. See related issues:
https://github.com/nestjs/nest/issues/1048
https://github.com/nestjs/nest/issues/3960
