### ISSUE TITLE
Route not called, if request body parsed in middleware

### ISSUE THREAD

**Issue by amit12cool** [nestjs/nest#4002]
I have been experiencing an issue in nestjs where in parsing the request body in middleware results in route NOT called, hence the api hangs.

Here is the link to sample code:- 

https://github.com/amit12cool/testMiddleware/blob/master/src/middlewares/request-body-parser.middleware.ts

If line no. 11 in ```testMiddleware/src/middlewares/request-body-parser.middleware.ts``` is commented, then everything will work and route will be called. But if not, the request hangs as route is not called.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by amit12cool** [comment]
@kamilmysliwiec this is not fair.I think it's a bug that's why I have raised it here.

**Comment by amit12cool** [comment]
@kamilmysliwiec it seems like you want to just increase the closed issue count to show the community, sadly this not helping the community.

**Comment by kamilmysliwiec** [comment]
@amit12cool this is not a bug. I would love to point everyone's issues in their codebases, but unfortunately, I also have a limited amount of time in my life.
