### ISSUE TITLE
Redis Brocker TLS not working

### ISSUE THREAD

**Issue by sanjitbauli** [nestjs/nest#4006]
## Current behavior
I am using Redis as transport, it is working fine on my local machine, but when i deploy my app to the Kubernetes cluster, the Redis connection fails. `Retry time exhausted: `rediss://admin:xxxxx`, is it because of TLS as you can see my connection string starts with `rediss://`

## Expected behavior
It should connect redis as expected.

## Possible Solution
Maybe add TLS support or a way to supply the cert.

## Environment
Production

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
