### ISSUE TITLE
💥 While using NestJS to create API's I was wondering which is the best way to handle errors/exception. I have found two different approaches .

### ISSUE THREAD

**Issue by yonicb** [nestjs/nest#4008]
While using NestJS to create API's I was wondering which is the best way to handle errors/exception. I have found two different approaches .

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
