### ISSUE TITLE
Extract core decorators into a separate package

### ISSUE THREAD

**Issue by spion** [nestjs/nest#4012]
## Is your feature request related to a problem? Please describe.

We're migrating from another framework to NestJS and we would like to build shared modules that work in both frameworks during the transition. However, adding a peer dependency on the entire framework seems heavy-handed and it means that all of the services that use the shared modules would have to declare NestJS as a dependency. Additionally, some of the components are meant to be reused on the client-side too, which means that they can't depend on node-specific things too much.

## Describe the solution you'd like

It looks like the injectable and module decorators, as well as their constants, are completely independent of the rest of NestJS as they only define metadata. It would be great if they can be extracted into a separate module that is independently versioned. I glanced at the commit history and it seems this module has been very stable for a while - those decorators haven't changed in a backward-incompatible way for a couple of years.

## Teachability, Documentation, Adoption, Migration Strategy

No migration strictly necessary, new modules will be able to import the e.g. module and injectable decorators from `@nestjs/decorators` and only list that one as a (peer) dependency, old modules can continue to use the re-export 

## What is the motivation/use case for changing the behavior?

We would more easily be able to define a shared module for things such as e.g. JWT scope and role validation that work across multiple micro-services using two different (but similar) frameworks.

I believe this might increase NestJS adoption in general as the cost of adding support for loading a package as a Nest component will become much lower.

**Comment by kamilmysliwiec** [comment]
We discussed the packages structure plenty of times already (you can find more details in old issues) and we don't plan to introduce any breaking changes. The current API is considered stable. Every NestJS package which leverages decorators should define `@nestjs/common` as a peer dependency (which shouldn't be a big deal btw, the package size is 297kb). Having `@nestjs/common` registered as a peer dependency won't lead to any conflicts with other libraries/frameworks.

**Comment by spion** [comment]
Thanks for the quick response.

Adding a 297kb dependency which pulls RxJS and axios to a package that could be reusable on the front-end might be a non-starter in some cases.

No migration would be necessary as `nestjs/common` would continue to re-export the decorators

I understand however that this might be a done-deal topic already. I'll search through the relevant issues and try to find out more about the reasons behind the decisions.

Would you say it would be safe to manually implement the decorators that generate identical metadata keys and values to what NestJS currently does? Are the Reflect.metadata keys and values likely to change at this point?

**Comment by kamilmysliwiec** [comment]
> Are the Reflect.metadata keys and values likely to change at this point?

This is very unlikely :)
