### ISSUE TITLE
Injection within custom validator

### ISSUE THREAD

**Issue by galwa** [nestjs/nest#4013]
I am trying to use a custom validator that would have the service injected per module

```
@Module({
    imports: [  TypeOrmModule.forFeature([EntityA,]) ],
    controllers: [AController],
    providers: [
        AService,
        {provide: 'SERVICE', useClass: AService},
        UniqueField
    ]
}) export class AModule {}
```

and an equivalent B module with {provide: 'SERVICE', useClass: BService},

```
@ValidatorConstraint({ name: 'uniqueField', async: true })
export class UniqueField implements ValidatorConstraintInterface {
    constructor( @Inject('SERVICE') private readonly service ) {
            console.log("UniqueField:Constructor: "+this.service.constructor.name );
    }

    async validate(value: any, args: ValidationArguments ) {
            console.log("UniqueField:validate: "+this.service.constructor.name );
    }
}
```

I made sure to set up the main.ts with 
`validator.useContainer(app.select(AppModule), {fallbackOnErrors: true});`

The result : 
//for controller A
UniqueField:validate: AService
//for controller B
UniqueField:validate: AService

It looks like the Class-validator does not resolve the context correctly ?

**Comment by kamilmysliwiec** [comment]
`validator.useContainer()` is just a workaround. Custom validators DI isn't compatible with NestJS scoping.
