### ISSUE TITLE
No data emitted for HttpService request with responseType: 'stream'

### ISSUE THREAD

**Issue by 3fd** [nestjs/nest#4014]
## Potential Commit/PR that introduced the regression**

https://github.com/nestjs/nest/pull/3777

## Describe the regression

No data is emitted for a HttpService request with responseType set to 'stream'. Readstream gets closed immediately.

## Input Code

```ts
import { HttpService } from '@nestjs/common';
import { createWriteStream } from 'fs';

new HttpService().get('http://bit.ly/2mTM3nY', { responseType: 'stream' }).subscribe({
  next: (response) => {
    response.data.pipe(createWriteStream('ada_lovelace.jpg'));
  },
});
```

## Expected behavior/code

Behavior should be equivalent to running:

```js
const axios = require('axios');
const fs = require('fs');

axios({
  method: 'get',
  url: 'http://bit.ly/2mTM3nY',
  responseType: 'stream',
}).then(function(response) {
  response.data.pipe(fs.createWriteStream('ada_lovelace.jpg'));
});
```
## Environment
<pre><code>
Nest version: 6.10.11 -> 6.11.6

For Tooling issues:
- Node version: 12.14.0  
- Platform: Linux 

Others:

</code></pre>

**Comment by Boshen** [comment]
Interesting, looking into it.

**Comment by Boshen** [comment]
After some testing, I've found that it's going to be a lot of code to support node stream and request cancellation. So one rather simple solution is just to skip request cancellation with 
```
              if (config.responseType !== 'stream') {
                cancelSource.cancel();
              }
```
I’ll make a PR if this is acceptable.
