### ISSUE TITLE
@MessagePattern not working as expected

### ISSUE THREAD

**Issue by rhlsthrm** [nestjs/nest#4017]
## Describe the regression
I'm using a very simple `@MessagePattern()` controller. The controller is an async request-response, and returns results fetched from a repository.:

```ts
@Controller()
export class AppRegistryController {
  constructor(private readonly appRegistryRepository: AppRegistryRepository) {}

  @MessagePattern("app-registry")
  async get(
    data: { name?: string; chainId?: number; appDefinitionAddress?: string } | undefined,
  ): Promise<AppRegistry[]> {
    if (data && data.chainId && data.name) {
      return [await this.appRegistryRepository.findByNameAndNetwork(data.name, data.chainId)];
    }

    if (data && data.appDefinitionAddress) {
      return [await this.appRegistryRepository.findByAppDefinitionAddress(data.appDefinitionAddress)];
    }
    return await this.appRegistryRepository.find();
  }
}
```

This was working fine on Nest 6.5.3. I am trying to upgrade to Nest 6.11.6, but now this controller is no longer working. I can see that Nest receives the input message, but never publishes the response.

This is my test code:

```ts
import { connect } from "ts-nats";

async function start(): Promise<void> {
  const nc = await connect({ servers: ["nats://localhost:4222"] });
  const req = await nc.request("app-registry", 10000, JSON.stringify({ id: "myid2" }));
  console.log("req: ", req);
}

start();
```

The above code always times out.

## Input Code
Above.

## Expected behavior/code
Expect to receive a response from Nest back to my client.

## Environment
<pre><code>
Nest version: 6.5.3 -> 6.11.6

For Tooling issues:
- Node version: v10.18.1
- Platform:  Mac

Others:

</code></pre>

**Comment by rhlsthrm** [comment]
Created a minimal test repo for this issue: https://github.com/rhlsthrm/nest-microservice-regression

**Comment by johnbiundo** [comment]
@rhlsthrm We did introduce a change in 6.11.6,  It's possibly related, but on quick review, I'm unclear why that would cause this problem.  I'll look further.  In the mean time, please try updating your `main.ts` to this, which I believe fixes the problem:

```typescript
import { NestFactory } from '@nestjs/core';
import { Transport } from '@nestjs/microservices';
import { AppModule } from './app.module';

import { ConsumerDeserializer, IncomingRequest } from '@nestjs/microservices';

class IdDeserializer implements ConsumerDeserializer {
  deserialize(value: any): IncomingRequest {
    return value;
  }
}

async function bootstrap() {
  const app = await NestFactory.createMicroservice(AppModule, {
    transport: Transport.NATS,
    options: {
      servers: ['nats://localhost:4222'],
      deserializer: new IdDeserializer(),
    },
  });
  app.listen(() => console.log('Microservice is listening'));
}
bootstrap();
```

**Comment by rhlsthrm** [comment]
That did fix the issue thanks for the response @johnbiundo!

**Comment by johnbiundo** [comment]
@rhlsthrm I tested in 6.11.5 and the problem still exists, so it's (apparently) unrelated to the 6.11.6 change.  Can you confirm it works in 6.5.3?  That would indicate a regression in between -- I only started looking at `@nestjs/microservices` in the last month, so I'm not sure what may have changed.  If you confirm, I'll see if I can figure that out.

**Comment by johnbiundo** [comment]
@rhlsthrm BTW, that is probably not a super-robust fix.  Depending on what you're trying to do, you may need to build a better deserializer. As it happens, I'm going to publish an article on this topic in the next few days.  I'll try to remember to post here, but you can follow me on dev.to (or the nestjs channel on dev.to) to see when that publishes.

**Comment by rhlsthrm** [comment]
Can you explain a little about what issues we might run into with using this deserializer? Assuming we could have a scenario with lots of clients communicating with the server over NATS.

**Comment by rhlsthrm** [comment]
> Can you confirm it works in 6.5.3? That would indicate a regression in between -- I only started looking at @nestjs/microservices in the last month, so I'm not sure what may have changed. If you confirm, I'll see if I can figure that out.

My example repo didn't seem to work without the deserializer when using 6.5.3.

**Comment by johnbiundo** [comment]
@rhlsthrm it depends on a few things.  Does the `id` field you're passing in have meaning in your external requestor, or is it just there to satisfy the Nest requirement?  If the latter, you might want to try a deserializer like this.  This one should work with any arbitrary message without requiring a faux `id` field.  If you **do** have meaningful external `id`'s, we'd need to work on something a little different. This one should also handle the case where you are sending in an event from the external system (internally in Nest, events don't have `id` fields).  What it **won't** handle is a mixture of Nest requestors (e.g., `ProxyClient#request(...)`) and non-Nest requestors.  I do cover that case in the upcoming article.

```typescript
// need to add `import * as uuid from 'uuid/v4';`
class InboundMessageExternalDeserializer implements ConsumerDeserializer {
  deserialize(value: any, options?: Record<string, any>) {
    /**
     * Here, we merely wrap our inbound message payload in the standard Nest
     * message structure.
     */
    return {
      pattern: undefined,
      data: value,
      id: options && options.replyTo ? uuid() : undefined,
    };
  }
}
```

To get into more detail will require diving into some more background, which is exactly what I'm doing in the blog post series I'm readying to publish.

**Comment by rhlsthrm** [comment]
> Does the id field you're passing in have meaning in your external requestor, or is it just there to satisfy the Nest requirement? If the latter, you might want to try a deserializer like this.

Correct, we don't depend on the ID field at all. I followed you on dev.to, looking forward to reading the article and more advanced Nest content!

**Comment by johnbiundo** [comment]
Great!  Part 1 went up just now.  https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-1-p3

Part 2 will go up tomorrow, and Part 3 shortly after.

**Comment by johnbiundo** [comment]
This article covers this topic in detail: https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-1-p3
