### ISSUE TITLE
Wrong response structure while performing e2e test

### ISSUE THREAD

**Issue by omer-morad-ni** [nestjs/nest#4018]
## Current behavior
In my main nest application I use an interceptor which transforms the response into different structure, here it is:

```ts
export interface Response<T> {
  content: T;
}

@Injectable()
export class TransformInterceptor<T> implements NestInterceptor<T, Response<T>> {
  intercept(context: ExecutionContext, next: CallHandler): Observable<Response<T>> {
    return next.handle().pipe(map(data => ({ content: data })));
  }
}
```

When trying to test the application, the response body, I get only the `response.text` property and `response.body` is undefined.

Here is the code:

```ts
it('/ (GET)', async done => {
  const res = await request(app.getHttpServer()).get('/tips/fetch');

  expect(res.body.content).toBe('1 tip entities');
  expect(res.status).toBe(HttpStatus.CREATED);

  done();
});
```

## Expected behavior
the `res` object should contain `body` property (`res.body`) which includes the structure that was defined in the interceptor, something like `res.body.content`, but it seems like the part of `app.getHttpServer()` is ignoring the interceptor so the only thing I get is `response.text` property

## Environment
<pre>
"@nestjs/common": "^6.11.5"
"@nestjs/config": "^0.1.0"
"@nestjs/core": "^6.11.4"
"@nestjs/platform-express": "^6.7.2"
</pre>

- Node version: 10.17.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
