### ISSUE TITLE
Controller prefix not working, can't create route with given prefix

### ISSUE THREAD

**Issue by ichn-hu** [nestjs/nest#4028]
## Current behavior

![not-working](https://user-images.githubusercontent.com/29735669/74172878-f8f15a80-4c6b-11ea-91d2-c8afd196c9c8.png)

## Input Code

Use `nest n proj` to create a blank project and change `src/app.controller.ts` into (just add prefixes)

```ts
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller('cat')
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('good')
  getHello(): string {
    return this.appService.getHello();
  }
}
```

## Expected behavior

`getHello` routed to `/cat/good`, however it is routed to `/good` and the `cat` prefix is ignored.

## Environment

<pre>
➜  project-name git:(master) ✗ nest -v
6.14.2
<code>
Nest version: 6.14.2

 
For Tooling issues:
- Node version: v13.8.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by JustinR93** [comment]
So you get the result you are expecting at the `/good` endpoint but not the `/cat/good` endpoint?

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by ichn-hu** [comment]
> So you get the result you are expecting at the `/good` endpoint but not the `/cat/good` endpoint?

I am expecting `/cat/good`, but get `/good`.

**Comment by ichn-hu** [comment]
> Please, provide a minimal repository which reproduces your issue.

Sure, please take a look, https://github.com/ichn-hu/nestjs-route-bug-reproduce

**Comment by ichn-hu** [comment]
https://github.com/ichn-hu/nestjs-route-bug-reproduce/blob/master/src/app.controller.ts

This is the only modified file from `nest n proj`, I didn't do anything with other files. I was working on another project using nestjs but found the route not working and could reproduce it from the bare bone `nest n proj`.

**Comment by ichn-hu** [comment]
My fault, it is actually routed to `/good/cat`... The logged information is misleading, it reads

```
[Nest] 13871   - 02/11/2020, 9:42:45 AM   [NestFactory] Starting Nest application...
[Nest] 13871   - 02/11/2020, 9:42:45 AM   [InstanceLoader] AppModule dependencies initialized +32ms
[Nest] 13871   - 02/11/2020, 9:42:45 AM   [RoutesResolver] AppController {/cat}: +11ms
[Nest] 13871   - 02/11/2020, 9:42:45 AM   [RouterExplorer] Mapped {/good, GET} route +3ms
[Nest] 13871   - 02/11/2020, 9:42:45 AM   [NestApplication] Nest application successfully started +2ms
```

When I saw `Mapped {/good, GET}`, I thought it's routed to `/good`, but it is actually `/cat/good` as expected.

Perhaps this issue can be useful from a starter's perspective, and I would suggest some change here but since my problem is solved, I am closing it.

Thanks @JustinR93  and @kamilmysliwiec for comment.
