### ISSUE TITLE
Possibility of ClientsModule.registerAsync

### ISSUE THREAD

**Issue by feihan** [nestjs/nest#4040]
## Is your feature request related to a problem? Please describe.

Currently i have to write static values into ClientModule.register().
I would like to inject my ConfigModule and read values from there.

## Describe the solution you'd like

Make a ClientsModule.registerAsync(). Like the TypeormModule / HttpModule / ...

## Teachability, Documentation, Adoption, Migration Strategy

The registerAsync is a very common pattern in nestjs.

## What is the motivation / use case for changing the behavior?

Make values configurable thorugh other Modules or services. No need for static typed values.

That would help me a lot.
Thank you for your awesome product!

**Comment by jmcdo29** [comment]
Is anyone working on this? I can give it a shot if not

**Comment by kamilmysliwiec** [comment]
@jmcdo29 PR would be more than welcome :)

**Comment by feihan** [comment]
@jmcdo29 would be great. If you need help, let me know.

**Comment by jmcdo29** [comment]
What would be the main difference in creating a `ClientsModule.registerAsync()` vs using a [Custom Provider](https://docs.nestjs.com/microservices/basics#client) that uses a factory as shown in the docs?

**Comment by kamilmysliwiec** [comment]
@jmcdo29 I'm guessing it's just all about the consistency with other `@nestjs/` modules. Using a custom provider approach would work fine in this case as well :)

**Comment by jmcdo29** [comment]
To anyone who would like to take a crack at this, it'll be a while before I can get back to it, so feel free :)

**Comment by Hexenon** [comment]
Im going to work on this one, because i need this feature. Hope i do it right.

**Comment by Amorites** [comment]
> > > i have lot of work i started it and researching how to achieve it, wanna join ?
> > 
> > 
> > Sounds great! Is there any task that can be split？
> 
> first of all, research how ClientsModule factory works, and understand how providers can be returned asynchronously within NestJS provider factory and what other methods are in there to dynamically return providers or modules

I made a Pull Request according to your prompt. Would you please give a review?

**Comment by Hexenon** [comment]
> > > > i have lot of work i started it and researching how to achieve it, wanna join ?
> > > 
> > > 
> > > Sounds great! Is there any task that can be split？
> > 
> > 
> > first of all, research how ClientsModule factory works, and understand how providers can be returned asynchronously within NestJS provider factory and what other methods are in there to dynamically return providers or modules
> 
> I made a Pull Request according to your prompt. Would you please give a review?

good job, all makes sense to me. Its exactly what I was in my wip fork. now let's wait until they review and merge.

**Comment by synic** [comment]
@Sotatek-HuyTran3 Not sure if you still need this, but it looks something like this:

```typescript
@Module({
  imports: [
    ClientsModule.registerAsync([
      {
        name: 'NOTIFICATIONS_SERVICE',
        inject: [appConfig.KEY],
        useFactory: async (config: ConfigType<typeof appConfig>) => ({
          transport: Transport.RMQ,
          options: {
            urls: config.microservices.rabbitMqUrls,
            queue: 'notifications',
            queueOptions: {
              durable: true,
            },
          },
        }),
      },
    ]),
  ]
})
export class NotificationsModule {}
```
