### ISSUE TITLE
Documentation for HTTP exceptions is incorrect

### ISSUE THREAD

**Issue by saulotoledo** [nestjs/nest#4042]
The documentation for the HTTP exceptions in `packages/common/exceptions/` is incorrect:

- The default return format for specific HTTP exceptions is `{ statusCode, error }`, not  `{ statusCode, message }` (this leads to #4044, but it may be a breaking change and it can wait);
- The `statusCode` in the result cannot be overwritten as described;
- A proper explanation for the `message` argument is missing;
- The `error` argument is not required and has a complete different meaning from the current description.

**Comment by Luca-Terrazzan** [comment]
I would also add that the documentation also contains other errors, for example, argument `error` is described ad required but is -- in reality -- optional.

Also, I', not sure about the usefulness of the `error` parameter; we already have a description of the exception and a status code. This additional parameter is pretty confusing and ends up with different payloads between HttpExceptions and specific exceptions.
