### ISSUE TITLE
Inconsistent output for HTTP exceptions

### ISSUE THREAD

**Issue by saulotoledo** [nestjs/nest#4044]
## Current behavior

The default output of HTTPException is `{statusCode, message}`, but the default output for another specific exception (e.g., BadRequestException) is `{statusCode, error}`. They should be consistent.

## Input Code

```ts
throw new HTTPException('Bad request', 400);
// It will result on {statusCode, message}

throw new BadRequestException();
// It will result on {statusCode, error}
```

## Expected behavior

The calls should have a compatible result. I suggest they all return `{statusCode, message}`.

## Environment

<pre><code>Nest version: 6.11.4</code></pre>

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/3454
