### ISSUE TITLE
Thank you so much for making this project!

### ISSUE THREAD

**Issue by yayajacky** [nestjs/nest#4046]
We have been using NestJS in production for 6-8 months but it's nothing but pleasantness to work with defining module/controllers/service/repositories/entities/transforms/pipes everyday.

Feature development on the backend is way faster than frontend work, and I am glad I am on the backend team because I get to work with NestJS everyday!

Just want to say thank you again for this amazing work! You are making TypeScript backend work a better place.

**Comment by kamilmysliwiec** [comment]
Thank you Jack 😊😊😊 Good luck with your project!!
