### ISSUE TITLE
NestModule.configure is not called when a module is created in Test.createTestingModule

### ISSUE THREAD

**Issue by whitebyte** [nestjs/nest#4052]
## Bug Report

Consider the following snippet:
```ts
export class AppModule implements NestModule {
    public configure(consumer: MiddlewareConsumer) {
        consumer
            .apply(TradingApplicationContextMiddleware)
            .forRoutes('*');
   ...

```
This is a module that uses a middleware, and it works OK. Now, when I do...
```ts
const moduleRef = await Test.createTestingModule({
            imports: [AppModule]
        })
            .overrideProvider(AppModule)
            .useValue(AppModule)
            .compile();

        app = moduleRef.createNestApplication();
        await app.init();
    });
```
...`AppModule.configure()` is never called. It makes `Test.createTestingModule` effectively useless for e2e tests if there are class-based (non-function based) middlewares.
For me it looks kike a bug.

Nest version: 6.11.6
Node version: 12.14.1
Platform:  Linux

Others:
There is a relevant issue https://github.com/nestjs/nest/issues/1408 that was never resolved

**Comment by kamilmysliwiec** [comment]
Remove this:
```typescript
.overrideProvider(AppModule)
.useValue(AppModule)
```
and it will be working fine. You shouldn't pass a class reference to the `useValue` method
