### ISSUE TITLE
Plugin framework NestJS

### ISSUE THREAD

**Issue by Jantje2000** [nestjs/nest#4057]
Hi, I don't know if this is a feature request, or a support question, but I'm trying to create a plugin architecture. 
I'm creating a multitenant app (an application for multiple companies with each their own database), but also the loaded modules should be dependent on the current tenant. I would achieve this by loading some extra modules in the middleware, but I don't know if that's possible in NestJS?
I saw your dynamic modules, and it's really nice, but is it possible to load some modules in runtime instead of when bootstrapping?

**Comment by kamilmysliwiec** [comment]
Can you elaborate (describe your use-case) on what exactly you would like to load per consumer? Loading modules dynamically on-demand (at runtime) doesn't make too much sense in Nest.

**Comment by Jantje2000** [comment]
@kamilmysliwiec 
I have at the moment for example an existing module for customers and suppliers. Companies can manage them there. 
Some companies also want to add tasks for their customers. This routes should be added only when they are requesting my API.
Not only for routes, because the entity for example should also not be loaded.

It would be nice too, if I could load the modules from an external source, whereafter I could load that module in my nest app.
Is that possible?

**Comment by kamilmysliwiec** [comment]
> Some companies also want to add tasks for their customers. This routes should be added only when they are requesting my API.

I'm not sure what's the use-case for adding routes dynamically (and removing them afterward?). This should never be the case. 

> It would be nice too, if I could load the modules from an external source, whereafter I could load that module in my nest app.

You can achieve all that with dynamic modules and asynchronous providers.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
