### ISSUE TITLE
Can't inject a repository from a different module

### ISSUE THREAD

**Issue by nilkrdg** [nestjs/nest#4062]
## Bug Report
I have a boilerplate project with Nest.js using postgresql with TypeORM.
I am trying to inject a repository from a different module into a service but I receive the following error:

> Nest can't resolve dependencies of the CasbinService. Please make sure that the argument ClientRepository at index [0] is available in the AuthoriseModule context.

## Current behavior

I have two modules: ClientModule and CasbinModule. Each module has a repository and database queries are working as expected. (Client and Casbin repositories.)
I need to call some client queries inside the casbin module but I am unable to inject Client repository into CasbinService. I have followed the documentation from this link [https://docs.nestjs.com/techniques/database](url).
I share my module files. Am I doing something wrong or dependency injection isn't working as expected?

## Input Code

casbin.module.ts
```ts
import { Module } from '@nestjs/common';
import { CasbinService } from './casbin.service';
import { CasbinController } from './casbin.controller';
import { CasbinRule } from './casbin.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CasbinAdapter } from './casbin.adapter';
import { ClientModule } from '../client/client.module';

@Module({
    imports: [TypeOrmModule.forFeature([CasbinRule]), ClientModule],
    controllers: [CasbinController],
    providers: [CasbinService],
    exports: [CasbinService]
})
export class CasbinModule { }
```

casbin.service.ts
```ts
import { Inject, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Client } from '../client/client.entity';
import { Repository } from 'typeorm';

@Injectable()
export class CasbinService {
    private enforcer: casbin.Enforcer;
    constructor( @InjectRepository(Client) private readonly repository: Repository<Client>) {
    }
}
```
client.module.ts
```ts
import { Module } from '@nestjs/common';
import { ClientController } from './client.controller';
import { ClientService } from './client.service';
import { Client } from './client.entity';
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
  imports: [TypeOrmModule.forFeature([Client])],
  controllers: [ClientController],
  providers: [ClientService],
  exports: [TypeOrmModule]
})
export class ClientModule {}
```
client.service.ts
```ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { EntityManager, Repository } from 'typeorm';
import { Client } from './client.entity';
@Injectable()
export class ClientService {
    constructor(@InjectRepository(Client)
    private readonly repository: Repository<Client>) {
    }
 }
```

## Expected behavior

CasbinService dependencies are resolved successfully and I can call the client repository inside the CasbinService.

## Environment

<pre><code>
Nest version: 6.11.3

 
For Tooling issues:
- Node version:  v10.17.0
- TypeORM version: 6.11.3

- Platform:  Linux, Ubuntu~18.04.1

</code></pre>

**Comment by kamilmysliwiec** [comment]
That's the expected behavior. Please, read this chapter https://docs.nestjs.com/modules

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by nilkrdg** [comment]
> That's the expected behavior. Please, read this chapter https://docs.nestjs.com/modules
> 
> Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

Thank you for your prompt reply. I will read that section again and if I can't still figure it out, I will ask from Discord channel.
