### ISSUE TITLE
How to Implement service locator with Nest.js?

### ISSUE THREAD

**Issue by thohoh** [nestjs/nest#407]
I'm submitting a question.

In one of my factories I need to dynamically pull out services out from nestjs container. Normally in IoC containers you have the ability to inject the container itlsef.

So I want to inject something like Execution Context into my service and then use it's method ``get()`` to resolve whatever I want.

Here's example of what it could look like:
```
@Component()
export class Factory {
    constructor(
         private context: INestExecutionContext
    ) {}

    create(type) {
        return this.context.get(type);
    }
}
```

Is there is a way to achieve that ?

Thanks.

**Comment by sqrter** [comment]
Hi, I guess you can do it like this:
```typescript
@Component()
export class CatsService implements OnModuleInit {
  private service: Service;
  constructor(private readonly moduleRef: ModuleRef) {}

  onModuleInit() {
    this.service = this.moduleRef.get<Service>(Service);
  }
}
```
Though, as far as I'm concerned the limitation is that you can do it like this only get components provided inside the same module.

https://github.com/nestjs/nest/issues/258#issuecomment-355237100

**Comment by thohoh** [comment]
@sqrter That's quite enough, thank you!
