### ISSUE TITLE
The "All" route handler does not work with Fastify.

### ISSUE THREAD

**Issue by FormerPhysicist** [nestjs/nest#4075]
## Bug Report
Using the "All" route handler with a path wildcard does not work when using the fastify framework. It works when using express, however.

## Current behavior
Returns 404 with the following payload
```
{
    "statusCode": 404,
    "error": "Not Found",
    "message": "Cannot GET /any/old/path"
}
```
## Input Code
I am trying to use the "All" decorator as follows
```ts
@All('*')
public async handler(): Promise<string> {...}
```

See this [repository](https://github.com/FormerPhysicist/nestjs-bug) for a minimal reproduction of the bug. The fastify branch uses fastify as the underlying framework and _does not work_. The express branch uses express as the underlying framework and _it does work_.

## Expected behavior
The controller method should be called for all HTTP verbs and paths when fastify is being used; 404 should not be returned.

## Environment

Nest version: 6.11.7
 
For Tooling issues:
- Node version: 12.13.0
- Platform:  windows

**Comment by kamilmysliwiec** [comment]
Fastify has a slightly different wildcard notation. Use `(.*)` instead
