### ISSUE TITLE
Graceful shutdown in rabbitmq

### ISSUE THREAD

**Issue by kirit0s** [nestjs/nest#4076]
## Is your feature request related to a problem? Please describe.

When ServerRMQ.close() invoke, channel immediately closes. All my 'ack' lost, because channel closed. Instead of this I want to stop receive messages from queue, and then (in simple version after some time) close channel.

## Describe the solution you'd like

Now I have to patch server-rmq.js. Because I didn't find a way to do it from the outside (for example in shutdown hooks). I add this:
```js
async close() {
    await this.channel.removeSetup(undefined, channel => {
        channel.cancel(this.consumerTag);
        return new Promise(resolve => setTimeout(resolve, 5000))
    });
    
    this.channel && this.channel.close();
    this.server && this.server.close();
}
```
Get `consumerTag` from `channel.consume` return;
```js
async setupChannel(channel, callback) {
  const noAck = this.getOptionsProp(this.options, 'noAck', constants_1.RQM_DEFAULT_NOACK);
  await channel.assertQueue(this.queue, this.queueOptions);
  await channel.prefetch(this.prefetchCount, this.isGlobalPrefetchCount);
  const { consumerTag } = await channel.consume(
    this.queue,
    msg => this.handleMessage(msg, channel),
    { noAck }
  );
  this.consumerTag = consumerTag;
  
  callback();
}
```

## Teachability, Documentation, Adoption, Migration Strategy

For now, I haven't found a way to wait for all messages to be processed, so I'm just waiting some time for my operations to complete.

Time can be passed via options.

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/docs.nestjs.com/issues/113
