### ISSUE TITLE
Improve Logger static calls behaviour

### ISSUE THREAD

**Issue by AzariasB** [nestjs/nest#4077]
## Is your feature request related to a problem? Please describe.
When calling the static methods on the Logger (log, error, warn, debug, verbose), it then calls the stdout printing
[code here](https://github.com/nestjs/nest/blob/549e2927775690db6db7f6efc683eb896d610ab3/packages/common/services/logger.service.ts#L154)

## Describe the solution you'd like
I know (thank you documentation), that I can create my own Logger implementation, but It would be great if I could just extend the existing Logger, by forcing it to use a custom LoggerService class when calling the static methods.

## Teachability, Documentation, Adoption, Migration Strategy
It would look something like this :
```ts
import { Logger } from '@nestjs/common';

async function bootstrap() {
 // Setup app and stuff
 Logger.setStaticLogger(MyCustomLoggerService);
 Logger.info("info");// Uses MyCustomLoggerService instead of printing on stdout
}
```

## What is the motivation / use case for changing the behavior?
This features avoids the creation of a new class that is an almost complete copy-pasta of the nestjs implementation, with some slight changes.

**Comment by kamilmysliwiec** [comment]
> This features avoids the creation of a new class that is an almost complete copy-pasta of the nestjs implementation, with some slight changes.

You can just extend the `Logger` class (inheritance).

> by forcing it to use a custom LoggerService class when calling the static methods.

We're not planning such a feature. If you are willing to use a custom `LoggerService`, you should use it instead of interacting with the `Logger` static methods.
