### ISSUE TITLE
Typeorm lazy loading

### ISSUE THREAD

**Issue by krystofrezac** [nestjs/nest#4078]
I have been trying to implement [Typeorm lazy loading](https://github.com/typeorm/typeorm/blob/master/docs/eager-and-lazy-relations.md) but it seems that it does not work in my [project](https://github.com/krystofrezac/next-nest-template/tree/feature/lazy-loading/api) (files user.resolver and user-entity). When I fetch the User entity the roles field is always null. Is something that I have missed? Do you have any examples or documentation concerning this topic?

**Comment by kamilmysliwiec** [comment]
Please, use the typeorm repository for such questions.

**Comment by krystofrezac** [comment]
I don't think that is typeorm problem because it works in auth.service. The problem is that it does not go through graphql layer. And I found [example](https://github.com/MichalLytek/type-graphql/tree/master/examples/typeorm-lazy-relations) with typegraphql where everything is working. So the only reason that comes to my mind is that @nestjs/graphql package somehow influences basic typegraphql behavior.

**Comment by krystofrezac** [comment]
For those who could come across the same problem I have found a solution. My problem was that I was using Interceptors. The basic `ClassSerializerInterceptor` uses a method called `transformToPlain` which returns `object`. But Typeorm needs `class` to work properly so the only thing that is needed to make it work is to rewrite this method like this: 
```js 
transformToClass(plainOrClass: any, options: ClassTransformOptions): PlainLiteralObject {
    return plainOrClass && plainOrClass.constructor !== Object
      ? classTransformer.classToClass(plainOrClass, options)
      : plainOrClass;
  } 
```
