### ISSUE TITLE
Controler of the nest application created with ExpressAdapter doesn't work. 

### ISSUE THREAD

**Issue by Serg-Mois** [nestjs/nest#4079]
Hello, I have an existing express app and would like to iteratively migrate to nest.js. 

```
const server = express();
server.use('api/something', ...);

const app = await NestFactory.create(
  ApplicationModule,
  new ExpressAdapter(server),
);

app.listen(3000);
app.init();

```
When I created app in this way - controllers provided in ApplicationModule is not visible, but all 'server' routes works fine ( such as localhost:3000/api/something ).

Is it possible to combine express instance routes with nest.js controllers?

**Comment by kamilmysliwiec** [comment]
> Is it possible to combine express instance routes with nest.js controllers?

Yes.

```
app.listen(3000);
app.init();
```

You should call `await app.init()` before `listen()`
