### ISSUE TITLE
Can I create a nest application and microservice together?

### ISSUE THREAD

**Issue by figo2264** [nestjs/nest#4088]
This is my bootstrap file.

`import {NestFactory} from '@nestjs/core';
import {AppModule} from './app.module';
import {Logging} from './shared/logging/logging.service';
import {ConfigService} from './config/config.service';
import {Transport} from '@nestjs/microservices';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const config: ConfigService = app.get(ConfigService);
  app.enableCors();
  app.useLogger(app.get(Logging));

  await app.listen(3000, config.get('SERVER_IP'));

  // const mApp = await NestFactory.createMicroservice(AppModule, {
  //   transport: Transport.RMQ,
  //   options: {
  //     urls : ['amqp://localhost:5672'],
  //     queue: 'renderQueue',
  //     queueOptions: {
  //       durable: true
  //     },
  //   },
  // });
}
bootstrap();`

I was running an application but I want to integrate rabbitmq into existing application.
according to the nest documentation, I have to create a microservice from the factory, but it seems to be not compatible with existing app.

Any guide?

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/faq/hybrid-application

**Comment by figo2264** [comment]
@kamilmysliwiec Thanks~!!!
