### ISSUE TITLE
How to add keepalive options in grpc client?

### ISSUE THREAD

**Issue by CatsMiaow** [nestjs/nest#4094]
I did not find it when I searched with keepalive on Discord.

Fixing a connection issue in an AWS environment requires the keepalive setting in the grpc client option.
```ts
'grpc.keepalive_time_ms': 120000,
'grpc.http2.min_time_between_pings_ms': 120000,
'grpc.keepalive_timeout_ms': 20000,
'grpc.http2.max_pings_without_data': 0,
'grpc.keepalive_permit_without_calls': 1
```

https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-grpc.ts#L67-L95
https://github.com/nestjs/nest/blob/master/packages/common/interfaces/microservices/microservice-configuration.interface.ts#L28-L51
It appears that we currently only support two(`grpc.max_send_message_length`, `grpc.max_receive_message_length`) options.

Let me know if there's a way to set it up.

Note link.
- https://github.com/grpc/grpc-node/issues/154
- https://github.com/grpc/grpc/blob/master/doc/keepalive.md
- https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-best-practices-app&locale=en#best-practices-app-connections

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? It seems that this is not possible currently.

**Comment by kamilmysliwiec** [comment]
Added in 6.11.9
