### ISSUE TITLE
encodeURIComponent have some conflict with HttpService Module

### ISSUE THREAD

**Issue by giovanniKleinCampigoto** [nestjs/nest#4102]
## Current behavior

After using encodeURIComponent to request a url with a query string for e.g:
http://foo.bar?query=some1247%/weirdtoken
This is happening:
![error](https://user-images.githubusercontent.com/23245646/74844443-35782280-530c-11ea-926b-4f0efed7df04.png)
## Input Code

```ts
Module:
@module({
imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    JwtModule.register({
      secret: 'secret',
      signOptions: { expiresIn: '60s' },
    }),
    HttpModule.register({
      baseURL: process.env.MIDDLEWARE_URL,
      headers: {
        'Content-Type': 'application/json',
      },
    }),
  ],

Service:
 getLeadByToken(token: string) {
    return this.httpService.get(`/leads?token=${encodeURIComponent(token)}`);
  }
```

## Expected behavior

Should at least go to my exception filter, but the code blows up even before that
## Environment
<pre><code>
Nest version: X.Y.Z

 "dependencies": {
    "@nestjs/common": "^6.7.2",
    "@nestjs/config": "0.0.9",
    "@nestjs/core": "^6.7.2",
    "@nestjs/jwt": "^6.1.1",
    "@nestjs/platform-express": "^6.7.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.5.3"
  },
  "devDependencies": {
    "@nestjs/cli": "^6.9.0",
    "@nestjs/schematics": "^6.7.0",
    "@nestjs/testing": "^6.7.1",

For Tooling issues:
- Node version: v12.14.1
- Platform:  Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
