### ISSUE TITLE
It´s possible create entity(orm) from database

### ISSUE THREAD

**Issue by uldcra** [nestjs/nest#4106]
Hello everybody.
Sorry my english is very poor, but there is a possibility to create entity from database sql, that the tables in your database.

**Comment by JustinR93** [comment]
Are you using TypeORM?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
