### ISSUE TITLE
Allow module-wide customisation of default attributes for decorators

### ISSUE THREAD

**Issue by otavioleitao** [nestjs/nest#4107]
Hi,

**Context:**
Currently, NestJS decorators have fixed default values for the expected attributes. 

**Problem:**
As projects using NestJS vary a lot in context, these default values will work for some projects, but not for others. For these projects, developers have to specify the same attribute every single time they are using the decorator around their projects, even if the value is the same project-wide.

**Example:**
It might make sense for a project to have the `ValidationPipe` applied to the `@Body` decorator automatically. Instead of setting the `ValidationPipe` every time the `@Body` decorator is used, a default attribute could be configured at the module level so developers don't have to set it every time.

**Benefits:**
It's not only cleaner but it also removes chances of engineers forgetting about setting decorator attributes they should use by default in their projects.

**Suggested solution:**
NestJS should allow the customisation of default attribute values for decorators at the module level.

Hope that makes sense.

Thanks,
Otávio.

**Comment by kamilmysliwiec** [comment]
> It might make sense for a project to have the ValidationPipe applied to the @Body decorator automatically. Instead of setting the ValidationPipe every time the @Body decorator is used, a default attribute could be configured at the module level so developers don't have to set it every time.

So why not just set the global pipe?

**Comment by kamilmysliwiec** [comment]
You can also inherit from the `ValidationPipe` and filter values by the `type` property of the `ArgumentMetadata` (to validate only "body" values) 

![image](https://user-images.githubusercontent.com/23244943/75035893-d869a180-54b0-11ea-8a70-70dd743fa74f.png)
