### ISSUE TITLE
ParseObjectIdPipe for projects using TypeORM with MongoDB

### ISSUE THREAD

**Issue by matthiashermsen** [nestjs/nest#4109]
## Is your feature request related to a problem? Please describe.
I'm using TypeORM with MongoDB and want to validate and transform incoming id params in my Controller. These IDs are of type `ObjectID` and there is no built-in pipe for validation and transformation.

**The problem is that I don't know if that problem is related to NestJs when one is not using TypeORM. So it's fine if you don't want to support this.** 

## Describe the solution you'd like
It would be nice to have a `ParseObjectIdPipe`. This pipe should check if the param is a valid MongoDB ObjectID and transforms the value if it's valid.

So the following code is just a suggestion :)

```ts
import { PipeTransform, Injectable } from '@nestjs/common';
import { ObjectID } from 'mongodb';

import { ArgumentException } from '../exceptions/argument.exception';

/**
 * Defines the pipe for MongoDB ObjectID validation and transformation
 */
@Injectable()
export class ParseObjectIdPipe implements PipeTransform<any, ObjectID> {
  /**
   * Validates and transforms a value to a MongoDB ObjectID
   *
   * @remarks
   * Throws a ArgumentException if the validation fails
   *
   * @param value - The value to validate and transform
   * @returns The MongoDB ObjectID
   */
  public transform(value: any): ObjectID {
    try {
      const transformedObjectId: ObjectID = ObjectID.createFromHexString(value);
      return transformedObjectId;
    } catch (error) {
      throw new ArgumentException('Validation failed (ObjectId is expected)');
    }
  }
}
```

## Teachability, Documentation, Adoption, Migration Strategy
So if you are using ID columns of type `number` you would come up with

```ts
  @Get(':id')
  public getUserById(@Param('id', ParseIntPipe) id: number): Promise<User> {
    // ...
  }
```

When using MongoDB you could use the correct pipe for those `ObjectID`s.

```ts
  @Get(':id')
  public getUserById(@Param('id', ParseObjectIdPipe) id: ObjectID): Promise<User> {
    // ...
  }
```

## What is the motivation / use case for changing the behavior?
This pipe could be used by many projects relying on MongoDB. You don't have to create your own pipe all the time.

**Comment by kamilmysliwiec** [comment]
NestJS is platform-agnostic which means that it can be used with typeorm, sequelize, knex, mongoose, and even the native drivers. Adding a pipe to the core packages which is useful for just one of the mentioned libraries wouldn't make too much sense.. Thanks for sharing your solution anyway, perhaps someone else will be searching for this!

**Comment by alexluong** [comment]
Hi @kamilmysliwiec, just wanna chime in and say that I believe this pipe would be helpful for a lot of projects using Mongo regardless of the database layer (TypeORM/Mongoose/native MongoDB driver). I'm researching NestJS with a MongoDB project and do a quick search after reading the [Pipe chapter](https://docs.nestjs.com/pipes). Thanks @matthiashermsen for opening the issue, it's really helpful!

**Comment by matthiashermsen** [comment]
If more people request this you might want to create a repo `@nestjs/mongodb` and ship utils like this pipe?

**Comment by kamilmysliwiec** [comment]
Everyone is welcome to publish any package that may help other people. We can't really maintain all of them under the official organization, so I recommend publishing this as a separate package.
