### ISSUE TITLE
Hybrid application's microservice doesn't inherit application configuration 

### ISSUE THREAD

**Issue by 2Kable** [nestjs/nest#4112]
## Bug Report

Similar to #353 but with suggestion to fix

## Current behavior
When connecting a microservice to a NestApplication I would expect it to inherit configuration like Interceptors and such

```ts
const app = await NestFactory.create(AppModule, { logger })
app.useGlobalInterceptors(LoggerInterceptor)
app.connectMicroservice({
  transport: Transport.GRPC,
  options: {}
})
```
In this case the microservice will not inherit the Application global interceptor

this is caused in 
[packages/core/nest-application.ts](packages/core/nest-application.ts)
```ts
  public connectMicroservice(options: MicroserviceOptions): INestMicroservice {
    const { NestMicroservice } = loadPackage(
      '@nestjs/microservices',
      'NestFactory',
      () => require('@nestjs/microservices'),
    );

    const applicationConfig = new ApplicationConfig();
    const instance = new NestMicroservice(
      this.container,
      options,
      applicationConfig,
    );
    instance.registerListeners();
    instance.setIsInitialized(true);
    instance.setIsInitHookCalled(true);

    this.microservices.push(instance);
    return instance;
  }
```
`NestMicroservice` instance is instantiated with a whole `new ApplicationConfig()`

## Expected behavior
I would expect that hybrid application can share the same `ApplicationConfig`

## Possible Solution
We fixed it by patching nest source code and passing the `NestApplication` config in the `NestMicroservice` constructor

```diff
- const applicationConfig = new ApplicationConfig();
- const instance = new NestMicroservice(this.container, options, applicationConfig);
+ const instance = new NestMicroservice(this.container, options, this.config);
```

But this would lead to a huge breaking change for current application that wants a separate configuration.

I would suggest an optional argument/property to pass to the `connectMicroservice` function to use the existing `ApplicationConfig` instance

Another solution could be adding a method to attach a `NestMicroservice` instance to the NestApplication without relying on connectMicroservice

```ts
  public attachMicroservice(instance: NestMicroservice): INestMicroservice {
    instance.registerListeners();
    instance.setIsInitialized(true);
    instance.setIsInitHookCalled(true);
    this.microservices.push(instance);
    return instance;
  }
```

# Environment

<pre><code>
Nest version: 6.11.6
</code></pre>

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/75035808-a1938b80-54b0-11ea-9137-5fd93dfcc27a.png)

This is intentional, see docs: https://docs.nestjs.com/guards#binding-guards

**Comment by 2Kable** [comment]
Hi,
I get that this is intended, but is this design improvable ?

Not being able to set global guard/interceptors for nest-grpc running in an hybrid application, greatly reduce the experience of it.

My use case is: I want to run grpc alongside the graphql/http instance, and being able to intercept all request to log them is kinda basic.

And there's currently no way to set it up in an hybrid, or event create a NestMicroservice instance ourselves and attach it to the NestApplication

The change can be non breakable, and greatly improve the hybrid experience

**Comment by regevbr** [comment]
@2Kable totally agree with you!
