### ISSUE TITLE
sample/04-grpc might out of maintain

### ISSUE THREAD

**Issue by aquariuslt** [nestjs/nest#4122]
## Current behavior

Can not run `sample/04-grpc` with `npm run start:prod` correctly

## Input Code

```shell
npm run start:prod

## ... nest application bootstrap log

[Server] ENOENT: no such file or directory. /path/to/nest/sample/04-grpc/dist/hero/hero.proto
```

## Expected behavior

The build script suppose to copy `.proto` file to `dist` directory, so the. protoloader can load from `path.join(__dirname, 'path/to/proto')` when `__dirname` is under dist directory.

## Possible Solution

Update build script to copy `proto` file into dist directory

## Environment

<pre><code>
Nest version: 6.11.8

 
For Tooling issues:
- Node version: v12.16.0
- Platform:  MacOS 10.15

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
> The build script suppose to copy .proto file to dist directory, so the. protoloader can load from path.join(__dirname, 'path/to/proto') when __dirname is under dist directory.

I've just tested and it works fine. `npm run build` should automatically copy `.proto` file to the `dist` directory. Are you sure that you used `npm run build` instead of `tsc`?

**Comment by aquariuslt** [comment]
sorry for use outdate code version, it works now
😭

**Comment by ckken** [comment]
no work for me too

**Comment by Desusha** [comment]
I think better way on **nest-cli.json**  file add compilation option

` "compilerOptions": {
    "deleteOutDir": true,
    "assets": [
      "**/*.proto"
    ],
    "watchAssets": true
  }`

this will add the .proto file to the dist.

**Comment by MrLightful** [comment]
what if using monorepo?

I have app1 (client), app2 (service). Both need proto file, which i included in libs/abstractions. How would i include proto file from a lib, be included in the app's build?
