### ISSUE TITLE
Delaying database connection until application bootstrap

### ISSUE THREAD

**Issue by rettgerst** [nestjs/nest#4128]
we have a nestjs application that uses the typeorm module to connect to a database. we also use the swagger module and a script to generate an openapi spec - but instead of serving the spec over http we write it to disk. a simplified version of our script:

```typescript
async function main() {
	const app = await NestFactory.create(AppModule);
	const options = new DocumentBuilder()
		.setTitle('Title')
		.setDescription('description')
		.setVersion('0.0.1')
		.addServer('http://localhost:3000', 'Development server')
		.addTag('hello')
		.build();
	const document = SwaggerModule.createDocument(app, options, {
		ignoreGlobalPrefix: true
	});

	fs.writeFileSync(outPath, JSON.stringify(document, undefined, '  '));

	console.log('built openapi spec file');
}
```

this script worked well until we added typeorm to our project, since typeorm immediately tries to make a database connection on init, even when we don't intend to completely bootstrap the application. this will cause the script to stay open and never exit.

in a different project where we use redis I was able to work around this by moving the redis connection to an `onApplicationBootstrap` method on the service:

```typescript
import { Injectable } from '@nestjs/common';

import * as chalk from 'chalk';
import * as Queue from 'bull';

@Injectable()
export class QueueService {
	queue!: Queue.Queue;

	onApplicationBootstrap() {
		this.queue = new Queue('queue', process.env.REDIS_URL);
		process.on('exit', () => {
			this.queue.close().then(() => () => {
				console.log('bull queue closed');
				process.exit();
			});
		});
		this.queue.on('error', err => {
			console.error(chalk.red('Redis error:'), err.message);
		});
	}
}
```

I was wondering if it was possible to do the same with typeorm.

**Comment by rettgerst** [comment]
I discovered a different solution to this issue which is using a sqlite in-memory db for the spec generation script, similar to how many users do the same for testing.

my approach is a bit different though because I'm not using the testing module to override DI, rather I'm doing it in app.module.ts controlled by an environment variable:

```typescript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { UserController } from './user/user.controller';
import { TypeOrmModule, TypeOrmModuleOptions } from '@nestjs/typeorm';
import { UserEntity } from './user/user.entity';
import { UserModule } from './user/user.module';

const baseOrmCfg: Partial<TypeOrmModuleOptions> = {
	entities: [UserEntity],
	synchronize: process.env.DB_SYNCHRONIZE === 'true'
};

const realOrmCfg: Partial<TypeOrmModuleOptions> = {
	type: 'postgres',
	host: process.env.DB_HOST,
	port: +process.env.DB_PORT,
	username: process.env.DB_USERNAME,
	password: process.env.DB_PASSWORD,
	database: process.env.DB_DATABASE
};

const fakeOrmCfg: Partial<TypeOrmModuleOptions> = {
	type: 'sqlite',
	database: ':memory:'
};

const realDb = !+process.env.FAKE_DB;

const ormCfg = realDb
	? { ...baseOrmCfg, ...realOrmCfg }
	: { ...baseOrmCfg, ...fakeOrmCfg };

@Module({
	imports: [UserModule, TypeOrmModule.forRoot(ormCfg as TypeOrmModuleOptions)],
	controllers: [AppController, UserController],
	providers: [AppService]
})
export class AppModule {}
```

then in my openapi generation script I set `process.env.FAKE_DB = 1`.

**Comment by 1nVitr0** [comment]
I haven't found any references to this in the typeorm docs, nor in the changelog, but since version `10.0.2` (https://github.com/nestjs/typeorm/commit/016881bf3795cacc8932fcb8d453f8e8e4e11d58) typeorm supports the option `manualInitialization`:

```typescript
  /**
   * If `true` database initialization will not be performed during module initialization.
   * This means that database connection will not be established and migrations will not run.
   * Database initialization will have to be performed manually using `DataSource.initialize`
   * and it will have to implement own retry mechanism (if necessary).
   */
  manualInitialization?: boolean;
```

For me this allowed to keep my database configuration and simply skip the connection step when just generating the OpenAPI files.
