### ISSUE TITLE
RabbitMQ Consumer with Multiple Queue's

### ISSUE THREAD

**Issue by mfsoftworks** [nestjs/nest#4132]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

I'm a little confused by the RabbitMQ microservice docs and I can't seem to find a proper answer for this. 

It seems the options object requires a single queue to be specified for the initial connection. Can I subscribe to multiple queues? 

I'll often have my servers grouped by area with something like `user:create` `user:notify` `user:update` all handled by a single User-centric workers server. Is this possible with NestJS? I'm loving the framework so it would be good to see an example code for subscribing to multiple queues.

Sidenote: each queue I have will have a different `noAck` setting as well, some priority tasks require acknowledgement but lesser priority tasks do not require an acknowledgement

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/docs.nestjs.com/issues/113

**Comment by andrucz** [comment]
@mfcodeworks did you manage to make it work with multiple queues? I can't seem to find any good custom transport for RabbitMQ either.

**Comment by pryme0** [comment]
@andrucz  Any solution for this yet?

**Comment by aldoapicella** [comment]
@mfcodeworks Are there any solutions?

**Comment by Sebastian-Iwanczyszyn** [comment]
Hey, check it out https://www.npmjs.com/package/@nestjstools/messaging

You can define multiple channels, so you can listen on multiple queues with handlers.
