### ISSUE TITLE
HttpService has an issue with stream response type

### ISSUE THREAD

**Issue by Vandell63** [nestjs/nest#4144]
## Current behavior
After a http request from the httpmodule with a `requestType: 'stream'`, the response seems to not pass the stream after call the `toPromise()`
## Input Code

```ts
  async getStreamFromUrl(url: string) {
    const writeStream = fs.createWriteStream(
      path.resolve("public/static/videos/test.jpg")
    );

    const response1 = await Axios({
      method: "GET",
      url,
      responseType: "stream"
    });

    const response2 = await this.httpService
      .get(url, { responseType: "stream" })
      .toPromise();

    response1.data.pipe(writeStream); // Work !
    response2.data.pipe(writeStream); // Do not Work !

    return new Promise((resolve, reject) => {
      writeStream.on("finish", resolve);
      writeStream.on("error", reject);
    });
  }
```
Example code showing the two cases. But only one is used in my code

## Expected behavior
Http service must work as same as the Axios request.
For the response1 it create the stream properly and my file is created with a size of 1Mb
For the response2 it create the file with a size of 0Mb

## Possible Solution
Nope

## Environment

<pre><code>
    "@nestjs/common": "^6.10.1",
    "@nestjs/core": "^6.10.1",
    "@nestjs/jwt": "^6.1.1",
    "@nestjs/passport": "^6.1.0",
    "@nestjs/platform-express": "^6.10.1",
    "@nestjs/swagger": "^3.1.0",
    "@nestjs/terminus": "^6.5.2",
    "@nestjs/typeorm": "^6.2.0",
    "@nestjsx/crud": "^4.4.1",
    "@nestjsx/crud-typeorm": "^4.2.0",
    "axios": "^0.19.2"
</code></pre>

**Comment by kamilmysliwiec** [comment]
@Boshen can you take a look? It might be related to your PR

**Comment by Boshen** [comment]
@kamilmysliwiec Let me take a look

**Comment by Boshen** [comment]
@Vandell63 I can't replicate this. And it may be due to your test setup, you are using the same stream and attaching the event listeners after the pipe.
A proper setup would be something like
```javascript
const getStreamFromUrl = (url) => {
  return new Promise(async (resolve, reject) => {
    const writeStream = createWriteStream('img.jpg');
    writeStream.on("finish", resolve);
    writeStream.on("error", reject);

    const response = await new HttpService()
      .get(url, { responseType: "stream" })
      .toPromise();

    response.data.pipe(writeStream);
  });
}
```

**Comment by kamilmysliwiec** [comment]
Thanks @Boshen

**Comment by Vandell63** [comment]
Oh sry i was absent some days. So yeah my example could be confused but i precise `Example code showing the two cases. But only one is used in my code` so only one stream is created and only one request is sent ( but i show you the 2 differents request ). And yes it was a mistake event should be just after the write stream, and the pipe method then.

So thx @Boshen  for you example. I have just copy past your example and effectly the same result happened. The result of this function in my side create a file with a 0kb size again. Do you made a try to your example method ?

So if i replace your method with the Axios library instead of the HttpService. It work in my side ( it create the full file like 5Mb ) . Can you try it ?. 
To resume, in my side this working: 

```
const getStreamFromUrl = (url) => {
  return new Promise(async (resolve, reject) => {
    const writeStream = createWriteStream('img.jpg');
    writeStream.on("finish", resolve);
    writeStream.on("error", reject);

    const response = await Axios({
        method: "GET",
        url,
        responseType: "stream"
      });

    response.data.pipe(writeStream);
  });
}
```
