### ISSUE TITLE
How to transform the uuid to be entity instance for validate in dto?

### ISSUE THREAD

**Issue by lichnow** [nestjs/nest#4148]
I want transform the uuid to be entity instance for validate in dto，but can not get container service of connection,and use `getConnection` import from typeorm directly also can not found named `default` connection。 but in service which inject to modules it work fine

if @body has dto type class, how to validate uuid and then transform to entity instance and then validate the entity instance?

```
export class ArticleDto {
    private categoryRepository: Repository<BlogCategory>;

    public constructor(
        @InjectConnection() private readonly connection: Connection,
    ) {
        // Can not get connection here,connection is undefined
        this.categoryRepository = connection.getRepository(BlogCategory);
      // also error: 'default' connection not found
       this.categoryRepository = getConnection().getRepository(BlogCategory);
    }
// ...
    @IsOptional()
    @IsUUID()
    @Transform(
        data =>
            data.map(
                async item => await this.categoryRepository.findByIds(item),
            ),
        { toClassOnly: true },
    )
    @ValidateNested()
    readonly categories: Promise<BlogCategory[]>;
}```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
