### ISSUE TITLE
How i can pass fastify response schema from nest to fastify?

### ISSUE THREAD

**Issue by femike** [nestjs/nest#4149]
May be have decorator? 
May be in the `nest` it differently?
Or where i can pass router schema data to `fastify`?

For example:
In Nest
```js
@Post()
login() {
// get user bla bla bla
user = { password: 'changeme', username: 'admin' }
const { password, ..data } = user;
return data;
}
```
response return  { username: 'admin' }

in Fastify
```js
fastify.route({ url: '/login', method: ["GET"],
schema: {
  response: {
    201: {
       type: 'object',
       properties: { username: {type: 'string' } }
   }
},
handler: (req, resp) {
   // get user bla bla bla
   user = { password: 'changeme', username: 'admin' }
   return resp.code(201).send(user);
}
```
response return  { username: 'admin' } without password according to the scheme

_Sorry for google translate eng._

**Comment by kamilmysliwiec** [comment]
Use the `@nestjs/swagger` module instead https://docs.nestjs.com/recipes/swagger

**Comment by femike** [comment]
> Use the `@nestjs/swagger` module instead https://docs.nestjs.com/recipes/swagger

It only describe in `@ApiResponse()` for the `swagger` to show example in the `swagger` not filtred output.
I d like to pass scheme to `fastify` to filtre output response according my scheme.

**Comment by kamilmysliwiec** [comment]
Check this chapter then https://docs.nestjs.com/techniques/serialization

**Comment by femike** [comment]
> Check this chapter then https://docs.nestjs.com/techniques/serialization

That's better, it works, good thanks.

**Comment by sergeyampo** [comment]
> Check this chapter then https://docs.nestjs.com/techniques/serialization

It's great but fastify uses fast-json-stringify to serialize response based on a specific schema and Nest uses class-transformer, can we change default serializer?

**Comment by micalevisk** [comment]
> It's great but fastify uses fast-json-stringify to serialize response based on a specific schema and Nest uses class-transformer, can we change default serializer?

You can implement your own `ClassSerializerInterceptor`. See https://github.com/nestjs/nest/blob/d90516640f65c12746771a722a91e48a448aac81/packages/common/serializer/class-serializer.interceptor.ts

**Comment by yantrab** [comment]
@sergeyampo  How did you solve it? 
Fastify has a build-in validation and serialization. 
It does not make sense to use another pipeline...
