### ISSUE TITLE
NodeJS CLS support. NestJS scope improvements

### ISSUE THREAD

**Issue by frct1** [nestjs/nest#4150]
Hello, NestJS contributors

In RU-lang NestJS (https://t.me/nest_ru) community was sent link to https://github.com/nodejs/node/commit/9c702922cdcf830cedb92d51e5dc9f956584c3ee which telling about including CLS to NodeJS. 
I got obvious question: will nestjs get support to pass context into service methods instead of instantiating service instance with each request (a.k.a Request scope)

**Comment by kamilmysliwiec** [comment]
See https://github.com/nestjs/nest/pull/1407
