### ISSUE TITLE
Grpc @GrpcStreamMethod Metadata

### ISSUE THREAD

**Issue by mkaufmaner** [nestjs/nest#4158]
## Is your feature request related to a problem? Please describe.

Currently, when trying to receive and access the metadata within the Grpc method using the `@GrpcStreamMethod` decorator, the second argument is always `undefined`.  Instead, I believe this should be the metadata of the call.

## Describe the solution you'd like

Add the metadata from the call stream to the handler.

## What is the motivation / use case for changing the behavior?

I want to be able to use the metadata sent when the stream was initially established for grpc methods that are wrapped with an observable.

**Comment by kamilmysliwiec** [comment]
Fixed in 6.11.9
