### ISSUE TITLE
Support for Squirrelly view engine template

### ISSUE THREAD

**Issue by finzaiko** [nestjs/nest#4161]
## Is your feature request related to a problem? Please describe.
I want to change my view template using [Squirrelly](https://squirrelly.js.org/)

## Describe the solution you'd like
Might something like
```
  app.setViewEngine({
    engine: {
      squirrelly: require('squirrelly'),
    },
    templates: join(__dirname, '..', 'views'),
  });
```

## What is the motivation / use case for changing the behavior?
New and better template engine

**Comment by kamilmysliwiec** [comment]
If it works with Express, you can use it with NestJS as well. You can access the library instance using the `getHttpAdapter().getInstance()` https://docs.nestjs.com/faq/http-adapter
