### ISSUE TITLE
Can't overrideProvider with a Proxy (or any object with a "then" function)

### ISSUE THREAD

**Issue by nadav-dav** [nestjs/nest#4165]
## Current behavior
During tests, it is common to return a Proxy object that will wrap an instance with spying abilities over its.
When trying to resolve the instance, for some reason, Nest assumes the return object is a promise, and if it has a method named "then" it `await` for it.

## Input Code
```ts
import { Test, TestingModule } from '@nestjs/testing';
import { AppController } from './app.controller';
import { AppService } from './app.service';

describe('AppController', () => {
  let appController: AppController;

  beforeEach(async () => {
    const app: TestingModule = await Test.createTestingModule({
      controllers: [AppController],
      providers: [AppService],
    })
      .overrideProvider(AppService)
      .useValue({then: () => 'then'})
      .compile();
      // This method never resolves and get the tests stuck. 
    

    appController = app.get<AppController>(AppController);
  });

  describe('root', () => {
    it('should return "Hello World!"', () => {
      expect(appController.getHello()).toBe('Hello World!');
    });
  });
});

```

## Expected behavior
If `useValue` is declared, I expect it to use the value I provided, and not try to resolve it (for example, something I want to pass in promises and not have the wait for it to complete).

## Possible Solution
the `useValue` method should pass the value as is, and not try to resolve the promise.

This ticket also be the cause of [this ticket](https://github.com/nestjs/nest/issues/2303) that was never resolved.

## Environment

<pre><code>
Nest version: 6.7.2

 
For Tooling issues:
- Node version: 12
- Platform:  Mac

**Comment by nadav-dav** [comment]
Did some testings and found out this:

This is not a Nest issue but a Node.JS issue (still I think Nest should provide mitigation since this is a common usage patten when testing these kind of frameworks)

Apparently when calling Promise.all on an object with a function named "then" it waits for it and gets stuck. 
```ts
(async function main() {
  console.log(await Promise.all([{ then: () => "then" }]));
  console.log("this is never called");
})(); 
```


A possible solution, can be doing something like this (which can be ugly, but it works)
```ts
(async function main() {
  console.log(
    (
      await Promise.all(
        [{ then: () => "then" }].map(v =>
          types.isPromise(v) ? v : { __then: v }
        )
      )
    ).map((t: any) => (t && t.__then ? t.__then : t))
  );
  console.log("Not getting stuck!");
})();
```

**Comment by kamilmysliwiec** [comment]
This is not related to NestJS. Node will await every `thenable` object

**Comment by nadav-dav** [comment]
@kamilmysliwiec you are right, but i'll argue that  Nest should not await on a value provided at all - that's that whole point of providing a value :)

For example, you can pass on a pending promise as a value (it is common to pass a promise that waits for the environment setup) but more importantly, it could support various frameworks of mocking and proxying, that the community is using regularly. It would makes the system simpler, more straight forward and provide the developers more freedom when choosing their tools.

What do you think?

**Comment by kamilmysliwiec** [comment]
> i'll argue that Nest should not await on a value provided at all 

This is how it works from the first release of Nest. If you provide a Promise as a value, Nest will await it. That is the expected behavior
