### ISSUE TITLE
`Unknown authentication strategy "local"` error when injecting Request to a service

### ISSUE THREAD

**Issue by RezaRahmati** [nestjs/nest#4166]
## Current behavior

`Unknown authentication strategy "local"` error thrown from
`node_modules\@nestjs\passport\dist\auth.gurad.js:16:12`

## Input Code

steps to reproduce:
1- follow these [steps ](https://docs.nestjs.com/techniques/authentication)add local and jwt authentication
2- confirm `auth/login` works with no issue
3. change `user.service` and inject `Request` as below

```
import { Injectable, Scope, Inject } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import { Request } from 'express';

@Injectable({ scope: Scope.REQUEST })
export class UserService {
  constructor(@Inject(REQUEST) private readonly request: Request) {}
  .... rest of code
```
4. call `auth/login` again

## Expected behavior

Working as before with no error
## Environment

<pre><code>
Nest version: 6.10.14
nestjs/jwt : 6.1.2
nestjs/passport: 6.2.0
passport: 0.4.1
passport-jwt: 4.0.0
passport-local: 1.0.0

 
For Tooling issues:
- Node version: 6.10
- Platform:  windows

Others:

</code></pre>

Also the link in [https://docs.nestjs.com/techniques/authentication](https://docs.nestjs.com/techniques/authentication) to navigate to example is broken and it goes to nestjs home page

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/authentication#request-scoped-strategies

**Comment by darkfusion90** [comment]
> https://docs.nestjs.com/techniques/authentication#request-scoped-strategies

For future readers, this URL no longer redirects to the correct section. Use this URL instead https://docs.nestjs.com/recipes/passport#request-scoped-strategies
