### ISSUE TITLE
Documentation for mixin in @nestjs/common is missing

### ISSUE THREAD

**Issue by george3447** [nestjs/nest#4180]
- Documentation for mixin is not available in docs site.

- Files for mixin docs is still available in the [repository](https://github.com/nestjs/docs.nestjs.com/tree/master/src/app/homepage/pages/advanced/mixin-components), but no route is defined for the same in [app-routing.module.ts](https://github.com/nestjs/docs.nestjs.com/blob/master/src/app/app-routing.module.ts).

**Comment by kamilmysliwiec** [comment]
Mixin docs are deprecated. We're working on this in this repo https://github.com/nestjs/docs.nestjs.com

**Comment by dan22-book** [comment]
Is mixin still a recommended feature to use or is there any other reason why is not documented?

**Comment by dfenerski** [comment]
The new [Advanced Concepts](https://courses.nestjs.com/#advanced-concepts) Nest course has a section on it, so my guess is they are not deprecated, wondering where the docs are then..

**Comment by kamilmysliwiec** [comment]
Mixins are OK to use, you just don't need to use `mixin()` function anymore. Otherwise, there are no specific requirements to make mixins work with Nest - hence no documentation (same behavior as with any other existing library, framework, etc).
