### ISSUE TITLE
Got assertionError when using express' Response object

### ISSUE THREAD

**Issue by jannomeister** [nestjs/nest#4181]
## Current behavior
There's a weird error when using express' Response object.  I's returning the result but the server will stop due to the error. (see screenshot).

<img width="749" alt="Screen Shot 2020-02-28 at 5 22 33 PM" src="https://user-images.githubusercontent.com/46916819/75531071-e9855600-5a4e-11ea-806b-7387981032f9.png">

example:
```
return res.json({ greetings: "hello world" });
```

## Expected behavior
It should not throw some error, I guess?

## Environment

<pre><code>
Nest version: `6.12.2`

 
For Tooling issues:
- Node version: `v10.16.3`
- Platform:  `Mac`
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by jannomeister** [comment]
I already solved the issue. The cause of the error was the `return` statement, removing the `return` statement solved the problem. Closing this one now
