### ISSUE TITLE
Requests made with HttpService is very slow

### ISSUE THREAD

**Issue by cupofjoakim** [nestjs/nest#4184]
## Current behavior
Making a request seems to be very slow. CURL'ing to the same URL takes about 10ms, doing it in a newly created NestJS project takes about 3100ms. This could (ofcourse) be on my end, but I'm having trouble seeing what it could be. I've looked around a bunch and can't really find any similar issues.

## Input Code

```ts
// In Service
getInterestList() {
    return this.httpService
      .get<ListInterestCollection>(`${this.baseUrl}/v3/interest`, {
        headers: {
          'Content-Type': 'application/json',
        },
      })
      .pipe(map(result => result.data))
      .toPromise();
}

// In controller method
const startTime = performance.now();
console.log('Starting request');
const { listInterests } = await this.interestService.getInterestList();
console.log(`Finished request in ${performance.now() - startTime}ms`) // Gives ~3100ms
return listInterests;
```

```sh
# Gives 0.01s
time curl <base-url>/v3/interest
```

## Expected behavior
10ms is quick, and a bit of overhead should be expected. I'd guess anything from 11ms to 20ms?

## Environment

<pre><code>
Nest version: 6.11.8
 
For Tooling issues:
- Node version: v12.16.1
- Platform:  Mac Catalina (10.15.3)

Others:
vscode, npm

</code></pre>

**Comment by jmcdo29** [comment]
How's the speed comparison if you use Observables instead of Promises (i.e. don't use `toPromise()`)?

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by cupofjoakim** [comment]
@kamilmysliwiec I tried reproducing the issue at home (where the environment is a bit different, running ubuntu and I don't have complex network rules for an actual enterprise to care about) and couldn't really get the same results there. There still was a lot of overhead, but now around 300ms instead of 3000ms which I kind of think is acceptable.

https://github.com/cupofjoakim/slow-request-reproduction

The reproduction service just makes a call to get my user profile on github. Curl takes less than 10ms and axios takes around 300ms.

I'll probably have to check again on my macbook on monday to see if the minimal reproduction differs based on what I'm calling.

**Comment by cupofjoakim** [comment]
@jmcdo29 I'll see if working with observables changes anything on monday as well.

**Comment by jmcdo29** [comment]
With the repo you've provided, and using the time command to curl, I get the following output for time
```sh
curl -ko /dev/null https://api.github.com/users/cupofjoakim  0.01s user 0.01s system 6% cpu 0.414 total
```
Total time being 414ms. Using observables and modifying your code to use `tap` instead of promises I get the log statement
```sh
Finished request in 208.67289000749588ms
```
I saw promises coming in around `300ms`, so you shave off about 1/3 of the time using `RxJS`, but either way, it's still faster than the overall time of the `cURL`.

**Comment by kamilmysliwiec** [comment]
If you are encountering any performance issues with Axios, please, report an issue in this repository https://github.com/axios/axios

**Comment by cupofjoakim** [comment]
Turns out this was a hickup locally, and was probably something with our local network rules. A weekend later and the issue is gone (without explanation or change). Thanks for the help @jmcdo29 and @kamilmysliwiec.
