### ISSUE TITLE
MulterModule not found in @nestjs/common

### ISSUE THREAD

**Issue by abhishek6262** [nestjs/nest#4190]
## Bug Report

It's mentioned in the documentation that Nestjs provides a built-in module for multer. However, on trying to import it from the `@nestjs/common` we received an error that the package doesn't have any exported member with that name.

## Current behaviour

"/node_modules/@nestjs/common"' has no exported member 'MulterModule'.

## Input Code

```ts
import { Module, MulterModule } from '@nestjs/common';

@Module({
  imports: [
    MulterModule.register({
      dest: './public',
    }),
  ],
})
export class AppModule { }
```

## Environment

<pre><code>
Nest version: 6.14.2
 
For Tooling issues:
- Node version: 13.6.0
- Platform:  Windows 10
</code></pre>

**Comment by jmcdo29** [comment]
The `MulterModule` comes from the [`@nestjs/platform-express`](https://github.com/nestjs/nest/blob/master/packages/platform-express/multer/multer.module.ts) package

**Comment by abhishek6262** [comment]
@jmcdo29 it isn't mentioned in the docs anywhere. Can please someone update the documentation for the same.

Thanks.

**Comment by jmcdo29** [comment]
You wanna make a PR for it? The docs are open source so this stuff can get fixed. It is implicitly mentioned, but only in passing at the beginning of the article

> Warning
Multer cannot process data which is not in the supported multipart format (multipart/form-data). Also, note that this package is not compatible with the FastifyAdapter.

Which _could_ lead one to believe it'll be from the `platform-express` package, but as it isn't explicit, it is a bit confusing

**Comment by abhishek6262** [comment]
Thanks and sure I will make a PR for it.

**Comment by kamilmysliwiec** [comment]
I've just added a hint 
![image](https://user-images.githubusercontent.com/23244943/75657123-ce406380-5c65-11ea-940f-e5db165d8514.png)

Thank you for your contribution though
