### ISSUE TITLE
if two different controller have same router, which one will go first?

### ISSUE THREAD

**Issue by swaitw** [nestjs/nest#4191]
for example: 
one controller in module called "pages" with a router:
@Controller('')
class PagesController{
   @Get('*')
  function(){
  // match existed pages firstly, if not match will call next() to match posts.
}
}

and another controller in module called "posts" with a same router:
@Controller('')
class PostsController{
   @Get('*')
  function(){
  // match existed post firstly, if not match will render 404 page
}
}

in root apple module:
imports:[
   PagesModule,
 PostsModule
]

but, in fact, it always match posts firstly and then match pages, is it possible to control the match order?

**Comment by jmcdo29** [comment]
Is there a reason to have both route handlers attached to the same route? Seems a bit like an anti-pattern to me

**Comment by kamilmysliwiec** [comment]
This is an anti-pattern.
