### ISSUE TITLE
App broken at the nest new app-name

### ISSUE THREAD

**Issue by MikeProcudin** [nestjs/nest#4194]
## Bug Report
I just scaffolded brand new nest project with nest new _nest-api_ command
then _npm start_ it found 41 errors.

## Input Code
$ npm start

> nest-api@0.0.1 start D:\projects\courierCore\nest-api
> nest start
node_modules/@types/jest/index.d.ts:32:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: describe, fdescribe, xdescribe, it, fit, xit, beforeEach, 
afterEach, beforeAll, afterAll, expect, CustomEqualityTester, CustomMatcherFactory, DEFAULT_TIMEOUT_INTERVAL

32 declare var beforeAll: jest.Lifecycle;
   ~~~~~~~

  ../node_modules/@types/jasmine/ts3.1/index.d.ts:21:1
    21 type ImplementationCallback = jasmine.ImplementationCallback;
       ~~~~
    Conflicts are in this file.
node_modules/@types/jest/index.d.ts:32:13 - error TS2300: Duplicate identifier 'beforeAll'.

32 declare var beforeAll: jest.Lifecycle;
               ~~~~~~~~~

  ../node_modules/@types/jasminewd2/index.d.ts:15:18
    15 declare function beforeAll(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
                        ~~~~~~~~~
    'beforeAll' was also declared here.
node_modules/@types/jest/index.d.ts:33:13 - error TS2300: Duplicate identifier 'beforeEach'.

33 declare var beforeEach: jest.Lifecycle;
               ~~~~~~~~~~

  ../node_modules/@types/jasminewd2/index.d.ts:13:18
    13 declare function beforeEach(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
                        ~~~~~~~~~~
    'beforeEach' was also declared here.
node_modules/@types/jest/index.d.ts:34:13 - error TS2300: Duplicate identifier 'afterAll'.

34 declare var afterAll: jest.Lifecycle;
               ~~~~~~~~

  ../node_modules/@types/jasminewd2/index.d.ts:16:18
    16 declare function afterAll(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
                        ~~~~~~~~
    'afterAll' was also declared here.
node_modules/@types/jest/index.d.ts:35:13 - error TS2300: Duplicate identifier 'afterEach'.

35 declare var afterEach: jest.Lifecycle;
               ~~~~~~~~~

  ../node_modules/@types/jasminewd2/index.d.ts:14:18
    14 declare function afterEach(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
                        ~~~~~~~~~
    'afterEach' was also declared here.
node_modules/@types/jest/index.d.ts:39:13 - error TS2300: Duplicate identifier 'it'.

39 declare var it: jest.It;
               ~~

  ../node_modules/@types/jasminewd2/index.d.ts:10:18
    10 declare function it(expectation: string, assertion?: (done: DoneFn) => Promise<void>, timeout?: number): void;
                        ~~
    'it' was also declared here.
node_modules/@types/jest/index.d.ts:40:13 - error TS2300: Duplicate identifier 'fit'.

40 declare var fit: jest.It;
               ~~~

  ../node_modules/@types/jasminewd2/index.d.ts:11:18
    11 declare function fit(expectation: string, assertion?: (done: DoneFn) => Promise<void>, timeout?: number): void;
                        ~~~
    'fit' was also declared here.
node_modules/@types/jest/index.d.ts:41:13 - error TS2300: Duplicate identifier 'xit'.

41 declare var xit: jest.It;
               ~~~

  ../node_modules/@types/jasminewd2/index.d.ts:12:18
    12 declare function xit(expectation: string, assertion?: (done: DoneFn) => Promise<void>, timeout?: number): void;
                        ~~~
    'xit' was also declared here.
node_modules/@types/jest/index.d.ts:1319:46 - error TS2314: Generic type 'ArrayContaining<T>' requires 1 type argument(s).

1319     function arrayContaining(sample: any[]): ArrayContaining;
                                                  ~~~~~~~~~~~~~~~
node_modules/@types/jest/index.d.ts:1320:45 - error TS2314: Generic type 'ObjectContaining<T>' requires 1 type argument(s).

1320     function objectContaining(sample: any): ObjectContaining;
                                                 ~~~~~~~~~~~~~~~~
node_modules/@types/jest/index.d.ts:1346:15 - error TS2428: All declarations of 'ArrayContaining' must have identical type parameters.

1346     interface ArrayContaining {
                   ~~~~~~~~~~~~~~~
node_modules/@types/jest/index.d.ts:1352:15 - error TS2428: All declarations of 'ObjectContaining' must have identical type parameters.

1352     interface ObjectContaining {
                   ~~~~~~~~~~~~~~~~
node_modules/@types/jest/index.d.ts:1361:14 - error TS2314: Generic type 'SpyAnd<Fn>' requires 1 type argument(s).

1361         and: SpyAnd;
                  ~~~~~~
node_modules/@types/jest/index.d.ts:1362:16 - error TS2314: Generic type 'Calls<Fn>' requires 1 type argument(s).

1362         calls: Calls;
                    ~~~~~
node_modules/@types/jest/index.d.ts:1368:15 - error TS2428: All declarations of 'SpyAnd' must have identical type parameters.

1368     interface SpyAnd {
                   ~~~~~~
node_modules/@types/jest/index.d.ts:1401:15 - error TS2428: All declarations of 'Calls' must have identical type parameters.

1401     interface Calls {
                   ~~~~~
node_modules/@types/jest/index.d.ts:1427:16 - error TS2314: Generic type 'CallInfo<Fn>' requires 1 type argument(s).

1427         all(): CallInfo[];
                    ~~~~~~~~
node_modules/@types/jest/index.d.ts:1432:23 - error TS2314: Generic type 'CallInfo<Fn>' requires 1 type argument(s).

1432         mostRecent(): CallInfo;
                           ~~~~~~~~
node_modules/@types/jest/index.d.ts:1437:18 - error TS2314: Generic type 'CallInfo<Fn>' requires 1 type argument(s).

1437         first(): CallInfo;
                      ~~~~~~~~
node_modules/@types/jest/index.d.ts:1444:15 - error TS2428: All declarations of 'CallInfo' must have identical type parameters.

1444     interface CallInfo {
                   ~~~~~~~~
node_modules/@types/jest/index.d.ts:1480:9 - error TS2687: All declarations of 'message' must have identical modifiers.

1480         message: string | (() => string);
             ~~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:21:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: describe, fdescribe, xdescribe, it, fit, xit, 
beforeEach, afterEach, beforeAll, afterAll, expect, CustomEqualityTester, CustomMatcherFactory, DEFAULT_TIMEOUT_INTERVAL

21 type ImplementationCallback = jasmine.ImplementationCallback;
   ~~~~

  node_modules/@types/jest/index.d.ts:32:1
    32 declare var beforeAll: jest.Lifecycle;
       ~~~~~~~
    Conflicts are in this file.
../node_modules/@types/jasmine/ts3.1/index.d.ts:306:9 - error TS2375: Duplicate number index signature.

306         [n: number]: T;
            ~~~~~~~~~~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:309:15 - error TS2428: All declarations of 'ArrayContaining' must have identical type parameters.

309     interface ArrayContaining<T> extends AsymmetricMatcher<any> {
                  ~~~~~~~~~~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:313:15 - error TS2428: All declarations of 'ObjectContaining' must have identical type parameters.

313     interface ObjectContaining<T> extends AsymmetricMatcher<any> {
                  ~~~~~~~~~~~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:317:9 - error TS2386: Overload signatures must all be optional or required.

317         jasmineToString?(): string;
            ~~~~~~~~~~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:355:9 - error TS2374: Duplicate string index signature.

355         [index: string]: CustomMatcherFactory;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:360:9 - error TS2687: All declarations of 'message' must have identical modifiers.

360         message?: string;
            ~~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:360:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'message' must be of type 'string | (() => string)', but here has type 'string'.

360         message?: string;
            ~~~~~~~

  node_modules/@types/jest/index.d.ts:1480:9
    1480         message: string | (() => string);
                 ~~~~~~~
    'message' was also declared here.
../node_modules/@types/jasmine/ts3.1/index.d.ts:904:15 - error TS2428: All declarations of 'SpyAnd' must have identical type parameters.

904     interface SpyAnd<Fn extends Func> {
                  ~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:925:15 - error TS2428: All declarations of 'Calls' must have identical type parameters.

925     interface Calls<Fn extends Func> {
                  ~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:944:15 - error TS2428: All declarations of 'CallInfo' must have identical type parameters.

944     interface CallInfo<Fn extends Func> {
                  ~~~~~~~~
../node_modules/@types/jasmine/ts3.1/index.d.ts:948:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'args' must be of type 'any[]', but here has type 'Parameters<Fn>'.

948         args: Parameters<Fn>;
            ~~~~

  node_modules/@types/jest/index.d.ts:1452:9
    1452         args: any[];
                 ~~~~
    'args' was also declared here.
../node_modules/@types/jasmine/ts3.1/index.d.ts:950:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'returnValue' must be of type 'any', but here has type 
'ReturnType<Fn>'.

950         returnValue: ReturnType<Fn>;
            ~~~~~~~~~~~

  node_modules/@types/jest/index.d.ts:1456:9
    1456         returnValue: any;
                 ~~~~~~~~~~~
    'returnValue' was also declared here.
../node_modules/@types/jasminewd2/index.d.ts:10:18 - error TS2300: Duplicate identifier 'it'.

10 declare function it(expectation: string, assertion?: (done: DoneFn) => Promise<void>, timeout?: number): void;
                    ~~

  node_modules/@types/jest/index.d.ts:39:13
    39 declare var it: jest.It;
                   ~~
    'it' was also declared here.
../node_modules/@types/jasminewd2/index.d.ts:11:18 - error TS2300: Duplicate identifier 'fit'.

11 declare function fit(expectation: string, assertion?: (done: DoneFn) => Promise<void>, timeout?: number): void;
                    ~~~

  node_modules/@types/jest/index.d.ts:40:13
    40 declare var fit: jest.It;
                   ~~~
    'fit' was also declared here.
../node_modules/@types/jasminewd2/index.d.ts:12:18 - error TS2300: Duplicate identifier 'xit'.

12 declare function xit(expectation: string, assertion?: (done: DoneFn) => Promise<void>, timeout?: number): void;
                    ~~~

  node_modules/@types/jest/index.d.ts:41:13
    41 declare var xit: jest.It;
                   ~~~
    'xit' was also declared here.
../node_modules/@types/jasminewd2/index.d.ts:13:18 - error TS2300: Duplicate identifier 'beforeEach'.

13 declare function beforeEach(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
                    ~~~~~~~~~~

  node_modules/@types/jest/index.d.ts:33:13
    33 declare var beforeEach: jest.Lifecycle;
                   ~~~~~~~~~~
    'beforeEach' was also declared here.
../node_modules/@types/jasminewd2/index.d.ts:14:18 - error TS2300: Duplicate identifier 'afterEach'.

14 declare function afterEach(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
                    ~~~~~~~~~

  node_modules/@types/jest/index.d.ts:35:13
    35 declare var afterEach: jest.Lifecycle;
                   ~~~~~~~~~
    'afterEach' was also declared here.
../node_modules/@types/jasminewd2/index.d.ts:15:18 - error TS2300: Duplicate identifier 'beforeAll'.

15 declare function beforeAll(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
                    ~~~~~~~~~

  node_modules/@types/jest/index.d.ts:32:13
    32 declare var beforeAll: jest.Lifecycle;
                   ~~~~~~~~~
    'beforeAll' was also declared here.
../node_modules/@types/jasminewd2/index.d.ts:16:18 - error TS2300: Duplicate identifier 'afterAll'.

16 declare function afterAll(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
                    ~~~~~~~~

  node_modules/@types/jest/index.d.ts:34:13
    34 declare var afterAll: jest.Lifecycle;
                   ~~~~~~~~
    'afterAll' was also declared here.

Found 41 error(s).

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-api@0.0.1 start: `nest start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nest-api@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mikeg\AppData\Roaming\npm-cache\_logs\2020-03-01T16_11_56_184Z-debug.log

## Expected behavior
at the initial scaffold of the app, it should be running with no issues, for example I don't have a clue what to do now.

## Environment

nest -v
6.14.2

$ node -v
v12.6.0

**Comment by izio38** [comment]
Looks like you have both `@types/jest` and `@types/jasminewd2`, try to remove the package in `package.json` named : `@types/jasminewd2`. Then `npm i` and it should be ok.

**Comment by jmcdo29** [comment]
I'm on node v12.8.1, but I don't think that changes the scaffolding of the project. On Mac I was able to run `npx nest new nest-api -p npm` (use `nest` without globally installing it and set the package manager to npm) without a problem. It definitely looks like you have conflicting types and the original scaffolding only has `@types/jest` so I'm not sure how you got the `@typoes/jasminewd2` in there to conflict. Did you install any other packages? Are ther eany other steps to reproduce this?

**Comment by MikeProcudin** [comment]
Still the same error with `npx nest new nest-api -p npm`.

So what I have is Angular Project and in it I have nest.js and looks like nest.js is trying to grab wrong node models (of Angular project)



![Untitled](https://user-images.githubusercontent.com/19872423/75633959-47599f80-5c01-11ea-88e9-e0ab8d5062ea.png)

**Comment by jmcdo29** [comment]
This isn't a problem of Nest, but rather a problem of Node/NPM and your directory set up. Angular, by default, uses Jasmine as a test runner, whereas NestJS uses Jest (though it is easy enough to configure either technology to use the other). If you're going to be developing an Angular and NestJS application in in the same workspace, I would suggest looking into a monorepo like [Nx](https://nx.dev). Also, make sure if you're running npm commands, you're in the same directory as the matching `package.json`. Don't know if that will completely fix the issue, it may still pull from the parent's `node_module` folder, but it's a good step to take

**Comment by MikeProcudin** [comment]
@jmcdo29  Thnks bro will check that out

**Comment by gerhartz** [comment]
Angular project only here. I had to remove both ` "@types/jasmine": "~3.3.8"` and `"@types/jasminewd2": "~2.0.3",` and then npm i solved it
