### ISSUE TITLE
Lifecycle events in tests not called

### ISSUE THREAD

**Issue by florianbepunkt** [nestjs/nest#4199]
## Current behavior
It looks like the lifecycle event are not called while runnings tests. In my app I have some queue workers that poll the queue via interval. The workers get stopped with the `onModuleDestroy` event. While doing some integration test, I see that the app never quits, jests hangs and my workers keep polling…

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
[Nest] Debug    2.3.2020, 12:11:36 [QueueWorkersService] worker 5e5ce9e3f7f14f0c3b88455f is polling - {}
[Nest] Debug    2.3.2020, 12:11:36 [QueueWorkersService] worker 5e5ce9e3f7f14f0c3b884561 is polling - {}
```

## Input Code

```ts
import { AppModule } from '../../src/app.module';
import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';

const createApp = async (): Promise<INestApplication> => {
  const moduleFixture: TestingModule = await Test.createTestingModule({
    imports: [AppModule]
  }).compile();

  const app: INestApplication = moduleFixture.createNestApplication();
  app.enableShutdownHooks();

  await app.init();

  return app;
};

export { createApp };
```

You can basically test this with any service, e. g:

```ts
export class QueueWorkersService implements OnModuleDestroy {
async onModuleDestroy() { console.log("this should have been called); }
}

```
## Expected behavior
I expect the lifecycle hook to be called

## Environment

<pre><code>
Nest version: 6.10.14

</code></pre>

**Comment by kamilmysliwiec** [comment]
It won't trigger a hook until you call `app.close()`;

**Comment by Cassianokunsch** [comment]
I have a same problem, but when i want test a module where de provider implements a interface OnModuleInit =/

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
