### ISSUE TITLE
Nest can't resolve dependencies

### ISSUE THREAD

**Issue by tx4x** [nestjs/nest#420]
Hi,
I'd like to use my non-NestJS classes (legacy code) in a constructor: 
```ts 
@ApiUseTags('devices')
@ApiBearerAuth()
@Controller('/api/devices')
@UseGuards(AccessGuard)
export class DevicesController extends BaseController {
constructor(
        @InjectRepository(Device)
        private readonly repository: Repository<Device>, // nestjs class
        private contextManager: ContextManager // non-nestjs class 
    ) {
}
```

I get an error with no real hints : 

Error: Nest can't resolve dependencies of the DevicesController (+, +, ?). Please verify whether [2] argument is available in the current context.
    at Injector.<anonymous> (/PMaster/control-freak/xserver/node_modules/@nestjs/core/injector/injector.js:160:23)
    at Generator.next (<anonymous>)
    at fulfilled (/PMaster/control-freak/xserver/node_modules/@nestjs/core/injector/injector.js:4:58)
    at <anonymous>
 1: node::Abort() [node]

I tried all sort of things like adding an import statement in all parent export files (index.ts) or adding the imports statement of the parent module but no, it doesn't work. 

Any idea how to resolve such things? 

thanks,
g

**Comment by mchmielarski** [comment]
Hi,

one of possible solutions:
```
@Module({
  components: [
    { provide: 'CONTEXT_MANAGER', useFactory: () => new ContextManager() }
  ]
})
export clasa YourModule {}
```
and in your controller:
```
constructor(@Inject('CONTEXT_MANAGER') private contextManager: ContextManager) {}
```

**Comment by kamilmysliwiec** [comment]
Hi @tx4x,
You have to use at least one decorator. Another way is a solution proposed by @mchmielarski 🙂

**Comment by tx4x** [comment]
@kamilmysliwiec, ah so Nest is picking my classes up correctly by looking at the metadata? Is there a particular meta field I should write into ? The thing is I can't use nestjs in the other classes.

**Comment by kamilmysliwiec** [comment]
Honestly, I don't understand what exactly you're trying to achieve.

**Comment by tx4x** [comment]
i'd like to have a standard controller emitting certain events on rest calls , caught then in this very base class which then sends model updates via web-socket back to the front-end. I usually do this with custom aspect decorators (@before/@after), not sure yet this can be done nicely in nestjs; i am still fiddling this out. right now, i am trying to build a decorator for all GET/PUT entries which does the nest job but also emits events to the base class, providing the rest path and the arguments (after/before). does this makes sense ? i have the same problem with adding a CLI interface automatically to such controllers but not sure this is even possible.

**Comment by tx4x** [comment]
so somehow i am trying to remove the nestjs specifics/dependencies from my controller implementation and use nestjs only to expose a http interface.

**Comment by kamilmysliwiec** [comment]
Actually, I don't understand an idea.

**Comment by tx4x** [comment]
never mind, got it sorted.

**Comment by jacobkdick** [comment]
BUT HOW, @tx4x? Always, always, ALWAYS put your resolution!

**Comment by sandyksit** [comment]
Hi ,
I am getting error when I run the test case, please help 

● Attacks Controller › should be defined

    Nest can't resolve dependencies of the AttacksService (?). Please make sure that the argument at index [0] is available in the _RootTestModule context.

      at Injector.lookupComponentInExports (../node_modules/@nestjs/core/injector/injector.js:180:19)

  ● Attacks Controller › should be defined

    expect(received).toBeDefined()

    Received: undefined

##attack-controller-spec.ts
`import { Test, TestingModule } from '@nestjs/testing';
import { AttacksController } from './attacks.controller';
import { AttacksService } from './attacks.service';

describe('Attacks Controller', () => {
  let controller: AttacksController;
  let service: AttacksService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AttacksController],
      providers: [AttacksService],
    }).compile();

    controller = module.get<AttacksController>(AttacksController);
    service = module.get<AttacksService>(AttacksService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });  
});
`
## attack-controller.ts
`import { Controller, Inject, Get, Query, Param } from '@nestjs/common';
import { AttacksService } from './attacks.service';
import { Attack } from './interfaces/attacks.interface';
import { GetAttacksDto } from './dto/get-attacks.dto';

@Controller('attacks')
export class AttacksController {
  constructor(@Inject('AttacksService') private readonly attacksService: AttacksService) {}

  @Get()
  async getAttacks(@Query() dto: GetAttacksDto): Promise<Attack[]> {
      return this.attacksService.getAvailableAttacks( dto.id ||'');
  }

  @Get(':id')
  async getAttacksByAttackId(@Param('id') id: string): Promise<Attack[]> {
      return this.attacksService.getAvailableAttacks(id);
  }
}
`
