### ISSUE TITLE
req.body empty in NestMiddleware #2

### ISSUE THREAD

**Issue by danilomartinelli** [nestjs/nest#4205]
## Current behavior
My problem is the same of #3148. I tried the @kamilmysliwiec's solution ([here](https://github.com/nestjs/nest/issues/3148#issuecomment-541043223))

## Input Code
```ts
// app.module.ts

@Module({
  imports: [],
  controllers: [AppController],
  providers: [
    {
      provide: APP_FILTER,
      useClass: AllExceptionsFilter,
    },
  ],
})

export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(LoggerMiddleware)
      .forRoutes({ path: '*', method: RequestMethod.ALL });
  }
}

// logger.middleware.ts

@Injectable()
export class LoggerMiddleware implements NestMiddleware {
  constructor(private readonly dbService: DbService) {}

  async use(req: Request, res: Response, next: Function) {
    const { body } = req;

    console.log(body); // body is undefined!!!

    next();
  }
}
```

## Expected behavior
I would like to get one value from body.

## Possible Solution
My middleware needs to be applied after bodyParser.

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version: 13.6.0
- Platform:  Mac

</code></pre>

**Comment by jmcdo29** [comment]
Do you have a minimum reproduction of this?

**Comment by danilomartinelli** [comment]
> Do you have a minimum reproduction of this? And have you tried with the latest version of Nest?

```ts
// app.module.ts
@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    SendgridModule,
    FormContactModule,
  ],
  controllers: [AppController],
  providers: [
    {
      provide: APP_FILTER,
      useClass: AllExceptionsFilter,
    },
  ],
})
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(LoggerMiddleware)
      .forRoutes({ path: '*', method: RequestMethod.ALL });
  }
}

// form-contact.service.ts
async createEmailJob(data: ContactJobBuilder, file: any) {
    if (data.name.length < 1 || !data.name) {
      throw new BadRequestException('Obrigatório inserir o nome.');
    }

    if (!validateEmail(data.email) || data.email.length < 1) {
      throw new BadRequestException('Obrigatório inserir e-mail válido.');
    }

    if (data.job.length < 1 || !data.job) {
      throw new BadRequestException('Obrigatório inserir a vaga.');
    }
    try {
      const { email, job } = data;

      await this.sendGripService.sendEmail(
        'contato@onbank.com.br',
        job,
        sendNotificationHTML(job),
        file ? file.buffer.toString('base64') : null,
      );

      await this.sendGripService.sendEmail(
        email,
        job,
        sendConfirmationHTML(job),
      );

      return data;
    } catch (error) {
      if (error) {
        throw new InternalServerErrorException(
          'Servico temporariamente indisponível',
        );
      }
    }
  }

// logger.middleware.ts
@Injectable()
export class LoggerMiddleware implements NestMiddleware {
  constructor(private readonly dbService: DbService) {}

  async use(req: Request, res: Response, next: Function) {
    const uidgen = new UIDGenerator();
    const id = await uidgen.generate();

    const { httpVersion, headers, method, baseUrl, params, query, body } = req;
    // body is Undefined!

    const newLogger = new this.dbService.db.Logger({
      id,
      httpVersion,
      headers,
      method,
      baseUrl,
      params,
      query,
      body,
    });

    res.locals.loggerId = id;
    await newLogger.save();

    next();
  }
}
```

On createEmailJob I can use body as data but on middleware req.body always returns undefined.

I made this call on postman:
<img width="898" alt="Captura de Tela 2020-03-02 às 17 07 29" src="https://user-images.githubusercontent.com/28323438/75713377-770fb280-5ca8-11ea-8be8-bcfd45b331f8.png">

**Comment by kamilmysliwiec** [comment]
Are you using Fastify?

**Comment by danilomartinelli** [comment]
> Are you using Fastify?

No

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by jeffminsungkim** [comment]
@danilomartinelli 
Your form is configured to use multipart/form-data. Please give it a try with `x-www-form-urlencoded` instead. (It works) 

Nest handles the following by default.

- URL encoding
- JSON encoding

**Comment by danilomartinelli** [comment]
> @danilomartinelli
> Your form is configured to use multipart/form-data. Please give it a try with `x-www-form-urlencoded` instead. (It works)
> 
> Nest handles the following by default.
> 
>     * URL encoding
> 
>     * JSON encoding
> 
> 
> As a side note, the `body-parser` only handles JSON and urlencoded data, not multipart.

It works. Thanks!

**Comment by Belocum** [comment]
> Are you using Fastify?

I am using Fastify. Do you have any solution to get the request body in Middleware?

**Comment by F2BEAR** [comment]
@jeffminsungkim what if I need to read `multipart/form-data` as a requirement?

If I send a JSON it works as expected but in some of my routes I need multipart/form-data as the request may include files.

**Comment by micalevisk** [comment]
@F2BEAR then you'll need to configure a body parser middlware for that.
