### ISSUE TITLE
body-parser obsolescence

### ISSUE THREAD

**Issue by jeffminsungkim** [nestjs/nest#4209]
Hi, Kamil. I have a question that came into my mind that is there a particular reason why the Nest needs to use `body-parser`? 🤔

```typescript
// platform-express/adapters/express-adapter.ts
import * as bodyParser from 'body-parser';

public registerParserMiddleware() {
  const parserMiddleware = {
    jsonParser: bodyParser.json(),
    urlencodedParser: bodyParser.urlencoded({ extended: true }),
  };
  Object.keys(parserMiddleware)
    .filter(parser => !this.isMiddlewareApplied(parser))
    .forEach(parserKey => this.use(parserMiddleware[parserKey]));
}
```

How about use Express's built-in `body-parser` instead?

**Comment by kamilmysliwiec** [comment]
> How about use Express's built-in body-parser instead?

They are pretty much equal. Honestly, I don't see any reason to switch.

**Comment by jeffminsungkim** [comment]
@kamilmysliwiec 
I agree with your point. It was a small suggestion. I'd like to keep the project dependencies as clean as possible (Less things to manage on my own). Since the Nest uses the latest version of the Express, I thought there's no point in having an extra code if it is not worthy of it to depend on.
