### ISSUE TITLE
mongoose - acsessing data of one collection from anther module

### ISSUE THREAD

**Issue by roeehershko** [nestjs/nest#421]
## Current behavior
i am using the mongoose module, lets say i have User collection which configured in the User module,
Now i need this collection data in the Accounts module, i need to register it again in the Accounts module ?
this is how my modules extract schemas:

Accounts Module
```
MongooseModule.forFeature([
     { name: 'Account', schema: AccountsSchema},
     { name: 'User', schema: UserSchema},
])
```

Users Module
```
MongooseModule.forFeature([
   { name: 'User', schema: UserSchema},
])
```

Is there a better way of doing it?

**Comment by shekohex** [comment]
`MongooseModule` is a Global Scope Module. *i.e has a  `@Global()`  decorator* , so you don't need to Register the Model Again, just inject it;

**Comment by silvelo** [comment]
Remember to export, import the modules correctly

**Comment by roeehershko** [comment]
i am getting out of context error, but after exporting and importing it as @silvelo said it works now, 
couldnt find it anywhere in the docs, maybe worth adding (mongoose docs)

**Comment by silvelo** [comment]
@roeehershko the docs you find this https://docs.nestjs.com/modules, Modules re-exporting explain about it.

**Comment by roeehershko** [comment]
ok thanks, one more question, is it normal that it takes the application 10 seconds to initialize mongoose module ? 
```
[Nest] 350   - 2018-2-14 16:13:06   [InstanceLoader] MongooseCoreModule dependencies initialized +10082ms
```
Also after the initalize it takes approx 20 seconds for the connection to establish

**Comment by silvelo** [comment]
I create 8 collections and 
[Nest] 19344   - 2018-2-14 17:16:02   [InstanceLoader] MongooseCoreModule dependencies initialized +1044ms

It should depend on schemas complexity

**Comment by roeehershko** [comment]
weird, i tried to down it to 1 schema and its still 10 seconds, i just figured the connection delay was due to using the auto-increment plugin, i will try to investigate more

**Comment by silvelo** [comment]
Yes, its weird.
MongooseModule only wrapper the old way to make the connection and schemas.

**Comment by roeehershko** [comment]
your working on windows?

**Comment by silvelo** [comment]
Yes, i am using windows.

You can try this because the way to generate token could make the problem.

Go to this repo, download it and compile with npm run build, then copy the content of dist folder to node_module/@nestjs/mongoose/.
Create a collection at the same way
```
MongooseModule.forFeature([{ name: USER_COLLECTION_NAME, schema: UserSchema }]),
```
The next step is correct the break change:
```
@InjectModel(UserSchema) private readonly userModel: Model<User>
```
to:
```
@InjectModel(USER_COLLECTION_NAME) private readonly userModel: Model<User>
```
https://github.com/silvelo/mongoose

**Comment by roeehershko** [comment]
updated the comment:
issue with docker, i tried to run it without docker and it took less then a second, i guess its gonna be harder to figure this one

**Comment by silvelo** [comment]
Perfect then. you can close the issue.

**Comment by roeehershko** [comment]
well i was able to solve this eventually, i used the machine IP instead of docker container name
so instead of:
```
mongodb://mongo/admin
```
i did:
```
mongodb://192.168.99.100/admin
```
just if anyone is breaking his head on it, probobly some docker internal DNS crap
