### ISSUE TITLE
ExceptionFilters and Pipes for Services

### ISSUE THREAD

**Issue by florianbepunkt** [nestjs/nest#4215]
## Is your feature request related to a problem? Please describe.
In my app I have a lot of services that can either be called by a controller or for example via a cronjob.

For controllers I find the pipe and exception filter feature really helpful. I wonder if it would be possible to use these features on services as well. From the documentation I see that pipes and exception filters can only be bound to a controller.

## Describe the solution you'd like
Pipes: @UsePipes decorator for service methods as well as parameter scoped decorators
Errors: Use the existing error exception filters. Basically they could be scoped to any class method

**Comment by kamilmysliwiec** [comment]
This has been discussed in the past already. We don't plan to allow using enhancers on services level
