### ISSUE TITLE
ApiProperty name is ignored during post request

### ISSUE THREAD

**Issue by vmikhailov** [nestjs/nest#4217]
## Current behavior
There is a possibility to specify alternative name for a property. 
@ApiProperty({ name: 'message_type' })
public messageType: string;

It gets reflected in the swagger documentation but at Post the mapping is ignored and incoming object has a property message_type and is of type Object rather than being specific to expected body type.
@ApiBody is used to specify expected message type.

## Expected behavior
It is expected to have the models properly mapped.

## Possible Solution
There is might be other decorator to simulate the same behaviour

## Environment

<pre><code>
Nest version: 6.11.11

For Tooling issues:
- Node version: 12.14
- TypeScript version: 3.7.4
- Platform:  Mac

Others:
</code></pre>

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
