### ISSUE TITLE
[@nestjs/ng-universal] How to debug nestjs part in the project 

### ISSUE THREAD

**Issue by zajcman** [nestjs/nest#4221]
There is a any way to start project in debug mode link in normal nestjs project 

**package.json**
 "start:debug": "nest start --debug --watch",

Sorry that i ask here but i can't find any anwser on github or stacoverflow or google

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
