### ISSUE TITLE
Global exception handling for SubscribeMessage of WebSocketGateway

### ISSUE THREAD

**Issue by IMalyugin** [nestjs/nest#4229]
## Feature Request
1. Automatically throw unhandled exceptions in handlers of WebSocketGateway;
2. Add a strategy to attach global exception handlers for websockets;

## Is your feature request related to a problem? Please describe.

Is there any reason, why exceptions in ws handlers are swallowed? I mean for http requests - normal behaviour is to throw internal server error with stacktrace in console, but that is not the case for ws.
It can be reproduced with a super straightforward throw:
```
@SubscribeMessage('message')
handleEvent(
  @MessageBody() data: any,
  @ConnectedSocket() client: Socket,
): void {
  console.log('You have a new message');
  throw new Error('A ninja exception');
}
```
Server just runs normally, you see the new message console.log and that is it.
It took me some time to figure out how to properly handle that error to see it thrown by creating a custom AllWsExceptionFilter and applying it to gateway, but that's not exactly a perfect solution, next time i create another WSGateway it's gonna be the same, unless i recall that I need to attach handler.

Also the documentation is not clear on the fact that global error handlers ignore errors in ws, so attaching one didn't help at all.

P.S. Using latest version of nestjs: 6.11.11

## Describe the solution you'd like

It would be nice if by default, when not configured, exceptions in sync and async SubscribeMessage handlers of WebSocketGateway were caught and processed similar to http requests.

## What is the motivation / use case for changing the behaviour?

Simplicity of development, proper out-of-the-box behaviour.

**Comment by kamilmysliwiec** [comment]
Everything is explained in the documentation:

![image](https://user-images.githubusercontent.com/23244943/76064203-7c5f4c80-5f89-11ea-9cf3-640538f4e920.png)

https://docs.nestjs.com/websockets/exception-filters

> With the sample above, Nest will handle the thrown exception and emit the exception message with the following structure:

Hence, in order to "catch" the error on the client-side, simply register a listener for `"exception"` messages.

> Also the documentation is not clear on the fact that global error handlers ignore errors in ws, so attaching one didn't help at all.

![image](https://user-images.githubusercontent.com/23244943/76064278-a1ec5600-5f89-11ea-9969-e10eda3cb0ec.png)
