### ISSUE TITLE
Can't export as library

### ISSUE THREAD

**Issue by tx4x** [nestjs/nest#423]
[x] Feature request
[x] Documentation issue or request

if i run tsc with --declaration I get lots of errors: 

Return type of public method from exported class has or is using name 'DeleteResult' from external module "/PMaster/control-freak/xserver/node_modules/typeorm/query-builder/result/DeleteResult" but cannot be named.
or 

Exported variable 'UserEntity' has or is using name 'PipeTransform' from external module "/PMaster/control-freak/xserver/node_modules/@nestjs/common/interfaces/pipe-transform.interface" but cannot be named.

tsc: 2.7.1
node: 9.4.1

Any glue how to fix this ? 

ps: I'd like to share some code to the front-end
thanks

**Comment by chanlito** [comment]
@tx4x try to specify the return type manually?

**Comment by tx4x** [comment]
hey there, thanks. let me try

**Comment by kamilmysliwiec** [comment]
Hi @tx4x,
Setting a type explicitly should help. However, github issues is not a best place for this kind of questions. Please, use stackoverflow instead.

**Comment by tx4x** [comment]
Hi,
setting the exact return didn't change anything, same for setting it to 'any'. 

Is it possible at all to build nestjs based libraries? would be a desaster for me if now ;-)
thanks,
g

**Comment by tx4x** [comment]
never mind, found the problem: tsc want's to have those unresolved types explicitly imported in the target module.

**Comment by atMari** [comment]
@tx4x , I am having this same issue.  Can you show me a quick example of how you explicitly imported the unresolved types?

**Comment by tx4x** [comment]
@atMari : in the tsc error log you should see at which point it's unable to resolve the name/types. in my case i got : 
src/controllers/groups.controller.ts(142,32): error TS2304: Cannot find name 'ParseIntWithDefaultPipe'.

so I added in groups.controller.ts : 
import { ParseIntWithDefaultPipe } from '../pipes/parse-int-with-default.pipe';
and so forth. 

that is of course annoying and there is a reported Typescript issue about this and they are working on it.
