### ISSUE TITLE
how to get context Id in microservices(e.g. nats) ?

### ISSUE THREAD

**Issue by vinni-jopa** [nestjs/nest#4231]
Hello, following the documentation: https://docs.nestjs.com/fundamentals/module-ref#getting-current-sub-tree
I can get value of request by:

```typescript
@Controller({scope: Scope.REQUEST})
export class RequestController {
constructor(
       @Inject (REQUEST) request: any
}{}
```

but, if i try to get ContexId:
```typescript
request[REQUEST_CONTEXT_ID] === undefined 
```
and
```typescript
ContextIdFactory.getByRequest(request)
```
create new contextId.

I found that the code for generating the contextId is commented out:
https://github.com/nestjs/nest/blob/master/packages/microservices/listeners-controller.ts :129

and so, how do you get the context identifier?

**Comment by jmcdo29** [comment]
You should be using `CONTEXT` instead of `REQUEST` in your `@Inject()` in the constructor. [Quote from the docs](https://docs.nestjs.com/microservices/basics#scopes)
> Request-scoped handlers and providers can inject `RequestContext` using the `@Inject()` decorator in combination with `CONTEXT` token:

**Comment by vinni-jopa** [comment]
ок, let's using something like this:
```typescript
@Controller({scope: Scope.REQUEST})
export class RequestController {
constructor(
       @Inject (REQUEST) request: any,
       @Inject(CONTEXT) context: any
}{}
```
and let's compare params:
```typescript
  this.context === this.request
```
it's the same thing...

**Comment by kamilmysliwiec** [comment]
Thanks for reporting. I'll share solution shortly

**Comment by kamilmysliwiec** [comment]
Fixed in this PR https://github.com/nestjs/nest/pull/4201. Your example will work properly once merged
