### ISSUE TITLE
Expose metadata keys in nestjs/common

### ISSUE THREAD

**Issue by theabuitendyk** [nestjs/nest#4232]
## Is your feature request related to a problem? Please describe.
I'm using the request method decorators from the nestjs/common package (Post, Get, Delete, etc.) and have a controller decorated with an authorization guard. I'd like to perform different authorization logic according to the request method that is available as metadata with the `METHOD_METADATA` key.

In my code I've had to duplicate the metadata key constants and hope that there won't be breaking changes to them going forward.

## Describe the solution you'd like
I'd like for the metadata keys to be exported from the nestjs/common package. The drawback is any changes to those constants would be breaking changes for the public API.

## Teachability, Documentation, Adoption, Migration Strategy
Example usage:
```
import { METHOD_METADATA } from '@nestjs/common';
...

export class AuthorizationGuard implements CanActivate {
  constructor(
    private readonly reflector: Reflector,
  ) {}

  canActivate(context: ExecutionContext) {
    const requestMethod = this.reflector.get<string>(
      METHOD_METADATA,
      context.getHandler(),
    );
    
    switch (requestMethod) {
      case RequestMethod.Get:
         // authorize get
      case RequestMethod.Post:
         // authorize post
      ...
    }
  }
}
```
## What is the motivation / use case for changing the behavior?
Reduces code duplication and allows nestjs users to leverage metadata from publicly exposed decorators.

**Comment by kamilmysliwiec** [comment]
You should never use this metadata - it's considered as private. To determine what type of request you're dealing with, use the `ExecutionContext`:

```typescript
context.switchToHttp().getRequest().method
```

**Comment by cuongphamcxa** [comment]
@kamilmysliwiec : If it is considered as private then there is any way I can read the method params metadata like body dto, query dto...etc?
