### ISSUE TITLE
JWT functionality doesn't work !

### ISSUE THREAD

**Issue by JihenHm** [nestjs/nest#4234]
## Current behavior
Hi, I  have an error when I start using JWT functionnality.
when I add "private readonly jwtService: JwtService" to the constractor in auth.service.ts I have an ExceptionHandler: Nest can't resolve dependencies of the AuthService (?, UserService). Please make sure that the argument JwtService at index [0] is available in the UserModule context.

Potential solutions:
- If JwtService is a provider, is it part of the current UserModule?
- If JwtService is exported from a separate @Module, is that module imported within UserModule?
  @Module({
    imports: [ /* the Module containing JwtService */ ]
  })

## Input Code
auth.service.ts
import { Injectable } from '@nestjs/common';
import {UserService } from '../user/user.service';
import { JwtService } from '@nestjs/jwt';
import { User } from 'src/user/user.entity';

@Injectable()
export class AuthService {
  
  
    constructor(
     private readonly jwtService: JwtService,
      private readonly userService: UserService,
      ) {}

    async validateUser(email: string, pass: string): Promise<any> {
      //const user =new User();
        const user = await this.userService.getUserByEmail(email);
        
        if (user.Password === pass) {
          const { Password, ...result } = user;
          return result;
          //return user;
        }
        return null;
      }

      async login(user: User) {
        const payload = { username: user.Email, sub: user.Id };
        
        return {
          accesstoken: this.jwtService.sign(payload),
        };
      }

      
}

## Environment

<pre><code>
Nest version: 6.14.2
- Node version: 10.16.2
- Platform:   Windows

**Comment by bukhalo** [comment]
Try to run a [code sample](https://github.com/nestjs/nest/tree/master/sample/19-auth-jwt) and find the error in yourself.

**Comment by jeffminsungkim** [comment]
@JihenHm 
```bash
ExceptionHandler: Nest can't resolve dependencies of the AuthService (?, UserService). Please make sure that the argument JwtService at index [0] is available in the UserModule context.
```
Please double check that your auth module has registered the `JwtModule` correctly. This is not the Nest issue.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
