### ISSUE TITLE
[fatal bug!!]typeOrm cant‘ save @Column('simple-json') correctly when body has parameter  equal with the   colunm-value i want to save

### ISSUE THREAD

**Issue by aqnaruto** [nestjs/nest#4235]
## Current behavior

typeOrm is working fine if don't using nest,
but when  post with body,and the body has one of parameter equal with colunm-value i want to save ,it can't save correctly.
it will be ommited by unknow reson
here is my post data 
![image](https://user-images.githubusercontent.com/9067159/76075652-56ad6400-5fd8-11ea-8fc5-7ed37a52ad02.png)
here is my user Entity
![image](https://user-images.githubusercontent.com/9067159/76075749-83617b80-5fd8-11ea-957c-f94af5322541.png)

here is my code 

```ts
async changefollow(@auth() userInfo, @Body() { action, femail, test }) {
const ownUser = await this.userDto.findOne({ email: userInfo.email });
ownUser.following = [3, action, 'fffd', 'ffff'];
return await this.userDto.save([ownUser])
}
```

## Expected behavior
here is 
database saved
![image](https://user-images.githubusercontent.com/9067159/76076146-3af68d80-5fd9-11ea-8197-45e2b1e15e05.png)

it should save [3, action, 'fffd', 'ffff'] , but 'ffff' has been ommited because the body have parameter equals 'ffff'

## Possible Solution
check the reason , and let it work normally

## Environment

<pre><code>
Nest version: ^6.7.1
 
For Tooling issues:
- Node version: v12.3.1
- Platform:  windows 10

**Comment by aqnaruto** [comment]
debug info 
![image](https://user-images.githubusercontent.com/9067159/76078215-274d2600-5fdd-11ea-80a1-c4d5f8f114c8.png)
it execute wrong sql

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by aqnaruto** [comment]
@kamilmysliwiec it not a question ,it a bug report . 
https://discord.gg/G7Qnnhy  this website can't be reached . did you need me provide a minimize demo ?
