### ISSUE TITLE
Scope Singleton missing (v6.8.3)

### ISSUE THREAD

**Issue by jasper-jool** [nestjs/nest#4236]
## Bug Report

The docs tell me that I can make my service a singleton, but this scope does not exist.
https://docs.nestjs.com/fundamentals/injection-scopes

## Current behavior
Scope singleton missing

## Expected behavior
Should be there

## Environment

Nest version: 6.8.3

**Comment by kamilmysliwiec** [comment]
SINGLETON = DEFAULT

**Comment by jasper-jool** [comment]
> SINGLETON = DEFAULT

Wouldn't that make the documentation outdated? ;-)

**Comment by kamilmysliwiec** [comment]
It wouldn't :)

**Comment by brunnerh** [comment]
It makes it harder to understand though. At a glance the documentation states that there is a scope `SINGLETON`, but this value does not exist in the code. In my opinion the presentation should either be such that it does not suggest that these are valid code values (using uppercase and `<code>` blocks) or list the values and explain that default means singleton.

I would recommend changing the `SINGLETON` cell to:

> `DEFAULT` (Singleton)
