### ISSUE TITLE
Upload multiple files with different options

### ISSUE THREAD

**Issue by abhishek6262** [nestjs/nest#4243]
How can we upload multiple files with different options (mime type) and storage path?

I checked the documentation for the details and found `FileFieldsInterceptor` but this interceptor only allows a single set of options and does not allow us to control option based on the field.

Please can anyone help me with this?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
