### ISSUE TITLE
Make type of INestApplication.getHttpServer() be equal to its @returns in jsdoc

### ISSUE THREAD

**Issue by ShGKme** [nestjs/nest#4245]
## Is your feature request related to a problem? Please describe.
In e2e test we may often find lines like `http = app.getHttpServer();` or `request(app.getHttpServer())`, where `getHttpServer()` return any, but we exacly now, it's a http server. 

`@nestjs/core/interfaces/nest-application.interface.ts` has `getHttpServer()` method, that returns `any;` while jsdoc above has `* @returns {http.Server}`.

https://github.com/nestjs/nest/blob/403e4454405baa833bf2eef0a8b11578a58e9bec/packages/common/interfaces/nest-application.interface.ts#L95-L100

## Describe the solution you'd like
Maybe return http.Server directly? If it depends on express or fastify, maybe add some generic or smth like that? Otherwise, jsdoc shouldn't contain `* @returns {http.Server}`.

**Comment by kamilmysliwiec** [comment]
Fixed in this PR https://github.com/nestjs/nest/pull/4201

**Comment by ShGKme** [comment]
Why it cannot return http.Server instead of any?
