### ISSUE TITLE
Get all dto's metatypes

### ISSUE THREAD

**Issue by stepanzabelin** [nestjs/nest#4246]
## Feature Request
Swagger solves an important problem - the interaction between front-end and back-end. But it is limited by standard OpenAPI. The data that the swagger generates is not enough for front-end. 
I would like to send validation schemas from API in the development process to synchronize 
 validation schemas with front-end. So, a function is needed which can get dto's metatypes then I would handle these metatypes and pull out their validation schemas into json
Then, the front-end would be able to download ready-made validation schemas into the project and this would greatly simplify the development process

## Describe the solution you'd like

A new function kind of
`const definitions = SwaggerModule.getDefinitions(app);
`

![image](https://user-images.githubusercontent.com/45755031/76203086-15e76200-6207-11ea-9313-455695aa2f45.png)

**Comment by kamilmysliwiec** [comment]
We don't plan to add such a feature in the near future
