### ISSUE TITLE
Unknown authentication strategy "local"

### ISSUE THREAD

**Issue by atefbenbelgacem** [nestjs/nest#4247]
## Current behavior
I've followed the docs at https://docs.nestjs.com/techniques/authentication. and got this error: "Error: Unknown authentication strategy "local", despite that I think that I've done everything right.

## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: 6.14.2

 
For Tooling issues:
- Node version: 12.13.1  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Bulletninja** [comment]
I have the same issue, everything seems ok to me but keeps telling me "Unknown authentication strategy "local""

**Comment by jmcdo29** [comment]
As Kamil said __over a year ago__, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
