### ISSUE TITLE
Transform id from request params to object

### ISSUE THREAD

**Issue by fireridlle** [nestjs/nest#4248]
Hello everyone. Question is pretty simple but can't reach solution.
Let's say i have list of endpoints that accept id as a param. example: `@Post(':id/someroute')`
I would like each endpoint with param `:id` automatically check if entity exists and if yes return it to controller

What i have tried.

Pipe
```
@Injectable()
export class IdTransform implements PipeTransform<string, Promise<IdObjectDTO>> {
  constructor(private repository: Repository) {}
  async transform(value: string): Promise<IdObjectDTO> {
    const object = await this.repository.getById(value);
    if (!object) {
      throw new BadRequestException(`Object "${value} not found"`);
    }
    return object;
  }
}
```

DTO
```
export class IdObjectDTO {
  @ApiProperty()
  prop1: string;
  @ApiProperty()
  prop2: string;
}
```

Controller
```
  @Post(':id/someroute')
  someRoute(@Param('id', IdTransform) object: IdObjectDTO) {
    return id;
  }
```

In that case swagger ui show that id has type IdObjectDTO and doesn't allow me to send request.
If i change controller to be `@Param('id', IdTransform) object: string` it works. But the issue that object has type string and i can't work with it like with object

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
