### ISSUE TITLE
Apply middleware for routes(string) has regressed #692

### ISSUE THREAD

**Issue by jasperblues** [nestjs/nest#4259]
## Bug Report

Issue #692 appears to have regressed.  

## Current behavior

Create middleware as follows: 

```typescript
export class AppModule implements NestModule {
    configure(consumer: MiddlewareConsumer): any {
        consumer.apply(TransactionContextMiddleware).forRoutes('**/**');
    }
}
```

Run the app standalone from a startup script: 

*Expected:*
Middleware is applied

*Actual:* 
Middleware is not applied

Run the app using a test case and supertest works. eg: 

```
beforeAll(async () => {
        const moduleFixture: TestingModule = await Test.createTestingModule({
            imports: [AppModule]
        }).compile();

        app = moduleFixture.createNestApplication();
        await configureApp(app);
        await app.init();
    });
```

^-- works

## Input Code

```ts
const your = (code) => here;
```

## Possible Solution
Works in NestJS 6.8.3. Does not work in 6.11.11

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by jeffminsungkim** [comment]
I guess that's normal behavior. Have a look at [#4210](https://github.com/nestjs/nest/issues/4210#issuecomment-595037635)

**Comment by jasperblues** [comment]
Here is a repository that reproduces the issue: https://github.com/liberation-data/drivine

*Steps to Reproduce:* 

* Install/run Neo4j. 
* Load [this gist](https://gist.github.com/jasperblues/7a6e774090c9ef0f18c44920b48b6b23). 
* Start the app `npm run start-test-app` 
* Hit this url: http://localhost:3000/routes/between/NYC/Pigalle. (works)
* Update to latest nest in package.json, hit same URL (breaks) 

Sorry, I don't have time to provide a more minimal repository in the coming days. Close the issue if you like.  The bug will be still be there when you get back.

**Comment by kamilmysliwiec** [comment]
There's no test app in this repo (nor `start-test-app`). Please, next time when you find some time, create an issue with a minimal repository so we can better understand what exactly you're trying to report.

**Comment by jasperblues** [comment]
Sorry, I forgot to push 🤦‍♂ (wrong ssh keys).  It is there now, if you want to have a look. 

Otherwise, I will provide a repo later.

**Comment by xv-jasper-b** [comment]
Update: *We found a workaround:*

```consumer.apply(TransactionContextMiddleware).forRoutes('');```
^-- This will work for all routes. 

```consumer.apply(TransactionContextMiddleware).forRoutes('*');```
^-- This will not work

```consumer.apply(TransactionContextMiddleware).forRoutes('**/**');```
^-- This will not work either

Appears to be a regression of #692 and does not match previous versions of Nest or docs. 

*It does not occur when running via NestJS testing module!!*

**Comment by jasperblues** [comment]
Update: We found a workaround:

```consumer.apply(TransactionContextMiddleware).forRoutes('');```
^-- This will work for all routes.

```consumer.apply(TransactionContextMiddleware).forRoutes('*');```
^-- This will not work

```consumer.apply(TransactionContextMiddleware).forRoutes('**/**');```
^-- This will not work either

Appears to be a regression of #692 and does not match previous versions of Nest or docs.

It does not occur when running via NestJS testing module!!
