### ISSUE TITLE
Logging: method to turn on ISO8601 format

### ISSUE THREAD

**Issue by lorenzleutgeb** [nestjs/nest#4262]
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
Have Nest.js loggers use an ISO8601 conform timestamp by default.

## Teachability, Documentation, Adoption, Migration Strategy
Not really required. Folks that parse log output might be annoyed or have their parsing logic break, so this should be done as part of a major release.

## What is the motivation / use case for changing the behavior?
ISO8601 is just the best way we have to format dates.
Humorous: https://xkcd.com/1179/ and https://i.imgur.com/TKJkOWu.png

**Comment by kamilmysliwiec** [comment]
Thanks for your proposal! We have discussed this issue many times in the past and we're not planning to change the default behavior. However, this might be a good idea to provide an additional method to customize the date format (so anyone who is interested in using ISO8601 doesn't necessarily have to implement the logger from scratch).

**Comment by 5c0r** [comment]
Hello, 
I was thinking if we could either use optional injection as a function so user can injection their own timestamp function

Below can be an example
`{
      provide: 'TIMESTAMP_FORMAT',
      useValue: () => string = ( ) => new  Date().toISOString(),
    },`

**Comment by xuzaixian** [comment]
what about implement this inside logService which provide a funciton maybe called  `getTimestamp`.
we can extend logService and override the function then `useLogger(MyLogService)`

**Comment by kamilmysliwiec** [comment]
@xuzaixian sounds good 👍

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/5681

**Comment by Karman40** [comment]
Hi, thanks for the discussion above! I was wondering what the current status of this issue is. Is there now an officially supported way to override or configure the timestamp format used by the built-in Logger? I couldn’t find exact documentation for this in the official NestJS docs. Thanks

**Comment by jonasbn** [comment]
@Karman40 the following worked for me:

```javascript
class CustomLogger extends ConsoleLogger {
  protected getTimestamp(): string {
    return new Date().toISOString();
  }
}

async function bootstrap() {
  const logger = new CustomLogger({
    colors: false,
    prefix: 'fetch-geodata', // Default is "Nest"
    json: true,
    logLevels: ['fatal', 'error', 'warn'],
  });

  const app = await NestFactory.create(AppModule, {
    logger: logger,
  });

...
```
