### ISSUE TITLE
Shutdown hooks only work intermittently on linux

### ISSUE THREAD

**Issue by Roaders** [nestjs/nest#4263]
## Current behavior
`beforeApplicationShutdown` (and other pre shutdown hooks) only works sometimes on linux. They seem to work reliably on windows

## Environment
- Node version: 10.15.1
- Platform:  Linux

I am calling `enableShutdownHooks()` but the hooks that are called when the server are killed are only triggered very occasionally. I have been ripping my application apart trying to figure out what has broken it as this used to work but I have discovered that if I run the app and the hooks work running the exact same compiled code again the hooks don't work.

This is very frustrating and means that I have hundreds of registrations of servers left hanging around that died long ago but as these hooks did not fire they have not de-registered themselves.

Calling `app.close()` in code does seem to work. I am testing by using ctrl-c in a terminal to kill the server. This does not reliably work.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by Roaders** [comment]
I'm afraid that I'm not able to do that. I work in a locked down environment that does not allow access public git access.

**Comment by kamilmysliwiec** [comment]
I'm not sure how we can reproduce your issue then. Every issue is reproducible and we haven't encountered anything that you described above. In fact, "shutdown hooks" is a very simple feature, a thin abstraction layer on top of the native `process.on(...)` API. Behind the scenes, we call, e.g. `process.on('SIGTERM', listener)` where the `listener` is a reference to your method and that's it. Thus, I doubt your issue is even related to NestJS but should be rather reported in Node.js repo.

**Comment by Roaders** [comment]
I have implemented my own code that does `process.on(...)` and so far it seems to be working consistently. If this fails in the same way at a later point I'll come back and update this issue.
At some point I might try and reproduce at home.

**Comment by kamilmysliwiec** [comment]
Also, here's what we are doing underneath to setup listeners https://github.com/nestjs/nest/blob/11ce74cafce39d4b752cda4ef7fb57ea080fad04/packages/core/nest-application-context.ts#L166 As I've mentioned, it's fairly short

**Comment by kamilmysliwiec** [comment]
Please, if you find a way on how to reproduce this issue, create a separate one with a repository URL included

**Comment by BrunnerLivio** [comment]
It is a Windows Limitation we can not overcome.

From [godaddy/terminus](https://github.com/godaddy/terminus#limited-windows-support).
Let's add this to the documentation @kamilmysliwiec ?

> Due to inherent platform limitations, terminus has limited support for Windows. You can expect SIGINT to work, as well as SIGBREAK and to some extent SIGHUP. However SIGTERM will never work on Windows because killing a process in the task manager is unconditional, i.e., there's no way for an application to detect or prevent it. Here's some relevant documentation from libuv to learn more about what SIGINT, SIGBREAK etc. signify and what's supported on Windows - http://docs.libuv.org/en/v1.x/signal.html. Also, see https://nodejs.org/api/process.html#process_signal_events.

**Comment by kamilmysliwiec** [comment]
Sounds good @BrunnerLivio. Would you like to create a PR? :)
