### ISSUE TITLE
Out of the box uncaught exception logging for WebSocketGateway

### ISSUE THREAD

**Issue by IMalyugin** [nestjs/nest#4267]
Feature request I created was closed instantly with discussion lock #4229 as a support request, but it was never meant to be one.

The idea of request is that you currently CAN handle exceptions in WebSockets, but they are not handled out of the box, instead they are swallowed entirely which makes it very complicated for early debugging. So the idea was to add out of the box error handling, throwing uncaught exception or at least swallowing exception with a warning in console is better and more user friendly than not doing anything if there was a crash with no filters attached.

Sorry for opening a duplicate, I'm not trying to be noisy, I love the way NestJS works and so far really enjoying using it, but the reply didn't say anything about why it was meant this way, or that it's too complicated to implement.

E.g. if there is no filter, at least throw a warning in server console:
```
Warning: There was an uncaught exception in SubscribeMessage call,
but no filter is attached.
```

**Comment by kamilmysliwiec** [comment]
Oh, I'm sorry! I think I've misunderstood your previous issue. 

I totally agree! We should log unknown/unrecognized (so these that don't inherit from the `WsException` class) exceptions thrown from any subscribe message handler (we're already doing this for HTTP and micro services). I fixed this as part of this commit: https://github.com/nestjs/nest/commit/3fcde293b72ce78847b37d639a474b4ef7156dd8 It will be added in the new release.

**Comment by IMalyugin** [comment]
Sweet, thanks!
