### ISSUE TITLE
Cannot reconnect if one of  RabbitMQ host in cluster array URLs does not exist

### ISSUE THREAD

**Issue by hatung** [nestjs/nest#4268]
## Current behavior

RabbitMQ  client does not reconnect  if the first rabbitMQ host of cluster does not exist 
Exception:
[Nest] 17296   - 03/11/2020, 5:02:52 PM   [ClientProxy] Disconnected from RMQ. Trying to reconnect. +2035ms
[Nest] 17296   - 03/11/2020, 5:02:52 PM   [ClientProxy] Object:
{
  "err": {
    "cause": {
      "errno": "ECONNREFUSED",
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 6672
    },
    "isOperational": true,
    "errno": "ECONNREFUSED",
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "127.0.0.1",
    "port": 6672
  }
}
## Input Code

```ts

  public connect(): Promise<any> {
    if (this.client) {
      return this.connection;
    }
    this.client = this.createClient();
    this.handleError(this.client);
    this.handleDisconnectError(this.client);

    const connect$ = this.connect$(this.client);
    this.connection = this.mergeDisconnectEvent(this.client, connect$)
      .pipe(
        switchMap(() => this.createChannel()), 
        share(),
      )
      .toPromise();

    return this.connection;
  }


  public mergeDisconnectEvent<T = any>(
    instance: any,
    source$: Observable<T>,
  ): Observable<T> {
    const close$ = fromEvent(instance, DISCONNECT_EVENT).pipe(
      map((err: any) => {
        throw err;
      }),
    );
    return merge(source$, close$).pipe(first());
  }

```

## Expected behavior
Retry to connect other host of RabbitMQ cluster and application continuously

## Possible Solution

Should not throw error and subscribe 'connect' event then call  this.createChannel()), 

## Environment
Use cluster RabbitMQ enviroment

```
app.connectMicroservice({
        transport: Transport.RMQ,
        options: {
            urls: configService.get('RABBITMQ_URL').split(','),
            queue: QueueConst.CATEGORY_QUEUE,
            queueOptions: { durable: false }
        },
    });

```

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
