### ISSUE TITLE
Controller gets mapped but returns 404 when trying to access routes

### ISSUE THREAD

**Issue by DaCurse** [nestjs/nest#4269]
## Current behavior
When running my application, the console says that a certain controller's routes were mapped but when I try to acess them via postman I get a 404 error
![image](https://user-images.githubusercontent.com/26578884/76422271-9942b800-63ad-11ea-9f16-29a79bc04b66.png)

My controller is connected to a module which has it's own application created using `NestFactoryStatic`, so this might be the issue. I have also tried creating various dummy routes, setting a global prefix, everything was logged to the console as it was working but it did not. Routes for the other application being created using another `NestFactoryStatic` worked without problem.

## Input Code
Controller:
```ts
@Controller()
export class RedirectController {
	constructor(private readonly redirectService: RedirectService) {}

	@Get(':shortId')
	async redirect(
		@Param('shortId') shortId: string,
		@Res() res: Response,
	): Promise<void> {
		const originalUrl = await this.redirectService.getOriginalUrl(shortId);
		res.redirect(originalUrl);
	}
}
```
Module:
```ts
@Module({
	imports: [
		TypeOrmModule.forRoot(typeOrmRedirectConfig),
		TypeOrmModule.forFeature([LinkRepository], 'redirect'),
	],
	controllers: [RedirectController],
	providers: [RedirectService],
})
export class RedirectModule {}
```
main.ts:
```ts
async function bootstrap() {
	const server = new ExpressAdapter();

        // These routes work
	const apiFactory = new NestFactoryStatic();
	const apiApp = await apiFactory.create(ApiModule, server);
	apiApp.setGlobalPrefix('api/v1');
	await apiApp.init();

        // These get mapped but don't work
	const redirectFactory = new NestFactoryStatic();
	const redirectApp= await redirectFactory.create(RedirectModule, server);
	await redirectApp.init();

	http.createServer(server.getInstance()).listen(process.env.PORT || 3000);
}
```

## Expected behavior
The routes should return a response

## Environment

<pre><code>
Nest version: 6.10.14
Updated all packages to latest version, the issue still occurs with nest 6.11.11
 
For Tooling issues:
- Node version: 12.6.1
- Platform:  Windows 10 64 Bit

Others:
Using yarn, vscodium
</code></pre>

**Comment by jmcdo29** [comment]
@DaCurse this is the same thing I warned you about on Discord yesterday relating to #4114. In short, the routes **do** get mapped, but they get mapped after a not found handler has already been mapped, so while they do exist in the route handler, the routes can never be called. #4186 is a PR with a possibility to fix it, if you'd like to take a look at the discussion there.

**Comment by DaCurse** [comment]
@jmcdo29 Thank you, I will follow that pull request

**Comment by OysterD3** [comment]
I found a workaround `await Promise.all([apiApp.init(), redirectApp.init()])`

**Comment by j-a-h-i-r** [comment]
Still getting this error on `7.6.15`

**Comment by jmcdo29** [comment]
@j-a-h-i-r please create a new issue with a minimum reproduction Repository.

**Comment by j-a-h-i-r** [comment]
> @j-a-h-i-r please create a new issue with a minimum reproduction Repository.

Hi, I've created an issue https://github.com/nestjs/nest/issues/7384
