### ISSUE TITLE
Infinite retryAttempts

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#4270]
## Is your feature request related to a problem? Please describe.
When creating a microservice or a client (e.g. with redis) it is possible to set the `retryAttempts`, which default to 0. But I would like to set it to infinite.

## Describe the solution you'd like
- Set to `-1` to have infinite retryAttempts
- `-1` might be the default
- `retryDelay` might have something greater than `0` as default

## What is the motivation / use case for changing the behavior?
I dont see any reason why it should stop trying. If Redis is down i would like the app to retry until it is Redis back up. Even if it takes a day. But if I set it to a value like 9999 it might end retrying.

**Comment by kamilmysliwiec** [comment]
You can set it to `Infinity`, as follows:
```
{
   retryAttempts: Infinity,
}
```

**Comment by MickL** [comment]
Thank you! Do you want to add the info to the docs?
