### ISSUE TITLE
Nest doesn't find reflect-metadata with everything installed supposedly correctly

### ISSUE THREAD

**Issue by DaCurse** [nestjs/nest#4273]
## Current behavior
In my project, I get the following exception when trying to run the project:
```
<path>\link-shortener-backend\node_modules\@nestjs\common\decorators\core\optional.decorator.js:21
            const args = Reflect.getMetadata(constants_1.OPTIONAL_DEPS_METADATA, target) || [];
                                 ^

TypeError: Reflect.getMetadata is not a function
```
The error also happens in `injectable.decorator.js` if I comment out the code that uses `Reflect` in `optional.decorator.js`
I am not using `Reflect` anywhere in my code.

## Input Code
You can reproduce the issue by cloning and trying to run this repo: https://github.com/DaCurse/link-shortener-backend

## Expected behavior
The error should not occur and `reflect-metadata` should be found

## Possible Solution
I can fix the issue by manually going the file that the issue is coming from, and requiring `reflect-metadata`, but only in some specific ones (Specifically `optional.decorator.js` and `injectable.decorator.js`)

## Environment
```
$ nest info

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : Windows 10
NodeJS Version : v12.16.1
YARN Version    : 1.22.0

[Nest CLI]
Nest CLI Version : 6.14.2

[Nest Platform Information]
platform-express version : 6.11.11
passport version         : 6.2.0
typeorm version          : 6.3.4
common version           : 6.11.11
core version             : 6.11.11
jwt version              : 6.1.2
```

**Comment by kamilmysliwiec** [comment]
`reflect-metadata` is loaded by barrel files (`index.ts` files of `@nestjs/...` packages). In your code, you're using nested imports what, in case of NestJS, is always considered as bad practice.

See here: https://github.com/DaCurse/link-shortener-backend/blob/master/src/main.ts#L1-L2

`NestFactoryStatic` is a private API and should never be used. Similarly, you should replace this:

```
import { ExpressAdapter } from '@nestjs/platform-express/adapters/express-adapter';
```

with this:

```
import { ExpressAdapter } from '@nestjs/platform-express';
```
