### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Bautista-Baiocchi-lora** [nestjs/nest#4283]
## Current behavior
when running 'npm run start' I get an error as described here: https://stackoverflow.com/questions/59435293/typeorm-entity-in-nestjs-cannot-use-import-statement-outside-a-module

## Input Code
repo: https://github.com/Bautista-Baiocchi-lora/LAB1-Server

```ts
import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export default class Barrio{

    @PrimaryGeneratedColumn()
    barrio_id: number;

    @Column()
    email: string;

    @Column()
    password: string;

    @Column()
    name: string;

}
```

## Expected behavior
Server should start up without any problems.

## Environment
package.json

{
  "name": "nest-typescript-starter",
  "private": true,
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^6.10.14",
    "@nestjs/core": "^6.10.14",
    "@nestjs/platform-express": "^6.10.14",
    "@nestjs/typeorm": "^6.3.4",
    "pg": "^7.18.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.5.4",
    "typeorm": "^0.2.24"
  },
  "devDependencies": {
    "@nestjs/cli": "^6.13.2",
    "@nestjs/schematics": "^6.8.1",
    "@nestjs/testing": "^6.10.14",
    "@types/express": "^4.17.2",
    "@types/jest": "^24.9.1",
    "@types/node": "^13.1.6",
    "@types/supertest": "^2.0.8",
    "@typescript-eslint/eslint-plugin": "^2.12.0",
    "@typescript-eslint/parser": "^2.12.0",
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-import": "^2.19.1",
    "jest": "^24.9.0",
    "prettier": "^1.18.2",
    "supertest": "^4.0.2",
    "ts-jest": "^24.3.0",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^3.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

**Comment by jmcdo29** [comment]
I'll go ahead and answer this with a rehash of my answer on the StackOverflow question you linked: you are trying to load Typescript files while running JavaScript, which will fail 100% of the time. Your `entities` array of your `TypeOrmModule.forRoot()` configuration is looking for `js` and `ts` files in the `src` directory, which should be only where your `ts` files live. Your `js` files should exist solely in `dist` (at least the ones created from compilation), and you shouldn't really look for the `ts` files in the first place. If you want to be able to load `ts` or `js` files, you should use `__dirname` instead of `src`. In the end though, as you should be using `node` to run the server, and so long as you aren't using `ts-node` for development, you should replace the line completely with `dist/**/*.entity.js`

**Comment by kamilmysliwiec** [comment]
Thanks for sharing the solution @jmcdo29 :)

**Comment by Bautista-Baiocchi-lora** [comment]
> I'll go ahead and answer this with a rehash of my answer on the StackOverflow question you linked: you are trying to load Typescript files while running JavaScript, which will fail 100% of the time. Your `entities` array of your `TypeOrmModule.forRoot()` configuration is looking for `js` and `ts` files in the `src` directory, which should be only where your `ts` files live. Your `js` files should exist solely in `dist` (at least the ones created from compilation), and you shouldn't really look for the `ts` files in the first place. If you want to be able to load `ts` or `js` files, you should use `__dirname` instead of `src`. In the end though, as you should be using `node` to run the server, and so long as you aren't using `ts-node` for development, you should replace the line completely with `dist/**/*.entity.js`

Sorry for bring the problem back up. Your solution worked only AFTER i rebuilt the dist directory. I found that dist had old build files. These were clashing with the new changes.

**Comment by zquintana** [comment]
In case anyone else is wondering about this checkout this answer on stackoverflow https://stackoverflow.com/a/61119284/1072058.

**Comment by btd1337** [comment]
Structure to support migrations:

```typescript
// FILE: src/config/ormconfig.ts

const connectionOptions: ConnectionOptions = {
  
  // Other configs here

  // My ormconfig isn't in root folder
  entities: [`${__dirname}/../**/*.entity.{ts,js}`],
  synchronize: false,
  dropSchema: false,
  migrationsRun: false,
  migrations: [getMigrationDirectory()],
  cli: {
    migrationsDir: 'src/migrations',
  }
}

function getMigrationDirectory() {
	const directory = process.env.NODE_ENV === 'migration' ? 'src' : `${__dirname}`;
	return `${directory}/migrations/**/*{.ts,.js}`;
}

export = connectionOptions;
```

```json
// FILE package.json

{
  "scripts": {
    "typeorm": "NODE_ENV=migration ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --config src/config/database.ts",
	"typeorm:migrate": "NODE_ENV=migration npm run typeorm migration:generate -- -n",
	"typeorm:run": "NODE_ENV=migration npm run typeorm migration:run",
	"typeorm:revert": "NODE_ENV=migration npm run typeorm migration:revert"
  }
}

**Comment by jocbarbosa** [comment]
Actually, typeorm was designed to work with javascript by default.
To run the migrations with typescript, you must tell typeorm to do it.
Just put in your package.json, in the **scripts** part this line below:

`"typeorm": "ts-node-dev ./node_modules/typeorm/cli.js"`

and then, try to migrate again:

`yarn typeorm migration:run`

**Comment by augustnmonteiro** [comment]
One thing to check as well is if you are not importing `typeorm/browser` instead of `typeorm` I just spent way to much time to figure that this was the problem.

**Comment by Juraj-Masiar** [comment]
I'm still unable to auto-run migrations with the `migrationsRun: true,` switch without failing with this error.
The only way I can make it work is renaming it to ".js" and removing types and changing to commonjs export:
```
module.exports = class AuthTokenAddEmail1612821117049 {
    async up(queryRunner) {
        await queryRunner.query(`ALTER TABLE "auth_token" ADD COLUMN "email" TEXT`);
    }
    async down(queryRunner) {
        await queryRunner.query(`ALTER TABLE "auth_token" DROP COLUMN "email"`);
    }
}
```
I'm not sure if migrations in Nest + TypeORM doesn't work with TS out of box, but I guess using javascript for migrations is totally fine, it's not like TypeScript adds any value here (as long as you don't use the API that is...).

**Comment by mikejtaylor22** [comment]
I am having the same issue "SyntaxError: Cannot use import statement outside a module"

My ormconfig.ts looks like:

`const config: ConnectionOptions = {
  type: "postgres",
  host: "localhost",
  port: Number(port),
  username: "***",
  password: "***",
  database: "***",
  synchronize: false,
  migrations: ["dist/src/migrations/*.js"],
  entities: ["dist/src/models/*/*.entity{.ts,.js}"],
  cli: {
    migrationsDir: "src/migrations",
  },
};

export = config;
`

and app module
`
import { Module } from "@nestjs/common";
import { ConfigModule, ConfigService } from "@nestjs/config";
import { TypeOrmModule } from "@nestjs/typeorm";
import { getConnectionOptions } from "typeorm";

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      useFactory: async () =>
        Object.assign(await getConnectionOptions(), {
          autoLoadEntities: true,
        }),
    }),
    UsersModule,
/* more modules here
  ],
})
export class AppModule {}`

Anyone able to point me in the right direction?

**Comment by jmcdo29** [comment]
There's several resources in this thread already about the error message. If you need more assistance, please use our [Discord](https://discord.gg/nestjs) for support.
