### ISSUE TITLE
Service sharing from Higher modules to Lower Modules

### ISSUE THREAD

**Issue by javadparvaresh** [nestjs/nest#4288]
## Bug Report

To have a modular system, needed to register some providers independent of the target module. Imaging ModuleA has imported ModuleB. ModuleB provides a `LoggerService` which required `LoggerProvider`. ModuleA provider `LoggerProvider`.  so:

LoggerService -> depends -> LoggerProvider
ModuelB -> providers -> LoggerService
ModuleA -> imported -> ModuleB.
ModuleA -> providers -> LoggerProvider

in this case, the expected behavior is to have access to the `LoggerProvider` in LoggerService. but get 
`Nest can't resolve dependencies of the LoggerService (?). Please make sure that the argument ILOGGERPROVIDER at index [0] is available in the LoggerModule context.` error.

Here is the sample code : 

```ts
const TOKEN="token";
class ILoggerProvider{
    write:(...);
}

@Injectable()
class LoggerService{
    constructor(@Inject(TOKEN) private readonly provider: ILoggerProvider) {}
}


@Module({
    providers: [
        LoggerService,
        ],
})
export class LoggerModule {}

Module({
    imports: [LoggerModule],
    providers: [
    {
        provide: LOGGER_PROVIDER_INJECTION_TOKEN,    
        useValue: {
        write: () => null,
        },
    }],
})
export class AppModule {}

```

## Current behavior
Error occures : `Nest can't resolve dependencies of the LoggerService (?). Please make sure that the argument ILOGGERPROVIDER at index [0] is available in the LoggerModule context.`

## Expected behavior
Should `LoggerProvider` inject into the `LoggerService`.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: v13.8.0
- Platform:  Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
This has been discussed many times in the past. Please, check the documentation https://docs.nestjs.com/modules or look for similar issues on Github

**Comment by javadparvaresh** [comment]
@kamilmysliwiec Why do you think I haven't read the documentation and also I haven't checked issues?

as I read in the documentation, there is only this fact, that the module only can inject the imported module, but what is the solution for this problem?!

**Comment by jmcdo29** [comment]
You're looking at a circular reference between the `AppModule` and the `LoggerModule` as the `LoggerModule` needs a value from the `AppModule`, but the `AppModule` needs to import the `LoggerModule`. In this case, I'd say avoid it however you can, probably by using a [Dynamic Module](https://docs.nestjs.com/fundamentals/dynamic-modules) so that you can set up a `forRoot()`/`forRootAsync()` static method to allow passing configurations.

**Comment by javadparvaresh** [comment]
@jmcdo29 actually not, it's not circular reference, the main problem is to be able to configure the child Module by defining the services. 

for example, needed to pass the default context parameter to logger service by `rootModule`.  so the logger service will inject `defautlContextParameter` and use in logging process. 

in order to fix that, in nestjs it seems i need to create `Global` module.

**Comment by kamilmysliwiec** [comment]
> @jmcdo29 actually not, it's not circular reference, the main problem is to be able to configure the child Module by defining the services.

@javadparvaresh this is exactly the circular reference. What you're describing here is not a bug, but a fundamental Nest design decision. Please, check out this chapter https://docs.nestjs.com/modules for more information
