### ISSUE TITLE
Importing external file breaks build

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#4289]
## Current behavior

When importing an external file outside of the project root the build is kind of weird and the compiler throws an error:

![Bildschirmfoto 2020-03-12 um 17 46 01](https://user-images.githubusercontent.com/5103210/76545144-856c8400-6489-11ea-9116-0e794fb33eb9.png)

![Bildschirmfoto 2020-03-12 um 17 47 15](https://user-images.githubusercontent.com/5103210/76545148-88677480-6489-11ea-86e1-0c2e2acd6e2c.png)

## Input Code
```ts
import { PORT_ADMIN } from '../../shared/config';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  await app.listen(PORT_ADMIN);
}
bootstrap();
```

Why:
I do have multiple Nest apps in one repo that should share some variables and functions.

**Comment by uc4w6c** [comment]
You neet to modify `nest-cli.json`.

```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "admin/src"
}
```

This is a repository for reference just in case.

Example: https://github.com/uc4w6c/nest-issue-4289

If you still have a problems, please use our (Discord)[https://discordapp.com/invite/G7Qnnhy]  channel.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by MickL** [comment]
Thanks, but now the cli does not work correct anymore. When I do `nest g module auth` it creates it outside of the src folder:

<img width="259" alt="Bildschirmfoto 2020-03-16 um 16 07 54" src="https://user-images.githubusercontent.com/5103210/76771920-5c593580-67a0-11ea-8089-951087486484.png">

**Comment by MickL** [comment]
The problem was that I did not create a monorep as explained here:
https://docs.nestjs.com/cli/monorepo

Then [Libraries](https://docs.nestjs.com/cli/libraries) can be created and Webpack is used for building the app.

**Comment by uc4w6c** [comment]
@MickL 
Sorry. My first explanation was wrong.

But if you have single project + external file, you don’t have to use monorepo.
We need to make project in Root Directory.
It will be as follows.
<img width="400" alt="スクリーンショット 2020-03-21 9 59 52" src="https://user-images.githubusercontent.com/36355491/77216263-70b08000-6b5c-11ea-91a7-0229974326c0.png">

If you have multiple project, you need to use monorepo.
