### ISSUE TITLE
Position based 

### ISSUE THREAD

**Issue by AnanthGopal** [nestjs/nest#4290]
I created a service by using NESTJS. Consider I have two or more get service in a controller so that I need to give the name each get method like @Get("getDetails"),@Get("getDetailsWithPagination"), 
`import { Controller, Get, Query, Param, Post, Body, Put, Delete, HttpStatus } from '@nestjs/common';
import { GeneralCodeService } from 'src/service/general-code.service';
import { Generalcode } from 'src/entities/Generalcode';
import { ApiTags, ApiQuery, ApiParam } from '@nestjs/swagger';
import { Pagination } from 'nestjs-typeorm-paginate';
import { PageRequest } from 'src/model/page-request';
import { generalcodeDto } from 'src/model/generalcode-request';
import { ResponseFilter } from 'src/framework/all-exceptions.filter';

@ApiTags('General Codes')
@Controller('generalCodes')
export class GeneralCodeController {
    constructor(private readonly service: GeneralCodeService) { }
   
    @ApiQuery({ name: 'pageNumber', type: 'number', required: true })
    @ApiQuery({ name: 'pageSize', type: 'number', required: true })
    @ApiQuery({ name: 'sortBy', type: 'string', required: true })
    @ApiQuery({ name: 'sortDirection', type: 'string', required: true })
    @Get("getDetailsWithPagination")
    async getDetailsWithPagination(
        @Query('pageNumber') pageNumber = 1,
        @Query('pageSize') pageSize,
        @Query('sortBy') sortBy,
        @Query('sortDirection') sortDirection): Promise<Pagination<Generalcode>> {
        let request = new PageRequest();
        request.pageNumber = pageNumber;
        request.pageSize = pageSize;
        request.sortBy = sortBy;
        request.sortDirection = sortDirection;
        let response =  await this.service.paginate(request);
        return ResponseFilter.FormatResponse(HttpStatus.OK, response);
    }
   
    @ApiParam({ name: 'id', type: 'number', required: true })
    @Get(':id')
    async getById(@Param('id') id): Promise<Generalcode> {
        let response = await this.service.findOne(id);
        return ResponseFilter.FormatResponse(HttpStatus.OK, response);
    }

    @Post()
    async createDetails(@Body() data: generalcodeDto): Promise<any> {
        await this.service.create(data);
        return ResponseFilter.FormatResponse(HttpStatus.OK, true);
    }

    @ApiParam({ name: 'id', type: 'number', required: true })
    @Put(':id')
    async update(@Param('id') id, @Body() data: generalcodeDto): Promise<any> {
        await this.service.update(id, data);
        return ResponseFilter.FormatResponse(HttpStatus.OK, true);
    }
    @ApiParam({ name: 'id', type: 'number', required: true})
    @Delete(':id')
    async delete(@Param('id') id): Promise<boolean> {
      let response =  await this.service.delete(id);
      return ResponseFilter.FormatResponse(HttpStatus.OK, response);
    }
   @ApiQuery({ name: 'pageNumber', type: 'number', required: true })
    @ApiQuery({ name: 'pageSize', type: 'number', required: true })
    @ApiQuery({ name: 'sortBy', type: 'string', required: true })
    @ApiQuery({ name: 'sortDirection', type: 'string', required: true })
    @Get("getDetails")
    async getById1(@Query('pageNumber') pageNumber,
    @Query('pageSize') pageSize,
    @Query('sortBy') sortBy,
    @Query('sortDirection') sortDirection): Promise<Pagination<Generalcode>> {
        let request = new PageRequest();
        request.pageNumber = pageNumber;
        request.pageSize = pageSize;
        request.sortBy = sortBy;
        request.sortDirection = sortDirection;
        let response =  await this.service.paginate(request);
        return ResponseFilter.FormatResponse(HttpStatus.OK, response);
    }
}
`
In above method have two get methods. they are,
- @Get("getDetailsWithPagination")  this method added in first postion of the contorller
- @Get("getDetails")  this method added in last postion of the contorller(same code used).
Issue is 
@Get("getDetailsWithPagination") this method is working but @Get("getDetails") method throwing error, this error occurred based on the position because of this method in the last position. Also this same method(@Get("getDetails") working as expected when I add this method before @Get("getDetailsWithPagination").
For your reference, I have attached the video link below.
[Swagger UI - Google Chrome 2020-03-12 16-54-32.zip](https://github.com/nestjs/nest/files/4328156/Swagger.UI.-.Google.Chrome.2020-03-12.16-54-32.zip)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
