### ISSUE TITLE
Swagger api response time monitor

### ISSUE THREAD

**Issue by zonorion** [nestjs/nest#4291]
Hi, i use swagger stats to monitor api request/ response but i have an question about response time.
I saw response time from interceptor differences time from swagger stats like below:
`[Nest] 29382   - 03/13/2020, 4:43:01 PM   [***Controller] [GET] /***/v1/airports?codes=XXX - [Excuted time: 11ms] +6754ms`
I dont know what's "+6754ms" time, let me know and how to choose right way to monitor response time with swagger stats, thanks.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
