### ISSUE TITLE
Can't use queue

### ISSUE THREAD

**Issue by wy-inceptionpad** [nestjs/nest#4292]
I am following [doc](https://docs.nestjs.com/techniques/queues) to start to use queue. I installed `@nestjs/bull`, `bull`, `@types/bull` dependencies. And here is my `app.module.ts`: 

```javascript
@Module({
    imports: [
        ConfigModule.forRoot({
            load: [configuration],
        }),
        BullModule.registerQueue({
            name: 'create_checkin',
            redis: {
                host: 'localhost',
                port: 6379,
            },
        }),
        EventModule,
    ],
})
export class AppModule {}
```

I imported BullModule in root module. And here is my `event.service.ts`:

```javascript
@Injectable()
export class EventService {

    constructor(
        @InjectQueue('create_checkin') private readonly createCheckinQueue: Queue,
    ) {
    }
}
```

And when I start server, I got the following error message:

```
Nest can't resolve dependencies of the EventService
Please make sure that the argument BullQueue_create_checkin at index [0] is available in the EventModule context.
```

I don't know which step I did wrong. Someone can help me?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
