### ISSUE TITLE
RabbitMQ heartbeat / unexpected close -> reconnect possibllity ?

### ISSUE THREAD

**Issue by ed-fruty** [nestjs/nest#4301]
## Current behavior
Now, using microservices and RabbitMQ as transport,  when we got an error about heartbeat error and unexpected close connection with RabbitMQ, I assume we can't control reconnection, isn't it ?

## Input Code

```bash
19|instance  | Error: Unexpected close
19|instance  |     at succeed (/node_modules/amqplib/lib/connection.js:272:13)
19|instance  |     at onOpenOk (/node_modules/amqplib/lib/connection.js:254:5)
19|instance  |     at /node_modules/amqplib/lib/connection.js:166:32
19|instance  |     at /node_modules/amqplib/lib/connection.js:160:12
19|instance  |     at Socket.recv (/node_modules/amqplib/lib/connection.js:499:12)
19|instance  |     at Object.onceWrapper (events.js:299:28)
19|instance  |     at Socket.emit (events.js:210:5)
19|instance  |     at emitReadable_ (_stream_readable.js:574:12)
19|instance  |     at processTicksAndRejections (internal/process/task_queues.js:79:21)

19|instance  | Error: Heartbeat timeout
19|instance  |     at Heart.<anonymous> (/node_modules/amqplib/lib/connection.js:427:19)
19|instance  |     at Heart.emit (events.js:210:5)
19|instance  |     at Heart.runHeartbeat (/node_modules/amqplib/lib/heartbeat.js:88:17)
19|instance  |     at listOnTimeout (internal/timers.js:531:17)
19|instance  |     at processTimers (internal/timers.js:475:7)
```

I suggest we can pass socket options, like `heartbeat`, but if connection was closed by server we can't reconnect automatically now. 

Have you any suggestion, how to control this ?

## Environment

<pre><code>
$ nest i

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/

[System Information]
OS Version     : Linux 3.10
NodeJS Version : v12.11.1
NPM Version    : 6.11.3

[Nest CLI]
Nest CLI Version : 7.0.0

[Nest Platform Information]
platform-socket.io version : 6.8.0
platform-express version   : 6.8.0
elasticsearch version      : 6.0.1
microservices version      : 6.8.0
websockets version         : 6.8.0
mongoose version           : 6.1.2
swagger version            : 3.1.0
typeorm version            : 6.2.0
common version             : 6.8.0
core version               : 6.8.0
cqrs version               : 6.0.1
jwt version                : 6.1.1
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
