### ISSUE TITLE
Graphql endpoint keep calling

### ISSUE THREAD

**Issue by ngohungphuc** [nestjs/nest#4310]
## Current behavior

When I go to the playground at http://localhost:3000/graphql I'm alway see the network keep making the post request to http://localhost:3000/graphql

![ConEmu64_8pdWDlsw7B](https://user-images.githubusercontent.com/13591213/76682330-e03ee080-662d-11ea-9622-80b6fdbbe997.png)

![chrome_wvemtBD2AL](https://user-images.githubusercontent.com/13591213/76682332-e2a13a80-662d-11ea-865c-c7c915aa288e.png)

## Input Code

Here is how I config my graphql server using code first approach
```ts
@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    GraphQLModule.forRoot({ autoSchemaFile: true }),
    MongooseModule.forRoot(process.env.DB_CONNECTION_STRING, {
      useNewUrlParser: true,
    }),
    HomeModule,
  ],
  controllers: [],
  providers: [],
})
export class AppModule {}
```

Any idea how it would cause this issue ? Thanks everyone.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by VictorGaiva** [comment]
Graphql Playground has a timer that retrieves the schema information from the back-end, which are these requests.
This is not an issue.

**Comment by ngohungphuc** [comment]
@VictorGaiva Thank you for your clarification
