### ISSUE TITLE
req.url is always '/' in class based middleware

### ISSUE THREAD

**Issue by arvinsingla** [nestjs/nest#4315]
## Current behavior
In Class based middleware `req.url` seems to always be `/` regardless of what path is being requested. This is not the case in functional middleware, where the correct path is set.

A previous Bug was filed in 2019 (https://github.com/nestjs/nest/issues/2261) with a similar finding but was closed as not related to nest. I am re-opening as it does seem related to nest. If I am incorrect it would be great to understand why this is happening.

## Input Code
https://github.com/arvinsingla/nestjs-middleware-test

Set up a test repo that has the two logging middlewares lifted from the docs examples. I created a health module that responds with a 200 at `/health` and console logging `req.url` for both middlewares. The results are the following.

```
req.url (Functional Middleware):  /health
req.url (Class Middleware):  /
```

## Expected behavior
In class based middleware the `req.url` should match the requested url.

## Possible Solution
`¯\_(ツ)_/¯`

## Environment

<pre><code>
Nest version: 7.0.1
 
For Tooling issues:
- Node version: v12.15.0
- Platform:  Mac
</code></pre>

**Comment by arvinsingla** [comment]
Upon further investigation I now understand this is not a Nest issue and related specifically to how `app.use()` functions with express. There is a description in the [express docs](https://expressjs.com/en/api.html#req.originalUrl) which specifies `the “mounting” feature of app.use() will rewrite req.url to strip the mount point.` Which is exactly what is occurring.

**Comment by apricote** [comment]
We had a similar issue where we registered the middleware using the `MiddlewareConsumer` and the path was missing from the `req` object in the middleware. We fixed it by changing the mounting point from `"*"`, to `"/"`, the middleware is still called for every request, but now the `req.url` property has the expected value.

```diff
 export class AppModule implements NestModule {
   public configure(consumer: MiddlewareConsumer) {
     consumer
       .apply(LoggingMiddleware)
-      .forRoutes("*");
+      .forRoutes("/");
   }
 }
```

Concrete changes required in our project: https://github.com/narando/nest-xray/pull/188/files#diff-5692e63ea675c2f3fbe340865adb78bc1d4a5b6b3b1cd148b6fde3d64b760987L13-L15

**Comment by qlereboursBS** [comment]
@apricote you saved my life, thank you! :+1: :+1:

**Comment by oriarazi** [comment]
> We had a similar issue where we registered the middleware using the `MiddlewareConsumer` and the path was missing from the `req` object in the middleware. We fixed it by changing the mounting point from `"*"`, to `"/"`, the middleware is still called for every request, but now the `req.url` property has the expected value.
> 
> ```diff
>  export class AppModule implements NestModule {
>    public configure(consumer: MiddlewareConsumer) {
>      consumer
>        .apply(LoggingMiddleware)
> -      .forRoutes("*");
> +      .forRoutes("/");
>    }
>  }
> ```
> 
> Concrete changes required in our project: https://github.com/narando/nest-xray/pull/188/files#diff-5692e63ea675c2f3fbe340865adb78bc1d4a5b6b3b1cd148b6fde3d64b760987L13-L15

any idea why it caused it? it indeed fixed my issue too, but why would '/*' cause this? thanks

**Comment by tmtron** [comment]
We also use express and stumbled upon this issue.   
Our solution is to import the [Request](https://expressjs.com/en/api.html#req) type from express and use [originalUrl](https://expressjs.com/en/api.html#req.originalUrl)

`logger.middleware.ts`:
```typescript
import { Request } from 'express';
...

@Injectable()
export class LoggerMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction) {
    console.log(req.originalUrl);
  }
}
```

`app.module.ts`:
```typescript
 export class AppModule implements NestModule {
   public configure(consumer: MiddlewareConsumer) {
     consumer
       .apply(LoggingMiddleware)
       .forRoutes("*");
   }
 }
```

**Comment by jrosa-pt** [comment]
> > We had a similar issue where we registered the middleware using the `MiddlewareConsumer` and the path was missing from the `req` object in the middleware. We fixed it by changing the mounting point from `"*"`, to `"/"`, the middleware is still called for every request, but now the `req.url` property has the expected value.
> > ```diff
> >  export class AppModule implements NestModule {
> >    public configure(consumer: MiddlewareConsumer) {
> >      consumer
> >        .apply(LoggingMiddleware)
> > -      .forRoutes("*");
> > +      .forRoutes("/");
> >    }
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Concrete changes required in our project: https://github.com/narando/nest-xray/pull/188/files#diff-5692e63ea675c2f3fbe340865adb78bc1d4a5b6b3b1cd148b6fde3d64b760987L13-L15
> 
> any idea why it caused it? it indeed fixed my issue too, but why would '/*' cause this? thanks

I think it would be important to the community to clarify this behaviour

**Comment by lsmith77** [comment]
thank you for this ticket.
