### ISSUE TITLE
`nest build` ignores tsconfig exclude option

### ISSUE THREAD

**Issue by umstek** [nestjs/nest#4316]
## Current behavior
`nest build` ignores `tsconfig.json`'s `exclude` option. e.g.: I want to exclude `scripts` folder from compiling and this works with `tsc`. But when I run `nest build`, `scripts` folder is also compiled and copied to `dist`. 

## Input Code
Inside `tsconfig.json`:

```json
  "exclude": ["node_modules", "dist", "uploads", "static", "scripts"]
```

## Expected behavior
`nest build` should obey `tsconfig` excludes. 

## Environment

<pre><code>
Nest version: 7.0.1
 
For Tooling issues:
- Node version: 13.7.0
- Platform:  Linux 4.4

Others:
Yarn: 1.22.4
</code></pre>

**Comment by jeffminsungkim** [comment]
Please, provide a minimal repository which reproduces your issue.

From what I've reproduced, it works as expected.
```json
// tsconfig.build.json
{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "scripts", "test", "dist", "**/*spec.ts"]
}
```

**Comment by VFC-elindgren** [comment]
I'm having a similar problem, except nest build respects the tsconfig.build.json exclude, however nest start does not seem to respect the normal tsconfig.json exclude.

**tsconfig.json:**
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "jsx": "react"
  },
  "exclude": ["node_modules", "generated", "dist", "**/*spec.ts"]
}
```

**example.e2e-spec.ts:**
```
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { ExampleModule } from './example.module';
import {
  ApolloServerTestClient,
  createTestClient,
} from 'apollo-server-testing';
import {
  GetExampleDocument,
  GetExampleQuery,
} from '../../../generated/graphql';

describe('Example E2E against mock server', () => {
  let app: INestApplication;
  let client: ApolloServerTestClient;
  
  fasdf // intentional error
  
  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [GraphQLModule.forRoot({ autoSchemaFile: true }), ExampleModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();

    const gqlModule = app.get<GraphQLModule>(GraphQLModule);
    client = createTestClient(gqlModule.apolloServer as any); // there's a slight mismatch in peer dependency versions for nest vs apollo-server-testing, so the any is necessary for now
  });

  it('Example resolver should return object with hello greeting and dynamic id', async () => {
    const { query } = client;
    const id = 'one';

    const res = await query<GetExampleQuery>({
      query: GetExampleDocument,
      variables: {
        id,
      },
    });

    expect(res.data.example.exampleField).toMatch(`hi my id is: ${id}`);
  });
});
```

**output of nest start --watch:**
```
src/modules/example/example.e2e-spec.ts:17:2 - error TS2304: Cannot find name 'fasdf'.

17  fasdf
    ~~~~~

[2:39:16 PM] Found 1 error. Watching for file changes.
```

**Comment by VFC-elindgren** [comment]
as @umstek mentioned, tsc does as expected and ignores the spec file

**Comment by umstek** [comment]
`extends` only extends properties in the top level, which means, the `exclude` array defined in `tsconfig.json` will be overridden by what is specified in `tsconfig.build.json`. You need to specify everything defined in `tsconfig.json` `exclude` plus the new ones also, in `tsconfig.build.json`. Hope this helps. @VFC-elindgren

**Comment by VFC-elindgren** [comment]
@umstek Awesome thanks, that was very helpful. It seems unexpected that both the `nest build` and `nest start` command rely on the `tsconfig.build.json` file, but that hint was enough for us to realize we could override the nest start's tsconfig choice with a flag. Thanks again!

**Comment by jmcdo29** [comment]
`nest start` looks to see if a `dist` directory exists in the project, and if it doesn't it will call `nest build` so that the `js` files can be ran directly by `node` without needing a separate package like `ts-node`. So in the end, it is expected, but only if you realize that the build is called if there isn't an existing `dist` directory.

**Comment by cardozotm** [comment]
This worked for me:
` "include": ["src", "test", "ormconfig.ts", "jest.config.ts"],`

**Comment by devadee** [comment]
This is my tsconfig.build.json file:
{
  "extends": "./tsconfig.json",
  "include": ["./src", "src", "src/**/*"],
  "exclude": ["node_modules", "test", "dist", "**/*spec.ts", "../common/**/*", "common/**/*", "dist/common"],
}

I want to exclude the common folder which is outside of the Nest project. But it get compiled and comes in dist folder.
So that i am getting error like dist/main is missing. Its correct because, in dist folder i can see the project named folder and the common folder.
Please help me to solve this issue.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
