### ISSUE TITLE
Cannot find module '@nestjs/common/interfaces/microservices/microservice-configuration.interface'

### ISSUE THREAD

**Issue by smhmayboudi** [nestjs/nest#4318]
## Current behavior

```ts
node_modules/@nestjs/terminus/dist/health-indicators/microservice/grpc.health.d.ts:1:29 - error TS2307: Cannot find module '@nestjs/common/interfaces/microservices/microservice-configuration.interface'.

1 import { GrpcOptions } from '@nestjs/common/interfaces/microservices/microservice-configuration.interface';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@nestjs/terminus/dist/health-indicators/microservice/microservice.health.d.ts:1:93 - error TS2307: Cannot find module '@nestjs/common/interfaces/microservices/microservice-configuration.interface'.

1 import { RedisOptions, NatsOptions, MqttOptions, GrpcOptions, RmqOptions, TcpOptions } from '@nestjs/common/interfaces/microservices/microservice-configuration.interface';
                                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 error(s).
```
## Input Code

create a simple project and add the terminus packages. update to latest packages.

src/app.health.indicator.ts
```ts
import { HealthCheckError } from "@godaddy/terminus";
import { Injectable } from "@nestjs/common";
import { HealthIndicator, HealthIndicatorResult } from "@nestjs/terminus";

@Injectable()
export class AppHealthIndicator extends HealthIndicator {
  async isHealthy(): Promise<HealthIndicatorResult> {
    const isHealthy = true;
    const result = super.getStatus("app", isHealthy);
    if (isHealthy) {
      return Promise.resolve(result);
    }
    throw new HealthCheckError("Action failed.", result);
  }
}
```

## Expected behavior

To run correctly.

## Environment

<pre><code>
Nest version: 7.0.1

"dependencies": {
  "@godaddy/terminus": "^4.3.1",
  "@nestjs/common": "^7.0.1",
  "@nestjs/config": "^0.4.0",
  "@nestjs/core": "^7.0.1",
  "@nestjs/graphql": "^7.0.1",
  "@nestjs/jwt": "^7.0.0",
  "@nestjs/passport": "^7.0.0",
  "@nestjs/platform-express": "^7.0.1",
  "@nestjs/swagger": "^4.4.0",
  "@nestjs/terminus": "^6.5.6",
  "@nestjs/typeorm": "^7.0.0",
  "@sentry/node": "^5.14.2",
  "aws-sdk": "^2.639.0",
  "cache-manager": "^3.2.0",
  "cache-manager-ioredis": "^2.0.0",
  "class-transformer": "^0.2.3",
  "class-validator": "^0.11.0",
  "cookie-parser": "^1.4.4",
  "cors": "^2.8.5",
  "crypto-random-string": "^3.2.0",
  "csurf": "^1.11.0",
  "elastic-apm-node": "^3.5.0",
  "express-rate-limit": "^5.1.1",
  "hashids": "^2.2.1",
  "helmet": "^3.21.3",
  "imgproxy": "^0.1.2",
  "kaop-ts": "^4.3.0",
  "lodash": "^4.17.15",
  "mime": "^2.4.4",
  "mime-types": "^2.1.26",
  "mmmagic": "^0.5.3",
  "moment": "^2.24.0",
  "mongoose": "^5.9.4",
  "ms": "^2.1.2",
  "multer": "^1.4.2",
  "mysql": "^2.18.1",
  "passport": "^0.4.1",
  "passport-anonym-uuid": "^1.0.3",
  "passport-jwt": "^4.0.0",
  "passport-local": "^1.0.0",
  "passport-telegram-official": "^1.1.0",
  "passport-unique-token": "^1.0.0",
  "prom-client": "^12.0.0",
  "prometheus-gc-stats": "^0.6.2",
  "reflect-metadata": "^0.1.13",
  "rimraf": "^3.0.2",
  "rxjs": "^6.5.3",
  "source-map": "^0.7.3",
  "source-map-support": "^0.5.16",
  "swagger-ui-express": "^4.1.3",
  "typeorm": "^0.2.24",
  "uuid": "^7.0.2"
},
"devDependencies": {
  "@commitlint/cli": "^8.3.5",
  "@commitlint/config-angular": "^8.3.4",
  "@commitlint/prompt": "^8.3.5",
  "@commitlint/prompt-cli": "^8.3.5",
  "@nestjs/cli": "^7.0.0",
  "@nestjs/schematics": "^7.0.0",
  "@nestjs/testing": "^7.0.1",
  "@types/aws-lambda": "^8.10.46",
  "@types/bluebird": "^3.5.30",
  "@types/cache-manager": "^2.10.2",
  "@types/connect": "^3.4.33",
  "@types/cookie-parser": "^1.4.2",
  "@types/cors": "^2.8.6",
  "@types/csurf": "^1.9.36",
  "@types/express": "^4.17.3",
  "@types/express-rate-limit": "^5.0.0",
  "@types/hashids": "^1.0.30",
  "@types/helmet": "0.0.45",
  "@types/jest": "^25.1.4",
  "@types/lodash": "^4.14.149",
  "@types/mime-types": "^2.1.0",
  "@types/mmmagic": "^0.4.29",
  "@types/mongoose": "^5.7.6",
  "@types/ms": "^0.7.31",
  "@types/multer": "^1.4.2",
  "@types/node": "^13.9.1",
  "@types/passport-jwt": "^3.0.3",
  "@types/passport-local": "^1.0.33",
  "@types/passport-unique-token": "^1.0.2",
  "@types/prometheus-gc-stats": "^0.6.1",
  "@types/source-map-support": "^0.5.1",
  "@types/supertest": "^2.0.8",
  "@types/uuid": "^7.0.0",
  "@typescript-eslint/eslint-plugin": "^2.23.0",
  "@typescript-eslint/parser": "^2.23.0",
  "conventional-changelog": "^3.1.18",
  "conventional-changelog-cli": "^2.0.31",
  "eslint": "^6.8.0",
  "eslint-config-prettier": "^6.10.0",
  "eslint-plugin-jest": "^23.8.2",
  "eslint-plugin-prettier": "^3.1.2",
  "husky": "^4.2.3",
  "hygen": "^5.0.3",
  "jest": "^25.1.0",
  "lint-staged": "^10.0.8",
  "prettier": "^1.18.2",
  "supertest": "^4.0.2",
  "ts-jest": "^25.2.1",
  "ts-loader": "^6.1.1",
  "ts-node": "^8.6.2",
  "tsconfig-paths": "^3.9.0",
  "typescript": "^3.8.3"
},

For Tooling issues:
- Node version: v13.11.0  
- Platform: Mac v10.15.3 

Others:
- IDE: vscode v1.43.0
- package manager: npm v6.14.2
</code></pre>

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/terminus/pull/593

**Comment by twigs67** [comment]
@kamilmysliwiec I'm not even using terminus though. I tried installing it, but I'm still getting this error: ```node_modules/@nestjs/testing/testing-module.d.ts:2:37 - error TS2307: Cannot find module '@nestjs/common/interfaces/microservices/microservice-configuration.interface'.
``` after running ```tsc```. 

Do you still think this is related to nestjs/terminus#593?

**Comment by geekyayush** [comment]
Same, I'm also facing the issue :-/

**Comment by twigs67** [comment]
@geekyayush what fixed it for me was not using ```npm run build``` and instead use ```tsc -p tsconfig.build.json``` and I updated my `tsconfig.build.js` file to: 

```
{
  "extends": "./tsconfig.json",
  "include": ["src/**/*"],
  "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
}
```
This just excludes testing. Not a great fix, but it got me going. Hopefully it works for you.

**Comment by kamilmysliwiec** [comment]
Please, just make sure that you're using the latest version (or the same major versions) of the `@nestjs/core`, `@nestjs/common`, `@nestjs/microservices`, and `@nestjs/testing` packages.

This will fix your issue.

**Comment by BrunnerLivio** [comment]
Also check your `@nestjs/terminus` version (currently on your project `6.5.6`). Use a least 7.0.0!
