### ISSUE TITLE
Uncaught error when using next function with error in middlleware

### ISSUE THREAD

**Issue by shyimo** [nestjs/nest#432]
## I'm submitting a...
[ ] Regression 

## Current behavior
When calling next with error in express middleware the error handler does not catch it.

Example:
- some-file.js:
class CustomError extends Error {
     constructor(errors, place, message) {
        super(message);
        this.errors = errors;
    }
}
function someMiddlleware(req, res, next) {
    return next(new CustomError(new Error('Some_error')));
}

- error-handler.js
@Catch(CustomError)
exports class CustomErrorFilter implements ExceptionFilter {
      catch(exception, response) {
            /// do some logic...
      }
}

## Expected behavior
CustomErrorFilter should catch the error.

- It seems that the problem only occurs in the version  4.6.xx

**Comment by bojidaryovchev** [comment]
https://github.com/nestjs/nest/issues/431 is that the same problem?

**Comment by kamilmysliwiec** [comment]
duplicate of #431
