### ISSUE TITLE
Can't use ConfigService in multer options

### ISSUE THREAD

**Issue by RezaT1994** [nestjs/nest#4320]
## Bug Report

I can't use `ConfigService` in destination method of multer options.

Here is the code I'm using.
```ts
destination: (req, file, cb) => {
    cb(null, this.configService.get<string>('UPLOAD_PATH'));
},
```

I think `this` refers to the destination method and not the class.

I get this error
```Untyped function calls may not accept type arguments.```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
