### ISSUE TITLE
Set FileInterceptor's multerOptions.preservePath=true not work

### ISSUE THREAD

**Issue by tian0o0** [nestjs/nest#4325]
## Current behavior
I have set FileInterceptor's multerOptions.preservePath=true, but i can't find file filed in the uoloadedFile object

## Input Code
```ts
@UseInterceptors(FileInterceptor('file', { preservePath: true }))
async upload(@UploadedFile() file): Promise<UploadResult> {
    console.log(file);
    // { 
    //   fieldname: 'file',
    //   originalname: 'xxx.png',
    //   encoding: '7bit',
    //   mimetype: 'image/png',
    //   buffer: xxx
    //   size: 34943 
    //   // path field not found here
    // }
    return await this.uploadService.upload(file);
}
```

## Expected behavior
there should be a `path` field in the uploadedFile object

## Environment

<pre><code>
Nest version: 6.11.7
Nest version: 7.0.2

**Comment by jabedzaman** [comment]
did u got the path same as it was sent from client???
