### ISSUE TITLE
Add possibility to make (validation) pipes optional

### ISSUE THREAD

**Issue by SeWaS** [nestjs/nest#4328]
## Is your feature request related to a problem? Please describe.

I usually use pipes to transform and validate `@Query(...)` values on controller level. Often these query-parameters are used for filtering and sorting information and hence are optional (Nice, if sent, but if not, also good).
Now, if I do something like `@Query('sorted', ParseBoolPipe) shouldSort: boolean`, the pipe would ofc not consider `undefined` as a valid boolean value and return a `400` response. So the query parameter is no longer optional 🤔

## Describe the solution you'd like

My workaround (or maybe even solution) to avoid this is extending the built-in Pipes and check for existence of the value in advance before triggering transformation/validation by the original pipe.
But maybe there is a smarter way available to archive this goal than extending all the pipes I just wasn't aware of 😁

## Teachability, Documentation, Adoption, Migration Strategy

Wouldn't it make sense to have an option available like `{ isOptional }`, similar to the `skipMissingProperties` option in the `ValidatorOptions` used by `ValidationPipe`?

Could be used like
```typescript
// controller.ts
@Get('/entities')
public async getAllEntities(
  @Query(
    'sorted', 
    new ParseBoolPipe({ isOptional: true })
  ) shouldBeSorted: boolean
): Promise<Entity[]> {
  ...
}

// GET /entities => will bypass the pipe
// GET /entities?sorted=true => will go through the pipe
// GET /entities?sorted=invalid => will tigger the pipe to throw a BadRequestException
```

## What is the motivation / use case for changing the behavior?

My motivation behind this is to have the possibility to say "If a query-parameter was sent, then validate/transform it, if not, then fine, as well, just bypass the pipe". Values sent as query parameters are optional per se, but if sent, I want to validate them.

**Comment by kamilmysliwiec** [comment]
`ParseBoolPipe` and `ParseIntPipe` has been added to allow explicitly validating & transforming non-optional parameters.

In your case, you can either use the [implicit type conversion](https://docs.nestjs.com/migration-guide#implicit-type-conversion-validationpipe) or define a DTO:

```typescript
@Get('/entities')
public async getAllEntities(
  @Query() { sorted }: IsSortedDto,
): Promise<Entity[]> {
  ...
}
```

and

```typescript
export class IsSortedDto {
    @IsOptional()
    @Transform((val: string) => val === 'true')
    sorted: boolean;
}
```

and lastly (enable `transform`)

```typescript
app.useGlobalPipes(new ValidationPipe({ transform: true }));
```

**Comment by SergeyP2H** [comment]
I don't know is it still require, but I tried to solve the same issue. I want to validate my request query params "limit". It should be optional, but if it exists should be an integer.
```javascript
import { isLimitTodo } from './todos.dto'
import { ValidationPipe } from './validation.pipe.js' 
...
  async getTodos(@Query(new ValidationPipe()) limit: isLimitDto) {
    return this.todosDatabaseService.getTodos();
  }
...
 ```
`validation.pipe.js` file according to documentation https://docs.nestjs.com/pipes
 
 ```javascript
 
'validation.pipe.js'
 
 
import { PipeTransform, Injectable, ArgumentMetadata, BadRequestException } from '@nestjs/common';
import { validate } from 'class-validator';
import { plainToClass } from 'class-transformer';

@Injectable()
export class ValidationPipe implements PipeTransform<any> {
  async transform(value: any, { metatype }: ArgumentMetadata) {
    if (!metatype || !this.toValidate(metatype)) {
      return value;
    }
    const object = plainToClass(metatype, value);
    const errors = await validate(object);
    if (errors.length > 0) {
      throw new BadRequestException('Validation failed');
    }
    return value;
  }

  private toValidate(metatype: Function): boolean {
    const types: Function[] = [String, Boolean, Number, Array, Object];
    return !types.includes(metatype);
  }
}
 ```
 
 ```javascript
 'todos.dto.ts'
 
import { IsOptional, IsInt } from 'class-validator';
import { Type } from 'class-transformer';

export class isLimitDto {
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  limit: number;
}
 ```

**Comment by sedukhsergey** [comment]
I don't know is it still require, but I tried to solve the same issue. I want to validate my request query params "limit". It should be optional, but if it exists should be an integer. Hope this can help someone.
```javascript
import { isLimitTodo } from './todos.dto'
import { ValidationPipe } from './validation.pipe.js' 
...
  async getTodos(@Query(new ValidationPipe()) limit: isLimitDto) {
    return this.todosDatabaseService.getTodos();
  }
...
 ```
`validation.pipe.js` file according to documentation https://docs.nestjs.com/pipes
 
 ```javascript
 
'validation.pipe.js'
 
 
import { PipeTransform, Injectable, ArgumentMetadata, BadRequestException } from '@nestjs/common';
import { validate } from 'class-validator';
import { plainToClass } from 'class-transformer';

@Injectable()
export class ValidationPipe implements PipeTransform<any> {
  async transform(value: any, { metatype }: ArgumentMetadata) {
    if (!metatype || !this.toValidate(metatype)) {
      return value;
    }
    const object = plainToClass(metatype, value);
    const errors = await validate(object);
    if (errors.length > 0) {
      throw new BadRequestException('Validation failed');
    }
    return value;
  }

  private toValidate(metatype: Function): boolean {
    const types: Function[] = [String, Boolean, Number, Array, Object];
    return !types.includes(metatype);
  }
}
 ```
 
 `isLimitDto`
 
 ```javascript
 'todos.dto.ts'
 
import { IsOptional, IsInt } from 'class-validator';
import { Type } from 'class-transformer';

export class isLimitDto {
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  limit: number;
}
 ```

**Comment by jmcdo29** [comment]
@sedukhsergey please use our [Discord](https://discord.gg/nestjs) channel for Support
