### ISSUE TITLE
Implicit type conversion does not work.

### ISSUE THREAD

**Issue by CatsMiaow** [nestjs/nest#4331]
Version 7.0.2
https://docs.nestjs.com/migration-guide#implicit-type-conversion-validationpipe
https://github.com/nestjs/nest/releases/tag/v7.0.0
> common: automatically transform primitives (number, bool) with ValidationPipe #4110 

In the above PR, the `transformPrimitive` function was added,
Was reverted from #4116 

https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts
The `transformPrimitive` source was not found in the actual master source.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in 7.0.3
