### ISSUE TITLE
UseGuards not triggered for Resolvers and Queries

### ISSUE THREAD

**Issue by axos88** [nestjs/nest#4337]
## Bug Report

UseGuards are not triggered for Resolvers, or Queries

Related to: https://github.com/nestjs/nest/issues/2484

```
import {ExecutionContext, Injectable} from "@nestjs/common";
import {AuthGuard} from "@nestjs/passport";
import {GqlExecutionContext} from "@nestjs/graphql";
import {ExecutionContextHost} from "@nestjs/core/helpers/execution-context-host";
import { AuthenticationError } from 'apollo-server-express';

@Injectable()
export class GqlAuthGuard extends AuthGuard('jwt') {
  canActivate(context: ExecutionContext) {
    console.log("CANACTIVATE");

    const ctx = GqlExecutionContext.create(context);
    const { req } = ctx.getContext();

    return super.canActivate(
      new ExecutionContextHost([req]),
    );
  }
```

```
import {Query, Resolver} from "@nestjs/graphql";
import {CurrentUser, GqlAuthGuard} from "../authz/grpahql-jwt.guard";
import {UseGuards} from "@nestjs/common";
import {UserProfile as UserProfileType} from "./user-profile.graphql";
import {UserProfile} from "../entities/user-profile.entity";

@Resolver(of => UserProfileType)
// @UseGuards(GqlAuthGuard)
export class UserProfileResolver {


  @Query(returns => UserProfileType)
  @UseGuards(GqlAuthGuard)
  async me(@CurrentUser() context: any) {
    console.log("CTX");
    console.log(context);


    return await UserProfile.findOne({ where: { id: 1}});
  }

}
```

## Current behavior

Does not trigger GqlAuthGuard.canActivate, and does not set up the req.user data, thus @CurrentUser() always returns null, and allows unauthenticated requests!

```
```

## Expected behavior
It should be triggered.

## Environment
<pre><code>
Nest version: 6.11.11
 
For Tooling issues:
- Node version: 10.19.0
- Platform:  Linux
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by axos88** [comment]
The issue turned out to be that GqlAuthGuard was not in the providers section of the module. Would it be possible to make this throw an error?

**Comment by kamilmysliwiec** [comment]
`GqlAuthGuard` should never be in the providers section

**Comment by axos88** [comment]
But putting GqlAuthGuard in the providers sections fixed the issue for me. Without having it in the providers section, it is not triggered.
