### ISSUE TITLE
documentation is so terrible

### ISSUE THREAD

**Issue by quanzhiyuan** [nestjs/nest#4340]
nest.js is so cool. it use Typescript and use DI and AOP，but the learn documentation is so  
hard to understand。 i don't know how to start a sample project， i don't know why i need Pipes, Middleware, guards, interceptors and what the execute order. the documentation's table of Contents is  always confusion me. is the table of Contents 
has been carefully designed ?

**Comment by quanzhiyuan** [comment]
should it be friendly to front-end developers ?

**Comment by johnbiundo** [comment]
You should go through the documentation in the order it's presented.  Start with the Overview section - First Steps, then Controllers, etc.  It should answer your questions about Pipes, Middleware, Guards, etc.  Also, look at the samples in the repository here: https://github.com/nestjs/nest/tree/master/sample.  01 and 15 are good starter examples.  Once you've read those sections, ask your questions of the community here: https://discordapp.com/invite/G7Qnnhy.  There are good resources the community can guide you to, or answer for you.
