### ISSUE TITLE
graphql missing in ContextType, @nestjs/common v7.0.3

### ISSUE THREAD

**Issue by gempain** [nestjs/nest#4344]
## Current behavior
I'm not sure if this is intentional, but @nestjs/common v7.0.3 seems to be missing `graphql` in the [`ContextType`](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/features/arguments-host.interface.ts) enum.

```
export declare type ContextType = 'http' | 'ws' | 'rpc';
```

Workaround when checking equality:
```
ctx.getType().toString() === 'graphql';
```

## Possible Solution
```
export declare type ContextType = 'http' | 'ws' | 'rpc' | 'graphql';
```

## Environment

```
@nestjs/common: 7.0.3
```

**Comment by kamilmysliwiec** [comment]
For GraphQL, you should use `GqlExecutionContext` factory https://docs.nestjs.com/graphql/tooling#custom-decorators

**Comment by gempain** [comment]
Alright, I think a bit of background is necessary here. I initially found [an SO thread](https://stackoverflow.com/questions/55269777/nestjs-get-current-user-in-graphql-resolver-authenticated-with-jwt) explaining how to inject the current user in a GraphQL `@Query()` annotated method. That answer pointed to [a Github issue](https://github.com/nestjs/graphql/issues/48#issuecomment-420693225) on which [you commented](https://github.com/nestjs/graphql/issues/48#issuecomment-420770784) and ended up updating [the docs](https://docs.nestjs.com/techniques/authentication#graphql).

There, you specifically say to use `ctx.getContext().req.user`:

```
export const CurrentUser = createParamDecorator(
  (data: unknown, context: ExecutionContext) => {
    const ctx = GqlExecutionContext.create(context);
    return ctx.getContext().req.user; // <- right here
  },
);
```

which does work. I think the documentation you pointed to is either incorrect, misleading, or I'm not understanding where your `user` property is binded.

Moreover, when I do use my `@CurrentUser()` in a `@Query()` annotated method, and `console.log(ctx)`, this is what I get:

```
ExecutionContextHost {
  args: [
    undefined,
    { id: '5e6bab744fa4174cf1b4547c' },
    {
      req: [IncomingMessage],
      _extensionStack: [GraphQLExtensionStack]
    },
    {
      fieldName: 'user',
      fieldNodes: [Array],
      returnType: User!,
      parentType: Query,
      path: [Object],
      schema: [GraphQLSchema],
      fragments: [Object: null prototype] {},
      rootValue: undefined,
      operation: [Object],
      variableValues: {},
      cacheControl: [Object]
    }
  ],
  constructorRef: [Function: UserResolver],
  handler: [AsyncFunction: user],
  contextType: 'graphql'
}
```

and `ctx.getType()` returns:

```
graphql
```

which is awesome, because I was able to create a `@CurrentUser()` decorator that can be used both for `http` and `graphql` contexts:

```
export const CurrentUser = createParamDecorator((data, ctx: ExecutionContext) => {
  if (ctx.getType().toString() === 'graphql') {
    const gqlContext = GqlExecutionContext.create(ctx);
    return gqlContext.getContext().req.user;
  }
  return ctx.switchToHttp().getRequest().user;
});
```

Can you clarify why the docs points in different directions ?

**Comment by ttsirkia** [comment]
I also noticed this in my simple logging `NestInterceptor`.

This code

```ts
intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
  if (context.getType() === 'graphql') {
```

gives an error. I'd like to have a bit different handling for `graphql` and `http`.

**Comment by kamilmysliwiec** [comment]
@ttsirkia 
```typescript
context.getType<GqlContextType>()
```

where `GqlContextType` is imported from the `@nestjs/graphql`.

**Comment by ttsirkia** [comment]
@kamilmysliwiec thanks for the pointer!
