### ISSUE TITLE
How to Get data in mutiple @ManyToMany in Nest.js

### ISSUE THREAD

**Issue by JihenHm** [nestjs/nest#4347]
I have a ManyToMany relation between two entities and I don't know how can I Get data from the join table "device_users_user"

@Entity()
export class Device{

  @PrimaryColumn()
  Name:string;

  @Column({ nullable: true})
  Port:number;

  @Column({ nullable: true})
  IPadress:string;

  @Column({ nullable: true})
  Location:string;

  @ManyToMany(type => User)
    @JoinTable()
    users: User[];

  }
@Entity()
export class User{

  @PrimaryColumn()
  Id:number;
  @Column({ nullable: true})
  Departement:string;
  @Column({ nullable: true})
  FirstName:string;
  @Column({ nullable: true})
  LastName:string;
  @Column({ nullable: true})
  CardNumber:string;
  @Column({ nullable: true})
  MobilePhone:string;

}

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
