### ISSUE TITLE
NATS `userJWT` option not being passed through to NATS client

### ISSUE THREAD

**Issue by rhlsthrm** [nestjs/nest#4356]
## Current behavior
I have a NATS server that requires authentication by bearer token. I am trying to instantiate the Nest microservices application with the `userJWT` option, which is [documented](https://docs.nestjs.com/microservices/nats#options) to be supported. However the authentication fails and I can see that the bearer token is not part of the connection.

## Input Code
- Requires locked down NATS server.

```ts
import { NestFactory } from '@nestjs/core';
import { Transport, MicroserviceOptions, NatsOptions } from '@nestjs/microservices';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.createMicroservice<MicroserviceOptions>(
    AppModule,
    {
      transport: Transport.NATS,
      servers: ["nats://localhost:4222"],
      userJWT: "foo", // this option is not passed
    } as NatsOptions,
  );
  app.listen(() => console.log('Microservice is listening'));
}
bootstrap();
```

## Expected behavior
Authentication should work.

## Environment

Nest version: 7.0.2
 
For Tooling issues:
- Node version: v10.18.1
- Platform: Mac

**Comment by kamilmysliwiec** [comment]
```
{
      transport: Transport.NATS,
      servers: ["nats://localhost:4222"],
      userJWT: "foo", // this option is not passed
    } as NatsOptions,
```

to:

```
{
      transport: Transport.NATS,
      options: {
           servers: ["nats://localhost:4222"],
           userJWT: "foo", // this option is not passed
       },
}
```

**Comment by rhlsthrm** [comment]
Hi @kamilmysliwiec, sorry for the confusion. I was actually doing it the way you mentioned, I mistyped in my initial comment. The `servers` option is working fine, so I know at least some of the options are passed correctly. This has been working for me until I tried to use the `userJWT` option.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-nats.ts#L69-L76

The entire options object is passed down to the `nats.connect()` method.

**Comment by rhlsthrm** [comment]
OK, I will try to reproduce this with the raw NATS lib.
