### ISSUE TITLE
CLI: start all / build all for monorepo's

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#4362]
## Is your feature request related to a problem? Please describe.
Having a monorepo with multiple apps inside, it would be useful to have commands like `nest start all`, `nest start:dev all` and `nest build all`.

## What is the motivation / use case for changing the behavior?
Currently each app needs to be started separately for development. If I have 10 apps/microservices in my repo I need to have 10 terminal tabs open.

Further it is impossible to build more than one application per repo because `/dist` will always be cleared. E.g.: 

- `npm run build admin`
- `npm run build client`
- -> app admin has been removed

**Comment by kamilmysliwiec** [comment]
You can achieve this with https://www.npmjs.com/package/concurrently (one line)

**Comment by MickL** [comment]
But how can you build multiple apps when it always clears the dist folder?

**Comment by kamilmysliwiec** [comment]
It never clears the dist folder unless you have `deleteOutDir` set to true in the `nest-cli.json` file

**Comment by MickL** [comment]
Doesnt it make sense to have a build all command that clears dist once and then builds all apps? Or maybe to even define groups of apps in the nest-cli.json and the build groupname?

**Comment by kamilmysliwiec** [comment]
Use `rimraf` as a `prebuild` hook instead

**Comment by MickL** [comment]
I think you meant `prestart`:

```
"scripts": {
    "prestart": "rimraf dist",
    "start": "nest start --watch",
}
```

There is not prebuild according to the docs: `https://docs.npmjs.com/misc/scripts`
