### ISSUE TITLE
[Documentation] Cache Interceptor: First parameter is invisible

### ISSUE THREAD

**Issue by cloakedch** [nestjs/nest#4364]
## Is your feature request related to a problem? Please describe.

When using a cache interceptor in a websocket gateway, the `getArgByIndex()` is including the socket on its first index, even though _only_ a `@MessageBody()` was supplied.

## Describe the solution you'd like

When one uses a websocket and a cache interceptor like so:

```js
@UseInterceptors(MyCacheInterceptor)
@SubscribeMessage('my-endpoint')
myEndpoint(@MessageBody() myParam: string): Observable<WsResponse<MyResponse>> {
    /// whatever
}
```

Inteceptor:

```js
@Injectable()
export class MyInterceptor extends CacheInterceptor {
  trackBy(context: ExecutionContext): string | undefined {
    return context.getArgByIndex(1); // 0 is the (invisible) socket
  }
}
```

As you can see in the comment of the interceptor, the index zero is the invisible socket.
=> This behaviour should be mentioned in the documentation.

## Teachability, Documentation, Adoption, Migration Strategy

Suggestion:
Under https://docs.nestjs.com/techniques/caching#adjust-tracking
describe in more detail how `context` behaves, in particular `getARgByIndex`.

## What is the motivation / use case for changing the behavior?

Avoid misleading index.

**Comment by kamilmysliwiec** [comment]
Please, read this chapter https://docs.nestjs.com/fundamentals/execution-context
