### ISSUE TITLE
ModuleRef.get(token, {strict: false}) does not inject dependencies

### ISSUE THREAD

**Issue by greenreign** [nestjs/nest#4368]
## Current behavior
When using ModuleRef to get providers there are situations when the instance returned does not have its own dependencies injected

## Input Code
https://github.com/greenreign/nest-moduleref-repro

## Expected behavior
Instances returned should have all their dependencies or Nest should error if it cannot inject them

## Environment

<pre><code>
Nest version: 6.11.11, 6.10.3, 7.0.3

**Comment by kamilmysliwiec** [comment]
You should never use `ModuleRef` in the constructor. Use lifecycle hooks instead, as shown here: https://docs.nestjs.com/fundamentals/module-ref#retrieving-instances

Move your code to `onModuleInit` and let me know if you are still encountering this issue.

**Comment by greenreign** [comment]
Yes, that absolutely fixes it for me.  
Wow, I can't believe I never noticed that assignment was in an `onModuleInit` in the example.  I didn't think it mattered.  It's actually worked perfectly for most of my test scenarios.  Just a few which have cost me a lot of time.  Is it worth a note or warning in the docs?

Thanks for the clarification!

**Comment by kamilmysliwiec** [comment]
Glad it worked! I'll check the docs and see if we can improve this
