### ISSUE TITLE
Jest error with reflect-metadata

### ISSUE THREAD

**Issue by edstevo** [nestjs/nest#4369]
## Current behavior
Similar to this issue: https://github.com/nestjs/nest/issues/1305 (although slightly different error stack) , when running a test using Jest in a fresh installation of NestJs, I get the following error:

`
FAIL  src/app.controller.spec.ts
  ● Test suite failed to run

    TypeError: Reflect.getMetadata is not a function

      at Optional (../node_modules/@nestjs/common/decorators/core/optional.decorator.js:21:34)
      at ../node_modules/tslib/tslib.js:100:41
      at Object.__decorate (../node_modules/tslib/tslib.js:95:99)
      at Object.<anonymous> (../node_modules/@nestjs/common/services/logger.service.js:118:29)
      at Object.<anonymous> (../node_modules/@nestjs/common/utils/load-package.util.js:3:26)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.15s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
`
<img width="808" alt="Screenshot 2020-03-21 at 08 20 08" src="https://user-images.githubusercontent.com/9676607/77222616-c9781c80-6b4c-11ea-954a-7836c144e97e.png">

So, I have installed a fresh project of NestJs and attempted to run a test straight away and received this error.

## Expected behavior
No error. I don't see this error on NestJS 7.0.3 or when running in the browser.

## Possible Solution
I have tried the solutions suggested in this post, with no success: https://github.com/nestjs/nest/issues/1305

I have imported `'reflect-metadata'` in the spec file and also in a jest setup file.

**Comment by kamilmysliwiec** [comment]
What's your OS & Node version? 

> No error. I don't see this error on NestJS 7.0.3 or when running in the browser.

What do you mean by running in the browser?

**Comment by edstevo** [comment]
Hi Kamil,

After your prompt here, I updated Node and it now works.

Sorry for the inconvenience!
