### ISSUE TITLE
Add optional array type argument for MiddlewareConsumer

### ISSUE THREAD

**Issue by GrayStrider** [nestjs/nest#4370]
That would allow the usage of array as an alternative to the list of arguments, like so:
![image](https://user-images.githubusercontent.com/43771776/77223736-59e94800-6bb3-11ea-863c-9cf87ff5f0c1.png)
Would be equivalent to
![image](https://user-images.githubusercontent.com/43771776/77223749-6cfc1800-6bb3-11ea-9f68-823fbaa447ff.png)
As I meticulously elaborated in [this PR](https://github.com/nestjs/nest/pull/4359), implementation is already in place thanks to `flatten` function, so there are only 2 thing that would need updating: documentation and types.

**Comment by GrayStrider** [comment]
will also work with
```TS
const m1 = [ma(), mb()]
const m2 = [mc(), md()]
apply(m1, m2)
```
types of expressions, since `flatten` will recursively run as long as there are any arrays in the arguments.

**Comment by kamilmysliwiec** [comment]
I've already replied here https://github.com/nestjs/nest/pull/4359#issuecomment-602018394. Please, stop creating issues/PRs regarding this.
