### ISSUE TITLE
Exceptions thrown in GraphQL resolvers are considered as valid returns

### ISSUE THREAD

**Issue by greg-md** [nestjs/nest#4374]
## Bug Report

If I throw a non-standard exception in a resolver, it thinks it's a response and tries to validate it.

## Current behavior
If thrown exception is a valid response format, it returns as successful:
```json
{
  "data": {
    "attack": true
  }
}
```

If thrown exception is not a valid response format, it returns invalid field format:
```json
{
  "errors": [
    {
      "message": "Boolean cannot represent a non boolean value: \"Error\"",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "attack"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": null
}
```

## Input Code

```ts
@Mutation(returns => Boolean)
async attack(): Promise<boolean> {
  throw 'Error';
  // or
  throw true;
}
```

## Expected behavior
It should return a generic internal error, but not a validation error.

## Environment

<pre><code>Nest version: 7.0.3

For Tooling issues:
- Node version: v12.3.1
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in `@nestjs/core@7.0.4`. Thanks for reporting!
