### ISSUE TITLE
Electron + Nestjs: Express still a hard dependency

### ISSUE THREAD

**Issue by ASAPHAANING** [nestjs/nest#4382]
## Current behavior
I removed `@nestjs/platform-express` to use Nestjs for its DI & other utilities for an Electron project. When I initialize the root module I get the following error:

``` [PackageLoader] No driver (HTTP) has been selected. In order to take advantage of the default driver, please, ensure to install the "@nestjs/platform-express" package ($ npm install @nestjs/platform-express).```

## Input Code
https://github.com/ASAPHAANING/electron-react-nestjs

Removing @nestjs/platform-express and changing the code in `src/main/main.ts` to:

```ts
    const app = await NestFactory.create(AppModule);
    await app.init()
```
Still gives me the error

## Expected behavior
No complaints and Nest runtime starting fully

## Environment

Nest version: 7.0.4
 
For Tooling issues:
- Node version: v10.16.0
- Platform:  Arch Linux x86_64

**Comment by izio38** [comment]
NestJs needs an Http platform in order to receive request and respond to it.

However, Nest can be used as a standalone application (https://docs.nestjs.com/standalone-applications), by using it, you'll get the DI system.

But, you cannot use the Http Server without having an http platform.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
