### ISSUE TITLE
Helper function for mocking mongoose models to plain objects

### ISSUE THREAD

**Issue by abbasogaji** [nestjs/nest#4385]
## Feature Request

Helper function for mocking mongoose models to plain objects

## Describe the solution you'd like

````typescript
 .....

 {
        provide : getModelToken('Contract'),
        useValue : generateMockModel('Contract', contractSchema)
         // generates a plain Object that implements "mongoose.Model" 
                                                                                                       
      },
.....
````

**Comment by jmcdo29** [comment]
There are already libraries like this that exist for helping create mocks. The problem with _some_ of these is that it would lock a user into using only one test runner, which is against what Nest wants to do. The docs even mention that the `Test.createTestingModule` works with any test runner, so I'm not sure if a method dedicated to creating mocks would be the best, as it would rely either on a specific test runner, or another library and new methods.

[One from golevelp](https://github.com/golevelup/nestjs/tree/master/packages/testing)
[jest-mock-extended](https://github.com/marchaos/jest-mock-extended)
[ts-mockito](https://github.com/NagRock/ts-mockito)
[Substitue](https://github.com/nsubstitute/NSubstitute)
