### ISSUE TITLE
Throwing a different HTTP status code in ValidationPipe error

### ISSUE THREAD

**Issue by Dominic-Preap** [nestjs/nest#4393]
## Feature Request
Is there any ways to return a different HTTP status code when throwing in `ValidationPipe`? 

```json
// Default response in Nest 7
{
  "statusCode": 400,
  "message": ["email must be an email"],
  "error": "Bad Request"
}

// I want change to HTTP status code
{
  "statusCode": 422,
  "message": ["email must be an email"],
  "error": "Unprocessable Entity"
}
```

Using `exceptionFactory` will return `class-validator` errors which I have to write a custom function to return a response object like above. In the past, I put that function in `AppExceptionFilter`.
```ts
new ValidationPipe({
  exceptionFactory: errors => {
     //  Some Logic to transform error response 
     return new UnprocessableEntityException(errors);
  }
});
```

## Is your feature request related to a problem? Please describe.

I just want throw every DTO exception errors with status code 422 without writing a custom function to transform a response either in `AppExceptionFilter` or `ValidationPipe`.
```ts
app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
app.useGlobalFilters(new AppExceptionFilter());
```

## Describe the solution you'd like

I suggest we should have an option to pass HTTP status code enum in `ValidationPipe`.
```ts
new ValidationPipe({
  exceptionCode: HttpStatus.UNPROCESSABLE_ENTITY // something like that
});
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Dominic-Preap** [comment]
I will take a look into that.

**Comment by iveselin** [comment]
I would also like to add a small snippet of code that could be related to this. I am not using current version of Nest, but in previous ones you would get only one level of validation errors displayed. If that is true for v7 also i could have a fix. I have created this small snippet that we use to extract and flatten all validation errors, even from nested objects in one nice format. 
```typescript
export const extractAllErrors = (e: ValidationError): string[] => {
  if (!!e.children && e.children.length) {
    const errors: string[] = [];
    e.children.forEach((child) => {
      errors.push(
        ...extractAllErrors(child).map(
          (childErr) => `${e.property} => ${childErr}`,
        ),
      );
    });
    return errors;
  } else {
    return values(e.constraints);
  }
};
```
This piece of code extracts all errors in a nice readable way and than i flatMap it with lodash in message param 
```typescript
...
message: flatMap(errors, (e: ValidationError) => extractAllErrors(e)),
...
```
---
PS yes i know its a recursion, but it works like a charm for a long time with response being something like this:
```json
{
  "statusCode": 400,
  "error": "Incorrect parameters",
  "message": [
    "description must be a string",
    "revisionStage must not be greater than 3",
    "referenceTo => 0 => property fasdf should not exist",
    "referenceTo => 0 => id must be an UUID",
    "formTemplate => property helloSignTemplateId should not exist"
  ]
}
```

**Comment by Dominic-Preap** [comment]
@ivanveselin they're already tracking [here](https://github.com/nestjs/nest/pull/4360)

**Comment by kamilmysliwiec** [comment]
Added in 7.0.6
