### ISSUE TITLE
Dynamic module's providers cannot be injected

### ISSUE THREAD

**Issue by aliu-bsm** [nestjs/nest#4395]
## Current behavior
Dynamic module's providers cannot be referenced after #3363 's fix. 

The dynamic module is loading exporting and import from different module based on an environment variable. With the fix, the provider cannot be referenced/injected anymore.

I have tried changing the name of the `prod` & `dev` module, but it does not fix the problem.

## Input Code
[A minimum reproducible repo](https://github.com/aliu-bsm/nestjs-dynamic).

You should see an error after you start the app.
```bash
$ npm i && npm run start
```

**Dynamic module**
```ts
@Module({})
export class MyDynamicModule {
  static init(): DynamicModule {
    const myModule =
      process.env.NODE_ENV === 'production'
        ? require('./my-dynamic.module.prod')
        : require('./my-dynamic.module.dev');
    const imports = [myModule.MyDynamicModule]

    return {
      exports: imports,
      imports,
      module: MyDynamicModule,
    };
  }
}
```

## Expected behavior

Prior to the fix (version 6.9.0), the providers can be injected/referenced in other services.

## Possible Solution

N/A.

## Environment

<pre><code>
Nest version: 6.10.0 (affected)

 
For Tooling issues:
- Node version: 10.16.3
- Platform: Mac 10.14.6

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Your code is invalid. `NestHttpModule.registerAsync` imports the `MyDynamicModule` module (which is not global). `MyDynamicModule` doesn't export anything by default. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
