### ISSUE TITLE
[Microservices]: refactor serializer/deseriazlier to their base types

### ISSUE THREAD

**Issue by shlomiassaf** [nestjs/nest#4406]
## Is your feature request related to a problem? Please describe.

Currently, `Server` defines the serialization types as follows: 

https://github.com/nestjs/nest/blob/831dac8e8a016f288f2b38b67670c7c98362be73/packages/microservices/server/server.ts#L38-L39

While the library has a more generic types

```ts
export interface Serializer<TInput = any, TOutput = any> {
    serialize(value: TInput): TOutput;
}

export interface Deserializer<TInput = any, TOutput = any> {
    deserialize(value: TInput, options?: Record<string, any>): TOutput;
}
```

This forces all implementations to obey the consumer model, while they might want to implement it differently or follow a different model (with new decorators of course).

## Describe the solution you'd like

Refactor `serializer` and `deserializer` to use the more generic `Serializer` and `Deserializer` types.

To maintain compatibility, Generics can be added:

```ts
  //...
  export abstract class Server<TSer extends  Serializer = Serializer, TDes extends Deserializer = Deserializer> {
    protected serializer: TSer;
    protected deserializer: TDes;
  //...
```

Or, to really keep things as they were:

```ts
  //...
  export abstract class Server<TSer extends  Serializer = ConsumerSerializer, TDes extends Deserializer = ConsumerDeserializer> {
    protected serializer: TSer;
    protected deserializer: TDes;
  //...
```

## What is the motivation / use case for changing the behavior?

- Implementing slightly different paradigms of the request / response model
- Working with microservices using different paradigms
 - I believe it's in general the right types to put there.

> Note that the current decorators (`MessagePattern`, `EventPattern`) do restrain the microservices package to a defined model however this can be worked-around while still using the underlaying framework (handler discovery, defined flow, etc...)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by shlomiassaf** [comment]
Sure, will proudly help :)
