### ISSUE TITLE
Wrong error response object? 

### ISSUE THREAD

**Issue by ardyfeb** [nestjs/nest#4408]
## Current behavior
`HttpException` repoduces wrong object, when calling `new ForbiddenException('error_code_string', 'error_message`) response should like this

```
{
  "statusCode": 403,
  "message": "error_message",
  "error": "error_code_string"
}

```

instead
```
{
  "statusCode": 403,
  "message": "error_code_string",
  "error": "error_message"
}

```

## Input Code
Reproducible repo: https://github.com/ardyfeb/nest-issue-response

## Possible Solution
on https://github.com/nestjs/nest/blob/master/packages/common/exceptions/http.exception.ts#L78
should be

```diff
- { statusCode, message: objectOrError, error: message }
+ { statusCode, message, error: objectOrError };
```

## Environment

<pre><code>
Nest version: 7.0.5
 
For Tooling issues:
- Node version: v13.9.0
- Platform:  LInux (Arch)
</code></pre>

**Comment by ardyfeb** [comment]
i'll send pr if needed

**Comment by ardyfeb** [comment]
another reference https://github.com/nestjs/nest/blob/master/packages/common/exceptions/forbidden.exception.ts#L29

**Comment by kamilmysliwiec** [comment]
It seems that the comment is invalid. The response object is fine though.

**Comment by ardyfeb** [comment]
`error` field like more suitable for error code such "invalid_credentials", "token_required" and `message` field for friendly error like "Token are required for this request"

**Comment by ardyfeb** [comment]
Same as github api https://developer.github.com/v3/#client-errors

**Comment by kamilmysliwiec** [comment]
If you don't agree with the current behavior, you can create an exception filter and define a different response object shape. We discussed this many times in the past already.

Fixed in this commit https://github.com/nestjs/nest/commit/f7b48a3e181e1d430c62977aa2a6d096d9ffc3d3
