### ISSUE TITLE
Returning throwError within websocket interceptor does nothing

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#4411]
## Current behavior
When returning `throwError()` within a websocket interceptor the client does not receive an error event. Instead the error is shown in the console:

<img width="655" alt="Bildschirmfoto 2020-03-25 um 01 31 24" src="https://user-images.githubusercontent.com/5103210/77489457-721dc900-6e38-11ea-9729-082babda868a.png">

## Input Code

```ts
@Injectable()
export class GatewayAuthInterceptor implements NestInterceptor {
  constructor(private authService: AuthService) {
  }

  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    const socket = context.switchToWs().getClient() as Socket;
    const accessToken = socket.handshake.query.accessToken;

    if (!this.authService.isValid(accessToken)) {
      return throwError('unauthorized');
    }

    return next.handle();
  }
}
```

## Expected behavior
The client should receive an error event. Nothing should be shown in the console.

## Workaround
return nothing. Instead throw an error manually:

```ts
if (!this.authService.isValid(accessToken)) {
    socket.error('unauthorized');
    return;
}
```

## Environment

<pre><code>
Nest version: 7.0.3
</code></pre>

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/77511977-65b66200-6e72-11ea-9f61-e56dccedbf69.png)

https://docs.nestjs.com/websockets/exception-filters

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by MickL** [comment]
I tried `throw new WsException('Invalid credentials.');` but it does nothing. May you reopen?

I tested:
- `return throwError('unauthorized');`
-> Logs error. No error-event sent to the client.
- `return throwError(new Error('unauthorized'));`
-> Logs error, shows error in console. No error-event sent to the client.
- `return throwError(new WsException('unauthorized'));`
-> Does nothing. No error-event sent to the client.
- `throw new Error('unauthorized');`
-> Logs error, shows error in console. Error-event IS sent to the client.
- `throw new WsException('unauthorized');`
-> Does nothing. No error-event sent to the client.

Also it is very confusing that in a normal interceptor you can return a RxJS `throwError()` but in a WS you cant?

**Comment by kamilmysliwiec** [comment]
Please, listen to the `exception` message, not `error`. `error` is a reserved event

**Comment by MickL** [comment]
There is no such event:

Server: `throw new WsException('unauthorized');`
Client: `fromEvent(this.socket, 'unauthorized')..subscribe(data => { ... });`

Anyway I would find it kind of confusing:

1. The documentation throws `Invalid credentials.` which is a human readable string, not an event-name
2. If the error-message is already taken as the event-name, there is no space to add an actual message or data
3. If i throw an error I would expect socket.io to receive it with 'error' event
4. When I return `next(new Error(constants.admin.socketEvents.unauthorized));` within a middleware socket.io receives the 'error' event as expected:
```
 afterInit(server: Server) {
         server.use((socket, next) => {
                  const accessToken = socket.handshake.query.accessToken;

                  if (!this.authService.authTokenIsValid(accessToken)) {
                           return next(new Error(constants.admin.socketEvents.unauthorized));
                  }

                  return next();
         });
}
   ```

**Comment by kamilmysliwiec** [comment]
Listen to the `exception `message (as stated in the documentation...), not `error` or `unauthorized`. Please, read the documentation carefully and ask such questions on StackOverflow/Discord next time.
