### ISSUE TITLE
Logger with app context for monorepo's

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#4412]
## Is your feature request related to a problem? Please describe.
When having multiple apps/microservices running, it would be nice to set a context for the app itself. Currently there is only a number differentiating the apps, but it is not human readable.

<img width="744" alt="Bildschirmfoto 2020-03-25 um 02 22 19" src="https://user-images.githubusercontent.com/5103210/77491996-a3e65e00-6e3f-11ea-911d-1a7f9dbc49b4.png">

## Describe the solution you'd like
Setting a context for the app itself so above logs would be something like:

```
[start] [Nest] 4623   - 03/25/2020, 2:22:05 AM   [ClientApp] [AppGateway] Client connected, id: 'BH0a-ZW-BX3Q-Qj4AAAA'
[start] [Nest] 4624   - 03/25/2020, 2:22:08 AM   [AdminApp] [AppGateway] Admin connected, id: 'LuiU2tkaDL0ue3ZQAAAA'
```

**Comment by kamilmysliwiec** [comment]
> Currently there is only a number differentiating the apps, but it is not human readable.

I don't think we have any feature that groups logs by the application. It's up to the developer.

> When having multiple apps/microservices running, it would be nice to set a context for the app itself.

Likewise, you can easily accomplish this. There's no need for hardcoding such a thing.

**Comment by MickL** [comment]
@kamilmysliwiec What do you mean by easily accomplish that? How might I set an app context to the logs Nest itself does?
