### ISSUE TITLE
Error importing an existing module on a new module

### ISSUE THREAD

**Issue by DavideCarvalho** [nestjs/nest#4420]
## Current behavior

I created a module inside my project called DashboardModule. This DashboardModule will have dependency with many other modules, but once I add one module inside "imports", it gives me circular dependency error

## Input Code

Repo: https://github.com/DavideCarvalho/newschool-backend
Branch: feature/dashboard-users-quantity.
To run, just create a .env file exactly like .env.example file

The code is currently without the UserModule being importes on DashboardModule, so to replicate the error just add ```ts
...
imports: [ UserModule ]
...
```
On dashboard.module.ts

## Expected behavior
<!-- A clear and concise description of what you expected to happen (or code). -->
The module should import UserModule without give me any kind of error

## Possible Solution
<!--- Only if you have suggestions on a fix for the bug -->

## Environment

<pre><code>
Nest version: X.Y.Z
<!-- Check whether this is still an issue in the most recent Nest version -->
 
For Tooling issues:
- Node version: XX  <!-- run `node --version` -->
- Platform:  <!-- Mac, Linux, Windows -->

Others:
<!-- Anything else relevant?  Operating system version, IDE, package manager, ... -->
</code></pre>

**Comment by LeonardoRosaa** [comment]
I don't understanding, you importing DashboardModule in AppModule where too has imported UserModule, this is necessary? I can be wrong :/

**Comment by DavideCarvalho** [comment]
>  I don't understanding, you importing DashboardModule in AppModule where too has imported UserModule, this is necessary? I can be wrong :/

AFAIK, imports are scoped into the modules that request it. If I need UserModule to be used in all modules without requesting it on “imports” property, I need to make it global

**Comment by kamilmysliwiec** [comment]
See https://github.com/nestjs/nest/issues/1181#issuecomment-430197191 (barrel files = `index.ts`)
