### ISSUE TITLE
Does JwtStrategy fail to throw an exception? 

### ISSUE THREAD

**Issue by matrixpool** [nestjs/nest#4421]
## Bug Report
Does JwtStrategy fail to throw an exception? The exception I throw doesn't seem to be caught by the system!!
```javascript
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor(
    private readonly configService: ConfigService,
    private readonly merchantService: MerchantService,
  ) {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      ignoreExpiration: false,
      secretOrKey: configService.get('jwt').secretKey,
    });
  }

  async validate(payload: ITokenPayload) {
    if (payload.en !== this.configService.get('app').env) {
      throw new UnauthorizedException(ERRORS.ENVIRONMENT_NOTMATCHED);
    }
    return payload
  }
}
```
The exception I throw doesn't seem to be caught by the system!!

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by matrixpool** [comment]
Yes, I am in discord @nestjs/passport. Questions were also posted but no one responded to me
