### ISSUE TITLE
ConfigModuleOptions.envFilePath doesn't allow multiple files as stated in the documentation

### ISSUE THREAD

**Issue by gitlui** [nestjs/nest#4422]
## Current behavior
While registering the ConfigModule its not possible to use more than one file as stated [here](https://docs.nestjs.com/techniques/configuration#custom-env-file-path)
## Input Code

```ts    
ConfigModule.forRoot({
      envFilePath: 'default.env, development.env',
      validationSchema: environmentValidationSchema
    })
```

## Expected behavior
Being able to use more than one file where the values of the last in order are overriding the values of the first stated.

In addition it would really be nice if the stated files could be made optional.

## Environment

<pre><code>
Nest version: 6.14.1

**Comment by kamilmysliwiec** [comment]
Update to the latest version of `@nestjs/config`
