### ISSUE TITLE
Optional chaining not working

### ISSUE THREAD

**Issue by tomsh99** [nestjs/nest#4423]
I tried to use optional chaining in nestjs. In my `tsconfig.json` I tried to set the target to both `esnext` and `es2020`. Then when I run `nest build` everything seems to be ok, but if I run `nest start` I get exception: `SyntaxError: Unexpected token ‘.’`

**Comment by kamilmysliwiec** [comment]
Update `typescript` to the latest version

**Comment by tomsh99** [comment]
I’m using `typescript@3.8.3` which is the latest right now...

**Comment by jmcdo29** [comment]
es2020 and esNext both have problems with optional chaining, [you can see that in the typescript playground](https://www.typescriptlang.org/play/#example/optional-chaining). I usually use es2017-es2019
