### ISSUE TITLE
Default [ExceptionHandler] triggers on caught errors when testing with createTestingModule

### ISSUE THREAD

**Issue by GrayStrider** [nestjs/nest#4444]
Global filter is used in imported module:
`filter.ts`
```TS
@Catch ()
export class GqlExceptionFilter implements ExceptionFilter {
	catch (exception: any, host: ArgumentsHost): void {
		const ctx = host.switchToHttp ()
		const response = ctx.getResponse ()
		const request = ctx.getRequest ()
		const next = ctx.getNext ()
		
		log (exception)
		
	}
}
```

`module.ts`
```TS
{ provide: APP_FILTER, useClass: GqlExceptionFilter }
```
Test setup as usual:
```TS
const moduleFixture = await Test.createTestingModule ({
	imports: [KBFModule]
}).compile ()
// ...
```
But in my test runner, as you can see, both `GqlExceptionFilter` and default `[ExceptionHandler]` get triggered:
![image](https://user-images.githubusercontent.com/43771776/77843828-81ac6180-71ec-11ea-9e89-e83ef1d65fa1.png)

When running the server normally, everything works as expected and default handler only triggers on uncaught exceptions. Is there a way to make test server behave in the same way?

I've tried all variations of applying it, using `app.useGlobalFilters`, using a decorator, using `useValue new ...` etc, default handler still triggers every time.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
