### ISSUE TITLE
How can I get ip when I use graphql?

### ISSUE THREAD

**Issue by YanceyOfficial** [nestjs/nest#4453]
I make this decorator and use it in my graqhql resolver, but I can't get **ip**.

```ts
// req.decorator.ts

export const ReqDecorator = createParamDecorator(
  (data: unknown, ctx: ExecutionContext) => GqlExecutionContext.create(ctx).getContext().req,
)
```

```ts
@Mutation(() => Model)
public async login(@ReqDecorator() req) {
  console.log(req.ip) // undefined
  return this.authService.login()
}
```

**Comment by jmcdo29** [comment]
Please share a repository that reproduces this issue.

**Comment by archer747** [comment]
Faced a similar challenge. Using @Ip() decorator directly in your resolver returns null.
Apparently you need to create a custom decorator such as:

```
import { createParamDecorator, ExecutionContext } from '@nestjs/common';
import { GqlExecutionContext } from '@nestjs/graphql';

export const UserIp = createParamDecorator(
  (data: unknown, context: ExecutionContext) => {
    const ctx = GqlExecutionContext.create(context);
    return ctx.getContext().req.ip;
  },
);
```

**Comment by toknT** [comment]
> Faced a similar challenge. Using @ip() decorator directly in your resolver returns null. Apparently you need to create a custom decorator such as:
> 
> ```
> import { createParamDecorator, ExecutionContext } from '@nestjs/common';
> import { GqlExecutionContext } from '@nestjs/graphql';
> 
> export const UserIp = createParamDecorator(
>   (data: unknown, context: ExecutionContext) => {
>     const ctx = GqlExecutionContext.create(context);
>     return ctx.getContext().req.ip;
>   },
> );
> ```

It may not work , alway get `::ffff:127.0.0.1` under a nginx proxy
