### ISSUE TITLE
es4x under the hood

### ISSUE THREAD

**Issue by nythrox** [nestjs/nest#4454]
## Feature Request
Is it possible for nestjs to support using es4x under the hood? If possible nestjs would be able to perform better then express, fastify, and vanilla nodejs while still being the most elegant solution.

![image](https://user-images.githubusercontent.com/41273690/77862548-a0adf200-71f2-11ea-916e-1210b1a5c7c3.png)

**Comment by kamilmysliwiec** [comment]
We don't plan to support this (yet?)

**Comment by iamkhalidbashir** [comment]
Any news on this ?

**Comment by wSedlacek** [comment]
@kamilmysliwiec What would be the requirements for supporting [es4x](https://github.com/reactiverse/es4x)?
Is the issue interoperability with express plugins?

Basically what I am asking is if there is any place I can proactively contribute to

**Comment by jmcdo29** [comment]
If you'd like to try your hand at it, you could always make your own adapter, like the fastify or Express adapter, that could be passed to the `NestFactory`

**Comment by wSedlacek** [comment]
I was thinking about that however there are sever modules where it assumes that the adapter will either be `fastify` or `express`. 

Example:
https://github.com/nestjs/swagger/blob/a3cd446614f255c1d9d13febd35d1fadf648e2d1/lib/swagger-module.ts#L51-L64

So even I made a custom adapter, these modules would not work unless they support that adapter.
So that kinda rules out maintaining my own adapter, which is why I would want to contribute to unblocking es4x support from nestjs proper.

An alternative would be adding better support for custom adapters within modules like swagger.
I would be happy with this solution if that is the direction that NestJS wants to move in.

**Comment by jmcdo29** [comment]
For the swagger module compatibility, you could also extend that module and patch in the necessary chess for es4x, a least until we figure out a way to provider better extensibility for the package (probably gql would need something too). Or if you could live without it for a bit, just not use swagger. Or, use both es4x and Express, having Express for the sole purpose of generating the swagger file then closing that server immediately. I'll think on what we can do for the extensibility though

**Comment by wSedlacek** [comment]
For sake of completeness here are the other places I see the type of the adapter checked within the nestjs organization:

https://github.com/nestjs/graphql/blob/96ed9def3966a28add72eecf1b74e975879c159b/lib/graphql.module.ts#L182-L193

https://github.com/nestjs/graphql/blob/0af4f4af0d34af4719fe5da02c1815f94150507e/lib/federation/graphql-federation.module.ts#L186-L197

These places will fail more gracefully as they don't assume that `express` is used when `fastify` is not like swagger does.

**Comment by wSedlacek** [comment]
> For the swagger module compatibility, you could also extend that module and patch in the necessary chess for es4x, a least until we figure out a way to provider better extensibility for the package (probably gql would need something too). Or if you could live without it for a bit, just not use swagger. Or, use both es4x and Express, having Express for the sole purpose of generating the swagger file then closing that server immediately. I'll think on what we can do for the extensibility though

Let me know if there is anything I can help with for improving the extensibility.
I will get to work creating a custom adapter and seeing if there are any issues within the runtime (like missing global methods or the like)

Thank you for your timely responses.
