### ISSUE TITLE
Nest can't resolve dependencies of the [ServiceName]

### ISSUE THREAD

**Issue by rrdlpl** [nestjs/nest#4457]
## Bug Report
The error that says that the dependency can't be resolved is not clear enough, because of this. Currently, the error output says: 
```
[ExceptionHandler] Nest can't resolve dependencies of the LeadService (LeadRepository, ?). Please make sure that the argument dependency at index [1] is available in the LeadModule context.
``` 
From this output, I can conclude that the dependency `ConsentService` of my `LeadService`. See `LeadService` constructor below.

Additionally, the output also puts the following suggestion:

*Potential solutions:*

>  - If dependency is a provider, is it part of the current LeadModule?

**My answer:** It is a provider, but it's not part of the current module. It's a provider from the ConsentModule. See ConsentModule definition. 

>  - If dependency is exported from a separate @Module, is that module imported within LeadModule?

```
   @Module({
     imports: [ /* the Module containing dependency */ ]
   })
```
**My answer:** Yes, it is exported from the ConsentModule and it is imported in the LeadModule thus I don't understand why is this failing.

## Input Code
**ConsentService** 
```ts
@Injectable()
export class ConsentService {
  constructor(@InjectRepository(Consent) private repository: Repository<Consent>) {}
}
```

**LeadService**
```ts
@Injectable()
export class LeadService<T extends LeadPayload> {
  constructor(
    @InjectRepository(Lead)
    private leadRepository: Repository<Lead>,
    @Inject()
    private consentService: ConsentService
  ) {}
}
```

**ConsentModule**
```ts
import { Module } from '@nestjs/common';
import { ConsentService } from './consent.service';
import { Consent } from '../db/models';
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
  imports: [TypeOrmModule.forFeature([Consent])],
  providers: [ConsentService],
  exports: [ConsentService]
})
export class ConsentModule {}

```
**LeadModule**
```ts
import { Module } from '@nestjs/common';
import { LeadService } from './lead.service';
import { Lead } from '../db/models';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConsentModule } from './consent.module';

@Module({
  imports: [ConsentModule, TypeOrmModule.forFeature([Lead])],
  providers: [LeadService],
  exports: [LeadService]
})
export class LeadModule {}

```

**AppModule**
```ts
@Global()
@Module({
  imports: [
    ConsentModule,
    LeadModule,
    TypeOrmModule.forRoot({
      ...getDbConnectionProperties(),
      entities: [Consent, Lead]
    })
  ],
  controllers: [
    DevController,
    HealthController
  ],
  providers: []
})
export class AppModule {}
```

## Expected behavior
- I would like to know why exactly is the error happening because I think I have declared everything correctly. If no, a more precise error output could be helpful.

## Environment
Nest version: 7.0.6
 
For Tooling issues:
- Node version: v13.10.1
- Platform:  Mac Catalina 10.15.3
- package manager: yarn

**Comment by kamilmysliwiec** [comment]
```
@Inject()
private consentService: ConsentService
```
Why do you use `@Inject()` here? Remove it.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by rrdlpl** [comment]
> ```
> @Inject()
> private consentService: ConsentService
> ```
> 
> Why do you use `@Inject()` here? Remove it.
> 
> Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

because ConsentService has the @Injectable() annotation. Or is the @Inject() only for the @Controllers ?

**Comment by kamilmysliwiec** [comment]
Please, read the documentation https://docs.nestjs.com/providers

**Comment by kamilmysliwiec** [comment]
For those that are repeatedly struggling with the "Cannot resolve dependency" error, check out the [NestJS Devtools](https://www.devtools.nestjs.com/) (read more [here](https://docs.nestjs.com/devtools/overview#investigating-the-cannot-resolve-dependency-error)).

Example:

![image](https://user-images.githubusercontent.com/23244943/225931543-a92ba2de-fce7-4ae6-8343-3f1d745a2022.png)
