### ISSUE TITLE
Real Time Applications

### ISSUE THREAD

**Issue by all2pie** [nestjs/nest#4458]
## Feature Request

I would like to have full real-time support in nestjs like [https://feathersjs.com/](feathersjs)

That would be great.

PS: Client Library also.

**Comment by all2pie** [comment]
Helpful article that i found: [https://blog.feathersjs.com/design-patterns-for-modern-web-apis-1f046635215](url)

**Comment by BrunnerLivio** [comment]
What do you mean with "real-time" support? Do you mean Websockets? We would have a chapter for [that](https://docs.nestjs.com/websockets/gateways)!

**Comment by kamilmysliwiec** [comment]
NestJS supports real-time applications. Please, check the documentation.

**Comment by all2pie** [comment]
Yep pretty aware of that, i have used them also, but its a very hard to manually implement i.e to make a simple crud real-time, same goes for the client side. 

Please check out the specified framework and the article for a specified solution.
