### ISSUE TITLE
Problem hangs after some days

### ISSUE THREAD

**Issue by carmas123** [nestjs/nest#4459]
Hi all, I've my project running in production but I've a big problem.
My project use SocketIO, Redis and other stuff of NestJS.
I've in my project some apis with a backend Postgres DB, all work fine and I've discovered into NestJS a powerful and very fast and simple developing method for server with nodejs.

My app running with PM2 with an Nginx middleware, the problem is that after some days all hangs the api run slow and sometime with a request timeout but the problem is that the server is idle with a 0 cpu usage and memory free. 
If I restart the app with pm2 restart all work fine again.

Have anyone some problems?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by azwalzaman** [comment]
I'm having the same issue. CPU usage and memory usage is not high at all but my NestJS app would stop responding after a few requests. I use TypeORM with postgres and express js for routing. I also use PM2 with Nginx

**Comment by micalevisk** [comment]
@azwalzaman it's hard to help you out without some code.

Please, open a new issue with a proper repro or use our discord.
