### ISSUE TITLE
Nest.js Installation at cli

### ISSUE THREAD

**Issue by Nirali-Tech** [nestjs/nest#4464]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

I have installed nest.js. now I went to command prompt and give this command, 
$ npm i -g @nestjs/cli
to create a project. but it gives warnings. What should I
![WarningPage](https://user-images.githubusercontent.com/60235470/77949071-59783d80-7294-11ea-8661-c193fb87d329.JPG)
 do?
$ nest new project-name

**Comment by jmcdo29** [comment]
[You'll see in the installation instructions](https://docs.nestjs.com/#installation) that `npm i -g @nestjs/cli` installs the cli and `nest new project-name` creates a new project. Please use [Disocrd](https://discord.gg/nestjs) next time as we are trying ti use Github to track issues and bugs.
