### ISSUE TITLE
Middleware global registration fails

### ISSUE THREAD

**Issue by sergey-prokofiev** [nestjs/nest#4467]
## Current behavior
I create an empty middleware class according to documentation. If I register it using app.use(), I get an exception 

> "TypeError: Class constructor LoggerMiddleware cannot be invoked without 'new'"

 on each http request, regardless if my module implements NestModule interface or not. 
However if the module implements NestModule interface and middleware is registered like 
```ts
consumer.apply(LoggerMiddleware).forRoutes("/");
```
it works.

## Input Code
```ts
@Injectable()
export class LoggerMiddleware implements NestMiddleware {

  use(req: Request, res: Response, next: Function) {
    console.log(req.url);
    next();
    console.log(res.statusText);
  }
}
....
    const app = await NestFactory.create(AppModule, {
      logger: false
    });

    app.use(LoggerMiddleware);
    app.useLogger(app.get("ILogger"));
    return await app.listen(3000);
```

## Expected behavior
Registration should work as documented.
## Environment

Nest version: 7.0.0
 
For Tooling issues:
- Node version: 13.7.0
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by sergey-prokofiev** [comment]
Actually, it is bug.

**Comment by kamilmysliwiec** [comment]
It's not a bug, your code is wrong. Please, verify it once again
