### ISSUE TITLE
confusing http exception messages/errors

### ISSUE THREAD

**Issue by dkocich** [nestjs/nest#4469]
## Bug Report

Make it more clear in the type signature what should be used in HttpExceptions. I would except different behaviour from fn. arguments naming.

## Current behavior

- looks switched here (`message` is in fact an `error` and not `message`)

![image](https://user-images.githubusercontent.com/6165660/78020467-cd2c5000-7351-11ea-888d-cc20bb9c93c8.png)

- looks ok here

![image](https://user-images.githubusercontent.com/6165660/78020392-af5eeb00-7351-11ea-8275-8bfecc0a33ed.png)

## Environment

<pre><code>
    "@nestjs/common": "7.0.3",
    "@nestjs/core": "7.0.3",
    "@nestjs/platform-express": "7.0.3",
    "@nestjs/swagger": "4.4.0",
    "@nestjs/cli": "7.0.0",
    "@nestjs/schematics": "7.0.0",
    "@nestjs/testing": "7.0.3",
 
For Tooling issues:
- Node version: 12

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, update to the latest version. We've fixed this regression + arguments names already
