### ISSUE TITLE
(microservice) Bug getContextFactory() is not a function when create hybrid application.

### ISSUE THREAD

**Issue by trantuan94** [nestjs/nest#4478]
## Bug Report
I'm creating an hybridapp with microservices refer at:https://github.com/nestjs/nest/tree/master/sample/03-microservices example 
When I npm start my service, it cannot run and show error:
TypeError: this.contextUtils.getContextFactory is not a function
    at RpcContextCreator.getMetadata (/home/tuan/nest-auth-service/node_modules/@nestjs/microservices/context/rpc-context-creator.js:74:50)

## Current behavior
After I change the code in 
/node_modules/@nestjs/microservices/context/rpc-context-creator.js file to use getCustomFactory() function. It run normally!. 
I think have an error here!
Please check again and resolve this problem.Thanks!

## Input Code

```ts
import { NestFactory } from '@nestjs/core';
import { Transport, MicroserviceOptions } from '@nestjs/microservices';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.connectMicroservice({
    transport: Transport.TCP,
    options: {
      port: 3001,
      retryAttempts: 5,
      retryDelay: 3000,
    },
  });
  await app.startAllMicroservicesAsync();
  await app.listen(3000);
}
bootstrap();
```

## Environment

<pre><code>
Nest version: 6.13.3
@nestjs/core version: 6.11.11
@nestjs/common version: 6.11.11
@nestjs/microservices version: 7.0.7

 
For Tooling issues:
- Node version: 12.16.1  
- Platform: Linux - Ubuntu 18.04.02

**Comment by kamilmysliwiec** [comment]
Update core and common to the latest version.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
