### ISSUE TITLE
Validation options

### ISSUE THREAD

**Issue by toondaey** [nestjs/nest#4480]
#### Version of NestJS used

* v7.0.0

#### Use-case 

* Validation

Hi nest team,

So I was playing around with the validation here and I noticed that users get a flattened validation error array right out of the box. It's a great idea, but I think users should have the options to get a flat validation or the full `ValidationError[]` as provided by `class-validator`.

Just a thought though.

https://github.com/nestjs/nest/blob/76ff1016da4540c4da22c9eb1048e8eac6015564/packages/common/pipes/validation.pipe.ts#L123

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/pipes#the-built-in-validationpipe

Use the `exceptionFactory` configuration property
