### ISSUE TITLE
Exception Filter: catch errors returned by factory function

### ISSUE THREAD

**Issue by GrayStrider** [nestjs/nest#4481]
```TS
function makeCustomError (
	code: ErrorCodes, defaultMessage: string,
	defaultDetails?: AnyObject | string
) {
	
	return class ExpectedError extends ApolloError implements IExpectedError {
		
		public details?: AnyObject | string
		
		constructor (message?: string, details?: AnyObject | string) {
			
			super (message ?? defaultMessage, code)
			this.details = details ?? defaultDetails ?? {}
			
		}
		
	}
	
}
```

I've tried supplying `@Catch()` an instance of `makeCustomError(...)`, but it doesn't seem to work, errors fall through to the default handler. Is this even possible to do with `@Catch()` , or should I look into other methods?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
