### ISSUE TITLE
query params metatype is null in pipe

### ISSUE THREAD

**Issue by Diluka** [nestjs/nest#4485]
### route
```ts
@Get()
testRoute(@Query() qs: FormType){}
```
### pipe
```ts
  transform(value: any, metadata: ArgumentMetadata): any {
// metadata.metatype is null
}
```

## Expected behavior

`metadata.metatype` is `FormType`

## Environment

<pre><code>
Nest version: 7

 
For Tooling issues:
- Node version: 12 
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by Diluka** [comment]
I don't know why but it seems ok now.

I was creating a minimum reproduction repository. And find out it is working fine.

Then I delete package-lock.json and node_modules and reinstall the deps. Now it can get metatype.

My project start one year ago. And it upgrades several times from 5, 6 and now is 7.
