### ISSUE TITLE
i18n module

### ISSUE THREAD

**Issue by cosinus84** [nestjs/nest#4486]
I am new to nestJs. Because I wanted to use some solid framework with TS I chose nestJS. What I want is to implement i18n. I was surprised to see that the framework doesn't mention anything about i18n. Also class-validator decorators on dto can't be used, I must find a way to validate using message keys or something.

Is there any plan to provide a solid i18n module? Is there some explanation that there is none?
Thanks

**Comment by kamilmysliwiec** [comment]
>  Is there some explanation that there is none?

NestJS is an Open source product. If you want to invest your time, you can build such a module and share it with the community. Unfortunately, we have a tons of other more important things to do and therefore, providing everything out-of-the-box is pretty much impossible.

Anyways, there's a community package which you can consider using https://github.com/ToonvanStrijp/nestjs-i18n

Also, any existing solution for express (e.g., https://www.npmjs.com/package/i18n) should work fine as well.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
