### ISSUE TITLE
No way to access ValidationError on exception filters.

### ISSUE THREAD

**Issue by daigok** [nestjs/nest#4489]
## Feature Request
The ability to access validation error details on exception filters.

## Is your feature request related to a problem? Please describe.
If I want to customer error messages of REST API response, I need to implement an exception filter. However, validation error details are lost on the validation pipe. It converts ValidationError[] to string[] and no way to recover the error details.

## Describe the solution you'd like
The ability to access the ValidationError[] on exception filters like ASP.NET Core's ModelState. It also has very handy factory method InvalidModelStateResponseFactory for customizing error response. This provides a better way to achieve #2953 too.

https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1

## What is the motivation / use case for changing the behavior?
Improve the flexibility of exception filter and easier to customer error messages.

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/validation

```typescript
new ValidationPipe({ exceptionFactory: (errors) => new BadRequestException(errors) })
```

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
