### ISSUE TITLE
Support for Deno

### ISSUE THREAD

**Issue by jadhavajay** [nestjs/nest#4495]
## Feature Request
Now that it has [been announced](https://github.com/denoland/deno/issues/2473#issue-453631188) that Deno 1.0 will be released the 13rd of May 2020.

So maybe it's time to consider this?

## Is your feature request related to a problem? Please describe.
Nope. When Deno 1.0 releases in the May, it would great to start using it with NestJS.

**Comment by kamilmysliwiec** [comment]
As @BrunnerLivio, let's see how Deno evolves over time. If the community grows rapidly, I'll certainly consider porting several core mechanisms to Deno, respecting their style guide and conventions. It doesn't make any sense at this point though.
