### ISSUE TITLE
Duplicated route silently stops serving

### ISSUE THREAD

**Issue by underfisk** [nestjs/nest#4496]
## Current behavior
So if i created 2 routes with the equal endpoints with same params, nest instead of throw any kind of error, it allows the same replication but it stops the application of serving. What i mean is that the application is running but if you try to cURL or access via http the app, it displays as if the app was not running.

## Input Code
```ts
    @Post(':charterId/products/:id')
    async onProductUpdate(
        @Param() { charterId, id }: BusinessUpdateLineDto,
    ): Promise<boolean> {
       ....
    }

    @Post(':charterId/products/:id')
    async onProductDuplication(
        @Param() { charterId, id }: BusinessUpdateLineDto,
    ): Promise<boolean> {
       ....
    }
```

## Expected behavior
Either both are invoked or only one is handled but some kind of warning or error is throwed but instead the app is not serving http requests

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by underfisk** [comment]
This is strange but sometimes happens and there is no error thrown, the app boots fine, and the listen callback is invoked but when you try to access one of the controllers it either throws "ERR_CONNECTION_RESET" and appears as if the app was offline.
Is there any way to access the internal errors, I'm not sure if they are thrown but my custom logger doesn't catch any error at all.
I can't publish this production application but this needs triage in order to see if some misconfiguration or duplication might conflict with the router service or something
