### ISSUE TITLE
Allow auth guard on handleConnection

### ISSUE THREAD

**Issue by twigs67** [nestjs/nest#4497]
As it stands, there's no way to use the AuthGuard when the connection is initially made. Are there any plans on adding this? 

In the meantime, has anyone found a workaround for this? I'm trying to capture the users id and add it to the connection pool. This seems like it should be doable. 

Thanks

**Comment by kamilmysliwiec** [comment]
You can simply use `handleConnection` hook for now (without guards). 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
