### ISSUE TITLE
Abstraction for Real Time Applications

### ISSUE THREAD

**Issue by all2pie** [nestjs/nest#4501]
## Feature Request

I am using Nest for every web and app backend but whenever i have to add real-time functionality even for a simple curd, i have to manually make socket connection and manually handle all the functionality associated with it (using nest socket wrapper). So when my friends ask me which framework to use for fully real time application, i can not recommend nest to them, which is sad. I myself want nest to be the framework for all kinds of backends.

So i am suggesting to please have a look at https://feathersjs.com/

It uses this https://blog.feathersjs.com/design-patterns-for-modern-web-apis-1f046635215

If some functionality like this can be added it would be great. 

PS: I am not an experienced developer yet, otherwise i wold have manually contributed and made this feature available and opened a pull request.

**Comment by kamilmysliwiec** [comment]
As long as you follow the documentation and you use services to retrieve data & interact with the database, adding a real-time layer (WebSockets) on top of that shouldn't take more than a few minutes (simply inject a platform-agnostic service into a gateway and setup message handlers). Everything that is described in the article you mentioned can be easily accomplished with Nest with a minimum effort.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
