### ISSUE TITLE
Allow customization of kafka logcreator

### ISSUE THREAD

**Issue by oemergenc** [nestjs/nest#4508]
## Feature Request
As far as i can see the kafkajs logCreator config is hard coded and can not be customized by the nestjas application developer. Please propagate the config of the logCreator up to kafkajs.

## Is your feature request related to a problem? Please describe.
`ClientKafka` class has this code:
```
public createClient<T = any>(): T {
    return new kafkaPackage.Kafka(
      Object.assign(this.options.client || {}, {
        clientId: this.clientId,
        brokers: this.brokers,
        logCreator: KafkaLogger.bind(null, this.logger),
      }) as KafkaConfig,
    );
  }
```
While `this.options` object comes from the application developer and could be used to customize the logcreator, the logcreator is hardcoded an cannot be customized.

## Describe the solution you'd like
If the application developer specifies a kafkaOptions object like this:
```
    {
        transport: Transport.KAFKA,
        options: {
            client: {
                clientId: 'my-client-id,
                logCreator: myCustomLogCreator
...
```
propagte it to kafkajs lib.

**Comment by jmcdo29** [comment]
Would you like to create a PR for this? Looks like an update to [this file](https://github.com/nestjs/nest/blob/master/packages/microservices/interfaces/microservice-configuration.interface.ts#L131) and to the [client-kafka](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-kafka.ts#L143) file.

**Comment by Durairaj** [comment]
> Would you like to create a PR for this? Looks like an update to [this file](https://github.com/nestjs/nest/blob/master/packages/microservices/interfaces/microservice-configuration.interface.ts#L131) and to the [client-kafka](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-kafka.ts#L143) file.

Is Someone working on this PR?

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome :)
