### ISSUE TITLE
Custom condition in @Catch()

### ISSUE THREAD

**Issue by fw623** [nestjs/nest#4516]
## Feature Request
Allow defining custom condition for when an exception filter should be called.

## Is your feature request related to a problem? Please describe.
The current stituation where an exception filter only checks for `instanceof` and catches any instances of these errors (or any error when `@Catch()` is empty) is too coarse. 

This becomes a problem when one wants to handle errors of the same class (e.g. with different message formats) differently and thus in their respective exception filters without having to differentiate within the exception filter. 

Another situation is when a package throws e.g. a `BadRequestException` (1) but from another `node_modules` directory than where the filters are defined, the exception filter with `@Catch(BadRequestException)` (2) will not catch it, because the thrown `BadRequestException` (1) will not be `instanceof BadRequestException` (2).

## Describe the solution you'd like
One approach would be to allow exception filters to rethrow the received exception for the next exception filter to catch it. Though this is currently not possible and I believe not the cleanest approach since it might break current implementations.

### Proposed solution
Allow passing a function which returns a `boolean` to `@Catch()`. According to its return value, the exception filter will be called or not.\
This function should receive the same paramaters as the `catch` method of the filters (`exception: T, host: ArgumentsHost`). 

Note that this would be fully compatible with the current implementation since it should be no problem to differentiate between a function and the Exceptions (which can still be checked with `instanceof`).

## Teachability, Documentation, Adoption, Migration Strategy

```typescript
// async should also be possible
function isSpecialError(exception: Error, host: ArgumentsHost): boolean {
  // ... logic to determine whether it looks like a special error
  return true
}

@Catch(isSpecialError)
class SpecialExceptionFilter<T extends Error> implements ExceptionFilter {
  catch(exception: T, host: ArgumentsHost) {
    // ...
  }
}
```

## What is the motivation / use case for changing the behavior?
* more flexibility in distributing exceptions to filters
* provide clean solution to the above problems

**Comment by fw623** [comment]
I would like to contribute a solution for this myself.

My approach would be to change `ExceptionFilterMetadata` to 
```typescript
export type ExceptionFilterMetadata = {
  func: ExceptionFilter['catch'];
  exceptionMetatypes: Type<any>[];
} | {
  func: ExceptionFilter['catch'];
  catchCondition: (exception: Error, host: ArgumentsHost) => boolean | Promise<boolean>;
}
```
and append either `exceptionMetatypes` or `catchCondition` to the `filter` according to whether a function was passed to `@Catch` or not.

And then obviously change all the checks from checking `exceptionMetatypes` to either `exceptionMetatypes` or `catchCondition` depending on what is defined.

**Comment by kamilmysliwiec** [comment]
> This function should receive the same paramaters as the catch method of the filters (exception: T, host: ArgumentsHost).

If this function would accept the same set of arguments, why can't you just move this filtering logic to the `catch()` method body?

**Comment by fw623** [comment]
> If this function would accept the same set of arguments, why can't you just move this filtering logic to the catch() method body?

We could also only pass the `exception` but I believe that is unnecessarily limiting.

### Current workaround
What you proposed is pretty much what I currently use (which - I hope you agree - is not pretty).

For example if I want to have the filters to be checked in this order (if they should catch it or not): `ValidationExceptionFilter ` --> `HttpExceptionFilter ` --> `GlobalExceptionFilter`

Currently I have to only use the `GlobalExceptionFilter` which catches all exceptions with an empty `@Catch()` and do something like this in it:
```typescript
const payload = ValidationExceptionFilter.isOfType(exception)
  ? ValidationExceptionFilter.payload(exception)
  : HttpExceptionFilter.isOfType(exception)
    ? HttpExceptionFilter.payload(exception)
    : this.payload(exception)
```

and therefore lose the ability to use only a subset of these filters or simply in a different order (which doesn't make sense in this example, but I'm sure could be the case in other situations).

Note that in this case it is needed because of the exceptions originating from another `node_modules` directory and thus not being caught accordingly by the `@Catch` decorator. If that wasn't the case, one could do it like in the example below (which is still not ideal). 

### Example: Validation Exception
This was before NestJS transformed the `class-validator` exceptions, so I'm not sure how relevant this exact use case is now, but I hope you get the idea why it'd be useful.

Here I wanted to transform the `class-validator` exceptions before sending them to the client. Therefore I want to create a `ValidationExceptionFilter` which should only catch `BadRequestExceptions` which have the message of a `class-validator` exception, and not all `BadRequestExceptions` because ideally the normal `BadRequestExceptions` would be caught in the `HttpExceptionFilter`. 

Right now the `ValidationExceptionFilter` has to catch all `BadRequestExceptions` and also handle ones which aren't `class-validator` exceptions.\
With my proposed solution, it'd be possible for the `ValidationExceptionFilter` to receive only `class-validator` exceptions.

### Other solution
Another possible solution would be to allow for a method `catchIf` in all filters which (if defined) would act like the `@Catch` decorator. But I prefer changing the `@Catch` decorator as that is what is already doing what I want - just only checking with `instanceof` and not allowing more granular distribution.

**Comment by kamilmysliwiec** [comment]
> Here I wanted to transform the class-validator exceptions before sending them to the client. Therefore I want to create a ValidationExceptionFilter which should only catch BadRequestExceptions which have the message of a class-validator exception, and not all BadRequestExceptions because ideally the normal BadRequestExceptions would be caught in the HttpExceptionFilter.

For this, you should simply define the `ValidationExceptionFilter` which inherits from `HttpExceptionFilter`. Then, the `catch` method could look as follows:

```typescript
catch(err, host) {
   if (isClassValidatorErr) {
      return super.catch(err, host);
   }
  your logic
}
```

And that's it. This can be also properly tested (as opposed to a custom condition passed as an anonymous function to a decorator).

> Note that in this case it is needed because of the exceptions originating from another node_modules directory and thus not being caught accordingly by the @Catch decorator. If that wasn't the case, one could do it like in the example below (which is still not ideal).

This means your dependencies are incorrectly defined. Every shared package should be defined as peer dependency. Hence, all exceptions will originate from the same `node_modules` directory.

**Comment by fw623** [comment]
Makes sense to extend from the `HttpExceptionFilter` and it works how I want it to.\
I was actually trying something like this at first but I couldn't get it to work - maybe because the *incorrect* depenedencies. :thinking:

I'll look into how to use peer dependencies, thank you!

This solution doesn't quite allow for the same degree of freedom as my proposed feature, but I agree with you and believe this feature would then be unnecessary (assuming the peer dependency stuff works).

**Comment by schiemon** [comment]
Suppose we want to catch Mongoose's `MongoError`s via `ExceptionFilter`s. It would be nice to have something like that:

```ts
@Catch(exception => exception instanceof MongoError && exception.code === 11000)
class DuplicationKeyMongoExceptionFilter {...}
```
```ts
@Catch(exception => exception instanceof MongoError && exception.code === 4)
class NoSuchKeyExceptionFilter {...}
```

This would allow us to only use those `ExceptionFilters` that we expect would fire at a Controller. For achieving that we see us left with the following options:

1. Use a Mongoose plugin to unravel the generic `MongoError` to then differentiate between the error types (e.g `MongoDuplicationKeyError`). Then we could write separate `ExceptionFilter`s.
2. Use Interceptors.
3. Forget about multiple Filters and catch every `MongoError` and `switch`-through each type of exception as mentioned [here](https://stackoverflow.com/questions/50864001/how-to-handle-mongoose-error-with-nestjs).

Is there a recommended approach for such use cases where we want to split up the exception instances coming from a single class?

**Comment by micalevisk** [comment]
@fw you could use the lib [nestjs-conditional-exception-filter](https://www.npmjs.com/package/nestjs-conditional-exception-filter) for that :)

see here how it works: https://dev.to/micalevisk/nestjs-tip-fine-grained-exception-filtering-for-the-same-exception-class-5ha5
