### ISSUE TITLE
NestJS v7 new project test SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by z-ax** [nestjs/nest#4517]
## Bug Report
Getting syntax error when trying to run tests on a new project.

## Current behavior
Create a project, run `npm run test` (or `test:cov`, `test:watch`). Getting an error:

```
    Details:

    /Users/dklymenko/Repo/nxx/web-nest/src/app.controller.spec.ts:1
    import { Test, TestingModule } from '@nestjs/testing'
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime._execModule (../node_modules/jest-runtime/build/index.js:1009:58)
```

## Expected behavior
Test runs and seccedes.

## Possible Solution
Something's off in configuration. For example, `npm run test:e2e` succeeds, `test:debug` runs (didn't connect with IDE yet).
Also: `start*`, `build`, `format`, `lint` scripts run just fine.

## Environment

<pre><code>
Nest version: v7 (latest as of now)
 
For Tooling issues:
- Node version: v12.16.1
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
I can't reproduce your issue. 
Please provide a minimum reproduction repository.

**Comment by z-ax** [comment]
That's pretty weird, just created a new one and it doesn't fail. Closing it then until get once again, thanks for checking it out.
