### ISSUE TITLE
Optional injection doesn't work properly in graphql modules.

### ISSUE THREAD

**Issue by snys98** [nestjs/nest#4518]
## Current behavior

Optional dependency didn't resolve properly and throws exception.

## Input Code

![image](https://user-images.githubusercontent.com/11873100/78454949-02c49680-76ce-11ea-8d3a-7f5bc0f7afe5.png)

which leads to 

![image](https://user-images.githubusercontent.com/11873100/78454985-4a4b2280-76ce-11ea-97c5-ddd9587dc12e.png)

## Expected behavior

assign undefined to optional dependencies but do not throw exception.

## Possible Solution

ignore undefined instance wrapper and return undefined for these dependencies

## Environment

<pre><code>
Nest version: 7.0.7

 
For Tooling issues:
- Node version: 12.16.1  
- Platform:  Windows 

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by snys98** [comment]
Well, It's kind of wired that this only happens in my _large_ repository, and won't reproduce in my testing minimal one. Maybe there are some other dependencies that causes this problem. I'll close this issue before I really figure it out. Thanks for replying. 😄

**Comment by GrayStrider** [comment]
@snys98 That's the way it always goes 😄
