### ISSUE TITLE
Using request scope efficiently

### ISSUE THREAD

**Issue by guyisra** [nestjs/nest#4521]
## Bug Report
Request scope is very useful in request based flows, where one would need to store information to be used throughout the request's life. However, when the provider that is scoped for a request is injected to singleton controllers, these get request scope as well, making the whole chain request scoped. While this is fine in theory, I found this causes memory leaks in specific types (perhaps all?) of use cases

## Input Code

Using request scope in in a service that looks like 
```
export class ContextService {
    private readonly store: Store

    constructor() {
        this.store = {}
    }
}
```
where information would be stored a long the way of a request, like tokens generated, etc
and then used in chain that looks like

controller (singleton) <- utilService (singleton) <- contextService (request scope)

makes all the data in the util service to be duplicated for each request and then this doesn't garbage collected
## Expected behavior
all of the objects that is request scoped or caused to be request scope will be garbage collected
## Possible Solution

So I am wondering if there is a special know-how to using request scope in a real app flow (real as in complex)

## Environment

<pre><code>
Nest version: 6 & 7

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
> While this is fine in theory, I found this causes memory leaks in specific types (perhaps all?) of use cases

It doesn't cause memory leaks unless your code creates them.

> controller (singleton) <- utilService (singleton) <- contextService (request scope)

In this chain, everything would become request-scoped either way (as stated in the docs) so marking them as singleton won't change anything.

> makes all the data in the util service to be duplicated for each request and then this doesn't garbage collected

The garbage collector cannot clean up the memory as long as any reference to per-request data exists (which is somewhat obvious). If you store a reference to, e.g., request object, long after the response has been sent already, JS won't be able to remove all associated objects.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
