### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by elie222** [nestjs/nest#4524]
## Current behavior

Server won't start up. Can't find entity files.

## Input Code

Updated packages to these versions:

```
  "dependencies": {	  "dependencies": {
    "@nestjs/common": "^7.0.3",	    "@nestjs/common": "^7.0.7",
    "@nestjs/config": "^0.4.0",	    "@nestjs/config": "^0.4.0",
    "@nestjs/core": "^7.0.3",	    "@nestjs/core": "^7.0.7",
    "@nestjs/graphql": "^7.0.9",	    "@nestjs/graphql": "^7.2.0",
    "@nestjs/passport": "^7.0.0",	    "@nestjs/passport": "^7.0.0",
    "@nestjs/platform-express": "^7.0.3",	    "@nestjs/platform-express": "^7.0.7",
```

## Expected behavior

Server starts up.

## Possible Solution

Reverting to a previous version of Nest.

## Environment

<pre><code>
Nest version: 7.0.7

 
For Tooling issues:
- Node version: v12.7.0
- Platform:  Mac & Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
