### ISSUE TITLE
[Question] - Using NestJS in an enterprise-level application.

### ISSUE THREAD

**Issue by rbgfloripa** [nestjs/nest#4527]
Hi all,

I know that there are many companies using NestJs in production.
But... Any using in a corporate level application?

I'm not talking about websites, todo's, simple form applications and others.

I'm talking about a large application with >50 forms, generating PDF reports, connected to an Oracle DB and with an average of 100 simultaneous accesses.

Thanks.

Rafael

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/discover/companies
