### ISSUE TITLE
[CLI] Pre-build hook

### ISSUE THREAD

**Issue by truchi** [nestjs/nest#4529]
## Is your feature request related to a problem? Please describe.
Cannot hook pre-build with npm scripts when `nest [build|start] --watch ...`

## Describe the solution you'd like
`nest [build|start] --watch --before=./executable ...`
(+ API if you have this)
(+ nest-cli.json ?)

## Teachability, Documentation, Adoption, Migration Strategy
Incremental changes sent to the before script would be top notch (if you have that as well).
Infinite recursive build corner-cases could be expected to be handled properly (when before script messes with src/).

## What is the motivation / use case for changing the behavior?
From the CLI doc page:

>  [...] the nest command interacts with compilers and scripts to help DevOps personnel manage the development environment.

Currently, the only way to do this (did not try) would be to compile with webpack, which is cumbersome (and not documented). Or opting out of CLI for watching. 

My own specific use-case: code generation (in src/) with templating engine.
***
*Thank you*,
I am willing to help if not that time consuming. Just guide me into it.

**Comment by BrunnerLivio** [comment]
Have you tried with extending your start package.json script which runs [concurrently](https://www.npmjs.com/package/concurrently) with `nest start` + nodeman which runs your script?

**Comment by kamilmysliwiec** [comment]
Nest CLI simply runs `tsc` in the `watch` mode (incremental builds enabled). To run any post-build hooks in the watch mode, you can consider using nodemon (as @BrunnerLivio suggested) and point to the `dist` files (so react on updates to the output `.js` files).

**Comment by truchi** [comment]
I will end up doing the watching myself, I was suggesting the feature.

Thanks both of you anyway.
