### ISSUE TITLE
typeorm droping then adding the same column

### ISSUE THREAD

**Issue by kayisse** [nestjs/nest#4536]
## Bug Report

each time i start the server typeorm drop some columns and adding them back and it wont start untill i cleare all the table.

## Current behavior

query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'typeorm_metadata'
query: ALTER TABLE "user" DROP CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb"
query: ALTER TABLE "user" DROP COLUMN "username"
query: ALTER TABLE "user" DROP COLUMN "password"
query: ALTER TABLE "user" ADD "username" text NOT NULL
query failed: ALTER TABLE "user" ADD "username" text NOT NULL
error: error: la colonne « username » contient des valeurs NULL

## Input Code

```ts
const your = (code) => here;


import { Entity, Column, PrimaryGeneratedColumn, BeforeInsert } from 'typeorm';


@Entity('user')
export class UserEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text')
  firstName: string;

  @Column('text')
  lastName: string;

  @Column({
    type: 'text',
    unique: true,
  })
  username: string;

  @Column('text')
  password: string;
  
}
```
## Environment

Nest version: 7.1.2

 
For Tooling issues:
- Node version:  v12.16.1
- Platform:  Windows 
-Database: Postgres 12.2

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the typeorm repository.
