### ISSUE TITLE
Can't inject a provider into another provider

### ISSUE THREAD

**Issue by BeaRRRRR** [nestjs/nest#4537]
## Current behavior
I'm trying to create a simple REST API. I have a controller, service and a repository layer. My service and repository are both basically providers, annotated with `@Injectable()`
The logic behind this is the following, controller calls the service methods, and service calls repository methods

## Input Code

I don't think that the controller code is important, so I'll leave it out.

task.service.ts
```ts
import { Injectable } from '@nestjs/common';
import { TaskRepository } from './task.repository';

@Injectable()
export class TaskService {
    // @ts-ignore
    constructor(private taskRepository: TaskRepository) { }
}

```

task.repository.ts

```ts
import { Injectable } from '@nestjs/common';

@Injectable()
export class TaskRepository { }
```

task.module.ts
```ts
import { Module } from '@nestjs/common';
import { TaskController } from './task.controller';
import { TaskRepository } from './task.repository';
import { TaskService } from './task.service';

@Module({
    controllers: [TaskController],
    providers: [TaskService, TaskRepository],
})
export class TaskModule { }
```

When I try to run it fails with the message below
```bash
[Nest] 3006   - 04/07/2020, 1:06:52 PM 
[ExceptionHandler] Nest can't resolve dependencies of the TaskService (?).
Please make sure that the argument TaskRepository at index [0] is available in the TaskService context.
Potential solutions:
- If TaskRepository is a provider, is it part of the current TaskService?
- If TaskRepository is exported from a separate @Module, is that module imported within TaskService?
@Module({imports: [ /* the Module containing TaskRepository */ ]})
```

## Expected behavior
Nest should inject TaskRepository into TaskService's controller, but for some reason, it doesn't.

## Environment

<pre><code>
Nest version: 7.0.0
 
For Tooling issues:
- Node version: 13.10.1
- Platform: Manjaro Linux

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
