### ISSUE TITLE
Watchpack error

### ISSUE THREAD

**Issue by dimitrios1988** [nestjs/nest#4540]
When I type npm -g ls this comes up after my installed packages.

npm ERR! error in /home/dimitrios1988/.npm-global/lib/node_modules/@nestjs/cli/node_modules/watchpack/node_modules/fsevents: ENOENT: no such file or directory, open '/home/dimitrios1988/.npm-global/lib/node_modules/@nestjs/cli/node_modules/watchpack/node_modules/fsevents/package.json'

I have installed latest NestJs cli 7.1.2 with latest NodeJs 13.12.0 and I am using the latest Manjaro KDE. I have confirmed the same behavior on a freshly installed system too.

**Comment by kamilmysliwiec** [comment]
I think you can ignore this error. See similar issues
https://stackoverflow.com/questions/48384811/npm-enoent-no-such-file-or-directory-error-when-installing-sails-js-dependenc
https://stackoverflow.com/questions/49651221/npm-enoent-no-such-file-or-directory-rename/52718859
