### ISSUE TITLE
V8 crash when specifying log levels

### ISSUE THREAD

**Issue by helaili** [nestjs/nest#4551]
## Current behavior

Following [the doc](https://docs.nestjs.com/techniques/logger#using-the-logger-for-application-logging) in order to set the log level for my app.  

I'm getting this at startup time: 

```
nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node -r tsconfig-paths/register src/main.ts`
 1: 0x1000819ca node::Abort() [/usr/local/bin/node]
 2: 0x1000d4c1c node::CauseSegfault(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 3: 0x1001ef100 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 4: 0x1001ee6cb v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 5: 0x1001eddb0 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x100954059 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
 7: 0x1008e00fb Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
 8: 0x1008e00fb Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
 9: 0x1008da039 Builtins_ArgumentsAdaptorTrampoline [/usr/local/bin/node]
10: 0x1008e00fb Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[nodemon] app crashed - waiting for file changes before starting...
```

Seems like ` logger: ['error', 'warn']` is triggering this. It works fine when using ` logger: false`. 

## Input Code

```ts
import { NestFactory } from '@nestjs/core'
import { AppModule } from './app.module'

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    logger: ['error', 'warn']
  })
  
  await app.listen(process.env.PORT || process.env.API_PORT || 3000);
}
bootstrap();
```

## Environment

<pre><code>
Nest version: 5.1

 
For Tooling issues:
- Node version: v13.6.0 
- Platform:  Mac 

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction.

**Comment by helaili** [comment]
Here's [a repo](https://github.com/helaili/crash-test/) with the code. It's just a freshly bootstrapped project using `nest new <project>`  and the code modification in `main.ts` as seen in the original post.

**Comment by kamilmysliwiec** [comment]
It sounds like you're using an old version of Nest (v5 released 2 years ago). Please, update to the latest major release (v7)

**Comment by helaili** [comment]
Oooohhh, I had an old `nest` binary in `/usr/local/bin` so my update with npm wasn't used and I actually didn't double check the latest version number. Don't know how it ended up there. 

May I suggest to mention at least the current major version in the issue template? Not sure how often you run into such issues but that would have prevented me from creating an issue and unnecessary noise.

Anyway, thanks!
