### ISSUE TITLE
Dependency Maintenance - class-transformer and class-validator

### ISSUE THREAD

**Issue by dsbert** [nestjs/nest#4553]
Nestjs uses `class-transformer` and `class-validator` as a primary dependency. Both of these projects are maintained under the same organization - https://github.com/typestack. Despite the primary maintainers continuing to be active on github, these two projects have received little attention. 

`class-transformer` has a most recent commit of May 20, 2019. 
`class-validator` has a small commit on March 18, 2020 and prior to that it was May 6, 2019.

This is **not** intended as an attack on those projects maintainers. However, since nestjs depends so heavily on these libraries (they are referenced in many places in the docs), it may result in an appearance of poor maintenance within nestjs itself. 

Is there a long-term plan for these libraries from the standpoint of dependency maintenance?

**Comment by kamilmysliwiec** [comment]
> Nestjs uses class-transformer and class-validator as a primary dependency

Clarification: we leverage `class-transformer` for the `ClassSerializerInterceptor` and `ValidationPipe`. The `class-validator` is being used by the `ValidationPipe` and nothing else. Saying that those packages are "primary dependencies" is not true.

> class-transformer has a most recent commit of May 20, 2019. class-validator has a small commit on March 18, 2020 and prior to that it was May 6, 2019.

For the last 3-4 years (or more), all commits in the `express` repository are either deps updates or test additions. And still, express has ~13 millions downloads per week and is considered as the most popular and stable option for Node.js. The lack of commits does not always mean that the library has been abandoned. In many cases, this means that all fundamental requirements have already been met and work well. Both projects are open-source so if you are willing to invest your time and help to create new features, you can do that. Other than that, I haven't noticed any significant issue or important bug in these libraries for years
