### ISSUE TITLE
secret key for jwt

### ISSUE THREAD

**Issue by kajal098** [nestjs/nest#4555]
I am newbie in nest js. I want to use **jwt tokens**. can you please help for what to pass in '**secretkey**' ? **and how to generate it ? and from where to generate it ?**

```
export const jwtConstants = {
  secret: 'secretKey',
};
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
