### ISSUE TITLE
FileInterceptor and Body Issue

### ISSUE THREAD

**Issue by Ratatinator97** [nestjs/nest#4564]
Hello, I apologize if this post isn't at the right place. I didn't know if it's a bug or a documentation issue or another kind of problem.

I have done a stackoverflow [post](https://stackoverflow.com/questions/61148959/fileinterceptor-and-body-issue-in-nestjs-upload-a-file-and-data-in-a-request) where I explain the issue I'm struggling with.

**The main issue is** :  When using `FileInterceptor() in the same request as a Body(), Body() gives nothing, even if I sent data.

I read other issues:  #3470 #167 #428 and so on.

To do a file upload with additional data do I have to install swagger ? 

Sorry if this issue is redundant but I'm a bit lost here.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
