### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by EmilCataranciuc** [nestjs/nest#4566]
## Is your feature request related to a problem? Please describe.
The current logo is a bit unclear. For example, what does the lower, left part of the logo represent? Is it part of the cat's jaw? Is it fur?

## Describe the solution you'd like
It should be simplified to be more concise so that it conveys a clear message. That is Nest about, simplicity? Familiarity? Or maybe adherence to standards (at least to me this is the most important thing because it is predictable, it may be used in prod etc.).

## What is the motivation / use case for changing the behavior?
To consolidate the message.

**Comment by kamilmysliwiec** [comment]
There's no plan to change the logo.

+ it's a cat (as other photos on the official website may suggest)
