### ISSUE TITLE
how to get connect instance with typeorm oracle through nestjs DI

### ISSUE THREAD

**Issue by wowtrxqn** [nestjs/nest#4570]
my login table in aaaa schema, but my project config connectionStr is bbb schema ,now how can i write entity in schema aaaa, i check document  i can use connect.query('custom sql') for login table to login ,but how can i get connection from typeorm , i don want to createConnection  . i want to use anything that denpendency by nest js,all i wish to do is use Repository, but in mycase ,how to writing code like currentConnect schema when deal with login business?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
