### ISSUE TITLE
Add more comments of intentions of all classes in ./packages/**/* to let opensource developers understand more

### ISSUE THREAD

**Issue by ecpy** [nestjs/nest#4571]
## Is your feature request related to a problem? Please describe.
no docs in ./packages/**/*, currently I just use the debugger to step through the source code and understand the framework execution contexts by guessing the meaning of the class and func. names

## Describe the solution you'd like
ask the maintainers to add back some comments

## What is the motivation / use case for changing the behavior?
let opensource developers understand more and contribute more

**Comment by kamilmysliwiec** [comment]
This has been discussed many times in the past already. Please, search for old issues
