### ISSUE TITLE
How to become a contributor?

### ISSUE THREAD

**Issue by ecpy** [nestjs/nest#4572]
How to become a contributor?

**Comment by BrunnerLivio** [comment]
Read through our [Contributing Guideline](https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md) and you should be ready to submit your pull request(s)! 
Once your first pull request is merged, you will automatically be added to the [Github Contributors Graph](https://github.com/nestjs/nest/graphs/contributors).
