### ISSUE TITLE
Mocking data to test 07-sequelize sample

### ISSUE THREAD

**Issue by markau** [nestjs/nest#4574]
I have a working application based on the [07-sequelize sample](https://github.com/nestjs/nest/tree/master/sample/07-sequelize), but am confused with the [doco that outlines how to mock a model when testing](https://docs.nestjs.com/techniques/database#testing-1) . It talks about a mockModel object but does not provide a more detailed example.

Below is what I have got working. I expect the goal here is to mock the UsersService (repository) - to provide mock data instead of real data - to test controller and service functions without hitting the database.

The below does that, but I have an issue with it - `usersController.findOne` returns a `Promise<User>` but when mocked below this type is not constrained. I thought I might instantiate a User model object to provide a mock response (e.g. `return new User({ name: "Bob" })`), but in doing so I get error `Model not initialized: User cannot be instantiated. "User" needs to be added to a Sequelize instance.`

This question clearly falls into "support" but I wonder whether we could expand the docs a bit to explain what I am (inevitably) doing wrong here.

```
import { Test, TestingModule } from '@nestjs/testing';
import { UsersController } from './users.controller';
import { UsersService } from './users.service';
import { getModelToken } from '@nestjs/sequelize';
import { User } from './user.model';

const mockUserService = {
  findOne(id: string) {
    return "some value";
  }
};

describe('Users Controller', () => {
  let usersController: UsersController;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UsersService,
        {
          provide: getModelToken(User),
          useValue: mockUserService,
        }
      ],
      controllers: [UsersController],
    }).compile();

    usersController = module.get<UsersController>(UsersController);
  });

  it('usersController should be defined', () => {
    expect(usersController).toBeDefined();
  });

  describe('findOne', () => {
    it('should return User', async () => {
      const result = "some value";
      expect(await usersController.findOne('1')).toBe(result);
    });
  });

});

```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by bodva** [comment]
This part of the documentation really needs some improvements.

**Comment by EdByrnee** [comment]
> I have a working application based on the [07-sequelize sample](https://github.com/nestjs/nest/tree/master/sample/07-sequelize), but am confused with the [doco that outlines how to mock a model when testing](https://docs.nestjs.com/techniques/database#testing-1) . It talks about a mockModel object but does not provide a more detailed example.
> 
> Below is what I have got working. I expect the goal here is to mock the UsersService (repository) - to provide mock data instead of real data - to test controller and service functions without hitting the database.
> 
> The below does that, but I have an issue with it - `usersController.findOne` returns a `Promise<User>` but when mocked below this type is not constrained. I thought I might instantiate a User model object to provide a mock response (e.g. `return new User({ name: "Bob" })`), but in doing so I get error `Model not initialized: User cannot be instantiated. "User" needs to be added to a Sequelize instance.`
> 
> This question clearly falls into "support" but I wonder whether we could expand the docs a bit to explain what I am (inevitably) doing wrong here.
> 
> ```
> import { Test, TestingModule } from '@nestjs/testing';
> import { UsersController } from './users.controller';
> import { UsersService } from './users.service';
> import { getModelToken } from '@nestjs/sequelize';
> import { User } from './user.model';
> 
> const mockUserService = {
>   findOne(id: string) {
>     return "some value";
>   }
> };
> 
> describe('Users Controller', () => {
>   let usersController: UsersController;
> 
>   beforeEach(async () => {
>     const module: TestingModule = await Test.createTestingModule({
>       providers: [
>         UsersService,
>         {
>           provide: getModelToken(User),
>           useValue: mockUserService,
>         }
>       ],
>       controllers: [UsersController],
>     }).compile();
> 
>     usersController = module.get<UsersController>(UsersController);
>   });
> 
>   it('usersController should be defined', () => {
>     expect(usersController).toBeDefined();
>   });
> 
>   describe('findOne', () => {
>     it('should return User', async () => {
>       const result = "some value";
>       expect(await usersController.findOne('1')).toBe(result);
>     });
>   });
> 
> });
> ```

Could you please share you solution, I think we would all benefit from it :)

**Comment by jmcdo29** [comment]
I've created a [community managed repo](https://github.com/jmcdo29/testing-nestjs) that has simple test examples for most NestJS unit test cases. Feel free to check it out and contribute to it

**Comment by EdByrnee** [comment]
> I've created a [community managed repo](https://github.com/jmcdo29/testing-nestjs) that has simple test examples for most NestJS unit test cases. Feel free to check it out and contribute to it

You're repo is great, I already use it as a point of reference. But I can't find any examples of mocking the database responses and returning Sequelize Models. Your example only includes JSON mocked responses. 

Something similar to your Type-ORM example would be perfect.

**Comment by jmcdo29** [comment]
> You're repo is great, I already use it as a point of reference. But I can't find any examples of mocking the database responses and returning Sequelize Models. Your example only includes JSON mocked responses.

Classes are generally objects with some extra functionalties under the hood. That's why we can use JSON to represent a class response. If you really want, you can use `new Entity()` and then assign entity values instead of returning the JSON. Personally, I feel as that pattern is already shown, it doesn't explicitly need to be shown again, but if you want to make a PR over there you're welcome to.

**Comment by nicostubi** [comment]
Hello @jmcdo29 I can only second @EdByrnee, it would be useful to have an example pf mocking database responses and Sequelize Models.

I am stuck in a (probably) similar problem. I have declared my Model as the example in cats.service.ts: 

```
{
          provide: getModelToken(Cat),
          useValue: {
            findAll: jest.fn(() => [testCat]),
            findOne: jest.fn(),
            create: jest.fn(() => testCat),
            remove: jest.fn(),
          },
        },
```

only that instead of mocking these 4 functions, I am trying to mock .save().

However, I get an error:

TypeError: productCompositions[i].Composition.save is not a function.

**Comment by micalevisk** [comment]
@nicostubi you could make that request to https://github.com/jmcdo29/testing-nestjs
