### ISSUE TITLE
Property 'intercept' in type 'LoggingInterceptor' is not assignable to the same property in base type 'NestInterceptor<any, any>'.

### ISSUE THREAD

**Issue by kajal098** [nestjs/nest#4578]
![Screenshot from 2020-04-13 16-10-25](https://user-images.githubusercontent.com/21876329/79114600-4e97cf80-7da1-11ea-97b8-c6e15cacdfad.png)
## Current behavior
Property 'intercept' in type 'LoggingInterceptor' is not assignable to the same property in base type 'NestInterceptor<any, any>'.

## Input Code
`import {
  Injectable,
  NestInterceptor,
  ExecutionContext,
  Logger,
} from '@nestjs/common';
import { GqlExecutionContext } from '@nestjs/graphql';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';

@Injectable()
export class LoggingInterceptor implements NestInterceptor {
  intercept(
    context: ExecutionContext,
    call$: Observable<any>,
  ): Observable<any> {
    const now = Date.now();
    const req = context.switchToHttp().getRequest();
    if (req) {
      const method = req.method;
      const url = req.url;

      return call$.pipe(
        tap(() =>
          Logger.log(
            `${method} ${url} ${Date.now() - now}ms`,
            context.getClass().name,
          ),
        ),
      );
    } else {
      const ctx: any = GqlExecutionContext.create(context);
      const resolverName = ctx.constructorRef.name;
      const info = ctx.getInfo();

      return call$.pipe(
        tap(() =>
          Logger.log(
            `${info.parentType} "${info.fieldName}" ${Date.now() - now}ms`,
            resolverName,
          ),
        ),
      );
    }
  }
}`

atform:  

Others:

</code></pre>

node -v = 12.16.1
npm -v = 6.13.4
nest -v = 7.1.2

**Comment by kamilmysliwiec** [comment]
Please, make sure to use the latest version of all `@nestjs/...` packages (+ ensure their major versions match).

Next time use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
