### ISSUE TITLE
Injection scopes not working with UseGuards Passport implementation local strategy (or any strategy)

### ISSUE THREAD

**Issue by rainercedric23** [nestjs/nest#4581]
## Current behavior
I am implementing some request scope injection on our project where I should inject a request object onto a service or into the http module but it's not working correctly with Useguards as I've encountered this error on runtime: 

```
Error: Unknown authentication strategy "local"
    at attempt (/home/rcmariano/Projects/Codes/nest-fiddle/nestjs-simple-login/node_modules/passport/lib/middleware/authenticate.js:190:39)
    at authenticate (/home/rcmariano/Projects/Codes/nest-fiddle/nestjs-simple-login/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at /home/rcmariano/Projects/Codes/nest-fiddle/nestjs-simple-login/node_modules/@nestjs/passport/dist/auth.guard.js:84:3
    at new Promise (<anonymous>)
    at /home/rcmariano/Projects/Codes/nest-fiddle/nestjs-simple-login/node_modules/@nestjs/passport/dist/auth.guard.js:76:83
    at LocalAuthGuard.<anonymous> (/home/rcmariano/Projects/Codes/nest-fiddle/nestjs-simple-login/node_modules/@nestjs/passport/dist/auth.guard.js:48:36)
    at Generator.next (<anonymous>)
    at /home/rcmariano/Projects/Codes/nest-fiddle/nestjs-simple-login/node_modules/@nestjs/passport/dist/auth.guard.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/home/rcmariano/Projects/Codes/nest-fiddle/nestjs-simple-login/node_modules/@nestjs/passport/dist/auth.guard.js:16:12)
```

## Input Code
https://github.com/rainercedric23/nestjs-simple-login
not the actual repo but I replicated the error there
```ts
@Injectable({ scope: Scope.REQUEST })
export class UsersService {
  private readonly users: User[];

  constructor(@Inject(REQUEST) private readonly request: Request) {}
}
```

or this

```ts
        HttpModule.registerAsync({
            useFactory: request => {
                console.log(request.get('host'));
                let fromLocal = 0;
                if (request.headers.host.includes('localhost')) {
                    fromLocal = 1;
                }
                return { headers: { fromLocal } };
            },
            inject: [REQUEST],
        }),
```

## Expected behavior
Should get the request object just as the requests that doesn't have an authorization layer behind since it is working without guards or passport strategy

## Possible Solution
I really don't know what causes the issue

## Environment

<pre><code>
Nest version: latest 6.10

 
For Tooling issues:
- Node version: 12.14
- Platform:  Linux

Others:

</code></pre>

**Comment by johnbiundo** [comment]
@rainercedric23  This has been discussed in these issues.  Bottom line, request scoped providers are not compatible with Passport because Passport is "global".   There may be some hints on techniques you can use to work around this in these issues:
https://github.com/nestjs/passport/issues/95
https://github.com/nestjs/nest/issues/1870

**Comment by RayZoey** [comment]
> @ rainercedric23 在这些问题中已对此进行了讨论。底线是，请求范围的提供程序与Passport不兼容，因为Passport是“全局”的。在这些问题上，您可能会使用一些技巧来解决此问题：
> [nestjs / passport＃95 ](https://github.com/nestjs/passport/issues/95)
> [＃1870](https://github.com/nestjs/nest/issues/1870)
i have the same problem,and i use ` PassportModule.register({ defaultStrategy: 'jwt' }),` , its still invalid
