### ISSUE TITLE
Importing pre-compiled libraries Error

### ISSUE THREAD

**Issue by AviFix** [nestjs/nest#4582]
## Bug Report
cannot create the module instance when importing the pre-built library

## Current behavior
Get an error: Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.

## Example

I created a new NestJs application (nest new project-name). I then created a new Library (nest g library hello). I then build the library I created (nest build hello).

After all of that, I imported the built library into my main module.

```
import {Module} from '@nestjs/common';
import {AppController} from './app.controller';
import {AppService} from './app.service';
import {HelloModule} from '../libs/hello/hello-file.js';

@Module({
    imports: [HelloModule],
    controllers: [AppController],
    providers: [AppService],
})
export class AppModule {
}

```
I get the following error:

> Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.

If I import the ts module, everything works fine.

```
import {Module} from '@nestjs/common';
import {AppController} from './app.controller';
import {AppService} from './app.service';
import {HelloModule} from '../libs/hello/src/hello.module';

@Module({
    imports: [HelloModule],
    controllers: [AppController],
    providers: [AppService],
})
export class AppModule {
}
```
## Expected behavior
Pre-compiled module is loaded properly

## Environment

<pre><code>
Nest version: 6.7.2

 
For Tooling issues:
- Node version: v10.16.3
- Platform:  Mac

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Can you please provide a reproduction of this?

**Comment by BrunnerLivio** [comment]
The error message which you get displayed is most probably wrong. See #4586. Could you check what `HelloModule` prints?

```typescript
console.log(HelloModule)
```

In any case, please provide a reproduction of your problem.

**Comment by AviFix** [comment]
> Can you please provide a reproduction of this?

I did in the Example section

**Comment by BrunnerLivio** [comment]
@AviFix With that we mean a minimal reproduction repository so we can test your bug locally.
