### ISSUE TITLE
grpc-loader not able to load  well-knows-photos like google/protobuf/wrappers.proto

### ISSUE THREAD

**Issue by xmlking** [nestjs/nest#4584]
## Bug Report
`@grpc/proto-loader` was not able to load well-knows-photos like `google/protobuf/descriptor.proto` etc
this was working before. 

## Current behavior
```
(node:88142) Warning: google/protobuf/wrappers.proto not found in any of the include paths /Users/schintha/Developer/Work/SPA/yeti/dist/apps/api/proto
(node:88142) Warning: google/protobuf/descriptor.proto not found in any of the include paths /Users/schintha/Developer/Work/SPA/yeti/dist/apps/api/proto
(node:88142) Warning: google/protobuf/duration.proto not found in any of the include paths /Users/schintha/Developer/Work/SPA/yeti/dist/apps/api/proto
(node:88142) Warning: google/protobuf/timestamp.proto not found in any of the include paths /Users/schintha/Developer/Work/SPA/yeti/dist/apps/api/proto
(node:88142) Warning: google/protobuf/empty.proto not found in any of the include paths /Users/schintha/Developer/Work/SPA/yeti/dist/apps/api/proto
(node:88142) Warning: google/protobuf/wrappers.proto not found in any of the include paths /Users/schintha/Developer/Work/SPA/yeti/dist/apps/api/proto
```

## Input Code
git clone https://github.com/xmlking/yeti.git
cd yeti
```
ng serve api
```

## Expected behavior
 Should have no loading `Warnings`

## Environment

<pre><code>
Nest version: 7.1.2

 
For Tooling issues:
- Node version: v13.12.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by xmlking** [comment]
This was working in the previous `nestjs` release.  I guess some recent updates in `proto-loader`, `grpc` npm packages may be causing this issue.  I suspect it is a regression issue.

**Comment by daniel-vera-g** [comment]
> This was working in the previous `nestjs` release. I guess some recent updates in `proto-loader`, `grpc` npm packages may be causing this issue. I suspect it is a regression issue.

Hey @xmlking, were you able to fix this and load the well-knows types?  

- `proto-loader` uses the latest Protobuf.js package, so I think this is the blocking issue: https://github.com/protobufjs/protobuf.js/issues/1042

My current workaround is to have the needed types locally, so the `proto-loader` finds them.
