### ISSUE TITLE
Improve error message when imported module is nil

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#4586]
## Current behavior
Currently, when the module imports a clearly undefined module, it will throw the `InvalidModuleException` and reminding the user to use forwardRef. Though this is incorrect (false positive)!

## Input Code

Will throw `InvalidModuleException`.

```ts
@Module({
  imports: [undefined],
})
export class CatsModule {}
```

## Expected behavior
It should tell the user that the given module is not defined

## Possible Solution
1. Improve typing
2. Add appropriate error message

## Environment

<pre><code>
Nest version: 7.0.2

 </pre></code>

## Other

You may ask yourself, why would anyone import an `undefined` or `null`? Off course, in most cases, it is not as obvious - for example when the import path of a module is dynamically imported using `optional(path: string)` and it returns `null`. Or another case in #4582

**Comment by BrunnerLivio** [comment]
Related issues #4582

**Comment by kamilmysliwiec** [comment]
> Currently, when the module imports a clearly undefined module, it will throw the InvalidModuleException and reminding the user to use forwardRef. Though this is incorrect (false positive)!

In the case of circular dependency, the module class will be represented as `undefined` as well.

Example:

```typescript
@Module({
   imports: [AModule],
})
class BModule {} 

@Module({
   imports: [BModule], // BModule === undefined
})
class AModule {} 
```

How do we cover this scenario here?

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec Good catch -- this makes it way harder to detect :(

Seems like Angular simply checks it using [circular-dependency-plugin](https://github.com/aackerman/circular-dependency-plugin) for webpack in the Angular CLI. See [here](https://github.com/angular/angular-cli/commit/1f3738b19f8e4710ef39c9046f70a5fd9b5d9284). The error message in the browser logs is just `ReferenceError: Cannot access 'BModule' before initialization`. 

That is how they are able to give comprehensive guidance on both of these cases. It seems like the only solution for us would be to go in a similar direction. An intermediate solution would be, to simply expand the `InvalidModuleException` error message with "this error has been thrown because either your module is `undefined` or you have a circular dependency without forwardRef".

**Comment by kamilmysliwiec** [comment]
> That is how they are able to give comprehensive guidance on both of these cases. It seems like the only solution for us would be to go in a similar direction

Nest CLI is optional while webpack mode is opt-in. Unfortunately, we can't really mimic Angular behavior.

> An intermediate solution would be, to simply expand the InvalidModuleException error message with "this error has been thrown because either your module is undefined or you have a circular dependency without forwardRef".

Sounds good. I think that adding this:

```
... This is because the module at index [x] ...
```

will already help a lot! In addition, we can differentiate `null` and `undefined` values. `null` value = developer issue (e.g., `return null` from a static method). Circular deps are always represented as `undefined` (never `null`), so we can show slightly different messages based on that. :)
