### ISSUE TITLE
Monorepo mode integration lerna.js

### ISSUE THREAD

**Issue by lichnow** [nestjs/nest#4593]
## Is your feature request related to a problem? Please describe.
In monorepo mode, when you add `package.json` to a lib and then start app that depends on this lib (run through webpack),  it will throw error 'MODULE_NOT_FOUND' . How to solve this problem?thx
error code
```
code: 'MODULE_NOT_FOUND',
path: '/Users/sfcc/Code/mono-test/node_modules/@app/core/package.json',
requestPath: '@app/core'

```

## Describe the solution you'd like
The monorepo mode can integration lerna.js + yarn workspaces

## What is the motivation / use case for changing the behavior?
If monorepo mode can integration lerna.js ,then lib can published independent to be a npm package, and also can isomorphic with the front end like react or next.js

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by BrunnerLivio** [comment]
@lichnow  FYI, I created [this starter project](https://github.com/brunnerlivio/nestjs-monorepo-starter) some time ago which does exactly what you are asking for. Though it is not updated for v7 and some nest cli updates.  Feel free to contribute!
