### ISSUE TITLE
exception could contains some context information for error like promise reject without any params

### ISSUE THREAD

**Issue by luokuning** [nestjs/nest#4601]
## Is your feature request related to a problem? Please describe.
I'm implementing a custom global exception filter that [Catch everything](https://docs.nestjs.com/exception-filters#catch-everything). And in a route handler I reject a promise intentionally, **without a param**:

```javascript
@Controller()
export class AppController {
  @Get()
  getHello() {
    Promise.reject()
  }
}
```

Then I made a request to this endpoint triggered the rejection, and the custom exception filter did catch the error. However, the value of `exception` passed to `catch` method is `undefined`:
```javascript
@Catch()
export class AllExceptionFilter implements ExceptionFilter {
  constructor(private logger: LoggerService) {}

  // exception is undefined
  catch(exception: unknown, host: ArgumentsHost): any {
    const ctx = host.switchToHttp()
    const response = ctx.getResponse<Response>()
    const request = ctx.getRequest<Request>()

    const status = exception instanceof HttpException ?
      exception.getStatus() :
      HttpStatus.INTERNAL_SERVER_ERROR

    this.logger.error({
      statusCode: status,
      error: exception, // exception is undefined
      path: request.url,
    })

    response.status(status).json({
      statusCode: status,
      timestamp: new Date().toLocaleString('en-US', { timeZone: 'Asia/Shanghai' }),
      message: 'Internal server error',
    })
  }
}
```
therefore I can't capture any useful information about the rejection in the log.

## Describe the solution you'd like
Maybe we could attach some context information about the rejection in this case (promise reject without any params).

**Comment by kamilmysliwiec** [comment]
This is not related to NestJS specifically. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
