### ISSUE TITLE
How to use seed data like laravel ?

### ISSUE THREAD

**Issue by imagine10255** [nestjs/nest#4605]
Hi, How to use seed data like laravel in nestjs?

ref:
https://laravel.tw/docs/5.2/seeding

ex:
php artisan db:seed --class=UserTableSeeder
in nestjs

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
