### ISSUE TITLE
Head Route is not working

### ISSUE THREAD

**Issue by dannyheard7** [nestjs/nest#4609]
## Current behavior

I have a @Head() Route as shown in the code example. However when i try to make a HEAD request to the /appointments endpoint, nothing is logged to the console.

## Input Code

```ts
import { Controller,  Head } from "@nestjs/common";
import { ApiResponse } from '@nestjs/swagger';

@Controller("appointments")
export class AppointmentsController {
    @Head('')
    @ApiResponse({
        type: Boolean
    })
    head(): boolean {
        console.log("hello")
        return true;
    }
}
```

## Expected behavior

Hello is logged to the console

## Environment

Nest version: 7.0.8
 
For Tooling issues:
- Node version: 12.16.2
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
