### ISSUE TITLE
 PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by ganshiqingyuan** [nestjs/nest#4615]
## Current behavior

request failed with @Body decorator
## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by ganshiqingyuan** [comment]
> Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

didn`t you sleep now ?
