### ISSUE TITLE
Third party modules

### ISSUE THREAD

**Issue by fwoelffel** [nestjs/nest#462]
Hi there

As said by @kamilmysliwiec here https://github.com/nestjs/nest/issues/404#issuecomment-369397149 Nest allows us to build all the modules we need. Those modules may not be needed everywhere and should be picked according to our needs and this why we can't add them to the core.
With Nest growing community, more and more modules are going to be created and it would be really great to have a place to share those.

I'm thinking of something like an "awesome list" where we could reference our modules. Is that a good idea? Where should we host these references?

IMO, something "official" (i.e. a `nestjs/third-party` repo) could be the way to go because it would avoid the dissemination of information/documentation/references.

**Comment by kamilmysliwiec** [comment]
I saw something like this so far https://github.com/juliandavidmr/awesome-nest. About NPM, I'd recommend publishing modules with `nestjsx-` or just `nestjs-` prefix.

**Comment by shekohex** [comment]
what about making a standard for the 3rd party Modules first

naming: nest-[name]
structure: lib, src, testing .. etc
and so on.

This Important since as starting of v5 Nest will be Boom boom 🔥🎆.

see some of what will be included [Nest Project](https://github.com/nestjs/nest/projects/1)
and about the ` awesome-list`, I think there is a one.
but as you mentioned , we should have a place to list them.

**Comment by fwoelffel** [comment]
About the module naming, I think we should stick to `nestjs-*` because it is close to the naming of the official modules (`@nestjs/swagger`, `@nestjs/graphql`, ...)

**Comment by kamilmysliwiec** [comment]
@fwoelffel `nestjs-` sounds reasonable 🙂

**Comment by zMotivat0r** [comment]
@kamilmysliwiec as I said you a couple of months ago, I've created `@nextjsx` organization in NPM and have added `nestjscore` with owner privileges. So you're free to use it if you wish :)

**Comment by kamilmysliwiec** [comment]
@zMotivat0r I figured out that in this case, I'd have to manually manage this organization which is a little bit inflexible. Let's stay with `nestjs-` prefix and `@nestjs/` scope for official packages.
