### ISSUE TITLE
PartialType and OmitType

### ISSUE THREAD

**Issue by jhonaikerf** [nestjs/nest#4627]
## Current behavior
@nestjs/graphql has no exported member PartialType
@nestjs/graphql has no exported member OmitType

## Input Code
`import { InputType, PartialType, OmitType } from '@nestjs/graphql';
import { PartialType } from '@nestjs/common'
import { CreateUserInput } from './create-user.input';

@InputType()
export class UpdateUserInput extends PartialType(
  OmitType(CreateUserInput, ['username','password']),
) {}`

## Environment
Nest: 7.1.2
Nnestjs/graphql: 7.0.13,

For Tooling issues:
- Node version: v13.5.0
- Platform:  Windows

**Comment by kamilmysliwiec** [comment]
Please, update the `@nestjs/graphql` to the latest version
