### ISSUE TITLE
Route endpoints not working as expected

### ISSUE THREAD

**Issue by mm-spiio** [nestjs/nest#4628]
## Current behavior
I have a controller called transactionsController with a few endpoints where the first GET method is "empty" `@Get('')` which returns all transactions for a given user when calling localhost:xxxx/api/transactions. 

## Input Code
```ts
import { Controller, Get, Post, Put, Delete, Request, Res, Param, Body } from '@nestjs/common';
import { TransactionService } from '../services';
import { TransactionDto } from '@models/dto/db';

@Controller('transactions')
export class TransactionController {
    @Get('')
    async findAll() {
        return this.transactionService.findAll();
    }

    @Get(':id')
    async findOneById(@Param('id') id: string): Promise<TransactionDto> {
        return this.transactionService.findOneById(id);
    }

    @Get('bymonth')
    async byMonth() {
        console.log('here');
        return this.transactionService.findAll();
    }

    @Get('groupby/month')
    async groupByMonth() {
        console.log('here');
        return this.transactionService.findAll();
    }

    @Post()
    async create(@Body() statement: TransactionDto): Promise<TransactionDto> {
        return this.transactionService.create(statement);
    }

    @Put(':id')
    async update(@Param('id') id: string, @Body() statement: TransactionDto) {
        return this.transactionService.update(id, statement);
    }

    @Delete(':id')
    async delete(@Param('id') id: string) {
        return this.transactionService.delete(id);
    }

    constructor(private transactionService: TransactionService) {

    }
}
```

## Expected behavior
Adding a new endpoint `@Get('byMonth')` I would expect to return the appropriate result when calling localhost:xxx/api/transactions/bymonth. But it doesn't. It returns and empty object and doesn't hit the expected method. However, if I do something like `@Get('groupby/month')` then it works perfectly. Am i missing something here? 

Also if I have both  @Get('bymonth') and  @Get('groupby/month') then I get an internal server error if I try to hit http://localhost:xxxx/api/transactions/groupby/month which otherwise works perfectly without @Get('bymonth')

## Environment

Nest version: 7.0.8
 
For Tooling issues:
- Node version: 13.2.0 
- Platform:  OSX 10.15.4

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by mm-spiio** [comment]
> Please provide a minimum reproduction repository.

Hey! I actually found out! If I have a route with empty decorator, then it needs to be the last (in cardinal order) in the code. Not sure why that would be or why I didn't see it in the docs, but it does work!

So, this works

```ts
@Get('bymonth')
    async byMonth() {
        return this.transactionService.groupedByMonth();
    }

    @Get(':id')
    async findOneById(@Param('id') id: string): Promise<TransactionDto> {
        return this.transactionService.findOneById(id);
    }

    @Get()
    async findAll() {
        return this.transactionService.findAll();
    }
```

this does not:

```ts

 @Get()
    async findAll() {
        return this.transactionService.findAll();
    }

@Get('bymonth')
    async byMonth() {
        return this.transactionService.groupedByMonth();
    }

    @Get(':id')
    async findOneById(@Param('id') id: string): Promise<TransactionDto> {
        return this.transactionService.findOneById(id);
    }
```

**Comment by madhan4r** [comment]
Hello @mm-spiio,

I know this is closed. I wanted to share an observation I made that might be of interest to you, given your previous experience. It appears that in the code snippet you provided, when calling the "bymonth" endpoint, the system interprets "bymonth" as a parameter for the ":id" endpoint. As a result, the "findOneById" endpoint is triggered unintentionally.

However, when you call the "groupby/month" endpoint, the system handles it correctly and the operation works as expected. This distinction seems to be due to the addition of a new tag in the endpoint name, which prevents any ambiguity.

It's important to be mindful of such interactions when defining endpoints to ensure that the routing is clear and unambiguous.

**Comment by neolinoux** [comment]
> Hello @mm-spiio,
> 
> I know this is closed. I wanted to share an observation I made that might be of interest to you, given your previous experience. It appears that in the code snippet you provided, when calling the "bymonth" endpoint, the system interprets "bymonth" as a parameter for the ":id" endpoint. As a result, the "findOneById" endpoint is triggered unintentionally.
> 
> However, when you call the "groupby/month" endpoint, the system handles it correctly and the operation works as expected. This distinction seems to be due to the addition of a new tag in the endpoint name, which prevents any ambiguity.
> 
> It's important to be mindful of such interactions when defining endpoints to ensure that the routing is clear and unambiguous.

i've been debungging for 12 hours, checking every guard and strategis and still got nothing, but this... this HELPS ME A LOT

thank you

**Comment by antonioscript** [comment]
I also have exactly the same problem. If I do it this way it doesn't work:

```typescript
  @Get()
  async findAll() {
    return this.queryBus.execute(new GetAllVehicleTypesQuery());
  }

  @Get(':id')
  async findOne(@Param('id') id: number) {
    const numberId = Number(id);
    return this.queryBus.execute(new GetOneVehicleTypeQuery(numberId));
  }

  @Get('paginated')
  async findPaginated(@Query('page') page?: number, @Query('pageSize') pageSize?: number) {
    return await this.queryBus.execute(new GetPagedVehicleTypesQuery(Number(page), Number(pageSize)));
  }
```

There are two solutions in this case, as @mm-spiio commented, you should put those with a decorator first, then those with a parameter and finally those with an empty route, like this: 

```typescript

  @Get('paginated') //1º
  async findPaginated(@Query('page') page?: number, @Query('pageSize') pageSize?: number) {
    return await this.queryBus.execute(new GetPagedVehicleTypesQuery(Number(page), Number(pageSize)));
  }

  @Get(':id') //2º
  async findOne(@Param('id') id: number) {
    const numberId = Number(id);
    return this.queryBus.execute(new GetOneVehicleTypeQuery(numberId));
  }

  @Get() //3º
  async findAll() {
    return this.queryBus.execute(new GetAllVehicleTypesQuery());
  }
```

Or put something in front of the decorator, like this: 
```typescript

  @Get('something/paginated') //that's how it works
  async findPaginated(@Query('page') page?: number, @Query('pageSize') pageSize?: number) {
    return await this.queryBus.execute(new GetPagedVehicleTypesQuery(Number(page), Number(pageSize)));
  }

```

**Comment by phat-dang** [comment]
I got that problem and spent more than 30 minutes too crazy. And then, turned off laptop until the next morning when my mind was fresh, and yeah found that on the document:

https://docs.nestjs.com/controllers
> Routes with parameters should be declared after any static paths. This prevents the parameterized paths from intercepting traffic destined for the static paths.

<img width="1295" alt="SCR-20240908-gjhz" src="https://github.com/user-attachments/assets/554c66de-f334-4ad8-9c99-b490c6e1cc30">


_Nest team should be notice that instead of hint_ 

```javascript
✅ Do - declared param after static path

@Controller('cats')
export class CatsController {

    //GET /cats/breed -> OK 200
    @Get('breed')
    findOneBeforeFindOne(@Param('id') id: string): string {
      return `This action returns a #${id} cat`;
    }
    
    //GET /cats/1 -> OK 200
    @Get(':id')
    findOne(@Param('id') id: string): string {
      return `This action returns a #${id} cat`;
    }
}

```

```javascript
❌ Do not - will lead to not found error

@Controller('cats')
export class CatsController {

    //GET /cats/1 -> OK 200
    @Get(':id')
    findOne(@Param('id') id: string): string {
      return `This action returns a #${id} cat`;
    }

    //GET /cats/breed -> 404 NOT FOUND
    @Get('breed')
    findOneBeforeFindOne(@Param('id') id: string): string {
      return `This action returns a #${id} cat`;
    }
    
}
```

**Comment by antonioscript** [comment]
I'm glad you were able to resolve it and find that in the reference. Even though this is now in the documentation, people like me and many others who came from other frameworks and languages tend to get used to how controllers work in the REST pattern and end up doing it automatically. So, I believe that Nest should somehow address this to prevent people from struggling unnecessarily. But I'm happy you found that.
