### ISSUE TITLE
Support REQUEST scope for standalone applications

### ISSUE THREAD

**Issue by umbertoo** [nestjs/nest#4630]
## Is your feature request related to a problem? Please describe.
I can't use request scope for standalone application

## Describe the solution you'd like
Some new method on standalone application which will allow to do "requests". and so the app would be cappable to track of them.

## What is the motivation / use case for changing the behavior?
I'm making a highly encapsulated module with an interface. Client should not know what's inside. I expose the interface something like that 
```js
    const app = await NestFactory.createApplicationContext(MyModule);
    this.executor = await app.get(ModuleController);
```
The module has to create a new db transaction on each method invocation of the inteface.
Request scope for standalone application can allow to create a request scoped transaction provider which will provide new transaction for each request.

overall module structure looks like this
![module](https://i.ibb.co/YQSymmQ/com-mycompahy-myapp-web.png)

I'm relatively new to nest. Maybe I don't understant something and there is a solution to that problem already.

**Comment by kamilmysliwiec** [comment]
Use `app.resolve()` instead https://docs.nestjs.com/fundamentals/module-ref

**Comment by cjancsar** [comment]
@kamilmysliwiec can you override the request object? Most of the time if something is request scoped it needs access to the underlying request object.

**Comment by cxstomer-dev** [comment]
I was able to do this, by creating a dynamic module to accept a scope. If scope is null or default, I create a different version of the service to avoid using the service that is request scoped. If scope is supplied I set that on the service in the module, not in the service file @Injectable(). Here's the module:
```ts
export type SupabaseOptions = {
  scope: Scope;
};

@Global()
@Module({})
export class SupabaseModule {
  /**
   * Registers the SupabaseModule with service role privs if scope is null/DEFAULT. Use with caution.
   * @param options if scope is null or DEFAULT the supabase service registers with service role privs.
   * @returns
   */
  static register(options?: SupabaseOptions): DynamicModule {
    const { scope } = options || {};

    const providers: Provider[] = [SupabaseStrategy, SupabaseGuard];

    if (scope == null || scope === Scope.DEFAULT) {
      const supabaseServerClient = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, {
        auth: {
          autoRefreshToken: false,
          persistSession: false,
        },
      });

      // Register the service role key for admin privs over Supabase.
      providers.push({
        provide: SupabaseService,
        useValue: supabaseServerClient,
      });
    } else {
      providers.push({
        provide: SupabaseService,
        useClass: SupabaseService,
        scope: scope,
      });
    }

    return {
      module: SupabaseModule,
      imports: [ConfigModule],
      providers,
      exports: [SupabaseService, SupabaseStrategy, SupabaseGuard],
    };
  }
}
```

Then in my standalone app module:
```ts

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: [`.env.${process.env.npm_config_stage || process.env.APP_STAGE || "local"}`, ".env"],
      expandVariables: true,
      isGlobal: true,
    }),
    // Register supabase with service role auth as users do not enter this part of the app.
    SupabaseModule.register(),
  ],
  providers: [PubService, SubService],
  exports: [PubService, SubService],
})
export class PubsubModule {}
```
