### ISSUE TITLE
Source maps aren't outputted for monorepo app buils

### ISSUE THREAD

**Issue by thebigredgeek** [nestjs/nest#4644]
## Current behavior
1. Install latest version of nest cli
2. Create a new project
3. Run `nest generate app api` (or whatever name you want to give it)
4. Run `nest build app`
5. Look at dist and see that source maps are missing despite them being configured in the tsconfig files.  Have tried a bunch of different things to get this to work, to no avail.

## Expected behavior
There should be a source map present for app build output.  Otherwise, it's impossible to get clean stack traces in production error reporting.

## Environment

<pre><code>
CLI version: 7.1.2
Lib versions: >7.0.0 according to package.json generated in scaffolding by the CLI version above.

 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Elementary OS (linux)

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
> Look at dist and see that source maps are missing despite them being configured in the tsconfig files. Have tried a bunch of different things to get this to work, to no avail.

Monorepo mode is using the `webpack` compiler which has source maps disabled by default.

Follow this guide: https://www.npmjs.com/package/ts-loader#devtool--sourcemaps
Docs on how to provide your own webpack config: https://docs.nestjs.com/cli/monorepo#webpack-options

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
