### ISSUE TITLE
nestswagger can't find module when using webpack

### ISSUE THREAD

**Issue by jakobwgnr** [nestjs/nest#4657]
## Current behavior
I have setup a nest project with swagger & webpack (for hot reload) all from the recipes and implemented the first module.
Unfortunately the code doesn't compile due to a module not found issue i suppose comes from the nestswagger functionality..

## Input Code

```ts
import { Controller, Get } from '@nestjs/common';
import { PatientService } from './patient.service';
import { ApiResponse } from '@nestjs/swagger';
import { PatientDTO } from './patient.dto';

@Controller('patients')
export class PatientController {
    constructor(private service: PatientService) {}

    @Get()
    @ApiResponse({
        description: 'An array of all Patients',
        type: PatientDTO,
    })
    public async getAll(): Promise<PatientDTO[]> {
        return await this.service.getAll();
    }
}
```

## Expected behavior
code should compile

## Possible Solution
What is wierd is that the ApiResponse seems like to be resolved twice, when looking in the compiled and in one case (i expect from the decorator) it finds the module
main.js
```js
    swagger_1.ApiResponse({
        description: 'An array of all Patients',
        type: patient_dto_1.PatientDTO,
    }),
    openapi.ApiResponse({ status: 200, type: [__webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module '../C:\\Projekte\\carenamics-backend\\src\\patient\\patient.dto'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())).PatientDTO] }),

```

## Environment

<pre><code>
Nest version: 7.1.2

 
For Tooling issues:
- Node version: XX  v10.15.1
- Platform:  Windows

Others:
n/a

Thanks in advance for your help

**Comment by jakobwgnr** [comment]
Hello!
I'm closing this issue as I found a solution to this.
https://stackoverflow.com/questions/56870498/nest-cant-resolve-dependencies-of-the-itemsservice-please-make-sure-that-t

The problem was that i was twice importing the Controller&Service in the app.module through the patient.module.
Nevertheless the errormessage thrown was very confusing for me.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by jakobwgnr** [comment]
a complete clean of the project resolved that issue now... sorry for inconvenience
