### ISSUE TITLE
Code does not work in Mac. Works flawlessly in Linux, CodeSandbox without any changes

### ISSUE THREAD

**Issue by Suedo** [nestjs/nest#4658]
## Current behavior
My app is a simple Todo kinda app. I can create Tasks, and then I want to filter tasks based on search criteria. 

For the search/filter stuff, I have a service, whose method gets called from the controller. When running in debug mode, the code works as expected, printing console.logs and outputs the expected filtered result, But when running the same code in normal non-debug mode, it does not print the console.log-s, nor does it return proper filtered data.

I tested the same code in codesandbox, as well as a LinuxMint 18 machine.. **It works perfectly in codesandbox, as well as Linux**, printing all the console.logs and giving the expected results as well.

Only issue is when running in normal mode in Mac. I am using Catalina 10.15.2

I dunno if this is a bug, or a problem with my own machine. Submitting here as it seems the best place to ask.

## Input Code
https://github.com/Suedo/NestJS/tree/UdemyNestJSHero

```ts
@Injectable()
export class TasksService {
  private _tasks: Task[] = [];
  
  .
  .

  getFilteredTasks(filter: FilterTaskDto): Task[] {
    console.log('in getFilteredTasks'); // does not print in my Mac's normal `yarn start:dev` mode
    const { status = '', search = '' } = filter;
    console.log(`${status}, ${search}`); // does not print either
    
    // in normal `yarn start:dev` this filter returns empty array even with valid search fields
    // but this issue does not happen when running in codeSandbox. Proper filtered array is obtained
    const filteredTasks = this._tasks.filter(
      task => task.title.includes(search) || task.description.includes(search),
    );

    if (status.length > 0) {
      return filteredTasks.filter((task: Task) => task.status === status);
    }

    console.log(filteredTasks); // does not print either

    return filteredTasks;
  }
  .
  .

```

## Expected behavior
Steps to recreate my issue:
1. Create a few tasks by adding them using the create task endpoint
![image](https://user-images.githubusercontent.com/4963779/80031494-612fa880-8507-11ea-8a4a-247059e56b20.png)

2. view all added tasks using the 'GET' /tasks endpoint:
![image](https://user-images.githubusercontent.com/4963779/80031809-dbf8c380-8507-11ea-9288-a30d2a81835b.png)

3. Newly created tasks have OPEN status by default. Try searching for some task by giving 'search' query param
![image](https://user-images.githubusercontent.com/4963779/80031696-aeac1580-8507-11ea-855a-bf65b632c5f0.png)

In my local, in step 3, even though i give proper value for search, it doesnt show any results, neither does it show log statements printed in the console. But if I run the same in Codesandbox, it works as expected, shows logs, as well as returns the filtered output

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: v12.16.1  
- Platform:  Mac OSX 10.15.2 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
