### ISSUE TITLE
Can't resolve factory provider  if it has request scoped service injected.

### ISSUE THREAD

**Issue by umbertoo** [nestjs/nest#4662]
## Current behavior

Can't resolve factory provider from applicationContext if it has request scoped service injected.
Response:
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of null`

## Input Code

Repo link: https://github.com/umbertoo/check-resolve-use-factory-provider

app.module.ts
```ts
@Module({
  imports: [],
  providers: [
    RequestScopedService,
    {
      provide: FactoryProvidedService,
      useFactory: (service) => new FactoryProvidedService(service),
      inject: [RequestScopedService],
    },
  ],
})
export class AppModule {}
```
main.ts
```ts
async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);

  const service = await app.resolve(FactoryProvidedService);
}
bootstrap();
```
// UPDATE: also can't resolve request scoped FactoryProvidedService even without dependecies. Error is the same `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of null`
```ts
...
 {
      provide: FactoryProvidedService,
      useFactory: () => new FactoryProvidedService(),
      scope: Scope.REQUEST,
    },
```

## Expected behavior
Expect a factory provider to be resolved as an unique instance of the provider from its own DI container sub-tree on each resolve method invocation.

## Possible Solution
Currently I've found a couple of workarounds
1. **ModuleRef** // UPDATE: That variant does not work. Actually it does resolve but it returns the same instance though .
```ts
@Module({
  imports: [],
  providers: [
    RequestScopedService,
    {
      provide: FactoryProvidedService,
      useFactory: async (moduleRef) =>
            new FactoryProvidedService(await moduleRef.resolve(RequestScopedService)),
      inject: [ModuleRef],
    },
  ],
})
export class AppModule {}
```
2. **Inject FactoryProvidedService in some provider, and then resolve that provider**
```ts
  const app = await NestFactory.createApplicationContext(AppModule);

  const service = await app.resolve(ServiceWithInjectedFactoryProvidedService);

```
## Environment
<pre><code>
Nest version: 7.0.8

 
For Tooling issues:
- Node version: v13.13.0  
- Platform:   Mac, Linux

**Comment by kamilmysliwiec** [comment]
Fixed in 7.0.9. Thanks for reporting!
