### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by shvelo** [nestjs/nest#4668]
## Is your feature request related to a problem? Please describe.
I find the documentation very weird because it mentions decorators / classes / interfaces etc by name and doesn't link to their documentation. The only way to see proper documentation is to see the source comments from the code editor.

## Describe the solution you'd like
There should be an API documentation, even if it's auto-generated, preferably versioned, like other projects have, and the regular documentation should link to it when mentioning individual components.

## Teachability, Documentation, Adoption, Migration Strategy
For example, in this documentation segment, the `@Controller()` should be a link to API documentation page for this decorator.

![image](https://user-images.githubusercontent.com/1080798/80201341-0b591e80-8635-11ea-8f9d-ffb45963892f.png)

## What is the motivation / use case for changing the behavior?
This will massively improve the documentation and learning experience.

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/docs.nestjs.com/pull/413
