### ISSUE TITLE
Transpile existing project to pure javascript.

### ISSUE THREAD

**Issue by panaceadev** [nestjs/nest#4671]
## Is your feature request related to a problem? Please describe.
We started to build backend using nestjs and client eventually requested to use pure javascript instead of using typescript. 

## Describe the solution you'd like
I think it is not mandatory, but it would be cool if there is any cli command to transpile current project into pure javascript project.

**Comment by kamilmysliwiec** [comment]
We don't plan to add such a feature.

**Comment by panaceadev** [comment]
Thank you for your reply. I understand it. But may I ask you if there is any workaround to do this? 
I'm transpiling using tsc and then use babel like the javascript-starter project, but couldn't make it yet.

**Comment by jmcdo29** [comment]
@panaceadev once you transpile the code using `tsc` (or `nest build`), the JavaScript is runnable as is. It may be a bit more complex to look at, due to the transpilation process, but it is there.
