### ISSUE TITLE
Global filter or interceptor get dependency as undefined

### ISSUE THREAD

**Issue by zjy01** [nestjs/nest#4676]
## Bug Report
Global filter or interceptor get dependency as undefined

## Current behavior
When I use `Exception filters` as [exception-filters#binding-filters](https://docs.nestjs.com/exception-filters#binding-filters) say，register a global-scoped filter in `providers`。I get a wrong message:
```log
(node:37173) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reportOppProcess' of undefined
```

## Input Code
```ts
// app.module.ts
@Module({
  imports: [
    MonitorModule,
  ],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_FILTER,
      useClass: HttpExceptionFilter,
    },
  ],
})
export class AppModule {}
```

```ts
// http-exception.filter.ts
import { ExceptionFilter, Catch, ArgumentsHost, HttpException } from '@nestjs/common';
import { Request, Response } from 'express';
import { MonitorService } from '../monitor/monitor.service';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  constructor(private monitor: MonitorService) {}
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const request = ctx.getResponse<Request>();
    const response = ctx.getResponse<Response>();
    const status = exception.getStatus();

    response.status(status).json({
      statusCode: status,
      code: 0,
      msg: exception.message,
    });
    this.report(request, response, 0);
  }

  async report(req: Request, res: Response, duration: number): Promise<void> {
    const reportInfo = {
      apiName: req.url,
      operation: req.method,
      code: '0',
      status: res.statusCode,
      success: res.statusCode >= 500 ? 1 : 0,
      duration,
      addition: '',
    };
    this.monitor.reportOppProcess(reportInfo);
  }
}
```

## Expected behavior
I think `monitor` should be injected, but `this.monitor` is undefined when running。

## Environment

<pre><code>
Nest version: 7.0.8

 
For Tooling issues:
- Node version: 12.14.1  
- Platform: Mac  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction. 

If you are using any REQUEST scoped providers in your enhancers, they will not be resolved properly. This can lead to the injected value being undefined.

**Comment by kamilmysliwiec** [comment]
> If you are using any REQUEST scoped providers in your enhancers, they will not be resolved properly. This can lead to the injected value being undefined.

This can be fixed with changing this:

```
{
   provide: APP_FILTER,
   useClass: HttpExceptionFilter,
},
```

to this:

```
{
   provide: APP_FILTER,
   useClass: HttpExceptionFilter,
   scope: Scope.REQUEST
},
```

**Comment by jmcdo29** [comment]
@kamilmysliwiec you learn something new every day. Thank you :smile_cat:

**Comment by zjy01** [comment]
@kamilmysliwiec

**Comment by zjy01** [comment]
@kamilmysliwiec That works for me. Thank you
