### ISSUE TITLE
When using nest cli, using commands like npm run start or nest g module <name> gives this error

### ISSUE THREAD

**Issue by ansonfoong** [nestjs/nest#4678]
## Current behavior
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\\Documents\nest-project\node_modules\is-promise\index.js
require() of ES modules is not supported.
require() of C:\Users\\Documents\nest-project\node_modules\is-promise\index.js from C:\Users\\Documents\nest-project\node_modules\run-async\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename C:\Users\\Documents\nest-project\node_modules\is-promise\index.js to end in .cjs, change the requiring code to use import(), or remove "type":
"module" from C:\Users\\Documents\nest-project\node_modules\is-promise\package.json.

## Possible Solution

It says to go inside is-promise package and remove the "type: module", this fixed it, but of course why should this be an issue?

## Environment

TypeScript v3.8.3
Nest version: X.Y.Z

Nest Version: 7.1.2
 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Windows

**Comment by msheakoski** [comment]
Related issue: #4677

**Comment by msheakoski** [comment]
Confirmed to be working again. This issue can be closed.
