### ISSUE TITLE
app.enableCors not working properly

### ISSUE THREAD

**Issue by gimyboya** [nestjs/nest#4683]
## Current behavior
when setting an array of strings or regex as an origin the `Access-Control-Allow-Origin` header is missing completely. 

## Input Code
```ts
// this works perfectly fine
app.enableCors({
      origin: `https://my.domain.com,
      credentials: true,
    });

// this however doesn't work
app.enableCors({
      // origins are localhost and netlify.com
      origin: [/http:\/\/localhost:[\d]{2,4}/, /.+netlify\.com/],
      credentials: true,
    });
// or this
app.enableCors({
      origin: ['https://my.domain.com', 'https://localhost:5000'],
      credentials: true,
    });
```

## Expected behavior
support all the cors [configuarion options](https://github.com/expressjs/cors#configuration-options) as per the docs.

## Possible Solution
not sure where the bug is coming from

## Environment
<pre><code>
Nest version: 6.11.11
 
For Tooling issues:
- Node version: 12.16.2 
- Platform:  Linux, Windows
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, report this here https://github.com/expressjs/cors

**Comment by cksharma11** [comment]
@gimyboya could you paste your package json here, I'd similar problem while using 8.2.6 version and when I changed it to 8.2.3 it worked

**Comment by gimyboya** [comment]
@cksharma11 sorry this issue was 2 years old and I don't have the context I had back then. Nor I remember how I solved it
