### ISSUE TITLE
Linting warnings in a new project

### ISSUE THREAD

**Issue by Fgerthoffert** [nestjs/nest#4684]
## Bug Report

I'm starting a new GraphQL project, following the code-first approach, but I'm getting a bunch of linting warning for rule `@typescript-eslint/no-unused-vars` whenever `@Field` is used.

I see the same is happening with the following sample project: https://github.com/nestjs/nest/tree/master/sample/23-graphql-code-first

I don't want to disable the rule altogether, other than disabling the rule for each line, would there be a way to address this in the code?

## Steps to reproduce

```bash
git clone git@github.com:nestjs/nest.git
cd nest/sample/23-graphql-code-first
yarn
yarn run lint
```

## Current behavior

```bash
nest/sample/23-graphql-code-first on  master [?] is 📦 v1.0.0 via ⬢ v12.16.2 took 26s 
➜ yarn run lint
yarn run v1.22.4
$ eslint '{src,apps,libs,test}/**/*.ts' --fix

/Users/user/GitHub/nestjs/nest/sample/23-graphql-code-first/src/common/scalars/date.scalar.ts
  4:17  warning  'type' is defined but never used  @typescript-eslint/no-unused-vars

/Users/user/GitHub/nestjs/nest/sample/23-graphql-code-first/src/recipes/dto/new-recipe.input.ts
  15:10  warning  'type' is defined but never used  @typescript-eslint/no-unused-vars

/Users/user/GitHub/nestjs/nest/sample/23-graphql-code-first/src/recipes/dto/recipes.args.ts
   6:10  warning  'type' is defined but never used  @typescript-eslint/no-unused-vars
  10:10  warning  'type' is defined but never used  @typescript-eslint/no-unused-vars

/Users/user/GitHub/nestjs/nest/sample/23-graphql-code-first/src/recipes/models/recipe.model.ts
   5:10  warning  'type' is defined but never used  @typescript-eslint/no-unused-vars
  17:10  warning  'type' is defined but never used  @typescript-eslint/no-unused-vars

/Users/user/GitHub/nestjs/nest/sample/23-graphql-code-first/src/recipes/recipes.resolver.ts
  11:11  warning  'of' is defined but never used       @typescript-eslint/no-unused-vars
  15:10  warning  'returns' is defined but never used  @typescript-eslint/no-unused-vars
  24:10  warning  'returns' is defined but never used  @typescript-eslint/no-unused-vars
  29:13  warning  'returns' is defined but never used  @typescript-eslint/no-unused-vars
  38:13  warning  'returns' is defined but never used  @typescript-eslint/no-unused-vars
  43:17  warning  'returns' is defined but never used  @typescript-eslint/no-unused-vars

/Users/user/GitHub/nestjs/nest/sample/23-graphql-code-first/src/recipes/recipes.service.ts
  14:16  warning  'data' is defined but never used         @typescript-eslint/no-unused-vars
  18:21  warning  'id' is defined but never used           @typescript-eslint/no-unused-vars
  22:17  warning  'recipesArgs' is defined but never used  @typescript-eslint/no-unused-vars
  26:16  warning  'id' is defined but never used           @typescript-eslint/no-unused-vars

✖ 16 problems (0 errors, 16 warnings)

✨  Done in 4.27s.
```

## Expected behavior
No warnings

## Environment

Nest version: 7.0.9
 
For Tooling issues:
- Node version: v12.16.2
- Platform: Mac

**Comment by jmcdo29** [comment]
You can use a function that looks like this instead and then not have those errors. This is an issue of an aggressive linter, not a problem with the framework.

```ts
@Field(() => ID)
```
And now there's no linting error.

**Comment by Fgerthoffert** [comment]
Awesome, thanks for the quick response.

**Comment by RodrigoLeiteF** [comment]
You can also modify your .eslintrc.js file to include the following:

```js
module.exports = {
  rules: {
    '@typescript-eslint/no-unused-vars': ['error', { args: 'none' }],
  },
};
```

This disables the `no-unused-vars` rule but only for function arguments, making this issue go away while keeping the rule in other contexts.

**Comment by timecatalyst** [comment]
Sorry for bringing back this thread, but I'm experiencing a similar problem with the `Get()` decorator in a fresh project created with `@nestjs/cli`.  It seems to happen whenever I use an interface in a `Promise` generic response:

```
 1 import { Controller, Get } from '@nestjs/common';
 2
 3 interface Foo {
 4   foo: string;
 5 }
 6
 7 @Controller('foo') 
 8 export class FooController {
 9   @Get()
10   async doSomething(): Promise<Foo> {
11     return Promise.resolve({ foo: 'bar' });
12   }
13 }
```

The linter is throwing a `no-unused-vars` warning on line 3: `interface Foo`, despite it being used as the response type of `doSomething()` on line 10.  If I remove the `@Get` decorator, the warning disappears.  So far I haven't been able to find a workaround for it.

<img width="723" alt="Screen Shot 2021-01-21 at 11 19 45 AM" src="https://user-images.githubusercontent.com/6643210/105383399-139fb380-5bdf-11eb-859a-f6fc89e13a69.png">

**Comment by jmcdo29** [comment]
This looks like something that would be reported to the Typescript-eslint repository. It might be trusted to a new change dealing with decorators and exported types

**Comment by timecatalyst** [comment]
@jmcdo29 Sounds good, will do. Thanks for the quick response.

**Comment by timecatalyst** [comment]
In case anyone ends up here in the future, the problem I was experiencing was related to `emitDecoratorMetadata` in `tsconfig.json`.  See: https://github.com/typescript-eslint/typescript-eslint/issues/2972
