### ISSUE TITLE
Graphql Apollo Federation Sample

### ISSUE THREAD

**Issue by arceliver** [nestjs/nest#4686]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Can a sample of how using apollo federation with nestjs be uploaded? Most of the docs sections have a sample attached, but this one has just a tutorial that is not working for my case.

## Teachability, Documentation, Adoption, Migration Strategy
Users will have an example to start their own projects.

## What is the motivation / use case for changing the behavior?
I'm trying to use but with no success.

**Comment by igortas** [comment]
Is it possible the sample to be done also in code first approach? I can't follow with the example in the docs, as I can't generate SDL like most of examples explain federation.

**Comment by Tony133** [comment]
For this sample do you have to do it for both code-first and schema-first?

**Comment by BhupenT** [comment]
I am also waiting for this. I am having trouble To make it work too. Thanks

**Comment by Flusinerd** [comment]
I'll look into this.

**Comment by Flusinerd** [comment]
Created a PR for this #7486

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/7486
