### ISSUE TITLE
findOne - relations

### ISSUE THREAD

**Issue by wlyssescerqueira** [nestjs/nest#4691]
let prod = await this.productRepository.findOne(product.id, { relations: ['productAdditional']});

return:
![image](https://user-images.githubusercontent.com/41481028/80418105-3ea5e280-88ad-11ea-8306-11002fc15413.png)

I need to check the two objects using **Object.assign**, but it **doesn't work** because the productAdditional object is different.
![image](https://user-images.githubusercontent.com/41481028/80418174-5c734780-88ad-11ea-82bd-828f6cd8cbfe.png)

Question: Is there a way to not bring the name of the object using the findOne method?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
