### ISSUE TITLE
Sharing type definitions between NodeJS package and React Application fails with dependency issues

### ISSUE THREAD

**Issue by AeroNotix** [nestjs/nest#4692]
## Example repository

https://github.com/AeroNotix/react-nest-test

## Related Issues

* https://github.com/nestjs/nest/issues/1706

## Current behavior

I have a rush monorepo which has various packages, the two I am having issue are:

* NestJS NodeJS application
* React application created with `create-react-app`.

## description

Depending on a nestjs-based NPM package results in compilation errors for missing modules, e.g.:

```
/home/foo/bar/common/temp/node_modules/.registry.npmjs.org/@nestjs/core/7.0.6/node_modules/@nestjs/core/nest-application.js
Module not found: Can't resolve '@nestjs/microservices' in '/home/foo/bar/common/temp/node_modules/.registry.npmjs.org/@nestjs/core/7.0.6/node_modules/@nestjs/core'
```

The behaviour looks to be related to how webpack is determining which modules should be loaded and included. In the above example the npm package makes no use of the `@nestjs/microservices` package directly, though it is throwing missing module errors for that package (which led us to the related ticket).

I realise in the related ticket that you mention that there's a disconnect between how NestJS wants to do "lazy loading" of modules, compared to how webpack may be traversing the dependency graph - that said. The react application I am consuming the package from is barely modified beyond what `create-react-app` spits out.

## Expected behavior

I expect to be able to depend on a NestJS-based npm package in a React application, to consume type definitions, without issue.

## Possible Solution

* If I `import` the type directly from the module where it is created, the issue ceases, e.g.:

```typescript
import { MyCoolType } from "package/dist/src/thing/module'; // this works!
import { MyCoolType } from "package"; // this results in the above error
```

* webpack.IgnorePlugin to selectively remove/ignore dependencies the application shouldn't be including.
* Refactor types into a third-package sans all NestJS-related dependencies
* Copy/paste code around between packages.

## Environment

```
    "@nestjs/common": "7.0.6",
    "@nestjs/config": "0.4.0",
    "@nestjs/core": "7.0.6",
    "@nestjs/graphql": "7.2.1",
    "@nestjs/platform-express": "7.0.7",
    "@nestjs/schedule": "0.3.1",
    "@nestjs/swagger": "4.5.1",
    "@nestjs/typeorm": "7.0.0",
```

For Tooling issues:
- Node version: v10.17.0
- Platform:  Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by AeroNotix** [comment]
I don't use discord and I'm not following how this isn't being interpreted as a bug?

**Comment by mateushnsoares** [comment]
It is a bug.... This issue need be reopened
