### ISSUE TITLE
Gateway e2e tests

### ISSUE THREAD

**Issue by underfisk** [nestjs/nest#4693]
## Is your feature request related to a problem? Please describe.
I'm currently trying to mock my gateways and avoid creating a real WebSocket server for tests or not getting it at all

## Describe the solution you'd like

I  would like to test if some events are really fired and having a base event emitter that simply emits locally because my HTTP publish events and i would like to know if the consumers are getting it correctly 

## What is the motivation / use case for changing the behavior?

Testing the consumer side when publishing my gateway events

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
