### ISSUE TITLE
Enable bootstrap tracing

### ISSUE THREAD

**Issue by manju-reddys** [nestjs/nest#4694]
## Is your feature request related to a problem? Please describe.

I want to turn on the application bootstrapping logging to tracing but there is no documentation how to enable or turn on tracing of bootstrapping

![image](https://user-images.githubusercontent.com/1906881/80429502-1d3ef980-88a1-11ea-9c27-58b612cef9e8.png)
 

## Describe the solution you'd like

How to turn on the bootstrapping tracing? I tried both `--debug and --trace` neither worked 

## What is the motivation / use case for changing the behavior?
There is no documentation about the log / trace the application bootstrap.

**Comment by kamilmysliwiec** [comment]
We don't have any additional console logs that could be enabled by the host application.
