### ISSUE TITLE
Can't use an Axios CancelToken in HttpService

### ISSUE THREAD

**Issue by nlenepveu** [nestjs/nest#4698]
## Current behavior
Can't use an Axios Cancel Token in HttpService. Sometimes we can't rely on the timeout and we need to use the cancel token in order to make the request not last forever (or use any valid reason to cancel a request).

HttpService uses a cancel token internally for its own purpose and overwrites any cancel token provided by the user.

## Input Code
```ts
this.httpService.get(url, {
  cancelToken: new axios.CancelToken(cancel => setTimeout(() => cancel(), 3_000)),
})
```

## Expected behavior
We should be able to provide a cancel token with not need to use the Axios instance.

## Possible Solution
Using the axiosRef is a solution but we should also need to manually wrap it as an observable. 
```ts
defer(() => this.httpService.axiosRef.get(url, {
  cancelToken: new axios.CancelToken(cancel => setTimeout(() => cancel(), 3_000)),
}))
```

We could check if a cancel token is provided before creating a new one. 

## Environment

<pre><code>
Nest version: v7.0.9
 
For Tooling issues:
- Node version: v12.15.0
- Platform:  Linux
</code></pre>

**Comment by nlenepveu** [comment]
I'll provide a PR with a change later.

**Comment by kamilmysliwiec** [comment]
Added in the latest release. Thanks!
