### ISSUE TITLE
Content Negotiation in Nest

### ISSUE THREAD

**Issue by btilford** [nestjs/nest#4704]
Is there anything similar to [res.format](https://expressjs.com/en/api.html#res.format) in express that you can use without needing to directly interact with the native response? I've looked through docs and tried discord a few times but haven't got anywhere with this. 

If this isn't currently supported would writing an interceptor be the recommended way of achieving it or would it be necessary to use another method?

**Comment by jmcdo29** [comment]
@btilford I know we talked briefly on Discord about this. Looking into [how the Express adapter sends responses](https://github.com/nestjs/nest/blob/master/packages/platform-express/adapters/express-adapter.ts#L21), this is probably something you can do in an interceptor, as you'll have full access to the request (for incoming headers), the response (for outgoing headers), and the response body (via the `map()` operator from `rxjs`). I planned on getting to doing a small test with it today 😸

**Comment by jmcdo29** [comment]
@btilford got it! [Here's the repo](https://github.com/jmcdo29/nest-content-negotiation). This is absolutely possible in interceptors. Sorry for steering you wrong yesterday.

**Comment by btilford** [comment]
Awesome, looks like that's exactly what I was looking for. I assume I could use the ExecutionContext to read in metadata for things like template paths if I were using a template engine there as well?

**Comment by jmcdo29** [comment]
It may require a bit of metadata reading, but it should be possible. I'm not sure where that information would be (if it is on the req or res objects), but if not you can always rely on the `reflector` and get metadata from the current handler.

**Comment by btilford** [comment]
Sounds good, I'd probably need to write some decorators to add metadata but I think I've got enough info to get started.

**Comment by kamilmysliwiec** [comment]
@jmcdo29 thanks for helping out!

As we are using GitHub to track bugs, feature requests, and potential improvements, please, use either StackOverflow or Discord next time. :)

**Comment by zbarbuto** [comment]
Sorry to grave-dig a ticket but for anyone who stumbles on this issue like I did and is curious about how you can do the rendering that @btilford was talking about - I've put together an example repo based on @jmcdo29 's demo here:

https://github.com/zbarbuto/nest-example-html-content-negotation

It will dynamically either render the response of the cats controller as a HTML view (defined with the `ViewAs` decorator) or return the raw JSON based on the `Accept` headers sent.
