### ISSUE TITLE
How to validate ONE param in query nestjs?

### ISSUE THREAD

**Issue by milovidov983** [nestjs/nest#4713]
I need to validate only one param in query.

What I have now:
```typescript
  @Get('status')
  getStatus(@Query() token: string): IStatusResponse {
    if (!token) {
      throw new HttpException('Token param is empty', HttpStatus.BAD_REQUEST);
    }
    const response = this.service.getStatus(token);
    if (response) {
      return response;
    }
    throw new HttpException('Data not found.', HttpStatus.NOT_FOUND);
  }
```

How I wish it was:

```typescript
  @Get('status')
  @IsNotEmptyParam('token', 'Token param is empty', HttpStatus.BAD_REQUEST)
  getStatus(@Query() token: string): IStatusResponse {
    const response = this.service.getStatus(token);
    if (response) {
      return response;
    }
    throw new HttpException('Data not found.', HttpStatus.NOT_FOUND);
  }
```
or something

And what else can be improved in this code?

thx!

**Comment by jmcdo29** [comment]
What is `@IsNotEmptyParam()`? Couldn't you make this kind of logic work with a pipe? 

Please use [Discord](https://discord.gg/nestjs) as we are using GitHub to track bugs and enhancements.

**Comment by milovidov983** [comment]
> What is `@IsNotEmptyParam()`? Couldn't you make this kind of logic work with a pipe?
> 
> Please use [Discord](https://discord.gg/nestjs) as we are using GitHub to track bugs and enhancements.

this is my fiction about how I would like

**Comment by jmcdo29** [comment]
As I said, what you're looking for is doable in a pipe. This isn't really an enhancement to the framework. If you need more guidance, please [ask on Discord](https://discord.gg/nestjs)

**Comment by dynamikus** [comment]
I think this is already implemented with the auto validation feature of nest 7.
In the documentation, there is already something similar to what you are looking for.
The example is for param but I will assume it will be the same for query params as well.

`@Get(':id')
findOne(@Param() params: FindOneParams) {
  return 'This action returns a user';
}`

`
import { IsNumberString } from 'class-validator';

export class FindOneParams {
  @IsNumberString()
  id: number;
}


https://docs.nestjs.com/techniques/validation#auto-validation
`

**Comment by milovidov983** [comment]
thanks everyone

**Comment by ravi31srv** [comment]
> I think this is already implemented with the auto validation feature of nest 7. In the documentation, there is already something similar to what you are looking for. The example is for param but I will assume it will be the same for query params as well.
> 
> `@Get(':id') findOne(@Param() params: FindOneParams) { return 'This action returns a user'; }`
> 
> `import { IsNumberString } from 'class-validator';
> 
> export class FindOneParams { @IsNumberString() id: number; }` https://docs.nestjs.com/techniques/validation#auto-validation

Yes, it is there in documentation in which class FindOneParams is used for single ':id' param. 
Is there any way using which we can implement same thing directly on controller without making class FindOneParam.
