### ISSUE TITLE
unit-test controller guard

### ISSUE THREAD

**Issue by webplus** [nestjs/nest#4717]
```shell

 FAIL  src/modules/material/controller/material.controller.spec.ts
  ● Test suite failed to run

    Invalid guard passed to @UseGuards() decorator (CreativeController).

      12 | @Controller('creative')
      13 | @UseGuards(AuthGuard)
    > 14 | export class CreativeController {
         |                                ^
      15 |     constructor(private readonly creativeService: CreativeService) {}

      at Object.validateEach (../node_modules/_@nestjs_common@6.11.11@@nestjs/common/utils/validate-each.util.js:20:15)
      at UseGuards (../node_modules/_@nestjs_common@6.11.11@@nestjs/common/decorators/core/use-guards.decorator.js:38:30)
      at DecorateConstructor (../node_modules/_reflect-metadata@0.1.13@reflect-metadata/Reflect.js:541:33)
      at Object.decorate (../node_modules/_reflect-metadata@0.1.13@reflect-metadata/Reflect.js:130:24)
      at Object.__decorate (../node_modules/_tslib@1.11.1@tslib/tslib.js:94:96)
      at Object.<anonymous> (modules/creative/controller/creative.controller.ts:14:32)
```

AuthGuard.ts
```javascript
@Injectable()
export class AuthGuard implements CanActivate {
    constructor(private readonly authService: AuthService) {}

    async canActivate(context: ExecutionContext): Promise<boolean | any> {
      ......  
      return true;
    }
}
```

material.controller.ts、creative.controller.ts
```javascript

// material.controller.ts
@UseGuards(AuthGuard)
export class MaterialController {
    constructor(private readonly materialService: MaterialService) {}
}

// creative.controller.ts
@UseGuards(AuthGuard)
export class CreativeController {
    constructor(private readonly creativeService: CreativeService) {}
}
```

material.controller.spec.ts
```javascript
describe('test controller', () => {
    let controller: MaterialController;
    beforeEach(() => {
        // const mockGuard: CanActivate = { canActivate: jest.fn(() => Promise.resolve(true)) };

        const module: TestingModule = await Test.createTestingModule({
            imports: [MaterialModule],
        }).compile();

        controller = module.get<MaterialController>(MaterialController);
    });
});
```

I don't know why？
Invalid guard passed to @UseGuards() decorator (CreativeController).

Appreciate any help, Thanks.

**Comment by jmcdo29** [comment]
You shouldn't be using `imports` in your unit tests, as that will import the entire module. Rather, you should be using `controllers: [MaterialController]` and provide custom providers to mock out the dependencies of the `MaterialController` for the unit test. 

Please use our [Discord](https://discord.gg/nestjs) as we are using GitHub to track bugs and feature requests.

**Comment by webplus** [comment]
Sorry, I can't use discordapp.com in China

I find .overrideguard() doesn't work.
It's ok if I try to remove line constructor(private readonly authService: AuthService) {}


```typescript
@Injectable()
export class AuthGuard implements CanActivate {
    constructor(private readonly authService: AuthService) {}

    async canActivate(context: ExecutionContext): Promise<boolean | any> {}
```

material.controller.spec.ts

```typescript

describe('test controller', () => {
    beforeEach(async () => {
        const mockGuard: CanActivate = { canActivate: jest.fn(() => true) };

        const module: TestingModule = await Test.createTestingModule({
            controllers: [MaterialController],
            // providers: [{ provide: AuthGuard, useValue: mockGuard }],
        })
            .overrideGuard(AuthGuard)
            .useValue(mockGuard)
            .compile();

        const controller = module.get<MaterialController>(MaterialController);

        describe('controller test', () => {
            it('test hi', (done) => {
                expect(controller.query()).toBe('hi');
                done();
            });
        });
    });
});

```

### Environment
  - Nest version: 6.5.0 
  - Node version: 10.15.3

**Comment by kamilmysliwiec** [comment]
My guess is that you use `index.ts` files (barrel files) to re-export classes. In Jest, this will sometimes lead to classes represented as `undefined`. This error:

> Invalid guard passed to @UseGuards() decorator (CreativeController).

Means that you passed `undefined `value (`AuthGuard` = `undefined`). Make sure to get rid of your `index.ts` (or any barrel files) in your app.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) or StackOverflow for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by darrenangle** [comment]
For anyone experience strange issues in this territory, I've seen a similar error when I was exporting types and injection token consts directly from my feature.module.ts that were being imported into the guard.

It seems like jest doesn't play well with this pattern and these should live in their own files, as importing anything from the module file triggers unpredictable and difficult to diagnose dependency errors elsewhere.
