### ISSUE TITLE
webpack build outDir doesn't work

### ISSUE THREAD

**Issue by xrobert35** [nestjs/nest#4721]
Hello,

## Current behavior

I'm building a multi apps projet using the nest and angular. 
I need to changed the dist path (to the parent folder) to have my angular and nestjs dist in the same folder. In the **tsconfig.app.json** of my nestjs app  and simply change the "outDir" directory of the compilerOptions but the **main.js** keep is position in  :

- angular-project
- nest-mono-repo-projet
  - nest-cli.json
  - dist/apps/[nest-projet-name]/main.js  **<<< still here**
- dist
  - angular-project
  - [nest-projet-name]/main.js **<< what i want**

The strange thing is that I have some assets in the project and the assets are correctly moved in the new dist folder

## To reproduce

```
nest --version
7.1.4
```

``` back
nest new nest-project
cd nest-project
nest generate app scd-app
```

edit the **tsconfig.app.sjon** of  nest-project app

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "declaration": false,
    "outDir": "../../../dist/apps/nest-project"   // old : ../../dist/apps/nest-project
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist", "test", "**/*spec.ts"]
}
```

```
nest build nest-project
```

The default **dist** folder is still used. I tried to change the folder name also but nothing change, except for assets

Am I missing something ?

## Expected behavior

The outDir parameter should change the build output

## Environment

<pre><code>
Nest version: 7.1.4

 
For Tooling issues:
- Node version: v10.19.0 (tried with 12.10.0 also)
- Platform:  Ubuntu 20.04
- IDE : vscode
</pre></code>

Thanks,

**Comment by kamilmysliwiec** [comment]
Webpack ignored the `outDir`. For this, define the custom `webpack.config` https://docs.nestjs.com/cli/monorepo#webpack-options (`output` option https://webpack.js.org/configuration/output/)

**Comment by xrobert35** [comment]
Hello,

thanks for this quick answer. Here's is a working :  

```javascript
// webpack.config.js

const path = require('path');

module.exports = (options) => {
  let config = { ...options };
  config.output.path = path.resolve(__dirname, '../dist');
  return config;
};
```
