### ISSUE TITLE
Grpc interface creation using protoc - solution inside!

### ISSUE THREAD

**Issue by iangregsondev** [nestjs/nest#4722]
Hi,

This isn't really a support question, its more of a request to include some info in the docs.

I am using the GRPC proto implementation for microservices, i searched high and low for some libraries just to create standard interfaces - but I wasn't able to find anything. 

Anyway I created a pull request (at it was accepted) - here https://github.com/stephenh/ts-proto

I would appreciate if we can create something in the docs as a link - it would be really really helpful to help people like me.

I might have got something wrong, I don't think i did but I was kind of creating it around me:-)

it supports grpc metadata and also returning either promises or observables.

I would appreciate any input and getting the word out there.

Maybe I missed something, the author of the library is a really nice guy and accepted a NestJS only PR - if anybody can improve it - I am sure it would be more than helpful!

@kamilmysliwiec I don't know if you could put a link on the docs - but I know it would be helpful - I have been searching for something for a long time - most of the stuff I found would create the full classes with all the grpc methods, instead of just plain old interfaces.

Thanks!

**Comment by kamilmysliwiec** [comment]
Thanks for sharing your insights @iangregsondev.

Unfortunately, we can't really recommend a package that we never played with. Linking an external library from the documentation may lead to the wrong conclusion that we consider it as stable & secure etc (although, we've never used it).
