### ISSUE TITLE
Adding webassembly improves performance.

### ISSUE THREAD

**Issue by zuohuadong** [nestjs/nest#473]
Use: Https://github.com/AssemblyScript/assemblyscript

Consider using webassembly to improve typescript performance.

**Comment by BorntraegerMarc** [comment]
I doubt web Assembly is ready for a prod nodejs application. At least not until version wasm 2.0 is released...

**Comment by FriOne** [comment]
It still is not ready for anything, I saw a code that is slower than the same js implementation.

**Comment by kamilmysliwiec** [comment]
WebAssembly is not ready yet. We'll definitely think about it in the future.
