### ISSUE TITLE
Nest microservice registration does not wait for modules to init

### ISSUE THREAD

**Issue by shlomiassaf** [nestjs/nest#4731]
## Current behavior

```ts
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [ NesBusTestModule ],
    }).compile();

    app = moduleFixture.createNestMicroservice({ strategy: createSbServer() });

    await app.listenAsync();
```

When calling ` await app.listenAsync();` or `app.listen` with a callback, nest will init all modules.

However, the code does not wait for all module to init.

https://github.com/nestjs/nest/blob/995e2870d5e2ebbd012031f9fb1036c2f185b23a/packages/microservices/nest-microservice.ts#L118

The call to `this.registerModules();` is async and it runs all module init lifecycle hooks and bootstrap.

**Comment by kamilmysliwiec** [comment]
This has been fixed already
