### ISSUE TITLE
Implement HTTP/2 server

### ISSUE THREAD

**Issue by gabrielmoncea** [nestjs/nest#4734]
It would be really awesome if Nest would add support for HTTP/2 for Express through [node-spdy](https://github.com/spdy-http2/node-spdy).

```
   With this module you can create HTTP2 / SPDY servers in node.js
with natural http module interface and fallback to regular https
(for browsers that don't support neither HTTP2, nor SPDY yet).
```

**Comment by kamilmysliwiec** [comment]
You can integrate Nest and spdy by following these instructions: https://docs.nestjs.com/faq/multiple-servers#multiple-simultaneous-servers

**Comment by brianschardt** [comment]
Yes but what if the reason you are using http2 is to use websockets with graphql subscriptions. 
There is a note that says this does not work with gql subscriptions. 
Thanks for the help on this.

**Comment by cjkoral** [comment]
Im looking for the same solution as @brianschardt.  GraphQL subscriptions appear to be much more limited through HTTP/1
