### ISSUE TITLE
Question: Access request context in entity

### ISSUE THREAD

**Issue by treykaws** [nestjs/nest#4739]
I tried to use the suggested methods of support/questions but have not been able to get any feedback. So I decided to test my luck here.

**Design/Question:**
Primarily regarding TypeORM

As most of you are aware of it is common practice in web applications to keep track of data updates / insertions. Thus creating createdBy / updatedBy columns is standard in table design. Most of the time this is tracked by authentication tokens housing specific data to link to a user.

Instead of flowing the data from the controller (req.user) all the way down to the service/entity. Is there any way to access the request context directly within an entity? I was able to accomplish this in C# (dotnet core). So I was hoping to find a solution or be pointed in the right direction in doing so - if it is at all possible!

Alternatively, even if I'm able to inject the request context onto an Event Subscriber that may be a possible solution.

All help is appreciated. Thanks!

**Comment by kamilmysliwiec** [comment]
Check out this chapter https://docs.nestjs.com/fundamentals/injection-scopes

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
