### ISSUE TITLE
This document is hard to use

### ISSUE THREAD

**Issue by bibiuc** [nestjs/nest#474]
This is a suggestion：
Although the editor can prompt the code may have parameters.
But I think we still need a list of API type method parameters. 
We are not likely to go back to the code to find this function and what other features. Or advanced extensions

**Comment by chanlito** [comment]
`This document` can you elaborate?

**Comment by cojack** [comment]
@chanlito I think that @bibiuc is missing the API Docs, like http://typedoc.org/

**Comment by RafaelCasuso** [comment]
"This documentation" I guess is the right expression. Yes, a complete API reference is needed, not just a guide. For example it is hard to find logger capabilities in the guide, you have to dig into the code.

**Comment by kamilmysliwiec** [comment]
There're several open issues regarding documentation. I'm on it right now, will share a progress as soon as possible.
