### ISSUE TITLE
Cannot use overrideProvider() to override undefined value

### ISSUE THREAD

**Issue by andreialecu** [nestjs/nest#4743]
## Current behavior

Seems that if a provider has an `undefined` initial value, it cannot be overriden using `overrideProvider()`.

## Input Code

```ts
const mongoUriProvider = {
  provide: "MONGO_URI",
  useValue: process.env.MONGO_URI, // this is undefined in TEST env
};

@Module({
  providers: [mongoUriProvider, ConfigService],
  exports: [ConfigService],
})
export class ConfigModule {}
```

Then in tests:

```ts
    const module: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider("MONGO_URI")
      .useValue(someConnectionString)
      .compile();
```

Everything fails because `MONGO_URI` is not defined:

```
    Nest can't resolve dependencies of the ConfigService (?). Please make sure that the argument MONGO_URI at index [0] is available in the ConfigModule context.

    Potential solutions:
    - If MONGO_URI is a provider, is it part of the current ConfigModule?
    - If MONGO_URI is exported from a separate @Module, is that module imported within ConfigModule?
      @Module({
        imports: [ /* the Module containing MONGO_URI */ ]
      })
```

This took a couple of hours of troubleshooting to figure out. A workaround is to provide a default non-undefined value. `null` seems to work:

```
const mongoUriProvider = {
  provide: "MONGO_URI",
  useValue: process.env.MONGO_URI || null,
};
```

## Expected behavior

Should be able to override the provider during tests even if it is set to undefined. 

At a minimum, a warning should be emitted that an undefined provider has been set, if it cannot be fixed for other reasons.

## Environment

<pre><code>
Nest version: 7.0.9
</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for reporting!

This was already discussed in the past. You can't bind `undefined` values to the container (`undefined` has simply too many meanings, we can't determine whether you did it on purpose or not) so it's not really an issue with the `overrideProvider()` method.

**Comment by andreialecu** [comment]
Could `overrideProvider` at least log an error that the token wasn't found and to check whether it is set to an undefined value?

> You can't bind undefined values to the container 

But you can. :) And it results in this sort of issue. Maybe just throw an error on initialization if an undefined provider is detected?

I feel this behavior is very unexpected and not documented anywhere and just leads into a lot of confusion.

**Comment by andreialecu** [comment]
Here's an alternative:

If `ValueProvider` is defined like this:

```ts
export interface ValueProvider<T = string | number | boolean | symbol | bigint | object | null> {
    /**
     * Injection token
     */
    provide: string | symbol | Type<any> | Abstract<any> | Function;
    /**
     * Instance of a provider to be injected.
     */
    useValue: T;
}
```

It will at least show a compilation error in typescript `strict` mode:

![image](https://user-images.githubusercontent.com/697707/81280779-a86a7d00-9061-11ea-963f-9608f2ac62f1.png)

Not sure if anything can be done about non-strict mode.

Some relevant discussion here: https://github.com/microsoft/TypeScript/issues/7648
