### ISSUE TITLE
certs reload without server rbeoot

### ISSUE THREAD

**Issue by l0yu** [nestjs/nest#4744]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

Hi nest team, I am reading https://docs.nestjs.com/faq/multiple-servers#https
is it possible to reload key/cert file periodically without reboot server ?
If I add function like
```
const httpsOptions = {
  key: fs.readFileSync('./secrets/private-key.pem'),
  cert: fs.readFileSync('./secrets/public-certificate.pem'),
};

function reloadCerts(httpsOptions) {
  httpsOptions.key = fs.readFileSync('./secrets/private-key.pem')
  httpsOptions.cert = fs.readFileSync('./secrets/public-certificate.pem')
}

// refresh key/certs every second
setTimeout(reloadCerts, 1000, httpsOptions);

const app = await NestFactory.create(ApplicationModule, {
  httpsOptions,
});
await app.listen(3000);
```
does this work ? ^^

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
