### ISSUE TITLE
Support for Prisma 2.x

### ISSUE THREAD

**Issue by Akxe** [nestjs/nest#4745]
## Is your feature request related to a problem? Please describe.
This is related to NestJS being compatible with Prisma 1.x

## Describe the solution you'd like
One would expect to have the option to use Prisma 2.x. I would even say that Prisma 1.x could be discontinued.

## Teachability, Documentation, Adoption, Migration Strategy
Migration is minimal:
* Prisma will take care of its migration
* NestJS need to update/want the user to update the `PrismaService`

## What is the motivation / use case for changing the behavior?
Futureproofing

**Comment by kamilmysliwiec** [comment]
PRs to examples & docs from anyone interested in doing that are more than welcome. We have other priorities now

**Comment by vh13294** [comment]
@kamilmysliwiec 

Are you planing to migrate to different ORM?

Considering the issues are pilling up in TypeORM.

I think Prisma 2 is definitely a viable candidate for replacement.

**Comment by kamilmysliwiec** [comment]
@vh13294 you can use any ORM you want, TypeORM, Sequelize, MikroOrm, or tools like Knex, Prisma, etc. Nest isn't tied to any specific ORM.
