### ISSUE TITLE
Provide Validation for FileInterceptor/UploadedFile to Ensure a File is Actually Uploaded

### ISSUE THREAD

**Issue by WonderPanda** [nestjs/nest#4752]
## Feature Request
Provide a built in way to ensure that when using `@FileInterceptor` that it is easy to validate the scenario where no file was actually sent to the backend

## Is your feature request related to a problem? Please describe.
The current `@UploadedFile` implementation doesn't allow it to participate in Pipes validation. Even if it did, many users would have to implement a custom Pipe to ensure that the file was set in UserLand code. This seems like a common enough scenario that it would make sense for NestJS to support an out of the box solution

## Describe the solution you'd like
One of: 
- Extend the existing `@FileInterceptor` so that it takes (optional) additional configuration that indicates an error should be thrown if no file/files are found at the specified fields.
- Update the `@UploadedFile` decorator so that it can participate in Pipes validation and then provide a built in Pipe eg `ParseFile`

## What is the motivation / use case for changing the behavior?
Seamless out of the box experience for dealing with file uploading. Less duplication in user land code to cover common community scenarios

## Notes
I'd be happy to open up a PR for this if there is some guidance regarding which approach would be preferred

**Comment by kamilmysliwiec** [comment]
> - Extend the existing @FileInterceptor so that it takes (optional) additional configuration that indicates an error should be thrown if no file/files are found at the specified fields.
> - Update the @UploadedFile decorator so that it can participate in Pipes validation and then provide a built in Pipe eg ParseFile

TBH I like both ideas 🙂 The second one should be easier to implement though. 

Would you like to create a PR with eg `ParseFile` you mentioned? I'll chime in then and make sure that pipes are evaluated for files too.

**Comment by rubiin** [comment]
@WonderPanda both of the ideas look great.

**Comment by WonderPanda** [comment]
Apologies guys life has been super busy the last couple weeks as I'm transitioning jobs at the moment. I'll look at getting a PR up for this this week

**Comment by Langstra** [comment]
@WonderPanda really interested in this, both ideas seem great!

**Comment by mertcanekiz** [comment]
Any updates on this?

**Comment by JeromeGill** [comment]
Is anyone working on this?

**Comment by kamilmysliwiec** [comment]
@JeromeGill  @mertcanekiz  @Langstra PRs are more than welcome! There's no PR targeting this issue atm

**Comment by omer-morad-ni** [comment]
Hi,

@kamilmysliwiec is this issue still need a PR? 
Or someone is already working on one?

I would love to give it a shot :)

**Comment by kamilmysliwiec** [comment]
@omer-morad-ni yes, PR would be more than welcome

**Comment by patryk-bernasiewicz** [comment]
@omer-morad-ni any word on your idea? :)

**Comment by omer-morad-ni** [comment]
Sorry for the late response!
I did not have time to progress so much, I was loaded with a lot of work in the last month 😭

**Comment by mdaj06** [comment]
@kamilmysliwiec is this issue still open, if so i could help out!

**Comment by kamilmysliwiec** [comment]
Still open yes! @mdaj06

**Comment by mdaj06** [comment]
Shall I have a go at it @kamilmysliwiec ?

**Comment by kamilmysliwiec** [comment]
Sounds great!

**Comment by dzcpy** [comment]
Any solutions so far?

**Comment by kamilmysliwiec** [comment]
This will be added in v9.0.0
