### ISSUE TITLE
Documentation: Strategy naming

### ISSUE THREAD

**Issue by JonasPrimbs** [nestjs/nest#4753]
## Is your feature request related to a problem? Please describe.
I had an issue implementing my own Passport Strategy and naming it, so I can use it in an AuthGuard. I solved the issue, but I recommand to improve the documentation about it.

When I looked at the documentation [here](https://docs.nestjs.com/techniques/authentication#implementing-passport-jwt), for some reasons I thought, that naming the Strategy 'JwtStrategy' will be enough to extend the `AuthGuard` class using `... extends AuthGuard('jwt')`. This works, but not because I named the Strategy `JwtStrategy`, but because there is a strategy already registerd with the name `jwt`, which is very confusing!

I also found out, that it is possible, to name the strategy, using `passport.use('jwtbasic', this);` after the `super(...)` statement in the constructor of the Strategy. Is this bad style or why is there no reference that this would be a possible alternative?

## Describe the solution you'd like
It would be nice, if the feature of naming strategies, as described [here](https://docs.nestjs.com/techniques/authentication#named-strategies), will be already presented in the first code example [here](https://docs.nestjs.com/techniques/authentication#implementing-passport-jwt).

If the `passport.use(...)` solution isn't bad style, it would be nice, if this is also stated in the documentation.

## What is the motivation / use case for changing the behavior?
In my case, I did not realize, that I am able to give the Strategy a custom name, when I read [this](https://docs.nestjs.com/techniques/authentication#implementing-passport-jwt) section.

The `passport.use(...)` statement is an easy alternative, if I want to create a strategy (in my case an `abstract class JwtStrategy`) to derive different sub-strategies from it (in my case a `class JwtBearerStrategy` and a `class JwtGetStrategy`).

**Comment by jmcdo29** [comment]
It sounds like what you're looking for is the [Named Strategies](https://docs.nestjs.com/techniques/authentication#named-strategies) portion of the docs. The default name for each Strategy comes from the passport library itself, otherwise you can provide other names as described in the link.

**Comment by JonasPrimbs** [comment]
So my first intention was right?
When I define a Strategy with
```js
@Injectable()
export class JwtBearerStrategy { ... }
```
and provide and export it in my Module as follows:
```js
@Module( {
  ...
  exports: [JwtBearerStrategy],
  providers: [JwtBearerStrategy]
})
...
```
Then it will be available named `JwtBearer`, so I can use it like `AuthGuard('JwtBearer')`?

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/81381051-4a46a400-910c-11ea-97b3-c6c25c9c3fed.png)

Default name !== class name. The default name is imposed by the strategy you use.

For example, the default strategy for `passport-jwt` https://github.com/mikenicholson/passport-jwt is `jwt`:

![image](https://user-images.githubusercontent.com/23244943/81381196-8d087c00-910c-11ea-9f42-b3977e675091.png)

For `passport-http` https://github.com/jaredhanson/passport-http, it will be `basic` as specified in the README:

> Use passport.authenticate(), specifying the 'basic' strategy, to authenticate requests. 

https://github.com/jaredhanson/passport-http#authenticate-requests

**Comment by Bryan-Herrera-DEV** [comment]
> ![image](https://user-images.githubusercontent.com/23244943/81381051-4a46a400-910c-11ea-97b3-c6c25c9c3fed.png)
> 
> Default name !== class name. The default name is imposed by the strategy you use.
> 
> For example, the default strategy for `passport-jwt` https://github.com/mikenicholson/passport-jwt is `jwt`:
> 
> ![image](https://user-images.githubusercontent.com/23244943/81381196-8d087c00-910c-11ea-9f42-b3977e675091.png)
> 
> For `passport-http` https://github.com/jaredhanson/passport-http, it will be `basic` as specified in the README:
> 
> > Use passport.authenticate(), specifying the 'basic' strategy, to authenticate requests.
> 
> https://github.com/jaredhanson/passport-http#authenticate-requests

Thanks man
