### ISSUE TITLE
Pipes don't capture ArgumentMetadata metatype for Custom Decorators

### ISSUE THREAD

**Issue by WonderPanda** [nestjs/nest#4755]
## Bug Report
The documentation isn't completely clear on this so I'm not sure if this is truly a bug or currently expected behavior. According to the page on [Custom Decorators](https://docs.nestjs.com/custom-decorators#working-with-pipes) `Nest treats custom param decorators in the same fashion as the built-in ones`.

When I try this, I can see that the Pipe does execute for a custom decorator but the `ArgumentMetadata` is always empty except for `{"type":"custom"}`. Ideally I'd have access to the `metatype` property as well so I can do something with the annotated class.

I've tried various different type annotations on the method as well as applying the Pipe in different locations (Controller level, Method level, directly on the custom decorator) and haven't managed to get access to metatype.

## Current behavior
Pipes run for Custom Decorators but don't provide access to metatype

## Expected behavior
Pipes provide access to the all relevant properties of ArgumentMetadata when used with Custom Decorators

## Environment
I tried this against Nest 6 and Nest 7 and see the same behavior for each.

I've created a repro with v7 here https://github.com/WonderPanda/nestjs-custom-decorators-and-pipes.

Hitting the AppController endpoint will cause the Pipe to run which logs it's arguments. The output is always only `{"type":"custom"}`

**Comment by kamilmysliwiec** [comment]
I'll look into this one asap

**Comment by kamilmysliwiec** [comment]
@WonderPanda I've cloned your repository locally and everything seems to work fine. One key thing is - `JSON.stringify(metadata)` doesn't serialize function references (and neither do classes). Simply replace it with:

```
console.log(JSON.stringify(metadata), metadata);
```

and you'll see the metatype ref:

![image](https://user-images.githubusercontent.com/23244943/81660744-6bc0cc00-943b-11ea-9ae4-254dfe9ea650.png)

**Comment by WonderPanda** [comment]
:facepalm: I'm totally aware of this behavior too. Lesson learned: don't open issues in the morning when you're tired

Thanks for looking at it

**Comment by hygison** [comment]
I could solve that by making a guard to change the request and add a typeORM entity depending on some specific decorator.

MY problem: 
I want to pass a typeORM entity from the controller to the Pipe dynamically. The pipe would be used all over the application for multiple request, to validate. I want to have a decorator on the controller that will get the Entity I am referring it too and use it 

For that I am adding a decorator on my controller:

```ts
@DynamicPipeForId(Restaurant)
export class RestaurantController extends JsonBaseController<Restaurant> {
```
The process will be:

- Make a Decorator / Metadata will be passed within the request object
- Make a Guard to get the metadata and bind the desired object (In my case typeORM entity) to the request object.
- Access the request object from the pipe and find the metadata you had previously set.

My Decorator to pass the metadata. Here I am passing a typeORM entity.
```ts
export const TargetEntityPipeId = (entity: Entity): CustomDecorator => SetMetadata(TARGET_ENTITY_PIPE_ID_KEY, entity);
```

Guard:
I don't want to make any checks. I just want to have some decorators I can add anywhere and they will be responsible for setting the meta on the request. In this case I am showing I am only setting one value, but I use the same guard to set multiple values to be available on the request object.
```ts
@Injectable()
export class DynamicGuard implements CanActivate {
	constructor(private reflector: Reflector) {}

	canActivate(context: ExecutionContext): boolean | Promise<boolean> | Observable<boolean> {
		const request = context.switchToHttp().getRequest();
		const entity = this.reflector.getAllAndOverride(TARGET_ENTITY_PIPE_ID_KEY, [
			context.getHandler(),
			context.getClass(),
		]);
		request[TARGET_ENTITY_PIPE_ID_KEY] = entity;
		return true; // I don't make any checks
	}
}
```

PIPE:
As you can see here, I am getting the request and collecting the `user` that I have set in the jwt guard. But what you should pay attention in the `entityClass` that I am able to access as well.
```ts
@Injectable()
export class IdCheckPipe implements PipeTransform {
	constructor(
		@Inject(REQUEST) private readonly request: Request,
		@InjectDataSource() private readonly connection: Connection,
	) {}

	async transform(value: any) {
		const user: ActiveUserData = await this.request[REQUEST_USER_KEY];
		const entityClass = await this.request[TARGET_ENTITY_PIPE_ID_KEY];
		try {
			await securityModifier(entityClass)?.canAccessId(user, value, this.connection);
		} catch (e) {
			throw new NotFoundException(`Not found id = ${value}`);
		}
		return value;
	}
}
```
