### ISSUE TITLE
How nestjs design friendly use worker_threads

### ISSUE THREAD

**Issue by zjy01** [nestjs/nest#4762]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

I need to use `worker_threads` in my projects.

``` ts
// some.service.ts
import { Worker } from "worker_threads";
const worker = new Worker('./worker/data.worker.ts');
```
```ts
// ./worker/data.worker.ts
import func from '../utils/functions';
// ...
```

In this way, i found that the webpack bundle file : `main.js` not contain `./worker/data.worker.ts` content, and can‘t find any relative bundle file.

Of course, I can use `tsc` to compile `./worker/*`, but it has many import file in `app`, I don't know if this is a good idea.

**Comment by kamilmysliwiec** [comment]
The worker threads usage (with TypeScript) is not specifically related to NestJS.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) or StackOverflow for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by wcldyx** [comment]
### 1.Webpack Configuration Add Rules 
```javascript 

 {
        test: /\.worker\.ts$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'file-loader',
            options: {
              outputPath: 'worker',
              name: '[name].[hash:8].js',
            },
          },
          {
            loader: 'ts-loader',
          },
        ],
      },
      {
        test: /\.ts$/,
        use: 'ts-loader',
        exclude: [/node_modules/, /\.worker\.ts$/],
      },
```
### 2.
```typescript 
import mypath from './test.worker';
import { Worker } from 'worker_threads';
import { resolve } from 'path';
const filePath = resolve(__dirname, mypath);
const runSerice = (workerData) => {
  return new Promise((resolve, reject) => {
    const worker = new Worker(filePath, { workerData });

    worker.on('message', resolve);

    worker.on('error', reject);

    worker.on('exit', (code) => {
      if (code !== 0) reject(new Error(`Worker Thread stopped with exit code ${code}`));
    });
  });
};

const run = async () => {
  const result = await runSerice('Tunde Ednut');

  console.log(result);
};
```
