### ISSUE TITLE
HTTPModule - Socket hangs up when using keepAlive on HTTPS agent

### ISSUE THREAD

**Issue by viniciusjssouza** [nestjs/nest#4767]
I am using the Nest.js `HTTPModule` to reach out an external API. Due to the large amount of requests, I tried to use https.Agent with `{ keepAlive: true }` option but, after that, I started receiving socket hang up error responses **every other request**. When I turn off persistent connections ({ keepAlive: false }), it works again.

Also, I tried to use axios directly with the same agent and keepAlive enabled, and it worked perfectly. It really seems to be an issue with the nest.js HttpModule involving persistent connections on TLS sockets.

Configuration:
```
// HttpsAgent from agentkeepalive library
const keepAliveAgent = new HttpsAgent({
  maxSockets: 100,
  keepAlive: true,
  maxFreeSockets: 10,
  timeout: 60000,
  freeSocketTimeout: 30000
});

export const HTTP_CLIENT_CONFIG = {
  timeout: 15000,
  maxRedirects: 5,
  httpAgent: new http.Agent({ keepAlive: true }),
  httpsAgent: keepAliveAgent,
};
// On my module:
imports: [
  HttpModule.register(HTTP_CLIENT_CONFIG)
]
```

Nest.js version: 6.10.14
Stack trace:

```
Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at TLSSocket.socketCloseListener (_http_client.js:373:25)
    at TLSSocket.emit (events.js:203:15)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at _handle.close (net.js:607:12)
    at TCP.done (_tls_wrap.js:388:7)
```
Code: `ECONNRESET`

Node versions:
  - v10.19.0
  - v12.15.0

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by BitPatty** [comment]
This is definitely a bug. It only happens when using the NestJS HttpModule. Currently a custom HttpModule is required to use keep-alive with the https agent.

Node 12.16.1, Nest 6.13.4

**Comment by jmcdo29** [comment]
@BitPatty if it is a bug, please provide a minimum reproduction repository to show the functionality that is happening. Make sure you are using the latest version of Nest as well (I see you're on 6.11.5, 7.3.0 was just released today)

**Comment by BitPatty** [comment]
Alright, I couldn't reproduce it on 7.4.0 with a quick hello world project. Will report back if the issue appears again on the current version. 👍

**Comment by RyanAtWare2Go** [comment]
Did anyone ever figure out what in Nest 7 fixed this?

**Comment by MFrat** [comment]
I'm also facing this issue. Happens in my qa environment but does not in localhost. When i stopped using HttpModule and started using axios purely, things just worked fine.
