### ISSUE TITLE
what the ClientRMQ class expected to use，how to simply bind an handler to consume

### ISSUE THREAD

**Issue by rawbin-** [nestjs/nest#4773]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

**Comment by rawbin-** [comment]
I extend the ClientRMQ classs, and rewrite the createChannel method not allowed by grammer, and add an new method cannot be called

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
