### ISSUE TITLE
HTTP error message switching

### ISSUE THREAD

**Issue by WillSquire** [nestjs/nest#4776]
## Current behavior
Not sure if this is intentional or not, but after migrating for 6.X to 7.X the exception error messages seem to swap from `message` to `error` depending on if a custom error message is passed. The migration guide says it follows the same structure now, but this seems to go against the grain a bit.

## Input Code
```ts
throw new ConflictException('Email address has already been registered.')
```
returns
```
{
  "statusCode": 409,
  "message": "Email address has already been registered.",
  "error": "Conflict"
}
```

But
```ts
throw new ConflictException()
```
returns
```
{
  "statusCode": 409,
  "message": "Conflict",
}
```
Which is irritating as the HTTP error name flips between either `error` or `message`.

## Expected behavior
I'd expect "Conflict" to always be assigned to `error` and `message` to be optional (depending if it was set). Makes typing and testing the response easier to follow.

## Possible Solution
Same as above.

## Environment

<pre><code>
Nest version: "@nestjs/common": "^7.0.9"
</code></pre>

**Comment by getspooky** [comment]
Hi @WillSquire 
I think that the result must be : 
```
{
  "statusCode": 409,
  "message": "Conflict",
  "error": "Conflict"
}
```

**Comment by WillSquire** [comment]
Nope, it’s just ‘statusCode’ and ‘message’. Or do you mean as a proposal? Personally I’d like it to be ‘undefined’ if it’s not set to keep them distinctly separated. The custom messages I show on the front end as “User friendly” overrides (if set).

**Comment by kamilmysliwiec** [comment]
This has been discussed a few times in the past already. The current behavior is expected.

Please, search for similar issues.
