### ISSUE TITLE
How can I become sponsor by PayPal

### ISSUE THREAD

**Issue by RezaRahmati** [nestjs/nest#478]
Hello

I would like to support nest.js because I think it's great and worth it, but I want to do it through Paypal, how can I do that?

Sorry to post it here, there were no place to comment on website

**Comment by kamilmysliwiec** [comment]
Hi @RezaRahmati,
Please, send me an email at support@nestjs.com or post yours that I can use to contact you. 🙂 Also, I'll provide more details in the documentation about different ways of supporting nest as soon as possible.
