### ISSUE TITLE
Getting an instance anywhere (TypeDI "Container" like)

### ISSUE THREAD

**Issue by LeandroDoldan** [nestjs/nest#4789]
## Feature Request

I've been using TypeDI for a long time and moved to Nest the second I found it. I've been looking for a way to accomplish the following since I started using it, but I've always found a workaround for it. Not this time. And honestly, my life would have been way easier if it existed before.

## Is your feature request related to a problem? Please describe.
We are using TypeORM. We need to connect to multiple databases dynamically. We don't even know the name of the DB until runtime. We have a method that creates connections on the go, using some base settings. These settings are an object of the type `ConnectionOptions`.

One of the properties of the object is `logger`, which expects an instance of a class implementing a certain interface.

My entire file is the following:
```
export const typeORMConfig: ConnectionOptions = {
  logger: TYPEORM_LOGGER_ENABLED ? new AppLogger() : undefined,
 [...]
  host,
  port,
  username,
  password
};
```

Being AppLogger an `injectable` class.

The problem, however, is that I need to inject some dependencies to AppLogger. So I cannot use `new` anymore.

## Describe the solution you'd like
I'd love to do the same I do in TypeDI, or something similar. Either a class or a function:
```
export const typeORMConfig: ConnectionOptions = {
  logger: TYPEORM_LOGGER_ENABLED ? Container.get(AppLogger) : undefined,
 [...]
  host,
  port,
  username,
  password
};
```

Drawbacks? None that I'm aware of, regarding architecture.

**Comment by kamilmysliwiec** [comment]
I'm not sure where you define the `typeORMConfig` and how you use it (and what's your use-case). Without context, it's quite hard to help you. 

Perhaps the following chapters can help you somehow:
- https://docs.nestjs.com/standalone-applications
- https://docs.nestjs.com/fundamentals/module-ref
(not sure which one though, since we don't really know what you want to achieve)

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by LeandroDoldan** [comment]
@kamilmysliwiec Sorry, I didn't do a good job expressing myself, but this issue is a feature request. I already explained both the use case and the problem on Discord, and the solution is way more verbose than the one I'm proposing here.

I need to connect to databases dynamically, so I have a file exporting the base settings. One of those settings is an instance of a logger.

My file is not a class, so the best I can do is in `main.ts` export the variable `app`, and do the following:

```
export const typeORMConfig: ConnectionOptions = {
  logger: TYPEORM_LOGGER_ENABLED ? app.get(AppLogger) : undefined,
 [...]
};
```

Besides my specific use case, it'd be a really useful feature to have.

**Comment by kamilmysliwiec** [comment]
> @kamilmysliwiec Sorry, I didn't do a good job expressing myself, but this issue is a feature request. I already explained both the use case and the problem on Discord, and the solution is way more verbose than the one I'm proposing here.

As for the container available globally, this has been discussed many times in the past and we don't plan to change the current behavior (see old issues for further information). This change would simply break many other existing features and would collide with the whole concept & design assumptions of NestJS.
