### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by krystofrezac** [nestjs/nest#4795]
## Bug Report
In my `ShiftWeekService` I am trying to inject `UserService` in the constructor:
```ts
constructor(
    @InjectRepository(ShiftWeek)
    private readonly shiftWeekRepository: Repository<ShiftWeek>,
    private readonly userService: UserService,
  ) {}
```
But then nestjs starts complainng: `Nest can't resolve dependencies of the ShiftWeekService (ShiftWeekRepository, ?). Please make sure that the argument dependency at index [1] is available in the ShiftWeekModule context.`

But my `ShiftWeekModule` imports the `UserModule`:
```ts
@Module({
  imports: [
    TypeOrmModule.forFeature([ShiftWeek]),
    forwardRef(() => AuthModule),
    forwardRef(() => ShiftWeekTemplateModule),
    forwardRef(() => UserModule),
  ],
  providers: [ShiftWeekService, ShiftWeekResolver],
  exports: [ShiftWeekService],
})
class ShiftWeekModule {}
```

And `UserModule` exports `UserService`:
```ts
@Module({
  imports: [
    TypeOrmModule.forFeature([User]),
    forwardRef(() => AuthModule),
    RoleModule,
    forwardRef(() => BranchModule),
    ShiftRoleTypeModule,
    forwardRef(() => ShiftRoleModule),
    GlobalSettingsModule,
    EmailModule,
  ],
  providers: [UserResolver, UserPaginatorResolver, UserService],
  exports: [UserService],
})
```
It's weird beacause I use `UserService` in many other modules and there it's working.
## Current behavior

It throws error message: `Nest can't resolve dependencies of the ShiftWeekService (ShiftWeekRepository, ?). Please make sure that the argument dependency at index [1] is available in the ShiftWeekModule context.`

## Expected behavior
I would expect not to throw error.

## Environment
I tried to update to newest version of `@nestjs/core` and it was throwing the same error message.

<pre><code>
@nestjs/core version: 6.11.1
 
For Tooling issues:
- Node version: 12.14
- Platform: Linux

**Comment by kamilmysliwiec** [comment]
Based on the code sample you provided, I assume you have several circular dependencies in your applications. If Nest cannot resolve your dependency, `UserService` is very likely represented as `undefined` due to some circular imports. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
