### ISSUE TITLE
Validate Headers

### ISSUE THREAD

**Issue by cosinus84** [nestjs/nest#4798]
It will be useful to validate headers along with all Body, Query etc. Is not always about keys and tokens so that you use a `guard`, there can also be other values that you want to use in headers for some methods. Taking advantage of class-validator, transforms and `DTO` that nestjs is promoting

`@Headers("x-lang", LangPipe, CustomValidationPipe) langDto LangDto; `

Thanks

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/356#issuecomment-357698382

**Comment by SpartanX1** [comment]
.

**Comment by SpartanX1** [comment]
Leaving it here in case someone needs it. As said by @kamilmysliwiec , a custom decorator can be used for validating the headers. (In the same way we validate req body ! )
#### request-header.dto.ts
```

import { createParamDecorator, ExecutionContext } from '@nestjs/commom'
import { plainToClass } from 'class-transformer';
import { ClassType } from 'class-transformer/ClassTransformer';
import { validateOrReject } from 'class-validator';

export const RequestHeader = createParamDecorator(
  async (value:  ClassType<unknown>, ctx: ExecutionContext) => {

    // extract headers
    const headers = ctx.switchToHttp().getRequest().headers;

    // Convert headers to DTO object
    const dto = plainToClass(value, headers, { excludeExtraneousValues: true });
    
    // Validate 
    await validateOrReject(dto);

    // return header dto object 
    return dto;
  },
);
```

Define your header dto according to the headers which would be coming
#### header.dto.ts
```
import { IsDefined, IsString } from "class-validator";

export class HeaderDTO {
    @IsString()
    @IsDefined()
    myHeader1: string;

    @IsString()
    @IsDefined()
    myHeader2: string;
}
```
Finally use it as a method param and pass the dto you want to validate against :) 
```
 @Get('/hello')
 getHello(@RequestHeader(HeaderDTO) headers: any) {
        console.log(headers);
    }
}
```

**Comment by bloigge** [comment]
Wouldn't it better to throw an error in case the validation fails?

`export const RequestHeader = createParamDecorator(
  async (value:  any, ctx: ExecutionContext) => {

    // extract headers
    const headers = ctx.switchToHttp().getRequest().headers;

    // Convert headers to DTO object
    const dto = plainToClass(value, headers, { excludeExtraneousValues: true });
    
    // Validate 
    return validateOrReject(dto).then(
      (res) => {
        return dto;
      },
      (err) => {
        throw new HttpException({
          status: HttpStatus.FORBIDDEN,
          error: "Missing Authorization Header"
        }, HttpStatus.FORBIDDEN);
      }
    );    
  },
);`

**Comment by rluvaton** [comment]
If you wanna let the `ValidationPipe` handle the validation and the transformation (which I think it's the best option), use this:

```ts
// request-headers.decorator.ts
import { createParamDecorator, ExecutionContext } from '@nestjs/common';

export const RequestHeaders = createParamDecorator(
  async (property: string | number | symbol, ctx: ExecutionContext) => {
    const headers = ctx.switchToHttp().getRequest().headers;

    if (
      typeof property === 'string' ||
      typeof property === 'number' ||
      typeof property === 'symbol'
    ) {
      return headers[property];
    }

    return headers;
  },
);
```

And in your Controller:
```ts
// app.controller.ts

import { Controller, Get, Headers, ValidationPipe } from '@nestjs/common';
import { AppService } from './app.service';
import { RequestHeaders } from './request-headers.decorator';

import { TestHeaderDto } from './app.dto';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('/')
  getHello(
     // Add this:
    @RequestHeaders(new ValidationPipe({ validateCustomDecorators: true }))
    headers: TestHeaderDto,
  ): string {
    console.log({ headers });
    return this.appService.getHello();
  }
}
```

and if you have [`ValidationPipe` globally enabled](https://docs.nestjs.com/pipes#global-scoped-pipes), you can do this:
```ts
// main.ts
async function bootstrap() {
  // ... 
  app.useGlobalPipes(
    new ValidationPipe({
      validateCustomDecorators: true // <-- Add this to allow the validation pipe to work with our custom decorator
    })
  );
  // ...
}
bootstrap();


// app.controller.ts

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('/')
  getHello(@RequestHeaders() headers: TestHeaderDto): string {
    console.log({ headers });
    return this.appService.getHello();
  }
}
```

**Comment by juanpablopiano** [comment]
> If you wanna let the `ValidationPipe` handle the validation and the transformation (which I think it's the best option), use this:
> 
> ```ts
> // request-headers.decorator.ts
> import { createParamDecorator, ExecutionContext } from '@nestjs/common';
> 
> export const RequestHeaders = createParamDecorator(
>   async (property: string | number | symbol, ctx: ExecutionContext) => {
>     const headers = ctx.switchToHttp().getRequest().headers;
> 
>     if (
>       typeof property === 'string' ||
>       typeof property === 'number' ||
>       typeof property === 'symbol'
>     ) {
>       return headers[property];
>     }
> 
>     return headers;
>   },
> );
> ```
@rluvaton I tried this, but what do I have to pass as a DTO if I only wanted to validate one header? As if I pass a 'property' in decorator call?
