### ISSUE TITLE
[Microservices] Move from grpc to @grpc/grpc-js package

### ISSUE THREAD

**Issue by gperdomor** [nestjs/nest#4799]
## Feature Request

According to official grpc page, a new `@grpc/grpc-js` package is released, the old `grpc` will be deprecated... More info [here](https://grpc.io/blog/grpc-js-1.0/)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue :)?

**Comment by ssilve1989** [comment]
Any update on this? Looks like the PR just has small conflicts to resolve?

**Comment by gperdomor** [comment]
@ssilve1989 PR updated :D

**Comment by adematte** [comment]
so according to the linked issue, this should be shipped on the next major version of NestJS since this introduces a breaking change. Any plans yet for when the next version will come out?

**Comment by dranzboi** [comment]
guys, when will you release a new version with grpc-js?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/4806
