### ISSUE TITLE
What's the right way to  holding configuration for multi-env?

### ISSUE THREAD

**Issue by janckerchen** [nestjs/nest#480]
hold  env config  like: ip, port, db, ....
```
config/
dev.ts
prod.ts
test.ts
```

I have multi modules in project,   should I create a shared module to hold env config?

**Comment by rmvermeulen** [comment]
If I understand correctly, maybe this can help https://www.npmjs.com/package/config

**Comment by cojack** [comment]
@janckerchen Im handling this by this example: https://github.com/cojack/ts-config

**Comment by darioxtx** [comment]
I'm using https://github.com/mozilla/node-convict

**Comment by kamilmysliwiec** [comment]
Additionally, you can do it in more nest-way, using custom providers. Example:
```typescript
provide: ConfigService,
useClass: process.env.NODE_ENV === 'development' 
     ? DevelopmentConfigService 
     : ProductionConfigService
```
where `ConfigService` is an `abstract` class and both `DevelopmentConfigService` and `ProductionConfigService` extends `ConfigService`.

**Comment by janckerchen** [comment]
thx @kamilmysliwiec .  I found there are three ways to spread config to multi modules.

1.  pass config to  anymodule.forRoot(config).  it's a static way,  config is passed before module creation and  some provider factories will consume the config data.
2.  inject configService to any other component like @kamilmysliwiec mentioned above.config is passed before component creation.
3.  pass config to AnyService.Init(config) in module's constructor, because any component belongs to the module can be inject to  module's constructor. At this time, component has been created.

I switched from rails,   I expected  proper nest-way to manage config.

**Comment by trainerbill** [comment]
Are there plans to build @kamilmysliwiec recommendation into the framework?

**Comment by neilime** [comment]
And what about https://github.com/nestjs-community/nestjs-config ?

**Comment by maximpyshko** [comment]
Try https://github.com/maximpyshko/neconfig
