### ISSUE TITLE
tslib regression

### ISSUE THREAD

**Issue by dyatko** [nestjs/nest#4801]
## Regression

tslib@1.12.0 breaks typeorm
https://github.com/microsoft/tslib/issues/107

## Describe the regression

```
TypeError: Cannot set property EntityManager of #<Object> which has only a getter
```

https://stackoverflow.com/questions/61781357/typeerror-cannot-set-property-entitymanager-of-object-which-has-only-a-gette

## Environment
<pre><code>
Nest version: 7.0.9 -> 7.0.11

For Tooling issues:
- Node version: 12.16.2
- Platform: Amazon Linux 4.14.3

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed https://github.com/microsoft/tslib/issues/102#issuecomment-628296863
