### ISSUE TITLE
Unable to get request parameters using Post request

### ISSUE THREAD

**Issue by chico-malo** [nestjs/nest#4805]
## Bug Report
I ’m going crazy, I can’t get the parameters in the POST request, it ’s all printed out {}

## Current behavior

Projects built with cli
1.service
```
 @Post('login')
    userLogin(@Body() user: { account: string, password: string }): string {
        console.log('user', user);
        if (user.account === 'admin' && user.password === '12345') {
            return 'success';
        } else {
            return 'failed';
        }
    }
```
2.result
Data return user {}, Request to return  failed

## Expected behavior

1.Returns the parameters in the body。
2.Give me the dom that I can run. I've tried other people's dom, tried the official dom... None of this works. I've searched for other problems, and I can't introduce ValidationPipe either. Thank you very much

## Possible Solution

I didn't know

## Environment

<pre><code>
Nest version: 7.1.5

 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) or StackOverflow for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
