### ISSUE TITLE
Simple Gateway set up is not working out-of-the-box.

### ISSUE THREAD

**Issue by andrisole92** [nestjs/nest#4809]
## Current behavior
Registering a new Gateway. Getting error: `VM27574:1 GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=N8PrIhm net::ERR_CONNECTION_REFUSED`

## Input Code
Minimum set up.

Gateway code:

```ts
import {
    OnGatewayConnection,
    OnGatewayDisconnect,
    OnGatewayInit,
    SubscribeMessage,
    WebSocketGateway
} from '@nestjs/websockets';
import {Logger} from "@nestjs/common";

@WebSocketGateway({namespace: 'events'})
export class SignallingGateway implements OnGatewayConnection, OnGatewayInit, OnGatewayDisconnect {
    @SubscribeMessage('message')
    handleMessage(client: any, payload: any): string {
        return 'Hello world!';
    }

    handleConnection(client: any, ...args: any[]): any {
        Logger.log(client);
    }

    afterInit(server: any): any {
        Logger.log('SignallingGateway initialized');
    }

    handleDisconnect(client: any): any {
        Logger.log(`ClientDisconnect: ${client}`)
    }
}

```

## Expected behavior
Expected to connect while using: `io('localhost:3000')`

## Possible Solution
Not sure as of yet.

<pre><code>
Nest version: 7.0.0
 
For Tooling issues:
- Node version: 10.19
- Platform:  Mac

Others:
Thank you so much for helping me!

**Comment by jmcdo29** [comment]
You're using a namespace for your Gateway. [You need to connect using a namespace according to Socket.IO's documentation](https://socket.io/docs/rooms-and-namespaces/). 

Please use our [Discord](https://discord.gg/nestjs) for support questions. We are using GitHub to track bugs and feature requests.
