### ISSUE TITLE
How to  create dynamic  component with init params like Module.forRoot()?

### ISSUE THREAD

**Issue by janckerchen** [nestjs/nest#481]

**Comment by janckerchen** [comment]
I found offical doc in 'Dependency Injection' chapter.

**Comment by jamesliauw** [comment]
@Module({
	imports: [CommonModule],
	controllers: [ConfigController],
	providers: [{
		provide: ConfigService,
		useValue: new ConfigService(new BaseConfig().getInstance())
	}],
	exports: [ConfigService],
})
export class ConfigModule {}
