### ISSUE TITLE
Documentation for Rest/Graphql-Crud

### ISSUE THREAD

**Issue by renehauck** [nestjs/nest#4810]
## Feature Request
Documentation for Rest/Graphql-Crud

## Is your feature request related to a problem? Please describe.

There are very good microframeworks that make CRUD(create, read, update, delete) extremely easy. Unfortunately you won't find anything in the official documentation. :confused:

## Describe the solution you'd like

There should at least be a note in the documentation that you can save a lot of time with these CRUD frameworks. For example, for REST my choice would be "https://github.com/nestjsx/crud" and for graphql "https://github.com/doug-martin/nestjs-query". 

## What is the motivation / use case for changing the behavior?

Especially for beginners, who don't know the potential of nestjs yet and write their whole API "by hand" and realize at the end of the project that they could have saved a lot of time, this would be a great achievement :-D.

Many thanks for this great framework!

**Comment by kamilmysliwiec** [comment]
> There are very good microframeworks that make CRUD(create, read, update, delete) extremely easy. Unfortunately you won't find anything in the official documentation. 😕

Both libraries are built by the community, not the NestJS core team. They are not maintained under the official organization, and so, they're not mentioned in the docs.

**Comment by renehauck** [comment]
is it already planned to implement an official CRUD system?

**Comment by jlarmstrongiv** [comment]
I’m curious if there will be an official CRUD system in the future too 😄
