### ISSUE TITLE
Enterprise support

### ISSUE THREAD

**Issue by JiProchazka** [nestjs/nest#4811]
Hi,
I'm interested in an enterprise support, but I'm not able to reach anyone. Could someone contact me, pls?
Thanks

**Comment by kamilmysliwiec** [comment]
If we didn't reply, it means we're very busy. Pinging us everywhere won't help. We'll respond as soon as we have enough time.

**Comment by JiProchazka** [comment]
Seriously? You are so busy you can't answer one email? At least - we got your email, but we are busy now, we will handle it within a week/month/year? That is meant to be an enterprise support?
I like your product, but in that case this is not an enterprise support we can rely on in our company..
I want to pay you and I'm not even sure my e-mail didn't end up in a spam.
