### ISSUE TITLE
Cant get response object on exception filter using NestFastifyApplication (not express)

### ISSUE THREAD

**Issue by rizesky** [nestjs/nest#4812]
Hi, everyone

im trying to return the response.status().json() from exception filters of nestjs,

```javascript
@Catch(UserNotFoundException)
export class UserNotFoundExceptionFilter implements ExceptionFilter {
  catch(exception: UserNotFoundException, host: ArgumentsHost) {
    const errorResponse = new ErrorResponse<string[]>();
    const response = host.switchToHttp().getResponse();
    errorResponse.message = 'unauthorized exception'
    errorResponse.errors = [
      'invalid username or pass'
    ];
    response.status(401).json(errorResponse)

  }
}
```
I got error, saying that the response.status().json() is not a valid function: 
```javascript
[Nest] 5400   - 05/17/2020, 00:27:26   [ExceptionsHandler] response.status(...).json is not a function +82263ms
TypeError: response.status(...).json is not a function
```

I believe that it is happen because <b>response.status().json()</b> is kind of response object from <b>express</b> as i read on nestjs docs,while im using the nestjs using fastify.

previously , i already try adding the Response object from express:
```javascript
import { Response } from 'express';
```
and change my code on the exception filter as following:
```javascript
 const response = host.switchToHttp().getResponse<Response>();
```
and everything running smooth. but, i dont want to add more depedencies to my code, and want to go just with nest fastify.

what object in nest fastify  i can used as alternative to this <b>Response</b> object from express?
or do you guys have another clever way to tackle this ? , please suggest

Thanks everyone

**Comment by jmcdo29** [comment]
Fastify has a different response object than Express does. You're looking for FastifyReply.

Please use our [Discord](https://discord.gg/nestjs) for support questions. We are using GitHub to track bugs and feature requests.

**Comment by kamilmysliwiec** [comment]
The `.status()` method doesn't exist on the `FastifyReply` object (exported from the `fastify` package).
