### ISSUE TITLE
GRPC Date handling error

### ISSUE THREAD

**Issue by jessequinn** [nestjs/nest#4815]
## Current behavior
Date handling by GRPC when defined as `google.protobuf.timestamp` returns an empty object.

## Input Code
A quick example of a proto file:

```proto
message ExampleWithTimestamps {
  google.protobuf.Timestamp programStart = 1;
  google.protobuf.Timestamp programEnd = 2;
}
```

The typescript:

```ts
export interface ExampleWithTimestamps {
  programStart: Date;
  programEnd: Date;
}
```
## Expected behavior
The expected behaviour would be that a Date object is passed.

## Possible Solution
My current solution, which i do no support, is to use strings, and convert said strings to dates within the service.

## Environment

<pre><code>
Nest version: 7.0.13

"@grpc/proto-loader": "^0.5.4",
"@nestjs/common": "^7.0.13",
"@nestjs/core": "^7.0.13",
"@nestjs/microservices": "^7.0.13",
"@nestjs/platform-express": "^7.0.13",
 
For Tooling issues:
- Node version: v14.1.0
- Platform:  Mac

Others:
N/A
</code></pre>

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be directly related to NestJS. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by YonatanHanan** [comment]
Was there a solution?

**Comment by sneaker102** [comment]
Same is happening to me

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
