### ISSUE TITLE
[nestjs-grpc] max_pings_without_data cannot set to 0

### ISSUE THREAD

**Issue by Jekiwijaya** [nestjs/nest#4816]
## Current behavior
`http2MaxPingsWithoutData: 0` is ignored, my app sometimes always return too many pings

## Input Code
I think because of this
https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-grpc.ts#L128

## Expected behavior
```
if (key === undefined) {
    continue;
}
```

## Environment

<pre><code>
Nest version: ^6.13.2

 
For Tooling issues:
- Node version: v10.16.1
- Platform:  Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 7.1.0.
