### ISSUE TITLE
Clearer Default Error Reporting from ServerMqtt, e.g. for MQTT.js Error Code 5 Currently Not Receiving An Accompanying Error Message From The Wrapper MQTT.js Library Explaining What Error Code 5 Is

### ISSUE THREAD

**Issue by dcs3spp** [nestjs/nest#4821]
## Is your feature request related to a problem? Please describe.

Trying to learn MQTT with NestJS. Have implemented a custom server:

``` ts
import { MessageHandler } from '@nestjs/microservices/interfaces';
import { ServerMqtt } from '@nestjs/microservices/server';


const MQTT_SEPARATOR = '/';
const MQTT_WILDCARD_ALL = '#';
const MQTT_WILDCARD_SINGLE = '+';

/**
 * Custom MQTT Server with added pattern matching for event topics.
 * Currently, pull request #2954 of @nestjs/microservices addresses this
 * feature. Awaiting this to be merged.
 * In the meantime this is the suggested workaround.
 */
export class CustomServerMqtt extends ServerMqtt {

    public getHandlerByPattern(pattern: string): MessageHandler | null {

        if (this.messageHandlers.has(pattern)) {
            return this.messageHandlers.get(pattern);
        }

        for (const [key, value] of this.messageHandlers) {
            if ((key.indexOf(MQTT_WILDCARD_SINGLE) !== -1
                || key.indexOf(MQTT_WILDCARD_ALL) !== -1)
                && this.matches(key, pattern)) {
                return value;
            }
        }

        return null;
    }

    public matches(pattern: string, topic: string) {
        const patternSegments = pattern.split(MQTT_SEPARATOR);
        const topicSegments = topic.split(MQTT_SEPARATOR);
        const patternLength = patternSegments.length;
        const topicLength = topicSegments.length;
        const lastIndex = patternLength - 1;
    
        for (let i = 0; i < patternLength; i++) {
          const currentPattern = patternSegments[i];
          const patternChar = currentPattern[0];
          const currentTopic = topicSegments[i];
    
          if (!currentTopic && !currentPattern) continue;
    
          if (!currentTopic && currentPattern !== MQTT_WILDCARD_ALL) return false;
    
          if (patternChar === MQTT_WILDCARD_ALL) return i === lastIndex;
    
          if (
            patternChar !== MQTT_WILDCARD_SINGLE &&
            currentPattern !== currentTopic
          )
            return false;
        }
    
        return patternLength === topicLength;
      }

      public handleError(stream: any) {
        stream.on('error', (err: any) => this.logger.error(`MQTT Server encountered an error => ${JSON.stringify(err)}`));
      }
}
```

[handleError](https://github.com/nestjs/nest/blob/baadb3f92593da397952060ec868bb27b9c766bf/packages/microservices/server/server-mqtt.ts#L196) is overriden. Recently, repeated logs of error code 5 were reported upon starting a microservice:

{"level":50,"time":1589887906325,"pid":6556,"hostname":"host","context":"Server","trace":"","msg": {\"code\":5}","v":1}
{"level":50,"time":1589887907340,"pid":6556,"hostname":"hosti","context":"Server","trace":"","msg":{\"code\":5}","v":1}

Through overriding the error handler, discovered that this error log originates from [handleError](https://github.com/nestjs/nest/blob/baadb3f92593da397952060ec868bb27b9c766bf/packages/microservices/server/server-mqtt.ts#L196). 

The context gave some information relating to the source of the error. After looking through the source code Server is a base class for MqttServer. It looks as though MqttServer wraps the MQTT.js which, for some reason is only reporting an error code (5) and not the accompanying error message. Upon inspecting the source code for MQTT.js I found that error code [5](https://github.com/mqttjs/MQTT.js/blob/2980e96bb472a3132c3d8850f6d0c73f93513b6a/lib/client.js#L39) relates to authorisation.

## Describe the solution you'd like

Provide an error message to accompany the [error codes](https://github.com/mqttjs/MQTT.js/blob/2980e96bb472a3132c3d8850f6d0c73f93513b6a/lib/client.js#L39)  reported by [MQTT.js](https://github.com/mqttjs/MQTT.js/blob/2980e96bb472a3132c3d8850f6d0c73f93513b6a/lib/client.js) in the onError hander of the default ServerMqtt class from the wrapped MQTT.js library.

## Teachability, Documentation, Adoption, Migration Strategy

Default implementation will raise an accompanying error message to facilitate fault finding for developers, as opposed to subclassing and customising.

## What is the motivation / use case for changing the behavior?

Default implementation will raise an error message facilitating fault finding for developers, as opposed to subclassing and customising, saving development time.

**Comment by kamilmysliwiec** [comment]
`ServerMqtt` simply wraps the `mqtt` library and integrates it with Nest execution context. If you think that the default error messages provided by library should be more descriptive (and thus, improve the development experience), please, report it here https://github.com/mqttjs/MQTT.js

**Comment by dcs3spp** [comment]
@kamilmysliwiec thanks...`ServerMqtt` *handleError* currently does not appear to be logging the message in the default implementation, only the code gets logged....see pino log output below:
 
```
{"level":50,"time":1589887906325,"pid":6556,"hostname":"host","context":"Server","trace":"","msg": {"code":5}","v":1}
{"level":50,"time":1589887907340,"pid":6556,"hostname":"hosti","context":"Server","trace":"","msg":{"code":5}","v":1}
```

The default error handler code in `ServerMqtt` that produces this log is:
``` ts
public handleError(stream: any) {
    stream.on(ERROR_EVENT, (err: any) => this.logger.error(err));
  }
```

If I override it with the code below it logs an error code AND message....

```
public handleError(stream: any) {
        stream.on(ERROR_EVENT, (err: any) => {
            if (err.code && !err.message) {
                this.logger.error(`code(${err.code}):error message unavailable`);
            }
            else {
                this.logger.error(`code(${err.code}):${err.message}`);
            }
        });
}
```

Maybe it could be related to the logger in use??? I am using nestjs-pino:

``` ts
import * as fs from 'fs';

import { Logger as NestLogger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

import { Logger } from 'nestjs-pino';

import { AppModule } from './app/app.module';
import { CustomServerMqtt } from './mqtt.server';
import { InboundMessageExternalDeserializer } from './deserializer';

async function bootstrap() {

  if (!validateEnvironment()) {
    console.error(`Exiting server, invalid environment...`);
    return;
  }

  try {
    const microservice = await NestFactory.createMicroservice(AppModule.forRoot(
      { // some app options etc. }),
      {
        logger: false,
        strategy: createMqttServer(),
      },
    );

    const logger: Logger = microservice.get(Logger);
    microservice.useLogger(logger);

    microservice.listen(() => {
      logger.log('Started microservice', 'boostrap');
    });
  }
  catch (err) {
    console.error(`Exception encountered ${err.message} with trace: ${err.trace}`);
    NestLogger.error(`The following error occurred while bootsrapping livecam microservice ${err.message}`, 'bootstrap');
  }
}
```
