### ISSUE TITLE
New Nest.js DenoJS framework 

### ISSUE THREAD

**Issue by Donliang** [nestjs/nest#4832]
I hope there would be a new deno.js framework call nest2.js
Is there any hope?

**Comment by jmcdo29** [comment]
Duplicate of #1796, #3464, and #4495

**Comment by Donliang** [comment]
> Duplicate of #1796, #3464, and #4495

thanks

**Comment by kamilmysliwiec** [comment]
There's simply no reason to migrate to Deno at the moment. First, let's make sure this runtime is battle-tested and production-ready. Once there any major advantages to use Deno instead of Node, we'll provide a compatible version of Nest. This shouldn't take too much time anyway
