### ISSUE TITLE
Run the official Sequelize example but get error

### ISSUE THREAD

**Issue by gyh9457** [nestjs/nest#4835]
## Bug Report
I am learning nestjs and hope to use sequelisze to connect to sqlite database. 

I used the [example](https://github.com/nestjs/nest/tree/master/sample/07-sequelize) provided by the official for testing, but it does not work

## Current behavior
I get an error；
> Nest can't resolve dependencies of the UsersService (UserRepository, ?). Please make sure that the argument Sequelize at index [1] is available in the UsersModule context

![image](https://user-images.githubusercontent.com/13557235/82671485-81bb6180-9c71-11ea-92ff-50da600364dc.png)

## Input Code

Except for the inconsistent code of the database connection, everything else is the same

```ts
  imports: [
    SequelizeModule.forRoot({
      dialect: 'sqlite',
      name: 'user',
      storage: `../db.sqlite`,
      autoLoadModels: true,
      synchronize: true,
    }),
    UsersModule,
  ],
```

## Expected behavior

The code runs normally

## Environment
Node 10.15.0
nestjs/core 7.0.0
sequelize: 5.21.10
sequelize-typescript: 1.1.0
sqlite3: 4.2.0

**Comment by rizesky** [comment]
u need to also create an instance of userRepo that required to be injected to your user service,

import Sequelize.forFeature([array of repo models here]) on your userModule

**Comment by gyh9457** [comment]
@rizesky  I think i have done.

![image](https://user-images.githubusercontent.com/13557235/82680413-cdc0d300-9c7e-11ea-9390-a576389c562c.png)

there is a reproduce demo here [demo](https://github.com/gyh9457/sequelize-sqlite)

**Comment by rizesky** [comment]
I think there is some misconfiguration in your sequelize module.
I try commenting 'name' and add database , it works fine now on my machine:


```javascript
SequelizeModule.forRoot({
      dialect: 'sqlite',
      database:'user',
      // name: 'user',
      storage: `../db.sqlite`,
      autoLoadModels: true,
      synchronize: true,
    }),
    UsersModule,
```


```javascript
[Nest] 8004   - 05/22/2020, 22:58:47   [NestFactory] Starting Nest application...
[Nest] 8004   - 05/22/2020, 22:58:47   [InstanceLoader] AppModule dependencies initialized +86ms
[Nest] 8004   - 05/22/2020, 22:58:47   [InstanceLoader] SequelizeModule dependencies initialized +1ms
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `firstName` VARCHAR(255), `lastName` VARCHAR(255), `isActive` TINYINT(1) DEF
AULT 1, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Users`)
[Nest] 8004   - 05/22/2020, 22:58:47   [InstanceLoader] SequelizeCoreModule dependencies initialized +11ms
[Nest] 8004   - 05/22/2020, 22:58:47   [InstanceLoader] SequelizeModule dependencies initialized +1ms
[Nest] 8004   - 05/22/2020, 22:58:47   [InstanceLoader] UsersModule dependencies initialized +0ms
[Nest] 8004   - 05/22/2020, 22:58:47   [RoutesResolver] UsersController {/users}: +4ms
[Nest] 8004   - 05/22/2020, 22:58:47   [RouterExplorer] Mapped {/users, POST} route +3ms
[Nest] 8004   - 05/22/2020, 22:58:47   [RouterExplorer] Mapped {/users, GET} route +0ms
[Nest] 8004   - 05/22/2020, 22:58:47   [RouterExplorer] Mapped {/users/:id, GET} route +1ms
[Nest] 8004   - 05/22/2020, 22:58:47   [RouterExplorer] Mapped {/users/:id, DELETE} route +1ms
[Nest] 8004   - 05/22/2020, 22:58:47   [NestApplication] Nest application successfully started +2ms

```
hope this helps

**Comment by gyh9457** [comment]
@rizesky Thank you for your help.

**Comment by unicornware** [comment]
for any `@nestjs/sequelize` maintainers that come across this, it would be great if comments were included in the project build. i faced this same issue, but my error came from a misunderstanding of how to use the `name` option. 

the [source code][1] documents what `name` is:

```typescript
import { SequelizeOptions } from 'sequelize-typescript';

export type SequelizeModuleOptions = {
  /**
   * Connection name
   */
  name?: string;
  /**
   * Number of times to retry connecting
   * Default: 10
   */
  retryAttempts?: number;
  /**
   * Delay between connection retry attempts (ms)
   * Default: 3000
   */
  retryDelay?: number;
  /**
   * If `true`, models will be loaded automatically.
   */
  autoLoadModels?: boolean;
  /**
   * If `true`, "sequelize.sync()" will be called.
   * Default: true
   */
  synchronize?: boolean;
} & Partial<SequelizeOptions>;
```

but the project build doesn't include the docs:

![nestjs-sequelize-dist-interfaces-sequelize-options.interface.d.ts](https://user-images.githubusercontent.com/20430108/147799272-f3fed74c-78b9-48f5-aebb-022c5e5a167f.png)

i also searched the `sequelize` docs, but it's possible i missed something! 

additionally:

- leaving the comments in the build would be helpful for those who do a lot of source code diving / tend to search through project distributions during development
- using `@default` where necessary would be useful for vscode users as the tag and value will be displayed with intellisense

[1]: https://github.com/nestjs/sequelize/blob/master/lib/interfaces/sequelize-options.interface.ts#L5

**Comment by jmcdo29** [comment]
@unicornware would you like to make a PR in [nestjs/sequelize](https://github.com/nestjs/sequelize) to set `removeCommetns: false` in the `tsconfig`?

**Comment by unicornware** [comment]
@jmcdo29 i'd be honored! 😄 anything special i need to know about making PRs or is that all documented?

**Comment by jmcdo29** [comment]
@unicornware Just know how to make a PR. Everything else should really be straightforward :)
