### ISSUE TITLE
Unable to authenticate connections to websocket gateways

### ISSUE THREAD

**Issue by Roaders** [nestjs/nest#4841]
## Is your feature request related to a problem? Please describe.
Documentation about how to implement authentication on a gateway.

I have been reading through this issue:
https://github.com/nestjs/nest/issues/1254

But the approaches here do not seem to work based on my limited understanding.

@ed-fruty initially said

> handleConnection() inside gateway. Is this is the place where auth might be?

and @kamilmysliwiec replied

> For now, this is a place where the authentication logic could be potentially located (inside method you have a reference to the client instance so you can easily close the connection)

so this sounds good. If the user is not authenticated then we close the connection. But how do we detect if the client is authenticated or not? I cant see any way of getting access to the http request that was made to connect so we can't inspect the headers.

There are examples of implementing guards on `SubscribeMessage` functions like this:

```
@UseGuards(WsJwtGuard)
@SubscribeMessage('events')
onEvent(client, data) {
    // data.user contains your user if you set it in the guard
}
```

but at this point the client is already connected and receiving messages. In my use case the client will only be subscribing to messages and not pushing any messages at all. I could call `client.disconnect()` in the function above if the client is not authenticated but in that case the client could just not send that message and still receive all updates.

As far as I can see the auth challenge needs to be in the `handleConnection()` function. I can't see any way of getting information from the client that could be used to authenticate.

**Comment by kamilmysliwiec** [comment]
> but at this point the client is already connected and receiving messages. 

Correct. You shouldn't use guards on the `SubscribeMessage` level if only certain users should be able to connect.

> If the user is not authenticated then we close the connection. But how do we detect if the client is authenticated or not? 

https://github.com/nestjs/nest/issues/882#issuecomment-625903268

You can use the `socket.handshake.query.token` and verify the token (within the `handleConnection` hook).

Let's track this here https://github.com/nestjs/nest/issues/882

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Enrico724** [comment]
> > but at this point the client is already connected and receiving messages.
> 
> Correct. You shouldn't use guards on the `SubscribeMessage` level if only certain users should be able to connect.
> 
@kamilmysliwiec 
So, why there is not an explained way on how to handle security on Gateways at [the official docs](https://docs.nestjs.com/websockets/guards)? 

This issue has been opened several times, should we detail best practice on NestJS' website? I think this part needs to be reviewed. Shall we?
