### ISSUE TITLE
Add OpenRPC support

### ISSUE THREAD

**Issue by shanejonas** [nestjs/nest#4844]
## Describe the solution you'd like
I think this project could benefit from integration with OpenRPC which provides a base foundation for service discovery and tooling such as documentation/client generation/mock server for JSON-RPC akin to OpenAPI/Swagger.

Here is an example of the OpenRPC playground, it gets the OpenRPC Document via calling the [rpc.discover](https://spec.open-rpc.org/#service-discovery-method) method:

https://playground.open-rpc.org/?url=https://mock.open-rpc.org/petstore-1.0.0

and just the bare inspector:
https://inspector.open-rpc.org/?url=https://mock.open-rpc.org/petstore-1.0.0

Let me know how I can help.

## Teachability, Documentation, Adoption, Migration Strategy
![image](https://user-images.githubusercontent.com/364566/82826801-a9bde700-9e62-11ea-8adf-cd03d43f3465.png)
![image](https://user-images.githubusercontent.com/364566/82826915-d540d180-9e62-11ea-8069-6934287954ac.png)

## What is the motivation / use case for changing the behavior?
Read more about the [advantages of OpenRPC vs Swagger](https://github.com/open-rpc/spec/issues/112#issuecomment-474971078).

**Comment by kamilmysliwiec** [comment]
We don't plan to release a dedicated package for the OpenRPC. We encourage anyone who is interested in contributing to the ecosystem to give it a shot and maybe release as a community package. For reflecting & generating data models, the `@nestjs/swagger` can be used (at least as a reference implementation)
