### ISSUE TITLE
DI of custom Provider using interface (Symbol) instead of string token

### ISSUE THREAD

**Issue by genadis** [nestjs/nest#4845]
## Is your feature request related to a problem? Please describe.
Currently if we want to use DI for custom provider that implements an interface, the only solution is to use string tokens with boilerplate of defining constant strings, etc.

## Describe the solution you'd like
Leverage Symbols + Typescript interfaces in DI.
The concept and example usage is explained very well here:
https://docs.aurelia.io/app-basics/dependency-injection#using-interfaces

## Teachability, Documentation, Adoption, Migration Strategy
Full details and examples: https://docs.aurelia.io/app-basics/dependency-injection#using-interfaces

## What is the motivation / use case for changing the behavior?
This will allow strong typing and using the interface directly for DI and save some boilerplate code.

**Comment by kamilmysliwiec** [comment]
This is already possible with NestJS.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by genadis** [comment]
@kamilmysliwiec Thank you for your quick response and the great framework.

After your answer i'v reviewed the `Provider` definition and noticed in the docs the big bold "In addition to using strings as token values, you can also use JavaScript symbols."
My bad...

Would be great to have example in docs:
```
import { ICatsService } from './interfaces';

@Controller('cats')
export class CatsController {
  constructor(@Inject(ICatsService) private catsService: ICatsService) {}
}
```

while `ICatsService` defined as:

```
// interfaces.ts
export const ICatsService = Symbol('ICatsService');
export interface ICatsService {
...
}
```

**Comment by jmcdo29** [comment]
You mean, [something similar to this](https://docs.nestjs.com/fundamentals/custom-providers#non-class-based-provider-tokens)? Technically, the interface and the injection token don't need to have the same name, but it is doable if that is your preference. All that matters is that the injection token matches in the `provider` and in the `@Inject()`

**Comment by genadis** [comment]
@jmcdo29 thank you, I'm familiar with string tokens (have been using those until now), Using Symbol feels more elegant and less boilerplate. no need to maintain additional constans with strings across the projects. It feels more like injecting an Interface with single import statement since Typescript is able to merge definitions.
