### ISSUE TITLE
Why Schema in GitHub use decorators?

### ISSUE THREAD

**Issue by Noriller** [nestjs/nest#4846]
This is weird, in github you give as example a schema using decorators, in https://docs.nestjs.com/recipes/mongodb you use the common way of doing...

From what I saw, the decorators seems like those of typegoose, but they arent those...

I'm still learning and this made all so confusing because I really like the decorator way but I found nothing on them on the docs...

**Comment by jmcdo29** [comment]
The `@nestjs/mongoose` package has had some decorators added to it to make things feel more like the other packages (typeorm, sequelize, and graphql). However, the documentation still is not complete on them and is being worked on. There is [an open issue](https://github.com/nestjs/docs.nestjs.com/issues/1230) in the docs repo about it. If you'd like to see an example similar to the docs, [sample 14-mongoose-base](https://github.com/nestjs/nest/tree/master/sample/14-mongoose-base) is a good place to look.

**Comment by kamilmysliwiec** [comment]
We'll update the docs shortly
