### ISSUE TITLE
Middleware: DI not working

### ISSUE THREAD

**Issue by hellokvn** [nestjs/nest#4848]
## Bug Report

Firstly I wanna say that I found similar bug reports, but they are either out dated or doesn't even provide a solution.

## Current behavior

Created a global module which provides a service and injects a global middleware. But the middleware can't inject the service, somehow service is undefined inside middleware.

`TesterMiddleware/use { service: undefined }`

## Input Code

I created a repo, please pull and run by `npm run start:dev`. Port is 3012, so please open the app in: `http://localhost:3012/` - the middleware should console.log it's service but, as you will see, the service is undefined.

https://github.com/hellokvn/nestmid

## Expected behavior

Service should be not undefined in middleware.

## Environment

<pre><code>
Nest version: 7.1.0

 
For Tooling issues:
- Node version: 14.1.0
- Platform:  Mac 12.x

**Comment by hellokvn** [comment]
Found a solution:


  constructor(private readonly testerService: TesterService) {}

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
