### ISSUE TITLE
Server not available with hot reload after compilation error

### ISSUE THREAD

**Issue by darioielardi** [nestjs/nest#4850]
## Current behavior

With hot reload configured following the setup described in the docs ( with Nest CLI ):
- a file gets changed with invalid code ( anything that causes a compilation error )
- webpack server triggers a module replacement, the error shows up
- the file gets changed to fix the compilation error
- webpack server triggers another reload, this time everything compiles and looking at the log the server appears as working

Except that at this point the app server is unreachable.

## Environment

<pre><code>
Nest version: 7.1.0
 
For Tooling issues:
- Node version: 12
- Platform:  Mac

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by darioielardi** [comment]
Actually I just noticed the webpack log after the compilation is:
```
[HMR] Cannot apply update.
[HMR] Error: ...
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
```

This is actually not caused by a tsc error, but only by syntax errors.

Moreover, most of the times I also need to delete the `dist` folder before restarting the app to got it working again, otherwise it will serve the code as it was before the error no matter what.

Anyway, this happens with a brand new nest app ( with updated CLI ) with just the HMR setup, nothing more. Let me know if you still need a reproduction repo.

**Comment by darioielardi** [comment]
To be clear, restarting the app the error is something like:
```
[HMR] Cannot apply update.
[HMR] Error: Aborted because 9 is not accepted
Update propagation: 9 -> 6 -> 4 -> 0
```
Just tried with the webpack sample in the nest repo, same exact behavior.

**Comment by kamilmysliwiec** [comment]
Can you share the exact steps to reproduce your issue? I can't get this error locally

**Comment by darioielardi** [comment]
sure: 

1. clone the nest repo, open the 08-webpack sample, `npm install`
2. `npm run build:dev`
3. server is now running, `curl http://localhost:3000` outputs `Hello world`
4. if you make any change in the code webpack does hmr as expected
5. make a syntax error, webpack tries to update but:
```
[HMR] Cannot apply update.
[HMR] Error: ...
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
***stacktrace ***
[HMR] You need to restart the application!
```
6. ctrl+c to stop the server, `npm run build:dev` to start again
7. any change made ad this point makes webpack fail with something like:
```
[HMR] Cannot apply update.
[HMR] Error: Aborted because 9 is not accepted
Update propagation: 9 -> 6 -> 4 -> 0
...
[HMR] You need to restart the application!
```
so the application is still running but the served code is always the one built before the syntax error.
8. stop the server, `rm -rf dist`, restart and of course everything works again

**Comment by kamilmysliwiec** [comment]
OK I think I understand. Thanks for sharing the reproduction steps!

There's not too much we can do except for making the DX somewhat better by enabling the `deleteOutDir: true` in the `nest-cli.json`. Now, it will automatically wipe out the previously generated bundle before running a new build process.

Added in this commit https://github.com/nestjs/nest/commit/c573fb3b8947a7544b08251989f4f2273ec40420

**Comment by darioielardi** [comment]
I see, anyway I could probably skip HMR and just use `nest start --watch` since it does incremental builds and not a full rebuild each time, is that right?

**Comment by kamilmysliwiec** [comment]
Correct

**Comment by darioielardi** [comment]
Nice, thanks for your time!
