### ISSUE TITLE
[Microservices] the gRPC DTO is undefined if a param decorator is used

### ISSUE THREAD

**Issue by jonasbeyer** [nestjs/nest#4851]
## Current behavior

If a param decorator is applied to a parameter of a gRPC route handler, the DTO is always undefined, but the parameter the custom decorator is applied to gets populated properly.

## Input Code

```
// controller

@GrpcMethod('ReportService')
createReport(createReportDto: CreateReportDto, @AuthUser() user: User): Promise<Report> {
  console.log(createReportDto); // undefined
  console.log(user) // {id: 1, role: 2}

  return this.reportService.createOne(createReportDto, user.id);
}
```
```
// param decorator

export const AuthUser = createParamDecorator(
  (data: any, context: ExecutionContext) => {
    const metadata = context.switchToRpc().getContext();
    return metadata.user; // the user is attached to the context in a guard
  },
);
```

## Expected behavior

Both the DTO and the parameter that the decorator is applied to, should be populated properly.

## Environment

<pre><code>
Nest version: 7.1.0

</code></pre>

**Comment by kamilmysliwiec** [comment]
Have you tried using `@Payload() createReportDto: CreateReportDto`?

**Comment by jonasbeyer** [comment]
That works. I did not see that there is a separate param decorator for a gRPC handler. 

However, it seems that the `@Body()` decorator also works for the gRPC handler, since I'm trying to use the same handler for HTTP + gRPC.

 Is this the intended behavior?

**Comment by kamilmysliwiec** [comment]
I'm glad it fixed your issue! 

> However, it seems that the @Body() decorator also works for the gRPC handler, since I'm trying to use the same handler for HTTP + gRPC.

This is due to the backward compatibility. 

We gotta improve the documentation. Sorry for the inconvenience!

**Comment by danias** [comment]
What about metadata and call? When I use a decorator, data shows up when I use @Payload() but I don't know what to use for metadata and call.

**Comment by MaksymShuldiner** [comment]
@kamilmysliwiec @danias agree, what argument should be used for metadata and call?
