### ISSUE TITLE
socket_io_redis_1.default is not a function

### ISSUE THREAD

**Issue by bcba25** [nestjs/nest#4852]
Following the documentation example for [redis adapter](https://docs.nestjs.com/websockets/adapter) I've created an adapter exactly the same as in example:

```
import { IoAdapter } from '@nestjs/platform-socket.io';
import redisIoAdapter from 'socket.io-redis';

export class RedisIoAdapter extends IoAdapter {
  createIOServer(port: number, options?: any): any {
    const server = super.createIOServer(port, options);
    const redisAdapter = redisIoAdapter({ host: 'localhost', port: 6379 });

    server.adapter(redisAdapter);
    return server;
  }
}
```

But can't start the application, receiving this error:
`(node:15717) UnhandledPromiseRejectionWarning: TypeError: socket_io_redis_1.default is not a function`

**Comment by bcba25** [comment]
Wrong imports in documentation, issue resolved

**Comment by jagg625** [comment]
> Wrong imports in documentation, issue resolved

Excuse me, i have the same problem, which imports did you used ?

**Comment by kamilmysliwiec** [comment]
@jagg625 change it to:

```
import * as redisIoAdapter from 'socket.io-redis';
```

**Comment by jagg625** [comment]
@kamilmysliwiec thanks a lot

**Comment by phattranky** [comment]
For me, I need to change to 

```
import redisIoAdapter from 'socket.io-redis';
```
