### ISSUE TITLE
Unable to build using webpack with  libraries.

### ISSUE THREAD

**Issue by kkrishnakv** [nestjs/nest#4858]
## Bug Report
Added library: 
 nest g library cache-manager.

Build the library using 
nest build cache-manager. 

Build command using  webpack. 
 "start:dev": "webpack --config webpack.config.js"

## Current behavior
Getting the below error:

Module not found: Error: Can't resolve '@app/cache-manager'

## Webpack configuration:

const webpack = require('webpack');
const path = require('path');
const nodeExternals = require('webpack-node-externals');
const StartServerPlugin = require('start-server-webpack-plugin');

module.exports = {
  entry: ['webpack/hot/poll?100', './src/main.ts'],
  watch: true,
  target: 'node',
  externals: [
    nodeExternals({
      whitelist: ['webpack/hot/poll?100'],
    }),
  ],
  module: {
    rules: [
      {
        test: /.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  mode: 'development',
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new StartServerPlugin({ name: 'server.js' }),
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'server.js',
  },
};

## Environment

<pre><code>
Nest version: 6.11.1

For Tooling issues:
- Node version: 10:15.1
- Platform:  Windows 10.

**Comment by kamilmysliwiec** [comment]
If you're using a custom webpack config, you must apply the `TsconfigPathsPlugin` plugin manually. See the default options for reference https://github.com/nestjs/nest-cli/blob/master/lib/compiler/defaults/webpack-defaults.ts#L49-L51
