### ISSUE TITLE
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

### ISSUE THREAD

**Issue by helloitsm3** [nestjs/nest#4859]
## Current behavior

Unable to return anything when trying to use a custom api route. I.e. localhost:3000/api/:id

## Input Code

`@Controller('api')
export class UserIDController{
  @Get(':id')
  getOTP(): string {
    return {id: userid}
  }
}
`

```ts
const your = (code) => here;
```

## Expected behavior

able to render user id on browser when url is entered

## Environment

<pre><code>
Nest version: 7.0.0

 
For Tooling issues:
- Node version: 13.12.0
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
