### ISSUE TITLE
Can't resolve factory provider with String or Symbol token from NestApplicationContext

### ISSUE THREAD

**Issue by umbertoo** [nestjs/nest#4861]
## Current behavior
Can't resolve factory provider with String or Symbol token from NestApplicationContext
>TypeError: Cannot read property 'getInstanceByContextId' of undefined
## Input Code

Repo link: https://github.com/umbertoo/check-resolver

app.module.ts
```ts
export const SYMBOL_TOKEN = Symbol();
export const STRING_TOKEN = 'STRING_TOKEN';

@Module({
  imports: [],
  providers: [
    {
      provide: SYMBOL_TOKEN,
      useFactory(){ return { name: 'factory provider with SYMBOL TOKEN'} }
    },
    {
      provide: STRING_TOKEN,
      useFactory(){ return { name: 'factory provider with STRING TOKEN'} }
    },
  ],
})
export class AppModule {}
```
main.ts
```ts
async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);

  const factoryProviderWithToken = await app.resolve(SYMBOL_TOKEN);
  const factoryProviderWithString = await app.resolve(STRING_TOKEN);
}
bootstrap();
```
## Expected behavior

To be resolved
## Possible Solution

---
## Environment

<pre><code>
Nest version: 7.1.1

 
For Tooling issues:
- Node version: 12.17.0  
- Platform:  Mac, Linux

**Comment by kamilmysliwiec** [comment]
Apart from the error message that should be more descriptive, why are you trying to use `.resolve()` for non-scoped providers?

**Comment by umbertoo** [comment]
I'm sorry. I thought it's quite descriptive.
I've reported about bug because signature of the NestApplicationContext.resolve method clearly says that a string token or a symbol token can be used 
```ts
  public resolve<TInput = any, TResult = TInput>(
    typeOrToken: Type<TInput> | string | symbol,
    contextId = createContextId(),
    options: { strict: boolean } = { strict: false },
  ): Promise<TResult>
```

If it relates to the bug, my particular usecase is
```    
{
      provide: 'CommandMediator',
      useFactory: (moduleRef: ModuleRef): CommandMediator => {
        commandMediator.setResolver(moduleRef.resolve.bind(moduleRef));
        return commandMediator;
      },
      inject: [ModuleRef],
},
```
I've not describe my partical usecase because the main point of the bug report was that claimed functionality does not work.

Actually, I expected it to work as ModuleRef

Both `resolve` methods from `ModuleRef` and `NestApplicationContext` delegate resolving to their own `resolvePerContext` method. Which implementations are very similar, except that `resolvePerContext` method of `NestApplicationContext` does not pass `InstanceWrapper` resolved by `containerScanner.getWrapperCollectionPair` to `injector.loadPerContext`.

So, I've tried to pass `InstanceWrapper` and it works. The full unit tests suite is passed.

**Comment by kamilmysliwiec** [comment]
> I've reported about bug because signature of the NestApplicationContext.resolve method clearly says that a string token or a symbol token can be used

You **can** use a string token (or symbol).

What I'm saying is that your factory **is NOT request/transient-scoped**. Thus, you should use `app.get()` instead of `app.resolve()`.

**Comment by umbertoo** [comment]
Ok, I thought the same logic applies to NestApplicationContext as to ModuleRef. Because through ModuleRef I can resolve NOT request/transient-scoped from within application. A bit inconsistent approach to me. That's why it confused me. Thank for your time!
