### ISSUE TITLE
Initiate multiple providers from one factory

### ISSUE THREAD

**Issue by hongyiweiwu** [nestjs/nest#4863]
## Is your feature request related to a problem? Please describe.
Suppose I want to provide `n` instances of some service (which can be database connections, redis clients, etc), each with a different injection token. Moreover I want to create all these instances from one config object which must be asynchronously generated. This is currently not doable in NestJS because the closest we can get is to

1. Create an async provider to provide the option object itself.
2. Create another async provider to which the option object is injected into. We then use `useFactory` to generate the instances.

However, in this case we can only generate one provider for all the instances, because the `provide` property only takes in one token. We also must know the name of the token ahead of time.

## Describe the solution you'd like
A new property `provideMany` that takes in a function which transforms the value from the factory into an object with keys the injection tokens and values the provided value corresponding to the token. The `provide` property is kept albeit with a different semantics when `provideMany` is also present: It now refers to all the injection tokens made from `provideMany`, so we can export all tokens from `provideMany` by putting the token from `provide` in the `export` array.

Here's an example:
```typescript
// This module provides the following:
// TOKEN: Symbol(0), DATA: "zero"
// TOKEN: Symbol(1), DATA: "one"
@Module({
    providers: [{
        useValue: ["zero", "one"],
        provide: "NUMBERS",
        provideMany: (rawValue: string[]) => {
            let obj = {};
            rawValue.forEach((val, index) => Reflect.set(obj, Symbol(index), val));
            return obj;
        },
    } as any],
    exports: [
        Symbol(0),      // You can choose to export a single token defined in provideMany.
        "NUMBERS",      // Or you can use the token in `provide` to export everything (in this case, both Symbol(0) and Symbol(1)).
    ]
})
export class AModule {}

@Injectable()
export class AService {
    @Inject(Symbol(0)) 
    private readonly z: string;     // Will have value "zero".
}
```

**Comment by kamilmysliwiec** [comment]
> Suppose I want to provide n instances of some service (which can be database connections, redis clients, etc), each with a different injection token. Moreover I want to create all these instances from one config object which must be asynchronously generated. This is currently not doable in NestJS 

This is doable. However, provider tokens must be known beforehand (thus, can't be modified from within the factory - which is done by design, otherwise, it wouldn't make sense).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
