### ISSUE TITLE
Distributed scheduler/queue with Scaling Graphql API

### ISSUE THREAD

**Issue by kaufmo** [nestjs/nest#4865]
Hi guys, I hope somebody can help me, I don't know where to post my question. I'm working on a Graphql(code first) Typeorm(postgres) Nestjs API(express) which is Deployed in Openshift(Kubernetes) with horizontal Scaling. What I want to do now is to integrate scheduling (crons) in combination of queueing (bull) to send millions of notifications. My plan is to use scheduler to find notifications to send and add these to a redis queue which will be sent separatly. My problem here is that every scheduler will start with every api pod so the jobs will be handled multiple times for every runnig api pod. Does anybody of you have an idea how to solve this that the scheduler can run distributed?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by eugenio165** [comment]
Hi @kaufmo have you found a solution for this? I'm going to need something like this in the near future
