### ISSUE TITLE
Logger is marked with @Injectable() but injection doesn't work

### ISSUE THREAD

**Issue by gremo** [nestjs/nest#4868]
## Current behavior
Logger is marked with @Injectable() but injection doesn't work. It throws 

> 2020-6-2 11:55:33 [ExceptionHandler] Nest can't resolve dependencies of the AppController (AppService, ?). Please make sure that the argument Logger at index [1] is available in the AppModule context.

## Input Code

```ts
import { Controller, Get, Logger } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService,
    private readonly logger: Logger) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}

```

## Expected behavior
`Logger` instance is injected.

## Possible Solution
Don't know. For now, use `Logger` static methods, directly.

## Environment

<pre><code>
Nest version: 7.1.1

For Tooling issues:
- Node version: v12.16.3
- Platform:  Windows 10 x64

Others:

</code></pre>

**Comment by jmcdo29** [comment]
More than likely, you haven't added the `Logger` to the module's `providers` array. 

In the future, please use [Discord](https://discord.gg/nestjs) for support as we are using GItHub for bug reports and feature requests

**Comment by gremo** [comment]
Sorry, maybe. Where is documented? Is something in the documentation like an example on how to inject the default logger service (and actually, include in in your module before trying to use it)?

**Comment by jmcdo29** [comment]
[The docs mention it with a custom extension](https://docs.nestjs.com/techniques/logger#dependency-injection), but this applies as well to the base class. **Everything** in nest that is to be injected needs to be A) in a module's `providers` array and B) in the context of the current module. With things like the `Reflector` and `ModuleRef`, those are globally scoped, so it's not necessary to add them, but the `Logger` class is not in a global module, so it needs to be added to the `providers` array of the current module

**Comment by gremo** [comment]
Yes, exactly, the example is with a custom implementation. It should also explain **how to use the original `Logger` alone**, and explicitly say that service is not provided as a "global" one.

In my case, being the author of [nest-winston](https://github.com/gremo/nest-winston) package, I was interested only in retrieving the original Logger instance (which "wraps" the custom logger).

BTW thanks, closing.
