### ISSUE TITLE
inject http context into typeorm listeners

### ISSUE THREAD

**Issue by huyvd94** [nestjs/nest#4869]
https://github.com/nestjs/nest/issues/173

referring to this issue. does anyone archive this? if any can I have a simple example?
thanks

**Comment by huydroz** [comment]
so what I am trying to do. I have entity and every time I created new line or update it I can know who's create or update it.
I have baseEntity like this. and order entity will inherit this one.
`@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    createdBy: string;

    @Column()
    updatedBy: string;
}`

// use decorator
`
import { createParamDecorator } from '@nestjs/common';

export const User = createParamDecorator((data, req) => {
  return req.user; // current userid
});`

what I don't know is how to get the userId every time the entity created or update.
according to the typeorm documentation that I can implement it in "Entity Listeners or Subscribers".
I were read a lot of issues in nest and know a lot of people stuck like me. and @kamilmysliwiec were mention it in a lot of topic about this using using Injection scopes. but I can't found an example for this.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by kamilmysliwiec** [comment]
Btw, injection scopes chapter https://docs.nestjs.com/fundamentals/injection-scopes
