### ISSUE TITLE
improve di circular dependency error, possible solutions

### ISSUE THREAD

**Issue by darrenjennings** [nestjs/nest#4872]
## Current behavior
From the docs:
> A forward reference allows Nest to reference classes which aren't yet defined using the forwardRef() utility function. For example, if CatsService and CommonService depend on each other, both sides of the relationship can use @Inject() and the forwardRef() utility to resolve the circular dependency. Otherwise Nest won't instantiate them because all of the essential metadata won't be available.

If you set up a circular dependency without forward refs then you get a warning:
```
[Nest] 30635   - 06/02/2020, 11:57:14 AM   [ExceptionHandler] Nest can't resolve dependencies of the CatsService (?). Please make sure that the argument dependency at index [0] is available in the CommonModule context.

Potential solutions:
- If dependency is a provider, is it part of the current CommonModule?
- If dependency is exported from a separate @Module, is that module imported within CommonModule?
  @Module({
    imports: [ /* the Module containing dependency */ ]
  })
```

## Expected behavior
It would be nice to see that there is a circular dependency in potential solutions list pointing to using forward refs (or discouraging circular deps if desired).

## Environment

<pre><code>
Nest version: 6.10.12

 
For Tooling issues:
- Node version: v11.15.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by darrenjennings** [comment]
@kamilmysliwiec 👍
