### ISSUE TITLE
Strict routing mode for express web-server isn't working

### ISSUE THREAD

**Issue by Pterko** [nestjs/nest#4875]
## Bug Report

I've wanted to have two separate methods in my controller: `/test` and `/test/`. Due to express, in non-strict mode these routes are identical.
I've tried to configure an underlying express server: I've wanted to use strict routing to have two methods `/test` and `/test/` in my controller. So I've enabled "strict routing" in express settings. But it looks like a second method (`/test/`) of my controller doesn't transform into express route, because it returns 404.

## Current behavior
`/test` method working correctly, `/test/` test method returns 404 code.

## Input Code
Github repo: https://github.com/Pterko/nestjs-strict-routing
Codesandbox link: https://codesandbox.io/s/github/Pterko/nestjs-strict-routing

Controller part:
```
@Get("/test/")
testStrict() {
  return "test strict";
 }

@Get("/test")
test() {
  return "test";
}
```

Main.ts
```
const app = await NestFactory.create(AppModule);
const httpAdapter = app.getHttpAdapter().getInstance();
httpAdapter.set("strict routing", true);

await app.listen(3000);
```

## Expected behavior
Two methods of this controller work separately and return 200 code.

## Environment

<pre><code>
Nest version: 7.1.3

 
For Tooling issues:
- Node version: 12.16.3
- Platform:   Linux

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Could you provide the codesandbox link as a git repo instead so it can be cloned and ran locally?

**Comment by Pterko** [comment]
Yes, sure.
Github repo: https://github.com/Pterko/nestjs-strict-routing
Codesandbox link: https://codesandbox.io/s/github/Pterko/nestjs-strict-routing

**Comment by Pterko** [comment]
I've made a little investigation of this issue: it looks like Nest.js deletes ending slash for any controller route:
https://github.com/nestjs/nest/blob/master/packages/core/router/router-explorer.ts#L172

Maybe we can add a way to configure this behavior (maybe through ApplicationConfig)?

**Comment by jmcdo29** [comment]
@Pterko I saw the issue happening when I cloned your repo. What's a use case of having separate functionality at `/test` and at `/test/`? Is this only affecting `Express` or does `Fastify` normally treat these different as well?

**Comment by kamilmysliwiec** [comment]
This is the intended behavior (for the sake of consistency & predictability between applications).  We're not looking into changing this at the moment.
