### ISSUE TITLE
Config Docs - Configuration namespaces - Wrong parameter name is used which conflicts with the import statement

### ISSUE THREAD

**Issue by vishch** [nestjs/nest#4879]
## Current behavior
https://docs.nestjs.com/techniques/configuration#configuration-namespaces
Docs for the "strong typing" section, use "databaseConfig" name in the import statements as well as the parameter name which creates conflict and compilation issue.

```ts
import databaseConfig from './config/database.config';

constructor(
  @Inject(databaseConfig.KEY)
  private databaseConfig: ConfigType<typeof databaseConfig>,
) {}
```

## Expected behavior
There shouldn't be any compilation when using the Docs code snippets.

## Possible Solution
Rename the parameter from "databaseConfig" to "dbConfig".

**Comment by kamilmysliwiec** [comment]
Good catch! Thank you. Fixed
