### ISSUE TITLE
Use Firebase with Nestjs

### ISSUE THREAD

**Issue by ildemartinez** [nestjs/nest#4880]
## Bug Report
Hello

I am trying to deploy Nestjs into firebase functions to deploy a API services but when try to configure Firebase to use auth modules for example got an compilation error

I have used latest version packages versions. I attached a screenshoot of the error

![firebase_nestjs](https://user-images.githubusercontent.com/1641352/83790839-158d2480-a699-11ea-8147-bc8378a41a5c.PNG)

Looking in the net I found not too much information about use NestJS in the Firebase services...Is it possible or should I switch to Express.js?

All the best
ilde

**Comment by jmcdo29** [comment]
It looks like you're trying to use an Angular module inside of a Nest application. These module types are not compatible with each other.

Please use our [Discord](https://discord.gg/nestjs) for support. We are using GitHub for feature requests and bug reports.
