### ISSUE TITLE
How to import nestjs GIT branches as dependency in package.json

### ISSUE THREAD

**Issue by sjkummer** [nestjs/nest#4881]
I love contributing to the nestjs project.

But: I cannot easily use or test new features or bugfixes as long as they have not been published on npm.

For other projects, this can be done easily in package.json using the `github` prefix:
```
{
...
  "dependencies": {
    "library-name": "github:username/library-name#commit",
    }
}
```

For nestjs, this does not work since multiple npm modules are in one github project.

Is there an easy way to work with github commits for nest?

The only workarround I know is to clone manually on every machine and use a file:// link in package json 😕

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
