### ISSUE TITLE
How do I need to use mqtt's "connect", "reconnect" and other callback events in nest?

### ISSUE THREAD

**Issue by ShareQiu1994** [nestjs/nest#4887]
I am using nestjs mqtt to subscribe to message queuing，I couldn't find a callback method for mqtt to listen for events due to a lack of documentation on the combination of nest and mqtt. How do I need to use mqtt's "connect", "reconnect" and other callback events in nest?

this my code
 “main.ts”
`import { NestFactory } from '@nestjs/core';
import { MqttModule } from '../../mqtt/mqtt.module';
import { Transport } from '@nestjs/microservices';

async function bootstrap() {
  const mqtt = await NestFactory.createMicroservice(MqttModule, {
    transport: Transport.MQTT,
    options: {
      url: 'mqtt://127.0.0.1:1883',
    },
  });
  await mqtt
    .listenAsync()
    .then(() => {
      console.log(`SUCCESS!`);
    })
    .catch(err => {
      console.log('ERROR!');
      console.error(err);
    });
  console.log(mqtt);
}
bootstrap();
`
“mqtt.module.ts“
`import { Module } from '@nestjs/common';
import { MqttService } from './mqtt.service';
import { MqttController } from './mqtt.controller';
@Module({
  imports: [],
  providers: [MqttService],
  controllers: [MqttController],
})
export class MqttModule {}`

“mqtt.controller.ts”
`import { Controller } from '@nestjs/common';
import {
  Payload,
  Ctx,
  MqttContext,
  EventPattern,
  Client,
  ClientProxy,
  Transport,
  MessagePattern,
} from '@nestjs/microservices';

@Controller()
export class MqttController {

  @MessagePattern('GpsInfoNotify')
  getNotifications(@Ctx() context: MqttContext) {
    console.log(`Topic: ${context.getPacket()}`);
  }
}
`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) or StackOverflow for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
