### ISSUE TITLE
Typed injection token

### ISSUE THREAD

**Issue by fan-tom** [nestjs/nest#4890]
## Feature Request
Make injection tokens typed
## Is your feature request related to a problem? Please describe.

Now type of injection token is not connected with type of entity it is used to inject. It is very common task when testing to override provider for specific token with some mock, or to get component by token it is injected by, to inspect its internal state.
## Describe the solution you'd like

I'd suggest to create type `Token<T>`, where `T` is interface of component this token is used to inject. Also, add overloads of `NestApplicationContext.get` and `NestApplicationContext.resolve` to precisely fix return type to `T` when `Token<T>` is provided, and change interface `OverrideBy` to track the type of used token to restrict the types of `useFactory/useValue/useClass`.
## Teachability, Documentation, Adoption, Migration Strategy

Deprecate plain strings and symbols as injection tokens in favor of some function `createToken<T=unknown>(name: string | symbol): Token<T>`, that attaches `T` to token type.(make `T=unknown` by default to force user provide type explicitly)
No existing code will break, as we still accept untyped tokens, all changes are on type level anyway.
It would be very useful to also adopt `@Inject(token)` to be type safe, but seems that it is impossible with current state of decorators (we need to know the type of argument decorator used with, but we only know index in parameters list)
## What is the motivation / use case for changing the behavior?

```typescript
const MyToken = 'MyToken';
interface IMyService {
  foo(): number;
}
class MyService implements IMyService {...}
class MyOtherService {...}
const provider: Provider<MyService> = {
  provide: MyToken,
  useClass: MyService
};

const module = await Test.createTestingModule({...})
    .overrideProvider(MyToken)
    .useClass(MyOtherService)// mistake, MyOtherService doesn't implement IMyService, strange runtime errors like "foo is not a function" when attempting to call "foo"
    .compile();

const myService = module.get(MyToken);// myService: any, should be IMyService

**Comment by kamilmysliwiec** [comment]
This has been discussed in the past already and we don't plan to change it.

**Comment by fan-tom** [comment]
Do you mean this issue? https://github.com/nestjs/nest/issues/1019. I didn't find anything else mentioning injection tokens. Taking into account that angular makes their tokens typed, I don't see any reason to be against type-safety in this area. Suggested changes are not so invasive, are backward-compatible and let people to at least have a chance to catch errors at compile time.

**Comment by HananoshikaYomaru** [comment]
so is this issue solved? what is the solution? if not, where is the original discussion?
