### ISSUE TITLE
ApiResponse `type` attribute does not support Array<MyClass> but supports [MyClass]

### ISSUE THREAD

**Issue by zackarychapple** [nestjs/nest#4891]
## Current behavior
`TS2365: Operator '' cannot be applied to types 'ArrayConstructor' and 'typeof MyClass'.`

## Input Code

```ts
@ApiResponse({status: HttpStatus.OK, type: Array<MyClass>})
```

However the following works:

```ts
@ApiResponse({status: HttpStatus.OK, type: [MyClass]})
```
## Expected behavior
It would be awesome if both type formats were accepted.

<pre><code>
Nest version: 7.0.2
Typescript version: 3.8.3

**Comment by kamilmysliwiec** [comment]
This isn't supported by TypeScript (`Array` is a generic) https://docs.nestjs.com/recipes/swagger#generics-and-interfaces
