### ISSUE TITLE
Documentation on querying syntax

### ISSUE THREAD

**Issue by felixunivers** [nestjs/nest#4892]
## Feature Request
Great product. I like your server! However, it is hard to find proper syntax with examples for some detailed features. At this time I am really struggling to do queries on the server. Would you please provide some more documentation with details and examples?

## Is your feature request related to a problem? Please describe.

Please have a look at [this post](https://stackoverflow.com/questions/62273942/client-is-angular-8-with-ngrx-data-server-is-nestjs-mysql-how-to-get-data-us). It contains a more detailed example of the struggle. Perhaps, for now, you could post some answers there and later add to your docs.
Thank you.

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for Support. We are using GitHub for tracking Bug Reports and Feature Requests.
