### ISSUE TITLE
how to get user data with req.user on decorator

### ISSUE THREAD

**Issue by webafra** [nestjs/nest#4894]
Hello .
I created the authentication ( jwt ) and the process is done properly.

I can access the user's information using the following code, but I can't get the user's information using the decorator!

controller : 
```
@Post('/me/info')
  @UseGuards(AuthGuard())
  myInfo(
    @GetUser() user,
    @Req() req,
  ) {
    console.log(user); // undefined 
    console.log(req.user); // get user data object
  }
```
![image](https://user-images.githubusercontent.com/8689072/84226318-b004c200-aaf6-11ea-9638-dad52cffc4dc.png)

my decorator is:

```
import { createParamDecorator } from '@nestjs/common';
import { User } from './user.entity';

export const GetUser = createParamDecorator((data, req): User => {
  return req.user;
});
```

what is my code problem ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by ellenaua** [comment]
The same issue for me. This example from documentation does not work - https://docs.nestjs.com/custom-decorators

**Comment by jmcdo29** [comment]
@ellenaua you probably don't have the passport guard running first, which sets `req.user`. Please follow Kamil's instructions and let's discuss this on [Discord](https://discord.gg/nestjs)
