### ISSUE TITLE
eslint: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.

### ISSUE THREAD

**Issue by OlegBrony** [nestjs/nest#4900]
## Bug Report
I installed nest and start new project. and there is a problem with eslint: in .eslint.js I got error 
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided.
```
eslint in code also not working, and command `npm run lint` doesn't find any problems.

## Input Code
.eslintrc.js 
```
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    sourceType: 'module',
    project: 'tsconfig.json'
  },
  plugins: ['@typescript-eslint/eslint-plugin'],
  extends: [
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier',
    'prettier/@typescript-eslint',
  ],
...
};
```
I didn't change anything actually.

## Environment

<pre><code>
Nest version: 7.2.0
 
For Tooling issues:
- Node version: 13.10.1
- Platform:  Linux mint

webstorm, npm 6.13.7.
</code></pre>

is it reproduced or is it just me?

**Comment by OlegBrony** [comment]
is it reproduced or is it just me?

**Comment by kamilmysliwiec** [comment]
I can't reproduce your issue. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by OlegBrony** [comment]
> I can't reproduce your issue.
> Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

ok, but what should I looking for? looks like I don't get relevant result when I google `Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.`

**Comment by heleg** [comment]
@OlegBrony, looks like this happened because webstorm automatically tries to apply eslint to `.eslintrc.js` file and parse it with typescript config (which is not working with `js` files). You can safely ignore it.

**Comment by BrenoGO** [comment]
I believe this issue should be a bug.. I am having the same error. The script lint runs but doesn't fix or complain about any of the many linting errors I left in the code...

**Comment by jmcdo29** [comment]
@BrenoGO can you provide a minimum reproduction?

**Comment by BrenoGO** [comment]
Just run "nest new my-project". The .eslintrc will show the error.
I made ran the eslint --init and now it's ok. I thought it would start already configured.

**Comment by BrenoGO** [comment]
I am using the nest 7.4.1.
Using the git clone https://github.com/nestjs/typescript-starter.git, it's the same..
Does anyone does these procedures and the eslint works fine?! Could be something with my VSCode?
In other projects I always use it configuring from beginning with eslint --init and is working fine..

**Comment by jmcdo29** [comment]
@BrenoGO using the latest version of the Nest CLI I created a new project 
```bash
$ nest new nest-lint-problem -p yarn
```
Once the installation finished I moved into the new project's directory
```bash
$ cd nest-lint-problem
```
And then I ran the linter
```bash
$ yarn lint
eslint "{src,apps,libs,test}/**/*.ts" --fix
Done in 13.18s.
```
Just to be sure, I then ran eslint directly
```bash
yarn eslint --fix
~/nest-lint-problem/node_modules/.bin/eslint --fix
Done in 3.33s.
```
Not sure what you're facing, but the configuration setup is fine in terms of running the lint command. It sounds like the problem is with the IDE, as in eslint trying to lint the `.eslintrc.js` file. As that doesn't really happen from the lint commands, I don't really see it being an issue. If you want to fix it though, you can create an `.eslintignore` file and add all `.js` files or specific ones, just like you would for a `.gitignore`

**Comment by BrenoGO** [comment]
The problem is when we go to a file and leave some code out of pattern, the eslint does not report any errors..
![Screen Shot 2020-07-24 at 06 41 52](https://user-images.githubusercontent.com/45217043/88379765-d9fa0700-cd79-11ea-85f1-75b7945b85b2.png)

I thought this should be not happening as expected because of the error in the .eslintrc above:
![Screen Shot 2020-07-24 at 06 44 42](https://user-images.githubusercontent.com/45217043/88379940-1af21b80-cd7a-11ea-8ed4-80c7b30938a1.png)

**Comment by sanch941** [comment]
Solved by replacing filename from .eslintrc.js to .eslintrc and removing module.exports etc.

**Comment by BrenoGO** [comment]
Doing that the error in .eslintrc will be gone. But still some basic rules like "semi", "comma-dangle" and "quotes" are not being reported by the eslint. I seems like we have to configure it all by ourselves..

**Comment by sanch941** [comment]
> Doing that the error in .eslintrc will be gone. But still some basic rules like "semi", "comma-dangle" and "quotes" are not being reported by the eslint. I seems like we have to configure it all by ourselves..

You should install this dependencies
`yarn add eslint-config-prettier eslint-plugin-prettier --dev`
And replace extends object in .eslintrc by this
`
"extends": [
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint", 
    "plugin:prettier/recommended"
 ]
`
After VsCode reload should work

**Comment by BrenoGO** [comment]
> > Doing that the error in .eslintrc will be gone. But still some basic rules like "semi", "comma-dangle" and "quotes" are not being reported by the eslint. I seems like we have to configure it all by ourselves..
> 
> You should install this dependencies
> `yarn add eslint-config-prettier eslint-plugin-prettier --dev` or `npm install eslint-config-prettier eslint-plugin-prettier --save-dev`
> And replace extends object in .eslintrc by this
> 
> "extends": [
> "plugin:@typescript-eslint/eslint-recommended",
> "plugin:@typescript-eslint/recommended",
> "prettier/@typescript-eslint",
> "plugin:prettier/recommended"
> ]
> 
> After VsCode reload should work

There we go! thanks

**Comment by lucasluca** [comment]
> > Doing that the error in .eslintrc will be gone. But still some basic rules like "semi", "comma-dangle" and "quotes" are not being reported by the eslint. I seems like we have to configure it all by ourselves..
> 
> You should install this dependencies
> `yarn add eslint-config-prettier eslint-plugin-prettier --dev` or `npm install eslint-config-prettier eslint-plugin-prettier --save-dev`
> And replace extends object in .eslintrc by this
> 
> "extends": [
> "plugin:@typescript-eslint/eslint-recommended",
> "plugin:@typescript-eslint/recommended",
> "prettier/@typescript-eslint",
> "plugin:prettier/recommended"
> ]
> 
> After VsCode reload should work

Does not worked for me

**Comment by BrenoGO** [comment]
@lucasluca ,  did you also did that?

> Solved by replacing filename from .eslintrc.js to .eslintrc and removing module.exports etc.

what did not work for you?

**Comment by hooman-myadbox** [comment]
I did exactly the same thing. Added the packages and extended what was recommended. I still have the same issue.

**Comment by hreisi** [comment]
I did exactly the same thing. Added the packages and extended what was recommended. I still have the same issue.

**Comment by hreisi** [comment]
I had to change the extension of the `.eslintrc.js` to `ts`. Then it was resolved.

**Comment by OlegBrony** [comment]
SO... all the fix was about
1) changing name from '.eslintrc.js' to '.eslintrc'.
2) making json from object (and fix all json syntax errors).
![image](https://user-images.githubusercontent.com/19880334/89500937-2e19d800-d7cb-11ea-8979-cb5b6355a3e1.png)

**Comment by maitrungduc1410** [comment]
For me this error happens for all files in `test` folder, and I found the reason is eslint is using `tsconfig.json` for configuration, and by default in `tsconfig.json` there's no `test` in `include`. So here's the fix:
```json
{
  ... other options
  "include": [ "src", "test"] // add "test" folder here
}

```

**Comment by sesdeyb** [comment]
For me it was the .eslintrc file in `tests` folder, it had the wrong path to tsconfig.json.

I had to change the parserOptions.project to "../tsconfig.json".

```
{
  "parserOptions": {
	... other options
    "project": "../tsconfig.json"
  }
}
```

**Comment by stvnwrgs** [comment]
Adding ` "createDefaultProgram": true` to the tsconfig, after doing https://github.com/nestjs/nest/issues/4900#issuecomment-669743374 fixed it for me.

```{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "sourceType": "module",
    "createDefaultProgram": true
  },
  ...
```

**Comment by bernhardvollnhofer** [comment]
What I still don't understand:
Is this a bug in IntelliJ? Or in eslint?
Or does NestJS create a faulty eslint configuration?

**Comment by ErolPeel** [comment]
What I still don't understand:
Is this a bug in IntelliJ? Or in eslint?
Or does NestJS create a faulty eslint configuration?

**Comment by ErolPeel** [comment]
In my opinion, NestJS creates an erroneous configuration.

The file `.eslintrc.js` shoud look like this:
```javascript
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'tsconfig.json',
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint/eslint-plugin'],
  extends: [
    'plugin:@typescript-eslint/recommended',
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
  ],
  root: true,
  env: {
    node: true,
    jest: true,
  },
  ignorePatterns: ['.eslintrc.js'], // !!! new and important part !!!
  rules: {
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
};
```

By adding `ignorePatterns: ['.eslintrc.js']` eslint is told to ignore the `.eslintrc.js` file itself.

Otherwise it results in an error, because eslint tries to lint the `.eslintrc.js` file, even though it is not included in the `tsconfig.json` configuration.

See also https://github.com/typescript-eslint/typescript-eslint/issues/967#issuecomment-530907956.

**Comment by jmcdo29** [comment]
The `lint` command that Nest provides in the `package.json` works fine, and I can't reproduce this on VSCode **unless** I open up the `.eslintrc.js` file. However, I do see where this is coming from, so if you'd like to create a PR to the typescript-starter to add that line in, please feel free to do so. I'll double check if any other locations would need it as well.

**Comment by huybuidac** [comment]
`"createDefaultProgram": true` worked, don't know why @@

**Comment by ijash** [comment]
this [answer](https://stackoverflow.com/a/79312456/6274120) works for me:

Solved the problem by adding **ecmaVersion** parameter inside **.eslintrc.js**:  

```js
module.exports = {
  ecmaVersion: 15,
  ...
```
