### ISSUE TITLE
Nest API Reference

### ISSUE THREAD

**Issue by aschrijver** [nestjs/nest#4901]
## Is your feature request related to a problem? Please describe.

The current `docs.nestjs.com` describe how to use Nest, but are not an API reference (even though `awesome-nest` points to it as such). There is an issue from 2018 closed as Duplicate that also mention the need for quick reference API doc: https://github.com/nestjs/nest/issues/474 but I could not find others issues dealing with this.

## Describe the solution you'd like

I'd like to have a Swagger-like reference to what is in the various Nest modules as a reference while coding.

## Teachability, Documentation, Adoption, Migration Strategy

The 'API Reference' can be a menu entry in current Docs site.

## What is the motivation / use case for changing the behavior?

Clarity, ease-of-use, overview, quick reference.

**Comment by jmcdo29** [comment]
[There's an open issue here](https://github.com/nestjs/docs.nestjs.com/issues/249) and a [WIP PR here](https://github.com/nestjs/docs.nestjs.com/pull/413)

**Comment by aschrijver** [comment]
Wow, that PR looks great. Didn't search in the docs repo, sorry. Thanks for pointing me there :+1:
