### ISSUE TITLE
unexpected EOF on client connection with an open transaction

### ISSUE THREAD

**Issue by hejkerooo** [nestjs/nest#4902]
## Current behaviour
When trying to update the entity before insert app stops working (socket hangs up). When I remove subscriber it starts working.

## Input Code
https://gist.github.com/hejkerooo/f8027aaacce8809c25c373218f285653

## Expected behaviour
The entity should be modified, the app should work

## Environment
Ubuntu

<pre><code>
Nest version: 7.1.3

 
For Tooling issues:
- Node version: 12.3
- Postgres 12.3
- Platform:  Ubuntu 19.04
- Docker 19.03.7
- Docker-compose 1.25.4

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
