### ISSUE TITLE
False positive for GET-request with JSON-payload during development

### ISSUE THREAD

**Issue by flaming-codes** [nestjs/nest#4904]
## Current behavior
A GET-request isn't allowed to send params as JSON-payload. This behavior works correctly when deploying the Nest.js-server as a firebase function, as a GET-request with JSON-payload returns a 400.

During local development the request gets accepted, which shouldn't be the case. The local dev server was started using `firebase serve --only functions` as the Nest.js-server is deployed as firebase-function.

## Input Code
```ts
@Controller("user")
export class UserController {
  constructor(private readonly service: UserService) {}

  @Get("meta")
  getMeta(@Body() payload: { id: string }) {
    return payload.id
  }
}

```

## Expected behavior
The GET-request should fail during development and return a 400, as it does in production.

## Environment
<pre><code>
"@nestjs/common": "^7.1.3",
"@nestjs/core": "^7.1.3",
"@nestjs/jwt": "^7.0.0",
"@nestjs/passport": "^7.0.0",
"@nestjs/platform-express": "^7.1.3",
"@nestjs/testing": "^7.1.3",
"express": "^4.17.1",
"firebase-admin": "^8.12.1",
"firebase-functions": "^3.7.0",

For Tooling issues:
- Node version: 10.14.1
- Platform:  Mac (local)
</code></pre>

**Comment by jmcdo29** [comment]
This should be brought up with the underlying adapter's repository owner. [Express](https://github.com/expressjs/express) and [Fastify](https://github.com/fastify/fastify)

**Comment by flaming-codes** [comment]
Ok, thanks. I'll close this issue and report the bug at express, as it's the adapter I'm using.
