### ISSUE TITLE
TestingModuleBuilder is missing overrideModule

### ISSUE THREAD

**Issue by oschlegel** [nestjs/nest#4905]
## Is your feature request related to a problem? Please describe.
I want to use mock modules to override functionalities of the module instead of overriding internals of the module again and again.

## Describe the solution you'd like
A `overrideModule` method similar to `overrideProvider` would solve the issue, example:
```ts
Test.createTestingModule({
  ...
})
  .overrideModule(LoggerModule)
  .useClass(LoggerTestingModule)
  .compile();
```

## What is the motivation / use case for changing the behavior?
For the cases of e2e / integration testing in a project with many encapsulated libraries / modules it would be very helpful to be able to override entire modules instead of overriding internals of the modules every time the module is part of a testing module.

**Comment by kamilmysliwiec** [comment]
Sounds interesting! Would you like to try to create a PR for this issue?

**Comment by moshewe** [comment]
I'm testing in a hyper-microservice environment and I could really use this feature. I was on the cusp of giving up on nestjs e2e testing entirely and just do unit and integration tests (e.g. Postman) because I was loosing too much time on figuring out why certain mocks work and others don't.

@oschlegel let me know how I can help.

**Comment by oschlegel** [comment]
I will build a solution if i can find some time

**Comment by anajuliabit** [comment]
This is exactly what I need. I'm working in a application that has one module whose uses several services from other modules and override all internals modules is very painful

**Comment by joebowbeer** [comment]
See `withModule` method in `TestModuleBuilder` from `@jbiskur/nestjs-test-utilities`

https://www.npmjs.com/package/@jbiskur/nestjs-test-utilities

**Comment by leonardovillela** [comment]
Hi everyone, good evening. I took some time last week to add this functionality on `testing-module.builder.ts` API.

Maintainers(cc: @kamilmysliwiec) when you have time please, take a look at [this PR](https://github.com/nestjs/nest/pull/8777).

**Comment by kamilmysliwiec** [comment]
Thanks @leonardovillela! Let's track this here https://github.com/nestjs/nest/pull/8777

**Comment by jdelgado-fortis** [comment]
Do we have any updates on the PR? https://github.com/nestjs/nest/pull/8777

I could really use this feature! :)

**Comment by MartianH** [comment]
> Do we have any updates on the PR? #8777
> 
> I could really use this feature! :)

I concur. Would be very useful.

**Comment by navarrojava** [comment]
+1

**Comment by elovin** [comment]
As far as I can tell this has been added to nestjs 10 ?!

Yet when the inject "CACHE_MANAGER" does not use the settings from the overwritten module:

`@Inject(CACHE_MANAGER) cacheManager: Cache`


```typescript

class MockCacheModule extends CacheModule {
	static override register<StoreConfig extends Record<any, any> = Record<string, any>>(
		options?: CacheModuleOptions<StoreConfig>,
	): DynamicModule {
		return CacheModule.register({ ...options, ttl: 100 });
	}
}

const module = await Test.createTestingModule({
	imports: [DatabaseModule],
})
	.overrideProvider(ProjectConfigService)
	.useClass(ProjectConfigTestService)
	.overrideModule(CacheModule)
	.useModule(MockCacheModule)
	.compile();

```

**Comment by fmrsabino** [comment]
> As far as I can tell this has been added to nestjs 10 ?!
> 
> Yet the injected "CACHE_MANAGER" does not use the settings from the overwritten module:

I had a similar issue with a `DynamicModule`. I got a suggestion on how to tackle it in https://github.com/nestjs/nest/issues/11967. It might help with your use-case.
