### ISSUE TITLE
mongoose type hints 

### ISSUE THREAD

**Issue by lukasfrank** [nestjs/nest#4906]
## Current behavior
- define a schema  
- query document 
- type is always schema 

## Input Code

```ts
  constructor(
    @InjectModel(User.name) private readonly userModel: Model<User>,
  ) {}

  async findOneByEmail(email: string): Promise<User | null> {
   //type: User
   // expected type: User | null
    const user = await this.userModel.findOne({ email }).exec();
    return user;
  }
```

## Expected behavior
expected type: User | null

## Environment

Nest version: 7.1.3

**Comment by jmcdo29** [comment]
`Model` comes from the [`mongoose`](https://github.com/Automattic/mongoose) repository, along with all of the types following from its functions (like `findOne`). This should be brought up with their repository.
