### ISSUE TITLE
Two injectables which have useValue dependency, break when one starts depending on the other

### ISSUE THREAD

**Issue by 1valdis** [nestjs/nest#4908]
## Current behavior
I have a single dynamic module with 3 providers, 2 of them being injectables and the other created with useValue. Both injectables inject provided useValue into themselves and it works fine. But as soon as one of them starts depending on the other, it breaks. The error makes not much sense: `Nest can't resolve dependencies of the SomeModuleApi (?). Please make sure that the argument dependency at index [0] is available in the SomeModule context.`. So it complains that value provided with useValue is unavailable.

## Input Code
Reproduction repo: https://github.com/1valdis/nest-usevalue-bug (search "uncomment this line", uncomment and observe it breaking)

```typescript
export class SomeModule {
  static register(options: SomeModuleOptions): DynamicModule {
    return {
      imports: [],
      module: SomeModule,
      providers: [
        {
          provide: SomeModuleOptionsSymbol,
          useValue: options,
        },
        SomeModuleApi,
        SomeModuleProvider
      ]
    }
  }
}
```

```typescript
@Injectable()
export class SomeModuleApi {
  constructor(@Inject(SomeModuleOptionsSymbol) private readonly options: SomeModuleOptions) {}
}

@Injectable()
export class SomeModuleService {
  constructor(
    // private readonly api: SomeModuleApi, // uncomment this line to make it die horribly
    @Inject(SomeModuleOptionsSymbol) private readonly options: SomeModuleOptions
  ) {}
}
```

## Expected behavior
It just works. The options get passed to SomeModuleApi injectable, then this injectable along with the same options gets passed to SomeModuleService injectable.

## Environment

Nest version: 7.0.0
 
For Tooling issues:
- Node version: 12.6.1
- Platform:  Mac

**Comment by IMalyugin** [comment]
That is called circular dependency. Anything bundled with circular dependencies would break, nest is not an exception. There is a guide on how to prevent circular dependencies from ruining your day. While the best advice would be - design your system to prevent them from happening.

https://docs.nestjs.com/fundamentals/circular-dependency

**Comment by 1valdis** [comment]
@IMalyugin excuse me, how is this a circular dependency? There's no loops in the dependency tree:
![image](https://user-images.githubusercontent.com/18512697/84687780-f159ff00-af46-11ea-8ce5-7c1e21ccb8c8.png)

**Comment by jmcdo29** [comment]
@1valdis there is, however, a circular dependency between the files, due to how you have your providers set up. I can make a fork and PR of your repo if you'd like. This isn't an issue with Nest though.

**Comment by 1valdis** [comment]
@jmcdo29 I'd very welcome your PR. Nest docs say about _classes (or, providers)_ depending on each other, not _files_. That sounds strange to me, although I'm a newbie in Nest.

**Comment by 1valdis** [comment]
@jmcdo29 Got your PR. Thank you. I must say that I didn't bother about where exactly my interface and symbols were declared, I was much more concerned about my provider/dependency structure in Nest terms. It's not circular. File structure however is, as you and @IMalyugin pointed out. I still don't particularly understand, why it all doesn't break immediately as I make circular `import` statements. I'll dig deeper in Typescript on that, it seems. You are free to close the issue, thank you again for your help.
