### ISSUE TITLE
I want to Permit controller access if one of guard return true. 

### ISSUE THREAD

**Issue by programmerkgit** [nestjs/nest#4910]
`@UseGuard` reject controller access if one of 'Guard' return false.    
However,  I want to permit api call if one of guards return true.   

For example Consider about some project management application, where system admin can call all api, and project's admin user call project update api. 

Then, I suggest `@PermitGuard` syntax like :

```
@Controller("project")
export class ProjectController {
  @Put(":id")
  @PermitGuard([SystemAdminGuard, ProjectAdminGuard])
  updateProject(): string {
      // some 
  }
}
```
Then updateProject can be called by System Admin User or Project admin user.
`PermitGuard` allow access to controller if one of `Guard` arguments return true, otherwise reject access to controller.

**Comment by kamilmysliwiec** [comment]
> However, I want to permit api call if one of guards return true.

You can create a composite guard that runs specific guards in an appropriate order.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
