### ISSUE TITLE
Swagger plugin boolean

### ISSUE THREAD

**Issue by adelin-b** [nestjs/nest#4913]
## Current behavior
- boolean parameters are not recognized using swagger plugin
- swagger decorators or the swagger plugin are not casting the boolean into a boolean, its a nothing, or a string with true/false inside, it lead to corrupted data in the dto.

## Input Code

```ts
export class testDto {
  @ApiProperty({ required: false, default: true }) // when this is commented swagger-plugin doesn't give a scrolldown menu
  test?: boolean = true;
}
```
This had been tried with and without 
```ts
// test.dto.ts
@ApiProperty({ required: false, default: true }) // when this is commented swagger-plugin doesn't give a scrolldown menu
// @IsBooleanString
@IsBoolean
  test?: boolean = true;


// main.ts
  /* Validate all the requests when class-validator are used to define dto */
  app.useGlobalPipes(new ValidationPipe({ transform: true }));

```
## Current solution
This is what I do to fix it, I really wouldn't want to do that
```ts
  @ApiProperty({ required: false, default: true })
  @Transform((value: any) => value === 'true' || value === true || value === 1 || value === '1')
  test?: boolean = true;
```

## Expected behavior
should turn into boolean

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by darioielardi** [comment]
@adelin-b Did you find out the reason or any valid workaround for this? Thanks

**Comment by adelin-b** [comment]
The only workaround I found was the use of the transform decorator casting it in boolean.

I believe this is a bug because the doc state that
```ts
@ApiProperty({ required: false, default: true }) isEnabled?: boolean = true;
```
Is equivalent of
```ts
isEnabled?: boolean = true;
```
Which is not the case
