### ISSUE TITLE
PassportStrategy: default field value is username and password, how do I set the other fields, example email and password ?

### ISSUE THREAD

**Issue by MutelyMilo** [nestjs/nest#4918]
import { Injectable, UnauthorizedException } from '@nestjs/common';
import { PassportStrategy } from '@nestjs/passport';
import { Strategy } from 'passport-local';
import { AuthService } from '../auth.service';

@Injectable()
export class LocalStrategy extends PassportStrategy(Strategy) {
  constructor(private readonly authService: AuthService) {
    super();
  }

  async validate(email: string, password: string): Promise<any> {
    const user = await this.authService.validateUser(email, password);
    if (!user) {
      throw new UnauthorizedException();
    }
    return user;
  }
}

This is my code
It'll return the Unauthorized when I request the interface and add email and password

**Comment by jmcdo29** [comment]
Please, use our [Discord](https://discord.gg/NestJS) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by MutelyMilo** [comment]
I connot connect the website, maybe because I'm in China ?

**Comment by msheakoski** [comment]
Hi @MutelyMilo. This section of the docs shows how you can change the default username/password fields and send other options to a passport strategy:

https://docs.nestjs.com/techniques/authentication#customize-passport

Taking your example, it would look like this:
```typescript
@Injectable()
export class LocalStrategy extends PassportStrategy(Strategy) {
  constructor(private readonly authService: AuthService) {
    super({ usernameField: "email" })
  }

  async validate(email: string, password: string) {
    // ...
  }
}
```

**Comment by amiraatalla** [comment]
how can I convert that to login by email or username and password
![image](https://user-images.githubusercontent.com/52547252/134005180-f0445939-97e8-4617-89fc-c7eca9427afa.png)

**Comment by micalevisk** [comment]
@amiraatalla you could treat the `email` parameter of `validate` method as "email or username". And then write this logic in your `AuthService#validateUser`.

We can talk more about this in https://discord.gg/NestJS
