### ISSUE TITLE
Activate a component by profiles

### ISSUE THREAD

**Issue by hantsy** [nestjs/nest#4927]
## Is your feature request related to a problem? Please describe.
I have a question published on stackoverflow, https://stackoverflow.com/questions/62462487/how-to-activate-a-component-by-conditons-in-nestjs. How to activate service by env variables or profile(a concept in Spring)? Eg. I have a DataInitializer (using `@Injectable`) service which is for inserting some data when the application is starting.

```typescript
@Injectable()
export class PostDataInitializerService implements OnModuleInit, OnModuleDestroy {
  private data: CreatePostDto[] = [
    {
      title: 'Generate a NestJS project',
      content: 'content',
    },
    {
      title: 'Create CRUD RESTful APIs',
      content: 'content',
    },
    {
      title: 'Connect to MongoDB',
      content: 'content',
    },
  ];

  constructor(private postService: PostService) {}
  onModuleInit(): void {
    console.log('(PostModule) is initialized...');
    this.data.forEach(d => {
      this.postService.save(d).subscribe(saved => console.log(saved));
    });
  }
  onModuleDestroy(): void {
    console.log('(PostModule) is being destroyed...');
    this.postService
      .deleteAll()
      .subscribe(del => console.log(`deleted ${del.deletedCount} rows`));
  }
}
```
but I want to **disable the service**(do not need this service) in a production env, how to archive this purpose?

## Describe the solution you'd like
1. Add a `@Profile` to component(controller, any @Injectable components), eg. 
    ```typescript
       @Profile("dev")
       @Injectable()
        export class DataInitializer {}
    ```
2. When I switch to production, add CLI parameters, or set system env variables to active related profiles.
    eg. 

    ```bash
    node dist/main.js --nestjs-profiles-active="prod, !dev"
    ```
    or set env variables in .evn file, docker/k8s env variables.
    
   ```bash
   NESTJS_PROFILES_ACTIVE=prod,!dev
   ```

## Migration 

Every injectable component has a **default** profile if it is not set. And *default* profile is always active unless you disable it explicitly by appending a `!default` in the *nestjs-profiles-active* parameters. 

For any other user custom profiles, if they are not in the active list or disabled by appending a `!` char, they will be NOT active by default.

esp, for example, if there are two custom profiles: *prod*, *dev*.

   ```bash
   NESTJS_PROFILES_ACTIVE=prod,!dev //prod,default profiles are active, dev is NOT
   ```
   is equal to 
   ```bash
   NESTJS_PROFILES_ACTIVE=prod //prod,default profiles are active, dev is NOT
   ```
  
  But 
  
   ```bash
   NESTJS_PROFILES_ACTIVE=prod,!default //prod is active, default and dev are NOT
   ```
   is very different from 

   ```bash
   NESTJS_PROFILES_ACTIVE=prod  //prod and default profiles are active, dev is NOT
   ```

 Another challenge is from the registration of the multi implementation of interfaces.  

```typescript 
export interface OrderService{}
```
``` typescript
@Profile("typeorm")
@Injectable
export class TypeORMOrderService implements OrderService{}
```

``` typescript
@Profile("mongoose")
@Injectable
export class MongooseOrderService implements OrderService{}
```
When registering in `@Module`, it should provide some ways to allow multi implementations.  I remember  Angular some components(eg. form validators) in `@NgModule` has such options. 

## What is the motivation / use case for changing the behavior?

Ignore the instantiation of the service/components when it is NOT in the active profiles.

**Comment by kamilmysliwiec** [comment]
For this, you should use dynamic modules (https://docs.nestjs.com/fundamentals/dynamic-modules) & custom providers (https://docs.nestjs.com/fundamentals/custom-providers) features.

> Another challenge is from the registration of the multi implementation of interfaces.

You can accomplish this without any additional decorators:

```typescript
{
   provide: OrdersService // where "OrdersService" is an abstract class or a token
   useClass: process.env.PROFILE_DB === 'typeorm' ? TypeORMOrderService : MongooseOrderService // if you need more options, you can use "switch" instead
}
```

> but I want to disable the service(do not need this service) in a production env, how to archive this purpose?

There are several ways. Depending on your use-case, you can use either dynamic modules, lifecycle hooks, or custom providers.

NestJS DI & modules system is flexible enough to cover all cases you described.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
