### ISSUE TITLE
Question about the injection of the global registered filter

### ISSUE THREAD

**Issue by wayou** [nestjs/nest#4929]
I setup a [repo](https://github.com/wayou/nest-global-filter-injection-issue) to illustrate this.

According to [the doc](https://docs.nestjs.com/exception-filters#exception-filters-1),

if using `  app.useGlobalFilters(new HttpExceptionFilter());` to register the filter, the filter cannot be injected directly but:

```ts
import { Module } from '@nestjs/common';
import { APP_FILTER } from '@nestjs/core';

@Module({
  providers: [
    {
      provide: APP_FILTER,
      useClass: HttpExceptionFilter,
    },
  ],
})
export class AppModule {}
```

however, in this repo I still can inject the filter normally:

```diff
import { Controller, ForbiddenException, Get } from '@nestjs/common';
import { HttpExceptionFilter } from '../exception/http-excption.filter';

@Controller('cats')
export class CatsController {
+  constructor(private readonly filter: HttpExceptionFilter) {
+    console.log('look, the filter been injected', this.filter);
+  }
  @Get()
  async create() {
    throw new ForbiddenException();
  }
}

```

**Comment by jmcdo29** [comment]
I think there's some confusion about what it means to inject in this case. What the docs are trying to say is that by using `app.useGlobalFilters`, the DI system will not handle injecting the filter's dependencies into it, and instead it would be up to the developer to call `app.get()` for each of the filter's dependencies. When you use the `APP_FILTER` method, however, dependency injection works normally and Nest takes care of it all under the hood.
