### ISSUE TITLE
Auto update for nest js based application.

### ISSUE THREAD

**Issue by sameerinfodb** [nestjs/nest#4935]
We have created the API service using nest js, we are looking for auto updater for nestjs based application. so that when we have the newest version of API service , it can update the service automatically. Do we have this feature in-built int nestjs. if not, what are the option we have to achieve this functionality.

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for Support. We are using GitHub to track Feature Requests and Bug Reports.
