### ISSUE TITLE
PassportStrategy validate method should support Rxjs Observerable as return type

### ISSUE THREAD

**Issue by hantsy** [nestjs/nest#4938]
## Is your feature request related to a problem? Please describe.
Add  `Obseverable` as an option of the return type.

## Describe the solution you'd like
I would like to use Rxjs API as possible in my application because I have some experience of Angular, but unfortunately, in the NestJS application,  it mixes Promise and Observable.

I try to use `Observable` as validating return type, it does not work.

```typescript
@Injectable()
export class LocalStrategy extends PassportStrategy(Strategy) {
  constructor(private authService: AuthService) {
    super({
      usernameField: 'username',
      passwordField: 'password',
    });
  }

 validate(username: string, password: string): Observable<any> {
   return this.authService
     .validateUser(username, password)
     .pipe(throwIfEmpty(() => new UnauthorizedException()));
 }
}
```

## Teachability, Documentation, Adoption, Migration Strategy
Currently, it only supports Promise, and any simple type, but does not support Rxjs  Observable.

```typescript
  async validate(username: string, password: string): Promise<any> {
    const user = await this.authService
      .validateUser(username, password)
      .toPromise();

    if (!user) {
      throw new UnauthorizedException();
    }

    return user;
  }
```

## What is the motivation / use case for changing the behavior?

Support Rxjs `Observable`

**Comment by jmcdo29** [comment]
It absolutely does support promises. [You can see an example here (local)](https://github.com/jmcdo29/zeldaPlay/blob/master/apps/api/src/app/auth/local.strategy.ts) and [here (google)](https://github.com/jmcdo29/zeldaPlay/blob/master/apps/api/src/app/auth/google.strategy.ts)

**Comment by hantsy** [comment]
@jmcdo29 I will verify it again, I have changed my codes to Promise to make it work now. Thanks.

**Comment by hantsy** [comment]
Maybe the pipe is not correct.
```typescript
.pipe(throwIfEmpty(() => new UnauthorizedException()));
```
I am not sure if the user not found what Mongoose reuturns.

**Comment by jmcdo29** [comment]
Can't say with the rest of your code, as it isn't visible, but it is possible. For further support, please use our [Discord](https://discord.gg/nestjs). You're also welcome to look through the rest of the project above to see if it can help you find your problem

**Comment by hantsy** [comment]
OK, Thanks.

**Comment by Jintus** [comment]
I do not understand why this Issue as been closed.

The suggested code from @hantsy works well if we add `firstValueFrom` operator to transform Observable into Promise but if we use the code as it, the request attribute `user` will be populate with the observable, so the controller will be triggered.

For this controller :

```ts
@UseGuards(LocalAuthenticationGuard)
@Post('/auth/login')
login(@Request() req: { user: AuthenticatedUser }) {
  console.log('Controller', req.user);
  return req.user;
}
```
---

With bad credentials :
```ts
async validate(email: string, password: string): Promise<AuthenticatedUser | undefined> {
  return firstValueFrom(this.authenticationService.validateUser(email, password).pipe(
    throwIfEmpty(() => new UnauthorizedException())
  ));
}

// Will not trigger Controller console log
```
```ts
async validate(email: string, password: string): Observable<AuthenticatedUser | undefined> {
  return this.authenticationService.validateUser(email, password).pipe(
    throwIfEmpty(() => new UnauthorizedException())
  );
}

// Will trigger Controller console log, with req.user to be the entire Observable
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
