### ISSUE TITLE
Integrating logic with dynamic table name with TypeOrm

### ISSUE THREAD

**Issue by balibou** [nestjs/nest#4939]
I'm trying to use the same entity for different tables.

Basically I fetch a list of stocks with different prices: open / high / low / close / volumes.
And I want a table for each of those stocks.

I went through this article: https://medium.com/@terence410/working-with-dynamic-table-name-with-typeorm-6a67128b9671

But I'm still struggling to make it work for nest 7.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
