### ISSUE TITLE
compilation error in websocket  io-adapter.d.ts

### ISSUE THREAD

**Issue by soundarpandiyan** [nestjs/nest#494]
Hi guys, i'm getting compilation error when i try to use websockets. Can you please let me know how to resolve this issue.
```
node_modules/@nestjs/websockets/adapters/io-adapter.d.ts(2,23): error TS2688: Cannot find type definition file for 'socket.io'.
node_modules/@nestjs/websockets/adapters/io-adapter.d.ts(14,27): error TS2503: Cannot find namespace 'SocketIO'.
node_modules/@nestjs/websockets/adapters/io-adapter.d.ts(16,35): error TS2503: Cannot find namespace 'SocketIO'.
```

**Comment by soundarpandiyan** [comment]
The issue has been resolved after installing the @types/socket.io so closing the issue

**Comment by EreckGordon** [comment]
I added socket.io (^2.0.4) and while it got rid of the first error you pasted, the lower 2 remain. What exactly did you install to fix your error, @soundarpandiyan ?

**Comment by soundarpandiyan** [comment]
Please install the types for socket.io hopefully the issue will get resolved

```
npm install --save @types/socket.io
```

**Comment by BorntraegerMarc** [comment]
Ah seems it is an official bug https://github.com/nestjs/nest/issues/512
