### ISSUE TITLE
Custom DI Class-Validators Break Mono Repo Architecture

### ISSUE THREAD

**Issue by tommyc38** [nestjs/nest#4945]
## Bug Report
Custom DI Class-Validators Breaks Mono Repo Architecture. 
## Current behavior
I have a mono repo where the font/backend share the same interfaces / classes for data structures (e.g. Angular + Nestjs).  I decided to implement a custom class-validator as described [here.](https://github.com/nestjs/nest/issues/528)  The problem I am facing with this implementation is that I am importing a Nest Injectable into the same file aslo used by Angular which defines a class (e.g. Users).  Moreover, this also introduces circular dependancies which I was able to get around this by creating more Nest Libs (not the end of the world but not ideal either).  

See below for possible solution to resolve both issues.

## Input Code

In bootstrap function:
```ts
     const app = await NestFactory.create(ApplicationModule);
     useContainer(app.select(ApplicationModule), { fallbackOnErrors: true });
     await app.listen(config.api.port);
```

custom class validator:
```ts
     @ValidatorConstraint({ name: 'isUserAlreadyExist', async: true })
     @Injectable()
     export class IsUserAlreadyExist {
       constructor(
         @Inject('UserService') private readonly userService: UserService,
       ) {}

       async validate(text: string) {
         const user = await this.userService.findOneByEmail(text);
         return !user;
       }
}
```
User entity (this is shared by both Nest and Angular):
```ts
     @Entity()
     export default class User {
      @PrimaryGeneratedColumn('uuid') id: string;

      @IsNotEmpty()
      @MaxLength(100)
      @Validate(IsUserAlreadyExist) //<--ISSUE IMPORTING CLASSS HERE
      @IsEmail()
      @Column({
         type: 'varchar',
         length: 100,
         primary: true,
      })
  email: string;
}
```

## Expected behavior
I shouldn't have to import a backend class into a shared backend/front file.

## Possible Solution

Off the top of my head, I would think NestJs would need a wrapper decorator around class-validator's `@Validate()` decorator where, instead of passing a class, as in the case above, a string token is passed, `@Validate('isUserAlreadyExist')` that Nest could use to resolve to the actual class while Angular (or any other front end) would ignore it.

**Comment by kamilmysliwiec** [comment]
`ValidatorConstraint` is a `class-validator` feature, not NestJS. The technique which uses `useContainer()` is just a workaround to share the same IoC container. This issue isn't related to NestJS framework itself.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by tommyc38** [comment]
@kamilmysliwiec that is true but NestJs has “out of the box” support for using their library and has tons of documentation with how to implement it.  I would appreciate it if you and your team would reconsider this a bug.  I can’t be the only person using NestJs and class-validator in a monorepo.

**Comment by jmcdo29** [comment]
@tommyc38 can you provide a minimum reproduction of this, because without that, it's pretty much a moot point about considering the "bug".

**Comment by tommyc38** [comment]
Yes, I will provide a repro.

**Comment by tommyc38** [comment]
After a lot of research, it looks like Storybook / Webpack are not compiling correctly.  However, I did setup a repro, below, in case anyone else runs into the same issue I had, you can send them there.

Repro: https://github.com/storybookjs/storybook/issues/11309
Similar Webpack Issue: https://github.com/webpack/webpack/issues/7378#issuecomment-649286854
Storybook Issue: https://github.com/storybookjs/storybook/issues/11309
