### ISSUE TITLE
Documention Update: Pipes with config AND dependency

### ISSUE THREAD

**Issue by tommyc38** [nestjs/nest#4949]
## Current behavior
Your docs give great examples of how to configure a Pipe for DI or an options object but not both.  The use case below would allow me to create one pipe that I could configure for any request object by supplying the property name containing the file path value.  As it stands, I would basically need to create the same pipe over and over again for requests with different request signatures.  This example is contrived but hopefully you could see how it could be beneficial.

## Input Code

pipe.ts
```ts
@Injectable()
export class FileExistsPipe implements PipeTransform {

  constructor(private filePath: string, db: DatabaseService) { }

  async transform(value: any, metadata: ArgumentMetadata) {
    const path = value[this.filePath];
    const doesExist =  await this.db.file(path).exists()
    if(!doesExist)  throw new BadRequestException();
    return value;
  }
}
```
controller.ts
```ts
interface JobRequest {
   input: 'path/to/file/on/server'
}

@Controller('transcode')
export class TranscodeController {

  @Post()
  async transcode ( 
    @Body( new FileExistsPipe('input')) transcodeRequest: JobRequest) {
    return await this.videoProducer.addJob(transcodeRequest);
  }
```
## Expected behavior
The above solution doesn't work because the call to `new FileExistsPipe('input')` needs two arguments, the second being the DatabaseService dependency.  The other option would be to do `@Body(FileExistsPipe)` but then I wouldn't be able to pass my property name to my pipe to look up in the request object.

## Possible Solution
I have posted this question on stackoverflow,[ here](https://stackoverflow.com/questions/62526828/how-to-create-a-nestjs-pipe-with-a-config-object-and-dependency), in case you would prefer to leave the documentation as is.

**Comment by nartc** [comment]
@tommyc38 this can be achieved with `Mixin`.
@jmcdo29 is it time that a documentation on `Mixin` due?

**Comment by tommyc38** [comment]
@nartc, Thanks!

I tried your implementation but am getting the following error in my IDE (e.g. `@Body(FIleExistPipe('input'))`.  I tried to comment on your answer but they don't give me enough characters.  FYI, I am using Lodash's memoize function.  

Any ideas whats going on here?

```
TS2769: No overload matches this call.   Overload 1 of 3, '(...pipes: (PipeTransform<any, any> | 
Type<PipeTransform<any, any>>)[]): ParameterDecorator', gave the following error.     Argument 
of type 'CanActivate' is not assignable to parameter of type 'PipeTransform<any, any> | 
Type<PipeTransform<any, any>>'.       Type 'CanActivate' is missing the following properties from 
type 'Type<PipeTransform<any, any>>': apply, call, bind, prototype, and 5 more.   Overload 2 of 3, 
'(property: string, ...pipes: (PipeTransform<any, any> | Type<PipeTransform<any, any>>)[]): 
ParameterDecorator', gave the following error.     Argument of type 'CanActivate' is not assignable 
to parameter of type 'string'.
```

**Comment by jmcdo29** [comment]
@nartc yeah, docs on Mixins would be nice. I know there are already some docs about what a mixin is on Typescript's website, but it would be nice to have a section in the Nest docs about it

@tommyc38 it looks like you're using a class that implements `CanActivate` instead of `PipeTransform`. I pipes are the only thing that can works with the `@Body()` decorators (and similar), so the `CanActivate` (guard) is giving a problem

**Comment by nartc** [comment]
> @nartc, Thanks!
> 
> I tried your implementation but am getting the following error in my IDE (e.g. `@Body(FIleExistPipe('input'))`. I tried to comment on your answer but they don't give me enough characters. FYI, I am using Lodash's memoize function.
> 
> Any ideas whats going on here?
> 
> ```
> TS2769: No overload matches this call.   Overload 1 of 3, '(...pipes: (PipeTransform<any, any> | 
> Type<PipeTransform<any, any>>)[]): ParameterDecorator', gave the following error.     Argument 
> of type 'CanActivate' is not assignable to parameter of type 'PipeTransform<any, any> | 
> Type<PipeTransform<any, any>>'.       Type 'CanActivate' is missing the following properties from 
> type 'Type<PipeTransform<any, any>>': apply, call, bind, prototype, and 5 more.   Overload 2 of 3, 
> '(property: string, ...pipes: (PipeTransform<any, any> | Type<PipeTransform<any, any>>)[]): 
> ParameterDecorator', gave the following error.     Argument of type 'CanActivate' is not assignable 
> to parameter of type 'string'.
> ```

Looks like I made a mistake on my reply (was copy-paste one of the mixin I have in my app). Just updated the answer. And it is exactly like @jmcdo29 said.

**Comment by tommyc38** [comment]
@nartc, Thank you again for the update which fixed my IDE issue.  However, it doesn't look like Nest is injecting my dependency, DatabaseService, because its throwing an error as it is undefined.  Moreover, my database service is in a lib, inside of a `@Global()` module (in case that matters).  I have had no issues with DI working with my DatabaseService  til now.  Any thoughts?

**Comment by tommyc38** [comment]
There error only happens when I make a request to the api.

**Comment by nartc** [comment]
Can you provide a repro?

**Comment by tommyc38** [comment]
@nartc, yes.

**Comment by tommyc38** [comment]
https://github.com/tommyc38/nest-pipe-repro

I included instructions in the README.  Should be pretty straightforward.  Note, I am also creating another Nest repro and am using this for that as well.

**Comment by tommyc38** [comment]
56654386e09eb9c812b670f79da5cc9fad25a7f8

@nartc please refer to this commit for the repro.  I have since turned this repo into another issue.  Let me know if you have any questions.  Thanks again for the help!

**Comment by kamilmysliwiec** [comment]
I went through this issue real quick and I can see that this is neither a bug nor a feature request. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by tommyc38** [comment]
@nartc can you please delete your answer on Stackoverflow since it doesn’t work.

**Comment by nartc** [comment]
@tommyc38 I just checked your repo (sorry for missing it before). Your `DatabaseService` is `undefined` in the `FIleExistPipe` because you use the pipe in `AppController`. `AppController` will be resolved before the `DatabaseModule` gets resolved. You can use `forwardRef()` to inject the `DatabaseService` in your pipe if you are going to use the pipe in `AppController`. The good practice here is to have feature controllers provided in feature modules. 

```ts
export const FileExistPipe: (filePath: string) => PipeTransform = memoize(
  createFileExistPipe
);

function createFileExistPipe(filePath: string): Type<PipeTransform> {
  class MixinFileExistPipe implements PipeTransform {
    constructor(
      // use forwardRef here
      @Inject(forwardRef(() => DatabaseService)) private db: DatabaseService 
    ) {
      console.log(db);
    }

    async transform(value: ITranscodeRequest, metadata: ArgumentMetadata) {
      console.log(filePath, this.db);
      const doesExist = await this.db.checkFileExists(filePath);
      if (!doesExist) throw new BadRequestException();
      return value;
    }
  }

  return mixin(MixinFileExistPipe);
}
```

this is the fix btw

**Comment by tommyc38** [comment]
@nartc thank you!  I accepted your answer on Stackoverlow.  Much appreciated.

**Comment by aberrier** [comment]
Any plans to update the documentation to properly document this case with an official example ?

**Comment by micalevisk** [comment]
@aberrier feel free to open a new pull request to introduce an example of this. This is from 2020, we aren't tracking it anymore.
