### ISSUE TITLE
i have a problem when running npm i

### ISSUE THREAD

**Issue by AlirezaEbrahimkhani** [nestjs/nest#4952]
Hi i got this error when running npm i :/

`npm ERR! code EINVALIDTAGNAME`
`npm ERR! Invalid tag name ">=0.2.1.1": Tags may not have any characters that encodeURIComponent encodes.`
`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /home/alireza/.npm/_logs/2020-06-23T20_12_26_681Z-debug.log`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by AlirezaEbrahimkhani** [comment]
ok thanks for your suggestion :heart:
