### ISSUE TITLE
Map src directory in package.json  jest config

### ISSUE THREAD

**Issue by cdcarson** [nestjs/nest#4953]
## Feature Request
Add an entry to `package.json` (created with `nest new`) that tells Jest to map the `src` path correctly. 

## Is your feature request related to a problem? Please describe.
I like to use  **nice, concise** import statements  like this:

```
@import { FooService } from 'src/core/foo.service';
```
...rather than **nasty nested ones**, like this...

```
@import { FooService } from '../../../../core/foo.service';
```

The nice, first option complies fine when building, but fails when running Jest. 

## Describe the solution you'd like

This can be fixed easily by adding  a `moduleNameMapper` to the Jest config in `package.json`:
```
"moduleNameMapper": {
    "^src/(.*)$": "<rootDir>/$1"
},
```
The full `jest` entry...
```json
"jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "moduleNameMapper": {
      "^src/(.*)$": "<rootDir>/$1"
    },
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
```

## What is the motivation / use case for changing the behavior?

It seems that VSCode currently uses  the **concise**  style for deeply nested imports in Nest projects -- i.e when automatically importing other modules via autocomplete.  It would be nice if the Jest config were set up to handle this style out of the box -- it took me a while to figure it out from the Jest docs.

**Comment by kamilmysliwiec** [comment]
This has been discussed multiple times in the past already (see "Issues" history).

> I like to use nice, concise import statements like this:

Using absolute imports with `src` included is not recommended and is considered a bad practice.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
