### ISSUE TITLE
How can I use OData query with nestjs

### ISSUE THREAD

**Issue by RezaRahmati** [nestjs/nest#496]
Hey

Thanks for great work, I was wondering if there is any way to use OData queries along with nest.js, something like [this library](https://www.npmjs.com/package/odata-v4-server)

**Comment by kamilmysliwiec** [comment]
I guess that there's no mature solution available so far. You should check whether there're some existing express packages that provide OData wrappers, maybe there compatible with Nest as well.

**Comment by johannesschobel** [comment]
Hey @RezaRahmati ,

just wondering if you found a proper solution for your problem? I am currently in need of a `OData > NestJS > TypeORM` solution and thought you may be able to help me?!

All the best

**Comment by RezaRahmati** [comment]
Unfortunately not
