### ISSUE TITLE
Has there been any talks about creating Nest for Deno?

### ISSUE THREAD

**Issue by cafesanu** [nestjs/nest#4963]
## Feature Request
I was just wondering, given the sudden buzz about Deno(https://deno.land/v1), and given how relatively new Nest is, if you have given a thought about doing Nest for Deno. I think this would be awesome and Nest could capture a whole future market that has yet to exist. I know this is risky, but if Deno succeeds, the reward would be great!

Here is an interesting article I just read that makes me think Deno might be the future... https://blog.bitsrc.io/node-to-deno-first-impression-d2b41b920c1f

**Comment by jmcdo29** [comment]
[Yes](https://github.com/nestjs/nest/issues/4876) [there](https://github.com/nestjs/nest/issues/4832) [has](https://github.com/nestjs/nest/issues/4495) [been](https://github.com/nestjs/nest/issues/3464) [talks](https://github.com/nestjs/nest/issues/1796) of deno support. (each of those is a separate link)

**Comment by cafesanu** [comment]
wow I am so sorry. Forgot to do my research... closing this shamefully with the tail between my legs...
![](https://media.tenor.com/images/b9dd3777f397ea56bf51eebf4a0eca91/tenor.gif)

**Comment by FrancescoBorzi** [comment]
I'm commenting here since the other thread is locked.

> let's see how Deno evolves over time. If the community grows rapidly, I'll certainly consider porting several core mechanisms to Deno, respecting their style guide and conventions. It doesn't make any sense at this point though.

this comment from @kamilmysliwiec was about 1 year ago, I was wondering if there are some plans now that Deno has been growing in both maturity and popularity. It would be great if NestJS supported Deno out of the box.

**Comment by kamilmysliwiec** [comment]
There's no plan to support Deno atm. The reason is that I currently don't see any benefit in using Deno instead of Node.js.
