### ISSUE TITLE
Cannot inject request to request-scoped service with moduleRef resolve method

### ISSUE THREAD

**Issue by piotr-pawlowski** [nestjs/nest#4967]
## Current behavior
I cannot inject Request into service with moduleRef resolve method. The request object is always undefined. I'd like to inject request-scoped service into singleton-scoped controller.

## Input Code

app.service.ts
```ts
import { Injectable, Scope, Inject } from '@nestjs/common';
import { REQUEST } from '@nestjs/core'

@Injectable({ scope: Scope.REQUEST })
export class AppService {

  constructor(@Inject(REQUEST) request: any) {
    console.log(request) //undefined
  }

  getHello(): string {
    return 'Hello World!';
  }
}
```

app.controller.ts
```ts
import { Controller, Get } from '@nestjs/common';
import { ModuleRef } from '@nestjs/core';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly moduleRef: ModuleRef) {}

  @Get()
  async getHello(): Promise<string> {
    return (await this.moduleRef.resolve(AppService)).getHello()
  }
}
```

app.module.ts
```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

## Environment

<pre><code>
"@nestjs/common": "^7.0.0",
"@nestjs/core": "^7.0.0",
"@nestjs/platform-express": "^7.0.0",
"reflect-metadata": "^0.1.13",
"rimraf": "^3.0.2",
"rxjs": "^6.5.4"
</code></pre>

**Comment by piotr-pawlowski** [comment]
@kamilmysliwiec please, take a look. I can't go further with my work :(

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction Repository. We are working through bugs as we can

**Comment by piotr-pawlowski** [comment]
> Please provide a minimum reproduction Repository.

https://github.com/piotr-pawlowski/nestjs-inject-request-issue

**Comment by kamilmysliwiec** [comment]
We've added the `registerRequestByContextId()` method to the `ModuleRef` in 7.3.0 release. Example

```typescript
const contextId = ContextIdFactory.create();
this.moduleRef.registerRequestByContextId(YOUR_REQUEST_OBJECT, contextId);
const appService = await this.moduleRef.resolve(AppService, contextId);
```

**Comment by piotr-pawlowski** [comment]
Does it work with GraphQL `Context` as well? I mean injecting a context: `@Inject(CONTEXT)`  and a request: `@Inject(REQUEST)`.
