### ISSUE TITLE
ValidationPipe({ transform: true )} does not work for optional InputType class

### ISSUE THREAD

**Issue by nicobermudez** [nestjs/nest#4979]
## Current behavior
When I add transform: true to the validation pipeline, when there is an optional inputType, it transforms the input into an empty object instead of keeping it undefined.

## Input Code
```ts
    @Mutation(_ => Boolean)
    async createAccount(
        @Args("createAccount") createAccountInput: CreateAccountInput,
        @Args("otherInput", { nullable: true }) otherInput?: OtherInput,
    ): Promise<boolean> {
       // otherInput becomes {} but should be undefined
        return this.authService.createAccount(createAccountInput, otherInput);
    };
```

## Expected behavior
The optional input type (otherInput) should remain undefined instead of converting to an empty object

## Environment

<pre><code>
Nest version: 7.1.0

**Comment by kamilmysliwiec** [comment]
The `ValidationPipe` is unable to read your GraphQL params metadata. I'd suggest creating your own, dedicated pipe that will fallback to `undefined` in such a scenario.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by jameskuizon1315** [comment]
@nicobermudez this might help: https://github.com/nestjs/nest/issues/1331#issuecomment-485901349
