### ISSUE TITLE
setGlobalPrefix() Middleware not working with Fastify

### ISSUE THREAD

**Issue by xingxinglail** [nestjs/nest#4980]
## Current behavior
Middleware does not handle global prefix when set

## Expected behavior
Middleware handle global prefix when set

## Minimal reproduction of the problem with instructions
```ts
// This does NOT work
const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter()
);

// This works
const app = await NestFactory.create(AppModule);

app.setGlobalPrefix('demo');

// app.module.ts
@Module({
  controllers: [AppController]
})
export class AppModule {
  configure (consumer: MiddlewareConsumer) {
    // This does NOT work
    function logger (req: any, res: any, next: any) {
      console.log('run...');
      next();
    }

    consumer.apply(logger).forRoutes('*');
  }
}
```

## Environment

<pre><code>
Nest version: 7.2.0

For Tooling issues:
- Node version: 10.16.0
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/85983264-7af9da00-b9e7-11ea-9cd2-b6d37a95f0e6.png)

https://docs.nestjs.com/middleware#route-wildcards
