### ISSUE TITLE
Node 13 is not support because of dep of uuid 8

### ISSUE THREAD

**Issue by vipcxj** [nestjs/nest#4991]
## Current behavior

Node 13 is not support because of dep of uuid 8
see this [link](https://github.com/uuidjs/uuid/issues/466#issuecomment-641129599)

## Input Code

```ts
const your = (code) => here;
```

## Expected behavior

Node 13 is supported or tell peoples it is not supported in the document.
## Possible Solution

downgrade uuid to 7 or demonstrate node 13 is not supported because of uuid in document.

## Environment

<pre><code>
Nest version: 7.1.0

 
For Tooling issues:
- Node version: 13  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Btw is there any reason you use v13? This version is not even maintained anymore https://nodejs.org/en/about/releases/. You should rather use either v12 (LTS) or v14 (Current)

**Comment by vipcxj** [comment]
> Btw is there any reason you use v13? This version is not even maintained anymore https://nodejs.org/en/about/releases/. You should rather use either v12 (LTS) or v14 (Current)

I did upgrade to v14, but I also meet this issue when I still in v13. I use v13 just because when I install node, it is the latest stable version. I think not every one alway upgrade their node. If they meet this issue, This can leave them at a loss because the error message doesn't point to the Node version problem at all.

**Comment by kamilmysliwiec** [comment]
> I use v13 just because when I install node, it is the latest stable version.

v13 is neither stable nor the latest

**Comment by vipcxj** [comment]
> > I use v13 just because when I install node, it is the latest stable version.
> 
> v13 is neither stable nor the latest

It was the latest version when no 14 released, and not everybody often update node

**Comment by gperdomor** [comment]
According to uuid readme, Node 13 is not supported, so this issue is not related to NestJS... I think should be closed
>Complete - Support for RFC4122 version 1, 3, 4, and 5 UUIDs
Cross-platform - Support for ...
CommonJS, ECMAScript Modules and CDN builds
Node 8, 10, 12, 14
Chrome, Safari, Firefox, Edge, IE 11 browsers
Webpack and rollup.js module bundlers
React Native

**Comment by vipcxj** [comment]
> According to uuid readme, Node 13 is not supported, so this issue is not related to NestJS... I think should be closed
> 
> > Complete - Support for RFC4122 version 1, 3, 4, and 5 UUIDs
> > Cross-platform - Support for ...
> > CommonJS, ECMAScript Modules and CDN builds
> > Node 8, 10, 12, 14
> > Chrome, Safari, Firefox, Edge, IE 11 browsers
> > Webpack and rollup.js module bundlers
> > React Native

UUID said it not support node 13， but this library not said. And we don't know this library depend on uuid if we not see the "package.json".

**Comment by kamilmysliwiec** [comment]
Anyway, there's certainly no reason to downgrade `uuid` library because it doesn't support an **unstable and unsupported** version of Node (which shouldn't be used either way).
