### ISSUE TITLE
Request an scalable example with Nestjs in the monorepo

### ISSUE THREAD

**Issue by sketchnotes** [nestjs/nest#5008]
## Is your feature request related to a problem? Please describe.
I hope this proposition would help to boost the real implementation of `nestjs` in the monorepo.

## Describe the solution you'd like
I believe that it misses a good, scalable example for `nestjs` in the monorepo (e.g. @NxDevTools).

## Teachability, Documentation, Adoption, Migration Strategy
I've already created a request for such an example on `nrwl/nx-example` [request](https://github.com/nrwl/nx-examples/issues/106https://github.com/nrwl/nx-examples/issues/106). But maybe you could help to build an optimal solution based on your architecture and best practice. 

## What is the motivation / use case for changing the behavior?
I spend quite a bit of time practicing with both `nx` & `nestjs` and I investigated the different solutions and existed examples but none of them would have the real practical value. In slacks (`nx`) and discord (`nestjs`), the communities are rather silent as well. So, it was the true motivation to create this request.

**Comment by kamilmysliwiec** [comment]
We don't plan to add any Nx+NestJS sample to the main repo. Please, check out old issues for more on this topic

**Comment by JimLynchCodes** [comment]
@kamilmysliwiec I don't think OP was asking for an Nx+NestJs sample project. 

Rather, we'd like to see _any_ working nest monorepo project.
