### ISSUE TITLE
"Error [ERR_SERVER_NOT_RUNNING]: Server is not running" with Fastify, WebSocketGateway and enableShutdownHooks

### ISSUE THREAD

**Issue by Boshen** [nestjs/nest#5016]
## Current behavior
With Fastify, WebSocketGateway and app.enableShutdownHooks(), 
node.js throws `Error [ERR_SERVER_NOT_RUNNING]: Server is not running.`
when we shut down the app with ctrl-c.

## Input Code
https://github.com/boshen/nestjs-playground

## Expected behavior
It doesn't throw

**Comment by kamilmysliwiec** [comment]
This should be fixed in 7.3.1. Please, let me know if you still face this issue
