### ISSUE TITLE
DI on validators 

### ISSUE THREAD

**Issue by saulotoledo** [nestjs/nest#5017]
## Feature Request

DI on validators.

## Is your feature request related to a problem? Please describe.

Adapting an example from the class-validator package documentation, it is not possible to inject dependencies into validators:

```typescript
import {registerDecorator, ValidationOptions, ValidatorConstraint, ValidatorConstraintInterface, ValidationArguments} from "class-validator";

@ValidatorConstraint({ async: true })
export class IsUserAlreadyExistConstraint implements ValidatorConstraintInterface {

    validate(userName: any, args: ValidationArguments) {
        // It is not possible to inject the repository below:
        return this.userRepository.findOneByName(userName).then(user => {
            if (user) return false;
            return true;
        });
    }

}
```

## Describe the solution you'd like

I would like to inject the user repository in the example above using constructor injection. I was wondering if that is possible using https://github.com/typestack/class-validator#using-service-container

## What is the motivation / use case for changing the behavior?

A few use cases: async db validation, validation depending on external factors.

**Comment by kamilmysliwiec** [comment]
This has been discussed tons of times. Please, search for old issues.
