### ISSUE TITLE
Inversion of control

### ISSUE THREAD

**Issue by citosid** [nestjs/nest#502]
```
[ ] Regression 
[ ] Bug report
[x] Feature request
[x] Documentation issue or request
[ ] Support request 
```

## Current behavior
Right now, I can do injection of dependencies in nest (according to what is written here: https://docs.nestjs.com/fundamentals/dependency-injection), however in my application I'm developing multiple modules, like this:

<img width="639" alt="screenshot 2018-03-12 17 02 07" src="https://user-images.githubusercontent.com/201430/37309369-1ec06486-2617-11e8-95c0-54b6f9d27308.png">

I want to define interfaces in the `global` project, and then `use` them in the domain, but the injection should happen in the `login` module, so the actual implementation is not in the `domain` but in the module.

## What is the motivation / use case for changing the behavior?
We are developing using `DDD` and in order to enforce boundaries, we want to keep the different modules and domains in different packages, not relying in the developer to trust he will not cross boundaries.

## Environment

```
Nest version: 4.5.9
 
For Tooling issues:
- Node version: 9.8.0
- Platform:  Mac
```

**Comment by kamilmysliwiec** [comment]
Could you provide a code example? (with expected/current behavior)

**Comment by citosid** [comment]
Thanks @fjcero 

@kamilmysliwiec I've found the answer, but I think it could be a little more clear by adding the explanation to the wiki. 

Will try to add a PR to the project in https://github.com/nestjs/docs.nestjs.com
