### ISSUE TITLE
Two calls are executed when I do the request to the route

### ISSUE THREAD

**Issue by prebolledo** [nestjs/nest#5023]
## Current behavior

When I run my API and I send request to the route "/", two calls are executed

The answer I currently have is:

> Hello World!
> Hello World!

## Input Code

```ts
  @Get()
  getHello(): string {
    const h = this.appService.getHello();
    console.log(h)
    return h;
  }
```

## Expected behavior

Hello World!
## Environment

<pre><code>
Nest version: 7.4.1

 
For Tooling issues:
- Node version: v12.18.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction Repository

**Comment by prebolledo** [comment]
Hi @jmcdo29 
Basically is an initial project created by "nest new project".

I have upload project to https://github.com/prebolledo/test-nest

Thanks

**Comment by jmcdo29** [comment]
I cloned, installed deps, started, and called `curl http://localhost:3000`. Single response to the client and one log in the server's terminal. Can't reproduce it @prebolledo

**Comment by prebolledo** [comment]
@jmcdo29 I have done the test with postman and is ok, with curl is ok, but when i send request from chrome (urls bar) then throw twice calls. :D

**Comment by jmcdo29** [comment]
@prebolledo nope, still just one call on my side. I tried Brave (Chromium based) and Firefox. Neither of them sent multiple requests.

For further support, please use our [Discord](https://discord.gg/nestjs) as we are using GitHub to track Bug Reports and Feature Requests.

**Comment by prebolledo** [comment]
@jmcdo29 thanks bro, it is so strange.
But i try sent this to Discord.

Peace.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
