### ISSUE TITLE
Controllers should be first class citizens along with other classes using providers

### ISSUE THREAD

**Issue by kvernon** [nestjs/nest#5025]
## Is your feature request related to a problem? Please describe.
Recently, I've been tasked with building multiple libraries where we can compose a nestjs application. It will allow for one giant app or smaller or even smaller to microservices. I've broken up the projects where the core modules are `DynamicModule`s, and it's great. Most of the injections patterns are pushed up at that level; keeping the classes clean and easy for changes.

The problem around the customization is that these prebuilt controllers (ones I created for these libraries) allow little flexibility in the current state. With other classes, I can set up a provider for them, and if someone needs to change what's injected, they can do so by creating and wiring up their own custom provider. However, the controller does not allow this flexibility per the nestjs system. 

Currently, the controller has lots of swagger decorators and context, which is expected with a controller, but if I can inject at a higher level, it will allow them to retain the controller with its metadata. Now if someone needs to change their strategy (token vs class) then they're out of luck. They'll have to `extend` the class and force another `@Inject()` at the constructor, which isn't clean. 

I can add that, once the controller class is not referenced as a controller, then it can use a custom provider injection pattern, it's only when I attempt to use it as a controller where it isn't allowed.

Even if I go to examples for other libraries or frameworks, controllers, are also included for custom provider injection. It would be great if controllers could be first-class citizens and utilize custom providers too.

## Describe the solution you'd like
```
export class TheController {
   // Note: no @Inject("THE_SERVICE"), this is the ideal
   constructor(service: IService) {
        this.service = service;
   }
}

export const ServiceProvider = {
    provide: "THE_SERVICE",
    useClass: MyService
}

export const ControllerProvider = {
   provide: TheController ,
   useFactory: (service : IService) => new TheController (service)
}

@Module({
  controllers: [TheController ],
  providers: [ServiceProvider ],
  exports: [ServiceProvider, "THE_SERVICE"]
})
export class TheModule {

}
```

## Teachability, Documentation, Adoption, Migration Strategy
I think I just did with the description above. Equally, making the controller behave like the rest of the classes would actually make it align with the documentation more.

## What is the motivation / use case for changing the behavior?
The behavior again is to provide cleaner code. It's also to provide custom dependencies directly for the controller.

**Comment by kamilmysliwiec** [comment]
This has been discussed several times in the past. We don't plan to allow custom providers syntax to be used with controllers. Thanks for the proposal though!
