### ISSUE TITLE
Nest app is not starting with npm run start (:dev)

### ISSUE THREAD

**Issue by camboYY** [nestjs/nest#5028]
## Bug Report
[12:35:18] Starting compilation in watch mode...

[12:35:23] Found 0 errors. Watching for file changes.
## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: 7.4.1

 
For Tooling issues:
- Node version: XX  
v10.2.1
- Platform:  
window 10

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please, use our [Discord](https://discord.gg/nestjs) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
