### ISSUE TITLE
Allow ModuleRef to create multiple classes

### ISSUE THREAD

**Issue by vinverdy** [nestjs/nest#5035]
## Is your feature request related to a problem? Please describe.
Is it possible to dynamically instantiate multiple classes in ModuleRef? So, it could inject new providers that has not been registered before.

```ts
@Injectable()
class A {}

@Injectable()
class B {
  public constructor(a: A) {}
}

moduleRef.create(B); // ERROR: Nest can't resolve dependencies of the B (?)
```

## Describe the solution you'd like
I hope moduleRef could instantiate multiple classes like [angular's injector](https://angular.io/api/core/Injector#create)

## Teachability, Documentation, Adoption, Migration Strategy
I think if the API would be same with angular, it will be great.

**Comment by kamilmysliwiec** [comment]
This isn't how the `create()` method is supposed to work and there's no plan to change it.
