### ISSUE TITLE
DefaultValuePipe is not setting specified default value

### ISSUE THREAD

**Issue by tooleks** [nestjs/nest#5036]
## Current behavior

`DefaultValuePipe` with `ParseIntPipe` is not setting specified default value for `number` typehint. After some debugging I found that `DefaultValuePipe#transform` receives `NaN` value, it uses `isNil` util to check whether provided value is defined. `isNil` returns `false` for `NaN` value which prevents from setting a default value: https://github.com/nestjs/nest/blob/master/packages/common/pipes/default-value.pipe.ts#L17.

## Input Code

[Pipes / Providing defaults](https://docs.nestjs.com/pipes#providing-defaults):

```ts
@Get()
async findAll(
  @Query('activeOnly', new DefaultValuePipe(false), ParseBoolPipe) activeOnly: boolean,
  @Query('page', new DefaultValuePipe(0), ParseIntPipe) page: number, // Throws BadRequestException
) {
  return this.catsService.findAll({ activeOnly, page });
}
```

Response example:

```json
{
    "statusCode": 400,
    "message": "Validation failed (numeric string is expected)",
    "error": "Bad Request"
}
```

## Expected behavior

`DefaultValuePipe` should set specified default value.

## Possible Solution

Not sure yet.

## Environment

<pre><code>
Nest version: 7.3.1
 
For Tooling issues:
- Node version: 12.14.1
- Platform:  Linux

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 7.3.2. Thanks for reporting!

**Comment by tooleks** [comment]
@kamilmysliwiec Great! Thank you.

**Comment by acodercat** [comment]
I have the same problem in the version 8.0
