### ISSUE TITLE
Alternate cache invalidation criterion

### ISSUE THREAD

**Issue by adriano-di-giovanni** [nestjs/nest#5044]
## Is your feature request related to a problem? Please describe.

I'm facing a scenario where the cache keys should be invalidated daily, weekly, monthly, and yearly. 

Thus, I should set an expiry date instead of a TTL. AFAIK, there is no way to handle this scenario but

* customizing the `CacheInterceptor` to track by a time-scoped key and decorate each route with the appropriate `@CacheTTL` decorator
* request-scoping the controller and decorate the routes with a @CacheTTL whose value is computed on the fly (would it work?)

## Describe the solution you'd like
If there is no current idiomatic solution, I can think of 

* a different interface for the `CacheInterceptor`. This interface would allow subclasses to also specify a custom TTL
* `@CacheKey` and `@CacheTTL` decorators accepting thunks

Any other ideas?

I'd be happy to contribute to the feature implementation if we agreed on a solution.

**Comment by kamilmysliwiec** [comment]
> I'm facing a scenario where the cache keys should be invalidated daily, weekly, monthly, and yearly.

You can inject the cache manager reference and implement any additional, customized logic you want (depending on your app requirements) using the `@Inject(CACHE_MANAGER)`. We track the missing docs on that here https://github.com/nestjs/docs.nestjs.com/issues/156
