### ISSUE TITLE
TestingModule not compatible with alternative HTTP Adapter?

### ISSUE THREAD

**Issue by kkarimi** [nestjs/nest#5052]
## Current behavior

I am working on an app that uses the Nest [Azure Functions HTTP module](https://github.com/nestjs/azure-func-http).

When defining an app for integration testing, I cannot set `AzureHttpRouter`  as an adapter because in testing module, I get:

```
{
	"resource": "/Users/nima/dev/src/app/tests/app.integration.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'AzureHttpRouter' is not assignable to parameter of type 'HttpServer<any, any>'.\n  The types returned by 'useStaticAssets(...)' are incompatible between these types.\n    Type 'void' is not assignable to type 'HttpServer<any, any>'.",
	"source": "ts",
	"startLineNumber": 52,
	"startColumn": 47,
	"endLineNumber": 52,
	"endColumn": 66
}
```

## Input Code

```ts
const moduleFixture: TestingModule = await Test.createTestingModule({
  imports: [AppModule],
}).compile()

app = moduleFixture.createNestApplication(new AzureHttpRouter)
```

This is while in the application, there is no problem using it as a HTTP adapter:

```ts
import { AzureHttpRouter } from '@nestjs/azure-func-http'

const app = await NestFactory.create(AppModule, new AzureHttpRouter())
```

## Expected behavior

I expect this should be allowed if the type for the `httpAdapter` is changed to `AbstractHttpAdapter` which seems to be what the Azure adapter uses
## Possible Solution

Maybe in `testing-module.ts` the adapter [type](https://github.com/nestjs/nest/blob/master/packages/testing/testing-module.ts#L28) type should be changed to allow [AbstractHttpAdapter](https://github.com/nestjs/nest/blob/1aa238d39c60a2c065d7441177d36984d7af846d/packages/core/adapters/http-adapter.ts#L9) 

```ts
import { AbstractHttpAdapter } from '@nestjs/core';

  public createNestApplication<T extends INestApplication = INestApplication>(
    httpAdapter?: HttpServer | AbstractHttpAdapter,
    options?: NestApplicationOptions,
  ): T {

```
## Environment

<pre><code>
Nest version: 7.3.0

 
For Tooling issues:
- Node version: v10.21.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 7.3.2. Thanks for reporting!
