### ISSUE TITLE
[Microservices] Dynamic subscriptions during runtime.

### ISSUE THREAD

**Issue by koper89** [nestjs/nest#5062]
## Is your feature request related to a problem? Please describe.
No issue I know of.

## Describe the solution you'd like
I've got use case where I need to dynamically subscribe to channels (NATS, but I suspect it could be applied to more) during runtime. Let's say we've got a topic in format:
'id.doSomething'
on multiple instances I want to be able to subscribe to different set of id's (but they'll have same handler).

```
@DynamicMessagePattern('id.doSomething')
doSomething(@Payload() data: number[], @Ctx() context: NatsContext) {
  console.log(`Subject: ${context.getSubject()}`); // e.g. "time.us.east"
  return new Date().toLocaleTimeString(...);
}
```
So on each instance I want to be able to subscribe to those handlers during runtime to specified ID's instead of static subscription on bootstrap. 

## Teachability, Documentation, Adoption, Migration Strategy
As Client is currently only injectable easiest way would be to add new method towards it that would allow us to subscribe. Set of new decorators for Message and Event Patter that would notify nest that this is dynamic subscription, which would indicate to not subscribe on bootstrap. 
As possible command: this.client.subscribe(subject, channel);
where subject would be exact subject i.e. 1.doSomething, and channel would be pointing to dynamic handler 'id.doSomething'.

## What is the motivation / use case for changing the behavior?
In my case I've got multiple instances of microservices that are websocket gateways. I want to be able to direct messages towarts connected websocket clients using microservices. To best use resources as I know some uniqueId's I could subscribe on each instance on different set of them which would significantly improve performance vs publishing message to all instances and filtering out on "server" side.

**Comment by koper89** [comment]
I started a bit of digging to implement it myself, but am struggling with finding good way of exposing internal Server class.
So far I added a couple of decorators (so far only applied to NATS), that register handlers correctly but doesn't subscribe to them.
[https://github.com/nestjs/nest/compare/master...koper89:feature/microserviceDynamicSubscription](url)
Now the hard part, how to expose some module that will have access to internal Server class instance (or some other that got access to Server class). To guard it module will only expose i.e. bindDynamicEvent function, i.e. ServerModule that would have dependency injected from within one of above mentioned.

**Comment by koper89** [comment]
Couple more thoughts, as we can have multiple microservices challenge would be on selection of module to inject, it could be another option in MicroserviceOptions that would have a field to specify name for "ServerModule" for association. This way on bootstrapping of microservice if such a name exists such a module could be created otherwise not. Another nice feature of such an injection of module per microservice could be reusing server connection to client capabilties in projects that require both capabilities, as currently i.e. on nats if I want to send and receive microservices I need to have 2 active connections ClientModule and Listener.

**Comment by kamilmysliwiec** [comment]
> I've got use case where I need to dynamically subscribe to channels (NATS, but I suspect it could be applied to more) during runtime. Let's say we've got a topic in format: 'id.doSomething' on multiple instances I want to be able to subscribe to different set of id's (but they'll have same handler).

For this, you can simply use NATS SDK directly. In fact, to build microservices on top of the Nest framework, using the `@nestjs/microservices` isn't even required. This package ships with several features available out-of-the-box (for example, decorators so you can declaratively define subscriptions and runtime for loading/registering them automatically). However, if you need more control & flexibility (e.g., dynamic subscriptions), it would be better to just use any SDK directly (regardless of whether it's NATS, Kafka, or RabbitMQ).

**Comment by TrejGun** [comment]
@koper89 Hi man!
Have you been able to implement dynamic subscriptions? I want to do the same for my project. Can you please share your solution?
