### ISSUE TITLE
NestJs compiling Angular application wich is in a different folder

### ISSUE THREAD

**Issue by Leccho** [nestjs/nest#5069]
## Current behavior
When using npm start, it also compile my angular application in my dist folder. This cause this error to apear:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Users\lecle\Desktop\Workspace\template\rest-api\dist\main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Structure of application:
A www folder wich contains a rest-api folder for NestJs app and a webui folder for Angular

## Expected behavior
Should only compile my nestjs application

## Environment

<pre><code>
Nest version: 7.1.5
 
For Tooling issues:
- Node version: 13.9.0
- Platform:  Windows

Others:
- Angular version: 9.1.12
</code></pre>

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for questions. We are using GitHub to track feature requests and bug reports.

**Comment by Leccho** [comment]
This is a bug repport, nestjs should not be compiling my angular app.

**Comment by jmcdo29** [comment]
This isn't a bug with Nest. This is a bug with how `tsc` and the `tsconfig` work. If you're working in a monorepo it may be useful to use a monorepo tool like [Nx](https://nx.dev).

**Comment by Leccho** [comment]
My bad thank you for the help. I didn't know.
