### ISSUE TITLE
Nest can't resolve dependencies of ... Service. 

### ISSUE THREAD

**Issue by Edwardchorius** [nestjs/nest#5072]
## Current behavior
I have 2 modules. After running the integration tests, the error that occurs states that `" Nest can't resolve dependency of the ....Service. Please make sure that the argument dependency at index [1]  is available in the ...Module context"`. Now, I have many services that are provided correctly in the module. Also, 6 repositories. This argument at index [1] is actually a repository. In the other module I have it is provided the same way but I wonder why this error occurs only here. It is not something trivial, for example to forget to import something somewhere or to provide it.

## Environment
I am using Jest for the integration tests.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by kamilmysliwiec** [comment]
For those that are repeatedly struggling with the "Cannot resolve dependency" error, check out the [NestJS Devtools](https://www.devtools.nestjs.com/) (read more [here](https://docs.nestjs.com/devtools/overview#investigating-the-cannot-resolve-dependency-error)).

Example:

![image](https://user-images.githubusercontent.com/23244943/225931543-a92ba2de-fce7-4ae6-8343-3f1d745a2022.png)
