### ISSUE TITLE
Unable to use Nest default Logger as described in the documentation

### ISSUE THREAD

**Issue by alexqbm** [nestjs/nest#5076]
## Bug Report
The documentation says:

- *To enable specific logging levels, set the logger property to an array of strings specifying the log levels to display.*
- *Values in the array can be any combination of 'log', 'error', 'warn', 'debug', and 'verbose'.*

However, the *logger* property of the *NestFactory* configuration object expects either a boolean or a LoggerService as a value.

## Current behavior

When using the default custom logger this issue is raised:
![image](https://user-images.githubusercontent.com/51962150/87283107-3f860200-c4f5-11ea-9645-2fff0327cb96.png)

## Input Code

```ts
const app = await NestFactory.create(ApplicationModule, {
  logger: ['error', 'warn'],
});
```

## Expected behavior

I should let me use the default logger as shown in the documentation without raising an error.
![image](https://user-images.githubusercontent.com/51962150/87283447-97bd0400-c4f5-11ea-9684-d8368dc666e3.png)

## Possible Solution

Either update the documentation in order to manifest that passing an array of strings representing logger levels is not accepted or update the value types that the logger parameter of the NestFactory object accepts.
## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
What's your version of `@nestjs/common` and `@nestjs/core`? On 7.3.2 I have the options as described. Can you provide a reproduction?

**Comment by jmcdo29** [comment]
@isdiop can you provide a reproduction?

**Comment by isdiop** [comment]
@jmcdo29 this is a fresh nest installation with some node modules.

I don't have the issue in this project.
https://github.com/isdiop/nest-issue-5076


i will add all other packages to see if i will able to reproduce the same behavior.

**Comment by kamilmysliwiec** [comment]
This is very likely related to versions of your packages (`@nestjs/common` and `@nestjs/core`). 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
