### ISSUE TITLE
Can't use nestjs ConfigService in main.ts 

### ISSUE THREAD

**Issue by sotnasaj** [nestjs/nest#5079]
## Bug Report
**Documentation says:**

While our config is a stored in a service, it can still be used in the main.ts file. This way, you can use it to store variables such as the application port or the CORS host.

To access it, you must use the app.get() method, followed by the service reference: ...

```const configService = app.get(ConfigService);```

You can then use it as usual, by calling the get method with the configuration key:

```const port = configService.get('PORT');```

## Current behavior

Using the config service in other modules seems to work, i can configure TypeOrm with ConfigService.
The problem is in the main.ts, for example trying to access PORT via ConfigService retrieves a random port, or undefined for HOSTNAME.

Using process.env.PORT  and process.env.HOSTNAME works, so the ConfigModule loads the envFile correctly.
But using ConfigService fails, i expect a 7000 PORT and a 127.0.0.1 HOSTNAME.

![Captura de pantalla de 2020-07-13 10-01-05](https://user-images.githubusercontent.com/38994837/87326971-b10f8180-c4f0-11ea-86b7-69bb7a30fa43.png)

I don't know if i'm doing something wrong , but i tried to follow the instructions.
## Input Code

```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const config =  app.get(ConfigService);
  const document = SwaggerModule.createDocument(app, swaggerDocument);
  SwaggerModule.setup('api/swagger/docs', app, document);
  app.enableCors();
  app.use(helmet());
  await app.listen(config.get<number>('app.port'));
}
bootstrap();

```

```ts
...
      ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: '.env',
      load: [AppConfig, DatabaseConfig],
    }),
...
```
Minimal repo: https://github.com/sotnasaj/SimpleRepo
npm start
With env.example , just trying to run and log  the environment variables in main.ts 

## Expected behavior
Load env variables via ConfigService in main.ts as documentations explains.

## Environment

<pre><code>
Nest version: 7.2.0

 
For Tooling issues:
- Node version: 12.16.3 
- Platform: Linux  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by sotnasaj** [comment]
> Please provide a minimum reproduction repository.

I update the Bug Report, also here in the comment:  https://github.com/sotnasaj/SimpleRepo
Is almost empty, just trying to log out and start the app with the right environment variables in .env.example file

**Comment by jmcdo29** [comment]
Okay. A couple of things.
1) You were using `app.hostname` when you've only registered `host` and `port` as values under `app`, hence why `app.hostname` was undefined. 
2) For `port` you have `parseInt(process.env.PORT, 10) | 7000`. Pay close attention to the fact that that is `|` and **not** `||`. You're doing a [bitwaise OR](https://en.wikipedia.org/wiki/Bitwise_operation#OR) operation meaning the port comes out as 7128, not 5000.

Once you fix those two things everything works as expected.

In the future, please use our [Disrcord](https://discord.gg/nestjs) channel (Support) for help, as we are using GitHub to track bug reports, feature requests and regressions.

**Comment by sotnasaj** [comment]
What a shame man...
Thanks a lot , i also found one more bitwise OR error in other config...
Sorry for the time, and thanks a lot again!
