### ISSUE TITLE
Module aliassing

### ISSUE THREAD

**Issue by stefaanMLB** [nestjs/nest#5082]
## Feature Request
I would be nice if module aliassing would be better supported in nestjs both during development (debug, tests and non-debug running) and for deployment
[This blog](https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353) provides a nice introduction

When I manage to get aliasing working during debug, then it doesn't work for regular execution and for testing.  It's rather complicated to get it working everywhere.  Would be great if it were supported out-of-the-box for all cases

**Comment by jmcdo29** [comment]
This already works using the nest CLI.

Please us our [Discord](https://discord.gg/nestjs) channel (Support) for help. We are using GitHub to track Bug Reports and Feature Requests.

**Comment by stefaanMLB** [comment]
Well, it's not working for me.
Can you point me to the documentation where it is explained how to use this feature ?
