### ISSUE TITLE
NestFactory.createApplicationContext(moduleRef) throws an Error: "TypeError: metatype is not a constructor"

### ISSUE THREAD

**Issue by omer-morad-ni** [nestjs/nest#5092]
## Current behavior
I'm using @nest/testing package in order to create "TestingModule" instance (with .compile() method).
After I'm creating the module successfully, I want to "get" service or a provider.
I don't know why `moduleRef.get(SomeService)` doesn't work anymore, so I tried to use
`const app = NestFactory.createApplicationContext(moduleRef)` and then use `app.get(SomeService)` but it throws exception `NestFactory.createApplicationContext(moduleRef)`

## Input Code

```ts
  describe('register', () => {
    let secretsManagerService: SecretsManagerService;

    beforeAll(async () => {
      const moduleRef = await Test.createTestingModule({
        imports: [SecretsManagerModule.register({ ... })],
      })
        .overrideProvider(SECRETS_MANAGER)
        .useValue({})
        .overrideProvider(SECRETS_MANAGER_CREDENTIALS)
        .useValue({})
        .compile();

      const app = await NestFactory.createApplicationContext(moduleRef);
      secretsManagerService = await app.get<SecretsManagerService>(SecretsManagerService);
    });

    it('Should provide/export the secrets manager service (SecretsManagerService)', async () => {
      expect(secretsManagerService).toBeDefined();
      expect(secretsManagerService).toBeInstanceOf(SecretsManagerService);
    });
  });
```

## Expected behavior
It should get `SecretsManagerService`

## Environment

<pre><code>
Nest version: 7.3.2 (All: core, common, testing)
 
For Tooling issues:
- Node version: v10.17.0
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
You should never use the `NestFactory.createApplicationContext()` in combination with the `Test.createTestingModule()`. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
