### ISSUE TITLE
name property of `ClientProviderOptions` should accept symbol values

### ISSUE THREAD

**Issue by wayou** [nestjs/nest#5093]
## Current behavior
According to the [doc](https://docs.nestjs.com/microservices/basics#client):

> The name property serves as an injection token that can be used to inject an instance of a ClientProxy where needed. The value of the name property, as an injection token, can be an arbitrary string or JavaScript symbol, as described here.

we can use Symbol as injection token for the microservice.

## Input Code

```ts
@Module({
  imports: [
    ClientsModule.register([
      {
        // 🚨 Type 'symbol' is not assignable to type 'string'.ts(2322)
        name: Symbol('my_microservice'),
      },
    ]),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

## Expected behavior
the `name` should accept Symbol values.

## Possible Solution

_[packages/microservices/module/interfaces/clients-module.interface.ts](https://github.com/nestjs/nest/blob/master/packages/microservices/module/interfaces/clients-module.interface.ts)_
```diff
export type ClientProviderOptions = ClientOptions & {
-  name: string;
+  name: string | symbol;
};
```

## Environment

<pre><code>
Nest version: 7.4.1

 
For Tooling issues:
- Node version: v14.0.0  
- Platform: Mac 

</code></pre>

**Comment by jmcdo29** [comment]
Would you like to create a PR for this?
