### ISSUE TITLE
using VSCode autoAttach "on" and "yarn start:dev" will launch into debugger

### ISSUE THREAD

**Issue by UTGuy** [nestjs/nest#5094]
## Regression
 Using this setting... would only launch the debugger when using `yarn start:debug`
```
{
    "debug.node.autoAttach": "on"
}
```

Prior to this VSCode 1.47.0 (or 1.47.1) running NestJs under `yarn start:dev` would correctly not launch into the debugger.
After 1.47.0 the debugger began to autoAttach when running dev.

It seems the latest VSCode has caused this issue. see: https://github.com/microsoft/vscode/issues/102035

Setting the preview off returns everything back to normal...
```
{
    "debug.node.autoAttach": "on",
    "debug.javascript.usePreview": false
}
```
## Expected behavior/code
Nest should not launch into the debugger when running `yarn start:dev`

## Environment
<pre><code>
Nest version: 6.10.14

For Tooling issues:
- Node version: v12.18.0
- Platform:  Mac / Linux (vie Remote container)

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Is this an issue with Nest or with VSCode? I'm not sure what we can do about this to help.

**Comment by UTGuy** [comment]
That's an excellent question. I don't know. I believe the new debugger in VSCode cause it, but I also don't know if there's something you guys need to adjust on the Nest side either.

**Comment by jmcdo29** [comment]
I'm pretty sure this is a VSCode issue, especially as we aren't getting reports from other IDE users. The `start:dev` command is `nest start --watch` which will essentially run `tsc && node dist/main` and run that again when anything changes. Nothing about the debugger should be touched in general, but something in the VSCode update changed that.

**Comment by connor4312** [comment]
@UTGuy saw your reference on the other issue -- for auto attach, see here: https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467

**Comment by UTGuy** [comment]
@connor4312 That didn't help, we are running Node v12.18.0

**Comment by connor4312** [comment]
Yes, the issue you linked originally is not the problem you're hitting -- see the link in my last comment for details around auto attach 🙂

**Comment by UTGuy** [comment]
@connor4312 Are there other autoAttach issues being reported with 1.47.0+ ? This started with that version... I can stop it by setting
```
"debug.javascript.usePreview": false
```

**Comment by connor4312** [comment]
Yes, a couple. The one you're discussing here is something I mentioned in the message on https://github.com/microsoft/vscode-js-debug/commit/6932b620d6d5ea697a1a1cd00f5bdb07b9167ee6 -- we now have the superpower to attach to all process in auto attach, without requiring --inspect flags. However we failed to consider the impact this would have on users used to the old auto attach mechanic who would  'suddenly' get a bunch of things they don't want being attached to them.

The other main issue is one where if OSX or Linux machines crash they can orphan an auto-attach such causes the user to get 'stuck' in auto attach mode. But that's not what you're running into here.

**Comment by UTGuy** [comment]
@connor4312 That first one sounds exactly like what's going on. Is there a path to fixing this?

**Comment by connor4312** [comment]
You have four options which I outlined in the linked issue 🙂 

>1. Turning Auto Attach (setting ID `debug.node.autoAttach`) to "off" or "disabled.
>1. Use the latest [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension) where we added an options (true by default) to only attach to processes started with `--inspect`
>1. Set `debug.javascript.usePreview` to turn off the new debugger entirely (if needed)
>1. Use [VS Code Insiders](https://code.visualstudio.com/insiders/), or wait until the Thursday recovery release on Thursday the 16th (**tomorrow**).

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
