### ISSUE TITLE
Forbiden resource

### ISSUE THREAD

**Issue by LuisSarmientoM** [nestjs/nest#5095]
I'm trying to add security with roles by following the documentation and when I try to do this
`const roles: string[] = this._reflector.get<string[]>(
    'roles',
    context.getHandler(),
);`
gives me this message:
![image](https://user-images.githubusercontent.com/42702720/87581420-86fbc200-c69e-11ea-8a59-b666edad0f74.png)

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for help and support. We are using GitHub to track Feature Requests, Bug Reports and regressions.

**Comment by LuisSarmientoM** [comment]
> Please use our [Discord](https://discord.gg/nestjs) channel (Support) for help and support. We are using GitHub to track Feature Requests, Bug Reports and regressions.

thanks!
