### ISSUE TITLE
[OpenAPI/Swagger] Issue with a generic Data Access Layer (DAL) and Swagger documentation.

### ISSUE THREAD

**Issue by leovct** [nestjs/nest#5104]
## Bug Report
Issue with a generic Data Access Layer (DAL) and Swagger documentation.

## Current behavior
I have developed a generic DAL using NestJs called __dal__ and applied it to an entity in one of my databases, namely __student__. All my routes work fine, I tested with cURL but there is a serious problem with the documentation generated by Swagger.

This concerns the documentation of the Student entity as well as the PUT route _/students/{id}_ (because it takes a Student entity as a requested parameter in the body of the query).  As you can see on the screen below, the documentation for the Student entity is not generated. Same thing for the PUT _/student/{id}_ route: the Student entity does not appear in the route requested body...

![documentation-not-working](https://user-images.githubusercontent.com/28714795/87679120-175c0480-c77c-11ea-902e-9bfa47140268.png)

## Input Code

My __generic DAL__ with only the PUT _update/{id}_ route that causes problems.
```ts
/* dal.module.ts */
import { Module } from '@nestjs/common'
import { DalController } from './dal.controller'
import { DalService } from './dal.service'

@Module({
  controllers: [DalController],
  providers: [DalService]
})
export class DalModule {}


/* dal.controller.ts */
import { Body, Param, Put } from '@nestjs/common'
import { ApiResponse } from '@nestjs/swagger'
import { UpdateResult } from 'typeorm'
import { DalService } from './dal.service'

export class DalController<T> {
  constructor(private dalService: DalService<T>) {}

  @Put(':id')
  @ApiResponse({ status: 200, description: 'The entity has been successfully updated thanks to its id.' })
  update(@Param('id') id: string, @Body() entity: T): Promise<UpdateResult> {
    return this.dalService.update(id, entity)
  }
}


/* dal.service.ts */
import { Repository, UpdateResult } from 'typeorm'

export class DalService<T> {
  constructor(private readonly repository: Repository<T>) {}

  async update(id: string, entity: T): Promise<UpdateResult> {
    return await this.repository.update(id, entity)
  }
}
```

The __use of the generic LAD for the Student entity__
```ts
/* student.module.ts */
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { StudentController } from './student.controller'
import { StudentService } from './student.service'
import { Student } from './student.entity'
import { REPOSITORY_DB } from 'src/app.service'

@Module({
  imports: [TypeOrmModule.forFeature([Student], REPOSITORY_DB)],
  controllers: [StudentController],
  providers: [StudentService]
})
export class StudentModule {}


/* student.controller.ts */
import { DalController } from '../../dal/dal.controller'
import { Controller } from '@nestjs/common'
import { ApiTags } from '@nestjs/swagger'
import { StudentService } from './student.service'
import { Student } from './student.entity'

@ApiTags('/students')
@Controller('students')
export class StudentController extends DalController<Student> {
  constructor(studentService: StudentService) {
    super(studentService)
  }
}


/* student.service.ts */
import { Injectable } from '@nestjs/common'
import { InjectRepository } from '@nestjs/typeorm'
import { Repository } from 'typeorm'
import { DalService } from '../../dal/dal.service'
import { Student } from './student.entity'
import { REPOSITORY_DB } from 'src/app.service'

@Injectable()
export class StudentService extends DalService<Student> {
  constructor(
    @InjectRepository(Student, REPOSITORY_DB)
    studentRepository: Repository<Student>
  ) {
    super(studentRepository)
  }
}
```

## Expected behavior
Here are two screens that illustrates the expected behaviour.

First of all, Swagger generates the documentation for the Student entity. Then, the documentation of the PUT _students/{id}_ route displays the Student in the requested body of the query. 

![documentation-works](https://user-images.githubusercontent.com/28714795/87679122-17f49b00-c77c-11ea-9589-e6cdf8a46c30.png)

![update-route-works](https://user-images.githubusercontent.com/28714795/87679123-188d3180-c77c-11ea-95c7-7a6a958bea70.png)

## Possible Solution
The only solution I found to solve the problem is to redefine the PUT route _students/{id}_ in _student.controller.ts_. This provides both the documentation for the entity and the correct documentation for the PUT _student/{id}_ route.

However, it's only an alternative and bad solution, moreover it's not viable. This even goes against the philosophy of a generic DAL because I find myself having to redefine this PUT update/{id} route for each of the entities in my database.

```ts
/* updated student.controller.ts */
import { DalController } from '../../dal/dal.controller'
import { Controller, Put, Param, Body } from '@nestjs/common'
import { ApiTags } from '@nestjs/swagger'
import { StudentService } from './student.service'
import { Student } from './student.entity'
import { UpdateResult } from 'typeorm'

const DEFAULT_FIELDS: (keyof Student)[] = ['id', 'firstname', 'lastname']

@ApiTags('/students')
@Controller('students')
export class StudentController extends DalController<Student> {
  constructor(studentService: StudentService) {
    super(studentService, DEFAULT_FIELDS)
  }

  /* override the generic update route */
  @Put(':id')
  update(@Param('id') id: string, @Body() student: Student): Promise<UpdateResult> {
    return super.update(id, student)
  }
}
```

## Environment

<pre><code>Nest version: 7.4.1
OpenAPI/Swagger version: 4.5.12
TypeORM version: 7.1.0
 
For Tooling issues:
- Node version: 12.18.1
- Platform: Linux
</code></pre>

**Comment by jmcdo29** [comment]
Generics aren't generally supported by the swagger module or swagger plugin due to limitations of typescript metadata reflection. More info here: https://github.com/nestjs/swagger/issues/86
