### ISSUE TITLE
Add missing precondition failed (412) exception class

### ISSUE THREAD

**Issue by dsebastien** [nestjs/nest#5113]
## Is your feature request related to a problem? Please describe.
Related to error handling in a RESTful API.
In our API, we make use of conditional requests for updates (i.e., clients pass the If-Match header with the ETag) and the server must respond with an HTTP 412 (precondition failed) if the data is outdated (cfr https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests).

Under @nestjs/common/exceptions, a number of HTTP exception class are available, but not the one I'm after.

## Describe the solution you'd like
Add an exception class for precondition failed (412).
Related to #2727, but IMO it makes sense to include this exception class

## What is the motivation / use case for changing the behavior?
Completeness of Nest's API and avoid reinventing the wheel.

**Comment by dsebastien** [comment]
(and if we do get 418, then I assume 412 makes sense too?? :D)

**Comment by jmcdo29** [comment]
Sounds like a fair case. Wanna make a PR to add the exception?

**Comment by dsebastien** [comment]
Yep, I've opened it

**Comment by kamilmysliwiec** [comment]
Thanks @dsebastien! Let's track this here https://github.com/nestjs/nest/pull/5116
