### ISSUE TITLE
Switch to use Bree instead of Bull

### ISSUE THREAD

**Issue by niftylettuce** [nestjs/nest#5114]
Hello, this is a mirror of https://github.com/nestjs/bull/issues/496 so others are aware.  There are core issues with Bull that myself and others have discovered, and are still unresolved (for months now).  You should definitely switch to use https://github.com/breejs/bree in my opinion!

**Comment by BrunnerLivio** [comment]
I’ll close this issue, since we don’t want duplications amongst our repositories. Continue the discussion in the nestjs/bull repo. 

Please  - avoid this behavior in the future - if everyone would mirror their issues to gain visibility, an issuer tracker would just become an untrackable mess.

**Comment by niftylettuce** [comment]
No problem, there just seems to be so many issues with Bull and general confusion that I thought I'd share here - I otherwise wouldn't have.
