### ISSUE TITLE
Add Fallback Routes

### ISSUE THREAD

**Issue by getspooky** [nestjs/nest#5124]
Using the `@Fallback` decorator, you may define a route that will be executed when no other route matches the incoming request. Typically, unhandled requests will automatically render a "404" page via your application's exception handler. 

```js
@Fallback()
NotFound(@Req() request: Request): string {
    return 'Page Not Found';
 }
```

**Comment by jmcdo29** [comment]
Any reason you couldn't just add a filter specifically for the `NotFoundException` that Nest already handles? 
```typescript
import {
  ArgumentsHost,
  Catch,
  ExceptionFilter,
  NotFoundException,
} from '@nestjs/common';

@Catch(NotFoundException)
export class NotFoundFilter<T extends NotFoundException>
  implements ExceptionFilter {
  catch(exception: T, host: ArgumentsHost) {
    console.log('Route not found');
    host
      .switchToHttp()
      .getResponse()
      .status(exception.getStatus())
      .send({
        statusCode: exception.getStatus(),
        ...(exception.getResponse() as object),
      });
  }
}

```

**Comment by lucavb** [comment]
Hey,

the problem with that approach is that it prevents me from throwing a `NotFoundException` as part of my regular flow. This will get treated as the same with this middleware. Pretty much what `TheRennen` said in the second comment of the first solution. Is there really no other way to handle this? 

[That comment I mentioned](https://stackoverflow.com/questions/49879274/nestjs-default-wildcard-route)

**Comment by jmcdo29** [comment]
How would you suggest treating it differently? If Nest doesn't find a route, it by default throws a `NotFoundException` and handles it later thanks to the built in `BaseExceptionFilter`. If you wanted custom logic around it, you could pass a message with the exception and check if this is a 404 due to missing route or due to a bad id

**Comment by lucavb** [comment]
Hmm yes I see the problem of the distinction. So far I've only been using Nest but what would be the downside / problem with having something like `app.setGlobalFallbackHandler(new FallbackMiddleware)` or providing a function. At least my particular use case would only be for logging whether I forgot some routes that my frontend uses or whether Nest does not handle certain routes.
