### ISSUE TITLE
Cannot use ApiImplicitFile

### ISSUE THREAD

**Issue by hoangduy0610** [nestjs/nest#5125]
It was not until I fix @nestjs/swagger/dist/decoratos/index.d.ts that i could use ApiImplicitFile. I hope you fix it soon. Thanks you
P/s:Sorry because my English isn't good.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
