### ISSUE TITLE
Static file serving with Fastify doesn't work

### ISSUE THREAD

**Issue by munjalpatel** [nestjs/nest#5127]
## Current behavior
I am trying the get basic static file server using `Fastify` to work.

It keeps failing with the following error **even though I have installed `fastify-static` and is available in `node_modules`**:
```
[PackageLoader] The "fastify-static" package is missing. Please, make sure to install this library ($ npm install fastify-static) to take advantage of ServeStaticModule. +50ms
```

> Here is a repo to reproduce:
> https://github.com/munjalpatel/nest-fastify-static-test

## Code
**main.ts**

```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter({ logger: true }),
  );

  await app.listen(3000);
}

bootstrap();
```

**app.module.ts**

```ts
import { join } from 'path';
import { Module } from '@nestjs/common';
import { ServeStaticModule } from '@nestjs/serve-static';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [
    ServeStaticModule.forRoot({
      rootPath: join(__dirname, '..', 'client', 'dist'),
      renderPath: '/client/*',
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**package.json (deps)**

```json
"dependencies": {
  "@nestjs/common": "^7.0.0",
  "@nestjs/core": "^7.0.0",
  "@nestjs/platform-fastify": "^7.3.2",
  "@nestjs/serve-static": "^2.1.3",
  "fastify-static": "^3.2.0",
  "reflect-metadata": "^0.1.13",
  "rimraf": "^3.0.2",
  "rxjs": "^6.5.4"
}
```

## Expected behavior
When I navigate to `http://localhost:3000/client` I should see my static website served.

## Environment

<pre><code>
Nest version: 7.4.1
Node version: v12.16.3
Platform:  Mac
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by munjalpatel** [comment]
@jmcdo29 add a repo to use for repro --> https://github.com/munjalpatel/nest-fastify-static-test

**Comment by jmcdo29** [comment]
You need to use `fastify-static@2.7.0`. The current version you have is for Fastify v3 which is not yet supported by Nest.

**Comment by munjalpatel** [comment]
OK. Thanks!

**Comment by jagdishjadeja** [comment]
i am still facing same issue
