### ISSUE TITLE
Request to add getspooky to the triage team 

### ISSUE THREAD

**Issue by getspooky** [nestjs/nest#5130]
I have read and understood the project's Code of Conduct.
I also have read and understood the process and best practices around Express triaging.

I request for a triager role for the following GitHub organizations: `nestjs`

**Comment by jmcdo29** [comment]
Triage help is always appreciated on GitHub and in the [Discord](https://discord.gg/nestjs) server. I'm not sure why we'd need a new role inside the NestJS organization though.

**Comment by kamilmysliwiec** [comment]
Help is always appreciated and having a role isn't a prerequisite for this. We select people to the core team based on their contributions & commitment to the project.
