### ISSUE TITLE
Nest JS - Rest API Question

### ISSUE THREAD

**Issue by ramesh3535** [nestjs/nest#5133]
For example, I have REST API application is Person Account  API - I have 2 person accounts' in the request payload and out of 2 person account's there is  one person account required fields are missing. 
Now the question was do i need to get the results for other person account or it wouldn't be allow to execute the request payload if we missed required field for one person account. ?? Could you please advise ??

Required fields : externalid, phone , firstname, lastname & accountsource 
Example for Request payload
[
 {
	  "externalId": "XXXXXXXXXXXXX",
	  "accountSource": "XXXXXXXXXXXX",
	  "phone ": "XXXXXXXXXX",
	  "firstName": "Test1111",
	  "lastName": "XEEEEEE",
	 
	},
	{
	  "externalId": "XXXXXXXXXXXXX",
	  "accountSource": "XXXXXXXXXXXX",
	  "phone ": "XXXXXXXXXX",
	  "firstName": "Test1111" 
	 
	}
]

Currently ,  it wouldn't be allow to execute the request payload for other person account record also . we are getting  "Request missing field \"lastName\" at index 1." - like i am getting BadRequestException.

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for support questions. We are using GitHub to track Feature Requests, Regression and Bug Reports.

**Comment by ramesh3535** [comment]
Thanks for suggestion.
