### ISSUE TITLE
How can I use backpack in nest.js project?

### ISSUE THREAD

**Issue by YogiWu** [nestjs/nest#514]
I'm a beginner of nest.js and I meet a problem that when use backpack with ts-loader to start a development environment of nest.js, it always report errors like cannot find module or read undefined aftercompile. So will you add the support for backpack or how can I solve the problem?

**Comment by YogiWu** [comment]
Sorry for my stupid,here's something wrong in my configure.However,I need assure no problem to use backpack.

**Comment by kamilmysliwiec** [comment]
We need more details

**Comment by cojack** [comment]
@YogiWu if you're using TypeScript there is no reason to use backpack for it...

**Comment by YogiWu** [comment]
@kamilmysliwiec I've solved the problem of backpack.Here is my project url:[github](https://github.com/YogiWu/nest_nuxt.git).There is a problem of nuxt.js  that seemed like due to the discrepancy between the middleware in nest.js  and in express.

**Comment by YogiWu** [comment]
@cojack Because of the ts-node?However I using it for the reason of nuxt.js :joy:

**Comment by chanlito** [comment]
@YogiWu u don't need backpack to use nuxt.js

**Comment by YogiWu** [comment]
@chanlito I‘m a beginner of node.js. Could you recommend a tool with hot reload for me please?All I know is nodemon and backpack.

**Comment by cojack** [comment]
@YogiWu here you are, this is my "scripts" from package.json

```
  "scripts": {
    "start": "ts-node $NODE_DEBUG_OPTION src/index.ts",
    "dist": "node dist/index.js",
    "build": "tsc"
  },
```

Development process looks like: `npm start`, then I do `npm run build` and to run it ias node is enough to run command: `npm run dist`.

Does it helps to you?

**Comment by chanlito** [comment]
@YogiWu you use nodemon + ts-node for development.
