### ISSUE TITLE
Dynamic modules accidently shared in different modules

### ISSUE THREAD

**Issue by OpportunityLiu** [nestjs/nest#5140]
https://github.com/nestjs/nest/blob/1b43bac54819b235af87502a589ca577f76f1ec8/packages/core/injector/module-token-factory.ts#L10-L53

Currently, the `getDynamicMetadataToken` with `replacer` will get values like `'{"providers":[{"useFactory":"useFactory","inject":["ConfigService"],"provide":"REDIS_OPTIONS"},{"useFactory":"useFactory","inject":["REDIS_OPTIONS"]}]}'`, where `useFactory` is commonly a lambda function whose `name` will always be `"useFactory"`. Then dynamic modules will have an identical hash and be shared.

Is it possible to get a more reliable representation for functions? Maybe `hash(func.toString())`?

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by OpportunityLiu** [comment]
Is it safe to do this modification? I'm worry about performace impact or compatibility problems

**Comment by kamilmysliwiec** [comment]
@OpportunityLiu it should be safe :)

**Comment by imfengzi** [comment]
useFactory has different return value，but useFactory.toString() is same
