### ISSUE TITLE
"This" is undefined on nested injected provider

### ISSUE THREAD

**Issue by iruizmar** [nestjs/nest#5147]
## Current behavior
I have four providers declared on the same module, the first is injected on a controller, the second is injected in the first, the third injected in the second and the fourth injected in the third. The dependency graph is as follows:

Controller -> Provider 1 -> Provider 2 -> Provider 3 -> Provider 4

The problem comes when, in the Provider 1, my code runs a function of the Provider 2, that makes use of a function of the Provider 3 that makes use of a function of the Provider 4; all of them uses the instance of the provider they depend on that is injected by Nest on the constructor, using "this.injectedProvider". But "this" is undefined on Provider 3.

### Module
```ts
@Module({
  imports: [
    TypeOrmModule.forFeature([
        ...
    ]),
  ],
  controllers: [DialoguesController],
  providers: [
    DialoguesService,
    DialogueEntityMapper,
    DialogueNodeEntityMapper,
    DialogueOptionEntityMapper,
  ],
})
export class DialoguesModule {}```

### Provider 1 (The service that was injected on the controller)
```ts
@Injectable()
export class DialoguesService {
  constructor(
    @InjectRepository(DialogueEntity)
    private dialoguesRepository: Repository<DialogueEntity>,
    private readonly dialogueEntityMapper: DialogueEntityMapper,
  ) {}
  ...
  ...
  async getDialogue(id: string): Promise<DialogueDto> {
    const foundDialogue = await this.dialoguesRepository.findOne(id, {
      relations: ['nodes', 'nodes.options'],
      where: { id: id },
    });
    if (!foundDialogue) throw new DialogueNotFoundException();
    return this.dialogueEntityMapper.mapFromEntity(foundDialogue);
  }
}
```
### Provider 2 (Injected onto Provider 1)
```ts
@Injectable()
export class DialogueEntityMapper {
  constructor(
    private readonly dialogueNodeEntityMapper: DialogueNodeEntityMapper,
  ) {}

  mapFromEntity(dialogueEntity: DialogueEntity): DialogueDto {
    return {
      id: dialogueEntity.id,
      name: dialogueEntity.name,
      nodes: dialogueEntity.nodes
        ? dialogueEntity.nodes.map(this.dialogueNodeEntityMapper.mapFromEntity)
        : null,
    };
  }
}
```
### Provider 3 (injected onto Provider 2)
```ts
@Injectable()
export class DialogueNodeEntityMapper {
  constructor(
    private readonly dialogueOptionEntityMapper: DialogueOptionEntityMapper,
  ) {}

  mapFromEntity(dialogueNodeEntity: DialogueNodeEntity): DialogueNodeDto {
    return {
      id: dialogueNodeEntity.id,
      name: dialogueNodeEntity.name,
      content: dialogueNodeEntity.content,
      options: dialogueNodeEntity.options
        ? dialogueNodeEntity.options.map(
            this.dialogueOptionEntityMapper.mapFromEntity,
          )
        : null,
    };
  }
}
```

Important: I could not reproduce this on a bare repository. If this should be anywhere else but here, please, let me know,

## Expected behavior
"This" should have value.
## Environment

<pre><code>
Nest version: 7.0.0
 
For Tooling issues:
- Node version: v10.10.0 
- Platform:  Linux
</code></pre>

**Comment by kamilmysliwiec** [comment]
> Important: I could not reproduce this on a bare repository. If this should be anywhere else but here, please, let me know,

We can't help without having a minimal reproduction repository. Please, try to recreate & mirror your app structure in a separate repo.

**Comment by bostendorf-io** [comment]
This is actually not a bug with nest, but with your use of higher order functions.
this will error with this is undefined: `dialogueEntity.nodes.map(this.dialogueNodeEntityMapper.mapFromEntity)`
but this wont: `dialogueEntity.nodes.map(x => this.dialogueNodeEntityMapper.mapFromEntity(x))`

For clarification, here is a minimal example:
```js
let obj = {
    member: { value: 1 },
    pureFn(x) { return x; },
    method() { return this.member; },
    nestedMethod() { return this.member.value; },
};

[1].map(obj.pureFn) // returns [1], as expected
[1].map(obj.method) // returns [undefined], because `member` is not in the scope of `this` in Array.map
[1].map(obj.nestedMethod) // same as your bug
[1].map(x => obj.nestedMethod(x)) // returns [1], as expected
[1].map(obj.nestedMethod.bind(obj)) // returns [1] as well
```

For more explanation, see [MDN: this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)
