### ISSUE TITLE
Is there a way to explicitly apply DTO?

### ISSUE THREAD

**Issue by dilame** [nestjs/nest#5150]
## Feature Request

Not sure if this feature exists, but if it doesn't - it's just an unfortunate circumstances that definitely needs to be fixed.
I cant find a way to explicitly apply DTO. I was only able to find a way to apply it using TypeScript reflection, but this way it becomes impossible to use controller factories.

## Is your feature request related to a problem? Please describe.

```ts
function factory(DTO) {
  class Controller {
    @Post()
    method(@Body() dto: any) {}
  }
  return Controller;
}
```

## Describe the solution you'd like

The solution is fairly simple

```ts
function factory(DTO) {
  class Controller {
    @Post()
    method(@Body(DTO) dto: any) {}
  }
  return Controller;
}

```

**Comment by kamilmysliwiec** [comment]
We use `reflect-metadata` to reflect arguments types. You can change the TS design-time metadata using the `@Reflect.defineMetadata` decorator https://www.npmjs.com/package/reflect-metadata#api (metadata key is `design:paramtypes`).
