### ISSUE TITLE
Can I extends from abstract.controller

### ISSUE THREAD

**Issue by thangha610** [nestjs/nest#5155]
**Extend from parent class**
* I have a abstract.controller like:
```
import { HttpStatus, Get, Param, Post, Body, Patch, Delete, Type } from "@nestjs/common";
import FindOneParams from "src/utils/FindOneParams";

export default class AbstractController<Type> {
    _service: any;
    constructor(service: any) {
        this._service = service;
    }
    
    @Post()
    async create(@Body() item: Type) {
        console.log(item, 3482342349239423949234)
        const newitem = await this._service.create(item);
        return {
            statusCode: HttpStatus.CREATED,
            data: newitem
        };
    }
}
```    
* I wana extend from `AbstractController` and pass Interface into It. Ex:
```
@Controller('roles')
export class RolesController extends AbstractController<IRole> {
    constructor(private _rolesService: RolesService) {
        super(_rolesService);
     }

  @Post('test')
  async register(@Body() role: IRole) {
   console.log(role, 934939439)
  }
}
```
* Everything is okay but Interface IRole can't validate data. I create function register and it can validate my request body. I don't know what is wrong. Pls Help me.
* This is my interface validator:
```
import { IsString, IsNotEmpty, IsNumber, IsOptional } from 'class-validator';

export class IRole {
  @IsNumber()
  @IsOptional()
  id: number;

  @IsString()
  @IsNotEmpty()
  name: string;

  @IsString()
  @IsNotEmpty()
  @IsOptional()
  alias: string;

  @IsString()
  @IsOptional()
  role_data: string;

  @IsString()
  @IsOptional()
  description: string;
}

export default IRole;
```
P/s: My english is very bad, sorry.
**Thankssssssssssssss** 

* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
