### ISSUE TITLE
Guards does get applied to only some controller and not to others - no visible DI issue

### ISSUE THREAD

**Issue by vnenkpet** [nestjs/nest#5156]
## Current behavior
We have a guard applied to 2 controllers, the module that has the guard exports it and is imported in both the modules where these controllers are. 

The guard code doesn't get executed at all in one of them without giving any reason (checked by console.log on the first line of the canActivate method)

## Input Code
Simplified code:

```ts
@Module({
  imports: [IdentityModule],
  providers: [AService],
  controllers: [AController],
})
export class AModule {}

@Module({
  imports: [IdentityModule],
  providers: [BService],
  controllers: [BModule],
})
export class BModule {}

@Module({
  imports: [ConfigModule],
  providers: [Identity, TokenAuthGuard],
  exports: [Identity, TokenAuthGuard],
})
export class IdentityModule {}

// (...)

// this doesn't work
@ApiTags('A')
@UseGuards(TokenAuthGuard)
@ApiBearerAuth()
@Controller()
export class AController {}

// this does
@ApiTags('B')
@UseGuards(TokenAuthGuard)
@ApiBearerAuth()
@Controller()
export class BController {}
```

## Expected behavior
The guard's canActivate method should get called on both controllers on all methods.

## Possible Solution
I don't know if it could be caused by some else dependency (I had to remove some of the code due to security reasons) but we cannot see any issue or why should the same guard act differently in each module/controller when it's imported and applied the same way. 

## Environment

<pre><code>
Nest version: 7.3.2
</code></pre>

**Comment by vnenkpet** [comment]
It seems like it got fixed by removing some unrelated module/provider from the DI, but it still seems like this shouldn't be happening or at least we should get some sort of warning when a Guard is not getting applied for some reason if it's clearly defined in the controller.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
