### ISSUE TITLE
Controllers are providers.

### ISSUE THREAD

**Issue by dfee** [nestjs/nest#5158]
Controllers are providers. It feels like an inconsistency to have:

```ts
@Module({
  controllers: [MyController],
  providers: [MyService]
})
export class MyModule {}
```

When this distinction isn't a user concern:
```ts
@Module({
  providers: [
    MyController,
    MyService,
  ],
})
export class MyModule {}
```

Why does this matter? It's an inconsistency in the API design.

**Comment by kamilmysliwiec** [comment]
Controllers aren't providers.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.

**Comment by dfee** [comment]
I did mention that there. Why aren't they providers? If they're not providers, then neither are Guards, Interceptors, Resolvers, etc.

**Comment by kamilmysliwiec** [comment]
> Guards, Interceptors [..]

Yes, guards and interceptors are not providers either. Hence, you don't use `providers` array to define them.

**Comment by jmcdo29** [comment]
@dfee they may act __similar__ to providers, but as I said yesterday on Discord, they aren't the same. You still have dependency injection, but controllers have a whole other set of metadata and contexts to deal with, whereas services and providers are exactly what you write them to be. The same goes for other NestJS enhancers, as you don't normally call a Pipe's `transform` method, Nest does that for you.

**Comment by dfee** [comment]
My point is they _could_ be providers, and in typically DI parlance, they _should_ be. Metadata is irrelevant, as we know how to filter on provider attributes (look [here](https://github.com/nestjs/nest/blob/67e15afbf33364ac6dcf0ade58d26aade7c2eb1f/packages/core/hooks/on-app-shutdown.hook.ts#L68-L72) for an example).

As to Guards, yes I misspoke. Having gone through building an auth strategy, and using that as provider, I lumped the strategy and guard together.

Perhaps the question I'm trying to ask is why? There aren't design docs that discuss these tradeoffs, so it's a bit hard to evaluate all of this and keep the model in mind.
