### ISSUE TITLE
SSL on website is expired since Mon, 19 Mar 2018 07:08:29 UTC

### ISSUE THREAD

**Issue by marcj** [nestjs/nest#516]
See for example: https://docs.nestjs.com/recipes/swagger

More information at https://www.ssllabs.com/ssltest/analyze.html?d=docs.nestjs.com&latest.

![screen shot 2018-03-19 at 12 38 58](https://user-images.githubusercontent.com/450980/37593512-8362b762-2b72-11e8-847f-60618e453210.png)

**Comment by kamilmysliwiec** [comment]
Thanks, fixed 🙂
