### ISSUE TITLE
17-mvc-fastify - The "fastify-static" package is missing.

### ISSUE THREAD

**Issue by KASOGIT** [nestjs/nest#5167]
## Current behavior
When starting the `17-mvc-fastify` sample the application crash on startup with:
![image](https://user-images.githubusercontent.com/15908751/88906153-62cfe180-d257-11ea-869a-786997029107.png)

## Input Code
https://github.com/nestjs/nest/tree/master/sample/17-mvc-fastify
```
npm install
npm run start:dev
```

## Possible Solution
Add the needed package `fastfify-static@2.7.0`

I could submit a PR to fix it if necessary just tell me :)

Edit: The PR fixing the bug https://github.com/nestjs/nest/pull/5168

**Comment by kamilmysliwiec** [comment]
Thank you :)
