### ISSUE TITLE
Why constructor not working in service with using the Inject(REQUEST)?

### ISSUE THREAD

**Issue by B1anker** [nestjs/nest#5172]
## Regression
Why constructor not working in service with using the Inject(REQUEST)?

## Describe the regression

The console not print in the terminal.
## Input Code

https://github.com/B1anker/inject-constructor-issue/blob/c70f22e66582ca85ddd4254b0eae6d12f51a95cd/src/app.service.ts#L12
```ts
import { Injectable, Inject, Scope, OnModuleInit } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import { Request } from 'express';

@Injectable({
  scope: Scope.REQUEST
})
export class AppService implements OnModuleInit {
  constructor (
    @Inject(REQUEST) private readonly request: Request
  ) {
    // not print
    console.log("constructor");
  }

  onModuleInit () {
    // not print
    console.log("onModuleInit");
  }

  getHello(): string {
    return 'Hello World!';
  }
}
```

## Environment
<pre><code>
Nest version: 7.0.0 -> 7.4.2

For Tooling issues:
- Node version: 10.14.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by B1anker** [comment]
![image](https://user-images.githubusercontent.com/17514962/88948541-a280e280-d2c4-11ea-9016-6b5c467dc092.png)

**Comment by B1anker** [comment]
![image](https://user-images.githubusercontent.com/17514962/88948670-c512fb80-d2c4-11ea-917c-6c585dd321dc.png)

**Comment by jmcdo29** [comment]
The constructor isn't called because the `AppService` has not yet been created (same for the reason you don';t see the `onModuleInit` call). With `REQUEST` scoped providers, the provider (and classes the provider is injected into) are created until the request comes in, because the request needs to be injected into the provider, and without it the class just can't be created.

Please use our [Discord](https://discord.gg/nestjs) channel (Support) for support questions, as we are using GitHub to track feature request, bug reports and regressions.

**Comment by B1anker** [comment]
@jmcdo29 
Hi, request comes working well.

But now I have another issue.
Here's my reproduced expample:
[example](https://github.com/B1anker/inject-constructor-issue/blob/master/src/modules/user/user.service.ts)
cyclic dependencies with ```Inject(REQUEST)```

When I visited http://localhost:3000/user/1, the process had an error:
![image](https://user-images.githubusercontent.com/17514962/88959558-c64c2480-d2d4-11ea-954b-69c1d3c9fa74.png)
![image](https://user-images.githubusercontent.com/17514962/88959582-cd733280-d2d4-11ea-8959-332efc97924e.png)
it was behaved that constructor injects were failed.

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for support questions, as we are using GitHub to track feature request, bug reports and regressions.
