### ISSUE TITLE
Nest.js Swagger page returns 404 in firebase hosting setup

### ISSUE THREAD

**Issue by sformisano** [nestjs/nest#5178]
## Bug Report

When hooking nestjs to firebase functions/hosting, the JSON version of swagger works, but the interactive HTML swagger page returns a 404.

I'm not 100% sure this is a bug, but I particularly noticed that the main issue seems to be having the nestjs app using the swagger middleware and the express adapter having a get route with the same URL as the nestjs app middleware, i.e. https://github.com/nestjs/swagger/blob/master/lib/swagger-module.ts#L55-L57

If you change the get URL to something else the URL will work but because it diverges from the middleware URL it's unable to get the swagger files (which based on the name is what the swagger middleware is for).

Please note: this code runs properly, i.e. swagger works, if I run the nestjs server directly rather than hooking into firebase by sharing the express instance between firebase and the nestjs express adapter.

## Current behavior

1. Follow this simple setup https://fireship.io/snippets/setup-nestjs-on-cloud-functions/
2. Pick the swagger initialization code from here https://docs.nestjs.com/recipes/swagger
3. Serve the functions locally or deploy them online
4. If you browse `/api` you will get a 404 error, whereas `/api-json` works as expected

## Input Code

```ts
import { NestFactory } from '@nestjs/core';
import { ExpressAdapter } from '@nestjs/platform-express';
import { AppModule } from './app.module';
import * as express from 'express';
import * as functions from 'firebase-functions';
import {DocumentBuilder, SwaggerModule} from '@nestjs/swagger';

export const createNestServer = async (expressInstance) => {
  const adapter = new ExpressAdapter(expressInstance);
  const app = await NestFactory.create(
    AppModule,
    adapter,
  );
  
  const options = new DocumentBuilder()
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('explorer', app, document);
  
  return await app.init();
};

const server = express();

createNestServer(server)
  .then(v => console.log('Nest Ready'))
  .catch(err => console.error('Nest broken', err));

export const api = functions.https.onRequest(server);
```

## Expected behavior

The swagger page should be visible and functional.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/issues/437
