### ISSUE TITLE
Call external API

### ISSUE THREAD

**Issue by mmenik** [nestjs/nest#518]
In a javascript backend i usually use 'request' package to do hhtp calls to another external web service (REST Json).

In a Nestjs solution what's the best practice?

Thanks

**Comment by shekohex** [comment]
I recommending using [`Axios`](https://github.com/axios/axios) but since `v5.x` * _which will be released soon_ * you could use [`HttpModule`](https://github.com/nestjs/nest/blob/master/src/common/http/http.module.ts)

**Comment by kamilmysliwiec** [comment]
`HttpModule` is available already (in 4.6.6 as well). You can import it from `@nestjs/common/http`. It exposes `HttpService`. 🙂

**Comment by reyco1** [comment]
@RezaRahmati Just add HttpModule to your imports in your app.module.ts and then inject HttpService into your constructor.

**Comment by SafalTammewar** [comment]
the syntax for HTTP get method because I m getting no response can anyone provide me
