### ISSUE TITLE
is this a bad practice?

### ISSUE THREAD

**Issue by SebasLeal** [nestjs/nest#5181]
It is just a dude.
I have to use an endpoint like 100 times and this can take a lot of time, like 30-40 mins.

so im doing something like this.

` res.status(201).send();
await aLotOfWork();
return 'nobody will catch this so whatever'`;

**Comment by tubert** [comment]
I would take a look to a queue/message queue approach for this use case.

**Comment by BrunnerLivio** [comment]
Please, use our [Discord]( https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
