### ISSUE TITLE
NestJS for deno...

### ISSUE THREAD

**Issue by dev-akshat** [nestjs/nest#5183]
When can we user **_NestJS_** for _**deno**_  instead of _**node**_?

**Comment by jmcdo29** [comment]
[Please](https://github.com/nestjs/nest/issues/1796) [see](https://github.com/nestjs/nest/issues/3464) [the](https://github.com/nestjs/nest/issues/4495) [previously](https://github.com/nestjs/nest/issues/4832) [closed](https://github.com/nestjs/nest/issues/4876) [issues](https://github.com/nestjs/nest/issues/4963)

**Comment by Mistic92** [comment]
I checked all the link but everywhere is info that we'll think about support but no details. As we have new year maybe where is some roadmap for supporting Deno?:)

**Comment by kamilmysliwiec** [comment]
There's currently no plan to support Deno in the near future as I don't see any benefit that this transition (from Node to Deno) would potentially give us.
