### ISSUE TITLE
unable to listen event on WebSocketServer.on()

### ISSUE THREAD

**Issue by letsbask** [nestjs/nest#5186]
## Bug Report
 unable to listen on socket when a client emits on _channel_
       WebSocketGateway.server.on(_channel_,(data)=>{
           // do stuff
        })
## Current behavior
1. create a server variable  **@WebSocketServer() server: Server** inside **class @WebSocketGateway() MyServerGateway **
2. get an instance of **WebSocketServer** in **MyManagerClass** and try to listen on socket.
3. emit event from client app on above socket
4. unable to listen event on socket 

## Input Code
**manager class**
```ts
export class MyManagerClass{
newSocketGateWay
constructor(socket:MyServerGateway){}
this.newSocketGateWay = socket
this.newSocketGateWay.server.on(channel,(data) =>{
//do stuff
)
}
```
**gateway**
```ts
@WebSocketGateway()
export class MyServerGateWay{
@WebSocketServer() server: Server;
}
```
**client**
```ts
export class client implements OnInit {
socketClient :SocketIOClient.Socket
  ngOnInit() {
    this.x = socket.connect('http://localhost:3000')
    //_client knows the event '**channel**' that server is listening to_
  } 
 emitEvent(){
    const payload= { obj: objdata}  
    this.socketClient.emit(channel , playload)
    this.socketClient.close()
 }
}
```

## Expected behavior
get event and payload on server in **MyManagerClass**
## Possible Solution
Usage of @SubscribeMessage(MY_DYNAMIC_EVENT) 
## Environment

<pre><code>
Nest version: 7.4.1
Nest CLI Version : 7.4.1 
 
For Tooling issues:
- Node version: v12.14.1
- Platform:  Mac

Others:
N/A

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
