### ISSUE TITLE
Body-parser errors always transformed to 500

### ISSUE THREAD

**Issue by tomasAlabes** [nestjs/nest#5191]
## Current behavior
If you send a payload that is too big for body-parser, it should respond with a HTTP code 413. But Nest's`Base Exception Filter` is [considering BP's exception as an unknown error](https://github.com/nestjs/nest/blob/01dfe29458a2851e42efe8d5b4d614caf9935742/packages/core/exceptions/base-exception-filter.ts#L30), hence wrapping it in a `500 Internal Server Error`.

## Input Code
Vanilla Nest app with body-parser enabled. I can't paste the "too big" request.

## Expected behavior
As body-parser and cors are part of Nest core functionality, the errors thrown by them should be honored by the app.

## Possible Solution
Special check for cors/body-parser exceptions?
A special exception handler that comes with `platform-express` that understands express middleware?
Duck typing to see if the exception comes with a http status or error code?

## Environment
Nest version: 7.4.2
 
For Tooling issues:
- Node version: 12.18.3
- Platform:  Mac

### Others:
Using @nestjs/graphql but it doesn't even get to that layer.

```text
PayloadTooLargeError: request entity too large
    at readStream (/Users/path/to/repo/node_modules/raw-body/index.js:155:17)
    at getRawBody (/Users/path/to/repo/node_modules/raw-body/index.js:108:12)
    at read (/Users/path/to/repo/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/Users/path/to/repo/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/Users/path/to/repo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/path/to/repo/node_modules/express/lib/router/index.js:317:13)
    at /Users/path/to/repo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/path/to/repo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/path/to/repo/node_modules/express/lib/router/index.js:275:10)
    at cors (/Users/path/to/repo/node_modules/cors/lib/index.js:188:7)
```

**Comment by tomasAlabes** [comment]
Hi @kamilmysliwiec, do you think this is a bug or special exception filters are expected?

**Comment by tomasAlabes** [comment]
From @jmcdo29 in discord:
> this is something I've been thinking about since your raised the issue the first time. I could think of a way to make it work, but it may take me some time to getting some code for it. Until then, you could write your own Exception Filter that extends Nest's BaseExceptionFilter, or you could just write one from scratch 🙂 

My filter until this is added to the framework: https://gist.github.com/tomasAlabes/249229f97e22774b4ab9682105ce2ca6

**Comment by makhataibar** [comment]
`
import { NextFunction, Request, Response } from 'express';
import { json, OptionsJson } from 'body-parser';

export const jsonBodyParser = (options?: OptionsJson) => (
  req: Request,
  res: Response,
  next: NextFunction,
) => {
  json(options)(req, res, err => {
    if (err) {
      res.status(err.status).json(err);
    } else {
      next();
    }
  });
};

`

**Comment by heavenkiller2018** [comment]
how to fix it ?  "request entity too large"

**Comment by makhataibar** [comment]
> how to fix it ? "request entity too large"

It’s custom body parser middleware

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/5990
