### ISSUE TITLE
Handling Errors in components

### ISSUE THREAD

**Issue by gkucmierz** [nestjs/nest#5202]
## Is your feature request related to a problem? Please describe.

I found #956 this issue while I was trying to solve my problem:

And I realize I need solution to catch and handle any type of error globally in all my controllers.

Is there any way to do this now in NestJS?

**Comment by jmcdo29** [comment]
https://docs.nestjs.com/exception-filters#catch-everything

**Comment by gkucmierz** [comment]
Thank you!

I didn't noticed that.
