### ISSUE TITLE
Websocket connection closes with empty error object

### ISSUE THREAD

**Issue by ijohnrusu** [nestjs/nest#5205]
## Current behavior
I using platform-ws on nestjs app.
Sometimes on websocket conenction is closing direct after initialization. 
After OnGatewayConnection.handleConnection function is finished i receive in log message:
[Nest] 22144   - 08/04/2020, 8:16:49 PM   [WsAdapter] Object:
{}
 +10239601ms

## Input Code

`async handleConnection(client: any, request:any, server:Server) {

      try{
        let startTime = Date.now();
        console.log("new connection started");        
        const cookies = parseCookies(request);
        let token = '';
        let authCookie = cookies['Authorization'];
        if (authCookie) {
          token = authCookie.replace('Bearer ', '');
        } else {
          token = request.headers.authorization.replace('Bearer ', '');
        }          
        let user = await this.authSvc.CheckJwtToken(token);         
        console.log(user);     
        await this.disconnectAlreadyConnectedUsersById(user.id, server);
        user.ws = client;
        user.ws.lastPong = Date.now();
        client.user = user;
        client.user.token = token;
        client.id = await this.getUniqueId();
        client.send(JSON.stringify({event:"authenticated", data:{code:200}}));
        if(client.user.current_role){
          this.kafkaSvc.emit(`ws.${client.user.current_role}.connected`, {user:{
            roles:client.user.roles,
            id:client.user.id,
            token:client.user.token,
            current_role:client.user.current_role
          }});
        }else{          
          throw {message:`token does not have current_role on user_id:${user.id}`}
        }
        this.kafkaSvc.emit("ws.user.connected", {user:{
          roles:client.user.roles,
          id:client.user.id,
          token:client.user.token,
          current_role:client.user.current_role
        }});
        //this.JoinRoleRooms(client);
        console.log(`socket with id"\"${client.id}\" connected with success`); 
        client.on('ping', ()=>{
          console.log("PING RECEIVED FROM USER:"+ client.user.id); 
          client.lastPong = Date.now();
        });
        let endTime = Date.now();
        console.log(`time for new connection handling:\"${endTime - startTime}\"`);        
      }
      catch(e){
        client.send(JSON.stringify({event:"authenticationerror",data:{code:401,data:e.message}}));
        client.close()
        console.log(e);         
      }
    }`

`
async handleDisconnect(client: any) {

      let user = client.user;
      client.user = undefined;
      if(user.current_role){
        this.kafkaSvc.emit(`ws.${user.current_role}.disconnected`, {user:{
          roles:user.roles,
          id:user.id,
          token:user.token,
          current_role:user.current_role
        }});
      }
      this.kafkaSvc.emit("ws.user.disconnected", {user:{
        roles:user.roles,
        id:user.id,
        token:user.token,
        current_role:user.current_role
      }});  
      console.log(`socket with id"\"${client.id}\" terminated`)
    }
`

LOG OUTPUT:
new connection started
{
  aud: '1',
  jti: '32af8a20f9196a4826bba732ab095583d1037df24f75a545a3929fcad15c663181a38e1429e928c3',
  iat: 1596550459,
  nbf: 1596550459,
  exp: 1628086459,
  sub: '6',
  scopes: [],
  id: 6,
  roles: [ 'super-admin', 'admin', 'client', 'driver' ],
  current_role: 'client',
  permissions: []
}
socket with id""a864649c-54cb" connected with success
time for new connection handling:"7"
[Nest] 22144   - 08/04/2020, 8:16:49 PM   [WsAdapter] Object:
{}
 +10239601ms
socket with id""a864649c-54cb" terminated

## Expected behavior
I want to receive information why connection were closed by WsAdapter

## Environment

<pre><code>
Nest version: 7.4.1
 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Linux, Windows

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
