### ISSUE TITLE
Provides compatibility with Koa.js library

### ISSUE THREAD

**Issue by getspooky** [nestjs/nest#5210]
## Describe the solution you'd like

Nest makes use of the Express framework. As mentioned earlier, Nest also provides compatibility with other libraries such as, for example, Fastify, I think it would be a powerful to add [Koa.js](https://github.com/koajs/koa) integration. Especially koa.js is used by a large community 

```js
async function bootstrap() {
  const app = await NestFactory.create<NestKoaApplication>(
    AppModule,
    new KoaAdapter()
  );
  await app.listen(3000);
}
```

## What is the motivation / use case for changing the behavior?

- Expand the community

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/54
