### ISSUE TITLE
Wildcard support for Redis Microservices

### ISSUE THREAD

**Issue by Bidzina** [nestjs/nest#5211]
## Current behavior

Wildcard message pattern works only for MQTT and NATS
## Input Code

@MessagePattern('private-channel-*')
@MessagePattern('private-channel-+')

None of them work for Redis message pattern.

**Comment by kamilmysliwiec** [comment]
You should rather report this here https://github.com/NodeRedis/node-redis

**Comment by Bidzina** [comment]
@kamilmysliwiec But they have "psubscribe" method in their package and NEST's not implementing in @MessagePattern() decorator

**Comment by xAqweRx** [comment]
Is there any news about this feature?
