### ISSUE TITLE
onApplicationShutdown close the app immediately rather than wait the Promise to be resolved

### ISSUE THREAD

**Issue by shawnliujw** [nestjs/nest#5214]
## Current behavior
i registered the onApplicationShutdown to ensure the graceful shutdown inside kubernetes , and enable the 
`enableShutdownHooks` , but the app always been shutdown immediately when receive the `SIGTERM`.
like the below code , only output `ready to exit xxxxxx`

code run in docker container and run `docker stop` to stop the container ,  the process has received the singal `SIGTERM`.

BTW:  i tried use only `express` and `process.on('SIGTERM')` , it worked as expected.

## Input Code

```ts
@Injectable()
export class Service implements OnApplicationShutdown {

  onApplicationShutdown(signal?: string): Promise<any> {
    console.log('ready to exit', signal);
    return new Promise<any>((resolve, reject) => {
      setTimeout(() => {
        console.log('will exit now');
        resolve();
      }, 3000);
    });
  }

}
```

## Expected behavior
hope the `onApplicationShutdown` can wait the Promise to be resolved 

## Environment

<pre><code>
Nest version: 7.4.2

 
For Tooling issues:
- Node version: 12.18.2
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
To use shutdown hooks, you must enable listeners by calling `app.enableShutdownHooks()`. https://docs.nestjs.com/fundamentals/lifecycle-events#application-shutdown Do you have it enabled? If so, please, provide a minimal reproduction repository.

**Comment by shawnliujw** [comment]
It works now,  due to i used `yarn start: prod ` then i didn't pass the singal `SIGTERM` to node process properly,  now i changed to `node dist/main` it worked as expected.  Thanks

**Comment by nikelborm** [comment]
Hi guys I think the issue should be reopened

It works for prod as @shawnliujw  said `node dist/main`. But this is still a problem in development, because I have a development docker container that calls `nest start` and when i run `docker compose stop`, `OnModuleDestroy` does not get called even with
```app.enableShutdownHooks([ShutdownSignal.SIGTERM, ShutdownSignal.SIGINT]);```

And yes, the hooks works fine when it is production container which calling node directly
