### ISSUE TITLE
Guard mixin doesn't properly import services in constructor

### ISSUE THREAD

**Issue by Figments** [nestjs/nest#5215]
## Current behavior
When importing services to a guard mixin using a constructor, even when the module the guard is used in imports all the correct associated modules, said services come up as `undefined`.

## Input Code

[Repository to see the behavior described](https://github.com/Figments/roles-guard-problem)

## Expected behavior

The services imported should not be `undefined` and should be imported as expected.

## Environment

<pre><code>
Nest version: 7.4.1

 
For Tooling issues:
- Node version: 12.17.0
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
Have you tried adding the `@Injectable()` decorator on top of the `RolesGuardMixin` class?

**Comment by Figments** [comment]
Just tried it. Looks like it's working now. Can't believe I missed that. Thanks for the assist!

**Comment by kamilmysliwiec** [comment]
Sure thing:)
