### ISSUE TITLE
error after install nestjs 

### ISSUE THREAD

**Issue by rahulwebinfomart** [nestjs/nest#5218]
## Current behavior

After installing the nestjs, when i hit npm start. It will give below error
 
Error  host.onConfigFileDiagnostic is not a function 

## Input Code

nest new projectname
npm run start:dev

```
fresh project
```

## Expected behavior

run the server on mention port

## Environment

<pre><code>
Nest version: 7.4.1

 
For Tooling issues:
- Node version: 10.16.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by andreracz** [comment]
I Know this is closed, but I got the same error and found the cause, so leaving a comment if someone stumbles upon this in the future.

This error happens when you don't install the dependencies with ```npm install```

The correct commands to run for a new project are:

```bash
nest new projectname
npm install
npm run start:dev
```

**Comment by jmcdo29** [comment]
You shouldn't need to install. Unless you provide `--skip-install` the `@nestjs/cli` will install the dependencies for you using your package manager of choice (npm or yarn)
