### ISSUE TITLE
npm install command is not working for NestJs and its packages

### ISSUE THREAD

**Issue by guneraykut** [nestjs/nest#5220]
## Current behavior
Following packages can not be installed. 
<pre><code>
"@nestjs/common": "^6.11.3",
"@nestjs/config": "^0.5.0",
"@nestjs/core": "^6.11.3",
"@nestjs/jwt": "^6.1.1",
"@nestjs/passport": "^6.1.0",
"@nestjs/platform-express": "^6.11.3",
"@nestjs/swagger": "^4.2.2",
"@nestjs/typeorm": "^6.2.0",
</pre></code>
![image](https://user-images.githubusercontent.com/21086881/89519386-f61f8e80-d7e4-11ea-8c1b-51303cd0e0a0.png)

## Input Code

As an example: 

```console
npm i @nestjs/platform-express@6.11.3
```

## Expected behavior
Installing of NestJS and its dependencies like `cli` or `typeorm`

**Comment by gkTim** [comment]
Also having this issue with the current version of the packages.

**Comment by georgesbiaux** [comment]
Me too

**Comment by kamilmysliwiec** [comment]
There's a temporary issue in NPM registry: https://status.npmjs.org/

![image](https://user-images.githubusercontent.com/23244943/89520682-86a6a080-d7de-11ea-9230-21ca2530f04c.png)

**Comment by kamilmysliwiec** [comment]
Reopening for visibility

**Comment by gkTim** [comment]
Seems to work again.
@kamilmysliwiec Thanks for the quick response!

**Comment by guneraykut** [comment]
It still continues for dependencies like `'@nestjs/config@^0.5.0`. Maybe it can be version specific. I guess it will be fixed soon. 
Thanks for your quick response @kamilmysliwiec

**Comment by bryansilva10** [comment]
I can't even install Nest, let alone it's dependencies. I guess we just have to wait.

**Comment by guneraykut** [comment]
You can use mirror if you want as suggested here. <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Folks, you can workaround this issue with using public NPM mirrors. But the mirrors I could find were only chinese mirror. Please recommend if there is any other better alternative. Thanks!<a href="https://t.co/YZz5ikObKr">https://t.co/YZz5ikObKr</a></p>&mdash; 김지현 (@simnalamburt) <a href="https://twitter.com/simnalamburt/status/1291313412748664833?ref_src=twsrc%5Etfw">August 6, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by mrpharderwijk** [comment]
Wauw, this is really annoying! I thought it was just me. So try to generate a new project with `nest new` but even that has issues...

**Comment by kamilmysliwiec** [comment]
It should be resolved now
