### ISSUE TITLE
构建工程安装出错

### ISSUE THREAD

**Issue by magdsnail** [nestjs/nest#5221]
npm i -g @nestjs/cli  此命令出错

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nestjs%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@nestjs/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by kamilmysliwiec** [comment]
There's a temporary issue in NPM registry: https://status.npmjs.org/

![image](https://user-images.githubusercontent.com/23244943/89520682-86a6a080-d7de-11ea-9230-21ca2530f04c.png)

**Comment by magdsnail** [comment]
> NPM注册表中存在一个临时问题：[https](https://status.npmjs.org/) : [//status.npmjs.org/](https://status.npmjs.org/)
> 
> ![图片](https://user-images.githubusercontent.com/23244943/89520682-86a6a080-d7de-11ea-9230-21ca2530f04c.png)

thank you

**Comment by magdsnail** [comment]
什么时候可以好，能知道吗？谢谢您 @kamilmysliwiec

**Comment by magdsnail** [comment]
换了镜像源之后好了

**Comment by kamilmysliwiec** [comment]
It should be resolved now

**Comment by magdsnail** [comment]
嗯嗯 看到了已经好了 谢谢
