### ISSUE TITLE
Can't accept URL params longer than 100 characters solution

### ISSUE THREAD

**Issue by Keimeno** [nestjs/nest#5225]
The problem mentioned in #2065 did not receive a proper solution. The issue was locked automatically, and therefore I want to give my solution to this problem here.

@raffomania is using Fastify, which sets it's parameter length limit to 100 characters which is problematic if using email as parameter. It was mentioned that the body parser options have to be overwritten which is not entire true. 
Overriding the body parser options via `app.use(urlencoded({ parameterLimit: 1000 }));` doesn't do anything. The default body parser options are already at 1000 and not 100. However Fastify seems to ignore external body parser settings. The way this can be overwritten is by writing the following:

```ts
const app = await NestFactory.create<NestFastifyApplication>(
  AppModule,
  new FastifyAdapter({ maxParamLength: 1000 }),
);
```

Fastify offers the maxParamLength option, which must be set on initialisation.

@kamilmysliwiec could we move or pin this comment to/in #2065 if possible?

**Comment by kamilmysliwiec** [comment]
Thanks for sharing the solution @Keimeno! Will link this issue in #2065 :)

**Comment by MartinSchere** [comment]
This solution weirdly sets my application into a permanent loading state when inserting a long parameter.

**Comment by FranciscoKloganB** [comment]
How would one do this in express and for specific endpoints only?
