### ISSUE TITLE
ValidateNested Is not working as expected

### ISSUE THREAD

**Issue by tavoohoh** [nestjs/nest#5226]
## Current behavior
Validate nested objects is not working for me. Here's An example of what I'm trying to do:

```ts
export class AdministratorDto {
  @IsNotEmpty()
  readonly firstName: string
}

export class BasicInformationDto {
  @ValidateNested()
  @Type(() => AdministratorDto)
  readonly administrator: AdministratorDto;
}
```

If firstName is not defined the validation returns: 
```json
{
  "message": "invalid params",
  "error": {
    "validators": [
      null
    ]
  }
}
```

## Expected behavior
The expectation is that the validation return a message saying that `firstName` is required. Instead is returning `null`.

## Possible Solution
Is something missing at my side?

## Environment

<pre><code>
Nest version: ^6.7.2

 
For Tooling issues:
- Node version: v10.16.1
- Platform:  Windows
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by tavoohoh** [comment]
Guys I'm using a custom `exceptionFactory`, I believe that's is what is causing this error.

```ts
 app.useGlobalPipes(
    new ValidationPipe({
      exceptionFactory: (errors) => {
        const exception = new ClassValidationException(errors);
        logger.error(exception.toString());

        return exception;
      }
    })
  );
```

Apologies for opening this issue. I will close it now.
