### ISSUE TITLE
Upgrading from grpc to @grpc/grpc-js

### ISSUE THREAD

**Issue by davidhuang1550** [nestjs/nest#5227]
## Is your feature request related to a problem? Please describe.

 I am currently using NestJS Microservices v7.4.2 which is dynamically requiring GRPC lib for ClientGrpcProxy. However, GRPC lib is being deprecated. The new version grpc-js is going to replace regular grpc. After switching to grpc-js, I am encountering package loader exceptions due to the dynamic loading of old grpc. Is there going to be an update on this to be able to use the new version of grpc-js? or is there a workaround for this?

Issue when using @Grpc/grpc-js

'The "grpc" package is missing. Please, make sure to install this library ($ npm install grpc) to take advantage of ClientGrpcProxy.'

![Issue](https://user-images.githubusercontent.com/22035024/89578943-f0d03d00-d800-11ea-8e2b-3a3488c7bedc.png)

Deprecation notice to package: https://www.npmjs.com/package/grpc

## Describe the solution you'd like

![Solution](https://user-images.githubusercontent.com/22035024/89578916-e9109880-d800-11ea-8a09-026270d82c7a.png)

dynamically require new version of grpc or have this configurable

## Teachability, Documentation, Adoption, Migration Strategy

N/A
## What is the motivation / use case for changing the behavior?

Issue when using new version of @grpc/grpc-js

**Comment by davidhuang1550** [comment]
just noticed the duplicate to

https://github.com/nestjs/nest/issues/4799

is there a target date for the new version?

**Comment by kamilmysliwiec** [comment]
> is there a target date for the new version?

Unfortunately, not yet. Switching to a different package is a breaking change, so we must wait till the next major release. We'll keep you informed!

Let's track this here #4799
