### ISSUE TITLE
Predifined data for reflectors

### ISSUE THREAD

**Issue by TheBlue-1** [nestjs/nest#5229]
## Is your feature request related to a problem? Please describe.
I want to make sure the object my api returns is of the right type. 
As Example:
``` 
@Get()
  test(): User {
    const x: any = { username: 'username', id: '0', noUserProperty: 'something' };
    return x;
  }
```
should return a object without "noUserProperty"
I'm using an interceptor where I call plaintoclass, but to do so i need the classType of the returntype of my handler.

## Describe the solution you'd like
I think the reflector should not just contain Metadata added by decorators. It should also contain some information about the function|class|whatever. In case of a function something like `{returnType,parameters,declearigType,accessability}:FunctionInfo`. Many other languages have this feature, but not typescript. Thats why I think the nestjs reflector should contain this feature.
## Teachability, Documentation, Adoption, Migration Strategy
You can use this feature everywhere you can use a reflector. Than call something like `reflector.predifinedInfo(type)` and use the "reflected" information.

## What is the motivation / use case for changing the behavior?
Currently i use a Metatag to describe my returnType, which is very akward.
With this feature you could easily make sure, that you return the correct type at requests.
Also you can use this for many other dynamic practices.

**Comment by jmcdo29** [comment]
Nest's `Reflector` is a wrapper of `Reflect` with slightly more user friendly functions. This means that it isn't adding any additional data or properties to the base `Reflect`, just making it easier to work with. What you're asking for would need to be at the language level, and reported to Typescript for the additional metadata to be available. There really isn't much Nest is going to be able to do to provide this extra data.
