### ISSUE TITLE
Testing With Database

### ISSUE THREAD

**Issue by psaunders** [nestjs/nest#523]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
The documentation is pretty weak on integration testing but even a read through of all the issues had no solution that worked for me.

```
Nest can't resolve dependencies of the RoundService (?). Please verify whether [0] argument is available in the current context.
```

A TypeOrm entity
```
import {Entity, PrimaryGeneratedColumn, BaseEntity} from "typeorm";

@Entity('round')
export class Round extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;
}
```

A Service
```
import { Component } from '@nestjs/common';
import { Round } from './round.entity';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

@Component()
export class RoundService
{
  constructor(
    @InjectRepository(Round)
    private readonly repo: Repository<Round>
  ) { }

 someFunction(){
    return "I exist";
 }

```

A test
```
import { Test, TestingModule } from "@nestjs/testing";
import { RoundService } from "../round.service";
import { TypeOrmModule } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { Round } from "../round.entity";

describe('RoundService', () => {

  let service: RoundService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [TypeOrmModule.forRoot()],
      components: [RoundService, {
        provide: RoundRepository,
        useClass: Repository
      }
      ]
    }).compile();

    service = module.get<RoundService>(RoundService);
  });

  describe('run', () => {
    it('should be able to run some function', async () => {
      service.someFunction();
    });
  });
}
```

## Expected behavior
Test to new up the service successfully.

## Minimal reproduction of the problem with instructions

#363 has answers from @VinceOPS that would lead me to believe this would work, but obviously "RoundRepository" doesn't exist because it's called "Round". If you can help me out with this I'll submit a PR for the docs, I think injecting more complex dependencies really illustrates the structure of a NestJS application well.

## Environment

<pre><code>
Nest version: 4.6.6

**Comment by pumano** [comment]
Also very important for me

**Comment by kamilmysliwiec** [comment]
I'm on it! Will update docs soon. Closing due to #363 duplicate.
