### ISSUE TITLE
Nest can't resolve dependencies of service when starting up, despite e2e tests using the whole AppModule running just fine.

### ISSUE THREAD

**Issue by vnenkpet** [nestjs/nest#5235]
## Current behavior
I can't run nest start because I'm getting 

```sh
$ npm start
```

```
Nest] 2313   - 2020/08/09 10:02:24   [NestFactory] Starting Nest application...
[Nest] 2313   - 2020/08/09 10:02:24   [ExceptionHandler] Nest can't resolve dependencies of the ProjectRepoService (IdentityService, ?). Please make sure that the argument dependency at index [1] is available in the ProjectModule context.

Potential solutions:
- If dependency is a provider, is it part of the current ProjectModule?
- If dependency is exported from a separate @Module, is that module imported within ProjectModule?
  @Module({
    imports: [ /* the Module containing dependency */ ]
  })
```

```typescript
// main.ts

import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();

```

However testing the AppModule in e2e test runs just fine. 

```typescript
  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });
```

```
 api@0.0.1 test:e2e /Users/petr/Projects/Personal/project-a/api
> jest --config ./test/jest-e2e.json

 PASS  test/app.e2e-spec.ts
  AppController (e2e)
    ✓ GET / (227 ms)
    ✓ GET /:dsn/identity (14 ms)
    ✓ POST /:dsn/capture/service-a/service-b (12 ms)
    ✓ GET /:dsn/identity (9 ms)
    ✓ POST /:dsn/capture/service-a/service-b (repeat) (13 ms)
    ✓ GET /:dsn/identity (15 ms)
    ✓ POST /:dsn/capture/service-a/service-c) (10 ms)
    ✓ GET /:dsn/identity (10 ms)

Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        3.31 s, estimated 7 s
```

And so do all the other tests throughout the code when in most of them the AppModule is also imported in the testing module as whole.

I've also checked multiple times and I see absolutely no reason why "Nest can't resolve dependencies of the ProjectRepoService (IdentityService, ?). Please make sure that the argument dependency at index [1] is available in the ProjectModule context.", because the service on Index 1 is imported through the same module as the service on index 0 where both of them are registered as providers and exported. 

```typescript
import { Module } from '@nestjs/common';
import { IdentityService } from './identity/identity.service';
import { ProjectIdentityService } from './project-identity/project-identity.service';

@Module({
  providers: [IdentityService, ProjectIdentityService],
  exports: [IdentityService, ProjectIdentityService],
})
export class IdentityModule {}
```

```typescript
import { Module } from '@nestjs/common';
import { ProjectRepoService } from './project-repo/project-repo.service';
import { IdentityModule } from 'src/shared/identity/identity.module';

@Module({
  imports: [IdentityModule],
  providers: [ProjectRepoService],
  exports: [ProjectRepoService],
})
export class ProjectModule {}
```

```typescript
@Injectable()
export class ProjectRepoService {
  constructor(
    private readonly identity: IdentityService,
    private readonly projectIdentity: ProjectIdentityService,
  ) {}
}
```

And they're also both basically identical (only with different names and type of private property, and both are request-scoped). 

## Input Code
The current repository (I have no idea what is the cause of this issue so I really can't strip it down to only relevant code, however the repo is really small currently).

https://github.com/vnenkpet/nest-minimal-repo-bug/tree/master/api

## Expected behavior
Running nest start should resolve all dependencies same as creating the testing module or neither should run if there was an issue. 

## Environment

<pre><code>
Nest version: 7.4.2

 
For Tooling issues:
- Node version: v12.10.0
- Platform:  Mac

</code></pre>

**Comment by vnenkpet** [comment]
I also tried to check for circular dependencies but I don't see any.

**Comment by fgirardey** [comment]
I have the same issue with unit testing on a controller, the TestingModule seems to not be hydrated with services, it is just broken IMO.

**Comment by vnenkpet** [comment]
I don't think the issue is with the TestingModule in my case. If anything, TestingModule seems to work as intended, while the regular nest application cannot resolve the same dependencies for some weird reason. I feel like if there really was the issue it says when trying to start up the nest app there is now way the e2e tests would pass for me as they actually use the services that have the issue and it seems to work correctly.

**Comment by fgirardey** [comment]
I'm surprised because, for me, this doesn't work and fail with the following error.

```
AppController › getData › should return "Welcome to web-service!"

    TypeError: Cannot read property 'getData' of undefined

       9 |      @Get()
      10 |      get(): { message: string } {
    > 11 |              return this.appService.getData();
         |                                     ^
      12 |      }
      13 | }
      14 | 
```

```typescript
import { Test, TestingModule } from '@nestjs/testing';

import { AppController } from './app.controller';
import { AppService } from './app.service';

describe('AppController', () => {
  let app: TestingModule;

  beforeEach(async () => {
    app = await Test.createTestingModule({
      controllers: [AppController],
      providers: [AppService],
    }).compile();
  });

  describe('getData', () => {
    it('should return "Welcome to web-service!"', () => {
      const appController = app.get(AppController);
      expect(appController.getData()).toEqual({ message: 'Welcome to web-service!' });
    });
  });
});
```

For me it's clear that when we get an instance of a controller the service is not automatically provided to the controller, which is weird.

**Comment by vnenkpet** [comment]
@fgirardey I am pretty sure that's an unrelated issue to mine. 
I also think that happens when you forget something like @Injectable decorator on the service or something similar, you'd have to provide more code to see the issue, but I think it should be under a different issue.

**Comment by fgirardey** [comment]
Yeah maybe you are right, but i'm pretty sure that i did not forgot any decorator, anyway i'll not pollute your issue with mine 😅

**Comment by fgirardey** [comment]
Found my issue, it was the missing `emitDecoratorMetadata` TypeScript flag in my various `tsconfig.json`. Sorry for bothering.

**Comment by jmcdo29** [comment]
@vnenkpet your `ProjectRepoService` has a file import to `ProjectIdentityService` which has a file import back to `ProjectRepoService`, making a circular dependency. I assume `ts-jest` handles this in a different way than `tsc` naturally does, which allows you to run things through `jest`. 

You should move all of the interfaces to separate files so they can be imported without creating circular file references.

**Comment by vnenkpet** [comment]
Ah okay thanks! That's something I didn't realize, I only checked for
circular deps in Nest module imports...

2020年8月9日(日) 18:58 Jay McDoniel <notifications@github.com>:
