### ISSUE TITLE
[Suggestion] Declaration of entities in TypeOrmModule.forFeature add them automaticly in typeOrmModule.forRoot entities list

### ISSUE THREAD

**Issue by Leccho** [nestjs/nest#5240]
## Feature Request
I'm curently using mysql with typeORM in a NestJS project and I would like to offer a suggestion.
### How it's working now:
As of now, you have to declare each entity twice instead of once once in the forRoot and again in the forFeature function.

app.module.ts:
```typescript
@Module({
  imports: [
    UserModule,
    TypeOrmModule.forRoot({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      username: 'demo',
      password: 'none',
      database: 'demo',
      entities: [
        User,
        UserType
        // Or importing all using glob
      ],
      synchronize: true,
    }),
  ]
})
```
user.module.ts:
```typescript
@Module({
  imports: [
    TypeOrmModule.forFeature([
      User,
      UserType
    ])
  ]
})
```

### What I'm suggesting:
Instead of declaring twice and reducing readability of the code (especially in bigger project) I suggest automaticly adding the entities present in forFeature in the entities list. This also insured the modularity.
app.module.ts:
```typescript
@Module({
  imports: [
    UserModule,
    TypeOrmModule.forRoot({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      username: 'demo',
      password: 'none',
      database: 'demo',
      entities: [ ],
      synchronize: true,
    }),
  ]
})
```
user.module.ts:
```typescript
@Module({
  imports: [
    TypeOrmModule.forFeature([
      User,
      UserType
      // By declaring these entities here, it's automaticly added in the entities list of our forRoot if we have imported our user module in our app module.
    ])
  ]
})
```

Thank you for reading!

**Comment by kamilmysliwiec** [comment]
This is already available https://docs.nestjs.com/techniques/database#auto-load-entities

**Comment by Leccho** [comment]
Thanks alot, I missed it!
