### ISSUE TITLE
BadRequestException 400 getting returned to client as a 500 error

### ISSUE THREAD

**Issue by johncmunson** [nestjs/nest#5241]
## Current behavior

I have an endpoint that is returning 500 when it should be returning 400. The controller associated with this endpoint is throwing a BadRequestException, but when it bubbles up to the global Nest error handling mechanism it is not being recognized as an instance or subclass of HttpException. Therefore, Nest is returning a default of 500 to the client.

```ts
import { isoToDate } from 'shared-nest-logic';

@Controller('todos')
class TodosController {
  constructor(private readonly todoService: TodoService) {}

  @Get()
  async getTodos(
    @Query('start') start: string,
    @Query('end') end: string
  ) {
    // isoToDate comes from a library that contains shared logic
    // for several different Nest apps. This library lists
    // @nestjs/core and @nestjs/common as dependencies.
    // When a required query parameter is missing, isToDate will
    // throw a NestJS BadRequestException.

    const [startDate, endDate] = [isoToDate(start), isoToDate(end)];
    const todos: Todo[] = this.todoService.getTodos(startDate, endDate);
    return todos;
  }
}
```

## Expected behavior

I would expect Nest to recognize the BadRequestException as a valid instance of HttpException and return 400 to the client, rather than the fallback error of 500.

## Environment

<pre><code>
Application:
  @nestjs/common: 7.3.2
  @nestjs/core: 7.3.2

Library:
  @nestjs/common: 7.3.2
  @nestjs/core: 7.3.2
 
- Node: 10.16.3
- NPM: 6.9.0
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction.

**Comment by kamilmysliwiec** [comment]
> // isoToDate comes from a library that contains shared logic
    // for several different Nest apps. This library lists
    // @nestjs/core and @nestjs/common as dependencies.

Shared libraries should list `@nestjs/core` and `@nestjs/common` as **peerDependencies**. Otherwise, `httpException instanceof HttpException` in which `httpException` is thrown from shared library will give `false` value.

**Comment by v1d3rm3** [comment]
I did what you said, but it not worked.

**Comment by jmcdo29** [comment]
@v1d3rm3 without a reproduction I can't tell you what's wrong. What Kamil said it's the correct approach. If you're working with this locally, you'll need to move the built library to the `node_modules` rather than using something like `npm link` due to Typescript's class instanceof resolution

**Comment by v1d3rm3** [comment]
@jmcdo29, i'm using Lerna. I'll try to create a reproduction. Thanks.

**Comment by v1d3rm3** [comment]
@jmcdo29 @kamilmysliwiec 
reproduction https://github.com/v1d3rm3/nestjs-monorepo-bug

**Comment by kamilmysliwiec** [comment]
@v1d3rm3 your code is invalid. `@nestjs/common` and `@nestjs/core` should be defined as peer dependencies, not dependencies.
