### ISSUE TITLE
WebSocketGateway should allow services

### ISSUE THREAD

**Issue by kkoomen** [nestjs/nest#5244]
## Bug Report

I'm using websockets and I need to use some specific headers. I need to be able to use my custom `configService` to get the values that I want. Right now it seems that it can't be achieved.

## Input Code

```ts
@WebSocketGateway({
  handlePreflightRequest(req, res) {
    const headers = {
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      'Access-Control-Allow-Origin': 'http://localhost:8000', // <-- this needs to be like: this.configService.get('...')
      'Access-Control-Allow-Credentials': true,
    };
    res.writeHead(200, headers);
    res.end();
  },
})
export class MessageGateway {}
```

The downside of this is that I can't use services since it's a decorator.

## Expected behavior

Allow gateways' settings to be changed with services

## Possible Solution

no idea.

## Environment

<pre><code>Nest version: 7.3.2</code></pre>

**Comment by jmcdo29** [comment]
This is a limitation of Typescript, class members cannot be used in decorators. You can save the value to a file and read it from there, but there's not much that can be done in a decorator

**Comment by kkoomen** [comment]
@jmcdo29 Can it be made in such as way that it can be modified in the constructor?

**Comment by jmcdo29** [comment]
You could try reflecting the metadata from the constructor, but it's probably too late at that point as the server has already been set up and read the options set, more than likely

**Comment by kkoomen** [comment]
That was my only remaining idea yeah.

**Comment by AlexandrChehlovDevPro** [comment]
@kkoomen Have you resolved the issue? Please share the details.
