### ISSUE TITLE
Unit test for controller

### ISSUE THREAD

**Issue by bcba25** [nestjs/nest#5252]
## Current behavior
I do have the following controller method which I'm trying to unit test:

```
@Get('list')
    public async findAll(@Res() res) {
        try {
            const users = await this.usersService.findAll();
            return res.status(HttpStatus.OK).json(users);
        } catch (error) {
            throw new MessageCodeError('request:error');
        }
}
```

## Input Code
Controller test example
https://pastebin.com/UbYc3r56

## Expected behavior
When running the tests, displays the following message, and it seems like the controller service is not mocked
```
console.log src/modules/users/users.controller.ts:48
      Error:  TypeError: Cannot read property 'json' of undefined
          at UsersController.findAll
```

## Environment

<pre><code>
Nest version: 7.0.0

For Tooling issues:
- Jest: 25.1.0

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for help and questions. We are using GitHub to track bug reports, regression reports, and feature requests.
