### ISSUE TITLE
Validation pipe primitive transformation not working

### ISSUE THREAD

**Issue by ColinMorris83** [nestjs/nest#5253]
## Current behavior

Set the validation pipe globally with transform true:
`app.useGlobalPipes(new ValidationPipe({ transform: true }));`

Have a route taking path params e.g.:
```
@Get(':val')
methodName(@Param() params: PathParamsWithPropertiesThatWeWantToBeIntegers) {
}
```

```
class PathParamsWithPropertiesThatWeWantToBeIntegers {
  @IsInt()
  val: number;
}
```

Try to call the route e.g /route/5

Validation errors:
val must be an integer number

## Expected behavior

According to the migration guide from Nest 6 to 7, this should be auto transformed, therefore expected behaviour would be no validation errors.

## Environment

<pre><code>
Nest version: 7.4.2

 
For Tooling issues:
- Node version: 12.16.0
- Platform:  Mac

**Comment by jmcdo29** [comment]
Route parameters always come in as strings. This is a problem with `class-transformer` not Nest. Please report it there accordingly.

**Comment by kamilmysliwiec** [comment]
To fix this, enable the implicit type conversion https://github.com/typestack/class-transformer#implicit-type-conversion

```typescript
app.useGlobalPipes(
  new ValidationPipe({
     transformOptions: { enableImplicitConversion: true },
  }),
);
```

**Comment by ColinMorris83** [comment]
Thanks, I think I tried that and it works for that particular use case. What would happen though if the model was declared as a string with @IsString() validator, I presume that would then fail as will have turned the route param value into a number? I have stuck with specifying @Type(() => Number) in places where I want conversion

**Comment by johnnybarton411** [comment]
@kamilmysliwiec I'm curious why we would need to use the "implicit conversion" (i.e. using the type information that is provided by typescript), where my understanding is the `app.useGlobalPipes(new ValidationPipe({ transform: true }));` should transform the types based on the decorators, i.e. `@IsInt()` should attempt to transform a string to an integer. Any insight would be helpful, thanks!

**Comment by verycosy** [comment]
> @kamilmysliwiec I'm curious why we would need to use the "implicit conversion" (i.e. using the type information that is provided by typescript), where my understanding is the `app.useGlobalPipes(new ValidationPipe({ transform: true }));` should transform the types based on the decorators, i.e. `@IsInt()` should attempt to transform a string to an integer. Any insight would be helpful, thanks!

agree with you

**Comment by ianzone** [comment]
> To fix this, enable the implicit type conversion https://github.com/typestack/class-transformer#implicit-type-conversion
> 
> ```ts
> app.useGlobalPipes(
>   new ValidationPipe({
>      transformOptions: { enableImplicitConversion: true },
>   }),
> );
> ```

Would you please add this solution to the docs? Otherwise, it's a bit confusing.
https://docs.nestjs.com/techniques/validation#transform-payload-objects

**Comment by carlosloaiza21** [comment]
hey look at this

```
import { Type } from 'class-transformer';
import { IsInt, IsNotEmpty } from 'class-validator';

export class CreateCatDto {
  
  @IsNotEmpty()
  @IsInt()
  @Type(() => Number)
  age: number;
  
}
```
It worked for me

**Comment by HuzefaC** [comment]
> hey look at this
> 
> ```
> import { Type } from 'class-transformer';
> import { IsInt, IsNotEmpty } from 'class-validator';
> 
> export class CreateCatDto {
>   
>   @IsNotEmpty()
>   @IsInt()
>   @Type(() => Number)
>   age: number;
>   
> }
> ```
> 
> It worked for me

This might create a weird bug where if someone sends in age as `true` it might do Number(true) which will turn out to be 1.
