### ISSUE TITLE
Second optional argument with a status message for a @HttpCode decorator

### ISSUE THREAD

**Issue by muturgan** [nestjs/nest#5256]
## Is your feature request related to a problem? Please describe.
Some times teams uses non-standard status codes. For example for internal projects and with following any internal conventions.  
But if you try to pass a non-standard status code to a @HttpCode decorator, like @HttpCode(277), then you will see the next header at an http response: "HTTP/1.1 277 unknown". If team have some internal status code dictionary then they can prefer to see something like "HTTP/1.1 277 Updated". (Btw the same point for non-standard codes at the HttpException. You can pass a 419 code for example. Non-standard but very common. And the status message will be "unknown" too).

## Describe the solution you'd like
I suggest to add an optional second argument for the HttpCode decorator (and third for the HttpException) with a custom status message.

**Comment by kamilmysliwiec** [comment]
You can use the `@SetMetadata()` decorator in combination with an interceptor to accomplish this. We don't plan to add this to the core.
