### ISSUE TITLE
Make SwaggerModule.createDocument parse some decorators from @nestjs/common

### ISSUE THREAD

**Issue by muturgan** [nestjs/nest#5257]
## Is your feature request related to a problem? Please describe.
Using a few decorators make you method code very neat. But using lots of decorators make it too noisy and flickering. 
Using @nestjs/swagger is super useful but unfortunately leads to a decorators count increasing.

## Describe the solution you'd like
I suggest to make SwaggerModule.createDocument parse some decorators from @nestjs/common. Primarily the HttpCode decorator and the content-type header from a Header decorator. This will allow to not obscure the routing logic by documentation (of course you can always override or extend this with @nestjs/swagger decorators if you need to). The additional benefit is a single source of truth because technically you can write different things at the HttpCode and the ApiResponse decorators and you won't get an IDE warning.

**Comment by kamilmysliwiec** [comment]
> Primarily the HttpCode decorator and the content-type header from a Header decorator.

We are already using the `HttpCode` metadata with NestJS Swagger Plugin. https://docs.nestjs.com/openapi/cli-plugin
There are no plans to read `Header` related metadata
