### ISSUE TITLE
lots of warnings on install, mainly deprecated packages

### ISSUE THREAD

**Issue by classbasics** [nestjs/nest#5260]
## Current behavior
C:\Users\selvy\WebstormProjects\ETS3>npm i -g @nestjs/cli
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
C:\Users\selvy\AppData\Roaming\npm\nest -> C:\Users\selvy\AppData\Roaming\npm\node_modules\@nestjs\cli\bin\nest.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\@nestjs\cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.7.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\@nestjs\cli\node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @nestjs/cli@7.4.1
added 23 packages from 15 contributors, removed 19 packages, updated 54 packages and moved 19 packages in 58.858s

C:\Users\selvy\WebstormProjects\ETS3>nest --version
7.4.1

C:\Users\selvy\WebstormProjects\ETS3>node --version
v14.7.0

## Input Code

```ts
const your = (code) => here;
```

## Expected behavior
Expected no warnings/automatic upgrade

## Possible Solution
update dependencies

## Environment
npm  6.14.5
<pre><code>
Nest version:7.4.1
 
For Tooling issues:
- Node version: 14.5.0
- Platform:  Windows 10 Pro

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
You can ignore all these warnings. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by rabbishuki** [comment]
@kamilmysliwiec Are you sure?
It seems to be getting worse.

![image](https://user-images.githubusercontent.com/24904197/96706090-cb35e700-139e-11eb-8e9c-6ec35f405476.png)

**Comment by erichstark** [comment]
Now the v14 is default LTS, chokidar should be upgraded to higher version.
