### ISSUE TITLE
Sending Files

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#5263]
## Feature Request

I didn't see any old/closed issues referring to supporting sending files other than support requests that were directed towards [Discord](https://discord.gg/nestjs). 

I'd like to see Nest support sending files out of the box, by making a check in the `reply` method of the `ExpressAdapter` and `FastifyAdapter` and using the proper method accordingly (it looked like Fastify can actually handle this under its hood, so we'd just need to support it with Express.

## Is your feature request related to a problem? Please describe.

Not _really_ a problem, but sending files is somewhat common, and having to use `@Res()` to do it is a major buzzkill for me in the Nest world. Losing the use of post-request interceptor functionality is really annoying, especially when it comes to logging.

## Describe the solution you'd like

I'd like to see Nest support the returning of a `Buffer` or a `stream` and calling the appropriate method from Express `stream.pipe(res)` or Fastify `reply.send(stream)` to send the file back successfully.

## Teachability, Documentation, Adoption, Migration Strategy

Add to the docs that sending files is supported. Shouldn't need much more teachability, and it shouldn't cause any breaking changes.

## What is the motivation / use case for changing the behavior?

Sending files 📁 because there's definitely a use case for that.

I'd be more than happy to get to work on this and add it in, but I'd love to hear some feedback first.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this? :)

**Comment by jmcdo29** [comment]
You bet! I'll see what I can have by the end of the weekend

**Comment by kamilmysliwiec** [comment]
Let's track this in a single place, here https://github.com/nestjs/nest/pull/5278
