### ISSUE TITLE
ValidationPipe in WebsocketGateway returns Internal Server Error

### ISSUE THREAD

**Issue by kkoomen** [nestjs/nest#5267]
## Bug Report

Note: I created an issue because I experience this issue, but it was already properly described by someone else on StackOverflow, see [here](https://stackoverflow.com/questions/60749135/nestjs-validationpipe-in-websocketgateway-returns-internal-server-error).

I'm trying to add some validation to my WebSocketGateway in NestJS. Here's the code:

```ts
// MessageDTO

import { IsNotEmpty, MinLength } from 'class-validator';

export class MessageDTO {
  @IsNotEmpty()
  username: string;

  @IsNotEmpty()
  @MinLength(10)
  text: string;
}
```

```ts
// Gateway

import { ValidationPipe, UsePipes } from '@nestjs/common';
import { MessageBody, SubscribeMessage, WebSocketGateway, WsResponse } from '@nestjs/websockets';
import { MessageService } from './message/message.service';
import { MessageDTO } from './message/message.dto';
import { Message } from './message/message.entity';

@WebSocketGateway()
export class AppGateway {
  constructor(private readonly messageService: MessageService) {}

  @UsePipes(new ValidationPipe())
  @SubscribeMessage('message')
  async handleMessage(@MessageBody() dto: MessageDTO): Promise<WsResponse<Message>> {
    const message = await this.messageService.saveMessage(dto);
    return { event: 'message', data: message };
  }
}
```

Now, when I try to send a message that doesn't meet validation rules, it errors out, but the client always receives `{ status: 'error', message: 'Internal server error'}`. Also, Nest logs the error to the console which should not happen:

```
Error: Bad Request Exception
    at ValidationPipe.exceptionFactory (/usr/src/app/node_modules/@nestjs/common/pipes/validation.pipe.js:78:20)
    at ValidationPipe.transform (/usr/src/app/node_modules/@nestjs/common/pipes/validation.pipe.js:50:24)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async resolveParamValue (/usr/src/app/node_modules/@nestjs/websockets/context/ws-context-creator.js:104:31)
    at async Promise.all (index 0)
    at async pipesFn (/usr/src/app/node_modules/@nestjs/websockets/context/ws-context-creator.js:106:13)
    at async /usr/src/app/node_modules/@nestjs/websockets/context/ws-context-creator.js:41:17
    at async AppGateway.<anonymous> (/usr/src/app/node_modules/@nestjs/websockets/context/ws-proxy.js:11:32)
    at async WebSocketsController.pickResult (/usr/src/app/node_modules/@nestjs/websockets/web-sockets-controller.js:85:24)
```

## Current behavior

Throws an error service and client-side, but incorrectly.

## Expected behavior

Front-end should have the error returned in the `ack` callback.

## Environment

<pre><code>Nest version: 7.4.2
Platform: MacOS
</code></pre>

**Comment by jmcdo29** [comment]
[`BadRequestException`](https://github.com/nestjs/nest/blob/master/packages/common/exceptions/bad-request.exception.ts) is a child class of [`HttpException`](https://github.com/nestjs/nest/blob/master/packages/common/exceptions/http.exception.ts). Nest's default [exception handler for websockets](https://github.com/nestjs/nest/blob/master/packages/websockets/exceptions/base-ws-exception-filter.ts#L19) checks to see if the caught exception is an `instanceof WsException` and if not returns an unknown exception.

To get around this, you can implement a filter that catches `BadRequestException` and transforms it to an appropriate `WsException` before having Nest's exception filter handle the exception from there.

```typescript
@Catch(BadRequestException)
export class BadRequestTransformationFilter extends BaseWsExceptionFilter {
  catch(exception: BadRequestException, host: ArgumentHost) {
    const properError = new WsException(exception.getResponse());
    super.catch(properException, host);
  }
}
```

**Comment by kkoomen** [comment]
After debugging, I came to the same conclusion, but I actually catch the `HttpException` just for the `ws` context.

**Comment by kkoomen** [comment]
But.... is this what we want? Is the current logic normal? because it seems odd to me.

**Comment by omidh28** [comment]
Agreed, And it is not mentioned in documentation.

**Comment by jbrandao2807** [comment]
Any news on this?

**Comment by jmcdo29** [comment]
The documentation still needs to be updated to mention that this is the error thrown by default. You can change the error type though by making use of the `exceptionFactory` property of the `ValidationPipe`, or you can [follow the advice of my comment above](https://github.com/nestjs/nest/issues/5267#issuecomment-673498998)
