### ISSUE TITLE
Subscription naming convention breaks ResolveField

### ISSUE THREAD

**Issue by WillSquire** [nestjs/nest#5272]
## Current behavior
This took the best part of a day to figure out and drove me to question everything, but naming a GraphQL model `Subscription` prevents `ResolveField` in the resolver to fire.

## Input Code
Given the following model and resolver:
```ts
// test.model.ts
import { Field, ObjectType } from '@nestjs/graphql'
import { Node } from '../graphql/node.model'

@ObjectType()
export class Test extends Node {
  @Field(() => String)
  id!: string

  @Field(() => String)
  item!: string
}
```

```ts
// test.resolver.ts
import { UseGuards } from '@nestjs/common'
import { Query, ResolveField, Resolver } from '@nestjs/graphql'
import { GqlAuthGuard } from '../auth/graphql.guard'
import { Test } from './test.model'

@Resolver(() => Test)
export class TestResolver {
  @Query(() => [Test])
  @UseGuards(GqlAuthGuard)
  async currentTest() {
    return { id: 'abc' }
  }

  @ResolveField()
  @UseGuards(GqlAuthGuard)
  async item() {
    return '123'
  }
}
```

When these classes are renamed to `Subscription` and `SubscriptionResolver` (respectively), the `ResolveField` functions do not fire.

## Expected behavior
For naming convention not to have any effect (or worst case scenario, be extremely well documented with bright light, bells and whistles plaster over the place and throw an error if trying to use).

## Possible Solution
Ditto

## Environment

<pre><code>
Nest version:
"@nestjs/common": "^7.0.9"
"@nestjs/core": "^7.0.9"
"@nestjs/graphql": "^7.3.7"
"@nestjs/jwt": "^7.0.0"
"@nestjs/passport": "^7.0.0"
"@nestjs/platform-express": "^7.0.9"
"@nestjs/typeorm": "^7.0.0"
</code></pre>

**Comment by jmcdo29** [comment]
This is being tracked [here](https://github.com/nestjs/graphql/issues/934)
