### ISSUE TITLE
Metatype is not a constructor     at Injector.instantiateClass 

### ISSUE THREAD

**Issue by enmanuel97** [nestjs/nest#5277]
Hi, I'm following an udemy tutorial and we are building an API but I'm having this error I do not know what is the problem, can someone help me?

![image](https://user-images.githubusercontent.com/22060566/90318716-5f4b8400-df00-11ea-983e-ea182f9e68af.png)

I think that the problem is in this part: 
![image](https://user-images.githubusercontent.com/22060566/90318764-afc2e180-df00-11ea-9b4b-190e2ad6a7fd.png)

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for help requests. We are using GitHub to track Bug Reports, Regressions, and Feature Requests.
