### ISSUE TITLE
FastifyError: Unsupported Media Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by underfisk** [nestjs/nest#5279]
## Current behavior
After upgrading the fastify adapter to the latest version (7.4.2) it stopped working with POST requests, it simply throws the following error: 
"Unsupported Media Type: application/x-www-form-urlencoded +54073ms | FastifyError: Unsupported Media Type: application/x-www-form-urlencoded"
I'm also using the following plugins:
```
"fastify-compress": "^3.3.0",
"fastify-cookie": "^4.0.2",
"fastify-multipart": "^2.0.3",
"fastify-rate-limit": "^4.0.2",
"fastify-swagger": "^3.3.0",
```

## Input Code
Simply create a new project, use the latest adapter, create a post handler and the error surges

## Expected behavior
It should parse as previously, right now if complaints about formbody plugin but if i add the plugin it also throws error saying its already registered. Now the error is internal and out of control in my side

## Environment

<pre><code>
Nest version: 7.4.2 (latest)

 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Linux

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Hmm, I'm not able to reproduce this.
```sh
$ nest new fastify-form-encoded
$ cd fastify-form-encoded
```
Add in `FastifyAdapter()` instead of the default `ExpressAdapter`.
Add a Post method, it can just return `this.appService.getHello()` inside of `AppController`.
```sh
curl http://localhost:3000 -d 'hello=world'
```
See the response without an error.

Dependencies
```
▶ yarn list --depth=0 | grep @nestjs
├─ @nestjs/cli@7.4.1
├─ @nestjs/common@7.4.2
├─ @nestjs/core@7.4.2
├─ @nestjs/platform-express@7.4.2
├─ @nestjs/platform-fastify@7.4.2
├─ @nestjs/schematics@7.0.1
├─ @nestjs/testing@7.4.2
```
(I was lazy and didn't remove platform-express. Shouldn't change anything).

I'll make a git repo if you'd like.

**Comment by underfisk** [comment]
@jmcdo29 Thanks for sharing the reproduction but what I find strange is that it complains about my project which is kinda weird, even if I disable the fastify plugins it still persists the same error and my grep is different tho

> ├─ @nestjs/platform-fastify@7.4.2
├─ fastify-compress@3.3.0
├─ fastify-cookie@4.0.2
├─ fastify-cors@4.1.0
├─ fastify-error@0.2.0
├─ fastify-formbody@4.0.3
├─ fastify-multipart@2.0.3
├─ fastify-plugin@2.3.0
├─ fastify-rate-limit@4.0.2
├─ fastify-static@3.2.0
├─ fastify-swagger@3.3.0
├─ fastify-warning@0.2.0
├─ fastify@3.2.0

The stack when i perform a simple CURL is the following:

```
backend  | FastifyError: Unsupported Media Type: application/x-www-form-urlencoded
backend  |     at ContentTypeParser.run (/backend/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/contentTypeParser.js:95:16)
backend  |     at handleRequest (/backend/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/handleRequest.js:35:39)
backend  |     at next (/backend/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/route.js:379:7)
backend  |     at Object.preParsing (/backend/node_modules/fastify-compress/index.js:282:14)
backend  |     at next (/backend/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/route.js:389:16)
backend  |     at preParsingHookRunner (/backend/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/route.js:405:3)
backend  |     at runPreParsing (/backend/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/route.js:356:5)
backend  |     at next (/backend/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/hooks.js:155:7)
backend  |     at onIncr (/backend/node_modules/fastify-rate-limit/index.js:158:9)
backend  |     at /backend/node_modules/fastify-rate-limit/store/RedisStore.js:27:7
backend  |     at tryCatcher (/backend/node_modules/standard-as-callback/built/utils.js:11:23)
backend  |     at /backend/node_modules/standard-as-callback/built/index.js:19:49
backend  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
As you can see it ends in content type parser, i don't have any way of intercept it and its fully managed via nest http adapter when it binds formbody

**Comment by jmcdo29** [comment]
I'll remove my `yarn.lock` and reinstall everything, just to verify. In the meantime, can you create a minimum reproduction that illustrates this issue? Is there a chance another plugin is somehow causing the issue? Looks like possibly `fastify-rate-limit` as it is in the stack trace as well.

**Comment by underfisk** [comment]
@jmcdo29 I though also of that but i will try to provide you a repo to reproduced, meanwhile i tested your reproduction and it works fine but there wasn't things that i have like cors which might or not interfere with fastify plugin system

**Comment by jmcdo29** [comment]
> backend  |     at onIncr (/backend/node_modules/fastify-rate-limit/index.js:158:9)
backend  |     at /backend/node_modules/fastify-rate-limit/store/RedisStore.js:27:7

This makes me think it's a `fastify-rate-limit` issue

**Comment by underfisk** [comment]
@jmcdo29 Manage to find the issue, the issue with related with nest swagger module for fastify

**Comment by underfisk** [comment]
```
export const registerSwagger = (app: NestFastifyApplication) => {
	//Register swagger
	const options = new DocumentBuilder()
		.setTitle("test")
		.setDescription(`api`)
		.setVersion('2.0')
		.addBearerAuth()
		.build()

	const document = SwaggerModule.createDocument(app, options, {
		// include: [ApiModule]
	})

	SwaggerModule.setup('swagger', app, document)
}
```

Try this on your fastify and let me know

**Comment by jmcdo29** [comment]
Swagger comes up without a problem, can send values in with `x-www-form-urlencoded` and there's no errors showing up in my console.

**Comment by underfisk** [comment]
@jmcdo29 If i enable swagger on my app, it throws the error but disabling it its okay

```
├─ @nestjs/swagger@4.5.12
├─ @types/swagger-schema-official@2.0.21
├─ fastify-swagger@3.3.0

```

**Comment by jmcdo29** [comment]
:shrug: I was able to start up the app, make a request from CURL and from Swagger and got successful responses on both sides. I can't really tell what's going on, and without a reproduction, I probably won't be able to properly debug it either.

**Comment by underfisk** [comment]
@jmcdo29 I understand, i'll see if i can get you a repo to test but this is kinda hard to split into a new app due to the whole business logic

**Comment by mohd-akram** [comment]
I had filed this issue at nestjs/swagger#891 with a repo.

**Comment by underfisk** [comment]
> I had filed this issue at [nestjs/swagger#891](https://github.com/nestjs/swagger/issues/891) with a repo.

Thanks mate

**Comment by kamilmysliwiec** [comment]
Lets track this here https://github.com/nestjs/swagger/issues/891
