### ISSUE TITLE
Add info() method to Logger/LoggerService

### ISSUE THREAD

**Issue by mohd-akram** [nestjs/nest#5281]
## Is your feature request related to a problem? Please describe.
Many loggers have an `info()` method and having it in the default Logger/LoggerService allows easily switching between different kinds of loggers.

## Describe the solution you'd like
Add an `info()` method to LoggerService and Logger.

## Teachability, Documentation, Adoption, Migration Strategy
--

## What is the motivation / use case for changing the behavior?
Allow using different kinds of loggers with the same interface. `info()` is also a more descriptive name than `log()`.

**Comment by jmcdo29** [comment]
In most logging frameworks, isn't `info` the same thing as `log`? And what's keeping you from extending the `Logger` and adding in an `info` method yourself?

**Comment by mohd-akram** [comment]
Well if you look at [winston](https://github.com/winstonjs/winston) the `log` method is different there.

> And what's keeping you from extending the Logger and adding in an info method yourself?

Nothing really, but I guess you could say that about anything :D It's more configuration for what should be a default, IMO. I think basically every logging framework has an `info` method, so it's a notable omission.

**Comment by jmcdo29** [comment]
And if you look at the [Ogma](https://github.com/jmcdo29/ogma/blob/master/packages/logger/src/logger/ogma.ts#L26) logger (Disclaimer, I'm the author of it), you'll see that `log` and `info` are the same method, with different names. [Pino](https://github.com/pinojs/pino/blob/master/docs/api.md#logger) doesn't have a`log` method, but it does have `info`. Same thing with [Bunyan](https://github.com/trentm/node-bunyan#levels)

**Comment by mohd-akram** [comment]
Sounds like all the more reason to add an `info` method! :D

**Comment by kamilmysliwiec** [comment]
Can you please share a use case in which using `info` would be preferable to `log`?

**Comment by gilzarfati** [comment]
To me, having the same method with 2 different names sounds confusing and redundant. When you code and the auto complete suggests you both log and info, first you get confused, and then you just pick one cause you don't see the difference, and with time and multiple developers, the logging becomes inconsistent.

**Comment by kamilmysliwiec** [comment]
Fully agree on this with @gilzarfati

**Comment by mohd-akram** [comment]
It wouldn't be the same method. They'd be two different methods, with an additional log level called `info`.

**Comment by kamilmysliwiec** [comment]
You have `log` log level for this.
