### ISSUE TITLE
Nest start is using the wrong folder

### ISSUE THREAD

**Issue by talesmgodois** [nestjs/nest#5287]
## Current behavior
SO, this is really weird, and not sure if it's easy to simulate. I am running my dev server using `nest start --watch` . I got the following log:

```
 yarn dev
yarn run v1.22.4
$ nodemon src/server.ts
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/talesmarinho/projetos/heroku-scheduler/pinger/src/**/*
[nodemon] starting `sucrase-node src/server.ts src/server.ts`
[nodemon] restarting due to changes...

 pwd
**/Users/talesmarinho/projetos/heroku-scheduler/pinger2**

```

## Expected behavior
Run the server at the right folder

## Possible Solution

It maybe something regarding webpack cache

## Environment
<pre><code>
Nest version: 7.4.1
Node version: v12.16.2
 
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
