### ISSUE TITLE
Is it possible to inject an array of similar services?

### ISSUE THREAD

**Issue by iandrc** [nestjs/nest#5288]
Let's say I have the following service:
```
export const QB: FB = {
  provide: QUERY_BUILDER,
  scope: Scope.TRANSIENT,
  useFactory: () => new QueryBuilder(params),
};
```

And I wanna use inject it into `@Controller`.  Smth like this:
```
@Inject(QUERY_BUILDER) private requestBuilder: RequestBuilder
```

Unfortunately, I didn't find any way to inject an array of `QueryBuilders`. Is it even possible?

**P.S.** Sorry for asking here, I use neither of your resources

**P.P.S** I guess it could be somehow related to https://github.com/nestjs/nest/issues/4786 yet I'm not 100% sure

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
