### ISSUE TITLE
 Does Nest currently support server-side rendering?

### ISSUE THREAD

**Issue by JunYanchan** [nestjs/nest#5290]
At present, we want to use Nest in the middle layer of our project. If server-side rendering is required in the page, what if we use Nest to write?

**Comment by kamilmysliwiec** [comment]
Sure. Nest supports everything that express/fastify (that are used under the hood) support. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
