### ISSUE TITLE
e2e testing not working with fastify V3

### ISSUE THREAD

**Issue by Summon528** [nestjs/nest#5308]
## Bug Report
Original issue here https://github.com/fastify/help/issues/228. While the workaround in that thread works, it leaves open handles and has to hardcode port number. Also, they seem to conclude that something in `app.init` has to be changed.

## Current behavior

```
    TypeError: Cannot read property 'length' of undefined

      at next (../node_modules/fastify/lib/route.js:374:32)
      at preParsingHookRunner (../node_modules/fastify/lib/route.js:405:3)
      at runPreParsing (../node_modules/fastify/lib/route.js:356:5)
      at Object.routeHandler [as handler] (../node_modules/fastify/lib/route.js:334:7)
      at Router.lookup (../node_modules/find-my-way/index.js:356:14)
```
## Input Code

main.ts
```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  await app.listen(3000);
}
bootstrap();
```

app.e2e-spec.ts
```ts
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as request from 'supertest';
import { AppModule } from './../src/app.module';
import { FastifyAdapter } from '@nestjs/platform-fastify';

describe('AppController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication(new FastifyAdapter());
    await app.init();
  });

  it('/ (GET)', () => {
    return request(app.getHttpServer())
      .get('/')
      .expect(200)
      .expect('Hello World!');
  });
});
```

## Expected behavior
Test pass. (It works as expected if using fastify V2 and @nestjs/platform-fastify@7.2)

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: 7.4.2
- Platform:   Ubuntu

Others:

</code></pre>

**Comment by YuriiKovalenko** [comment]
@Summon528 have same problem. Pls clarify your solution.

**Comment by Summon528** [comment]
You will want to use fasitify's [`inject`](https://www.fastify.io/docs/latest/Testing/) and drop `supertest` altogether

**Comment by sramteare-chwy** [comment]
@Summon528 Please share an example here. I have similar problem, using fastify.inject is not recognized on INestApplication
```Property 'inject' does not exist on type 'INestApplication'.```

**Comment by jmcdo29** [comment]
Use `FastifyNestApplication` instead of `INestApplication`. You can cast this type as necessary. [You can see an example here](https://github.com/jmcdo29/nest-cookies/blob/main/test/fastify.e2e-spec.ts#L47)
