### ISSUE TITLE
Export other cache constant token as public api

### ISSUE THREAD

**Issue by mehdi-sh-hm** [nestjs/nest#5335]
# Feature Request
## Scenario description
I recently added an interceptor to my code that determines what the value of cache ttl will be based on request parameters, kind of a conditional ttl. 

## Problem description
When I want to define ttl as metadata on handler we need constant token of `CACHE_TTL_METADATA` and it is private right now.

## Current solution
```
intercept(ctx: ExecutionContext, next: CallHandler) {
    const body = ...;
    if (!body.term) {
      Reflect.defineMetadata('cache_module:cache_ttl' /** (Problem) cache constant in @nest/common */, 2000, ctx.getHandler());
    } // else will be default
    return super.intercept(ctx, next);
}
```
But the problem with this solution is that any change in the content of this token will cause the code to crash.

## Possible solution
Please just export them as public api 🙏😊

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
