### ISSUE TITLE
When using regex in allowed origins, all origin matches

### ISSUE THREAD

**Issue by david-espinosa** [nestjs/nest#5336]
## Bug Report
When setting the allowed origins for cors and using regex, all origin are matched.

## Current behavior

After setting a regex for allowed origins, any value in the request header Origin is valid, and is included in the response header  access-control-allow-origin.

## Input Code

```ts
nestApp.enableCors({origin: /\foo\.fiu\.com$/, credentials: true});
```

## Expected behavior

Only origins matching the provided regex are accepted.

## Environment

<pre><code>
Nest version: 7.1.3

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Nest passes the options from `enableCors` to [cors](https://github.com/expressjs/cors) or [fasitfy-cors](https://github.com/fastify/fastify-cors) depending on your adapter. No modifications are made, so this should be reported to the underlying libraries.

**Comment by tidx1995** [comment]
It's not error of cors or fastify-cors.
After i change 
`app.enableCors({ origin: "*" })` 
to 
`
const cors = require('fastify-cors');
adapter.register(cors)
`

It's work normally
