### ISSUE TITLE
When decorator applied to controller body is ignored form Swagger

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#5337]
## Current behavior
When applying a decorator to a controller method, Swagger ignores the body type of the the @Body.  
The @Body documentation is missing from Swagger but the logic behind the rateLimit decorator (which is my own decorator - not a nestJS decorator https://github.com/vlio20/utils-decorators#ratelimit-method) is working as expected. 
![Swagger](https://i.ibb.co/34rDC4x/swagger.png)

## Input Code

```ts
import {Body, Controller, HttpException, HttpStatus, Post} from '@nestjs/common';
import {rateLimit} from 'utils-decorators';

  @Post()
  @rateLimit({
    timeSpanMs: 60 * 60 * 1000,
    allowedCalls: 3,
    exceedHandler: () => {
      throw new HttpException('rate-limit acceded', HttpStatus.TOO_MANY_REQUESTS);
    },
  })
  createAccount(@Body() createDto: CreateAccountDto): Promise<CreatedAccountDto> {
    return this.accountApi.createAccount(createDto);
  }
```

## Expected behavior
I would expect the documentation to show the dto attributes.

<pre><code>
Nest version: 7.4.2

**Comment by jmcdo29** [comment]
Is `CreateAccountDto` decorated with the Swagger decorators? Can you provide a minimum reproduction?

**Comment by vlio20** [comment]
Yes, by removing the rateLimit decorator all the fields of the dto are visible in swagger.

@jmcdo29 in would be happy to show a reproduction. Is there any available repo from which I can fork and add my needed changes?

**Comment by jmcdo29** [comment]
You can copy any of the sample, or use the [typescript-starter](https://github.com/nestjs/typescript-starter) to get going

**Comment by vlio20** [comment]
It's a duplicate #217
