### ISSUE TITLE
Generic type 'FastifyRequest<RouteGeneric, RawServer, RawRequest, HttpRequest>' requires 4 type argument(s).

### ISSUE THREAD

**Issue by VitaliiLysak** [nestjs/nest#5340]
## Environment

<pre><code>
"@nestjs/platform-fastify": "^7.4.2",
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by VitaliiLysak** [comment]
@kamilmysliwiec Sorry
Error happens at the "npm start" stage
I just updated platform-fastify to 7.4.2

**Comment by kamilmysliwiec** [comment]
We can't help you without the reproduction repository

**Comment by VitaliiLysak** [comment]
@kamilmysliwiec thank you
I found the issue

**Comment by rghorbani** [comment]
@VitaliiLysak How did you fix the problem?

**Comment by Dotunj** [comment]
@VitaliiLysak How were you able to fix this issue?
