### ISSUE TITLE
API Call not responding after @Res declaration and TCP microservice connection

### ISSUE THREAD

**Issue by Root-Control** [nestjs/nest#5345]
## Current behavior
Testing "n" cases i have seen the API stucks and didn't sent response to UI/Postman and the.
This weird behavior happens when you try to connect to a microservice TCP based in a pattern.
## Input Code

Not working example
```ts
@Post('dostuff')
doStuff(@Req() req, @Res() res) {
	return this.client.send<number>({ cmd: 'some-pattern' }, [1, 2, 3, 4, 5, 6, 7, 8]);
}
```
Working example
```ts
@Post('dostuff')
doStuff(@Req() req) {
	return this.client.send<number>({ cmd: 'some-pattern' }, [1, 2, 3, 4, 5, 6, 7, 8]);
}
```
## Expected behavior
The parameters in the method shouldn't stuck the lifecycle.
## Possible Solution
Removing @Res() res -> this parameter is crashing the entire process
## Environment

<pre><code>
Nest version: 7.0.0

 
For Tooling issues:
- Node version:  14.8.0 
- Platform:  Win 10

Others:
I know this issue can be solved, but is very strange, that's why i delayed at least 3hs debugging, I hope it doesn't happen to anyone else

**Comment by jmcdo29** [comment]
[This is the documented](https://docs.nestjs.com/controllers) and expected behavior. [See more specifics here](https://docs.nestjs.com/controllers#appendix-library-specific-approach)

**Comment by Root-Control** [comment]
> [This is the documented](https://docs.nestjs.com/controllers) and expected behavior. [See more specifics here](https://docs.nestjs.com/controllers#appendix-library-specific-approach)

Interesting , thank you! now i need to be carefull :D
