### ISSUE TITLE
missing await

### ISSUE THREAD

**Issue by stavalfi** [nestjs/nest#5347]
https://github.com/nestjs/nest/blob/e70196b8c20dd597fe98f4d3daeda588af0e832f/packages/core/injector/container.ts#L97

you need to wait for the promises to finish or it may cause unhandaled promise rejection and race conditions.

**Comment by kamilmysliwiec** [comment]
Great catch! Thanks. Lets track this here https://github.com/nestjs/nest/pull/5348
