### ISSUE TITLE
Don't change table if already exists

### ISSUE THREAD

**Issue by rsofista** [nestjs/nest#5354]
## Bug Report
The application is dropping fields and creating sequences when they already exist.

*if this is a problem with typeorm then I will make a bug report there*

## Current behavior
I was following this tutorial https://www.techiediaries.com/nestjs-tutorial-rest-api-crud/ on how to create a simple CRUD when I decided to use a preexisting database and table to test;
So I mapped one table with using only 3 fields and when I started the server it failed with the error:
<pre><code>
 ddpc[11:14:52 AM] Starting compilation in watch mode...

[11:14:59 AM] Found 0 errors. Watching for file changes.

[Nest] 2105   - 08/30/2020, 11:15:00 AM   [NestFactory] Starting Nest application...
[Nest] 2105   - 08/30/2020, 11:15:00 AM   [InstanceLoader] TypeOrmModule dependencies initialized +74ms
[Nest] 2105   - 08/30/2020, 11:15:00 AM   [InstanceLoader] AppModule dependencies initialized +1ms
query: START TRANSACTION
query: SELECT * FROM current_schema()
query: SELECT * FROM "information_schema"."tables" WHERE ("table_schema" = 'public' AND "table_name" = 'dpco_de_para_comando')
query: SELECT *, ('"' || "udt_schema" || '"."' || "udt_name" || '"')::"regtype" AS "regtype" FROM "information_schema"."columns" WHERE ("table_schema" = 'public' AND "table_name" = 'dpco_de_para_comando')
query: SELECT "ns"."nspname" AS "table_schema", "t"."relname" AS "table_name", "cnst"."conname" AS "constraint_name", pg_get_constraintdef("cnst"."oid") AS "expression", CASE "cnst"."contype" WHEN 'p' THEN 'PRIMARY' WHEN 'u' THEN 'UNIQUE' WHEN 'c' THEN 'CHECK' WHEN 'x' THEN 'EXCLUDE' END AS "constraint_type", "a"."attname" AS "column_name" FROM "pg_constraint" "cnst" INNER JOIN "pg_class" "t" ON "t"."oid" = "cnst"."conrelid" INNER JOIN "pg_namespace" "ns" ON "ns"."oid" = "cnst"."connamespace" LEFT JOIN "pg_attribute" "a" ON "a"."attrelid" = "cnst"."conrelid" AND "a"."attnum" = ANY ("cnst"."conkey") WHERE "t"."relkind" = 'r' AND (("ns"."nspname" = 'public' AND "t"."relname" = 'dpco_de_para_comando'))
query: SELECT "ns"."nspname" AS "table_schema", "t"."relname" AS "table_name", "i"."relname" AS "constraint_name", "a"."attname" AS "column_name", CASE "ix"."indisunique" WHEN 't' THEN 'TRUE' ELSE'FALSE' END AS "is_unique", pg_get_expr("ix"."indpred", "ix"."indrelid") AS "condition", "types"."typname" AS "type_name" FROM "pg_class" "t" INNER JOIN "pg_index" "ix" ON "ix"."indrelid" = "t"."oid" INNER JOIN "pg_attribute" "a" ON "a"."attrelid" = "t"."oid"  AND "a"."attnum" = ANY ("ix"."indkey") INNER JOIN "pg_namespace" "ns" ON "ns"."oid" = "t"."relnamespace" INNER JOIN "pg_class" "i" ON "i"."oid" = "ix"."indexrelid" INNER JOIN "pg_type" "types" ON "types"."oid" = "a"."atttypid" LEFT JOIN "pg_constraint" "cnst" ON "cnst"."conname" = "i"."relname" WHERE "t"."relkind" = 'r' AND "cnst"."contype" IS NULL AND (("ns"."nspname" = 'public' AND "t"."relname" = 'dpco_de_para_comando'))
query: SELECT "con"."conname" AS "constraint_name", "con"."nspname" AS "table_schema", "con"."relname" AS "table_name", "att2"."attname" AS "column_name", "ns"."nspname" AS "referenced_table_schema", "cl"."relname" AS "referenced_table_name", "att"."attname" AS "referenced_column_name", "con"."confdeltype" AS "on_delete", "con"."confupdtype" AS "on_update", "con"."condeferrable" AS "deferrable", "con"."condeferred" AS "deferred" FROM ( SELECT UNNEST ("con1"."conkey") AS "parent", UNNEST ("con1"."confkey") AS "child", "con1"."confrelid", "con1"."conrelid", "con1"."conname", "con1"."contype", "ns"."nspname", "cl"."relname", "con1"."condeferrable", CASE WHEN "con1"."condeferred" THEN 'INITIALLY DEFERRED' ELSE 'INITIALLY IMMEDIATE' END as condeferred, CASE "con1"."confdeltype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confdeltype", CASE "con1"."confupdtype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confupdtype" FROM "pg_class" "cl" INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid" INNER JOIN "pg_constraint" "con1" ON "con1"."conrelid" = "cl"."oid" WHERE "con1"."contype" = 'f' AND (("ns"."nspname" = 'public' AND "cl"."relname" = 'dpco_de_para_comando')) ) "con" INNER JOIN "pg_attribute" "att" ON "att"."attrelid" = "con"."confrelid" AND "att"."attnum" = "con"."child" INNER JOIN "pg_class" "cl" ON "cl"."oid" = "con"."confrelid" INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid" INNER JOIN "pg_attribute" "att2" ON "att2"."attrelid" = "con"."conrelid" AND "att2"."attnum" = "con"."parent"
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'typeorm_metadata'
query: ALTER TABLE "dpco_de_para_comando" DROP COLUMN "dpco_data_cadastro"
query: CREATE SEQUENCE "dpco_de_para_comando_dpco_codigo_seq" OWNED BY "dpco_de_para_comando"."dpco_codigo"
query: ALTER TABLE "dpco_de_para_comando" ALTER COLUMN "dpco_codigo" SET DEFAULT nextval('dpco_de_para_comando_dpco_codigo_seq')
query: ALTER TABLE "dpco_de_para_comando" ALTER COLUMN "dpco_codigo" DROP DEFAULT
query: ALTER TABLE "dpco_de_para_comando" DROP COLUMN "dpco_descricao"
query: ALTER TABLE "dpco_de_para_comando" ADD "dpco_descricao" character varying NOT NULL
query failed: ALTER TABLE "dpco_de_para_comando" ADD "dpco_descricao" character varying NOT NULL
error: error: column "dpco_descricao" contains null values
    at Parser.parseErrorMessage (/mnt/d/dev/node/nest-rest-server/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/mnt/d/dev/node/nest-rest-server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/mnt/d/dev/node/nest-rest-server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/mnt/d/dev/node/nest-rest-server/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 100,
  severity: 'ERROR',
  code: '23502',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '3820',
  routine: 'ATRewriteTable'
}
query: ROLLBACK
[Nest] 2105   - 08/30/2020, 11:15:01 AM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +796ms
QueryFailedError: column "dpco_descricao" contains null values
    at new QueryFailedError (/mnt/d/dev/node/nest-rest-server/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/mnt/d/dev/node/nest-rest-server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/mnt/d/dev/node/nest-rest-server/node_modules/pg/lib/query.js:139:19)
    at Client._handleErrorMessage (/mnt/d/dev/node/nest-rest-server/node_modules/pg/lib/client.js:326:17)
    at Connection.emit (events.js:315:20)
    at /mnt/d/dev/node/nest-rest-server/node_modules/pg/lib/connection.js:109:12
    at Parser.parse (/mnt/d/dev/node/nest-rest-server/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/mnt/d/dev/node/nest-rest-server/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
</code></pre>

This taught me to never makes tests on production again... luckily for me it rolled back.

The weird part are these lines:
<pre><code class="sql">ALTER TABLE "dpco_de_para_comando" DROP COLUMN "dpco_data_cadastro";
CREATE SEQUENCE "dpco_de_para_comando_dpco_codigo_seq" OWNED BY "dpco_de_para_comando"."dpco_codigo";
ALTER TABLE "dpco_de_para_comando" ALTER COLUMN "dpco_codigo" SET DEFAULT nextval('dpco_de_para_comando_dpco_codigo_seq');
ALTER TABLE "dpco_de_para_comando" ALTER COLUMN "dpco_codigo" DROP DEFAULT;
ALTER TABLE "dpco_de_para_comando" DROP COLUMN "dpco_descricao";
ALTER TABLE "dpco_de_para_comando" ADD "dpco_descricao" character varying NOT NULL;
</code></pre>

Here are the problems:
* It tried to drop "dpco_data_cadastro" because it wasn't mapped in the entity
* It created a sequence for the primary key, set it as default and drop the default (a little weird, it should be the contrary)
* It droped and recreated "dpco_descricao", I don't know why since the declaration is: "descricao?: string;"

## Expected behavior
It shouldn't drop database fields that aren't mapped in the entity. Some tables may have fields that aren't supposed to be "CRUD-able" and may serve some other obscure purpose the app isn't supposed to know.
In my case all sequences have a naming convention that's different from the database default (postgres in this instance), since the app doesn't even use the sequence name on inserts then it shouldn't try to create one.
The whole drop and recreate looks unnecessary.

## Possible Solution
So nothing major is changed, I suggest going for the "if the table already exists, then skip everything regarding the table creation".

## Environment
<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 12.18.3
- Platform:  Ubuntu (on Windows 10)
</code></pre>

**Comment by jmcdo29** [comment]
This probably comes from having `synchronize: true`. It's a TypeORM functionality and should be reported to them

**Comment by rsofista** [comment]
Copied over to typeorm repo https://github.com/typeorm/typeorm/issues/6641

**Comment by pabloweinx** [comment]
> This probably comes from having `synchronize: true`. It's a TypeORM functionality and should be reported to them

You saved my life. Thanksss!
