### ISSUE TITLE
Calling $method_definitions and $method_names from gRPC client results in an error

### ISSUE THREAD

**Issue by genericapplesauce** [nestjs/nest#5371]
## Current behavior
When trying to call $method_definitions and $method_names, I get the error `TypeError: Function.prototype.apply was called on #<Object>, which is a object and not a function` thrown at [this line](https://github.com/nestjs/nest/blob/v7.4.4/packages/microservices/client/client-grpc.ts#L243).

## Input Code
I have a `getClient()` method that simply exposes all of the gRPC calls available
```ts
@Injectable()
export class myClient implements OnModuleInit {
  @Client(grpcClientOptions) private readonly client: ClientGrpc;
  private myService: MyService;

  onModuleInit(): void {
    this.myService = this.client.getService<MyService>('MyService');
  }

  getClient(): MyService {
    return this.myService;
  }
}
```

On the consumer side, if I print the returned client, I get an object of my gRPC method (`findById`) along with $method_definitions and $method_names
```ts
@Controller()
export class ExampleController {
    constructor(private readonly myClient: MyClient) {}
    
    test() {
        console.log(this.wrappedClient.getClient());
        /*output:
        { '$method_definitions': [Function],
            '$method_names': [Function],
            findById: [Function] } */
    }
}
```

`findById` is a function that returns an Observable that behaves correctly. `$method_definitions` and `$method_names` return Observables, that when subscribed, result in `TypeError: Function.prototype.apply was called on #<Object>, which is a object and not a function`

## Expected behavior
I'm guessing these aren't really supposed to be called explicitly by the consumer, but I was searching for some amount of introspection into method names which is how I noticed this. I'm not sure what the expected behavior _should_ be, but I know $method_names contains something like this
```ts
    { '/examplePackage.MyService/FindById': 'FindById' }
```
and $method_definitions
```ts
{ FindById:
   { path: '/examplePackage.MyService/FindById',
     requestStream: false,
     responseStream: false,
     requestSerialize: [Function: serialize],
     requestDeserialize: [Function: deserialize],
     responseSerialize: [Function: serialize],
     responseDeserialize: [Function: deserialize],
     originalName: 'findById',
     requestType:
      { format: 'Protocol Buffer 3 DescriptorProto',
        type: [Object],
        fileDescriptorProtos: [Array] },
     responseType:
      { format: 'Protocol Buffer 3 DescriptorProto',
        type: [Object],
        fileDescriptorProtos: [Array] } }
}
```

## Possible Solution
I believe the error thrown is because of the arg spread in [this line](https://github.com/nestjs/nest/blob/v7.4.4/packages/microservices/client/client-grpc.ts#L243). $method_names and $method_definitions are objects containing metadata about the actual gRPC methods available.

## Environment

<pre><code>
Nest version: 7.4.4
(also tried 6.11.11 and 6.6.0)

 
For Tooling issues:
- Node version: 10.15.3
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by genericapplesauce** [comment]
> Would you like to create a PR for this issue?

I'll give it a try in a couple days. Is making an exception to the method invocation at [line 243](https://github.com/nestjs/nest/blob/v7.4.4/packages/microservices/client/client-grpc.ts#L243) an acceptable solution, given that $method_definitions and $method_names is always generated by grpc when generating a client, or should the fix be a bit more robust?

**Comment by kamilmysliwiec** [comment]
@genericapplesauce it should be fine :)
