### ISSUE TITLE
Error: Nest can't resolve dependencies of the UserService (?). Please make sure that the argument UserRepository at index [0] is available in the AuthModule context.

### ISSUE THREAD

**Issue by abi2810** [nestjs/nest#5372]
## Bug Report
While I run  `npm run start` I'm getting this error

` Nest can't resolve dependencies of the UserService (?). Please make sure that the argument UserRepository at index [0] is available in the AuthModule context.

Potential solutions:
- If UserRepository is a provider, is it part of the current AuthModule?
- If UserRepository is exported from a separate @Module, is that module imported within AuthModule?
  @Module({
    imports: [ /* the Module containing UserRepository */ ]
  })
 +1ms
Error: Nest can't resolve dependencies of the UserService (?). Please make sure that the argument UserRepository at index [0] is available in the AuthModule context.

Potential solutions:
- If UserRepository is a provider, is it part of the current AuthModule?
- If UserRepository is exported from a separate @Module, is that module imported within AuthModule?
  @Module({
    imports: [ /* the Module containing UserRepository */ ]
  })

    at Injector.lookupComponentInParentModules (../node_modules/@nestjs/core/injector/injector.js:191:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
`

## Current behavior

I have created a module and imported necessary services and I don't have any kind of repository. I'm using Modules, Controllers, and Services. And I'm using **sequelize-typescript** and models(not entity).

## Input Code
**auth.module.ts**

`import { Module } from '@nestjs/common';
import { JwtModule } from '@nestjs/jwt';
import { BullModule } from '@nestjs/bull';
import { Queue } from 'bull';
import { PassportModule } from '@nestjs/passport';
import { UsersModule } from '../users/users.module';
import { TutorModule } from '../tutor/tutor.module';
import { AuthService } from './auth.service';
import { JwtStrategy } from './strategies/jwt-strategy';
import { LocalStrategy } from './strategies/local-strategy';
import { AuthController } from './auth.controller';
import { jwtConstants } from './constants';
import { TutorService } from '../tutor/tutor.service';
import { MailService } from '../mail/mail.service';
import { UserService } from '../users/users.service';

@Module({
  imports: [
    PassportModule,
    UsersModule,
    JwtModule.register({
      secret: jwtConstants.secret, //Move it to environment variable
      signOptions: { expiresIn: jwtConstants.expiresIn },
    }),
  ],
  providers: [AuthService,UserService,TutorService,MailService],
  controllers: [AuthController],
  exports: [AuthService]
})
export class AuthModule {}
`

Why it is getting error like this, even I don't use Repository. 
Can anyone help me out?

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for hello questions. We are using GitHub for taking Bug Reports, Regressions, and Feature Requests

**Comment by abi2810** [comment]
> Please use our [Discord](https://discord.gg/nestjs) channel (Support) for hello questions. We are using GitHub for taking Bug Reports, Regressions, and Feature Requests

Okay, Thnaks
