### ISSUE TITLE
EntityMetadataNotFoundError with HMR

### ISSUE THREAD

**Issue by gamingumar** [nestjs/nest#5377]
## Current behavior
When using HMR, upon any changes in file, nest js crashes and I get following error. 
```
EntityMetadataNotFound: No metadata for "User" was found.
```

## Expected behavior
I have followed this guidance with CLI.
https://docs.nestjs.com/recipes/hot-reload

## Environment
I am using TypeORM with Postgres

<pre><code>
Nest version: 7.4.4
Node version: 12.16.3
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by kuangshp** [comment]
How did you solve the same problem

**Comment by gamingumar** [comment]
@kuangshp man that was years ago :P I think I stopped using HMR.

**Comment by iamzzg** [comment]
I had the same problem，because I connected to the database width typeorm in which I set the entities options to “path.join(__dirname,'./entity/**/*.{js,ts}')”.when I set "entities:[User]",this problem was solved immediately.

**Comment by iamzzg** [comment]
> I had the same problem，because I connected to the database width typeorm in which I set the entities options to “path.join(__dirname,'./entity/**/*.{js,ts}')”.when I set "entities:[User]",this problem was solved immediately.

It is stange that the output files compiled into the dist folder by webpack were diffrent between the normal mode and HMR mode.In normal way(non-HMR), the source code will be compiled into javascript files according to the original folder structure.While in HMR way the source code will be compiled into one file named main.js.

**Comment by iamzzg** [comment]
It is stange that the output files compiled into the dist folder by webpack were diffrent between the normal mode and HMR mode.In normal way(non-HMR), the source code will be compiled into javascript files according to the original folder structure.While in HMR way the source code will be compiled into one file named main.js.

**Comment by jmcdo29** [comment]
@iamzzg by "non-HMR" do you mean just compiling with typescript? Because of so then that's just a difference of how typescript and webpack compile, one being just a compiler and the other being a compiler **and** a bundler

**Comment by iamzzg** [comment]
@jmcdo29 "non-HMR" means running nest app without HMR.You can find out that they are different in the dist folder when you run the nest app in HMR and non-HRM.

**Comment by iamzzg** [comment]
![image](https://github.com/user-attachments/assets/906d1510-2497-4382-a508-6bce77ea7031)
Above is the result of running the nest start script.
![image](https://github.com/user-attachments/assets/be961b65-4b4c-49f6-917b-b938e72d04e2)
Above is the result of HMR
