### ISSUE TITLE
IIS web.config setting to http and web socket

### ISSUE THREAD

**Issue by KenChanSwivel** [nestjs/nest#5384]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework
I have a nest program behind a IIS server. I added some web socket gateway to the program. However, I don't know how to config the web.config. Can anyone help?
My http server is running at port 8080 and web socket gateway on 8085.
Thanks

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for help questions. We are using GitHub to track Bug Reports, Feature Requests, and Regressions. If Discord isn't an option, you can try [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) as well.
