### ISSUE TITLE
Scaling issue while testing libraries

### ISSUE THREAD

**Issue by Wykks** [nestjs/nest#5385]
## Current behavior

Libraries generated by nest cli have one entry point "index.ts". This "index.ts" may contain a lot of exports, which slow down a lot unit testing.

I'm not sure how to explain this, so let me show you with code:

## Input Code

Let say we have two library.
- core
- users

I have a "user" service in my "users" library. 

```ts
import { Injectable } from '@nestjs/common';
import { CalculateService } from '@toto/core';

@Injectable()
export class UserService {
  constructor(private readonly calculateService: CalculateService) {}

  doStuff() {
    return this.calculateService.doStuff();
  }
}
```

And the corresponding unit test:

```ts
import { Test, TestingModule } from '@nestjs/testing';
import { UserService } from './user.service';
import { CalculateService } from '@toto/core'; // <== This import the whole "index.ts" from @toto/core /!\

describe('UserService', () => {
  let service: UserService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UserService,
        { provide: CalculateService, useValue: { doStuff: () => 'TEST' } },
      ],
    }).compile();

    service = module.get<UserService>(UserService);
  });

  it('should do stuff', () => {
    expect(service.doStuff()).toEqual('TEST');
  });
});
````

Now let's say I have another service in core: 
```ts
import { Injectable } from '@nestjs/common';

console.log('Hello, i\'m not part of the user test but I\'m running anyway');
const x = 100000000;
// eslint-disable-next-line no-empty
for (let i = 0; i <= x; i++) {}

@Injectable()
export class MonitorService {}
````

index.ts of core :
```ts
export * from './lib/core.module';
export * from './calculate/calculate.service';
export * from './monitor/monitor.service';
```

If I run the test of my "users" library, it's going to run the code inside "MonitorService".

EDIT: Repro https://github.com/Wykks/NestJsIssue5385

## Expected behavior

I just want to unit test "UserService" without loading anything else.
In a real world app, my tests are taking 30s to fire up just because of this (and multiply this by ~30 libs, it's a lot of time wasted). Typescript is basically spending a lot of time resolving everything... Even worse, when some of my services are using dependencies like "kerberos", which are trying to load bindings.

## Possible Solution

So far, I found this solution (inside user.service.spec.ts): 
```ts
[...]
jest.mock('@toto/core', () => ({
  CalculateService: {}
}));

describe('UserService', () => {
  let service: UserService;
[...]
```
But that not very convenient.

Am I missing something ?

## Environment

<pre><code>
Nest version: 7.0

 
For Tooling issues:
- Node version: 12.13.0
- Platform:  Windows 

Others:
NX 10.1
</code></pre>

**Comment by jmcdo29** [comment]
Couldn't you import the file directly? `import { whatever } from '@todo/core/path/to/lib/file'`? Also, why have top level functions in these files that run at import time? Shouldn't everything be behind a function that ran at call-time? Besides decorators of course as there isn't really a way around that.

**Comment by Wykks** [comment]
Hi ! Thanks for answering.

I can't import the file directly because theses library are packaged and may run independently. It's possible to do that only in the test file, but that doesn't solve anything since the service still import from the big "index.ts".
About top level function, yeah it was just an exaggeration here. Because this is an issue only on "big" project. And by that I mean at least more than ~200 lines of exports with also something like ~20 import for each file and so on (typescript resolve _everything_ before running the test).
When I run the profiler on jest, _3/4 of the time spend is on module resolution_.

And most of the time, I'm doing this import (`import { ... } from '@toto/core';`) just for nest injection dependency. (And also typings of the dependency ideally).
As soon as I need a thing in a library, the _whole_ library is resolved by typescript... _That's really inefficient._

I am aware that, the way it's done currently, there is no way around. But this is a real problem on a "big" project.

There must be a way to implement that test without loading the whole library, I'm kinda surprised that nobody encountered this issue, so that's why I'm wondering if I missed something.
Or, is this simply a big flaw in esmodule / nest injection dependency and we have to deal with it ?

**Comment by jmcdo29** [comment]
Can you provide a reproduction? Because you should be able to import past the root import so long as the path alias is set up correctly

**Comment by Wykks** [comment]
Sure https://github.com/Wykks/NestJsIssue5385

**Comment by jmcdo29** [comment]
Well, one option would be to add the path alias

```
"@toto/core/*": ["libs/core/src/*"]
```

And then start using `@toto/core/calculate/calculate.service` instead of `@toto/core`.

The problem here is that with using a barrel file (`index.ts`) for your exports, when that file is imported, even if you specify a part of the import, the entire file is imported first, meaning any top level functionality not hidden behind an export or a function call is going to happen. It's the same reason why we can do things like 

```js
// dist/main.js
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();
```

And call `node dist/main` and have the server start up. There's a top level function call that will be resolved on the file import (or run in this case, which is a fancy import). My suggestion would be to remove the top level code if possible, or keep it behind functions that are called elsewhere to keep the code from being ran on import. 

This isn't really a Nest thing, but a Typescript and JavaScript thing, and we just have to know how to live with it.

**Comment by Wykks** [comment]
The thing is, when core is packaged, then I can only access the file though the entrypoint "index.ts".
If an external project want to use my lib "users", it's not going to work.

I'm totally aware of the fact that top level function are run when a file is imported.
The true question is: why should my whole library be imported when I only want "CalculateService" ? It's not really a big deal for a build, but for testing there should be a way to bypass that.
Typescript is super slow resolving the whole library. In my real project, this take about **30 seconds** to resolve the whole lib and then run the test. The profiler literally show that the time is spend on typescript module resolution.

I added some random service to the repro. But since these services don't import anything (except Injectable), it's only adding 0.5s to the test.... Please bear with me that in my project it's not 0.5s but 30s (and -30s as soon as I remove the import from the core lib).

**Comment by jmcdo29** [comment]
The reason the import resolves the entire library is because the expert file exports the entire library. Even though you say `import { CalculatorService }` this is essentially object deconstruction. It's like doing
```ts
import * as CoreLibrary from '@toto/core'
const { CalculatorService } = CoreLibrary;
```

It's how Node and Typescript resolve imports

**Comment by Wykks** [comment]
Yes, sorry I'm definitely not clear about what I'm asking for 😅
I know why it's happening. But the issue it's as I explained before is that this "index.ts" pattern doesn't scale. And the tooling provided by Nest doesn't mention anything about this fact. Something is broken in this pattern, there should be a way to implement a test without having to resolving everything.
I'm not asking why it's happening, but how can we mitigate this issue, since this pattern is everywhere.

**Comment by jmcdo29** [comment]
> how we can mitigate this issue

Well, as I mentioned, set up the paths to import the file directly inserted of the index file. The other option is remove all top level code and let decorators be the only thing running at import time.

Other than those, this is an issue with language rather than framework or tools

**Comment by Wykks** [comment]
> set up the paths to import the file directly inserted of the index file
Can't do, these library are packaged and loaded independently.
> The other option is remove all top level code and let decorators be the only thing running at import time.
Yes this is the case 99% of the time. But the slow down is caused by typescript module resolution. Not actual code from the library.
And for the 1%: https://github.com/mongodb-js/kerberos/blob/master/lib/kerberos.js#L3
(Yeah, this cause a loading of kerberos bindings when a I run a unit test of a SomethingService which has nothing to do with kerberos... 😆)

Alright, we're going in circle here. Thanks for your time though 🙂
