### ISSUE TITLE
Create CRUD API using CLI

### ISSUE THREAD

**Issue by Syntax-hue** [nestjs/nest#5386]
## Is your feature request related to a problem? Please describe.

Create a CRUD API using just CLI.

## Describe the solution you'd like

it should look like this 

nest g crud (or whatever) [name]

That command should generate a RESTful API (module, controller, and service) with a dummy connection to the database (probably MongoDb will be the easiest to work with). This way we can develop even faster small applications like blogs, e-commerce (basically every product needs a small blog).

## Teachability, Documentation, Adoption, Migration Strategy

Users will be able to generate a user-friendly CRUD structure which will go further in production or serve as an example.

## What is the motivation/use case for changing the behavior?

We're making e-commerce for clothes. The customer requested a blog in which he can post useful information/sales/etc.

**Comment by jmcdo29** [comment]
[Duplicate on the CLI repo](https://github.com/nestjs/nest-cli/issues/836) , [the schematics repo](https://github.com/nestjs/schematics/issues/367) and [two open](https://github.com/nestjs/nest-cli/pull/849) [pull requests](https://github.com/nestjs/schematics/pull/466)

**Comment by kamilmysliwiec** [comment]
I've been working on something related to this issue as well. Will publish a blog post shortly.
