### ISSUE TITLE
support StaticInjector

### ISSUE THREAD

**Issue by zuohuadong** [nestjs/nest#539]
In dependency injection, or reflectiveinjector, and angular has begun to use staticinjector, theoretically staticinjector reduce the map level of lookup, have better performance.

**Comment by shekohex** [comment]
> Angular version 5 deprecated the `ReflectiveInjector` API and introduced `StaticInjector`. In short, the dependency injection in the newest versions of Angular will happen entirely compile-time so reflection will not be necessary.

> However, if you want to use dependency injection in your Node.js, Vue, React, Vanilla JS, TypeScript, etc. application you won't be able to take advantage of `StaticInjector` the way that Angular will because your application won't be compatible with Angular compiler.

> Form [Injection-js](https://github.com/mgechev/injection-js) author
That have been said, we actually didn't see anything wrong with Nest's Injection Engine
Which is very similar to Angular 4 one's

In Nest V5, the Injectior gets simpler, removed a lot of complexity and overhead (__scopes__). which will introduce more performance, reduced bootstrap time and more.

**Comment by zuohuadong** [comment]
use :StaticInjector & koa    
https://github.com/kyoko-df/nesk

Although I don't like KOA.

**Comment by kamilmysliwiec** [comment]
Nest uses a completely different injector under the hood. The API looks pretty similar (almost the same) and it was intended 🙂
