### ISSUE TITLE
Error Modules & Dependencies production

### ISSUE THREAD

**Issue by ralbeiro** [nestjs/nest#5398]
## Bug Report
Hi everybody, After many attempts, I still get the error that I report below, I have done it with the npm run build command and also with webpack, but it has not worked in any way when I want to pass my project to production.

Apparently it is not loading any module in production.

I really appreciate the help you can give me.

Thanks....

## Current behavior

After run 'node main.js' in the terminal open this error:

Error: Cannot find module '@nestjs/core'
Require stack:
- C:\server\main.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\server\main.js:118:18)
    at __webpack_require__ (C:\server\main.js:20:30)
    at Object.<anonymous> (C:\server\main.js:103:16)
    at __webpack_require__ (C:\server\main.js:20:30)
    at C:\server\main.js:84:18
    at Object.<anonymous> (C:\server\main.js:87:10) {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'C:\\server\\main.js'[39m ]
}

## Input Code

```ts

```

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 12.6.1  
- Platform:  
- Nest CLI Version : 7.5.1
Others:

</code></pre>

**Comment by jmcdo29** [comment]
I'd be willing to bet you don't have `node_modules` installed (i.e. `npm i --prod` or `yarn --production`).

Please use our [Discord](https://disocrd.gg/nestjs) channel (Support). We are using GitHub for Bug Reports, Regressions, and Feature Requests.

**Comment by ralbeiro** [comment]
> I'd be willing to bet you don't have `node_modules` installed (i.e. `npm i --prod` or `yarn --production`).
> 
> Please use our [Discord](https://disocrd.gg/nestjs) channel (Support). We are using GitHub for Bug Reports, Regressions, and Feature Requests.

Thanks for answering @jmcdo29, but it is assumed that if I run an 'npm run start: prod' or 'npm run build' all I have to do is pass the dist folder to the location in production and run it with pm2 or in terminal with 'node main.js', but should I run npm install there?

Because I have already done it and it still does not work, I think the error is at the time of generating the production files.

Thanks.....

**Comment by jmcdo29** [comment]
Just like with any other node server, you still need your production dependencies. You need the `package.json`, the `dist` and the `node_modules` so that node knows how they're all related to each other. This is the standard approach and not specific to Nest. Please use our [Discord](https://discord.gg/nestjs) for further discussion.

**Comment by ralbeiro** [comment]
> Just like with any other node server, you still need your production dependencies. You need the `package.json`, the `dist` and the `node_modules` so that node knows how they're all related to each other. This is the standard approach and not specific to Nest. Please use our [Discord](https://discord.gg/nestjs) for further discussion.

Thanks bro.... Im going to 'Disscord' .... but my dude is , for example in monoliticapp with Angular and Nestjs, the files for production is in folder dist/browser for views and dist/server for production and only contain main.js in the folder server.....

for example : https://medium.com/@naimishverma50/node-backend-for-angular-using-nest-js-f9d1528ef2dc
 

Than you for everything...

**Comment by mohsinamjad** [comment]
@ralbeiro I'm getting the same error, can you tell me how did you fix that?
I think it should work without node_modules in production as it's the responsibility of webpack to add relevant packages in your main.js file during the tree-shaking process while building.

**Comment by jmcdo29** [comment]
@mohsinamjad [that's not really the case for node servers](https://github.com/nestjs/nest/issues/1706#issuecomment-579248915), yes you can use webpack for _some_ of that, but it can't work with everything, as mentioned in the linked answer, due to requiring underlying lower level processes that could vary from machine to machine (bcrypt and database drivers are two common examples). Because of this, you can webpack it all into a `main`, but you still need to install the dependencies for production.
