### ISSUE TITLE
Using Nest with Kotlin

### ISSUE THREAD

**Issue by sereden** [nestjs/nest#540]
Is it possible to use Nest vs Kotlin? I found it's quite easy to use it with _express_ however express is not as good as Nest.

The biggest problem I've found that I can't import core Module
`import { Module } from '@nestjs/common';`

**Comment by shekohex** [comment]
See https://github.com/zachgrayio/nest-kotlin

Hope that helps you

**Comment by sereden** [comment]
@shekohex thanks. Looks like it doesn't have sense to mix it
