### ISSUE TITLE
Set the same annotations for all my controllers

### ISSUE THREAD

**Issue by anrolmar** [nestjs/nest#5410]
Hi, I have a bunch of controllers that needs to have the same annotations, like

```
@UseFilters(new HttpExceptionFilter())
@UseInterceptors(HttpResponseInterceptor)
```

Is there any option to implement a parent controller class with this annotations and then all my controllers could inherit them?

Thanks

**Comment by smolinari** [comment]
This might give you some ideas. 

https://github.com/nartc/nest-abstract

Scott

**Comment by kamilmysliwiec** [comment]
@anrolmar https://docs.nestjs.com/custom-decorators#decorator-composition
