### ISSUE TITLE
Support ReactSSR

### ISSUE THREAD

**Issue by thachp** [nestjs/nest#5413]
## Feature Request
To be able to use ReactJS as a template engine other than HBS or PUG.  

## Is your feature request related to a problem? Please describe.
I have a conditional issue, where I need to check if the length of an array is greater than X, then display certain text.
With HBS, I need to register a length helper, then call that helper in the template.  The entire flow seems redundant and tedious, for something that should be supported out of the box.  It gets more complicated when I need to apply nested logics.

## Describe the solution you'd like
To be able to take full advantage of ReactJS and JSX syntax.

## Teachability, Documentation, Adoption, Migration Strategy
There is a temporary solution, and it seems to work, but it required changes to the start command.
https://github.com/saltyshiomix/react-ssr

## What is the motivation/use case for changing the behavior?
I'm more comfortable coding in ReactJS than other template engines.

**Comment by Subv** [comment]
I was recently looking for ways to use React with Nest and found this solution which bridges NextJS and NestJS: https://github.com/kyle-mccarthy/nest-next

So far it has worked fine for us.

**Comment by thachp** [comment]
@Subv  I appreciate you sharing the solution.  I'll use it too.

**Comment by kamilmysliwiec** [comment]
`nest-next` should fulfill your needs.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by pmb0** [comment]
You can try my express/nestjs render engine:

https://www.npmjs.com/package/express-tsx-views
