### ISSUE TITLE
ClassSerializerInterceptor doesn't seem to work on request DTOs

### ISSUE THREAD

**Issue by avner-hoffmann** [nestjs/nest#5426]
## Current behavior
I'm trying to add ClassSerializerInterceptor to my controllers in order to be able to use the @Expose decorator of class-transformer on my request and response DTOs.

In the docs of interceptors (https://docs.nestjs.com/interceptors) it seems that the interceptors should run both on the request and response of the controller.

Lookking at the serialization docs (https://docs.nestjs.com/techniques/serialization), I've added the @UseInterceptors(ClassSerializerInterceptor) on top of my controller class definition, imported the "Exclude" decorator from class-transformer library and used it on top of my DTO class field definitions.
However it seems that the interceptor only works for the response DTOs and not for the request ones.
In the controller my requests are either POST or PUT and I'm using the @Body decorator to get the body of the request into my request DTO.
In the docs there's only an example of usage on the response DTO and not the request.

## Input Code

controller:
```
@UseInterceptors(ClassSerializerInterceptor)
export class Controller {
    @Post('path')
    @HttpCode(200)
    public async someRoute(@Body() payload: RequestDTO) : Promise<ResponseDTO> { ... }
}
```

RequestDTO:
```
import { Expose } from 'class-transformer';

export class RequestDTO {
    @Expose({ name: 'field1_name' })
    field1Name: string;

    @Expose({ name: 'field2_name' })
    field2Name: string;
}
```

also on the main.ts file I'm importing 'reflect-metadata' as stated in the class-transformer docs )https://github.com/typestack/class-transformer):

```
import 'reflect-metadata';
```

## Expected behavior
The request body json fields will be mapped to the DTO fields

## Environment

@nestjs/common": "^7.0.0",
@nestjs/core": "^7.0.0",
@nestjs/platform-express": "^7.0.0",
class-transformer": "^0.3.1",
reflect-metadata": "^0.1.13" 

For Tooling issues:
- Node version: 14.9.0
- Platform:  Mac

**Comment by jmcdo29** [comment]
The `ClassSerializationInterceptor` is for serliazing data from a class to a JSON, and being able to strip properties by decorating them accordingly. I'm not sure of the use case of stripping incoming data, other than stripping fields that don;t exist on the DTO, but if you want to make use of `class-transformer` on incoming requests, you can set `transform: true` on the `ValidationPipe`.

Please use our [Discord](https://discord.gg/nestjs) channel (Support) for more help. We are using GitHub to track bug reports, feature requests, and regressions.

**Comment by avner-hoffmann** [comment]
@jmcdo29 - So what you're saying is that the way to do the above is using ValidationPipe which will transform the request fields into the request DTO fields?
I'd expect that if the ClassSerializationInterceptor works on the response it should work for requests as well, as it stated in the docs that interceptors work for the request as well

**Comment by jmcdo29** [comment]
@avner-hoffmann that's exactly what I'm saying. The problem with using the `ClassSerializerInterceptor` for that would be getting the type for all of the appropriate parameters (`@Body()`, `@Query()`, `@Param()`, custom decorators, and decorators outside of standard HTTP), and de-serializing them to their class representation.  The type is necessary due to the signature of the `class-transformer` method, `plainToClass(classType, plainObject)`. Without that type, there's nothing to de-serialize to. This already happens for pipes by default in NestJS, so it wouldn't make much sense to move the logic to an interceptor.
