### ISSUE TITLE
Transient custom provider not injected into middleware

### ISSUE THREAD

**Issue by alisd23** [nestjs/nest#5427]
## Current behavior
When trying to inject a custom provider with `Transient` scope into a global middleware configured in the `configure()` method of the `AppModule`, the dependency is not passed into the constructor - instead `null` is passed in.

Interestingly if the custom provider has scope `REQUEST`, everything works fine and the service is passed in.

## Input Code
Minimal reproduction:
https://codesandbox.io/s/nest-forked-jud6p?file=/src/app.module.ts

## Expected behavior
I would expect a new instance to be passed into the middleware constructor, unique to the middleware (because of the transient scope)

## Environment
Nest version: 7.4.4

**Comment by jmcdo29** [comment]
Looks like this is due to the way that `consumer.apply(ClassMiddleware)` runs. Can you please convert the codesandbox to a GitHub repo so it's easier to clone and run locally?

**Comment by alisd23** [comment]
@jmcdo29 Here you go: https://github.com/alisd23/nestjs-transient-dependency-middleware-repro

Another interesting thing I just tried: the `useClass` provider seems to work as expected in this super basic case. I haven't tried `useExisting`, but it could actually be a specific issue/limitation with `useFactory`.

**Comment by kamilmysliwiec** [comment]
This should be fixed in the latest release.
