### ISSUE TITLE
Multi http path / method on contoller 

### ISSUE THREAD

**Issue by ardyfeb** [nestjs/nest#5428]
## Is your feature request related to a problem? Please describe.

Using different http path or method on same controller method.

**Scenario:**
Creating or updating resources often have same logic, creating different function for each operation cause DRY code

## Describe the solution you'd like

**Example:**
```ts
@Post('/')
@Patch('/:productId')
async upsert(...) { ... }
```

**Comment by kamilmysliwiec** [comment]
This has been discussed in the past already. Please, search for past issues.
