### ISSUE TITLE
Is it possible to apply a middleware for all routes (globally)?

### ISSUE THREAD

**Issue by weeco** [nestjs/nest#543]
I'd like to apply a middleware for all routes, but apparently the `forRoutes()` config is needed. Is there a way to apply the middleware for all routes in the app.module ?

My use case is the JWT authentication for a REST Api which should be active for all endpoints.

```ts
export class AppModule {
  configure(consumer: MiddlewaresConsumer) {
    consumer.apply(AuthMiddleware);
  }
}
```

**Comment by ericzon** [comment]
Hello weeco, if you pass a controller class in forRoutes, it'll be applied to all is routes.

**Comment by Mesko89** [comment]
You can also use `forRoutes({ path: '*', method: RequestMethod.ALL })`:
```ts
export class AppModule {
  configure(consumer: MiddlewaresConsumer): void {
    consumer
      .apply([AuthMiddleware])
      .with('AppModule')
      .forRoutes({ path: '*', method: RequestMethod.ALL });
  }
}
```

**Comment by weeco** [comment]
Using the wildcard for the path works. Thanks!

**Comment by BMalaichik** [comment]
@weeco JFYI, for this case i think better use guards
https://docs.nestjs.com/guards
it's kinda clever middleware with access to invoke context

**Comment by lazarljubenovic** [comment]
Apparently, simply passing an asterisk `*` (instead of a full object) works as well, for all methods (I think).

```ts
export class AppModule implements NestModule {
  public configure (consumer: MiddlewareConsumer): void {
    consumer
      .apply(AuthMiddleware)
      .forRoutes('*')
  }
}
```

**Comment by yharaskrik** [comment]
You can also do: 

`
const app = await NestFactory.create(ApplicationModule);
app.use(logger);
await app.listen(3000);`

https://docs.nestjs.com/middleware

**Comment by felangel** [comment]
This seems like it's no longer working in `v5.7.4` 😢

**Comment by vijayakumar-psg587** [comment]
I myself wanted to use busboy body parser middleware, but unsure how that can be done in nestjs. Any ideas.? `app.use(busboybodyParser());` doesn't work  My nest version is **5.8.0**

**Comment by felixhayashi** [comment]
> You need to use functional middleware when using app.use();

this should definitely be documented...

**Comment by kamilmysliwiec** [comment]
> this should definitely be documented...

It's is documented

**Comment by felixhayashi** [comment]
Hi @kamilmysliwiec,

thanks for your reply.

The [section regarding global middlewares](https://docs.nestjs.com/middleware#multiple-middleware)  does not include a note about that only functional middlewares are possible on a "global" level.

![2019-07-21 08:40:55](https://user-images.githubusercontent.com/4307137/61587923-74d26b00-ab93-11e9-8c65-537be3eb2eaa.png)

I would recommend to add: "Accessing the DI container in a global middleware is not possible, you need to use a functional middleware instead when using app.use();"

The [section about functional middlewares](https://docs.nestjs.com/middleware#multiple-middleware) also does not conatin such a hint. Maybe it could be extended to:

> Consider using the simpler functional middleware alternative any time your middleware doesn't need any dependencies or if you need to register the middleware as global middleware.

Finally, in the [section about DI](https://docs.nestjs.com/middleware#dependency-injection) it starts of with the claim: 

> Nest middleware **fully** supports Dependency Injection. 

Which does not seem to be true for global middlewares.

The only part I found where it is **implicitly** communicated, that DI is impossible for global DI is this part in the [section about DI](https://docs.nestjs.com/middleware#dependency-injection).

> Just as with providers and controllers, they are able to inject dependencies that are available within the same module. As usual, this is done through the constructor

May I ask, whether you ever considered also making the services, that are publicly exposed by the different modules via `providers`, available to global middlewares via DI? 

Anyhow, the `.forRoutes('*')` technique to listen to all requests works fine for me now.

**Offtopic:** thanks for the great framwork, it is great to see somebody being dedicated to the idea of improving the architecture of nodejs backends :+1:
