### ISSUE TITLE
Re: @Body decorator only picking up one named argument.

### ISSUE THREAD

**Issue by OluAgunloye** [nestjs/nest#5430]
## Current behavior
This was already referenced in #21 (closed now) but basically the body decorator only takes one named argument, still. 
This should have been fixed with the upgrade, but wasn't for some reason. 

## Input Code

```ts
  async updatePaper( @Users('phoneNumber', 'userType') phoneNumber: string, usrType: string, @Body() content, @Body('PaperData') PaperData: UpdatePaperDto, @Body(UPipe, MPipe, UsPipe, APipe, CPipe, AEPipe) recipe:Object): Promise<any> {
    return  await this.workService.editPaper(phoneNumber, usrType, paperData, recipe);
  }
```

## Expected behavior
Expecting the body decorator to take and validate/transform one property with the same name as the named argument and then pass the entire body on. In the case of a dto, it should not transform the entire body by only taking the named property from the body and discarding the rest.

## Possible Solution

Whatever was done in the upgrade that fixed this issue, perhaps has been overridden or reversed somehow?

## Environment

<pre><code>
Nest version: 7.1.5
 
For Tooling issues:
- Node version: 12.16.0
- Platform:  Standard Ubuntu 18

Others:
</code></pre>

**Comment by OluAgunloye** [comment]
I just forcefully reupdated everything (uninstall then install latest via npm).  Seems to be working just fine now.

**Comment by kamilmysliwiec** [comment]
> Whatever was done in the upgrade that fixed this issue, perhaps has been overridden or reversed somehow?

Passing more than one attribute name has never been possible and there are no plans to add it in the near future.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
