### ISSUE TITLE
Nest changing @Query to false if is not sent on the request

### ISSUE THREAD

**Issue by DavideCarvalho** [nestjs/nest#5435]
## Bug Report
I have an endpoint where I expect a Query param called "enabled". This query param is optional, but, if the client doesn't send it, Nest makes it default false.

Tried adding the "?" mark to the variable, but it doesn't change.

## Current behavior

If the client doesn't send the "enabled" query param, it will always be false

## Input Code

You can check it on our open source project, on "course.controller.ts" on getAll method.
https://github.com/NewSchoolApp/newschool-backend/tree/develop

## Expected behavior

If the client doesn't send the enabled query param, it should be null

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
The repo which you provided has far too much going on in it to be a minimum reproduction. Can you pare down what's happening and make a __minimum__ reproduction of your issue?

**Comment by DavideCarvalho** [comment]
> The repo which you provided has far too much going on in it to be a minimum reproduction. Can you pare down what's happening and make a **minimum** reproduction of your issue?

Can do, sorry about that

**Comment by DavideCarvalho** [comment]
I'm trying to reproduce it on a codesandbox environment, but I'm not getting the same result. I'll close it, and if I'm able to reproduce it again on another environment that is not the open source project, I'll open it again, okay?

Sorry for the trouble
