### ISSUE TITLE
Tag the project with swagger and/or openapi

### ISSUE THREAD

**Issue by tmanolat** [nestjs/nest#5439]
## Is your feature request related to a problem? Please describe.
Not problem related - I thought the project should be tagged with swagger / openapi since nest.js gives nice out of the box features and it should be found by browsing swagger / openapi  GitHub tags

## Describe the solution you'd like
Tag the project with swagger and/or openapi 

## Teachability, Documentation, Adoption, Migration Strategy
N/A

## What is the motivation / use case for changing the behavior?
Visibility of project when searching for Swagger / OpenApi solutions

**Comment by jmcdo29** [comment]
The nestjs/swagger repository already has the `swagger` tag. As this monorepo doesn't contain code for the swagger module, I'm not sure it should be tagged.
