### ISSUE TITLE
Execution context vs declare Global namespace in a CRON job proccess

### ISSUE THREAD

**Issue by cdiaz** [nestjs/nest#544]
I have a process that runs repetitively on a cron Job using Bull

This process is outside from my Nest application context, but I need to call  methods of a component of my nest application.

I am using NestFactory.createApplicationContext () to obtain the instance of my component, on follow mode:

```js
import { NestFactory } from '@nestjs/core';
import { BtcPriceModule } from '../../btcprice/btcprice.module';
import { BtcPriceService } from '../../btcprice/btcprice.service';

const BtcPriceProcessor = async (job) => {
  
  const context = await NestFactory.createApplicationContext(BtcPriceModule);
  const btcPriceService = context.get(BtcPriceService);

  return await btcPriceService.fetch(job.data.currency)
    .then(data=> Promise.resolve(data))
    .catch(err=> Promise.reject(err))
}

export { BtcPriceProcessor } 
```
But this causes that during each execution of the process (every minute) NestFactory and InstanceLoader are initialized

![alt text](https://i.imgur.com/whnQuDv.png)

Another alternative that works for me is adding the app to global interface in the following way:

```js
//global.d.ts
declare namespace NodeJS {
  interface Global {
    app: any;
  }
}
```

```js
//main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  global.app = app;
  await app.listen(3000);
}
bootstrap();
```

```js
import { BtcPriceModule } from '../../btcprice/btcprice.module';
import { BtcPriceService } from '../../btcprice/btcprice.service';

const BtcPriceProcessor = async (job) => {
  
  const btcPriceService = global.app.select(BtcPriceModule).get(BtcPriceService);
  return await btcPriceService.fetch(job.data.currency)
    .then(data=> Promise.resolve(data))
    .catch(err=> Promise.reject(err))
}

export { BtcPriceProcessor }
 ```

I would like to know what implications have in terms of performance and what is the best practice to do so?

The reproducible example is in this [repository](https://github.com/cdiaz/nest-job-queue)

**Comment by fwoelffel** [comment]
I think you could also define a `nest.instance.ts` file with the following content:

```ts
// nest.instance.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
export const getNestInstance = async () => {
    return await NestFactory.create(AppModule);
}
```

Then in you `main.ts` and every file where the Nest instance is needed:

```ts
// main.ts
import { getNestInstance } from './nest.instance.ts';
async function bootstrap() {
  const app = await getNestInstance();
  await app.listen(3000);
}
bootstrap();
```

This way, you make use of the [Node.js caching mechanism](https://nodejs.org/api/modules.html#modules_require_cache) and avoid the global variable definition (which is a bad practice).

PS: I haven't tested this code. Let me know if there's anything wrong with it.

**Comment by kamilmysliwiec** [comment]
Either is fine. However, a solution without `global` variable seems to be a bit cleaner here. 🙂
