### ISSUE TITLE
Exception from referenced project do not bubble up correctly

### ISSUE THREAD

**Issue by rajeevBlr** [nestjs/nest#5440]
## Current behavior
My code project structure:
+---apps
|   +---AppServer
|   |   +---config
|   |   +---src
|   |   |   +---ScenarioHttp
|   |   |   \---tasks
|   |   |       +---dto
|   |   |       \---pipes
\---libraries
    +---domain
    |   \---src
    |       +---common
    |       |   \---dto
    |       \---scenario
    |           +---dto
    |           +---entity
    |           +---repo
    |           \---service

I have code in the above structure. Here **Apps** project references **domain** library. 
When I throw an `HttpException` from **Apps**, the api gives the correct error message and correct status code.

But if I throw an `HttpException` from **domain** library then the api shows _500 Internal Server Error._ The original error is not sent as a response.
## Input Code

```ts
```
I throw below exception in both of the cases.
`throw new HttpException('TEST', HttpStatus.FORBIDDEN);`

## Expected behavior
The framework should have a consistent response irrespective of where in the call stack the exception is thrown. The API response should have been consistent. The API should give 403 status code with 'TEST' as a message irrespective of where the exception was thrown from.

## Environment

<pre><code>
Nest version: 7.3.2

 
For Tooling issues:
- Node version: 12.18.2
- Platform: Windows 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by rajeevBlr** [comment]
@kamilmysliwiec you may want to have a look at the code https://github.com/rajeevBlr/Nest-pnpm

**Comment by cice** [comment]
> @kamilmysliwiec please have a look at the code https://github.com/rajeevBlr/Nest-pnpm which can replicate the issue. I have reported it under Discord channel too.

Did you manage to solve this? i'm having the same issue, and my guess that it's rooted in typescript's well-known Error-subclassing+instanceof issue https://github.com/microsoft/TypeScript/issues/13965 .
