### ISSUE TITLE
(microservices) Update Kafka Interface (kafkajs 1.13.0)

### ISSUE THREAD

**Issue by mkaufmaner** [nestjs/nest#5442]
## Is your feature request related to a problem? Please describe.
Currently the `kafka-options.interface.ts` is a little bit out of date.  In v1.13.0 of kafkajs there is support for [follower fetching](https://kafka.js.org/docs/consuming#a-name-follower-fetching-a-follower-fetching) which requires a `rackId` to be set when defining the consumer.

## Describe the solution you'd like
Update the `kafka-options.interface.ts`.

## Teachability, Documentation, Adoption, Migration Strategy
No breaking changes.

## What is the motivation / use case for changing the behavior?
Follower fetching, see https://www.confluent.io/blog/multi-region-data-replication/ and https://medium.com/collaborne-engineering/how-we-cut-kafka-data-transfer-costs-by-90-4beb5c464cdf

**Comment by kamilmysliwiec** [comment]
Updated in 7.5.0
