### ISSUE TITLE
Using @Res() the response freezes

### ISSUE THREAD

**Issue by nichmorgan** [nestjs/nest#5448]
## Current behavior

When the controller method has @Res as a parameter, the response freezes

## Input Code

```ts
...
import {Response} from 'express'
import {Res} from '@nestjs/common'
...
@Get(':id')
  findOne(@Param('id') id: string, @Res() res: Response) {
    const user = this.usersService.findById(id)
    return user
  }
```

## Without @Res()

![image](https://user-images.githubusercontent.com/55922364/93694768-17fb7900-fae6-11ea-80b5-0aee03809876.png)

## With @Res()
![image](https://user-images.githubusercontent.com/55922364/93694792-424d3680-fae6-11ea-8b71-aed86d847598.png)

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: v14.11.0  
- Platform: Windows 
- Using TypeORM

**Comment by jmcdo29** [comment]
This is expected and documented

**Comment by nichmorgan** [comment]
But the response never comes in

**Comment by jmcdo29** [comment]
As soon as you add `@Res()` to the handler, you must handle the response yourself. This is the excepted and documented functionality. Please use our [Discord](https://discord.gg/NestJS) for further support

**Comment by nichmorgan** [comment]
I had handle It too. I removed the handler to simplify.

**Comment by jmcdo29** [comment]
If you really do handle it and it freezes, please provide a minimum reproduction

**Comment by nichmorgan** [comment]
My friend, I will explain again. The scenario is that just by using @Res as a parameter it freezes when serializing the object in the response. If I return @ Res.send () it works, but when serializing it freezes. If you don't want to help me, don't be unpleasant either, we are on the same side of the opensource initiative, trying to help improve what we can.

**Comment by jmcdo29** [comment]
Yes, [in the documentation](https://docs.nestjs.com/controllers#appendix-library-specific-approach) it's mentioned that if you use `@Res()` for **any** reason in that route handler (class method) you **must** handle the response yourself. If you do not handle it, the request hangs. This **is** the expected functionality. I would love to help you if you are noticing something other than that, but so far it doesn't sound like that is the case. 

And apologies if I come off as rude, but we have [a discord server dedicated to support](https://discord.gg/NestJS) and many times we get people submitting issues without fully reading the documentation.

If you're still having a problem, please provide a minimum reproduction repository and we'll take a look as soon as possible.

**Comment by Max-dev228** [comment]
To fix this, you can set the passthrough option to true.

**Comment by danielcamargo** [comment]
Here is one way to fix the issue:
```
@Get('me')
  async me(@Res({ passthrough: true }) res): Promise<User> {
    const { uid: id } = res.locals;
    return await this.usersService.findOne(`users/${id}`);
  }
```
