### ISSUE TITLE
If exceptionFactory is defined in global pipe, use it as a fallback when using other pipes

### ISSUE THREAD

**Issue by royi-frontegg** [nestjs/nest#5449]
## Is your feature request related to a problem? Please describe.
I declared a global pipe with exceptionFactory of my own. Then, when using another pipe (more precisely ParseArrayPipe) It didn't use the global exceptionFactory but Nest's default exception factory

## Describe the solution you'd like
I'd prefer the global pipe would be used as the name suggests.. a global pipe 

## What is the motivation / use case for changing the behavior?
If I declare a standard way to return values from my app, it's redundant that I declare it over and over again only since I used a different pipe. Especially if the only way to get array of objects in my API, is use a different pipe

**Comment by kamilmysliwiec** [comment]
This is not the way NestJS pipes are designed. For sharing the exceptions handling logic, you should rather create an exception filter.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by royi-frontegg** [comment]
I don't wish to share exception logic. I wish that validation exceptions would conform to my structure. Validation exceptions are not going through the global exception filter so I must define an exceptionFactory in the global pipe. Since ParserArrayPipe was defined for a certain endpoint, I had to redefine it again on that pipe.

A better feature request would be that validation exception would go through the GlobalExceptionFilter.

BTW, this was a feature request

**Comment by kamilmysliwiec** [comment]
> Validation exceptions are not going through the global exception filter

They do.

Again, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
