### ISSUE TITLE
Don't use lint-staged

### ISSUE THREAD

**Issue by ThisIsMissEm** [nestjs/nest#5460]
## Current behavior

Currently, `nest new` generates a project that configures using both husky and lint-staged, including running prettier on each commit. This is an anti-pattern.

When running `git commit`, the developer has explicitly selected what to commit via `git add`, by running something that modifies that selection during the commit phase, the developer no longer has any control over what's committed. For instance, I just went to change two files in my projects without committing one of the other files (an unrelated change), and husky/lint-staged/prettier "helpfully" committed all the changed files, even though they weren't staged.

> That is, git hooks shouldn’t change the users’ intent when they issue git commit, which is what hooks like lint-staged and husky with prettier do. They change the code you’re committing, meaning you don’t know for certain what you’re committing.

See here for better ideas: https://twitter.com/thisismissem/status/1119061841806807041?s=21

## Expected behavior

When I do `git commit` only the code that I've requested be committed via `git add` should be committed.

## Possible Solution

Remove lint-staged / prettier in pre-commit hooks. If you want similar functionality, perhaps offer a warning that the commit did not pass a `prettier` "check" run. (`prettier -c <dir>`)

## Environment

<pre><code>
Nest version: 7.4.1
 
For Tooling issues:
- Node version: v12.18.3
- Platform:  Mac
</code></pre>

**Comment by ThisIsMissEm** [comment]
Another alternative would be to use `pretty-quick` with the `--staged` option: https://github.com/azz/pretty-quick#--staged-only-git, though even then, you have issues because `lint-staged` modifies the files on disk when checking them, such that if you're in a rebase you can encounter errors because what you've saved in your editor is now out of sync with the on-disk changes.

**Comment by ThisIsMissEm** [comment]
Oh! My bad, I was told it was nest-cli that added this, but it seems to have actually been one of our developers, it just looked like it came from nest. Apologies!

**Comment by airtonix** [comment]
btw lint-staged doesn't do this. it'd be how you have your tasks configured in the lint-staged config.
