### ISSUE TITLE
NestJS Microservice TCP error handling wrong status

### ISSUE THREAD

**Issue by skliarovartem** [nestjs/nest#5464]
I have api gateway and some service. Transport is TCP. On my service I have ValidationPipe on MessagePattern method and the following catch, to convert http exception to rpc

```
@Catch(HttpException)
export class HttpErrorFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    return new RpcException(exception.getResponse())
  }
}
```

On my api gateway I use general catch:

```
@Catch()
export class HttpErrorFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const request = ctx.getRequest();
    const response = ctx.getResponse();
    const status = exception.getStatus ? exception.getStatus() : 500;
    const responseMessage = exception.getResponse ? exception.getResponse() : '';

    const errorResponse = {
      code: status,
      timestamp: new Date().toTimeString(),
      path: request.url,
      method: request.method,
      message: exception.message,
      responseMessage: responseMessage,
    };

    Logger.error(`${request.method} ${request.url}`, JSON.stringify(errorResponse), 'ExceptionFilter');
    response.status(status).json(errorResponse);
  }
}
```
Here is how I call method on my api gateway:

```
@Post()
  async check(@Body() body) {
    let res = this.client.send('check', body).toPromise();
    return res
  }
```
When validation is not passed I receive the following answer from api gateway:

```
{
    "error": {
        "statusCode": 400,
        "message": [
            "url must be an URL address",
            "url should not be empty"
        ],
        "error": "Bad Request"
    },
    "message": "Rpc Exception"
}
```

Answer looks more less nice, but the problem is that status of the answer is 201, but not 400. As I see solution now it is add middleware in api gateway to check if there is error field in all the answers and then throw new error, but it doesn't look nice solution. (btw, catch on api gateway is not triggered in this case) 
How to get proper status on api gateway answer? 
Many thanks!

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by sogunshola** [comment]
I am having the same issue
