### ISSUE TITLE
How to get decorator metadata inside custom transport strategy

### ISSUE THREAD

**Issue by vladimir-krasulya2** [nestjs/nest#5465]
Hello guys.
I'm struggling to pass options from EventPattern decorator.
I've create custom decorator :
```
function myEvent(pattern: string, options?: Record<any, any>) {
  return (target, key, descriptor) => {
    EventPattern(pattern)(target, key, descriptor);
    SetMetadata('myEventOptions', options)(target, key, descriptor);
  };
}
```

and then I'm trying to access `options` inside transport strategy
```
export class MyTransportStrategy extends Server implements CustomTransportStrategy {
  private async handleMessage(message) {
    const handler = this.getHandlerByPattern(message.name)!;
    const options = Reflect.getMetadata('myEventOptions',, handler);
  }
}
```
in the end - `options` is undefined, not sure what I'm missing here
Thx in advance.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
