### ISSUE TITLE
Is there anyway can  I generate the model from database

### ISSUE THREAD

**Issue by jiajiafish** [nestjs/nest#5466]
Hi，Great author
My project is built with Django，the database is postgre.
Django has a command called "inspectdb" which can generate model from database.

I want to migrate my project to nestjs now , does nestjs has similar command ?

**Comment by jmcdo29** [comment]
Nest is a framework for NodeJS. There is no built in database connection so you can use whatever ORM you want. This question sound be asked of your ORM of choice

**Comment by jiajiafish** [comment]
> Nest is a framework for NodeJS. There is no built in database connection so you can use whatever ORM you want. This question sound be asked of your ORM of choice

Thank you for your indicator .
Do you know which ORM can do this?

**Comment by kamilmysliwiec** [comment]
Example: https://www.npmjs.com/package/typeorm-model-generator

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
