### ISSUE TITLE
The ParseArrayPipe doesn't receive any error when I set items of Number  in ParseArrayOptions and send string item to it.

### ISSUE THREAD

**Issue by Abson** [nestjs/nest#5467]
## Bug Report

The ParseArrayPipe doesn't receive any error when I set items of Number  in ParseArrayOptions and send string item to it.

## Input Code

```ts
@Get()
findByIds(
  @Query('id', new ParseArrayPipe({ items: Number, separator: ',' }))
  ids: number[],
) {
  return 'This action returns users by ids';
}
```

## Expected behavior
This construction validates the incoming query parameters from an HTTP GET request like the following:
```ts
GET /?ids=p1,2,3
```
This HTTP request didn't receive any error.

## Possible Solution
I don't know

## Environment
```
 "@nestjs/common": "^7.0.0",
"@nestjs/core": "^7.0.0",
 "@nestjs/platform-express": "^7.0.0",
"class-transformer": "^0.3.1",
"class-validator": "^0.12.2",
```
 
For Tooling issues:
- Node version: v13.14.0
- Platform:  Mac

Others:

IDE: VSCode

**Comment by borabaloglu** [comment]
As far as I know, parse array pipe does not check the type after it transforms the data. I don't know if it is a design purpose. You can write your custom pipe such as:

```typescript
import * as validator from 'class-validator';

import { PipeTransform, Type } from '@nestjs/common';

export class ParseArray implements PipeTransform {
  private readonly type: Type<unknown>;
  private readonly seperator: string;

  constructor(options: any) {
    this.type = options.type;
    this.seperator = options.seperator;
  }

  parseAndValidate(value: any) {
    switch (this.type) {
      case Number: {
        const parsedValue = +value;
        if (!validator.isNumber(parsedValue, { allowNaN: false, allowInfinity: false })) {
          throw new Error('Given item must be a number.');
        }
        return parsedValue;
      }
      default: {
        break;
      }
    }
  }

  transform(value: any) {
    let items: any;
    try {
      items = value.split(this.seperator);
    } catch (error) {
      throw new Error('Given input is not parsable.');
    }

    return items.map(item => {
      return this.parseAndValidate(item);
    });
  }
}
```

usage:

```typescript
@Get()
findByIds(
  @Query(
    'id',
    new ParseArray({
      type: Number,
      seperator: ',',
    }),
  )
  ids: number[],
) {
  return ids;
}
```

You should improve this code by adding more validation check etc. I wrote the first thing that I came up with.

Hope it helps.

**Comment by kamilmysliwiec** [comment]
Just pulled the repo and it works as expected with the latest version

**Comment by inglkruiz** [comment]
@kamilmysliwiec What branch or tag did you pull? This is not working on v7.6.7. I read the Unit tests and this is not tested.

**Comment by RezaErfani67** [comment]
@kamilmysliwiec 
what do you mean?
this is not working on 7.6.15

![image](https://user-images.githubusercontent.com/24381986/116407762-578dfe80-a847-11eb-9a05-21a1ca7bf278.png)

**Comment by jmcdo29** [comment]
@RezaErfani67 if it's not working, will you provide a [minimum reproduction](http://minimum-reproduction.wtf)?

**Comment by RezaErfani67** [comment]
@jmcdo29 
```
@Get()
findByIds(
  @Query('id', new ParseArrayPipe({ items: Number, separator: ',' }))
  ids: number[],
) {
  return 'This action returns users by ids';
}
```
Expected behavior
This construction validates the incoming query parameters from an HTTP GET request like the following:

GET /?ids=p1,2,3
This HTTP request didn't receive any error.

Possible Solution
I don't know

**Comment by jmcdo29** [comment]
@RezaErfani67 did you read the link and how it mentions a git repo, not just a code snippet?
