### ISSUE TITLE
Remove cli-color dependency

### ISSUE THREAD

**Issue by ninja-** [nestjs/nest#5469]
## Current behavior

Currently dependency on cli-color is pulling up some legacy stuff(es5 shims etc.) causing crash when compiling with NCC - see https://github.com/vercel/ncc/issues/594.
It creates some weird webpack bug where it requires some random module instead of correct one.

## Possible Solution

https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts
```
const clc = {
  green: a => `\x1B[32m${a}\x1B[39m`,
  yellow: a => `\x1B[33m${a}\x1B[39m`,
  red: a => `\x1B[31m${a}\x1B[39m`,
  magentaBright: a => `\x1B[95m${a}\x1B[39m`,
  cyanBright: a => `\x1B[96m${a}\x1B[39m`
}
const yellow = a => `\x1B[38;5;3m${a}\x1B[39m`; // xterm(3)
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by ninja-** [comment]
@kamilmysliwiec sure :D would it be fine with you if I were to hardcode only the needed colors, similar to above?

**Comment by kamilmysliwiec** [comment]
Sounds good to me :) Let's keep them together in a separate file and we should be fine

**Comment by kamilmysliwiec** [comment]
Removed in 7.5.0
