### ISSUE TITLE
How to extend nest or write a plugin

### ISSUE THREAD

**Issue by FrancisVarga** [nestjs/nest#547]
Hi sorry it's not really an issue, **BUT** maybe i do mist it, any documentation?

**Comment by chanlito** [comment]
What do u mean by extend or plugins?

**Comment by FrancisVarga** [comment]
@shekohex thanks though gonna look into thanks.

@chanlito for instance the swagger module has a lot of missing part's(also some missing documentation), i would love to extend it and add more decorators.

**Comment by kpfromer** [comment]
I agree! I find it a little difficult building complex modules for nest js.

**Comment by kamilmysliwiec** [comment]
@FrancisVarga if you want to contribute to Swagger module, I'd very appreciate your help 🙂 

In general, 3rd-party modules/plugins should be built on top of *dynamic modules* API. This concept is a little bit further explained in the latest documentation: https://docs.nestjs.com/v5 (Modules chapter). However, there is still a missing part about `ModulesContainer` (a way to access a whole modules graph). I hope to provide a dedicated chapter soon.
