### ISSUE TITLE
 Cannot read property 'getInstanceByContextId' of undefined when injecting REQUEST

### ISSUE THREAD

**Issue by SaifJerbi** [nestjs/nest#5470]
## Bug Report
When injecting REQUEST object using @inject(REQUEST), i get the error below in production 
```log
[Nest] 1   - 09/23/2020, 12:13:53 PM   [ExceptionsHandler] Cannot read property 'getInstanceByContextId' of undefined +30379ms
TypeError: Cannot read property 'getInstanceByContextId' of undefined
    at /usr/src/app/node_modules/@nestjs/core/injector/injector.js:322:39
    at Array.map (<anonymous>)
    at Injector.loadCtorMetadata (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:322:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:87:26)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:81:9)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:38:9)
    at async Injector.resolveComponentHost (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:155:13)
    at async Promise.all (index 5)
    at async Injector.loadCtorMetadata (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:320:23)
```
I'm using REQUEST to get informations about the current user and some params from url to do logging. 
In dev mode, it works well and there are no issues with the injected instance.
But after production build and deployment, we get the error.

## Current behavior

An error is thrown in production only when we use @inject(REQUEST).
By trying to debugging in the [code](https://github.com/nestjs/nest/blob/09fbc83108c8429a21c4d383b62f68037d6d2204/packages/core/injector/injector.ts#L718) . The injector resolve an undefined host, 
```ts
return hosts.map(
      item => item.getInstanceByContextId(contextId, inquirerId).instance,
    );
```
## Input Code

```ts
export class LoggerService{
    constructor(@Inject(REQUEST) private request: Request){}
}
```

## Expected behavior

Get the instance without error
## Possible Solution

I'm working on a PR to fix the issue
## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: 10.20.1 and v12.16.3  
- Platform:  All

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by SaifJerbi** [comment]
Hi @kamilmysliwiec , 

Thanks for your reactivity, i found the issue causing the problem,
I tried to reproduce the bug in a fresh app, it wasn't reproduced.
So by looking deeper in my code. i found that the issue was caused in the injector when trying to instantiate a service that uses an ```@optional Kafka client provider``` which is not available in current context.
I removed this provider (the kafka client is no longer required) from my constructor and the issue disappeared.

I think the bug will be reproduced if you have: 
- serviceA injecting an optional provider (and not provided so it will be undefined)
- serviceB injecting the REQUEST provider
- serviceC injecting serviceA and serviceB

**Comment by kamilmysliwiec** [comment]
We still need a minimum reproduction repository to verify this behavior. It would be great if you could provide one

**Comment by prashant-amt** [comment]
Got the same issue, I have a service-A which is optional and it's been injected in a service B which is been injected in service-c,

For now, I have removed the optional decorator service-A and added it as a provider in all the places

**Comment by jmcdo29** [comment]
If you have the same issue, please provide a minimum reproduction and open a new issue with it
