### ISSUE TITLE
Refactoring to allow web frameworks to share services

### ISSUE THREAD

**Issue by tanekim77** [nestjs/nest#5480]
One of my projects uses nest js, but I want to share some of its services with other projects that are to be run in the web only. 
The services that I am planning to share do not use any Node server specific libraries, like 'fs', so they should be able to be shared with projects that are to be run solely in web browsers. However, when I tried this, it thew an error, because some of Inject, Injectable, or Module components of nest js are using server specific libraries, like 'fs'. Wouldn't it be nice if the nestjs can be refactored so that these components do not depend on server specific libraries so that the scenario like this would be possible?

**Comment by kamilmysliwiec** [comment]
This has been discussed many times in the past. Please, search for old issues.
