### ISSUE TITLE
Error 415: Unsupported media type for application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by advsoft** [nestjs/nest#5481]
## Current behavior
Nest.js with fastify returns 415 for POST request with application/x-www-form-urlencoded content type

## Input Code

My nest.js/fastify initialization:

```
async function bootstrap() {
  const fastifyAdapter = new FastifyAdapter();
  
  fastifyAdapter.register(fmp, {
    limits: {
      fieldNameSize: 100, // Max field name size in bytes
      fieldSize: 10000000, // Max field value size in bytes
      fields: 10,         // Max number of non-file fields
      files: 20,           // Max number of file fields
      headerPairs: 2000,   // Max number of header key=>value pairs
    },
  });

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    fastifyAdapter,
  );

  app.setGlobalPrefix('/api/v1');
  app.useGlobalPipes(new ValidationPipe());
  app.enableShutdownHooks();
  app.enableCors();

  ....

  await app.listen(3000, '0.0.0.0');
}

```

## Expected behavior
Correct handling of requests with application/x-www-form-urlencoded content type

## Possible Solution
Looks like there is something wrong with fastify-formbody registration, also I can not register it from main.ts (getting an error that content handler for application/x-www-form-urlencoded is already registered. However if I comment a line 121:

`this.register(require('fastify-formbody'));`

in `platform-fastify/fastify-adapter.js`, I am able to register fastify-formbody manually and it works.

## Environment

<pre><code>
Nest version: 7.4.2
 
For Tooling issues:
- Node version: 13.12.0
- Platform:  Windows

Others:
- platform-fastify: 7.4.4
</code></pre>

PS:
I have seen this one:
https://github.com/nestjs/nest/issues/3936
but looks like the problem reappeared

**Comment by jmcdo29** [comment]
Are you using TypeORM and Swagger? It seems that the use of both of those leads to this problem.

**Comment by advsoft** [comment]
> Are you using TypeORM and Swagger? It seems that the use of both of those leads to this problem. If not, can you please provide a minimum reproduction?

Yes, I use both of them, do we have a solution for this case?

**Comment by jmcdo29** [comment]
[There's an open issue and a workaround in the nestjs/swagger repository](https://github.com/nestjs/swagger/issues/891#issuecomment-686283228)

**Comment by advsoft** [comment]
Thank you, it solves the problem
