### ISSUE TITLE
Use string based ContextId.

### ISSUE THREAD

**Issue by snys98** [nestjs/nest#5482]
## Is your feature request related to a problem? Please describe.
No, but current `contextId` is `Math.random()` with a type of `number`.

## Describe the solution you'd like
Use string based ContextId, maybe some implementation like mongodb's `ObjectId`

## What is the motivation / use case for changing the behavior?
String based contextId is better for combination with other frameworks(e.g. tracing & logging).

**Comment by kamilmysliwiec** [comment]
`contextId` is considered as a private API and shouldn't be used in NestJS applications

**Comment by snys98** [comment]
Thank reply😄 

I also think it should be a private API, but in fact it is exposed when resolving the `Request Scoped` objects as the [doc](https://docs.nestjs.com/fundamentals/module-ref#getting-current-sub-tree) says. This may be another question, but I think the default behavior should be **resolving `contextId` automaticly when getting Request Scoped objects**, not current 
![image](https://user-images.githubusercontent.com/11873100/94502670-4a6c4b00-0237-11eb-87c6-061e01e7bd52.png)
(if I'm not misunderstanding something.) 

Thanks again!
