### ISSUE TITLE
Dependcy injection with moduleRef.resolve() does not find TRANSIENT providers in imported modules

### ISSUE THREAD

**Issue by glachac** [nestjs/nest#5487]
## Current behavior
This is an extension on the issue of the bug that was fixed in closed issue #4756 

When creating an injectable class using ModuleRef.resolve() the module is not found if it is inside an imported module.
Attempting to resolve results in:

```
    Error: Nest could not find Cat2Service element (this provider does not exist in the current context)
```

## Input Code

Minimal code reproducing error based on extending #4756 code is available here: [nest-di-bug](https://github.com/glachac/nest-di-bug)

```ts
@Module({
  imports: [],
  providers: [ 
    Cat2Service, 
    Cat2PetService
  ],
  exports:[Cat2Service,Cat2PetService]
})
export class Cat2Module {}

@Module({
  imports: [Cat2Module],
  providers: [
    AppService,
    CatService,
    CatPetService,
  
  // I Should not need to include these explicitly, but if I do, the moduleRef.resolve() will work
    // Cat2Service,
    // Cat2PetService
  ],
})
export class AppModule {}

//// app.service.ts
async addCat() {
    this.logger.log('`addCat()` called, should create a `CatService` and a `CatPetService` now...')
    const catService = await this.moduleRef.resolve(CatService);

    // This fails to resolve
    const cat2Service = await this.moduleRef.resolve(Cat2Service);
 
  }
```

## Expected behavior

Calling moduleRef.resolve() should find providers in imports.  Instead, the imported services must be explicitly add to the providers list to be found.

## Environment

-   Nest version: 7.4.4
-   Node version: v12.18.4
-   Platform: Ubuntu 20.04
 

## Work-aroud
If I explicitly list the providers that are exported in the other module, in the app.module providers list, the are found

**Comment by kamilmysliwiec** [comment]
By default, `ModuleRef` runs in a strict mode. You should either explicitly select modules (e.g., `moduleRef.select(Cat2Module).resolve(Cat2Service)` or disable the strict mode = `moduleRef.resolve(Cat2Service, { strict: false })`

**Comment by glachac** [comment]
Thanks!
For future readers, strict mode=false works, but you need to specify a contextId in the resolve interface:
```
const contextId = ContextIdFactory.create();
const cat2Service = await this.moduleRef.resolve(Cat2Service, contextId, {strict:false});
```

The `moduleRef.select()` does not seem to be an exposed interface on class ModuleRef in Nest 7.4.4  It appears to exist in NestApplicationContext however.

**Comment by rhyek** [comment]
Having little to no knowledge of the internal workings of Nest's IoC container, I would expect the same rules would apply when using `moduleRef.resolve` vs when allowing Nest to instantiate a provider/controller using the normal flow.

Given this module setup:
```ts
@Module({
  providers: [AuthService],
  exports: [AuthService],
})
export class AuthModule {}

@Module({
  imports: [AuthModule],
  providers: [AuthController],
})
export class ApiModule {}
```
And this working as expected:
```ts
@Controller({ scope: Scope.REQUEST, path: 'auth' }) // just for consistency with next code block
export class AuthController {
  constructor(private authService: AuthService) {} // no problem

  @Get('profile')
  async profile() {
    // ...
  }
}
```
Why would this not work as well?
```ts
@Controller({ scope: Scope.REQUEST, path: 'auth' })
export class AuthController {
  constructor(private moduleRef: ModuleRef) {}

  @Get('profile')
  async profile(@Req() req: Request) {
    const contextId = ContextIdFactory.getByRequest(req);
    const authService = await this.moduleRef
      .resolve(AuthService, contextId); // error thrown
  }
}
```

The moduleref documentation says:
> To retrieve a provider from the global context (for example, if the provider has been injected in a different module), pass the { strict: false } option as a second argument to get().

`AuthService` has in fact been injected or provided to the `ApiModule` since we imported `AuthModule` into it.

> By default, ModuleRef runs in a strict mode.

This is consistent with normal provider instantiation (cannot inject via constructor anything not provided within the current module) and so that's great! But that fact seems unrelated to the issue.

This seems like a bug to me unless it is made clear that the provider resolution semantics are different between moduleref and normal instantiation flow.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
