### ISSUE TITLE
Improve extensibility

### ISSUE THREAD

**Issue by kkoomen** [nestjs/nest#5497]
## Is your feature request related to a problem? Please describe.

Today I had to modify a single thing inside my validation pipe which extends the core validation pipe. All the methods being used in that core class are marked as `private` which is just unacceptable regarding extensibility for the community. I had to copy the *whole* core validation.pipe code just to make a small change. If all the methods were `protected` then I could just simply overwrite that small function without having to touch anything else. 

FYI: This change was not meant as a potential core fix, but had to be done temporarily due to another third-party package its incompatibility with something.

When creating packages it is recommended to use `protected`. It doesn't hurt the current code base or tests and if a developer needs to overwrite a method then you're allowing them to due to the `protected` visibility. Right now this can't be done for at least the `packages/common/pipes/validation.pipe.ts`, but I'm sure this is a general problem so I am submitting this feature request as a suggestion to change this in all packages where needed.

## Describe the solution you'd like

Change all the `private` visibility modifiers in all packages to `protected` to support better extensibility for the community.

## What is the motivation / use case for changing the behavior?

Methods should be able to be overwritten if a developer needs to extend a core class in order to change something.

**Comment by kamilmysliwiec** [comment]
> When creating packages it is recommended to use protected. It doesn't hurt the current code base or tests and if a developer needs to overwrite a method then you're allowing them to due to the protected visibility.

Most of the classes in the codebase are considered to be a part of the private API and so their methods, as well as properties, should (and are) specified as `private`. `ValidationPipe` is a good example in which having `protected` modifier gives more flexibility though. Feel free to create a PR with any changes that might be useful for the community (similar to #5498). However, we don't plan any massive action in which we change all the `private` access modifiers to `protected`.
