### ISSUE TITLE
Queue Processor sometimes running, sometimes not running

### ISSUE THREAD

**Issue by izundo-viennv** [nestjs/nest#5499]
## Current behavior
When I add a job to the queue, sometimes it calls handleComplete on ActionConsumer class, but sometimes it's not

## Input Code

`app.module.ts`
```ts
@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    FrameworkModule,
    BullModule.registerQueue({
      name: 'action',
      redis: process.env.REDIS_URL,
    }),
  ],
  controllers: [ActionController],
  providers: [ ActionConsumer, ActionService],
})
export class AppModule {}
```

`action.service.ts`
```ts
await this.actionQueue.add(
  'complete',
  {
    userId: user.id,
    actionId: action.id,
    abc: input.abc,
  },
  { priority: 1, attempts: 5, backoff: 10000, removeOnComplete: true },
);
```

`action.processor.ts`
```ts
@Processor('action')
export class ActionConsumer {
  private readonly logger = new Logger(ActionConsumer.name);

  constructor(
    private readonly actionService: ActionService,
  ) {}

  @Process('complete')
  async handleComplete(job: Job) {
    const { userId, actionId, abc} = job.data;
    console.log(userId);
  }
}
```

## Expected behavior
When I add a job to the queue, it's always call  handleComplete on ActionConsumer class

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: 12.18.3
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
I would suggest reporting this in the Bull repo https://github.com/OptimalBits/bull instead as this doesn't seem to be related to this package

**Comment by izundo-viennv** [comment]
I don't think so, I tested with the bull library it's work well
