### ISSUE TITLE
Monorepo has problems discovering entities

### ISSUE THREAD

**Issue by goodoldneon** [nestjs/nest#5505]
## Current behavior

In the TypeORM config, setting `entities` to `[__dirname + '/**/*.entity{.ts,.js}']` doesn't work. However, explicitly importing entities and passing them to `entities` works.

For example:

```ts
TypeOrmModule.forRoot({
  type: 'mysql',
  host: 'localhost',
  port: 3306,
  username: 'root',
  password: 'root',
  database: 'foo',

  /* The following `entities` value doesn't work. */
  // entities: [__dirname + '/**/*.entity{.ts,.js}'],

  /* The following `entities` value works. */
  entities: [User],

  synchronize: true,
}),
```

I suspect this is due to the way monorepos build. The `__dirname` variable points to `dist`, but the entities aren't compiled into `dist` in a monorepo. There are, however, compiled into `dist` in a non-monorepo.

## Input Code
https://github.com/goodoldneon/nestjs-monorepo-typeorm-issue

## Expected behavior

TypeORM should be able to discover entities on its own if you pass a glob path string, like with non-monorepos.

## Possible Solution

Maybe compile entities into `dist`?

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: 12.18.3
- Platform:  Mac

Others:

</code></pre>

**Comment by jmcdo29** [comment]
This is known and document. You can find [more information here](https://docs.nestjs.com/techniques/database#auto-load-entities).

> Note, however, that glob paths are not supported by webpack, so if you are building your application within a monorepo, you won't be able to use them. To address this issue, an alternative solution is provided. To automatically load entities, set the autoLoadEntities property of the configuration object (passed into the forRoot() method) to true, as shown below:

**Comment by goodoldneon** [comment]
Thank you! Sorry, I didn't see that in the docs.
