### ISSUE TITLE
Nest.js HMR does not replace module

### ISSUE THREAD

**Issue by kshahani** [nestjs/nest#5513]
## Current behavior

I'm using the Webpack example from [here](https://github.com/nestjs/nest/tree/master/sample/08-webpack), and modifying the text returned in `ApplicationService.getHello()` from `Hello world!` to `Hello world!!!`. I see the module get detected by Webpack, but hitting `http://localhost:3000` returns `Hello world!` still. Help!

## Reproducible example
https://github.com/kshahani/nestjs-webpack-issues

## Expected behavior
The route should return `Hello world!!!`

## Environment

<pre><code>
Nest version: 7.4.4
For Tooling issues:
- Node version: 12.13.1
- Platform: Mac
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by kshahani** [comment]
Here: https://github.com/kshahani/nestjs-webpack-issues

**Comment by jmcdo29** [comment]
It's working fine for me. I had to install the `@nestjs/cli`, but it works without a problem

**Comment by kshahani** [comment]
I'm seeing it work _occasionally_. If I add a few exclamation marks and save, I'll still see `Hello world!`, but then if I add a few more, I'll see `Hello world!!!!` or whatever I've added. Is there some kind of cache mechanism being used? I've tried in my browser, without cache, and even in postman without being able to narrow down the source of the problem...

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be related to NestJS CLI, but rather to the `HotModuleReplacementPlugin`. Please, report this issue in the `webpack` repository.
