### ISSUE TITLE
how to get/set express http  context in the file in nestjs

### ISSUE THREAD

**Issue by ajayprasad1982** [nestjs/nest#5514]
Hi @kamilmysliwiec 
I want to use [express-http-context](https://www.npmjs.com/package/express-http-context) in nestjs,is there any inbuilt package available.please suggest on this

Your reply will be a great help to me

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
