### ISSUE TITLE
Webpack resolution error when working in monorepo mode

### ISSUE THREAD

**Issue by nick-lehmann** [nestjs/nest#5516]
## Current behavior

When using nestjs in a monorepo setup with `lerna` and `yarn workspaces` with `compilerOptions.webpack` set to `false`, a lot of resolution errors show up.

```
ERROR in /private/tmp/nestjs-monorepo-webpack-error/node_modules/@nestjs/core/nest-application.js
Module not found: Error: Can't resolve '@nestjs/microservices/microservices-module' in '/private/tmp/nestjs-monorepo-webpack-error/node_modules/@nestjs/core'
 @ /private/tmp/nestjs-monorepo-webpack-error/node_modules/@nestjs/core/nest-application.js 17:120-173
 @ /private/tmp/nestjs-monorepo-webpack-error/node_modules/@nestjs/core/index.js
 @ ./src/main.ts

ERROR in /private/tmp/nestjs-monorepo-webpack-error/node_modules/@nestjs/core/nest-application.js
Module not found: Error: Can't resolve '@nestjs/websockets/socket-module' in '/private/tmp/nestjs-monorepo-webpack-error/node_modules/@nestjs/core'
 @ /private/tmp/nestjs-monorepo-webpack-error/node_modules/@nestjs/core/nest-application.js 16:102-145
 @ /private/tmp/nestjs-monorepo-webpack-error/node_modules/@nestjs/core/index.js
 @ ./src/main.ts
```

I'd like to have all nestjs applications under `/apps` and all libraries under `libs`. The official documentation suggests to have the libraries in a `libs` folder directly inside your application. However, I would like to a share a library with multiple applications inside a monorepo, so this way would not work for us.

It seems that `webpack` tries to resolve optional dependencies. I have not included `@nestjs/microservices` in any of my packages but is shows up as an optional dependency in `@nestjs/core`. After installing `@nestjs/microservices`, it then tries to find all its optinal dependencies, e.g. `mqtt`, `kafka`, etc. which I do not need at all.

## Input Code

[Reproduction Repo](https://github.com/nick-lehmann/nestjs-monorepo-webpack-error)

## Expected behavior

Nest CLI builds the application without any erros and reload if changes are made to any file in the libraries, e.g. `libs/core/src/core.service.ts`.

## Possible Solution

Use the typescript compiler instead. It builds the application, but does not reload on changes to the library.

## Environment

<pre><code>Nest version: 7.4.4
 
For Tooling issues:
- Node version: v14.7.0  
- Platform: OSX 11 Beta 6  
- Yarn: 1.22.4
</code></pre>

**Comment by kamilmysliwiec** [comment]
> When using nestjs in a monorepo setup with lerna and yarn workspaces with compilerOptions.webpack set to false, a lot of resolution errors show up.

If you want to use lerna/yarn workspaces, you shouldn't be using NestJS monorepo mode. You should never use both at the same time.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by shaurgon** [comment]
The problem is not with a lerna/yarn workspaces.
I dont use lerna, project was configured as Nest monorepo by [one](https://trilon.io/blog/announcing-nestjs-monorepos-and-new-commands) & [two](https://docs.nestjs.com/cli/monorepo#monorepo-mode) articles.
Webpack enabled by default
**webpack.config.js** from second article:
```
module.exports = (options) => {
    return {
      ...options,
      externals: [],
    };
};
```
On `nest build` command I see the same errors
