### ISSUE TITLE
@SerializeOptions works only on output while @Expose works on inputs

### ISSUE THREAD

**Issue by eyalyoli** [nestjs/nest#5517]
## Current behavior

The use case is that I have a class `UserPreferencesDto` that is a DTO for input payload in `savePrefs` while serving as an output DTO of another route.
In this case I use `@Expose` (meant to be applicable only for the output - as the [docs](https://docs.nestjs.com/techniques/serialization) say) and `@IsEnum` as an input validator.
This use case should work - according to the docs.

Apparently what happens is that because `@Expose` is based on class-transformer that works for both input/out (plainToClass/classToPlain), this removes the `type` prop from `prefs` input of the function `savePrefs`, afterward the validation runs and throws an error that `type` prop must be an enum (and it is missing!).
As you can see I tried to add `@SerializeOptions({ groups: ['self'] })` but it seems that this applies to outputs only! So it is an impossible use case to implement the same class for input/output while using `@Expose`.

## Input Code

```ts
export class UserPreferencesDto {
  @Expose({ groups: ['self'] })
  @IsEnum(Types)
  type: Types;
}

@SerializeOptions({ groups: ['self'] })
@Patch('preferences')
async savePrefs(
  @Request() req,
  @Body() prefs: UserPreferencesDto,
  ): Promise<any> {
...
}
```

## Expected behavior

`type` is not removed when the DTO is used as an input of some route.

## Possible Solution

Make `@SerializeOptions` apply to inputs (plainToClass) as in outputs (classToPlain)
OR
Don't apply `@Expose` to the inputs - maybe not possible

And fix the documentations on serialization.

## Environment

<pre><code>
Nest version: v7.2.0

 
For Tooling issues:
- Node version: v14.7.0  
- Platform:  Mac & Windows

Others:

</code></pre>

**Comment by jmcdo29** [comment]
This sounds exactly like why class-transformer has the option to add in which direction the transformation decorators apply. Looks like you'd need to add `{ toPlainOnly: true }` to the `@Expose()` decorator. [CT docs](https://github.com/typestack/class-transformer#skipping-depend-of-operation)

**Comment by eyalyoli** [comment]
Thnx! It seems to be what I'm looking for.

**Comment by KeM1aL** [comment]
`@ApiProperty({
    type: String,
  })
  @Transform(lowerCaseTransformer)
  @IsNotEmpty()
  @IsEmail()
  @Expose({ toPlainOnly: true, groups: [GROUP_USER]  })
  email: string | null;`

I have exactly the same issue but the toPlainOnly does not fix my issue ... any suggestion ?
