### ISSUE TITLE
Support Monorepo with JS as language

### ISSUE THREAD

**Issue by dominicrico** [nestjs/nest#5519]
## Is your feature request related to a problem? Please describe.

NestJS App as Monorepo with language JS is not working. It always wants tsconfig.json and tsconfig.app.json files.

## Describe the solution you'd like

Make it work?

## What is the motivation / use case for changing the behavior?

I'm using the plain JS variant of Nest and want to use the monorepos too

**Comment by jmcdo29** [comment]
[You already opened an issue in the CLI repo. Please do not open multiple issues regarding the same issue](https://github.com/nestjs/nest-cli/issues/897)

**Comment by dominicrico** [comment]
True, but I would rather close the CLI issue then this one, because I don't think that this is an CLI issue on its own.

**Comment by jmcdo29** [comment]
Why do you think it wouldn't be a CLI issue? You're literally using the `@nestjs/cli` to start the project and getting an error out of it.
