### ISSUE TITLE
Path param put in middle of a url does not work - returns 403 Not Found

### ISSUE THREAD

**Issue by Edwardchorius** [nestjs/nest#5520]
Currently when I want to access an endpoints:
`_api/someEndpoint/:pathParam/endOfEndpoint_` returns 403. But if I put it like that:
__api/someEndpoint/endOfEndpoint/:pathParam__  it works. 

Shouldn't we be able to use the first case as well?

**Comment by getspooky** [comment]
Hi @Edwardchorius Please give code example in order to have a clear idea about the problem
thanks

**Comment by Edwardchorius** [comment]
This works: 
`@Controller('api/vehicles')
export class SettingsController
...

@Patch('/repair/:partType')`
, whereas this does NOT work:

`@Controller('api/vehicles/:partType')
export class SettingsController
...

@Patch('repair')`

**Comment by jmcdo29** [comment]
Can you provide a minimum reproduction repository?

**Comment by Edwardchorius** [comment]
This is all there is. You have a standard controller class and action methods, decorated with 'Patch', 'Get'. You have a part of the **url** stated in the class and other parts in the action methods. When I put the path param somewhere but not at the end of the **url** , when testing with Postman, I receive a 403 Not Found error.

**Comment by jmcdo29** [comment]
Out of respect for maintainers of open source software, it is customary to provide a minimum reproduction, so that we do not need to spend time getting _your_ setup just right. So I'll ask again: Can you provide a minimum reproduction repository?
