### ISSUE TITLE
Support CSRF Protection by default

### ISSUE THREAD

**Issue by getspooky** [nestjs/nest#5521]
## Feature Request
Automatically generates a CSRF "token" for each active user session managed by the application. This token is used to verify that the authenticated user is the one actually making the requests to the application.

The VerifyCsrfToken middleware  will automatically verify that the token in the request input matches the token stored in the session.

**Comment by jmcdo29** [comment]
I'm not sure how I feel about this, to be honest. On the hone hand, authentication/authorization and security is something that we should all be aware of and vigilant about, and having a framework manage that for you would be great, but on the other hand, there's a lot of moving parts when it comes to security, and any time you add a new component (or two in this case) it can become very easy to have a rigid structure if you aren't careful. 

This especially becomes the case when it comes to customizing the session storage and the token generation method. With something like express there is [`express-session`](https://www.npmjs.com/package/express-session) and for fastify there is [`fastify-session`](https://www.npmjs.com/package/fastify-session), but both of these then bring in their own dependencies and can lead to extra size of the server, not to mention more confusion from users who don't understand that it's the underlying libraries that handle things like that and not Nest (most of the time).

I'm personally one for leaving this to the dev and letting them implement `csrf` or whatever other package they want, as Nest uses Express or Fastify under the hood, there isn't much reason to go and re-invent the wheel for this. Maybe an external package that could be configured, but overall, I don't see this to be the responsibility of the framework.
