### ISSUE TITLE
ClassSerializerInterceptor does not work properly when returning a WsResponse object

### ISSUE THREAD

**Issue by mukaschultze** [nestjs/nest#5525]
## Current behavior

Gateway responses do not respect `@Expose()` and `@Exclude()` decorators for classes when returning a `WsResponse` object.

## Input Code

```ts
export class SerializedClass {
    @Expose()
    exposed = "this should be exposed";
    @Exclude()
    excluded = "this should be excluded";
}
```

```ts
@SubscribeMessage("message")
handleMessage() {
    return merge(
        of({ event: "issue-demo", data: new SerializedClass() } as WsResponse), // Class doesn't get serialized
        of(new SerializedClass()) // Works fine
    );
}
```

### Client side logs

Data received from the server on the client is shown below:

Excluded property being transmitted to the client | Serialization working properly
-- | --
![image](https://user-images.githubusercontent.com/13923364/95004338-425a3580-05c0-11eb-9e05-334b5ec08da8.png) | ![image](https://user-images.githubusercontent.com/13923364/95004347-6289f480-05c0-11eb-8c81-9af15dc8b56b.png)

## Expected behavior
The serialization should also be applied to `WsResponse` objects.

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: v14.4.0  
- Platform: Windows 

Others:

Using @nestjs/platform-socket.io@7.4.4
</code></pre>

**Comment by jmcdo29** [comment]
Do you have the subscription method decorated with `@UseInterceptors(ClassSerializationInterceptor)`? Can you provide a minimum reproduction?

**Comment by mukaschultze** [comment]
> Do you have the subscription method decorated with `@UseInterceptors(ClassSerializationInterceptor)`

The decorator is in the class. The serialization does not work at all if the decorator is in the method.

The full implementation and repo can be [found here](https://github.com/mukaschultze/nestjs-issue-5525/blob/master/src/issue.gateway.ts).

If you connect to the gateway and emit a `message` event you'll be able to see both a `message` reply and an acknowledgement (the last function argument of socket.io's emit). The reply is correctly serialized, the ack is not.

One more thing,

[From the docs](https://docs.nestjs.com/techniques/serialization#exclude-properties):
> Note that we must return an instance of the class. If you return a plain JavaScript object, for example, { user: new UserEntity() }, the object won't be properly serialized.

Perhaps this is the reason why the serialization is not working, the `WsResponse` is a plain object and not a class instance.

Anyway, I'm pretty sure this is not the expected behaviour, and if it is I think it should be documented in the `WsResponse` documentation as some people might rely on `@Expose()` and `@Exclude()` to hide sensitive fields.

**Comment by jmcdo29** [comment]
Seems like having a mention in the docs would be useful. Would you like to make a PR for that?

**Comment by mukaschultze** [comment]
Done nestjs/docs.nestjs.com/pull/1489

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/1489
