### ISSUE TITLE
custom repository issue: "TypeError: Cannot read property 'findOne' of undefined"

### ISSUE THREAD

**Issue by Mng12345** [nestjs/nest#5526]
## Bug Report
I defined an custom repositoy, and used the findOne method in controller, i get the error: TypeError: Cannot read property 'findOne' of undefined. I looked up the source code, the reason seems to be that the manager: EntityManager does not injected into my custom repositoy, can any one tell me how to fix this problem? Someone also got the same situation: [Nest js and typeorm custom repository issue](https://stackoverflow.com/questions/63538964/nest-js-and-typeorm-custom-repository-issue)
## Input Code

```ts
const your = (code) => here;
```

## Environment
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "@nestjs/typeorm": "^7.1.4",
    "@types/nodemailer": "^6.4.0",
    "axios": "^0.20.0",
    "crypto-js": "^4.0.0",
    "dayjs": "^1.9.1",
    "mng-easy-util": "^1.1.6",
    "mysql": "^2.18.1",
    "nodemailer": "^6.4.11",
    "rimraf": "^3.0.2",
    "rxjs": "^6.5.4",
    "typeorm": "^0.2.26"
 
<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Mng12345** [comment]
This is not a bug???

**Comment by Jeh212** [comment]
Hello does anyone know how to solve this problem? Same here! I did my model all over again, checked the migrations and still getting the same issue! **"TypeError: Cannot read property 'findOne' of undefined"**

**Comment by jmcdo29** [comment]
nestjs/typeorm#317
