### ISSUE TITLE
null union types don't seemed to be captured when using an Entity 

### ISSUE THREAD

**Issue by JamesLMilner** [nestjs/nest#5536]
## Current behavior

Let's say I have a User Entity with a `test` property which is a `string | null`:
![image](https://user-images.githubusercontent.com/8822075/95224426-92204300-07f2-11eb-9cb0-925856867245.png)

When you go to use this property it seems to type it to `string`:
![image](https://user-images.githubusercontent.com/8822075/95224397-892f7180-07f2-11eb-82c7-f0cd08c69095.png)

## Input Code

```ts

@Entity()
export class User {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({ nullable: true })
    test: string | null;
}
```

```ts

        user.test;

```

## Expected behavior

Property with union null types to possibly be null.

## Environment

<pre><code>

"@nestjs/common": "7.3.1",
"@nestjs/core": "7.3.1",
"@nestjs/passport": "7.1.0",
"@nestjs/platform-express": "7.3.1",
"@nestjs/serve-static": "2.1.3",
"@nestjs/swagger": "4.5.12",
"@nestjs/terminus": "^7.0.1",
"@nestjs/typeorm": "^7.1.0",

For Tooling issues:
- Node version: v12.18.3
- Platform:  Linux

Others:
I'm using VSCode
</code></pre>

**Comment by jmcdo29** [comment]
This should be reported to [TypeORM's repository](https://github.com/typeorm/typeorm).

**Comment by JamesLMilner** [comment]
Apologies, yes of course. Sorry was in a bit of a daze!
