### ISSUE TITLE
Support for websocket gateway handling simultaneous https and http connections.

### ISSUE THREAD

**Issue by Rvkstrauss** [nestjs/nest#554]
I am attempting to create a socket.io instance in my app that can listen for client requests from both http and https connections, Currently in my server code  I am creating separate listeners for two ports, one http, and the other https:
    
    let appConf = null;
    if (config.SSL.enable === true) {
        appConf = {key: config.SSL.key, cert: config.SSL.cert};
    }
    const expressApp = express();

    const app = await NestFactory.create(ApplicationModule, expressApp);
    // app.useWebSocketAdapter(new IoAdapter(Server));

    app.use(bodyParser.json());
    app.connectMicroservice({
        transport: Transport.REDIS,
        url: config.redis
    });

    await app.startAllMicroservicesAsync();
    await app.listen(config.apiPort, () => console.log('app listening on port ' + config.apiPort));
    http.createServer(appConf).addListener('request', expressApp).listen(3443, () => {
        console.log('HTTPS server listening on port 443');
    });

telnet to both ports shows active listeners, and http socket connection on client functions as expected. However the https socket connection fails on client with a response of 
{"statusCode":404, "error":"Not Found","message":"Cannot GET /socket.io/?EIO=3&transport=polling&t=MAlH7Hi&sid=2sreZc_t8U40Bu6AAAA"} 

How can I configure my socket server instance to connect to clients via https?
(I'm using nest 4.2.1)
current socket implementation via @WebSocketGateway decorator

**Comment by kamilmysliwiec** [comment]
Even though you run 2 separated HTTP servers, Nest knows only about the default one created during the application initialization process. In this case, your `@WebSocketGateway()` will use only HTTP server, without access to this manually created HTTPS instance. The guide how to switch a default server from HTTP to HTTPS is available in the newest version of the documentation, here: https://docs.nestjs.com/v5/ (FAQ -> HTTPS [...]). However, it still won't make possible to use both servers at once.
