### ISSUE TITLE
Allow to redirect from a controller

### ISSUE THREAD

**Issue by fennperfo** [nestjs/nest#5541]
## Current behavior
When You try to do 301 redirections from a controller You get: "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client" error. Headers are sent to a client to early.

(node:11660) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header 

## Input Code

```ts
@Get('route*')
  someRoute(@Req() req, @Res() res, @Next() next) {
    if (!req?.cookies?.accessToken) {
      res.redirect(301,'/auth/login');
      return;
    }
    next();
  }
```

## Expected behavior
Redirection will be done without any error.

## Environment

<pre><code>
Nest version: 7.0.0
 
For Tooling issues:
- Node version: 12.18.0
- Platform:  Windows
</code></pre>
This issue is similar to [#794](https://github.com/nestjs/nest/issues/793)
Solutions mentioned in the above link didn't work for us

**Comment by jmcdo29** [comment]
[This is already possible and documented](https://docs.nestjs.com/controllers#redirection)

**Comment by fennperfo** [comment]
@jmcdo29 thanks for responding. Actually i have gone through this doc but the problem is i cannot use @Redirect as i have to call next as i am using it as middle ware as you see in the example i mentioned above, hence facing this issue. Do you know any solution or workaround to this?

**Comment by jmcdo29** [comment]
@fennperfo why do you have to call `next()`? What's the point of your controller being a middleware? The use case isn't clear to me. It seems kind of against Nest's usual standards.

**Comment by fennperfo** [comment]
@jmcdo29 then probably i am doing something wrong, my use case is only just to guard my static files, i am checking if there is authentication token, if not redirecting frontend to login page...this is my requirement. Not sure if i can use guards. Any help would be appreciated

**Comment by jmcdo29** [comment]
[Let's move this to Discord](https://discord.gg/nestjs) as it doesn't appear to be a bug.

**Comment by fennperfo** [comment]
@jmcdo29 i have joined the discord channel..should i post my issue in support-1 or support-2?

**Comment by kamilmysliwiec** [comment]
You can use either one
