### ISSUE TITLE
start --watch reloads without changes

### ISSUE THREAD

**Issue by fdorantesm** [nestjs/nest#5543]
## Current behavior
When i try to start with watching mode terminal reloads as if changes exists.

## Environment

<pre><code>
Nest version: 7.4.4
 
For Tooling issues:
- Node version: v12.8.0
- Platform:  Mac

Others:

I moved projects from folder into main MacOS Drive to secondary drive `/System/Volumes/Data` -> `/Volumes/Data`. Start works without `--watch` param.

If i move project to main drive works properly but i preffer store projects into secondary volume.
</code></pre>

[https://www.youtube.com/watch?v=_UCn_gI4_FY&feature=youtu.be](https://www.youtube.com/watch?v=_UCn_gI4_FY&feature=youtu.be)

**Comment by jmcdo29** [comment]
If I had to bet, the `tsconfig` is improperly configured, as Nest uses `tsc --watch` under the hood for watching if compilation should happen. The compilation happens, the `dist` gets modified, typescript incorrectly sees new files, restarts compilation, and you've got a loop.

Without knowing your configs and project setup, this is impossible for us to determine. Please provide a minimum reproduction that we can run on our machines to determine what is happening.

**Comment by fdorantesm** [comment]
That make sense to me.

This is my tsconfig.json
``` json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "lib": ["es2019"]
  }
}

```

But, project works fine in a directory inside main disk drive. Could it be by .DS_Store files?

**Comment by jmcdo29** [comment]
I'll re-iterate

> Without knowing your configs and project setup, this is impossible for us to determine. Please provide a minimum reproduction that we can run on our machines to determine what is happening.

If you can get us a minimum reproduction, with the exact steps that show what's going on, I'm sure we can help, but otherwise, there's not much we'll be able to do. It seems like the typescript watcher thinks something has changed after compilation for some reason. We'd need a reproduction to tell what

**Comment by fdorantesm** [comment]
I can reproduce with an empty project using `nest new nest-project` and `yarn start:dev`.

If i run in `/System/Volumes/Data/www/nest-project` works fine but if i run in another disc like `/Volumes/Data/nest-project` when both directories are in different hard disk drives.

**Comment by jmcdo29** [comment]
What would be the reproduction steps? Does `tsc --watch` show the same problem, as that's what Nest uses under the hood.

**Comment by fdorantesm** [comment]
Yep, just try to compile a typescript source project in a external hard disk drive.

**Comment by jmcdo29** [comment]
If `tsc --watch` is presenting the same problem this should be brought up with the Typescript compiler repository.
