### ISSUE TITLE
Using Fastify the GraphQL Playground does not show up

### ISSUE THREAD

**Issue by JohannesKlauss** [nestjs/nest#5544]
## Bug Report
Using Sample 23 as a basis, when I change the adapters to Fastify, the playground doesn't show up.

## Current behavior
Currently only when using express the GraphQL playground show up in the browser when opening `localhost:3000/graphql`. When we use Fastify a 400 response is returned and the error states `GET query missing.`

## Input Code
https://github.com/JohannesKlauss/nest/tree/master/sample/23-graphql-code-first

## Expected behavior
The Playground shows up no matter we use fastify or express.

## Possible Solution
I am not quite sure if this is a bug with `platform-fastify`, nest itself or `apollo-server-fastify`

## Environment
```
"dependencies": {
    "@nestjs/common": "7.4.4",
    "@nestjs/core": "7.4.4",
    "@nestjs/graphql": "7.7.0",
    "@nestjs/platform-fastify": "7.4.4",
    "apollo-server": "2.18.2",
    "apollo-server-fastify": "2.18.2",
    "class-transformer": "0.3.1",
    "class-validator": "0.12.2",
    "graphql": "15.3.0",
    "graphql-query-complexity": "0.7.0",
    "graphql-subscriptions": "1.1.0",
    "reflect-metadata": "0.1.13",
    "rxjs": "6.6.3"
},
```

**Comment by jmcdo29** [comment]
This is a problem with `apollo-server-fastify` not with Nest. It's [already logged there](https://github.com/apollographql/apollo-server/issues/4463)

**Comment by JohannesKlauss** [comment]
Oh, thank you very much!
