### ISSUE TITLE
platform-fastify doesn't work anymore with fastify-compress

### ISSUE THREAD

**Issue by EtienneGhiringhelli** [nestjs/nest#5552]
## Bug Report

When using fastify adaptater & fastify-compress for compression, it doesn't work.

## Current behavior

FastifyPlugin seems to be causing this error as it seems to be decrepated:
```ts
Argument of type 'typeof import(".../node_modules/fastify-compress/index")' is not assignable to parameter of type 'FastifyPlugin<FastifyPluginOptions>'.
  Type 'typeof import(".../nest-compress/node_modules/fastify-compress/index")' is not assignable to type 'FastifyPluginAsync<FastifyPluginOptions, Server>'.
    Type 'typeof import(".../nest-compress/node_modules/fastify-compress/index")' provides no match for the signature '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>, opts: FastifyPluginOptions): Promise<...>'
```

## Input Code

Please check this sample repo to reproduce: https://github.com/EtienneGhiringhelli/fastify-compress-issue-repo

Steps done to create this repo:
```bash
nest new nest-fastify-compress
yarn add @nestjs/platform-fastify
yarn add fastify-compress
```

Then modified main.ts file with below instructions :
https://docs.nestjs.com/techniques/performance#example
&
https://docs.nestjs.com/techniques/compression

## Expected behavior

Either the documentation is outdated and I would kindly ask for instructions or this is a bug.

## Possible Solution

No idea, sorry.

## Environment

<pre><code>
 _   _             _      ___  _____  _____  _     _____ 
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |  
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |  
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_ 
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/ 

[System Information]
OS Version     : Windows 10
NodeJS Version : v12.18.3
YARN Version    : 1.22.4 

[Nest CLI]
Nest CLI Version : 7.5.1        

[Nest Platform Information]     
platform-express version : 7.0.0
platform-fastify version : 7.4.4
common version           : 7.0.0
core version             : 7.0.0

</code></pre>

Thanks a lot !

**Comment by jmcdo29** [comment]
Looks like for Fastify V3, the compress package moved from a named export to a default export. Using `import compress from 'fastify-compress` it works as expected. Would you like to make a PR to the [docs repo](https://github.com/nestjs/docs.nestjs.com) to make a note about this?
