### ISSUE TITLE
Unexpected dependency injection when using inheritance

### ISSUE THREAD

**Issue by mikeconley12** [nestjs/nest#5553]
## Bug Report

I'm not sure if this is a bug or not, but I would like to clarify if this behavior is expected.

## Current behavior
If class providers are inherited and [child provider](https://github.com/mikeconley12/typescript-starter/blob/master/src/child.provider.ts) doesn't have `@Injectable()` decorator, but [parent provider](https://github.com/mikeconley12/typescript-starter/blob/master/src/parent.provider.ts) has this decorator, then NestJS will inject dependencies of the parent provider to the child provider.

Run the code from [this repository](https://github.com/mikeconley12/typescript-starter) and you should see something like this:

```
otherProvider ModuleRef {
  ...
}
moduleRef null
```

But `otherProvider` has type `OtherProvider`, not `ModuleRef`

## Input Code
See the [code](https://github.com/mikeconley12/typescript-starter/tree/master/src)

## Expected behavior
I expected NestJS to not inject any dependencies because the [child provider](https://github.com/mikeconley12/typescript-starter/blob/master/src/child.provider.ts) doesn't have `@Injectable()` decorator

## Environment

<pre><code>
Nest version: 7.1.1

 
For Tooling issues:
- Node version: v14.7.0
- Platform: Ubuntu

Others:

</code></pre>

**Comment by jmcdo29** [comment]
I believe this comes from how Typescript passes on metadata from parent to child, so if a parent has the `@Injectable()` decorator, the metadata is set on it. [Checkout this playground link](https://www.typescriptlang.org/play?jsx=0#code/GYVwdgxgLglg9mABAEQKYTgJwIZVQCgEoAuRAYQBtsBnatDHKLRAbwFgAoRRTVKETEnxRsmAOZ9SAMXDR4YQogC8APladu3AEqpgFdFAB01PsNESjAB0xwmUAJ6XUAGkQByACbosuVG9dQmCCohADcGogAvpzRHJwAAvQ+eEScEFS0iAAKoqhgUEmMqB7qcRyxaRnU5AAWMBQeAPLAhb4lqAAeeGAe1Tm8+a14JSwVHOk0fbn5AHK2Q8WsYxOZZHUNzXMF3kXtXXm92dNQWwsjywjUUIiWx-TKiGCoAO5HA9sMbUTh45fXEOsPPclI8XrV6k0WjsvmE0n8bsdTqgAG4PJ6vfp5E7zaHDb5wsBXRAAiFzMDA0GvNYQzY4z542FlDCEuD6QwUOBifA6PQGQwWfC3d70VyeXF+QiM5nUVmodmc7m6fTQfmmEkNEXuLz0iVSy6y+VcnnKowCoVYpHI0Xa5K6n7Sg0co1KvkC9UeMmasU6tySn6cIA) that shows the same behavior

**Comment by mikeconley12** [comment]
Yes, but I think NestJS uses [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) package to handle metadata. And this package has `.getOwnMetadata()` method:

```
// get metadata value of an own metadata key of an object or property
let result = Reflect.getOwnMetadata(metadataKey, target);
```

This method should help to fix the bug (if this is a bug).

**Comment by jmcdo29** [comment]
How would this affect things like classes that extend abstract classes that make use of dependency injection? If we use `getOwnMetadata()` would the child class not have access to the abstract class's dependencies?

**Comment by mikeconley12** [comment]
I don't know how NestJS dependency injection works, but I have some assumptions.

I think the constructor-based injection should use `Reflect.getOwnMetadata()`. And the property-based injection should use `Reflect.getMetadata()`.

So it will work for classes that extend abstract classes that make use of dependency injection.

**Comment by jmcdo29** [comment]
I'd be concerned if that became the case then things like `AuthGuard()` and `BaseExceptionFilter` would start breaking. Both of the classes, `AuthGuard()` especially, make great use of inheritance, to allow for customization.

What's the specific use case for wanting the child classes to not inherit the DI properties from the parent class?

**Comment by mikeconley12** [comment]
Perhaps I didn't make myself clear. Inheritance should only be for the property-based injection. So, `BaseExceptionFilter` and `AuthGuard` won't be broken. Inheritance of the constructor-based injection is the cause of this bug.

**Comment by jmcdo29** [comment]
The `AuthGuard()` does use constructor-based injection. It has an `@Optional()`, but it does still make use of it.

**Comment by mikeconley12** [comment]
Right, so this bug can't be fixed without breaking changes?

**Comment by jmcdo29** [comment]
I'm still not convinced it's a bug, and don't see a use case for not letting the metadata follow the inheritance chain. I'll ask again:

> What's the specific use case for wanting the child classes to not inherit the DI properties from the parent class?

**Comment by mikeconley12** [comment]
I only have one use case: to fix this issue :) If this is not a bug - ok. But I think this behavior is a bit confusing.

**Comment by kamilmysliwiec** [comment]
The current behavior is valid

**Comment by mikeconley12** [comment]
Thank you for the clarification!
