### ISSUE TITLE
Microservices: add ioredis please

### ISSUE THREAD

**Issue by wisekaa03** [nestjs/nest#5554]
## Describe the solution you'd like
in the class ClientRedis you can find the following lines:
```
redisPackage = loadPackage('redis', ClientRedis.name, () =>
      require('redis'),
    );
```
i suggest replacing them :)

## What is the motivation / use case for changing the behavior?
I want not to depend on redis

**Comment by jmcdo29** [comment]
[You can create a custom transport for this](https://dev.to/nestjs/part-1-introduction-and-setup-1a2l)

**Comment by kamilmysliwiec** [comment]
We also plan to replace `redis` with `ioredis` at some point. There's a separate, open issue where we're tracking this.

**Comment by imdurgadas** [comment]
@kamilmysliwiec Is there any ticket that we can track ?  Not having this support and writing custom transporter defeats the purpose.

**Comment by kamilmysliwiec** [comment]
@imdurgadas we're currently focusing on other priorities and we don't plan to migrate from `redis` to `ioredis` in the foreseeable future. I'd suggest creating a custom transporter for this atm
