### ISSUE TITLE
Nest build gives unexpected module resolution path when conflict with a same named folder

### ISSUE THREAD

**Issue by chigix** [nestjs/nest#5555]
## Bug Report

`nest build` will unexpectedly give a relative path for module resolution, when there is a folder in the project's root and named with the same name to one dependency module in that project.

This problem will be especially severe when organizing external services' configuration files into folders that are directly labeled with corresponding services' names.

However `tsc -p tsconfig.build.json` still give a correct path for path resolution so that this problem would not be raised through direct typescript compiling.

## Current behavior

Taking the example code provided in the next section for description,
* npm package [`sequelize`](https://www.npmjs.com/package/sequelize) is installed as the project's dependency
* There is a folder called `sequelize` under the project root.

Clone the code from this branch, https://github.com/chigix/nest/tree/build-wrong-resolution-path , and run the following scripts to finish setup and build:
```shell
$ git checkout build-wrong-resolution-path
$ npm install
$ npm run build
```
you'll see the build result in the file `dist/User.model.js` requires the dependency `sequelize` using a relational path:

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = void 0;
const sequelize_1 = require("../sequelize"); // <-- This should be the package name directly
class User extends sequelize_1.Model {
}
exports.User = User;
//# sourceMappingURL=User.model.js.map
```

## Input Code

See this branch: https://github.com/chigix/nest/tree/build-wrong-resolution-path

## Expected behavior

Because this problem is not thrown when using original typescript compiler directly, run the following script to get the compiling result from `tsc`:

```shell
$ npm run ts-build
```
the module path compiled in the result file `dist/User.model.js` is expected:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = void 0;
const sequelize_1 = require("sequelize"); // <-- This is expected
class User extends sequelize_1.Model {
}
exports.User = User;
//# sourceMappingURL=User.model.js.map
```

## Environment

<pre><code>
Nest version: 7.5.1
 
For Tooling issues:
- Node version: v12.18.4
- Platform:  Ubuntu Server 18.04

Others:

</code></pre>

**Comment by jmcdo29** [comment]
[There's a lot of discussion on this here](https://github.com/nestjs/nest-cli/issues/838) in the CLI repository. We're still looking into a fix.
