### ISSUE TITLE
DataTypeNotSupportedError: Data type "timestamptz" in "Item.createDateTime" is not supported by "mysql" database

### ISSUE THREAD

**Issue by NextZeus** [nestjs/nest#5561]
## Bug Report

[https://github.com/typeorm/typeorm/issues/6736](https://github.com/typeorm/typeorm/issues/6736)

[x] bug report

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[] `mssql`
[x] `mysql^2.18.1` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `0.2.26` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

# Code

```
# app.module.ts

TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        type: 'mysql',
        host: configService.get<string>('TYPEORM_DATABASE_HOST'),
        port: +configService.get<number>('TYPEORM_DATABASE_PORT'),
        username: configService.get<string>('TYPEORM_DATABASE_USERNAME'),
        password: configService.get<string>('TYPEORM_DATABASE_PASSWORD'),
        database: configService.get<string>('TYPEORM_DATABASE_NAME'),
        entities: [__dirname + '/**/*.entity{.ts,.js}'],
        synchronize: true,
      }),
      inject: [ConfigService],
}),

# .env.development
TYPEORM_DATABASE_HOST=localhost
TYPEORM_DATABASE_PORT=3306
TYPEORM_DATABASE_USERNAME=root
TYPEORM_DATABASE_PASSWORD=123456
TYPEORM_DATABASE_NAME=demodb


# user.entity.ts
import { Entity, PrimaryGeneratedColumn, Column, PrimaryColumn } from "typeorm";

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstname: string;

    @Column()
    lastname: string;

    @Column()
    username: string;

    @Column()
    password: string;

    @Column({ default: true })
    isActive: boolean;
}

# user.module.ts
@Module({
    imports: [TypeOrmModule.forFeature([User])],
    exports: [TypeOrmModule],
})

```

I searched 'timestamptz', it occured in postgres driver, 
[ColumnTypes.ts](https://github.com/typeorm/typeorm/blob/43a7386719280a11cfd0495748189799bc51b7d6/src/driver/types/ColumnTypes.ts)

i cannot understand why the problem came out when i used mysql driver. 
when i changed to postgres driver type, everything is fine.

ps:

i tried use 

```
TypeOrmModule.forRoot({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      username: 'root',
      password: '123456',
      database: 'nestjsdb',
      autoLoadEntities: true,
      synchronize: true,
    }),
```
this works.

[code here](https://github.com/NextZeus/hellonestjs)

**Comment by constb** [comment]
@NextZeus 

Your error description mentions `Item.createDateTime` but I don't see it in the code you provided. If I had to guess, I'd probably say that `entities: [__dirname + '/**/*.entity{.ts,.js}'],` in config captures some extraneous entity files by accident, since `**` matched all deeply nested folders, and there is some entity somewhere deep, in a random file that matches the wildcard. And this entity file is not mysql compatible.

`autoLoadEntities` works differently. It relies on you importing and specifying particular entities through `.forFeature()` module imports. It doesn't care about paths and it doesn't load any random unused files.

**Comment by NextZeus** [comment]
@constb Thanks a lot, i tried to fix  entities: [__dirname + '/users/entity/*.entity{.ts,.js}'], everything was fine.  ** should be used carefuly.

**Comment by dileepainivossl** [comment]
When using autoloadentities error still occures

```
 TypeOrmModule.forRoot({
      type: 'mssql',
      host: 'localhost',
      port: 1433,
      username: 'localuser',
      password: 'user123',
      database: 'testdb',
      synchronize: true,
      options: {
        encrypt: false,
      },
      autoLoadEntities: true,
    }),
```

![image](https://github.com/nestjs/nest/assets/124654997/2c6e28c1-0ee1-4cd8-90ae-38bd3358dbe9)
