### ISSUE TITLE
HttpService - Delete method does not include data - even if it's included in data config.

### ISSUE THREAD

**Issue by iteratelance** [nestjs/nest#5569]
## Current behavior
When making delete request the data is not added to the request.

## Input Code
Please note that config is the second argument for delete request per axios documentation.
https://github.com/axios/axios/issues/897 - this is not the cause of this bug. I think it has something to do with http.service.js makeObservable

```ts
const res = await this.httpService.delete<any>('/url', {data: body, headers: {}}).toPromise();
```

## Expected behavior
Should append data to the request body.

## Workaround
```ts
    const config = {
      url: '/url',
      method: 'delete' as Method,
      headers: {}
      data: {some_payload: {}}
    };
const res = await this.httpService.request<any>(config).toPromise();
```

## Environment

<pre><code>
Nest version: 7.4.4

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by constb** [comment]
@iteratelance 

AFAIK, this should be like that:

```typescript
const res = await this.httpService.delete<any>('/url', body, {headers: {}}).toPromise();
```

**Comment by nrayburn-tech** [comment]
I think that this is related to an issue with Axios.

I am not sure what version of Axios that nest uses, but here is a related issue from the Axios repo, https://github.com/axios/axios/issues/3220.
This https://github.com/axios/axios/pull/3282 fixes that issue, and is expected to be in the next release.

**Comment by iteratelance** [comment]
> @iteratelance
> 
> AFAIK, this should be like that:
> 
> ```ts
> const res = await this.httpService.delete<any>('/url', body, {headers: {}}).toPromise();
> ```

@constb thanks for the reply.  I tried that format as well.  According to the old docs for axios body is not accepted as an argument and most be passed as a config value when using the .delete method. https://github.com/axios/axios/issues/897

Really appreciate the support from you all.

**Comment by jasonsaayman** [comment]
Hi,

Version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks
