### ISSUE TITLE
HTTP/EXpress multiple process

### ISSUE THREAD

**Issue by nileshdattatraykedare** [nestjs/nest#557]
Hi @kamilmysliwiec is it possible to create multiple process of http/express. If not can I create something which is easily possible in express

for example
<code>
throng({
    workers: workers,
    master: startMaster,
    start: startWorker,
    lifetime: Infinity
});

function startMaster() {
}

function startWorker(id) {
    mainServerCode();
}

function mainServerCode() {
    var express = require('express');
    var app     = express();
    var port    =   process.env.PORT || 5050;

    var apiRouter = require('./api/index');

    var bodyParser = require('body-parser');
    var compression = require('compression');

    app.use(bodyParser.json({limit: "100mb"}));
    app.use(bodyParser.urlencoded({ limit: "100mb", extended: false }));

    app.use(compression());

    app.use('/api', apiRouter);

    app.get('/loaderio-98736a46c23210f0f8117186a58efbfb', function (req, res) {
        res.send('loaderio-98736a46c23210f0f8117186a58efbfb');
    });

    app.listen(port, function () {
        console.log('server is running on 5050')
    });
}

</code>

**Comment by kamilmysliwiec** [comment]
Please, use ISSUE_TEMPLATE. I cannot help when the code snippets are broken (it's very difficult to read).
