### ISSUE TITLE
Implement strategy pattern with Nest js

### ISSUE THREAD

**Issue by Aakash-sanandiya** [nestjs/nest#5573]
Hello everyone, hope you all are doing well. And, amazing work guys, this frame work makes life easy. As title suggests, posting here after lots of digging around to implement simple strategy pattern with NestJs. Yes, there has been given [an example in official docs ](https://docs.nestjs.com/v6/fundamentals/custom-providers#custom-providers-1). 

> What I want to implement

**I want to implement something exact same. In may case, I have an interface (abstraction) to which 2 other classes implements. Any class depends on this interface will inject an instance of any one of the classes which implements it.** 

To achieve above, what I have done is:
1. Created an interface with definition of the methods 
2. Created 2 classes(services) which implements this interface
3. Created custom provider which can accept a **type** parameter and decides which implementation to inject accordingly using useFactory.
OK, this much works perfect, when I use this provider in any module to inject any class from 2, but I have to pass that **type** in to provider method hard code. I want to make it dynamically. I am aware that I can inject another providers to useFactory. The problem here is that, I will be able to know what **type** it will be from the API params.
Thus, I need to have an access of API param to this provider or to module class where I am using this provider. 

To Illustrate, 
I have,
1 interface named **ISecAvailQuesGetter**
`export interface ISecAvailQuesGetter {
    findQuesBySection: (section: Section) => Promise<Question[]>;
}`

2 classes named **SecGenAvailQuesGetterService** and **SecWithModAvailQuesGetterService**, both these implements **ISecAvailQuesGetter**
`export class SecGenAvailQuesGetterService implements ISecAvailQuesGetter{
    findQuesBySection = (section: Section): Promise<Question[]> => {
        return Question.findBySection(section);
    }
}`

`export class SecWithModAvailQuesGetterService implements ISecAvailQuesGetter {
    findQuesBySection = (section: Section): Promise<Question[]> => {
        return Question.findBySectionWithModules(section);
    }
}`
3 provider named **SecAvailQuesGetterProvider** which accepts argument **type** and returns any class accordingly.
`export const SecAvailQuesGetterProvider = (type: string) => {
    return {
        provide: "SecAvailQuesGetter",
        useFactory: () => {
            switch (type) {
                case "section":
                    return new SecGenAvailQuesGetterService();
                    break;
                case "module":
                    return new SecWithModAvailQuesGetterService();
                    break;
            }
        }
    };
}`
4 A controller named **KeyGenerator** depends on **ISecAvailQuesGetter** for path **generate-key/{testId}**

Now, here I will be able to know type by fetching test record by testId and accordingly class should be injected.

I hope I wrote enough to understand the concern and please ask without hesitation if anything is unclear. Thanks

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
