### ISSUE TITLE
Pattern information in Mqtt publish function - ClientMqtt.emit 

### ISSUE THREAD

**Issue by skteiche** [nestjs/nest#5574]
## Bug Report
I just want to send the data to a broker, not with the pattern.

## Current behavior
I am not sure, if this is a bug. But if I want to publish data on a Mqtt Broker, the Broker gets a JSON object with pattern and data

{
  "pattern": "test/test",
  "data": "Data is here"
}

Here a screenshot of Mqtt Explorer:

![image](https://user-images.githubusercontent.com/72961713/96217394-c4fcd080-0f82-11eb-8c22-2f38dabbbce2.png)

## Input Code

```ts
  @Client({
    transport: Transport.MQTT,
    options: {
      url: 'mqtt://localhost:11883',
    },
  })
  public clientMq: ClientMqtt;

  public async onModuleInit(): Promise<void> {
    this.sendMessage();
  }

  public async sendMessage(): Promise<any> {
    await this.clientMq.emit('test/test', 'Data is here');
  }


```

## Expected behavior

I just want the data, not an JSON object with pattern and data

![image](https://user-images.githubusercontent.com/72961713/96217486-f9708c80-0f82-11eb-8e53-445f028b6cee.png)

## Possible Solution

Maybe there is any options to suppress this behaviour. 

## Environment

<pre><code>
Nest version: 7.0.0
 
For Tooling issues:
- Node version: v12.18.3
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
> I just want the data, not an JSON object with pattern and data

In this case, you should use `mqtt` client directly instead of using the `ClientMqtt` proxy. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by tuankietkaito** [comment]
> > I just want the data, not an JSON object with pattern and data
> 
> In this case, you should use `mqtt` client directly instead of using the `ClientMqtt` proxy.
> Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

I found that in the `ClientMqtt` proxy source code, method `publish` is to publish all the `partialPacket` which is the JSON `{pattern, data}` rather than only `packet.data`
```
protected publish(
    partialPacket: ReadPacket,
    callback: (packet: WritePacket) => any,
  ): Function {
    try {
      const packet = this.assignPacketId(partialPacket);
      const pattern = this.normalizePattern(partialPacket.pattern);

      ...
        this.mqttClient.publish(
          this.getAckPatternName(pattern),
          JSON.stringify(packet),
        );
      });
      ...
  }
```
So if I just want to use `ClientMqtt` porxy but just only publish the `data` field of the packet, how can I do so?
