### ISSUE TITLE
new FastifyAdapter() throw error - > No overload matches this call

### ISSUE THREAD

**Issue by johnico** [nestjs/nest#5582]
## Bug Report

Error is thrown via vsCode 
tried to align the versions number with nestjs but it does not work

## Current behavior
`
	"message": "No overload matches this call.\n  Overload 1 of 2, '(module: any, options?: NestApplicationOptions): Promise<NestFastifyApplication>', gave the following error.\n    Type 'FastifyAdapter<Server, IncomingMessage, ServerResponse>' has no properties in common with type 'NestApplicationOptions'.\n  Overload 2 of 2, '(module: any, `
## Input Code

```
async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter()
  ); ..........

```

tsconfig 

```ts
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": false,
    "noLib": false,
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "types": ["node", "jest"],
    "incremental": true,
    "paths": {
        "*": ["types/*"],
        "@app/*": ["*"],
    }
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
  
```

## Environment

```
  "dependencies": {
    "@nestjs/common": "7.4.4",
    "@nestjs/core": "7.4.4",
    "@nestjs/platform-fastify": "7.4.4",
    "@nestjs/swagger": "^4.6.1",
    "@nestjs/mongoose": "^7.0.2",
    "@nestjs/terminus": "^7.0.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "fastify-swagger": "^3.4.0",
    "mongoose": "^5.10.9",
    "rxjs": "^6.6.3"
  },
```
 
For Tooling issues:
- Node version: v10.16.0
- Platform:  Mac

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by jeremycastanza** [comment]
@johnico - I was able to resolve this by importing `NestApplicationOptions` from `@nestjs/common` and typecasting the create parameter like so:

```new FastifyAdapter() as NestApplicationOptions```

Hope this helps.
