### ISSUE TITLE
File Upload Validation on the basis of non-file Form Field

### ISSUE THREAD

**Issue by manishg345** [nestjs/nest#5584]
## Current behavior
Multer package throws exception while throwing HttpException to validate file upload on the basis of non-file form field as below:

 ...\dist\interceptors\file-interceptor.js:33
                    throw new common_1.HttpException({
                    ^

HttpException [Error]: Allowed Category Types: meeting,user-profile
    at ...\dist\interceptors\file-interceptor.js:33:27
    at Immediate.<anonymous> (...\node_modules\multer\lib\make-middleware.js:53:37)      
    at processImmediate (internal/timers.js:458:21)
    at process.topLevelDomainCallback (domain.js:137:15) {
  response: {
    status: false,
    error: 'Invalid Category',
    message: 'Allowed Category Types: meeting,user-profile',
    code: 1002
  },
  status: 400
}
## Input Code

```
async intercept(
        context: ExecutionContext,
        next: CallHandler,
      ): Promise<Observable<any>> {
        const ctx = context.switchToHttp();
  
        await new Promise((resolve, reject) =>
          this.multer.single(fieldName)(
            ctx.getRequest(),
            ctx.getResponse(),
            (err: any) => {
                let categoryTypes  = ['meeting','user-profile'];
                const obj = JSON.parse(JSON.stringify(ctx.getRequest().body))
                
                if(!categoryTypes.includes(obj.category)){
                    console.log('hello');
                     throw new HttpException(
                       {
                         status: false,
                         error: 'Invalid Category',
                         message: 'Allowed Category Types: '+categoryTypes.toString(),
                         code: 1002
                       },
                       HttpStatus.BAD_REQUEST,
                     );
                    }
              if (err) {
                const error = transformException(err);
                return reject(error);
              }
              resolve();
            },
          ),
        );
        
        return next.handle();
      }
```

## Expected behavior
Multer module should not crash while throwing HttpException and the output must be as per thrown HttpException

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by manishg345** [comment]
The issue got fixed. https://github.com/expressjs/multer/issues/299
