### ISSUE TITLE
Order of all "onApplicationBootstrap" methods to be fired

### ISSUE THREAD

**Issue by sarpt** [nestjs/nest#5585]
Hi,
I've come across an use-case where a specific "onApplicationBootstrap" method on a service class requires other "onApplicationBootstrap" method on another service class to be already finished to end successfully. 
I can't find information whether there is an order defined to the execution of all registered "onApplicationBootstrap" methods, but from what I can observe there may be none since some "onApplicationBootstrap" methods end faster, even though the services they belong to are after the others in a module's provider list (and the one ending sooner is actually dependent in DI on the one ending later), suggesting that it's not something controlled.

Is there a way to influence (preferably ensure) that one "onApplicationBootstrap" (or any other same-hook method) will always finish before the other using purely nestjs framework-related mechanisms?

Edit:
Looking at the source code I can see that `Promise.all()` is being used by `callModuleBootstrapHook`, so I assume the only ensured order of finishing the providers hooks is that under the same module the hooks on transient instances will finish faster than on the non-transient ones, but the same type hooks will finish in whatever order.

**Comment by kamilmysliwiec** [comment]
See this issue https://github.com/nestjs/nest/issues/4599 for more info :)
