### ISSUE TITLE
Accept abstract class as argument in INestApplicationContext.resolve()

### ISSUE THREAD

**Issue by gangajogur** [nestjs/nest#5586]
## Is your feature request related to a problem? Please describe.
INestApplicationContext.resolve() does not accept Abstract classes (like .get() does)

## Describe the solution you'd like
It would be great if resolve also accepts of type `Abstract<TInput>`

## Teachability, Documentation, Adoption, Migration Strategy
The solution can be used something like below:

`dataServiceMock = await module.resolve(DataProviderService, contextId)`

where `DataProviderService` is an abstract class

## What is the motivation / use case for changing the behavior?
Better unit testing capabilities without having to change the concrete implementation of the code.

**Comment by jmcdo29** [comment]
I believe `resolve` works based off the injection token. Can you provide a minimum reproduction showing what's not working?

**Comment by gangajogur** [comment]
Hi Jay,

I've created a repo that demonstrates the problem.

https://github.com/gangajogur/nestjs-abstract-resolve

The interesting bits are on line 30 of app.controller.spec.ts. 

Please let me know if my comments are not quite clear.

Thanks heaps.

**Comment by jmcdo29** [comment]
Yep, I can definitely see the error you're receiving. It's definitely stemming from Typescript's `abstract` vs `non-abstract` class definitions. Interestingly enough, when I do `AbstractService.name` instead, I still receive a test failure, so I'll try to look into that. @kamilmysliwiec any thoughts about how to allow `resolve` to take in an `abstract` class?

**Comment by gangajogur** [comment]
This might be to do with differences in how `resolve` signature difference between NestApplicationContext and INestApplicationContext

INestApplicationContext seems to have the additional `Abstract<TInput>` type for the `typeOrToken`.

```
INestApplicationContext:
    resolve<TInput = any, TResult = TInput>(typeOrToken: Type<TInput> | Abstract<TInput> | string | symbol, contextId?: {
        id: number;
    }, options?: {
        strict: boolean;
    }): Promise<TResult>;
```

```
NestApplicationContext
    resolve<TInput = any, TResult = TInput>(typeOrToken: Type<TInput> | string | symbol, contextId?: ContextId, options?: {
        strict: boolean;
    }): Promise<TResult>;
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this @gangajogur? Updating a method signature should be enough

**Comment by gangajogur** [comment]
Yes, absolutely. I will create a PR for this. Also, wondering if there are units tests that I need to update/create?

**Comment by kamilmysliwiec** [comment]
> Also, wondering if there are units tests that I need to update/create?

Nope. Updating a method signature should be fine

**Comment by kamilmysliwiec** [comment]
Ping @gangajogur 🏓
