### ISSUE TITLE
[BUG]example '05-sql-typeorm' can not run with ts-node -r tsconfig-paths/register src/main.ts

### ISSUE THREAD

**Issue by fewiki** [nestjs/nest#559]
example '05-sql-typeorm' can not run with ts-node -r tsconfig-paths/register src/main.ts

process result:

![image](https://user-images.githubusercontent.com/13325335/38659199-fb00d006-3e5a-11e8-8768-0744a996f59a.png)

Can not find module， but run with node index.js is OK.
Thanks~

**Comment by kamilmysliwiec** [comment]
We need a bit more context here.
