### ISSUE TITLE
Auto Attach debugging not working with Nx and Visual Studio Code

### ISSUE THREAD

**Issue by rhyek** [nestjs/nest#5590]
## Current behavior
In a new nx project with nest preset, after setting a breakpoint somewhere and configuring Visual Studio Code's `Debug -> JavaScript -> Auto Attach Filter` with several configurations, the application will not start and the breakpoint will not hit when running `nx serve`. It does not matter wether I enable or disable `Debug -> JavaScript -> Use Preview`.

Different values for the auto attach setting have the following results:
`always`
![image](https://user-images.githubusercontent.com/702922/96661327-07b70380-1309-11eb-914f-2cb534b7215b.png)

`smart`
![image](https://user-images.githubusercontent.com/702922/96661381-23220e80-1309-11eb-822d-51b0c2f78231.png)

`onlyWithFlag`
![image](https://user-images.githubusercontent.com/702922/96661429-45b42780-1309-11eb-8792-e40630b2fc39.png)

`disabled`
![image](https://user-images.githubusercontent.com/702922/96661469-59f82480-1309-11eb-87e9-c5e46a37f7ad.png)

## Expected behavior
The application should start and breakpoints should break processing. This was working up until recently. I am not entirely sure, but I believe up until at least 1 month ago it was working fine.

Having a project with *just* NestJS does work with Visual Studio Code's auto attach debugging.

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: 14.13.1
- Platform: Mac

Others:

"@nrwl/nest": "10.3.1",
</code>
</pre>

**Comment by jmcdo29** [comment]
If this works fine with nest in it's own it should be reported to the appropriate Nx repository.

**Comment by rhyek** [comment]
> If this works fine with nest in it's own it should be reported to the appropriate Nx repository.

Ok, that makes sense, but I've seen issues related to Nx here in the past. Feel free to close this one if necessary. I opened a new one in the nx repo.

**Comment by jmcdo29** [comment]
Yeah, sometimes Nx issues will hang around here. This seems like a problem specifically with their build and serve step

**Comment by kamilmysliwiec** [comment]
Please, report this issue in Nx repository.
