### ISSUE TITLE
ExceptionFilter fires twice

### ISSUE THREAD

**Issue by Aragur** [nestjs/nest#5592]
## Current behavior

ExceptionFilter's @Catch fires twice, so double Console Output is created.

## Input Code

See this Repository: https://github.com/Aragur/bug-exception-filter

## Expected behavior
ExceptionFilter should run only once, so no double console output should be present.

## Possible Solution

Sorry I have no idea..

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: 14.14.0
- Platform:  Linux
Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by Aragur** [comment]
Done: https://github.com/Aragur/bug-exception-filter

**Comment by jmcdo29** [comment]
Looks like this is specifically for the Fastify adapter. Probably related (to an extent) with Fastify v3 vs Fastify v2. I'll dig more into this soon. Thanks for the reproduction 😄

**Comment by code-coffee-sleep** [comment]
@jmcdo29 
This is not only for Fastify, i faced with this issue in Express mode too

**Comment by jmcdo29** [comment]
@code-coffee-sleep you wanna get me a reproduction for that? Because the above reproduction provided by Aragur only fires twice with Fastify.

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be an issue with NestJS. Fastify triggers a global error handler every time you call `response.send(error)` in which `error` is an instance of the `Error` class (or any class that inherits from `Error`) - that's exactly what happens in your `ApiFilter`.

**Comment by zanpen2000** [comment]
@Aragur 你好，我也遇到了同样的问题，并且找到了原因，[how-to-handle-errors-in-exception-filters-with-fastify-nestjs](https://stackoverflow.com/questions/70594497/how-to-handle-errors-in-exception-filters-with-fastify-nestjs)
```javascript
const exceptionResponse = exception.getResponse(); // ==> HERE!!!
const status = exception.getStatus();
const error =
	typeof resp === 'string'
		? { message: exceptionResponse }
		: (exceptionResponse as object);
resp.status(status).send(error);
```

**Comment by harshagarwal00** [comment]
As mentioned by @zanpen2000 :
dont rethrow same exception caught by ExceptionFilter

for example below code works great:

`import { ExceptionFilter, Catch, ArgumentsHost, HttpException } from '@nestjs/common';
import { FastifyRequest, FastifyReply } from 'fastify';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const request: any = ctx.getRequest();
    const response: FastifyReply = ctx.getResponse();

    const exceptionResponse = exception.getResponse();
    const status = exception.getStatus();
    const error =
      typeof exceptionResponse === 'string'
        ? { message: exceptionResponse }
        : (exceptionResponse as object);
    console.log("EXCEPTION THROWN WITH STATUS: " + status);
    response.status(status).send(error);
  }
}`
