### ISSUE TITLE
CLI - generate service in a module with different name

### ISSUE THREAD

**Issue by llezhava** [nestjs/nest#5593]
## Feature Request

I want to have two services in my module named "topics".
topics.service.ts and topics.database.service.ts

I can generate topics.service.ts using the CLI tool, but for another one, I have to create it manually.

Can you add another property, which will indicate the module in which I want given service?

like:
nest g service topics:topics.database

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
