### ISSUE TITLE
CONTEXT injection do not work

### ISSUE THREAD

**Issue by izquierdogalan** [nestjs/nest#5596]
## Current behavior

context is udefined
## Input Code

 
```ts
 constructor(
    private queryBus: QueryBus,
    @Inject(CONTEXT) private readonly context: any
  ) {
  }
```

## Expected behavior

I need receive param created in context with GraphQL

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction. If you're working with CQRS, you cannot do REQUEST scoped injections.

**Comment by izquierdogalan** [comment]
Thanks @jmcdo29 I appreciate your help, you are right it was CQRS. Thinking about that I guess it is a good aproach, not coupling CQRS with REQUEST or CONTEXT.
