### ISSUE TITLE
Support transaction per request with TypeORM 

### ISSUE THREAD

**Issue by shusson** [nestjs/nest#560]
<pre><code>
[x] Feature request
</code></pre>

## What is the motivation / use case for changing the behavior?
We would like to make all TypeORM database operations during a certain request/endpoint transactional. Based on https://github.com/typeorm/typeorm/issues/404#issuecomment-295855913 we could create a transactional entity manager and pass it around to all our services, but that doesn't feel very nestjs like. More recently @pleerock suggested the use of `scoped services` in https://github.com/typeorm/typeorm/issues/1895#issuecomment-380556498 which would enable a transaction-per-request and use the same transaction manager instance across all services without having to pass it around. A concrete example is in this [doc](https://github.com/typestack/typedi#using-multiple-containers-and-scoped-containers).

Are `scoped services` something that the nestjs team has thought about implementing?

Is there a better way of handling TypeORM transactions in nestjs? Keeping in mind that custom repositories [should not be singleton services](https://github.com/typeorm/typeorm/issues/404) and it is likely transaction decorators will be [removed from TypeORM core](https://github.com/typeorm/typeorm/issues/1895#issuecomment-380419156).

For example: 

UserController.ts
```typescript
@Controller("/user")
export class UserController {
    constructor(
        private userService: UserService,
    ) {}

    @Post("/")
    @Transaction()
    async createNewUser(@Body() body: UserDTO) {        
        return await this.userService.createNewUser(body);
    }
}
```

UserService.ts
```typescript
@Component()
export class UserService {
    constructor(private userRepository: UserRepository) {}

    async createNewUser(userDTO: UserDTO): Promise<User> {
        const user = new User();
        user.username = userDTO.username;
        ...

        const saved = await this.userRepository.save(user);

        await this.userRepository
            .createQueryBuilder()
            .relation(User, "departments")
            .of(saved)
            .add(userDTO.departmentIds);

        return saved;
    }
}
```
Where the dependency injected `userRepository` automagically is using the transactional entity manager under the hood.

**Comment by shusson** [comment]
Thanks @nicomouss, @kamilmysliwiec is there any interest in implementing something like this in nestjs core?

**Comment by icepeng** [comment]
I think this feature should be implemented in https://github.com/nestjs/typeorm not the nestjs core.

**Comment by shusson** [comment]
@icepeng Yeah happy to move it, but I think the discussion has implications on nestjs core, i.e `scoped services`.

**Comment by kamilmysliwiec** [comment]
Hey @shusson,
In terms of `scoped services`, I have mixed feelings. Nest has a complex modules container, meaning, each time when the request hits our app, we would have to mount modules, resolve all relationships between providers (including async providers, such as database connection), and then attach them to the particular request. It's not only about resolving a set of services making it much more complicated.

However, what we definitely want to provide is a support for async hooks once they hit a stable release. With async hooks, we could create a kind of 'request bag' that could be easily accessed by each provider/controller/anything, in order to set/get any value that concerns only processed request. That will enable us to provide a way to handle with, for example, transactions-per-request feature. Nevertheless, the `async-hooks` are still in experimental phase.

**Comment by shusson** [comment]
Thanks for the update @kamilmysliwiec, `async-hooks` sounds like a promising way forward.

**Comment by kamilmysliwiec** [comment]
We'll get back to this feature once `async-hooks` functionality moves into *stable* API.

**Comment by odavid** [comment]
Hi All,
I've created a small project that adds a Spring Style Transactional Decorator and can control propagation.
See https://github.com/odavid/typeorm-trasactional-cls-hooked

Hope this helps,
Ohad

**Comment by hangdonchoi** [comment]
> Hi All,
> I've created a small project that adds a Spring Style Transactional Decorator and can control propagation.
> See https://github.com/odavid/typeorm-transactional-cls-hooked
> 
> Hope this helps,
> Ohad

I really find this solution ^^ thanks alot

**Comment by hangdonchoi** [comment]
> Hi All,
> I've created a small project that adds a Spring Style Transactional Decorator and can control propagation.
> See https://github.com/odavid/typeorm-transactional-cls-hooked
> 
> Hope this helps,
> Ohad

I am finding this solution now!!! thanks alot!

**Comment by nicolae536** [comment]
> I tested the aproach above with Jmeter using concurent request and the application breaks, I also switched to cls-hooked. The described case it happens

_-> reuqest -> change the entityManager1 -> start transaction -> await a select operation from the db
-> another request -> change the entityManager2 -> await another select operation from the db -> now the first select is ready to be continue so we resume that callback -> the current entityManger is not entityManager1 it's entityManager2_
