### ISSUE TITLE
NestJS doesn't instantiate a Provider at the start of the application if the provider has a circular dependency

### ISSUE THREAD

**Issue by DavideCarvalho** [nestjs/nest#5600]
## Current behavior

If two services have circular dependency, NestJS doesn't instantiate them at the start of the application. This is a problem, since in my Open Source project, we usePubSubJS to separate the gamefication logic from the rest of the app, and since NestJS cannot instantiate the gamefication services at the start of the application, we cannot start listening to those events. Neither constructor or onModuleInit works.

## Input Code

Repl: 
https://codesandbox.io/s/wonderful-fog-duhiq

but if you guys want to see our code, here it is: 
https://github.com/DavideCarvalho/newschool-backend/tree/feature/gamefication-invite-users

## Expected behavior

All the classes should be available at the start of the application.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Looking at your codesandbox link, I see in the terminal this:
![cir-dep-start](https://user-images.githubusercontent.com/28268680/97089169-ebf27c80-15ea-11eb-8d00-b17d8f5b38e4.png)

This looks like the services are being started up before the server fully starts and is listening. Is there something I'm not seeing here?

**Comment by DavideCarvalho** [comment]
I'm trying to create a more closer reproduction from what we are having on our project, will create another bug as soon as I can reproduce on codesandbox

**Comment by jmcdo29** [comment]
If possible a git repo would be best, just for the ease of running and modifying locally. 

I have a guess that it may be due to request scoping of providers, as those providers would not be instantiated until a request comes in. Don't forget about the [scope hierarchy](https://docs.nestjs.com/fundamentals/injection-scopes#scope-hierarchy)

**Comment by DavideCarvalho** [comment]
Was working on the project, and everything worked fine when I used property based injection. Tomorrow I'll try to create a github project so you guys can take a look
