### ISSUE TITLE
Microservice payload decorator is not working very well

### ISSUE THREAD

**Issue by smhmayboudi** [nestjs/nest#5601]
## Current behavior

The payload return the value instead of value.value

## Input Code

```ts
  @MessagePattern(USER_FIND_BY_USERNAME)
  findOneByUsername(
    @Payload() dto: UserFindOneByUsernameReqDto
  ): Promise<UserResDto | undefined> {
    return this.userService.findOneByUsername(dto);
  }
```
receiving this message:
```ts
{
  magicByte: 2,
  attributes: 0,
  timestamp: '1603482181562',
  offset: '10',
  key: null,
  value: { username: 'smhmayboudi' },
  headers: {
    kafka_correlationId: 'e8f751b4-109e-41ff-87be-5f6f549e7711',
    kafka_replyTopic: 'USER_SERVICE_FIND_BY_USERNAME.reply',
    kafka_replyPartition: '0'
  },
  isControlRecord: false,
  batchContext: {
    firstOffset: '10',
    firstTimestamp: '1603482181562',
    partitionLeaderEpoch: 0,
    inTransaction: false,
    isControlBatch: false,
    lastOffsetDelta: 0,
    producerId: '-1',
    producerEpoch: 0,
    firstSequence: 0,
    maxTimestamp: '1603482181562',
    timestampType: 0,
    magicByte: 2
  },
  topic: 'USER_SERVICE_FIND_BY_USERNAME',
  partition: 0
}
```

## Expected behavior

The payload should only return the value part as the dto.

## Possible Solution

```ts
import { ArgumentMetadata, Injectable, PipeTransform } from "@nestjs/common";

@Injectable()
export class PayloadPipe implements PipeTransform {
  transform(value: any, _metadata: ArgumentMetadata): any {
    return value.value;
  }
}
...
  @MessagePattern(USER_FIND_BY_USERNAME)
  findOneByUsername(
    @Payload(PayloadPipe) dto: UserFindOneByUsernameReqDto
  ): Promise<UserResDto | undefined> {
    return this.userService.findOneByUsername(dto);
  }
```

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: v12.19.0 
- Platform:  Mac 

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by smhmayboudi** [comment]
Thanks in advance for your supports.

I port my project from Redis transport to Kafka transport and find out the payload is not the same as the old one. I put the console log in the user service to check it. Please follow the readme.

https://github.com/smhmayboudi/nestjs-kafkajs-payload

**Comment by smhmayboudi** [comment]
@jmcdo29 @kamilmysliwiec Thanks in advance for your supports.

I port my project from Redis transport to Kafka transport and find out the payload is not the same as the old one. I put the console log in the user service to check it. Please follow the readme.

https://github.com/smhmayboudi/nestjs-kafkajs-payload
