### ISSUE TITLE
Import multi typeorm options by configure should been array type

### ISSUE THREAD

**Issue by lichnow** [nestjs/nest#5602]
I has database provider, and the `db.getOptions` function in it will get all options by `ConfigModule` for every connect,but `TypeOrmModuleAsyncOptions` is not array type...
```typescript
@Module({
    imports: [ 
        TypeOrmModule.forRootAsync({
                useFactory: (db: Database) =>  db.getOptions(),
                inject: [Database],
            })
    ]
})
export class AppModule{}
```
now I  have to manually add each option,
```typescript
@Module({
    imports: [ 
        TypeOrmModule.forRootAsync({
                useFactory: (db: Database) =>  db.getOptions()[0],
                inject: [Database],
            }),
       TypeOrmModule.forRootAsync({
                useFactory: (db: Database) =>  db.getOptions()[1],
                inject: [Database],
            })
    ]
})
export class AppModule{}
```

**Comment by jmcdo29** [comment]
Would you like to open a PR to make this possible? And keep the existing functionality as well as to be backwards compatible.

**Comment by lichnow** [comment]
@jmcdo29 thx,not needed for now,I rewrite a configuration module,it can been used for yargs cli,every provider been inject after `new` it and inited by config.so in yargs cli it can be used flexibly ^v^
