### ISSUE TITLE
forwardRef module and queue breaks service injection?

### ISSUE THREAD

**Issue by incompletude** [nestjs/nest#5604]
# Bug Report
Not sure if it s a bug or I'm missing something.

## Current behavior
forwardRef module and queue breaks service injection?

## Input Code
I have a UserService that contains multiple circular dependencies with other modules. I can't inject the service along with a queue (UserService is undefined error). If I remove the queue injection, the UserService works.

```ts
@Module({
  imports: [
    BullModule.registerQueue({
      name: "transactional",
      redis: {
        host: EnvConfig.REDIS_HOST,
        port: EnvConfig.REDIS_PORT,
      },
      defaultJobOptions: {
        attempts: 1,
        removeOnComplete: true,
        removeOnFail: false,
      },
    }),
    EmailSenderModule,
    SMSSenderModule,
    ValidationCodeModule,
    forwardRef(() => UserModule),
    NaturalModule,
    ContactModule,
  ],
  providers: [TransactionalService, TransactionalConsumer],
  exports: [TransactionalService],
})
export class TransactionalModule {}
```

```
Injectable()
export class TransactionalService {
  public constructor(
    @InjectQueue("transactional")
    private readonly transactionalQueue: Queue,
    private readonly userService: UserService, // todo: cant inject this in transactional service?
  ) {}

  public async addToQueue(id: number, type: EmailEnum): Promise<boolean> {
    await this.transactionalQueue.add(type, {
      payload: id,
    })

    return true
  }
}

```

## Environment
LTS

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by incompletude** [comment]
here it goes

[connect.zip](https://github.com/nestjs/nest/files/5440372/connect.zip)

**Comment by jmcdo29** [comment]
You need to use `@Inject(forwardRef())` on the services as well as the modules.

Please take any further questions to our [Discord server](https://discord.gg/nestjs) as we are using GitHub for Bug Reports, Regressions, and Feature Requests.
