### ISSUE TITLE
Incorrect CustomOrigin type definition 

### ISSUE THREAD

**Issue by ea-tal** [nestjs/nest#5606]
## Current behavior
current declaration is:

```ts
export declare type CustomOrigin = (requestOrigin: string, callback: (err: Error | null, allow?: boolean) => void) => void;
```

## Expected behavior
According to the [doc](https://github.com/expressjs/cors#configuration-options): 
_... and a callback (called as callback(err, origin), where origin is a non-function value of the origin option) as the second._

## Possible Solution
```ts
export declare type CustomOrigin = (requestOrigin: string, callback: (err: Error | null, origin?:  boolean | string | RegExp | (string | RegExp)[]) => void) => void;
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
