### ISSUE TITLE
FastifyError: Content type parser 'multipart' already present. and Unsupported Media Type: multipart/form-data;

### ISSUE THREAD

**Issue by JohannesKlauss** [nestjs/nest#5607]
## Current behavior
Using the fastify adapter I need to support multipart file upload.
But when I try to upload a file, Fastify states `FastifyError: Unsupported Media Type: multipart/form-data`. When I am using the `fastify-multipart` package and register it, then the following error gets thrown: `FastifyError: Content type parser 'multipart' already present.`

So no matter what I am doing, I can't upload a file.

## Input Code
This is my main.ts

```ts
import fastifyMultipart from 'fastify-multipart';

async function bootstrap() {
  const adapter = new FastifyAdapter({
    logger: true,
  });

  adapter.register(fastifyMultipart, {
    limits: {
      fieldNameSize: 100, // Max field name size in bytes
      fieldSize: 1000000, // Max field value size in bytes
      fields: 10,         // Max number of non-file fields
      fileSize: 100,      // For multipart forms, the max file size
      files: 1,           // Max number of file fields
      headerPairs: 2000,   // Max number of header key=>value pairs
    },
  });

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    adapter,
  );

  // .... rest is just basic standard stuff
```

This is my files controller:

```ts
import { Controller, Post, Request } from '@nestjs/common';

@Controller('files')
export class FilesController {
  @Post('upload')
  uploadFile(@Request() req) {
    console.log(req.multipart());

    return 'ok';
  }
}

```

## Expected behavior
With one way I should be able to upload a file. I don't know if this is a bug in NestJS or Fastify or the adapter.

## Environment

Nest version: 7.4.4

**Comment by jmcdo29** [comment]
Similar issue as to [nestjs/typescript#655](https://github.com/nestjs/typeorm/issues/655) and [nestjs/swagger#891](https://github.com/nestjs/swagger/issues/891)

**Comment by JohannesKlauss** [comment]
After investigating a bit more I realized that for some reason `apollo-server-fastify` was causing this issue. Updating this package to the newest alpha version `3.0.0-alpha.3` fixes it.

**Comment by HeroBanana** [comment]
Before updating to an alpha package consider the following: Are you using Apollo uploads? If not you can disable the upload function by disabling the uploads prop in the GraphQLModule options.

```
GraphQLModule.forRootAsync({
    useFactory: (): GqlModuleOptions => ({
        uploads: false,
    })
}),
```
