### ISSUE TITLE
Websocket @SubscribeMessage is not triggered when user send the msg from the client 

### ISSUE THREAD

**Issue by tomNjerry** [nestjs/nest#5608]
## Current behavior
- The current code to connect to web-socket works perfectly fine  with development server locally 
- In production the server connects to the web-socket on server, but it doesn't listen to the event on server when client trys to emit msg to the event.
- it does not listen to the event on the server

## Input Code

```ts
 @SubscribeMessage('msgToServer')
  handleMessage(@ConnectedSocket() client: Socket, 
                @MessageBody() _data: RecieveMsg): void{
    this.logger.log(`Recieved message from client :- ${client.id}, message is ${_data.message}`);
    const dataObj: ChatData = {
      id: client.id,
      message: _data.message,
    };

    this.server.emit('msgToClient', dataObj);
  }
```

## Expected behavior
- listen the client emit to event on server and send emit the same event to server and listen that event on the client side.

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 12.19.0
- NPM version: 6.14.8
- Platform:   Linux 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by tomNjerry** [comment]
Issue Resolved it was the configuration on nginx how it consider the socket connection on which location blog in nginx server config
