### ISSUE TITLE
Graceful Shutdown for any outstanding promises

### ISSUE THREAD

**Issue by danscrima** [nestjs/nest#5610]
I'm trying to implement the graceful shutdown with **app.enableShutdownHooks();** along with **onApplicationShutdown** functions. My goal, however is to listen for the SIGINT or SIGTERM signals etc... and when those are sent, wait for any outstanding promises to fully resolve before exiting. It seems like only the code in those **onApplicationShutdown** functions will execute, but I need a way of saying "Are there outstanding promises not yet resolved? If so, wait until they are all resolved, then exit the process." Is this even possible?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
