### ISSUE TITLE
Middleware with dependency is always executing first

### ISSUE THREAD

**Issue by MFrat** [nestjs/nest#5612]
## Current behavior
Middleware with request scoped dependency always executes first than the others without dependencies.
Print from the code is:
```
AuthMiddleware
1
```
When i remove the dependency or remove the REQUEST scope, things just works normally and the output becomes:
```
1
AuthMiddleware
```

## Input Code
``` typescript
export class AppCoreModule implements NestModule {
    configure(consumer: MiddlewareConsumer): void {
        consumer
            .apply(UIDMiddleware)
            .forRoutes('/')
            .apply(AuthMiddleware)
            .forRoutes('/');
    }
}

@Injectable()
export class AuthMiddleware implements NestMiddleware {
    constructor(private readonly dependency: Dependency) {}

    async use(req: any, res: any, next: () => void) {
        console.log('AuthMiddleware');
        return next();
    }
}

@Injectable()
export class UIDMiddleware implements NestMiddleware {
    use(req: any, res: any, next: () => void) {
        console.log('1');
        next();
    }
}

@Injectable({ scope: Scope.REQUEST })
export class Dependency {
    ...
}
```

## Expected behavior
The order should be respected even if there is one or more middlewares with dependencies.

## Resitory
https://github.com/MFrat/nestjs-middleware-bug

## Environment

<pre><code>
Nest version: 7.4.4
 
For Tooling issues:
- Node version: 10.22.1
- Platform: Mac OS Catalina

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by MFrat** [comment]
Reproduction Repository added, and more info added.

**Comment by jmcdo29** [comment]
As a side note, it looks like the different order is only when the dependency is `REQUEST` scoped.
