### ISSUE TITLE
Why is it so difficult to get a simple step to get the header values of an API request for nestjs fastify/express?

### ISSUE THREAD

**Issue by cyb3rs4pi3n** [nestjs/nest#5614]
can someone please give the straight forward way to get request values(headers/params) in the controller API. Also can we specify this in the DTO for the API request. Didn't find it in the documentation either (found it for express specific for the request but not for fastify- this was for access and not for the DTO)

**Comment by VishwasShashidhar** [comment]
@cyb3rs4pi3n Did you check the [documentation here](https://docs.nestjs.com/controllers#request-object)?

**Comment by jmcdo29** [comment]
@cyb3rs4pi3n I'm not sure what you're having problems with, but `@Headers()`, `@Param()`, `@Query()`, and all the other decorators work for both Express and Fastify without any extra configuration necessary. You could theoretically do it in the DTO, but you then need a custom decorator which could be more annoying than expected. 

If you have more questions about general use of the framework, please use our [Discord](https://discord.gg/nestjs) as we're using GitHub to track Feature Requests, Bug Reports, and Regressions.
