### ISSUE TITLE
Cannot catch ECONNRESET for microservice send

### ISSUE THREAD

**Issue by CubePoint** [nestjs/nest#5616]
## Current behavior

microservices <code>clientProxy.send(pattern, data);</code> 
```ts
[ClientTCP] write ECONNRESET - {"stack":["Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:780:11)
    at Socket._write (net.js:792:8)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Socket.Writable.write (_stream_writable.js:316:11)
    at JsonSocket.sendMessage (@nestjs\\microservices\\helpers\\json-socket.js:46:21)
    at ClientTCP.publish (@nestjs\\microservices\\client\\client-tcp.js:76:25)
    at Observable._subscribe (@nestjs\\microservices\\client\\client-proxy.js:23:25)
    at Observable._trySubscribe (rxjs\\internal\\Observable.js:44:25)
    at Observable.subscribe (rxjs\\internal\\Observable.js:30:22)
    at Object.innerSubscribe (rxjs\\internal\\innerSubscribe.js:102:23)
    at MergeMapSubscriber._innerSub (rxjs\\internal\\operators\\mergeMap.js:80:50)
    at MergeMapSubscriber._tryNext (rxjs\\internal\\operators\\mergeMap.js:74:14)
    at MergeMapSubscriber._next (rxjs\\internal\\operators\\mergeMap.js:57:18)at MergeMapSubscriber.Subscriber.next (rxjs\\internal\\Subscriber.js:66:18)
    at rxjs\\internal\\util\\subscribeToPromise.js:7:24"],"errno":"ECONNRESET","code":"ECONNRESET","syscall":"write"}
```
cannot handle the error with a catch clause or a .catch on the Observable.

## Input Code

```ts
try {
  await this.clientProxy.send('pattern', data).toPromise()
} catch (error) {
  // Error not catched??!
  console.error(e);
}
```

## Possible Solution

I expect ECONNREFUSED to be catchable.

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: v12.16.1
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by CubePoint** [comment]
> ## Bug Report
> ## Current behavior
> microservices `clientProxy.send(pattern, data);`
> 
> ```ts
> [ClientTCP] write ECONNRESET - {"stack":["Error: write ECONNRESET
>     at afterWriteDispatched (internal/stream_base_commons.js:154:25)
>     at writeGeneric (internal/stream_base_commons.js:145:3)
>     at Socket._writeGeneric (net.js:780:11)
>     at Socket._write (net.js:792:8)
>     at doWrite (_stream_writable.js:441:12)
>     at writeOrBuffer (_stream_writable.js:425:5)
>     at Socket.Writable.write (_stream_writable.js:316:11)
>     at JsonSocket.sendMessage (@nestjs\\microservices\\helpers\\json-socket.js:46:21)
>     at ClientTCP.publish (@nestjs\\microservices\\client\\client-tcp.js:76:25)
>     at Observable._subscribe (@nestjs\\microservices\\client\\client-proxy.js:23:25)
>     at Observable._trySubscribe (rxjs\\internal\\Observable.js:44:25)
>     at Observable.subscribe (rxjs\\internal\\Observable.js:30:22)
>     at Object.innerSubscribe (rxjs\\internal\\innerSubscribe.js:102:23)
>     at MergeMapSubscriber._innerSub (rxjs\\internal\\operators\\mergeMap.js:80:50)
>     at MergeMapSubscriber._tryNext (rxjs\\internal\\operators\\mergeMap.js:74:14)
>     at MergeMapSubscriber._next (rxjs\\internal\\operators\\mergeMap.js:57:18)at MergeMapSubscriber.Subscriber.next (rxjs\\internal\\Subscriber.js:66:18)
>     at rxjs\\internal\\util\\subscribeToPromise.js:7:24"],"errno":"ECONNRESET","code":"ECONNRESET","syscall":"write"}
> ```
> 
> cannot handle the error with a catch clause or a .catch on the Observable.
> 
> ## Input Code
> ```ts
> try {
>   await this.clientProxy.send('pattern', data).toPromise()
> } catch (error) {
>   // Error not catched??!
>   console.error(e);
> }
> ```
> 
> ## Expected behavior
> ## Possible Solution
> I expect ECONNREFUSED to be catchable.
> 
> ## Environment
> ```
> 
> Nest version: 7.4.4
> 
>  
> For Tooling issues:
> - Node version: v12.16.1
> - Platform:  Windows
> 
> Others:
> ```

**Comment by CubePoint** [comment]
When the server does not know that the client is disconnected. Then the server sends a message, it will happen this kind of error.

I think I can solve this problem with timeout. I found this https://github.com/nestjs/docs.nestjs.com/issues/222

A little suggestion:When capturing `tcp error`, `callback({err})` in routingMap
```
// @nestjs\microservices\client\client-tcp.js  :64
handleError(err) {
  this.logger.error(err);
  this.routingMap.forEach((callback) => {
    callback && callback({ err })
  });
}
```

Very sorry for my poor english

**Comment by kamilmysliwiec** [comment]
Can you please provide a minimum reproduction repository (github repo with an example)? This would help us a lot

**Comment by CubePoint** [comment]
A reproduction repository is here. 
https://github.com/CubePoint/nestjs-issue-5616

**Comment by brunoosilva** [comment]
@CubePoint how you resolved this problem ?

**Comment by CubePoint** [comment]
> @CubePoint how you resolved this problem ?

use the timeout
```
await this.clientProxy.send('pattern', data)
    .pipe(timeout(5000))
    .toPromise()
```
