### ISSUE TITLE
ModuleRef.resolve - allow to pass down additional parameters to constructor of resolved service 

### ISSUE THREAD

**Issue by theres** [nestjs/nest#5617]
## Is your feature request related to a problem? Please describe.
I want to instantiate transient service that have some additional, **required** parameters that are created dynamically. Because those parameters are required, it is safer to force passing it down through the constructor than some setter. I'd love to see some built-in framework method for achieving this goal. 
Rough pseudocode:

```ts
@Injectable()
class InjectableService{...}

class AdditionalParameter{...}

@Injectable({scope: Scope.TRANSIENT})
class CatService {
    constructor(private injectableService: InjectableService, private additionalParameter1: AdditionalParameter, private additionalParameter2: AdditionalParameter){}
}

...
moduleRef.resolve(CatService);

```

## Describe the solution you'd like
For now I can imagine two APIs for this:
1. pass additional parameters to the resolve method, possibly to the options parameter `moduleRef.resolve(CatService, contextId, {params: [additionalParam1, additionalParam2]})`
2 add a method to the moduleRef that allows to register providers/values for given token & contextId, something similar to the `registerRequestByContextId`

```ts
...

@Injectable({scope: Scope.TENTATIVE})
class CatService {
    constructor(private injectableService: InjectableService, @Inject(ADDITIONAL_PARAMETER_1_TOKEN) private additionalParameter1: AdditionalParameter, @Inject(ADDITIONAL_PARAMETER_2_TOKEN) private additionalParameter2: AdditionalParameter){}
}
...

moduleRef.registerProviderByContextId(additionalParameter1, ADDITIONAL_PARAMETER_1_TOKEN, contextId);
moduleRef.registerProviderByContextId(additionalParameter2, ADDITIONAL_PARAMETER_2_TOKEN, contextId);
moduleRef.resolve(CatService)
```

**Comment by jmcdo29** [comment]
How would this be different than registering those injection tokens to begin with as custom providers? Can you provide a minimum reproduction that shows _why_ this change would be useful?

**Comment by theres** [comment]
AFAIK I cannot register more then one provider for given token per request. In our case, we get some indentifier in a request, with this indentifier we fetch data from database and for each row we want to instantiate new instance of transient service, depending of the data in the row. Our production case is a lot more complicated, have a few of different service types etc, but this pseudocode is kind of essence of problem. If you need I can provide repo with that tomorrow.

```ts
class MyEntity {
  id: string;
  type: 'cat' | 'dog';
// other stuff
}

@Injectable({scope: Scope.TRANSIENT})
class CatService {
  constructor(/*lots of injectable services*/, catData: MyEntity){}
}
@Injectable({scope: Scope.TRANSIENT})
class DogService {
  constructor(/*lots of other injectable services*/, dogData: MyEntity){}
}

@Injectable()
class BusinessLogicService {
  constructor(private moduleRef: ModuleRef){}
  
  getInstances(id: string): (CatService | DogService)[] {
      const entities: MyEntity[] = // fetch from db by given id
      return entities.map(entity => {
         switch(entity.type){
              case 'cat': return this.moduleRef.resolve(CatService);
              case 'dog': return this.moduleRef.resolve(DogService);
         }
      })
  }
}

```

**Comment by jmcdo29** [comment]
A repository would be great to get a chance to play with this and see what can be done with it.

**Comment by kamilmysliwiec** [comment]
```typescript
const entities: MyEntity[] = // fetch from db by given id
```
Why this part cannot be defined as a custom provider?

**Comment by theres** [comment]
Hmm, it can, but the key point of this issue is this: 
   
```ts
         switch(entity.type){
              case 'cat': return this.moduleRef.resolve(CatService); // need to inject entity here
              case 'dog': return this.moduleRef.resolve(DogService); // and here.
         }
```

In the example I need to resolve custom service for each of the entities in this array. AFAIK custom provider doesn't allow to do this. Also, as I said, this is quite simplified version, we resolve some of the entities later, conditionaly, during the buisiness logic execution - some of those services can spawn other services and so one.

**Comment by theres** [comment]
But as you can see, this is in invoked in the `map` method, that means I need to inject different entity to each service instance.I can easily create async factory in module to make the whole array of entities or specified entity injectable via specified token.  The thing is, in single request I'd need to create multiple CatService instances, each of them with **different** injected entity. 

Here is an example repo to play with: https://github.com/theres/example-nestjs-resolve
 
There is couple of possible workarounds to achieve this. In the repo I've presented one way - exposing public setter for the entity on the service and set this just after resolve. This approach is rather wrong. The thing is, there is no way to enforce using this setter so I need to guard myself in runtime rather than forcing this by constructor. 
Another approach would be make those services stateless and pass those entities via parameters of invoked methods. This is doable for this example, but for more complicated business logic it is in practice in the same way as it would be in practice to manually pass request object via parameter.

Also, bear in mind, even if in this example we fetch all entities as a first step, in our production case we instantiate some of the services a lot later as a result of some business logic.

**Comment by kamilmysliwiec** [comment]
```typescript
const animals = this.repository.getByGroup(group);
    const animalsPromise = animals.map(async (animal) => {
      switch(animal.type){
        case 'cat': {
          const service = await this.moduleRef.resolve(CatService);
          service.entity = animal;
          return service;
        };
        case 'dog': {
          const service = await this.moduleRef.resolve(DogService);
          service.entity = animal;
          return service;
        }
      }
    });
    const services = await Promise.all(animalsPromise);
    return services.map(service => service.getHello()).join(', ')
```
^ this code (taken from your repo) can be implemented in a way that won't force you to assign entities manually. As I've pointed out above, you can create a custom provider (which is request-scoped) with an async factory function that per request (= function will be executed per each request/or per each `.resolve()` method call), fetches corresponding entities or any other per-request data (based on the `REQUEST` object [which can be injected into an async factory function using the `REQUEST` token] or any additional metadata you assign to this object from the database). This way you can dynamically create a provider "on the fly" PER specific user/tenant/request. This provider might be equal to, for example, an array of entities that belongs to a specified group (extracted from the REQUEST).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. I would love to help you with this, but unfortunately, I don't have enough time to dive into this now.
