### ISSUE TITLE
TypeOrm fails on migration generate, run, and app start

### ISSUE THREAD

**Issue by mmacdonald1** [nestjs/nest#5626]
## Current behavior

Entire application works on other computers except one. On the computer where it fails TypeOrm silently fails on migration generate, run, and app start

## Console Output
console output before it silently fails:
```ts
npm run typeorm:migration:run

>  typeorm:migration:run /Users/melaniemacdonald/apps/terrayn-backend
> npm run typeorm -- migration:run


> typeorm /Users/melaniemacdonald/apps/terrayn-backend
> ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js "migration:run"
```

## Expected behavior
Fully functional as seen on the other computers

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 14.8.0
- Platform:  Mac Catalina

**Comment by jmcdo29** [comment]
This should probably be reported to TypeORM's repository with a minimum reproduction

**Comment by kamilmysliwiec** [comment]
As @jmcdo29 pointed out above, please, report this issue in TypeORM repository https://github.com/typeorm/typeorm
