### ISSUE TITLE
reflect-metadata specific version needed?

### ISSUE THREAD

**Issue by grofit** [nestjs/nest#563]
## Current behavior
NestJs currently seems to depend on a specific version of `reflect-metadata` (0.1.10) and will complain in NPM unless you resolve this SPECIFIC version, I tried higher versions and it complained it needed that specific one.

## Expected behavior
It should ideally not *need* any specific polyfill for `Reflect.getMetadata` etc it should just expect the consumer to provide one (until nodejs etc) doesn't need it polyfilled.

Currently to my knowledge there are 2 available polyfills:
- core-js
- reflect-metadata

Problem here is if you were to have both of them in a project your metadata gets wiped as each polyfill is replacing each others polyfill (this may be fixed now but was an issue a few months back).

## Minimal reproduction of the problem with instructions
- Make a new project
- Add restjs dependencies
- See error for missing `reflect-metadata` 0.1.10
- install 0.1.12 version of `reflect-metadata`
- See error for missing `reflect-metadata` 0.1.10

## What is the motivation / use case for changing the behavior?
It just seemed odd that it should force you to use a specific version of a polyfill, and in some cases people may want to use `core-js` which would probably cause decorators that use metadata to blow up.

## Recommended solution?
I would remove the dependency on `reflect-metadata` entirely, and just include a `devDependency` for `@types/reflect-metadata`, that will allow you to write TS code that uses metadata, then you require the consumer to provide a relevant polyfill (as listed above).

This is done on one of my other libs:

- [TS code using metadata functionality](https://github.com/Treacherous/treacherous-decorators/blob/master/src/helpers/metadata-helper.ts)
- [No hard dependency on polyfill in package.json](https://github.com/Treacherous/treacherous-decorators/blob/master/package.json)

**Comment by ith** [comment]
Upvote for this. I have the exact same issue

**Comment by kamilmysliwiec** [comment]
Hey @grofit,
Thanks for reporting! This issue is fixed in `v5.0.0` (currently `v5.0.0-beta.2`).

**Comment by amitport** [comment]
@kamilmysliwiec the dependency seems to be still forced in the bundles 
(https://github.com/nestjs/nest/blob/53bcbefb63b92fac42d327ec33564da4bc7dc32b/bundle/core/package.json#L16)
