### ISSUE TITLE
Cannot find name 'ApiQuery'

### ISSUE THREAD

**Issue by lacivert** [nestjs/nest#5640]
## Current behavior

Everything works fine on my local (macosx). But on the server (Ubuntu20), `build` command has a problem. It started after I add `@ApiQuery` annotation for a string array (multiple) query parameter. Build stops with this:

```
src/data/data.controller.ts:38:4 - error TS2304: Cannot find name 'ApiQuery'.

38   @ApiQuery({
      ~~~~~~~~

Found 1 error(s).

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 build: `nest build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-11-01T14_17_15_378Z-debug.log

```

I tried to upgrade typescript/node/npm versions. Reinstall node_modules from scratch. No luck.

If I remove `@ApiQuery` that works but swagger part has problems on the UI (web console)

```
Uncaught TypeError: Cannot read property 'anyOf' of undefined
    at e (fn.js:87)
    at configure-map.js:61
    at $e (utils.js:570)
    at Ke (utils.js:589)
    at n.setDefaultValue (parameter-row.jsx:107)
    at new n (parameter-row.jsx:30)
    at u._constructComponentWithoutOwner (ReactCompositeComponent.js:295)
    at u._constructComponent (ReactCompositeComponent.js:282)
    at u.mountComponent (ReactCompositeComponent.js:185)
    at Object.mountComponent (ReactReconciler.js:43)
``` 

## Input Code

A basic controller has a method to get data by a query param. It may be an array.

```ts
  @ApiQuery({
     name: 'id',
     isArray: true,
     required: false
   })
  @Get()
  getData(@Query('id') ids) {
    return this.dataService.getData(ids);
  }
```

## Expected behavior

I expect that works.

## Environment

<pre><code>
Nest version: X.Y.Z

nest cli 7.5.1
"@nestjs/core": "^7.0.0",
"@nestjs/swagger": "^4.6.0",
 
For Tooling issues:
- Node version: XX  
- Platform:  

- Node: 12.18.3, 12.19.0
- Platform: Ubuntu 20

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by lacivert** [comment]
I understand but this is not a support question

**Comment by lacivert** [comment]
Just for a note; I am not able to solve this problem directly but I found an alternative way; I created a type for `@Query()` parameter and I defined `@ApiProperty()` for the array inside of the query.

``` typescript
  @Get()
  getData(@Query('id') query: QueryDto) {
    return this.dataService.getData(ids);
  }
```

QueryDto:

``` typescript
export class QueryDto {
  @ApiProperty({
    required: false,
    isArray: true,
    type: String
  })
  id: string[];
}
```
