### ISSUE TITLE
Unable to create Queue job

### ISSUE THREAD

**Issue by deema089786** [nestjs/nest#5651]
## Bug Report
Trying to create Queue job, but promise doesn't resolved and get this error
## Current behavior

`
[Nest] 1   - 11/02/2020, 9:02:37 PM   [ExceptionsHandler] Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details. +209347ms
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:172:37)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12)
(node:1) UnhandledPromiseRejectionWarning: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:172:37)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:172:37)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

`
## Input Code

```ts
for (let page = 0; page < PAGES; page += 1) {
      await this.merchantFeedQueue.add(
        'writeFeed',
        {
          page,
        },
        { removeOnComplete: true, removeOnFail: true },
      );
    }
```

## Environment

<pre><code>
[Nest CLI]
Nest CLI Version : 7.4.1 

[Nest Platform Information]
platform-express version : 7.5.1
serve-static version     : 2.1.3
passport version         : 7.1.0
schedule version         : 0.4.1
typeorm version          : 7.1.4
common version           : 7.5.1
bull version             : 0.2.2
core version             : 7.5.1
jwt version              : 7.1.0

 
For Tooling issues:
- Node version: 12  
- Platform: Ubuntu, Docker container 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
