### ISSUE TITLE
[Discussion] Serving Publics/Privates Routes

### ISSUE THREAD

**Issue by lindomar-oliveira** [nestjs/nest#5653]
I'm confused about how best to create public and private routes for my NestJS application.

Do I create all routes on a single controller? Do I Separate into folders, for example: `public` and `private` my modules?

And yet keep the codebase scalable and the DX (Developer Experience).

Here my current project structure:

```
- src
    - products
        - product.entity.ts
        - products.controller.ts
        - products.modules.ts
        - products.service.ts
    ... etc
    app.module.ts
    main.ts
    ...
```

**Comment by jmcdo29** [comment]
This seems like something that would best be discussed on [Discord](https://discord.gg/nestjs) as we are using GitHub to track Bug Reports, Feature Requests, and Regressions.
