### ISSUE TITLE
Nest CLI GraphQL Plugin not working with custom options

### ISSUE THREAD

**Issue by steinroe** [nestjs/nest#5661]
## Bug Report
Cannot set options on the GraphQL plugin for the nest cli. 

## Current behavior
The GraphQL plugin is not used and my IDE throws 
_Incompatible types. Required: string. Actual: object._ 
for the plugins array.

## Input Code
**nest-cli.json**
```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/graphql/plugin",
        "options": {
          "typeFileNameSuffix": [".input.ts", ".args.ts", ".type.ts", ".model.ts"]
        }
      }
    ]
  }
}
```

## Expected behavior
It should pick up the GraphQL plugin and use the provided options.

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 12.19.0  
- Platform:  Mac

IDE: Webstorm
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by steinroe** [comment]
I assumed this is a bug since I use the exact same config as proposed in the docs and it doesn't work as expected

**Comment by Simon-Bin** [comment]
same it
