### ISSUE TITLE
Official Webpack HMR example fails

### ISSUE THREAD

**Issue by nick-lehmann** [nestjs/nest#5667]
## Current behavior

After checking out the [webpack sample](https://github.com/nestjs/nest/tree/master/sample/08-webpack), installing all packages, the command `yarn build:dev` fails with

```
Error  Cannot read property 'tap' of undefined
```

## Input Code

```bash
> git clone https://github.com/nestjs/nest
> cd nest/sample/08-webpack
> yarn
> yarn build:dev
yarn run v1.22.4
$ nest build --watch --webpack --webpackPath webpack-hmr.config.js

 Info  Webpack is building your sources...

Starting type checking service...

 Error  Cannot read property 'tap' of undefined
```

Same happens when using `npm` instead of `yarn`.

## Expected behavior

Server is up and running.

## Environment

<pre><code>
Nest version: 7.4.1

 
For Tooling issues:
- Node version: v14.7.0
- Platform:  Mac

Others:
Current master at time of writing is [this one](https://github.com/nestjs/nest/tree/8e216b2b25756002243da545d80b5112431010b1)
</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed, thanks for reporting! Also, it seems that the `start-server-webpack-plugin` isn't compatible with Webpack 5 so I had to temporarily remove it. Let's track this here https://github.com/ericclemmons/start-server-webpack-plugin/issues/40

**Comment by douglasgc** [comment]
I sent a PR for the documentation with a new lib, why don't have the answer in the current package and recent updates.
https://github.com/nestjs/docs.nestjs.com/pull/1545

**Comment by atassis** [comment]
BTW, you can use [this](https://github.com/atassis/run-script-webpack-plugin) instead 
And if you receive a bug- you can make an issue, will look through it
