### ISSUE TITLE
Set trustProxy for Fastify

### ISSUE THREAD

**Issue by Menci** [nestjs/nest#5671]
## Is your feature request related to a problem? Please describe.
Express's trustProxy option can be set with `app.set("trust proxy", 1);`. But in fastify we have no way to set it.

## Describe the solution you'd like
I don't know. Looks like Fastify doesn't have an method to set `trustProxy` via its app instance.

## Teachability, Documentation, Adoption, Migration Strategy
Just like Express's one.

## What is the motivation / use case for changing the behavior?
Because this is needed for replacing Express with Fastify.

**Comment by kamilmysliwiec** [comment]
https://github.com/fastify/fastify/pull/1086
