### ISSUE TITLE
Nested Dependency Injection of custom-decorated classes fails for some node versions

### ISSUE THREAD

**Issue by StenCalDabran** [nestjs/nest#5673]
## Bug Report

I'm not quite sure if this issue is placed correctly here, there are multiple possibilities:
- Usage of custom class decorators in combination with `@Injectable()` is generally not supported (I did not find documentation for this)
- There is a bug in the NestJS depencency injection framework
- There is a bug in multiple stable Node versions but not in others (see version info below, maybe not that likely?)

Could you please confirm which of the three possibilities is true?

## Current behavior
If run with Node version 15.0.1 (latest) or 12.19.0 (latest), the following error is thrown when executing the test:
```
Error: Nest can't resolve dependencies of the  (?). Please make sure that the argument + at index [0] is available in the RootTestModule context.

Potential solutions:
- If + is a provider, is it part of the current RootTestModule?
- If + is exported from a separate @Module, is that module imported within RootTestModule?
  @Module({
    imports: [ /* the Module containing + */ ]
  })
```
If run with Node version 14.15.0 (latest) or 12.13.0 the test correctly passes.

I am not sure where between 12.13.0 and 12.19.0 it breaks.

## Input Code

```ts
import { Injectable } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';

function SomeClassDecorator<T extends new (...args: any[]) => any>(Base: T): T {
  return class extends Base {
    constructor(...args: any[]) {
      super(...args);
    }
  };
}

@Injectable()
@SomeClassDecorator
class ExtendedClass {}

@Injectable()
@SomeClassDecorator
class IntermediaryClass {
  constructor(private readonly extendedClass: ExtendedClass) {}
}

class ExtendingClass {
  constructor(private readonly intermediaryClass: IntermediaryClass) {}
}

describe('ExtendingClass', () => {
  let extendingClass: ExtendingClass;
  beforeEach(async () => {
    const testingModule: TestingModule = await Test.createTestingModule({
      providers: [ExtendedClass, IntermediaryClass, ExtendingClass],
    }).compile();
    extendingClass = testingModule.get<ExtendingClass>(ExtendingClass);
  });
  it('should be defined', () => {
    expect(extendingClass).toBeDefined();
  });
});
```

## Expected behavior
The test should pass regardless of the used Node version.

## Environment

<pre><code>
Nest version: 7.5.1
 
For Tooling issues:
- Node version: not working for 15.0.1 (latest), 12.19.0 (latest); works fine for 14.15.0 (latest) and 12.13.0
- Platform:  Linux, Windows (I guess also Mac)
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by StenCalDabran** [comment]
I figured it would be easier for both you and me to just provide the code above which is a standalone testfile which can be inserted into any nest project to show the problem.

But sure, I also inserted it into its own repository: https://github.com/StenCalDabran/nestjs-di

**Comment by jmcdo29** [comment]
At least for node 12.19.0, the `name` property of the class is being overwritten by the decorator, and in doing so, Nest can no longer know for sure what to inject when it comes across that class (because Nest uses injection tokens via `Class.name` unless specified using `@Inject()`. Modifying your code to look like this:

```typescript
import { Inject, Injectable } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';

function SomeClassDecorator<T extends new (...args: any[]) => any>(Base: T): T {
  return class extends Base {
    constructor(...args: any[]) {
      super(...args);
    }
  };
}

@Injectable()
@SomeClassDecorator
class ExtendedClass {}

@Injectable()
@SomeClassDecorator
class IntermediaryClass {
  constructor(@Inject('Extended') readonly extendedClass: ExtendedClass) {}
}

@Injectable()
class ExtendingClass {
  constructor(
    @Inject('Intermediary') readonly intermediaryClass: IntermediaryClass,
  ) {}
}

describe('ExtendingClass', () => {
  let extendingClass: ExtendingClass;
  beforeEach(async () => {
    const testingModule: TestingModule = await Test.createTestingModule({
      providers: [
        {
          provide: 'Extended',
          useClass: ExtendedClass,
        },
        {
          provide: 'Intermediary',
          useClass: IntermediaryClass,
        },
        ExtendingClass,
      ],
    }).compile();
    extendingClass = testingModule.get<ExtendingClass>(ExtendingClass);
  });
  it('should be defined', () => {
    expect(extendingClass).toBeDefined();
    expect(extendingClass.intermediaryClass).toBeDefined();
    expect(extendingClass.intermediaryClass.extendedClass).toBeDefined();
  });
});
```
Everything works as expected in the test. It seems something in how 14 treats anonymous classes makes things work out, which is super weird.

**Comment by StenCalDabran** [comment]
So I guess the right way to write a decorator which works well with Nest's dependency injection would be like this?
```ts
function SomeClassDecorator<T extends new (...args: any[]) => any>(Base: T): T {
  const decoratedClass = class extends Base {
    constructor(...args: any[]) {
      super(...args);
    }
  };
  Object.defineProperty(decoratedClass, 'name', {
    value: Base.name,
  });
  return decoratedClass;
}
```

**Comment by StenCalDabran** [comment]
Interestingly enough, for node 14 
```ts
class extends Base {
      constructor(...args: any[]) {
        super(...args);
      }
    }.name
```
is defined and gives the same value as `Base.name`, which is weird behaviour but explains why it does work out there.

**Comment by StenCalDabran** [comment]
I opened a node issue for this weird behaviour: https://github.com/nodejs/node/issues/36038

It would be nice if you could give a comment on the validity of the alternative decorator definition above, but apart from that this issue can be closed.

**Comment by jmcdo29** [comment]
Your new decorator, which sets the name property, does work as intended, so you've at least got that workaround for now. I'll keep an eye on that node issue if anything comes up with it. Really weird that anon classes get different names in different versions.
