### ISSUE TITLE
Update socket.io to 3.0 in @nestjs/platform-socket.io package

### ISSUE THREAD

**Issue by mateuszlewko** [nestjs/nest#5676]
Hi there,

socket.io got recently updated to 3.0. @nestjs/platform-socket.io depends on the version 2.3. Note that socket.io 3.0 client/server is not backwards compatible with v2.0.

**Comment by jmcdo29** [comment]
As this will be a major change, we can probably make this a goal for v8. @kamilmysliwiec does that sound right?

**Comment by kamilmysliwiec** [comment]
Correct @jmcdo29. Let's wait till the next major release.

**Comment by mateuszlewko** [comment]
For those that need socket.io 3 support now, here is a socket.io adapter from the official nestjs sources adjusted for version 3.0.

#### socket-io.adapter.ts

```typescript
import { INestApplicationContext } from '@nestjs/common';
import { isFunction, isNil } from '@nestjs/common/utils/shared.utils';
import {
  AbstractWsAdapter,
  MessageMappingProperties,
} from '@nestjs/websockets';
import { DISCONNECT_EVENT } from '@nestjs/websockets/constants';
import { fromEvent, Observable } from 'rxjs';
import { filter, first, map, mergeMap, share, takeUntil } from 'rxjs/operators';
import { Server } from 'socket.io';

export class SocketIoAdapter extends AbstractWsAdapter {
  constructor(
    appOrHttpServer?: INestApplicationContext | any,
    private readonly corsOrigins = [],
  ) {
    super(appOrHttpServer);
  }

  public create(
    port: number,
    options?: any & { namespace?: string; server?: any },
  ): any {
    if (!options) {
      return this.createIOServer(port);
    }
    const { namespace, server, ...opt } = options;
    return server && isFunction(server.of)
      ? server.of(namespace)
      : namespace
      ? this.createIOServer(port, opt).of(namespace)
      : this.createIOServer(port, opt);
  }

  public createIOServer(port: number, options?: any): any {
    if (this.httpServer && port === 0) {
      const s = new Server(this.httpServer, {
        cors: {
          origin: this.corsOrigins,
          methods: ['GET', 'POST'],
          credentials: true,
        },
        cookie: {
          name: 'io',
          httpOnly: true,
          path: '/',
        },
        // Allow 1MB of data per request.
        maxHttpBufferSize: 1e6,
      });

      return s;
    }
    return new Server(port, options);
  }

  public bindMessageHandlers(
    client: any,
    handlers: MessageMappingProperties[],
    transform: (data: any) => Observable<any>,
  ) {
    const disconnect$ = fromEvent(client, DISCONNECT_EVENT).pipe(
      share(),
      first(),
    );

    handlers.forEach(({ message, callback }) => {
      const source$ = fromEvent(client, message).pipe(
        mergeMap((payload: any) => {
          const { data, ack } = this.mapPayload(payload);
          return transform(callback(data, ack)).pipe(
            filter((response: any) => !isNil(response)),
            map((response: any) => [response, ack]),
          );
        }),
        takeUntil(disconnect$),
      );
      source$.subscribe(([response, ack]) => {
        if (response.event) {
          return client.emit(response.event, response.data);
        }
        isFunction(ack) && ack(response);
      });
    });
  }

  public mapPayload(payload: any): { data: any; ack?: Function } {
    if (!Array.isArray(payload)) {
      return { data: payload };
    }
    const lastElement = payload[payload.length - 1];
    const isAck = isFunction(lastElement);
    if (isAck) {
      const size = payload.length - 1;
      return {
        data: size === 1 ? payload[0] : payload.slice(0, size),
        ack: lastElement,
      };
    }
    return { data: payload };
  }
}
```

#### main.ts

```typescript

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  // ...
  app.useWebSocketAdapter(new SocketIoAdapter(app, corsOrigins));
}
```

**Comment by longdhit** [comment]
> For those that need socket.io 3 support now, here is a socket.io adapter from the official nestjs sources adjusted for version 3.0.
> 
> #### socket-io.adapter.ts
> ```ts
> import { INestApplicationContext } from '@nestjs/common';
> import { isFunction, isNil } from '@nestjs/common/utils/shared.utils';
> import {
>   AbstractWsAdapter,
>   MessageMappingProperties,
> } from '@nestjs/websockets';
> import { DISCONNECT_EVENT } from '@nestjs/websockets/constants';
> import { fromEvent, Observable } from 'rxjs';
> import { filter, first, map, mergeMap, share, takeUntil } from 'rxjs/operators';
> import { Server } from 'socket.io';
> 
> export class SocketIoAdapter extends AbstractWsAdapter {
>   constructor(
>     appOrHttpServer?: INestApplicationContext | any,
>     private readonly corsOrigins = [],
>   ) {
>     super(appOrHttpServer);
>   }
> 
>   public create(
>     port: number,
>     options?: any & { namespace?: string; server?: any },
>   ): any {
>     if (!options) {
>       return this.createIOServer(port);
>     }
>     const { namespace, server, ...opt } = options;
>     return server && isFunction(server.of)
>       ? server.of(namespace)
>       : namespace
>       ? this.createIOServer(port, opt).of(namespace)
>       : this.createIOServer(port, opt);
>   }
> 
>   public createIOServer(port: number, options?: any): any {
>     if (this.httpServer && port === 0) {
>       const s = new Server(this.httpServer, {
>         cors: {
>           origin: this.corsOrigins,
>           methods: ['GET', 'POST'],
>           credentials: true,
>         },
>         cookie: {
>           name: 'io',
>           httpOnly: true,
>           path: '/',
>         },
>         // Allow 1MB of data per request.
>         maxHttpBufferSize: 1e6,
>       });
> 
>       return s;
>     }
>     return new Server(port, options);
>   }
> 
>   public bindMessageHandlers(
>     client: any,
>     handlers: MessageMappingProperties[],
>     transform: (data: any) => Observable<any>,
>   ) {
>     const disconnect$ = fromEvent(client, DISCONNECT_EVENT).pipe(
>       share(),
>       first(),
>     );
> 
>     handlers.forEach(({ message, callback }) => {
>       const source$ = fromEvent(client, message).pipe(
>         mergeMap((payload: any) => {
>           const { data, ack } = this.mapPayload(payload);
>           return transform(callback(data, ack)).pipe(
>             filter((response: any) => !isNil(response)),
>             map((response: any) => [response, ack]),
>           );
>         }),
>         takeUntil(disconnect$),
>       );
>       source$.subscribe(([response, ack]) => {
>         if (response.event) {
>           return client.emit(response.event, response.data);
>         }
>         isFunction(ack) && ack(response);
>       });
>     });
>   }
> 
>   public mapPayload(payload: any): { data: any; ack?: Function } {
>     if (!Array.isArray(payload)) {
>       return { data: payload };
>     }
>     const lastElement = payload[payload.length - 1];
>     const isAck = isFunction(lastElement);
>     if (isAck) {
>       const size = payload.length - 1;
>       return {
>         data: size === 1 ? payload[0] : payload.slice(0, size),
>         ack: lastElement,
>       };
>     }
>     return { data: payload };
>   }
> }
> ```
> 
> #### main.ts
> ```ts
> async function bootstrap() {
>   const app = await NestFactory.create(AppModule);
>   // ...
>   app.useWebSocketAdapter(new SocketIoAdapter(app, corsOrigins));
> }
> ```

It seem not working

**Comment by JamesLMilner** [comment]
Anyone facing the issues when using the latest `socket.io-client` (3.x), as per https://github.com/nestjs/nest/issues/5832, you can install `2.3.1` and set your `transports` in your `WebSocketGateway` options to include `polling`. That seemed to work for me for now.

**Comment by JulianMiranda** [comment]
Hi, when I create the file socket-io.adapter.ts, I get a cookie error: { name: 'io', ....}, name : 'io' gives me an error

**Comment by MickL** [comment]
Took me a while to figure out `socket.io-client` latest is now on 3.x but `socket.io-platform` still uses 2.x. He was always connecting and then disconnecting without any error message.

**Comment by MickL** [comment]
I updated the adapter so it works now. Also changed the origins types to be on par with socket.io 3. Anyhow dont know about the cookie thing: I just removed the name and there is also a note about cookies in socket.io 3.0 here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html#No-more-cookie-by-default

```
import { INestApplicationContext } from '@nestjs/common';
import { isFunction, isNil } from '@nestjs/common/utils/shared.utils';
import {
  AbstractWsAdapter,
  MessageMappingProperties,
} from '@nestjs/websockets';
import { DISCONNECT_EVENT } from '@nestjs/websockets/constants';
import { fromEvent, Observable } from 'rxjs';
import { filter, first, map, mergeMap, share, takeUntil } from 'rxjs/operators';
import { Server } from 'socket.io';
import { CustomOrigin } from '@nestjs/common/interfaces/external/cors-options.interface';

// TODO: Using this until socket.io v3 is part of Nest.js, see: https://github.com/nestjs/nest/issues/5676
export class SocketIoAdapter extends AbstractWsAdapter {
  constructor(
    appOrHttpServer?: INestApplicationContext | any,
    private corsOrigin?: boolean | string | RegExp | (string | RegExp)[] | CustomOrigin,
  ) {
    super(appOrHttpServer);
  }

  public create(
    port: number,
    options?: any & { namespace?: string; server?: any },
  ): any {
    if (!options) {
      return this.createIOServer(port);
    }
    const { namespace, server, ...opt } = options;
    return server && isFunction(server.of)
      ? server.of(namespace)
      : namespace
        ? this.createIOServer(port, opt).of(namespace)
        : this.createIOServer(port, opt);
  }

  public createIOServer(port: number, options?: any): any {
    if (this.httpServer && port === 0) {
      const s = new Server(this.httpServer, {
        cors: {
          origin: this.corsOrigin,
          methods: ['GET', 'POST'],
          credentials: true,
        },
        cookie: {
          httpOnly: true,
          path: '/',
        },
        // Allow 1MB of data per request.
        maxHttpBufferSize: 1e6,
      });

      return s;
    }
    return new Server(port, options);
  }

  public bindMessageHandlers(
    client: any,
    handlers: MessageMappingProperties[],
    transform: (data: any) => Observable<any>,
  ) {
    const disconnect$ = fromEvent(client, DISCONNECT_EVENT).pipe(
      share(),
      first(),
    );

    handlers.forEach(({ message, callback }) => {
      const source$ = fromEvent(client, message).pipe(
        mergeMap((payload: any) => {
          const { data, ack } = this.mapPayload(payload);
          return transform(callback(data, ack)).pipe(
            filter((response: any) => !isNil(response)),
            map((response: any) => [response, ack]),
          );
        }),
        takeUntil(disconnect$),
      );
      source$.subscribe(([response, ack]) => {
        if (response.event) {
          return client.emit(response.event, response.data);
        }
        isFunction(ack) && ack(response);
      });
    });
  }

  public mapPayload(payload: any): { data: any; ack?: Function } {
    if (!Array.isArray(payload)) {
      return { data: payload };
    }
    const lastElement = payload[payload.length - 1];
    const isAck = isFunction(lastElement);
    if (isAck) {
      const size = payload.length - 1;
      return {
        data: size === 1 ? payload[0] : payload.slice(0, size),
        ack: lastElement,
      };
    }
    return { data: payload };
  }
}
```

**Comment by JulianMiranda** [comment]
Hello Mick, thank you very much for contacting me with the solution, I am
very grateful. Greetings Julian

**Comment by danielehrhardt** [comment]
> I updated the adapter so it works now. Also changed the origins types to be on par with socket.io 3. Anyhow dont know about the cookie thing: I just removed the name and there is also a note about cookies in socket.io 3.0 here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html#No-more-cookie-by-default
> 
> ```ts
> import { INestApplicationContext } from '@nestjs/common';
> import { isFunction, isNil } from '@nestjs/common/utils/shared.utils';
> import {
>   AbstractWsAdapter,
>   MessageMappingProperties,
> } from '@nestjs/websockets';
> import { DISCONNECT_EVENT } from '@nestjs/websockets/constants';
> import { fromEvent, Observable } from 'rxjs';
> import { filter, first, map, mergeMap, share, takeUntil } from 'rxjs/operators';
> import { Server } from 'socket.io';
> import { CustomOrigin } from '@nestjs/common/interfaces/external/cors-options.interface';
> 
> // TODO: Using this until socket.io v3 is part of Nest.js, see: https://github.com/nestjs/nest/issues/5676
> export class SocketIoAdapter extends AbstractWsAdapter {
>   constructor(
>     appOrHttpServer?: INestApplicationContext | any,
>     private corsOrigin?: boolean | string | RegExp | (string | RegExp)[] | CustomOrigin,
>   ) {
>     super(appOrHttpServer);
>   }
> 
>   public create(
>     port: number,
>     options?: any & { namespace?: string; server?: any },
>   ): any {
>     if (!options) {
>       return this.createIOServer(port);
>     }
>     const { namespace, server, ...opt } = options;
>     return server && isFunction(server.of)
>       ? server.of(namespace)
>       : namespace
>         ? this.createIOServer(port, opt).of(namespace)
>         : this.createIOServer(port, opt);
>   }
> 
>   public createIOServer(port: number, options?: any): any {
>     if (this.httpServer && port === 0) {
>       const s = new Server(this.httpServer, {
>         cors: {
>           origin: this.corsOrigin,
>           methods: ['GET', 'POST'],
>           credentials: true,
>         },
>         cookie: {
>           httpOnly: true,
>           path: '/',
>         },
>         // Allow 1MB of data per request.
>         maxHttpBufferSize: 1e6,
>       });
> 
>       return s;
>     }
>     return new Server(port, options);
>   }
> 
>   public bindMessageHandlers(
>     client: any,
>     handlers: MessageMappingProperties[],
>     transform: (data: any) => Observable<any>,
>   ) {
>     const disconnect$ = fromEvent(client, DISCONNECT_EVENT).pipe(
>       share(),
>       first(),
>     );
> 
>     handlers.forEach(({ message, callback }) => {
>       const source$ = fromEvent(client, message).pipe(
>         mergeMap((payload: any) => {
>           const { data, ack } = this.mapPayload(payload);
>           return transform(callback(data, ack)).pipe(
>             filter((response: any) => !isNil(response)),
>             map((response: any) => [response, ack]),
>           );
>         }),
>         takeUntil(disconnect$),
>       );
>       source$.subscribe(([response, ack]) => {
>         if (response.event) {
>           return client.emit(response.event, response.data);
>         }
>         isFunction(ack) && ack(response);
>       });
>     });
>   }
> 
>   public mapPayload(payload: any): { data: any; ack?:  () => any } {
>     if (!Array.isArray(payload)) {
>       return { data: payload };
>     }
>     const lastElement = payload[payload.length - 1];
>     const isAck = isFunction(lastElement);
>     if (isAck) {
>       const size = payload.length - 1;
>       return {
>         data: size === 1 ? payload[0] : payload.slice(0, size),
>         ack: lastElement,
>       };
>     }
>     return { data: payload };
>   }
> }
> ```
> 
> main.ts
> `app.useWebSocketAdapter(new SocketIoAdapter(app, true));`

Somehow it still does the reconnect on my side..

**Comment by gp187** [comment]
Any news?

**Comment by JulianMiranda** [comment]
Hi Gabriel, I still haven’t found a solution, so I downloaded the version
of the front to 2

**Comment by MickL** [comment]
@JulianMiranda your problem might have todo with CORS, the correct url/path in client,  or you dont actually use v3 on client or server. But this isnt a support thread. 

I would also be very interested for any news on this being implemented in nest.js :)

**Comment by JulianMiranda** [comment]
Hi Mike, the problem is that '@nestjs/websockets' uses socket-io version 2.
in its internal configuration, so when I installed socket version 3. on my
client it was not supported.
I finally solved it by using version 2. in my client until they updated
'@nestjs/websockets' with socket 3 dependency.

**Comment by gp187** [comment]
The problem is definitely the v2/v3 incompatibility. V3 has some great new features that we need to take advantage of.

maybe a `@nestjs/platform-ws3` ?

**Comment by steinroe** [comment]
Would it be possible to add this information to the docs? It took me half a day to figure this out, since there is no error message at all, just a constant connection - disconnection loop on the server side.

**Comment by JulianMiranda** [comment]
I also spent 1 day watching why it was connecting and disconnecting. I
finally figured it out because the socket client has a
socket.io("connect_error",()=>
{console.log(error)} function. And so it told me that I was connecting a
socket 2 with a socket 3. But in Nest I haven't tested if I can put this
socket.io("connect_error"()=> {console.log(error)}.

**Comment by MickL** [comment]
I agree with both of you, should be documented or something, took me also couple of hours. Searched for everything else but the  this...

Maybe having no error message should also be reported socket.io itself

**Comment by JulianMiranda** [comment]
Of course there are several problems, first of all there is no way that
@nestjs/websockets has no way to work with socket 3. It is also something
uncomfortable that socket does not allow to work between the 2 versions, or
that Nest does not warn of the problem and just connects and disconnects. I
hope Nest doesn't take long to upgrade the @nestjs/websockets dependency to
socke t3.

**Comment by jmcdo29** [comment]
> Would it be possible to add this information to the docs?

@steinroe absolutely! Would you like to make a Pull Request? Just a quick mention that currently Socket.IO v3 is not yet supported.

**Comment by MickL** [comment]
The problem occurs after adding socket.io to nestjs and then using `npm i socketio-client` in the frontend.

Does the client add version information to the socket object? Or is there any value that is not on client v2 so we can detect that and show an error in Nestjs?

**Comment by matinzd** [comment]
Any updates on this?

**Comment by jmcdo29** [comment]
> Any updates on this?

When there is an update on this, the Pull Request will be linked. Until then, assume this is a Work In Progress. Creating unnecessary noise is just distracting.

**Comment by matinzd** [comment]
> > Any updates on this?
> 
> When there is an update on this, the Pull Request will be linked. Until then, assume this is a Work In Progress. Creating unnecessary noise is just distracting.

Sorry for that.

**Comment by Seovos** [comment]
> For those that need socket.io 3 support now, here is a socket.io adapter from the official nestjs sources adjusted for version 3.0.
> 
> #### socket-io.adapter.ts
> ```ts
> import { INestApplicationContext } from '@nestjs/common';
> import { isFunction, isNil } from '@nestjs/common/utils/shared.utils';
> import {
>   AbstractWsAdapter,
>   MessageMappingProperties,
> } from '@nestjs/websockets';
> import { DISCONNECT_EVENT } from '@nestjs/websockets/constants';
> import { fromEvent, Observable } from 'rxjs';
> import { filter, first, map, mergeMap, share, takeUntil } from 'rxjs/operators';
> import { Server } from 'socket.io';
> 
> export class SocketIoAdapter extends AbstractWsAdapter {
>   constructor(
>     appOrHttpServer?: INestApplicationContext | any,
>     private readonly corsOrigins = [],
>   ) {
>     super(appOrHttpServer);
>   }
> 
>   public create(
>     port: number,
>     options?: any & { namespace?: string; server?: any },
>   ): any {
>     if (!options) {
>       return this.createIOServer(port);
>     }
>     const { namespace, server, ...opt } = options;
>     return server && isFunction(server.of)
>       ? server.of(namespace)
>       : namespace
>       ? this.createIOServer(port, opt).of(namespace)
>       : this.createIOServer(port, opt);
>   }
> 
>   public createIOServer(port: number, options?: any): any {
>     if (this.httpServer && port === 0) {
>       const s = new Server(this.httpServer, {
>         cors: {
>           origin: this.corsOrigins,
>           methods: ['GET', 'POST'],
>           credentials: true,
>         },
>         cookie: {
>           name: 'io',
>           httpOnly: true,
>           path: '/',
>         },
>         // Allow 1MB of data per request.
>         maxHttpBufferSize: 1e6,
>       });
> 
>       return s;
>     }
>     return new Server(port, options);
>   }
> 
>   public bindMessageHandlers(
>     client: any,
>     handlers: MessageMappingProperties[],
>     transform: (data: any) => Observable<any>,
>   ) {
>     const disconnect$ = fromEvent(client, DISCONNECT_EVENT).pipe(
>       share(),
>       first(),
>     );
> 
>     handlers.forEach(({ message, callback }) => {
>       const source$ = fromEvent(client, message).pipe(
>         mergeMap((payload: any) => {
>           const { data, ack } = this.mapPayload(payload);
>           return transform(callback(data, ack)).pipe(
>             filter((response: any) => !isNil(response)),
>             map((response: any) => [response, ack]),
>           );
>         }),
>         takeUntil(disconnect$),
>       );
>       source$.subscribe(([response, ack]) => {
>         if (response.event) {
>           return client.emit(response.event, response.data);
>         }
>         isFunction(ack) && ack(response);
>       });
>     });
>   }
> 
>   public mapPayload(payload: any): { data: any; ack?: Function } {
>     if (!Array.isArray(payload)) {
>       return { data: payload };
>     }
>     const lastElement = payload[payload.length - 1];
>     const isAck = isFunction(lastElement);
>     if (isAck) {
>       const size = payload.length - 1;
>       return {
>         data: size === 1 ? payload[0] : payload.slice(0, size),
>         ack: lastElement,
>       };
>     }
>     return { data: payload };
>   }
> }
> ```
> 
> #### main.ts
> ```ts
> async function bootstrap() {
>   const app = await NestFactory.create(AppModule);
>   // ...
>   app.useWebSocketAdapter(new SocketIoAdapter(app, corsOrigins));
> }
> ```

An error occurred with 'Server' only refers to a type, but is being used as a value here.

**Comment by ak2g** [comment]
> An error occurred with 'Server' only refers to a type, but is being used as a value here.

 npm i socket.io  
 should help

**Comment by DblK** [comment]
For me, I have this error on `socket-io.adapter.js:39`:
```js
const s = new socket_io_1.Server(this.httpServer, {
          ^
TypeError: socket_io_1.Server is not a constructor
```

Any idea?

**Comment by kamilmysliwiec** [comment]
We'll update `@nestjs/platform-socket.io` to use socket.io 3.0 in the next major release (v8) which is coming very shortly.
