### ISSUE TITLE
Can't inject request into validation constraint

### ISSUE THREAD

**Issue by gulaandrij** [nestjs/nest#5677]
## Current behavior
Can't inject Request into validation constraint

## Input Code
https://github.com/gulaandrij/nest-request

## Environment

<pre><code>
Nest version: latest

**Comment by jmcdo29** [comment]
[This has](https://github.com/nestjs/nest/issues/5566) [already](https://github.com/nestjs/nest/issues/1955) [been discussed](https://github.com/nestjs/nest/issues/528). In short, you can't use `REQUEST` scoped providers with validation constraints with `class-validator` because `REQUEST` is a framework feature and`class-validator` is third-party (not a direct part of the framework, it just integrates nicely).

**Comment by gulaandrij** [comment]
@jmcdo29 is there way to get user in constrain?

**Comment by jmcdo29** [comment]
Custom decorator ([param decorator](https://docs.nestjs.com/custom-decorators)) Or just validate the shape of the request with `class-validator` and use specific logic inside of services for what you're doing?

**Comment by gulaandrij** [comment]
I need to take user id from request and use it in db query. User object is injected by passport strategy

**Comment by netojose** [comment]
This can help: https://dev.to/avantar/injecting-request-object-to-a-custom-validation-class-in-nestjs-5dal

**Comment by constb** [comment]
@netojose actually this is insecure – attacker may supplement their own `_requestContext` in request data and access API as an arbitrary user. You could probably replace string constant with a ES6 `Symbol`, but I believe the best approach would be to rely on node's `AsyncLocalStorage` and avoid modifying request data entirely.

**Comment by netojose** [comment]
@constb , I believe that using a Symbol as a key is much smarter than a constant with the value `_requestContext`. But, that makes no difference. Even if someone sends something in the `_requestContext`, that something will be overwritten on the server by the correct authenticated user.

**Comment by constb** [comment]
> @constb , I believe that using a Symbol as a key is much smarter than a constant with the value `_requestContext`. But, that makes no difference. Even if someone sends something in the `_requestContext`, that something will be overwritten on the server by the correct authenticated user.

@netojose provided there actually IS an authenticated user :) `Symbol` is better because no user input can override those under any circumstances. And the use of ALS separates context data from request entirely and makes it accessible in functions that don't receive the request object at all.

**Comment by netojose** [comment]
> > @constb , I believe that using a Symbol as a key is much smarter than a constant with the value `_requestContext`. But, that makes no difference. Even if someone sends something in the `_requestContext`, that something will be overwritten on the server by the correct authenticated user.
> 
> @netojose provided there actually IS an authenticated user :) `Symbol` is better because no user input can override those under any circumstances. And the use of ALS separates context data from request entirely and makes it accessible in functions that don't receive the request object at all.

I tried to use `symbol`, but didn't work. But now I read again your message, and and your suggestion about `AsyncLocalStorage` it's an awesome idea. I will update my code on an application I'm changing the request object. Thanks.
