### ISSUE TITLE
Passing Express instance Error for build

### ISSUE THREAD

**Issue by FrancisVarga** [nestjs/nest#568]
By creating my own epxress instance:
```js
const exprs = express();
const server = await NestFactory.create(AppModule, exprs);
```
I get an build error:
![image](https://user-images.githubusercontent.com/142090/38847931-b88280f0-4236-11e8-926b-60f2711045cf.png)

```bash
src/server.ts(47,54): error TS2560: Value of type 'Express' has no properties in common with type 'NestApplicationOptions'. Did you mean to call it?

47   const server = await NestFactory.create(AppModule, exprs);
```

I'm following this:
https://docs.nestjs.com/faq/express-instance

**Comment by FrancisVarga** [comment]
Nevermind just checked, missing one parameter:
```js
const server = await NestFactory.create(AppModule, exprs, {cors: true});
```

**Comment by HaveF** [comment]
@FrancisVarga How did you find the solution? 👨 The FAQ does not mention that

**Comment by FrancisVarga** [comment]
@HaveF sorry though the last comment was the solution.
