### ISSUE TITLE
Best practices of nest deployment with docker

### ISSUE THREAD

**Issue by rossowu-towify** [nestjs/nest#5682]
when i use docker deploy my nest api with docker. i have two questions. 

1.  How to build app src with all dependencies into a single file?
2.  Where is the best practice document about docker deployment？

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
