### ISSUE TITLE
metatype is not a constructor

### ISSUE THREAD

**Issue by zhangjindong** [nestjs/nest#5685]
## Bug Report
metatype is not a constructor
## Current behavior

![image](https://user-images.githubusercontent.com/5567162/98761327-24c68a00-2410-11eb-9a5c-33ad1f0422a0.png)

## Input Code

```ts
import { ShareModule } from '@app/share';
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [ShareModule],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

```

```ts

import { Module } from '@nestjs/common';
import { API_DOCUMENT } from '.';
import { ShareService } from './share.service';

@Module({
  providers: [
    ShareService,
    {
      provide: API_DOCUMENT,
      useFactory: () => {},
    },
  ],
  exports: [ShareService],
})
export class ShareModule {}

```

## Environment

<pre><code>
Nest version: 7.5.2

 
For Tooling issues:
- Node version: v14.0.0.0  
- Platform:  Linux

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by zhangjindong** [comment]
> Please provide a minimum reproduction repository

https://github.com/zhangjindong/nest_test_libs.git

**Comment by jmcdo29** [comment]
Without running the code, I'm 90% certain that this is due to `import ... from '.';`. You've created a circular import due to how barrel files work. Try importing from the file directly and see if that fixes it

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/fundamentals/circular-dependency

![image](https://user-images.githubusercontent.com/23244943/98807429-ee423c80-241a-11eb-87c0-9b273df5e807.png)

**Comment by zhangjindong** [comment]
> 如果不运行代码，我 90% 肯定这是由于。由于桶文件的工作方式，您已经创建了循环导入。尝试直接从文件导入，看看是否修复了它`import ... from '.';`

I understand. Thank you！

**Comment by dimitropoulos** [comment]
For anyone else searching around that found this, I had this problem because of the following

```ts
export const MyGuard = (someArgumentsMyInlineGuardNeeds: any) => applyDecorators(
  UseGuards(
    AuthGuard('sessionAuth'),
    () => { ... use someArgumentsMyInlineGuardNeeds ... },  // custom inline guard
  ),
)
```

The problem here is that the custom inline guard _was not invoked_.  I was moving quickly (too quickly, perhaps) and wanted to skip the step of creating a separate factory and instead just rely on scoping to give me access to the variables I needed.  The solution was to use an iife or just extract and pass the data I need to my guard as an argument (which is what I did).

**Comment by 2donny** [comment]
@dimitropoulos
You saved my life
