### ISSUE TITLE
ValidationPipe not working with a mixin

### ISSUE THREAD

**Issue by pbn4** [nestjs/nest#5688]
## Describe the regression

Global validation pipe is probably not retrieving type through reflection correctly. 

## Input Code

The code below used to work for me starting from July, but today I must have upgraded a dependency that caused a regression, although I'm unable to tell which one, hence the issue. Looking for some hints. 

I have a generic factory function which procudes a controller of some type `T`. This type `T` is used with `@Body()` and so far was picked up correctly by the ValidationPipe and the validation was triggered, validation messages were returned if the payload was not valid:

```
export interface IController<T> {
  hello(body: T);
}

export function Factory<T>(): ClassType<IController<T>> {
  @Controller()
  class ControllerHost<T> implements IController<T> {
    @Post()
    hello(@Body() body: T) {
      return "hello"
    }
  }
  return ControllerHost;
}

export class MyDto {
  @Expose()
  @IsDefined()
  @IsString()
  hello: string;
}

export class AppController extends Factory<MyDto>() {}
```

Validation pipe setup:

```
  app.useGlobalPipes(new ValidationPipe({
    transform: true,
    whitelist: true
  }))
```

## Environment
Nest version: ^7.0.0

For Tooling issues:
- Node version: Node 14.15.0
- Platform:  Mac

Others:
Reproduction repo: https://github.com/pbn4/nestj-validation-pipe-problem

Q1: Is there a way to pass ClassType as a value to the `@Body()` ? I could pass it through factory function arguments and the 
problem would be solved.

**Comment by kamilmysliwiec** [comment]
This has been discussed many times in the past. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by kamilmysliwiec** [comment]
More on this topic:
https://github.com/nestjs/nest/issues/965#issuecomment-415149081
https://github.com/nestjs/nest/issues/2189#issuecomment-492567964
