### ISSUE TITLE
Custom filters

### ISSUE THREAD

**Issue by TrejGun** [nestjs/nest#5689]
This is bug report and documentation request

So I have copied examples from 
https://docs.nestjs.com/exception-filters
but it doesn't work under some conditions

you can clone this repo to reproduce what i say
https://github.com/TrejGun/error-handling-in-nestjs-microservices

to run example execute
```sh
git clone git@github.com:TrejGun/error-handling-in-nestjs-microservices.git
cd error-handling-in-nestjs-microservices
npm i
npm run bootstrap
npm start
```

1 Error passed from microservice using RMQ transport does not have type of RpcException
so i can't rely on catch decorator to filter it
```ts
@Catch(RpcException)
```
you can check this behavior by navigating to 
http://127.0.0.1:3001/rpc/extended/TEAPOT

2 Lets assume I throw RpcException directly from my code then I catch it with

```ts
@Catch(RpcException)
export class CustomRpcExceptionFilter implements RpcExceptionFilter<RpcException> {
  catch(exception: RpcException): Observable<any> {
    return throwError(exception.getError());
  }
}
```

I expect this new error is catched by default exception handler but it does not
you can check this behavior by navigating to 
http://127.0.0.1:3001/rpc/custom/TEAPOT

3 in fact it looks like any call to @UseFilters() unbinds default exception handler
documentation does not say a word about rebinding default handler tho

currently only this code prints exception

```ts
@Catch()
export class ExtendedHttpExceptionFilter extends BaseExceptionFilter implements ExceptionFilter {
  catch(exception: any, host: ArgumentsHost) {
    if (exception instanceof HttpException) {
      return super.catch(exception, host);
    } else {
      return super.catch(new HttpException(exception.message), host)
    }
  }
}
```

which does not seems to be a really good solution

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by TrejGun** [comment]
@kamilmysliwiec 
i spend 2 hours compiling repro for you and you just close the issue without reading
and this is your standard way of solving issues

you know what i do in my spare time? 
i write tutorials to your framework because your docs sucks and everybody knows this
but once a year I see a bug and create an issue to be slaped in a face
here is a good example https://github.com/nestjs/graphql/issues/571

no i don't need gratitude for tutorials I just need my code written for 6.8.2 works again with 7.5.1
without 4 hours of googling for pieces of knowledge somewhere deep in a pile of stackoverflow

**Comment by kamilmysliwiec** [comment]
The fact that you don't understand a specific feature doesn't mean that you have the privilege of being impolite to others. Your code is simply wrong so I've closed the issue. If you see any potential areas we could improve in the documentation, PRs are more than welcome https://github.com/nestjs/docs.nestjs.com
