### ISSUE TITLE
Websocket gateway returns 404 on connection

### ISSUE THREAD

**Issue by evilfant** [nestjs/nest#5691]
## Current behavior
When client is trying to connect via socket to the Websocket Gateway it takes response with code 404  
Chrome dev tools:
<img width="881" alt="Screen Shot 2020-11-12 at 6 07 18 PM" src="https://user-images.githubusercontent.com/6253480/98957216-fdf07c80-2511-11eb-8051-4b767f56fabe.png">

## Input Code
Project with bug: https://github.com/evilfant/bug_nest-express-socket  
The problem is related to combination of Nest + express + Websocket  
Bug appears only if to start server with `express.listen(3000)`.  
If to start `nestApp.listen(3000)` everything will be fine  
https://github.com/evilfant/bug_nest-express-socket/blob/main/src/main.ts#L17

## Expected behavior
Client connects via websocket successfully  

## Environment

<pre><code>
Nest version: 7.5.4

Node version: 12.18.1
</code></pre>

**Comment by kamilmysliwiec** [comment]
This issue was discussed a few times in the past and the current behavior is correct. If you call `listen()` on the express instance, you won't start the underlying HTTP server to which WS gateways are bound. Is there any reason why you want to call `listen()` on express instance instead of Nest app?

**Comment by evilfant** [comment]
> This issue was discussed a few times in the past and the current behavior is correct. If you call `listen()` on the express instance, you won't start the underlying HTTP server to which WS gateways are bound. Is there any reason why you want to call `listen()` on express instance instead of Nest app?

Yes, I want to setup [Multiple simultaneous servers](https://docs.nestjs.com/faq/multiple-servers#multiple-simultaneous-servers) http and https (just like in the documentation)

**Comment by kamilmysliwiec** [comment]
WebSocket gateways are bound to a particular application. Since each gateway in fact represents a separate server (or namespace), which server should it represent if you start 2 different servers? If you want to listen to WS messages on 2 different ports (and so create N gateways in which N = number of servers), you should simply create N Nest application instances.

**Comment by evilfant** [comment]
@Haltarys
Here is my code from that project
I hope it will help you
```ts
const options: NestApplicationOptions = dev ? { httpsOptions } : {};
const app = await NestFactory.create<NestExpressApplication>(AppModule, new ExpressAdapter(express), options);

await app.init()
app.listen(port, (error?: Error) => {
    if (error) {
        // eslint-disable-next-line no-console
        console.error(error);

        return;
    }

    if (dev) {
        // eslint-disable-next-line no-console
        console.log(`Server started on: https://localhost:${port}`);
        https.globalAgent.options.rejectUnauthorized = false;
    }
});
```

**Comment by Haltarys** [comment]
I managed to solve my issue by merging my code with examples from [this issue](https://github.com/nestjs/nest/issues/5407).
Leaving it here for posterity:
```ts
async function bootstrap() {
  const server = express();
  const app = await NestFactory.create(AppModule, new ExpressAdapter(server));
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
      whitelist: true,
      forbidNonWhitelisted: true,
    }),
  );

  const launchConfigService = app.get(LaunchConfigService);

  app.enableCors({ origin: launchConfigService.corsOrigin });

  if (launchConfigService.isProduction) {
    const httpsServer = https.createServer(
      launchConfigService.httpsOptions!,
      server,
    );

    const adapter = new IoAdapter(httpsServer);
    app.useWebSocketAdapter(adapter);
    await app.init();
    httpsServer.listen(launchConfigService.port);
  } else {
    const httpServer = http.createServer(server);
    const adapter = new IoAdapter(httpServer);
    app.useWebSocketAdapter(adapter);
    await app.init();
    httpServer.listen(launchConfigService.port);
  }
}
```
Thank you @evilfant for such a quick reply!

**Comment by wfk007** [comment]
`@nestjs/core@8.4.4` with `@nestjs/platform-socket.io@10.0.3` and `@nestjs/websockets@10.0.3` will also get a response with 404, dam!
