### ISSUE TITLE
Add better support to .env files

### ISSUE THREAD

**Issue by Xwil** [nestjs/nest#5692]
## Is your feature request related to a problem? Please describe.
ConfigModule is hard to use when I have seprate .env files, such like `.env.production` and `.env.development`。
ConfigModule will load .env file,but not .env.production or .env.development by default.
So I have to set envFilePath like this:
``` ts
    ConfigModule.forRoot({
      envFilePath: ['.env.development', '.env.production'],
    }),
```
And both file have same properties, so `process.env.DB` will always get value from `.env.development` file.

My currently solution is use `cross-env`,  set `NODE_ENV`:
```
// package.json

...
"scripts":{
    "dev": "cross-env NODE_ENV=development nest start --watch ",
    "prod": "cross-env NODE_ENV=production node dist/main",
}
```

and then change ConfigModule parameters:
```
    ConfigModule.forRoot({
      envFilePath: [`.env.${process.env.NODE_ENV}`],
    }),
```

then I can get right value from right .env file.

## Describe the solution you'd like
1. nest.js should set `process.env.NODE_ENV` automaticlly when run scripts.
2. ConfigModule should load the *right* .env file, not just .env as default. 

## What is the motivation / use case for changing the behavior?
For better experience.

P.S: I'm not sure is nest.js support this feature already and I'm done some wrong thing, or nest.js has another solution for this problem

**Comment by jmcdo29** [comment]
How do you suggest Nest knows what environment you're in? The `start:prod` script that Nest ships with is a simple `node` script, whereas `start` and `start:dev` use the `@nestjs/cli`. I'm of the persuasion that the `NODE_ENV` variable should be set in the script, something like `export NODE_ENV=production node ./dist/main` or in the server's environment itself. 

Also, following the [12-factor application](https://12factor.net/config), there should only really be one `.env` file per environment, but that's more of an ideology. Nest allows you to set the name of the file to get around this if you so please (as you've mentioned)

**Comment by Xwil** [comment]
> How do you suggest Nest knows what environment you're in? The `start:prod` script that Nest ships with is a simple `node` script, whereas `start` and `start:dev` use the `@nestjs/cli`. I'm of the persuasion that the `NODE_ENV` variable should be set in the script, something like `export NODE_ENV=production node ./dist/main` or in the server's environment itself.
> 
> Also, following the [12-factor application](https://12factor.net/config), there should only really be one `.env` file per environment, but that's more of an ideology. Nest allows you to set the name of the file to get around this if you so please (as you've mentioned)

I think one solution is :
1. When run `start` or `start:dev` by `@nestjs/cli`, `NODE_ENV` set to development by cli.
2. When run `build`, cli inject the code about set `NODE_ENV` to `dist/main`.
3.In ConfigModule, if `envFilePath` not set, then try load `.env` file with `NODE_ENV`.

I'm not fimilar with backend development, so I don't know whether `.env`  there should only really be one .env file per environment.

As `Create-react-app` support .env files by:

> Files on the left have more priority than files on the right:
> 
> npm start: .env.development.local, .env.local, .env.development, .env
> npm run build: .env.production.local, .env.local, .env.production, .env
> npm test: .env.test.local, .env.test, .env (note .env.local is missing)

https://create-react-app.dev/docs/adding-custom-environment-variables

**Comment by kamilmysliwiec** [comment]
> nest.js should set process.env.NODE_ENV automaticlly when run scripts.

This would lead to tons of unexpected side-effects.

> My currently solution is use cross-env, set NODE_ENV:

Your solution is completely fine.

**Comment by vaneeckhoutnicolas** [comment]
Hello,

This could be consider as an old thread but Nestjs initialy by design through installing "@nestjs/config" was working in order to read env file. Currently, It doesn't seem to not work anymore and seems very difficult to debug as related to "process.env".

Is there a well breaking changes related to a node version or something like that?

I would like to avoid the dotenv workaround which anyway should be embedded in teh nest config.

Thanks,
Nico

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
