### ISSUE TITLE
I learned more about gateway documentation

### ISSUE THREAD

**Issue by LeonYanghaha** [nestjs/nest#5693]
I used Nestjs + Federation to build the graphql service, but I found that there were very few documents about gateway, [only linked ones](https://docs.nestjs.com/graphql/federation#federated-example-gateway). What documents should I read if I want to study gateway in a comprehensive way? who can tell me ? thank you.

**Comment by kamilmysliwiec** [comment]
https://www.apollographql.com/docs/federation/

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
