### ISSUE TITLE
7.5.x replacer() ModuleTokenFactory change causes dynamicmodules with useFactory() to load twice

### ISSUE THREAD

**Issue by glachac** [nestjs/nest#5698]
## Regression

The dependency injection system is loading modules multiple times even though they should be loaded once.  

## Potential Commit/PR that introduced the regression**
This is the commit that caused the change
https://github.com/nestjs/nest/commit/2344e7241813adae2294f211bb285bea4faaa24d

If I hand change just this commit code in my local node-modules directory, it behaves as it did before.

## Describe the regression

DynamicModules are loaded twice if  the useFactory() method code bodies are different.  It seems that the replacer() method in module-token-factory.ts is generating a different token, even though the modules are defined to be the same.   I do not think this change was intentional.

It is a pretty common pattern in Dynamic modules to have multiple static methods return the DynamicModule definition for a single module.  If the return value isn't absolutely identical, they now appear to be identified as different modules instead of the same.  This is not the same behavior as prior to 7.5.  A common example of this pattern is the ConfigurationModule with forRoot() and forFeature()

## Input Code

Full sample project demonstrating regression is here:

https://github.com/glachac/nestjs-moduletoken-bug

This is the extracted skeleton "configuration" module from that repo which shows the two static methods that return the dynamic module information.  If the bodies of the two useFactory() methods are identical, it only loads the module once.  Any difference and it loads twice.

```ts
export class ConfigurationModule {
  constructor() {
    console.log('ConfigurationModule constructor');
  }

  static forRoot(filename2: string): DynamicModule {
    console.log(`ConfigurationModule.forRoot`);

    return {
      global: true,
      module: ConfigurationModule,
      providers: [
        {
          provide: CONFIGURATION_SERVICE,
          useFactory: () => {
            // If the two useFactory() bodies look different, then ConfigurationModule is
            // is loaded twice - anything from a log line, to passing a different arg
            // If you change filename2 ==> filename, then it only gets loaded once
            return this.factory(filename2);
          },
        },
      ],
      exports: [CONFIGURATION_SERVICE],
    };
  }

  static forFeature(filename: string): DynamicModule {
    console.log(`ConfigurationModule.forFeature`);
    return {
      global: true,
      module: ConfigurationModule,
      providers: [
        {
          provide: CONFIGURATION_SERVICE,
          useFactory: () => {
            return this.factory(filename);
          },
        },
      ],
      exports: [CONFIGURATION_SERVICE],
    };
  }

  
  private static _cfgService: ConfigService;

  private static factory(options: string) {
      if (this._cfgService) {
          return this._cfgService;
      } else {
          this._cfgService = new ConfigService(options);
          return this._cfgService;
      }
  }
}
```

## Expected behavior/code

Expected (7.4.4 behavior)
```
ConfigurationModule.forFeature
ConfigurationModule.forRoot
[Nest] 350465   - 11/13/2020, 10:33:14 AM   [NestFactory] Starting Nest application...
[Nest] 350465   - 11/13/2020, 10:33:14 AM   ConfigService Constructor: cfgfile
[Nest] 350465   - 11/13/2020, 10:33:14 AM   Created AppServer
ConfigurationModule constructor
[Nest] 350465   - 11/13/2020, 10:33:14 AM   [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 350465   - 11/13/2020, 10:33:14 AM   [InstanceLoader] ConfigurationModule dependencies initialized +0ms
[Nest] 350465   - 11/13/2020, 10:33:14 AM   Created WidgetService CFG: cfg
[Nest] 350465   - 11/13/2020, 10:33:14 AM   [InstanceLoader] WidgetModule dependencies initialized +1ms
[Nest] 350465   - 11/13/2020, 10:33:14 AM   `dummy()`
```

What happens under (7.5.1):
```
ConfigurationModule.forFeature
ConfigurationModule.forRoot
[Nest] 357422   - 11/13/2020, 11:02:15 AM   [NestFactory] Starting Nest application...
[Nest] 357422   - 11/13/2020, 11:02:15 AM   ConfigService Constructor: cfgfile
[Nest] 357422   - 11/13/2020, 11:02:15 AM   Created AppServer
ConfigurationModule constructor
ConfigurationModule constructor
[Nest] 357422   - 11/13/2020, 11:02:15 AM   [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 357422   - 11/13/2020, 11:02:15 AM   [InstanceLoader] ConfigurationModule dependencies initialized +0ms
[Nest] 357422   - 11/13/2020, 11:02:15 AM   [InstanceLoader] ConfigurationModule dependencies initialized +0ms
[Nest] 357422   - 11/13/2020, 11:02:15 AM   Created WidgetService CFG: cfg
[Nest] 357422   - 11/13/2020, 11:02:15 AM   [InstanceLoader] WidgetModule dependencies initialized +0ms
[Nest] 357422   - 11/13/2020, 11:02:15 AM   `dummy()`
```

## Environment
<pre><code>
Nest version: 7.4.4 -> 7.5.1

For Tooling issues:
- Node version:  12.18.4
- Platform: Ubuntu 20.04

</code></pre>

**Comment by kamilmysliwiec** [comment]
> DynamicModules are loaded twice if the useFactory() method code bodies are different. It seems that the replacer() method in module-token-factory.ts is generating a different token, even though the modules are defined to be the same. I do not think this change was intentional.

This change was intentional - the previous behavior was incorrect (it was a bug).
Each dynamic module should be instantiated separately (unless the exact same arguments were passed into the same static method).
