### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by solodynamo** [nestjs/nest#57]
Repo should have some contributing guidelines for new people who would like to contribute , I would like to add initial CONTRIBUTING.md which can be modified later.

**Comment by battila7** [comment]
Absolutely, it'd be great to exactly state the guidelines and terms for new contributors (such as me).

**Comment by lsilva-kununu** [comment]
I'm in

**Comment by oreofeolurin** [comment]
Hello, Any update on the Contributing guidelines? I also want to contribute on this project.

**Comment by Caballerog** [comment]
That's a good idea.
