### ISSUE TITLE
TypeError: res.setHeader is not a function at FacebookStrategy.strategy.redirect when using Nestjs with Fastify

### ISSUE THREAD

**Issue by piosystems** [nestjs/nest#5702]
## Current behavior

I am using NestJs with Fastify. I have successfully implemented local as well as jwt strategies for passport-based authentication. The problem however is with Facebook strategy. I have also seen a few complains online with respect to Google strategy when using Fastify with Nestjs, but no solution. When the /facebook route is invoked, the error message printed to the console is **"res.setHeader is not a function TypeError: res.setHeader is not a function at FacebookStrategy.strategy.redirect"*

## Input Code
To reproduce, implement the code available at the URL [](https://github.com/elishaking/nestjs-facebook-login) **but replacing Express with Fastify**.

## Expected behavior
Instructions on what is expected to happen is well documented at the URL [](https://dev.to/elishaking/how-to-implement-facebook-login-with-nestjs-90h).

## Environment
Nest version: 7.0.0
 
For Tooling issues:
- Node version: 14.12.0.
- Platform:  Mac

**Comment by jmcdo29** [comment]
Fastify isn't guaranteed to work with Passport, as Passport is Express middleware. The issue here is that `FastifyReply` has a `header` method to set headers, but no `setHeader` like Express's `Response`. We can add this to the documentation that there's no guarantee for passport to work with fastify engine servers.

**Comment by piosystems** [comment]
Any workaround for _NestJS_ with _fastify_ to be compatible with _passport_? Workaround may involve _NestJS'_ use of [fastify-passport](url), in place of _passport_. 

Meanwhile, here is what I did to overcome the error; it seems untidy to me though, but it could be a clue to a neater solution. I  directly modified _passport/lib/authenticate.js_ in my _node_modules_. All I did was to change any _res.setHeader()_ to _res.raw.setHeader()_ and also changed any _res.end()_ to _res.raw.end()_ knowing that those are the _fastify_ equivalents. I am now able to authenticate with Facebook without further adjustment of my codes.

**Comment by kamilmysliwiec** [comment]
Once `fastify-passport` becomes stable, we'll add support for it in the `@nestjs/passport` package.

**Comment by piosystems** [comment]
Openid-client implementation also does not work for NestJS with fastify, without the appropriate  fastify-passport and fastify-secure-session, etc. An implementation of fastify passport and related support in NestJS will be highly appreciated.

**Comment by pavgup** [comment]
Has the status of this changed at all or is this still waiting for upstream inclusion in the nestjs passport plugin?

**Comment by Nishchit14** [comment]
+1 Highly needed Auth mechanism for Fastify in Nestjs.

**Comment by tristanwagner** [comment]
if that can help anyone I found a workaround by making bindings for express compatibility, it seems to work with passport & fastify 

`
  fastifyInstance.addHook('onRequest', (request, reply, done) => {
    reply.setHeader = function (key, value) {
      return this.raw.setHeader(key, value)
    }
    reply.end = function () {
      this.raw.end()
    }
    request.res = reply
    done()
  })

`

**Comment by raiyansarker** [comment]
> if that can help anyone I found a workaround by making bindings for express compatibility, it seems to work with passport & fastify
> 
> ```js
>   fastifyInstance.addHook('onRequest', (request, reply, done) => {
>     reply.setHeader = function (key, value) {
>       return this.raw.setHeader(key, value)
>     }
>     reply.end = function () {
>       this.raw.end()
>     }
>     request.res = reply
>     done()
>   })
> ```

Where to put it?

**Comment by tristanwagner** [comment]
> > if that can help anyone I found a workaround by making bindings for express compatibility, it seems to work with passport & fastify
> > ```js
> >   fastifyInstance.addHook('onRequest', (request, reply, done) => {
> >     reply.setHeader = function (key, value) {
> >       return this.raw.setHeader(key, value)
> >     }
> >     reply.end = function () {
> >       this.raw.end()
> >     }
> >     request.res = reply
> >     done()
> >   })
> > ```
> 
> Where to put it?

Its been a while but you should put that where after you instanciated the fastify instance. Basically where you would put any onRequest hook. (see the fastify docs)

**Comment by jmcdo29** [comment]
You can add this to the `main.ts` where `fastifyInstance` is  `app.getHttpAdapter().getInstance()`. For any further help on this, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions. Fastify doesn't directly integrate with the base `passport` package, and as such this is not a bug.
