### ISSUE TITLE
Node 14 crash on brand new macOS Catalina

### ISSUE THREAD

**Issue by caiusCitiriga** [nestjs/nest#5709]
## Current behavior
I was having troubles running a project on an iMac that was given to me. Node was continuing to crash with a nasty error, which I had no clue of what it was. 
So I thought that the previous computer owner had something messed up. I decided to re install macOS from scratch, and have a clean environment to start with.

The surprising problem is that on a **brand new**  mac installation without any other software or configurations changes node keeps blowing up with this error:

```
 1: 0x1012e2bc5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a5cb9 node::Abort() [/usr/local/bin/node]
 3: 0x100114d99 node::Abort(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x100259878 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 5: 0x100258e0c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x100258532 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x100a796d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
 8: 0x100a129a2 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
```

#### Strange thing:
I'd expect this to blow on every single machine if there was a "coding" problem, but the problem is that the same code, on a docker container, or on my currently in use macbook pro (running Mojave) runs without any problem. 

I've also tried to downgrade to node 12, but with no effect. The same problem keeps hunting me, and I'm a bit desperate since I was working on this project since a month now, and I have no clue of what could generate this error.

I thought that it was an environment configuration error, so before bothering you with any useless issue, I have formatted the iMac and installed a brand new copy of mac, without any further "touches" except for the installation of node 14. I was in panic when I saw the same error repeat on a clean environment.

## Expected behavior
I expect the same code to run on every machine or to break on every machine. 

## Possible Solution
Clueless. I don't even know what this error means, and Google wasn't helpful to me.

## Environment

<pre><code>
Nest version: 7.5.1
 
For Tooling issues:
- Node version: 14.15.1
- Platform:  macOS Catalina
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by caiusCitiriga** [comment]
Hi @kamilmysliwiec thank you for your response. Sorry for the delay. I was writing this when you closed the issue 😅  Unfortunately I'm unable to share a working repo, since the application is pretty big, and the code is unfortunately not open source 😭 

What I can do, if you could suggest me how (since I don't know), is to provide all the possible logs & dumps of that error. 
Yesterday evening I've investigated a bit further and I've noticed that a *new* NestJS project created on the incriminated iMac builds and runs flawlessly. Which leads me to think that there might be a code or library error (?). 

This is however oddly strange, since the same exact code runs on any other system (another mac, linux and even Docker). 
I've also tried to update node on my macbook pro to the same version of the iMac, but the result was that the old application runs flawlessly on the macbook pro with the same version of node as the iMac. I was hoping in a crash...

**Comment by kamilmysliwiec** [comment]
I'm on Node v14 and macOS Catalina too and I haven't encountered any issues so far (and I'm running tons of Nest apps locally 😄 )

**Comment by caiusCitiriga** [comment]
*Perhaps this is caused by a different, external package you use in the application(?)* 

That's what I'm thinking... I'm trying to reconstruct the application by creating a new one that runs and importing modules one by one, until it breaks again, hopefully I'll catch the guilty package...

If interested, I can keep you posted 😊

**Comment by caiusCitiriga** [comment]
WOW. I'm in a very WTF situation here. I found the culprit. And I still cannot believe this. 

Ok, first let's see the code, and then let's complain:

```ts
private logToFile(message: string, file = 'app.log.txt', skipDateString = false): void {
    if (!skipDateString) {
        message = `${this.getDateString()} ${message}\n`;
    } else {
        message += `\n`;
    }

    fs.writeFileSync(`./logs/${file}`, message, { encoding: 'utf8', flag: 'a+' });
}
```

This was exploding because that `./logs/` folder was missing! What the heck? Should it throw something like **dude! There's no folder called `logs` in here!" instead of dramatically explode like that? 🙀 🙀

**Comment by jmcdo29** [comment]
Normally, yeah, it should throw a simple error. You can check in a Node REPL to see that
```js
const { writeFileSync } = require('fs');
writeFileSync('./path/to/folder/that/does/not/exist/file.log', 'Hello World', { encoding: 'utf8', flag: 'a+' })
```
And you'll see a standard error from Node. There's probably something like `--abort-on-uncaught-exception` being used or set with V8 options that caused the V8 error dump

**Comment by caiusCitiriga** [comment]
@jmcdo29 thank you for your clarification. I wonder what could have changed that flag, since I didn't for sure. At the time of writing the system is still "virgin" and no particular tools other than Ionic & build tools for iOS and Android.

Well, again thank you for sharing that.

**Comment by TrejGun** [comment]
@jmcdo29 @caiusCitiriga I have this error too
I started to receive it after installation nest-winston as system logger

**Comment by space-schnoodle** [comment]
Thank you @TrejGun , for us it was a problem related to nest-winston.
