### ISSUE TITLE
platform-socket.io doesn't call ack on envents without data

### ISSUE THREAD

**Issue by mimopo** [nestjs/nest#5711]
## Current behavior

Ack method is never called when no data sent to the event.

## Input Code

Client side:

```ts
const socket = io.connect("http://localhost:3000");
socket.emit("hello", (response) => {
  console.log("Server says " + response);
});
```

Nest code (doesn't work), "hello" method is called but the ack not:

```ts
@WebSocketGateway()
export class MyGateway {
  @SubscribeMessage("hello")
  async hello(client: Socket): Promise<string> {
    return "hello";
  }
}
```

If we emit data from client side it works fine:

```ts
const socket = io.connect("http://localhost:3000");
socket.emit("hello", null, (response) => {
  console.log("Server says " + response);
});
```

## Expected behavior

The same event handling written in vainilla socket.io works:

```ts
const io = require("socket.io")(3000);
io.on("connection", (socket) => {
  socket.on("hello", (ack) => {
    ack("hello");
  });
});
```

## Possible Solution

It happens on the method "mapPayload" at the "IoAdapter" class:

```ts
// https://github.com/nestjs/nest/blob/master/packages/platform-socket.io/adapters/io-adapter.ts
export class IoAdapter extends AbstractWsAdapter {
  // ...
  public mapPayload(payload: any): { data: any; ack?: Function } {
    if (!Array.isArray(payload)) {
      // fix
      if (isFunction(payload)) {
        return { data: undefined, ack: payload };
      }
      // end fix
      return { data: payload };
    }
    const lastElement = payload[payload.length - 1];
    const isAck = isFunction(lastElement);
    if (isAck) {
      const size = payload.length - 1;
      return {
        data: size === 1 ? payload[0] : payload.slice(0, size),
        ack: lastElement,
      };
    }
    return { data: payload };
  }
}
```

## Environment

<pre><code>
Nest version: 7.5.3
    
 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Linux 

Others:
    "@nestjs/common": "^7.5.3",
    "@nestjs/core": "^7.5.3",
    "@nestjs/platform-express": "^7.5.3",
    "@nestjs/platform-socket.io": "^7.5.3",
    "@nestjs/typeorm": "^7.1.5",
    "@nestjs/websockets": "^7.5.3",
</code></pre>

**Comment by jmcdo29** [comment]
Sounds useful. Would you like to make a PR for this?

**Comment by mimopo** [comment]
Sure, I'm on it :)

**Comment by mimopo** [comment]
Hi! it's possibly my first pull request on Git Hub so I don't know how to link it to the issue.  

Maybe I should add a few tests related to the fix. 
So if you need them before merging it I will code them tomorrow.

Thanks in advance!

**Comment by kamilmysliwiec** [comment]
Lets' track this here https://github.com/nestjs/nest/pull/5712
