### ISSUE TITLE
RST_STREAM response if TE header is missing in the http/2 request

### ISSUE THREAD

**Issue by tickboxs** [nestjs/nest#5713]
## Current behavior
When send http/2 request without TE header,grpc send RST_STREAM response

## Possible Solution

problem: form calling notification(nestjs with grpc) return error (TST_STREAM)
fixes: 1. Add TE header to form gRPC call.  OR 2. replace grpc(nestjs) to grpc-js(example) in nodejs for notification
test result:
form (without fix 1) calling notification (without fix 2)  -> error
form (with fix 1) calling notification (without fix 2)  -> success
form (without fix 1) calling notification (with fix 2) -> success
form (with fix 1) calling notification (with fix 2) -> success

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
