### ISSUE TITLE
Validation Pipe Async errorFactory

### ISSUE THREAD

**Issue by BerniWittmann** [nestjs/nest#5718]
## Is your feature request related to a problem? Please describe.

I'm using `nestjs-i18n` for my internalization. Sadly i18n returns the translation results as observables and thus it is asynchrounous and requires to use `await this.i18n.t('key')`.
My goal is to write a custom Validation Pipe that translates the validation errors. This is perfectly possible with extending the Validaiton Pipe and overloading `createExceptionFactory`. However, in the `transform` function the exceptionFactory is only called synchronously. 

https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L116

```
if (errors.length > 0) {
    throw this.exceptionFactory(errors);
}
```

## Describe the solution you'd like

It would be good to `await` the result from `this.exceptionFactory(errors)`, since then asynchronous code can be used in the custom exception factory implementation.

```
if (errors.length > 0) {
    throw await this.exceptionFactory(errors);
}
```

## Teachability, Documentation, Adoption, Migration Strategy
I know that this problem could be solved by overloading the `transform` function, but since the `transform` function is quite long and complex, just keeping this part of the code maintained in my own project would be quite bad imo.

## What is the motivation / use case for changing the behavior?
See above

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/5719
