### ISSUE TITLE
Caching with Redis

### ISSUE THREAD

**Issue by madelfresno** [nestjs/nest#572]
## I'm submitting a...
[ ] Regression
[ ] Bug report
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
## Current behavior
Hi everyone!!

First of all, thanks to @kamilmysliwiec  for this awesome framework!!!

I want to use Redis as a caching system in a CRUD but I don't know how/where to include. In Express is quite easy but I don't know which is the best way with Nest modular architecture. 

Could anyone help me please?? 

Thanks for all

**Comment by roeehershko** [comment]
What you need to cache? if its database(probably) and your using an ORM like TypeORM/Mongoose, almost every ORM support redis cache, you can check there docs for more info

**Comment by madelfresno** [comment]
Hi @roeehershko,

I need it for a database, I'm not using TypeORM, only Mongoose but perhaps it would be better using TypeORM. 

Thanks!!

**Comment by roeehershko** [comment]
whichever you choose is depends on your needs, specific mongoose i found pretty quick 2 packages:
https://www.npmjs.com/package/mongoose-redis
https://www.npmjs.com/package/mongoose-redis-cache
thought both of them are pretty old, personally i use typeORM and it has its own redis cache support so not need external library
https://github.com/typeorm/typeorm/blob/master/docs/caching.md

**Comment by madelfresno** [comment]
I'll follow your advice. Thanks for all!!
