### ISSUE TITLE
req.session is undefined when using NestJS with Fastify adapter

### ISSUE THREAD

**Issue by piosystems** [nestjs/nest#5720]
## Current behavior
When using NestJS with fastify adapter, req.session is undefined. I have attempted to import and use _express-session_ . Alternatively, I have also imported and registered fastify-session and fastify-secure-session. In all cases, the following codes report session as undefined. Same if I inject @Req() and attempt to use req.session.set. 

## Input Code

```
@Get('test-session')
  testSession(@Session() session: any,@Res() reply: Reply){
    session.set('data', 'This was written to session'); 
    reply.send(session.get('data'));
  } 
```

## Expected behavior
data should be set in session and same data read from session and sent as reply, from the controller module

## Environment

Nest version: 7.0.0

 
For Tooling issues:
- Node version: 14.12.0
- Platform:  Mac

**Comment by jmcdo29** [comment]
`req.session` works fine, as does using `@Session()`. Just installed `@nestjs/platform-fastify` `fastify-cookie` (required by `fastify-session`) and `fastify-session`. Configured everything according to the `fastify-sesssion` readme, checked for `@Session()` and saw the data.

Please provide a minimum reproduction if you are still facing issues.
