### ISSUE TITLE
@Query with ParseBoolPipe is forcing query param to be required

### ISSUE THREAD

**Issue by Pacheco95** [nestjs/nest#5748]
## Current behavior

If I use `ParseBoolPipe` in conjunction with `@Query`, nest turn it required

## Input Code

```ts
// Case 1
@Get('user/:id/notifications')
async getUserNotifications(
  @Param('id') userId: string,
  @Query('read') read?: boolean,
) {/* ... */}

/*
GET /user/5fb5434de99196abe971b1b0/notifications?read=true (ok)
GET /user/5fb5434de99196abe971b1b0/notifications (ok)
*/

// Case 2
@Get('user/:id/notifications')
async getUserNotifications(
  @Param('id') userId: string,
  @Query('read', ParseBoolPipe) read?: boolean,
) {/* ... */}

/*
GET /user/5fb5434de99196abe971b1b0/notifications?read=true (ok)
GET /user/5fb5434de99196abe971b1b0/notifications throws:
{
    "statusCode": 400,
    "message": "Validation failed (boolean string is expected)",
    "timestamp": "2020-11-20T19:45:40.281Z",
    "path": "/user/5fb5434de99196abe971b1b0/notifications"
}
*/

// Case 3
@Get('user/:id/notifications')
async getUserNotifications(
  @Param('id') userId: string,
  @Query('read', new DefaultValuePipe(true), ParseBoolPipe) read?: boolean,
) {/* ... */}

/*
GET /user/5fb5434de99196abe971b1b0/notifications?read=true (ok)
GET /user/5fb5434de99196abe971b1b0/notifications (ok, but I don't want a default value because absence has a meaning to my use case)
*/
```

## Expected behavior

Use of `ParseBoolPipe` in conjunction with `@Query` should not mark query param as required, nor throw any exception complaining about value absence

## Possible Solution

- `@Query('read?', ParseBoolPipe)`
- `@Query('read', OptionalValuePipe, ParseBoolPipe)`
- `@Query('read', true | false, ParseBoolPipe)`
- `@Query({ name: 'read', required: false }, ParseBoolPipe)`
- `@Query('name', new ParseBoolPipe(false))`
- `@Query('name', new ParseBoolPipe({required: false}))`

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: v12.19.0  
- Platform: Linux 

Others:

</code></pre>

**Comment by Pacheco95** [comment]
Sory, it shouldn't be a a bug report but a feature request

**Comment by Pacheco95** [comment]
https://github.com/nestjs/nest/issues/5749

**Comment by fjamon** [comment]
You can instanciate the ParseBoolPipe class with options like following.

`// Case 1
@Get('user/:id/notifications')
async getUserNotifications(
  @Param('id') userId: string,
  @Query('read',new ParseBoolPipe({optional: true}) read?: boolean,
) {/* ... */}`
