### ISSUE TITLE
Add optional config to @Query decorator

### ISSUE THREAD

**Issue by Pacheco95** [nestjs/nest#5749]
## Feature Request
As explained in the [doc](https://docs.nestjs.com/pipes#providing-defaults), optional query params should make use of `DefaultValuePipe`, but there are some cases that absense of a query param have use case meaning.
Imagine that I want to get user's notifications:

```ts
@Get('user/:id/notifications')
getUserNotifications(
  @Param('id') userId: string,
  @Query('read', new DefaultValuePipe(true), ParseBoolPipe) read?: boolean,
) {}
```

If I need to get all notifications no matter the read status?

## Describe the solution you'd like

Simple solutions like these:
- `@Query('read?', ParseBoolPipe)`
- `@Query('read', OptionalValuePipe, ParseBoolPipe)`
- `@Query('read', true | false, ParseBoolPipe)`
- `@Query({ name: 'read', required: false }, ParseBoolPipe)`
- `@Query('name', new ParseBoolPipe(false))`
- `@Query('name', new ParseBoolPipe({required: false}))`

**Comment by kamilmysliwiec** [comment]
I'm not sure that I'm following. For validation & transformation of parameters (path/query/body), you should use pipes. We don't plan to add any additional properties to the existing decorators.

**Comment by xegulon** [comment]
@kamilmysliwiec could you then give some advice on a way to combine `@Query` and `Parse*Pipe` when we want the query parameter to be optional? For now, adding the pipe to the Query decorator makes the query parameter compulsory

What about this solution: `@Query('name', new ParseBoolPipe({required: false}))`?

**Comment by xegulon** [comment]
I followed your answer here: https://github.com/nestjs/nest/issues/4328#issuecomment-599948130 and it worked! Thanks!

**Comment by chriskuech** [comment]
@kamilmysliwiec please reopen this. I repeatedly face this issue with nestjs. Some pipes support `{ optional: true }` param and others don't. This is an extremely common use case for query strings as they are used for a filter param--absence of a value means to not use it in the filter.

**Comment by alko89** [comment]
I'm confused about the answers here. I'm also using the ParseBoolPipe for an optional query param and it used to work fine until updating to Nest 10.

The solution here seems to be to create a DTO for one query param?  :thinking:

This worked before v10:

```
@Query('immediate', ParseBoolPipe) immediate?: boolean,
```

**Comment by ebiggz** [comment]
Live @alko89 above, I also experienced this issue after upgrading to Nest 10. Since this is the first google result that comes up I thought I'd post the solution I found here after looking at ParseBoolPipe source. As of v10, [`ParseBoolPipe` supports the optional config param](https://github.com/nestjs/nest/commit/3dc80a4181173a89488036c73658308bc59f06cc), so you must explicitly set `{ optional: true }` for it to work.

This works for me:
```ts
@Query('withDeleted', new ParseBoolPipe({ optional: true }))
withDeleted?: boolean,
```

**Comment by johnrake-betablox** [comment]
> Live @alko89 above, I also experienced this issue after upgrading to Nest 10. Since this is the first google result that comes up I thought I'd post the solution I found here after looking at ParseBoolPipe source. As of v10, [`ParseBoolPipe` supports the optional config param](https://github.com/nestjs/nest/commit/3dc80a4181173a89488036c73658308bc59f06cc), so you must explicitly set `{ optional: true }` for it to work.
> 
> This works for me:
> 
> ```ts
> @Query('withDeleted', new ParseBoolPipe({ optional: true }))
> withDeleted?: boolean,
> ```

For anyone coming to this thread looking for a solution. This is it. Here's my example where I needed to support an optional `userId` filter param, but still wanted to transform with `ParseIntPipe`

```ts
  @Get()
  async findAll(
    @Query('taskId', new DefaultValuePipe('')) taskId: string,
    @Query('userId', new ParseIntPipe({ optional: true })) userId: number,
  ) {
    return this.service.findAll({ taskId, userId });
  }
```

I can probably clean up the `taskId` from using the default value pipe, but I'm already 2+ hours into this issue and frankly I have better stuff to do.

**Comment by alko89** [comment]
@johnrake-betablox this works yes, another option if you're using a DTOs for query params is to enable implicit conversion in validation pipe:

```typescript
new ValidationPipe({ transformOptions: { enableImplicitConversion: true } }
```

IMO both of these should be added to nest docs.

**Comment by ananuness** [comment]
A example of what you all can do if the `{ optional: true }` is not available for the pipe you need:

First override the pipe you need:

```js
// ParseOptionalEnumPipe.pipe.ts

import { ArgumentMetadata, ParseEnumPipe } from '@nestjs/common';

export class ParseOptionalEnumPipe<T = any> extends ParseEnumPipe<T> {
  override transform(value: T, metadata: ArgumentMetadata): Promise<T> {
    if (typeof value === 'undefined') return undefined;

    return super.transform(value, metadata);
  }
}
```

Then, use it in your controller:

```js
@Get()
findAll(
  @Query('type', new ParseOptionalEnumPipe(BookType)) type?: BookType,
) {
    // some code here
}
```

> :warning: If **strictNullChecks: true** in `tsconfig.json`, it will not work properly.

**Comment by gollex** [comment]
not sure why, but this does not work for me:
```typescript
   new ParseIntPipe({ optional: true })) userId: number
```
still the pipe throws...
