### ISSUE TITLE
Socket IO dynamic namespace

### ISSUE THREAD

**Issue by xxxle0** [nestjs/nest#5750]
## Feature Request
WebSocket dynamic namespace document
## Is your feature request related to a problem? Please describe.

I'm using nestJs and socket io. I have followed gateways document on nestjs and use regex on namespace WebSocketGateway to support dynamic namespace. Do we have any instructions for setup regex on namespace.

**Comment by kamilmysliwiec** [comment]
For this, you can use socket.io directly. Gateways allow you to spin up servers & bind message handlers statically in a declarative way. If you need more flexibility (dynamically bind handlers, dynamically determine the socket.io namespace), you can use the library directly without gateways.

**Comment by xxxle0** [comment]
Do you have an instruction? @kamilmysliwiec

**Comment by ChrisKatsaras** [comment]
@xxxle0  did you end up finding the solution to your problem?

**Comment by ChrisKatsaras** [comment]
@esp-dqtran That's great! Would you mind sharing what you did? Did you end up just using native socket.io? I'm considering switching after @kamilmysliwiec suggestion!

**Comment by kamilmysliwiec** [comment]
You can use a native socket.io with Nest without using gateways by simply booting up the server & registering message handlers within an arbitrary provider, whether it's a class or a factory.
