### ISSUE TITLE
Support websocket and socket.io at the same time.

### ISSUE THREAD

**Issue by dzcpy** [nestjs/nest#5751]
## Feature Request
Is it possible to support both `websocket` and `socket.io`, and appoint it from websockets gateways? Like I have a need to connect to the sever from a rust program using websocket, and socket.io from web. I kind of need both, but currently there's no way to achieve that.

## Is your feature request related to a problem? Please describe.

The problem is that websocket adapter is app-wise, not gateway-wise.

## Describe the solution you'd like

I would hope being able  to set different adapters in different gateways. For example: `WebSocketGateway(WsAdapter, 8080)` something like that

**Comment by kamilmysliwiec** [comment]
> I kind of need both, but currently there's no way to achieve that.

If you have to use both at the same time, you can always interact with the library directly. Nest provides Gateways to allow defining message handlers declaratively. However, if you need more flexibility (dynamic subscriptions, multiple servers, different libraries), you can always just use the library directly (for example, define custom providers which represent your Socket.io and WS servers and register handlers from providers).

**Comment by ext0** [comment]
Quick update to this if anybody is looking for an answer to this. It's by no means the cleanest implementation, and could benefit from far more abstraction, but this is what I tossed as a quick solution.

`import * as WebSocket from 'ws';
import * as SocketIO from "socket.io";
import { WebSocketAdapter, INestApplicationContext } from '@nestjs/common';
import { MessageMappingProperties } from '@nestjs/websockets';
import { Observable, fromEvent, EMPTY, fromEventPattern } from 'rxjs';
import { mergeMap, filter } from 'rxjs/operators';
import { NestExpressApplication } from '@nestjs/platform-express';

export enum SocketServerType {
  SOCKET_IO = 'socket.io',
  WEBSOCKET = 'ws'
};

export interface SocketServerOptions {
  type: SocketServerType;
  path?: string;
  cors?: {
    origin?: string;
  }
}

export class HybridSocketAdapter implements WebSocketAdapter {
  private type: SocketServerType;

  constructor(private app: NestExpressApplication) {}

  create(port: number, options: SocketServerOptions = { type: SocketServerType.WEBSOCKET }): any {
    this.type = options.type;

    switch (this.type) {
      case SocketServerType.WEBSOCKET:
        return new WebSocket.Server({ port, ...options });
      case SocketServerType.SOCKET_IO:
        const socketIOServer = new SocketIO.Server(this.app.getHttpServer(), options);
        socketIOServer.listen(port);
        return socketIOServer;
    }
  }

  bindClientConnect(server: WebSocket.Server | SocketIO.Server, callback: Function) {
    switch (this.type) {
      case SocketServerType.WEBSOCKET:
        (server as WebSocket.Server).on('connection', callback as any);
        return;
      case SocketServerType.SOCKET_IO:
        (server as SocketIO.Server).on('connection', callback as any);
        return;
    }
  }

  bindMessageHandlers(
    client: WebSocket | SocketIO.Socket,
    handlers: MessageMappingProperties[],
    process: (data: any) => Observable<any>,
  ) {
    switch (this.type) {
      case SocketServerType.WEBSOCKET:
        const websocketClient = client as WebSocket;
        fromEvent(websocketClient, 'message')
          .pipe(
            mergeMap(data => this.bindMessageHandler(data, handlers, process)),
            filter(result => result),
          )
          .subscribe(response => websocketClient.send(JSON.stringify(response)));
        break;
      case SocketServerType.SOCKET_IO:
        const socketIOClient = client as SocketIO.Socket;
        const onAny$ = fromEventPattern(
          (handler) => socketIOClient.onAny(handler),
          (handler) => socketIOClient.offAny(handler)
        );

        onAny$
          .pipe(
            mergeMap(data => this.bindMessageHandler(data, handlers, process)),
            filter(result => result),
          )
          .subscribe(({ response, event }: { response: any, event: string }) => {
            socketIOClient.emit(event, response)
          });
        break;
    }

  }

  bindMessageHandler(
    buffer: any,
    handlers: MessageMappingProperties[],
    process: (data: any) => Observable<any>,
  ): Observable<any> {
    switch (this.type) {
      case SocketServerType.WEBSOCKET:
        // For now, WebSockets will not support the message handler
        return EMPTY;
      case SocketServerType.SOCKET_IO:
        const [event, data] = buffer;

        const body = typeof data === 'object' && data['body'] ? data.body : data;

        const messageHandler = handlers.find(
          handler => handler.message === event,
        );

        if (!messageHandler) {
          return EMPTY;
        }

        const executionPromise = async () => {
          const response = await messageHandler.callback(body);
          return {
            response: response,
            event: event
          };
        };

        return process(executionPromise());
    }
  }

  close(server: WebSocket.Server | SocketIO.Server): void {
    server.close();
  }
}`

**Comment by iGoodie** [comment]
> Quick update to this if anybody is looking for an answer to this. It's by no means the cleanest implementation, and could benefit from far more abstraction, but this is what I tossed as a quick solution.

Hey thanks a lot for the amazing time-saver! 🎉 

It actually inspired me a lot, I abstracted the whole thing one step further and turned it into an actual Adapter Proxy!
I might introduce further abstractions and turn this thing into its own library. But for now, I also want to share my quick and ugly solution 😁 

```ts
import { INestApplication, WebSocketAdapter } from '@nestjs/common';
import { IoAdapter } from '@nestjs/platform-socket.io';
import { WsAdapter } from '@nestjs/platform-ws';
import {
  AbstractWsAdapter,
  GatewayMetadata,
  WebSocketGateway,
} from '@nestjs/websockets';
import * as SocketIO from 'socket.io';
import * as WebSocket from 'ws';

export enum SocketServerType {
  SOCKET_IO = 'socket.io',
  WEBSOCKET = 'ws',
}

export interface SocketServerOptions {
  type: SocketServerType;
  path?: string;
  cors?: {
    origin?: string;
  };
}

export class HybridSocketAdapter implements WebSocketAdapter {
  private readonly registry: Record<
    SocketServerType,
    {
      adapter: WebSocketAdapter;
      checkClient: (client: any) => boolean;
      checkServer: (server: any) => boolean;
    }
  >;

  constructor(app: INestApplication<any>) {
    this.registry = {
      [SocketServerType.SOCKET_IO]: {
        adapter: new IoAdapter(app),
        checkClient: (client) => client instanceof SocketIO.Socket,
        checkServer: (server) => server instanceof SocketIO.Namespace,
      },
      [SocketServerType.WEBSOCKET]: {
        adapter: new WsAdapter(app),
        checkClient: (client) => client instanceof WebSocket.WebSocket,
        checkServer: (server) => server instanceof WebSocket.Server,
      },
    };
  }

  private getMatchingAdapter(targetType: 'client' | 'server', target: any) {
    const [type, entry] =
      Object.entries(this.registry).find(([, entry]) =>
        targetType === 'server'
          ? entry.checkServer(target)
          : entry.checkClient(target),
      ) ?? [];

    if (type == null) {
      throw new Error('Could not find a matching ' + targetType);
    }

    return {
      type: type as SocketServerType,
      ...entry,
    };
  }

  private proxyHandle<
    K extends keyof WebSocketAdapter,
    $args extends any[] = AbstractWsAdapter[K] extends (...args: infer A) => any
      ? A
      : never,
  >(method: K, typeExtractor: (...args: NoInfer<$args>) => SocketServerType) {
    return (...args: $args) => {
      const type = typeExtractor(...args);
      const { adapter } = this.registry[type] ?? {};

      if (adapter == null) {
        throw new Error('Unknown server type -> ' + type);
      }

      const methodImpl = adapter[method] as Function;
      return Reflect.apply(methodImpl, adapter, args);
    };
  }

  create = this.proxyHandle(
    'create',
    (port, opts: SocketServerOptions) => opts.type,
  );

  bindClientConnect = this.proxyHandle(
    'bindClientConnect',
    (server, cb) => this.getMatchingAdapter('server', server).type,
  );

  bindClientDisconnect = this.proxyHandle(
    'bindClientDisconnect',
    (client, cb) => this.getMatchingAdapter('client', client).type,
  );

  bindMessageHandlers = this.proxyHandle(
    'bindMessageHandlers',
    (client, handlers, transform) =>
      this.getMatchingAdapter('client', client).type,
  );

  close = this.proxyHandle(
    'close',
    (server) => this.getMatchingAdapter('server', server).type,
  );
}

export const HybridSocketGateway = WebSocketGateway<
  GatewayMetadata & SocketServerOptions
>;
```

**Comment by Philipinho** [comment]
I achieved something similar with the code below.

Nest `platform-socket.io` is used, and then a custom adapter and module for WS.

Code extracted from my project to help you get started.

```ts
// source: https://github.com/docmost/docmost/blob/main/apps/server/src/collaboration/adapter/collab-ws.adapter.ts
import { WebSocketServer } from 'ws';

export class WsAdapter {
  private readonly wss: WebSocketServer;

  constructor() {
    this.wss = new WebSocketServer({ noServer: true });
  }

  handleUpgrade(path: string, httpServer: any) {
    httpServer.on('upgrade', (request: any, socket: any, head: any) => {
      try {
        const baseUrl = 'ws://' + request.headers.host + '/';
        const pathname = new URL(request.url, baseUrl).pathname;

        if (pathname === path) {
          this.wss.handleUpgrade(request, socket, head, (ws) => {
            this.wss.emit('connection', ws, request);
          });
        } else if (pathname === '/socket.io/') {
          return;
        } else {
          socket.destroy();
        }
      } catch (err) {
        socket.end('HTTP/1.1 400\r\n' + (err as Error).message);
      }
    });

    return this.wss;
  }

  public destroy() {
    try {
      this.wss.clients.forEach((client) => {
        client.terminate();
      });
      this.wss.close();
    } catch (err) {
      console.error(err);
    }
  }
}
```

```ts
// source: https://github.com/docmost/docmost/blob/69447fc3757230d3d177111297dffa9484a3cce6/apps/server/src/collaboration/collaboration.module.ts
import { Logger, Module, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { HttpAdapterHost } from '@nestjs/core';
import { WsAdapter } from './adapter/collab-ws.adapter';
import { IncomingMessage } from 'http';
import { WebSocket } from 'ws';

@Module({})
export class CollaborationModule implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(CollaborationModule.name);
  private wsAdapter: CollabWsAdapter;
  private path = '/collab';

  constructor(
    private readonly collaborationGateway: CollaborationGateway,
    private readonly httpAdapterHost: HttpAdapterHost,
  ) {}

  onModuleInit() {
    this.collabWsAdapter = new CollabWsAdapter();
    const httpServer = this.httpAdapterHost.httpAdapter.getHttpServer();

    const wss = this.wsAdapter.handleUpgrade(this.path, httpServer);

    wss.on('connection', (client: WebSocket, request: IncomingMessage) => {
      this.collaborationGateway.handleConnection(client, request);

      client.on('error', (error) => {
        this.logger.error('WebSocket client error:', error);
      });
    });

    wss.on('error', (error) =>
      this.logger.log('WebSocket server error:', error),
    );
  }

  async onModuleDestroy(): Promise<void> {
    if (this.wsAdapter) {
      this.wsAdapter.destroy();
    }
  }
}
```

**Comment by iGoodie** [comment]
> > Quick update to this if anybody is looking for an answer to this. It's by no means the cleanest implementation, and could benefit from far more abstraction, but this is what I tossed as a quick solution.
> 
> Hey [@ext0](https://github.com/ext0), thanks a lot for the amazing time-saver! 🎉
> 
> It actually inspired me a lot, I abstracted the whole thing one step further and turned it into an actual Adapter Proxy! I might introduce further abstractions and turn this thing into its own library. But for now, I also want to share my quick and ugly solution 😁
> 
> import { INestApplication, WebSocketAdapter } from '@nestjs/common';
> import { IoAdapter } from '@nestjs/platform-socket.io';
> import { WsAdapter } from '@nestjs/platform-ws';
> import { GatewayMetadata, WebSocketGateway } from '@nestjs/websockets';
> import * as SocketIO from 'socket.io';
> import * as WebSocket from 'ws';
> 
> export enum SocketServerType {
>   SOCKET_IO = 'socket.io',
>   WEBSOCKET = 'ws',
> }
> 
> export interface SocketServerOptions {
>   type: SocketServerType;
> }
> 
> export class HybridSocketAdapter implements WebSocketAdapter {
>   private readonly registry: Record<
>     SocketServerType,
>     {
>       adapter: WebSocketAdapter;
>       checkClient: (client: any) => boolean;
>       checkServer: (server: any) => boolean;
>     }
>   >;
> 
>   constructor(app: INestApplication<any>) {
>     this.registry = {
>       [SocketServerType.SOCKET_IO]: {
>         adapter: new IoAdapter(app),
>         checkClient: (client) => client instanceof SocketIO.Socket,
>         checkServer: (server) => server instanceof SocketIO.Namespace,
>       },
>       [SocketServerType.WEBSOCKET]: {
>         adapter: new WsAdapter(app),
>         checkClient: (client) => client instanceof WebSocket.WebSocket,
>         checkServer: (server) => server instanceof WebSocket.Server,
>       },
>     };
>   }
> 
>   private getMatchingAdapter(targetType: 'client' | 'server', target: any) {
>     const [type, entry] =
>       Object.entries(this.registry).find(([, entry]) =>
>         targetType === 'server'
>           ? entry.checkServer(target)
>           : entry.checkClient(target),
>       ) ?? [];
> 
>     if (type == null) {
>       throw new Error('Could not find a matching ' + targetType);
>     }
> 
>     return {
>       type: type as SocketServerType,
>       ...entry,
>     };
>   }
> 
>   private proxyHandle<
>     K extends keyof WebSocketAdapter,
>     $args extends any[] = WebSocketAdapter[K] extends (...args: infer A) => any
>       ? A
>       : never,
>   >(method: K, typeExtractor: (...args: NoInfer<$args>) => SocketServerType) {
>     return (...args: $args) => {
>       const type = typeExtractor(...args);
>       const { adapter } = this.registry[type] ?? {};
> 
>       if (adapter == null) {
>         throw new Error('Unknown server type -> ' + type);
>       }
> 
>       const methodImpl = adapter[method] as Function;
>       return Reflect.apply(methodImpl, adapter, args);
>     };
>   }
> 
>   create = this.proxyHandle(
>     'create',
>     (port, opts: SocketServerOptions) => opts.type,
>   );
> 
>   bindClientConnect = this.proxyHandle(
>     'bindClientConnect',
>     (server, cb) => this.getMatchingAdapter('server', server).type,
>   );
> 
>   bindClientDisconnect = this.proxyHandle(
>     'bindClientDisconnect',
>     (client, cb) => this.getMatchingAdapter('client', client).type,
>   );
> 
>   bindMessageHandlers = this.proxyHandle(
>     'bindMessageHandlers',
>     (client, handlers, transform) =>
>       this.getMatchingAdapter('client', client).type,
>   );
> 
>   close = this.proxyHandle(
>     'close',
>     (server) => this.getMatchingAdapter('server', server).type,
>   );
> }
> 
> export const HybridSocketGateway = WebSocketGateway<
>   GatewayMetadata & SocketServerOptions
> >;
> Usage:
> 
> @HybridSocketGateway(3001, {
>   type: SocketServerType.SOCKET_IO,
>   namespace: 'my-socket',
>   transports: ['websocket', 'polling'],
>   cors: { origin: '*' },
> })
> export class MySocketGateway { /* omitted */ }

I have extracted it into its own library 😁 
Leaving it for the ones who might want to use it.

Hybrid Websocket Adapter:
https://github.com/iGoodie/nestjs-hybrid-websocket-adapter
