### ISSUE TITLE
@Sse() not compatible with compression() middleware

### ISSUE THREAD

**Issue by bchoii** [nestjs/nest#5762]
## Current behavior
Current SSE not compatible with compression() middleware (https://github.com/expressjs/compression).

If compression middleware is present, SSE events do not seem to reach the browser.

## Expected behavior
Expecting SSE to work with compression() middleware

## Possible Solutions
Option 1:
Filter sse from compression()
```ts
  app.use(
    compression({
      filter: (req, res) =>
        !res.getHeaders()['content-type']?.includes('text/event-stream'),
    }),
  );
```

Option 2:
Add "no-transform" to "Cache-Control" headers for SSE responses. Compression middleware will detect this header and skip compression on this particular response. See https://github.com/expressjs/compression/issues/51
```ts
 response.set({
    'Cache-Control': 'no-transform',
  });
```

**Comment by kamilmysliwiec** [comment]
This will be fixed in the next patch/minor release https://github.com/nestjs/nest/commit/41d46c0c07551bc01988f0545cefc75c5d9daa8a
