### ISSUE TITLE
There is no user object into request when connecting guard through useGlobalGuards

### ISSUE THREAD

**Issue by KirillCherkalov** [nestjs/nest#5776]
## Current behavior

There is no `user` object into `request` when connecting guard through `useGlobalGuards`.
But it works well if I connect the guard to the controller through `UseGuards` decorator.
I use `@nestjs/jwt` for auth.

## Input Code

`main.ts` file
```ts
  ...
  app.useGlobalGuards(new RolesGuard(new Reflector()));
```

`roles.guard.ts` file 
```ts
import { Injectable, CanActivate, ExecutionContext } from '@nestjs/common';
import { Reflector } from '@nestjs/core';

@Injectable()
export class RolesGuard implements CanActivate {
  constructor(private reflector: Reflector) {}

  canActivate(context: ExecutionContext): boolean {
    const roles = this.reflector.get<string[]>('roles', context.getHandler());

    if (!roles) {
      return true;
    }

    const request = context.switchToHttp().getRequest();
    const user = request.user; // undefined in case with useGlobalGuards

    return true;
  }
}

```

## Expected behavior

`user` object should be available for both cases

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 12.16.3
- Platform:  any

**Comment by jmcdo29** [comment]
`user` is not a default property on HTTP Request objects. In most cases, it is added by the `passport` package from when the `AuthGuard()` is used. If you have a guard running before the `AuthGuard()` ([check order of operations here](https://docs.nestjs.com/faq/request-lifecycle)) then it will not have access to the `user` property.

Please use our [Discord](https://discord.gg/nestjs) channel (Support) for support as we are using GitHub to track Bug Reports, Feature Requests, and Regressions.
