### ISSUE TITLE
Circular dependency doesn't work if Service has a Request Scoped Provider

### ISSUE THREAD

**Issue by djfabrix** [nestjs/nest#5778]
## Current behavior
When there is a circular dependency between 2 modules and a service has a Request Scoped Provider injected, methods are called before constructor and so all injected providers are undefined.

## Input Code
https://github.com/djfabrix/nest-circular-request-scoped-provider

## Expected behavior
Injected providers in service are not undefined.

## Environment

<pre><code>
Nest version: 7.0.0

 
For Tooling issues:
- Node version: v14.15.1  
- Platform:  Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/fundamentals/circular-dependency#forward-reference

![image](https://user-images.githubusercontent.com/23244943/100199566-a7b20f00-2efd-11eb-8ed6-dec18df1e750.png)

In request-scoped providers, classes **depend on which constructor is called first by nature**. In your example, `CompanyService` is simply called first.

![image](https://user-images.githubusercontent.com/23244943/100200736-5145d000-2eff-11eb-92bc-89539ed3b6c2.png)

You can fix this issue using the the `process.nextTick()` function:

```typescript
async getUsers() {
    await new Promise(resolve => process.nextTick(resolve)); // <- add this
    console.log('getUsers function');
    ...
}
```

Still, using request-scoped providers in combination with circular dependencies is very unpredictable and I'd definitely recommend refactoring your code to get rid of them.

**Comment by djfabrix** [comment]
Thank you so much Kamil!

**Comment by s4kh** [comment]
> https://docs.nestjs.com/fundamentals/circular-dependency#forward-reference
> 
> ![image](https://user-images.githubusercontent.com/23244943/100199566-a7b20f00-2efd-11eb-8ed6-dec18df1e750.png)
> 
> In request-scoped providers, classes **depend on which constructor is called first by nature**. In your example, `CompanyService` is simply called first.
> 
> ![image](https://user-images.githubusercontent.com/23244943/100200736-5145d000-2eff-11eb-92bc-89539ed3b6c2.png)
> 
> You can fix this issue using the the `process.nextTick()` function:
> 
> ```ts
> async getUsers() {
>     await new Promise(resolve => process.nextTick(resolve)); // <- add this
>     console.log('getUsers function');
>     ...
> }
> ```
> 
> Still, using request-scoped providers in combination with circular dependencies is very unpredictable and I'd strongly recommend refactoring your code to get rid of them.

Thanks for the workaround @kamilmysliwiec. Can you please provide an example of how to refactor module circular dependency?
AppLogModule imports AppDeployment -> AppLogService has multiple methods that use appdeploymentService
Now AppDeploymentService wants to use appLogservice through importing the AppLogsModule. Only 1 method uses applogService in appDeploymentservice.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
