### ISSUE TITLE
Order of execution class-validator class transformer

### ISSUE THREAD

**Issue by vh13294** [nestjs/nest#5787]
## Current behavior
I was reading docs about Validation and pipe. Are they meant to be used together?
I want to validator query params and reject if it doesn't meet requirement. 
However the @ Transform tag run first, in this case parseInt which could lead to unpredictable result.

Is there a better way to convert DTO to integer( after validation not before?) 

## Input Code

```ts
import { IsInt, IsPositive } from 'class-validator';
import { Transform } from "class-transformer";

export class Search {
    @IsInt()
    @IsPositive()
    @Transform(value => parseInt(value))
    locationId: number;

    @Transform(value => parseInt(value))
    @IsInt()
    @IsPositive()
    productId: number;
    
    @Transform(value => parseInt(value))
    @IsInt()
    pageNumber?: number = 0;
}

```

## Environment

<pre><code>
Nest version: 7.5.5

**Comment by like0413** [comment]
i have same question,how did you solve it?
