### ISSUE TITLE
Heartbeat for RMQ socket options not working as expected

### ISSUE THREAD

**Issue by christianallred** [nestjs/nest#5788]
## Current behavior
When configuring a Rmq Microservice. using the documentation on the website: https://docs.nestjs.com/microservices/rabbitmq

It suggests that the socket options being used are those in the amqlib library, however. Upon inspecting the NestJS microservice factory it appears to be using the amqp-connection-manager library. Which has a different socketOptions footprint.
`https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-rmq.ts#L54`

the socket options footprint is described here: https://www.npmjs.com/package/amqp-connection-manager#user-content-amqpconnectionmanagercreatechanneloptions

The documentation that is listed on nestJS says you should us `heartbeat:60` per the documents in amqlib however teh amqp-connection-manager says to use `heartbeatIntervalInSeconds: 60`

Also, it would appear that neither heartbeat or heartbeatIntervalInSeconds actually has an effect on the heartbeat setting from what i can see. 

The only way i was able to get the heartbeat to work as expected was to pass in the url as a object config instead as suggested by this PR: https://github.com/nestjs/nest/issues/5587

## Input Code
```ts
app.connectMicroservice(<RmqOptions>{
    transport: Transport.RMQ,
    options: {
      urls: ['connectionstring'],
      queue: queue,
      socketOptions: {
        heartbeatIntervalInSeconds: 60,
      },
    },
  })
```

## Expected behavior
1) Need to validate what library is being used for socket options so we can update the documentation properly
2) need to ensure that either `amqplib`, or `amqp-connection-manager` options are being respected properly when using `connectMicroservice`

## Possible Solution
Update the documenation. 

I am going to see if i can get the heartbeat config to work properly using what i see in the live code today: `amqp-connection-manager`

## Environment

<pre><code>
Nest version: ~7.0.13

 
For Tooling issues:
- Node version: v12.5.0
- Platform:  Mac

Others:

</code></pre>

**Comment by christianallred** [comment]
Upon further inspection of the amqp-connection-manaager code, it looks like there is an odd issue with connection URL objects vs strings. 

I think the issue might be in the amqp-connection-manaager repo.

**Comment by christianallred** [comment]
It looks like the code calling amqp-connection-manager is passing over the options incorrectly: 
https://github.com/jwalton/node-amqp-connection-manager

**Comment by christianallred** [comment]
https://github.com/nestjs/nest/pull/5790

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Lets track this here https://github.com/nestjs/nest/pull/5790

**Comment by arturgrigor** [comment]
In the latest versions of the `@nestjs/microservices` package, certain client options are not being properly passed to the `AmqplibConnectionManager`. Specifically, the options `heartbeatIntervalInSeconds` and `reconnectTimeInSeconds` are omitted when configuring the connection. Currently, only the `connectionOptions` property is being forwarded.

**Issue in code**: The problem can be traced to this section of the `client-rmq.ts` file in the Nest.js repository: [client-rmq.ts#L139](https://github.com/nestjs/nest/blob/47cda929227046f8aa5647436d60d4621155f979/packages/microservices/client/client-rmq.ts#L139)
**Relevant connection manager code**: The related code in `AmqpConnectionManager` can be found here: [AmqpConnectionManager.ts#L200](https://github.com/jwalton/node-amqp-connection-manager/blob/v4.1.14/src/AmqpConnectionManager.ts#L200)

cc @kamilmysliwiec

**Comment by v-sum** [comment]
@arturgrigor I've added a possible fix that would include the discarded options https://github.com/nestjs/nest/pull/14059/files
