### ISSUE TITLE
Handle ValidationPipe errors

### ISSUE THREAD

**Issue by itamardavidyan** [nestjs/nest#5800]
I use `class-validator` with `nestjs` and I created dto class with validations and I want that if validation failed to get the error in the client (I mean to throw HttpBadException) 
How can I do it?

** I tried to use Exception filters but it doesn't catch the validation errors

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
