### ISSUE TITLE
nest start --watch doesn't reload after changes

### ISSUE THREAD

**Issue by dechans** [nestjs/nest#5808]
## Bug Report
Hi everyone, i'm facing a problem with nest start --watch
## Current behavior
As always, launching my NestJS project in DEV MODE (npm run start:dev), but since few days, changes is detected, but server not reloaded with changes.

Just this messages after changes : 
```
[10:33:44] File change detected. Starting incremental compilation...

[10:33:44] Found 0 errors. Watching for file changes.
```
So when i'm calling API, the changes are not effective.

## Expected behavior
I expect a working watch function

## Environment

Nest version: last

For Tooling issues:
- Node version: 14.15.1
- Platform:  Windows

Others:
i've tried to reinstall npm, node, nestjs/cli..
On new project, with npm or yarn, same problem : the changes are not effective

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
