### ISSUE TITLE
Support custom logger better for startup logs

### ISSUE THREAD

**Issue by yissachar** [nestjs/nest#5811]
## Is your feature request related to a problem? Please describe.
According to the [docs](https://docs.nestjs.com/techniques/logger#injecting-a-custom-logger) when we use a custom logger we have two options when it comes to startup logs:

1. Use the Nest default logger for the first few startup logs until the custom logger is setup
2. Don't output the first few startup logs

These are both not ideal solutions. Using the default logger means that the first few logs are in a different format than we expect which can have undesirable consequences in a production environment where log shipping/parsing agents are setup. And hiding the first few startup logs means we may lose critical error information such as dependency injection frameworks.

## Describe the solution you'd like
It should be possible to inject a custom logger and have it apply to all logs, including the early startup ones.

## Teachability, Documentation, Adoption, Migration Strategy
The same approach as today could be used, with only the underlying implementation changing. `logger: false` parameter could be removed from `create` or alternatively could be replaced with an argument that specifies the logger to use if that makes implementation easier, e.g.:

```
const app = await NestFactory.create(ApplicationModule, {
  logger: new MyLogger(),
});
```

## What is the motivation / use case for changing the behavior?
Better production logging experience.

**Comment by kamilmysliwiec** [comment]
This has been discussed several times in the past. Please, search for old issues for more information on this topic.

**Comment by yissachar** [comment]
@kamilmysliwiec Can you please link to the issues? I did search and was not able to find anything that provided a solution, only issues like #3439 which just re-iterate the current problematic behaviour. Thanks!

**Comment by jmcdo29** [comment]
#1828
#2497
#1043
#507
And the one with most context and conversation #247
