### ISSUE TITLE
logger attribute in createApplicationContext is not working

### ISSUE THREAD

**Issue by vinayak25** [nestjs/nest#5816]
## Current behavior
In `createApplicationContext` method, toggling logger attribute disables the logger even if `true` is passed.

```ts
  const app = await NestFactory.createApplicationContext(BaseConsoleModule, {
    logger: true,
  });
```
is having same effect as
```ts
  const app = await NestFactory.createApplicationContext(BaseConsoleModule, {
    logger: false,
  });
```
Logger is not working in both the cases. To make it work I had to remove the `logger` attribute completely.

## Expected behavior
Passing `logger: true` should work and logging should be done while building application context.

## Possible Solution
inside nest-factory.ts the `applyLogger` method is wrongly checking for the options or `logger` attribute's existence.

```ts
  private applyLogger(options: NestApplicationContextOptions | undefined) {
    if (!options) {
      return;
    }
    !isNil(options.logger) && Logger.overrideLogger(options.logger);
  }
```

## Environment
Nest version: ^7.0.0

For Tooling issues:
- Node version: v12.8.3
- Platform:  macOS Big Sur v11.0.1

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/5817
