### ISSUE TITLE
@Sse does not detect parallel [updates/changes/events]

### ISSUE THREAD

**Issue by ningacoding** [nestjs/nest#5822]
## Bug Report
@Sse lose subscriptions on almost all observables.

## Current behavior
is not possible to emit events or changes from another [service/controller/client] observables.

## Input Code
Controller
```ts
@Controller('events')
export class EventsController {

  constructor(private readonly eventsService: EventsService) {
  }

  @Sse('eventSubscription')
  chatRoomEvents() {
    return this.eventsService.subscribe();
  }

  @Post('someParallelEvent')
  async someParallelEvent() {
    // this fires events ok but @Sse just not catching
    this.eventsService.emit("hello from someParallelEvent");
    return {};
  }
```

### EventsService Case 1
```ts
import { fromEvent } from 'rxjs';
import { EventEmitter } from 'events';

@Injectable()
export class EventsService {

  private readonly emitter: EventEmitter;

  constructor(
  ) {
    this.emitter = new EventEmitter();
  }

  subscribe() {
    const events = fromEvent(this.emitter, 'eventName');
    events.subscribe({
      next: value => console.log('next', value), // this prints values OK but @Sse does not emit changes
      error: value => console.log('error', value),
      complete: () => console.log('complete'),
    });
    return events;
  }

  async emit(data) {
    this.emitter.emit('eventName', data);
  }
```

### EventsService Case 2
```ts
import { Observable } from 'rxjs';

@Injectable()
export class EventsService {

  // does not care if subscriber is stored on a Map list, to store all client instances...
  // so in this example i won't store subscribers on a list, just a single instance
  private subscriber;

  subscribe() {
    return new Observable(subscriber => {
      subscriber.next("{}"); // this makes @Sse works OK !! emits data well
      this.subscriber = subscriber; // copy subs instance to make it available for emit method
    });
  }

  async emit(data) {
    // when subscriber is setted emits data OK but @Sse not catching [changes/events]
    this.subscriber?.next(data); // the same subscriber instance @Sse does nothing :(
  }
```

## Expected behavior
@Sse should be able to capture Observables changes outside method scope since almost all events occurs outside.

## Environment

<pre><code>
Nest version: ~7.5.5
 
For Tooling issues:
- Node version: v12.18.3
- Platform:  Windows 10 19042.630

Others:
"rxjs": "~6.6.3",

**Comment by jmcdo29** [comment]
Can you please provide a minimum reproduction repository?

**Comment by ningacoding** [comment]
I'm building minimum reproducible repo here:

https://github.com/ningacoding/nest-sse-bug

this example works, let me add some real world flow to reproduce bug.

in my real case i reported, i have @Guards on the controller, i'll update the repo asap. i'll let you know.

**Comment by ningacoding** [comment]
@jmcdo29 I've updated the repo with a min reproducible bug

please see:
https://github.com/ningacoding/nest-sse-bug

**Comment by jmcdo29** [comment]
You need to emit the data to follow the `MessageEvent` interface as defined by Nest [and as stated in the docs](https://docs.nestjs.com/techniques/server-sent-events). You can change the line 
```ts
async emit(data) {
    this.emitter.emit('eventName', data);
}
```
to be
```ts
async emit(data) {
    this.emitter.emit('eventName', { data });
}
```
and it works
