### ISSUE TITLE
NestJS proxy for ESRI request

### ISSUE THREAD

**Issue by letiimmy** [nestjs/nest#5828]
I'm trying to redirect my ESRI-request from my frontend via my backend to the ESRI-endpoint (using it like a proxy).
If I do so, i get the following Error: 
![image](https://user-images.githubusercontent.com/70129675/100610666-6e6c0b80-3310-11eb-9baa-bece2ac93cfd.png)

I tried changing the url-endpoint directly to the arcgis api, instead of redirecting via localhost. This way it works, but that's not what i wanted to do.

Does anyone have an idea how to fix this? Request Headers looking fine so far...

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by letiimmy** [comment]
@kamilmysliwiec only sad when no One replies...

**Comment by jmcdo29** [comment]
@letiimmy [Someone did respond asking for more context on what you're doing, you never responded to them](https://discord.com/channels/520622812742811698/520649487924985885/783003923597361175)
