### ISSUE TITLE
Errors are shows in javascripts files instead of typescript files 

### ISSUE THREAD

**Issue by madhawa-se** [nestjs/nest#5829]
## Current behavior
  Error messages are shown inside js files instead of typescript file. I'm having hard time finding exact error line as i can only see  js error lines.i expect to see errors with .ts file lines.is there any configuration or something to fix this ?

![Capture](https://user-images.githubusercontent.com/9608201/100610998-a38b5480-3336-11eb-9239-98f2c68f369a.PNG)

## Environment
windows10  
nestjs v7.5.0

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
