### ISSUE TITLE
Sockets io version mismatch issues

### ISSUE THREAD

**Issue by simonbarker** [nestjs/nest#5832]
## Current behavior
socket io client 3.0.3 continually polls nestjs server and creates multiple clients in the gateway with different ides

## Input Code
https://github.com/simonbarker/nestjs-sockets

connect either of the frontends to the express app, no issues. Connect either of them to the nestjs app and connections don't hold.

## Expected behavior
ws connections are stable

## Possible Solution
use socker io client 2.3.1 and all seems fine

## Environment

<pre><code>
➜ nest --version              
7.5.3

**Comment by jmcdo29** [comment]
Socket.IO version 3 is not yet compatible with Nest. We're tracking this here: #5676

**Comment by SagaciousLittle** [comment]
and what about socket.io v4

**Comment by jmcdo29** [comment]
Socket.io v3 and v4 are compatible with each other, unlike v2 and v3. That said, v4 is what the [Nest v8 PR](https://github.com/nestjs/nest/pull/6349) seems to support. [Specific commit](https://github.com/nestjs/nest/pull/6349/commits/557b80338b77ea59541a14d4a7459f027da31558)
