### ISSUE TITLE
Nest Fastify Applicaiton not taking Fastify Adapter as second argument

### ISSUE THREAD

**Issue by CarrieEBeaton** [nestjs/nest#5833]
## Current behavior
I add new FastifyAdapter() as an argument to NestFastifyApplication and I get the following error: No matching overload.  It appears this is not available in the constructor anymore.

## Input Code
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());

The types returned by 'createMiddlewareFactory(...) are incompatible with allowed types

## Expected behavior
I expect to be able to register a fastify adapter with the Nest Factory for NestFastifyApplication per the current documentation:
https://docs.nestjs.com/techniques/performance

## Possible Solution
Create an overloaded constructor for the NestFastifyApplication that allows the FastifyAdapter

## Environment
Nest version:7.5.5
I have installed the most recent 
 
For Tooling issues:
- Node version: v14.15.1
- Platform: Windows

Others:
No

**Comment by jmcdo29** [comment]
I'm not able to replicate this. Do you have a minimum reproduction available?

**Comment by CarrieEBeaton** [comment]
Hi, I have the following:
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';

const fastify: any = new FastifyAdapter();

const app = await NestFactory.create<NestFastifyApplication>(AppModule, fastify);

and I don't get the type error but if I change the fastify type to be strongly typed as the Fastify Adapter I get the error that it is not a valid second argument in the NestFactory.create with the NestFastifyApplication interface.

**Comment by jmcdo29** [comment]
Yeah, this gives no error for me:
```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, new FastifyAdapter());
  await app.listen(3000);
}
bootstrap();

```
I can't replicate your issue. If you can provide a minimum reproduction that can be cloned and shows the issue, I'll happily reopen this.

**Comment by CarrieEBeaton** [comment]
I don't think this has to do with it but if I am trying to do the following to await fastify.register(require('fastify-express')); so I can I still use the express setup I had.  For example, I want to do the following: fastify.use(cookieParser());  Is that possible with the Fastify Adapter or am I setting it up incorrectly?

**Comment by jmcdo29** [comment]
Sounds like it might be set up incorrectly. You could be able to do `app.use(cookieParser())` after the `NestFactory`.
