### ISSUE TITLE
Request is undefined in Request-scoped strategies

### ISSUE THREAD

**Issue by ablipan** [nestjs/nest#5842]
## Current behavior

I'm following the [Authentication Document](https://docs.nestjs.com/security/authentication#request-scoped-strategies) to handle Request-scoped strategies, but the injected request in service is always undefined.

## Input Code

Repo: https://github.com/ablipan/nestjs-request-undefined

```ts
// local.strategy.ts
const contextId = ContextIdFactory.getByRequest(request)
const authService = await this.moduleRef.resolve(AuthService, contextId)
const user = await authService.getSession()

// auth.service.ts
constructor(@Inject(REQUEST) private request: FastifyRequest){}
```

## Expected behavior

The injected request is FastifyRequest object.
## Possible Solution

Sorry, i'm new to nestjs, don't really understand what nestjs did under the hood.

## Environment

<pre><code>
Nest version: 7.5.5

For Tooling issues:
- Node version: v12.16.3  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/security/authentication#request-scoped-strategies
