### ISSUE TITLE
NestJS DTO extended with PartialType breaks validation

### ISSUE THREAD

**Issue by auerbachb** [nestjs/nest#5844]
## Bug Report
https://stackoverflow.com/questions/64376439/nestjs-dto-extended-with-partialtype-breaks-validation
## Current behavior

This may simply be a `class-validator` limitation, but if I use `PartialType` the type coercion in the DTO, then in `useGlobalPipes` the `enableImplicitConversion: true,` does not work (ie I try to pass an integer but it remains a string and does not get coerced). 

The reason is explained in the S/O link

## Input Code

```ts
const your = (code) => here;
```

## Expected behavior

A new class object could be generated in the compilation process to work around this, or _**the documentation could be updated to note this limitation and avoid confusion**_

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by NicolasPapp94** [comment]
Hello, i have the same problem too for a Parent and Child class using Partial Types. The validations doesn't work. Can someone help us? 
Regards

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

If you think this is a bug please open a new issue and provide a [minimum reproduction repository](http://minimum-reproduction.wtf).
