### ISSUE TITLE
Transform called twice

### ISSUE THREAD

**Issue by ihorTymofieiev** [nestjs/nest#5852]
## Current behavior
Transform called twice

## Input Code

I have simple application with next method:

```
    @Get(`/:id`)
    @ApiImplicitParam({name: 'id', required: true})
    async getProjectInfo(@Query() query: GetProjectQueryDto) {
...
    }

```
And I have GetProjectQueryDto class:

```
import {IsBoolean, IsOptional} from 'class-validator';
import {ApiProperty} from '@nestjs/swagger';
import {Transform} from 'class-transformer';

export class GetProjectQueryDto {
    @IsOptional()
    @Transform(value => {
        // this method called twice
        // first with data is raw
        // second with transformed data
        return value === true.toString();
    })
    @IsBoolean()
    @ApiProperty({ required: false, type: Number, default: 'false', enum: ['false', 'true'] })
    includeAllRelations: boolean = false;
}

```

## Expected behavior
Transform call only once

## Environment

<pre><code>
Nest version: 7.5.5
 
For Tooling issues:
- Node version: 14.7.0
- Platform: Mac

Others:
- class-transformer: 0.3.1
- class-validator: 0.12.2
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by ihorTymofieiev** [comment]
@jmcdo29 
https://github.com/ihorTymofieiev/nest-transform-error

**Comment by jmcdo29** [comment]
This is from having to transform from `plainToClass` and once again from `classToPlain`. You can set up options to have it only work in one direction, or you can set `transform: true` in the `ValidationPipe`'s options to not have the`classToPlain` transformation called.

**Comment by elliotaplant** [comment]
@jmcdo29 Thanks for your answer. To clarify, is the intended logic to run both `plainToClass` and `classToPlain` when a DTO is received by the server? 

In this example, if we hit the `some-route` endpoint, what do you expect to console log?
```
// my.dto.ts
class MyDto {
  @Transform((params) => {
    if (params.type === TransformationType.PLAIN_TO_CLASS) {
      return "plain-to-class";
    } else if (params.type === TransformationType.CLASS_TO_PLAIN) {
      return "class-to-plain";
    }
   })
  myProperty: string;
}
```
```
// my.controller.ts
@Post('some-route')
public async route(@Body() myDto: MyDto): Promise<void> {
  // Does this log 'plain-to-class' or 'class-to-plain'?
  console.log(myDto.myProperty);
}
```

Thanks for your help!

**Comment by jmcdo29** [comment]
Also, if you have an `validatorOptions` set in the `ValidaitonPipe` config, `classTrasnformer.classToPlain` will be called, to take care of the possible use of `transformOptions`

https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L147
