### ISSUE TITLE
In GRPC, the Proto syntax is not fully explained in the fourth example.

### ISSUE THREAD

**Issue by aoumeior** [nestjs/nest#5861]
I want to add the use of oneof, enum, and Message in the fourth example.

I didn't know how to define them using Typescript's interface syntax.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
