### ISSUE TITLE
Try monorepo mode with javascript

### ISSUE THREAD

**Issue by ilaipi** [nestjs/nest#5864]
## Current behavior
my situation:

```
# create new project
nest n -l js -g -s  my-nest-js

cd my-nest-js

nest g app app1
```

and then my project switch to monorepo mode. But now, I got:

```
// index.js
require('@babel/register');
require('./src/main');  // this is wrong

// jsconfig.json  

// I think index.js and jsconfig.json show be deleted when nest g app app1 (or maybe they are moved to ./my-nest-js).
```

And, I really want to delete my-nest-js/my-nest-js (the default app), because I want my project has app1 and app2 and more apps.

Well, I can delete it manually.

But, How to start my app1? it was js, but in nest-cli.json:
```
    "app1": {
      "type": "application",
      "root": "apps/app1",
      "entryFile": "main",
      "sourceRoot": "apps/app1/src",
      "compilerOptions": {
        "tsConfigPath": "apps/app1/tsconfig.app.json"    // ERROR: not exists, and I AM JavaScript !!!
      }
    }
```

I have tried to create a nodemon.app1.json: 

```
{
  "watch": ["apps/app1/src"],
  "ext": "js",
  "ignore": ["apps/app1/src/**/*.spec.js"],
  "exec": "node apps/app1/index --exec babel-node"
}

// and add script to package.json:
"start:app1:dev": "nodemon --config nodemon.app1.json"
```

and then `npm run start:app1:dev`, got:
```
Error: Cannot find module 'babel-plugin-transform-decorators-legacy' from 'xxxx/my-nest-js/apps/app1'
```

## Expected behavior
1, nest new my-nest-js -m monorepo  (just create a new empty project with config files)
2, nest g app app1 (`compilerOptions: { jsConfigPath: "apps/app1/jsconfig.json" }`)
3, nest start app1 is ok

## Environment

<pre><code>
Nest version: 7.5.3

 
For Tooling issues:
- Node version: v12.16.1

- Platform:  Mac

Others:
package manager: npm
</code></pre>

**Comment by jmcdo29** [comment]
Kamil answered a similar question in the cli repo: [nest-cli#897](https://github.com/nestjs/nest-cli/issues/897)
