### ISSUE TITLE
nestJS API deployment

### ISSUE THREAD

**Issue by ettouzany** [nestjs/nest#5865]
I learned NestJS and I made a rest API with it.
now I want to deploy my API my questions are:
- can I deploy it to a shared hosting in a NodeJS application ?
- if not what is the proper method to Deploy it?

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/NestJS) channel (Support) for support questions. We are using GitHub to teach Bug Reports, regressions, and Feature Requests
