### ISSUE TITLE
Yet another "can't resolve dependencies" issue

### ISSUE THREAD

**Issue by MirageDT** [nestjs/nest#5868]
## Bug Report

I have checked back and forth my imports and it still not works. I have no idea why after 2 days of looking through all the same subjets reported by Google.

It should be noted that removing the `@Injectable` decorator from `jwt.strategy.ts` makes the build work, but not the code (the auth service is not injected)

## Current behavior

```
[16:02:31] File change detected. Starting incremental compilation...

[16:02:31] Found 0 errors. Watching for file changes.

[Nest] 22216   - 2020-12-06 16:02:32   [NestFactory] Starting Nest application...
[Nest] 22216   - 2020-12-06 16:02:32   [ExceptionHandler] Nest can't resolve dependencies of the AuthService (JwtService, ?). Please make sure that the argument dependency at index [1] is available in the AuthModule context.

blablabla
```

## Input Code

**app.module.ts**

```ts
@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'mongodb',
      useUnifiedTopology: true,
      host: 'localhost',
      port: 27017,
      database: 'XXX',
      logging: true,
      retryAttempts: 0,
      autoLoadEntities: true,
    }),
    ExtensionsModule,
    AuthModule,
    UsersModule,
  ],
  controllers: [AppController],
})
export class AppModule {}
```

**auth.module.ts**

```ts
@Module({
  imports: [
    PassportModule.register({
      defaultStrategy: 'jwt',
      property: 'user',
      session: false,
    }),
    JwtModule.register({
      secret: process.env.JWT_SECRET_KEY,
      signOptions: {
        expiresIn: process.env.JWT_EXPIRATION,
      },
    }),
    UsersModule,
  ],
  providers: [JwtStrategy, AuthService],
  exports: [PassportModule, JwtModule],
  controllers: [AuthController],
})
export class AuthModule {}
```

**users.module.ts**

```ts
@Module({
  imports: [TypeOrmModule.forFeature([MgUser])],
  providers: [UsersService],
  exports: [UsersService, TypeOrmModule],
})
export class UsersModule {}
```

**auth.service.ts**

```ts
@Injectable()
export class AuthService {
  constructor(private jwt: JwtService, private users: UsersService) {}

  async validateUser() {}
  async registerNewUser() {}
  async logUserIn() {}
  createToken() {}
}
```

**jwt.strategy.ts**

```ts
@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor(private auth: AuthService) {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      secretOrKey: process.env.JWT_SECRET_KEY,
      secretOrPrivateKey: process.env.JWT_SECRET_KEY,
    });
  }

  async validate() {}
}
```

## Environment

<pre><code>Nest version: 7.5.3 </code></pre>

**Comment by MirageDT** [comment]
Okay I have found the issue ! 

Couple of imports were having the format

```ts
import { UsersService } from 'src/users/users.service';
```

Changing **ALL** to 

```ts
import { UsersService } from '../users/users.service';
```

*(Well depending on the file obviously)*

Did the trick. 

Very not straightforward and obscure, so I will keep this ticket open in hope this gets either resolved, or explained better !

**Comment by jmcdo29** [comment]
When you compile your code, the ts files that are originally in `src` get transpiled to `js` files into (most likely) `dist`, keeping the rest of the same structure (i.e. `src/XXX/YYY.service.ts` becomes `dist/XXX/YYY.service.js`). Due to this, importing from `src` really isn't a great practice with Typescript as it can lead to situations like above. 

Next time, please use our [Discord](https://discord.gg/nestjs) channel (Support) for help questions as we are using GitHub for tracking Bug Reports, Feature Requests, and Regressions.

**Comment by Maryannah** [comment]
Just for the record, I did not choose to import from src, my IDE did. Is there a way to setup the ts condig so that it uses relative imports ?

(I do not face this issue with angular for instance)
