### ISSUE TITLE
The test module dependencies is wrong

### ISSUE THREAD

**Issue by OlegYudovichFiverr** [nestjs/nest#5875]
## Current behavior

The tests fail on another modules dependency

## Input Code

I have simple HealthController:
```ts
@Controller('api/v1/health')
export class HealthController {
    constructor(
        private readonly health: HealthCheckService,
        private readonly pegasusHealthIndicator: PegasusHealthIndicator
    ) { }

    @Get()
    @HealthCheck()
    check() {
        return this.health.check([
            () => this.pegasusHealthIndicator.isHealthy(Configuration.appName),
        ]);
    }
}
```

And here is the module:

```ts
import { Module } from '@nestjs/common';
import { HealthController } from '../controllers';
import { PegasusHealthIndicator } from '../services/health';
import { TerminusModule } from '@nestjs/terminus';

@Module({
    imports: [TerminusModule],
    controllers: [HealthController],
    providers: [PegasusHealthIndicator]
})
export class HealthModule { }
```
This is the test:

```ts
import {
	Test,
	TestingModule
} from '@nestjs/testing';
import { HealthController } from '../controllers';
import { PegasusHealthIndicator } from '../services/health';
import { TerminusModule } from '@nestjs/terminus';

describe('HealthController', () => {
	let controller: HealthController;

	beforeEach(async () => {
		const module: TestingModule = await Test.createTestingModule({
            imports: [TerminusModule],
            controllers: [HealthController],
            providers: [PegasusHealthIndicator]
		}).compile();

		controller = module.get<HealthController>(HealthController);
	});

	it('should be defined', () => {
		expect(controller).toBeDefined();
	});
});
```

This test works well and check is passed.
But when i add another controller, not related to this module:
```ts
import { Controller } from '@nestjs/common';
import { DispatchService } from '../../services';

@Controller()
export class BaseMicroserviceController {
    constructor(protected readonly dispatchService: DispatchService) { }
}
```
The test fail because Test suite trying to load dependencies of another controllers which implements this `BaseMicroserviceController` and belongs to another module.

## Expected behavior

The Testing module should't load dependencies not related to this module

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 14  
- Platform:   Mac

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository. I'll say, this looks like a configuration problem with how the test is set up, but I'll dig in if you can provide something.

**Comment by OlegYudovichFiverr** [comment]
> Please provide a minimum reproduction repository. I'll say, this looks like a configuration problem with how the test is set up, but I'll dig in if you can provide something.

I started to create an example repo to share it with you and found the problem.
The problem is not related to NestJS testing modules.
In my test in the above example i require controller from '../controllers'
This folder have `index.ts` file:

```
export * from './v1/health.controller';
export * from './logged-out-homepage.controller';
```

The test was trying to import another controller dependencies
Fixed it by explicit import from '../controllers/v1/health.controller'
My mistake, sorry for the noise guys
