### ISSUE TITLE
Sample Microservices Architecture

### ISSUE THREAD

**Issue by mcbrowny35** [nestjs/nest#5876]
So, I looked into the documentation for nestjs microservices and I'm relatively new to microservices. I was wondering if it was possible if the people who created the samples could create or reference an example with for instance 2 microservices, and an api gateway since this could help new people out.

**Comment by jmcdo29** [comment]
Both the [microservice sample](https://github.com/nestjs/nest/tree/master/sample/03-microservices) and the [grpc sample](https://github.com/nestjs/nest/tree/master/sample/04-grpc) show microservices (even if they are used as a hybrid application). 

That said, it could be nice to have a full microservice sample with some light orchestration between them and using a few different transport types with an API gateway. I'll see if I have some time to throw that together. 

In the meantime, feel free to ask our on our [Discord](https://discord.gg/nestjs) and see if anyone has a sample they're willing to share.

**Comment by mcbrowny35** [comment]
Thanks for letting me know! :)
