### ISSUE TITLE
Disable bodyParser just for one specific route

### ISSUE THREAD

**Issue by eric72** [nestjs/nest#5907]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

Hi, i wanted to know, is it possible to disable bodyParser just for one specific route and not the rest of my webservice ?
ps: i didn't get answer from discord.

**Comment by kamilmysliwiec** [comment]
We are using GitHub to track bugs, feature requests, and potential improvements. If you need help, please, use our Discord channel or StackOverflow.
