### ISSUE TITLE
Custom injection with decorator

### ISSUE THREAD

**Issue by bokzor** [nestjs/nest#5912]
With typeDI I was able to use a decorator to inject a custom service.
I would love to see this kind of feature !

Here is some code to be understood.

```
/**
 * Annotation that will inject the logger
 *
 * Should be use on a constructor parameter
 * constuctor(private @Log(//optional{name: 'MyLogger'}))
 *
 * By default the logger's name is the className
 */

export function Log(options?: LoggerDecoratorOptions): Function {
    return function(object: any | Function, propertyName: string, index?: number): any {
        Container.registerHandler({
            object,
            index,
            propertyName,
            value: container => {
                const loggerService: LoggerService = container.get(LoggerService);
                return loggerService.getLogger(options?.name || object.name);
            }
        });
    };
}
```

**Comment by jmcdo29** [comment]
This seems like a factory provider wrapped inside of a decorator, which would mean that it's not really within Nest's DI context anymore. I suppose you could do something similar, and mark the parameter then as `@Optional()` so that Nest doesn't try to instantiate it, but why not just use a factory instead of the decorator?

**Comment by bokzor** [comment]
I cannot use a factory because the logger will be instantiated per class. (Some class can log in debug others not, some loggers are part of the group 'Repository' and so on....

Do you have any example on how to inject the logger service for a decorator in the constructor ?

I successfully injected the service with a decorator on a method but it's not working on constructor parameters.


An example of successful injected service on a method : 

@logErrorDecorator()  
getEntity(): Entity {
 }

```
export function logErrorDecorator() {
  const injectLogger = Inject(LoggerService);

  return (target: any, propertyKey: string, propertyDescriptor: PropertyDescriptor) => {
    injectLogger(target, 'logger'); // this is the same as using constructor(private readonly logger: LoggerService) in a class

    //get original method
    const originalMethod = propertyDescriptor.value;

    //redefine descriptor value within own function block
    propertyDescriptor.value = async function(...args: any[]) {
      try {
        return await originalMethod.apply(this, args);
      } catch (error) {
        const loggerService: LoggerService = this.logger;
        const logger = loggerService.getLogger();
        logger.setContext(target.constructor.name);
        logger.error(error.message, error.stack);

      }
    };
  };
}
```

**Comment by kamilmysliwiec** [comment]
> I cannot use a factory because the logger will be instantiated per class. (Some class can log in debug others not, some loggers are part of the group 'Repository' and so on....

You can always make logger transient-scoped. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
