### ISSUE TITLE
Release 7.6.1 does not include the kafka-options.interface file, resulting in TS compilation errors

### ISSUE THREAD

**Issue by Jedeu** [nestjs/nest#5917]
We ran into an issue with our TS linter throwing the error `Cannot find module '@nestjs/microservices/external/kafka-options.interface'` after upgrading from `7.5.5` to `7.6.1` for @nestjs/common and @nestjs/core. It appears this is because the release does not include this file.

Our current workaround is to just keep our nestjs version to `7.5.5`, but would be interested to know if there were issues with the interface file that we should be aware of.

**Comment by kamilmysliwiec** [comment]
This file was never supposed to be a part of the public API (and hence, it wasn't exported from the root `index.ts`). Anyways, depending on what you need, you can still access these types from this import `@nestjs/microservices/external/kafka.interface`. Keep in mind that these type definitions are simply copied from this file https://github.com/tulios/kafkajs/blob/master/types/index.d.ts and so we would recommend to import them from `kafkajs` directly instead.
