### ISSUE TITLE
shared_utils_1.addLeadingSlash is not a function

### ISSUE THREAD

**Issue by Lidashuai1** [nestjs/nest#5920]
## Bug Report
shared_utils_1.addLeadingSlash
## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dengnan123** [comment]
me too

**Comment by phonegap100** [comment]
me too

**Comment by twou12031** [comment]
> ## Bug Report
> shared_utils_1.addLeadingSlash
> 
> ## Current behavior
> ## Input Code
> ```ts
> const your = (code) => here;
> ```
> 
> ## Expected behavior
> ## Possible Solution
> ## Environment
> ```
> 
> Nest version: X.Y.Z
> 
>  
> For Tooling issues:
> - Node version: XX  
> - Platform:  
> 
> Others:
> ```

i have the same problem.
then i use the @nestjs/core@7.5.0
solved.

**Comment by kamilmysliwiec** [comment]
Please, update both `@nestjs/core` and `@nestjs/common` packages. Their versions must be in sync
