### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by HTMHell** [nestjs/nest#5925]
## Current behavior
I'm using `WebSocketGateway` with `redis-io` adapter. I'm trying to broadcast a message to all clients that are connected to a room, and I get this exception:

> TypeError: callback is not a function
> [0]     at Encoder.encode (E:\Workspace\Web\matan\backend\node_modules\socket.io-parser\index.js:135:5)
> [0]     at RedisAdapter.broadcast (E:\Workspace\Web\matan\backend\node_modules\socket.io-adapter\dist\index.js:102:45)
> [0]     at RedisAdapter.broadcast (E:\Workspace\Web\matan\backend\node_modules\socket.io-redis\dist\index.js:267:15)
> [0]     at Socket.emit (E:\Workspace\Web\matan\backend\node_modules\socket.io\lib\socket.js:171:18)
> [0]     at WsExceptionsHandler.handleUnknownError (E:\Workspace\Web\matan\backend\node_modules\@nestjs\websockets\exceptions\base-ws-exception-filter.js:29:16)
> [0]     at WsExceptionsHandler.handleError (E:\Workspace\Web\matan\backend\node_modules\@nestjs\websockets\exceptions\base-ws-exception-filter.js:15:25)
> [0]     at WsExceptionsHandler.catch (E:\Workspace\Web\matan\backend\node_modules\@nestjs\websockets\exceptions\base-ws-exception-filter.js:11:14)
> [0]     at WsExceptionsHandler.handle (E:\Workspace\Web\matan\backend\node_modules\@nestjs\websockets\exceptions\ws-exceptions-handler.js:17:20)
> [0]     at WsProxy.handleError (E:\Workspace\Web\matan\backend\node_modules\@nestjs\websockets\context\ws-proxy.js:28:27)
> [0]     at EventsGateway.<anonymous> (E:\Workspace\Web\matan\backend\node_modules\@nestjs\websockets\context\ws-proxy.js:21:22)

## Input Code
This is the line that causes the problem:
```ts
client.to(room).emit('test');
```
I've shrinked the class to only what is relevant:
```
import {ConnectedSocket, SubscribeMessage, WebSocketGateway, WebSocketServer} from '@nestjs/websockets';
import {Server, Socket} from 'socket.io';

@WebSocketGateway(3005, {transports: ['websocket']})
export class EventsGateway {
    @WebSocketServer() server: Server;

    @SubscribeMessage('joinRoom')
    public joinRoom(@ConnectedSocket() client: Socket, room: string): void {
        client.join(room);
        client.emit('joinedRoom', room); // working
        client.to(room).emit('test'); // throwing exception
    }
}
```

## Expected behavior
It should emit a message to all clients in the room (except the sender)
I also tried:
```
this.server.to(room).emit('test');
```
which should broadcast to all clients in the room including the sender, but I get the same behavior.

## Environment

<pre><code>
[System Information]
OS Version     : Windows 10
NodeJS Version : v12.16.1
NPM Version    : 6.13.4

[Nest CLI]
Nest CLI Version : 7.5.4

[Nest Platform Information]
platform-socket.io version : 7.6.1
platform-express version   : 7.6.1
websockets version         : 7.6.1
passport version           : 7.1.5
typeorm version            : 7.1.5
common version             : 7.6.1
core version               : 7.6.1
jwt version                : 7.2.0
</code></pre>

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/5789
