### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by indhio** [nestjs/nest#593]
## Environment
<pre><code>
Nest version: 4.5.10

 
For Tooling issues:
- Node version: v8.6.0
- NPM version: 5.8.0
- Platform:  Mac (macOS High Sierra - 10.13.3) 
</code></pre>

## Problem and steps
I am tried uploading file to Firebase Storage using 'firebase'
<pre><code>
import * as firebase from 'firebase';

upload(bytes: Uint8Array, id: string): void {
        try {
            var storage = firebase.app().storage("gs://seta-fcd79.appspot.com/");
            console.log(storage);

            var storageRef = storage.ref();

            var message = 'This is my message.';
            storageRef.child('file.png').putString(message).then(function (snapshot) {
                console.log('Uploaded a raw string!');
            });

        } catch (error) {
            console.log(error);
        }
    }
</code></pre>

When I'm submitting a service to Firebase Storage a receive that follow error. 
<pre><code>
/Users/indhio/Desenv/workspace/git/xxx/xxx/node_modules/@firebase/storage/dist/index.cjs.js:672
        this.xhr_ = new XMLHttpRequest();
                        ^
ReferenceError: XMLHttpRequest is not defined
    at new NetworkXhrIo (/Users/indhio/Desenv/workspace/git/xxx/xxx/node_modules/@firebase/storage/dist/index.cjs.js:672:25)
    at XhrIoPool.createXhrIo (/Users/indhio/Desenv/workspace/git/xxx/xxx/node_modules/@firebase/storage/dist/index.cjs.js:798:16)
    at doTheRequest (/Users/indhio/Desenv/workspace/git/xxx/xxx/node_modules/@firebase/storage/dist/index.cjs.js:3130:34)
    at Timeout._onTimeout (/Users/indhio/Desenv/workspace/git/xxx/xxx/node_modules/@firebase/storage/dist/index.cjs.js:3001:13)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[nodemon] app crashed - waiting for file changes before starting...
</code></pre>

I don't know why but I think XMLHttpRequest is not included in NestJS. 

Anyone know how can I add XMLHttpRequest in my project to firebase service use?

**Comment by shekohex** [comment]
I think this issue related to firebase module, not nestjs, you should follow up this [issue](https://github.com/firebase/firebase-js-sdk/issues/349)

**Comment by chanlito** [comment]
@indhio you have to use "firebase-admin" with node.js

**Comment by chanlito** [comment]
@indhio `XMLHttpRequest ` doesn't exists in node.js

**Comment by indhio** [comment]
@chanlito I follow the documentation and had implemented in another projects with angular and works very well. 

Someway XMLHttpRequest don’t work inside nest project. I just don’t why yeat.

**Comment by chanlito** [comment]
`I just don’t why yeat.` - because Nest.js doesn't run on the browser.

**Comment by chanlito** [comment]
If you want to use firebase with node.js, you have to use `firebase-admin` from npm.

**Comment by indhio** [comment]
@chanlito of course Nest.Js don’t run in browser. I really forget that for a moment. Thanks for your help!
