### ISSUE TITLE
Order of routes sharing the same prefix across multiple controllers

### ISSUE THREAD

**Issue by nilscox** [nestjs/nest#5931]
## Is your feature request related to a problem? Please describe.

Hi! I don't think there's a way to deal with controllers that share the same url prefix.

As described in #2394, if a controller uses a route param, it will shadow the routes defined in controllers that start with the same url:

- `/store/:id` in `StoreController` will always match
- `store/item-inventory` in `ItemInventoryController` cannot be matched

Here is a reproduction repository with a failing test: https://github.com/nilscox/repro-controllers-order

## Describe the solution you'd like

Having some kind of control over the order controllers are registered would be great, but I don't have a specific solution in mind.

**Comment by kamilmysliwiec** [comment]
The failing test has a small typo (`'/store/item-invetory'` -> `'/store/item-inventory'`).

As I've said in the issue you mentioned, the order matters. If you want the `store/item-inventory` route to be registered first, the `ItemInventoryController` must be placed before `StoreController` in the module definition. If controllers exist in different modules, you can control the order by importing them in the root module. For example, if you change `AppModule` file to this:

```typescript
@Module({
  imports: [ItemInventoryModule, StoreModule],
})
export class AppModule {}
```

Tests will suceed.

**Comment by nilscox** [comment]
Thanks for your answer. Indeed, [this solves the problem](https://github.com/nilscox/repro-controllers-order/commit/d462ee6dd8632724c4dc0174a1b823ff22683b70).

So if I understand correctly, I can't have both the `ItemInventoryModule` as a child of `StoreModule` and have control over the controllers orders. In a real world project, it's unfortunate because it would make sense to have a specific modules hierarchy, but can't be achieved because of this issue.

Is there something I'm missing?
