### ISSUE TITLE
Absolute imports don't work in testing environment 

### ISSUE THREAD

**Issue by sarmad1995** [nestjs/nest#5933]
## Current behavior
When absolute paths are configured throught tsconfig.json. The absolute paths don't while while in testing environemnt.

## Input Code
```ts
Test suite failed to run

    Cannot find module 'users/users.service' from 'auth/auth.service.ts'

    Require stack:
      auth/auth.service.ts
      auth/auth.resolver.ts
      auth/auth.resolver.spec.ts

      1 | import { Injectable, UnauthorizedException } from '@nestjs/common';
    > 2 | import { UsersService } from 'users/users.service';
```
My tsconfig

```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "allowUnreachableCode": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitAny": true,
    "noUnusedParameters": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "noUnusedLocals": true,
    "sourceMap": true,
    "outDir": "./dist",
    "incremental": true,
    "rootDir": "./src"
  },
}

```

## Expected behavior
The absolute paths should work in testing environment as well, or there must be a way to configure it.

## Environment

<pre><code>
Nest version: 7.0.0

 
For Tooling issues:
- Node version: v14.8.0 
- Platform:  Mac,

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by FacePalmDev** [comment]
It really would have helped if you'd just answered the question here. I could have read your answer. Instead you'd rather 1000's of people come to you on discord and ask the same question over and over?! Seriously?

**Comment by jmcdo29** [comment]
@FacePalmDev the thing is, this isn't a problem with the framework, it's a configuratiion problem with jest, so we don't have time to answer every question about every integration within the framework. You could come to the same issue when using express and Jest, would you go to Express's repo and ask about it? What about Fastify? The underlying cause here, was indeed, the jest configuration. Not something to do with the Nest framework at all.

**Comment by kamilmysliwiec** [comment]
@FacePalmDev this issue is completely unrelated to the framework.
