### ISSUE TITLE
GraphQL + Fastify CORS does not seems to work

### ISSUE THREAD

**Issue by delucca** [nestjs/nest#5943]
hi!

I'm trying to enable cors in my server and not being able to do so. I have a NestJS backend using Fastify adapter and GraphQL that is being used by Apollo GraphQL client.

I've added the `enableCors` to my bootstrap module and also the cors configs for my GraphQL module, but it does not seems to work.

Here is my bootstrap:

```ts
import { existsSync, readFileSync } from 'fs'

import { ValidationPipe } from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import { NestFactory } from '@nestjs/core'
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify'

import appConfig from 'config/app/config'
import buildLogger from 'lib/logger'

import BootstrapModule from './module'

async function bootstrap() {
  const https = buildHttpsConfig()
  const app = await NestFactory.create<NestFastifyApplication>(
    BootstrapModule,
    new FastifyAdapter({ https }),
  )

  const configService: ConfigService = app.get(ConfigService)

  const logger = buildLogger(
    configService.get('logging.level'),
    configService.get('logging.serviceName'),
  )

  app.setGlobalPrefix(configService.get('globalPrefix'))
  app.useLogger(logger)
  app.enableCors({
    origin: 'https://local.getbud.co:3000',
    credentials: true,
  })
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
    }),
  )

  await app.listen(configService.get('port'), '0.0.0.0')
  logger.log(`Started server listening to port ${appConfig.port.toString()}`)
}

const buildHttpsConfig = () => {
  const isHttps =
    existsSync(appConfig.https.credentials.key) && existsSync(appConfig.https.credentials.cert)

  const httpsConfig = isHttps
    ? {
        key: readFileSync(appConfig.https.credentials.key),
        cert: readFileSync(appConfig.https.credentials.cert),
      }
    : {}

  return httpsConfig
}

export default bootstrap
```
And this is the factory of my GraphQL module:

```ts
import { ConfigModule, ConfigService } from '@nestjs/config'
import { GqlModuleAsyncOptions } from '@nestjs/graphql'

import { gqlConfig } from 'config'

const graphQLFactory: GqlModuleAsyncOptions = {
  imports: [ConfigModule.forFeature(gqlConfig)],
  inject: [ConfigService],
  useFactory: async (configService: ConfigService) => ({
    debug: configService.get('debug'),
    playground: configService.get('playground'),
    autoSchemaFile: configService.get('schemaFile'),
    cors: configService.get('cors'),
    useGlobalPrefix: true,
  }),
}

export default graphQLFactory
```

Where `configService` of GraphQL module returns the following:
```ts
const config: GqlConfigOptions = {
  debug: APP_ENV !== 'production',
  playground: APP_ENV !== 'production',
  schemaFile: GRAPHQL_SCHEMA_FILE_PATH,
  cors: {
    credentials: true,
    origin: 'https://local.getbud.co:3000',
  },
}
```

Anyone can help me discover what am I doing wrong? Thanks!

**IMPORTANT:** I've already tried using `origin: true`, `origin: '*'` and also adding `methods: ['GET', 'PUT', 'PATCH', 'POST', 'DELETE', 'OPTIONS']` but the issue persisted.

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by delucca** [comment]
@jmcdo29 how can I create a minimum repository to test CORS? It would be complicated to do so.

There are any specific requirements for CORS using the Fasting adapter?

I searched lot and it seems that other users have this issue too, none of them were able to solve it.

**Comment by jmcdo29** [comment]
> how can I create a minimum repository to test CORS? 

How can we tell you if this is a bug or not without one?

> any specific requirements for CORS using the Fastify adapter?

Make sure to have `fastify-cors` installed. That's about it.

**Comment by delucca** [comment]
> > how can I create a minimum repository to test CORS?
> 
> How can we tell you if this is a bug or not without one?
> 
> > any specific requirements for CORS using the Fastify adapter?
> 
> Make sure to have `fastify-cors` installed. That's about it.

I have the `fastify-cors` package installed, already :/

**Comment by kamilmysliwiec** [comment]
We can't help you without the reproduction repository. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support)/StackOverflow for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
