### ISSUE TITLE
Use "stderr" too instead of only "stdout" on default nest common Logger

### ISSUE THREAD

**Issue by Hwan-seok** [nestjs/nest#5952]
## Feature Request

Use `stderr` on error log made by common `LoggerService`

## Is your feature request related to a problem? Please describe.

Currently, common logger service uses only `stdout` but no `stderr` on every log levels(info, warn, error, ...).
But it is common behavior to seperate common logs and error logs into other files such as `access.log` and `error.log`
We can achieve this by building custom logger but I think it is more standard approach that `Logger.error` uses `stderr` and `Logger.log, Logger.warn, etc...` uses `stdout`

### logger service
https://github.com/nestjs/nest/blob/2b1529923eb4a1c79feef4c684c558bd279bf5a6/packages/common/services/logger.service.ts#L156

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/5986
