### ISSUE TITLE
Private methods in ClassSerializerInterceptor make impossible to extend from it

### ISSUE THREAD

**Issue by Baterka** [nestjs/nest#5957]
## Describe the solution you'd like
In `ClassSerializerInterceptor` (https://github.com/nestjs/nest/blob/master/packages/common/serializer/class-serializer.interceptor.ts) is `getContextOptions` method private.

This means that I cannot properly extend this class and use custom `intercept` method, because I will get TS error.

When I want to pass custom **dynamic** options into `class-transformer`, I am unable to do it like so:
```typescript
export class CustomClassSerializerInterceptor extends ClassSerializerInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    // @ts-ignore
    const contextOptions = this.getContextOptions(context);
    const options = {
      ...this.defaultOptions,
      ...contextOptions,
      groups: res.user.roles //pseudo
    };
    return next
      .handle()
      .pipe(map((res: PlainLiteralObject | Array<PlainLiteralObject>) => this.serialize(res, options)));
  }
}
```

Second option is to create fully custom interceptor, but that is pointless code duplication, when I want exacly same interceptor, just add dynamically some options (ex. based on current http request).

I think that change of `getContextOptions` from `private` to `protected` would be nice.

## What is the motivation / use case for changing the behavior?
We will be able to extend `ClassSerializerInterceptor` with custom `intercept` method.

**Comment by jmcdo29** [comment]
Couldn't you use something like the `@SerializationOptions()` decorator to [pass extra options](https://docs.nestjs.com/techniques/serialization#pass-options)?

**Comment by Baterka** [comment]
> Couldn't you use something like the `@SerializationOptions()` decorator to [pass extra options](https://docs.nestjs.com/techniques/serialization#pass-options)?

Nope. Decorators are static :) I need to intercept based on data from request

**Comment by jmcdo29** [comment]
> I need to intercept based on data from request

That would've been good to add to the original issue. You _mentioned_ dynamic options, but then showed something static so it wasn't clear what you were trying to do.

**Comment by kamilmysliwiec** [comment]
We can change the modifier to `protected` instead. Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/5982
