### ISSUE TITLE
Nest core doesn't compile on Node v14

### ISSUE THREAD

**Issue by nirga** [nestjs/nest#5967]
## Current behavior
When running `npm i` on https://github.com/nestjs/nest with Node v14, there's a failure to install **fsevents**. It appears that v1 of it [has been deprecated](https://www.npmjs.com/package/fsevents/v/1.2.9) and can't be used anymore on Node v14.

## Possible Solution

There're several possible solutions (probably it's best to do them all):
1. Update [CONTRIBUTING.md](https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md) specifying that the dev environment should Use Node with version < 14
2. Adding an nvmrc with the target Node version that works well.
3. Upgrading to fsevents v2.

## Environment

<pre><code>
Nest version: 7.5.3

 
For Tooling issues:
- Node version: 14  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/5968#issuecomment-747485379
