### ISSUE TITLE
Sample build error

### ISSUE THREAD

**Issue by nvthuong1996** [nestjs/nest#5969]
I try pull latest code in master branch
Follow step
```
cd sample/08-webpack
npm i
npm run build:dev
```

Error apper
```
> nest-typescript-starter@1.0.0 build:dev
> nest build --watch --webpack --webpackPath webpack-hmr.config.js


 Info  Webpack is building your sources...


 Error  The 'compilation' argument must be an instance of Compilation

```

**Comment by jmcdo29** [comment]
The `webpack` version is probably too new, so the build fails. You can find [more information here](https://github.com/nestjs/docs.nestjs.com/issues/1554). In the meantime, we're working on fixing it, but this has already been discussed.

**Comment by nvthuong1996** [comment]
thank you.
