### ISSUE TITLE
How to catch 401 error and then resubmit original request

### ISSUE THREAD

**Issue by henryyue2010** [nestjs/nest#5978]
I need to write a http header interceptor to add Authorization header, if there is 401 error, submit another request for new token, then resubmit the original request with the new token.

catchError(async error => {

    if (error.response.status === 401) {

      // get a new token 

      // then resubmit the request with the new token
      
      const originalRequest = error.config;
      
      return next.handle(originalRequest);
    }

  })
But next.handle(originalRequest) doesn't work. How to resubmit the original request in the interceptor? Thank you very much in advance for your help.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
