### ISSUE TITLE
Error when connecting REDIS microservice transporter on digitalocean managed database

### ISSUE THREAD

**Issue by yusufola** [nestjs/nest#5981]
## Bug Report
I am using the redis transporter on nestjs microservice to connect to my redis managed db hosted on digitalocean and I keep getting error after a few minutes of starting my service. 
NOTE: This error didn't show up on the nestjs microservice client connection just consumer services

The redis connection string is prefixed with rediss:// but I have also tried redis:// and it is still not working

## Current behavior
Currently getting 
**Error: Retry time exhausted**

## Input Code

This is the code I am currently connecting with 
```ts
  const app = await NestFactory.createMicroservice<MicroserviceOptions>(
    AppModule,
    {
      transport: Transport.REDIS,
      options: {
        url: process.env.REDIS_URL,
        tls: {}
      },
    },
  );
```

## Expected behavior

Expect a connection to the managed redis on digitalocean.

## Possible Solution

An alternative way of connecting to redis using tls. I'm able to connect to other redis (heroku) which don't require tls

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
