### ISSUE TITLE
[Proposal] Reflect the application globals in an end-to-end test (@nestjs/testing)

### ISSUE THREAD

**Issue by omermorad** [nestjs/nest#5995]
## Is your feature request related to a problem? Please describe.
When creating a new `INestApplication` using `NestFactory` in the `main.ts` file, we can of course use application globals, like `app.useGlobalFilters()` or `app.useGlobalInterceptor()` for example.

So far so good, but when I want write an `e2e` test for the actual application, let's say, for example, testing the full flow from the `Controller` until the `Repository` (which uses any kind of database) - I ran into to a problem.

All the global middleware, interceptors, filters and even the application global prefix (`app.setGlobalPrefix('prefix')`) are not being reflected in the testing application, cause as we know, it's a different module.

Here is the example from the official documentation of Nest:

```typescript
describe('Cats', () => {
  let app: INestApplication;
  let catsService = { findAll: () => ['test'] };

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [CatsModule],
    })
      .overrideProvider(CatsService)
      .useValue(catsService)
      .compile();

    app = moduleRef.createNestApplication();
    await app.init();
  });

  it(`/GET cats`, () => {
    return request(app.getHttpServer()).get('/cats').expect(200).expect({
      data: catsService.findAll(),
    });
  });

  afterAll(async () => {
    await app.close();
  });
});

``` 

The `application` instance created from `moduleRef.createNestApplication()` is of course not the same instance of the one from the `main.ts` file where we use the `NestFactory` to create the application.

```typescript
const app = await NestFactory.create(AppModule);
app.useGlobalInterceptors( ... )
```

The problem is that the global interceptors I use in the "real" application, is not reflected in the module I compile in the test file.

## Describe the solution you'd like
The solution is to somehow add all the globals to the `createTestingModule` method and to simulate a "real-app" request-response cycle, including all the middeware types (interceptors, guards, filters, etc.).

## Teachability, Documentation, Adoption, Migration Strategy

**main.ts**

```typescript
(async () => {
  const app = await NestFactory.create(AppModule);

  app.registerGlobals({
    useInterceptors: [ ... ],
    useGuards: [ ... ],
  });

  await app.listen(3000);

  console.log(`Application is running on: ${await app.getUrl()}`);
})();
```

**some-test.spec.ts**

```typescript

describe('Cats', () => {
  let app: INestApplication;
  let catsService = { findAll: () => ['test'] };

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }, { ... <the same object we use in the main.ts file above> })
      .overrideProvider(CatsService)
      .useValue(catsService)
      .compile();

    app = moduleRef.createNestApplication();
    await app.init();
  });

  it(`/GET cats`, () => {
    return request(app.getHttpServer()).get('/cats').expect(200).expect({
      data: catsService.findAll(),
    });
  });

  afterAll(async () => {
    await app.close();
  });
});
```

## What is the motivation / use case for changing the behavior?
Writing reliable end-to-end tests the uses an identical application request-response flow like in the actual application in the `main.ts` file.

**Comment by jmcdo29** [comment]
This would require whatever is in `main.ts` to be ran before `test:e2e` which doesn't make sense in a CI/CD setting. If you need globals for interceptors and other enhancers you can use the `APP_<ENHANCER_TYPE>` token for a custom provider [as mentioned in the docs](https://docs.nestjs.com/pipes#global-scoped-pipes) (all enhancers have one of these and they act as multi-value providers).

Another idea is to abstract out the registration of middleware and global values to a function and call that single function is the test setup and in `main.ts`. Both of these approaches bring more stability and parity between how the application and test run.

**Comment by omermorad** [comment]
> This would require whatever is in `main.ts` to be ran before `test:e2e` which doesn't make sense in a CI/CD setting. If you need globals for interceptors and other enhancers you can use the `APP_<ENHANCER_TYPE>` token for a custom provider [as mentioned in the docs](https://docs.nestjs.com/pipes#global-scoped-pipes) (all enhancers have one of these and they act as multi-value providers).

@jmcdo29 I think I was not clear enough in my original example, so I've edited it, hope it is clearer now.

I didn't mean to run the code altogether haha; I meant two separate files, one for the application (`main.ts`) and another one for the test (`some-test.spec.ts`)

Did you get what I mean now? 

> Another idea is to abstract out the registration of middleware and global values to a function and call that single function is the test setup and in `main.ts`. Both of these approaches bring more stability and parity between how the application and test run.

Can you give a short example just to make sure I understand?

**Comment by kamilmysliwiec** [comment]
> Can you give a short example just to make sure I understand?

Example:

```typescript
export function registerGlobals(app: INestApplication) {
  app.useGlobalFilters(...);
  app.useGlobalInterceptors(...);
  app.setGlobalPrefix('prefix');
}
```

`main.ts`:

```typescript
const app = await NestFactory.create(AppModule);
registerGlobals(app);
await app.listen(3000);
```

Test file:

```typescript
app = moduleRef.createNestApplication();
registerGlobals(app);
await app.init();
```
