### ISSUE TITLE
Query and Params decorator cannot be used in same function?

### ISSUE THREAD

**Issue by sandeshgb** [nestjs/nest#6000]
## Current behavior
I need to use param and query decorator in same function, but its giving me 404 error

## Input Code
`@Get('count/:userId')
    async getCount(@Param('userId') userId: any = 0, @Query() query, @Res() res) {
        const count = await this.service.getCount(userId, query);
        return res.status(HttpStatus.OK).json(count);
    }`

## Environment

Nest version: 7.0.2

 
For Tooling issues:
- Node version: 13.14.0
- Platform:  Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by sandeshgb** [comment]
I know that, but I've posted here as a feature request.
It does not support both decorators at the same time.

**Comment by sandeshgb** [comment]
> Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

@kamilmysliwiec 
You can consider this as an improvement or feature request..
I've already tested it, hence have asked for a solution just in case if I haven't missed any anything!!

**Comment by jmcdo29** [comment]
@sandeshgb they can and do work in the same function together. I have the following controller:

```typescript
import { Controller, Get, Param, Query } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  @Get(':name')
  getHelloWithName(
    @Param('name') name: string,
    @Query() query: Record<string, any>,
  ): Record<string, any> {
    return {
      hello: this.appService.getHello(name),
      query,
    };
  }
}
```
And can send in the following curl and get a response like so:
```shell
▶ curl http://localhost:3000/Jay\?key\=value
{"hello":"Hello Jay!","query":{"key":"value"}}%  
```
Both `@Param()` and `@Query()` are working as designed.
