### ISSUE TITLE
why must I config jwt twice?

### ISSUE THREAD

**Issue by MaoScut** [nestjs/nest#6003]
## Current behavior

If I want to implment jwt authentication, I have to config jwt secret or rsa keys twice. The one is in
```ts
    JwtModule.register({
      secret: jwtConstants.secret,
      signOptions: { expiresIn: '60s' },
    })
```
the other is in 
```ts
@Injectable()
export class JwtStrategyService extends PassportStrategy(Strategy) {
  constructor() {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      ignoreExpiration: false,
      secretOrKey: jwtConstants.secret,
    });
  }

  async validate(payload: any) {
    return { userId: payload.sub, username: payload.username };
  }
}
```
It is 'repeat yourself', right?
if you comment out `secretOrKey: jwtConstants.secret`, it would cause error `TypeError: JwtStrategy requires a secret or key`

## Input Code

https://github.com/MaoScut/nest-jwt-code
clone this repository, run 
```bash
$ yarn
$ yarn run start
```
you can see the `TypeError: JwtStrategy requires a secret or key` error.

## Expected behavior

Just config jwt in `JwtModule.register`.
Acutally, I use `secretOrKeyProvider` to load asymmetric keys, so it is quiet cumbersome to config `secretOrKeyProvider` twice.

## Environment

<pre><code>
Nest version:7.5.1

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by jmcdo29** [comment]
The `JwtModule` and the `JwtStrategy` are two separate entities. One is for configuring the `jsonwebtoken` package (what the `@nestjs/jwt` package uses under the hood) and one is for `passport` (what `@nestjs/passport` uses under the hood). 

Side note: Dang Kamil, beat me by a minute 😸
