### ISSUE TITLE
Issue with mongoose populate

### ISSUE THREAD

**Issue by folivi** [nestjs/nest#6010]
## Current behavior
Calling populate returns an empty array. 
But removing the populate() method returns an array with the ids

## Input Code

```ts
//my schema

export const CrewSchema = new Schema(
  {
    _id: { type: String, default: shortid.generate },
    name: { type: String },
    description: { type: String },
    members: { type: [String], default: [], ref: 'Profile' },
  },
  {
    timestamps: true,
  },
);

//inside a service

this._crewModel.findOne({ _id })
  .populate('members', this._profileModel)
  .then(crew => console.log(crew));
```

## Expected behavior
The call should return the requested object and an embedded array of the referenced objects

## Environment

<pre><code>
Nest version: ^7.5.1

 
For Tooling issues:
- Node version: v14.15.0
- Platform:  Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by folivi** [comment]
Hi.
Got it but I thought is a bug?
