### ISSUE TITLE
Support AsyncLocalStorage for better flexibility

### ISSUE THREAD

**Issue by youngjoon-lee** [nestjs/nest#6012]
## Feature Request

[AsyncLocalStorage](https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage) can probably be useful for handling Authentication/Authorization and also for [DataLoader](https://github.com/krislefeber/nestjs-dataloader), especially in GraphQL use cases.

## Is your feature request related to a problem? Please describe.

Yes. 

The [JwtStrategy](https://docs.nestjs.com/security/authentication#implementing-passport-jwt) (called by `JwtAuthGuard`) generally sets a `user` object to the `ctx.getContext().req.user`.
Then, we extract it using the [@CurrentUser()](https://docs.nestjs.com/security/authentication#graphql) decorator.
But, that decorator only can be accessible in Controller/Resolver layers.

For authorizations, the `user` object is necessary.
And, many authorization logic needs to be done in Service/Repository layers.
That is, the `user` object is not accessible for authorizations.

## Describe the solution you'd like

I would like to suggest to adopt [AsyncLocalStorage](https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage) for these kinds of request-scoped stuff, instead of touching `ExecutionContext` which can only be accessible in Controller/Resolver layers.

I've already tried to do it in my project which is based on NestJS + GraphQL.
But, it would be great if NestJS provides it as the first-class citizen for less boilerplate, test-ability and flexibility.

Here is what I've implemented.
First, I created a Middleware which initialize AsyncLocalStorage for each incoming request.
```ts
export class RequestContext {    // <--- any class you want
  user: User;
}

export function asyncLocalStorageMiddleware(req: Request, res: Response, next: NextFunction): void {
  asyncLocalStorage.enterWith(new RequestContext());
  next();
}
```
```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.use(asyncLocalStorageMiddleware);
  await app.listen(3000);
}

bootstrap();
```

Then, I stored an `user` object to AsyncLocalStorage, in the `JwtStrategy`.
```ts
@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
  ...
  async validate(request: Request, payload: JwtPayload): Promise<User> {
    const user = this.userSvc.getById(payload.sub);
    asyncLocalStorage.getStore().user = user;   // <--- HERE
    return user;
  }
}
```
For authorization, I could extract the `user` object from ALS easily at any layer.
```ts
@EntityRepository(Schedule)
export class ScheduleRepository extends Repository<Schedule> {
  async getSchedule(id: string): Promise<Schedule> {
    const schedule = this.repo.getById(id);
    const user = asyncLocalStorage.getStore().user;
    if (user.id !== schedule.userId) {
        throw new ForbiddenException();
    }
    return schedule;
  }
}
```

This works quite well.
But, I hope I can use ALS without the explicit middleware that I've made, because middlewares aren't executed for [GraphQL Subscription](https://docs.nestjs.com/graphql/subscriptions) operations.

Also, it makes unit-tests difficult. For example, the middleware isn't executed at the following unit test code. So, any subsequent functions cannot access ALS.
```ts
describe('ScheduleService', () => {
  beforeAll(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [TestAppModule],
    }).compile();

    scheduleSvc = module.get<ScheduleService>(ScheduleService);
  });
```

## Teachability, Documentation, Adoption, Migration Strategy

It would be great if NestJS initializes a ALS per request and uses it for `@nestjs/auth` (future feature).

## What is the motivation / use case for changing the behavior?

Authorization:
https://www.osohq.com/
https://github.com/osohq/oso-nest-doc-mgmt

ALS Performance:
https://twitter.com/andreypechkurov/status/1234189388436967426

Other implementations:
https://mikro-orm.io/docs/next/usage-with-nestjs#using-asynclocalstorage-for-request-context

**Comment by youngjoon-lee** [comment]
I've also implemented `RequestContextModule` that uses AsyncLocalStorage internally. 
https://github.com/medibloc/nestjs-request-context/pull/1
Please see my implementation if you think that this ALS approach is reasonable.

**Comment by kamilmysliwiec** [comment]
You can implement the per-request local storage with request-scoped providers https://docs.nestjs.com/fundamentals/injection-scopes. We're also tracking the `async_hooks` integration here:  https://github.com/nestjs/nest/pull/1407 but since it's still very experimental, we don't plan to add it to the package in the foreseeable future.

**Comment by steinroe** [comment]
Hi,

I cannot use request-scoped providers since the passport module is global by default. I was able to set it up using AsyncLocalStorage, but the middleware is not applied in e2e tests as you already mentioned @youngjoon-lee. Can this be solved somehow?

**Comment by james4388** [comment]
@kamilmysliwiec I have an application like this: Request - >controller -> service -> client -> HTTPClient (axios) -> another service
If I use request-scoped look like it can only implement for controller layer, how to pass down to axios so it can use that to call another service? This is tracing.
Thanks
