### ISSUE TITLE
GRPC method name that ends with numbers and letters fails reports "not provided"

### ISSUE THREAD

**Issue by iangregsondev** [nestjs/nest#6017]
## Current behavior

take the following proto

```
  rpc GetLargestBlocksSizes24 (GetLargestBlocksSizes24hRequest) returns (GetLargestBlocksSizes24hResponse) {}
  rpc GetLargestBlocksSizes48h (GetLargestBlocksSizes24hRequest) returns (GetLargestBlocksSizes24hResponse) {}
  rpc GetLargestBlocksSizes48hours (GetLargestBlocksSizes24hRequest) returns (GetLargestBlocksSizes24hResponse) {}
```
 and (adding 1 as they are all the same)

```
  @GrpcMethod("MainNetDataService", "getLargestBlocksSizes123hours")
  getLargestBlocksSizes123hours(
    request: GetLargestBlocksSizesRequest,
    metadata?: Metadata
  ): Promise<GetLargestBlocksSizesResponse> | Observable<GetLargestBlocksSizesResponse> | GetLargestBlocksSizesResponse {
    throw new Error("Method not implemented.")
  }
```

If method ends in a number ONLY then it doesn't complain but if it ends with a number and then words it fails.

I couldn't find any info about it being invalid. I have done a lot of tests and every time I can reproduce it just by using the ending of the method name with number and letter

here is the error

```
Method handler GetLargestBlocksSizes24h for /main_net_data_service.MainNetDataService/GetLargestBlocksSizes24h expected but not provided
Method handler GetLargestBlocksSizes48h for /main_net_data_service.MainNetDataService/GetLargestBlocksSizes48h expected but not provided
Method handler GetLargestBlocksSizes48hours for /main_net_data_service.MainNetDataService/GetLargestBlocksSizes48hours expected but not provided
Method handler GetLargestBlocksSizes123hours for /main_net_data_service.MainNetDataService/GetLargestBlocksSizes123hours expected but not provided
```

Am I missing something ?

## Expected behavior
To be able to end method names with numbers and letters

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: 14
- Platform: Mac Big sur

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by iangregsondev** [comment]
Sure here you go

https://github.com/iangregsondev/grpc-numeric-method-name-problem

you will notice, just run the dev script   start:dev

you will notice 5 errors

```
Method handler GetLargestBlocksSizes24h for /main_net_data_service.MainNetDataService/GetLargestBlocksSizes24h expected but not provided
Method handler GetLargestBlocksSizes48h for /main_net_data_service.MainNetDataService/GetLargestBlocksSizes48h expected but not provided
Method handler GetLargestBlocksSizes48hours for /main_net_data_service.MainNetDataService/GetLargestBlocksSizes48hours expected but not provided
Method handler GetLargestBlocksSizes123hours for /main_net_data_service.MainNetDataService/GetLargestBlocksSizes123hours expected but not provided
Method handler Get123hours for /main_net_data_service.MainNetDataService/Get123hours expected but not provided
```

you willl notice that the method names that don't end with a numeric and a word - work perfectly.

I didn't add any logic here but the error message outlines it

check out "main-net-controller.ts"

I already copied the proto file into the dist folder and pushed it to github so its ready for testing.

**Comment by kamilmysliwiec** [comment]
This is the default behavior of the protocol buffers loader https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/java/java_helpers.cc#L161 (regardless of the programming language). To work around this, always make sure to capitalize the character that follows the number, for example, change:

```typescript
@GrpcMethod('MainNetDataService', 'getLargestBlocksSizes48h')
```
to:

```typescript
@GrpcMethod('MainNetDataService', 'getLargestBlocksSizes48H')
```
