### ISSUE TITLE
Update sample/02-gateways to support latest socket.io-redis

### ISSUE THREAD

**Issue by nfedyashev** [nestjs/nest#6019]
## Current behavior
sample/02-gateways doesn't seem to work against latest redis-io.adapter npm version.

## Input Code

```
src/adapters/redis-io.adapter.ts:5:22 - error TS2349: This expression is not callable.
  Type 'typeof import("/home/nikita/Projects/app-nestjs/node_modules/socket.io-redis/dist/index")' has no call signatures.

5 const redisAdapter = redisIoAdapter({ host: 'localhost', port: 6379 });
                       ~~~~~~~~~~~~~~
[8:03:32 PM] Found 1 error. Watching for file changes.
```

and

vanilla example from https://github.com/nestjs/nest/tree/master/sample/02-gateways

## Possible Solution
https://github.com/socketio/socket.io-redis#typescript 
(not verified yet)

## Environment

<pre><code>
Nest version: 7.6.4

socket.io-redis: 6.0.1
</code></pre>

**Comment by jmcdo29** [comment]
Socket.io-redis >6 uses socket.io version 3 and greater. Nest does not yet support version 3 of Socket.IO, and we have an open issue tracking that. #5676
