### ISSUE TITLE
libs if one's name is other's prefix will fail tests

### ISSUE THREAD

**Issue by Diluka** [nestjs/nest#6020]
## Bug Report

1. use nest cli create 2 empty libs: `demo` and `demo1`
2. import the 2 libs in `AppModule`

## Current behavior

- npm start (⭕ )
- npm run test:e2e (❌ )

## Input Code

https://codesandbox.io/s/nestjs-libs-name-issue-03lv9

## Expected behavior

test with no errors

## Possible Solution

rename `demo` to `demo1` or any other names. just need to change the folder name and mapper configs. it's nothing to do with the code.

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Can you convert the codesanbox to a git repo that can be ran locally?

**Comment by kamilmysliwiec** [comment]
The codesandbox project you've shared works fine. I just tested on a sample project and it works properly too.

**Comment by Diluka** [comment]
```
sandbox@sse-sandbox-03lv9:/sandbox$ npm run test:e2e

> nestjs-libs-name-issue@1.0.0 test:e2e /sandbox
> jest --config ./test/jest-e2e.json

 FAIL  test/app.e2e-spec.ts (5.162 s)
  AppController (e2e)
    ✕ / (GET) (1 ms)

  ● AppController (e2e) › / (GET)

    Nest cannot create the AppModule instance.
    The module at index [1] of the AppModule "imports" array is undefined.

    Potential causes:
    - A circular dependency between modules. Use forwardRef() to avoid it. Read more: https://docs.nestjs.com/fundamentals/circular-dependency
    - The module at index [1] is of type "undefined". Check your import statements and the type of the module.

    Scope [RootTestModule]

      at DependenciesScanner.scanForModules (../node_modules/@nestjs/core/scanner.js:45:23)

  ● AppController (e2e) › / (GET)

    TypeError: Cannot read property 'getHttpServer' of undefined

      17 |
      18 |   it('/ (GET)', () => {
    > 19 |     return request(app.getHttpServer())
         |                        ^
      20 |       .get('/')
      21 |       .expect(200)
      22 |       .expect('Hello World!');

      at Object.it (app.e2e-spec.ts:19:24)

  console.log
    [Function: DemoModule] undefined

      at Object.<anonymous> (../src/app.module.ts:7:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.406 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nestjs-libs-name-issue@1.0.0 test:e2e: `jest --config ./test/jest-e2e.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nestjs-libs-name-issue@1.0.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additionallogging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sandbox/.npm/_logs/2020-12-28T08_50_20_963Z-debug.log
```

**Comment by Diluka** [comment]
> The codesandbox project you've shared works fine. I just tested on a sample project and it works properly too.

@kamilmysliwiec do you really run `npm run test:e2e` on the sandbox? I paste my result in previous comment

**Comment by kamilmysliwiec** [comment]
I can't reproduce your issue locally on a clean setup which means this is very likely related to the codesandbox itself. Please, share a **Github repository that reproduces your issue**.

**Comment by Diluka** [comment]
@kamilmysliwiec https://github.com/Diluka/nestjs-lib-name-issue
