### ISSUE TITLE
Ability to convert entire app into a single binary like Golang

### ISSUE THREAD

**Issue by Nikhiladiga** [nestjs/nest#6023]
This is the one of the main things that is stopping JavaScript from taking over the embedded systems development. The ability to hide source code and also to eliminate the use of node_modules in the end. Inspiration taken from golang which compiles into one binary that is not dependent on anything except OS.

**Comment by jmcdo29** [comment]
This is less a Nest thing, and more a Node thing in general. You _could_ work on getting a `webpack` configuration to bundle all thee node_modules together (like is done for the frontend), but that comes with challenges of ensuring that you have packages that   don't have `node-gyp` or `C++` type of dependencies (like database drivers or hashing packages like `bcrypt`  or `argon2`). This has generally been discussed before, [and you can read more on that here](https://github.com/nestjs/nest/issues/1706)
