### ISSUE TITLE
WebSocketGateway + MaxListenerExceededWarning with gateway options

### ISSUE THREAD

**Issue by piscis** [nestjs/nest#6026]
## Current behavior
We're currently have multiple modules implementing websocket gateways. All of the gateways using the exact same configuration (namespace, path, transports e.g.). The Only difference is the business logic inside of the particular gateway for its module.

How ever we discovered that having 6 or more gateways a cross multiple modules will trigger a memory leak warning if you omit the port and use custom configuration.

```bash
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```
How every this is not the case if we omit the gateways options and just instanziate the gateways with its default config

## Input Code

This is how we instantiate the gateway loading to the warning
```ts
@UseFilters(new WsExceptionsFilter())
@Injectable()
@WebSocketGateway({
  path: '/api/bla/blub',
  serveClient: false,
  namespace: '/foobar,
  transports: ['websockets'],
})
export class GatewayA
  implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect {
  @WebSocketServer() server: Server;
....
```

If we instantiate all of our gateways like this:

```ts
@UseFilters(new WsExceptionsFilter())
@Injectable()
@WebSocketGateway()
export class GatewayA
  implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect {
  @WebSocketServer() server: Server;
....
```

We have no warnings at all. But we have no way to control which transports are available and what namespace it should use.

## Expected behavior
It should not trigger a memory leak listener warning

## Possible Solution
current workaround is to not specify any options for the gateway but its not a solution.

## Environment

<pre><code>
Nest version: 7.6.4

For Tooling issues:
- Node version: 12.18.3
- Platform:  Mac + Linux

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by genadis** [comment]
I believe there is general issue, when using multiple gateways.
For each gateways [bindClientConnect](https://github.com/nestjs/nest/blob/72a88d5e76d940cf5b7e962d16dcfa999e283a8f/packages/websockets/adapters/ws-adapter.ts#L28) and [bindMessageHandlers](https://github.com/nestjs/nest/blob/72a88d5e76d940cf5b7e962d16dcfa999e283a8f/packages/platform-socket.io/adapters/io-adapter.ts#L34) is called. Each one of them uses `socket.on()` (`fromEvent` in case of `bindMessageHandlers`, but essentially the same).

Socket.io socket implementation extends Node EventEmitter which by default has a limit of  10 listeners. So this is the source of the warning.

To solve the above we added `setMaxListeners()` to our [custom Adapter](https://docs.nestjs.com/websockets/adapter#advanced-custom-adapter) implementation:

```typescript
public bindClientConnect(server: Server, callback: (socket?: Socket) => void): void {
        server.on(CONNECTION_EVENT, (socket: Socket) => {
            socket.setMaxListeners(this.options.maxSocketListeners || 10);
            callback(socket);
        });
    }
```

`maxSocketListeners` is not a built in options, we extend the default options interface for that.

**Comment by Suvitruf** [comment]
> @kamilmysliwiec @jmcdo29 I believe there is general issue, when using multiple gateways. For each gateway [bindClientDisconnect](https://github.com/nestjs/nest/blob/72a88d5e76d940cf5b7e962d16dcfa999e283a8f/packages/websockets/adapters/ws-adapter.ts#L32) and [bindMessageHandlers](https://github.com/nestjs/nest/blob/72a88d5e76d940cf5b7e962d16dcfa999e283a8f/packages/platform-socket.io/adapters/io-adapter.ts#L34) is called. Each one of them uses `socket.on()` (`fromEvent` in case of `bindMessageHandlers`, but essentially the same).
> 
> Socket.io socket implementation extends Node EventEmitter which by default has a limit of 10 listeners. So this is the source of the warning.
> 
> To solve the above we added `setMaxListeners()` to our [custom Adapter](https://docs.nestjs.com/websockets/adapter#advanced-custom-adapter) implementation:

You can also do the same in one of you Gateways without creating adapter in `handleConnection` callback.

```
@WebSocketGateway(APP_CONFIG.serverWsPort, {
    pingTimeout: 10000,
    transports:  ['websocket'],
    allowEIO3:   true
})
export class WSGateway implements OnGatewayConnection {

    constructor() {
    }

    async handleConnection(client: Socket, ...args: any[]) {
        client.setMaxListeners(APP_CONFIG.maxSocketListeners || 20);
   }
}

```
