### ISSUE TITLE
Found Usage of Empty Functions

### ISSUE THREAD

**Issue by HarshCasper** [nestjs/nest#6027]
While browsing through the Code, I found the usage of this empty function: 

https://github.com/nestjs/nest/blob/bfc7bea887a80f7fd29776417c679c77b452709c/integration/scopes/src/request-chain/helper/helper.service.ts#L8

Can this be treated as an Issue or a PR raised for the same?

**Comment by jmcdo29** [comment]
That looks to be a function used for testing request scoped services, and isn't used in the final code base (it's in `integration` so it's used for tests). No need to worry about it
