### ISSUE TITLE
I got an empty object when loaded  Instance on constructor .

### ISSUE THREAD

**Issue by JayStevency** [nestjs/nest#6032]
## Bug Report

I hoped to inject an object of epcRepository  when loaded instance's partner service class. but I got an empty object like followings. plz help me.  

## Current behavior

[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] LocationModule dependencies initialized +1ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] EpcModule dependencies initialized +0ms
**[Nest] 33953   - 2020-12-28 17:19:30   Object:
{}
 +0ms**
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] OwnerModule dependencies initialized +1ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] XopModule dependencies initialized +0ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] PartnerModule dependencies initialized +0ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] MemberModule dependencies initialized +0ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 33953   - 2020-12-28 17:19:30   [InstanceLoader] TermsModule dependencies initialized +1ms
## Input Code

```ts
// epc.module.ts

import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Epc } from './entities';
import { EpcRepository, EpcRepositoryProvider } from './repositories';

@Module({
  imports: [
    TypeOrmModule.forFeature([Epc])
  ],
  providers: [EpcRepository, EpcRepositoryProvider],
  exports: [EpcRepository]
})
export class EpcModule { }

```

```ts
// partner.module.ts
import { forwardRef, Logger, Module } from '@nestjs/common';
import { PartnerService } from './partner.service';
import { PartnerResolver } from './partner.resolver';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Partner } from './entities';
import { PartnerRepository, PartnerRepositoryProvider } from './repositories';
import { MemberModule } from '../member/member.module';
import { AuthModule } from '@nrgx/auth/auth.module';
import { LocationModule } from '../location/location.module';
import { EpcModule } from '../epc/epc.module';
import { EpcRepository } from '../epc/repositories';

@Module({
  imports: [
    TypeOrmModule.forFeature([Partner]),
    EpcModule,
    MemberModule,
    LocationModule,
    forwardRef(() => AuthModule)
  ],
  providers: [
    PartnerService, 
    PartnerResolver, 
    PartnerRepository, 
    PartnerRepositoryProvider,
    EpcRepository,
  ]
})
export class PartnerModule {}

```

```ts
//partner.service.ts
import { forwardRef, HttpException, HttpStatus, Inject, Injectable, Logger } from '@nestjs/common';
import { AuthService } from '@nrgx/auth/auth.service';
import { Transactional } from 'typeorm-transactional-cls-hooked';
import { EpcRepository } from '../epc/repositories';
import { LocationRepository } from '../location/repositories';
import { MemberRepository } from '../member/repositories';
import { SignUpPartnerArgs } from './dto';
import { PartnerRepository } from './repositories';

@Injectable()
export class PartnerService {
  constructor(
    private partnerRepository: PartnerRepository,
    private memberRepository: MemberRepository,
    private epcRepository: EpcRepository,
    private locationRepository: LocationRepository,
    @Inject(forwardRef(() => AuthService)) private authService: AuthService
  ) {
    **Logger.log(this.epcRepository)**
  }
...
```
```ts
//epc.repository.ts
import { Injectable } from "@nestjs/common";
import { Connection, EntityRepository } from "typeorm";
import { BaseRepository } from "typeorm-transactional-cls-hooked";
import { Epc } from "../entities";

@EntityRepository(Epc)
@Injectable()
export class EpcRepository extends BaseRepository<Epc> {
  
} 

export const EpcRepositoryProvider = {
  provide: 'EpcRepository',
  useFactory: (connection: Connection) => connection.getCustomRepository(EpcRepository),
  inject: [Connection]
}
```

## Expected behavior

When the other right repository logging : 

[Nest] 35748   - 2020-12-28 17:28:09   [InstanceLoader] LocationModule dependencies initialized +1ms
[Nest] 35748   - 2020-12-28 17:28:09   [InstanceLoader] EpcModule dependencies initialized +0ms
[Nest] 35748   - 2020-12-28 17:28:09   [ExceptionHandler] Converting circular structure to JSON
    --> starting at object with constructor 'EntityManager'
    |     property 'repositories' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Repository'
    --- property 'manager' closes the circle +1ms
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'EntityManager'
    |     property 'repositories' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Repository'
    --- property 'manager' closes the circle
    at JSON.stringify (<anonymous>)
....

## Environment

<pre><code>
Nest version: 7.1.5

 
For Tooling issues:
- Node version: 12.16.3  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
