### ISSUE TITLE
Build problem using resolveJsonModule

### ISSUE THREAD

**Issue by vincenzoSalernoEos** [nestjs/nest#6045]
### Current behavior
If I put a json file outside the src folder and I want to use it inside a typescript file with _resolveJsonModule_ flag, the build produce a dist folder without the main.js, so if I run the command `npm run start:prod` it doesn't works.

### Software versions
```cmd
λ node -v
v14.15.3

λ npm -v
6.14.9

λ nest -v
7.5.4
```

### Step to reproduce

1. Create new project using `nest new <projectName>` using npm
2. Inside <projectName> folder create a new json file called _abc.json_ with a json content:
```json
{"abc":"def"}
```
3. Inside src folder, edit the file _app.service.ts_ adding this import line before class declaration:
```ts
import * as foo from 'abc.json';
```
4. Edit the file _tsconfig.json_ adding the line `"resolveJsonModule": true,` inside _compilerOptions_ block
5. Inside <projectName> folder run command `npm run build`
6. Inside <projectName> folder run command `npm run start:prod`

**Comment by jmcdo29** [comment]
This is how Typescript works and is not specific to nest. You can change your `start:prod` script to point to `dist/src/main`
