### ISSUE TITLE
Middleware in v5 is deprecated

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#605]
Hi,
The Middleware annotation is deprecated in V5 (v5-beta3). I looked through the v5 documentation and couldn't find anything that indicates what annotation should be used for middlewares.

Also the `ExpressMiddleware` is not available via `'@nestjs/common'`. 

Here is a screenshot:
![alt text](https://preview.ibb.co/k6beUH/bug.png "Errors")

Here is the link to the documentation:
https://docs.nestjs.com/middlewares

**Comment by shekohex** [comment]
You are looking at wrong documation, this docs is for `v4.x` 
go here for `v5` : https://docs.nestjs.com/v5/middlewares
 
I think this will solve your issue :grinning:

**Comment by cojack** [comment]
@shekohex link doesn't work, can you improve it a bit?

**Comment by vlio20** [comment]
@shekohex , here you go:
https://docs.nestjs.com/v5/middlewares
