### ISSUE TITLE
MessagePattern is throwing a validationError

### ISSUE THREAD

**Issue by Yassen-Higazi** [nestjs/nest#6053]
## Current behavior
I'm trying to connect two microservices  using regular TCP transport and it is throwing this error
ValidationError: Invalid JoiPipeOptions: "pattern" is not allowed
 
Error details
```json
details: [
    {
      "message": "'pattern' is not allowed",
      "path": ["Array"],
      "type": "object.unknown",
      "context": ["Object"]
    }
  ]
```

Service A Controller
```ts
@Controller('/')
export class TestController {

  @MessagePattern({ cmd: 'MyPattern' })
  async test(data: any) {
    return 'result'
  }
}
```
Service B Client call
```ts
// service B
const result = await this.serviceAClient
      .send({ cmd: 'MyPattern'}, data)
      .toPromise();
```

## Expected behavior
to be able to call the other service

## Environment

Nest version: 7.5.4
 
For Tooling issues:
- Node version: 14.15.1
- Platform:  Linux

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by SoyketHM** [comment]
Can anyone fix this issue?
I am having the same issue!

**Comment by jmcdo29** [comment]
> Can anyone fix this issue?
> I am having the same issue!
> @jmcdo29 

Can you provide a minimum reproduction, as was asked for before the issue was originally closed? Can't really do much without it

**Comment by Yassen-Higazi** [comment]
@SoyketHM In my case the problem wasn't in nestjs I was using [nestjs-joi](https://www.npmjs.com/package/nestjs-joi) and i removed it and everything worked fine

**Comment by alfianriv** [comment]
> @SoyketHM In my case the problem wasn't in nestjs I was using [nestjs-joi](https://www.npmjs.com/package/nestjs-joi) and i removed it and everything worked fine

Do you know how to solve without removing [nestjs-joi](https://www.npmjs.com/package/nestjs-joi) ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
