### ISSUE TITLE
swagger plugin cat not  handle @Body() if is a complex structure

### ISSUE THREAD

**Issue by lxiaoixi** [nestjs/nest#6057]
## Current behavior

swagger cat not  handle @Body() if is a complex structure， but I find it can handle the same structure in response, can it also support in @Body()?

## Input Code

Here is my code. 

```ts
controller.ts

@Post('lessons')
async getLessons(@Body() body: LessonDto[]): Promise<LessonRes[]> {
    return null;
}

export class LessonDto {
    name: string;
}

export class LessonRes {
    
    state: number;
    version: string;
    url: string;
}

```

## Expected behavior

the `@Body()` structure is `LessonDto[]`, the response is `LessonRes[]`, but in swagger-ui , the body is 
[
  "string"
]
it cat get the LessonDto attribute, but response LessonRes[] may can do it

the swagger json now is 
```
"/lessons": {
	"post": {
		"operationId": "PackageController_postLesson1LessonId",
		"summary": "interface",
		"requestBody": {
			"required": true,
			"content": {
				"application/json": {
					"schema": {
						"type": "array",
						"items": {
							"type": "string"
						}
					}
				}
			}
		},
		"responses": {
			"201": {
				"description": "",
				"content": {
					"application/json": {
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/components/schemas/LessonRes"
							}
						}
					}
				}
			}
		}
	}
}
```

and I expect is 
```
"/lessons": {
	"post": {
		"operationId": "PackageController_postLesson1LessonId",
		"summary": "interface",
		"requestBody": {
			"required": true,
			"content": {
				"application/json": {
					"schema": {
						"type": "array",
						"items": {
								"$ref": "#/components/schemas/LessonDto"
						}
					}
				}
			}
		},
		"responses": {
			"201": {
				"description": "",
				"content": {
					"application/json": {
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/components/schemas/LessonRes"
							}
						}
					}
				}
			}
		}
	}
}

```

for 

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Arrays are technically considered generics by Typescript, so you need to [follow the documentation on dealing with generics](https://docs.nestjs.com/openapi/types-and-parameters#generics-and-interfaces) to make it show up correctly in swagger.

Please use our [Discord](https://discord.gg/nestjs) for Support as we are using GitHub for Bug Reports, Feature Requests, and Regressions.

**Comment by egarkavy** [comment]
It worked, thanks
