### ISSUE TITLE
is there a solution to create a http gateaway which can accept bundle requests

### ISSUE THREAD

**Issue by minzojian** [nestjs/nest#6061]
I was thinking to package some request from client into one single request, then remap into seprated requests to different controlers to  process, then after all, gether the result into one single response and return to client.

the purpose to do so is try to reduce the request number, that would some kind of optimize works.

so is there some clue to make that happen?
so far i can image is to do some work in a Interceptors which can process the request and the response in the same place.

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel for Support. We are using GitHub to discuss Bug Reports, Features requests, and Regressions.
