### ISSUE TITLE
`envFilePath` in `ConfigModule.forRoot` function won't evaluate `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by jameskentTX** [nestjs/nest#6064]
I have in app.module such fragment of code:

```typescript
@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: `env/${(process.env.NODE_ENV || 'local').toLowerCase()}.env`,
      validationSchema: Joi.object({
        TYPEORM_HOST: Joi.required(),
        TYPEORM_PORT: Joi.number().default(5432),
      }),
    })
]})
```

This code doesn't work. Env variables are unknown.

If I change code to
```typescript
envFilePath: `env/${('development' || 'local').toLowerCase()}.env`,
```
everything is working fine.

But if I remove file extension `.dev` code won't work again.

So there are in fact two errors.

**Comment by jmcdo29** [comment]
Can you provide a minimum reproduction?

**Comment by jameskentTX** [comment]
Just move `.env` file to `env` directory, change name to `development.env` and write in that file `NODE_ENV=development`
Then try to read `process.env.NODE_ENV` in `envFilePath`.

**Comment by jmcdo29** [comment]
A minimum reproduction that is clonable. A Git repo

**Comment by jameskentTX** [comment]
not working: envFilePath: `env/${process.env.NODE_ENV}.env`,
working: envFilePath: `env/${'development'}.env`,
not working: envFilePath: `env/${'development'}`,

**Comment by jmcdo29** [comment]
For the third and last time, [please provide a minimum reproduction](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction). It's common courtesy in open source development that if you find a bug, you provide a reproduction of it.

**Comment by jameskentTX** [comment]
I don't know how to do it. It would take me too much time.

But problem is very very simple to reproduce. ConfigModule.forRoot function in app.module.ts has no access to process.env.NODE_ENV variable. It means ConfigModule.forRoot function doesn't read `.env` file, or read it too late.

You may close issue if you want, I will simply use string 'development' instead of ${process.env.NODE_ENV} in envFilePath.

**Comment by jmcdo29** [comment]
> it would take too much time... Very simple to reproduce

Which is it? If it would take too much time, it's not simple to reproduce. If it's simple to reproduce it won't take much time.

**Comment by kamilmysliwiec** [comment]
This isn't a bug. 

```typescript
ConfigModule.forRoot({
   envFilePath: `env/${(process.env.NODE_ENV || 'local').toLowerCase()}.env`,
   validationSchema: Joi.object({
      TYPEORM_HOST: Joi.required(),
      TYPEORM_PORT: Joi.number().default(5432),
   }),
})
```
Since `ConfigModule` is responsible for loading `process.env` variables, they are simply unavailable just yet when you try to use them to configure the module itself.
