### ISSUE TITLE
Why do I have to declare a class as a Provider twice?

### ISSUE THREAD

**Issue by ericmorand** [nestjs/nest#6081]
I'm reading the documentation of Nest.js and am puzzled at two contradictory information. When declaring a module, I have to explicitely tell what providers this module exposes:

https://docs.nestjs.com/modules#modules

> providers | the providers that will be instantiated by the Nest injector and that may be shared at least across this module

Then, when reading the Providers documentation, it is said that for a class to be considered as a Provider, it must have the `@Injectable` decorator applied:

https://docs.nestjs.com/providers#services

> The @Injectable() decorator attaches metadata, which tells Nest that this class is a Nest provider.

From my understanding, I have to tell **twice** to the framework that my class is a Provider: once in the Provider class definition itself, using the `@Injectable` decorator, and once when I declare my Module class, using the `@Module()` decorator.

Wouldn't declaring a class as a Provider enough by just using the `@Module` decorator? If I declare a class as a Provider here, the framework can assume that it _is_ a Provider, right?

What happens if I declare a class as a Provider, using the `@Module` decorator, but don't apply the `@Injectable` decorator to the said class?

### My conceptual concerns

Let's say that it is possible to use a class as a Provider without having to attach it to a Module via the `@Module` decorator. It renders possible to create Module-less providers (it's not necessarily a bad thing, I don't have an opinion on that). But if it is possible to create Module-less providers, what is the point of having Modules declare their providers using the `@Module` decorator?

Now, let's say that it is not possible to use a class as a Provider without having to attach it to a Module via the `@Module` decorator. It creates a strong dependency between Providers and Modules where only Modules can declare the existence of Providers (it's not necessarily a bad thing, I don't have an opinion on that either). But it makes the `@Injectable` decorator redundant and useless when declaring a Provider class: since it is not possible to declare a Provider outside of a Module, why would we need to declare the Provider class as Injectable? It _is_ injectable since it is a Provider, and the framework can totally add the `@Injectable` decorator itself to any class provided in the `providers` array of the `@Module` decorator.

I'm certainly missing something here, though.

**Comment by magicmatatjahu** [comment]
Hi! `@Injectable` (you can use another decorator on class, important is that you attached some decorator to class) is used due to how reflection works in TS. Using class decorators you tell TS (with enabled `experimentalDecorators`, `emitDecoratorMetadata` flags in `tsconfig.json`): please emits reflection metadata of class. By defining class like:

```ts
@Injectable()
class SomeClass {
  constructor(
    private parameter: TypeA,
    private parameter: TypeB,
  ) {}
}
``` 

TS emits metadata based on types declared in constructor -> `[TypeA, TypeB]`. NestJS by this metadata knows which types must inject in appropriate provider. Without class decorator you have to declare types manually using `@Inject()` decorator like:

```ts
class SomeClass {
  constructor(
    @Inject() private parameter: TypeA,
    @Inject() private parameter: TypeB, // @Inject() infer type from property
  ) {}
}
```

or using custom factory provider:

```ts
{
  provide: SomeClass,
  useFactory: (...args) => new SomeClass(args),
  inject: [TypeA, TypeB],
}
```

Maybe this is redundant work, but it helps in reflection and I don;t know any easier method to read types from constructor. I don't know code base of Nest, but you should be able to attach also `@Module` decorator to your class, then add this class to `providers` array and used in other providers like normal `@Injectable` class :) 

Using `@Injectable` in Nest allows you also to specify `scope` of class. Without this you must do something like:

```ts
{
  provide: SomeClass,
  useClass: SomeClass,
  scope: {SCOPE}
}
```

Another standalone DI system like `tsyringe`, `typedi`, `inversifyJS` works similar and also you must attach some decorator to class to avoid manually defining types from the constructor.

**Comment by smolinari** [comment]
I get the question or the reason for asking it. I think it boils down to a couple of things (as also explained [here}(https://docs.nestjs.com/fundamentals/custom-providers)). 

1. With the `module.ts` file, we (and Nest) have a general and consistent place to look for what should be included in and exported out of a module. 
2. The `module.ts` file is a declarative way to set up the DI container. Nest needs this "config" to be told what to build during app bootup. It uses this info, plus the dependencies of services to build the dependency graph.

So, I think of it this way. The `Injectable` decorator is to flag the class as "DI capable" and to say it needs to also be analysed for dependencies itself. The `module`decorator is the method of registration for those DI capable classes. 

Scott

**Comment by ericmorand** [comment]
@smolinari 

> The module decorator is the method of registration for those DI capable classes.

So, the provider will be analysed because it is `@Injectable` whether it is declared by a module or not, right?

@kamilmysliwiec , I'm sorry but my question remains valid: there has been some suppositions here but no definitive answer. 

Why do I have to use both the `providers` parameter of the `@module` decorator _and_ the `@Injectable` decorator to declare a class as a Provider? Why don't Nest.js register any class passed to the `providers` parameter of the `@module` decorator as a Provider? What else could the classes passed as parameter here be?

**Comment by jmcdo29** [comment]
@ericmorand as @smolinari without the `@Injectable()` decorator, the metadata for the constructor will not be properly reflected, so Nest won't be able to instantiate the class as you intend it to be.

**Comment by ericmorand** [comment]
@jmcdo29 , I think I get it: `@Injectable` is not necessary for a class to be recognized as a Provider. It is necessary for a class to be recognized as, well, Injectable. It seems obvious when explained this way, but it is not what the documentation implies:

> The @Injectable() decorator attaches metadata, which tells Nest that this class is a Nest provider.

It's pretty clear here that the `@Injectable` decorator is used to tell Nest that a class is a Provider.

I understood your point after reading the Interceptors documentation:

https://docs.nestjs.com/interceptors

> An interceptor is a class annotated with the @Injectable() decorator.

It is not much clearer but when reading both pages, we understand that the `@Injectable` decorator is not used to declare a class as a Provider, neither to declare a class as a Provider. It is needed to declare it as an Injectable.

Actually, I think there should be a `@Provider` decorator and an `@Interceptor` decorator that should take care of boostrapping the class with the needed dependencies to transform it into a propor Provider or Interceptor. Namely here, by applying the `@Injectable` decorator.

**Comment by jmcdo29** [comment]
> Actually, I think there should be a `@Provider` decorator and an `@Interceptor` decorator that should take care of boostrapping the class with the needed dependencies to transform it into a propor Provider or Interceptor. Namely here, by applying the `@Injectable` decorator.

If this were the case, would `@Interceptor()` decorated classes still be allowed to be in the `providers` array (there are times where this is useful for any nest enhancer to do things like 

```ts
@Module({
  providers: [
    CustomInterceptor,
    {
      provide: APP_INTERCEPTOR,
      useExisting: CustomInterceptor,
    }
  ],
})
```

So that we can later mock the interceptor (or enhancer) without having to find the UUID attached to the `APP_INTERCEPTOR` (trust me, doing that isn't pretty, I have code for it though))

Also, would we still use the `@Module()` decorator to define what modules have access to what providers, or would you suggest doing away with it (which absolutely goes against what Nest believes with separation of concerns)

**Comment by ericmorand** [comment]
> If this were the case, would @Interceptor() decorated classes still be allowed to be in the providers array

I'd say yes, but would it still be easily possible?

> Also, would we still use the @Module() decorator to define what modules have access to what providers, or would you suggest doing away with it (which absolutely goes against what Nest believes with separation of concerns)

I would, definitely.

I have no concern with the current approach of the `@Module` decorator. It just seemed confusing that the `@Injectable` decorator was described as "used to tell Nest that a class is a Provider". I assume that updating the documentation to make things clearer would be enough here.

My proposal of having discrete decorators (`@Provider` and `@Interceptor`) that would in turn apply the `@Injectable` decorator under the hood was just another way to make things clearer adnd more semantically accurate. And arguably more future-proof in case at some point providers need for example a specific metadata that don't need to be shared by other injectables - but I don't have a thourough enough understanding of Nest to be sure that it makes sense.

What I understand now, thanks to your clarifications (i.e. providers are exposed solely by the `@Module` decorator and a class that needs to be a valid provider needs to be _at least_ an Injectable), is perfectly fine by me.

I'm still reading the documentation - like I always do before even writing a single line of code which explain why the wording is so important to me. I can't wait to actually test Nest.js for good.

**Comment by jmcdo29** [comment]
> I'm still reading the documentation - like I always do before even writing a single line of code which explain why the wording is so important to me.

Ah yeah, things get a little clearer as you start to play with the framework. If you have a specific idea of how the wording can be updated, we'd love to consider it. Our docs are open source and PRs are more than welcomed if it makes things easier for new users of the framework. For those of us on the core team or that have been using it for a while, sometimes it can be hard to look at the wording and think "Yeah, that may be a little confusing" so if we can make things clearer, let's do it.

**Comment by smolinari** [comment]
> What I understand now, thanks to your clarifications (i.e. providers are exposed solely by the @Module decorator and a class that needs to be a valid provider needs to be at least an Injectable), is perfectly fine by me.

Add to that the ability to "export" the providers. By that I mean, in the `@Module` decorator you also (have to) tell Nest that a provider should be available to other modules (via the export property). I'd rather have the control over what is in the DI Container/ how the dependency graph is built than have Nest make assertions via "special-case" decorators. 

At first, I too saw the module concept as verbose and superfluous, but I have now come to be accustomed to it and even like it, because it's the "point of control" for a whole module. I only need to look in that one place to see what is going on within that module and how it is "offered" to the rest of the app. With "special-case" decorators, I'd have to go searching for that logic among all the classes of the module or I'd need to know what my thinking was in the past (and other devs would need to learn/ know this too), so one could see the `@Module` decorator more like documentation for the module. WIth those advantages, control of the dependency graph and documentation-like support, I can overlook the verbosity easily and I am sure you will too, once you start working with Nest more. 😀  

Scott

**Comment by dmasterstempus** [comment]
As someone who likes to read the docs before diving in, I have to agree with @ericmorand 's points.  The documentation is _extremely_ misleading with regards to the `@Injectable` decorator.  It directly states several times that this decorator is fundamentally what differentiates a regular javascript class from that of a "Nest Provider" javascript class.

**Comment by jmcdo29** [comment]
What would you prefer the docs say? What would make it cleaner for newcomers to know what the `@Injectable()` is for? Without getting into the nitty-gritty of how decorators and emitDecoratorMetadata works, this is the cleanest solution I know of

**Comment by smolinari** [comment]
When I started working with TS and more importantly, started working with decorators, I had a small idea about what they were and why they were there from other languages (like Java). They provide type annotations and meta-programming data.  But I also [went and refreshed my memory on what TS decorators are all about](https://www.youtube.com/watch?v=R3xoMCjP3Tk) just to be sure my knowledge is still up-to-date. In a nutshell and in my own words, decorators are about "building metadata around the code". And, if you don't understand the process of that "building of metadata", you will always have issues with what is happening, when decorators are used. I think Nest's docs were written with the assumption the user understands the TS decorator process and that is what is being called out as an issue. Maybe the docs could make the user aware about learning what decorators are all about, before "digging in" to the NestJS docs?

Scott

**Comment by ericmorand** [comment]
@smolinari decorators are more than type annotation and metadata providers. They are basically mixins: functions that are called with the target of the decorator and can do whatever they want with that target: modify it,.validate it, compute a result from it... To illustrate this, NestJS not only uses them as a way to identify things but also to return things - like the `@Param` or `@Query` decorators. 

Anyway, `@Injectable` basically declares a class as "available for dependency injection". Strictly speaking, it can be applied to any class and guarantee that this class can be injected later by its token.

The issue I have with the documentation is that it says explcitely that `@Injectable` is used to declare providers. This is not true strictly speaking. You can use `@Injectable` on a class and never put that class as part of the `providers` or `exports` property of a module and it will never be available. Thus, for a class to be a provider, it needs to be present in one of these module properties. Being `@Injectable` is not enough.

**Comment by ericmorand** [comment]
I'm conducting some tests about the `@Injectable` decorator and they are interesting.

Consider the following sources:

> foo.provider.ts

```ts
export class FooProvider {
}
```

> foo.module.ts

```ts
import {FooModule} from "./foo.provider";
import {FooController} from "./foo.controller";

@Module({
    controllers: [FooController],
    providers: [FooProvider]
})
export class FooModule {
}
```

> foo.controller.ts

```ts
import {FooProvider} from "./foo.provider";

@Controller('foo)
export class FooController {
    constructor(@Inject(FooProvider) private readonly fooProvider: FooProvider) {
        console.warn(fooProvider); // log FooProvider {}
    }
}
```

As you can see, I didn't apply the `@Injectable` decorator to `FooProvider`. Still it is injected successfully in `FooController`. Most probably because it's declared as a provider in `FooModule`.

Now, consider the following sources:

> foo.provider.ts

```ts
@Injectable()
export class FooProvider {
}
```

> foo.module.ts

```ts
import {FooModule} from "./foo.provider";
import {FooController} from "./foo.controller";

@Module({
    controllers: [FooController],
    providers: []
})
export class FooModule {
}
```

> foo.controller.ts

```ts
import {FooProvider} from "./foo.provider";

@Controller('foo)
export class FooController {
    constructor(@Inject(FooProvider) private readonly fooProvider: FooProvider) {
        // throws an error because FooProvider is missing
    }
}
```

`FooController` constructor throws an error in that case.

It seems to mean that the `@Injectable` decorator is not needed to declare a provider. A provider is solely something that is declared as such by modules.

I may have missed something in my tests so feel free to correct me.

**Comment by ericmorand** [comment]
Actually, I think it is covered by the documentation:

https://docs.nestjs.com/fundamentals/custom-providers#custom-providers-1

It's made very clear that a class doesn't have to be `@Injectable` to be a provider. It just has to be declared as such by a module.

May the documentation need improving, I think it is to clarify what the `@Injectable` decorator really does.

**Comment by smolinari** [comment]
> decorators are more than type annotation and metadata providers. 

I said it's "meta-programming data", as in data that is used to generate meta-programming, which includes enhancing classes, methods, arguments, etc. 

About your deductions on @Injectable:
Please reread what I and @jmcdo29 have noted above:

> without the @Injectable() decorator, the metadata for the constructor will not be properly reflected, so Nest won't be able to instantiate the class as you intend it to be.

> Actually, I think it is covered by the documentation:

As I also noted above in my first sentence of my first reply. 

I think the docs do make it fairly clear, yet the docs still do assume the reader is "in-the-know" about what decorators do. 

The docs say this:

> In cats.service.ts, the @Injectable() decorator **_declares the CatsService class as a class that can be managed by the Nest IoC container_**. 

And in the end, the module and @Injectable team forms a convention. Follow that convention for the DI system of Nest to work and just be happy it works so well. 😀 

Scott

**Comment by kamilmysliwiec** [comment]
I think that this topic has already been exhausted so I gotta lock this issue. As @jmcdo29 suggested here https://github.com/nestjs/nest/issues/6081#issuecomment-756392341, our docs are open source and PRs are more than welcome so if you have any specific ideas of how the wording can be updated, we'd love to consider it!
