### ISSUE TITLE
ValidationPipe injection issue

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#609]
Hi,
I am trying to set a global validation pipe:
```
import {NestFactory} from '@nestjs/core';
import {AppModule} from './app/app.module';
import {ValidationPipe} from '@nestjs/common';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe());
  await app.listen(3000);
}
```

Here is how I am using it:
```
  @Post()
  @UsePipes(ValidationPipe)
  public createUser(@Body() createUserDto: CreateUserDto) {
    ...
  }
```

As you can see the `ValidationPipe` is imported from `'@nestjs/common'` but here is the error that I am getting: 
```
Error: Nest can't resolve dependencies of the ValidationPipe (?). Please verify whether [0] argument is available in the current context
```

I am on nest v5-beta4

**Comment by vlio20** [comment]
Using it by the following way works correctly:  
```
@Post()
  public createUser(@Body(new ValidationPipe()) createUserDto: CreateUserDto) {
    ...
  }
```

Without having it set globally:
```
app.useGlobalPipes(new ValidationPipe());
```

**Comment by vlio20** [comment]
I see.... 
thanks @kamilmysliwiec

**Comment by cloakedch** [comment]
According to https://docs.nestjs.com/pipes the following should work:

```
@Post()
@UsePipes(ValidationPipe)
async create(@Body() createCatDto: CreateCatDto) {
  this.catsService.create(createCatDto);
}
```

> The instance of  ValidationPipe has been created immedietely in-place. Another available way is to pass the class (not instance), leaving framework the instantiation responsibility and enabling dependency injection.


However, it throws:

> Nest can't resolve dependencies of the ValidationPipe (?). Please make sure that the argument at index [0] is available in the current context.

Any ideas?

**Comment by cloakedch** [comment]
Okay, I just manually checked. It works if one uses the ValidationPipe of the example, but it does not work if one is using the ValidationPipe from `@nestjs/common`. Is that on purpose? Could we make this one going to work as well?
