### ISSUE TITLE
please add Lucid ORM to Nest js

### ISSUE THREAD

**Issue by webafra** [nestjs/nest#6093]
hi .

Lucid is one of the best packages available that has a very large and simple structure.

Unfortunately, to use this package, you need to use the Adonis framework.
I do not want to use it.

I will write some examples of the code of this package, maybe you will agree with me:

sample relationship:
```
  @hasMany(() => Post)
  public posts: HasMany<typeof Post>
```

```
const posts = await user.related('posts').createMany([
  {
    title: 'test',
    body: 'Lorem Ipsum is simply dummy text'
  },
  {
    title: 'NodeJS 101',
    body: 'Lorem Ipsum is simply dummy text'
  }
])
```

query on relationship:
```
// ex1: get a user with all published post ( eager Loading )

User.query().preload('posts', (query) => {
  query.where('published', true)
})


// You can also define the number of rows you expect the join query to return. For example: Select all users, who have enrolled for more than two courses.

const veterans = await User.query().has('courses', '>', 2)


you can get a user with relation count with one query ( automatic add relationname_count to output collection ) <3

const users = await User.query().withCount('posts')

```

I became very interested in this structure, how about you?

Please create this wonderful package (or similar package) for the lovely NestJs .

https://preview.adonisjs.com/guides/model-relations/introduction

thanks .

**Comment by jmcdo29** [comment]
You said it yourself, to use Lucid you must use Adonis. I've looked into this before, and it requires using their CLI, their core package, and their framework. This isn't something Nest can support, but it's not something supported in pure Node, you **must** use their framework to use **their** ORM. It's unfortunate, but it's the truth.

**Comment by webafra** [comment]
You are right and that is why I said:
Create a similar structure.

Unfortunately, this package is exclusive, but as far as I checked, I realized that the KnexJs package was used in the core of the system.

In version 10 of this package, the command line dependency has been removed.

https://github.com/adonisjs/lucid

**Comment by jmcdo29** [comment]
Nest is about making a Node Framework around architecture, not about another Node ORM. While it seems like a great thing to have, ORMs are tricky and require a lot of foresight and thought (check how TypeORM is doing at the moment). You can always use Knex as a query builder or you can check out MikroORM for another Node ORM, but Nest has no (current) plans to make a framework specific ORM

**Comment by webafra** [comment]
All frameworks have such a package, but unfortunately NestJs does not have this and the options that can be selected are not really suitable.

**Comment by jmcdo29** [comment]
Express, Fastify, Koa, Hapi, all of these are node frameworks without ORMs. It just so happens that NestJS is built on top of Express and fastify. 

[I'll leave you with this comment from Kamil about providing wrappers for node packages] (https://github.com/nestjs/nest/issues/4007#issuecomment-582779510)
