### ISSUE TITLE
@Nestjs/microservices, External TCP connection

### ISSUE THREAD

**Issue by Root-Control** [nestjs/nest#6106]
I am creating a centralized microservice which will receive commands from all possible places.
This microservice will be hosted on a dedicated server, that is why I want to connect externally and not internally as the documentation shows, I have tried host / port, but it does not work, is there something I missed?
```ts
imports: [
        MongooseModule.forFeature([{ name: User.name, schema: UserSchema }]),
        ClientsModule.register([{ name: 'MicroService', transport: Transport.TCP, options: { host: 'aws_host', port: 5000 } }])
    ],
```

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel for Support. We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

If you feel this is a bug report, please provide a [minimum reproduction](http://minimum-reproduction.wtf) that shows the bug in action.

**Comment by ctocto** [comment]
> 

Did you solve the problem?

**Comment by ctocto** [comment]
> I am creating a centralized microservice which will receive commands from all possible places. This microservice will be hosted on a dedicated server, that is why I want to connect externally and not internally as the documentation shows, I have tried host / port, but it does not work, is there something I missed?
> 
> ```ts
> imports: [
>         MongooseModule.forFeature([{ name: User.name, schema: UserSchema }]),
>         ClientsModule.register([{ name: 'MicroService', transport: Transport.TCP, options: { host: 'aws_host', port: 5000 } }])
>     ],
> ```


Did you solve the problem?
