### ISSUE TITLE
How to mock GqlExecutionContext using ts-mockito

### ISSUE THREAD

**Issue by esvm** [nestjs/nest#6112]
I have a custom Param Decorator in my code:
```
export const AuthUser = createParamDecorator((_, context: ExecutionContext):
  | AuthUserEntity
  | undefined => {
  const gqlCtx = GqlExecutionContext.create(context);

  return gqlCtx.getContext<AuthenticatedContext>().user;
});
```

This param decorator retrieves the `user` object injected in context during the Authentication process. I use it in my queries/mutations to have easy access to the user properties.

```
@Query(() => Wishlist)
  async wishlist(@AuthUser() user?: AuthUserEntity): Promise<Wishlist> {
    return new Wishlist(user?.id);
  }
```

During the test process, the authentication/authorization is turned off because some api limits with the api we use to authenticate. Since authentication is disabled, the user object is not injected into the context and the tests fails because this. So I need to mock the GqlExecutionContext to return a user in the getContext() method.

Someone han calp me with this? Is this the best place to ask?

I tried to mock doing the following:

```
const user = { id: authId };

const mockContext = mock<typeof GqlExecutionContext>(GqlExecutionContext);
  when(mockContext.create(anything())).thenReturn({
    getContext: () => ({
      user,
    }),
} as GqlExecutionContext);
```

But did not work

**Comment by Tony133** [comment]
Hi @esvm, If you have difficulty I recommend you to use the [discord](https://discord.com/invite/G7Qnnhy) nest channel for support, you can propose this issue there, the core team of nest uses GitHub for the following things: to track bug reports, feature requests and regressions .

**Comment by SalahAdDin** [comment]
@esvm did you get the answer?

**Comment by elbasan** [comment]
@frankfullstack @esvm anyone of you figured this out?

**Comment by SalahAdDin** [comment]
> @frankfullstack @esvm anyone of you figured this out?

I don't think so, I couldn't do it anyway.

**Comment by jmcdo29** [comment]
{I have an example in my ogma repo](https://github.com/jmcdo29/ogma/blob/main/packages/platform-graphql/test/graphql-interceptor.service.spec.ts#L9). Essentially you create an `ExecutionContext` object that has the `context` and `info` as `args[2]` and `args[3]` respectively. `args[0]` and `args[1]` can be empty objects. This will make `GqlExecutionContext.create()` work correctly.

**Comment by elbasan** [comment]
yeah I actually got it working, I found your repo and modified it a bit;

here's the solution:

```
import { ExecutionContext } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { RolesGuard } from './roles.guard';

const gqlMockFactory = (context: Record<string, any>): ExecutionContext =>
  ({
    getType: () => 'graphql',
    getHandler: () => 'query',
    getClass: () => 'Test Class',
    getArgs: () => [{}, {}, context, {}],
    getArgByIndex: () => ({} as any),
    switchToHttp: () => ({} as any),
    switchToRpc: () => ({} as any),
    switchToWs: () => ({} as any),
  } as any);

describe('RolesGuard', () => {
  let guard: RolesGuard;
  let reflector: Reflector;

  beforeAll(() => {
    reflector = new Reflector();
    guard = new RolesGuard(reflector);
  });

  it('should be defined', () => {
    expect(guard).toBeDefined();
  });

  it('should...', () => {
    reflector.getAllAndOverride = jest.fn().mockReturnValue(['ROLE_ADMIN']);
    const gqlContext = gqlMockFactory({
      req: {
        user: 'value',
      },
    });

    const canActivate = guard.canActivate(gqlContext);
    expect(canActivate).toBe(false);
  });
});

```

**Comment by SalahAdDin** [comment]
> yeah I actually got it working, I found your repo and modified it a bit;
> 
> here's the solution:
> 
> ```
> import { ExecutionContext } from '@nestjs/common';
> import { Reflector } from '@nestjs/core';
> import { RolesGuard } from './roles.guard';
> 
> const gqlMockFactory = (context: Record<string, any>): ExecutionContext =>
>   ({
>     getType: () => 'graphql',
>     getHandler: () => 'query',
>     getClass: () => 'Test Class',
>     getArgs: () => [{}, {}, context, {}],
>     getArgByIndex: () => ({} as any),
>     switchToHttp: () => ({} as any),
>     switchToRpc: () => ({} as any),
>     switchToWs: () => ({} as any),
>   } as any);
> 
> describe('RolesGuard', () => {
>   let guard: RolesGuard;
>   let reflector: Reflector;
> 
>   beforeAll(() => {
>     reflector = new Reflector();
>     guard = new RolesGuard(reflector);
>   });
> 
>   it('should be defined', () => {
>     expect(guard).toBeDefined();
>   });
> 
>   it('should...', () => {
>     reflector.getAllAndOverride = jest.fn().mockReturnValue(['ROLE_ADMIN']);
>     const gqlContext = gqlMockFactory({
>       req: {
>         user: 'value',
>       },
>     });
> 
>     const canActivate = guard.canActivate(gqlContext);
>     expect(canActivate).toBe(false);
>   });
> });
> ```

which repo?

**Comment by jmcdo29** [comment]
[This one](https://github.com/nestjs/nest/issues/6112#issuecomment-1197108287)
