### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: shared_utils_1.addLeadingSlash is not a function

### ISSUE THREAD

**Issue by faridg18** [nestjs/nest#6115]
## Bug Report
I am trying to give namespaces to my gateways.

like so:

`
@WebSocketGateway({ namespace: '/messages' })
`

After adding a namespace, I get the following error:

UnhandledPromiseRejectionWarning: TypeError: shared_utils_1.addLeadingSlash is not a function
(node:10226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

this only happens after then namespace option.

Does anyone have had a problem like this?

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by kamilmysliwiec** [comment]
@faridg18 make sure your `@nestjs/websockets`, `@nestjs/core`, and `@nestjs/common` are all in sync (same versions installed). This will fix your issue

**Comment by LukeeeeBennett** [comment]
I got this when `@nestjs/common` was not up to date with `@nestjs/core`, resolved by upgrading both to the same version

**Comment by faridg18** [comment]
Upgrading the versions for nest fixed it for me thanks
