### ISSUE TITLE
[microservices] Extend EventPattern to listen for event types within a specified topic with Kafka [type:feat]

### ISSUE THREAD

**Issue by fresto32** [nestjs/nest#6119]
## Feature Request
The current strategy of topic creation for kafka microservices does not follow best practice. For each `EventPattern` decorator in some Kafka microservice controller, a new topic is created in Kafka. This is contrary to best practices (see: [confluent article](https://www.confluent.io/blog/put-several-event-types-kafka-topic/)). Rather, I think it is argued that related event types should be grouped within a single topic. 

This is important primarily for ordering of events. Kafka maintains the ordering of messages only within a topic-partition, not between topics. This means that listeners of some topics could see them in a nonsensical order. Moreover, this can cause issues for Kafka users who want to use EventSourcing or save their Kafka topics for replayability / recovery. 

My suggestion is to allow a user to set the topic within an `EventPattern` and then the pattern matches an event type within that topic.

**Comment by kamilmysliwiec** [comment]
> Rather, I think it is argued that related event types should be grouped within a single topic.

We can't presume what event types should be grouped within a single topic so we must leave this decision to developers. For example, in case you want to group several events together (under one topic), you can register a single `EventPattern` and then, within a handler emit another **internal event** (appropriate for the specific, incoming event) using the `@nestjs/event-emitter` package https://docs.nestjs.com/techniques/events

**Comment by fresto32** [comment]
Thanks for getting back to me :smile: . You're right - I didn't realize this technique was possible. Thank you for documenting the `EventPattern` tactic to handle multiple events from a single topic.
