### ISSUE TITLE
[Feature] inject provider by NestFactory.create

### ISSUE THREAD

**Issue by s97712** [nestjs/nest#6123]
## Describe the solution you'd like

The current way of configuring the service is a bit inconvenient for me and I hope to support the following usage
```ts
  const app = await NestFactory.create(AppModule, {
    provider: [{
      provide: "AppConfig", 
      useValue: {
        mongodb: process.env["test"] ? "mongodb://localhost/test" : "mongodb://localhost/dev",
        redis: process.env["test"] ? "redis://localhost/0" : "redis://localhost/dev/1",
      }
    }]
  });
```

**Comment by kamilmysliwiec** [comment]
This is doable with dynamic modules (you can pass a dynamic module to the `#create` method). Example:

```typescript
NestFactory.create(AppModule.forRoot({ 
  ... configuration
}));
```

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
