### ISSUE TITLE
Official docs. Examples page broken.

### ISSUE THREAD

**Issue by ph55** [nestjs/nest#613]
1. Go to docs - https://docs.nestjs.com/
2. Got to FAQ -> Examples
![image](https://user-images.githubusercontent.com/1386622/39441103-8324e4be-4cb5-11e8-964a-8c6d393da00e.png)

Link broken:
https://github.com/nestjs/nest/tree/master/examples
![image](https://user-images.githubusercontent.com/1386622/39441127-9b588c84-4cb5-11e8-80ae-3bf16c9205a1.png)

**Comment by kamilmysliwiec** [comment]
Thanks @ph55. This issue is reported [here](https://github.com/nestjs/docs.nestjs.com/issues/68) already.
