### ISSUE TITLE
Update class-validator interface 

### ISSUE THREAD

**Issue by nean** [nestjs/nest#6131]
## Current behavior
The current class-validator ValidatoOptions is outdated and does not match the definition from the latest class-validator package.

## Possible Solution
Update the class-validation [validator-options.interface](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/external/validator-options.interface.ts) in nestjs/common to reflect upstream definition  [linked here](https://github.com/typestack/class-validator/blob/develop/src/validation/ValidatorOptions.ts)

## Environment

<pre><code>
Nest version: 7.5.1
 
For Tooling issues:
- Node version: v14.8.0
- Platform:  Mac
</code></pre>

**Comment by jmcdo29** [comment]
Would you like to create a PR to update these?

**Comment by Tony133** [comment]
to say that this issue can be closed as a pull was made for it.
