### ISSUE TITLE
Federation Documentation Seems Incomplete

### ISSUE THREAD

**Issue by mattsidjohn** [nestjs/nest#6137]
I'm trying to set up a schema first implementation of the documentation https://docs.nestjs.com/graphql/federation and I don't see in the User resolver the resolve field for posts, and I'm having a trouble returning the array of posts for a given user. Any help would be appreciated.

**Comment by Tony133** [comment]
@mattsidjohn  If you have difficulty in his discord channel

Maybe you can solve it like this:
```
@Resolver('User')
export class UserInPostsResolver {
  @ResolveField('posts')
  posts(@Parent() user: any) {
    return this.postsService.find({ where: { userId: user.id } })
  }
}
```
If you refer to this problem here https://github.com/nestjs/docs.nestjs.com/issues/1216

**Comment by mattsidjohn** [comment]
So weird - I have added the resolve field an the resolve reference however when i add the array on the type in the schema it says "Expected Iterable, but did not find one for field ...."

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
