### ISSUE TITLE
ExecutionContext.getModule()

### ISSUE THREAD

**Issue by samchon** [nestjs/nest#6138]
## Feature Request
I want you to add a new method `ExecutionContext.getModule()`.

The `ExecutionContext.getModule()` would return a type of the module who is related with the request.

## Is your feature request related to a problem? Please describe.
I often develop a http(s) server who encrypts all of the request & response body to make annoying someone who're trying to steal my data through the illegal crawling. Also, I'm using NestJS and adjusting those encryptions by creating a custom decorator function who configuring the encryption password in the `NestJS.Controller` level.

  - https://github.com/samchon/encrypted-nestjs/blob/465de05e0480f0d9071f5ab258b795ff27631350/src/EncryptedRoute.ts#L11-L18
  - https://github.com/samchon/encrypted-nestjs/blob/465de05e0480f0d9071f5ab258b795ff27631350/src/EncryptedRoute.ts#L66-L79

However, developing my encrypted server through the custom decorator function using the `NestJS.Controller`, I often hope that configuring the password in the `Module` level, it would be much better. However, I can't realize the hope because the `ExecutionContext` does not provide the `ExecutionContext.getModule()` method.

## Describe the solution you'd like
Without the `ExecutionContext.getModule()` method, I have to configure duplicated encryption password  in every controller classes. However, if you support the `ExecutionContext.getModule()` method, I can avoid those duplicated and annoying works.

```typescript
class Interceptor implements nest.NestInterceptor
{
    public intercept(ctx: nest.ExecutionContext, next: nest.CallHandler): Observable<any>
    {
        const param: IPassword | IPassword.Closure = Reflect.getMetadata("encryption:config", ctx.getModule());
        return next.handle().pipe(
            map(value => 
            {
                const content: string = JSON.stringify(value);
                const config: IPassword = (param instanceof Function)
                    ? param(content, true)
                    : param;
                return AesPkcs5.encode(content, config.key, config.iv);
            }),
            catchError(err =>
            {
                return throwError(err);
            }),
        );
    }
}
```

**Comment by kamilmysliwiec** [comment]
Conceptually, there's no such thing as module-level metadata in NestJS and so there are no plans to add the `getModule()` method to the `ExecutionContext`.

> I have to configure duplicated encryption password in every controller classes

One idea off top of my head would be to wrap the `@Module()` decorator into a new, custom decorator and inside it, iterate through the `controllers` array (before passing the object down to the original `@Module()` decorator), providing a dedicated `encryption:config` metadata for all controllers.

For other questions/ideas, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support).

**Comment by samchon** [comment]
Thanks for providing a good solution that creating a custom decorator wrapping the `@Module`.

However, if I want to design a `@Controller` class that can use different encryption password by wrapping the `@Controller` class in different `@Module` classes, how should I do?

**Comment by kamilmysliwiec** [comment]
> However, if I want to design a @Controller class that can use different encryption password by wrapping the @Controller class in different @Module classes, how should I do?

You can always register an interceptor on the class-level (for example, in your custom `@Module()` decorator) by iterating through the `controllers` array (instead of registering it globally). Then, make your interceptor dependent on a provider that will provide a different encryption password based on the host module.

For other questions/ideas, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support).
