### ISSUE TITLE
Ability to pipe Nest application startup logs to loggers like pino

### ISSUE THREAD

**Issue by ThisIsMissEm** [nestjs/nest#6142]
## Is your feature request related to a problem? Please describe.

Due to how `NestFactory.create` works, we are seeing non-json log lines in our logs, further more, these all include ansi escape codes, as Nest's default logger using coloured/pretty output.

I can supply a third argument to `NestFactory.create` of: ```{
      logger: new Logger(
        new PinoLogger({
          pinoHttp: { prettyPrint: process.env.NODE_ENV === 'development' },
        }),
        {},
      ),
    },```

Which does route the logs through pino, but it feels like a very messy hack. The only other option would be to disable all the initialization logs, which doesn't seem like a good idea.

## Describe the solution you'd like

One potential option would be to introduce a different `NestFactory` API which allows you to instantiate the application but not yet load it, and then have a `load()` method that actually allows you to load everything up. This would allow for (pseudocode) like the following:

```
const app = NestFactory.create(AppModule, new FastifyAdapter({}))

app.setLogger(someLogger)
await app.load()
await app.listener()
```

This would enable developers to correctly set the logger to their desired logger prior to application initialization.

## Teachability, Documentation, Adoption, Migration Strategy

n/a really?

## What is the motivation / use case for changing the behavior?

A desire to have all our application logs as JSON which simplifies ingesting them into log aggregation and analysis systems.

**Comment by jmcdo29** [comment]
Please search through some of our old issues on this. There is some discussion [here](https://github.com/nestjs/nest/issues/5353), [here](https://github.com/nestjs/nest/issues/5811), [here](https://github.com/nestjs/nest/issues/1828), [here](https://github.com/nestjs/nest/issues/2497), [here](https://github.com/nestjs/nest/issues/1043), [here](https://github.com/nestjs/nest/issues/507), and [here](https://github.com/nestjs/nest/issues/247)

**Comment by kamilmysliwiec** [comment]
Just fyi: I'm currently working on logger improvements and I hope I'll find a neat workaround for this issue (e.g., allow to buffer log messages instead of immediately printing them to stdout). I should be able to ship it in the next major release

**Comment by ThisIsMissEm** [comment]
You could also change the NestFactory logger to just be required to be an object with the logging methods, rather than an instance of a specific type of class.

**Comment by kamilmysliwiec** [comment]
@ThisIsMissEm it can be an object (for example, `logger: console.log` should work too)

**Comment by ThisIsMissEm** [comment]
> Emelia Smith it can be an object (for example, `logger: console.log` should work too)

hrm, I could've sworn I tried that and it didn't work.. will take a look again.
