### ISSUE TITLE
directives first code bug 

### ISSUE THREAD

**Issue by zexliu** [nestjs/nest#6149]
## I created a directive code first  like the link    <https://docs.nestjs.com/graphql/directives> 
it is work, but it don't show in SDL

**Comment by Tony133** [comment]
Hi @zexliu, if you have difficulty use the [discord](https://discord.com/invite/G7Qnnhy) channel for support

Then, if you think it's a bug, provide minimal production in a clonable git repository so the core team can evaluate your problem.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).

**Comment by ttyniwa** [comment]
answer is here.

https://github.com/nestjs/graphql/issues/1278#issuecomment-744287059
