### ISSUE TITLE
How can I avoid repeat rxjs `pipe` all the time or  config to go back  v4  style?  

### ISSUE THREAD

**Issue by janckerchen** [nestjs/nest#616]
` keep code small`  is  a  requirement for client side, not server side.

**Comment by kamilmysliwiec** [comment]
Hey @janckerchen,
`keep code small is a requirement for client side, not server side.`
Yes, but at the same time, we cannot be stuck with the old version of rxjs. I'm also not a huge fan of `.pipe()`. However, it seems that it is the only solution until this [proposal]( https://github.com/tc39/proposal-pipeline-operator ) hits stage 3.
