### ISSUE TITLE
Add Log Level Output to built in Logger

### ISSUE THREAD

**Issue by WonderPanda** [nestjs/nest#6172]
## Is your feature request related to a problem? Please describe.
The default logger supports multiple log levels but currently the only distinguishing aspect is different colors (assuming that the developer has this turned on). When managing logs in a deployed environment its essential to be able to search for and group on different log levels to properly diagnose issues.

## Describe the solution you'd like
The log level should be written out as part of the log message. Eg `[INFO]` or `[ERROR]` should be part of the log string itself. This will allow for proper GROK patterns to be set up with various log aggregation tools to properly categorize logs by type

I'm happy to contribute this change if @kamilmysliwiec feels its a reasonable addition

**Comment by kamilmysliwiec** [comment]
Thanks for the suggestion! Let's track this here https://github.com/nestjs/nest/pull/6221
