### ISSUE TITLE
Add decorator for quickly injecting the current user

### ISSUE THREAD

**Issue by nick-lehmann** [nestjs/nest#6174]
## Feature Request

It is quite common that I have to get the `req.user` property for the current request in order to return basically anything to the client. Currently, I use the `@Request` decorator for injecting the whole request and then access `req.user` or any property of it.

As this is very common for me and probably others, I would like to recommend either a builtin `@User` decorator or some documentation on how to implement such a decorator.

I understand that the maintainers probably do not want to add builtin decorators for everything in `req.user` but this one is probably very common.

If the maintainer do not want to add this special decorator, I would be fine with some documentation on how to implement this decorator. This would have the advantage that anybody could implement decorators like `@Username` or `@UserId` for specifc property of the user payload. Unfortunately, I was not able to figure it out myself as the code in [packages/common/decorators/http/route-params.decorator.ts](https://github.com/nestjs/nest/blob/master/packages/common/decorators/http/route-params.decorator.ts) seems very cryptic to me as it uses a lot of `Reflect` magic.

## Is your feature request related to a problem? Please describe.

No, it is only for convenience.

## Describe the solution you'd like

```
export class ThingController {
    async getAll(@User() user: UserPayload): Promise<Thing[]> {
        return this.service.get(user)
    }
}
```

## Teachability, Documentation, Adoption, Migration Strategy

Not really applicable as nothing that already exists would need to be changed.

## What is the motivation / use case for changing the behavior?

A specific decorator would enhance readability and it is convenient as I currently have to do this a couple times a day.

**Comment by jmcdo29** [comment]
You mean [documentation like this](https://docs.nestjs.com/custom-decorators#custom-route-decorators) where it shows you can use `createParamDecorator`? The explicit use case is even for `req.user`

```ts

import { createParamDecorator, ExecutionContext } from '@nestjs/common';

export const User = createParamDecorator(
  (data: unknown, ctx: ExecutionContext) => {
    const request = ctx.switchToHttp().getRequest();
    return request.user;
  },
);
```

**Comment by nick-lehmann** [comment]
Oh fail, never mind 🤦🏼‍♂️ Thank you for pointing it out @jmcdo29 👍🏻
