### ISSUE TITLE
After creating a new project, this one can't find tsconfig.json file

### ISSUE THREAD

**Issue by Leccho** [nestjs/nest#6178]
## Current behavior
On installation, eslint 7.7.0 is installed and then all files of type js and ts have this error:
`Parsing error: Cannot read file tsconfig.json`

## Expected behavior
Should be able to find the file.

## Possible Solution
Downgrading eslint to version 6.8.0 seems to do the trick, but a message apear on eslint inisialization:
`Failed to load plugin '@typescript-eslint' declared in 'rest-api\.eslintrc.js': Cannot find module '@typescript-eslint/eslint-plugin' Require stack: - [path]\__placeholder__.js Referenced from: [path]\rest-api\.eslintrc.js`

<pre><code>
Nest version: 7.5.1
 
For Tooling issues:
- eslint version: 7.7.0
- typescript version 3.7.4
- Node version: 13.9.0 
- Platform:  Windows 10

Others:
Visual studio code with extension ESLint 2.1.14 (Dirk Baeumer)

Note:
In Angular, I have this error from tslint lately: `Not using the local TSLint version found` and I have to enable loading and linting rules from the current workspace. Maybe the two are related.
</code></pre>

**Comment by jmcdo29** [comment]
What are the steps to reproduce this?

**Comment by Leccho** [comment]
With nestjs 7.5.1, you create the project `nest new [project-name]`

Opening any file of type ts or js will throw the error.

**Comment by Leccho** [comment]
It fixed itself. So I don't know what the problem was because I never found it.

**Comment by gmwill934** [comment]
How did you solve this? I've tried your solution but it still shows me that error.

**Comment by Leccho** [comment]
It's not solved. Go in your packages.json and for eslint use 6.8.0. It give an error in eslint loading and the error disapear. Not what I wanted but for now it's that.

You need to reinstall node_modules. And reload VS code so the errors disapear.

**Comment by DaZiYuan** [comment]
Please reopen this issue, it still occurs when running these commands.

repro setups:
```
nest new server
cd ./server
nest g app admin
yarn
yarn start:dev
```

**Comment by micalevisk** [comment]
@DaZiYuan I didn't manage to reproduce that on my Ubuntu using the latest version of `@netsjs/cli` (v8.2.1). Everything went fine here.

<details>
<summary>proof</summary>

![image](https://user-images.githubusercontent.com/13461315/156498514-7d8d20ea-565b-442c-bef5-5b77430904b5.png)

</details>

**Comment by DaZiYuan** [comment]
I can reproduce this on windows10.
https://github.com/DaZiYuan/nest-test

it starts ok but have an error message in vscode when you import anything from '@nestjs/xx';
```
nest new server
Which package manager would you ❤️  to use? yarn
cd ./server
nest g app admin
yarn
yarn start:dev
```

![image](https://user-images.githubusercontent.com/80653/156500506-cb124097-e226-47bd-9949-51d06f042055.png)

![image](https://user-images.githubusercontent.com/80653/156500056-828676bd-de4c-4836-8730-1cc4ff66927b.png)

![image](https://user-images.githubusercontent.com/80653/156500646-ea579d8a-2691-415f-b4d9-70dabc659e05.png)
![image](https://user-images.githubusercontent.com/80653/156500666-0fb4c896-ba48-4115-9ce9-177b88397e11.png)

**Comment by kamilmysliwiec** [comment]
`nest g app` should never be used directly.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
