### ISSUE TITLE
Fastify Compression doesn't work anymore

### ISSUE THREAD

**Issue by Aragur** [nestjs/nest#6179]
## Current behavior
App Crashes  
Crash Log: https://pastebin.com/ZEExtbC9

## Input Code

```ts
//...
import compression from 'fastify-compress';

async function bootstrap(): Promise<void> {
    const app = await NestFactory.create<NestFastifyApplication>(
        AppModule,
        new FastifyAdapter({
            logger: false, // Set to true to activate the built in logger
            ignoreTrailingSlash: true,
            maxParamLength: 300,
        }),
    );
    app.register(compression);
}
bootstrap();
```
Example Repository: https://github.com/Aragur/bug-fastify-compression

## Expected behavior
Should work :)

## Possible Solution
Downgrade Fastify

## Environment
<pre><code>
Nest version: 7.6.5
 
For Tooling issues:
- Node version: v15.6.0
- Platform:  Linux (Arch)

Other:
- Fastiy-Version 3.10.1
- Fasify-Version (working) 3.9.2
</code></pre>

**Comment by Tony133** [comment]
Hi @Aragur, you can leave a minimal reproduction of a clonable git repo so the core team can evaluate the problem you reported.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by Aragur** [comment]
@Tony133 @kamilmysliwiec Done: https://github.com/Aragur/bug-fastify-compression

**Comment by jmcdo29** [comment]
Using `yarn install` with your reproduction, I can't start the server. Something about fastify 3.10.x vs 3.9.x.

When I **do** use 3.9.x I have no problems calling to `GET /` and `GET /error` without something crazy happening in the logs. 

In short, with what you've provided, I can't reproduce this
