### ISSUE TITLE
Fastify GraphQL Playground doesn't work

### ISSUE THREAD

**Issue by gitbugr** [nestjs/nest#6180]
## Current behavior
GraphQL Playground does not load when using fastify, instead `GET query missing.` is shown in plain text.

## Expected behavior
GraphQL Playground should load.

## Reproducible Environment
https://codesandbox.io/s/bold-snowflake-hmet5
(go to the /graphql route in the sandbox browser)

**Comment by gitbugr** [comment]
I've just found this: https://github.com/apollographql/apollo-server/issues/4463

Which explains that the issue is with the latest apollo-server-fastify version not supporting fastify3. The temp solution is to install `"apollo-server-fastify": "3.0.0-alpha.3"` until that's released. Maybe this should be documented until then?

**Comment by jmcdo29** [comment]
If you want to add a comment in the docs about this, that would be great. `@nestjs/platform-fastify@7.4.2` (I think) was when fastify was bumped to v3

**Comment by gitbugr** [comment]
It seems I was a bit preemptive in saying the above was a solution, this is still partially broken in nest when using this version. The page loads, however it appears some scripts don't load due to cors? 
<img width="1345" alt="Screenshot 2021-01-16 at 18 40 53" src="https://user-images.githubusercontent.com/6732567/104820102-95cc5880-582a-11eb-884d-404509472bcc.png">

**Comment by jmcdo29** [comment]
Are you using helmet as well or just the fastify-cors package? Seeing as it is a CSP issue, I would bet that it's something similar to [what's mentioned in the swagger docs](https://docs.nestjs.com/openapi/introduction#bootstrap)

**Comment by gitbugr** [comment]
> Are you using helmet as well or just the fastify-cors package? Seeing as it is a CSP issue, I would bet that it's something similar to [what's mentioned in the swagger docs](https://docs.nestjs.com/openapi/introduction#bootstrap)

You're right, it was helmet!
Adding a policy for the cdn fixes the issue, however I'm a little annoyed these aren't served locally, so going to look into that.
 
```
  app.register(helmet, {
      contentSecurityPolicy: {
      directives: {
         defaultSrc: [`'self'`],
        styleSrc: [`'self'`, `'unsafe-inline'`, 'cdn.jsdelivr.net', 'fonts.googleapis.com'],
        fontSrc: [`'self'`, 'fonts.gstatic.com'],
        imgSrc: [`'self'`, 'data:', 'cdn.jsdelivr.net'],
        scriptSrc: [`'self'`, `https: 'unsafe-inline'`, `cdn.jsdelivr.net`],
      },
    },
  });
```

**Comment by jmcdo29** [comment]
Looks like something to bring up with the apollo team, it is their playground afterall. If you'd like to add a note about this in the docs, the `Security > Helmet` page would probably be a good place to note it so there's only one place we need to update in the future :smile:

**Comment by gitbugr** [comment]
> Looks like something to bring up with the apollo team, it is their playground afterall.

Of course, sorry, I didn't intend to make it seem like I was criticising nest regarding this. Just airing my thoughts lol

> If you'd like to add a note about this in the docs

I've just pushed a PR to the docs repo. Had to pop out so just got around to it. :)

**Comment by jmcdo29** [comment]
> Of course, sorry, I didn't intend to make it seem like I was criticising nest regarding this. Just airing my thoughts lol

No worries, just figured I should mention where to bring it up

> I've just pushed a PR to the docs repo. Had to pop out so just got around to it. :)

Awesome, thank you.

I'm going to go ahead and close this out, as it's not related to Nest directly.

**Comment by steinroe** [comment]
The above config didn't work for me. I had to use the following:


```
await app
      .getHttpAdapter()
      .getInstance()
      .register(fastifyHelmet, {
        contentSecurityPolicy: {
          directives: {
            defaultSrc: [`'self'`],
            styleSrc: [
              `'self'`,
              `'unsafe-inline'`,
              'unpkg.com',
              'cdn.jsdelivr.net',
              'fonts.googleapis.com',
            ],
            connectSrc: [`'self'`, `unpkg.com`],
            fontSrc: [`'self'`, 'fonts.gstatic.com'],
            imgSrc: [`'self'`, 'data:', 'cdn.jsdelivr.net'],
            scriptSrc: [
              `'self'`,
              `'unsafe-eval'`,
              `https: 'unsafe-inline'`,
              `cdn.jsdelivr.net`,
              `unpkg.com`,
            ],
          },
        },
      });
```
