### ISSUE TITLE
HttpService Socket Hang Up w/ Connection Pooling

### ISSUE THREAD

**Issue by alexhwoods** [nestjs/nest#6182]
Hey guys! First of all, thank you for creating Nest.js — we use it at work and we really like it.

We've recently implemented connection pooling and we've with [agentkeepalive](https://www.npmjs.com/package/agentkeepalive) noticed a certain proportion of requests will fail with `socket hang up` errors.

I spent a while testing `agentkeepalive` with Node's HTTP module directly, as well as with Axios, and they both work as expected. However, when combined with `HttpService`, it causes `socket hang up` errors. The error can be bypasses if you use `httpService.axiosRef` directly—which is evidence that the problem is in `HttpService`.

e.g. With this connection pooling setup

```tsx
import { Module, HttpModule } from '@nestjs/common';
import * as Agent from 'agentkeepalive';

import { AppController } from './app.controller';
import { AppService } from './app.service';

const agentConfig = {
  maxSockets: 1,    // constraining this to produce the issue easily
  maxFreeSockets: 1,
};

@Module({
  imports: [
    HttpModule.registerAsync({
      useFactory: () => ({
        httpAgent: new Agent(agentConfig),
        httpsAgent: new Agent.HttpsAgent(agentConfig),
      }),
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

This works with it, using the connection pooling properly

```tsx
// works fine with connection pooling
await this.httpService
  .axiosRef({
    url: 'https://google.com',
    method: 'GET',
  })
  .then(...)
  .catch(...);
```

and this does not, causing socket hang ups

```tsx
// causes socket hang ups with connection pooling
await this.httpService
  .get('https://google.com')
  .toPromise()
  .then(...)
  .catch(...);
```

I have a full reproduction [in this repo](https://github.com/alexhwoods/socket-hangups), with instructions in the README. Thank you for any help in advance!

**Comment by kamilmysliwiec** [comment]
If you look inside the `HttpService`, you'll notice that we're simply wrapping `axios` calls in RxJS observable streams so there's nothing we can fix/change on our side. My guess is that the issue is caused specifically by the `.toPromise()` call and the way it works in combination with the `defer()` creator function.

I would suggest using our [Discord](https://discord.gg/G7Qnnhy) channel (support channel) for support questions as we are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by alexhwoods** [comment]
Sure - why would there be a difference between the two then?

**Comment by alexhwoods** [comment]
Hey @kamilmysliwiec, thanks for responding!

And ok, I'll try to boil it down to a specific difference between promises and observables, in case someone else comes across this bug.

**Comment by alexhwoods** [comment]
Can confirm it's not `toPromise` — produces socket hang ups with normal observables too. Could be Axios + Observables not working in this use case
```typescript
  getHelloWithObservable() {
    this.logIncomingRequest('(observable)');

    this.httpService
      .get(url)
      .subscribe(() => this.logFinished(), err => this.logError(err));
  }
```
(This is now in my example)

**Comment by alexhwoods** [comment]
Mmm, note that I was using Nest 6. I believe this might be fixed in Nest 7. I'll confirm w my tests now

**Comment by alexhwoods** [comment]
Yep, was an issue with Nest 6. Thanks!
