### ISSUE TITLE
FileInterceptor on Fastify using fastify-multer

### ISSUE THREAD

**Issue by AlecDusheck** [nestjs/nest#6183]
## Is your feature request related to a problem? Please describe.
We're all aware of the fact that the `FileInterceptor` does not work with the `FastifyAdapter`. For many, this drawback is enough to make them ditch Fastify all together until a clean solution can be established.

About a year ago, a new package named [fastify-multer](https://www.npmjs.com/package/fastify-multer) was released which ports over Multer, the underlying package under the `FileInterceptor`, to Fastify.

## Describe the solution you'd like
Ideally, the a new FileInterceptor can be made under the Fastify platform and can be adapted to use this package.

## Teachability, Documentation, Adoption, Migration Strategy
I don't see any major technical hurdles to accomplishing this. The`FileInterceptor` code doesn't seem too hard to deal with and port over.

## What is the motivation / use case for changing the behavior?
To cleanly handling file uploads using Fastify

**Comment by kamilmysliwiec** [comment]
Tracking this here https://github.com/nestjs/nest/pull/4921
