### ISSUE TITLE
Dependancy vulnerability

### ISSUE THREAD

**Issue by httpsOmkar** [nestjs/nest#619]
## I'm submitting a...
[ ] Regression
[-] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
I was using the snyk for checking the vulnerability of the dependency and I found that the following dependency have  `Regular Expression Denial of Service (ReDoS) ` vulnerability

`@nestjs/websockets@4.6.6 > @nestjs/core@4.6.6 > debug@2.6.7`
`@nestjs/common@4.6.6 › class-validator@0.8.1 › validator@9.2.0 `

## Environment
Nest version: 4.6.6
OS: Linux
 
For Tooling issues:
- Node version: v9.11.1
- Platform: Linux

**Comment by kamilmysliwiec** [comment]
This issue is fixed in the incoming release 🙂 Thanks for reporting @httpsOmkar
