### ISSUE TITLE
Randomly get topic ... whcih is not assigned to any partitions exception 

### ISSUE THREAD

**Issue by qkhanhpro** [nestjs/nest#6197]
## Current behavior
I am using NestJs with Kafka and the error `The client consumer subscribed to the topic (${topic}) whcih is not assigned to any partitions.`, is often thrown with failed code execution
Some other time I get `The client consumer did not subscribe to the corresponding reply topic (${topic}).`,

The setup is very basic 

## Input Code

```ts
  @Client(serviceConfig)
  streamClient;

  onModuleInit() {
      this.streamClient.subscribeToResponseOf(...);
    };
  }

  onModuleDestroy() {
    this.streamClient.close();
  }


export const serviceConfig = {
  transport: Transport.KAFKA,
  options: {
    client: {
      clientId: '...',
      brokers: [`...`],
    },
    consumer: {
      groupId: '...',
    },
  },
};
```

## Expected behavior
The code often runs fine but sometimes the error just happens, specifically around the time of rebalancing

My configuration consists of 3 kafka broker and **2 NestJS instances** running in paralell with same source code / same setting (kubernete setup)

I put also my situation here 

https://stackoverflow.com/questions/65788607/is-it-normal-to-have-less-partition-than-broker-count-kafka-configuration?noredirect=1#comment116317902_65788607

## Possible Solution
I see that my NestJS version is before this commit https://github.com/nestjs/nest/commit/b0a0623cf8374c2dca19a5aaff1ded19ebda5926#diff-72a9f557d4f070b2a084eaf4ba5d7e3ad02a496f670958e6efee128624e6b097

I am not sure if the behaviour i am facing is related to what the commit is fixxing?

## Environment

<pre><code>
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/microservices": "^7.4.2",

Thanks for the help!

**Comment by qkhanhpro** [comment]
Update: I am using streamClient.send()

**Comment by Tony133** [comment]
Hi @qkhanhpro, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by qkhanhpro** [comment]
I am afraid this happens with specific HA configuration so it would be kind of hard to provide a minimal repo. I will still try to create a minimal reproduction and update when possible
Thanks a lot @Tony133

**Comment by qkhanhpro** [comment]
I made progress on this issue and found out the root problem
It did not come from NestJS

**Here is the full situation that caused the problem**
- I used MessagePattern as described [here](https://docs.nestjs.com/microservices/kafka) with send() method
- I set up the streamClient with Kafka transport af follow 

```
export const serviceConfig = {
  transport: Transport.KAFKA,
  options: {
    client: {
      clientId: `my-client`,
      brokers: [`${process.env.MESSAGE_BROKER_HOST}`],
    },
    consumer: {
      groupId: `my-consumer-group`
    },
  },
};
```

- The above code is built as image to deploy to high availability cluster

**The problem**

By having all NestJS instances having the same "my-consumer-group", the reply message does not reach back to the instance where the send() operation started, causing the error above

```
Consumers label themselves with a consumer group name, and each record published to a topic is delivered to one consumer instance within each subscribing consumer group. Consumer instances can be in separate processes or on separate machines.

If all the consumer instances have the same consumer group, then the records will effectively be load balanced over the consumer instances.

If all the consumer instances have different consumer groups, then each record will be broadcast to all the consumer processes.
```

My solution 

```
export const serviceConfig = {
  transport: Transport.KAFKA,
    consumer: {
      groupId: `my-consumer-group`+ guid() // Add GUID to differentiate groups
    },
};
```

**Comment by jmcdo29** [comment]
Glad you found the issue. I'll go ahead and close this out

**Comment by smilovanovic** [comment]
Why was this closed? Having a unique consumer group per instance is not really a solution because while you want all instances to consume the reply message you do not want that behaviour for regular messages which should be processed only once.

**Comment by ben-walters-veratrak** [comment]
Currently having the same issue. Despite explicitly subscribing to the response of `topic` with the snipped below, this error is still thrown.

```
this.client.subscribeToResponseOf(topic)
```

**Comment by NathBabs** [comment]
@ben-walters-veratrak were you able to fix it, i am currently facing this issue

**Comment by Akuma225** [comment]
Hello there. I got the same problem and it was just like my replies topic was deleted. It was because i subscribed to some in my user controller and another in my auth guard and in auth guard, i did kafkaClient.connect (So it seems like it deleted the previous subscribed topics).

I hope it can help someone

**Comment by mohammadjavadsameni-strenx** [comment]
i have multiple pods from a service with different envs.
i changed consumer group ids to be unique (as @qkhanhpro said [here](https://github.com/nestjs/nest/issues/6197#issuecomment-767260061)) for each env and each pods are connecting to same consumer id.
i didn't face this issue anymore.
try to check other configs. specially "clientId" of each pod. they should be unique too,
