### ISSUE TITLE
Using `WsAdapter` throws CORS: no header sent

### ISSUE THREAD

**Issue by gp187** [nestjs/nest#6198]
## Current behavior
When using the WS adapter the request are blocked by CORS
`has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

## Input Code

https://github.com/nestjs/nest/tree/master/sample/16-gateways-ws
```ts
  const app = await NestFactory.create(AppModule, fastify, {
    cors: {
      origin: origins,
      methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'HEAD'],
      credentials: true,
    }
  });
  app.useWebSocketAdapter(new WsAdapter(app));
```

I also tried setting the origins in the @Gateway
```ts
@WebSocketGateway(wsPort, { path: '/ws', namespace: '/users', origins: '*:*' })
@WebSocketGateway(wsPort, { path: '/ws', namespace: '/users', origins: 'https://' })
@WebSocketGateway(wsPort, { path: '/ws', namespace: '/users', origins: '*' })

```

## Expected behavior
CORS settings should be inherited from app CORS

## Environment

<pre><code>
Nest version: latest
    "@nestjs/platform-ws": "^7.5.4",

 
For Tooling issues:
- Node version: 12  
- Platform:  Linux

Others:

</code></pre>

**Comment by Tony133** [comment]
Hi @gp187,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by kamilmysliwiec** [comment]
> CORS settings should be inherited from app CORS

CORS configuration you pass into the `NestFactory#create()` method (or to the `enableCors()`) isn't supposed to be picked up by gateways automatically. This works as expected.
