### ISSUE TITLE
Route parameters (i.e. slug) of length above 100 lead to 404

### ISSUE THREAD

**Issue by Green-Cat** [nestjs/nest#6201]
## Current behavior
If the route parameter length the router throws a 404.

## Input Code

```ts
    @Get("/:slug")
    async details(@Param("slug") slug: string) {
        // any code here
    }
```
Then visit:
http://mydomain.we/my-module/this-is-a-very-very-very-long-slug-resulting-in-a-404-error-on-latest-nestjs-version

## Expected behavior
The router calls the correct function.

## Environment

<pre><code>
Nest version: 7.6.5
Fastify version: 3.10.1 

For Tooling issues:
- Node version: 13.9
- Platform: Tested on Linux and macOS 
</code></pre>

**Comment by jmcdo29** [comment]
https://github.com/fastify/fastify/blob/master/docs/Server.md#maxparamlength

**Comment by Green-Cat** [comment]
@jmcdo29 Thanks!
