### ISSUE TITLE
Validation not working when extending abstract base controller

### ISSUE THREAD

**Issue by dorinionut** [nestjs/nest#6205]
## Bug Report

I have created a base controller where I defined all the methods accepted and basic parameters (eg: itemsPerPage, page etc.).

For each data type I extend this base controller and create a controller specific to that type.

## Current behavior
However, validation fails in this case, meaning that empty values will pass right on and go to straight to DB.

## Input Code
base.controller.ts

```ts
export abstract class BaseController<T> {
  constructor(
    private service: DatabaseService<T>
  ) {}

  @Post()
  insert(@Body() item: T) {
    return this.service.insert(item);
  }
}
```

child.controller.ts

```ts
@Controller('child')
export class ChildController extends BaseController<Child> {
  constructor(
    private childService: ChildService
  ) {
    super(childService);
  }
}
```

## Expected behavior
Type validation should still work and throw error / Bad Request

## Environment

<pre><code>
Nest version: 7.6.5

 
For Tooling issues:
- Node version: 14.15.1
- Platform:  Mac

Others:
class-transformer: 0.3.2
class-validator: 0.13.1
</code></pre>

**Comment by jmcdo29** [comment]
Generic types don't get reflected by Typescript so nest can't read the parameter's type and know how to pass it on to the pipe. You can use a `mixin` (a function that returns a class) instead to help with your type definitions. Or you can check out how `@nestjsx/crud` tackles this problem.
