### ISSUE TITLE
Reconnecting to Redis is not working

### ISSUE THREAD

**Issue by zwiras** [nestjs/nest#6212]
## Current behavior

I am using an example from the documentation about queues (26-queues). I set a delay of 3000 ms in calling the procedure. I start redis in docker and run applications. It then calls an endpoint that adds the procedure to the queue. Before calling the procedure, it restarts the redis in the docker. The procedure is not launched. Only when the application is restarted, this procedure starts.
## Expected behavior

NestJs and Redis should try to reconnect. I think it should be configurable like in microservices.

## Environment

<pre><code>
Nest version: 7.6.5

 
For Tooling issues:
- Node version: 12.19.0  
- Platform: Windows  

Others:
IDE: Visual Studio Code

</code></pre>

**Comment by Tony133** [comment]
Hi @zwiras , I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the Bull repository.
