### ISSUE TITLE
[typeorm]If entity class name is end with "Entity", it will trigger Nest can't resolve dependencies of the ***error message

### ISSUE THREAD

**Issue by WongYueKeung** [nestjs/nest#6219]
**and requested change in doc as well
Hi all, I know it is a bug might related to the typeorm, but idk which framwork contribute to this error and  thats why i open a ticket here

## Bug Report
how to recreate this error message
install typeorm
set up DB config and stuff
**create a entity file**
and class name end with "Entity"

## Input Code
``ts filename: application-place.entity.ts
import { Column, Entity, PrimaryColumn, UpdateDateColumn, } from 'typeorm';

export const SETUP_JSON_LIMIT = 2048;

@Entity()
export class ApplicationPlaceEntity {

  @PrimaryColumn()
  id: number;

  @Column()
  name: string;

  @Column()
  siteId: string;

  @Column()
  appId: string;

  @UpdateDateColumn()
  updateDate: Date; 

}

## Expected behavior

NPM start -> Nest can't resolve dependencies of the ApplicationService (***, ?,
**** ). Please make sure that the argument ApplicationSiteRepository at index [1] is available in t
he ApplicationModule context.

## Possible Solution
confirmed fixing solution:
ez rename the application-place.entity.ts's class name from ApplicationPlaceEntity to  ApplicationPlace 
and it would stop prompting the dependencies resolving error massage

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by WongYueKeung** [comment]
uhh wait but i am sure this is framework's bug
it oly goes wrong if the entity's class name end with Entity, framework should allow ppl to use any class name they want unless it is stated in the document
can u please just spend a minute, go install typeorm and nestjs, set up a DB table and try to name the class name end with Entity (in the **.entity.ts file), and u will see the error by nestjs trust me

**Comment by kamilmysliwiec** [comment]
This isn't a bug. As I've mentioned above, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by jmcdo29** [comment]
If you really think this is a bug, which I'm not convinced of yet, please provide a [minimum reproduction repository](http://minimum-reproduction.wtf). I'm not sure what steps to take provided what you've given us, cause I'm sure I can set all that up and get no error. Otherwise, like Kamil said, please use our Discord channel for immediate support.
