### ISSUE TITLE
Nestjs + Nats = infinity loop

### ISSUE THREAD

**Issue by skliarovartem** [nestjs/nest#6227]
System goes to infinity loop of requests-reponses with particular message pattern name.  For example suddenly my message pattern `getUserByID` starts to give me this loop. To fix it I need to change message pattern to something else, like `getUserByID1` and it works, so I don't change my code, just message pattern. `docker-compose down` doesn't help. I'm working on Mac and run application id docker-compose. My colleague  has same problem in Linux but with another message pattern.
It is difficult to work in this way. Currently we decided to move from nats to rabbit...

**Comment by jmcdo29** [comment]
Can you provide a minimum reproduction of this?

**Comment by skliarovartem** [comment]
Sure, it is very simple:
In my API Gateway:
```
async validate(payload: any) {

        const user = await this.usersService.send('getUserById', {userId: payload.id}).toPromise();
        if(!user){
            return null
        }
        const {password, ...res} = user
        return res
    }
```

In my user microservice:
```
@MessagePattern('getUserById')
    async getById(@Body() body: { userId: number }): Promise<User> {
        this.logger.log(body, 'Get user by ID');
        return await this.service.getById(body.userId);
    }
```
Suddenly infinity loop appeared, and to fix it I need to change getUserById to something else. I was trying to remove docker images, but didn't help, so only rename the message pattern name worked...
Let me know if you need something else
Many thanks!

**Comment by jmcdo29** [comment]
> Sure, it is very simple:

Great, then you won't mind making it a git repo that is clonable, right?

**Comment by skliarovartem** [comment]
Well, it is difficult to reproduce. Because it appears randomly. We changed transporter to rabbit and now it works perfectly, without changing any code of message patterns or other communication logic.

**Comment by kamilmysliwiec** [comment]
We can't help without a reproduction repository.
