### ISSUE TITLE
Nest don't handle shutdown hooks or SIGTERM SIGINT when running application in docker

### ISSUE THREAD

**Issue by titkovandrew** [nestjs/nest#6234]
## Current behavior
I can't handle any shutdown hook or process signals if run application in Docker.

## Input Code

main.ts
```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableShutdownHooks();
  await app.listen(3000);

  process.stdin.resume();

  process.on('SIGINT', () => {
    console.log('SIGINT');
  });

  function handle(signal) {
    console.log(signal);
  }

  process.on('SIGINT', handle);
  process.on('SIGTERM', handle);
}
bootstrap();
```

Dockerfile 
```

FROM node:14.15.1

COPY . /server

WORKDIR /server
RUN echo insecure >> ~/.curlrc
RUN DOWNLOAD=1 yarn install
RUN yarn global add @nestjs/cli

ENTRYPOINT ["nest", "start --watch"]
```

P.S. it works if in next configuration of dockerfile (but i would like to have hot reload)
```
FROM node:14.15.1

COPY . /server

WORKDIR /server
RUN echo insecure >> ~/.curlrc
RUN DOWNLOAD=1 yarn install
RUN yarn build

ENTRYPOINT ["node", "dist/main.js"]

```

## Expected behavior
I would like handle shutdown hooks and process signals ('gracefully shutdown') when running application in Docker.

<pre><code>
Nest version: 7.5.0
 
For Tooling issues:
- Node version: v14.4
- Platform:  Mac

**Comment by techvlad** [comment]
This not a bug

>Node.js was not designed to run as PID 1 which leads to unexpected behaviour when running inside of Docker. For example, a Node.js process running as PID 1 will not respond to SIGINT (CTRL-C) and similar signals. As of Docker 1.13, you can use the --init flag to wrap your Node.js process with a lightweight init system that properly handles running as PID 1.
```bash
docker run -it --init node
```
https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#handling-kernel-signals

**Comment by titkovandrew** [comment]
@techvlad  in next configuration i have node and it is works.
I see SIGTERM and SIGINT 

and also can handle all hooks 

```
FROM node:14.15.1

COPY . /server

WORKDIR /server
RUN echo insecure >> ~/.curlrc
RUN DOWNLOAD=1 yarn install
RUN yarn build

ENTRYPOINT ["node", "dist/main.js"]
```

but it won't work if i run the save project without building it 
```
RUN yarn build
```

BTW i can't pass flag because I have docker-compose file

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
