### ISSUE TITLE
Switching to Fastify errors on a module dependency

### ISSUE THREAD

**Issue by chrismeller** [nestjs/nest#6246]
## Current behavior
```
[17:38:38] Starting compilation in watch mode...

node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.d.ts:3:23 - error TS2305: Module '"../../common/interfaces/external/cors-options.interface"' has no exported member 'CorsOptionsDelegate'.

3 import { CorsOptions, CorsOptionsDelegate } from '@nestjs/common/interfaces/external/cors-options.interface';
                        ~~~~~~~~~~~~~~~~~~~

[17:38:43] Found 1 error. Watching for file changes.
```

## Input Code
Very basic, I switch a working app from this:
```ts
const app = await NestFactory.create(AppModule);
```

to this:
```ts
const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter({ logger: true }));
```

## Expected behavior
A web server that starts and, ideally, uses Fastify instead of Express.

## Environment

Relevant dependencies:
```
    "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/platform-fastify": "^7.6.6",
```
And for dev, since it's through the Nest CLI:
```
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
```
 
For Tooling issues:
- Node version: 15.2.1
- Platform:  Windows 10

**Comment by jmcdo29** [comment]
Make sure your `common`, `core`, and `platform-*` dependencies all have the same version. 7.6.6 was recently released which has this exported types that is being complained about.

**Comment by chrismeller** [comment]
Thanks very much @jmcdo29. I'm never totally sure when you guys update each package, that was a total "npm says everything is fine". My bad, I'll close this.
