### ISSUE TITLE
GraphQL WebSocket Connection Scope

### ISSUE THREAD

**Issue by flux627** [nestjs/nest#6253]
## Is your feature request related to a problem? Please describe.
While NestJS does expose the `onConnect` and `onDisconnect` hooks in the subscriptions options object, I am looking to maintain class instances that manage the client's state for the duration of their websocket connection from within the DI context.

## Describe the solution you'd like
I don't know how feasible this is, but it would be great to simply define the scope via `@Module({ scope: GRAPHQL_WS_CONNECTION })`. I am open to any solution, however.

## What is the motivation / use case for changing the behavior?
When the websocket connection establishes from the client, I need to open up multiple streams of data from which I aggregate state, which I use to determine when/if I should push updates to the client, based on their open subscriptions. As there isn't a 1-to-1 relationship between subscriptions and needed backend streams, opening up streams per-subscription leads to a lot of duplicate data and processing.

**Comment by kamilmysliwiec** [comment]
As this https://github.com/nestjs/nest/issues/4287 is a very similar issue, let's track it there in one place

**Comment by flux627** [comment]
Thanks for bringing this other issue my attention.

Would you have any suggestions for the best way to use `onConnect` and `onDisconnect` to effectively achieve what I need, as a workaround?

**Comment by flux627** [comment]
@kamilmysliwiec not sure if this has visibility to you since the issue is now closed.
