### ISSUE TITLE
with class-transformer v0.3.2

### ISSUE THREAD

**Issue by rktyt** [nestjs/nest#6256]
## Current behavior

I got type error.
> error TS2322: Type '{ excludeExtraneousValues: true; exposeDefaultValues: true; }' is not assignable to type 'ClassTransformOptions'.

### pagination.dto.ts

```ts
import { IsOptional, IsPositive, IsInt, Max } from 'class-validator'
import { Type, Expose } from 'class-transformer'

class PaginationDto {
  @IsOptional()
  @IsInt()
  @IsPositive()
  @Type(() => Number)
  @Expose()
  readonly page = 1

  @IsOptional()
  @IsInt()
  @IsPositive()
  @Type(() => Number)
  @Expose()
  @Max(100)
  readonly limit = 50

  get skip(): number {
    return (this.page - 1) * this.limit
  }
  get take(): number {
    return this.limit
  }
}
```

### controller.ts

```ts
import {
  Controller,
  Get,
  Query,
  UsePipes,
  ValidationPipe,
} from '@nestjs/common'
import { PaginationDto } from './pagination.dto.ts'

@Controller('test')
export class AppController {
  @Get('')
  @UsePipes(
    new ValidationPipe({
      transform: true,
      transformOptions: { excludeExtraneousValues: true, exposeDefaultValues: true },
    })
  )
  async index(@Query() dto: PaginationDto) {
    console.log(dto.skip, dto.take)
    ......
  }
}
```

## Expected behavior

- No type error

## Possible Solution

Please add `exposeDefaultValues?: boolean;`  to <https://github.com/nestjs/nest/blob/v7.6.7/packages/common/interfaces/external/class-transform-options.interface.ts>.

See <https://github.com/typestack/class-transformer/blob/v0.3.2/src/interfaces/class-transformer-options.interface.ts>.

----

#### controller.ts

```ts
import {
  Controller,
  Get,
  Query,
  UsePipes,
  ValidationPipe,
} from '@nestjs/common'
import { PaginationDto } from './pagination.dto.ts'
import { ClassTransformOptions } from 'class-transformer'

@Controller('test')
export class AppController {
  @Get('')
  @UsePipes(
    new ValidationPipe({
      transform: true,
      transformOptions: { excludeExtraneousValues: true, exposeDefaultValues: true } as ClassTransformOptions,
    })
  )
  async index(@Query() dto: PaginationDto) {
    console.log(dto.skip, dto.take)
    ......
  }
}
```
## Environment

<pre><code>
Nest version: 7.6.7

 
For Tooling issues:
- Node version: v12.20.0  
- Platform:  Linux 

Others:

- class-transformer: v0.3.2
</code></pre>

**Comment by Tony133** [comment]
Hi @rktyt,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

however, you could add `exposeDefaultValues?: boolean;` as you said.

**Comment by kamilmysliwiec** [comment]
Let's track this here  https://github.com/nestjs/nest/pull/6257
