### ISSUE TITLE
Metatype is not a constructor

### ISSUE THREAD

**Issue by ShivamPathak10194** [nestjs/nest#6258]
I am working on a nestjs project with graphql and mikro-orm. Everything had been working fine on my main repository until today. All of a sudden, I have been seeing "metatype is not a constructor" when I do a yarn start:debug.
Attaching my package.json.
Please help.

package.json

> {
>   "name": "priojet-backend",
>   "version": "0.0.1",
>   "description": "",
>   "author": "",
>   "private": true,
>   "license": "UNLICENSED",
>   "scripts": {
>     "prebuild": "rimraf dist",
>     "build": "NODE_ENV=production nest build",
>     "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
>     "start": "NODE_ENV=development nest start",
>     "start:dev": "NODE_ENV=development nest start --watch",
>     "start:debug": "NODE_ENV=development nest start --debug --watch",
>     "start:prod": "NODE_ENV=production node dist/main",
>     "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
>     "test": "NODE_ENV=test jest",
>     "test:watch": "NODE_ENV=test jest --watch",
>     "test:cov": "NODE_ENV=test jest --coverage",
>     "test:debug": "NODE_ENV=test node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
>     "test:e2e": "NODE_ENV=test jest --config ./test/jest-e2e.json",
>     "todo": "grep -R --exclude-dir=node_modules 'todo' .",
>     "TODO": "grep -R --exclude-dir=node_modules 'TODO' .",
>     "loose-types": "echo -e 'anys:\n\n'; grep -r any src; echo -e '\n\nfunctions\n\n'; grep -r function src; echo -e '\n\n';",
>     "db": "mikro-orm",
>     "db:help": "cat ./src/migrations/cli.ts",
>     "db:update": "echo 'Running db:create (creating migration based on diff) and db:up (migrate database to the latest migration)\n\n'; yarn db:create; yarn db:up",
>     "db:init": "mikro-orm schema:create -r",
>     "db:create": "mikro-orm migration:create",
>     "db:up": "mikro-orm migration:up       # Migrate up to the latest version",
>     "db:down": "mikro-orm migration:down     # Migrate one step down",
>     "db:list": "mikro-orm migration:list     # List all executed migrations",
>     "db:pending": "mikro-orm migration:pending  # List all pending migrations",
>     "prebuild:prod": "rimraf dist # && tsc"
>   },
>   "dependencies": {
>     "@casl/ability": "^5.2.2",
>     "@mikro-orm/cli": "^4.4.0",
>     "@mikro-orm/core": "^4.4.0",
>     "@mikro-orm/nestjs": "^4.2.0",
>     "@mikro-orm/postgresql": "^4.4.0",
>     "@mikro-orm/reflection": "^4.4.0",
>     "@nestjs/common": "^7.6.7",
>     "@nestjs/config": "^0.6.2",
>     "@nestjs/core": "^7.6.7",
>     "@nestjs/graphql": "^7.9.8",
>     "@nestjs/passport": "^7.1.5",
>     "@nestjs/platform-express": "^7.6.7",
>     "apollo-server-errors": "^2.4.2",
>     "apollo-server-express": "^2.19.2",
>     "autoclean": "^1.0.2",
>     "class-validator": "^0.13.1",
>     "dotenv": "^8.2.0",
>     "graphql": "^15.5.0",
>     "graphql-fields-to-relations": "^1.0.4",
>     "graphql-tools": "^7.0.2",
>     "passport-azure-ad": "^4.3.0",
>     "passport-jwt": "^4.0.0",
>     "randomstring": "^1.1.5",
>     "reflect-metadata": "^0.1.13",
>     "rimraf": "^3.0.2",
>     "rxjs": "^6.5.4",
>     "type-graphql": "^1.1.1",
>     "util": "^0.12.3",
>     "uuid": "^8.3.1"
>   },
>   "devDependencies": {
>     "@nestjs/cli": "^7.5.4",
>     "@nestjs/schematics": "^7.2.7",
>     "@nestjs/testing": "^7.6.7",
>     "@types/passport-azure-ad": "^4.0.8",
>     "@types/uuid": "^8.3.0",
>     "eslint": "7.18.0",
>     "eslint-config-prettier": "^7.2.0",
>     "eslint-plugin-import": "^2.20.1",
>     "jest": "26.6.3",
>     "prettier": "2.2.1",
>     "supertest": "^6.1.3",
>     "ts-jest": "26.4.4",
>     "ts-loader": "^8.0.14",
>     "ts-node": "^9.0.0",
>     "tsconfig-paths": "^3.9.0",
>     "typescript": "^4.1.3"
>   },
>   "jest": {
>     "moduleFileExtensions": [
>       "js",
>       "json",
>       "ts"
>     ],
>     "rootDir": "src",
>     "testRegex": ".spec.ts$",
>     "transform": {
>       "^.+\\.(t|j)s$": "ts-jest"
>     },
>     "coverageDirectory": "../coverage",
>     "testEnvironment": "node"
>   },
>   "mikro-orm": {
>     "useTsNode": true,
>     "tsConfigPath": "./tsconfig.orm.json",
>     "configPaths": [
>       "./src/config/database/postgres/mikro-orm.postgres.config.ts",
>       "./build/config/database/postgres/mikro-orm.postgres.config.ts"
>     ]
>   }
> }

[package.txt](https://github.com/nestjs/nest/files/5881238/package.txt)

**Comment by Tony133** [comment]
Hi @ShivamPathak10194,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.
