### ISSUE TITLE
Display errors thrown by loadPackage()

### ISSUE THREAD

**Issue by chriswoodle** [nestjs/nest#6260]
## Feature Request
In https://github.com/nestjs/nest/blob/275e71f89ad2d1bf7ddecd691602b5a15708291d/packages/common/utils/load-package.util.ts#L8

The error caught should be displayed to the console.

## Is your feature request related to a problem? Please describe.

This try-catch swallows errors thrown by require

```typescript
 try {
        return loaderFn ? loaderFn() : require(packageName);
    } catch (e) {
        logger.error(MISSING_REQUIRED_DEPENDENCY(packageName, context));
        process.exit(1);
    }
```

## Describe the solution you'd like
Could the error caught be displayed to the console or logged with the logger?

## Teachability, Documentation, Adoption, Migration Strategy
N/A

## What is the motivation / use case for changing the behavior?
When using Yarn2 PnP pnpMode: strict, it is necessary to look at these errors to debug dependency access. For example this error is hidden:

```
Required package: swagger-ui-express (via "swagger-ui-express")
Required by: @nestjs/swagger@virtual:2e4cb0595f9ad4225538d59e3595a6b5e6a8809d034737d43d9aa2e617b2caae6
5f33724658ce0a806c2cd8fb035c423acf187fe2419ae608ab7e10644587687#npm:4.7.12 ...
```
And instead shown as:
```
[PackageLoader] The "swagger-ui-express" package is missing....
```

In order to fix other library dependencies, these errors have to be visible.

Thanks!

**Comment by jmcdo29** [comment]
There's already a try/catch around the require function and in the `catch` there's a logger statement. Are you wanting to see that error re-thrown?

**Comment by chriswoodle** [comment]
> 
> 
> There's already a try/catch around the require function and in the `catch` there's a logger statement. Are you wanting to see that error re-thrown?

It doesn't have to be rethrown, just displayed to the console:

```
 try {
        return loaderFn ? loaderFn() : require(packageName);
    } catch (e) {
        console.log(e);
        logger.error(MISSING_REQUIRED_DEPENDENCY(packageName, context));
        process.exit(1);
    }
```
Or with the logger, I'm not sure which is more appropriate.

**Comment by jmcdo29** [comment]
That's what I'm saying though, it should be shown by the logger. That's why that `logger.error()` is there. The only reason it wouldn't be displayed is if you set `logger: false` in the `NestFactory`. And there's a PR to help with that here soon so that if error happen during bootstrap the default logger logs it and if not the custom logger can log everything

**Comment by chriswoodle** [comment]
> 
> 
> That's what I'm saying though, it should be shown by the logger. That's why that `logger.error()` is there. The only reason it wouldn't be displayed is if you set `logger: false` in the `NestFactory`. And there's a PR to help with that here soon so that if error happen during bootstrap the default logger logs it and if not the custom logger can log everything

So something like this then? Where `e` is passed into the logger?
```
 try {
        return loaderFn ? loaderFn() : require(packageName);
    } catch (e) {
        logger.error(MISSING_REQUIRED_DEPENDENCY(packageName, context), e);
        process.exit(1);
    }
```

**Comment by jmcdo29** [comment]
I guess my question here is what value does this bring
```
Required package: swagger-ui-express (via "swagger-ui-express")
Required by: @nestjs/swagger@virtual:2e4cb0595f9ad4225538d59e3595a6b5e6a8809d034737d43d9aa2e617b2caae6
5f33724658ce0a806c2cd8fb035c423acf187fe2419ae608ab7e10644587687#npm:4.7.12 ...
```
Over just this
```
[PackageLoader] The "swagger-ui-express" package is missing. Please, make sure to install this library ($ npm install "swagger-ui-express") to take advantage of "@nestjs/swagger".
```

Both seem to say what package is missing and what is making use of it (at least in terms of what component uses it)

**Comment by chriswoodle** [comment]
> 
> 
> I guess my question here is what value does this bring
> 
> ```
> Required package: swagger-ui-express (via "swagger-ui-express")
> Required by: @nestjs/swagger@virtual:2e4cb0595f9ad4225538d59e3595a6b5e6a8809d034737d43d9aa2e617b2caae6
> 5f33724658ce0a806c2cd8fb035c423acf187fe2419ae608ab7e10644587687#npm:4.7.12 ...
> ```
> 
> Over just this
> 
> ```
> [PackageLoader] The "swagger-ui-express" package is missing. Please, make sure to install this library ($ npm install "swagger-ui-express") to take advantage of "@nestjs/swagger".
> ```
> 
> Both seem to say what package is missing and what is making use of it (at least in terms of what component uses it)

Apologies, I forgot part of my error message. This error is not because the module is not installed. This kind of error is because `@nestjs/swagger` does not have `swagger-ui-express` listed in its package.json as an `optionalDependency`:

```
[nodemon] starting `node -r dotenv/config -r source-map-support/register ./dist/src/main.js`
[Nest] 7688   - 01/27/2021, 5:40:06 PM   [NestFactory] Starting Nest application...
[Nest] 7688   - 01/27/2021, 5:40:06 PM   [InstanceLoader] EnvModule dependencies initialized +14ms
[Nest] 7688   - 01/27/2021, 5:40:06 PM   [InstanceLoader] AuthModule dependencies initialized +1ms
[Nest] 7688   - 01/27/2021, 5:40:06 PM   [InstanceLoader] AppModule dependencies initialized +0ms
Error: @nestjs/swagger tried to access swagger-ui-express, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: swagger-ui-express (via "swagger-ui-express")
Required by: @nestjs/swagger@virtual:2e4cb0595f9ad4225538d59e3595a6b5e6a8809d034737d43d9aa2e617b2caae65f33724658ce0a806c2cd8fb035c423acf187fe2419ae608ab
7e10644587687#npm:4.7.12 (via C:\xxxxxxxxx\.yarn\$$virtual\@nestjs-swagger-virtual-19a50d414e\0\cache\@nestjs-swagger-npm-4.7
.12-2b0b173971-90a7dc2c72.zip\node_modules\@nestjs\swagger\dist\)

Require stack:
....
```

Another similar example:

```
[nodemon] starting `node -r dotenv/config -r source-map-support/register ./dist/src/main.js`
[Nest] 37040   - 01/27/2021, 6:14:07 PM   [NestFactory] Starting Nest application...
[Nest] 37040   - 01/27/2021, 6:14:07 PM   [InstanceLoader] EnvModule dependencies initialized +15ms
[Nest] 37040   - 01/27/2021, 6:14:07 PM   [InstanceLoader] AuthModule dependencies initialized +1ms
[Nest] 37040   - 01/27/2021, 6:14:07 PM   [InstanceLoader] AppModule dependencies initialized +1ms
Error: swagger-ui-express tried to access express (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and 
unsound.

Required package: express (via "express")
Required by: swagger-ui-express@virtual:19a50d414ea61722ddd093e308f5fe02abbe176b31d122b78ae52821da2b56978b3fd7c3707f6f21a8e895f20857049d411eeb9bedcb3bcc
fc9b62ad5cb6c33a#npm:4.1.6 (via C:\xxxxxxx\.yarn\$$virtual\swagger-ui-express-virtual-5569fbddf2\0\cache\swagger-ui-express
-npm-4.1.6-1400f0d081-ded7c3cc5d.zip\node_modules\swagger-ui-express\)
Ancestor breaking the chain: @nestjs/swagger@virtual:2e4cb0595f9ad4225538d59e3595a6b5e6a8809d034737d43d9aa2e617b2caae65f33724658ce0a806c2cd8fb035c423acf
187fe2419ae608ab7e10644587687#npm:4.7.12
```

**Comment by jmcdo29** [comment]
Ah, so this is more of a request to update the `peerDependencies` and the metadata of the peerDependnecies of the `@nestjs/swagger` package, right?

**Comment by chriswoodle** [comment]
Not exactly, I can make that PR seperatly. This issue is because I am currently unable to see this error message I have shown you without making the modifications I have requested. I had to fork nest to add console.log in order to get these error messages:

https://github.com/chriswoodle/nest/commit/e138ab2d09a2a5abf9884e1ba3994178c942db78

**Comment by jmcdo29** [comment]
Hey @kamilmysliwiec could we possibly do something like `logger.fatal(e.message)` to log out the caught error message, but make it easily hide-able? In theory, this error shouldn't show up once everything is correctly configured in the first place.

**Comment by kamilmysliwiec** [comment]
In the best-case scenario, we should never see such errors thrown by the library. The bottleneck here is the way how Berry PnP resolves dependencies, and to support that, we gotta update packages. Once we have all optional/peer deps explicitly listed, this error should never appear again. Let's track this here https://github.com/nestjs/swagger/issues/1155

**Comment by chriswoodle** [comment]
> 
> 
> In the best-case scenario, we should never see such errors thrown by the library. The bottleneck here is the way how Berry PnP resolves dependencies, and to support that, we gotta update packages. Once we have all optional/peer deps explicitly listed, this error should never appear again. Let's track this here [nestjs/swagger#1155](https://github.com/nestjs/swagger/issues/1155)

While that would be true at some point in the future, logging the error would help discover these issues to begin with.
