### ISSUE TITLE
Proposal: adding an sample using event emitter 2 with NestJS

### ISSUE THREAD

**Issue by Tony133** [nestjs/nest#6262]
## Feature Request
Proposal adding an sample using event emitter 2 with NestJS ♥️

## What is the motivation / use case for changing the behavior?

In addition to the main guide of [event emitter2 ](https://github.com/EventEmitter2/EventEmitter2), it might be useful for beginners who are using it for the first time with  NestJS ♥️. Since I believe that the events part is an important part for every framework

**Comment by kamilmysliwiec** [comment]
We don't have examples for all `@nestjs/{..}` packages as some of them are so small that providing a dedicated example might be an overkill (hence, it's not a priority in this case). However, if you are interested and you have some time to contribute, feel free to create a PR with a new "example app" following code examples from the docs (to stay consistent) :)
