### ISSUE TITLE
Boot loop because of inexistent changes

### ISSUE THREAD

**Issue by gilneto8** [nestjs/nest#6271]
## Current behavior

`nest start --watch` ends up on a loop while checking for changed files. This started happening when I installed the `nexus-plugin-prisma` (on the `configurations/prisma` branch, everything worked, but now it doesn't). Yes, I know that it might seem the problem is with the plugin, but bear with me: the schema and the prisma client are being created correctly, but for some reason the application is recognizing inexistent changes. If I run `nest start` (without the `--watch` flag), the server initiates as expected and I can access the GraphQL playground and test the query I've created.

## Input Code

[Project on configurations/nexus branch, which is the one failing](https://github.com/gilneto8/loop-backend/tree/configurations/nexus).

To start the environment (confirm it's on the `configurations/nexus` branch):
- from the `infrastructure` folder: `docker-compose up`;
- from the `api` folder: `npm install ; npm run start:dev`;

## Expected behavior

Start the server normally, accessible through the playground, without looping on boot.

## Possible Solution

I don't have a possible solution, but I did try to use `autoSchemaFile` on the `GraphQLModule.forRoot` config options, pointing it to the schema created by the plugin (`src/__generated/schema.gql`), to no avail (`Query Root` non-existent, or something like that).

I've also checked [#5543](https://github.com/nestjs/nest/issues/5543) and tested `tsc --watch`, but the outcome is not the same as with `nest start --watch` (to test this, just run `npm run start:tsc`).

## Environment

Everything is on the project, but to simplify:

```
"dependencies": {
    "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/graphql": "^7.9.8",
    "@nestjs/platform-express": "^7.5.1",
    "@prisma/client": "^2.15.0",
    "graphql": "^15.5.0",
    "graphql-tools": "^7.0.2",
    "nexus": "^1.0.0",
    "nexus-plugin-prisma": "^0.28.0",
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@prisma/cli": "^2.15.0",
    "ts-node": "^9.0.0",
  }
```

- Node version: 12.20.0
- Platform:  Ubuntu 18.04.5 LTS
- IDE: JetBrains WebStorm 2021.1 EAP

Thanks in advance.

**Comment by Tony133** [comment]
Hi @gilneto8, If you are having difficulty I recommend that you use the [discord](https://discord.com/invite/G7Qnnhy) channel  for support.

**Comment by jmcdo29** [comment]
As discussed on Discord, this comes from `nexus` generating interfaces at runtime. Moving the generation script to a prebuild or something similar would probably be what you're looking for.
