### ISSUE TITLE
Validating and Converting Query params.

### ISSUE THREAD

**Issue by ahhkk** [nestjs/nest#6272]
I have defined a DTO to validate and convert incoming query params.
```ts
export class ScrollingDto {
    @ApiPropertyOptional({
        description: 'Number of items to skip',
        default: 0,
        nullable: true
    })
    @IsOptional()
    @Type(() => Number)
    @IsInt()
    skip?: number;

    @ApiPropertyOptional({
        description: 'Number of items to take',
        example: 20,
        nullable: true
    })
    @IsOptional()
    @Type(() => Number)
    @IsInt()
    take?: number;
}
```

And I've added the global validation pipe in `main.ts`.

```ts
app.useGlobalPipes(new ValidationPipe({ transform: true }));
```

But it returns Bad Request error - `skip must be an integer number` with this query:

```
?skip=0
```

I am not sure what I did wrong here. Hope to get any help on this.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
