### ISSUE TITLE
Unable to resolve the HttpModule dependency

### ISSUE THREAD

**Issue by igorasilveira** [nestjs/nest#6280]
## Current behavior
Following the `Axios` with the `HttpModule` tutorial on Next docs for a specific feature module, the dependencies are unable to be resolved.

```
Error: Nest can't resolve dependencies of the YoutubeService (?). Please make sure that the argument HttpService at index [0] is available in the YoutubeService context.
```

## Input Code

> Repo Link
[Reproducible Repo](https://github.com/igorasilveira/nest-server-test)

> YouTube Module
```ts
import { HttpModule, Module } from '@nestjs/common';
import { YoutubeController } from './youtube.controller';
import { YoutubeService } from './youtube.service';

@Module({
  imports: [
    HttpModule.register({
      timeout: 5000,
      maxRedirects: 5,
      baseURL: `https://youtube.googleapis.com/youtube/v3`,
      headers: {
        Accept: 'application/json',
      },
    }),
  ],
  controllers: [YoutubeController],
  providers: [YoutubeService],
  exports: [YoutubeService],
})
export class YoutubeModule {}

```

> YouTube Service
```ts
import { HttpService, Injectable } from '@nestjs/common';
import { AxiosResponse } from 'axios';
import { Observable } from 'rxjs';

@Injectable()
export class YoutubeService {
  constructor(private httpService: HttpService) {}

  async getMetrics(): Promise<Observable<AxiosResponse<any>>> {
    // return new Promise((resolve) => true);
    return this.httpService.get('/channels', {
      params: {
        part: 'snippet%2CcontentDetails%2Cstatistics',
        id: process.env.CHANNEL_ID,
        key: process.env.YOUTUBE_API_KEY,
      },
    });
  }
}


```

## Expected behavior
We should be able to use the registered HttpModule correctly from the YouTubeService.

## Environment

<pre><code>
Nest version: 7.5.4

 
For Tooling issues:
- Node version: v11.15.0
- Platform:  macOS BigSur

Others:

</code></pre>

**Comment by Tony133** [comment]
Hi @igorasilveira,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported. 

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by igorasilveira** [comment]
> Hi @igorasilveira, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.
> 
> However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

I added on to the original comment, thank you!

**Comment by jmcdo29** [comment]
This is not a bug. Please use our [Discord](https://discord.gg/nestjs) for Support. You may find some help in [our common errors documentation](https://docs.nestjs.com/faq/common-errors) as well. The issue here is a `YoutubeService` in an `imports` array. You can tell by the error looking in the "YoutubeService context"
