### ISSUE TITLE
Ability to use websocket SubscribeMessage in controllers

### ISSUE THREAD

**Issue by Tinadim** [nestjs/nest#6283]
## Feature Request
I think it would be very interesting if the websocket message subscription could be used in a similar fashion to what was done in [this library](https://www.npmjs.com/package/express-ws) and let us handle websocket messages in controllers. That said, please consider I'm new to websockets, and that might not fit the websocket model very well, being considered an anti-pattern or have any obvious drawbacks I'm missing - in witch case, just let me know and we can close this issue.

## Is your feature request related to a problem? Please describe.
Not really. I just think it would fit the module model better, so each area of the product could handle its own websocket message handlers.

## Describe the solution you'd like
It would be cool if we could decorate controller methods in a similar fashion to what is done for HTTP methods. Perhaps something like:

```
export class CatsController {
    /* the optional path in the decorator would be concatenated with other paths parts, such as the global prefix, 
     * module paths and controller paths
    @WS('some-path') 
    doSomething(client: Socket, data: DataDto) {
        ...
    }
}
```

In fact, I tried to do it myself.  I tried to create the method decorator, and checked how Nest iterates over modules and controllers, adding the listeners to express and thought about doing the same with websockets. 
If I understood correctly, I believe `SocketModule` and `WebSocketController` do a similar thing during app creation (iterating over modules), but unless I got the code wrong, I think the iteration only covers module providers - excluding controllers, and filtering by the ones that are decorated with `WebSocketGatway`, and since those two classes are instantiated when the application is created, I don't think we can extend them or change their behavior somehow.

## Teachability, Documentation, Adoption, Migration Strategy
See example above

## What is the motivation / use case for changing the behavior?
When you develop a Nest application, everything is organized in terms of modules, and incoming requests are handled in controllers. I think letting controllers handle websocket messages as well would help keeping the code organized and letting each module handle its own websocket messages.

**Comment by kamilmysliwiec** [comment]
We don't plan to change anything regarding this. In Nest, you should register your message listeners in Gateway classes. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
