### ISSUE TITLE
Mqtt message payload with data and info fields is trimmed

### ISSUE THREAD

**Issue by ckrawczynski** [nestjs/nest#6292]
## Current behavior
I'm using mqtt microservice transport layer, and my broker receives messages with payload object containing both data and info fields. Unfortunately payload field is injected only with data field.

The original data

```
const payload = context.getPacket().payload.toString()
```
consist of the whole payload data (with proper info and data fields).

## Input Code

```
mosquitto_pub -t 'topic' -m '{"data": {"key": "value"}, "info": {"key": "value"}}'
```

```ts
@Controller('signal-processor')
export class SPController {
  @MessagePattern('topic')
  async counter(
    @Payload() data: any,
    @Ctx() context: MqttContext,
  ): Promise<void> {
    console.log(data);
    console.log(context.getPacket().payload.toString());
  }
}
```

## Expected behavior

I want to see both info and data fields in payload.

## Environment

<pre><code>
Nest version: 7.5.4
 
For Tooling issues:
- Node version: 14.15.4
- Platform:  Linux

</code></pre>

**Comment by kamilmysliwiec** [comment]
Check out this article series https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-1-p3 (especially this one https://dev.to/nestjs/integrate-nestjs-with-external-services-using-microservice-transporters-part-2-3hgd)
