### ISSUE TITLE
NestJS with TypeOrm (Mysql) save unaccurate date in the database

### ISSUE THREAD

**Issue by soscler** [nestjs/nest#6294]
## Bug Report
NestJS with TypeOrm (Mysql) save unaccurate date in the database.
## Current behavior

Whilte testing a repository with typeorm, I noticed that date objects saved to the db are different from their source entities date values.

## Input Code

```ts
export class Project {
startDate: Date;
...
}

const expectedProject: Project = new Project( { startDate: new Date(), ... });
// expectedProject{ "startDate": "2021-02-01T18:55:02.843Z", ... })
const savedProject: Project = projectRepository.save(expectedProject);
// savedProject = { "startDate": "2021-02-01T18:55:03.000Z", ... }
expect(expectedProject).toEqual(savedProject); // This test fails
```
The test fails because the date returned from the db is different from the date in the expectedProject object.
The difference is barely noticable because it's in the milliseconds. The date saved in the db are rounded to the near second.
For e.g.:
2021-02-01T18:55:`02.843Z` will be 2021-02-01T18:55:`03.000Z` in the db.

## Environment

<pre><code>
Nest version: 7.5.4
NodeJS version: 14.15.4
MySQL version: 5.7.32

**Comment by kamilmysliwiec** [comment]
This issue is unrelated to NestJS framework.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
