### ISSUE TITLE
Client proxy close method is never called 

### ISSUE THREAD

**Issue by p-fedyukovich** [nestjs/nest#6296]
## Current behavior
All microservice clients implement `ClientProxy` interface which has `close()` method. This method is called inside `MicroservicesModule.close()` but I have not found any place where it's called, which means when application shuts down microservices clients are never closed. But some underlying client can rely on it which would lead to wrong behavior.

## Expected behavior
Instances of `ClientProxy` interface should be closed upon application shuts down

## Possible Solution
1. Amend `MicroservicesModule.close()` implementation in order to make it async with awaiting of all proxy clients are closed. 
1. Call `MicroservicesModule.close()` inside `NestApplication.dispose()`
## Environment

<pre><code>
Nest version: 7.6.9

 
For Tooling issues:
- Node version: 12  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 7.6.11
