### ISSUE TITLE
Route decorator affecting next route handlers

### ISSUE THREAD

**Issue by Kalluste** [nestjs/nest#6307]
## Current behavior
First route handler has route 'relations/:uuid' and the second route handler has a route 'profile'. When trying to request /profile I get an error saying:
{
    "statusCode": 400,
    "message": "Validation failed (uuid v4 is expected)",
    "error": "Bad Request"
}

It seems like the route decorator is somehow affecting the next route handler.  When the order of route handlers is changed the issue is fixed.

It seems like a bug...

## Input Code

```ts
    @UseGuards(JwtAuthGuard, RolesGuard, BusinessUserGuard)
    @Delete('relations/:uuid')
    @Roles('manager')
    removeUserRelationsInBusiness(
        @Param('uuid', new ParseUUIDPipe({ version: '4' })) uuid: string,
    ): Promise<User> {
        return null;
    }
    
    @UseGuards(JwtAuthGuard)
    @Get('profile')
    async getProfile(
        @ReqUser() user
    ): Promise<User> {
        return await this.usersService.getProfile(null);
    }
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Tony133** [comment]
Hi @Kalluste, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by rubiin** [comment]
@Kalluste you can drop queries like this on discord with a minimal reproduction link. 
From the looks of it looks like a routing problem, but if there was a minimal reproduction repo, i could be more precise

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
