### ISSUE TITLE
Compile() on TestingModule is being skipped

### ISSUE THREAD

**Issue by Edwardchorius** [nestjs/nest#6310]
SInce the code where I am experiencing this is a source private code I cannot share it and the reproduction would take a while I would like just to ask - has anyone experienced such a thing?

I have `const appAndFixture =  await Test.createTestingModule({
        imports: [SomeModule]
      })
      .compile()
      app = await appAndFixture.createNestApplication().init()`

Nevermind the chaining of functions. The problem is that **after compile() the rest is being skipped and it gets straight to the test** This means that we don't even get to the point of initialization of the app. The `compile()` doesn't get triggered as if there is a hidden `go to`. There are no errors no warnings nor anything useful in the logs. I have put a try/catch and still nothing. I even left a console.log() and it doesn't get triggered after compile(). Like I said - as if there is a hidden go to.

**Comment by jmcdo29** [comment]
As I mentioned on Discord already, please provide a [minimum reproduction repository](http://minimum-reproduction.wtf)

**Comment by kamilmysliwiec** [comment]
I haven't seen such an issue in the past. Please provide a minimum reproduction repository, otherwise, we won't be able to help you.
