### ISSUE TITLE
Validation not applied by global ValidationPipe

### ISSUE THREAD

**Issue by alsiola** [nestjs/nest#6322]
## Current behaviour
Validation behaviour is different when `ValidationPipe` is applied via `useGlobalPipes` or passed directly to a decorator, e.g. `@Body(ValidationPipe)`.

Specifically, when using:

```
class DTO {
  @IsNumber()
  age!: number;
}
```

this validation does not seem to run when the global `ValidationPipe` is used. I.e. a body of `{ age: 'a string' }` does not lead to a `400` error.

## Input Code
Please see minimal example at https://github.com/alsiola/test-nest-validation

## Expected behaviour
Location of `ValidationPipe` application has no impact on its behaviour.

## Environment

<pre><code>
Nest version: 7.5.1
 
For Tooling issues:
- Node version: Tested on Node v12.20.0
- Platform:  Tested on MacOS Big Sur 11.1

**Comment by kamilmysliwiec** [comment]
From the README file (of your repository):

> Demonstrates an issue with validation using ValidationPipe. My expectation is that both e2e tests in this repository should pass, **currently one fails**.

One fails because you're not applying the `ValidationPipe` to the testing application here https://github.com/alsiola/test-nest-validation/blob/master/test/app.e2e-spec.ts#L14

This:

```typescript
app = moduleFixture.createNestApplication();
app.useGlobalPipes(new ValidationPipe()); // < this is new
await app.init();
```
will fix your issue.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by aprilmintacpineda** [comment]
I'm encountering the same problem right now on an exam, the test is failing because the auto validation pipe is not working, if I add @UsePipe the test will pass. HOWEVER, on the actual server (when you run yarn start) the endpoint actually works as expected.

```
beforeEach(async () => {
  const module: TestingModule = await Test.createTestingModule({
    imports: [AppModule],
  }).compile();
  app = module.createNestApplication();
  app.useGlobalPipes(new ValidationPipe({ forbidUnknownValues: true }));
  await app.init();
});
```

Notice that I have `useGlobalPipes`.
