### ISSUE TITLE
how to integrate graphql schema (code first) and prisma schema in nest.js

### ISSUE THREAD

**Issue by simayi0322** [nestjs/nest#6326]
I am building api server using graphql in nestjs(code first).
also, I use prisma2.
when I used typeorm, I could integrate db schema and graphql schema using decorator
but, I can't integrate prisma2, graphql in nestjs(code first)

as single source of truth, I want to integrate

do you give me solution?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
