### ISSUE TITLE
@Inject 

### ISSUE THREAD

**Issue by ahmet-emrebas** [nestjs/nest#6328]
## Input Code

```
@Inject('NotProvidedToken')
```

## Expected behavior
Error Message: You are trying to inject 'NotProvidedToken'  that is not provided in the current scope. 

## Possible Solution
Verify the the parameter of the @Inject annotation is provided in the scope or not.

## Environment
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 14.15.4  
- Platform:  Windows

**Comment by jmcdo29** [comment]
This doesn't seem like a bug. If you think it is, please provide a [minimum reproduciton](http://minimum-reproduction.wtf) and I'll re-open this. Otherwise, please seek help on our [Discord](https://discord.gg/nestjs)
