### ISSUE TITLE
Security report on Socket IO

### ISSUE THREAD

**Issue by maxleboit** [nestjs/nest#6330]
Hello,

I am a user of Nest JS and I found a security issue from one of your dependency on socket.io 2.4 version. It is DOS attack affected

## Bug Report

You should improve the dependency of this package to avoid this risk.

**Comment by kamilmysliwiec** [comment]
We plan to update to Socket.io v3 in the next major release.

**Comment by maxleboit** [comment]
Perfect, 

Thanks for your quick answer.

Kind regards
