### ISSUE TITLE
Incorrect error message for unresolved dependencies with forward ref

### ISSUE THREAD

**Issue by TrejGun** [nestjs/nest#6331]
## Current behavior
error for unresolved dependencies with forward ref is incorrect
```
    Nest can't resolve dependencies of the BookingService (?, [object Object]). Please make sure that the argument dependency at index [0] is available in the BookingModule context.
```

## Input Code
```ts
  constructor(
    private readonly userService: UserService,
    @Inject(forwardRef(() => MerchantService))
    private readonly merchantService: MerchantService,
  ) {}
```

## Expected behavior
error should read
```
    Nest can't resolve dependencies of the BookingService (?, MerchantService). Please make sure that the argument dependency at index [0] is available in the BookingModule context.
```

## Possible Solution
unknown

## Environment

<pre><code>
Nest version: 7.6.11
 
For Tooling issues:
- Node version: v12.20.1
- Platform: win

Others:

</code></pre>

**Comment by Tony133** [comment]
Hi @TrejGun, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by TrejGun** [comment]
here it is
https://github.com/TrejGun/nestjs-unresolved-ref-bug

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in this commit https://github.com/nestjs/nest/commit/124afbbdc7042bec51d0cd38435b02d5e5c61721 and will be published as part of the next release

**Comment by TrejGun** [comment]
thanks
