### ISSUE TITLE
Incorrect typings at HttpServer.getRequestUrl at @nestjs/common

### ISSUE THREAD

**Issue by muturgan** [nestjs/nest#6338]
## Current behavior

Incorrect typings at HttpServer.getRequestUrl at @nestjs/common

## Input Code

```ts
getRequestUrl?(request: TResponse): string;
```

## Expected behavior

should pass a Request as param
at least at FastifyAdapter we can see:
```ts
public getRequestUrl(request: FastifyRequest): string
```

## Possible Solution

making a PR

**Comment by muturgan** [comment]
https://github.com/nestjs/nest/pull/6339

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/6339
