### ISSUE TITLE
Nest doesn't recompile when importing path defined in tsconfig "paths" 

### ISSUE THREAD

**Issue by romeerez** [nestjs/nest#6343]
## Bug Report

Nest doesn't recompile when importing path defined in tsconfig "paths".
I'm trying to have a "server" dir with nest.js backend and "shared" dir on the same level as "server" to keep shared with frontend code.

Full tsconfig for nest:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": ".",
    "incremental": true,
    "paths": {
      "@shared/*": [
        "../shared/*"
      ]
    }
  }
}
```

Just added "paths" to point to shared directory.

Somewhere in server I add such import:
```typescript
import { hello } from '@shared/hello';
```
And I'm calling `hello`, which just need to put a message to console, but it doesn't.

After making code change I can see in console that nest recompiled successfully, application is running, but when making request I see old console logs which I removed before, and no hello message.

After I remove that import statement, only then app recompiles correctly and starts to log actual messages.

Maybe it's a limitation that nest.js can not use such imports, but then it should result in an error.

The same behavior when trying to handle shared folder using tsconfig "references" - no ts error, but not recompiles.

## Environment

Nest version:
@nestjs/cli@^7.5.1
@nestjs/common@^7.5.1
@nestjs/config@^0.6.3
@nestjs/core@^7.5.1
@nestjs/platform-express@^7.5.1
 
For Tooling issues:
- Node version: v14.11.0
- Platform: Linux

**Comment by jmcdo29** [comment]
This seems like `tsc`'s file watcher isn't watching the file you expect it to. You can look into configuration options for it [here](https://www.typescriptlang.org/docs/handbook/configuring-watch.html)

Please provide a [minimum reproduction](http://minimum-reproduction.wtf)

**Comment by romeerez** [comment]
Here I created min reproduction repo: https://github.com/romeerez/nest-reproduce-external-import-bug
Here are actual changes to reproduce problem: https://github.com/romeerez/nest-reproduce-external-import-bug/commit/991dc552d8507a89693cf400332441e4de4ea265

As dist isn't saved to git, this repo won't compile at all.
Locally I have dist folder, and nest will use it without applying new changes in code.

I just want to reuse code somehow, tell me please if you know some other way to do it.

**Comment by kamilmysliwiec** [comment]
From what I can see, this issue doesn't seem to be related to NestJS, but rather to the TypeScript compiler configuration (`nest build` in a single-repo mode uses `tsc` under the hood), as @jmcdo29 mentioned above.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by romeerez** [comment]
Solution: importing modules from outside, using "references" in tsconfig or not, it may affect on structure inside `dist`.

By default nest is trying to start process with `dist/main.js`, but if your dist to has sub folders - find where is main and put it into `nest-cli.json`

For me adding this to nest-cli.json solved the issue:
```json
{
  ...
  "entryFile": "server/src/main"
}
```

thanks to @jmcdo29 who suggested to change `entryFile`!

**Comment by tecoad** [comment]
@romeerez saved my day.
