### ISSUE TITLE
asyncLocalStorage returns undefined if the request body is not empty (post, patch ...)

### ISSUE THREAD

**Issue by LoginovSO** [nestjs/nest#6345]
node v14.6.0
```

  "dependencies": {
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
```

returns undefined if the request body is not empty (post, patch ...)
when using async localStorage. run ()
but when using async localStorage.enter With() everything works fine

```
const asyncLocalStorage = new async_hooks.AsyncLocalStorage();


@Module({
    providers: [
        {
            provide: ASYNC_STORAGE,
            useValue: asyncLocalStorage,
        }
    ],
})
export class SomeModule {}
```

```
async function bootstrap() {
  app.use((req, res, next) => {
    const asyncStorage = app.get(ASYNC_STORAGE);
....
    const store = new Map().set('store', {
      foo
    });
    asyncStorage.run(store, () => {
       next();
    });
  });
}
```

```
export class JwtStrategy extends PassportStrategy(Strategy) {
    constructor(
        @Inject(ASYNC_STORAGE) private readonly asyncStorage: AsyncLocalStorage<Map<string, Record<string, any>>>
    ) {}

    async validate(payload: IAuthPayload)
    {
     const store= this.asyncStorage.getStore()?.get('store'); // undefined
```

**Comment by Tony133** [comment]
Hi @LoginovSO,
if you have difficulty you can use the [discord] channel (https://discord.com/invite/G7Qnnhy) for support.

Nest's Core Team uses GitHub to track bugs, feature requests, and potential improvements.

**Comment by LoginovSO** [comment]
the body parser is not working properly

**Comment by Tony133** [comment]
@LoginovSO Ok,
then I recommend that you leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you reported.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions as this doesn't seem to be the framework's issue. We are using GitHub to track bugs, feature requests, and potential improvements.
