### ISSUE TITLE
@grpc/grpc-js causes metadata to be omitted from ExecutionContext

### ISSUE THREAD

**Issue by Jaypov** [nestjs/nest#6350]
## Current behavior
When using `@grpc/grpc-js` on the server and constructing metadata with `@grpc/grpc-js` on client. added meta data is omitted from ExecutionContext 

When using `@grpc/grpc-js` on the server and constructing metadata with `grpc` on client. added meta data is correctly included ExecutionContext 

## Input Code

Minimal reproduction repo: [nestjs-grpc-bug-minimal-repo](https://github.com/Jaypov/nestjs-grpc-bug-minimal-repo )

Server
```ts
import { createParamDecorator, ExecutionContext } from '@nestjs/common';
import { Metadata, status } from '@grpc/grpc-js';
import { RpcException } from '@nestjs/microservices';

export interface IUserDecorator {
  clientId: string;
}

export const User = createParamDecorator(
  (data, context: ExecutionContext): IUserDecorator => {
    const metadata = context.switchToRpc().getContext() as Metadata;
    const { clientid } = metadata.getMap();

    if (!clientid) {
      throw new RpcException({
        code: status.UNAUTHENTICATED,
        message: 'clientId is required',
      });
    }

    return {
      clientId: clientid.toString(),
    };
  },
);
```
Broken request meta
```
// Client
import  *  as  GRPC  from  '@grpc/grpc-js';

const  meta = new  GRPC.Metadata();
meta.add("clientId", "dasd");

// produces
Metadata { internalRepr: Map { 'clientid'  => [Array] }, options: {} }
```

Working request meta
```
// Client
import  *  as  GRPC  from  'grpc';

const  meta = new  GRPC.Metadata();
meta.add("clientId", "dasd");

// produces
Metadata { _internal_repr: { clientid: [Array] }, flags: 0 }
```

## Expected behavior
I expect that you should be able to construct metadata using the `@grpc/grpc-js` package on the client side and be able to receive the meta inside the `ExecutionContext` on the server. Cannot continue to use `grpc` on the client and `@grpc/grpc-js` on the server as `grpc` is being depreciated

## Environment

<pre><code>
@nestjs/microservices: ^7.6.11
@nestjs/common: ^7.6.11

For Tooling issues:
- Node version: v14.2.0
- Platform:  Mac

</code></pre>

**Comment by Tony133** [comment]
Hi @Jaypov, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by Jaypov** [comment]
@Tony133 No problem, bug report update with a link to a minimal repo [nestjs-grpc-bug-minimal-repo](https://github.com/Jaypov/nestjs-grpc-bug-minimal-repo)

**Comment by jayMedicalChain** [comment]
FYI: if i connect to the server using `@grpc/grpc-js` directly by loading the protos with `@grpc/proto-loader` and then load the definitions / connect to server with `@grpc/grpc-js` metadata constructed with `@grpc/grpc-js` is accepted.

It is only with nests `ClientsModule` that constructing metadata with `@grpc/grpc-js` does not work

**Comment by kamilmysliwiec** [comment]
The current version isn't compatible with the `@grpc/grpc-js` package. This will change in v8 release that we're tracking here https://github.com/nestjs/nest/pull/6349

**Comment by Stefanone91** [comment]
I've updated my application to nest v8 but the problem seems not resolved.
Metadata got lost if using new `@grpc/grpc-js` library to create Metadata object

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
