### ISSUE TITLE
@Body generates a plane object instead of mapped class

### ISSUE THREAD

**Issue by vlio20** [nestjs/nest#636]
Hi,
I have the following controller:
```
  @Post()
  public async getGroups(@Req() req: AppRequest,
                         @Body(new ValidationPipe()) groupCreateDto: GroupCreateDto) {
    ...
  }
```

And here is the dto:
```
export class GroupCreateDto {

  private internalTypeId: number;

  @IsString()
  @IsNotEmpty()
  public readonly name: string;

  @IsString()
  @IsNotEmpty()
  public readonly typeId: string;

  public getInternalTypeId(): number {
    if (!this.internalTypeId) {
      this.internalTypeId = UtilsService.decodeId(this.typeId)
    }

    return this.internalTypeId;
  }
}
```

When the `groupToCreate` is being injected it's just a plain javascript object which only has the `name` and `typeId` fields on it. There is no `getInternalTypeId` method on this object.

Is it a bug?

**Comment by BMalaichik** [comment]
@vlio20
I am not sure it's a bug because this is about http data serialization\deserialization

your behavior can be easily reached via custom pipe, which takes plain object & create instance class based on it's props, kinda

```
@Post()
  public async getGroups(@Req() req: AppRequest,
                         @Body(new ValidationPipe(), new CastTypePipe(GroupCreateDto)) groupCreateDto: GroupCreateDto) {
    ...
  }
```


Pipe:

```
import { PipeTransform, Pipe, ArgumentMetadata } from '@nestjs/common';

@Pipe()
export class CastTypePipe implements PipeTransform<any> {
  public constructor(protected CastType: new () => BaseDto) { // 'newable' interface goes here

  }
  transform(value: any, metadata: ArgumentMetadata) {
    return new CastType(value);
  }
}

```

BaseDto to derive from:
```
export abstract class BaseDto {

    public constructor(props: any) {
       Object.assign(this, { ...props })
   }
}
```

**Comment by XGHeaven** [comment]
You need to enable `transform` option for ValidatePipe, `@Body(new ValidatePip({ transform: true }))`

**Comment by vlio20** [comment]
@BMalaichik , I think it is a bug  because when I am referring that a parameter is of a class type:
```
 @Body(new ValidationPipe()) groupCreateDto: GroupCreateDto
```

I am expecting that if I run `instanceOf groupCreateDto == GroupCreateDto` would return `true` - which in the current state will return `false`.

@XGHeaven, it worked! though I think that it should be part of the `@Body` annotation, WDYT?

@XGHeaven , is it possible to configure it globally (`transform: true `)?

**Comment by kamilmysliwiec** [comment]
Hi @vlio20,
This is an intended behavior.  
```
is it possible to configure it globally (transform: true)?
```
Sure.
```typescript
app.useGlobalPipes(new ValidationPipe({ transform: true }));
```
All available options are described in the new version of the docs: https://docs.nestjs.com/v5/ (Pipes section)

**Comment by vlio20** [comment]
@kamilmysliwiec , I have to say a bit odd to put a type of a class and to get a plain javascript object.
It is great that there is still an option to do it with the `ValidationPipe` but I think it's not the right place.
