### ISSUE TITLE
In-browser Nest

### ISSUE THREAD

**Issue by anthonyjlmorel** [nestjs/nest#6360]
## Is your feature request related to a problem? Please describe.
I work on a code base that is expected to be running in two environments:
- a browser
- Nodejs

Today we use a home-made framework that, depending on a target (browser or nodejs), we build target-specific strategies to get the main code running (such as file access is used by a HTTP strategy in browser, and a Nodejs fs strategy for Node).
Running into your framework, I see you have handled in a much more beautiful manner a lot of the issues we ran into (dependency injection etc.) and we would like to propose, if feasible, to allow Nestjs to execute into a browser environment (maybe not the whole framework, but enough to be useful).

## Describe the solution you'd like
I would like, first, to see at what point we could bring some of the Nestjs stuff browser-side, to avoid altering too much of a code-base. Things like:
- controllers
- dependency injection
- logging
- etc.

For instance, in our code base, when we build for a Nodejs Env., the client is served and communicate through an "http" strategy with the back end.
When we build for a Browser env, we inject a different strategy in charge of directly instantiating the requested service and calling it for the client (as the "core back end code" is embedded).

## Teachability, Documentation, Adoption, Migration Strategy
If don't think there would need an adoption or migration strategy. I would say that the "default" running mode of Nest would stay as today and if we wanted to embed it in another environment, we would implement "strategies" to cope with differences.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
