### ISSUE TITLE
Add an organization sponsor?

### ISSUE THREAD

**Issue by CatsMiaow** [nestjs/nest#6362]
Hi.
https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-organization

https://github.com/nestjs
It would be nice to add sponsors to the nestjs GitHub organization page above.

E.g https://github.com/django
![image](https://user-images.githubusercontent.com/1300172/107353949-f6407400-6b10-11eb-9221-f73905dd95c8.png)

When a user sponsoring an organization, it will also appear on their GitHub profile.
![image](https://user-images.githubusercontent.com/1300172/107353734-b6798c80-6b10-11eb-84a9-685f052bca98.png)

I want to have a nestjs icon that appears on my GitHub profile.

**Comment by kamilmysliwiec** [comment]
There are no plans to add it ATM. If anything changes, I'll definitely post about it here!
