### ISSUE TITLE
Nest is crashing when executing app methods in chain

### ISSUE THREAD

**Issue by stoleruradu** [nestjs/nest#6365]
## Current behavior

The invocation of `NestExpressApplication` and `INestApplication` methods in chain crashes the app on bootstrap phase.

![image](https://user-images.githubusercontent.com/10254524/107405574-263b4780-6b10-11eb-82b6-985136d9c922.png)

## Input Code

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { NestExpressApplication } from '@nestjs/platform-express';

(async function bootstrap() {
  const app: NestExpressApplication = await NestFactory.create(AppModule);

  await app
    .setGlobalPrefix('api')
    .disable('etag')
    .disable('x-powered-by')
    .listen(3000);

  console.log(`Server is listening on: http://localhost:${3000}`);
})();
```
## Minimal reproduction of the problem with instructions

- git clone https://github.com/stoleruradu/app-disable-crash-reproduction.git
- cd app-disable-crash-reproduction
- npm install
- npm run start:dev
## Expected behavior

The `this` reference returned from `NestExpressApplication`'s methods should point to `NestApplication` and not to `http adapter` itself.
## Possible Solution

Change the behavior of `createAdapterProxy` method from `NestFactoryStatic` to return a proxy after calling a `http adapter` method instead of returning the original result.
## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: v12.18.4  
- Platform: Mac  

</code></pre>

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/6366
