### ISSUE TITLE
ConfigModule Prisma .env not loaded and values are undefined at Google Cloud Run

### ISSUE THREAD

**Issue by RoyBkker** [nestjs/nest#6376]
## Current behavior
When running the code locally, everything works as it should be and according to the docs. I can access the process.env.DATABASE_URL. 
But when deploying to Cloud Run, the process.env.DATABASE_URL is not set for Prisma. 

Inside app.module.ts

```ts
import { MiddlewareConsumer, Module, NestModule } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { LoggerMiddleware } from './common/middleware/logger.middleware';
import { PaymentsController } from './payments/payments.controller';

import { PaymentsModule } from './payments/payments.module';
import { NotificationsController } from './notifications/notifications.controller';
import { PrismaService } from './prisma/prisma.service';
import { NotificationsService } from './notifications/notifications.service';

const ENV = process.env.NODE_ENV;
console.log({ ENV });
console.log(!ENV ? '.env.development.local' : `.env.${ENV}`);

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: !ENV ? '.env.development.local' : '.env.production',
      isGlobal: true,
    }),

    PaymentsModule,
  ],
  controllers: [AppController, NotificationsController],
  providers: [AppService, PrismaService, NotificationsService],
})
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(LoggerMiddleware).forRoutes(PaymentsController);
  }
}

```

Inside main.ts

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  console.log(`Starting server....... ${process.env.NODE_ENV}`);
  console.log(process.env.DATABASE_URL);

  const app = await NestFactory.create(AppModule, { cors: true });

  app.setGlobalPrefix('api');
  await app.listen(4001);
  console.log(`Server started at PORT 4001 and ${process.env.NODE_ENV}`);
}
bootstrap();
```

So, locally, all logs are showing the correct value. 
But when deploying to Cloud Run, 
The logs from app.module.ts are showing correct value, but the log inside main.ts is undefined. 
This log is undefined = console.log(process.env.DATABASE_URL);

NODE_ENV is set at the Cloud Run instance, so that is all working correctly.

## Expected behavior
Prisma should get the DATABASE_URL from .env.production and the console.log(process.env.DATABASE_URL); 
inside main.ts should not be undefined.

## Environment

<pre><code>
Nest version: 7.5.1
 
For Tooling issues:
- Node version: v15.5.1
- Platform:  Mac & Cloud Run

Others:

</code></pre>

**Comment by Tony133** [comment]
HI @RoyBkker, if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support. 
 
Nest's Core Team uses GitHub to track bugs, feature requests, and potential improvements.

**Comment by kamilmysliwiec** [comment]
This issue is unrelated to the framework. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
