### ISSUE TITLE
 How to use Nest Services in another App

### ISSUE THREAD

**Issue by delphit** [nestjs/nest#638]
<pre><code>
[ ] Regression
[ ] Bug report
[X] _Question_
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the motivation?
Does Nest.js have any popular practice for creating external workers? Where you can use all methods from PaymentsService or AccountService. But run worker separately from the main app (For example from PM2 in another process). 

I will be grateful if you explain me also how to build this in production. Because of worker maybe can be on another server.

_Current project structure:_ 
```
app/
├── modules/
│   ├── account
│   └── payments
├── workers/
│   ├── index.js
│   └── worker.ts
├── app.module.ts
```

</code></pre>

**Comment by weeco** [comment]
I think what you are looking for are microservices: https://docs.nestjs.com/v5/microservices/basics . Nest already comes with built in transport methods.

Hypothetically you can share the code across microservices, but it's not recommended. Let's say your worker is responsible for sending HTTP requests against an API, why would something but your worker need code for performing the HTTP request?

**Comment by kamilmysliwiec** [comment]
You could make use of **execution context** feature which basically allows you creating multiple applications that take advantage of Nest ecosystem. This is explained in the new version of the documentation - https://docs.nestjs.com/v5 (execution context chapter)

**Comment by delphit** [comment]
Thanks, @kamilmysliwiec, the issue can be closed!
