### ISSUE TITLE
Mqtt client interface

### ISSUE THREAD

**Issue by xtrinch** [nestjs/nest#6403]
I've imported the mqtt client interface from 
```
import { MqttClient } from '@nestjs/microservices/external/mqtt-client.interface';
```

So if I try to publish something with mqtt client, I am faced with a:

```
    this.mqttClient.publish(
      `radios/config-downstream/${radio.accessToken}`, 
      JSON.stringify(radio.config)
    );
```

```
[Nest] 6244   - 02/13/2021, 2:58:41 PM   [ExceptionsHandler] callback is not a function +817ms
TypeError: callback is not a function
    at ClientMqtt.publish (C:\Users\xtrinch\repos\sensor-dashboard-nestjs-backend\node_modules\@nestjs\microservices\client\client-mqtt.js:105:13)
    at RadioService.sendConfigToRadio (C:\Users\xtrinch\repos\sensor-dashboard-nestjs-backend\src\modules\radio\radio.service.ts:145:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at RadioController.sendConfig (C:\Users\xtrinch\repos\sensor-dashboard-nestjs-backend\src\modules\radio\radio.controller.ts:128:5)
    at C:\Users\xtrinch\repos\sensor-dashboard-nestjs-backend\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at C:\Users\xtrinch\repos\sensor-dashboard-nestjs-backend\node_modules\@nestjs\core\router\router-proxy.js:9:17
```

So I did a little digging in the code, and found a connect function, which does not exist in the type definitions.

So if I now try to publish like this:
```
    // @ts-ignore
    this.mqttClient.connect();
    this.mqttClient.publish(
      `radios/config-downstream/${radio.accessToken}`, 
      JSON.stringify(radio.config)
    );
```

It does not throw an error, however nothing is really emitted via MQTT.

Found the interface to also contain a reconnect function, which does not exist in the underlying code (https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-mqtt.ts):

https://github.com/nestjs/nest/blob/f26163df3ece725d3cfdea41c197d3dc87b147a6/packages/microservices/external/mqtt-client.interface.ts#L122

The only way I've found publishing works is via this:

```
    this.mqttClient.emit(
      `radios/config-downstream/${radio.accessToken}`, 
      JSON.stringify(radio.config)
    );
```

Not sure what the purpose of all the other exposed functions is then. And the docs on mqtt really only mention receiving messages.

**Comment by kamilmysliwiec** [comment]
`MqttClient` is an interface used internally, you should never use it in your application. Your `this.mqttClient` is an instance of the `ClientProxy` class (which is an abstraction over low-level, transport strategy specific clients).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
