### ISSUE TITLE
ValidationPipe on WebSockets calls twice and breaks connection

### ISSUE THREAD

**Issue by shaggyrec** [nestjs/nest#6407]
I have ValidationPipe that throws `WsException`:

```
@Injectable()
export class ValidationPipe implements PipeTransform {
    async transform(value: any, metadata: ArgumentMetadata): Promise<any> {
        ValidationPipe.assertIsNotEmpty(value);
        const { metatype } = metadata;

        const object = plainToClass(metatype, value);

        const errors = await validate(object);

        if (errors.length > 0) {
            throw new WsException(ValidationPipe.formatErrors(errors));
        }
    }

    private static assertIsNotEmpty(value: any) {
        if (Object.keys(value).length < 1) {
            throw new WsException('No payload provided');
        }
    }

    private static formatErrors (errors: any[]): string {
        return errors.map(error => {
            for (const key in error.constraints) {
                return error.constraints[key];
            }
        }).join(', ');
    }
```
I want to send the message to the client without disconnecting. But ws breaks the connection. 

I tried to implement custom filter like this

```
@Catch()
export class WsExceptionFilter extends BaseWsExceptionFilter{
    catch(exception: WsException, host: ArgumentsHost) {
        // @ts-ignore
        host.getClient().send(exception.message);
    }
}
```

Message was sent but connection was broken.

I see in console

```
 [Nest] 31   - 02/14/2021, 7:37:21 PM   [WsAdapter] undefined +963ms
api_1       | [Nest] 31   - 02/14/2021, 7:37:21 PM   [WsAdapter] Object:
api_1       | {
api_1       |   "code": "ERR_MULTIPLE_CALLBACK"
api_1       | }
api_1       |  +8ms
````

Is it bug? 
Do I have the option to avoid the disconnecting after validation error?

**Comment by Tony133** [comment]
Hi @shaggyrec, To be safe, I recommend that you leave a minimal reproduction of a clonable git repository so that the core team can evaluate the issue you reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by shaggyrec** [comment]
Ok. Sorry, I had to incapsulate problem before the write the topic.

I have changed the title. 

This is the repo https://github.com/shaggyrec/nestjs-ws-disconnect-on-error-

`transform` called twice. I tried to send `{"event":"testCmd", "data" 1}` and `{"event":"testCmd", "data":{"test":"data"}}`
In first call I have WsException and it works as I want. But on second call WS was disconnected

**Comment by kamilmysliwiec** [comment]
> transform called twice.

`transform()` will be called twice since you've applied the `ValidationPipe` on the method-level (`@UsePipes(new ValidationPipe())`). You should rather bind it to a specific method argument instead, and for this, you must use the `@MessageBody()` too https://docs.nestjs.com/websockets/gateways.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
