### ISSUE TITLE
Feature: Support multi store in cache module.

### ISSUE THREAD

**Issue by RomanBurunkov** [nestjs/nest#6419]
## Is your feature request related to a problem? Please describe.
Cache-manager which used by a nest cache module supports multi store configuration.
That can increase performance in some cases since cached data could be read from memory without having to access cache services like redis or memcached. Also that could make app more fault tolerance in case cache service went down or need to be restarted/updated.

E.g. 

```js
var multiCache = cacheManager.multiCaching([memoryCache, someOtherCache]);

// Sets in all caches.
// The "ttl" option can also be a function (see example below)
multiCache.set('foo2', 'bar2', {ttl: ttl}, function(err) {
    if (err) { throw err; }

    // Fetches from highest priority cache that has the key.
    multiCache.get('foo2', function(err, result) {
        console.log(result);
        // >> 'bar2'

        // Delete from all caches
        multiCache.del('foo2');
    });
});
```

## Describe the solution you'd like

At the moment cache module users `cacheManager.caching` to create an instance of cache manager.
New feature should make possible to pass an array of cache stores into a cache module to create a multi store cache manager with `cacheManager.multiCaching`.

## What is the motivation / use case for changing the behavior?

That could increase caching performance and also add some fault tolerance.

**Comment by jmcdo29** [comment]
Seems like this could be useful. Would you like to make a PR for this?

**Comment by RomanBurunkov** [comment]
Hi,

Despite change doesn't seem complicated I don't familiar with TS so not feel confident about creating a PR.

With JS I would do some simple check to determine which method to use to create a cache-manager instance.

```js
const factory = Array.isArray(opts) ? cacheManager.multiCaching : cacheManager.caching;
```

**Comment by jmcdo29** [comment]
You'd pretty much do the exact same in Typescript. So long as `opts` is typed to be `CacheStorage | CacheStorage[]` (replacing `CacheStorage` with the official type) it should be no problem. Maybe a few interface updates too to reflect the change. 

If you'd like some help pair programming it you can reach out to me on Discord at PerfectOrphan31#6003.

**Comment by RomanBurunkov** [comment]
Thanks @jmcdo29 

Will try make a PR and reach you in discord in case any help needed.

**Comment by kamilmysliwiec** [comment]
PR has been merged. This change will be published as part of v8 release

**Comment by vosferatu** [comment]
This was somehow removed from master

**Comment by DenisLutsky** [comment]
is this feature suported by NestJS?

**Comment by Henridv** [comment]
@DenisLutsky, @vosferatu it is part of [@nesjs/cache-manager](https://github.com/nestjs/cache-manager/)

**Comment by olivbau** [comment]
Do you have an example on how to use it?

**Comment by MagnusSafty** [comment]
> I dont see anything on this in the doc: https://docs.nestjs.com/techniques/caching Do you have an example of how to use it?

Did you figure it out? I have the same problem.

**Comment by b310L** [comment]
Not work register multi CacheModule in redis.
