### ISSUE TITLE
Mongoose OverwriteModelError when using discriminator 

### ISSUE THREAD

**Issue by dpolicastro** [nestjs/nest#6425]
## Current behavior
I'm trying to use Mongoose discriminator feature, but I'm getting this strange error even if I'm just importing the schema in the module definition. I don't know how I should approach, I'm doing the same thing described in the docs.
I'm using the repository pattern, so I inject the Model in the repository and then inject the repository in the service.
#### module.ts
```ts
@Module({
  imports: [
    MongooseModule.forFeatureAsync([
      { name: CornerShowerBox.name, useFactory: () => CornerShowerBoxSchema },
      { name: FrontalShowerBox.name, useFactory: () => FrontalShowerBoxSchema },
      {
        name: Product.name, useFactory: () => ProductSchema,
        discriminators: [
          { name: CornerShowerBox.name, schema: CornerShowerBoxSchema },
          { name: FrontalShowerBox.name, schema: FrontalShowerBoxSchema },
        ],
      },
    ]),
  ],
  controllers: [
    ProductController
  ],
  providers: [
    ProductService,
    ShowerBoxRepository
  ]
})
export class ProductModule { }
```
#### repository.ts
```ts
@Injectable()
export class ShowerBoxRepository {
  constructor(
    @InjectModel(CornerShowerBox.name) private cornerShowerBoxModel: Model<CornerShowerBoxDocument>,
  ) { }
...
}
```
#### Stack trace
```
OverwriteModelError: Cannot overwrite `CornerShowerBox` model once compiled.
    at Function.Model.discriminator (/Users/denis.policastro/dones/furnit/furnit-api/node_modules/mongoose/lib/model.js:1137:11)
    at /Users/denis.policastro/dones/furnit/furnit-api/node_modules/@nestjs/mongoose/dist/mongoose.providers.js:15:56
    at Array.forEach (<anonymous>)
    at addDiscriminators (/Users/denis.policastro/dones/furnit/furnit-api/node_modules/@nestjs/mongoose/dist/mongoose.providers.js:15:20)
    at Object.<anonymous> (/Users/denis.policastro/dones/furnit/furnit-api/node_modules/@nestjs/mongoose/dist/mongoose.providers.js:42:21)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/denis.policastro/dones/furnit/furnit-api/node_modules/@nestjs/mongoose/dist/mongoose.providers.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Expected behavior
Should inject the Model in the service without problems.

## Environment

<pre><code>
Nest version: 7.5.4
 
For Tooling issues:
- Node version: v12.18.3
- Platform:  Mac

</code></pre>

**Comment by jmcdo29** [comment]
Is this related to [this issues](https://github.com/nestjs/mongoose/issues/697)?

**Comment by dpolicastro** [comment]
@jmcdo29 Looks like it's the same problem! I was getting crazy with it 😆 

Looks like there is an opened pull request with the fix (https://github.com/nestjs/mongoose/pull/692), do you have any news about that?

**Comment by jmcdo29** [comment]
I mean, Kamil's asked for a reproduction and no one has provided one, so so far to me it looks blocked.

**Comment by dpolicastro** [comment]
> Is this related to [this issues](https://github.com/nestjs/mongoose/issues/697)?

@jmcdo29 The issue you pointed contains a valid repo that can be used for this purpose: https://github.com/lafeuil/nestjs-mongoose-test
what do you think?

**Comment by jmcdo29** [comment]
Linked them. Let's track things over there
