### ISSUE TITLE
Allow CacheInterceptor to be more extendable

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#6427]
## Is your feature request related to a problem? Please describe.

Currently the `CacheInterceptor` can be extended, but adding a new request method type to cache is difficult due to needing to re-wrte most of the method for `trackBy`.

## Describe the solution you'd like

Instead of doing the check in [this line](https://github.com/nestjs/nest/blob/master/packages/common/cache/interceptors/cache.interceptor.ts#L78) with a hardcoded string, we could move the `'GET'` string to an `allowedMethods` array that is `protected` so and do `!this.allowedMethods.includes(httpAdapter.getRequestMethod(request))` so that all that needs to happen is 

```ts
@Injectable()
export class CustomizedCacheInterceptor extends CacheInterceptor {
  protected allowedMethods = ['GET', 'HEAD'];
}
```

## Teachability, Documentation, Adoption, Migration Strategy

Docs would need to be updated, which I'd be happy to do.

## What is the motivation / use case for changing the behavior?

Caching currently skips `'HEAD'` requests, and if there's a heavy operation that the `GET` route is tied to then it re-computes that heavy operation.

## Other

Before you ask, yes I'm happy to make this modification and open a PR for it :smile_cat:

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/642
