### ISSUE TITLE
ValidationError - $value missing in error message

### ISSUE THREAD

**Issue by waji-io** [nestjs/nest#6431]
## Current behavior

When triggered a validation error, the resulting error message with the variable **$value** shows the variable name instead of the actual value. Other ValidationError variables still work, like $property or $contraint1

**Example**

```
"limit is too big. Maximum value is 250, but actual is $value"
```

## Input Code

```ts
@Max(250, { message: '$property is too big. Maximum value is $constraint1, but actual is $value' })
limit: number = 100;
```

## Expected behavior
Show the actual value of **$value** and not its name.

## Possible Solution
Worked previously...

## Environment

<pre><code>
Nest version: 7.6.11

 
For Tooling issues:
- Node version: 15.8.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the `class-validator` repository

**Comment by waji-io** [comment]
Created: https://github.com/typestack/class-validator/issues/921
