### ISSUE TITLE
cannot got graphql decorator

### ISSUE THREAD

**Issue by guotie** [nestjs/nest#6441]
In the docs: https://docs.nestjs.com/security/authentication#graphql

the currentuser is null, why?

```
@Query(returns => User)
@UseGuards(GqlAuthGuard)
whoAmI(@CurrentUser() user: User) {
  return this.usersService.findById(user.id);
}
```

it seems the GqlAuthGuard have not execute

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
