### ISSUE TITLE
More flexibility in setting log levels for built-in logging service

### ISSUE THREAD

**Issue by mowies** [nestjs/nest#6444]
## Feature Request

I have a feature request for the built-in logging service. Right now, you can adjust the logging behavior at app startup by setting the `logger:` option to `true/false`, `LogLevel[]` or to a custom logger implementation.
Why not also allow a single `LogLevel` in addition to the `LogLevel[]`? The default logger could have some logic behind so that the set log level and all levels above it are printed out when the logger is called.

**Example:**
```
const app = await NestFactory.create(ApplicationModule, {
  logger: 'warn',
});
await app.listen(3000);
```
The above code would result in log messages being printed out as if the logger was set up like this:
```
const app = await NestFactory.create(ApplicationModule, {
  logger: ['error', 'warn'],
});
await app.listen(3000);
```

## What is the motivation / use case for changing the behavior?
I thought this is a standard behaviour for programming frameworks and languages and was confused when I found out that it's not possible in NestJS. Python for example has similar behavior. ([source](https://docs.python.org/3/howto/logging.html))

**Comment by Tony133** [comment]
I think the logs part will be revised and improved in the next major Nest release ♥️ 🚀

**Comment by kamilmysliwiec** [comment]
As @Tony133 mentioned above, this is addressed in this PR https://github.com/nestjs/nest/pull/6349 and will be shipped as part of the next major release.
