### ISSUE TITLE
Microservice Client should allow to add caching module

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#6446]
## Is your feature request related to a problem? Please describe.
It would be great to be able to add caching to the .send function of microservice clients. And if there is a cached value, instead of sending a nats event, directly returning the cached data.

## Describe the solution you'd like
Would be great if this uses the cache module. 

The cache should have the option to set an expiration time, automatically generate a cache-id and manually set a cache id function per .send() to be able to clear the cache manually.

**Comment by kamilmysliwiec** [comment]
This should be fairly simple by extending the `ClientProxy` class and adding a caching logic on top (or using the `memoize` function, for instance). To register a custom client class, you can leverage the `customClass` feature about which you can learn more here https://github.com/nestjs/docs.nestjs.com/pull/1702

**Comment by MickL** [comment]
Thanks for the info, sounds good!
