### ISSUE TITLE
Run/Update Benchmarks folder on every pr/merge

### ISSUE THREAD

**Issue by diazgilberto** [nestjs/nest#6453]
## Is your feature request related to a problem? Please describe.
`NaN`

## Describe the solution you'd like
Based on this [answer](https://stackoverflow.com/a/48226084/4111920) from Kamil in Stackoverflow, he expressed that the benchmarks are run on every pr, however, when one navigates to the folder on Github, those folders are 2/3 years old. It is possible to update the benchmarks folder when the actions run?

## Teachability, Documentation, Adoption, Migration Strategy
`NaN`

## What is the motivation/use case for changing the behavior?
Transparency!

**Comment by jmcdo29** [comment]
Benchmarks are still being ran on each Pull Request. You can go to the PR -> Checks -> Codechecks -> Benchmarks to see the benchmarks for the PR.

@kamilmysliwiec it may be useful to find a way to update `benchmarks` directory on each release. Do you know if that would be possible?

**Comment by kamilmysliwiec** [comment]
As @jmcdo29 mentioned above, you can find current benchmarks for every PR opened (or closed) in this repository.

> @kamilmysliwiec it may be useful to find a way to update benchmarks directory on each release. Do you know if that would be possible?

Taking into account how many PRs we have for small updates/minor interface additions or even deps upgrades (renovate/dependabot), updating all benchmarks on each merge may not make too much sense. Still, we should update them once in a while and this is what I just did using `autocannon` https://github.com/nestjs/nest/blob/master/benchmarks/all_output.txt :)
