### ISSUE TITLE
unexpected route mapping when using a trailing slash

### ISSUE THREAD

**Issue by brain4711** [nestjs/nest#6454]
## Bug Report
This actually might not be a bad bug but, I encountered some , at least in my opinion, unexpected behavior.
## Current behavior
when coding a controller like this:
```typescript

@Controller('cats')
export class CatsController {
    @Get('/') // note the explicit slash here, trying to mean 'when the request url ends with a slash'
    getAll(){
        return ...
    }

    @Get('/:id')
    getById( @Param('id')id: string ){
        return ...
    }
}
```
with this the following routes get applied:
```
[Nest] 24372   - 19.02.2021, 16:26:56   [RouterExplorer] Mapped {/api/cats/:id, GET} route +1ms
[Nest] 24372   - 19.02.2021, 16:26:56   [RouterExplorer] Mapped {/api/cats, GET} route +2ms
```
Now when I send a request to `/api/cats/` (note the trailing slash here), my backend routes this request to the `getById` function with an undefined `id` parameter. Which is not exactly what I would expect.

With the current implementation, when I want to _get all_ data I would have to send my GET request to `.../api/cats` _(without trailing slash)_ but I am missing the feature to explicitly handle the request **with** a trailing slash and without any `:id` parameter.

It seems that the current implementation just ignores the trailing slash within the `@Get('/')` configuration for the `getAll` function and treats this specification equal to `@Get()` without slash

It confuses me that the current router applies equal mappings for `@Get('/')...` and `@Get()...` which are obviously two different cases. And it also doesen't make sense, that a request to `api/cats/` is treated equal to a request to `api/cats/:id` with undefined id paremeter

## Expected behavior
In my opinion it would feel more logical, when I define a controller method using `@Get('/')` that this function is mapped to the route `api/<controller-prefix>/` including a trailing slash. 

considering the above code-example I would rather expect, that the `getAll` function is called for a request to `.../api/cats/`

Becase with my code I explicitly want to distinguish between those two cases:
 - a request to `cats/` _(ending with a /)_ should be handled by `getAll(...)`
 - a request to `cats/...` _(followed by an id parameter)_ should be handled by `getById(...)`

Yes I am aware that in order to work, I just would have to omit the trailing slash in my request to access the `getAll` function, But the problem is, that in my project I cannot change the url of the request easily. Because I use the [@ngrx/data](https://ngrx.io/guide/data) framework, which automatically adds this trailing slash to each request.
## Possible Solution
Would require to change the implementation of the current router-mapping to apply a controller function with `@Get('/')` to a route including a trailing slash.

## Environment

<pre><code>
Nest version: 7.6.7

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction](http://minmum-reproduction.wtf) that shows what's going on.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
