### ISSUE TITLE
ESTree breaking build

### ISSUE THREAD

**Issue by maschinenlesbareregierung** [nestjs/nest#6457]
## Current behavior

Triggering 'npm run build' exits with a error from estree, originating from ESLint

```
node_modules/@types/eslint/index.d.ts:260:41 - error TS2724: '"/home/politik/projects/nestjs-meta-admin/node_modules/@types/estree/index"' has no exported member named 'ChainExpression'. Did you mean 'ThisExpression'?

260         ChainExpression?: (node: ESTree.ChainExpression & NodeParentExtension) => void;
                                            ~~~~~~~~~~~~~~~
node_modules/@types/eslint/index.d.ts:283:42 - error TS2694: Namespace '"/home/politik/projects/nestjs-meta-admin/node_modules/@types/estree/index"' has no exported member 'ImportExpression'.

283         ImportExpression?: (node: ESTree.ImportExpression & NodeParentExtension) => void;
                      
```

## Input Code

```json
{
  "name": "nestjs-meta-admin",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:watch": "nodemon --config nodemon.json",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "db:sync": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js schema:sync"
  },
  "dependencies": {
    "@malereg/typeorm-model-urls": "git+ssh://git@github.com/maschinenlesbareregierung/typeorm-model-urls.git",
    "@nestjs/common": "^7.6.11",
    "@nestjs/core": "^7.6.11",
    "@nestjs/platform-express": "^7.6.11",
    "@nestjs/swagger": "^4.7.13",
    "@nestjs/typeorm": "^7.1.5",
    "@nestjsx/crud": "^5.0.0-alpha.3",
    "@nestjsx/crud-typeorm": "^5.0.0-alpha.3",
    "admin-bro": "^3.4.0",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-formidable": "^1.2.0",
    "pg": "^8.5.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3",
    "swagger-ui-express": "^4.1.6",
    "typeorm": "^0.2.30"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.5",
    "@nestjs/schematics": "^7.2.7",
    "@nestjs/testing": "^7.6.11",
    "@types/express": "^4.17.11",
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.31",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.15.0",
    "@typescript-eslint/parser": "^4.15.0",
    "eslint": "^7.19.0",
    "eslint-config-prettier": "7.2.0",
    "eslint-plugin-prettier": "^3.3.1",
    "jest": "^26.6.3",
    "nodemon": "^2.0.7",
    "prettier": "^2.2.1",
    "supertest": "^6.1.3",
    "ts-jest": "^26.5.1",
    "ts-loader": "^8.0.16",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "4.1.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

## Expected behavior

I expect the build to finish

## Environment

Nest version:7.6.11

For Tooling issues:
- Node version: 15.15.1  
- Platform:  Mac

Others:
I get a build result that I can successfully start witn npm run start:prod

**Comment by jmcdo29** [comment]
I'm not able to reproduce this locally. Can you provide a reproduction? It looks like it may not be related to Nest.

**Comment by maschinenlesbareregierung** [comment]
I was wrong about the OS. its the Linux Ubuntu box I am working on. 

It might be releated to the typeorm model I am using. It is in a own repo. MIght that be a problem? the lockfile shows different versions for the estree module

**Comment by jmcdo29** [comment]
I tried this in a fresh docker environment, node 15.9 instead of 15.15, but everything else shows the issue isn't coming from Nest. Do you have a minimum reproduction?

**Comment by maschinenlesbareregierung** [comment]
Ill try to get that together tomorrow. Thanks

**Comment by maschinenlesbareregierung** [comment]
i gave you access to

**Comment by jmcdo29** [comment]
Hmm, I'd prefer a public [minimum reproduction](http://minimum-reproduction.wtf) if that is possible. If not, it can be pretty difficult to figure out where the bug is and who it should be reported to.

**Comment by maschinenlesbareregierung** [comment]
is there a way to disable eslint for nest in general?

**Comment by jmcdo29** [comment]
You can uninstall it. I'm not sure why it's the build command for you is trying to build eslint related code in the first place

**Comment by maschinenlesbareregierung** [comment]
i expected that to be a part of nestjs build ;)

**Comment by jmcdo29** [comment]
Not really. The build should be building your `src` code (your ts files) and using the `d.ts` files that your code depends on. The only reason I could think of it looking for `estree` is if for whatever reason in a `ts` file you import `eslint`. Otherwise, it shouldn't even be looking at those files

**Comment by maschinenlesbareregierung** [comment]
my typeorm module is based on pure typeorm and in a specific repo. 

Do I need to base that on the nestjs variant maybe?

**Comment by maschinenlesbareregierung** [comment]
I found the source of the bug: my child typeorm had version 0.2.15, latest nestjs/typeorm has .31 matching both versions fixes it. I assume these minor versions have a different version of eslint (its just typing errpr after all) or estree and here we go. 

mathcing the versions makes all fine. 

Thanks for the help

**Comment by jmcdo29** [comment]
> Do I need to base that on the nestjs variant maybe?

Shouldn't need to, no. There's no "this is a NestJS project" generally speaking. Just making use of the packages and compiling typescript to JavaScript. Maybe using the `nest-cli.json` but that's really it.

> I found the source of the bug: my child typeorm had version 0.2.15, latest nestjs/typeorm has .31 matching both versions fixes it. I assume these minor versions have a different version of eslint (its just typing errpr after all) or estree and here we go.

Ah, glad you found it. Next time, try to provide a minimum reproduction from the get-go.

**Comment by in-live-md** [comment]
I had the same issue - and I believe its related to version of typescript used by the cli. npm list typescript
```api@0.0.1 /Users/Documents/proj/api
├─┬ @nestjs/cli@7.5.6
│ └── typescript@4.1.5```
When I back it up to @7.5.1 problem goes away - the version of typescript for the cli is then 3.9.9 - so maybe a typescript 4 incompatibility?

**Comment by jyutzio** [comment]
I encountered the same issue while trying to update one of my apps that I hadn't touched for about 6 months. It was really doing my head in.

```bash
$ npx nest build
node_modules/@types/eslint/index.d.ts:260:41 - error TS2724: '"/home/jyutzio/src/app/node_modules/@types/estree/index"' has no exported member named 'ChainExpression'. Did you mean 'ThisExpression'?

260         ChainExpression?: (node: ESTree.ChainExpression & NodeParentExtension) => void;
                                            ~~~~~~~~~~~~~~~
node_modules/@types/eslint/index.d.ts:283:42 - error TS2694: Namespace '"/home/jyutzio/src/app/node_modules/@types/estree/index"' has no exported member 'ImportExpression'.

283         ImportExpression?: (node: ESTree.ImportExpression & NodeParentExtension) => void;
                                             ~~~~~~~~~~~~~~~~

Found 2 error(s).
```

My understanding is that the @types/eslint package requires a specific version of @types/estree. But in @types/eslint's package json it has the following:

```json
    "dependencies": {
        "@types/estree": "*",
        "@types/json-schema": "*"
    },
```

I solved it by adding the following package:

```bash
npm i -D @types/estree@^0.0.45
```

I spent a lot longer than I would like to admit figuring this out. I still don't know where exactly things went wrong but I'm glad to have it solved and hopefully this can help others.

**Comment by kamilmysliwiec** [comment]
As this doesn't seem to be related to the framework, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
