### ISSUE TITLE
{"statusCode":404,"message":"Cannot GET /","error":"Not Found"}

### ISSUE THREAD

**Issue by vasaman** [nestjs/nest#6458]
my `app.module.ts```import { Module } from '@nestjs/common';
import { CarsModule } from './cars/cars.module';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Cars } from './cars/cars.entity';
import { AppController } from "./app.controller";
import { AppService } from "./app.service";

@Module({
  imports: [
      TypeOrmModule.forRoot({
      type: 'postgres',
      host: 'localhost',
      port: 5432,
      username: 'postgres',
      password: '',
      database: 'transportation',
      entities: [Cars],
      synchronize: true,
    }),
    CarsModule
  ],
  providers: [ AppService ],
  controllers: [ AppController ],
})
export class AppModule {}

> 

> 

> my app.controller,ts
`import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service'
 
@Controller()
export class AppController {
  constructor(private readonly appService : AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}

> 

> 

> my app.service.ts
``import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  getHello(): string {
    return 'Hello World!';
  }
}

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction](http://minimum-reproduction.wtf)

**Comment by vasaman** [comment]
> Please provide a [minimum reproduction](http://minimum-reproduction.wtf)

When i m navigating root director

Localhost:3000 

I am getting error {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}

**Comment by Tony133** [comment]
Hi @vasaman,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

**Comment by vasaman** [comment]
> Hi @vasaman, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.
sorry i didnt understand
here is url of repo
https://github.com/vasaman/nestjs-.git

**Comment by jmcdo29** [comment]
This is not a minimum reproduction. You have a database dependency (TypeORM) and no way for us to easily start a database (like a docker-compose file). 

Anyways, after setting up a docker-compose and running the database I can't get the same error you do. `curl http://localhost:3000/` returns a `200` status code and `Hello World!` in the terminal as expected.

**Comment by velvetrevolver** [comment]
For those who can have a 404 for an existing mapped route, you have to know that on some boilerplates there is a api prefix "api" configured in app.config.ts : 
http://localhost:3000/api/
