### ISSUE TITLE
build:dev not working

### ISSUE THREAD

**Issue by DanielRuf** [nestjs/nest#646]
It throws an error because of `gulp.packages` (when we use gulp 4).

is this even a method of gulp (3)? I found no resources or examples which use `gulp.packages()`.

**Comment by DanielRuf** [comment]
Did you try it with Node.js 10? I got issues on Windows 10 when forking and installing the project and gulp is not globally installed. Still `gulp.packages` is not working here.

**Comment by kamilmysliwiec** [comment]
I'm using latest LTS 8.11.x

**Comment by DanielRuf** [comment]
Well, I'm using Node.js 10.0.0 stable ;-)

**Comment by DanielRuf** [comment]
> Did you try it with Node.js 10? I got issues on Windows 10...

**Comment by wbhob** [comment]
This needs to be tested with Node.JS v10, *espescially* before it goes into LTS.

**Comment by kamilmysliwiec** [comment]
Fixed in 5.2.0
