### ISSUE TITLE
NestJS - CircularDependencyException [Error] when using two repositories in one service - NestJS

### ISSUE THREAD

**Issue by sz-adminuser** [nestjs/nest#6462]
## Current behavior
I have two entities, with a one to one relationship.  I want to manage these from the same service with two repositories.  One is custom, one is the generic.  The repositories are injected into the service and give an CircularDependencyException error when I try and run the migration generation.

## Input Code

```
Error during migration generation:
CircularDependencyException [Error]: A circular dependency has been detected inside @InjectRepository(). Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()". Also, try to eliminate barrel files because they can lead to an unexpected behavior too.
```

Service:
```
  constructor(
    @InjectRepository(CustomerRepository) private readonly customerRepository: CustomerRepository,
    @InjectRepository(CustomerDetails) private readonly customerDetailsRepository: Repository<CustomerDetails>,
)
```

Module
```
@Module({
  imports: [
    TypeOrmModule.forFeature([Customer, CustomerRepository, CustomerDetails ]), 
```

Customer
```
@ChildEntity()
export abstract class Customer extends Person {
  @OneToOne(() => CustomerDetails, customerDetails => customerDetails.customer, {cascade: true})
  protected customerDetails?: CustomerDetails;
....
```

Person
```
@Entity({ name: 'person'})
@TableInheritance({column: {type: 'varchar', name: 'type'}})
export abstract class PersonProps {

  @PrimaryGeneratedColumn()
  public readonly id!: number;
}
```

CustomerDetails

```

@Entity({ name: 'customer_details'})
export class CustomerDetails {
....
  @OneToOne('Customer', 'customerDetails', {nullable: false})
  @JoinColumn({ name: 'customer_id' })
  public customer!: Customer;

  @Column( {nullable:false, name: 'customer_id'})
  public customerId!: number;
....
```
## Environment

<pre><code>
Nest version: 7.1

 
For Tooling issues:
- Node version: 12.18  
- Platform:  Windows

**Comment by Tony133** [comment]
Hi @sz-adminuser , I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
