### ISSUE TITLE
Applying of Middleware to controller with prefix array cause build fail  UnhandledPromiseRejectionWarning: TypeError: path.charAt is not a function

### ISSUE THREAD

**Issue by zemlakov** [nestjs/nest#6463]
## Current behavior
Applying of Middleware to controller with prefix array cause  build fail

<pre><code>
(node:2070) UnhandledPromiseRejectionWarning: TypeError: path.charAt is not a function
    at Object.addLeadingSlash (/Users/user/Documents/website/node_modules/@nestjs/common/utils/shared.utils.js:25:48)
    at RoutesMapper.validateGlobalPath (/Users/user/Documents/website/node_modules/@nestjs/core/middleware/routes-mapper.js:45:39)
    at /Users/user/Documents/website/node_modules/@nestjs/core/middleware/routes-mapper.js:36:28
    at Array.map (<anonymous>)
    at /Users/user/Documents/website/node_modules/@nestjs/core/middleware/routes-mapper.js:35:23
    at Array.map (<anonymous>)
    at RoutesMapper.mapRouteToRouteInfo (/Users/user/Documents/website/node_modules/@nestjs/core/middleware/routes-mapper.js:34:14)
    at MapIterator.iteratee (/Users/user/Documents/website/node_modules/@nestjs/core/middleware/builder.js:50:40)
    at MapIterator.next (/Users/user/Documents/website/node_modules/iterare/lib/map.js:13:39)
    at FlattenIterator.next (/Users/user/Documents/website/node_modules/iterare/lib/flatten.js:20:44)
(node:2070) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2070) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

</code></pre>

## Expected behavior
Applying of Middleware to controller with prefix array successfully works.

## Minimal reproduction of the problem with instructions

<pre><code>
// store middleware
@Injectable()
export class StoreMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction) {
    console.log(`Request...`);
    next();
  }
}

// home-page module
@Module({
  controllers: [HomePageController]
})
export class HomePageModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(StoreMiddleware)
      .forRoutes(HomePageController);
  }
}

// home-page controller
@Controller(['ch', 'de', 'en', 'pt', 'dk', 'se'])
export class HomePageController {

  @Get()
  getPage() {
    return 'home-page';
  }
}

// app module
@Module({
  imports: [
    HomePageModule
  ]
})
export class AppModule {}

</code></pre>

## Possible Solution

If replace .forRoutes(HomePageController); with directly specific routes prefixes it works.
<pre><code>
// home-page module
@Module({
  controllers: [HomePageController]
})
export class HomePageModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(StoreMiddleware)
      .forRoutes('ch', 'de', 'en', 'pt', 'dk', 'se');
  }
}
</code></pre>

## Environment

<pre><code>
Nest version: 7.5.4
 
For Tooling issues:
- Node version: v12.16.3
- Platform:  Mac
</code></pre>

**Comment by Tony133** [comment]
Hi @zemlakov, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by zemlakov** [comment]
Hi, @Tony133 thanks for advice.

Here is repo. with minimal reproduction project https://github.com/zemlakov/nest-website-issue

In current configuration it is failing on compilation. 

In src/home-page/home-page.module.ts at L:12 currently specified controller name (as it described in documentation)

If replace .forRoutes(HomePageController); with .forRoutes("ch", "de", "en", "pt", "dk", "se") - with prefixes from that controllers everything works fine.

**Comment by jmcdo29** [comment]
I'm able to confirm this is a bug. Probably having to do with the `core/middleware/routes-mapper` file.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in 7.6.13
