### ISSUE TITLE
Nestjs MVC Architect - Redirect inside Controller>Method that have @Render decorator

### ISSUE THREAD

**Issue by euclid1990** [nestjs/nest#6466]
Hello everyone, I have a question about Nestjs MVC. 

### Problem
The followings is my code: (A feature for reset password with token string in url param: auth/reset-password/abcxyz)

```typescript
  @Get('reset-password/:token')
  @Render('auth/reset-password')
  async getResetPassword(@Req() request: Request, @Res() response: Response, @Param() params) {
    try {
      await this.authService.validatePasswordReset(params.token);
      return { input: request.flash('input'), message: request.flash('message') };
    } catch (err) {
      if (err instanceof InvalidPasswordResetTokenException) {
        request.flash('message', err.getMessage());
        return response.redirect('/auth/reset');
      }
    }
  }
```
If I using `return response.redirect('/auth/reset');` like above and err is instance of `InvalidPasswordResetTokenException`, Nest output error:
```
_http_outgoing.js:535
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:535:11)
    at ServerResponse.header (/Users/euclid/Projects/onbai.net/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/euclid/Projects/onbai.net/node_modules/express/lib/response.js:170:12)
    at done (/Users/euclid/Projects/onbai.net/node_modules/express/lib/response.js:1008:10)
    at /Users/euclid/Projects/onbai.net/node_modules/nunjucks/src/environment.js:39:5
    at RawTask.call (/Users/euclid/Projects/onbai.net/node_modules/asap/asap.js:40:19)
    at flush (/Users/euclid/Projects/onbai.net/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
```
- Discord link: https://discord.com/channels/520622812742811698/520649487924985885/813103177158492221 
- Minimum Reproduction Git:  https://github.com/euclid1990/nestjs

### Cause
I think maybe ` @Render` decorator is executed after `response.redirect` run ??? And 2 methods is conflicted !

### Expect
How to avoid it error while I still want to:
- Use  `@Render` decorator alternative `response.render` function in controller=>method body ?
- Redirect to another action inside controller>method using `@Render` decorator !

**Thanks for reading it !**

**Comment by jmcdo29** [comment]
Looks like it's not just `redirect`, but in general if `@Render()` is on a route, and `@Res()` is injected, Nest does not go "hands off" of the request as it normally does. @kamilmysliwiec I'd assume this is a bug, as we'd only want to not be "hands off" if the `{ passthrough: true }` is passed, right?

**Comment by kamilmysliwiec** [comment]
>  if @Render() is on a route, and @Res() is injected, Nest does not go "hands off" of the request as it normally does

Nest does not go "hands-off" not only for `@Render()`, but also when `@Redirect()` or `@Sse()` is applied. The reason is that we wanted to allow people assigning `locals` to `res` objects within "render" methods so they can use them in templates (for example, in njk templates). We might either change this since now `passthrough` option is available (but this will introduce a breaking change) or just update the docs (we actually don't mention `@Render()` decorator for dynamic template rendering either way https://docs.nestjs.com/techniques/mvc#dynamic-template-rendering).

**Comment by euclid1990** [comment]
@kamilmysliwiec Repeat @Res() in all Controller.method is boring, so is it possible to inject Response into Controller.constructor like request ?
```typescript
export class ABCController {
  constructor(@Optional() @Inject(REQUEST) protected request: Request) {}
}
``` 
I want to create protected variable like response, and call response.render in any method that I want ?

**Comment by kamilmysliwiec** [comment]
@euclid1990 you can define a controller as request-scoped https://docs.nestjs.com/fundamentals/injection-scopes#controller-scope https://docs.nestjs.com/fundamentals/injection-scopes#request-provider

**Comment by vuongnv-0085** [comment]
@kamilmysliwiec It only can inject request, and can not inject response object ?

**Comment by kamilmysliwiec** [comment]
You can extract the response object from the request (`request.res`)

**Comment by euclid1990** [comment]
@kamilmysliwiec Special thanks !
