### ISSUE TITLE
@Controller is deprecated

### ISSUE THREAD

**Issue by menme95** [nestjs/nest#647]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ X ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I'm using nest v5 migrating a old code, decorator @Controler is deprecated but it appears in the Documentation. I don't know how to change the @Controller to @Injectable. Where can I found an example? 

## Environment
Nestjs 5.0.0.beta8
<pre><code>
 

</code></pre>

**Comment by kamilmysliwiec** [comment]
`@Controller()` isn't deprecated. :)

**Comment by menme95** [comment]
Oh, yes... It was Component and I don't know read, I'm so sorry
