### ISSUE TITLE
Doc | Get started

### ISSUE THREAD

**Issue by abelardolg** [nestjs/nest#6486]
Hi there,

I am a newbie with Nest. 

When I read the Get Started section, I miss a section about routing.

I created an app from scratch and without doing it, I have a path route ("/").

IMHO, the doc should be guided step by step by using the first elements to make a web app. 
Firstly, you start by explaining the main. It's OK.
Secondly, you continue with controllers; but..wait!, where's the route section explained here?? After main, you should explain module and then...routes! Finally, you should continue with controllers and so on.

Hope it helps!

Happy coding & best regards.

**Comment by abelardolg** [comment]
What I would like to say in my last comment, is that the steps to create a specific file to contain routes should be mentioned in your doc. This explanation should have its own section, isolated by the controllers section.

We should decouple routes from our controllers and leave them inside a separated files as controllers, services and so on.

Best regards.

**Comment by Tony133** [comment]
Hi @abelardolg, if you have difficulty using Nest you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

Nest's core team uses GitHub for bugs, features, and regression.

For the routing part you can see [here](https://docs.nestjs.com/controllers) in the routing section

For the next time for what concerns the documentation of Nest open the issues [here](https://github.com/nestjs/docs.nestjs.com)

I hope I was helpful :-)

**Comment by abelardolg** [comment]
Hi @Tony133 
Thanks for your comment.

I suggest you to show a link in the tutorial to that site where issues related to the documentation have to be creaed.

I saw the section about routing. I will create an issue at that site to suggest an improvement about this section.

Best regards.

**Comment by jmcdo29** [comment]
Closing this out as the question was asked in the docs repo :)
