### ISSUE TITLE
Microservice errors are not emitted to client (RpcExceptionsHandler)

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#6496]
## Current behavior
When using `ClientProxy.send()` and the other microservice throws an error `throw new Error('hello world')`, the other microservice correctly throws an `RpcException`:

> [RpcExceptionsHandler] hello world

But the client receives an unspecified error without the message:

> { status: 'error', message: 'Internal server error' }

## Input Code
Client app:
```ts
this.natsClient.send('mysubject', {}).toPromise();
```

Microservice app:
```ts
@Controller()
export class MyController {

  @MessagePattern('mysubject')
  async myTester(): Promise<void> {
    throw new Error('hello world');
  }
}
```

To get around this I would need to wrap all my functions, which is very unhandy:

```ts
  @MessagePattern('mysubject')
  async myTester(): Promise<void> {
    try {
       throw new Error('hello world'); // This is actually a complex function that may throw an error
    } catch (e) {
       throw new RpcException('hello world');
    }
  }
```

This would also throw an RpcException in the microservice but also the client receives the RpcException with the message.

## Expected behavior
As with http controllers throwing an `Error` automatically returns a HttpException to the http request. Docs:

> When an exception is unrecognized (is neither HttpException nor a class that inherits from HttpException), the built-in exception filter generates the following default JSON response

I would expect a microservice to also automatically throw an `RpcException` with the defined message if the exception is unrecognized (is neither `RpcException` nor a class that inherits from `RpcException`)

**Comment by kamilmysliwiec** [comment]
See this PR https://github.com/nestjs/nest/pull/5710 and this convo https://github.com/nestjs/nest/issues/5694

**Comment by MickL** [comment]
Could you add a sentence to this topic? The PR and the issue are a little bit like chinese to me. Also they are merged a year ago but I am on the latest nestjs version.

**Comment by MickL** [comment]
Are they even related to what I described?

**Comment by kamilmysliwiec** [comment]
> Also they are merged a year ago but I am on the latest nestjs version.

The PR was merged 23 days ago.

> Are they even related to what I described?

That's the exact same issue.
