### ISSUE TITLE
Disconnected from RMQ

### ISSUE THREAD

**Issue by harshk1311** [nestjs/nest#6505]
==========================================================
Project 1
`@Module({
  imports: [ClientsModule.register([
    {
      name: 'USER',
      transport: Transport.RMQ,
      options: {
        urls: [aqmpConUrl],
        queue:aqmpMessageQueue ,
        queueOptions: {
          durable: false
        },
      },
    },
  ])
    ,TypeOrmModule.forFeature([RegistereduserRepository])],
  controllers: [UsersController],
  providers: [UsersService]
})
export class UsersModule { }`

above code is of user.module.ts
---------------------------------------------------------------------------------------------------
`@Controller('users')
export class UsersController {

    constructor(private usersService: UsersService,
        @Inject('USER') private readonly client:ClientProxy
        ) { }

    @Get('/:id')
    getUserById(@Param('id', ParseIntPipe) id: number): Promise<Registereduser> {
        this.client.emit('hello','Hello Test')
        return this.usersService.getUserById(id);
    }

}`

this is code of user.controller.ts
=====================================================================
Project 2

`const app = await NestFactory.createMicroservice(AppModule, {
      transport: Transport.RMQ,
      options: {
        urls: [aqmpConUrl],
        queue: aqmpMessageQueue,
        prefetchCount: 1,
        noAck: false,
        queueOptions: {
          durable: true,
        }
      },
        ],
      })
    });

    app.listen(() => {
      console.log("Message Server microservice started...");
    });`

this is code of main.ts
---------------------------------------------------------------------------------------------------

`@EventPattern('hello')
  async getUser(data :any){
    console.log(data)
  }`

this is code of user.controller.ts
----------------------------------------------------------------------------------------------------
==============================================================================
where i m wrong 
 i facing **"ClientProxy","stack":[""],"level":"error","message":"Disconnected from RMQ. Trying to reconnect."}**  this error
please help

**Comment by donalddoe** [comment]
Hello @harshk1311  Did you come up with any solution for this issue ?
