### ISSUE TITLE
GRPC hero.proto      Can't build in     dist

### ISSUE THREAD

**Issue by cswww** [nestjs/nest#6511]
ENOENT: no such file or directory, open  hero/hero.proto

const app = await NestFactory.createMicroservice<MicroserviceOptions>(TuyaapiModule, {
  transport: Transport.GRPC,
  options: {
    package: 'hero',
    protoPath: join(__dirname, 'hero/hero.proto')
  },
});

app.listen(() => console.log('Microservice is listening'));

**Comment by kamilmysliwiec** [comment]
See instructions in this PR https://github.com/nestjs/docs.nestjs.com/pull/1777
