### ISSUE TITLE
wss not worked

### ISSUE THREAD

**Issue by Steven95689** [nestjs/nest#6512]
Hi, when i change the config for ssl in the api, websocket not accessible through wss and still accessible through ws. but the api can access through https. what is the problem? is there another configuration needs for ssl through websocket?
this is my bootstrap function in main.module.ts

async function bootstrap() {
  const key  = fs.readFileSync(__dirname + '/../server.key');
  const cert = fs.readFileSync(__dirname + '/../server.crt');
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    httpsOptions: {
      key: key,
      cert: cert,
    }
  });
  app.useGlobalPipes(new ValidationPipe());
  app.enableCors({
    origin: true,
    methods: "GET,HEAD,PUT,PATCH,POST,DELETE",
    allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, Authorization",
  });
  app.useStaticAssets(join(__dirname, '..', 'public'));
  await app.listen(8182);
}

and this is my gateway content:

import {
  MessageBody,
  OnGatewayDisconnect,
  SubscribeMessage,
  WebSocketGateway,
  WebSocketServer
} from '@nestjs/websockets';
import { Server, Socket } from 'socket.io';
  
@WebSocketGateway(8283, { transports: ['websocket'] })
export class EventsGateway implements OnGatewayDisconnect {

/** some content */

}

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
