### ISSUE TITLE
ExceptionFilter: @Catch() doesn't work with InternalServerErrorException

### ISSUE THREAD

**Issue by vahidvdn** [nestjs/nest#6514]
## Current behavior
When I use the following decorator with my Exception Filter class:

```typescript
@Catch(InternalServerErrorException)
export class HttpExceptionFilter extends BaseExceptionFilter implements ExceptionFilter {
```

The `catch` method within the class doesn't get fired at all. But for example, it works fine with `ForbiddenException`. Here is the way I test it:

```ts
throw new HttpException('500 errrrr', HttpStatus.INTERNAL_SERVER_ERROR);
```

## Input Code
Here is the repo link for reproduction:
https://github.com/vahidvdn/typescript-starter

Just run the API by Swagger (http://localhost:3000/docs) you will see the issue. Then open the `http-exception.filter.ts` file and remove `InternalServerErrorException` and you will see the difference in response of api.

## Expected behavior
`catch` method should get fired and catch the 500 internal error exception.

## Possible Solution
For now I do the following, but it's not the actual solution

```ts
if (status != 500) super.catch(exception, host);
```

## Environment

<pre><code>
Nest version: 7.x

 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Windows

**Comment by Tony133** [comment]
Hi @vahidvdn, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by jmcdo29** [comment]
Please  provide a [minimum reproduction](http://minimum-reproduction.wtf)

**Comment by vahidvdn** [comment]
@Tony133 @jmcdo29 I updated the issue and added the repo link. Would you please check the repo and steps to reproduction?

**Comment by jmcdo29** [comment]
If you change from `new HttpException()` to `new InternalServerException` it will properly get caught. This has to do with how the `@Catch()` decorator provides a class for Nest it check `instanceof` against, and while `InternalServerException` is an `instanceof HttpException` the inverse is not true.

**Comment by vahidvdn** [comment]
@jmcdo29 Yes, you are right. `new InternalServerErrorException` works fine. But in my case that actually a query fails with an error (like a foreign key constraint, etc), again it doesn't work. Any idea?

**Comment by vahidvdn** [comment]
Thank you so much. Now it makes sense.

**Comment by andreyfomin** [comment]
It is disappointing. Documentation should be improved https://docs.nestjs.com/fundamentals/execution-context.
Create working example for it :(

**Comment by jmcdo29** [comment]
@andreyfomin what would you like to see improved? Our docs [are open source](https://GitHub.com/nestjs/docs.nestjs.com) and contributions are more than welcome
