### ISSUE TITLE
Error and message are not return correctly

### ISSUE THREAD

**Issue by RezaRahmati** [nestjs/nest#6516]
## Current behavior

![image](https://user-images.githubusercontent.com/10086092/109243712-69054c80-77ab-11eb-8f24-556cf538f6a4.png)

## Input Code

here is the signature of BadRequestException, (or any other exceptions)

```ts
constructor(objectOrError?: string | object | any, description?: string);
```
First parameter is ObjectOrError and second parameter is called description

Now run below code
```ts
throw new BadRequestException('errorOrObject', 'description');
```

## Expected behavior

'errorOrObject' been returned as `error`, and 'description' been returned as `description` or `message`. or parameter name in method signature changed

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
