### ISSUE TITLE
Provider<T> doesn't typecheck as expected

### ISSUE THREAD

**Issue by ericmorand** [nestjs/nest#6522]
# Bug Report

## Current behavior

When typing a provider using the generic `Provider<T>` type, any valid provider is considered as valid, defeating the purpose of typing.

## Input Code

```ts
import {ConfigService} from "@nestjs/config";

const provider: Provider<string> = ConfigService;
```

## Expected behavior

Assigning `ConfigService` to a variable of type `Provider<string>` should raise a TS2322 error since `ConfigService` is not providing a `string`.

## Possible Solution

It is possible to workaround the issue but using a custom type and use that type instead of the provided `Provider<T>` type:

```ts
import {ConfigService} from "@nestjs/config";

type ExplicitProvider<T = any> = Type<T> | ClassProvider<T> | ValueProvider<T> | FactoryProvider<T> | ExistingProvider<T>;

const provider: ExplicitProvider<string> = ConfigService; // TS2332
```

But `Provider<T>` should be fixed since it doesn't provide any typechecking in its current form.

**Comment by jmcdo29** [comment]
@kamilmysliwiec I can see this comes from `Provider<T>` using `Type<any>`, is there a reason it doesn't use `Type<T>`? Felxibility of the framework?

**Comment by kamilmysliwiec** [comment]
> Felxibility of the framework?

Correct. Nest lets you specify a completely different class/object as a provider token and its value/class ref/factory's return value. They don't have to match and so the following declaration:

```typescript
provide: RandomClass,
useValue: {}, // or "use.."
```

is fully valid & supported.

**Comment by ericmorand** [comment]
Out of curiosity, what is the point of having a generic Provider type? From my understanding, it doesn't type-check anything, by design, and thus doesn't provide any usage.

**Comment by Ionaru** [comment]
A small utility function similar to Angular's new `provide*(...)` can be made to get the desired type safety:

```ts
import { Module, DynamicModule, InjectionToken, Provider } from "@nestjs/common";

// This will bind the type given in the InjectionToken to the useValue parameter.
export const provideValue = <T>(provide: InjectionToken<T>, useValue: T): Provider<T> => ({ provide, useValue });

export const MySecret: InjectionToken<string> = 'MY_SECRET';

@Module({})
export class MyModule {
  static forRoot(): DynamicModule {
    return {
      module: MyModule,
      providers: [
        provideValue(MySecret, 500), // TS2345: Argument of type number is not assignable to parameter of type string
      ],
    };
  }
}
```
