### ISSUE TITLE
@nestjs/microservices error  rxjs version update

### ISSUE THREAD

**Issue by rosenbergvr** [nestjs/nest#6523]
## Bug Report
The error occurs by updating rxjs
https://www.npmjs.com/package/rxjs 

## Current behavior
 
../../packages/abstract/middleware/node_modules/@nestjs/microservices/exceptions/base-rpc-exception-filter.d.ts:5:5 - error TS2416: Property 'catch' in type 'BaseRpcExceptionFilter<T, R>' is not assignable to the same property in base type 'RpcExceptionFilter<T, any>'.

 
 
## **Momentary Solution** 

 For the moment it is advisable to fix the rxjs version in the package

"rxjs": "6.6.3",
"@nestjs/microservices": "7.6.13",

**Comment by Tony133** [comment]
Hi @rosenbergvr , I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
