### ISSUE TITLE
@Req and @Res not working as expected

### ISSUE THREAD

**Issue by dualmacops** [nestjs/nest#6525]
## Bug Report
@Req and @Res decorators in get request doesn't work if also not importing the Request and Response  from'@nestjs/common';
it says ReferenceError: Response is not defined ReferenceError: Request is not defined:

Also when using **app.use(cookieParser());** middleware i get the following error when trying to use the response.cookie function
[3:18:14] File change detected. Starting incremental compilation...

src/controllers/app.controller.ts:27:14 - error TS2339: Property 'cookie' does not exist on type 'Response'.

response.cookie('refreshToken', refreshToken,{httpOnly:true,path:'/refresh_token'})

## Input Code
```ts
import { Controller, Get, Param, Post, Query,  Res } from '@nestjs/common';
import { Response } from "express";
import { Cookies } from 'src/decorators/cookies.decorator';
import { Auth } from 'src/models/auth.model';
import { AuthService } from 'src/services/auth.service';
import { AppService } from '../services/app.service';

@Controller()
export class AppController {
  constructor(private readonly auth: AuthService) {}
  @Get('refresh_token')
  refreshToken(@Cookies('refreshToken') token: string, @Res({ passthrough: true }) response: Response) {
    const { accessToken, refreshToken } = this.auth.refreshToken(token); 
    response.cookie('refreshToken', refreshToken,{httpOnly:true,path:'/refresh_token'})
    return refreshToken
  }
}
```
This code will work, for it to get the fist error remove the import express, to get the second one import Response from @nestjs/common

## Expected behavior
I expect to be able to use Req and Res without importing Request and Response.
I expect to be able to import Request from @nestjs/common.

## Possible Solution
it works when importing Request,Res,Response and Res
it works when importing from express with **import { Response } from "express";**

## Environment
<pre><code>
Nest version: 7.6.9

 
For Tooling issues:
- Node version: 14.15.4
- Platform:  Windows

**Comment by jmcdo29** [comment]
`Req`, `Request`, Res`, and`Response` are all decorators, `Req` and `Request` meaning the incoming HTTP request and are aliases for one another, and similarly for `Res` and `Response`, but about the incoming response object that will be sent at the end of the request. These are made as aliases for each other to make sure that developers have options for using `@Req()` or `@Request()` and to make sure there are no collisions with other packages (i.e. a dev can use `@Req()` for the decorator and `import { Request } from 'express'` for the type).

I've not ever seen anything about `@Req()` and `@Res()` not working if `Request` or `Response` is also not imported. Can you provide a git reproduction with that?

**Comment by dualmacops** [comment]
I think i did get a bit lost with the imports, as importing Response,Request from '@nestjs/common';
Forget the 1st part of the issue.

The problem is that i need to import the type { Response } from "express" to be able to use response.cookie() instead of from '@nestjs/common';

**Comment by jmcdo29** [comment]
That's the expected functionalty. Like I said in my first comment, `Response` from `@nestjs/common` is the `@Response()` **decorator**, which is not the same as the `Response` **type** from `express`

**Comment by dualmacops** [comment]
Oh i think Request and Response was being imported from lib.dom.d.ts, or so tells me VScode.
I' see what you are saying, but i dont understand why is "compiling" when i import Response from '@nestjs/common'
![image](https://user-images.githubusercontent.com/9700375/109374150-7148af00-78b3-11eb-8a52-6cdec0c15de8.png)
![image](https://user-images.githubusercontent.com/9700375/109374157-7dcd0780-78b3-11eb-8ba1-4df7df2e4f5c.png)

**Comment by jmcdo29** [comment]
Technically, while a decorator shouldn't be used as a type, it is possible to do so. And if you do, then `.cookies` won't exist on the type `Response` because `Response` is a `ParamDecorator`. That's why it can compile, though generally it shouldn't be used like this.

If you need further support, I suggest you visit our [Discord](https://discord.gg/nestjs)
