### ISSUE TITLE
TypeUnions don't compile for Code-first GraphQL

### ISSUE THREAD

**Issue by iiian** [nestjs/nest#6526]
## Current behavior
Code-first GraphQL, having problems with the type unions! 😄 
When I go to create a type union as directed in the [docs](https://docs.nestjs.com/graphql/unions-and-enums), my system will not build. If I remove the attempted type-union creation, my system recompiles and serves a GraphQL API.

**Error trace**
```log
(node:8652) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at getObjectType (/<path-to-me>/node_modules/@nestjs/graphql/dist/schema-builder/factories/union-definition.factory.js:16:96)
    at /<path-to-me>/node_modules/@nestjs/graphql/dist/schema-builder/factories/union-definition.factory.js:17:60
    at Array.map (<anonymous>)
    at types (/<path-to-me>/node_modules/@nestjs/graphql/dist/schema-builder/factories/union-definition.factory.js:17:48)
    at resolveThunk (/<path-to-me>/node_modules/graphql/type/definition.js:480:40)
    at defineTypes (/<path-to-me>/node_modules/graphql/type/definition.js:944:15)
    at GraphQLUnionType.getTypes (/<path-to-me>/node_modules/graphql/type/definition.js:900:26)
    at collectReferencedTypes (/<path-to-me>/node_modules/graphql/type/schema.js:356:59)
    at collectReferencedTypes (/<path-to-me>/node_modules/graphql/type/schema.js:368:9)
    at new GraphQLSchema (/<path-to-me>/node_modules/graphql/type/schema.js:153:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Input Code
```ts
// src/data/model/data_value.ts
import { createUnionType } from '@nestjs/graphql';

// kills my whole app
export const ValueUnion = createUnionType({
  name: 'ValueUnion',
  types: () => [String,Number,Boolean]
});
```

```ts
// src/data/model/data.model.ts
import { ObjectType, Field } from '@nestjs/graphql';

@ObjectType()
export class Data {
  // Data model omitted; I really don't believe it's necessary to share--it does not seem to be a part of the problem.
}
```

```ts
// src/data/data.resolver.ts
@Resolver(of => Data)
export class DataResolver {
  constructor() {}

  // I really just want to test type unions in nestjs, but darn it if they don't seem to be broken!
  // Removing this query fixes the system.
  @Query(returns => [ValueUnion])
  getValue(): Array<typeof ValueUnion> {
    return ['aahhh why is this so hard', 'lol'];
  }

  // rest, related to data model...
  // note that I also tried `DataValue` type union on an `@ObjectType` that needed it, same explosion.
}
```

```ts
@Module({
  imports: [
    GraphQLModule.forRoot({ 
      autoSchemaFile: true,
      debug: true,
      playground: true
    }),
  ],
  providers: [DataResolver, DataService] // DataService omitted
})
export class DataModule {}
```

## Expected behavior
Serving on port `:3000` 🍾 

## Possible Solution
Curl in fetal position, abandon GraphQL, take up archery

## Environment

Nest version: ...?
```$
$ nest --version
7.4.1
``` 

```yarn.lock
"@nestjs/cli@^7.0.0":
  version "7.5.6"
...
"@nestjs/common@^7.0.0":
  version "7.6.13"
```
For Tooling issues:
- Node version: 14.8.0, 13.8.0, both fail
- Platform:  MacOS

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by iiian** [comment]
Should be public access
https://github.com/iiian/graphql-type-union-bug

I could just be doing it wrong, the documentation on type unions seems really slim, but even trying to precisely follow the guide falls apart on me

**Comment by iiian** [comment]
Seems like the `UnionDefinitonFactory` gets wiped of its `typeDefinitionsStorage` somewhere between executing the `createUnionType` and executing the `Query` command that fails to find `ValueUnion`

**Comment by iiian** [comment]
I traced execution... it's something to do with the `UnionDefinitionFactory` getting **dependency injected**, without knowledge of the GraphQL type decorations collected on the compiler's initial voyage through my codebase, which were shared with the `TypeMetadataStorageHost` singleton.

Now whether this is because I'm doing something incorrectly or not, I can't tell. But it seems like maybe there's a link between the `TypeDefinitionStorage` & the `TypeMetadataStorageHost`? Any hints are appreciated.

Thanks!

**Comment by jmcdo29** [comment]
It looks like the built in scalars aren't union-able. You could probably make a custom class wrapper around the String, Int, and Boolean scalars and get a union-able method then. I have a [sample union repo](https://github.com/jmcdo29/nest-graphql-union/blob/main/src/baz.model.ts) if you'd like to take a look.

@kamilmysliwiec is this expected? I'm not 100% familiar with GraphQL unions, but I feel this is probably what we'd expect to happen.

**Comment by iiian** [comment]
Hey @jmcdo29. Thanks for your efforts here. I just realized primitives are not unionable in GraphQL, which came as a quite a surprise. After making Box types for String|Int, everything is compiling.

I can close this ticket now!
