### ISSUE TITLE
CircularDependencyException('@InjectRepository()')

### ISSUE THREAD

**Issue by ThomasEddie** [nestjs/nest#6528]
## Current behavior
I have ServiceEntity I have Join ManyToOne or OneToMany To Its work fine but when I use it with AppointmentRoomEnity it got error like :
throw new circular_dependency_exception_1.CircularDependencyException('@InjectRepository()');
        ^

CircularDependencyException [Error]: A circular dependency has been detected inside @InjectRepository(). Please, make sure that each side of a bidirectional relationship is decorated with "forwardRef()". Also, try to eliminate barrel files because they can lead to an unexpected behavior too.

*Note I have read the same issue but  my problem is it works with UserEntity is find but when used with AppointmentRoomEntity it got the error I don't know why

## ServiceEntity

```
@Entity({ name: 'service' })
export class ServiceEntity extends ShareBaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ nullable: true })
  image: string;

  @Column()
  name: string;

  @Column({
    type: 'enum',
    enum: Time_Type,
    default: Time_Type.Time,
    nullable: true,
  })
  type: Time_Type;

  @Column({ type: 'float' })
  price: number;

  @Column({ nullable: true })
  description: string;

  @Column({ default: true, nullable: true })
  status: boolean;

   // WORK FINE
  @ManyToOne(() => UserEntity, (userEntity) => userEntity.service)
  @JoinColumn({ name: 'staff_id', referencedColumnName: 'id' })
  staff: UserEntity;
  @Column()
  staff_id: number;

  @ManyToOne(
    () => ServiceCategoryEntity,
    (ServiceCategoryEntity) => ServiceCategoryEntity.service,
  )
  @JoinColumn({ name: 'service_category_id', referencedColumnName: 'id' })
  service_category: ServiceCategoryEntity;
  @Column({ nullable: true })
  service_category_id: number;

   // WORK FINE
  @OneToMany(
    () => MembershipServiceEntity,
    (membershipService) => membershipService.service,
  )
  membership_service: MembershipServiceEntity;
  // WORK FINE
  @OneToMany(
    () => SaleServiceEntity,
    (SaleServiceEntity) => SaleServiceEntity.service,
  )
  sale_service: SaleServiceEntity;

//ERROR
  @OneToMany(() => AppointmentRoomEntity, (entity) => entity.service)
  apt_room: AppointmentRoomEntity;
}
```

## ServiceService
```
@Injectable()
export class ServiceService {
  constructor(
    @InjectRepository(ServiceEntity)
    private serviceRepo: Repository<ServiceEntity>,
  ) {}

}

```

##AppointmentRoomEntity
```
import { ServiceEntity } from './../../service/entities/service.entity';
import { RoomEntity } from '../../room/entities/room.entity';
import { ShareBaseEntity } from '../../../common/share-base-entity/share-base.entity';
import { AppointmentStatus } from '../../../enums/apointment-status-enum';
import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { UserEntity } from '../../users/entities/user.entity';
import { CustomerEntity } from '../../customer/entities/customer.entity';

@Entity({ name: 'appointment_room' })
export class AppointmentRoomEntity extends ShareBaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ nullable: true })
  note: string;

  @Column({ nullable: true })
  name: string;

  price: number;

  @Column({ nullable: true })
  phone: string;

  @Column({ type: 'time' })
  time_in: Date;

  @Column({ type: 'time' })
  time_out: Date;

  @Column({ nullable: true, type: 'date' })
  join_date: Date;

  @Column({
    default: AppointmentStatus.PENDING,
    nullable: true,
    enum: AppointmentStatus,
  })
  status: AppointmentStatus;

  // WORK FINE
  @ManyToOne(
    () => UserEntity,
    (UserEnitiy) => UserEnitiy.appointment_to_staff,
    { nullable: true },
  )
  @JoinColumn({ name: 'staff_id', referencedColumnName: 'id' })
  staff: UserEntity;
  @Column({ nullable: true })
  staff_id: number;

 // WORK FINE
  @ManyToOne(
    () => CustomerEntity,
    (CustomerEntity) => CustomerEntity.appointment_to_customer,
    { nullable: true },
  )
  @JoinColumn({ name: 'customer_id', referencedColumnName: 'id' })
  customer: CustomerEntity;
  @Column({ nullable: true })
  customer_id: number;
  // WORK FINE
  @ManyToOne(() => RoomEntity, (RoomEntity) => RoomEntity.appointment)
  @JoinColumn({ name: 'room_id', referencedColumnName: 'id' })
  room: RoomEntity;
  @Column()
  room_id: number;

  // ERROR
  @ManyToOne(() => ServiceEntity, (entity) => entity.apt_room)
  @JoinColumn({ name: 'service_id', referencedColumnName: 'id' })
  service: ServiceEntity;
}
```

###ServiceModule
```
import { Global, Module } from '@nestjs/common';
import { ServiceService } from './service.service';
import { ServiceController } from './service.controller';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ServiceEntity } from './entities/service.entity';

@Module({
  imports: [TypeOrmModule.forFeature([ServiceEntity])],
  controllers: [ServiceController],
  providers: [ServiceService],
  exports: [ServiceService],
})
export class ServiceModule {}

```

## ServiceService
```


```

## Environment

<pre>"dependencies": {
    "@casl/ability": "^5.1.2",
    "@nestjs/common": "^7.5.1",
    "@nestjs/config": "^0.6.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/jwt": "^7.2.0",
    "@nestjs/mapped-types": "^0.1.1",
    "@nestjs/passport": "^7.1.5",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/platform-fastify": "^7.6.5",
    "@nestjs/schedule": "^0.4.1",
    "@nestjs/swagger": "^4.7.10",
    "@nestjs/typeorm": "^7.1.5",
    "@nestjs/websockets": "^7.6.5",
    "@types/cron": "^1.7.2",
    "@types/dotenv": "^8.2.0",
    "@types/passport-jwt": "^3.0.3",
    "@types/uuid": "^8.3.0",
    "@types/voca": "^1.4.0",
    "axios": "^0.21.1",
    "bcrypt": "^5.0.0",
    "chalk": "^4.1.0",
    "class-transformer": "0.3.1",
    "class-validator": "^0.13.1",
    "dayjs": "^1.10.4",
    "dotenv": "^8.2.0",
    "fastify-compress": "^3.4.1",
    "fastify-helmet": "^5.1.0",
    "fastify-multer": "^2.0.2",
    "fastify-multipart": "^3.3.1",
    "fastify-no-icon": "^4.0.0",
    "fastify-static": "^3.4.0",
    "fastify-swagger": "^3.5.0",
    "fastify-url-data": "^3.0.3",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.32",
    "multer": "^1.4.2",
    "nestjs-i18n": "^8.0.10",
    "nestjs-typeorm-paginate": "^2.2.6",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "pg": "^8.5.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3",
    "swagger-ui-express": "^4.1.6",
    "typeorm": "^0.2.29",
    "uuid": "^8.3.2",
    "voca": "^1.4.0"
  },<code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction](http://minimum-reproduction.wtf). 

In the meantime, you can also ask on our [Discord](https://discord.gg/nestjs) for more immediate support. I don't believe this is a bug in Nest, but I'll take a look if you provide a reproduction.

**Comment by ThomasEddie** [comment]
@jmcdo29 when I  delete another module it works now but I still cannot figure out why it works it's my fault can I delete this issued ?

**Comment by jmcdo29** [comment]
I can close this out and we can discuss on discord

**Comment by ThomasEddie** [comment]
Thank sir @jmcdo29
