### ISSUE TITLE
express session regenerate doesn't work well

### ISSUE THREAD

**Issue by typestar-y** [nestjs/nest#6533]
## Input Code

```ts
// main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as session from 'express-session';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.use(
    session({
      secret: 'my-secret',
      resave: false,
      saveUninitialized: false,
    }),
  );
  await app.listen(3000);
}
bootstrap();
```

```ts
// app.controller.ts
import { Controller, Get, Session } from '@nestjs/common';
import { Session as ExpressSession, SessionData } from 'express-session';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('login')
  session(@Session() session: any): Record<string, string> | void {
    session.regenerate((error: Error) => {
      if (error) {
        throw error;
      }
      // some login processes
      return { "message": "login succeeded" }; // return result message
    });
  }
```

## Current behavior

When using express-session's regenerate function, the processes of callback doesn't work as expected. 

```
GET http://localhost:3000/session


HTTP/1.1 200 OK
<Response body is empty>
```

## Expected behavior

```
GET http://localhost:3000/session


HTTP/1.1 200 OK

{
  "message": "login succeeded"
}
```

## Possible Solution

I think the cause of this behavior is that regenerate function calls setImmediate in the process of regenerating session. I found that the regenerating process calls destroying session before regenerating and the destroying process calls regenerate function with `setImmediate` as follows:

```ts
MemoryStore.prototype.destroy = function destroy(sessionId, callback) {
  delete this.sessions[sessionId]
  callback && defer(callback)
}
...
var defer = typeof setImmediate === 'function'
  ? setImmediate
  : function(fn){ process.nextTick(fn.bind.apply(fn, arguments)) }
...
```

https://github.com/expressjs/session/blob/a8641429502fcc076c4b2dcbd6b2320891c1650c/session/memory.js#L93
https://github.com/expressjs/session/blob/a8641429502fcc076c4b2dcbd6b2320891c1650c/session/memory.js#L25

So, session regenerate process and the callback process will be completed after responding 200 response with no body for the above example and the client can't receive expected 200 response with message.

What should I do for regenerating session with nestjs and express-session ? I hope someone help me...
## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 14.15.4  
- Platform:  macOS 

Others:

Express Session: 1.17.1

</code></pre>

**Comment by micalevisk** [comment]
You could use the response object like this:

```typescript
  @Get('login')
  session(@Session() session: any, @Res() res: Response): Record<string, string> | void {
    session.regenerate((error: Error) => {
      if (error) {
        throw error;
      }
      // some login processes
      res.json({ "message": "login succeeded" });
    });
  }
```

or with `promisify` (from node utils) to use with async/await.

I think that Nestjs can't handle this case for us.

**Comment by jmcdo29** [comment]
@typestar-y Callbacks are asynchronous responses, which usually need some sort of `next` handler to pass the value on to the next function. Without that next handler, the original asynchronous method can be called, and will eventually return the value, but will not pass the value on. You can try using `@Next()`, but that means you'll be in charge of the entire response. Same with using `@Res()` to get the response object. 

If you want, you can wrap the `session.regenerate` in a `promise` or use `promisify` from `utils` like @micalevisk suggested

A sample could look like

```ts
@Get('login')
session(@Session() session: any): Record<string, string> {
  return new Promise((resolve, reject) => {
    session.regenerate((error?: Error) => {
      if(error) {
        return reject(error);
      }
      resolve({{ "message": "login succeeded" });
    });
  });
}
```
