### ISSUE TITLE
NestJS task-scheduling documentation is misleading

### ISSUE THREAD

**Issue by eifory** [nestjs/nest#6538]
https://docs.nestjs.com/techniques/task-scheduling#dynamic-intervals

The code examples have standard constructor injection:
`constructor(private schedulerRegistry: SchedulerRegistry) {}`

But when describing the addInterval method we see:
`this.scheduler.addInterval(name, interval);`

deleteInterval method:
`this.scheduler.deleteInterval(name);`

getIntervals method: 
`this.scheduler.getIntervals();`

It probably should be like this:
`this.schedulerRegistry`

**Comment by jmcdo29** [comment]
Would you like to make a PR for this change? Should be a simple name change in the docs

**Comment by eifory** [comment]
Yes I would like to make a PR

**Comment by kamilmysliwiec** [comment]
Lets' track this here https://github.com/nestjs/docs.nestjs.com/pull/1813
