### ISSUE TITLE
Which one should be the best way (or make more sense) to import outer provider

### ISSUE THREAD

**Issue by miracle0930** [nestjs/nest#6557]
Suppose I have a ```BarModule``` and ```FoodModule```. Now the ```BarModule``` depends on ```FoodModule``` to perform some function, I have two ways to do the connection:

Firstly:
```js
// BarModule
import { FoodModule } from '@/food/food.module.ts';
@Module({
    controllers: [ BarController ],
    providers: [ BarService ],
    imports: [ FoodModule ],
    exports: [],
})

// FoodModule
@Module({
    controllers: [ FoodController ],
    providers: [ FoodService ],
    imports: [],
    exports: [ FoodService ]
})
```

Secondly:
```js
// BarModule
import { FoodService } from '@/food/food.service.ts';
@Module({
    controllers: [ BarController ],
    providers: [ BarService, FoodService ],
    imports: [ FoodModule ],
    exports: [],
})

// FoodModule
@Module({
    controllers: [ FoodController ],
    providers: [ FoodService ],
    imports: [],
    exports: []
})
```

These two ways can both meet my requirement and personally  I prefer the first one, but I am still wondering if there are any differences under the hood or which one should be the best one?

**Comment by jmcdo29** [comment]
These are not equal methods, by the way. In the first one you have a single `FooService`, created and exported by the `FooModule` then consumed by the `BarModule` and `BarService`

In the second one, you have two `FooService`s, separately instanced, and not shared between the modules.

Generally, go with the first, you'll run into fewer problems (like dependencies of dependencies)

Please use our [Discord](https://discord.gg/nestjs) for further support
