### ISSUE TITLE
Nest does not throw an error when failing to resolve request-scoped service outside API context

### ISSUE THREAD

**Issue by kfirba** [nestjs/nest#6563]
## Current behavior
`Request` injection scope makes the app silently fail its dependency injection and, as a result, crash in runtime.

When we have some service that uses the `Request` injection scope, and we use it outside of an API context, it fails to resolve the request and by that not resolving **any** dependency. However, the main class is instantiated, but when it is called, we get the infamous `Cannot read property 'x' of undefined`. 

The flow is very simple:
1. Have `ServiceA` with `@Injectable()` (Default scope) with `ServiceB` as its dependency.
2. `ServiceB` has `@Injectable({ scope: Scope.REQUEST })`
3. When Nest attempts to resolve `ServiceB` to pass it to `ServiceA`, everything works if we are in an API context. However, suppose the context of resolution is CLI, Queue, or anything else. In that case, it fails to resolve `ServiceB`, and not only that, if `ServiceA` has more dependencies, they also won't be resolved.

One would expect Nest to crash and throw some error, however, it just silently fails, and we encounter the issue in runtime.

In our scenario, we receive an API call and dispatch a job onto the queue. The class that is responsible for fetching the jobs from the queue and processing them has a dependency on some service that depends on a request-scoped service:

```
.
└── QueueProcessor/
    ├── DependencyA
    ├── DependencyB/
    │   ├── ServiceWithRequestScope <-- this causes the entire tree not to resolve
    │   ├── SubdepA
    │   └── SubdepB
    └── DependencyC
```

You may ask yourself why the hell you use the `ServiceWithRequestScope` inside this context, and the simple answer to that is because this service is also being used in other parts of our app in the correct API context.

## Input Code

```ts
@Injectable()
export class QueueProcessor {
  constructor(
    protected readonly depA: DependencyA,
    protected readonly depB: DependencyB, 
    protected readonly depB: DependencyB, 
  ) {}

  @Queue('foo')
  async foo() {
    // ...
  }
}

@Injectable()
export class DependencyB {
  constructor(
    protected readonly serviceWithRequestScope: ServiceWithRequestScope,
    protected readonly subdepA: SubdepA, 
    protected readonly subdepB: SubdepB, 
  ) {}
}

@Injectable({ scope: Scope.REQUEST })
export class ServiceWithRequestScope {
  // ...
}
```

## Expected behavior
Nest should error when booting the Queue Processing microservice.

## Possible Solution
N/A

## Environment

<pre><code>
Nest version: 7.6.7

 
For Tooling issues:
- Node version: 14.15.5  
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by kfirba** [comment]
@kamilmysliwiec That would take a while. I'm afraid I won't be able to provide one soon.
If we break it down, the main issue is that the dependency resolution process swallows an exception instead of reporting it

**Comment by kamilmysliwiec** [comment]
We need a minimum reproduction repository to better understand your use-case.

> When Nest attempts to resolve ServiceB to pass it to ServiceA, everything works if we are in an API context. However, suppose the context of resolution is CLI, Queue, or anything else. In that case, it fails to resolve ServiceB, and not only that, if ServiceA has more dependencies, they also won't be resolved.

For example, this ^ is the expected behavior. Without looking at your code & the way you use it, I can't tell you whether it works as it's designed to be.

**Comment by kfirba** [comment]
@kamilmysliwiec I see.

I'm not sure this is the expected behavior. What happens is that nest actually "resolves" the dependencies, but they are all `undefined` making your code fail in runtime. It should've raised an exception, in my opinion.

It will take me a while to set up a reproduction.

**Comment by kamilmysliwiec** [comment]
> I'm not sure this is the expected behavior. What happens is that nest actually "resolves" the dependencies, but they are all undefined making your code fail in runtime. It should've raised an exception, in my opinion.

So that's why I'm saying we need a reproduction repository. If you think this may take more than 1-2 weeks, I'd suggest creating a new issue once you have it ready as there's nothing we can really track here atm
