### ISSUE TITLE
Security Vulnerable Issue after upgraded to nest js latest version

### ISSUE THREAD

**Issue by GowriSarathkumar** [nestjs/nest#6564]
We are happily saying that we also a part of Nest Js family. Very much glad for that!

Recently we had faced one high level security vulnerable issue with nest js package which is glob-parent. Our heads are  rolling like anything to resolve that issue and  feeling sad to say that  we couldn't find any solution yet to resolve. 

Could you please anyone help us to get away from it?

I have added following details to get better understand on it  

![twistlockscan](https://user-images.githubusercontent.com/79970207/109782670-26ba9000-7c2f-11eb-8945-f959ae846b45.PNG)

If you can observe above image you guys can find one high level vulnerable issue which originated from glob-parent package.

our deliverables are hanged up somewhere as it's need your help to get promotion.

Very much thanks in Advance :) 

Appreciate your efforts !

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
