### ISSUE TITLE
Feature request: a nest CLI command to check that there is no runtime error (e.g. dependency injection error) at server start

### ISSUE THREAD

**Issue by pleportz** [nestjs/nest#6565]
## Problem

I would like to integrate a compilation check in my test CI workflow.

My use case: I share some Nest modules across 2 Nest applications: a web app and a background jobs app for task scheduling.
I'm afraid that while working locally on the web app I might break the background jobs app compilation without noticing it, and then releasing it to production.

## An approach I have tried

Systematically launching both apps when developing locally with:
`yarn nest start --config nest-cli-background-job-app.json --watch & yarn nest start --watch`

- the first command starts the background jobs app and put it in the current terminal background, allowing me to spot the compilation errors
- the second command starts the web app in the foreground

Problems with this approach:

- most of the time I am working on only 1 app at the same time
- I have to manually kill the processes spawned by `yarn nest start --config nest-cli-background-job-app.json --watch` after hitting `Ctrl+Z`

## Describe the solution you'd like

A Nest CLI command that throws an error if it detects a compilation error.
A bit like `yarn nest start` except it would not actually launch the server in the end.

**Comment by jmcdo29** [comment]
> A Nest CLI command that throws an error if it detects a compilation error.

You mean, something like `nest build`?

**Comment by pleportz** [comment]
Hi @jmcdo29 :)

I tried it locally: `nest build` does not throw compilation errors like `nest start` does.

For example, when I remove the `TypeOrmModule.forRootAsync(...)` import from my  `src/app.module.ts` file, `nest build` does not throw an error, while `nest start` gives me:

```
[Nest] 35416   - 03/03/2021, 6:06:16 PM   [ExceptionHandler] Nest can't resolve dependencies of the EmployerRepository (?). Please make sure that the argument Connection at index [0] is available in the TypeOrmModule context.
```

**Comment by jmcdo29** [comment]
> Nest] 35416   - 03/03/2021, 6:06:16 PM   [ExceptionHandler] Nest can't resolve dependencies of the EmployerRepository (?). Please make sure that the argument Connection at index [0] is available in the TypeOrmModule context.

This isn't a compilation error. This is a runtime error because the dependency injection context is not correctly set.

**Comment by pleportz** [comment]
Thanks I updated the title of the feature request. Now it seems less feasible to me (?).

Maybe I'd better rely on my staging server monitoring alerts to detect dependency injection runtime errors at server start. This way a potential issue won't reach the production environment.
What do you think ? Would have liked to catch the issue in my test CI though.

I'm closing the issue, thanks for your input!

**Comment by jmcdo29** [comment]
It's definitely more of a challenge. You may be able to make use of some package that does some basics of what Nest's DI system does (I have a small package called [nestjs-spelunker](https://github.com/jmcdo29/nestjs-spelunker) that may be able to help)
