### ISSUE TITLE
GraphQL issues on initial setup

### ISSUE THREAD

**Issue by JBraze** [nestjs/nest#6571]
## Current behavior

When using the most recent release of `@nestjs/cli` package and attempting to follow the Nestjs Documentation tutorial for GraphQL after a fresh install and new project, I can't even download the GraphQL packages specified in the "Getting Started" page without getting errors about conflicting versions of packages.

## Input Code
I use the command specified in the docs: 
`npm i --save @nestjs/graphql graphql-tools graphql apollo-server-express`

I then see this from NPM:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: graphql@14.7.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"*" from the root project
npm ERR!   peer graphql@"^14.1.1 || ^15.0.0" from @nestjs/graphql@7.9.11
npm ERR!   node_modules/@nestjs/graphql
npm ERR!     @nestjs/graphql@"*" from the root project
npm ERR!   74 more (apollo-server-express, graphql-tools, @apollo/gateway, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^15.0.0" from relay-compiler@10.1.0
npm ERR! node_modules/@graphql-tools/relay-operation-optimizer/node_modules/relay-compiler
npm ERR!   relay-compiler@"10.1.0" from @graphql-tools/relay-operation-optimizer@6.3.0
npm ERR!   node_modules/@graphql-tools/relay-operation-optimizer
npm ERR!     @graphql-tools/relay-operation-optimizer@"^6.2.5" from graphql-tools@7.0.4
npm ERR!     node_modules/graphql-tools
npm ERR!       graphql-tools@"*" from the root project
...
```

And if I install a current version of GraphQL first and then run the previous command I see:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: graphql@15.5.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"15.5.0" from the root project
npm ERR!   peer graphql@"^14.1.1 || ^15.0.0" from @nestjs/graphql@7.9.11
npm ERR!   node_modules/@nestjs/graphql
npm ERR!     @nestjs/graphql@"*" from the root project
npm ERR!   9 more (apollo-server-express, graphql-tools, @apollo/gateway, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^14.2.1" from apollo-graphql@0.4.5
npm ERR! node_modules/@apollo/gateway/node_modules/apollo-graphql
npm ERR!   apollo-graphql@"^0.4.0" from @apollo/gateway@0.17.0
npm ERR!   node_modules/@apollo/gateway
npm ERR!     optional @apollo/gateway@"^0.17.0" from @nestjs/graphql@7.9.11
npm ERR!     node_modules/@nestjs/graphql
npm ERR!       @nestjs/graphql@"*" from the root project
```

## Expected behavior
A clean install without dependency issue that prevent NPM from even installing the packages specified by Nestjs to install.

## Possible Solution
Update the GraphQL dependencies for Nestjs so that they align, enabling installation in accordance to your documentation.

## Environment

Here is the result of `nest info`
<pre><code>

[System Information]
OS Version     : Linux 4.19
NodeJS Version : v15.10.0
NPM Version    : 7.5.6

[Nest CLI]
Nest CLI Version : 7.5.6

[Nest Platform Information]
platform-express version : 7.6.13
common version           : 7.6.13
core version             : 7.6.13
 
For Tooling issues:
- Node version: v14.16.0
- Platform:  Linux - Ubuntu 20.04
</code></pre>

**Comment by jmcdo29** [comment]
I'm able to reproduce this. It has to do with how npm v7 resolves peer dependencies. [This StackOverflow answer](https://stackoverflow.com/questions/64701308/graphql-eresolve-unable-to-resolve-dependency-tree-when-building-my-docker-conta) goes into more depth about it. Until we update the `@nestjs/graphql` package, there's the option of using `--legacy-peer-deps` to get rid of the error. We'll work on updating the package, and there's already an open issue for it at nestjs/graphql#1408
