### ISSUE TITLE
How can I extract my factory funcion from custom decorator?

### ISSUE THREAD

**Issue by juanmanuel-perez** [nestjs/nest#6576]
I need to test a custom Decorator and I am not able yet. I read the following suggestion
https://github.com/nestjs/nest/issues/1020#issuecomment-417646366_ but I don't undestarnd the way of extracting the factory. How can i achieve that?

Thanks a lot!

**Comment by jmcdo29** [comment]
Generally, something like
```ts
export const decoratorFactoryFunction = (data, context: ExectuonContext) => {
  // do your thing here
}
```

And use it like 
```ts
export const Foo = createParamDecorator(decoratorFactoryFucntion);
```

Please use our [Discord](https://discord.gg/nestjs) for further support
