### ISSUE TITLE
Graphql Mapped Types decorator parameter doesn't work.

### ISSUE THREAD

**Issue by Zony-Zhao** [nestjs/nest#6579]
## What works without error
![image](https://user-images.githubusercontent.com/50739849/110191792-59e66480-7e65-11eb-896e-728ddb0dcf7e.png)
![image](https://user-images.githubusercontent.com/50739849/110191806-69fe4400-7e65-11eb-8e99-d95288cb6649.png)

as you can see. DishMeta is the model. As doc pointed out, this should be the typical use case for Mapped Types like PickType and so on.
@see https://docs.nestjs.com/graphql/mapped-types
## What throws an error
When I add a parameter of InputType as decorator.(The create dto is a InputType and DishMeta is the ObjectType). 
![image](https://user-images.githubusercontent.com/50739849/110191877-e09b4180-7e65-11eb-9827-121447d121da.png)

I got this.
![image](https://user-images.githubusercontent.com/50739849/110191868-d1b48f00-7e65-11eb-80ef-6b35b098d2f3.png)

**Comment by jmcdo29** [comment]
`@InputType()`s need to extend `@InputType()`s. `@ObjectType()`s need to extend `@ObjectType()`s. At least to my knowledge. In the meantime, please provide a [minimum reproduction](http://minimum-reproduction.wtf)

**Comment by Zony-Zhao** [comment]
> `@InputType()`s need to extend `@InputType()`s. `@ObjectType()`s need to extend `@ObjectType()`s. At least to my knowledge. In the meantime, please provide a [minimum reproduction](http://minimum-reproduction.wtf)

What do you mean by that? I thought the decorator parameter is for different parent and child types.
![image](https://user-images.githubusercontent.com/50739849/110191972-661ef180-7e66-11eb-9233-e409dd0728af.png)

**Comment by jmcdo29** [comment]
Ah, interesting. I missed that in your code snippet, and actually wasn't aware Kamil implemented that. My apologies. Can you provide a minimum reproduction?

**Comment by Zony-Zhao** [comment]
It was related to some overlapping between the parent and child object. The function is working fine.(maybe the error in  graphql needs to be more clear and precise, it always takes me long to find out what the true problem is)
