### ISSUE TITLE
NestJS: Microservices with Docker

### ISSUE THREAD

**Issue by abhjain18** [nestjs/nest#6584]
Please help
https://stackoverflow.com/questions/66511229/nestjs-microservice-issue-with-docker

**Comment by Tony133** [comment]
Hi @abhjain18, if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by abhjain18** [comment]
@Tony133 
I have already added. If possible please help
https://discord.com/channels/520622812742811698/616321218567471151/817886362744389662

**Comment by jmcdo29** [comment]
Please use our Discord and StackOverflow for support (as you already have). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
