### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by clayrisser** [nestjs/nest#6586]
## Bug Report

NestJS does not correctly detect class when babel transforms class to function.

## Current behavior
throws following error
```
TypeError: Cannot call a class as a function
```

## Input Code
_.baberc_
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "corejs": 3,
        "spec": true,
        "useBuiltIns": "usage",
        "targets": {
          "node": "12"
        }
      }
    ],
    "@babel/preset-typescript"
  ],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-transform-runtime"
  ]
}
```

```ts
import { Injectable, Inject, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

@Injectable()
export default class SomeMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction) {
    console.log('some middleware');
    next();
  }
}
```

## Expected behavior
Should log `some middleware` when api is called.

## Possible Solution
Update `isClass` implementation to detect a class that was transformed to a function.
https://github.com/nestjs/nest/blob/d6bc71ddd4bd937115a0bbf2d80d3ac83b6870c9/packages/core/middleware/utils.ts#L62

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: v12.20.0
- Platform:  Debian Linux
- NestJS: 7.6.13

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction

**Comment by clayrisser** [comment]
This is worth reading regarding this issue. Basically it's only checking if it's a native class. It's not checking if it's a conventional class.

https://stackoverflow.com/a/49510834

**Comment by clayrisser** [comment]
> Please provide a minimum reproduction

```sh
git clone https://github.com/clayrisser/example-graphback-nestjs
cd example-graphback-nestjs
make start
```

**Comment by clayrisser** [comment]
I created a pull request to fix this. #6587

**Comment by kamilmysliwiec** [comment]
Let's track this herehttps://github.com/nestjs/nest/pull/6587
