### ISSUE TITLE
@nestjs/swagger/plugin , In some cases the documentation is not generated automatically

### ISSUE THREAD

**Issue by nightsimon** [nestjs/nest#6590]
I used the plugin to generate the swagger document automatically. 

 In the interface for getting all users, the UserEntityList is returned, which is automatically generated for the interface document。But in adding the user interface, I return a custom wrapped result object, which does not automatically generate documentation, I am not sure why.

Please give me a hand, thank you

 ResultDto
![image](https://user-images.githubusercontent.com/45738680/110248050-2cef9a00-7faa-11eb-81f8-ba1370e0cb94.png)

controller
![image](https://user-images.githubusercontent.com/45738680/110247858-4cd28e00-7fa9-11eb-9ba9-63401101d215.png)
service
![image](https://user-images.githubusercontent.com/45738680/110247879-61168b00-7fa9-11eb-863b-fe73a7d8ab41.png)
swagger api doc
![image](https://user-images.githubusercontent.com/45738680/110247916-886d5800-7fa9-11eb-8686-acb7dcfff87e.png)

![image](https://user-images.githubusercontent.com/45738680/110247938-9cb15500-7fa9-11eb-870c-79902793ac43.png)

**Comment by jmcdo29** [comment]
You're using generic types, [which the docs say can't be reflected by default](https://docs.nestjs.com/openapi/types-and-parameters#generics-and-interfaces). This is a limitation of Typescript, not a problem with NestJS. You can create mixins instead to get a similar result

**Comment by Hwan-seok** [comment]
@jmcdo29 Can I get some example of mixin to achieve expected result?

**Comment by micalevisk** [comment]
@Hwan-seok https://github.com/nestjs/swagger/issues/86#issuecomment-510927068
