### ISSUE TITLE
How do I pass the service in the interceptor or guards?

### ISSUE THREAD

**Issue by Mcalready** [nestjs/nest#6592]
**Here is my code。**
In rbacInterceptor, My code is like this:

`import {
  CallHandler,
  ExecutionContext,
  Injectable,
  NestInterceptor,
  ForbiddenException,
  UnauthorizedException,
  Inject,
} from '@nestjs/common';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { RedisCacheService } from '../cache/redis.service';
import { RedisService } from 'nestjs-redis';
@Injectable()
export class RbacInterceptor implements NestInterceptor {
  constructor(
    private readonly role: number,
    private redisCacheService: RedisCacheService,
  ) {}

  async intercept(
    context: ExecutionContext,
    next: CallHandler,
  ): Promise<Observable<any>> {
    const req = context.getArgByIndex(1).req;
    const user = req.user;
    const authorization = req['headers'].authorization || void 0;
    const token = authorization.split(' ')[1]; // authorization: Bearer xxx

    const key = `${user.id}-${user.username}`;
    const cache = await this.redisCacheService.get(key);

    return next.handle().pipe(
      tap(() => {
        if (token !== cache) {
          throw new UnauthorizedException('Your account is logged in elsewhere, please log in again!');
        } else {
          if (req.user.role > this.role) {
            throw new ForbiddenException('sorry，You do not have permission to log in! ');
          }
        }
      }),
    );
  }
}`

I need to call the interceptor, My controller code is like this:
`import {
  Controller,
  Post,
  Body,
  Get,
  UseGuards,
  UsePipes,
  UseInterceptors,
} from '@nestjs/common';
import { UserService } from './user.service';
import { AuthService } from '../logical/auth/auth.service';
import { User } from '../entities/user/user.entity';
import { RegisterDTO } from './dto/register.dto';
import { LoginDTO } from './dto/login.dto';
import { ValidationPipe } from '../common/pipe/validation.pipe';
import { RbacInterceptor } from '../common/interceptor/rbac.interceptor';
import { roleConstans as role } from '../common/constants/constants';
import { RedisCacheService } from '../common/cache/redis.service';
import { RedisService } from 'nestjs-redis';
import { Redis } from 'ioredis';

@Controller('user')
export class UserController {
  constructor(
    private readonly userService: UserService,
    private readonly authService: AuthService,
    private configService: ConfigService,
  ) {}

  @UseGuards(AuthGuard('jwt'))
  // I am confused here. However, I use RedisCacheService or new RedisCacheService(), this code can not work. why?
  @UseInterceptors(new RbacInterceptor(role.DEVELOPER, RedisCacheService))
  @Get()
  async getUserList(): Promise<User[]> {
    return this.userService.geteUser();
  }
}
`
I have studied for a long time by myself, but no results. please help me. 
thanks!

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for support. We are using GitHub to track bug reports, feature requests, and regressions.

**Comment by Mcalready** [comment]
Ok.thank you so much~
