### ISSUE TITLE
Use multiple websocket adapters

### ISSUE THREAD

**Issue by ffpetrovic** [nestjs/nest#6604]
## Is your feature request related to a problem? Please describe.
The problem is that https://docs.nestjs.com/websockets/adapter uses `app.useWebSocketAdapter(new RedisIoAdapter(app));
`. I also made my own adapter to handle authentication. 
```
 create(port: number, options?: EngineOptions): any {
    options.allowRequest = async (request: IncomingMessage, allowFunction) => {
      try {
        if(!await this.authService.validateToken(request.headers?.authorization as string)) {
          return allowFunction("Unauthorized", false)
        }
      } catch (e) {
        console.warn("Failed to authenticate user:", e)
        return allowFunction("Unauthorized", false)
      }
      return allowFunction(null, true)
    }

    return super.createIOServer(adaport, options);
  }
```
Using this method, I don't see how to combine these two adapters.

## Describe the solution you'd like
`addAdapter` or something. I know this is actually just an abstraction layer on top of socket.io server, but I don't see a way to combine functionality of a custom built adapter and `socket.io-redis`. Or just any two adapter libraries.

## What is the motivation / use case for changing the behavior?
Currently (it seems) it's not possible to combine the functionality of two adapters.

**Comment by kamilmysliwiec** [comment]
If you want to combine 2 adapters, you must create a new one that wraps the former two following socket.io package instructions. There's nothing we can do on our side.
