### ISSUE TITLE
I configured the cross-domain, but it didn’t work

### ISSUE THREAD

**Issue by Fcscanf** [nestjs/nest#6608]
## Current behavior

I configured the cross-domain, but it didn’t work
![image](https://user-images.githubusercontent.com/27654200/110409178-d5445200-80c1-11eb-86e1-76ec27ff11d8.png)
![image](https://user-images.githubusercontent.com/27654200/110409276-fc028880-80c1-11eb-8288-6587403afae5.png)

## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
-❯ node -v
v14.15.4
- Platform:  
Window

Others:

</code></pre>

**Comment by micalevisk** [comment]
What if you change your request url from `localhost:3000/api/user/login` to `http://localhost/api/user/login`?

**Comment by Fcscanf** [comment]
@micalevisk If not specified, he will think it is a request from the current domain
![image](https://user-images.githubusercontent.com/27654200/110411589-cbbce900-80c5-11eb-9e9e-2b74092eb4ca.png)

**Comment by micalevisk** [comment]
how you're doing this AJAX? I didn't get it. I think this is not about the CORS at all

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Fcscanf** [comment]
@micalevisk  I am XHR wrapped in Axios, but I am correct in using the debug tool access interface to return
![image](https://user-images.githubusercontent.com/27654200/110440291-7697cc00-80f3-11eb-9082-afab4b5ee982.png)
