### ISSUE TITLE
Nest can't resolve dependencies of the UsersService (?)

### ISSUE THREAD

**Issue by Ahmed2Game** [nestjs/nest#661]
hi 
i get this error 
Nest can't resolve dependencies of the UsersService (?). Please verify whether [0] argument is available in the current context.

this my users.service.ts
<pre><code>
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { User } from './interfaces/user.interface';
import { CreateUserDto } from './dto/create-user.dto';

@Injectable()
export class UsersService {
  constructor(@InjectModel('User') private readonly userModel: Model<User>) {}

  async create(createUserDto: CreateUserDto): Promise<User> {
    const createdUser = new this.userModel(createUserDto);
    return await createdUser.save();
  }

  async findAll(): Promise<User[]> {
    return await this.userModel.find().exec();
  }
}

</code></pre>

and this my users.module.ts

<pre><code>
import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { UsersController } from './users.controller';
import { UsersService } from './users.service';
import { UserSchema } from './schemas/user.schema';

@Module({
  imports: [MongooseModule.forFeature([{ name: 'User', schema: UserSchema }])],
  controllers: [UsersController],
  providers: [UsersService],
})
export class UsersModule {}
</code></pre>

**Comment by kamilmysliwiec** [comment]
The `mongoose` package has not been published yet. That's why inside `@InjectModel()` decorator, you should use a schema instead of a name (see here: https://docs.nestjs.com/techniques/mongodb)

**Comment by Ahmed2Game** [comment]
i used this https://docs.nestjs.com/v5/recipes/mongodb and work good

**Comment by menme95** [comment]
I have the same problem but I am not able to fix it. I was working with 5 beta, and I update today and it doesn't work.

![image](https://user-images.githubusercontent.com/22968155/39992653-d3468470-5773-11e8-8ea3-c6ba1c71386e.png)

![image](https://user-images.githubusercontent.com/22968155/39992752-10853d90-5774-11e8-9642-035d42e00364.png)

![image](https://user-images.githubusercontent.com/22968155/39992701-f25925b6-5773-11e8-9388-d87070db4cd3.png)

The documentation <a href="https://docs.nestjs.com/recipes/mongodb"> recipes/mongoose </a> show some providers, but in your mongoose module <a href="https://docs.nestjs.com/techniques/mongodb"> techniques/mongoDB</a> there aren't any, are there necesary too?

**Comment by menme95** [comment]
@Ahmed2Game @kamilmysliwiec sorry, I don't know if I should mention you, comment here or open other issue because this is closed

**Comment by JSMonk** [comment]
@kamilmysliwiec, still broken in js application.

user.schema.js
`import * as mongoose from "mongoose";

export const UserSchema = new mongoose.Schema({
  firstName: {
    type: String,
    required: true,
  },
  lastName: {
    type: String,
    required: false,
  },
  email: {
    type: String,
    required: false,
    unique: true,
  },
  password: {
    type: String,
    required: false,
  },
});

UserSchema.virtual("createdAt").get(function() {
  return new Date(this._id.getTimestamp());
});

export const UserModel = { name: "User", schema: UserSchema };`

user.module.js
`import { Module } from "@nestjs/common";
import { MongooseModule } from "@nestjs/mongoose";
import { PassportModule } from "@nestjs/passport";
import { UserModel } from "./user.schema";
import { UserService } from "./user.service";
import { CryptographyModule } from "../cryptography/cryptography.module";
import { UserController } from "./user.controller";

@Module({
  imports: [
    CryptographyModule,
    PassportModule,
    MongooseModule.forFeature([UserModel]),
  ],
  exports: [UserService],
  providers: [UserService],
  controllers: [UserController],
})
export class UserModule {}`

user.service.js
`import { Injectable, Dependencies } from "@nestjs/common";
import { InjectModel } from "@nestjs/mongoose";
import { ConfigService } from "nestjs-config";
import { UserSchema } from "./user.schema";
import { CryptographyService } from "../cryptography/cryptography.service";

@Injectable()
@Dependencies(CryptographyService, ConfigService, InjectModel(UserSchema))
export class UserService {
  constructor(cryptographyService, configService, userRepository) {
    this._cryptographyService = cryptographyService;
    this._configService = configService;
    this._userRepository = userRepository;
  }`

<img width="1680" alt="screen shot 2019-02-11 at 5 28 25 pm" src="https://user-images.githubusercontent.com/10776615/52573425-cd524f00-2e22-11e9-85e9-bac68c8d80ca.png">

**Comment by kamilmysliwiec** [comment]
You should pass model name instead of a schema since `@nestjs/mongoose` has been published already. See https://docs.nestjs.com/techniques/mongodb **Model injection**

**Comment by JSMonk** [comment]
@kamilmysliwiec, same problem. + Old inject version inside documentation.

<img width="1086" alt="screen shot 2019-02-11 at 5 44 34 pm" src="https://user-images.githubusercontent.com/10776615/52574338-bca2d880-2e24-11e9-82e9-c1ec08bd3f7d.png">

**Comment by JSMonk** [comment]
```
import { Injectable, Dependencies } from "@nestjs/common";
import { InjectModel } from "@nestjs/mongoose";
import { ConfigService } from "nestjs-config";
import { UserSchema } from "./user.schema";
import { CryptographyService } from "../cryptography/cryptography.service";

@Injectable()
@Dependencies(CryptographyService, ConfigService, InjectModel("User"))
export class UserService {
  constructor(cryptographyService, configService, userRepository) {
    this._cryptographyService = cryptographyService;
    this._configService = configService;
    this._userRepository = userRepository;
  }
}
```
<img width="1680" alt="screen shot 2019-02-11 at 5 46 58 pm" src="https://user-images.githubusercontent.com/10776615/52574472-0f7c9000-2e25-11e9-801f-ce775dc07a8d.png">

**Comment by kamilmysliwiec** [comment]
Well, it seems that JS code snippet hasn't been updated. I need to fix it asap.

**Comment by JSMonk** [comment]
@kamilmysliwiec, I’ve just madden PR for the listing update.
