### ISSUE TITLE
Can nestjs use with other react SSR framework nextjs together? if can ,how use?

### ISSUE THREAD

**Issue by mickeyzhou** [nestjs/nest#662]

**Comment by whtiehack** [comment]
Nestjs is just a development framework. Help you manage the structure and dependencies.
I think you need to look at the documentation.
https://docs.nestjs.com/v5/
https://docs.nestjs.com/v5/execution-context

**Comment by mickeyzhou** [comment]
Thanks @whtiehack ,  I would like to use nestjs manage my node code , I also need to use nextjs implement SSR function , has anyone  use  in this scenario...

**Comment by kamilmysliwiec** [comment]
I'd suggest using execution context feature to take advantage of Nest ecosystem but leave the rest to the nextjs.

**Comment by mickeyzhou** [comment]
@kamilmysliwiec , thanks your suggest!
