### ISSUE TITLE
Rails like console for Nestjs

### ISSUE THREAD

**Issue by asemoon** [nestjs/nest#6620]
## Feature Request

We are running Nestjs for a few our of applications on production now and we are pretty happy with it. However, a lot of our engineers are used to using Rails console to be able to debug issues, export data, and see the state of data and application status. As we have more and more usage on our applications this is becoming more important for us. I was wondering if there are any plans on your roadmap for this? I see there are some workarounds provided by third-party packages, however, this seems to be an important built-in feature needed for applications running in production.

**Comment by kamilmysliwiec** [comment]
There are currently no plans to add it.

Please search through some of our old issues on this (this has been discussed several times in the past).
