### ISSUE TITLE
Inject CONTEXT from @nestjs/graphql block service 's constructor

### ISSUE THREAD

**Issue by sinbargit** [nestjs/nest#6625]
Inject CONTEXT from @nestjs/graphql block service 's constructor

Inject CONTEXT from @nestjs/graphql, then set a member variable,the variable is undefined.
```
import { Injectable, Inject } from '@nestjs/common';
import { CONTEXT } from '@nestjs/graphql'
@Injectable()
export class AppService {
@Inject(CONTEXT) private readonly context
constructor(){
console.log('i am test crom------------------------------')
console.log('i am test crom------------------------------')
console.log('i am test crom------------------------------')
console.log('i am test crom------------------------------')
console.log('i am test crom------------------------------')
}
getHello(): string {
    return 'Hello World!';
  }
}
```
There no print after nest start, but after I remove the Inject CONTEXT, it works fine
The simple demo has upload at https://github.com/sinbargit/nestjstest

**Comment by jmcdo29** [comment]
`CONTEXT` is request scoped, so nothing will be created until you send in a request.

**Comment by sinbargit** [comment]
@jmcdo29  So, how it works, if there is a @cron behind the @Inject(context). Does the constructor still do not be called? but what is the execution context of the cron

**Comment by jmcdo29** [comment]
You shouldn't have any request scoped dependencies in a cron job (or inside anything that runs outside of the request lifecycle) of this is the case, `undefined` will be injected. This is the expected functionality

**Comment by sinbargit** [comment]
I understand the context is undefined since it is the request scope. But the constructor should be call, the current situation is the Cron still run, but the constructor of it was never be called.
something like :
```
import { Injectable, Inject } from '@nestjs/common';
import { CONTEXT } from '@nestjs/graphql'
@Injectable()
export class AppService {
@Inject(CONTEXT) private readonly context
constructor(){
console.log('i am test cron------------------------------')
console.log('i am test cron------------------------------')
console.log('i am test cron------------------------------')
console.log('i am test cron------------------------------')
console.log('i am test cron------------------------------')
}
@Cron()
getHello(): string {
    return 'Hello World!';
  }
}
```

**Comment by kamilmysliwiec** [comment]
I've just updated the `@nestjs/schedule` to ignore any request-scoped providers to avoid any confusion in the future.
