### ISSUE TITLE
Set view engine for once module

### ISSUE THREAD

**Issue by aventez** [nestjs/nest#6628]
How to set view engine like `setViewEngine(engine: string)` from `NestExpressApplication` only for once module?

**Comment by jmcdo29** [comment]
What's the use case of setting per module rather than for the entire server?

**Comment by aventez** [comment]
We're writing API that implements a lot of endpoints and we need to create just one view in HBS (change password view). It's small application, then we don't have to use big frontend solutions like React/Vue.JS etc.

**Comment by jmcdo29** [comment]
I still don't see the need to register a view engine for a single module. If you install it globally it won't activate unless you use the `@Render()` decorator, or use `res.render`, so it's not like there will be any slowdown to the response

**Comment by aventez** [comment]
Great, then now we're clear - that's exactly what I want. Thanks for the explanation!
