### ISSUE TITLE
nested object in body of multipart/form-data not validated

### ISSUE THREAD

**Issue by ahmedsaiddev50** [nestjs/nest#6635]
## Bug Report
DTO nested validation only work 'application/json' and not working with ' multipart/form-data '
 
## DTO file
export class nameDTO {

  @MinLength(2)
  @MaxLength(40)
  readonly ar: string;

  @MinLength(2)
  @MaxLength(40)
  readonly en: string;
}

export class branchDto {

  @Type(() => nameDTO)
  @ValidateNested()
  readonly name: nameDTO;

 @IsOptional()
  readonly photo: any;

  @IsString()
  @IsOptional()
  readonly sku: string;

}
## Controller
  @Post()
  @ApiConsumes('multipart/form-data', 'application/json')
  @UseInterceptors(FileInterceptor('photo'))
  addOne(
    @UploadedFile() photo: any,
    @Body() payload: branchDto,
  ): any {
    console.log(photo);
    console.log(payload);
    return payload;
  }

##Error
name.nested property name must be either object or array

## Expected behavior
When I send data as 'application/json' without the photo file , the nested validation (name) works fine, but when i send data  ' multipart/form-data ' even without photo file i found that the name handled as string and not transformed to object
branchDto {
  sku: '',
  name: '{ "ar": "dddd","en": "ddddd"}'
}

**Comment by Tony133** [comment]
Hi @ahmedsaiddev50, [here](https://github.com/nestjs/nest/tree/master/sample/29-file-upload) you can find a working example for uploading files.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by ahmedsaiddev50** [comment]
Hi @Tony133 , thanks for your fast response, my problem with validation nested object inside body when using multipart/form-data even without uploading files, i will use discord thanks

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
