### ISSUE TITLE
Logger value ignored when calling createMicroService after createApplicationContext

### ISSUE THREAD

**Issue by ColinMorris83** [nestjs/nest#6636]
## Current behavior

Create a new app with logger false. This correctly does no logging.
Then create a new microservice. This will also do no logging.

## Input Code
```ts
const appContext: INestApplicationContext = await NestFactory.createApplicationContext(
    AppModule,
    {
      logger: false,
    }
  );

const microservice: INestMicroservice = await NestFactory.createMicroservice<MicroserviceOptions>(AppModule, {
    // logger defaults to true, but even if uncommented there is no logging due to the setting of false previously
    // logger: true, 
    transport: Transport.KAFKA,
});
```

## Expected behavior
The microservice instance should have logging

## Environment

<pre><code>
Nest version: 7.6.13

 
For Tooling issues:
- Node version: 12.19.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Logger is globally scoped to the Node.js process, not to a Nest application context (and thus, you can use its static methods, e.g., `Logger.warn('...`)). We don't plan to change this as you should never run multiple Nest apps in a single process (as there's simply no reason to do that).
