### ISSUE TITLE
@nestjs/mapped-types is not found after using  `nest g resource user`

### ISSUE THREAD

**Issue by GregEisenberg** [nestjs/nest#6642]
## Bug Report
After running `nest g resource user` to create a new resource module for "user" (with controller, service and entities stubbed) the pre-generated `update-user.dto.ts` fails to resolve `import { PartialType } from '@nestjs/mapped-types';`

## Current behavior
Assuming  `npm i -g @nestjs/cli`  has been run 
1. run `nest new test-project` to create a test project 
2. run `npm install --save @nestjs/typeorm typeorm postgres pg`  to get TypeOrm and Postgres support in place 
3. run  `nest g resource user` to create a user module 
4. run `npm start run` to test 

(its possible #2 is not a required step of the repro)

## Expected behavior
awesomeness 

## Actual behavior
```
src/user/dto/update-user.dto.ts:1:29 - error TS2307: Cannot find module '@nestjs/mapped-types' or its corresponding type declarations.

1 import { PartialType } from '@nestjs/mapped-types';
                              ~~~~~~~~~~~~~~~~~~~~~~
```

## Possible Solution
worked around by manually running 
  `npm i --save @nestjs/mapped-types`
which is fine - but no place in the docs does it reference that this package would have to be installed separately - thus I decided I would submit this issue. 

## Environment

<pre><code>
Nest version:
> nest --version
7.5.6

- Platform:   Windows WSL 2 using Ubuntu 20.04.2 LTS

</code></pre>

BTW - thanks for the awesome NestJS platform!

**Comment by jmcdo29** [comment]
@kamilmysliwiec should we add this as a step to the resource generation (check if `@nestjs/mapped-types` is installed and install it if not) or just add a note in the docs saying this package should be installed?

**Comment by GregEisenberg** [comment]
If you are asking me - my opinion is that since the resource generation code inserts `import { PartialType } from '@nestjs/mapped-types';` then the resource generation code is responsible to (check if @nestjs/mapped-types is installed and install it if not)

**Comment by kamilmysliwiec** [comment]
Added in `@nestjs/schematics@7.3.0`

**Comment by HolikovOleksandr** [comment]
In my case
**@nestjs/mapped-types**
did not install with the command
**nest g resource user** 
because he needed administrator rights for some reason.

Issue:
**sudo nest g resource user**

Mac/Linux

**Comment by micalevisk** [comment]
@HolikovOleksandr everything went fine here on Linux:

```bash
npm i -g @nestjs/cli@latest # 10.3.0
nest new test-project
cd test-project
npm install --save @nestjs/typeorm typeorm postgres pg
nest g resource user
npm run start
```

Please provide a minimum reproduction if you want us to take a look on it again.
