### ISSUE TITLE
Node hangs upon exit when using @Sse and app.enableShutdownHooks()

### ISSUE THREAD

**Issue by PeS82** [nestjs/nest#6643]
## Current behavior

When annotating route with `@Sse('tada')` and using `app.enableShutdownHooks();` and there are clients connected to the SSE endpoint the process does not exit when SIGINT (or possibly other) request to terminate is received.

One must press `Ctrl+C` twice to terminate. Or click Stop button in Webstorm twice.

When there are no clients connected to the endpoint the process is terminated correctly.

## Input Code
```ts
import {NestFactory} from "@nestjs/core";
import {BeforeApplicationShutdown, Controller, Get, Injectable, MessageEvent, Module, Sse} from "@nestjs/common";
import {Subject} from "rxjs";
import {distinctUntilChanged, share} from "rxjs/operators";

@Injectable()
export class TestSseService implements BeforeApplicationShutdown {
    private events = new Subject<MessageEvent>();
    private c = 0;
    private readonly interval: NodeJS.Timeout;

    constructor() {
        this.interval = setInterval(() => {
            this.events.next({
                retry: 3,
                type: 'message',
                id: `id-${++this.c}`,
                data: {message: `number ${this.c}`}
            })
        }, 1000);
    }

    get events$() {
        return this.events.pipe(distinctUntilChanged(), share());
    }

    beforeApplicationShutdown(signal?: string): any {
        clearInterval(this.interval);
        console.log('App shutdown');
    }

}

@Controller('/api/test-sse')
export class TestSseController {
    constructor(private sseService: TestSseService) {
    }

    @Sse('sse')
    serverSideEvents() {
        return this.sseService.events$;
    }

    @Get('hello')
    getHello() {
        return 'howdy';
    }
}

@Module({
    controllers: [TestSseController],
    providers: [TestSseService]
})
export class TestSseModule {
}


async function bootstrap() {
    const app = await NestFactory.create(TestSseModule);
    app.enableShutdownHooks();
    await app.listen(3000);
}

bootstrap();
```

## Expected behavior

App terminates when asked to.

## Possible Solution

IDK

## Environment

<pre><code>
Nest version: 7.5.6
 
For Tooling issues:
- Node version: 12.3.1
- Platform: Windows
</code></pre>

Oh, and thx for Nest.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by PeS82** [comment]
The code provided is not enough?

**Comment by jmcdo29** [comment]
When providing code for a [reproduction](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction/), especially for a framework, a git repo is usually appreciated

**Comment by PeS82** [comment]
OK, I really do not get it but this code was honestly hanging in the morning. The same one does not now. Closing.

**Comment by PeS82** [comment]
And... we're back. The difference between morning and now is that in the morning there were clients connected to the SSE endpoint.

I will edit the description and prepare repo.

**Comment by PeS82** [comment]
Sigh. While preparing the repo I wrote simple client in vanilla javascript and in that one it works as expected as opposed to when our Angular client is connected.

Therefore, closing again 😃
