### ISSUE TITLE
Update socket.io to 4.0 in @nestjs/platform-socket.io package

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#6649]
Following up from https://github.com/nestjs/nest/issues/5676 socket.io 4.0 has been released with some breaking api changes:

https://socket.io/blog/socket-io-4-release/

**Comment by Tony133** [comment]
I think socket.io 4.0 compatibility will be added either in the next major version of Nest v8 ♥ ️ 🚀 or in the future, however the next version will be compatible with socket.io 3.x.

**Comment by kamilmysliwiec** [comment]
Fixed here https://github.com/nestjs/nest/pull/6349
