### ISSUE TITLE
Update socket.io version 4.0.0 to @nestjs/platform-socket.io package

### ISSUE THREAD

**Issue by BuiTanLan** [nestjs/nest#6656]
Hi Nestjs team!

Socket.io team recently updated their package to 4.0.0 but @nestjs/platform-socket.io still depends on the version 2.4.1. So I hope  Nestjs update your package soon.

**Comment by Tony133** [comment]
Hi @BuiTanLan, socket.io 4.0 compatibility will be added either in the next major version of Nest v8 ♥ 🚀

see issues [here](https://github.com/nestjs/nest/issues/6649)
