### ISSUE TITLE
Add missing precondition required (428) exception class 

### ISSUE THREAD

**Issue by spin** [nestjs/nest#6657]
## Is your feature request related to a problem? Please describe.
Related to RESTful API error handling.
We make use of HTTP conditional requests to implement concurrency control (e.g If-Match header + ETag). Except for respond with `HTTP 412 Precondition Failed` when the condition is not fulfilled, we also like to handle cases that the conditional header is required.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/428

## Describe the solution you'd like
Add a new exception class for precondition required.
Related to #5113

## What is the motivation / use case for changing the behavior?
To implement conditional request use cases in a more complete way.

**Comment by kamilmysliwiec** [comment]
As creating your own exceptions based on the existing `HttpException` is fairly straightforward (and explained in the docs), we decided to not add more built-in HTTP exceptions (mapping to HTTP errors) as they are unnecessarily bloating the codebase.
