### ISSUE TITLE
Multi instances of the same module are instantiated when provided as an import of a DynamicModule

### ISSUE THREAD

**Issue by ramyhhh** [nestjs/nest#6660]
## Current behavior
DynamicModule does not override same static type Module which cases the container to have to instances of the same metatype.

## Input Code

```ts
@Module({ })
export class LibModule { } 

@Module({
    imports: [LibModule] //importing from here allows the module to be used as StaticType module
})
export class AppModule {
    static register(options): DynamicModule {
        return {
            module: AppModule,
            imports: [{ module: LibModule }], //importing as a dynamic module which is considered to be different from the above import
        };
    }
}

```

## Expected behavior
DynamicModule should override StaticModule imports and only instantiate one instance. If not a complete override perhaps a merge between the two metadata.

## Possible Solution
Remove the dynamic property when calculating ModuleToken, to make the token based only on meta type and not metadata. I can't see why DynamicModule.module is not acting as a key to prevent duplicates.

Remove this and it works fine in most cases. 
https://github.com/nestjs/nest/blob/58735f943434d6eea240d6410a07d61389b6fd4e/packages/core/injector/module-token-factory.ts#L18

I'm sure this requires more thinking into it, but instantiating two modules of the same type is not an expected behaviour at least it should throw and error, or implement a strategy to choose between the two metadata.

**Comment by ramyhhh** [comment]
## Alternative solution
One another workaround is to to pass the NestContainer to NestFactoryStatic instead of instantiating it, where the passed container could allow for custom instance loader logic.
Currently there are 3 places where the container is instantiated:
1. NestFactoryStatic.create
2. NestFactoryStatic.createMicroservice
3. NestFactoryStatic.createApplicationContext
And three of them could possibly provide more control by being able to pass the container object directly.

**Comment by kamilmysliwiec** [comment]
This is the expected behavior, `LibModule` !== `{ module: LibModule }`. Also, using such a construction doesn't make any sense so there's simply no reason to change this.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
