### ISSUE TITLE
This inside static method

### ISSUE THREAD

**Issue by Igrokqq** [nestjs/nest#6662]
https://github.com/nestjs/nest/blob/58735f943434d6eea240d6410a07d61389b6fd4e/packages/common/services/logger.service.ts#L77

I got an error "this.printMessage() is not a function". I've started to research why I see this error. I was amazed when I've seen static log() { this.printMessage() }. Fix it please

**Comment by jmcdo29** [comment]
If `this` is used in a `static` method, Typescript uses the `static` context for other `this.` methods, meaning
```ts
class Logger {

  static log(message: string) {
	this.printMessage(message);
  }
  
  private static printMessage(message: string) {
    console.log('Printing message');
    console.log(message);
  }
}
```
Is valid code. Please provide a [minimum reproduction](http://minimum-reproduction.wtf) that shows the error you're facnig.

**Comment by Igrokqq** [comment]
1. App.Dockerfile
`FROM node:12-alpine

ENV NODE_ENV development

WORKDIR /var/www/app
COPY . /var/www/app/

RUN apk --update add g++ gcc libgcc libstdc++ linux-headers make python bash

RUN npm install && npm install --quiet node-gyp -g
RUN npm rebuild bcrypt --build-from-source

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
`

2. docker-compose
`version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/App.Dockerfile
    container_name: app
    command: bash -c "npm run dev"
    volumes:
      - ./:/var/www/app:cached
      - /var/www/app/node_modules # anonymous volume for node_modules only
    restart: always
    ports:
      - 3000:3000`
3. app.module
`  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    MongooseModule.forRoot(process.env.MONGODB_URL || '', {
      connectionFactory: (connection: Mongoose.Connection) => {
        connection.on('error', (error: any) => {
          Logger.error(error);
        });
        connection.on('reconnectFailed', () => {
          Logger.error('Reconnect to Mongodb has been failed');
        });
        connection.on('attemptReconnect', () => {
          Logger.log('attempt to reconnect Mongodb');
        });
        connection.on('reconnect', () => {
          Logger.log('reconnect to Mongodb');
        });
        connection.on('open', () => {
          Logger.log('Mongodb is connected successfully');
        });

        return connection;
      },`

Logger was imported from @nestjs/common. Locally it works fine but when I run it inside a docker container my server break and errors in my terminal are forward to logger.service file to static methods (log, warn, error, ...etc)

**Comment by jmcdo29** [comment]
Did you look at the link I added? 

> A minimum reproduction repository is a git repository that can be shared publicly (doesn’t expose private business logic), shows the problem you’re running into, and has the fewest dependencies installed possible.

While adding the code to the issue can sometimes be helpful, if you're  looking for us to run this, provide a repository with instructions on _how_ to run it.

**Comment by Igrokqq** [comment]
Sorry,  my bad. Okay

**Comment by kamilmysliwiec** [comment]
Using `this` in this context is valid. That means, I believe this issue isn't related to the framework but rather to your code. If you come up with a minimum reproduction repository that shows the incorrect behavior, please, create a new issue and link it there.
