### ISSUE TITLE
decorators 

### ISSUE THREAD

**Issue by Rebiss** [nestjs/nest#6673]
Hi !!
Native decorators must appear in Javascript. As far as I understand, they are different than Typescript decorators.
Could this be a problem in the future?

**Comment by jmcdo29** [comment]
If it's a problem for us, it's a problem for Angular, TypeORM, MikroORM, TypeGoose, class-validator, class-transformer, and many others. _If_ that problem arises, we'll deal with it then.

**Comment by Rebiss** [comment]
okay thanks
