### ISSUE TITLE
security issue with js-yaml 3.12.0

### ISSUE THREAD

**Issue by KrishnanSriram** [nestjs/nest#6686]
## Current behavior
JFrog report security vulnerability with js-yaml version 3.12.0
JS-YAML contains a flaw in the storeMappingPair() function in lib/js-yaml/loader.js that is triggered when handling certain object properties as map keys. This may allow a context-dependent attacker to execute arbitrary code.

## Expected behavior
Use js-yaml: 3.14.0

## Possible Solution
Bare min requirement version of js-yaml is 3.13.1

**Comment by kamilmysliwiec** [comment]
This isn't related to the framework
