### ISSUE TITLE
Upgrade to NATS.js 2.0

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#6690]
## Feature Request

nats.js 2.0 has been released and is not api-compatible with nats.js 1.x

Migration guide: https://github.com/nats-io/nats.js/blob/master/migration.md

I already updated the docs to install 1.x.

**Comment by kamilmysliwiec** [comment]
This has been addressed in this PR https://github.com/nestjs/nest/pull/6349 and will be published as part of the next release.
