### ISSUE TITLE
Microservice's ClientProxies should make client instances public

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#6692]
## Feature Request

I am really really sorry to open the [same issue](https://github.com/nestjs/nest/issues/6671) again but comments were closed so there was no room left for discussion.

Each client, e.g. `ClientNats` holds a client instance that is protected. This instance should be public in my opinion. E.g. the nats.js client has events that are otherwise not accessible:

```
natsClient.on('disconnect', () => {
  console.log('disconnect')
})
```

Personally I see no advantage of preventing the user to access the instance directly. As a user I would like to keep the simplicity of Nest.js dependency injection and ready-to-use modules without the need of extending classes for solving simple and common issues.

If you agree I could create a PR that makes the client-instances of all clients public. 

This would also fix #6671

**Comment by kamilmysliwiec** [comment]
This has been discussed several times in the past and that's why there's no reason to have the same conversations over and over, as I also have limited time in my life.

**Comment by jmcdo29** [comment]
[Link](https://github.com/nestjs/nest/issues/3913)
