### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by Martodox** [nestjs/nest#67]
Hi.
How would you guys go about to integrate swagger with nest.js?

**Comment by kamilmysliwiec** [comment]
Hi @Martodox,
Definitely needed! I'll make it in the future. Stay tuned :smile:

**Comment by Martodox** [comment]
@kamilmysliwiec The project that I had started at work copied my approach from my another project: [sample file](https://github.com/Martodox/cloudrm-server/blob/develop/src/components/session-management/session-management.js) with swagger-jsdoc. It does the job, but it would be cool to integrate it with TS decorators (just like java swing).

**Comment by cojack** [comment]
@Martodox hmm if there will be an solution to inject some "middleware" into http controllers, there will be option to create independent module for `nest` to generate a `swagger.json` file as output ;>

@kamilmysliwiec an extra events like hooks ;) hmmm ;>

**Comment by kamilmysliwiec** [comment]
Hi guys,
Swagger module is in beta stage. Hope to share it with you asap :)

**Comment by KatSick** [comment]
@kamilmysliwiec any updates on swagger module ? maybe i can help at least in testing ?

**Comment by irissoftworks** [comment]
Hey guys. I have to say that Nest looks really good. Kudos to the dev team. 
Good architecture, and learning curve is minimal if Angular is your background. 
Not having swagger integration is a major issue though (pretty much the only issue I found so far).
Everyone who's got Angular skills will want to generate their client code and use swagger tooling. 
Maintaining a swagger spec in sync manually is a nightmare, so if this issue could be fixed, then Nest ( combined with typeorm ) would probably be the ultimate way to go on the node side of things. 
I am currently using TSOA which provides a swagger spec from the route decorators and it's fairly mature. 
Decorators aren't too different from the ones on Nest. I didn't investigate how much of that code would be portable ? 
Anyway, let me know if there's anything I can do to speed this up, as the above poster, even if it's just testing.

**Comment by ericzon** [comment]
@irissoftworks I think Swagger integration is ready on release/v4 branch. I hope it would be ready soon to start playing with.

**Comment by irissoftworks** [comment]
Great! Apologies everyone, I went through the other branch yesterday, but I think I must have missed it. 

I realized it was actually mentioned on the release ticket. If anyone else is looking, this is #120 .

Looking forward to it!

**Comment by cojack** [comment]
@kamilmysliwiec how does v4 influence on this issue?

**Comment by kamilmysliwiec** [comment]
Hi @cojack,
The `@nestjs/swagger` package is in alpha version, I need to publish it as a separated repo :slightly_smiling_face:

**Comment by cojack** [comment]
@kamilmysliwiec waiting so much :+1:

**Comment by zackarychapple** [comment]
@valorkin this is what Georgii needed for our swagger docs. :)

**Comment by valorkin** [comment]
As far as I know, swagger was renamed to Open API

**Comment by Jorgevillada** [comment]
could you share the progress of the swagger documentation and tell us how we can help you?

**Comment by VinceOPS** [comment]
@kamilmysliwiec 
Yup, would like to help too. Nestjs is a very good project. Slowly starting to enjoy writing Express API's with it :D. Thanks for your work, Kamil.

**Comment by MaheshCasiraghi** [comment]
@kamilmysliwiec any chance you can share the work in progress of the tutorial?

**Comment by darioxtx** [comment]
Hi,

here is example of basic usage: 

```typescript
@Controller('status')
@ApiUseTags("status") // OpenAPI tag property
export class StatusController {

    @Get("/status")
    @ApiOperation({title: "Returns API status"})
    @ApiResponse({status: HttpStatus.OK, type: StatusModel, description: "Returns API status"})
    @ApiResponse({status: "default", type: RequestException, description: "Error Response"})
    async getStatus(@Req() req, @Res() res) {
        return await this.statusService.getStatus();
    }
}

//model definition
export class StatusModel {

    @ApiModelProperty()
    public status: string;

    @ApiModelProperty()
    public uptime: Date;

    @ApiModelProperty({items: {type: 'string', enum: SomeEnum}})
    public items: SomeEnum[];
}

@Controller('swagger')
@ApiUseTags("swagger") // OpenAPI tag property
export class SwaggerController {

    @Get("/status")
    @ApiOperation({title: "Returns swagger json"})
    @ApiResponse({status: HttpStatus.OK, type: Object, description: "Returns swagger json"})
    @ApiResponse({status: "default", type: RequestException, description: "Error Response"})
    async getSwagger(@Req() req, @Res() res) {
        let apiDoc = SwaggerModule.createDocument(app, {
            //TODO: swagger: '2.0',
            info: {
                description: "Customer Portal API",
                version: "1.0.0",
                title: "Customer Portal API",
            },
            basePath: "/api"
        });
        apiDoc['swagger'] = '2.0';

        return res.json(apiDoc);
    }
}
```

Hope it helps to start

**Comment by Jorgevillada** [comment]
You can also see an example here. https://github.com/nestjs/swagger/issues/4

**Comment by MaheshCasiraghi** [comment]
Hello @darioxtx: 2 questions related to your answer (sorry for noobying, I am kind of new to nest :-)): 

1) how do you have access to (i.e., inject) the 'app' object within the swagger controller?
2) what is the RequestException object? 

Thank you!

**Comment by darioxtx** [comment]
My bad, you should use SwaggerModule in app bootstrap function.
I updated example.

**Comment by MaheshCasiraghi** [comment]
Cool @darioxtx, thank you. I ended up following a separate solution, based on the thread @Jorgevillada proposed, with some due modifications. Here my server.ts:

`import * as bodyParser from 'body-parser';
import { NestFactory } from '@nestjs/core';
import { ApplicationModule } from './modules/app.module';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

const express = require('express');
const cors = require('cors');
const swaggerUI = require('swagger-ui-express');

const showExplorer = true;
const appHost = 'localhost:3000';

async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule);
  const Eapp = express();

  Eapp.use(cors());
  app.use(cors());
  app.use(bodyParser.json());

  const documentBuilder = new DocumentBuilder();
  documentBuilder.addBearerAuth('Authorization', 'header');
  documentBuilder.setHost(appHost);
  const document = SwaggerModule.createDocument(app, documentBuilder.build());
  Eapp.use('/swagger', swaggerUI.serve, swaggerUI.setup(document, false));
  Eapp.use('/api-docs', (req, res, next) => res.send(document));

  await Eapp.listen(3001);
  await app.listen(3000);
}

bootstrap();`

**Comment by kamilmysliwiec** [comment]
Here's an example https://docs.nestjs.com/recipes/swagger 🙂 I hope it's enough for now!

**Comment by qinyang1980** [comment]
@kamilmysliwiec, amazing work. This is just what I want. 
You must have been a Java Sprint Boot developer.

**Comment by LuukMoret** [comment]
@kamilmysliwiec Yes, very nice indeed! Any ETA on the GraphQL recipe? Really curious about that one as well

**Comment by kamilmysliwiec** [comment]
@qinyang1980 one time 😄
@LuukMoret in progress 💪

**Comment by marcelfalliere** [comment]
Amazing thread :) 

quick question : how do you generate a static website of the documentation ? So far, it's only available when running the nest server. I don't wish to expose the swagger to everyone when starting the server.

**Comment by arielweinberger** [comment]
@marcelfalliere 
`SwaggerModule.createDocument()`, take a look at the example above posted by @darioxtx .
