### ISSUE TITLE
need to make prefix for collections 

### ISSUE THREAD

**Issue by Ahmed2Game** [nestjs/nest#670]
hi 
i need make dynamic prefix for collections and will get it from Body or header sent from front end
so how can make it  

<pre><code>
import * as mongoose from 'mongoose';

export const UserSchema = new mongoose.Schema({
  _id: {type: Number, required: true},
  name: {type: String, required: true, unique: true},
  email: {type: String, required: true, unique: true},
  password: {type: String, required: true},
  remember_token: {type: String},
  is_active: {type: Boolean, default: false},
  invite_by: {type: Number},
  birth_date: {type: Date},
  gender: {type: String, enum: ['Male', 'Female']},
  address: {type: String},
  gold_num: {type: Number, min: 0, max: 20000000},
  gold_buy: {type: Number, min: 0, max: 20000000},
  friends_id: [{type: Number}],
  blocked_id: [Number],
  avatar: {type: String},
}, { collection: prefix + '_users', timestamps: { createdAt: 'created_at', updatedAt: 'update_at' } });
</pre><code>

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by AntoineMaitre** [comment]
Maybe wrap this piece of code in a function that will take your prefix as parameter so that you can use your prefix inside the function and return your prefixed schema/collection ?

**Comment by Ahmed2Game** [comment]
like this 
```
function prefixedSchema(@Req() req) {
  return req.headers.prefix;
}

const  prefix = prefixedSchema;
```

**Comment by Ahmed2Game** [comment]
i can't use Req in schema file

**Comment by kamilmysliwiec** [comment]
Please, use StackOverflow for such questions. https://stackoverflow.com/questions/tagged/nestjs
