### ISSUE TITLE
Export INestApplication

### ISSUE THREAD

**Issue by mlazuardy-dyned** [nestjs/nest#6709]
i'm sorry if there is a question like that has been asked by another user.

inside main.ts (bootstrap) there is a instance of Nest application in 
```
const app = await NestFactory.create(AppModule);
```

can i ( or is it safe ) to export INestApplication that can be use inside another file outside DI Lifecycle ? something like this.

let app: INestApplication;

```
const nf = await NestFactory.create(AppModule);
app = nf;
```

Thanks.

**Comment by jmcdo29** [comment]
It's generally fine to do if you have a reason for it.

In the future, please use our [Discord](https://discord.gg/nestjs) for support. We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by mlazuardy-dyned** [comment]
@jmcdo29 thank you sir it works i think, will do in next questions
