### ISSUE TITLE
NO_COLOR not work

### ISSUE THREAD

**Issue by myeveryheart** [nestjs/nest#6712]
## Current behavior
I want disable the color, because my logfile looks like:
<img width="1089" alt="图片" src="https://user-images.githubusercontent.com/6395323/111865657-40840300-89a3-11eb-90ea-86cd8c29ed59.png">

## Input Code
So I set the NO_COLOR environment variable.
But this didn't help.
<img width="597" alt="图片" src="https://user-images.githubusercontent.com/6395323/111865765-e6d00880-89a3-11eb-947e-1afb6df2ecaa.png">

## Expected behavior
I want to disable the color.

## Environment
    "@nestjs/common": "7.6.14",
    "@nestjs/core": "7.6.14",
    "@nestjs/jwt": "7.2.0",
    "@nestjs/passport": "7.1.5",
    "@nestjs/platform-express": "7.6.14",
    "@nestjs/swagger": "4.7.16",
    "@nestjs/typeorm": "7.1.5",
 
For Tooling issues:
- Node version: v12.21.0
- Platform: Linux

**Comment by Tony133** [comment]
Hi @myeveryheart, I advise you to leave a minimal reproduction of a clonable git repository.

**Comment by micalevisk** [comment]
@myeveryheart I've tried with `NO_COLOR=''` and it didn't work but `NO_COLOR=' '` does work.

**Comment by myeveryheart** [comment]
@micalevisk Yes, you are right, thanks!!!

**Comment by Albro3459** [comment]
> [@myeveryheart](https://github.com/myeveryheart) I've tried with `NO_COLOR=''` and it didn't work but `NO_COLOR=' '` does work.
> 
> This is due to the following line
> 
> [nest/packages/common/utils/cli-colors.util.ts](https://github.com/nestjs/nest/blob/cf2fbb9a3bfc33af79756182af68ad7dedbaf50d/packages/common/utils/cli-colors.util.ts#L3)
> 
> Line 3 in [cf2fbb9](/nestjs/nest/commit/cf2fbb9a3bfc33af79756182af68ad7dedbaf50d)
> 
>  const isColorAllowed = () => !process.env.NO_COLOR; 
> which should be `const isColorAllowed = () => process.env.NO_COLOR !== undefined` if it is expected to accept empty strings.

THANK YOU!!!!
