### ISSUE TITLE
nest.js nacos How to bond intimately

### ISSUE THREAD

**Issue by magdsnail** [nestjs/nest#6713]
nest.js nacos How to bond intimately?

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for support. We are using GitHub for Bug Reports, Feature Requests, and regressions.

Generally speaking, you'd use it in a similar way you'd use it with Express. I've never heard of nacos, so I can't say much more without samples, and their docs are pretty slim.
