### ISSUE TITLE
module Prefix

### ISSUE THREAD

**Issue by kuangshp** [nestjs/nest#6714]
For example, if there is a front-end module with a front, all the following controllers will add a front, do not need to add a front on every controller. The other admin module operates in a similar way

**Comment by Tony133** [comment]
Hi @kuangshp, if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support. 

Nest's core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by kuangshp** [comment]
> Hi @kuangshp, if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.
> 
> Nest's core team uses GitHub to track bug reports, feature requests, and regressions.

I have no authority to send questions

**Comment by Tony133** [comment]
you don't have to be in a role to ask questions or expose your problem in the discord channel for support, just connect to the link I gave you above, which would be this: https://discord.com/invite/G7Qnnhy

**Comment by jmcdo29** [comment]
There are several issue _like_ this one in our issues. Feel free to search them, we don't plan to implement this any time soon.
