### ISSUE TITLE
can not gzip post response

### ISSUE THREAD

**Issue by myeveryheart** [nestjs/nest#6715]
## Current behavior
According to https://docs.nestjs.com/techniques/compression, I use nginx to compression my api.
The nginx.conf is below:
server {
    listen       80;
    server_name  localhost;
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
        if ( $uri ~ \.html$ ) {
            add_header Cache-Control 'no-store';
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        }
        location ~* \.(js|css|gif|jpg|jpeg|png|webp|svg|ttf|woff|woff2|eot)$ {
            add_header Cache-Control  max-age=315360000000;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        }
    }

    location /api/ {
        proxy_pass http://easy-doctor-api:3000/;

    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

http://easy-doctor-api:3000/ is my backend which is nestjs.
The strange thing is my get method can be gzip, but post method can not.

## Input Code
Get request header:
<img width="529" alt="图片" src="https://user-images.githubusercontent.com/6395323/111894075-c86d1a00-8a42-11eb-93f5-55e0cd07f61d.png">

Get response header:
<img width="289" alt="图片" src="https://user-images.githubusercontent.com/6395323/111894097-e76bac00-8a42-11eb-9771-b4866e581b52.png">

Post request header:
<img width="530" alt="图片" src="https://user-images.githubusercontent.com/6395323/111894128-226ddf80-8a43-11eb-8fc1-bf19b39ea514.png">

Post response header:
<img width="294" alt="图片" src="https://user-images.githubusercontent.com/6395323/111894134-31ed2880-8a43-11eb-8f06-5d404cdbb776.png">

You can see, there's no Content-Encoding: gzip in Post response header.

## Expected behavior
Can gzip post method

## Environment
"@nestjs/common": "7.6.14",
"@nestjs/core": "7.6.14",
"@nestjs/jwt": "7.2.0",
"@nestjs/passport": "7.1.5",
"@nestjs/platform-express": "7.6.14",
"@nestjs/swagger": "4.7.16",
"@nestjs/typeorm": "7.1.5",
 
For Tooling issues:
- Node version: v12.21.0
- Platform:  Linux

**Comment by Tony133** [comment]
Hi @myeveryheart, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

If you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
