### ISSUE TITLE
Enable ClassSerializerInterceptor to be used globally

### ISSUE THREAD

**Issue by slavafomin** [nestjs/nest#6716]
Hello! First of all, thank you for your hard work! Nest.js is an amazing framework and I'm having a lot of pleasure working with it so far.

## Is your feature request related to a problem? Please describe.
Right now, [`ClassSerializerInterceptor`](https://github.com/nestjs/nest/blob/ca487ce9957af729d267ba892459640715c9b11e/packages/common/serializer/class-serializer.interceptor.ts) can only be fully used with the `@UseInterceptors` decorator like [shown](https://docs.nestjs.com/techniques/serialization) in the documentation.

However, it's not very convenient to specify the decorator and to repeat the interceptor configuration in all controllers/actions of the application. This violates DRY principle, creates a lot of repeated code, makes the code harder to read (due to bloat) and makes refactoring/audit harder (because you need to change configuration in multiple places).

I believe, there should be a way to use the `ClassSerializerInterceptor` globally in a friendly manner (like [it works](https://docs.nestjs.com/techniques/validation#auto-validation) with the `ValidationPipe` for example).

Now, it's not possible to specify the `ClassSerializerInterceptor` directly in `app.useGlobalInterceptors()`, because the function expects the instance of the interceptor and not the class itself. I've found a workaround by configuring the global provider this way:

```typescript
@Module({
  providers: [
    {
      provide: APP_INTERCEPTOR,
      useClass: ClassSerializerInterceptor,
    },
  ],
})
export class AppModule {}
```

It works, but it's not possible to specify the configuration object this way. It looks like the only option to specify the default configuration is to actually instantiate the `ClassSerializerInterceptor` class manually, but it's not easy to do, because it has dependencies. Namely it expects a `reflector` instance as a first argument to it's constructor. Also, I can't retrieve this reflector from the DIC manually, because it's DI token is not public:

```typescript
const REFLECTOR = 'Reflector'; // it's not public!

@Injectable()
export class ClassSerializerInterceptor implements NestInterceptor {
  constructor(
    @Inject(REFLECTOR) protected readonly reflector: any,
    @Optional() protected readonly defaultOptions: ClassTransformOptions = {},
  ) {}
}
```

Also, the `ClassSerializerInterceptor` has no API to change the default option after the instance is created, because this property is `protected` and `readonly`.

## Describe the solution you'd like
I would like a simple way to use the `ClassSerializerInterceptor` globally with the ability to specify it's default configuration.

## Teachability, Documentation, Adoption, Migration Strategy
[The documentation](https://docs.nestjs.com/techniques/serialization) needs to be updated to show how the interceptor could be used globally.

## What is the motivation / use case for changing the behavior?
I'm developing a REST application and I would like to transform responses from all controllers automatically if the response object supports the serialization.

---

Thanks!

**Comment by Tony133** [comment]
Hi @slavafomin, if I understand correctly your request is in some world related to this issue #1464 if I'm not mistaken so I think it could be a new feature for the next major version of Nest ♥️🚀 or in the future, doubtful it will be included in Nest v7.x

However it is an interesting feature 👍

**Comment by jmcdo29** [comment]
> Now, it's not possible to specify the ClassSerializerInterceptor directly in app.useGlobalInterceptors(), because the function expects the instance of the interceptor and not the class itself.

But you can get the reflector from the DI context and pass it in

```ts
const reflector = app.get(Reflector);
app.useGlobalInterceptors(new ClassSerializationInterceptor(reflector));
```

> It works, but it's not possible to specify the configuration object this way. It looks like the only option to specify the default configuration is to actually instantiate the ClassSerializerInterceptor class manually, but it's not easy to do, because it has dependencies.

You can use `useFacotry` instead of `useClass` and pass the reflector similar to above

```ts
{
	provide: APP_INTERCEPTOR,
	inject: [Reflector],
	useFactory: (reflector: Reflector) => new ClassSerializationInterceptor(reflector),
}
```

> It works, but it's not possible to specify the configuration object this way.

With the above you can also pass the options

>  Namely it expects a reflector instance as a first argument to it's constructor. Also, I can't retrieve this reflector from the DIC manually, because it's DI token is not public:

The reason for this is actually because if we imported the `Reflector` directly from `@nestjs/core` it would cause a circular dependency between the `@nestjs/common` and `@nestjs/core` packages, so instead, we use `Reflector` as a string, which is what `Reflector.name` comes to. 

> Also, the ClassSerializerInterceptor has no API to change the default option after the instance is created, because this property is protected and readonly.

I believe for this you can use the `@SerializationOptions()` to override options for a specific route
