### ISSUE TITLE
Thrown built-in exception may lose its status code depending on the input parameter

### ISSUE THREAD

**Issue by Wotzhs** [nestjs/nest#6723]
## Bug Report

Thrown built-in exception may lose its status code depending on the input parameter

## Input Code

```ts
throw new NotFoundException("some error message");
// caught exception
{ "statusCode": 404, "message": "some error message", "error": "Not found"}

throw new NotFoundException({"some-key": "some value"});
// caught exception
{ "some-key": "some value" }
```

## Expected behavior

Expect the default properties are there, especially the `statusCode` as it is thrown specifically with the built-in exception, unless it is overwritten, but not for the `statusCode`.

```ts
throw new NotFoundException({"some-key": "some value"});
// caught exception
{ "statusCode": 404, "some-key": "some value", "error": "Not found", "message": null } // or simply:
{ "statusCode": 404, "some-key": "some value", "error": "Not found" }

throw new NotFoundException({"error": "Customized error"});
// caught exception
{ "statusCode": 404, "error": "Customized error", "message": null }

throw new NotFoundException({"error": "Customized error", "statusCode": 500, "message": "some message"});
// caught exception
{ "statusCode": 404, "error": "Customized error", "message": "some message" }

throw new NotFoundException({
  "error": "Customized error", 
  "statusCode": 500, 
  "message": "some message", 
  "a": 1, 
  "b": 2
});
// caught exception
{ 
  "statusCode": 404, 
  "error": "Customized error", 
  "message": "some message",
  "a": 1,
  "b": 2,
}
```

## Possible Solution

Changes to : https://github.com/nestjs/nest/blob/a430adcf080ea4836e1d8abb6efb7a5c3b1a5b4c/packages/common/exceptions/http.exception.ts#L77

```diff
    return isObject(objectOrError) && !Array.isArray(objectOrError)
-     ? objectOrError
+     ? {...objectOrError, statusCode, error: description}
      : { statusCode, message: objectOrError, error: description };
```

## Environment

<pre><code>
Nest version: 7.6.9

 
For Tooling issues:
- Node version: v15.12.0  
- Platform:  Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Wotzhs** [comment]
@kamilmysliwiec I wonder what is the point of using the different built-in exceptions if the status code can be overwritten? I see this a bug not a question.

consider this:

`throw new BadRequestException({statusCode: 502})`
