### ISSUE TITLE
[microservices] The redis host option is ignored as a url.

### ISSUE THREAD

**Issue by CatsMiaow** [nestjs/nest#6724]
- Node.js v14.15.4
- @nestjs/microservices v7.6.14

**Code**
```ts
const app = await NestFactory.createMicroservice<RedisOptions>(AppModule, {
  transport: Transport.REDIS,
  options: {
    host: '111.222.33.44', // external redis host
    password: 'something',
  },
});
```

**Error**
I entered `host` but connect to `localhost`.
```sh
[Server] Error ECONNREFUSED: redis://localhost:6379

[Server] Retry time exhausted: redis://localhost:6379

/home/tested/node_modules/@nestjs/microservices/server/server-redis.js:111
            throw new Error('Retry time exhausted');
            ^

Error: Retry time exhausted
    at ServerRedis.createRetryStrategy (/home/tested/node_modules/@nestjs/microservices/server/server-redis.js:111:19)
    at Object.retry_strategy (/home/tested/node_modules/@nestjs/microservices/server/server-redis.js:98:50)
    at RedisClient.connection_gone (/home/tested/node_modules/redis/index.js:553:41)
    at RedisClient.on_error (/home/tested/node_modules/redis/index.js:345:10)
    at Socket.<anonymous> (/home/tested/node_modules/redis/index.js:222:14)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Nest server-redis**
https://github.com/nestjs/nest/blob/e329f2565f70cc4c2fbb69da8736aa1125ee0677/packages/microservices/server/server-redis.ts#L74-L79
**Nest client-redis**
https://github.com/nestjs/nest/blob/e329f2565f70cc4c2fbb69da8736aa1125ee0677/packages/microservices/client/client-redis.ts#L84-L89

If the `url` option is not entered, it is defined as `REDIS_DEFAULT_URL`.
The url is included in the final input option.
```ts
{
  host: '111.222.33.44',
  password: 'something',
  retry_strategy: [Function: retry_strategy],
  url: 'redis://localhost:6379'
}
```

If the `host` value is present, it seems that the `url` option shouldn't be included.

**Comment by Tony133** [comment]
Hi @CatsMiaow, if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by kamilmysliwiec** [comment]
Fixed in `@nestjs/microservices@7.6.15`

**Comment by Meywether** [comment]
Hello, 
sorry to bring this issue back to live, but also in 7.6.15 my host and port setting are ignored resolving this error: 
![image](https://user-images.githubusercontent.com/39849054/113413887-f3009080-93bb-11eb-9613-50190a8280f2.png)

This is my package.json
![image](https://user-images.githubusercontent.com/39849054/113413936-1297b900-93bc-11eb-8a0e-41036f8cc458.png)


And this is the Transport.Redis Setting, which always got redirected to localhost:
![image](https://user-images.githubusercontent.com/39849054/113414055-5a1e4500-93bc-11eb-953a-d46228858697.png)

I do not have a clue why it is not accepting the settings...

May I ask you for help ?

Best regards Meywether

**Comment by kamilmysliwiec** [comment]
@meywether please, create a separate issue with a minimum reproduction repository.
