### ISSUE TITLE
Not all NestJs logs are disabled

### ISSUE THREAD

**Issue by dudewalking** [nestjs/nest#6727]
## Current behaviour
In NestJs it's possible to use custom logger:
```ts
app.useLogger(CustomLogger)
```

Also In order to disable NestJs default logs (like `[NestFactory] Starting Nest application...`) we should use ``NestApplicationOptions`` in the following way:
```ts
const app = await NestFactory.create<NestExpressApplication>(AppModule.register(), { logger: false });
```

When I have my CustomLogger set up and default NestJs logs disabled I still has some NestJs logs on application start:
```
{"level":"info","timestamp":"2021-03-22T12:55:27.329Z","message":"\"AppController {/}:\""}
{"level":"info","timestamp":"2021-03-22T12:55:27.333Z","message":"\"Mapped {/, GET} route\""}
{"level":"info","timestamp":"2021-03-22T12:55:27.333Z","message":"\"Mapped {/health, GET} route\""}
```

As I understand these logs are coming from ```RoutesResolver``` and ```RoutesExplorer``` classes (@nestjs -> core -> router) due to this:
```ts
private readonly logger = new Logger(RoutesResolver.name, true);
```
and
```ts
private readonly logger = new Logger(RouterExplorer.name, true);
```

## Expected behaviour
Do not have any NestJs default logs after disabling via using NestApplicationOptions ```{ logger: false }```

## Environment

<pre><code>
Nest version: 6.11.1

 
For Tooling issues:
- Node version: 14.15.0 
- Platform:  Mac (macOS Catalina version 10.15.7)

**Comment by jmcdo29** [comment]
Please provide a minimum reprdudction. I've been using `{ logger: false }` to disable the startup logs for a while now and I've never seen it print those startup logs

**Comment by dudewalking** [comment]
> Please provide a minimum reprdudction. I've been using `{ logger: false }` to disable the startup logs for a while now and I've never seen it print those startup logs

Sure, here you can find a repo - https://github.com/dudewalking/nestjs-logger-bug.
Just run it and you will notice some extra logs.

**Comment by jmcdo29** [comment]
![image](https://user-images.githubusercontent.com/28268680/112012560-87c6dc80-8ae6-11eb-83a4-7476fbe5fa7b.png)

This is all I see, which is expected

**Comment by dudewalking** [comment]
> ![image](https://user-images.githubusercontent.com/28268680/112012560-87c6dc80-8ae6-11eb-83a4-7476fbe5fa7b.png)
> 
> This is all I see, which is expected

I disagree as I think this is **not** expected.
If you remove my custom logger from main.ts (```app.useLogger(app.get(CustomLoggerService));```) then you won't see them at all.

And if you remove ```{ logger: false }``` then you'll see that AppController and etc. are the part of NestJs logs.

Am I wrong?

**Comment by jmcdo29** [comment]
This is the expected functionality. By setting `logger: false` you tell Nest "do not log" and as soon as you use `app.useLogger()` you are overriding that initial statement and saying "Log with this logger implementation". The big reason for this is because as of right now, there's no way to modify the initial startup logs (Module resolved, service dependencies resolved, etc) without instantiating the logger directly, or just getting rid of the logs altogether (this is changing in v8). As most people don't want to truly disable logging altogether, this is the functionality that is expected

**Comment by dudewalking** [comment]
@jmcdo29 So, that means we can't totally disable NestJs logs when using custom logger? That's a bit confusing for me as documentation says:
```
You can fully control the behavior of the logging system, including any of the following:

* disable logging entirely
```

And for example, a real use case:

I have NestJs integrated with AWS XRay and Winston logger that is set up with CloudWatch transport type.
All my logs are redirected to a particular log-group in CloudWatch. XRay and such logs implies that I have to have an opened xRay segment in order to make everything work (there is an interceptor for instance that opens a segment for all the incoming requests). But there are still some NestJs logs that I was planning easily remove by using ```{ logger: false }``` option.

Surprisingly it won't work because of "partially removed" NestJs logs as there is no opened xRay segment during initial startup but the logs are still presented. And all is left to make it work is to manually open xRay segment before bootstrap and close it after. 

1) Should the current docs be updated as it's turned out that ```{ logger: false }``` and custom logger used together do not actually disable internal logging entirely? 
2) Did I understand correctly the next version (v8) will fix this problem by totally removing NestJs logs?

Thank you in advance. That was useful to learn.

**Comment by jmcdo29** [comment]
For the most part, with custom logger implementations, after using `app.useLogger()` the logs are then controlled by the underlying logger that was set by what's passed. Winston has options of log levels, as do most other logging libraries, which is what Nest is expecting you to use for log management. The point of the `useLogger` is to allow you to use `new Logger()` anywhere (or just inject it) and still get the same logger that was passed to the `useLogger` method. 

We could probably update the docs to be clearer on that. It's become second nature to me, so I have a hard time knowing what is and isn't clear to others

**Comment by jmcdo29** [comment]
v8 will _partially_ fix this, in the sense that `NestFactory.create`'s logs can be buffered and printed out to the same logger that `app.useLogger` uses. It still will have the same functionality under the hood though, of if `useLogger` is passed it can override the original options passed to the `NestFactory.create` method.
