### ISSUE TITLE
TypeError: multer is not a function

### ISSUE THREAD

**Issue by CordlessWool** [nestjs/nest#6728]
## Current behavior
I want to use file upload and it work well, but the test for the controller is failing with TypeError: multer is not a function

## Input Code

https://gitlab.com/CordlessWool/shadow-api/-/blob/main/src/images/images.controller.spec.ts
https://gitlab.com/CordlessWool/shadow-api/-/blob/main/src/images/images.controller.ts

https://gitlab.com/CordlessWool/shadow-api/-/jobs/1117368930

## Expected behavior

Controller should be create able in the test.

## Environment
Ubuntu 20.04 and Node docker container lts
<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: 14.15.3  
- Platform: Linux 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
