### ISSUE TITLE
TypeOrmOptionsFactory and migration:run give Error during migration run: MissingDriverError: Wrong driver: "undefined" given.

### ISSUE THREAD

**Issue by PetrShchukin** [nestjs/nest#6742]
When I run `yarn typeorm -- migration:run` I'm getting `Error during migration run:
MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".` I believe that's because I'm using **TypeOrmOptionsFactory**. In app module I added TypeOrmConfigService , and everything works, migrations have been run when I start the service, but I can't use neither migrations:run nor migrations:generate.

**ormconfig.ts**
````import { Injectable } from '@nestjs/common;
import { TypeOrmOptionsFactory, TypeOrmModuleOptions } from '@nestjs/typeorm';
import * as typeormNamingStrategies from 'typeorm-naming-strategies';
import { join } from 'path';

@Injectable()
export class TypeOrmConfigService implements TypeOrmOptionsFactory {
  async createTypeOrmOptions(): Promise<TypeOrmModuleOptions> {
    const url = await this.getDBConnectionString();
    return {
      type: 'postgres',
      url,
      entities: [],
      synchronize: false,
      migrations: [join(__dirname, '/../**/database/migrations/**/*{.ts,.js}')],
      migrationsRun: true,
      logging: true,
      namingStrategy: new typeormNamingStrategies.SnakeNamingStrategy(),
    };
  }
}
````

**package.json**
`"typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --config src/database/ormconfig.ts"`

**versions:**
````"@nestjs/cli": "7.5.6",
    "@nestjs/common": "7.6.14",
    "@nestjs/config": "0.6.3",
    "@nestjs/core": "7.6.14",
    "@nestjs/jwt": "7.2.0",
    "@nestjs/passport": "7.1.5",
    "@nestjs/platform-express": "7.6.14",
    "@nestjs/terminus": "7.1.0",
    "@nestjs/typeorm": "7.1.5",
    "pg": "8.5.1",
    "pg-mem": "1.8.2",    "typeorm": "0.2.31",
    "typeorm-naming-strategies": "2.0.0",

**Comment by jmcdo29** [comment]
You'd need to return an instance of the class and cal l the correct method. Nest's DI does this automatically, which is why it works fine when you start the server. This isn't a problem with Nest, but rather your conifguration. Please use our [Discord](https://discord.gg/nestjs) or [TypeORM's slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) for support. We are using GitHub to track bug reports, feature requests, and regressions.
