### ISSUE TITLE
socket.io moved to version 4.0.0

### ISSUE THREAD

**Issue by hrahul2605** [nestjs/nest#6743]
We'll update `@nestjs/platform-socket.io` to use socket.io 3.0 in the next major release (v8) which is coming very shortly.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/5676#issuecomment-771613092_

Hey there, socket.io has moved to 4.0, on nest next major release, i.e v8, can we get support for 4.0?

**Comment by jmcdo29** [comment]
It's already planned. You can look at the 8.0.0 pr and see the planned features
