### ISSUE TITLE
Support TCP microservice over TLS

### ISSUE THREAD

**Issue by BorntraegerMarc** [nestjs/nest#6745]
## Is your feature request related to a problem? Please describe.

In our Hybrid-Cloud environment we have some microservices running in our Cloud and some microservices running On-Premise of our customers.

Communication between the microservices is all TCP based.

Now, unencrypted traffic for internal Cloud communication might be OK. But not once the traffic goes beyond the Cloud over the public internet inside to a mission critical On-Prem service.

## Describe the solution you'd like

NodeJS supports TCP sockets over TLS: https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

Something similar should be implemented for NestJS.

## Teachability, Documentation, Adoption, Migration Strategy

It's a new feature:
```ts
const options = {
  key: fs.readFileSync('server-key.pem'),
  cert: fs.readFileSync('server-cert.pem'),

  // This is necessary only if using client certificate authentication.
  requestCert: true,

  // This is necessary only if the client uses a self-signed certificate.
  ca: [ fs.readFileSync('client-cert.pem') ]
};

await NestFactory.createMicroservice<MicroserviceOptions>(
    AppModule,
    {
        transport: Transport.TCP,
        options: options
    },
);
 ```

## What is the motivation / use case for changing the behavior?

I'm aware of the old issue: https://github.com/nestjs/nest/issues/1056

I'm also aware of the possibility to create a custom NestJS transporter to achieve the same goal.

However this ticket is about native NestJS TLS support. Which seems a good idea to secure traffic.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this feature? :)

**Comment by BorntraegerMarc** [comment]
I would love to create a PR 😄 I'm missing a bit the time though.

Anyone else can take this one?

**Comment by daflodedeing** [comment]
Hey, I work with nestjs since two years and want to contribute to the project. If you @kamilmysliwiec want, I would try to create a PR for it?

**Comment by kamilmysliwiec** [comment]
@daflodedeing sounds great!

**Comment by Flusinerd** [comment]
@daflodedeing Any progress?
Otherwise I would look into this.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/7516
