### ISSUE TITLE
Unable to use CacheModule in feature modules

### ISSUE THREAD

**Issue by gperdomor** [nestjs/nest#6753]
## Current behavior
I can't use CacheModule in feature modules unless I import it in all of them (and call register)

## Input Code

```ts
// app.module.ts:
@Module({
  imports: [
    ConfigModule.forRoot({ ... }),
    CacheModule.registerAsync({ ... }),
    FeatureModule
  ],
})
export class AppModule {}

// feature.module.ts:
@Module({
  controllers: [FeatureController],
  providers: [FeatureService],
})
export class FeatureModule {}

// feature.controller.ts
@Controller('features')
export class FeatureController {
  constructor(@Inject(CACHE_MANAGER) private cacheManager: Cache, ...) {}
  ...
}

```

## Expected behavior
When import the CacheModule in the "global" app.module.ts, the CACHE_MANAGER provider should be available en all of the feature modules

## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Tony133** [comment]
You should leave a minimal reproduction of the problem.

**Comment by jmcdo29** [comment]
`AppModule` is not a `Global` module. It is a container module for the application. If you want a global cache module, you should make a wrapper module that imports and exports the `CacheModule` and is makred with `@Global()`.

**Comment by gperdomor** [comment]
@jmcdo29 sorry, when i say "global" I want to say that is the module of the entry point of the app...

**Comment by jmcdo29** [comment]
My answer still stands and this is the expected functionality. Unless you are using a `@Global()` module, modules registered in the `AppModule` (or whatever other root you are using) do not propagate down to other modules. For further discussion, please visit out [Discord](https://discord.gg/nestjs)
