### ISSUE TITLE
https://docs.nestjs.com/ outage?

### ISSUE THREAD

**Issue by AlexAsh** [nestjs/nest#6754]
## Current behavior
Cannot get to https://docs.nestjs.com/ both from my location (ru) and from us-central (gcp).

## Expected behavior
Docs should be accessible.

**Comment by micalevisk** [comment]
There's a [Netlify](https://www.netlifystatus.com) issue going on right now.

**Comment by jmcdo29** [comment]
Issue has been resolved.
