### ISSUE TITLE
startAllMicroservicesAsync generate error method not implemented.

### ISSUE THREAD

**Issue by radonirinamaminiaina** [nestjs/nest#6757]
## Current behavior

When I add `await app.startAllMicroservicesAsync();` to my bootstrap file, it generates the following error:
```
Method handler FindAll for /articles.ArticlesService/FindAll expected but not provided
```

## Input Code

```ts
async function bootstrap() {
  const app = await NestFactory.create(ArticlesModule);
  const options = grpcTransport('articles') as MicroserviceOptions;

  app.connectMicroservice<MicroserviceOptions>(options);
  await app.startAllMicroservicesAsync(); // <- generate the error

  Logger.log('Service Users started');
}
bootstrap();
```

And within my controller, I do this:

```ts
@GrpcStreamCall('ArticlesService')
  findAll(stream: any) {
    stream.on('data', (msg) => {
      console.log(msg);
    });
    stream.write({
      articles: this.articles,
    });
  }
```

And here my protofile

```protobuf
service ArticlesService {
  rpc FindAll (google.protobuf.Empty) returns (stream Articles);
}
```

## Minimum repos
[https://github.com/radonirinamaminiaina/grpc-streaming-call](https://github.com/radonirinamaminiaina/grpc-streaming-call)

## Expected behavior

I should be able to use the `@GrpcStreamCall` but I don't.
So, in my client, I have the error:
```
Error: 12 UNIMPLEMENTED: The server does not implement this method
```

If I use, `@GrpcMethod` it work like a charm. But I want to try the stream, so I was blocked there.

But if I remove the line `startAllMicroservicesAsync `, the error disappears but when I make a call with my client, the server doesn't respond anymore.

*Note*:
- Servers are in apps/articles and apps/users
- Client is in apps/gateways
- Servers don't use HTTP
- Client use HTTP server listen on 3000

## Environment

<pre><code>
Nest version: 7.5.4

 
For Tooling issues:
- Node version: v15.4.0
- Platform:  Linux

Others:
Package manager: yarn
IDE: VS code
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository

**Comment by radonirinamaminiaina** [comment]
> Please provide a minimum reproduction repository

I updated my report.
[https://github.com/radonirinamaminiaina/grpc-streaming-call](https://github.com/radonirinamaminiaina/grpc-streaming-call)

**Comment by randomprofilename** [comment]
Hi, GrpcStreamCall expects to get stream as an argument

I think you could try add 'stream' to your proto like this `rpc FindAll (stream google.protobuf.Empty) returns (stream Articles)`

Sample of using GrpcStreamCall can be found [here](https://github.com/nestjs/nest/blob/7e31161e5596fad283dcc0746c70dfee4b7ae36b/sample/04-grpc/src/hero/hero.proto#L7)

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be a bug. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
