### ISSUE TITLE
Migrating subscriptions-transport-ws to graphql-ws

### ISSUE THREAD

**Issue by Minishlink** [nestjs/nest#6762]
## Feature Request

As stated [here](https://github.com/apollographql/subscriptions-transport-ws#graphql-ws), `subscriptions-transport-ws` is now longer actively maintained and they propose to switch to `graphql-ws`.

Is it something that you consider?

Thanks

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/1348
