### ISSUE TITLE
DI causes issue due to sequence in which modules are instantiated

### ISSUE THREAD

**Issue by hardik2801** [nestjs/nest#6765]
## Current behavior
Service exported by **Module A** is being injected and used in **Module B**, everything works fine but one day when making changes in a completely unrelated module, service of Module B shows: **Nest can't resolve dependencies** even when this was working fine and nothing changed either in Module A or Module B.

This issue is only Resolved if we use ```forwardRef(() => ServiceOfModuleA)``` to inject the service required in Module B.
This should not happen as there is no circular dependency between Module A and Module B (only Module A is imported in Module B and not the other way around)

## Expected behavior
```forwardRef(() => ServiceOfModuleA)``` should not be required to inject a service into another service if there is no circular dependency between the two (also this error pops up while making changes to a completely unrelated module while no changes made to the modules in questions and before that the DI was working just fine).

Also, a circular dependency would mean we need to inject Module B in Module A using **forwardRef** too but that is not the case since Module A does not import/ inject Module B at all, then why does forwardRef solve the issue here?

## Environment

<pre><code>
Nest version: 
"@nestjs/common": "^7.6.13",
 "@nestjs/core": "^7.6.13",

 
For Tooling issues:
- Node version: v12.18.3  
- Platform:  Linux and Mac

Others:

running Nest with Docker Swarm and its amazing! Kudos to the team and community (huge thank you to @kamilmysliwiec for Nest :) )
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository. There are several specific scenarios when the circular dependency might occur in your code.

**Comment by hardik2801** [comment]
Hi @kamilmysliwiec,

i'm sorry I couldn't provide a minimum production repo, i'll do that as soon as I can, could we reopen the issue after i am able to post the minimum repro repo?
