### ISSUE TITLE
Registering entities in their own module with a named TypeORM connection causes an injection error

### ISSUE THREAD

**Issue by jrista** [nestjs/nest#6766]
## Current behavior
When creating a module that contains entities and their services, using the TypeOrmModule.forFeature() call to register those entities, using a custom connection name throws an injection error. However using the default connection works just fine.

## Input Code

```ts
// entities.module.ts
@Module({
  imports: [TypeOrmModule.forFeature([MyEntity], 'myName')],
  exports: [TypeOrmModule],
  providers: [MyEntityService]
})
export class EntitiesModule {}

// app.module.ts
@Module({
  imports: [
    ConfigModule.forRoot(),
    TypeOrmModule.forRoot({
      type: 'mongodb',
      name: 'myName',
      url: process.env.MONGODB_URI_DEV,
      useUnifiedTopology: true,
      logging: true,
      logger: 'advanced-console',
      autoLoadEntities: true,
    }),
    EntitiesModule,
  ],
})
export class AppModule {}
```

The above fails with the following on startup:

```
[Nest] 62435   - 03/26/2021, 2:56:50 AM   [ExceptionHandler] Nest can't resolve dependencies of the MyEntityService (?). Please make sure that the argument DemoAccountRepository at index [0] is available in the EntitiesModule context.

Potential solutions:
- If MyEntityRepository is a provider, is it part of the current EntitiesModule?
- If MyEntityRepository is exported from a separate @Module, is that module imported within EntitiesModule?
  @Module({
    imports: [ /* the Module containing MyEntityRepository */ ]
  })
 +0ms
Error: Nest can't resolve dependencies of the MyEntityService (?). Please make sure that the argument MyEntityRepository at index [0] is available in the EntitiesModule context.

Potential solutions:
- If MyEntityRepository is a provider, is it part of the current EntitiesModule?
- If MyEntityRepository is exported from a separate @Module, is that module imported within EntitiesModule?
  @Module({
    imports: [ /* the Module containing MyEntityRepository */ ]
  })
```

When eliminating the name for the connection (which won't be a possibility in this project once we fully get it implemented, as multiple database connections are required), it works. The relevant code when making this change:

```ts
// entities.module.ts
@Module({
  imports: [TypeOrmModule.forFeature([MyEntity])],
  exports: [TypeOrmModule],
  providers: [MyEntityService]
})
export class EntitiesModule {}

// app.module.ts
@Module({
  imports: [
    ConfigModule.forRoot(),
    TypeOrmModule.forRoot({
      type: 'mongodb',
      url: process.env.MONGODB_URI_DEV,
      useUnifiedTopology: true,
      logging: true,
      logger: 'advanced-console',
      autoLoadEntities: true,
    }),
    EntitiesModule,
  ],
})
export class AppModule {}
```

## Expected behavior
I would expect that named connections should work just as well as the default connection when using `TypeOrmModule.forFeature([...], 'name')` within a different module than the root.

## Environment

<pre><code>
Nest version: 7.5.6
 
For Tooling issues:
- Node version: 14.15.4  
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by jrista** [comment]
Update: This issue actually seems to occur regardless of whether .forFeature() is called within another module, or in the root app.module. I know that using named connections with .forFeature has worked in the past. We have other projects that have been worked on recently where using named connections work just fine. The following will also not work:

```ts
@Module({
  imports: [
    ConfigModule.forRoot(),
    CryptoModule,
    TerminusModule,
    ScheduleModule.forRoot(),
    TypeOrmModule.forRoot({
      type: 'mongodb',
      name: 'mongo',
      url: process.env.MONGODB_URI_DEV,
      useUnifiedTopology: true,
      logging: true,
      logger: 'advanced-console',
      entities: [MyEntity],
    }),
    TypeOrmModule.forFeature([MyEntity], 'mongo')
  ],
  providers: [MyEntityService],
})
export class AppModule {}
```

**Comment by kamilmysliwiec** [comment]
Btw just before you share anything, this is very likely related to the wrong usage of the `@InjectRepository()` decorator.

**Comment by jrista** [comment]
https://github.com/jrista/nestjs-typeorm-named-connection-bug

Well, here's the repro. It includes the entity service with the `@InjectRepositiry()` usage...

**Comment by kamilmysliwiec** [comment]
> At this point, you have User and Album entities registered with their own connection. With this setup, you have to tell the TypeOrmModule.forFeature() method **and the @InjectRepository() decorator which connection should be used. If you do not pass any connection name, the default connection is used.**

![image](https://user-images.githubusercontent.com/23244943/112611183-caa5ee80-8e1d-11eb-9977-de78d850dc2e.png)

`@InjectRepository(MyEntity)` -> `@InjectRepository(MyEntity, 'my_connection_name')`

**Comment by nghiatd27** [comment]
With custom repository like this:
```
@EntityRepository(FbAccountEntity)
export class FbAccountRepository extends Repository<FbAccountEntity> {}
```
How can i inject this to a service (when using multiple databases)?
I try: 
```
@Injectable()
export class FbAccountsService {
  constructor(private repository: FbAccountRepository) {}
```
But i get this error:
Nest can't resolve dependencies of the FbAccountsService (?). Please make sure that the argument FbAccountRepository at index [0] is available in the FbAccountModule context.

I can use this: 
`@InjectRepository(MyEntity, 'my_connection_name')`
It not create correct instance of FbAccountRepository

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
