### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by mushroomgenie** [nestjs/nest#6777]
## Bug Report
Hot Module Reload is not working with webpack 5.11.0

## Current behavior

The application doesn't reload on saving a file

## Expected behavior

Application should reload on saving a file
## Minimal Reproduction 
- `nest generate application`
- `yarn install`
- `yarn run start`
- Save a file 
## Environment

<pre><code>
Nest version: 7.5.6

 
For Tooling issues:
- Node version: 15.10.0  
- Platform: Mac

**Comment by Tony133** [comment]
Hi @mushroomgenie, can you leave a minimal reproduction of a clonable git repository in order to evaluate the problem?

**Comment by mushroomgenie** [comment]
@Tony133 the repository I am working on is on Gitea and it's private. Do you need any other information?

**Comment by jmcdo29** [comment]
Well, "not working" and "doesn't reload" are pretty generic and don't really tell us much. If you can provide a [minimum reproduction](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction/) we can actually see what's happening.

It may be useful to check previous issues too because of issues with webpack 5 that were discovered earlier this year

**Comment by Tony133** [comment]
@mushroomgenie, can you provide minimal reproduction like @jmcdo29 told you too? so that we see the problem well

**Comment by mushroomgenie** [comment]
@Tony133 @jmcdo29 I just added a minimal reproduction.

**Comment by jmcdo29** [comment]
@mushroomgenie did you read the link that I provided? It specifically states a git repo, the above are steps, but not something cloneable with your exact same configuration.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimum reproduction repository next time.
