### ISSUE TITLE
Add verifyClient to the WebSocketGateway decorator, when using websocket via ws

### ISSUE THREAD

**Issue by Manuelbaun** [nestjs/nest#6778]
## Is your feature request related to a problem? Please describe.
I was looking for an proper way to intercept the websocket upgrade request, to verify an user, **before** a websocket conection can be established. I use the websocket via *ws* and not *socket.io*. One suggestion was to handle that in the `handleConnection` of a gateway. But this is not a good option, since the server establishes a connection, then checks the user and if the user has no rights, it can be closed. Waste of ressources and possible security issues.

## Describe the solution you'd like
The websocket-server.js of the ws lib actually gives already an option to verify the client, before the upgrade happens. [verifyClient](https://github.com/websockets/ws/blob/114de9e33668075f0af88dc440f1ebd813161e72/lib/websocket-server.js#L224). This is also possible to use via the WebSocketGateway decorator, it is just missing. Basically, everything, that is passed as an option, is also given to the websocket-server in the `create` of the `wsAdapter`:
[here](https://github.com/nestjs/nest/blob/7476fc5402897ed10ca485b24eb99e4e6afb54a8/packages/platform-ws/adapters/ws-adapter.ts#L46) and
[here](https://github.com/nestjs/nest/blob/7476fc5402897ed10ca485b24eb99e4e6afb54a8/packages/platform-ws/adapters/ws-adapter.ts#L55).

## Teachability, Documentation, Adoption, Migration Strategy
Technically, you just have to add the `verifyClient`-Method to the websocket [GatewayMetadata](https://github.com/nestjs/nest/blob/master/packages/websockets/interfaces/gateway-metadata.interface.ts) and that is all. No breaking changes etc.

## What is the motivation / use case for changing the behavior?
How to use the decorator would look like this:

```ts
@WebSocketGateway({
    cookie: 'sid',
    path: '/ws',
    allowUpgrades: false,
    transports: ['websocket'],
    verifyClient: (info, cb) => {
        console.log(info.req);
        cb(true, 200, 'you are verified', {
            cookie: 'sid: hello world',
        });
    },
})
```

**Comment by kamilmysliwiec** [comment]
`@WebSocketGateway` is a generic decorator that let you pass any arbitrary options object to configure the underlying server https://github.com/nestjs/nest/blob/master/packages/websockets/decorators/socket-gateway.decorator.ts Your object doesn't have to match the `GatewayMetadata` interface so you should be able to safely pass the `verifyClient` in there without modifying the actual interface.

**Comment by rohitkhatri** [comment]
@Manuelbaun How to attach some information for each client after successful connection and access it in the handleConnection method?
