### ISSUE TITLE
How to save Header from jwt.strategy?

### ISSUE THREAD

**Issue by blogaster** [nestjs/nest#6780]
Hello! I use JwtStrategy for check JWT token. And if access token expired but refresh token not expired I update access token. 
How I can pass new token to Controller or set header response from JwtStrategy ?

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for Support. We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by blogaster** [comment]
Thank you. I'm sorry
