### ISSUE TITLE
DTO class-validator interceptor bypassed

### ISSUE THREAD

**Issue by lapwat** [nestjs/nest#6783]
## Current behavior
class-validator decorators are not taken into account if you import a DTO from a module.

`import { SimpleDto as SimpleDtoFileImport } from './simple.dto'` ==> Works
`import { SimpleDto as SimpleDtoModuleImport } from '@controller'` ==> Class-validator decorators bypassed.

## Input Code
I have created a repo to reproduce.

REPO

https://github.com/lapwat/bypassdtobug

```sh
❯ git clone https://github.com/lapwat/bypassdtobug.git
```

COMMIT INVOLVED

https://github.com/lapwat/bypassdtobug/commit/54c62aa6f159758e9944f06505e343c017c5c5c7

Notes:
- Install class-validator / class-transformer
- Enable global validation in `main.js`
- Create own module path in `tsconfig`

TEST

```
❯ cd bypassdtobug
❯ yarn
❯ yarn start

❯ curl localhost:3000/controller/dto_ok
{"statusCode":400,"message":["notEmpty should not be empty"],"error":"Bad Request"}%

❯ curl localhost:3000/controller/dto_bypass
Hello World!%
```

## Expected behavior
Obtain error 400 for both tests

## Possible Solution
No idea.

## Environment

<pre><code>
Nest version: 7.6.0

 
For Tooling issues:
- Node version: 15.12.0  
- Platform: Linux  

Others:

</code></pre>

**Comment by lapwat** [comment]
It is interesting to notice that the bypass is happening only if you are importing the dto **from the SAME folder**.

Branch adding second controller:

```sh
❯ git checkout not_happening_from_another_folder
```

TEST

```sh
❯ curl localhost:3000/controller2/dto_ok
{"statusCode":400,"message":["notEmpty should not be empty"],"error":"Bad Request"}%

❯ curl localhost:3000/controller2/dto_bypass
{"statusCode":400,"message":["notEmpty should not be empty"],"error":"Bad Request"}%
```

Both tests are working, they return Error 400.

**Comment by kamilmysliwiec** [comment]
The issue here is very likely a circular dependency that your `@controller` import leads to. When importing `@controller` from the  `controller.controller`, you in fact import the entire `index.ts` file, which in turn exports the `controller.controller`. This introduces a circular dependency, and circular deps frequently cause TS/JS metadata-related issues. This isn't really the framework's fault in this case.

**Comment by lapwat** [comment]
Thanks, I guess the solution would be to directly import the file you need when you are working from the same folder.
