### ISSUE TITLE
The @nestjs/microservices KafkaClient module clobbers the KafkaJS `logCreator` option.

### ISSUE THREAD

**Issue by benderTheCrime** [nestjs/nest#6797]
## Bug Report

The logger definition in the `KafkaClient` module, `client-kafka.js`, clobbers the KafkaJS `logCreator` option:
https://github.com/nestjs/nest/blob/85e50eb8e72b0e01fe3d847c5b780f5b5d880401/packages/microservices/client/client-kafka.ts#L149

if a `logCreator` method is defined on `this.options.client`, it will always be assigned over by the defined `KafkaLogger`.

## Current behavior

I noticed my logs using `nestjs-pino` were "double wrapped." This is because the `PinoLogger` adds a log level and a timestamp to a log line, as does the built in `KafkaLogger`:
https://github.com/nestjs/nest/blob/85e50eb8e72b0e01fe3d847c5b780f5b5d880401/packages/microservices/helpers/kafka-logger.ts#L31

The resulting log lines look something like this:

```sh
[1617071745700] DEBUG (46596 on localhost): DEBUG [ConsumerGroup] Fetching from 1 partitions for 1 out of 1 topics {"timestamp":"2021-03-30T02:35:45.700Z","logger":"kafkajs","topics":["hero.kill.dragon"],"activeTopicPartitions":[{"topic":"hero.kill.dragon","partitions":[0]}],"pausedTopicPartitions":[]} 
```

## Input Code
This example is derived from an app using the example code here: https://docs.nestjs.com/microservices/kafka.

With two caveats: the app has a custom logger defined, https://www.npmjs.com/package/nestjs-pino, at the top-level of the app and as a module import.

```ts
 const logger = new PinoLogger();
 const app = await NestFactory.create(AppModule, { logger });
```

```ts
import { LoggerModule } from "nestjs-pino";
 
@Module({
  imports: [LoggerModule.forRoot()],
})
class MyModule {}
```

The client configuration in my app is the same as the example, excepting that has a `logLevel` and a `logCreator` option defined, as specified by the `KafkaOptions` and `KafkaConfig` typings:
https://github.com/nestjs/nest/blob/29192b38e403ecd9be6ef106f27957138882c1d9/packages/microservices/external/kafka.interface.ts#L27

```
const logger = new PinoLogger()

@Module({
  imports: [
    ClientsModule.register([
      {
        name: 'HERO_SERVICE',
        transport: Transport.KAFKA,
        options: {
          client: {
            clientId: 'hero',
            brokers: ['localhost:9092'],
            logLevel: 1,
            logCreator: (level) => ({ namespace, level, log }) => logger.error(log),
          },
          consumer: {
            groupId: 'hero-consumer'
          }
        }
      },
    ]),
  ]
})
```

## Expected behavior

The `logCreator` property should make it possible to pass a log message into the underlying Logger service, either in-built or custom. This option should be used to define a custom log line to be generated from the KafkaJS client. 

Given the above code, I should be able to produce a log message that looks like this:

```sh
[1617071745700] DEBUG (46596 on localhost): [ConsumerGroup] Fetching from 1 partitions for 1 out of 1 topics {"timestamp":"2021-03-30T02:35:45.700Z","logger":"kafkajs","topics":["hero.kill.dragon"],"activeTopicPartitions":[{"topic":"hero.kill.dragon","partitions":[0]}],"pausedTopicPartitions":[]} 
```

or, using a `console.log` even:

```sh
Fetching from 1 partitions for 1 out of 1 topics {"timestamp":"2021-03-30T02:35:45.700Z","logger":"kafkajs","topics":["hero.kill.dragon"],"activeTopicPartitions":[{"topic":"hero.kill.dragon","partitions":[0]}],"pausedTopicPartitions":[]} 
```

## Possible Solution

Check for a provided `options.client.logCreator` on the user-provided client options before falling back to the `KafkaLogger`:
KafkaLogger:
https://github.com/nestjs/nest/blob/85e50eb8e72b0e01fe3d847c5b780f5b5d880401/packages/microservices/helpers/kafka-logger.ts#L31

Something like this:

```ts
  public createClient<T = any>(): T {
    return new kafkaPackage.Kafka({
        logCreator: KafkaLogger.bind(null, this.logger),
        ...this.options.client || {},
        clientId: this.clientId,
        brokers: this.brokers,
    });
  }
```

This sacrifices the Logger service awareness of the built-in Nest.js service, and I think that's ok - wherever the `KafkaClient` is created, if the `logCreator` option is preferred, a logger will need to be in scope.

Either this, or the `logCreator` option should be stricken from the exposed `KafkaConfig` interface:
https://github.com/nestjs/nest/blob/29192b38e403ecd9be6ef106f27957138882c1d9/packages/microservices/external/kafka.interface.ts#L27

## Environment

<pre><code>
Nest version: "@nestjs/microservices": "^7.6.14"
 
For Tooling issues:
- Node version: 13.8.0
- Platform: Mac/Linux
</code></pre>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Thanks, let's track this here https://github.com/nestjs/nest/pull/6806!
