### ISSUE TITLE
[Suggestion] Consider using lerna

### ISSUE THREAD

**Issue by alexjoverm** [nestjs/nest#68]
[Lerna](https://github.com/lerna/lerna) is meant to make easy the maintenance and publishing of monorepo multipackage projects (like this one).

Not sure how you @kamilmysliwiec currently do releases, but probably this can help a lot.

It could go even smoother using [Lerna Semantic Release](https://github.com/atlassian/lerna-semantic-release). I haven't use this Lerna fork, but I do use Semantic release alone on [TypeScript library starter](https://github.com/alexjoverm/typescript-library-starter) and [ShortcutJS](https://github.com/coosto/ShortcutJS) and releases are fully automated.

**Comment by kamilmysliwiec** [comment]
Hi @alexjoverm,
Yes, there is a big confusion with packages publishing :smiley: I have to consider it

**Comment by d3viant0ne** [comment]
There is really no need for a framework to manage the publishing of your framework. Lerna is a sledge hammer & far more cumbersome than anyone needs.

It takes 15 l.o.c to publish Angular, why would you need the extra complexity here?

**Comment by alexjoverm** [comment]
Well the idea is to automate the releases as much as possible. In my libraries I'm happily using semantic release. Since this is a multipackage library, I know Lerna is meant to be used for that.

@d3viantOne can you point us to those 15LOC? Have any other suggestions?

**Comment by d3viant0ne** [comment]
Semantic release != Lerna

Angular executes a simple bash script which in turn iterates over all of it's child packages & publishes them.

Point being, there is no need for an abstraction layer when a simple script can accomplish the same thing without being dependent on yet another library.

**Comment by alexjoverm** [comment]
Fair enough. Anyway, do you know where that angular script lives?

**Comment by wbhob** [comment]
I made a PR to add lerna. @d3viant0ne the reason to have a lerna as a package is so we don’t need to write scripts. It makes the repo smaller as a whole and reduces conflicts. That is, why write and maintain scripts when Lerna Core team is already doing it?

**Comment by kamilmysliwiec** [comment]
I agree with @d3viant0ne here, can't find any reason why we need another tool.
