### ISSUE TITLE
Move to racially neutral code terms

### ISSUE THREAD

**Issue by kevjames3** [nestjs/nest#6808]
## Feature Request

Per the code of conduct...

> In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

With some in the industry moving toward racially neutral terms, I am proposing that we should do the same in the NestJS side of things.

Sources
- https://www.digitalinformationworld.com/2020/07/apple-starts-moving-towards-racially-neutral-coding-terms.html
- https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md
- https://www.marketplace.org/2020/06/17/tech-companies-update-language-to-avoid-offensive-terms/

## Describe the solution you'd like
I am not believing that this will be done immediately and I assume that what will start here is a discussion, but I am making changes on some personal repositories so I believed extending the request out to NestJS as a proposal is not a bad move.  

Initial proposals...
- Move default branch name to `main` from `master`
- Terms such as “blacklist” and “whitelist” reinforce the notion that black==bad and white==good. These terms can usually be replaced by “blocklist” and “allowlist” without changing their meanings, but particular instances may need other replacements.
  - Only code I found mentioning whitelist https://github.com/nestjs/nest/blob/8bc4e92d21c67406a6c652e1f4db183ed3d6a718/packages/common/interfaces/external/validator-options.interface.ts#L26-L31.  Simply mark `whitelist` as deprecated and move to `allowlist`

## What is the motivation / use case for changing the behavior?
See the above at the top of the issue

**Comment by kamilmysliwiec** [comment]
> Only code I found mentioning whitelist

As you can see, this interface is located inside the `external` folder meaning, this is an external interface we had to bring to the repository (to provide autocompletion and at the same time, avoid compilation errors in case one doesn't have the `class-validator` package installed locally) BUT it's not really under NestJS team control. This interface must mimic the corresponding `ValidatorOptions` from the `class-validator` https://github.com/typestack/class-validator/blob/develop/src/validation/ValidatorOptions.ts Once they update the interface, we'll be able to do it here as well so I'd suggest creating an issue there.

> Move default branch name to main from master

I'm all in when it comes to using `main` as the default branch for any future repository we create under the framework organization, but renaming the current default branch in all existing repos (including this one) is just way too complicated & costful operation (see more details in React/Angular/Node.js repositories on the same issue). We'll definitely think about this in the future, but there's no plan to do it atm.
