### ISSUE TITLE
onModuleDestroy have not been called

### ISSUE THREAD

**Issue by huangyanxiong01** [nestjs/nest#6824]
## Bug Report
database connection is not closed after Execute e2e test.Try count database connction wtih `ps aux | grep mydb | grep -v grep | wc -l`, already more than 90 connections when execute many time. If database connection more than postgres max connection, I got this error `FATAL: sorry, too many clients already"`. I follow this issue [issue](https://github.com/nestjs/nest/issues/2893) add ` app.close(); `to `afterAll`. But not solved my issue
## Current behavior

onModuleDestroy have not been called
## Input Code

`auth.e2e-spec.ts`
```ts
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as request from 'supertest';
import { AppModule } from '../src/app.module';
const apiEndPoint = '/api/auth/login';
describe('AuthController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  afterAll(() => {
    app.close();
  });

  it(`/api/auth/login (POST)`, () => {
    return request(app.getHttpServer())
      .post(apiEndPoint)
      .send({ username: 'john', password: 'changeme' })
      .then((res) => {
        expect(res.body).toHaveProperty('token');
      });
  });

  it('/api/auth/login (POST) with invalid user', () => {
    return request(app.getHttpServer())
      .post(apiEndPoint)
      .send({ username: 'xx', password: 'xxx' })
      .expect(401);
  });
});
```
`prisma.service.ts`
```ts
import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleDestroy, OnModuleInit {
  async onModuleDestroy() {
    await this.$disconnect();
  }
  async onModuleInit() {
    await this.$connect();
  }
}
```
Full code at [here](https://github.com/huangyanxiong01/nest-starter)
## Expected behavior

close database connection after test complete
## Environment

<pre><code>
Nest version: 7.6.13

 
For Tooling issues:
- Node version: v14.15.5  
- Platform: Ubuntu 20.04.2 LTS  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
