### ISSUE TITLE
Populate() not working on collection using UUID as _id

### ISSUE THREAD

**Issue by jblyberg** [nestjs/nest#6833]
## Current behavior
`Collection.populate()` does not work for an array of UUIDs in a collection that uses UUID as its identifier. Using `.populate()` on such a collection fails silently and no further operations are performed.

## Input Code
Extending the example given in the docs, using `String` instead of `Types.ObjectId` because mongoose ids are not UUIDs:

in `cats.schema`:
```ts
  @Prop({ type: [{ type: String, ref: Owner.name }] })
  owner: Owner[] | string[];
```

in `owner.schema`:
```ts
  @Prop({ type: String, default: uuid })
  _id: string;
```

## Expected behavior

If I run:

```ts
const catWithOwners = await catModel.findById(id).populate('owner');
```

I should get a populated array, instead the program halts without error.

## Possible Solution
allow `@Prop` types other than `Types.ObjectId` to be used.

## Environment

```
Nest version: 7.6.15
- "@nestjs/mongoose": "^7.2.4"
- "mongoose": "^5.12.3",
- mongoDB: 4.4.4
 
For Tooling issues:
- Node version: 15.9.0
- Platform:  Mac
```

**Comment by jmcdo29** [comment]
Does mongoose on its own allow this kind of functionality? Can you provide a minimum reproduction?

**Comment by jblyberg** [comment]
Turns out I was not registering the mongoose model properly. Found my solution here: https://github.com/nestjs/nest/issues/364

Closing.
