### ISSUE TITLE
Hybrid application cannot share the same TCP PORT

### ISSUE THREAD

**Issue by 2627500295** [nestjs/nest#6851]
## Current behavior

It can run normally on Mac OS X, but on Linux system, it prompts that the port is occupied.

Although, this problem can be solved by assigning different ports.

However, we stipulate that only this port can be used.

I want to know how can I solve this problem and be able to run it normally in docker.

I tried to solve this problem by giving different hosts for microservices and Http services.

example:

```
microservice: 0.0.0.0
http: 127.0.0.1
```

But none of them worked.

## Input Code

```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.connectMicroservice<MicroserviceOptions>({
    transport: Transport.TCP,
    options: { port: 3000 },
  });

  await app.startAllMicroservicesAsync();
  await app.listen(3000);
}

bootstrap();
```

## Expected behavior

<pre><code>
registered with eureka:  HUOZI-PLATFORM-OPERATING-RECORD/127.0.0.1:3000
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1310:16)
    at listenInCluster (node:net:1358:12)
    at Server.listen (node:net:1445:7)
    at ExpressAdapter.listen (/home/microld/server/huozi-platform-operating-record/node_modules/@nestjs/platform-express/adapters/express-adapter.js:45:32)
    at NestApplication.listen (/home/microld/server/huozi-platform-operating-record/node_modules/@nestjs/core/nest-application.js:149:26)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async bootstrap (/home/microld/server/huozi-platform-operating-record/dist/main.js:20:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1337:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
</code></pre>

## Environment

<pre><code>
[System Information]
OS Version     : Linux 5.10
NodeJS Version : v15.12.0
YARN Version    : 1.22.10 

[Nest CLI]
Nest CLI Version : 7.6.0 

[Nest Platform Information]
platform-express version : 7.6.15
microservices version    : 7.6.15
mapped-types version     : 0.4.1
typeorm version          : 7.1.5
common version           : 7.6.15
config version           : 0.6.3
core version             : 7.6.15
</code></pre>

**Comment by Tony133** [comment]
Hi @2627500295,

If you think this is an issue with Nest, it's a good idea to provide minimal reproduction when submitting a bug report so the nest core team can evaluate your issue.
Although seeing it would not seem a problem with the Nest framework. You are using the same port `3000` as some other Nodejs application. Check which TCP ports you have in use and try to terminate the process on the port, or put a different port number than `3000` type `4000`, etc.

However for support and support requests use the [Discord](https://discord.com/invite/G7Qnnhy) channel.

Nest's core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
