### ISSUE TITLE
Multiple Guard which is any more than 1 auth methods, Is it support?

### ISSUE THREAD

**Issue by PandhuWibowo** [nestjs/nest#6864]
## Feature Request

Hi guys, In this case, I will make auth for call server to server to read or write data (maybe use Secret Key or stuff like that, similar method), in other hand, the endpoint also will be used to client app (mobile app), and I will cover it with otp. Is it possible if I put on both of them to each functions in the controller?
How can they know where is calling from client app and where is calling from another server?

For instance, I have endpoint `/articles`. The endpoint able to use for read or write from another server access. I will cover it by make the secret key or stuff like that, and this endpoint also be used in mobile app which is will cover it by otp. Is it posibble ?
If support, any example to doing this my issue? Any suggestions to solve this?

Thanks in advance.

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for support. We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
