### ISSUE TITLE
Swagger raw api endpoint

### ISSUE THREAD

**Issue by lzkill** [nestjs/nest#6865]
Alongside the path of the Swagger UI it would be useful to have another endpoint exposing the [raw api](https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml) (json or yaml), so the client gereration by another team would be as easy as running [swagger-codegen](https://swagger.io/tools/swagger-codegen/).

**Comment by jmcdo29** [comment]
From the docs

> Hint
To generate and download a Swagger JSON file, navigate to http://localhost:3000/api-json (swagger-ui-express) or http://localhost:3000/api/json (fastify-swagger) in your browser (assuming that your Swagger documentation is available under http://localhost:3000/api). 

[Link](https://docs.nestjs.com/openapi/introduction)

**Comment by lzkill** [comment]
That's sweet! Thank you so much!
