### ISSUE TITLE
Disabling caching on a specific route has no effect

### ISSUE THREAD

**Issue by nils-jansen** [nestjs/nest#6870]
## Current behavior

I have set up my app to automatically cache responses [as described in the Docs](https://docs.nestjs.com/techniques/caching#auto-caching-responses). However, a specific route should not be cached. I tried to achieve this with the decorator ```@CacheTTL(0)```, but responses are still being cached.

## Input Code

In **app.module.ts**:
```ts
@Module({
  imports: [
    // ...
    CacheModule.register({
      ttl: +process.env.CACHE_TTL || 10, // time to live in seconds
      max: +process.env.CACHE_MAX_ITEMS || 100, // maximum number of items in cache
    }),
    // ...
  ],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_INTERCEPTOR,
      useClass: CacheInterceptor,
    },
  ],
})
export class AppModule {}
```

In **event.controller.ts**:
```ts
   /**
   * Returns all group events in a given timespan
   */
  @Get('range')
  @CacheTTL(0) // this isn't working!
  findByRangeAndGroup(@Body() findByTimeRangeDto: FindByTimeRangeDto) {
    return this.eventService.findByTimeRange(findByTimeRangeDto);
  }
```

## Expected behavior

I was expecting that ```@CacheTTL(0)``` would effectively disable caching for this specific route.

## Possible Solution

I don't know if this is a bug or if I am just missing something. I did not find a decorator etc. like ```@DisableCache()```.

## Environment

<pre><code>
Nest version: 7.5.4

 
For Tooling issues:
- Node version: 14.15.1  
- Platform: Windows 

Others:

</code></pre>

**Comment by jmcdo29** [comment]
[According to the code](https://github.com/nestjs/nest/blob/master/packages/common/cache/interceptors/cache.interceptor.ts#L40) a `0` should be a fine value. Please provide a [minimum reproduction](http://minimum-reproduciton.wtf)

**Comment by nils-jansen** [comment]
Please find the minimum reproduction [here](https://github.com/Publical/caching-bug-min-reprod).

**Comment by jmcdo29** [comment]
Looks like this is actually a problem with `cache-manager`'s underlying cache system [node-lru-cache](https://github.com/isaacs/node-lru-cache). [You can see here](https://github.com/isaacs/node-lru-cache/blob/master/index.js#L154) that there's a `maxAge || this[MAX_AGE]` call for the TTL, and as `0` is falsey it reverts to the original option

**Comment by jmcdo29** [comment]
As a workaround, you can do something like `@CacheTTL(0.000001)` and it essentially invalidates the cache immediately, but with `cache-manager`'s default cache, `0` is not a valid invalidator

**Comment by nils-jansen** [comment]
Ok, thanks a lot for the explanation - this solved my problem 😄 . Could you maybe include this in the related section of the Docs? It will probably help others who have the same problem.

**Comment by jmcdo29** [comment]
[I'll at least add the reference here](https://github.com/BryanDonovan/node-cache-manager/issues/43) it definitely is an issue with `lru-cache`
