### ISSUE TITLE
Add @nestjs/create

### ISSUE THREAD

**Issue by galkin** [nestjs/nest#6873]
## Is your feature request related to a problem? Please describe.
Bootstrap new project.

## Current solution
```
$ npm i -g @nestjs/cli
$ nest new project-name
```

## Proposed solution
```
npm init @nestjs
```

## Teachability, Documentation, Adoption, Migration Strategy
Change https://docs.nestjs.com/#installation

## What is the motivation / use case for changing the behavior?
Avoid global package installation by using [npm init](https://docs.npmjs.com/cli/v6/commands/npm-init)

**Comment by jmcdo29** [comment]
What's wrong with using `npx @nestjs/cli new <projectName>`?
