### ISSUE TITLE
Possible To Accept Case Insensitive Request Bodies?

### ISSUE THREAD

**Issue by JimLynchCodes** [nestjs/nest#6878]
Hi, I'm just wondering if it is possible to create an @expressJS or @Nestsjs #nodejs REST API that accepts case insensitive JSON fields? :thinking:

Is there something I can use from Nest or ClassValidator to just to this across the board or for certain routes?

Possibly we could add some kind of case insensitivizing decorator in the controller file?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
