### ISSUE TITLE
Websockets won't work at all

### ISSUE THREAD

**Issue by leandrogenas** [nestjs/nest#6880]
## Current behavior
I am not quite convinced that this is in fact a bug, but here it is: From a couple of weeks to this date, I cannot create any application that uses websockets, as I cannot connect no matter the port I use it in, but the Gateway seems to be initialized, as I try to make a Post request to the ws endpoint, it returns me 404 instead of connection refused.

The connection also does not seem to be leaving any tracks for me to pick up at wireshark, so my attempts at debugging this are futile.

## Input Code
I tried running this basic example: https://github.com/TannerGabriel/Blog/tree/master/NestVueChat

All seems to start up just fine, but here's what's happening when I try to connect to it
![image](https://user-images.githubusercontent.com/43735409/114452783-3a9ecd80-9baf-11eb-9f0a-c61978340233.png)

As a side note, I have a hint that this plugin is able to reach the server because when I'm running the websocket server in nest, it takes longer to give me this error

## Expected behavior
I should connect just fine and answer to the commands.

## Possible Solution
?

## Environment

<pre><code>
Nest version: (any)
 
For Tooling issues:
- Node version: v15.13.0
</code></pre>

Platform:  
![image](https://user-images.githubusercontent.com/43735409/114453114-979a8380-9baf-11eb-8f3c-48a94a3da7ba.png)

**Comment by jmcdo29** [comment]
If I had to guess, it's due to using `socket.io-client` v1 on the client side and `socket.io` v2 on server side. I'm not convinced this is an issue with Nest though

**Comment by leandrogenas** [comment]
how can I test this? can I force Nestjs to use the socket.io-client v1 for me to test? maybe my web socket tester uses this one by default

**Comment by jmcdo29** [comment]
I'm just looking at the `static/index.html` which has a reference to `socket.io-client` v1. I'm not sure of your Weasel tool. It may be using `socket.io-client` v4, which also has it's own issues when connecting to a v2 server

**Comment by jmcdo29** [comment]
If that's the case you can try using the alpha of nest v8 and see if that works

**Comment by leandrogenas** [comment]
just tried that here, no luck :/ this doesn't seem to be the issue though..

![image](https://user-images.githubusercontent.com/43735409/114456900-c9ade480-9bb3-11eb-9a72-845f9596a307.png)

**Comment by jmcdo29** [comment]
My guess then is that there's a disconnect between using `socket.io` and the `ws` protocol that weasel uses. This isn't an issue with Nest, but rather a way that socket.io's engine works. Please use our [Discord](https://discord.gg/nestjs) for further support as this doesn't appear to be a bug.
