### ISSUE TITLE
Outdated GRPC package

### ISSUE THREAD

**Issue by axotion** [nestjs/nest#6886]
GRPC package used in nest is now marked as depreacted

https://www.npmjs.com/package/grpc

"This library is now only receiving bug fixes and runtime compatibility updates. In April 2021 it will be deprecated and will no longer receive any updates. We recommend using @grpc/grpc-js instead."

Will NestJS change GRPC package to https://www.npmjs.com/package/@grpc/grpc-js in near future?

**Comment by jmcdo29** [comment]
[This is already planned](https://github.com/nestjs/nest/pull/6349)
