### ISSUE TITLE
Being able to customize printed log messages

### ISSUE THREAD

**Issue by RezaRahmati** [nestjs/nest#6892]
## Is your feature request related to a problem? Please describe.
In my app which is deploying to Google cloud run, I extended Logger class as below, mostly using the base logger, but logs in google cloud doesn't look like pretty (below picture)

![image](https://user-images.githubusercontent.com/10086092/114748453-f41cb080-9d1f-11eb-992e-8933151fc483.png)

```
import { Injectable, Logger, Scope } from '@nestjs/common';

@Injectable({ scope: Scope.TRANSIENT })
export class LoggerService extends Logger {}
```

I checked the repo code, and seems Logger is using some private static method called [printMessage](https://github.com/nestjs/nest/blob/58d850da0f72426aab50317749bc404a0d1b7887/packages/common/services/logger.service.ts#L145)

## Describe the solution you'd like
As a developer I want to be able to override how logs are printed when I am extending Logger class

**Comment by jmcdo29** [comment]
So long as you make your own methods that match the `LoggerService` interface, you can customize the logs however you want. [This is documented in the docs](https://docs.nestjs.com/techniques/logger#custom-implementation) and [there are](https://github.com/jmcdo29/ogma) [several packages](https://github.com/iamolegga/nestjs-pino) [that handle this](https://github.com/gremo/nest-winston) [for you](https://github.com/eropple/nestjs-bunyan-logger). 

For more support on writing a custom logger, please visit our [Discord](https://discord.gg/nestjs). This feature is already implemented

**Comment by RezaRahmati** [comment]
@jmcdo29 Yes, I know how to customize it, then I have to reinvent the wheel, so I would like to keep existing functionality of methods (log,warn.info, error) and juts override how the messages are printed,

For example if `printMessage` was virtual, so I could have just override that in my logger and change how the messages should have been displayed (even using the colorize method that exists to colorize it)

**Comment by jmcdo29** [comment]
There's a large overhaul of the logger in v8 coming as well, so that may be something to look forward to. The reason for the static methods is due to using `Logger.log` and similar methods in some of the application startup, which we are trying to minimize to make things better. 

If you're looking to just get rid of the colors, you can set the env variable `NO_COLOR` to `true` and it should stop the colors from being used
