### ISSUE TITLE
[Feature] fastify-multipart interceptors

### ISSUE THREAD

**Issue by maronfranc** [nestjs/nest#6894]
## Feature Request
Platform Fastify `FileInterceptor`, `FilesInterceptor`, `AnyFilesInterceptor` and `FileFieldsInterceptor`

## Is your feature request related to a problem? Please describe.
There is a [fastify-multer pull request](https://github.com/nestjs/nest/pull/4921#issuecomment-689814762) and @emagnier asked to consider adding a `fastify-multipart` version.

## Describe the solution you'd like
I implemented a `fastify-multipart` wrapper that works in a similar way as `platform-express` interceptors.
I'd like to create a PR, so we can discuss if it is a good solution.

## Teachability, Documentation, Adoption, Migration Strategy
[The documentation](https://docs.nestjs.com/techniques/file-upload) will be almost same as it is, the main difference is that the uploaded file interface is a modified version of `fastify-multipart` `MultipartFile` interface.

## What is the motivation / use case for changing the behavior?
File upload for `platform-fastify`.

**Comment by kamilmysliwiec** [comment]
Feel free to create a PR for this issue if you have a working version ready 🙌  Just a heads-up however, we cannot promise whether we'll merge it or not just yet (the decision if we want to provide `fastify-multipart` integration right from the `platform-fastify` package hasn't been made).

**Comment by chanphiromsok** [comment]
feel free to add my package to "platform-fastify" 
link https://www.npmjs.com/package/fastify-file-interceptor
