### ISSUE TITLE
Build Error TS2694

### ISSUE THREAD

**Issue by titobundy** [nestjs/nest#6904]
## Bug Report

After adding dependency _@types\multer_  v1.4.5, I can't build project, an error ocurrs.

## Current behavior

```
$ nest build

node_modules/@types/multer/node_modules/@types/express/index.d.ts:58:29 - error TS2694: Namespace 'serveStatic' has no exported member 'RequestHandlerConstructor'.

var static: serveStatic.RequestHandlerConstructor<Response>;
```
## Input Code

```ts
    @Post('/upload')
    @HttpCode(HttpStatus.CREATED)
    @UseInterceptors(FileInterceptor('file', {
        fileFilter: FileHelper.isHtmlFormat
    }))
    async upload(
        @UploadedFile() file: Express.Multer.File) {       

        if (file?.size) {
            return await this.emailTemplateService.uploadTemplate(file);
        }
    }
```

## Expected behavior
Build successfully

## Environment

<pre><code>
Nest version: 7.5.4

 
For Tooling issues:
- Node version: 12.20.0
- Platform:  Linux

Others:

{
  "name": "ms-proj",
  "version": "1.0.3",
  "description": "",
  "author": "hdiaz",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@hapi/joi": "^17.1.1",
    "@nestjs/common": "^7.0.0",
    "@nestjs/config": "^0.5.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/mongoose": "^7.0.2",
    "@nestjs/platform-express": "^7.0.0",
    "@nestjs/platform-socket.io": "^7.6.13",
    "@nestjs/swagger": "^4.6.1",
    "@nestjs/terminus": "^7.0.1",
    "@nestjs/websockets": "^7.6.13",
    "@ssut/nestjs-sqs": "^1.0.0",
    "@types/mongoose": "^5.7.36",
    "@types/socket.io": "^2.1.13",
    "aws-sdk": "^2.806.0",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "exceljs": "^4.1.1",
    "html-pdf": "^2.2.0",
    "memory-streams": "^0.1.3",
    "mongoose": "^5.10.3",
    "mongoose-aggregate-paginate-v2": "^1.0.42",
    "mongoose-paginate-v2": "^1.3.9",
    "muhammara": "^1.5.1",
    "nest-winston": "^1.3.6",
    "pify": "^5.0.0",
    "pug": "^3.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.5.4",
    "swagger-ui-express": "^4.1.4",
    "uuid": "^8.3.2",
    "winston": "^3.3.3",
    "xlsx-populate": "^1.21.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.0.0",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0",
    "@types/exceljs": "^1.3.0",
    "@types/express": "^4.17.3",
    "@types/hapi__joi": "^17.1.4",
    "@types/html-pdf": "^2.2.0",
    "@types/jest": "26.0.10",
    "@types/multer": "^1.4.5",
    "@types/node": "^13.9.1",
    "@types/supertest": "^2.0.8",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "3.9.1",
    "@typescript-eslint/parser": "3.9.1",
    "eslint": "7.7.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "jest": "26.4.2",
    "mongodb-memory-server": "^6.9.0",
    "prettier": "^1.19.1",
    "supertest": "^4.0.2",
    "ts-jest": "26.2.0",
    "ts-loader": "^6.2.1",
    "ts-node": "9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^3.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node",
    "setupFiles": [
      "../test/setEnvVars.ts"
    ]
  }
}

</code></pre>

**Comment by jmcdo29** [comment]
[This is an issue with express's types](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49595)

Closing as it's not related to Nest.

**Comment by titobundy** [comment]
Finally I solved the problem doing an upgrade my project's dependencies:

**Nest update from 7.0.0 to 7.6.15**
`nest update -f -t latest`

**Yarn upgrade**
`yarn upgrade`

**I had to keep the old versions of mongoose**

_Dont works with @nestjs/mongoose@7.2.x and mongoose@5.11.x_

```
yarn upgrade @nestjs/mongoose@7.1.2
yarn upgrade mongoose@^5.10.19
```

**Add dev dependency @types\multer**

`yarn add -D @types/multer`

And now _nest build_ works fine...
