### ISSUE TITLE
Incorrect application with adapter behaviour

### ISSUE THREAD

**Issue by tony-bondarenko** [nestjs/nest#6907]
## Input Code

```ts
const app = await NestFactory.create<NestFastifyApplication>(
        AppModule,
        new FastifyAdapter()
    );
const response = await app.inject({
            method: 'GET',
            url: '/',
        });
```

## Current behavior
response is an instance of NestApplication

## Expected behavior
response is an instance of LightMyRequestResponse according to NestFastifyApplication interface

## Possible Solution
The issue was introduced in commit: https://github.com/nestjs/nest/commit/40ec0aee09a47040cc7968ec6f3ae2504a0fad4a
```ts
-          return this.createExceptionZone(adapter, prop);

+          return (...args) => {
+            this.createExceptionZone(adapter, prop)(...args);
+            return proxy;
+          };
```
Now proxy always returns itself instead of a method return value.

## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: v12.19.0
- Platform: Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
I think this has been fixed in v8
