### ISSUE TITLE
Union Type

### ISSUE THREAD

**Issue by JonathanWilbur** [nestjs/nest#6914]
## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

The NestJS Documentation describes an `IntersectionType` higher-order decorator [here](https://docs.nestjs.com/techniques/validation#mapped-types). It would be nice to have a `UnionType` that matches at least one of a selection of DTOs.

## What is the motivation / use case for changing the behavior?

I don't know of an elegant "Nest-like" way to validate a request body that can take on one of multiple forms.

**Comment by kamilmysliwiec** [comment]
`IntersectionType`, `PartialType`, `PickType`, and lastly `OmitType` let us dynamically create a new, single inline class constructed based on the original class(or classes) passed into them. This is technically pretty straightforward, as classes themselves are supported by vanilla JavaScript. Union type on the other hand is a TypeScript specific feature, and all unions get erased at the compilation time. In vanilla JavaScript, there's no elegant, native way to represent unions at this point, nor in the `class-validator` package (unless it's a class member/property). Creating a union that behaves as expected would literally require X calls to the `validate` (and `transform`) methods within the `ValidationPipe` to test against a class that the union consists of. I think that in this particular case, it would be easier if `class-validator` exposed a function that constructs unions that are compatible with their validators (and it's not atm).
