### ISSUE TITLE
NestJS fails to serialize BigInt

### ISSUE THREAD

**Issue by alonbilu** [nestjs/nest#6919]
If a service returns an object that contains a value of type BigInt, nest (or express) fails to serialize it and throws the following error:

**TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
...**

## Input Code
<pre>
@Controller('test')
export class TestController {
    @Get()
    GetObject() {
        return {
                 id: BigInt(1234);
        }
    }
}
</pre>

## Expected behavior
Should return a valid Json response

## Possible Solution
Convert the BigInt to numeric or a String

As a temporary fix, I'm calling the following function (which converts all BigInts to String) before returning the object:
<pre>
    public convertBigintToString(obj) {
       
        for (const key in obj) {
            // convert main tree
            if (typeof(obj[key])=='bigint') {
                obj[key] = obj[key].toString();
            }

            for (const prop in obj[key]) {

                // recursively search for inner branches
                if (typeof(obj[key][prop])=='object') {
                    this.convertBigintToString(obj[key])
                } else {
                    if (typeof(obj[key][prop])=='bigint') {
                        obj[key][prop] = obj[key][prop].toString();
                    }
                }
            }
        }
        return obj;
      }
</pre>

Example usage:
<pre>
@Get('xx')
    GetObject() {
        return this.common.convertBigintToString (
        {
                 id: BigInt(1234)
        })
    }
</pre>

## Environment

Nest + Prisma
<pre><code>
Nest version: 7.5.6

 
For Tooling issues:
- Node version: v14.16.1  
- Platform:  Ubuntu

**Comment by micalevisk** [comment]
maybe this is related to https://github.com/expressjs/express/issues/4453

**Comment by kamilmysliwiec** [comment]
This isn't related to Nest framework but rather to the fact that `BigInt` type isn't yet properly supported by `JSON.stringify`.
