### ISSUE TITLE
Cannot find module 'class-validator"

### ISSUE THREAD

**Issue by abelardolg** [nestjs/nest#6926]
## Current behavior

![image](https://user-images.githubusercontent.com/22522883/115225918-eba4eb00-a10e-11eb-92b2-139dd99967e0.png)
## Input Code

![image](https://user-images.githubusercontent.com/22522883/115226011-08412300-a10f-11eb-9ef3-41afc810d3b8.png)

![image](https://user-images.githubusercontent.com/22522883/115226061-15f6a880-a10f-11eb-886f-a16743770687.png)

In local it smoothly runs.

## Expected behavior

I expected this app correctly runs

 "dependencies": {
    "@nestjs/common": "^7.6.15",
    "@nestjs/core": "^7.6.15",
    "@nestjs/mapped-types": "*",
    "@nestjs/mongoose": "^7.2.4",
    "@nestjs/platform-express": "^7.6.15",
    "mongoose": "^5.12.4",
    "nodemailer": "^6.5.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.6"
  }, 

Ubuntu 20.04

**Comment by chenc041** [comment]
may be you  should install  class-validator ?

**Comment by abelardolg** [comment]
Hi @chenc041 ,

Yes, obviously it was.

I didn't see at the documentation that I have to install these packages:
npm install class-validator  class-transformer

Could you add this "npm install" instructions in your documentation, please?

Best regards.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
