### ISSUE TITLE
Requests not responding when using completing observables while @Res() is present in method parameter list.

### ISSUE THREAD

**Issue by jrista** [nestjs/nest#6933]
## Current behavior

A controller method that uses RxJs and Observables never returns a response, even when the observable completes, when the Response object is passed in as a parameter. The sole reason I need the response object, is so I can dynamically set response headers...otherwise, I do not want to have to manually send the response myself with res.send() or anything like that.

I've tried many mechanisms to get my observables to complete, including simply using `of` on static data, and `from` on a basic promise, as well as using `from` with TypeORM services, and explicitly adding a `take(1)` to the end of my pipes. 

The of/from alone should be sufficient, since any observable created with those completes by default (in the same tick of the scheduler, even). It does not seem as though any mechanism of forcing a complete in a stream seem works, though. I often use `take(1)` to cause streams that otherwise would not complete (which shouldn't be the case with my code) to complete after the first value, and that still does not seem to do the trick. 

## Input Code
Very simple reproduction:

```ts
@Get('/:id')
getById(@Param('id', ParseIntPipe) id: number, @Res() res: Response) {
  return of({ id }).pipe( // Reflect passed in id back to client
    tap(() => res.setHeader('cache-control', 'private')) // This is actually determined DYNAMICALLY relative to any incoming Cache-Control header from the client!! Hence why I need the response...
  );; 
}
```

Removing the request from the parameter list of the `getById` method, and commenting out the relevant tap, will result in the code functioning just fine. The ultimate goal is to actually augment the observable (or whatever...promise or normal return value) and attach the headers part using a custom `@OutputCache('cacheName')` decorator...however this issue stopped me before I was able to actually delve into that.

## Expected behavior
The observable should be subscribed to and whatever data is output (or exception thrown) should be handled as normal when returning an observable from a controller method. The mere presence of the `Response` object should not nullify the ability to use an observable to handle a request.

## Possible Solution
Don't require that the response be handled entirely manually simply if it is passed into the method? It seems that if a parameter is decorated with `@Res()`, then suddenly any automatic handling of the returned value from the method is simply ignored.... I actually just tried removing the observables entirely, just to see what would happen, and the request still hangs if I add `@Res()` to the parameter list, and then simply do `return { id };`

It seems like NestJS could do a little bit of snooping of the return value from the method, or maybe spy on the request object a bit? If seems easy enough to simply check if `res.json()` or any other relevant method was called by the method, then NestJS would not bother trying to finish the request itself. Otherwise, if the end developer is NOT manually calling res.json() or any other "send the response" method, Nest should then still step in and handle the finalization itself. 

That would allow end developers such as myself to inject and use the Response object only for setting headers and the like, while still keeping the rest as simple as returning the desired result (or result wrapped in a promise or observable.) It should then probably simply be documented that if an Observable or Promise is returned from the controller method, that res.json() or similar "send the response" methods should not be used. 

## Environment

<pre><code>
Nest version: 7.5.6

 
For Tooling issues:
- Node version: 14.15.4  
- Platform:  Mac 

Others:

</code></pre>

**Comment by jmcdo29** [comment]
This s the expected and documented behavior of Nest. If you inject the response object, it is considered to be taking the library-specific approach and the developer must handle the response. This is to ensure that if `res.send` ends up getting called, that Nest does not try to call it under the hood. The only exception to this is if the options object passed to the `@Res()` decorator contains `{ passthrough: true }` so long as you are using Nest 7.5.3 or greater.

[Library-Specific Approach docs](https://docs.nestjs.com/controllers#library-specific-approach)

**Comment by cottsak** [comment]
> This s the expected and documented behavior of Nest. If you inject the response object, it is considered to be taking the library-specific approach and the developer must handle the response. This is to ensure that if `res.send` ends up getting called, that Nest does not try to call it under the hood. The only exception to this is if the options object passed to the `@Res()` decorator contains `{ passthrough: true }` so long as you are using Nest 7.5.3 or greater.
> 
> [Library-Specific Approach docs](https://docs.nestjs.com/controllers#library-specific-approach)

this is so not obvious
