### ISSUE TITLE
TypeError: Map#toJSON isn't generic

### ISSUE THREAD

**Issue by uncleGena** [nestjs/nest#6939]
## Current behavior
![image](https://user-images.githubusercontent.com/11743243/115382840-3180b280-a1e6-11eb-8fb1-97c35dd2fb35.png)

## Input Code
[reproduction](https://github.com/uncleGena/repro_nestjs_pinata)

```ts
// this doesn't work
const pinataSDK = require('@pinata/sdk');
```

## Expected behavior
require without errors

## Environment

<pre><code>
Nest version: 7.6.15
 
For Tooling issues:
- Node version: v14.16.0
- Platform:  Mac

</code></pre>

May be this bug in pinata I'm not sure
[pinata sdk](https://www.npmjs.com/package/@pinata/sdk)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
