### ISSUE TITLE
How to use has methods for grpc methods? 

### ISSUE THREAD

**Issue by DenisVASI9** [nestjs/nest#6940]
I created my grpc method and call it like this: 
  async findDevice(computer) {
    return await this.database.findDevice(computer).toPromise();
  }
  const res = await findDevice(computer);

After that, I want to check if the data field is there, because, this method uses a declaration with oneof:
message NullableDevice {
  oneof device {
    google.protobuf.NullValue null = 1;
    Device data = 2;
  }
}

But I get the error "hasData is not a function", what to do?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
