### ISSUE TITLE
Prisma support

### ISSUE THREAD

**Issue by incompletude** [nestjs/nest#6952]
## Feature Request

https://www.prisma.io/

The new Prisma version is ready for prod. Can it be supported somehow?

**Comment by jmcdo29** [comment]
[Looks like the Prisma team already has integration instructions on their website](https://www.prisma.io/nestjs). We don't plan to make a package under the NestJS org (at least to my knowledge), but feel free to make a community package if you'd like.

**Comment by incompletude** [comment]
Yes, i saw that later. I'm sorry for opening an issue.
