### ISSUE TITLE
@nestjs/mongoose fails to set default Date

### ISSUE THREAD

**Issue by nickerlan** [nestjs/nest#6975]
## Current behavior
For some reason cannot set default date with @nestjs/mongoose, whether can set it for type "Number".

## Input Code

```ts

@Prop({ type: Number, default: () => 123 })
  someNumber: number;

@Prop({
   type: Date,
   default: Date.now,
})
  someDate: Date;
```

## Expected behavior

I expect both parameters to set default values, but Date type gives me an error on compile. 

```
TypeError: Invalid schema configuration: `Now` is not a valid type at path `someDate.default`.
```

If I comment `// default: Date.now`, compilation goes well and everything works, default value for someNumber is set, and someDate field works also, when I write manually to it. 

If I try `default: () => new Date()`, I get

```
`Default` is not a valid type at path `someDate.default`
```

## Environment

<pre><code>
"@nestjs/core": "^7.5.1",
"@nestjs/mongoose": "^7.2.4",
"mongoose": "^5.12.5",

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

Apr 26, 2021 12:06:16 AM Nick Erlan ***@***.***>:

**Comment by kamilmysliwiec** [comment]
This isn't related to the `@nestjs/mongoose` package, but rather to the underlying `mongoose` library itself. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
