### ISSUE TITLE
CSRF error when using Fastify

### ISSUE THREAD

**Issue by arielhernandezmusa** [nestjs/nest#6978]
## Current behavior
NestJS application crash when start using Fastify and fastify-csrf 

## Input Code

```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';
import helmet from 'fastify-helmet';
import fastifyCsrf from 'fastify-csrf';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  await app.register(helmet);
  await app.register(fastifyCsrf);
  await app.enableCors();
  await app.listen(4000);
}

bootstrap();

```

## Expected behavior
The app must start without errors

## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: v15.6.0
- Platform:  Mac,nux, Windows -->

Others:
</code>

/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/avvio/time-tree.js:40
  if (parentNode.id) {
                 ^

TypeError: Cannot read property 'id' of undefined
    at TimeTree.getParent (/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/avvio/time-tree.js:40:18)
    at TimeTree.add (/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/avvio/time-tree.js:63:27)
    at TimeTree.start (/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/avvio/time-tree.js:78:15)
    at Plugin.<anonymous> (/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/avvio/boot.js:245:36)
    at Object.onceWrapper (node:events:486:26)
    at Plugin.emit (node:events:379:20)
    at Plugin.exec (/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/avvio/plugin.js:130:8)
    at Boot.loadPlugin (/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/avvio/plugin.js:266:10)
    at Task.release (/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/fastq/queue.js:147:16)
    at worked (/Users/ahernandez/pp/labs/node_child_process/droidx-server/node_modules/fastq/queue.js:199:10)

</pre>

**Comment by Tony133** [comment]
Hi @arielhernandezmusa,  have you tried to import FastifyCookie too?

I've tried this and it seems to work:

```
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';
import { fastifyHelmet } from 'fastify-helmet';
import { fastifyCookie } from 'fastify-cookie';
import fastifyCsrf from 'fastify-csrf';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  app.register(fastifyCookie);
  app.register(fastifyHelmet);
  app.register(fastifyCsrf);

  await app.enableCors();
  await app.listen(3000);
}

bootstrap();
´``

At best, try to leave minimal replay in a clonable git repository

**Comment by arielhernandezmusa** [comment]
Thanks, @Tony133 by adding `fastify-cookie` the app starts without errors. close #6978

**Comment by mkgn** [comment]
I get a similar error. I have installed  "@fastify/cookie": "^9.3.1", and "fastify-csrf": "^3.1.0" and basic configuration is as below

    const app = await NestFactory.create<NestFastifyApplication>(AppModule,new FastifyAdapter());

      await app.register(fastifyCookie, {
        secret: app.get(AppSettings).jwt.secret
      });
      await app.register(fastifyCsrf);
      //other code
      await app.listen(app.get(AppSettings).runtimePort);

App doesn't start because I get an error as below

    Uncaught AssertionError AssertionError [ERR_ASSERTION]: The dependency 'fastify-cookie' of plugin 'fastify-csrf' is not registered

If I just comment out the fastifyCsrf registration line app starts fine.

i couldn't find any resources related to this particular error either in nestjs issues or fastify-csrf. Other resources shows a similar code but they have got it working. Anybody have any idea?

**Comment by Tony133** [comment]
> I get a similar error. I have installed "@fastify/cookie": "^9.3.1", and "fastify-csrf": "^3.1.0" and basic configuration is as below
> 
> ```
> const app = await NestFactory.create<NestFastifyApplication>(AppModule,new FastifyAdapter());
> 
>   await app.register(fastifyCookie, {
>     secret: app.get(AppSettings).jwt.secret
>   });
>   await app.register(fastifyCsrf);
>   //other code
>   await app.listen(app.get(AppSettings).runtimePort);
> ```
> 
> App doesn't start because I get an error as below
> 
> ```
> Uncaught AssertionError AssertionError [ERR_ASSERTION]: The dependency 'fastify-cookie' of plugin 'fastify-csrf' is not registered
> ```
> 
> If I just comment out the fastifyCsrf registration line app starts fine.
> 
> i couldn't find any resources related to this particular error either in nestjs issues or fastify-csrf. Other resources shows a similar code but they have got it working. Anybody have any idea?

Try adding `{ cookie: true }`  when registering the `fastify-csrf` plugin like this: `fastify.register(fastifyCsrf, { cookie: true });`
