### ISSUE TITLE
Swagger CLI plugin does not work in a monorepo

### ISSUE THREAD

**Issue by jmroon** [nestjs/nest#6982]
## Current behavior
In a standard yarn workspaces monorepo, many, but not all of the nestjs dependencies are hoisted to the top level node_modules. When attempting to add the nest/swagger plugin to nest-cli, typescript gives the following error on startup:

    Cannot read property 'kind' of undefined

By installing dependencies locally within node_modules rather than hoisting them through yarn workspace, the issue resolves itself.

e.g. with yarn berry:

```
-- .yarnrc.yml --
nmHoistingLimits: dependencies
```

## Expected behavior
Compilation is successful

## Possible Solution
Although I'm not sure which package is causing the issue (as the TS compiler's output is not verbose whatsoever), preventing the hoisting of dependencies to the root node_modules fixes the issue. I expect either the nestjs/swagger package or one of its dependencies it not traversing symlinks correctly.

## Environment

    [System Information]
    OS Version     : Windows 10
    NodeJS Version : v14.16.0
    NPM Version    : 6.14.11
    
    [Nest CLI]
    Nest CLI Version : 7.6.0
    
    [Nest Platform Information]
    platform-express version : 7.6.15
    mapped-types version     : 0.4.1
    swagger version          : 4.8.0
    common version           : 7.6.15
    core version             : 7.6.15

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by jmroon** [comment]
Oddly I can't reproduce this in a new repo. If I do get a reproduction again I'll re-open.
