### ISSUE TITLE
Postgresql highload cause response long time

### ISSUE THREAD

**Issue by car1ot** [nestjs/nest#6987]
## Current behavior
Nest use `Postgresql` and `typeorm`.
We have the request handler, that selects one row of data.
If there are a lot of new requests to the handler at the same time, nest stucks and stop to handle other requests, until previous will be handeled.

`/chat.service.ts`
```
const someData = await this.chatRainRepository.findOne();
return someData;
```

If there is no "ddos" to the request handler, response time is ~30 ms.
If there is "ddos" - a lot of new requests to the handler, response time is ~5 sec.

Also I've tested in PgAdmin the same request, that handler makes and response time is ~200 ms while "ddos" and while no "ddos". The time not changed.

## Expected behavior
The response time in "ddos" from handler should not overweight ~30 - 100 ms. Bot not ~5 sec, as it in "ddos", because Postgresql is not stuck and responding with a good timings while "ddosing" and while not "ddosing".

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
