### ISSUE TITLE
Mongoose middleware not working when importing another module

### ISSUE THREAD

**Issue by levi-ren** [nestjs/nest#6996]
## Current behavior
Middleware post and pre hooks stop working when importing another module to reference a different schema. I am aware of this [issue](https://github.com/nestjs/mongoose/issues/7) and tried to use `useValue` but doesn't work as well, am I missing something? How do I use another schema from another module?

## Input Code

```ts
export const EmployeePostSave: AsyncModelFactory = {
  name: Employee.name,
  inject: [getModelToken(User.name)],
  imports: [UserDataModule],
  useFactory: (userSchema: Model<UserDocument>) => {
    const schema = EmployeeSchema;
    schema.post('save', async function () {
      const user = await userSchema.find();
      console.log(user);
    });
    console.log('x');
    return schema;
  },
};
```

## Environment

<pre><code>
Nest version: 7.6.15
 
For Tooling issues:
- Node version: 14.13.1 
- Platform:  Windows

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
