### ISSUE TITLE
yarn not used when generating a resource for the first time

### ISSUE THREAD

**Issue by philipodev** [nestjs/nest#7003]
## Current behavior
* creating a new project using `nest new` and selecting `yarn` as package manager
* using `nest g resource posts`
* generate method adds `@nestjs/mapped-types` to package.json and installs it using `npm`

## Input Code
new project

## Expected behavior
`@nestjs/mapped-types` should be installed using `yarn` instead of `npm` since that's what i chose when created project.

## Possible Solution
Sadly no idea.

## Environment

<pre><code>
Nest version: 7.6.0

 
For Tooling issues:
- Node version: 14.15.0  
- Platform:  Linux 

Others:
Not relevant
</code></pre>

**Comment by jmcdo29** [comment]
[Similar issue here with information on what the solution can be](https://github.com/nestjs/nest-cli/issues/1115)
