### ISSUE TITLE
Prisma swallows all end-of-lifecycle events

### ISSUE THREAD

**Issue by EkiGui** [nestjs/nest#7005]
I know this is not a problem with Nest itself, but since the documentation provides an official recipe for using Prisma, I thought it was appropriate to open an issue on this topic. I think it will also save some people from searching for hours why their hooks are not triggered.

The Prisma client, at the moment (_v2.21.2_), intercepts the application end of life events (SIGINT, SIGTERM, etc.) and kills the process by itself, so the Nest hooks (`onModuleDestroy`, `beforeApplicationShutdown`, `onApplicationShutdown`) are never called.

This behavior is described on [this issue](https://github.com/prisma/prisma/issues/2917) of Prisma repo, and the alternative presented is the following: 

```ts
const prisma = new PrismaClient()

prisma.on('beforeExit', async () => {
  await prisma.user.deleteMany()
})
```

__I think it would be nice to put a warning about this in Nest "Lifecycle events" documentation__. Also, in the Prisma recipe in the documentation there is a proposed implementation for a PrismaService:

```ts
@Injectable()
export class PrismaService extends PrismaClient
  implements OnModuleInit, OnModuleDestroy {
  async onModuleInit() {
    await this.$connect();
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }
}
```

__This example seems misleading to me, because the `onModuleDestroy` hook will never be called.__

**Comment by kamilmysliwiec** [comment]
Please, report this issue in Prisma repository.
