### ISSUE TITLE
Throwing UnauthorizedException generates invalid HTTP response without WWW-Authenticate

### ISSUE THREAD

**Issue by gh-andre** [nestjs/nest#7011]
## Current behavior

Throwing `UnauthorizedException` from any controller method generates `401 Unauthorized` response that lacks `WWW-Authenticate` header, which is mandatory in the HTTP and Bearer token RFCs:

https://tools.ietf.org/html/rfc2616#section-10.4.2
> 10.4.2 401 Unauthorized
>
> The request requires user authentication. The response MUST include a
> WWW-Authenticate header field (section 14.47) containing a challenge
> applicable to the requested resource.

https://tools.ietf.org/html/rfc6750#section-3
> 3. The WWW-Authenticate Response Header Field
>
> If the protected resource request does not include authentication
> credentials or does not contain an access token that enables access
> to the protected resource, the resource server MUST include the HTTP
> "WWW-Authenticate" response header field;

Even if a custom passport strategy overrides `authenticate` to handle exceptions via the `fail` method, passport strategy wrapper in `auth.guard.js` drops the challenge text and throws a plain `UnauthorizedException`, ignoring `info` and `status`, which are values passed into the `fail` method:
```typescript
        handleRequest(err, user, info, context, status) {
            if (err || !user) {
                throw err || new common_1.UnauthorizedException();
            }
            return user;
        }
```
## Input Code

Throwing `UnauthorizedException` from any controller method will generate an HTTP response without `WWW-Authenticate`.

## Expected behavior

NestJS should provide a way to generate standards-compliant authentication failure HTTP responses and should emit `WWW-Authenticate` header with some challenge text. For bearer tokens it could look along these lines:

```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer realm="my-realm",
                         error="invalid_token",
                         error_description="expired token"
```
As an additional note, NestJS shouldn't throw away failure information generated by custom strategies via `fail` calls.

## Possible Solution

Given that passport functionality is completely abstracted out in NestJS, the challenge test perhaps should go into the HTTP exceptions.

## Environment
<pre><code>
+-- @nestjs/cli@7.5.6
+-- @nestjs/common@7.6.14
+-- @nestjs/core@7.6.14
+-- @nestjs/jwt@7.2.0
+-- @nestjs/passport@7.1.5
+-- @nestjs/platform-express@7.6.14
+-- @nestjs/schematics@7.2.8

For Tooling issues:
- Node version: 14.15.2
- Platform:  Windows
</code></pre>

**Comment by kamilmysliwiec** [comment]
That's the expected behavior. Throwing built-in exception classes will only have an impact on the status code and the response body. Everything else must be implemented manually if needed (for example, in the custom exception filter).
