### ISSUE TITLE
Validation on @Query

### ISSUE THREAD

**Issue by somehowchris** [nestjs/nest#7013]
## Current behavior
I have found multiple tutorials and blogposts on the validation of `@Query` properties with the validation pipe. The main documentation is the [validation docs](https://docs.nestjs.com/techniques/validation#validation) part in the nestjs docs which is fine and works with the `@Body` payload. There seems to be a problem as types like numbers and boolean are not transformed.

## Input Code
I have setup a small repository with it and the pinned dependencies.

https://github.com/somehowchris/nestjs-query-validation-failing

The main parts:

Usage of the pipe:
```typescript
app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
    }),
  );
```

Query class:
```typescript
import { IsBoolean, IsInt, IsPositive, IsString } from 'class-validator';

export class AppSearchQuery {
  @IsString()
  public name: string;
  @IsBoolean()
  public external: boolean;
  @IsInt()
  @IsPositive()
  public age: number;
}
```

The endpoint:
```typescript
  @Get()
  getHello(@Query() query: AppSearchQuery): AppSearchQuery {
    return query;
  }
```

Using the code in the repository you can do:
```bash
curl --location --request GET 'http://localhost:3000/?name=chris&external=false&age=20'
```

Which results in:
```json
{
    "statusCode": 400,
    "message": [
        "external must be a boolean value",
        "age must be a positive number",
        "age must be an integer number"
    ],
    "error": "Bad Request"
}
```

## Expected behavior
The types should be transformed just like with `@Body`

## Possible Solution
I have looked into the Validation Pipe code itself but couldn't find any problems with the pipe itself nor seems the metadata generated for the validation and transformation ok. I literally have no clue.

## Environment

<pre><code>Nest version: 7.6.15

 
For Tooling issues:
- Node version: v14.15.4
- Npm version: 6.14.10
- Platform:  Windows 10 (Version	10.0.18363 Build 18363)

Others:
Has also been tested inside docker with node:14.15.4-alpine

</code></pre>

**Comment by jmcdo29** [comment]
Query and URL Parameters come in as strings by default. This is by design of the underlying adapters. You can [enable implicit transformer](https://github.com/typestack/class-transformer#implicit-type-conversion) or use a [custom transform decorator](https://github.com/typestack/class-transformer#advanced-usage). This is not a problem with Nest. Please use our [Discord](https://discord.gg/nestjs) for more support
