### ISSUE TITLE
Consider upgrade socket.io package

### ISSUE THREAD

**Issue by ymchun** [nestjs/nest#7014]
Hello everyone,

Currently `platform-socket.io` is using `socket.io` version **2.4.1** which has multiple security issues according to [Snyk](https://snyk.io/vuln/search?q=socket.io&type=npm).

Is it possible to upgrade to a higher version of `socket.io`, say **4.0.1**?

**Comment by jmcdo29** [comment]
They're have been several issues brought up about the socket.io version. Please search for those. Nest v8 will update to the happiest version.
