### ISSUE TITLE
setter injection

### ISSUE THREAD

**Issue by Martin-Mok-Tin-Kui** [nestjs/nest#7015]
## Feature Request
I hope that NestJs can support setter injection.  
## Is your feature request related to a problem? Please describe.
Recently, my team need to use request scoped providers to handle some request based states.  
As we found out that request scope bubbles up the injection chain, those providers make the upper controllers request scoped as well.  
We want to use setter injection instead of constructor injection to bypass the constructor injection chain.  
## Describe the solution you'd like
I expect that I can do something like the following:  
```ts
someMethod (@Inject('MYSERVICE') myService: MyService) {
myService.doSomething();
}
```  
## What is the motivation / use case for changing the behavior?
bypass the constructor injection chain.

**Comment by smolinari** [comment]
@Martin-Mok-Tin-Kui - Did you try property based injection? 

https://docs.nestjs.com/providers#property-based-injection

Scott

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
