### ISSUE TITLE
Exact file location of exception

### ISSUE THREAD

**Issue by resid666** [nestjs/nest#7020]
In NestJS I would like to know in which file faulty code I made that makes the application threw an error (while starting application ~nest start~)

In the current situatuion console displays only root level libraries file location which not helpful exatly. Like in Java Spring boot  it is more clear to understand why error occured and which file reason to this. How to make same behaviour in Nest JS?
P.S: Is this a FEATURE ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by resid666** [comment]
@kamilmysliwiec Thanks for reply and sorry for my wrong choise. https://discord.com/invite/G7Qnnhy ==> It says "Invite Invalid"

**Comment by micalevisk** [comment]
@resid666 well this invitation works here. But here you go another one (that will expire in 7 days from now): https://discord.gg/kvDUkuSF
