### ISSUE TITLE
Send file to microservice using TCP transport layer?

### ISSUE THREAD

**Issue by YannisMarios** [nestjs/nest#7029]
Hi,

Is it possible to send a file to a microservice using the TCP transport layer? I already asked in Discord channels but I didn't get any answer.

in my gateway resolver:
![image](https://user-images.githubusercontent.com/11289298/116983449-cbf6f080-acd2-11eb-9ce9-0f9337490abe.png)

in my gateway service
![image](https://user-images.githubusercontent.com/11289298/116984693-33617000-acd4-11eb-9920-ae577db673bd.png)

in my mycroservice controller:
![image](https://user-images.githubusercontent.com/11289298/116983711-1d06e480-acd3-11eb-9f73-1f02a6b16633.png)

All I get in my microservice controller is:

```
{
   filename: 'Screenshot_1.png',
   mimetype: 'image/png',
   encoding: '7bit'
 }
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by YannisMarios** [comment]
> Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

I am writing that I already have asked in discord and I did not get an answer. Do you know the answer or are you just eager to close issues?

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/116987800-cd72e980-accf-11eb-93db-94cd9179f946.png)
