### ISSUE TITLE
Kill exception

### ISSUE THREAD

**Issue by Howsky** [nestjs/nest#704]
## Problem
Server closes after some time (20min-3h usually) without visible reason.

## Logs

<pre><code>
internal/child_process.js:399
      throw errnoException(err, 'kill');
</code></pre>

## Occurance frequency
Always

## Expected behavior
The server should run forever

## Environment

<pre><code>
Nest version: 5.0.0-beta.6
TypeORM: 0.2.5
MongoDB: 3.6

For Tooling issues:
- Node version: 9.11.1
- Platform:  Win10 x64

</code></pre>

**Comment by kamilmysliwiec** [comment]
Have you tried with the latest stable `v5.0.0` version. Also, do you have a bit more logs?

**Comment by menme95** [comment]
I have the same error, this is my log
<pre><code>
(node:7652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.internal/child_process.js:414
      throw errnoException(err, 'kill');
      ^

Error: kill EINVAL
    at ChildProcess.kill (internal/child_process.js:414:13)
    at process.<anonymous> (C:\Users\emengual\Documents\Gitlab\common-service\node_modules\ts-node\dist\bin.js:54:93)
    at process.emit (events.js:187:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! common-service@1.0.0 start: `ts-node -r --inspect=5858 tsconfig-paths/register src/main.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the common-service@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output
above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\emengual\AppData\Roaming\npm-cache\_logs\2018-05-21T09_47_18_219Z-debug.log

</code></pre>

**Comment by Howsky** [comment]
I've checked it with 5.0.0 stable. The problem seems to be resolved :) (so far server is running 12h without a crash)

**Comment by kamilmysliwiec** [comment]
Sweet @Howsky 🙂

**Comment by menme95** [comment]
@kamilmysliwiec @Howsky I still have the error and I'm using v5.0.0

**Comment by jbelford** [comment]
I also get this error. It occurs when I resize my terminal window - it's very odd. I'm on windows.

**Comment by kamilmysliwiec** [comment]
It is a `ts-node` issue. Take a look here: https://github.com/nestjs/nest/issues/595
