### ISSUE TITLE
How to exclude a specific path for controller？

### ISSUE THREAD

**Issue by NNNaix** [nestjs/nest#7050]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

First of all, thank you for the awesome project !

The actual scenario is that I am using both MVC and static service, and because the client is a SPA, I have to set my template render controller match the '*', like below code for transferring routing control privileges to the browser router.

```
Get('*')
```

But frustratingly, I couldn't quite control the priority at which the route matching took effect, which resulted in all my requests for static files matching into the template render route as well.

My thought was to exclude some of the route matches, just like in the spring boot filter. or giving static service a higher priority than controllers but find no way to do that.

Can any of you brothers help me with this problem?

**Comment by kamilmysliwiec** [comment]
Hi @NNNaix! This has been discussed several times in the past so please search through some of our old issues on this. Also, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
