### ISSUE TITLE
[Security] Use `secure-env` for .env files

### ISSUE THREAD

**Issue by RobertLowe** [nestjs/nest#7072]
This is similar to what rails does with its `credentials` command, you can read about it here: https://edgeguides.rubyonrails.org/security.html#environmental-security

The long and short of it is you encrypt any environment file and its only decrypted at run time.

This has a number of advantages:

1. No leaking environment credentials with Web Interfaces (like Heroku for example)
2. Enables environment variable files to be tracked in git

Here's an example of an implementation in node - https://www.npmjs.com/package/secure-env 
* Note: the rails command provides a slightly nicer interface for editing with `rails credentials:edit` which decrypts and opens in your `$EDITOR` and encrypts on save & exit via your `$MASTER_KEY`.

I purpose we add such a mechanism to nestjs.

**Comment by kamilmysliwiec** [comment]
You can easily integrate NestJS with the `secure-env` package if you want to use it in your project. There are many great NPM packages out there and providing official integrations for them (especially when the integration process itself is very seamless) is not doable (time-wise).
