### ISSUE TITLE
Scopes not working as expected

### ISSUE THREAD

**Issue by notmedia** [nestjs/nest#7073]
As documentation says:

`DEFAULT` scope -

> A single instance of the provider is **shared across the entire application**. The instance lifetime is tied directly to the application lifecycle. Once the application has bootstrapped, all singleton providers have been instantiated. Singleton scope is used by default.

`TRANSIENT` scope -

> Transient providers **are not shared across consumers**. Each consumer that injects a transient provider will receive **a new, dedicated instance**.

Let's code.

First with default scope

```ts
let i = 0;

@Injectable({ scope: Scope.DEFAULT })
export class ServiceA {
  i: number;
  constructor() {
    console.log(`created ServiceA ${++i}`);
    this.i = i;
  }
}

@Module({
  providers: [ServiceA],
})
export class ModuleA {}

@Module({
  providers: [ServiceA],
})
export class ModuleB {
  constructor(service: ServiceA) {
    console.log('injected service: ', service.i);
  }
}

@Module({
  imports: [ModuleA, ModuleB],
})
export class AppModule {}
```

outputs:

```bash
[Nest] 15922   - 09/05/2021, 23:56:24   [NestFactory] Starting Nest application...
created ServiceA 1
created ServiceA 2
[Nest] 15922   - 09/05/2021, 23:56:24   [InstanceLoader] AppModule dependencies initialized +25ms
[Nest] 15922   - 09/05/2021, 23:56:24   [InstanceLoader] ModuleA dependencies initialized +0ms
injected service:  2
[Nest] 15922   - 09/05/2021, 23:56:24   [InstanceLoader] ModuleB dependencies initialized +1ms
[Nest] 15922   - 09/05/2021, 23:56:24   [NestApplication] Nest application successfully started +6ms
```

Okay, its default scope but problem with docs. Because docs says that provider is shared across all application. But actually the provider is singletoned only across each module.

In another place in docs I found this:

>  Nest, however, encapsulates providers inside the module scope

So the problem in docs I think.

Go next:

```ts
let i = 0;

@Injectable({ scope: Scope.TRANSIENT }) // SWITCHED HERE TO TRANSIENT
export class ServiceA {
  i: number;
  constructor() {
    console.log(`created ServiceA ${++i}`);
    this.i = i;
  }
}

@Module({
  providers: [ServiceA],
})
export class ModuleA {}

@Module({
  providers: [ServiceA],
})
export class ModuleB {
  constructor(service: ServiceA) {
    console.log('injected service: ', service.i);
  }
}

@Module({
  imports: [ModuleA, ModuleB],
})
export class AppModule {}

```

outputs:

```bash
[Nest] 15955   - 10/05/2021, 00:00:54   [NestFactory] Starting Nest application...
created ServiceA 1
[Nest] 15955   - 10/05/2021, 00:00:54   [InstanceLoader] AppModule dependencies initialized +27ms
[Nest] 15955   - 10/05/2021, 00:00:54   [InstanceLoader] ModuleA dependencies initialized +0ms
injected service:  1
[Nest] 15955   - 10/05/2021, 00:00:54   [InstanceLoader] ModuleB dependencies initialized +1ms
[Nest] 15955   - 10/05/2021, 00:00:54   [NestApplication] Nest application successfully started +6ms
```

We se here that with `Transient` scope `ServiceA` created only once (like it would be with singleton behaviour in angular my guess).

But in fact with `Transient` scope I must get a new instance of provider in each injectable class.

**Comment by jmcdo29** [comment]
Things are actually still working as expected. With `TRANSIENT` scoped services, they are created at the time of injection. If you were to add the same constructor to your `ModuleA` you'd get 
```
Created ServiceA 1
Created ServiceA 2
injected service:  1
injected service:  2
```
This helps to keep the load time down by not needlessly instantiating classes. The same thing happens with `REQUEST` scoped classes, they aren't created until needed. So while a `DEFAULT` provider is created at startup, `TRANSIENT` ones are only created when injected.

**Comment by notmedia** [comment]
Thanks!
