### ISSUE TITLE
ParseArrayPipe always accepts unknown attributes (no whitelist, no forbidNonWhitelisted)

### ISSUE THREAD

**Issue by NitnekB** [nestjs/nest#7080]
## Is your feature request related to a problem? Please describe.

I'm not entirely sure if it's a bug, a regression or a feature request, sorry for that!

I tried to update an array of object using `@Body(new ParseArrayPipe({ items: FuelDto, optional: false }))`

Here's my Dto:

```typescript
export class FuelDto {
  @IsString()
  @IsNotEmpty()
  label: string;

  @IsString()
  @IsNotEmpty()
  pricePerLiter: string;
}
```

The validation works pretty well but I realized I can add any attributes on the payload, which is not good to secure incoming data..

Currently using: `"@nestjs/common": "^7.6.11"`

## Describe the solution you'd like

From `ParseArrayPipe` documentation, it's possible to use some options: `items`, `separator`, `optional` and `exceptionFactory`. Is it possible to add a `whitelist` or `forbidNonWhitelisted` option such as in `ValidatePipe`?

## Teachability, Documentation, Adoption, Migration Strategy

I used the given documentation: https://docs.nestjs.com/techniques/validation#parsing-and-validating-arrays. We could update it to explain how to add  whitelist example...

## What is the motivation / use case for changing the behavior?

I'm a bit surprised we can validate an array of object without ability to restrict unknown attributes.
I think it would be a nice feature to have

**Comment by kamilmysliwiec** [comment]
These are supported https://github.com/nestjs/nest/blob/master/packages/common/pipes/parse-array.pipe.ts#L15
