### ISSUE TITLE
E2E: Change main.ts structure so that a new createNestApplicationFromBootrap() will automatically call bootrap.

### ISSUE THREAD

**Issue by babaliaris** [nestjs/nest#7081]
## Describe the solution you'd like
Currently, you can create [e2e](https://docs.nestjs.com/fundamentals/testing#end-to-end-testing) testing modules and call **createNestApplication()** in order to test a single controller. Though that this works pretty well, you need to [manually override global stuff](https://docs.nestjs.com/fundamentals/testing#overriding-globally-registered-enhancers) that you already have defined in the **bootstrap** function. 

I managed to changes this by moving **bootstrap(): Promise(INestApplication)** outside of the **main.ts** file and calling it inside the **main.ts** file that also calls **listen()**. My method does not create any breaking changes and does not change anything in the current way you make E2E tests according to the documentation.

At the end of this post, I will show you some code to try and make you understand how I changed the bootsrap/main.ts structure
in order to achieve that.

## Teachability, Documentation, Adoption, Migration Strategy
The user could do something like this:
```typescript
//Before all.
  beforeAll(async ()=>
  {

    //Create the testing module.
    const moduleRef = Test.createTestingModule({
      imports: [], //Add imports. You can also import the AppModule if you wish to start the entire framework!!!
      controllers: [],  //Controllers
      providers: [] //Additional providers.
    });

    //Create a NestApplication using the bootrap method which already contains all the global stuff
    //and maybe additional stuff that the developer might add.
    app = moduleRef.createNestApplicationFromBootrap();

    //Listen for connections.
    await app.listen(process.env.PORT);
    
  });
```
Since bootstrap exists in its own file the **createNestApplicationFromBootrap()**  could automatically create an app
instance by calling bootstrap.

## What is the motivation/use case for changing the behavior?
I love e2e tests when it comes to testing controllers in order to make sure that they work, they return the correct
responses, and that the data are being stored correctly in the Database. Because I use global filters and a custom logger I wanted a quick way to set up my e2e (using everything I define in bootstrap), **this why I did the following:**

**src/bootstrap.ts**
```typescript
import { NestFactory } from '@nestjs/core';
import {VampLogger, UnhandledExceptionsFilter} from 'src/services/logger/logger.service';
import { INestApplication } from '@nestjs/common';


/**
 * 
 * @param rootModule The root Module() of your project.
 * @returns The app instance.
 */
export async function bootstrap(rootModule: any): Promise<INestApplication>
{
  //Create the app.
  const app = await NestFactory.create(rootModule);

  //Create the logger.
  const logger = new VampLogger("Agro Ajenda", true);

  //Create the filter.
  const filter = new UnhandledExceptionsFilter(logger);

  //Use the logger.
  app.useLogger(new VampLogger("Agro Ajenda", true));

  //Use the global filter.
  app.useGlobalFilters(filter);

  //Return the app.
  return app;
}
```

**src/main.ts**
```typescript
import {bootstrap} from './bootstrap';
import { AppModule } from './app.module';
import {INestApplication} from '@nestjs/common';
import {ConfigService} from '@nestjs/config';
import * as assert from 'assert';

//Entry Point.
async function entryPoint()
{
    //Bootstrap the Application.
    const app:INestApplication = await bootstrap(AppModule);

    //Get the configuration service.
    const configServ = app.get<ConfigService>(ConfigService);

    //Get the port from the process.env.PORT.
    const port = configServ.get<number>('PORT');

    //Assert the port.
    assert(port, "Make sure you have a PORT variable in .env file.");

    //Start Listening.
    await app.listen(port);
}


entryPoint();
```

**An example e2e test (Check the beforeAll()  function):**
```typescript
import {Test} from '@nestjs/testing';
import {bootstrap} from 'src/bootstrap';
import {UsersController} from './users.controller';

import {ServicesModule} from 'src/services/services.module';
import {MysqlService} from 'src/services/mysql/mysql.service';
import {JwtService} from 'src/services/jtw/jwt.service';

import {UserLoginWithEmailModel, UserLoginWithUsernameModel} from 'src/models/user-login.model';
import {TokenModel} from 'src/models/token.model';
import {DeviceIDModel} from 'src/models/device-id.model';

import { INestApplication } from '@nestjs/common';
import * as axios from 'axios';


describe('UsersController', () => {

  //Module Instances.
  let app: INestApplication;
  let controller: UsersController;
  let mysqlServ: MysqlService;
  let jwtServ: JwtService;

  //Some other variables.
  let user_id = -1;

  //Before all.
  beforeAll(async ()=>
  {

    //Create the testing module.
    const moduleRef = Test.createTestingModule({
      imports: [ServicesModule],
      controllers: [UsersController]
    });

    //Start the app.
    app = await bootstrap(moduleRef);

    //Listen for connections.
    await app.listen(process.env.PORT);

    //Get the controller instance.
    controller = app.get<UsersController>(UsersController);

    //Get The MysqlService.
    mysqlServ = app.get<MysqlService>(MysqlService);

    //Get JtwService Service.
    jwtServ = app.get<JwtService>(JwtService);
    
  });


  //After all.
  afterAll(async ()=>
  {
    //Terminate the app.
    await app.close();
  });
  
 .
 .
 .
```

**Comment by kamilmysliwiec** [comment]
This has been several times in the past. Your approach is indeed correct but since there are so many different ways you could/want to configure your app in e2e tests, to remain flexible we don't recommend any specific approach (yet?).

**Comment by babaliaris** [comment]
> This has been several times in the past. Your approach is indeed correct but since there are so many different ways you could/want to configure your app in e2e tests, to remain flexible we don't recommend any specific approach (yet?).

I understand this completly. Thank you for your review!
