### ISSUE TITLE
Setting the log levels using ConfigService

### ISSUE THREAD

**Issue by fmagno** [nestjs/nest#7108]
How can I set the allowed log levels by using the ConfigService?

I tried to do it through main.ts but the logLevels are set during the `app` creation call which is also required to `get` the ConfigService.
``` typescript
const app = await NestFactory.create(
    AppModule.register(),
    { logger: configService.get('LOG_LEVELS') }    // <-- at this point I still can't do: const configService = app.get(ConfigService);
);
```

Is is possible to create the `app` object with the logLevels set to default and then override it? Something like this:

``` typescript
const app = await NestFactory.create(
    AppModule.register(),
    { logger: true }
);

const configService = app.get('ConfigService');
app.setLogLevels(configService.get('LOG_LEVELS'));
```

Also tried a different avenue but the solution is not ideal. I tried first to set the logLevels in the constructor of MyLogger but the class member logLevels is private to Logger so I can't override it. The same seems to be the case for the method `isLogLevelEnabled(level)`.

The only option I found so far is to check the logLevels allowed inside the actual logging methods: log, warn, error, etc...

``` typescript
@Injectable()
export class MyLogger extends Logger {
    constructor(private configService: ConfigService) {
        super();
        MyLogger.logLevels = configService.get('LOG_LEVELS')   // <-- can't set because it's private to Logger
    }

    isLogLevelEnabled(level) {}   // <-- can't override because it's private to Logger


    log(message: any, context? string): void {
        const logLevels = this.configService.get('LOG_LEVELS');
        // check if this method has the right level to log the message depending on logLevels before proceeding
        super.log(message, context);
    }
}
```

Is there a better way to do this?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by fmagno** [comment]
Okay, cheers!

Just so it doesn't get lost in discord messages, this question relates to these issues: #6349 and #2343.
