### ISSUE TITLE
Query mongodb by date range using Timestamp

### ISSUE THREAD

**Issue by dwarak123** [nestjs/nest#7113]
Hello, 

I am using nestjs to host api's one of the requirements is to extract mongodb documents by date range. I have implemented timestamps in the mongoose schema and created a GET function to get the data. The function itself works below is the function 

 @Get('/dateRange/:dateFrom/:dateTo')
  async findDateRange(
    @Res() res,
    @Param('dateFrom: Format YYYY-MM-DD') dateFrom: string,
    @Param('dateTo: Format YYYY-MM-DD') dateTo: string,
  ) {
    const filter = {};    
    if (dateFrom) {
      if (!filter["createdAt"]) filter["createdAt"] = {};
     const from = dateFrom + 'T00:00:00.000Z';
      filter["createdAt"]['$gte'] = from;
    }
    if (dateTo) {
      if (!filter["createdAt"]) filter["createdAt"] = {};
      const to = dateTo +  'T23:59:59.999Z';
      filter["createdAt"]['$lte'] = to;
    }
    try {
      logger.log(filter);
      const lists = await this.servicesService.find(filter);
      if (!lists) throw new NotFoundException('Document does not exist!');
      return res.status(HttpStatus.OK).json(lists);
    } catch (err) {
      res.status(HttpStatus.BAD_REQUEST).json(err);
    }
  }

But I am not able to pass parameters using @Param All my other functions work for other filters. The only difference I am see is that I am using parameters from the existing schema the above users just strings that I am trying to pass through the URL. I am not sure what am I doing wrong......Your help is appreciated

**Comment by jmcdo29** [comment]
Your `@Params()` are incorrectly formatted.

Please use our [Discord](https://discord.gg/nestjs) for further support. We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
