### ISSUE TITLE
Typescript support for regex controller hosts

### ISSUE THREAD

**Issue by ccontour** [nestjs/nest#7120]
## Describe the solution you'd like
Currently, the `@Controller` annotation expects a string as it's host input (according to docs + typescript). However, since the property is passed through the [path-to-regexp](https://www.npmjs.com/package/path-to-regexp) library, there is currently also support for passing in regular expressions for this property.

I'd like to have the typescript definition for the host param updated to also indicate it allows for regular expressions to reflect this (perhaps accidental) support.

From local testing, everything works as I would expect. Requests not going to a matched domain return 404's, and `@HostParam` will return capture groups from the expression (ex: `@HostParam('0')`)

## What is the motivation / use case for changing the behavior?
Regular expressions can be used for negative look ahead functionality in url matching. For example, a wrapper around `@Controller` to ignore specific subdomains, but still capture the subdomain name (while ignoring the rest of the domain)

```
export const IgnoreSubdomainsController = (
  ignoreList: string[],
): ReturnType<typeof Controller> => {
  // @ts-ignore
  return Controller({
    host: new RegExp(`^(?!${ignoreList.join('|')})([^/]+?)\\.(.*)/?$`),
  });
};
```

I can then block off certain subdomains but have not tie myself to any particular top level domain:
```
@IgnoreSubdomainsController(['portal', 'blog'])
export class MyApiController {
  @Get('/:param')
  public fetchParam(
    @HostParam('0') project: string,
    @Param('param') parameter: string,
  ) {
    // ... logic
  }
}
```

This operation cannot be performed using string hostnames, since a negative lookahead does not work there. The exclamation mark inside the group gets escaped, breaking the entire expression and causing the server to fail to start

**Comment by jmcdo29** [comment]
Seems like a useful improvement. Would you like to create a PR? We probably won't merge it until after the v8 release, but it would be great to see this addition as it seems to be just types

**Comment by ccontour** [comment]
Sounds good to me, I'll open one tomorrow
