### ISSUE TITLE
How to end SSE connection from server?

### ISSUE THREAD

**Issue by softmarshmallow** [nestjs/nest#7125]
NestJS Forces us to use Observable for SSE. It's convenient, but not for some specific cases.

**My case**
I have this application called [assistant](https://github.com/bridgedxyz/assistant) which is a figma plugin, means it can not use browser url callback. so for the app's authentication i have to open a sse connection from the app and wait for the user to authenticate(login) from the different platform(web). when user completes the auth from the web, server sends a event to client that auth with complete with some credentials.

In this scenario, i only have to trigger the event once, send data once.
Current implementation does the sending event part, but not the automatic disposing. (I can close manually from client. but why would I?)
```
  @Sse('/session/listen')
  listenAuthenticationStatusFromProxySource(): Observable<any> {
     // this is a mock promise for waiting for user to authenticate
    const pr = Promise.resolve('data');
    const obs = from(pr).pipe(finalize(() => console.log('End')));
    return obs;
  }
```

I tried using `finilize` but testing from the browser won't close the connection. (progress bar keeps loading)

Help me with this case ! Thanks :)

**Comment by kamilmysliwiec** [comment]
`finalize` is an operator that lets you react when the stream ends, but it doesn't itself close the observable stream. To control the stream's lifecycle, you would have to create an observable by yourself :)

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
