### ISSUE TITLE
graphql cors error with aws lamdba

### ISSUE THREAD

**Issue by YeomDongUk** [nestjs/nest#7134]
I use severless and nest graphql with lambda.
fetch express ( controller/event ) is possible. 
but fetch graphql return cors error 
<pre><code>
GraphQLModule.forRoot({
      autoSchemaFile: true,
      cors: {
        origin: '*',
        credentials: true,
      },
      playground: {
        endpoint: process.env.IS_NOT_SLS === 'true' ? '/graphql' : `/${process.env.STAGE}/graphql`,
      },
    }),
</code></pre>

how can i fix it?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
