### ISSUE TITLE
nginx + nestjs dist folder

### ISSUE THREAD

**Issue by puffanddmx** [nestjs/nest#7136]
hi

i have a question.

for the normal dist folder for not nestjs production build, there is the index.html file for the nginx route.
but for the dist to run production build nestjs, there is no file for index.html in dist folder -> so nginx cannot found it.
how to solve this with nginx to find index.html in nestjs prod build dist to work well for the route?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
