### ISSUE TITLE
[Bug] Type 'TServer' does not satisfy the constraint 'Http2Server'.

### ISSUE THREAD

**Issue by JaeWangL** [nestjs/nest#7147]
## Bug Report
When using with `@nestjs/platform-fastify`,
At build time, Type error occured

## Current behavior
Can't build because of type error in `fastify-adapter.d.ts - line 26`.

## Possible Solution
I'm temporarily remove `FastifyHttp2Options<TServer> | FastifyHttp2SecureOptions<any>`
But this is not good solution

## Environment
```
    "@nestjs/common": "^7.6.15",
    "@nestjs/config": "^0.6.3",
    "@nestjs/core": "^7.6.15",
    "@nestjs/jwt": "^7.2.0",
    "@nestjs/passport": "^7.1.5",
    "@nestjs/platform-fastify": "^7.6.15",
    "@nestjs/swagger": "^4.8.0",
    "@nestjs/testing": "^7.6.15",
    "@nestjs/typeorm": "^7.1.5",
```

Nest version: 7.6.15

 
For Tooling issues:
- Node version: 14
- Platform:  Mac

Others:
<img width="1326" alt="Screen Shot 2021-05-18 at 3 31 28 PM" src="https://user-images.githubusercontent.com/42147939/118603236-9ed83100-b7ee-11eb-9d99-ef6c9c9c0b44.png">

**Comment by kamilmysliwiec** [comment]
Fixed in 7.6.16
