### ISSUE TITLE
On Development Machine can able to use client side (react) port and run whole project on single Server side Port like dotnet core UseProxyToSpaDevelopmentServer

### ISSUE THREAD

**Issue by amitsinghrawat1994** [nestjs/nest#7148]
## Feature Request
On Development Machine can able to use client-side (react) port and run the whole project on single Server-side Port

I am from a Dotnet core background. and It has a feature to run a client-side port under a server-side. Like below

https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-5.0&tabs=visual-studio#run-the-cra-server-independently

Can this is also possible in NestJs ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
