### ISSUE TITLE
TypeError: Cannot read property 'XXX' of undefined

### ISSUE THREAD

**Issue by ddimitrioglo** [nestjs/nest#7151]
## Current behavior
HttpStatus enum does not export it's own keys

## Input Code

`console.log(HttpStatus);`

with v7.6.14
```
{
  '100': 'CONTINUE',
  '101': 'SWITCHING_PROTOCOLS',
  '102': 'PROCESSING',
  '103': 'EARLYHINTS',
  '200': 'OK',
  '201': 'CREATED',
  ...
```
with v7.6.17

```
undefined
```

**Comment by xiniria** [comment]
@ddimitrioglo Fixed in `v7.6.17` thanks to commit [8ef6c42](https://github.com/nestjs/nest/commit/8ef6c429d3220cb1bbaaa4ebbb9d80ebf5fd283a).
