### ISSUE TITLE
Test expectations in error handlers

### ISSUE THREAD

**Issue by tonyhallett** [nestjs/nest#7153]
Just a heads up.  I was looking through some old work and...

## Current behavior
I suggested that you use the linter to disallow such behaviour in https://github.com/nestjs/nest/issues/3491 and provided a list of tests with expectations in error handlers.

https://github.com/nestjs/nest/issues/3491#issuecomment-559710245

> As for custom tslint rules, I don't think that we necessarily need them. These issues that you've found are very likely one-time fixes. It should be fine to just fix them now and pay more attention to such cases in the future (during code reviews).

This test was added some time later
https://github.com/nestjs/nest/blob/d90516640f65c12746771a722a91e48a448aac81/integration/injector/e2e/scoped-instances.spec.ts#L90

```
  it('should throw an exception when "resolve()" method is used for static providers', async () => {
    try {
      await testingModule.resolve(STATIC_FACTORY);
    } catch (err) {
      expect(err).to.be.instanceOf(InvalidClassScopeException);
    }
  });
```

## Expected behavior
No expectations in error handlers

## Possible Solution
!

**Comment by kamilmysliwiec** [comment]
If you have already found such an issue, could you just open a PR with a one-line fix to address this?
