### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by M3sca** [nestjs/nest#7162]
## Current behavior
In the documentation, there is a small typo.
https://docs.nestjs.com/techniques/configuration
In this paragraph:
"Once the package is installed, we use yaml#load function to load YAML file we just created above."
There is config.yml filename and in other source example it was call config.yaml.

**Comment by jmcdo29** [comment]
You can make a PR to the docs repo if you'd like

**Comment by M3sca** [comment]
Done!
I close this "issue".
