### ISSUE TITLE
feat: Add logging for WebSockets when we mount gateways

### ISSUE THREAD

**Issue by Ayzrian** [nestjs/nest#7165]
## Feature Request
Add logging for WebSockets when we mount gateways

## Is your feature request related to a problem? Please describe.
The problem is that there is no logging when you are working with gateways, for example when Nest.js mounts HTTP endpoints you can see in the logs that such endpoints were mounted and etc. So when you are working with Gateways you are completely blind, whether it works or not. 

## Describe the solution you'd like
Add logging for Gateways, which gateway class mounted as a gateway, which method mounted to which WebSocket message. 
Also, we may add logging to the socket creation and etc. 

## Teachability, Documentation, Adoption, Migration Strategy
Totally backward compatible change.

## What is the motivation / use case for changing the behavior?
Add more visibility when working with the WebSocket. 

FWIW, I have a desire to submit PR myself. 🙂

**Comment by mani9896** [comment]
@kamilmysliwiec can i work on this one , if possible?

**Comment by jmcdo29** [comment]
Seems useful! I'd say go for it! Looking forward to the PR

**Comment by mani9896** [comment]
@jmcdo29 Hey thanks , If possible can i get some help support with code structure and guidance . 
New Contributor here

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8203
