### ISSUE TITLE
Exception Filter

### ISSUE THREAD

**Issue by franxx32** [nestjs/nest#7166]
Hi, i want to use custom exception filter 
it's look like
```
@Catch()
export class ErrorHandlingFilter implements ExceptionFilter {
  constructor(private readonly logger: Logger) {}

  catch(error: HttpException, host: ArgumentsHost): void {
    const exception = error instanceof HttpException ? error : new InternalServerErrorException(error);
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const status = exception.getStatus();

    this.logger.error(error);
    response.status(status).json({
      statusCode: status,
      message: exception.message,
      timestamp: new Date().toISOString()
    });
  }
}
```
When BadRequest Error happens from validator 
`message: exception.message` return `Bad Request Exception` message
But i expected sth like `["offset must not be less than 0"]`
That message (what i wanted) located exception.response.message but HttpException Interface  not provided access there
Is it a bug ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by franxx32** [comment]
@kamilmysliwiec 
So this behavior kind of OK
When i do this -> ` throw new InternalServerErrorException('Lol this is work')`
Message looks like 
```
{
"statusCode": 500,
"message": "Lol this is work",
"timestamp": "2021-05-20T13:10:27.615Z"
}
```
-------------------------
One the other hand when i do this `throw new InternalServerErrorException(['Lol this', 'is work!?']);`
I get this response
{
"statusCode": 500,
"message": "Internal Server Error Exception",
"timestamp": "2021-05-20T13:47:28.554Z"
}

Message not provided correctly 
All other code the same

Is it correct behavior ??

**Comment by kamilmysliwiec** [comment]
> Is it correct behavior ??

Yes
