### ISSUE TITLE
Global exception filter catching middleware error but not returning graphql response

### ISSUE THREAD

**Issue by piyushk96** [nestjs/nest#7167]
## Bug Report
Errors thrown from the middleware is caught by the global exception filter in graphql but the `HttpException` returned from exception filter is not returned in graphql response. Also, the functions `formatError` and `formatResponse` passed in `GraphQLModule.forRoot` doesn't gets executed in this case. In case if error is thrown from mutation/query function then everything works fine.

## Current behavior
I'm trying to use [graphql-upload](https://github.com/jaydenseric/graphql-upload) for uploading files to my graphql server. Here, if `graphqlUploadExpress` middleware throws an exception it is catched by the global exception filter added in `main.ts` (as expected) but HttpException returned from filter is not returned in graphql response. Also, the request gets stuck in the middle and doesn't gets complete

## Input Code
https://codesandbox.io/s/smoosh-thunder-wcve5

```
curl localhost:3000/graphql \
  -F operations='{ "query": "mutation ($file: Upload!) { upload(file: $file) }", "variables": { "file": null } }' \
  -F map='{ "0": [`variables.file`] }' \
  -F 0=@a.txt
```
Here I'm sending wrong json in map field so `graphqlUploadExpress` will throw an error.

## Expected behavior
Graphql request should complete with error response.

## Environment

<pre><code>
@nestjs/common: ^7.5.1
@nestjs/core: ^7.5.1
@nestjs/graphql: ^7.9.8
graphql-upload: ^12.0.0

 
Node version: 14

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions (similar issues were discussed several times in the past). We are using GitHub to track bugs, feature requests, and potential improvements.
