### ISSUE TITLE
ValidationPipe: Option for disabling error message details

### ISSUE THREAD

**Issue by cvh23** [nestjs/nest#717]
[ ] Regression
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request

## Current behavior

Currently every property of a DTO which couldnt be validated successfully is stated in the BadRequest exception of ValidationPipe as the error messages from class-validator are directly passed to the client.

## Expected behavior

It would be good to have an option for not forwarding ANY class-validator error messages to the client/user by extending the ValidationPipeOptions with a boolean switch. The ValidationPipe should then just answer a request with a simple BadRequest exception in case of unsuccessful validation.

## Minimal reproduction of the problem with instructions

https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts

## What is the motivation / use case for changing the behavior?

In a high security environment you may dont wont to expose detailed error messages or the cause for a bad request, especially if the API is not made for public access, but more for a certain frontend. On the other hand, in a development environment, it would still be good to have detailed error messages. With the option one can set the behavior according to his needs/environment.

## Environment

<pre><code>
Nest version: 5.0.0
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Mac

Others:
--
</code></pre>

**Comment by kamilmysliwiec** [comment]
I'll add it really soon. Thanks!

**Comment by kamilmysliwiec** [comment]
The `disableErrorMessages` option has been added. Will be available soon.

**Comment by kamilmysliwiec** [comment]
Lets' track this issue here https://github.com/nestjs/docs.nestjs.com/issues/100
