### ISSUE TITLE
Add support for Nats 2.0.4+

### ISSUE THREAD

**Issue by jubairsaidi** [nestjs/nest#7170]
## Is your feature request related to a problem? Please describe.

Currently Nats 2.0.4 node package breaks your app when it uses nats.

## Describe the solution you'd like

Add support for V2 Nats, which comes with some nice new features.

## What is the motivation / use case for changing the behavior?

Adding support to more modern nats features

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/6349
