### ISSUE TITLE
Nest project crush and raise exception when the working directory contains '('

### ISSUE THREAD

**Issue by mysthogm** [nestjs/nest#7172]
## Current behavior
Steps to reach this issue
- Inside a directory '/tmp/test(test)'
- Run CLI `nest new project`
- Change directory to the new project '/tmp/test(test)/project'
- Run command `yarn && yarn start`

/bin/sh: -c: line 0: syntax error near unexpected token \`('
/bin/sh: -c: line 0: `node /tmp/test(test)/project/dist/main'

## Expected behavior
Expect the program to start without mentioned error.

## Possible Solution
N/A

## Environment

<pre><code>
Nest version: 7.6.0
 
For Tooling issues:
- Node version: v16.2.0
- Platform:  Mac

**Comment by jmcdo29** [comment]
I can reproduce this, but I'm not sure if it's at the Nest CLI level, or if it comes from a lower level CLI (like `tsc` or `node`). I'll take a quick look, but what's the use case for a directory with a `(` in the name? Any sort of navigation to that directory will require escape characters, and will probably cause more problems than they solve.

**Comment by jmcdo29** [comment]
Here's a bit more of a stack trace, looks like this may come from packages that get created as CLI commands with `node`
```
node --trace-uncaught --trace-warnings --trace-exit ./node_modules/.bin/nest start
/home/jay/Documents/code/help/with(parenthesis)/test/node_modules/.bin/nest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Thrown at:
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Module._load (internal/modules/cjs/loader.js:769:14)
    at executeUserEntryPoint (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(node:30334) WARNING: Exited the environment with code 1
```

**Comment by mysthogm** [comment]
> I can reproduce this, but I'm not sure if it's at the Nest CLI level, or if it comes from a lower level CLI (like `tsc` or `node`). I'll take a quick look, but what's the use case for a directory with a `(` in the name? Any sort of navigation to that directory will require escape characters, and will probably cause more problems than they solve.

About the use case, we have project that name has the '(', that's why we create the same directory name with this character. I think this is expected nowadays that the directory name can be anything as long as it is utf8.

Another point, the error message is a bit misleading, it took quite a while to guess that the error means the issue in directory name

Thanks.

**Comment by jmcdo29** [comment]
I think this is an issue with node bin scripts and not something handled at the Nest level. If you take a look at the `node_modules/.bin/nest` you'll see this
```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

export NODE_PATH="~/Documents/code/projects/nestjs-commander/node_modules/.pnpm/@nestjs+cli@7.5.4/node_modules/@nestjs/cli/bin/node_modules:~/Documents/code/projects/nestjs-commander/node_modules/.pnpm/@nestjs+cli@7.5.4/node_modules/@nestjs/cli/node_modules:~/Documents/code/projects/nestjs-commander/node_modules/.pnpm/@nestjs+cli@7.5.4/node_modules/@nestjs/node_modules:~/Documents/code/projects/nestjs-commander/node_modules/.pnpm/@nestjs+cli@7.5.4/node_modules:~/Documents/code/projects/nestjs-commander/node_modules/.pnpm/node_modules:~/Documents/code/projects/nestjs-commander/node_modules:~/Documents/code/projects/node_modules:~/Documents/code/node_modules:~/Documents/node_modules:~/node_modules:/home/node_modules:/node_modules:~/Documents/code/projects/nestjs-commander/node_modules/@nestjs/cli/bin/node_modules:~/Documents/code/projects/nestjs-commander/node_modules/@nestjs/cli/node_modules:~/Documents/code/projects/nestjs-commander/node_modules/@nestjs/node_modules"
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../@nestjs/cli/bin/nest.js" "$@"
else
  exec node  "$basedir/../@nestjs/cli/bin/nest.js" "$@"
```
(note, I use pnpm and cleaned to remove my home directory)

This error comes from that first line `basedir=$(dirname "$(echo "$0" | sed -e 's\\,/,g')")`. 

There isn't much Nest can do about this. You'll notice `jest` and `husky` "suffer" from the same problem. It's something `node` manages, not the CLIs you're making use of.

**Comment by kamilmysliwiec** [comment]
It sounds like there's nothing we can do on our side, unfortunately. @jmcdo29 thanks for sharing your notes & research
