### ISSUE TITLE
Seems that DynamicModule does not work with strict mode, but the docs are not telling about it

### ISSUE THREAD

**Issue by ProteanCode** [nestjs/nest#7173]
At this phase, I am learning the framework and I started by making a standalone app to check the IoC & how the modules work together.

Static modules so far are not making a problem, but I want to create another module that uses different service based on remote server healthcheck.

For example, if a health check for firebase messaging is fine, then use Firebase service for sending messaging, otherwise use a private RabbitMQ server. Just a fallback behaviour for the app.

This code works:

```
async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);
  const messenger = app.get(FirebaseService);
  await app.close();
}

bootstrap();
```

but this one does not:

```
async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);
  const messenger = app
    .select(MessagingModule)
    .get(FirebaseService, { strict: true });
  await app.close();
}

bootstrap();
```

Above throws **Nest could not select the given module (it does not exist in current context)** error

I will quickly add here a modules declarations:

```
@Module({
  imports: [MessagingModule.register()],
})
export class AppModule {}
```

```
@Module({})
export class MessagingModule {
  static register(): DynamicModule {
    return {
      module: MessagingModule,
      providers: [FirebaseService],
      exports: [FirebaseService],
    };
  }
}
```

So for me it looks like dynamic modules cannot be used in strict mode due to the fact these are loaded at runtime, not compile time.

I may be wrong tho, docs are not telling me anything about that.

**Comment by ProteanCode** [comment]
This is something else.

The following code crashes and it is not a strict mode

```
  const app = await NestFactory.createApplicationContext(AppModule);
  const mm = app.select(MessagingModule);
```

**Comment by ProteanCode** [comment]
This is caused because of using `MessagingModule.register()` in AppModule import decorator, without it the module is still visible, but Service is not.

**Comment by jmcdo29** [comment]
Thank you for all the information! Can you leave a minimum reproduction repository as well?

**Comment by ProteanCode** [comment]
> Thank you for all the information! Can you leave a minimum reproduction repository as well?

Based on typescript template project

https://github.com/ProteanCode/samples-nestjs

**Comment by jmcdo29** [comment]
Okay, due to the way that the `ModuleRef`'s `select` method works, it needs to match the module completely, meaning in the `main` you need to do `app.select(MessagingModule.register()).get(FirebaseService)`. As you can assume, this would cause problems if you need to end up getting the config again, so as an option instead, you can do `app.get(FirebaseService, { strict: false })` to pull the service from __anywhere__ in the application.

**Comment by ProteanCode** [comment]
> Okay, due to the way that the `ModuleRef`'s `select` method works, it needs to match the module completely, meaning in the `main` you need to do `app.select(MessagingModule.register()).get(FirebaseService)`. As you can assume, this would cause problems if you need to end up getting the config again, so as an option instead, you can do `app.get(FirebaseService, { strict: false })` to pull the service from **anywhere** in the application.

Ok, but the question is if I did something wrong? I think i have been following the docs quite strictly so far

**Comment by jmcdo29** [comment]
> id I [do] something wrong?

Nope, it's all correct, just how the `select` method works. The metadata needs to match, and `MessagingModule` on it's own does not match (it doesn't have the same providers) so you need to use the `MessagingModule.register()` to make sure the metadata is the same. This is why I mentioned just using  `{ strict: false }` instead.

**Comment by ProteanCode** [comment]
Thanks, I guess I understand now :)
