### ISSUE TITLE
How to launch a specified main file with nest cli

### ISSUE THREAD

**Issue by GO-DIE** [nestjs/nest#7176]
## Is your feature request related to a problem? Please describe.

My project has two main files, one is about APP and the other is about APP admin background system. The specified main file needs to be launched during deployment

## Describe the solution you'd like
How to launch a specified main file with nest cli？

**Comment by jmcdo29** [comment]
You would need two separate `nest-cli.json` files, one with the standard setup, one with an `entryFile` option pointing to the admin launch. 

For further help, please visit our [Discord](https://discord.gg/nestjs) for Support. We are using GitHub to track Bug Reports, Feature Requests and Regressions.

**Comment by GO-DIE** [comment]
> You would need two separate `nest-cli.json` files, one with the standard setup, one with an `entryFile` option pointing to the admin launch.
> 
> For further help, please visit our [Discord](https://discord.gg/nestjs) for Support. We are using GitHub to track Bug Reports, Feature Requests and Regressions.

Thank you.
Where can I find the relevant information in the document.

**Comment by jmcdo29** [comment]
We're working on the `nest-cli.json` options documentation. For now, I've just used the [source code](https://github.com/nestjs/nest-cli/blob/master/actions/start.action.ts#L75) and read through it

**Comment by vfrank66** [comment]
This would be nice to have as a nest start --entryFile <filename> option instead of having to create two nest-cli.json options with differing configuration for "entryFile"

**Comment by jmcdo29** [comment]
You mean like how `nest start --help` shows that `--entryFile` is an option that you can pass?

```
nest start --help
Usage: nest start [options] [app]

Run Nest application.

Options:
  -c, --config [path]        Path to nest-cli configuration file.
  -p, --path [path]          Path to tsconfig file.
  -w, --watch                Run in watch mode (live-reload).
  --watchAssets              Watch non-ts (e.g., .graphql) files mode.
  -d, --debug [hostport]     Run in debug mode (with --inspect flag).
  --webpack                  Use webpack for compilation.
  --webpackPath [path]       Path to webpack configuration.
  --tsc                      Use tsc for compilation.
  --sourceRoot [sourceRoot]  Points at the root of the source code for the single project in
                             standard mode structures, or the default project in monorepo mode
                             structures.
  --entryFile [entryFile]    Path to the entry file where this command will work with.
                             Defaults to the one defined at your Nest's CLI config file.
  -e, --exec [binary]        Binary to run (default: "node").
  --preserveWatchOutput      Use "preserveWatchOutput" option when tsc watch mode.
  -h, --help                 Output usage information.
```

**Comment by micalevisk** [comment]
that feat was added in `@nestjs/cli@8.2.7` @vfrank66

**Comment by vfrank66** [comment]
Looks like I need to upgrade from v7.x thank you
