### ISSUE TITLE
Is there formal API documentation?

### ISSUE THREAD

**Issue by J-Rojas** [nestjs/nest#7177]
Hi, the Nestjs project appears to be fairly mature at this time. Is there formal API documentation somewhere? The comprehensive guide that is online is helpful, but it doesn't cover the specifics details of the framework API objects and functions. I find myself trying to hunt through example code and the code base itself to understand how I might be able to do something the guide doesn't fully explain.

**Comment by jmcdo29** [comment]
[There's an open PR that laid some groundwork](https://github.com/nestjs/docs.nestjs.com/pull/413), but there's nothing definite, and it needs to be re-visited.
