### ISSUE TITLE
Is there a concept of unimplemented provider?

### ISSUE THREAD

**Issue by ProteanCode** [nestjs/nest#7178]
Imagine a project that uses a messaging module, in which we use three services (ie. Slack, FCM, Facebook). These services are responsible for sending push messages.

Imagine, if three of these services would be down.

Which provider should I pick then, if there is no message to send?

I doubt returning a null value from `useFactory` is a legitimate way for solving this puzzle.

**Comment by jmcdo29** [comment]
I'd say you could provide a fourth, fallback as a `NoopService` which has whatever send method you're using but no implementation so it's essentially a forgotten call. Better would be to somehow buffer to messages to be sent when the provider is back online.

For further support, please use our [Discord](https://discord.gg/nestjs) as we are using GitHub for Bug Reports, Feature Requests, and Regressions.
