### ISSUE TITLE
[Question]: Does the FileInterceptor work with FastifyAdapter?

### ISSUE THREAD

**Issue by chanlito** [nestjs/nest#719]
If it doesn't, I think it should be mentioned somewhere in the documentation.

**Comment by kamilmysliwiec** [comment]
The `FileInterceptor` is based on the `multer` package which is incompatible with fastify. I'll mention it in the docs.

**Comment by kamilmysliwiec** [comment]
+ someday we'll support fastify either.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/issues/103

**Comment by huming2207** [comment]
Hi there,

Someone ported Multer for Fastify. I'm not sure if it works or not but maybe we should try it: https://github.com/fox1t/multer

Jackson
