### ISSUE TITLE
Allow APP_* providers to be module-scoped rather than global

### ISSUE THREAD

**Issue by KennyDurand** [nestjs/nest#7193]
## Is your feature request related to a problem? Please describe.
Right now, there seems to be no way to apply a Guard to a whole specific module without the Guard being applied to all other modules in the application.
When i do:
```
@Module({
  providers: [
    {
      provide: APP_GUARD,
      useClass: Module1Guard,
    },
  ]
})
export class Module1 {}

@Module({
  providers: [
    {
      provide: APP_GUARD,
      useClass: Module2Guard,
    },
  ]
})
export class Module2 {}

@Module({
  imports: [Module1, Module2]
})
export class MainModule {}
```

... both Module1Guard and Module2Guard are applied to all requests in MainModule.

Same thing seems to happen with APP_INTERCEPTOR, etc.

## Describe the solution you'd like
Something like this:
```
providers: [
    {
      provide: APP_GUARD,
      useClass: Module1Guard,
      global: false
    },
  ]
```

or: 
```
providers: [
    {
      provide: MODULE_GUARD,
      useClass: Module1Guard
    },
  ]
```

would be great!

**Comment by kamilmysliwiec** [comment]
This has been discussed in the past. `APP_*` providers are intended to be global and currently, we don't plan to add module-scoped enhancers. Thanks for the suggestion though!
