### ISSUE TITLE
Create Kafka consumer if necessary in microservice

### ISSUE THREAD

**Issue by lafeuil** [nestjs/nest#7194]
## Is your feature request related to a problem? Please describe.
When I use the microservice framework to only emit events with the Kafka client, a Kafka consumer is created while it is not necessary. In the Kafka server, a consumer group is created with some clients but without subscribed topics. The startup of application is slowed down because it must join a consumer group.   

## Describe the solution you'd like
In the [Kafka client](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-kafka.ts), a Kafka consumer is always created. I think it should only be created if there is a subscription with the `subscribeToResponseOf` function.  

## What is the motivation / use case for changing the behavior?
- Does not create a unnecessary consumer group 
- Improve the startup of application by avoiding to wait to join the consumer group

**Comment by kamilmysliwiec** [comment]
The philosophy of the built-in Kafka strategy is to create the consumer on the application bootstrap and there are no plans to change it. However, if your application requires slightly different setup, you can always create a custom strategy https://docs.nestjs.com/microservices/custom-transport
