### ISSUE TITLE
RabbitMQ microservice: @UseFilters(...) in Controller not catching malformed JSON message

### ISSUE THREAD

**Issue by obaqueiro** [nestjs/nest#7196]
## Current behavior
When using a vanilla RabbitMQ NestJS micro service, with a Controller  than handlers incoming messages, if a message with invalid JSON format is entered into the queue, the application crashes, even if using a custom @UseFilters(...) filter for that class

Full stack trace:

```
 /app/node_modules/@nestjs/microservices/server/server-rmq.js:77
   	   rawMessage = JSON.parse(content.toString());
   	                     ^

 SyntaxError: Unexpected token k in JSON at position 0
     at JSON.parse (<anonymous>)
     at ServerRMQ.handleMessage (/app/node_modules/@nestjs/microservices/server/server-rmq.js:77:25)
     at channel.consume.noAck.noAck (/app/node_modules/@nestjs/microservices/server/server-rmq.js:65:51)
     at ConfirmChannel.BaseChannel.dispatchMessage (/app/node_modules/amqplib/lib/channel.js:484:12)
     at ConfirmChannel.BaseChannel.handleDelivery (/app/node_modules/amqplib/lib/channel.js:493:15)
     at ConfirmChannel.emit (node:events:369:20)
     at /app/node_modules/amqplib/lib/channel.js:279:10
     at ConfirmChannel.content (/app/node_modules/amqplib/lib/channel.js:332:9)
     at ConfirmChannel.C.acceptMessageFrame (/app/node_modules/amqplib/lib/channel.js:247:31)
     at ConfirmChannel.C.accept (/app/node_modules/amqplib/lib/channel.js:400:17)
     at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:64:33)
     at Socket.go (/app/node_modules/amqplib/lib/connection.js:478:48)
     at Socket.emit (node:events:369:20)
     at emitReadable_ (node:internal/streams/readable:574:12)
     at processTicksAndRejections (node:internal/process/task_queues:80:21)


```
## Input Code
1. Create a vanilla RabbitMQ NestJS microservice project
2.  Add a Controller that will receive RabbitMQ messages  like:

```

@UseFilters(new AllExceptionsFilter())
@Controller('MessagesControllerr')
export class MessagesController {
...
}
```
All exceptions filter file (with a generic Catch() decorator to catch all exceptions:
```
import {  ExceptionFilter, Catch } from '@nestjs/common';
 
  @Catch()
  export class AllExceptionsFilter implements ExceptionFilter {
    catch(exception: unknown, ...args ) {
        console.group(exception)
        console.log(args)
    }
  }
```

3. Then start the application and send a message into the queue with some garbled text in the content (using RabbitMQ admin UI for example)

## Expected behavior
The thrown exception should be caught by the custom AllExceptionsFilter filter, it should print the expected data into the console and the application should not fail

## Possible Solution
Adding a try...catch clause in the `microservices/server/server-rmq.js ` file (`handleMessage` function) removes the assumption that is being made that the incoming message will be a valid JSON string

```
       const { content, properties } = message;
        let rawMessage;
      try {
           rawMessage = JSON.parse(content.toString());
       } catch (err) {
        rawMessage = {}
      }
       const packet = this.deserializer.deserialize(rawMessage);
```

## Environment

Nest version: 7.6.0

For Tooling issues:
- Node version: v15.14.0
- Platform:  Linux (alpine, within docker)

Others:

NA

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction.

**Comment by obaqueiro** [comment]
@jmcdo29 :  
https://github.com/obaqueiro/nest-json-error
This repo contains the whole project where the error can be reproduced.   Just use `npm i; npm start` and then send a message to the created queue in local rabbitmq instance

**Comment by obaqueiro** [comment]
For now we can live without a fix by using a wrapper for handleMessage. This si not a fix, but if someone is experiencing the same issue, it is a workaround:
```

handleMessageWrapper() {
    const originalFunction = ServerRMQ.prototype.handleMessage;
    ServerRMQ.prototype.handleMessage = async function (message, channel) {
      try {
        JSON.parse(message.content)
      } catch (err) {        
        message.content = JSON.stringify(message.content.toString())
      }
      return originalFunction.call(this,message, channel)
    }
  }
```

**Comment by kamilmysliwiec** [comment]
@obaqueiro would you like to create a PR to fix this issue?

**Comment by obaqueiro-primetrust** [comment]
@kamilmysliwiec  The problem is that I don't think the fix that I  can provide (as shown in the workaround on  [my previous comment](https://github.com/nestjs/nest/issues/7196#issuecomment-850531311) addresses the source of the problem.  As far as I can see, the problem is that a JSON.parse error is not being caught by an ExceptionFilter..  I have no idea how to fix that problem. 

The fix that I can provide would be to "fix" the symptom (when the JSON.parse() function fails, an exception is thrown), but I think that will only "hide" the underlying issue.

**Comment by obaqueiro** [comment]
@kamilmysliwiec The problem is that I don't think the fix that I can provide (as shown in the workaround on my previous comment addresses the source of the problem. As far as I can see, the problem is that a JSON.parse error is not being caught by an ExceptionFilter.. I have no idea how to fix that problem.

The fix that I can provide would be to "fix" the symptom (when the JSON.parse() function fails, an exception is thrown), but I think that will only "hide" the underlying issue.

**Comment by obaqueiro** [comment]
Since writing this I've done a _cleaner_ workaround by implementing a custom transport and adding the JSON validation as an override of the handleMessage method:

```
import { RmqOptions, ServerRMQ } from "@nestjs/microservices";

export class CustomServerRMQ extends ServerRMQ {
  constructor(protected readonly options: RmqOptions['options']) {
    super(options);
  }

  async handleMessage(message: Record<string,any>, channel:any) {
      try {
        JSON.parse(message.content);
      } catch (err) {
        message.content = JSON.stringify(message.content.toString());
      }
      return super.handleMessage(message, channel);
  }
}
```

This is cleaner than the monkey-patching I was doing before and solves the immediate problem (albeit not the underlying issue reported in this ticket).

Feel free to close this issue if you don't think it is worth investigating the main issue:  **exception in ServerRMQ.handleMessage() is not being caught by an ExceptionFilter**.

**Comment by zer0str0ng** [comment]
I would like to use your CustomServerRMQ suggestion, however not sure how to implement it, could you please provide an example?

I mean, how con you use it with your current NestFactory.createMicroservice.

**Comment by Macavity** [comment]
We are running currently into similar issues with wrongly empty messages.
@obaqueiro how do you tell NestJS to use that CustomServerRMQ instead of the default one?

**Comment by MahmudulHassan5809** [comment]
@obaqueiro  i am also facing this issue . where i need to use this class CustomServerRMQ? help please.
Thanks

**Comment by obaqueiro-primetrust** [comment]
Hey there,

We have it under the main.ts file, in the `app.connectMicroservice` function call under the `strategy` parameter.
It looks something like this:

```
  // This is the custom RabbitMQ provider
  import { CustomServerRMQ } from './providers/rabbitmq/rabbitmq.provider';

 ...
app.connectMicroservice<MicroserviceOptions>(
    {
      strategy: new **CustomServerRMQ**({
        urls: <string[]>[configService.get('RABBIT_MQ_CONNECTION_STRING')],
        queue: configService.get('RABBIT_MQ_QUEUE_NAME'),
        prefetchCount: prefetchCount,
        queueOptions: { [...]        },
      }),
    },
    { inheritAppConfig: true },
  );

  app.startAllMicroservices();
  app.listen(3003);
}

**Comment by MahmudulHassan5809** [comment]
@obaqueiro thanks

**Comment by delucca** [comment]
@kamilmysliwiec I was able to find a possible solution for this issue, but we need to discuss the following details:

1. Currently, we can't execute an `ExceptionFilter` from within the message handler. My idea is to create the ExceptionFilter object within the `listener-controllers` and add it alongside with `extras` within the message handler, them use it when the message is processed
2. In RabbitMQ we don't have access to the pattern **before** processing the message. How we're going to handle this? Even having the exception handlers properly created, how can we define which exception filters to execute? (given that we don't know the pattern)

**Comment by kamilmysliwiec** [comment]
Yeah, I don't think we can process that exception within the exception filters layer @delucca. I think the main objective is to avoid crashing the application if that error occurs (so basically handle it internally without populating it to further layers). In this case, the end-user won't be able to customize the behavior of the transporter but I think that's acceptable.

**Comment by delucca** [comment]
@kamilmysliwiec agreed :)

I'll think about something in that direction 😄 thanks!
