### ISSUE TITLE
assets not copied to dist folder

### ISSUE THREAD

**Issue by stijnvanderlaan** [nestjs/nest#7199]
## Bug Report
I try to copy template assets to the build dir, but nothing is copied.

## Current behavior
Nothing is copied to `dist/` when running `start:dev`.

## Input Code
This is my `nest-cli.json`:
```json
{
  "language": "ts",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": ["@nestjs/swagger"],
    "assets": ["mail/templates/**/*"],
    "watchAssets": true
  }
}

```

## Expected behavior
I expect the files to be present in the `dist/src/mail/templates/` folder.

## Environment
Nest version: 7.6.17
 
For Tooling issues:
- Node version: v14.16.0
- Platform:  Mac

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction. There are several resolved issues of this in [nestjs/nest-cli](https://github.com/nestjs/nest-cli)

**Comment by kamilmysliwiec** [comment]
As @jmcdo29 pointed out above, there are several resolved issues you can find in the `nestjs/nest-cli` repository. If you won't be able to find a solution there, please, create an issue with a minimum reproduction.

**Comment by stijnvanderlaan** [comment]
Found the problem, the command in my package.json was:
```
concurrently --handle-input \"wait-on dist/src/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\" 
```
Which needs to be:
```
nest start --watch
```
