### ISSUE TITLE
bug: "crbug/1173575" importing Res & Req decorator for controller file.

### ISSUE THREAD

**Issue by BaoPham92** [nestjs/nest#7201]
## Current behavior
Receiving error once adding either ```@Res``` or ```@Req``` to the arguments of the path function I would create for any part of the controller.

## Input Code
```
import { Controller, Get, Req, Res } from '@nestjs/common';

@Controller('suite')
export class SuiteController {
  @Get()
  async suiteAuth(@Req() req, @Res() res): Promise<any> {
    return {
      message: "server message, TBA."
    };
  }
}
```

## Expected behavior
To be able to detect a response and request object, whilst not breaking the app accessing the route that is passing Req or Res.

## Possible Solution
```
using the "createParamDecorator":
let { req, redis, res } = (await GqlExecutionContext.create( context,
).getContext())
```

is the current way I am getting the Response and Request object.

## Environment

<pre><code>
Nest version: ^7.5.1
 
For Tooling issues:
- Node version: v14.16.0
- Platform:  Big Sur 11.4

Others:

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
