### ISSUE TITLE
MQTT not receiving messages published from nest client 

### ISSUE THREAD

**Issue by marcoripa96** [nestjs/nest#7203]
## Bug Report
Messages sent from Nest client aren't received from the broker eventhough I'm currently subscribed to the topic. The broker correctly receive messages and broadcast them to all subscribers other than the Nest server.
If messages are sent from other clients (not from nest), the nest server receives those messages (on the same exact topic).

## Current behavior
I emit a message on a standard get route, the message is correctly sent to the broker and broadcasted to all subscribers other than the nest server (which is also a subscriber).

## Input Code
`AppController.ts`

```ts
@Controller()
export class AppController {
  constructor(private appService: AppService) {}

  @EventPattern('mri/#')
  getNotifications(data) {
    console.log(data);
  }


  @Get('/')
  test() {
    this.appService.sendMessage();
  }
}
```

`AppService.ts`
```ts
@Injectable()
export class AppService implements OnModuleInit {
  constructor(@Inject('MQ_CLIENT') private client: ClientProxy){
  }

  async onModuleInit() {
    console.log('connecting');
    await this.client.connect();
    console.log('connected');
  }

  sendMessage() {
    this.client.emit('mri/test', 'a message');
  }
}
```

## Expected behavior
The nest server should also receive the message sent with the client since it is a subscriber to the same topic of the message.

## Environment

<pre><code>
Nest version: 7.6.15
@nestjs/microservices version: 7.6.17

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
