### ISSUE TITLE
Issue #1184 persists - HttpModule can't resolve dependencies.

### ISSUE THREAD

**Issue by natejgardner** [nestjs/nest#7207]
## Current behavior

Issue #1184 has not yet been resolved. Simply importing `HttpModule` in a module results in the same error listed in that issue. A workaround is to call `register()` from the module import as in @E-Mwaurer 's response. However, this doesn't match the documentation.

## Input Code

```ts
import { HttpModule, Module } from '@nestjs/common';
import { MyController } from './my/my.controller';
import { MyService } from './my/my.service';
@Module({
  imports: [HttpModule],
  controllers: [MyController],
  providers: [MyService]
})
export class MyModule {}
```

## Expected behavior

The HttpModule import works when implemented as documented.

## Environment

<pre><code>
Nest version: 7.6.0

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by micalevisk** [comment]
I just test this with `7.6.0` (and with `7.6.15`) and didn't get any error.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
