### ISSUE TITLE
Non singleton modules

### ISSUE THREAD

**Issue by diabelb** [nestjs/nest#721]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on 
</code></pre>

## Current behavior

Hello,

Lets imagine we have module with simple provider and controller:

```
@Injectable()
export class CatsService {
 private cat: Cat;

 public setCat(cat: Cat) {
  this.cat = cat;
 }
 public getCat() {
  return this.cat;
 }
}
```
```

@Controller('cats')
export class CatsController {
  public constructor(private readonly catsService: CatsService) {}

  @Get()
  findAll() {
    this.catsService.setCat(someCat);
    return this.catsService.getCat();
  }

  @Get(:someParams)
  secondFindAll() {
    return this.catsService.getCat();
  }
}
```

When we run findAll() and after that secondFindAll() both returns someCat because of singleton even for independent customers on different computers. 

## Expected behavior

What are the best practics in similar situations? Creating factory of catsService? and what if we need non singleton module? Creating factory that uses NestFactory.createApplicationContext(ApplicationModule) is a good idea? Or it can cause performance issues? Unfortunately i can't find any help in documenation. I'll be happy to see some help ;)

**Comment by kamilmysliwiec** [comment]
What you are asking about is a request-scoped DI which is not available in Nest (new instance per incoming request, client). The best possible approach is creating a factory. `NestFactory.createApplicationContext(ApplicationModule)` may cause some performance issues, especially when the `ApplicationModule` is huge. We're looking forward to the [async-hooks](https://nodejs.org/api/async_hooks.html) feature which could help a bit, but it's still in the experimental stage.
