### ISSUE TITLE
Redundant links in docs

### ISSUE THREAD

**Issue by sourabhbagrecha** [nestjs/nest#7214]
## Current behavior

While going through the README file of this project, the first point in the [Getting Started](https://github.com/nestjs/nest#getting-started) list has the following behavior:
> - To check out the [guide](https://docs.nestjs.com/), visit [docs.nestjs.com.](https://docs.nestjs.com/) 📚

Please note that there are two links:
- One for "guide"
- Another one for "docs.nestjs.com"

## Expected behavior

While both links are pointing to the same resource, I guess it would be a lot better to have a single link unless we have a strong reason behind having them separately, because it may cause confusion to the newcomers while browsing through README.

## Possible Solution

Either point the "Guide" link to https://docs.nestjs.com/first-steps or some other getting-started/initial-setup resource or else remove the redundant link.

## Environment
GitHub README

**Comment by Tony133** [comment]
Hi @sourabhbagrecha, It could be an interesting change, but I think there is a reason why it was made.

However, if we look at the links written in Chinese, Korean, etc. the `guide` link points to` readme_jp.md` for example, so if we follow that guideline it should point to the repository's `Readme.md` file.

Let's see what Kamil thinks.

Tony
