### ISSUE TITLE
Testing multi tenant application. Main database containing tenants database

### ISSUE THREAD

**Issue by juanibe** [nestjs/nest#7216]
## Bug Report
The app has a multi tenant system. That means that from the main app we have access to the multiple tenants, each one with its database. For this we have a main database, which stores each of the tenants database information. (Host, port, etc...). 
For this we use middleware, custom providers and the Request Scope. 
So, depending on which tenant name we receive in the params, will be the connection we will establish. For example, 
`/tenant1/api.
`
This will connect to tenant1.
This connection is established dynamically through a Tenancy Module, where we look in the main database a Tenant that has that name and if found we make the connection to its database. Then in our services we consume the provider TENNANT_CONNECTION, and we connect to the corresponded database. 
We are using the Request.SCOPE in our services, so each request constructs this again and avoid using the singleton pattern. 

Our problem comes at the time of testing, we are getting that the connection was not found. 

## Current behavior
In tests getting
`   Received: undefined
`## Input Code

```ts
describe('UserService', () => {
  let service: UserService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [TenancyModule, Connection],
      providers: [UserService],
    }).compile();

    service = module.get<UserService>(UserService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined(); // Getting undefined
  });
});

```

## Expected behavior
Test the service that has in its constructor the TENNANT_CONNECTION.

## Possible Solution
I tried several things, like using Factory in Test.Module. and trying to inject the required dependencies.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: 14.15.1 
- Platform:  Mac / Linux

Repo with sample app:
https://github.com/victrsanchez/multitenant-api

To run the test =>  npm run test -- user.service.spec.ts
If you want to run the complete app with docker => docker-compose up.
In other case:
- npm install
- npm run start:dev

**Comment by kamilmysliwiec** [comment]
Check out this chapter https://docs.nestjs.com/fundamentals/testing, most importantly this section https://docs.nestjs.com/fundamentals/testing#testing-request-scoped-instances 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
