### ISSUE TITLE
gRPC server and client "package" option is mandatory

### ISSUE THREAD

**Issue by ericmorand** [nestjs/nest#7219]
## Current behavior

When instanciation a gRPC server or client, the `package` option is mandatory:

```ts
return NestFactory.createMicroservice<GrpcOptions>(ApplicationModule, {
    transport: Transport.GRPC,
    options: {
      package: '',
      protoPath: 'src/domain/index.proto',
      url: 'localhost:3000'
    }
  }).then((application) => {
    return application.listenAsync();
  });
```

But Protocol Buffers specification clearly establish that `package` is optional in `.proto` definitions.

https://developers.google.com/protocol-buffers/docs/overview#packages

> You can add an **optional** package specifier to a .proto file to prevent name clashes between protocol message types.

Current NestJS@7 behavior prevents using `.proto` files that doesn't come with a `package`.

It seems to be working with the server by passing an empty array as `package`, but doing the same with the client throws an error:

> Error: The invalid gRPC service (service not found)

It looks like the gRPC client, at least, doesn't support `.proto` definitions without `package`. And I suspect that the server doesn't support it either but I can't test it without a functioning client.

**Comment by Tony133** [comment]
Hi @ericmorand, I have created a pull that should solve this problem. 🤞

Tony

**Comment by kamilmysliwiec** [comment]
@Tony133 making this property optional will not fix the actual issue, see what @ericmorand mentioned above

> doing the same with the client throws an error

@ericmorand I can't recall myself what was the reason for making the `package` required in the first place. I'll take a look as soon as I can!

**Comment by ericmorand** [comment]
@Tony133 , I confirm that it won't work. I tried to hijack the definitions to solve the issue and it prevents both the server and the client to function.

@kamilmysliwiec , I suspected that it was due to the `grpc` library used, but I did not test that theory.

**Comment by Tony133** [comment]
I also confirm I have tried on a prototype that I had created and it does not work.
Too bad, I tried I thought in theory it was easier.

However it is strange because the interface requires a string even with the empty string which should actually go and instead does not go.
If I find out how it can be solved I'll let you know, I'm curious how to solve this problem.

**Comment by robtayl0r** [comment]
Isn't the package name required as the token to `@Inject(token)` the grpc service client into a constructor looking to interface with the service?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/8188

**Comment by kodmanyagha** [comment]
Same problem exist still. `package` property must be optional in `GrpcOptions` interface. Why we need this? Let me explain the situation. I'm compiling multiple proto files with `npx buf generate proto_folder` command. This is generating all types and constant values (for example service name with package). And we can implement multiple services in one nestjs project. And if we specify `package` property in `GrpcOptions` than we can't use these generated constant values in `GrpcMethod` annotation.
