### ISSUE TITLE
Nest CLI doesn't respect existing yarn workspaces

### ISSUE THREAD

**Issue by ShivamArora** [nestjs/nest#7224]
## Bug Report
Nest CLI doesn't respect existing yarn workspaces while generating the resources.

## Current behavior
When a resource is generated, Nest CLI adds `@nestjs/mapped-types` as a dependency to `package.json` and generates a `package-lock.json`.

## Input Code
None

## Expected behavior
Nest CLI should respect the existing yarn workspaces and instead of generating a `package-lock.json`, it should add the changes to `yarn.lock` at the workspace root.

## Possible Solution
I believe Nest CLI performs an install using `npm` instead of `yarn` which results in generation of `package-lock.json` since it previously doesn't exist.
If there's a way to tell the nest cli to use `yarn` instead of `npm` using the `nest-cli.json` or during the creation of the nest project, it might solve the problem.

## Environment

<pre><code>
Nest version: 7.6.0

 
For Tooling issues:
- Node version: 14.16.0
- Platform:  Mac

Others:

Package Manager: yarn
</code></pre>

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/nest-cli/issues/1115
