### ISSUE TITLE
Nest CLI adds dependency to mapped-types without specific version

### ISSUE THREAD

**Issue by ShivamArora** [nestjs/nest#7225]
## Current behavior
When generating your first resource in a nest project, nest cli adds a dependency to `@nestjs/mapped-types` but without specifying a version it uses `*` to use any version.

## Input Code
```
nest g resource cats
```

## Expected behavior
The dependency added for `mapped-types` must conform to a specific version range. e.g. `^0.4.0` as of now.

## Environment

<pre><code>
Nest version: ^7.6.0

 
For Tooling issues:
- Node version: 14.16.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
This is the expected behavior

**Comment by ShivamArora** [comment]
> This is the expected behavior

@kamilmysliwiec Any specific reason why this is the expected behavior? Version locking is always a preferred guideline.

**Comment by kamilmysliwiec** [comment]
Because it doesn't matter what version of this package should be installed by this schematic. Then you're in charge of adapting the version to what you want to use in your project.
