### ISSUE TITLE
Custom scalar bug

### ISSUE THREAD

**Issue by Kimblis** [nestjs/nest#7226]
## Current behavior
In code first approach if I create UUID custom scalar, it turns all my unspecified fields, or specified with `() => String` fields into UUID in schema...

## Expected behavior
It should let me specify in field that it's of type `() => UUID` without throwing me an error, or mutate all fields, however, if I specify `() => String` it should be string, not UUID

![3](https://user-images.githubusercontent.com/46688616/120596491-7f771000-c44c-11eb-9ced-0e729ca5b7e2.png)
![2](https://user-images.githubusercontent.com/46688616/120596492-80a83d00-c44c-11eb-96ab-7d20a183cd34.png)
![unknown](https://user-images.githubusercontent.com/46688616/120596493-80a83d00-c44c-11eb-9979-731ba8c35d08.png)

**Comment by calebpanza** [comment]
Hey @Kimblis how did you resolve this? I'm running into the exact same issue when creating a custom scalar for a Date.

**Comment by apss-pohl** [comment]
Hi,

i also have the same issue, why is this closed?
