### ISSUE TITLE
Multiple gateways with socket.io get (disconnect listeners added to [Socket])

### ISSUE THREAD

**Issue by aviadhadidainx** [nestjs/nest#7228]
## Current behavior
Using multiple gateway (Same socket io server).
When there a connection we get 'Possible EventEmitter memory leak detected. X disconnect listeners added to [Socket]'

It looks like for every gateway for every connection is subscribed to disconnect event(Also connect). Look on image below:

![image](https://user-images.githubusercontent.com/44137685/120615167-aa6b5f00-c460-11eb-9bc6-884a0c08f04e.png)
The file is ws-adapter.js

## Expected behavior
Not to get this warning or at least understand what can cause it and what is the risk

## Possible Solution
N/A

## Environment

<pre><code>
Nest version: 7.6.11

I also tried to update to latest but with no success
 
For Tooling issues:
- Node version: 12.16.3
- Platform:  Windows

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by aviadhadidainx** [comment]
#7287 https://github.com/nestjs/nest/issues/7287
