### ISSUE TITLE
What if I want to get multiple parameters directly in @Query()

### ISSUE THREAD

**Issue by yyqsc** [nestjs/nest#7233]
I see that I can get the value of key directly by @query('key'), but if I have multiple arguments, how do I pass this?

**Comment by micalevisk** [comment]
```ts
@Get()
async foo(@Query('key') key: string, @('another_param') anotherParam: string) {
}
// or
@Get()
async foo(@Query() params: MyParamsDto) {
   // params.key
   // params.another_param
}
```

**Comment by yyqsc** [comment]
> ```ts
> @Get()
> async foo(@Query('key') key: string, @('another_param') anotherParam: string) {
> }
> // or
> @Get()
> async foo(@Query() params: MyParamsDto) {
>    // params.key
>    // params.another_param
> }
> ```

Thanks very much !!!

**Comment by Tony133** [comment]
Hi @yyqsc, if you are having difficulty with Nest and want to ask questions, I suggest you use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

Nest's core team uses GitHub to track Bug Reports, Feature Requests, and Regressions.

Tony
