### ISSUE TITLE
Standardising the name convention for controllers message handlers  with @MessagePattern In Microservice Context

### ISSUE THREAD

**Issue by manjufy** [nestjs/nest#7235]
## Is your feature request related to a problem? Please describe.
I'm still quite new to NestJS, please bear with me if there is already an existing solution to the problem I'm describing.

Let's consider the following services
- A Gateway service (HTTP) based talks to a couple of microservices
- A Microservice (TCP)

In A Microservice, I have a couple of controllers Ex
```
// Foo Controller
import { Controller } from '@nestjs/common';
import { MessagePattern } from '@nestjs/microservices';

@Controller()
export class FooController {
  @MessagePattern('get_foo')
  foo(data: string): string {
    return 'foo'
  }
}

// Bar Controller
import { Controller } from '@nestjs/common';
import { MessagePattern } from '@nestjs/microservices';

@Controller()
export class BarController {
  @MessagePattern('get_bar')
  foo(data: string): string {
    return 'bar'
  }
}
```

API Gateway connects the above microservice in the following manner

```
@Controller()
export class AppController {
    constructor(
    @Inject('FOO_BAR_SERVICE')
    private fooBarServiceClient: ClientProxy,
  ) {}

  @Get('/foo)
  async foo(): Promise<string> {
        const foo = await this.fooBarServiceClient
          .send('get_foo', 'test')
          .toPromise();

    return foo;
  }

  @Get('/bar')
  async users(): Promise<any> {
          const foo = await this.fooBarServiceClient
          .send('get_bar', 'test')
          .toPromise();

    return bar;
  }
}
```

In the Gateway / Client who is consuming the microservice is not aware of the controller's structure or the structure of the message pattern. i.e. in microservice, we could have conflicting `@MessagePattern('name')` / Colliding @MessagePattern names.
Ex: In the above-mentioned Microservice I could have another controller with same @MessagePattern('get_foo')
```
// Zen Controller
import { Controller } from '@nestjs/common';
import { MessagePattern } from '@nestjs/microservices';

@Controller()
export class ZenController {
  @MessagePattern('get_foo') // we have the same name in FooController already
  foo(data: string): string {
    return 'bar'
  }
}
```

Is there a way to correctly name the message patterns based on the controller names and not having to have conflicting names across the service?

## Describe the solution you'd like

We can identify the message pattern names prefixed with controller name
Ex: `controllerName:pattern_name` => `foo:get_foo`

```
// Foo Controller
import { Controller } from '@nestjs/common';
import { MessagePattern } from '@nestjs/microservices';

@Controller()
export class FooController {
  @MessagePattern('get_foo')
  foo(data: string): string {
    return 'foo'
  }
}

// Bar Controller
import { Controller } from '@nestjs/common';
import { MessagePattern } from '@nestjs/microservices';

@Controller()
export class BarController {
  @MessagePattern('get_bar')
  foo(data: string): string {
    return 'bar'
  }
}
```

Client / Gateway

```
@Controller()
export class AppController {
    constructor(
    @Inject('FOO_BAR_SERVICE')
    private fooBarServiceClient: ClientProxy,
  ) {}

  @Get('/foo)
  async foo(): Promise<string> {
        const foo = await this.fooBarServiceClient
          .send('foo:get_foo', 'test')
          .toPromise();

    return foo;
  }

  @Get('/bar')
  async users(): Promise<any> {
          const foo = await this.fooBarServiceClient
          .send('bar:get_bar', 'test')
          .toPromise();

    return bar;
  }
}
```

## What is the motivation/use case for changing the behavior?

A microservice with quite a number of controllers makes it hard to name the message handlers with names that might collide with message handlers from other controllers.

It would be easier for developers to identify the message handler names If we could design message handlers that would follow certain structures or standards to identify them in the microservices context.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
