### ISSUE TITLE
ModuleRef probably not respecting { strict: false }

### ISSUE THREAD

**Issue by flisboac** [nestjs/nest#7239]
I've been implementing a custom service that makes use of `ModuleRef.resolve`.

I would expect `ModuleRef.resolve` to be able to resolve any provider, in any of the modules (including outside its own module, i.e. anywhere in the global context, [as per the documentation](https://docs.nestjs.com/fundamentals/module-ref#retrieving-instances)), when strict mode is explicitly disabled.

Unfortunately, this seems to work only for `Scope.TRANSIENT` providers. If you configure your provider in any other way, and if said target provider is exported in another module, the ModuleRef resolver mechanism will fall into the conditional highlighted below:

https://github.com/nestjs/nest/blob/99ee3fd99341bcddfa408d1604050a9571b19bc9/packages/core/injector/module-ref.ts#L82-L85

As you can see, it doesn't seem like the options are being passed along with the token to look up, and NestJS understandably cannot find the provider, because 1. `ModuleRef.resolve` is running in strict mode at that point; and 2. the provider being looked up is in another module.

Is that right, or am I overseeing/misinterpreting something about the resolution mechanism?

**Comment by kamilmysliwiec** [comment]
Great catch! Would you like to create a PR for this issue? We should pass the `options` object down to the `get()` method.

**Comment by flisboac** [comment]
@kamilmysliwiec sure thing! Right now I don't have free time in my hands, but that won't be for long, though.

I will try to write the fix by tomorrow.

**Comment by kamilmysliwiec** [comment]
Fixed in this commit https://github.com/nestjs/nest/commit/26720034a8e57b62ccc646cc7243ca0ddfd1b874 will be released very shortly
