### ISSUE TITLE
How to send/emit/publish MQTT messages with Qos2 and retain?

### ISSUE THREAD

**Issue by sshhawwnn** [nestjs/nest#7240]
Currently the emit function only accepts two parameters.
`this.clientMqtt.emit('Webservice', _body.payload);`

How can we set the options while publishing a new message?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
