### ISSUE TITLE
The ability of calling auth guard once per request for graphQL 

### ISSUE THREAD

**Issue by fedeoo** [nestjs/nest#7241]
## Is your feature request related to a problem? Please describe.

I have a GraphQL application based with `nest.js` and I notice that auth guard is called multiple times for a single request. 
What I expected is triggering auth guard on the endpoint. I can find similar requirement on StackOverflow and workaround solutions. Just wondering if we can provide a built-in approach for this. Thanks!
https://stackoverflow.com/questions/51944801/nest-js-use-authguard-as-middleware-for-graphql
https://stackoverflow.com/questions/60148630/nestjs-authguard-validation-per-request

## Describe the solution you'd like

Probably adding a new flag to GraphQL Module options. If true, then we just call the global guard once per request.
By default, it won't have impact on existing behaviour.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by jmcdo29** [comment]
@kamilmysliwiec this is a feature request, and I could've sworn I've seen this request before but I can't seem to find it. 

I believe the request is a limitation of how GQL requests work, but I could be wrong on that

**Comment by kamilmysliwiec** [comment]
@jmcdo29 you can already execute auth guard once per query/mutation (that's what happens by default). If you group multiple queries in a single HTTP request that spans N queries though, auth guard will be executed N times and this is just a limitation of how GQL & Nest work.
