### ISSUE TITLE
@nestjs/core: vinyl-fs types are being referenced in core/router/sse-stream.d.ts

### ISSUE THREAD

**Issue by jonseitz** [nestjs/nest#7247]
## Current behavior

With `@nestjs/core@v17.6.7` installed in a project, `tsc` is failing with the following error:

```
node_modules/@nestjs/core/router/sse-stream.d.ts:2:23 - error TS2688: Cannot find type definition file for 'vinyl-fs'.

2 /// <reference types="vinyl-fs" />
```

`@types/vinyl-fs` isn't listed among the dependencies of `@nestjs/core`, nor is `@types gulp` , which depends on it in turn.

## Expected behavior

All of the necessary dependencies of `@nestjs/core` should be installed with it.

## Possible Solution

The issue seems to be that `@types/vinyl-fs` contains [an ambient declaration of the `NodeJS.WritableStream`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vinyl-fs/index.d.ts#L10-L16) interface that's used in `core/router/sse-stream.ts`:

```ts
declare global {
    namespace NodeJS {
        interface WritableStream {
            write(buffer: any/* Vinyl.File */, cb?: (err?: Error | null) =&gt; void): boolean;
        }
    }
}
```

That interface is presumably being pulled in by the `gulp` build process and causing the reference to appear here. I think you could resolve this by adding `"types": ["node"]` under `compilerOptions` in `packages/tsconfig.base.json`. At a quick glance I'm not seeing any other `@types` packages that need to be included globally, though I haven't done any testing to confirm this.

I'm happy to test further and submit a PR if that's appropriate here.

## Environment

<pre><code>
Nest version: 7.6.17 
 
For Tooling issues:
- Node version: 14.16.0  
- Platform:  Arch Linux 
</code></pre>

**Comment by jmcdo29** [comment]
I'm not able to replicate this build error. But I do see the reference you're talking about in my local install of `@nestjs/core`. Not sure how that got there in the first place. Thanks for bringing this to our attention. Would you like to create a PR for it?

**Comment by jonseitz** [comment]
@jmcdo29 Sure, I'll put together a PR and get it submitted.

It only started happening in my build recently as I've been updating dependencies, but I did get the error both in local development and in CI, so it may be some combination of package/tool versions unique to our setup.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/7253
