### ISSUE TITLE
Is it OK to override to override handleEvent method when we build custom Transporter

### ISSUE THREAD

**Issue by dtuyenle** [nestjs/nest#7254]
We building a custom transporter that extend Server class (https://docs.nestjs.com/microservices/custom-transport)

For some reason we need to do some custom code for handleEvent. So my question is 

Is it OK to override the handleEvent method here :

https://github.com/nestjs/nest/blob/99ee3fd99341bcddfa408d1604050a9571b19bc9/packages/microservices/server/server.ts#L93

With something like below:

```


    const handler = this.getHandlerByPattern(pattern);
    if (!handler) {
      return this.logger.error(`${NO_EVENT_HANDLER} Event pattern: ${JSON.stringify(pattern)}.`);
    }
    const resultOrStream = await handler(packet.data, context);
    if (resultOrStream && typeof resultOrStream.subscribe === 'function') {
      await resultOrStream.toPromise();
    }
    return resultOrStream;
```

**Comment by kamilmysliwiec** [comment]
> Is it OK to override the handleEvent method here :

Overriding `handleEvent`/`handleMessage` is completely fine, but I can't verify if your exact implementation is correct because it depends on many other factors (context, the rest of the transport strategy code etc)
