### ISSUE TITLE
Explicit Conversion should to allow default value

### ISSUE THREAD

**Issue by kuriel-trivu** [nestjs/nest#7257]
## Bug Report
About: https://docs.nestjs.com/techniques/validation#explicit-conversion

But what about if we want to pass a default param value? like: `page = 1` 
This means that as method param: "if value is not provided, we can use the default one".

## Current behavior

With this implementation (see Input Code), the backend responds with: 
`Validation failed (numeric string is expected)`

## Input Code

```ts
findOne(
  // if client does not provide a page, we start with the first one (1).
  @Param('page', ParseIntPipe) page: number = 1, 
) 
```

## Expected behavior

With `page = 1` as method param, we refer to "if value is not provided, we can use the default one".

## Possible Solution

Today we have to build a custom ParseIntPipe to return 1 if value is undefined.

## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: v12.18.3 
- Platform:  Windows

**Comment by micalevisk** [comment]
see https://docs.nestjs.com/pipes#providing-defaults

**Comment by Tony133** [comment]
Hi @kuriel-trivu, if you are having difficulty with Nest and want to ask questions, I suggest you use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

Nest's core team uses GitHub to track Bug Reports, Feature Requests, and Regressions.

Tony

**Comment by kuriel-trivu** [comment]
@micalevisk  as i can see, that [Providing Defaults](https://docs.nestjs.com/pipes#providing-defaults) is a workarround because for some reason nest can't catch the default value from method params, because the natural flow of coding should to be the provided in this issue.

@Tony133  is not a question, thanks.

It's a bug or improvement for nestjs to code intuitively, but obviously we can use the workarround...

**Comment by Tony133** [comment]
Hi @kuriel-trivu,  If you think this is a bug, create a minimal production in a clonable git so that the base team at the nest can evaluate the problem.
While if you feel it could be an improvement for NestJS, pull requests for Nest's core team are always welcome.

Tony

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/pipes#providing-defaults
