### ISSUE TITLE
OpenAPI generation not working with automatic constructor parameters

### ISSUE THREAD

**Issue by programmatix** [nestjs/nest#7258]
Given this code

```
export class Test {
    foo: number;

    constructor(public bar: number) {
    }
}
```

in test.entity.dto, I'd expect the OpenAPI generated from the plugin to include both `foo` and `bar`.  However, it only includes `foo`:

```
      "Test": {
        "type": "object",
        "properties": {
          "foo": {
            "type": "number"
          }
        },
        "required": [
          "foo"
        ]
      },
```

Is it possible to make `bar` work?  This is the way I prefer to write TS classes, as it saves having to declare variables both in the constructor parameters, and as class fields.

Nest versions:

```
    "@nestjs/common": "^7.5.1",
    "@nestjs/config": "^0.6.3",
    "@nestjs/core": "^7.5.1",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/swagger": "^4.8.0",
    "@nestjs/typeorm": "^7.1.5",
```

**Comment by kamilmysliwiec** [comment]
Currently there's no way to do this out-of-the-box and we don't plan to support this feature in the foreseeable future.
