### ISSUE TITLE
Nestjs Kafka client using ClientsModule is always trying to join to consumer group even if only publish is needed

### ISSUE THREAD

**Issue by jlortega-ayala** [nestjs/nest#7259]
## Bug Report

We are developing an artefact using Nestjs and kafka who is triggered by a http request and must publish a message to a kafka topic. We tried to implement ClientsModule to instanciate a Kakfa client, but it is always trying to join to a consumer group (we don't need consume anything, just publish messages). Looking into nestjs microservices client code (https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-kafka.ts) we found that a nestjs kafka client is always implementing a consumer even if we only need to publish and didn't send consumer params in ClientsModule.register method. There is any reason about this? Thanks in advance!

## Current behavior

We are geeting this logs when did not send kafka consumer params:
```
[Nest] 33072   - 13-06-2021 12:56:08   [ClientKafka] INFO [Consumer] Starting {"timestamp":"2021-06-13T16:56:08.247Z","logger":"kafkajs","groupId":"nestjs-group-group"}
[Nest] 33072   - 13-06-2021 12:56:09   [ClientKafka] ERROR [Connection] Response GroupCoordinator(key: 10, version: 2) {"timestamp":"2021-06-13T16:56:09.646Z","logger":"kafkajs","broker":"xxxxxxxxx","clientId":"xxxxxxx","error":"Not authorized to access group: Group authorization failed","correlationId":2,"size":49} +1398ms
[Nest] 33072   - 13-06-2021 12:56:18   [ClientKafka] INFO [Consumer] Stopped {"timestamp":"2021-06-13T16:56:18.188Z","logger":"kafkajs","groupId":"nestjs-group-group"}
[Nest] 33072   - 13-06-2021 12:56:18   [NestApplication] Nest application successfully started +4ms
```

We are getting this logs when we sent consumer params with a groupId (This way is producing more logs that we expected because the consumer is always re-joining the consumer-group, from our point of view it is unnecessary):
```
[Nest] 4344   - 13-06-2021 13:00:09   [ClientKafka] INFO [Consumer] Starting {"timestamp":"2021-06-13T17:00:09.229Z","logger":"kafkajs","groupId":"xxxxxxxx"}
[Nest] 4344   - 13-06-2021 13:00:13   [ClientKafka] INFO [ConsumerGroup] Consumer has joined the group {"timestamp":"2021-06-13T17:00:13.621Z","logger":"kafkajs","groupId":"xxxxxxxx","memberId":"xxxxxxxxxx-64d18fdb-e00b-451a-84ed-7becf4b07fe5","leaderId":xxxxxxxxx-97f0ede3-0852-47cf-8612-5eaf371dbd64","isLeader":false,"memberAssignment":{},"groupProtocol":"NestReplyPartitionAssigner","duration":4134}
[Nest] 4344   - 13-06-2021 13:00:13   [NestApplication] Nest application successfully started +4ms

```

## Input Code
```
const getConfig = (): KafkaConfig => {
  if (process.env.NODE_ENV !== 'local') {
    return {
      clientId: process.env.KAFKA_CLIENT_ID,
      brokers: [process.env.KAFKA_BROKER],
      ssl: true,
      sasl: {
        mechanism: 'plain',
        username: process.env.KAFKA_USERNAME,
        password: process.env.KAFKA_PASSWORD
      }
    }
  }
  return {
    clientId: process.env.KAFKA_CLIENT_ID,
    brokers: [process.env.KAFKA_BROKER]
  }
}

@Module({
  imports: [HttpModule, ConfigModule.forRoot({ isGlobal: true}), 
    ClientsModule.register([
    {
      name: 'KAFKA_SERVICE',
      transport: Transport.KAFKA,
      options: {
          client: getConfig(),
          postfixId: process.env.KAFKA_POSTFIXID
      }        
    }
  ])],
  controllers: [AppController, HealthController],
  providers: [AppService, ProducerService]
})
export class AppModule {}
```

## Expected behavior

We expect that by not sending the "consumer" parameter when trying to generate the kafka client using ClientModule.register(), it  does not try to consume anything since it only requires publishing a message and no message consumption is required.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
`ClientsModule` is exposed to provide a simple way to interact with Kafka (and other) Nest-based microservices. For example, in your case, the Kafka client tries to join the consumer group to properly support message-based communication (which is one supported by Nest out of the box). If you want to simply publish messages/events to Kafka and you don't require anything else (any abstraction on top of that), you should rather integrate Nest with Kafkajs directly. **If you want to use Kafka with Nest, using `@nestjs/microservices` package (and so the `ClientsModule`) is not _required_.**
