### ISSUE TITLE
WebSocket Gateway add listener

### ISSUE THREAD

**Issue by franz-geiser** [nestjs/nest#7262]
I'm trying to add a ws listener from a service.
`console.log('Adding listener');`
`await this.DevicesGateway.server.on('hello', () => {`
`          console.log('hello');`
`        });`

When i send the ws message from the client, the nestjs server does not fire the event.
In the server console i get
`Adding listener`
`  socket.io-parser decoded 2["hello"] as {"type":2,"nsp":"/","data":["hello"]} +3ms`
`  socket.io:socket got packet {"type":2,"nsp":"/","data":["hello"]} +7s`
`  socket.io:socket emitting event ["hello"] +1ms`
`  socket.io:socket dispatching an event ["hello"] +0ms`
`[Nest] 272277   - 2021-06-15 9:47:00   [LoggingPlugin] New Request +3497ms`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
