### ISSUE TITLE
Where to get both of the extracted parameters of controller handler and execution context at the same time before handler?

### ISSUE THREAD

**Issue by cnwangjie** [nestjs/nest#7264]
I've read the request lifecycle doc (https://docs.nestjs.com/faq/request-lifecycle#summary) It seems pipes is the last place before the route handler. I hope an aspect that I can get both of the extracted parameters of controller handler and execution context at the same time. 

In my case, I want to build an authorization module as a decorator. It needs to authorize the request with a specified resource. I hope to get it in parameter so that I can reuse the intercepter and pipes. And I also need to get some general data in the context (e.g user info).

Is it possible or need to enhance the framework?

**Comment by jmcdo29** [comment]
I'm not sure I really understand what's being asked for here. Something like you want a decorator, say, `@Authentication()` to be able to do all of your auth needs as part of a route handler's parameter decorators? I'm not sure if this makes much sense. 

In any case, for more support you should use our [Discord](https://discord.gg/nestjs) channel. We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by cnwangjie** [comment]
@jmcdo29 Hi,

Sorry for taking a question here. The Discord is a bit noisy. And it may be a feature request.

Let me show my case in more detail.

Guess we have a route named `/item/:id` like this. Before handling the request I need to check if the user has permission to access this item.

```ts
@Controller('item')
class ItemController {

  @Get(':id')
  @Authorize(ReadScope)
  async getItem(@Param('id', ParseIntPipe) id: number) {
    // ...
  }
}
```

And I need to get the id from param. I want to reuse the parameter pipe because maybe I will need to parse the parameter, although I can get it from context again. And I need to get the request context because I need to get the user info in checks, but I don't need it in the handler so I don't want to add it in arguments.

Here is something similar with what I want.

```ts
const Authorize = (scope: string): PropertyDecorator => {
  return (target, property) => {
    const handler = Reflect.get(target, property);
    const wrappedHandler = async (...args: any[]) => {
      // get user info from context
      // do authorize here with args
      return handler(...args);
    };
    return wrappedHandler;
  };
};
```

In my case, I actually need a place in AOP that between parameter pipes and the route handler method so that I can get the final parameters extracted from the request in a middle layer.

I like the abstraction in Nest very much, such as Guards and Interceptors. But the framework does too much and also has some limits. Is it currently possible to do something like the above by the framework?

Looking forward to your reply and hope to reopen this issue.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements. Your use-case is covered by the existing features.
