### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by royibernthal** [nestjs/nest#7265]
Are there any benchmarks available for nest?

For instance, it'd be great to see how it compares to plain Express, Fastify, Hapi, etc.
I imagine it'd be slower since it adds more logic and abstraction on top of these, but I'm curious to see to what extent.

**Comment by jmcdo29** [comment]
[This is the most recent benchmarks file written](https://github.com/nestjs/nest/blob/master/benchmarks/all_output.txt) which works between express, fastify, nest-express, and nest-fastify. Benchmarks are currently being ran during our CI as well, but codechecks currently doesn't expose that outcome publicly other than just "benchmarks run fine"

**Comment by royibernthal** [comment]
Got it, thanks :)
