### ISSUE TITLE
Circular dependency error

### ISSUE THREAD

**Issue by serendipity1004** [nestjs/nest#7266]
I have three modules that are depending on each other.

Post -> Answer -> Comment

PostModule is exporting PostService,
AnswerModule is exporting AnswerService,
CommentModule is exporting CommentService.

Now PostModule needs to import AnswerModule,
AnswerModule needs to import both PostModule and CommentModule,
CommentModule is importing AnswerModule.

As documented in the official website, I have imported the modules using forwardRef.

PostModule
```
@Module({
  imports: [
    TypeOrmModule.forFeature([Post]),
    forwardRef(() => AnswerModule),
    PaginationModule,
  ],
  controllers: [PostController],
  providers: [PostService],
  exports: [PostService],
})
export class PostModule {}
```

AnswerModule
```
@Module({
  imports: [
    TypeOrmModule.forFeature([Answer]),
    PaginationModule,
    forwardRef(() => PostModule),
    forwardRef(() => CommentModule),
  ],
  controllers: [AnswerController],
  providers: [AnswerService],
  exports: [AnswerService],
})
export class AnswerModule {}
```

CommentModule
```
@Module({
  imports: [
    TypeOrmModule.forFeature([Comment]),
    PaginationModule,
    forwardRef(() => Answer),
  ],
  controllers: [CommentController],
  providers: [CommentService],
  exports: [CommentService],
})
export class CommentModule {}
```

The problem is that I cannot use AnswerService in CommentService even after importing AnswerModule.

I've solved the problem by changing the constructor of CommentService from

```
  constructor(
    @InjectRepository(Comment)
    private repository: Repository<Comment>,
    private postAnswerService: PostAnswerService,
  ) {}
```

to

```
  constructor(
    @InjectRepository(Comment)
    private repository: Repository<Comment>,
    @Inject(forwardRef(() => AnswerService))
    private postAnswerService: AnswerService,
  ) {}
```

but I want to know the logic behind the need for extra forwardRef in the service when I am clearly importing the module using the forwardRef already.

**Comment by jmcdo29** [comment]
`forwardRef`s are required for **both** modules and providers. Nest normally uses reflected type metadata to know what to inject, but when there is a circular reference, typescript no longer reflects the metadata properly. By using `forwardRef` we make this loading and reading of the other class lazy, so that we can properly let typescript resolve what it needs to. Then, we can later read this metadata and inject the instance as expected.
