### ISSUE TITLE
Query params aren't behave the same when using platform/fastify

### ISSUE THREAD

**Issue by mandaputtra** [nestjs/nest#7276]
## Bug Report

I had a habit when making search filter on an HTTP API I always use this kind of pattern `?page=1&limit=10&filter[name]=jhon&filter[age]=10` so I'll get response like this :

```json
{
  "page": "1",
  "limit": "10",
  "filter": {
    "name": "jhon",
    "age": "10"
  }
}
``` 

With response like this, you can validate the filter that the user can use more easily. It already works using the default express platform, but on Fastify adapter the behavior changed.

## Current behavior

Using Fastify adapter, the JSON returned like this

```json
{
  "page": "1",
  "limit": "10",
  "filter[name]": "jhon",
  "filter[age]": "10"
}
``` 

## Input Code

Check the repo [here](https://gitlab.com/mandaputtra/nest-issue-query-params)

Test with curl

```bash
$ curl --location -g --request GET 'localhost:3000?page=1&limit=10&filter[name]=jhon&filter[age]=10'
```

## Expected behavior

When using Fastify adapter, the JSON query params returned should be the same as the default adapter.

## Possible Solution

Didn't look at the platform/fastify code yet.

## Environment

```json
    "@nestjs/common": "^7.6.15",
    "@nestjs/core": "^7.6.15",
    "@nestjs/platform-express": "^7.6.15",
    "@nestjs/platform-fastify": "^7.6.18",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.6"
```

- Node version: 12.x
- Platform:  Linux

Others:

</code></pre>

I would love to make a pull request, to fix this. Just tell me where to start. Thanks! Love this framework!

**Comment by kamilmysliwiec** [comment]
This is the default behavior of fastify. You can specify your own `querystring` using this configuration parameter https://www.fastify.io/docs/latest/Server/#querystringparser

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
