### ISSUE TITLE
Allow ClassSerializerInterceptor to transform plain objects

### ISSUE THREAD

**Issue by Aareksio** [nestjs/nest#7281]
## Is your feature request related to a problem? Please describe.
I want to return objects with multiple class properties in my app
```ts
interface Response { 
	status: ServiceStatus,
    endpoints: ServiceEndpoint[]
}
```

## Describe the solution you'd like
Allow ClassSerializerInterceptor to serialize plain objects using `classToPlain` method (<https://github.com/typestack/class-transformer#classtoplain>). Current limitation was coded 3 years ago here: https://github.com/nestjs/nest/blame/master/packages/common/serializer/class-serializer.interceptor.ts#L69.

From my experience, class-transformer's `classToPlain` works seamlessly with such objects, perhaps the limitation is not required anymore?

## Teachability, Documentation, Adoption, Migration Strategy
Removing the limitation (`plainOrClass.constructor !== Object`) may introduce bugs in applications which relied on `ClassSerializerInterceptor` **not** transforming plain objects. Perhaps this could be implemented as a constructor option.

The change can be tested by replacing existing `ClassSerializerInterceptor` with the following extension:
```ts
import { ClassSerializerInterceptor as ClassSerializerInterceptorBase, PlainLiteralObject } from '@nestjs/common';
import { classToPlain, ClassTransformOptions } from 'class-transformer';

export class ClassSerializerInterceptor extends ClassSerializerInterceptorBase {
  serialize(
    response: PlainLiteralObject | Array<PlainLiteralObject>,
    options: ClassTransformOptions,
  ): PlainLiteralObject | PlainLiteralObject[] {
    return classToPlain(response, options);
  }
}
```

The extension drops all `constructor !== Object`, `isObject` and `isArray` checks, letting `class-transformer` decide what to do with the response object. My guess is over the last 3 years `class-transformer` adopted it's own ways of dealing with non-class values, thus there is no need to code additional checks outside the lib.

## What is the motivation / use case for changing the behavior?
I failed to find the reason constructor check is required for `classToPlain` to work. Migrating from `routing-controllers`, I found it strange returning `{ user }` or similar structure from the controller does not properly sarialize the class instance. This may lead to unknowingly exposing properties marked with `@Exclude()` or `@Expose({ groups: ['staff'] })`.

**Comment by jmcdo29** [comment]
I've made a [small demo here](https://stackblitz.com/edit/typescript-4afjsv?file=index.ts) with just `class-transformer` to show that it does indeed work on objects with class properties.

@kamilmysliwiec unless you have any objections, I think this could be a useful change. Is there anything we should be worried about with this?

**Comment by kamilmysliwiec** [comment]
@jmcdo29 I think we had this check just to avoid calling `classToPlain` in case we knew it won't perform any transformations (and that was the case for literal JS objects in the past) = performance++. However, since it sounds that the `class-transformer` handles such scenarios now, we should probably remove that condition. 

@Aareksio Would you be willing to create a PR to address this issue?
