### ISSUE TITLE
LevelUp Integration

### ISSUE THREAD

**Issue by thachp** [nestjs/nest#7282]
## Feature Request
Similar to how there is a module for Bull and MongoDB.  There should be one for Levelup  (https://github.com/Level/levelup)

## Is your feature request related to a problem? Please describe.
Levelup is a wrapper class for Leveldown, which provides a C++ interface layer for LevelDB.   

## Describe the solution you'd like
A  @nestjs/Levelup Module with an injectable service class to invoke Level-up operations (put, get. delete, etc...). 

The injectable classes should work with the CQRS module, specifically when injecting the service into a CommandHandler

## Teachability, Documentation, Adoption, Migration Strategy
https://leveljs.org/
https://r.va.gg/presentations/nodejsdub/#/
http://highscalability.com/blog/2011/8/10/leveldb-fast-and-lightweight-keyvalue-database-from-the-auth.html

Bitcoin, Ethereum uses LevelDB.

## What is the motivation/use case for changing the behavior?
In most cases, MongoDb / Mariadb is sufficient.. this request is for the 2% problems where it is necessary to work with large datasets.

**Comment by jmcdo29** [comment]
Please refer to [this comment](https://github.com/nestjs/nest/issues/5388#issuecomment-777457372) and [this comment](https://github.com/nestjs/nest/issues/4007#issuecomment-582779510) in regards to new database and other integration modules.
