### ISSUE TITLE
Multiple gateways with socket.io get (disconnect listeners added to [Socket])

### ISSUE THREAD

**Issue by aviadhadidainx** [nestjs/nest#7287]
Bug Report
Current behavior
Using multiple gateway (Same socket io server).
When there a connection we get 'Possible EventEmitter memory leak detected. X disconnect listeners added to [Socket]'

It looks like for every gateway for every connection is subscribed to disconnect event(Also connect). Look on image below:
![image](https://user-images.githubusercontent.com/44137685/122873626-aa150400-d33a-11eb-84b7-48e948294fc7.png)

image
The file is ws-adapter.js

Expected behavior
Not to get this warning or at least understand what can cause it and what is the risk

Possible Solution
N/A

Environment

Nest version: 7.6.11

I also tried to update to latest but with no success
 
For Tooling issues:
- Node version: 12.16.3
- Platform:  Windows

Attached example project that reproduce this issue.
When you start the project you can see the warning on logs.. 

[https://github.com/nestjs/nest/issues/7228](url)

**Comment by aviadhadidainx** [comment]
[16-gateways-ws.zip](https://github.com/nestjs/nest/files/6691510/16-gateways-ws.zip)
Example with reproudction project is attached.. I just took the Gateway example and added 10 more gateways

**Comment by jmcdo29** [comment]
Is this related to #7249?

**Comment by aviadhadidainx** [comment]
Looks like it is related.. But not 100% sure

**Comment by kamilmysliwiec** [comment]
Can you please provide a minimum reproduction repository (and make it available through Github)?

**Comment by aviadhadidainx** [comment]
https://github.com/aviadhadidainx/nestjs-ws-bug

**Comment by aviadhadidainx** [comment]
@kamilmysliwiec I updated the issue 13 days ago with repo and project that reproduce.
I think you missed it because now i guess this is enough for clarification. Correct? If no let me know and i will add what you need

**Comment by aviadhadidainx** [comment]
@kamilmysliwiec  Any updates? Maybe this issue needs another label?

**Comment by genadis** [comment]
I believe it is related to: https://github.com/nestjs/nest/issues/6026#issuecomment-881339664

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/7249
