### ISSUE TITLE
Add option to pass raw packet to custom microservice de/serializers

### ISSUE THREAD

**Issue by Dallin343** [nestjs/nest#7288]
## Feature Request
We would like the ability to pass the raw packet from an external service to a custom deserializer, which can process the packet and return the proper format for pattern matching.

## Is your feature request related to a problem? Please describe.
When we integrated Nest microservices with our external services, we realized that there is currently no way to route events to the proper controller when using formats that don't conform to Nest's requirements. Specifically, when using RabbitMQ and Kafka, we use custom headers to delineate event types. Because of the domain of our work, we cannot change the format of our events, meaning we cannot include the "pattern" key required by Nest. If we could pass the packet to a custom deserializer, we could perform all necessary processing to return an object with the correct format, including the "pattern" key.

## Describe the solution you'd like
We would like to add a configuration option alongside custom serializers and deserializers which, when enabled, would pass raw packets to the de/serializer instead of the content alone.

## Teachability, Documentation, Adoption, Migration Strategy
This can be used by providing a custom de/serializer and setting a "useRawPacket" configuration option.

## What is the motivation / use case for changing the behavior?
In order to be "platform-agnostic", Nest needs to support formats that may not fit its own. Allowing custom serializers and deserializers to process packets into a supported format will allow microservices to support any external service, regardless of message format.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to address this issue? This has been discussed many times in the past and currently, the only solution is to create a custom transport strategy.

**Comment by Dallin343** [comment]
Absolutely, I'll clean up our implementation and create a PR when I have time.

**Comment by leonardovillela** [comment]
Hi @kamilmysliwiec, I think this is already supported by microservice [deserializer option](https://github.com/nestjs/nest/blob/9aa9d0ee24d6f4efe2cef8d6cfa114a546dddebb/packages/microservices/server/server.ts#L172-L179).

**Comment by jeanbmar** [comment]
> Hi @kamilmysliwiec, I think this is already supported by microservice [deserializer option](https://github.com/nestjs/nest/blob/9aa9d0ee24d6f4efe2cef8d6cfa114a546dddebb/packages/microservices/server/server.ts#L172-L179).

No, the JSON socket attempts to parse the raw data to JSON.

```js
private handleMessage(data: string) {
    this.contentLength = null;
    this.buffer = '';

    let message: Record<string, unknown>;
    try {
      message = JSON.parse(data);
    } catch (e) {
      throw new InvalidJSONFormatException(e, data);
    }
    message = message || {};
    this.socket.emit(MESSAGE_EVENT, message);
  }
```

**Comment by jeanbmar** [comment]
@kamilmysliwiec I can code this PR quicky but I would like your opinion on my solution first.

The main difficulty with raw TCP packets is that NestJS users are responsible for their delimitation.
We are not talking about the de/serialization level. We are talking about the socket level and how we delimit a raw message from net.Socket `data` event.

The solution I have in mind:
1. The existing JsonSocket is split in two classes:
  - a generic TcpSocket class which contain generic socket logic,
   - a new JsonSocket class which inherits TcpSocket and implements the data / message events as in the existing class.
2. The new TcpSocket class is exposed so users can inherit it and implement their own delimitation of messages from socket data. i.e. they are responsible for managing the socket `data` event and for emitting the Nest `message` event.
3. A `socket` option is added for the `Transport.TCP` transport when `createMicroservice` is called. Default value is JsonSocket so we are 100% backward compatible. Users can specify their own derived child from TcpSocket instead, which will be used inside `getSocketInstance`.
4. I've mainly talked about packet decoding in server class, but packet encoding follows the same logic in client class.

What's your opinion about it? Thanks for your time.

**Comment by ologbonowiwi** [comment]
this still open?

**Comment by jg572h** [comment]
Is there an example somewhere of how to use this?

**Comment by jeanbmar** [comment]
@jg572h [JsonSocket](https://github.com/nestjs/nest/blob/master/packages/microservices/helpers/json-socket.ts) is an example of a raw tcp socket implementation.
You can implement your own socket the same way, and pass it to [ClientTCP](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-tcp.ts) and [ServerTCP](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-tcp.ts) using the `socketClass` option.

**Comment by receiver1** [comment]
I still don't understand why this was done. Logically, `JsonSocket` should be responsible for the message stream format when communicating via JSON, and we have a `Serializer` and `Deserializer` for this, but for some reason, `TcpSocket` tries to forcefully deserialize JSON when called `emitMessage` method. It would be better to move this to `JsonSocket` to allow users to use custom formats, not JSON. Right now, I have to manually call `this.server.emit('message', string)` and handle all deserialization in my own `Deserializer` as it was originally intended, I suppose..
