### ISSUE TITLE
Global validation pipe overriden in whole Resolver if overriden in single method

### ISSUE THREAD

**Issue by ekzyis** [nestjs/nest#7290]
## Current behavior

I have enabled validation and transformation globally via 
```ts
app.useGlobalPipes(new ValidationPipe({ transform: true }));
```
This works just fine.

Now, I wanted to validate a simple string property without having to create a class, so I created a custom validation pipe `IsNotEmptyStringPipe` and used it like this inside a GraphQL mutation:
```ts
@Mutation()
async mergeGroups(
  @Args('name', IsNotEmptyStringPipe) name: string,
  @Args('groupIds') groupIds: string[]
): Promise<Group> {
  return this.graphqlService.mergeGroups({ name, groupIds });
}
```

This also works just fine.

BUT: After some debugging, I noticed that this causes the globally enabled validation pipe to disappear on the other methods of the same resolver.

This means in this mutation:
```ts
@Mutation()
async updateGroup(
  @Args('id') id: string,
  @Args('group') group: UpdateGroupInput
): Promise<Group> {
  return this.graphqlService.updateGroup({ id, group });
}
```
`group` is no longer transformed to a `UpdateGroupInput` instance as long as `IsNotEmptyStringPipe` exists in the other method. 
## Input Code

*main.ts*
```ts
// App setup 
// ...
app.useGlobalPipes(new ValidationPipe({ transform: true }));
// ...
```
*group.resolver.ts*
```ts
@Resolver('Group')
export class GroupResolver {
  constructor(private graphqlService: GraphqlService) {}

  @Mutation()
  async updateGroup(
    @Args('id') id: string,
    @Args('group') group: UpdateGroupInput
  ): Promise<Group> {
    return this.graphqlService.updateGroup({ id, group });
  }

  @Mutation()
  async mergeGroups(
    @Args('name', IsNotEmptyStringPipe) name: string,
    @Args('groupIds') groupIds: string[]
  ): Promise<Group> {
    return this.graphqlService.mergeGroups({ name, groupIds });
  }
}
```

*UpdateGroupInput.dto.ts*
```ts
export class UpdateGroupInput {
  @IsNotEmptyString()
  @IsOptional()
  name?: string;
  @Transform(({ value }) => (value.trim() === '' ? null : value.trim()))
  @IsOptional()
  country?: string;
  @Transform(({ value }) => (value.trim() === '' ? null : value.trim()))
  @IsOptional()
  contract?: string;
  @Transform(({ value }) => (value.trim() === '' ? null : value.trim()))
  @IsOptional()
  website?: string;
}
```

*validation.ts*
```ts
import { ArgumentMetadata, Injectable, PipeTransform } from '@nestjs/common';
import {
  ValidationOptions,
  registerDecorator,
  isNotEmpty,
  ValidationArguments,
  isString,
} from 'class-validator';

export function IsNotEmptyString(validationOptions?: ValidationOptions) {
  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  return (object: unknown, propertyName: string) => {
    registerDecorator({
      name: 'isNotEmptyString',
      target: object.constructor,
      propertyName,
      options: validationOptions,
      validator: {
        validate: (value: any): boolean =>
          isString(value) && isNotEmpty(value.trim()),
        defaultMessage: (validationArguments?: ValidationArguments): string =>
          `${validationArguments.property} should be a non-empty string`,
      },
    });
  };
}

@Injectable()
export class IsNotEmptyStringPipe implements PipeTransform {
  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  transform(value: any, metadata: ArgumentMetadata): string {
    if (!(isString(value) && isNotEmpty(value.trim()))) {
      throw Error(`${metadata.data} should be a non-empty string`);
    }
    return value;
  }
}
```

## Expected behavior

Overriding a globally enabled validation pipe in a single method should not cause the globally enabled validation pipe to disappear in other methods. This is very confusing behaviour and took me a whole day to debug why my input is no longer transformed.

## Environment

<pre><code>
Nest version: 7.6.0
Node version: v16.2.0
</code></pre>

**Comment by ekzyis** [comment]
I have not provided a minimal reproduction repo because I first wanted to check if this may indeed be expected behavior and not a bug and I just haven't found documentation about this.

So before I dig into creating one, I wanted to make sure that this issue is not already known.

If you want one to dig further into this, I can provide one, just let me know :+1:

**Comment by jmcdo29** [comment]
Yeah, this seems super weird if it's truly the case. If you could provide a minimum reproduction repo, that would be great

**Comment by ekzyis** [comment]
Also, I found out when I import `ValidationPipe` without even using it everything works as expected:

```ts
import { ValidationPipe } from '@nestjs/common';
// ...
@Resolver('Group')
export class GroupResolver {
  constructor(private graphqlService: GraphqlService) {}

  @Mutation()
  async updateGroup(
    @Args('id') id: string,
    @Args('group') group: UpdateGroupInput
  ): Promise<Group> {
    return this.graphqlService.updateGroup({ id, group });
  }

  @Mutation()
  async mergeGroups(
    @Args('name', IsNotEmptyStringPipe) name: string,
    @Args('groupIds') groupIds: string[]
  ): Promise<Group> {
    return this.graphqlService.mergeGroups({ name, groupIds });
  }
}
```

So this may make things even more weird :D 

> Yeah, this seems super weird if it's truly the case. If you could provide a minimum reproduction repo, that would be great

Okay, I'll see if I can create one soon :+1: 

Thanks for answering so fast!

**Comment by ekzyis** [comment]
Okay, my minimum reproduction repo has concluded that this indeed work. So I can use 
```
app.useGlobalPipes(new ValidationPipe({ transform: true }));
```
and a custom pipe on a method without the validation disappear on the other method ...

Mhh, have to check what is different in my code ...

**Comment by kamilmysliwiec** [comment]
@ekzyis I suppose that the reason might be a circular dependency causing metadata losses. Check out this tool https://github.com/pahen/madge and try to eliminate unnecessary circular imports/refs between your files (e.g., move interfaces to separate files, avoid using barrel `index.ts` files, etc.)

**Comment by ekzyis** [comment]
Okay, very weird. I remembered that I forgot to mention that this only seems to happen during e2e tests (I am using jest) but not during the actual run of the server with `nest start`.

But now I rechecked that but it seems that now, it also works during the e2e tests (without my hotfix from yesterday where I imported `ValidationPipe` without using it).

Now I am very confused :D I hoped it would be a circular dependency issue and I can properly fix it that way but now the issue seems completely gone :D That's how going crazy must feel :D

Will come back again when I ever notice it again, thanks for your support!

**Comment by jmcdo29** [comment]
@ekzyis in your e2e test do you bind the global pipe?

**Comment by ekzyis** [comment]
Good question but yes, I do :+1:

**Comment by jmcdo29** [comment]
Okay, that's one of the common culprits. Like Kamil said, if you want to discuss this further, I'll be happy to on our [Discord](https://discord.gg/nestjs). Usually quicker and easier responses there in my opinion as well
