### ISSUE TITLE
How to return data from once service into another service when using @MessagePatterns

### ISSUE THREAD

**Issue by dwarak123** [nestjs/nest#7292]
## Current behavior
Hello 

I have implemented the hybrid application with nestjs with an external http port and an internal microservices port. I have many services for which I do not require responses so have implemented the @EventPattern for this and works like a charm. But for some of my services that depend on the other I need to get the response and use it as an input into another service. 

The issue is that if I assign a constant to the client to receive the data instead of returning it fails how do I capture the observable that comes back thanks in advance 

## Input Code client code

async create(ClaimDto: CreateClaimDto) {
    const crRequest = await this.createCareRecipients(ClaimDto);
    this.Client.send(Constants.CLAIM.msCrReq, crRequest)   
  }

@MessagePattern(Constants.CLAIM.msCrReq)
  async processCarerecipient(dto: CreateCarerecipientDto){
    this.logger.log(`Data Listner : ${JSON.stringify(dto)}`);
    return await this.service.processCarerecipient(dto);
  }

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by divyarajbaraiya** [comment]
@dwarak123 you have to append promise to get result from request pattern. see ex. below

async create(ClaimDto: CreateClaimDto) {
const crRequest = await this.createCareRecipients(ClaimDto);
const response = this.Client.send(Constants.CLAIM.msCrReq, crRequest).pipe().toPromise();
}

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
