### ISSUE TITLE
ValidationPipe doesn't handle composite objects

### ISSUE THREAD

**Issue by skliarovartem** [nestjs/nest#7295]
## Current behavior
It is common for microservices when body is composited from few models/DTOs, for example I receive Foo DTO in my API Gateway and then send it with User object to microservice. In my case `@Transform` decorator in Foo DTO doesn't work. But it works if body is just Foo.

## Input Code
```
@MessagePattern(FOO)
async foo(@Body() body: { user: User, data: Foo }){
}

export class Foo {
    @Transform(val => BigInt(val.value))
    amount: bigint;
}

app.useGlobalPipes(new ValidationPipe({transform: true}));
```

## Expected behavior
All Foo transforms must be executed

## Possible Solution
Maybe some ValidationPipe parameters can solve it

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
