### ISSUE TITLE
Code generator for CRUD CQRS

### ISSUE THREAD

**Issue by FBurner** [nestjs/nest#7296]
## Feature Request

Since there are a lot resources already in the generator.
I would really enjoy to see a crud generator for CQRS.

I would suggest that the generator are more focused on the seperate use cases,
for example GraphQL -> CQRS -> Mongoose.

nest g resource users --cqrs

would generate:
/command/user-create.event.ts
/command/user-create.handler.ts
...
/events/user-created.event.ts
/events/user-created.handler.ts
..
/queries/get-user.query.ts
/queries/get-user.handler.ts

and wire those already with the auto generated dto.

## Teachability, Documentation, Adoption, Migration Strategy
Add generator to the general documentation for crud.

## What is the motivation / use case for changing the behavior?
we generate a lot of features with cqrs and graphql and it takes a lot of time to wire it together manually and it would speed up development.

-- otherwise
any suggestion for tools to build a custom code generator?

**Comment by jmcdo29** [comment]
Nest uses [Angular Schematics](https://angular.io/guide/schematics) for code generation, if you want to throw your hand at making your own collection for this. I think resources is feature complete from Nest's perspective as is, but community additions are always welcome. If you need another examples [nest-commander](https://github.com/jmcdo29/nestjs-commander) has a schematics package that can be used with the Nest CLI
