### ISSUE TITLE
Token Validation didnt work when we use Passport BearerStrategy

### ISSUE THREAD

**Issue by rammarella21** [nestjs/nest#7302]
We are facing an issue in validating JWT token using BearerStrategy along with AuthGaurd. We have protected our API with AuthGaurd and then when we use postman or any other tool by calling API endpoint without real token in it like 
"Authentication" : "Bearer testtoken" or 
"Authentication" : "Bearer t" or 

it simply passed and allowed the user to execute API; as long as authentication header has Bearer to begin with it passes.

Code using:
export class BearerStrategy extends PassportStrategy(Strategy, 'bearer') {
        async validate(accessToken: string) {
        
         done(null, accessToken);//this is without Bearer word on it; so its real token passing
}

Our API protection:
@UseGuards(AuthGuard('bearer'))
    async get(@Body() filter: TESTDATA[]) {
}
----
AuthModule:
@Module({
  
  controllers: [AuthController],
  providers: [OAuth2Strategy, BearerStrategy],
})

from our UI we execute login API end point using 'oauth2' strategy and that code follows:

export class OAuth2Strategy extends PassportStrategy(Strategy, 'oauth2') {

  constructor() {
    const serverURL = config.get('SERVER_URL');
    let appRootURL = process.env.NODE_ENV === 'localhost' ? 'http://localhost:' + config.get('app.port') : config.get('app.rootUrl');
    if (!appRootURL.endsWith('/')) {
      appRootURL += '/';
    }
    const appBaseURL = `${appRootURL}${config.get('globalPrefix')}`;
    const loginCallbackURL = `${appBaseURL}/auth/login/callback`;
    super({
      authorizationURL: `${serverURL}oauth2/authorize`,
      tokenURL: `${serverURL}oauth2/token`,
      clientID: config.get('CLIENT_ID'),
      clientSecret: config.get('CLIENT_SECRET'),
      callbackURL: loginCallbackURL,
      scope: ['openid', 'profile'],
      state: (100000000000).toString(36)
    }, function(accessToken: string, refreshToken: string, params: any, profile: any, done: VerifyCallback) {
      done(null, {
        accessToken: accessToken
      });
    });
  }
}
Once we have token generated here with AWS COGNITO - we pass that token there after in every API call as Bearertoken as Authentcation header.

Everyother functional API protected with AUTHGUARD with 'bearer' strategy.

Documentation says that under validate method simply call  - callback done function by passing token and under the hood passportjs would validate the token.

I could add as much as I can but let me know if you need further details.

There is no issue in generating the token - user key in the thier details and UI calls login API which are using 'oauth2' AUTHGUARD which helps us to get authenticated and returns valid token; But, when UI sends this token to API for subsequent calls to pull data etc via APIs the token isnt really getting validated if we use PostMan or any other tools to test out API.

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction

**Comment by rammarella21** [comment]
> Please provide a minimum reproduction. This seems like a configuration problem, but I'll look into it if you can provide something.

Thanks for checking this - I have added as much information as I could; of course we do use AWS Secret/clientId from config files to pass while creating the token using 'oauth2';

**Comment by jmcdo29** [comment]
There's no [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction/) available to clone, with reproduction instructions, so there's nothing I can do here. If you can provide a repo that I can work with I'll reopen the issue.

**Comment by rammarella21** [comment]
I have added the code snippets into the original post - but I dont have the git repo to provide.

**Comment by jmcdo29** [comment]
You validate the token in nest as you do in node. Whatever you return from your `validate` is what is assigned to `req.user` using passport.

Nope, either provide a minimum reproduction repository, or use our [Discord](https://discord.gg/NestJS) where I'll ask you for the same thing. We're using GitHub to track Bug Reports, Feature Requests, and Regressions.
