### ISSUE TITLE
Apps are not created in src directory

### ISSUE THREAD

**Issue by tbhaxor** [nestjs/nest#7303]
## Current behavior

![Screenshot_20210626_155029](https://user-images.githubusercontent.com/28386721/123509952-3eae9780-d696-11eb-93ac-cc87b3dc9547.png)

I completed nestjs documentation yesterday. Till then apps were created in the `src` folder. Now the command creates an application in the `apps` directory

nest-cli.json before running the command
```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src"
}
```

nest-cli.json after running the command
```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "apps/backend/src",
  "monorepo": true,
  "root": "apps/backend",
  "compilerOptions": {
    "webpack": true,
    "tsConfigPath": "apps/backend/tsconfig.app.json"
  },
  "projects": {
    "backend": {
      "type": "application",
      "root": "apps/backend",
      "entryFile": "main",
      "sourceRoot": "apps/backend/src",
      "compilerOptions": {
        "tsConfigPath": "apps/backend/tsconfig.app.json"
      }
    },
    "test": {
      "type": "application",
      "root": "apps/test",
      "entryFile": "main",
      "sourceRoot": "apps/test/src",
      "compilerOptions": {
        "tsConfigPath": "apps/test/tsconfig.app.json"
      }
    }
  }
}
```

One more thing. while scaffolding there is a `src` directory and after running `nest g app test` it deletes the folder and create `apps` folder

PS: Take any name of the app, the result is the same

## Input Code

1. `nest new App`
2. `nest g app test`

## Possible Solution

It should only contain apps in the `src` folder

## Environment

<pre><code>
Nest version: 7.6.0

 
For Tooling issues:
- Node version: 14.17.0
- Platform:  Linux

Others:

</code></pre>

**Comment by jmcdo29** [comment]
You change from a single application setup to a monorepo setup. This is the expected behavior and everything is working as designed

**Comment by tbhaxor** [comment]
@jmcdo29 Could you help me out here?

**Comment by jmcdo29** [comment]
If you need support, I suggest you visit our [Discord](https://discord.gg/nestjs). This is not a bug but the intended design of what should happen when you have multiple applications under the same project root, [as described in the docs](https://docs.nestjs.com/cli/monorepo#monorepo-mode)

**Comment by tbhaxor** [comment]
Yeah i have already found the docs related to it
