### ISSUE TITLE
Please provide way to send & receive Temporal PlainDate and have it reflected in OpenAPI spec

### ISSUE THREAD

**Issue by programmatix** [nestjs/nest#7304]
## Is your feature request related to a problem? Please describe.
The OpenAPI specification permits two forms of dates & date-times:

```
"myDate": {
  "format": "date-time",
  "type": "string"
}
```
which can take ISO-8601 date-times like "2017-07-21T17:32:28Z".

and 
```
"myDate": {
  "format": "date",
  "type": "string"
}
```
which can take ISO-8601 dates like "2017-07-21".

As far as I can tell, Nest will automatically set the "date-time" format when using a js `Date` object.  Otherwise, I can't see any way to get Nest to send a "format" field.  When I try to use a Temporal PlainDate, I just see it described as a basic `object` in the OpenAPI spec:

```
"myDate": {
  "$ref": "#/components/schemas/PlainDate"
},

...

"PlainDate": {
  "type": "object",
  "properties": {}
},

```

## Describe the solution you'd like
I'd like to be able to send a Temporal PlainDate in my DTO:
```
import {Temporal} from 'proposal-temporal';

export class DateTest {
    myDate: Temporal.PlainDate;
}
```
and have it produce the "date" format OpenAPI:
```
"myDate": {
  "format": "date",
  "type": "string"
}
```

Similarly, I'd like to be able to send and receive a `Temporal.PlainDateTime` and `Temporal.ZonedDateTime` and have that result in a "date-time" format.

If would be great if it worked automagically as above.  If that's not possible and instead I need to do some annotation work, something like this, then that's also fine:

```
export class DateTest {
    @Transform(({value}) => PlainDate.from(value), {toClassOnly: true})
    @Transform(({value}) => value.toString(), {toPlainOnly: true})
    @ApiProperty({format: 'date'})
    date: Temporal.PlainDate;
}
```

If it's possible to support other libraries than Temporal, such as Moment et al, even better!

## Teachability, Documentation, Adoption, Migration Strategy
Er, not sure! 

## What is the motivation / use case for changing the behavior?
Many JS users don't like using the `Date` built-in library and prefer to use more advanced replacements, like Temporal, which looks like it may become the de-facto replacement.  This would extend NestJS's great OpenAPI support to nicely handle popular alternative Date libraries, and correct set the OpenAPI fields

**Comment by jmcdo29** [comment]
After taking a look at the `proposal-temporal` code, what Nest is doing makes sense in the fact that `Temporal.PlainDate` is a class and not some sort of primitive. Until there is a definite replacement of JavaScript's built-in `Date` class, I don't think Nest is going to be able to make any assumptions about temporal, moment, date-fns or any other date handling package, due to the amount of complexity this would bring in. It is possible to set this metadata yourself, as you've demonstrated using `@ApiProperty()` and `@Transform()` to get the transformations to happen as well, but I'm not sure this is going to be something Nest can handle easily.

**Comment by programmatix** [comment]
Hi @jmcdo29, thank you for the reply.  I understand your position there.

> It is possible to set this metadata yourself, as you've demonstrated using @ApiProperty() and @Transform()

Well just to point out, my example with the @ApiProperty({format: 'date'}) does not work - that's an example of what a Nest extension could look like.  And this would seem a reasonable extension, I think?  Allow the OpenAPI parameters to be set, without adding anything Temporal-specific.

**Comment by jmcdo29** [comment]
Maybe I'm missing something, but `@ApiProperty({ format: 'date' })` does indeed tell OpenAPI  that the value should be a string in the date format, **but** you have to also specify the `type` property to be `string`. You can see on the screenshot that swagger understands it
![image](https://user-images.githubusercontent.com/28268680/123551952-de1c6a80-d728-11eb-937e-32ec6c19c849.png)

Along with the corresponding code and openapi-json
```ts
// app.dto.ts
import { ApiProperty } from '@nestjs/swagger';
import { Temporal } from 'proposal-temporal';

export class AppDto {
  @ApiProperty({ format: 'date', type: 'string' })
  public date: Temporal.PlainDate;
}
```
```json
{
  "openapi": "3.0.0",
  "info": { "title": "", "description": "", "version": "1.0.0", "contact": {} },
  "tags": [],
  "servers": [],
  "components": {
    "schemas": {
      "AppDto": {
        "type": "object",
        "properties": { "date": { "format": "date", "type": "string" } },
        "required": ["date"]
      }
    }
  },
  "paths": {
    "/": {
      "get": {
        "operationId": "AppController_getHello",
        "parameters": [
          {
            "name": "date",
            "required": true,
            "in": "query",
            "schema": { "format": "date", "type": "string" }
          }
        ],
        "responses": { "200": { "description": "" } }
      },
      "post": {
        "operationId": "AppController_getPost",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/AppDto" }
            }
          }
        },
        "responses": { "201": { "description": "" } }
      }
    }
  }
}
```
[This is how the Open API spec expects to see date fields](https://swagger.io/docs/specification/data-models/data-types/#string), so unless I'm missing something, this is already possible

**Comment by programmatix** [comment]
> Maybe I'm missing something, but @ApiProperty({ format: 'date' }) does indeed tell OpenAPI

My apologies, I'd had a look through the docs and source, but couldn't find this parameter available.  On looking again more closely I see it's there on one of the parent classes of `ApiPropertyOptions`:

```
export interface SchemaObject {
...
    pattern?: string;
```
Thank you for the help.
