### ISSUE TITLE
Cron Job Multiple Core Support

### ISSUE THREAD

**Issue by Bob-MYMC** [nestjs/nest#7305]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

We have the scheduled job running every 5 mins to export info from the database.
The server runs two cores, causing duplicate files exported. 
Is there any setting or solution to run the job only on one core?

Thanks

**Comment by kamilmysliwiec** [comment]
> Is there any setting or solution to run the job only on one core?

For example, repeatable jobshttps://docs.nestjs.com/techniques/queues + https://optimalbits.github.io/bull/

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
