### ISSUE TITLE
Conditional Injection for factories/static methods

### ISSUE THREAD

**Issue by pragmaticivan** [nestjs/nest#7306]
## Is your feature request related to a problem? Please describe.
I'm currently trying to conditionally inject something based on a config param.

```ts
private static async createNodeSDKProvider(): Promise<Provider> {
    return {
      provide: OPENTELEMETRY_SDK,
      useFactory: async (options: OpenTelemetryModuleOptions, exporter: PrometheusExporter) => {
        const { enable = false } = options?.withPrometheusExporter;
        if (enable) {
          options.nodeSDKConfiguration.metricExporter = exporter;
        }
        return new NodeSDK(options.nodeSDKConfiguration);
      },
      inject: [OPENTELEMETRY_MODULE_OPTIONS, OPENTELEMETRY_PROMETHEUS_EXPORTER],
    };
  }
```
` exporter: PrometheusExporter` might not be available depending on the value in the `enable` config.

## Describe the solution you'd like
A way to define a inject param to be conditional maybe?

ex:
```ts
private static createPrometheusExporterProvider(): Provider {
    return {
      provide: OPENTELEMETRY_PROMETHEUS_EXPORTER,
      useFactory: (options: OpenTelemetryModuleOptions) => {
        const { port = 8081 } = options?.withPrometheusExporter;
        return new PrometheusExporter({ port });
      },
      inject: [OPENTELEMETRY_MODULE_OPTIONS],
      strict: false, (or: conditional: true)
    };
  }
```
`strict?: boolean` or `conditional?: boolean`

**Comment by jmcdo29** [comment]
I think, if we make this possible in the first place, it should adhere closely to the already defined methods of conditionally injecting, namely `@Optional()` and we allow for something like
```ts
inject: [Foo, { provide: Bar, optional: true }]
```
Where `provide` can be a Class, symbol, or string, as injection tokens already are. 

I think this would be the best way to keep the dependency injection logic from getting too overloaded and cumbersome to work with. The other option, as we just spoke about on Discord, is to provide a `noop` provider for the optional dependency as a default and override it as necessary.

**Comment by kamilmysliwiec** [comment]
> I'm currently trying to conditionally inject something based on a config param.

https://docs.nestjs.com/fundamentals/module-ref#retrieving-instances

^ you can just inject the `ModuleRef` and conditionally retrieve the appropriate provider. No need to overcomplicate provider definitions.

**Comment by pragmaticivan** [comment]
@kamilmysliwiec would that work for static methods? That's the problem we're trying to solve in this ticket.

**Comment by kamilmysliwiec** [comment]
Yes
