### ISSUE TITLE
ERR_CONNECTION_RESET while file upload

### ISSUE THREAD

**Issue by Genbel** [nestjs/nest#7307]
I have implemented in a controller a route to upload files from axios. For that I use *FileInterceptor*. Everything works properly but as soon as I activate *network throttling* in the browser the uploader does not work. Here is the snippet:

```
@Post('/upload')
@UseInterceptors(
  FileInterceptor("file", { 
    storage: diskStorage({
      destination: './src/uploads',
      // editFileName is a function that changes the name of the file
      filename: editFileName,
    }), 
  })
)
uploadFile(@UploadedFile() file) {
  try {
    console.log(file)
    return 'ok';
  } catch(e) {
    console.log(e)
  }
}
```
This is the following error that I get: 

> POST http://localhost:3003/user/file/upload net::ERR_CONNECTION_RESET

It seems, it tries to connect twice to complete the process. First connection time is 60s and the second one also but after that it throws the above error.

I try many ways changing the timeout param but in none of them not success.
The first one is changing the destination config param of *diskStorage* from string to function:
```
destination: (req, file, callback) => {
  console.log(file);
  // That output I see when it uploads successfully in a normal network condition (wifi) 
  // but it ignores the timer time (30s). Usually is after 5 seconds.
  req.socket.setTimeout(30000, () => console.log('Socket ErrorTimeout'))
  req.setTimeout(5000, () => console.log('Error req timeout'))
  callback(null, './src/uploads')
}
```

Next one is, inside of bootstrap function on the main file adding the following snippet:
```
const server = await app.listen(3003);
server.on('connection', (socket) => {
 console.log('Connected!')
 socket.setTimeout(5*10*1000)
})
```

And finally adding another module in FileUploader module but also not success:
```
@Module({
  imports: [
    MulterModule.register({
      dest: './src/uploads'
    }),
    HttpModule.register({
      timeout: 90000,
      maxRedirects: 5,
    })
  ],
  controllers: [FilesController]
})
export class FilesModule {}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Genbel** [comment]
No problem! thanks

**Comment by liuwenzhoa** [comment]
我也遇到了类似的问题。当 multer 的 fileFilter 返回一个异常的时候，如果客户端请求的文件过大，客户端就会导致Network Error。客户端无法接收到正确的异常响应信息。
