### ISSUE TITLE
How to use Service in Global-interceptor in NEST Js

### ISSUE THREAD

**Issue by shaharyar123** [nestjs/nest#731]
I want to use service in global interceptor.

My code look like this in Global-interceptor  file:
```
import { VariablesService } from '../app/modules/variables/variables.service';

@Interceptor()
export class globalInterceptor implements NestInterceptor {
  constructor(private service: VariablesService) {
    console.log('contructor running', service);  //getting null here
  }
```

and on server.ts first i was initializing like this :

`app.useGlobalInterceptors(new globalInterceptor())
`

but after the injection of service i have to do some modification because parameters are needed now in **globalInterceptor()**

```
const variableService = await app.get<VariablesService>(VariablesService);
  app.useGlobalInterceptors(new globalInterceptor(variableService));
```

Now what the problem is I am getting **service** is **null** .
 I am unable to create the object of the service

Stack-overflow : [Link](https://stackoverflow.com/questions/50503996/how-to-use-service-in-global-interceptor-in-nest-js)

**Comment by kamilmysliwiec** [comment]
Hi @shaharyar123,
I left an answer on the stackoverflow: https://stackoverflow.com/questions/50503996/how-to-use-service-in-global-interceptor-in-nest-js/50528691#50528691
