### ISSUE TITLE
Rmq socket options not passed correctly when creating a microservice

### ISSUE THREAD

**Issue by alexreal1314** [nestjs/nest#7317]
## Current behavior
When creating a RMQ microservice and passing socketOptions object it is not passed correctly to amqpb-connection-manager library. I saw the PR that was made https://github.com/nestjs/nest/pull/5790 but it did not resolve the issue.
The documentation listed in https://www.npmjs.com/package/amqp-connection-manager suggest that the following params:
options.heartbeatIntervalInSeconds  and options.reconnectTimeInSeconds are passed directly to the library options.

## Input Code

```ts
  const options: MicroserviceOptions = {
    transport: Transport.RMQ,
    options: {
      urls: [app.get('ConfigService').get('rabbit.hostname')],
      queue: app.get('ConfigService').get('rabbit.autopsyQueue'),
      prefetchCount: 1,
      noAck: false,
      queueOptions: {
        durable: true,
      },
      socketOptions: {
        heartbeatIntervalInSeconds: 6000,
        reconnectTimeInSeconds: 10
      }
    }
  }

//microservices/server.rmq.js
    createClient() {
        const socketOptions = this.getOptionsProp(this.options, 'socketOptions');
        return rqmPackage.connect(this.urls, { connectionOptions: socketOptions });
    }

//output of the server object
this.server  AmqpConnectionManager {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: 0,
  _channels: [],
  _currentUrl: 0,
  connectionOptions: { heartbeatIntervalInSeconds: 6000, reconnectTimeInSeconds: 10 },
  heartbeatIntervalInSeconds: 5,
  reconnectTimeInSeconds: 5,
  _findServers: [Function (anonymous)],
  _connectPromise: Promise { <pending> },
  [Symbol(kCapture)]: false
}
```

## Expected behavior
pass the heartbeatIntervalInSeconds and reconnectTimeInSeconds as parameters when creating a connection.

## Possible Solution
```ts
public createClient<T = any>(): T {
    const socketOptions = this.getOptionsProp(this.options, 'socketOptions');
    return rqmPackage.connect(this.urls, { 
        connectionOptions: socketOptions,
        heartbeatIntervalInSeconds: socketOptions.heartbeatIntervalInSeconds,
        reconnectTimeInSeconds: socketOptions.reconnectTimeInSeconds
    });
  }
```

## Environment

<pre><code>
Nest version: 7.6.0
amqp-connection-manager: "^3.2.2"

 
For Tooling issues:
- Node version: v14.16.0  
- Platform:Linux  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by alexreal1314** [comment]
yes, I'll open a PR

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/7345

**Comment by luigi-13** [comment]
Hello, 

maybe forgive my misunderstanding, but dont we have the same problem with the /microservices/client/client-rmq.js file ?

Indeed, with @nestjs/microservices@9.1.2 this working for my microservice app, the heartbeat is updated but not when using with ClientsModule/ClientProxy on another app with same version.

So   

```
const queue: ClientProviderOptions = {
  ...rmqOptions,
  // injection token for our RabbitMQ client
  name: queueName,
  options: {
    ...rmqOptions.options,
    // actual RabbitMQ queue name
    queue: queueName,
    // require explicit acknowledgement of messages
    noAck: false,
    prefetchCount:200,
    queueOptions: {
      // setup the dead letter exchange to point to the default exchange
      deadLetterExchange: '',
      // all dead letters should be routed to our recoveryQueue
      deadLetterRoutingKey: recoveryQueue,
      // set message time to live to 4s
      messageTtl: 3600000,
    },
    socketOptions: {
      heartbeatIntervalInSeconds: 20,
      reconnectTimeInSeconds: 5,
    },
  },
  
};
const microservice = await app.connectMicroservice(queue);
```
heartbeat is updated on this microservice app.

But 
` ClientsModule.register([queue])` on another app not update the heartbeat for this connection

Thanks
