### ISSUE TITLE
Testing: Cannot override provider with value because the value is falsy

### ISSUE THREAD

**Issue by dawidcxx** [nestjs/nest#7362]
## Current behavior

Currently in my application I have a configuration parameter that I declare in a `providers[]` block of the module declaration. This param is an number, in my application. I set it to `30`. For testing I would like to set this value to `0`. For this I'm using `TestingModuleBuilder#overrideProvider` followed by a `OverrideBy#useValue` However I'm unable to do so! After some investigation it seems like it is impossible to override using falsy values. 

## Input Code
```typescript
// doesn't actually override anything
export function commonTestBuilderSettings(builder: TestingModuleBuilder) {
  builder
    .overrideProvider(SOME_DELAY_I_WANT_TO_CONFIG_FOR_TESTING)
    .useValue(0);
}
```

```typescript
// now works, because 1 is not falsy
export function commonTestBuilderSettings(builder: TestingModuleBuilder) {
  builder
    .overrideProvider(SOME_DELAY_I_WANT_TO_CONFIG_FOR_TESTING)
    .useValue(1);
}
```

## Expected behavior
At least I would expect a warning or, better to just work also with `0`. 

## Possible Solution
I suppose the issue is a `if (value) ` or `||` operator somewhere in the code. Should consider strict checking (`===`) or using `??`

## Environment

<pre><code>
Nest version: 7.6.18

**Comment by kamilmysliwiec** [comment]
Great catch!

Fixed in this commit https://github.com/nestjs/nest/commit/12ee93136df48fa72076d089883423d7f49ca800, will be published as part of the next release.
