### ISSUE TITLE
NestJS Passport Token Validation doesnt work with bearer/jwt strategy

### ISSUE THREAD

**Issue by rammarella21** [nestjs/nest#7364]
## Current behavior
We have JWT token generated by APP by using OAUTH2 strategy by using COGNITO at the user login(we had to use OAUTH2 for SSO capabilities to build upon. The web app will send the JWT token in subsequent API calls and our APIs are protected by NESTJS Guards(bearer); But APIs are accesible from postman or any other similar tools if calls made using just authorization header as "Bearer test" or "Bearer " - the validate method under BearerStrategy returns successful all the times.
Since, Bearer didnt work, we tried with JWT strategy by passing appropriate parameters as mentioned in jwt-strategy.ts file but it failed with "TypeError: cb is not a function".

our COGNITO generates the token and also we pass clientID and ClientSecret from our Oauth2 strategy to generate the token.

## Input Code

repo created with code
https://github.com/rammarella21/nest-js-jwt-passport

## Expected behavior
when we call validate method in BearerStrategy it should validate the token appropriately.

## Environment

We are facing this in QA env and we are heading to prod soon.
 
all configurations needs to be added default.json file that app is expecting like COGNITO related params; I did not supply them.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
