### ISSUE TITLE
Add unit tests to documentation

### ISSUE THREAD

**Issue by FrancoAntu** [nestjs/nest#7368]
## Is your feature request related to a problem? Please describe.
The documentation of the framework is really great, but it would be greater with unit test included, not on the page but in the Github repositories

**Comment by jmcdo29** [comment]
One of the reasons unit tests are talked about in theory/api wise vs showing examples is to ensure developers don't think that what's in the docs "is the only way". That's the reason I created [testing-nestjs](https://github.com/jmcdo29/testing-nestjs) to show several examples of test types with NestJS. Maybe instead we could mention this is a public repository of examples, but they are not in any way the only canonical way to test Nest apps.

**Comment by FrancoAntu** [comment]
Thank you for your prompt response, that is true it is not the only way to do that.
I'll take a look to the repository you've provide me and see if there's the unit test I'm looking for, thank you very much

**Comment by jmcdo29** [comment]
There's really not a reason to test the `*.module.ts` files, as they should be all config for Nest. If you have logic in them that needs to be tested, that logic can be moved to a different file

**Comment by FrancoAntu** [comment]
That's true, I'm going to try that, thank you Jay :grinning:
