### ISSUE TITLE
OnModuleInit lifecycle doesn't work with service from global module

### ISSUE THREAD

**Issue by golubvladimir** [nestjs/nest#7374]
## Current behavior
OnModuleInit lifecycle doesn't work, when I import service from global module

## Input Code

```ts
@Injectable()
export class AuthorsService implements OnModuleInit {
  constructor(
    private readonly appService: AppService // service flom @global module
  ) {}

  onModuleInit(): any {
    console.log(111222);
  }
}

```

## Expected behavior
OnModuleInit lifecycle will work

## Environment

<pre><code>
Nest version: 7.0.0

 
For Tooling issues:
- Node version: v14.16.1
- Platform:  Windows

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.
