### ISSUE TITLE
Getting array index in exceptionFactory

### ISSUE THREAD

**Issue by Abasz** [nestjs/nest#7379]
Fixed in 6.9.10.

The default (expected) exception message for nested objects:

```
'[0] random.title must be a string',
'[1] random.isEnabled should not be null or undefined',
'[1] random.isEnabled must be a boolean value',
'[1] random.createdAt must be a Date instance',
```

where [i] is an index in the input array. And for nested arrays:

```
'[0] random.0.title must be a string',
'[0] random.1.title must be a string',
'[1] random.0.isEnabled should not be null or undefined',
'[1] random.0.isEnabled must be a boolean value',
'[1] random.0.createdAt must be a Date instance',
```

if you need more control, you can always modify the `exceptionFactory` as @jmcdo29 suggested above.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/6263#issuecomment-772329310_

Hi I am trygin to get the array index within the exceptionFacotry to compose a custom error path. But I think this is not exposed in the exception factory. Is there any way to get hold of this index?

Thanks

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
