### ISSUE TITLE
Some routes under same controller getting 404

### ISSUE THREAD

**Issue by j-a-h-i-r** [nestjs/nest#7384]
## Bug Report

I have a quite simple setup. One AppModule and one AuthModule. The AppModule is generated by nest cli and is unchanged. 

```
// auth.controller.ts
@Controller('auth')
export class AuthController {
  constructor(private readonly authService: AuthService) {}

  @Post('/register')
  register(@Body() registerDto: RegisterDto) {
    return this.authService.register(registerDto);
  }

  @Post('/login')
  login(@Body() loginDto: LoginDto) {
    return this.authService.login(loginDto);
  }
}
```

The issue that POST to `/register` works fine but POST to `/login` returns 404. But in the console, I can see that both `/login` and `/register` are mapped correctly.

![image](https://user-images.githubusercontent.com/21159766/124327727-295fce80-dbaa-11eb-89e3-d87610f84f66.png)

This is already reported in #4269 but I was told to open a new issue.

## Expected behavior

Both routes respond with appropriate HTTP codes

## Environment

<pre><code>
Nest version: 7.6.15

For Tooling issues:
- Node version: 14.16.1  
- Platform: Windows  
</code></pre>

**Comment by jmcdo29** [comment]
I asked for a [minimum reproduction repository](http://minimum-reproduction.wtf). Without that, we won't be able to help you

**Comment by micalevisk** [comment]
@pro100kryto 

Please provide a minimum reproduction repository. You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by pro100kryto** [comment]
I dont know how to reproduce the problem without sharing the private code. I have successfully solved the bug moving that two problematic routes at the top of the same controller (above of all others routes, copy-paste). Then I have checked all routes for the same controller and all they are working 🤷‍♂️ well.

**Comment by micalevisk** [comment]
@pro100kryto as explained in the link I shared, we can't help you guys without some repro

**Comment by pro100kryto** [comment]
My mistake was that the route that I created at the bottom was too similar to another.
GET '/object/:id'
GET '/object/command'
I was trying to call the second route but the first one was cathing my request and return 404.
