### ISSUE TITLE
Nestjs endpoint resolution not working when upgrading Node version from 14 to 16

### ISSUE THREAD

**Issue by xplatsolutions** [nestjs/nest#7387]
## Current behavior
Using aws-serverless-express, graphql and serverless-offline locally with node 14.17.2 and Nestjs works fine but if I upgrade nodejs to 16 although the API starts when trying to hit any endpoint route API doesn't work, no errors or messages it just seem to not be able to connect/resolve. You can however connect to the graphql playground so it seems it is purely an GraphQL Nestjs endpoint resolution;
I am also using CQRS and JWT if that helps more.

## Expected behavior
The server API should resolve the route and correctly process the GraphQL input to provide response from the respective resolver.

## Possible Solution
No ideas at this point really.

## Environment

<pre><code>
"@nestjs/common": "^7.6.18",
"@nestjs/config": "0.5.0",
"@nestjs/core": "^7.6.18",
"@nestjs/cqrs": "^7.0.1",
"@nestjs/graphql": "^7.11.0",
"@nestjs/jwt": "^7.2.0",
"@nestjs/passport": "^7.1.6",
"@nestjs/platform-express": "^7.6.18",

 
For Tooling issues:
- Node version: 16
- Platform:  Mac

Others:
NPM package manager

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction

**Comment by xplatsolutions** [comment]
Will try to put something together first chance
