### ISSUE TITLE
WebSockets documentation errors

### ISSUE THREAD

**Issue by rkhaslarov** [nestjs/nest#7396]
## Current behavior
https://docs.nestjs.com/websockets/adapter -> Advanced (custom adapter) -> ws-adapter.ts code -> create function -> ws (undeclared variable) is used

## Expected behavior
WebSocket should be used

## Possible Solution
WebSocket should be used

[https://ibb.co/fQ7wxRx](url)

**Comment by kamilmysliwiec** [comment]
Fixed
