### ISSUE TITLE
Can't get response back from controller

### ISSUE THREAD

**Issue by tejaschauhan373** [nestjs/nest#7409]
Issue:
I have executed below code and at last return statement, it's going in infinity loop as I debug code,
It goes in infinity loop and does not give any error so I have not generated issue in stackoverflow & discord,
So, I want to draw attention towards it here

![image](https://user-images.githubusercontent.com/59693377/124585902-66aab180-de73-11eb-8c25-baf3f3337717.png)

Thanks!

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
