### ISSUE TITLE
monorepo depoly

### ISSUE THREAD

**Issue by Juan-hwt** [nestjs/nest#7413]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework
* 
how to deploy Monorepo project ????? with pm2

**Comment by Tony133** [comment]
Hi @Juan-hwt, for this type of advice question use the [discord](https://discord.com/invite/G7Qnnhy) support channel. 
 
The NestJS Core Team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by Juan-hwt** [comment]
thank you

**Comment by Tony133** [comment]
you're welcome, it's nothing. 👍
