### ISSUE TITLE
only use port 4000 but swagger can't display

### ISSUE THREAD

**Issue by Juan-hwt** [nestjs/nest#7414]
## Current behavior

I use monorepo mode on aws ec2 with 4000 port opened, input 'nest start' and run the project,
netstat -ntlp
![image](https://user-images.githubusercontent.com/82884966/124607949-e602aa00-dea0-11eb-9d17-8924a834ebb6.png)

all the things right , server no error 
but http://ec2-54-64-235-60.ap-northeast-1.compute.amazonaws.com:4000/api-doc/  
give me a error
![image](https://user-images.githubusercontent.com/82884966/124608203-1ba79300-dea1-11eb-95de-f16d963ef76b.png)

## Input Code

I think it is not of code error, it's problem of config,
but how can i open aws or server rights for swagger ??????
```ts
const your = (code) => here;
```

## Expected behavior

give me some advise to try
## Environment

<pre><code>
Nest version: 7.6.0

 
For Tooling issues:
- Node version: 14.17.2
- Platform:  Red Hat Enterprise Linux

Others:

</code></pre>

**Comment by Tony133** [comment]
Try asking this question on the [discord](https://discord.com/invite/G7Qnnhy) channel for support.
