### ISSUE TITLE
Logger setContext is not available in nestjs v8 anymore

### ISSUE THREAD

**Issue by angelo-v** [nestjs/nest#7442]
## Regression

We checked the migration guide, it does not mention changes in Logger.

## Describe the regression

In nestjs v7 we inject the logger via DI and set the context to the class name as follows:

```ts
constructor(
    private readonly logger: Logger,
  ) {
    this.logger.setContext(ThisService.name);
  }
```
This does not compile with nestjs v8 anymore:

> Property 'setContext' does not exist on type 'Logger'

## Expected behavior/code

We are unsure if this change is intended, as it is not mentioned in the migration guide. Please either update the guide and explain what alternatives exist to set the context when using DI or restore the method.

Also [the documentation](https://docs.nestjs.com/techniques/logger#logger) should not use setContext in the examples, if no longer available.

## Environment
<pre><code>
Nest version: 7.6.15-> 8.0.0

</code></pre>

**Comment by Tony133** [comment]
Hi @angelo-v, have you taken a look at this https://docs.nestjs.com/migration-guide#logger-breaking-changes? has recently been updated.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting!

Examples updated https://docs.nestjs.com/techniques/logger#injecting-a-custom-logger
Migration section added https://docs.nestjs.com/migration-guide#logger-breaking-changes

**Comment by mnedok** [comment]
> Hi @angelo-v, have you taken a look at this https://docs.nestjs.com/migration-guide#logger-breaking-changes? has recently been updated.

it's not in the docs and how to change existing code is also nowhere to be found.

**Comment by kamilmysliwiec** [comment]
@mnedok you should extend `ConsoleLogger` instead of `Logger`. This is outlined in the migration guide.
