### ISSUE TITLE
Documentation Error on Cache integration

### ISSUE THREAD

**Issue by RoxKilly** [nestjs/nest#7452]
## Bug Report
There are two errors in the [Cache integration docs](https://docs.nestjs.com/techniques/caching)

## Current behavior
1. The docs say:
> To disable expiration of the cache, set the ttl configuration property to null:

```ts
await this.cacheManager.set('key', 'value', { ttl: null });
```

In fact, the item is immediately purged when ttl is null

2. The docs also state:
> If the item does not exist in the cache, undefined will be returned.

In fact, when the item is not found `null` is returned

![Screenshot 2021-07-07 140650](https://user-images.githubusercontent.com/12346501/124808494-037d5580-df2d-11eb-88ed-1a62e9c98d5a.png)

## Expected behavior
1. Setting the ttl to `null` seems to expire the item immediately. 
2. I expected an `undefined` check against the query to tell me whether the item is in the cache

## Possible Solution
 To make it persist in the cache, I had to instead set ttl to `0`.  To check whether the item was found, I had to check for a `null` result.  Actually I do both but null is what gets returned
```ts
if (result === null || result === undefined) { /* nothing found */ }
```
 I suggest updating the docs.

## Environment

<pre><code>
Nest version: 7.6.18
cache-manager: 3.4.4
cache-manager-redis-store: 2.0.0
</code></pre>

[Repo link](https://github.com/RoxKilly/nestjs-redis-troubleshoot/tree/issue-7452)

**Comment by kamilmysliwiec** [comment]
Fixed. Thanks for reporting!
