### ISSUE TITLE
Should Passport also be at Version 8? 7.1.6 not working

### ISSUE THREAD

**Issue by godbrain** [nestjs/nest#7459]
## Regression
Passport Version fails so npm update and build fails...

## Describe the regression

After updating to Nest 8 the Passport package won't resolve

## Input Code
npm ERR! Found: @nestjs/common@8.0.0
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^6.0.0 || ^7.0.0" from @nestjs/passport@7.1.6
npm ERR! node_modules/@nestjs/passport
npm ERR!   @nestjs/passport@"*" from the root project

## Expected behavior/code
The passport dependency should work with Nest 8

## Environment
<pre><code>
Nest version: 8.0.0

For Tooling issues:
- Node version: 15.12.0 
- Platform:   MX Linux

**Comment by micalevisk** [comment]
I pretty sure that they will upgrade soon. Also, I think you should move this to https://github.com/nestjs/passport instead.

**Comment by godbrain** [comment]
I see that out there but npm is not pulling that down. It's still not seeing 8. Maybe it's cached somewhere. I'll blow away my nodes folder and see if I get latest. Thanks

**Comment by kamilmysliwiec** [comment]
v8 has just been published
