### ISSUE TITLE
Add Debug Level Logs during provider resolution

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#7465]
## Is your feature request related to a problem? Please describe.

Often times new users to the framework are confused about where the dependency resolution is coming from with the server startup and how dependencies end up getting injected into each dependency.

## Describe the solution you'd like

I'd like to see logs at a `debug` or `verbose` level that can be turned on and off (hence the level) to help describe why dependencies are being injected, where they are pulled from, and what is attempted to be looked at for the dependencies. Ideally something like

```
Resolving dependencies for FooService
Resolving BarService
Searching in FooModule for BarService
Searching in BarModule's exports for BarService
BarService found in BarModule's exports.
BarService Resovled
Resolving BazService
...
```

This may be a bit more verbose than absolutely necessary, and might be a good split between just debug and verbose levels. 

## Teachability, Documentation, Adoption, Migration Strategy

It should be pretty easy to make a mention about this in the docs. And it would be pretty opt-in so it shouldn't harm anyone

## What is the motivation / use case for changing the behavior?

I feel like this will help newcomers and veterans of the framework see how Nest resolves dependencies better and give developers more confidence about what is happening under the covers.

I'm more than happy to work on this, already started with a bit of code actually, but will need some pointers about determining what module the current dependency belongs to. I think I can follow most the rest of the code though.

**Comment by evantrimboli** [comment]
As an addendum to this, there could be some other logs are provider resolution.

I was a bit surprised by the way the DI will automatically alter the scope as necessary to accommodate other dependencies, for example:

```ts
@Injectable({ scope: Scope.DEFAULT }
class MyService {
  constructor(private readonly otherService: RequestScopedService) {}
}
```

I understand why it does so and the behaviour makes sense, however I feel as though it should not do this without a warning at a minimum. My reasoning here is that looking at the code above, it's pretty easy to gloss over the fact that `MyService` would be created on each request, which would be no good if some expensive operation is happening when it gets spun up.

There could possibly even be an opt-in flag to throw an exception which would require the developer to explicitly specify the scoping. I would prefer that, but it would probably be too much of a breaking change.

Thanks for your consideration.

**Comment by kamilmysliwiec** [comment]
Totally agree!

Since some people might be already using the `verbose` and `debug` log levels for logging application-specific stuff (and force adding framework-specific logs on top of that may just spam their terminals), I'm wondering if we should either add a new, dedicated log level (turned off by default) OR even expose a new flag to turn such logs on/off (regardless of specified log levels). What do you think?

**Comment by tak1n** [comment]
> Totally agree!
> 
> Since some people might be already using the `verbose` and `debug` log levels for logging application-specific stuff (and force adding framework-specific logs on top of that may just spam their terminals), I'm wondering if we should either add a new, dedicated log level (turned off by default) OR even expose a new flag to turn such logs on/off (regardless of specified log levels). What do you think?

Hi, pretty new to NestJS and the whole Node.js ecosystem, but from what I've seen so far `DEBUG` environment variable is used quite often to enable verbose debug logs. Eg when setting `DEBUG=*` in my current nest application https://gist.github.com/tak1n/2506892e8ea85049fb0f9f4bf35c242c.

- https://expressjs.com/en/guide/debugging.html
- https://www.prisma.io/docs/concepts/components/prisma-client/debugging

**Comment by jmcdo29** [comment]
To give a quick update on this, I've currently got logs looking like this
![image](https://user-images.githubusercontent.com/28268680/130333510-2086f376-f2c9-4208-bdec-e078d795e700.png)

Right now I've just been modifying the JS with console.logs before going into the TS. I think this pretty well shows what's happening in the resolution phase, and plan to put this behind an env flag like `DEBUG`, maybe `NEST_DEBUG` and just checking for `process.env.FLAG`. The only concern with that would be needing to call `dotenv` off the bat, or starting up the process as `export NEST_DEBUG=true nest start --watch` or similar. 

Any concerns with the above? We can also move the convo to the PR once I have one made

**Comment by kamilmysliwiec** [comment]
This is looking great so far @jmcdo29! Let's track this here https://github.com/nestjs/nest/pull/7910
