### ISSUE TITLE
Documentation Error on https://docs.nestjs.com/websockets/gateways

### ISSUE THREAD

**Issue by yodhcn** [nestjs/nest#7466]
## Bug Report
Documentation Error on https://docs.nestjs.com/websockets/gateways

## Current behavior
Installation#
To start building WebSockets-based applications, first install the required package:
```
$ npm i --save @nestjs/websockets @nestjs/platform-socket.io
$ npm i --save-dev @types/socket.io
```

## Possible Solution
socket.io V4 provides its own type definitions, so you don't need @types/socket.io installed.

**Comment by kamilmysliwiec** [comment]
Fixed!
