### ISSUE TITLE
Cannot Upgrade to Nest 8

### ISSUE THREAD

**Issue by arianlopezc** [nestjs/nest#7476]
## Current behavior
When running nest update -f the update fails. I tried it twice and then the second time it mentions just an exception.

```
Failed to execute command: npm install --save @nestjs/common@latest @nestjs/config@latest @nestjs/core@latest @nestjs/cqrs@latest @nestjs/jwt@latest @nestjs/mongoose@latest @nestjs/passport@latest @nestjs/platform-express@latest @nestjs/throttler@latest
✖ Package installation in progress... ☕
✔ Installation in progress... ☕

nest update -f
▹▹▸▹▹ Installation in progress... ☕
Failed to execute command: npm uninstall --save 
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by michael-golden** [comment]
try with `nest update -f -t latest`

**Comment by arianlopezc** [comment]
Same thing. It returns me the same response. It removes the v7 packages but
when installing the v8 ones, it fails with the output I showed.

**Comment by jmcdo29** [comment]
I can't replicate this with a fresh repo (using nest cli 7.5.6 to install and update)

**Comment by arianlopezc** [comment]
could you try with this set of dependencies?

***@***.***/common": "^7.6.15",
***@***.***/config": "^0.6.3",
***@***.***/core": "^7.6.15",
***@***.***/cqrs": "^7.0.1",
***@***.***/jwt": "^7.2.0",
***@***.***/mongoose": "^7.2.4",
***@***.***/passport": "^7.1.5",
***@***.***/platform-express": "^7.6.15",
***@***.***/throttler": "^1.1.3",
"cache-manager": "^3.4.4",
"class-transformer": "^0.4.0",
"class-transformer-validator": "^0.9.1",
"class-validator": "^0.13.1",

**Comment by jmcdo29** [comment]
I would need a git repo I can clone as a minimum reproduction

**Comment by kamilmysliwiec** [comment]
Instead of using `nest update -f` I'd recommend `npx ncu -u`

**Comment by arianlopezc** [comment]
I also tried that way but it fails when it gets to the nest’s dependencies
saying that it cannot find the dependency tree, even when I do -f to force
it.

**Comment by kamilmysliwiec** [comment]
Remove `node_modules` and reinstall all packages.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
