### ISSUE TITLE
Wrong autoFlushLogs default value?

### ISSUE THREAD

**Issue by gperdomor** [nestjs/nest#7481]
## Current behavior
According the trillon blog [post](https://trilon.io/blog/announcing-nestjs-8-whats-new) and the docs, the default value for `autoFlushLogs` is `true` but in the code is `false`

https://github.com/nestjs/nest/blob/d30403e8d1262f2c46671c60ca30d0c5b70fd456/packages/core/nest-factory.ts#L34

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in v8.0.1
