### ISSUE TITLE
Wrong documentation on task scheduling

### ISSUE THREAD

**Issue by tomer953** [nestjs/nest#7482]
## Current behavior
https://docs.nestjs.com/techniques/task-scheduling#declarative-cron-jobs
in this section, the following code is wrong:
``` typescript
  @Cron(CronExpression.EVERY_45_SECONDS)
  handleCron() {
    this.logger.debug('Called every 45 seconds');
  }
```
Because:
`Property 'EVERY_45_SECONDS' does not exist on type 'typeof CronExpression'. Did you mean 'EVERY_5_SECONDS'?`
## Possible Solution
change to `CronExpression.EVERY_10_SECONDS`
(or one of the other values: https://github.com/nestjs/schedule/blob/renovate/node-14.x/lib/enums/cron-expression.enum.ts )
## Environment

<pre><code>
Nest version: 7.6.0
</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed. Thanks for reporting
