### ISSUE TITLE
The "listener" argument must be of type function. Received an instance of Object

### ISSUE THREAD

**Issue by fireridlle** [nestjs/nest#7483]
## Current behavior
I'm using package `coingecko-api-v3` which internally uses `https` for requests. When i use this package inside service, http module throws an error `The "listener" argument must be of type function. Received an instance of Object`. However, it works when calling it inside a provider

## Minimum code for reproduce

```ts

export const Provider = {
  provide: Name,
  useFactory: () => {
    const coinGeckoClient = new CoinGeckoClient({
      timeout: 10000,
      autoRetry: true,
    });

    coinGeckoClient.exchangeIdTickers({
      id: 'binance',
      page: 1,
    });

    return coinGeckoClient;
  },
};


@Injectable()
export class Service {
  constructor(
    @Inject(CoinGecko.Name) private coinGeckoClient: CoinGeckoClient,
  ) {
    coinGeckoClient.exchangeIdTickers({
      id: 'binance',
      page: 1,
    });
  }
}
```

Or simplify to use only `https` package
```
export const Provider = {
  provide: Name,
  useFactory: () => {
    https
      .request(
        'https://api.coingecko.com/api/v3/exchanges/binance/tickers?id=binance&page=1',
        {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' },
          timeout: 10000,
        },
        console.info,
      )
      .end();
    return {}
  },
};

@Injectable()
class Service() {
constructor() {
    https
      .request(
        'https://api.coingecko.com/api/v3/exchanges/binance/tickers?id=binance&page=1',
        {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' },
          timeout: 10000,
        },
        console.info,
      )
      .end();
}
}
```

## Expected behavior
https.request must worksif called inside service

## Environment

<pre><code>
Nest version: 7.6.15
 
For Tooling issues:
- Node version: 15.14.0
- Platform:  Mac
</code></pre>

**Comment by jmcdo29** [comment]
I don't think this is an error related to Nest. If you can provide a [minimum reproduction](http://minimum-reproduction.wtf) I can take a look, but again I don't think this is Nest related, so I'm going to close this out. For more support, please use [Discord](https://discord.gg/nestjs)
