### ISSUE TITLE
Filters not working with DI

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#7484]
## Current behavior

Filters can't be bound using `@UseFilters()` and DI after upgrading to Nest v8

## Input Code
[Reproduction Repository](https://github.com/jmcdo29/filters-not-executing)

## Expected behavior

I expect DI to still work just fine with filters, just as it already does for pipes, guards, and interceptors

## Possible Solution

I think this is a regression from how the provider resolution happens

## Environment

<pre><code>
[Nest Platform Information]
platform-express version : 8.0.0
common version           : 8.0.0
core version             : 8.0.0
 
For Tooling issues:
- Node version: 14.16.0
- Platform:  Mac and Linux
</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in v8.0.1

**Comment by jmcdo29** [comment]
Confirmed! Thanks for the quick fix on that.
