### ISSUE TITLE
Configuration module not working? 

### ISSUE THREAD

**Issue by parikmaan** [nestjs/nest#7492]
Hi, I am trying to use config `@nestjs/config` module in my nestjs project.

I have configured it in my `app.module.ts` and then used in my controllers in another module. I get `undefined` for the `console.log()` statement.

app.module.ts
```
@Module({
  imports: [
    PostsModule,
    AuthModule,
    UsersModule,
    ThrottlerModule.forRoot({ ttl: 60, limit: 10 }),
    AppCacheModule,
    DatabaseModule,
    ConfigModule.forRoot({ isGlobal: true }),
  ],
  providers: [
    PostsDynamodbFactory,
    UsersDynamodbFactory,
    { provide: APP_GUARD, useClass: ThrottlerGuard },
  ],
})
export class AppModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(RequestLoggerMiddleware).forRoutes('*');
  }
}
```

posts.module.ts
```
@Module({
  imports: [AppCacheModule, DatabaseModule, ConfigModule],
  controllers: [PostsController],
  providers: [PostsService, ImagesService],
})
export class PostsModule {}
```

posts.controller.ts
```
@Controller('posts')
export class PostsController {
  constructor(
    private readonly configService: ConfigService,
  ) {}
 @Get(':yearAndMonth')
  async listByYearAndMonth(
    @Param('yearAndMonth')
    yearAndMonth: string,
  ) {
    console.log(this.configService.get<string>('DATABASE_USER'));
 }
}
```

.env
```
DATABASE_USER=test
DATABASE_PASSWORD=test
```

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by Arnaud-Dev-Nodejs** [comment]
The problem comes from a double configModule imports. The one with the global is enough. But it have to be import before the PostModule. It's supposed to be obvious but it isn't.

So just do this :: 
```
@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    PostsModule,
    AuthModule,
    UsersModule,
    ThrottlerModule.forRoot({ ttl: 60, limit: 10 }),
    AppCacheModule,
    DatabaseModule,
  ],
  providers: [
    PostsDynamodbFactory,
    UsersDynamodbFactory,
    { provide: APP_GUARD, useClass: ThrottlerGuard },
  ],
})
export class AppModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(RequestLoggerMiddleware).forRoutes('*');
  }
}
```

**Comment by parikmaan** [comment]
@jmcdo29  Link to repository - [Minimum reproduction repository](https://github.com/parikmaan/config-issue.git)

Steps:

>Setup
> 1) npm install
> 
>Reproduction
> 1) npm run start:dev
> 2) open new terminal
> 3) curl http://localhost:3000/
> 4) Should display `Hello World!test` but displays `Hello World!undefined`

@Arnaud-Dev-Nodejs I tried but it didn't work.

**Comment by kamilmysliwiec** [comment]
`.env` file should be located in the root directory (not `src`)

**Comment by parikmaan** [comment]
Thanks @kamilmysliwiec
