### ISSUE TITLE
Nest could not find UserService element (this provider does not exist in the current context)

### ISSUE THREAD

**Issue by siavashg87** [nestjs/nest#7494]
## Current behavior
Getting this error on all my tests after upgrading to v 8.0.
Worked fine before the upgrade

## Input Code

```ts
let moduleFixture: TestingModule;
beforeAll(async () => {

    moduleFixture = await Test.createTestingModule({
      imports: [AppModule]
    }).compile();
    app = moduleFixture.createNestApplication();
    userService = moduleFixture.get<UserService>('UserService'); <--------------- error

  });
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
If I had to bet, this is over of how service resolution got updated in v8. Strings no longer map directly to the class, and instead you need to use the class reference for responding the dependency e.g. `moduleFixture.get(UserService)`.

If that does not fix it, or get it to an easily fixable state for you, please provide a [minimum reproduction repository](http://minimum-reproduction.wtf)

**Comment by siavashg87** [comment]
Thank you that fixed te issue.

Also noticed that running nest update does not update devDependensies, so I had to manually update @nestjs/testing.
