### ISSUE TITLE
The autoFlushLogs default is incorrect and does not apply.

### ISSUE THREAD

**Issue by CatsMiaow** [nestjs/nest#7495]
```ts
const app = await NestFactory.create<NestExpressApplication>(AppModule, {
  bufferLogs: true,
});
app.useLogger(app.get(CustomLogger));
```
This code does not output a log even if an error occurs during startup.

```ts
const app = await NestFactory.create<NestExpressApplication>(AppModule, {
  bufferLogs: true,
  autoFlushLogs: true,
});
```
This code works.

https://docs.nestjs.com/techniques/logger#dependency-injection
> you can set the autoFlushLogs to false (default true) to manually flush logs (using the Logger#flush() method).

https://github.com/nestjs/nest/blob/d30403e8d1262f2c46671c60ca30d0c5b70fd456/packages/core/nest-factory.ts#L34
The default doesn't seem to be `true`.
But even if I modify that code it doesn't work.

https://github.com/nestjs/nest/blob/d30403e8d1262f2c46671c60ca30d0c5b70fd456/packages/core/nest-factory.ts#L235-L242
There is no code to apply the default value when `autoFlushLogs` is not passed as an option.

**Comment by kamilmysliwiec** [comment]
Duplicate https://github.com/nestjs/nest/issues/7481
