### ISSUE TITLE
Feature Request: StreamableFile add filename option

### ISSUE THREAD

**Issue by Zclhlmgqzc** [nestjs/nest#7496]
## Is your feature request related to a problem? Please describe.

filepath
xxxx/uuid

real filename
abc.txt

```
reply.header('Content-Disposition', 'attachment;filename=abc.txt').send(
  createReadStream(filePath)
)

=>

return new StreamableFile(createReadStream(filePath), 'abc.txt');
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
