### ISSUE TITLE
Using 5.0.0 @nestjs/swagger would break the nest app

### ISSUE THREAD

**Issue by Haixiang6123** [nestjs/nest#7499]
## Bug Report

Hi, I just started to use Nest.js + Swagger and not sure if this is a bug. I follow the [docs](https://docs.nestjs.com/openapi/introduction) and got this error message:

```
Error: Cannot find module '@nestjs/core/router/route-path-factory'

Require stack:
- /Users/tx-haixiang/workspace/nest-todo/server/node_modules/@nestjs/swagger/dist/swagger-explorer.js
- /Users/tx-haixiang/workspace/nest-todo/server/node_modules/@nestjs/swagger/dist/swagger-scanner.js
- /Users/tx-haixiang/workspace/nest-todo/server/node_modules/@nestjs/swagger/dist/swagger-module.js
- /Users/tx-haixiang/workspace/nest-todo/server/node_modules/@nestjs/swagger/dist/index.js
- /Users/tx-haixiang/workspace/nest-todo/server/node_modules/@nestjs/swagger/index.js
- /Users/tx-haixiang/workspace/nest-todo/server/dist/main.js
```

I can't search any info or solutions on google, so put an issue here.

## Current behavior

Error: Cannot find module '@nestjs/core/router/route-path-factory'

## Input Code

```ts
const startSwagger = (app) => {
  const config = new DocumentBuilder()
    .setTitle('待办事项')
    .setDescription('nest-todo 的 API 文档')
    .setVersion('1.0')
    .addTag('todo')
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('docs', app, document);
};
```

## Expected behavior
No error message.

## Possible Solution
I found the problem is that I was using the latest package `"@nestjs/swagger": "^5.0.0"`. After downgrading to `"@nestjs/swagger": "^4.8.2"`, everyting works fine. Hopefully it could help someone got in the same problem 😅.

## Environment

Nest version: 7.6.15
 
For Tooling issues:
- Node version: v12.18.2
- Platform:  MacOS Catalina 10.15.6

Others: nope

**Comment by kamilmysliwiec** [comment]
Swagger v5 is compatible with Nest v8 (`@nestjs/core@^8.0.0`, `@nestjs/common@^8.0.0` etc)
Swagger v4 is compatible with Nest v7

**Comment by Haixiang6123** [comment]
> Swagger v5 is compatible with Nest v8 (`@nestjs/core@^8.0.0`, `@nestjs/common@^8.0.0` etc)
> Swagger v4 is compatible with Nest v7

thx.

**Comment by j314h** [comment]
hello, 

I still have the same concerns, here is my package.json

```json
 "dependencies": {
    "@nestjs/common": "^8.0.5",
    "@nestjs/config": "^1.0.1",
    "@nestjs/core": "^8.0.5",
    "@nestjs/mapped-types": "^1.0.0",
    "@nestjs/mongoose": "^8.0.0",
    "@nestjs/platform-express": "^8.0.5",
    "@nestjs/swagger": "^5.0.9",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "mongoose": "^5.13.5",
    "mongoose-autopopulate": "^0.14.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.1.6"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^26.0.24",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@types/mongoose-autopopulate": "^0.10.2",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-config-woopear": "^1.0.5",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "27.0.6",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
```

my versions are OK.
I have all tested

example :
`app.enableVersioning ();`
in main.ts file
does not work
here is the error
Property 'enableVersioning' does not exist on type 'INestApplication'

do you have a lasting solution ? TH
