### ISSUE TITLE
Impossible to inject data in ejs from interceptor

### ISSUE THREAD

**Issue by Arnaud-Dev-Nodejs** [nestjs/nest#7502]
## Bug Report
Missing data in variable "locals" in ejs engine.

## Current behavior
The data injected in res.locals is supposed to appear in the ejs page rendering but nothing appear.
Please note the res.render('error', {someData}) was called in an ExceptionFilter (Pop up after Interceptor invocation).
the Observable with next.handle() ignored the modification of "res".

## Input Code

```ts
@Injectable()
export class ExceptionInterceptor implements NestInterceptor {
  constructor(
    private readonly logger: LoggerService,
    protected readonly config: ConfigService,
  ) {
    this.logger.setContext(this.constructor.name);
  }

   myTestFunction(host: ArgumentsHost) {
    const res = host.switchToHttp().getResponse();
    const { exception } = res.locals;
    const session = this.configService.getCurrentSession(host)
    res.locals.session = session;  // <=== here
     res.locals.exception = exception;// <== here
    this.logger.trace({ locals: res.locals });
  }
  async intercept(
    host: ExecutionContext,
    stream$: CallHandler,
  ): Promise<Observable<any>> {
    this.logger.debug('RedirectSpInterceptor: intercept()');
    this.logger.trace({ host, stream$ });

    return stream$.handle().pipe(
        tap(() => {
          this.myTestFunction(host);
       }),
     );
  }
}

```
in the ExceptionFilter ::
```ts
  protected async renderError(
    host: ArgumentsHost,
    exception: Error,
    statusCode = HttpStatus.INTERNAL_SERVER_ERROR,
  ) {
    this.logger.trace({ exception, statusCode });

    const informations = this.getInformationsFromException(exception);

    const res = host.switchToHttp().getResponse();

    res.locals.exception = exception;

    res.status(statusCode);
    res.render('error', {
      ...informations,
    });
  }
```

## Expected behavior
res.locals in 'ejs' must contains information.

## Possible Solution
adapt order between interceptors and ExceptionFilter

## Environment

<pre><code>
Nest version: 7.0.7
 
For Tooling issues:
- Node version: 14.xx 
- Platform:  Linux 
- PackageManager : yarn
</code></pre>

**Comment by kamilmysliwiec** [comment]
> adapt order between interceptors and ExceptionFilter

We don't plan to change the execution order.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
