### ISSUE TITLE
Support for resiliency patterns

### ISSUE THREAD

**Issue by bhupatikrish** [nestjs/nest#7504]
## Often times many NestJs apps connect to backend systems. It would be nice to have NestJs support certain resiliency patterns (circuit breaker, retry, bulkhead etc) that help in a large distributed environments. 

Many frameworks have support for resiliency patterns.
Few examples are, 
- Springboot: https://resilience4j.readme.io/
- .Net: https://github.com/App-vNext/Polly

[cockatiel](https://www.npmjs.com/package/cockatiel) is a JayaScript library that does support most of resiliency patterns. It would be great if NestJs provide similar resiliency patterns.

It would be powerful for teams to build dashboards using these resiliency patterns.

**Comment by jmcdo29** [comment]
Can't this be integrated already, or am I missing something? Are you just wanting this baked into the framework instead of having to integrate it yourself?

**Comment by bhupatikrish** [comment]
Yes, I was hoping NestJs can bake it into the framework with simpler annotations.

**Comment by kamilmysliwiec** [comment]
You should be able to implement & apply most of that patterns with Nest using, for example, interceptors (~1-2 files per pattern). There's no reason to provide annotations for that.
