### ISSUE TITLE
Doc for gRPC options is misleading

### ISSUE THREAD

**Issue by archana-maharjan** [nestjs/nest#7506]
Advance apology, if implementation at my end is causing issue!!!
## Bug Report
"credentials" in gRPC options points to [GRPC.ServerCredentials](https://grpc.github.io/grpc/node/grpc.ServerCredentials.html), which throws TypeError with message "Channel credentials must be a ChannelCredentials object" error, however, if used GRPC.credentials then throws TypeError with message "creds._getSettings is not a function".

## Current behavior
[gRPC Doc](https://docs.nestjs.com/microservices/grpc) provides neither good documentation on credentials nor working example.

## Input Code
[grpc-mtls](https://github.com/archana-maharjan/grpc-mtls)

```ts
export const grpcClientOptions: ClientOptions = {
  transport: Transport.GRPC,
  options: {
    package: 'hero',
    protoPath: join(__dirname, './hero/hero.proto'),
    credentials: credentials.createSsl(
      fs.readFileSync(join(process.cwd(), "certificates", "ca-cert.pem")), 
      fs.readFileSync(join(process.cwd(), "certificates", "server-key.pem")), 
      fs.readFileSync(join(process.cwd(), "certificates", "server-cert.pem")))
    // credentials: ServerCredentials.createSsl(
    //     fs.readFileSync(join(process.cwd(), 'certificates', 'ca-cert.pem')),
    //     [
    //       {
    //         private_key: fs.readFileSync(
    //           join(process.cwd(), 'certificates', 'server-key.pem'),
    //         ),
    //         cert_chain: fs.readFileSync(
    //           join(process.cwd(), 'certificates', 'server-cert.pem'),
    //         ),
    //       },
    //     ],
    //     true,
    //   )
  },
};
```

## Expected behavior
Should provide good documentation on credentials options or a good example, or resolve aforementioned TypeError.

## Environment

<pre><code>
Nest version: 8.0.0

 
For Tooling issues:
- Node version: 14.16.1  
- Platform: Mac 

Others:
- Visual Studio Code: 1.57.1
- Yarn: 1.22.10
- macOS Big Sur: 11.4

</code></pre>

**Comment by geek96** [comment]
https://github.com/archana-maharjan/grpc-mtls
Sample code repository is not available.

**Comment by kamilmysliwiec** [comment]
Please, make the repository publicly available

**Comment by archana-maharjan** [comment]
@geek96 , @kamilmysliwiec repo is public!

**Comment by archana-maharjan** [comment]
@kamilmysliwiec  @geek96 repo's public, and I wonder what other information you require to take a look at the issue. Just in case if you're looking for certificates, then please create "certificates at the root folder and add certificates that is generated using following commands or your own.

1. Generate CA's private key and self-signed certificate
    openssl req -x509 -newkey rsa:4095 -days 365 -nodes -keyout ca-key.pem -out ca-cert.pem
 2. Generate web server's private key and certificate signing request (CSR)
    openssl req -newkey rsa:4096 -nodes -keyout server-key.pem -out server-req.pem
3. Create server-ext.cnf file and add following content in the file
   subjectAltName=DNS:*.domainName.com,DNS:*.domainName.org,IP:0.0.0.0
4. Use CA's private key to sign web server's CSR and get back the signed certificate
    openssl x509 -req -in server-req.pem -days 60 -CA ca-cert.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile server-ext.cnf

Or else you can also generate certificates other way as follow:
Note: Please replace Your Country, Your State, Your Organization with appropriate values.
         // Create certificates.conf file and add following contents in it.
            [req]
            default_bits = 4096
            prompt = no
            default_md = sha256
            req_extensions = req_ext
            distinguished_name = dn
            [dn]
            C = Your Country
            ST = Your State
            O = Your Organization
            CN = localhost
            [req_ext]
            subjectAltName = @alt_names
            [alt_names]
            DNS.1 = localhost
            IP.1 = ::1
            IP.2 = 127.0.0.1
          // Create Root signing Key
          -- openssl genrsa -out ca.key 4096
          // Generate self-signed Root certificate
          -- openssl req -new -x509 -key ca.key -sha256 -subj "/C=Your Country/ST=Your State/O=Your Organization" -days 365 -out ca.cert
          // Create a Key certificate for the Server
          -- openssl genrsa -out service.key 4096
          // Create a signing CSR, note create conf file with
          -- openssl req -new -key service.key -out service.csr -config certificates.conf
          // Generate a certificate for the Server
          -- openssl x509 -req -in service.csr -CA ca.cert -CAkey ca.key -CAcreateserial -out service.pem -days 365 -sha256 -extfile certificates.conf -extensions req_ext

Please let me know if you need more info?

**Comment by kamilmysliwiec** [comment]
I checked out your repository and it seems that this issue is unrelated to NestJS but rather to the underlying `@grpc/grpc-js` package. Please, report this issue in their repository https://github.com/grpc/grpc-node

**Comment by archana-maharjan** [comment]
Thank you!!!
