### ISSUE TITLE
HTTP module with Axios

### ISSUE THREAD

**Issue by ArneTesch** [nestjs/nest#751]
Hello all,

I have some difficulties with the HTTP Module in Nest.js

I tried to refactor my current project, that worked and used the Schema and Model approach.
But I am getting an 500 error code when making a GET request to my local MongoDb.

**Error:**
Error: Request failed with status code 500
    at createError (.../node_modules/axios/lib/core/createError.js:16:15)
    at settle (.../node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (.../node_modules/axios/lib/adapters/http.js:192:11)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
^C[ExceptionsHandler] Request failed with status code 500

Here is my code:
**- product.service.ts**
```
import { HttpService, Injectable } from '@nestjs/common';
import { AxiosResponse } from 'axios';
import { Observable } from 'rxjs';

import { Product } from './interfaces/product.interface';

@Injectable()
export class ProductService {
  constructor(private readonly http: HttpService) {}

  url = 'http://localhost:3000/products';

  create(product: Product): Observable<AxiosResponse<Product>> {
    return this.http.post(this.url, product);
  }

  findAll(): Observable<AxiosResponse<Product[]>> {
    return this.http.get(this.url);
  }
}
```

**- products.controller.ts**

```
import {
  Body,
  Controller,
  Get,
  Post,
} from '@nestjs/common';

import { Product } from './interfaces/product.interface';
import { ProductService } from './product.service';

@Controller('products')
export class ProductsController {
  constructor(private readonly productService: ProductService) {
  }

  @Get()
  findAll() {
    return this.productService.findAll();
  }

  @Post()
  create(product: Product) {
    this.productService.create(product);
  }
}
```

**Comment by kamilmysliwiec** [comment]
See here: https://stackoverflow.com/questions/50355670/nestjs-returning-the-result-of-an-http-request

**Comment by ArneTesch** [comment]
Hi @kamilmysliwiec ,

Thanks for your help!

But this didn't fix my problem. I still get an error -> 
{
"statusCode": 500,
"message": "Internal server error"
}

The error is not caused by the error explained in the Stackoverflow issue.
**_TypeError: Converting circular structure to JSON at JSON.stringify () at stringify_** 

I guess I am still doing something wrong in my service or controller.
Or  the implementation of MongoDb is wrong...

**- AppModule**
```
import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { ProductsModule } from 'products/products.module';
import { Mongoose } from 'mongoose';

@Module({
  imports: [
    MongooseModule.forRoot(
      'mongodb://localhost/items',

    ),
    ProductsModule,
  ],
})
export class AppModule {}

```

**- ProductsModule**
```
import { Module, HttpModule } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';

import { ProductSchema } from './schemas/product.schema';
import { ProductService } from './product.service';
import { ProductsController } from './products.controller';

@Module({
  imports: [
  MongooseModule.forFeature([
      {
        name: 'Product',
        schema: ProductSchema,
      },
    ]),
    HttpModule,
  ],
  controllers: [ProductsController],
  providers: [ProductService],
})
export class ProductsModule {}
```

**Comment by unstephenk** [comment]
I am also getting this error. Were you able to resolve it?

**Comment by Tolga-FNT** [comment]
I also have this issue! 500 Internal server error.....!!!!!

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
