### ISSUE TITLE
Logger passed to microservice crash application

### ISSUE THREAD

**Issue by Satont** [nestjs/nest#7528]
## Describe the regression
I have this setup:

```json
"@nestjs/common": "^8.0.0",
"@nestjs/core": "^8.0.0",
"@nestjs/microservices": "^8.0.0",
```

And some of from `common` or `core` modules makes application crash with followed error: 
```
1: 0xb200e0 node::Abort() [node]
 2: 0xb92e89  [node]
 3: 0xd6fc5b  [node]
 4: 0xd7110c  [node]
 5: 0xd71786 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 6: 0x1640919  [node]
 ```
 
If i remove `logger` option, then it's works.
 
If i downgrade `core` and `common` to `7.6.15`, then it's also works. I mean passing logger not crashing my application.

## Input Code
```ts
const app = await NestFactory.createMicroservice<MicroserviceOptions>(AppModule, {
    logger: new Logger(),
    options: {
      port: 3004,
    },
});

await app.listen();
```

## Expected behavior/code

Atleast correct log of error, or even fix of some bug.
## Environment
<pre><code>
Nest version: 7.6.15 -> 8.0.0

For Tooling issues:
- Node version: v16.4.2
- Platform:  arch, `Linux 5.12.15-arch1-1`
Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in v8.0.2
