### ISSUE TITLE
command line [--max-http-header-size] options doesn`t work 

### ISSUE THREAD

**Issue by mfoonirlee** [nestjs/nest#7532]
## Current behavior
we have a request with 30kb header, but it doesn't work when we add command line option  `--max-http-header-size`,then we get a 431 http status code.

## Input Code

```ts
nest start -- --max-http-header-size=32768
```

## Expected behavior
http status code is 200

## Environment

<pre><code>
Nest version: X.Y.Z

@nestjs/cli: 7.6.0
@nestjs/core: 7.6.18
node: 
For Tooling issues:
- Node version:  14.17.1 
- Platform:  Mac OS 11.4 chrome 91.0.4472.114

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
