### ISSUE TITLE
 Cannot use namespace 'ClassDeclaration' as a type.

### ISSUE THREAD

**Issue by ITmonkey-cn** [nestjs/nest#7534]
node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:1:58 - error TS2307: Cannot find module '@apollo/gateway' or its corresponding type declarations.

1 import { GatewayConfig, ServiceEndpointDefinition } from '@apollo/gateway';
                                                           ~~~~~~~~~~~~~~~~~
node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:2:35 - error TS2307: Cannot find module '@apollo/gateway/dist/datasources/types' or its corresponding type declarations.

2 import { GraphQLDataSource } from '@apollo/gateway/dist/datasources/types';

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/1621
