### ISSUE TITLE
[Feature Request] JwtAuthGuard: support WebSockets as well as Http

### ISSUE THREAD

**Issue by vahidvdn** [nestjs/nest#7542]
## Is your feature request related to a problem? Please describe.
JwtAuthGuard that extends `AuthGuard('jwt')` works in a way that token should exist in HTTP header.  But we can set a header in WS as well. Although there is a tricky way to extract the header from WS and attach it to HTTP's header manually, so nestjs can go on and handle it, still, it's not an ideal way.

Also, there is another problem with the Strategy class. In HTTP base, in Strategy class, I can return payload in `verify` method, then nestjs can set it in the `req`. I don't know how to access the `context` in order to set the payload to WS body.

## Describe the solution you'd like
It would be ideal that nestjs supports it under the hood. So, when I set the header in WS with the same format: "Authorization": "Bearer {token}", so nestjs can extract it, decode it, and set the payload to WS

## What is the motivation / use case for changing the behavior?
To have the same pattern without having to decode the token manually.

**Comment by jmcdo29** [comment]
Passport is an HTTP middleware. It's possible to make it work with websockets, graphql, and RPC, but it requires you to write some code for `getRequest`. There's nothing Nest needs to do for this. Please use our [Discord](https://discord.gg/nestjs) for Support.
