### ISSUE TITLE
Strange folder structure under dist/ after build

### ISSUE THREAD

**Issue by jbeckton** [nestjs/nest#7561]
## Bug Report

Using the Nest CLI generate a new app. Then generate a library inside the new app. Then generate a second app to convert the nest project into a monorepo. The project should now have two apps and one library. Consume your library from both apps, via imports. The specific implementation of your apps and library are irrelevant.

Disable webpack in the nest-cli.json file and then run nest build command. I don't really need webpack bundles for a node server app. I did not notice this issue while webpack was enabled.

## Current behavior

after building one of the apps the dist/ folder structure is as follows.

![dist](https://user-images.githubusercontent.com/2669585/125546242-7cccd820-63ae-4615-b0f7-3fb5f800dfa6.png)

## Expected behavior

I would expect the dist folder to look more like the app src directory structure

dist
- apps
- - my-app
- - - my-controller.js
- - - my-lib
- - - - some-service.js

## Environment

<pre><code>
Nest version: 8.0.0

 
For Tooling issues:
- Node version: 16
- Platform:  Mac

Others:

vs code
</code></pre>

**Comment by jmcdo29** [comment]
This is how Typescript builds applications when there are ts files in more than just the folder being built. Usually if you have something like

```ts
src/
  main.ts
config.ts
```

You'll end up with a dist like
```ts
dist
  src/
    main.js
  config.js
```

The above is pretty much expected depending on what your `outDir` looks like and what your config is.

**Comment by jbeckton** [comment]
Unfortunately if i set the outDir in my app project tsc doesn't like the fact that the lib code is outside of the rootDir. I guess I'll just keep using webpack. I read the webpack team is planning to release a feature that allows you to disable the bundling and it just produces single files much like tsc does.
