### ISSUE TITLE
console.log() and Logger.log  no  output ?

### ISSUE THREAD

**Issue by RobinYang11** [nestjs/nest#7571]
![image](https://user-images.githubusercontent.com/20513480/125716796-44e2f269-1f68-4e61-bcc8-c622330f46ef.png)

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

If you think this is a bug, please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).
