### ISSUE TITLE
app.listen method blocks execution with Fastify adapter

### ISSUE THREAD

**Issue by gperdomor** [nestjs/nest#7572]
## Describe the regression
The logger message never show up in the console with Nest 8 and Fastify Adapter

## Input Code

```ts
async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());

  await app.listen(3000);
  Logger.log(`🚀 Application is running on: ${await app.getUrl()}`);
}

bootstrap();
```

## Expected behavior/code
The log message should be appear in the console like does with ExpressAdapter or Nest 7

## Environment
<pre><code>
Nest version: 8.0.2

For Tooling issues:
- Node version: 16.4.2
- Platform:  Mac
Others:

</code></pre>

**Comment by micalevisk** [comment]
https://github.com/nestjs/nest/issues/7571#issuecomment-880338045

**Comment by gperdomor** [comment]
It was a duplicated route which cause the issue so I will close this...

```ts
  @Get() <---- this
  getData() {
    return this.appService.getData();
  }

  @UseGuards(AuthorizationGuard)
  @Get() <---- this
  getPrivateData(@Req() req) {
    return this.appService.getData();
  }
```

**Comment by lolo32** [comment]
No, it's not the same, because it's working without any header API versioning
