### ISSUE TITLE
Getting error message when trying to staring nestjs microservice

### ISSUE THREAD

**Issue by 4RSIM3R** [nestjs/nest#7573]
## Bug Report

Hello, i just write a simple implementation of nest.js microservice with official package

## Input Code

```ts
async function bootstrap() {
  const app = await NestFactory.createMicroservice<MicroserviceOptions>(AppModule, {
    transport: Transport.TCP
  })
  app.listen(() => console.log('First Service Started'))
}

bootstrap();
```

## Expected behavior
I expected this code will running, because I write this code with official documentation reference.
but I getting this error message : 

```
G:\nesan\first-service\node_modules\@nestjs\microservices\nest-microservice.js:88
TypeError: this.flushLogs is not a function
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: 12
- Platform: windows

**Comment by jmcdo29** [comment]
Are all of your nest deps on the same major version?

**Comment by Limsanity** [comment]
> Are all of your nest deps on the same major version?

After the downgrade `@nestjs/microservices` to `^7.0.0`，it works.

**Comment by kamilmysliwiec** [comment]
`@nestjs/core` version must be in sync with the `@nestjs/microservices`
