### ISSUE TITLE
ValidationPipe bug on type `string[]`

### ISSUE THREAD

**Issue by willin** [nestjs/nest#7574]
## Bug Report

ref https://github.com/nestjs/swagger/issues/1452

## Input Code

```ts
// class field specification
  @ApiProperty({ type: [String] })
  readonly hidden_fileds: string[];
```

## Expected behavior

i pass in a object (not valid string array), it passed.

```bash
curl -X POST "http://example.com/role" -H  "accept: application/json" -H  "x-api-key: xxxx" -H  "Content-Type: application/json" -d \
 "{\"hidden_fileds\":{\"test\":1},\"username\":\"test\"}"
```

which should return 400 error 

## Possible Solution

upgrade ValidationPipe function

## Environment

<pre><code>
Nest version: 7.6.0

 
For Tooling issues:
- Node version: 16.4.2  
- Platform: Linux  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
The swagger decorators do not do anything for `class-validator` or the `ValidationPipe`. Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
