### ISSUE TITLE
ValidationPipe with transformation to throw error when unknown option is send

### ISSUE THREAD

**Issue by spiotr12** [nestjs/nest#7580]
## Feature Request
When I setup ValidationPipe, so it validates whitelisted AND transforms to classes I would like that the validation would happen before transformation, so it throws 400 BAD_REQUEST.

Example

```typescript
// main.ts (ValidationPipe configuration)
app.useGlobalPipes(new ValidationPipe({
  // Validation (class-validator)
  whitelist: true,
  forbidNonWhitelisted: true,
  forbidUnknownValues: true,
  // Transformation (class-transformer)
  transform: true,
  transformOptions: {
    excludeExtraneousValues: true,
  },
}));
```
```typescript
// update.dto (DTO configuration)
import { Expose } from 'class-transformer';
import { Allow, IsOptional } from 'class-validator';

export class UpdateObjectDto {
  @Expose()
  @Allow()
  @IsOptional()
  public name: string | undefined;

  @Expose()
  @Allow()
  @IsOptional()
  public icon: string | undefined;
}
```

And when I send request I would expect to get 400 BAD_REQUEST:
```http
PUT http://localhost:3000/objects
Content-Type: application/json

{
  "name": "value",
  "icon": "icon",
  "unknownOption": "any", // <-- This should throw
}
```

## Describe the solution you'd like
If both validation and transformation is set I would like the validation to happen BEFORE transformation

## What is the motivation / use case for changing the behavior?
I want to transform objects to DTO classes (as I might have dedicated methods there) but still tell the API user that the request was wrong because he/she sent the object with unknown/forbidden properties

**Comment by jmcdo29** [comment]
Validations via class-validator **cannot** happen before the transformation, because there's no class created and therefor no metadata for class-validator to make use of. The transformation from plain JSON object has to happen before sending the class instance on to `validate` from `class-validator`. By using `excludeExtraneousValues`, you're already stripping unknown values
