### ISSUE TITLE
Cache TTL set to 0/null is not keeping the cache

### ISSUE THREAD

**Issue by nolawnchairs** [nestjs/nest#7581]
## Bug Report

Cache will not set a null TTL. In version 7, setting ttl to `null` and after upgrading to version 8, setting ttl to `0`. Your documents say: 

To disable expiration of the cache, set the ttl configuration property to 0

## Current behavior
When setting cache to have a TTL of 0, it disobey and clears after 5 seconds still.

```ts
// Module
@Module({
  imports: [
    TypeOrmModule.forFeature([Admin]),
    CacheModule.register(),
  ],
  providers: [AdminService],
  controllers: [AdminController]
})
export class AdminModule { }

// Service
@Injectable()
export class AdminService implements OnModuleInit {

  constructor(
    @Inject(CACHE_MANAGER) private cacheManager: Cache,
    @InjectRepository(Admin) private repository: Repository<Admin>) { }

  async onModuleInit() {
    const admins = await this.repository.find()
    this.cacheManager.set('admins', admins, { ttl: 0 })
  }

  async create(data: CreateAdminDto): Promise<Admin> {
    const cached = await this.cacheManager.get<Admin[]>('admins') ?? []
    console.log(cached) // -> []
    // code omitted
  }
}
```

The documentation say to set the value to `0`, but he says on version 7 to set it to `null`. I try both ways on both version (before and after upgrade) and still the same problem is there. The cache does not stay in the memory

## Expected behavior
Memory cache to stay forever or unless I ask to clear it

## Possible Solution
Possible false equivalency? e.g. `value || 5` instead of `value ?? 5`. In JavaScript, value 0 is also false equivalent, so maybe it is interpret my `0` value as false, so the default value of 5 is being used instead of this. Using `??` will check if null or undefined so will keep the `0` as a intended value.

## Environment

<pre><code>
Nest version: 7.6.13 and 8.0.3
 
For Tooling issues:
- Node version: 14
- Platform:  Linux

Others:
"cache-manager": "^3.4.4"
</code></pre>

**Comment by micalevisk** [comment]
https://github.com/nestjs/nest/issues/6870#issuecomment-817178920

**Comment by ehaynes99** [comment]
Should the docs be updated, then?

https://docs.nestjs.com/techniques/caching

> To disable expiration of the cache, set the ttl configuration property to 0:

```typescript
await this.cacheManager.set('key', 'value', { ttl: 0 });
```
