### ISSUE TITLE
Perhaps should add some property decorator like @NotBlank/NotNull/NotEmpty

### ISSUE THREAD

**Issue by jingyuexing** [nestjs/nest#7594]
## Is your feature request related to a problem? Please describe.
I want to limit the validity of the data and return errors to the front end when they do not comply

## Describe the solution you'd like
Decorators that provide some field detection

## Teachability, Documentation, Adoption, Migration Strategy
```ts
import { Prop , NotBlank, NotNull, NotEmpty} from "@nestjs/mongoose";

export class User{
  @Prop()
  @NotBlank(message="some error information")
  name:string;

  @Prop()
  @NotBlank(message="must is not blank string")
  password:string;
}

```
```ts
import "reflect-metadata";

const NotBlankMetadataKey = Symbol("NotBlank");

function NotBlank(message: string) {
    return Reflect.metadata(NotBlankMetadataKey, CheckIsNotBlank);
}
```
## What is the motivation / use case for changing the behavior?

# Let's be more spring style

**Comment by jmcdo29** [comment]
1) NestJS does not strive to be like Spring. They're different frameworks in different languages. They may draw from similar ideas, but they are separate and different approaches

2) this sounds like a perfect use case for the `ValidationPipe` and integrating with `class-validator` instead of rolling our own validations. Is there a reason that approach isn't valid in this scenario?

**Comment by jingyuexing** [comment]
> 
> 
>     1. NestJS does not strive to be like Spring. They're different frameworks in different languages. They may draw from similar ideas, but they are separate and different approaches
> 
>     2. this sounds like a perfect use case for the `ValidationPipe` and integrating with `class-validator` instead of rolling our own validations. Is there a reason that approach isn't valid in this scenario?

I reread the document, and maybe installing class-validator on the document solves the problem of detecting the legitimacy of the data, but class-validator is not available for detection,like NotBlank,NotNull,etc

**Comment by Zclhlmgqzc** [comment]
> I reread the document, and maybe installing class-validator on the document solves the problem of detecting the legitimacy of the data, but class-validator is not available for detection,like NotBlank,NotNull,etc

see [custom-validation-decorators](https://github.com/typestack/class-validator#custom-validation-decorators)

**Comment by jmcdo29** [comment]
> but class-validator is not available for detection, like NotBlank, NotNull,

I mean, for a catch all there `@IsNotEmpty()` which matches `''`, `null`, and `undefined`. Then for `NotBlank` you could do `@MinLength(1)`. Or as mentioned by @Zclhlmgqzc you could make a custom decorator for it. There's no need for Nest to provide extra validations on a library that already exists.
