### ISSUE TITLE
File upload with `FilesInterceptor` throws 400 Bad Request

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#7602]
## Current behavior
Using `FilesInterceptor()`, following the [docs](https://docs.nestjs.com/techniques/file-upload#array-of-files), throws a Bad Request error `400` with message `Unexpected field`.

## Input Code

```ts
@Post('upload')
@UseInterceptors(FilesInterceptor('files'))
uploadFile(@UploadedFiles() files: Array<Express.Multer.File>) {
  console.log(files);
}
```

Frontend:

```js
    const formData = new FormData();

    files.forEach(file => {
      formData.append('files', file);
    });

    const response = await fetch('http://localhost:3000', {
        method: 'POST',
        body:   formData,
    });
```

## Reproduction repo
Link: Reproduction Repo: https://github.com/MickL/nestjs-multer-400

- yarn install
- yarn start
- Open ./index.html
- Select one file -> Contoller logs `undefined` instead of file array
- Select multiple files -> Frontend shows 400 error

## Environment

<pre><code>
Nest version: 8.0.4
 
For Tooling issues:
- Node version: 14.17.0
- Platform:  macOS Big Sur
</code></pre>

**Comment by MickL** [comment]
Works as expected. I have used `FileInterceptor` instead of `FilesInterceptor`

**Comment by brenoccamp** [comment]
I have the same problem.
Does someone know why it happens?
Here is my controller:
```
  @Post('update-massive')
  @UseInterceptors(FileInterceptor('file'))
  async updateMassiveDevice(@UploadedFile() file: Express.Multer.File): Promise<any> {
    console.log('controller started')
```
But log never out. Postman shows followed:
`{
    "statusCode": 400,
    "message": "Unexpected field",
    "error": "Bad Request"
}`
