### ISSUE TITLE
Enable shutdown hooks may cause the app will not exit

### ISSUE THREAD

**Issue by ZanMinKian** [nestjs/nest#7611]
## Current behavior
When client's http request headers includes `Connection: keep-alive`, request from new http connection will be refused. But it will not refuse connection which established, and the app will reponse with headers `Keep-Alive: timeout=5`. The app will not shutdown if client request frequently using established connection.

## Expected behavior
After call `app.close()`, app response contains headers: `Connection: close`.

## Environment

<pre><code>
Nest version: 7.6.11
 
For Tooling issues:
- Node version: 12.22.1
- Platform: Mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
This is how Node.js Net server works https://nodejs.org/api/net.html#net_server_close_callback. 

> Stops the server from accepting new connections and keeps existing connections. This function is asynchronous, the server is finally closed when all connections are ended and the server emits a 'close' event. The optional callback will be called once the 'close' event occurs. Unlike that event, it will be called with an Error as its only argument if the server was not open when it was closed.

To force close all connections, check out this link https://stackoverflow.com/questions/18874689/force-close-all-connections-in-a-node-js-http-server

(to retrieve the underlying HTTP server from the Nest application, check out this chapter https://docs.nestjs.com/faq/http-adapter)
