### ISSUE TITLE
Router module docs example is wrong

### ISSUE THREAD

**Issue by TimurAztec** [nestjs/nest#7612]
## Current behavior
https://docs.nestjs.com/recipes/router-module
In first code snippet there is no mention that you have to add DashboardModule to imports before RouterModule

## Input Code

```ts
@Module({
  imports: [
    RouterModule.register([
      {
        path: 'dashboard',
        module: DashboardModule,
      },
    ]),
  ],
})
export class AppModule {}
```

## Expected behavior
To have dashboard accessible on http://localhost:3000/dashboard

## Possible Solution
Change docs code snippet to 
```ts
@Module({
  imports: [
    DashboardModule,
    RouterModule.register([
      {
        path: 'dashboard',
        module: DashboardModule,
      },
    ]),
  ],
})
export class AppModule {}
```
And add mention that you have to change ```@Controller('dashboard')``` to ```@Controller()``` inside dashboard.controller.ts

**Comment by kamilmysliwiec** [comment]
> And add mention that you have to change @Controller('dashboard') to @Controller() inside dashboard.controller.ts

This should be obvious.

As for importing the `DashboardModule`, sounds good. Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/1973
