### ISSUE TITLE
Wildcard Routing Causing Constant 100% CPU Usage on Linux Server

### ISSUE THREAD

**Issue by ModestosV** [nestjs/nest#7625]
## Current behavior
When using wildcard routing with the `@Get` Decorator, CPU usage stays at a constant 100% immediately after launching the application. Replacing the wildcard with any other string that does not contain a wildcard does not cause this issue. The performance of the application seems okay despite the 24/7 100% CPU usage, but it is still strange that this occurs.

My use case is as follows, I have a bunch of sitemaps that contain a similar structure. When the endpoint starts with 'sitemap' and ends with 'xml', I want to hit a specific endpoint. Below are all the decorators I use along with the function signature.

The code being run generates a sitemap with a few hundred thousand lines, but when I replace the wildcard route with a hardcoded route, the same code executes just fine and CPU Usage is normal.

## Input Code

```ts
    @Get('sitemap*xml')
    @Header('content-type', 'application/xml')
    @Header('content-encoding', 'gzip')
    getSitemap(@Req() request: Request, @Res() response: Response) {
        .....
    }
```

## Expected behavior

CPU Usage should not be 100%.

## Environment

<pre><code>
Nest version: 7.6.17

 
For Tooling issues:
- Node version: v14.17.0 
- Platform:  1 GB Memory / 25 GB Disk - Ubuntu 18.04.3 (LTS) x64

Others:

    "@nestjs/common": "^7.6.17",
    "@nestjs/core": "^7.6.17",
    "@nestjs/ng-universal": "^4.3.0",
    "@nestjs/platform-express": "^7.6.17"
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by ModestosV** [comment]
From the link you sent me "_half the time while creating the minimum reproduction, you’ll find what the problem was yourself_ "... This was the case, thanks for that.
