### ISSUE TITLE
In Logger, the error stack goes to the next line.

### ISSUE THREAD

**Issue by CatsMiaow** [nestjs/nest#7626]
- @nestjs/common: ^8.0.4
- @nestjs/core: ^8.0.4

I cloned [typescript-starter](https://github.com/nestjs/typescript-starter) and tested it.
```ts
import { Controller, Get, Logger } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  private readonly logger: Logger = new Logger(AppController.name);

  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    this.logger.error({ test: 'foo', foo: 'bar' });
    this.logger.error('Test1');
    this.logger.error('Test2', 'TestStack');

    // It happens on this line.
    this.logger.error('Test3', 'TestStack', 'TestContext');

    return this.appService.getHello();
  }
}
```
![image](https://user-images.githubusercontent.com/1300172/126592025-edbab230-6590-4067-9cb1-3d8d9b6be687.png)

https://github.com/nestjs/nest/blob/bddecac3a73e628dfe2a0202ea3000f47f0cc69e/packages/common/services/console-logger.service.ts#L176
It seems to contain `stack` inside `messages`.

**Comment by kamilmysliwiec** [comment]
Your logger has the context already specified in this line:

```typescript
private readonly logger: Logger = new Logger(AppController.name);
```

so this:

```typescript
this.logger.error('Test3', 'TestStack', 'TestContext');
```

will be interpreted as `[message, message, stack]` instead.

This is the expected behavior.
