### ISSUE TITLE
`moduleRef` injection gives undefined in parent module

### ISSUE THREAD

**Issue by rcarcasses** [nestjs/nest#7628]
## Current behavior
`moduleRef` is undefined in parent module.

## Input Code

See [repo](https://github.com/rcarcasses/nest-8.0.0-moduleref-bug)

## Expected behavior
`moduleRef` should not be `undefined`.

## Possible Solution
No idea

## Environment

Nest version: 8.0.4

 
For Tooling issues:
- Node version: 14.15.4
- Platform:  all

Others:

I'm currently developing a `nestjs` library whose code can be utilized from a `nestjs` app. I have configured a [monorepo](https://github.com/rcarcasses/nest-8.0.0-moduleref-bug) using `yarn` workspaces where I have two packages: one is the `nest` library I would like to develop, basically a new module, called `workspace-a`. The other package is called `workspace-b`, which is a `nestjs` app created with `nest create workspace-b` and imports the module defined in `workspace-a`.

Inside `workspace-a` I have a [`DummyClass` with a constructor parameter `readonly moduleRef: ModuleRef`](https://github.com/rcarcasses/nest-8.0.0-moduleref-bug/blob/f2dddfcf38a9566c5b99ddd78e561df4ddd475d0/workspace-a/src/index.ts#L5). When I build `workspace-a` and use it in `workspace-b` app it results that the injected parameter is `undefined`, as can be seen from the logs:
```shell
cd workspace-a
yarn build
cd ../workspace-b
yarn start:dev
``` 
On the opposite, [injection of `ModuleRef` in `workspace-b` indeed works](https://github.com/rcarcasses/nest-8.0.0-moduleref-bug/blob/f2dddfcf38a9566c5b99ddd78e561df4ddd475d0/workspace-b/src/app.service.ts#L9).

I have created a similar setup using `nestcli` and it works, but it is unclear to me how to produce an independent, reusable and publishable library from this (tips appreciated). I suspect I'm missing some configuration, can you help?

Thanks in advance for all your hard work!

**Comment by rcarcasses** [comment]
Update: I have found that the generated code from `workspace-a`  is missing the "design:paramtypes" metadata, so that's why no dependency injection is done after all. Any idea why this would happen? Thanks!

**Comment by kamilmysliwiec** [comment]
> Update: I have found that the generated code from workspace-a is missing the "design:paramtypes" metadata, so that's why no dependency injection is done after all. Any idea why this would happen? Thanks!

Invalid `tsconfig.json` configuration. Make sure to have those settings set to `true`:

```
"experimentalDecorators": true,
"emitDecoratorMetadata": true
```

**Comment by rcarcasses** [comment]
@kamilmysliwiec thanks for your reply. I had already added those and indeed now the metadata is exported, but now nest complains that it can't resolve the dependencies of `DummyClass`.
```shell
ERROR [ExceptionHandler] Nest can't resolve dependencies of the DummyClass
```
any ideas?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
