### ISSUE TITLE
Feature Request: transitional dependency

### ISSUE THREAD

**Issue by dilame** [nestjs/nest#7631]
## Is your feature request related to a problem? Please describe.

It is often needed to instantiate several instances of the same class with different input parameters. 
Real-life example
```ts 
class BillingService {
  constructor(private apiKey: string) {}
} 
```
I need two different `BillingService` instances because my billing provider doesn't support multiple currencies per one API KEY.

## Describe the solution you'd like

```ts
const first = await this.moduleRef.resolve(TransientService, {
  providers: [
    {
      provide: 'API_KEY',
      useValue: 'xxx',
    },
  ],
});

const second = await this.moduleRef.resolve(TransientService, {
  providers: [
    {
      provide: 'API_KEY',
      useValue: 'yyy',
    },
  ],
});
```

## What is the motivation / use case for changing the behavior?

It will make the NestJS DI system closer to full-featured. And it solves real problems.

**Comment by jmcdo29** [comment]
Couldn't you do something like
```ts
@Module({
  imports: [BillingModule.register(options1)],
  providers: [
	{
      provide: 'BillingService1',
      useExisting: BillingService,
    },
  ],
  exports: ['BillingService1'],
})
export class BillingModule1 {}

@Module({
  imports: [BillingModule.register(options2)],
  providers: [
    {
      provide: 'BillingService2',
      useExisting: BillingService,
    },
  ],
  exports: ['BillingService2'],
})
export class BillingModule2 {}

@Module({
  imports: [BillingModule1, BillingModule2],
})
export class BillingConsumerModule {}
```
And now you can use `@Inject('BillingService1')` and `@Inject('BillingService2')` injects two instances of `BillingService` but they have different configurations.

**Comment by dilame** [comment]
Thank you for your response, @jmcdo29. The method you mentioned is useful, but it assumes that parameters values and amount is defined at the code writing time. But what if I got a table in a database that contains tens of rows?
The example I provided is the simplified one. I just wanted to demonstrate that the feature i am requesting is real and useful.

Actually, i am building a chatbot web service. Users can configure it through the web GUI as block diagrams. Those diagram configurations are stored in the DB as JSON arrays. Each element of the array represents some class with its parameters. And i need to dynamically build a class tree with the DI system. Each class depends on some "global" or "common" dependencies along with its own parameters object.

**Comment by dilame** [comment]
Also would be nice to have the ability to manually remove dependencies from the container.

**Comment by kamilmysliwiec** [comment]
Have you tried using this https://docs.nestjs.com/fundamentals/module-ref#instantiating-custom-classes-dynamically?

**Comment by dilame** [comment]
> Have you tried using this https://docs.nestjs.com/fundamentals/module-ref#instantiating-custom-classes-dynamically?

Thank you for response, @kamilmysliwiec ;) I will never forget the moment when I shook your hand at HolyJS conference in Moscow 2019.
I haven't washed this hand since then!!

In fact, that’s the method I would want to use, but how can I pass transitional parameters as dependency?
I mean I would want to add a transitional parameters object as a provider in the container, then I want it to instantiate some class, and after that I want the transitional parameters object to be deleted from the container automatically (or at least manually).

**Comment by kamilmysliwiec** [comment]
😅 😅 😅 

> Each class depends on some "global" or "common" dependencies along with its own parameters object.

What if you define "common" classes (prototypes) that depend on static providers (and so can be instantiated & managed by the container) and then, separately, classes that require dynamic/custom objects/configuration + a set of static providers (where this "set" is represented by our "common" class instance)? 

Pseudo-code:

```typescript
// can be transient or singleton depending on what you want to accomplish
@Injectable()
export class PrototypeA {
 @Inject() readonly staticProvider1: StaticProvider1;
 @Inject() readonly staticProvider2: StaticProvider2;
 @Inject() readonly staticProvider3: StaticProvider3;
}

class DynamicClass1 {
   constructor(private prototypeA: PrototypeA, ...customArgs) {}
}

//// elsewhere
const prototypeA = this.moduleRef.get(PrototypeA);
for (...) {
   const dynamicClassInstance = new DynamicClass1(prototypeA, 1, 2, 3)
} 
```

This lets you control the `dynamicClassInstance` lifecycle as well and since you want to eventually remove those, this sounds like a better approach than storing them in the IoC container.

**Comment by dilame** [comment]
I got what you are talking about. This approach would be nice if it was a small part of the application - just several non-critical files somewhere in the corner. But actually it's a lot of such dynamic classes. Almost the whole application is these dynamic classes because the application is a user-defined chatbot, therefore the main functionality of the application is to interpret flowcharts into code.
It is cumbersome to repeat `Object.assign(...)` in all the constructors. Neither it is cumbersome to access the general dependencies throw one extra access point (`this.prototypeA.provider1`).
In a big complex application, it is always better to keep things as simple as possible, often it's even better to simplify at the expense of performance. And that's the case. I would prefer to write complex IoC container management logic somewhere in one class but keep the other 100 classes cleaner.

Another cornerstone - dynamic classes could depend on their specific providers, e.g. `NotificationService` may depend on several notification strategies - `EmailNotificationStrategyService`, `TelegramNotificationStrategyService` etc... And these strategies are not used by other services, only this one. Should i also inject `EmailNotificationService`, `TelegramNotificationService` in the `PrototypeA`? Wouldn't `PrototypeA` become a god object?

NestJS is inspired by Angular, as i heard 😄  Angular has got very nice [resolveAndCreateChild()](https://angular.io/api/core/ReflectiveInjector#resolveandcreatechild) method. I think NestJS DI is kinda turning incomplete without this feature, but will because Turing complete with such. I would love to create a child container for every user flowchart and then sub-child-container for every block of flowchart.

I can easily achieve it by [InversifyJS](https://github.com/inversify/InversifyJS), but i'm not sure if it's a good idea to have 2 DI systems in the same runtime... It's confusing.

**Comment by dilame** [comment]
As i understand - NestJS DI system should already have all the related functionality somewhere under the hood, because request-scoped providers is _almost_ what i am talking about, but with some additional http-server magic.

**Comment by kamilmysliwiec** [comment]
> As i understand - NestJS DI system should already have all the related functionality somewhere under the hood, because request-scoped providers is almost what i am talking about, but with some additional http-server magic.

Request-scoped providers are actually not tied to anything HTTP-specific. You can create your own DI sub-tree by creating a custom `ContextId` using the `ContextIdFactory`, check out this chapter https://docs.nestjs.com/fundamentals/module-ref#registering-request-provider

> I would love to create a child container for every user flowchart and then a sub-child-container for every block of flowchart.

Once your "context id" reference is removed (garbage-collected), your entire DI sub-tree will be removed as well (and so will all of your dynamically created instances assigned to this subtree).

**Comment by dilame** [comment]
Yeah, i see, the container uses `WeakMap`. But is there an explicit way to remove by service identifier? 
And create nested child containers?

**Comment by kamilmysliwiec** [comment]
> But is there an explicit way to remove by service identifier? And create nested child containers?

There's no plan to add such a feature in the foreseeable future as I don't see a scenario that would not be feasible using existing functionalities.

**Comment by dilame** [comment]
Well, I will try to graphically explain the case that is not feasible with NestJS DI.

<img width="581" alt="Снимок экрана 2021-07-27 в 22 51 01" src="https://user-images.githubusercontent.com/9336742/127218571-b3b014a5-174b-44ed-8b4d-20a08f5a2c7e.png">

Let's pretend we have a `FlowchartBlock` interface. It's a building block for a flowchart. It only contains `PARAMS` object.
It got 2 implementations:

* `SendTextFlowchartBock` – it sends text to the chat.
* `WaitForTextFlowchartBlock` – it waits for some text from the user.

They accept some dynamic parameters.

We can have multiple flowcharts, every flowchart can have multiple different building blocks.
That's why every flowchart should live in sub-container, and every `FlowchartBlock` should live in sub-sub-container. 
But all of them should use the same DB connection, that's why DB connection should live in the top-level container.

<img width="683" alt="Снимок экрана 2021-07-27 в 22 49 07" src="https://user-images.githubusercontent.com/9336742/127218345-f8495603-0734-4545-91aa-b1f2a5cafa8f.png">

As far as i learned NestJS IoC container - it's impossible to build such a structure with it.

**Comment by kamilmysliwiec** [comment]
It's doable. Think of the `ContextId` as a reference to your sub-tree host node. Whenever all references to the `ContextId` are gone, your sub-tree will be removed as well. Now to create a sub-tree of another sub-tree, assign the ContextId reference (of a sub-sub-tree) to at least 1 provider within the parent tree (sub-tree). In this case, all of your providers from within the sub-sub-tree will be removed & garbage collected automatically ONCE the sub-tree (aka parent tree in this case) is removed as well (and it will be removed once you destroy all references to the `ContextId`). All sub-trees can also inject dependencies from the main container (ex. Database connection).

I'm gonna close this issue (although I'd love to talk & and I appreciate all discussions so far) because I simply don't have the time & capacity to talk more. As I've mentioned in the previous post, there's no plan to implement a feature (originally discussed here) in the foreseeable future.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for further questions.
