### ISSUE TITLE
When using an Array of strings as origin as app.enableCors()-Parameter, no Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by ccebinger** [nestjs/nest#7634]
## Current behavior
When using an array of strings instead of a single string, no Access-Control-Allow-Origin gets printed.

@nestjs/common: "^7.6.17"
@nestjs/platform-express: "^7.6.17"

**Comment by Tony133** [comment]
Hi @ccebinger, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by ccebinger** [comment]
i am not able to provide code.

I got:

HTTP/1.1 204 No Content
X-Powered-By: Express
Access-Control-Allow-Origin: https://abnahme.belegservice.de
Vary: Origin, Access-Control-Request-Headers
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
Access-Control-Max-Age: 8400
Content-Length: 0
Date: Thu, 22 Jul 2021 15:26:43 GMT
Connection: keep-alive

The configuration was: 
```
 app.enableCors({
      origin: ['http://localhost:4200'],
      credentials: true,
      maxAge: 8400,
    });

```

I found this signature in cors-options.interface.d.ts 
declare type StaticOrigin = boolean | string | RegExp | (string | RegExp)[];

So Array of Strings and Regexps are allowed.

**Comment by ccebinger** [comment]
but origin: 'http://localhost:4200' works, but not with array.

**Comment by Tony133** [comment]
what version of nest do you use?

**Comment by ccebinger** [comment]
"@nestjs/common": "^7.6.17",
    "@nestjs/core": "^7.6.17",

**Comment by Tony133** [comment]
I tried on my project and I'm using nestjs v8 and it works (see screenshot):

<img width="487" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/126669286-fcc8e1fb-8eab-4d58-8587-8831b9aaae76.png">

see if i have a project with nestjs v7

**Comment by ccebinger** [comment]
How looks your Header? The Header of OPTIONS-Request is the point.
I tried it with 8.0.4 too, it doesnt work.

**Comment by Tony133** [comment]
If you could create a minimal reproduction on a clonable git I can see the problem a little better.

**Comment by ccebinger** [comment]
I found now the trick. 

I look at the source code at https://github.com/expressjs/cors/blob/master/lib/index.js

So I saw, that it is necessary, to set Origin-Header in the Request.
With curl: -H "Origin: http://localhost:4200"

Now it works.

**Comment by Tony133** [comment]
Glad you managed to find the problem

**Comment by ccebinger** [comment]
I guess the implementation makes sense. But it was confusing.
Why doesnt the single string - option depend on right setting of Origin.

**Comment by ccebinger** [comment]
This issue can be closed. Thank you.

**Comment by Tony133** [comment]
Of nothing, if I can help I do it willingly. 👍

If you need future support for Nest, remember that you can always use the [discord] channel (https://discord.com/invite/G7Qnnhy) for support.

**Comment by micalevisk** [comment]
> This issue can be closed.

@ccebinger as the author of an issue, you can close it btw ^^
