### ISSUE TITLE
ApplicationContext keep alive

### ISSUE THREAD

**Issue by BorntraegerMarc** [nestjs/nest#7638]
## Is your feature request related to a problem? Please describe.

I have a use case where I have a [task scheduler](https://docs.nestjs.com/techniques/task-scheduling) which will fetch some data in an interval and store it in a DB. I want to use the awesome NestJS features (like DI, etc.) in my app. But don't need a web server or micro service.

According to the docs the only way to use task scheduler is by creating a NestJS web server (or hacky micro service; see below stackoverflow). But I want my app to be as lightweight as possible. I don't want to launch a web server.

Seems like other people also have the same problem: https://stackoverflow.com/questions/65555197/run-nestjs-scheduler-without-starting-the-http-server

## Describe the solution you'd like

A way to create a NestJS application context and "keeping it alive" so that my tasks can run. E.g:
```ts
const app = await NestFactory.createApplicationContext(AppModule, { keepAlive: true });
```

## Teachability, Documentation, Adoption, Migration Strategy

```ts
/**
 * Use this in case you want to keep alive your application context. Any defined schedulers, etc. will run in your defined interval.
 */
keepAlive: boolean = true;
```

## What is the motivation / use case for changing the behavior?

Being as lightweight as possible while still having a full NestJS experience.

Technically I could just use the `node-cron` library directly and wrap my NestJS code inside an own `job`. But I feel like having the decorators of NestJS available is more straightforward for a lot of devs.

**Comment by kamilmysliwiec** [comment]
With any tasks scheduled (timeouts, intervals, connections, polling) your application should remain "alive" without any additional strategies/code needed. Did you run into any issues with that?

**Comment by BorntraegerMarc** [comment]
Oh, I see. So, after your message I updated all my dependencies (including NestJS) and indeed the app is kept alive.

Thanks for the help and sorry about the hazzle!
