### ISSUE TITLE
Importing types.d.ts when using Webpack HMR causes module not found error (nest start works fine)

### ISSUE THREAD

**Issue by jaooe** [nestjs/nest#7639]
## Current behavior
Importing protobuf.types.d.ts using webpack hmr causes `Module not found: Error: Can't resolve `

Issue does not appear when using `nest start`

## Input Code

```ts
import { routes} from '../../proto/routes.types'; //protobuf type declaration to import routes.types.d.ts
```

## Expected behavior
File should be imported fine

## Possible Solution
N/A

## Environment
<pre><code>
Nest version: 8.0.0

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Tony133** [comment]
Hi @jaooe, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

**Comment by jaooe** [comment]
Thanks @Tony133  https://github.com/jaooe/minimal-nestjs-issue-7639

**Comment by jaooe** [comment]
Managed to resolve the issue myself, seems nest didn't like proto types built by `pbjs`, used `ts-proto`.
