### ISSUE TITLE
Nest v8 module ref cannot resolve provider using the name

### ISSUE THREAD

**Issue by kashyap-aditya** [nestjs/nest#7640]
## Current behavior

let className = 'someClass'; // loaded from database
await moduleRef.resolve(
          className,
          ContextIdFactory.getByRequest(request),
          { strict: false },
 );
-> this fails. Worked fine in v7

## Input Code

```ts
let className = 'someClass'; // loaded from database
await moduleRef.resolve(
          className,
          ContextIdFactory.getByRequest(request),
          { strict: false },
 );
```

## Expected behavior

Inject the provider with the name className

## Environment

<pre><code>
Nest version: 8.0.0

 
For Tooling issues:
- Node version: 14.16.1
- Platform:  all

Others:

</code></pre>

**Comment by jmcdo29** [comment]
This was a change in Nest v8. Provider resolution now works off of class references, not the class name by default. To counter this if you still need the old functionality you can use a custom provider and `@Inject()` to inject providers based on the string

```ts
{
	provide: 'someClass',
    useClass: someClass,
}
```
And 
```ts
@Inject('someClass')
```
or
```ts
let className = 'someClass'; // loaded from database
await moduleRef.resolve(
          className,
          ContextIdFactory.getByRequest(request),
          { strict: false },
 );
```

**Comment by kashyap-aditya** [comment]
A. This change needs to be reflected in the documentation.

B.

        ```
const classMap = {'classA': classA, 'classB':classB}

        let provider: T = await moduleRef.resolve<T>(
          ClassMap['classA'],
          ContextIdFactory.getByRequest(request),
          { strict: false },
        );
```

i tried this solution but as soon as I do it, I get an error saying that this function (inside which this moduleRef call is contained) is not a constructor.
If I simply change 
`ClassMap['classA']`
to 
`'classA'`
it works just fine.

The function is typed properly (types for all input and output parameters) and that is left unchanged

**Comment by kamilmysliwiec** [comment]
@kashyap-aditya using stringified class names as injection tokens was never really documented in the first place so there's no reason to flag it as a breaking change.
