### ISSUE TITLE
typescript is throwing an error when trying to access req.params

### ISSUE THREAD

**Issue by Ahmad-RW** [nestjs/nest#7641]
## Current behavior
I created a middleware and tried to access req.params but typescript is throwing an error saying property does not exist on type.
Acessing using req['params'] works fine.
Object.keys(req) shows params is there.

## Input Code

```ts
import { Injectable, NestMiddleware } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { NextFunction } from "express";
import { ChallengeRepository } from "src/challenges/challenges.repository";
import { ChallengesService } from "src/challenges/challenges.service";



@Injectable()
export class GetChallengeMW implements NestMiddleware{
    constructor(private challengesService : ChallengesService){}
    async use(req : Request, res : Response, next : NextFunction){
        console.log(req.params)
        next()
    }
}
```

## Expected behavior
typescript shouldn't throw this error.

## Possible Solution
vscode suggests modifying lib.dom.d.ts file by adding "adding index signature for property 'params'"

## Environment
<code><pre>
[System Information]
OS Version     : Windows 10
NodeJS Version : v14.16.1
NPM Version    : 7.20.1 

[Nest CLI]
Nest CLI Version : 8.0.2

[Nest Platform Information]
platform-express version : 8.0.0
typeorm version          : 8.0.1
common version           : 8.0.0
core version             : 8.0.0
Others:

</code></pre>

**Comment by Ahmad-RW** [comment]
in fact this is also causing issues in modifying request object. As per [docs](https://docs.nestjs.com/middleware#middleware), middleware is used to modify request and response but currently it's throwing errors when trying to modify.

**Comment by micalevisk** [comment]
Import `Request` and `Response` from `express` as well.

**Comment by jmcdo29** [comment]
Types isn't a bug, just importing the wrong types. Request and response should be imported from the proper adapter library

**Comment by Ahmad-RW** [comment]
> 
> 
> You're using the nodejs types and they don't have `.params`.
> 
> Import `Request` and `Response` from `express`, as the docs shows.

Ah okay it's working now. Didn't notice that vscode didn't import it automatically.
Cheers 👍
