### ISSUE TITLE
Documentation Error on RedisIoAdapter class implementation under Websockets

### ISSUE THREAD

**Issue by shriniwassurve** [nestjs/nest#7642]
## Current behavior
[https://docs.nestjs.com/websockets/adapter](https://docs.nestjs.com/websockets/adapter)
There is this code in RedisIoAdapter class implementation section

```import { IoAdapter } from '@nestjs/platform-socket.io';
import * as redisIoAdapter from 'socket.io-redis';

export class RedisIoAdapter extends IoAdapter {
  createIOServer(port: number, options?: any): any {
    const server = super.createIOServer(port, options);
    const redisAdapter = redisIoAdapter({ host: 'localhost', port: 6379 });

    server.adapter(redisAdapter);
    return server;
  }
}
```
This wouldn't work anymore as [the library will no longer create Redis clients on behalf of the user.](https://github.com/socketio/socket.io-redis-adapter/blob/master/CHANGELOG.md)

## Possible Solution
```import { IoAdapter } from '@nestjs/platform-socket.io';
import { RedisClient } from 'redis';
import { ServerOptions } from 'socket.io';
import { createAdapter } from 'socket.io-redis';

const pubClient = new RedisClient({ host: 'localhost', port: 6379 });
const subClient = pubClient.duplicate();
const redisAdapter = createAdapter({ pubClient, subClient });

export class RedisIoAdapter extends IoAdapter {
  createIOServer(port: number, options?: ServerOptions): any {
    const server = super.createIOServer(port, options);
    server.adapter(redisAdapter);
    return server;
  }
}
```
There is same code under [gateway adapter sample](https://github.com/nestjs/nest/blob/master/sample/02-gateways/src/adapters/redis-io.adapter.ts)

## Environment

<pre><code>
Nest version: 8.0.4

**Comment by shriniwassurve** [comment]
I think this should be mentioned in [Migration Guide](https://docs.nestjs.com/migration-guide).

**Comment by Tony133** [comment]
I don't think it's worth adding it to the migration guide as well. I have some doubts, I don't know if it's worth adding it there too, I think that with the update of the snippets in the example it should be fine.

**Comment by kamilmysliwiec** [comment]
Updated. Thanks for reporting
