### ISSUE TITLE
CORS error when calling websocket request

### ISSUE THREAD

**Issue by qafoori** [nestjs/nest#7649]
## Current behavior
CORS error happens with websockets request even i use `app.enableCors()`

## Important
I'm sure the exact same code works with version 7.0.0. I downgraded my project to 7.0.0 and everything was fine.
Note that I don't have CORS error in my REST APIs. And it just happens with websocket

## Input Code
chat.gateway.ts:
```
import { MessageBody, SubscribeMessage, WebSocketGateway, WebSocketServer } from "@nestjs/websockets";
@WebSocketGateway()
export class ChatGateway {
  @WebSocketServer()
  server;
  @SubscribeMessage('message')
  handleMessage(@MessageBody() message: string): void {
    this.server.emit('message', message);
  }
}
```
app.module.ts:
```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ChatGateway } from './chat.gateway';
@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService, ChatGateway],
})
export class AppModule {}
```
and in my client:
```
const socket = io("http://localhost:9998")
const sendMessage = () => {
  socket.emit('message', { data: message.value })
}
socket.on('message', ({ data }) => {
  // am doing something with 'data'
})
```

## What I tried
I tried any solutions for get ride out of CORS error such as using `cors` package. but it didn't works

## Expected behavior
My client connect to my server websockets without CORS error

## Environment

<pre><code>
Nest version: 8.0.0
 
For Tooling issues:
- Node version: 14.17.3 
- Platform:  Windows

**Comment by jmcdo29** [comment]
[There was a change between socket.io v2 and socket.io v3](https://socket.io/docs/v4/migrating-from-2-x-to-3-0/) where CORS must now be configured. In Nest v8, socket.io v4 is used, which means that you must configure CORS yourself

**Comment by qafoori** [comment]
> [There was a change between socket.io v2 and socket.io v3](https://socket.io/docs/v4/migrating-from-2-x-to-3-0/) where CORS must now be configured. In Nest v8, socket.io v4 is used, which means that you must configure CORS yourself

Can you update that example in sample folder with the new way to implement websockets?. I mean [02-gateways](https://github.com/nestjs/nest/tree/master/sample/02-gateways)

**Comment by qafoori** [comment]
> [There was a change between socket.io v2 and socket.io v3](https://socket.io/docs/v4/migrating-from-2-x-to-3-0/) where CORS must now be configured. In Nest v8, socket.io v4 is used, which means that you must configure CORS yourself

I used some configurations like this. but its still not working:

 ```
app.enableCors({
    origin: '*',
    methods: [
      'GET',
      'HEAD',
      'PUT',
      'PATCH',
      'POST',
      'DELETE',
    ],
    allowedHeaders: [
      'Access-Control-Allow-Origin',
    ],
  })
```

where is wrong with my configs?
am getting this error in console:
Access to XMLHttpRequest at 'http://localhost:9998/socket.io/?EIO=3&transport=polling&t=NhVSQQ2' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by kamilmysliwiec** [comment]
```typescript
@WebSocketGateway({
  cors: {
    origin: 'https://example.com',
    methods: ['GET', 'POST'],
    allowedHeaders: ['my-custom-header'],
    credentials: true,
  },
})
export class ChatGateway { .. }
```

**Comment by Ayzrian** [comment]
I wonder if we can allow providing a config through DI, otherwise configuring the `cors` seems a bit broken, as we don't have the access to DI container when applying the Gateway decorator. 

This would make the dynamic configuration of the cors possible. 

What do you think?

**Comment by kamilmysliwiec** [comment]
DI container is fully detached from the transport layer. Configuring CORS through DI would require a lot of significant, architectural changes to implement it properly. There are currently no plans to do so.
