### ISSUE TITLE
Graphql e2e testing error when calling "createTestingModule" - TypeError: graphql_1.GraphQLScalarType is not a constructor

### ISSUE THREAD

**Issue by ayoubyt** [nestjs/nest#7650]
## Bug Report

while trying to make an end-to-end test to a Graphql API, I face a weird error, even when just initializing the testing module.

## Current behavior

```bash
npm run test:e2e

> node-challenge-assignment@0.0.1 test:e2e /goinfre/aaguert/node-challenge-assignment
> jest --config ./test/jest-e2e.json

 FAIL  test/app.e2e-spec.ts
  ● Test suite failed to run

    TypeError: graphql_1.GraphQLScalarType is not a constructor

      at Object.<anonymous> (../node_modules/@nestjs/graphql/dist/scalars/iso-date.scalar.js:5:30)
      at Object.<anonymous> (../node_modules/@nestjs/graphql/dist/scalars/index.js:6:22)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.356 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-challenge-assignment@0.0.1 test:e2e: `jest --config ./test/jest-e2e.json`
npm ERR! Exit status 1
```

## Input Code

```ts
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import { AppModule } from 'src/app.module';

describe('AppController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  afterAll(() => {
    app.close();
  })

  it('make random test', () => {
    expect(2 + 2).toBe(4);
  });
});

```

## Expected behavior

```bash
npm run test:e2e

> node-challenge-assignment@0.0.1 test:e2e /goinfre/aaguert/node-challenge-assignment
> jest --config ./test/jest-e2e.json

 PASS  test/app.e2e-spec.ts
  AppController (e2e)
    ✓ make random test (2 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.66 s
Ran all test suites.
```

## Environment

<pre><code>
Nest version: 8.0.2

 
For Tooling issues:
- Node version: 14.17.3  
- Platform: Mac

**Comment by jmcdo29** [comment]
This is probably a configuration problem. Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by ayoubyt** [comment]
> This is probably a configuration problem. Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

hello @jmcdo29, thanks for answering, that's a link to the minimum reproduction repository you asked for: https://github.com/ayoubyt/nestjs-graphql-e2e-test-error-minimum-reproduction/tree/master

**Comment by CatsMiaow** [comment]
@ayoubyt you need to configure plugin(`@nestjs/graphql/plugin`) in jest.
See https://docs.nestjs.com/graphql/cli-plugin#integration-with-ts-jest-e2e-tests

**Comment by ayoubyt** [comment]
> @ayoubyt you need to configure plugin(`@nestjs/graphql/plugin`) in jest.
> See https://docs.nestjs.com/graphql/cli-plugin#integration-with-ts-jest-e2e-tests

I tried experimenting with "@nestjs/graphql/plugin" but still get the same error, maybe because  I'm still a beginner in jest and testing in general.
but as far as I know, the link you sent me @CatsMiaow talks about testing Graphql when the plugin is enabled, but as you can realize in the [minimum reproduction repository](https://github.com/ayoubyt/nestjs-graphql-e2e-test-error-minimum-reproduction/tree/master) I provided I didn't enable or use the nests Graqphql plugin, it only contains one resolver with one query that just returns a scalar

```ts
import { Query, Resolver } from '@nestjs/graphql';

@Resolver()
export class AppResolver {
  @Query(() => String)
  test() {
    return 'test';
  }
}
```

it would be really helpful to state exactly the issue or what exactly needs to be changed in the example repo I provided.

**Comment by jmcdo29** [comment]
I get the same error with your minimum reproduction, but I don't get why it's there. `graphql` uses named exports, so Nest is consuming the library properly, it's like something in the ts-jest config is having a problem here. I'm still looking into it for you, but I'm not certain this is specific to Nest

**Comment by jmcdo29** [comment]
Okay, found it, I was right it's a config error. By using
```json
{
	"moduleDirectories": [
		"node_modules",
		"."
	]
}
```
in your `jest-e2e.json`, you made it so that and import of `graphql` would look first in the closest directory possible before going on to `node_modules` (just how the jest search was working). I assume you have this for using `src/` absolute imports. If you still want to use those you can use `moduleNameMapper`, like so:
```json
{
  "moduleFileExtensions": [
    "js",
    "json",
    "ts"
  ],
  "rootDir": ".",
  "moduleDirectories": [
    "node_modules"
  ],
  "moduleNameMapper": {
    "^src/(.*)$": "<rootDir>/../src/$1"
  },
  "testEnvironment": "node",
  "testRegex": ".e2e-spec.ts$",
  "transform": {
    "^.+\\.(t|j)s$": "ts-jest"
  }
}
```

**Comment by ayoubyt** [comment]
yes, that actually was the issue, I've never thought that could be from "moduleDirectories", and yes, I used that to use ```src/``` absolute imports.
the ```moduleNameMapper``` was a great idea to solve the problem.

thanks a lot, @jmcdo29 for the help, we appreciate your work guys, best wishes for you.
