### ISSUE TITLE
nestjs microservices deserializers should allow async

### ISSUE THREAD

**Issue by konqi** [nestjs/nest#7657]
## Is your feature request related to a problem? Please describe.
In my current project we're using nestjs microservices with kafka. We're also using the kafka schema registry. The registry works in a way that parses AVRO/PROTOBUF/JSON encoded messages into plain objects. This step is essentially a deserializer. The kafka message contains the information about which schema to use in the first 5 byte preamble. Before reading the preamble it is unknown which is the right schema. Once the preamble is read, the correct schema has to be downloaded to deserialize the message according to the schema defintions.
Currently, nestjs microservices requires deserializers to run synchronous, thus possibly fetching the schema from the registry in the deserializer doesn't work. I hacked around this by returning an unresolved Promise in the deserializer and await the result in the message handler. This is super ugly and I really want to change this.

## Describe the solution you'd like
Deserializers could simply await the result, thus allowing the actual deserializer to be async. Since awaiting something that isn't a promise yields the value the change is backward compatible.

## Teachability, Documentation, Adoption, Migration Strategy
Since awaiting something that isn't a promise yields the value the change is backward compatible.

I have already created a Pull Request for this: https://github.com/nestjs/nest/pull/7248

**Comment by kamilmysliwiec** [comment]
Added in 8.0.5
