### ISSUE TITLE
io-ts as a DTO for request & OpenApi

### ISSUE THREAD

**Issue by mits87** [nestjs/nest#7667]
Hello, 

First of all thanks for an amazing framework. I'm happy to use it!

Currently I have a small issue with amount of classes (DTOs) for request validation and Swagger documentation which are 100% duplicated with my interfaces. I'm trying to solve the issue using io-ts library but actually I guess there must be some work done under the hood. 

Right now I'm using a DTO like that: 
```
export interface IFee {
    name: string;
    price: number;
    quantity: number;
    total: number;
}

export class FeeDto implements IFee {
  /**
   * Name
   * @example Fee Name
   */
  name: string;

  /**
   * Price
   * @example 1000
   */
  price: number;

  /**
   * Quantity
   * @example 2
   */
  quantity: number;

  /**
   * Total
   * @example 2000
   */
  total: number;
}
```

And this solution works.
But in my project actually I use io-ts library for my all interfaces like that:

```
import * as t from 'io-ts';

const TFee = t.type({
  /**
   * A name of the fee
   * @example Fee Name
   */
  name: t.string,
  /**
   * A fee price in cents
   * @example 1000
   */
  priceCents: t.number,
  /**
   * A quantity
   * @example 2
   */
  quantity: t.number,
  /**
   * Calculated total fee in cents
   * @example 2000
   */
  totalCents: t.number,
});

export interface IFee extends t.TypeOf<typeof TFee> {}
```

and right now my problem is how can I use it as a DTO class (with io-ts validation)? 
Is it possible?

I tried do like here https://www.npmjs.com/package/io-ts-derive-class

```
export class FeeDto extends tdc.DeriveClass(TFee) {}
```

But it not gonna work properly and swagger documentation is not generating correctly.
Maybe it would be a good idea to support `io-ts` for swagger & validation?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
