### ISSUE TITLE
Upgrading to version 8.0.4 breaks dependency injection using module forward ref

### ISSUE THREAD

**Issue by chadbaily** [nestjs/nest#7674]
## Bug Report

When doing the migration from NestJs v7.6.15 to v8.0.4 the module forward reference breaks.

## Current behavior
I have two modules and am using the [module forward reference](https://docs.nestjs.com/fundamentals/circular-dependency#module-forward-reference) in each of them to provide a class for one of the modules. 

On version `8.0.4` I receive the following error

```bash
[Nest] 7103  - 07/27/2021, 9:12:12 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the CreateProductUseCase (?, ProductFactory). Please make sure that the argument ProductRepository at index [0] is available in the ApplicationModule context.
```

### Application Module
```ts
import { Module, forwardRef } from '@nestjs/common';
import { InfrastructureModule } from '../infrastructure/infrastructure.module';
import CreateProductUseCase from './usecases/createProductUsecase';
...
@Module({
  imports: [
    forwardRef(() => InfrastructureModule),
    ...
  ],
  controllers: [],
  providers: [
    CreateProductUseCase,
    ...
  ],
  exports: [
    CreateProductUseCase
    ...
  ],
})
export class ApplicationModule {}
```

### CreateProductUsecase
```ts
import { Inject, Injectable } from '@nestjs/common';
import { Observable } from 'rxjs';
import { ProductRepoPort } from '../../domain/product.port';
import Product from '../../domain/product.aggregate';
import ProductFactory from '../product.factory';
import { CreateProductDto } from '../createProduct.dto';
@Injectable()
export default class CreateProductUseCase {
  constructor(
    @Inject('ProductRepository')
    private productRepository: ProductRepoPort,
    private productFactory: ProductFactory,
  ) {}

  public handler(
    productDto: CreateProductDto,
  ): Observable<Product> {
    const product = this.productFactory.createProduct(
      productDto,
    );
    return this.productRepository.create(product);
  }
}
```

### InfrastructureModule
```ts
import { Module, forwardRef } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigModule } from '@nestjs/config';
import { ApplicationModule } from '../application/application.module';
import ProductController from './primary/product.controller';
import { ProductEntity } from './secondary/product.entity';
import { ProductRepository } from './secondary/product.repo';

@Module({
  imports: [
    forwardRef(() => ApplicationModule),
    ConfigModule,
    TypeOrmModule.forFeature([ProductEntity]),
  ],
  controllers: [ProductController],
  providers: [ProductRepository],
  exports: [ProductRepository],
})
export class InfrastructureModule {}
```

### ProductRepository
```ts
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ProductRepoPort } from '../../domain/product.port';
import { ProductEntity } from './product.entity';

@Injectable()
export class ProductRepository implements ProductRepoPort {
  constructor(
    @InjectRepository(ProductEntity)
    private productRepository: Repository<ProductEntity>,
  ) {}
  ...
}
```

### Package.json

```json
...
"dependencies": {
    "@casl/ability": "^5.3.1",
    "@nestjs/common": "^8.0.4",
    "@nestjs/config": "^1.0.1",
    "@nestjs/core": "^8.0.4",
    "@nestjs/platform-express": "^8.0.4",
    "@nestjs/swagger": "^5.0.8",
    "@nestjs/typeorm": "^8.0.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.1.6",
    "typeorm": "^0.2.34"
  },
...
```

## Expected behavior
The application module is able to resolve the providers (`ProductRepository`) from the infrastructure module without issue

## Environment

<pre><code>
Nest version: 7.6.0
 
For Tooling issues:
- Node version: v12.16.3
- NPM: 6.14.4
- Platform: Mac
</code></pre>

**Comment by jmcdo29** [comment]
1) Why is this circular? Nothing in your `ProductModule` requires the `CreateProductUseCase`
2) If `ApplicationModule` is your root module, that should pretty much never be imported elsewhere, even via forwardRef, as that would mean other parts of your server need the root package of the server to instantiate first, which really doesn't make sense
3) Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by chadbaily** [comment]
Thanks for your response Jay!
1. It was circular in order to resolve the dependency injection originally. You are correct, there are no circular references within the modules. It just seemed to be what was needed in order for the code to work
2. `ApplicationModule` is in the root module and the forwardRef was needed in order for the dependency to be resolved
3. I will work on creating this and share the link in another comment

**Comment by chadbaily** [comment]
[Here](https://github.com/chadbaily/nest-module-ref) is a link to a repo that reproduces the issue

**Comment by kamilmysliwiec** [comment]
`@nestjs/typeorm` v8 shouldn't be used with NestJS v7 (core/common/etc. packages). v7 is compatible with v7, v8 with v8

**Comment by chadbaily** [comment]
@kamilmysliwiec I am a little confused. It seems to me that you were looking in the wrong branch on the repository. I have downgraded `@nest/typeorm` in the `main` branch (where the code is working) and everything still works fine. In the `v8` branch (where the issue is demonstrated) every `@nest` package is on the latest major version. Am I missing something in the `package.json`?
```json
"dependencies": {
    "@nestjs/common": "^8.0.5",
    "@nestjs/config": "^1.0.1",
    "@nestjs/core": "^8.0.5",
    "@nestjs/platform-express": "^8.0.5",
    "@nestjs/swagger": "^5.0.8",
    "@nestjs/typeorm": "^8.0.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "pg": "^8.6.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.1.6",
    "typeorm": "^0.2.34"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.1.0",
    "@nestjs/schematics": "^8.0.2",
    "@nestjs/testing": "^8.0.5",
    "@types/express": "^4.17.11",
    "@types/jest": "^26.0.22",
    "@types/node": "^14.14.36",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "jest": "^26.6.3",
    "prettier": "^2.2.1",
    "supertest": "^6.1.3",
    "ts-jest": "^26.5.4",
    "ts-loader": "^8.0.18",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.2.3"
  },
```

**Comment by kamilmysliwiec** [comment]
Ahh, you're right, I didn't know I have to change my branch.

Looking at v8 now, this:

![image](https://user-images.githubusercontent.com/23244943/127500492-dac51af7-05f7-4dc2-9b07-2883e7299912.png)

(injecting by the class name instead of a class reference) should never even work in v7 in the first place (it was never documented).

You can find a few other issues asking the same question in this repository.

https://github.com/nestjs/nest/issues/7640#issuecomment-885811172
https://github.com/nestjs/nest/issues/7583#issuecomment-881209020

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for further questions on this topic. We are using GitHub to track bugs, feature requests, and potential improvements.
