### ISSUE TITLE
Unable to integrate swagger -> Cannot find module '@nestjs/core/router/route-path-factory'

### ISSUE THREAD

**Issue by phanivaranasi** [nestjs/nest#7684]
Cannot find module '@nestjs/core/router/route-path-factory'
I've followed as per docs for integrating Swagger in nest api but while nest start command throwing above error

Nest version: 7.6.0

 
For Tooling issues:
- Node version: v12.18.4 
- Platform:  Windows

**Comment by jmcdo29** [comment]
If you're using swagger v5 you need to use nest v8. If you're using swagger v4 you need to use nest v7
