### ISSUE TITLE
BadRequestException: default message isn't overriden in exception filter

### ISSUE THREAD

**Issue by Awaydrasil** [nestjs/nest#7685]
## Bug Report
When throwing a new BadRequestException with a message, I'm unable to retrieve the message inside an exception filter. Instead it has a default message which is "Bad Request Exception" 
Doc says that if a new exception is thrown with a custom message, the default one should be overriden with the custom one

## Current behavior

When throwing a new error with a custom message and catching it with an exception filter, the exception doesn't have the message

## Input Code

```ts
/* service.ts */
throw new BadRequestException(`Missing some parameters...`);

/* error-exception.filter.ts*/
async catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    const status = exception.getStatus();

    const exceptionResponse = exception.getResponse() as IThrownException;

    if (!Array.isArray(exceptionResponse.message)) {
      exceptionResponse.message = [];
    }

    response.status(status).json({
      status: exceptionResponse.statusCode,
      type: exceptionResponse.error,
      message: exception.message,
      timestamp: new Date().toISOString(),
    });
  }

/* API response */
{
    "status": 400,
    "type": "Bad Request",
    "message": "Bad Request Exception",
    "timestamp": "2021-07-28T08:05:39.433Z"
}
```

## Expected behavior

```exception.message``` should equal ```Missing some parameters``` instead of its default value ```Bad Request Exception```
## Environment

<pre><code>Nest version: 8.0.0

 
For Tooling issues:
- Node version: 16.5.0
- Platform:  macOS Big Sur 11.4
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
