### ISSUE TITLE
MSSQL error. SequelizeHostNotFoundError

### ISSUE THREAD

**Issue by SlavaDen** [nestjs/nest#7686]
Good afternoon
I am trying to connect to the mssql database through the sequence
I get an error when connecting
SequelizeHostNotFoundError: Failed to connect to
I am connecting, as indicated in the official documentation

`
import {Module} from "@nestjs/common";
import { SequelizeModule } from "@nestjs/sequelize";
import {AppController} from "./app.controller";
import {AppService} from "./app.service";
import {UsersModule} from "./users/users.module";
import {User} from "./users/users.model";

@Module({
    controllers:[AppController],
    providers: [AppService],
    imports: [
        SequelizeModule.forRoot({
            dialect: 'mssql',
            host: "SLAVA\\SQLEXPRESS01",
            port: 1433,
            username: "sa",
            password: "password",
            database: "test",
            models: [User],
            autoLoadModels: true,
            logging: console.log,
        }),
        UsersModule,
    ]
})

export class AppModule {}
`

package.json
`{
  "name": "test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mongoose": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/sequelize": "^8.0.0",
    "@nestjs/typeorm": "^8.0.1",
    "mongoose": "^5.13.3",
    "mssql": "^7.1.3",
    "mysql2": "^2.2.5",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "sequelize": "^6.6.5",
    "sequelize-typescript": "^2.1.0",
    "tds": "^0.1.0",
    "tedious": "^11.4.0",
    "typeorm": "^0.2.34"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^26.0.24",
    "@types/node": "^16.0.0",
    "@types/sequelize": "^4.28.10",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "27.0.6",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
`

I want to note that the connection with this data passes through PHP. I also have access to several mssql servers and the connection does not work on more than one

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
