### ISSUE TITLE
Logger without Context tries to use optionalParams and results in an undefined log

### ISSUE THREAD

**Issue by fbalbinoribeiro** [nestjs/nest#7691]
## Current behavior
Logger without Context tries to use optionalParams and results in an undefined log
``` 
/**
   * Write a 'log' level log, if the configured level allows for it.
   * Prints to `stdout` with newline.
   */
  log(message: any, context?: string): void;
  log(message: any, ...optionalParams: [...any, string?]): void;
  log(message: any, ...optionalParams: any[]) {
```

## Input Code
`
CustomerLogger.log(message, undefined);
`

```ts
const your = (code) => here;
```

## Expected behavior
If I have a context undefined and no optional parameters, may our logger defines and empty context and doesn't log an undefined value

## Possible Solution
If I have a context undefined and no optional parameters, may our logger defines and empty context and doesn't log an undefined value

## Environment

<pre><code>
Nest version: 8.0.5
 
For Tooling issues:
- Node version: 15
- Platform: windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Why are you calling `CustomerLogger.log(message, undefined)` instead of `CustomerLogger.log(message)` then?
