### ISSUE TITLE
ValidationPipe does not get triggered in the base controller

### ISSUE THREAD

**Issue by arthu** [nestjs/nest#7695]
## Current behavior

I have a base controller for basic CRUD operation, if a controller needs CRUD operation, it can just extends this controller. Everything works fine except that the ValidationPipe does not get trigger, but if I put a route in the child controller, the ValidationPipe gets triggered as expected.

## Input Code
```js

export class CatalogueCreateDto {
  @MinLength(2)
  catalogueId: string

  @MinLength(4)
  name: string
}

export abstract class EntityController<Entity, CreateEntityDto> {
  constructor(private entityService: EntityService<Entity, CreateEntityDto>) {}

  @Post()
  create(@Body() createDto: CreateEntityDto) {
    return this.entityService.create(createDto)
  }

  // ..... other route handlers
}
```

```js
@Controller('catalogues')
export class CataloguesController extends EntityController<Catalogue, CatalogueCreateDto> {
  constructor(cataloguesService: CataloguesService) {
    super(cataloguesService)
  }

  @Post('ping')
  myping(@Body() createDto: CatalogueCreateDto) {
    return createDto
  }
}
```

## Expected behavior
The ValidationPipe should be triggered regardless it's defined in base or child controller

## Environment

<pre><code>
Nest version: 8.0.4

 
For Tooling issues:
- Node version: 16
- Platform:  Mac Os

Others:

</code></pre>

**Comment by jmcdo29** [comment]
This is a problem with typescript and reflection and a limitation of the language. Typescript does not reflect generic types, so when Nest reads the metadata for the route, it can't read the type properly, and has to skip the validation. The only way to get around this is to use a mixin instead of a generic abstract class.

**Comment by Zclhlmgqzc** [comment]
like this

```

export class CatalogueCreateDto {
  @MinLength(2)
  catalogueId: string

  @MinLength(4)
  name: string
}

export function createAbstractEntityController<T>(
  ClassRef: Type<T>
) {
  abstract class EntityController<Entity, T> {
    constructor(private entityService: EntityService<Entity, T>) {}

    protected readonly validationPipe: ValidationPipe = new ValidationPipe({})

    protected transform(dto: T, type = 'body') {
      return this.validationPipe.transform(dto, {
        type,
        metatype: ClassRef
      })
    }

    @Post()
    create(@Body() createDto: T) {
      await this.transform(createDto)
      return this.entityService.create(createDto)
    }

    // ..... other route handlers
  }

  return EntityController
}

```

```
@Controller('catalogues')
export class CataloguesController extends createAbstractEntityController(CatalogueCreateDto) {
  constructor(cataloguesService: CataloguesService) {
    super(cataloguesService)
  }
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
