### ISSUE TITLE
Add ability to validate response

### ISSUE THREAD

**Issue by redwert** [nestjs/nest#7713]
## Is your feature request related to a problem? Please describe.
In my project I need to validate all responses according to dto schemas

## Describe the solution you'd like
It would be great to have something like @Body decorator in which I can pass the ResponseDto and use class validator in ResponseDto to validate the response.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
