### ISSUE TITLE
Error 'cannot set distance of undefined' thrown with forwardRef async modules

### ISSUE THREAD

**Issue by ldiego08** [nestjs/nest#7715]
## Potential Commit/PR that introduced the regression**

This was introduced in NestJS version ^8.0.0

## Describe the regression

When registering an async module (i.e GraphQL) using `forwardRef`, a `TypeError: Cannot set property 'distance' of undefined` exception is thrown on app start. It seems to come from the module dependency scanner (`@nestjs/core/scanner.ts`) and is not recoverable. This might potentially be blocking anyone trying to use forwardRef with async modules. 

## Input Code

[Here's a complete repro in CodeSandbox](https://codesandbox.io/s/headless-darkness-tur5u?file=/src/other.module.ts:0-297), and additionally, the failing code:

```ts
import { forwardRef, Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';

@Module({
  imports: [
    forwardRef(() =>
      GraphQLModule.forRootAsync({
        useFactory: () => ({
          cors: true,
        }),
      }),
    ),
  ],
})
export class MyModule {}
```

Error and stack trace:

```
(node:1840) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'distance' of undefined
    at /sandbox/node_modules/@nestjs/core/scanner.js:169:44
    at Set.forEach (<anonymous>)
    at calculateDistance (/sandbox/node_modules/@nestjs/core/scanner.js:168:27)
    at /sandbox/node_modules/@nestjs/core/scanner.js:170:17
    at Set.forEach (<anonymous>)
    at calculateDistance (/sandbox/node_modules/@nestjs/core/scanner.js:168:27)
    at DependenciesScanner.calculateModulesDistance (/sandbox/node_modules/@nestjs/core/scanner.js:174:9)
    at DependenciesScanner.scan (/sandbox/node_modules/@nestjs/core/scanner.js:28:14)
    at /sandbox/node_modules/@nestjs/core/nest-factory.js:92:17
    at Function.asyncRun (/sandbox/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
```

## Expected behavior/code

The application should load correctly, without unhandled exceptions coming from NestJS core, and potentially warn of any bad module dependencies.

## Environment
<pre><code>
Nest version: 7.4.2 -> 8.0.5

For Tooling issues:
- Node version: 14.8.0
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in this commit https://github.com/nestjs/nest/commit/0b64023fbd9746a93ae1957acead3a90207c98ea (and will be fixed in the next release very shortly).
