### ISSUE TITLE
non-secure POST request is interpreted as GET causing confusion or hard-to-find bugs

### ISSUE THREAD

**Issue by ferenci84** [nestjs/nest#7723]
## Current behavior
On production server, when POST endpoint called via http instead of https, it silently interpretes it as GET request.

## Input Code
Our code is under NDA, if needed, I can provide example code.

## Expected behavior
If this is a security feature, some notice should be shown to the developer.

## Possible Solution
It should either:
* Return an error http code
* Show a warning/error in the log
* Just allow POST with http, or have an explicit config option to turn on this feature

## Environment

<pre><code>
- Nest version: 7.6.13
- Node version: 12.20
- Platform:  Linux
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

Also, check with the minimum reproduction if this happens with just Express. It sounds like it would be an adapter problem, as Nest only tells the adapter what kind of routing to set up.

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be related to the framework but rather to the HTTP adapter you use (Express or Fastify). Please, report this issue in the corresponding library.
