### ISSUE TITLE
Selecting service using its name not work after upgrade from 7.x to 8.x

### ISSUE THREAD

**Issue by Mati365** [nestjs/nest#7724]
## Current behavior

Executing `app.select(Module).get('ServiceName')` not work after upgrade from 7.x to 8.x version. 

## Input Code

```ts
  const app = await NestFactory.create(AppModule);

  app.enableShutdownHooks();
  await (
    app
      .select(SomeModule)
      .get('ModuleService')
  );
```

it throws:
```
Error: Nest could not find ModuleService element (this provider does not exist in the current context)
```

but using 
```
app.select(SomeModule).get(ModuleService);
```
works

## Expected behavior

It should not throw error.

## Environment

<pre>
<code>
Nest version: >= 8.0.0 (feature works on 7.6.17)

For Tooling issues:
- Node version: 16.6.0
- Platform:  Linux
</code></pre>

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest/issues/7640#issuecomment-885811172
https://github.com/nestjs/nest/issues/7583#issuecomment-881209020
