### ISSUE TITLE
[WIP] Create Mock endpoints from Swagger decorators to help front and backend teams work together. 

### ISSUE THREAD

**Issue by marcfielding1** [nestjs/nest#7726]
## Is your feature request related to a problem? Please describe.
No. Not a problem, it's an enhancement.

## Describe the solution you'd like
I would like to implement a decorator that allows requests to select the API response they'd like from the swagger.

## Teachability, Documentation, Adoption, Migration Strategy
[WIP] I'm working on this - so in actual fact if you did this correcetly and Swagger became the source of truth you can even do things automatically like create AWS SAM, Serverless, Terraform automatically from this work if you do it right in the first place.

The initial feature would be to decorate empty endpoints with the right request/response/example objects and then inject a middleware that would return the mock response when the header is present.

## What is the motivation/use case for changing the behavior?
Swagger is a great way to communicate between various teams for API contracts, the problem is that agile teams spend a lot of time in meetings. Now as an API guy I sit in meetings with frontend/iOS/Android devs and the output is we agree on the API contract - until I have an endpoint that produces that they're blocked.

The solution would be that just be creating empty endpoints with the right decorators(swagger outputs) the FE teams should be able to specify perhaps X-MOCK-RESPONSE: 200 and then get the example response back from the swagger while the backend team completes the working code.

**Comment by kamilmysliwiec** [comment]
This sounds like something that could be implemented as a separate library and does not require modifications/updates on the framework's side. There are currently no plans to add such a feature to the core but if you decide to publish it as an NPM package, it would be great if you could post a link here and share it with others!
