### ISSUE TITLE
Can't use custom repositories in nest v8

### ISSUE THREAD

**Issue by lazaroofarrill** [nestjs/nest#7728]
## Current behavior
After upgrading my codebase to nest 8. My custom typeorm repositories stopped working.
When a I request a resource a get method not found exception.

## Input Code

```ts
@EntityRepository()
export class CustomRepo extends Repository<CustomEntity> {}
```

```ts
@InjectRepository(CustomRepo) _repo: CustomRepo
```

## Expected behavior

This pattern used to work in nest 7

## Environment

<pre><code>
Nest version: 8.0.4

 
For Tooling issues:
- Node version: 14
- Platform:  Linux

Others:
typeorm: 0.2.34
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by lazaroofarrill** [comment]
https://github.com/lazaroofarrill/nest_v8_custom_typeorm_repo_error

**Comment by jmcdo29** [comment]
`UserRepository` should be added to `TypeOrmModule.forFeature()` [as shown in the docs](https://docs.nestjs.com/techniques/database#custom-repository)

**Comment by lazaroofarrill** [comment]
I already tried that. Still not working.

**Comment by lazaroofarrill** [comment]
Yeah that was it. Thank you very much.

**Comment by ahmed-com** [comment]
> `UserRepository` should be added to `TypeOrmModule.forFeature()` [as shown in the docs](https://docs.nestjs.com/techniques/database#custom-repository)

Help!
I'm encountering that same issue now, and that's not what the docs say.
The docs say the **TypeOrmModule.forFeature()** takes an entity not a repository, and adding a repository to *forFeature()* yields an error

**Comment by micalevisk** [comment]
@ahmed-com the comment was made in 2021, man haha typeorm stuff changed a lot

We could help you on our [Discord](https://discord.gg/nestjs) server.
