### ISSUE TITLE
Any Kafka End-To-End test example in nestjs ?

### ISSUE THREAD

**Issue by cheikhnadiouf** [nestjs/nest#7735]
## Current behavior

THERE IS NO WORKING EXAMPLES OF KAFKA E2E TEST IN NESTJS  

## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/issues/1954
