### ISSUE TITLE
[discussion]: Should `DefaultValuePipe` accept a function to define query param default values dynamically?

### ISSUE THREAD

**Issue by hedgerh** [nestjs/nest#7746]
## Is your feature request related to a problem? Please describe.
I have a use case where the default value for a querystring parameter needs to be a date string that is computed based on the current date, e.g. the default value should be a date string that is 30 days before the date of the current request being handled.

The `DefaultValuePipe` only accepts a static value to use as a default when a query parameter value is missing. From the docs:

```js
@Query('activeOnly', new DefaultValuePipe(false), ParseBoolPipe) activeOnly: boolean,
@Query('page', new DefaultValuePipe(0), ParseIntPipe) page: number,
```

## Describe the solution you'd like
Could the `DefaultValuePipe` be extended to handle functions to compute default values dynamically? Something like:

```js
typeof this.defaultValue === 'function' ? this.defaultValue() : this.defaultValue;
```

So usage might look like:

```js
@Query('startDate', new DefaultValuePipe(() => get30DaysAgo()), DateParamPipe) startDate?: Date 
```

## Teachability, Documentation, Adoption, Migration Strategy
The docs on providing defaults in the Pipes documentation could be modified to include an example of this usage https://docs.nestjs.com/pipes#providing-defaults

## What is the motivation / use case for changing the behavior?
I outlined my specific use case above.  I wanted to propose this in case it's a common use case that should be handled by built-in pipes instead of needing a custom one.

**Comment by kamilmysliwiec** [comment]
There are no plans on adding more functionalities to the existing `DefaultValuePipe`, but it should be super simple to extend it with a custom implementation (just create a new pipe that extends the `DefaultValuePipe`).
