### ISSUE TITLE
Global modules doesn't work anymore since 8.0.0: Nest can't resolve the dependencies of the X from a global module.

### ISSUE THREAD

**Issue by hellokvn** [nestjs/nest#7755]
## Bug Report

Global Modules doesn't work as they did in version 7 and earlier.  I added the official ConfigModule, which I need to get my env-specific data for TypeOrm. ConfigModule is registered as global. Worked since the ConfigModule was released. It's not working since 8.0.0.

```
Nest can't resolve the dependencies of the TypeOrmConfigService. Please make sure that the "config" property is available in the current context.

Potential solutions:
- If ConfigService is a provider, is it part of the current TypeOrmCoreModule?
- If ConfigService is exported from a separate @Module, is that module imported within TypeOrmCoreModule?
  @Module({
    imports: [ /* the Module containing ConfigService */ ]
  })
```

I have also self-created global modules, which also doesn't work anymore. I tested it by removing ConfigModule and my TypeOrm service. 

I created a simple repository, created with nest-cli@7.6.0 and added ConfigModule, TypeOrm, a simple global module (GlobalsModule), and a simple normal module (CatModule). **On its very last commit**, I updated Nest to its latest version (currently 8.0.5). All global modules are throwing errors. I don't really get why. You can remove the ConfigModule and TypeOrm after you cloned the module to see further errors based on the GlobalsModule (the global module I created by myself).

## Input Code

https://github.com/hellokvn/nest-global-module

## Expected behavior

No errors.

## Environment

<pre><code>
Nest version: 8.0.0+

 
For Tooling issues:
- Node version: 12.22.1
- Platform:  macOS Big Sur 11.5
</code></pre>

Thank you for any help!

**Comment by jmcdo29** [comment]
Briefly looking at your reproduction, it looks like you're using a string for the injection token, which changed in v8. Instead, you should be using the class reference for the token

**Comment by hellokvn** [comment]
That's it. Thanks @jmcdo29

**Comment by maksugr** [comment]
@jmcdo29 Why documentation and migration guide didn't specify it?

**Comment by jmcdo29** [comment]
> @jmcdo29 Why documentation and migration guide didn't specify it?

Because using the string name of the class as the injection token was an undocumented method of doing the injection.

I've been wanting to make a mention as to the fact that it's changed, but haven't had the time to do so
