### ISSUE TITLE
RouterModule mapped paths are lost in e2e tests when closing the app after each test

### ISSUE THREAD

**Issue by elovin** [nestjs/nest#7761]
## Current behavior
During e2e testing I call `await app.close()` after each test run. Before each test I create a new application with the test module. This all works fine for the first test but after `await app.close();` has been called the path mapping is lost and `RouterModule.register` is not being called again (debugged it) and thus all test except for the first one result in a 404 error code. 

### All requests result in 404 except for the first test
```ts

import { Module } from '@nestjs/common';
import { RootControllerModule } from './controller/root-controller.module';
import { RouterModule } from 'nest-router';
import { ParentControllerModule } from './controller/parent-controllers.module';

@Module({
	imports: [
		RouterModule.register([
			{
				path: 'api',
				module: RootControllerModule,
				children: [
					{
						path: 'parent_controller_a',
						module: ParentControllerModule, // which has the controller with uri "child_controller_a"
					},
				],
			},
		]),
		ParentControllerModule,
		RootControllerModule,
	],
	controllers: [],
	providers: [],
})
export class AppModule {}


import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { AppModule } from '../src/app.module';
import * as request from 'supertest';

describe('AppController (e2e)', () => {
	let app: INestApplication;

	afterEach(async () => {
		await app.close();
	});

	beforeEach(async () => {
		const moduleFixture: TestingModule = await Test.createTestingModule({
			imports: [AppModule],
		}).compile();

		app = moduleFixture.createNestApplication();
		await app.init();
	});

        // works
	it('test a', () => {
		return request(app.getHttpServer()).post('/api/parent_controller_a/child_controller_a').expect(400);
	});

        // fails with 404 not found
	it('test b', () => {
		return request(app.getHttpServer()).post('/api/parent_controller_a/child_controller_a').expect(400);
	});
});

```

## Expected behavior
After some debugging It seems that `RoutingModule.register` is not being called again. 
I would expect that the paths are registered again with each new test module and app setup.
The [nest-router from nestjsx](https://github.com/nestjsx/nest-router) seems to do this and works as expected. 

## Possible Solution
I suppose this will be fixed when [nest-router from nestjsx](https://github.com/nestjsx/nest-router)  is merged ?
For the mean time nest-router can be used or the app has to be reused across all tests.
## Environment

<pre><code>
Nest version: 8.0.5

    "@nestjs/common": "8.0.5",
    "@nestjs/core": "8.0.5",
    "@nestjs/platform-express": "8.0.5",

 
For Tooling issues:
- Node version: 4.16.1
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
There's no plan to merge `nest-router` library to the `core`.

Please provide a minimum reproduction repository.

**Comment by elovin** [comment]
@kamilmysliwiec alright I will provide the repository later when I have the time. 

Regarding the nest-router library [according to the creator of that lib](https://github.com/nestjsx/nest-router/issues/136) the `RouterModule` in `nestjs` core is the same so this has already been merged ?
> Absolutely, there is no difference between this package and the one in the core, in fact, the code in the core is same. what happened is that we upstreamed this package code to be included into the core of Nestjs.

**Comment by elovin** [comment]
@kamilmysliwiec okay I uploaded a minimum repository [here](https://github.com/elovin/nestjs-routing-module-e2e) with two e2e test files one using the build in RouterModule and another using `nest-router` when you run `npm run test:e2e` 3 out of 4 test will pass, all test using `nest-router` pass, when using the build in `RouterModule` the second test (copy of the first) fails after creating a new app for the second test.

**Comment by kamilmysliwiec** [comment]
> Regarding the nest-router library, im confused because according to the creator of that lib the RouterModule in nestjs core is the same and has already been merged:

@elovin I've rewritten most of the underlying code (we're using different path concatenation techniques now so the final behavior may be different), although the public API remains the same.

@jmcdo29 looking into this rn!

**Comment by kamilmysliwiec** [comment]
Fixed in this commit https://github.com/nestjs/nest/commit/3657d5fb34cb373aad2d9b887ff13582ff476f4f Check out v8.0.6
