### ISSUE TITLE
StreamableFile is not accessible from @nestjs/common 

### ISSUE THREAD

**Issue by Lishenga** [nestjs/nest#7765]
## Current behavior
Module '"@nestjs/common"' has no exported member 'StreamableFile'.ts(2305)
```ts
import StreamableFile
```

## Expected behavior
I need to import the SreamableFile class so as to be able allow file downloads from my Nest app.

## Possible Solution
I would appreciate a suggestion for a solution.

## Environment

<pre><code>
Nest version: 7.5.4
@NestJs/Common version: ^7.5.1

 
For Tooling issues:
- Node version: v16.3.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Upgrade to v8

**Comment by kamilmysliwiec** [comment]
Upgrade to v8
