### ISSUE TITLE
beforeApplicationShutdown not called by NestMiddleware

### ISSUE THREAD

**Issue by artursudnik** [nestjs/nest#7768]
## Current behavior
I have defined a middleware 

```
@Injectable()
export class MyMiddleware implements NestMiddleware {
```

with the following hooks defined:

```
  async onModuleDestroy() {
    console.log('middleware onModuleDestroy');
  }

  async beforeApplicationShutdown(signal) {
    console.log(`middleware beforeApplicationShutdown (${signal})`);
  }

  onApplicationShutdown(signal) {
    console.log(`middleware onApplicationShutdown (${signal})`);
  }
```

```
[Nest] 26102  - 08/05/2021, 1:28:14 PM     LOG [NestFactory] Starting Nest application...
[Nest] 26102  - 08/05/2021, 1:28:14 PM     LOG [InstanceLoader] AppModule dependencies initialized +24ms
[Nest] 26102  - 08/05/2021, 1:28:14 PM     LOG [RoutesResolver] AppController {/}: +8ms
[Nest] 26102  - 08/05/2021, 1:28:14 PM     LOG [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 26102  - 08/05/2021, 1:28:14 PM     LOG [NestApplication] Nest application successfully started +1ms
^Cmiddleware onModuleDestroy
module onModuleDestroy
module beforeApplicationShutdown
middleware onApplicationShutdown (SIGINT)
module onApplicationShutdown
```

## Expected behavior

When an application receives a signal and closes, I'd expect all three hooks to be executed. Actually only `onModuleDestroy` and `onApplicationShutdown` are executed.

All three hooks are executed if for example defined for a module, not middleware.

Is this expected behavior and I have not read about something or a bug?

## Environment

<pre><code>
Nest version: 8.0.4
nodejs version: 14.16.1
</code></pre>

Problem is reproduced in the following repo: https://github.com/artursudnik/nestjs-middleware-hooks-problem

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by artursudnik** [comment]
@kamilmysliwiec reproduced here: https://github.com/artursudnik/nestjs-middleware-hooks-problem

**Comment by kamilmysliwiec** [comment]
Thanks! Fixed in this commit: https://github.com/nestjs/nest/commit/89c7c5009a8b4be032a7db76fa95577a35812aa5 I'll publish a new patch release very shortly
