### ISSUE TITLE
NATS Client-Proxy logging pings to console

### ISSUE THREAD

**Issue by Flusinerd** [nestjs/nest#7772]
## Current behavior
Currently every 2 minutes (default ping time) the logger will log the ping message to the console.

## Input Code
Minimum reproduction:
https://github.com/Flusinerd/nestjs-nats-ping

## Expected behavior
This type of message should not be logged when running without ``verbose`` or ``debug`` to decrease clutter in production logs.

## Possible Solution
The relevant part in the NATS client is:
https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-nats.ts#L57
One simple solution would be to check if ``status.type === 'pingTimer'``.

## Environment

<pre><code>
Nest version: 8.0.6

 
For Tooling issues:
- Node version: v14.15.4  
- Platform: Windows, Mac and Alpine Linux 

Others:

</code></pre>

**Comment by jmcdo29** [comment]
I think changing the method from `log` to `debug` is a good fix here, with making sure that we log that to debug only when it is a `pingTimer` status. Would you like to make a PR for it? I'm sure Kamil will have something to say on this as well, but we definitely don't want to clutter the logs by default

**Comment by Flusinerd** [comment]
Ye, I thought about somethink like this as well.
NATS Client options has ``verbose`` and ``debug``
![image](https://user-images.githubusercontent.com/22977969/128428701-4d8394b6-a7a5-476d-baaa-37b766427d7f.png)
![image](https://user-images.githubusercontent.com/22977969/128428720-4a9c47e6-05b0-4313-8d36-2ac62549dc9a.png)

I'm happy to make a PR, if the solution of checking either of these settings and then simply using an if to filter out the ``pingTimer`` status is fine :)

**Comment by kamilmysliwiec** [comment]
Fixed in this commit https://github.com/nestjs/nest/commit/f91cd20230ff9dc2d6d8f640e60523227008d37d I'll publish a new patch release very shortly!

**Comment by Flusinerd** [comment]
Is this released yet?
Since its commited on 6. August but 8.0.6 was released on 5. August?
