### ISSUE TITLE
[Feature] Enable overriding of global ValidationPipe in controller (as in #2390)

### ISSUE THREAD

**Issue by lucasvianav** [nestjs/nest#7779]
## Feature Request

Add an option to make local pipes override global ones.

## Is your feature request related to a problem? Please describe.

Not really a problem but it's due to a global ValidationPipe taking precedence over a local one.

## Describe the solution you'd like

I would like to use a global validation pipe and be able to override it at module/controller/method level in order to specify different options when needed.

## What is the motivation / use case for changing the behavior?

I have a project in which I've the ValidationPipe globally in main.ts:

```
async function bootstrap () {
    const app = await NestFactory.create(AppModule)
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }))
    useContainer(app.select(AppModule), { fallbackOnErrors: true })
    await app.listen(process.env.API_PORT || 3000)
}
bootstrap()
```

But I have some classes with different validations depending on the group used, like so:
```
export class SocialMediaDto {
    @IsEnum(AllowedMemberSocialMedia, { groups: ['member'] })
    @IsEnum(AllowedCompanySocialMedia, { groups: ['company'] })
    @IsNewSocialMedia({ always: true })
    name: string

    @IsSocialMediaValueOK({ always:  true })
    value: string
}
```

The method that creates social media for a member would validate with group 'member' and the method that creates social media for the company would validate with group 'company'. 

I would like to use the global validation pipe (in order to validate the majority of classes that do not use different groups) and be able to override it at module/controller/method level in order to specify a group when needed.

Another use case is the one described in #2390.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.
