### ISSUE TITLE
How can i get the websocket client in controller

### ISSUE THREAD

**Issue by acodercat** [nestjs/nest#7780]
How can i get the websocket client in controller.

I need to emit a websocket message in the controller.

**Comment by Tony133** [comment]
Hi @acodercat, if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support. 

The NestJS Core Team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
