### ISSUE TITLE
Interceptors are not being called after request execution

### ISSUE THREAD

**Issue by wowjeeez** [nestjs/nest#7781]
## Current behavior
Interceptor observable pipe functions are not being called after request execution. (neither with `@UseInterceptors` or global)
## Input Code

```ts
import { Injectable, NestInterceptor, ExecutionContext, CallHandler, Logger } from '@nestjs/common';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { Request } from 'express';

@Injectable()
export class ProfilerInterceptor implements NestInterceptor {
  private readonly logger = new Logger(ProfilerInterceptor.name)
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    //const now = Date.now();
    this.logger.debug(`Intercepting request on: ${context.switchToHttp().getRequest<Request>().path}`)
    const now = Date.now();

    return next.handle().pipe(
        map((data) => {
          this.logger.debug(`Request finished in: ${Date.now() - now}`)
          return { respTime: Date.now() - now, ...data };
        }),
      );
  }
}
```
(NOTE: I tried the interceptor showed [here](https://docs.nestjs.com/interceptors#aspect-interception), it didn't work either)
## Expected behavior
Pipe functions being called and executed.

## Possible Solution
It was already marked as fixed in #1016
## Environment

<pre><code>
Nest version: 8.1.1

 
For Tooling issues:
- Node version: 16.6.0
- Platform:  Windows

Others:

PM: yarn
IDE: Webstorm
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by wowjeeez** [comment]
I figured out it was an issue on my end (I was throwing an error), sorry for wasting your time, closing.
