### ISSUE TITLE
Logger doesn't seem to fail gracefully

### ISSUE THREAD

**Issue by stevenadams** [nestjs/nest#7782]
## Potential Commit/PR that introduced the regression**
Might have been this one: https://github.com/nestjs/nest/pull/6221

## Describe the regression
When we run our application on AWS we use the built in global JS console, specified in options.logger in NestFactory. I wasn't around when this was decided I guess it reduced the noise of the logs 🤷. Anyway, it used to fail gracefully when you would do this.logger.verbose() - there would just be no output as verbose doesn't exist on console. We recently upgraded to v8 from v6 and this no longer seems to be the case. Getting lots of "_a.verbose is not a function" errors (_a is just what it was compiled to in TS when the error was logged).  

## Input Code
Private enterprise code but issue _feels_ pretty general.

## Expected behavior/code
It would be good if it still failed gracefully I guess, but if erroring is the desired outcome then some advice on best approach for this scenario would be great :)

## Environment
<pre><code>
Nest version: 8.0.5

For Tooling issues:
- Node version: 12
- Platform:  Mac (local) Linux (remote) - same issue on both
</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Fixed in this commit https://github.com/nestjs/nest/commit/2d334271ec32adfa4f797a8fea38cdb849328aae and will be published as part of the next patch release very shortly :)
