### ISSUE TITLE
Add support for "disconnecting" event on Websockets

### ISSUE THREAD

**Issue by njsubedi** [nestjs/nest#7784]
## Feature Request

While the Websockets package already has `OnGatewayInit`, `OnGatewayConnection` and `OnGatewayDisconnect` interfaces, a new interface `OnGatewayDisconnecting` is also required. The primary use case is that, when the OnGatewayDisconnect callback is fired, we can no longer have a list of rooms that the socket has joined. That's why we cannot call `socket.leave()` method, so the socket id may stay dangling in the room even after the client has disconnected. On the other hand, after adding `OnGatewayDisconnecting` interface,  `socket.rooms` will still contain the list of rooms that the socket has joined.

The [socket.io v4 documentation](https://socket.io/docs/v4/rooms/#Disconnection) describes this behavior. 

Looking at how the `DISCONNECT_EVENT` is handled, [it looks trivial](https://github.com/nestjs/nest/search?q=DISCONNECT_EVENT) to add the interface  It seems trivial to add the interface, but since I am just new to Nestjs and the source of the Websockets package, I opened an issue instead.

**Comment by jmcdo29** [comment]
Does `Ws` also support this event, or is it Socket.io v4 only?

**Comment by njsubedi** [comment]
`Ws` does not seem to support this. Checked the source; only the `close` event is fired after disconnection. Nothing like `closing`.

**Comment by kamilmysliwiec** [comment]
We can't add an interface for non-generic events (events that are not presumably available in other WS adapters, including `ws` adapter). Still, you should be able to add such an event listener to your code because the `handleConnection` lifecycle hook receives the `socket` instance (client) reference as a first argument.
