### ISSUE TITLE
nest can`t build assest file in dist

### ISSUE THREAD

**Issue by CloudWoR** [nestjs/nest#7793]
I want use the configure, create a yaml configure file in application can build in dist, but the yaml configure file in library, can`t build assest in dist.
this is my minimum reproduction repository

https://github.com/CloudWoR/nestAssest.git

please use branch minimum

**Comment by jmcdo29** [comment]
Did you take just open **the same issue** in another repo? You already opened this in nestjs/nest-cli.

**Comment by CloudWoR** [comment]
> Did you take just open **the same issue** in another repo? You already opened this in nestjs/nest-cli.

year, A little anxious
