### ISSUE TITLE
Cannot import from apollo-server

### ISSUE THREAD

**Issue by silentlight** [nestjs/nest#7795]
## Current behavior
When I try to import errors from apollo-server I get type error:

```
node_modules/apollo-cache-control/dist/index.d.ts:24:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'cacheControl' must be of type '{ cacheHint: CachePolicy; setCacheHint(hint: CacheHint): void; cacheHintFromType(t: GraphQLCompositeType): CacheHint; }', but here has type '{ setCacheHint: (hint: CacheHint) => void; cacheHint: CacheHint; }'.
```

## Input Code
```ts
import { AuthenticationError, ForbiddenError } from 'apollo-server';
```

## Expected behavior
No TS errors.

## Environment

<pre><code>
Nest version: 8.0.2
 
For Tooling issues:
- Node version: 14.15.0
- Platform:  MacOS

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
