### ISSUE TITLE
not able to access this.server.of where this.server is the socket.io server instance.

### ISSUE THREAD

**Issue by rajneesh3923** [nestjs/nest#7796]
## Current behavior
not able to access this.server.of in my websocket gateway where the server is the socket.io server instance.

## Input Code

```ts

  @WebSocketServer()
  private server: Server;

  this.server.of('/userstatus').emit('userStatus', {
          status: UserStatus.OFFLINE,
          userId: user.id,
        });
```

## Expected behavior
this.server.of() should be working so that I can send messages to other namespaces.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
