### ISSUE TITLE
Mongo-typeorm uses mongoDB v4 but this is not supported by typeorm

### ISSUE THREAD

**Issue by knopkem** [nestjs/nest#7799]
## Current behavior
running the nestjs provided example, doesn't work, because it uses mongodb 4 which is not supported by typeorm

see: https://github.com/nestjs/nest/blob/master/sample/13-mongo-typeorm/package.json

## Expected behavior
* it should reference a version that works

## Possible Solution
* downgrade dependency

**Comment by jmcdo29** [comment]
Would you like to open a PR downgrading the mongo dependency?

**Comment by knopkem** [comment]
Sure.

**Comment by knopkem** [comment]
https://github.com/nestjs/nest/pull/7800

**Comment by kamilmysliwiec** [comment]
Merged
