### ISSUE TITLE
Extract Eaxample from Repo

### ISSUE THREAD

**Issue by FrancisVarga** [nestjs/nest#781]
Hi currently it's very hard to contribute in the examples since it's inside of the library, isn't it easier to extract them and add them as example repository so we can add new samples? 

U cold also just open a repository and we can migrate nor build new samples :).

**Comment by kamilmysliwiec** [comment]
Why is it difficult? The "Pull requests" section is always open - everyone is invited to create a new example. If it brings new value to the people, I'd merge it with pleasure :)
