### ISSUE TITLE
Table Inheritance not working 

### ISSUE THREAD

**Issue by tahir-jamil** [nestjs/nest#7812]
I am using Typeorm with nest js but inheritance is not working
Following image is the result as you can see it has no properties but
![image](https://user-images.githubusercontent.com/40952630/128871706-a78d424b-2bc0-4bca-b47b-1c44a2f845a5.png)

we have properties in entity table
![image](https://user-images.githubusercontent.com/40952630/128871976-36adb1d2-0b96-4915-87e8-e65319a57fad.png)
![image](https://user-images.githubusercontent.com/40952630/128872067-82523881-8490-4d60-b832-ece13bf2c66b.png)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
