### ISSUE TITLE
Graphql Exception filter makes NotFoundException not working

### ISSUE THREAD

**Issue by NykolaySavin** [nestjs/nest#7813]
## Current behavior
 
We have Graphql Exception filter for error logging. 
It is registered globally.
Now we are trying to request any endpoint, that is not under /graphql - nothing is returned, timeout. If we stop using this exception filter - everything start working good and 404 is returned. While debugging I see that `BaseExceptionFilter` will be used in case if no filter is use globally. Trying to add BaseExceptionFilter manually after our complex LoggerExceptionFilter did not help

## Input Code

```ts
app.useGlobalFilters( new LoggerExceptionFilter(app.get(Logger))

@Catch()
export class LoggerExceptionFilter implements GqlExceptionFilter {
  constructor(private logger: Logger) {}
  catch(exception: unknown, host: ArgumentsHost): any {
    if (exception instanceof Error) {
      const gqlHost = GqlArgumentsHost.create(host);
      const gqlContext = gqlHost.getContext();
      const req = gqlContext.req;
      if (req) {
        this.logger.error(
          {
            message: `Error: ${exception.message}`,
            type: 'error',
            stack: exception.stack,
            requestId: req.headers['request-id'],
          },
          exception.stack,
        );
      } else {
        this.logger.error(
          {
            message: `Error: ${exception.message}`,
            type: 'error',
            stack: exception.stack,
          },
          exception.stack,
        );
      }
    }
    return exception;
  }
}
```

## Expected behavior
404 error returned even if Graphql Exception Filter is used

## Environment

<pre><code>
Nest version: 8.0

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
