### ISSUE TITLE
NatsError: CONNECTION_REFUSED

### ISSUE THREAD

**Issue by CloudWoR** [nestjs/nest#7819]
## Bug Report
NatsError: CONNECTION_REFUSED

## Current behavior

I tried to open a microservice server based on Nats. According to the configuration of the official website, I ran the code and found that NATs reported an error natserror: connection_ REFUSED
## Input Code

```ts
import { NestFactory } from '@nestjs/core';
import { MicroserviceOptions, Transport } from '@nestjs/microservices';
import { BrokerNatsModule } from './broker-nats.module';

async function bootstrap() {
  const app = await NestFactory.createMicroservice<MicroserviceOptions>(
    BrokerNatsModule,
    {
      transport: Transport.NATS,
      options: {
        servers: ['nats://localhost:4222'],
        queue: 'BROKER_NATS',
      },
    },
  );
  await app.listen();
}
bootstrap();
```

## Expected behavior
UnhandledPromiseRejectionWarning:
NatsError: CONNECTION_REFUSED
    at Function.errorForCode (D:\project\zhenmu\AutoPrint\server\node_modules\nats\nats-base-client\error.ts:115:12)

## Environment

<pre><code>
"nats": "^2.1.0"

 
For Tooling issues:
- Platform:  
Windows 10
Others:

</code></pre>

# my miniumu github branch: https://github.com/CloudWoR/nestAssest.git
please chooese the branch of miniumu,thank you.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by CloudWoR** [comment]
ok, thanks.
