### ISSUE TITLE
appContext.close() does not terminate process

### ISSUE THREAD

**Issue by dg-eparizzi** [nestjs/nest#7821]
## Current behavior
Calling `appContext.close()` in a standalone app should terminate the process, but it just hangs.

## Input Code

```ts
async function bootstrap() {
  const appContext = await NestFactory.createApplicationContext(AppModule);

  appContext.enableShutdownHooks();

  const appService = appContext.get(AppService);

  try {
    await appService.start();
  } catch (err) {
    console.error(err);
    console.log('Shutting down app...');
    await appContext.close();
  }
}

bootstrap();
```

## Expected behavior
When an unhandled exception occurs in the `appService.start()` method I want to catch it, log it and just finish the process so it can be restarted in a clean state.
When calling `appContext.close()` I see all the logs I've added in all the `onModuleDestroy` (disconnecting from RabbitMQ, flushing writes to db, etc). So while everything is gracefully destroyed, the process does not terminate.

## Environment

```
@nestjs/cli                         7.6.0
@nestjs/common                     7.6.18
@nestjs/config                      0.6.3
@nestjs/core                       7.6.18
@nestjs/platform-express           7.6.18
@nestjs/schedule                    0.4.3
@nestjs/schematics                  7.3.1
@nestjs/testing                    7.6.18
``` 
 
For Tooling issues:
- Node version: 14.17.3
- Platform:  Ubuntu 20.04

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
