### ISSUE TITLE
Default Logger is printing context as next message, instead of using it as actual context

### ISSUE THREAD

**Issue by kuskoman** [nestjs/nest#7822]
## Current behavior

Logger is printing second argument in log/debug/etc. functions in separate message, instead of setting it to be a context

## Input Code

```ts
[....]
const logger = new Logger('Bootstrap');
logger.debug('Message', 'Context');
[...]
```

Result:
```log
PS C:\Users\kkm\...> yarn start
yarn run v1.22.5
$ nest start
[Nest] 18996  - 11.08.2021, 12:50:37   DEBUG [Bootstrap] Message
[Nest] 18996  - 11.08.2021, 12:50:37   DEBUG [Bootstrap] Context
```

## Expected behavior

Expected logs:
```log
PS C:\Users\kkm\...> yarn start
yarn run v1.22.5
$ nest start
[Nest] 18996  - 11.08.2021, 12:50:37   DEBUG [Context] Message
```

## Environment
App 1:
<pre><code>
Nest version:
@nestjs/core@8.0.5
@nestjs/common@8.0.5
@nestjs/cli@8.1.1
</code></pre>

App 2:
<pre><code>
Nest version:
@nestjs/core@8.0.6
@nestjs/common@8.0.6
@nestjs/cli@8.1.11
</code></pre>

**Comment by kamilmysliwiec** [comment]
If you specified the context at the constructor level, this one passed as a second argument to the method will be interpreted as a regular message to be logged in the console. This is the expected behavior.

Please search through some of our old issues on this (this has been discussed in the past).
