### ISSUE TITLE
ModuleRef.get(Symbol) don't work under some cases

### ISSUE THREAD

**Issue by tonivj5** [nestjs/nest#7824]
## Current behavior
![image](https://user-images.githubusercontent.com/7110786/129062158-1f5dc82c-f4c2-4f2e-bd5f-d72e0fb5f674.png)
The order of console logs are unexpected 😕 ModuleRef returns an instance of the service without call its constructor.

## Input Code

```ts
import { Inject, Injectable, Module, Optional } from '@nestjs/common';
import { ModuleRef } from '@nestjs/core';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Injectable()
class SpecialService {
  constructor(public readonly service: AppService) {
    console.log(`Hey! SpecialService here, my constructor has been called and the AppService is inyected correctly: `, service);
  }
}

const SpecialSymbol = Symbol('Special Symbol');

// If you uncomment any of two comments below (or both), all works as expected
@Module({
  controllers: [AppController],
  providers: [AppService, /* SpecialService, */ { provide: SpecialSymbol, useClass: SpecialService }],
})
export class AppModule {
  constructor(
    @Optional() /* @Inject(SpecialSymbol) */ specialService: SpecialService,
    private moduleRef: ModuleRef,
  ) {
    // It works as expected...
    // console.log(`from ModuleRef`, this.moduleRef.get(SpecialService))
    console.log(`from ModuleRef`, this.moduleRef.get(SpecialSymbol))
    console.log(`from DI`, specialService)
  }
}

```

Repro: https://github.com/tonivj5/nestjs-bug-module-ref-symbol
- clone
- npm run start
- Play with the comments

## Expected behavior
If you uncomment `/* SpecialService, */` or `/* @Inject(SpecialSymbol) */` it works as expected.
![image](https://user-images.githubusercontent.com/7110786/129062659-276a775a-e343-4014-bc81-0b15da390a9d.png)

## Possible Solution
IDK

## Environment

<pre><code>
Nest version: 8.0.6

 
For Tooling issues:
- Node version: latest  
- Platform: Linux 

Others:

</code></pre>

**Comment by Minishlink** [comment]
Hi, I also noticed that (in [nestjs-console](https://github.com/Pop-Code/nestjs-console/commit/16f465524ab5a0c9abcb0380295de4225d09854f)), you can use .resolve to workaround this, although you'll need to have an asynchronous logic

**Comment by kamilmysliwiec** [comment]
I haven't reproduced your issue.

Original repo:
![image](https://user-images.githubusercontent.com/23244943/129169395-97003f5b-2709-4a42-a546-4c04642151ee.png)

Uncommented `/* SpecialService, */`:

![image](https://user-images.githubusercontent.com/23244943/129169450-5cd89d02-0905-4941-bee1-be36d943ebab.png)

Uncommented `console.log` 

![image](https://user-images.githubusercontent.com/23244943/129169592-22da5d99-bd62-4ca8-bfb8-b6e13dcee28e.png)

Tested on Node v12 and Node v16

**Comment by tonivj5** [comment]
@kamilmysliwiec Excuse me 😓, I uploaded the code with an uncommented line (explained above). I have updated the repo. Please retry again:
- git clone
- npm i
- npm run start

You will see the bug. As I have explained above:
> If you uncomment `/* SpecialService, */` or `/* @Inject(SpecialSymbol) */` it works as expected.

**Comment by jmcdo29** [comment]
Okay, I can see the `moduleRef.get` getting the service before the constructor is called with the current repo. What's the use case where you're using the `ModuleRef` to get the provider in the constructor instead of injecting the provider via the symbol? 

What I can tell is happening is that the `AppModule` class is being instantiated before the `SpecialService` class, and the `ModuleRef` can see that there's this `SpecialSymbol` token and grabs it, but it doesn't have a value associated to it yet, it's just an empty object.

The reason it works properly when you uncomment `SpecialService` or `@Inject(SpecialSymbol)` is because that optional dependency now actually exists in the container and Nest waits for it, but when you have `@Optional()` if the provider doesn't exist at all, it'll just be `undefined` as you've seen.

**Comment by kamilmysliwiec** [comment]
@tonivj5 thanks for updating the repro repository. @jmcdo29 explained what's happening here in the post above.

Just to add my 2 cents here, you should never use `moduleRef` within the constructor, it's not designed to be used there.

**Comment by tonivj5** [comment]
Thank you @jmcdo29 & @kamilmysliwiec! I understand that it doesn't work "by design", it makes sense. 

> Just to add my 2 cents here, you should never use moduleRef within the constructor, it's not designed to be used there.

Yeah, it should be used in a later hook (as `onModuleInit`)

Thank you guys! :-)
