### ISSUE TITLE
How can i validate a data from rabbitmq?

### ISSUE THREAD

**Issue by BrunyC** [nestjs/nest#7825]
When I need validate a Body data from a Post request, I use @Body() data: createdDataDto for example. How can i validade the data when i received this data from rabbitmq.

I think some like:

@MessagePattern('some_queue')
    async addSomeContact(@Payload() data: createdDataDto, @Ctx() context: RmqContext) {}

But createdDataDto doenst works for this case. So how can i validade de data fields from rabbitmq?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
