### ISSUE TITLE
How to support @Put @Patch dispatch route?

### ISSUE THREAD

**Issue by muyu66** [nestjs/nest#783]
Examples:

	 @Controller('users')
	 class User
	 
	 @Put('/:id') @Patch('/:id') // eq: only @Put('/:id')
		public async update(

These code will only  generate "/users/:id  PUT"

	 @Controller('users')
	 class User
	 
	 @Patch('/:id') @Put('/:id') // eq: only @Patch('/:id')
		public async update(

These code will only generate "/users/:id  PATCH"

How to implement  **@Put('/:id') @Patch('/:id')** is equal to **"/users/:id  PUT" or "/users/:id  PATCH"**

**Comment by kamilmysliwiec** [comment]
Just create 2 different methods and if the behavior is equal, call the same service inside them.
