### ISSUE TITLE
Social Authentication

### ISSUE THREAD

**Issue by aleksadjukic** [nestjs/nest#7836]
I've seen a lot of developers complaining about Nest not having a good documentation for social authentication, including myself, as there is only like a couple of blog posts hacking away the google authentication using passport.
It would be awesome if there was a documentation update for passport, or **even better**, if there was a new feature that makes social authentication a breeze. I think this feature would really give Nest an edge over the competition.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
