### ISSUE TITLE
Feature request: Read metadata from UnaryCall using gRPC client

### ISSUE THREAD

**Issue by stemis** [nestjs/nest#7847]
## Is your feature request related to a problem? Please describe.
I would like to be able to read gRPC metadata when making a unary call with the gRPC client.
Currently, this is already possible with StreamCalls which is also properly documented, but not with the Unary Call's

Consider the following code:

**Simplified Provider:**
```typescript
{
    provide: 'SERVICE_GRPC',
    useFactory: () => {
        return ClientProxyFactory.create({
            transport: Transport.GRPC,
            options: {
                package: 'myPackage',
                protoPath: 'my.proto
                url: '127.0.0.1',
            },
        });
    }
},
```
**Simplified Class**
```typescript
interface SomeService {
  someGrpcMethod: (argument: Request) => Observable<Response>;
}

class SomeClass {
  constructor(@Inject('SERVICE_GRPC') private readonly _client: ClientGrpc) {}
  
  onModuleInit(): void {
    this._someService = this._client.getService<SomeService>('SomeService');
  }
  
  someMethod(): void {
    const observer = this._someService.someGrpcMethod({param1:true})
    // Need the metadata send by server here
    observer.subscribe(...);
  }
}
```

## Describe the solution you'd like

I would like to be able to read the metadata that is send by the server
The `client-grpc.js` file does currently not hook into the `call.on('metadata', (metadata) => ...)`, which is why the metadata is not accessible at all.

I am now using a workaround by calling the client directly:
```typescript
const client = this._client.getClientByServiceName('SomeService');

const addDriver = new Promise(async (resolve, reject) => {
    let metadata: Metadata | null = null;

    const call = client.someMethod({
        someParam: "someValue"
    }, (error: any, res: any) => {
        if (error) {
            reject({...error, metadata});
        } else {
            resolve({...res, metadata});
        }
    });

    call.on('metadata', (meta: Metadata) => {
        metadata = meta;
    });
});
```

## What is the motivation / use case for changing the behavior?
We are providing validation errors via the metadata to the client. However, this can now not be read.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past (check out older issues) and it's currently not on our radar. If you want to contribute to this issue, feel free to create a PR, I'd be more than happy to review it!

**Comment by 0x-stone** [comment]
> ## Feature Request
> ## Is your feature request related to a problem? Please describe.
> I would like to be able to read gRPC metadata when making a unary call with the gRPC client. Currently, this is already possible with StreamCalls which is also properly documented, but not with the Unary Call's
> 
> Consider the following code:
> 
> **Simplified Provider:**
> 
> ```ts
> {
>     provide: 'SERVICE_GRPC',
>     useFactory: () => {
>         return ClientProxyFactory.create({
>             transport: Transport.GRPC,
>             options: {
>                 package: 'myPackage',
>                 protoPath: 'my.proto
>                 url: '127.0.0.1',
>             },
>         });
>     }
> },
> ```
> 
> **Simplified Class**
> 
> ```ts
> interface SomeService {
>   someGrpcMethod: (argument: Request) => Observable<Response>;
> }
> 
> class SomeClass {
>   constructor(@Inject('SERVICE_GRPC') private readonly _client: ClientGrpc) {}
>   
>   onModuleInit(): void {
>     this._someService = this._client.getService<SomeService>('SomeService');
>   }
>   
>   someMethod(): void {
>     const observer = this._someService.someGrpcMethod({param1:true})
>     // Need the metadata send by server here
>     observer.subscribe(...);
>   }
> }
> ```
> 
> ## Describe the solution you'd like
> I would like to be able to read the metadata that is send by the server The `client-grpc.js` file does currently not hook into the `call.on('metadata', (metadata) => ...)`, which is why the metadata is not accessible at all.
> 
> I am now using a workaround by calling the client directly:
> 
> ```ts
> const client = this._client.getClientByServiceName('SomeService');
> 
> const grpcCall = new Promise(async (resolve, reject) => {
>     let metadata: Metadata | null = null;
> 
>     const call = client.someMethod({
>         someParam: "someValue"
>     }, (error: any, res: any) => {
>         if (error) {
>             reject({...error, metadata});
>         } else {
>             resolve({...res, metadata});
>         }
>     });
> 
>     call.on('metadata', (meta: Metadata) => {
>         metadata = meta;
>     });
> });
> ```
> 
> ## Teachability, Documentation, Adoption, Migration Strategy
> ## What is the motivation / use case for changing the behavior?
> We are providing validation errors via the metadata to the client. However, this can now not be read.

Thank you for your use case , i seek for metadata solution also.
