### ISSUE TITLE
Nest can't start if you generate a .ts migration with typeorm

### ISSUE THREAD

**Issue by Ahmad-RW** [nestjs/nest#7855]
## Current behavior
the issue happens when you generate a typeorm .ts migration. It'll go into a migrations folder. Then nest will try to restart since it's in watch mode. and there the issue happens.

## Sample of my migration

```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class init1629056474593 implements MigrationInterface {
    name = 'init1629056474593'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "challenger" ("id" SERIAL NOT NULL, "challengerName" character varying NOT NULL, "userId" integer, CONSTRAINT "REL_d4e8557a93f726529cf8b0d21e" UNIQUE ("userId"), CONSTRAINT "PK_0788fc5afc5650836ceaeab116e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permission" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT 
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_has_permission" DROP CONSTRAINT "FK_f5037fa234ce4d65b964dd59b0e"`);
        await queryRunner.query(`ALTER TABLE "user_has_permission" DROP CONSTRAINT "FK_8bfdb3d8279b50783f38891e499"`);
        await queryRunner.query(`ALTER TABLE "role_has_permission" DROP CONSTRAINT "FK_834ea967df63edbe515cb737ba8"`);
    }

}

```

## Expected behavior
I don't think nest start should consider, in my instance, migration files. Since migration classes are separate from the Nest application source code.

## Possible Solution
Not sure but I think the issue is with typescript configuration not nest it self

## Environment

<pre><code>
Nest version: 8.0.2

</code></pre>

ormconfig.json
<pre><code>

{
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username" : "xyz",
    "password" : "zyx",
    "database" : "test",
    "entities": ["dist/**/*.entity{.ts,.js}"],
    "synchronize": false,
    "autoLoadEntities" : "true",
    "migrationsTableName": "migration",
    "migrations": ["migration/*.ts"],
    "cli": {
      "migrationsDir": "migration"
  }
  }
 </code></pre>

tsconfig.json
<pre><code>

{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true
  }
}

 </code></pre>

## Exception I'm getting 
<pre><code>
import {MigrationInterface, QueryRunner} from "typeorm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at \src\util\DirectoryExportedClassesLoader.ts:41:22
    at Array.map (<anonymous>)
    at Object.importClassesFromDirectories 
</code></pre>

**Comment by jmcdo29** [comment]
This is how `tsc --watch` would work in general. You can specify what folders to include in the tsconfig so that the migrations directory is ignored. This is not an issue with nest, nor is there something we can (easily) do about it.

**Comment by Ahmad-RW** [comment]
> 
> 
> This is how `tsc --watch` would work in general. You can specify what folders to include in the tsconfig so that the migrations directory is ignored. This is not an issue with nest, nor is there something we can (easily) do about it.
> 
> Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

so internally npm run start:dev will eventually call tsc --watch?

**Comment by jmcdo29** [comment]
Yes it does.
