### ISSUE TITLE
Provide PRECONDITION_REQUIRED in enum HttpStatus

### ISSUE THREAD

**Issue by juergenzimmermann** [nestjs/nest#7859]
## Is your feature request related to a problem? Please describe.
When _optimistic locking_ aka _optimistic concurrency control_ has to be implemented, then _PUT_ and _PATCH_ requests must include the header _If-Match_ with the current version. When the submitted version is not the current one, then the server sends the statuscode 'HttpStatus.PRECONDITION_FAILED' (= 412). However, when the header _If-Match_ is missing, then the server should send 428 (= PRECONDITION_REQUIRED).

## Describe the solution you'd like
It would be good, if HttpStatus provides PRECONDITION_REQUIRED with value 428 in https://github.com/nestjs/nest/blob/master/packages/common/enums/http-status.enum.ts#L41.

## Teachability, Documentation, Adoption, Migration Strategy
It's related to _optimistic locking_ aka _optimistic concurrency control_ as described in e.g. https://en.wikipedia.org/wiki/Optimistic_concurrency_control

## What is the motivation / use case for changing the behavior?
It's not a change, it's an additional behavior. See the motivation above.

**Comment by kamilmysliwiec** [comment]
Added in this commit https://github.com/nestjs/nest/commit/2405b66075d1e5108f611752598c185fa52ca4e5 Will be published as part of the next release

**Comment by juergenzimmermann** [comment]
@kamilmysliwiec Thank you very much for the immediate support.
