### ISSUE TITLE
@nestjs/microservices: set headers to NATS when publishing messages

### ISSUE THREAD

**Issue by kvandake** [nestjs/nest#7863]
## Feature Request

I use NATS for communicate between microservices built on nest.js.
I want to use [headers](https://nats.io/blog/headers-java-client/) from NATS, but I didn`t find some information about it.
I found an example in [official repo](https://github.com/nats-io/nats.js#headers). I think we can put headers in [this lines](https://github.com/nestjs/nest/blob/986dacfd4cb46ca4a350d70cbe9582cfcad2ba42/packages/microservices/client/client-nats.ts#L117).

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
