### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by manuel-alvarez-antelo** [nestjs/nest#7870]
## Bug Report

When I execute npm run build (nest build) it happen this compilation error:

node_modules/@nestjs/common/services/console-logger.service.d.ts:25:43 - error TS1256: A rest element must be last in a tuple type.

25     log(message: any, ...optionalParams: [...any, string?]): void;

How can solve this?

Best regargs

**Comment by jmcdo29** [comment]
Upgrade your Typescript version, the error should go away
