### ISSUE TITLE
ConsoleLogger ismissing in 8.0.6

### ISSUE THREAD

**Issue by manju-reddys** [nestjs/nest#7872]
## Current behavior
`ConsoleLogger` not exported or available in `@nestjs/common`

## Expected behavior
As documented [here](https://docs.nestjs.com/techniques/logger#extend-built-in-logger), the `ConsoleLogger` should be available in `@nestjs/common`

## Possible Solution
Missing export?

## Environment

<pre><code>
Nest version: 8.0.6

Others:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/1906881/129668957-0e405641-60c1-4790-85f4-bdadef0a1c76.png">

<img width="727" alt="image" src="https://user-images.githubusercontent.com/1906881/129669035-47bfcc3f-d837-4d5e-b258-70505fde416b.png">

**Comment by jmcdo29** [comment]
Make sure your common and core packages are on v8
