### ISSUE TITLE
app.useGlobalPipes() is not adding global pipes to app as doc is explaining

### ISSUE THREAD

**Issue by goulaheau** [nestjs/nest#7873]
## Current behavior
Using app.useGlobalPipes() is not adding pipes to the app.

## Input Code
Using the code from the doc at https://docs.nestjs.com/techniques/validation#auto-validation
```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe());
  await app.listen(3000);
}
bootstrap();
```

## Expected behavior
Should add ValidationPipe as a global pipe.

## Possible Solution
The only fix I found is to reassign app with the result of useGlobalPipes.

```ts
async function bootstrap() {
  let app = await NestFactory.create(AppModule);
  app = app.useGlobalPipes(new ValidationPipe());
  await app.listen(3000);
}
bootstrap();
```

If it's the expected behaviour, this documentation has to be changed : https://docs.nestjs.com/techniques/validation#auto-validation

## Environment

<pre><code>
Nest version: 8.0.0
 
For Tooling issues:
- Node version: XX  14.17.0, 14.17.5, 16.6.2
- Platform:  Windows 10
Others:
</code></pre>

**Comment by kamilmysliwiec** [comment]
We have this covered in e2e tests so this is very likely something wrong with your project. 
Please provide a minimum reproduction repository (in codesandbox/stackblitz in the best-case scenario).

**Comment by goulaheau** [comment]
After verification, you're right. 
That wasn't working but that should be an other thing that wasn't working.
Sorry.

**Comment by TEHbKA-dev** [comment]
When including the useGlobalPipes(new ValidationPipe()) method, we get an error that there is no such classToPlain and plainToClass method. The NESTJS dependencies say that we can use any version of the class-transformer library. Only since version v0.4.1 the classToPlain and plainToClass methods have been replaced with instanceToPlain and plainToInstance.
Alternatively, then package.json for the class-transformer library, specify the version v0.4.0

**Comment by kamilmysliwiec** [comment]
@TEHbKA-dev 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. This has been discussed many times in the past. We are using GitHub to track bugs, feature requests, and potential improvements.
