### ISSUE TITLE
v8 AllExceptions filter receiving error instead of exception

### ISSUE THREAD

**Issue by pgg** [nestjs/nest#7875]
## Current behavior
```
@Catch()
export class AllExceptionsFilter extends BaseExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost) {
    console.log({ error: exception instanceof Error, http: exception instanceof HttpException })
    super.catch(exception, host);
  }
}
```
in controller: ```throw new HttpException('boom', 400);```
prints: ```{ error: true, http: false }```

## Expected behavior
should print: ```{ error: true, http: true }```

## Possible Solution
likely to do with rxjs 7 wrapping Errors for inproved stack trace

## Environment

<pre><code>
Nest version: 
@nestjs/common@8.0.6
@nestjs/config@1.0.1
@nestjs/core@8.0.6
@nestjs/platform-express@8.0.6
@nestjs/platform-fastify@8.0.6
@nestjs/schematics@8.0.2
@nestjs/testing@8.0.6
rxjs@7.3.0
 
Node version: v16.6.1
Platform:  mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by pgg** [comment]
was wrapping in app wide logging interceptor
