### ISSUE TITLE
How can we use @Tree('closure-table') in NestJs?

### ISSUE THREAD

**Issue by vifattahi** [nestjs/nest#7878]
I want use @Tree('closure-table') so I have the below method and entity:
```
 public async create(createCategoryDto: CreateCategoryDto) {
    try {
      const manager = getManager();
      const category = await this.categoryRepository.create(createCategoryDto);
      return await manager.save(category);
    } catch (e) {
      throw e;
    }
  }
```
And entity:
```
import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
  Tree,
  TreeChildren,
  TreeParent,
} from 'typeorm';

@Entity()
@Tree('closure-table')
export class Category {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @TreeChildren()
  children: Category[];

  @TreeParent()
  parent: Category;
}
```
but this one can't create the tree, Is there anyone that knows the problem?

**Note**: Examples of typeorm document are very simple.

[Stackoverflow](https://stackoverflow.com/questions/68819910/how-can-we-use-treeclosure-table-in-nestjs)  questions link.

**Comment by Tony133** [comment]
Hi @vifattahi,  if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support. 

Try asking this question there too.

Nest's core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by vifattahi** [comment]
> Hi @vifattahi, if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.
> 
> Try asking this question there too.
> 
> Nest's core team uses GitHub to track bug reports, feature requests, and regressions.


Tanks a lot.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
