### ISSUE TITLE
Using custom logger, like console, should print out timestamp diff when using Logger

### ISSUE THREAD

**Issue by ZanMinKian** [nestjs/nest#7883]
## Is your feature request related to a problem? Please describe.
```ts
// main.ts
app.useLogger(console)

// app.controller.ts
import { Logger } from '@nestjs/common'
@Controller()
export class AppController {
  private readonly logger = new Logger(AppController.name, {
    timestamp: true
  })

  @All('*')
  async all(): Promise<void> {
    this.logger.log('hello')
  }
}
```
Running the code above, when visiting the http api, my expectation is print out: `hello AppController +1000ms`. However, the console print out `hello AppController`.

In my opinion, code like `app.useLogger(xxx)` is a way to change a logger adapter. I want to always use `Logger` which exported from `'@nestjs/common'`  in my project. When using `app.useLogger(xxx)`, I can easily change the logger adapter just in one line code.

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by kamilmysliwiec** [comment]
In v8, `ConsoleLogger` contains logic for printing messages out to the console (and calculating timestamp). `Logger` is just a simple wrapper that passes down the `timestamp` option down to the default logger constructor, and we made this decision to remain "almost backward compatible" (introduce fewer breaking changes). If you want timestamps to be printed out in your custom logger as well, you should implement this logic in your custom logger class.
