### ISSUE TITLE
All the routes returning 404

### ISSUE THREAD

**Issue by karankumarshreds** [nestjs/nest#7884]
## Bug Report
All the routes are returning 404 response.

## Current behavior
All the routes are returning `404` response after creating a middleware (as guided by the official docs)

Few sample routes: 
- `http://localhost:3000/auth/whoami` must return **403** or **200**
- `http://localhost:3000/auth/signup` must return **201** 

All the routes are returning `4041 instead.
```
{
    "statusCode": 404,
    "message": "Not Found"
}
```
## Input Code
Here is the link to the repository:

https://github.com/karankumarshreds/NestAPI

## Expected behavior
None of the routes are returning expected response other than 404.

For Tooling issues:
- Node version: ```v14.15.0```
- Platform:  Windows 
- Packages: 
```
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^1.0.1",
    "@nestjs/core": "^8.0.0",
```

**Comment by kamilmysliwiec** [comment]
Please provide a **minimum reproduction repository** (without entities/dependencies/extra modules - just controller + middleware)
