### ISSUE TITLE
503 error from Server-Sent Events if used through Gloo proxy

### ISSUE THREAD

**Issue by panuhorsmalahti** [nestjs/nest#7887]
## Current behavior
I'm getting a HTTP 503 error from an endpoint which implements Server-Sent Events (SSE) if I'm using Nest with Gloo Edge proxy.

The error doesn't trigger if I'm calling a container directly. The error also doesn't happen if I use alternative SSE implementation (e.g. nestjs-sse), which leads me to think that there is some minor issue with Nest's SSE implementation.

Response from curl:
```
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< vary: Accept-Encoding
< date: Wed, 18 Aug 2021 06:20:08 GMT
< server: envoy

upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

## Input Code

```ts
  @Sse("events/all")
  async events() {
    return listenObservable.pipe(
      map(({ type, entity }) => ({
        type,
        data: {
          entity
        }
      }))
    );
  }
```

## Expected behavior
I should not get 503 error.

## Possible Solution
See what's the difference between the SSE implementations to figure out the reason for the bug.

## Environment

<pre><code>
Nest version: 7.6.15

Others:
We're using Kubernetes and Gloo Edge Proxy.
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).
