### ISSUE TITLE
Exclude on setGlobalPrefix are applied wrong.

### ISSUE THREAD

**Issue by yusunglee2074** [nestjs/nest#7896]
## Current behavior
I want to apply middleware on the whole router except one.

## Input Code
```ts
// on main.ts
const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    bodyParser: false,
});
app.setGlobalPrefix('v1', {
    exclude: ['external/([^\\s]+)'],
});
```
```ts
// on app.module.ts
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    const webhookRoute = {
      method: RequestMethod.ALL,
      path: 'v1/orders/webhook',
    };
    consumer
      .apply(json(), urlencoded({ extended: true }))
      .exclude(webhookRoute)
      .forRoutes('*');
  }
}
```
## Expected behavior
```ts
@Controller('external')
export class ExternalSolutionsController {
    @Post()
    crate(@Body() body: any) {
        console.log(body) 
        // undefined with app.setGlobalPrefix('v1', { exclude: ['external/([^\\s]+)'] });
        // working well with app.setGlobalPrefix('v1')
        // both requests are touch this method.
    }
}
```
## Possible Solution
Maybe these two GlobalPrefix options and middleware consumers are influenced each other in nestjs source code.
No clue.

## Environment
Nest version: 8.0.6

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by yusunglee2074** [comment]
I realize that it is not the middleware side.

**Comment by yusunglee2074** [comment]
I have minimum reproduction repo.
https://github.com/yusunglee2074/nestjs-globalsetprefix-issue-reproduce
Sorry for that.

**Comment by jmcdo29** [comment]
It _looks_ like the middleware are being bound after the route handlers are, which is why you can't properly send in the JSON request. Odd that this only happens when the `exclude` is used with the `setGlobalPrefix`. Definitely a strange issue

**Comment by yusunglee2074** [comment]
If it is this shallow problem, I want to fix this problem.
If anyone do not mind to little help, I am ready to spend time on this issue.

**Comment by kamilmysliwiec** [comment]
Contributions are more than welcome!

**Comment by Zclhlmgqzc** [comment]
ref 
https://github.com/nestjs/nest/blob/47f05de6c1629ca7ede1691cc56f732898d74ecd/packages/core/router/router-explorer.ts#L210...L222
https://github.com/nestjs/nest/blob/5974b6fed12dfe3d0846cb48dcf2cb449bde2557/packages/core/router/route-path-factory.ts#L96...L116

packages\core\middleware\middleware-module.ts

```ts
  function isExcludedFromGlobalPrefix(
    path: string, 
    method?: RequestMethod, 
    prefixOptions: GlobalPrefixOptions<ExcludeRouteMetadata>) {
    ...
  }
```

registerHandler

```ts

    const prefix = this.config.getGlobalPrefix();
    const prefixOptions = this.config.getGlobalPrefixOptions();
 
    if (isExcludedFromGlobalPrefix(path, method, prefixOptions)) {
      path = addLeadingSlash(prefix)
    } else {
      const basePath = addLeadingSlash(prefix);
      if (basePath?.endsWith('/') && path?.startsWith('/')) {
        // strip slash when a wildcard is being used
        // and global prefix has been set
        path = path?.slice(1);
      }
     path = basePath + path;
    }
```

**Comment by alex73630** [comment]
Hi, on a project we work on, we are having the same issue.
Is one of those PRs will be merged soon?

What is needed in order to make one of those PRs ready to merge?
Thanks in advance!

**Comment by Zclhlmgqzc** [comment]
> Hi, on a project we work on, we are having the same issue.
> Is one of those PRs will be merged soon?
> 
> What is needed in order to make one of those PRs ready to merge?
> Thanks in advance!
> 

try [patch-package]( https://www.npmjs.com/package/patch-package)
to solve the problem temporarily

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8039
