### ISSUE TITLE
ModuleRef.get() throws an error when a string token is passed as an argument

### ISSUE THREAD

**Issue by sjalexandre** [nestjs/nest#7899]
# Bug Report

## Current Behavior
When retrieving a provider using `ModuleRef.get()` using a string token (e.g. `this.moduleRef.get('HelloService')`, the following error is generated:

```
Error: Nest could not find HelloService element (this provider does not exist in the current context)
```

Using `ModuleRef.get()` with a service class (e.g. `this.moduleRef.get(HelloService)` works as expected. 

This error first appeared after upgrading from `v7` to `v8`.

## Expected Behavior
`ModuleRef.get()` should work with a string token.

## Test Repo
Minimal repository to reproduce: https://github.com/sjalexandre/nestjs-bug-moduleRef

## Relevant Code

**hello.service.ts**
```typescript
import { Injectable } from '@nestjs/common';

@Injectable()
export class HelloService {
  getHello(): string {
    return 'Hello World!';
  }
}
```

**app.service.ts**
```typescript
@Injectable()
export class AppService {
  private helloService: HelloService;

  constructor(private readonly moduleRef: ModuleRef) {}

  onModuleInit() {
    // this.helloService = this.moduleRef.get(HelloService);
    this.helloService = this.moduleRef.get('HelloService');
  }

  getHello(): string {
    return this.helloService.getHello();
  }
}
```

## Environment
Nest version: 8.0.6
Node version: 14.15.0
Platform: macOS 11.4

**Comment by jmcdo29** [comment]
This is expected as in v8 Nest no longer uses class names as the token, but class references themselves. If you still want to use class names, and make the `moduleRef` work via strings, you can make a [custom provider](https://docs.nestjs.com/fundamentals/custom-providers). This has been discussed a few times since the v8 upgrade.
