### ISSUE TITLE
Log levels are not passed to custom logger

### ISSUE THREAD

**Issue by iamolegga** [nestjs/nest#7907]
## Current behavior

We can pass levels to logger along with using our custom implementation.

```ts
  const app = await NestFactory.create(AppModule, {
    // neither with buffering nor without it
    bufferLogs: true,
    logger: ['warn', 'error'],
  });
  app.useLogger(app.get(CustomLogger));
```

`LoggerService` has optional method `setLogLevels?(levels: LogLevel[]): void`, so it's expected that if a custom logger implements this method it should be called with passed log levels on startup. But this method is not called.

## Input Code

https://github.com/iamolegga/nestjs-custom-logger-levels

## Expected behavior

If custom logger implements `setLogLevels` method it should be called

## Possible Solution

Should be one of:

- If custom logger implements `setLogLevels` method it should be called when field `logger` is an array of levels
- drop `setLogLevels` method from `LoggerService`

## Environment

<pre><code>
Nest version: ^8.0.0

 
For Tooling issues:
- Node version: 12
- Platform: Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
`logger:` option should never be used in combination with the `useLogger` (these settings are designed to override each other).

> drop setLogLevels method from LoggerService

`setLogLevels` is present in the `LoggerService` interface (and it's optional) to support the following scenario:

```typescript
Logger.overrideLogger(YOUR_LOGGER);
const app = await NestFactory.create(AppModule, {
  logger: ['warn'],
});
```

**Comment by iamolegga** [comment]
@kamilmysliwiec thanks for your response, but then I have a couple more question on this topic:

1. yes, it works when I pass instance of CustomLogger when it'is not use DI :

```ts
  Logger.overrideLogger(new CustomLogger());
  const app = await NestFactory.create(AppModule, {
    logger: ['warn', 'error'],
  });
```

But when my `CustomLogger` needs to use DI I can only set it via `app.useLogger(app.get(CustomLogger))`. Am I right that in such case it's impossible to use `logger` field to pass levels?

2. Can we add all of this to docs? I believe that would be useful for creators of custom loggers  🙂

Thanks in advance ✌️
