### ISSUE TITLE
StreamableFile does not work with global interceptor ClassSerializerInterceptor

### ISSUE THREAD

**Issue by Zyles** [nestjs/nest#7909]
## Current behavior

Using: `app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)))` in main.ts breaks StreamableFile in a controller and returns the stream object instead of the file.

## Input Code

main.ts
`app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)))`

controller:
```
@Get('/file')
  async downloadFile(@Res({ passthrough: true }) res: Response) {
    try {
      const filename = 'test.csv'
      const filepath = `tmp/${filename}`

      const readStream = createReadStream(join(process.cwd(), filepath))

      res.set({
        'Content-Type': 'text/csv',,
        'Content-Disposition': 'attachment; filename="' + filename + '"'
      })

      // res.send(readStream)

      return new StreamableFile(readStream)

    } catch (error) {
      throw new Error(error)
    }
  }
```

Response:
```
{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":1,"path":"workdir\tmp\\test.csv","fd":null,"flags":"r","mode":438,"end":null,"autoClose":true,"bytesRead":0,"closed":false}
```

## Expected behavior

Return file.

## Possible Solution

Donno.

## Environment

<pre><code>
"@nestjs/core": "^8.0.6",
</code></pre>

**Comment by jmcdo29** [comment]
I actually found this being a bug the other day, just haven't made a PR for it. I'm thinking we can do a check for `value intanceof StreamableFile` and if so skip the `classToPlain()` method

**Comment by micalevisk** [comment]
@jmcdo29 so basically in https://github.com/nestjs/nest/blob/f4d7af83eaf51407adc3d7f52ee9c70553d9c207/packages/common/serializer/class-serializer.interceptor.ts#L50-L57 do something like

```diff
- if (!isObject(response) && !isArray)
+ if ((!isObject(response) && !isArray) || response instanceof StreamableFile)
```

here's the minimum repo: https://gitlab.com/micalevisk/nest-issue-7909

**Comment by jmcdo29** [comment]
Generally, yeah. That way we can just skip the `classToPlain` call

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/7911
