### ISSUE TITLE
Swagger Cli, detect entity type at runtime 

### ISSUE THREAD

**Issue by fatats96** [nestjs/nest#7914]
I was trying to code a BaseController for CRUD operations then all of the controllers will be extending that class but with Swagger, it can't get the type of the schema for the endpoint at runtime. It would be really cool to have that kind of improvement

**Comment by jmcdo29** [comment]
What would this `BaseController` look like and how would your controllers extend it? Does it use generics?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
