### ISSUE TITLE
Allow middlewares to be applied after all controllers

### ISSUE THREAD

**Issue by omidh28** [nestjs/nest#7918]
## Is your feature request related to a problem? 
This issue is already mentioned in #284 however in this case I'm having problem with services that requires their handlers to be used after all controllers (which are not developed by myself).

Take Sentry.io for example, It perfectly works with express but not with NestJs because its error handler middleware must be applied after all controllers. 

The problem is that NestJs applies all middlewares before controllers no matter what, If there was a feature to fix that, then using services like Sentry would be easier which eliminates the need to use a third party package or maintaining my own hack.

## Describe the solution you'd like
Not sure but maybe something like this:
```javascript
app.useAfter(middleware);
```

## What is the motivation / use case for changing the behavior?

More flexibility around using middlewares.

**Comment by micalevisk** [comment]
another ideia:

![changing MiddlewareConfigProxy to add afterRoutes method](https://user-images.githubusercontent.com/13461315/130493583-a5ccf424-6cf2-4f4c-9fb2-79881e28f5da.png)

**Comment by jmcdo29** [comment]
What about binding the error handler via an interceptor? Similar to how Nest has in the before section for multer in the `FileInterceptor`? At the moment, we aren't planning on allowing for post-request middleware

**Comment by omidh28** [comment]
> 
> 
> What about binding the error handler via an interceptor? Similar to how Nest has in the before section for multer in the `FileInterceptor`? At the moment, we aren't planning on allowing for post-request middleware

I'm not sure what you mean when you say bind it to interceptor, However I created an interceptor and somehow rewrote Sentry io middleware in interceptor. However it'd be nice to just plug the official middleware and use it because these kinds of solutions might require maintenance. 

Is there a reason that this features is not implemented yet?

**Comment by jmcdo29** [comment]
> I'm not sure what you mean when you say bind it to interceptor,

Calling would have been a better word for me to use.

> Is there a reason that this features is not implemented yet?

Because there's already interceptors, which can make this work pretty much as you've seen. It's not often that you need post-request middleware other than error handlers (exception filters), loggers (interceptors) and response mappers (also interceptors). There's already a good bit of complexity in how the proxy around express and fastify is set up, and managing another middleware layer between post-controller and response sent would be more to worry about in making the codebase more complex.

**Comment by omidh28** [comment]
Fair point even though we already have Express-only functionalities implemented. However I think we can close this at least for now.
