### ISSUE TITLE
DI failing to find repositories after upgrading to v8

### ISSUE THREAD

**Issue by Regan-entrostat** [nestjs/nest#7933]
## Potential Commit/PR that introduced the regression**
- Error occurred when upgrading from v7.6.18 to v8.0.6 on 24 Aug 2021

## Describe the regression
- Dependency injection errors are thrown as a result of Nest not being able to find an entity's repository. Repositories are all imported in a single module (database.module.ts) using the forFeature() function.

### app.module.ts
```ts
@Module({
    imports: [SharedModule],
    controllers: [AppController],
    providers: [
        NetworkInterceptorModelService,
        {
            provide: APP_INTERCEPTOR,
            useClass: NetworkLoggerInterceptor,
        },
    ],
})
```

### package.json
```ts
"dependencies": {
        "@mikro-orm/cli": "^4.5.7",
        "@mikro-orm/core": "^4.5.7",
        "@mikro-orm/nestjs": "^4.2.0",
        "@mikro-orm/postgresql": "^4.5.7",
        "@mikro-orm/reflection": "^4.5.7",
        "@mikro-orm/sql-highlighter": "^1.0.1",
        "@nestjs/common": "^8.0.6",
        "@nestjs/core": "^8.0.6",
        "@nestjs/jwt": "^8.0.0",
        "@nestjs/passport": "^8.0.1",
        "@nestjs/platform-express": "^8.0.6",
        "@nestjs/throttler": "^2.0.0",
```

### shared.module.ts
```ts
@Global()
@Module({
 imports: [LoggerModule, DatabaseModule, DeviceModule, AccountUserTrackerModule, TemplateModule],
    providers: [
        {
            provide: APP_INTERCEPTOR,
            useClass: ThrottlerInterceptor,
        },
        ProfanityCheckService,
    ],
    exports: [
        LoggerModule,
        DatabaseModule,
        MoyaMessagingModule,
        ThrottleStorageService,
        DeviceModule,
        ProfanityCheckService,
        AccountUserTrackerModule,
    ],
})

```

### database.module.ts
```ts
@Module({
    providers: [
        ....
    ],
    imports: [
        MikroOrmModule.forRoot(OrmConfig),
        MikroOrmModule.forFeature([
			.....
            AccountUserEncryption,
            AdminUser,
            Category,
            CategoryRelation,
            DataUsage,
            .....
            Profanity,
 			.....
            User,
        ]),
        forwardRef(() => UserModule),
        CsvModule,
    ],
    exports: [MikroOrmModule],
```

### network-logger-interceptor.service.ts
```ts
export class NetworkLoggerInterceptor extends NetworkInterceptorModelService implements NestInterceptor {
    constructor(
        private throttleStorageService: ThrottleStorageService,
        private dataUsageRepo: DataUsageRepository,
        private logger: LoggerService,
        protected reflector: Reflector,
    ) {
        super(reflector, logger);
    }
.
.
.
.
.
.
}

```
### profanity.repository.ts
```ts
@Repository(Profanity)
export class ProfanityRepository extends EntityRepository<Profanity> {
    ....
	....
	....
}
```

### profanity-check.service.ts
```ts
@Injectable()
export class ProfanityCheckService {
    constructor(private profanityRepository: ProfanityRepository) {}
    async containsProfanity(strings: string[]): Promise<{ check: boolean; terms: Profanity[] }> {
	....
	....
	....
    }
}

```

### Error Message
```ts
Error: Nest can't resolve dependencies of the ProfanityCheckService (?). Please make sure that the argument ProfanityRepository at index [0] is available in the SharedModule context.
```
## Expected behavior/code
NestJs should find the repositories and inject them appropriately.

## Environment
		"@mikro-orm/cli": "^4.5.7",
        "@mikro-orm/core": "^4.5.7",
        "@mikro-orm/nestjs": "^4.2.0",
        "@mikro-orm/postgresql": "^4.5.7",
        "@mikro-orm/reflection": "^4.5.7",
        "@mikro-orm/sql-highlighter": "^1.0.1",
        "@nestjs/common": "^8.0.6",
        "@nestjs/core": "^8.0.6",
        "@nestjs/jwt": "^8.0.0",
        "@nestjs/passport": "^8.0.1",
        "@nestjs/platform-express": "^8.0.6",
        "@nestjs/throttler": "^2.0.0",	

For Tooling issues:
- Node version: 14.17.5
- Platform:  Linux

Others:
- I can get rid of this particular error by putting MikroOrmModule.forFeature([Profanity]) in the imports section of profanity.module.ts file; except this is not a good solution as the errors continue onto the next repository until I come across a repository that is used across multiple services all provided in different modules.

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the MikroORM repository.
