### ISSUE TITLE
[Query] what is the way to access form-data type text property from request 

### ISSUE THREAD

**Issue by tkssharma** [nestjs/nest#7934]
I want to access the multipart ('form/multipart') POST request, with the field name "json"
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
