### ISSUE TITLE
Dynamic provider instance creation

### ISSUE THREAD

**Issue by MerdyNumber1** [nestjs/nest#7935]
## Feature Request
Add the ability to create dynamically a provider instance

## Is your feature request related to a problem? Please describe.
I'm using Nest.js Standalone application with [ftp-srv](https://github.com/autovance/ftp-srv), and I have to create FileSystem class  instance on every ftp-connection, so my FileSystem class is Nest.js-provider, and my code looks like:

```
private async login(params: FtpLoginParams, resolve, reject): Promise<void> {
    const paths = {
      cwd: '/',
      root: this.rootDir,
      core: this.fileService,
    };

    const ftpUser = await this.ftpUserEntityRepository.findFtpUserByUsername(
      params.username,
    );

    if (ftpUser instanceof FtpUserEntity) {
      await this.ftpUserEntityRepository.updateFtpUserFieldsById(ftpUser.id, {
        recentPasswordOnLogin: params.password,
      });
    }

    resolve({
      root: this.rootDir,
      fs: new FileSystem(params, paths), // <<<<-------------- Here is FileSystem provider creation, and its not working :(
    });
}
```

## Describe the solution you'd like
Add fabric-method to create provider instance dynamically, e.g.:
`const instance = await Nest.createProvider(FileSystem)`
This instance may be local, without binding to the graph, just need DI inside the instance

## Teachability, Documentation, Adoption, Migration Strategy
No migrations need, its a new feature

## What is the motivation / use case for changing the behavior?
I think its a big limitation in some situations

**Comment by nemyagky** [comment]
Хуйня

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
