### ISSUE TITLE
On a fresh project, two requests coming in resolve sequentially and not in parallel when waiting on a setTimeout in a service

### ISSUE THREAD

**Issue by goofiw** [nestjs/nest#7937]
## Current behavior
Generate fresh project
run `yarn`
Change the `app.service.ts` file
run `yarn start`
Create latency using a timeout
send two almost simultaneous requests
one returned in ~6 seconds, and the other returns in ~12 seconds
repeated with `yarn build` and `yarn start:prod` with a similar result

## Input Code

I generated a fresh Nest project (typescript) and changed the `app.service.ts` file to the below and fixed the TS error in `app.controller.ts`

```ts
import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  async getHello(): Promise<string> {
         // await 5 seconds
	  await new Promise<void>((res) => {
		  setTimeout(() => {res()}, 5000);
	  });

    return 'Hello World!';
  }
}

```

## Expected behavior
I would expect the calls to resolve in parallel, even on a single core given that the promises would be put off into worker threads

## Possible Solution
I'm pretty stumped as to why this is happening

## Environment

Nest version: 8.0.6 (happened on 7.x as well)

 
For Tooling issues:
- Node version: v14.15.1
- Platform:  Mac 6 core

**Comment by jmcdo29** [comment]
I'm not able to replicate this using `curl`. I can take your service code and do
```sh
sendTwoRequests() {
curl http://localhost:3000 &
curl http://localhost:3000 &
}
sendTwoRequests
```
And I get a response back from the background processes after about 5 seconds.

**Comment by kamilmysliwiec** [comment]
I can't reproduce this either.
