### ISSUE TITLE
I want to join the organization.

### ISSUE THREAD

**Issue by EXELANCE-LLC** [nestjs/nest#7978]
**Successful project, I'm looking into it. I like it so much. How about inviting me to the github organization?**

**Comment by jmcdo29** [comment]
Feel free to look through open issues and contribute with PRs as you're able. No need to be a part of the organization to contribute to the framework.

**Comment by smolinari** [comment]
This is not how it works @EXELANCE-LLC. It's OSS, so if you want to "join", do some work. Do PRs to fix an issue or add an improvement in the source code or the docs. [Join the community](https://discord.gg/RKRdYv4k) and help answer questions. Write articles or create tutorial videos about the tech and how to use it and promote it in the community. Be an evangelist. Get (deeply) involved. 

And depending on what you've done, you'll be asked to become a part of the team, automatically. 

Scott

**Comment by smolinari** [comment]
Doh. Jay was more succinct and quicker than I. 😁 

Scott

**Comment by EXELANCE-LLC** [comment]
I will write articles and help developers and enthusiasts. As you said, I am starting to work to contribute. I hope to be a part of your organization soon.
