### ISSUE TITLE
Nest can't resolve dependencies

### ISSUE THREAD

**Issue by menme95** [nestjs/nest#798]
## Current behavior
I'm trying to import a service in other service. They are in the same module:
<pre><code>
@Module({
	imports: [MongooseModule.forFeature([{ name: 'users_new', schema: UsersSchema }]), MongooseModule.forFeature([{ name: 'resetpassword', schema: ResetPasswordSchema }]), GenericModule],
	controllers: [UsersController, AuthenticateController],
	providers: [UsersService, AuthService, Config,]
})
</code></pre>
<pre><code>
constructor(@InjectModel('resetpassword') private readonly resetPasswordModel: Model<ResetPassword>) {
	}
</code></pre>

<pre><code>
constructor(@InjectModel('users_new') private readonly userModel: Model<UsersDto>, private readonly resetService: ResetPasswordService, private readonly config: Config)
</code></pre>

This is the error: 
Nest can't resolve dependencies of the UsersService (+, ?, +). Please verify whether [1] argument is available in the current context.
So I think the problem is in resetpassword service, Is there anything wrong?

<pre><code>
[System Information]
OS Version     : Windows 7
NodeJS Version : v10.0.0
NPM Version    : 6.0.0
[Nest Information]
microservices version : *
websockets version    : *
mongoose version      : 4.0.0
passport version      : 1.0.10
swagger version       : 2.0.0
testing version       : *
common version        : 5.0.1
core version          : 5.0.1
</code></pre>

**Comment by kamilmysliwiec** [comment]
The `ResetPasswordService` isn't defined in your `@Module()` metadata. Please, use StackOverflow (nestjs tag) for such questions.
