### ISSUE TITLE
Unable to upgrade to Nest 8

### ISSUE THREAD

**Issue by florianmartens** [nestjs/nest#7982]
## Bug Report

I'm having trouble upgrading from NestJS 7 -> 8. My project runs in a monorepo managed with Lerna.

My first approach was to run the upgrade via the CLI. Running `nest update --force' did simply delete all my @nest/* dependencies from node_modules as well as from package.json and resulted in an error message:

![Screenshot 2021-08-28 at 20 01 08](https://user-images.githubusercontent.com/48451846/131226797-62b7b352-6085-475a-86ba-6e9092723128.png)

My second approach was to manually upgrade the packages but this leads to a weird behavior where the installation of one package will remove another package from the `@nest/*` folder. In consequence, the packages would be missing and my app would not run.

The following dependencies result in the following `@nestjs/*` folder structure:

**Dependencies**

```
"dependencies": {
        "@nestjs/common": "^8.0.6",
        "@nestjs/core": "^8.0.6",
        "@nestjs/platform-express": "^8.0.6",
        "@nestjs/config": "^1.0.1",
        "@nestjs/jwt": "^8.0.0",
        "@nestjs/passport": "^8.0.1",
        "@nestjs/swagger": "^5.0.9",
        "@prisma/client": "2.25",
        "@types/bcrypt": "^5.0.0",
        "@types/handlebars": "^4.1.0",
        "@types/nodemailer": "^6.4.4",
        "@types/passport-google-oauth20": "^2.0.9",
        "@types/passport-jwt": "^3.0.5",
        "@types/passport-local": "^1.0.33",
        "bcrypt": "^5.0.1",
        "class-transformer": "^0.4.0",
        "class-validator": "^0.13.1",
        "draft-convert": "^2.1.11",
        "draft-js": "^0.11.7",
        "handlebars": "^4.7.7",
        "nodemailer": "^6.6.3",
        "passport": "^0.4.1",
        "passport-google-oauth": "^2.0.0",
        "passport-google-oauth20": "^2.0.0",
        "passport-jwt": "^4.0.0",
        "passport-local": "^1.0.0",
        "prisma": "2.25",
        "reflect-metadata": "^0.1.13",
        "rimraf": "^3.0.2",
        "rxjs": "^6.6.6",
        "swagger-ui-express": "^4.1.6"
    },
"devDependencies": {
        "@nestjs/cli": "^7.6.0",
        "@nestjs/schematics": "^7.3.0",
        "@nestjs/testing": "^7.6.15",
        "@types/express": "^4.17.11",
        "@types/faker": "^5.5.7",
        "@types/jest": "^26.0.22",
        "@types/node": "^14.14.36",
        "@types/supertest": "^2.0.10",
        "@typescript-eslint/eslint-plugin": "^4.19.0",
        "@typescript-eslint/parser": "^4.19.0",
        "dotenv": "^10.0.0",
        "dotenv-cli": "^4.0.0",
        "eslint": "^7.22.0",
        "eslint-config-prettier": "^8.1.0",
        "eslint-plugin-prettier": "^3.3.1",
        "faker": "^5.5.3",
        "jest": "^26.6.3",
        "prettier": "^2.2.1",
        "supertest": "^6.1.3",
        "ts-jest": "^26.5.4",
        "ts-loader": "^8.0.18",
        "ts-node": "^9.1.1",
        "tsconfig-paths": "^3.9.0",
        "typescript": "^4.2.3"
    },
```

**node_modules/@nestjs**

```
.
├── cli
└── schematics
```

When I downgrade to `Nest@7.x.x` I do not experience the bug.

**Comment by jmcdo29** [comment]
In general, it's best not to use `nest update` and to use a tool like [`ncc`]() or [`npm-check`]() for updating your dependencies. Or something like `yarn upgradeInteractive` or `pnpm upgrade -i` for the package manager's explicit interactive mode. The `nest update` feature was a bit experimental and not ass robust as full package manager implementations. We're looking at deprecating the method and cleaning up the CLI.

**Comment by florianmartens** [comment]
Thank you for your input, @jmcdo29 . I'm trying to investigate the issue a little further. At this point, I'm not sure if the issue really comes down to the updating-tool I'm using. No matter the update path, there seems to be something that triggers rewriting of the `@nestjs`  module folder. In consequence, only the folders `cli` and `schematics` are present in the node_modules folder.

If I remove the dependencies to `cli` and `schematics` the rewriting does not happen and the correct dependencies are present.

**Comment by florianmartens** [comment]
I now found an update path by removing the dev-dependencies to:
```
        "@nestjs/cli": "^8.1.1",
        "@nestjs/schematics": "^8.0.3",
```
And updating the all nest dependencies selectively (npm-check-updates):

`ncu '/^@nest.*/' -u`

Deleting `node_modules` and running `yarn install`.

(In case someone is trying to reproduce this, it's also important to delete `node_modules` and run a clean install and not simply upgrade dependencies in place)

**Comment by kamilmysliwiec** [comment]
Thanks for sharing your solution @florianmartens! 

As this doesn't seem to be related to the actual framework, I'll close this issue
