### ISSUE TITLE
Switching from Express (TypeScript) to NestJS

### ISSUE THREAD

**Issue by Mingyang-Li** [nestjs/nest#8001]
I'm been wondering if NestJS would be a better option than .NET for the following use cases in a startup scene with the following objectives:

1. Scalable - think Canva, Airbnb, Booking.com or Trivago
2. Fast development speed for MVPs
3. Great architecture
3. Easy to pick up for devs from all backgrounds (Node, C#, Java devs)
4. Easy to hire new devs (think uni student or new grads) to train, as we'll be on a smaller budget

The community for NestJS hasn't been as huge as .NET or Java etc, so I'm pretty keen to learn more from your early adopters.

**Comment by micalevisk** [comment]
this comment might help you https://www.reddit.com/r/node/comments/pa5go8/building_restful_apis_with_node_whats_your/ha2dg2b

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
