### ISSUE TITLE
SSE server doesn't dispose observable when reverse proxy is set

### ISSUE THREAD

**Issue by pacexy** [nestjs/nest#8006]
## Current behavior
I have a NX monorepo which the frontend port is 4200 and the server port is 3333, and proxy `http://localhost:4200/api` to `http://localhost:3333/api`. Even if the client has closed event source, the server will still emit the message.

## Input Code
```ts
@Sse('sse')
sse() {
  return interval(1000).pipe(
    map((_) => {
      console.log('emit')
      return { data: { hello: 'world' } }
    }),
  )
}
```

```ts
const eventSource = new EventSource('/api/sse')

// close the tab or call `eventSource.close`
setTimeout(() => {
  eventSource.close()
}, 3000)
```

## Expected behavior
The observable can be disposed correctly.

## Environment

<pre><code>
Nest version: 8.0.6

 
For Tooling issues:
- Node version: 16.0.0
- Platform:  Windows 10

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
I think this might be actually caused by the reverse proxy. I don't think there's anything we can do to fix this issue on our side, but correct me if I'm wrong!

**Comment by pacexy** [comment]
> I think this might be actually caused by the reverse proxy. I don't think there's anything we can do to fix this issue on our side, but correct me if I'm wrong!

That is to say, the reverse proxy shouldn't be used with Sse? Now I use CORS, and it works.

**Comment by kamilmysliwiec** [comment]
Check out this section https://webpack.js.org/configuration/dev-server/#devserverproxy
And if you won't find the solution, I'd suggest reporting this issue in this repository https://github.com/chimurai/http-proxy-middleware (that's what Webpack [and I'm guessing Nx as well?] uses under the hood)
