### ISSUE TITLE
UseGuards Doesn't Use Dependency Injection - Can't Override Guard

### ISSUE THREAD

**Issue by dima-gusyatiner** [nestjs/nest#8011]
## Current behavior
The documentation states [here](https://docs.nestjs.com/guards#binding-guards) that:
> ...we passed the RolesGuard type (instead of an instance), leaving responsibility for instantiation to the framework and enabling dependency injection.

So I'm expecting to "override" a guard with another, via the module's `providers`.
This doesn't work as expected.

Interestingly enough,
injecting the same service via the controller's constructor does yield the correct service, though.

## Input Code
Simple: https://github.com/dima-gusyatiner/nestjs-guards-override/tree/only-app-module
With Another module, using `exports`: https://github.com/dima-gusyatiner/nestjs-guards-override/tree/master

Controller:
```ts
@Controller()
@UseGuards(AuthGuard)
```

Module:
```ts
@Module({
  controllers: [AppController],
  providers: [
    {
      provide: AuthGuard,
      useClass: AuthOverrideGuard,
    }
  ],
})
```

## Expected behavior
I would expect `AuthGuard` to never even be constructed.
Instead, both classes are constructed, and `AuthGuard` is used as the guard.

## Environment
<pre><code>- Nest version: 8.0.6
- Node version: 16.8.0
- Platform: Linux</code></pre>

## StackOverflow
Also created a public question there:
https://stackoverflow.com/questions/69012560/useguards-doesnt-use-dependency-injection-cant-override-guard

**Comment by danielmwakanema** [comment]
I am not sure I understand it that well either but from what I saw:
- With UseGuards, the passed in class is not resolved as provider. Only when you declare the guard as a dependency. Just like in AppController, is it looked up in the provider scope.
- Sure the guards dependencies are resolved as providers within the calling module's scope but it itself is not. Just regular instantiation with dependency injection.
- I think that is why both guards are still created, just that AuthOverrideGuard, is registered as a provider.

That is why you get the following output:

```bash
[Nest] 77074  - 05/09/2021, 05:01:39     LOG [NestFactory] Starting Nest application...
Construct AuthOverrideGuard
Construct AuthGuard
AuthGuard
AppController AuthOverrideGuard {}
```

- this.guard is correctly resolved as AuthOverrideGuard from the provider scope

**Comment by kamilmysliwiec** [comment]
> So I'm expecting to "override" a guard with another, via the module's providers.

You can't override enhancers (interceptors, guards, pipes, or filters). You can only override providers.
