### ISSUE TITLE
calling a get route that has a path but no parameters is causing typeorm to automatically execute

### ISSUE THREAD

**Issue by MrAbdul** [nestjs/nest#8013]
## Current behavior

I have an api that has a get end point and I defined it as get("byInstitution") and then I am getting the institution id in the header, however whenever I hit it with postman I get an internal server error.
[Nest] 22804  - 09/01/2021, 8:22:09 PM   ERROR [ExceptionsHandler] invalid input syntax for type integer: "NaN"
QueryFailedError: invalid input syntax for type integer: "NaN"
I even added a console log inside the route handler and it doesnt seem to be called.

 

## Input Code

```ts
import { Controller, Get, Post, Body, Patch, Param, Delete, Headers, Header, ClassSerializerInterceptor, UseInterceptors } from '@nestjs/common';
import { courseDTO, courseService } from './course.service';
import { CreatecourseDto } from './dto/create-course.dto';
import { UpdatecourseDto } from './dto/update-course.dto';

@Controller('course')
export class courseController {
  constructor(private readonly courseService: courseService) {}

  @Post()
  create(@Body() createcourseDto: CreatecourseDto) {
    return this.courseService.create(createcourseDto);
  }

  @Get()
  findAll() {
    return this.courseService.findAll();
  }

  @Get(':id')
  findOne(@Param('id') id: string) {
    return this.courseService.findOne(+id);
  }
  //FIXME:wierd bug where if no parameter is found it throws typeorm errors
  @Get('byInstitution')
  @UseInterceptors(ClassSerializerInterceptor)
  async findOneByInstitution(@Headers('byInstitution') id:string):Promise<Map<String,courseDTO[]>> {
    console.log(id)
    // console.log(id)
    let courses = await this.courseService.findByInstitution(+id);
    return  courses
  }

  @Patch(':id')
  update(@Param('id') id: string, @Body() updatecourseDto: UpdatecourseDto) {
    return this.courseService.update(+id, updatecourseDto);
  }

  @Delete(':id')
  remove(@Param('id') id: string) {
    return this.courseService.remove(+id);
  }
}

```

## Expected behavior

I expected that the @Get('byInstitution') function executes when called.

## Possible Solution

a workaround I found was to add a parameter to the route like this
 @Get('byInstitution/:id')
and then just ignore that, and send 0 in postman, then it works fine.

## Environment
windows 10, with postgress running on docker and using VScode as IDE
<pre><code>
Nest version:8.1.1

 
For Tooling issues:
- Node version: v14.17.4  
- Platform:  Windows 

Others:

</code></pre>

**Comment by micalevisk** [comment]
what's the value of the parameter `id`? looks like you're end up passing some `NaN` value to `CourseService#findByInstitution` method, thus it will thrown an error that is translated to Internal Server Error

**Comment by jmcdo29** [comment]
Routes are registered in the order they appear in the class. In this case, you have 
```ts
@Get(':id')
```
before you have
```ts
@Get('byInstituion')
```
Because of this, when express is going through route matches, `byInstitution` matches `:id` and that route is triggered. Move the `@Get('byInstituion')` to be before the `@Get(':id')` route and this hould work fine.

For further support, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

If you think this is a bug please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by UrchenkoV** [comment]
@jmcdo29 This is the solution to the problem. Thanks.
