### ISSUE TITLE
Not able to find extended class

### ISSUE THREAD

**Issue by sirredd** [nestjs/nest#8015]
I am currently trying to create a unit test for a service. 
This service uses a User entity which extends a BaseEntity 
```
export class BaseEntity {
  @IsNumber()
  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn({ type: 'timestamptz', default: () => 'CURRENT_TIMESTAMP()' })
  createDate: DateTime;

  @UpdateDateColumn({ type: 'timestamptz', default: () => 'CURRENT_TIMESTAMP()' })
  updateDate: DateTime;
}


```

```
@Entity('Users')
@Unique(['NPI'])
export class User extends BaseEntity {
  @Column({ nullable: false })
  @IsString()
  authId: string;

  @Column({ nullable: true })
  @IsNumberString()
  NPI: string;

  @Column({
    type: 'enum',
    enum: MedicalTitle,
    default: MedicalTitle.NONE,
  })
  medicalTitle: MedicalTitle;

  @Column({ nullable: true })
  @IsString()
  firstName: string;

  @Column({ nullable: true })
  @IsString()
  middleName?: string;

  @Column({ nullable: true })
  @IsString()
  lastName?: string;
  ...

  @ManyToOne(() => PracticeRole, { eager: true })
  @JoinColumn()
  practiceRole: PracticeRole;

  @OneToMany(() => UserNotification, notification => notification.user)
  userNotifications: UserNotification[];

  @OneToMany(() => PracticeSystemRoleUser, practice => practice.user)
  practices: PracticeSystemRoleUser[];
}

```
But the test fails to find the BaseEntity from the User Entity. Here is the error.
```
Cannot find module 'src/entities/base.entity' from 'hcp/users/entities/user.entity.ts'
```
![image](https://user-images.githubusercontent.com/34552815/131724055-8ff9193b-f56f-4aec-8a60-e77a8ad669bb.png)

* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by KingDracula** [comment]
how to fix it ?
i also meet this problem

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest/issues/8015#issuecomment-910555035
