### ISSUE TITLE
Typescript compilation failed when mongoose schema is used in model 

### ISSUE THREAD

**Issue by tbhaxor** [nestjs/nest#8025]
## Current behavior

When i create schema from the class using `SchemaFactory.createForClass(Staff)` and use it as type in the `Model` in service, I get the error **'StaffSchema' refers to a value, but is being used as a type here. Did you mean 'typeof StaffSchema'?**

When i am using typeof StaffSchema, it is not showing name, email and other properties in intellisense, rather showing intellisense of schema (plugin, id, virtual).

![image](https://user-images.githubusercontent.com/28386721/132009097-fc4e54de-8713-42b7-a1bc-4694e680a728.png)

## Input Code

```ts
import { Prop, raw, Schema, SchemaFactory } from '@nestjs/mongoose';
import { StaffName, StaffRole } from '../dto/create-staff.dto';

@Schema()
export class Staff {
  @Prop(
    raw({
      first: { required: [true, 'Firstname is required'], type: String },
      last: { type: String, required: [true, 'Lastname is required'] },
    }),
  )
  name: StaffName;

  @Prop({ type: String, required: [true, 'Email is required'] })
  email: string;

  @Prop({ type: String, required: [true, 'Password is required'] })
  password: string;

  @Prop({ type: Number, default: StaffRole.SUPPORT })
  role: StaffRole;
}

export const StaffSchema = SchemaFactory.createForClass(Staff);
```

## Expected behavior

It should work as demonstrated in example

## Possible Solution

N/A

## Environment

<pre><code>
Nest version: 8.0.0

 
For Tooling issues:
- Node version: v14.17.4
- Platform:  Linux

Others:

</code></pre>

**Comment by micalevisk** [comment]
looks like you didn't follow the example properly

https://github.com/nestjs/nest/blob/99ee3fd99341bcddfa408d1604050a9571b19bc9/sample/06-mongoose/src/cats/cats.service.ts#L10

https://github.com/nestjs/nest/blob/99ee3fd99341bcddfa408d1604050a9571b19bc9/sample/06-mongoose/src/cats/schemas/cat.schema.ts#L4

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
