### ISSUE TITLE
Need to perform middlewares after route

### ISSUE THREAD

**Issue by dkduyanh** [nestjs/nest#8026]
Hello,

I need to implement API paths as bellow:

> http://localhost:3000/api/v1/xyz/customers/1

> http://localhost:3000/api/v1/xyz/products

(xyz is channel name defined in database)

I found some available techniques provided by Nests
- /api   --->  Global Prefix
- /v1    --->  Versioning
- /customer/:id, or /products    --->  Controller Route

Because the channel name is dynamic, so my idea is to define it as a param and use a middleware to verify if the channel is valid, then bind it into `req.channel` so that I can query data related to that channel.

### Customer Controller
```
@Controller({
  path: ':channel/customers',
})
export class CustomersController {
  constructor(private readonly customerService: CustomersService) {}

  @Get()
  async findAll(): Promise<any> {
    const customers = await this.customerService.findAll();
    return plainToClass(CustomerDto, customers, {
      excludeExtraneousValues: true,
    });
}
```

I need to perform a middleware instead of manually verifying the channel in each action. Anyone can suggest me a solution for this?

I also tried the NestMiddleware but it seems not confortable when manually parse channel name from the path.

Best Reards,

**Comment by Tony133** [comment]
Hi @dkduyanh, for this type of question I recommend that you use the support channel [discord](https://discord.com/invite/G7Qnnhy).

The NestJS Core Team uses GitHub to track bug reports, feature requests, and regressions.
