### ISSUE TITLE
Api response does not change in hot reload.

### ISSUE THREAD

**Issue by wxs77577** [nestjs/nest#8027]
I have follow the official guide to setup hot reload, but after I changed return value of `getHello()` in `apps/nest-hot/src/app.service.ts`, I refresh the page http://localhost:5000/ and it still show's the old value.

git repo: https://github.com/wxs77577/nest-hot-1

```shell
yarn
yarn dev
```

**Comment by jmcdo29** [comment]
Worked just fine for me. For reference, I cloned, installed (installed webpack explicitly in the package.json because pnpm expected it), ran `pnpm dev` to start up the server, hit `/` and got back `1`. Changed the return of `AppService#getHello()` to be `JSON.stringify({ hello: 'world' })`, hit `/` again and got `{"hello":"word"}`

```sh
nest-hot-1 on  main [📝🤷‍] via ⬢ v14.16.0  8h14m ⚑ ◒  ⍉
❯ curl http://localhost:5000
1
nest-hot-1 on  main [📝🤷‍] via ⬢ v14.16.0   8h15m ⚑ ◒
❯ curl http://localhost:5000
{"hello":"word"}
```

<details>

<summary>And the logs of the server</summary>

```
 Info  Webpack is building your sources...

webpack 5.45.1 compiled successfully in 2176 ms
[Nest] 11541  - 09/04/2021, 9:11:35 AM     LOG [NestFactory] Starting Nest application...
[Nest] 11541  - 09/04/2021, 9:11:35 AM     LOG [InstanceLoader] AppModule dependencies initialized +20ms
[Nest] 11541  - 09/04/2021, 9:11:35 AM     LOG [RoutesResolver] AppController {/}: +4ms
[Nest] 11541  - 09/04/2021, 9:11:35 AM     LOG [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 11541  - 09/04/2021, 9:11:35 AM     LOG [NestApplication] Nest application successfully started +1ms

 Info  Webpack is building your sources...

[Nest] 11541  - 09/04/2021, 9:12:11 AM     LOG [NestFactory] Starting Nest application... +35778ms
[HMR] Updated modules:
[HMR]  - 8
[HMR]  - 7
[HMR]  - 5
[HMR]  - 3
Entrypoint main 43.8 KiB = apps/nest-hot/main.js 42.4 KiB 0.2fddb6f0fe1efa6550bb.hot-update.js 1.34 KiB
webpack 5.45.1 compiled successfully in 179 ms
[HMR] Update applied.
[Nest] 11541  - 09/04/2021, 9:12:11 AM     LOG [InstanceLoader] AppModule dependencies initialized +5ms
[Nest] 11541  - 09/04/2021, 9:12:11 AM     LOG [RoutesResolver] AppController {/}: +0ms
[Nest] 11541  - 09/04/2021, 9:12:11 AM     LOG [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 11541  - 09/04/2021, 9:12:11 AM     LOG [NestApplication] Nest application successfully started +0ms
```

</details>

**Comment by wxs77577** [comment]
Thanks for your reply, I still got same problem in browser (I have checked the **disable cache** in devtools), but when I use `curl http://localhost:5000` it (**curl**) just works fine. After  use `curl`, I refresh the browser and it display the right text (sometimes..).

**Comment by jmcdo29** [comment]
That would mean the browser cached the response, not something related to the server or the framework. Glad you found the solution of disabling the browser cache

**Comment by wxs77577** [comment]
But it works fine when I use `nest start -w`, I've tested with Edge and Chrome on macbook.

**Comment by jmcdo29** [comment]
I still don't think this is related to the framework, as a pure non-cachng HTTP client (like curl) shows the updated response after a server restart, meaning that the code was properly updated. If you can show with your minimum reproduction that a non-caching HTTP client does not get the updated response, then it might be related to the framework

**Comment by wxs77577** [comment]
I have tested with fastify (https://docs.nestjs.com/techniques/performance), it works fine too. Maybe there are some problem in express adapter.

**Comment by jmcdo29** [comment]
I told you already, if it works from `cURL` it means the server is responding properly. Something, somewhere is caching the response, but it's not the server.

**Comment by TranThanhTamBuu** [comment]
I have the same problem too, any ideas?
