### ISSUE TITLE
Access events on kafka microservice

### ISSUE THREAD

**Issue by Kannndev** [nestjs/nest#8028]
Hi Guys, I would like to listen to the events on consumer object returned by Kafkajs. But in nestjs since i am starting the microservice like this 

app.connectMicroservice<MicroserviceOptions>({
    transport: Transport.KAFKA,
    options: {
      client: {
        clientId: configService.get('KAFKA_CLIENT_ID'),
        brokers: configService.get('KAFKA_BROKERS').split(','),
      },
      consumer: {
        groupId: configService.get('KAFKA_GROUP_ID'),
      },
    },
  });

How can I access the consumer instance which would be returned by kafkajs.

**Comment by Tony133** [comment]
Hi @Kannndev, for this type of question I recommend that you use the support channel [discord](https://discord.com/invite/G7Qnnhy).

The NestJS Core Team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by Kannndev** [comment]
Hey @Tony133 sorry about that. I already posted in discord and twitter as well. I did not get any reponses. I thought it was lost in the long list of messages.

**Comment by Tony133** [comment]
No problem 👍, we usually move these kind of issues / messages to the discord channel for support also to help Kamil, in solving problems like bugs, new features, etc.

I give you another tip on discord try to post the problem using a thread, it has a duration of 24 hours if I'm not mistaken, so you know that the problem you posed is not forgotten or lost, they are only archived but not removeds.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
