### ISSUE TITLE
Incorrect responses for StreamableFile

### ISSUE THREAD

**Issue by averri** [nestjs/nest#8029]
## Current behavior
When using a `StreamableFile` as a response type in a controller, the result is incorrect.

This is the wrong result of a `StreamableFile`, when invoking `GET http://localhost:3000/file`:

```
{
  "stream": {
    "path": "/home/alex/dev/src/other/example/package.json",
    "flags": "r",
    "mode": 438,
    "fd": null,
    "end": null,
    "bytesRead": 0,
    "closed": false,
    "_readableState": {
      "objectMode": false,
      "highWaterMark": 65536,
      "buffer": {
        "head": null,
        "tail": null,
        "length": 0
      },
      "length": 0,
      "pipes": [],
      "flowing": null,
      "ended": false,
      "endEmitted": false,
      "reading": false,
      "constructed": false,
      "sync": true,
      "needReadable": false,
      "emittedReadable": false,
      "readableListening": false,
      "resumeScheduled": false,
      "errorEmitted": false,
      "emitClose": true,
      "autoDestroy": true,
      "destroyed": false,
      "errored": null,
      "closed": false,
      "closeEmitted": false,
      "defaultEncoding": "utf8",
      "awaitDrainWriters": null,
      "multiAwaitDrain": false,
      "readingMore": false,
      "dataEmitted": false,
      "decoder": null,
      "encoding": null
    },
    "_events": {},
    "_eventsCount": 1
  }
}
```

## Input Code
Simple example from documentation (ref: ):
```ts
  @Get('file')
  getFile(): StreamableFile {
    const file = createReadStream(join(process.cwd(), 'package.json'));
    return new StreamableFile(file);
  }
```

I'm using global interceptors:

`main.ts` file:
```ts
  // Converts all input JSON to classes for requests, opposite for responses.
  app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)));
```

## Expected behavior
The response should be the contents of the stream, in the case of the example above, the contents of the file `package.json`.

## Possible Solution
No solutions.

## Environment

<pre><code>
Nest version: 8.0.0
 
For Tooling issues:
- Node version: 16.8.0
- Platform:  Linux Ubuntu 18

Others:
Package manager: yarn
</code></pre>

**Comment by averri** [comment]
Maybe this is connected to: https://github.com/nestjs/nest/issues/7909

I'm using global interceptors, so it could be messing with `StreamableFile` responses.

**Comment by averri** [comment]
I'm closing this, because the solution is in the https://github.com/nestjs/nest/pull/7911.

**Comment by chriszrc** [comment]
@averri `StreamableFile` is working fine as long as I don't package (webpack) the nest app with dependencies included. Then I'm getting the raw json stream output you posted above. I'm using nx if that makes any difference-
