### ISSUE TITLE
@ApiResponse: type property accepts a type.

### ISSUE THREAD

**Issue by morgan-wild** [nestjs/nest#8035]
## Is your feature request related to a problem? Please describe.

`@ApiOkResponse({ type: OperationReport })`

With 

`export class OperationReport { }`

Works, but with 

`export type OperationReportsSearchRequest = { }`

I have the following error:

`'OperationReport' only refers to a type, but is being used as a value here.`

## Describe the solution you'd like
Allow a Type fot the 'type' parameter.

## What is the motivation / use case for changing the behavior?
The reason I'm trying to use Types instead of Classes is because it allow feature like Pick and Omit, it is really great to manage DTO variants.

Thank you very much.

**Comment by jmcdo29** [comment]
Types are erased by Typescript at runtime, so there's no way they can be used as values. Unless you want to find some proposal to the Typescript team about keeping types at runtime, I don't think this will be doable anytime soon.

As for the use of things like `Pick` and `Omit`, that's what the [`PickType`](https://docs.nestjs.com/openapi/mapped-types#pick) and [`OmitType`](https://docs.nestjs.com/openapi/mapped-types#omit) mixins are for

**Comment by morgan-wild** [comment]
Thank you for this fast and clear response @jmcdo29 
I will investigate this way!
