### ISSUE TITLE
GraphQL subscription configuration not working correctly for "subscriptions" options

### ISSUE THREAD

**Issue by arthurolmos** [nestjs/nest#8038]
## Current behavior
I'm following the docs to create a GraphQL subscription, but it seems that something changed and the configuration is not working correctly anymore.

## Input Code
The documentation recommends using graphql-ws:
![image](https://user-images.githubusercontent.com/37308377/132224263-2cc4c2be-6b98-4440-9639-a240b281080a.png)

But when I do this exactly configuration, I get this TS error:
![image](https://user-images.githubusercontent.com/37308377/132224688-33b3bddf-adfa-4b6b-8223-676e2d350a20.png)

src/app.module.ts:24:9 - error TS2322: Type '{ 'graphql-ws': true; }' is not assignable to type 'string | false | Partial<SubscriptionServerOptions>'.
  Object literal may only specify known properties, and ''graphql-ws'' does not exist in type 'Partial<SubscriptionServerOptions>'.

24         'graphql-ws': true,

These are the accepted options for "subscriptions" param:
![image](https://user-images.githubusercontent.com/37308377/132226863-6def1618-9b5c-48f0-84fa-2e33468b1a5b.png)

## Expected behavior
If this is realy a bug, the docs needs to be updated.

## Environment

<pre><code>
Nest version: 7.6.0

 
For Tooling issues:
- Node version: v14.15.1
- Platform:  WIndows

**Comment by micalevisk** [comment]
you're using nest v7 while reading the docs of nest v8.

Read the v7 version here: https://docs.nestjs.com/v7/graphql/subscriptions or upgrade

**Comment by arthurolmos** [comment]
> you're using nest v7 while reading the docs of nest v8.
> 
> Read the v7 version here: https://docs.nestjs.com/v7/graphql/subscriptions or upgrade

Oh... what a silly mistake... I'll close the issue.

But btw, what are the right steps to upgrade Nest CLI? I've tried to run **nest update**,  **nest update -f**, and even installed it again with **yarn global add @nestjs/cli**, and in the end of installation shows that version 8.1.1 has been installed, but when i run  nest -v it still shows version 7.6.0. Can you help me?

**Comment by micalevisk** [comment]
> But btw, what are the right steps to upgrade Nest CLI?

https://github.com/nestjs/nest/issues/7982#issuecomment-907671454
