### ISSUE TITLE
@deprecated 'bodyParser' is deprecated

### ISSUE THREAD

**Issue by jeremiassantos** [nestjs/nest#8040]
## Current behavior

'bodyParser' is deprecated.ts(6385)
index.d.ts(19, 5): The declaration was marked as deprecated here.
(alias) function bodyParser(options?: bodyParser.OptionsJson & bodyParser.OptionsText & bodyParser.OptionsUrlencoded): NextHandleFunction
(alias) namespace bodyParser
import bodyParser
@deprecated

 app.setGlobalPrefix('api/v1')
app.use(bodyParser.json({ limit: '10mb' }))
app.use(bodyParser.urlencoded({ limit: '10mb', extended: true }))

**Comment by jeremiassantos** [comment]
Resolved By

Import using extractor operator

import { json, urlencoded } from 'body-parser'

 app.use(json({ limit: '10mb' }))
 app.use(urlencoded({ limit: '10mb', extended: true }))

**Comment by jmcdo29** [comment]
I'm not quite sure what the issue with Nest is here.

**Comment by micalevisk** [comment]
@jeremiassantos Your issue is related to `express`. Nest already uses your solution by default, here:

https://github.com/nestjs/nest/blob/5974b6fed12dfe3d0846cb48dcf2cb449bde2557/packages/platform-express/adapters/express-adapter.ts#L154-L157
