### ISSUE TITLE
Fastify CSRF: TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Zerotask** [nestjs/nest#8049]
## Bug Report
I tried adding CSRF protection for Fastify, as described here:
https://docs.nestjs.com/security/csrf#use-with-fastify

Fastify in general is working as expected. If I comment out the line, where it gets registered, if's working again.

## Current behavior
When I start the app with: npm run start:dev
I get this error:
>C:\Users\Patrick\dev\nastyville-testing\node_modules\avvio\time-tree.js:40
if (parentNode.id) {

> TypeError: Cannot read properties of undefined (reading 'id')
at TimeTree.getParent (C:\Users\Patrick\dev\nastyville-testing\node_modules\avvio\time-tree.js:40:18)
at TimeTree.add (C:\Users\Patrick\dev\nastyville-testing\node_modules\avvio\time-tree.js:63:27)
at TimeTree.start (C:\Users\Patrick\dev\nastyville-testing\node_modules\avvio\time-tree.js:78:15)
at Plugin. (C:\Users\Patrick\dev\nastyville-testing\node_modules\avvio\boot.js:245:36)
at Object.onceWrapper (node:events:514:26)
at Plugin.emit (node:events:394:28)

## Expected behavior
Working as expected

## Possible Solution
Update the dependecy.

## Environment

<pre><code>
[System Information]
OS Version     : Windows 10
NodeJS Version : v16.9.0
NPM Version    : 7.21.1 

[Nest CLI]
Nest CLI Version : 8.1.1

[Nest Platform Information]
platform-express version : 8.0.6
platform-fastify version : 8.0.6
schematics version       : 8.0.3
swagger version          : 5.0.9
typeorm version          : 8.0.2
testing version          : 8.0.6
common version           : 8.0.6
config version           : 1.0.1
core version             : 8.0.6
cli version              : 8.1.1
</code></pre>

**Comment by Zerotask** [comment]
@micalevisk 
This works, but you have to register the cookie middleware before the csrf middleware. If you change the order, you still get the error.
But this still seems to be a bug with a dependency, which is probably already fixed in a later version.

Also, if it always needs the cookie middleware, the docs should be updated.

**Comment by jmcdo29** [comment]
[fastify-csrf](https://github.com/fastify/fastify-csrf#usage) requires the use of either sessions or cookies. Looks like we should at the very least be linking over to their docs to help make this clearer

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/issues/2040
