### ISSUE TITLE
Add an option to set a global default API version

### ISSUE THREAD

**Issue by Zerotask** [nestjs/nest#8050]
## Feature Request
I want to use API versioning (URI Versioning Type) and I want to avoid setting the default version for every controller.
Instead I want to have an option to set it globally.

https://docs.nestjs.com/techniques/versioning

## Is your feature request related to a problem? Please describe.
If you add API versioning to your application, using URI Versioning Type, you have to update every controller's decorator and add the `version: '1'`. 
Example:
```ts
@Controller({ path: 'user', version: '1' })
export class UserController { }
```

If you decide later to update your default version from 1 to 2, you have to update every controller again.

## Describe the solution you'd like
To avoid redundancy and improve the comfort, it would be great to set a default version in your main.ts

Example:
```ts
  app.enableVersioning({
    type: VersioningType.URI,
    default: '1'
  });
```

This would mean, that if you don't use @Version decorators in your controllers (class or method), it uses `/v1`
If you decide to use a different version, then this default version will be overwritten. Therefore this won't introduce a breaking change.

**Comment by micalevisk** [comment]
I just prototype this feature here: https://gitlab.com/micalevisk/nest-issue-8050 with few tests. But I use `defaultVersion` instead of `default`

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this feature?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8128
