### ISSUE TITLE
Add cache option isGlobal

### ISSUE THREAD

**Issue by Zerotask** [nestjs/nest#8051]
## Feature Request
Similar to the option for configuration, where you can set isGlobal?: boolean, it would be a great addition to have the same option for the CacheModule.

## Is your feature request related to a problem? Please describe.
I use the cache module quite a lot and setting it as a global module in the app.module.ts would simplify the development and the code.

## Describe the solution you'd like
Add isGlobal?: boolean to CacheManagerOptions.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by lengxuegang** [comment]
hi, I've created a PR for this issue: https://github.com/nestjs/nest/pull/8126

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8126
