### ISSUE TITLE
Bad JSON with NATS microservice

### ISSUE THREAD

**Issue by ismael-iskauskas** [nestjs/nest#8055]
## Current behavior
if you call send on ClientProxy with an unknown command´you will get an BAD JSON exception and the calling service dies completly

## Input Code

```ts
import { Inject, Injectable, Logger } from '@nestjs/common';
import { ClientProxy, RpcException } from '@nestjs/microservices';
import { Observable, ObservableInput, TimeoutError } from 'rxjs';
.....
@Injectable()
export class NatsProxyService {
  private logger = new Logger(NatsProxyService.name);
  constructor(@Inject(NATS_SERVICES) private client: ClientProxy) {}

  public send<T>(cmd: string, payload: Payload): Observable<T> {
    return this.client.send({ cmd }, payload).pipe(
      timeout(this.config.NATS_TIMEOUT),
      catchError((err) => {
        this.logger.error('Error in send', err);
        return this.handleError(err);
      })
    );
  }
}

// call the service from controller ... Pseudo code
NatsProxyService.send('some-unknown-action', randomDataObject);
```

## Expected behavior
A JSON Parse exception should not lead to a total crash

## Possible Solution
in file microservices/client/client-nats.ts lines 67 - 95
```ts
public createSubscriptionHandler(
    packet: ReadPacket & PacketId,
    callback: (packet: WritePacket) => any,
  ) {
    return async (error: unknown | undefined, natsMsg: NatsMsg) => {
      if (error) {
        return callback({
          err: error,
        });
      }
      const rawPacket = natsMsg.data;
      // FIX
      // const message = await this.deserializer.deserialize(rawPacket);
      let message = null;
      try {
          message = await this.deserializer.deserialize(rawPacket);
      } catch (error) {
          return callback({
              err: error,
          });
      }
      if (message.id && message.id !== packet.id) {
        return undefined;
      }
      const { err, response, isDisposed } = message;
      if (isDisposed || err) {
        return callback({
          err,
          response,
          isDisposed: true,
        });
      }
      callback({
        err,
        response,
      });
    };
  }
```
## Environment

<pre><code>
Nest version: 8.0.4

 
For Tooling issues:
- Node version: 16
- Platform:  Windows

Others:
</code></pre>

**Comment by Tony133** [comment]
Hi @ismael-iskauskas, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

**Comment by ismael-iskauskas** [comment]
Hello @Tony133, i dont have the time right now to to setup up a demo repository. 
It is possible to fix the crash if you wrap the call to `const message = await this.deserializer.deserialize(rawPacket);` in an tryCatch and trigger the callback
```
let message = null;
try {
    message = await this.deserializer.deserialize(rawPacket);
} catch (error) {
    return callback({
        err: error,
    });
}
```

**Comment by Tony133** [comment]
at the moment i can't tell you if it's a real bug, without a  minimal reproduction , however glad you solved it at the moment.

**Comment by ismael-iskauskas** [comment]
I setup a demo project.

[https://github.com/ismael-iskauskas/nest-error.git](url)

**Comment by mberrezak** [comment]
This is not fixed at all, I am using the following packages and the client still crashes with "Bad Json" errors: 

"dependencies": {
    "@nestjs/common": "^9.0.2",
    "@nestjs/core": "^9.0.2",
    "@nestjs/mapped-types": "^1.1.0",
    "@nestjs/microservices": "^9.0.2",
    "@nestjs/platform-express": "^9.0.2",
    "@prisma/client": "^4.0.0",
    "class-validator": "^0.13.2",
    "nats": "^2.7.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
