### ISSUE TITLE
Web Gateway - NESTJS Unit Test

### ISSUE THREAD

**Issue by ilanl** [nestjs/nest#8065]
I'm wondering how to write a unit test for WS Gateway, without using real:

```
app.listen(port)
```

Is there any documentation regarding that matter? I couldn't find any on NEST docs

**Comment by Tony133** [comment]
Hi @ilanl,  for this type of question I recommend that you use the support channel [discord](https://discord.com/invite/G7Qnnhy).

The NestJS Core Team uses GitHub to track bug reports, feature requests, and regressions. 

Anyway I suggest you take a look at this repository: https://github.com/jmcdo29/testing-nestjs ?

**Comment by ilanl** [comment]
thanks

**Comment by Tony133** [comment]
you're welcome, it's nothing 👍
