### ISSUE TITLE
why this show err : 应有 0 个参数，但获得 1 个。ts(2554)

### ISSUE THREAD

**Issue by zhfnjust** [nestjs/nest#8068]
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/nestframework

compiling error 
```javascript

  async login(@AuthUser() user: User,  @Res({ passthrough: true }) response: FastifyReply) {

```

but success if change t o

```javascript

  async login(@AuthUser() user: User,  @Res() response: FastifyReply) {

```

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
