### ISSUE TITLE
Post Body undefined on production

### ISSUE THREAD

**Issue by flxwu** [nestjs/nest#8069]
## Current behavior
I'm posting using this curl command below, and when api_url is my localhost it works, but when it's the production url (on Heroku), the body is always empty - for all my controllers.

```
curl --location --request POST '$api_url/instructors' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "linda@dot9.co",
    "id": "auth0|612aa1370e245a006a2aa0cd13x",
    "firstName": "Linda",
    "lastName": "Thelen",
    "organizationId": "1",
}'
```

## Input Code

```ts
@Controller('instructors')
export class InstructorsController {
  constructor(
    private readonly instructorsService: InstructorsService,
    private readonly studentsService: StudentsService,
    private readonly calendarEventsService: CalendarEventsService,
  ) {}

  @Post()
  create(
    @Body() createInstructorDto: CreateInstructorDto,
  ): Promise<Instructor> {
    console.log({ createInstructorDto });
    return this.instructorsService.create(createInstructorDto);
  }
```

## Expected behavior
Body should be filled, both locally and on prod.

## Environment

<pre><code>
"@nestjs/core": "^8.0.0"
 
For Tooling issues:
- Node version: latest stable
- Platform:  Heroku 

Others:

</code></pre>

**Comment by Tony133** [comment]
Hi @flxwu, try posting this issue on [discord](https://discord.com/invite/G7Qnnhy) support channel as well.
 
If you think it's a bug, create a minimal reproduction in a clonable git, so the NestJS core team can evaluate your problem.

**Comment by flxwu** [comment]
it actually kind of just resolved itself... maybe it was some problem with Heroku.

**Comment by Tony133** [comment]
Glad you solved 👍
