### ISSUE TITLE
RabbitMQ MessagePattern doesn't work!

### ISSUE THREAD

**Issue by HackPoint** [nestjs/nest#8070]
Having an issue with:
The ` @MessagePattern('que.transactions.manager')` is never initialises the `options.channel` this way the I'm always getting this unexplainable error. I had to go to sources and find the issue to actually understand what's going on.
If you can please extend the error and fix the bug.

This is the way I'm initialising the MessagePattern decorator

```
@Controller()
export class TransactionController {
  private readonly logger = new Logger(TransactionController.name);

  constructor(private readonly service: TransactionService) {
  }

  @MessagePattern('que.transactions.manager')
  async execute(@Payload() message: TransactionMessage, @Ctx() context: RmqContext) {
    await this.service.addTransaction(message, context);
  }


  /* @MessagePattern('transaction.v1.*.*.*.event.#')
   async listener(@Payload() message: TransactionResponseMessage, @Ctx() context: RmqContext) {
     await this.service.updateTransaction(message, context);
   }*/
}
```

Error I'm getting:
`ERROR [Server] There is no matching event handler defined in the remote service. Event pattern: undefined.`

This invocation of the deserializer is actually wrong.
`const packet = await this.deserializer.deserialize(rawMessage, "Missing options");`

I would invoked this because it has `message.fields.routingKey` and that way the generic arch doesn't get's broken.

`const packet = await this.deserializer.deserialize(rawMessage, message);`

```
class IncomingRequestDeserializer {
    deserialize(value, options) { // options is always undefined!
        return this.isExternal(value) ? this.mapToSchema(value, options) : value;
    }
    isExternal(value) {
        if (!value) {
            return true;
        }
        if (!shared_utils_1.isUndefined(value.pattern) ||
            !shared_utils_1.isUndefined(value.data)) {
            return false;
        }
        return true;
    }
    mapToSchema(value, options) {
        if (!options) {
            return {
                pattern: undefined,
                data: undefined,
            };
        }
        return { 
            pattern: options.channel,
            data: value,
        };
    }
}
```

NestJS: 8.0.6
Typescript: 4.3.5
I'm using monorepo: NRWL NX

**Comment by HackPoint** [comment]
@kamilmysliwiec hey how are you? At least a comment would be really appreciated. Can you check how to fix that issue?

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by montera82** [comment]
this issue is not fixed!!!! discord is not friendly !!

**Comment by micalevisk** [comment]
@montera82 

Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by montera82** [comment]
found out that the issue is that your event handler must be a controller and not just any file..hopefully this guides someone else.
