### ISSUE TITLE
I'm getting 'Can't resolve 'fastify-swagger'  when calling webpack

### ISSUE THREAD

**Issue by jpmoraez** [nestjs/nest#8072]
## Current behavior
When calling nest build --webpack I'm getting this issue:
ERROR in ./node_modules/@nestjs/swagger/dist/swagger-module.js 46:106-132
Module not found: Error: Can't resolve 'fastify-swagger'  ......

## Input Code
https://github.com/jpmoraez/financial-app-nestjs

## Expected behavior
I should get application running and swagger available when calling: nest build --webpack

## Environment

<pre><code>
Nest version:
"@nestjs/core": "^8.0.0",
 
For Tooling issues:
- Node version: v12.20.0
- Platform:  Mac

**Comment by micalevisk** [comment]
Looks like it related to https://github.com/nestjs/swagger/issues/1414

**Comment by jpmoraez** [comment]
@micalevisk 
After the changes I'm getting another error:
Error: offline: handler 'handler'  ....dist/main is not a function

I just did the update in my repo

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
