### ISSUE TITLE
socket.io does not emit connect_error or exception event on next(error) on middleware

### ISSUE THREAD

**Issue by nguyentanphu** [nestjs/nest#8074]
## Bug Report
I have a custom a socket adapter to deal with authentication. In the docs, socket.io said that when you call next(new Error()) it should emit event 'connect_error' or event 'exception' event in our case. On client side, I dont see any events.
## Input Code

```ts
export class AuthSocketAdapter extends IoAdapter {
  constructor(app: INestApplication, private authService: AuthenticationService) {
    super(app);
  }
  createIOServer(port: number, options?: any) {
    const server = super.createIOServer(port, options) as Server;

    const authMiddleware = (client: Socket, next) => {
      const token = client.handshake.headers['token'] as string;
      try {
        const user = this.authService.validateJwtToken(token);
        client['user'] = user;
        next();
      } catch (error) {
        next(new WsException('token is not valid.'));
      }
    };
    server.of(toksNamespace).use(authMiddleware);
    server.of(messageNamespace).use(authMiddleware);

    return server;
  }
}

// using the custom adapter in main.ts
app.useWebSocketAdapter(new AuthSocketAdapter(app, authService));

// client side
  socket.onAny((event, ...args) => {
    console.log(event, args);
  });
```

## Expected behavior
It should emit an event to the socket.

## Environment

<pre><code>
Nest version: 8.0.6
nestjs/websockets: 8.0.6

 
</code></pre>

**Comment by Tony133** [comment]
Hi @nguyentanphu, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

**Comment by nguyentanphu** [comment]
hi @Tony133, thanks for your response. I'll add all the code of my adapter. Hope it's clearer now

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
