### ISSUE TITLE
mongoose multiple databases doesn't work with MongooseModule.forRootAsync()

### ISSUE THREAD

**Issue by MostajeranMohammad** [nestjs/nest#8075]
## Current behavior
when use below code with forRootAsync dependency injection error occurs, registered model in MongooseModule.forFeature( [{ name: example.name, schema: exampleSchema }],  'db1')  throw error:
Error: Nest can't resolve dependencies of the exampleModel (?). Please make sure that the argument db1Connection at index [0] is available in the MongooseModule context.

## Input Code
```ts
@Module({
    imports: [
      ConfigModule.forRoot({
        cache: true,
        isGlobal: true,
        load: [configuration],
        validate,
      }),
      // forRootAsync doesn't work
      MongooseModule.forRootAsync({
        imports: [ConfigModule],
        inject: [ConfigService],
        useFactory: (configService: ConfigService) => ({
          connectionName: 'db1',
          uri: configService.get('mongo.db1_mongoUrl'),
          useNewUrlParser: true,
          useCreateIndex: true,
        }),
      }),
      MongooseModule.forRootAsync({
        imports: [ConfigModule],
        inject: [ConfigService],
        useFactory: (configService: ConfigService) => ({
          connectionName: 'db2',
          uri: configService.get('mongo.db2_mongoUrl'),
          useNewUrlParser: true,
          useCreateIndex: true,
        }),
      }),
  
      // forRoot works with same config
      MongooseModule.forRoot(process.env.db1_MONGO_URL, {
        connectionName: 'db1',
      }),
      MongooseModule.forRoot(process.env.db2_MONGO_URL, {
        connectionName: 'db2',
      }),
    ],
  })
  export class AppModule {}
  ```

**Comment by Tony133** [comment]
Hi @MostajeranMohammad, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

**Comment by Tony133** [comment]
@MostajeranMohammad  did you try like this:

```
   MongooseModule.forRootAsync({
      connectionName: 'mongodb1',
      useFactory: () => ({
        uri: 'mongodb://localhost:27017/test1',
        useNewUrlParser: true,
        useCreateIndex: true,
      }),
    }),
    MongooseModule.forRootAsync({
      connectionName: 'mongodb2',
      useFactory: () => ({
        uri: 'mongodb://localhost:27018/test2',
        useNewUrlParser: true,
        useCreateIndex: true,
      }),
    }),
```

**Comment by MostajeranMohammad** [comment]
> @MostajeranMohammad did you try like this:
> 
> ```
>    MongooseModule.forRootAsync({
>       connectionName: 'mongodb1',
>       useFactory: () => ({
>         uri: 'mongodb://localhost:27017/test1',
>         useNewUrlParser: true,
>         useCreateIndex: true,
>       }),
>     }),
>     MongooseModule.forRootAsync({
>       connectionName: 'mongodb2',
>       useFactory: () => ({
>         uri: 'mongodb://localhost:27018/test2',
>         useNewUrlParser: true,
>         useCreateIndex: true,
>       }),
>     }),
> ```

thanks this works.🙂

**Comment by Tony133** [comment]
you're welcome, it's nothing 👍
