### ISSUE TITLE
NestJS app doesn't stop using process.exit() when initial mongoose connection error is occurred

### ISSUE THREAD

**Issue by levytskyi** [nestjs/nest#8077]
## Current behavior
While trying to handle initial MongoDB connection errors, Nest application is unable to perform `process.exit()` when it gets to the `catch` block. It just logs to the console `console.log()` command and then freezes and nothing happens.

Also I do have `app.enableShutdownHooks()` in my `main.ts` file but I believe it has nothing to do with such a problem.

## Input Code
```ts
import * as mongoose from "mongoose";
import { MONGO_URI } from "src/constants";
import { DATABASE_CONNECTION } from "./database.constants";

export const databaseConnectionProviders = [
    {
        provide: DATABASE_CONNECTION,
        useFactory: async (): Promise<typeof mongoose> => {
            try {
                return await mongoose.connect(MONGO_URI, {
                    useNewUrlParser: true,
                    useUnifiedTopology: true,
                    useCreateIndex: true
                });
              } catch (error) {
                console.log(`Error on initial MongoDB connection: ${error}`);
                process.exit(1); // <--- it does nothing
              }       
        }
    }
];
```

## Expected behavior
Server should be stopped.

## Possible Solution
Currently none.

## Environment

<pre><code>
Nest version: 8.0.0

 
For Tooling issues:
- Node version: v14.17.3
- Platform:  macOS 11.5.2

Others:
- mongoose: 5.13.5
</code></pre>

**Comment by Tony133** [comment]
Hi @levytskyi , I advise you to leave a minimal reproduction of a clonable git repository so that the NestJS core team can evaluate the issue you reported.

**Comment by levytskyi** [comment]
> Hi @levytskyi , I advise you to leave a minimal reproduction of a clonable git repository so that the NestJS core team can evaluate the issue you reported.

Hey there @Tony133 I just pushed a minimal repro code here - https://github.com/levytskyi/nest-mongo-repro

**Comment by AntonyAsatiani** [comment]
Hey!
maybe issue is how the project  starts.
first I run code in watch mode `npm run start:dev` in this case server continue to work after execution of process.exit(1);
then I try to launch with script `npm run start`, in this case, server stopped work and exited with following error:
```
failed to connect to the MongoDB due to: MongooseServerSelectionError: Server selection timed out after 3000 ms
Performing process exit
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-mongo-repro@0.0.1 start: ‘nest start’
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nest-mongo-repro@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-09-18T21_34_46_967Z-debug.log
```

I after that I checked npm logs: 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/user/.nvm/versions/node/v14.15.5/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v14.15.5/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle nest-mongo-repro@0.0.1~prestart: nest-mongo-repro@0.0.1
6 info lifecycle nest-mongo-repro@0.0.1~start: nest-mongo-repro@0.0.1
7 verbose lifecycle nest-mongo-repro@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle nest-mongo-repro@0.0.1~start: PATH: /home/user/.nvm/versions/node/v14.15.5/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Desktop/nest/issue-8077/nest-mongo-repro/node_modules/.bin:/home/user/.nvm/versions/node/v14.15.5/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle nest-mongo-repro@0.0.1~start: CWD: /home/user/Desktop/nest/issue-8077/nest-mongo-repro
10 silly lifecycle nest-mongo-repro@0.0.1~start: Args: [ '-c', 'nest start' ]
11 silly lifecycle nest-mongo-repro@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle nest-mongo-repro@0.0.1~start: Failed to exec start script
13 verbose stack Error: nest-mongo-repro@0.0.1 start: `nest start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v14.15.5/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v14.15.5/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid nest-mongo-repro@0.0.1
15 verbose cwd /home/user/Desktop/nest/issue-8077/nest-mongo-repro
16 verbose Linux 5.4.0-58-generic
17 verbose argv "/home/user/.nvm/versions/node/v14.15.5/bin/node" "/home/user/.nvm/versions/node/v14.15.5/bin/npm" "run" "start"
18 verbose node v14.15.5
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error nest-mongo-repro@0.0.1 start: `nest start`
22 error Exit status 1
23 error Failed at the nest-mongo-repro@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
it's seems `process.exit(1)` works fine.

I also try to run proccess.exit(1) from `main.ts` file and get same result, on npm run start, server was stopped, but in watch mode it continue to work.
@levytskyi  @Tony133 could you check it, please?

**Comment by jmcdo29** [comment]
It _looks_ to me like with watch mode, `process.exit(1)` doesn't kill the CLI's watch processor, it just kills the server so it won't accept any new connections or keep processing the code, making it _look_ like it's still running when it really isn't. @kamilmysliwiec is this the expected behavioir here, or should the watch process end up dying too?

**Comment by Tony133** [comment]
Hi everyone, so I tried the minimal reproduction and I confirm what he said @AntonyAsatiani, the process is not terminated when the following command is run from the terminal `npm run start:dev`,  using `npm run start` everything works fine.

To kill the process during "dev" mode you could use `process.kill(0)` but I don't know if it's a good practice, however the process ends (see screenshot). But in this way we kill him definitively 😄

<img width="1201" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/133921845-8994f97c-531b-4c40-9954-daac1116a42a.png">

In my opinion there is something strange during the watch mode, and as if `process.exit(1)` is not seen. Will it be a CLI bug?  Anyway, let's wait what Kamil says about it.

**Comment by lahdekorpi** [comment]
If I'm reading this correctly, the intent in @nestjs/cli is to use the same exit code [actions/start.action.ts:116](https://github.com/nestjs/nest-cli/blob/80f27f4a42cfadd04438aecf1be39ad57d21fb84/actions/start.action.ts#L116)?

**Comment by kamilmysliwiec** [comment]
> It looks to me like with watch mode, process.exit(1) doesn't kill the CLI's watch processor, it just kills the server so it won't accept any new connections or keep processing the code, making it look like it's still running when it really isn't. @kamilmysliwiec is this the expected behavioir here, or should the watch process end up dying too?

This is the expected behavior.
