### ISSUE TITLE
Cannot find module 'source-map-support/register'

### ISSUE THREAD

**Issue by baily90** [nestjs/nest#8081]
选择用pnpm创建项目 -> 采用monorepo模式 -> 启动指定项目报错
```
webpack 5.45.1 compiled successfully in 3788 ms
node:internal/modules/cjs/loader:903
  throw err;
  ^

Error: Cannot find module 'source-map-support/register'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1237:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:453:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:73:3)
    at node:internal/main/run_main_module:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

**Comment by Tony133** [comment]
Hi @baily90, I recommend that you leave a minimal replay of a clonable git repository so that the NestJS core team can evaluate the issue you reported.

**Comment by baily90** [comment]
@Tony133 
git@github.com:baily90/demo.git
use pnpm to install packages,  and run the project, it will throw an exception;
but use yarn or npm It can work normally

**Comment by jmcdo29** [comment]
Ah, pnpm is very particular with what packages it will find and what it won't. Seems like `source-map-support` needs to be added as a dependency for pnpm to work properly.

**Comment by baily90** [comment]
@jmcdo29 thx, It's working

**Comment by Val-istar-Guo** [comment]
Why does pnpm cause this problem?

**Comment by jmcdo29** [comment]
It has to do with if peer dependencies are installed by default or not. With pnpm they are not, so you need to specifically install them
