### ISSUE TITLE
PipeTransform does not reflect the correct ArgumentMetadata for request body data

### ISSUE THREAD

**Issue by ahoehn** [nestjs/nest#8082]
I have a custom PipeTransform class which is mapped as APP_PIPE. The transform method receives the correct body value as value param, but the metadata is not complete anymore since V8. The same code was working in older versions (V6, V7).

**Expected behavior:**
metadata.metatype.name **should represent the value of the type name**: e.g. MyBodyData

Current behavior:
metadata.metatype.name is just 'Object'.

Controller of route handler is defined as:
```
import { Body, Controller, Post } from '@nestjs/common';

@Controller()
export class QuotesController {

  @Post()
  async create(
    @Body() quoteDto: Quote,
  ): Promise<Quote> {
    //do something
    return quoteDto;
  }
}
```

**Comment by Tony133** [comment]
Hi @ahoehn, try to propose this issue in the [discord](https://discord.com/invite/G7Qnnhy)  support channel.

**Comment by ahoehn** [comment]
user problem
