### ISSUE TITLE
Let's create NEST GO ???!!!))))

### ISSUE THREAD

**Issue by Hellomik2002** [nestjs/nest#8084]
NEST JS is one of the coolest stuff I have ever seen. I can't say that NEST JS is just framework. It is also very cool guide where JUNIOR DEVELOPER WILL UNDERSTAND COMPLICATED STUFF that happens in our world. I think NEST GO must be created one day. I understand that they have different approaches but we should think about it.

**Comment by TheStarkster** [comment]
my eyes are wet, after reading this, so beautiful! just my imagining

**Comment by irlen-dot** [comment]
I absolutely agree with you. GoLang is a young language and nestjs will help new developers to get involved in the whole GO thing faster. GO is faster than JS, so let's make it easier for junior developers.

**Comment by dimuska139** [comment]
> I absolutely agree with you. GoLang is a young language and nestjs will help new developers to get involved in the whole GO thing faster. GO is faster than JS, so let's make it easier for junior developers.

Why GO? Rust is faster than Go. Let's create NEST Rust?

**Comment by jmcdo29** [comment]
> X is faster/better/whatever than Y.

And this is why I'm going to say if **you** want to re-create Nest in another language, feel free too. It's not in the Nest team's interest to create yet another framework in another language for us to maintain. We're all glad you like the framework so much, but we will continue to build for, and support, Typescript and JavaScript.

**Comment by HuyNguyen3003** [comment]
hi everyone i want to announce that me and a friend are building nest go, wait for us ~~~
