### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [nestjs/nest#8085]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Tony133** [comment]
Hi @JamieSlome, what about the axios package?

**Comment by JamieSlome** [comment]
@Tony133 ?

**Comment by Tony133** [comment]
What is the security issue?

**Comment by JamieSlome** [comment]
@Tony133 https://huntr.dev/bounties/fc086018-02b4-4861-8374-b4c9461fddf8/

**Comment by jmcdo29** [comment]
@JamieSlome we'll work on creating a `SECURITY.md` here soon. In the meantime, if you need to send a contact to someone, you can send it to me at jmcdo29@gmail.com and I can forward it on to Kamil and the rest of the team as necessary :smile:

**Comment by kamilmysliwiec** [comment]
✅  added
