### ISSUE TITLE
Mocking dependencies with ts-mockito results in a timeout

### ISSUE THREAD

**Issue by donnyroufs** [nestjs/nest#8087]
## Current behavior
Setting up a test module that uses `ts-mockito` to mock dependencies results in it timing out. (Without mockito and manual mocks it all runs fine.)

You can find the minimum reproduction repo here:
https://github.com/donnyroufs/nest-issue-8087-mrr

## Input Code
```ts
import { Test } from '@nestjs/testing';
import { CreateAccountUseCase } from '../../../src/lib/user/use-cases/create-account.usecase';
import { Provider } from '@nestjs/common';
import { instance, mock } from 'ts-mockito';
import {
  IUserMapper,
  userMapperToken,
} from '../../../src/lib/user/interface-adapters/user-mapper.interface';
import {
  IUserRepo,
  userRepoToken,
} from '../../../src/lib/user/interface-adapters/user-repo.interface';

const userMapperMock = mock<IUserMapper>();
const userRepoMock = mock<IUserRepo>();

const mapperProvider: Provider = {
  provide: userMapperToken,
  useValue: instance(userMapperMock),
};

const repoProvider: Provider = {
  provide: userRepoToken,
  useValue: instance(userRepoMock),
};

describe('create account use-case', () => {
  let sut: CreateAccountUseCase;

  beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({
      providers: [CreateAccountUseCase, mapperProvider, repoProvider],
    }).compile();

    sut = moduleRef.get(CreateAccountUseCase);
  });

  test('be defined', () => {
    expect(sut).toBeDefined();
  });
});
```

## Expected behavior
Test module should initialize and not timeout.

## Environment

<pre><code>
Nest version: ^7.0.0

Others:
Doubt it is related but I'm using an NX mono-repo.
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by donnyroufs** [comment]
> Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

You can find it here:
https://github.com/donnyroufs/nest-issue-8087-mrr

**Comment by micalevisk** [comment]
looks like it is not related to Nest: https://github.com/NagRock/ts-mockito/issues/219

**Comment by donnyroufs** [comment]
That's odd since I do not have the problem with Inversify or my own DI container ;/
