### ISSUE TITLE
nuxt+nest+fastify+any orm not work

### ISSUE THREAD

**Issue by Mitch-i** [nestjs/nest#8092]
If to main.ts from this example to add any database orm (sequalize/prisma/typeorm)

Prism controller from https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nestjs
```
import {
  Controller,
  Get,
  Param
  // Post,
  // Body,
  // Put,
  // Delete,
  // Query
} from '@nestjs/common'
import {
  // User as UserModel,
  Post as PostModel
  // Prisma
} from '@prisma/client'
import { AppService } from './app.service'
@Controller()
export class AppController {
  // eslint-disable-next-line no-useless-constructor
    constructor (private readonly prismaService: AppService) {}

    @Get('post/:id')
    async getPostById (@Param('id') id: string): Promise<PostModel> {
      return await this.prismaService.post.findUnique({ where: { id: Number(id) } })
    }
```
get an error:

ERROR [ExceptionsHandler] Cannot read property 'post' of undefined TypeError: Cannot read property 'post' of undefined
```

Sequalize controller from https://github.com/nestjs/nest/tree/master/sample
    import { Body, Controller, Delete, Get, Param, Post } from '@nestjs/common'
    import { CreateUserDto } from './dto/create-user.dto'
    import { User } from './user.model'
    import { UsersService } from './users.service'

    @Controller('users')
    export class UsersController {
      // eslint-disable-next-line no-useless-constructor
      constructor (private readonly usersService: UsersService) {}

      @Post()
      create (@Body() createUserDto: CreateUserDto): Promise<User> {
        return this.usersService.create(createUserDto)
      }
```
ERROR [ExceptionsHandler] Cannot read property 'findOne' of undefined TypeError: Cannot read property 'findOne' of undefined

Main.ts from
```

  import { NestFactory } from '@nestjs/core';
  import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify'; // npm i --save @nestjs/platform-fastify
  import { AppModule } from './app.module';

  async function bootstrap() {
    const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter({ ignoreTrailingSlash: true, logger: true }));
    await app.init();

    const fastify = app.getHttpAdapter().getInstance();
    await fastify.ready();

    // Unlike the Express version which the app instance itself is a handler function, the fastify instance is an object
    // we have to return a handler function for Nuxt serverMiddleware
    return function (req, res) {
      fastify.server.emit('request', req, res);
    };
  }

  export default bootstrap;
```

Minimum reproduction https://github.com/Mitch-i/nuxt_nest

Run  npm run nuxt:dev and open for example http://localhost:3000/api/users.
ERROR [ExceptionsHandler] Cannot read property 'findAll' of undefined

**Comment by jmcdo29** [comment]
This feels like something about the DI is getting messed with. If you can [provide a minimum reproduction](http://minimum-reproduction.wtf) we can take a better look.

**Comment by Mitch-i** [comment]
> This feels like something about the DI is getting messed with. If you can [provide a minimum reproduction](http://minimum-reproduction.wtf) we can take a better look.

Minimum reproduction https://github.com/Mitch-i/nuxt_nest

Run  npm run nuxt:dev and open for example http://localhost:3000/api/users.
ERROR [ExceptionsHandler] Cannot read property 'findAll' of undefined

**Comment by Mitch-i** [comment]
> Where's the `docker-compose` for the database?

I understand. I will wait another 20 days until Nuxt 3 and I will use the built-in server from it.

Maybe it will work with newest version of nextjs

**Comment by Mitch-i** [comment]
If I do like this


@Controller('users')
export class UsersController {
  private usersService = null

  // eslint-disable-next-line no-useless-constructor
  constructor () {
    this.usersService = new UsersService(User)
  }


[Nest] 16671  - 09/21/2021, 5:00:55 PM   ERROR [ExceptionsHandler] Decorating class property failed. Please ensure that proposal-class-properties is enabled and runs after the decorators transform.



With typeORM I get the same error without modification of constructor

**Comment by Mitch-i** [comment]
> Again, we need a [**minimum reproduction**](http://minimum-reproduction.wtf). You add a docker compose and setup instructions to your repo above, we can take a look.
thanks, no need, I will not use it, fastify is enough
