### ISSUE TITLE
Websocket and sessions

### ISSUE THREAD

**Issue by DevDom05** [nestjs/nest#8094]
Hi everyone, 
sessions and websockets don't seems to work.

Is it possible to use them ? If not, there is an alternative ?

Have a nice day.

**Comment by Tony133** [comment]
Hi @DevDom05, for this type of question I recommend that you use the support channel [discord](https://discord.com/invite/G7Qnnhy).

The NestJS Core Team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by DevDom05** [comment]
Oh sorry, thank you :)

**Comment by Tony133** [comment]
You're welcome, it's nothing 👍
