### ISSUE TITLE
Nest-GraphQL 12-graphql-schema-first fails to build

### ISSUE THREAD

**Issue by sgentile** [nestjs/nest#8099]
this page references the working example:
https://docs.nestjs.com/graphql/quick-start

Example#
A fully working schema first sample is available here.

https://github.com/nestjs/nest/tree/master/sample/12-graphql-schema-first

running npm i and npm start - fails to build

**Comment by Tony133** [comment]
Hi @sgentile, if I understand correctly the example is not working?

I ran `npm install` from terminal and then` npm run start` seems to work (see screenshot)

<img width="1035" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/134145148-4102adc6-1b37-485d-8948-3679f3645616.png">
