### ISSUE TITLE
Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by menme95** [nestjs/nest#810]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Some times I have this warning: 
<pre> <code>DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated </code> </pre>
I haven't ablet to find where it happens, but I think it is in some mongoose's functions.
 I've looking for and .inspect()  is deprecated in node 10.0.0

## Expected behavior
The Deprecation Warning doesn't appear

## Environment

<pre><code>
Nest version: 5.1.0
 
For Tooling issues:
- Node version: 10.0.0
- Platform:  Windows

Others:
[Nest Information]
mongoose version      : 4.0.0
passport version      : 1.0.10
swagger version       : 2.0.0
common version        : 5.0.1
core version          : 5.0.1
</code></pre>

**Comment by cojack** [comment]
@menme95 if those warning are from `mongoose` package, it can not be fixed by nest, please consider create an issue in correct place, like this one: https://github.com/Automattic/mongoose

**Comment by menme95** [comment]
I am using their mongoose, so I am not sure if the problem is from"pure" mongoose or from theirs.

**Comment by kamilmysliwiec** [comment]
@cojack +1. This issue doesn't come from Nest. Anyway, thanks for reporting!
