### ISSUE TITLE
Native support for sorting and pagination

### ISSUE THREAD

**Issue by hichemfantar** [nestjs/nest#8110]
## Describe the solution you'd like
It'd be great if nestjs offered native support for sorting and pagination, atleast with typeorm.
Considering that NestJS is considered as a batteries included framework, pagination and sorting seem like a must.
I'm currently [nestjs-typeorm-paginate](https://github.com/nestjsx/nestjs-typeorm-paginate) but it still lacks certain functionalities.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
