### ISSUE TITLE
Import module by Symbol / String

### ISSUE THREAD

**Issue by mjgp2** [nestjs/nest#8117]
## Feature Request

- I want to import a module by a string/symbol reference so that I do not have a library dependence from importing the module class
- Because I have an interfaces package and an implementation package I should only require a dependency on the interface package
- Currently the workaround for this is to declare the module I want to import as `@Global`
- Ideally want loose coupling such that I ask for an interface and I don't need to know who is providing the implementation, rather than tight coupling by creating a package dependency between the consumer => producer

Suggestion would be to have an optional parameter on `@Module` such as `moduleId` which then can be used within the `imports` of another module instead of the class reference.

**Comment by micalevisk** [comment]
That would be cool.

For providers, you can achieve this using the tiny lib [`nestjs-injectable`](https://www.npmjs.com/package/nestjs-injectable)

**Comment by micalevisk** [comment]
The issue with this feat is that, AFIK, nestjs modules are only registered if they appear in any `imports` array (or are passed to `NestFactory.create`, of course). So there's no way to look up for modules by their symbol/string if they didn't even was registered beforehand. Got it?

**Comment by micalevisk** [comment]
@jmcdo29 am I right?

**Comment by jmcdo29** [comment]
Pretty much to my knowledge. I mean, there's ways to write in automatic registration, but I really wouldn't be for it. I'm not really a fan of TypeO/Mikro's `entities: ['./**/*.entity.js']` approach as it leads to way more issues from misconfiguration than it solves problems (in my opinion). So yeah, auto-registration is out, meaning that _somewhere_ there needs to be an `imports` of the module to make sure Nest knows what that module is, and now that it's been imported somewhere, it doesn't make too much sense to have a separate symbol for it that abstracts away the implementation, as the module itself still needs to be imported somewhere, so why not just import it there.

This might be something that could be made into a plugin if you really wanted to, and it could be cool to see, but _I_ don't think it would bring in any value

**Comment by micalevisk** [comment]
right. There's a lib that follows that strategy to import and export providers: https://github.com/fjodor-rybakov/nestjs-dynamic-providers

**Comment by kamilmysliwiec** [comment]
We'd have to expose a similar mechanism to what `@nestjs/graphql` provides via `orphanedTypes` where you can explicitly pass an array of types to be registered even though they weren't referenced elsewhere. Once they are registered, we should be able to retrieve them by symbol/string.

**Comment by mjgp2** [comment]
Let me put a quick example in addition to original post:

* workers pull things off a queue
* there are interface packages `@scope/worker-interface` and `@scope/queue-interface`
* there are implementation packages `@scope/worker` and `@scope/queue`
* `@scope/worker` (implementation) depends on `@scope/queue-interface` but NOT `@scope/queue`
* `WorkerModule` in `@scope/worker` imports/uses `IQueueService`
* `QueueModule`  in `@scope/queue` exports `MyQueueImplementation` as `IQueueService`
* The `AppModule` imports both `QueueModule` and `WorkerModule`, i.e. the app choses the implementations it requires
* `WorkerModule` needs some way of importing an "interface module" `IQueueModule` and that resolving to `QueueModule` - this could be done with a global module alias - as long at the module is parsed before the dependant the map of aliases would have the implementing class available (could pre-scan any imports for module aliases to correctly place them in the dependency graph)

**Comment by kamilmysliwiec** [comment]
What you described above should be already feasible with dynamic modules and abstract classes.

**Comment by mjgp2** [comment]
That would be awesome @kamilmysliwiec - I can't quite see how though? I am familiar with dynamic modules... perhaps if you give me a sentence outlining how you would approach it I could do a PR for the docs with it as an example.

**Comment by Sikora00** [comment]
You can achieve it this way too
https://github.com/Sikora00/sales-leads-scraper/blob/main/libs/sales-leads-acquisition/shell/src/lib/sales-leads-acquisition-shell.module.ts

**Comment by Sikora00** [comment]
@mjgp2 
You can achieve it this way too
https://github.com/Sikora00/sales-leads-scraper/blob/main/libs/sales-leads-acquisition/shell/src/lib/sales-leads-acquisition-shell.module.ts
https://github.com/Sikora00/sales-leads-scraper/blob/main/libs/sales-leads-acquisition/application/src/lib/sales-leads-acquisition-application.module.ts

**Comment by Sikora00** [comment]
Check this as well
https://github.com/nestjs-architects/nx-ddd-plugin
