### ISSUE TITLE
Access auth user from everywhere

### ISSUE THREAD

**Issue by dagistan-tuncbilek** [nestjs/nest#8123]
I am coming from Java and Laravel background, and have some difficulty to access auth user.

I know in nest we can access auth user from request.user with decorators. It is enough most of the time. But yesterday, i needed to access auth user in prisma middleware, which belongs to prismaOrm, to log data with user. But it was almost impossible for me to access request.user in built in prisma function. Here is the link.

https://www.prisma.io/docs/concepts/components/prisma-client/middleware/logging-middleware

 In Laravel, developers can access auth()->user() from anywhere in application. It was a perfect solution for me and i used it too much. Maybe you can find a solution like that.

**Comment by Tony133** [comment]
Hi @dagistan-tuncbilek, for this type of question I recommend that you use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

The NestJS core team uses GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by dagistan-tuncbilek** [comment]
Thanks for invitation, i logged in.

**Comment by Tony133** [comment]
You're welcome, it's nothing 😉👍
