### ISSUE TITLE
ResolveReference with Context

### ISSUE THREAD

**Issue by sgentile** [nestjs/nest#8124]
## Is your feature request related to a problem? Please describe.

I'm needing to inject Context for a Dataloader into the ResolveReference for federation.   It can be done with a ResolveField but not a ResolveReference

ie. https://github.com/filipegeric/nestjs-graphql-dataloaders/blob/main/src/posts/posts.resolver.ts

## Describe the solution you'd like
I'd like access to Context inside ResolveReference in a similar way as ResolveField

## What is the motivation / use case for changing the behavior?
Allow for injection of a dataloader  as shown in this article https://dev.to/filipegeric/using-graphql-dataloaders-with-nestjs-2jo1 but to support federation

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/945#issuecomment-648787016
