### ISSUE TITLE
New Sample request: GraphQL code-first Prisma 

### ISSUE THREAD

**Issue by AdsonCicilioti** [nestjs/nest#8125]
If possible, i would looks like a sample for this aproach.

Thanks so much!

**Comment by Tony133** [comment]
Hi @AdsonCicilioti, for this type of question try using the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by AdsonCicilioti** [comment]
> Hi @AdsonCicilioti, for this type of question try using the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

My proposal is for add on [samples](https://github.com/nestjs/nest/tree/master/sample) directories

**Comment by Tony133** [comment]
Ok, @AdsonCicilioti, if you find some time and want to contribute, create a pull request with the example you proposed, so the NestJS core team will evaluate the proposal.

**Comment by kamilmysliwiec** [comment]
We don't plan to add more examples in the near future but PRs are always more than welcome!
