### ISSUE TITLE
@nestjs/platform-fastify: this.setInstance is not a function

### ISSUE THREAD

**Issue by gussalesdev** [nestjs/nest#8127]
## Bug Report

When try starting the server using version `8.0.7` of `@nestjs/platform-fastify` I got the error `TypeError: this.setInstance is not a function`, not sure why is causing this, but returning to the `8.0.6` works normally.

## Current behavior
When starts the app using `new FastifyAdapter()` I got:
```
/Users/gsales/personal-workspace/freed-services/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:72
        this.setInstance(instance);
             ^
TypeError: this.setInstance is not a function
    at new FastifyAdapter (/Users/gsales/personal-workspace/freed-services/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:72:14)
    at bootstrap (/Users/gsales/personal-workspace/freed-services/src/main.ts:12:5)
    at Object.<anonymous> (/Users/gsales/personal-workspace/freed-services/src/main.ts:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

## Input Code
```ts
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );

  await app.listen(3000);
}
bootstrap();
```

## Expected behavior
The expected behavior is the app running on start using `yarn start:dev`.

## Environment

<pre><code>
Nest version: 8.0.0
@nestjs/platform-fastify: 8.0.7
 
For Tooling issues:
- Node version: 16.6.2
- Platform:  Mac
</code></pre>

**Comment by micalevisk** [comment]
This is a bug indeed in #7874

If you want to patch this locally with [`patch-package`](https://www.npmjs.com/package/patch-package), just replace the following

https://github.com/nestjs/nest/blob/d8add273e0faa84561dfef11c065285f15284877/packages/platform-fastify/adapters/fastify-adapter.ts#L197

to `this.instance = instance`

**Comment by Tony133** [comment]
Hi @gussalesdev,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

**Comment by micalevisk** [comment]
@gussalesdev I just notice that you need to upgrade `@nestjs/core` to 8.0.7 as well xD

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by Rykuno** [comment]
I ran into this issue. Updating to `@nestjs/core": "8.0.7` solved the issue for me.
