### ISSUE TITLE
Make placement of version key in final path configurable.

### ISSUE THREAD

**Issue by CodingMeSwiftly** [nestjs/nest#8129]
## Is your feature request related to a problem? Please describe.

I have one nest application that serves my SaaS.
The application handles both frontend related work (create user, login user, refresh tokens, schedule jobs etc.) and lets registered users access the service directly via the api (schedule jobs, etc.).
I'd like to 'split' the api. One part with prefix 'tool' and one part without any prefix.
I'd like to be able to separately version the parts. (`/tool/v1`, `/tool/v2`, `/v1`, `/v2`)
I know about `RouterModule`, `setGlobalPrefix` and `enableVersioning`, however I have not found a way to combine those components in a way that lets me build the paths described above.
The issue is that the order in which the components contribute to the final path is fixed to:
`{global prefix}/{version key}/{router path}/...` where I need `{router path}/{version key}/...`.

## Describe the solution you'd like

Preferably, the first answer to this post describes how to achieve the routing outlined above with the current tools and I feel stupid for having posted this issue.

If that is not possible,
I'd like to be able to configure the order in which version keys and router paths are applied.
I imagine a template variable (e.g. `:versionkey:`) placable anywhere where routes are used would be the most flexible solution. But I can see how that might not be feasible to do.

**EDIT**
In the meantime, three possible ways to enable the desired routing came to my mind:

1. Add `pathPlacement` option to `RouteTree` interface. E.g. `PathPlacement.BeforeVersion`, `PathPlacement.AfterVersion`.
2. `setGlobalPrefix` for a single module. Kind of an inverse to the exclude option already available?
3. Template variable :versionkey: in `RouteTree ` path property.

I'm sure there are more solutions to this but which one is best is something someone more familiar with the codebase should decide :)

**Comment by Ayzrian** [comment]
I think you can work around this limitation by means of manually specifying the full path in each controller, rather than relying on `setGlobalPrefix` or built-in versioning, if that doesn't match your requirements. 

e.g. `@Controller('/tool/v1')` and `@Controller('/v1')`.

And there is probably a question of design, why not do something like this `/v1/tool` and `/v1` rather than `/tool/v1` and `/v1`?

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
