### ISSUE TITLE
Exception Filter is not catching MongoServerError/MongoError

### ISSUE THREAD

**Issue by Vasfuhder** [nestjs/nest#8132]
## Current behavior
I'm having problems trying to catch MongoServerError exception.
I have a mongo schema that the 'user' property cannot repeat in the database.
When simulating the error I get: "MongoServerError: E11000 duplicate key error collection: master.users index: user_1 dup key: { user: "test" }"

My exception filter is able to capture the error when using the @Catch() decorator

When using:
```ts
@Catch()
export class MongoFilter implements ExceptionFilter {

  catch(exception: any, host: ArgumentsHost): any {
    console.log(exception.constructor.name);
  }
}
```
I get "MongoServerError"

But if I use
```ts
@Catch(MongoServerError)
export class MongoFilter implements ExceptionFilter {

  catch(exception: MongoServerError, host: ArgumentsHost) {
    //foo
  }
}
```
or
```ts
@Catch(MongoError)
export class MongoFilter implements ExceptionFilter {

  catch(exception: MongoError, host: ArgumentsHost) {
    //foo
  }
}
```
I get 
```
[Nest] 27228  - 27/09/2021 01:23:46   ERROR [ExceptionsHandler] E11000 duplicate key error collection: master.users index: user_1 dup key: { user: "teste1" }
MongoServerError: E11000 duplicate key error collection: master.users index: user_1 dup key: { user: "teste1" }
    at F:\xxx\xxx\xxx\node_modules\mongoose\node_modules\mongodb\src\operations\insert.ts:75:25
    at F:\xxx\xxx\xxx\node_modules\mongoose\node_modules\mongodb\src\cmap\connection_pool.ts:469:13
    at handleOperationResult (F:\xxx\xxx\xxx\node_modules\mongoose\node_modules\mongodb\src\sdam\server.ts:600:5)
    at MessageStream.messageHandler (F:\xxx\xxx\xxx\node_modules\mongoose\node_modules\mongodb\src\cmap\connection.ts:752:5)
    at MessageStream.emit (events.js:375:28)
    at processIncomingData (F:\xxx\xxx\xxx\node_modules\mongoose\node_modules\mongodb\src\cmap\message_stream.ts:167:12)
    at MessageStream._write (F:\xxx\xxx\xxx\node_modules\mongoose\node_modules\mongodb\src\cmap\message_stream.ts:64:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.ondata (internal/streams/readable.js:726:22)
```
nest automatically responds with 500 status code and no exception is caught by my custom filter.

I don't know if this is a bug or I'm missing something 😟

## Input Code
Repo: https://github.com/Vasfuhder/nest-api-test

## Expected behavior
I was hoping the filter would be able to successfully catch the exception given by Mongo so that I could actually handle the exceptions.

## Possible Solution
none :/

## Environment

<pre><code>
Nest version: 8.0.7
 
For Tooling issues:
- Node version: v14.17.3
- Platform:  Windows

**Comment by jmcdo29** [comment]
Can you please add a sticker compose set up for mongo in your application? It'll help us with getting to reproducing the error faster

**Comment by Vasfuhder** [comment]
Sorry for the question, I'm new here, but what is "sticker compose"?

**Comment by jmcdo29** [comment]
"sticker compose" is me typing too fast on mobile and having autocorrect hate me. I meant to say "docker compose"

**Comment by Vasfuhder** [comment]
Sorry again, I'm feeling dumb hahahah like I said, I'm new, I've never done this before. If you can offer me a tutorial on how to do it I can reproduce it :)

**Comment by micalevisk** [comment]
I just use this:

```
docker run -it --rm -p 2727:27017 -e MONGO_INITDB_ROOT_PASSWORD=root -e MONGO_INITDB_ROOT_USERNAME=root mongo
```

with this URI: `mongodb://root:root@localhost:2727/` in `app.module.ts`

---

Looks like `exception` isn't an instance of `MongoError`, even tho `exception.constructor.name === MongoServerError`. This is why your filter can't catch that error.

**Comment by Vasfuhder** [comment]
@micalevisk, ja tentei inserir todas as classes/instancias possiveis dentro do catch, nao consigo capturar o erro, só consigo quando deixo o catch sem parametro, ou seja, quando ele passa a capturar tudo...
Ele não é instancia de MongoServerError e nem de MongoError como você disse, nao sei qual o correto a usar nessa situação, possui alguma sugestão?

**Comment by micalevisk** [comment]
@Vasfuhder 
For now, you could use the [catch-all filter](https://docs.nestjs.com/exception-filters#catch-everything) and do the checkings by yourself like 

```js
if (exception.constructor.name === 'MongoServerError') { ... }
```

I'm not sure if this is something related to exception filter dataflow or with `mongodb`

---

Se quiser discutir isso num grupo pt-br: https://t.me/nestjsbr

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/2664#issuecomment-525687266

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
