### ISSUE TITLE
NestJs backend Failed over AppGateway initialization when run docker-compose up -d

### ISSUE THREAD

**Issue by anshul-manan** [nestjs/nest#8138]
Posted on Stackoverflow :
https://stackoverflow.com/questions/69344049/nestjs-backend-failed-over-appgateway-initialization-when-run-docker-compose-up

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
