### ISSUE TITLE
@nestjs/common@7.6.18 > axios@0.21.1: Security Vulnerability

### ISSUE THREAD

**Issue by elsbrock** [nestjs/nest#8153]
## Bug Report

latest v7 of `@nestjs/common` (`7.6.18`) depends on `axios@0.21.1` which has a known CVSS with score 7.5: https://snyk.io/vuln/SNYK-JS-AXIOS-1579269

Can we get another v7 release fixing this?

**Comment by Tony133** [comment]
Hi @elsbrock, this problem has been solved [here](https://github.com/nestjs/nest/pull/8030),  for NestJS v8

I think you will need to upgrade to NestJS version 8.x, as I don't think there are any updates for NestJS v7.x

**Comment by elsbrock** [comment]
Right, I have seen it is solved in v8 – I was hoping for another v7 release.

**Comment by kamilmysliwiec** [comment]
Is there anything blocking you from updating to v8? There are almost no breaking changes so I'd personally recommend always being on the latest.

**Comment by elsbrock** [comment]
Well, at least in our CI the update to v8 is failing with a `Nest can't resolve dependencies, … Please make sure that the argument … at index [1] is available in the RootTestModule context.` so I was assuming it is not straightforward or a breaking change.

Now that I read your statement that it should be non-breaking, maybe it is easy to fix. I will have another look.

**Comment by micalevisk** [comment]
@elsbrock
> Well, at least in our CI the update to v8 is failing with a `Nest can't resolve dependencies, … Please make sure that the argument … at index [1] is available in the RootTestModule context.`

We can discuss this in https://discord.gg/nestjs :)

(I haven't upgrated my app yet, so I'd like to see what kinds of issues people are having)

**Comment by Siedlerchr** [comment]
I just upgraded my nest js app to v8, relatively smooth, I just had to replace the http module and deps everywhere to point to the nestjs/axios dependency
