### ISSUE TITLE
GRPC interceptor support

### ISSUE THREAD

**Issue by jayMedicalChain** [nestjs/nest#8154]
## Problem
I have created multiple NestJs servers that communicate via GRPC. When deploying my services with docker i get an intermittent connection issues from GRPC `ECONNRESET [{"message":"14 UNAVAILABLE: read ECONNRESET"}]`. Judging by this issue posted on the `@grpc/grpc-node` it seems this is an issue with the library.

[https://github.com/grpc/grpc-node/issues/1907#issuecomment-927361244](https://github.com/grpc/grpc-node/issues/1907#issuecomment-927361244)

## Solution i would like
Advice i got from posting on the `node-grpc` issue thread was to create an interceptor to retry requests, looking at the `GrpcOptions` within nest, nest does not allow for interceptors. A simple way allowing interceptors would be a nice feature to have.

information about interceptors can be found here

[https://github.com/grpc/proposal/blob/master/L5-node-client-interceptors.md#examples](https://github.com/grpc/proposal/blob/master/L5-node-client-interceptors.md#examples)

## Teachability, Documentation, Adoption, Migration Strategy
Ideally you would be able to pass interceptors as options like so

```
export const grpcOptions: GrpcOptions = {
  transport: Transport.GRPC,
  options: {
     interceptors: [someInterceptor],
    url: `${env.SERVER_HOST}:${config.gateway.port}`,
    package: [
      config.gateway.users.v1.package,
      config.gateway.records.v1.package,
    ],
    protoPath: [
      config.gateway.users.v1.protoPath,
      config.gateway.records.v1.protoPath,
    ],
    loader: {
      includeDirs: [config.protoLoaderDir],
      arrays: true,
      enums: String,
    },
  },
};
```

## What is the motivation / use case for changing the behavior?
Having these sort of intermittent issues that make API calls sporadically fail without a way to easily implement retries isn't great.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by kamilmysliwiec** [comment]
> looking at the GrpcOptions within nest, nest does not allow for interceptors. 

We might need to just update the interface given that the `options` object is actually passed down to the `@grpc/grpc-node` package.

**Comment by jayMedicalChain** [comment]
I can confirm it is just a case of updating the interface, i have just tested and passing an `interceptors` array into options, like so, works fine.

```
const clientOptions: ClientsModuleOptions = [
  {
    name: "HP_USERS_PACKAGE",
    //@ts-ignore
    transport: Transport.GRPC,
    options: {
      channelOptions: {
        //@ts-ignore
        interceptors: [interceptor],
      },
      url: `${env.USERS_SERVICE}:${config.users.port}`,
      package: [config.users.users.v1.package],
      protoPath: [config.users.users.v1.protoPath],
      loader: {
        includeDirs: [config.protoLoaderDir],
        enums: String,
        arrays: true,
      },
    },
  },
];
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to address this issue?

**Comment by Jaypov** [comment]
sure thing, ill get it done either later today or tomorrow.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8231

**Comment by vietkute02** [comment]
This pull request expose interceptors option for grpc but it not pass this options to grpc-js client

**Comment by wdhxs** [comment]
> I can confirm it is just a case of updating the interface, i have just tested and passing an an interceptor into the options via the `interceptors` property, like so, works fine.
> 
> ```
> const clientOptions: ClientsModuleOptions = [
>   {
>     name: "HP_USERS_PACKAGE",
>     //@ts-ignore
>     transport: Transport.GRPC,
>     options: {
>       channelOptions: {
>         //@ts-ignore
>         interceptors: [interceptor],
>       },
>       url: `${env.USERS_SERVICE}:${config.users.port}`,
>       package: [config.users.users.v1.package],
>       protoPath: [config.users.users.v1.protoPath],
>       loader: {
>         includeDirs: [config.protoLoaderDir],
>         enums: String,
>         arrays: true,
>       },
>     },
>   },
> ];
> ```

Hi~We have also encountered this problem recently. And we did it according to your method, but this interceptor did not be executed. 
`
options: {
    channelOptions: {
      interceptors: [retryInterceptor],
    },
}
`
And the retryInterceptor is same as retry from https://github.com/grpc/proposal/blob/master/L5-node-client-interceptors.md#examples
Could you tell me why?Thanks!
