### ISSUE TITLE
can not resolve HttpAdapterHost

### ISSUE THREAD

**Issue by crazyxhz** [nestjs/nest#8174]
## Bug Report
nest can not resolve HttpAdapterHost in context
simple project created by the nest cli will fail
https://docs.nestjs.com/faq/http-adapter#in-context-strategy
## Current behavior

![image](https://user-images.githubusercontent.com/6551888/135245202-8e1df658-bc0f-4388-91c3-e8e14f9137ee.png)

## Input Code

```bash
nest new adaptertest
// edit src/app.service.ts, constructor injection of adapterhost will throw error
constructor(private adapterHost: HttpAdapterHost){}
```

## Expected behavior
nest can resolve HttpAdapterHost

## Environment

<pre><code>
Nest version: 8.0.8

 
For Tooling issues:
- Node version: v12.19.1
- Platform:  macOS 10.15.7 (19H2)

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by crazyxhz** [comment]
> Please provide a minimum reproduction repository.

https://github.com/crazyxhz/nestdebug

**Comment by micalevisk** [comment]
@crazyxhz 

![image](https://user-images.githubusercontent.com/13461315/135284346-1d26a56c-fc02-41d6-9939-0d74960e4095.png)

but in your code:

![image](https://user-images.githubusercontent.com/13461315/135284426-11f91b99-8101-4116-82d0-2853cf431bdc.png)

**Comment by crazyxhz** [comment]
> @crazyxhz
> 
> ![image](https://user-images.githubusercontent.com/13461315/135284346-1d26a56c-fc02-41d6-9939-0d74960e4095.png)
> 
> but in your code:
> 
> ![image](https://user-images.githubusercontent.com/13461315/135284426-11f91b99-8101-4116-82d0-2853cf431bdc.png)
> 
> `HttpAdapterHost` from `@nestjs/common` is just a TS interface. The real class lives under `@nestjs/core`.

thanks, my mistake
