### ISSUE TITLE
Parse @Headers to string array

### ISSUE THREAD

**Issue by simonkurka** [nestjs/nest#8175]
## Current behavior
A route handler with parameter
```js
@Headers('x-custom-header') custom-header: Array<string>
```
sucessfully maps to `array[string]` in OpenAPI. From SwaggerUI an array is sent as `string1,string2`which is not correctly transformed into a string-array in TypeScript. Currently it's the comma-separated string `string1,string2`.

## MWE
https://github.com/simonkurka/nestjs-mwe-header-array

## Expected behavior
The route handler should receive a string array instead of a comma-separated string.

## Environment

<pre><code>
Nest version: 8.0.0
</code></pre>

I'm sorry if it's not a bug. It is at least unexpected.

**Comment by Tony133** [comment]
Hi @simonkurka,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

**Comment by simonkurka** [comment]
Hi @Tony133 and thank you for your advice.

https://github.com/simonkurka/nestjs-mwe-header-array

**Comment by jmcdo29** [comment]
This comes from the underlying libraries (express and fastify) and how they parse the headers object rather than from what Nest is doing itself. You can implement a custom decorator to retrieve the header from the req, and then pass it through a pipe to parse the array for you.
