### ISSUE TITLE
Import children modules in parent module conditionally based on custom provider in NestJS

### ISSUE THREAD

**Issue by mjangir** [nestjs/nest#8178]
This is not actually a bug neither a feature request. Rather its more of confirming if there is a solution to my specific problem here.

**The Problem**
Its quite common in a NestJS application that a module makes use of `useClass` or `useFactory` to get its configuration from `ConfigServer` during its asynchronous registration and then it loads some inner or child modules inside based on that async configuration through custom provider. I've not been able to make it work in such a way that I add/remove the inner modules based on parent module's configuration.

**Example**
I have a parent dynamic module here which gets async configs from `useFactory`. It also imports few child modules internally. The `useFactory` method returns actual configuration telling us which child modules should be loaded but somehow I'm not able do that. Is there a `nest` way to make it work?

**parent.options.ts**

    import { ModuleMetadata } from '@nestjs/common/interfaces';
    
    interface ActualConfigForChildren {
        child1?: {
            child1Id: string;
        };
        child2?: {
            child2Id: string;
        };
        child3?: {
            child3Id: string;
        };
    }
    
    export interface ParentModuleAsyncOptions
      extends Pick<ModuleMetadata, 'imports'> {
      name?: string;
      useFactory?: (
        ...args: any[]
      ) => Promise<ActualConfigForChildren> | ActualConfigForChildren;
      inject?: any[];
    }

**parent.module.ts**

    import { Module, Global, DynamicModule } from '@nestjs/common';
    import { ParentModuleAsyncOptions } from './parent.options';
    
    @Global()
    @Module({})
    export class ParentModule {
    
      static forRootAsync(options: ParentModuleAsyncOptions): DynamicModule {
        return {
          module: ParentModule,
          providers: [{
            provide: 'PARENT_MODULE_CONFIG_SERVICE',
            useFactory: options.useFactory,
            inject: options.inject || [],
          }],
          exports: ['PARENT_MODULE_CONFIG_SERVICE'],
          imports: [
            ChildModule1, // I want to import it if child1 config is present
            ChildModule2, // I want to import it if child2 config is present
            ChildModule3, // similarly
          ],
        };
      }
    }

**app.module.ts (Where I actually import my parent module)**

    @Module({
        imports: [
          ParentModule.forRootAsync({
            useFactory: (/* Assume I'll make use of ConfigService here */) => ({
                child1: {
                    child1Id: '123'
                },
                child2: {
                    child2Id: '123'
                },
                child3: {
                    child3Id: '123'
                }
            })
          }),
        ],
      })
    export class AppModule {}

Although the child modules can access `PARENT_MODULE_CONFIG_SERVICE ` but I don't want them to load at all.

**Comment by Tony133** [comment]
Hi @mjangir, for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel

The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.

**Comment by mjangir** [comment]
> Hi @mjangir, for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel
> 
> The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.

Sure @Tony133 I discussed on discord and found my answer. Thanks to @jmcdo29
