### ISSUE TITLE
Make official Objection js recipe

### ISSUE THREAD

**Issue by AlexandrosMelissas** [nestjs/nest#8185]
## Feature Request
Official integration with Objection js

## Describe the solution you'd like

I would love if an official stable integration with Objection js existed.

**Comment by smolinari** [comment]
There are a couple community solutions.

https://github.com/willsoto/nestjs-objection
https://github.com/svtslv/nestjs-objection

Scott

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
