### ISSUE TITLE
Exception is not caught by Exception filter when throwing from within an Observable subsricption in a Controller

### ISSUE THREAD

**Issue by NovDavid** [nestjs/nest#8190]
## Bug Report

I'm trying to perform an HTTP call with axios from within a controller, process the returned data within my application, and then return. I'm using rxjs Observables. However when there is an error, eg. ECONNREFUSE, I'm unable to handle that properly, since when I'm throwing an HttpException, it is not caught by the exception filter, and crashes the entire application.
See more details including a minimal repro below.

## Current behavior
The application crashes with the following error:
```
<...>\nest-bug-repro\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:52
            onError(err);
            ^
HttpException: BadRequest
    at C:\git\nest-bug-repro\src\example-service\example.service.ts:16:15
    at C:\git\nest-bug-repro\node_modules\rxjs\src\internal\operators\catchError.ts:116:35
    at OperatorSubscriber._this._error (C:\git\nest-bug-repro\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:52:13)
    at OperatorSubscriber.Subscriber.error (C:\git\nest-bug-repro\node_modules\rxjs\src\internal\Subscriber.ts:91:12)
    at OperatorSubscriber.Subscriber._error (C:\git\nest-bug-repro\node_modules\rxjs\src\internal\Subscriber.ts:124:24)
    at OperatorSubscriber.Subscriber.error (C:\git\nest-bug-repro\node_modules\rxjs\src\internal\Subscriber.ts:91:12)
    at C:\git\nest-bug-repro\node_modules\@nestjs\axios\dist\http.service.js:65:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## Input Code
[nest-bug-repro](https://github.com/NovDavid/nest-bug-repro)

## Expected behavior
The HttpException shall be caught by the Exception filter and return an HTTP error code.

## Environment

<pre><code>
Nest version: 8.0.9
Also tried with 7.5.3, same result
</code></pre>

**Comment by jmcdo29** [comment]
[Why do you subscribe to the original observable here and migrate it to a subject?](https://github.com/NovDavid/nest-bug-repro/blob/main/src/app.controller.ts#L24) What's going on here?

**Comment by kamilmysliwiec** [comment]
Your code is invalid. This issue is unrelated to Nest framework.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
