### ISSUE TITLE
Rest/GraphQL coexist, and how to have Rest invoke GraphQL query internally?

### ISSUE THREAD

**Issue by tangentlin** [nestjs/nest#8201]
I am building a NestJS API and thinking of offering both GraphQL and traditional REST endpoints.  Ideally, I would develop GraphQL first, and REST essentially just make GraphQL query call internally without any redirection. For example:

```JavaScript
// pseudo code
class TraditionalRestController {
  @Get("students")
  getStudents() {
    const query = `{
      students {
        id,
        lastName
      }
    }`;

    // How do execute this GraphQL internally assuming the NestJS application already has GraphQL code and resolvers implemented
    const students = await internalInvokeGraphQL(query);
    return students;
  }
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
