### ISSUE TITLE
Error: invalid expiresIn option for string payload

### ISSUE THREAD

**Issue by JefferyHus** [nestjs/nest#8204]
## Current behavior
I am using the JwtModule and it keeps throwing this error `Error: invalid expiresIn option for string payload` I have tried multiple values but same error is being thrown.

When I remove `expiresIn` property, it works.

## Input Code
```ts
    JwtModule.register({
      secret: 'haha',
      signOptions: {
        expiresIn: 3600,
      }
    }),
```

## Expected behavior
To not throw the error and apply the expiration value.

## Possible Solution
n/a

## Environment

<pre><code>
Nest version: 8.0.0
 
For Tooling issues:
- Node version: v16.3.0
- Platform: Mac

Others:
n/a
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by Elbarae1921** [comment]
this is a [`jsonwebtoken`](https://www.npmjs.com/package/jsonwebtoken) issue. You can't set expiration date if the payload is a string.

> Please note that exp or any other claim is only set if the payload is an object literal. Buffer or string payloads are not checked for JSON validity.

https://www.npmjs.com/package/jsonwebtoken#jwtsignpayload-secretorprivatekey-options-callback

**Comment by JefferyHus** [comment]
@Elbarae1921 The payload is an object.

**Comment by jmcdo29** [comment]
I'll say it again, Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by JefferyHus** [comment]
@jmcdo29 no need to say it again 😅

**Comment by kamilmysliwiec** [comment]
This isn't an issue with the `@nestjs` wrapper library.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
