### ISSUE TITLE
Asynchronous Context Tracking is not working for microservices

### ISSUE THREAD

**Issue by skliarovartem** [nestjs/nest#8210]
## Current behavior
I'm trying to use context to track my requests in microservice. I use NestInterceptor for this reason:

## Input Code
```ts
import {CallHandler, ExecutionContext, Injectable, NestInterceptor} from '@nestjs/common';
import {PinoLogger} from "nestjs-pino";
import {AsyncLocalStorage} from "async_hooks";
import {Observable} from "rxjs";

const asyncLocalStorage = new AsyncLocalStorage();

@Injectable()
export class LoggerInterceptor implements NestInterceptor {

    intercept(context: ExecutionContext, next: CallHandler) {

        return asyncLocalStorage.run(this.logger, () => {
            const res = next.handle.bind(this)()
            return res
        }) as Observable<any>
    }
}

@MessagePattern(SOME_PATTERN)
    async sendFromUser(@Body() body: any) {

        const id = asyncLocalStorage.getStore();
        console.log(id)
        // ...
    }
```

## Expected behavior
It must be possible to get data from async storage in services, so "id" must be "hello!" but not undefined

**Comment by Tony133** [comment]
Hi @skliarovartem,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team of NestJS can evaluate the problem you have reported.

**Comment by constb** [comment]
@skliarovartem I've been trying to tackle the very same problem for a few days last week. I think I found some sort of solution, that seems to work, but it's still being tested. Try this yourself and tell me if this works for you!

First, we need a rxjs operator that runs observables with ALS:

```ts
import { ContextStore, run } from '@app/common';

function withContext<T>(store: () => ContextStore): MonoTypeOperatorFunction<T> {
  return function (source: Observable<T>) {
    return new Observable(observer => {
      let sub: Subscription;

      // run is just stub for ALS.run
      run(store(), () => {
        sub = source.subscribe(observer);
      });

      // @ts-ignore
      return sub;
    });
  };
}
```

This will make ALS available inside the handler, but if your logger interceptor is followed by another interceptor, its `intercept` method will still be ALS-less. So, second we need to run handle with ALS like you do:

```ts
import { ContextStore, run, withContext } from '@app/common';

export class MicroserviceContextInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> | Promise<Observable<any>> {
    const payload = context.switchToRpc().getData();

    const ctx = ContextStore.make(/* ... */); // here I create an ALS store
    return run(ctx, () => next.handle().pipe(withContext(() => ctx))); // run is just stub for ALS.run
  }
}
```

Combined together, I have access to request context in both interceptors that follow this one and in the handler itself:

```ts
import {
  get,
  MicroserviceContextInterceptor,
  RmqAcknowledgementInterceptor,
  RmqTimingLoggerInterceptor,
} from '@app/common';

@Controller()
export class AppController {
  @EventPattern('some.notification')
  @UseInterceptors(MicroserviceContextInterceptor, RmqTimingLoggerInterceptor, RmqAcknowledgementInterceptor)
  async appReceive(data: AppReceiveInput) {
    const ctx = get(); // get is a typed wrapper for ALS.getStore()
    //
  }
}
```

In my case context contains "child logger" that outputs request id. I see reqId field in both timing interceptor output and handler output as well.

**Comment by constb** [comment]
I think this issue may be caused by the way [InterceptorsConsumer](https://github.com/nestjs/nest/blob/master/packages/core/interceptors/interceptors-consumer.ts) converts `next()` between async callback and an observable… Wrapping `subscribe()` on a cold observable reintroduces context back to the flow and does the trick…

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
