### ISSUE TITLE
Improvement request for using built in RabbitMQ features instead of own features

### ISSUE THREAD

**Issue by rluvaton** [nestjs/nest#8218]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The issue relate to _Not receiving messages in the reply queue that sent to RabbitMQ using amqplib and processed by NestJS_

Question (and workaround) of the issue explained [here](https://stackoverflow.com/q/69436001/5923666) in detail

### Describe the solution you'd like

I would like if the RabbitMQ adapter could use the already built-in feature in RabbitMQ (`reply-to`) to determinate if a queue message is a message (`MessagePattern`) or event (`EventPattern`) instead of adding `id` property for the message content

### Teachability, documentation, adoption, migration strategy

For users which use NestJs solely, it will be hidden from them as this is an implementation detail.

For others who use it with other services they probably added a dummy `id` property to make this work

### What is the motivation / use case for changing the behavior?

The motivation is to use the RabbitMQ built-in features instead of creating our own implementation which will help users to understand how to interact with NestJS through RabbitMQ in other languages as there is no need for doing something special to start using message pattern

-----

I'm willing to create a PR if interested

**Comment by kamilmysliwiec** [comment]
If you want to communicate with an external service not built on top of Nest, you shouldn't even use the `ClientProxy` in the first place. Just use the `amqplib` library directly instead, you don't need the proxy.
