### ISSUE TITLE
Not work with nuxt if use as server middleware the main.ts and not mai.js from dist after build

### ISSUE THREAD

**Issue by Mitch-i** [nestjs/nest#8224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
ERROR [ExceptionsHandler] Cannot read property 'findOne' of undefined TypeError: Cannot read property 'findOne' of undefined

[Nest] 16671 - 09/21/2021, 5:00:55 PM ERROR [ExceptionsHandler] Decorating class property failed. Please ensure that proposal-class-properties is enabled and runs after the decorators transform.

Minimum reproduction https://github.com/Mitch-i/nuxt_nest

Run  npm run nuxt:dev and open for example http://localhost:3000/api/users.
ERROR [ExceptionsHandler] Cannot read property 'findAll' of undefined

### Minimum reproduction code

https://github.com/Mitch-i/nuxt_nest

### Steps to reproduce

npm i
npm run nuxt:dev
open url /api/users

### Expected behavior

To work propper

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

@nestjs/common:"^8.0.6
@nestjs/config: ^1.0.1
@nestjs/core: ^8.0.6
@nestjs/platform-fastify:"^8.0.6
@nestjs/sequelize: ^8.0.0

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
