### ISSUE TITLE
use nest main.ts not main.js as server middlevare of nuxt 

### ISSUE THREAD

**Issue by Mitch-i** [nestjs/nest#8226]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Now it produce errors. Can I change something to teach nuxt use of nest @inject and other things.
And what that mean proposal-class-properties is enabled and runs after the decorators transform.
Where to add change?

ERROR [ExceptionsHandler] Cannot read property 'findOne' of undefined TypeError: Cannot read property 'findOne' of undefined

[Nest] 16671 - 09/21/2021, 5:00:55 PM ERROR [ExceptionsHandler] Decorating class property failed. Please ensure that proposal-class-properties is enabled and runs after the decorators transform.

Minimum reproduction https://github.com/Mitch-i/nuxt_nest

Run npm run nuxt:dev and open for example http://localhost:3000/api/users.
ERROR [ExceptionsHandler] Cannot read property 'findAll' of undefined

https://github.com/Mitch-i/nuxt_nest

### Describe the solution you'd like

use main.ts as server middleware

### Teachability, documentation, adoption, migration strategy

---

### What is the motivation / use case for changing the behavior?

To not have 2 separated apps for client and server. To not have cors problems and other

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/8224#issuecomment-934139426
