### ISSUE TITLE
Nodejs cluster not work.

### ISSUE THREAD

**Issue by Folliant** [nestjs/nest#8227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Nodejs cluster not work, because it imported incorrectly.

### Minimum reproduction code

https://i.imgur.com/2sOBAdP.png

### Steps to reproduce

`docker run -it node:14 /bin/sh`

`npm i -g @nestjs/cli`
`nest new cluster`

in `main.ts` put:

```
import cluster from "cluster";
console.log(cluster)
```

`npm run start`

### Expected behavior

Expected that cluster must work.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

   - "@nestjs/common": "^8.0.0",
   - "@nestjs/core": "^8.0.0",
   - "@nestjs/platform-express": "^8.0.0",

### Node.js version

v14.18.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
