### ISSUE TITLE
Transfer awesome-nest ownership

### ISSUE THREAD

**Issue by juliandavidmr** [nestjs/nest#8261]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No problem, I want to transfer awesome-nest to the Nest team.

I have managed [awesome-nest](https://github.com/juliandavidmr/awesome-nestjs) since its inception, it has grown as NestJS does. It is the largest community project I have ever led, and none of this would be possible with all the help of the community. After so long, I have decided to transfer the ownership of awesome-nest to the Nest team.

### Describe the solution you'd like

I hope that the awesome-nest project will grow much more if it is led by the Nest team.

I do not expect to receive anything in return for this transfer of ownership.

### Teachability, documentation, adoption, migration strategy

Not applicable.

### What is the motivation / use case for changing the behavior?

Not applicable

**Comment by juliandavidmr** [comment]
Hi @jmcdo29, a long time ago I was talking by email with John Biundo, but due to personal problems he had to leave, so the conversation ended there. I will be attentive to the steps to follow if the team decides to continue with the receipt of ownership.

I'm also happy to do this, and with a bit of nostalgia because awesome-nest is like a son to me 😅.

**Comment by kamilmysliwiec** [comment]
Great work with the repository so far @juliandavidmr! 

I'd be more than happy to transfer this repo under the NestJS organization so let me know what we have to do to make this happen. This may require some extra work at first but it's definitely worth it!

**Comment by Tony133** [comment]
@juliandavidmr if I remember correctly once you send the repository transfer request you should wait for Kamil to accept, at least it worked like this transferring a repo from one user to another.

**Comment by Tony133** [comment]
@juliandavidmr  yes I think it should work. You give Kamil access to the repository, so being the NestJS organization administrator he can move the repository.

**Comment by kamilmysliwiec** [comment]
> I think the alternative is to add kamilmysliwiec or jmcdo29 as awesome-nestjs admin, they may have permission to do the transfer.

Sounds good!

**Comment by juliandavidmr** [comment]
@kamilmysliwiec, I sent you an invitation.

**Comment by juliandavidmr** [comment]
> juliandavidmr I received & accepted the invite but I still don't have sufficient permissions to transfer the project

@kamilmysliwiec, I thought that GitHub would allow assigning admin permissions to the repository, but after reading the GitHub documentation about repository transfers, it seems to be possible to assign admin role if the repository is part of an organization.

This is written in the doc:

> To transfer repositories to an organization, you must have repository creation permissions in the receiving organization. If organization owners have disabled repository creation by organization members, only organization owners can transfer repositories out of or into the organization.
> 
> Once a repository is transferred to an organization, the organization's default repository permission settings and default membership privileges will apply to the transferred repository.


[Documentation](https://docs.github.com/en/enterprise-server@3.0/repositories/creating-and-managing-repositories/transferring-a-repository#repository-transfers-and-organizations)


It seems that it only remains to try this last alternative. On the other hand, is it okay if we continue the thread by mail? Or if you prefer, we continue here.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/awesome-nestjs

Repository transferred 🎉 💥
