### ISSUE TITLE
Class Validator ValidateNested TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Zyles** [nestjs/nest#8265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am using ValidateNested decorator on an array of objects in my DTO with a child DTO.

When I am not sending in all required properties of the child DTO I get an error:
`Cannot convert undefined or null to object`

Instead it should throw the error from decorator `@IsNotEmpty()` on the property.

Is this a nestjs problem or class-validator?

### Minimum reproduction code

...

### Steps to reproduce

```
app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true, // Only allow properties that are defined in DTOs, so users do not POST/PATCH custom fields
      transform: true,
      exceptionFactory: (validationErrors: ValidationError[] = []) => {
        return new BadRequestException(validationErrors)
      },
    }),
  )

export class OrderDto {
  @IsNotEmpty()
  @Length(1, 255)
  first_name: string

  @IsNotEmpty()
  @Length(1, 255)
  last_name: string

  @Type(() => OrderLineDto)
  @IsArray()
  @ArrayNotEmpty()
  @ValidateNested({ each: true })
  order_lines: OrderLineDto[]
}

export class OrderLineDto {

  @IsNotEmpty()
  sku!: string

  @Type(() => Number)
  @IsNumber()
  @IsNotEmpty()
  @Min(0)
  quantity!: number
}
```

Posting the following request (missing the OrderLineDto field quantity): 
```
{
    "first_name": "First name",
    "last_name": "Last name",
    "order_lines": [
        {
            "sku": "12341",
        }
    ]
}
```

Throws error:
`TypeError: Cannot convert undefined or null to object`

When it should throw error from class validator:
`quantity should not be empty`

### Expected behavior

Throw error from class-validator `quantity should not be empty` instead of `TypeError: Cannot convert undefined or null to object`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

class-validator

### NestJS version

^8.0.6

### Packages versions

"@nestjs/core": "^8.0.6",

### Node.js version

14.17.4

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by Alejandrocuartas** [comment]
@Zyles, could you tell how you solve it?

**Comment by LucasNguyenTVF** [comment]
I also encountered this problem while working on a project and managed to solve it, so I think this solution might be helpful as a reference

### DTO File:

```typescript
class Order {
  @ArrayMinSize(2)
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CreateWaypointInput)
  @Field(() => [CreateWaypointInput])
  waypoints: CreateWaypointInput[];
}

class CreateWaypointInput {
  @IsLatitude()
  @IsNumber()
  @Field()
  lat: number;

  @IsLongitude()
  @IsNumber()
  @Field()
  lng: number;

  @IsString()
  @Field()
  contactName: string;

  @IsPhoneNumber()
  @Field()
  contactPhoneNumber: string;
}

```
The issue arose when the client provided incorrect data types, such as an invalid contactPhoneNumber. The error message I received was:
```
Cannot convert undefined or null to object
```

Root cause:
After spending a few hours debugging, I discovered that the problem was not with NestJS or class-validator. Instead, it was related to how my application handled errors.
Before:
### main.ts
```
await app.useGlobalPipes(
  new ValidationPipe({
    transform: true,
    exceptionFactory: async (errors) => {
      console.log(
        "errors: ",
        errors.map((error) => {
          console.log(error.children);
        }),
      );
      const errorMessages = errors.map((error) =>
        Object.values(error.constraints),  // The problem is here
      );

      console.log(JSON.stringify(errorMessages, null, 2));

      return new BadRequestException(errorMessages.toString());
    },
  }),
);
```

The issue was with how I was extracting error messages. The code was only handling top-level errors and did not account for nested validation errors.
After:
To fix the issue, I implemented a recursive function to correctly extract all error messages, including those nested within child objects.

```
const extractErrorMessages = (errors: ValidationError[]): string[] => {
  const messages: string[] = [];

  errors.forEach((error) => {
    if (error.constraints) {
      messages.push(...Object.values(error.constraints));
    }
    if (error.children && error.children.length > 0) {
      messages.push(...extractErrorMessages(error.children));
    }
  });

  return messages;
};

await app.useGlobalPipes(
  new ValidationPipe({
    transform: true,
    exceptionFactory: async (errors: ValidationError[]) => {
      console.log("Validation errors:", errors);

      const errorMessages = extractErrorMessages(errors);

      console.log("Extracted error messages:", JSON.stringify(errorMessages, null, 2));

      return new BadRequestException(errorMessages.toString());
    },
  }),
);
```
