### ISSUE TITLE
Generic Resolver

### ISSUE THREAD

**Issue by dragonhelios** [nestjs/nest#8274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

I'm attempting to create a generic resolver for a graphQL/TypeORM project I'm working on using a code first approach.

Following the NestJS website examples and some other answers in the issues I've been able to create the Queries ad mutations and name them dynamically, but the @Args passed to the function does not seem to resolve dynamically when the schema is built.  The input types does not get built in the schema and the mapped input types is wrong.

For example: 

```
@Entity()
@InputType('UserInput')
@ObjectType()
export class User {
  @PrimaryGeneratedColumn(Int)
  @Field(() => ID)
  id: number;

  @Column({ nullable: false })
  @Field({ description: 'Firstname of user' })
  firstname: string;

  @Column({ nullable: false })
  @Field({ description: 'Surname of user' })
  surname: string;
}
```

```
@InputType('createUserInput')
export class CreateUserInput {
  @Field({ description: 'Firstname of user' })
  firstname: string;

  @Field({ description: 'Surname of user' })
  surname: string;
}
```

```
@InputType('updateUserInput')
export class UpdateUserInput extends PartialType(CreateUserInput) {
  @Field(() => Int)
  id: number;
}
```

```
export function BaseResolver<T extends Type<unknown>>(entity: T): any {
  @Resolver({ isAbstract: true })
  abstract class BaseResolverHost {
    protected constructor(private readonly BaseService: IBaseDataService<T>) {}

    @Query(() => [entity], {
      name: `get${capitalize(entity.name)}s`,
      nullable: true,
    })
    findAll() {
      return this.BaseService.findAll();
    }

    @Mutation(() => entity, { name: `create${capitalize(entity.name)}` })
    create(
      @Args({
        type: () => entity,
        name: `create${capitalize(entity.name)}Input`,
      })
      createInput: DeepPartial<T>,
    ): Promise<T | boolean> {
      return this.BaseService.create(createInput);
    }

    @Mutation(() => entity, { name: `update${capitalize(entity.name)}` })
    update(
      @Args({
        type: () => entity,
        name: `update${capitalize(entity.name)}Input`,
      })
      updateInput: IUpdateInput<unknown>,
    ) {
      return this.BaseService.update(updateInput);
    }
  }
```

Results in a schema generated:
```
type User {
  id: ID!

  """Firstname of user"""
  firstname: String!

  """Surname of user"""
  surname: String!
}

input UserInput {
  """Firstname of user"""
  firstname: String!

  """Surname of user"""
  surname: String!
}

type Query {
  getUsers: [User!]
}

type Mutation {
  createUser(createUserInput: UserInput!): User!
  updateUser(updateUserInput: UserInput!): User!
  removeUser(id: Int!): User!
}
```

### Minimum reproduction code

https://github.com/dragonhelios/nestjs_graphql_generic_resolver

### Steps to reproduce

1. npm i
2. npm run start:dev
3. review generated schema.gql

### Expected behavior

That the name passed to the @Args arguments for the mutations is resolved at time of the schema being built similar to how the names for the @Query and @Mutation Decorators are.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

8.0.0

### Packages versions

    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^9.0.6",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/typeorm": "^8.0.2",

### Node.js version

16.5.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Tony133** [comment]
Hi @dragonhelios, try to post this problem in the [discord](https://discord.com/invite/G7Qnnhy) support channel. 

However if it can help you I have created a simple quick tutorial on NestJS with GraphQL (code first), maybe it can help you, if you have never used NestJS with GraphQL before.

Link: https://dev.to/tony133/simple-example-graphql-with-nestjs-8-x-3l5i

**Comment by jmcdo29** [comment]
@dragonhelios where are you trying to use the `@InputType()` decorated class? I see you referencing type `entity` often, but nothing about the `@InputType()` class.

**Comment by dragonhelios** [comment]
Hi @Tony133 @jmcdo29 ,

Thanks for the response.

The idea is to use the generic resolver to DRY majority of the queries and mutations.

The minimal viable gtihub should give more clarity. As a simple example I have a User Entity with 2 Input classes, create-user-input and update-user-input. The entity is decorated using @Entity, @Input('UserInput') and @Object(). the input classes is decorated using @Input('updateUserInput') and @Input('createUserInput'). 

I also have a UserResolver class decorated as @Resolver(() => User) and Userservice class.

From the user resolver class I'm wanting to extend the base resolver class.

```
import { Resolver } from '@nestjs/graphql';
import { UserService } from './user.service';
import { User } from './entities/user.entity';
import { BaseResolver } from 'src/base/base.resolver';
import { Logger } from '@nestjs/common';

@Resolver(() => User)
export class UserResolver extends BaseResolver(User) {
  private logger: Logger;
  constructor(private readonly userService: UserService) {
    super(userService);
    this.logger = new Logger();
  }
}

```

The problem I'm having is that when inspection occurs, when the schema.gql file is being built, that the input types is not being resolved and does not get created in the schema.gql file.

```
    @Mutation(() => entity, { name: `update${capitalize(entity.name)}` })
    update(
      @Args({
        type: () => entity,
        name: `update${capitalize(entity.name)}Input`,
      })
      updateInput: IUpdateInput<unknown>,
    ) {
      return this.BaseService.update(updateInput);
    }
```

The above code results in the required mutation being created and named correctly but the input 'createUserInput' and 'updateUserInput' does not created in the schema file and the types for input on the mutations defaults to 'UserInput' instead of the 'createUserInput' and 'updateUserInput' types. The problem seems specific to the name option in this section:

```
    update(
      @Args({
        type: () => entity,
        name: `update${capitalize(entity.name)}Input`,
      })
```

```
type Mutation {
  createUser(createUserInput: UserInput!): User!
  updateUser(updateUserInput: UserInput!): User!
  removeUser(id: Int!): User!
}
```

**Comment by dragonhelios** [comment]
The folder structure was created using nest g resource User. 

Attached screenshot of one of the input classes I'm as well as the other.

![image](https://user-images.githubusercontent.com/44094871/136667678-9a5c7871-a9c4-4947-9cb3-3c85bd270fa0.png)

**Comment by dragonhelios** [comment]
> Right, again, I don't see where you're trying to use the `@InputType()` classes. You set a `name` property for the argument, but the `name` argument is not the type that's going to be used. You use `type: () => entity` which is why it shows up as `UserInput`, because the `entity` you pass in has that decorated type (and is named as `UserInput`). You **need** to use the reference to `CreateUserInput` and `UpateUserInput`

Thanks will try changing to type for the inputs and advise

**Comment by dragonhelios** [comment]
Feeling a bit foolish for not noticing it earlier. Thanks for the assist

```
export function BaseResolver<
  T extends Type<BaseEntity>,
  C extends DeepPartial<T>,
  U extends QueryDeepPartialEntity<T>,
>(entity: T, createInputType: C, updateInputType: U): any {
  @Resolver({ isAbstract: true })
  abstract class BaseResolverHost {
    protected constructor(private readonly BaseService: IBaseDataService<T>) {}

    @Query(() => [entity], {
      name: `get${capitalize(entity.name)}s`,
      nullable: true,
    })
    findAll() {
      return this.BaseService.findAll();
    }

    @Query(() => entity, {
      name: `get${capitalize(entity.name)}`,
      nullable: true,
    })
    findOne(@Args('id', { type: () => Int }) id: number) {
      return this.BaseService.findOne(id);
    }

    @Query(() => entity, {
      name: `get${capitalize(entity.name)}ByName`,
      nullable: true,
    })
    findByFieldOne(@Args('name', { type: () => String }) name: string) {
      return this.BaseService.findByFieldOne('name', name);
    }

    @Mutation(() => entity, { name: `create${capitalize(entity.name)}` })
    create(
      @Args({
        type: () => createInputType,
        name: `create${capitalize(entity.name)}Input`,
      })
      createInput: DeepPartial<T>,
    ): Promise<T | boolean> {
      return this.BaseService.create(createInput);
    }

    @Mutation(() => entity, { name: `update${capitalize(entity.name)}` })
    update(
      @Args({
        type: () => updateInputType,
        name: `update${capitalize(entity.name)}Input`,
      })
      updateInput: IUpdateInput<unknown>,
    ) {
      return this.BaseService.update(updateInput);
    }

    @Mutation(() => entity, { name: `remove${capitalize(entity.name)}` })
    remove(@Args('id', { type: () => Int }) id: number) {
      return this.BaseService.remove(id);
    }
  }
```
