### ISSUE TITLE
No error output with ClientsModule.registerAsync when bufferLogs enabled

### ISSUE THREAD

**Issue by notmedia** [nestjs/nest#8275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

main.ts
```ts
  const app = await NestFactory.create(AppModule, {
    bufferLogs: true,
  });
```

module.ts
```ts
    ClientsModule.registerAsync([
      {
        name: 'TEST',
        inject: [ConfigService],
        useFactory: (config: ConfigService<Config>): ClientProvider => {
          return {
            transport: Transport.GRPC,
            options: {
              package: 'test',
              protoPath: join(__dirname, 'test.proto'),
            },
          };
        },
      },
    ]),
```

For example, **don't** install required @grpc/proto-loader. Btw the problem in async dynamic modules error handlers.

If you run this app, there is no output.

### Expected behavior

Output exists

### Package

- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [x] <code>@nestjs/microservices</code>

### NestJS version

8

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by notmedia** [comment]
Sorry, I don't have enough time for creating a repo. I have already reported another bug for this project with repo and PR.. waiting since February. If you want, you can close this issue.

**Comment by jmcdo29** [comment]
I was able to find where the `flush()` call needs to be made.  I'll have a PR up for it here soon. As for the PR in nestjs/graphql, I'm not aware enough of the context around it at the moment, but I'll try to take a look soon / get Kamil's attention back on it
