### ISSUE TITLE
CurrentUser Decorator

### ISSUE THREAD

**Issue by ToonvanStrijp** [nestjs/nest#830]
## I'm submitting a...

<pre><code>
[X] Feature request
</code></pre>

## Current behavior

Now I'm required to get my user by a service.

## Expected behavior

I would be awesome to have it by a custom decorator like routing-controllers does: [read here](https://github.com/typestack/routing-controllers#currentuser-decorator)
It's a cleaner way to get the current user.

Would it be nice to have a feature like this, or something similar.

**Comment by adrien2p** [comment]
Hey to get the current user you can have a middleware that populate the current user on the request and then create a custom parameter decorator that can be use in the controller to get the user from the request.

**Comment by ToonvanStrijp** [comment]
@adrien2p is there some documentation on it? And does it load the current use on every request or only on the requests that use this custom decorator? Cause it would be efficient to load it only when it's needed to?

**Comment by adrien2p** [comment]
The middleware will apply on the route according to your configuration. And the decorator will be there just to pick it from the request. So if you don’t use the decorator it will not be picked. But the middleware will always be executed before accessing the route. That is depending on the implementation you are doing. There is a doc about custom decorator and about middleware. But what you are trying to do is more related to the implementation of your project.

**Comment by adrien2p** [comment]
If you want the active user, it mean than he is connected, put the authenticated user on the request through the middleware. And the you will be able to pick him from the request

**Comment by ToonvanStrijp** [comment]
@adrien2p yes I get that but for example inside a service I can inject a typeorm repository by doing this:
```
 @InjectRepository(User) private readonly userRepository: Repository<User>
```

My question is how to do this inside the decorator so I can query the database to get the user.

**Comment by adrien2p** [comment]
You can’t that is not the purpose of a decorator. You have to get the user else where before ^^

**Comment by adrien2p** [comment]
With a decorator you can work with metadat (metaprograming)

**Comment by ToonvanStrijp** [comment]
@adrien2p I don't know how to get it to work by doing (metaprogramming) but how I solved it is by extending my User Entity with the TypeORM BaseEntity class:

```
@Entity('users')
export class User extends BaseEntity {
...
}
```
What I can do now in the decorator is:

```
import { createParamDecorator } from '@nestjs/common';
import {User} from './user.entity';

export const CurrentUser = createParamDecorator(async (data, req) => {

    if (req.session.hasOwnProperty('userId') && !!req.session.userId) {
        return await User.findOne({id: req.session.userId})
    } else {
        return null;
    }
});
```

The BaseEntity class is getting the current connection context in some way, so that enabled my decorator to use the database connection and query it :).

**Comment by adrien2p** [comment]
Great :) good job

**Comment by kamilmysliwiec** [comment]
Just wanted to add: Nest gives flexibility to easily create any type of decorator. We haven't provided a built-in solution to don't suggest any auth strategy/database.

**Comment by Diluka** [comment]
here is a simple one
```ts
import { createParamDecorator, UnauthorizedException } from '@nestjs/common';

export interface CurrentUserOptions {
  required?: boolean;
}

export const CurrentUser: (options?: CurrentUserOptions) => ParameterDecorator = createParamDecorator((options: CurrentUserOptions = {}, req) => {
  const user = req.user;
  if (options.required && !user) {
    throw new UnauthorizedException();
  }
  return user;
});

```
