### ISSUE TITLE
feat(core): Implicitly throw an error when someone provides not a module to imports array

### ISSUE THREAD

**Issue by Ayzrian** [nestjs/nest#8302]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Nest.js silently accepts non-module in `imports` array. e.g.

```typescript
@Module({
  imports: [SomeClassThatIsNotModule],
})
export class TasksModule {}
```

### Describe the solution you'd like

Nest.js should throw an error when a developer makes an obvious mistake and tries to import anything that is not a module. 

### Teachability, documentation, adoption, migration strategy

Though throwing an error is not backward compatible, but taking into consideration that most applications are written correctly the change should be compatible. 

No documentation updates are needed, the change happens under the hood of the framework.

### What is the motivation / use case for changing the behavior?

Making Nest.js framework more reliable framework and enhance developers quality of life.

**Comment by Ayzrian** [comment]
Should I start working on a PR to implement this?

**Comment by jmcdo29** [comment]
Just a heads up, `forwardRef`fed modules aren't done as objects. It's just
```ts
imports: [forwardRef(() => OtherModule)]
```
so it will be a function, but it won't have the `@Module()` metadata.

**Comment by micalevisk** [comment]
I just prototyped this approach here: https://github.com/micalevisk/nest/commit/747ee022508c990acd068052e97a9b8b7bfa37c8

![image](https://user-images.githubusercontent.com/13461315/145700109-de383068-39b2-4f76-97e0-ff2aa5a5c687.png)

---

the issue with this solution is that it won't be backward-compatible, right? Projects out there could have an injectable that has no dependencies on `imports`, and this doesn't crashes the app.

So as this feat might be introduced only in the next major release, it could display more info, like:

![image](https://user-images.githubusercontent.com/13461315/145700362-83b1cb27-ae5c-43fa-af8f-020d7545b56b.png)

**Comment by jmcdo29** [comment]
This is looking great! Thanks for the work on it

**Comment by micalevisk** [comment]
what if we add this in Nest v8 but using an warning instead. And then turning it into an error in v9?

**Comment by kamilmysliwiec** [comment]
@micalevisk sounds good to me!
