### ISSUE TITLE
8.1.0 breaks named imports when using ESM

### ISSUE THREAD

**Issue by BenSjoberg** [nestjs/nest#8320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

8.1.0 must seems to have changed something with exports, which affects projects using pure ESM. After updating, my application fails to launch with the following message:

```
import { Controller, Get, Header } from '@nestjs/common';
         ^^^^^^^^^^
SyntaxError: Named export 'Controller' not found. The requested module '@nestjs/common' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

Downgrading to 8.0.11 resolves the issue. A workaround without downgrading is to do something like:

```
import nestcommon from '@nestjs/common';
const import { Controller, Get, Header } = nestcommon;
```

But this is pretty clumsy.

Our project transpiles TypeScript to ESM, instead of to CommonJS, since some of our dependencies have moved to pure ESM without a CommonJS fallback.

### Minimum reproduction code

https://github.com/BenSjoberg/nest-esm-import-issue-example

### Steps to reproduce

* Install @nestjs/common 8.0.11
* Create a file called test.mjs with the content `import { Controller } from '@nestjs/common';`
  * Alternatively, named the file test.js and set `"type": "module"` in package.json
* Run `node test.mjs` - it should work.
* Upgrade @nestjs/common to 8.1.0, it will fail with the error I described.

The sample repo I linked shows the issue in a working nest.js project. The initial commit (bfcd0c99) works because it's pinned to Nest 8.0.x, the latest commit doesn't work because I updated to 8.1.0.

### Expected behavior

Named imports should work from pure ESM as they did in 8.0.x.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

- `@nestjs/cli`: 8.1.2
- `@nestjs/common`: 8.1.0
- `@nestjs/core`: 8.1.0
- `@nestjs/platform-express`: 8.1.0
- `@nestjs/schematics`: 8.0.3
- `@nestjs/testing`: 8.1.0

### Node.js version

16.11.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by vadistic** [comment]
@kamilmysliwiec FYI same thing is still broken for `@nestjs/graphql` https://github.com/nestjs/graphql/issues/1843

**Comment by BenSjoberg** [comment]
This appears to have broken again in 8.3.0 due to 329b08311960a6415c1d91af6991faf736e8c927.

Would it be possible keep TypeScript at 4.3.x until 4.6 is released? Based on my testing in the dev release of TypeScript, the problem that causes this will be fixed in 4.6.

**Comment by sionzee** [comment]
@BenSjoberg I think this deserves a new issue otherwise it won't get fixed.

**Comment by kamilmysliwiec** [comment]
Fixed in 8.3.1

**Comment by huan** [comment]
I run into this issue today with `@nestjs/common@8.3.1`:

```sh
┌ huan@dev.zixia.net:~/git/wechaty/friday/src/core/statuspage/sagas [19:31:42] tty:[3] jobs:[0]
└ {nestjs} $ ./statuspage.saga.spec.ts 
file:///home/huan/git/wechaty/friday/src/wechaty-repository/wechaty.repository.ts:2
import { Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
                     ^^^^^^^^^^^^^^^
SyntaxError: Named export 'OnModuleDestroy' not found. The requested module '@nestjs/common' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@nestjs/common';
const { Injectable, OnModuleDestroy, OnModuleInit } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

$ npm ls @nestjs/common
friday.bot@1.13.15 /home/huan/git/wechaty/friday
├── @nestjs/common@8.3.1
├─┬ @nestjs/core@8.3.1
│ └── @nestjs/common@8.3.1 deduped
├─┬ @nestjs/cqrs@8.0.2
│ └── @nestjs/common@8.3.1 deduped
├─┬ @nestjs/mapped-types@1.0.1
│ └── @nestjs/common@8.3.1 deduped
├─┬ @nestjs/platform-express@8.3.1
│ └── @nestjs/common@8.3.1 deduped
├─┬ @nestjs/schedule@1.0.2
│ └── @nestjs/common@8.3.1 deduped
└─┬ @nestjs/testing@8.3.1
  └── @nestjs/common@8.3.1 deduped

┌ huan@dev.zixia.net:~/git/wechaty/friday/src/core/statuspage/sagas [19:33:40] tty:[3] jobs:[0]
└ {nestjs} $ npm ls typescript
friday.bot@1.13.15 /home/huan/git/wechaty/friday
├─┬ @chatie/eslint-config@1.0.4
│ └─┬ @typescript-eslint/eslint-plugin@4.33.0
│   └─┬ tsutils@3.21.0
│     └── typescript@4.5.5 deduped
├─┬ @chatie/tsconfig@4.6.2
│ ├─┬ ts-node@10.5.0
│ │ └── typescript@4.5.5 deduped
│ ├─┬ tstest@1.0.1
│ │ └─┬ tap@15.1.6
│ │   └── typescript@4.5.5 deduped
│ └── typescript@4.5.5
├─┬ @nestjs/cli@8.2.1
│ ├─┬ fork-ts-checker-webpack-plugin@6.5.0
│ │ └── typescript@4.5.5 deduped
│ └── typescript@4.5.5 deduped
└─┬ @nestjs/schematics@8.0.6
  └── typescript@4.5.5 deduped
```

Reproduce repo:

https://github.com/wechaty/friday/tree/25c04016497a7f3af44e6563b5c88e0f8a8ffe25

**Comment by sionzee** [comment]
@huan 
The bug was again fixed in 8.3.1 and it works without issues. 

That must be an issue on your side, if you generate a new project, you will notice it works out of the box.

Looks like you are using SWC, have you make a right configuration for SWC to be running in es mode? The default tool for test is ts-node at nestjs, in case of swc you must enable decorators + proper settings for latest ES.

**Comment by huan** [comment]
@sionzee Thanks for the quick reply!

I'm working on it and trying to figure out the problem right now.

My case is very strange: all the code works without any problem this afternoon; after I do an `rm -fr node_modules/ && npm i`, then this error message jumped out.

My SWC works in the past days. I guess my problem is related to the `node_modules` file change.

I will update here when I got any updates.

**Comment by huan** [comment]
## Update

it seems that @sionzee is right, my issue is related to swc.

I have created an issue on my repo for continuing tracking my problem.

- https://github.com/wechaty/friday/issues/114

Thank you very much!

**Comment by Toilal** [comment]
I hit this issue, and I can confirm it's fixed by upgrading.
