### ISSUE TITLE
TypeError: common_1.Version is not a function

### ISSUE THREAD

**Issue by brave-coder9** [nestjs/nest#8330]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

7.6.15 -> 8.1.1

### Describe the regression

I was going to use Versioning of nestjs 8.
But it's not working on my server.

### Input code

- `main.ts`
```ts
app.enableVersioning({
    type: VersioningType.URI,
})
```
- `controller`
```ts
@Version('1')
@Get('/scan/:id')
scan(
    @Param('id') id: string,
    @Res() res: Response,
) {
    return res.redirect(`/post/${id}`)
}
```

### Expected behavior

Nest app should not die.

**Comment by brave-merida** [comment]
I can't provide it because it's working on my local but not only ubuntu server.
Maybe this will be enough:
> - main.ts
app.enableVersioning({
    type: VersioningType.URI,
})
> - controller
@Version('1')
@Get('/scan/:id')
scan(
    @Param('id') id: string,
    @Res() res: Response,
) {
    return res.redirect(`/post/${id}`)
}

**Comment by micalevisk** [comment]
@brave-merida what's the output of `grep version ./node_modules/@nestjs/common/package.json`?
