### ISSUE TITLE
I don't know if I'm using the migrations correctly

### ISSUE THREAD

**Issue by TemaOvchinnikov** [nestjs/nest#8350]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I meet a lot of questions about migration

### Describe the solution you'd like

`{
  "type": "mysql",
  "host": "localhost",
  "port": 3306,
  "username": "root",
  "password": "root",
  "database": "app1",
  "entities": ["dist/**/*.entity{.ts,.js}"],
  "synchronize": false, //true
  "migrations": ["dist/migrations/*{.ts,.js}"],
  "cli": {
    "migrationsDir": "src/migrations"
  }
}`

`"scripts": {
    "typeorm": "node --require ts-node/register ./node_modules/typeorm/cli.js",
    "migrate:run": "npm run build && npm run typeorm migration:run",
    "migrate:generate": "npm run build && npm run typeorm migration:generate -- -n",
    "migrate:create": "npm run build && npm run typeorm migration:create -- -n",
    "migrate:revert": "npm run build && npm run typeorm migration:revert",
    "migrate:show": "npm run build && npm run typeorm migration:show",
    "migrate:drop": "npm run build && npm run typeorm schema:drop",
    "migrate:fresh": "npm run build && npm run typeorm schema:drop && npm run typeorm migration:run"
  },`

`npm run migrate:generate tablename
npm run migrate:create tablename
npm run migrate:run
npm run migrate:revert
npm run migrate:show
npm run migrate:drop
npm run migrate:fresh`

### Teachability, documentation, adoption, migration strategy

Followed this documentation [Migrations](https://typeorm.io/#/migrations)

### What is the motivation / use case for changing the behavior?

I love you NAN https://www.angular.love/2020/11/20/przywitaj-nan-stack/ motivation

**Comment by micalevisk** [comment]
you can ask this on TypeORM's repo https://github.com/typeorm/typeorm or go to nestjs discord (under `#nestjs-typeorm`) instead
