### ISSUE TITLE
Memory Leak in Tests

### ISSUE THREAD

**Issue by cramhead** [nestjs/nest#8392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running multiple tests in a single test run the memory increases for each test module

### Minimum reproduction code

https://github.com/cramhead/test-test/

### Steps to reproduce

This code uses the 
1. The scaffolding provided by Nestjs, so `nest new test-test`
2. Duplicates and renames the app.e2e-spec.ts and renames to app2.e2e-spec.ts
3. Modifies the test:e2e script to expose memory usage

### Expected behavior

Memory should not increase on each test module

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^27.0.6",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

# test-test
exposes memory leak in Nestjs testing infrastructure

The attached image shows that running the same test twice in one test run has increased the memory use on each test.
![image](https://user-images.githubusercontent.com/386035/138190465-354634ee-a902-42f4-ad7f-dc3e8a83b0ca.png)

**Comment by jmcdo29** [comment]
It could also be related to supertest. Or out could just generally be a jest bug. I'm not sure what we'd have to do to specify this is related explicitly to nest

**Comment by jmcdo29** [comment]
I think we'd need to check if the same thing happens with Ava, mocha, or some other testing framework

**Comment by jmcdo29** [comment]
Swapping out mocha shouldn't be _too_ tough. Good to know it's not related to supertest though

**Comment by kamilmysliwiec** [comment]
As @micalevisk, this issue doesn't seem to be related to Nest & there's not much we can do here.
