### ISSUE TITLE
Dto with class-validators doesm work out of the box with websockets (lack of documentation)

### ISSUE THREAD

**Issue by pedrohba1** [nestjs/nest#8393]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

If I have a Dto like this:
```js
export class CreateDto {
  @IsNotEmpty()
  id: string;
}
``` 

And my method calls it like this:

```js
  @SubscribeMessage('createSomething')
  async create(
    @MessageBody() createDto: CreateDto,
  ) {
    this.server.emit('createSomething',createDto);
  }
```

Dto `class-validators`, more specific, `@IsNotEmpty` in this case, does not apply for the `createDto` variable. I can send a message to "createSomething" without the `id` and it will execute the funciton normally. I want it to throw a websocket exception.

### Describe the solution you'd like

I would either the behavior I want implemented or a more specific documentation on how to achieve this behavior. 
Currently, there are pipe validators and exception filters for websockets in documentation, but nothing that gets going for this specific case.

### Teachability, documentation, adoption, migration strategy

 Since this is a behavior that most developers would want (validating requests is crucial), I think it would be useful at least a documentation for this specific case.

### What is the motivation / use case for changing the behavior?

I need the MessageBody of my weboscket requests to be validated. It needs to be a very specific set of data, and validating it inside the controller and throwing errors if it does not match doesn't look like the best approach.
I want to do it like I do in the HTTP reques, but in Websocketst: Validate in the DTO and it throws the exception.

**Comment by jmcdo29** [comment]
Did you actually bind the `ValidaitonPipe` to the websocket gateway?
