### ISSUE TITLE
HttpModule error : TypeError: Converting circular structure to JSON     --> starting at object with constructor 'ClientRequest'

### ISSUE THREAD

**Issue by islamhanafi94** [nestjs/nest#8417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use `HttpModule` to make an api call and return the result directly in order to respond to the client

as per the Documentation : https://docs.nestjs.com/techniques/http-module

Nest should auto subscribe for this

i'm following the docs but I still getting this error 

```
[Nest] 100256  - 10/23/2021, 2:01:15 PM   ERROR [ExceptionsHandler] Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle


```

### Minimum reproduction code

https://github.com/islamhanafi94/httpModuleIssue_Nestjs

### Steps to reproduce

```
npm i 
npm run start:dev

go to http://localhost:3100 and check the console for errors
```

### Expected behavior

Nest automatically subscribe for the observable and return the data in json

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nest/axios

### NestJS version

8.1.3

### Packages versions

-     "@nestjs/axios": "^0.0.3",
-     "@nestjs/common": "^8.0.0",
-     "@nestjs/core": "^8.0.0",
-     "@nestjs/platform-express": "^8.0.0",
-     "axios": "^0.23.0",
-     "reflect-metadata": "^0.1.13",
-     "rimraf": "^3.0.2",
-     "rxjs": "^7.2.0"

-     "@nestjs/cli": "^8.0.0",
-     "@nestjs/schematics": "^8.0.0",
-     "@nestjs/testing": "^8.0.0",
-     "@types/express": "^4.17.13",
-     "@types/jest": "^27.0.1",
-     "@types/node": "^16.0.0",
-     "@types/supertest": "^2.0.11",
-     "@typescript-eslint/eslint-plugin": "^4.28.2",
-     "@typescript-eslint/parser": "^4.28.2",
-     "eslint": "^7.30.0",
-     "eslint-config-prettier": "^8.3.0",
-     "eslint-plugin-prettier": "^3.4.0",
-     "jest": "^27.0.6",
-     "prettier": "^2.3.2",
-     "supertest": "^6.1.3",
-     "ts-jest": "^27.0.3",
-     "ts-loader": "^9.2.3",
-     "ts-node": "^10.0.0",
-     "tsconfig-paths": "^3.10.1",
-     "typescript": "^4.3.5"

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by ThinhNguyen-Madi** [comment]
I still have these issues with nesjs version `8.0.0`.
