### ISSUE TITLE
Memory Leak in Testing

### ISSUE THREAD

**Issue by cramhead** [nestjs/nest#8437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running e2e tests memory increases for each file. 
When running Jest tests outside of Nestjs the memory does not increase.
When running unit test on autogenerated unit test memory does not increase. 

Having some tests that leak memory and some that do not leak memory running with the same versions of the libraries should clearly point out that it's not a Jest issue. Despite that, I tried all approaches laid out in https://github.com/facebook/jest/issues/7874 and tried all the options presented there the end to end tests continue to leak memory. 

The image attach shows 
Top Left: Jest config with Ts-jest adjustments
Top-Right: The end to end test with attempts to reclaim memory
Middle: The Nodejs and Jest options provide
Bottom: Three test runs. The first is end to end tests with a memory leak, the next is standard Jest tests not using Nestjs, the next tests on scaffolded code

![image](https://user-images.githubusercontent.com/386035/138752715-08a84059-2b2e-4569-aae7-1bd84d1a9807.png)

### Minimum reproduction code

https://github.com/cramhead/test-test/

### Steps to reproduce

1. `npm run test:e2e`
2. View memory increasing in output
3. `npm run test:simple`
4. View memory does not increase in output
5. `npm run test`
6. View memory does not increase in output

### Expected behavior

Memory should not go up in a consistent manner as more tests are run

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

"dependencies": {
    "@nestjs/common": "^8.1.2",
    "@nestjs/core": "^8.1.2",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/testing": "^8.1.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.2",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^27.3.1",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  }

### Node.js version

14.17.4

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Okay, so I'm getting around to looking into this (sorry for the wait), and I extended the number of tests running to 7 instead of  2. Also, just to be sure this wasn't from supertest, I changed the test to use node's `http` module like so:

```ts
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as http from 'http';
import { AppModule } from './../src/app.module';

describe('AppController (e2e)', () => {
  let app: INestApplication;
  let url: string;
  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.listen(0);
    url = await app.getUrl();
  });

  afterEach(async () => {
    app.flushLogs(); // force flush to hopefully remove references to logs

    await app.close(); // close the app to force cleanup
    app = null; // remove reference to the app

    global.gc && global.gc(); // instigate garbage collection
  });

  it('/ (GET)', (done) => {
    http.get(url, (res) => {
      let data = '';
      res.on('data', (chunk) => {
        data += chunk;
      });
      res.on('end', () => {
        expect(data).toBe('Hello World!');
        expect(res.statusCode).toBe(200);
        done();
      });
    });
  });
});
```

Now, when I run the tests I get the following output:

```
> test-test@0.0.1 test:e2e /home/jay/Documents/code/help/nest-memory-leak-test
> NODE_OPTIONS=--max-old-space-size=6144 NODE_ENV=test && node --expose-gc ./node_modules/jest/bin/jest -i --config ./test/jest-e2e.json --runInBand --logHeapUsage --no-cache

 PASS  test/app6.e2e-spec.ts (150 MB heap size)
 PASS  test/app.e2e-spec.ts (153 MB heap size)
 PASS  test/app7.e2e-spec.ts (154 MB heap size)
 PASS  test/app5.e2e-spec.ts (154 MB heap size)
 PASS  test/app3.e2e-spec.ts (154 MB heap size)
 PASS  test/app2.e2e-spec.ts (154 MB heap size)
 PASS  test/app4.e2e-spec.ts (154 MB heap size)

Test Suites: 7 passed, 7 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        5.165 s
Ran all test suites.
```
So, it does increase for the first three tests, but then it stays constant.

I also created a `ts-jest` specific suite of the simple `jest` tests and made it `async` to ensure it wasn't a promise or `ts-jest` related issue, which is doesn't seem to be. I'm going to extend this test suite out to an obscene number and see if it ever increases over the max so far, or if it just runs up to this ceiling value and doesn't rise above for whatever reason.

**Comment by cramhead** [comment]
That's awesome. 
I ran tests with tracing, `node --inspect-brk --trace_gc -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand`, and found that the URLSearchParams holds lots of memory
![image](https://user-images.githubusercontent.com/386035/141593629-1da1f9fb-9eb2-4cb8-8bd2-a7ccb68febd4.png)

**Comment by JVMartin** [comment]
We are running into this issue as well.

Strangely, we are seeing the heap both grow + shrink over time, though the trend is definitely upwards:
![image](https://user-images.githubusercontent.com/4450814/147611979-dbf082e2-7909-4cce-920e-b25ea80f0726.png)

(Ran with `--runInBand --logHeapUsage`)

**Comment by kamilmysliwiec** [comment]
@JVMartin 

> Strangely, we are seeing the heap both grow + shrink over time, though the trend is definitely upwards:

If that's the case, this is likely caused by your application, not NestJS itself.

**Comment by JVMartin** [comment]
@kamilmysliwiec The leak can also be shown with the [`typescript-starter` project (branch here).](https://github.com/JVMartin/typescript-starter/tree/e2e-leak/test)

```
npm run test:e2e -- --runInBand --logHeapUsage

> nest-typescript-starter@1.0.0 test:e2e /home/jacob/code/typescript-starter
> jest --config ./test/jest-e2e.json "--runInBand" "--logHeapUsage"

 PASS  test/app-17.e2e-spec.ts (160 MB heap size)
 PASS  test/app-30.e2e-spec.ts (175 MB heap size)
 PASS  test/app-19.e2e-spec.ts (187 MB heap size)
 PASS  test/app-13.e2e-spec.ts (165 MB heap size)
 PASS  test/app-15.e2e-spec.ts (180 MB heap size)
 PASS  test/app-23.e2e-spec.ts (191 MB heap size)
 PASS  test/app-21.e2e-spec.ts (197 MB heap size)
 PASS  test/app-28.e2e-spec.ts (211 MB heap size)
 PASS  test/app-26.e2e-spec.ts (223 MB heap size)
 PASS  test/app-24.e2e-spec.ts (235 MB heap size)
 PASS  test/app-29.e2e-spec.ts (246 MB heap size)
 PASS  test/app-25.e2e-spec.ts (257 MB heap size)
 PASS  test/app-27.e2e-spec.ts (268 MB heap size)
 PASS  test/app-22.e2e-spec.ts (273 MB heap size)
 PASS  test/app-10.e2e-spec.ts (286 MB heap size)
 PASS  test/app-9.e2e-spec.ts (299 MB heap size)
 PASS  test/app-5.e2e-spec.ts (311 MB heap size)
 PASS  test/app-6.e2e-spec.ts (322 MB heap size)
 PASS  test/app-16.e2e-spec.ts (333 MB heap size)
 PASS  test/app-11.e2e-spec.ts (338 MB heap size)
 PASS  test/app-8.e2e-spec.ts (352 MB heap size)
 PASS  test/app-12.e2e-spec.ts (365 MB heap size)
 PASS  test/app.e2e-spec.ts (376 MB heap size)
 PASS  test/app-7.e2e-spec.ts (388 MB heap size)
 PASS  test/app-20.e2e-spec.ts (399 MB heap size)
 PASS  test/app-14.e2e-spec.ts (404 MB heap size)
 PASS  test/app-2.e2e-spec.ts (418 MB heap size)
 PASS  test/app-18.e2e-spec.ts (431 MB heap size)
 PASS  test/app-3.e2e-spec.ts (442 MB heap size)
 PASS  test/app-4.e2e-spec.ts (454 MB heap size)
```

**Comment by micalevisk** [comment]
@JVMartin the heap size still increases even when the spec file does nothing, so it seems to be a Jest issue(?)

```ts
import * as request from 'supertest';
// import { Test } from '@nestjs/testing';
// import { AppModule } from './../src/app.module';
import { INestApplication } from '@nestjs/common';

describe('AppController (e2e)', () => {
  let app: INestApplication;

  /*
  beforeAll(async () => {
    const moduleFixture = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });
  */

  it('/ (GET)', () => {
    expect(true).toBe(true)
    /*
    return request(app.getHttpServer())
      .get('/')
      .expect(200)
      .expect('Hello World!');
    */
  });
});

```

```
$ npm run test:e2e -- --runInBand --logHeapUsage

> nest-typescript-starter@1.0.0 test:e2e
> jest --config ./test/jest-e2e.json "--runInBand" "--logHeapUsage"

 PASS  test/app-19.e2e-spec.ts (5.205 s, 138 MB heap size)
 PASS  test/app-22.e2e-spec.ts (145 MB heap size)
 PASS  test/app-5.e2e-spec.ts (146 MB heap size)
 PASS  test/app-25.e2e-spec.ts (153 MB heap size)
 PASS  test/app-28.e2e-spec.ts (152 MB heap size)
 PASS  test/app-9.e2e-spec.ts (159 MB heap size)
 PASS  test/app-18.e2e-spec.ts (158 MB heap size)
 PASS  test/app-8.e2e-spec.ts (165 MB heap size)
 PASS  test/app-7.e2e-spec.ts (166 MB heap size)
 PASS  test/app-4.e2e-spec.ts (173 MB heap size)
 PASS  test/app-16.e2e-spec.ts (173 MB heap size)
 PASS  test/app.e2e-spec.ts (180 MB heap size)
 PASS  test/app-20.e2e-spec.ts (180 MB heap size)
 PASS  test/app-30.e2e-spec.ts (186 MB heap size)
 PASS  test/app-26.e2e-spec.ts (186 MB heap size)
 PASS  test/app-24.e2e-spec.ts (193 MB heap size)
 PASS  test/app-6.e2e-spec.ts (193 MB heap size)
 PASS  test/app-12.e2e-spec.ts (199 MB heap size)
 PASS  test/app-27.e2e-spec.ts (200 MB heap size)
 PASS  test/app-14.e2e-spec.ts (206 MB heap size)
 PASS  test/app-11.e2e-spec.ts (206 MB heap size)
 PASS  test/app-13.e2e-spec.ts (213 MB heap size)
 PASS  test/app-2.e2e-spec.ts (213 MB heap size)
 PASS  test/app-15.e2e-spec.ts (219 MB heap size)
 PASS  test/app-10.e2e-spec.ts (219 MB heap size)
 PASS  test/app-21.e2e-spec.ts (226 MB heap size)
 PASS  test/app-17.e2e-spec.ts (225 MB heap size)
 PASS  test/app-3.e2e-spec.ts (232 MB heap size)
 PASS  test/app-23.e2e-spec.ts (232 MB heap size)
 PASS  test/app-29.e2e-spec.ts (239 MB heap size)
```

**Comment by JVMartin** [comment]
@micalevisk I can't replicate that at all. When I apply those changes to all 30 files, my heap size remains constant, no matter how many times I run it:

```
» npm run test:e2e -- --runInBand --logHeapUsage

> nest-typescript-starter@1.0.0 test:e2e /home/leng/code/typescript-starter
> jest --config ./test/jest-e2e.json "--runInBand" "--logHeapUsage"

 PASS  test/app-19.e2e-spec.ts (137 MB heap size)
 PASS  test/app-22.e2e-spec.ts (144 MB heap size)
 PASS  test/app-11.e2e-spec.ts (142 MB heap size)
 PASS  test/app-23.e2e-spec.ts (148 MB heap size)
 PASS  test/app-26.e2e-spec.ts (144 MB heap size)
 PASS  test/app-18.e2e-spec.ts (151 MB heap size)
 PASS  test/app-12.e2e-spec.ts (157 MB heap size)
 PASS  test/app-28.e2e-spec.ts (152 MB heap size)
 PASS  test/app-8.e2e-spec.ts (159 MB heap size)
 PASS  test/app-25.e2e-spec.ts (156 MB heap size)
 PASS  test/app-13.e2e-spec.ts (162 MB heap size)
 PASS  test/app-5.e2e-spec.ts (160 MB heap size)
 PASS  test/app-16.e2e-spec.ts (136 MB heap size)
 PASS  test/app.e2e-spec.ts (153 MB heap size)
 PASS  test/app-17.e2e-spec.ts (160 MB heap size)
 PASS  test/app-21.e2e-spec.ts (167 MB heap size)
 PASS  test/app-10.e2e-spec.ts (150 MB heap size)
 PASS  test/app-2.e2e-spec.ts (146 MB heap size)
 PASS  test/app-30.e2e-spec.ts (167 MB heap size)
 PASS  test/app-6.e2e-spec.ts (144 MB heap size)
 PASS  test/app-14.e2e-spec.ts (181 MB heap size)
 PASS  test/app-3.e2e-spec.ts (148 MB heap size)
 PASS  test/app-29.e2e-spec.ts (154 MB heap size)
 PASS  test/app-4.e2e-spec.ts (152 MB heap size)
 PASS  test/app-27.e2e-spec.ts (168 MB heap size)
 PASS  test/app-7.e2e-spec.ts (145 MB heap size)
 PASS  test/app-9.e2e-spec.ts (139 MB heap size)
 PASS  test/app-15.e2e-spec.ts (145 MB heap size)
 PASS  test/app-24.e2e-spec.ts (151 MB heap size)
 PASS  test/app-20.e2e-spec.ts (147 MB heap size)

Test Suites: 30 passed, 30 total
Tests:       30 passed, 30 total
Snapshots:   0 total
Time:        2.984 s
Ran all test suites.
```

**Comment by micalevisk** [comment]
that's weird. I've used `--clearCache` and  
`rm test/app-*`  
`for i in {2..60}; do cp test/app.e2e-spec.ts test/app-$i.e2e-spec.ts; done`

<details>
<summary>summary</summary>

```
 PASS  test/app-59.e2e-spec.ts (143 MB heap size)
 PASS  test/app-19.e2e-spec.ts (145 MB heap size)
 PASS  test/app-37.e2e-spec.ts (152 MB heap size)
 PASS  test/app-35.e2e-spec.ts (151 MB heap size)
 PASS  test/app-28.e2e-spec.ts (158 MB heap size)
 PASS  test/app-44.e2e-spec.ts (157 MB heap size)
 PASS  test/app-3.e2e-spec.ts (164 MB heap size)
 PASS  test/app-58.e2e-spec.ts (164 MB heap size)
 PASS  test/app-14.e2e-spec.ts (171 MB heap size)
 PASS  test/app-40.e2e-spec.ts (171 MB heap size)
 PASS  test/app-2.e2e-spec.ts (178 MB heap size)
 PASS  test/app-22.e2e-spec.ts (178 MB heap size)
 PASS  test/app-52.e2e-spec.ts (185 MB heap size)
 PASS  test/app-13.e2e-spec.ts (185 MB heap size)
 PASS  test/app-15.e2e-spec.ts (192 MB heap size)
 PASS  test/app-36.e2e-spec.ts (192 MB heap size)
 PASS  test/app-39.e2e-spec.ts (199 MB heap size)
 PASS  test/app-20.e2e-spec.ts (199 MB heap size)
 PASS  test/app-31.e2e-spec.ts (206 MB heap size)
 PASS  test/app-47.e2e-spec.ts (206 MB heap size)
 PASS  test/app-57.e2e-spec.ts (213 MB heap size)
 PASS  test/app-53.e2e-spec.ts (213 MB heap size)
 PASS  test/app-16.e2e-spec.ts (219 MB heap size)
 PASS  test/app-7.e2e-spec.ts (219 MB heap size)
 PASS  test/app-12.e2e-spec.ts (226 MB heap size)
 PASS  test/app-23.e2e-spec.ts (226 MB heap size)
 PASS  test/app-8.e2e-spec.ts (233 MB heap size)
 PASS  test/app-51.e2e-spec.ts (233 MB heap size)
 PASS  test/app-42.e2e-spec.ts (240 MB heap size)
 PASS  test/app-34.e2e-spec.ts (240 MB heap size)
 PASS  test/app.e2e-spec.ts (247 MB heap size)
 PASS  test/app-10.e2e-spec.ts (247 MB heap size)
 PASS  test/app-27.e2e-spec.ts (254 MB heap size)
 PASS  test/app-33.e2e-spec.ts (254 MB heap size)
 PASS  test/app-60.e2e-spec.ts (261 MB heap size)
 PASS  test/app-25.e2e-spec.ts (261 MB heap size)
 PASS  test/app-5.e2e-spec.ts (268 MB heap size)
 PASS  test/app-32.e2e-spec.ts (268 MB heap size)
 PASS  test/app-49.e2e-spec.ts (274 MB heap size)
 PASS  test/app-45.e2e-spec.ts (275 MB heap size)
 PASS  test/app-24.e2e-spec.ts (281 MB heap size)
 PASS  test/app-21.e2e-spec.ts (281 MB heap size)
 PASS  test/app-4.e2e-spec.ts (288 MB heap size)
 PASS  test/app-9.e2e-spec.ts (288 MB heap size)
 PASS  test/app-50.e2e-spec.ts (295 MB heap size)
 PASS  test/app-30.e2e-spec.ts (295 MB heap size)
 PASS  test/app-17.e2e-spec.ts (301 MB heap size)
 PASS  test/app-54.e2e-spec.ts (302 MB heap size)
 PASS  test/app-26.e2e-spec.ts (308 MB heap size)
 PASS  test/app-48.e2e-spec.ts (308 MB heap size)
 PASS  test/app-11.e2e-spec.ts (315 MB heap size)
 PASS  test/app-56.e2e-spec.ts (315 MB heap size)
 PASS  test/app-29.e2e-spec.ts (322 MB heap size)
 PASS  test/app-55.e2e-spec.ts (322 MB heap size)
 PASS  test/app-41.e2e-spec.ts (329 MB heap size)
 PASS  test/app-38.e2e-spec.ts (230 MB heap size)
 PASS  test/app-6.e2e-spec.ts (237 MB heap size)
 PASS  test/app-18.e2e-spec.ts (244 MB heap size)
 PASS  test/app-46.e2e-spec.ts (243 MB heap size)
 PASS  test/app-43.e2e-spec.ts (250 MB heap size)
```

</details>

**Comment by cramhead** [comment]
I'm using node 14 LTS with Nestjs 7 and see this problem.

**Comment by JVMartin** [comment]
@micalevisk If the contents of all 60 files is:
```
describe('test', () => {
  it('test', () => {
    expect(true).toBe(true);
  });
});
```

Then the heap is *guaranteed* to remain constant, because otherwise there is a fatal flaw in Jest itself, which cannot be the case because the entire community is constantly testing to make sure our tests are not leaky. We use articles like [this](https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html) and [this](https://making.close.com/posts/finding-the-cause-of-a-memory-leak-in-jest), which would not work if there were built-in leaks. There aren't.

Just to sanity check, I had a few of my coworkers run this on different machines - OSX, Ubuntu, RedHat, and there were no leaks on any of them until Nest was included.

**Comment by micalevisk** [comment]
@JVMartin right. Do you think those values I'm getting are constant? from 140 MB to 258 MB with 40 test suites with just that code `expect(true).toBe(true)`

Not sure if you've seen this Issue on their side: https://github.com/facebook/jest/issues/7874

**Comment by mickaelmesdocteurs** [comment]
I experienced the same problem, but I don't thing this is related to Nest.
Jest has many openned issues about that as @micalevisk mentionned.
The simplest reproductible repo I found is there https://github.com/facebook/jest/issues/10467 (https://github.com/Garethp/jest-memory-leak)
