### ISSUE TITLE
Improve Versioning to support alternative Media Type header formats

### ISSUE THREAD

**Issue by adworacz** [nestjs/nest#8441]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The current versioning support in NestJS is pretty good, but it's pretty rigid in some cases and makes some assumptions.

Specifically, when using Media Type for versioning, the current implementation assumes that the version uses a semi-colon delimiter with the version key after the media type, like so: `application/json;v=2`. [Reference](https://docs.nestjs.com/techniques/versioning#media-type-versioning-type)

To be honest, I've never seen this standard before.

In our case, we follow the [OpenAPI vendor mimetype standard](https://swagger.io/docs/specification/media-types/) aka [RFC4288 "Vendor Types"](https://datatracker.ietf.org/doc/html/rfc4288#section-3.2). As demonstrated in [this article](https://www.baeldung.com/rest-versioning), we use something like the following: `application/vnd.myresourcename.v2+json`.

This is not currently possible to do with the existing Media Type versioning support.

### Describe the solution you'd like

Being able to specify the version as a part of the vendor specific Media Type.

Obviously, this solution would need to account for any other code paths that may impact the Media Type (like things that might return simple strings/not JSON).

So this need might be two-fold - specifying a vendor-specific media type, and adding versioning to it accordingly. But I could very well be wrong here, interested to hear feedback from the devs.

### Teachability, documentation, adoption, migration strategy

Ideally, it would be as simple to configure as the following:
```
const app = await NestFactory.create(AppModule);
app.enableVersioning({
  type: VersioningType.MEDIA_TYPE,
  vendorSuffix: 'v',
  //or maybe
  mediaTypeTemplate: '{type}/vnd.{vendor-type}.{version}+{sub-type}'
});
await app.listen(3000);
```

### Option 1
And perhaps using the `@Header` annotation like so:
```
@Header('Content-Type', 'application/vnd.myresource+json')
@Version('2')
async myResource() {...}
```
This is brittle though.

### Option 2
Or this may be better implemented with users creating their own [custom decorators](https://docs.nestjs.com/custom-decorators#custom-route-decorators) to create something like:
```
@VendorResource('myresource')
@Version('2')
async myResource() {...}
```

### Option 3
Or maybe:
```
@MediaType(type='application', subtype='json', vendor='myresource')
@Version('2')
async myResource() {...}
```

### End result

All of which produces the following result:

```
Content-Type: application/vnd.myresource.v2+json
```

Along with supporting the following Accept request header, which allows clients to express their supported versions as a matter of content negotiation:
```
Accept: application/vnd.myresource.v1+json, application/vnd.myresource.v2+json
```

### What is the motivation / use case for changing the behavior?

Support for an alternative versioning specification using Media Types, which aligns with OpenAPI and certain industry practices.

**Comment by adworacz** [comment]
Following up on this, as I'm about to start the work needed to provided a custom function for version extraction.

Any pertinent details that can address the above questions?

**Comment by adworacz** [comment]
Just a status update - I have the code for this about 75% done. Still need to finish the Fastify adapter and write some tests. I think I found/fixed a potential bug in the Fastify adapter as well, as it wasn't handling version array's properly.

I'll post a PR once I finish, should be in the next day or two if things go well.

**Comment by adworacz** [comment]
I've created a beginning, WIP PR here: https://github.com/nestjs/nest/pull/8603

It does not currently have specific tests/documentation added yet, but I wanted to get feedback that I'm headed in the right direction before adding any more test/documentation at this time.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8603
