### ISSUE TITLE
Adding gRPC option to provide an packageDefinition option instead of providing .proto files

### ISSUE THREAD

**Issue by aaronschweig** [nestjs/nest#8457]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

During development with gRPC-Service (most of them not implemented using Nest, but other programming languages) the `.proto` files get compiled down using the `protoc` tool and language specific code gets generated. The common behaviour in other languages includes using the generated code to make clients or implement servers based on the protobuffers.

In NodeJS you get the option of either providing the `.proto` file directly and generate the needed PackageDefinitions during runtime to load them into the `@grpc/grpc-js` package, or to also statically generate the code without using any  `.proto` loader, so not needing any `*.proto` files in your repository.

The current implementation of the GRPC transport in NestJS does not allow to choose which method to use, because there is only the option to provide a specific `*.proto` file, which then gets picked up by the `@grpc/proto-loader` package.

It would be great to have both methods available as an end user

### Describe the solution you'd like

To get the expected behaviour describe above only minor changes would be needed inside the `nestjs/nest/packages/microservices/client/client-grpc.ts` GRPC-Client. 

An argument could be provided in the options object which would enable the user to pass an already present `packageDefinition` which then would skip the need to provide a `protoPath`.

The new `GrpcOptions` interface could look like this:

```diff
export interface GrpcOptions {
  transport?: Transport.GRPC;
  options: {
    interceptors?: Array<(options: any, nextCall: (options: any) => any) => any>;
    url?: string;
    maxSendMessageLength?: number;
    maxReceiveMessageLength?: number;
    maxMetadataSize?: number;
    keepalive?: {
      keepaliveTimeMs?: number;
      keepaliveTimeoutMs?: number;
      keepalivePermitWithoutCalls?: number;
      http2MaxPingsWithoutData?: number;
      http2MinTimeBetweenPingsMs?: number;
      http2MinPingIntervalWithoutDataMs?: number;
      http2MaxPingStrikes?: number;
    };
    channelOptions?: ChannelOptions;
    credentials?: any;
    protoPath: string | string[];
    package: string | string[];
+   packageDefinition: PackageDefinition;
    protoLoader?: string;
    loader?: {
      keepCase?: boolean;
      alternateCommentMode?: boolean;
      longs?: Function;
      enums?: Function;
      bytes?: Function;
      defaults?: boolean;
      arrays?: boolean;
      objects?: boolean;
      oneofs?: boolean;
      json?: boolean;
      includeDirs?: string[];
    };
  };
}
```

This new field could be mutually exclusive with the `protoPath` field. 

In the actual GRPC-Client only a few adoptions would be needed, namely conditionally loading the proto-loader package, and adjusting the `loadPackage()` function to respect the new option and directly pass the option to the `grpc.loadPackageDefinition` function.

As this would be an additional option it would not break the existing implementation and only provide another way of using gRPC within NestJS.

### Teachability, documentation, adoption, migration strategy

There would only be minor documentation updates needed, as it would only affect the specific gRPC portion.

### What is the motivation / use case for changing the behavior?

The motiviation results in my and my companies tries of migrating from an monolithic NestJS implementation into a gRPC based microservice architecture. The problem with gRPC is its bad dependency management for the proto files, but with using generated libraries it would be possible to integrate with NestJS nicely without having a monorepo or git submodules

**Comment by minh1611** [comment]
Hi @aaronschweig , I have just read your issue and you had a solution. I wonder could you give me the example code of create GRPC server in Nestjs with directly import ".ts" file instead of ".proto" file. This ".ts" file is generated from ".proto" file by protoc. I tried to search but can't find any. Here's my code, but it doesn't work. 

```
const app = await NestFactory.createMicroservice<MicroserviceOptions>(AppModule, {
    transport: Transport.GRPC,
    options: {
      package: 'tenant_pb',
      protoPath: '',
      packageDefinition: protoLoader.loadSync(__dirname + '/protobuf/tenant_pb/tenant_service.ts'),
    },
  });

 await app.listen();
```
Note: "tenant_service.ts" is the file generated from "tenant_service.proto" via protoc (in this case I use plugin from https://github.com/stephenh/ts-proto). The package name of "tenant_service.proto" is "tenant_pb"

Thank you!
