### ISSUE TITLE
Allow specyfing logger token to custom log initialization error.

### ISSUE THREAD

**Issue by Ginden** [nestjs/nest#8462]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Let's assume we have code like:

```
import { Logger } from 'nestjs-pino';
const app = await NestFactory.create(AppModule, {
  bufferLogs: true,
});
const logger = app.get(Logger);
app.useLogger(logger);
```

If error happens during initialization of any module required by `AppModule`, Nest.js will fallback to default logger, even if LoggerModule was initialized correctly.

 

### Describe the solution you'd like

I would like to have option to specify "use this logger as soon as it becomes available".

It can be implemented as some kind of magical object passed to `logger` option:

```ts
  const app = await NestFactory.create(AppModule, {
    bufferLogs: true,
    logger: injectLogger(Logger)
  });
```

I suppose hacky workaround can be used (like multi-stage initialization with `createApplicationContext` to create instance of logger before initialization of main app), but I didn't try to implement them.

### Teachability, documentation, adoption, migration strategy

It seems extremely simple for teachability, adaption and migration.

### What is the motivation / use case for changing the behavior?

I would like to log errors during initialization to Sentry.

**Comment by kamilmysliwiec** [comment]
There are no plans to add such a feature in the foreseeable future.
