### ISSUE TITLE
Can I use logging Interceptor or Middleware in service?

### ISSUE THREAD

**Issue by matiyem** [nestjs/nest#8471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I write global interceptor for logging.its work fine.but I need log in services classes with interceptor too.interceptor can't see services?
How can i solved my issue 

Thanks every body

### Minimum reproduction code

Wwwww

### Expected behavior

I need log in every layer conttoroller service and....
I should use interceptor or Middleware or other?
Please help me

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Packages versions

Winston for log

### Node.js version

10

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
