### ISSUE TITLE
ParseUUIDPipe ignores exceptionFactory when value is not a string

### ISSUE THREAD

**Issue by titivuk** [nestjs/nest#8472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When `ParseUUIDPipe` validates not a string value, it ignores `exceptionFactory`

### Minimum reproduction code

https://github.com/titivuk/nestjs-parse-uuid-pipe-issue

### Steps to reproduce

1. `npm i`
2. `npm run test`

### Expected behavior

`ParseUUIDPipe` always has to throw custom exception if it's provided

### Package

- [X] <code>@nestjs/common</code>

### NestJS version

8.1.2

### Packages versions

- `@nestjs/common`: "^8.0.0"
- `@nestjs/core`: "^8.0.0"
- `@nestjs/platform-express`: "^8.0.0"

### Node.js version

16.6.1

### In which operating systems have you tested?

- [X] Windows
- [X] Linux

### Other

PR to fix
https://github.com/nestjs/nest/pull/8459

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8459
