### ISSUE TITLE
Invalid Schema

### ISSUE THREAD

**Issue by devbanana** [nestjs/nest#8474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Not sure if I'm reporting this in the right place.

But in nest-cli.json I was trying to set up the `@nestjs/swagger` plugin. But when I include options to pass to the plugin, I get an error from PhpStorm that it's incompatible with the schema.

Here's my nest-cli.json:

```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/swagger",
        "options": {
          "introspectComments": true,
          "dtoFileNameSuffix": [
            ".command.ts",
            ".query.ts",
            ".view-model.ts",
            ".dto.ts"
          ]
        }
      }
    ]
  }
}

```

Here's the error:

`Incompatible types. Required: string. Actual: object.`

Basically it seems it's expecting `plugins` to only be an array of strings, not to accept an object.

### Minimum reproduction code

https://github.com/devbanana/uuid-server/blob/master/nest-cli.json

### Expected behavior

No error.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

8.1.2

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^1.0.2",
    "@nestjs/core": "^8.0.0",
    "@nestjs/cqrs": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/swagger": "^5.1.4",
    "bs58": "^4.0.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "crockford-base32": "^1.0.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.1.6",
    "uuid": "^8.3.2",
    "validator": "^13.6.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/bs58": "^4.0.1",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@types/uuid": "^8.3.1",
    "@types/validator": "^13.6.3",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^27.0.6",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },

```

### Node.js version

14.17.6

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be related to NestJS.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
