### ISSUE TITLE
feature() add AsyncLocalStorage module

### ISSUE THREAD

**Issue by joebowbeer** [nestjs/nest#8480]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

AsyncLocalStorage is an increasingly useful resource, and as such I think a NestJS module would be a welcome addition. It's use should be more performant than request-scoped providers for many applications.

Is there another location where this is being discussed? As far as I can tell, all issues and PR's on this topic have been closed for comment:

* #1407
* #4150
* #6012 <= _**See description of feature here**_

This makes it difficult to update or correct any of the information.

In particular, note that AsyncLocalStorage is for the most part STABLE:

https://nodejs.org/api/async_context.html#class-asynclocalstorage

@Papooch spent some time researching and testing and the result is this package:

https://github.com/Papooch/nestjs-cls

> It would be great if Nest provided some 'request hooks' so we could wrap the execution context of the whole request somehow instead of relying on a middleware or an 'enhancer' (though I don't know if that's even possible)

_Originally posted by @Papooch in https://github.com/nestjs/nest/issues/1407#issuecomment-942670644_

### Describe the solution you'd like

https://github.com/nestjs/nest/issues/6012#issue-773949212

### Teachability, documentation, adoption, migration strategy

https://github.com/nestjs/nest/issues/6012#issue-773949212

### What is the motivation / use case for changing the behavior?

https://github.com/nestjs/nest/issues/6012#issue-773949212

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/1407#issuecomment-944042478
