### ISSUE TITLE
SchemaDirectiveVisitor was removed in: @graphql-tools/utils

### ISSUE THREAD

**Issue by lukasholzer** [nestjs/nest#8481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using the snippet from the documentation about custom graphql schema directives:
https://docs.nestjs.com/graphql/directives#custom-directives

does not work anymore as `@graphql-tools/utils` has removed the `SchemaDirectiveVisitor`

![CleanShot 2021-11-01 at 12 43 51](https://user-images.githubusercontent.com/11156362/139666492-747df999-f4ce-4435-a4eb-b57dfe06d40c.png)

### Minimum reproduction code

https://github.com/nestjs/graphql/blob/master/tests/graphql-federation/posts-service/posts/upper.directive.ts

### Steps to reproduce

go to the tests and update graphql-tools to the latest version: `@graphql-tools/utils": "^8.5.1`

### Expected behavior

The example on the documentation should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

8.1.2

### Packages versions

```
    "@nestjs/common": "^8.1.2",
    "@nestjs/config": "^1.0.2",
    "@nestjs/core": "^8.1.2",
    "@nestjs/graphql": "^9.1.1",
    "@nestjs/mapped-types": "1.0.0",
    "@nestjs/microservices": "^8.1.2",
    "@nestjs/mongoose": "^9.0.1",
    "@nestjs/platform-fastify": "^8.1.2",
```

### Node.js version

16.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/139814491-5212230f-f9fe-4b55-93fe-a3ecc9964376.png)
