### ISSUE TITLE
APP_GUARD dependency key is a token instead of name

### ISSUE THREAD

**Issue by dyaacov** [nestjs/nest#849]
Hi All,
It worked since yesterday...

the following line cannot find the dependency:
`const authGuard: AuthGuard = app.select(ApplicationModule).get(APP_GUARD)`

looking at the mapped dependencies in _**nest-application-context.js**_, my APP_GUARD was saved as "pg9bq82wc5" 
![screen shot 2018-07-06 at 23 19 55](https://user-images.githubusercontent.com/3389108/42398745-af1f6916-8173-11e8-864f-409e37e9cac2.png)
instead of "APP_GUARD" (see object #6)

**Comment by autaut03** [comment]
It's a fix of #812
