### ISSUE TITLE
Unable to use context.log and contex.res for azure functions 

### ISSUE THREAD

**Issue by uttamnest** [nestjs/nest#8490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to use nestjs with azure functions. It works for successful request. 
In normal azure function without using nestjs I can log data with context.log() and also throw error in response context.res is used 

Sample code from azure site :
```
const domain = req.body.email.split("@")[1];
  const allowedDomains = ["gmail.com"];

  // Check that the domain of the email is from a specific other tenant
  if (!allowedDomains.includes(domain.toLowerCase())) {
    context.res = {
      body: {
        version: API_VERSION,
        action: "ShowBlockPage",
        userMessage:
          "You must have an account from a valid domain to register as an external user for " + allowedDomains.join(", or ") + ".",
        code: "SignUp-BlockByEmailDomain-0",
      },
    };
    context.log(context.res);
    return;
  }
```

 But in case of nestjs, if I throw any error like return response status 400, its not working. I tried `@Res` decorator but still not working.

How do I access context in controller so that I can log the data in azure functions console and also throw error for input validations. 

### Minimum reproduction code

NA

### Steps to reproduce

-

### Expected behavior

I want to use context.log and context.res so that I can throw error or log data in azure console

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/azure-func-http

### NestJS version

8.0.0

### Packages versions

- `"@nestjs/azure-func-http": "^0.7.0"`

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
