### ISSUE TITLE
Winston test issue with Jest framework

### ISSUE THREAD

**Issue by cheikhnadiouf** [nestjs/nest#8491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

THERE IS NO WORKING EXAMPLES OF WINSTON TEST IN JEST framework

### Minimum reproduction code

no one

### Steps to reproduce

install winston logger
and try a test

### Expected behavior

it should work lol

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

any version

### Packages versions

any versions

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
