### ISSUE TITLE
Problems with validation pipe

### ISSUE THREAD

**Issue by hiukky** [nestjs/nest#8494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The validation pipe transformation method is breaking in some validations and the reason is related to this piece of code that looking at it for a while doesn't seem to make much sense since the `plainToClass` method is fulfilling its role.

Reference
https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L108-L115

One of the first problems I noticed was the line https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L109
along with the test https://github.com/nestjs/nest/blob/master/packages/common/test/pipes/validation.pipe.spec.ts#L372-L383

It really should return an error lol, but here https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L109 we are trying to set the constructor property on an array, since it is not a primitive resulting in the following code

```
    {
      entity: [
        TestModelNoValidaton {
          prop1: 'value1',
          prop2: 'value2',
          prop3: 'value3'
        },
        constructor: [class TestModelNoValidaton]
      ]
    }
```

I believe that this is not the expected behavior, as the validation method is receiving an invalid value to be analyzed.

But the real problem was the fact that it's missing some metadata in validation because of that constructor definition.

I'm creating a utility to query dynamic queries, https://github.com/hiukky/class-toolkit/blob/develop/samples/query.sample.ts (DTO example), it works well following the transformation and validation with the validator and transformer.

In this case for example, the Prop decorator registers other decorators in a new prototype at validation time.

This works fine, but when integrating with my application I ran into this issue with current validation pipe.

### Minimum reproduction code

https://github.com/hiukky/class-toolkit/blob/develop/samples/query.sample.ts

### Expected behavior

https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L105-L115 is a solution that seems favorable to me, but I didn't get to analyze all possible cases to know where that will imply, but we have no problems in current tests.

The second option was to pass the entity constructor at https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L117 but this doesn't work in all cases because of line https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L109 assigning this to an Array for example.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.3

### Packages versions

"@nestjs/common": "^8.1.2"

### Node.js version

16.11.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a **minimum** reproduction repository.
