### ISSUE TITLE
how to use sourceRoot in nest-cli.json when i use test:e2e

### ISSUE THREAD

**Issue by zhonggithub** [nestjs/nest#8506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

 I set sourceRoot: src in next-cli.json , then use npm run test:e2e, the error happ like this: 
![image](https://user-images.githubusercontent.com/17545551/140031137-08e34bf3-5c26-4ffb-b1de-571987c9d985.png)
why npm run test:e2e not to parsing the next-cli.json

### Minimum reproduction code

https://user-images.githubusercontent.com/17545551/140031137-08e34bf3-5c26-4ffb-b1de-571987c9d985.png)

### Expected behavior

no error happing

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

"@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
