### ISSUE TITLE
get Execution Context in all components

### ISSUE THREAD

**Issue by hackboy** [nestjs/nest#851]
## I'm submitting a...
[ ] Feature request

## Current behavior

I don't find a way to get the Execution Context in components，it is useful when i want to get a component from the custome decorator

## Expected behavior

I want to get the Execution Context in every component，i think this can be done when the components scanner process

## What is the motivation / use case for changing the behavior?

for example ,when i want to get ConfigService from the decorator as below

import 'reflect-metadata'
import { ConfigService } from '../config/config.service';

export const Value = ():PropertyDecorator => {
    return (target:object,propertyKey:string|symbol)=>{
       //how can i get the ConfigService instance by the execution context，i think if the target is 
       // instance by the container has the context property,i can call target.context to get it
        console.log('-----target-------',target,propertyKey)
        Reflect.set(target,propertyKey,configService.get(propertyKey))
    }
}

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Not sure what this question is about. Could you explain it further?

**Comment by hackboy** [comment]
@kamilmysliwiec 
I'm sorry，what's my want is to get a provider instance in a decorator.
but i can not find a way to do that
I think nest can provide a property(for example app) on the target object to get the Execution Context，therefore i can get  a provider by call app.get()

i want this feature because i design a decorator,which add to a class property so they can bind to a value read from ConfigService

/**
the Value decorator
**/
import 'reflect-metadata'

export const Value = ():PropertyDecorator => {
    return (target:object,propertyKey:string|symbol)=>{
       const configService = //get configService some way
        console.log('-----target-------',target,propertyKey)
        Reflect.set(target,propertyKey,configService.get(propertyKey))
    }
}

/**
use the Value decorator
**/
import { Get, Controller, HttpException, HttpStatus, UseFilters, Param, Render, UseGuards } from '@nestjs/common';
import { AppService } from './app.service';
import {Value} from './decorators/value.decorator'

@Controller()
export class AppController {

  @Value()
  appId:string

  constructor(private readonly appService: AppService) { }

  @Get()
  @Render('index')
  root(){
    return {message:`${this.appId}`}
  }

}

**Comment by kamilmysliwiec** [comment]
The decorators are static. Hence, they don't have an access to the Nest container which is maintained dynamically underneath. What you can do instead, is to inject `ModulesContainer` or `ModuleRef` and then, access object property from within the decorator's body.
