### ISSUE TITLE
Search providers by glob pattern(DynamicProvider)

### ISSUE THREAD

**Issue by fjodor-rybakov** [nestjs/nest#8536]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have many similar classes that I want to instantiate automatically

### Describe the solution you'd like

I suggest adding a dynamic provider that will look for files with injectable classes.

```typescript
export declare type Provider<T = any> = Type<any> | ClassProvider<T> | ValueProvider<T> | FactoryProvider<T> | ExistingProvider<T> | DynamicProvider;


/**
 * Glob pattern by which files injectable classes will be searched.
 */
export type DynamicProvider = string;
```

### Teachability, documentation, adoption, migration strategy

Example:

```typescript
@Module({
  providers: ['**/*.animal.ts'] // Pattern will find classes: Cat, Dog, Hamster, because file names end in `.animal.ts`
})
export class AnimalModule {}
```

```typescript
/* cat.animal.ts */

@Injectable()
export class Cat {
}
```

```typescript
/* dog.animal.ts */

@Injectable()
export class Dog {
}
```

```typescript
/* hamster.animal.ts */

@Injectable()
export class Hamster {
}
```

### What is the motivation / use case for changing the behavior?

Creating each provider manually is a burden

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
