### ISSUE TITLE
[queues] No error thrown if redis connection is invalid, blocking the app for 1h

### ISSUE THREAD

**Issue by paulintrognon** [nestjs/nest#8552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using [queues](https://docs.nestjs.com/techniques/queues), if redis is misconfigured and cannot be reached, no error is ever thrown, blocking the process for 1 full hour, waiting for I-don't-know-what.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/26-queues

### Steps to reproduce

1. `npm i`
2. `npm start dev`
3. `curl -X POST http://localhost:3000/audio/transcode`
4. If you don't have redis set up, you get blocked for 1 full hour...

### Expected behavior

If redis connection is misconfigured, an error should be thrown, so that we know that something is wrong.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/bull

### Packages versions

- `@nestjs/bull`: 0.4.2
- `@nestjs/common`: 8.0.11
- `@nestjs/core`: 8.0.11

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/141095577-030c61fc-5f84-4571-a0af-db8b1355771b.png)

![image](https://user-images.githubusercontent.com/23244943/141095592-c2eb22c1-d1f7-4a36-be8b-af50af1472e7.png)
