### ISSUE TITLE
Nest can't resolve dependencies of the DeploymentFactory

### ISSUE THREAD

**Issue by alvipeo** [nestjs/nest#8555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Here's the repo - https://github.com/alvipeo/nestjs-di-issue.

when I run it with `npm run start:debug` I get the error:
> Nest can't resolve dependencies of the DeploymentFactory (?). Please make sure that the argument dependency at index [0] is available in the DeploymentsModule context

I've double checked MANY times and I have no idea what's wrong with it. Also, there is NO information whatsoever hinting what's wrong here even with `NEST_DEBUG` set!

1. Can you please tell me what is missing?
2. Can you please make it easier to fix?

### Minimum reproduction code

https://github.com/alvipeo/nestjs-di-issue

### Expected behavior

It should work as all the dependencies are provided.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.0

### Packages versions

see repo

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Based on the error, you have a circular file import. Not necessarily a circular dependency between the providers, but the files themselves are circular. This is pretty common with barrel files if you aren't careful with them. In this case, I found that your `src/deployments/commands/models/deployment.factory.ts` imports `src/deployments/db` which has an import back to `src/deploymetns/commands/models` which imports `src/deployments/commands/models/deployment.factory.ts`. Hence, the circular  import. For further help, please visit our [Discord](https://discord.gg/nestjs)

**Comment by alvipeo** [comment]
Can you please error it out? So people do not go in circles.

Overall, this is my nest project, and I've been working with angular since v.2 (nxrx, etc). So far so good, but such things are really frustrating.

**Comment by jmcdo29** [comment]
Not really sure what you want us to be able to do. The dependency comes in as `undefined` because of how Typescript resolves circular dependencies, so all we can do is say we cannot resolve `dependency`. We could make another mention in the [Common Errors page](https://docs.nestjs.com/faq/common-errors#circular-dependency-error) warning about this possibility.

**Comment by alvipeo** [comment]
@jmcdo29 ok, I thought there was a way of telling where it bumps into this with `NEST_DEBUG`, or at least tell that there IS circular dependence somewhere.

**Comment by jmcdo29** [comment]
Looks like we _may_ be able to move the log around a little bit, but we won't be able to give a more meaningful error message. It would result in a similar `Resolving dependency undefined in the DeploymentsFactory provider`. Do you think that would be helpful at all?

**Comment by alvipeo** [comment]
I'd say if you add __*(this might be a circular dependency issue)*__ would be really helpful.

**Comment by jmcdo29** [comment]
I think the best thing we can do is update the documentation at the moment. We could add a log as well, or possibly update the error message being thrown, but I have a feeling that's going to affect more than we anticipate and could cause some unforeseen issues (just being on the safe side here). While it is an error that should stop the server from starting, you never know who's doing what with these error messages, and changes to them could throw people off (for whatever reason). I'll make a PR for the log and let Kamil be the deciding factor on it, and get a PR for the docs up soon

**Comment by alvipeo** [comment]
the problem with this particular issue that first I get to the docs and did not find any info on *circular dependencies* related to that particular error. then I found `NEST_DEBUG` and that didn't help much too. I tried many different things and nothing worked.

so, the only help I got here now. what if someone else has this problem, or I forget about this (which I doubt! :) ) later?

**Comment by jmcdo29** [comment]
> the problem with this particular issue that first I get to the docs and did not find any info on circular dependencies related to that particular error.

Which is why I've [made a PR to update the docs](https://github.com/nestjs/docs.nestjs.com/pull/2103). Like I said earlier, I don't really think the `NEST_DEBUG` log would help in this case, because it's just going to say `Resolving dependency undefined in the DeploymentsFactory provider`, which will still be confusing. I also added #8556 to see if Kamil wants to write a warning before the main error message or not.

**Comment by jmcdo29** [comment]
Now please, for further  discussion, please use our [Discord](https://discord.gg/nestjs) as I've mentioned before.
