### ISSUE TITLE
risk associated with multer dependency in @nestjs/platform-express

### ISSUE THREAD

**Issue by recaph** [nestjs/nest#8557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Scans on our projects, tagged the project as vulnerable due to usage of very old dependency. Almost all violations were coming from our use of @nestjs/platform-express package. After further analysis, found that multer has a v2 (rc) version which cleared these violations

My request is - is it possible to update the multer dependency in @nestjs/platform-express to latest one.

### Minimum reproduction code

N/A

### Steps to reproduce

Scans on our projects, tagged the project as vulnerable due to usage of very old dependency. Almost all violations were coming from our use of @nestjs/platform-express package. After further analysis, found that multer has a v2 (rc) version which cleared these violations

My request is - is it possible to update the multer dependency in   to latest one.

### Expected behavior

replace multer/1.4.3 with multer/2.0.0-rc.3 or higher in @nestjs/platform-express package

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.11

### Packages versions

"dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  }

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

![image](https://user-images.githubusercontent.com/704289/141209343-2e6aa032-ff62-4533-83c3-a9dfa13bc3cc.png)
![image](https://user-images.githubusercontent.com/704289/141209230-b01250d7-4ebc-408e-8467-bd7adbd93f3b.png)

**Comment by kamilmysliwiec** [comment]
Renovate & dependabot take care of auto-upgrading all deps
