### ISSUE TITLE
Support union type in swagger plugin

### ISSUE THREAD

**Issue by RageYL** [nestjs/nest#8565]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, the swagger plugin is unable to to annotate union types properties with `@ApiProperty({ enum: ... })`, it only works with enum.

Prisma ORM generates union type instead of enum which forces us to annotate all Dto.

### Describe the solution you'd like

Detect union types and generate the corresponding `@ApiProperty({ enum: ... })`

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

Reduce boilerplate and maintainability.

**Comment by jmcdo29** [comment]
1) this should have been opened in the nestjs/swagger repository

2) would you like to open a PR for this?

**Comment by RageYL** [comment]
I would love to contribute, but wasn't able to understand everything when I skimmed through. Do you have some guidance to make my investigation easier?

I didn't notice I was in the wrong repo, I'll reopen it in the swagger repository once I have a possible fix.

**Comment by RageYL** [comment]
Opened https://github.com/nestjs/swagger/issues/1665. Closing.
