### ISSUE TITLE
Annotation to change model/class name in OpenApi to hide 'Dto' suffix in swager documentation

### ISSUE THREAD

**Issue by MarcosRava** [nestjs/nest#8574]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to choose model name in OpenApi generated json

### Describe the solution you'd like

A class annotation to choose the schema name

### Teachability, documentation, adoption, migration strategy

Eg.
```js
@ApiSchema({ name: 'User' })
export class UserDto {
}
```

### What is the motivation / use case for changing the behavior?

No one need to know about Dto classes or any other class name suffix in swagger docs
this can confuse API consumers.

**Comment by micalevisk** [comment]
this was implemented already here: https://github.com/nestjs/swagger/pull/983 btw
