### ISSUE TITLE
the lib option in tsconfig does not work in new project created by nest cli v8

### ISSUE THREAD

**Issue by liaoliaots** [nestjs/nest#8584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I created a new project by `@nestjs/cli` and added the `lib` option of `tsconfig.json` with the value `["es2017"]`, then used the `promise.allSettled()` of **es2020** in my code, but **ts(2550)** error **did not** prompt, and the tsc command compiles properly.

vs code should prompt this error:
```
Property 'allSettled' does not exist on type 'PromiseConstructor'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.ts(2550)
```

If I use `npm init -y` to create a minimal project, then install the `typescript` package and copy tsconfig.json to this project, the error prompts normally:
<img width="686" alt="屏幕截图 2021-11-15 162138" src="https://user-images.githubusercontent.com/27341089/141746846-a872c1a7-e918-4840-a053-59dc2d630d35.png">

### Minimum reproduction code

https://github.com/liaoliaots/my-app

### Steps to reproduce

1. `nest new my-app`
2. add `lib` option to file `tsconfig.json` with **["es2017"]**
3. add code to main.ts: `const p = Promise.allSettled([]);`
4. **vs code does not prompt ts(2550) error**

### Expected behavior

vs code should prompt ts(2550) error

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^8.0.0

### Packages versions

- `@nestjs/common`: ^8.0.0
- `@nestjs/core`: ^8.0.0
- `@types/node`: ^16.0.0

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

- npm: 8.1.3
- `@nestjs/cli`: 8.1.4 (global)
- `@nestjs/schematics`: 8.0.4 (global)
- OS1: Windows 10 Pro 21H1
- OS2: Kubuntu 20.04 LTS

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
