### ISSUE TITLE
Breaking change in registering middleware since patch 8.0.11 (express)

### ISSUE THREAD

**Issue by Papooch** [nestjs/nest#8585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Say I have this route in my application: `/users/:id/details`, when I register a middleware on the route `/users`, then I expect it to run for all routes begining with `/users` (like `/users/John/details`).

Since `@nestjs/platform-express` v8.0.11, registering a middleware on route `/users`, causes it to be triggered *only* for that route.

### Minimum reproduction code

https://github.com/Papooch/nestjs-issue-8_0_10-8_0_11

### Correct behavior
0) Clone the repo
1) Install dependencies and run
```bash
npm i

npm run start
```
2) Visit http://localhost:3000/users/John/details in your browser.
3) There should be 2 logs from 2 middlewares in the console:
```
[Nest] ... DEBUG [LoggingMiddleware] Route: /users/john/details
[Nest] ... DEBUG [TestMiddleware] Route: /users/john/details
```

### Incorrect behavior
4) Stop the server and install the next patch version (or `@latest`)
```
npm i @nestjs/core@8.0.11 @nestjs/common@8.0.11 @nestjs/platform-express@8.0.11

npm run start
```
5) Visit http://localhost:3000/users/John/details in your browser.
6) Observe that now the `TestMiddleware` is not being hit and the console only shows one log entry:
```
[Nest] ... DEBUG [LoggingMiddleware] Route: /users/john/details
```

### Expected behavior

Registering a middleware for the route `/users` should cause it to be triggered for all child routes.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.11

### Packages versions

- `@nestjs/core`: ^8.0.11
- `@nestjs/comon`: ^8.0.11
- `@nestjs/platform-express`: ^8.0.11

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

While reproducing this issue, I found out that the expected behavior can be achieved by registering the middleware for `/users/*` instead of `/users`, but that is different to how you could register the same express route with `app.use('/users', ...)`.

All in all, it is still a breaking change and I think it should not have been introduced in a **patch** version. It caused a *lot* of headache for us while tracking it down :(

**Comment by kamilmysliwiec** [comment]
> when I register a middleware on the route /users, then I expect it to run for all routes begining with /users (like /users/John/details).

This was never supposed to work this way in v8. We introduced a regression in 8.0.5 that we fixed in 8.0.11. that's the expected behavior.

Apologies for the confusion! 🙏
