### ISSUE TITLE
Add configuration phase before http/rpc/ws servers launched

### ISSUE THREAD

**Issue by artaommahe** [nestjs/nest#86]
There is a case when microservice should get/request some configuration (or load initial data from db to memory storage) from separate config service before his servers( http/rpc/ws) will be launched.
Would be cool to have an opportunity to delay `nest` servers launch providing some function that returns Observable. This function should has access to app services and http/rpc requests to get/load initial data.
Also there is related issue - what if nest servers config (e.x. launch ports) should be requested from separate config service (http/rpc request). Currently it requires non-framework code that would wrap `nest` launch before configs loaded.

**Comment by kamilmysliwiec** [comment]
Hi @artaommahe,

Take a look - https://docs.nestjs.com/lazy-microservice-client.html. Is it something what are you looking for?

**Comment by artaommahe** [comment]
@kamilmysliwiec mmm i need to defer any server (http/ws) launch before init done. App should not be publicly available until it loaded all initial data/configuration params.

**Comment by cojack** [comment]
@artaommahe then don't start server untill what you have to do, will be done.

**Comment by FranciZ** [comment]
@artaommahe 
Did you figure anything out? Have been looking at the various aspects of initialisation and have yet to figure this one out. 

@kamilmysliwiec
It's pretty essential to be able to defer server startup until all outside dependencies like database connections and third party API integrations have been established. Is there any way to achieve this at the moment?

**Comment by artaommahe** [comment]
@FranciZ nope, waiting for nest implementation )

**Comment by cojack** [comment]
@artaommahe will async `onModuleInit` functions cover your case?

https://docs.nestjs.com/lifecycle-events.html

**Comment by artaommahe** [comment]
@cojack it fires after servers init and does not delay microservice (his servers) starting. I cant allow microservice to be publicly available until it requested environment configs from another microservice (with important config data) and connected to database

**Comment by cojack** [comment]
@artaommahe I feel the same needs, and I would like to help in this case (because I miss them too) and thinking about the solution for this. Do you have any proposal of how the API, Interfaces of this might looks like for you? It might be a good start to collect a requirements and then start to improve the **nest** ;)

**Comment by artaommahe** [comment]
@cojack mb smth like `onModuleInit` in module constructor that returns observable and delays application bootstrap (servers run). I need to inject any service here, have a possibility to make RPC calls (RPC client should be available in servers) or WS requests (if someone use websocket for cross-services communication).
Hm, looks like servers (at least WS) should be available here but dont available from outside for public requests? Becoming more complicated )

**Comment by cojack** [comment]
@artaommahe so I guess we're looking for async component initialization callback. Then the case we have, when fire this?

1. After module init, 
2. After all of the modules init (deps resolution [@shared()])? 

So, then we will add a special function, similar to the `onModuleInit` but fe like in angular and his components `OnInit`?

I would like to (receive / get) more suggestions from you and start discussing this subject to have a clear path of requirements. So please submit your suggestions. This concerns all of you.

**Comment by cojack** [comment]
@artaommahe please check PR

**Comment by artaommahe** [comment]
@cojack `setupModules()` is called after `await this.callInitHook();` and due to do this
```ts
    public setupModules() {
        SocketModule.setup(this.container, this.config);
        MiddlewaresModule.setup(this.container, this.config);
        MicroservicesModule.setupClients(this.container);
    }
```
in `onModuleInit` RPC clients and WS calls will be unavailable

**Comment by cojack** [comment]
@artaommahe wasn't this expose RPC and WS on the world before the `onModuleInit`? I have to check this, fell free to update the commit/pr.

**Comment by cojack** [comment]
@artaommahe It expose the websocket to the world before rest of app is ready, so I don't think it's a good idea to move them after the `setupModules` call. Without it it won't fit your requirement?

**Comment by kamilmysliwiec** [comment]
Hey guys,
In the nearest release it'd be possible to create an **async** components (factories & values). All components, which depends on async components, would be also async, so you can use them as a some kind of configuration phase. 

```typescript
{
     provide: 'AsyncDatabaseConnection',
     useFactory: async (...args): Promise<any> => {

     },
     inject: [...]
},
```

Those async components are just promises, which have to be resolved before http/rpc/ws servers launch and may be injected into another components.

**Comment by kamilmysliwiec** [comment]
Hi @artaommahe,
A little bit more about *async components* is available [here](http://www.docs.nestjs.com/advanced/async-components)

**Comment by bradleyayers** [comment]
@kamilmysliwiec that link seems broken now

**Comment by kamilmysliwiec** [comment]
Update https://docs.nestjs.com/fundamentals/async-components ^
