### ISSUE TITLE
New hooks - beforeRequest, onRequest, onRequestDestroy, onRequestDestroyed 

### ISSUE THREAD

**Issue by Mitch-i** [nestjs/nest#8604]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

New hooks - beforeRequest, onRequest, onRequestDestroy, onRequestDestroyed 

### Describe the solution you'd like

Add these hooks

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

-

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
