### ISSUE TITLE
E2E API Test fails with missing dependency

### ISSUE THREAD

**Issue by sn0wbi** [nestjs/nest#8605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I used nestjs to build an API to lint OpenAPI Specs with the Spectral-Core SDK from @stoplight/spectral-core.

All works fine so far, but when I try to implement e2e tests for the /lintings API, I do get the following error:

` FAIL  test/lintings-e2e-spec.ts
  ● Test suite failed to run

    Cannot find module 'nimma/legacy' from '../node_modules/@stoplight/spectral-core/dist/runner/runner.js'

    Require stack:
      /Users/stelzers/dev/github/nestjs-speactral-api-linting/node_modules/@stoplight/spectral-core/dist/runner/runner.js
      /Users/stelzers/dev/github/nestjs-speactral-api-linting/node_modules/@stoplight/spectral-core/dist/runner/index.js
      /Users/stelzers/dev/github/nestjs-speactral-api-linting/node_modules/@stoplight/spectral-core/dist/spectral.js
      /Users/stelzers/dev/github/nestjs-speactral-api-linting/node_modules/@stoplight/spectral-core/dist/index.js
      /Users/stelzers/dev/github/nestjs-speactral-api-linting/src/lintings/lintings.service.ts
      /Users/stelzers/dev/github/nestjs-speactral-api-linting/src/lintings/lintings.controller.ts
      /Users/stelzers/dev/github/nestjs-speactral-api-linting/src/lintings/lintings.module.ts
      lintings-e2e-spec.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (../node_modules/@stoplight/spectral-core/src/runner/runner.ts:9:1)`

Mentioned files in the stack trace can be found in the public git repo.

### Minimum reproduction code

https://github.com/sn0wbi/nestjs-speactral-api-linting

### Steps to reproduce

1. npm install
2. npm run test:e2e

### Expected behavior

Dependency should work in e2e test.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### NestJS version

^8.0.0

### Packages versions

{
  "name": "api-linting",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "postbuild": "cp src/spectral.yml dist/spectral.yml",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "prestart:dev": "mkdir -p dist && cp src/spectral.yml dist/spectral.yml",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "prestart:hmr": "mkdir -p dist && cp src/spectral.yml dist/spectral.yml && cp src/spectral.js dist/spectral.js",
    "start:hmr": "nest build --webpack --webpackPath webpack-hmr.config.js --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "npm run build && jest --config ./test/jest-e2e.json",
    "copy-assets": "cp -rv src/spectral.yml dist/spectral.yml"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^1.1.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/swagger": "^5.1.4",
    "@stoplight/spectral-core": "^1.6.1",
    "@stoplight/spectral-ruleset-migrator": "^1.5.2",
    "@stoplight/spectral-rulesets": "^1.3.0",
    "class-validator": "^0.13.1",
    "compression": "^1.7.4",
    "dotenv": "^10.0.0",
    "express-basic-auth": "^1.2.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.1.6"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^27.0.6",
    "prettier": "^2.3.2",
    "run-script-webpack-plugin": "0.0.11",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5",
    "webpack": "^5.63.0",
    "webpack-node-externals": "^3.0.0"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

### Node.js version

14.17.5

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
