### ISSUE TITLE
An exception looses its type when an exception filter is imported from another library and become Error

### ISSUE THREAD

**Issue by PetrShchukin** [nestjs/nest#8617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I import a filter from another library the filter doesn't work unless it's "all catch" filter, as exceptions loose their type.
I have a filter which looks like this:
```
@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    const status = exception.getStatus();
    logger.error(exception);

    response.status(status).json({
      statusCode: status,
      timestamp: new Date().toISOString(),
      path: request.url,
      message: exception.message,
    });
  }
}
````
I throw a HttpException and it works perfectly when I import a local file. When I move this filter to a library and import it, it doesn't work and the exception is caught by the Error filter. The reason why is that "exception" variable looses its type and become a general Error. In a library I do not have any modules for filters I just export the classes.

### Expected behavior

Exceptions should persist their types regardless of exception filters.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.6

### Packages versions

    "@nestjs/cli": "8.1.1",
    "@nestjs/common": "8.0.6",
    "@nestjs/config": "1.0.1",
    "@nestjs/core": "8.0.6",
    "@nestjs/jwt": "8.0.0",
    "@nestjs/passport": "8.0.1",
    "@nestjs/platform-express": "8.0.6",
    "@nestjs/swagger": "5.1.0",
    "@nestjs/terminus": "8.0.0",
    "@nestjs/typeorm": "8.0.2",

### Node.js version

14.15.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
> The reason why is that "exception" variable looses its type and become a general Error

I don't think this is the issue.

To catch exceptions with `@Catch(Foo)`, Nestjs will do search for the first exception when `exception instanceof Foo` to find the exception filter. See:

https://github.com/nestjs/nest/blob/99ee3fd99341bcddfa408d1604050a9571b19bc9/packages/core/exceptions/exceptions-handler.ts#L32-L33

thus if your exception filter lives in another nodejs package, you'll need to make sure that `Foo` (from the example I give above) is exported from the same nodejs **module**

---

As you didn't provide an repo reproducing this, I'm not sure if I understood your issue.

**Comment by PetrShchukin** [comment]
Hi, but that's the thing that exception has a type of Error. In my case Foo is HttpException it's in '@nestjs/common' package. There's not much code honestly, here are
main.ts
````
app.useGlobalFilters(
  new HttpExceptionFilter(),
  new AllExceptionFilter(httpAdapterHost),
);
````
controller
````
@Get('/test')
test() {
  throw new BadRequestException();
}
````
and in all AllExceptionFilter
````
    console.log('HttpException?', exception instanceof HttpException);
    console.log('Error?', exception instanceof Error);
````
gives me HttpException? false and Error? true

And it works if I create a file in my main project and import it, but once it's in different package (to test I use npm link), and when I import it like `import { HttpExceptionFilter, StandardExceptionFilter } from '@crossreg/core';` it stops working.

**Comment by micalevisk** [comment]
basically, this is due to the following Nodejs behavior:

![image_2021-09-27_15-19-40](https://user-images.githubusercontent.com/13461315/142256942-40fe4d64-8627-4dc8-a534-5e50ffb0e9ee.png)

you just need to make sure that `@nestjs/common` imported in your exception filter is not nested under `your_exception_filter_package/node_modules/@nestjs/common`

**Comment by PetrShchukin** [comment]
That makes sense, thanks! 
Just for testing in the main project controller `import { HttpException } from '@crossreg/core/node_modules/@nestjs/common';` works. Unfortunately adding peerDependencies didn't help. I added this into package.json of the library 
````
  "peerDependencies": {
    "@nestjs/common": "8.0.6"
  }
````
tried even with all nestjs packages, still no use. I'm wondering if it has something to do with ``npm link``

**Comment by micalevisk** [comment]
when you install that package that has the `peerDependencies` entry, does `@nestjs/common` exists under the `node_modules` of that package? Also, you drop the `@nestjs/common` from `dependencies`, right?

could be an issue/limitation with `npm link`. For Yarn you can use this utility: https://github.com/wclr/yalc

**Comment by PetrShchukin** [comment]
Dropping `@nestjs/common` from dependencies results in build failing. But I think it works now.
- added a peer dependency
- manually droped the nestjs folder from node_modules
- npm install & npm link

and now it seems to be working. Thanks a million, will close the issue!

**Comment by micalevisk** [comment]
> build failing

I guess you must add it to `devDependencies` list
