### ISSUE TITLE
WebSocket writes to log with each client connection

### ISSUE THREAD

**Issue by brettbatie** [nestjs/nest#8618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a client connects to a WebSocket a message like the following is displayed in the logs.

```
Subscribe SocketGateway. method to message message.
```

In my case, the client is a frontend website. Each time a user refreshes their browser or loads the page for the first time I see this message 5 times (since I have 5 messages that the client subscribes to). This can make the logs very noisy for a high-traffic website. 

I suggest we revert the following commit (https://github.com/nestjs/nest/commit/0effa64d3e3e3859eab19af5914bb8b08d48f279) that started this behavior.

@jmcdo29 

### Minimum reproduction code

https://github.com/brettbatie/nest-websocket-verbose-logging

### Steps to reproduce

yarn test

### Expected behavior

The 3rd test (titled: "should not log on each socket connection") should succeed but it fails. The test checks if the message **Subscribe SocketGateway. method to message message.** was logged when a client connects to the socket.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.1

### Packages versions

  "dependencies": {
    "@nestjs/common": "^8.2.1",
    "@nestjs/core": "^8.2.1",
    "@nestjs/platform-express": "^8.2.1",
    "@nestjs/platform-socket.io": "^8.2.1",
    "@nestjs/websockets": "^8.2.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.4.0",
    "socket.io-client": "^4.3.2"
  },

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Oh that's a leftover! This was supposed to be removed as we added these logs upon app bootstrap instead.

Thanks for reporting this issue. Fixed in 8.2.2
