### ISSUE TITLE
Grpc: CLOSE_WAIT

### ISSUE THREAD

**Issue by zuohuadong** [nestjs/nest#862]
Nestjs :5.0
Linux: ubuntu 16.04
docker: k8s 1.9   & alpine 3.7
node: 10.5.0
Grpc: 1.12.4

![_20180711150514](https://user-images.githubusercontent.com/11203929/42555752-e5a0dde8-851b-11e8-8eae-ebe94d83f0c6.jpg)

```
@Client({
        transport: Transport.GRPC,
        options: {
            url: ENV_CONFIG.pm_rpc_host + ":" + ENV_CONFIG.pm_rpc_port,
            package: "vfair.pm",
            protoPath: join(__dirname, "./protobufs/vfair.pm.proto")
        }
    })
    public readonly pmServiceClient: ClientGrpc;
```

A large number of TCP connections are generated in use, blocking new connections.

**Comment by kamilmysliwiec** [comment]
That looks quite familiar: https://github.com/grpc/grpc/issues/15990

**Comment by zuohuadong** [comment]
@kamilmysliwiec 
You should be able to close the channel with client.channel.close() or client._channel.close().

But it seems that nest has not been seen to offer similar.

**Comment by kamilmysliwiec** [comment]
You can now get an underlying gRPC client using `getClientByServiceName()` method
