### ISSUE TITLE
Shouldn't there be any way to get the current Request from different Scope then Request

### ISSUE THREAD

**Issue by mathis-m** [nestjs/nest#8625]
# HttpContextAccessor
Maybe this is not an issue as mention before. But I think there are several reasons why this can become benifitial and increase code quality!

## Original
It's not an issue. You can't use `get()` to retrieve request-scoped instances + you can't inject request-scoped instances to singleton, statically scoped services.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/2861#issuecomment-527140242_

## Current Behavior
1. As developer I am interessted to less code where possible.
2. I have to pass Request from controler down the chain of services via method arguments.
3. Or I have to make all services request scoped!

## Accpected Behavior.
1. I would like to have a mechanism to access the current Request in any other scope.
2. I know this principal from asp.net core, see [Implementation of HttpContextAccessor](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/HttpContextAccessor.cs)

@kamilmysliwiec
Can you provide any guidiance for best practice in Nest.JS, or is there any way to implement a HttpContextAccessor in some way like in .net core.

Thanks for the great framework and all you work!

**Comment by micalevisk** [comment]
what about https://github.com/Papooch/nestjs-cls

**Comment by mathis-m** [comment]
Thanks gonna try this!

**Comment by datnm2** [comment]
any feedback when trying https://github.com/Papooch/nestjs-cls
2023 I have the same concern
