### ISSUE TITLE
ValidationPipe causes TypeError when building with Webpack in production mode

### ISSUE THREAD

**Issue by Fry98** [nestjs/nest#8639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you are running your server bundled by Webpack with mode set to "production" and your controller's arguments fail validation (using `class-validator` decorators), it causes the server to throw this error:
```
TypeError: Cannot read properties of null (reading 'join')
    at initMessage (C:\Users\filip\Desktop\JS\nest-repro\dist\main.js:2:23661)
    at new l (C:\Users\filip\Desktop\JS\nest-repro\dist\main.js:2:23386)
    at new i (C:\Users\filip\Desktop\JS\nest-repro\dist\main.js:2:21469)
    at f.exceptionFactory (C:\Users\filip\Desktop\JS\nest-repro\dist\main.js:2:46817)
    at f.transform (C:\Users\filip\Desktop\JS\nest-repro\dist\main.js:2:46490)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\filip\Desktop\JS\nest-repro\dist\main.js:2:167096
    at async Promise.all (index 0)
    at async C:\Users\filip\Desktop\JS\nest-repro\dist\main.js:2:166961
    at async C:\Users\filip\Desktop\JS\nest-repro\dist\main.js:2:164689
```

As a result of that, the reponse sent to the client is **500 Internal Server Error** instead of the regular **400 Bad Request**.

The location where this error gets initially thrown is line 55 of the file `packages/common/exceptions/http.exception.ts`.

### Minimum reproduction code

https://github.com/Fry98/nest-repro

### Steps to reproduce

1. `yarn`
2. `yarn prod:start`
3. Visit `http://localhost:3000/test?test=qwe`
4. The server returns **500 Internal Server Error** instead of the expected **400 Bad Request** and you can see the server logged a TypeError in your terminal
5. You can also try running `yarn dev:start` to bundle and run the server in development mode. This works as desired. *(Bundling with mode set to "none" also works without an issue.)*

### Expected behavior

The server should behave the same as it does when running unbundled or bundled in development mode.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

webpack

### NestJS version

8.2.2

### Packages versions

    "@nestjs/cli": "^8.0.0",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/node": "^16.0.0",
    "class-transformer": "<=0.4.0",
    "class-validator": "^0.13.2",
    "cross-env": "^7.0.3",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "source-map-support": "^0.5.20",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This is most likely an issue of webpack minifying and bundling the code all together. In the `development` mode everything keeps proper class names. I'll take a brief look into it, but generally we don't suggest letting webpack minify and uglify the code, as it doesn't bring much value in a node environment.

**Comment by Fry98** [comment]
@jmcdo29 Thanks for the advice! 👍
Adding this to the config fixed it:
```
optimization: {
  minimizer: [new TerserPlugin({
    terserOptions: {
      keep_classnames: true
    }
  })]
},
```

&nbsp;

The only reason I'm even trying to bundle the server is because I'm deploying it in AWS Lambda and the NestJS FAQ section on [Serverless](https://docs.nestjs.com/faq/serverless) recommends it for performance reasons. Might be a good idea to mention this in there to avoid other people getting confused.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to the docs with this hint?

**Comment by Fry98** [comment]
@kamilmysliwiec Created the PR (https://github.com/nestjs/docs.nestjs.com/pull/2118). Not sure how great my english is but hopefully it won't require any too drastic changes.
