### ISSUE TITLE
Official Vite support

### ISSUE THREAD

**Issue by calebeaires** [nestjs/nest#8669]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not directly related to: there are some plugins that can lead Nest to Vite but after try using some issues came out.

### Describe the solution you'd like

Vite uses esbuild

### Teachability, documentation, adoption, migration strategy

when the user create a Nest project, cli will give an option to choose Vite as the main builder.

### What is the motivation / use case for changing the behavior?

Vite is fast and makes the development faster.

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest-cli/issues/731

TL:DR; We don't plan to currently add in new compilers, but you're welcome to use what you want for building and transpiling your code.

**Comment by talha-asad** [comment]
No wonder not alot of people use nestjs and most of your courses are preorder
