### ISSUE TITLE
Update dependency class-transformer to v0.5.0

### ISSUE THREAD

**Issue by rbaumi** [nestjs/nest#8670]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Braking changes from v0.4.1: renamed `classToPlain` -> `instanceToPlain`.  

classToPlain is used in couple of places (fx. https://github.com/nestjs/nest/blob/21d5b6acbc3e1204f14b34e34d852d20fd12110b/packages/common/pipes/validation.pipe.ts#L148).

### Describe the solution you'd like

Updated dep.

### Teachability, documentation, adoption, migration strategy

none

### What is the motivation / use case for changing the behavior?

up to date deps.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/8637
