### ISSUE TITLE
Adding an Array of options(host & port) To ClientProxyFactory.create()

### ISSUE THREAD

**Issue by Mellywins** [nestjs/nest#8671]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm having a use case where the same event emitted by an API Gateway has to be consumed by a Query MicrosService(for cqrs), and a synchronisation MS between Elasticsearch and Mongodb.
I tried subscribing to the same eventpattern i already used to execute the querries on mongo, but I dont think it's possible with the way Client Proxy providers are configured. You'd need a different provider I guess. I'd love to have more input on this topic.
The general goal is to use the same event emission in multiple Subscribing Microservices.

### Describe the solution you'd like

It would look something like this:
`
providers: [
    AppService,
    {
      provide: 'WRITE_USER_SERVICE',
      useFactory: () =>
        ClientProxyFactory.create({
          transport: Transport.TCP,
          options: [
          {
            host: 'write_ms',
            port: 3000,
          },
          {
            host: 'sync_ms',
            port: 3001,
          },
          ]
                  }),
    },
`

### Teachability, documentation, adoption, migration strategy

A new hint could be added:
***
HINT
You can register multiple hosts per ClientProxy, giving them the ability to simultaneously listen to the same event emitted by that client.

### What is the motivation / use case for changing the behavior?

Semantically speaking, One event might have several implications on different parts of the microservice network, Having a common providers that proxies all of those microservices to emit semantically linked events that they should all react to makes more sense.

**Comment by kamilmysliwiec** [comment]
What you proposed is not about `ClientProxyFactory#create` taking multiple arguments but rather allowing factories to return multi providers. This feature has been discussed in the past and there're no plans to implement it in the foreseeable future.
