### ISSUE TITLE
Nestjs official Doc's to use with in Nextjs

### ISSUE THREAD

**Issue by tahir-jamil** [nestjs/nest#8692]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I recently move from angular frontend to node backend using nestjs and i am in love with nestjs so easy and supporting environment 
But when I study nextjs it provides both frontend and backend while nestjs is backend only 

I don't want to leave nestjs powers for fast and flexible coding but at the same time i want to use all features of nextjs

Both frameworks are doing great work i feel if nextjs and nestjs will work together they can move web development on a larger new scale with awesome cli support and most advanced ways to develop a full stack application 

My simple question is 
Do nestjs provide some support with nextjs officially?

Please 🙏 guide me about that 
Thanks in advanced 

### Describe the solution you'd like

One cli on top of nest cli and nect cli 
One directory for both backend and frontend 
Production build's support all features out of the box.

### Teachability, documentation, adoption, migration strategy

No info yet

### What is the motivation / use case for changing the behavior?

No info yet

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
