### ISSUE TITLE
Update dependency class-transformer to v0.5.0 in common package

### ISSUE THREAD

**Issue by kamikawa-lvgs** [nestjs/nest#8694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Error message: classTransformer.plainToClass is not a function

Fix the class-transformer version in common/package.json, or update common/pipes/validateion.pipe.ts.

Thanks.

### Minimum reproduction code

https://github.com/nestjs/nest/issues/8670

### Expected behavior

The validation.pipe `transform()` works.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.6.15

### Packages versions

- `@nestjs/common`: 7.6.15

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

https://github.com/nestjs/nest/issues/8670

**Comment by kamilmysliwiec** [comment]
Install 0.5.1 instead.
