### ISSUE TITLE
Parameters applied by @Query cannot be automatically converted to types.

### ISSUE THREAD

**Issue by TaroXin** [nestjs/nest#8695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

A very simple example, I used @Query to get parameters in the controller function. I expected its type to be number, but I actually got string.

```js
@Get()
getHello(
  @Query('pageIndex') pageIndex: number,
  @Query('pageSize') pageSize: number,
): string {
  console.log(typeof pageIndex, typeof pageSize); // Expected result: number number

  return this.appService.getHello();
}
```

`curl -X 'GET' 'http://localhost:3000?pageIndex=1&pageSize=1'  -H 'accept: */*'`

```js
@Get()
getHello(
  @Query('pageIndex') pageIndex: number,
  @Query('pageSize') pageSize: number,
): string {
  console.log(typeof pageIndex, typeof pageSize); // Actual result: string string
  return this.appService.getHello();
}
```

![image](https://user-images.githubusercontent.com/19855713/143212266-fb1f598e-ed96-4969-967d-37493d85102c.png)

### Minimum reproduction code

https://github.com/TaroXin/nest-issue-minimum-reproduction-2021111401/blob/master/src/app.controller.ts

### Expected behavior

I hope @Query can automatically complete the type conversion.

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

"@nestjs/common": "^8.0.0"
"@nestjs/core": "^8.0.0"

### Node.js version

v14.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/validation#transform-payload-objects

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
