### ISSUE TITLE
Default routes using @All()

### ISSUE THREAD

**Issue by ensellure** [nestjs/nest#8696]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

#6237

### NestJS version

7.5.0 -> 8.0.0

### Describe the regression

I recently migrated an application using nest from version 7 to version 8. This application uses a All decorator without argument. It used to make routes / and /status respond with a status 200. Now /status responds with status 404.

### Expected behavior

The decorator All has its argument optional. It reflected [router.use](https://expressjs.com/fr/4x/api.html#app.use) behavior in nest version 7.

With nest version 8, All uses [router.all](https://expressjs.com/fr/4x/api.html#app.all), which first argument is mandatory. All argument is still optional but if not passed, it no longer routes paths other than /.

### Other

Passing '*/' as argument to All seems to fix my problem, but it was not clear in the migration guide that this behavior would change.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
