### ISSUE TITLE
Interceptor can null request.body values, but cannot delete / remove them

### ISSUE THREAD

**Issue by xaphod** [nestjs/nest#8698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am not sure if this is a bug or intended behavior.
Given an http request with a body like { "foo": "bar" }, I would like to use an Interceptor to **delete** foo in some cases.

```
@Injectable()
export class RequestBodyDataInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
    const request = context.switchToHttp().getRequest()
    // tried: deleting keys, or setting body like this
   request.body = {}
   return next.handle()
}
```

The above does not work: Controllers still get the original body.

What DOES work:

```
@Injectable()
export class RequestBodyDataInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
    const request = context.switchToHttp().getRequest()
    // tried: deleting keys, or setting body like this
   request.body['foo'] = undefined
   return next.handle()
}
```

... but this is not what I want, as falsy might be a value that's different than not present.

thanks for any help!

### Minimum reproduction code

see above

### Expected behavior

see above

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.6.18

### Packages versions

7.6.18

### Node.js version

14.18.6

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
