### ISSUE TITLE
[ExceptionHandler] Nest can't resolve dependencies of the AppController (?). Please make sure that the argument Object at index [0] is available in the AppModule context.

### ISSUE THREAD

**Issue by tqma113** [nestjs/nest#8702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[ExceptionHandler] Nest can't resolve dependencies of the AppController (?). Please make sure that the argument Object at index [0] is available in the AppModule context.

### Minimum reproduction code

https://github.com/tqma113/modern-nest-test

### Steps to reproduce

1. pnpm install
2. pnpm run dev

### Expected behavior

No Error

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.2

### Packages versions

"@nestjs/core": "^8.2.2",
"@nestjs/common": "^8.2.2"

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

https://github.com/modern-js-dev/modern.js/issues/333

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
