### ISSUE TITLE
ValidationPipe should let `tranform` option to be `true` by default

### ISSUE THREAD

**Issue by ZanMinKian** [nestjs/nest#8703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have read the source code of `validation.pipe.ts`. I think `tranform` option should be `true` by default. Here is the demo:

```typescript
import { NestFactory } from "@nestjs/core";
import { IsString } from "class-validator";
import { Controller, Get, Module, Param, UsePipes, ValidationPipe } from "@nestjs/common";

class Hello {
  @IsString()
  id!: string;
}

@Controller("hi1")
export class AppController1 {
  @Get(":id")
  @UsePipes(ValidationPipe)
  getHello(
    @Param() query: Hello
  ): string {
    return String(query instanceof Hello);
  }
}

@Controller("hi2")
export class AppController2 {
  @Get(":id")
  @UsePipes(new ValidationPipe({ transform: true }))
  getHello(
    @Param() query: Hello
  ): string {
    return String(query instanceof Hello);
  }
}

@Module({
  controllers: [AppController1, AppController2]
})
export class AppModule {
}

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}

bootstrap();
```

I think the first controller `AppController1` should return `true`。

### Minimum reproduction code

https://github.com/ZanMinKian/nest-transform-enabled-default-demo.git

### Steps to reproduce

1. run `git clone https://github.com/ZanMinKian/nest-transform-enabled-default-demo.git && cd nest-transform-enabled-default-demo && npm ci && npm run start`
2. run `curl http://localhost:3000/hi1/abc`
3. run `curl http://localhost:3000/hi2/abc`

### Expected behavior

Currently, `curl http://localhost:3000/hi1/abc` return `false`, but I think it should return `true`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.1

### Packages versions

{
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
}

### Node.js version

12.22.7

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> I think the first controller AppController1 should return true。

It should return false.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
