### ISSUE TITLE
Swagger definitions gets corrupted when using class-transformer annotations to serialize the response for a controller

### ISSUE THREAD

**Issue by onhate** [nestjs/nest#8704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When annotating a controller method with  `class-transformer` `@TransformPlainToClass` the Swagger documentation gets corrupted, depending on the order of the annotations it either loses the Params descriptors or the Response descriptor

### Minimum reproduction code

https://github.com/onhate/nestjs-transformers-issue

### Steps to reproduce

1. `npm i`
2. `npm run start:dev`
3. open http://localhost:3000/#/default/transform
4. see no swagger definition is present
![2021-11-25 at 09 46 23@2x](https://user-images.githubusercontent.com/980905/143444456-5f98b8d9-ee6b-4911-9496-16b53b0fe1df.png)
5. comment out the `@TransformPlainToClass` annotation on `AppController.transform`
6. open http://localhost:3000/#/default/transform
7. see it works fine

Extra steps:

this sequence breaks the params
```
  @Get(':name')
  @ApiOperation({ operationId: 'transform' })
  @ApiResponse({ type: OriginalDto })
  @TransformPlainToClass(OriginalDto, {
    excludeExtraneousValues: true,
  })
```

this sequence breaks the params and the response type
```
  @Get(':name')
  @TransformPlainToClass(OriginalDto, {
    excludeExtraneousValues: true,
  })
  @ApiOperation({ operationId: 'transform' })
  @ApiResponse({ type: OriginalDto })
```

this sequence breaks it all
```
  @TransformPlainToClass(OriginalDto, {
    excludeExtraneousValues: true,
  })
  @Get(':name')
  @ApiOperation({ operationId: 'transform' })
  @ApiResponse({ type: OriginalDto })
```

### Expected behavior

Swagger definitions should remain intact when transformation operations are defined.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

^8.0.0 => 8.2.3

### Packages versions

```
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/swagger": "^5.1.5",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.1.6"
```

### Node.js version

14

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
`class-transformer` decorators override original function descriptors. They are not designed to work with NestJS controllers.
