### ISSUE TITLE
Can't get JoiValidationPipe to work

### ISSUE THREAD

**Issue by dyaacov** [nestjs/nest#871]
Hi All,
I tried 2 options:

1. @UsePipes(new _JoiValidationPipe_(_ChangePasswordSchema_))
2. @Body(new _JoiValidationPipe_(_ChangePasswordSchema_)) body

but my _ChangePasswordSchema_ is undefined in _JoiValidationPipe_ constructor

**_ChangePasswordSchema.dto.ts_**
`
const Joi = require('joi');

export const ChangePasswordSchema = Joi.object().keys({
    oldPassword: Joi.string(),
    newPassword: Joi.string()
})

`

any idea?
Dekel

**Comment by kamilmysliwiec** [comment]
Please, use ISSUE template.
