### ISSUE TITLE
Failed to launch app with enabled CORS after minor update of platform-fastify

### ISSUE THREAD

**Issue by pasha-vuiko** [nestjs/nest#8711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using GrapphQL on my project.

After updating `@nestjs/platform-fastify` from version `8.0.6` to `^8.0.11` the Error occurs when CORS is enabled in `main.ts` via `app.enableCors()` :
```
/app/node_modules/fastify/lib/decorate.js:40
     throw new FST_ERR_DEC_ALREADY_PRESENT(name)
           ^
 FastifyError: The decorator 'corsPreflightEnabled' has already been added!
     at decorateConstructor (/app/node_modules/fastify/lib/decorate.js:40:11)
     at Object.decorateRequest (/app/node_modules/fastify/lib/decorate.js:118:3)
     at fastifyCors (/app/node_modules/fastify-cors/index.js:20:11)
     at Plugin.exec (/app/node_modules/avvio/plugin.js:132:19)
     at Boot.loadPlugin (/app/node_modules/avvio/plugin.js:267:10)
     at Task.release (/app/node_modules/fastq/queue.js:149:16)
     at worked (/app/node_modules/fastq/queue.js:201:10)
     at /app/node_modules/avvio/plugin.js:270:7
     at done (/app/node_modules/avvio/plugin.js:202:5)
     at check (/app/node_modules/avvio/plugin.js:226:9)
     at internal/process/task_queues.js:141:7
     at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
     at AsyncResource.runMicrotask (internal/process/task_queues.js:138:8)
     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Noticed that it is caused by GraphQL enabled in project. If I completely turn off GraphQL or use `@nestjs/platform-fastify` version `8.0.6` everything is working.

### Minimum reproduction code

https://github.com/pasha-vuiko/nestjs-platform-fastify-cors-bug

### Steps to reproduce

1. `npm i`
2. `npm start:dev`
3. See the error in console...

### Expected behavior

Absence of error when CORS is enabled for REST endpoints while GraphQL is present in a project.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.6

### Packages versions

 "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^9.1.2",
    "@nestjs/platform-fastify": "^8.2.3",
    "apollo-server-fastify": "^3.5.0",
    "fastify-compress": "^3.6.1",
    "fastify-helmet": "^5.3.2",
    "graphql": "^15.7.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"

### Node.js version

14.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
when enabling CORS, [this line](https://github.com/fastify/fastify-cors/blob/2b846697bd42b96ed498ed9b44cd9beb029a0bd7/index.js#L20) of `fastify-cors` is called twice, which triggers that error

**Comment by kamilmysliwiec** [comment]
There's not much we can do to prevent this issue. Check out @micalevisk for instructions on how to fix it.
