### ISSUE TITLE
generate swagger static artifact

### ISSUE THREAD

**Issue by kusyka911** [nestjs/nest#8714]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As a developer, I want be able to generate API documentation artifacts during the CI builds.

There are a few [similar issues](https://github.com/nestjs/swagger/issues/231) about generating static swagger artifacts with [solution to modify app's entrypoint](https://github.com/nestjs/swagger/issues/110#issuecomment-527455775) of the application.

But I think things like this must not exists in code when it's delivered to production servers, so I'm not agreed with solutions like this.

### Describe the solution you'd like

Add cli command to generate swagger artifacts in json/yaml/html format.
example:
```bash
nest swagger
```

Add options option `type`
example:
```bash
nest swagger --type html
```

generate static artifact into `dist/swagger` directory and allow developers to configure it via `nest-cli.json` config.

Show error in case swagger is not installed as project dependency or dev-dependency

As additional feature to generate customizeble entry-point like `src/swagger.ts` to configure documents generator, and split full API into a few smaller documents.

### Teachability, documentation, adoption, migration strategy

This will allow to generate static artifacts in acceptable way on local machine and during CI/CD pipeline.

### What is the motivation / use case for changing the behavior?

To generate swagger artifacts during CI build and avoid useless code inside application build.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
