### ISSUE TITLE
Can't set configuration per micro service in hybrid app

### ISSUE THREAD

**Issue by regevbr** [nestjs/nest#8715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using hybrid app, I want to be able to define global interceptors for each micro service seperatly.
This is techincally currently possible by calling the `useGlobalFilters` method on the returned instance of `connectMicroservice` but sadly it doesn not work and the interceptros are not being used. It seems that the code in `connectMicroservice` causes the config to be ignored somehow.

### Minimum reproduction code

https://github.com/regevbr/nestjs-issue8715

### Steps to reproduce

1. clone the reproduction repo
2. `npm run start:dev`
3. `curl http://localhost:3000/hello`
You will see that the interceptor is not being used (i.e. the console log doens't happen)

### Expected behavior

We should be able to control the config of the micro service indepdently. This can be probalby achieved most easily by allowing to pass the config object in the `connectMicroservice` method

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.8

### Packages versions

   "@nestjs/common": "^8.0.8",
    "@nestjs/config": "^1.1.0",
    "@nestjs/core": "^8.0.8",
    "@nestjs/microservices": "^8.0.8",

### Node.js version

v16.11.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I managed to get it working by allowing the hybridAppOptions to get a predefined ApplicationConfig object, that if we initialize beforehand, will make the interceptor work. I don't mind working on a PR if that is something that you want to fix :-)

**Comment by regevbr** [comment]
@vlad-ostrovski

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.
