### ISSUE TITLE
Sse Metadata Reflection

### ISSUE THREAD

**Issue by wSedlacek** [nestjs/nest#8716]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Server Side Events operate differently to other http request and when writing interceptors and guards it is not possible to know if a route is for a server side event or another type.

For example, when a server side event adding headers like `Server-Timing` are meaningless as the server would have sent the headers before the request is "complete"

I see that there is some metadata set on the handler here

https://github.com/nestjs/nest/blob/d9a0e4f66c1752d7c0c8f2a47344f2168bc7977e/packages/common/decorators/http/sse.decorator.ts#L23

But the `SSE_METDATA` nor any function that users that key is exposed.
I can write something like this using my own constant as the key
```
    const isSse = Reflect.getMetadata('__sse__', context.getHandler()) as boolean;
```

But this seems like I am getting far too close to internal details as there is no contract between this code and the `SSE_METDATA` that the value will remain the same.

### Describe the solution you'd like

It would be great if `getType()` had `sse` returned for sse methods, or if a new method was introduced to the `ExecutionContext` context.

### Teachability, documentation, adoption, migration strategy

Adding documentation to either the Sse or Interceptors/Guards pages might just be as simple as examples.

### What is the motivation / use case for changing the behavior?

I discovered the need for this API when building a ServerTimingInterceptor which is applied as global middleware.

**Comment by kamilmysliwiec** [comment]
We can export the `SSE_METADATA` constant from the root (of the package). There are no plans to update the `getType()` method though (it's still HTTP regardless)

**Comment by micalevisk** [comment]
you can import `SSE_METADATA` like so:  
`import { SSE_METADATA } from '@nestjs/common/constants'`
