### ISSUE TITLE
CORS Headers are not applied to SSE when using fastify adapter

### ISSUE THREAD

**Issue by wSedlacek** [nestjs/nest#8717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the fastify adapter with `@Sse()` routes the `app.enableCors()` does not append the `cors` headers to to the response.

### Minimum reproduction code

https://github.com/wSedlacek/nest-fastify-sse-cors

### Steps to reproduce

1. Clone the reproduction (look at commit history for changes from a fresh project) 
2. `npm i`
3. `nest start`
4. Open `http://localhost:3000/example`
5. Look at header and see that `Access-Control-Allow-Origin` is missing.
<img width="586" alt="Screen Shot 2021-11-29 at 03 21 53" src="https://user-images.githubusercontent.com/8206108/143859786-e75d318d-2289-4613-94e7-acaf729abbb0.png">

### Expected behavior

I would expect that when configuring `cors` via `app.enableCors()` for that to affect all routes in the application including sse routes.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.3

### Packages versions

```
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/platform-fastify": "^8.0.0",
```

### Node.js version

v14.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

It's not clear if this is something that can be fixed with nest packages, or with `fastify-cors`.
If this is something that needs to be fixed with `fastify-cors` then I am happy to open an issue there so this can be resolved.

**Comment by wSedlacek** [comment]
I found a similar library which may have a solution.

https://github.com/NodeFactoryIo/fastify-sse-v2/pull/22

**Comment by jmcdo29** [comment]
From the looks of it, this takes the current existing headers, and adds them to the custom headers that are being written, correct? I think that would be beneficial for both Express and Fastify. Would you like to implement this in a PR?

**Comment by wSedlacek** [comment]
> Would you like to implement this in a PR?

Already on it.

**Comment by kamilmysliwiec** [comment]
Lets track this here https://github.com/nestjs/nest/pull/8729
