### ISSUE TITLE
ValidationPipe is using class-validator instead @nestjs/class-validator

### ISSUE THREAD

**Issue by gperdomor** [nestjs/nest#8719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ValidationPipe is using class-validator instead @nestjs/class-validator

### Minimum reproduction code

N/A

### Expected behavior

ValidationPipe should use `@nestjs/class-validator` of check one of this: `@nestjs/class-validator` or `class-validator`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

8.2.3

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Hi @gperdomor, I think this `@nestjs/class-validator` package transaction will happen with the future major version of NestJS (v9). 
I had read it in some old issue as soon as I find it I attach it to this.

At the moment however it is correct that it uses the package `class-validator`, then the package `@nestjs/class-validator` and a fork of the package `class-validator`.

**Comment by micalevisk** [comment]
see https://github.com/nestjs/nest/issues/8562#issuecomment-970107298
