### ISSUE TITLE
Query Params with Pipes cause server to fall over when used with SSE and Interceptors

### ISSUE THREAD

**Issue by wSedlacek** [nestjs/nest#8730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using a pipe with a query param like so
```ts
@Controller('example')
@UseInterceptors(ExampleInterceptor)
export class ExampleController {
  @Sse()
  public events(
    @Query('id', ParseUUIDPipe) id: string,
  ): Observable<MessageEvent> {
    console.log(id);
    return interval(300).pipe(mapTo({ data: 'Example' }));
  }
}
```

The following error would be thrown if `id` fails the `ParseUUIDPipe` transform, such as when it is missing.
```
/node_modules/@nestjs/common/utils/is-uuid.js:13
        throw new exceptions_1.BadRequestException('The value passed as UUID is not a string');
              ^
BadRequestException: The value passed as UUID is not a string
    at Object.isUUID (/node_modules/@nestjs/common/utils/is-uuid.js:13:15)
    at ParseUUIDPipe.transform (/node_modules/@nestjs/common/pipes/parse-uuid.pipe.js:20:24)
    at /node_modules/@nestjs/core/pipes/pipes-consumer.js:16:33
    at resolveParamValue (/node_modules/@nestjs/core/router/router-execution-context.js:147:23)
    at async Promise.all (index 0)
    at pipesFn (/node_modules/@nestjs/core/router/router-execution-context.js:150:13)
    at /node_modules/@nestjs/core/router/router-execution-context.js:37:30
 ```

### Minimum reproduction code

https://github.com/wSedlacek/sse-query-pipes

### Steps to reproduce

1. Clone the reproduction (look at commit history for changes from a fresh project)
2. `npm i`
3. `nest start`
4. Open `http://localhost:3000/example`
5. Notice that in the terminal an error was thrown
6. Attempt another request
7. Notice how the server does not respond

### Expected behavior

I would expect the failing to transform to return a 400 like any http request and for the server to continue to respond to future request.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.3

### Packages versions

├── @nestjs/cli@8.1.5
├── @nestjs/common@8.2.3
├── @nestjs/core@8.2.3
├── @nestjs/platform-express@8.2.3
├── @nestjs/schematics@8.0.5
├── @nestjs/testing@8.2.3

### Node.js version

14.18.

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by wSedlacek** [comment]
Looking the code, this appears to be where it branches depending on if there is an interceptor or not.
https://github.com/nestjs/nest/blob/9aa9d0ee24d6f4efe2cef8d6cfa114a546dddebb/packages/core/interceptors/interceptors-consumer.ts#L21-L39

It works just fine without any interceptors so I suspect the bug is somewhere in there.

**Comment by wSedlacek** [comment]
So I have done some further investigation.

The problem occurs when `InterceptorsConsumer#intercept` returns an observable with an SSE handler.

Typically on a GET that observable would be turned into a promise here:
https://github.com/nestjs/nest/blob/9aa9d0ee24d6f4efe2cef8d6cfa114a546dddebb/packages/core/router/router-execution-context.ts#L451

Which is awaited and if an error occurs it is thrown back here:
https://github.com/nestjs/nest/blob/9aa9d0ee24d6f4efe2cef8d6cfa114a546dddebb/packages/core/router/router-proxy.ts#L22-L25

However with an SSE the result is never turned back into a promise instead piped into an observable here:
https://github.com/nestjs/nest/blob/9aa9d0ee24d6f4efe2cef8d6cfa114a546dddebb/packages/core/router/router-response-controller.ts#L101

Now when the response from `InterceptorsConsumer#intercept` is a `Promise` (seems to only be when there are no interceptors) the result is is awaited here:
https://github.com/nestjs/nest/blob/9aa9d0ee24d6f4efe2cef8d6cfa114a546dddebb/packages/core/router/router-execution-context.ts#L163-L170

Which if thrown makes it back up to the `RouterProxy#createProxy`

So I think there are two ways to approach this problem:
 a) Have the results `InterceptorsConsumer#intercept` collapsed into a `Promise` before they get to `RouterResponseController#sse` OR
 b) Add in a `catchError()` to `RouterResponseController#sse` that effectively does the same thing as the catch in `RouterProxy#createProxy`
 
 @jmcdo29 if you have any thoughts I would love to hear them.

**Comment by wSedlacek** [comment]
Because a Interceptor could return an error at an emission from the handler I am thinking `b` is the right solution, however I don't know how I feel about duplicating the catch logic in `RouterProxy#createProxy`.

Perhaps I could refactor that catch logic to be passed in to the `RouterResponseController#sse`?

**Comment by jmcdo29** [comment]
I think the `catchError` approach is cleaner, let's not take it from an observable to a promise  back to an observable, you know? I think being able to reuse the existing logic would be great, but if it isn't possible it won't be the worst thing in the world

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8740
