### ISSUE TITLE
NestFactory.createApplicationContext buffer logs does not print buffered logs to custom logger

### ISSUE THREAD

**Issue by max-abclabs** [nestjs/nest#8733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

NestFactory.createApplicationContext buffer logs does not print buffered logs to custom logger.

```typescript
async function bootstrap() {
  const app = await NestFactory.createApplicationContext(
    AppModule,
    {
      bufferLogs: true,
    },
  );
  app.useLogger(app.get(CustomLogger));
  app.get(CustomLogger).log('Json log');
}
bootstrap();
```

This code only logs `{"message":"Json log","logLevel":"log","appName":"MyApp"}`. It should log all of Nestjs buffered logs.

### Minimum reproduction code

https://github.com/max-abclabs/min-repro

### Steps to reproduce

1. `npm i`
2. `npm run start`

### Expected behavior

Expect the custom logger to log all buffered logs. Including the dependency injections and that the application has started successfully..

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",

### Node.js version

v16.6.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Looks like this is definitely a bug. @kamilmysliwiec is there a reason we don't flush the logs as soon as the new logger configuration is registered, and we wait for the server to be up and listening?

**Comment by kamilmysliwiec** [comment]
Well, after calling the `createApplicationContext` method you're already _all set_, meaning, there are no `listen()` or `init()` methods that would flush buffered logs. We also can't flush them out automatically as this feature wouldn't make any sense then. We could technically flush logs when _app.useLogger()_ is called (in case `createApplicationContext` is used) and I'd be happy to accept such a PR! Contributions are more than welcome :)

**Comment by max-abclabs** [comment]
Solved it by manually calling `app.flushLogs()` after registering the custom logger.

**Comment by max-abclabs** [comment]
I will leave the issue open if anyone wants to create a PR for flushing logs when `app.useLogger()` is called.

**Comment by micalevisk** [comment]
> Is it possible to flush the logs manually efter the custom logger has been registered?

(just for referenc) this is covered here: https://docs.nestjs.com/techniques/logger#dependency-injection

![image](https://user-images.githubusercontent.com/13461315/144245497-d925e07f-5a5a-44ec-9fc5-92e07ba4ad2c.png)

---

Also, I think the docs can tell us regarding when `Logger#flush` is invoked when `autoFlushLogs` is on, right?

**Comment by micalevisk** [comment]
@kamilmysliwiec 

> We could technically flush logs when app.useLogger() is called (in case `createApplicationContext` is used)

but only if `autoFlushLogs === true`, right?

To me, this condition make things a bit tricky to get working without passing `options` below around by adding fields to `NestApplicationContext` (to avoid breaking changes), as `context` object need to be aware of `options.autoFlushLogs`

https://github.com/nestjs/nest/blob/df2dab4fccc5e9a32e2305929e09c7392b3daf78/packages/core/nest-factory.ts#L129-L146

https://github.com/nestjs/nest/blob/24e6c821a0859448646fd88831f20e4c5ae50980/packages/core/nest-application-context.ts#L132-L134

```diff
+   if ( ?? autoFlushLogs ?? ) this.flushLogs();
```

**Comment by kamilmysliwiec** [comment]
Correct @micalevisk, only when app created with `createApplicationContext` and `autoFlushLogs === true`

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8738
