### ISSUE TITLE
Microservice broken after update from 7 -> 8, docs provide no alternative from nestfactory.create with app.get()

### ISSUE THREAD

**Issue by Meywether** [nestjs/nest#8742]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

7-8

### Describe the regression

Hi there, 
thanks for your time.
I create my microservices by creating a INestApplication as seen here in this repo: https://github.com/Meywether/nestjs_ms1
After upgrading from 7 -> 8 and after consulting the migration guide I came to the result that my way of getting my config variables is not supported anymore. But the migration guide does not tell me how the handle this issue. Let me outline the problem:

I create my Nest application with nest-winston as  a logger and need to get the variables from my config:
``
![image](https://user-images.githubusercontent.com/39849054/144745227-b3393096-80f5-4db7-8223-1d11f8ea5168.png)

``
Since createMicroservice does not allow to inject my config service, containing the redis config, I need to workaround this in this way: 
![image](https://user-images.githubusercontent.com/39849054/144745271-d1dca8f9-01f2-4d79-8118-a6128a22426b.png)

As you can already see line 65 is red -> This is also stated in the migration guide, that startAllMicroservices does not have any argument. But also with .then()... I can not get this running again.

Also with app.listen -> not working because app is not a instance of INestMicroservices.

Here the error:
![image](https://user-images.githubusercontent.com/39849054/144745137-6c551783-c3b9-474d-b143-d5d7a789b2d2.png)

Here is the main HTTP Repo: https://github.com/Meywether/nestjs_http_sample -> working with Nest 8
Here is the main Microservice Repo in broken state with config service: https://github.com/Meywether/nestjs_ms1

May I kindly ask for your help ?

Thank you very much in advance!

### Minimum reproduction code

https://github.com/Meywether/nestjs_ms1 and https://github.com/Meywether/nestjs_http_sample

### Input code

```ts

```

### Expected behavior

Help to develop a different approach to inject config service.

Update: 05.12.2021- Nest 8 and Nest 7 communication via redis is also not possible due to redis 4 @ nest 8 and redis 3 @nest 7 updated depency of the main repo to cover this.
Update 05.12.2021 - Found an open discussion about a similar context. I think this one is related:
https://github.com/nestjs/nest/issues/2343

**Comment by jmcdo29** [comment]
The microservice `start` method (whether in a hybrid application or a dedicated one) no longer takes a callback. It's just an async method. This worked for me (save for the fact that I had an invalid config)

```ts
  await app.startAllMicroservices();
  console.log("MS 1 is listening ....");
```

[We make a general mention of this here](https://docs.nestjs.com/migration-guide#async-listenstart-methods), but we can update this to be more explicit if need be.

**Comment by Meywether** [comment]
@jmcdo29 thanks for your answer but using my test repo, mentioned above, I never come to the console.log:

![image](https://user-images.githubusercontent.com/39849054/144761156-8c433c26-f71e-48b8-8a59-44e923a7113d.png)

Did you changed anything else within the repo ?

Best regards
Meywether

**Comment by jmcdo29** [comment]
Well, in your reproduction you didn't provide a way to run redis, so I didn't get any further r the invalid host error. Next time please provide as full minimum reproduction

**Comment by Meywether** [comment]
@jmcdo29 this point goes to you, sorry my fault:
Please find here the redis docker container and I updated the repo with a .env sample
[redis.zip](https://github.com/nestjs/nest/files/7656759/redis.zip)

**Comment by micalevisk** [comment]
@Meywether run your code with `NEST_DEBUG=true` and `DEBUG=*` env vars

**Comment by Meywether** [comment]
@micalevisk Very warm welcome to the discussion :)

I set the two variabes in .env: 

and this is the output:

![image](https://user-images.githubusercontent.com/39849054/144803804-ff31e196-8574-4559-914c-8ae4b4fcc04f.png)

Can you see something ?

express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +3ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +2ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +1ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +1ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to 'C:\\Users\\XXXXXX\\Desktop\\nestjs_probs\\ms\\views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
[NestWinston] Info      6.12.2021, 08:16:23 [NestFactory] Starting Nest application... 
- {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency Reflector in the Reflector provider (alias) - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for Reflector in InternalCoreModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Found Reflector in InternalCoreModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency HttpAdapterHost in the HttpAdapterHost provider (alias) - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for HttpAdapterHost in InternalCoreModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Found HttpAdapterHost in InternalCoreModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency String in the Logger provider  - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for String in AppModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for String in ConfigModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for String in ConfigHostModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency Object in the Logger provider  - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for Object in AppModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for Object in ConfigModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for Object in ConfigHostModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency Symbol(CONFIG_SERVICE) in the ConfigService provider  - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for Symbol(CONFIG_SERVICE) in ConfigModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for Symbol(CONFIG_SERVICE) in ConfigHostModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Found Symbol(CONFIG_SERVICE) in ConfigHostModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency CONFIGURATION_TOKEN in the ConfigService provider  - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for CONFIGURATION_TOKEN in ConfigHostModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Found CONFIGURATION_TOKEN 
in ConfigHostModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency CONFIGURATION(1dc97cb2-cd12-467a-959f-c645dc9420f8) in the ConfigService provider  - {}     
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for CONFIGURATION(1dc97cb2-cd12-467a-959f-c645dc9420f8) in ConfigModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Found CONFIGURATION(1dc97cb2-cd12-467a-959f-c645dc9420f8) in ConfigModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency CONFIGURATION_TOKEN in the CONFIGURATION_LOADER provider  - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for CONFIGURATION_TOKEN in ConfigModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for CONFIGURATION_TOKEN in ConfigHostModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Found CONFIGURATION_TOKEN 
in ConfigHostModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency CONFIGURATION(1dc97cb2-cd12-467a-959f-c645dc9420f8) in the CONFIGURATION_LOADER provider  - 
{}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for CONFIGURATION(1dc97cb2-cd12-467a-959f-c645dc9420f8) in ConfigModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Found CONFIGURATION(1dc97cb2-cd12-467a-959f-c645dc9420f8) in ConfigModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for String in StatusModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for Object in StatusModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for String in InternalCoreModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for Object in InternalCoreModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Resolving dependency AppService in the AppController provider  - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Looking for AppService in 
AppModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InjectorLogger] Found AppService in AppModule - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InstanceLoader] StatusModule dependencies initialized - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InstanceLoader] ConfigHostModule dependencies initialized - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InstanceLoader] AppModule dependencies initialized - {}
[NestWinston] Info      6.12.2021, 08:16:23 [InstanceLoader] ConfigModule dependencies initialized - {}

**Comment by Meywether** [comment]
Some experiments later I found a possible explaination for the not starting MS but it gets me to another problem:
Downgrading Redis to 3.1.2 with nest 8 apps let it work again! But both on redis 4 -> MS not working so I think that this is a possible redis issue in connection with redis 4.0 package.


BUT If you want to trigger the status endpoint -> its throws me an 500 because suddenly my injected config service in status.controller ins the ms1 repo is suddenly undefined:

![image](https://user-images.githubusercontent.com/39849054/144820183-63aca403-2d5a-47ab-ad3e-7d75e12360c3.png)

Can you maybe tell me why ? ^^

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/8710
