### ISSUE TITLE
How to implement the "comment" requirement for SSE polyfill implementation

### ISSUE THREAD

**Issue by ellogwen** [nestjs/nest#8749]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am using SSE endpoints to catch notifications in the frontend. The frontend is a quasar application, that uses the VueSSE package. VueSSE utilizes the EventSource polyfill from Yaffle.

Now I am facing, the issue, that the polyfill requires a `comment` packet each 15-30 seconds to keep the connection alive. If this packet is missing, the EventSource drops the connection and reconnects. 

See: https://github.com/Yaffle/EventSource#server-side-requirements

This is not that big of a deal, however the polyfill throws uncatchable errors to the console, that cannot be surpressed

See: https://github.com/tserkov/vue-sse/issues/35

I would like to know, how I can send those comment heartbeats?

### Describe the solution you'd like

To be honest, for me the best solution would be to add the option to the sse decorator `@Sse('/feed', { heartbeat: { event: 'comment', timeout: 30000 } }) `

Maybe, this is already an option? I am using nest for only a couple of months, so maybe there is a way to add this to existing decorators or extend existing decorators and add the option (via middleware) ?

### Teachability, documentation, adoption, migration strategy

@Sse('/feed', { heartbeat: { event_type: 'comment', timeout: 30000 } })
async getSseFeed(...) { ... }

### What is the motivation / use case for changing the behavior?

The usecase would be to be complient with the EventSource polyfill implementation. I need to use this polyfill, because it enables to add custom headers, that I require when connecting to the sse feed.

**Comment by kamilmysliwiec** [comment]
If you need more granular control over what's happening, consider not using the `@Sse` decorator at all. Just inject the `@Res()` object into your route and apply all required headers manually https://stackoverflow.com/questions/34657222/how-to-use-server-sent-events-in-express-js

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
