### ISSUE TITLE
Add an @ElementCollection like in Java Spring

### ISSUE THREAD

**Issue by Alwinator** [nestjs/nest#8750]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No.

### Describe the solution you'd like

The exact same ElementCollection annotation like detailly described [here](https://stackoverflow.com/a/8969164/8997468). 

### Teachability, documentation, adoption, migration strategy

@ElementCollection allows you to simplify code when you want to implement one-to-many relationship with simple or embedded type. For instance in JPA 1.0 when you wanted to have a one-to-many relationship to a list of Strings, you had to create a simple entity POJO (StringWrapper) containing only primary key and the String in question:

```java
@OneToMany
private Collection<StringWrapper> strings;

//...

public class StringWrapper {
  @Id
  private int id;

  private String string;
}
```
With JPA 2.0 you can simply write:

```java
@ElementCollection
private Collection<String> strings
```

### What is the motivation / use case for changing the behavior?

It would save a lot of time for the developer.

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the ORM-specific repository (TypeORM, MikroORM, whatever you're using).
