### ISSUE TITLE
clean up NestFactory.create signature

### ISSUE THREAD

**Issue by wbhob** [nestjs/nest#876]
https://github.com/nestjs/nest/blob/8d623079875df3eff9dfc38f2790a4b98e3ae727/packages/core/nest-factory.ts#L35-L62

In these lines, the method has six or seven different signature. This should be reduced to as short as possible. I see several that could be reduced. I'm opening a PR for this issue very shortly.

**Comment by kamilmysliwiec** [comment]
Merged
