### ISSUE TITLE
Is there an event sourcing module extending the CQRS module?

### ISSUE THREAD

**Issue by jtuchel** [nestjs/nest#8765]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There is a CQRS module targeting commands and queries but currently there is no Event Sourcing module yet.

https://docs.nestjs.com/recipes/cqrs#cqrs 

### Describe the solution you'd like

It would be nice to have such a module too. It's quite hard to find packages that are still maintained, the only thing I was able to find was this one

https://github.com/thenativeweb/wolkenkit

but I personally still want to go with Nest and feel comfortable with it :)

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

It would be nice if NestJs would target this feature

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
