### ISSUE TITLE
Graphql use FastifyAdapter and  middleware is not runnning

### ISSUE THREAD

**Issue by aikin-vip** [nestjs/nest#8770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

middleware is not correct running

### Minimum reproduction code

https://codesandbox.io/s/lingering-https-oj274?file=/package.json:781-1203

### Steps to reproduce

1. start graphql server 
2. visit https://oj274.sse.codesandbox.io
3. the terminal will show  'middleware is running'
4. visit https://oj274.sse.codesandbox.io/graphql
5.  submit a query 
![image](https://user-images.githubusercontent.com/64122272/145568125-71ed6593-d890-42fc-944a-43a43c024d5d.png)
6. the terminal did't show message
7. in express  it's seems ok 

### Expected behavior

middleware is correct running

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

"@nestjs/common": "8.2.3",
    "@nestjs/core": "8.2.3",
    "@nestjs/graphql": "9.1.2",
    "@nestjs/platform-fastify": "8.2.3",
    "apollo-server": "3.5.0",
    "apollo-server-fastify": "3.5.0",
    "class-transformer": "0.4.0",
    "class-validator": "0.13.2",
    "graphql": "15.7.2",
    "graphql-query-complexity": "0.11.0",
    "graphql-subscriptions": "2.0.0",
    "reflect-metadata": "0.1.13",
    "rxjs": "7.4.0"

### Node.js version

14.18.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
