### ISSUE TITLE
Graphql @ObjectType with name 'Subscription' breaks @ResolveField

### ISSUE THREAD

**Issue by dwene** [nestjs/nest#8772]
### Is there an existing issue for this?
Yes, but it was closed without comment: nestjs/graphql#934
- [X] I have searched the existing issues

### Current behavior

If you create an ObjectType with the name `Subscription`, and request a field off the Subscription entity that requires a @ResolveField, the @ResolveField annotated function is never called.

There was an existing issue for this, but it was closed without comment https://github.com/nestjs/graphql/issues/934

### Minimum reproduction code

https://github.com/lambda-curry/nest-subscription-name-bug

### Installation

`npm install`

### Starting the Server

`npm run start:dev`

### Graphql Playground

When the application is running, you can go to [http://localhost:3000/graphql](http://localhost:3000/graphql) to access the GraphQL Playground. See [here](https://docs.nestjs.com/graphql/quick-start#playground) for more.

### Reproducing the Bug

Go to localhost:3000/graphql and run this query

```
query subscriptions {
  subscriptions {
    id,
    orders {
      id
    }
  }
}

```

Notice that orders always comes back null.

Now try changing the `@ObjectType('Subscription')` to `@ObjectType('SubscriptionModel')`, and run the same query

Notice that it works.

### Expected behavior

The name of the ObjectType should not break the code, or there should at least be a huge warning/error if `Subscription` is a reserved word.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

latest

### Packages versions

    "@nestjs/common": "8.2.3",
    "@nestjs/core": "8.2.3",
    "@nestjs/graphql": "9.1.2",
    "@nestjs/platform-express": "8.2.3",

### Node.js version

17, and 14

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Subscription is a reserved word (in GraphQL) that cannot be used otherwise. 
Please search through some of our old issues on this (this has been discussed several times in the past).
