### ISSUE TITLE
Is there a way to set the nest application to use h2 protocol ?

### ISSUE THREAD

**Issue by SunilManthenaG01** [nestjs/nest#8773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, nest listen is working as HTTP 1.1. Is there a way I can config to use HTTP 2 

### Minimum reproduction code

https://github.com/SunilManthenaG01/nest-monorepo-dist

### Expected behavior

Expected behavior to serve with h2 protocol.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.0

### Packages versions

"@nestjs/common": "8.2.0",
    "@nestjs/core": "8.2.0",
    "@nestjs/platform-express": "8.2.0",

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
[`expressjs` still doesn't support Node `http2` module](https://stackoverflow.com/a/59569226/5290447)

I believe you can use it with fastify https://www.fastify.io/docs/latest/HTTP2

https://github.com/nestjs/nest/blob/8d20e65e7b47a317c778f76e4b49bae86d2d9b1a/packages/platform-fastify/adapters/fastify-adapter.ts#L178-L181

---

Please respect this next time:

![image](https://user-images.githubusercontent.com/13461315/145644170-ec44110b-cd0f-45b3-b3b1-5ef39ab6b74e.png)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
