### ISSUE TITLE
Hi @ajvorobiev,

### ISSUE THREAD

**Issue by sandesh-bhoir** [nestjs/nest#8774]
@kamilmysliwiec 
The response mapping doesn't work with the express response strategy (using `@Res()` object directly is not possible). I've added the *note* about it in the docs. https://docs.nestjs.com/interceptors.

As you have mentioned it cannot be done directly, so is there any other way to achieve this?

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/174#issuecomment-333409901_

**Comment by Tony133** [comment]
Hi @sandesh-bhoir , for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel.

The NestJS Core team uses GitHub to track bug reports, feature requests, and regressions.

However if you think it's a bug, when you find some time try to create a reproduction minimal in a clonable git repository so the NestJS Core Team can to evaluate the problem.
