### ISSUE TITLE
Manually ack Nats Message

### ISSUE THREAD

**Issue by vlad-monittor** [nestjs/nest#8776]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Is there a way to manually acknowledge a message if I use NATS for async communication in a NestJS app? This is very common use case where the message is acknowledge after a service is done processing it. If the message is not acknowledged, the server would need to redeliver (just like in the old NATS Streaming library). This is needed to guarantee that message gets processed.

@EventPattern({ cmd: 'user:create' })
async createUser(@Payload() user: UserDto, @Ctx() context: NatsContext) {
  await this.emailsService.sendWelcomeEmail(user)
  // need to manually acknowledge the message here but the docs do not provide a way to do so.
}

RabbitMQ has this functionality. Old Nats Streaming has this functionality.

### Describe the solution you'd like

@EventPattern({ cmd: 'user:create' })
async createUser(@Payload() user: UserDto, @Ctx() context: NatsContext) {
  await this.emailsService.sendWelcomeEmail(user)
  context.ack() // <-- manually acknowledge the message
}

### Teachability, documentation, adoption, migration strategy

Users would choose to manually acknowledge a message by stating message.ack() or something like handleAck(message)

### What is the motivation / use case for changing the behavior?

Need a guarantee that every service processes the message, because if the service crashes after received it, the message will be lost.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
