### ISSUE TITLE
Provider constructor params become `undefined` without `@Injectable` decorating.

### ISSUE THREAD

**Issue by ZanMinKian** [nestjs/nest#8786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```ts
import { Injectable } from '@nestjs/common';
import { App2Service } from './app2.service';

// @Injectable()
export class AppService {
  constructor(app2: App2Service) {
    console.log(typeof app2);
  }
}
```

If I comment `@Injectable()` out, it prints `undefined`. What I expect is `object` or throwing an error when bootstrap.

### Minimum reproduction code

https://github.com/ZanMinKian/nest-injectable-bug.git

### Steps to reproduce

```bash
git clone https://github.com/ZanMinKian/nest-injectable-bug.git && cd nest-injectable-bug && npm i && npm run start
```

### Expected behavior

Print `object` or throw an error when bootstrap.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.3

### Packages versions

    "@nestjs/common": "^8.2.3",
    "@nestjs/core": "^8.2.3",
    "@nestjs/platform-express": "^8.2.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.4.0"

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This is the expected outcome. Without that decorator (o any other decorator in the class) Typescript won't reflect the constructor's metadata and Nest can't read the metadata, so it just calls `new  AppService()` without the knowledge of anything else needing to be there. This is a limitation of Typescript, and without writing our own AST parser, which we don't plan to do, there's nothing we can do about this
