### ISSUE TITLE
Jest spy and mock function doesn't work on Microservice's controller

### ISSUE THREAD

**Issue by Fazatholomew** [nestjs/nest#8790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying to spy on Microservice controller while doing E2E testing to indicate that the service is called by event emitted by the client. However, when trying to use `service.get<UserController>(UserController)` and spy on the controller, it doesn't work. After asking around in NestJS Discord, here is the [problem](https://discord.com/channels/520622812742811698/600976791452254209/915499808083562518).

Currently, the only workaround this is to spy on console.log which demonstrated in the repro. 

### Minimum reproduction code

https://github.com/Fazatholomew/spy-on-microservice-controller

### Steps to reproduce

1. yarn
2.  yarn test:e2e

### Expected behavior

There should be a way to spy on microservice controller or service or its equivalent. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

"dependencies": {
    "@nestjs/common": "^8.2.3",
    "@nestjs/core": "^8.2.3",
    "@nestjs/microservices": "^8.2.3",
    "@nestjs/platform-express": "^8.2.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.4.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^8.2.3",
    "@types/express": "^4.17.8",
    "@types/jest": "^26.0.15",
    "@types/node": "^14.14.6",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "eslint": "^7.12.1",
    "eslint-config-prettier": "7.1.0",
    "eslint-plugin-prettier": "^3.1.4",
    "jest": "^26.6.3",
    "prettier": "^2.1.2",
    "supertest": "^6.1.6",
    "ts-jest": "^26.4.3",
    "ts-loader": "^8.0.8",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5"
  }

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).

Long story short: you can spy on/mock **service** methods. You **can't** spy on/mock controller methods (annotated methods) after your app is initialized (execution context is created).
