### ISSUE TITLE
Jest Test case error in InjectModel

### ISSUE THREAD

**Issue by kkrishnakv** [nestjs/nest#8792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is mono-repo project

A circular dependency has been detected inside @InjectModel(). Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()". Also, try to eliminate barrel files because they can lead
to an unexpected behavior too.
6 | export class ApplicationService {
7 | constructor(
> 8 | @InjectModel(ApplicationModel)
| ^

@Injectable()
export class ApplicationService {
    constructor(@InjectModel(ApplicationModel) private applicationModel: typeof ApplicationModel) {}

    public async getApplication(): Promise<any> {
        return this.applicationModel.findAll({ attributes: ["appName", "apiKey"] });
    }

    public async getApplicationByKey(key: string): Promise<any> {
        return this.applicationModel.findByPk(key);
    }

    getApp(): string {
        return "hello";
    }
}

application.spect.ts
describe("ApplicationUser", () => {
    let applicationService: ApplicationService;
    let module: TestingModule;
    let applicationController: ApplicationController;
    let httpService: HttpService;
    beforeAll(async () => {
        module = await Test.createTestingModule({
            controllers: [ApplicationController],
            providers: [
                ApplicationService,
                { provide: getModelToken(ApplicationModel), useValue: { findAll: jest.fn().mockResolvedValue([]) } },
            ],
            imports: [HttpModule],
        }).compile();
        applicationService = module.get<ApplicationService>(ApplicationService);
        applicationController = module.get(ApplicationController);
        httpService = module.get<HttpService>(HttpService);
    });
    it("should be defined", () => {
        expect(applicationService).toBeDefined();
        expect(applicationController).toBeDefined();
    });
});

### Minimum reproduction code

https://github.com/nestjs

### Expected behavior

The unit test should execute without error.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

 "@nestjs/sequelize": "0.1.1",
@nestjs/common": "7.3.1",
        "@nestjs/core": "7.3.1",

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
