### ISSUE TITLE
HttpHealthIndicator pingCheck can report status down without raising error in HealthCheckService

### ISSUE THREAD

**Issue by spencer-easton-ait** [nestjs/nest#8795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When the HttpHealthIndicator pingCheck method reports a URL is down it successfully adds the report to the info parameter, but not the error paramter. It also will return HTTP 200. 

{"status":"ok","info":{"nestjs-docs":{"status":"down"}},"error":{},"details":{"nestjs-docs":{"status":"down"}}}

### Minimum reproduction code

https://github.com/spencer-easton-ait/NestJs-Issue-Repro

### Steps to reproduce

npm i 
npm run start:dev
open localhost:3000/health

### Expected behavior

I would expect the check to return a 503 and the HttpHealthIndicator failure reported in the error object 

{"status":"error","info":{"nestjs-docs":{"status":"down"}},"error":{"nestjs-docs":{"status":"down"}},"details":{"nestjs-docs":{"status":"down"}}}

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [x] Other (see below)

### Other package

@nestjs/terminus

### NestJS version

8.0.0

### Packages versions

"@nestjs/axios": "0.0.3",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/terminus": "^8.0.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"

### Node.js version

14.16.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Here is a health response from my actual server while my sql server is down:

{"status":"error","info":{"CF_SERVICE":{"status":"down"},"Redis":{"status":"up"},"Firestore":{"status":"up"}},"error":{"SQL":{"status":"down"}},"details":{"CF_SERVICE":{"status":"down"},"Redis":{"status":"up"},"Firestore":{"status":"up"},"SQL":{"status":"down"}}}

Only the SQL server is noted in the error object. CF-SERVICE is not listed even though it is down. 

If I turn on SQL

{"status":"ok","info":{"CF_SERVICE":{"status":"down"},"SQL":{"status":"up"},"Redis":{"status":"up"},"Firestore":{"status":"up"}},"error":{},"details":{"CF_SERVICE":{"status":"down"},"SQL":{"status":"up"},"Redis":{"status":"up"},"Firestore":{"status":"up"}}}

CF_SERVICE is still down, but the health check passed with HTTP 200 and a status of 'ok'

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
