### ISSUE TITLE
Reporting missing imports in modules

### ISSUE THREAD

**Issue by ClementNerma** [nestjs/nest#8799]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Despite Nest.js being an awesome framework (and I really mean it, using it everyday at work) one of the few remaining pain points is the unresolved dependencies.

Example: you have a module named `UserModule` which has a declared and exported `UserService`. Then in `ArticleModule` you have an `ArticleService` which tries to inject `UserService` in its constructor, but you forgot to import it in the article module, so you get an error about `UserService` not being resolved, without any indication.

### Describe the solution you'd like

I was wondering if it was possible to detect that, since `UserService` is declared as a provider of `UserModule`, there was simply a missing import in `ArticleModule`.

That way, instead of getting a verbose error like:

```
Nest can't resolve dependencies of the <provider> (?). Please make sure that the argument <unknown_token> at index [<index>] is available in the <module> context.

Potential solutions:
- If <unknown_token> is a provider, is it part of the current <module>?
- If <unknown_token> is exported from a separate @Module, is that module imported within <module>?
  @Module({
    imports: [ /* the Module containing <unknown_token> */ ]
  })
```

The displayed error would be something like:

```
Nest can't resolve dependencies of the <provider> (?). It looks like this provider belongs to `UserModule`, which is not imported in `ArticleModule`.
```

Or an equivalent error message to indicate what the error is and how to fix it easily.

What do you think about that?

### Teachability, documentation, adoption, migration strategy

TBD

### What is the motivation / use case for changing the behavior?

Simply give a direct solution to a very common problem in Nest.js

**Comment by micalevisk** [comment]
that would be cool to have, but (IMO) only if it doesn't degrade performance _(or maybe we could opt-in to enable it)_. I'm not sure if this is feasible, tho.

Also, the same provider might be registered in multiple modules. And the module may not be found because it wasn't imported/used anywhere. So the message can look something like this:

```
Nest can't resolve dependencies of the <provider> (?). Please make sure that the argument <unknown_token> at index [<index>] is available in the <module> context.

Hint: Nest's scanner has found <provider> exported in the following modules:
- <module1>
- <module2>
- <moduleN>
You may want to add one of them in <module>'s imports array.
```

**Comment by jmcdo29** [comment]
While I think this is cool, it does add in a lot of complexity to the module resolution code, as it's going to mean we need to have to save each module not only to the current tree it's in but to a global tree as well. While we could get rid of the tree after startup, it's still going to increase the time it takes for applications to start. @micalevisk has another good point that a provider could be registered to multiple modules so we'd need to able to account for that, and then there are dynamic providers (liek the ones from `OgmaModule.forFeature()` or `TypeOrmModule.forFeature()`) that Nest wouldn't have any idea about unless the module is actually imported.

The [current error is documented as](https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error)

```
Nest can't resolve dependencies of the <provider> (?). Please make sure that the argument <unknown_token> at index [<index>] is available in the <module> context.

Potential solutions:
- If <unknown_token> is a provider, is it part of the current <module>?
- If <unknown_token> is exported from a separate @Module, is that module imported within <module>?
  @Module({
    imports: [ /* the Module containing <unknown_token> */ ]
  })
```

> ```
> - If <unknown_token> is exported from a separate @Module, is that module imported within <module>?
>   @Module({
>   imports: [ /* the Module containing <unknown_token> */ ]
>  })
> ```

Without increasing complexity and load times, I feel this is probably the best situation we can heave.

**Comment by micalevisk** [comment]
> Without increasing complexity and load times, 

... and memory consumption.

> I feel this is probably the best situation we can heave.

me too.

**Comment by ClementNerma** [comment]
Thanks for your comments. I don't know how Nest.js works internally, but for simple cases (so leaving aside stuff like TypeORM modules etc.) wouldn't it be doable to have a simple object mapping module names with the list of services they declare? That way it would be possible to show from which module the service comes from in most cases.

**Comment by jmcdo29** [comment]
> wouldn't it be doable to have a simple object mapping module names with the list of services they declare?

Yes, and this is partially what the dependency resolution is already doing, but currently Nest only does this for the current tree it is in (so the current module and the modules it exports), along with the global modules (those marked with `@Global()`, `isGlobal: true`, or Nest core providers [like `ModuleRef` and `REQUEST`]).

For this feature, we'd have to explore all of the modules (at least those in an `imports` array) first, map their providers (not caring about exports), and _then_ start with the module resolution. It could be doable, and may provide some benefits, just not sure how much extra work it would add to the system as it tries to keep all of this mapped. If we do go with this, I feel like adding it behind the `NEST_DEBUG` flag would be a good plan, just to keep it opt-in no matter what. 

@kamilmysliwiec what are your thoughts?

**Comment by kamilmysliwiec** [comment]
I agree with everything that @jmcdo29 and @micalevisk pointed out above. There are simply way too many edge-cases we'd have to cover + it would surely downgrade the performance, complicate the injector/container code even further with minimal benefits for the end-user. If you're already aware that the "UsersService" is missing, you can simply use the "Search" tool of your IDE to determine where it was declared & registered (and so which import is missing).
