### ISSUE TITLE
Introduce hooks into the nest CLI

### ISSUE THREAD

**Issue by max-abclabs** [nestjs/nest#8801]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently working with nest in a big monorepo with ~10 nest applications. We are using the nest CLI to manage applications and it's working really well! 🚀  

Since every application is independent it has it's own Dockerfile in the repo which (almost) always looks the same. When nest scaffolds a project it would be nice to a scaffolded  Dockerfile as well. 

This is not the only problem, we would like to add the app to an existing workflow and add a script in the package.json. I foresee this demand increasing at the same rate as our project grows. 

### Describe the solution you'd like

What would be a good solution to this is to be able to extend the already existing `nest g app <app-name>` command with hooks or plugins which alters the boilerplate code generated by the CLI.

### Teachability, documentation, adoption, migration strategy

I'm not completely sure what is the best solution for this. 

One solution could be to do something similar to git hooks. Another solution is to write standalone plugins which could be injected into the nest cli via a config file. 

As previously mentioned I don't have the perfect solution but would be up to discuss this 😸 

### What is the motivation / use case for changing the behavior?

This would allow the nest CLI to be customised for different applications which in turn can have different deployments settings and config.

**Comment by kamilmysliwiec** [comment]
> What would be a good solution to this is to be able to extend the already existing nest g app <app-name> command with hooks or plugins which alters the boilerplate code generated by the CLI.

This is doable with custom schematics.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
