### ISSUE TITLE
MQTT microservice server and client with same ClientID

### ISSUE THREAD

**Issue by donatoferrulli** [nestjs/nest#8804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The current use of MQTT microservice does not allow to reuse the same connection to publish messages.
Using the same ClientID causes a constant restart of the application (On many Brokes it is not possible to have two sessions with the same clientID).

### Minimum reproduction code

use the standard mqtt example but with ClientID

### Expected behavior

I expect to reuse the same MQTT microservice connection in order to publish messages

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.3

### Packages versions

"@nestjs/common": "^8.0.0",
"@nestjs/core": "^8.0.0",
"@nestjs/mapped-types": "*",
"@nestjs/microservices": "^8.2.3",
"@nestjs/platform-express": "^8.0.0",

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository & example of what you're trying to accomplish.

**Comment by donatoferrulli** [comment]
main.ts : 

```
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const microservice = app.connectMicroservice({
    transport: Transport.MQTT,
    options: {
      url: 'mqtt://localhost:1883',
      **clientId: "test",**
    },
  });

  await app.startAllMicroservices();
  await app.listen(3000);
}
bootstrap();
```

mqtt-client.service.ts
```
@Injectable()
export class MqttClientService {
    
    @Client({
        transport: Transport.MQTT,
        options: {
          url: 'mqtt://localhost:1884',
          **clientId: "test",**
          serializer: new OutboundResponseSerializer()
        }
      })
    client: ClientProxy;

    async onApplicationBootstrap() {
      await this.client.connect();
    }  
    emitMessage(topic: String, data: any) {
        this.client.emit<any>(topic, data);
    } 
}

```

OUTPUT:
[Nest] 4292  - 17/12/2021, 11:07:30     LOG [NestMicroservice] Nest microservice successfully started +899ms
[Nest] 4292  - 17/12/2021, 11:07:31     LOG [NestMicroservice] Nest microservice successfully started +1136ms
[Nest] 4292  - 17/12/2021, 11:07:32     LOG [NestMicroservice] Nest microservice successfully started +1033ms
[Nest] 4292  - 17/12/2021, 11:07:34     LOG [NestMicroservice] Nest microservice successfully started +1947ms
[Nest] 4292  - 17/12/2021, 11:07:35     LOG [NestMicroservice] Nest microservice successfully started +1126ms
[Nest] 4292  - 17/12/2021, 11:07:37     LOG [NestMicroservice] Nest microservice successfully started +2053ms
[Nest] 4292  - 17/12/2021, 11:07:39     LOG [NestMicroservice] Nest microservice successfully started +1038ms
[Nest] 4292  - 17/12/2021, 11:07:40     LOG [NestMicroservice] Nest microservice successfully started +1912ms
[Nest] 4292  - 17/12/2021, 11:07:42     LOG [NestMicroservice] Nest microservice successfully started +1175ms
[Nest] 4292  - 17/12/2021, 11:07:43     LOG [NestMicroservice] Nest microservice successfully started +1888ms


On the Broker side i can see that there are 2 sessions one for mqtt server and one for mqtt client, so we have 2 sessions with the same ClientID so the broker disconnect one client...
For sure i can use a different ClientId but i think that should be a good idea the share the same connection into microservices

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf). Just code snippets is not enough.

**Comment by Nestjss** [comment]
@donatoferrulli don't create repo, you will waste time in vain

**Comment by siewdass** [comment]
Any way to shared the same connection? not always MessagePattern is enougth.. and having 2 connections is redundant.

**Comment by keithwhitson** [comment]
Is this still being considered?

**Comment by brunomarchioro** [comment]
Hello!
I'm building a hybrid NestJs app with a NATS microservice and I need to handle subscriptions and publish messages to different topics. Only "returning" from a @MessagePattern handler is not enough. I dont figure out how to get a reference of the connection created on microservice creation. How can I do that without create an Client and another NATS connection only for this?
