### ISSUE TITLE
Guard dependency fails to resolve despite being used in module where dependency is a provider

### ISSUE THREAD

**Issue by Figments** [nestjs/nest#8805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a `RolesGuard` that exists in a `shared` folder located at the source root. It uses an `AuthService` that's provided by the `AccountsModule` in order to check a user's roles against what the database says they have so that requests can be acknowledged. However, it currently fails when it's used for a route in the `AuthController` within that `AccountsModule`—currently on the `addPseudonym` route—and NestJS produces the following error:

<img width="934" alt="Screen Shot 2021-12-19 at 10 26 53 AM" src="https://user-images.githubusercontent.com/2677783/146692659-672ed335-755f-4386-89f0-20a53965ba67.png">

### Minimum reproduction code

https://github.com/OffprintStudios/dragonfish-next/tree/main/apps/api

### Steps to reproduce

1) `yarn install`
2) add a dummy `.env` file in the `apps/api` folder containing the following values: `REDIS_HOST`, `REDIS_PORT`, `MONGO_URL`
3) from the root, `yarn start:api`
4) see error

### Expected behavior

The API should start, and the `RolesGuard`'s dependencies should be initializing correctly. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

"@nestjs/bull": "^0.4.2",
"@nestjs/common": "^8.2.4",
"@nestjs/core": "^8.2.4",
"@nestjs/event-emitter": "^1.0.0",
"@nestjs/graphql": "^9.1.2",
"@nestjs/jwt": "^8.0.0",
"@nestjs/mongoose": "^9.0.1",
"@nestjs/platform-express": "^8.2.4",
"@nestjs/cli": "^8.1.6",
"@nestjs/schematics": "^8.0.5",
"@nestjs/testing": "^8.2.4",

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I've tried getting help about this in the Discord server, to no avail. I've also tried searching to see if maybe I was doing something incorrectly via the Issues posted here, or on StackOverflow and my many attempts at googling, also to no avail.

So if you guys feel this is posted here in error, mea culpa. But I'm starting to think it's a larger issue than can be solved via assistance.

For reference, here are some random bits of additional info:
- Package Manager: `yarn`
- IDE: VS Code and WebStorm
- OS: macOS Monterey 12.1

**Comment by micalevisk** [comment]
looks like we cannot use your repo due to `@dragonfish/models` not being public available

![image](https://user-images.githubusercontent.com/13461315/146694185-7d89e649-7ddb-4f72-a63f-1adb327de232.png)

**Comment by Figments** [comment]
> After following your steps, I'm getting this:
> 
> ![image](https://user-images.githubusercontent.com/13461315/146694185-7d89e649-7ddb-4f72-a63f-1adb327de232.png)
> 
> Also, try to create a _minimum_ version of it in another branch, idk.

Ah, my bad!

Try this repository out instead: https://github.com/Figments/problem-example

To reproduce:
- `yarn install`
- create a .env file in the root with `REDIS_HOST`, `REDIS_PORT`, and `MONGO_URL`
- `nest start`

**Comment by jmcdo29** [comment]
This error is from a circular dependency . Your `RolesGuard` imports from `$modules/accounts` which is a barrel file. That barrel includes `modules/accounts/services/auth.service.ts` which the `RolesGuard` wants to use, but it also includes `moduels/accounts/controllers/auth.controller.ts` which wants to use the `RolesGuard`, so now to create the `RolesGuard` the `AuthController` needs to be imported, but to set up the metadata for the `AuthController` the `RolesGuard` needs to be created and 💥 circular dependency. 

Try to remove the circular references. Be very careful with barrel files. They can easily lead to this

**Comment by micalevisk** [comment]
@Figments https://github.com/nestjs/nest/issues/1181#issuecomment-430197191

**Comment by Figments** [comment]
Oh, awesome!

I swear this problem was making me tear my hair out. Thanks, you two!
