### ISSUE TITLE
Unable to use TestingModule container with class-validadtor useContainer

### ISSUE THREAD

**Issue by prabhanjansap** [nestjs/nest#8807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying write unit tests using Jest for a class which has custom validator constraints. When I try to create a mock and inject the same into TestingModule, I get undefined for the dependency. I am trying with useContainer as below but it does not accept TestingModule.

useContainer(app.select(moduleFixture), { fallbackOnErrors: true });

It throws an error saying,

Argument of type 'TestingModule' is not assignable to parameter of type 'DynamicModule | Type<unknown>'.
  Type 'TestingModule' is missing the following properties from type 'Type<unknown>': apply, call, bind, prototype, and 5 more.ts(2345)

beforeAll(async () => {
    const moduleRef = await Test
      .createTestingModule({
        imports: [..],
      })
      .compile();

    app = moduleRef.createNestApplication();

    useContainer(app.select(moduleRef), { fallbackOnErrors: true });

    await app.init();
  });

### Minimum reproduction code

Added in description

### Expected behavior

The dependency injection should work in Unit Tests when using validator constraints.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

"@nestjs/common": "8.2.3",
"@nestjs/core": "8.2.3",
"@nestjs/platform-express": "8.2.3",
"@nestjs/typeorm": "8.0.2",

### Node.js version

16.6.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
