### ISSUE TITLE
[NESTJS BUG] Request context not working when using FastifyAdapter

### ISSUE THREAD

**Issue by mittche** [nestjs/nest#8809]
Works pretty well with HTTP GET requests and with other HTTP requests that doesn't have a body. When requests have a body, the logger does not brings context and only prints the basic log message, even when log is invoked inside the request context.

- [X] I have searched the existing issues

### Current behavior

https://github.com/mikro-orm/mikro-orm/discussions/2531

https://github.com/iamolegga/nestjs-pino/issues/546

### Minimum reproduction code

https://github.com/mittche/nest-mikro-rom

### Steps to reproduce

npm i

npm run dev

### Expected behavior

work as expected

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Packages versions

@nestjs/common": "^8.2.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, provide a **minimum reproduction repository** without any third-party libraries.

**Comment by mittche** [comment]
> without any third-party libraries.
https://github.com/nestjs/nest/issues/8234#issuecomment-935995947

**Comment by jmcdo29** [comment]
> > without any third-party libraries.
> > @kamilmysliwiec  [#8234 (comment)](https://github.com/nestjs/nest/issues/8234#issuecomment-935995947)

@mittche there's no minimum reproduction in that issue thread. There's links to other projects that have dependencies as well, but nothing minimum, so please provide a [minimum reproduction repository](https://minimum-reproduction.wtf) so we can better diagnose this

**Comment by mittche** [comment]
> > > without any third-party libraries.
> > > @kamilmysliwiec  [#8234 (comment)](https://github.com/nestjs/nest/issues/8234#issuecomment-935995947)
> 
> @mittche there's no minimum reproduction in that issue thread. There's links to other projects that have dependencies as well, but nothing minimum, so please provide a [minimum reproduction repository](https://minimum-reproduction.wtf) so we can better diagnose this

I can't, I do the maximum that I can :). I not understand how it all work.

**Comment by mittche** [comment]
I don't understand why but if I remove fastify adapter the minimal app work with post, but the me (not so big and complicated app) not work with express adapter too.

**Comment by jmcdo29** [comment]
For us to do anything, we need a __minimum reproduction repository__ as we've already mentioned. I'm going to close this as we don't have one. If you can provide a reproduction, I'll re-open the issue.

**Comment by mittche** [comment]
I'm starting to think it's intentional.
Go and buy paid support for our bugs.

**Comment by jmcdo29** [comment]
Excuse you. None of these are minimum though. A minimum reproduction shouldn't rely on other packages to show the bug, it should be able to stand on it's own and show "Yes, this bug exists in __just__ the framework's code". As we (the Nest team) do not own the code for MikroORM or the nestjs-pino repo, they should not be used to show the bug. Feel free to speculate all you want. All we are asking for is a __simple and minimum__  reproduction that __only__ uses code inside the framework and not an external package. Sorry that's too much for you to manage.

**Comment by mittche** [comment]
absurd, given the fact that in the east there is nothing finite and it is always used in combination with something else
