### ISSUE TITLE
Wildcard support for Kafka topics

### ISSUE THREAD

**Issue by Simpey** [nestjs/nest#8811]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm trying to use wildcard with  @MessagePattern decorator:
`@MessagePattern('my-topic.*')`
But receiving 
`UnhandledPromiseRejectionWarning: KafkaJSProtocolError: The request attempted to perform an operation on an invalid topic at createErrorFromCode (/var/www/nest_app/node_modules/kafkajs/src/protocol/error.js:581:10)`

### Describe the solution you'd like

I'd like to have wildcard support, just like NATS with its wildcard subscriptions

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

-

**Comment by mittche** [comment]
what kafka they with adapter can't do well

**Comment by mittche** [comment]
what kafka they an adapter can't made to work

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/3083
