### ISSUE TITLE
Nest + Fastify + AsyncLocalStorage middlewares

### ISSUE THREAD

**Issue by B5nan** [nestjs/nest#8843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The middlewares are not working if fastify (adapter) is installed. When it is removed the middleware starts to work (express adapter), for both GET and POST requests.

### Minimum reproduction code

https://github.com/B4nan/nest-fastify-als

### Steps to reproduce

yarn
yarn start
curl localhost:3000
curl -X POST localhost:3000

### Expected behavior

To return stored value not undefined.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.4

### Packages versions

platform-express version : 8.2.4
platform-fastify version : 8.2.4
schematics version : 8.0.5
testing version : 8.2.4
common version : 8.2.4
core version : 8.2.4
cli version : 8.1.6

### Node.js version

14/16/17

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
I think this is directly related to #8837

**Comment by kamilmysliwiec** [comment]
#8837
