### ISSUE TITLE
Native support for CBOR as an alternative to JSON

### ISSUE THREAD

**Issue by pstepniewskiconfigit** [nestjs/nest#8846]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Use different format of request and responses. More info could be found on wiki of [CBOR](https://en.wikipedia.org/wiki/CBOR)

### Describe the solution you'd like

Add global serializer for request/response for CBOR.

### Teachability, documentation, adoption, migration strategy

Something similar to `app.setGlobalPrefix(...)` like `app.setGlobalPayloadFormat('cbor')`.

### What is the motivation / use case for changing the behavior?

To have better transfer speed and easier to parse payloads.

**Comment by jmcdo29** [comment]
What about just adding in a [`cbor`](https://www.npmjs.com/package/cbor-body-parser) parser with `app.use()`? This is already doable for and xml parser

```ts
import * as cbor from 'cbor-body-parser';

const bootstrap = async () => {
  const app = await NestFactory.create();
  app.use(cbor({limit: "100kB"}));
  await app.listen(3000);
}
bootstrap();
```

**Comment by micalevisk** [comment]
same as above but using [NestJS middleware](https://docs.nestjs.com/middleware):

```ts
// cbor-body-parser.middleware.ts
import { NestMiddleware } from '@nestjs/common';
import * as cbor from 'cbor-body-parser';

export class CborBodyParserMiddleware implements NestMiddleware {
  use = cbor({ limit: '100kB' });
}
```

```ts
// app.module.ts
// ...
@Module({})
export class AppModule implements NestModule {
  configure(middlewareConsumer: MiddlewareConsumer): void {
    middlewareConsumer
      .apply(CborBodyParserMiddleware)
      .forRoutes({
        path: '*',
        method: RequestMethod.ALL,
      });
```

**Comment by kamilmysliwiec** [comment]
@micalevisk you can also register the middleware using the inline syntax:

```typescript
middlewareConsumer
   .apply(cbor({ limit: '100kB' }))
   ...
```

Creating a dedicated class isn't required.
