### ISSUE TITLE
NestJS problems with APP_FILTER token - Missing Dependencies

### ISSUE THREAD

**Issue by GeorgianStan** [nestjs/nest#8849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When APP_FILTER token is added for a global-scoped filter in `app.module.ts` the following output is received when the application is run.

```
 Nest can't resolve dependencies of the GlobalExceptionFilter (?). Please make sure that the argument Object at index [0] is available in the AppModule context.
Potential solutions:

- If Object is a provider, is it part of the current AppModule?
- If Object is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })
```

### Minimum reproduction code

https://github.com/GeorgianStan/nestjs-app-filter-issue

### Steps to reproduce

1. `npm i`
2. `npm start:dev`

### Expected behavior

App should compile and the global filter should catch all the errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

"@nestjs/common": "^8.0.0"
"@nestjs/core": "^8.0.0",
 "@nestjs/platform-express": "^8.0.0",

### Node.js version

v14.15.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
`HttpAdapterHost` should be imported from the `@nestjs/core` package
