### ISSUE TITLE
Vercel Deployment

### ISSUE THREAD

**Issue by jdgamble555** [nestjs/nest#8853]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We need a way to deploy NestJS to Vercel.  It seems every other framework has build their own (NuxtJS, NextJS, etc).

### Describe the solution you'd like

I would like to easily deploy NestJS to Vercel, particularly an Angular Universal Application.

### Teachability, documentation, adoption, migration strategy

It would somehow user Verce.json (maybe).  It would be easy.

### What is the motivation / use case for changing the behavior?

To deploy to Vercel, which would be good for Advertisement, and getting new NestJS users for you guys!

**Comment by jmcdo29** [comment]
> Vercel is the best place to deploy any frontend app

NestJS is a Node framework. It's not really meant to be used for front end applications (it can serve them, but not really a builder for them, though I guess you could create one)

[If you look at all of their templates you'll notice there is no Koa, Express, or Fastify](https://vercel.com/new/templates). Vercel is for __frontend__ applications, not HTTP servers. 

[There's an open issue in Vercel's repo about Angular Universal Support too](https://github.com/vercel/ng-deploy-vercel/issues/9), so I feel this is less on Nest and more on Vercel's documentation on how to support Angular Universal

**Comment by jdgamble555** [comment]
Hi @jmcdo29.  Thank you for responding.  However, this is incorrect.

Vercel is not JUST for frontend applications.  Every single major frontend framework (Angular, React, Vue, and Svelte) have a counterpart which serves SSR (Angular Universal / NestJS, NextJS, NustJS, Sapper / Sveltekit).  

Angular Universal and NestJs are the only Node Applications that are NOT served on Vercel for the moment.  I realize Nest is not specific to Angular, but it is the closest counterpart.

It is not just about serving express.  These applications can be served on lambda functions in Vercel, just like it NestJS can work on Google Firebase Functions and Google Cloud Run.  Here are examples:

- https://fireship.io/snippets/setup-nestjs-on-cloud-functions/
- https://softwarebrothers.co/blog/setting-up-nestjs-with-firebase-functions/

Vercel essentially does the same thing with Nust, Next, Sapper, and Sveltekit.  It seems `builders` were written for each application to support it:

- [Nuxt Builder](https://github.com/nuxt/vercel-builder)
- [NextJS](https://github.com/vercel/next.js/) - now just part of vercel
- [Sveltekit Adapter](https://github.com/sveltejs/kit/tree/master/packages/adapter-vercel)
- [Sapper Builder](https://github.com/thgh/vercel-sapper)

There are also other builders for other types of applications.

While the builders can be simple or complicated, I imagine Vercel would support it, if someone built it.  Perhaps following rules [here](https://vercel.com/docs/cli#project-configuration/routes).  I am not sure how to go about it, but it should be done.

Thanks,

J

**Comment by jmcdo29** [comment]
> Every single major front end framework have a counterpart which serve SSR

True enough

> Angular Universal / NestJS

Hmm, not sure if I agree with that, especially as the angular universal team has the [express-engine](https://github.com/angular/universal/tree/master/modules/express-engine), [hapi-engine](https://github.com/angular/universal/tree/master/modules/hapi-engine), and [socket-engine](https://github.com/angular/universal/tree/master/modules/socket-engine). There is the [`@nestjs/ng-universal` package](https://github.com/nestjs/ng-universal), though it's definitely not as well maintained, and not mentioned in our docs at all.

> Angular Universal and NestJs are the only Node Applications that are NOT served on Vercel for the moment. I realize Nest is not specific to Angular, but it is the closest counterpart.

I feel this is a bit misleading honestly. Nuxt and Next are both built specifically to be SSR engines for Vue and React respectively. Nest was built to bring Angular's module syntax and class oriented approach to Node, but never was built with the sole intention of being an SSR engine for Angular. In fact, you could use Nest to be the server for Nuxt and Next with the right configuration.

> It is not just about serving express. These applications can be served on lambda functions in Vercel, just like it NestJS can work on Google Firebase Functions and Google Cloud Run.

You could [use Nest as a serverless engine](https://docs.nestjs.com/faq/serverless) on Vercel following Vercel's general [server documentation](https://vercel.com/docs/concepts/functions/serverless-functions)

> Vercel essentially does the same thing with Nust, Next, Sapper, and Sveltekit. It seems builders were written for each application to support it:

Awesome. It would be great to see someone in the community help with this.

**Comment by micalevisk** [comment]
> You could use Nest as a serverless engine on Vercel following Vercel's general server documentation

an example for AWS: https://github.com/rdlabo-team/serverless-nestjs

**Comment by jdgamble555** [comment]
@micalevisk  - Yeah, unfortunately the AWS configuration is completely different.  @jmcdo29 - I have tried creating it myself lol.

If someone got it working, perhaps by building some kind of wrapper like [here](https://github.com/nuxt/vercel-builder/blob/main/src/build.ts) would be cool.

Thanks,

J

**Comment by kamilmysliwiec** [comment]
This issue doesn't seem to be related to Nest framework. See @jmcdo29 answers above for more details.
