### ISSUE TITLE
[Discussion] Need pattern for direct access on Service Layer

### ISSUE THREAD

**Issue by nsisodiya** [nestjs/nest#8854]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Right now, We can only access Services via HTTP Requests. 

If we can have direct access to the service layer via CLI then it will be much faster to work only on the service layer. 

### Describe the solution you'd like

It will really be great If can access the service in some sort of CLI like this.

> services.projectService.create({
    name: "SuperCool Website"
});

> services.projectService.findByName("SuperCool WebSite")

> services.projectService.findById("61c1609b11b57dcf3779953d");

> services.projectService.update({id: "61c1609b11b57dcf3779953d"}, 
{name: "New SuperCoolWebsite"});

This will speed up development because right now, Service Layer is tightly developed along with Resolve Or Controller Layer which can be accessed only via HTTP/CURL methods.

### Teachability, documentation, adoption, migration strategy

Best way to adopt.
```
npm run services
```

### What is the motivation / use case for changing the behavior?

Faster development and while writing great backend, one can focus on service layer without worry about the consumer (REST/GraphQL).

**Comment by micalevisk** [comment]
What if the service use the [request scope](https://docs.nestjs.com/fundamentals/injection-scopes#request-provider)?

**Comment by jmcdo29** [comment]
What about something like [nest-commander] (https://jmcdo29.github.io/nest-commander/docs)? This way you can build your CLI, incorporate easily asking questions to fill in the DTO, and run the service

**Comment by kamilmysliwiec** [comment]
> Right now, We can only access Services via HTTP Requests

This isn't correct. Nest can be used just as an IoC container and you can build any standalone applications on top of that.

https://docs.nestjs.com/standalone-applications
