### ISSUE TITLE
Cannot resolve dependencies when using npm workspaces

### ISSUE THREAD

**Issue by TheAsda** [nestjs/nest#8857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using npm workspaces to organize projects and nest application is in one of workspaces. When i run `start` command it cannot resolve some internal dependencies.

<details>
<summary>Here is the error</summary>

```
ERROR in ../../node_modules/@nestjs/core/nest-application.js 18:102-145
Module not found: Error: Can't resolve '@nestjs/websockets/socket-module' in 'D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\core'
resolve '@nestjs/websockets/socket-module' in 'D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\core'
  Parsed request is a module
  using description file: D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\core\package.json (relative path: .)
    resolve as module
      D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\core\node_modules doesn't exist or is not a directory
      D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\node_modules doesn't exist or is not a directory
      D:\Andrey\Programming\temp\nest-workspaces\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in D:\Andrey\Programming\temp\nest-workspaces\node_modules
        D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\websockets doesn't exist
      D:\Andrey\Programming\temp\node_modules doesn't exist or is not a directory
      D:\Andrey\Programming\node_modules doesn't exist or is not a directory
      D:\Andrey\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
 @ ../../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 3:15-38

ERROR in ../../node_modules/@nestjs/core/nest-application.js 19:119-172
Module not found: Error: Can't resolve '@nestjs/microservices/microservices-module' in 'D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\core'
resolve '@nestjs/microservices/microservices-module' in 'D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\core'
  Parsed request is a module
  using description file: D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\core\package.json (relative path: .)
    resolve as module
      D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\core\node_modules doesn't exist or is not a directory
      D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\node_modules doesn't exist or is not a directory
      D:\Andrey\Programming\temp\nest-workspaces\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in D:\Andrey\Programming\temp\nest-workspaces\node_modules
        D:\Andrey\Programming\temp\nest-workspaces\node_modules\@nestjs\microservices doesn't exist
      D:\Andrey\Programming\temp\node_modules doesn't exist or is not a directory
      D:\Andrey\Programming\node_modules doesn't exist or is not a directory
      D:\Andrey\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
 @ ../../node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/main.ts 3:15-38

webpack 5.65.0 compiled with 2 errors in 3651 ms
```
</details>

### Minimum reproduction code

https://github.com/TheAsda/nest-workspace-issue

### Steps to reproduce

`npm run -w nest start`
Error shows right after start

### Expected behavior

I think there is no much difference between running in single folder or npm workspace as dependencies should resolve the same way.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8

### Packages versions

- "@nestjs/common": "^8.0.0",
-   "@nestjs/core": "^8.0.0",
-   "@nestjs/platform-express": "^8.0.0",

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
So a `nest new` project works with webpack by default, but in an npm workspace this fails. I was able to force it to work by adding `'@nestjs/websockets/websocket-module'` and `@nestjs/microservices/microservices-module` to the built in default webpack config, but this is definitely not the solution we'd want to go for in the end. I'll try and figure out what's going on and why the webpack config acts differently in the separate repos

**Comment by jmcdo29** [comment]
Okay, error comes from the `webpack-node-externals` library not figuring out where `node_modules` is correctly. I think this is just going to be something specific to each workspace approach that isn't a Nest monorepo, so it _may_ be out of our hands. I found two solutions that work with the current minimum reproduction (thank you so much for including that from the start, it really helps us)

1. create a `webpack.config.js` file in `apps/nest` with the following contents:

```js
const nodeExternals = require('webpack-node-externals');

module.exports = (args) => ({
  ...args,
  externals: [nodeExternals({ modulesDir: '../../node_modules' })],
});
```

This tells `webpack-node-externals` to look in the correct spot for the `node_modules` directory`

2. create a symlink from `apps/nest/node_modules` to `node_modules`.  This works in the minimum reproduction, but take care with using symlinks as sometimes you can end up causing multiple references back to the same package which can cause some of Nest's `instanceof` checks to fail and get you some very interesting errors. This could be common if you end up having multiple applications, so I'd go with the custom webpack config from 1.

**Comment by TheAsda** [comment]
Thanks a lot

**Comment by 0xborisgregor** [comment]
Still got caught with same issue 2025. I'm not using **nest.js** but i changed `moduleResolution` from `nodenext` into `bundler` and everything just works.
