### ISSUE TITLE
A circular dependency has been detected. Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()"

### ISSUE THREAD

**Issue by usama7x** [nestjs/nest#8862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

unable to start the application and the point is I'm to trace the issue

### Minimum reproduction code

www.hitgub.com

### Expected behavior

app should start without issues.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.6.15

### Packages versions

  "@nestjs/common": "7.6.15",
    "@nestjs/config": "0.6.3",
    "@nestjs/core": "7.6.15",

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
please respect the warning message:

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- If it's just a quick question you can ping [our Twitter](https://twitter.com/nestframework)

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
