### ISSUE TITLE
Optionally use headers to map requests

### ISSUE THREAD

**Issue by adriano-di-giovanni** [nestjs/nest#8863]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The article [Exposing CQRS Through a RESTful API](https://www.infoq.com/articles/rest-api-on-cqrs/) uses level 4 (Domain) of [Five Levels of Media Type (5LMT)](http://byterot.blogspot.co.uk/2012/12/5-levels-of-media-type-rest-csds.html) to map requests to handlers.

5LMT uses a `domain-model` key-value pair within the `Content-Type` header to tell the command the request body refers to. The NestJS versioning functionality uses a similar technique when the versioning type is [Media Type](https://docs.nestjs.com/techniques/versioning#media-type-versioning-type).

Currently, NestJS maps requests to handlers by request path and method. As far as I know, there's no mechanism to also take key-value pairs in headers into consideration but the library-specific.

### Describe the solution you'd like

The request mapping decorators, `@Get()`, `@Post()`, `@Put()`, `@Delete()`, `@Patch()`, `@Options()`, and `@Head()` could accept some sort of parameter to tell which key-value pair of which header consider.

```typescript
@Post('resource', { header: 'Content-Type', key: 'domain-model', value: 'CreateResource' })
```

### Teachability, documentation, adoption, migration strategy

The change should be backward-compatible

### What is the motivation / use case for changing the behavior?

The approach described in the article seems to me far more comprehensive than the one proposed by [@nestjs/cqrs](https://docs.nestjs.com/recipes/cqrs) because exposes CQRS through a RESTful API instead of an RPC-like API.

**Comment by micalevisk** [comment]
looks like this is related with https://github.com/nestjs/nest/issues/8441

**Comment by adriano-di-giovanni** [comment]
@micalevisk, it seems. Your contribution (thanks!) should make mapping requests according to headers possible. As far as I understand, if versioning is used to map requests it can't also be used to version the API. Correct?

**Comment by micalevisk** [comment]
I'm not sure I follow :thinking: We'll need to ping the author of the PR #8603: @adworacz

**Comment by kamilmysliwiec** [comment]
> Currently, NestJS maps requests to handlers by request path and method. As far as I know, there's no mechanism to also take key-value pairs in headers into consideration but the library-specific.

This is correct and there are no plans to implement this feature in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
