### ISSUE TITLE
Deno Support as now there is Compat Mode 

### ISSUE THREAD

**Issue by IamManchanda** [nestjs/nest#8867]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I [am](https://github.com/nestjs/nest/issues/1796) [aware](https://github.com/nestjs/nest/issues/3464) [that](https://github.com/nestjs/nest/issues/4495) [there](https://github.com/nestjs/nest/issues/4832) [are](https://github.com/nestjs/nest/issues/4876) [previously](https://github.com/nestjs/nest/issues/4963) [closed](https://github.com/nestjs/nest/issues/5183) [issues](https://github.com/nestjs/nest/issues/8421) but this is kind of a "new drum" 🥁 

Deno now has Node.js compability mode and I think that now or in near Future, it makes sense to support Deno along with Node so creating the issue ... Cheers and Happy New Year 2022 😄 🎉 🥳 

### Describe the solution you'd like

Deno Compatibility along with Node

### Teachability, documentation, adoption, migration strategy

https://deno.land/manual@v1.17.1/npm_nodejs/compatibility_mode

### What is the motivation / use case for changing the behavior?

Deno is deeply integrated with the V8 runtime and is a distributed system that allows you to run JavaScript, TypeScript, and WebAssembly close to users, at the EDGE, worldwide. It helps the Web community in it's mission to move to the "Edge"

**Comment by Tony133** [comment]
I don't think there is anything planned at the moment, as you have read in previous issues. 
I think it's also an extra work overload for the NestJS Core Team. 

This [mode](https://deno.land/manual@v1.17.1/npm_nodejs/compatibility_mode) of Deno currently does not support Typescript.
The beauty of NestJS is to use Typescript.

**Comment by jmcdo29** [comment]
It looks like you _might_ be able to build the application using the Nest CLI and then run it with deno, if you _really_ want to use Deno. Otherwise, Tony is right, there's no plans to support deno, at least from the core team's side. If someone wants to figure out how to and make a write up on it, that's fine by us.

**Comment by IamManchanda** [comment]
ohk thanks ... Cheers 🙌😇
