### ISSUE TITLE
Issue when using enableCors or setGlobalPrefix with version 8 not 7

### ISSUE THREAD

**Issue by tomavic** [nestjs/nest#8868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have installed fresh copy using the cli and followed the normal setup. The problem comes when I tried to use `app.setGlobalPrefix('api/v1');` or `app.enableCors();` when I found that the local serve has not reflected yet! I stoped the terminal and run it again and the result is the same. 

I have compared my code to a previous tutorial starter articles and videos but couldn't find anything I've mistaken for now. 

### Minimum reproduction code

https://github.com/tomavic/nestjs-backend-sample

### Steps to reproduce

I tried to use `.env` configuration too to check if the app is even reflecting to any changes, I've set the `PORT=5000` and tried to serve the app but unfortunately it served on port 3000!

### Expected behavior

configuration should be applied when I use `app.enableCors()` or `app.setGlobalPrefix`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

- ^8.0.0

### Node.js version

14.17.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

^8.0.0

**Comment by jmcdo29** [comment]
Were you using `nest start` (npm script `start`) or `nest start --watch` (npm script `start: dev`)?

**Comment by tomavic** [comment]
I was using ` npm run start:dev`

BTW, I've followed this tutorial and the sample code used in this article works awesomely fine! It's using nest@7.x but I don't believe there are braking changes between versions 7.x and 8.x that can cause this issue.

**Comment by micalevisk** [comment]
@tomavic try it again with this `nest-cli.json` instead:

```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true
  }
}
```

---

> I've set the PORT=5000 and tried to serve the app but unfortunately it served on port 3000!

It works here.

**Comment by tomavic** [comment]
Yeah that works!! However, why this is not a default config in `nest-cli.json` file?

**Comment by jmcdo29** [comment]
That should be the default behavior. I'll clone your repo later and see if anything seems weird

**Comment by tomavic** [comment]
hi @jmcdo29 did you tried out and check if my repo works?

**Comment by jmcdo29** [comment]
@tomavic I can't start your repository because it has a dependency on mongoDB and no docker-compoes to run it locally.

**Comment by tomavic** [comment]
Can you try to remove Mongo module and try to serve it please?

**Comment by jmcdo29** [comment]
Removing the `MongooseModule` and the `UsersModule`, when I start he server I can request  `api/v1` just fine (takes me to swagger). I change the `setGlobalPrefix` to `api/v2` the server restarts and I can request `api/v2` and get `Hello World` back just fine. Not sure what issue you're having.

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
