### ISSUE TITLE
Show the URL/Port being listened on when running start:dev

### ISSUE THREAD

**Issue by simplenotezy** [nestjs/nest#8869]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When initially playing around with Nest.js I was a bit confused as to what port / host the application was running on, after having run `start:dev`.

### Describe the solution you'd like

Through my experience with Next.js, Nuxt.js, Create React App and similar apps, I am used to something like this:

    Listening on http://localhost:3000 ...

After I have run e.g. `npm run start:dev`

### What is the motivation / use case for changing the behavior?

Making it easier for new and existing users to quickly navigate to your Nest.js application, by simply clicking the link in the console

**Comment by micalevisk** [comment]
for now we can use:

```ts
// main.ts
import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const logger = new Logger('bootstrap');
  await app.listen(process.env.PORT || 3000);
  logger.log(`Listening on ${await app.getUrl()}`);
}
bootstrap();
```

![image](https://user-images.githubusercontent.com/13461315/147893204-a183292f-2f13-4b58-a4f4-5feb33401ad8.png)

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
