### ISSUE TITLE
[discussion]: Requesting transporter for Redis Stream

### ISSUE THREAD

**Issue by afikrim** [nestjs/nest#8871]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

-

### Describe the solution you'd like

Add a new transporter for Redis Stream

### Teachability, documentation, adoption, migration strategy

Article related to this request,

- [Intro to Redis Stream](https://redis.io/topics/streams-intro)

### What is the motivation / use case for changing the behavior?

There are a few problems when we use Redis Pub/Sub as our message broker,
- The subscriber must be online to receive the message
- The message will be deleted after being fire
- It's kinda hard to scale service with many subscribers because it will duplicate the message

Redis Stream is a new feature in Redis v5.0. In Redis Stream, events that have already been sent will not be deleted unless it is manually deleted or when the amount of data reaches the limit. We also can use many consumers without worrying about any duplicate data by using the `XREADGROUP` command in Redis, which allow us to read the event as a group of consumer. I think it'd be great if nestjs can provide a transporter for Redis Stream.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
