### ISSUE TITLE
Scope.TRANSIENT not working when importing PinoLogger in another module

### ISSUE THREAD

**Issue by yitzchak-ben-ezra-ecoplant** [nestjs/nest#8872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Pino Logger isn't injected as `TRANSIENT` when wrapped in another `TRANSIENT` service and imported from another module
in older `nestjs` version (7.x.x) and `nestjs-pino` (1.4.0) it's injecting same `PinoLogger` instance every time even though the wrapper is injected as new instance every time.
in latest version of both it - **throws an exception** without any details

### Minimum reproduction code

https://codesandbox.io/s/github/yitzchak-ben-ezra-ecoplant/nestjs-pino-logger-issue/tree/main?file=/src/main.ts

### Steps to reproduce

1. npm install
2. npm run start:dev

### Expected behavior

PinoLogger is injected as new instance for every service
each service logs a message in construction time and a second after..
need to see that each log message shows the correct context.
on latest version we see just exception
on older version it's injected as same instance every time

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.4

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^8.2.4",
    "@nestjs/microservices": "^8.2.4",
    "@nestjs/platform-express": "^8.2.4",
    "express": "^4.17.1",
    "nestjs-pino": "^2.4.0",
    "pino-http": "^6.5.0",
    "reflect-metadata": "^0.1.13"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.1.6",
    "@nestjs/schematics": "^8.0.5",
    "@nestjs/core": "^8.2.4",
    "@nestjs/testing": "^8.2.4",
    "@types/jest": "^26.0.20",
    "prettier": "^2.5.1",
    "jest": "^26.6.3",
    "snyk": "^1.812.0",
    "typescript": "^4.5.4"
  }
}
```

### Node.js version

14.15.5

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I'm using `nestjs-pino` package version 2.4.0

**Comment by kamilmysliwiec** [comment]
Please, report this in the nestjs-pino repository.
