### ISSUE TITLE
Test.createTestingModule set a new logger even if logger is disable

### ISSUE THREAD

**Issue by HirokoMatsumoto-novade** [nestjs/nest#8875]
### Did you read the migration guide?

- [x] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

ae128f6e91e27bb59a85ebe587a8787eebc81a2c

### NestJS version

7.6.15 -> 8.2.4

### Describe the regression

Environment:
node.js v14.16.0
NestJS 8.2.4
unit test tool: jest 26.6.3

Situation:
In terms of unit test. `Test.createTestingModule` (`TestingModuleBuilder`) forcefully instantiate the logger at `this.applyLogger();`
https://github.com/nestjs/nest/commit/ae128f6e91e27bb59a85ebe587a8787eebc81a2c
We try to restrict logger during unit test for `Logger.overrideLogger([]);` at jest configuration of `setupFiles` https://jestjs.io/docs/configuration#setupfiles-array
But `this.applyLogger();` override the logger disable.

### Input code

```ts

```

### Expected behavior

If logger is already disable, it isn't set a new logger.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
