### ISSUE TITLE
 【BUG】Nest can't resolve dependencies of the UserModel (?). Please make sure that the argument DatabaseConnection at index [0] is available in the MongooseModule context.

### ISSUE THREAD

**Issue by RobinYang11** [nestjs/nest#8876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[Nest] 55837  - 2022/01/05 下午2:23:58   ERROR [ExceptionHandler] Nest can't resolve dependencies of the UserModel (?). Please make sure that the argument DatabaseConnection at index [0] is available in the MongooseModule context.

Potential solutions:
- If DatabaseConnection is a provider, is it part of the current MongooseModule?
- If DatabaseConnection is exported from a separate @Module, is that module imported within MongooseModule?
  @Module({
    imports: [ /* the Module containing DatabaseConnection */ ]
  })

Error: Nest can't resolve dependencies of the UserModel (?). Please make sure that the argument DatabaseConnection at index [0] is available in the MongooseModule context.

Potential solutions:
- If DatabaseConnection is a provider, is it part of the current MongooseModule?
- If DatabaseConnection is exported from a separate @Module, is that module imported within MongooseModule?
  @Module({
    imports: [ /* the Module containing DatabaseConnection */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:202:19)
    at Injector.resolveComponentInstance (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:157:33)
    at resolveParam (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:108:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:123:27)
    at Injector.loadInstance (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:74:9)
    at Injector.lookupComponentInImports (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:236:17)
    at Injector.lookupComponentInParentModules (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:200:33)
    at Injector.resolveComponentInstance (/Users/panzi/Desktop/git_pro/nest-mongo/node_modules/@nestjs/core/injector/injector.js:157:33)

### Minimum reproduction code

none 

### Expected behavior

mongoose work right

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

none 

### NestJS version

^8.0.0

### Packages versions

```json


{
  "name": "nest-mongo",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mongoose": "^9.0.2",
    "@nestjs/platform-express": "^8.0.0",
    "mongoose": "^6.1.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^26.0.24",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "27.0.6",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

``` typescript 
/****** AppModule ***** /

import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { UserModule } from './components/user/user.module';

@Module({
  imports: [
    MongooseModule.forRootAsync({
      connectionName: 'mongodb1',
      useFactory: () => ({
        uri: 'mongodb://10*.1*.237.******',
        user:"root",
        authSource: 'admin',
        dbName: 'panzi',
        pass: 'XXXXXX',
      }),
    }),
    UserModule
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}


 /**** UserModule.ts********* /

import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { User, UserSchema } from './entities/user.schema';
import UserController from './user.controller';
import {UserService} from './user.service';


@Module({
  imports: [
    MongooseModule.forFeature([{ name: User.name, schema: UserSchema}]),
  ],
  providers: [UserService],
  controllers: [UserController],
})
export class UserModule {}


/***** UserService.ts***********/

import { Injectable } from '@nestjs/common';
import { InjectConnection, InjectModel } from '@nestjs/mongoose';
import { Connection, Model } from 'mongoose';
import { User, UserDocument } from './entities/user.schema';

@Injectable()
export class UserService {

  constructor(
    @InjectModel(User.name) private userModel: Model<UserDocument>
    ) {}

  public async create(user: any): Promise<any> {
    const createdUser = new this.userModel(user);
    return createdUser.save();
  }
}


```

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by RobinYang11** [comment]
> 

https://github.com/RobinYang11/nset-mongo-demo

**Comment by RobinYang11** [comment]
> Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by RobinYang11** [comment]
> Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
