### ISSUE TITLE
GraphQL - empty context

### ISSUE THREAD

**Issue by hloos** [nestjs/nest#888]
@kamilmysliwiec 

In another closed issue, you mentionned:

> Another approach is to use context. You can pass a request as a context value in the graphqlExpress() function, then, access this object inside your queries/mutations/resolvers.

Unfortunately, it does seem to work for me. Here is my module configuration:

```typescript  
configure(consumer: MiddlewareConsumer) {
    const schema = this.createSchema();

    consumer
      .apply(graphqlExpress(req => {
        return ({ schema, rootValue: req, context: req });
      }))
      .forRoutes('/graphql');
  }
```

With a breakpoint, I can see for each request, `req` is correctly defined. However once in the resolver, the context become undefined.

```typescript
 @Query('game')
 @Roles('user')
 async findOneById(obj, args, context, info): Promise<GameBean | undefined> {
    const { id } = args;
    return await this.gameService.findOneById(id);
 }
```
Is this the way you suggested earlier ? Or am I missing something ?

Thanks

**Comment by hloos** [comment]
Same issue in  the sample [12-apolloserver](https://github.com/nestjs/nest/tree/master/sample/12-graphql-apollo) provided in the `sample` directory. 

`obj / context / info` are undefined in the [cats resolver](https://github.com/nestjs/nest/blob/master/sample/12-graphql-apollo/src/cats/cats.resolvers.ts)

```typescript
  @Query('cat')
  async findOneById(obj, args, context, info): Promise<Cat | undefined> {
    const { id } = args;
    return await this.catsService.findOneById(+id);
  }
```

Even after having added (in the [module](https://github.com/nestjs/nest/blob/master/sample/12-graphql-apollo/src/app.module.ts)) the req in the context:

```typescript
    consumer
      .apply(
        graphiqlExpress({
          endpointURL: '/graphql',
          subscriptionsEndpoint: `ws://localhost:3001/subscriptions`,
        }),
      )
      .forRoutes('/graphiql')
      .apply(graphqlExpress(req => ({ schema, rootValue: req, context: req })))
      .forRoutes('/graphql');
```

**Comment by hloos** [comment]
I found some weird behaviors trying to find a workaround to this issue.

Please find the detail here: [https://github.com/nestjs/graphql/issues/38](https://github.com/nestjs/graphql/issues/38)

**Comment by kamilmysliwiec** [comment]
Hi @hloos,
Thanks for investigating this issue. Let's track it here: https://github.com/nestjs/graphql/issues/38
