### ISSUE TITLE
Providers are created without need

### ISSUE THREAD

**Issue by avri87** [nestjs/nest#8882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hey, I am talking only for scope services:

I am not sure if it is by deisgn:

If you just create a provider and **not** inject it at all, then, the constructor relevant is **called**
Why dose it happen? should not it be created on **demand (injection)**? 

In angular, such thing is happening only via APP_INITIALIZED Token.

### Minimum reproduction code

Have none, just create any simple provider :)

### Expected behavior

Services should be created **only** by demand

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.5.1

### Packages versions

```json
 "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/platform-express": "^7.5.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3"
```

### Node.js version

15.8.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by micalevisk** [comment]
I believe OP is talking about this:

```ts
class Foo {
  constructor() {
    console.log('this will be called even if this instance is not used anywhere')
  }
}

@Module({
  providers: [Foo],
})
export class AppModule {}
```

I believe this is by design. I guess this is an optimization for the most common scenario: if you have registered a provider, you're pretty likely to inject it somewhere.

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
