### ISSUE TITLE
Self-injection causes the app to get stuck in the initializing process without error

### ISSUE THREAD

**Issue by mahdavipanah** [nestjs/nest#8894]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When an Injectable tries to inject itself in the constructor, the initializing process hangs without showing any error.
```javascript
import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  constructor(private readonly appService: AppService) {}
  getHello(): string {
    return 'Hello World!';
  }
}
```
App's logs:
```bash
[12:49:52 PM] File change detected. Starting incremental compilation...
api_1       | 
api_1       | [12:49:53 PM] Found 0 errors. Watching for file changes.
api_1       | 
api_1       | For help, see: https://nodejs.org/en/docs/inspector
api_1       | [Nest] 182  - 01/11/2022, 12:49:54 PM     LOG [NestFactory] Starting Nest application...
api_1       | [Nest] 182  - 01/11/2022, 12:49:54 PM     LOG [InstanceLoader] PrismaModule dependencies initialized +119ms
api_1       | [Nest] 182  - 01/11/2022, 12:49:54 PM     LOG [InstanceLoader] UsersModule dependencies initialized +2ms
```

### Minimum reproduction code

https://codesandbox.io/s/friendly-lalande-ni9oq

### Expected behavior

Nest should throw an error describing that the provider cannot inject itself.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.9

### Packages versions

```json
{
  "name": "server",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug 0.0.0.0:9229 --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^8.0.0",
    "@prisma/client": "^3.7.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.0.2",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "prisma": "^3.7.0",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
I was able to replicate this. I'll try to figure out where the exit is happening so that it can be properly reported

**Comment by kamilmysliwiec** [comment]
I'm honestly not sure if we really should provide any extra information about this particular scenario. Clearly, self-injection is impossible and should never be possible in NestJS as it just doesn't make any sense. There are many other things you could potentially do, like passing a number instead of a module to the `NestFactory.create` method and Nest won't explicitly instruct you that what you did is invalid (because it's just too obvious).

**Comment by mahdavipanah** [comment]
> I'm honestly not sure if we really should provide any extra information about this particular scenario. Clearly, self-injection is impossible and should never be possible in NestJS as it just doesn't make any sense. There are many other things you could potentially do, like passing a number instead of a module to the `NestFactory.create` method and Nest won't explicitly instruct you that what you did is invalid (because it's just too obvious).

I tested your example (passing a number to `NestFactory.create`) and I got a `TypeError` which completely makes sense:
```
[Nest] 253  - 01/17/2022, 9:45:58 AM     LOG [NestFactory] Starting Nest application...
[Nest] 253  - 01/17/2022, 9:45:58 AM   ERROR [ExceptionHandler] 
TypeError: 
    at Reflect.getMetadata (/usr/src/app/node_modules/reflect-metadata/Reflect.js:354:23)
    at DependenciesScanner.isInjectable (/usr/src/app/node_modules/@nestjs/core/scanner.js:304:26)
    at DependenciesScanner.insertModule (/usr/src/app/node_modules/@nestjs/core/scanner.js:74:18)
    at DependenciesScanner.scanForModules (/usr/src/app/node_modules/@nestjs/core/scanner.js:35:43)
    at DependenciesScanner.scan (/usr/src/app/node_modules/@nestjs/core/scanner.js:28:20)
    at /usr/src/app/node_modules/@nestjs/core/nest-factory.js:95:17
    at Function.asyncRun (/usr/src/app/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
    at NestFactoryStatic.initialize (/usr/src/app/node_modules/@nestjs/core/nest-factory.js:94:13)
    at NestFactoryStatic.create (/usr/src/app/node_modules/@nestjs/core/nest-factory.js:37:9)
    at bootstrap (/usr/src/app/src/main.ts:13:15)
```

There are lots of obvious errors that can lead to undetectable bugs. Especially in applications with numerous modules and providers and with complicated dependencies.

If your argument about the problem being obvious is accepted, then maybe we should also accept that there is no point in Nest giving an error when there is a circular dependency between two modules.

**Comment by kamilmysliwiec** [comment]
> I tested your example (passing a number to NestFactory.create) and I got a TypeError which completely makes sense:

And how descriptive is this error?

> we should also accept that there is no point in Nest giving an error when there is a circular dependency between two modules.

Well, circular dependencies are not obvious and in some edge-case scenarios are quite hard to track so I'm not sure how this relates to the problem we're discussing here.

**Comment by mahdavipanah** [comment]
> And how descriptive is this error?

I agree with you that it is not very descriptive, but it does show the source of the problem and therefore it can be fixed quickly.

> Well, circular dependencies are not obvious and in some edge-case scenarios are quite hard to track so I'm not sure how this relates to the problem we're discussing here.

I just used it as an example but I agree that it is a much more complicated issue.

**Comment by micalevisk** [comment]
> I got a `TypeError`

but AFIK this one is delegated to the runtime. It was not expected within nestjs. It just happen to throw something.

---

I do agree that nestjs should at least crash the app in that edge-case too. But if this comes with load time penalty, than something need to be changed before treating them.

**Comment by micalevisk** [comment]
After adding `console.log` around the line below, only the first pair of `console.log` is printed out even tho no errors are throwing

https://github.com/nestjs/nest/blob/521bc2b1bd4107c27a85901cf870daa194b79cc0/packages/core/injector/injector.ts#L395

and after droping the `await` below

https://github.com/nestjs/nest/blob/521bc2b1bd4107c27a85901cf870daa194b79cc0/packages/core/injector/injector.ts#L209

the app (with self-injection provider) doesn't exit anymore. This is not a solution of course.

**Comment by micalevisk** [comment]
for reference: using another token but the same class will lead to this issue as well.

```ts
class AppService {
  constructor(@Inject('Foo') appService: any) {}
}

@Module({
  providers: [
   { provide: 'Foo', useClass: AppService }
  ],
})
class AppModule {}
```

**Comment by kamilmysliwiec** [comment]
I think this is somewhat obvious. Self-injection technically makes no sense, as I've already mentioned above.
