### ISSUE TITLE
Authorization with RoleGuard when using Graphql

### ISSUE THREAD

**Issue by cavator** [nestjs/nest#8902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

executionContext.switchToHttp().getRequest()
inside Guard return null, when I hit resolver using Graphiql (GraphQL IDE)

### Minimum reproduction code
```typescript
 @Injectable()
  export class RolesGuard implements CanActivate {
    constructor(
      private readonly reflector: Reflector,
    ) {}
  
    canActivate(context: ExecutionContext): boolean {
      const requireRole = this.reflector.getAllAndOverride<Role[]>('roles', [context.getHandler(),context.getClass()])
      if (!requireRole) return true
  
      const {user} = context.switchToHttp().getRequest(); //user undefined all times
      return requireRole.some((role) => user?.role?.includes(role))
  
    }
  }
```

### Expected behavior

executionContext.switchToHttp().getRequest() should return http request data
Minimal reproduction of the problem with instructions

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

```json
{
   "@nestjs/core": "^8.0.0",
}
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other
DUPLICATED - (UNSOLVED ISSUE) https://github.com/nestjs/nest/issues/1080
I'm opening this, because don't have a proper documentation(not even a good or a complete one), and the answer in the "duplicated" issue, is useless and it's not self explanatory at all, if u will answer this, please post a full example with all necessary classes or even a git repo with the basic to do RBAC with GraphQL, i have no idea why such big framework have so poor documentation
and i know it's expected to do this, you need do some things about context to do it work, so please dont be that guy
"go here {some incomplete peace of information in NestJS doc}, and done", please exemplify, help people who like me do not understand how get the user in the context in the guard, where i need get, the flow, thinks like that, not some silly stuff, as if everyone here work in the developing of the Framework 10y like u guys

**Comment by cavator** [comment]
@jmcdo29 ok, i had already tried this solution, but i always face the problem that the "setMetaData" being called before the AuthGuard, in any way i try, i already change the orders
```typescript
  @Query(() => [User])
  @Roles(Role.USER) //equal to the docs
  @UseGuards(GraphqlJwtAuthGuard)
  async findAllUser() {
    return await this.userService.findAll()
  }
```

**Comment by jmcdo29** [comment]
The `GraphqlJwtAuthGuard` will need to be called before the `RolesGuard`. **Every** guard has a `canActivate`, that's literally the defining method of the guard. If the `GraphqlJwtGuard` is called first `gqlContext.getContext().req.user` will be populated (so long as you set up the `getRequest` of the `GraphqlJwtAuthGuard` properly) and your `RoleGuard` will be able to correct read `gqlContext.getContext().req.user` to get the roles of the user

> but i always face the problem that the "setMetaData" being called before the AuthGuard

That's fine. You can set the metadata whenever. The issue you were describing in the original post is that the `req.users` is read before it's populated

> or the problem is here? in theapp.module?

Yes, that's a global binding for a guard, and global guards are ran before local guards. This is outlined very well [in the docs](https://docs.nestjs.com/faq/request-lifecycle#guards). 

> what the work flow that I need to follow and why?

I would keep the RoleGuard global, but make the `GraphqlJwtAuthGuard` global as well [as described in the docs here](https://docs.nestjs.com/security/authentication#enable-authentication-globally) and have a decorator to set metadata to tell the `GraphqlJwtAuthGuard` to skip check the authentication of the request (if this happens the `RolesGuard` should be skipped too)

**Comment by kamilmysliwiec** [comment]
In the future, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
