### ISSUE TITLE
Referencing two collections from single collection or schema

### ISSUE THREAD

**Issue by musahibrahimali** [nestjs/nest#8903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

So i have tried to reference two collection in an API am building and for some reason one works and the other throws an error.
the code and the ide shows no signs of error but on running the error is thrown.
`import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Type, Transform } from 'class-transformer';
import { Document, ObjectId } from 'mongoose';
import * as mongoose from 'mongoose';
import { Troll } from "src/troll/schemas/troll.schema";
import { Client } from "src/client/schemas/client.schema";

export type TrollLikeModel = TrollLike & Document;

@Schema({ timestamps: true })
export class TrollLike {
    @Transform(({ value }) => value.toString())
    _id: ObjectId;

    @Prop({ required: true, type: mongoose.Schema.Types.ObjectId, ref: Client.name })
    @Type(() => Client)
    user: Client;

    @Prop({ required: true, type: mongoose.Schema.Types.ObjectId, ref: Troll.name })
    @Type(() => Troll)
    troll: Troll;
}

export const TrollLikeSchema = SchemaFactory.createForClass(TrollLike);
`
the user property works fine however the troll property isn't
if i change the ref to s string like so...
`@Prop({ required: true, type: mongoose.Schema.Types.ObjectId, ref: "Troll"})
    @Type(() => Troll)
    troll: Troll;`
then the error goes away. however i cannot populate the request above it not getting the type-safe feature.

this is the error am getting
`D:\DEV\BACKEND-FRAMEWORKS\NEST-JS\PROJECTS\alumni.backend\src\trolllike\schemas\troll.like.schema.ts:19
    @Prop({ required: true, type: mongoose.Schema.Types.ObjectId, ref: Troll.name })
                                                                             ^
TypeError: Cannot read properties of undefined (reading 'name')
    at Object.<anonymous> (D:\DEV\BACKEND-FRAMEWORKS\NEST-JS\PROJECTS\alumni.backend\src\trolllike\schemas\troll.like.schema.ts:19:78)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\DEV\BACKEND-FRAMEWORKS\NEST-JS\PROJECTS\alumni.backend\src\troll\schemas\troll.schema.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)`

### Minimum reproduction code

https://github.com/musahibrahimali/alumni.backend.nestjs

### Steps to reproduce

- yarn install
- rename the .env.example file to .env
- yarn start:dev

### Expected behavior

Commenting out the said line of code from the codes solves the issue but it would mean my program wont work
there should not be any error as with the string referencing
`[5:34:03 AM] File change detected. Starting incremental compilation...

[5:34:04 AM] Found 0 errors. Watching for file changes.

Server running on port http://localhost:5000
Swagger running on port http://localhost:5000/api
Press CTRL-C to stop server
`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/mongoose

### Packages versions

```json
```
`{
  "name": "alumni",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@casl/ability": "^5.4.3",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^1.1.6",
    "@nestjs/core": "^8.0.0",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mongoose": "^9.0.2",
    "@nestjs/passport": "^8.1.0",
    "@nestjs/platform-express": "^8.2.4",
    "@nestjs/swagger": "^5.1.5",
    "@types/passport-facebook": "^2.1.11",
    "bcrypt": "^5.0.1",
    "bl": "^5.0.0",
    "cache-manager": "^3.6.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "cookie-parser": "^1.4.6",
    "csurf": "^1.11.0",
    "dotenv": "^10.0.0",
    "helmet": "^5.0.1",
    "joi": "^17.5.0",
    "jwks-rsa": "^2.0.5",
    "mongo-gridfs": "^1.1.0",
    "mongoose": "^6.1.5",
    "multer-gridfs-storage": "^5.0.2",
    "passport": "^0.5.2",
    "passport-facebook": "^3.0.0",
    "passport-google-oauth20": "^2.0.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.1",
    "swagger-ui-express": "^4.3.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/bl": "^5.0.2",
    "@types/cache-manager": "^3.4.2",
    "@types/cookie-parser": "^1.4.2",
    "@types/dotenv": "^8.2.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.0.2",
    "@types/multer": "^1.4.7",
    "@types/node": "^17.0.8",
    "@types/passport": "^1.0.7",
    "@types/passport-google-oauth20": "^2.0.11",
    "@types/passport-jwt": "^3.0.6",
    "@types/passport-local": "^1.0.34",
    "@types/pump": "^1.1.1",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
`

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I am using the visual studio code text editor

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
