### ISSUE TITLE
[microservices]: Saga for implementing ACID in microservices pattern

### ISSUE THREAD

**Issue by vahidvdn** [nestjs/nest#8925]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In the monolith pattern, we use commit or rollback for our transactions (ACID) in order to make consistent data. This can not be done in a Microservice pattern, since we have private databases for each microservice. One of the ways to handle this is Saga. I couldn't be able to find anything related to Saga in NestJS microservices.

I asked this in Discord, but someone referred to CQRS Saga which I guess has nothing to do with what I need.

So in Saga, each transaction (Ti) has a Compensated transaction (Ci) in order to undo the transaction whenever needed.

### Describe the solution you'd like

To add support for Saga in NestJS microservices. (Or maybe any alternative solution)

### Teachability, documentation, adoption, migration strategy

https://www.youtube.com/watch?v=YPbGW3Fnmbc

### What is the motivation / use case for changing the behavior?

To have the same ACID principles in microservice pattern

**Comment by Flusinerd** [comment]
This seems interesting and I think would be a nice to have in Nestjs.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
