### ISSUE TITLE
ApplicationContext as parameter in NestFactory

### ISSUE THREAD

**Issue by stechy1** [nestjs/nest#8931]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I would like to separate startup logs from rest of the application. To configure logs correctly, I need to get ConfigService from DI.

```ts
const app = await NestFactory.create(AppModule, { bufferLogs: true });
const appLogger = app.get(Logger);
app.useLogger(appLogger);
```

This solution will put all logs (including startup) into one log. 

As discussed on discord:

> only way to get the CoinfigService from the application to use before `NestFactory.create()` would be to use a `NestFactory.createApplicationContext()` to get the `ConfigService`, **close the context, and then start the actual server**.

The issue in solution is in initialization of DI two times.

### Describe the solution you'd like

My proposal is to simply use created application context as a parameter in _create()_ method.

### Teachability, documentation, adoption, migration strategy

```ts
const context = NestFactory.createApplicationContext();
const startupLogger = context.get(StartupLogger);
const app = await NestFactory.create(AppModule, { context, logger: startupLogger });
const appLogger = app.get(Logger);
app.useLogger(appLogger);
```

### What is the motivation / use case for changing the behavior?

Be able to get any class from DI right before application itself is created.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
