### ISSUE TITLE
Accessing/using global Response object in controllers?

### ISSUE THREAD

**Issue by k-gun** [nestjs/nest#8934]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

At first, I am not sure this could be a feature request or whatever. I was just trying to use global (node/express) response object in my controllers. Although I achieve that, there are some issues with sending final response.

```
Error: Cannot set headers after they are sent to the client
  at new NodeError (node:internal/errors:371:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at ServerResponse.header (/home/kerem/dev/nestjs/foo/node_modules/@nestjs/platform-express/node_modules/express/lib/response.js:771:10)
  at ServerResponse.json (/home/kerem/dev/nestjs/foo/node_modules/@nestjs/platform-express/node_modules/express/lib/response.js:264:10)
  at ServerResponse.send (/home/kerem/dev/nestjs/foo/node_modules/@nestjs/platform-express/node_modules/express/lib/response.js:158:21)
  at /home/kerem/dev/nestjs/foo/src/util/index.ts:51:26
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The referential question is here https://stackoverflow.com/questions/70727038/nestjs-accessing-global-response-object-in-controllers. Please see it, I did not want to move all stuff here.

### Describe the solution you'd like

I would like to use the global response object in the controllers (and the request, logger objects as well) in a such a way, say.

```js
// base.controller.ts
@Controller()
export class BaseController {
  public readonly request: Request;
  public readonly response: Response;

  constructor(
    @Inject('REQUEST') request: Request,
    @Inject('RESPONSE') response: Response, // No such thing exists in deed.
  ) {
    this.request = request;
    this.response = response;
    // this.response = request.res; // I only could do thing, but causes error.
  }
}

// app.controller.ts
@Controller()
export class AppController extends BaseController {
  private readonly service: AppService;

  constructor(
    @Inject(AppService) service: AppService,
  ) {
    this.service = service;
  }

  @Get('/')
  index(): any {
    // Do whatever with this.request or this.response...
  }
}
```

### Teachability, documentation, adoption, migration strategy

I dunno.

### What is the motivation / use case for changing the behavior?

I dunno.

**Comment by jmcdo29** [comment]
> ### What is the motivation / use case for changing the behavior?

> I dunno.

I think this speaks volumes. If you don't have a motivation behind using the response this way, then why should this be added?

---

The reason the `REQUEST` is injectable, is because _sometimes_ there's use cases to use data from the request object (like headers, the user property or cookies. There's not really any information you need to grab off the response object. You might need to call a method like `set, `setCookie`, `clearCookie`, or similar. Other than that, 99 times out of 100, you should be letting Nest handle sending the response for you. The above setup doesn't make much sense, and it's erroring out because `res.send` gets called twice, once by you via `this.res.send()` and once by Nest after the end of the controller code. I don't foresee us adding in a `RESPONSE` injection token, as it would just add complexity without adding any seen value. If you want to discuss more, feel free to reach out on [Discord](https://discord.gg/nestjs)

**Comment by k-gun** [comment]
You know what guys? This simply sucks, blocking the developer from accessing Response object while allowing Request. 

```js
public sendFoo(@Req() req: Request, @Res() res: Response): Suck<ing> {
  // Do sucking logic and send sucking response...
}
```

It is not only that delighting having and being forced to do this all the time, but also simply sucks! Because eventually, I just want to send a response my sucking way to the client using that sucking Response object and to be able using it anywhere I want, he/she wants.

I am sorry if it seems a bit rude, but the only thing I just realized yet is I am soooooooo depressed trying to figure out that sucking issue after wasting my sucking hours and hours. This is so cruel...

BTW, I just realized that is not possible with Express as well. Here is its awesome error like Nest's;
```
TypeError: Cannot read properties of undefined (reading 'content-type')
  at ServerResponse.getHeader (node:_http_outgoing:597:24)
  at ServerResponse.res.get (/home/kerem/dev/js_express/node_modules/express/lib/response.js:794:15)
  at ServerResponse.send (/home/kerem/dev/js_express/node_modules/express/lib/response.js:144:17)
  at IndexController.index (/home/kerem/dev/js_express/src/controller/IndexController.ts:12:19)
  at Layer.handle [as handle_request] (/home/kerem/dev/js_express/node_modules/express/lib/router/layer.js:95:5)
  at next (/home/kerem/dev/js_express/node_modules/express/lib/router/route.js:137:13)
  at Route.dispatch (/home/kerem/dev/js_express/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/home/kerem/dev/js_express/node_modules/express/lib/router/layer.js:95:5)
  at /home/kerem/dev/js_express/node_modules/express/lib/router/index.js:281:22
  at Function.process_params (/home/kerem/dev/js_express/node_modules/express/lib/router/index.js:341:12)
```

And here is what causes;
```js
// Controller
constructor(app: Application) {
  this.app = app; // From express() stuff.
  this.request = app['request'];
  this.response = app['response'];
}

// IndexController extends Controller
public index(): void {
  this.response.send('Hello, world!\n');
}
```

Lastly, sorry for I dunno's, I really forgot I was doing at that time...
