### ISSUE TITLE
Websockets not working on iOS and Safari 

### ISSUE THREAD

**Issue by ituhin** [nestjs/nest#8941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

my websocket setup is something like this - https://docs.nestjs.com/websockets/adapter
as described in the nestjs docs using redis and socket.io

websockets works fine everywhere EXCEPT IOS on SAFARI thanks to something called - NSURLSession 

also found this similar - https://stackoverflow.com/questions/62352790/websockets-not-working-on-ios-and-safari-ossstatus-error-9837

someone mentioned additionally allowing TLSv1.2 might fix the problem. 
But I am also reading that, by default, Node JS support all the TLS protocols

So anyone faced this issue or have any suggestion ?

Thanks, any idea will be appreciated 

### Minimum reproduction code

[in the nest js doc sample](https://docs.nestjs.com/websockets/adapter)

### Expected behavior

websocket pushes should come to ios safari like other browser or os

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [X] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.0.8

### Packages versions

```json
{
"@nestjs/common": "^7.0.8",
"@nestjs/core": "^7.0.8",
"@nestjs/websockets": "^7.4.4"
"socket.io": "^2.3.0",
"socket.io-redis": "^5.4.0",
"express": "~4.17.1",
}
```

### Node.js version

14

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I guess you should report this on https://github.com/socketio/socket.io instead.

---

Also, try to not ignore the required fields in the issue form, they are there for some reason.

**Comment by kamilmysliwiec** [comment]
Please, report this issue here https://github.com/socketio/socket.io instead.
