### ISSUE TITLE
Serve graphql with existing express server

### ISSUE THREAD

**Issue by davidNHK** [nestjs/nest#8950]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have existing graphql application that written with apollo-server and koa.

now i want to migration it to NestJS because it provide architecture conventional and IoC out of box.

if i working rest API, i can migrate endpoint one by one.

but graphql only have 1 endpoint and seem i can't merge the resolver on legacy server and nestJS

### Describe the solution you'd like

I have searching / thing some existing solutions

# Apollo federation

## Pros:
- Officials solution on graphql
- V1 can auto complain schema conflict

## Cons:
- Complex setup, i need setup proxy server, legacy server, nest js which total 3 pod there
- V2 will release soon and it start with auto merging schema
- Extra setting on schema is needed
- Need remove Apollo federation after migration is done

# Fallback api call, if request can't serve on nestJS application, serve on legacy

## Pros:

- Simple config
- Nearly no action after migration done

## Cons:

- Need custom code

### Teachability, documentation, adoption, migration strategy

Above?

### What is the motivation / use case for changing the behavior?

Make migration of graphql from existing express / koa app happy.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
