### ISSUE TITLE
Axios v0.25.0 update

### ISSUE THREAD

**Issue by stephenwade** [nestjs/nest#8953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Axios has been updated to v0.25.0. Among other things, it includes a fix for a vulnerable dependency (follow-redirects).

### Expected behavior

Can we get an update to @nestjs/common and @nestjs/core with the latest version of Axios? Thanks!

### Package

- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] Other (see below)

### Other package

@nestjs/axios (https://github.com/nestjs/axios/issues/301)

### NestJS version

8.2.4

### Packages versions

```json
"@nestjs/axios": "0.0.4",
"@nestjs/common": "8.2.4",
"@nestjs/core": "8.2.4",
```

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/8956
