### ISSUE TITLE
The query handler for the "GetHeroesQuery" query was not found!

### ISSUE THREAD

**Issue by developer239** [nestjs/nest#8954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I test the run jest tests CQRS is probably not initialized and throws `The query handler for the "GetHeroesQuery" query was not found!`.

### Minimum reproduction code

https://github.com/developer239/nest-cqrs-example/tree/test/heroes-controller

### Steps to reproduce

1. `npm install`
2. `npm run test`

### Expected behavior

It should not throw `The query handler for the "GetHeroesQuery" query was not found!`.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/cqrs

### Packages versions

```json
{
  "name": "nest-cqrs-example",
  "version": "1.0.0",
  "description": "Nest CQRS module usage example",
  "license": "MIT",
  "scripts": {
    "start": "nest start --watch",
    "test": "jest"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/cqrs": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "cli-color": "^2.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.2",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.2.5",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^16.0.1",
    "jest": "^27.4.7",
    "nodemon": "^2.0.9",
    "prettier": "^2.3.2",
    "ts-jest": "^27.1.3",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node",
    "moduleNameMapper": {
      "^src/(.*)$": "<rootDir>/$1"
    }
  }
}

```

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Thank you 🙌

**Comment by developer239** [comment]
![image](https://user-images.githubusercontent.com/14946081/149971174-b8268f59-4799-4183-9c8e-776a51fa068b.png)

**Comment by semyonf** [comment]
Yeah, but why tho? Why do query handlers require you to call `init()` on the module for them to be found? Event handlers don't need that

**Comment by kamilmysliwiec** [comment]
They do need that too
