### ISSUE TITLE
Suggestion NestFastifyPlugin 

### ISSUE THREAD

**Issue by winverse** [nestjs/nest#8964]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When use fastify adapter, middleware type not matched #8837

and middleware concept is diluted in fastify

I want use fastify decorator and hooks with other provider as dependency injection

it is possible?

### Describe the solution you'd like

```javascript
// token.plugin.ts
import { NestFastifyPlugin } from '@nest/fastify-platform';
import { TokenService } from '@provider/token.service';

@Injectable()
export class TokenPlugin implements NestFastifyPlugin {
   constructor(private tokenService: TokenService) {};
   callback(fastify, option, done) {
      fastify.decorateRequest('user', null);
      fastify.addHook('preHandler', async (reqeust, reply) => {
        // do something
        // maybe get cookie from request.cookies and tokenService method call
      });

      done();
  }
}


// app.module.ts
  @Module({
    imports: [
      NestConfigModule,
      ConfigModule,
    ],
    providers: [
      {
        provide: APP_PRUGIN,
        useClass: TokenPlugin,
      },
    ],
  })
  export class AppModule {}

```

### Teachability, documentation, adoption, migration strategy

In nestjs document, write about fastify plugin as provider.

### What is the motivation / use case for changing the behavior?

a person want to do something before or after API calls using the fastify life cycle (which is different from the interceptor).

But he/she don't just use the hook
It can be used with other existing providers as dependency injection.

and the module imported in app.module.ts
so everything is alright.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions (this is already doable with Nest). We are using GitHub to track bugs, feature requests, and potential improvements.
