### ISSUE TITLE
how to use papertrail (send logs) in nest js?

### ISSUE THREAD

**Issue by naveennsit** [nestjs/nest#8973]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

is there any way to use papertrail in nestjs application ? I am added loggers like this https://docs.nestjs.com/techniques/logger

Now I want to send this logs to papertrail.. is there any way to send ?

I got the example of nodejs . but I didn't find any example of nestjs

### Describe the solution you'd like

NA

### Teachability, documentation, adoption, migration strategy

NA

### What is the motivation / use case for changing the behavior?

NA

**Comment by jmcdo29** [comment]
NestJS is a Node framework. If it works in Node, it'll work in Nest. 

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
