### ISSUE TITLE
Number Array Validation

### ISSUE THREAD

**Issue by MubasherMajeed** [nestjs/nest#8974]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have an issue during validation of number array in DTO`s. Not able to validate each element of array containing numbers.
![image](https://user-images.githubusercontent.com/46961156/150285761-7c44042b-9d56-4773-a7db-75f60f72cf51.png)

### Describe the solution you'd like

I want is like string array. which has the method @IsString( { each : true } ) to validate each element of array.
![image](https://user-images.githubusercontent.com/46961156/150285784-72b1b06b-9072-465d-8eef-8db1bc6ebfec.png)

### Teachability, documentation, adoption, migration strategy

user can use is like in string array with decorator @IsString( { each : true} ).
![image](https://user-images.githubusercontent.com/46961156/150285582-d44f0865-7485-42d7-bf21-15f771c255e0.png)

### What is the motivation / use case for changing the behavior?

With this we will be able to validate whole list elements by using one decorator and turning is each property to true. Like in array of strings.

**Comment by jmcdo29** [comment]
`@IsNumber()` comes from `class-validator` please report the error to the appropriate repository.
