### ISSUE TITLE
DI returned instance breaks inside function callback

### ISSUE THREAD

**Issue by tienshiao** [nestjs/nest#8976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { Connection } from 'typeorm';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);

  const connection = app.get(Connection);
  const result1 = await connection.query('SELECT 1');
  console.log(result1);

  setTimeout(async () => {
    const result2 = await connection.query('SELECT 2');
    console.log(result2);
  }, 1000);

  await app.close();
}
bootstrap();
```

The first query will succeed and the second query will fail. Depending on your type of database this will result in the second query throwing something like `TypeORMError: Connection is not established with mysql database` or `TypeORMError: Driver not Connected`. (Postgres). This also occurs with MikroORM. I originally encountered issue with MikroORM with Postgres while working on a command line script to process jobs from a queue. I'm pretty sure it worked at some point.

From my commit history/yarn.lock, it seems like it may have occurred when going from 8.0.x to 8.2.x. Unfortunately I was refactoring a bunch of stuff and refactored the command line script last so I did not notice right away.

This might technically be a regression from prior versions because I can drop the above code in older nestjs 5 and nestjs 7 projects and it will work (console.logs two successful queries, no errors).

### Minimum reproduction code

https://github.com/tienshiao/nestjs-typeorm-repro

### Steps to reproduce

0. `docker compose up` -- to start up the database if you don't have one handy
1. `yarn`
2. `yarn build`
3. `node dist/test.ts`

or

0. `docker compose up`
1. `yarn`
2. `./node_modules/.bin/ts-node src/test.ts`

### Expected behavior

I would expect both queries to run successfully.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.5

### Packages versions

```
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v14.18.1
YARN Version    : 1.22.10 

[Nest CLI]
Nest CLI Version : 8.2.0 

[Nest Platform Information]
platform-express version : 8.2.5
schematics version       : 8.0.5
typeorm version          : 8.0.3
testing version          : 8.2.5
common version           : 8.2.5
core version             : 8.2.5
cli version              : 8.2.0
```

### Node.js version

14.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
`app.close()` auto-terminates DB connection so receiving the `TypeORMError: Connection is not established `with mysql database or `TypeORMError: Driver not Connected` is the expected behavior.

**Comment by tienshiao** [comment]
Hrmm.. damn, that doesn't help me with my non-minimal repro as those don't use `setTimeout` or `app.close`, but I guess share the same symptoms.

**Comment by tienshiao** [comment]
Thanks, I was able to resolve my non-minimal repro with your `app.close()` pointer.

My original repro used `nestjs-console` and their documentation ( https://github.com/Pop-Code/nestjs-console/wiki/Getting-started ) references `app.close()`. I also have a `nest-commander` version and `nest-commander` internally calls `app.close()` when used with `CommandFactory.run()`. Removing the `app.close()` or using `CommandFactory.runWithoutClosing()` (which doesn't call `app.close()`) resolved the issue.

I guess `app.close()` did not previously trigger the DB connection terminations? That would probably explain why the issue doesn't come up on older versions.
