### ISSUE TITLE
Cron at specific time is not working

### ISSUE THREAD

**Issue by saito-kosuke** [nestjs/nest#8977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Cron at specific time like below is not working
`@Cron("48 21 20 1 *")`
and
``` 
 @Cron("48 21 20 1 *, {
    name: "sendEmailToAllUsers",
    timeZone: "Asia/Tokyo",
  })
```

### Minimum reproduction code

https://gist.github.com/saito-kosuke/d34e4f25f6d32cb3ab40518c3ac3b1f2

### Expected behavior

trigger cron at a specific time

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/schedule

### Packages versions

```json
[System Information]
OS Version     : macOS Big Sur
NodeJS Version : v14.18.1
YARN Version    : 1.22.0 

[Nest CLI]
Nest CLI Version : 8.1.5 

[Nest Platform Information]
class-transformer version : 0.4.0
platform-express version  : 8.2.3
class-validator version   : 0.13.3
websockets version        : 8.2.4
schematics version        : 8.0.5
passport version          : 8.0.1
schedule version          : 1.0.2
graphql version           : 9.1.2
typeorm version           : 8.0.2
testing version           : 8.2.3
common version            : 8.2.3
config version            : 1.1.5
core version              : 8.2.3
jwt version               : 8.0.0
cli version               : 8.1.5
 version                  : 1.6.0
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in this repository https://github.com/kelektiv/node-cron
