### ISSUE TITLE
@Get('*') not working

### ISSUE THREAD

**Issue by tx4x** [nestjs/nest#898]
Hi,
i am getting a 400 for a @Get('*'). I thought it's using app express but it doesn't behave like it. i tried all sort of things. 

I'd like to handle 'dynamic' routes like /vfs/mount_name/file_path_segment_a/file_path_segment_b/ ... to basically output files from a VFS. 

sorry for the newbie question,
thanks.
g

**Comment by menme95** [comment]
Why don't you use Get('/') ?

**Comment by tx4x** [comment]
that's what i tried to : 'vfs/2/test' but ends in a 404

**Comment by tx4x** [comment]
the controller setup : 
```ts

@ApiUseTags('vfs')
@ApiBearerAuth()
@Controller('/api/vfs')
```

**Comment by tx4x** [comment]
weird, got it working with @Get('/*/') 

thanks again !
