### ISSUE TITLE
Microservices: plain object thrown in BaseRpcExceptionFilter.handleUnknownError

### ISSUE THREAD

**Issue by Ginden** [nestjs/nest#8999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This line _throws_ non-error object.

https://github.com/nestjs/nest/blob/28516d739df350564eceea546dd1f58b5e9c9800/packages/microservices/exceptions/base-rpc-exception-filter.ts#L32

It took me some time to find out why and how is such object returned.

I'm still not sure _why_ it was returned, because there is no stack trace.

### Minimum reproduction code

 https://github.com/nestjs/nest/blob/28516d739df350564eceea546dd1f58b5e9c9800/packages/microservices/exceptions/base-rpc-exception-filter.ts#L32

### Expected behavior

`Error` instances are always returned from such methods. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.5

### Packages versions

```Nest CLI Version : 8.2.0 

[Nest Platform Information]
platform-express version : 8.2.5
event-emitter version    : 1.0.0
microservices version    : 8.2.5

```

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository and more details on the current vs expected behavior.

**Comment by mustafa-barakat** [comment]
This should return a string and not a json object , right ? rx expects strings

**Comment by Ginden** [comment]
> Please provide a minimum reproduction repository

It's quite hard, because without stack traces it's hard to locate how this bug happens. I will try to isolate minimum case, but it can take some time.

> more details on the current vs expected behavior.

Currently if  BaseRpcExceptionFilter handles `Error` instance, original stack trace is dropped. I expect stack traces to be preserved.

**Comment by mustafa-barakat** [comment]
@Ginden Can you try to replace
` return _throw(() => ({ status, message: errorMessage })); `
with
` return _throw(() => (errorMessage)); `

**Comment by mustafa-barakat** [comment]
I think we need to reopen this issue, the BaseRpcExceptionFilter is sending objects instead of strings.

**Comment by kamilmysliwiec** [comment]
> I think we need to reopen this issue, the BaseRpcExceptionFilter is sending objects instead of strings.

This is the expected behavior. Please, create a separate issue with a **reproducible example** that shows current vs expected behavior (and issues you've run into).
