### ISSUE TITLE
Supporting reasonml/rescript language

### ISSUE THREAD

**Issue by nodejsdeveloperskh** [nestjs/nest#9004]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Are not you tired of too much type definitions and typescript bottlenecks? I am.

### Describe the solution you'd like

So I think instead of having typescript why we do not use rescrip. Strongly typed. Fast compiler. Auto generated type definition.

### Teachability, documentation, adoption, migration strategy

I think due to the nature of rescript migration from js/ts to rescript should not be so hard. Besides I think we can have it as a separated project. Like [rescript-express](https://github.com/bloodyowl/rescript-express).

### What is the motivation / use case for changing the behavior?

Get ride of typescript bottlenecks and slow compile time. More test able and reliable codebase. Do not sticking to the Typescript, even due it is good for now.

**Comment by jmcdo29** [comment]
Please search some of our old issues. We do not plan to re-write nest in another language. It's MIT licensed, so if _you_ want to, go ahead.

**Comment by nodejsdeveloperskh** [comment]
> Please search some of our old issues. We do not plan to re-write nest in another language. It's MIT licensed, so if _you_ want to, go ahead.

No. I don't mean to rewrite nest. But now I understand that what I need is equal to rewriting nestjs. Thanks for the answer.

BTW if I could I would like to start rewriting the nest

**Comment by jmcdo29** [comment]
Like I said, if you want to rewrite it in another language, you are more than welcome to
