### ISSUE TITLE
Add option to `generate resource` with  GraphQL `Global Object Identification`

### ISSUE THREAD

**Issue by alber70g** [nestjs/nest#9005]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have an issue when I generate a resource. I don't want to have getters for each resource when I could use the Global Object Identification

### Describe the solution you'd like

I'd like the `generate resource` command to generate [Global Object Identification](https://graphql.org/learn/global-object-identification) defaults and add it to the `Node` resolver automatically

### Teachability, documentation, adoption, migration strategy

The `generate resource` could ask:

- do you want to generate boilerplate for Global Object Identification  
  (i.e. `query { node(id: "ID") { .. } })`)

### What is the motivation / use case for changing the behavior?

Discourage users from using GraphQL as a simple CRUD layer. It can be used like that, but the `query` side of the graph should have meaningful root fields, that aren't just to retrieve (R from CRUD) data.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
