### ISSUE TITLE
Participate in feature request for WebStorm to avoid Circular Dependency by smarter imports of barrel files

### ISSUE THREAD

**Issue by dantaeusb** [nestjs/nest#9006]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The problem is described well enough in this comment: https://github.com/nestjs/nest/issues/1181#issuecomment-430197191
TL;DR: Using a barrel file of the module inside the module itself causes Circular Dependency error. 

### Describe the solution you'd like

Barrel files are quite good, and I don't think we should omit them because of the problem that is, in my opinion, could be solved quite easily by the IDE.

I tried my best to explain the issue at https://youtrack.jetbrains.com/issue/WEB-54524, but I'm not really aware of the internal structure of build system, so I'd like to ask for maintainers help to describe important details of why this error happens.

If you think that I described the problem well enough or don't want to spend your time on this, I'm okay if you close the issue without any comments. 

### Teachability, documentation, adoption, migration strategy

This issue is mentioned on this page https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error in the last paragraph of first section. Bus as it's not a Nest issue, I don't think this needs to be changed. Just WebStorm uses will be able to avoid this issue by using a simple setting.

### What is the motivation / use case for changing the behavior?

 I believe for WebStorm users, this will make a big impact in Nest's ease of use and maintainability.

As I have written in the WebStorm issue, the import section of the file will be giving a very clean glance at which bundles are used (because all needed modules will be imported from the same path as @lib/auth); and which modules are not supposed to be exported by a bundle (I tend to use barrel file as a declaration of modules that I intend to expose for external use, and suppose many developers do the same) because they will use direct path like @lib/auth/service/internal.service.

**Comment by micalevisk** [comment]
sorry, I didn't understand how the IDE could solve this runtime nodejs limitation :thinking: 

```bash
├── src
│   ├── a
│   │   ├── a.module.ts
│   │   ├── a.service.ts # imports BService from '../b'
│   │   └── index.ts
│   ├── app.module.ts
│   ├── b
│   │   ├── b.module.ts
│   │   ├── b.service.ts # imports AService from '../a'
│   │   └── index.ts
│   └── main.ts
...
```

![image](https://user-images.githubusercontent.com/13461315/163443818-0c430b6e-982e-47d9-85da-8ba97cf9a3c6.png)

**Comment by dantaeusb** [comment]
Hi, I believe you misunderstood my idea. I think that IDE can have smarter auto-import, which would or would not use barrel files depending on import location and IDE settings. So for this specific case, it would use not `../a` when auto-imported, but `../a.service`.

If you think that I poorly explained my idea, please consider opening another issue or comments with better explanation.

I truly believe that this feature would be good for a lot of developers using Nestjs.

**Comment by dantaeusb** [comment]
My apologies, I edited my comment. It's not about circular dependency itself, but auto-import feature within one "bundle" (Monorepo Nestjs service/library), which is treated like circular dependency if part of "a" imports "a" through barrel file.

**Comment by jmcdo29** [comment]
> In such case, IDE should not use barrel file when import done within one path.

I agree with this, but not sure what would be required of us.

**Comment by dantaeusb** [comment]
I think that your comment and/or better explanation about core problem behind this error could make a big impact and bring this feature to live quicker, considering Nestjs popularity. If you believe there's no way you can impact that, you can dismiss this issue. I am glad that I get your attention on this, and understand if you think there's no way to impact that from the side of Nestjs team.

As I got your attention on this, I think I can close the issue, and if you have time you can discuss that or bring that up to WebStorm team somehow.

**Comment by jmcdo29** [comment]
Overall I think you've explained the issue rather well, and linked to useful resources. I don't think us weighing in would add much of an impact. It's just up to the Webstorm team to implement this
