### ISSUE TITLE
Give a way to access to the context for incoming request during the whole request life cycle without Scope.REQUEST to the avoid dependency injection bubble 

### ISSUE THREAD

**Issue by esalazarv** [nestjs/nest#9008]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm trying to add a trace id for each incoming request on a GRP micro service in order to use it in my logger service, I know that I can use an Interceptor or Guard to get the trace id from the current context if it exists or I can add one if the request does not includes it yet.

```Ts
@Injectable()
export class RequestInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
    const ctx = context.switchToRpc().getContext();
    const { debug } = ctx;
    if (!debug) {
      ctx.trace = {
        id: uuid(),
        ip: getIp(),
      };
    }
    return next.handle();
  }
}

```

After that I can inject the ExecutionContext to my logger service using `@Inject(REQUEST)`  to finally send a log with the trace id.

```Ts
import { Inject, Injectable, Logger, Scope } from '@nestjs/common';
import { WINSTON_MODULE_NEST_PROVIDER, WinstonLogger } from 'nest-winston';
import { INQUIRER, REQUEST } from '@nestjs/core';
import { RequestContextHost } from '@nestjs/microservices/context/request-context-host';

@Injectable({ scope: Scope.TRANSIENT })
export class OysterLogger {
  source: string;
  constructor(
    @Inject(REQUEST) protected request: RequestContextHost,
    @Inject(WINSTON_MODULE_NEST_PROVIDER) private logger: Logger,
    @Inject(INQUIRER) source?: string | unknown,
  ) {
    this.source = source?.constructor?.name;
    (logger as unknown as WinstonLogger).setContext(source?.constructor?.name);
  }

  log(
    message: unknown,
    payload?: Record<string, unknown>,
    ...optionalParams: unknown[]
  ): void {
    const { trace } = this.request.context;
    this.logger.log({ message, trace, ...payload }, [
      this.source,
      ...optionalParams,
    ]);
  }

 // Rest of methods ... 
}

```

And it works, but since I’m planning to use the logger service in everywhere, I think that this approach is not a good idea because it can result on a dependency injection bubble just like doc explains [scope-hierarchy](https://docs.nestjs.com/fundamentals/injection-scopes#scope-hierarchy)

For this reason I’m looking for another alternatives in order to avoid use  `Scope.REQUEST` to access to Grp context during whole request life cycle. I’ve seen that some devs are using `AsyncLocalStorage` to solve the problem and looks like a good solution but it is only working for HTTP micro services  because that approach is using Middleware as you can see on  [This website](https://blog.haroldadmin.com/posts/asynclocalstorage-logs-nestjs). 

Then I was working on a similar solution using Nest Interceptors without good results because  `AsyncLocalStorage.run` should wraps the grpc method handler and the rest of the request lifecycle in order to don’t lose the context.

### Describe the solution you'd like

I had success  with a workaround but is needs touch the [nest/server-grpc.ts](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-grpc.ts).  refactoring  `createUnaryServiceMethod ` ,  however  it can be applied on the rest of the related methods	 like `createStreamServiceMethod` ,  `createRequestStreamMethod`  and  `createStreamCallMethod` with no breaking changes.

```Ts
import {
  isObject,
  isString,
  isUndefined,
} from '@nestjs/common/utils/shared.utils';
import { EMPTY, fromEvent, lastValueFrom, Subject } from 'rxjs';
import { catchError, takeUntil } from 'rxjs/operators';
import {
  CANCEL_EVENT,
  GRPC_DEFAULT_PROTO_LOADER,
  GRPC_DEFAULT_URL,
} from '../constants';
import { GrpcMethodStreamingType } from '../decorators';
import { Transport } from '../enums';
import { InvalidGrpcPackageException } from '../errors/invalid-grpc-package.exception';
import { InvalidProtoDefinitionException } from '../errors/invalid-proto-definition.exception';
import { CustomTransportStrategy, MessageHandler } from '../interfaces';
import { GrpcOptions } from '../interfaces/microservice-configuration.interface';
import { Server } from './server';
import { ChannelOptions } from '../external/grpc-options.interface';

let grpcPackage: any = {};
let grpcProtoLoaderPackage: any = {};

interface GrpcCall<TRequest = any, TMetadata = any> {
  request: TRequest;
  metadata: TMetadata;
  sendMetadata: Function;
  end: Function;
  write: Function;
  on: Function;
  emit: Function;
}

export const EphemeralContext = new AsyncLocalStorage<Map<string, unknown>>();

export class ServerGrpc extends Server implements CustomTransportStrategy {

//  Rest of code ...

public createUnaryServiceMethod(methodHandler: Function): Function {
  return async (call: GrpcCall, callback: Function) => {
    EphemeralContext.run(new Map<string, unknown>(), () => {
      const handler = methodHandler(call.request, call.metadata, call);
      this.transformToObservable(await handler).subscribe({
        next: (data) => callback(null, data),
        error: (err: any) => callback(err),
      });
    });
  };
}

//  Rest of code ...

}
```

After that I can use  `EphemeralContext`  on my interceptor  

```Ts
import {
  CallHandler,
  ExecutionContext,
  Injectable,
  NestInterceptor,
} from '@nestjs/common';
import { Observable } from 'rxjs';
import { EphemeralContext } from '@nestjs/microservices';
import { v4 as uuid } from 'uuid';
import { getIp } from './../utils';


@Injectable()
export class RequestInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
    const ctx = context.switchToRpc().getContext();
    const { debug } = ctx;
    EphemeralContext.getStore().set('trace', {
      id: debug ? debug.id : uuid(),
      ip: getIp(),
    });
    return next.handle();
  }
}

```

And I don’t need to inject the `RequestContextHost`  using the `@Inject(REQUEST)` decorator  to my Logger Service avoiding the Dependency Injection Bubble

```Ts
import { Inject, Injectable, Logger, Scope } from '@nestjs/common';
import { WINSTON_MODULE_NEST_PROVIDER, WinstonLogger } from 'nest-winston';
import { INQUIRER } from '@nestjs/core';
import { EphemeralContext } from '@nestjs/microservices';

@Injectable({ scope: Scope.TRANSIENT })
export class OysterLogger {
  source: string;
  constructor(
    @Inject(WINSTON_MODULE_NEST_PROVIDER) private logger: Logger,
    @Inject(INQUIRER) source?: string | unknown,
  ) {
    this.source = source?.constructor?.name;
    (logger as unknown as WinstonLogger).setContext(source?.constructor?.name);
  }

 //  Rest of code ...

  log(message: unknown, payload?: Record<string, unknown>, ...optionalParams: unknown[]): void {
    const trace = ServerStore.getStore().get('trace');
      this.logger.log({ message, trace, ...payload }, [
    	this.source,
    	...optionalParams,
      ]);
  }

 //  Rest of code ...
}
```

### Teachability, documentation, adoption, migration strategy

Since It does not change the way to configure a service the only thing needed is add documentation for the new feature and a way to allow to the devs set a custom store that implement an interface from the Nest core  for the use of the EphemeralContext.

### What is the motivation / use case for changing the behavior?

Access to context  for incoming request without use `Scope.REQUEST` to avoid the Dependency Injection bubble. In my case is for logging purposes on gRPC Microservices.

I know it's a very specific use case, but I think it can be useful for other types of Nest Microservices or other purposes.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several(!) times in the past).

For further questions, use our [Discord](https://discord.gg/G7Qnnhy) channel (support).
