### ISSUE TITLE
Global Enhancers in Standalone Application

### ISSUE THREAD

**Issue by SocketSomeone** [nestjs/nest#9017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Recently, I created a [Necord ](https://github.com/SocketSomeone/necord) library for developing [discord ](https://discord.com/) bots, since they _do not use HTTP_ in most cases, so we use the [Standalone Application](https://docs.nestjs.com/standalone-applications). But to our disappointment, we found that _global enhancers_ **do not work** in **Standalone Application**. This slows development down a lot, not only for our library, but also for others that can do _without HTTP_. My library using `ExternalContextCreator`!

We have found a way around this problem and run the application without an HTTP server, but this method leaves `@nestjs/platform-express` as a dependency.

### Minimum reproduction code

https://github.com/SocketSomeone/nestjs-global-enhancers-repro

### Steps to reproduce

1. yarn install
2. yarn build
3. yarn start:standalone

You will see global guards don't work :(

```bash
LOG [AppGuard | CLASS] New event
LOG [AppGuard | METHOD] New event
LOG [AppService] New event
Done in 0.41s.
```
But if using `NestFactory.create(AppModule)` with `app.init()` you will see what Global guard works, but HTTP adapter is not running.

4. yarn start:http

```bash
LOG [AppGuard | GLOBAL] New event
LOG [AppGuard | CLASS] New event
LOG [AppGuard | METHOD] New event
LOG [AppService] New event
```

> Is it correct that we add a dependency that is not required for the functionality to work correctly?

### Expected behavior

When creating a Standalone Application, `APP_*` providers should work correctly.
Don't depend on `@nestjs/platform-express` for set global enhancers.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.6

### Packages versions

```bash
NodeJS Version : v16.13.0
YARN Version    : 1.22.17

[Nest CLI]
Nest CLI Version : 8.2.0

[Nest Platform Information]
platform-express version : 8.2.6
schematics version       : 8.0.5
common version           : 8.2.6
core version             : 8.2.6
cli version              : 8.2.0
```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

* Microsoft Windows [Version 10.0.22538.1010]
* Yarn
* WebStrorm

https://user-images.githubusercontent.com/30754373/150861437-8b770fda-1a35-463a-85eb-b79d3a6c92bc.mp4

**Comment by micalevisk** [comment]
from the docs site and looking at the interface of enhancers (guards, exception filters and interceptors), I conclude that they were designed for HTTP. I believe this won't change soon :/

**Comment by kamilmysliwiec** [comment]
@micalevisk enhancers are "transfer protocol-agnostic" so they can be used in combination with all microservices, WS gateways, GraphQL resolvers, and also (obviously) HTTP routes. To leverage enhancers in a standalone application (Nest context) then you should be using `ExternalContextCreator` that you can retrieve from the container using `app.get(ExternalContextCreator)`. Check out the `@nestjs/graphql` repository to learn how we bind enhancers to routes from within an external library.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for further questions. We are using GitHub to track bugs, feature requests, and potential improvements.
