### ISSUE TITLE
Problem document Authentication - Guard, how to print debug log Authentication in Nestjs

### ISSUE THREAD

**Issue by nhanpiti** [nestjs/nest#9037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I follow document https://docs.nestjs.com/security/authentication - setup authentication  local passport + JWT, it works great.
The problem occur at section "Enable authentication globally" (I changed "Request-scoped strategies" BTW)

@UseGuards(LocalAuthGuard)
@Post('auth/login')
async login(@Request() req) {
  return req.user;
}

This API return 401 (Document does not mention this error ?)

Carefully read the document, I see "Extending guards", the last sentence "we can allow authentication to go through a chain of strategies", so I edit 

`export class JwtAuthGuard extends AuthGuard('jwt')`
to
`export class JwtAuthGuard extends AuthGuard(['local','jwt'])`

This API now works correct.

Question:
I guest when I set JwtAuthGuard as APP_GUARD provide, it disable all other guards like LocalAuthGuard, is it correct ?
It's really hard to debug authentication, Nestjs have logs record the Req through the chain of Authentication ?

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/19-auth-jwt

### Expected behavior

The code runs exactly as document

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

"@nestjs/core": "^8.0.0"

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
