### ISSUE TITLE
Release for Axios v0.25.0 update

### ISSUE THREAD

**Issue by stephenwade** [nestjs/nest#9040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The latest Axios update has been merged. It includes a fix for a vulnerable dependency. However, I can't easily upgrade because Nest hasn't had an update since then.

### Expected behavior

Please release a patch update to NestJS with the latest dependency updates.

### Package

- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>

### NestJS version

8.2.4

### Packages versions

```json
"@nestjs/common": "8.2.4",
"@nestjs/core": "8.2.4",
```

**Comment by micalevisk** [comment]
```bash
$ npm view @nestjs/common version
8.2.6

$ grep -w axios myapp/node_modules/@nestjs/common/package.json 
    "axios": "0.24.0",
```

indeed. The current code is not in sync with the published one

https://github.com/nestjs/nest/blob/02ebd8edfbc15147c939c75bddb377817d18f271/packages/common/package.json#L3

https://github.com/nestjs/nest/blob/02ebd8edfbc15147c939c75bddb377817d18f271/packages/common/package.json#L20

**Comment by kamilmysliwiec** [comment]
A new version will be published very very shortly. Please, stay patient.
