### ISSUE TITLE
A route working in dev mode returns 404 during e2e tests with Jest

### ISSUE THREAD

**Issue by jclaveau** [nestjs/nest#9053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While running my app in dev mode I can access my / route without problem. During e2e tests, I get a 404 answer.

### Minimum reproduction code

https://github.com/jclaveau/event-sourcing-nestjs-graphql-example/tree/make_ci_working

### Steps to reproduce

docker-compose up -d
yarn
yarn test:e2e yarn test test/app.e2e

### Expected behavior

I should get a 200 answer and validate the answer body. The test suite should pass.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.4

### Packages versions

```json
{
  "name": "event-sourcing-nestjs-example",
  "version": "1.0.0",
  "description": "A sample project implementing CQRS and Event Sourcing using NestJS.",
  "author": "ArkerLabs",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "reconstruct-view-db": "ts-node -r tsconfig-paths/register src/scripts/reconstruct-view-db.ts",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "tslint -p tsconfig.json -c tslint.json",
    "test": "jest --runInBand --detectOpenHandles --forceExit",
    "test:watch": "jest --watch --runInBand --detectOpenHandles --forceExit",
    "test:cov": "jest --runInBand --detectOpenHandles --forceExit --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --runInBand --detectOpenHandles --forceExit --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@apollo/gateway": "^0.46.0",
    "@nestjs/common": "^8.2.4",
    "@nestjs/core": "^8.2.4",
    "@nestjs/cqrs": "^8.0.1",
    "@nestjs/graphql": "^9.1.2",
    "@nestjs/passport": "^8.0.1",
    "@nestjs/platform-express": "^8.2.4",
    "apollo-server-express": "^3.6.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "dotenv": "^10.0.0",
    "event-sourcing-nestjs": "^1.0.3",
    "express": "^4.17.2",
    "graphql": "^15.0.0",
    "graphql-tools": "^8.2.0",
    "jsonwebtoken": "^8.5.1",
    "nanoid": "^3.1.30",
    "passport": "^0.5.2",
    "passport-jwt": "^4.0.0",
    "redisk": "^2.0.0",
    "redisk-nestjs": "^1.0.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^7.5.1",
    "ts-morph": "^13.0.3",
    "webpack": "^5.67.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.1.6",
    "@nestjs/schematics": "^8.0.5",
    "@nestjs/testing": "^8.2.4",
    "@types/express": "^4.17.1",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "@types/supertest": "^2.0.8",
    "jest": "^27.4.7",
    "prettier": "^2.5.1",
    "supertest": "^6.1.6",
    "ts-jest": "^27.1.2",
    "ts-loader": "^9.2.6",
    "ts-mockito": "^2.5.0",
    "ts-node": "^10.4.0",
    "tsconfig-paths": "^3.9.0",
    "tslint": "^6.1.3",
    "typescript": "^4.5.4"
  },
  "jest": {
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "./",
    "modulePaths": [
      "<rootDir>"
    ],
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node",
    "verbose": true,
    "moduleNameMapper": {
      "src/(.*)": "<rootDir>/src/$1"
    }
  }
}

```

### Node.js version

14.18.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other
- A test run is available here: https://github.com/jclaveau/event-sourcing-nestjs-graphql-example/runs/4991653898?check_suite_focus=true

- I dumped the routes during my test and I get an empty array (logged in the test)

- I found a similar issue closed due to use case repository missing: https://github.com/nestjs/nest/issues/4269

- I also had to change `const req = request(app.getHttpServer())` to  `const req = request.default(app.getHttpServer())` to make it work which has not been updated in your docs: https://docs.nestjs.com/fundamentals/testing#end-to-end-testing

Thanks a lot for your work!

**Comment by micalevisk** [comment]
here:

![image](https://user-images.githubusercontent.com/13461315/151666776-cd6c9081-a042-4dc3-8b27-e4ea9dfce136.png)

you're using `AppModule` as a static module, while the controller is defined only here:

![image](https://user-images.githubusercontent.com/13461315/151666783-d0092e6f-3519-4ddd-bfb2-2800af89b623.png)

Thus change that line to `imports: [ AppModule.forRoot() ]`

**Comment by jclaveau** [comment]
Thank you very much for this fast and accurate answer! It solved my issue.

It's probably not directly related but I had the same error as the one described here afterwards: https://stackoverflow.com/questions/61356672/error-when-i-try-to-test-with-nestjs-jest-and-graphqlfederationmodule

The user found a fix but never understood what was happening. If you ever understand why it could improve the Nest / Jest / Graphql knowledge base.

Thank you very much!
