### ISSUE TITLE
Jest never ends during e2e tests despite all passing tests and app.close() during afterAll

### ISSUE THREAD

**Issue by jclaveau** [nestjs/nest#9066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I run my tests, my assertions pass with success but Jest fails throwing 
```
thrown: "Exceeded timeout of 5000 ms for a test.
```

### Minimum reproduction code

https://github.com/jclaveau/nestjs-geteventstore/blob/e2e_tests_for_example/examples/test/app.e2e-spec.ts

### Steps to reproduce

1. docker-compose up -d
2. `yarn install`
3. `cd examples`
4. `yarn install` // this will probably change soon
5. yarn test:e2e  // Which is `jest --runInBand --detectOpenHandles --forceExit`

You can also simply check the result here: https://github.com/jclaveau/nestjs-geteventstore/runs/4998083180?check_suite_focus=true

### Expected behavior

The tests should succeed

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.6.7

### Packages versions

```json
{
  "name": "nest-cqrs-example",
  "version": "1.0.0",
  "description": "Nest CQRS module usage example",
  "license": "MIT",
  "scripts": {
    "postinstall": "link-module-alias",
    "start": "yarn start:heroes:cqrs:eventstore",
    "start:heroes:cqrs:eventstore": "ts-node-dev src/bin/runner.ts",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:e2e": "jest --runInBand --detectOpenHandles --forceExit"
  },
  "_moduleAliases": {
    "~nestjs-geteventstore": "../src"
  },
  "dependencies": {
    "@eventstore/db-client": "^2",
    "@godaddy/terminus": "^4.4.1",
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/cqrs": "^7.0.1",
    "@nestjs/platform-express": "^6.0.0",
    "@nestjs/terminus": "^7.0.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "cli-color": "^1.4.0",
    "global": "^4.4.0",
    "nestjs-context": "^0.12.0",
    "nestjs-geteventstore": "^1.6.0",
    "nestjs-pino-stackdriver": "^2.1.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.0.0"
  },
  "devDependencies": {
    "@compodoc/compodoc": "^1.1.11",
    "@nestjs/testing": "^7",
    "@types/express": "^4.16.1",
    "@types/jest": "^27.4.0",
    "@types/node": "^11.9.4",
    "@typescript-eslint/eslint-plugin": "^4.28.4",
    "@typescript-eslint/parser": "^4.28.4",
    "dot-prop": ">=4.2.1",
    "eslint": "^7.31.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jest": "^24.4.0",
    "eslint-plugin-local": "^1.0.0",
    "jest": "^27.4.7",
    "link-module-alias": "^1.2.0",
    "nodemon": "^1.18.10",
    "prettier": "^1.12.1",
    "serialize-javascript": ">=3.1.0",
    "start-server-webpack-plugin": "^2.2.5",
    "supertest": "^6.2.2",
    "ts-jest": "^27.1.3",
    "ts-loader": "^7.0.4",
    "ts-node": "^8.0.2",
    "ts-node-dev": "^1.1.6",
    "typescript": "^4.3.4",
    "webpack": "^4.43.0",
    "webpack-node-externals": "^1.7.2"
  }
}
```

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

- I wonder it comes from this async registration of a dynamic module but I still don't get enough all the process of Nest to know what I say: https://github.com/jclaveau/nestjs-geteventstore/blob/e2e_tests_for_example/src/event-store/event-store.module.ts#L25-L31
- The app works perfectly while `yarn start` so it creates a delta between e2e testing and user experience which is exactly what we do not want (as much as possible). Also this seems kind of tricky to fix alone so I considered it could be interesting to share it as a bug even if it may come from me or the developers of the repo I'm patching (I searched a lot before posting). Hoping I'm right

Anyway, thank you very much for your work!

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
