### ISSUE TITLE
Missing swagger dto

### ISSUE THREAD

**Issue by techandmedia** [nestjs/nest#9070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Empty DTO in Swagger API when using class-validator in a DTO Class

![151652983-5f3f2a60-1d12-4f58-a3ca-d71ce70898d7](https://user-images.githubusercontent.com/15700861/151798983-cb9aeb46-102f-4ea2-8df8-6efa0cead161.jpg)

### Minimum reproduction code

https://github.com/techandmedia/nest-swagger

### Expected behavior

Removing the class-validator to make the DTO appear

![151653011-36f757a1-9f5f-4adf-b968-e0c06c642a8d](https://user-images.githubusercontent.com/15700861/151799098-20aaf02a-cf3c-4f49-bbe4-62084bc66cbd.jpg)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

8.2.6

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "8.2.6",
    "@nestjs/core": "8.2.6",
    "@nestjs/platform-express": "8.2.6",
    "@nestjs/swagger": "5.2.0",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.5.2",
    "swagger-ui-express": "4.3.0"
  },
  "devDependencies": {
    "@nestjs/cli": "8.2.0",
    "@nestjs/schematics": "8.0.5",
    "@nestjs/testing": "8.2.6",
    "@types/express": "4.17.13",
    "@types/node": "17.0.13",
    "@types/supertest": "2.0.11",
    "@typescript-eslint/eslint-plugin": "5.10.1",
    "@typescript-eslint/parser": "5.10.1",
    "eslint": "8.8.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-import": "2.25.4",
    "jest": "27.4.7",
    "prettier": "2.5.1",
    "supertest": "6.2.2",
    "ts-jest": "27.1.3",
    "ts-loader": "9.2.6",
    "ts-node": "10.4.0",
    "tsconfig-paths": "3.12.0",
    "typescript": "4.5.5"
  }
```

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Cannot reproduce. I cloned your repo, installed deps, ran `start:dev` and went to the swagger page and saw everything as expected. Try clearing your browser cache or possibly removing the `dist` and recompiling your code.
