### ISSUE TITLE
HTTP server with errors on kubernetes

### ISSUE THREAD

**Issue by diegolisboajj** [nestjs/nest#9088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm having trouble running getHttpServer on NestJs runs

`
  const server = app.getHttpServer();
  console.debug('server:', app);
`

today I have 2 environments to climb the nest in kubernetes pod , and both YAML from docker deploys are identical,  in one when running the cod I get this following

`server:<ref *1> Server {
  maxHeaderSize: undefined,
  insecureHTTPParser: undefined,
  _events: [Object: null prototype] {
    request: [Function (anonymous)] {
      listener: [Function],
      [Symbol(DynatraceEmbeddedData)]: [Object: null prototype]
    },
    connection: [Function: connectionListener]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  _connections: 0,
  _handle: TCP {
    reading: false,
    onconnection: [Function: onconnection],
    [Symbol(owner_symbol)]: [Circular *1]
  },
  _usingWorkers: false,
  _workers: [],
  _unref: false,
  allowHalfOpen: true,
  pauseOnConnect: false,
  httpAllowHalfOpen: false,
  timeout: 0,
  keepAliveTimeout: 5000,
  maxHeadersCount: null,
  headersTimeout: 60000,
  requestTimeout: 0,
  _connectionKey: '6::::5021',
  [Symbol(IncomingMessage)]: [Function: IncomingMessage],
  [Symbol(ServerResponse)]: [Function: ServerResponse],
  [Symbol(kCapture)]: false,
  [Symbol(async_id_symbol)]: 6937
}`

and the POD that mounts the HTTP server returns me everything correct

`server:<ref *1> Server {
  maxHeaderSize: undefined,
  insecureHTTPParser: undefined,
  _events: [Object: null prototype] {
    request: [Function: app] {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      setMaxListeners: [Function: setMaxListeners],
      getMaxListeners: [Function: getMaxListeners],
      emit: [Function: emit],
      addListener: [Function: addListener],
      on: [Function: addListener],
      prependListener: [Function: prependListener],
      once: [Function: once],
      prependOnceListener: [Function: prependOnceListener],
      removeListener: [Function: removeListener],
      off: [Function: removeListener],
      removeAllListeners: [Function: removeAllListeners],
      listeners: [Function: listeners],
      rawListeners: [Function: rawListeners],
      listenerCount: [Function: listenerCount],
      eventNames: [Function: eventNames],
      init: [Function: init],
      defaultConfiguration: [Function: defaultConfiguration],
      lazyrouter: [Function: lazyrouter],
      handle: [Function: handle],
      use: [Function: use],
      route: [Function: route],
      engine: [Function: engine],
      param: [Function: param],
      set: [Function: set],
      path: [Function: path],
      enabled: [Function: enabled],
      disabled: [Function: disabled],
      enable: [Function: enable],
      disable: [Function: disable],
      acl: [Function (anonymous)],
      bind: [Function (anonymous)],
      checkout: [Function (anonymous)],
      connect: [Function (anonymous)],
      copy: [Function (anonymous)],
      delete: [Function (anonymous)],
      get: [Function (anonymous)],
      head: [Function (anonymous)],
      link: [Function (anonymous)],
      lock: [Function (anonymous)],
      'm-search': [Function (anonymous)],
      merge: [Function (anonymous)],
      mkactivity: [Function (anonymous)],
      mkcalendar: [Function (anonymous)],
      mkcol: [Function (anonymous)],
      move: [Function (anonymous)],
      notify: [Function (anonymous)],
      options: [Function (anonymous)],
      patch: [Function (anonymous)],
      post: [Function (anonymous)],
      pri: [Function (anonymous)],
      propfind: [Function (anonymous)],
      proppatch: [Function (anonymous)],
      purge: [Function (anonymous)],
      put: [Function (anonymous)],
      rebind: [Function (anonymous)],
      report: [Function (anonymous)],
      search: [Function (anonymous)],
      source: [Function (anonymous)],
      subscribe: [Function (anonymous)],
      trace: [Function (anonymous)],
      unbind: [Function (anonymous)],
      unlink: [Function (anonymous)],
      unlock: [Function (anonymous)],
      unsubscribe: [Function (anonymous)],
      all: [Function: all],
      del: [Function (anonymous)],
      render: [Function: render],
      listen: [Function: listen],
      request: [IncomingMessage],
      response: [ServerResponse],
      cache: {},
      engines: {},
      settings: [Object],
      locals: [Object: null prototype],
      mountpath: '/',
      _router: [Function]
    },
    connection: [Function: connectionListener]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  _connections: 0,
  _handle: TCP {
    reading: false,
    onconnection: [Function: onconnection],
    [Symbol(owner_symbol)]: [Circular *1]
  },
  _usingWorkers: false,
  _workers: [],
  _unref: false,
  allowHalfOpen: true,
  pauseOnConnect: false,
  httpAllowHalfOpen: false,
  timeout: 0,
  keepAliveTimeout: 5000,
  maxHeadersCount: null,
  headersTimeout: 60000,
  requestTimeout: 0,
  _connectionKey: '6::::5021',
  [Symbol(IncomingMessage)]: [Function: IncomingMessage],
  [Symbol(ServerResponse)]: [Function: ServerResponse],
  [Symbol(kCapture)]: false,
  [Symbol(async_id_symbol)]: 86
}`

Has anyone seen this situation? I have this problem because I had routes that worked and others show 404, one HTTP server goes up correctly and another one doesn't show most definitions

### Minimum reproduction code

github.com/diegolisboajj

### Expected behavior

The sames POD up with same server HTTP

package.json

`"dependencies": {
    "aws-sdk": "^2.1038.0",
    "base64url": "^3.0.1",
    "bcrypt": "^5.0.1",
    "cache-manager": "^3.3.0",
    "cache-manager-ioredis": "^2.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.1",
    "elasticsearch": "^16.7.2",
    "express-list-routes": "^1.1.3",
    "jwt-decode": "^3.1.2",
    "keycloak-connect": "15.0.2",
    "migrate": "^1.7.0",
    "mongoose": "^6.0.13",
    "mongoose-unique-validator": "^3.0.0",
    "nest-keycloak-connect": "^1.7.6",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "querystring-ts": "^1.0.1",
    "redis-commands": "^1.6.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.3.0",
    "winston": "^3.3.3"
  },
  "description": "",
  "devDependencies": {
    "@golevelup/ts-jest": "^0.3.2",
    "@keycloak/keycloak-admin-client": "^15.0.2",
    "@nestjs/axios": "0.0.2",
    "@nestjs/common": "^8.0.6",
    "@nestjs/config": "^1.0.2",
    "@nestjs/core": "^8.0.6",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mongoose": "^9.0.1",
    "@nestjs/passport": "^8.0.1",
    "@nestjs/platform-express": "^8.0.6",
    "@nestjs/swagger": "^5.1.5",
    "@nestjs/terminus": "^8.0.1",
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/cache-manager": "^2.10.3",
    "@types/cache-manager-ioredis": "^2.0.1",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.1",
    "@types/mongoose": "^5.11.97",
    "@types/mongoose-unique-validator": "^1.0.5",
    "@types/node": "^16.0.0",
    "@types/passport": "^1.0.7",
    "@types/passport-jwt": "^3.0.6",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^27.0.6",
    "jest-sonar-reporter": "^2.0.0",
    "prettier": "2.4.1",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },`

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

{
  "author": "",
  "dependencies": {
    "aws-sdk": "^2.1038.0",
    "base64url": "^3.0.1",
    "bcrypt": "^5.0.1",
    "cache-manager": "^3.3.0",
    "cache-manager-ioredis": "^2.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.1",
    "elasticsearch": "^16.7.2",
    "express-list-routes": "^1.1.3",
    "jwt-decode": "^3.1.2",
    "keycloak-connect": "15.0.2",
    "migrate": "^1.7.0",
    "mongoose": "^6.0.13",
    "mongoose-unique-validator": "^3.0.0",
    "nest-keycloak-connect": "^1.7.6",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "querystring-ts": "^1.0.1",
    "redis-commands": "^1.6.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.3.0",
    "winston": "^3.3.3"
  },
  "description": "",
  "devDependencies": {
    "@golevelup/ts-jest": "^0.3.2",
    "@keycloak/keycloak-admin-client": "^15.0.2",
    "@nestjs/axios": "0.0.2",
    "@nestjs/common": "^8.0.6",
    "@nestjs/config": "^1.0.2",
    "@nestjs/core": "^8.0.6",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mongoose": "^9.0.1",
    "@nestjs/passport": "^8.0.1",
    "@nestjs/platform-express": "^8.0.6",
    "@nestjs/swagger": "^5.1.5",
    "@nestjs/terminus": "^8.0.1",
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/cache-manager": "^2.10.3",
    "@types/cache-manager-ioredis": "^2.0.1",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.1",
    "@types/mongoose": "^5.11.97",
    "@types/mongoose-unique-validator": "^1.0.5",
    "@types/node": "^16.0.0",
    "@types/passport": "^1.0.7",
    "@types/passport-jwt": "^3.0.6",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^27.0.6",
    "jest-sonar-reporter": "^2.0.0",
    "prettier": "2.4.1",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "engines": {
    "node": ">=14 <=15"
  },
  "license": "MIT",
  "scripts": {
    "build": "nest build",
    "build:shared": "yarn --cwd ../shared build",
    "format": "prettier --write \"src/**/*.ts\"",
    "lint": "eslint \"src/**/*.ts\" --fix",
    "prebuild": "rimraf bin",
    "prepare": "husky install",
    "start:dev": "yarn build:shared && nest start --debug 0.0.0.0:5870 tsc --watch  \"../shared/src/index.ts\" ",
    "start:prd": "node ./bin/main.js",
    "test": "jest --config jest.config.json --no-cache --maxWorkers=50%",
    "test:coverage": "jest --coverage --config jest.config.json --no-cache && xdg-open ./coverage/lcov-report/index.html",
    "test:e2e": "jest --config ./jest-e2e.ts",
    "clean": "ttsc --build --clean && concurrently -r \"yarn clean:d.ts\" \"yarn clean:js.map\" \"yarn clean:js\" ",
    "clean:d.ts": "find ./src/*[!@types]* -name \"*.d.ts\" -exec rm {} \\;",
    "clean:js.map": "find ./src/*[!@types]* -name \"*.js.map\" -exec rm {} \\;",
    "clean:js": "find ./src/*[!@types]* -name \"*.js\" -exec rm {} \\;",
    "db:migrate": "yarn migrate:up",
    "migrate:create": "migrate create --template-file ./src/migrations-utils/template.ts --migrations-dir=\"./src/migrations\" --compiler=\"ts:./src/migrations-utils/ts-compiler.js\"",
    "migrate:up": "migrate --migrations-dir=\"./src/migrations\" --compiler=\"ts:./src/migrations-utils/ts-compiler.js\" up",
    "migrate:down": "migrate --migrations-dir=\"./src/migrations\" --compiler=\"ts:./src/migrations-utils/ts-compiler.js\" down"
  },
  "version": "0.0.1"
}

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
