### ISSUE TITLE
Interceptor post-controller logic happens when injecting `@Res()`

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#9089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using `@Res()` in a controller's route handler, an interceptor's post-controller logic (inside the RxJS pipe of `next.handle()`) still executes. The reason this came up is an [issue from my ogma logger and interceptor](https://github.com/jmcdo29/ogma/issues/1101).  

### Minimum reproduction code

https://github.com/jmcdo29/post-controller-interceptor-bug

### Steps to reproduce

1 `npm ci`
2 `npm run start:dev`
3 in a separate terminal `curl http://localhost:3000`

### Expected behavior

Even if `@Res()` is used in a controller, unless the `{ passthrough: true }` option is set, the interceptor's post-controller logic is not executed.

I know that generally using `@Res()` is discouraged, and this particular issue can be avoided by using `return` **not** on the `res` object, but I still found it curious that the logic still executes. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.6

### Packages versions

```text
[System Information]
OS Version     : Linux 5.15
NodeJS Version : v16.13.0
PNPM Version    : 6.25.1

[Nest CLI]
Nest CLI Version : 8.2.0

[Nest Platform Information]
platform-express version : 8.2.6
schematics version       : 8.0.5
testing version          : 8.2.6
common version           : 8.2.6
core version             : 8.2.6
cli version              : 8.2.0
```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
> When using @Res() in a controller's route handler, an interceptor's post-controller logic (inside the RxJS pipe of next.handle()) still executes. 

This is actually intentional 😅  In your interceptor, you can check if the response was already sent using `response.headersSent` flag.

**Comment by jmcdo29** [comment]
Oh interesting! The culprit I found was from `JSON.stringify()` on the `Express.Response` causes some headers to get set. 

We should probably update the docs then to make it clear that the post-controller logic **does** happen, but doesn't effect the response
