### ISSUE TITLE
How to test a function that has a Promise in its own? 

### ISSUE THREAD

**Issue by danieltadresu** [nestjs/nest#9092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a function that returns a value that i get when i call a Promise. This Promise  resolves with data and this data is returned by my function that i want to test.

```
async retrieveSecurityToken(): Promise<any> {
    let endpoint = this.configService.get<string>("SECURITY_URI");
    endpoint = endpoint ? endpoint.replace("?wsdl", "") : null;
    const result = new Promise((resolve, reject) => {
      this.securitySoapClient.RetrieveSecurityToken(
        {
          RetrieveSecurityTokenRequest: {
            CarrierCodes: { CarrierCode: { AccessibleCarrierCode: "dummy" } },
            LogonID: "dummy",
            Password: "dummy",
          },
        },
        function (err, result) {
          if (err) return reject(err);
          resolve(result);
        }
      );
    });
    const data: RetrieveSecurityTokenDTO = await result;
    if (!data.RetrieveSecurityTokenResult.SecurityToken)
      throw new Error("No se pudo obtener el token");
    return { SecurityToken: data.RetrieveSecurityTokenResult.SecurityToken };
  }
```

I'm trying to test my **retrieveSecurityToken** function.

```
it("my unit test", async () => {
    const obj = {
      id: 1,
    };
    const response = await securityClient.retrieveSecurityToken();
    expect(obj).toEqual(response);
  });
```

But i get this error:

![Captura de Pantalla 2022-02-02 a la(s) 21 43 20](https://user-images.githubusercontent.com/63379296/152262036-8c07ab6e-deb1-451c-9976-6a86bc278d45.png)

How can i test my function that returns a value got from a promise?

Thanks a lot!

### Minimum reproduction code

https://github.com/danieltadresu/burger-app

### Steps to reproduce

1. npm install
2. npm run start:dev

### Expected behavior

I expect to test my function that returns a value got from a Promise (callback)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.3

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
