### ISSUE TITLE
IIFE for bootstrap

### ISSUE THREAD

**Issue by HelloMinchan** [nestjs/nest#9094]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

-

### Describe the solution you'd like

First of all, Thank you for creating a best framework, NestJS.

In my opinion, How about change bootstrap function to IIFE?
* before
```
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe());

  await app.listen(3000);
  console.log(`Application is running on: ${await app.getUrl()}`);
}
bootstrap();
```

* after
```
(async function () {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe());

  await app.listen(3000);
  console.log(`Application is running on: ${await app.getUrl()}`);
})();
```

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

There's no remarkable differences. 😂
But I think, IIFE better than before.

Firstly, bootstrap is not used after the declaration.
Secondly, can have the advantage of IIFE. (name collision prevention, clean global scope, and so on.)
Finally, it looks simple and cool.

**Comment by micalevisk** [comment]
I prefer not having an IIFE because we could handle exceptions on `bootstrap`, and doing  
`bootstrap.catch(...)` is more readable to me.

**Comment by HelloMinchan** [comment]
Oh, I got it. Thank you for your reply.
