### ISSUE TITLE
Nest can't resolve dependencies when import module from index.ts.

### ISSUE THREAD

**Issue by GO-DIE** [nestjs/nest#9095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Nest can't resolve dependencies when import module from index.ts.

index.ts:
![image](https://user-images.githubusercontent.com/38709773/152396284-d79a93d2-ce0a-4633-a7a1-f984915eb3aa.png)

error:
![image](https://user-images.githubusercontent.com/38709773/152395219-64ec1df7-195b-4cf1-ad61-9fb1b03a056f.png)

### Minimum reproduction code

https://github.com/GO-DIE/nestjs.git

### Steps to reproduce

git clone https://github.com/GO-DIE/nestjs.git
npm i
npm run start:dev

error:
![image](https://user-images.githubusercontent.com/38709773/152395219-64ec1df7-195b-4cf1-ad61-9fb1b03a056f.png)

### Expected behavior

normal operation!

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "nest",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prepare": "husky install",
    "format": "prettier --write \"{src,test}/**/*.ts\" \"**/*.+(json|yaml)\"",
    "lint": "eslint \"{src,test}/**/*.ts\" --fix",
    "prebuild": "rimraf dist",
    "build": "nest build",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.0.2",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5",
    "@commitlint/cli": "^16.1.0",
    "@commitlint/config-angular": "^16.0.0",
    "husky": "^7.0.4",
    "lint-staged": "^12.3.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

16.0.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
https://github.com/nestjs/nest/issues/7290#issuecomment-866568498

https://github.com/nestjs/nest/issues/1181#issuecomment-430037003

**Comment by jeanbmar** [comment]
Generally speaking you should never import a module when you are already inside the module. It's a guaranteed circular dependency.
Import the file instead.

`import { DemoService } from './demo.service';`

**Comment by jmcdo29** [comment]
Thanks guys. @GO-DIE if you're still in need of support please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
