### ISSUE TITLE
NATS EventPattern return the data.

### ISSUE THREAD

**Issue by zlooun** [nestjs/nest#9096]
@borovik96 
The bug is still present. If you send a request from one microservice that is waiting for a response to another, which is just subscribed to this event and is not going to send a response. It will still send "nothing" and it will break the first microservice.
1 microservice (that send the request):
![image](https://user-images.githubusercontent.com/50909481/152400023-b6c2251a-b6ff-4473-81cb-32d84b333b9f.png)
2 microservice (that just want to get data):
![image](https://user-images.githubusercontent.com/50909481/152399806-fb078bfe-5e55-4576-a870-155f6d43c843.png)
3 microservice (who must to reply):
![image](https://user-images.githubusercontent.com/50909481/152400173-aaed6b39-0aef-46b0-8471-184ef5114976.png)

The error (because the second microservice send reply, but it shouldn't to do it):
![image](https://user-images.githubusercontent.com/50909481/152400246-d7a55251-39d7-45d3-913a-e824793598b9.png)

_Originally posted by @zlooun in https://github.com/nestjs/nest/issues/4874#issuecomment-1029249347_

**Comment by jmcdo29** [comment]
Closing in favor of #9097
