### ISSUE TITLE
NATS EventPattern return the data.

### ISSUE THREAD

**Issue by zlooun** [nestjs/nest#9097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you send a request from one microservice that is waiting for a response to another, which is just subscribed to this event and is not going to send a response. It will still send "nothing" and it will break the first microservice.
1 microservice (that send the request):
![image](https://user-images.githubusercontent.com/50909481/152400023-b6c2251a-b6ff-4473-81cb-32d84b333b9f.png)
2 microservice (that just want to get data):
![image](https://user-images.githubusercontent.com/50909481/152399806-fb078bfe-5e55-4576-a870-155f6d43c843.png)
3 microservice (who must reply):
![image](https://user-images.githubusercontent.com/50909481/152400173-aaed6b39-0aef-46b0-8471-184ef5114976.png)

The error (because the second microservice send reply, but it shouldn't to do it):
![image](https://user-images.githubusercontent.com/50909481/152400246-d7a55251-39d7-45d3-913a-e824793598b9.png)

### Minimum reproduction code

https://github.com/zlooun/nats-eventpattern-return-the-data

### Expected behavior

EventPattern shouldn't reply anything.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

```json

```
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/microservices": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "nats": "^2.6.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by zlooun** [comment]
> Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

5 minutes

**Comment by zlooun** [comment]
> Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

Done

**Comment by kamilmysliwiec** [comment]
You can't use the same "pattern" (`notifications.qwe`) for both message and event handlers. This isn't supported by NATS.
