### ISSUE TITLE
You can't use the same "pattern" (`notifications.qwe`) for both message and event handlers. This isn't supported by NATS.

### ISSUE THREAD

**Issue by zlooun** [nestjs/nest#9102]
Have you locked the conversation so that something cannot be opposed?

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/9097#issuecomment-1029740738_
> You can't use the same "pattern" (`notifications.qwe`) for both message and event handlers. This isn't supported by NATS.

**No, you can**. Nats accepts the very first response, and discards the rest. So you can subscribe to request/reply in order to simply get information and not have to respond. And I implemented it with the help of the Nats client.

**Read the documentation:**
https://docs.nats.io/nats-concepts/core-nats/reqreply

**Comment by kamilmysliwiec** [comment]
Well, let me reformulate my original message as it was poorly written.

You can't use the same "pattern" (notifications.qwe) for both message and event handlers. This isn't supported by NATS **transport strategy (NestJS implementation)**. There are currently no plans to change this.
