### ISSUE TITLE
Module IoC lifetime options and data passing

### ISSUE THREAD

**Issue by Falven** [nestjs/nest#9106]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

_**IoC Terms**_
- _**transient**: transient modules are always different instances. Whenever a transient module gets imported, it's lifetime is bound to its parent module, and it cannot be shared with other modules outside of the parent module's context._
- _**singleton**: a singleton module is a shared instance. Whenever a module imports a singleton module, they get the same instance that other modules are importing as well._
- _**injection token**: an identifier (type, string, or other) used to retrieve singleton modules._

Currently, it is very tedious to create transient or singleton module behavior in nest. Couple this with trying to pass data into your module and you have a spaghetti dish of boilerplate code.

### Creating singleton modules
By default, modules are singleton with the injection token being the module type passed into the imports array.
```typescript
@Module({ providers: [ ... ], exports: [ ... ] })
export class SingletonModule {}

// AppModule will import a shared instance of SingletonModule.
@Module({ imports: [ SingletonModule ] })
export class AppModule {}
```

### Creating transient modules:
In order to create a transient module, some obscure, under-documented, pattern involving a `register`, `forRoot` or `forFeature` function that returns a `DynamicModule` has to be implemented. More details on these patterns [here](https://dev.to/nestjs/advanced-nestjs-how-to-build-completely-dynamic-nestjs-modules-1370) and [here](https://stackoverflow.com/questions/70946854/nestjs-dynamic-module-ioc-scope).
```typescript
@Module({})
export class TransientModule{
  // or forRoot(...), or forFeature(...)
  static register(...): DynamicModule {
    return { module: TransientModule, providers: [ ... ], exports: [ ... ] };
  }
}

// AppModule will import a unique instance of TransientModule tied to the lifetime of AppModule.
@Module({ imports: [ TransientModule.register(...) ] })
export class AppModule {}
```

#### Option 1, using the `Global()` decorator:
```typescript
@Global()
@Module({})
export class TransientModule{
  // or forRoot(...), or forFeature(...)
  static register(moduleOptions: Provider<ModuleOptions>): DynamicModule { 
    return { module: TransientModule, providers: [ moduleOptions ], exports: [ moduleOptions ] };
  }
}

// AppModule will import a shared instance of TransientModule as a singleton.
@Module({ imports: [ TransientModule ] })
export class AppModule {}
```

#### Option 2, wrapping the `DynamicModule` in a regular/static module:
```typescript
@Module({})
export class TransientModule{
  // or forRoot(...), or forFeature(...)
  static register(moduleOptions: Provider<ModuleOptions>): DynamicModule { 
    return { module: TransientModule, providers: [ moduleOptions ], exports: [ moduleOptions ] };
  }
}

@Module({ imports: [ TransientModule.register(moduleOptions) ], providers: [ ... ], exports: [ ... ] })
export class SingletonWrapperModule {}

// AppModule will import a shared instance of SingletonWrapperModule to share a wrapped transient module as a singleton.
@Module({ imports: [ SingletonWrapperModule  ] })
export class AppModule {}
```

### Describe the solution you'd like

I will preface this section by stating that, if possible, I believe this solution would greatly reduce the amount of boilerplate code and confusion around the NestJS module system. While the solution may not be entirely possible, the issue at hand still remains a big problem for both new, and existing, developers to the framework. As a seasoned developer, it took me nearly a week of searching for information and reading complex framework code to fully grasp these patterns and now I find myself writing a lot of useless boilerplate code.

The basics of my solution involves taking the core concepts of Providers, extending them a little bit and applying them to modules as well. At the end of the day, it could all be consolidated to registering and retrieving both modules and providers with IoC using the same concepts.

### Creating singleton modules
```typescript
@Module({ providers: [ ... ], exports: [ ... ] })
export class SingletonModule {}

// AppModule will import and create a shared instance of SingletonModule using its type as the injection token.
@Module({ imports: [ { provide: SingletonModule,  useValue: new SingletonModule() } ] })
export class AppModule {}
```

### Importing singleton modules
```typescript
// MyModule will import a shared instance of SingletonModule using its type as the injection token.
@Module({ imports: [ { provide: SingletonModule } ] })
export class MyModule {}
```

### Creating transient modules:
```typescript
@Module({ providers: [ ... ], exports: [ ... ] })
export class TransientModule {}

// AppModule will create and import a transient instance of TransientModule using an arbitrary string as the injection token.
@Module({ imports: [ { provide: 'MyTransientModule1',  useValue: new TransientModule() } ] })
export class AppModule {}
```

### Importing transient modules:
```typescript
// MyModule will import a transient instance of TransientModule using an arbitrary string as the injection token.
@Module({ imports: [ { provide: 'MyTransientModule1' } ] })
export class MyModule {}
```

In the 2 cases above, we are basically using the `Provider` type as either an `ImportProvider` (I would like to import a module from the IoC container) or `ExportProvider` (I would like to register a module with the IoC container). However, different types could also be used to avoid confusion.

### Creating singleton modules and passing in `moduleOptions` from the parent context:
```typescript
@Module({ providers: [ ... ], exports: [ ... ] })
export class SingletonModule {
  constructor(moduleOptions: ModuleOptions) {...}
}

// AppModule will import a configured and shared instance of SingletonModule using its type as the injection token.
@Module({ imports: [{ provide: SingletonModule,  useValue: new SingletonModule({...}) }] })
export class AppModule {}
```

### Importing configured singleton modules:
```typescript
// AppModule will import a configured, shared, instance of SingletonModule using its type as the injection token.
@Module({ imports: [{ provide: SingletonModule }] })
export class AppModule {}
```

The example is very WIP, but can be adapted to provide a much better solution that aligns both providers and modules to just injectable objects and object containers/modules respectively. I am also open to discussing other potential solutions that use familiar concepts and less boilerplate code while remaining simple and straightforward.

### Teachability, documentation, adoption, migration strategy

I think my examples above could be used in conjunction with existing documentation on `Providers`, `Modules` and `DynamicModules` to demonstrate typical Module use cases while educating readers on the terminology. I would be happy to do that on the off chance this solution is implemented. Otherwise I think at a minimum I think we should add a section in the documentation with some of these common examples I posted so others can learn about these obscure patterns directly from official sources/NestJS.

### What is the motivation / use case for changing the behavior?

As I mentioned above, currently, it is very tedious to manage the scope/lifetime of modules in nest. It is also a separate concept from managing the scope/lifetime of providers and causes confusion. The concepts for passing in data to a module are also complex to grasp, unrecognized and time consuming. They should be simpler, familiar and more straightforward.

**Comment by magicmatatjahu** [comment]
@Falven Hi! As you wrote this is just a WIP but overall I have a few problems with this solution and I don't understand everything.

Of course, few people know how "sharing" modules work at Nest. Nest converts a given import into a hash, so changes the representation in JS (as reference to class or object - dynamic module case) to a string and hashes it and then compares elsewhere whether to use the same module or create a new one with new providers (with exports as well).

Some of the problems you mentioned can be solved by using a "proxy" module (some examples you gave), for example for singleton modules:

```ts
@Module({ providers: [ ... ], exports: [ ... ] })
export class SingletonModule {}

@Module({ imports: [ SingletonModule ] })
export class MyModule {}

// AppModule and MyModule will share that same instance of SingletonModule
@Module({ imports: [ SingletonModule, MyModule ] })
export class AppModule {}
```

Of course for "transient" modules you have to create that boilerplate with `SingletonWrapperModule` where you import dynamic module of the `TransientModule` module and it can be a problem (with boilerplate of course). Even if core team accept that idea with `useValue`, that solution with passing `moduleOptions` to the constructor of the given module doesn't have any sense, because in the module's constructor you cannot create new providers and export them to the another module.

Lets consider that example:

```ts
@Module({ imports: [ { provide: 'MyTransientModule',  useValue: new TransientModule() } ] })
export class Module1 {}

@Module({ imports: [ { provide: 'MyTransientModule',  useValue: new TransientModule() } ] })
export class Module2 {}

@Module({ imports: [Module1, Module2] })
export class AppModule {}
``` 

What configuration should be used for the module token then? The one from Module1 or Module2? Of course this is quite a simple situation, but imagine that you have a very deep nesting and it will be difficult to determine which configuration will be loaded for a given module.

Another problem (when we decide to pick up config for first meet module), each module (or rather its metadata) is processed asynchronously and it may happen that once the metadata from `Module1` will be processed earlier than from `Module2`, but in second run in reverse order, so what then? It's not determistic. I may be wrong here, so forgive me if I'm speaking foolishly.

I am not sure, but I think that circular modules might be another problem and I also ask: what then?

It seems to me that the current solution (with that boilerplate related to the `SingletonWrapperModule`) solves the above problems, but it requires a boilerplate. I would like to hear the opinion of someone from the core team.

**Comment by Falven** [comment]
Hey @magicmatatjahu,
Thanks for taking the time to read and provide your 2c.

> Even if core team accept that idea with `useValue`, that solution with passing `moduleOptions` to the constructor of the given module doesn't have any sense, because in the module's constructor you cannot create new providers and export them to the another module.

Right, I think this may be part of the changes needed. It all depends on the core IoC implementation for Modules, which is abstracted away from us; we need some input from the core team.
To speculate, maybe there would need to be a module base class where you can access the providers array, or some other way to register provider metadata. Otherwise, the module classes are useless. What use do they have besides presenting a placeholder for the `@Module` annotation?

> Lets consider that example:
> 
> ```ts
> @Module({ imports: [ { provide: 'MyTransientModule',  useValue: new TransientModule() } ] })
> export class Module1 {}
> 
> @Module({ imports: [ { provide: 'MyTransientModule',  useValue: new TransientModule() } ] })
> export class Module2 {}
> 
> @Module({ imports: [Module1, Module2] })
> export class AppModule {}
> ```
> 
> What configuration should be used for the module token then? The one from Module1 or Module2? Of course this is quite a simple situation, but imagine that you have a very deep nesting and it will be difficult to determine which configuration will be loaded for a given module.

I'm not following this question/example. Are you asking how an IoC container handles _injection token_ collision? It's implementation dependent, but I would assume that in the NestJS example the IoC container would work in the following fashion:
1. AppModule is bootstrapped and injected first in your `main.ts` as is convention.
2. The IoC container then recursively initializes the modules and providers of `AppModule`.
3. For the case of `Module1` imported in `AppModule`, the IoC container registers a new `TransientModule` using the injection token 'MyTransientModule'.
4. For the case of `Module2` imported in `AppModule`, the IoC container attempts to register a new `TransientModule` in it's imports using the injection token 'MyTransientModule'.
5. There is a collision as there is an existing token for 'MyTransientModule'. Depending on implementation (or configuration), the IoC container can then error out or simply replace the existing object referenced by that injection token.

> Another problem (when we decide to pick up config for first meet module), each module (or rather its metadata) is processed asynchronously and it may happen that once the metadata from `Module1` will be processed earlier than from `Module2`, but in second run in reverse order, so what then? It's not determistic. I may be wrong here, so forgive me if I'm speaking foolishly.

I think this question falls under the same answer above, it should not matter if the IoC container performs registrations asynchronously for either of the collision resolution strategies I outlined above. If you're registering two transient modules under the same injection token then you're asking for trouble regardless of the order the framework initializes imported modules.

> I am not sure, but I think that circular modules might be another problem and I also ask: what then?

Correct me if I am wrong, but I don't think the solution I provided adds anything that would change the way NestJS currently handles provider registration or circular dependencies. Just extending the same behavior from providers to encapsulate modules.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestions. There are no plans to change the current syntax for importing modules and the API will likely not change in the foreseeable future either.

> As I mentioned above, currently, it is very tedious to manage the scope/lifetime of modules in nest. It is also a separate concept from managing the scope/lifetime of providers and causes confusion. The concepts for passing in data to a module are also complex to grasp, unrecognized and time consuming. They should be simpler, familiar and more straightforward.

If you have any ideas on how we could make the documentation better and you're willing to contribute, definitely go for it.  The documentation repository is open-sourced and contributions are more than welcome https://github.com/nestjs/docs.nestjs.com I can see that the current behavior might not be as properly documented as it should be and there's certainly room for improvement there. We should do a better job in explaining edge cases too.

We're also currently working on providing some extra tooling that would simplify the creation of configurable dynamic modules and will likely somewhat improve the documentation (overall modules docs) on that as part of the process.

If you have any questions regarding the current behavior of NestJS modules, please ask them on our [Discord](https://discord.gg/G7Qnnhy) channel (support).
