### ISSUE TITLE
Make it possible to compose decorations using a custom factory

### ISSUE THREAD

**Issue by noamtamim** [nestjs/nest#9110]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have two types of `Controller` methods: "public" (used by external web apps) and "internal" (used only by microservices in the same VPC). The public methods use both `@UseGuards(publicApiGuard)` with a "public" guard **and** `@ApiTags("Public API")` (for Swagger doc); similarly, the internal methods use a different guard and a "Protected API" tag.

I want to be able to create a decorator factory such as `@PublicApi()` that will apply both `@UseGuards` and `@ApiTags` (and maybe others).

This does not seem to be possible ATM, because `UseGuards` and `ApiTags` are themselves decorator factories.

### Describe the solution you'd like

Create some kind of helper that will allow decorator composition.

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

See description above.

**Comment by jmcdo29** [comment]
In case anyone else happens upon this, [the applyDecorators](https://docs.nestjs.com/custom-decorators#decorator-composition) method is what you're looking for.
