### ISSUE TITLE
Configuration to enable undefined to be passed in ClientProxy send method

### ISSUE THREAD

**Issue by robertohein** [nestjs/nest#9125]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently i integrated with a external services that has only one channel and they send me a undefined message pattern, after debugging and changed my Message received annotation as below

`  @UsePipes( new RabbitPipe() )
  @MessagePattern( )
  received( @Ctx() msg: RabbitMessage ) {
    this.inventory.addToQueue( msg );
    return 'ok';
  }` 
  
i was able to receive their messages, but when i was writing tests i was not ablet to publish a message with the ClientProxy with a undefined message pattern because the send method checks if the pattern is null or undefined 

`  public send<TResult = any, TInput = any>(
    pattern: any,
    data: TInput,
  ): Observable<TResult> {
    if (isNil(pattern) || isNil(data)) {
      return _throw(() => new InvalidMessageException());
    }
    return defer(async () => this.connect()).pipe(
      mergeMap(
        () =>
          new Observable((observer: Observer<TResult>) => {
            const callback = this.createObserver(observer);
            return this.publish({ pattern, data }, callback);
          }),
      ),
    );
  }
`

### Describe the solution you'd like

i suggest passing a third and optional argument to the send method like a configuration, and in that configuration i would have a option like disablePatternChecks or something like that

### Teachability, documentation, adoption, migration strategy

This change would be backwards compatible

### What is the motivation / use case for changing the behavior?

Be able to receive any message pattern, since not all microservices will receive messages coming from the nestjs client proxy and other devs may choose to not use any pattern at all.

**Comment by robertohein** [comment]
I created the #9126 PR making this change.

**Comment by kamilmysliwiec** [comment]
> And other devs may choose to not use any pattern at all.

So you likely shouldn't be using the `@nestjs/microservices` package for this and instead, use Nest application context + RMQ library directly.

Please search through some of our old issues on this (this has been discussed several times in the past).
