### ISSUE TITLE
ConfigModule/Service in Microservice undefined

### ISSUE THREAD

**Issue by Meywether** [nestjs/nest#9127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The ConfigModule here is undefined during runtime: https://github.com/Meywether/nestjs_ms1/blob/main/src/status/status.controller.ts
line 14 shows a workaround but I do not understand why the ConfigService is not defined, since there is no error message, I think that this is a bug.

### Minimum reproduction code

https://github.com/Meywether/nestjs_ms1 and https://github.com/Meywether/nestjs_http_sample

### Steps to reproduce

Cloning both repos, 
starting both repos
Trigger the endpoint localhost:8080/status
Error in Repo MS 1 StatusController Line 13 -> configService undefined (https://github.com/Meywether/nestjs_ms1/blob/main/src/status/status.controller.ts)

### Expected behavior

ConfigService in https://github.com/Meywether/nestjs_ms1/blob/main/src/status/status.controller.ts line 13 should be defined

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.X

### Packages versions

```json
{
  "name": "sample-http",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.2.3",
    "@nestjs/config": "^1.1.5",
    "@nestjs/core": "^8.2.3",
    "@nestjs/microservices": "^8.2.3",
    "@nestjs/platform-express": "^8.2.3",
    "nest-winston": "^1.6.2",
    "redis": "^3.0.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.4.0",
    "winston": "^3.3.3",
    "winston-daily-rotate-file": "^4.5.5"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.1.5",
    "@nestjs/schematics": "^8.0.5",
    "@nestjs/testing": "^8.2.3",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.3",
    "@types/node": "^16.11.11",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.5.0",
    "@typescript-eslint/parser": "^5.5.0",
    "eslint": "^8.4.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.4.3",
    "prettier": "^2.5.1",
    "supertest": "^6.1.6",
    "ts-jest": "^27.1.0",
    "ts-loader": "^9.2.6",
    "ts-node": "^10.4.0",
    "tsconfig-paths": "^3.12.0",
    "typescript": "^4.5.2"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

16.10.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Aren't you missing the `@Controller()` decorator on the [`StatusController`](https://github.com/Meywether/nestjs_ms1/blob/main/src/status/status.controller.ts#L5)

**Comment by jmcdo29** [comment]
Yeah, just tested. Adding the `@Controller()` decorator fixes the config service injection. 
Please use our [Discord](https://discord.gg/nestjs) channel (Support) for further support. We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by Meywether** [comment]
@jmcdo29 Wait what happened ? 
Many thanks, and thanks for the Discord Link :)
