### ISSUE TITLE
Trouble with webpack with openapi when build an application

### ISSUE THREAD

**Issue by ccalderon9411** [nestjs/nest#9129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am building a nestjs application using webpack, but it build, the schemas of DTO´s breaks.

Application in dev
![image](https://user-images.githubusercontent.com/43613718/153300116-422c6419-991e-4ddc-919e-1767452324d5.png)

Application build (schemas breaks)
![image](https://user-images.githubusercontent.com/43613718/153300013-d8c44ed7-48c7-4232-aa8c-3c04ee5f1d4e.png)

### Minimum reproduction code

https://github.com/rudemex/nestjs-starter.git

### Steps to reproduce

1. git clone https://github.com/rudemex/nestjs-starter.git
2. npm install
3. npm run build
4. run compiled application
5. can see the demo of project here: https://rudemex-nestjs-starter.herokuapp.com/docs/

### Expected behavior

Schemas names should be as I define in code.
![image](https://user-images.githubusercontent.com/43613718/153300793-abace8c0-23c1-415c-8fde-76a7ccde0512.png)

### Package

- [ ] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [x] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [x] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger
@nestjs/class-transformer
@nestjs/class-validator
class-transformer

### NestJS version

8.2.6

### Packages versions

```json
"@nestjs/swagger": "^5.1.5",
"@nestjs/class-transformer": "^0.4.0",
"@nestjs/class-validator": "^0.13.3",
 "class-transformer": "^0.5.1"
```

### Node.js version

14.17.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This is expected because you are minimizing the code. By doing so, webpack changes the names of the classes, and the metadata read at runtime reflects those names. If you don't really need minimization (there isn't much need for it on the server side) then I'd suggest not using it

**Comment by rudemex** [comment]
Hi @jmcdo29 Is there any configuration for webpack that transpiles the code in a single file? similar to monorepo but for applications.

**Comment by jmcdo29** [comment]
Just using `nest build --webpack` should do that automatically.

**Comment by rudemex** [comment]
@jmcdo29 Great, and does it detect if the transpiling is for production? or do you have to expand the configuration?

**Comment by jmcdo29** [comment]
@rudemex 
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
