### ISSUE TITLE
ValidationPipe: an unknown value was passed to the validate function

### ISSUE THREAD

**Issue by rudemex** [nestjs/nest#9132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Sending the correct parameters through the body in a PUT or PATCH returns a 400 Bad Request status with the message "an unknown value was passed to the validate function".
![Captura de Pantalla 2022-02-10 a la(s) 12 12 04 a  m](https://user-images.githubusercontent.com/1771743/153330058-f0827456-1335-47e6-ba37-307dadeddb66.png)

### Minimum reproduction code

https://github.com/rudemex/nestjs-starter

### Steps to reproduce

1. git clone https://github.com/rudemex/nestjs-starter
2. git checkout feat/docker
3. npm install
4. rename .env.example to .env
5. npm run start:dev
6. go to http://localhost:8080/docs/#/Users/UsersController_update
7. Try PUT method with ID = 1 and change any value of schema
8. see the response

### Expected behavior

It is expected to validate the body data against the DTO and make the change with an ok status.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/class-transformer, @nestjs/class-validator, class-transformer

### NestJS version

8.2.6

### Packages versions

```json
"@nestjs/class-transformer": "^0.4.0",
"@nestjs/class-validator": "^0.13.3",
"class-transformer": "^0.5.1",
```

### Node.js version

14.15.4

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

### Other

Global Pipe validation config

```ts
// ./src/main.ts

app.useGlobalPipes(
    new ValidationPipe({
      validatorPackage: require('@nestjs/class-validator'),
      transformerPackage: require('class-transformer'),
      //whitelist: true,
      forbidUnknownValues: true,
      forbidNonWhitelisted: true,
      transformOptions: {
        enableImplicitConversion: true,
      },
    }),
  );
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
