### ISSUE TITLE
When OnModuleInit exec failed, should stop running.

### ISSUE THREAD

**Issue by XGHeaven** [nestjs/nest#914]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

```typescript
export class SomeService implements OnModuleInit {
  async onModuleInit() {
    throw new Error('should stop')
  }
}
```

When I running, a error occured, server process don't stop.

## Expected behavior

server process should stop when any of onModuleInit called failed.

## What is the motivation / use case for changing the behavior?

When running in docker, server cannot start correctly because onModuleInit called failed.
The server process still alived. And docker think it still running. It's wrong.

## Environment

<pre><code>
Nest version: 5.1.0

 
For Tooling issues:
- Node version: 10.7.0  
- Platform: Mac

**Comment by XGHeaven** [comment]
Sorry, I can't found a commit relative with this issue.

**Comment by kamilmysliwiec** [comment]
5.2.0 is here! Let me know if you face any issue
