### ISSUE TITLE
MIddleware exception handling is completely broken from a documentation standpoint

### ISSUE THREAD

**Issue by brian-pinwheel** [nestjs/nest#9144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When an exception is thrown in middleware, custom filters are called with NestJS Requests/Responses instead of the platform's Request/Responses as [documented](https://docs.nestjs.com/exception-filters#exception-filters-1).

Unfortunately, the only way to resolve this is to build the exception filter to handle both platform and NestJS Requests/Responses, which is not optimal, much less not documented.

An alternative approach is to call the `next` method with the exception.  This works, but it is not documented and is not part of the [type definitions](https://github.com/nestjs/nest/blob/99ee3fd99341bcddfa408d1604050a9571b19bc9/packages/common/interfaces/middleware/nest-middleware.interface.ts) as the method currently takes no parameters.

### Minimum reproduction code

https://github.com/pinwheel-phone/middleware-exception-repo

### Steps to reproduce

To run the sample project do:

1. yarn install
2. yarn start
3. curl http://localhost:3000/hello

### Expected behavior

Custom Filters work as documented and exceptions that occur in middleware don't require changes to the exception filter.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.4

### Packages versions

```json
{
  "name": "middleware-exception-repo",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-fastify": "^8.2.6",
    "fs": "^0.0.1-security",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.2.41"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.0.2",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v14.18.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> When an exception is thrown in middleware, custom filters are called with NestJS Requests/Responses instead of the platform's Request/Responses as [documented](https://docs.nestjs.com/exception-filters#exception-filters-1).

Express middleware are called with Express specific Request & Response objects.

Fastify middleware are called with **raw** Request & Response objects (and so error filters will receive **raw** request & response objects when exception is thrown from the middleware).

Please search through some of our old issues on this (this has been discussed several times in the past).

> An alternative approach is to call the next method with the exception. This works, but it is not documented and is not part of the [type definitions](https://github.com/nestjs/nest/blob/99ee3fd99341bcddfa408d1604050a9571b19bc9/packages/common/interfaces/middleware/nest-middleware.interface.ts) as the method currently takes no parameters.

That's something we could indeed improve. Would you like to create a PR adding an optional error parameter?

**Comment by brian-pinwheel** [comment]
@kamilmysliwiec I created a [PR](https://github.com/nestjs/nest/pull/9247) for the change as suggested.
