### ISSUE TITLE
how setViewEngine（ ） use to  Layout ？？？？

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [nestjs/nest#916]
```
import { NestFactory } from '@nestjs/core';
import { AppModule } from 'app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.useStaticAssets(__dirname + '/public');
  app.setBaseViewsDir(__dirname + '/plugins');
  app.setViewEngine('hbs');

  await app.listen(3000);
}
bootstrap();

```

I don't know how to set up a layout

**Comment by kamilmysliwiec** [comment]
Please, use ISSUE template.

**Comment by cdiaz** [comment]
@rainbowMorelhahahah  use `registerPartials` from `hbs`
```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as hbs from 'hbs';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useStaticAssets(__dirname + '/public');
  app.setBaseViewsDir(__dirname + '/views');
  app.setViewEngine('hbs');
  hbs.registerPartials(__dirname + '/views/partials');

  await app.listen(3000);
}
bootstrap();
```

**Comment by slawinski** [comment]
I might've encountered the same problem. This post on stackoverflow should solve it.
https://stackoverflow.com/questions/51845556/how-to-set-up-a-default-layout-in-nest-js-using-handlebars-js

**Comment by KapSSe** [comment]
Maybe this example will be clear: 

`import { NestFactory } from '@nestjs/core';
import { join } from 'path';
import { AppModule } from './app.module';
import * as hbs from 'hbs';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  app.useStaticAssets(join(__dirname, '..', 'public'));
  app.setBaseViewsDir(join(__dirname, '..', 'views'));
  app.setViewEngine('hbs');
  hbs.registerPartials(join(__dirname, '..', 'views/partials'));
  await app.listen(3000);
}
bootstrap();
`

**Comment by KapSSe** [comment]
Maybe this example will be clear:

```
import { NestFactory } from '@nestjs/core';
import { join } from 'path';
import { AppModule } from './app.module';
import * as hbs from 'hbs';

async function bootstrap() {
const app = await NestFactory.create(AppModule);
app.enableCors();
app.useStaticAssets(join(__dirname, '..', 'public'));
app.setBaseViewsDir(join(__dirname, '..', 'views'));
app.setViewEngine('hbs');
hbs.registerPartials(join(__dirname, '..', 'views/partials'));
await app.listen(3000);
}
bootstrap();
```
