### ISSUE TITLE
GraphQL subscription server close example.

### ISSUE THREAD

**Issue by ph55** [nestjs/nest#917]
https://github.com/nestjs/nest/blob/master/sample/12-graphql-apollo/src/subscriptions/subscriptions.service.ts

At the end:
```ts
onModuleDestroy() {
    this.ws.close();
}
```

Shouldn't it be?
```ts
onModuleDestroy() {
    this.subscriptionServer.close();
}
```

**Comment by kamilmysliwiec** [comment]
Actually, it depends. Either one is fine. I guess that the perfect solution would be to close them both. There is a plan to make GraphQL module much more robust then so far, I'll share the details soon.
