### ISSUE TITLE
Typeorm migrations when using webpack (nestjs monorepo) (nest-cli)

### ISSUE THREAD

**Issue by alinturbut** [nestjs/nest#9190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Typeorm migrations in Monorepo mode is not documented. Relates to: https://github.com/nestjs/nest/issues/3223

### Minimum reproduction code

not-needed

### Steps to reproduce

1. Generate a monorepo nestjs app
2. Generate typeorm migrations
3. yarn start:dev

### Expected behavior

Migrations should be found and ran.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/typeorm

### Packages versions

```json
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v14.16.0
YARN Version    : 1.19.1

[Nest CLI]
Nest CLI Version : 8.2.0

[Nest Platform Information]
platform-express version : 8.2.6
microservices version    : 8.2.6
mapped-types version     : 1.0.1
schematics version       : 8.0.5
passport version         : 8.1.0
terminus version         : 8.0.4
typeorm version          : 8.0.3
testing version          : 8.2.6
common version           : 8.2.6
config version           : 1.1.6
core version             : 8.2.6
jwt version              : 8.0.0
cli version              : 8.2.0
```

### Node.js version

node v14.16.0 (npm v6.14.11)

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

It's not clear from the documentation how to extend the webpack configuration to allow for unbundled migration files for typeorm in the case of monorepo.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
