### ISSUE TITLE
Workaround to the issue: (ValidationPipe transforms before validating #2856)

### ISSUE THREAD

**Issue by breno-bortot** [nestjs/nest#9194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If a property from a DTO has transformation and validation decorators the transformation decorator will be applied before the validation ones. Since the validators work essentially with the string type, they become useless when those strings are converted to objects in the transformation step.

The following code won't work. @IsMongoId will never pass, because the array of strings is transformed into an array of ObjectID before it is used.

If we remove the @IsMongoId decorator and the request contains an invalid ObjectID string, the server will throw a 500 error, because it can't instantiate the object ObjectID.

### Minimum reproduction code

https://github.com/nestjs/nest/issues/2856

### Steps to reproduce

@IsNotEmpty()
@IsArray()
@IsMongoId({
   each: true
 })
@Transform(strings => strings.map(string => new ObjectID(string)))
readonly categoriesId: ObjectID[];

### Expected behavior

The validation step should happen before the transformation step.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
> The validation step should happen before the transformation step.

This is impossible. At least with the current package we use for the `ValidationPipe` (`class-validator`) a **class instance** must be used. To turn an object into a class instance, we use `class-transformer` which is what makes use of the `@Transform()` decorator.

**Comment by breno-bortot** [comment]
just a moment, I'm writing... hehe

**Comment by breno-bortot** [comment]
So there was this guy [IGassmann](https://github.com/IGassmann), with this same question that me.
And I waht I just did to workaround this problem, was to use a ternary operator like this:

`export class CreateUserDto {
    @Transform(({ value }) => typeof(value) === 'string' ? sanitize(value, { disallowedTagsMode:"escape" }) : value)
    @IsString()
    readonly name: string;

    @IsEmail()
    readonly email: string;
    
    @IsString()
    readonly password: string;

   @ValidateIf(CreateUserDto => CreateUserDto.seller )
   @IsBoolean()
    readonly seller?: boolean;
}
`

In this situation a needed to have the @IsString validation to keep being useful, so as the @Transform runs before the validation, I used the ternary operator to sanitize what I need if the input was a string, and if it was not a string, I just pass it foward as before and it will be cacth by the @IsString validation.

**Comment by breno-bortot** [comment]
> > The validation step should happen before the transformation step.
> 
> This is impossible. At least with the current package we use for the `ValidationPipe` (`class-validator`) a **class instance** must be used. To turn an object into a class instance, we use `class-transformer` which is what makes use of the `@Transform()` decorator.

**Comment by breno-bortot** [comment]
So there was this guy [IGassmann](https://github.com/IGassmann), with this same question that me. #2856
And what I just did to workaround this problem, was to use a ternary operator like this:


```
import { Transform } from "class-transformer";
import { IsBoolean, IsEmail, IsString, ValidateIf } from "class-validator";
import * as sanitize from "sanitize-html";


export class CreateUserDto {
    @Transform(({ value }) => typeof(value) === 'string' ? sanitize(value, { disallowedTagsMode:"escape" }) : value)
    @IsString()
    readonly name: string;

    @IsEmail()
    readonly email: string;
    
    @IsString()
    readonly password: string;

   @ValidateIf(CreateUserDto => CreateUserDto.seller )
   @IsBoolean()
    readonly seller?: boolean;
}
```




In this situation a needed to have the @IsString validation to keep being useful, so as the @Transform runs before the validation, I used the ternary operator to sanitize what I need if the input was a string, and if it was not a string, I just pass it foward as before and it will be cacth by the @IsString validation.

**Comment by jmcdo29** [comment]
Is there an actual issue here, or are you just creating noise?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
