### ISSUE TITLE
[8.1.1] - Nest can't resolve dependencies of the JwtAuthGuard...

### ISSUE THREAD

**Issue by dattran1232003** [nestjs/nest#9198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`error: Nest can't resolve dependencies of the JwtAuthGuard. Please make sure that the "options" property is available in the current context.`

![image](https://user-images.githubusercontent.com/57513789/153992556-cf265807-f135-4f6f-851f-e0b5e3eb60d5.png)

My code:
jwt-auth.guard.ts
![jwt-auth.guard.ts](https://user-images.githubusercontent.com/57513789/153992838-468648a7-ad80-4559-b46f-4a23a50901ea.png)

### Minimum reproduction code

no have

### Steps to reproduce

Happens when updating package `@nestjs/passport` from v8.1.0 to v8.1.1.

### Expected behavior

Don't throw error

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/passport

### NestJS version

8.3.0

### Packages versions

![image](https://user-images.githubusercontent.com/57513789/153993102-6b532d9d-8301-4593-adef-f0f2bef5ec3d.png)

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

It's don't happen with the old version of @nestjs/passport. I found out while building app with docker (automatically install newest package)

**Comment by jmcdo29** [comment]
There's an open issue and pr to fix this over in the [nestjs/passport](https://github.com/nestjs/passport) repository.. Please check there for more information.

**Comment by kamilmysliwiec** [comment]
Fixed
