### ISSUE TITLE
MessagePattern could be used more than once on single method

### ISSUE THREAD

**Issue by Dzixxx** [nestjs/nest#9222]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When U introduced versioning in Nest v8 we decided to start adapting our code to it. Http went pretty smooth but when it goes about our microservice architecture then we started seeing limitations of MessagePattern. I think that it won't affect any other package than `@nest/microservice` 

### Describe the solution you'd like

I know that due to reflect only one MessagePattern will be saved in metadata so are U able to tell if this is planned to be implemented at all 😂 ? I can offer help with implementation cause we have also custom decorator for wrapping MessagePattern (we connected everything with AsyncAPI etc.) 

```typescript
// what we're trying to achieve
@Controller()
class MyCtrl {

  @MessagePattern('/pattern1')
  method() {
     // ...
  }

  @MessagePattern('/v2/pattern1')
  @MessagePattern('/v3/pattern1')
  nextGenMethod() {
     // ...
  }
}

// how it will look like in our code
@Controller()
class MyCtrl {

  @DzixxxPattern('/pattern1')
  method() {
     // ...
  }

  @DzixxxPattern(['v2', 'v3'], '/pattern1')
  nextGenMethod() {
     // ...
  }
}
```

### Teachability, documentation, adoption, migration strategy

I think that only additional paragraph in microservices section that U can use more than only one pattern ;)

### What is the motivation / use case for changing the behavior?

It will let us to not copy/paste methods for versioned patterns in nats (and any other ofc...) 🚀

**Comment by Dzixxx** [comment]
definitely can try today :)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/9230
