### ISSUE TITLE
Missing release notes / changelog since November 2021

### ISSUE THREAD

**Issue by zackdotcomputer** [nestjs/nest#9225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is no (evident) way to find out what changes have been released to NestJS releases since November 2021.

The Github release notes are inactive, there is no CHANGELOG.md file in the repository (as has been discussed [many](https://github.com/nestjs/nest/issues/4335) [times](https://github.com/nestjs/nest/issues/7263) [previously](https://github.com/nestjs/nest/issues/6836) with the most recent guidance being to check the release notes on Github instead), and the [Migration Guide](https://docs.nestjs.com/migration-guide) only documents how to upgrade between major versions 7 and 8.

This was [reported in November](https://github.com/nestjs/nest/issues/8526), after which release notes were added for 8.2.0 and 8.2.3, but then the process was halted again. As such, 7 releases over the past 3 months have no documentation about what has changed in them.

### Minimum reproduction code

https://github.com/nestjs/nest/releases

### Steps to reproduce

Compare the [npm version list](https://www.npmjs.com/package/@nestjs/core) with the [documented release notes](https://github.com/nestjs/nest/releases) for the project.

### Expected behavior

The expected behavior would be one or more of:
- an up to date CHANGELOG or RELEASE_NOTES file
- release notes in Github
- a releases page on the website

Ideally, updating this destination / these destinations would be automated as part of the deploy process. From the history of issues on this topic, I think the manual process has proven not as reliable as we would hope.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

As far as I can tell, all NestJS Packages

### NestJS version

8.3.1

### Packages versions

```json
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v14.18.1
NPM Version    : 8.1.4 

[Nest CLI]
Nest CLI Version : 8.2.1 

[Nest Platform Information]
platform-express version : 8.3.1
schematics version       : 8.0.6
sequelize version        : 8.0.0
passport version         : 8.2.1
terminus version         : 8.0.4
swagger version          : 5.2.0
testing version          : 8.3.1
common version           : 8.3.1
config version           : 1.2.0
axios version            : 0.0.5
core version             : 8.3.1
cli version              : 8.2.1
```

### Node.js version

14 LTS

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
If there are no release notes, that means changes that were made are rather irrelevant (non-essential). I understand that we should be transparent with everything and I apologize for my lack of responsiveness! 

I've just added release notes to all recent releases.
