### ISSUE TITLE
Add content-length header as option to StreamableFile

### ISSUE THREAD

**Issue by davidschuette** [nestjs/nest#9229]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No simple way to specify content-length when using StreamableFile class.

### Describe the solution you'd like

Currently the content-type and content-disposition header can be customized when returning a StreamableFile instance. Adding the content-length header as well would make it easy to specify the content length without accessing the response object.

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

Needing to specify the content-length header for file downloads.

**Comment by kamilmysliwiec** [comment]
What's the current vs expected behavior?
Would you like to create a PR to address this issue?

**Comment by davidschuette** [comment]
## Current behavior
Only `type` and `disposition` can be specified for `StreamableFile` class.
## Expected behavior
Option to provide more headers related to providing file streams. Like `Content-Length`, `Content-Range` and `Accept-Ranges`.
## Example
[Here](https://github.com/davidschuette/nestjs-file-streaming/blob/master/src/app/app.service.ts) is an example I am trying to refactor to use the `StreamableFile` class.

I will start working on a PR today.

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/nest/pull/9240
