### ISSUE TITLE
option to correct the timezone for timestamps

### ISSUE THREAD

**Issue by doctor-beat** [nestjs/nest#9248]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently the timestamp in the log entries are always in UTC. This is anoying for reallife persons trying to read the logs (unless you life in Greenwich.

### Describe the solution you'd like

Plz add an option to set the timezone in this method:

protected getTimestamp(): string {
    const localeStringOptions = {
      year: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
      second: 'numeric',
      day: '2-digit',
      month: '2-digit',
    };
    return new Date(Date.now()).toLocaleString(
      undefined,
      localeStringOptions as Intl.DateTimeFormatOptions,
    );
  }

Like: timezone: process.env.TZ

### Teachability, documentation, adoption, migration strategy

Set the TZ variable in the .env

### What is the motivation / use case for changing the behavior?

Ease of use

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
