### ISSUE TITLE
Add support for commitOffsets functions from kafkajs in class ClientKafka

### ISSUE THREAD

**Issue by davidschuette** [nestjs/nest#9258]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There is no option to manually commit offsets when comsuming kafka events.

### Describe the solution you'd like

Provide `commitOffsets` function from native kafkajs via ClientKafka implementation.

```typescript
constructor(@Inject('KAFKA') private readonly client: ClientKafka) {}
...
@EventPattern('pattern')
consumeEvent(@Payload() data: any, @Ctx() context: KafkaContext) {
  this.client.commitOffsets(...)
}
```

If this idea gets approval I will start working on a PR and I am happy to update the docs as well.

### Teachability, documentation, adoption, migration strategy

Developers will be able to manually commit offsets instead of auto commit. In production this is essential when using kafka.

### What is the motivation / use case for changing the behavior?

Need to manually commit offsets when working with kafka in production.

**Comment by kamilmysliwiec** [comment]
Contributions are more than welcome!

**Comment by davidschuette** [comment]
These are all the changes I am planing to make to `ClientKafka`.
```ts
public commitOffsets(
  topicPartitions: TopicPartitionOffsetAndMetadata[],
): Promise<void> {
  return this.consumer.commitOffsets(topicPartitions);
}
```

Does such a simple function require a test?

**Comment by kamilmysliwiec** [comment]
I think no tests are needed in this case.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/9270
