### ISSUE TITLE
Unable to use the same instance of custom logger for the entire application

### ISSUE THREAD

**Issue by gremo** [nestjs/nest#926]
The first time I learned about Nest I was really excited. Coming from Symfony/PHP world, it seemed a good way of starting switching to JavaScript. But now, after a few weeks, all the shining things about the DI, services, injections seems to "glue" not very well in Nest.

First it was https://github.com/nestjs/nest/issues/897 and now I'm facing another issue. Take the logger, everyone needs it. So you may end up creating a service, even a **module** providing `MyLogger`:

```typescript
// logger.module.ts
import { Global , Module } from '@nestjs/common';

@Global()
@Module({ })
export class LoggerModule {
  static forRoot(options: LoggerModuleOptions): DynamicModule {
    // This is a dynamic module which accept options and provide a configured
    // instance of MyLogger. Options maybe further manipulated.
  }
}
```

```typescript
// mylogger.service.ts
export class MyLogger {
  // Complex options...
  constructor (options: LoggerOptions) { }
}
```

So far so good you inject `MyLogger` pretty everywhere and you are happy.

But then you realize that when the application starts, messages from Nest are not logged using `MyLogger`, of course, but you may change this behavior:

```typescript
const app = await NestFactory.create(ApplicationModule, {
  logger: new MyLogger(),
});
await app.listen(3000);
```
... the only problem here is I can't use DI! I can't use the already configure instance of `MyLogger`, I should pass a fresh new object, duplicating all the options used to build it.

**Comment by gremo** [comment]
@kamilmysliwiec thanks, waiting for 5.2 then!

**Comment by kamilmysliwiec** [comment]
5.2.0 is published!
