### ISSUE TITLE
Directive in @nestjs/graphql has no effect

### ISSUE THREAD

**Issue by Mark-Panda** [nestjs/nest#9261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

GraphQLModule.forRoot({
  autoSchemaFile: 'src/schema.gql',
  buildSchemaOptions: {
    dateScalarMode: 'timestamp',
    schemaDirectives: {
      upper: UpperCaseDirective, // no effect
    },
  },
  schemaDirectives: {
    upper: UpperCaseDirective, // no effect
  },
  playground: true,
  introspection: true,
  debug: true,
  // Allow guards and middleware to access req and headers
  context: ({ req }) => ({
    req,
    headers: req.headers,
    databaseConnection: req.databaseConnection,
    updatedAt: req.updatedAt,
  }),
}),

### Minimum reproduction code

https://stackoverflow.com/questions/63045893/directive-in-nestjs-graphql-has-no-effect

### Expected behavior

Directive in @nestjs/graphql has effect

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
"@commitlint/cli": "^16.1.0",
    "@commitlint/config-conventional": "^16.0.0",
    "@nestjs/apollo": "^10.0.0",
    "@nestjs/common": "^8.2.6",
    "@nestjs/core": "^8.2.6",
    "@nestjs/graphql": "^9.1.2",
    "@nestjs/platform-express": "^8.2.6",
    "@paljs/plugins": "^4.0.13",
    "@prisma/client": "^3.8.1",
    "@semantic-release/changelog": "^6.0.1",
    "@semantic-release/git": "^10.0.1",
    "@types/flat": "^5.0.2",
    "@types/lodash": "^4.14.178",
    "@types/mocha": "^9.1.0",
    "@types/node": "^17.0.10",
    "@types/pluralize": "^0.0.29",
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.10.0",
    "apollo-server-express": "^3.6.2",
    "c8": "^7.11.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "commitizen": "^4.2.4",
    "cz-customizable": "^6.3.0",
    "decimal.js": "^10.3.1",
    "eslint": "^8.7.0",
    "eslint-import-resolver-node": "^0.3.6",
    "eslint-plugin-etc": "^2.0.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-only-warn": "^1.0.3",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-regexp": "^1.5.1",
    "eslint-plugin-simple-import-sort": "^7.0.0",
    "eslint-plugin-sort-class-members": "^1.14.1",
    "eslint-plugin-unicorn": "^40.1.0",
    "eslint-plugin-wix-editor": "^3.3.0",
    "expect": "^27.4.6",
    "ghooks": "^2.0.4",
    "git-branch-is": "^4.0.0",
    "graphql": "^16.2.0",
    "graphql-scalars": "^1.14.1",
    "graphql-type-json": "^0.3.2",
    "mocha": "^9.1.4",
    "ololog": "^1.1.175",
    "precise-commits": "^1.0.2",
    "prettier": "^2.5.1",
    "prisma": "^3.8.1",
    "prisma-graphql-type-decimal": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.2",
    "semantic-release": "^19.0.2",
    "simplytyped": "^3.3.0",
    "temp-dir": "^2.0.0",
    "ts-node": "^10.4.0",
    "ts-node-dev": "^1.1.8",
    "tslib": "^2.3.1",
    "typescript": "^4.5.5",
    "watchexec-bin": "^1.0.0"
}
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
