### ISSUE TITLE
TS2307: Cannot find module '@nestjs/ng-universal/tokens' or its corresponding type declarations.

### ISSUE THREAD

**Issue by DaSchTour** [nestjs/nest#9262]
### Did you read the migration guide?

- [x] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

https://github.com/nestjs/ng-universal/commit/508bba7eddd6a638d342e6bc587c8587c9bb226a

### NestJS version

7→ 8

### Describe the regression

It is not possible to import Tokens correctly

```
import { REQUEST } from '@nestjs/ng-universal/tokens';
```

### Input code

```ts

```

### Expected behavior

Import should work as expected and documented

### Other

https://github.com/nestjs/ng-universal/issues/573

PR with fix: https://github.com/nestjs/ng-universal/pull/688

**Comment by kamilmysliwiec** [comment]
Duplicate
