### ISSUE TITLE
[Queues] No error thrown if Bull redis config is wrong

### ISSUE THREAD

**Issue by kodekage** [nestjs/nest#9264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

1. When Redis is misconfigured for the bull queue no error is thrown
2. When using the queue producer/consumer in an endpoint it's blocking because of misconfigured Redis

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/26-queues

### Steps to reproduce

1. npm i
2. npm start dev
3. curl -X POST http://localhost:3000/audio/transcode
4. Notice the infinite execution without any response

### Expected behavior

1. I expect to get an error when starting my Nestjs project that Redis is misconfigured
2. I ideally expect errors when trying to use producers/consumers instead of the blocking execution

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/bull

### NestJS version

8.1.1

### Packages versions

```json

[System Information]
OS Version     : macOS Monterey
NodeJS Version : v14.16.1
NPM Version    : 6.14.12 

[Nest CLI]
Nest CLI Version : 8.2.0 

[Nest Platform Information]
platform-express version : 8.1.1
schematics version       : 8.0.4
passport version         : 8.1.0
schedule version         : 1.0.2
terminus version         : 8.0.4
swagger version          : 5.2.0
typeorm version          : 8.0.3
testing version          : 8.1.1
common version           : 8.1.1
config version           : 1.1.6
axios version            : 0.0.5
bull version             : 0.5.0
core version             : 8.1.1
jwt version              : 8.0.0
cli version              : 8.2.0

```

### Node.js version

14.16.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I also found a similar [issue](https://github.com/nestjs/nest/issues/8552)

**Comment by micalevisk** [comment]
duplicated of https://github.com/nestjs/bull/issues/1076
