### ISSUE TITLE
MQTT client emit sends builder options

### ISSUE THREAD

**Issue by Nosfistis** [nestjs/nest#9272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently the docs mention an MQTT client using `send` to send a message. However, MQTT is not really a request-response pattern. More often, we just fire a message and forget about it. For this purpose, I think `emit` and `@EventPattern()` are more suitable as examples with MQTT.

Other than that, the recent nice addition of builders does not work the same way in both `emit` and `send`. When using `emit`, the entire. This is because currently the `options` property is not removed in the `dispatchEvent` function:

https://github.com/nestjs/nest/blob/342649a0f5b4b88a51bd856ecc18bbedc03f460e/packages/microservices/client/client-mqtt.ts#L172-L185

### Minimum reproduction code

-

### Expected behavior

Just like `send`, the packets should have the same format.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.3.1

### Packages versions

```json
platform-socket.io version : 8.3.1
platform-fastify version   : 8.3.1
microservices version      : 8.3.1
websockets version         : 8.3.1
schematics version         : 8.0.6
passport version           : 8.2.1
schedule version           : 1.0.2
swagger version            : 5.2.0
typeorm version            : 8.0.3
testing version            : 8.3.1
common version             : 8.3.1
config version             : 1.2.0
axios version              : 0.0.5
core version               : 8.3.1
cli version                : 8.2.1
 version                   : 1.6.1

```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I am sorry for not including a reproduction repo, as I have pinpointed the issue in the code.

**Comment by kamilmysliwiec** [comment]
Fixed here https://github.com/nestjs/nest/pull/9277 Thanks for reporting!
