### ISSUE TITLE
Use `threadId` of worker_thread when logging inside worker thread

### ISSUE THREAD

**Issue by gioragutt** [nestjs/nest#9281]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This isn't critical but could help out with working out logs.
I have an app that delegates jobs via pull to workers that run with `worker_threads`.

When logging, there's no indication that the log is emitted from a worker thread (compared to the main thread).

Example log:

```log
[Nest] 15054  - 03/02/2022, 9:59:30 AM     LOG [NestApplication] Nest application successfully started +0ms
```

### Describe the solution you'd like

I'd be happy if, optionally, the logger would append the thread id to (f.e) the PID, like so:

```
[Nest] 15054 (1)  - 03/02/2022, 9:59:30 AM     LOG [NestApplication] Nest application successfully started +0ms
```

Where `1` is the thread id.

### Teachability, documentation, adoption, migration strategy

If this won't be turned on by default, perhaps this can be activated via a method as follows:

```ts
import {Logger} from '@nestjs/common';
import {isMainThread, threadId} from 'worker_threads';

if (!isMainThread) {
  Logger.setThreadId(threadId);
}
```

### What is the motivation / use case for changing the behavior?

Ability to better understand and differentiate logs coming from worker threads.
I do believe the same might apply to `cluster` f.e, I didn't use it but I assume a similar problem might arise there.

**Comment by stanimirovv** [comment]
@kamilmysliwiec  @micalevisk 

is anyone working on this ? If not I would gladly give it a shot.

**Comment by micalevisk** [comment]
@stanimirovv I guess it's better to await Kamil's thoughts on this feat. I'd prefer this to be always enable, therefore you would just do a minor change below:

https://github.com/nestjs/nest/blob/94c2aca452ece5be12bb53b54a88d23d94f971f6/packages/common/services/console-logger.service.ts#L197

thanks :)

**Comment by kamilmysliwiec** [comment]
I'd say we should just make it somehow simpler to extend the current format of the messages so people who want to add certain details (such as a thread id) could extend the built-in logger and tweak 1 method.

**Comment by stanimirovv** [comment]
On it

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/9316
