### ISSUE TITLE
Nest doesnt want to compile dist correctly

### ISSUE THREAD

**Issue by lohevol** [nestjs/nest#9298]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

Nest does not compile the dist folder correctly. I first encountered this problem when **nest stopped updating my code**, after a few hours I opened the dist folder:
```
dist
  config
  server/src <- here are app module and auth module
  tsconfig.build.tsbuildinfo
```

when I run `npm run start` or `npm run start:dev` I get an error:
```
Error: Cannot find module 'C:\Users\server\dist\main'
    at Function.Module._resolveFilename(node: internal/modules/cjs/loader:933:15)
    in Function.Module._load(node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain](node:internal/modules/run_main:81:12)
    on node: internal/main/run_main_module:17:47
```

and it's true, main is in the dist/server/src folder which has been compiled into three files main.d.ts, main.js, main.js.map
but I don't understand why the root folder of the server is duplicated and files without the root folder are not compiled (for example, just dist/main)

before that all i saw was that nest didn't want to update my files, then i removed dist, ran `npm run build` to update my code but no success, nest created server folder (why?), and after that when i ran start i had the same error

### Minimum reproduction code

https://github.com/lohevol/nestjs-issue/

### Steps to reproduce

1. `npm run start:dev`
2. try to update anything
3. see what nothing doesnt update
or
1. `npm run start:dev`
2. delete dist (what i did when code stopped to update)
5. `npm run build` (i thought it can help to update)
6. `npm run start:dev`
7. See error

### Expected behavior

what nest compile files without server folder, just dist/main, dist/app.module, etc.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

no

### NestJS version

8.0.0

### Packages versions

```json
{
  "name": "server",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mongoose": "^9.0.2",
    "@nestjs/platform-express": "^8.0.0",
    "bcryptjs": "^2.4.3",
    "class-validator": "^0.13.2",
    "mongoose": "^6.2.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "jest": "^27.2.5",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
your repo didn't reproduce the issue

I got this after running `npm run start:dev`

```
src/app.module.ts:5:24 - error TS2307: Cannot find module '../../config/default' or its corresponding type declarations.

import { config } from '../../config/default';
```

---x

Also, 

![image](https://user-images.githubusercontent.com/13461315/156931512-294f206e-7323-42f8-ae6b-3feaee14e7e3.png)

what if you change that `sourceRoot` to `src` (which is the default)

**Comment by lohevol** [comment]
> your repo didn't reproduce the issue
> 
> I got this after running `npm run start:dev`
> 
> ```
> src/app.module.ts:5:24 - error TS2307: Cannot find module '../../config/default' or its corresponding type declarations.
> 
> import { config } from '../../config/default';
> ```
> 
> Also,
> 
> ![image](https://user-images.githubusercontent.com/13461315/156931512-294f206e-7323-42f8-ae6b-3feaee14e7e3.png)
> 
> what if you change that `sourceRoot` to `"src"` (which is the default when bootstraping a new app)
> 
> **EDIT**
> 
> You might need to adjust your `tsconfig.json` to fulfill your needs. `nest build` will use `tsc` (typescript compiler) to build the project.

I said that if the error is not reproduced, error occurred with bundle, then all files are still generated nested, and nest cannot access main, as well as new files, so nest did not react to the fact that I rewrote the code and issued the same thing, even if I could erase one file under a clean one, dist did not change in the end.

And at the expense of changing the path in nest-cli.json - it didn’t work, the server folder is also generated, it’s not clear how it gets there at all, I tried to immediately change the path in tsconfig.json but also to no avail

**Comment by micalevisk** [comment]
`rm -rf dist && npm run build`

```
dist/
├── app.controller.d.ts
├── app.controller.js
├── app.controller.js.map
├── app.module.d.ts
├── app.module.js
├── app.module.js.map
├── auth
│   ├── auth.controller.d.ts
│   ├── auth.controller.js
│   ├── auth.controller.js.map
│   ├── auth.module.d.ts
│   ├── auth.module.js
│   ├── auth.module.js.map
│   ├── auth.service.d.ts
│   ├── auth.service.js
│   ├── auth.service.js.map
│   └── dto
│       ├── create-user.dto.d.ts
│       ├── create-user.dto.js
│       └── create-user.dto.js.map
├── main.d.ts
├── main.js
├── main.js.map
├── schemas
│   ├── user.schema.d.ts
│   ├── user.schema.js
│   └── user.schema.js.map
└── tsconfig.build.tsbuildinfo

3 directories, 25 files
```

**Comment by lohevol** [comment]
> `rm -rf dist && npm run build`

```
dist/
├── app.controller.d.ts
├── app.controller.js
├── app.controller.js.map
├── app.module.d.ts
├── app.module.js
├── app.module.js.map
├── auth
│   ├── auth.controller.d.ts
│   ├── auth.controller.js
│   ├── auth.controller.js.map
│   ├── auth.module.d.ts
│   ├── auth.module.js
│   ├── auth.module.js.map
│   ├── auth.service.d.ts
│   ├── auth.service.js
│   ├── auth.service.js.map
│   └── dto
│       ├── create-user.dto.d.ts
│       ├── create-user.dto.js
│       └── create-user.dto.js.map
├── main.d.ts
├── main.js
├── main.js.map
├── schemas
│   ├── user.schema.d.ts
│   ├── user.schema.js
│   └── user.schema.js.map
└── tsconfig.build.tsbuildinfo

3 directories, 25 files
```
![nestjs-issue](https://user-images.githubusercontent.com/74186950/156939276-ef8fb399-ad19-445e-b98f-b9f0853cf1e2.jpg)

**Comment by micalevisk** [comment]
can you show your `tsconfig.json`? Could be hard to tell what's going on without a reproduction

**Comment by lohevol** [comment]
> can you show your `tsconfig.json`? Could be hard to tell what's going on without a reproduction

tsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src", <-
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

nest-cli.json:
```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "./src" <-
}
```

**Comment by jmcdo29** [comment]
Most likely this isn't nest's doing, but how Typescript's compiler works. It will try to keep your original directory structure in the dist of it's not a single directory (i.e. there's a directory with Typescript, that is not ignored, outside of the top level directory [usually src]). Best is just calling the Typescript compiler and trying to call `dist/main`. If that's failing, you've probably got a file outside of src that is being compiled.

**Comment by micalevisk** [comment]
@lohevol read this: https://www.typescriptlang.org/tsconfig/rootDir.html and this: https://www.typescriptlang.org/tsconfig#baseUrl

**Comment by lohevol** [comment]
> Most likely this isn't nest's doing, but how Typescript's compiler works. It will try to keep your original directory structure in the dist of it's not a single directory (i.e. there's a directory with Typescript, that is not ignored, outside of the top level directory [usually src]). Best is just calling the Typescript compiler and trying to call `dist/main`. If that's failing, you've probably got a file outside of src that is being compiled.

yes, it's true, I forgot to add the config folder to the repository, from which I import the configuration file... after deleting the import, everything worked, but how can I use the config now?
