### ISSUE TITLE
NestJS/ Fastify Controller wildcard not working as intended

### ISSUE THREAD

**Issue by MarcoLeko** [nestjs/nest#9299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using NestJS with the fastify adapter and trying to apply a wildcard to a controller route, it does not get picked up as a regex.
Applying the hint from the [documentation](https://docs.nestjs.com/middleware) did not help at all:

> WARNING
> The fastify package uses the latest version of the path-to-regexp package, which no longer supports wildcard asterisks *. Instead, you must use parameters (e.g., (.*), :splat*).

What I would like to achieve for my cat controller to match any request call that at least contains /cat in the url. So requests that should hit are:

* `http:localhost:3000/foo/bar/cat`
* `http:localhost:3000/cat`
* `http:localhost:3000/foo-bar/cat`

By doing something like this:

```
// cat.controller.ts
@Controller('(.*)/cat/')
export class CatController {
    @Get()
    @Head()
    @Render('cat')
    root(@Param('catId') catId: string) {
        return {
            catId,
        };
    }
}
```

* I can only reach the route on `http:localhost:3000/(.*)/cat/` but not on the expected routes above.
* However when setting the route to `/*/cat/` in the controller it will match any request path also `http:localhost:3000/foo/bar`. For this usecase any routes matches because the wildcard is at the start of the route handler, but it does not respect, that the route should at least have `cat` in the request path. 

I've provided a minimal reproducable stackblitz env for this: [Stackblitz](https://stackblitz.com/edit/nestjs-starter-demo-qkygfu?file=src/cat.controller.ts)

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-starter-demo-qkygfu?file=src/cat.controller.ts

### Expected behavior

The expected behaviour is that the wildcard logic should apply for the given controllers.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.26

### Packages versions

```json
{
        "@nestjs/common": "^8.2.6",
        "@nestjs/config": "^1.2.0",
        "@nestjs/core": "^8.2.6",
        "@nestjs/platform-fastify": "^8.3.1",
        "@nestjs/swagger": "^5.1.5",
        "@nestjs/terminus": "^7.2.0",
        "@nestjs/typeorm": "^8.0.3"
}
```

### Node.js version

14.14

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
