### ISSUE TITLE
Logger service improvements.

### ISSUE THREAD

**Issue by cojack** [nestjs/nest#93]
I would like to open discuss about logger, so far we have an Logger service in `@nest/common`, as it might be enough for development purpose, now it's kind of "thorn" fe: there is no other possibility to turn off messages from nest instead of set `NestEnvironment.RUN` to `TEST`, but it might imply some other things now or in future. Im not saying the Logger service is bad, but I would like to suggest to evolve this idea to add fe: a [debug](https://www.npmjs.com/package/debug) package and inside use them.

I will love to run app with `DEBUG=nest.*` and get all of the logs from nest when it's necessary.

What do you think about this?

**Comment by juan-manuel-alberro** [comment]
I believe the current logger is enough for develop purposes. For prod environments I created a Middleware/Filter for Sentry and it gave me better information for error tracking.

**Comment by cojack** [comment]
It's related to #104 
@kamilmysliwiec any thoughts?

**Comment by kamilmysliwiec** [comment]
Hey @cojack,
I've pulled your PR (thanks again!). After some time with it, I realized that I don't like this 'context prefix'. Also, the possibility to enable/disable logging is a good feature, but it's not helpful in the initializing app process.  However, there was one thing which I liked - the timestamps between the following lines, and I provided a similar feature in the `4.0.1` update. :slightly_smiling_face:

**Comment by Kamshak** [comment]
So there is no way to do this atm? Why diverge from the standard way debug does this?

**Comment by cojack** [comment]
@Kamshak the idea behind **debug** package instead anything else stand for usability. Most of the problems is about the space, the space you're runing out of. Im not saying that the Nest logger is the most verbose logger that you ever seen. But I have hope it would be, I have hope, the verbose opestion should scream on the scen <3

To be honest, I fallow in love with **debug** package because It allows me to turn on the debug statements of packages that I would like to investigate, many times in my life Im using winston pre-configured as syslog with rsyslog where I send logs out of the host, and without possibility (less complex) to send Nest logs to the my logger it's kind of complex. You can ask my why? The answer is very simple, recurrence, using the same schema across the builds and projects, solve your time and you can extend your actual knowledge to not discovered layer. I know it sound like utopia, especially the last part, you can just believe me. 

It's it, more or less, I try to explain my point of view.

Im open to any question, regards.
