### ISSUE TITLE
Register the authentication guard as a global guard to the `graphql gateway` does not work.

### ISSUE THREAD

**Issue by Farshid-Far** [nestjs/nest#9306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have created a GqlJwtStrategy and GqlJwtAuthGuard using `PassportStrategy` and `AuthGuard`,
and **is working great in my sub graph**.
I moved those configs and guard to the **gateway**, and I want to do authentication process in the gateway and only send decoded jwt payload to the sub graph,
but `context.req.user` is undefined in the sub graph resolvers, so it means **no authentication** is done in the gateway.

Here is my app module in the gateway:
```
@Module({
  imports: [
    GraphQLModule.forRootAsync<ApolloGatewayDriverConfig>({
      imports: [ConfigModule, ConsumerAuthModule],
      driver: ApolloGatewayDriver,
      useFactory: (config: ConfigService) => ({
        server: {
          cors: true,
          playground: false,
          plugins: [ApolloServerPluginLandingPageLocalDefault()],
        },

        path: '/graphql',
        useGlobalPrefix: true,
        gateway: {
          supergraphSdl: new IntrospectAndCompose({
            subgraphs: [{ name: 'consumer', url: config.getSubgraphs().consumer }],
          }),
        },
      }),
      inject: [ConfigService],
    }),

    SecretsModule,
  ],
  providers: [
    {
      provide: APP_GUARD,
      useClass: GqlJwtAuthGuard,
    },
  ],
})
export class AppModule {}
```

### Minimum reproduction code

No response

### Expected behavior

Register `guard` should do the authentication process and add jwt payload to the `context.req.user` in the graphql gateway.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

8.2.6

### Packages versions

```json
@nestjs/graphql@^10.0.4"
@nestjs/apollo@^10.0.4"
@nestjs/jwt@^8.0.0"
@nestjs/passport@^8.0.1"
```

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
As gateways are pretty much websocket servers, this would be my expected outcome. 
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

If you feel this really is a bug please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by Farshid-Far** [comment]
thanks @jmcdo29 ,
Does nestjs have any doc for setting up authentication with qraphql gateway?
I did not find anything.

**Comment by lucassith** [comment]
@jmcdo29 here is the same issue and reproduction repository:

https://github.com/nestjs/graphql/issues/3116
