### ISSUE TITLE
ValidationPipe with whitelisted property doesn't recognize dto fields

### ISSUE THREAD

**Issue by ramon159** [nestjs/nest#9309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
![image](https://user-images.githubusercontent.com/36459453/157371882-f5827c86-e843-421f-b6e9-9424f4087a29.png)

ValidationPipe does not recognize dto fields **without class-validators decorators**
![image](https://user-images.githubusercontent.com/36459453/157370656-facc4359-e873-455c-b13d-d8d417f2bf3c.png)

**Response when create a user:**
![image](https://user-images.githubusercontent.com/36459453/157371122-4da341d4-bff3-47cb-85d8-25187686b3bd.png)

### Minimum reproduction code

https://github.com/ramon159/acl-backend/releases/tag/v0.0.1

### Steps to reproduce

1.  `yarn`
2.  `echo "PORT = 3000" >.env`
3. remove decorators from create-user.dto
4.  `npm start:dev`
5. 
```
curl -X 'POST' \
  'http://localhost:3000/users' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "firstName": "string",
  "lastName": "string"
}'
```

### Expected behavior

ValidationPipe recognizing dto fields
like this:
![image](https://user-images.githubusercontent.com/36459453/157371448-de08988c-cb95-4fab-a71c-7e68cec2a2da.png)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/swagger": "^5.2.0",
    "@nestjs/typeorm": "^8.0.3",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "dotenv": "^16.0.0",
    "install": "^0.13.0",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.3.0",
    "typeorm": "^0.2.45"
  },
```

### Node.js version

v16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
`whitelist: true` means that if it isn't on the whitelist (i.e. decorated with a class-validator decorator) then the property should be rejected. This is class-validator's functionality, not a bug
