### ISSUE TITLE
Arguments for nested fields - graphql + typeorm

### ISSUE THREAD

**Issue by maginkgo** [nestjs/nest#931]
I have a question. 
How can I define arguments for nested fields. Suppose I want to consult all my Posts but limit and sort the comments. Thank you for your help. 

`
{
  allPosts {
    title,
    comments(limit: 5) {
      content
    }
  }
}
`

**Comment by kamilmysliwiec** [comment]
Hi @maginkgo,
Please, use StackOverflow for such questions.
