### ISSUE TITLE
Nestjs/Mongoose , nested model with discriminator is not triggered

### ISSUE THREAD

**Issue by MrPeanutss** [nestjs/nest#9313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello everyone,I have a problem with discriminators, I tried to find a case like mine but without success.

I followed the example on the official documentation: https://docs.nestjs.com/techniques/mongodb#discriminators
So far everything works.

My problem is the following, I have for project to have nested models, where the last nested model must be able to have a different schema according to the informed type.

Here is the mother and daughter model:

Parent model : 
```
@Schema()
export class Parent  {
  @Prop()
  name: string;
  @Prop({ type: [ChildSchema], required: true })
  elements: Child[];
}
export const ParentSchema = SchemaFactory.createForClass(Parent);
```
Child model :
```
@Schema({ discriminatorKey: 'kind' })
export class Child{
  @Prop({
   type: String,
    required: true,
    enum: [ClickedLinkEvent.name, SignUpEvent.name], })
  kind: string;
}
export const ChildSchema = SchemaFactory.createForClass(Child);
```

Module : 
```
@Module({
  imports: [
    MongooseModule.forFeature([
      {
        name: Child.name,
        schema: ChildSchema,
       discriminators: [
         { name: ClickedLinkEvent.name, schema: ClickedLinkEventSchema },
          { name: SignUpEvent.name, schema: SignUpEventSchema },
        ],
      },
    ]),
    
   MongooseModule.forFeature([
     {
        name: Parent.name,
        schema: ParentSchema,
      },
    ]),
  ],
  
  providers: [ParentService],
  controllers: [ParentController],
})
export class ParentModule {}
```

Discriminators schemas : 
```
@Schema()
export class SignUpEvent {
  kind: string;
  time: Date;

  @Prop({ type: String, required: true })
  user: string;
}

@Schema()
export class ClickedLinkEvent {
  kind: string;

  @Prop({ type: String, required: true })
  url: string;
}

export const ClickedLinkEventSchema = SchemaFactory.createForClass(ClickedLinkEvent);
```

When I save a Mother containing Daugther (with different type) . I manage to save them but if I don't fill in a required field, an error is expected but this is not the case, the objects are saved without exactly following the schema.
I don't know if I miss import something or just nestjs/mongoose don't manage deep schemas.

I thank you in advance.

### Minimum reproduction code

None

### Expected behavior

Expecting error schema, because fields are not specified.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

 "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mongoose": "^9.0.2",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/swagger": "^5.2.0",
    "mongoose": "^6.2.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.3.0"

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
