### ISSUE TITLE
Guard: Not getting called in e2e tests unless specified in useGlobalGuards

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [nestjs/nest#9314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have local auth strategy giard and it is beying called when running application but it is not called when running e2e tests. I have tried litterally everything. I see similar issue here ithout answer: https://github.com/nestjs/nest/issues/628

I have added all required elements to repro just could not run e2e tests.
In case it works - I am using not express but fastify adapter so code can be changed a bit to:

```
let app: NestFastifyApplication;

    beforeAll(async () => {
        const moduleFixture: TestingModule = await Test.createTestingModule({
            imports: [AppModule],
        })
            .compile();

        app = moduleFixture.createNestApplication<NestFastifyApplication>(new FastifyAdapter());
        await app.init();
        await app.getHttpAdapter().getInstance().ready();
    });



it('should return error if email was not found', async () => {
            const { body, statusCode } = await app.inject({
                method: 'GET',
                url: AuthRoutes.getFullRoute('signin'),
                payload: {
                    username: 'vytasbboy@gmail.com',
                },
            });

            expect(body).toBe(true);
        });
```

### Minimum reproduction code

https://codesandbox.io/s/proud-architecture-rrubq6?file=/src/guards/jwt-auth.guard.ts

### Expected behavior

Guards should be called same like in normal call

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by stanimirovv** [comment]
Where exactly are you binding the guard ? Is it global or supposed to be for a controller ? 
I don't see it in the code, but that should be an issue on my end

**Comment by jmcdo29** [comment]
Could you put this in a git so it's easier to work with in a local environment?

**Comment by micalevisk** [comment]
@vytautas-pranskunas- I _think_ I know what's going on, assuming you have that `app.useGlobalGuards` line in your `src/main.ts` file only

You're expecting that the `bootstrap` function of your `src/main.ts` to being called. But it won't unless you call it explicity in your test suite setup (due to how nodejs works)

You can circumvent that by removing the `app.useGlobalGuards` in favor of this another approach:

```ts

import { Module } from '@nestjs/common';
import { APP_GUARD } from '@nestjs/core';

@Module({
  providers: [
    {
      provide: APP_GUARD,
      useClass: YourGuardClassHere,
    },
  ],
})
export class AppModule {}
```

now you just need to add `AppModule` in your `imports` array if you want to enable the guard `YourGuardClassHere` globally.

**Comment by vytautas-pranskunas-** [comment]
Sry I forgot to add @useguard(LocalAuth) decorator on e dpoint in example but I ha e it in my code.

Glilobal Jwt decorator gets called but local is not

**Comment by micalevisk** [comment]
make sure you have registered the `LocalStrategy` as a provider.

Your `AppModule` that you shared should be `providers: [AppService, LocalStrategy]`

![image](https://user-images.githubusercontent.com/13461315/157499356-1a01590f-28ef-4852-b0b4-504d0406cbb0.png)

**Comment by vytautas-pranskunas-** [comment]
I was doing this example code very quick. As I have mentioned it is working when I am starting server locally but it does not when in e2e tests. I have it registered as provider 
<img width="740" alt="Screenshot 2022-03-09 at 20 29 45" src="https://user-images.githubusercontent.com/3918999/157507449-66a525b4-22d2-4549-8dc6-67c103ea9c5c.png">

**Comment by jmcdo29** [comment]
[__Can you provide a minimum reproduction as a git repo?__](https://minimum-reproduction.wtf)

**Comment by vytautas-pranskunas-** [comment]
I did: https://github.com/vytautas-pranskunas-/temp

if you run loclly and hit signin endpoint with any username you will see console output: ``` console.log('validating local strategy');``` meaning that local auth guard was visited.
If you run e2e tests you will see 'Unauthorized' message without console output
Or you can simply debug

**Comment by vytautas-pranskunas-** [comment]
nooo! because it never goes to AuthGuard - dont you see? I could get 401 but it should visit AuthGuard! same as when you run server

**Comment by jmcdo29** [comment]
It does go to the `AuthGuard`, and `AuthGuard('local')` calls to passport, passport returns an error because there's a missing `password`, Nest catches the error in the `AuthGuard()` and returns a 401.[ __this is how the `AuthGuard()` works__](https://github.com/nestjs/passport/blob/master/lib/auth.guard.ts#L83)

**Comment by vytautas-pranskunas-** [comment]
Ah, OK I will try to add password when I am home. Thanks for now.
