### ISSUE TITLE
memory cache in async service of controller is return empty object

### ISSUE THREAD

**Issue by dengshenkk** [nestjs/nest#9329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ajax api return {}

### Minimum reproduction code

null

### Steps to reproduce

AppModule

```
@Module({
// ...
imports: [
  CacheModule.register({
      isGlobal: true,
      ttl: 60,
    }),
],
providers: [
  {
    provide: APP_INTERCEPTOR,
    useClass: CacheInterceptor,
  }
]
})
class AppModule {}
```

controller 
```
@Controller('cats')
export class CatController {

 constructor(private catService: CatService){}
  @Get()
  findAll(){
    return this.catService.findAll()
 }
}
```

service
```
@Injectalbe()
export class CatService {
  constructor(
    private httpService: HttpService,
  ) {}


  async findAll(){
    return this.httpService
     .request({method: 'get', url: '/xxx', data: null})
     // async
     .pipe(map(async res => {

     const result = await this.httpService.get('/yyy')
     return { data: result.someProperty + res.someProperty }
     }))
 }
}
```

### Expected behavior

in the frist request, return result is expect 
and other request(default 5s within) is return result is '{}'

but i can't found any doc in anywhere, the problem is took a long time,  hope other developer find this answer

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

CacheInterceptor

### NestJS version

8.4.0

### Packages versions

```json
  "dependencies": {
    "@nestjs/axios": "^0.0.5",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^1.1.7",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/swagger": "^5.2.0",
    "@nestjs/terminus": "^8.0.4",
    "cache-manager": "^3.6.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "cookie-parser": "^1.4.6",
    "dayjs": "^1.10.7",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.3.0",
    "winston": "^3.6.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/cache-manager": "^3.4.3",
    "@types/cookie-parser": "^1.4.2",
    "@types/express": "^4.17.13",
    "@types/jest": "27.0.2",
    "@types/morgan": "^1.9.3",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.7",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
```

### Node.js version

14.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
