### ISSUE TITLE
Scope override not working

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [nestjs/nest#9330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I would like to chnage how injected service works in e2e tests changing scope to 'REQUEST' because i need constructor to be called before each test.

I have class with ```@Injectable()``` decorator. If i add scope to it ```@Injectable({scope: Scope.REQUEST})``` my tests passes. However without scope - they fail. In order to fight it I am doing following
```
const moduleFixture: TestingModule = await Test.createTestingModule({
            imports: [AppModule],
            providers: [{
                provide: PaymentsService,
                useClass: PaymentsService,
                scope: Scope.REQUEST,
            }],
        })
            .compile();
```

but tests continue to fail

### Minimum reproduction code

have no reproducable example because maybe it is obvious question but could not find answer in stackoverflow neither NestJs docs

### Expected behavior

scope of service changed

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
