### ISSUE TITLE
First-class integration for backend proxying

### ISSUE THREAD

**Issue by brandon-leapyear** [nestjs/nest#9348]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

Related, but slightly different: https://github.com/nestjs/nest/issues/8111
This issue would fix that issue, since there would be a first-class implementation of the feature. The error in that issue is due to manually working around the lack of this feature.

### Is your feature request related to a problem? Please describe it

I need to expose a path that proxies to another service using `express-http-proxy`. Currently, we have to manually add the middleware in `main.ts` with `app.use()`, but it would be great to get first-class support to get the following features for free:
1. Use of standard interceptors and guards (e.g. AuthGuard)
    * Avoid manually piping passport functions together to mimic AuthGuard
2. Idiomatic `@Get`/`@Post` routing (although use-cases would probably also involve proxying entire subpaths, so there'd need to be a specific decorator for "all routes, all methods")
3. Idiomatic mocking of providers in tests (e.g. mocking guards)

Currently, these have to be manually reimplemented (e.g. manually call `passport.authenticate()`, add an express error handler to convert errors to JSON instead of HTML, etc.). For example, my code currently looks like:
```ts
app.use(
  '/foo',
  // need to manually define the middleware to mimic Nest's logic to bypass
  // passport's serializeUser logic
  // https://github.com/nestjs/passport/blob/b035a343e368e7959b370aa480adb1c01804a1e6/lib/auth.guard.ts#L100-L111
  (req, res, next) => {
    passport.authenticate(
      'myauth',
      {},
      (e, user) => {
        if (e) {
          next(e)
        } else if (!user) {
          next(new UnauthorizedException())
        } else {
          req.user = user
          next()
        }
      }
    )(req, res, next)
  ),
  proxy('example.com', {
    // standard express-http-proxy options
  }
)
```

### Describe the solution you'd like

It would be nice to have something of the form
```ts
@Controller
class MyController {
  @HttpProxy('example.com', {
    // options
  })
  @AllSubPaths('/foo')
  @AuthGuard(...)
  proxyFooToExample() {
    return {
       // if specified, overrides the url in the decorator,
       // to support dynamic urls or loading a url from
       // a provider
      url: ...,
      // any other options specified can override options in decorator
    }
  }
}
```
I'm not sure exactly how it would work to provide a backend-agnostic implementation, but it could also be exposed as backend-specific packages, e.g. `@nestjs/express-http-proxy`. A backend-agnostic implementation could use `rxjs` to define the hooks for the proxy, in a similar manner to interceptors, to allow operations like modifying headers or the path before forwarding the request

Notably, one major thing preventing using, say, the `Interceptor` concept to implement this, is that NestJS automatically parses the body of the request, and there's no way to get back the original bytes to proxy along. This caused issues for us with JSON containing large numbers (not sure if this is fixed, e.g. in `body-parser`) where deserializing + reserializing is not completely lossless. Also, conceptually, a proxy route should do absolutely nothing to the body, but pass things through verbatim.

### Teachability, documentation, adoption, migration strategy

Ideally, the feature would be designed with an idiomatic API that should be very easy to seamlessly integrate with a standard understanding of NestJS

### What is the motivation / use case for changing the behavior?

See problem

**Comment by brandon-leapyear** [comment]
> Though, something like nginx or another reverse proxy might be a better solution overall.

Agreed, although we need it in our Nest application temporarily right now. And from a quick Google search, it seems like it's a not uncommon problem:
* https://stackoverflow.com/questions/50236234/create-proxy-in-nestjs
* https://stackoverflow.com/questions/66640069/nestjs-proxy-standard-route-handling
* https://stackoverflow.com/questions/63683416/how-to-protect-proxy-with-guards-in-nestjs
* https://stackoverflow.com/questions/58726968/proxied-requests-other-than-get-are-hanging-with-nestjs-and-http-proxy-middlewar

> I think [this pr](https://github.com/nestjs/nest/pull/9342) would fix that problem by allowing the `rawBody` to still exist

Great! That definitely solves one issue, but it's also generally annoying to define that Interceptor ad-hoc, plus making it first-class would prevent NestJS making changes that break the ad-hoc implementation (e.g. #8111)

**Comment by kamilmysliwiec** [comment]
Not sure why we need an additional decorator for this. What about using the middleware directly?

```typescript
@Get('foo')
getHello(@Req() req, @Res() res, @Next() next) {
  proxy('https://google.com', {
    // standard express-http-proxy options
  })(req, res, next);
}
```

We could also declare pre-configured proxy function as a constant instead of registering it inline:

```typescript
const httpProxy = proxy('https://google.com', {
  // standard express-http-proxy options
});

@Controller()
export class AppController {
  @Get('foo')
  getHello(@Req() req, @Res() res, @Next() next) {
    httpProxy(req, res, next);
  }
}
```

and to proxy everything:

```typescript
const httpProxy = proxy('https://google.com', {
  // standard express-http-proxy options
});

@Controller()
export class AppController {
  @All('*')
  proxy(@Req() req, @Res() res, @Next() next) {
    httpProxy(req, res, next);
  }
}
```

**Comment by brandon-leapyear** [comment]
Well for one, nestjs automatically parses the body, so it doesn't pass the actual raw data (see #9342, referenced above). But in general, requests are automatically parsed by NestJS, causing discrepancies when passing the request through.

e.g. using this workaround on a new NestJS project proxying `/` to `httpbin.org`, there are the following behaviors:
* json keys should not be deduplicated
```console
$ curl -H 'content-type: application/json' httpbin.org/post -d '{"asdf": 1, "asdf: true}'
{
  "data": "{\"asdf\": 1, \"asdf\": true}",
}

$ curl -H 'content-type: application/json' localhost:3000/post -d '{"asdf": 1, "asdf": true}'
{
  "data": "{\"asdf\":true}"
}
```
* json whitespace should not be normalized
```console
$ curl -H 'content-type: application/json' httpbin.org/post -d '{"asdf": 1     }'
{
  "data": "{\"asdf\": 1     }",
}

$ curl -H 'content-type: application/json' localhost:3000/post -d '{"asdf": 1     }'
{
  "data": "{\"asdf\":1}"
}
```
* big numbers should not be truncated
```console
$ curl -H 'content-type: application/json' httpbin.org/post -d '{"asdf": 12481294621783612638172632817}'
{
  "data": "{\"asdf\": 12481294621783612638172632817}"
}

$ curl -H 'content-type: application/json' localhost:3000/post -d '{"asdf": 12481294621783612638172632817}'
{
  "data": "{\"asdf\":1.2481294621783613e+28}"
}
```
* GET query params are not passed
```console
$ curl "httpbin.org/get?asdf=1"
{
  "args": {
    "asdf": "1"
  }
}

$ curl "localhost:3000/get?asdf=1"
{
  "args": {}
}
```

**Comment by kamilmysliwiec** [comment]
> Well for one, nestjs automatically parses the body, so it doesn't pass the actual raw data (see https://github.com/nestjs/nest/pull/9342, referenced above). But in general, requests are automatically parsed by NestJS, causing discrepancies when passing the request through.

@brandon-leapyear you can turn this off by setting one boolean to `false`.

```typescript
const app = await NestFactory.create(AppModule, {
  bodyParser: false,
});
```

![image](https://user-images.githubusercontent.com/23244943/159442618-34ba741f-7401-4c7a-8acc-6121a2bd5c0b.png)

![image](https://user-images.githubusercontent.com/23244943/159442737-f0785d18-618f-4f29-b02c-3a835cb26ba4.png)

![image](https://user-images.githubusercontent.com/23244943/159442829-3dbef6dc-aa6a-40d1-8186-f5a25bef03d2.png)

**Comment by brandon-leapyear** [comment]
Yes, but the idea is that I have other NestJS routes that do need
bodyparser. If I didnt have other NestJS routes, I would just be using
plain express with express-http-proxy.

**Comment by kamilmysliwiec** [comment]
But you can selectively mount body-parser to specific routes using `MiddlewareConsumer`.
You can also use `MiddlewareConsumer` to register `body-parser` for all routes and just exclude those that are proxied.

Not sure what's the reason to reinvent the wheel here.

**Comment by jmcdo29** [comment]
Rather than creating our own `@Proxy()` that would do what the underlying package already does, is there a way we could add a `req.rawBody` by default so that we have the parsed body available at `req.body` as per usual, and the raw body at `req.rawBody` (to not conflict with Fastify's `req.raw`) so that webhooks _and_ proxies can just work without needing to reconfigure around body-parser?

**Comment by kamilmysliwiec** [comment]
IMO if we decide to merge https://github.com/nestjs/nest/pull/9342 we'll basically fill all the gaps and cover all possible use-cases. Hence, I don't think we'll be adding first-class supported methods/dedicated annotations in the foreseeable future.
