### ISSUE TITLE
Provide a CodeSandbox template for a reproduction

### ISSUE THREAD

**Issue by kykungz** [nestjs/nest#9349]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I've seen a lot of issues/conversation ended with a "Please provide a minimum reproduction repository" response.

There are many reasons why the issue opener choose to ignore it and left the issue abandoned:
1. Sometimes the problem is very obvious, and only require one line of code to reproduce
2. Creating a new repository and setting up a whole new NestJS application for every issue is very cumbersome

There are also many downsides of this kind of issue opening experience:
1. People turned away from NestJS because they feel like asking questions and getting their issues solved are very hard in NestJS community
2. When an issue is solved, some people will delete their reproduction repository because it's a mess. Leaving the solved issues unviewable

I know it's hard and annoying for the moderators to help solving an issue without providing a minimum reproduction repository. So I think there should be a better way where we could improve the process/experience for both parties.

### Describe the solution you'd like

Provide a CodeSandbox template with minimal NestJS setup, so that people can quickly create a minimum reproduction code.

Benefits of having CodeSandbox template:
1. Issue opener can quickly provide a minimum reproduction code
2. Moderators can easily view the issue without having to clone the production repository for every issue
3. We can be sure that the environments are the same

I don't have a CodeSandbox template of NestJS yet, and feel like the community/moderators here would have a better idea on which modules/setup should be included in the template.

### Teachability, documentation, adoption, migration strategy

NestJS team or moderators can reply with a template when asking for minimum reproduction repository.

Instead of replying:
> "Please provide a minimum reproduction repository"

We should have a template like (copied from [Material UI Community](https://github.com/mui/material-ui)):
> Please provide a CodeSandbox (https://material-ui.com/r/issue-template-latest), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
>
> Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

### What is the motivation / use case for changing the behavior?

I've opened some issues on NestJS, and seen a lot of abandoned old issues on NestJS. I personally feel like the experience on getting help in NestJS community is very difficult.

Then I came across the experience on [Material UI Community](https://github.com/mui/material-ui), which has a very good getting helped experience, mainly just because of this respond and a quick CodeSandbox template:

![Screen Shot 2565-03-17 at 15 25 31](https://user-images.githubusercontent.com/9304909/158767963-f8a59b51-3be2-4cad-b7f5-44615f08c2da.png)

This way, I can quickly create a minimum reproduction repository, and the moderators can quickly debug on my issue.

**Comment by kamilmysliwiec** [comment]
Both CodeSandbox, as well as Stackblitz, provide templates for NestJS out-of-the-box. In fact, many people are now using those to provide minimum reproduction repositories, if you check out some of the recent issues.

**Comment by kykungz** [comment]
@kamilmysliwiec
I know that some people did already provide a minimum reproduction repository using these tools, but we will miss the ones that haven't heard about CodeSandbox or Stackblitz, or not knowing that it already has a NestJS template.

For example, issues number 9263, 9097, 9306 (I'm not adding hyperlinks because I don't want to notify these issues)

My point is to guide users who doesn't know about these tools by changing the reply from "Please provide a minimum reproduction repository" to also include CodeSandbox or Stackblitz links by default.

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/158774344-6709c1c4-54dc-4506-9fb5-93f23da6390c.png)

https://github.com/nestjs/nest/issues/new?assignees=&labels=needs+triage&template=Bug_report.yml

**Comment by kykungz** [comment]
Yeah I also saw that, but if people missed that, it's unlikely that they will find it again after the issue has been posted. At least when replying to ask for reproduction repository, just repeat that full message again would be very kind 😄

**Comment by kamilmysliwiec** [comment]
Updated my template message to say this:

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

From now on.

**Comment by jmcdo29** [comment]
I will mention, the reason _I_ usually ask for git repos over StackBlitz or CodeSandbox links is that when it's a git repo it's easier to run and modify and add in debug logs where I need (or at least in my experience), and it allows for us to fork and make a PR if we have the time to show what the problem was and what the solution is. I do recognize that it can take some time to set up a git repo, but between `nest new` and `gh repo create` it's all pretty straightforward from the command line, in my experience
