### ISSUE TITLE
DI doesn't inject a scoped request provider using @Inject and Symbol

### ISSUE THREAD

**Issue by BrendonMFO** [nestjs/nest#9352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The DI isn't injecting/resolving a provider through @Inject when the property is a Symbol

This doesn't work:
```typescript
@Injectable()
class TestTargetService {
  @Inject() // Scoped Request
  private readonly testService: TestService;

  @Inject(SYMBOL_INJECTOR) // Scoped Request
  private readonly [SYMBOL_SERVICE]: SymbolService;

  getTestService() {
    return this.testService;
  }

  getSymbolService() {
    return this[SYMBOL_SERVICE]; // undefined
  }
}
```
But injecting those same providers through the constructor, the DI resolves all providers perfectly

This does work:
```typescript
@Injectable()
class TestTargetService {
  @Inject(SYMBOL_INJECTOR)
  private readonly [SYMBOL_SERVICE]: SymbolService;

  constructor(private readonly testService: TestService) {}

  getTestService() {
    return this.testService;
  }

  getSymbolService() {
    return this[SYMBOL_SERVICE]; // Symbol Service Instance
  }
}
```

I've spent a time debugging and found something about the cache of the metadatas. The property's instance wrapper was a new property but it was supposed to be an element inside the array, increasing its length. Was it supposed to be added as a new property?

![bug_detail](https://user-images.githubusercontent.com/7195926/159033262-4c2d218a-6012-440b-9830-431edfc39fec.png)

### Minimum reproduction code

https://github.com/BrendonMFO/nestjs-injection-bug

### Steps to reproduce

1. `npm i`
2. `npm test`

There're two test files each one using a different way to inject the providers

### Expected behavior

The DI should be able to resolve the dependencies through constructor and the decorator

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.1

### Packages versions

```json
"dependencies": {
  "@nestjs/common": "^8.0.0",
  "@nestjs/core": "^8.0.0",
  "@nestjs/platform-express": "^8.0.0",
  "reflect-metadata": "^0.1.13",
  "rimraf": "^3.0.2",
  "rxjs": "^7.2.0"
}
```

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
indeed. Here's a minimum reproduction of this: https://gitlab.com/micalevisk/nestjs-issue-9352

**Comment by micalevisk** [comment]
I was looking at the value `constructor`. But this works:

```ts
const TokenSymbol = Symbol()
const A = Symbol('A')
const B = Symbol('B')

@Module({
  providers: [
    { provide: TokenSymbol, useValue: 'hello' },
    { provide: 'my-str-token', useValue: 'world' },
  ],
})
export class AppModule {
  @Inject(TokenSymbol) private readonly [A]: string
  @Inject('my-str-token') private readonly [B]: string

  onApplicationBootstrap() {
    console.table({ hello: this[A], world: this[B] })
  }
}
/*
┌─────────┬─────────┐
│ (index) │ Values  │
├─────────┼─────────┤
│  hello  │ 'hello' │
│  world  │ 'world' │
└─────────┴─────────┘
*/
```

thus looks like the issue is related to `Scope.REQUEST`

**Comment by MyAeroCode** [comment]
I have fixed what was causing this issue. 
I'll submit a PR as soon as I'm done writing the test code 😃

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/9456
