### ISSUE TITLE
Throw error if unable to connect to Redis

### ISSUE THREAD

**Issue by Clee681** [nestjs/nest#9353]
### Is there an existing issue that is already proposing this?

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, if the `BullModule` is unable to connect to Redis, it fails silently.

```js
BullModule.forRootAsync({
  imports: [ConfigModule],
  useFactory: async (configService: ConfigService) => ({
    redis: {
      host: configService.get('QUEUE_HOST'),
      port: configService.get('QUEUE_PORT'),
    },
  }),
  inject: [ConfigService],
});
```

### Describe the solution you'd like

An error should be thrown (e.g. a connection timeout).

### Teachability, documentation, adoption, migration strategy

Users will be able to easily see if the redis connection is failing.

### What is the motivation / use case for changing the behavior?

The motivation is to not silence a real issue.

**Comment by micalevisk** [comment]
duplicate #9264

Please report on the right repo next time: https://github.com/nestjs/bull/issues/1076
