### ISSUE TITLE
crash run fresh project

### ISSUE THREAD

**Issue by AmrAbdalrahman** [nestjs/nest#9354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I created a new fresh project through 
`nest new test-project`
when  run 
`npm run start:dev`
I got 

```
(node:15523) ExperimentalWarning: queueMicrotask() is experimental.
 1: 0x100063a65 node::Abort() [/usr/local/bin/node]
 2: 0x1000bdbd5 node::Chdir(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 3: 0x100224b27 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 4: 0x1002240f6 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 5: 0x1002237f0 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x34a00544fb7d 
 7: 0x34a00540e458 
```

### Minimum reproduction code

https://github.com/AmrAbdalrahman/test-nest

### Steps to reproduce

1. nest new test-project
2. npm run start:dev

### Expected behavior

run successfully of port 3000

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

```json

[System Information]
OS Version     : macOS Big Sur
NodeJS Version : v11.6.0
NPM Version    : 6.14.8 

[Nest CLI]
Nest CLI Version : 8.2.3 

[Nest Platform Information]
platform-express version : 8.4.1
schematics version       : 8.0.8
testing version          : 8.4.1
common version           : 8.4.1
core version             : 8.4.1
cli version              : 8.2.3


```

### Node.js version

11.6.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I guess node 11 isn't supported. Can you try nodejs 12?

https://github.com/nodejs/Release

![image](https://user-images.githubusercontent.com/13461315/159168798-5612d6e9-31a8-4181-b483-7fbfab09934c.png)

**Comment by Tony133** [comment]
I tried the minimal production on 16.13.1 LTS node and it works fine.

**Comment by AmrAbdalrahman** [comment]
@micalevisk @Tony133 thanks a lot its causes because of node version **`11.6.0`** 
I upgraded to version **`16.14.2`**  works fine now.

**Comment by micalevisk** [comment]
I guess we need to check out what's the minimum version of nodejs that nestjs packages supports and then add the [`engines.node`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) field on every `package.json`

**Comment by Tony133** [comment]
On the `package.json` of the nest repository there is this:
```
"engines": {
    "node": "> = 10.13.0"
  },
```
Maybe it needs to be updated, but we should check the dependencies that are used within it.

**Comment by micalevisk** [comment]
I've run the following script to list all `engines.node` entry on every hard dependency of each package that are living under `nestjs/nest` repo. Not every package has that entry, of course


The results are:

<details>
<summary>for <code>@nestjs/common</code></summary>

```
>=6
```

</details>


<details>
<summary>for <code>@nestjs/core</code></summary>

```
>=8.0.0
>=6
>= 6
```

</details>


<details>
<summary>for <code>@nestjs/microservices</code></summary>

```
>=6
```

</details>


<details>
<summary>for <code>@nestjs/platform-express</code></summary>

```
>= 0.8
>= 0.10
>= 0.10.0
>= 0.10.0
```

</details>


<details>
<summary>for <code>@nestjs/platform-fastify</code></summary>

```
>=10.0.0
```

</details>


<details>
<summary>for <code>@nestjs/platform-socket.io</code></summary>

```
>=10.0.0
```

</details>


<details>
<summary>for <code>@nestjs/platform-ws</code></summary>

```
>=10.0.0
```

</details>


<details>
<summary>for <code>@nestjs/testing</code></summary>

```
(none)
```

</details>


<details>
<summary>for <code>@nestjs/websockets</code></summary>

```
>=6
>= 6
```

</details>

Thus, the minimum one that covers everything is `>=10.0.0`. But we know that this is wrong. Maybe the deps are not up to date

**Comment by jmcdo29** [comment]
[Our docs do show >10 except for 13](https://docs.nestjs.com/first-steps#prerequisites), but maybe that should be updated as well. Feel free to open a PR aligning all of the `engine` properties

**Comment by Tony133** [comment]
Yes, I think maybe updating the documentation could be useful, maybe we should put to use nodejs version 14 or 16 directly since version 12 next month is end of life.

Maybe something like this:

Please make sure that [Node.js](https://nodejs.org/)(>= 14.0.0 or LTS ) is installed on your operating system.
