### ISSUE TITLE
Usage of TS Discriminated Union for Provider type

### ISSUE THREAD

**Issue by ajubin** [nestjs/nest#9357]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When I'm declaring the following `Provider`, I'm expecting TS to error  because `inject` key has to be used in coordination with `useFactory`, not with `useClass` but I see no error.

```ts
const MyProvider : Provider = {
   provide: 'serviceA', 
   useClass: ServiceAClass,
   inject: ['deps_for_serviceA'] 
}
```

The error I'm waiting for is the following

```
 Object literal may only specify known properties, and 'inject' does not exist in type 'ClassProvider'.
```

### Describe the solution you'd like

TS doesn't throw because for the discriminated union feature to works, ts needs a defined string to differentiate between multiple types (maybe not only string, but I didn't find the exact rules for this), see the doc here https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions

Here's a link to TS playgrounds that show a possible solution

- What Nest does in a simplified  manner : https://www.typescriptlang.org/play?#code/FAegVGwARlDCBXATkgpgOwC5QM4EsBbABwBs8AzPVAEykNNQI0wENM8B7dKD8qTAJ5FUUAApIOANzzVUSOtwAqAZWhgQwQcKgBJdACtUAY3ZdFHANYYoAXlyYkedAHMA3MCeY55FkZGKhVAAeRVsoFnQBAD4oVAAPL3RqHCgAMQR0E05uAG9oKHRUAHcoAAoAOkqWJGccAC5wyIBtAF0ASgbFdwBfYA8sb18ROBIWHBxxKRk5ELCI6Kg8qCgiCWlZBr1DLLNLDHdlhBxUEbH6qADhEKievs9BvzTfTA4kAUn1mdC7eZillbW002BmMpnQ5is6AOUCOqFSz1eAgaFSqNXO81abVsMS6+Sc20wAH4GgBBFAsARBLag7IQ6w3fLAXpaEQfaZIWY-SIxOyncZs2QcxQxAA+TxMiIFXwZfSMo3GUGUcmkfhJi16wCMXBw2FWU0FDSl8js-z1nwaAHI4AB5ABytoAonBFDo7RaADT5WF885KpAq1Akz3LEAgKAACTkqHdF2UUGoHFQOHQFuwWuIoycUCKAAso2M6NgcDmOAgSNQ8SCTA1WkzgEA

- How we could do : https://www.typescriptlang.org/play?#code/FAegVGwARlCCUAOB7AzqglgIwDYFMpVkcBXAFw2QDtowRgyBPRAgSSoCs8BjC6gFWQBrPFSgBeQmQBOGKgHMA3MDlk80gGYBDbgX7M8AHn4SoWqowB8UPAA81VACaooAMRJVelMQG9oUKjwAdygACgA6SK1peVQALjMLAG0AXQBKBP5lAF9gFSo1TR0CAGEcLXQABWlkADcMR3VjU3MrKD8oKCYWBIBybnL0XoAaf0Qa+saE9i4vAWFRZU6SVDwyiviofRZjSxy81XVtXTcdMmRpRmq6hqaTSVbrDq6DPuPzy5Gxidvpzh4+FRBCIqEsoCs8K4zhdGAkIlEYptWqk0hJrFl-HJZmQAPwJODSaRaRiGGYA7zA0RQPb+YC5boEa6TO4tCzWSTrKo-RrSXZQAA+p14MKZt15-BpeQGGygAGV1PVdAgfLlgNxqKgyEhueoEqKeaZngy+tKhqNOuMblMoL0SgB5AByDoAoiV+KxHV9lqtOZt5dJFXg4OaoCAQFAABLqPDDLayqCOZB4FzqgC2iHKckx-14CVSdLyQA

There's a tradeoff though, because we muse precise a `type` on the Provider. Maybe other solutions exists, or maybe we should open an issue directly on TS
 

### Teachability, documentation, adoption, migration strategy

For this part, see the ts playground above

### What is the motivation / use case for changing the behavior?

I encounter a bug where `inject` was used with a `useClass`, so I was expecting the list of dependencies in the `inject` to be effectively injected, but it was not the case. 

I'd be happy to help doing the change btw, and thanks again for the work done

**Comment by jmcdo29** [comment]
I'd love to see this come in. We'd have to wait for v9 because it could unintentionally break some people's builds (though they shouldn't be like this in the first place it still could be). @kamilmysliwiec thoughts on better types for `Provider`?

**Comment by kamilmysliwiec** [comment]
Adding an extra property to the custom provider definition only for the sake of instructing users that `inject` should be used only in combination with `useFactory` sounds to me like a huge overkill, not to even mention how many codebases we would break, and how many articles/learning materials would become broken & outdated.

There should be a way to keep using the existing structure and still improve the UX, somehow. I'll see if there's anything we can do

**Comment by kamilmysliwiec** [comment]
@micalevisk this is great! Would you like to create a PR?

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/nest/pull/9383
