### ISSUE TITLE
invalid socket connection after microservice restart

### ISSUE THREAD

**Issue by JeffreyArt1** [nestjs/nest#9363]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

### Potential Commit/PR that introduced the regression

#9303

### NestJS version

8.4.1 - 8.4.2

### Describe the regression

After a change introduced in #9303, the `connect()` method doesn't longer evaluates the `isConnected` property. In my tests, after re-connecting a microservice, `bindEvents()` calls `handleClose()` on socket close event which turns the socket into `null` and `isConnected = false` causing this error `Cannot read properties of null (reading 'sendMessage')` on re-connection. 

### Input code

```ts

```

### Expected behavior

A new connection if the old doesn't work anymore.

**Comment by kamilmysliwiec** [comment]
Could you please create a minimum reproduction repo/test?

**Comment by kamilmysliwiec** [comment]
Fixed in 8.4.3

**Comment by JeffreyArt1** [comment]
uff no bulto
