### ISSUE TITLE
Microservice RabbitMQ multi url failed reconnect 

### ISSUE THREAD

**Issue by simonabler** [nestjs/nest#9364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

``` typescript
import { Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { ClientProxyFactory, ClientsModule, Transport } from '@nestjs/microservices';
import { AUTH_SERVICE } from './auth.constants';
import { AuthService } from './auth.service';


@Module({
    imports: [
        ClientsModule.register([
            {
                name: AUTH_SERVICE,
                transport: Transport.RMQ,
                options: {
                    urls: ['amqp://10.x.x.x:5672','amqp://10.x.x.x:5672','amqp://10.x.x.x:5672'],
                    queue: 'auth_validator',
                    queueOptions: {
                        durable: false
                    },
                    socketOptions:{
                        heartbeatIntervalInSeconds:5,
                        reconnectTimeInSeconds:5
                    }
                },
            }])
    ],
    providers: [AuthService],
    exports: [AuthService]
})
export class AuthModule { }
```

This will call the send function:

```typescript
 ping() {
        const pattern = { cmd: 'ping' };
        return firstValueFrom(this.client.send(pattern, "").pipe(timeout(5000)))
    }
```

I will register the client module with multiple urls. But, the first RabbitMQ broker is not reachable and the expected behavier should be a reconnect to the next url. Therefore, AmqpConnectionManager is first sending a "connectFailed" event and then reconnects to the second url. But, in this [commit](https://github.com/nestjs/nest/commit/d3b627fa007420d3f891bddac36135409aa9eefb#diff-be75f6c9c2c9a1228b67565a1a57063e16dceb983af8ee57fefb1bbeb2168dc7R122) the client RMQ connect function is also listening to the connectFailed event and then throws an error. 

commit: d3b627fa007420d3f891bddac36135409aa9eefb

First quick and dirty test was to remove `connectFailed$` from `return merge(source$, disconnect$, connectFailed$).pipe(first());` 
The first attempt will fail in a timeout exception but after that the AmqpConnectionManager is connected.
But, of course this will break some other functions.

### Minimum reproduction code

[Repo](https://github.com/simonabler/nestjs-microservice-rabbitmq-reconnect-issue-9364)

### Steps to reproduce

See Repo

### Expected behavior

connect to the next url without thrown error

### Package

- [X] <code>@nestjs/microservices</code>
- [X] Other (see below)

### Other package

amqp-connection-manager, amqplib

### NestJS version

8.4.1

### Packages versions

```json
"@nestjs/common": "^8.0.0",
"@nestjs/config": "^2.0.0",
"@nestjs/core": "^8.0.0",
"@nestjs/microservices": "^8.4.1",
"@nestjs/platform-express": "^8.0.0",
"amqp-connection-manager": "^4.1.1",
"amqplib": "^0.8.0",
"rxjs": "^7.2.0",
```

### Node.js version

v14.18.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [x] Linux

**Comment by Tony133** [comment]
Hi @simonabler , I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

Have you tried posting this issue on the [Discord](https://discord.com/invite/G7Qnnhy) support channel as well?

**Comment by simonabler** [comment]
Hi @Tony133, thanks for your answer. I made an update and added a minimal reproduction repository with description in the readme. 

Thanks for the hint with Discord, i will try it there too!

**Comment by simonabler** [comment]
@Tony133 unfortunately, nothing happened on [discord](https://discord.com/channels/520622812742811698/616321218567471151/956164045038301194)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/9425
