### ISSUE TITLE
NPM workspace, changing out directory not working (module not found)

### ISSUE THREAD

**Issue by Maryannah** [nestjs/nest#9367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Create a NPM workspace

```bash
npm init # then hit enter many times, add "server" workspace to package.json
npx @nestjs/cli new server -s -g
npm i -w server
```
Edit the `tsconfig.json` : 

```json
{
  "compilerOptions": {
    "outDir": "../dist/apps/server",
  }
}
```

Run `npm start -w server`

```
> my-app@1.0.0 serve:server
> npm start -w server


> server@0.0.1 start
> nest start

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@nestjs/core'
Require stack:
- S:\my-app\dist\apps\server\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (S:\my-app\dist\apps\server\main.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'S:\\my-app\\dist\\apps\\server\\main.js' ]
}
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: server@0.0.1
npm ERR!   at location: S:\my-app\server
```

From my understanding, the final "bundle" is looking for the node_modules dependencies relative to its root. If I don't change the output directory, it works fine, bt my node_modules are in the `server` folder, so putting it in the root directory does not work.

Any ideas on how to make this work ? 

Sorry if I am not in the right place to ask this but I figured this would be a bug ?

### Minimum reproduction code

https://i-cant-its-a-private-project.sorry

### Expected behavior

Should work out of the box as explained in the description

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

NPM itself

### NestJS version

7.5.1

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/platform-express": "^7.5.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@types/express": "^4.17.8",
    "@types/jest": "^26.0.15",
    "@types/node": "^14.14.6",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "eslint": "^7.12.1",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-prettier": "^3.1.4",
    "jest": "^26.6.3",
    "prettier": "^2.1.2",
    "supertest": "^6.0.0",
    "ts-jest": "^26.4.3",
    "ts-loader": "^8.0.8",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5"
  },

}
```

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

As said, not changing the output directory works fine, as well as copying the dependencies in the root package.json. But I would like not to use either solution ...

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
