### ISSUE TITLE
Allow chaining multiple exception filters

### ISSUE THREAD

**Issue by zoltan-mihalyi** [nestjs/nest#9372]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In exceptions-handler and external-exceptions-handler, only the first matching filter is called. It is not possible to call the whole filter-chain (and to use default handler without extending BaseExceptionFilter)

### Describe the solution you'd like

A layered approach would be nice, similar to how express middlewares work. A middleware can the next layer when it doesn't handle the request.

In exception handlers, instead of calling some kind of next function, throwing an exception would be the solution.
The logic in exceptions-handler would be:
- try to call first filter.
- if this call is successful, return
- if an exception is thrown, go to next filter
- if no more filters left, run the default exception handling logic (BaseExceptionFilter)

### Teachability, documentation, adoption, migration strategy

AFAIK, exception handlers should not throw an exception.
Exception handlers not throwing exception should work the same as before: a single exception handler is called.

### What is the motivation / use case for changing the behavior?

In my application i need to
- transform exceptions
- collect exception metrics for prometheus

This should be achieved by chaining exception filters

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
