### ISSUE TITLE
WebSocket gateway path versioning

### ISSUE THREAD

**Issue by 95gabor** [nestjs/nest#9376]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hi!

I have a [WebSocketGateway](https://docs.nestjs.com/websockets/gateways#gateways) and I use [API versioning](https://docs.nestjs.com/techniques/versioning). It would be great if I could use version parameters in the WebSocketGateway like in the Controller decorator.

### Describe the solution you'd like

```ts
@WebSocketGateway({
  path: '/ws',
  version: ['1'], // or '1', VERSION_NEUTRAL
})
```

then the generated endpoint would be `/v1/ws`

### Teachability, documentation, adoption, migration strategy

I think this would not be a breaking change and this would fit in the existing decorator concept.

### What is the motivation / use case for changing the behavior?

It developers want to use versioned WebSocket endpoint it would be useful.

**Comment by meness** [comment]
A simple workaround is using different namespaces for versioning, for example `chat.v1`, `chat.v2`, etc.

```typescript
@WebSocketGateway(80, {
  namespace: 'chat.v1',
})
```

**Comment by rzl** [comment]
i has a not good idea

`
require('express-ws')(app.getHttpAdapter().getInstance(), app.getHttpServer())
app.getHttpAdapter().getInstance().ws(xbbWebsocket._path, (ws, req, next) => { xbbWebsocket._handle(ws, req, next) })
`

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10597
