### ISSUE TITLE
Poor documentation deprecated HttpModule / @nestjs/axios

### ISSUE THREAD

**Issue by GustavoContreiras-Feegow** [nestjs/nest#9385]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The only information about @nestjs/axios that I can find is that HttpModule is deprecated and we should use @nestjs/axios.
But there isnt any example on the web or explanation on how to use it.

### Describe the solution you'd like

Examples.

### Teachability, documentation, adoption, migration strategy

https://docs.nestjs.com/migration-guide#http-module
https://docs.nestjs.com/techniques/http-module

### What is the motivation / use case for changing the behavior?

I need to understand how to use @nestjs/axios.

**Comment by jmcdo29** [comment]
> [Axios](https://github.com/axios/axios) is richly featured HTTP client package that is widely used. Nest wraps Axios and exposes it via the built-in HttpModule. The HttpModule exports the HttpService class, which exposes Axios-based methods to perform HTTP requests. The library also transforms the resulting HTTP responses into Observables.

What else do you want on top of this? What examples are you looking for in the end? It's pretty much just axios, configured at a module level, and using RxJS Observables instead of the default promises.

**Comment by micalevisk** [comment]
You can use [this query](https://cs.github.com/?scopeName=All+repos&scope=&q=%22%40nestjs%2Faxios%22+path%3Apackage.json+-org%3Anestjs) on https://cs.github.com to find repositories that have `@nestjs/axios` in their `package.json` file (but not the ones from @nestjs org)

![image](https://user-images.githubusercontent.com/13461315/160177511-8684e2c6-24d9-4b9c-b691-f6d28ec4ef4e.png)

**Comment by GustavoContreiras-Feegow** [comment]
Some minutes later I figured that the only thing to do after the deprecation is change `import { HttpModule } from '@nestjs/common'` to `import { HttpModule } from '@nestjs/axios'`

**Comment by jmcdo29** [comment]
You know, like it says in the [migration guide](https://docs.nestjs.com/migration-guide#http-module)

> The `HttpModule` exported from the `@nestjs/common` package has been deprecated and will be removed in the next major release. Instead, please use the `@nestjs/axios` package (otherwise, there are no API differences).

**Comment by shiva2021** [comment]
I think that this should still be mentioned somewhere on the HTTP Module documentation page and optionally on the migration guide. Just my unpopular opinion :)

**Comment by micalevisk** [comment]
@shiva2021 the docs are now for v9, not v8. That change was done in v8 (from v7)
