### ISSUE TITLE
Wrong typing for filter

### ISSUE THREAD

**Issue by spearmootz** [nestjs/nest#9387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i have this same issue here https://github.com/nestjs/nest/issues/8978 not sure why this issue was closed as it is a bug and not a person looking for support.  this code is literally in the documentation

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-tmwr39

### Expected behavior

code compiles without needing to add typescript comments disabling checks

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Am I missing something? I don't see a comment disabling type checking

**Comment by spearmootz** [comment]
> Am I missing something? I don't see a comment disabling type checking

please refer to this issue, i didnt comment in there because the issue is closed. not sure if you can reopen it. (i didnt make that original ticket)

https://github.com/nestjs/nest/issues/8978

**Comment by jmcdo29** [comment]
> please refer to this issue

Okay/

> For some reason this works well in stackblitz environment but doesn't on local environment

And for this reason we'll need something we can look at locally. Most likely, it's not actually a bug, hence why Kamil closed it.

**Comment by spearmootz** [comment]
interesting, it runs there. but im also running into the project locally, i verified my dependencies are matching 8.3.4, let me see if i can find a way to reproduce

**Comment by spearmootz** [comment]
@jmcdo29  here it is

https://stackblitz.com/edit/nestjs-typescript-starter-r117hr?file=package.json

**Comment by micalevisk** [comment]
everything went fine with that project on stackblitz

![image](https://user-images.githubusercontent.com/13461315/160243645-d8877176-26da-4394-8199-d3571d850cf3.png)

**Comment by micalevisk** [comment]
@spearmootz the mismatch here is that `AllExceptionsFilter` `constructor`'s expect an `HttpAdapterHost`. While you're supplyin `httpAdapter`
  
![image](https://user-images.githubusercontent.com/13461315/160246192-f5ba5c1e-6c3e-49f8-986c-46d96a0c9b71.png)

![image](https://user-images.githubusercontent.com/13461315/160246221-33a97688-e663-4b6e-bd8b-5f40d07aa185.png)

To fix that, you just need to change that to:

```ts
const httpAdapterHost = app.get(HttpAdapterHost);
app.useGlobalFilters(new AllExceptionsFilter(httpAdapterHost));
```

**Comment by spearmootz** [comment]
i see, so then the bug is not in fact in nest but rather in the nest documentation?  (last code snippet says to do it like that)
should i submit a bug to documentation?

https://docs.nestjs.com/exception-filters#exception-filters

**Comment by micalevisk** [comment]
you can open a PR to fix that line instead :smiley:

**Comment by jmcdo29** [comment]
This isn't a bug, as Kamil has pointed out in a different PR to the docs. In the [Catch Everything](https://docs.nestjs.com/exception-filters#catch-everything) section we explicitly set a `constructor` that takes in an `HttpAdapterHost`. In the next section of the docs ([Inheritance](https://docs.nestjs.com/exception-filters#inheritance)) we have a _different_ `AllExceptionsFilter` that `extends BaseExceptionFilter`. [Looking at the source code](https://github.com/nestjs/nest/blob/master/packages/core/exceptions/base-exception-filter.ts#L23) `BaseExceptionFilter` expects an `HttpServer` which `HttpAdapter` satisfies.

---

Both code snippets in the docs are correct, and separate classes and usages. Perhaps we should make that fact clearer, maybe changing the inherited class's name, but overall, everything is correct.
