### ISSUE TITLE
Microservice by ioredis

### ISSUE THREAD

**Issue by ali-master** [nestjs/nest#9392]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We want to run Redis Sentinel for our project which should handle millions of requests per day which has written by microservice approach via Redis and for high availability and failover, we are using Redis Sentinel but the node_redis doesn't support the Redis Sentinel and microservices should connect together by Redis and if the master goes down, microservice Redis client should route new requests to the new Redis master.

### Describe the solution you'd like

using the `ioredis` instead of `node_redis`

### Teachability, documentation, adoption, migration strategy

...

### What is the motivation / use case for changing the behavior?

if the application should be high-available and manage the failover automatically via Redis Sentinel and Redis Client, we should use the ioredis instead of node_redis and run the Redis on multi servers to make sure that the application works if one/or more than one of the Redis servers goes down.

**Comment by Tony133** [comment]
[Here](https://github.com/nestjs/nest/issues/1048) you find a discussion about it,  

Have you tried using a custom transport? I am attaching the link to the documentation [here](https://docs.nestjs.com/microservices/custom-transport)

**Comment by ali-master** [comment]
I believe it would be very useful if officially supported by the Nestjs microservice core system.

**Comment by jmcdo29** [comment]
[See our decision here](https://github.com/nestjs/nest/issues/3960#issuecomment-771647374)
