### ISSUE TITLE
【@nestjs/microservices】I want to know if there are any dynamically registered microservices in nest microservices

### ISSUE THREAD

**Issue by xiaoqiao112** [nestjs/nest#9396]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

want to know if there are any dynamically registered microservices in nest microservices

### Describe the solution you'd like

I want to dynamically register microservices in a general interface instead of registering all microservices in advance at one time. Is there any other solution?

### Teachability, documentation, adoption, migration strategy

For example, when all the interfaces of the client reach the nest server, there is a general interface. The function of this interface (similar to a gateway or an intermediate part) can register microservices, forward different routing interfaces to different microservices, etc., mainly Want to dynamically register microservices

### What is the motivation / use case for changing the behavior?

For example, when all the interfaces of the client reach the nest server, there is a general interface. The function of this interface (similar to a gateway or an intermediate part) can register microservices, forward different routing interfaces to different microservices, etc., mainly Want to dynamically register microservices

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
