### ISSUE TITLE
nest build do not compile alias in declaration

### ISSUE THREAD

**Issue by Leesson** [nestjs/nest#9417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`tsconfig:`
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "noImplicitThis": true,
    "noUnusedLocals": false,
    "stripInternal": true,
    "pretty": true,
    "resolveJsonModule": true,
    "typeRoots": [ "./typings", "./node_modules/@types"],
    "paths": {
      "@/*": ["./src/*"],
      "~/*": ["./*"]
    }
  }
}
```
`/src/index.ts:`
```ts
import A from '@/a';

export { A };
```
`/src/a.ts:`
```ts
export default class A {
  static say() {
    console.log('A');
  }
}

```
and then run `nest build`, get the output 
```
dist/
├─index.js
└-index.d.js
```

it's ok in the file `/dist/index.js`:
```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.A = void 0;
// compiled to relative path here
const a_1 = __importDefault(require("./a"));
exports.A = a_1.default;
```

But it is still alias in the declaration `/dist/index.d.js`:
```js
// still alias
import A from '@/a';
export { A };
```

### Minimum reproduction code

https://github.com/Leesson/nest-alias

### Steps to reproduce

1. `nest new nest-alias`
2. modify the files as mentioned above
3. `npm run build`

### Expected behavior

compiles alias to relative path in the declaration.

`/dist/index.ts`:
```js
// compile alias to relative path
import A from './a';
export { A };
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/cli

### NestJS version

@nestjs/core@8.4.3; @nestjs/cli@8.2.4; 

### Packages versions

```json
"@nestjs/common": "^8.0.0",
"@nestjs/core": "^8.0.0",
"@nestjs/platform-express": "^8.0.0",
"@nestjs/cli": "^8.0.0",
"@nestjs/schematics": "^8.0.0",
"@nestjs/testing": "^8.0.0",
```

### Node.js version

14.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
With a bit of searching you'll find out that this is how TypeScript work. See:

- https://github.com/ezolenko/rollup-plugin-typescript2/issues/201
- https://stackoverflow.com/questions/52500365/typescript-declaration-file-created-with-alias-instead-of-relative-path
- https://github.com/microsoft/TypeScript/issues/30952

I believe `@nestjs/nest-cli` should not resolve that.
