### ISSUE TITLE
How to use one module instance with two different  Applications

### ISSUE THREAD

**Issue by tw949561391** [nestjs/nest#942]
How to use one module instance with two different  Applications

![image](https://user-images.githubusercontent.com/31535319/43638098-16842bb4-974a-11e8-809c-2791068e27c0.png)

**Comment by kamilmysliwiec** [comment]
This is impossible and will not be supported in the nearest future. A possible workaround is to select providers one by one and tie them to another application's instance using dynamic modules feature.
