### ISSUE TITLE
Route wildcards do not work as expected

### ISSUE THREAD

**Issue by bcheidemann** [nestjs/nest#9422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```ts
forRoutes({ path: '*', method: RequestMethod.ALL });
```

The above code does not match the path "".

For example, consider a NestJS microservice at the route "/cats".

The above code will not apply to "/cats" but will apply to "/cats/".

This behaviour is inconsistent as "/cats" and "/cats/" are the same route.

### Minimum reproduction code

n/a

### Expected behavior

The [middleware documentation](https://docs.nestjs.com/middleware) states that the wildcard (*) "will match any combination of characters". As such, it should match no characters e.g. "".

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.6

### Packages versions

```json
    --snip--
    "@nestjs/common": "8.2.6",
    --snip--
```

### Node.js version

14.18.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
