### ISSUE TITLE
Route wildcards do not work as expected

### ISSUE THREAD

**Issue by bcheidemann** [nestjs/nest#9426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```ts
forRoutes({ path: '*', method: RequestMethod.ALL });
```

The above code does not match the path "".

For example, consider a NestJS microservice at the route "/cats".

The above code will not apply to "/cats" but will apply to "/cats/".

This behaviour is inconsistent as "/cats" and "/cats/" are the same route.

### Minimum reproduction code

n/a

### Expected behavior

The [middleware documentation](https://docs.nestjs.com/middleware) states that the wildcard (*) "will match any combination of characters". As such, it should match no characters e.g. "".

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
    --snip--
    "@nestjs/common": "8.2.6",
    --snip--
```

### Node.js version

14.18.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

**THIS IS A BUG REPORT**

@kamilmysliwiec You closed my previous issue with a confusing explanation.

`Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.`

This is a bug report so I have reopened the issue.

If this is intended behaviour please say so before closing the issue and I will happily follow up with a query on Discord. However, as explained above, my understanding (based on the documentation) is that this is not intended behaviour, hence the bug report.

Thank you!

**Comment by jmcdo29** [comment]
If this is a bug report, provide a us with a [minimum reproduction](https://minimum-reproduction.wtf). Otherwise, it looks like a support request because it's not working how _you_ think it should be.

**Comment by bcheidemann** [comment]
> If this is a bug report, provide a us with a [minimum reproduction](https://minimum-reproduction.wtf). Otherwise, it looks like a support request because it's not working how _you_ think it should be. 

I'm not sure how this is a support request; I understand perfectly well how this works.

As mentioned above, I raised this issue because the current implementation is different to what is described in the documentation.

Unfortunately, I'm too busy right now to add a minimum reproduction and from the responses I have received it is clear that this bug report is not of interest anyway so I will close it now.

Thanks for not closing this issue immediately this time and for offering some explanation.
