### ISSUE TITLE
Blocking the listener until the task completes

### ISSUE THREAD

**Issue by rseasta** [nestjs/nest#9428]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm trying to solve the following problem. I have many listeners for one message pattern (using nats, but can use redis, rabbit and other). Due to internal limitations and complexity of message execution. I need to block the listener while the task is running (so that it doesn't pick up other tasks until it finishes the current one). I did not find a way to do this with standard tools (maybe this is real?).

### Describe the solution you'd like

I suggest adding a "blocking" property to the message pattern (or property which set limit for parallel running messages). To be able to use it when needed.

### Teachability, documentation, adoption, migration strategy

Like: `@MessagePattern('RenderAnimation', {blockUntilExecution: true})` or `@MessagePattern('RenderAnimation', {parallelExecutionLimit: 10})`

### What is the motivation / use case for changing the behavior?

There are very resource-intensive tasks that go beyond the work of nodejs through cli adapters and other things (for example, third-party rendering of a complex object). In this case, it is possible to load the server completely, which will lead to a system failure.

**Comment by kamilmysliwiec** [comment]
This should be pretty straightforward to implement as an in-application locking mechanism (a provider that locks/unlocks execution returning a Promise/Observable that lets you chain actions).

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
