### ISSUE TITLE
 The "@nestjs/swagger" plugin is not compatible with Nest CLI. 

### ISSUE THREAD

**Issue by Exrelativity** [nestjs/nest#9429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

npm run start:dev

 Error  The "@nestjs/swagger" plugin is not compatible with Nest CLI. Neither "after()" nor "before()" nor "afterDeclarations()" function have been provided.

### Minimum reproduction code

https://github.com/Exrelativity/elwalker.git

### Expected behavior

proper code running on server

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

Nest CLI Version : 8.2.4

### Packages versions

{
  "name": "derived",
  "version": "0.0.0",
  "description": "derived",
  "repository": "git@github.com:exrelativity/elwaker.git",
  "author": "Exrelativity <exrrelativity@gmail.com>",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/src/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "npm run test:unit && npm run test:e2e",
    "test:watch": "jest --watch --testTimeout 30000",
    "test:cov": "jest --coverage --forceExit --testTimeout 30000",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand --testTimeout 30000",
    "test:unit": "jest --forceExit --testTimeout 30000",
    "test:e2e": "export TEST=true; npx ts-node tests/test-before.ts && jest --runInBand --config ./tests/jest-e2e.json --forceExit --testTimeout 30000"
  },
  "dependencies": {
    "@elastic/elasticsearch": "^7.10.0",
    "@googlemaps/google-maps-services-js": "^3.3.12",
    "@koj/config": "^1.2.11",
    "@nestjs/common": "^8.2.3",
    "@nestjs/config": "^0.6.1",
    "@nestjs/core": "^8.2.3",
    "@nestjs/passport": "^7.1.5",
    "@nestjs/platform-express": "^8.2.3",
    "@nestjs/schedule": "^0.4.1",
    "@nestjs/swagger": "^5.1.5",
    "@octokit/rest": "^18.0.12",
    "@sentry/node": "^6.19.3",
    "@sindresorhus/slugify": "^1.1.0",
    "@slack/web-api": "^6.7.1",
    "@staart/mustache-markdown": "^3.0.3",
    "aws-elasticsearch-connector": "^9.0.1",
    "aws-sdk": "^2.1106.0",
    "axios": "^0.21.1",
    "bcrypt": "^5.0.0",
    "cheerio": "^1.0.0-rc.5",
    "circularbuffer": "^0.1.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.2",
    "cloudinary": "^1.29.0",
    "crypto-random-string": "^3.3.0",
    "deep-equal": "^2.0.5",
    "dot-object": "^2.1.4",
    "formdata-node": "^2.4.0",
    "fs-extra": "^9.0.1",
    "geolite2-redist": "^1.0.7",
    "got": "^11.8.1",
    "helmet": "^4.3.1",
    "hibp": "^10.0.1",
    "ip-anonymize": "^0.1.0",
    "ip-range-check": "^0.2.0",
    "jsonwebtoken": "^8.5.1",
    "maxmind": "^4.3.1",
    "mem": "^8.0.0",
    "minimatch": "^3.0.4",
    "nodemailer": "^6.4.17",
    "normalize-email": "^1.1.1",
    "nunjucks": "^3.2.2",
    "otplib": "^12.0.1",
    "p-queue": "^6.6.2",
    "p-retry": "^4.2.0",
    "passport": "^0.4.1",
    "pidusage": "^2.0.21",
    "puppeteer": "^5.5.0",
    "qrcode": "^1.4.4",
    "quick-lru": "^5.1.1",
    "randomcolor": "^0.6.2",
    "rate-limiter-flexible": "^2.1.16",
    "reflect-metadata": "^0.1.13",
    "request-ip": "^2.1.3",
    "response-time": "^2.3.2",
    "rimraf": "^3.0.2",
    "rxjs": "7.4.0",
    "stripe": "^8.215.0",
    "swagger-ui-express": "^4.3.0",
    "twilio": "^3.76.0",
    "ua-parser-js": "^0.7.23",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@nestjs/cli": "8.1.5",
    "@nestjs/schematics": "8.0.8",
    "@nestjs/testing": "^8.2.3",
    "@prisma/cli": "^2.14.0",
    "@prisma/client": "^3.11.1",
    "@types/bcrypt": "^3.0.0",
    "@types/cheerio": "^0.22.23",
    "@types/deep-equal": "^1.0.1",
    "@types/dot-object": "^2.1.2",
    "@types/express": "^4.17.13",
    "@types/fs-extra": "^9.0.6",
    "@types/jest": "26.0.20",
    "@types/jsonwebtoken": "^8.5.0",
    "@types/minimatch": "^3.0.3",
    "@types/node": "16.11.26",
    "@types/nodemailer": "^6.4.0",
    "@types/nunjucks": "^3.1.3",
    "@types/passport-local": "^1.0.33",
    "@types/pidusage": "^2.0.1",
    "@types/puppeteer": "^5.4.2",
    "@types/qrcode": "^1.3.5",
    "@types/randomcolor": "^0.5.5",
    "@types/request-ip": "0.0.35",
    "@types/response-time": "^2.3.4",
    "@types/supertest": "^2.0.10",
    "@types/ua-parser-js": "^0.7.35",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "4.33.0",
    "@typescript-eslint/parser": "4.33.0",
    "dotenv": "^8.6.0",
    "dotenv-expand": "^5.1.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.4",
    "jest": "27.5.1",
    "prettier": "^2.5.1",
    "prisma": "^3.11.1",
    "supertest": "^6.1.6",
    "ts-jest": "27.0.7",
    "ts-loader": "^9.2.8",
    "ts-node": "10.4.0",
    "tsconfig-paths": "3.11.0",
    "typescript": "4.3.5",
    "utility-types": "^3.10.0"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

[System Information]
OS Version     : Windows 10
NodeJS Version : v14.16.1
NPM Version    : 7.24.2

[Nest CLI]
Nest CLI Version : 8.2.4

**Comment by micalevisk** [comment]
looks like your repository isn't public.

**Comment by Exrelativity** [comment]
Thanks the repository is now public

**Comment by micalevisk** [comment]
```bash
git clone -b master https://github.com/Exrelativity/elwalker
cd elwalker
npm i
```

I got this error due to dependencies versions mismatch:

```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: ts-jest@27.0.7
npm ERR! Found: @types/jest@26.0.20
npm ERR! node_modules/@types/jest
npm ERR!   dev @types/jest@"26.0.20" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @types/jest@"^27.0.0" from ts-jest@27.0.7
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"27.0.7" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @types/jest@27.4.1
npm ERR! node_modules/@types/jest
npm ERR!   peerOptional @types/jest@"^27.0.0" from ts-jest@27.0.7
npm ERR!   node_modules/ts-jest
npm ERR!     dev ts-jest@"27.0.7" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/micael/.npm/eresolve-report.txt for a full report.
```

Please share a repo that reproduce your issue.

**Comment by Exrelativity** [comment]
please find code at https://github.com/Exrelativity/elwalker/tree/master

**Comment by jmcdo29** [comment]
Cloned your repo, checked out master, installed using `pnpm` ran `pnpm build` to run `nest build`, got a lot of primsa errors, **but** the command did run, and the swagger decorators were added to the compiled js. Something is wrong in your environment, but that's all I can say. 

Next time please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project (GitHub repo preferred)).

**Comment by piosystems** [comment]
@jmcdo29 I am getting the same error. When I run 'npm run build' I am getting the message ' Error  The "@nestjs/swagger" plugin is not compatible with Nest CLI. Neither "after()" nor "before()" nor "afterDeclarations()" function have been provided.'.  My nest-cli version is 8.2.6 and the @nestjs/swagger is 5.2.1. My node version is 16.15.0

**Comment by micalevisk** [comment]
@piosystems please share some full project with us or at least the steps to create a nestjs app that reproduces your issue.
