### ISSUE TITLE
nest new add parserOptions.tsconfigRootDir to .eslintrc.js

### ISSUE THREAD

**Issue by rhyek** [nestjs/nest#9430]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When starting a new project intended to be a monorepo (mix of frontend and backend), one of my first steps is to create a nestjs app at `apps/backend`.

In vscode, the eslint extension will immediately complain with something like `Parsing error: Cannot read file '/users/carlos/dev/personal/some-project/tsconfig.json'`. This is when viewing, for example `/users/carlos/dev/personal/some-project/backend/src/app.module.ts`.

The error will show on the first line: `import { Module } from '@nestjs/common';`

### Describe the solution you'd like

Since it already includes `root: true`, it would make sense for .eslintrc.json to initially contain `tsconfigRootDir: __dirname,`:

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'tsconfig.json',
    tsconfigRootDir: __dirname, // this is new
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint/eslint-plugin'],
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
  ],
  root: true,
  env: {
    node: true,
    jest: true,
  },
  ignorePatterns: ['.eslintrc.js'],
  rules: {
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
};

```

### Teachability, documentation, adoption, migration strategy

https://stackoverflow.com/a/64940811/410224

### What is the motivation / use case for changing the behavior?

I have to add this every time I create a new monorepo project.

**Comment by micalevisk** [comment]
I just tested this in my non-monorepo project and I believe this won't break any standard setup.

PRs are more than welcomed :smile_cat: I guess we just need to change this file: https://github.com/nestjs/schematics/blob/aeb1fcb3211c85e8554f4212fb8c28bc9428fdf1/src/lib/application/files/ts/.eslintrc.js

**Comment by micalevisk** [comment]
btw you could also change the template repo https://github.com/nestjs/typescript-starter/blob/058bac9050372a11aa1a78490cb6f83b1c42042c/.eslintrc.js

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schematics/pull/989
