### ISSUE TITLE
MQTT client does not subscribe

### ISSUE THREAD

**Issue by MrManny** [nestjs/nest#9450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The MQTT client successfully connects to the broker and dispatches an initial message.

The MQTT client does not subscribe to the topics mentioned in `@EventPattern` or `MessagePattern`, and thus does not react.

### Minimum reproduction code

https://github.com/MrManny/nest-mqtt-test

### Steps to reproduce

1. `npm install`
2. Run MQTT broker locally (I am using Mosquitto)
3. `npm start`
4. Broker accepts connection
5. NestJS app automatically publishes to broker with the `message` topic
6. Broker sees message
7. Manually publish any payload to `message` topic using an external MQTT client (I am using MQTT Explorer)

### Expected behavior

Expect to see logging output, either "Received event" or "Received message", when publishing to the `message` topic using an external MQTT client.

Also expected to see the Nest application to subscribe to the topic, which it does not according to mosquitto's logging output.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.4

### Packages versions

```
[System Information]
OS Version     : Windows 10
NodeJS Version : v16.13.0
NPM Version    : 8.5.5

[Nest CLI]
Nest CLI Version : 8.2.5

[Nest Platform Information]
platform-express version : 8.4.4
microservices version    : 8.4.4
schematics version       : 8.0.10
testing version          : 8.4.4
common version           : 8.4.4
core version             : 8.4.4
cli version              : 8.2.5
```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

For testing, the following third-party applications have been used:

* mosquitto 2.0.14 as a broker,
* MQTT Explorer 0.4.0-beta1 as a second test client connected to the same broker. Issue is also reproduceable with mosquitto_pub and mosquitto_sub.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
