### ISSUE TITLE
@nestjs/microservices kafkajs eachBatch support

### ISSUE THREAD

**Issue by benhason1** [nestjs/nest#9455]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In today implementation of kafka microservice client there isn't any option for sending or consuming messages in batches.

### Describe the solution you'd like

I would like an option to define the type of messages I receive or send either: one by one or batches.

This features ( [consume](https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch), [produce](https://kafka.js.org/docs/producing) ) are already supported in kafkajs and it would be great if the nestjs library will reveal this in his implementation.

### consumer
```ts
 const app = await NestFactory.createMicroservice<MicroserviceOptions>(
    AppModule,
    {
      transport: Transport.KAFKA,
      options: {
        consumer: {
         messageType: 'message' | 'batch',
          groupId: 'temp',
        },
      },
    },
  );
```

### producer 
```ts
this.client.send('pattern', { messages: [] } | new DemoRequest() )
```

### What is the motivation / use case for changing the behavior?

process messages by batches for improving performance.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past (see older Kafka-related issues) and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
