### ISSUE TITLE
req.body is null in the middleware when using fastify

### ISSUE THREAD

**Issue by alirezadarban** [nestjs/nest#9469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hey guys! I get `null` as body in the req in the middleware since I use fastify.

### Minimum reproduction code

https://codesandbox.io/s/zealous-phoebe-rdzxj5?file=/src/middleware/logger.middleware.ts

### Steps to reproduce

1. npm i
2. npm start
3. See the null in the console

### Expected behavior

I expect the req.body object but I got null 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.3

### Packages versions

```{
  "name": "nest-typescript-starter",
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint '{src,apps,libs,test}/**/*.ts' --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "echo 'No e2e tests implemented yet.'"
  },
  "dependencies": {
    "@nestjs/common": "8.2.3",
    "@nestjs/core": "8.2.3",
    "@nestjs/platform-fastify": "8.2.3",
    "class-transformer": "0.4.0",
    "class-validator": "0.13.2",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.4.0"
  },
  "devDependencies": {
    "@nestjs/cli": "8.1.7",
    "@nestjs/schematics": "8.0.8",
    "@nestjs/testing": "8.2.3",
    "@types/express": "4.17.13",
    "@types/node": "16.11.26",
    "@types/supertest": "2.0.11",
    "@typescript-eslint/eslint-plugin": "4.33.0",
    "@typescript-eslint/parser": "4.33.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-import": "2.25.4",
    "jest": "27.5.1",
    "prettier": "2.5.1",
    "supertest": "6.1.6",
    "ts-jest": "27.0.7",
    "ts-loader": "9.2.8",
    "ts-node": "10.4.0",
    "tsconfig-paths": "3.11.0",
    "typescript": "4.3.5"
  }
}
```

### Node.js version

14.17.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
I'm rather certain this happens in a regular fastify application too, because of how `middie` is used for express middleware compatibility. It uses `req.raw` (`IncomingRequest`) instead of `FastifyRequest` as the `req` object, so `req.body` is not the actual body of the parsed `FastifyRequest`.

**Comment by alirezadarban** [comment]
> I'm rather certain this happens in a regular fastify application too, because of how `middie` is used for express middleware compatibility. It uses `req.raw` (`IncomingRequest`) instead of `FastifyRequest` as the `req` object, so `req.body` is not the actual body of the parsed `FastifyRequest`.

Thanks for your response @jmcdo29 ! So how can I access the content of the request in the middleware using fastify?

**Comment by jmcdo29** [comment]
Anything that's on the `IncomingRequest` is accessible, `headers`, `url`, a few others, but if you need `body` or similar you should probably use an interceptor, a guard, or a pipe.

For more support, and to determine why you need to access `body`, we can discuss this on our [Discord](https://discord.gg/nestjs) server
