### ISSUE TITLE
Docker image failing with split of undefined error

### ISSUE THREAD

**Issue by gauravranawynk** [nestjs/nest#9480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Create a docker image and after that run the container.
I'm getting below error.

I have tried with my other source code images which was working fine.
But after rebuilding those images again, same issue is coming in other source code also.

### Minimum reproduction code

Use any boiler plate code

### Expected behavior

Should run as expected on docker.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

toidentifier, http-errors

### NestJS version

8.0.0

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/mongoose": "^9.0.3",
    "@nestjs/platform-express": "^8.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "cross-env": "^7.0.3",
    "mongoose": "^6.2.9",
    "nanoid": "^3.3.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  }
```

### Node.js version

16.14.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

<img width="962" alt="Screenshot 2022-04-20 at 5 29 26 PM" src="https://user-images.githubusercontent.com/102725471/164226120-5f9914f4-1681-4597-8b43-7b9127dc8535.png">

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
