### ISSUE TITLE
Unable to receive response NestJS nats app when publishing from GoLang nats client

### ISSUE THREAD

**Issue by kielsoft** [nestjs/nest#9483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Publishing with "local-event-path" from a Golang application to a NestJS app running Nats @MessagePattern("local-event-path") is timing out on Golang app, the request data is getting to NestJS app as @Payload() but the handler return is not getting to Golang.

### Minimum reproduction code

https://github.com/nats-io/nats.go

### Steps to reproduce

```
err := natsEncodedConn.Request(request.Path, request, response, 10*time.Second)
if err != nil {
fmt.Printf("%+v\n", err)
}
fmt.Println(err)
fmt.Println(response)
fmt.Fprintf(w, "response %v \n", response)
```

### Expected behavior

```
nats: timeout
nats: timeout
{ <nil>}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

nats.js

### NestJS version

8

### Packages versions

```@nestjs/microservice

```

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Thanks

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
