### ISSUE TITLE
31-graphql-federation-code-first sample not working

### ISSUE THREAD

**Issue by all2pie** [nestjs/nest#9487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Getting this error on running the sample project: 

```
Error: A valid schema couldn't be composed. The following composition errors were found:
        Field "User.id" can only be defined once.
        Field "User.name" can only be defined once.
        There can be only one type named "User".
        [posts] User -> appears to be an entity but no @key directives are specified on the originating type.
```

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first

### Steps to reproduce

1. `npm i` in each directory
2. `npm start` in each directory according to order 
3. Check the gateway logs for error

### Expected behavior

It should work properly.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
duplicate issue: https://github.com/nestjs/nest/issues/9472
I also attach here the link where they keep trace of this problem nestjs/graphql#2141

**Comment by all2pie** [comment]
Okay, thanks 

The real issue that I am facing is with `MercuriusFederationDriver`, will open a separate issue for that.
