### ISSUE TITLE
HTTP Exceptions enforce the response content type to application/json with body

### ISSUE THREAD

**Issue by ericmorand** [nestjs/nest#9488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Whenever an exception inheriting from `HttpException` is thrown in a route handler, the generated response has its content type set to `application/json` and its body set to a JSON serialized object.

### Minimum reproduction code

none

### Expected behavior

The response content type should be unset and the body should be empty.

Would an implementation requires that responses generated from exceptions are JSON, it should be the responsibility of the implementation to do so. Currently, it is impossible to throw an `HTTPException` with an empty body for example:

`throw new UnauthorizedException(null)` sends an `application/json` response with a body.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"@nestjs/core": "8.4.1",
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Duplicate https://github.com/nestjs/nest/issues/8469#issuecomment-1000131605
