### ISSUE TITLE
NestJS is limiting query length of JSON to 624 symbols

### ISSUE THREAD

**Issue by realtril** [nestjs/nest#9500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is what I am getting as a query.body:

<img width="498" alt="Screen Shot 2022-04-26 at 11 55 47 AM" src="https://user-images.githubusercontent.com/53015418/165278304-d295e1fa-3e32-4d97-9170-220c254628ce.png">

### Minimum reproduction code

-----

### Steps to reproduce

This is my controller.
```
@Get(':id/preview')
  async getPreview(@Res() res: Response, @Param('id') id: string, @Query() query): Promise<void>{
    const opts = parseQuery(query);
    console.log(query.body,"query.body");
    const components = await this.componentsService.query(opts);
    const currComponent = (components || []).find(component => component._id.toString() === id)
    if(query.body){
      res.render('ui/pages/patterns/component', {
        pageName: `MULTIPLEX Design System`,
        header: 'patterns-library',
        innerCases: [
          { name: 'Designer Guides', link: 'designer-guids' },
          { name: 'Specs', link: 'specs' },
        ],
        current: currComponent,
        order: await this.componentOrderService.getOrder(),
        version: CONFIG.SERVER.VERSION,
        preview: true
      });
    } else {
      res.redirect('/patterns-library');
    }
  }
```

### Expected behavior

Getting full json length

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

4.5.10

### Packages versions

  "dependencies": {
    "@nestjs/common": "^4.5.9",
    "@nestjs/core": "^4.5.10",
    "@types/adm-zip": "^0.4.33",
    "adm-zip": "^0.4.14",
    "bootstrap": "^4.1.0",
    "cheerio": "0.22.0",
    "express-session": "^1.15.6",
    "express-static-gzip": "^0.3.2",
    "image-size": "^0.6.3",
    "jimp": "^0.2.28",
    "jsonwebtoken": "^8.2.1",
    "lodash": "^4.17.21",
    "moment": "^2.22.1",
    "mongodb": "2.2.35",
    "morgan": "^1.9.0",
    "multer": "^1.3.0",
    "nodemailer": "^4.6.3",
    "password-hash": "^1.2.2",
    "pug": "^2.0.0-rc.4",
    "redis": "^2.7.1",
    "reflect-metadata": "^0.1.12",
    "rimraf": "^2.6.2",
    "rxjs": "^5.5.6",
    "unzip-stream": "^0.3.0",
    "winston": "^3.3.3",
    "xml-parser": "^1.2.1"
  },
  "devDependencies": {
    "@types/express": "^4.11.1",
    "@types/jsonwebtoken": "^7.2.5",
    "@types/mongodb": "^3.0.7",
    "@types/node": "^9.3.0",
    "@types/nodemailer": "^4.6.0",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "dotenv": "^6.0.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "gulp": "^3.9.1",
    "gulp-uglifycss": "^1.0.9",
    "gulp-uglifyjs": "^0.6.2",
    "less": "^3.0.4",
    "less-loader": "^4.1.0",
    "less-plugin-autoprefix": "^1.5.1",
    "less-plugin-clean-css": "^1.5.1",
    "node-pre-gyp": "^0.10.0",
    "prismjs": "^1.14.0",
    "raw-loader": "^0.5.1",
    "style-loader": "^0.20.3",
    "ts-loader": "3.5.0",
    "ts-node": "^4.1.0",
    "typescript": "^2.9.1",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "^3.11.0"
  }

### Node.js version

9.11.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by BrunnerLivio** [comment]
The `@Query()`-decorator uses in the background the `res.query`-attribute of an Express response. So I doubt that this is a NestJS specific problem. 

I have a hunch that you may be hitting the 2000-character limit of URLs because special characters need to be escaped. For example

``` 
// this JSON:
{"test": "asdf"}

// results in this query parameter:
%7B%22test%22%3A%20%22asdf%22%7D
```

Because of that you might reach the 2000 char limit quite quickly. Have you considered transferring your JSON-data via body since Query Params are anyway not a good place to store JSON [read more here](https://softwareengineering.stackexchange.com/a/403252).

**Comment by realtril** [comment]
@BrunnerLivio yep! that was actually exactly my kind of a problem 😁 thanks!
