### ISSUE TITLE
Feature: add excludes the specified route feature to pipe 

### ISSUE THREAD

**Issue by GO-DIE** [nestjs/nest#9501]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently the scope of using pipes is global, and I cannot rule out the behavior of pipes that specify routes.

### Describe the solution you'd like

add excludes the specified route feature to pipe

### Teachability, documentation, adoption, migration strategy

I think usage habits can be similar to middleware.
```typescript
consumer
  .apply(MyPipe)
  .exclude(
    { path: 'cats', method: RequestMethod.GET },
    { path: 'cats', method: RequestMethod.POST },
    'cats/(.*)',
  )
  .forRoutes(CatsController);
```

### What is the motivation / use case for changing the behavior?

Customize the effective scope of a pipe.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
