### ISSUE TITLE
Fastify cors Error when throwing exception inside middleware

### ISSUE THREAD

**Issue by in-emilio** [nestjs/nest#9510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i fetch from other domain if my middleware throws an exception, it generates a CORS Error.
![image](https://user-images.githubusercontent.com/86231218/166236558-fb002ba3-77a5-48c9-adaf-c851c6daccb7.png)

If I switch to the express adapter, it works fine.

### Minimum reproduction code

https://github.com/in-emilio/fastify-cors-error

### Steps to reproduce

npm i
npm run start:dev

navigate to whatever web page except port 3000
fetch GET localhost:3000/test

### Expected behavior

It should appear the real exception (UnauthorizedException) instead of CORS error.
It is thrown in the middleware (RequestContextMiddleware).

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.1

### Packages versions

```json
{
  "name": "test-packages-project",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main"
  },
  "dependencies": {
    "@fastify/cors": "^7.0.0",
    "@nestjs/common": "8.4.1",
    "@nestjs/core": "8.4.1",
    "@nestjs/platform-express": "8.4.1",
    "@nestjs/platform-fastify": "^8.4.4",
    "reflect-metadata": "0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@nestjs/cli": "8.2.2",
    "@nestjs/schematics": "8.0.8",
    "@types/express": "4.17.13",
    "@types/node": "17.0.21",
    "@typescript-eslint/eslint-plugin": "5.14.0",
    "@typescript-eslint/parser": "5.14.0",
    "eslint": "8.10.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-prettier": "4.0.0",
    "prettier": "2.5.1",
    "ts-loader": "9.2.8",
    "ts-node": "10.7.0",
    "tsconfig-paths": "3.13.0",
    "typescript": "4.6.2"
  }
}

```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I believe your nestjs middleware is being evaluated before the `fastify-cors` plugin or something like that :thinking: idk why, as this only happens with the Fastify adapter

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
