### ISSUE TITLE
REQUEST isn't injected with moduleRef.resolve

### ISSUE THREAD

**Issue by urugator** [nestjs/nest#9515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a request scoped provider that injects `REQUEST`:
```javascript
{
  provide: 'token',
  scope: Scope.REQUEST,
  useFactory: (request) => {/**/},
  inject: [REQUEST],
},
```
Now if I try to resolve the service manually from eg. interceptor
```javascript
if (context.getType() === 'http') {
   const request = context.switchToHttp().getRequest();
   const contextId = ContextIdFactory.getByRequest(request);
   await this.moduleRef.resolve<void>('token', contextId);
}
```
the `request` passed to provider's factory is `undefined` - unless the service was previously injected elsewhere via different means, eg controller using `@Inject('token')`.

### Minimum reproduction code

https://codesandbox.io/s/inject-request-bug-pbrwgy?file=/src/app.module.ts

### Steps to reproduce

Open codesandbox, refresh page, see output in console:
```
interceptor
resolve
factory: request:  undefined
```
Go to `AppController`, uncomment:
`//@Inject('token') private readonly foo: string,`
Restart server (Server Control Panel - Restart Server)
Refresh page, see output
```
interceptor
resolve
factory: request:  object
```

### Expected behavior

`moduleRef.resolve` should be able to correctly resolve service that depends on `REQUEST`, no matter whether the service was resolved elsewhere via different means or not.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.4

### Packages versions

```json
"@nrwl/nest": "14.0.5",
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Temporary workaround:
```typescript
this.moduleRef.registerRequestByContextId(
  context.switchToHttp().getRequest(),
  contextId,
);
```
(before `.resolve()`)
