### ISSUE TITLE
In Template Rendering of NestJS, the return some return value string is converted to unicode.

### ISSUE THREAD

**Issue by ZungTa** [nestjs/nest#9518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use NestJS' Template Rendering, I passed the url to hbs.

However, when I print the url to console.log in hbs, I see that the "=" character is converted to "&#x3D;" (unicode).

I couldn't find anything related to the document, and I couldn't find a similar case in Google search, so I registered it as an Issue.

It is converted only in the javascript part within the hbs file.
When output as html, it is displayed normally.

Since the string passed from NestJS Controller to hbs is converted to unicode, an axios request using the string from hbs failed.

### Minimum reproduction code

https://github.com/ZungTa/nestjs-render-test

### Expected behavior

The string passed from NestJS Controller to hbs should not be converted to unicode and should be displayed normally.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^8.0.0

### Packages versions

```bash
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.14.2
YARN Version    : 1.22.15 

[Nest CLI]
Nest CLI Version : 8.2.5 

[Nest Platform Information]
platform-express version : 8.4.4
schematics version       : 8.0.10
testing version          : 8.4.4
common version           : 8.4.4
core version             : 8.4.4
cli version              : 8.2.5
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
