### ISSUE TITLE
Is there a way to add Metadata on the gRPC client

### ISSUE THREAD

**Issue by haoyuwangcq** [nestjs/nest#9520]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to add metadata in a gRPC client Request. In the doc, there is only instruction on the server-side. Is there any way to do it on the client-side?  client-side

### Describe the solution you'd like

Provide method or document on add metadata on the gRPC client sidea 

### Teachability, documentation, adoption, migration strategy

User should be able to add metadata such as jwt token, when sending gRPC request

### What is the motivation / use case for changing the behavior?

I want add jwt token as a part of header, when sending gRPC request

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
