### ISSUE TITLE
Dependency Injection Lifetime support

### ISSUE THREAD

**Issue by Meir017** [nestjs/nest#953]
# Feature request

## Current behavior

The dependency injection uses Singleton instances

## Expected behavior

I would like to be able to specify the lifetime of the dependency being injected
Something like - https://github.com/jeffijoe/awilix#lifetime-management

**Comment by tonyxiao** [comment]
On a related note, why does nestjs implement its own dependency injection framework rather than using something like typedi or inversify or awilix?

**Comment by xxxtonixxx** [comment]
Nestjs implements its own injection framework. I think @Meir017 is requesting the lifetime feature of awilix (singleton, scoped and transient modes)

**Comment by tonyxiao** [comment]
@xxxtonixxx I understand that nestjs implements its own, I'm asking why it does that instead of using existing solution like `typedi`.

**Comment by Meir017** [comment]
I'm talking about something similar to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1#service-lifetimes
This would allow me to pass parameters for each request
for example: add to the logging a request-id to trace actions related to that request

**Comment by marcus-sa** [comment]
I think your question answers itself.
The architecture is supposed to be as close to Angulars as possible.
That cannot be done using awilix, inversify or any other library for that matter because this DI is obviously built around the module architecture.

**Comment by marcus-sa** [comment]
There's already some sort of lifetime management, just not hierarchy dependent.
https://github.com/nestjs/nest/blob/9e6cf1f1aaa4afdbe255d106432e0274b70cbbd1/packages/common/decorators/modules/single-scope.decorator.ts#L4

**Comment by kamilmysliwiec** [comment]
Once `async-hooks` feature is stable, we'll think about providing a built-in solution for request-scoped instances.
