### ISSUE TITLE
Identify/guard against request-scope chain bubbling for classes which will never have access to a request

### ISSUE THREAD

**Issue by zpatrick** [nestjs/nest#9541]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Child nodes in our dependency graph may import or change their injection scope from DEFAULT to REQUEST, resulting in that change in scope to propagate all the way back up the dependency chain. This can cause issues for certain classes which cannot be created outside the scope of a request (e.g. a cli service or job consumer). When this happens, the nestjs injection framework passed `undefined` values instead of failing loudly. It's extremely difficult to debug and find the culprit that is causing the scope change, especially when dealing with larger application that have larger dependency trees.

### Describe the solution you'd like

The DI framework to fail loudly and clearly instead of passing `undefined` when it is trying to create a request-scoped dependency where no request is present.

Another option would be to add a `requiredScope` param to `@Injectable` decorator, e.g. `@Injectable({ requiredScope: Scope.DEFAULT })`. On startup, if nestjs identifies that a child dependency would cause this scope to change, it would error out which a clear message on which dependency chain was causing this scope rule to be violated. 

### Teachability, documentation, adoption, migration strategy

As an addition to: https://docs.nestjs.com/fundamentals/injection-scopes#scope-hierarchy

## Required scopes
Certain classes won't have access to a request, making the "bubble up" behavior of the request-scoped dependency chain an issue. We can use the optional `requiredScope` parameter in the `@Injectable` decorator to tell nestjs to error out if at any point the dependency chain causes the scope to change.

Consider the following, valid setup:
```
@Injectable({ requiredScope: Scope.DEFAULT })
export class CliService {
  constructor(private catsService: CatsService) {}
}

@Injectable()
export class CatsService {
  constructor() {}
}
```

If someone came along and added a request-scoped `CatsRepository` dependency:
```
@Injectable({ requiredScope: Scope.DEFAULT })
export class CliService {
  constructor(private catsService: CatsService) {}
}

@Injectable()
export class CatsService {
  constructor(private catsRepository: CatsRepository) {}
}

@Injectable({ scope: Scope.REQUEST })
export class CatsRepository {
  constructor() {}
}
```

The required scope would be violated, and we'd get an error message explaining the issue:
```
Required Scope DEFAULT violated for CliService due to dependency CatsService:
  CatsService is REQUEST scoped due to dependency CatsRepository:
    CatsRepository is defined as REQUEST scoped
```

### What is the motivation / use case for changing the behavior?

It's extremely difficult & tedious to debug these sorts of issues today. We often times don't find these issues until late in the development process. It would save a lot of time and headache finding this issues proactively.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project) that showcases your issue (and will serve as an example we could investigate).

**Comment by davedefiq** [comment]
I second this, requiring a certain scope and erroring when it changes based on another dependency would be fantastic.

**Comment by MikeChristensen** [comment]
I would also love to see this one fixed!  Spent around four hours last night trying to track down a bug, and it ended up being because the scope of one of our services had changed under the covers and caused various side effects.

**Comment by dlabs-matic-leva** [comment]
Repro case:
https://codesandbox.io/p/devbox/muddy-hill-rvkdck

EDIT: Run `npm start`. My expectation is to get an error from DI and not even reach `this.service.getRequest()`, as service is request-scoped. I expect that `app.get(ProcessorService)` would fail in some way.
