### ISSUE TITLE
Upgrade fastify-swagger to @fastify/swagger

### ISSUE THREAD

**Issue by wagerfield** [nestjs/nest#9542]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The `fastify-swagger` package was marked as deprecated 10 days ago (27th Apr)

https://www.npmjs.com/package/fastify-swagger

It has been replaced by `@fastify/swagger`

https://www.npmjs.com/package/@fastify/swagger

When running the server with `fastify-swagger` a deprecation warning is printed:

    (node:26467) [FST_MODULE_DEP_FASTIFY-SWAGGER] FastifyWarning.fastify-swagger: fastify-swagger has been deprecated. Use @fastify/swagger@6.0.0 instead.

When installing `@fastify/swagger` in place of `fastify-swagger` NestJS throws the error:

    ERROR [PackageLoader] The "fastify-swagger" package is missing. Please, make sure to install this library ($ npm install fastify-swagger) to take advantage of SwaggerModule.

### Describe the solution you'd like

Please upgrade `fastify-swagger` to `@fastify/swagger` 🙏 

### Teachability, documentation, adoption, migration strategy

Update the [OpenAPI Introduction » Installation](https://docs.nestjs.com/openapi/introduction#installation) and [OpenAPI Migration Guide](https://docs.nestjs.com/openapi/migration-guide).

### What is the motivation / use case for changing the behavior?

Use the latest maintained version of Fastify Swagger.

**Comment by Tony133** [comment]
Hi @wagerfield, there are open PRs for updating the `@fastify/swagger` package both of the package and of the documentation, I have recently linked them to this issues. 

Now you have to wait for Kamil when he finds time to merge and review 🤞

**Comment by wagerfield** [comment]
@Tony133 ah thank you! I did search the open issues and PR's for "fastify swagger" but there were no results! 🤔 

Should I close this issue given there are open PR's for it?

**Comment by Tony133** [comment]
The fastify packages were updated last week and for what you found no open issues about it.
However, for a few days now I have known that some people in the community wanted to know when the packages will be updated.

If you want you can leave it open so that other people know that it has already been reported. So they don't open another problem by duplicating it.
At most the members of the Nest Core Team will close it, don't worry.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/1908#issuecomment-1117320982
