### ISSUE TITLE
Can't use interceptor with optional parameter as type

### ISSUE THREAD

**Issue by superpupervlad** [nestjs/nest#9544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`@UseInterceptors` can't handle interceptor (with optional parameters) that passed as type.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-bnqkzn?file=src/app.controller.ts

### Expected behavior

Due to [documentation](https://docs.nestjs.com/interceptors#binding-interceptors) (`leaving responsibility for instantiation to the framework and enabling dependency injection`) nest should create an instance of interceptor because no parameters needed from user and it is possible to create interceptor.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.1

### Packages versions

From stackblitz
```ini
[Nest CLI]
Nest CLI Version : 8.1.3 

[Nest Platform Information]
platform-express version : 8.1.1
schematics version       : 8.0.4
testing version          : 8.1.1
common version           : 8.1.1
core version             : 8.1.1
cli version              : 8.1.3
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
your interceptor should have this constructor:

```
  constructor(
    @Optional() private first_optional_param?: string,
    @Optional() private second_optional_param: string = 'abc',
  ) {}
```

learn here: https://docs.nestjs.com/providers#optional-providers

**Comment by jmcdo29** [comment]
This is not a bug. Micael has the correct solution above.

For further support, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
