### ISSUE TITLE
8.0: Factory APP_INTERCEPTOR gets "Nest cannot export a provider that is not part of the currently processed module" but it is!

### ISSUE THREAD

**Issue by pvogel1967** [nestjs/nest#9545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
[Nest] 38603  - 05/08/2022, 2:07:13 PM     LOG [NestFactory] Starting Nest application...
[Nest] 38603  - 05/08/2022, 2:07:13 PM   ERROR [ExceptionHandler] Nest cannot export a provider/module that is not a part of the currently processed module (LoggingModule). Please verify whether the exported APP_INTERCEPTOR is available in this particular context.

Possible Solutions:
- Is APP_INTERCEPTOR part of the relevant providers/imports within LoggingModule?

Error: Nest cannot export a provider/module that is not a part of the currently processed module (LoggingModule). Please verify whether the exported APP_INTERCEPTOR is available in this particular context.

Possible Solutions:
- Is APP_INTERCEPTOR part of the relevant providers/imports within LoggingModule?

    at Module.validateExportedProvider (/Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/injector/module.js:283:19)
    at Module.addCustomExportedProvider (/Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/injector/module.js:267:43)
    at Module.addExportedProvider (/Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/injector/module.js:253:25)
    at NestContainer.addExportedProvider (/Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/injector/container.js:127:19)
    at DependenciesScanner.insertExportedProvider (/Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/scanner.js:231:24)
    at /Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/scanner.js:134:50
    at Array.forEach (<anonymous>)
    at DependenciesScanner.reflectExports (/Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/scanner.js:134:17)
    at DependenciesScanner.scanModulesForDependencies (/Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/scanner.js:87:18)
    at async DependenciesScanner.scan (/Users/pvogel/dev/hydrow/minimal-repro/node_modules/@nestjs/core/scanner.js:29:9)
```

### Minimum reproduction code

https://github.com/pvogel1967/minimal-repro

### Steps to reproduce

1.  yarn install
2. yarn build
3. yarn start:local

This is working fine in another repo of ours that is still on nest 7, so I suspect a regression.

### Expected behavior

Successful creation of the injected APP_INTERCEPTOR from the `RequestTrackerFactory` factory provider in `src/logging/request-interceptor.provider.ts` which is listed in the `provider` array as well as the `exports` array of the `LoggingModule` defined in `src/logging/logging.module.ts`

```
export const RequestTrackerFactory: FactoryProvider = {
    provide: APP_INTERCEPTOR,
    scope: Scope.REQUEST,
    inject: [ROOT_LOGGER, LOGGING_CONFIG_INJECTOR],
    useFactory: (logger: Bunyan, config: LoggingConfig) => {
        console.log('In requestInterceptorProvider factory');
        return new RequestTrackerInterceptor(logger, config);
    },
};
```

```
@Module({
    imports: [],
    providers: [LoggingConfigProvider, RequestTrackerFactory],
    exports: [LoggingConfigProvider, RequestTrackerFactory],
})
export class LoggingModule {}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.4

### Packages versions

```
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.15.0
YARN Version    : 1.22.18 

[Nest CLI]
Nest CLI Version : 8.2.5 

[Nest Platform Information]
platform-express version : 8.4.4
schematics version       : 8.0.11
testing version          : 8.4.4
common version           : 8.4.4
core version             : 8.4.4

```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by pvogel1967** [comment]
After a little more trial and error, I believe that if I simply _do not_ export the APP_INTERCEPTOR from the module, things work.  But this is definitely different behavior than we had in Nest 7.

**Comment by micalevisk** [comment]
here's a minimum repo that reproduces your issue: https://gitlab.com/micalevisk/nestjs-issue-9545

**Comment by jmcdo29** [comment]
I'll take a look into why out of curiosity, but there's no reason to need to add `APP_INTERCEPTOR` to the `exports` array, because `APP_INTERCEPTOR` is already a global binding. Most likely the reason the error is happening is because under the hood `APP_INTERCEPTOR` becomes `APP_INTERCEPTOR+<uuid>` (you can kind of see part of that fact in an [old e2e test for one of my libraries](https://github.com/jmcdo29/ogma/blob/51466fca0190ad6ca554f2d0322c824f29f0b245/integration/test/utils/getInterceptor.ts) [warning, really janky code for Nest v7]). Why it didn't happen in v7 I'm not sure yet, but maybe we can add some extra debug logs for the `NEST_DEBUG` env variable about what modules export which providers
