### ISSUE TITLE
WebSocket Gateway - Secure websockets - spdy(http2)

### ISSUE THREAD

**Issue by hemendpatel** [nestjs/nest#9547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

const bootstrap = async (): Promise<void> => {
  
 const expressApp = express();
  let spdyOptions: spdy.ServerOptions;
    spdyOptions = {
      key: readFileSync(join(process.env.APP_ROOT_DIR, tls.key)),
      cert: readFileSync(join(process.env.APP_ROOT_DIR, tls.cert)),
    };

  const { AppModule } = await import('./app.module');
 const server: spdy.Server = spdy.createServer(spdyOptions, expressApp);

 const app: NestApplication = await NestFactory.create(
    AppModule ,
    new ExpressAdapter(expressApp),
    {
      cors: true,
    },
  );
  await app.init();
server.listen(3000, () => {
    console.log(
      `HTTP/2 Application Server is listening at port 3000`,
    );
  });
};
bootstrap();

Socket.io doesn't support spdy so have provided port number to run gateway on different port. its working with http(WS) but doesn't get any option to run web socket gateway with https(wss). 

@WebSocketGateway(3002, { cors: true })
export class ChatGateway implements OnGatewayConnection, OnGatewayDisconnect {
  @WebSocketServer()
  server: Server;

  handleConnection(client: Socket, ...args: any[]) {
    console.log('connection made', client.id)
  }
  handleDisconnect(client: Socket) {
    console.log('disconnected', client.id)
  }

  @SubscribeMessage('sendMessage')
  handlerequest(client: Socket, message: string) {
    console.log(message);
    this.server.emit('newMessage', 'newMessage  : ' + message);
  }
}

Can you please guild me if I'm missing anything here?

### Minimum reproduction code

let me know if require more detail

### Expected behavior

We would like to run our application using http2 and https for websocket. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [X] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```
  "@nestjs/platform-socket.io": "^8.4.4",
    "@nestjs/platform-ws": "^8.4.4",
    "@nestjs/websockets": "^8.4.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "socket.io": "^4.5.0",
    "spdy": "^4.0.2"

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
