### ISSUE TITLE
Graphql Generate Schema with build

### ISSUE THREAD

**Issue by bneigher** [nestjs/nest#9553]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, to my understanding, when using a code-first approach to generating a graphql schema (with directives) --- the schema is generated when running `nest start` or `nest start --watch`

I'm currently trying to figure out how to make the schema generation independent from the development workflow - essentially enabling the generation of the schema from a build step (in Docker, or a pre-commit step).

It's not clear from the documents how we can accomplish that.  I have found a few examples of writing a script that attempts to do this:
```javascript
import { join } from 'path'
import { writeFile } from 'fs/promises'
import { NestFactory } from '@nestjs/core'
import { printSchemaWithDirectives } from '@graphql-tools/utils'
import { GraphQLSchemaBuilderModule, GraphQLSchemaFactory } from '@nestjs/graphql'

;(async () => {
  const app = await NestFactory.create(GraphQLSchemaBuilderModule)
    await app.init()
  
    const gqlSchemaFactory = app.get(GraphQLSchemaFactory)
  
    // pass all resolvers
    const schema = await gqlSchemaFactory.create([
      ...myResolvers
    ])
  
    const relativeSchemaPath = 'src/schema/schema.graphql'
    const schemaPath = join(process.cwd(), relativeSchemaPath)
    await writeFile(schemaPath, printSchemaWithDirectives(schema))
})()
```

But I need to add my resolvers manually here, and I have some additional dynamic configurations like adding directives that are being done within the actual src code for my nest app, and porting them to work in the script here is not a clean solution.

### Describe the solution you'd like

It would be great if we had the ability to spin up the nest app so that it generates the schema from the code, and then terminates the process.. so we can execute a `nest build-schema` like command... or provide in the documents a clear way of doing this without having to duplicate implementation in the "build script" and the existing api code.  

### Teachability, documentation, adoption, migration strategy

It would also make sense for this functionality to be demonstrated in the example repos.. e.g. https://github.com/nestjs/nest/tree/master/sample/23-graphql-code-first.. where there is a `generate-schema` npm script we can execute during build-time.

### What is the motivation / use case for changing the behavior?

Enabling CI/CD, gitflow, or Docker schema build use cases

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past). You can also use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.
