### ISSUE TITLE
bug: DyanmicModule is considered unique when it should not

### ISSUE THREAD

**Issue by regevbr** [nestjs/nest#9556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ModuleTokenFactory is used in order to track if a dynamic module was already defined by creating a hash on its definition.  Currently, there is a way to bypass that mechanism in a very naive way:
```typescript
export class ConfigurationModule {
  static forRoot(value: string): DynamicModule {
    return {
      // @ts-ignore
      // uniqueKey: value,
      module: ConfigurationModule,
      providers: [
        ConfigService,
        {
          provide: 'CONFIG_VALUE',
          useFactory: () => value,
        },
      ],
      exports: [ConfigService],
    };
  }
}
```
In the example above, the value can change for each call to `forRoot()` which should produce a different module, but since the "uniqness" of the call is "hidden" in the closure of the `useFactory` the hashing of the DynamicModule will always be the same (as it only hashes the function code)

### Minimum reproduction code

https://github.com/regevbr/nestjs-moduletoken-bug

### Steps to reproduce

1. `npm run start`
2. the logs show:
```bash
widget: widget2
widget2: widget2
```
i.e. the dynamic module was created only once

### Expected behavior

I wish there was a way to detect my scenario but as far as I understand, it is not possible. The way we currently avoid that issue is by extending the DynamicModule interface:
```typescript
type UniqueDynamicModule = DynamicModule & {uniqueId: any}
```
and then when providing a value, it will be part of the hash, forcing the uniqueness of the DynamicModule. If you uncomment 

https://github.com/regevbr/nestjs-moduletoken-bug/blob/59ba294e653075442539574ade92541dd0864cfe/src/config/config.module.ts#L8

in my reproduction repo, the behavior will work as expected (prints
```bash
widget: widget
widget2: widget2
```
)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.4

### Packages versions

```json
{
    "@nestjs/common": "^8.4.4",
    "@nestjs/core": "^8.4.4",
    "@nestjs/platform-express": "^8.4.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.5"
  }
```

### Node.js version

v16.5.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

In https://github.com/nestjs/nest/issues/5698 you claimed that the forRoot should create a unique module for each provided value, but as I show here, this can be bypassed by accident

**Comment by micalevisk** [comment]
https://docs.nestjs.com/fundamentals/dynamic-modules#community-guidelines

> `forRoot`, you are expecting to configure a dynamic module once and reuse that configuration in multiple places (though possibly unknowingly as it's abstracted away). This is why you have one `GraphQLModule.forRoot()`, one `TypeOrmModule.forRoot()`, etc. 

> `register`, you are expecting to configure a dynamic module with a specific configuration for use only by the calling module. 

so I believe you're trying to implement the `register` one, not `forRoot`. See how this is done in `@nestjs/axios`: https://github.com/nestjs/axios/blob/master/lib/http.module.ts

**Comment by regevbr** [comment]
> https://docs.nestjs.com/fundamentals/dynamic-modules#community-guidelines
> 
> > `forRoot`, you are expecting to configure a dynamic module once and reuse that configuration in multiple places (though possibly unknowingly as it's abstracted away). This is why you have one `GraphQLModule.forRoot()`, one `TypeOrmModule.forRoot()`, etc.
> 
> > `register`, you are expecting to configure a dynamic module with a specific configuration for use only by the calling module.
> 
> so I believe you're trying to implement the `register` one, not `forRoot`. See how this is done in `@nestjs/axios`: https://github.com/nestjs/axios/blob/master/lib/http.module.ts

Thanks for your answer. There they are using a random string which will cause every call to create a unique module, in my suggestion (which you can also apply by providing a dummy provider) you will get the same module if you provide the same parameter.

In any case this behavior of DynamicModule is very confusing and it took us some debugging into the internals to realize what went wrong all of a sudden... Thoughts on how to mitigate the issue?

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
