### ISSUE TITLE
Microservices do not report logs

### ISSUE THREAD

**Issue by osan15** [nestjs/nest#9557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

I have a microservice that uses MQTT as a transport (the one uses a connection with certificates).
I have enabled the logs in the `NestFactory.createMicroservice` function (like this: `{logger: ['log', 'error', 'warn', 'debug', 'verbose']}`)
If I enter a wrong parameter like a wrong client key or a wrong certificate, I don't get any feedback in the logs to tell me that the connection is in error.
The only thing is that the `microService.listen()` promise is not resolved.

I tried to call directly the mqqt.js library.
It gives me many errors in the "`onerror`" event.

I looked at the Nestjs repository for the MQTT transport and I saw that normally the error logs were sent to the logger.
Here is an example of code

```typescript
const myMicroservice = await NestFactory.createMicroservice(
    MyModule,
    {
       transport: Transport.MQTT,
       key: "...",
       cert: "...",
       ca: "...",
       logger: ['log', 'error', 'warn', 'debug', 'verbose']
    },
  );
  await myMicroservice.listen();
 ```
I have the same problem in the gateway using this micro service, I have no logs that tell me that the connection has failed.

How to solve this problem ?

Thank you in advance

### Minimum reproduction code

https://codesandbox.io/s/red-browser-68cmtd?file=/src/main.ts

### Expected behavior

The microservice should indicate that the connection to the MQTT server has failed.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.4

### Packages versions

```json

```

### Node.js version

v16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
