### ISSUE TITLE
Support ECMAScript decorators (coming in TypeScript 4.8)

### ISSUE THREAD

**Issue by smithki** [nestjs/nest#9558]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The [TC39 decorators proposal is stage 3](https://github.com/tc39/proposal-decorators) and TypeScript has plans to implement the spec in [version 4.8](https://github.com/microsoft/TypeScript/issues/49074). I'm new to NestJS, but I figure that supporting the new spec is a large, breaking change for the framework. I don't expect to see a full transition for some time, but it would be nice to track progress in an issue here on GitHub. I'm interested to see the ecosystem move towards standardized decorators sooner rather than later to (hopefully) avoid a similar mess to the one we saw with the transition from CommonJS to ES modules.

### Describe the solution you'd like

Find a way to support standardized ECMAScript decorators.

### Teachability, documentation, adoption, migration strategy

I'm not experienced enough with NestJS yet to offer advice on adoption strategy.

### What is the motivation / use case for changing the behavior?

To future-proof the framework and align to the language standard.

**Comment by kamilmysliwiec** [comment]
When it becomes a "thing", we'll start tracking the migration and estimating how much effort & time it will take. Currently, there are too many unknowns, we don't know what the final implementation in TS will work/look like. I hope they won't introduce too many breaking changes as it will undoubtedly greatly hurt the ecosystem.
