### ISSUE TITLE
Page: "MongoDB E2E Testing (Mongoose + Mockgoose)" is unlisted and has a broken link

### ISSUE THREAD

**Issue by linck5** [nestjs/nest#961]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
</code></pre>

This page: https://docs.nestjs.com/recipes/mockgoose

- Is not listed on https://docs.nestjs.com under "Recipes" tab
- At the very bottom of the page: "The full source code's available here.", the link goes to a 404 page

**Comment by kamilmysliwiec** [comment]
This article is outdated - that is the reason why it's hidden from the main navigation.
