### ISSUE TITLE
Add `Controller(prefix: never[]): never` function for the type safety

### ISSUE THREAD

**Issue by samchon** [nestjs/nest#9616]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

```typescript
export function Controller(prefix: string | string[]): ClassDecorator;
```

The `NestJS` Controller can get a string array typed parameter. However, if someone takes a mistake that configuring an empty array to the parameter, such mistake couldn't be caught in the compile time. The mistake only be caught in the runtime and the error message is not enough helprful.

```bash
The "path" argument must be of type string. Received an instance of Array
```

I think they may take such mistake by below scenario

  1. Decided to configure multiple paths
  2. Declared array at first
  3. Forgot the multiple paths configuration, because no compile error exists
  4. Meets the runtime error, `The "path" argument must be of type string. Received an instance of Array`

### Describe the solution you'd like

Therefore, I recommend to add never typed function like below, to catch the empty array error in the compilation level.

```typescript
export function Controller(): ClassDecorator;
export function Controller(prefix: never[]): ClassDecorator;
export function Controller(prefix: string | string[]): ClassDecorator;
export function Controller(options: ControllerOptions): ClassDecorator;
```

In the same reason, I recommend to add never typed function for the route decocrators.

```typescript
export function Get(path: never[]): never;
export function Post(path: never[]): never;
export function Patch(path: never[]): never;
export function Putt(path: never[]): never;
export function Delete(path: never[]): never;

export function Get(path?: string | string[]): MethodDecorator;
export function Post(path?: string | string[]): MethodDecorator;
export function Patch(path?: string | string[]): MethodDecorator;
export function Put(path?: string | string[]): MethodDecorator;
export function Delete(path?: string | string[]): MethodDecorator;
```

### Teachability, documentation, adoption, migration strategy

If the never typed function be declared, such empty array would cause a compile error.

![image](https://user-images.githubusercontent.com/13158709/169084702-6e570fe2-f871-4d96-81de-50207579fb50.png)

### What is the motivation / use case for changing the behavior?

With the never typed function, `NestJS` users do not need to afraid the empty array more.

**Comment by micalevisk** [comment]
Also, I believe that `@Controller()` should behave the same as `@Controller([])` and `@Controller({ path: [] })`, but currently it doesn't. So, to me, this is a bug
