### ISSUE TITLE
Deprecated fastify dependencies for @nestjs/swagger package

### ISSUE THREAD

**Issue by ssibrahimbas** [nestjs/nest#9617]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8.0.0

### Describe the regression

In order to integrate Swagger into my NestJS application where I use Fastify, I started to review the NestJS Swagger document and proceed with it. Then fastify said that the `fastify-swagger` and `fastify-static` packages that the `@nestjs/swagger` library uses are deprecated, suggesting using `@fastify/swagger` and `@fastify/static` instead.

We need to review the dependencies of the `@nestjs/swagger` package.

Warning Image:

Next, we also have to update the NestJS Swagger Documentation because it still tells us to install the `fastify-swagger` package. It should tell us to install the `@fastify/swagger` package instead.

Waiting for your feedback!

### Minimum reproduction code

https://github.com/ssibrahimbas/ssi-web

### Input code

```ts

```

### Expected behavior

A stand-up without warning should be expected by updating fastify dependencies.

### Other

When application started, console output:

```
(node:16605) [FST_MODULE_DEP_FASTIFY-SWAGGER] FastifyWarning.fastify-swagger: fastify-swagger has been deprecated. Use @fastify/swagger@6.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16605) [FST_MODULE_DEP_FASTIFY-STATIC] FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0 instead.
```

**Comment by micalevisk** [comment]
duplicate #9542

`@nestjs/swagger`: https://github.com/nestjs/swagger

**Comment by jmcdo29** [comment]
[Did](https://github.com/nestjs/swagger/pull/1928) [you](https://github.com/nestjs/swagger/pull/1908) [look at](https://github.com/nestjs/swagger/pull/1923) [the swagger repo](https://github.com/nestjs/swagger/pull/1886)?

**Comment by ssibrahimbas** [comment]
ouw so sorry, thanks for the warning.
