### ISSUE TITLE
Swagger - Fastify - Deprecated - fastify-swagger has been deprecated

### ISSUE THREAD

**Issue by daniloviic** [nestjs/nest#9620]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As per instructions from [your documentation ](https://docs.nestjs.com/openapi/introduction), we were trying to setup Swagger for our Fastify server.

The installation of packages (`@nestjs/swagger` `fastify-swagger`) works fine, but upon starting the application, the following warning occurs:

```
(node:6575) [FST_MODULE_DEP_FASTIFY-SWAGGER] FastifyWarning.fastify-swagger: fastify-swagger has been deprecated. Use @fastify/swagger@6.0.0 instead.
(node:6575) [FST_MODULE_DEP_FASTIFY-STATIC] FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0 instead.
```

Upon further investigation I have indeed discovered that the [library](https://www.npmjs.com/package/fastify-swagger) is deprecated.

### Describe the solution you'd like

The new library seem to be on the following [github](https://github.com/fastify/fastify-swagger).

The deprecated library should be dropped and replaced with the new one.

### Teachability, documentation, adoption, migration strategy

Project using the deprecated `fastify-swagger` should work just fine, but won't get any new features.

Since none of the code actually leverages the behind the scene libraries, but instead uses `@nestjs/swagger`, the migration shouldn't be a problem.

### What is the motivation / use case for changing the behavior?

Deprecated libraries should not be a part of official documentation and usage.

**Comment by kamilmysliwiec** [comment]
[Please search through some of our old issues on this (this has been discussed several times in the past).](https://github.com/nestjs/nest/issues/9617)
