### ISSUE TITLE
 Nest can't resolve dependencies of the AuthService (?, UserService)

### ISSUE THREAD

**Issue by wmedia** [nestjs/nest#9621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The code is not working as expected and show this:

ERROR [ExceptionHandler] Nest can't resolve dependencies of the AuthService (?, UserService). Please make sure that the argument String at index [0] is available in the AuthModule context.

Potential solutions:
- If String is a provider, is it part of the current AuthModule?
- If String is exported from a separate @Module, is that module imported within AuthModule?
  @Module({
    imports: [ /* the Module containing String */ ]
  })

Doesn't recognizes the native string  type as is, instead supposes that is a provider 

**CODE**

@Injectable()
export class AuthService {
  constructor(
    **protected readonly clientBaseUrl: string**,
    private readonly userService: UserService
  ) {}
  

### Minimum reproduction code

*

### Steps to reproduce

**File: auth.module.ts**

const providers = [
  AuthService
]

@Module({
  imports: [
    RouterModule.forRoutes([
      {
        path: '/auth',
        module: AuthModule
      }
    ]),
    UserModule
  ],
  controllers:[ AuthController ],
  providers: [ ...providers ],
  exports: [ ...providers ]
})
export class AuthModule {}

**File: auth.controller.ts**

@UseInterceptors()
@Controller('auth')
export class AuthController {
  constructor(
    private readonly authService: AuthService
  ) {}

  @HttpCode(HttpStatus.OK)
  @Post('/login')
  @Public()
  @UsePipes(new ValidationPipe({ transform: true }))
  async login(
    @Body() entity: LoginUserDTO
  ): Promise<IAuthRespuesta | null> {
    return this.authService.login(entity)
  }

}

**File: auth.service.ts**

@Injectable()
export class AuthService {
  constructor(
    **protected readonly clientBaseUrl: string**,
    private readonly userService: UserService
  ) {
  
  }

  /**
   * User Login Request
   *
   * @returns
   * @param request
   */
  async login(request: IAccesoUsuarioInput ): Promise<IAuthRespuesta | null> {
    const user = await this.userService.findOne({
      where:{
        email: 'test@mail.com',
        id: 1
      }
    });

    if (!user || !(await bcrypt.compare('cryptedpass', user.hash))) {
      return null;
    }
    return {
      user,
    };
  }

}

### Expected behavior

Start the api serve correctly 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

```json
    "@nestjs/common": "^8.4.5",
    "@nestjs/config": "^2.0.1",
    "@nestjs/core": "^8.4.5",
    "@nestjs/mapped-types": "^1.0.1",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.4.5",
    "@nestjs/typeorm": "^8.0.3",
    "@nestjs/jwt": "^8.0.1",
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
@wmedia also, read the FAQ: https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error

**Comment by wmedia** [comment]
But string is a type not a dependency.

**Comment by jmcdo29** [comment]
I'll say it again:

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
