### ISSUE TITLE
Lazy loaded module can't access global module's providers

### ISSUE THREAD

**Issue by andresberrios** [nestjs/nest#9622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the documentation it says:

> Also, "lazy-loaded" modules share the same modules graph as those eagerly loaded on the application bootstrap as well as any other lazy modules registered later in your app.

But when trying to import a provider that is exported from a globally registered module (which eager modules are able to receive injected into their providers), lazy modules produce an error saying that the provider is not found.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-muxzyg?file=src/app.module.ts

### Expected behavior

I expected the service of the lazy module to be able to import a service from a global module.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
    "@nestjs/common": "^8.1.1",
    "@nestjs/core": "^8.1.1",
}
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by WumaCoder** [comment]
me too

**Comment by WumaCoder** [comment]
I solved this problem in the onModuleInit event.

**Comment by WumaCoder** [comment]
https://stackblitz.com/edit/nestjs-typescript-starter-iqudkj?file=src/lazy.module.ts
```ts
import { Module, Injectable } from '@nestjs/common';
import { ModuleRef } from '@nestjs/core';
import { GlobalService } from './global.module';

@Injectable()
export class LazyService {
  private globalService: GlobalService;

  onModuleInit() {
    this.globalService = this.moduleRef.get(GlobalService);
  }
  constructor(private moduleRef: ModuleRef) {}
}

@Module({
  providers: [LazyService],
})
export class LazyModule {}

```

**Comment by dsullivan** [comment]
It looks like `DependenciesScanner`'s main `scan` method concludes by binding global modules:
```
  public async scan(module: Type<any>) {
    await this.registerCoreModule();
    await this.scanForModules(module);
    await this.scanModulesForDependencies();
    this.calculateModulesDistance();

    this.addScopedEnhancersMetadata();
    this.container.bindGlobalScope();
  }
```

On the other hand, `LazyModuleLoader.load` only calls `scanModulesForDependencies`.

It looks like we could either:
* move the call to `bindGlobalScope` inside the `scanModulesForDependencies` as a side effect, or
* expose `bindGlobalScope` or the container and call it explicitly from `LazyModuleLoader`

I could put together a PR for either approach, but this is pretty deep in the internals and I'm a little nervous about unintended consequences.
