### ISSUE TITLE
[meta] Update the `package-lock.json` file for NPM 8

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#9629]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Using NPM 8, after cloning this repo and running `npm ci` or `npm i`, we got a bunch of NPM warnings:

```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...

...
```

![image](https://user-images.githubusercontent.com/13461315/169674453-27bc4e37-51d9-449f-8244-3fa19b59e7e8.png)

### Describe the solution you'd like

As we're on the road to NestJS v9, I believe it's a good time to update the lockfile by removing it and then run `npm install` to generate a brand new up-to-date one :smiley_cat: But I feel that only Kamil should do this.

I tried that myself locally but then with `npm i` I got the following NPM error:

```bash
## Generate a new lock file
git clone --depth=1 git@github.com:nestjs/nest.git
cd nest
rm package-lock.json
npm i
```

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @nestjs/core@8.4.4
npm ERR! Found: @commitlint/cli@17.0.0
npm ERR! node_modules/@commitlint/cli
npm ERR!   dev @commitlint/cli@"17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @commitlint/cli@"^7.0.0" from commitlint-circle@1.0.0
npm ERR! node_modules/commitlint-circle
npm ERR!   dev commitlint-circle@"1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
...
```

- node: v16
- npm: 8.5
- OS: Ubuntu

We should do the same for each `packages/*/package-lock.json` as well

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

less warning messages (and maybe a slightly fast installation step) for those who want to contribute to the project, and a healthy lockfile (I guess?).

Also, even if we use NPM 6 (node10), we could still run `npm ci` with no worries for that newly created lockfile (`"lockfileVersion": 2`) - I just tested this myself in another project.

**Comment by kamilmysliwiec** [comment]
> Also, even if we use NPM 6 (node10), we could still run npm ci with no worries for that newly created lockfile ("lockfileVersion": 2) - I just tested this myself in another project.

What about `npm install`? Since Nest must be compatible with older versions of Node (v10, v12 etc), I'm typically using older versions for development as well.

**Comment by micalevisk** [comment]
> What about `npm install`?

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

---

I'm unsure how safe is that :/
