### ISSUE TITLE
Add exclude feature for "setGlobalPrefix"

### ISSUE THREAD

**Issue by weeco** [nestjs/nest#963]
Similiar to the exclude feature for middleware I am hereby requesting an exclude feature for the `setGlobalPrefix` method. I believe one can use the same arguments as used in the middleware exclude feature request issue (https://github.com/nestjs/nest/issues/790), to argue why this feature is helpful. 

**Use case:**

I am using the global prefix feature for API versioning, but for stuff like health or monitoring endpoints I'd like to exclude the global prefix.

**Comment by kamilmysliwiec** [comment]
Sounds like a good feature request 👍

**Comment by cyril-lakech** [comment]
Hello,

What API would you like?

.setGlobalPrefix('v1')
.setGlobalPrefixExclusions({path: '/health', method: GET}, ...);

Good first issue but not so easy lol

**Comment by kamilmysliwiec** [comment]
Something like:
```
.setGlobalPrefix('v1', { exclude: [
  { path: '/health', method: RequestMethod.GET }
]});
```
might be quite good I believe 😄

**Comment by cyril-lakech** [comment]
OK nice thanks,

I was wondering in which use case one would exclude a path only for specific Method (GET).

I understand that this API would allow more flexibility, more it adds some complexity that may not be needed in the implementation

**Comment by ericzon** [comment]
Maybe would be interesting if you are exposing your api (with typical crud verbs) and serving html in the same app (only get). Only the first case needs /api prefix.

**Comment by ericzon** [comment]
As far as I know, the approach showed by @br0wn is still valid (https://github.com/nestjs/nest/issues/255#issuecomment-360749246) but it would be great to have a direct way to handle this.

**Comment by cyril-lakech** [comment]
my first iteration to implement this: https://github.com/nestjs/nest/pull/1042

**Comment by Darkein** [comment]
Hello, any news about this feature ?

**Comment by nurikabe** [comment]
Looks like it's stuck with this PR: https://github.com/nestjs/nest/pull/1542

**Comment by pelssersconsultancy** [comment]
would be a really nice feature to have .. is this planned?

**Comment by fdescamps** [comment]
Hi all,

Thanks for this awesome work !
Any news about this PR please ?

F.

**Comment by nvuhung** [comment]
I also need this feature. Any news for this?

**Comment by mzavaletavargas** [comment]
Any news? it's a good idea.

**Comment by Darkein** [comment]
I’m sorry, I actually don’t have time to work on it at all. If some of you can take a look 😊

De : Gustavo Zavaleta Vargas
Envoyé le :mardi 9 juillet 2019 22:49
À : nestjs/nest
Cc : Darkein; Comment
Objet :Re: [nestjs/nest] Add exclude feature for "setGlobalPrefix" (#963)

Any news? it's a good idea.

**Comment by fdescamps** [comment]
Hi,

It seems a proposal (with code) exists here : https://github.com/nestjs/nest/pull/1042
May be it could help ?

A+

**Comment by lkreimann** [comment]
I guess the PR #1542 could fix this too.

**Comment by anaseinea** [comment]
Hi, I found a workaround that can help some of you.
I created a custom Controller decorator which has the prefix that I want to be applied globally.
Then you can use the custom decorator for all controllers that needs this prefix and use the original controller decorator for the exceptions.

The custom decorator looks like this:
`export function InternalController(path: string) {
  return Controller(`internal/${path}`);
}`

**Comment by BrunnerLivio** [comment]
Just a little note for myself in the future;
The next NestJS Terminus major release is dependant on this change since we would like to remove the v6 API until then. The v6 API allowed to register routes without the global prefix. In order to stay compatible, this should be resolved until then!

**Comment by omer-morad-ni** [comment]
> Just a little note for myself in the future;
> The next NestJS Terminus major release is dependant on this request since we would like to remove the v6 API until then. The v6 API allowed to register routes without the global prefix. In order to stay compatible, this should be resolved until then!

Hey, thanks for the answer
We are using Nest 7 (it's excellent) and we want to ignore the `setGlobalPrefix` in some route (and in health route as well)

How can we do that?

**Comment by twigs67** [comment]
@omer-morad-ni did you figure this out? I'm also trying to designate a separate health check path.

**Comment by Overfacto** [comment]
I need this features...

**Comment by galkin** [comment]
After migration to Terminus V7 this issue has bigger priority.

**Comment by kadoshms** [comment]
This feature can be super useful. 
 There's a workaround for this (setting the prefix for each controller), but it would be awesome to have this exclusion as part of the API.

**Comment by yannkaiser** [comment]
Is anybody working on this ?

What do you think of having this option set in the specific Controllers / routes that you don't want to prefix ?

**Comment by brianpooe** [comment]
+1

**Comment by brianpooe** [comment]
Any news on this?

**Comment by Kiliandeca** [comment]
Hi, I started working on it and managed to achieve what Kamil decribed in the comment (back in 2018)
It seems to work but I have yet to add some tests before submitting it, I will try to open a PR tomorrow

**Comment by glebsts** [comment]
Hello, I wonder if this is still alive?

**Comment by omer-morad-ni** [comment]
Yes

**Comment by imusama-akram** [comment]
When will you add this feature of exclude base path from some specific routes?
Is it coming or not? I will be a very much help instead of hard coding 'v1' in each controller except one.

**Comment by hengkx** [comment]
How can I solve this problem?

**Comment by jmcdo29** [comment]
@hengkx you can use a third party package (like `nest-router`), monkey patch the pr in yourself, or just wait, like everyone else is.

@imusama-akram the feature is eventually coming. Pinging on the issue will not speed up the development (most of the time). Also, if you're waiting for this feature for versioning, you're gonna end up having a bag time as you start needing to maintain multiple versions of each route.

The global prefix probably is not, and will not be, the best practice for versioning, as it really _should_ be a __global__ prefix

**Comment by kamilmysliwiec** [comment]
Lets' track this here https://github.com/nestjs/nest/pull/5291

**Comment by fressappdev** [comment]
By any chance this feature been implemented?

**Comment by vsDizzy** [comment]
It would be nice to ignore this at the controller level. I have dev/test controller where I'd like to ignore `setGlobalPrefix`.

**Comment by crazyxhz** [comment]
@nestjs/common ts type is not updated:
![image](https://user-images.githubusercontent.com/6551888/134446021-4d4665f7-eb1c-4a34-b7cb-6d56e16d2add.png)

**Comment by micalevisk** [comment]
@crazyxhz it is

https://github.com/nestjs/nest/blob/72a88d5e76d940cf5b7e962d16dcfa999e283a8f/integration/nest-application/global-prefix/e2e/global-prefix.spec.ts#L30-L31

**Comment by ackvf** [comment]
Would it be possible to extend this to add new Decorator to move the declaration from main.ts to the requested module/controller/method?

Such as this:
![image](https://user-images.githubusercontent.com/2313018/135559649-42fd1f69-4304-4ce8-82f0-74335bc0c22d.png)


I would prefer this^ more over the following:

```
app.setGlobalPrefix('v1', { exclude: [
  { path: '/health/heartbeat', method: RequestMethod.GET },
  { path: '/xyz/hi', method: RequestMethod.GET }
]});
```
