### ISSUE TITLE
CloudEvents support

### ISSUE THREAD

**Issue by Adiqq** [nestjs/nest#9633]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Applications can communicate using events and event data format has to be described.  We can create our own data format, but that may lead to low consistency.  Some standard for event data description can be selected to improve consistency and simplify handling of events.  This would introduce support for events generated by third-party solutions.

### Describe the solution you'd like

I would like to have integrated support for [CloudEvents](https://cloudevents.io/) in NestJS. There's example for [Typescript SDK](https://github.com/cloudevents/sdk-javascript/blob/main/examples/typescript-ex/src/index.ts). Typically API implementing CloudEvents will have single HTTP/HTTPS endpoint ([webhook](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/http-webhook.md)) that handles JSON message that follows [spec](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md) and message is routed/handled based on type attribute. Specification for CloudEvents supports different event formats and protocol bindings, however Javascript/Typescript SDK supports only JSON event format with HTTP/HTTPS or Kafka protocol binding at the moment, with potential support for AMQP/MQTT/NATS/WebSocket protocol bindings in the future. There should be support for sending and receiving CloudEvents, at least with HTTP/JSON.

> CloudEvents is a [specification](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md) for describing event data in a common way. CloudEvents seeks to dramatically simplify event declaration and delivery across services, platforms, and beyond!
> 
> CloudEvents is a new effort and it's still under active development. However, its working group has received a surprising amount of industry interest, ranging from major cloud providers to popular SaaS companies. The specification is now under the [Cloud Native Computing Foundation](https://cncf.io/).

### Teachability, documentation, adoption, migration strategy

User developing server API with NestJS can use `@MessagePattern('hero.kill.dragon')` annotation and receive CloudEvent , if JSON message received on configured HTTP/HTTPS endpoint is valid CloudEvent and MessagePattern matches type attribute from parsed event. This requires configuration of endpoints on which we want to listen, e.g. `["/listen"]` and we want to authenticate requests (basic auth, OpenID/JWT).  Behavior for missed/unparseable messages should be also configurable (with some default behavior).

User developing client functionality, should be able to select one of available endpoints and be able to send CloudEvent to it. List of HTTP/HTTPS endpoints should be configurable. It should be possible to specify authentication data for CloudEvent. There might be also functionality for configuring retries or circuit breaker.

### What is the motivation / use case for changing the behavior?

NestJS offers a lot of integrations out of the box. It seems like good fit to add support for CloudEvents, because it might give it another advantage over other frameworks.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
