### ISSUE TITLE
nestjs graphql upload not working with nestjs/graphql 10.x 

### ISSUE THREAD

**Issue by tkssharma** [nestjs/nest#9647]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

>8.1.3

### Describe the regression

with the earlier version, I was able to do an upload and it was working 
Now I have updated this GitHub example with these dependencies as my original project is using the latest version of nestjs/apollo and nestjs/graphql

```
    "@apollo/federation": "^0.36.1",
    "@nestjs/apollo": "^10.0.11",
    "apollo-server-core": "^3.7.0",
    "@nestjs/graphql": "^10.0.11"
```

After the upgrade I start getting the same old message `TypeError: createReadStream is not a function

### Minimum reproduction code

https://github.com/tkssharma/graphql-upload-with-apollo-federation

### Input code

```ts
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { PersonModule } from './modules/person/person.module';
import {
  ApolloFederationDriver,
  ApolloFederationDriverConfig,
} from '@nestjs/apollo';

@Module({
  imports: [
    PersonModule,
    GraphQLModule.forRoot({
      autoSchemaFile: 'person.gql',
      driver: ApolloFederationDriver,
      debug: true,
      playground: process.env.NODE_ENV !== 'production',
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule { }
```

### Expected behavior

I want to have the upload working on this example, before the upgrade it works as expected but post-upgrade to use apollo federation this does not work 

After I update this example with these dependencies it breaks

```
    "@apollo/federation": "^0.36.1",
    "@nestjs/apollo": "^10.0.11",
    "apollo-server-core": "^3.7.0",
    "@nestjs/graphql": "^10.0.11"
```
I am doing upload using gateway and gateway is using this upload APIs, I am always getting
`TypeError: createReadStream is not a function
I did enough research on this and want this working

we can't remove apollo-server-core which depends on @nestjs/apollo
so I am stuck here on how to get this upload working,

with the above same example, things won't work with the latest nestjs apollo migration to support federation

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
