### ISSUE TITLE
Build fails with the message, 'Error  The "@nestjs/swagger" plugin is not compatible with Nest CLI. Neither "after()" nor "before()" nor "afterDeclarations()" function have been provided.'

### ISSUE THREAD

**Issue by piosystems** [nestjs/nest#9650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I run 'npm run build' I am getting the message ' Error  The "@nestjs/swagger" plugin is not compatible with Nest CLI. Neither "after()" nor "before()" nor "afterDeclarations()" function have been provided.'. 

I have searched online and I can't see any solution provided so far. My nest-cli version is 8.2.6 and the @nestjs/swagger is 5.2.1. My node version is 16.15.0

### Minimum reproduction code

It is a build time error

### Steps to reproduce

1. npm run build

### Expected behavior

The build should complete successfully

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

8.2.6

### Packages versions

```json

"@nestjs/common": "^8.4.5",
"@nestjs/config": "^2.0.1",
"@nestjs/core": "^8.4.5",
"@nestjs/elasticsearch": "^8.1.0",
"@nestjs/jwt": "^8.0.1",
"@nestjs/platform-express": "^8.4.5",
"@nestjs/platform-fastify": "^8.4.5",
"@nestjs/swagger": "^5.2.1",
"@nestjs/typeorm": "^8.0.3",

```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

Running in a Jelastic provisioned virtual environment.

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by kamilmysliwiec** [comment]
There's no correlation between `@nestjs/swagger`, Nest CLI, and `NODE_ENV` so what you described above doesn't seem to be correct.

**Comment by piosystems** [comment]
@kamilmysliwiec that's why the error seemed strange to me too. However, I wouldn't immediately dismiss it because, the experience was real. I have also seen similar issues raised on discord,  e.g. in the context of AWS production environment. See https://discord.com/channels/520622812742811698/606125276845441034/972153409652269066.

**Comment by kamilmysliwiec** [comment]
I'm sorry but there's nothing we can do without a reproduction repository. As I mentioned above, this doesn't seem to be true.
