### ISSUE TITLE
High Severity in dicer@0.2.5 introduced by @nestjs/platform-express

### ISSUE THREAD

**Issue by aps1027** [nestjs/nest#9655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Issues with no direct upgrade or patch:
  ✗ Denial of Service (DoS) [High Severity][https://snyk.io/vuln/SNYK-JS-DICER-2311764] in dicer@0.2.5
    introduced by @nestjs/platform-express@8.4.4 > multer@1.4.4 > busboy@0.2.14 > dicer@0.2.5
  No upgrade or patch available
  
  REF:: https://snyk.io/vuln/SNYK-JS-DICER-2311764

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/packages/platform-express

### Expected behavior

Should solve dicer vulnerability.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
@nestjs/*@8.4.5
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
