### ISSUE TITLE
RPC exception filter is not catching second exception and microservice breaks

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [nestjs/nest#9656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have microservice built with RabbitMQ. When I am throwing RpcException inside microservice for the first time, RPC Exception filter cathces exception and everything goes as expected. However on the second attempt RPC exception breaks the microservice and exception is not cought.

https://user-images.githubusercontent.com/3918999/170045192-9b9ba59b-a168-46d8-a0ad-8dfc249d11c5.mov

### Minimum reproduction code

https://codesandbox.io/

### Expected behavior

RPC exceptions are not breaking the microservices and are catched each time

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.4

### Packages versions

```json
 "@nestjs/apollo": "^10.0.9",
        "@nestjs/axios": "^0.0.5",
        "@nestjs/common": "^8.0.0",
        "@nestjs/config": "^1.1.5",
        "@nestjs/core": "^8.0.0",
        "@nestjs/event-emitter": "^1.0.0",
        "@nestjs/graphql": "^10.0.10",
        "@nestjs/mapped-types": "*",
        "@nestjs/microservices": "^8.2.4",
        "@nestjs/platform-express": "^8.0.0",
        "@nestjs/platform-fastify": "^8.2.4",
        "@nestjs/platform-socket.io": "^8.2.4",
        "@nestjs/platform-ws": "^8.2.4",
        "@nestjs/terminus": "^8.0.6",
        "@nestjs/throttler": "^2.0.0",
        "@nestjs/websockets": "^8.2.4",
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by vytautas-pranskunas-** [comment]
@kamilmysliwiec are suggesting me to create minimal repro example with microservices apps? They should be hosted separatly :) with rabbit mq container etc...

**Comment by vytautas-pranskunas-** [comment]
I am no sure how to host rabbit mq server on StackBlitz together with 2 running apps...

**Comment by kamilmysliwiec** [comment]
It doesn't have to be on Stackblitz, you can create a regular Git repository.

**Comment by vytautas-pranskunas-** [comment]
Hi, so here you go:

https://github.com/vytautas-pranskunas-/nestjs-ms-crash.git

tu run it just type ```npm run docker:serve:all:build```

I was able to narrow the problem.
Everything works fine if i have no further actions in category-svc.controller.ts like this
```
@MessagePattern(CategoryMessagePatterns.GetCategories)
    async getCategories(): Promise<any[]> {
        const categories = this.categorySvcService.getCategories();

        return categories;
    }

```

however if I add redis cache clear for example:
```
@MessagePattern(CategoryMessagePatterns.GetCategories)
    async getCategories(): Promise<any[]> {
        const categories = this.categorySvcService.getCategories();
        await this.redisClient.invalidate('profiles:*');
        return categories;
    }
```

proccess tarts to crash. I was expecting that using ```@UseFilters(new SvcControllerExceptionFilter('CategorySvcController'))``` would handle this gracefully but seems like it is not.

I have also tried to wrap everything into try / catch

```
@MessagePattern(CategoryMessagePatterns.GetCategories)
    async getCategories(): Promise<any[]> {
        try {
            const categories = this.categorySvcService.getCategories();
            console.log('LANDED HERE');
            await this.redisClient.invalidate('profiles:*');
            return categories;
        } catch (ex) {
            throw ex;
        }
    }
```

but effect is the same.
Ideally i would not like to wrap each action into try / catch. 
Also i tried to mimic normal exception by throwing ```new Error``` but it output was the same - crash.

Any suggestions?

**Comment by kamilmysliwiec** [comment]
This issue doesn't seem to be related to NestJS. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
