### ISSUE TITLE
Add health check module

### ISSUE THREAD

**Issue by weeco** [nestjs/nest#966]
For deploying applications in Kubernetes you should always provide a health and liveness check endpoint, which allows Kubernetes to restart a pod if there is an issue. 

**Readiness endpoint:**
Readiness check has to be passed to allow Kubernetes sending traffic to your instance (pod). Therefore it should return an empty response with http status 200 once all initialization stuff is finished and all routes are bound. 

Such an endpoint is important for kubernetes deployment because by default it will send traffic to the pod once the container has been started. Instead we want to make sure the app is fully started and ready to serve traffic using a proper readiness endpoint.

**Liveness endpoint:**
The liveness endpoint is supposed to tell kubernetes if the app is alive or dead.

**Proposal:**
Create a module @nest/health which adds a single health endpoint (whose path can be defined). This endpoint starts to respond with status 200 if certain requirements are met:

1. All initialization stuff is done (asynchronous connections, binding routes, asynchronous modules, etc..)
2. The status of the connections to the infrastructure services (such as a database) is good
3. Allow users to add custom health indicators

**Comment by kamilmysliwiec** [comment]
It's a good idea to provide such functionality out-of-the-box. Do you have any API proposal? :)

**Comment by BMalaichik** [comment]
thinking about module API, I think it should be more abstract, just accepting list of checkers to be verified in controller route method:

I see 2 basic implementations ideas:
1. Use healthcheckers register class
```
type Checker  = { name: string; callback: (...args) => any };

export class HealthCheckerService {
   private registry: Map<string, Checker> = new Map();
    public registerChecker(opts: Checker) {
       // adding to the registry by hashed-name or just name
       const nameHash = someHashFunc(opts.name);
       this.registry.set(nameHash, callback);
   }

   public check() {
    const errors: string[] = [];
    //await Promise.map(this.registry.values(), async checker => {
         try {
          await checker.callback();
        } catch (err) {
          console.error(`Executing ${checker.name} failed: `, err);
          errors.push(obtainedErrorMessage);
        } 
      });
   }
}

@Controller()
class HealthCheckController {
   public constructor(@Inject('checker_token') private readonly healthcheckerService: HealthCheckerService) {}
   @Get()
   public async check() {
    const errors = this.healthcheckerService.check();

    if (!!errors.length) {
      return InternalServerErrorException(errors); // or more configured low-level response, like failStatusCode or whatever
    }
   }
}

```

export class HealthCheckModule {
   static forRoot(opts: { statusEndpointUrl?: string  }): DynamicModule {
        const controllerPath = opts.statusEndpointUrl || "/health";
        Reflect.defineMetadata(constants_1.PATH_METADATA, controllerPath, HealthCheckController);
       // in the same way dynamically set check method route path

        return {
            module: HealthCheckModule,
            controllers: [HealthCheckerController]
            components: [HealthCheckerService],
            exports: [...opts.checkersProviders],
        };
   }
}

```

2. More cooler from my POV, but it needs more general nest-pimp-up)) As for me, one of the major features to be added.
https://github.com/inversify/InversifyJS/blob/master/wiki/multi_injection.md

According to that, from `@nest/health` module we can expose some provider token
```
export const HEALTH_CHECK_PROVIDER_TOKEN = Symbol("health_checker");
```

expose dynamic module

```
export class HealthCheckModule {
   static forRoot(opts: { statusEndpointUrl?: string, checkerProviders: any[]  }): DynamicModule {
        const controllerPath = opts.statusEndpointUrl || "/health";
        Reflect.defineMetadata(constants_1.PATH_METADATA, controllerPath, HealthCheckController);
       // in the same way dynamically set check method route path

        return {
            module: HealthCheckModule,
            controllers: [HealthCheckerController]
            components: [...checkerProviders],
            exports: [...checkerProviders],
        };
   }
}
```

let's define interface:
```
export interface HealthChecker {
   public check(): void | Promise<void>;
}
```

than we can simply inject them into HealthCheckService

```
export class HealthCheckerService {

   public constructor(@MultiInject(HEALTH_CHECK_PROVIDER_TOKEN) checkers: HealthChecker)
   public check() {
    const errors: string[] = [];
    //await Promise.map(this.checkers, async checker => {
         try {
          await checker.callback();
        } catch (err) {
          console.error(`Executing ${checker.name} failed: `, err);
          errors.push(obtainedErrorMessage);
        } 
      });
   }
}
```


For me, option 2 is much cooler since we can operate with any other implemented checker services with their own injections, avoiding callback closures. One thing I am concerned is about injection hierarchy here.

**Comment by BMalaichik** [comment]
once we agree on API (not exactly proposed by me :rofl: ) I can implement it :muscle:

**Comment by unlight** [comment]
Why just not to integrate existing solution?
https://github.com/CloudNativeJS/cloud-health-connect

**Comment by BMalaichik** [comment]
@unlight good point, thanks.
Idea was to create something generic & extensible with ability to add custom health checks policies.
cloud-health-connect can be easily integrated into this module :+1:

**Comment by BMalaichik** [comment]
@weeco here I see a trouble with dependency injection. HealthModule doesn't know anything about your checkers dependencies, so it won't resolve it. correct me if I am wrong, please.

**Comment by BrunnerLivio** [comment]
As @unlight mentioned I think we should use an existing solution. I think [terminus](https://github.com/godaddy/terminus) from godaddy is a good choice which also adds better Kubernetes support in addition. [I've started a repository](https://github.com/BrunnerLivio/nest-terminus) and try to hack around with it from time to time. My proposal would be for a healthCheck:

[health.controller.ts](https://github.com/BrunnerLivio/nest-terminus/blob/master/sample/src/health.controller.ts)
```TypeScript

import { Controller, Get, Inject } from '@nestjs/common';
import { HealthCheck } from '@nestjs/terminus';
import { Connection } from 'typeorm';

@Controller('health')
export class HealthController {
    constructor(@Inject('Connection') public connection: Connection) { }

    @Get('/db')
    @HealthCheck()
    public async DbHealthCheck() {
        return this.connection.isConnected;
    }
}

```

If `@HealthCheck`-decorator is set, it will automatically [append it to the Terminus options](https://github.com/godaddy/terminus#usage).

**Comment by kamilmysliwiec** [comment]
What is definitely a MUST is that custom health checks have to be injectable. Also, I'm not really convinced if we should use decorators for this case (we shall ensure that we don't follow Spring way imho, decorators hell).

**Comment by kamilmysliwiec** [comment]
And lifecycle hooks like `beforeShutdown` should be within an injectable I believe

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec 

> And lifecycle hooks like `beforeShutdown` should be within an injectable I believe

My proposal for that would be:
```TypeScript

import { Injectable } from '@nestjs/common';
import { OnShutdown, OnSignal, BeforeShotdown } from '@nestjs/terminus';

@Injectable()
export class ServerLifecycle {
    constructor() { }

    @OnShutdown()
    async OnServerShutdown() {
        console.log('On Shutdown!!');
    }

}

```
But I do not know if this is the best approach. That would mean you can create multiple hook and I do not know yet if this is a good or a bad thing

**Comment by kamilmysliwiec** [comment]
I think that all this stuff could be easily integrated with Nest using a similar approach to this one that I have described here: https://github.com/nestjs/nest/issues/530. 0 decorators - just expose interfaces for options object, so end-user would know what method should be exposed. Then, all this stuff - lifecycle hooks, custom health checks could be simply managed by the developer.

**Comment by BrunnerLivio** [comment]
I hacked around a bit and got [a working version](https://github.com/BrunnerLivio/nest-terminus) (inspired of nest/typeorm).

## Example

At the moment you can use it with `useClass`. `useExisting`, `useFactory` to be followed.


```TypeScript

import { Module, Injectable } from '@nestjs/common';
import { TerminusModule } from '../../../lib/terminus.module';
import { TerminusOptions } from '../../../lib/interfaces/terminus-options';

@Injectable()
export class TerminusService implements TerminusOptions {
  public async onSignal() {
    console.log('1. onSignal');
  }

  public async onShutdown() {
    console.log('2. onShutdown');
  }

  // Fix me: No public attributes
  public signal: string = 'SIGTERM';
  public logger = console.log;
}

@Module({
  imports: [
    TerminusModule.forRootAsync({
      useClass: TerminusService,
    }),
  ],
})
export class ApplicationModule {}

```

```bash
kill -SIGTERM ${PID}
```
will print the following output:

``` 
1. onSignal
2. onShutdown
```


## Problems

### Express

It does not work with Express yet. The problem is Express does not expose or even store the internal http server instance ((Source)[https://github.com/expressjs/express/blob/master/lib/application.js#L618]). Express would need to add that or `@nest/core` should add a constant similar to `HTTP_SERVER_REF` but with the http server instance, not the adapter instance (which includes a express instance).

**Comment by kamilmysliwiec** [comment]
Looks pretty neat so far @BrunnerLivio

**Comment by BrunnerLivio** [comment]
[Terminus Nest integration](https://github.com/BrunnerLivio/nest-terminus) works so far :tada: 

## Getting started

```bash
nest new 
npm install --save @nestjs/core@5.3.0 @nestjs/common@5.3.0 @brunnerlivio/terminus @godaddy/terminus
```

Example:
```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { TerminusModule } from '@brunnerlivio/terminus';

@Module({
  imports: [TerminusModule.forRoot({
    healthChecks: {
      '/health': async () => true,
    },
  })],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule { }
```

[More samples here](https://github.com/BrunnerLivio/nest-terminus/tree/master/sample)


## Noteable

- Useable with synchronous Module creation `forRoot` or asynchronous `forRootAsync` in combination with `useFactory` or `useClass`
- e2e Tests
- Travis integration
- Commented


Anything to add @kamilmysliwiec ? Can this be a part of the `@nest`-org?

**Comment by kamilmysliwiec** [comment]
@BrunnerLivio 
```
Logging (e.g. when a health route gets registered)
```
As soon as it would be possible to disable/enable them 👍 
```
useExisting. (Never used this option actually myself, so do not even know how it behaves 😅 . Do not know if it makes sense in the context of @nestjs/terminus)
```
It makes sense (read here about useExisting: https://docs.nestjs.com/techniques/database)
```
Continuous deployment to npm (would be nice for other nest modules too!)
```
it would be awesome for each existing nest module. I didn't have enough time to take care of it so far.
```
Compodocs implementation: See feature/docs which has automatic doc generation using travis and gets published on Github pages: https://brunnerlivio.github.io/nest-terminus/
Predefined health checks?
```
not sure what do you mean by that

**Comment by BrunnerLivio** [comment]
Alright, add logging, `useExisting` and npm deployment asap. 

> Compodocs implementation: See feature/docs which has automatic doc generation using travis and gets published on Github pages: https://brunnerlivio.github.io/nest-terminus/

Created a PR with a better description. Hope it clarifies it for you. [brunnerlivio/nest-terminus#1](https://github.com/BrunnerLivio/nest-terminus/pull/1)

> Predefined health checks?

As @weeco mentioned:

> All initialization stuff is done (asynchronous connections, binding routes, asynchronous modules, etc..)
> The status of the connections to the infrastructure services (such as a database) is good

I think there should be an easy way to check these out of the box things.

**Comment by kamilmysliwiec** [comment]
> I think there should be an easy way to check these out of the box things.

i'm open to ideas :)

**Comment by BrunnerLivio** [comment]
brunnerlivio/nest-terminus is now [nest/terminus](https://github.com/nestjs/terminus). I try to release it on npm by the end of the week!

Lets discuss this further on nestjs/terminus. I've also created an issue for the predefined health checks [nestjs/terminus#2](https://github.com/nestjs/terminus/issues/2)

**Comment by zhenwenc** [comment]
@BrunnerLivio Hi, is your package ready to use yet? I don't see `@nestjs/terminus` in npm.

**Comment by BrunnerLivio** [comment]
@zhenwenc I am currently writing the documentation. Hopefully I'll find some time this week to finish everything from my side for the first release.

If you want to try it, you can currently use my test-npm-package:

```bash

npm i @brunnerlivio/terminus

```

Do not use this in production! This has not been approved by @kamilmysliwiec yet and the API interface may change. Nonetheless I'd highly encourage some feedback on the general architecture of the package.

Here are some examples:

- [Example project with database health check](https://github.com/BrunnerLivio/nestjs-terminus-rc-sample)
- [Example project with custom health checks + dns health indicator](https://github.com/nestjs/terminus/tree/master/sample/000-dogs-app)
