### ISSUE TITLE
Wrong typings for MessageHandler

### ISSUE THREAD

**Issue by dkonasov** [nestjs/nest#9668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Return type of `MessageHandler` function is `Promise<Observable<TResult>>`, while actually it returns `Promise<TResult>`.

### Minimum reproduction code

https://github.com/dkonasov/message-handler-typings-bug-demo/blob/b96262ee988bd62ab71f4dc6cbbfc996dcb1ab8b/src/demo-strategy.ts#L12

### Expected behavior

Should be typed according to real return value

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.5

### Packages versions

```
platform-express version : 8.4.5
microservices version    : 8.4.5
schematics version       : 8.0.11
testing version          : 8.4.5
common version           : 8.4.5
core version             : 8.4.5
cli version              : 8.2.6
```

### Node.js version

16.13.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Type should be `Promise<Observable<TResult>> | Promise<TResult>`. Would you like to create a PR for this issue?

**Comment by dkonasov** [comment]
> Type should be `Promise<Observable<TResult>> | Promise<TResult>`. Would you like to create a PR for this issue?

Yes, I'll create it in a next few days, thanks =)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/9674
