### ISSUE TITLE
httpsAgent support for axios httpservice

### ISSUE THREAD

**Issue by tsctrl** [nestjs/nest#9671]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

i am getting error when calling public api as below:

"status": 502,
"message": "unable to verify the first certificate",
"name": "HttpException"to specify agent using http module config to be use such as below:
stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)",

### Describe the solution you'd like

to specify agent using http module config to be use such as below:

// At instance level
```
const instance = axios.create({
  httpsAgent: new https.Agent({  
    rejectUnauthorized: false
  })
});
instance.get('https://something.com/foo');
```

// At request level
```
const agent = new https.Agent({  
  rejectUnauthorized: false
});
axios.get('https://something.com/foo', { httpsAgent: agent });
```

### Teachability, documentation, adoption, migration strategy

https://stackoverflow.com/questions/51363855/how-to-configure-axios-to-use-ssl-certificate
https://github.com/axios/axios/issues/535

### What is the motivation / use case for changing the behavior?

-

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
