### ISSUE TITLE
Crash in HeaderParser in dicer

### ISSUE THREAD

**Issue by hipages-guoxu** [nestjs/nest#9678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Issues with no direct upgrade or patch:
![image](https://user-images.githubusercontent.com/65523876/170674038-64934e08-7da6-4f33-b900-65fb64bd71b7.png)

No upgrade or patch available

I searched, but the issue https://github.com/nestjs/nest/issues/9655 have been closed, I have to open another.

I think there is detail about this security issue the https://github.com/advisories/GHSA-wm7h-9275-46v2
And if you run `yarn audit` it will show more detail.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/packages/platform-express

### Expected behavior

a patch to upgrade

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.5

### Packages versions

```json
@nestjs/common": "^8.4.5",
    "@nestjs/config": "^2.0.1",
    "@nestjs/core": "^8.4.5",
    "@nestjs/mapped-types": "^1.0.1",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.4.5",
    "@nestjs/swagger": "^5.2.1",
    "@nestjs/terminus": "^8.0.6",
    "@nestjs/typeorm": "^8.0.3",
```

### In which operating systems have you tested?

- [x] macOS
- [x] Windows
- [x] Linux

**Comment by kamilmysliwiec** [comment]
@dependabot and Renovate are in charge of automatically creating security (or just dep upgrade) PRs. If it's not closed yet, it will be addressed very soon.
