### ISSUE TITLE
Maximum call stack size exceeded when using validation pipeline with form-data

### ISSUE THREAD

**Issue by CIP43R** [nestjs/nest#9683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Since NestJS doesn't have interceptors or anything else for fastify (which I find quite disappointing as it is being advertised everywhere else on the platform and file uploads are a very essential part of a web application), I wanted to use the fastify-multipart (now @fastify/multipart) package.

As you can see in the sandbox, I registered the middleware the normal way, but I'm using the `attachFieldsToBody` option, so I can properly use the validation pipeline which I've set to global. I have a very simple setup with a DTO for my post request. If you let the sandbox container run, you'll see the 500 error saying `maximum call stack exceeded` which happened in the validation pipeline. 

If I remove the extra option, the validation will not work properly anymore, since it can't parse the form-data and will just throw errors about missing properties. If I disable the validation pipeline, I can see that the form data gets added to the body properly.

### Minimum reproduction code

https://codesandbox.io/s/nestjs-fastify-multipart-bug-17m5ls

### Steps to reproduce

1. Add a post request
2. Use the @Body decorator and a DTO with properties that are being validated with class-validator decorators
3. Install @fastify/multipart or fastify-multipart and register it in the app with the option `attachFieldsToBody: true`
4. Send a request to the api

### Expected behavior

I expected the validation pipeline to not infinitely loop. I am hoping that Nestjs will get native form-data support for Fastify soon.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.1

### Packages versions

```json
{
  "name": "nestjs-fastify-multipart-bug",
  "private": true,
  "version": "1.0.0",
  "description": "",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@fastify/multipart": "6.0.0",
    "@nestjs/common": "^8.1.1",
    "@nestjs/core": "^8.1.1",
    "@nestjs/platform-fastify": "8.4.5",
    "axios": "0.27.2",
    "class-transformer": "0.5.1",
    "class-validator": "0.13.2",
    "fastify": "3.29.0",
    "fastify-cors": "6.1.0",
    "fastify-helmet": "7.1.0",
    "fastify-multipart": "5.4.0",
    "form-data": "4.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.4.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.1.3",
    "@nestjs/schematics": "^8.0.4",
    "@nestjs/testing": "^8.1.1",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.2",
    "@types/node": "^16.11.1",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.29.2",
    "@typescript-eslint/parser": "^4.29.2",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.1",
    "jest": "^27.3.0",
    "prettier": "^2.4.1",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.6",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "ts-node": "^10.3.0",
    "tsconfig-paths": "^3.11.0",
    "typescript": "^4.4.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  },
  "keywords": []
}
```

### Node.js version

14.18.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
