### ISSUE TITLE
deprecated symbol has used @EntityRepository(Address)??

### ISSUE THREAD

**Issue by kushwahashiv** [nestjs/nest#9685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm getting deprecated symbols has used warning?
is this feature has been deprecated?

<img width="597" alt="image" src="https://user-images.githubusercontent.com/4386810/170885066-f3f55cda-3fb6-42b5-b15a-50d739a7bc5f.png">

### Minimum reproduction code

na

### Expected behavior

It should not show warning.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/jwt": "^8.0.1",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/swagger": "^5.2.1",
    "@nestjs/typeorm": "^8.0.3",
    "@types/geojson": "^7946.0.8",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "joi": "^17.6.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.4.0",
    "typeorm": "^0.3.6"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/passport-jwt": "^3.0.6",
    "@types/passport-local": "^1.0.34",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
it was drepecated in typeorm v0.3. Use `typeorm@0.2` instead if you want to.

And his is from `typeorm`, not from NestJS.

Also, there's a WIP PR to support the latest version of TypeORM on `@nestjs/typeorm`: https://github.com/nestjs/typeorm/pull/1233

Please, do some searching and go to the right repository before open issues next time.

**Comment by kushwahashiv** [comment]
> some searching and go to the right repository before open issues next time.

I see docs not up to date https://docs.nestjs.com/techniques/database#custom-repository

**Comment by micalevisk** [comment]
actually, that page is. See https://docs.nestjs.com/techniques/database#typeorm-integration
