### ISSUE TITLE
Multiple `ExceptionFilter` won't work as expect when there is one catches all

### ISSUE THREAD

**Issue by ryanhex53** [nestjs/nest#9696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

**Wrote two exception filters one for `TypeORMError` and the other for all.**
```ts
@Catch(TypeORMError)
export class TypeORMErrorFilter implements ExceptionFilter {
  private readonly logger = new Logger(TypeORMErrorFilter .name);

  catch(exception: TypeORMError, host: ArgumentsHost) {
    this.logger.log(exception.message);
  }
}

@Catch()
export class DefaultExceptionFilter extends BaseExceptionFilter {
  private readonly logger = new Logger(DefaultExceptionFilter.name);

  catch(exception: unknown, host: ArgumentsHost) {
    this.logger.log(exception);
    super.catch(exception, host);
  }
}
```
**Register two exception filters for module**
```ts
{
  provide: APP_FILTER,
  useClass: TypeORMErrorFilter
},
// TypeORMErrorFilter can't catches TypeORMError
{
  provide: APP_FILTER,
  useClass: DefaultExceptionFilter
}
// put the DefaultExceptionFilter below
```
When one controller throw a `TypeORMError` the `TypeORMErrorFilter` can't catch the error but the `DefaultExceptionFilter` does.
But if we reverse the order of filters, put the default one at the top, it works without problem.

```ts
{
  provide: APP_FILTER,
  useClass: DefaultExceptionFilter
},
// put the DefaultExceptionFilter at the top
{
  provide: APP_FILTER,
  useClass: TypeORMErrorFilter
}
// TypeORMErrorFilter works as excepted, DefaultExceptionFilter works too.
```

It seems that the order of `APP_FILTER` register is reversed to its execution order (from bottom to top). I can't tell if this is the expected behavior or if it's a bug.

### Minimum reproduction code

none

### Expected behavior

If it's not a bug, [documentation](https://docs.nestjs.com/exception-filters) here needs to be completed.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.5

### Packages versions

```json
{
    "@nestjs/common": "^8.4.5",
    "@nestjs/config": "^1.2.1",
    "@nestjs/core": "^8.4.5",
    "@nestjs/event-emitter": "^1.1.1",
    "@nestjs/jwt": "^8.0.1",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.4.5",
    "@nestjs/schedule": "^2.0.1",
    "@nestjs/serve-static": "^2.2.2",
    "@nestjs/swagger": "^5.2.1",
    "@nestjs/typeorm": "^8.0.4",
    "axios": "^0.27.2",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "express-mysql-session": "^2.1.8",
    "express-session": "^1.17.2",
    "hbs": "^4.2.0",
    "helmet": "^5.1.0",
    "morgan": "^1.10.0",
    "ms": "^2.1.3",
    "mysql2": "^2.3.3",
    "nanoid": "^3.3.4",
    "passport": "^0.5.2",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "path-to-regexp": "^6.2.0",
    "pinyin": "^2.11.2",
    "qrcode": "^1.5.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.3.0",
    "typeorm": "^0.2.45"
  }
```

### Node.js version

14.18.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
