### ISSUE TITLE
Adding configuration instruction to the docs (JWT configuration)

### ISSUE THREAD

**Issue by virusxd521** [nestjs/nest#9698]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

While integrating the JWT token I've followed the docs step by step yet I still couldn't create the token properly. 
the auth.service file contains a login method that signs the JWT token, according to the docs you only need to include the payload which is not correct.

### Describe the solution you'd like

After a couple of hours, I found that the secret must be included as well in order for the JWT to be signed. 
I'm using symmetric key encryption and I'm importing the key from the environment variables.
Example of the solution I'm using: 

```
  async login(user: any) {
    const payload = { username: user.email, sub: user.userId };
    return {
      access_token: this.jwtService.sign(payload ,{secret: process.env.JWT_SECRET_KEY}),
    };
  }
}
```

I've checked it several times yet if I've missed something I do apologize for wasting your time.

### Teachability, documentation, adoption, migration strategy

I will just use the same token as the docs, using the constant file, and adding the secret as a parameter to the sign method.

### What is the motivation / use case for changing the behavior?

My motivation is to help other people and save them a bit of time.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
