### ISSUE TITLE
fastify-static is deprecated

### ISSUE THREAD

**Issue by carepollo** [nestjs/nest#9716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

after following the instructions of the official docs (https://docs.nestjs.com/recipes/serve-static) I get the following error

```
The "fastify-static" package is missing. Please, make sure to install this library ($ npm install fastify-static) to take advantage of ServeStaticModule.
```
so I do it, but then I get the following warning

```
FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0
```
So I replace the previous package with this one and then I get back again the first errror.

I am aware that this is not a bug per-se, but I believe the framework shouldn't work with deprecated packages.
I must point out that I use fastify-platform

### Minimum reproduction code

https://github.com/carepollo/biller_server/blob/master/src/app.module.ts

### Steps to reproduce

1. Create a regular nest app
2. install and set up fastify platform as the offcial docs says (https://docs.nestjs.com/techniques/performance#performance-fastify)
3. then follow the instuctions as say in https://docs.nestjs.com/recipes/serve-static
4. then follow the instructions mentioned on the section of my current behaviour.

### Expected behavior

be able to run nest app without unexpected warnings.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/serve-static

### NestJS version

8.2.6

### Packages versions

```j
{
  "name": "biller_server",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/jwt": "^8.0.1",
    "@nestjs/mongoose": "^9.1.0",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/platform-fastify": "^8.4.5",
    "@nestjs/serve-static": "^2.2.2",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "mongoose": "^6.3.4",
    "passport": "^0.5.3",
    "passport-jwt": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/passport-jwt": "^3.0.6",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
see https://github.com/nestjs/serve-static/pull/872

**Comment by carepollo** [comment]
> see https://github.com/nestjs/serve-static/pull/872
> 
> btw `@nestjs/serve-static` has its own repo - run `npm docs @nestjs/serve-static`

What am I supposed to do then?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
