### ISSUE TITLE
Make .env defined variables available in config files

### ISSUE THREAD

**Issue by jayarjo** [nestjs/nest#9728]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

`process.env` vars are not available in config files, which doesn't make any sense. Following ticket is related: https://github.com/nestjs/nest/issues/6064#issuecomment-753828357. @kamilmysliwiec marked it as not bug and closed. 

### Describe the solution you'd like

.env files should be imported evaluated and made available for all consequent logic in config files.

### Teachability, documentation, adoption, migration strategy

But it's actually a huge drawback and also not intuitive at all. 

### What is the motivation / use case for changing the behavior?

One would expect dotenv vars to be available in config files to use as a conditional when initializing config props.

**Comment by micalevisk** [comment]
what do you mean by _config files_? I didn't follow

**Comment by jayarjo** [comment]
@micalevisk I meant [this](https://docs.nestjs.com/techniques/configuration#custom-configuration-files), but I just realized that I was trying to access env vars outside of the returning function. So that's why it wasn't working. So nevermind.
