### ISSUE TITLE
set default testEnvironment to node for jest

### ISSUE THREAD

**Issue by pelssersconsultancy** [nestjs/nest#973]
Hi guys,

as nestjs is a serverside framework it would help if you default set "testEnvironment": "node" for jest in package.json or inform people to do this.  I spent an hour debugging while an end-2-end test failed using axios.  (preflight request...).

Kind regards,
Robby Pelssers

**Comment by xxxtonixxx** [comment]
Is that so important to debug? I didn't know :confused:

**Comment by pelssersconsultancy** [comment]
Me neither until I had to spent time debugging this issue :)

https://jestjs.io/docs/en/configuration.html#testenvironment-string

"The default environment in Jest is a browser-like environment through jsdom. If you are building a node service, you can use the node option to use a node-like environment instead."

**Comment by kamilmysliwiec** [comment]
This PR will fix this issue: https://github.com/nestjs/typescript-starter/pull/49
