### ISSUE TITLE
GraphQL subscription doesn't work with authorization 

### ISSUE THREAD

**Issue by Bartek8** [nestjs/nest#9737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Example 1: Subscription doesn't start due to an error related to auth guard. Subscription works if you disable auth guard.
OR
Example 2: Subscription doesn't work, no auth related errors - connection parameter returned correctly.

In the repository I described two cases (auth works, subscription doesn't work and vice versa) in two configurations (code first and schema first). Code and code comments in the link below.
https://github.com/Bartek8/NestJS-Subscription/blob/master/src/graphql/graphql.module.ts

Related issues (obsolete solutions): 
* https://github.com/nestjs/nest/issues/1219
* https://github.com/nestjs/docs.nestjs.com/issues/394

### Minimum reproduction code

https://github.com/Bartek8/NestJS-Subscription

### Steps to reproduce

1. Run command: npm install
2. Run command: npm run start:dev
3. Open a browser and open: http://localhost:4000/graphql (hint: if u prefer playgraund, change this in the graphql.module.ts file)
4. Mutation loginUser -> set global Authorization Header: Authorization: `Bearer ${token}` -> Subscription deliveryPickedUp -> Mutation pickeupDelivery 

### Expected behavior

I expect graphql subscriptions to work correctly with authentication OR I expect the documentation to be updated with an example with the correct configuration, I have tried several ways and no configuration works. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql, graphql-subscriptions, graphql

### NestJS version

8.4.6

### Packages versions

```json
{
  "name": "gql-subscription",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "generate-typings": "ts-node src/graphql/schema-first/generate-typings.ts"
  },
  "dependencies": {
    "@golevelup/nestjs-rabbitmq": "^2.4.0",
    "@nestjs/apollo": "^10.0.14",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.1.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^10.0.15",
    "@nestjs/jwt": "^8.0.1",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.0.0",
    "apollo-server-core": "^3.8.1",
    "apollo-server-express": "^3.8.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "graphql": "^16.5.0",
    "graphql-redis-subscriptions": "^2.4.2",
    "graphql-subscriptions": "^2.0.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "ts-morph": "^15.1.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

14.19.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
