### ISSUE TITLE
fastify-formbody has been deprecated

### ISSUE THREAD

**Issue by DamianGlowala** [nestjs/nest#9738]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

![image](https://user-images.githubusercontent.com/48835293/172206574-5d17e2ef-2c1f-4fe0-a724-195d4cd56997.png)

### Describe the solution you'd like

Replace the deprecated `fastify-formbody` package.

### Teachability, documentation, adoption, migration strategy

n/a

### What is the motivation / use case for changing the behavior?

n/a

**Comment by micalevisk** [comment]
this will be fixed in the next major relase of nestjs (v9). See: https://github.com/nestjs/nest/pull/9588
