### ISSUE TITLE
Fastify 4.0 support

### ISSUE THREAD

**Issue by And2s** [nestjs/nest#9745]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It throws error `FastifyError: fastify-plugin: @fastify/helmet - expected '4.x' fastify version, '3.29.0' is installed` when fastify 4.0 installed along with e.g. `@fastify/helmet 9.1.0`

Without using helmet package, it works fine. I've tested with `@nestjs/platform-fastify 9.0.0-next.1`.

### Describe the solution you'd like

Support Fastify 4.0. It was released today.
https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e

### Teachability, documentation, adoption, migration strategy

...

### What is the motivation / use case for changing the behavior?

...

**Comment by micalevisk** [comment]
it will be support in v9: #9588

**Comment by Tony133** [comment]
see also this PR https://github.com/nestjs/nest/pull/9746
