### ISSUE TITLE
Support caching requests with 4xx responses

### ISSUE THREAD

**Issue by izacsc** [nestjs/nest#9747]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have an API that checks for a record in a database and returns it. If it doesn't find it, it will return 404, not found with a NotFoundException  . There's a client that keeps asking for this record and this database is not regularly updated. Every time it asks for the same record, a new query is made in the database, wasting resources. 

### Describe the solution you'd like

So, instead of searching everytime, I would like to cache the response to save resources. I would like to cache the 4xx requests using the [standard solution](https://docs.nestjs.com/techniques/caching). 

### Teachability, documentation, adoption, migration strategy

It would be useful to cache all 4xx exceptions. Probably a new decorator `@CacheExceptions` or something like this.

### What is the motivation / use case for changing the behavior?

The 4xx responses are, in many times, thrown on purpose, so it makes sense to have the hability to cache them. It also will save machine resources.

**Comment by kamilmysliwiec** [comment]
This should be simple to implement with an interceptor.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
