### ISSUE TITLE
TCP microservice fail with webpack hmr enabled

### ISSUE THREAD

**Issue by neeraj-ec** [nestjs/nest#9748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- Create a `TCP` microservice in monorepo with standard options as described [here](https://docs.nestjs.com/microservices/basics#getting-started)
- Enable `webpack hmr` as described in nestjs [docs](https://docs.nestjs.com/recipes/hot-reload#installation) 
- Modify `start:dev` command with `nest start --webpack --webpackPath webpack-hmr.config.js —watch`
- Run `npm run start:dev`

TCP Microservice boot up fails with error `Error: listen EADDRINUSE: address already in use` when run with webpack hmr enabled.

> ⚠️Note: Port is not actually used by any other process. Change port to whatever number results the same.

### Minimum reproduction code

https://github.com/neeraj-ec/cat-sample

### Steps to reproduce

1. `npm run start:dev cat-service`

Service fails with error
```log
> cat-sample@0.0.1 start:dev
> nest start --webpack --webpackPath webpack-hmr.config.js --watch "cat-service"


 Info  Webpack is building your sources...

webpack 5.72.1 compiled successfully in 2739 ms
[Nest] 42903  - 09/06/2022, 17:34:22     LOG [NestFactory] Starting Nest application...
[Nest] 42904  - 09/06/2022, 17:34:22     LOG [NestFactory] Starting Nest application...
[Nest] 42904  - 09/06/2022, 17:34:22     LOG [InstanceLoader] CatServiceModule dependencies initialized +95ms
[Nest] 42903  - 09/06/2022, 17:34:22     LOG [InstanceLoader] CatServiceModule dependencies initialized +95ms
[Nest] 42903  - 09/06/2022, 17:34:22     LOG [NestMicroservice] Nest microservice successfully started +24ms
[Nest] 42904  - 09/06/2022, 17:34:22   ERROR [Server] Error: listen EADDRINUSE: address already in use ::1:40745
Error: listen EADDRINUSE: address already in use ::1:40745
    at Server.setupListenHandle [as _listen2] (node:net:1414:16)
    at listenInCluster (node:net:1462:12)
    at GetAddrInfoReqWrap.doListen (node:net:1601:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:85:8)
``` 

### Expected behavior

Running the command should run the microservice successfully.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

run-script-webpack-plugin, webpack-node-externals

### NestJS version

8.2.6

### Packages versions

```json
"dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/microservices": "^8.4.6",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "run-script-webpack-plugin": "^0.0.14",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5",
    "webpack": "^5.73.0",
    "webpack-node-externals": "^3.0.0"
  }
```

### Node.js version

18.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

```json
"scripts": {
    "start:dev": "nest start --webpack --webpackPath webpack-hmr.config.js --watch",
  }
```

**Comment by delucca** [comment]
I was able to reduce the issue even further. I don't think it is related only to monorepos and microservices. It seems to be related with Webpack's HMR in general.

For example, I've forked the repo: https://github.com/delucca-workspaces/cat-sample

In my fork I've removed the microservice and the monorepo structure. Leaving just a simple app and after adding HMR it doesn't launch.

You can test both commands:
(runs with HMR and fails)
```
npm run start:dev
```

(runs without HMR and succeed
```
npm run start:dev:alt
```

**Comment by delucca** [comment]
@neeraj-ec I think our docs are outdated (I'm going to update it)

This is the proper webpack config: https://github.com/delucca-workspaces/cat-sample/blob/main/webpack-hmr.config.js

You can checkout my fork and test for yourself :)

**Comment by neeraj-ec** [comment]
@delucca so basically you removed the `run-script-webpack-plugin` from webpack hmr file.
I don’t have much knowledge about webpack but as the plugin’s documentation says 
> Automatically run your script once Webpack's build completes.

Does removing it will have any kind of side-effect?

**Comment by delucca** [comment]
> @delucca so basically you removed the `run-script-webpack-plugin` from webpack hmr file. I don’t have much knowledge about webpack but as the plugin’s documentation says
> 
> > Automatically run your script once Webpack's build completes.
> 
> Does removing it will have any kind of side-effect?

AFAIK since NestJS is responsible for starting the application, using this would initialize the application twice, and that's why you're getting that error (since we would try to launch 2 applications using the same port).

We only need that when we're not using Nest to initialize the application itself.

I think we can close the issue :)

**Comment by delucca** [comment]
@neeraj-ec sorry, I replied to you saying that we would have no issues, but after I talked with @kamilmysliwiec he explained to me exactly how HMR works.

In the docs we have the following:
![](https://user-images.githubusercontent.com/23244943/173529748-ffeddc79-cb72-4ca6-a1a9-09cd23ad2058.png)

As you can see, you should not start your application with `nest start`, that's why you were getting that error. So, you can keep your Webpack config as the docs suggested (with `run-script-webpack-plugin`) and change your `package.json` on your `start:dev` script to use `nest build` instead of `nest start`.

That should solve your issue 😄

**Comment by neeraj-ec** [comment]
Thanks @delucca . `nest build` worked for me with `run-script-webpack-plugin` enabled.
________________________________
