### ISSUE TITLE
How to Connect to MongoDB

### ISSUE THREAD

**Issue by maheraldous** [nestjs/nest#9750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to connect to MongoDB and later I will use the MongoDB Compass to see all the data.

**First try**
I tried these files https://github.com/nestjs/nest/tree/master/sample/06-mongoose/src/cats
but they give me this in the console.

[Nest] 13440  - 09/06/2022, 17:53:47     LOG [NestFactory] Starting Nest application...
[Nest] 13440  - 09/06/2022, 17:53:47     LOG [InstanceLoader] AppModule dependencies initialized +44ms
[Nest] 13440  - 09/06/2022, 17:53:47     LOG [InstanceLoader] MongooseModule dependencies initialized +0ms
[Nest] 13440  - 09/06/2022, 17:54:17   ERROR [MongooseModule] Unable to connect to the database. Retrying (1)...
[Nest] 13440  - 09/06/2022, 17:54:50   ERROR [MongooseModule] Unable to connect to the database. Retrying (2)...
[Nest] 13440  - 09/06/2022, 17:55:23   ERROR [MongooseModule] Unable to connect to the database. Retrying (3)...
[Nest] 13440  - 09/06/2022, 17:55:56   ERROR [MongooseModule] Unable to connect to the database. Retrying (4)...
[Nest] 13440  - 09/06/2022, 17:56:29   ERROR [MongooseModule] Unable to connect to the database. Retrying (5)...
[Nest] 13440  - 09/06/2022, 17:57:02   ERROR [MongooseModule] Unable to connect to the database. Retrying (6)...
[Nest] 13440  - 09/06/2022, 17:57:35   ERROR [MongooseModule] Unable to connect to the database. Retrying (7)...
[Nest] 13440  - 09/06/2022, 17:58:08   ERROR [MongooseModule] Unable to connect to the database. Retrying (8)...

I started the MongoDB Compass and the "C:\Program Files\MongoDB\Server\6.0\bin\mongos.exe" but nothing happen.

**Second  try**

I tried these files https://github.com/nestjs/nest/tree/master/sample/14-mongoose-base
but they give me this in the console.

[Nest] 2696  - 09/06/2022, 18:28:24     LOG [NestFactory] Starting Nest application...
[Nest] 2696  - 09/06/2022, 18:28:24     LOG [InstanceLoader] AppModule dependencies initialized +42ms
[Nest] 2696  - 09/06/2022, 18:28:54   ERROR [ExceptionHandler] connect ECONNREFUSED ::1:27017
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at NativeConnection.Connection.openUri (C:\Users\maheraldous\Desktop\NestJS\nestjs-server\node_modules\mongoose\lib\connection.js:807:32)
    at C:\Users\maheraldous\Desktop\NestJS\nestjs-server\node_modules\mongoose\lib\index.js:340:10
    at C:\Users\maheraldous\Desktop\NestJS\nestjs-server\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\maheraldous\Desktop\NestJS\nestjs-server\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\maheraldous\Desktop\NestJS\nestjs-server\node_modules\mongoose\lib\index.js:1140:10)    
    at Mongoose.connect (C:\Users\maheraldous\Desktop\NestJS\nestjs-server\node_modules\mongoose\lib\index.js:339:20)
    at InstanceWrapper.useFactory [as metatype] (C:\Users\maheraldous\Desktop\NestJS\nestjs-server\src\database\database.provider.ts:7:22)
    at Injector.instantiateClass (C:\Users\maheraldous\Desktop\NestJS\nestjs-server\node_modules\@nestjs\core\injector\injector.js:333:55)
    at callback (C:\Users\maheraldous\Desktop\NestJS\nestjs-server\node_modules\@nestjs\core\injector\injector.js:48:41)

So what should I do

I replaced the database link in every try with different name like:
mongodb://localhost:27017
mongodb://localhost:27017/test
mongodb://localhost/test

I also change those in the MongoDB Compass but still can't connect.

### Minimum reproduction code

I don't have thins on the interned

### Expected behavior

It must work if I follow the examples.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.6

### Packages versions

```json
{
  "name": "nestjs-server",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@fastify/formbody": "^7.0.0",
    "@nestjs/apollo": "^10.0.14",
    "@nestjs/common": "^8.4.6",
    "@nestjs/core": "^8.4.6",
    "@nestjs/graphql": "^10.0.15",
    "@nestjs/jwt": "^8.0.1",
    "@nestjs/mongoose": "^9.1.0",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.4.6",
    "@nestjs/platform-fastify": "^8.4.6",
    "apollo-server-fastify": "^3.8.2",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "fastify-formbody": "^5.3.0",
    "graphql": "^16.5.0",
    "graphql-tools": "^8.2.11",
    "mongoose": "^6.2.2",
    "passport-jwt": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.5"
  },
  "overrides": {
    "@nuxtjs/opencollective": "/dev/null"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.2.6",
    "@nestjs/schematics": "^8.0.11",
    "@nestjs/testing": "^8.4.6",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.1",
    "@types/node": "^17.0.40",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.27.1",
    "@typescript-eslint/parser": "^5.27.1",
    "eslint": "^8.17.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.0",
    "prettier": "^2.6.2",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.3",
    "ts-jest": "28.0.4",
    "ts-loader": "^9.3.0",
    "ts-node": "^10.8.1",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.7.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v18.3.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
that error means that your database server isn't reachable from `localhost:27017`

This is not a bug so please use our discord or stackoverflow instead, thanks.

**Comment by maheraldous** [comment]
How to solve it

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
