### ISSUE TITLE
fastify-formbody has been deprecated

### ISSUE THREAD

**Issue by asif4483** [nestjs/nest#9753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.

### Minimum reproduction code

(node:158572) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead. (Use `node --trace-warnings ...` to show where the warning was created)

### Expected behavior

Hey,
Need to update your package ( @nestjs/platform-fastify )
In this package using old deprecated package of fastify-formbody .

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.6

### Packages versions

```json

```

### Node.js version

14.19.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by asif4483** [comment]
I have run this command in terminal after that warning is not coming.
npm audit fix --force

**Comment by asif4483** [comment]
I have run this command in terminal after that warning is not coming.
npm audit fix --force

**Comment by devis12** [comment]
Okay, but I think you should still leave the issue open, so that they can specify in the required dependencies for platform-fastify a version equal or higher than 6.0.0 for @fastify/formbody (hoping it's not a breaking change), because I see here https://www.npmjs.com/package/@fastify/formbody that version 7.0.1 is reached
