### ISSUE TITLE
Create interface with resource generator

### ISSUE THREAD

**Issue by justinnoor** [nestjs/nest#9758]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The `$ nest g resource` command does not create an interface along with the rest of the files it generates.

### Describe the solution you'd like

Create an interface file along with the other files that are generated with the `$ nest g resource` command.

For example running `$ nest g resource user` would also include a **user.interface.ts** file.

### Teachability, documentation, adoption, migration strategy

This can be mentioned in the existing CRUD generator documentation.

https://docs.nestjs.com/recipes/crud-generator

### What is the motivation / use case for changing the behavior?

Productivity.

**Comment by micalevisk** [comment]
you can use the `nest g interface` 

I'm unsure if having interfaces is common enough since we have classes :thinking:

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
