### ISSUE TITLE
Gateway route parameters

### ISSUE THREAD

**Issue by sergeylukin** [nestjs/nest#9775]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The problem is as follows:

Client expects to open websocket connect at `ws://api.example.com/:id/connect` where id is dynamic route parameter token.

Currently such model is supported in Controllers while I couldn't get it to work in Gateway except for setting up custom Adapter which uses `express-ws` under the hood.

### Describe the solution you'd like

I'd expect consumer API to be something like:

```js
@WebSocketGateway({ path: '/:id/connect' })
connect(req) {
  const { id } = req.params
}
```

### Teachability, documentation, adoption, migration strategy

The same way HTTP clients are consuming REST APIs by using URL route parameter tokens.

### What is the motivation / use case for changing the behavior?

I think it is expected as it's a widely used pattern.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
