### ISSUE TITLE
ConfigService.get<T> returns a string regardless of T

### ISSUE THREAD

**Issue by hswope-arcweb** [nestjs/nest#9777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using ConfigService is its most basic form calling ConfigService.get<T> will always return a string. 

### Minimum reproduction code

https://github.com/hswope-arcweb/config-untyped

### Steps to reproduce

npm run build
npm run start
see error

### Expected behavior

Calling ConfigService.get<T> should return a value of type T.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/config

### NestJS version

8.4.7

### Packages versions

[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.10.0
NPM Version    : 7.24.0

[Nest CLI]
Nest CLI Version : 8.2.6

[Nest Platform Information]
platform-express version : 8.4.7
common version           : 8.4.7
config version           : 2.1.0
core version             : 8.4.7

### Node.js version

16.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I am not exactly sure the thinking here. I am using ConfigService in its most basic form, using .env. Despite the fact that .env files are inherently string based, It is intuitive to think that calling 

get<T>('KEY')

is going to do the best that it can to return a value of type T. It is not.

I would assume a call to get without a type parameter would perform whatever default type inference would happen in a given context. But if I am supplying a type parameter, every effort should be made to return the indicated type.

**Comment by jmcdo29** [comment]
https://github.com/nestjs/config/issues/503

**Comment by hswope-arcweb** [comment]
Sorry. I didn't realize this was in a separate location.
