### ISSUE TITLE
Using both NATS and TCP without creating separate microservices

### ISSUE THREAD

**Issue by prateek-ec** [nestjs/nest#9799]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello,

I am facing an issue where I have a microservice listening via TCP and I wish to subscribe to NATS without creating another microservice.
I looked into custom transporter but while creating microservice I can't provide it since there are already 2 parameters provided in `createMicroservice` method as I have already provided the main module and TCP transporter to the method.

I looked into it and I am unable to find anything to just listen to NATS topics either by creating a module or any other way.

I looked into this thread as well [Using proxy to subscribe](https://github.com/nestjs/nest/issues/6671) but finding it difficult to understand the resource provide in the thread.

Any help will be highly appreciated.
Thank you !

### Describe the solution you'd like

1. Either providing multiple transporters while creating microservices instance
2. A single modular initialization and listening to messages methods

### Teachability, documentation, adoption, migration strategy

1. Easier ways to subscribe to events from multiple subsystems

### What is the motivation / use case for changing the behavior?

A microservice listening to both TCP and NATS or any other subsystem

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
