### ISSUE TITLE
No support from learn.nestjs course administrators

### ISSUE THREAD

**Issue by justinnoor** [nestjs/nest#9800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Never wanted to submit this on the Git repo but cannot get any support or response from the nestjs fundamentals course administrators, or from Teachables.

Now when logging into the course the video is gone - it's just blank screen. The code samples are still in every section, but no video. 

Does the course expire? Unless it was overlooked, don't recall there being an expiration date on the course.

### Minimum reproduction code

learn.nestjs.com

### Expected behavior

When logging into the course, the video is gone. All of the code samples are still in each section, but the video is gone.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
n/a
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
what about support@nestjs.com :thinking:

**Comment by justinnoor** [comment]
There is a  support contact form in the login portal of learn.nestjs.com - it is non-responsive. If the contact form on learn.nestjs is not the correct channel, and support@nestjs.com is the correct channel, this needs to be stated somewhere.

**Comment by micalevisk** [comment]
As I am not on learn.nestjs.com side, I'll leave this open so Kamil can notice this issue.

But yeah, that contact form at https://learn.nestjs.com should work. If it doesn't, you can report that to support@nestjs.com I guess
