### ISSUE TITLE
Update contact support link for the learn.nestjs course

### ISSUE THREAD

**Issue by justinnoor** [nestjs/nest#9801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is a contact support form on the learn.nestjs login portal that is non-responsive. We have been trying to get support for several weeks through this contact form.

We submitted issue #9800 regarding this item and received a response by the community saying the support channel for the fundamentals course is through the following link: support@nestjs.com.

If support@nestjs.com is the correct support link, please update this information on the learn.nestjs.com website.

![Screenshot 2022-06-18 082439](https://user-images.githubusercontent.com/15651037/174445593-f531210b-634f-42ea-8400-38438a3e6cd4.png)

![Screenshot 2022-06-18 082405](https://user-images.githubusercontent.com/15651037/174445598-bb4108a3-913f-49b7-8590-19f6bd1b66a8.png)
 

### Minimum reproduction code

learn.nestjs.com

### Expected behavior

Contact form non-responsive

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
n/a
```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> There is a contact support form on the learn.nestjs login portal that is non-responsive. We have been trying to get support for several weeks through this contact form.

We're responding to every reasonable support request within days (or hours).

> We submitted issue https://github.com/nestjs/nest/issues/9800 regarding this item and received a response by the community saying the support channel for the fundamentals course is through the following link: [support@nestjs.com](mailto:support@nestjs.com).

This isn't correct.

I've just double-checked and I can't find any unanswered email so please, send it again and make sure to leave a link to this issue.
