### ISSUE TITLE
Upgrade deprecated packages

### ISSUE THREAD

**Issue by lewis45454** [nestjs/nest#9802]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Some deprecated packages need updating

### Describe the solution you'd like

Upgrade fastify-cors package to @fastify/cors
Upgrade fastify-formbody package to @fastify/formbody
Upgrade fastify-multipart package to @fastify/multipart
Upgrade fastify-static package to @fastify/static

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

Removes deprecated packages

**Comment by micalevisk** [comment]
duplicate
