### ISSUE TITLE
Create User Returns 201, Does Not Actually Create User

### ISSUE THREAD

**Issue by jared-leddy** [nestjs/nest#9803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using Postman, calling the API endpoint for creating a user, a 201 is returned but the user isn't created.

### Minimum reproduction code

#

### Steps to reproduce

I took the official Nest.js course, and the below code was copied directly from the project. Drop the `const flavors`. The `flavors` part was replaced with `password: hashedPassword`. The DTO was also updated. Otherwise, it's identical code on my end being used. I'm also using a real DB and not a Docker DB. 

```js
  async create(createCoffeeDto: CreateCoffeeDto) {
    const flavors = await Promise.all(
      createCoffeeDto.flavors.map((name) => this.preloadFlavorByName(name)),
    );

    const coffee = this.coffeeRepository.create({
      ...createCoffeeDto,
      flavors,
    });
    return this.coffeeRepository.save(coffee);
  }
```

### Expected behavior

We're expecting the 201 to be returned in Postman. 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/57743183/174463605-16a8ea48-9355-4113-8d90-95efb475fe66.png">

We're also expecting a user to be created. Instead we're getting an empty object. 

<img width="442" alt="image" src="https://user-images.githubusercontent.com/57743183/174463621-3b519fe9-f4f0-4785-a7c8-f34c395532bc.png">

### Package

- [X] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/typeorm

### NestJS version

8.4.6

### Packages versions

```
[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.14.0
NPM Version    : 8.10.0 

[Nest CLI]
Nest CLI Version : 8.2.6 

[Nest Platform Information]
platform-express version : 8.4.6
mapped-types version     : 1.0.1
schematics version       : 8.0.11
passport version         : 8.2.1
typeorm version          : 8.1.2
testing version          : 8.4.6
common version           : 8.4.6
config version           : 2.1.0
core version             : 8.4.6
jwt version              : 8.0.1
cli version              : 8.2.6
```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

This doesn't make any sense. I've got it working in the course codebase, but not in my actual project. Our repo is private, so if your team needs to see the code, please specify who needs to be added.

**Comment by micalevisk** [comment]
please respect the warning message.

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- If it's just a quick question you can ping [our Twitter](https://twitter.com/nestframework)

**Comment by jared-leddy** [comment]
@micalevisk which discord channel?
