### ISSUE TITLE
IntersectionType issue

### ISSUE THREAD

**Issue by mystyle2006** [nestjs/nest#9804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i'm not sure this is bug.
when using intersectionType with other mapper without `as const`,
the result is not expected.

### Minimum reproduction code

nope

### Steps to reproduce

example code

```
class BrandEntity {
  brandName: string;
  brandId: string;
}

class OrderEntity {
  orderNumber: string;
  orderId: string;
  brandId: string;
}

export class TestDto extends IntersectionType(
  OmitType(OrderEntity, ['brandId'] as const),
  PickType(BrandEntity, ['brandId']),
) {}
```

expected properties
- orderId
- orderNumber
- brandId

however, properties
- orderId
- orderNumber
- brandId
- brandName

it's working with const assertion like
```
export class TestDto extends IntersectionType(
  OmitType(OrderEntity, ['brandId'] as const),
  PickType(BrandEntity, ['brandId'] as const),
) {}
```

working

### Expected behavior

Expected properties
- orderId
- orderNumber
- brandId

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### Node.js version

14.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
`as const` is just you bypassing the typescript compiler and should have no effect on the class created by `IntersectionType`. I didn't understand if you have a runtime or build time error. 

Please use our Discord instead or share some real code.

[Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required).
