### ISSUE TITLE
Interceptor not running on socket server event emission in socket gateways

### ISSUE THREAD

**Issue by mwaqar666** [nestjs/nest#9805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

According to [Socket Gateway Interceptor](https://docs.nestjs.com/websockets/interceptors) docs, interceptors can be implemented in same way as implementing on any other controller. This also works if, in socket gateways, you return the data from same method where you listened the event. Example:

```
// Interceptor will run in this case

@SubscribeMessage("IncomingEvent")
@UseInterceptors(SomeInterceptor)
public handler(socket: Socket) {
    return "dummyStringData";
}
```

But if you use socket server to to emit any messages to connected clients, then it won't work. Example:

```
// Interceptor will not run in this case

@WebSocketGateway()
class SomeGateway {
    @Server
    private socketServer: Server;

    @SubscribeMessage("AnotherIncomingEvent")
    @UseInterceptors(SomeInterceptor)
    public anotherHandler(socket: Socket) {
        this.socketServer.to(socket.id).emit("OutgoingEvent");
    }
}
```

When the socket server emits the events to clients, then the interceptor will not run. Is this an issue of the framework? I have asked this question on StackOverflow [here](https://stackoverflow.com/questions/72672649/intercepting-messages-emitted-from-socket-server-in-nestjs) but I haven't received any responses yet. So I am posting it here.

Thanks

### Minimum reproduction code

https://codesandbox.io/s/condescending-fast-vuynom

### Expected behavior

Interceptor should run

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

socket.io

### NestJS version

8.0.0

### Packages versions

```
{
  "dependencies": {
    "@nestjs-modules/mailer": "^1.6.1",
    "@nestjs/bull": "^0.4.2",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mapped-types": "^1.0.1",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/platform-fastify": "^8.2.6",
    "@nestjs/platform-socket.io": "^8.4.4",
    "@nestjs/sequelize": "^8.0.0",
    "@nestjs/websockets": "^8.4.4",
    "socket.io": "^4.4.1",
  }
}
```

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> But if you use socket server to to emit any messages to connected clients, then it won't work. Example:

That's the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
