### ISSUE TITLE
`BaseExplorerService` not exported from `@nestjs/graphql`

### ISSUE THREAD

**Issue by rizwanahmed19** [nestjs/nest#9816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using a plugin to calculate the query complexity of my graph using [these docs](https://docs.nestjs.com/graphql/complexity).
When I provide the plugin in the list of providers I get this error

```
class PluginsExplorerService extends graphql_1.BaseExplorerService {
                                               ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/rizwan/Work/Sweetgreen/sg-monorepo/node_modules/@nestjs/apollo/dist/services/plugins-explorer.service.js:7:48)
```

I tried logging the `graphql_1` in `plugin-explorer.service.js` inside `node_modules` and couldn't find `BaseExplorerService` in the object. It is exported from the `graphql` module but not accessible.

### Minimum reproduction code

https://docs.nestjs.com/graphql/complexity

### Steps to reproduce

1. Create the complexity plugin
2. Add it to the list of providers in any module
3. See error

### Expected behavior

The `BaseExplorerService` should be accessible from `apollo/services/plugins-explorer.service.ts` file and code should compile without any errors

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/graphql

### NestJS version

8.4.7

### Packages versions

```json
"@nestjs/apollo": "^10.0.6",
    "@nestjs/axios": "^0.0.3",
    "@nestjs/common": "^8.2.4",
    "@nestjs/config": "^1.1.5",
    "@nestjs/core": "^8.4.7",
    "@nestjs/event-emitter": "^1.1.1",
    "@nestjs/graphql": "9.1.2",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mapped-types": "^1.0.1",
    "@nestjs/passport": "^8.0.1",
    "@nestjs/platform-express": "^8.2.4",
    "@nestjs/swagger": "^5.1.5",
    "@nestjs/terminus": "^8.0.3",
    "@nestjs/typeorm": "^8.0.2",

```

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
