### ISSUE TITLE
app.resolve(token) throws UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getInstanceByContextId' of undefined

### ISSUE THREAD

**Issue by TbotaPhantA** [nestjs/nest#9818]
### Is there an existing issue for this?

- [X] I have searched the existing issues. I found one issue with same error, but very different scenario.

### Current behavior

I have logger module. It has transient provider which is `AbstractLoggerService` with two implementations `CatLoggerService` and `DogLoggerService`. 

`bootstrap` function cannot resolve this transient provider:
```typescript
async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  // fails on versions below 8.0.0 !!!
  const logger = await app.resolve<AbstractLoggerService>(LOGGER_TOKEN);

  logger.setContext('bootstrap');

  app.useLogger(logger);

  await app.listen(3000);
}
```

### Minimum reproduction code

https://github.com/TbotaPhantA/nestjs-issue-app-resolve-error

### Steps to reproduce

1. `npm i` or `npm i --legacy-peer-deps` (`nestjs/common` and `nest/core` should have versions below `8.0.0` ).
2. `npm run start:dev`

### Expected behavior

NestJS should resolve Logger provider and launch application without any errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

7.6.15

### Packages versions

```json
{
  "name": "nest-test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^7.6.15",
    "@nestjs/config": "^0.6.3",
    "@nestjs/core": "^7.6.15",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "sleep": "^6.3.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.6.0",
    "@nestjs/schematics": "^7.3.1",
    "@nestjs/testing": "^7.6.15",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
```

### Node.js version

17.9.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

- The only way I managed to solve this issue is by upgrading from `7.6.15` to `8.0.0`. 

- It would be great if you'll provide another solution.

- If you'll not find another solution people should at least be able to google this issue by this error.

**Comment by micalevisk** [comment]
I believe we won't release patches for old versions :/ if this was a bug that have been fixed in v8, then you should use v8

**Comment by kamilmysliwiec** [comment]
We do release patches for older versions @micalevisk (security fixes etc).

However, this isn't a bug but rather a dependencies version mismatch in your project. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
