### ISSUE TITLE
Access Mongoose Model from a function like old way

### ISSUE THREAD

**Issue by maheraldous** [nestjs/nest#9833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Just don't know how should I call and query the user model from anywhere without passing it to a class like UserSerivce Class. In app without NestJS was it easy by just doing like that

```
// schema file
import mongoose from 'mongoose';
const { Schema } = mongoose;

const blogSchema = new Schema({
  title:  String, // String is shorthand for {type: String}
  author: String,
  body:   String,
  comments: [{ body: String, date: Date }],
  date: { type: Date, default: Date.now },
  hidden: Boolean,
  meta: {
    votes: Number,
    favs:  Number
  }
}); 

export const BlogMD = mongoose.model('Blog', blogSchema);
```

```
// Another file
import { BlogMD } from 'schema file'

const getUser = async (parent, args, context, info) => {
    const user = await BlogMD .findById(context.userAuth.currentUser._id);
    if (!user) {
      return new Error('No User found.')
    }
    return user 
  }
```

So since I use NestJS I was also trying to access userService but it didn't work
![image](https://user-images.githubusercontent.com/41970874/175701393-21170560-0202-4a6c-9162-16eba3656d94.png)

I asked on Discord but they didn't know so I hope @kamilmysliwiec  can help.

These are the photos I had on discord

![image](https://user-images.githubusercontent.com/41970874/175703874-23a9ab8a-22c4-49cc-950e-9f3ad5fd3a37.png)

![image](https://user-images.githubusercontent.com/41970874/175705503-09c0b4d0-65ec-4840-870a-ef983e4a8117.png)

![image](https://user-images.githubusercontent.com/41970874/175706182-450117da-83cf-46d7-96b5-6faa3c43ead9.png)

When I add this line `export const UserMD = model('user', UserSchema);`

I get this error
![image](https://user-images.githubusercontent.com/41970874/175708700-51d98d79-9bd4-4472-ba9c-36de90f66f08.png)

### Minimum reproduction code

I don't have thins on the internet

### Expected behavior

Be able to query Mongoose as old way but by keeping NestJS in the app but free Mongoose of NestJS or at least let NestJS allow using the query.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

mongoose version 9.1.0

### NestJS version

8.2.6

### Packages versions

```json
{
  "name": "apiserver",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/apollo": "^10.0.14",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^10.0.15",
    "@nestjs/mongoose": "^9.1.0",
    "@nestjs/platform-express": "^8.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/jsonwebtoken": "^8.5.8",
    "apollo-server-express": "^3.8.2",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "dotenv": "^16.0.1",
    "graphql": "^16.5.0",
    "graphql-middleware": "^6.1.29",
    "graphql-rate-limit": "^3.3.0",
    "graphql-shield": "^7.5.0",
    "graphql-ws": "^5.9.0",
    "helmet": "^5.1.0",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.21",
    "mongoose": "^6.3.8",
    "mongoose-unique-validator": "^3.1.0",
    "path": "^0.12.7",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "ws": "^8.8.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v18.3.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I don't follow what you're trying to do but looks like you're trying to use providers out side of nestjs DI context.

If you call `new FooService()`, there's no place for nestjs to resolve the dependencies of `FooService`.

---

We don't track questions here, sorry.

Also, there's no old vs new here. You can manage to use both together because it's just nodejs, in the end.

**Comment by maheraldous** [comment]
Don't close something just to end it. No if you used Express with Mongoose before you will understand what I was trying to do. If you just forget the pictures and looks at the code I wrote in the beginning of the question you will see that even without taking context it must work. I don't want the context because this is not the issues here.

If you can find this code hard to read like that

```
// Another file not a NestJS file. Just normal .ts file
import { BlogMD } from 'schema file'

const getUser = async (parent, args, context, info) => {
    const user = await BlogMD .findById(context.userAuth.currentUser._id);
    if (!user) {
      return new Error('No User found.')
    }
    return user 
  }
```

How about that without the context argument.
```
// Another file not a NestJS file. Just normal .ts file
import { BlogMD } from 'schema file'

const getUser = async (parent, args, context, info) => {
    const user = await BlogMD .findById(context.userAuth.currentUser._id);
    if (!user) {
      return new Error('No User found.')
    }
    return user 
  }
```

Please see this for more information
https://mongoosejs.com/docs/api.html#model_Model.findById

Mongoose allows us to call the model where what we want but NestJS tells you just to use it in Resolver and Service only so if there is none Resolver and Service file like another file then it seems I can do what I want.

**Comment by maheraldous** [comment]
Don't close something just to end it. No if you used Express with Mongoose before you will understand what I was trying to do. If you just forget the pictures and looks at the code I wrote in the beginning of the question you will see that even without taking context it must work. I don't want the context because this is not the issues here.

If you can find this code hard to read like that

```
// Another file not a NestJS file. Just normal .ts file
import { BlogMD } from 'schema file'

const getUser = async (parent, args, context, info) => {
    const user = await BlogMD .findById(context.userAuth.currentUser._id);
    if (!user) {
      return new Error('No User found.')
    }
    return user 
  }
```

How about that without the context argument.
```
// Another file not a NestJS file. Just normal .ts file
import { BlogMD } from 'schema file'

const getUser = async () => {
    const user = await BlogMD .findById("12345");
    if (!user) {
      return new Error('No User found.')
    }
    return user 
  }
```

Please see this for more information
https://mongoosejs.com/docs/api.html#model_Model.findById

Mongoose allows us to call the model where what we want but NestJS tells you just to use it in Resolver and Service only so if there is none Resolver and Service file like another file then it seems I can do what I want.

**Comment by jmcdo29** [comment]
As I've already told you on Discord you don't have to use `@nestjs/mongoose`. You can use `mongoose` alone, create a connection object in a `mongoose.ts` file and all of your schemas as you already do, without the use of `@Schema()` or the `SchemaFactory` object from `@nestjs/mongoose`. 

> but NestJS tells you just to use it in Resolver and Service only

Because of how provider naturally work. If you don't use `@nestjs/mongoose` then this isn't a problem. It seems like you're holding to a way of functional programming without the use of Dependency Injection via Object Oriented Principles, and that's okay, it just doesn't fit _as well_ with Nest's model of code.

> Don't close something just to end it.

micael wasn't closing it to end it, he was closing it because we don't use GitHub to provide support, that's what our [Discord Server](https://discord.gg/nestjs) is for.
