### ISSUE TITLE
Bug with installing NestJs in a workspace.

### ISSUE THREAD

**Issue by NeutronScott12** [nestjs/nest#9835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When installing Nest it splits between the two node_modules, causing problems like this "Cannot find module '@nestjs/jwt'", because there are two instances of nest installations one in the main node_modules and one in the project's local node_modules.

One fix I found, though more of a hack if I create another dummy nest application in the workspace, it installs all nest dependencies in the main node_modules and doesn't split it.

Just run the code in the link and it should repeat the same problem.

### Minimum reproduction code

https://github.com/NeutronScott12/NewsReviewRepo

### Steps to reproduce

Just install with yarn, run the news-review-backend, and this error should "Cannot find module '@nestjs/jwt', if I take @nestjs/jwt package and place it in the main node_modules it works again.

### Expected behavior

I expected the nest installation to install in the main node_modules, instead of splitting.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/jwt @nestjs/apollo

### NestJS version

8.4.7

### Packages versions

```json

```

### Node.js version

v16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
looks like the package `@thelasthurrah/the-last-hurrah-shared` is trying to use `@nestjs/jwt` but it doesn't have such dependency listed in their `package.json`

Please, use our [Discord](https://discord.gg/nestjs) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
