### ISSUE TITLE
Problem Dependency Version with Fastify

### ISSUE THREAD

**Issue by digladieux** [nestjs/nest#9845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I had this warning when I launch my app

```
(node:13053) [FST_MODULE_DEP_FASTIFY-MULTIPART] FastifyWarning.fastify-multipart: fastify-multipart has been deprecated. Use @fastify/multipart@6.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13053) [FST_MODULE_DEP_FASTIFY-STATIC] FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0 instead.
(node:13053) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.
```

So I decided to update my dependencies related to fastify. But I receive a new error

```
/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/pluginUtils.js:107
  if (!semver.satisfies(this.version, requiredVersion)) throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
                                                              ^
FastifyError: fastify-plugin: @fastify/multipart - expected '4.x' fastify version, '3.29.0' is installed
    at Object.checkVersion (/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/pluginUtils.js:107:63)
    at Object.registerPlugin (/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/pluginUtils.js:121:16)
    at Boot.override (/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/node_modules/@nestjs/platform-fastify/node_modules/avvio/plugin.js:80:33)
    at Boot.loadPlugin (/node_modules/@nestjs/platform-fastify/node_modules/avvio/plugin.js:274:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

In my package json in dependencies before  :

```
    "@nestjs/platform-fastify": "^8.4.5",
    "fastify": "^3.25.3",
    "fastify-multipart": "^5.2.1",
    "fastify-swagger": "^4.13.1",
```
So I update all my packages related to fastify

```
    "@nestjs/platform-fastify": "^8.4.7",
    "@fastify/multipart": "^7.1.0",
    "fastify": "^4.1.0",
    "@fastify/static": "^6.4.0",
```

When I check the yarn.lock, the only dependency releated to fastify 3.x is @nestjs/platform-fastify

```
"@nestjs/platform-fastify@^8.4.7":
  version "8.4.7"
  resolved "https://registry.yarnpkg.com/@nestjs/platform-fastify/-/platform-fastify-8.4.7.tgz#5c37fe00b4d5c039c4fc0f43c0d14cfc0fa101aa"
  integrity sha512-3miB5AYQMlwTAC6W3HE3UTfsQF5RcCsellIEHhNKWN9jGA3C++zr24nEBzw61+Ca2fOG4+ccg4agtODn53d+UA==
  dependencies:
    fastify "3.29.0"
    fastify-cors "6.1.0"
    fastify-formbody "5.3.0"
    light-my-request "5.0.0"
    middie "6.1.0"
    path-to-regexp "3.2.0"
    tslib "2.4.0"
```

Is there any way to upgrade fastify ?

### Minimum reproduction code

/

### Steps to reproduce

$ yarn install
$ nest start

### Expected behavior

My app should launch without warning

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.5

### Packages versions

[System Information]
OS Version     : macOS Monterey
NodeJS Version : v16.14.0
NPM Version    : 8.3.1 

[Nest CLI]
Nest CLI Version : 8.2.6 

[Nest Platform Information]
platform-fastify version : 8.4.7
schematics version       : 8.0.11
graphql version          : 10.0.16
swagger version          : 5.2.1
typeorm version          : 8.1.4
testing version          : 8.4.7
apollo version           : 10.0.16
common version           : 8.4.7
core version             : 8.4.7
cli version              : 8.2.6

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Fastify plugins update and new fastify version (v4.x) will be updated on NestJS v9 
 
see this PR #9588.

**Comment by jmcdo29** [comment]
[Is it](https://github.com/nestjs/nest/issues/9813) [so hard](https://github.com/nestjs/nest/issues/9802) [to search](https://github.com/nestjs/nest/issues/9767) [previous issues](https://github.com/nestjs/nest/issues/9739)? [This has](https://github.com/nestjs/nest/issues/9753) [already been](https://github.com/nestjs/nest/issues/9738) [discussed](https://github.com/nestjs/nest/issues/9716)
