### ISSUE TITLE
How to do a queries in nestjs using cqrs module?

### ISSUE THREAD

**Issue by yussenn** [nestjs/nest#985]
I am using nestjs in my app backend.I use the cqrs module https://github.com/nestjs/cqrs, I read that cqrs have a commands to write operations and queries to read operation but nestjs documentation (https://docs.nestjs.com/recipes/cqrs) only has a example of command so How Do I implement a queries in nestjs?

**Comment by kamilmysliwiec** [comment]
There is no single recommended solution. CQRS module is all about the write-side, whereas read-side is much simpler and less complex. Use whatever fits your requirements.
