### ISSUE TITLE
No example for postgre

### ISSUE THREAD

**Issue by oscarlagatta** [nestjs/nest#9850]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have seen many tutorials using PostgreSQL even from the training from the authors, and cannot find a working example anywhere.

### Describe the solution you'd like

PostgreSQL working example

### Teachability, documentation, adoption, migration strategy

many tutorias using PostgreSQL

### What is the motivation / use case for changing the behavior?

many tutorias using PostgreSQL

**Comment by jmcdo29** [comment]
Would this example be a raw postgres connection using something like the `pg` library (`node-pg`) or would it be going through something like `knex` or `typeorm`? I [have some old code](https://github.com/jmcdo29/zeldaPlay/tree/main/apps/api/src/app/database) that's essentially a custom ORM using the pg library if you want to take a look at it.

**Comment by Tony133** [comment]
@oscarlagatta see if you are interested I made a package: https://github.com/Tony133/nestjs-postgres

Find [here](https://dev.to/tony133/postgres-module-for-nestjs-8x-framework-599j)  a tutorial on how the package works.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
