### ISSUE TITLE
Using this context in custom method decorator

### ISSUE THREAD

**Issue by samuraitruong** [nestjs/nest#9855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We enable some tracking(newrelic) on the custom interval task scheduling. To implement this I have created the custom decorator to wrap the function. It was working perfect fine base on js/typescript decorator behavior. however, when the function execute this context is missing all the private field and the injected. field. (Only display class the methods)

my decorator look like

```
export function BackgroundTransaction(
  transactionName?: string,
  group?: string,
) {
  return (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
    const original = descriptor.value;
    const transactionGroup = target.transactionGroup || group || 'NA';
    descriptor.value = async (...args: any[]) => {
      if (process.env.NEW_RELIC_ENABLED === 'false') {
        return original.call(target, ...args);
      }
      const result = await newrelic.startBackgroundTransaction(
        transactionName || propertyKey,
        transactionGroup,
        async () => {
          const transaction = newrelic.getTransaction();
          try {
            const output = await original.call(target, ...args);
            return output;
          } catch (error) {
            newrelic.noticeError(error as Error);
            return error;
          } finally {
            transaction.end();
          }
        },
      );

      if (result instanceof Error) {
        throw result;
      }

      return result;
    };
  };
}
```

### Minimum reproduction code

I will provide later

### Expected behavior

Method decorator should still working when use with NestJS decorator (Injectable)

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.7

### Packages versions

```json
 "@nestjs/common": "^8.4.7",
    "@nestjs/config": "^2.1.0",
    "@nestjs/core": "^8.4.7",
    "@nestjs/jwt": "^8.0.1",
    "@nestjs/passport": "^8.2.2",
```

### Node.js version

16.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
