### ISSUE TITLE
[Fastify-Adapter] Injecting @Res() results in timeout of endpoin

### ISSUE THREAD

**Issue by aviz** [nestjs/nest#9857]
Reference: https://github.com/nestjs/nest/issues/3128#issue-504182724

Any plan to fix this bug ? this is still happening with the newest nestjs and fastify

**Comment by Tony133** [comment]
Hi @aviz, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported. 

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by aviz** [comment]
> Reference

There is a git repo in the original issue. 
Original Issue: https://github.com/nestjs/nest/issues/3128#issue-504182724

Git: https://github.com/mschuttt/bug-nest-fastify-adapter


As soon as you add @Res() res  to method when using fastify, the reply hangs.

**Comment by micalevisk** [comment]
didn't manage to reproduce this. 

```ts
@Controller()
export class AppController {
  @Get()
  getHello(@Res() res) {
    res.send({ hello: 'world' })
  }
}
```
