### ISSUE TITLE
Generic Azure Function triggers

### ISSUE THREAD

**Issue by Luku1806** [nestjs/nest#9861]
### Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The package @nestjs/azure-func-http provides nice integration for Azure Function HTTP triggers.
This is not possible for any other azure function trigger.

### Describe the solution you'd like

I implemented a package similar to @nestjs/azure-func-http to be able to use any kind of azure function trigger.
This also provides a decorator that can provide the azure function context into the method.
This package I would like to contribute to the NestJs project.

The repository with the proposed solution can be found here: [https://github.com/Luku1806/nestjs-azure-func-trigger]( https://github.com/Luku1806/nestjs-azure-func-trigger)

The drawback with the proposed solution is that we have to use Azure specific decorators to be able to use generic triggers and contexts. That means different from @nestjs/azure-func-http, the service needs to "know" of Azure Functions and can not be Azure agnostic. For example migrating from an Azure Function Timed trigger to using @nestjs/schedule for scheduling would mean that we have to switch decorators instead of just starting the service in a new runtime. 

### Teachability, documentation, adoption, migration strategy

The solution works similar to @nestjs/azure-func-http.
Each function with its trigger bootstraps the app and then calls every service method that is annotated with the name of this Azure Function. 
The following will show the Azure Function and an example service.

The Azure Functions function.json:
```json
{
  "bindings": [
    {
      "name": "trigger",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 0,30 7-23 * * *"
    }
  ],
  "scriptFile": "../dist/FunctionName/index.js"
}
```  

The azure functions main.ts:  
```typescript
import { Context } from '@azure/functions';
import { AzureFunctionTriggerAdapter } from 'nestjs-azure-func-trigger';
import { createApp } from '../src/main';

export default async function(context: Context): Promise<void> {
  return AzureFunctionTriggerAdapter.handle(createApp, context);
}
```

The nest  service: 
```typescript
import { Injectable } from '@nestjs/common';

@Injectable()
class ClassWithTrigger {
  @AzureFunctionTrigger('FunctionName')
  public timerWithContext (
    test: string,
    @AzureFunctionContext() context: Context,
  ) {
    context.log('TimerWithContext');
  }
}
```

In this example the AzureFunction is called "FunctionName". The method "timerWithContext" is called because it is annotated with this name. Also the @AzureFunctionContext decorator provides the context to the function. This way we can use all bindings via the context to input and output data.

### What is the motivation / use case for changing the behavior?

The original motivation for this package was that I am using @nestjs/azure-func-http for a service hosted in Azure Functions.
This works perfectly fine. The problem occurred when I wanted to do something periodically. Here I need a way to trigger the service with an Azure Function trigger. Also I want the service to process Event Hub messages which can be accomplished with the proposed package.

**Comment by kamilmysliwiec** [comment]
Thanks for sharing your work with the community!
