### ISSUE TITLE
fastify-formbody has been deprecated

### ISSUE THREAD

**Issue by amanf244** [nestjs/nest#9863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[Nest Platform Information]
[19.24.20] Starting compilation in watch mode...

[19.24.36] Found 0 errors. Watching for file changes.

[Nest] 29903  - 02/07/2022 19.24.40     LOG [NestFactory] Starting Nest application...
[Nest] 29903  - 02/07/2022 19.24.41     LOG [InstanceLoader] AppModule dependencies initialized +195ms
[Nest] 29903  - 02/07/2022 19.24.41     LOG [RoutesResolver] AppController {/}: +82ms
[Nest] 29903  - 02/07/2022 19.24.41     LOG [RouterExplorer] Mapped {/, GET} route +10ms
[Nest] 29903  - 02/07/2022 19.24.41     LOG [NestApplication] Nest application successfully started +11ms
(node:29903) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)

### Minimum reproduction code

https://codesandbox.io/s/crazy-fire-xtotfo?file=/src/main.ts

### Expected behavior

warning disappear

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

{
  "name": "nest-fastify",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/platform-fastify": "^8.4.7",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

### Node.js version

16.5.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

[System Information]
OS Version     : Linux 5.10
NodeJS Version : v16.15.1
YARN Version    : 3.2.1 

[Nest CLI]
Nest CLI Version : 8.2.8 

[Nest Platform Information]
platform-express version : 8.4.7
platform-fastify version : 8.4.7
schematics version       : 8.0.11
testing version          : 8.4.7
common version           : 8.4.7
core version             : 8.4.7
cli version              : 8.2.8

**Comment by micalevisk** [comment]
duplicate
