### ISSUE TITLE
Fastify request object not fully available on a middleware

### ISSUE THREAD

**Issue by didd** [nestjs/nest#9865]
### Current behavior

I have the following code : 

```
... 
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply((req, res, next) => {
        console.log(req.routerPath)
        next()
      })
      ...
  }
...
```
The `routerPath` from https://www.fastify.io/docs/latest/Reference/Request/ is `undefined` on the above console log.

### Expected behavior

The `routerPath` should give the right router path.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
    "@nestjs/common": "^8.4.7",
    "@nestjs/config": "^2.0.0",
    "@nestjs/core": "^8.4.7",
    "@nestjs/platform-fastify": "^8.4.6",
```

### Node.js version

v16.8.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction).

[Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required).

**Comment by jmcdo29** [comment]
Also keep in mind that `req` in a fastify middleware is actually `req.raw` (the `IncomingMessage` object, not a `FastifyRequest` object) because of how [`middie`](https://github.com/fastify/middie) works. If you need access to the `FastifyRequest` object, you should use a guard or an interceptor

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
