### ISSUE TITLE
Allow access to global DI container for invoking custom shutdown hooks in parallel

### ISSUE THREAD

**Issue by maxh** [nestjs/nest#9866]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I asked two questions on StackOverflow with no results so am proposing a feature suggestion here that will help me accomplish my goal.

https://stackoverflow.com/questions/72773447/can-nestjs-lifecycle-methods-run-in-parallel-rather-than-in-sequence
https://stackoverflow.com/questions/72773524/is-there-an-easy-way-to-retrieve-all-subclass-instances-of-a-base-class-from-nes

It looks like at one point a few years ago there were code paths for getting access to the global DI container:

https://github.com/nestjs/nest/pull/283
https://github.com/nestjs/nest/issues/189

However, I'm struggling to get access to the global container now, and that is preventing from implementing the shutdown behavior I want.

### Describe the solution you'd like

My problem would be solved by exposing an `app.getContainer()` method on NestApplication that allows me to implement something like this:

```ts
const app: NestApplication;

// start the app, etc...

process.on('SIGTERM', async () => {
  const pollers = getAllPollers(app);
  // In parallel, shut down all pollers.
  await Promise.all(pollers.map((poller) => poller.stopPolling()));
  await app.close();
  process.exit(0);
});

function getAllPollers(app: NestApplication): BasePoller[] {
  const pollers: BasePoller[] = [];
  app.getContainer().getModules().forEach((module) => {
    module.providers.forEach((provider) => {
      if (provider instanceof BasePoller) {
        pollers.push(provider);
      }
    });
  });
  return pollers;
}
```

### Teachability, documentation, adoption, migration strategy

Perhaps this could be considered an extension of https://docs.nestjs.com/fundamentals/module-ref?

### What is the motivation / use case for changing the behavior?

During app shutdown (triggered by SIGTERM in our case), I want to call the async `stopPolling()` method on all instances of subclasses of `BasePoller`. I want all these async functions to all be invoked immediately and awaited collectively with `Promise.all` or perhaps some Bluebird concurrency. Currently we use the `onApplicationShutdown` hook to call `stopPolling()`, but this runs each method serially and it is starting to take too long as the system grows.

I am very open to suggestions of other ways this could be accomplished. It's possible I'm overlooking something simple. Thanks!

**Comment by kamilmysliwiec** [comment]
> During app shutdown (triggered by SIGTERM in our case), I want to call the async stopPolling() method on all instances of subclasses of BasePoller. I want all these async functions to all be invoked immediately and awaited collectively with Promise.all or perhaps some Bluebird concurrency. Currently we use the onApplicationShutdown hook to call stopPolling(), but this runs each method serially and it is starting to take too long as the system grows.

This is already feasible with the `DiscoveryService`. You can follow this example: https://github.com/nestjs/schedule/blob/master/lib/schedule.explorer.ts#L23

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
