### ISSUE TITLE
Optional dynamic modules

### ISSUE THREAD

**Issue by OoDeLally** [nestjs/nest#9868]
### Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I will take the example of a Module `Bike` which may or may not have an engine `Engine`. The environment (available from `ConfigService`) decides whether this `Bike` uses an `Engine` or not.

Let's first assume `Engine` to be a simple service.
NestJS already provides the way to conditionally provide an service `Engine`.
This can be done with a `useFactory` which returns either an instance of `Engine`, or `null`, according to the `ConfigService` that we injected in.
On the `Bike` side, we can decorate the injected `Engine` with `@Optional`, and let the `Bike` service check by itself whether an instance of `Engine` was injected.

This is a great feature, but it does not scale.

At some point, `Engine` is too big and complex to fit in a single service, and has to become a whole **module** with its own submodules and dependencies.

`useFactory` seems to be (to my knowledge) the only way to implement a "logic middleware" within the dependency solving. 

Unfortunately:
1. `useFactory` only works at the level of an individual provider, and not module.
2. `useFactory` is expected to return a ready-to-use value, and not a class that we would leave NestJS to instantiate.

#### Rejected solution

A common workaround on various stackoverflow topics is to use a ternary operator in the `import` array of the app module.
```ts
@Module({
  imports: [
    process.env.ENGINE ? EngineModule : null,
  ]
})
```
This solution is not satisfying, because it assumes that the predicate of whether we want the module is always available synchronously at declaration time. This is definitely too limiting. 
Ideally we want to provide the way to resolve that predicate asynchronously according to an injected service (such as `ConfigService`).

### Describe the solution you'd like

I have not yet delved much in the innards of Nest's core.
However from my limited knowledge I see no theoretical reason why this should not be possible.

The most convenient way for the end-user would be to allow NestJs `DynamicModule` as fully-fledged `Provider`.

Dependencies would be resolved against the existing modules, and the exported providers of the `Engine` would be added to the rest of the app's providers.

### Teachability, documentation, adoption, migration strategy

```ts
{
  inject: [engineModuleKey],
  useFactory: async ({ engineType }: EngineModuleOptions) => {
    if (engineType) {
      return EngineModule.forRoot(engineType); // DynamicModule returned as Provider
    } else {
      return null;
    }
  },
}
```

**Comment by micalevisk** [comment]
this was discussed in the past btw

Not sure if Kamil will change his mind on that

**Comment by micalevisk** [comment]
I didn't find it neither

**Comment by kamilmysliwiec** [comment]
> This solution is not satisfying, because it assumes that the predicate of whether we want the module is always available synchronously at declaration time. This is definitely too limiting.

You can use the `await ConfigModule.envVariablesLoaded` helper to ensure env variables are already loaded.

Example:

```typescript
export async function getStorageModule() {
  await ConfigModule.envVariablesLoaded;
  return process.env.STORAGE === 'S3' ? S3StorageModule : DefaultStorageModule;
}
```

and then:

```typescript
imports: [getStorageModule()]
```

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
