### ISSUE TITLE
Support for Deno?

### ISSUE THREAD

**Issue by ZahiriNatZuke** [nestjs/nest#9873]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

...

### Describe the solution you'd like

When creating a new project from the cli it could give the option to generate a new project with nodejs or deno

### Teachability, documentation, adoption, migration strategy

...

### What is the motivation / use case for changing the behavior?

...

**Comment by jmcdo29** [comment]
Please search through our previously closed issues. This has already been discussed
