### ISSUE TITLE
Validation of args passed to generic mutation in base resolver

### ISSUE THREAD

**Issue by snigdha920** [nestjs/nest#9874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- I have a base class and some derived classes
- There is a BaseResolver, which is inherited by the resolvers of the derived classes
- Inside the BaseResolver, there is a create mutation
- This create mutation takes in different arguments depending on the derived class
- I pass the DTO class of these arguments to the BaseResolver while inheriting it in the derived resolvers

Base resolver:
```
export function BaseResolver<
  T extends Type<BaseClass>,
  createClassDto extends Type<CreateBaseClassDto>,
>(classRef: T, createClassArgsDtoRef: createClassDto): any
```

Derived resolver: 

```
@Resolver((of) => DerivedXClass)
export class DerivedXResolver extends BaseResolver(
  DerivedXClass,
  CreateDerivedXDto,
) 
```

- I specify the type of the arguments as follows:

```
 async createMutation(
      @Args({ type: () => createClassArgsDtoRef })
      args: Type<CreateBaseClassDto>,
    )
```

- The arguments are not being validated at all

### Minimum reproduction code

https://github.com/snigdha920/nestjs-validation-args

### Steps to reproduce

Written in the minimal reproduction code. 

### Expected behavior

While calling the create mutation for the particular derived class, I want the arguments to be validated as specified in the derived class's DTO. 

Eg. 
1. While calling `createDerivedXClass` I want the arguments to be validated as specified in the `CreateDerivedXDto`. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.8

### Packages versions

```json
 "dependencies": {
    "@nestjs/apollo": "^10.0.16",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^10.0.16",
    "@nestjs/platform-express": "^8.0.0",
    "apollo-server-express": "^3.9.0",
    "class-transformer": "0.5.1",
    "class-validator": "0.13.2",
    "graphql": "^16.5.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },

```

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
> `args: Type<CreateBaseClassDto>,`

This is the problem, you can't have a generic here, Typescript won't reflect it for Nest to read properly to send it on to the pipe. It's a limitation of Typescript's reflection system, not of Nest. You probably don't mean to use `Type<T>` here anyways, as you're expecting to get an instance of the class instead of the class reference. 

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by snigdha920** [comment]
> > `args: Type<CreateBaseClassDto>,`
> 
> This is the problem, you can't have a generic here, Typescript won't reflect it for Nest to read properly to send it on to the pipe. It's a limitation of Typescript's reflection system, not of Nest. You probably don't mean to use `Type<T>` here anyways, as you're expecting to get an instance of the class instead of the class reference.
> 
> Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

Thank you for your quick response. 

Do you have a suggestion for what I can use there instead of the generic type? When I do something like:

```
args: typeof createClassArgsDtoRef
```

It still fails to validate. 

I've asked the question in discord as well [here](https://discord.com/channels/520622812742811698/520649487924985885/994474987379499098), thanks for your help.

**Comment by snigdha920** [comment]
> > > `args: Type<CreateBaseClassDto>,`
> > 
> > 
> > This is the problem, you can't have a generic here, Typescript won't reflect it for Nest to read properly to send it on to the pipe. It's a limitation of Typescript's reflection system, not of Nest. You probably don't mean to use `Type<T>` here anyways, as you're expecting to get an instance of the class instead of the class reference.
> > Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
> 
> Thank you for your quick response.
> 
> Do you have a suggestion for what I can use there instead of the generic type? When I do something like:
> 
> ```
> args: typeof createClassArgsDtoRef
> ```
> 
> It still fails to validate.
> 
> I've asked the question in discord as well [here](https://discord.com/channels/520622812742811698/520649487924985885/994474987379499098), thanks for your help.

Resolved with 

```
async createMutation(
      @Args({ type: () => createClassArgsDtoRef })
      args: // @ts-ignore
      createClassArgsDtoRef,
    )
```
