### ISSUE TITLE
bufferLogs and autoFlushLogs not working when use NestFactory.create

### ISSUE THREAD

**Issue by phoenix741** [nestjs/nest#9880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

In version 8.4.4 of nestjs log aren't automatically flushed when working in a serverless context.

The code that active `autoFlushLogs` is only called on the method `createApplicationContext`

```ts
        if (this.autoFlushLogs) {
            context.flushLogsOnOverride();
        }
```

The method `createMicroservice` and `create` don't call this methods, so the logs are never flushed even if we call with autoFlushLogs: true

When calling flushLogs manually, it's working :

```ts
  const app = await NestFactory.create(AppModule, { bufferLogs: true });
  app.useLogger(app.get(MyLogger));
  app.flushLogs();

  await  app.init()

  const expressApp = app.getHttpAdapter().getInstance();
  return serverlessExpress({ app: expressApp });
```

Thanks

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-vcexx9?file=tsconfig.json

### Steps to reproduce

1. set bufferLogs = false
2. log start in nest format and next with logger
3. set bufferLogs = true
4. we don't have log

### Expected behavior

The autoflushLogs should work in all context

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.4

### Packages versions

```json
 "@nestjs/common": "^8.4.4",
    "@nestjs/core": "^8.4.4",
```

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
If you use a non-standard approach (serverless express) that doesn't call the `listen()` method, you have to manually flush logs so this is the expected behavior.
