### ISSUE TITLE
Platform Fastify incompatible version Fastify v4.x with @fastify/static v5.x

### ISSUE THREAD

**Issue by SirReiva** [nestjs/nest#9891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/50754871/177955982-c5f1196f-132a-4f82-9928-776415a144bb.png)

### Minimum reproduction code

none

### Steps to reproduce

Create an nest app with fastify adapter an use useStaticAssets

### Expected behavior

Error starting run application

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
"@nestjs/platform-fastify": "9.0.0",
```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in v9.0.1. Make sure to update all `@nestjs` and `@fastify` packages to the latest version.
