### ISSUE TITLE
Unable to connect to EventHub Kafka Surface with @nestjs/microservices

### ISSUE THREAD

**Issue by mrsauravsahu** [nestjs/nest#9892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying to connect to Kafka surface on EventHub fails only on Nestjs.

```
[Nest] 82042  - 08/07/2022, 14:25:00     LOG [ServerKafka] INFO [Consumer] Starting {"timestamp":"2022-07-08T08:55:00.944Z","logger":"kafkajs","groupId":"nestjs-group-server"}
[Nest] 82042  - 08/07/2022, 14:25:40   ERROR [ServerKafka] ERROR [Connection] Response SyncGroup(key: 14, version: 1) {"timestamp":"2022-07-08T08:55:40.620Z","logger":"kafkajs","broker":"kafka-repro1.servicebus.windows.net:9093","clientId":"kafka-sample-id-server","error":"The group is rebalancing, so a rejoin is needed","correlationId":35,"size":14}
[Nest] 82042  - 08/07/2022, 14:25:41   ERROR [ServerKafka] ERROR [Connection] Response SyncGroup(key: 14, version: 1) {"timestamp":"2022-07-08T08:55:41.208Z","logger":"kafkajs","broker":"kafka-repro1.servicebus.windows.net:9093","clientId":"kafka-sample-id-server","error":"The group is rebalancing, so a rejoin is needed","correlationId":39,"size":14}
```

The same configuration works fine with kafkajs - producer connects to Kafka Surface on eventhub, emits the message and consumer is able to consume it.

### Minimum reproduction code

https://github.com/mrsauravsahu/repro-kafka-event-hub-connection/tree/main/producer-nestjs

### Steps to reproduce

- create an eventhub on Azure
- update the template.envrc and add it to env
- run the app with npm start

### Expected behavior

The producer should be able to connect to Kafka Surface on event hub, emit messages.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

^8.4.7

### Packages versions

```json
    "@nestjs/microservices": "^8.4.7",
    "@nestjs/platform-express": "^8.4.7",
    "@nestjs/schedule": "^2.0.1",
    "kafkajs": "^1.15.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
```

### Node.js version

18.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

```bash
$ node -v  
v18.4.0
$ npm -v   
8.13.2
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
