### ISSUE TITLE
[9.x.x] Duplicate Provider names don't get shown in REPL-debug() function 

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#9893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Given the following Diagram:

```mermaid
graph TD;
  AppModule((AppModule))-->CatModule((CatModule))
  AppModule-->AppService_A>AppService]
  AppModule-->foo_A>provide: 'Foo', useValue: 'bar']

  CatModule-->AppService_B>AppService]
  CatModule-->foo_B>provide: 'Foo', useValue: 'barbaz']
  CatModule-->CatService>CatService]
```

Both the `AppModule` and `CatModule` have providers with the same name but **different implementations/instances**. 
When using the NestJS `repl()` method and print a `debug()` statement in order to list the application context, the `AppService` &  `Foo` provider does not get listed within the `CatModule`.

```
[Nest] 5340  - 07/08/2022, 11:18:42 AM     LOG [NestFactory] Starting Nest application...
[Nest] 5340  - 07/08/2022, 11:18:42 AM     LOG [InstanceLoader] CatModule dependencies initialized
[Nest] 5340  - 07/08/2022, 11:18:42 AM     LOG [InstanceLoader] AppModule dependencies initialized
[Nest] 5340  - 07/08/2022, 11:18:42 AM     LOG REPL initialized
> debug()

AppModule:
 - controllers:
  ◻ AppController
 - providers:
  ◻ AppService
  ◻ Foo
CatModule:
 - providers:
  ◻ CatService
```

### Minimum reproduction code

https://github.com/BrunnerLivio/nestjs-repro-duplicate-provider-repl

### Steps to reproduce

1. npm ci
2. npm run start:dev
3. Write `debug()` within REPL console

### Expected behavior

Should list all providers 

```diff
[Nest] 5340  - 07/08/2022, 11:18:42 AM     LOG [NestFactory] Starting Nest application...
[Nest] 5340  - 07/08/2022, 11:18:42 AM     LOG [InstanceLoader] CatModule dependencies initialized
[Nest] 5340  - 07/08/2022, 11:18:42 AM     LOG [InstanceLoader] AppModule dependencies initialized
[Nest] 5340  - 07/08/2022, 11:18:42 AM     LOG REPL initialized
$ debug()

AppModule:
 - controllers:
  ◻ AppController
 - providers:
  ◻ AppService
  ◻ Foo
CatModule:
 - providers:
  ◻ CatService
+ ◻ AppService
+ ◻ Foo
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
platform-express version : 9.0.0
schematics version       : 9.0.1
testing version          : 9.0.0
common version           : 9.0.0
core version             : 9.0.0
cli version              : 9.0.0
```

### Node.js version

16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I was expecting a lot of edge cases for the REPL tbh

I'll investigate this issue tomorrow

**Comment by kamilmysliwiec** [comment]
Should be easy to fix, luckily. Thank you @BrunnerLivio!

**Comment by kamilmysliwiec** [comment]
> Maybe we should consider a REPL command like this:

This is already feasible with `select` (instead of `module()`)

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec Yeah i saw that -- though even with `select(CatModule).get(AppService)` it will select the `AppService` of `AppModule` - not the one from `CatModule`. 

_Technically_ it's possible to get to the actual `AppService` of `CatModule` like this:

```
> const AppService_Cat = await import('./dist/cat/app.service.js').then(m => m.AppService)
> methods(AppService_Cat)
Methods:
 ◻ getDog

> select(CatModule).get(AppService_Cat).getDog()
'Bob'
```

**Comment by micalevisk** [comment]
another thing on this issue:

![image](https://user-images.githubusercontent.com/13461315/178123132-42fcbe3b-1c7b-4d91-960c-c3ddeb8a252c.png)

it is always selecting the provider registered on `CatModule`, not from `AppModule`

![image](https://user-images.githubusercontent.com/13461315/178123178-da290f59-ad78-4c11-9f92-ee8a6ad4129d.png)
![image](https://user-images.githubusercontent.com/13461315/178123185-e1655fdb-71c8-4c6b-b2fa-cc0c92825bd1.png)

**Comment by BrunnerLivio** [comment]
@micalevisk what Module is in your example being loaded via `await repl(…)`?

**Comment by micalevisk** [comment]
I'm using your repro

**Comment by micalevisk** [comment]
if we drop the `this.globalScope[stringifiedToken]` below and change that `configurable` to `true`, `debug()` will display the desired output

https://github.com/nestjs/nest/blob/34cb6001c30b3e2d2a9570bc87c6bd78a8c49524/packages/core/repl/repl-context.ts#L81-L87
https://github.com/nestjs/nest/blob/34cb6001c30b3e2d2a9570bc87c6bd78a8c49524/packages/core/repl/repl-context.ts#L91

but that didn't solve this another issue:

```
> $('Foo')
barbaz
```
it should display `Bar` as we called `repl(AppModule)`

**Comment by micalevisk** [comment]
@BrunnerLivio 
> though even with `select(CatModule).get(AppService)` it will select the `AppService` of `AppModule` - not the one from CatModule.

we need to supply `{ strict: true }` to the `get()` otherwise the root module will be used.

I thought this was the default behavior but looks like it's not:

<details>
<summary><code> </code></summary>

```ts
import { Module, Injectable, Controller, Get, Query } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

@Injectable()
class FooService {}

@Module({
  providers: [{ provide: 'qux', useValue: 'bar' }, { provide: FooService, useValue: 'bar-service' }]
})
export class BarModule {}

@Module({
  imports: [BarModule],
  providers: [FooService, { provide: 'qux', useValue: 'foo' }],
})
export class FooModule {}

async function bootstrap() {
  const app = await NestFactory.create(FooModule)
  await app.init()

  const ctxFooModule = app.select(FooModule)
  const ctxBarModule = app.select(BarModule)

  console.log(
    ctxFooModule.get('qux') // 'bar'
    ,
    ctxFooModule.get('qux', { strict: true }) // 'foo'
    ,
    ctxFooModule.get('qux') == ctxBarModule.get('qux') // true
    ,
    ctxFooModule.get('qux',{strict:true}) == ctxBarModule.get('qux',{strict:true}) // false
  )
}

bootstrap();
```

</details>

**Comment by micalevisk** [comment]
due to the above described behavior, `$(duplicatedToken)` ends up returning the wrong provider like so:

![image](https://user-images.githubusercontent.com/13461315/182028338-fe3fcc58-a60f-4ac1-837a-bdb8f79f8e22.png)

but if we use `strict: true` below, we got a _Nest could not find x element_ error

https://github.com/nestjs/nest/blob/81df0dde0881b0680808798565bc88a0e65dc2ed/packages/core/repl/native-functions/get-relp-fn.ts#L14-L15

**Comment by ologbonowiwi** [comment]
Guys, what's the solution for this issue?

**Comment by micalevisk** [comment]
@ologbonowiwi another bug that I believe isn't directly related to this issue is that: when we have a provider with the same token registered in multiple modules, the latest registered one is always selected when calling `get(token)` even if we call like this:  
`select(AppModule).get(token)`  
an workaround to that is `select(AppModule).get(token, {strict:true})`

**Comment by kamilmysliwiec** [comment]
@micalevisk that's how `NestApplicationContext` instance behaves by default (this isn't a bug)
