### ISSUE TITLE
Platform Fastify incompatible version Fastify v4.x with @fastify/accepts

### ISSUE THREAD

**Issue by gdsrmygdsrjr** [nestjs/nest#9894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/10488154/178032286-3a70ba55-62b0-4937-88ca-a4cd87ed24a2.png)
![image](https://user-images.githubusercontent.com/10488154/178032159-a538b6b6-dd5f-4af7-8911-55d1b7932cf7.png)

### Minimum reproduction code

None

### Steps to reproduce

None

### Expected behavior

Error

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.1

### Packages versions

```json
"@nestjs/platform-fastify": "^9.0.1",
"apollo-server-fastify": "^3.9.0"
```

### Node.js version

18.4.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
![image](https://user-images.githubusercontent.com/28268680/178033479-1490c42c-3d8e-48cb-bf26-c49cba70df86.png)

This is because `apollo-server-fastify` is not compatible with fastify 4.
