### ISSUE TITLE
NEST V9 REPL does not load all configuration on main.ts

### ISSUE THREAD

**Issue by Avivbens** [nestjs/nest#9897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When loading the application with the script
```
        "start:dev:repl": "npm run start:dev -- --entryFile repl",

```
All main.ts configuration includes Swagger and API prefix does not load. 
Also, no mapped routes as shown in the image. 

### Minimum reproduction code

https://github.com/Avivbens/test-nestjs-repl.git

### Steps to reproduce

1. npm ci
2. npm run start:dev
3. goto localhost:3000/api
4. swagger exists
5. ---------------
6. npm run start:dev:repl
7. goto localhost:3000/api
8. swagger does not show up

### Expected behavior

Fully functional application with the option of using the REPL feature, without duplicate main.ts logic and configuration. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json
{
    "name": "test-nest-repl",
    "version": "0.0.1",
    "description": "",
    "author": "",
    "private": true,
    "license": "UNLICENSED",
    "scripts": {
        "prebuild": "rimraf dist",
        "build": "nest build",
        "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
        "start": "nest start",
        "start:dev": "nest start --watch --preserveWatchOutput",
        "start:dev:repl": "npm run start:dev -- --entryFile repl",
        "start:debug": "nest start --debug --watch",
        "start:prod": "node dist/main",
        "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
        "test": "jest",
        "test:watch": "jest --watch",
        "test:cov": "jest --coverage",
        "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
        "test:e2e": "jest --config ./test/jest-e2e.json"
    },
    "dependencies": {
        "@nestjs/common": "^9.0.0",
        "@nestjs/core": "^9.0.0",
        "@nestjs/platform-express": "^9.0.0",
        "reflect-metadata": "^0.1.13",
        "rimraf": "^3.0.2",
        "rxjs": "^7.2.0",
        "@nestjs/swagger": "^6.0.1",
        "swagger-ui-express": "^4.4.0"
    },
    "devDependencies": {
        "@nestjs/cli": "^9.0.0",
        "@nestjs/schematics": "^9.0.0",
        "@nestjs/testing": "^9.0.0",
        "@types/express": "^4.17.13",
        "@types/jest": "28.1.4",
        "@types/node": "^16.0.0",
        "@types/supertest": "^2.0.11",
        "@typescript-eslint/eslint-plugin": "^5.0.0",
        "@typescript-eslint/parser": "^5.0.0",
        "eslint": "^8.0.1",
        "eslint-config-prettier": "^8.3.0",
        "eslint-plugin-prettier": "^4.0.0",
        "jest": "28.1.2",
        "prettier": "^2.3.2",
        "source-map-support": "^0.5.20",
        "supertest": "^6.1.3",
        "ts-jest": "28.0.5",
        "ts-loader": "^9.2.3",
        "ts-node": "^10.0.0",
        "tsconfig-paths": "4.0.0",
        "typescript": "^4.3.5"
    },
    "jest": {
        "moduleFileExtensions": [
            "js",
            "json",
            "ts"
        ],
        "rootDir": "src",
        "testRegex": ".*\\.spec\\.ts$",
        "transform": {
            "^.+\\.(t|j)s$": "ts-jest"
        },
        "collectCoverageFrom": [
            "**/*.(t|j)s"
        ],
        "coverageDirectory": "../coverage",
        "testEnvironment": "node"
    }
}
```

### Node.js version

16.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

<img width="1112" alt="Screen Shot 2022-07-09 at 16 07 48" src="https://user-images.githubusercontent.com/77183871/178107111-66ca0fe8-ad8f-46c7-abf1-b558f1754008.png">

**Comment by micalevisk** [comment]
when you call just `repl(AppModule)` there's no place to initialize the app, it is just the REPL. Thus `localhost:3000` doesn't even exists when running `npm run start:dev:repl`

**Comment by Avivbens** [comment]
I've expected to have the full application up, and the REPL on top of that
Like event to import bootstrap function to initial the app

**Comment by micalevisk** [comment]
maybe you can clarify that behavior on the docs page here: https://github.com/nestjs/docs.nestjs.com/blob/master/content/recipes/repl.md

**Comment by Avivbens** [comment]
I see the primary goal of it, but yet - will be nice to have a fully functional application with the REPL feature.
