### ISSUE TITLE
[9.x]: use @fastify/view@7.0.0 instead of point-of-view@5

### ISSUE THREAD

**Issue by liaoliaots** [nestjs/nest#9899]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

^9.0.0

### Describe the regression

**peer dependency** `point-of-view` has been deprecated, `@fastify/view@7.0.0` should be used.
Otherwise, when using `pnpm`, peer dependencies conflicts will block installations.

### Input code

```ts

```

### Expected behavior

add `@fastify/view@7.0.0` to peer dependencies to replace `point-of-view`

**Comment by Tony133** [comment]
view this PR: https://github.com/nestjs/nest/pull/9898

**Comment by kamilmysliwiec** [comment]
Fixed in 9.0.2
