### ISSUE TITLE
raw body option usage issue

### ISSUE THREAD

**Issue by obh** [nestjs/nest#9901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying this doc to access the raw body for a request - https://docs.nestjs.com/faq/raw-body

But this only works for json requests and not form-encoded. This should be made clear in the docs. 
The solution that i found was to just do this for form-encoded payload. 

```
const rawBodyBuffer = (req, res, buf, encoding) => {
          if (buf && buf.length) {
               req.rawBody = buf.toString(encoding || 'utf8');
           }
};
app.use(bodyParser.urlencoded({verify: rawBodyBuffer, extended: true }));
```

### Minimum reproduction code

https://github.com/obh/nest-test

### Expected behavior

ideally you accept both json and form-encoded requests to work in the same way. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
@tolgap could you look into that? 🙌

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/9926
