### ISSUE TITLE
"@fastify/static" package is missing

### ISSUE THREAD

**Issue by goriunov** [nestjs/nest#9905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After upgrade to the 9.0.1 with fastify module and @nestjs/swagger the below error is present, the solution is pretty simple to install @fastify/static but I believe it should be done as part of the "@nestjs/swagger" or "@nestjs/platform-fastify"

```
[Nest] 72813  - 11/07/2022, 11:23:21     LOG [NestFactory] Starting Nest application...
[Nest] 72813  - 11/07/2022, 11:23:21     LOG [InstanceLoader] Main dependencies initialized +35ms
[Nest] 72813  - 11/07/2022, 11:23:21   ERROR [PackageLoader] The "@fastify/static" package is missing. Please, make sure to install this library ($ npm install @fastify/static) to take advantage of FastifyAdapter.useStaticAssets().
```

### Minimum reproduction code

In the steps to reproduce

### Steps to reproduce

My current node modules structure:

```json
{
  "name": "proto-test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "tsc",
    "start": "ts-node ./src/start.ts"
  },
  "dependencies": {
    "@nestjs/class-transformer": "^0.4.0",
    "@nestjs/class-validator": "^0.13.4",
    "@nestjs/common": "^9.0.1",
    "@nestjs/core": "^9.0.1",
    "@nestjs/microservices": "^9.0.1",
    "@nestjs/platform-fastify": "^9.0.1",
    "@nestjs/swagger": "^6.0.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@nestjs/testing": "^9.0.1",
    "@types/node": "^16.11.43",
    "ts-node": "^10.8.2",
    "typescript": "^4.7.4"
  }
}
```

Server code:
```ts
@Module({
  imports: [],
  controllers: [],
  providers: [],
})
export class Main { }

const bootstrap = async () => {
  const app = await NestFactory.create(Main, new FastifyAdapter());
  SwaggerModule.setup('api', app, SwaggerModule.createDocument(app, new DocumentBuilder().build()));
  await app.listen(3000);
 }

```

### Expected behavior

isntall @fastify/static directly during the  @nestjs/platform-fastify or @nestjs/swagger installation... 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

9.0.1

### Packages versions

```json
{
  "name": "proto-test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "tsc",
    "start": "ts-node ./src/start.ts"
  },
  "dependencies": {
    "@nestjs/class-transformer": "^0.4.0",
    "@nestjs/class-validator": "^0.13.4",
    "@nestjs/common": "^9.0.1",
    "@nestjs/core": "^9.0.1",
    "@nestjs/microservices": "^9.0.1",
    "@nestjs/platform-fastify": "^9.0.1",
    "@nestjs/swagger": "^6.0.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@nestjs/testing": "^9.0.1",
    "@types/node": "^16.11.43",
    "ts-node": "^10.8.2",
    "typescript": "^4.7.4"
  }
}
```

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
> it should be done as part of the "@nestjs/swagger" or "@nestjs/platform-fastify"

`@fastify/static` is a optional peer dependency of `@nestjs/swagger`, meaning that you need to install it in your project if you want to. Moving this installation step to `@nestjs/swagger` doesn't make sense as that package isn't mandatory for those using the default HTTP platform (`express`)

**Comment by olawalejuwonm** [comment]
does that mean @fastify/static needs to be installed?

**Comment by micalevisk** [comment]
[![image](https://github.com/nestjs/nest/assets/13461315/f7106f75-1b95-4fe6-add9-773efefad686)](https://github.com/nestjs/nest/issues/9905#issuecomment-1179838904)

**Comment by dushmanta05** [comment]
Worked after installing @fastify/static, also make sure to install the version which is compatible with @nestjs/platform-fastify to avoid peer dependency warnings.
