### ISSUE TITLE
`nest start` ignores exclude folders from tsconfig

### ISSUE THREAD

**Issue by Shassk** [nestjs/nest#9925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`nest start` tries to compile files it shouldn't - including *.d.ts definitions from `node_modules`. As the result trying to run nest with `nest start` results in over 1'000 errors while tsc compiles w/o any errors. The issue remains with any nest project on my machine, even a new one created using nest cli tool.

### Minimum reproduction code

https://github.com/Shassk/test-nest-app

### Steps to reproduce

1. Take a nest app (in case of this example I've used a new one created with `node path-to-nest\nest.js -- n test-nest-app`)
2. `yarn install`
3. `yarn start`

### Expected behavior

`nest start` follows tsconfig rules and excludes `node_modules` from compiling.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [X] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.0

### Packages versions

````
{
  // . . .
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

The issue persisted on 8.4.6 as well.

Also unlikely, but still possibly related: I have my projects on an exFAT MicroSD (E:\) with a symlink in `C:\...\Documents` pointing at the projects folder on E:\. Although I've tried to run `nest start` from both the actual location and the symlink path - the result doesn't change. So I doubt that's the reason.

**Comment by micalevisk** [comment]
got no errors here (Ubuntu)

![image](https://user-images.githubusercontent.com/13461315/178624001-503fbb50-e7a1-4481-a768-f38e8b0ec8f4.png)

**Comment by Shassk** [comment]
Well that's what I see:
![image](https://user-images.githubusercontent.com/62873560/178625742-79134d14-6697-4b0c-ab4b-e74ab7950402.png)

**Comment by Shassk** [comment]
Damn, pressed the wrong button

**Comment by micalevisk** [comment]
I didn't manage to reproduce that. Could you please run the following commands:

```bash
git clone --depth=1 git@github.com:Shassk/test-nest-app.git foo
cd foo
yarn install
yarn start
```

**Comment by Shassk** [comment]
The `git@github.com:Shassk` part didn't want to work, so I'll use `https://github.com/Shassk` instead. Hope that won't be a problem? Install will take some time, my internet isn't particularly fast.

**Comment by Shassk** [comment]
That's... confusing to say the least.
![image](https://user-images.githubusercontent.com/62873560/178629362-a7de7a01-b3ca-4640-bc2b-e9ebdcddde03.png)

Guess now I have to re-clone out working project and try again.

**Comment by Shassk** [comment]
Didn't help with the working project unfortunately. Still over 1k errors after removing and new clone like you said to do before. And that's already with `skipLibCheck: true`.

**Comment by jmcdo29** [comment]
Does `tsc -p tsconfig.build.json` produce the same errors for you?

**Comment by Shassk** [comment]
No, it succeeds

**Comment by jmcdo29** [comment]
Weird, cause that's all that should be getting called. Without a proper reproduction I'm not sure what we'll be able to do though. `nest start` essentially just calls to `tsc -p tsconfig.build.json && node dist/main` if the `dist` does not exist or `node dist/main` if the `dist` does exist

**Comment by Shassk** [comment]
Does this mean it shouldn't try to recompile after a manual `tsc` call like I did just now?

**Comment by jmcdo29** [comment]
Nope, turns out we changed that at some point and I missed it. It'll run the compiler either way

**Comment by Shassk** [comment]
OK. So I've tried to clone working repo to a different drive (C:\) - and it seems that's symlinks and exFAT are the main culprits rn. Because from C:\ it started flawlessly. Any way for me to get more information about this? Maybe add some additional console logs somewhere to `node_nodules/@nest`?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
