### ISSUE TITLE
req.session is undefined in middleware when change express to fastify

### ISSUE THREAD

**Issue by zreo0** [nestjs/nest#9927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i use `@nestjs/platform-fastify`, req.session is undefined in `Middleware`, but worked well in `Controller`. 
`@nestjs/platform-express` do not have this problem, how can i get session info in `Middleware`?
Here is a simple repo.

### Minimum reproduction code

https://github.com/zreo0/fastify-session-demo

### Steps to reproduce

1. `npm i`
2. `npm run start:dev`
3. go localhost:3000/setSession to set session.count
4. go localhost:3000/getSession, see log in terminal, session.count in Middleware is undefined, but exist in Controller

### Expected behavior

req.session has corrent value in middlerware.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.3

### Packages versions

```
[System Information]
OS Version     : macOS Catalina
NodeJS Version : v16.13.1
NPM Version    : 8.1.2

[Nest CLI]
Nest CLI Version : 9.0.0

[Nest Platform Information]
platform-fastify version : 9.0.3
schematics version       : 9.0.1
testing version          : 9.0.3
common version           : 9.0.3
core version             : 9.0.3
cli version              : 9.0.0
```

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Due to the way `middie` works (the express to fastify middleware library) the `req` passed to fastify middleware is actually `req.raw` (`IncomingMessage`) and not `FastifyRequest` (where `@fastify/secure-session` attaches `req.session`). Is there a reason to use a middleware here instead of a guard or interceptor where `context.switchToHttp().getRequest()` will return the `FastifyRequest`?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
