### ISSUE TITLE
Jest v28 error with Nestjs/common uuid dependency

### ISSUE THREAD

**Issue by MarcusElevait** [nestjs/nest#9930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running a jest test in our NestJs application we get the jest error:
`
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /node_modules/@nestjs/common/node_modules/uuid/dist/esm-browser/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { default as v1 } from './v1.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/@jest/core/node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (../../node_modules/@nestjs/common/decorators/core/injectable.decorator.js:4:16)
`

Seems like this is coming from the uuid dependency, that is used within nestjs/common. This library is two years old and i guess this is and will not be compatible with the newest jest version.

Is there a workaround for this?

### Minimum reproduction code

there is no reproduction code

### Steps to reproduce

Create a simple nestjs app with the given dependencies and run a simple jest test.

### Expected behavior

I expect the tests to run without an error

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

jest v28.1.3

### NestJS version

9.0.3

### Packages versions

```json

```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction).

[Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required).

`npm run test` works in a fresh new nestjs v9 app (which uses jest v28)

**Comment by mcmxcdev** [comment]
We ran into this issue as well a while ago. We solved it by adding this to the jest configuration file:

```
moduleNameMapper: {
  '^uuid$': require.resolve('uuid'),
},
```
