### ISSUE TITLE
Type error when using useFactory for ConfigurableModuleClass.registerAsync

### ISSUE THREAD

**Issue by demaisj** [nestjs/nest#9933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using a factory in the registerAsync method generated by the ConfigurableModuleBuilder helper, typescript complains in strict mode that the injected parameter types can't be assigned.

Example usage:
We want to inject the configService inside the factory.
```typescript
TestModule.registerAsync({
  imports: [ConfigModule]   
  useFactory: (config: ConfigService /* ← error here */) => ({     
    someValue: config.get('SOME_VALUE'),
  }),
  inject: [ConfigService],
}),
```
The error reported by the typescript compiler:
```
src/app.module.ts:10:7 - error TS2322: Type '(config: ConfigService) => { someValue: string; }' is not assignable to type '(...args: unknown[]) => TestModuleOptions | Promise<TestModuleOptions>'.
  Types of parameters 'config' and 'args' are incompatible.
    Type '{}' is missing the following properties from type 'ConfigService<Record<string, unknown>, false>': internalConfig, isCacheEnabled, cache, _isCacheEnabled, and 8 more.

10       useFactory: (config: ConfigService) => ({
         ~~~~~~~~~~

  node_modules/@nestjs/common/module-utils/interfaces/configurable-module-async-options.interface.d.ts:31:5
    31     useFactory?: (...args: unknown[]) => Promise<ModuleOptions> | ModuleOptions;
           ~~~~~~~~~~
    The expected type comes from property 'useFactory' which is declared here on type 'ConfigurableModuleAsyncOptions<TestModuleOptions, "create">'
```

### Minimum reproduction code

https://github.com/demaisj/nestjs-configurablemodule-usefactory-issuerepro

### Steps to reproduce

1) npm install
2) npm run build
3) see the error

### Expected behavior

It should be possible to specify the types of the injected values.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.3

### Packages versions

```json
{
  "dependencies": {
    "@nestjs/common": "^9.0.3",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.3",
    "@nestjs/platform-express": "^9.0.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.6"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.1",
    "@nestjs/testing": "^9.0.3",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.5",
    "@types/node": "^18.0.4",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.6",
    "@typescript-eslint/parser": "^5.30.6",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "28.1.3",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "28.0.6",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.7.4"
  },
}

```

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Current workaround to replace the type of the injected value by any.

**Comment by kamilmysliwiec** [comment]
Fixed in 9.0.4
