### ISSUE TITLE
Support bun.sh

### ISSUE THREAD

**Issue by philosofonusus** [nestjs/nest#9945]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

My production application requires high load of user requests and sometimes it doesn’t work well

### Describe the solution you'd like

I would like nest to add support of bun.sh to make my application a lot more performant, even if it is in beta for now

### Teachability, documentation, adoption, migration strategy

Initialise project with `—bun` prefix, if user want to migrate `nest migrate bun`

### What is the motivation / use case for changing the behavior?

Significantly increase performance of an application

**Comment by micalevisk** [comment]
duplicate #9934

**Comment by kamilmysliwiec** [comment]
It's fun how Bun was announced literally a few days ago and suddenly everyone wants to migrate 😅 Give it **at least** a few months and let's see what happens by then.
