### ISSUE TITLE
Microservice client send message need to call subscribe()

### ISSUE THREAD

**Issue by HedgeHao** [nestjs/nest#9946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I follow the [tutorial](https://docs.nestjs.com/microservices/rabbitmq) for microservice (Hybrid) and RabbitMQ. I setup all the connection, messagePattern etc. I can see the connection and queue in the RabbitMQ admin page. But when I use client to send message to rabbitmq microservice as describe [here](https://docs.nestjs.com/microservices/basics#sending-messages). It does not work. I have to call the subscribe() then it send the message and the consumer works. Is that a bug or I did something wrong?

```typescript
@Controller()
export class TestController {
  constructor(
    @Inject(Config.rabbitmqClientName) private rabbitMQ: ClientProxy,
  ) {}

  @MessagePattern('MSG')
  consumer(@Payload() data: string, @Ctx() context: RmqContext) {
    console.log(`Consume: ${data}`);
    const channel = context.getChannelRef();
    const msg = context.getMessage();

    channel.ack(msg);
  }

  @Post('test')
  postTest(@Body() body: TestBody) {
   // this.rabbitMQ.send('MSG', body.name);   // not work
    this.rabbitMQ.send('MSG', body.name).subscribe();

    return { code: 200, msg: `Hello ${body.name}` };
  }
}

```

### Minimum reproduction code

https://gist.github.com/HedgeHao/8407cfcb065626016b264241968c38dd#file-nestjs-microservice

### Expected behavior

The code on the tutorial works.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.4

### Packages versions

```json
{
  "name": "Test",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "9.0.4",
    "@nestjs/core": "9.0.4",
    "@nestjs/microservices": "9.0.4",
    "@nestjs/platform-express": "9.0.4",
    "amqp-connection-manager": "^4.1.3",
    "amqplib": "^0.10.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "9.0.0",
    "@nestjs/schematics": "9.0.1",
    "@nestjs/testing": "9.0.4",
    "@types/express": "^4.17.13",
    "@types/jest": "27.5.0",
    "@types/multer": "^1.4.7",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.0.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.1",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
This is how RxJS works. [IF you notice in our `sending messages` parts of the docs](https://docs.nestjs.com/microservices/basics#sending-messages) we return the observable, which Nest will then subscribe to and handle under the hood. You can also use `lastValueFrom` to `await` the call if that's your preference. 

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
