### ISSUE TITLE
Update external/kafka.interface.ts to match types from kafkajs@2

### ISSUE THREAD

**Issue by tiagosiebler** [nestjs/nest#9947]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I've been testing kafkajs@latest with our nestjs project (8x but upgrading to 9x soon). It seems some of the interfaces from external/kafka.interface.ts are copies from those in kafkajs:
https://github.com/nestjs/nest/blob/master/packages/microservices/external/kafka.interface.ts#L869-L873

@nestjs/microservices also doesn't specify a specific kafkajs version, this is purely a build-time type conflict:
https://github.com/nestjs/nest/blob/master/packages/microservices/package.json#L36

A simple solution is to import those types from external/kafka.interface.ts into my project, instead of those from kafkajs@2, but this means I could be missing out on some of the newer properties. 

### Describe the solution you'd like

Update microservices kafka.interface to match those from kafkajs@2, or extend the interfaces coming from kafkajs, or allow generics that extend those interfaces. If I have kafkajs@2 installed, it will be using v2 logic meaning the interfaces might be misleading. 

### Teachability, documentation, adoption, migration strategy

Review interfaces copied from kafkajs that haven't been updated, e.g. this one:
https://github.com/tulios/kafkajs/blob/master/types/index.d.ts#L936-L942

### What is the motivation / use case for changing the behavior?

I want to update to kafkajs@2 and leverage the latest capabilities without type conflicts.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting!

> Update microservices kafka.interface to match those from kafkajs@2

Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Fixed in 9.0.5

**Comment by tiagosiebler** [comment]
> Fixed in 9.0.5

Thanks!
