### ISSUE TITLE
Kafka microservice server - parser modifies original message, which breaks retries

### ISSUE THREAD

**Issue by jDzames** [nestjs/nest#9956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I started using Nest recently and I really enjoy it, especially coming from the Spring background to the js/ts world. I stumbled upon this weird issue in the past days and I believe it is a bug. 

Context:
I am using Kafka microservice for consuming Kafka events. If during processing some event exception is thrown and bubbles up, then it is retried a moment later as expected.

Problem:
When an event is retried, then it contains already `parsed` content (`message`), which is again parsed as `value.toString()` and so result event payload is `value: '[object Object]'`.

Seems the problem is with following lines:  https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-kafka.ts#L153 
```ts
    const rawMessage = this.parser.parse<KafkaMessage>(  // parser modifies received param 
      Object.assign(payload.message, {  // topic and partition assigned to the original message
        topic: payload.topic,
        partition: payload.partition,
      }),
    );
```
or with the `kafka-parser` : https://github.com/nestjs/nest/blob/master/packages/microservices/helpers/kafka-parser.ts#L13 .
Simply - it seems that event content is sent to parser and parser modifies it (instead of creating new object somewhere on the way). Hence on retry already parsed data are present and parsing them again doesn't work.

Reproduction code link:
Should be clear without that too, but see link for inspiration if needed (remember to configure client and server based on local kafka).

### Minimum reproduction code

https://codesandbox.io/s/nervous-lichterman-qyyph3?file=/src/app.controller.ts

### Expected behavior

Event content is correctly "parsed" when Kafka event is retried multiple times. 

Proposed solution:
When I tested with custom `kafka server`, where I created new object and sent it to parser ( updated https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-kafka.ts#L153 ), then it worked fine. _Is it possible that the order of objects inside `Object.assign` is the opposite?_ 
Another option is for parser to create a new object and don't modify the received param.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.0.0",
```

### Node.js version

v16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
> Another option is for parser to create a new object and don't modify the received param.

I think this would be the simplest solution. Would you like to create a PR for this issue? 🙌

**Comment by jDzames** [comment]
> > Another option is for parser to create a new object and don't modify the received param.
> 
> I think this would be the simplest solution. Would you like to create a PR for this issue? 🙌

Probably also the most proper one. 
OK, I can try 🙂

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/9996
