### ISSUE TITLE
Fastify version conflict

### ISSUE THREAD

**Issue by mdalaminbey** [nestjs/nest#9957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`FastifyError: fastify-plugin: fastify-accepts - expected '3.x' fastify version, '4.2.1' is installed
    at Object.checkVersion (D:\doatkolom\fix-npm\node_modules\fastify\lib\pluginUtils.js:118:11)
    at Object.registerPlugin (D:\doatkolom\fix-npm\node_modules\fastify\lib\pluginUtils.js:133:16)
    at Boot.override (D:\doatkolom\fix-npm\node_modules\fastify\lib\pluginOverride.js:28:57)
    at Plugin.exec (D:\doatkolom\fix-npm\node_modules\avvio\plugin.js:79:33)
    at Boot.loadPlugin (D:\doatkolom\fix-npm\node_modules\avvio\plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

### Expected behavior

How to fix this issue?

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "nestjs",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/apollo": "^10.0.17",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^10.0.18",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-fastify": "^9.0.4",
    "apollo-server-fastify": "^3.10.0",
    "graphql": "^16.5.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Nest v9 uses fastify v4. The fastify-accepts package you're using only supports up to fastify v3. Replace it with `@fastify/accepts` and you'll be good to go

**Comment by micalevisk** [comment]
@mdalaminbey https://docs.nestjs.com/migration-guide#fastify

**Comment by jmcdo29** [comment]
Also, I just noticed you have `apollo-sever-fastify`, that only supports fastify v3, so it may be the root cause of your problem. Just an FYI

**Comment by mdalaminbey** [comment]
![image](https://user-images.githubusercontent.com/75071900/179795215-160da4cd-a2fd-4d41-a17e-bff1ce691fd5.png)
not fixed.

**Comment by mdalaminbey** [comment]
@jmcdo29 @micalevisk

**Comment by micalevisk** [comment]
run `npm ls fastify-accepts`

**Comment by jmcdo29** [comment]
> Also, I just noticed you have `apollo-sever-fastify`, that only supports fastify v3, so it may be the root cause of your problem. Just an FYI

This is most likely the issue here. Fastify v4 cannot be used with apollo-server-fastify v3. They are not compatible. This is not related to Nest, it's a problem with the asf package. More on the linked issue

https://github.com/apollographql/apollo-server/issues/6576

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2307
