### ISSUE TITLE
Lazy loaded dependencies prevent bundling application using NestJS #9987

### ISSUE THREAD

**Issue by ericmorand** [nestjs/nest#9988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Follow-up to https://github.com/nestjs/nest/issues/9987.

@kamilmysliwiec 

> Please search through some of our old issues on this (this has been discussed several times in the past).

Yes, this has been discussed, but not solved.

You have always debunked the issue with the argument "I recommend that you don't bundle node_modules", which is not your call.

The framework must not come in the way of a step that is not under its responsibility: building. NestJS framework, as it is written today, assumes multiple things:

* A CacheModule may be used
* User of the framework will not want to include node_modules in their bundle

Please re-consider your position. You are in my opinion reproducing exactly the same mistakes that the Symfony maintainers did years ago and they are now in the process of establishing hard-dependencies betweem the framework and the modules that they provide - i.e. they are admitting that their framework is not modular.

### Minimum reproduction code

None

### Expected behavior

Please re-consider your position. And please don't close issues that are not solved. You never solved it, you just provided workarounds in the past.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json

```

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
I've responded to this issue multiple times in the past, not only providing workarounds but also sharing my vision & plans for the future.
