### ISSUE TITLE
Generate type safe react hooks

### ISSUE THREAD

**Issue by JeremySazMining** [nestjs/nest#9998]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Data input and return types are currently shared between frontend and backend via swagger module for controllers. Sharing code of types like DTOs with the frontend for type safety is a pain point.

### Describe the solution you'd like

For Graphql there is graphql-codegen which generates type safe react hooks for the frontend by introspecting the graphql endpoint to query backend data with; I believe they do similiar with other frameworks and react components. I propose something similiar in nestjs to do the same with controllers and react-query, for the frontend to have typesafe react hooks. 

### Teachability, documentation, adoption, migration strategy

Teachability - pretty straightforward, create settings .yml and run commandline command
documentation - graphql-codegen is a good example to template from
adoption - if something like this was done for various frameworks n settings I bet it would be very highly loved
migration - no migration for backend, progressive implementation for frontend is straightforward

### What is the motivation / use case for changing the behavior?

Type safe usage of backend controllers in the frontend. No coding sharing of types, just run generate command to update types on frontend to match the backend. Nestjs already is highly focused on types so this seems like a very fitting step to improve nestjs advantages over anything else.

**Comment by jmcdo29** [comment]
We don't plan to tie ourselves to a single front end library or framework by supporting just it in terms of code generation. If you feel this is something that can live outside of the framework as a library or tool, we encourage you to publish a package for the community to use.
